In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D3 
clinical_train.isnull().sum().sum()

0

### COX assumption in Train data

In [6]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.01 0.91      0.13
LBP_003_PET                                                      0.00 0.98      0.03
LBP_012_CT                                                       0.00 0.95      0.08
LBP_012_PET                                                      0.00 0.97      0.04
LBP_021_CT                                                       0.00 0.97      0.05
LBP_021_PET                                                      0.01 0.92      0.12
LBP_030_CT                                                       0.00 0.99      0.02
LBP_030_PET                                                      0.00 0.99      0.01
LBP_102_CT                                                       0.00 0.99      0.02
LBP_102_PET                                                      0.01 0.94      0.09
LBP_111_CT                                                       0.01 0.94      0.09
LBP_111_PET                                                      0.02 0.90      0.16
LBP_120_CT                                                       0.01 0.93      0.10
LBP_120_PET                                                      0.00 0.97      0.05
LBP_201_CT                                                       0.01 0.94      0.09
LBP_201_PET                                                      0.00 0.99      0.01
LBP_210_CT                                                       0.00 0.98      0.03
LBP_210_PET                                                      0.00 0.97      0.05
LBP_300_CT                                                       0.00 0.98      0.03
LBP_300_PET                                                      0.00 0.98      0.02
MTV                                                              0.00 1.00      0.00
SUVpeak                                                          0.00 1.00      0.00
TLG                                                              0.00 1.00      0.00
age                                                              0.00 0.98      0.03
cavum_oris                                                       0.00 0.97      0.05
charlson                                                         0.00 0.95      0.08
female                                                           0.00 1.00      0.00
first_order_10Percentile_CT                                      0.00 0.97      0.05
first_order_10Percentile_PET                                     0.00 1.00      0.00
first_order_90Percentile_CT                                      0.00 0.96      0.05
first_order_90Percentile_PET                                     0.00 1.00      0.00
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 0.99      0.02
first_order_Entropy_CT_c16                                       0.00 0.99      0.02
first_order_Entropy_PET_b2                                       0.00 1.00      0.01
first_order_Entropy_PET_c04                                      0.00 0.99      0.02
first_order_InterquartileRange_CT                                0.00 0.98      0.03
first_order_InterquartileRange_PET                               0.00 1.00      0.00
first_order_Kurtosis_CT                                          0.00 0.98      0.02
first_order_Kurtosis_PET                                         0.00 0.99      0.02
first_order_Maximum_CT                                           0.01 0.94      0.09
first_order_Maximum_PET                                          0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.01
first_order_MeanAbsoluteDeviation_PET                            0.00 1.00      0.00
first_order_Mean_CT                                              0.00 1.00      0.01
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.99      0.01
first_order_Median_PET                                           0.00 0.99      0.01
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.01 0.93      0.11
first_order_Range_CT                                             0.00 0.96      0.06
first_order_Range_PET                                            0.00 0.99      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.96      0.07
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 0.99      0.01
first_order_RootMeanSquared_CT                                   0.00 0.99      0.01
first_order_RootMeanSquared_PET                                  0.00 1.00      0.00
first_order_Skewness_CT                                          0.03 0.85      0.23
first_order_Skewness_PET                                         0.00 0.97      0.04
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.97      0.04
first_order_Uniformity_CT_c16                                    0.00 0.99      0.02
first_order_Uniformity_PET_b2                                    0.00 0.99      0.01
first_order_Uniformity_PET_c04                                   0.00 0.99      0.01
first_order_Variance_CT                                          0.00 0.99      0.02
first_order_Variance_PET                                         0.00 1.00      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_b2                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_c04                                 0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_b20                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.95      0.07
glcm_ClusterProminence_d_1_PET_b2                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.98      0.03
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.94      0.08
glcm_ClusterShade_d_1_CT_c16                                     0.00 0.94      0.08
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.97      0.04
glcm_ClusterShade_d_1_PET_c04                                    0.01 0.93      0.10
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.98      0.03
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.98      0.02
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.02
glcm_Contrast_d_1_CT_c16                                         0.00 0.98      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 1.00      0.00
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.97      0.05
glcm_Correlation_d_1_CT_c16                                      0.01 0.93      0.10
glcm_Correlation_d_1_PET_b2                                      0.00 0.99      0.01
glcm_Correlation_d_1_PET_c04                                     0.00 0.97      0.05
glcm_DifferenceAverage_d_1_CT_b20                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.99      0.02
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.00
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.02
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 1.00      0.00
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 1.00      0.01
glcm_Id_d_1_CT_b20                                               0.00 1.00      0.00
glcm_Id_d_1_CT_c16                                               0.00 0.99      0.02
glcm_Id_d_1_PET_b2                                               0.00 0.99      0.02
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_c16                                              0.00 0.99      0.02
glcm_Idm_d_1_PET_b2                                              0.00 0.99      0.01
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Idmn_d_1_CT_c16                                             0.00 0.99      0.02
glcm_Idmn_d_1_PET_b2                                             0.00 0.95      0.08
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idn_d_1_CT_c16                                              0.00 0.99      0.02
glcm_Idn_d_1_PET_b2                                              0.00 0.98      0.03
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Imc1_d_1_CT_c16                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_b2                                             0.00 0.96      0.06
glcm_Imc1_d_1_PET_c04                                            0.00 1.00      0.01
glcm_Imc2_d_1_CT_b20                                             0.00 0.96      0.05
glcm_Imc2_d_1_CT_c16                                             0.00 0.97      0.05
glcm_Imc2_d_1_PET_b2                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.97      0.04
glcm_InverseVariance_d_1_CT_b20                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_b2                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.01
glcm_JointAverage_d_1_CT_b20                                     0.00 0.99      0.01
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 1.00      0.00
glcm_JointEnergy_d_1_CT_b20                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_c04                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_b20                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.98      0.02
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 1.00      0.00
glcm_MCC_d_1_CT_b20                                              0.01 0.93      0.10
glcm_MCC_d_1_CT_c16                                              0.00 0.99      0.02
glcm_MCC_d_1_PET_b2                                              0.00 0.97      0.05
glcm_MCC_d_1_PET_c04                                             0.00 0.99      0.01
glcm_MaximumProbability_d_1_CT_b20                               0.01 0.94      0.09
glcm_MaximumProbability_d_1_CT_c16                               0.00 0.99      0.01
glcm_MaximumProbability_d_1_PET_b2                               0.02 0.89      0.16
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.98      0.02
glcm_SumAverage_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 1.00      0.00
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.98      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumSquares_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumSquares_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumSquares_d_1_PET_c04                                      0.00 0.98      0.02
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.96      0.05
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.05
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 1.00      0.00
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.98      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 1.00      0.00
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_CT_c16                               0.01 0.93      0.11
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.96      0.05
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.98      0.03
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.97      0.05
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 1.00      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 1.00      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 1.00      0.00
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 1.00      0.00
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 1.00      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.96      0.06
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 0.98      0.04
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.97      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.96      0.07
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.96      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.03
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.98      0.02
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 1.00      0.00
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.07
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.01 0.94      0.10
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.01 0.93      0.11
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.98      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.98      0.03
glrlm_GrayLevelVariance_CT_b20                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_c16                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.02

In [7]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [8]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic      p  -log2(p)
LBP_003_CT                                                       0.06   0.81      0.31
LBP_003_PET                                                      0.76   0.38      1.38
LBP_012_CT                                                       0.13   0.72      0.48
LBP_012_PET                                                      0.27   0.60      0.73
LBP_021_CT                                                       0.56   0.45      1.14
LBP_021_PET                                                      0.00   0.97      0.04
LBP_030_CT                                                       0.04   0.83      0.26
LBP_030_PET                                                      0.06   0.81      0.30
LBP_102_CT                                                       0.00   1.00      0.00
LBP_102_PET                                                      0.02   0.90      0.15
LBP_111_CT                                                       0.14   0.71      0.49
LBP_111_PET                                                      0.51   0.47      1.08
LBP_120_CT                                                       0.51   0.47      1.08
LBP_120_PET                                                      0.14   0.71      0.50
LBP_201_CT                                                       0.27   0.61      0.72
LBP_201_PET                                                      0.70   0.40      1.31
LBP_210_CT                                                       1.25   0.26      1.92
LBP_210_PET                                                      0.00   1.00      0.00
LBP_300_CT                                                       0.01   0.91      0.14
LBP_300_PET                                                      0.01   0.93      0.10
MTV                                                              0.03   0.86      0.22
SUVpeak                                                          0.00   0.99      0.02
TLG                                                              0.13   0.72      0.48
age                                                              0.14   0.71      0.50
cavum_oris                                                       0.64   0.42      1.24
charlson                                                         7.69   0.01      7.49
female                                                           0.44   0.51      0.98
first_order_10Percentile_CT                                      0.00   0.98      0.03
first_order_10Percentile_PET                                     0.07   0.78      0.35
first_order_90Percentile_CT                                      2.21   0.14      2.87
first_order_90Percentile_PET                                     0.00   0.95      0.07
first_order_Energy_CT                                            0.01   0.94      0.09
first_order_Energy_PET                                           0.19   0.66      0.59
first_order_Entropy_CT_b20                                       0.00   0.96      0.05
first_order_Entropy_CT_c16                                       0.07   0.79      0.34
first_order_Entropy_PET_b2                                       0.00   0.98      0.04
first_order_Entropy_PET_c04                                      0.00   0.98      0.03
first_order_InterquartileRange_CT                                0.48   0.49      1.04
first_order_InterquartileRange_PET                               0.00   0.99      0.02
first_order_Kurtosis_CT                                          0.57   0.45      1.15
first_order_Kurtosis_PET                                         0.00   0.99      0.02
first_order_Maximum_CT                                           0.15   0.70      0.52
first_order_Maximum_PET                                          0.00   0.96      0.06
first_order_MeanAbsoluteDeviation_CT                             0.04   0.83      0.26
first_order_MeanAbsoluteDeviation_PET                            0.01   0.94      0.08
first_order_Mean_CT                                              0.00   0.98      0.03
first_order_Mean_PET                                             0.00   0.96      0.05
first_order_Median_CT                                            0.26   0.61      0.71
first_order_Median_PET                                           0.00   0.98      0.03
first_order_Minimum_CT                                           0.05   0.83      0.27
first_order_Minimum_PET                                          0.49   0.48      1.05
first_order_Range_CT                                             0.17   0.68      0.56
first_order_Range_PET                                            0.00   1.00      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.05   0.82      0.29
first_order_RobustMeanAbsoluteDeviation_PET                      0.00   0.95      0.08
first_order_RootMeanSquared_CT                                   0.00   0.96      0.06
first_order_RootMeanSquared_PET                                  0.00   0.99      0.02
first_order_Skewness_CT                                          0.37   0.54      0.88
first_order_Skewness_PET                                         0.08   0.78      0.37
first_order_TotalEnergy_CT                                       0.01   0.94      0.09
first_order_TotalEnergy_PET                                      0.19   0.66      0.59
first_order_Uniformity_CT_b20                                    0.00   0.96      0.07
first_order_Uniformity_CT_c16                                    0.01   0.92      0.12
first_order_Uniformity_PET_b2                                    0.12   0.73      0.45
first_order_Uniformity_PET_c04                                   0.01   0.94      0.10
first_order_Variance_CT                                          0.00   1.00      0.00
first_order_Variance_PET                                         0.00   0.99      0.02
glcm_Autocorrelation_d_1_CT_b20                                  0.15   0.70      0.51
glcm_Autocorrelation_d_1_CT_c16                                  0.01   0.91      0.14
glcm_Autocorrelation_d_1_PET_b2                                  0.00   0.98      0.03
glcm_Autocorrelation_d_1_PET_c04                                 0.03   0.87      0.20
glcm_ClusterProminence_d_1_CT_b20                                0.00   0.94      0.08
glcm_ClusterProminence_d_1_CT_c16                                0.01   0.93      0.10
glcm_ClusterProminence_d_1_PET_b2                                0.10   0.75      0.41
glcm_ClusterProminence_d_1_PET_c04                               0.17   0.68      0.56
glcm_ClusterShade_d_1_CT_b20                                     0.98   0.32      1.63
glcm_ClusterShade_d_1_CT_c16                                     0.00   0.96      0.06
glcm_ClusterShade_d_1_PET_b2                                     0.75   0.39      1.37
glcm_ClusterShade_d_1_PET_c04                                    0.33   0.57      0.82
glcm_ClusterTendency_d_1_CT_b20                                  0.01   0.91      0.14
glcm_ClusterTendency_d_1_CT_c16                                  0.01   0.94      0.09
glcm_ClusterTendency_d_1_PET_b2                                  0.00   0.97      0.05
glcm_ClusterTendency_d_1_PET_c04                                 0.09   0.76      0.40
glcm_Contrast_d_1_CT_b20                                         0.00   0.95      0.07
glcm_Contrast_d_1_CT_c16                                         0.03   0.86      0.21
glcm_Contrast_d_1_PET_b2                                         0.04   0.83      0.26
glcm_Contrast_d_1_PET_c04                                        0.01   0.94      0.09
glcm_Correlation_d_1_CT_b20                                      0.44   0.51      0.98
glcm_Correlation_d_1_CT_c16                                      0.72   0.40      1.33
glcm_Correlation_d_1_PET_b2                                      0.04   0.85      0.23
glcm_Correlation_d_1_PET_c04                                     0.02   0.88      0.18
glcm_DifferenceAverage_d_1_CT_b20                                0.00   0.98      0.02
glcm_DifferenceAverage_d_1_CT_c16                                0.00   0.97      0.05
glcm_DifferenceAverage_d_1_PET_b2                                0.00   0.98      0.03
glcm_DifferenceAverage_d_1_PET_c04                               0.00   0.96      0.06
glcm_DifferenceEntropy_d_1_CT_b20                                0.01   0.92      0.12
glcm_DifferenceEntropy_d_1_CT_c16                                0.00   0.95      0.08
glcm_DifferenceEntropy_d_1_PET_b2                                0.04   0.83      0.26
glcm_DifferenceEntropy_d_1_PET_c04                               0.13   0.72      0.47
glcm_DifferenceVariance_d_1_CT_b20                               0.01   0.93      0.11
glcm_DifferenceVariance_d_1_CT_c16                               0.04   0.84      0.26
glcm_DifferenceVariance_d_1_PET_b2                               0.10   0.76      0.40
glcm_DifferenceVariance_d_1_PET_c04                              0.08   0.77      0.37
glcm_Id_d_1_CT_b20                                               0.00   0.95      0.07
glcm_Id_d_1_CT_c16                                               0.00   0.98      0.02
glcm_Id_d_1_PET_b2                                               0.00   0.96      0.05
glcm_Id_d_1_PET_c04                                              0.01   0.91      0.14
glcm_Idm_d_1_CT_b20                                              0.00   0.95      0.08
glcm_Idm_d_1_CT_c16                                              0.00   1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00   0.99      0.02
glcm_Idm_d_1_PET_c04                                             0.01   0.93      0.11
glcm_Idmn_d_1_CT_b20                                             0.02   0.90      0.16
glcm_Idmn_d_1_CT_c16                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_b2                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_c04                                            0.00   0.95      0.08
glcm_Idn_d_1_CT_b20                                              0.01   0.92      0.12
glcm_Idn_d_1_CT_c16                                              0.00   0.98      0.02
glcm_Idn_d_1_PET_b2                                              0.23   0.63      0.66
glcm_Idn_d_1_PET_c04                                             0.01   0.94      0.08
glcm_Imc1_d_1_CT_b20                                             0.80   0.37      1.43
glcm_Imc1_d_1_CT_c16                                             0.08   0.78      0.37
glcm_Imc1_d_1_PET_b2                                             0.10   0.76      0.41
glcm_Imc1_d_1_PET_c04                                            0.02   0.90      0.16
glcm_Imc2_d_1_CT_b20                                             0.03   0.86      0.22
glcm_Imc2_d_1_CT_c16                                             0.71   0.40      1.32
glcm_Imc2_d_1_PET_b2                                             0.08   0.78      0.36
glcm_Imc2_d_1_PET_c04                                            0.01   0.92      0.12
glcm_InverseVariance_d_1_CT_b20                                  0.02   0.88      0.19
glcm_InverseVariance_d_1_CT_c16                                  0.02   0.89      0.17
glcm_InverseVariance_d_1_PET_b2                                  0.04   0.85      0.23
glcm_InverseVariance_d_1_PET_c04                                 0.06   0.80      0.31
glcm_JointAverage_d_1_CT_b20                                     0.06   0.81      0.30
glcm_JointAverage_d_1_CT_c16                                     0.04   0.85      0.23
glcm_JointAverage_d_1_PET_b2                                     0.00   0.96      0.06
glcm_JointAverage_d_1_PET_c04                                    0.00   0.98      0.03
glcm_JointEnergy_d_1_CT_b20                                      0.03   0.87      0.20
glcm_JointEnergy_d_1_CT_c16                                      0.01   0.93      0.10
glcm_JointEnergy_d_1_PET_b2                                      0.16   0.69      0.53
glcm_JointEnergy_d_1_PET_c04                                     0.00   0.98      0.02
glcm_JointEntropy_d_1_CT_b20                                     0.01   0.90      0.15
glcm_JointEntropy_d_1_CT_c16                                     0.08   0.78      0.36
glcm_JointEntropy_d_1_PET_b2                                     0.00   0.96      0.06
glcm_JointEntropy_d_1_PET_c04                                    0.00   0.96      0.06
glcm_MCC_d_1_CT_b20                                              0.40   0.53      0.92
glcm_MCC_d_1_CT_c16                                              0.06   0.81      0.30
glcm_MCC_d_1_PET_b2                                              0.01   0.92      0.12
glcm_MCC_d_1_PET_c04                                             0.02   0.88      0.19
glcm_MaximumProbability_d_1_CT_b20                               0.04   0.85      0.23
glcm_MaximumProbability_d_1_CT_c16                               0.10   0.76      0.40
glcm_MaximumProbability_d_1_PET_b2                               0.13   0.71      0.49
glcm_MaximumProbability_d_1_PET_c04                              0.00   1.00      0.00
glcm_SumAverage_d_1_CT_b20                                       0.06   0.81      0.30
glcm_SumAverage_d_1_CT_c16                                       0.04   0.85      0.23
glcm_SumAverage_d_1_PET_b2                                       0.00   0.96      0.06
glcm_SumAverage_d_1_PET_c04                                      0.00   0.98      0.03
glcm_SumEntropy_d_1_CT_b20                                       0.00   0.99      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.08   0.78      0.36
glcm_SumEntropy_d_1_PET_b2                                       0.00   0.97      0.05
glcm_SumEntropy_d_1_PET_c04                                      0.01   0.93      0.10
glcm_SumSquares_d_1_CT_b20                                       0.01   0.92      0.12
glcm_SumSquares_d_1_CT_c16                                       0.00   0.96      0.06
glcm_SumSquares_d_1_PET_b2                                       0.00   0.96      0.05
glcm_SumSquares_d_1_PET_c04                                      0.09   0.76      0.39
gldm_DependenceEntropy_d_1_CT_b20                                0.21   0.65      0.62
gldm_DependenceEntropy_d_1_CT_c16                                0.11   0.75      0.42
gldm_DependenceEntropy_d_1_PET_b2                                0.06   0.81      0.30
gldm_DependenceEntropy_d_1_PET_c04                               0.03   0.87      0.20
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.14   0.70      0.51
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.03   0.86      0.21
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.34   0.56      0.84
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.05   0.82      0.28
gldm_DependenceNonUniformity_d_1_CT_b20                          0.02   0.90      0.15
gldm_DependenceNonUniformity_d_1_CT_c16                          2.56   0.11      3.19
gldm_DependenceNonUniformity_d_1_PET_b2                          0.04   0.85      0.24
gldm_DependenceNonUniformity_d_1_PET_c04                         0.11   0.74      0.42
gldm_DependenceVariance_d_1_CT_b20                               0.83   0.36      1.47
gldm_DependenceVariance_d_1_CT_c16                               0.06   0.81      0.30
gldm_DependenceVariance_d_1_PET_b2                               0.28   0.60      0.75
gldm_DependenceVariance_d_1_PET_c04                              0.56   0.46      1.13
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.35   0.55      0.86
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.36   0.55      0.87
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.20   0.65      0.61
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00   0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00   1.00      0.00
gldm_GrayLevelVariance_d_1_CT_c16                                0.00   1.00      0.01
gldm_GrayLevelVariance_d_1_PET_b2                                0.00   0.98      0.03
gldm_GrayLevelVariance_d_1_PET_c04                               0.04   0.84      0.24
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.16   0.69      0.54
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.01   0.91      0.14
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00   0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.04   0.85      0.24
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.01   0.91      0.14
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.02   0.89      0.16
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.05   0.82      0.28
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.02   0.89      0.17
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.69   0.41      1.30
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00   0.95      0.07
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.04   0.85      0.24
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00   0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.02   0.89      0.17
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.04   0.84      0.24
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.10   0.75      0.41
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.51   0.48      1.07
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.03   0.87      0.20
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00   0.97      0.04
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.01   0.94      0.09
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.50   0.48      1.06
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.01   0.91      0.14
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.10   0.75      0.42
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.10   0.76      0.40
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.03   0.87      0.20
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.27   0.60      0.74
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.03   0.87      0.20
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.05   0.82      0.28
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01   0.92      0.12
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.02   0.88      0.19
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.20   0.66      0.61
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.03   0.87      0.19
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00   0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00   0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.46   0.50      1.01
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.03   0.87      0.21
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.04   0.84      0.25
glrlm_GrayLevelNonUniformity_CT_b20                              0.01   0.93      0.10
glrlm_GrayLevelNonUniformity_CT_c16                              1.08   0.30      1.74

In [9]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['charlson', 'glszm_LargeAreaEmphasis_CT_c16',
       'glszm_LargeAreaLowGrayLevelEmphasis_CT_c16',
       'glszm_ZoneVariance_CT_c16', 'ngtdm_Busyness_d_1_PET_b2'],
      dtype='object')

## Test dataset: MAASTRO

In [10]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [11]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [12]:
# Need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [13]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [14]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [15]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [16]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# Set y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [17]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [18]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [19]:
# Change the name of a column 'DFS_event' in the clincial_test 
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [20]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = StandardScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [23]:
# Divide the X_MAASTRO into numerical part and categorical part 
X_MAASTRO_categorical = X_MAASTRO[categorical_columns]
X_MAASTRO_numeric = X_MAASTRO.drop(categorical_columns, axis=1)

# Save the column name and index of the numeric part
X_MAASTRO_numeric_columns = X_MAASTRO_numeric.columns
X_MAASTRO_numeric_index = X_MAASTRO_numeric.index

In [24]:
# Standardize the numeric part 
X_MAASTRO_numeric_std = scaler.transform(X_MAASTRO_numeric)

# Change the standardized part into a dataframe 
X_MAASTRO_numeric_std = pd.DataFrame(X_MAASTRO_numeric_std, columns=X_MAASTRO_numeric_columns, index=X_MAASTRO_numeric_index)

# Concat the standardized part with the categorical part 
X_MAASTRO_std = pd.concat([X_MAASTRO_categorical, X_MAASTRO_numeric_std], axis=1)

# Change the column order of X_MAASTRO_std
X_MAASTRO_std = X_MAASTRO_std[original_X.columns]

In [25]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [26]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 18:35:39,653] A new study created in memory with name: no-name-30ce43f1-6d8c-4046-a577-c0cac58a26d8
python(25199) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-16 18:35:41,472] Trial 0 failed with parameters: {} because of the following error: LinAlgError('Matrix is singular.').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_24196/2750526300.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 449, in fit
    delta = solve(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 220, in solve
    _solve_check(n, info)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[W 2024-04-16 18:35:41,492] Trial 0 failed with value None.

LinAlgError: Matrix is singular.

In [27]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {}

In [28]:
# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [29]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [30]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [31]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

LinAlgError: Matrix is singular.

In [35]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [32]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:21:22,369] A new study created in memory with name: no-name-df37f121-e1b2-4210-b5cb-556856467b48

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-16 20:21:22,644] A new study created in memory with name: no-name-4305f0e0-6ce8-4ee1-8ba8-6aa6cc48aefa

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7267441860465116
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:21:22,639] Trial 0 finished with value: 0.6330033562371864 and parameters: {}. Best is trial 0 with value: 0.6330033562371864.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6330033562371864], datetime_start=datetime.datetime(2024, 4, 16, 20, 21, 22, 431844), datetime_complete=datetime.datetime(2024, 4, 16, 20, 21, 22, 639209), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6330033562371864

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709766223185
Fold 2 IBS: 0.2320398804259208
Fold 3 IBS: 0.22898186781735627
Fold 4 IBS: 0.24197476635329754
Fold 5 IBS: 0.22939558893495351
[I 2024-04-16 20:21:22,902] Trial 0 finished with value: 0.235927840238752 and parameters: {}. Best is trial 0 with value: 0.235927840238752.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.235927840238752], datetime_start=datetime.datetime(2024, 4, 16, 20, 21, 22, 679406), datetime_complete=datetime.datetime(2024, 4, 16, 20, 21, 22, 902279), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.235927840238752

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.633
train_ibs:  0.236

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.542

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:21:24,727] A new study created in memory with name: no-name-b87c1f42-3af2-4124-999d-3326178a69d3

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.4553191489361702
Fold 4 C-index: 0.4448669201520912

[I 2024-04-16 20:21:26,576] A new study created in memory with name: no-name-2bd4f78b-309c-4ca5-b53b-13f1aff7614f

Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:21:26,562] Trial 0 finished with value: 0.5064895572867079 and parameters: {}. Best is trial 0 with value: 0.5064895572867079.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5064895572867079], datetime_start=datetime.datetime(2024, 4, 16, 20, 21, 24, 754268), datetime_complete=datetime.datetime(2024, 4, 16, 20, 21, 26, 562524), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5064895572867079

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.47722249153378843
Fold 2 IBS: 0.3559505337162963
Fold 3 IBS: 0.47560772148855335
Fold 4 IBS: 0.4696450550522016
Fold 5 IBS: 0.3821180064513121
[I 2024-04-16 20:21:28,369] Trial 0 finished with value: 0.4321087616484304 and parameters: {}. Best is trial 0 with value: 0.4321087616484304.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.4321087616484304], datetime_start=datetime.datetime(2024, 4, 16, 20, 21, 26, 616131), datetime_complete=datetime.datetime(2024, 4, 16, 20, 21, 28, 369773), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.4321087616484304

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.506
train_ibs:  0.432

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.545

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.431

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:21:29,301] A new study created in memory with name: no-name-68c40b1f-e82e-4f9e-814b-d68f3f79bd8c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.425531914893617
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:21:30,769] Trial 0 finished with value: 0.49605583901155403 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.49605583901155403.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.44680851063829785
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:21:32,046] Trial 1 finished with value: 0.5079232965749896 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.5079232965749896.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.44680851063829785
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:21:33,304] Trial 2 finished with value: 0.509444209122518 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.509444209122518.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.5813953488372093
Fold 3 C-index: 0.4340425531914894
Fold 4 C-index: 0.4790874524714829
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 20:21:34,530] Trial 3 finished with value: 0.4881498086870856 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.509444209122518.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.425531914893617
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:21:35,940] Trial 4 finished with value: 0.49685265176055804 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.509444209122518.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.4297872340425532
Fold 4 C-index: 0.49049429657794674
Fold 5 C-index: 0.5236051502145923
[I 2024-04-16 20:21:37,138] Trial 5 finished with value: 0.48954017627943697 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.509444209122518.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.4808510638297872
Fold 4 C-index: 0.4600760456273764
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:21:38,775] Trial 6 finished with value: 0.5130258214138805 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.5130258214138805.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.4297872340425532
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:21:39,982] Trial 7 finished with value: 0.4969069028413413 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.5130258214138805.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.425531914893617
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:21:41,150] Trial 8 finished with value: 0.4885548431494618 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.5130258214138805.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.42127659574468085
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.5236051502145923
[I 2024-04-16 20:21:42,358] Trial 9 finished with value: 0.4901921303916348 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.5130258214138805.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.48936170212765956
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:21:44,376] Trial 10 finished with value: 0.5132070365259265 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 10 with value: 0.5132070365259265.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.46382978723404256
Fold 4 C-index: 0.44866920152091255
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:21:46,307] Trial 11 finished with value: 0.5074017536231474 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 10 with value: 0.5132070365259265.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.4723404255319149
Fold 4 C-index: 0.4524714828897338
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:21:48,355] Trial 12 finished with value: 0.5090059684577736 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 10 with value: 0.5132070365259265.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.41702127659574467
Fold 4 C-index: 0.49049429657794674
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:21:50,214] Trial 13 finished with value: 0.49999393161766326 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 10 with value: 0.5132070365259265.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:21:50,748] Trial 14 finished with value: 0.5882027806770826 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 14 with value: 0.5882027806770826.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 20:21:51,016] Trial 15 finished with value: 0.6345879709390051 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 15 with value: 0.6345879709390051.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:21:51,241] Trial 16 finished with value: 0.6345047956387423 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 15 with value: 0.6345879709390051.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:21:51,739] Trial 17 finished with value: 0.5873444115783701 and parameters: {'l1_ratio': 0.10932144510738274}. Best is trial 15 with value: 0.6345879709390051.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 20:21:51,966] Trial 18 finished with value: 0.6346095898895594 and parameters: {'l1_ratio': 0.013003332120057056}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:21:52,227] Trial 19 finished with value: 0.6345047956387423 and parameters: {'l1_ratio': 0.004308240931741479}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.4595744680851064
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:21:53,201] Trial 20 finished with value: 0.539078089557691 and parameters: {'l1_ratio': 0.20815195211742094}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 20:21:53,583] Trial 21 finished with value: 0.6338127771405555 and parameters: {'l1_ratio': 0.021025450652628987}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:21:54,404] Trial 22 finished with value: 0.5848924169816497 and parameters: {'l1_ratio': 0.11554413154907563}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049

Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:21:54,641] Trial 23 finished with value: 0.6345047956387423 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:21:55,438] Trial 24 finished with value: 0.562741272217538 and parameters: {'l1_ratio': 0.17890880660260244}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.42127659574468085
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:21:56,818] Trial 25 finished with value: 0.5013470950486626 and parameters: {'l1_ratio': 0.3507057512687868}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:21:57,125] Trial 26 finished with value: 0.6109514328182738 and parameters: {'l1_ratio': 0.08098111328264362}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.44680851063829785
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:21:58,071] Trial 27 finished with value: 0.5079232965749896 and parameters: {'l1_ratio': 0.2857736050228499}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:21:58,708] Trial 28 finished with value: 0.5651569103390187 and parameters: {'l1_ratio': 0.15645255996762497}. Best is trial 18 with value: 0.6346095898895594.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:21:58,895] Trial 29 finished with value: 0.6371483407104571 and parameters: {'l1_ratio': 0.06462618263940904}. Best is trial 29 with value: 0.6371483407104571.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:21:59,197] Trial 30 finished with value: 0.6101546200692698 and parameters: {'l1_ratio': 0.07733316154712004}. Best is trial 29 with value: 0.6371483407104571.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:21:59,389] Trial 31 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.04614974199010863}. Best is trial 29 with value: 0.6371483407104571.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.4425531914893617
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:00,251] Trial 32 finished with value: 0.5086442392926559 and parameters: {'l1_ratio': 0.26836278041021827}. Best is trial 29 with value: 0.6371483407104571.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.55893536121673
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:22:00,810] Trial 33 finished with value: 0.5659173666127829 and parameters: {'l1_ratio': 0.1522649277701571}. Best is trial 29 with value: 0.6371483407104571.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:00,981] Trial 34 finished with value: 0.6371483407104571 and parameters: {'l1_ratio': 0.05963918498758472}. Best is trial 29 with value: 0.6371483407104571.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.44680851063829785
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:01,868] Trial 35 finished with value: 0.509444209122518 and parameters: {'l1_ratio': 0.22717638914595276}. Best is trial 29 with value: 0.6371483407104571.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:02,040] Trial 36 finished with value: 0.6380067098091695 and parameters: {'l1_ratio': 0.06494322186230238}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.5813953488372093
Fold 3 C-index: 0.4340425531914894
Fold 4 C-index: 0.49049429657794674
Fold 5 C-index: 0.5364806866952789
[I 2024-04-16 20:22:03,039] Trial 37 finished with value: 0.4921479157058032 and parameters: {'l1_ratio': 0.5802102856643269}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.42127659574468085
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:03,950] Trial 38 finished with value: 0.5013470950486626 and parameters: {'l1_ratio': 0.347504487233298}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.44680851063829785
Fold 4 C-index: 0.532319391634981
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:04,755] Trial 39 finished with value: 0.5086837528487538 and parameters: {'l1_ratio': 0.24296619185977542}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:04,932] Trial 40 finished with value: 0.6371483407104571 and parameters: {'l1_ratio': 0.0629759352558336}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:05,116] Trial 41 finished with value: 0.6380067098091695 and parameters: {'l1_ratio': 0.06725532373034453}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:05,510] Trial 42 finished with value: 0.5857507860803622 and parameters: {'l1_ratio': 0.139593801081577}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:05,683] Trial 43 finished with value: 0.6371483407104571 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:22:06,238] Trial 44 finished with value: 0.5627776286927777 and parameters: {'l1_ratio': 0.16786154387705365}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.4595744680851064
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:06,942] Trial 45 finished with value: 0.5390997085082454 and parameters: {'l1_ratio': 0.2015877049263835}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4581673306772908
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:07,220] Trial 46 finished with value: 0.6109514328182738 and parameters: {'l1_ratio': 0.07853350716787645}. Best is trial 36 with value: 0.6380067098091695.

Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:07,654] Trial 47 finished with value: 0.5857507860803622 and parameters: {'l1_ratio': 0.1298882306515754}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.42127659574468085
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:22:08,957] Trial 48 finished with value: 0.4968347571550146 and parameters: {'l1_ratio': 0.758842798046546}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.5813953488372093
Fold 3 C-index: 0.42127659574468085
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:22:09,970] Trial 49 finished with value: 0.4884789731181242 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.5813953488372093
Fold 3 C-index: 0.4340425531914894
Fold 4 C-index: 0.4790874524714829
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 20:22:11,214] Trial 50 finished with value: 0.4881498086870856 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:11,439] Trial 51 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.05834367724630557}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:11,722] Trial 52 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.051190601441181885}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:22:12,274] Trial 53 finished with value: 0.589857962524799 and parameters: {'l1_ratio': 0.09922173578137658}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:12,519] Trial 54 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.05005229766616962}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:22:13,149] Trial 55 finished with value: 0.5619444594685341 and parameters: {'l1_ratio': 0.18617369447915716}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:13,635] Trial 56 finished with value: 0.5857507860803622 and parameters: {'l1_ratio': 0.1207977286137723}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.5813953488372093
Fold 3 C-index: 0.4297872340425532
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:14,744] Trial 57 finished with value: 0.4937124899974966 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:14,925] Trial 58 finished with value: 0.6372462535354052 and parameters: {'l1_ratio': 0.03680667291809313}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.43829787234042555
Fold 4 C-index: 0.5133079847908745
Fold 5 C-index: 0.5364806866952789
[I 2024-04-16 20:22:15,871] Trial 59 finished with value: 0.5038929812690991 and parameters: {'l1_ratio': 0.3151246612562087}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:22:16,051] Trial 60 finished with value: 0.634671146239268 and parameters: {'l1_ratio': 0.029763005782680887}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:16,342] Trial 61 finished with value: 0.6077858007728122 and parameters: {'l1_ratio': 0.09196181159812378}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:16,526] Trial 62 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.04255629403786997}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:16,979] Trial 63 finished with value: 0.5857507860803622 and parameters: {'l1_ratio': 0.1273111601572329}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:17,278] Trial 64 finished with value: 0.6101546200692698 and parameters: {'l1_ratio': 0.0870956252537092}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4262948207171315
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.4127659574468085
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:22:18,600] Trial 65 finished with value: 0.5006568989095356 and parameters: {'l1_ratio': 0.8815318180352767}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:22:18,812] Trial 66 finished with value: 0.6345047956387423 and parameters: {'l1_ratio': 0.000403136638176628}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:19,009] Trial 67 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.0584367944883113}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5475285171102662
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:22:19,590] Trial 68 finished with value: 0.5627776286927777 and parameters: {'l1_ratio': 0.16834508360761385}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 20:22:19,787] Trial 69 finished with value: 0.6355295153379804 and parameters: {'l1_ratio': 0.031871009505959}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.4553191489361702

Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:20,593] Trial 70 finished with value: 0.5374665694541395 and parameters: {'l1_ratio': 0.21935825140122497}. Best is trial 36 with value: 0.6380067098091695.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:22:20,779] Trial 71 finished with value: 0.638865078907882 and parameters: {'l1_ratio': 0.07142581107906198}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:22:21,101] Trial 72 finished with value: 0.6117734454417466 and parameters: {'l1_ratio': 0.07548295125203591}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:21,553] Trial 73 finished with value: 0.5873444115783701 and parameters: {'l1_ratio': 0.10370470728163014}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:22,009] Trial 74 finished with value: 0.5865475988293662 and parameters: {'l1_ratio': 0.1427648037074275}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 20:22:22,223] Trial 75 finished with value: 0.6338127771405555 and parameters: {'l1_ratio': 0.02257566409390399}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:22:22,422] Trial 76 finished with value: 0.638865078907882 and parameters: {'l1_ratio': 0.07147505974488672}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:22,872] Trial 77 finished with value: 0.5873444115783701 and parameters: {'l1_ratio': 0.10289918967534076}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.46382978723404256
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:22:23,592] Trial 78 finished with value: 0.5431668041324317 and parameters: {'l1_ratio': 0.19332018870214612}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:24,030] Trial 79 finished with value: 0.5857507860803622 and parameters: {'l1_ratio': 0.13147783398572757}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.44680851063829785
Fold 4 C-index: 0.5285171102661597
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:22:24,939] Trial 80 finished with value: 0.5079232965749896 and parameters: {'l1_ratio': 0.24837404569215596}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:25,147] Trial 81 finished with value: 0.6380067098091695 and parameters: {'l1_ratio': 0.06729864418576588}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:22:25,344] Trial 82 finished with value: 0.634671146239268 and parameters: {'l1_ratio': 0.025512401946118306}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:22:25,738] Trial 83 finished with value: 0.6117734454417466 and parameters: {'l1_ratio': 0.07462143955081717}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:26,634] Trial 84 finished with value: 0.5873444115783701 and parameters: {'l1_ratio': 0.10829018940479015}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:22:26,985] Trial 85 finished with value: 0.6345047956387423 and parameters: {'l1_ratio': 0.000669393137596036}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:22:27,687] Trial 86 finished with value: 0.563538084966542 and parameters: {'l1_ratio': 0.16059885852912834}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:27,900] Trial 87 finished with value: 0.6380067098091695 and parameters: {'l1_ratio': 0.06668902664314812}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:28,106] Trial 88 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.04202815991943468}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 20:22:28,532] Trial 89 finished with value: 0.5865475988293662 and parameters: {'l1_ratio': 0.14250634338664667}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:22:28,872] Trial 90 finished with value: 0.6117734454417466 and parameters: {'l1_ratio': 0.07573544676892142}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:29,093] Trial 91 finished with value: 0.6380067098091695 and parameters: {'l1_ratio': 0.0663092115285621}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:22:29,276] Trial 92 finished with value: 0.634671146239268 and parameters: {'l1_ratio': 0.030559621106688}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:22:29,718] Trial 93 finished with value: 0.5848924169816497 and parameters: {'l1_ratio': 0.11375789473899037}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:29,877] Trial 94 finished with value: 0.6371483407104571 and parameters: {'l1_ratio': 0.062007220710757545}. Best is trial 71 with value: 0.638865078907882.

Fold 1 C-index: 0.4541832669322709
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 20:22:30,179] Trial 95 finished with value: 0.6101546200692698 and parameters: {'l1_ratio': 0.09044181077412222}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 20:22:30,354] Trial 96 finished with value: 0.6338127771405555 and parameters: {'l1_ratio': 0.016480724948517787}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.42231075697211157
Fold 2 C-index: 0.5775193798449613
Fold 3 C-index: 0.425531914893617
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.5236051502145923
[I 2024-04-16 20:22:31,334] Trial 97 finished with value: 0.48865275597441 and parameters: {'l1_ratio': 0.4965881146918674}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:22:31,599] Trial 98 finished with value: 0.6363878844366928 and parameters: {'l1_ratio': 0.048489144812018214}. Best is trial 71 with value: 0.638865078907882.
Fold 1 C-index: 0.4302788844621514
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745

[I 2024-04-16 20:22:32,277] A new study created in memory with name: no-name-fe7daa92-4435-406d-aed2-ee2f3f1e0046

Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 20:22:32,268] Trial 99 finished with value: 0.5619444594685341 and parameters: {'l1_ratio': 0.18231504707202245}. Best is trial 71 with value: 0.638865078907882.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.638865078907882], datetime_start=datetime.datetime(2024, 4, 16, 20, 22, 20, 598857), datetime_complete=datetime.datetime(2024, 4, 16, 20, 22, 20, 779696), params={'l1_ratio': 0.07142581107906198}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=71, value=None)


* Best Score for C-index:
 0.638865078907882

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.46400927837705297
Fold 2 IBS: 0.36326713437890934
Fold 3 IBS: 0.4495531678028146
Fold 4 IBS: 0.4230153149702206
Fold 5 IBS: 0.37804967345141277
[I 2024-04-16 20:22:33,780] Trial 0 finished with value: 0.41557891379608203 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.41557891379608203.
Fold 1 IBS: 0.47153796586527336
Fold 2 IBS: 0.35072914215914724
Fold 3 IBS: 0.40203663354608876
Fold 4 IBS: 0.3933450035709491
Fold 5 IBS: 0.3584191801705698
[I 2024-04-16 20:22:35,351] Trial 1 finished with value: 0.39521358506240567 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.39521358506240567.
Fold 1 IBS: 0.4683009668637043
Fold 2 IBS: 0.34248170696972846
Fold 3 IBS: 0.38200623914650983
Fold 4 IBS: 0.37349309893955285
Fold 5 IBS: 0.3516793263104152
[I 2024-04-16 20:22:36,473] Trial 2 finished with value: 0.3835922676459821 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.4704135620618575
Fold 2 IBS: 0.36311294602907385
Fold 3 IBS: 0.44186760672403186
Fold 4 IBS: 0.4334142885506428
Fold 5 IBS: 0.3691323605430336
[I 2024-04-16 20:22:37,874] Trial 3 finished with value: 0.41558815278172795 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.46181899679843014
Fold 2 IBS: 0.3638669810982228
Fold 3 IBS: 0.4498664344682702
Fold 4 IBS: 0.42393395601964073
Fold 5 IBS: 0.37914573407942165
[I 2024-04-16 20:22:39,475] Trial 4 finished with value: 0.4157264204927971 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.4738466646686254
Fold 2 IBS: 0.36047581329972456
Fold 3 IBS: 0.4332917204530763
Fold 4 IBS: 0.4214097721263476
Fold 5 IBS: 0.3660977872191346
[I 2024-04-16 20:22:40,912] Trial 5 finished with value: 0.4110243515533817 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.47692240729852803
Fold 2 IBS: 0.35851168214697854
Fold 3 IBS: 0.47818353414881387
Fold 4 IBS: 0.4611196635570082
Fold 5 IBS: 0.38388092058661044
[I 2024-04-16 20:22:43,107] Trial 6 finished with value: 0.4317236415475878 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.46515941643973324
Fold 2 IBS: 0.362710400640159
Fold 3 IBS: 0.44946055215942105
Fold 4 IBS: 0.42411594739106717
Fold 5 IBS: 0.3772143662361718
[I 2024-04-16 20:22:45,274] Trial 7 finished with value: 0.4157321365733105 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.47336133524727053
Fold 2 IBS: 0.36388253734735077
Fold 3 IBS: 0.4395795194428596
Fold 4 IBS: 0.42721879122242723
Fold 5 IBS: 0.3672181643722354
[I 2024-04-16 20:22:47,464] Trial 8 finished with value: 0.41425206952642873 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.4736894268900916
Fold 2 IBS: 0.3581589322445607
Fold 3 IBS: 0.4285167578723142
Fold 4 IBS: 0.41655592435133443
Fold 5 IBS: 0.36493625824757425
[I 2024-04-16 20:22:50,364] Trial 9 finished with value: 0.408371459921175 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.3835922676459821.
Fold 1 IBS: 0.4474833579207697
Fold 2 IBS: 0.22910491227991228
Fold 3 IBS: 0.22882067018549726
Fold 4 IBS: 0.23911139037729487
Fold 5 IBS: 0.22667282599400485
[I 2024-04-16 20:22:51,232] Trial 10 finished with value: 0.2742386313514958 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.2742386313514958.
Fold 1 IBS: 0.24692250370846938
Fold 2 IBS: 0.23154842109725138
Fold 3 IBS: 0.22895208771471434
Fold 4 IBS: 0.24138974433869884
Fold 5 IBS: 0.22891344232386532
[I 2024-04-16 20:22:51,793] Trial 11 finished with value: 0.23554523983659986 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.23554523983659986.
Fold 1 IBS: 0.24659802228393485
Fold 2 IBS: 0.2310288527166041
Fold 3 IBS: 0.22892155907997117
Fold 4 IBS: 0.240829804933374
Fold 5 IBS: 0.22841880077965643
[I 2024-04-16 20:22:52,201] Trial 12 finished with value: 0.2351594079587081 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.24712325420639855
Fold 2 IBS: 0.23185511989505825
Fold 3 IBS: 0.2289705856912454
Fold 4 IBS: 0.24174934580815433
Fold 5 IBS: 0.22921187948827604
[I 2024-04-16 20:22:52,722] Trial 13 finished with value: 0.23578203701782652 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.4603083542180247
Fold 2 IBS: 0.22750700897724133
Fold 3 IBS: 0.2287576055639606
Fold 4 IBS: 0.23803396993370438
Fold 5 IBS: 0.3345469002237984
[I 2024-04-16 20:22:53,640] Trial 14 finished with value: 0.2978307677833459 and parameters: {'l1_ratio': 0.14337364566668}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.2470696006437127
Fold 2 IBS: 0.23177391356644544
Fold 3 IBS: 0.22896566568258866
Fold 4 IBS: 0.24165274026483421
Fold 5 IBS: 0.2291318028728211
[I 2024-04-16 20:22:54,241] Trial 15 finished with value: 0.2357187446060804 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.46753625592179204
Fold 2 IBS: 0.2260032257244153
Fold 3 IBS: 0.37659006993041877
Fold 4 IBS: 0.36919075727217104
Fold 5 IBS: 0.34968326287788903
[I 2024-04-16 20:22:56,595] Trial 16 finished with value: 0.3578007143453373 and parameters: {'l1_ratio': 0.21332970570491078}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.47193675613422326
Fold 2 IBS: 0.3538067441863127
Fold 3 IBS: 0.41026663193157226
Fold 4 IBS: 0.40192100380430074
Fold 5 IBS: 0.36102364443574186
[I 2024-04-16 20:22:59,219] Trial 17 finished with value: 0.3997909560984302 and parameters: {'l1_ratio': 0.31307066649676046}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.45668929530726243
Fold 2 IBS: 0.22806305695872828
Fold 3 IBS: 0.22877681815739645
Fold 4 IBS: 0.23837927568254358
Fold 5 IBS: 0.3273017817812488
[I 2024-04-16 20:23:00,932] Trial 18 finished with value: 0.2958420455774359 and parameters: {'l1_ratio': 0.12120380780234859}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.44953949247838004
Fold 2 IBS: 0.22887356997899908
Fold 3 IBS: 0.2288101517627525
Fold 4 IBS: 0.23893843388250324
Fold 5 IBS: 0.2264677999388294
[I 2024-04-16 20:23:01,492] Trial 19 finished with value: 0.27452588960829283 and parameters: {'l1_ratio': 0.09170436955756033}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.47596868953130217
Fold 2 IBS: 0.3599003821929534
Fold 3 IBS: 0.4732745448516676
Fold 4 IBS: 0.46050807988967934
Fold 5 IBS: 0.38785188027561496
[I 2024-04-16 20:23:11,704] Trial 20 finished with value: 0.4315007153482435 and parameters: {'l1_ratio': 0.9656427853442138}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.24700294894853175
Fold 2 IBS: 0.23167205468386767
Fold 3 IBS: 0.22895952906292105
Fold 4 IBS: 0.2415334129903012
Fold 5 IBS: 0.22903190288089811
[I 2024-04-16 20:23:12,892] Trial 21 finished with value: 0.23563996971330395 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.2467589360328289
Fold 2 IBS: 0.23128898997835748
Fold 3 IBS: 0.2289367106460004
Fold 4 IBS: 0.24110635597149194
Fold 5 IBS: 0.22866460307208084
[I 2024-04-16 20:23:16,003] Trial 22 finished with value: 0.23535111914015192 and parameters: {'l1_ratio': 0.018997068950600285}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.4638547119008525
Fold 2 IBS: 0.22686453826593148
Fold 3 IBS: 0.2287398532752195
Fold 4 IBS: 0.3525300513456504
Fold 5 IBS: 0.34141603518443037
[I 2024-04-16 20:23:19,781] Trial 23 finished with value: 0.32268103799441683 and parameters: {'l1_ratio': 0.17128591911951985}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.47202341306399404
Fold 2 IBS: 0.35386531610790106
Fold 3 IBS: 0.411181054000561
Fold 4 IBS: 0.402694788517388
Fold 5 IBS: 0.36137711860957333
[I 2024-04-16 20:23:22,311] Trial 24 finished with value: 0.40022833805988345 and parameters: {'l1_ratio': 0.31612098478358897}. Best is trial 12 with value: 0.2351594079587081.

Fold 1 IBS: 0.44878590243432254
Fold 2 IBS: 0.22895499755289705
Fold 3 IBS: 0.2288138071100771
Fold 4 IBS: 0.23899859714513985
Fold 5 IBS: 0.2265399329750911
[I 2024-04-16 20:23:23,011] Trial 25 finished with value: 0.2744186474435055 and parameters: {'l1_ratio': 0.08890608406899088}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.4689238457546616
Fold 2 IBS: 0.3438648658019378
Fold 3 IBS: 0.3849804469982634
Fold 4 IBS: 0.3762695755182494
Fold 5 IBS: 0.3525388212473729
[I 2024-04-16 20:23:25,079] Trial 26 finished with value: 0.385315511064097 and parameters: {'l1_ratio': 0.23521758130887002}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.46457863126453197
Fold 2 IBS: 0.36642881617790757
Fold 3 IBS: 0.45258628016037145
Fold 4 IBS: 0.4335524959912747
Fold 5 IBS: 0.3890169998588207
[I 2024-04-16 20:23:28,162] Trial 27 finished with value: 0.4212326446905813 and parameters: {'l1_ratio': 0.8345729974660353}. Best is trial 12 with value: 0.2351594079587081.
Fold 1 IBS: 0.24604337877095478
Fold 2 IBS: 0.23007949855370727
Fold 3 IBS: 0.22886908369421277
Fold 4 IBS: 0.23991383600263555
Fold 5 IBS: 0.22754377087729227
[I 2024-04-16 20:23:28,620] Trial 28 finished with value: 0.23448991357976054 and parameters: {'l1_ratio': 0.05293907552049415}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.47010354932719994
Fold 2 IBS: 0.36265149401960706
Fold 3 IBS: 0.44406197301721956
Fold 4 IBS: 0.43243780753548616
Fold 5 IBS: 0.3711916209292659
[I 2024-04-16 20:23:30,537] Trial 29 finished with value: 0.4160892889657557 and parameters: {'l1_ratio': 0.5967051388615063}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.44591013552216985
Fold 2 IBS: 0.22925399421917156
Fold 3 IBS: 0.2288276608160628
Fold 4 IBS: 0.23922622552985778
Fold 5 IBS: 0.2268051491614438
[I 2024-04-16 20:23:31,105] Trial 30 finished with value: 0.27400463304974115 and parameters: {'l1_ratio': 0.07886834045222822}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.2461731060853687
Fold 2 IBS: 0.23030919049366969
Fold 3 IBS: 0.22888134570608604
Fold 4 IBS: 0.24012199439533688
Fold 5 IBS: 0.2277529606463729
[I 2024-04-16 20:23:31,488] Trial 31 finished with value: 0.23464771946536683 and parameters: {'l1_ratio': 0.04614974199010863}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.46472194583427673
Fold 2 IBS: 0.22670726299865254
Fold 3 IBS: 0.22873633014136294
Fold 4 IBS: 0.35485579160049147
Fold 5 IBS: 0.3431449317283158
[I 2024-04-16 20:23:32,391] Trial 32 finished with value: 0.3236332524606199 and parameters: {'l1_ratio': 0.17854043677240342}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.2460868816840755
Fold 2 IBS: 0.23015703211865463
Fold 3 IBS: 0.2288731897125094
Fold 4 IBS: 0.23998323259777604
Fold 5 IBS: 0.2276139242579961
[I 2024-04-16 20:23:32,843] Trial 33 finished with value: 0.23454285207420228 and parameters: {'l1_ratio': 0.05062780651988015}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.4710585213810755
Fold 2 IBS: 0.3482855514452141
Fold 3 IBS: 0.39607381044171824
Fold 4 IBS: 0.3885441723032314
Fold 5 IBS: 0.3561542010645715
[I 2024-04-16 20:23:34,511] Trial 34 finished with value: 0.39202325132716215 and parameters: {'l1_ratio': 0.2670118969882481}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.46317060184120695
Fold 2 IBS: 0.22698716528978294
Fold 3 IBS: 0.22874283545327534
Fold 4 IBS: 0.34988706432285493
Fold 5 IBS: 0.3401378222129207
[I 2024-04-16 20:23:35,289] Trial 35 finished with value: 0.32178509782400816 and parameters: {'l1_ratio': 0.16575056199908278}. Best is trial 28 with value: 0.23448991357976054.
Fold 1 IBS: 0.2457690572665409
Fold 2 IBS: 0.22957881796704507
Fold 3 IBS: 0.22884343401611795
Fold 4 IBS: 0.2394860145176614
Fold 5 IBS: 0.22709434085008956
[I 2024-04-16 20:23:35,534] Trial 36 finished with value: 0.23415433292349097 and parameters: {'l1_ratio': 0.06836615943057256}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.4726323544843633
Fold 2 IBS: 0.3559363248592264
Fold 3 IBS: 0.42049493484517864
Fold 4 IBS: 0.40880875345748713
Fold 5 IBS: 0.3635897418782619
[I 2024-04-16 20:23:36,949] Trial 37 finished with value: 0.40429242190490344 and parameters: {'l1_ratio': 0.3506936539855874}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.4697218584668902
Fold 2 IBS: 0.34535404670524056
Fold 3 IBS: 0.3878516048607405
Fold 4 IBS: 0.3803240647808818
Fold 5 IBS: 0.3534549305311068
[I 2024-04-16 20:23:38,095] Trial 38 finished with value: 0.387341301068972 and parameters: {'l1_ratio': 0.24382273503593305}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.4575601546065259
Fold 2 IBS: 0.22793955749684505
Fold 3 IBS: 0.22877227205383102
Fold 4 IBS: 0.23830003574598196
Fold 5 IBS: 0.3290460884566538
[I 2024-04-16 20:23:38,727] Trial 39 finished with value: 0.2963236216719675 and parameters: {'l1_ratio': 0.12598202509267675}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.24586182380012517
Fold 2 IBS: 0.22975039504972747
Fold 3 IBS: 0.2288520490241676
Fold 4 IBS: 0.23962876845921793
Fold 5 IBS: 0.22724776399308047
[I 2024-04-16 20:23:39,046] Trial 40 finished with value: 0.23426816006526371 and parameters: {'l1_ratio': 0.06297896791389103}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.24585014892464513
Fold 2 IBS: 0.2297289282520589
Fold 3 IBS: 0.22885096087861395
Fold 4 IBS: 0.23961069349752728
Fold 5 IBS: 0.22722853892992234
[I 2024-04-16 20:23:39,300] Trial 41 finished with value: 0.23425385409655347 and parameters: {'l1_ratio': 0.0636471141894898}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.24577783958910995
Fold 2 IBS: 0.22959515972411104
Fold 3 IBS: 0.22884424635783154
Fold 4 IBS: 0.23949944235535153
Fold 5 IBS: 0.22710893063648876
[I 2024-04-16 20:23:39,583] Trial 42 finished with value: 0.23416512373257858 and parameters: {'l1_ratio': 0.06784839687035149}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.4665970120929043
Fold 2 IBS: 0.2263097231087427
Fold 3 IBS: 0.36995428902149485
Fold 4 IBS: 0.36396163218265165
Fold 5 IBS: 0.3470481224102532
[I 2024-04-16 20:23:40,370] Trial 43 finished with value: 0.35477415576320925 and parameters: {'l1_ratio': 0.19769395592707542}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.4557120976866131
Fold 2 IBS: 0.22820807714454286
Fold 3 IBS: 0.2287823471850361
Fold 4 IBS: 0.23847425686801785
Fold 5 IBS: 0.3255226469839854
[I 2024-04-16 20:23:40,873] Trial 44 finished with value: 0.29533988517363907 and parameters: {'l1_ratio': 0.11569346147636497}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.24584981773191025
Fold 2 IBS: 0.22972831874917737
Fold 3 IBS: 0.22885093002547305
Fold 4 IBS: 0.23961018120629785
Fold 5 IBS: 0.22722799320863257
[I 2024-04-16 20:23:41,113] Trial 45 finished with value: 0.23425344818429822 and parameters: {'l1_ratio': 0.0636661090123829}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.47379322636763577
Fold 2 IBS: 0.3600422075552778
Fold 3 IBS: 0.43259460875551325
Fold 4 IBS: 0.4203226983613996
Fold 5 IBS: 0.36590620925463563
[I 2024-04-16 20:23:42,408] Trial 46 finished with value: 0.4105317900588924 and parameters: {'l1_ratio': 0.4178465972493743}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.4727082910668612
Fold 2 IBS: 0.3640703390708638
Fold 3 IBS: 0.4410738224158543
Fold 4 IBS: 0.4291508610013671
Fold 5 IBS: 0.3681706862408643
[I 2024-04-16 20:23:44,100] Trial 47 finished with value: 0.4150347999591621 and parameters: {'l1_ratio': 0.5063994947206192}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.4602928544130817
Fold 2 IBS: 0.22751047176446954
Fold 3 IBS: 0.22875771481822896
Fold 4 IBS: 0.23803603130611978
Fold 5 IBS: 0.3345262773104625
[I 2024-04-16 20:23:44,727] Trial 48 finished with value: 0.2978246699224725 and parameters: {'l1_ratio': 0.14323017915115144}. Best is trial 36 with value: 0.23415433292349097.
Fold 1 IBS: 0.24570787927439822
Fold 2 IBS: 0.2294644136549992
Fold 3 IBS: 0.2288377965334998
Fold 4 IBS: 0.23939298293816474
Fold 5 IBS: 0.22699232084060642
[I 2024-04-16 20:23:45,145] Trial 49 finished with value: 0.2340790786483337 and parameters: {'l1_ratio': 0.07201890462980487}. Best is trial 49 with value: 0.2340790786483337.

Fold 1 IBS: 0.4528680686176761
Fold 2 IBS: 0.22855176102945338
Fold 3 IBS: 0.2287962292644494
Fold 4 IBS: 0.23870799813892157
Fold 5 IBS: 0.3210081231764322
[I 2024-04-16 20:23:45,959] Trial 50 finished with value: 0.2939864360453865 and parameters: {'l1_ratio': 0.10304820804750442}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24587444933585
Fold 2 IBS: 0.2297735686866457
Fold 3 IBS: 0.22885322693415577
Fold 4 IBS: 0.23964835057429018
Fold 5 IBS: 0.2272685279911469
[I 2024-04-16 20:23:46,213] Trial 51 finished with value: 0.2342836247044177 and parameters: {'l1_ratio': 0.0622595569832182}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.46156717425811067
Fold 2 IBS: 0.2272903421113041
Fold 3 IBS: 0.22875104746177286
Fold 4 IBS: 0.34557212563307005
Fold 5 IBS: 0.3370205701521933
[I 2024-04-16 20:23:47,286] Trial 52 finished with value: 0.3200402519232902 and parameters: {'l1_ratio': 0.15249375205395843}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.46687953181285186
Fold 2 IBS: 0.22621235807467016
Fold 3 IBS: 0.37203153333967853
Fold 4 IBS: 0.3657585736037457
Fold 5 IBS: 0.3479889576044671
[I 2024-04-16 20:23:48,305] Trial 53 finished with value: 0.3557741908870827 and parameters: {'l1_ratio': 0.20257511372116016}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2457740785502918
Fold 2 IBS: 0.2295881638589313
Fold 3 IBS: 0.2288438983823142
Fold 4 IBS: 0.23949368964442394
Fold 5 IBS: 0.2271026842381451
[I 2024-04-16 20:23:48,536] Trial 54 finished with value: 0.23416050293482127 and parameters: {'l1_ratio': 0.06806992823663353}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4548979869289075
Fold 2 IBS: 0.22831390724160983
Fold 3 IBS: 0.22878650777051635
Fold 4 IBS: 0.23854491757276367
Fold 5 IBS: 0.3241212603527083
[I 2024-04-16 20:23:49,121] Trial 55 finished with value: 0.2949329159733011 and parameters: {'l1_ratio': 0.11173879788574594}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24644617642213248
Fold 2 IBS: 0.23077773340769012
Fold 3 IBS: 0.22890722848904738
Fold 4 IBS: 0.24057338114314827
Fold 5 IBS: 0.22818442304856104
[I 2024-04-16 20:23:49,406] Trial 56 finished with value: 0.23497778850211587 and parameters: {'l1_ratio': 0.03282039168622503}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.46882294722257
Fold 2 IBS: 0.3620422627072236
Fold 3 IBS: 0.44580116097388844
Fold 4 IBS: 0.43017395663433233
Fold 5 IBS: 0.3729966985695813
[I 2024-04-16 20:23:50,719] Trial 57 finished with value: 0.4159674052215191 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24714621429275532
Fold 2 IBS: 0.23188965596817734
Fold 3 IBS: 0.22897268538552354
Fold 4 IBS: 0.24179088225476442
Fold 5 IBS: 0.2292460556222468
[I 2024-04-16 20:23:50,931] Trial 58 finished with value: 0.23580909870469347 and parameters: {'l1_ratio': 0.003680241884233326}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4715228092452051
Fold 2 IBS: 0.3509013512501194
Fold 3 IBS: 0.40255525436307105
Fold 4 IBS: 0.3938646036794821
Fold 5 IBS: 0.3585541544859437
[I 2024-04-16 20:23:52,032] Trial 59 finished with value: 0.39547963460476426 and parameters: {'l1_ratio': 0.28784129559051497}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4612998693151883
Fold 2 IBS: 0.22734044741271037
Fold 3 IBS: 0.22875251465005714
Fold 4 IBS: 0.23793608145140197
Fold 5 IBS: 0.3363115211384762
[I 2024-04-16 20:23:52,682] Trial 60 finished with value: 0.2983280867935668 and parameters: {'l1_ratio': 0.15035923363145354}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4445935919515543
Fold 2 IBS: 0.22937477454774605
Fold 3 IBS: 0.22883344111513018
Fold 4 IBS: 0.23932126344065535
Fold 5 IBS: 0.2269125179648253
[I 2024-04-16 20:23:53,083] Trial 61 finished with value: 0.2738071178039822 and parameters: {'l1_ratio': 0.07491572411425823}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24590397046997256
Fold 2 IBS: 0.2298275863223347
Fold 3 IBS: 0.2288559856056163
Fold 4 IBS: 0.23969428034149604
Fold 5 IBS: 0.22731697181289
[I 2024-04-16 20:23:53,377] Trial 62 finished with value: 0.23431975891046192 and parameters: {'l1_ratio': 0.06059006222565301}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.45586448408374075
Fold 2 IBS: 0.2281845265727498
Fold 3 IBS: 0.22878143559345518
Fold 4 IBS: 0.23845868832991213
Fold 5 IBS: 0.3257840638656931
[I 2024-04-16 20:23:53,935] Trial 63 finished with value: 0.29541463968911014 and parameters: {'l1_ratio': 0.11658107001693468}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24632875599087553
Fold 2 IBS: 0.2305787665648537
Fold 3 IBS: 0.2288961008524871
Fold 4 IBS: 0.24037706179506121
Fold 5 IBS: 0.22800048526367475
[I 2024-04-16 20:23:54,263] Trial 64 finished with value: 0.23483623409339044 and parameters: {'l1_ratio': 0.03839809112022652}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.44828104324739243
Fold 2 IBS: 0.22901365014626343
Fold 3 IBS: 0.2288164718993572
Fold 4 IBS: 0.23904241065121
Fold 5 IBS: 0.2265919097618568
[I 2024-04-16 20:23:54,648] Trial 65 finished with value: 0.27434909714121597 and parameters: {'l1_ratio': 0.08690790632204588}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2472220512532472
Fold 2 IBS: 0.23200281513919233
Fold 3 IBS: 0.22897959488104994
Fold 4 IBS: 0.24192890465849098
Fold 5 IBS: 0.22935855882027084
[I 2024-04-16 20:23:54,852] Trial 66 finished with value: 0.23589838495045026 and parameters: {'l1_ratio': 0.0009031167973598819}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4594968892525971
Fold 2 IBS: 0.36621842552022726
Fold 3 IBS: 0.45037523775244714
Fold 4 IBS: 0.4310201137412828
Fold 5 IBS: 0.3849258447788247
[I 2024-04-16 20:23:56,191] Trial 67 finished with value: 0.41840730220907585 and parameters: {'l1_ratio': 0.7965604964350725}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.46711209275797383
Fold 2 IBS: 0.2261276484833541
Fold 3 IBS: 0.3738096125463737
Fold 4 IBS: 0.36729958211280056
Fold 5 IBS: 0.34857790471877037
[I 2024-04-16 20:23:57,021] Trial 68 finished with value: 0.35658536812385455 and parameters: {'l1_ratio': 0.20688606641002338}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24644907944312908
Fold 2 IBS: 0.23078258778418453
Fold 3 IBS: 0.2289075023964619
Fold 4 IBS: 0.240578241766912
Fold 5 IBS: 0.22818892653646222
[I 2024-04-16 20:23:57,236] Trial 69 finished with value: 0.23498126758542998 and parameters: {'l1_ratio': 0.03268578715374158}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.46540741131055174
Fold 2 IBS: 0.22660221153619003
Fold 3 IBS: 0.22873417359886647
Fold 4 IBS: 0.35693817074898326
Fold 5 IBS: 0.3442427813961063
[I 2024-04-16 20:23:57,984] Trial 70 finished with value: 0.3243849497181396 and parameters: {'l1_ratio': 0.18348494859658188}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4452096410003889
Fold 2 IBS: 0.2293193239164455
Fold 3 IBS: 0.22883077462655704
Fold 4 IBS: 0.23927740561984082
Fold 5 IBS: 0.22686320374701902
[I 2024-04-16 20:23:58,380] Trial 71 finished with value: 0.2739000697820503 and parameters: {'l1_ratio': 0.07672326772242938}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2459934669672268
Fold 2 IBS: 0.22998991117350442
Fold 3 IBS: 0.2288643824899189
Fold 4 IBS: 0.23983472966889738
Fold 5 IBS: 0.22746293724445912
[I 2024-04-16 20:23:58,693] Trial 72 finished with value: 0.23442908550880132 and parameters: {'l1_ratio': 0.055634925966246}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4586612722242781
Fold 2 IBS: 0.22780030799046022
Fold 3 IBS: 0.22876733211877356
Fold 4 IBS: 0.238212463922161
Fold 5 IBS: 0.3307287107887678
[I 2024-04-16 20:23:59,325] Trial 73 finished with value: 0.2968340174088881 and parameters: {'l1_ratio': 0.13146710832293373}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4504620853637464
Fold 2 IBS: 0.2287819367973152
Fold 3 IBS: 0.22880610098046789
Fold 4 IBS: 0.2388716390927458
Fold 5 IBS: 0.3175636246933523
[I 2024-04-16 20:23:59,860] Trial 74 finished with value: 0.2928970773855255 and parameters: {'l1_ratio': 0.09488759483571174}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2458173546757825
Fold 2 IBS: 0.22966843361252615
Fold 3 IBS: 0.22884791012097092

Fold 4 IBS: 0.23956009050127555
Fold 5 IBS: 0.2271744056625828
[I 2024-04-16 20:24:00,127] Trial 75 finished with value: 0.2342136389146276 and parameters: {'l1_ratio': 0.06553896583892481}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4616056246886181
Fold 2 IBS: 0.22727668657042285
Fold 3 IBS: 0.2287506528643878
Fold 4 IBS: 0.3459040248125855
Fold 5 IBS: 0.3371648911673263
[I 2024-04-16 20:24:00,739] Trial 76 finished with value: 0.3201403760206681 and parameters: {'l1_ratio': 0.1530781934236944}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24651237705629012
Fold 2 IBS: 0.2308879732498956
Fold 3 IBS: 0.22891347637323045
Fold 4 IBS: 0.24068462849182948
Fold 5 IBS: 0.22828690062418514
[I 2024-04-16 20:24:00,976] Trial 77 finished with value: 0.23505707115908617 and parameters: {'l1_ratio': 0.02978065555037694}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4524340523933975
Fold 2 IBS: 0.22859380602326862
Fold 3 IBS: 0.22879799925262276
Fold 4 IBS: 0.2387374546650607
Fold 5 IBS: 0.3204473992747861
[I 2024-04-16 20:24:01,478] Trial 78 finished with value: 0.29380214232182716 and parameters: {'l1_ratio': 0.10153961475610777}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2457784333698561
Fold 2 IBS: 0.22959626386514492
Fold 3 IBS: 0.22884430130723085
Fold 4 IBS: 0.23950035087936386
Fold 5 IBS: 0.22710991656631327
[I 2024-04-16 20:24:01,715] Trial 79 finished with value: 0.2341658531975818 and parameters: {'l1_ratio': 0.06781344969142057}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.47043073753440845
Fold 2 IBS: 0.3462300392589904
Fold 3 IBS: 0.3908250084570463
Fold 4 IBS: 0.3828783073816592
Fold 5 IBS: 0.35433823930253433
[I 2024-04-16 20:24:02,756] Trial 80 finished with value: 0.3889404663869277 and parameters: {'l1_ratio': 0.25158468257335587}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24579824487624918
Fold 2 IBS: 0.22963304976221796
Fold 3 IBS: 0.22884613655683567
Fold 4 IBS: 0.239530718678178
Fold 5 IBS: 0.22714277605631147
[I 2024-04-16 20:24:03,132] Trial 81 finished with value: 0.23419018518595847 and parameters: {'l1_ratio': 0.06665171788817732}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2466037463609525
Fold 2 IBS: 0.23103820765032543
Fold 3 IBS: 0.2289220990430987
Fold 4 IBS: 0.24083955793943004
Fold 5 IBS: 0.22842758934436078
[I 2024-04-16 20:24:03,405] Trial 82 finished with value: 0.23516624006763348 and parameters: {'l1_ratio': 0.025686657636952}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4586360174329835
Fold 2 IBS: 0.22780454790147614
Fold 3 IBS: 0.22876747955343535
Fold 4 IBS: 0.2382151029977167
Fold 5 IBS: 0.3306746878977543
[I 2024-04-16 20:24:03,922] Trial 83 finished with value: 0.2968195671566732 and parameters: {'l1_ratio': 0.1312985401691572}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4477249377305922
Fold 2 IBS: 0.2290788692248178
Fold 3 IBS: 0.22881946576261328
Fold 4 IBS: 0.23909160500899748
Fold 5 IBS: 0.22664972949964715
[I 2024-04-16 20:24:04,264] Trial 84 finished with value: 0.27427292144533355 and parameters: {'l1_ratio': 0.08470291967243138}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24596689778775108
Fold 2 IBS: 0.22994194687880679
Fold 3 IBS: 0.2288618848835136
Fold 4 IBS: 0.23979284571615542
Fold 5 IBS: 0.22741974267880813
[I 2024-04-16 20:24:04,471] Trial 85 finished with value: 0.234396663589007 and parameters: {'l1_ratio': 0.05708954710461335}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.465086305024342
Fold 2 IBS: 0.22666760358866936
Fold 3 IBS: 0.22873549716840313
Fold 4 IBS: 0.35621919850317857
Fold 5 IBS: 0.3435120741494223
[I 2024-04-16 20:24:05,162] Trial 86 finished with value: 0.32404413568680307 and parameters: {'l1_ratio': 0.18039756271136526}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24723639429568373
Fold 2 IBS: 0.23202405954317795
Fold 3 IBS: 0.22898089706151453
Fold 4 IBS: 0.24195515096706458
Fold 5 IBS: 0.22937977198251672
[I 2024-04-16 20:24:05,398] Trial 87 finished with value: 0.2359152547699915 and parameters: {'l1_ratio': 0.000385144525051756}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4539405995154375
Fold 2 IBS: 0.22842781039989818
Fold 3 IBS: 0.22879110044201426
Fold 4 IBS: 0.23862226622300092
Fold 5 IBS: 0.32260686150451084
[I 2024-04-16 20:24:05,874] Trial 88 finished with value: 0.29447772761697233 and parameters: {'l1_ratio': 0.10754350264565515}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24661052293384098
Fold 2 IBS: 0.23104927321116456
Fold 3 IBS: 0.22892273822842868
Fold 4 IBS: 0.24085111235028586
Fold 5 IBS: 0.22843798954598796
[I 2024-04-16 20:24:06,093] Trial 89 finished with value: 0.23517432725394163 and parameters: {'l1_ratio': 0.025387654862977185}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4680102893521512
Fold 2 IBS: 0.22586962923787274
Fold 3 IBS: 0.3794285438314995
Fold 4 IBS: 0.3714335024310526
Fold 5 IBS: 0.35077304507852425
[I 2024-04-16 20:24:06,870] Trial 90 finished with value: 0.3591030019862201 and parameters: {'l1_ratio': 0.2204013938896959}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.24576961226629201
Fold 2 IBS: 0.2295798512926232
Fold 3 IBS: 0.22884348533045878
Fold 4 IBS: 0.23948686255292856
Fold 5 IBS: 0.22709526326266233
[I 2024-04-16 20:24:07,131] Trial 91 finished with value: 0.234155014940993 and parameters: {'l1_ratio': 0.06833339074578144}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4466561373190519
Fold 2 IBS: 0.22918605241320397
Fold 3 IBS: 0.2288244548664845
Fold 4 IBS: 0.23917355638375842
Fold 5 IBS: 0.22674482012876523
[I 2024-04-16 20:24:07,440] Trial 92 finished with value: 0.2741170042222528 and parameters: {'l1_ratio': 0.08111719860053983}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2461706668646606
Fold 2 IBS: 0.23030491374933376
Fold 3 IBS: 0.2288811147250343
Fold 4 IBS: 0.2401180469532428
Fold 5 IBS: 0.22774904637064441
[I 2024-04-16 20:24:07,709] Trial 93 finished with value: 0.2346447577325832 and parameters: {'l1_ratio': 0.04627457747274218}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4568605140379941
Fold 2 IBS: 0.22803138636679998
Fold 3 IBS: 0.2287756378677679
Fold 4 IBS: 0.2383588122588319
Fold 5 IBS: 0.3277182468738646
[I 2024-04-16 20:24:08,479] Trial 94 finished with value: 0.29594891948105173 and parameters: {'l1_ratio': 0.1224215390422528}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.46265915947174213
Fold 2 IBS: 0.22708485718628715
Fold 3 IBS: 0.22874535381982536
Fold 4 IBS: 0.34891897323187143
Fold 5 IBS: 0.33922087900112413
[I 2024-04-16 20:24:09,090] Trial 95 finished with value: 0.32132584454217006 and parameters: {'l1_ratio': 0.1614134843316634}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2457122558934403
Fold 2 IBS: 0.22947263086885186
Fold 3 IBS: 0.22883819853284554
Fold 4 IBS: 0.23939960870416255
Fold 5 IBS: 0.226999641929937
[I 2024-04-16 20:24:09,323] Trial 96 finished with value: 0.23408446718584744 and parameters: {'l1_ratio': 0.07175489371034097}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.4527403738680613
Fold 2 IBS: 0.22856590335520963
Fold 3 IBS: 0.2287968229311615
Fold 4 IBS: 0.23871788477246625
Fold 5 IBS: 0.3208621159795748
[I 2024-04-16 20:24:10,021] Trial 97 finished with value: 0.2939366201812947 and parameters: {'l1_ratio': 0.10253986593628098}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.45985862165341473
Fold 2 IBS: 0.2276073457574975
Fold 3 IBS: 0.22876082629160585
Fold 4 IBS: 0.23809414022025982
Fold 5 IBS: 0.33328576243753666
[I 2024-04-16 20:24:10,781] Trial 98 finished with value: 0.2975213392720629 and parameters: {'l1_ratio': 0.1392450659707795}. Best is trial 49 with value: 0.2340790786483337.
Fold 1 IBS: 0.2457190084534479
Fold 2 IBS: 0.22948529907244936
Fold 3 IBS: 0.22883881917411303
Fold 4 IBS: 0.23940984040460597
Fold 5 IBS: 0.22701093053238544
[I 2024-04-16 20:24:11,044] Trial 99 finished with value: 0.23409277952740032 and parameters: {'l1_ratio': 0.07134837995871275}. Best is trial 49 with value: 0.2340790786483337.


* Best trial for IBS:
 FrozenTrial(number=49, state=TrialState.COMPLETE, values=[0.2340790786483337], datetime_start=datetime.datetime(2024, 4, 16, 20, 23, 44, 730928), datetime_complete=datetime.datetime(2024, 4, 16, 20, 23, 45, 145087), params={'l1_ratio': 0.07201890462980487}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=49, value=None)


* Best Score for IBS:
 0.2340790786483337

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.639
train_ibs:  0.234

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.07142581107906198)

test_cindex : 0.54

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.07201890462980487)

test_ibs:  0.228

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 20:24:11,439] A new study created in memory with name: no-name-c9d8190a-30c2-4a22-b725-6ce4a1d62e14

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:24:29,571] Trial 0 finished with value: 0.6887600217317204 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 20:24:32,663] Trial 1 finished with value: 0.6166380389955435 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 20:24:35,205] Trial 2 finished with value: 0.62549226208284 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:24:35,853] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:24:36,643] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 20:24:40,752] Trial 5 finished with value: 0.6152561447305711 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:24:57,669] Trial 6 finished with value: 0.6539398109744831 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:24:59,143] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.45493562231759654
[I 2024-04-16 20:25:05,203] Trial 8 finished with value: 0.4909871244635193 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5064377682403434
[I 2024-04-16 20:25:09,320] Trial 9 finished with value: 0.5980152878848332 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:25:10,298] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 20:25:21,490] Trial 11 finished with value: 0.6475023250639829 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:25:26,729] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 20:25:34,615] Trial 13 finished with value: 0.6848917982857154 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 20:25:35,137] Trial 14 finished with value: 0.7054382711677689 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17530903073562382, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 20:25:35,430] Trial 15 finished with value: 0.7004658341847222 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.7842656506469521, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21467510010373286, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.4203187250996016
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.564638783269962

Fold 5 C-index: 0.6330472103004292
[I 2024-04-16 20:25:35,585] Trial 16 finished with value: 0.6103319349924515 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.8500299963488761, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3855568975046046, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 20:25:36,237] Trial 17 finished with value: 0.7340377976614955 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.9816256083986692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10458249310616385, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 20:25:36,925] Trial 18 finished with value: 0.6851322075080448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09529552899934571, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.759656652360515
[I 2024-04-16 20:25:38,576] Trial 19 finished with value: 0.7320533243959054 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.9945689686268684, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06762043908551946, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 20:25:39,423] Trial 20 finished with value: 0.7515482174710945 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.9966629277234803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06330216271601999, 'warm_start': True}. Best is trial 20 with value: 0.7515482174710945.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 20:25:40,225] Trial 21 finished with value: 0.7546701877723911 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.9639969203071097, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07844908418015549, 'warm_start': True}. Best is trial 21 with value: 0.7546701877723911.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 20:25:41,212] Trial 22 finished with value: 0.7403034664958661 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 203, 'oob_score': True, 'max_samples': 0.8676148902287203, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.005137686000517033, 'warm_start': True}. Best is trial 21 with value: 0.7546701877723911.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 20:25:42,543] Trial 23 finished with value: 0.7563113263464099 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.869669997416516, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 23 with value: 0.7563113263464099.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 20:25:44,040] Trial 24 finished with value: 0.7606536985757444 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.8640315509178289, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07916170845060883, 'warm_start': True}. Best is trial 24 with value: 0.7606536985757444.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 20:25:46,662] Trial 25 finished with value: 0.7695297572413502 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.8486986257893505, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0009444354266301414, 'warm_start': True}. Best is trial 25 with value: 0.7695297572413502.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 20:25:49,189] Trial 26 finished with value: 0.7733467661208285 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.6912922503777362, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030529967348810284, 'warm_start': True}. Best is trial 26 with value: 0.7733467661208285.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:25:52,415] Trial 27 finished with value: 0.7847011373516671 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.6826933317259629, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04163461906296005, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 20:25:54,394] Trial 28 finished with value: 0.7626451966882999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.6790845875969467, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1346390093951372, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 20:25:56,641] Trial 29 finished with value: 0.7524072808207946 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.5460873722581808, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04113891562651206, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:25:58,876] Trial 30 finished with value: 0.6881258758502385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.7127914138629038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2486312042554125, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.

Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:26:00,320] Trial 31 finished with value: 0.7493720402953852 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.6565648650889025, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14061763521617526, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 20:26:02,280] Trial 32 finished with value: 0.7736293479949021 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 241, 'oob_score': True, 'max_samples': 0.717337635186249, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11772473625239274, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.9141630901287554
[I 2024-04-16 20:26:04,005] Trial 33 finished with value: 0.811548824267636 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.7247276784505238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03689864626175683, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 20:26:06,029] Trial 34 finished with value: 0.7829876832219352 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.7198178767085571, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11161272848170577, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 20:26:07,013] Trial 35 finished with value: 0.6912157648511975 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.5459623200293144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18558790111621754, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 20:26:09,149] Trial 36 finished with value: 0.7867216702362756 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.7338075895235944, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11281996673704411, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 20:26:10,731] Trial 37 finished with value: 0.7233721608611505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.6085366031970421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16279221402739244, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.9012875536480687
[I 2024-04-16 20:26:13,028] Trial 38 finished with value: 0.8026868253099897 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.810357312668476, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10446792179794386, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 20:26:14,438] Trial 39 finished with value: 0.8315228203891329 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.8176202594483816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05127851337193651, 'warm_start': True}. Best is trial 39 with value: 0.8315228203891329.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 20:26:15,682] Trial 40 finished with value: 0.7216554226637257 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.7959580927210158, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2448692090849676, 'warm_start': True}. Best is trial 39 with value: 0.8315228203891329.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:26:17,037] Trial 41 finished with value: 0.835684247914353 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8200079355774805, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.045375207069811796, 'warm_start': True}. Best is trial 41 with value: 0.835684247914353.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 20:26:18,365] Trial 42 finished with value: 0.8179194749278222 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.9273819199836401, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08150372432531681, 'warm_start': True}. Best is trial 41 with value: 0.835684247914353.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 20:26:20,126] Trial 43 finished with value: 0.8427105605974863 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.9388551492979577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05266231183563491, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 20:26:21,530] Trial 44 finished with value: 0.8323518578595712 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.9237895859439657, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05612306340851575, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 20:26:22,757] Trial 45 finished with value: 0.830280628369804 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.9104218782867626, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06634160384660395, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 20:26:30,173] Trial 46 finished with value: 0.6286099736434962 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05822950436150222, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 20:26:31,287] Trial 47 finished with value: 0.8325077461103134 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9355514430804484, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020042410067937978, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 20:26:39,265] Trial 48 finished with value: 0.6009684370641499 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 427, 'oob_score': False, 'max_samples': 0.823645744803961, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01683251340101157, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 20:26:41,004] Trial 49 finished with value: 0.8388530534749343 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.953849061764575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050119666582895114, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 20:26:42,947] Trial 50 finished with value: 0.7812978402712039 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.944966006745767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026515719222611322, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 20:26:44,114] Trial 51 finished with value: 0.8245657831536615 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.8927024859362178, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050579232359344195, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 20:26:45,316] Trial 52 finished with value: 0.8163869819364665 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.957013350431845, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08747379737293745, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:26:46,722] Trial 53 finished with value: 0.835655340129135 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.9059004636526794, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02247138851000744, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 20:26:48,274] Trial 54 finished with value: 0.8325767347157822 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.9045683245877397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01863439664769996, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 20:26:49,863] Trial 55 finished with value: 0.8196868832821158 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8913844051686941, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020495893741253532, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 20:26:57,171] Trial 56 finished with value: 0.6133741946644458 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.959688406147559, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.29669443075161894, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:27:00,303] Trial 57 finished with value: 0.8237721374995439 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.7632151618163023, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01760206529138649, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 20:27:01,661] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.8443244755845074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 20:27:03,022] Trial 59 finished with value: 0.6869742749526709 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 477, 'oob_score': False, 'max_samples': 0.3824901058813928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1265828087269749, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 20:27:23,688] Trial 60 finished with value: 0.6218319311565197 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 426, 'oob_score': False, 'max_samples': 0.13319246988341354, 'max_features': None, 'min_weight_fraction_leaf': 0.00239012916342312, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:27:26,150] Trial 61 finished with value: 0.831772489711018 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.9227017110627658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06216084192304142, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:27:28,195] Trial 62 finished with value: 0.8356736421434732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.8850956833773682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03863615331212726, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 20:27:31,883] Trial 63 finished with value: 0.8371544903050128 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.8853130778846439, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03966154422786905, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 20:27:35,290] Trial 64 finished with value: 0.8196654077526582 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.8851895285643775, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09142295253878854, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 20:27:39,739] Trial 65 finished with value: 0.8474444748453905 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9873533850424658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04287202412707603, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 20:27:42,601] Trial 66 finished with value: 0.8435072299253937 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9947311488203058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04006148809996164, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 20:28:21,385] Trial 67 finished with value: 0.8388932548617867 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.993658937532094, 'max_features': None, 'min_weight_fraction_leaf': 0.040436540638610116, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 20:28:53,594] Trial 68 finished with value: 0.8382846820717941 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9994331375177823, 'max_features': None, 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:29:24,086] Trial 69 finished with value: 0.8375560102421463 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9996362451167412, 'max_features': None, 'min_weight_fraction_leaf': 0.07337892913174533, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 20:29:48,705] Trial 70 finished with value: 0.8382846820717941 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.9959834334340328, 'max_features': None, 'min_weight_fraction_leaf': 0.07185098947134154, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:30:14,608] Trial 71 finished with value: 0.836704946412359 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.9969458887289653, 'max_features': None, 'min_weight_fraction_leaf': 0.07306969695088597, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 20:30:34,027] Trial 72 finished with value: 0.8428910714445162 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.9705326205407735, 'max_features': None, 'min_weight_fraction_leaf': 0.09726369000634277, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 20:30:51,747] Trial 73 finished with value: 0.8347457235953728 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.9622083984206554, 'max_features': None, 'min_weight_fraction_leaf': 0.10090208352548545, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 20:31:05,226] Trial 74 finished with value: 0.8233007612427727 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.9751692801795903, 'max_features': None, 'min_weight_fraction_leaf': 0.15896417018836817, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 20:31:11,682] Trial 75 finished with value: 0.7521199937305012 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.9753592654341334, 'max_features': None, 'min_weight_fraction_leaf': 0.35481417747069804, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 20:31:32,835] Trial 76 finished with value: 0.8372771691473451 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.9488752737712128, 'max_features': None, 'min_weight_fraction_leaf': 0.0946162304034015, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9055793991416309
[I 2024-04-16 20:31:48,641] Trial 77 finished with value: 0.8330617609492732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.9819615930431459, 'max_features': None, 'min_weight_fraction_leaf': 0.12149124274513819, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 20:32:08,976] Trial 78 finished with value: 0.8366834708829012 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.9466630798470281, 'max_features': None, 'min_weight_fraction_leaf': 0.07869379995443634, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 20:32:25,488] Trial 79 finished with value: 0.8280562944412313 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.9762362824615723, 'max_features': None, 'min_weight_fraction_leaf': 0.1438601153670844, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 20:35:04,456] Trial 80 finished with value: 0.6335124296425151 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.9981652642996742, 'max_features': None, 'min_weight_fraction_leaf': 0.05275254415427701, 'warm_start': False}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 20:35:37,711] Trial 81 finished with value: 0.8391141269510269 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9979035111091495, 'max_features': None, 'min_weight_fraction_leaf': 0.0684721968600143, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 20:36:08,164] Trial 82 finished with value: 0.8390591716052278 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9394916145721695, 'max_features': None, 'min_weight_fraction_leaf': 0.08885679941630156, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9656652360515021
[I 2024-04-16 20:36:54,658] Trial 83 finished with value: 0.8358037897038839 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.9369494626132739, 'max_features': None, 'min_weight_fraction_leaf': 0.03228804063616034, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 20:37:22,592] Trial 84 finished with value: 0.8413843291575205 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.9632963350821008, 'max_features': None, 'min_weight_fraction_leaf': 0.08645608734851228, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 20:37:36,570] Trial 85 finished with value: 0.8340869044915674 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8445466446433496, 'max_features': None, 'min_weight_fraction_leaf': 0.09405144363135096, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 20:37:53,535] Trial 86 finished with value: 0.8372383598562632 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 350, 'oob_score': False, 'max_samples': 0.9593020592230249, 'max_features': None, 'min_weight_fraction_leaf': 0.062345011421902685, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 20:38:11,944] Trial 87 finished with value: 0.830877610701941 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9299549183842758, 'max_features': None, 'min_weight_fraction_leaf': 0.10663286795016572, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 20:38:27,641] Trial 88 finished with value: 0.8357167430437187 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.8678400525803166, 'max_features': None, 'min_weight_fraction_leaf': 0.08562946203667166, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 20:38:34,711] Trial 89 finished with value: 0.7461891440711376 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.9666623619578044, 'max_features': None, 'min_weight_fraction_leaf': 0.13289751230356953, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 20:38:47,445] Trial 90 finished with value: 0.7721635506485307 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.9143479302159204, 'max_features': None, 'min_weight_fraction_leaf': 0.04481644229535587, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.

Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 20:39:13,516] Trial 91 finished with value: 0.8446737781674148 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.9488468959302472, 'max_features': None, 'min_weight_fraction_leaf': 0.060774497145647054, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 20:39:45,454] Trial 92 finished with value: 0.8405269611800452 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.94014101252894, 'max_features': None, 'min_weight_fraction_leaf': 0.0548113701472033, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 20:40:02,503] Trial 93 finished with value: 0.8120089069227732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5075426217211035, 'max_features': None, 'min_weight_fraction_leaf': 0.0319777462255082, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.9108527131782945
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 20:40:48,216] Trial 94 finished with value: 0.8187892581947704 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.9227811582027634, 'max_features': None, 'min_weight_fraction_leaf': 0.00822735070118076, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 20:41:17,411] Trial 95 finished with value: 0.8407509903501437 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9752306812643342, 'max_features': None, 'min_weight_fraction_leaf': 0.06347739998417412, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 20:41:24,086] Trial 96 finished with value: 0.797411102196824 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.9383924139197609, 'max_features': None, 'min_weight_fraction_leaf': 0.06205878427847117, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 20:41:45,270] Trial 97 finished with value: 0.8413305019197933 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9752654941017508, 'max_features': None, 'min_weight_fraction_leaf': 0.08608757981910961, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 20:43:04,593] Trial 98 finished with value: 0.6673031775286545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.9756872825157317, 'max_features': None, 'min_weight_fraction_leaf': 0.11068049094138749, 'warm_start': False}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8631178707224335

[I 2024-04-16 20:43:15,366] A new study created in memory with name: no-name-fe6af062-0349-4693-bd52-889ab5bf3d9a

Fold 5 C-index: 0.871244635193133
[I 2024-04-16 20:43:15,348] Trial 99 finished with value: 0.8113937137105396 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 467, 'oob_score': False, 'max_samples': 0.9056858572892185, 'max_features': None, 'min_weight_fraction_leaf': 0.20123851264921916, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.


* Best trial for C-index:
 FrozenTrial(number=65, state=TrialState.COMPLETE, values=[0.8474444748453905], datetime_start=datetime.datetime(2024, 4, 16, 20, 27, 35, 307464), datetime_complete=datetime.datetime(2024, 4, 16, 20, 27, 39, 738613), params={'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9873533850424658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04287202412707603, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=65, value=None)


* Best Score for C-index:
 0.8474444748453905

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23042752124267438
Fold 2 IBS: 0.18839054215405548
Fold 3 IBS: 0.2293899661136923
Fold 4 IBS: 0.2169146460429805
Fold 5 IBS: 0.2142567055646754
[I 2024-04-16 20:43:38,784] Trial 0 finished with value: 0.21587587622361562 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2508146115058545
Fold 2 IBS: 0.20305081069239997
Fold 3 IBS: 0.2125601518843403
Fold 4 IBS: 0.23802356391790935
Fold 5 IBS: 0.24031357707661585
[I 2024-04-16 20:43:40,221] Trial 1 finished with value: 0.228952543015424 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-16 20:43:40,926] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-16 20:43:43,813] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-16 20:43:46,172] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2555512810814963
Fold 2 IBS: 0.20324441473182778
Fold 3 IBS: 0.20138344229687621
Fold 4 IBS: 0.24823005681755586
Fold 5 IBS: 0.23986172601998265
[I 2024-04-16 20:43:50,433] Trial 5 finished with value: 0.22965418418954772 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22937230878310585
Fold 2 IBS: 0.19783748265063947
Fold 3 IBS: 0.24758962979639584
Fold 4 IBS: 0.2293592142258337
Fold 5 IBS: 0.21843413307330445
[I 2024-04-16 20:44:04,856] Trial 6 finished with value: 0.22451855370585588 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24645459314284615
Fold 2 IBS: 0.2284327655476503
Fold 3 IBS: 0.2269204476718718
Fold 4 IBS: 0.24193873418388995
Fold 5 IBS: 0.23242562407841813
[I 2024-04-16 20:44:10,572] Trial 7 finished with value: 0.23523443292493526 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-16 20:44:19,780] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2514315797339687
Fold 2 IBS: 0.20486001394714717
Fold 3 IBS: 0.21413246491582993
Fold 4 IBS: 0.2488036649239709
Fold 5 IBS: 0.23916777605650416
[I 2024-04-16 20:44:21,847] Trial 9 finished with value: 0.23167909991548416 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-16 20:44:33,105] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22505044010769915
Fold 2 IBS: 0.19169873975025706
Fold 3 IBS: 0.24355652039688175
Fold 4 IBS: 0.22456118368774855
Fold 5 IBS: 0.2199364923604279
[I 2024-04-16 20:45:01,396] Trial 11 finished with value: 0.2209606752606029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.9485893528798968, 'max_features': None, 'min_weight_fraction_leaf': 0.34713111632234195}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22641537530591904
Fold 2 IBS: 0.1856122448029484
Fold 3 IBS: 0.23970956613213612
Fold 4 IBS: 0.22689978521066698
Fold 5 IBS: 0.21984826293499948
[I 2024-04-16 20:45:44,814] Trial 12 finished with value: 0.219697046877334 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.99460329717513, 'max_features': None, 'min_weight_fraction_leaf': 0.3273519300270286}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24906566803157934
Fold 2 IBS: 0.1844522654087228
Fold 3 IBS: 0.22247964562583175
Fold 4 IBS: 0.2200365797335415
Fold 5 IBS: 0.21390292106525644
[I 2024-04-16 20:46:38,474] Trial 13 finished with value: 0.21798741597298638 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.7795899048785642, 'max_features': None, 'min_weight_fraction_leaf': 0.16534086975223722}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.25156447987348923
Fold 2 IBS: 0.20970424521303116
Fold 3 IBS: 0.20875877537891965
Fold 4 IBS: 0.24770150304574612
Fold 5 IBS: 0.24420033286537043
[I 2024-04-16 20:46:43,938] Trial 14 finished with value: 0.23238586727531133 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.7714173351535261, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1619227173876303}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.26683527729810225
Fold 2 IBS: 0.20435168056118677
Fold 3 IBS: 0.21099863333114646
Fold 4 IBS: 0.23944579683045827
Fold 5 IBS: 0.2220476423219148
[I 2024-04-16 20:47:25,455] Trial 15 finished with value: 0.22873580606856173 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.7857370506104712, 'max_features': None, 'min_weight_fraction_leaf': 9.381036713218549e-05}. Best is trial 0 with value: 0.21587587622361562.

Fold 1 IBS: 0.22884349745474517
Fold 2 IBS: 0.18834811375380564
Fold 3 IBS: 0.2312043647935247
Fold 4 IBS: 0.21471543299997775
Fold 5 IBS: 0.21368545250258145
[I 2024-04-16 20:47:44,468] Trial 16 finished with value: 0.21535937230092697 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.7160627225800851, 'max_features': None, 'min_weight_fraction_leaf': 0.2245547459670535}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.23115054536847185
Fold 2 IBS: 0.19232972177370425
Fold 3 IBS: 0.2306960604186981
Fold 4 IBS: 0.2282864781982014
Fold 5 IBS: 0.22100826632463474
[I 2024-04-16 20:48:02,067] Trial 17 finished with value: 0.22069421441674208 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.6871243940599472, 'max_features': None, 'min_weight_fraction_leaf': 0.2285855344271941}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.2547124645596499
Fold 2 IBS: 0.21239240552877675
Fold 3 IBS: 0.20907384621625053
Fold 4 IBS: 0.2552638099119818
Fold 5 IBS: 0.239861875460518
[I 2024-04-16 20:48:05,309] Trial 18 finished with value: 0.2342608803354354 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08924573043815814}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.25153637815211566
Fold 2 IBS: 0.2130643844494364
Fold 3 IBS: 0.21653921536390197
Fold 4 IBS: 0.2515132161134549
Fold 5 IBS: 0.24551267392915996
[I 2024-04-16 20:48:07,158] Trial 19 finished with value: 0.2356331736016138 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.6061595584833309, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22791611456767383}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.24668838755067432
Fold 2 IBS: 0.2323223694774956
Fold 3 IBS: 0.22952287763530818
Fold 4 IBS: 0.24145505906170697
Fold 5 IBS: 0.23037434075470525
[I 2024-04-16 20:48:10,177] Trial 20 finished with value: 0.23607260689597806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.4458729287336371, 'max_features': None, 'min_weight_fraction_leaf': 0.3007687013181908}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.25768407946447835
Fold 2 IBS: 0.18741993444051966
Fold 3 IBS: 0.21990359018458633
Fold 4 IBS: 0.22758690645744453
Fold 5 IBS: 0.2122845055529156
[I 2024-04-16 20:49:02,925] Trial 21 finished with value: 0.2209758032199889 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.7968542041631069, 'max_features': None, 'min_weight_fraction_leaf': 0.14088312030047453}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.23994195701389592
Fold 2 IBS: 0.1880263620809246
Fold 3 IBS: 0.22200106857343152
Fold 4 IBS: 0.2333432594536798
Fold 5 IBS: 0.22313781821533352
[I 2024-04-16 20:49:51,452] Trial 22 finished with value: 0.22129009306745306 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.7333978805634859, 'max_features': None, 'min_weight_fraction_leaf': 0.2049420412000723}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.2625956010796006
Fold 2 IBS: 0.1928923730378316
Fold 3 IBS: 0.21796884204077038
Fold 4 IBS: 0.23320993234287188
Fold 5 IBS: 0.21762131459681405
[I 2024-04-16 20:50:54,897] Trial 23 finished with value: 0.22485761261957773 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8558877999962695, 'max_features': None, 'min_weight_fraction_leaf': 0.12237281401289234}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.22276602783377017
Fold 2 IBS: 0.18341833821581766
Fold 3 IBS: 0.23515178773766685
Fold 4 IBS: 0.2158844598266772
Fold 5 IBS: 0.214498386011388
[I 2024-04-16 20:51:41,199] Trial 24 finished with value: 0.214343799925064 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8436689400574193, 'max_features': None, 'min_weight_fraction_leaf': 0.244242289743401}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2232033563663133
Fold 2 IBS: 0.18483011757148574
Fold 3 IBS: 0.2387458608845854
Fold 4 IBS: 0.21469399502353012
Fold 5 IBS: 0.21400836240416607
[I 2024-04-16 20:52:25,943] Trial 25 finished with value: 0.21509633845001613 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.8781861106771913, 'max_features': None, 'min_weight_fraction_leaf': 0.25578130205333305}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2243469078613741
Fold 2 IBS: 0.18503556791629602
Fold 3 IBS: 0.239615094137992
Fold 4 IBS: 0.2128207476339741
Fold 5 IBS: 0.21343897546943888
[I 2024-04-16 20:53:27,797] Trial 26 finished with value: 0.21505145860381503 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8790368112638932, 'max_features': None, 'min_weight_fraction_leaf': 0.25879667379312365}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.24994978911265142
Fold 2 IBS: 0.20970593191211698
Fold 3 IBS: 0.21190261680704528
Fold 4 IBS: 0.24890297891386573
Fold 5 IBS: 0.24082074617028817
[I 2024-04-16 20:53:38,204] Trial 27 finished with value: 0.2322564125831935 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 463, 'oob_score': True, 'max_samples': 0.8959637112797967, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2611199851941091}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2502142619626781
Fold 2 IBS: 0.2062960293780691
Fold 3 IBS: 0.20914331859862303
Fold 4 IBS: 0.24450110394780006
Fold 5 IBS: 0.23744852143309458
[I 2024-04-16 20:53:50,009] Trial 28 finished with value: 0.22952064706405295 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.957086450216675, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3146636471285875}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2316496219569113
Fold 2 IBS: 0.20199211986849258
Fold 3 IBS: 0.25252580475553593
Fold 4 IBS: 0.23451794093985362
Fold 5 IBS: 0.22256455030066677
[I 2024-04-16 20:54:31,897] Trial 29 finished with value: 0.22865000756429205 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.8498266742400898, 'max_features': None, 'min_weight_fraction_leaf': 0.37494346942158263}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2293501237092553
Fold 2 IBS: 0.1835103223875015
Fold 3 IBS: 0.23279207931646337
Fold 4 IBS: 0.21732583133116853
Fold 5 IBS: 0.2103061227472283
[I 2024-04-16 20:55:33,070] Trial 30 finished with value: 0.2146568958983234 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9975403100242013, 'max_features': None, 'min_weight_fraction_leaf': 0.2599744768668571}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.22543889947738152
Fold 2 IBS: 0.1845289972063156
Fold 3 IBS: 0.23174838796536676
Fold 4 IBS: 0.2144936679622966
Fold 5 IBS: 0.21144518832087167
[I 2024-04-16 20:56:22,873] Trial 31 finished with value: 0.21353102818644648 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.9626750941879966, 'max_features': None, 'min_weight_fraction_leaf': 0.26115274999390314}. Best is trial 31 with value: 0.21353102818644648.

Fold 1 IBS: 0.22149490022552124
Fold 2 IBS: 0.18466865634717505
Fold 3 IBS: 0.23548539432841317
Fold 4 IBS: 0.2113697424267566
Fold 5 IBS: 0.2119677581906565
[I 2024-04-16 20:57:00,338] Trial 32 finished with value: 0.2129972903037045 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9673759674409311, 'max_features': None, 'min_weight_fraction_leaf': 0.27417727195073677}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.2567229873354098
Fold 2 IBS: 0.18854079292396503
Fold 3 IBS: 0.2249457788925835
Fold 4 IBS: 0.22508129343804778
Fold 5 IBS: 0.21386415001842546
[I 2024-04-16 20:57:46,311] Trial 33 finished with value: 0.2218310005216863 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.9964442664551478, 'max_features': None, 'min_weight_fraction_leaf': 0.1855920796843306}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22302338864627833
Fold 2 IBS: 0.18329215715895394
Fold 3 IBS: 0.23579844813453207
Fold 4 IBS: 0.21461565443498337
Fold 5 IBS: 0.21550729328840212
[I 2024-04-16 20:58:28,285] Trial 34 finished with value: 0.21444738833262997 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.9279710918176601, 'max_features': None, 'min_weight_fraction_leaf': 0.2867300145495075}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24931299863626957
Fold 2 IBS: 0.21399812944525917
Fold 3 IBS: 0.21838058951641673
Fold 4 IBS: 0.24989391243794642
Fold 5 IBS: 0.23922813868039394
[I 2024-04-16 20:58:36,984] Trial 35 finished with value: 0.23416275374325718 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9536728448516014, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3909359479764509}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23117720087911678
Fold 2 IBS: 0.20908991901846688
Fold 3 IBS: 0.2539101731203305
Fold 4 IBS: 0.24099766821400376
Fold 5 IBS: 0.2293088693612524
[I 2024-04-16 20:58:54,830] Trial 36 finished with value: 0.23289676611863408 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.9283967702859293, 'max_features': None, 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.2523224496304161
Fold 2 IBS: 0.21043432067224094
Fold 3 IBS: 0.2112721950288639
Fold 4 IBS: 0.24870441754756062
Fold 5 IBS: 0.23989403542441912
[I 2024-04-16 20:59:01,218] Trial 37 finished with value: 0.23252548366070017 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.8243905227087784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2901382904665285}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24687665709365722
Fold 2 IBS: 0.23216047658482733
Fold 3 IBS: 0.22943470935389718
Fold 4 IBS: 0.24151119067690444
Fold 5 IBS: 0.23038863917402108
[I 2024-04-16 20:59:05,510] Trial 38 finished with value: 0.23607433457666147 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.6365393674376216, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23138450633211288
Fold 2 IBS: 0.2012849705319908
Fold 3 IBS: 0.24592903460990817
Fold 4 IBS: 0.2321634541727149
Fold 5 IBS: 0.21646893363939826
[I 2024-04-16 20:59:20,553] Trial 39 finished with value: 0.225446179857225 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 178, 'oob_score': True, 'max_samples': 0.9213772884619962, 'max_features': None, 'min_weight_fraction_leaf': 0.3814300944091633}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24772435188079012
Fold 2 IBS: 0.23218742086626878
Fold 3 IBS: 0.23060758736791892
Fold 4 IBS: 0.24175508770731288
Fold 5 IBS: 0.23204474443418183
[I 2024-04-16 20:59:23,374] Trial 40 finished with value: 0.2368638384512945 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.16382436256125943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28669301454652507}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23272078581366948
Fold 2 IBS: 0.18387215718777747
Fold 3 IBS: 0.2312356985823202
Fold 4 IBS: 0.21835974803092903
Fold 5 IBS: 0.2118508415801541
[I 2024-04-16 21:01:02,345] Trial 41 finished with value: 0.21560784623897006 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.9968428823752321, 'max_features': None, 'min_weight_fraction_leaf': 0.24475563110472928}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22762467376302845
Fold 2 IBS: 0.19292454667228245
Fold 3 IBS: 0.24232575060581318
Fold 4 IBS: 0.22605305899139677
Fold 5 IBS: 0.2183712075716998
[I 2024-04-16 21:01:33,922] Trial 42 finished with value: 0.2214598475208441 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.8330638381230538, 'max_features': None, 'min_weight_fraction_leaf': 0.30703156935090925}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22060072941583395
Fold 2 IBS: 0.1839788116163854
Fold 3 IBS: 0.2354589586695753
Fold 4 IBS: 0.2103428787902223
Fold 5 IBS: 0.21157714114706494
[I 2024-04-16 21:02:01,009] Trial 43 finished with value: 0.2123917039278164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.9591424672361251, 'max_features': None, 'min_weight_fraction_leaf': 0.2785655043553118}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2256927624531365
Fold 2 IBS: 0.19403171073899753
Fold 3 IBS: 0.24180178869616473
Fold 4 IBS: 0.22271987208962252
Fold 5 IBS: 0.21926725742571193
[I 2024-04-16 21:02:17,673] Trial 44 finished with value: 0.22070267828072665 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.9395792767074951, 'max_features': None, 'min_weight_fraction_leaf': 0.35489094778373753}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2457081276764462
Fold 2 IBS: 0.2057089461106387
Fold 3 IBS: 0.2112006429304633
Fold 4 IBS: 0.2504179456089246
Fold 5 IBS: 0.2381093166637389
[I 2024-04-16 21:02:20,387] Trial 45 finished with value: 0.23022899579804235 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.8989588401372685, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28207190827118556}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.246544080673752
Fold 2 IBS: 0.23213980573826468
Fold 3 IBS: 0.2295309513645431
Fold 4 IBS: 0.24164345141610383
Fold 5 IBS: 0.23038069732103597
[I 2024-04-16 21:02:23,836] Trial 46 finished with value: 0.23604779730273995 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 245, 'oob_score': True, 'max_samples': 0.9587168953650592, 'max_features': None, 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24900574598687916
Fold 2 IBS: 0.200322207738425
Fold 3 IBS: 0.20666582272059178
Fold 4 IBS: 0.24160407963613872
Fold 5 IBS: 0.23964332065507346
[I 2024-04-16 21:02:27,691] Trial 47 finished with value: 0.22744823534742165 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 193, 'oob_score': True, 'max_samples': 0.8252659010917025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18709868233605237}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.23233061602902896
Fold 2 IBS: 0.20470776398952695
Fold 3 IBS: 0.24473722549758978
Fold 4 IBS: 0.23554082329183057
Fold 5 IBS: 0.22266798632628182
[I 2024-04-16 21:02:41,797] Trial 48 finished with value: 0.22799688302685164 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.7486071388218823, 'max_features': None, 'min_weight_fraction_leaf': 0.3316489763494004}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22140751210407167
Fold 2 IBS: 0.18446093935852728
Fold 3 IBS: 0.23819663142832964
Fold 4 IBS: 0.21304733351095642
Fold 5 IBS: 0.21354093321412873
[I 2024-04-16 21:03:09,885] Trial 49 finished with value: 0.21413066992320276 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.9104681524496127, 'max_features': None, 'min_weight_fraction_leaf': 0.2085463208364724}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22233291067700658
Fold 2 IBS: 0.18478464545596854
Fold 3 IBS: 0.23971913759043886
Fold 4 IBS: 0.21278768542579282
Fold 5 IBS: 0.21478540299561258
[I 2024-04-16 21:03:35,713] Trial 50 finished with value: 0.2148819564289639 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.8824600753169473, 'max_features': None, 'min_weight_fraction_leaf': 0.21462027388465296}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22734559235093124
Fold 2 IBS: 0.18318936929294466
Fold 3 IBS: 0.23297167248730816
Fold 4 IBS: 0.21245702972369868
Fold 5 IBS: 0.21111254387628536
[I 2024-04-16 21:04:06,402] Trial 51 finished with value: 0.21341524154623365 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.9625411717608587, 'max_features': None, 'min_weight_fraction_leaf': 0.23293844782753054}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22346864077437148
Fold 2 IBS: 0.18390840845858739
Fold 3 IBS: 0.23332464818299495
Fold 4 IBS: 0.2131988499365954
Fold 5 IBS: 0.21069690375604289
[I 2024-04-16 21:04:37,878] Trial 52 finished with value: 0.21291949022171847 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 352, 'oob_score': True, 'max_samples': 0.9641055300734946, 'max_features': None, 'min_weight_fraction_leaf': 0.23607641839390603}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22838038692070342
Fold 2 IBS: 0.18230534132767368
Fold 3 IBS: 0.2331843783263773
Fold 4 IBS: 0.21294291300198875
Fold 5 IBS: 0.21054265660575297
[I 2024-04-16 21:05:15,928] Trial 53 finished with value: 0.21347113523649922 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': None, 'min_weight_fraction_leaf': 0.17637754776024273}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2284275692142271
Fold 2 IBS: 0.18246107795839966
Fold 3 IBS: 0.23265587552703618
Fold 4 IBS: 0.2133213439680979
Fold 5 IBS: 0.21041220939694896
[I 2024-04-16 21:06:00,004] Trial 54 finished with value: 0.21345561521294196 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.967029635289036, 'max_features': None, 'min_weight_fraction_leaf': 0.13017229949607742}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24655826225731184
Fold 2 IBS: 0.23223212769483395
Fold 3 IBS: 0.2299109075503006
Fold 4 IBS: 0.24125502336117552
Fold 5 IBS: 0.23025881880809368
[I 2024-04-16 21:06:06,762] Trial 55 finished with value: 0.23604302793434312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.26065411177594827, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13302957117693476}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2288773906468273
Fold 2 IBS: 0.182557427331127
Fold 3 IBS: 0.23247262815573858
Fold 4 IBS: 0.21385954181177394
Fold 5 IBS: 0.2108105644361973
[I 2024-04-16 21:06:38,517] Trial 56 finished with value: 0.2137155104763328 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.975784426896677, 'max_features': None, 'min_weight_fraction_leaf': 0.10165017984714692}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2517864102395247
Fold 2 IBS: 0.21311790899482444
Fold 3 IBS: 0.21465108435997157
Fold 4 IBS: 0.25309517297336526
Fold 5 IBS: 0.2417203119244569
[I 2024-04-16 21:06:45,071] Trial 57 finished with value: 0.23487417769842858 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.47523615475756226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0456877909412422}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2243353112407589
Fold 2 IBS: 0.18266218635612108
Fold 3 IBS: 0.23393999495208184
Fold 4 IBS: 0.2149406342270133
Fold 5 IBS: 0.21045670202420302
[I 2024-04-16 21:07:23,015] Trial 58 finished with value: 0.21326696576003562 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.9713216893041037, 'max_features': None, 'min_weight_fraction_leaf': 0.17261347912606032}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24689331510957085
Fold 2 IBS: 0.20349936746264044
Fold 3 IBS: 0.20741536012216769
Fold 4 IBS: 0.24027185216325905
Fold 5 IBS: 0.23849175782634383
[I 2024-04-16 21:07:29,845] Trial 59 finished with value: 0.2273143305367964 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.9111341643808946, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15152628104819157}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23161246102067778
Fold 2 IBS: 0.18315762337529268
Fold 3 IBS: 0.23355670246252003
Fold 4 IBS: 0.2141622801821901
Fold 5 IBS: 0.21203217214938297
[I 2024-04-16 21:08:01,299] Trial 60 finished with value: 0.2149042478380127 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.8718303197272472, 'max_features': None, 'min_weight_fraction_leaf': 0.23327466883167086}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22544682915255349
Fold 2 IBS: 0.1837835452877901
Fold 3 IBS: 0.2340793656204444
Fold 4 IBS: 0.2134652558712757
Fold 5 IBS: 0.21112250446162584
[I 2024-04-16 21:08:32,761] Trial 61 finished with value: 0.21357950007873788 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.9574526723194436, 'max_features': None, 'min_weight_fraction_leaf': 0.16996612592674035}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23566977171208375
Fold 2 IBS: 0.18355373888054702
Fold 3 IBS: 0.23122032354257444
Fold 4 IBS: 0.2166971166015121
Fold 5 IBS: 0.21225529499203713
[I 2024-04-16 21:09:01,935] Trial 62 finished with value: 0.2158792491457509 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.9692513608661454, 'max_features': None, 'min_weight_fraction_leaf': 0.10901914015734161}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22018115372329825
Fold 2 IBS: 0.18426413954689186
Fold 3 IBS: 0.234485531054646
Fold 4 IBS: 0.2145039808669085
Fold 5 IBS: 0.21463282350485688
[I 2024-04-16 21:09:23,659] Trial 63 finished with value: 0.21361352573932027 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8078307550305597, 'max_features': None, 'min_weight_fraction_leaf': 0.17457092877839805}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.2365430487443625
Fold 2 IBS: 0.18238280317098843
Fold 3 IBS: 0.2322276544017584
Fold 4 IBS: 0.21380685041046066
Fold 5 IBS: 0.21115528132467798
[I 2024-04-16 21:09:59,603] Trial 64 finished with value: 0.21522312761044962 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.9369908825823273, 'max_features': None, 'min_weight_fraction_leaf': 0.19119487575645203}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2545794604503248
Fold 2 IBS: 0.18515187912067008
Fold 3 IBS: 0.22861527937785475
Fold 4 IBS: 0.22050482646274178
Fold 5 IBS: 0.2129134229864224
[I 2024-04-16 21:10:42,663] Trial 65 finished with value: 0.22035297367960277 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 362, 'oob_score': True, 'max_samples': 0.9998359499913109, 'max_features': None, 'min_weight_fraction_leaf': 0.1490943973635694}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22654845800464724
Fold 2 IBS: 0.18332141958706227
Fold 3 IBS: 0.2350631328838295
Fold 4 IBS: 0.21236321104852912
Fold 5 IBS: 0.21200214915706886
[I 2024-04-16 21:11:16,806] Trial 66 finished with value: 0.2138596741362274 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8962905931034715, 'max_features': None, 'min_weight_fraction_leaf': 0.0680516900187007}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2314909050987209
Fold 2 IBS: 0.20249096930835778
Fold 3 IBS: 0.23980167405092054
Fold 4 IBS: 0.2353173847496087
Fold 5 IBS: 0.2224605814306102
[I 2024-04-16 21:11:31,089] Trial 67 finished with value: 0.22631230292764365 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.576072702219687, 'max_features': None, 'min_weight_fraction_leaf': 0.23671139187646353}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23493478177072255
Fold 2 IBS: 0.1839771658107539
Fold 3 IBS: 0.2327966378875902
Fold 4 IBS: 0.21470499176958288
Fold 5 IBS: 0.21135088245166292
[I 2024-04-16 21:12:27,935] Trial 68 finished with value: 0.21555289193806249 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.9745293218944675, 'max_features': None, 'min_weight_fraction_leaf': 0.2208990376756659}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24543506602157308
Fold 2 IBS: 0.20317035895085483
Fold 3 IBS: 0.20373744028936427
Fold 4 IBS: 0.2408108283305109
Fold 5 IBS: 0.23682283690526376
[I 2024-04-16 21:12:32,676] Trial 69 finished with value: 0.22599530609951338 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.8624070878492855, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1990248466441951}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2503935277219034
Fold 2 IBS: 0.20812254306242206
Fold 3 IBS: 0.2113368150498763
Fold 4 IBS: 0.249610089701322
Fold 5 IBS: 0.24046537193598522
[I 2024-04-16 21:12:37,800] Trial 70 finished with value: 0.2319856694943018 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9186596987029689, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11544109176287089}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.221575371693387
Fold 2 IBS: 0.18398808173473347
Fold 3 IBS: 0.23724504533105953
Fold 4 IBS: 0.214033992760505
Fold 5 IBS: 0.21096749762165287
[I 2024-04-16 21:13:07,493] Trial 71 finished with value: 0.2135619978282676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.9723894444805646, 'max_features': None, 'min_weight_fraction_leaf': 0.2730206487158777}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22000227604484365
Fold 2 IBS: 0.1835976512867323
Fold 3 IBS: 0.23496758393840209
Fold 4 IBS: 0.2108901768233098
Fold 5 IBS: 0.21502432185948614
[I 2024-04-16 21:13:24,845] Trial 72 finished with value: 0.21289640199055476 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.9429494364281713, 'max_features': None, 'min_weight_fraction_leaf': 0.26970631759176494}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22727419395708034
Fold 2 IBS: 0.1871701080786577
Fold 3 IBS: 0.2378340481827281
Fold 4 IBS: 0.2289741531942034
Fold 5 IBS: 0.22120111363123252
[I 2024-04-16 21:13:45,443] Trial 73 finished with value: 0.22049072340878037 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.9341055458028956, 'max_features': None, 'min_weight_fraction_leaf': 0.31471941963288985}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22389252687104882
Fold 2 IBS: 0.18478568946187152
Fold 3 IBS: 0.23569319407407555
Fold 4 IBS: 0.21383105927421142
Fold 5 IBS: 0.21188816578028835
[I 2024-04-16 21:14:25,709] Trial 74 finished with value: 0.21401812709229912 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 476, 'oob_score': True, 'max_samples': 0.946932527578757, 'max_features': None, 'min_weight_fraction_leaf': 0.24504456019566914}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.21854302798549347
Fold 2 IBS: 0.18176372907932323
Fold 3 IBS: 0.23671374300002862
Fold 4 IBS: 0.21422935554752687
Fold 5 IBS: 0.21083967154267064
[I 2024-04-16 21:14:52,424] Trial 75 finished with value: 0.21241790543100855 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 288, 'oob_score': True, 'max_samples': 0.9803084469016909, 'max_features': None, 'min_weight_fraction_leaf': 0.13142931899110993}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2197445619216238
Fold 2 IBS: 0.18503554254500237
Fold 3 IBS: 0.23931664349279788
Fold 4 IBS: 0.21161636970789327
Fold 5 IBS: 0.2155020163620093
[I 2024-04-16 21:15:24,164] Trial 76 finished with value: 0.21424302680586535 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 293, 'oob_score': True, 'max_samples': 0.8898157454998676, 'max_features': None, 'min_weight_fraction_leaf': 0.04187570620310249}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2327743668403808
Fold 2 IBS: 0.1821560057823301
Fold 3 IBS: 0.23089143622316666
Fold 4 IBS: 0.23577008510470598
Fold 5 IBS: 0.2235347877710858
[I 2024-04-16 21:16:36,140] Trial 77 finished with value: 0.22102533634433388 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.9879662653142723, 'max_features': None, 'min_weight_fraction_leaf': 0.2732568395879575}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22818707588004375
Fold 2 IBS: 0.19020975012058644
Fold 3 IBS: 0.23714209938276803
Fold 4 IBS: 0.2286788294533738
Fold 5 IBS: 0.21849469879449682
[I 2024-04-16 21:17:22,463] Trial 78 finished with value: 0.2205424907262538 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.8577519434160554, 'max_features': None, 'min_weight_fraction_leaf': 0.2950875024553569}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23474728243730542
Fold 2 IBS: 0.1971796499722597
Fold 3 IBS: 0.22834092402557343
Fold 4 IBS: 0.23413287196690447
Fold 5 IBS: 0.2205931708782621
[I 2024-04-16 21:17:49,356] Trial 79 finished with value: 0.222998779856061 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.5125421624254995, 'max_features': None, 'min_weight_fraction_leaf': 0.09061426277200699}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.2511057207255618
Fold 2 IBS: 0.21572593535559278
Fold 3 IBS: 0.2149073004231141
Fold 4 IBS: 0.2472468833843753
Fold 5 IBS: 0.24247425822381166
[I 2024-04-16 21:18:11,915] Trial 80 finished with value: 0.23429201962249113 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.3618038809495957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15390327148267055}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22731065610063553
Fold 2 IBS: 0.18233470119562936
Fold 3 IBS: 0.23388585350331287
Fold 4 IBS: 0.21305351886000728
Fold 5 IBS: 0.21153134197254575
[I 2024-04-16 21:19:06,532] Trial 81 finished with value: 0.21362321432642614 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9436804929256887, 'max_features': None, 'min_weight_fraction_leaf': 0.12227771301430333}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2272092638449265
Fold 2 IBS: 0.18337145552397865
Fold 3 IBS: 0.23253451313019002
Fold 4 IBS: 0.2138892087318099
Fold 5 IBS: 0.21064394129949776
[I 2024-04-16 21:19:45,752] Trial 82 finished with value: 0.21352967650608057 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9739450345174413, 'max_features': None, 'min_weight_fraction_leaf': 0.13403887256843836}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22274585720905865
Fold 2 IBS: 0.1844029972495469
Fold 3 IBS: 0.23578817469856042
Fold 4 IBS: 0.21351903584251283
Fold 5 IBS: 0.2127567489010132
[I 2024-04-16 21:20:26,041] Trial 83 finished with value: 0.2138425627801384 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.9124790440575847, 'max_features': None, 'min_weight_fraction_leaf': 0.16278108493661606}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2202096426617108
Fold 2 IBS: 0.18300193402384377
Fold 3 IBS: 0.23678774176994796
Fold 4 IBS: 0.21045698381793299
Fold 5 IBS: 0.21165170888809465
[I 2024-04-16 21:22:28,311] Trial 84 finished with value: 0.21242160223230605 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.936102238020355, 'max_features': None, 'min_weight_fraction_leaf': 0.2119155188772585}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.21864119730769158
Fold 2 IBS: 0.18332295425049822
Fold 3 IBS: 0.23624932020049083
Fold 4 IBS: 0.21147766575005164
Fold 5 IBS: 0.21180476450696664
[I 2024-04-16 21:28:51,753] Trial 85 finished with value: 0.21229918040313978 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.9290276329324785, 'max_features': None, 'min_weight_fraction_leaf': 0.20767416366171196}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22157963241090176
Fold 2 IBS: 0.18471642393517332
Fold 3 IBS: 0.23692790272940076
Fold 4 IBS: 0.2129824811604961
Fold 5 IBS: 0.21206997240184605
[I 2024-04-16 21:29:14,856] Trial 86 finished with value: 0.21365528252756358 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.9228769430188052, 'max_features': None, 'min_weight_fraction_leaf': 0.21001587254602957}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22291669368529446
Fold 2 IBS: 0.182919208879211
Fold 3 IBS: 0.2388503936972904
Fold 4 IBS: 0.2158328741690931
Fold 5 IBS: 0.21059528283696147
[I 2024-04-16 21:29:30,340] Trial 87 finished with value: 0.21422289065357009 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.9992791729154259, 'max_features': None, 'min_weight_fraction_leaf': 0.2508797456646947}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25078768869857776
Fold 2 IBS: 0.2106109982817939
Fold 3 IBS: 0.21209311522476643
Fold 4 IBS: 0.2508930677647447
Fold 5 IBS: 0.2396844528546169
[I 2024-04-16 21:29:32,897] Trial 88 finished with value: 0.23281386456489997 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.8919471551124474, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2208845327776338}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25097719650425315
Fold 2 IBS: 0.21314574899449434
Fold 3 IBS: 0.21417231974570053
Fold 4 IBS: 0.24960112806534465
Fold 5 IBS: 0.23897071968187011
[I 2024-04-16 21:29:35,703] Trial 89 finished with value: 0.23337342259833255 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.7625776406001812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27140964339693613}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2245068533940247
Fold 2 IBS: 0.18699761355556005
Fold 3 IBS: 0.23544042396212175
Fold 4 IBS: 0.21923587620229615
Fold 5 IBS: 0.21746532566897547
[I 2024-04-16 21:29:51,499] Trial 90 finished with value: 0.2167292185565956 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 308, 'oob_score': True, 'max_samples': 0.8012706364382673, 'max_features': None, 'min_weight_fraction_leaf': 0.23491486759055114}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2218234667655608
Fold 2 IBS: 0.18409612316964802
Fold 3 IBS: 0.23464760900884943
Fold 4 IBS: 0.2117828169055223
Fold 5 IBS: 0.2103391213040047
[I 2024-04-16 21:30:12,322] Trial 91 finished with value: 0.21253782743071703 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.9410520587040254, 'max_features': None, 'min_weight_fraction_leaf': 0.1785736177001936}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22650071929198848
Fold 2 IBS: 0.18423351453669495
Fold 3 IBS: 0.23455340947340386
Fold 4 IBS: 0.2132023845394669
Fold 5 IBS: 0.21079535139402752
[I 2024-04-16 21:30:33,976] Trial 92 finished with value: 0.21385707584711638 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.9462078683111473, 'max_features': None, 'min_weight_fraction_leaf': 0.18398630290568166}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2206749867203408
Fold 2 IBS: 0.1845112548902161
Fold 3 IBS: 0.2346107050489519
Fold 4 IBS: 0.2108494294764449
Fold 5 IBS: 0.21185476519664903
[I 2024-04-16 21:30:58,836] Trial 93 finished with value: 0.21250022826652054 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.9344189667836965, 'max_features': None, 'min_weight_fraction_leaf': 0.25854173047664814}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.21954476841343637
Fold 2 IBS: 0.18528849913355389
Fold 3 IBS: 0.2376539942951079
Fold 4 IBS: 0.21407967576842526
Fold 5 IBS: 0.21415642969000542
[I 2024-04-16 21:31:15,689] Trial 94 finished with value: 0.21414467346010574 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 273, 'oob_score': True, 'max_samples': 0.8713272061326163, 'max_features': None, 'min_weight_fraction_leaf': 0.2544497221932043}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2208107209861332
Fold 2 IBS: 0.18302956342153184
Fold 3 IBS: 0.23391990270287968
Fold 4 IBS: 0.21268167805826516
Fold 5 IBS: 0.21308598369318132
[I 2024-04-16 21:31:34,378] Trial 95 finished with value: 0.21270556977239824 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.9058370293437961, 'max_features': None, 'min_weight_fraction_leaf': 0.19807593185105676}. Best is trial 85 with value: 0.21229918040313978.

Fold 1 IBS: 0.21975345965751325
Fold 2 IBS: 0.1826687616539912
Fold 3 IBS: 0.23593232323623828
Fold 4 IBS: 0.21692323202986982
Fold 5 IBS: 0.2157946933853038
[I 2024-04-16 21:31:49,454] Trial 96 finished with value: 0.21421449399258327 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.8401991280225705, 'max_features': None, 'min_weight_fraction_leaf': 0.20291905202477475}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22595559817931396
Fold 2 IBS: 0.18811290557691393
Fold 3 IBS: 0.23790732230802805
Fold 4 IBS: 0.22652570350197412
Fold 5 IBS: 0.21929538367243218
[I 2024-04-16 21:32:02,258] Trial 97 finished with value: 0.21955938264773245 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.9001142343235446, 'max_features': None, 'min_weight_fraction_leaf': 0.3126608885366039}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.219856246176777
Fold 2 IBS: 0.18353273410232165
Fold 3 IBS: 0.2355137490033137
Fold 4 IBS: 0.21361316808033728
Fold 5 IBS: 0.2140273787654496
[I 2024-04-16 21:32:26,406] Trial 98 finished with value: 0.21330865522563985 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.930993873060305, 'max_features': None, 'min_weight_fraction_leaf': 0.2803881279308147}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25162904138051667
Fold 2 IBS: 0.21372129222801167
Fold 3 IBS: 0.21584553623530486
Fold 4 IBS: 0.24661972756352624
Fold 5 IBS: 0.2419641213954559
[I 2024-04-16 21:32:29,468] Trial 99 finished with value: 0.23395594376056308 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7146385057934307, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2661847294368132}. Best is trial 85 with value: 0.21229918040313978.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.21229918040313978], datetime_start=datetime.datetime(2024, 4, 16, 21, 22, 28, 323030), datetime_complete=datetime.datetime(2024, 4, 16, 21, 28, 51, 750908), params={'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.9290276329324785, 'max_features': None, 'min_weight_fraction_leaf': 0.20767416366171196}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for IBS:
 0.21229918040313978

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.847
train_ibs:  0.212

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [58]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=16, max_features='auto', max_leaf_nodes=14,
                     max_samples=0.9873533850424658, min_samples_leaf=4,
                     min_samples_split=8,
                     min_weight_fraction_leaf=0.04287202412707603,
                     n_estimators=441, random_state=123, warm_start=True)

test_cindex:  0.54

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=11,
                     max_samples=0.9290276329324785, min_samples_leaf=20,
                     min_samples_split=9,
                     min_weight_fraction_leaf=0.20767416366171196,
                     n_estimators=268, oob_score=True, random_state=123)

test_ibs:  0.262

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [60]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [61]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 21:32:37,264] A new study created in memory with name: no-name-2decf87a-bcac-44d3-b6a8-88cbceddc6f6

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 21:32:38,122] Trial 0 finished with value: 0.716790225055755 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:40,048] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 21:32:44,256] Trial 2 finished with value: 0.637634842816299 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 21:32:44,651] Trial 3 finished with value: 0.7443588775438851 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:47,407] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:49,164] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 21:32:50,156] Trial 6 finished with value: 0.7034666689139027 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5095057034220533
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 21:32:52,440] Trial 7 finished with value: 0.5777346993743705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 21:32:52,619] Trial 8 finished with value: 0.7256957651909646 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 21:32:59,023] Trial 9 finished with value: 0.6059266344558226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:32:59,797] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5159362549800797
Fold 2 C-index: 0.560077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 21:32:59,989] Trial 11 finished with value: 0.6662340928785145 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 21:33:00,324] Trial 12 finished with value: 0.7197009443517154 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 21:33:00,845] Trial 13 finished with value: 0.72821263434496 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 21:33:01,386] Trial 14 finished with value: 0.7120489026779355 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9015509519801813, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 21:33:01,911] Trial 15 finished with value: 0.7572849484519277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.10514124205272785}. Best is trial 15 with value: 0.7572849484519277.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:33:02,543] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6778661833429002, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 21:33:03,033] Trial 17 finished with value: 0.7059353800436845 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 100, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3861349103797888, 'min_weight_fraction_leaf': 0.08960575345471988}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:33:07,195] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 289, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.0015754650744169152}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 21:33:07,888] Trial 19 finished with value: 0.6786787744649703 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 187, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6687006907779914, 'min_weight_fraction_leaf': 0.2047592648179435}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 21:33:08,508] Trial 20 finished with value: 0.7839268317994365 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7175509123723454, 'min_weight_fraction_leaf': 0.10521853896660721}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 21:33:08,930] Trial 21 finished with value: 0.7300192593991303 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7031450748447657, 'min_weight_fraction_leaf': 0.09403903585726361}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 21:33:09,582] Trial 22 finished with value: 0.7824269267844081 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6098864513030943, 'min_weight_fraction_leaf': 0.12170977787094135}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 21:33:09,888] Trial 23 finished with value: 0.7877806145769775 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.612388364912981, 'min_weight_fraction_leaf': 0.04561569622889031}. Best is trial 23 with value: 0.7877806145769775.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 21:33:10,259] Trial 24 finished with value: 0.7999244832738667 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 28, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5945370691033937, 'min_weight_fraction_leaf': 0.053281515068204915}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.49203187250996017
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.48068669527896996
[I 2024-04-16 21:33:10,494] Trial 25 finished with value: 0.63181873270089 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4547673780685811, 'min_weight_fraction_leaf': 0.04996091221009652}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 21:33:11,452] Trial 26 finished with value: 0.6663763013235233 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 45, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2871142790618468, 'min_weight_fraction_leaf': 0.037039062886846254}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 21:33:11,768] Trial 27 finished with value: 0.7922020480583813 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 28, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5158783707916587, 'min_weight_fraction_leaf': 0.06598691661059801}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:33:12,010] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5202420447021523, 'min_weight_fraction_leaf': 0.46961689585527955}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 21:33:13,475] Trial 29 finished with value: 0.7702942146882898 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3719168657740124, 'min_weight_fraction_leaf': 0.0713932172807959}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7510729613733905
[I 2024-04-16 21:33:13,741] Trial 30 finished with value: 0.718731646723884 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 40, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5897285086805036, 'min_weight_fraction_leaf': 0.021168508687250828}. Best is trial 24 with value: 0.7999244832738667.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-16 21:33:14,250] Trial 31 finished with value: 0.7450836287108459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6115041201105692, 'min_weight_fraction_leaf': 0.07529457384788989}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 21:33:14,710] Trial 32 finished with value: 0.7891534508186784 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 106, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5041709909476946, 'min_weight_fraction_leaf': 0.06275815026057982}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 21:33:14,932] Trial 33 finished with value: 0.7778383668899079 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5060458087305748, 'min_weight_fraction_leaf': 0.05994930115816848}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 21:33:15,318] Trial 34 finished with value: 0.7450364060708232 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 62, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3919948296728538, 'min_weight_fraction_leaf': 0.023576029209776687}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 21:33:16,250] Trial 35 finished with value: 0.6618125355016858 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 109, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4662710037037924, 'min_weight_fraction_leaf': 0.19476322320546924}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:33:16,845] Trial 36 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 28, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5268973035148778, 'min_weight_fraction_leaf': 0.38971770475262413}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 21:33:17,410] Trial 37 finished with value: 0.6460461608102859 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6401214919324493, 'min_weight_fraction_leaf': 0.2889936764724038}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 21:33:17,957] Trial 38 finished with value: 0.7517656861973904 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 124, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3198045057515263, 'min_weight_fraction_leaf': 0.06699213680332672}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.4903100775193798
Fold 3 C-index: 0.30425531914893617
Fold 4 C-index: 0.38022813688212925
Fold 5 C-index: 0.5364806866952789
[I 2024-04-16 21:33:18,223] Trial 39 finished with value: 0.45221500341169457 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5513036300755328, 'min_weight_fraction_leaf': 0.008478210005256219}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:33:19,688] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.43468184041368385, 'min_weight_fraction_leaf': 0.42733722871780283}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 21:33:22,431] Trial 41 finished with value: 0.786556444150027 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 94, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6273061563283064, 'min_weight_fraction_leaf': 0.10637509234156475}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 21:33:24,386] Trial 42 finished with value: 0.7790118129920596 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 56, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6164425687958124, 'min_weight_fraction_leaf': 0.039624372585458756}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7267441860465116
Fold 3 C-index: 0.8531914893617021
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 21:33:25,448] Trial 43 finished with value: 0.7182793874400513 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 43, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5600036197598728, 'min_weight_fraction_leaf': 0.08742449741166494}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 21:33:27,393] Trial 44 finished with value: 0.6220741639573587 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 214, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4844175747650499, 'min_weight_fraction_leaf': 0.12204423321537092}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 21:33:29,112] Trial 45 finished with value: 0.7157517489250119 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7291844385738098, 'min_weight_fraction_leaf': 0.1516538096539411}. Best is trial 24 with value: 0.7999244832738667.

Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 21:33:31,968] Trial 46 finished with value: 0.7975395138249034 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7438723611436409, 'min_weight_fraction_leaf': 0.03993350527314018}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 21:33:33,482] Trial 47 finished with value: 0.6647065921586429 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 26, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.42581868302241566, 'min_weight_fraction_leaf': 0.03606885164861798}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 21:33:35,943] Trial 48 finished with value: 0.7398991153868522 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8248732462756444, 'min_weight_fraction_leaf': 0.05743142223461807}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 21:33:37,781] Trial 49 finished with value: 0.7740102565229516 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7375840189864764, 'min_weight_fraction_leaf': 0.02900897691743311}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 21:33:41,747] Trial 50 finished with value: 0.8061742964895082 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8580859398770397, 'min_weight_fraction_leaf': 0.14067466804198955}. Best is trial 50 with value: 0.8061742964895082.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9141630901287554
[I 2024-04-16 21:33:46,485] Trial 51 finished with value: 0.8345109680877927 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8650780732103325, 'min_weight_fraction_leaf': 0.07836530237930157}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 21:33:50,239] Trial 52 finished with value: 0.8118997310422689 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 382, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9368700755827909, 'min_weight_fraction_leaf': 0.13447102711070466}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 21:33:53,369] Trial 53 finished with value: 0.801596270492346 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9333985785267058, 'min_weight_fraction_leaf': 0.17098721901271324}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 21:33:56,835] Trial 54 finished with value: 0.7883044323959387 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9223836761742507, 'min_weight_fraction_leaf': 0.18255482980599205}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 21:34:00,322] Trial 55 finished with value: 0.6482113869397063 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.850640872005829, 'min_weight_fraction_leaf': 0.22456808619691168}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 21:34:03,832] Trial 56 finished with value: 0.8045156871530021 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9504873149405666, 'min_weight_fraction_leaf': 0.14183520465682528}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 21:34:05,450] Trial 57 finished with value: 0.7476944411137867 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9549982016992005, 'min_weight_fraction_leaf': 0.1632420912078524}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 21:34:12,338] Trial 58 finished with value: 0.7041938058364086 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 289, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9955977767169721, 'min_weight_fraction_leaf': 0.139303061496208}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 21:34:15,003] Trial 59 finished with value: 0.6850776550936483 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9316447705416647, 'min_weight_fraction_leaf': 0.2770418832937534}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 21:34:17,351] Trial 60 finished with value: 0.7659333705752307 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.858061041207964, 'min_weight_fraction_leaf': 0.20492284757517695}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 21:34:19,957] Trial 61 finished with value: 0.8072715857181292 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.895774589556567, 'min_weight_fraction_leaf': 0.13260279061395738}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 21:34:22,070] Trial 62 finished with value: 0.8087820359158744 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981332031409504, 'min_weight_fraction_leaf': 0.13337740856374872}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 21:34:23,932] Trial 63 finished with value: 0.8072173346373459 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.89018545929469, 'min_weight_fraction_leaf': 0.13345593137281736}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 21:34:25,565] Trial 64 finished with value: 0.8039397464932385 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8837514156336624, 'min_weight_fraction_leaf': 0.13743872464484008}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 21:34:26,912] Trial 65 finished with value: 0.8022232887177733 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7835122881802231, 'min_weight_fraction_leaf': 0.11229139643403509}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 21:34:28,163] Trial 66 finished with value: 0.7125273202159338 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 373, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8328417978438267, 'min_weight_fraction_leaf': 0.15095298703120333}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 21:34:29,800] Trial 67 finished with value: 0.8192305249719898 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8966863484745369, 'min_weight_fraction_leaf': 0.08534464991274132}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 21:34:30,764] Trial 68 finished with value: 0.7895818286565903 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.978346026643418, 'min_weight_fraction_leaf': 0.09273408393147946}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 21:34:32,358] Trial 69 finished with value: 0.8102956431944776 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.896331905162175, 'min_weight_fraction_leaf': 0.12035329094677631}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 21:34:33,738] Trial 70 finished with value: 0.8079169388264177 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 270, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9017688247437723, 'min_weight_fraction_leaf': 0.08377148583149059}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 21:34:35,404] Trial 71 finished with value: 0.7983010681646548 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.891832704671649, 'min_weight_fraction_leaf': 0.12184359415244413}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 21:34:37,076] Trial 72 finished with value: 0.8130993617058649 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9102780085257545, 'min_weight_fraction_leaf': 0.07813836666294671}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 21:34:38,403] Trial 73 finished with value: 0.7998076505962926 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 254, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9138857823629444, 'min_weight_fraction_leaf': 0.07760837137280302}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 21:34:39,733] Trial 74 finished with value: 0.8086401909388299 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7932478141389542, 'min_weight_fraction_leaf': 0.09585515657733794}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 21:34:40,986] Trial 75 finished with value: 0.8097308691495133 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.768048780360931, 'min_weight_fraction_leaf': 0.08472098125787089}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 21:34:43,972] Trial 76 finished with value: 0.6077421067160182 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8075950318465789, 'min_weight_fraction_leaf': 0.10238704048789282}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 21:34:45,320] Trial 77 finished with value: 0.8053956752022688 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7673803604130273, 'min_weight_fraction_leaf': 0.11299645952197773}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 21:34:46,617] Trial 78 finished with value: 0.8088475970325533 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 202, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8265609743395299, 'min_weight_fraction_leaf': 0.09652130656141297}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:34:47,448] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9626257579282349, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 21:34:48,165] Trial 80 finished with value: 0.7313420533362782 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8393510141017606, 'min_weight_fraction_leaf': 0.07992117300354869}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 21:34:49,320] Trial 81 finished with value: 0.812638992208535 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7918630780504825, 'min_weight_fraction_leaf': 0.10229656223682107}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 21:34:50,554] Trial 82 finished with value: 0.8097453262522389 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8756895757277906, 'min_weight_fraction_leaf': 0.11757230018978515}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 21:34:51,701] Trial 83 finished with value: 0.807919942472151 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8726637848385762, 'min_weight_fraction_leaf': 0.11382370857816454}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7725321888412017
[I 2024-04-16 21:34:52,942] Trial 84 finished with value: 0.7704249207701752 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8061519296879504, 'min_weight_fraction_leaf': 0.09515235358222952}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 21:34:53,684] Trial 85 finished with value: 0.7697903027420463 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7614101494119764, 'min_weight_fraction_leaf': 0.05368501986833329}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 21:34:54,535] Trial 86 finished with value: 0.7980794918103985 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8672025396777255, 'min_weight_fraction_leaf': 0.15838375423479073}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 21:34:56,403] Trial 87 finished with value: 0.8168764432002176 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.821099320531621, 'min_weight_fraction_leaf': 0.07219095881107078}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 21:35:01,487] Trial 88 finished with value: 0.6418944800226886 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9410457375171901, 'min_weight_fraction_leaf': 0.016074649059118228}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 21:35:04,184] Trial 89 finished with value: 0.8111823792625452 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9747877453952127, 'min_weight_fraction_leaf': 0.07239963989752378}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 21:35:05,830] Trial 90 finished with value: 0.8031613891936974 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9993570244260745, 'min_weight_fraction_leaf': 0.06937148653050808}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 21:35:08,394] Trial 91 finished with value: 0.8136959302089742 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9761926707915443, 'min_weight_fraction_leaf': 0.07539349300221282}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 21:35:10,752] Trial 92 finished with value: 0.8135443171331339 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9178848241272458, 'min_weight_fraction_leaf': 0.06881178939245426}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8969957081545065
[I 2024-04-16 21:35:13,291] Trial 93 finished with value: 0.8168871695376991 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9726464389425372, 'min_weight_fraction_leaf': 0.04860102614756785}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 21:35:16,851] Trial 94 finished with value: 0.8363648293898092 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9661961925179824, 'min_weight_fraction_leaf': 0.05044552883677316}. Best is trial 94 with value: 0.8363648293898092.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:35:20,267] Trial 95 finished with value: 0.8420040749825455 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9149322253821399, 'min_weight_fraction_leaf': 0.0472298750691944}. Best is trial 95 with value: 0.8420040749825455.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 21:35:23,185] Trial 96 finished with value: 0.8420072320634038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9186714469202719, 'min_weight_fraction_leaf': 0.04956115599708024}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 21:35:25,276] Trial 97 finished with value: 0.8063263334084045 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.964556183783718, 'min_weight_fraction_leaf': 0.045349231505527596}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 21:35:26,507] Trial 98 finished with value: 0.8016468008219135 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9181873113334154, 'min_weight_fraction_leaf': 0.0021149043736411396}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851

[I 2024-04-16 21:35:29,997] A new study created in memory with name: no-name-73635a6f-04bb-4293-b5f7-89ca567eb1a9

Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 21:35:29,966] Trial 99 finished with value: 0.833109564461272 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9775205205061748, 'min_weight_fraction_leaf': 0.025836771862969607}. Best is trial 96 with value: 0.8420072320634038.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.8420072320634038], datetime_start=datetime.datetime(2024, 4, 16, 21, 35, 20, 276007), datetime_complete=datetime.datetime(2024, 4, 16, 21, 35, 23, 185284), params={'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9186714469202719, 'min_weight_fraction_leaf': 0.04956115599708024}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=96, value=None)


* Best Score for C-index:
 0.8420072320634038

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2458308290335683
Fold 2 IBS: 0.21843205852973288
Fold 3 IBS: 0.21441509219214497
Fold 4 IBS: 0.2444058540887671
Fold 5 IBS: 0.23326299386163582
[I 2024-04-16 21:35:33,773] Trial 0 finished with value: 0.2312693655411698 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2312693655411698.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-16 21:35:39,206] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2312693655411698.
Fold 1 IBS: 0.2422217804898227
Fold 2 IBS: 0.20604215939156156
Fold 3 IBS: 0.20536348887036088
Fold 4 IBS: 0.23816713819570307
Fold 5 IBS: 0.23443654693516552
[I 2024-04-16 21:35:44,440] Trial 2 finished with value: 0.22524622277652276 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.22524622277652276.
Fold 1 IBS: 0.23997737551317644
Fold 2 IBS: 0.20628917387182416
Fold 3 IBS: 0.19999308418823725
Fold 4 IBS: 0.2364990518088652
Fold 5 IBS: 0.2312952255166902
[I 2024-04-16 21:35:46,747] Trial 3 finished with value: 0.22281078217975864 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-16 21:35:51,959] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-16 21:35:54,038] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2471773923605192
Fold 2 IBS: 0.21732133101414405
Fold 3 IBS: 0.21608483753650748
Fold 4 IBS: 0.2446264041325047
Fold 5 IBS: 0.2336320559523974
[I 2024-04-16 21:35:58,760] Trial 6 finished with value: 0.23176840419921457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24753232495746105
Fold 2 IBS: 0.22863034299161297
Fold 3 IBS: 0.22780059870027192
Fold 4 IBS: 0.24525231645256226
Fold 5 IBS: 0.22980036498615944
[I 2024-04-16 21:36:02,057] Trial 7 finished with value: 0.23580318961761354 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24388792032844758
Fold 2 IBS: 0.20431268727524246
Fold 3 IBS: 0.20272723355028044
Fold 4 IBS: 0.2323397363347534
Fold 5 IBS: 0.24009730434274343
[I 2024-04-16 21:36:02,869] Trial 8 finished with value: 0.2246729763662935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2463750753680711
Fold 2 IBS: 0.23137427725039786
Fold 3 IBS: 0.22881548983290517
Fold 4 IBS: 0.24172449141228589
Fold 5 IBS: 0.23039951809375644
[I 2024-04-16 21:36:08,997] Trial 9 finished with value: 0.2357377703914833 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24657852287672213
Fold 2 IBS: 0.23206316112817363
Fold 3 IBS: 0.23003515681903183
Fold 4 IBS: 0.2412906026999272
Fold 5 IBS: 0.22957933452614643
[I 2024-04-16 21:36:10,625] Trial 10 finished with value: 0.2359093556100002 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24957527092392598
Fold 2 IBS: 0.22095833564497003
Fold 3 IBS: 0.22451358571145658
Fold 4 IBS: 0.23060380529406801
Fold 5 IBS: 0.2239626552625768
[I 2024-04-16 21:36:10,882] Trial 11 finished with value: 0.22992273056739948 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24023311319978927
Fold 2 IBS: 0.20654639843048508
Fold 3 IBS: 0.2105997477995539
Fold 4 IBS: 0.237375222973572
Fold 5 IBS: 0.22992356847238266
[I 2024-04-16 21:36:11,659] Trial 12 finished with value: 0.22493561017515656 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2397712237804985
Fold 2 IBS: 0.21059242308473916
Fold 3 IBS: 0.20295179527005874
Fold 4 IBS: 0.23391501821825889
Fold 5 IBS: 0.22771604186877867
[I 2024-04-16 21:36:13,097] Trial 13 finished with value: 0.2229893004444668 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.23887694209074434
Fold 2 IBS: 0.2134098978318189
Fold 3 IBS: 0.20587933877935985
Fold 4 IBS: 0.23635078736680823
Fold 5 IBS: 0.22529646039343412
[I 2024-04-16 21:36:15,184] Trial 14 finished with value: 0.2239626852924331 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9015509519801813, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.22281078217975864.

Fold 1 IBS: 0.22839809695394112
Fold 2 IBS: 0.20514152743957886
Fold 3 IBS: 0.20092249425472394
Fold 4 IBS: 0.2267763825894776
Fold 5 IBS: 0.2165164172534966
[I 2024-04-16 21:36:17,297] Trial 15 finished with value: 0.21555098369824366 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.10514124205272785}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2467245753421851
Fold 2 IBS: 0.23215086227692838
Fold 3 IBS: 0.22944190979967086
Fold 4 IBS: 0.24159087177588787
Fold 5 IBS: 0.2303525764883273
[I 2024-04-16 21:36:20,014] Trial 16 finished with value: 0.2360521591365999 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6778661833429002, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2388284357689523
Fold 2 IBS: 0.21255562783348272
Fold 3 IBS: 0.19795960994236278
Fold 4 IBS: 0.23366309896652035
Fold 5 IBS: 0.21908035151857583
[I 2024-04-16 21:36:21,550] Trial 17 finished with value: 0.22041742480597878 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 100, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3861349103797888, 'min_weight_fraction_leaf': 0.08960575345471988}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24132280104394047
Fold 2 IBS: 0.21269327432629742
Fold 3 IBS: 0.20049020592168434
Fold 4 IBS: 0.24087378277320573
Fold 5 IBS: 0.22425840634695127
[I 2024-04-16 21:36:23,557] Trial 18 finished with value: 0.22392769408241583 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 99, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3311809976298237, 'min_weight_fraction_leaf': 0.0013669683957226175}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24688611571045718
Fold 2 IBS: 0.23219132054830785
Fold 3 IBS: 0.23027940191796936
Fold 4 IBS: 0.2409026395193649
Fold 5 IBS: 0.22930251676390168
[I 2024-04-16 21:36:26,375] Trial 19 finished with value: 0.23591239889200016 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.10730942678329708, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24536664618236573
Fold 2 IBS: 0.2357094417147659
Fold 3 IBS: 0.21756007685466264
Fold 4 IBS: 0.2351394543483008
Fold 5 IBS: 0.2245456493888334
[I 2024-04-16 21:36:26,695] Trial 20 finished with value: 0.23166425369778568 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3772282506046544, 'min_weight_fraction_leaf': 0.08406658048281501}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2440283698606937
Fold 2 IBS: 0.21764096243387274
Fold 3 IBS: 0.21271440236923256
Fold 4 IBS: 0.23885081521770216
Fold 5 IBS: 0.2333205794826251
[I 2024-04-16 21:36:29,064] Trial 21 finished with value: 0.22931102587282526 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.11712848599628017}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23989681726525797
Fold 2 IBS: 0.21257567014754183
Fold 3 IBS: 0.20496080476015688
Fold 4 IBS: 0.23573527504580374
Fold 5 IBS: 0.2401811583699638
[I 2024-04-16 21:36:30,258] Trial 22 finished with value: 0.22666994511774483 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 85, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.05847692406679354}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24662017777674988
Fold 2 IBS: 0.2321469807414623
Fold 3 IBS: 0.2297372799644881
Fold 4 IBS: 0.2412254547631197
Fold 5 IBS: 0.2298155591809165
[I 2024-04-16 21:36:31,876] Trial 23 finished with value: 0.2359090904853473 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.242935508884002, 'min_weight_fraction_leaf': 0.19289553221610561}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23585018430451674
Fold 2 IBS: 0.20314428554405467
Fold 3 IBS: 0.1987071229364999
Fold 4 IBS: 0.2270924304194166
Fold 5 IBS: 0.2222151698718961
[I 2024-04-16 21:36:35,631] Trial 24 finished with value: 0.21740183861527682 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 221, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4214218271993085, 'min_weight_fraction_leaf': 0.1063490999450386}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23764386500385992
Fold 2 IBS: 0.21572081027096882
Fold 3 IBS: 0.20688911926768339
Fold 4 IBS: 0.23390279551321708
Fold 5 IBS: 0.2244570150053522
[I 2024-04-16 21:36:38,263] Trial 25 finished with value: 0.22372272101221627 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.46423262855736735, 'min_weight_fraction_leaf': 0.03989016828055364}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2466435841775417
Fold 2 IBS: 0.23225630869945743
Fold 3 IBS: 0.22989986339484095
Fold 4 IBS: 0.24118506766749884
Fold 5 IBS: 0.2302270252070719
[I 2024-04-16 21:36:42,681] Trial 26 finished with value: 0.23604236982928217 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2871142790618468, 'min_weight_fraction_leaf': 0.2830550434153414}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24581839690270998
Fold 2 IBS: 0.23209782103745266
Fold 3 IBS: 0.2301979993648951
Fold 4 IBS: 0.24136593180524166
Fold 5 IBS: 0.23032438582493162
[I 2024-04-16 21:36:43,462] Trial 27 finished with value: 0.23596090698704622 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 48, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.1729529760271648, 'min_weight_fraction_leaf': 0.09037604869015846}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24656075558902663
Fold 2 IBS: 0.23213951345883066
Fold 3 IBS: 0.23002825142879788
Fold 4 IBS: 0.2411104649641026
Fold 5 IBS: 0.22975811808319055
[I 2024-04-16 21:36:44,835] Trial 28 finished with value: 0.23591942070478966 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 99, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3965788725022428, 'min_weight_fraction_leaf': 0.46961689585527955}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24630859844407268
Fold 2 IBS: 0.2322956347000389
Fold 3 IBS: 0.22955007442663075
Fold 4 IBS: 0.24141130613962739
Fold 5 IBS: 0.23029996757106383
[I 2024-04-16 21:36:48,858] Trial 29 finished with value: 0.23597311625628672 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5102179166457144, 'min_weight_fraction_leaf': 0.41528561873840175}. Best is trial 15 with value: 0.21555098369824366.

Fold 1 IBS: 0.24189951983836425
Fold 2 IBS: 0.22116291305449884
Fold 3 IBS: 0.21713072638394984
Fold 4 IBS: 0.24023416048014104
Fold 5 IBS: 0.22691624187044754
[I 2024-04-16 21:36:50,939] Trial 30 finished with value: 0.2294687123254803 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5988223393644435, 'min_weight_fraction_leaf': 0.20241101766143602}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24364620279536037
Fold 2 IBS: 0.2205505651382432
Fold 3 IBS: 0.21184589055027794
Fold 4 IBS: 0.24142198209294274
Fold 5 IBS: 0.2268782233658812
[I 2024-04-16 21:36:52,784] Trial 31 finished with value: 0.22886857278854106 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4032327849321123, 'min_weight_fraction_leaf': 0.11708530604258689}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24661093959371452
Fold 2 IBS: 0.2301025933150535
Fold 3 IBS: 0.22780980093586722
Fold 4 IBS: 0.24300904078398428
Fold 5 IBS: 0.230890565198856
[I 2024-04-16 21:36:54,392] Trial 32 finished with value: 0.2356845879654951 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 140, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8550327764351591, 'min_weight_fraction_leaf': 0.09887734225836066}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2424013858898089
Fold 2 IBS: 0.22181355253513207
Fold 3 IBS: 0.21628743919777896
Fold 4 IBS: 0.2454744216544916
Fold 5 IBS: 0.23210919596554697
[I 2024-04-16 21:36:57,312] Trial 33 finished with value: 0.2316171990485517 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7143311025567932, 'min_weight_fraction_leaf': 0.059053506325031944}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2343422980803409
Fold 2 IBS: 0.19726504628882152
Fold 3 IBS: 0.19589228360095498
Fold 4 IBS: 0.22148252413832495
Fold 5 IBS: 0.214706958088969
[I 2024-04-16 21:37:00,774] Trial 34 finished with value: 0.21273782203948227 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 206, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5121057659041139, 'min_weight_fraction_leaf': 0.09009257320408029}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23551743581515994
Fold 2 IBS: 0.1988816220790032
Fold 3 IBS: 0.19713820389502454
Fold 4 IBS: 0.2194355626151018
Fold 5 IBS: 0.2139468393382114
[I 2024-04-16 21:37:05,831] Trial 35 finished with value: 0.2129839327485002 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5035601925130949, 'min_weight_fraction_leaf': 0.030526656384477324}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23568872403345578
Fold 2 IBS: 0.19973786792004417
Fold 3 IBS: 0.19454987157876255
Fold 4 IBS: 0.2220374053163543
Fold 5 IBS: 0.21894163635279854
[I 2024-04-16 21:37:10,621] Trial 36 finished with value: 0.2141911010402831 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5262952246734235, 'min_weight_fraction_leaf': 0.0345815739535376}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.2448880936287523
Fold 2 IBS: 0.19358697937735503
Fold 3 IBS: 0.19135743911323064
Fold 4 IBS: 0.22209877079990858
Fold 5 IBS: 0.2136995510425158
[I 2024-04-16 21:37:18,862] Trial 37 finished with value: 0.21312616679235247 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5274918233702399, 'min_weight_fraction_leaf': 0.02265299373602317}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.2448767682487151
Fold 2 IBS: 0.1940286543150714
Fold 3 IBS: 0.19114962341732433
Fold 4 IBS: 0.22260340040871293
Fold 5 IBS: 0.2137471478793161
[I 2024-04-16 21:37:27,811] Trial 38 finished with value: 0.213281118853828 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 358, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5285575239051581, 'min_weight_fraction_leaf': 0.020652803664130342}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.25250559243829124
Fold 2 IBS: 0.2142865173352782
Fold 3 IBS: 0.2171359677193678
Fold 4 IBS: 0.24416225491761936
Fold 5 IBS: 0.23974411262472503
[I 2024-04-16 21:37:32,839] Trial 39 finished with value: 0.2335668890070563 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6097100988293976, 'min_weight_fraction_leaf': 0.019130885670483717}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.242901108432075
Fold 2 IBS: 0.19697988117930024
Fold 3 IBS: 0.19238091011496858
Fold 4 IBS: 0.22078058275151072
Fold 5 IBS: 0.21495218733382793
[I 2024-04-16 21:37:41,271] Trial 40 finished with value: 0.21359893396233648 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4791645577618608, 'min_weight_fraction_leaf': 0.0694663236398695}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23908968735515912
Fold 2 IBS: 0.1947617350535389
Fold 3 IBS: 0.1930636406143849
Fold 4 IBS: 0.22123635288762244
Fold 5 IBS: 0.21467012929006576
[I 2024-04-16 21:37:48,836] Trial 41 finished with value: 0.2125643090401542 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4831314083966843, 'min_weight_fraction_leaf': 0.06563330905051376}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2396028413626137
Fold 2 IBS: 0.19718848617005288
Fold 3 IBS: 0.1948104348257847
Fold 4 IBS: 0.21837938467562384
Fold 5 IBS: 0.2149288714625758
[I 2024-04-16 21:37:58,369] Trial 42 finished with value: 0.21298200369933024 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5583443788864256, 'min_weight_fraction_leaf': 0.020815822054945837}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2396687176213861
Fold 2 IBS: 0.19612731372046435
Fold 3 IBS: 0.19260264364145704
Fold 4 IBS: 0.21936281835328128
Fold 5 IBS: 0.21697387881345614
[I 2024-04-16 21:38:08,259] Trial 43 finished with value: 0.212947074430009 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 398, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5930099345609534, 'min_weight_fraction_leaf': 0.0495559888649342}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2467168371470764
Fold 2 IBS: 0.23064557906926417
Fold 3 IBS: 0.2276870878947108
Fold 4 IBS: 0.24249203531915456
Fold 5 IBS: 0.2307608809971462
[I 2024-04-16 21:38:14,090] Trial 44 finished with value: 0.2356604840854704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5868150496992739, 'min_weight_fraction_leaf': 0.05755833486941584}. Best is trial 41 with value: 0.2125643090401542.

Fold 1 IBS: 0.24970180838617465
Fold 2 IBS: 0.20711640796461644
Fold 3 IBS: 0.210622445605441
Fold 4 IBS: 0.2398038048480638
Fold 5 IBS: 0.23687430367329662
[I 2024-04-16 21:38:21,534] Trial 45 finished with value: 0.22882375409551847 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 481, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6241818506764952, 'min_weight_fraction_leaf': 0.003649071529300437}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.23201805390304453
Fold 2 IBS: 0.20002733588165444
Fold 3 IBS: 0.19908476397700547
Fold 4 IBS: 0.22074033459452136
Fold 5 IBS: 0.21494542822340232
[I 2024-04-16 21:38:30,399] Trial 46 finished with value: 0.2133631833159256 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5598513951057802, 'min_weight_fraction_leaf': 0.14065807022429982}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25373498445062415
Fold 2 IBS: 0.19975024860475576
Fold 3 IBS: 0.18626200905063714
Fold 4 IBS: 0.23343402582868134
Fold 5 IBS: 0.2162436088485457
[I 2024-04-16 21:38:40,093] Trial 47 finished with value: 0.21788497535664883 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 401, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.456067991993716, 'min_weight_fraction_leaf': 0.04492679621107826}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.24471890993869544
Fold 2 IBS: 0.2177801752519796
Fold 3 IBS: 0.2138769702970347
Fold 4 IBS: 0.24414741845988078
Fold 5 IBS: 0.23442893665869308
[I 2024-04-16 21:38:46,798] Trial 48 finished with value: 0.23099048212125672 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 451, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7258961740431729, 'min_weight_fraction_leaf': 0.08041738051512136}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25137663968626234
Fold 2 IBS: 0.20933386581443944
Fold 3 IBS: 0.2080886887712674
Fold 4 IBS: 0.2390514698710601
Fold 5 IBS: 0.23530782004401327
[I 2024-04-16 21:38:52,392] Trial 49 finished with value: 0.22863169683740853 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 329, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6352263471927108, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2360626460552677
Fold 2 IBS: 0.20623441042932847
Fold 3 IBS: 0.20130662121469356
Fold 4 IBS: 0.22957511854007973
Fold 5 IBS: 0.2179557393265252
[I 2024-04-16 21:38:56,949] Trial 50 finished with value: 0.2182269071131789 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 261, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.49402812735141344, 'min_weight_fraction_leaf': 0.16186576022040558}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25013784901547137
Fold 2 IBS: 0.195316535389084
Fold 3 IBS: 0.18808126103485753
Fold 4 IBS: 0.22936838612837893
Fold 5 IBS: 0.21349776174083104
[I 2024-04-16 21:39:05,169] Trial 51 finished with value: 0.2152803586617246 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5509334567262397, 'min_weight_fraction_leaf': 0.027839511211907052}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2427342211563647
Fold 2 IBS: 0.1958477826874508
Fold 3 IBS: 0.20028177886831744
Fold 4 IBS: 0.22985892846448394
Fold 5 IBS: 0.22177135601929956
[I 2024-04-16 21:39:11,488] Trial 52 finished with value: 0.2180988134391833 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4433955231058734, 'min_weight_fraction_leaf': 0.012876902678362334}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.24397581332160848
Fold 2 IBS: 0.19953500021907264
Fold 3 IBS: 0.18917458509628868
Fold 4 IBS: 0.22839776163972092
Fold 5 IBS: 0.21811042015429574
[I 2024-04-16 21:39:22,971] Trial 53 finished with value: 0.21583871608619729 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5100539037151481, 'min_weight_fraction_leaf': 0.046932235033188746}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2347988257753084
Fold 2 IBS: 0.19668752838656633
Fold 3 IBS: 0.19211546662321186
Fold 4 IBS: 0.21780908681113587
Fold 5 IBS: 0.21515744682466584
[I 2024-04-16 21:39:30,603] Trial 54 finished with value: 0.21131367088417768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5670320468073893, 'min_weight_fraction_leaf': 0.031478107602535506}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.24677947770699765
Fold 2 IBS: 0.23053037304430873
Fold 3 IBS: 0.2275728132543721
Fold 4 IBS: 0.24233405204889266
Fold 5 IBS: 0.23106120652731021
[I 2024-04-16 21:39:37,096] Trial 55 finished with value: 0.23565558451637628 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 392, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5737647614035145, 'min_weight_fraction_leaf': 0.07423158709263047}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.23689214883150628
Fold 2 IBS: 0.2120673796940858
Fold 3 IBS: 0.20315541673905635
Fold 4 IBS: 0.23098032372176497
Fold 5 IBS: 0.22253237757409347
[I 2024-04-16 21:39:42,948] Trial 56 finished with value: 0.22112552931210136 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 418, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.13287864045187167}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2418042867685856
Fold 2 IBS: 0.20876050442208302
Fold 3 IBS: 0.20680932595685791
Fold 4 IBS: 0.23860265094248106
Fold 5 IBS: 0.23053544081685107
[I 2024-04-16 21:39:48,916] Trial 57 finished with value: 0.22530244178137168 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.649610303071809, 'min_weight_fraction_leaf': 0.042873000646334}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2424078057014189
Fold 2 IBS: 0.19483239886955803
Fold 3 IBS: 0.1957006646954686
Fold 4 IBS: 0.22122367318862327
Fold 5 IBS: 0.21799729720859018
[I 2024-04-16 21:39:57,966] Trial 58 finished with value: 0.2144323679327318 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4329823869456646, 'min_weight_fraction_leaf': 0.05393151837123201}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2318227492651181
Fold 2 IBS: 0.2004096906165338
Fold 3 IBS: 0.19250913676453307
Fold 4 IBS: 0.2145149387113131
Fold 5 IBS: 0.21608862724065606
[I 2024-04-16 21:40:06,383] Trial 59 finished with value: 0.21106902851963083 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 251, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.737660433782312, 'min_weight_fraction_leaf': 0.00011778406738288671}. Best is trial 59 with value: 0.21106902851963083.

Fold 1 IBS: 0.24516656524539981
Fold 2 IBS: 0.21062905264741455
Fold 3 IBS: 0.20928713648563754
Fold 4 IBS: 0.24177268946133224
Fold 5 IBS: 0.23349939521162735
[I 2024-04-16 21:40:12,379] Trial 60 finished with value: 0.2280709678102823 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 382, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7740796078428375, 'min_weight_fraction_leaf': 0.004254061138558238}. Best is trial 59 with value: 0.21106902851963083.
Fold 1 IBS: 0.23239287585025117
Fold 2 IBS: 0.19481155216054105
Fold 3 IBS: 0.19221809734433284
Fold 4 IBS: 0.21072513374212
Fold 5 IBS: 0.21430420045958357
[I 2024-04-16 21:40:23,847] Trial 61 finished with value: 0.20889037191136572 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 258, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7377275929061544, 'min_weight_fraction_leaf': 0.030622013808595125}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.23699492184296508
Fold 2 IBS: 0.20040108239906124
Fold 3 IBS: 0.19473792994851583
Fold 4 IBS: 0.2211524352297746
Fold 5 IBS: 0.21193828813811452
[I 2024-04-16 21:40:33,465] Trial 62 finished with value: 0.21304493151168624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6744371054295076, 'min_weight_fraction_leaf': 0.016590925140165264}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.23928053090982188
Fold 2 IBS: 0.1936596610783976
Fold 3 IBS: 0.1908565913097194
Fold 4 IBS: 0.2136596034157615
Fold 5 IBS: 0.21619632218993348
[I 2024-04-16 21:40:49,090] Trial 63 finished with value: 0.21073054178072675 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 462, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7351622406813987, 'min_weight_fraction_leaf': 0.0003006902136090811}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24020476969246154
Fold 2 IBS: 0.19629415252007748
Fold 3 IBS: 0.19025094185398114
Fold 4 IBS: 0.21475012076783115
Fold 5 IBS: 0.21301644327935212
[I 2024-04-16 21:41:14,199] Trial 64 finished with value: 0.21090328562274072 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 476, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7465470505675268, 'min_weight_fraction_leaf': 0.0023272127300384103}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.22993405190596755
Fold 2 IBS: 0.1998559263223298
Fold 3 IBS: 0.19199793628872658
Fold 4 IBS: 0.21593343290217692
Fold 5 IBS: 0.21578188257171663
[I 2024-04-16 21:41:40,280] Trial 65 finished with value: 0.2107006459981835 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 494, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7459236633132993, 'min_weight_fraction_leaf': 0.007694946674736216}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24633591302363841
Fold 2 IBS: 0.23213986158018776
Fold 3 IBS: 0.2295520278725056
Fold 4 IBS: 0.24147959530165872
Fold 5 IBS: 0.2302765128959233
[I 2024-04-16 21:41:47,430] Trial 66 finished with value: 0.23595678213478277 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8287742581608164, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24369000739500146
Fold 2 IBS: 0.21434232747391735
Fold 3 IBS: 0.21139458332988464
Fold 4 IBS: 0.24232956272573275
Fold 5 IBS: 0.2345267106479697
[I 2024-04-16 21:41:56,288] Trial 67 finished with value: 0.22925663831450116 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 454, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7522789839507332, 'min_weight_fraction_leaf': 0.000561806644931952}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24455511870316463
Fold 2 IBS: 0.2267934884914344
Fold 3 IBS: 0.22466410581046875
Fold 4 IBS: 0.24050323119395856
Fold 5 IBS: 0.22915624250480857
[I 2024-04-16 21:42:05,477] Trial 68 finished with value: 0.23313443734076697 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7468960619194147, 'min_weight_fraction_leaf': 0.35364036783604025}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.2300787980001647
Fold 2 IBS: 0.19641627828017147
Fold 3 IBS: 0.19122863621161298
Fold 4 IBS: 0.21189349607756788
Fold 5 IBS: 0.21244170680598337
[I 2024-04-16 21:42:16,039] Trial 69 finished with value: 0.20841178307510008 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 493, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9133634021932744, 'min_weight_fraction_leaf': 0.03482005395654732}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23082745033605492
Fold 2 IBS: 0.21258342376009118
Fold 3 IBS: 0.20163835694721952
Fold 4 IBS: 0.2224423063055546
Fold 5 IBS: 0.21255388838390268
[I 2024-04-16 21:42:25,064] Trial 70 finished with value: 0.21600908514656458 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9214187460767265, 'min_weight_fraction_leaf': 0.25717771363652614}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23082723175570813
Fold 2 IBS: 0.20323092307506263
Fold 3 IBS: 0.19491966614269055
Fold 4 IBS: 0.2171154201350026
Fold 5 IBS: 0.216027037289287
[I 2024-04-16 21:42:37,022] Trial 71 finished with value: 0.2124240556795502 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 490, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7932890461516613, 'min_weight_fraction_leaf': 0.032131426880574826}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23017369217350117
Fold 2 IBS: 0.20120230419550925
Fold 3 IBS: 0.193722336472291
Fold 4 IBS: 0.21617692077677259
Fold 5 IBS: 0.21617316312987098
[I 2024-04-16 21:42:46,932] Trial 72 finished with value: 0.211489683349589 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 496, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8066423104143661, 'min_weight_fraction_leaf': 0.034326469001936366}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23070291890906766
Fold 2 IBS: 0.19797577360905477
Fold 3 IBS: 0.18899048202721042
Fold 4 IBS: 0.21031986359975194
Fold 5 IBS: 0.21398083574867297
[I 2024-04-16 21:42:56,794] Trial 73 finished with value: 0.20839397477875155 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9312721157462464, 'min_weight_fraction_leaf': 0.0012393034300419575}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.23615857055079026
Fold 2 IBS: 0.1966427796691383
Fold 3 IBS: 0.1929622046457027
Fold 4 IBS: 0.20870198205403534
Fold 5 IBS: 0.2125121533077471
[I 2024-04-16 21:43:07,005] Trial 74 finished with value: 0.20939553804548275 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 464, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9963604831342023, 'min_weight_fraction_leaf': 0.012116695798136328}. Best is trial 73 with value: 0.20839397477875155.

Fold 1 IBS: 0.23374241288259937
Fold 2 IBS: 0.19930439672774886
Fold 3 IBS: 0.18717738406829976
Fold 4 IBS: 0.20823176235963525
Fold 5 IBS: 0.21501371316102338
[I 2024-04-16 21:43:16,129] Trial 75 finished with value: 0.20869393383986132 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9528867121166885, 'min_weight_fraction_leaf': 0.0012590377645196535}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.24525891729558977
Fold 2 IBS: 0.21896003468791347
Fold 3 IBS: 0.21598508493564658
Fold 4 IBS: 0.24394612844374725
Fold 5 IBS: 0.2322350643210711
[I 2024-04-16 21:43:23,448] Trial 76 finished with value: 0.23127704593679366 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9658026435569093, 'min_weight_fraction_leaf': 0.015592248007567035}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.23502608441142722
Fold 2 IBS: 0.19922817017063826
Fold 3 IBS: 0.1913519268015393
Fold 4 IBS: 0.207834087421465
Fold 5 IBS: 0.2143743871087013
[I 2024-04-16 21:43:35,672] Trial 77 finished with value: 0.2095629311827542 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9853092886561814, 'min_weight_fraction_leaf': 0.010625988750975616}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.24649287843030504
Fold 2 IBS: 0.2314585308300189
Fold 3 IBS: 0.2289401139897681
Fold 4 IBS: 0.2417606515795492
Fold 5 IBS: 0.2302679373267155
[I 2024-04-16 21:43:41,311] Trial 78 finished with value: 0.23578402243127136 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9996115065732951, 'min_weight_fraction_leaf': 0.41218066030994116}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.2320831075429349
Fold 2 IBS: 0.19874748876281936
Fold 3 IBS: 0.1868862737714415
Fold 4 IBS: 0.2088372674979119
Fold 5 IBS: 0.2146701772034217
[I 2024-04-16 21:43:50,622] Trial 79 finished with value: 0.20824486295570588 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9333351337148593, 'min_weight_fraction_leaf': 0.013312290067980048}. Best is trial 79 with value: 0.20824486295570588.
Fold 1 IBS: 0.2321051762336623
Fold 2 IBS: 0.19872958357290424
Fold 3 IBS: 0.1868058011919495
Fold 4 IBS: 0.20883435526793945
Fold 5 IBS: 0.21456058420717486
[I 2024-04-16 21:44:00,052] Trial 80 finished with value: 0.2082071000947261 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 434, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9378042438987818, 'min_weight_fraction_leaf': 0.015273006586386988}. Best is trial 80 with value: 0.2082071000947261.
Fold 1 IBS: 0.23313533084879992
Fold 2 IBS: 0.1981286213929884
Fold 3 IBS: 0.18691652009336918
Fold 4 IBS: 0.20977045296104274
Fold 5 IBS: 0.21423701428211908
[I 2024-04-16 21:44:10,900] Trial 81 finished with value: 0.20843758791566386 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 439, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9417972207458584, 'min_weight_fraction_leaf': 0.04295474256066548}. Best is trial 80 with value: 0.2082071000947261.
Fold 1 IBS: 0.23424681521074975
Fold 2 IBS: 0.19613148875309624
Fold 3 IBS: 0.18531675217461782
Fold 4 IBS: 0.21089939380355308
Fold 5 IBS: 0.21326941327667795
[I 2024-04-16 21:44:19,307] Trial 82 finished with value: 0.20797277264373898 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9407754324156289, 'min_weight_fraction_leaf': 0.04206241234084829}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23409773201844755
Fold 2 IBS: 0.19653382628018295
Fold 3 IBS: 0.1848127640243094
Fold 4 IBS: 0.21249359291139658
Fold 5 IBS: 0.21212141767021883
[I 2024-04-16 21:44:27,577] Trial 83 finished with value: 0.20801186658091106 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 407, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9384130833098913, 'min_weight_fraction_leaf': 0.04519634108137036}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2329791447085086
Fold 2 IBS: 0.1967881823073177
Fold 3 IBS: 0.18728551841253535
Fold 4 IBS: 0.213032794231675
Fold 5 IBS: 0.21183681257533377
[I 2024-04-16 21:44:40,059] Trial 84 finished with value: 0.2083844904470741 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.925429012053495, 'min_weight_fraction_leaf': 0.05783142863073238}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2447356385509223
Fold 2 IBS: 0.21001665735971864
Fold 3 IBS: 0.20948126396091446
Fold 4 IBS: 0.24093216180850846
Fold 5 IBS: 0.2324937799728014
[I 2024-04-16 21:44:48,276] Trial 85 finished with value: 0.22753190033057305 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9332004479717521, 'min_weight_fraction_leaf': 0.10710747728623181}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23246895566730055
Fold 2 IBS: 0.197925177609746
Fold 3 IBS: 0.18771443031867188
Fold 4 IBS: 0.21213172875001646
Fold 5 IBS: 0.2119327578096531
[I 2024-04-16 21:44:57,875] Trial 86 finished with value: 0.20843461003107758 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 440, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8874595645983381, 'min_weight_fraction_leaf': 0.06167441402952489}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23362791486913068
Fold 2 IBS: 0.19689264641068396
Fold 3 IBS: 0.18782225531230023
Fold 4 IBS: 0.21277906488160134
Fold 5 IBS: 0.2142720511235225
[I 2024-04-16 21:45:11,955] Trial 87 finished with value: 0.20907878651944775 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9017353280575152, 'min_weight_fraction_leaf': 0.08057063446482637}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.24405634920973077
Fold 2 IBS: 0.20958957820309626
Fold 3 IBS: 0.2098195749072522
Fold 4 IBS: 0.2397871849283553
Fold 5 IBS: 0.23205952756968465
[I 2024-04-16 21:45:17,746] Trial 88 finished with value: 0.22706244296362382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8603916137186303, 'min_weight_fraction_leaf': 0.060569968472295434}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2405934580650391
Fold 2 IBS: 0.20440412320775256
Fold 3 IBS: 0.19898625051637614
Fold 4 IBS: 0.2317675135857698
Fold 5 IBS: 0.21634911771450452
[I 2024-04-16 21:45:24,216] Trial 89 finished with value: 0.2184200926178884 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8837193202561466, 'min_weight_fraction_leaf': 0.04645664782974562}. Best is trial 82 with value: 0.20797277264373898.

Fold 1 IBS: 0.24308229605873613
Fold 2 IBS: 0.20243085243083073
Fold 3 IBS: 0.20257300733372727
Fold 4 IBS: 0.2350012477048381
Fold 5 IBS: 0.22812847237666628
[I 2024-04-16 21:45:32,412] Trial 90 finished with value: 0.2222431751809597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9384169100812306, 'min_weight_fraction_leaf': 0.10055258156251395}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23494236000327381
Fold 2 IBS: 0.19851393414446025
Fold 3 IBS: 0.188316054669442
Fold 4 IBS: 0.20779679335240808
Fold 5 IBS: 0.21280969619087245
[I 2024-04-16 21:45:42,579] Trial 91 finished with value: 0.20847576767209133 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 442, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9619952733655167, 'min_weight_fraction_leaf': 0.040942271619228025}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23001265173746965
Fold 2 IBS: 0.1977150909325567
Fold 3 IBS: 0.19105114040885984
Fold 4 IBS: 0.21098586838673528
Fold 5 IBS: 0.2124489528575252
[I 2024-04-16 21:45:52,106] Trial 92 finished with value: 0.20844274086462936 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9098083130133213, 'min_weight_fraction_leaf': 0.055959244689231205}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23186934214354446
Fold 2 IBS: 0.19805339699670332
Fold 3 IBS: 0.1938995408571186
Fold 4 IBS: 0.21365134743523576
Fold 5 IBS: 0.213834084904634
[I 2024-04-16 21:46:01,908] Trial 93 finished with value: 0.21026154246744722 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 482, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9015170018833202, 'min_weight_fraction_leaf': 0.07022180710301966}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2285498908935621
Fold 2 IBS: 0.20195173694905538
Fold 3 IBS: 0.1953268721154233
Fold 4 IBS: 0.21295922746705104
Fold 5 IBS: 0.2141875287765351
[I 2024-04-16 21:46:11,940] Trial 94 finished with value: 0.2105950512403254 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8354647860336294, 'min_weight_fraction_leaf': 0.055962542201087324}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23095232917209657
Fold 2 IBS: 0.1958865206360449
Fold 3 IBS: 0.18697181187731182
Fold 4 IBS: 0.21657103840856698
Fold 5 IBS: 0.21293289499416962
[I 2024-04-16 21:46:25,986] Trial 95 finished with value: 0.20866291901763798 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 452, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9126090538791146, 'min_weight_fraction_leaf': 0.09308205917407598}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23141696019440808
Fold 2 IBS: 0.1972469732359395
Fold 3 IBS: 0.19181384992497885
Fold 4 IBS: 0.2152661468482183
Fold 5 IBS: 0.21279056642111796
[I 2024-04-16 21:46:37,565] Trial 96 finished with value: 0.20970689932493256 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8661215594792465, 'min_weight_fraction_leaf': 0.023013782620960307}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23281842728585872
Fold 2 IBS: 0.1985355360657985
Fold 3 IBS: 0.1884611926825503
Fold 4 IBS: 0.21580615607654127
Fold 5 IBS: 0.2101267637405006
[I 2024-04-16 21:46:47,666] Trial 97 finished with value: 0.20914961517024988 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 379, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8846229014197279, 'min_weight_fraction_leaf': 0.07875220306861608}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.24376771737441366
Fold 2 IBS: 0.2156464818855228
Fold 3 IBS: 0.21470997467703382
Fold 4 IBS: 0.24506757753025096
Fold 5 IBS: 0.23431638494569054
[I 2024-04-16 21:46:54,749] Trial 98 finished with value: 0.23070162728258237 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9345235447965159, 'min_weight_fraction_leaf': 0.06398587825076422}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23157995819346658
Fold 2 IBS: 0.19882579261217193
Fold 3 IBS: 0.19153184528522163
Fold 4 IBS: 0.21524003658426155
Fold 5 IBS: 0.21412013270935618
[I 2024-04-16 21:47:03,297] Trial 99 finished with value: 0.2102595530768956 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.84377839218482, 'min_weight_fraction_leaf': 0.11311649789821646}. Best is trial 82 with value: 0.20797277264373898.


* Best trial for IBS:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.20797277264373898], datetime_start=datetime.datetime(2024, 4, 16, 21, 44, 10, 909272), datetime_complete=datetime.datetime(2024, 4, 16, 21, 44, 19, 304601), params={'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9407754324156289, 'min_weight_fraction_leaf': 0.04206241234084829}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for IBS:
 0.20797277264373898

In [62]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [63]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.842
train_ibs:  0.208

#### Test

In [64]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [65]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=16, max_features=None, max_leaf_nodes=10,
                   max_samples=0.9186714469202719, min_samples_leaf=2,
                   min_samples_split=3,
                   min_weight_fraction_leaf=0.04956115599708024,
                   n_estimators=474, random_state=123, warm_start=True)

C-index score: 0.567

ExtraSurvivalTrees(max_depth=12, max_features=None, max_leaf_nodes=9,
                   max_samples=0.9407754324156289, min_samples_leaf=9,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.04206241234084829,
                   n_estimators=431, oob_score=True, random_state=123)

IBS: 0.235

In [66]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 21:47:08,809] A new study created in memory with name: no-name-ec4a3edf-ba81-48f5-9b10-098112766976

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:47:36,274] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:47:49,337] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:48:05,496] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:48:43,296] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:48:55,231] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:48:58,574] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:49:47,996] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:50:02,075] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:50:03,614] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 21:51:05,618] Trial 9 finished with value: 0.6832201973708838 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 21:52:34,956] Trial 10 finished with value: 0.6712397937360077 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:54:25,067] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.6713147410358565
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 21:55:51,808] Trial 12 finished with value: 0.6841431930275611 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:56:29,079] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:57:23,188] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:58:27,737] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 21:58:59,429] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:00:06,584] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:01:34,039] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:01:38,645] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:02:11,687] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 22:03:34,149] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 22:04:52,187] Trial 22 finished with value: 0.619312795708334 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:06:06,406] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:07:00,815] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:08:07,855] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:08:31,887] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:09:43,209] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:09:49,857] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:10:39,052] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:10:56,378] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5228136882129277
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 22:12:02,844] Trial 31 finished with value: 0.611786790783696 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:13:10,398] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:14:06,227] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:14:51,889] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6553784860557769
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 22:15:25,112] Trial 35 finished with value: 0.6685420013231411 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:15:53,048] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:16:14,986] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:16:35,082] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:16:57,456] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:17:21,056] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 22:19:03,768] Trial 41 finished with value: 0.6093445399392414 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:19:57,171] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:20:51,068] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:21:11,348] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:22:08,640] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.463519313304721
[I 2024-04-16 22:22:15,438] Trial 46 finished with value: 0.5692906361531651 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:22:36,651] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.03176403693294541, 'dropout_rate': 0.3498118985606263, 'n_estimators': 311, 'criterion': 'squared_error', 'ccp_alpha': 1.661787786465391, 'min_weight_fraction_leaf': 0.3313569504524189, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0658502841058407e-06, 'validation_fraction': 0.9349106995677626, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:22:37,161] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7795620265296891, 'learning_rate': 0.02031575704478572, 'dropout_rate': 0.1073207171648626, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9933742654917034, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:23:30,375] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9838861069093487, 'learning_rate': 0.015139882774656225, 'dropout_rate': 0.29582807120816745, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'auto', 'min_impurity_decrease': 1.0677294357907833e-07, 'validation_fraction': 0.28616351261163725, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:23:52,506] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.0013062644622639785, 'dropout_rate': 0.24125576461922837, 'n_estimators': 291, 'criterion': 'squared_error', 'ccp_alpha': 2.2224019868292646, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 4.1535796547081375e-07, 'validation_fraction': 0.4330566028790252, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5170212765957447
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 22:25:28,508] Trial 51 finished with value: 0.6138143425937758 and parameters: {'subsample': 0.8717443631112737, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.17858790490895218, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.4658711277635662, 'max_features': 'auto', 'min_impurity_decrease': 3.7719550144765347e-07, 'validation_fraction': 0.8890948102888172, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:26:58,398] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.8600452143616768, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.18426490654900665, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.3268256777978031, 'min_weight_fraction_leaf': 0.4698482977463435, 'max_features': 'auto', 'min_impurity_decrease': 1.8970689457597929e-07, 'validation_fraction': 0.7907152055757274, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:36:04,421] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9429985164193612, 'learning_rate': 0.01210259689637212, 'dropout_rate': 0.16709004215832246, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 1.355930920770751, 'min_weight_fraction_leaf': 0.44688401918267284, 'max_features': 'auto', 'min_impurity_decrease': 1.3370772545900196e-06, 'validation_fraction': 0.8482207213921362, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:36:19,793] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8147206508663337, 'learning_rate': 0.043146549395218045, 'dropout_rate': 0.8266353856620614, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 0.4402476369193899, 'min_weight_fraction_leaf': 0.403465815144378, 'max_features': 'auto', 'min_impurity_decrease': 0.009274431072766336, 'validation_fraction': 0.9013663610610466, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:42:49,653] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9029355236435976, 'learning_rate': 0.0069862044003569015, 'dropout_rate': 0.2714637824563154, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.20205377440058656, 'max_features': 'auto', 'min_impurity_decrease': 5.480356851781927e-07, 'validation_fraction': 0.9611026002356494, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:43:41,926] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.9900310764127254, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.13035104784910678, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 1.030013456919117, 'min_weight_fraction_leaf': 0.39532826999294124, 'max_features': 1, 'min_impurity_decrease': 1.6304555456718902e-07, 'validation_fraction': 0.6752987077694675, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 22:44:21,430] Trial 57 finished with value: 0.6916626606095264 and parameters: {'subsample': 0.7372794740983749, 'learning_rate': 0.07439616301612664, 'dropout_rate': 0.5891903890315894, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.0019551426651700787, 'min_weight_fraction_leaf': 0.3663477858006307, 'max_features': 'auto', 'min_impurity_decrease': 3.365152936571637e-07, 'validation_fraction': 0.9993820900191361, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:44:57,196] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.740417255833941, 'learning_rate': 0.08011510722272602, 'dropout_rate': 0.6195846181212514, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 5.929975119025805, 'min_weight_fraction_leaf': 0.311339954548064, 'max_features': 0.1, 'min_impurity_decrease': 2.1554900690561924e-06, 'validation_fraction': 0.9698819721425359, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:45:25,994] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.6313932742304071, 'learning_rate': 0.08675370704859038, 'dropout_rate': 0.5460527407257292, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8542659560131192, 'min_weight_fraction_leaf': 0.3698106479709166, 'max_features': 'log2', 'min_impurity_decrease': 7.380740444731775e-07, 'validation_fraction': 0.9977032043603392, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:45:47,984] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.6791716844984723, 'learning_rate': 0.08763134010262277, 'dropout_rate': 0.6506047265765441, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 1.3887836841387762, 'min_weight_fraction_leaf': 0.3542140149719947, 'max_features': 'auto', 'min_impurity_decrease': 5.3774251612153256e-05, 'validation_fraction': 0.9294449799181549, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 57 with value: 0.6916626606095264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 22:46:39,887] Trial 61 finished with value: 0.5127659574468085 and parameters: {'subsample': 0.5777054240152439, 'learning_rate': 0.0043890144447948955, 'dropout_rate': 0.2238557425834033, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22729228144381666, 'min_weight_fraction_leaf': 0.4847667891453218, 'max_features': 'auto', 'min_impurity_decrease': 3.121762528354459e-07, 'validation_fraction': 0.8794060911772942, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6845493562231759
[I 2024-04-16 23:04:30,134] Trial 62 finished with value: 0.6671051444586171 and parameters: {'subsample': 0.8280927356694872, 'learning_rate': 0.012941968520404364, 'dropout_rate': 0.16851713525090162, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.41782991757217913, 'max_features': 'auto', 'min_impurity_decrease': 1.6297128321880156e-07, 'validation_fraction': 0.8216047754912434, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:05:10,199] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.8179794453140475, 'learning_rate': 0.07155184022383326, 'dropout_rate': 0.5059523129078595, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.733686110808502, 'min_weight_fraction_leaf': 0.4266346533719304, 'max_features': 'auto', 'min_impurity_decrease': 1.456573145641989e-07, 'validation_fraction': 0.8226670106263154, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:05:48,695] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7257892105627847, 'learning_rate': 0.02248195835921648, 'dropout_rate': 0.449913369550909, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4337068311554637, 'min_weight_fraction_leaf': 0.40949100256777493, 'max_features': 'auto', 'min_impurity_decrease': 2.3829259538917073e-07, 'validation_fraction': 0.9264223190540628, 'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:06:14,641] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.789360221844535, 'learning_rate': 0.011722172098720455, 'dropout_rate': 0.5832565770529121, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.9257201840062063, 'min_weight_fraction_leaf': 0.3826221056999394, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.7684528850780882, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:06:56,292] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9423465114553011, 'learning_rate': 0.026890895479547216, 'dropout_rate': 0.27005657366012886, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.3406131595034317, 'min_weight_fraction_leaf': 0.273466592831212, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.8663542646961032, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:07:44,080] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8509816424016059, 'learning_rate': 0.018962435344391418, 'dropout_rate': 0.12106779245577974, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 1.1793178188167732, 'min_weight_fraction_leaf': 0.32971711200084314, 'max_features': None, 'min_impurity_decrease': 1.1734866199377895e-06, 'validation_fraction': 0.9601204189934851, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:08:41,576] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8877022924129648, 'learning_rate': 0.035301196481135985, 'dropout_rate': 0.21544296697082643, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.437656675029897, 'max_features': 'auto', 'min_impurity_decrease': 1.3568513606672929e-07, 'validation_fraction': 0.7065228184822674, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:09:24,784] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5085409566716843, 'learning_rate': 0.07146375849643816, 'dropout_rate': 0.15565815102593683, 'n_estimators': 381, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7384677513512519, 'min_weight_fraction_leaf': 0.16528005308216742, 'max_features': 'auto', 'min_impurity_decrease': 3.4966343506407575e-07, 'validation_fraction': 0.5407783460399488, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.4765957446808511
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:10:00,484] Trial 70 finished with value: 0.6699861139528519 and parameters: {'subsample': 0.8427091117621403, 'learning_rate': 0.014080040753655973, 'dropout_rate': 0.7041903400301625, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.010117153579154908, 'min_weight_fraction_leaf': 0.23888457853481262, 'max_features': 'auto', 'min_impurity_decrease': 1.0665064545447388e-07, 'validation_fraction': 0.8311901171171172, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.49361702127659574
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:10:34,149] Trial 71 finished with value: 0.6705113277133752 and parameters: {'subsample': 0.837820165625454, 'learning_rate': 0.009162835586660466, 'dropout_rate': 0.7157677225693142, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.2238024810121353, 'max_features': 'auto', 'min_impurity_decrease': 1.6903767334797878e-07, 'validation_fraction': 0.9136175276841315, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.49361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:11:06,739] Trial 72 finished with value: 0.6704965901886897 and parameters: {'subsample': 0.8320550512705249, 'learning_rate': 0.015250213313703867, 'dropout_rate': 0.7084704325292757, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.0047914300176533624, 'min_weight_fraction_leaf': 0.22496831177560328, 'max_features': 'auto', 'min_impurity_decrease': 1.043158296301398e-07, 'validation_fraction': 0.8315500117499774, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:11:41,584] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.7522550686139352, 'learning_rate': 0.01549395863927688, 'dropout_rate': 0.7193234731509487, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.6105254483380164, 'min_weight_fraction_leaf': 0.23084281559796668, 'max_features': 'auto', 'min_impurity_decrease': 1.1425726740224786e-07, 'validation_fraction': 0.9089610037492091, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:12:09,439] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6901097639595143, 'learning_rate': 0.009706466282346518, 'dropout_rate': 0.8289978122630015, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.32830586032225173, 'min_weight_fraction_leaf': 0.19648377877761647, 'max_features': 'auto', 'min_impurity_decrease': 1.0237452134280835e-07, 'validation_fraction': 0.6403761250010531, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:12:38,921] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9243190445711414, 'learning_rate': 0.0038617948288836557, 'dropout_rate': 0.7224884343850821, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.5692251904189567, 'min_weight_fraction_leaf': 0.2446666417975855, 'max_features': None, 'min_impurity_decrease': 3.073066227115244e-07, 'validation_fraction': 0.9980785900823812, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:13:08,720] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.7974068669958387, 'learning_rate': 0.062047343259982284, 'dropout_rate': 0.6720237281802866, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.8485875561540186, 'min_weight_fraction_leaf': 0.2177983483250821, 'max_features': 'auto', 'min_impurity_decrease': 2.1896409704067416e-07, 'validation_fraction': 0.8579309717242278, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:13:32,805] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8422997308078775, 'learning_rate': 0.017766566895921525, 'dropout_rate': 0.6384272449487696, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5531698468613242, 'min_weight_fraction_leaf': 0.17978584394296698, 'max_features': 1, 'min_impurity_decrease': 1.6942780866930195e-07, 'validation_fraction': 0.9713474660357939, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 8}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:14:11,816] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.6517834016017484, 'learning_rate': 0.002407235870294221, 'dropout_rate': 0.5816105806888315, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.1587287440372196, 'min_weight_fraction_leaf': 0.2981694522309396, 'max_features': 'auto', 'min_impurity_decrease': 5.608281082695417e-07, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:14:21,199] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7102653479652419, 'learning_rate': 0.00926581670466016, 'dropout_rate': 0.8340744983902122, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.244213895373325, 'min_weight_fraction_leaf': 0.26516890393090514, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9441925364897708, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:14:41,652] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.5834757737011464, 'learning_rate': 0.026745879030501164, 'dropout_rate': 0.702176827465796, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.22999987323735258, 'max_features': 'log2', 'min_impurity_decrease': 2.3792015344208368e-07, 'validation_fraction': 0.3551379508028982, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.7131474103585658
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.4808510638297872
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6587982832618026
[I 2024-04-16 23:15:08,929] Trial 81 finished with value: 0.6730234656174222 and parameters: {'subsample': 0.8325293669317142, 'learning_rate': 0.011806037995297227, 'dropout_rate': 0.7551006664918564, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.04034911069069444, 'min_weight_fraction_leaf': 0.25447319867295237, 'max_features': 'auto', 'min_impurity_decrease': 1.5172002134087317e-07, 'validation_fraction': 0.9114851981025106, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:15:38,727] Trial 82 finished with value: 0.698879373414812 and parameters: {'subsample': 0.7574564379023108, 'learning_rate': 0.014548313409933181, 'dropout_rate': 0.7388190394293348, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.017672701019498645, 'min_weight_fraction_leaf': 0.18953464920787744, 'max_features': 'auto', 'min_impurity_decrease': 1.4736811730220929e-07, 'validation_fraction': 0.9118325083710781, 'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:16:05,712] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7686876073989469, 'learning_rate': 0.013838758072384357, 'dropout_rate': 0.7911803425652506, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.6372477576434026, 'min_weight_fraction_leaf': 0.19053597558098956, 'max_features': 'auto', 'min_impurity_decrease': 1.044261661000394e-07, 'validation_fraction': 0.9081833240552606, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:16:34,754] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8417391470557727, 'learning_rate': 0.02022963558253854, 'dropout_rate': 0.7549313249685682, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.21448418173643904, 'min_weight_fraction_leaf': 0.14529026645886883, 'max_features': 'auto', 'min_impurity_decrease': 1.644017634935428e-07, 'validation_fraction': 0.7522154789012329, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.

Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:16:58,270] Trial 85 finished with value: 0.6764106721092568 and parameters: {'subsample': 0.7354973785260009, 'learning_rate': 0.016077297348185124, 'dropout_rate': 0.7998038530392593, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.011704477637461151, 'min_weight_fraction_leaf': 0.25414654453375674, 'max_features': 'auto', 'min_impurity_decrease': 4.3624226956840624e-07, 'validation_fraction': 0.8473925109174445, 'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:17:02,204] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.7408782122857952, 'learning_rate': 0.008176338925322723, 'dropout_rate': 0.8784853674438767, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.8792495785897113, 'min_weight_fraction_leaf': 0.21067569979765627, 'max_features': 'auto', 'min_impurity_decrease': 8.838933091327168e-07, 'validation_fraction': 0.976898355040724, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:17:29,044] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7919841956110775, 'learning_rate': 0.016800285566641673, 'dropout_rate': 0.8053771471721777, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 6.848676757092456, 'min_weight_fraction_leaf': 0.25627475842564307, 'max_features': 'auto', 'min_impurity_decrease': 4.4582432432077124e-07, 'validation_fraction': 0.567887901649637, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:17:48,604] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.7637017957134666, 'learning_rate': 0.0046996483876466065, 'dropout_rate': 0.8619792930233291, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 0.4746488265956075, 'min_weight_fraction_leaf': 0.28109817636901246, 'max_features': 'auto', 'min_impurity_decrease': 6.846032299820816e-07, 'validation_fraction': 0.8020692816016028, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:18:24,181] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.9623924871310936, 'learning_rate': 0.0015527825801297172, 'dropout_rate': 0.7519223066786315, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 1.2232438573199316, 'min_weight_fraction_leaf': 0.15271636525917553, 'max_features': 'auto', 'min_impurity_decrease': 3.1868906706070215e-07, 'validation_fraction': 0.9409810619692617, 'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:18:32,630] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.8745132816034922, 'learning_rate': 0.024313584301659426, 'dropout_rate': 0.8788019303444206, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.2487952428061195, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5174531590387773e-06, 'validation_fraction': 0.8951588805626794, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.7131474103585658
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.4851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6630901287553648
[I 2024-04-16 23:18:59,501] Trial 91 finished with value: 0.6731825109490227 and parameters: {'subsample': 0.8354990297039531, 'learning_rate': 0.0138293831902292, 'dropout_rate': 0.7281039467319077, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.03758540364708225, 'min_weight_fraction_leaf': 0.2530637808301116, 'max_features': 'auto', 'min_impurity_decrease': 1.5118979817918927e-07, 'validation_fraction': 0.8408512373546821, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:19:23,505] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8085365523165823, 'learning_rate': 0.010756482814232722, 'dropout_rate': 0.7444483338307321, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.49447471804458437, 'min_weight_fraction_leaf': 0.25064996426719116, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.8390132957951739, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 23:19:43,622] Trial 93 finished with value: 0.6881273036948009 and parameters: {'subsample': 0.7453329553993305, 'learning_rate': 0.021174166394019457, 'dropout_rate': 0.7793451155626762, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04746460613674034, 'min_weight_fraction_leaf': 0.2093766049536608, 'max_features': 'auto', 'min_impurity_decrease': 4.3263336279630515e-07, 'validation_fraction': 0.7761975833676429, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:20:05,310] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.7279707912652753, 'learning_rate': 0.021608355611700266, 'dropout_rate': 0.7346078225406316, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.7086041731588438, 'min_weight_fraction_leaf': 0.20875637228664023, 'max_features': 'auto', 'min_impurity_decrease': 4.696900773859783e-07, 'validation_fraction': 0.7825380103331964, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:20:18,553] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.41059605701997526, 'learning_rate': 0.008265328833970157, 'dropout_rate': 0.7833536187763309, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.9761780021039411, 'min_weight_fraction_leaf': 0.26909043908757685, 'max_features': 'auto', 'min_impurity_decrease': 2.7953622898255886e-07, 'validation_fraction': 0.8675625663624191, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:20:48,613] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.7807484083766505, 'learning_rate': 0.019136234077479226, 'dropout_rate': 0.6797290416912756, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.2137190515453802, 'min_weight_fraction_leaf': 0.1836345173241593, 'max_features': 'auto', 'min_impurity_decrease': 1.5053955435348267e-07, 'validation_fraction': 0.9141346557445693, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 82 with value: 0.698879373414812.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:21:08,151] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.6692392383366766, 'learning_rate': 0.005703846641879013, 'dropout_rate': 0.778639362865728, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.4660418580309801, 'min_weight_fraction_leaf': 0.19771711093861588, 'max_features': 'auto', 'min_impurity_decrease': 0.0032862083702029487, 'validation_fraction': 0.9476450583671194, 'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 23:21:23,747] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.7074353323873224, 'learning_rate': 0.012490550235605942, 'dropout_rate': 0.8460634884916687, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.2365858465049468, 'max_features': 'auto', 'min_impurity_decrease': 9.113797265483529e-07, 'validation_fraction': 0.9834615394391507, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.7604562737642585

[I 2024-04-16 23:21:45,520] A new study created in memory with name: no-name-dc5e8e6f-4440-4a46-9bdc-83a2e172984b

Fold 5 C-index: 0.6802575107296137
[I 2024-04-16 23:21:45,499] Trial 99 finished with value: 0.6997238381485732 and parameters: {'subsample': 0.8597838031871279, 'learning_rate': 0.010888929954369636, 'dropout_rate': 0.8022681311855436, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.004507507039685693, 'min_weight_fraction_leaf': 0.1685851039915477, 'max_features': 'auto', 'min_impurity_decrease': 4.0700060224631717e-07, 'validation_fraction': 0.8827408742810589, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 99 with value: 0.6997238381485732.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.6997238381485732], datetime_start=datetime.datetime(2024, 4, 16, 23, 21, 23, 751063), datetime_complete=datetime.datetime(2024, 4, 16, 23, 21, 45, 498786), params={'subsample': 0.8597838031871279, 'learning_rate': 0.010888929954369636, 'dropout_rate': 0.8022681311855436, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.004507507039685693, 'min_weight_fraction_leaf': 0.1685851039915477, 'max_features': 'auto', 'min_impurity_decrease': 4.0700060224631717e-07, 'validation_fraction': 0.8827408742810589, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 12}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for C-index:
 0.6997238381485732

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:00,914] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:08,292] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:15,824] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:22:33,200] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:39,190] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:40,789] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:48,845] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:51,057] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:22:51,384] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24611646824848502
Fold 2 IBS: 0.23045314613284576
Fold 3 IBS: 0.22864908069318055
Fold 4 IBS: 0.24088343083773206
Fold 5 IBS: 0.2286067880417571
[I 2024-04-16 23:23:20,153] Trial 9 finished with value: 0.23494178279080008 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23166000859087926
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164904353219824
Fold 5 IBS: 0.2291762528827903
[I 2024-04-16 23:24:00,197] Trial 10 finished with value: 0.23563423441371983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:24:48,917] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2471389609167843
Fold 2 IBS: 0.23185194695073053
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.2418709994354467
Fold 5 IBS: 0.22931414809995274
[I 2024-04-16 23:25:32,809] Trial 12 finished with value: 0.23582622492055835 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:25:48,878] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:26:27,334] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:26:47,663] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:26:58,326] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:27:24,795] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:27:38,433] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:27:41,702] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:28:10,490] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2470758782497334
Fold 2 IBS: 0.2319847418263816
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.24189505261981767
Fold 5 IBS: 0.22923216203360366
[I 2024-04-16 23:28:40,906] Trial 21 finished with value: 0.23582190451342355 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2464930115110139
Fold 2 IBS: 0.23084795543166578

Fold 3 IBS: 0.22877023826826642
Fold 4 IBS: 0.24122503350572105
Fold 5 IBS: 0.22878079391093029
[I 2024-04-16 23:29:17,330] Trial 22 finished with value: 0.2352234065255195 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-16 23:29:47,913] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:30:08,882] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:30:27,685] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:30:43,916] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:30:45,849] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:30:50,805] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:31:10,956] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:31:41,294] Trial 30 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24669611373458267
Fold 2 IBS: 0.23161054906241668
Fold 3 IBS: 0.22885749682655868
Fold 4 IBS: 0.2415375526987621
Fold 5 IBS: 0.22900046780800146
[I 2024-04-16 23:32:14,265] Trial 31 finished with value: 0.2355404360260643 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24559061103708343
Fold 2 IBS: 0.23024033663487284
Fold 3 IBS: 0.2293974925753989
Fold 4 IBS: 0.24024323071520023
Fold 5 IBS: 0.2284489804567101
[I 2024-04-16 23:32:46,548] Trial 32 finished with value: 0.2347841302838531 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:33:06,929] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:33:29,126] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:33:36,514] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:33:59,386] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:34:02,299] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:34:12,916] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:34:27,411] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:34:47,742] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24564975054404245
Fold 2 IBS: 0.22980985720122352
Fold 3 IBS: 0.22862944699148766
Fold 4 IBS: 0.24019850838895782
Fold 5 IBS: 0.22847935077439893
[I 2024-04-16 23:35:22,874] Trial 41 finished with value: 0.23455338278002208 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24577893568533524
Fold 2 IBS: 0.2300168763545233
Fold 3 IBS: 0.2283274561934457
Fold 4 IBS: 0.24018944863835465
Fold 5 IBS: 0.2284694599346158
[I 2024-04-16 23:35:59,366] Trial 42 finished with value: 0.23455643536125495 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:36:43,205] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:37:18,953] Trial 44 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:37:29,139] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24711436282531865
Fold 2 IBS: 0.23189796599325815
Fold 3 IBS: 0.2289389886288917
Fold 4 IBS: 0.2418829980148295
Fold 5 IBS: 0.22932341012264723
[I 2024-04-16 23:37:56,037] Trial 46 finished with value: 0.23583154511698906 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:38:12,149] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:38:12,334] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:38:20,422] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:38:40,407] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.2462802649053173
Fold 2 IBS: 0.23090518019736747
Fold 3 IBS: 0.22910230952131883
Fold 4 IBS: 0.24089201571280294
Fold 5 IBS: 0.22880129355386447
[I 2024-04-16 23:39:11,562] Trial 51 finished with value: 0.23519621277813424 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24650272034345022
Fold 2 IBS: 0.23102415353022362
Fold 3 IBS: 0.22863881664006155
Fold 4 IBS: 0.2411028633234996
Fold 5 IBS: 0.22892412673294307
[I 2024-04-16 23:39:45,962] Trial 52 finished with value: 0.2352385361140356 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:40:16,307] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:40:47,390] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:41:12,145] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:41:31,898] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:41:53,024] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:17,396] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:35,192] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:42:50,217] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.246792274967983
Fold 2 IBS: 0.23161964216377484
Fold 3 IBS: 0.22888176928337703
Fold 4 IBS: 0.24155890986096298
Fold 5 IBS: 0.22907544730443408
[I 2024-04-16 23:43:24,401] Trial 61 finished with value: 0.2355856087161064 and parameters: {'subsample': 0.9918985385533109, 'learning_rate': 0.005743016439014149, 'dropout_rate': 0.28747233681343587, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.16038675829082302, 'max_features': 'auto', 'min_impurity_decrease': 2.9513412376244623e-06, 'validation_fraction': 0.9751691260171886, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24556197891151196
Fold 2 IBS: 0.22972947118075088
Fold 3 IBS: 0.22847603444167852
Fold 4 IBS: 0.23983661807749995
Fold 5 IBS: 0.22821417993674387
[I 2024-04-16 23:43:58,166] Trial 62 finished with value: 0.23436365650963703 and parameters: {'subsample': 0.9574333176186867, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.18564670695369828, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 7.301362864132341e-06, 'validation_fraction': 0.9275594296798731, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:44:08,450] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9611556459137681, 'learning_rate': 0.009885633504393494, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.40714661625851756, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:44:34,064] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9996724029846231, 'learning_rate': 0.02055321577299183, 'dropout_rate': 0.19552211208698841, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.21641604442433082, 'max_features': 'log2', 'min_impurity_decrease': 7.250192360253865e-06, 'validation_fraction': 0.9272295835693174, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:45:07,571] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.919652344200739, 'learning_rate': 0.014473083324943868, 'dropout_rate': 0.16799591889422819, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.351957844105687, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658996

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:45:37,264] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8489175059797514, 'learning_rate': 0.008448226967076113, 'dropout_rate': 0.12725750793823018, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.893877768639663, 'min_weight_fraction_leaf': 0.2702972473075093, 'max_features': 'auto', 'min_impurity_decrease': 7.586810829424823e-05, 'validation_fraction': 0.8971088342813041, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:45:58,562] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9594402941587806, 'learning_rate': 0.0039206688180527, 'dropout_rate': 0.25338876644885766, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1787054950134963, 'min_weight_fraction_leaf': 0.29081789854917856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.005146223539456e-06, 'validation_fraction': 0.9662549030476638, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:46:28,605] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.885928079608526, 'learning_rate': 0.01958784726286755, 'dropout_rate': 0.3188313005563145, 'n_estimators': 463, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.24383256255051056, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.99982951588149, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724158711521824
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:46:58,074] Trial 69 finished with value: 0.23592674084605642 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.011561561592981577, 'dropout_rate': 0.2251092355441408, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.30419922755720963, 'min_weight_fraction_leaf': 0.1929901790072115, 'max_features': 'auto', 'min_impurity_decrease': 1.6729804035130242e-06, 'validation_fraction': 0.8450602738806452, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24516581707410637
Fold 2 IBS: 0.229362987548221
Fold 3 IBS: 0.2285150856495683
Fold 4 IBS: 0.2397404288488306
Fold 5 IBS: 0.22776390319047718
[I 2024-04-16 23:47:22,858] Trial 70 finished with value: 0.23410964446224067 and parameters: {'subsample': 0.7327319228005876, 'learning_rate': 0.016866948400001296, 'dropout_rate': 0.17898373444054652, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.01005746855001105, 'min_weight_fraction_leaf': 0.3640638074298326, 'max_features': None, 'min_impurity_decrease': 9.787021311876353e-06, 'validation_fraction': 0.7926074734474466, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.2454369019344366
Fold 2 IBS: 0.23016772493855195
Fold 3 IBS: 0.22866734075144848
Fold 4 IBS: 0.2406555824750769
Fold 5 IBS: 0.22795295445317568
[I 2024-04-16 23:47:43,746] Trial 71 finished with value: 0.2345761009105379 and parameters: {'subsample': 0.6580825781997457, 'learning_rate': 0.016629440896307336, 'dropout_rate': 0.17328978363215145, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.4078164122376511, 'max_features': None, 'min_impurity_decrease': 3.981143358338061e-06, 'validation_fraction': 0.9287047300321795, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.2455804604771737
Fold 2 IBS: 0.23015122616770395
Fold 3 IBS: 0.22864882824644148
Fold 4 IBS: 0.2406032444136894
Fold 5 IBS: 0.22814137040371196
[I 2024-04-16 23:48:03,292] Trial 72 finished with value: 0.2346250259417441 and parameters: {'subsample': 0.6433252951647072, 'learning_rate': 0.015406216424115876, 'dropout_rate': 0.174165060267479, 'n_estimators': 372, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.4068999670923105, 'max_features': None, 'min_impurity_decrease': 9.143853678722166e-06, 'validation_fraction': 0.8050869160635631, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:48:24,646] Trial 73 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6415805639130162, 'learning_rate': 0.016957190070749008, 'dropout_rate': 0.1022557442615895, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.7340527434897883, 'min_weight_fraction_leaf': 0.41441154927232665, 'max_features': None, 'min_impurity_decrease': 2.8366918098535655e-05, 'validation_fraction': 0.8120762455660575, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:48:47,130] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5890037439982243, 'learning_rate': 0.02388572819447024, 'dropout_rate': 0.14309816759091956, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.33550183960235097, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': None, 'min_impurity_decrease': 1.1962100920927531e-05, 'validation_fraction': 0.6568048355299513, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:49:05,881] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6875143177223235, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.18219557324018512, 'n_estimators': 365, 'criterion': 'squared_error', 'ccp_alpha': 0.6626240923578504, 'min_weight_fraction_leaf': 0.3667876525646178, 'max_features': None, 'min_impurity_decrease': 8.996538110684365e-06, 'validation_fraction': 0.7854387247082943, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:49:27,235] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6310903661182281, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.16070017323462005, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.43428922098282363, 'max_features': None, 'min_impurity_decrease': 4.880048865700701e-06, 'validation_fraction': 0.7567620429516432, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:49:40,186] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7234820637720293, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.19884799526452568, 'n_estimators': 302, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.4027406894595495, 'max_features': None, 'min_impurity_decrease': 5.35591590419612e-07, 'validation_fraction': 0.8758106078120852, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:49:56,603] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6708593402641205, 'learning_rate': 0.02742354559286264, 'dropout_rate': 0.12642193192647372, 'n_estimators': 329, 'criterion': 'squared_error', 'ccp_alpha': 0.2456295975030462, 'min_weight_fraction_leaf': 0.3629864105918121, 'max_features': None, 'min_impurity_decrease': 0.00015140034318578482, 'validation_fraction': 0.6173345703129903, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.241851651618776
Fold 2 IBS: 0.225082141185961
Fold 3 IBS: 0.22886330137755048
Fold 4 IBS: 0.23945272971544493
Fold 5 IBS: 0.225546678965891
[I 2024-04-16 23:50:20,585] Trial 79 finished with value: 0.2321593005727247 and parameters: {'subsample': 0.6068487747881667, 'learning_rate': 0.08690058608305122, 'dropout_rate': 0.2202274723306249, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 0.0067848986270052205, 'min_weight_fraction_leaf': 0.442958513823715, 'max_features': None, 'min_impurity_decrease': 3.159003046563375e-05, 'validation_fraction': 0.6916250922837899, 'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.2321593005727247.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:50:43,436] Trial 80 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7431452433208791, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.22085807342340602, 'n_estimators': 416, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0208718228969498, 'min_weight_fraction_leaf': 0.4578321580005691, 'max_features': None, 'min_impurity_decrease': 6.219311571999601e-05, 'validation_fraction': 0.8063818584332632, 'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 1}. Best is trial 79 with value: 0.2321593005727247.
Fold 1 IBS: 0.24040275609642484
Fold 2 IBS: 0.22344468173586884
Fold 3 IBS: 0.22846224162930656
Fold 4 IBS: 0.23645999283112776
Fold 5 IBS: 0.22436389610083335
[I 2024-04-16 23:51:07,625] Trial 81 finished with value: 0.23062671367871226 and parameters: {'subsample': 0.6143582554906275, 'learning_rate': 0.09196546766753708, 'dropout_rate': 0.17154122956253648, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.025343486133480444, 'min_weight_fraction_leaf': 0.422923580742715, 'max_features': None, 'min_impurity_decrease': 3.0516618185477245e-05, 'validation_fraction': 0.6839523176227551, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:51:26,093] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6156671358096751, 'learning_rate': 0.09024426530842436, 'dropout_rate': 0.17324784818426983, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.5340758841421452, 'min_weight_fraction_leaf': 0.44660441203015316, 'max_features': None, 'min_impurity_decrease': 3.596173256287884e-05, 'validation_fraction': 0.6862764853454645, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:51:52,287] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.59035693752921, 'learning_rate': 0.08769222490327029, 'dropout_rate': 0.13695127070120913, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.29851318725213727, 'min_weight_fraction_leaf': 0.4224884983147852, 'max_features': None, 'min_impurity_decrease': 1.7043338510624665e-05, 'validation_fraction': 0.708718433392457, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:52:16,838] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5692772731117001, 'learning_rate': 0.09337007500374273, 'dropout_rate': 0.19406549234317277, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 0.7908292561402825, 'min_weight_fraction_leaf': 0.3834871581332913, 'max_features': None, 'min_impurity_decrease': 2.8122570662289344e-05, 'validation_fraction': 0.9095186934735143, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24230603015357494
Fold 2 IBS: 0.22627075094258225
Fold 3 IBS: 0.22794332453533264
Fold 4 IBS: 0.2379855545919495
Fold 5 IBS: 0.22601443786759767
[I 2024-04-16 23:52:20,226] Trial 85 finished with value: 0.23210401961820742 and parameters: {'subsample': 0.6445419753261435, 'learning_rate': 0.06087928731142127, 'dropout_rate': 0.24518342938103005, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.011216734292662366, 'min_weight_fraction_leaf': 0.4043905469812696, 'max_features': None, 'min_impurity_decrease': 1.493590751470447e-05, 'validation_fraction': 0.5742595190050698, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:52:23,888] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5345448615448432, 'learning_rate': 0.06299476346040861, 'dropout_rate': 0.16060697827295928, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.62448544277789, 'min_weight_fraction_leaf': 0.4834818041059262, 'max_features': None, 'min_impurity_decrease': 1.4511890623038534e-05, 'validation_fraction': 0.531307128627143, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24187291146832404
Fold 2 IBS: 0.2251821854583426
Fold 3 IBS: 0.2280766922101586
Fold 4 IBS: 0.2375222631191458
Fold 5 IBS: 0.22529950757040032
[I 2024-04-16 23:52:42,431] Trial 87 finished with value: 0.2315907119652743 and parameters: {'subsample': 0.6482886513725954, 'learning_rate': 0.08056151243791008, 'dropout_rate': 0.2600398597942537, 'n_estimators': 374, 'criterion': 'squared_error', 'ccp_alpha': 0.01745937818789605, 'min_weight_fraction_leaf': 0.40356411913419793, 'max_features': None, 'min_impurity_decrease': 9.949241277389102e-06, 'validation_fraction': 0.5582433992805256, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:52:44,055] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6879348852579991, 'learning_rate': 0.08209035744510738, 'dropout_rate': 0.24522201083374043, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.2983993026610602, 'min_weight_fraction_leaf': 0.3774672254272644, 'max_features': None, 'min_impurity_decrease': 5.4011226362110275e-06, 'validation_fraction': 0.568843188657281, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:52:47,573] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6555693108457097, 'learning_rate': 0.08348043724232247, 'dropout_rate': 0.1018982518393906, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.3922659564335438, 'max_features': None, 'min_impurity_decrease': 1.84353439530822e-05, 'validation_fraction': 0.4550485507485021, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:52:53,432] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6142534760575815, 'learning_rate': 0.07977183656340979, 'dropout_rate': 0.21675268812215465, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.43931856433894717, 'max_features': None, 'min_impurity_decrease': 4.509029295159726e-05, 'validation_fraction': 0.6255054030515286, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 8}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24033659095145252
Fold 2 IBS: 0.22271607873274998
Fold 3 IBS: 0.22784490354997913
Fold 4 IBS: 0.23529399067272844
Fold 5 IBS: 0.22413051884016097
[I 2024-04-16 23:53:15,254] Trial 91 finished with value: 0.2300644165494142 and parameters: {'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24714728680988468
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22893463205005193
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22935673483794422
[I 2024-04-16 23:53:33,842] Trial 92 finished with value: 0.235890661939015 and parameters: {'subsample': 0.5057005214243391, 'learning_rate': 0.09883062819528839, 'dropout_rate': 0.2685922627272655, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.19747740396734947, 'min_weight_fraction_leaf': 0.4679716753672616, 'max_features': None, 'min_impurity_decrease': 1.0671241077127033e-05, 'validation_fraction': 0.5950373519486988, 'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:53:56,692] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5538299448336005, 'learning_rate': 0.0868661642219975, 'dropout_rate': 0.20334468934521452, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.5267007889739713, 'min_weight_fraction_leaf': 0.42336750014808644, 'max_features': None, 'min_impurity_decrease': 8.867094040313709e-05, 'validation_fraction': 0.520690018337254, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:54:01,236] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5702665640439277, 'learning_rate': 0.09449632562825357, 'dropout_rate': 0.13870793304287105, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.8492587817200913, 'min_weight_fraction_leaf': 0.348550363613902, 'max_features': None, 'min_impurity_decrease': 6.826272330503328e-06, 'validation_fraction': 0.5659130589721448, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:54:19,015] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7076939032161012, 'learning_rate': 0.09136733918164754, 'dropout_rate': 0.18672112900745633, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.561945255260577, 'min_weight_fraction_leaf': 0.40234945062950195, 'max_features': None, 'min_impurity_decrease': 2.5588389290979514e-05, 'validation_fraction': 0.4537896994588092, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:54:33,907] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6655863757457166, 'learning_rate': 0.08941626520289533, 'dropout_rate': 0.2411336203156454, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.23565160101206817, 'min_weight_fraction_leaf': 0.42995214161407835, 'max_features': None, 'min_impurity_decrease': 3.937366373268103e-06, 'validation_fraction': 0.6733503587022674, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 16}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 23:54:34,284] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5830397464244746, 'learning_rate': 0.09649030637314325, 'dropout_rate': 0.1548001251941624, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 1.0632556006826448, 'min_weight_fraction_leaf': 0.4466142202394081, 'max_features': 1, 'min_impurity_decrease': 9.319522810040033e-06, 'validation_fraction': 0.49048790135092346, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:54:53,394] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6220799571230118, 'learning_rate': 0.08529012031921517, 'dropout_rate': 0.2588962329024949, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3323104826759427, 'min_weight_fraction_leaf': 0.4570033067989539, 'max_features': None, 'min_impurity_decrease': 1.5778942534009964e-05, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 3}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 23:54:59,506] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.07813501740629669, 'dropout_rate': 0.30318261654818046, 'n_estimators': 242, 'criterion': 'squared_error', 'ccp_alpha': 1.7079733343503498, 'min_weight_fraction_leaf': 0.32269779176244495, 'max_features': 0.1, 'min_impurity_decrease': 1.276230329676773e-06, 'validation_fraction': 0.36954438153697, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.2300644165494142], datetime_start=datetime.datetime(2024, 4, 16, 23, 52, 53, 434375), datetime_complete=datetime.datetime(2024, 4, 16, 23, 53, 15, 253503), params={'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.2300644165494142

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.7
train_ibs:  0.23

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004507507039685693,
                                 criterion='squared_error',
                                 dropout_rate=0.8022681311855436,
                                 learning_rate=0.010888929954369636,
                                 max_depth=12, max_features='auto',
                                 max_leaf_nodes=3,
                                 min_impurity_decrease=4.0700060224631717e-07,
                                 min_samples_leaf=10, min_samples_split=19,
                                 min_weight_fraction_leaf=0.1685851039915477,
                                 n_estimators=443, random_state=123,
                                 subsample=0.8597838031871279,
                                 validation_fraction=0.8827408742810589)

C-index score: 0.516

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03787089343697578,
                                 criterion='squared_error',
                                 dropout_rate=0.18479264516541616,
                                 learning_rate=0.09426091382038485, max_depth=2,
                                 max_leaf_nodes=6,
                                 min_impurity_decrease=7.4293259533530295e-06,
                                 min_samples_leaf=7, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4036747584607865,
                                 n_estimators=390, random_state=123,
                                 subsample=0.579213280645811,
                                 validation_fraction=0.5325834925366492)

IBS: 0.228

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 23:55:08,036] A new study created in memory with name: no-name-ec096de9-45ee-4dd7-a750-15600a0b2f9a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:55:10,819] Trial 0 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 23:55:24,538] Trial 1 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:55:29,071] Trial 2 finished with value: 0.6290789721738743 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6290789721738743.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:55:34,088] Trial 3 finished with value: 0.6321935102194108 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6321935102194108.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:55:40,617] Trial 4 finished with value: 0.6337580845111042 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 23:55:49,221] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 23:55:53,188] Trial 6 finished with value: 0.6223931075093858 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:55:54,224] Trial 7 finished with value: 0.6289447028736863 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:55:58,893] Trial 8 finished with value: 0.6265038648777369 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 23:56:10,055] Trial 9 finished with value: 0.6256454957790245 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6337580845111042.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:56:17,260] Trial 10 finished with value: 0.6375351660054568 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6375351660054568.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 23:56:25,250] Trial 11 finished with value: 0.6405556261236294 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6405556261236294.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 23:56:32,460] Trial 12 finished with value: 0.6373720994726242 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.6405556261236294.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:56:41,774] Trial 13 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.20866416710667365, 'n_estimators': 381, 'learning_rate': 0.007730532223257889}. Best is trial 11 with value: 0.6405556261236294.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:56:51,415] Trial 14 finished with value: 0.6426929839942281 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.28551472763591135, 'n_estimators': 405, 'learning_rate': 0.09963880726742597}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:57:00,963] Trial 15 finished with value: 0.6353084721080033 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.27636288621809485, 'n_estimators': 391, 'learning_rate': 0.09947254160519346}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:57:11,469] Trial 16 finished with value: 0.6352937345833181 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.6589471971473054, 'n_estimators': 433, 'learning_rate': 0.08458290731375975}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:57:20,048] Trial 17 finished with value: 0.632200815488336 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.2583839656010779, 'n_estimators': 331, 'learning_rate': 0.08745366302928001}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:57:31,603] Trial 18 finished with value: 0.6282058655504764 and parameters: {'subsample': 0.35888747153360906, 'dropout_rate': 0.3447583890440587, 'n_estimators': 430, 'learning_rate': 0.08572151849935988}. Best is trial 14 with value: 0.6426929839942281.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:57:37,614] Trial 19 finished with value: 0.6415412561098257 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.6903547530936671, 'n_estimators': 262, 'learning_rate': 0.09294018751145315}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:57:40,107] Trial 20 finished with value: 0.6306467035464258 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.7595640861978724, 'n_estimators': 112, 'learning_rate': 0.07955999934197197}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:57:47,358] Trial 21 finished with value: 0.641465386078488 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.6425820633083541, 'n_estimators': 268, 'learning_rate': 0.09343644263544207}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:57:54,188] Trial 22 finished with value: 0.6423996252085381 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.679900295966812, 'n_estimators': 275, 'learning_rate': 0.09972677629651769}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:58:00,538] Trial 23 finished with value: 0.6374919281043481 and parameters: {'subsample': 0.1850567218204376, 'dropout_rate': 0.8014372139995105, 'n_estimators': 242, 'learning_rate': 0.09933921904847048}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:58:11,271] Trial 24 finished with value: 0.6345332783095537 and parameters: {'subsample': 0.21399481655590702, 'dropout_rate': 0.5777122688304437, 'n_estimators': 435, 'learning_rate': 0.07974743825260833}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:58:17,301] Trial 25 finished with value: 0.6282821594248703 and parameters: {'subsample': 0.41518848496569194, 'dropout_rate': 0.7543012537460877, 'n_estimators': 239, 'learning_rate': 0.06516018052006908}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:58:20,737] Trial 26 finished with value: 0.6297198966721359 and parameters: {'subsample': 0.30189765315296246, 'dropout_rate': 0.9550625782808913, 'n_estimators': 150, 'learning_rate': 0.09170102453088905}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 23:58:20,858] Trial 27 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.5697175944982166, 'n_estimators': 1, 'learning_rate': 0.08004972927576576}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 23:58:29,288] Trial 28 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6095590802808257, 'dropout_rate': 0.6997719393568667, 'n_estimators': 353, 'learning_rate': 0.0419984866507666}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 23:58:35,704] Trial 29 finished with value: 0.6258265839042355 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.4676979660844651, 'n_estimators': 283, 'learning_rate': 0.09297112972994483}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:58:38,551] Trial 30 finished with value: 0.6375278607365316 and parameters: {'subsample': 0.15736775526254157, 'dropout_rate': 0.8018172915685011, 'n_estimators': 127, 'learning_rate': 0.059413693632515835}. Best is trial 14 with value: 0.6426929839942281.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:58:44,777] Trial 31 finished with value: 0.6431600814823024 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.6272937087146848, 'n_estimators': 271, 'learning_rate': 0.09514717407912383}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:58:50,468] Trial 32 finished with value: 0.640013038293372 and parameters: {'subsample': 0.1020527537827175, 'dropout_rate': 0.6120314862955579, 'n_estimators': 231, 'learning_rate': 0.09970344117873468}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:59:01,859] Trial 33 finished with value: 0.6337364655605497 and parameters: {'subsample': 0.21799908034261378, 'dropout_rate': 0.5285516404170425, 'n_estimators': 408, 'learning_rate': 0.07046324089673363}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:59:10,456] Trial 34 finished with value: 0.63988236635136 and parameters: {'subsample': 0.18164246038967474, 'dropout_rate': 0.4110803929825292, 'n_estimators': 345, 'learning_rate': 0.0834439706892902}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:59:17,890] Trial 35 finished with value: 0.6376552486108504 and parameters: {'subsample': 0.16380438916747353, 'dropout_rate': 0.7289297289645925, 'n_estimators': 283, 'learning_rate': 0.09274200709204287}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:59:30,919] Trial 36 finished with value: 0.6306614410711112 and parameters: {'subsample': 0.30986291207776295, 'dropout_rate': 0.8219784720634046, 'n_estimators': 498, 'learning_rate': 0.07560854805483297}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 23:59:36,353] Trial 37 finished with value: 0.636039453332397 and parameters: {'subsample': 0.23971409620421638, 'dropout_rate': 0.501772727021046, 'n_estimators': 198, 'learning_rate': 0.09455852050825762}. Best is trial 31 with value: 0.6431600814823024.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:59:43,294] Trial 38 finished with value: 0.6391219100775957 and parameters: {'subsample': 0.14784367538324486, 'dropout_rate': 0.6936459800104628, 'n_estimators': 263, 'learning_rate': 0.07662382993812163}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:59:47,297] Trial 39 finished with value: 0.6297198966721359 and parameters: {'subsample': 0.3156029735189495, 'dropout_rate': 0.6155875677640822, 'n_estimators': 159, 'learning_rate': 0.06699899580023713}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 23:59:49,265] Trial 40 finished with value: 0.6298030719723988 and parameters: {'subsample': 0.4315561410698563, 'dropout_rate': 0.33656925079356487, 'n_estimators': 87, 'learning_rate': 0.08894136775152894}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:59:54,188] Trial 41 finished with value: 0.6415703073161403 and parameters: {'subsample': 0.10437662902118044, 'dropout_rate': 0.6327400907722633, 'n_estimators': 220, 'learning_rate': 0.09521162645727377}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 23:59:58,967] Trial 42 finished with value: 0.6415486883655859 and parameters: {'subsample': 0.10332149394111544, 'dropout_rate': 0.6241062991924744, 'n_estimators': 213, 'learning_rate': 0.09619227085803086}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:00:04,476] Trial 43 finished with value: 0.6408093002124848 and parameters: {'subsample': 0.13661735606279404, 'dropout_rate': 0.5972714978752179, 'n_estimators': 217, 'learning_rate': 0.09983823585511446}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:00:09,406] Trial 44 finished with value: 0.6415991045487848 and parameters: {'subsample': 0.19072472435152255, 'dropout_rate': 0.5177539535038314, 'n_estimators': 191, 'learning_rate': 0.08374118177633995}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:00:14,235] Trial 45 finished with value: 0.6407334301811473 and parameters: {'subsample': 0.19438769521144972, 'dropout_rate': 0.4289802053469966, 'n_estimators': 186, 'learning_rate': 0.08365244721491161}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:00:21,909] Trial 46 finished with value: 0.6337364655605497 and parameters: {'subsample': 0.24492418336867433, 'dropout_rate': 0.5247411692963391, 'n_estimators': 304, 'learning_rate': 0.08810862739392829}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:00:26,165] Trial 47 finished with value: 0.6414327539482592 and parameters: {'subsample': 0.1504820465769198, 'dropout_rate': 0.19942008644713155, 'n_estimators': 175, 'learning_rate': 0.02011782838490002}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:00:29,453] Trial 48 finished with value: 0.6399981737818516 and parameters: {'subsample': 0.14484578947994778, 'dropout_rate': 0.38584891170265856, 'n_estimators': 130, 'learning_rate': 0.07307996322872462}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:00:31,470] Trial 49 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.8028849489503903, 'dropout_rate': 0.4522642499653091, 'n_estimators': 81, 'learning_rate': 0.08898470899421485}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:00:43,432] Trial 50 finished with value: 0.6338270731165728 and parameters: {'subsample': 0.2808318218006839, 'dropout_rate': 0.4911565455774716, 'n_estimators': 465, 'learning_rate': 0.09625011741401299}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:00:49,113] Trial 51 finished with value: 0.6383573056157644 and parameters: {'subsample': 0.1233247075208542, 'dropout_rate': 0.617029091759293, 'n_estimators': 220, 'learning_rate': 0.09633968101843315}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:00:53,948] Trial 52 finished with value: 0.6399439227010684 and parameters: {'subsample': 0.19231524371757866, 'dropout_rate': 0.6643872329051335, 'n_estimators': 204, 'learning_rate': 0.09640274483462208}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:00:57,384] Trial 53 finished with value: 0.627521703151106 and parameters: {'subsample': 0.5690120024759672, 'dropout_rate': 0.5595717609197708, 'n_estimators': 154, 'learning_rate': 0.09067854043502498}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:01:04,016] Trial 54 finished with value: 0.6390239972526475 and parameters: {'subsample': 0.22185594771168451, 'dropout_rate': 0.29972459161112963, 'n_estimators': 281, 'learning_rate': 0.08348613746434282}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6652360515021459
[I 2024-04-17 00:01:09,827] Trial 55 finished with value: 0.6405997117108504 and parameters: {'subsample': 0.1072818855403775, 'dropout_rate': 0.734113149587146, 'n_estimators': 249, 'learning_rate': 0.09599641845476739}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263

Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:01:18,391] Trial 56 finished with value: 0.639266641727567 and parameters: {'subsample': 0.17056782725443226, 'dropout_rate': 0.6386077390817109, 'n_estimators': 329, 'learning_rate': 0.08633293380836868}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:01:28,899] Trial 57 finished with value: 0.6398929556879782 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.879394527742577, 'n_estimators': 379, 'learning_rate': 0.099784925712311}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:01:33,894] Trial 58 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.6810537336561748, 'dropout_rate': 0.2209037286953491, 'n_estimators': 189, 'learning_rate': 0.03906851946160069}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:01:39,351] Trial 59 finished with value: 0.6329760092867855 and parameters: {'subsample': 0.2509352930149644, 'dropout_rate': 0.7108306710391713, 'n_estimators': 228, 'learning_rate': 0.0906830040234655}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:01:46,709] Trial 60 finished with value: 0.6367530907811381 and parameters: {'subsample': 0.19692954375616695, 'dropout_rate': 0.7739165366028944, 'n_estimators': 310, 'learning_rate': 0.08062601076901345}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:01:52,628] Trial 61 finished with value: 0.6415412561098257 and parameters: {'subsample': 0.10716607287097886, 'dropout_rate': 0.6868396815432842, 'n_estimators': 262, 'learning_rate': 0.09417660496836659}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:01:58,778] Trial 62 finished with value: 0.6424428631096468 and parameters: {'subsample': 0.13398133933928935, 'dropout_rate': 0.660513521442359, 'n_estimators': 250, 'learning_rate': 0.09171742563262261}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:02:04,036] Trial 63 finished with value: 0.6391071725529104 and parameters: {'subsample': 0.14033157621720097, 'dropout_rate': 0.6461767902634381, 'n_estimators': 209, 'learning_rate': 0.08692487930949734}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:02:09,715] Trial 64 finished with value: 0.6390239972526475 and parameters: {'subsample': 0.17933288782684165, 'dropout_rate': 0.593253052161115, 'n_estimators': 238, 'learning_rate': 0.09714135560037845}. Best is trial 31 with value: 0.6431600814823024.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:02:17,096] Trial 65 finished with value: 0.6431817004328567 and parameters: {'subsample': 0.13216213209911687, 'dropout_rate': 0.5405734282736818, 'n_estimators': 290, 'learning_rate': 0.0911821977077325}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:02:24,074] Trial 66 finished with value: 0.6337364655605497 and parameters: {'subsample': 0.22971758828758604, 'dropout_rate': 0.5495160818731236, 'n_estimators': 291, 'learning_rate': 0.053432863042118875}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:02:31,689] Trial 67 finished with value: 0.6400270980013312 and parameters: {'subsample': 0.16878708463822192, 'dropout_rate': 0.5102925155122479, 'n_estimators': 320, 'learning_rate': 0.08198276008199658}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:02:37,884] Trial 68 finished with value: 0.6330591845870485 and parameters: {'subsample': 0.2778571423418812, 'dropout_rate': 0.583662202262188, 'n_estimators': 272, 'learning_rate': 0.09119296318129214}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:02:43,732] Trial 69 finished with value: 0.641414292078563 and parameters: {'subsample': 0.13386078991177455, 'dropout_rate': 0.15393009950145684, 'n_estimators': 252, 'learning_rate': 0.08587456281738391}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:02:52,093] Trial 70 finished with value: 0.6377852427361365 and parameters: {'subsample': 0.20433265541986942, 'dropout_rate': 0.9969638279429532, 'n_estimators': 365, 'learning_rate': 0.07634530546024197}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6652360515021459
[I 2024-04-17 00:02:56,105] Trial 71 finished with value: 0.6382277353335346 and parameters: {'subsample': 0.10752770291089753, 'dropout_rate': 0.6287574818780473, 'n_estimators': 173, 'learning_rate': 0.09403412500427213}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:03:01,148] Trial 72 finished with value: 0.6415302429301513 and parameters: {'subsample': 0.161032270125004, 'dropout_rate': 0.6724849208816212, 'n_estimators': 227, 'learning_rate': 0.0980966315480196}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:03:06,554] Trial 73 finished with value: 0.640726124912222 and parameters: {'subsample': 0.12739078809837184, 'dropout_rate': 0.7278307749188091, 'n_estimators': 246, 'learning_rate': 0.09208963122670423}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:03:13,792] Trial 74 finished with value: 0.6431748190069877 and parameters: {'subsample': 0.10098303061383129, 'dropout_rate': 0.5649686612012577, 'n_estimators': 300, 'learning_rate': 0.09009454930871107}. Best is trial 65 with value: 0.6431817004328567.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:03:21,287] Trial 75 finished with value: 0.6416749745801225 and parameters: {'subsample': 0.1546200569046924, 'dropout_rate': 0.530901829214909, 'n_estimators': 297, 'learning_rate': 0.08902111298548405}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:03:29,481] Trial 76 finished with value: 0.63988236635136 and parameters: {'subsample': 0.17012225187208585, 'dropout_rate': 0.47141288235937145, 'n_estimators': 341, 'learning_rate': 0.08898292294449694}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:03:36,313] Trial 77 finished with value: 0.6322950039682732 and parameters: {'subsample': 0.34003236576020424, 'dropout_rate': 0.5340794382591971, 'n_estimators': 293, 'learning_rate': 0.0783862396816198}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:03:44,162] Trial 78 finished with value: 0.6374087528040852 and parameters: {'subsample': 0.20835215799855494, 'dropout_rate': 0.44904110981667855, 'n_estimators': 317, 'learning_rate': 0.08495329061766407}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:03:54,265] Trial 79 finished with value: 0.6398896716202851 and parameters: {'subsample': 0.14572604478077814, 'dropout_rate': 0.5629888751565124, 'n_estimators': 410, 'learning_rate': 0.09214115931386162}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:04:01,184] Trial 80 finished with value: 0.6282821594248703 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.3979503737716092, 'n_estimators': 274, 'learning_rate': 0.08159009972832452}. Best is trial 65 with value: 0.6431817004328567.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:04:08,401] Trial 81 finished with value: 0.6432396758586508 and parameters: {'subsample': 0.13514815140998385, 'dropout_rate': 0.5849037326403841, 'n_estimators': 305, 'learning_rate': 0.0943922625884125}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:04:15,800] Trial 82 finished with value: 0.6431817004328567 and parameters: {'subsample': 0.12839124102346985, 'dropout_rate': 0.5951726356430453, 'n_estimators': 299, 'learning_rate': 0.08867950272807247}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:04:22,997] Trial 83 finished with value: 0.6431817004328567 and parameters: {'subsample': 0.12786194307609555, 'dropout_rate': 0.5956388527342826, 'n_estimators': 293, 'learning_rate': 0.0887404090726661}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:04:32,862] Trial 84 finished with value: 0.6416460503606428 and parameters: {'subsample': 0.1286260892416411, 'dropout_rate': 0.5850528743901124, 'n_estimators': 363, 'learning_rate': 0.09786950160827963}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:04:40,935] Trial 85 finished with value: 0.6424065066344071 and parameters: {'subsample': 0.1336151602190812, 'dropout_rate': 0.6735888968432888, 'n_estimators': 337, 'learning_rate': 0.09399148004353945}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:04:48,779] Trial 86 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.992873343787547, 'dropout_rate': 0.6528170874694585, 'n_estimators': 336, 'learning_rate': 0.07212296629719053}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:04:56,662] Trial 87 finished with value: 0.6383573056157644 and parameters: {'subsample': 0.12507551159390493, 'dropout_rate': 0.6037536557815114, 'n_estimators': 303, 'learning_rate': 0.015330748934167915}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:05:05,156] Trial 88 finished with value: 0.6383935351041692 and parameters: {'subsample': 0.18304053152086575, 'dropout_rate': 0.5582862203361533, 'n_estimators': 349, 'learning_rate': 0.0937331252598074}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:05:16,496] Trial 89 finished with value: 0.6345800971345769 and parameters: {'subsample': 0.23628925875665188, 'dropout_rate': 0.7059289238558123, 'n_estimators': 449, 'learning_rate': 0.08716552506523868}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:05:25,321] Trial 90 finished with value: 0.6408455297008896 and parameters: {'subsample': 0.15447216401955777, 'dropout_rate': 0.6658099450288318, 'n_estimators': 319, 'learning_rate': 0.09028854153820878}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:05:33,060] Trial 91 finished with value: 0.6400667385442641 and parameters: {'subsample': 0.12291931708504004, 'dropout_rate': 0.6772132296644691, 'n_estimators': 289, 'learning_rate': 0.09996083947651514}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:05:40,586] Trial 92 finished with value: 0.6392772310641852 and parameters: {'subsample': 0.1212797716972323, 'dropout_rate': 0.5999150715812659, 'n_estimators': 307, 'learning_rate': 0.09422061550765465}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688

Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:05:46,668] Trial 93 finished with value: 0.6430769061820396 and parameters: {'subsample': 0.10126464195698669, 'dropout_rate': 0.7785534166412713, 'n_estimators': 256, 'learning_rate': 0.09774049977966316}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:05:53,150] Trial 94 finished with value: 0.6423017123835899 and parameters: {'subsample': 0.1016868657166503, 'dropout_rate': 0.8138324696840598, 'n_estimators': 265, 'learning_rate': 0.09169151325320307}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-17 00:06:03,296] Trial 95 finished with value: 0.624171402056519 and parameters: {'subsample': 0.5198280584984859, 'dropout_rate': 0.7744284369201457, 'n_estimators': 400, 'learning_rate': 0.061758596432288704}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-17 00:06:09,697] Trial 96 finished with value: 0.639842852795262 and parameters: {'subsample': 0.14595420626153477, 'dropout_rate': 0.5768954486608358, 'n_estimators': 256, 'learning_rate': 0.09532352228050528}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-17 00:06:17,048] Trial 97 finished with value: 0.6366335590056356 and parameters: {'subsample': 0.17041898617576234, 'dropout_rate': 0.9263488734601075, 'n_estimators': 280, 'learning_rate': 0.03184901175247192}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6824034334763949
[I 2024-04-17 00:06:26,128] Trial 98 finished with value: 0.6345948346592623 and parameters: {'subsample': 0.21639673636208012, 'dropout_rate': 0.8554839554076369, 'n_estimators': 333, 'learning_rate': 0.09799989889646639}. Best is trial 81 with value: 0.6432396758586508.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475

[I 2024-04-17 00:06:35,896] A new study created in memory with name: no-name-62111260-50a7-4c0d-a834-2e6c7407b0fe

Fold 5 C-index: 0.6781115879828327
[I 2024-04-17 00:06:35,890] Trial 99 finished with value: 0.6407407354500724 and parameters: {'subsample': 0.20012350999617778, 'dropout_rate': 0.3148341192155741, 'n_estimators': 378, 'learning_rate': 0.0886400440813294}. Best is trial 81 with value: 0.6432396758586508.


* Best trial for C-index:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.6432396758586508], datetime_start=datetime.datetime(2024, 4, 17, 0, 4, 1, 186579), datetime_complete=datetime.datetime(2024, 4, 17, 0, 4, 8, 400842), params={'subsample': 0.13514815140998385, 'dropout_rate': 0.5849037326403841, 'n_estimators': 305, 'learning_rate': 0.0943922625884125}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.13514815140998385, 'dropout_rate': 0.5849037326403841, 'n_estimators': 305, 'learning_rate': 0.0943922625884125}


* Best Score for C-index:
 0.6432396758586508

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.325676523044078
Fold 2 IBS: 0.24304825871263852
Fold 3 IBS: 0.32959725402563417
Fold 4 IBS: 0.28525857993950676
Fold 5 IBS: 0.27275166189156874
[I 2024-04-17 00:06:38,581] Trial 0 finished with value: 0.29126645552268526 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4243468471583305
Fold 2 IBS: 0.3901688969230736
Fold 3 IBS: 0.3925037735733181
Fold 4 IBS: 0.37084045783124014
Fold 5 IBS: 0.34079939992495495
[I 2024-04-17 00:06:50,880] Trial 1 finished with value: 0.3837318750821835 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.388663470563614
Fold 2 IBS: 0.30068109749088767
Fold 3 IBS: 0.37991021668413694
Fold 4 IBS: 0.31125225156593306
Fold 5 IBS: 0.33025000236569196
[I 2024-04-17 00:06:54,758] Trial 2 finished with value: 0.3421514077340527 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.39180502103928067
Fold 2 IBS: 0.2723339174348366
Fold 3 IBS: 0.3810564835553453
Fold 4 IBS: 0.31083880707894046
Fold 5 IBS: 0.32302330983004995
[I 2024-04-17 00:06:59,348] Trial 3 finished with value: 0.3358115077876906 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.3942661310659211
Fold 2 IBS: 0.27825464348562706
Fold 3 IBS: 0.3841559811167191
Fold 4 IBS: 0.31009432131921916
Fold 5 IBS: 0.335556226421305
[I 2024-04-17 00:07:05,719] Trial 4 finished with value: 0.3404654606817583 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4122519263817958
Fold 2 IBS: 0.37802969684822957
Fold 3 IBS: 0.39159093324564376
Fold 4 IBS: 0.3474683993736778
Fold 5 IBS: 0.331005424885477
[I 2024-04-17 00:07:15,239] Trial 5 finished with value: 0.3720692761469648 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.29828726911528397
Fold 2 IBS: 0.21645133017694293
Fold 3 IBS: 0.29703048020856426
Fold 4 IBS: 0.2630471709724218
Fold 5 IBS: 0.24865969387198464
[I 2024-04-17 00:07:20,412] Trial 6 finished with value: 0.26469518886903953 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.26469518886903953.
Fold 1 IBS: 0.2557242083039886
Fold 2 IBS: 0.20086012542584775
Fold 3 IBS: 0.2559954533104581
Fold 4 IBS: 0.22842064037634063
Fold 5 IBS: 0.21078271864122022
[I 2024-04-17 00:07:21,595] Trial 7 finished with value: 0.23035662921157102 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.3320623714087893
Fold 2 IBS: 0.24778879382834276
Fold 3 IBS: 0.33914263875054795
Fold 4 IBS: 0.28890146090534946
Fold 5 IBS: 0.2812784361061495
[I 2024-04-17 00:07:27,113] Trial 8 finished with value: 0.2978347401998358 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.41355256605441043
Fold 2 IBS: 0.3803418251430308
Fold 3 IBS: 0.391840649836237
Fold 4 IBS: 0.35131804113613163
Fold 5 IBS: 0.3420174736572878
[I 2024-04-17 00:07:38,758] Trial 9 finished with value: 0.3758141111654195 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24688672048424357
Fold 2 IBS: 0.23091253666135533
Fold 3 IBS: 0.22886383485395365
Fold 4 IBS: 0.2411627533361748
Fold 5 IBS: 0.22809345046771862
[I 2024-04-17 00:07:39,461] Trial 10 finished with value: 0.23518385916068918 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24591184955753378
Fold 2 IBS: 0.22742364641206644
Fold 3 IBS: 0.22872479609872584
Fold 4 IBS: 0.23866162133190572
Fold 5 IBS: 0.22419206168941844
[I 2024-04-17 00:07:39,655] Trial 11 finished with value: 0.23298279501793004 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.27982325200427544
Fold 2 IBS: 0.20722413182220606
Fold 3 IBS: 0.3033964040369018
Fold 4 IBS: 0.26160633832173985
Fold 5 IBS: 0.23981413983384053
[I 2024-04-17 00:07:41,044] Trial 12 finished with value: 0.2583728532037927 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24533484626464844
Fold 2 IBS: 0.22482603295491327
Fold 3 IBS: 0.2288900501286023
Fold 4 IBS: 0.2368692484235475
Fold 5 IBS: 0.22138571816323843
[I 2024-04-17 00:07:41,242] Trial 13 finished with value: 0.23146117918699 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.2838507400334174
Fold 2 IBS: 0.2064642223133477
Fold 3 IBS: 0.2862860280530503
Fold 4 IBS: 0.24814321123030184
Fold 5 IBS: 0.23241437860460895
[I 2024-04-17 00:07:43,818] Trial 14 finished with value: 0.25143171604694525 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.35006944344323987
Fold 2 IBS: 0.2558059352575901
Fold 3 IBS: 0.35764903579940016
Fold 4 IBS: 0.29628490195601653
Fold 5 IBS: 0.2989405361322798
[I 2024-04-17 00:07:46,182] Trial 15 finished with value: 0.3117499705177053 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.3585652745905061
Fold 2 IBS: 0.2519379885893402
Fold 3 IBS: 0.36782480611244606
Fold 4 IBS: 0.30255049921240573
Fold 5 IBS: 0.3027812736793432
[I 2024-04-17 00:07:52,942] Trial 16 finished with value: 0.31673196843680823 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24637560220536686
Fold 2 IBS: 0.21110503456978988
Fold 3 IBS: 0.23491938690940084
Fold 4 IBS: 0.22943718629070567
Fold 5 IBS: 0.21121348311812857
[I 2024-04-17 00:07:54,489] Trial 17 finished with value: 0.22661013861867835 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.291291305025286
Fold 2 IBS: 0.21140388138900232
Fold 3 IBS: 0.28863212236387226
Fold 4 IBS: 0.2563863518782749
Fold 5 IBS: 0.24311757382074356
[I 2024-04-17 00:08:02,431] Trial 18 finished with value: 0.2581662468954358 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2734286915536386
Fold 2 IBS: 0.20097901536547996

Fold 3 IBS: 0.2756019255493613
Fold 4 IBS: 0.24374223787259539
Fold 5 IBS: 0.22235550248109837
[I 2024-04-17 00:08:05,382] Trial 19 finished with value: 0.24322147456443471 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24550608887605468
Fold 2 IBS: 0.2133505584021398
Fold 3 IBS: 0.23294747738469943
Fold 4 IBS: 0.23024731593258208
Fold 5 IBS: 0.2123372739360029
[I 2024-04-17 00:08:06,883] Trial 20 finished with value: 0.22687774290629575 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448259892509062
Fold 2 IBS: 0.21786672573833757
Fold 3 IBS: 0.23050391968540718
Fold 4 IBS: 0.23249100529840805
Fold 5 IBS: 0.215533050087791
[I 2024-04-17 00:08:08,802] Trial 21 finished with value: 0.22824413801216997 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24640086873642586
Fold 2 IBS: 0.2292326597688009
Fold 3 IBS: 0.22875342577755223
Fold 4 IBS: 0.23993607277337323
Fold 5 IBS: 0.22642423701728293
[I 2024-04-17 00:08:10,991] Trial 22 finished with value: 0.23414945281468702 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2589848196302069
Fold 2 IBS: 0.2024618720492697
Fold 3 IBS: 0.25302707950360914
Fold 4 IBS: 0.23227378691244918
Fold 5 IBS: 0.21704698047063445
[I 2024-04-17 00:08:14,972] Trial 23 finished with value: 0.23275890771323388 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24622272418585897
Fold 2 IBS: 0.211517231301511
Fold 3 IBS: 0.23465708353277137
Fold 4 IBS: 0.22958311755255775
Fold 5 IBS: 0.21133338172755428
[I 2024-04-17 00:08:16,583] Trial 24 finished with value: 0.2266627076600507 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.27824402320018216
Fold 2 IBS: 0.20485085384499563
Fold 3 IBS: 0.2745783058664053
Fold 4 IBS: 0.24546543206826768
Fold 5 IBS: 0.23263373515357302
[I 2024-04-17 00:08:20,187] Trial 25 finished with value: 0.24715447002668472 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.33014689072398445
Fold 2 IBS: 0.24720038348309642
Fold 3 IBS: 0.3344515997942725
Fold 4 IBS: 0.28780550809923416
Fold 5 IBS: 0.2783585358589275
[I 2024-04-17 00:08:25,941] Trial 26 finished with value: 0.295592583591903 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24499219484414198
Fold 2 IBS: 0.21624851273382031
Fold 3 IBS: 0.2314723911058174
Fold 4 IBS: 0.23142113333280664
Fold 5 IBS: 0.21391217014232608
[I 2024-04-17 00:08:26,975] Trial 27 finished with value: 0.2276092804317825 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24515366399581964
Fold 2 IBS: 0.21501049991641955
Fold 3 IBS: 0.23211607481589766
Fold 4 IBS: 0.23087262715339726
Fold 5 IBS: 0.2134002972589192
[I 2024-04-17 00:08:29,089] Trial 28 finished with value: 0.22731063262809065 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3063594897860022
Fold 2 IBS: 0.22365458368515215
Fold 3 IBS: 0.3055669075377605
Fold 4 IBS: 0.2699993099904004
Fold 5 IBS: 0.25609676833722445
[I 2024-04-17 00:08:31,596] Trial 29 finished with value: 0.2723354118673079 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3037100708108595
Fold 2 IBS: 0.22137743897919782
Fold 3 IBS: 0.3028696552655383
Fold 4 IBS: 0.2673327822795468
Fold 5 IBS: 0.253763234707761
[I 2024-04-17 00:08:35,497] Trial 30 finished with value: 0.2698106364085807 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2449141797735416
Fold 2 IBS: 0.21676885376764835
Fold 3 IBS: 0.23117242159093349
Fold 4 IBS: 0.2319218743035483
Fold 5 IBS: 0.2146636746811494
[I 2024-04-17 00:08:37,707] Trial 31 finished with value: 0.2278882008233642 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24480968404806477
Fold 2 IBS: 0.21840173072243738
Fold 3 IBS: 0.2303084891481403
Fold 4 IBS: 0.23294002575148984
Fold 5 IBS: 0.21611746639599275
[I 2024-04-17 00:08:38,705] Trial 32 finished with value: 0.22851547921322504 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24444290623218176
Fold 2 IBS: 0.22003318344553727
Fold 3 IBS: 0.23004295934041907
Fold 4 IBS: 0.23318439942131822
Fold 5 IBS: 0.21729227081764876
[I 2024-04-17 00:08:40,590] Trial 33 finished with value: 0.228999143851421 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2599735862383478
Fold 2 IBS: 0.20223791307592695
Fold 3 IBS: 0.25497930340177116
Fold 4 IBS: 0.23208609347398076
Fold 5 IBS: 0.2141781691601287
[I 2024-04-17 00:08:43,628] Trial 34 finished with value: 0.2326910130700311 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24663201725543496
Fold 2 IBS: 0.2300001255908101
Fold 3 IBS: 0.22880051556212538
Fold 4 IBS: 0.2405667786146309
Fold 5 IBS: 0.2271226637337803
[I 2024-04-17 00:08:44,052] Trial 35 finished with value: 0.23462442015135632 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.367577937922695
Fold 2 IBS: 0.27682015096192025
Fold 3 IBS: 0.3682948275396474
Fold 4 IBS: 0.30452048859388936
Fold 5 IBS: 0.31541637422362634
[I 2024-04-17 00:08:54,524] Trial 36 finished with value: 0.32652595584835564 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.39841893189624056
Fold 2 IBS: 0.32060019829104597
Fold 3 IBS: 0.3852983569562301
Fold 4 IBS: 0.31620276009532605
Fold 5 IBS: 0.3366621790004037
[I 2024-04-17 00:08:59,924] Trial 37 finished with value: 0.35143648524784926 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2614340968260537
Fold 2 IBS: 0.2021120088730102

Fold 3 IBS: 0.2566141669263308
Fold 4 IBS: 0.23453614765450895
Fold 5 IBS: 0.2122914778844625
[I 2024-04-17 00:09:04,092] Trial 38 finished with value: 0.2333975796328732 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2943463281154152
Fold 2 IBS: 0.21435275898375683
Fold 3 IBS: 0.292776623523439
Fold 4 IBS: 0.2606234117164125
Fold 5 IBS: 0.24191548716779984
[I 2024-04-17 00:09:05,417] Trial 39 finished with value: 0.26080292190136467 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2956705905294083
Fold 2 IBS: 0.21430445848659016
Fold 3 IBS: 0.2928588854990794
Fold 4 IBS: 0.2596622123064148
Fold 5 IBS: 0.24678618384472736
[I 2024-04-17 00:09:07,993] Trial 40 finished with value: 0.261856466133244 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2455156591195911
Fold 2 IBS: 0.2134495272871624
Fold 3 IBS: 0.23298021917302758
Fold 4 IBS: 0.2302623346190742
Fold 5 IBS: 0.21228868131417766
[I 2024-04-17 00:09:09,540] Trial 41 finished with value: 0.22689928430260659 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448957834513211
Fold 2 IBS: 0.2170005935741622
Fold 3 IBS: 0.2310161992206827
Fold 4 IBS: 0.23202460062538527
Fold 5 IBS: 0.21439769364800865
[I 2024-04-17 00:09:10,441] Trial 42 finished with value: 0.22786697410391196 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2658273736705565
Fold 2 IBS: 0.2020524405250075
Fold 3 IBS: 0.2606080098559383
Fold 4 IBS: 0.23638269291325226
Fold 5 IBS: 0.2218591947364019
[I 2024-04-17 00:09:12,553] Trial 43 finished with value: 0.23734594234023126 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24553832608292522
Fold 2 IBS: 0.22567851914167422
Fold 3 IBS: 0.22880097138904068
Fold 4 IBS: 0.23740161794197437
Fold 5 IBS: 0.22252686111769712
[I 2024-04-17 00:09:14,191] Trial 44 finished with value: 0.2319892591346623 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24514475725184326
Fold 2 IBS: 0.2232932452954966
Fold 3 IBS: 0.229031285656079
Fold 4 IBS: 0.23565641281785177
Fold 5 IBS: 0.2206722434927271
[I 2024-04-17 00:09:14,935] Trial 45 finished with value: 0.23075958890279952 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.34556775223404884
Fold 2 IBS: 0.26003024903765853
Fold 3 IBS: 0.35086044091810686
Fold 4 IBS: 0.29629520252719266
Fold 5 IBS: 0.2940333944770714
[I 2024-04-17 00:09:18,953] Trial 46 finished with value: 0.30935740783881566 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2540323022244742
Fold 2 IBS: 0.19805028914151954
Fold 3 IBS: 0.25415324167744757
Fold 4 IBS: 0.22661596311585877
Fold 5 IBS: 0.21041880607269076
[I 2024-04-17 00:09:21,075] Trial 47 finished with value: 0.22865412044639816 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.25728763936252025
Fold 2 IBS: 0.20231216512367317
Fold 3 IBS: 0.25262795298766366
Fold 4 IBS: 0.23138017803988314
Fold 5 IBS: 0.21120324156934484
[I 2024-04-17 00:09:25,742] Trial 48 finished with value: 0.23096223541661703 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24673307008984274
Fold 2 IBS: 0.23042055290160676
Fold 3 IBS: 0.22882596707663166
Fold 4 IBS: 0.2408186354309607
Fold 5 IBS: 0.22754159795832032
[I 2024-04-17 00:09:25,894] Trial 49 finished with value: 0.23486796469147248 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2703393986257053
Fold 2 IBS: 0.20257051463406026
Fold 3 IBS: 0.2660776078398826
Fold 4 IBS: 0.23954054354969337
Fold 5 IBS: 0.22554209413235315
[I 2024-04-17 00:09:29,094] Trial 50 finished with value: 0.24081403175633892 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24526003850914455
Fold 2 IBS: 0.21467902770255018
Fold 3 IBS: 0.23231863109009884
Fold 4 IBS: 0.23070537111335643
Fold 5 IBS: 0.2129056406944009
[I 2024-04-17 00:09:30,273] Trial 51 finished with value: 0.2271737418219102 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2465932017623929
Fold 2 IBS: 0.2299268996974446
Fold 3 IBS: 0.22878875620635092
Fold 4 IBS: 0.24043322363238803
Fold 5 IBS: 0.22699010755245638
[I 2024-04-17 00:09:31,928] Trial 52 finished with value: 0.23454643777020653 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24483084636350344
Fold 2 IBS: 0.21994268306656278
Fold 3 IBS: 0.2298159042727
Fold 4 IBS: 0.23377868427496837
Fold 5 IBS: 0.217018869345563
[I 2024-04-17 00:09:33,138] Trial 53 finished with value: 0.22907739746465952 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2542837578406007
Fold 2 IBS: 0.20408105962436318
Fold 3 IBS: 0.24632166462762337
Fold 4 IBS: 0.2299345290491981
Fold 5 IBS: 0.20927255603620012
[I 2024-04-17 00:09:33,818] Trial 54 finished with value: 0.2287787134355971 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2534849870495454
Fold 2 IBS: 0.2041508121560885
Fold 3 IBS: 0.24576477799133983
Fold 4 IBS: 0.22971527127754243
Fold 5 IBS: 0.21306295114857882
[I 2024-04-17 00:09:36,250] Trial 55 finished with value: 0.229235759924619 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24660568247659428
Fold 2 IBS: 0.21064080007395522
Fold 3 IBS: 0.23535116446600424
Fold 4 IBS: 0.22928161830063465
Fold 5 IBS: 0.21108618854351036
[I 2024-04-17 00:09:37,311] Trial 56 finished with value: 0.22659309077213977 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.32634594317205234
Fold 2 IBS: 0.2441074249846434
Fold 3 IBS: 0.33090013102352434

Fold 4 IBS: 0.28596472610806994
Fold 5 IBS: 0.27461860801929316
[I 2024-04-17 00:09:43,966] Trial 57 finished with value: 0.29238736666151666 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2524958013314946
Fold 2 IBS: 0.20467957580837548
Fold 3 IBS: 0.24466604990129345
Fold 4 IBS: 0.22951388023914565
Fold 5 IBS: 0.21232254648299242
[I 2024-04-17 00:09:45,079] Trial 58 finished with value: 0.22873557075266032 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2450766728615442
Fold 2 IBS: 0.21570571438138603
Fold 3 IBS: 0.23170031253784298
Fold 4 IBS: 0.23100841297079955
Fold 5 IBS: 0.21387190006582926
[I 2024-04-17 00:09:45,627] Trial 59 finished with value: 0.2274726025634804 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2799925625848654
Fold 2 IBS: 0.20541721127231735
Fold 3 IBS: 0.27641891339421315
Fold 4 IBS: 0.24728738758668545
Fold 5 IBS: 0.231501204035336
[I 2024-04-17 00:09:48,309] Trial 60 finished with value: 0.24812345577468348 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24506114552036967
Fold 2 IBS: 0.2227391563952413
Fold 3 IBS: 0.22917592951399726
Fold 4 IBS: 0.23541036546351077
Fold 5 IBS: 0.21951860445014307
[I 2024-04-17 00:09:49,994] Trial 61 finished with value: 0.23038104026865242 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.25624845596017926
Fold 2 IBS: 0.2031140844165004
Fold 3 IBS: 0.24945076411968525
Fold 4 IBS: 0.2308386419236711
Fold 5 IBS: 0.21467054375030795
[I 2024-04-17 00:09:52,363] Trial 62 finished with value: 0.23086449803406878 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24525813986654407
Fold 2 IBS: 0.22394706204039122
Fold 3 IBS: 0.22893913491420798
Fold 4 IBS: 0.23632535189099202
Fold 5 IBS: 0.2214331425247103
[I 2024-04-17 00:09:53,433] Trial 63 finished with value: 0.2311805662473691 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2456393866366244
Fold 2 IBS: 0.21299153169174545
Fold 3 IBS: 0.23361997509095692
Fold 4 IBS: 0.22975030626215406
Fold 5 IBS: 0.21253431380250287
[I 2024-04-17 00:09:55,692] Trial 64 finished with value: 0.22690710269679676 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24436030005286818
Fold 2 IBS: 0.21456927917072746
Fold 3 IBS: 0.23251529067371102
Fold 4 IBS: 0.23061435502797772
Fold 5 IBS: 0.21371928695614437
[I 2024-04-17 00:09:57,258] Trial 65 finished with value: 0.22715570237628574 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24425791895146917
Fold 2 IBS: 0.2144102132061209
Fold 3 IBS: 0.2326749313963326
Fold 4 IBS: 0.23050958085920942
Fold 5 IBS: 0.213580757387187
[I 2024-04-17 00:09:58,903] Trial 66 finished with value: 0.22708668036006383 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.30111629951862323
Fold 2 IBS: 0.22040932376290737
Fold 3 IBS: 0.3017744714900754
Fold 4 IBS: 0.2662157921914366
Fold 5 IBS: 0.24893153605233173
[I 2024-04-17 00:10:07,167] Trial 67 finished with value: 0.26768948460307485 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.37509937493932133
Fold 2 IBS: 0.28368774613275377
Fold 3 IBS: 0.3742704223614346
Fold 4 IBS: 0.3062111301277816
Fold 5 IBS: 0.3222655203122733
[I 2024-04-17 00:10:19,973] Trial 68 finished with value: 0.3323068387747129 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24693470011980795
Fold 2 IBS: 0.2311270655102999
Fold 3 IBS: 0.2288788081398321
Fold 4 IBS: 0.2412571776298174
Fold 5 IBS: 0.22851254319260392
[I 2024-04-17 00:10:20,376] Trial 69 finished with value: 0.2353420589184722 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.3852246921641716
Fold 2 IBS: 0.28841568341452894
Fold 3 IBS: 0.38033520143731914
Fold 4 IBS: 0.3075302238095846
Fold 5 IBS: 0.3309485924349475
[I 2024-04-17 00:10:30,618] Trial 70 finished with value: 0.33849087865211036 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2447983751594558
Fold 2 IBS: 0.21391212397472412
Fold 3 IBS: 0.2330229517211651
Fold 4 IBS: 0.23018009501747053
Fold 5 IBS: 0.21284182693141118
[I 2024-04-17 00:10:32,116] Trial 71 finished with value: 0.22695107456084535 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24442739217118456
Fold 2 IBS: 0.2202080752130095
Fold 3 IBS: 0.22992449606500545
Fold 4 IBS: 0.23367467424256175
Fold 5 IBS: 0.21734687615024553
[I 2024-04-17 00:10:33,582] Trial 72 finished with value: 0.22911630276840134 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24873206449656773
Fold 2 IBS: 0.20714960221304482
Fold 3 IBS: 0.2391494048288076
Fold 4 IBS: 0.22844134347141637
Fold 5 IBS: 0.20990424423992582
[I 2024-04-17 00:10:35,964] Trial 73 finished with value: 0.2266753318499525 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.255704669484436
Fold 2 IBS: 0.20256586151204847
Fold 3 IBS: 0.24898577012417628
Fold 4 IBS: 0.2304554628587353
Fold 5 IBS: 0.2113616322548472
[I 2024-04-17 00:10:38,358] Trial 74 finished with value: 0.22981467924684865 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.26069403640186745
Fold 2 IBS: 0.2002858960044775
Fold 3 IBS: 0.2590273478317007
Fold 4 IBS: 0.2339318232668699
Fold 5 IBS: 0.2129658995167273
[I 2024-04-17 00:10:40,684] Trial 75 finished with value: 0.23338100060432856 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2449207774729007
Fold 2 IBS: 0.2164741146584261
Fold 3 IBS: 0.23115475964699578

Fold 4 IBS: 0.2318272715320025
Fold 5 IBS: 0.21495710360760373
[I 2024-04-17 00:10:41,548] Trial 76 finished with value: 0.22786680538358572 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2506811440240583
Fold 2 IBS: 0.2053539697592853
Fold 3 IBS: 0.2432701864482772
Fold 4 IBS: 0.2284683602008423
Fold 5 IBS: 0.21006566848816424
[I 2024-04-17 00:10:44,958] Trial 77 finished with value: 0.22756786578412544 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24728609182637104
Fold 2 IBS: 0.20948456237788454
Fold 3 IBS: 0.2367879689804507
Fold 4 IBS: 0.22900068533758589
Fold 5 IBS: 0.21042389725248523
[I 2024-04-17 00:10:46,600] Trial 78 finished with value: 0.2265966411549555 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2491522359439618
Fold 2 IBS: 0.20720785646863638
Fold 3 IBS: 0.23970965460068624
Fold 4 IBS: 0.22880108027481874
Fold 5 IBS: 0.2102336161969871
[I 2024-04-17 00:10:48,664] Trial 79 finished with value: 0.22702088869701803 and parameters: {'subsample': 0.6723788047810191, 'dropout_rate': 0.7413305472330791, 'n_estimators': 82, 'learning_rate': 0.01601211448054851}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24520954400807898
Fold 2 IBS: 0.2238125298457514
Fold 3 IBS: 0.22900572731692778
Fold 4 IBS: 0.2362826500145415
Fold 5 IBS: 0.22138753922008994
[I 2024-04-17 00:10:49,950] Trial 80 finished with value: 0.23113959808107792 and parameters: {'subsample': 0.5472725501406392, 'dropout_rate': 0.7943244209025906, 'n_estimators': 49, 'learning_rate': 0.006807484156131071}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24699041341064157
Fold 2 IBS: 0.20997334219713817
Fold 3 IBS: 0.23605719801087272
Fold 4 IBS: 0.22913034206464886
Fold 5 IBS: 0.21064802263090768
[I 2024-04-17 00:10:51,899] Trial 81 finished with value: 0.2265598636628418 and parameters: {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26424067842199594
Fold 2 IBS: 0.2020280704264556
Fold 3 IBS: 0.2598748714749781
Fold 4 IBS: 0.2359141284498117
Fold 5 IBS: 0.21842360306513237
[I 2024-04-17 00:10:54,896] Trial 82 finished with value: 0.23609627036767472 and parameters: {'subsample': 0.5922453928972238, 'dropout_rate': 0.6191715075378723, 'n_estimators': 120, 'learning_rate': 0.019313878373930102}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24781953444770255
Fold 2 IBS: 0.20853906349093898
Fold 3 IBS: 0.23756791720192394
Fold 4 IBS: 0.22887020018619814
Fold 5 IBS: 0.21041983371444753
[I 2024-04-17 00:10:56,664] Trial 83 finished with value: 0.22664330980824224 and parameters: {'subsample': 0.6146609519724093, 'dropout_rate': 0.6421886730626755, 'n_estimators': 78, 'learning_rate': 0.015223953623176103}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.25409839780204135
Fold 2 IBS: 0.20375347292509463
Fold 3 IBS: 0.2467636455182986
Fold 4 IBS: 0.2300581935658389
Fold 5 IBS: 0.21199853281475728
[I 2024-04-17 00:10:58,540] Trial 84 finished with value: 0.22933444852520615 and parameters: {'subsample': 0.6143777540837653, 'dropout_rate': 0.5703883223273155, 'n_estimators': 78, 'learning_rate': 0.02181695324241678}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2454340835099757
Fold 2 IBS: 0.2136961772818287
Fold 3 IBS: 0.23273056567389488
Fold 4 IBS: 0.23041441332302406
Fold 5 IBS: 0.21235879524348852
[I 2024-04-17 00:11:00,661] Trial 85 finished with value: 0.22692680700644238 and parameters: {'subsample': 0.6445770962436083, 'dropout_rate': 0.6275050227423727, 'n_estimators': 92, 'learning_rate': 0.009130620696524702}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24639926921114977
Fold 2 IBS: 0.22928356450634207
Fold 3 IBS: 0.228754183334704
Fold 4 IBS: 0.2399932817551604
Fold 5 IBS: 0.22623158679105324
[I 2024-04-17 00:11:01,480] Trial 86 finished with value: 0.23413237711968188 and parameters: {'subsample': 0.973596102528499, 'dropout_rate': 0.6913304253389554, 'n_estimators': 30, 'learning_rate': 0.003578120462130444}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2781927071106972
Fold 2 IBS: 0.2046340904187838
Fold 3 IBS: 0.2743538100055575
Fold 4 IBS: 0.24537628788578655
Fold 5 IBS: 0.22685278282223925
[I 2024-04-17 00:11:04,018] Trial 87 finished with value: 0.24588193564861288 and parameters: {'subsample': 0.5848767613231778, 'dropout_rate': 0.5581423348405448, 'n_estimators': 110, 'learning_rate': 0.0276271691730997}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24497452272007741
Fold 2 IBS: 0.21606979660825898
Fold 3 IBS: 0.23139670442225413
Fold 4 IBS: 0.2314990720998036
Fold 5 IBS: 0.2141402661253793
[I 2024-04-17 00:11:05,099] Trial 88 finished with value: 0.22761607239515466 and parameters: {'subsample': 0.6722249946799236, 'dropout_rate': 0.6479045648592634, 'n_estimators': 46, 'learning_rate': 0.01557167084756894}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26516278956994344
Fold 2 IBS: 0.20203982539169615
Fold 3 IBS: 0.2600655154320181
Fold 4 IBS: 0.23608038055976957
Fold 5 IBS: 0.21836273665359834
[I 2024-04-17 00:11:07,996] Trial 89 finished with value: 0.2363422495214051 and parameters: {'subsample': 0.6016440183315196, 'dropout_rate': 0.5918885750046846, 'n_estimators': 128, 'learning_rate': 0.018267143567723715}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24573908001820546
Fold 2 IBS: 0.2267737594491462
Fold 3 IBS: 0.22873715282488816
Fold 4 IBS: 0.23814825000178638
Fold 5 IBS: 0.22350505658163744
[I 2024-04-17 00:11:08,303] Trial 90 finished with value: 0.23258065977513276 and parameters: {'subsample': 0.7078102048337904, 'dropout_rate': 0.6730763431068749, 'n_estimators': 9, 'learning_rate': 0.02340866249635589}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24723648683966212
Fold 2 IBS: 0.2097930026030373
Fold 3 IBS: 0.23695352163573088
Fold 4 IBS: 0.22904234996289285
Fold 5 IBS: 0.21058878491646402
[I 2024-04-17 00:11:09,967] Trial 91 finished with value: 0.22672282919155742 and parameters: {'subsample': 0.5313026641418505, 'dropout_rate': 0.5328649004247455, 'n_estimators': 76, 'learning_rate': 0.014627227900695133}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24577407492517803
Fold 2 IBS: 0.21257383264762358
Fold 3 IBS: 0.23379619719392244
Fold 4 IBS: 0.2299460468627917
Fold 5 IBS: 0.21208238643358707
[I 2024-04-17 00:11:11,690] Trial 92 finished with value: 0.22683450761262053 and parameters: {'subsample': 0.5720522744908453, 'dropout_rate': 0.5211260831534085, 'n_estimators': 76, 'learning_rate': 0.011981813096347545}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2464934086281741
Fold 2 IBS: 0.2109727784624746
Fold 3 IBS: 0.23508367038465994
Fold 4 IBS: 0.22944836247402864
Fold 5 IBS: 0.21128845087097128
[I 2024-04-17 00:11:13,713] Trial 93 finished with value: 0.22665733416406172 and parameters: {'subsample': 0.4994903777603958, 'dropout_rate': 0.5262836252450818, 'n_estimators': 87, 'learning_rate': 0.011492132047389617}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24588199063218563
Fold 2 IBS: 0.2125930156354007
Fold 3 IBS: 0.23390337282832738
Fold 4 IBS: 0.22995057861580706
Fold 5 IBS: 0.21216121330590818
[I 2024-04-17 00:11:15,835] Trial 94 finished with value: 0.22689803420352578 and parameters: {'subsample': 0.49968900942877426, 'dropout_rate': 0.523020546752894, 'n_estimators': 82, 'learning_rate': 0.011066289138468185}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24490369228481912
Fold 2 IBS: 0.2167329842481149
Fold 3 IBS: 0.23111158091166403

Fold 4 IBS: 0.23195611702074945
Fold 5 IBS: 0.21507941572440312
[I 2024-04-17 00:11:18,411] Trial 95 finished with value: 0.22795675803795015 and parameters: {'subsample': 0.5665760978972413, 'dropout_rate': 0.4628605993177724, 'n_estimators': 100, 'learning_rate': 0.006666098315025223}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.3528807852002724
Fold 2 IBS: 0.26163876419301324
Fold 3 IBS: 0.35927296600690356
Fold 4 IBS: 0.2978922662575483
Fold 5 IBS: 0.30289336976611636
[I 2024-04-17 00:11:22,569] Trial 96 finished with value: 0.31491563028477076 and parameters: {'subsample': 0.41313939490511475, 'dropout_rate': 0.5213109482382285, 'n_estimators': 158, 'learning_rate': 0.054487916689644846}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24708172105946397
Fold 2 IBS: 0.21005062605084635
Fold 3 IBS: 0.23658239945020892
Fold 4 IBS: 0.2291089640988238
Fold 5 IBS: 0.2105403389046395
[I 2024-04-17 00:11:24,429] Trial 97 finished with value: 0.2266728099127965 and parameters: {'subsample': 0.5389995281019297, 'dropout_rate': 0.6077476353900257, 'n_estimators': 73, 'learning_rate': 0.014931416501109941}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26183286577938214
Fold 2 IBS: 0.20183342233582774
Fold 3 IBS: 0.2575253907596287
Fold 4 IBS: 0.23417362585495322
Fold 5 IBS: 0.21506795896798186
[I 2024-04-17 00:11:28,276] Trial 98 finished with value: 0.23408665273955473 and parameters: {'subsample': 0.545068613650571, 'dropout_rate': 0.5497522480626178, 'n_estimators': 139, 'learning_rate': 0.01569072107683937}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24506962981870725
Fold 2 IBS: 0.2156886398952901
Fold 3 IBS: 0.23166204482631356
Fold 4 IBS: 0.2313740373654556
Fold 5 IBS: 0.2142704544460028
[I 2024-04-17 00:11:30,401] Trial 99 finished with value: 0.22761296127035385 and parameters: {'subsample': 0.4999064806675035, 'dropout_rate': 0.6190205560651515, 'n_estimators': 90, 'learning_rate': 0.00800890927792778}. Best is trial 81 with value: 0.2265598636628418.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2265598636628418], datetime_start=datetime.datetime(2024, 4, 17, 0, 10, 49, 952677), datetime_complete=datetime.datetime(2024, 4, 17, 0, 10, 51, 899137), params={'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}


* Best Score for IBS:
 0.2265598636628418

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.643
train_ibs:  0.227

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5849037326403841,
                                              learning_rate=0.0943922625884125,
                                              n_estimators=305,
                                              random_state=123,
                                              subsample=0.13514815140998385)

C-index score: 0.531

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6341528845468055,
                                              learning_rate=0.014291926646619518,
                                              n_estimators=76, random_state=123,
                                              subsample=0.6070545538128025)

IBS: 0.234

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [80]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.847   1.0
ExtraSurvivalTrees               0.842   2.0
GradientBoosting                 0.700   3.0
ComponentwiseGradientBoosting    0.643   4.0
CoxElastic                       0.639   5.0
CoxRidge                         0.633   6.0
CoxLasso                         0.506   7.0

In [81]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.208   1.0
Randomsurvivalforest           0.212   2.0
ComponentwiseGradientBoosting  0.227   3.0
GradientBoosting               0.230   4.0
CoxElastic                     0.234   5.0
CoxRidge                       0.236   6.0
CoxLasso                       0.432   7.0

In [82]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.567   1.0
CoxLasso                         0.545   2.0
CoxRidge                         0.542   3.0
CoxElastic                       0.540   4.5
Randomsurvivalforest             0.540   4.5
ComponentwiseGradientBoosting    0.531   6.0
GradientBoosting                 0.516   7.0

In [83]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxElastic                     0.228   1.5
GradientBoosting               0.228   1.5
CoxRidge                       0.229   3.0
ComponentwiseGradientBoosting  0.234   4.0
ExtraSurvivalTrees             0.235   5.0
Randomsurvivalforest           0.262   6.0
CoxLasso                       0.431   7.0

In [84]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/standard/no_selection/'  # Folder path where you want to save the files

# List of corresponding file namess
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_standard_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [85]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-17