In [88]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                           ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
    
from sklearn.preprocessing import PowerTransformer

In [89]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [90]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [91]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [92]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [93]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [94]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [95]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [96]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [97]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [98]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [99]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [100]:
# Set lower, upper time point and times for IBS calculation later 

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 14)
y_train:  (139,)

(99, 16)

# Feature Selection: PLSR

In [101]:
selected_features = [
"MTV",
"TLG",
"hpv_related",
"SUVpeak",
"uicc8_III-IV",
"oropharynx",
"cavum_oris",
"charlson",
"hypopharynx"
]

# Selecting features in the DataFrame
X_plsr = X[selected_features]
X_new = X_plsr.copy()

In [102]:
X_MAASTRO_plsr = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_plsr.copy()

# Yeo-Johnson Transformation

In [103]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)
X_new_std = X_new_std[X_new.columns]


# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [104]:
X_new

,MTV,TLG,hpv_related,SUVpeak,uicc8_III-IV,oropharynx,cavum_oris,charlson,hypopharynx
0,7.934,86.228420,0.0,14.473272,0.0,1,0,0,0
1,1.656,7.040100,0.0,5.044678,0.0,0,0,1,0
2,14.502,83.569669,0.0,7.839043,1.0,0,1,1,0
3,2.440,5.567091,0.0,2.880631,0.0,0,0,1,0
4,3.668,16.150550,0.0,5.402006,0.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
134,3.650,26.280140,1.0,9.290139,0.0,1,0,0,0
135,18.967,101.754834,1.0,7.172883,1.0,1,0,0,0
136,6.370,66.273201,1.0,13.873187,0.0,1,0,1,0
137,12.443,71.832443,1.0,7.507419,1.0,1,0,1,0
138,7.983,78.647696,1.0,13.053465,1.0,1,0,0,0

In [105]:
X_new_std

,MTV,TLG,hpv_related,SUVpeak,uicc8_III-IV,oropharynx,cavum_oris,charlson,hypopharynx
0,0.080033,0.343545,0.0,0.750782,0.0,1,0,0,0
1,-1.722060,-1.657833,0.0,-1.213660,0.0,0,0,1,0
2,0.735716,0.318631,0.0,-0.474112,1.0,0,1,1,0
3,-1.291020,-1.835650,0.0,-1.992620,0.0,0,0,1,0
4,-0.816679,-1.003396,0.0,-1.106304,0.0,0,0,1,0
...,...,...,...,...,...,...,...,...,...
134,-0.822461,-0.611074,1.0,-0.158214,0.0,1,0,0,0
135,1.008070,0.474941,1.0,-0.632361,1.0,1,0,0,0
136,-0.170908,0.133612,1.0,0.658564,0.0,1,0,1,0
137,0.574668,0.197985,1.0,-0.551725,1.0,1,0,1,0
138,0.086991,0.270290,1.0,0.527960,1.0,1,0,0,0

In [106]:
MAASTRO_new

,MTV,TLG,hpv_related,SUVpeak,uicc8_III-IV,oropharynx,cavum_oris,charlson,hypopharynx
0,22.841,263.611623,1,15.438583,0,1,0,1,0
1,5.660,36.980700,0,8.829353,1,1,0,0,0
2,7.791,74.636342,0,13.476123,1,1,0,1,0
3,7.908,46.791979,0,8.632732,1,0,0,1,0
4,15.237,107.637514,1,9.783954,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...
94,6.110,144.490782,0,31.338410,1,0,0,0,0
95,7.182,69.214868,0,13.041604,1,0,0,1,0
96,16.483,102.594274,1,8.944517,1,1,0,1,0
97,9.981,103.229492,1,14.184236,0,1,0,0,0
98,3.495,28.553212,0,10.414851,1,0,0,0,1

In [107]:
MAASTRO_new_std

,MTV,TLG,hpv_related,SUVpeak,uicc8_III-IV,oropharynx,cavum_oris,charlson,hypopharynx
0,1.188930,1.218887,1,0.893634,0,1,0,1,0
1,-0.307894,-0.335276,0,-0.254678,1,1,0,0,0
2,0.059450,0.228548,0,0.595996,1,1,0,1,0
3,0.076321,-0.145668,0,-0.296877,1,0,0,1,0
4,0.786849,0.519421,1,-0.058378,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...
94,-0.219083,0.751363,0,2.645651,1,0,0,0,0
95,-0.033134,0.168333,0,0.526028,1,0,0,1,0
96,0.867254,0.481447,1,-0.230255,1,1,0,1,0
97,0.336049,0.486335,1,0.706707,0,1,0,0,0
98,-0.873431,-0.544074,0,0.064287,1,0,0,0,1

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [108]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:58:50,423] A new study created in memory with name: no-name-406643e6-b2f0-4d7b-b4d4-eaf77c471f39

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8059071729957806

[I 2024-04-13 23:58:52,512] A new study created in memory with name: no-name-e66d87fe-fbec-4009-8c80-aba27bfc2deb

Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 23:58:52,483] Trial 0 finished with value: 0.7373181120614343 and parameters: {}. Best is trial 0 with value: 0.7373181120614343.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7373181120614343], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 50, 778624), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 52, 482453), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7373181120614343

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16450084983071073
Fold 2 IBS: 0.19911115381589756
Fold 3 IBS: 0.16198548420238557
Fold 4 IBS: 0.1434899954309807
Fold 5 IBS: 0.2643634750339842
[I 2024-04-13 23:58:55,778] Trial 0 finished with value: 0.18669019166279174 and parameters: {}. Best is trial 0 with value: 0.18669019166279174.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18669019166279174], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 52, 559953), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 55, 756198), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18669019166279174

In [109]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [110]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.737
train_ibs:  0.187

#### Test

In [111]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [112]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.593
IBS score: 0.269

In [113]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [114]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [115]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:59:01,177] A new study created in memory with name: no-name-d93d378f-1e27-409b-bb7b-95385df4d183

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5411255411255411
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.6985294117647058
Fold 4 C-index: 0.7215189873417721

[I 2024-04-13 23:59:03,258] A new study created in memory with name: no-name-9568f296-570c-4f21-be57-60c2c682992a

Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 23:59:03,144] Trial 0 finished with value: 0.6466739228552569 and parameters: {}. Best is trial 0 with value: 0.6466739228552569.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6466739228552569], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 1, 410427), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 3, 144395), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6466739228552569

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652106674792
Fold 2 IBS: 0.2215779146949956
Fold 3 IBS: 0.20453593853798394
Fold 4 IBS: 0.22473802939707874
Fold 5 IBS: 0.218124313086617
[I 2024-04-13 23:59:05,470] Trial 0 finished with value: 0.21659054335668465 and parameters: {}. Best is trial 0 with value: 0.21659054335668465.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054335668465], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 3, 449768), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 5, 467549), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054335668465

In [116]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [117]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.647
train_ibs:  0.217

#### Test

In [118]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [119]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.701

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [120]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [121]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:59:06,801] A new study created in memory with name: no-name-09b65462-2373-4275-a365-d71eb0b9b730

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793

[I 2024-04-13 23:59:09,713] A new study created in memory with name: no-name-d01dd162-319a-44e5-a927-9727f0ebe9cd

Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:09,687] Trial 0 finished with value: 0.7356108423369023 and parameters: {}. Best is trial 0 with value: 0.7356108423369023.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7356108423369023], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 6, 831896), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 9, 684013), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7356108423369023

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16493530008837418
Fold 2 IBS: 0.20469114844351927
Fold 3 IBS: 0.1603629735865767
Fold 4 IBS: 0.14338296717670074
Fold 5 IBS: 0.26373792195731416
[I 2024-04-13 23:59:14,937] Trial 0 finished with value: 0.187422062250497 and parameters: {}. Best is trial 0 with value: 0.187422062250497.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.187422062250497], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 10, 256861), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 14, 936686), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.187422062250497

In [122]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [123]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.187

#### Test

In [124]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [125]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.597

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.272

In [126]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [127]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:59:17,064] A new study created in memory with name: no-name-b8c05738-c837-4e94-8a09-79b0a1fbbba1

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:20,083] Trial 0 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:22,263] Trial 1 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:25,555] Trial 2 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:27,906] Trial 3 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 23:59:30,987] Trial 4 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:34,665] Trial 5 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:37,462] Trial 6 finished with value: 0.7356108423369023 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 23:59:41,157] Trial 7 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:44,212] Trial 8 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:48,826] Trial 9 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:53,385] Trial 10 finished with value: 0.7356108423369023 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:58,562] Trial 11 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:02,659] Trial 12 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:05,951] Trial 13 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5790002205079156}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:10,669] Trial 14 finished with value: 0.7356522673576149 and parameters: {'l1_ratio': 0.8403787283021946}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:14,976] Trial 15 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.5936985909694869}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:18,680] Trial 16 finished with value: 0.7356522673576149 and parameters: {'l1_ratio': 0.8431112134784231}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:23,428] Trial 17 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.38235460437843727}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:28,353] Trial 18 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.16904074144805598}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:32,165] Trial 19 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.4686899435891718}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:36,658] Trial 20 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:41,380] Trial 21 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6019895493221561}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:44,959] Trial 22 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6211849927954638}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:48,320] Trial 23 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.47086259237357686}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:51,911] Trial 24 finished with value: 0.7356522673576149 and parameters: {'l1_ratio': 0.7602371709740536}. Best is trial 0 with value: 0.7357254336279643.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:54,809] Trial 25 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.535645013796375}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:57,746] Trial 26 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:00,880] Trial 27 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6634231383978803}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:03,856] Trial 28 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.7875853401064746}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:07,586] Trial 29 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6145503344695415}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:10,195] Trial 30 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.2756445174548568}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:12,872] Trial 31 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.5123220976518846}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:15,122] Trial 32 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.6274659080761568}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:18,233] Trial 33 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.4923262475133719}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:20,747] Trial 34 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.5732110287369119}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:23,241] Trial 35 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6832330961068265}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:25,840] Trial 36 finished with value: 0.7356522673576149 and parameters: {'l1_ratio': 0.7799058116217068}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:28,535] Trial 37 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.4397908935595221}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:30,813] Trial 38 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:33,227] Trial 39 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:36,198] Trial 40 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.7172766488193323}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:38,599] Trial 41 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.8847917175364184}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:40,884] Trial 42 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.9383680153677963}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:43,050] Trial 43 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.8119687552544277}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:45,539] Trial 44 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.723452613421334}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:47,825] Trial 45 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.6539947524468849}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:50,236] Trial 46 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.9379996843462697}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:52,748] Trial 47 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.595326626760052}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:56,004] Trial 48 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5380353622928669}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:58,578] Trial 49 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.5994542267890958}. Best is trial 0 with value: 0.7357254336279643.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:01,658] Trial 50 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.41653985858071785}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:04,523] Trial 51 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6094269520256451}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:07,480] Trial 52 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5861258204213798}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:10,530] Trial 53 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.5027402028507912}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:12,839] Trial 54 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6459180741703606}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:15,330] Trial 55 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.7079085917343294}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:17,939] Trial 56 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.45456370102538585}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:18,783] Trial 57 finished with value: 0.6517003868355556 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:20,931] Trial 58 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5360633421324255}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:25,064] Trial 59 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5875824196567045}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:27,522] Trial 60 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6769997543108753}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:29,692] Trial 61 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.6519398170704663}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:31,981] Trial 62 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.7499572491313622}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:34,240] Trial 63 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6240676112617324}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:37,177] Trial 64 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.5094211435041684}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:39,891] Trial 65 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6463081053454892}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:42,467] Trial 66 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5862387527748419}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:44,779] Trial 67 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.7007196704016344}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:47,338] Trial 68 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.3945477520279608}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:50,487] Trial 69 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:53,403] Trial 70 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.7499320384589567}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:57,284] Trial 71 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6244989913375336}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:00,311] Trial 72 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.554777153237211}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:02,562] Trial 73 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.6524882199292468}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793

Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:04,908] Trial 74 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.4724255215999874}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:07,175] Trial 75 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6408294248192088}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:09,370] Trial 76 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6867404669271633}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:11,678] Trial 77 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5272363905541898}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:13,920] Trial 78 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.604457553074803}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:15,938] Trial 79 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.5553025757517469}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:18,209] Trial 80 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6732844202597101}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:20,729] Trial 81 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6395165750876914}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:23,275] Trial 82 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6087903712468347}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:25,797] Trial 83 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.7382350247131454}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:28,259] Trial 84 finished with value: 0.7346718752007522 and parameters: {'l1_ratio': 0.791764699647302}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:30,970] Trial 85 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.5642214404288127}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:33,562] Trial 86 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.4939482094701635}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:35,751] Trial 87 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.6970652425948979}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:37,971] Trial 88 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6400310144756236}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:41,010] Trial 89 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5890853218918972}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:42,889] Trial 90 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.5250227662294168}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:44,710] Trial 91 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.6433304739166672}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:46,733] Trial 92 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.7283461945796648}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:48,625] Trial 93 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.6700099519990255}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:50,605] Trial 94 finished with value: 0.734786466491814 and parameters: {'l1_ratio': 0.637412551778829}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:52,655] Trial 95 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.5991882792546712}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:54,894] Trial 96 finished with value: 0.7338060743349513 and parameters: {'l1_ratio': 0.5693321526006927}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:57,257] Trial 97 finished with value: 0.7357254336279643 and parameters: {'l1_ratio': 0.47960564249640314}. Best is trial 0 with value: 0.7357254336279643.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:59,263] Trial 98 finished with value: 0.7356522673576149 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 0 with value: 0.7357254336279643.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7932489451476793

[I 2024-04-14 00:04:01,677] A new study created in memory with name: no-name-87966e42-7bca-4d93-9032-2428ed38bdf2

Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:04:01,545] Trial 99 finished with value: 0.7347450414711015 and parameters: {'l1_ratio': 0.42789292409203455}. Best is trial 0 with value: 0.7357254336279643.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7357254336279643], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 17, 211345), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 20, 82657), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.7357254336279643

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16469562500727153
Fold 2 IBS: 0.20449731917283143
Fold 3 IBS: 0.1600719084718141
Fold 4 IBS: 0.14343027006612022
Fold 5 IBS: 0.2636538440298299
[I 2024-04-14 00:04:04,276] Trial 0 finished with value: 0.18726979334957342 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.18726979334957342.
Fold 1 IBS: 0.1647003456291085
Fold 2 IBS: 0.204041943438731
Fold 3 IBS: 0.16135734558481252
Fold 4 IBS: 0.14346263739572104
Fold 5 IBS: 0.2636476971898714
[I 2024-04-14 00:04:06,670] Trial 1 finished with value: 0.1874419938476489 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.18726979334957342.
Fold 1 IBS: 0.1646944271302574
Fold 2 IBS: 0.20394851497628436
Fold 3 IBS: 0.16131777936473066
Fold 4 IBS: 0.14349730341343223
Fold 5 IBS: 0.2636546829900082
[I 2024-04-14 00:04:08,854] Trial 2 finished with value: 0.18742254157494256 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.18726979334957342.
Fold 1 IBS: 0.16465124827139324
Fold 2 IBS: 0.20437734849580524
Fold 3 IBS: 0.1600785866927873
Fold 4 IBS: 0.14346131750757374
Fold 5 IBS: 0.26365583666548476
[I 2024-04-14 00:04:11,030] Trial 3 finished with value: 0.18724486752660885 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.18724486752660885.
Fold 1 IBS: 0.16458694354798437
Fold 2 IBS: 0.204540131262208
Fold 3 IBS: 0.16015296109624308
Fold 4 IBS: 0.14345664789599996
Fold 5 IBS: 0.26368228554584344
[I 2024-04-14 00:04:12,992] Trial 4 finished with value: 0.1872837938696558 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 3 with value: 0.18724486752660885.
Fold 1 IBS: 0.16467288276719752
Fold 2 IBS: 0.20422468172340902
Fold 3 IBS: 0.16140003431858185
Fold 4 IBS: 0.14344374766060056
Fold 5 IBS: 0.26363072563891343
[I 2024-04-14 00:04:15,332] Trial 5 finished with value: 0.18747441442174045 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 3 with value: 0.18724486752660885.
Fold 1 IBS: 0.1649402611861414
Fold 2 IBS: 0.20468556112790146
Fold 3 IBS: 0.16031423597207928
Fold 4 IBS: 0.1433676422251426
Fold 5 IBS: 0.26372014234998975
[I 2024-04-14 00:04:17,716] Trial 6 finished with value: 0.18740556857225088 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 3 with value: 0.18724486752660885.
Fold 1 IBS: 0.16459251843804928
Fold 2 IBS: 0.2044907885744395
Fold 3 IBS: 0.16022224448686456
Fold 4 IBS: 0.1434163444664405
Fold 5 IBS: 0.26370161269341585
[I 2024-04-14 00:04:19,737] Trial 7 finished with value: 0.18728470173184195 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 3 with value: 0.18724486752660885.
Fold 1 IBS: 0.16464681323919847
Fold 2 IBS: 0.2042962986795689
Fold 3 IBS: 0.1599422390458009
Fold 4 IBS: 0.14345056499086475
Fold 5 IBS: 0.2636700404380947
[I 2024-04-14 00:04:22,371] Trial 8 finished with value: 0.18720119127870555 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16469023935670343
Fold 2 IBS: 0.20418448658630836
Fold 3 IBS: 0.16140210170419161
Fold 4 IBS: 0.14347798961889546
Fold 5 IBS: 0.2636347769864006
[I 2024-04-14 00:04:25,211] Trial 9 finished with value: 0.1874779188504999 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16470836950794154
Fold 2 IBS: 0.203483441887897
Fold 3 IBS: 0.16128504512854924
Fold 4 IBS: 0.1433504902620005
Fold 5 IBS: 0.26362352308125214
[I 2024-04-14 00:04:27,538] Trial 10 finished with value: 0.1872901739735281 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16474454633276336
Fold 2 IBS: 0.2043853643917153
Fold 3 IBS: 0.16011546401523583
Fold 4 IBS: 0.14347569026479698
Fold 5 IBS: 0.26367029870203235
[I 2024-04-14 00:04:29,762] Trial 11 finished with value: 0.18727827274130876 and parameters: {'l1_ratio': 0.560971385599288}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16474220096863235
Fold 2 IBS: 0.20438970033382217
Fold 3 IBS: 0.16144019988780875
Fold 4 IBS: 0.1434732149135151
Fold 5 IBS: 0.2636781463808151
[I 2024-04-14 00:04:31,938] Trial 12 finished with value: 0.1875446924969187 and parameters: {'l1_ratio': 0.5663251339911302}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16491508897792723
Fold 2 IBS: 0.2046405557587757
Fold 3 IBS: 0.16016735380976418
Fold 4 IBS: 0.14337123697410106
Fold 5 IBS: 0.2637082514397293
[I 2024-04-14 00:04:34,172] Trial 13 finished with value: 0.18736049739205948 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646414325387292
Fold 2 IBS: 0.2043100738557395
Fold 3 IBS: 0.1614004284622062
Fold 4 IBS: 0.14347405764210044
Fold 5 IBS: 0.26369210480033556
[I 2024-04-14 00:04:36,587] Trial 14 finished with value: 0.1875036194598222 and parameters: {'l1_ratio': 0.49455441315160786}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.2139166461568017
Fold 2 IBS: 0.2214173386775824
Fold 3 IBS: 0.20397451525128904
Fold 4 IBS: 0.22397152995423045
Fold 5 IBS: 0.21798664243484367
[I 2024-04-14 00:04:37,720] Trial 15 finished with value: 0.21625333449494946 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16468362198853062
Fold 2 IBS: 0.2040635517438387
Fold 3 IBS: 0.16134490099158155
Fold 4 IBS: 0.14352487030962577
Fold 5 IBS: 0.2636320839275494
[I 2024-04-14 00:04:40,311] Trial 16 finished with value: 0.1874498057922252 and parameters: {'l1_ratio': 0.30518868850921266}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16463865662704102
Fold 2 IBS: 0.2044081558793355
Fold 3 IBS: 0.16006524347145468
Fold 4 IBS: 0.1434047737911706
Fold 5 IBS: 0.2636533088561227
[I 2024-04-14 00:04:42,174] Trial 17 finished with value: 0.1872340277250249 and parameters: {'l1_ratio': 0.5929393609348088}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1649297425178238
Fold 2 IBS: 0.2045835138460841
Fold 3 IBS: 0.16023119278645997
Fold 4 IBS: 0.1434405166070619
Fold 5 IBS: 0.26366017075447296
[I 2024-04-14 00:04:44,107] Trial 18 finished with value: 0.18736902730238053 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16468111049537765
Fold 2 IBS: 0.2041930268988204
Fold 3 IBS: 0.16142653818380898
Fold 4 IBS: 0.14351187511535632
Fold 5 IBS: 0.26366612393580835
[I 2024-04-14 00:04:46,456] Trial 19 finished with value: 0.18749573492583435 and parameters: {'l1_ratio': 0.4078975242361199}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16463331363863848
Fold 2 IBS: 0.20444395646786415
Fold 3 IBS: 0.1601461466706446
Fold 4 IBS: 0.14343268905317438
Fold 5 IBS: 0.2636812381401081
[I 2024-04-14 00:04:48,859] Trial 20 finished with value: 0.18726746879408593 and parameters: {'l1_ratio': 0.6127580877814559}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464242130779042
Fold 2 IBS: 0.20430789096783533
Fold 3 IBS: 0.1613974877893808
Fold 4 IBS: 0.14347028048220042
Fold 5 IBS: 0.2636886116721769
[I 2024-04-14 00:04:51,668] Trial 21 finished with value: 0.18750133844387679 and parameters: {'l1_ratio': 0.4923489010257901}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646313418296755
Fold 2 IBS: 0.2044500613155214
Fold 3 IBS: 0.16017634835785016
Fold 4 IBS: 0.1434440977390975
Fold 5 IBS: 0.2636925683238826
[I 2024-04-14 00:04:53,844] Trial 22 finished with value: 0.1872788835132054 and parameters: {'l1_ratio': 0.6211849927954638}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465100158832077
Fold 2 IBS: 0.20428537981053055
Fold 3 IBS: 0.16141741852070768
Fold 4 IBS: 0.143527506066721
Fold 5 IBS: 0.26365158589504906
[I 2024-04-14 00:04:56,115] Trial 23 finished with value: 0.1875065783762658 and parameters: {'l1_ratio': 0.4701433285605998}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646981059879641
Fold 2 IBS: 0.20409655237737556
Fold 3 IBS: 0.16139527390306962
Fold 4 IBS: 0.14350669059405521
Fold 5 IBS: 0.2636285206784546
[I 2024-04-14 00:04:58,539] Trial 24 finished with value: 0.18746502870818382 and parameters: {'l1_ratio': 0.329990397647379}. Best is trial 8 with value: 0.18720119127870555.

Fold 1 IBS: 0.16492302770825934
Fold 2 IBS: 0.20459171325445838
Fold 3 IBS: 0.16029028566299094
Fold 4 IBS: 0.14345934583032743
Fold 5 IBS: 0.2636822114088275
[I 2024-04-14 00:05:00,770] Trial 25 finished with value: 0.1873893167729727 and parameters: {'l1_ratio': 0.8277117787416304}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464502137730158
Fold 2 IBS: 0.20439349740742072
Fold 3 IBS: 0.16144555475428507
Fold 4 IBS: 0.14348015102692974
Fold 5 IBS: 0.2636850530467372
[I 2024-04-14 00:05:02,866] Trial 26 finished with value: 0.18752985552253482 and parameters: {'l1_ratio': 0.5711012798301316}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1648742737962242
Fold 2 IBS: 0.20456045631195469
Fold 3 IBS: 0.16027496193957216
Fold 4 IBS: 0.14338878396514534
Fold 5 IBS: 0.2636656853757507
[I 2024-04-14 00:05:04,808] Trial 27 finished with value: 0.18735283227772942 and parameters: {'l1_ratio': 0.7581476603189202}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646923470975164
Fold 2 IBS: 0.20390658707290113
Fold 3 IBS: 0.16135568638815995
Fold 4 IBS: 0.14347090939916224
Fold 5 IBS: 0.26363478102872756
[I 2024-04-14 00:05:07,201] Trial 28 finished with value: 0.18741206219729345 and parameters: {'l1_ratio': 0.2025095518368651}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.164950921682678
Fold 2 IBS: 0.20467331662400565
Fold 3 IBS: 0.16021757187896823
Fold 4 IBS: 0.14344899130986247
Fold 5 IBS: 0.2636802888562035
[I 2024-04-14 00:05:09,269] Trial 29 finished with value: 0.18739421807034357 and parameters: {'l1_ratio': 0.9415089734292671}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.164622979205101
Fold 2 IBS: 0.20447262338626365
Fold 3 IBS: 0.16012006651822658
Fold 4 IBS: 0.14348704107445343
Fold 5 IBS: 0.26366369100266873
[I 2024-04-14 00:05:11,478] Trial 30 finished with value: 0.1872732802373427 and parameters: {'l1_ratio': 0.6547583765744691}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16463554112959117
Fold 2 IBS: 0.20441617038466006
Fold 3 IBS: 0.16011560775654
Fold 4 IBS: 0.14342089087468674
Fold 5 IBS: 0.26366950649761184
[I 2024-04-14 00:05:13,607] Trial 31 finished with value: 0.18725154332861793 and parameters: {'l1_ratio': 0.6042464204914008}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465183248240775
Fold 2 IBS: 0.2043744869807658
Fold 3 IBS: 0.1600737392125979
Fold 4 IBS: 0.14345943578579595
Fold 5 IBS: 0.2636539335748344
[I 2024-04-14 00:05:15,933] Trial 32 finished with value: 0.18724268560728036 and parameters: {'l1_ratio': 0.5501220413991621}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646333997434574
Fold 2 IBS: 0.20433165051837576
Fold 3 IBS: 0.16143027028170534
Fold 4 IBS: 0.1435115466960148
Fold 5 IBS: 0.2636657610837936
[I 2024-04-14 00:05:18,737] Trial 33 finished with value: 0.18751452566466936 and parameters: {'l1_ratio': 0.5173989954769777}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16466993363335844
Fold 2 IBS: 0.20414142395393148
Fold 3 IBS: 0.1614166301530493
Fold 4 IBS: 0.14351532486516613
Fold 5 IBS: 0.2636547135797267
[I 2024-04-14 00:05:21,381] Trial 34 finished with value: 0.1874796052370464 and parameters: {'l1_ratio': 0.3705140939663881}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16458815405268098
Fold 2 IBS: 0.20453558354886214
Fold 3 IBS: 0.1601251667567641
Fold 4 IBS: 0.1434476009320332
Fold 5 IBS: 0.2636726522862306
[I 2024-04-14 00:05:23,551] Trial 35 finished with value: 0.18727383151531424 and parameters: {'l1_ratio': 0.7114643040644401}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646562902531001
Fold 2 IBS: 0.2042651931104226
Fold 3 IBS: 0.1614007540545326
Fold 4 IBS: 0.14351144686059067
Fold 5 IBS: 0.26369391897640526
[I 2024-04-14 00:05:26,260] Trial 36 finished with value: 0.18750552065101025 and parameters: {'l1_ratio': 0.45812531174651205}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1647107023380684
Fold 2 IBS: 0.20391396722651153
Fold 3 IBS: 0.16133720748808844
Fold 4 IBS: 0.14344624091875222
Fold 5 IBS: 0.26361247528468246
[I 2024-04-14 00:05:28,381] Trial 37 finished with value: 0.1874041186512206 and parameters: {'l1_ratio': 0.21447341053919816}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646568785643809
Fold 2 IBS: 0.20436118947968265
Fold 3 IBS: 0.16003760729441824
Fold 4 IBS: 0.14343575539865322
Fold 5 IBS: 0.2636938936494133
[I 2024-04-14 00:05:30,509] Trial 38 finished with value: 0.18723706487730968 and parameters: {'l1_ratio': 0.5348029475462887}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465723408899535
Fold 2 IBS: 0.20436078315270137
Fold 3 IBS: 0.16003574699103215
Fold 4 IBS: 0.14343504004306593
Fold 5 IBS: 0.26369322490521546
[I 2024-04-14 00:05:32,928] Trial 39 finished with value: 0.18723640583620207 and parameters: {'l1_ratio': 0.5343557066482996}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16462171976924833
Fold 2 IBS: 0.20447622175028235
Fold 3 IBS: 0.16014124196516244
Fold 4 IBS: 0.14349398747410178
Fold 5 IBS: 0.26367119692757035
[I 2024-04-14 00:05:35,436] Trial 40 finished with value: 0.18728087357727305 and parameters: {'l1_ratio': 0.6604827452564003}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16466317866742883
Fold 2 IBS: 0.20424887463265823
Fold 3 IBS: 0.1614286580440394
Fold 4 IBS: 0.14348294362193081
Fold 5 IBS: 0.2636675067511589
[I 2024-04-14 00:05:38,268] Trial 41 finished with value: 0.18749823234344323 and parameters: {'l1_ratio': 0.4428597480970563}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465848382261472
Fold 2 IBS: 0.20435708930887977
Fold 3 IBS: 0.1599872230593713
Fold 4 IBS: 0.14342914746086965
Fold 5 IBS: 0.2636874710594415
[I 2024-04-14 00:05:40,948] Trial 42 finished with value: 0.18722388294223538 and parameters: {'l1_ratio': 0.5306956579982879}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16463247311678622
Fold 2 IBS: 0.20433420449596842
Fold 3 IBS: 0.16143379484418552
Fold 4 IBS: 0.14351607438931635
Fold 5 IBS: 0.2636703252970218
[I 2024-04-14 00:05:43,467] Trial 43 finished with value: 0.18751737442865565 and parameters: {'l1_ratio': 0.5202793352350564}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16468100701535987
Fold 2 IBS: 0.20413401533942177
Fold 3 IBS: 0.16138695322716168
Fold 4 IBS: 0.14347941694482716
Fold 5 IBS: 0.2636813858789872
[I 2024-04-14 00:05:46,236] Trial 44 finished with value: 0.18747255568115154 and parameters: {'l1_ratio': 0.35330501191376174}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16487273325328589
Fold 2 IBS: 0.20456243189569803
Fold 3 IBS: 0.1600907358174909
Fold 4 IBS: 0.14339314287923205
Fold 5 IBS: 0.26367043382687555
[I 2024-04-14 00:05:48,544] Trial 45 finished with value: 0.1873178955345165 and parameters: {'l1_ratio': 0.7621502926948881}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16467548127555548
Fold 2 IBS: 0.20420579218196483
Fold 3 IBS: 0.16139184856921174
Fold 4 IBS: 0.14352703345517528
Fold 5 IBS: 0.26368483199684595
[I 2024-04-14 00:05:51,091] Trial 46 finished with value: 0.18749699749575063 and parameters: {'l1_ratio': 0.4178876522481797}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646812918625194
Fold 2 IBS: 0.20400836929954014
Fold 3 IBS: 0.16137634252769864
Fold 4 IBS: 0.14349530928676935
Fold 5 IBS: 0.26366815405834054
[I 2024-04-14 00:05:53,771] Trial 47 finished with value: 0.18744589340697362 and parameters: {'l1_ratio': 0.27018649723045707}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464038218891783
Fold 2 IBS: 0.20440560897414442
Fold 3 IBS: 0.1600546525691416
Fold 4 IBS: 0.14350214424714716
Fold 5 IBS: 0.2637074128648655
[I 2024-04-14 00:05:56,056] Trial 48 finished with value: 0.18726204016884332 and parameters: {'l1_ratio': 0.5868463753001749}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465795234128408
Fold 2 IBS: 0.20435882134445738
Fold 3 IBS: 0.15999363085360951
Fold 4 IBS: 0.14343159033424255
Fold 5 IBS: 0.2636897407421677
[I 2024-04-14 00:05:58,139] Trial 49 finished with value: 0.18722634712315225 and parameters: {'l1_ratio': 0.5322078229897522}. Best is trial 8 with value: 0.18720119127870555.

Fold 1 IBS: 0.1646233455981672
Fold 2 IBS: 0.204471613951031
Fold 3 IBS: 0.1601195550835879
Fold 4 IBS: 0.14348509667238624
Fold 5 IBS: 0.26366169510967513
[I 2024-04-14 00:06:00,291] Trial 50 finished with value: 0.1872722612829695 and parameters: {'l1_ratio': 0.6531713347516178}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646569893970897
Fold 2 IBS: 0.2043609120872407
Fold 3 IBS: 0.16003633723065996
Fold 4 IBS: 0.1434352670057949
Fold 5 IBS: 0.26369343709403986
[I 2024-04-14 00:06:02,361] Trial 51 finished with value: 0.18723658856296505 and parameters: {'l1_ratio': 0.5344975351962169}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464257898199788
Fold 2 IBS: 0.20430705427785487
Fold 3 IBS: 0.16144530551933242
Fold 4 IBS: 0.14346883478293687
Fold 5 IBS: 0.2636872612956089
[I 2024-04-14 00:06:04,584] Trial 52 finished with value: 0.1875102069715462 and parameters: {'l1_ratio': 0.4915091696239893}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16466470297456984
Fold 2 IBS: 0.20424460658572452
Fold 3 IBS: 0.1614242171539566
Fold 4 IBS: 0.14347675392975578
Fold 5 IBS: 0.2636618181297984
[I 2024-04-14 00:06:06,890] Trial 53 finished with value: 0.18749441975476103 and parameters: {'l1_ratio': 0.4396727675720868}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16462898199832268
Fold 2 IBS: 0.20445626561808736
Fold 3 IBS: 0.16002967585711034
Fold 4 IBS: 0.14345576215857186
Fold 5 IBS: 0.2637041534979246
[I 2024-04-14 00:06:08,989] Trial 54 finished with value: 0.18725496782600337 and parameters: {'l1_ratio': 0.6300075472232939}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16474694151784544
Fold 2 IBS: 0.2043809304565156
Fold 3 IBS: 0.16009505756358014
Fold 4 IBS: 0.14346772534742805
Fold 5 IBS: 0.26366231820361186
[I 2024-04-14 00:06:11,398] Trial 55 finished with value: 0.18727059461779622 and parameters: {'l1_ratio': 0.5556098594148129}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16466115670757925
Fold 2 IBS: 0.2041771012465582
Fold 3 IBS: 0.1613916341614344
Fold 4 IBS: 0.1434636604951368
Fold 5 IBS: 0.2636857320588947
[I 2024-04-14 00:06:13,698] Trial 56 finished with value: 0.18747585693392066 and parameters: {'l1_ratio': 0.38576279454234186}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465092160365655
Fold 2 IBS: 0.20428558621110549
Fold 3 IBS: 0.16141775806903766
Fold 4 IBS: 0.1434311470599924
Fold 5 IBS: 0.2636519160186501
[I 2024-04-14 00:06:16,066] Trial 57 finished with value: 0.18748746579248846 and parameters: {'l1_ratio': 0.4703314514165695}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464285573439483
Fold 2 IBS: 0.20439910812657783
Fold 3 IBS: 0.16003155666172902
Fold 4 IBS: 0.1434904700756174
Fold 5 IBS: 0.26369523451389076
[I 2024-04-14 00:06:18,405] Trial 58 finished with value: 0.187251845022442 and parameters: {'l1_ratio': 0.5783360708467935}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16463737062911316
Fold 2 IBS: 0.20432130614558497
Fold 3 IBS: 0.1614152863788142
Fold 4 IBS: 0.14349302138681
Fold 5 IBS: 0.26364714915455595
[I 2024-04-14 00:06:20,655] Trial 59 finished with value: 0.18750282673897564 and parameters: {'l1_ratio': 0.5058732544590263}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16470171571647535
Fold 2 IBS: 0.20448544378450786
Fold 3 IBS: 0.16019200734120106
Fold 4 IBS: 0.1434050809725401
Fold 5 IBS: 0.2636903720637777
[I 2024-04-14 00:06:22,860] Trial 60 finished with value: 0.1872949239757004 and parameters: {'l1_ratio': 0.675688573771925}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646550956131326
Fold 2 IBS: 0.20436549411054167
Fold 3 IBS: 0.16005893543143293
Fold 4 IBS: 0.14344396104619564
Fold 5 IBS: 0.2637014551168784
[I 2024-04-14 00:06:25,138] Trial 61 finished with value: 0.18724498826363623 and parameters: {'l1_ratio': 0.5399789153353223}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465826220553173
Fold 2 IBS: 0.204343782362825
Fold 3 IBS: 0.159989815947433
Fold 4 IBS: 0.1434301358827145
Fold 5 IBS: 0.263688396825746
[I 2024-04-14 00:06:27,353] Trial 62 finished with value: 0.18722207864485005 and parameters: {'l1_ratio': 0.5313066237188923}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16463163063128528
Fold 2 IBS: 0.20444911823747627
Fold 3 IBS: 0.16017178232523752
Fold 4 IBS: 0.1434423301482455
Fold 5 IBS: 0.26369086533916425
[I 2024-04-14 00:06:29,826] Trial 63 finished with value: 0.18727714533628176 and parameters: {'l1_ratio': 0.6198664703635569}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464589867393445
Fold 2 IBS: 0.2042987126387485
Fold 3 IBS: 0.15995295408046603
Fold 4 IBS: 0.14345448352190152
Fold 5 IBS: 0.2636739596466921
[I 2024-04-14 00:06:32,237] Trial 64 finished with value: 0.18720520171234853 and parameters: {'l1_ratio': 0.48330348955178587}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464393285742204
Fold 2 IBS: 0.20430389963392934
Fold 3 IBS: 0.16144129593681786
Fold 4 IBS: 0.1434633941911021
Fold 5 IBS: 0.2636822014102196
[I 2024-04-14 00:06:34,386] Trial 65 finished with value: 0.1875069448058982 and parameters: {'l1_ratio': 0.48837072595204084}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16466826465840861
Fold 2 IBS: 0.20423595036097777
Fold 3 IBS: 0.16141369447243417
Fold 4 IBS: 0.14346225455685369
Fold 5 IBS: 0.26364823253336306
[I 2024-04-14 00:06:36,953] Trial 66 finished with value: 0.18748567931640747 and parameters: {'l1_ratio': 0.4323337153563157}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16473521295417348
Fold 2 IBS: 0.20440243696007182
Fold 3 IBS: 0.16003818402171047
Fold 4 IBS: 0.1434962632464297
Fold 5 IBS: 0.2637016052271852
[I 2024-04-14 00:06:39,342] Trial 67 finished with value: 0.18727474048191414 and parameters: {'l1_ratio': 0.5825994361001313}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465620391753957
Fold 2 IBS: 0.20426491806810573
Fold 3 IBS: 0.16140038618534966
Fold 4 IBS: 0.1435109755057163
Fold 5 IBS: 0.2636935515113149
[I 2024-04-14 00:06:43,065] Trial 68 finished with value: 0.18750520703760526 and parameters: {'l1_ratio': 0.45786588416124097}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16469034842878977
Fold 2 IBS: 0.20410053797362368
Fold 3 IBS: 0.16136211383557908
Fold 4 IBS: 0.1435344892472313
Fold 5 IBS: 0.26365223653989067
[I 2024-04-14 00:06:45,734] Trial 69 finished with value: 0.1874679452050229 and parameters: {'l1_ratio': 0.3400461849948634}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465441590845212
Fold 2 IBS: 0.2041923305690459
Fold 3 IBS: 0.16141149725288328
Fold 4 IBS: 0.1434909938733672
Fold 5 IBS: 0.2636468857217921
[I 2024-04-14 00:06:48,055] Trial 70 finished with value: 0.1874792246651081 and parameters: {'l1_ratio': 0.39808787496532727}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465920632016037
Fold 2 IBS: 0.20435522217468693
Fold 3 IBS: 0.15997865237284395
Fold 4 IBS: 0.14342588102107975
Fold 5 IBS: 0.263684477548944
[I 2024-04-14 00:06:50,754] Trial 71 finished with value: 0.187220687887543 and parameters: {'l1_ratio': 0.5286850391711021}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646362038471533
Fold 2 IBS: 0.20441447123316187
Fold 3 IBS: 0.16010672500780182
Fold 4 IBS: 0.14341746204984263
Fold 5 IBS: 0.2636660662516467
[I 2024-04-14 00:06:52,745] Trial 72 finished with value: 0.18724818567792126 and parameters: {'l1_ratio': 0.6018103922384312}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464591027825695
Fold 2 IBS: 0.20429868273508228
Fold 3 IBS: 0.15995282163064722
Fold 4 IBS: 0.14345443227607363
Fold 5 IBS: 0.26367391157810527
[I 2024-04-14 00:06:54,868] Trial 73 finished with value: 0.18720515169963306 and parameters: {'l1_ratio': 0.4832746057704764}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16465025147346282
Fold 2 IBS: 0.20428787172813076
Fold 3 IBS: 0.16142057442069743
Fold 4 IBS: 0.14343502269739242
Fold 5 IBS: 0.2636556058038754
[I 2024-04-14 00:06:57,073] Trial 74 finished with value: 0.18748986522471175 and parameters: {'l1_ratio': 0.4724255215999874}. Best is trial 8 with value: 0.18720119127870555.

Fold 1 IBS: 0.16463799926571732
Fold 2 IBS: 0.20431965754133014
Fold 3 IBS: 0.16141304465920647
Fold 4 IBS: 0.14349013355707313
Fold 5 IBS: 0.26364421037649893
[I 2024-04-14 00:06:59,137] Trial 75 finished with value: 0.1875010090799652 and parameters: {'l1_ratio': 0.5041192360230345}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464859813249
Fold 2 IBS: 0.20438415691590445
Fold 3 IBS: 0.16010991283393333
Fold 4 IBS: 0.14347351757544885
Fold 5 IBS: 0.26366815606211175
[I 2024-04-14 00:07:01,411] Trial 76 finished with value: 0.18725686830397764 and parameters: {'l1_ratio': 0.5595001145684224}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646079927827805
Fold 2 IBS: 0.20454688189514722
Fold 3 IBS: 0.16018894183323895
Fold 4 IBS: 0.1434701781534836
Fold 5 IBS: 0.2636968931690041
[I 2024-04-14 00:07:03,414] Trial 77 finished with value: 0.18730217756673087 and parameters: {'l1_ratio': 0.7318055230343666}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16462629877659513
Fold 2 IBS: 0.20446307362196173
Fold 3 IBS: 0.16006933202374854
Fold 4 IBS: 0.1434686857392869
Fold 5 IBS: 0.2636547207764262
[I 2024-04-14 00:07:05,593] Trial 78 finished with value: 0.1872564221876037 and parameters: {'l1_ratio': 0.6400359215091316}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646777882096507
Fold 2 IBS: 0.20421383872928292
Fold 3 IBS: 0.1613852171937795
Fold 4 IBS: 0.14352362104562222
Fold 5 IBS: 0.2636769139121452
[I 2024-04-14 00:07:07,927] Trial 79 finished with value: 0.1874954758180961 and parameters: {'l1_ratio': 0.4136110469125477}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16467827584126313
Fold 2 IBS: 0.20407540380727784
Fold 3 IBS: 0.16135875388107562
Fold 4 IBS: 0.14345183060835962
Fold 5 IBS: 0.2636483277442189
[I 2024-04-14 00:07:10,119] Trial 80 finished with value: 0.18744251837643905 and parameters: {'l1_ratio': 0.31162993252413296}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16466164066630712
Fold 2 IBS: 0.2043353898684428
Fold 3 IBS: 0.16143543676529754
Fold 4 IBS: 0.14351817972625933
Fold 5 IBS: 0.2636724299188112
[I 2024-04-14 00:07:12,220] Trial 81 finished with value: 0.1875246153890236 and parameters: {'l1_ratio': 0.5216280526412524}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16472852685756667
Fold 2 IBS: 0.20441276961064744
Fold 3 IBS: 0.16009778593869714
Fold 4 IBS: 0.14341401281382532
Fold 5 IBS: 0.26366259491883487
[I 2024-04-14 00:07:14,783] Trial 82 finished with value: 0.1872631380279143 and parameters: {'l1_ratio': 0.5993766546387894}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.1646457909421977
Fold 2 IBS: 0.20429899024600717
Fold 3 IBS: 0.15995418379772386
Fold 4 IBS: 0.14345495932496047
Fold 5 IBS: 0.263674405916752
[I 2024-04-14 00:07:16,967] Trial 83 finished with value: 0.1872056660455282 and parameters: {'l1_ratio': 0.48357180712641273}. Best is trial 8 with value: 0.18720119127870555.
Fold 1 IBS: 0.16464761422805502
Fold 2 IBS: 0.20429368834866746
Fold 3 IBS: 0.1599306196799559
Fold 4 IBS: 0.14344610697614035
Fold 5 IBS: 0.26366587032628525
[I 2024-04-14 00:07:18,831] Trial 84 finished with value: 0.18719677991182077 and parameters: {'l1_ratio': 0.47850235241861494}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16467168678888516
Fold 2 IBS: 0.2041374499801569
Fold 3 IBS: 0.1614124075087739
Fold 4 IBS: 0.14350937820474277
Fold 5 IBS: 0.2636493346804202
[I 2024-04-14 00:07:20,966] Trial 85 finished with value: 0.18747605143259577 and parameters: {'l1_ratio': 0.36796576749642906}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16466211065029446
Fold 2 IBS: 0.20425114910411565
Fold 3 IBS: 0.16143144214263527
Fold 4 IBS: 0.14348678834432893
Fold 5 IBS: 0.2636710940298379
[I 2024-04-14 00:07:23,463] Trial 86 finished with value: 0.18750051685424246 and parameters: {'l1_ratio': 0.4448657774461986}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16464550892540886
Fold 2 IBS: 0.20429929129381547
Fold 3 IBS: 0.15995551764480104
Fold 4 IBS: 0.14345547544320975
Fold 5 IBS: 0.26367481226176454
[I 2024-04-14 00:07:25,748] Trial 87 finished with value: 0.18720612111379992 and parameters: {'l1_ratio': 0.48386314519458473}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16464547125588774
Fold 2 IBS: 0.20430225717240674
Fold 3 IBS: 0.16143924487176303
Fold 4 IBS: 0.14346056794033143
Fold 5 IBS: 0.2636795492525734
[I 2024-04-14 00:07:28,043] Trial 88 finished with value: 0.18750541809859247 and parameters: {'l1_ratio': 0.4867537920749354}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.1646513220328518
Fold 2 IBS: 0.20428491626994774
Fold 3 IBS: 0.16141684707518836
Fold 4 IBS: 0.14352677044728826
Fold 5 IBS: 0.26365084460175714
[I 2024-04-14 00:07:30,267] Trial 89 finished with value: 0.18750614008540664 and parameters: {'l1_ratio': 0.4697214296471432}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.1646755489965255
Fold 2 IBS: 0.2042056277190924
Fold 3 IBS: 0.16139165495017355
Fold 4 IBS: 0.14352678332217347
Fold 5 IBS: 0.2636846785180156
[I 2024-04-14 00:07:32,439] Trial 90 finished with value: 0.1874968587011961 and parameters: {'l1_ratio': 0.4177627172281967}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.1646347543350403
Fold 2 IBS: 0.20432848325748157
Fold 3 IBS: 0.16142589130346652
Fold 4 IBS: 0.14350594765519534
Fold 5 IBS: 0.26366014833758306
[I 2024-04-14 00:07:34,475] Trial 91 finished with value: 0.18751104497775334 and parameters: {'l1_ratio': 0.5138747235776259}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16465190420729298
Fold 2 IBS: 0.2043743081847665
Fold 3 IBS: 0.16007291662246215
Fold 4 IBS: 0.14345911677294182
Fold 5 IBS: 0.2636536094990462
[I 2024-04-14 00:07:36,735] Trial 92 finished with value: 0.18724237105730196 and parameters: {'l1_ratio': 0.5499126980713362}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.1646412099025911
Fold 2 IBS: 0.20431064681963743
Fold 3 IBS: 0.16140120603505403
Fold 4 IBS: 0.14347505036579206
Fold 5 IBS: 0.2636930307866841
[I 2024-04-14 00:07:38,863] Trial 93 finished with value: 0.18750422878195172 and parameters: {'l1_ratio': 0.4951368634449346}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16465996622417084
Fold 2 IBS: 0.2042583271659617
Fold 3 IBS: 0.16144115256164465
Fold 4 IBS: 0.14350013537196724
Fold 5 IBS: 0.26368348632321903
[I 2024-04-14 00:07:41,342] Trial 94 finished with value: 0.1875086135293927 and parameters: {'l1_ratio': 0.4519511790826545}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.1646456039924081
Fold 2 IBS: 0.20439241895876473
Fold 3 IBS: 0.1614440293228701
Fold 4 IBS: 0.1434781761565012
Fold 5 IBS: 0.263683100119134
[I 2024-04-14 00:07:43,844] Trial 95 finished with value: 0.18752866570993562 and parameters: {'l1_ratio': 0.5697344009929485}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16465896563651278
Fold 2 IBS: 0.20435585055943747
Fold 3 IBS: 0.15998153540444762
Fold 4 IBS: 0.14342697966880766
Fold 5 IBS: 0.26368543861235544
[I 2024-04-14 00:07:45,632] Trial 96 finished with value: 0.1872217539763122 and parameters: {'l1_ratio': 0.5293598570038976}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16466485527597174
Fold 2 IBS: 0.2041675725820359
Fold 3 IBS: 0.16138060777078023
Fold 4 IBS: 0.1434462626981998
Fold 5 IBS: 0.2636727808324151
[I 2024-04-14 00:07:48,114] Trial 97 finished with value: 0.18746641583188056 and parameters: {'l1_ratio': 0.37926182258465724}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16469464615684082
Fold 2 IBS: 0.2037732753033304
Fold 3 IBS: 0.1613050516162655
Fold 4 IBS: 0.14340106235864356
Fold 5 IBS: 0.2636514840754959
[I 2024-04-14 00:07:50,495] Trial 98 finished with value: 0.18736510390211522 and parameters: {'l1_ratio': 0.15926120393133159}. Best is trial 84 with value: 0.18719677991182077.
Fold 1 IBS: 0.16464758466325313
Fold 2 IBS: 0.2042937620052912
Fold 3 IBS: 0.15993094746435355
Fold 4 IBS: 0.14344623262156408
Fold 5 IBS: 0.2636659884703808
[I 2024-04-14 00:07:52,496] Trial 99 finished with value: 0.18719690304496855 and parameters: {'l1_ratio': 0.4785719931084257}. Best is trial 84 with value: 0.18719677991182077.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.18719677991182077], datetime_start=datetime.datetime(2024, 4, 14, 0, 7, 16, 973321), datetime_complete=datetime.datetime(2024, 4, 14, 0, 7, 18, 830434), params={'l1_ratio': 0.47850235241861494}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.18719677991182077

In [128]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [129]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.187

#### Test

In [130]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [131]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.598

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.47850235241861494)

test_ibs:  0.272

In [132]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [163]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:48:37,261] A new study created in memory with name: no-name-eaa50ade-873f-422a-9a9f-e609614f02a3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:48:40,495] Trial 0 finished with value: 0.7405641982153078 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:48:43,049] Trial 1 finished with value: 0.7382735828654546 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:48:44,781] Trial 2 finished with value: 0.7278620290642067 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:48:45,405] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:48:46,182] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 12:48:48,962] Trial 5 finished with value: 0.7403505026299406 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:48:52,193] Trial 6 finished with value: 0.7138251668112423 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:48:54,022] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 12:49:00,781] Trial 8 finished with value: 0.52018779342723 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:49:04,368] Trial 9 finished with value: 0.7284436929117747 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:04,767] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:49:09,188] Trial 11 finished with value: 0.736903237607463 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 386, 'oob_score': False, 'max_samples': 0.7819966138938776, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17782839593648317, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:14,403] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:49:17,723] Trial 13 finished with value: 0.7397173772911164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20243052390700345, 'warm_start': False}. Best is trial 0 with value: 0.7405641982153078.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7394366197183099
[I 2024-04-14 12:49:18,350] Trial 14 finished with value: 0.752772825324882 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.6445886658470172, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09295212529598271, 'warm_start': True}. Best is trial 14 with value: 0.752772825324882.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7394366197183099
[I 2024-04-14 12:49:18,956] Trial 15 finished with value: 0.7652207475317394 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 79, 'oob_score': True, 'max_samples': 0.7155449435162471, 'max_features': None, 'min_weight_fraction_leaf': 0.10569022702051172, 'warm_start': True}. Best is trial 15 with value: 0.7652207475317394.

Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:49:19,369] Trial 16 finished with value: 0.7452471942033755 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 12, 'oob_score': True, 'max_samples': 0.4475428611563601, 'max_features': None, 'min_weight_fraction_leaf': 0.0888512086404308, 'warm_start': True}. Best is trial 15 with value: 0.7652207475317394.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 12:49:20,728] Trial 17 finished with value: 0.7732336823406651 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 119, 'oob_score': True, 'max_samples': 0.8531582264400189, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14704605185620673, 'warm_start': True}. Best is trial 17 with value: 0.7732336823406651.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 12:49:21,829] Trial 18 finished with value: 0.7778884498863483 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14090990140664925, 'warm_start': True}. Best is trial 18 with value: 0.7778884498863483.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:49:22,825] Trial 19 finished with value: 0.7790756533208592 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.9946585698860816, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15461760227658045, 'warm_start': True}. Best is trial 19 with value: 0.7790756533208592.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:49:24,118] Trial 20 finished with value: 0.7734232939152095 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 150, 'oob_score': True, 'max_samples': 0.9966620943332627, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24858261413121135, 'warm_start': True}. Best is trial 19 with value: 0.7790756533208592.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:49:25,072] Trial 21 finished with value: 0.7761758722192583 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.9639968014439106, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2380584728082943, 'warm_start': True}. Best is trial 19 with value: 0.7790756533208592.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:49:26,310] Trial 22 finished with value: 0.7837998085991071 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.9967775758291733, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3621093585169288, 'warm_start': True}. Best is trial 22 with value: 0.7837998085991071.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:49:28,571] Trial 23 finished with value: 0.7421003621630502 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.8577444001745218, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3806665508463201, 'warm_start': True}. Best is trial 22 with value: 0.7837998085991071.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:49:30,157] Trial 24 finished with value: 0.7392737769835239 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.8596848154877407, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38677688632292884, 'warm_start': True}. Best is trial 22 with value: 0.7837998085991071.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:49:32,079] Trial 25 finished with value: 0.7848431571854013 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 226, 'oob_score': True, 'max_samples': 0.994715714350113, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2814236335866849, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:49:34,008] Trial 26 finished with value: 0.7759993220168504 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.8936567356589131, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28283733920130744, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:49:35,498] Trial 27 finished with value: 0.7458562307076513 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.8185989435270558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36571499946796887, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:49:36,829] Trial 28 finished with value: 0.7402607390546941 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.9977567876774169, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4550469598772978, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7065727699530516
[I 2024-04-14 12:49:37,209] Trial 29 finished with value: 0.7734116592308652 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.9292311817019716, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1984511636411504, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.6082251082251082
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 12:49:37,879] Trial 30 finished with value: 0.699558799921531 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.7117451690731199, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.33709178306632787, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.

Fold 1 C-index: 0.6731601731601732
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 12:49:38,943] Trial 31 finished with value: 0.7772112471870869 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.9924754281584311, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14400488960666644, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7065727699530516
[I 2024-04-14 12:49:39,741] Trial 32 finished with value: 0.7751117221674322 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.9291992556079912, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23329272834713322, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:49:41,013] Trial 33 finished with value: 0.7796419409754858 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.896975660340393, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2756112438107189, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:49:42,129] Trial 34 finished with value: 0.7787493804917549 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 200, 'oob_score': True, 'max_samples': 0.8113202663225462, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26597864268461385, 'warm_start': True}. Best is trial 25 with value: 0.7848431571854013.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:49:43,365] Trial 35 finished with value: 0.7862361941000001 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9440132961126004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3252027655425411, 'warm_start': True}. Best is trial 35 with value: 0.7862361941000001.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:49:44,945] Trial 36 finished with value: 0.7800642695042976 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.8885000169020678, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33544280422913986, 'warm_start': True}. Best is trial 35 with value: 0.7862361941000001.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:49:46,528] Trial 37 finished with value: 0.7401885531356418 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 3, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.8936618761869961, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4116457835923904, 'warm_start': True}. Best is trial 35 with value: 0.7862361941000001.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:49:48,349] Trial 38 finished with value: 0.7749775529346571 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.8261504281131865, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33565038051472634, 'warm_start': True}. Best is trial 35 with value: 0.7862361941000001.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:49:49,972] Trial 39 finished with value: 0.7847863183750623 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.9356016752644559, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3090412930997603, 'warm_start': True}. Best is trial 35 with value: 0.7862361941000001.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:49:51,384] Trial 40 finished with value: 0.7816804380628409 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9381440321491106, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2987604618110606, 'warm_start': True}. Best is trial 35 with value: 0.7862361941000001.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:49:53,047] Trial 41 finished with value: 0.7870702524392956 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9415203168151968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30712180280602136, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:49:54,546] Trial 42 finished with value: 0.7860166940120835 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.9500614504650745, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.31453329775498273, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:49:56,258] Trial 43 finished with value: 0.7816486968132039 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.9388551492979577, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30554262249941894, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:49:58,201] Trial 44 finished with value: 0.7607459577292722 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.7477426491014909, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.31587945712768445, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:58,938] Trial 45 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.37489546541234886, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2889204701984669, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:50:03,912] Trial 46 finished with value: 0.7409535560119445 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.948223287518674, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21805230967447692, 'warm_start': False}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:05,250] Trial 47 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.12577877594208375, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3208337027267393, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:09,665] Trial 48 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.6676611423453302, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3674749901564333, 'warm_start': False}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:11,556] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.7756882736784324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4047153347216424, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:50:12,446] Trial 50 finished with value: 0.7801882294636522 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.8217816383137475, 'max_features': None, 'min_weight_fraction_leaf': 0.2597372311461957, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:50:14,205] Trial 51 finished with value: 0.7852558019431374 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 174, 'oob_score': True, 'max_samples': 0.9584357879002863, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.341549295426824, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:50:15,782] Trial 52 finished with value: 0.7702532116592241 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.8662866074109044, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3519900612572312, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:50:18,771] Trial 53 finished with value: 0.7834876170763609 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.9632955838631115, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3204970693005518, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:50:21,388] Trial 54 finished with value: 0.7780870904821515 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 246, 'oob_score': True, 'max_samples': 0.9133477775619847, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.29010044259256795, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:50:23,730] Trial 55 finished with value: 0.7820951253846326 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.958373284934598, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.31295725690679244, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:31,938] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.5264198294671414, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3436978907101283, 'warm_start': False}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:50:35,223] Trial 57 finished with value: 0.7806298833979531 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.8676575383462692, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2673276348187368, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6971830985915493
[I 2024-04-14 12:50:37,958] Trial 58 finished with value: 0.7794097810196543 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9669637245162913, 'max_features': None, 'min_weight_fraction_leaf': 0.24386657401569847, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6690140845070423
[I 2024-04-14 12:50:39,633] Trial 59 finished with value: 0.7630982174551857 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 14, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9126365565124677, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.39262932627137026, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:45,567] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.24535977099785755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4560551139860314, 'warm_start': False}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8627450980392157

Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:50:47,475] Trial 61 finished with value: 0.7828413354515051 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.9657743171424552, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36376522753397206, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:50:49,011] Trial 62 finished with value: 0.779386226199908 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.9130590070278978, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35277504396413784, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:50:50,688] Trial 63 finished with value: 0.7807263525193218 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.8427427923328927, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3302034437024043, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:50:52,865] Trial 64 finished with value: 0.7798457484908095 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 343, 'oob_score': True, 'max_samples': 0.9765478283863545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2989347094678926, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:50:54,282] Trial 65 finished with value: 0.7716872583285085 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.8764432124492653, 'max_features': None, 'min_weight_fraction_leaf': 0.37610818587138833, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:50:55,934] Trial 66 finished with value: 0.7824397886676997 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 209, 'oob_score': True, 'max_samples': 0.9356599406264843, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2799722410626111, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:50:56,717] Trial 67 finished with value: 0.7775385108661854 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.9961695828105527, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3554363605116643, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:57,367] Trial 68 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.7959080858734018, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.40898485506520693, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:50:58,621] Trial 69 finished with value: 0.7023632354042121 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.9139039572685456, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.43136674911642126, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:50:59,962] Trial 70 finished with value: 0.7768779501622202 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 216, 'oob_score': True, 'max_samples': 0.8373496449523768, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3228220875275828, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:51:02,212] Trial 71 finished with value: 0.7831997926036328 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 312, 'oob_score': True, 'max_samples': 0.9595923179114934, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.31023146905386145, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:51:04,675] Trial 72 finished with value: 0.7803932402147717 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.9746988939329244, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2950480859072579, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:51:06,482] Trial 73 finished with value: 0.7832217116128936 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 287, 'oob_score': True, 'max_samples': 0.999948385639289, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3255581541625629, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:51:09,154] Trial 74 finished with value: 0.7814244273375082 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.9493648324072135, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2536297941175603, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:51:11,385] Trial 75 finished with value: 0.776733297554909 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.8853545612683836, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2738762867283342, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:51:13,288] Trial 76 finished with value: 0.7720061569579939 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 13, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.9281084518159992, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2313459425491231, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:51:14,262] Trial 77 finished with value: 0.7837727523220508 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 272, 'oob_score': False, 'max_samples': 0.9780121298999858, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3427228676979754, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:51:15,317] Trial 78 finished with value: 0.7802934520864214 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.898274404132641, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.34377070969543194, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:51:19,957] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.5973322149672027, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36736536672459286, 'warm_start': False}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:51:21,501] Trial 80 finished with value: 0.7826147202264104 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9753442105849082, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3035263372841941, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:51:22,821] Trial 81 finished with value: 0.7812657500316778 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.9512408499455102, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38650616670843563, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:51:24,060] Trial 82 finished with value: 0.7828874454447982 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.9271052375444822, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32951822154293775, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:51:30,456] Trial 83 finished with value: 0.7813900270800552 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.9733462835348525, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3461324096543467, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:51:33,263] Trial 84 finished with value: 0.7831997926036328 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9436455987737301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3145383964272609, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7183098591549296
[I 2024-04-14 12:51:35,675] Trial 85 finished with value: 0.7767875782300473 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.9999308272404801, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003882628647270736, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:51:36,703] Trial 86 finished with value: 0.7778422442697885 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 190, 'oob_score': False, 'max_samples': 0.8771777763531513, 'max_features': None, 'min_weight_fraction_leaf': 0.28650222618021914, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:51:38,052] Trial 87 finished with value: 0.7718821778456111 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 4, 'n_estimators': 110, 'oob_score': True, 'max_samples': 0.9142681004473315, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37533904151955555, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6737089201877934
[I 2024-04-14 12:51:40,248] Trial 88 finished with value: 0.7675148932812561 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.8562140733738091, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3571280736071557, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:51:42,408] Trial 89 finished with value: 0.7846436904556471 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9809418749185329, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33680236754599374, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:51:44,282] Trial 90 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 253, 'oob_score': True, 'max_samples': 0.7357483446611088, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.40096562965536786, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:51:46,528] Trial 91 finished with value: 0.7846436904556471 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 279, 'oob_score': True, 'max_samples': 0.9837168052000326, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33245341729822436, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:51:49,233] Trial 92 finished with value: 0.7842022435159254 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.9416048433304514, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34323970488731, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:51:51,436] Trial 93 finished with value: 0.7860166940120835 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.9433625900415991, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.31023962005948885, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:51:53,358] Trial 94 finished with value: 0.782370419236918 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.8969420717506874, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3332541253930062, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:51:55,708] Trial 95 finished with value: 0.7798820362437265 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.947580042897835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3033390426065332, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6897321428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:52:00,535] Trial 96 finished with value: 0.7448631880465764 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.9254261201926446, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26711721354998685, 'warm_start': False}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:52:03,039] Trial 97 finished with value: 0.7823125995077846 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.9793964210050383, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.28793664317537404, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:52:05,735] Trial 98 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.384336114718309, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3184167720338122, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8649789029535865

[I 2024-04-14 12:52:08,377] A new study created in memory with name: no-name-926e571c-194c-4554-b561-47758067c8c7

Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:52:08,344] Trial 99 finished with value: 0.7772212896163506 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 256, 'oob_score': True, 'max_samples': 0.9013632682482189, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2773202646962566, 'warm_start': True}. Best is trial 41 with value: 0.7870702524392956.


* Best trial for C-index:
 FrozenTrial(number=41, state=TrialState.COMPLETE, values=[0.7870702524392956], datetime_start=datetime.datetime(2024, 4, 14, 12, 49, 51, 392223), datetime_complete=datetime.datetime(2024, 4, 14, 12, 49, 53, 46506), params={'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9415203168151968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30712180280602136, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=41, value=None)


* Best Score for C-index:
 0.7870702524392956

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17801007706309838
Fold 2 IBS: 0.24702650703752166
Fold 3 IBS: 0.16685441932579215
Fold 4 IBS: 0.1620574810409488
Fold 5 IBS: 0.23708108744534967
[I 2024-04-14 12:52:15,095] Trial 0 finished with value: 0.19820591438254215 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19820591438254215.
Fold 1 IBS: 0.18933081757545508
Fold 2 IBS: 0.21455029716648988
Fold 3 IBS: 0.16626786878862398
Fold 4 IBS: 0.17318932431894588
Fold 5 IBS: 0.22746929432818858
[I 2024-04-14 12:52:16,486] Trial 1 finished with value: 0.1941615204355407 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.1941615204355407.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-14 12:52:17,673] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.1941615204355407.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-14 12:52:22,993] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.1941615204355407.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-14 12:52:28,234] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.1941615204355407.
Fold 1 IBS: 0.18507670446620603
Fold 2 IBS: 0.22007351319884777
Fold 3 IBS: 0.1630802680658528
Fold 4 IBS: 0.15104807066211678
Fold 5 IBS: 0.22924724346814768
[I 2024-04-14 12:52:34,405] Trial 5 finished with value: 0.18970515997223422 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.18970515997223422.
Fold 1 IBS: 0.17894391813579008
Fold 2 IBS: 0.20140980289086294
Fold 3 IBS: 0.16732433271037334
Fold 4 IBS: 0.16809622085927756
Fold 5 IBS: 0.2244987933506356
[I 2024-04-14 12:52:39,151] Trial 6 finished with value: 0.18805461358938788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 6 with value: 0.18805461358938788.
Fold 1 IBS: 0.21152457980295827
Fold 2 IBS: 0.21794717755634715
Fold 3 IBS: 0.20262858075779472
Fold 4 IBS: 0.22015340941350825
Fold 5 IBS: 0.21643355106806592
[I 2024-04-14 12:52:43,795] Trial 7 finished with value: 0.21373745971973487 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 6 with value: 0.18805461358938788.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-14 12:52:50,839] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 6 with value: 0.18805461358938788.
Fold 1 IBS: 0.17718008040664
Fold 2 IBS: 0.21977099747606493
Fold 3 IBS: 0.1697097120556538
Fold 4 IBS: 0.16790887814646668
Fold 5 IBS: 0.22879755592204273
[I 2024-04-14 12:52:52,116] Trial 9 finished with value: 0.19267344480137363 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 6 with value: 0.18805461358938788.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-14 12:52:59,473] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3251129986182119}. Best is trial 6 with value: 0.18805461358938788.
Fold 1 IBS: 0.1776431095617831
Fold 2 IBS: 0.22445642233616642
Fold 3 IBS: 0.158063935951083
Fold 4 IBS: 0.14268316666407482
Fold 5 IBS: 0.2220655660596097
[I 2024-04-14 12:53:03,353] Trial 11 finished with value: 0.18498244011454343 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18831581726271787
Fold 2 IBS: 0.21465588515185158
Fold 3 IBS: 0.17588614875266062
Fold 4 IBS: 0.18539691174165462
Fold 5 IBS: 0.21789991567631672
[I 2024-04-14 12:53:06,237] Trial 12 finished with value: 0.1964309357170403 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9971022097505926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0030119988723624237}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1827876461064478
Fold 2 IBS: 0.20269852046300435
Fold 3 IBS: 0.17244504887512865
Fold 4 IBS: 0.1804984063463392
Fold 5 IBS: 0.21496181908135273
[I 2024-04-14 12:53:08,149] Trial 13 finished with value: 0.19067828817445454 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 177, 'oob_score': False, 'max_samples': 0.8614642794676799, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3325259434945655}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.19039957817096412
Fold 2 IBS: 0.24137065127747162
Fold 3 IBS: 0.16311602318374963
Fold 4 IBS: 0.1490018888228764
Fold 5 IBS: 0.24435214252906934
[I 2024-04-14 12:53:12,626] Trial 14 finished with value: 0.19764805679682623 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.8213409911746509, 'max_features': None, 'min_weight_fraction_leaf': 0.13671430557067935}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1807598432082
Fold 2 IBS: 0.20328799267209963
Fold 3 IBS: 0.17116929842628073
Fold 4 IBS: 0.17542868332103007
Fold 5 IBS: 0.21743353756788114
[I 2024-04-14 12:53:15,508] Trial 15 finished with value: 0.18961587103909833 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 276, 'oob_score': False, 'max_samples': 0.9975584771785205, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3655886525927784}. Best is trial 11 with value: 0.18498244011454343.

Fold 1 IBS: 0.18215160451104828
Fold 2 IBS: 0.2080050046735628
Fold 3 IBS: 0.17018142262332964
Fold 4 IBS: 0.17359285514878095
Fold 5 IBS: 0.2194107292355184
[I 2024-04-14 12:53:17,222] Trial 16 finished with value: 0.190668323238448 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.7722654699481682, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.26709239467760176}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1896128580376995
Fold 2 IBS: 0.24925064923347537
Fold 3 IBS: 0.1618717180718426
Fold 4 IBS: 0.14356550792628214
Fold 5 IBS: 0.2394094299611866
[I 2024-04-14 12:53:22,796] Trial 17 finished with value: 0.19674203264609727 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.8763218642348055, 'max_features': None, 'min_weight_fraction_leaf': 0.0048930076944222935}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.21396900601997718
Fold 2 IBS: 0.22136473465910927
Fold 3 IBS: 0.20478544054543849
Fold 4 IBS: 0.2246328686326041
Fold 5 IBS: 0.21860010415738457
[I 2024-04-14 12:53:26,620] Trial 18 finished with value: 0.21667043080290274 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.9455451604023817, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18780399679410292
Fold 2 IBS: 0.21901769838313725
Fold 3 IBS: 0.1649725893957866
Fold 4 IBS: 0.15239789705572385
Fold 5 IBS: 0.23057185659203025
[I 2024-04-14 12:53:32,018] Trial 19 finished with value: 0.19095280764415618 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.7692459385299205, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10100254960131559}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.21402964338029387
Fold 2 IBS: 0.22061817889261792
Fold 3 IBS: 0.2049550678395892
Fold 4 IBS: 0.22462748866954438
Fold 5 IBS: 0.21773172186764517
[I 2024-04-14 12:53:34,635] Trial 20 finished with value: 0.2163924201299381 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.23419761201309758, 'max_features': None, 'min_weight_fraction_leaf': 0.39117939148195957}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1796872247492733
Fold 2 IBS: 0.20616860961281866
Fold 3 IBS: 0.17042322350413458
Fold 4 IBS: 0.17461962948817067
Fold 5 IBS: 0.21721300752743194
[I 2024-04-14 12:53:37,465] Trial 21 finished with value: 0.18962233897636582 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.9791502851333911, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3484479474427451}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18029398189501258
Fold 2 IBS: 0.20375953080847495
Fold 3 IBS: 0.1715045824675962
Fold 4 IBS: 0.17631366271328222
Fold 5 IBS: 0.21707063209861294
[I 2024-04-14 12:53:39,782] Trial 22 finished with value: 0.18978847799659576 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.9930363485117423, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36920245296163934}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1803736370101638
Fold 2 IBS: 0.2094102324924096
Fold 3 IBS: 0.17017953348141748
Fold 4 IBS: 0.17134317693514323
Fold 5 IBS: 0.22144688250671096
[I 2024-04-14 12:53:41,243] Trial 23 finished with value: 0.190550692485169 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.9091385841865607, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30024960195968337}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.2139954512928879
Fold 2 IBS: 0.22150462431630302
Fold 3 IBS: 0.20480089616082334
Fold 4 IBS: 0.2246485384562975
Fold 5 IBS: 0.21853730360567655
[I 2024-04-14 12:53:43,287] Trial 24 finished with value: 0.21669736276639764 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 218, 'oob_score': False, 'max_samples': 0.8278537399386008, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.43946006278347205}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18554837676124938
Fold 2 IBS: 0.21797643817116127
Fold 3 IBS: 0.16779776426389975
Fold 4 IBS: 0.16661895830183435
Fold 5 IBS: 0.2246116500670551
[I 2024-04-14 12:53:46,751] Trial 25 finished with value: 0.19251063751303996 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.9124244802035567, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22736983224215201}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18654454505434673
Fold 2 IBS: 0.1915954452379428
Fold 3 IBS: 0.17488493758214654
Fold 4 IBS: 0.1856368658936483
Fold 5 IBS: 0.21356084414265833
[I 2024-04-14 12:53:50,451] Trial 26 finished with value: 0.19044452758214853 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.8005095071043449, 'max_features': None, 'min_weight_fraction_leaf': 0.3742291489758166}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1848365633217023
Fold 2 IBS: 0.20133362584764733
Fold 3 IBS: 0.17391605013593617
Fold 4 IBS: 0.18106603424892087
Fold 5 IBS: 0.21488027654072303
[I 2024-04-14 12:53:52,829] Trial 27 finished with value: 0.19120651001898595 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.71884917914564, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28215632694327686}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18493535563076643
Fold 2 IBS: 0.216772097540606
Fold 3 IBS: 0.16792724976319803
Fold 4 IBS: 0.16678132940204235
Fold 5 IBS: 0.22374665579464992
[I 2024-04-14 12:53:55,790] Trial 28 finished with value: 0.19203253762625255 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.9396196492096502, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2402299200925102}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.17638435941428535
Fold 2 IBS: 0.23727707527289926
Fold 3 IBS: 0.16657554486110168
Fold 4 IBS: 0.16105187085838463
Fold 5 IBS: 0.23274613063926453
[I 2024-04-14 12:53:59,216] Trial 29 finished with value: 0.19480699620918712 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 370, 'oob_score': False, 'max_samples': 0.613518726233037, 'max_features': None, 'min_weight_fraction_leaf': 0.20175880045724698}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.19946655056945808
Fold 2 IBS: 0.23769711572887114
Fold 3 IBS: 0.1674890530098315
Fold 4 IBS: 0.1451863106268064
Fold 5 IBS: 0.2317240871709022
[I 2024-04-14 12:54:01,411] Trial 30 finished with value: 0.1963126234211739 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.8613635236549323, 'max_features': None, 'min_weight_fraction_leaf': 0.04136262324149563}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.17974880817335653
Fold 2 IBS: 0.21068888437358538
Fold 3 IBS: 0.16992710436773284
Fold 4 IBS: 0.17172171763305816

Fold 5 IBS: 0.22005380670626368
[I 2024-04-14 12:54:04,184] Trial 31 finished with value: 0.1904280642507993 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 294, 'oob_score': False, 'max_samples': 0.9801990513520231, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3287325033473082}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1798801675037484
Fold 2 IBS: 0.20212655757633474
Fold 3 IBS: 0.17228268183458786
Fold 4 IBS: 0.17709018730697135
Fold 5 IBS: 0.2171759766259116
[I 2024-04-14 12:54:06,750] Trial 32 finished with value: 0.18971111416951078 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.9502203520505428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3560337622605024}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.19901138494030404
Fold 2 IBS: 0.20449130694717588
Fold 3 IBS: 0.18777784123095606
Fold 4 IBS: 0.20193324447571134
Fold 5 IBS: 0.21173369432008635
[I 2024-04-14 12:54:08,931] Trial 33 finished with value: 0.20098949438284675 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 234, 'oob_score': False, 'max_samples': 0.9962549788492522, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.455722516335922}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.21407011030087403
Fold 2 IBS: 0.22207822298246074
Fold 3 IBS: 0.2044432721434932
Fold 4 IBS: 0.22547073036469223
Fold 5 IBS: 0.2190042948234933
[I 2024-04-14 12:54:09,272] Trial 34 finished with value: 0.21701332612300273 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.7331786466845107, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4021755683643018}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18482347040316938
Fold 2 IBS: 0.22014208605560134
Fold 3 IBS: 0.16481180129708184
Fold 4 IBS: 0.15936983319580542
Fold 5 IBS: 0.228769723518687
[I 2024-04-14 12:54:13,317] Trial 35 finished with value: 0.191583382894069 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.8719734005186717, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16538449485881376}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.17893787317502693
Fold 2 IBS: 0.20433733131779871
Fold 3 IBS: 0.1724786977463649
Fold 4 IBS: 0.17870924712178674
Fold 5 IBS: 0.21639048076932307
[I 2024-04-14 12:54:16,870] Trial 36 finished with value: 0.19017072602606006 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.9358622127994423, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.34938265455333617}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.19471041891391033
Fold 2 IBS: 0.2021750283728447
Fold 3 IBS: 0.18351067032855783
Fold 4 IBS: 0.1974896175772066
Fold 5 IBS: 0.21230894865976396
[I 2024-04-14 12:54:19,671] Trial 37 finished with value: 0.1980389367704567 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6799062382275232, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3061039000862159}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.2139662216090729
Fold 2 IBS: 0.22126932880791406
Fold 3 IBS: 0.20490111590763438
Fold 4 IBS: 0.22459761829196093
Fold 5 IBS: 0.21852849321656354
[I 2024-04-14 12:54:24,124] Trial 38 finished with value: 0.21665255556662916 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 387, 'oob_score': True, 'max_samples': 0.4662710037037924, 'max_features': None, 'min_weight_fraction_leaf': 0.42580055151113144}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18285523576545645
Fold 2 IBS: 0.21252228846809218
Fold 3 IBS: 0.16792925637709846
Fold 4 IBS: 0.16869068091182243
Fold 5 IBS: 0.22326057656377865
[I 2024-04-14 12:54:25,557] Trial 39 finished with value: 0.19105160761724965 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.8888942962565618, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2598399548394158}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.20393693372565252
Fold 2 IBS: 0.20923194477702342
Fold 3 IBS: 0.19085874998950325
Fold 4 IBS: 0.20623418107771127
Fold 5 IBS: 0.2130819718896588
[I 2024-04-14 12:54:27,849] Trial 40 finished with value: 0.20466875629190984 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.836988147956236, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3960786437530065}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18594460813553232
Fold 2 IBS: 0.21647063248359408
Fold 3 IBS: 0.1645370779045361
Fold 4 IBS: 0.1547244961074742
Fold 5 IBS: 0.22504215031697827
[I 2024-04-14 12:54:31,667] Trial 41 finished with value: 0.18934379298962298 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.4829258124581028, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.041830021103781534}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18405483127604036
Fold 2 IBS: 0.2118938740765761
Fold 3 IBS: 0.1645421799934745
Fold 4 IBS: 0.15745483862428028
Fold 5 IBS: 0.22117630460096305
[I 2024-04-14 12:54:34,494] Trial 42 finished with value: 0.18782440571426687 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.4648999534728623, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03019568090092398}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18883615819454194
Fold 2 IBS: 0.2103494991854663
Fold 3 IBS: 0.1659948583879011
Fold 4 IBS: 0.16525622661899153
Fold 5 IBS: 0.2219700344497451
[I 2024-04-14 12:54:37,039] Trial 43 finished with value: 0.19048135536732919 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.40148826186526093, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03772345894881278}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.19006130444496086
Fold 2 IBS: 0.2156610541968521
Fold 3 IBS: 0.16637385512983344
Fold 4 IBS: 0.16218725405063322
Fold 5 IBS: 0.22209812413149976
[I 2024-04-14 12:54:38,991] Trial 44 finished with value: 0.19127631839075587 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 189, 'oob_score': False, 'max_samples': 0.4983494479834555, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10767812189339468}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18819139123156936
Fold 2 IBS: 0.2121051758910797
Fold 3 IBS: 0.1653629187533873
Fold 4 IBS: 0.15659587904496144
Fold 5 IBS: 0.22341855716220127
[I 2024-04-14 12:54:42,227] Trial 45 finished with value: 0.1891347844166398 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.38226663755027407, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032567362462471536}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18574371868928008
Fold 2 IBS: 0.2077774882903267
Fold 3 IBS: 0.1705111267987871
Fold 4 IBS: 0.17480219796680896
Fold 5 IBS: 0.21747332374368644
[I 2024-04-14 12:54:45,532] Trial 46 finished with value: 0.19126157109777786 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.3274139443887121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03554352651493527}. Best is trial 11 with value: 0.18498244011454343.

Fold 1 IBS: 0.18550379267172096
Fold 2 IBS: 0.21942995999964232
Fold 3 IBS: 0.16553621749747308
Fold 4 IBS: 0.15227009177089657
Fold 5 IBS: 0.22810092243528043
[I 2024-04-14 12:54:50,482] Trial 47 finished with value: 0.1901681968750027 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 418, 'oob_score': True, 'max_samples': 0.5827826014419875, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06743707678818638}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1890195171243487
Fold 2 IBS: 0.2115470997677741
Fold 3 IBS: 0.16677823033546224
Fold 4 IBS: 0.16290595324316187
Fold 5 IBS: 0.22288495726733487
[I 2024-04-14 12:54:54,849] Trial 48 finished with value: 0.19062715154761634 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 458, 'oob_score': False, 'max_samples': 0.3891906948262243, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.004317698405935787}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18631604219300138
Fold 2 IBS: 0.212244732422416
Fold 3 IBS: 0.16706215212407927
Fold 4 IBS: 0.16704008720050104
Fold 5 IBS: 0.2196334270175497
[I 2024-04-14 12:54:57,933] Trial 49 finished with value: 0.19045928819150948 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.45577549853428934, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09917279887175798}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.2057307979495729
Fold 2 IBS: 0.2073957572273886
Fold 3 IBS: 0.18545557393028006
Fold 4 IBS: 0.19797176282960252
Fold 5 IBS: 0.21363465554625816
[I 2024-04-14 12:54:58,878] Trial 50 finished with value: 0.20203770949662045 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 83, 'oob_score': False, 'max_samples': 0.3258487948494144, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14147922592542847}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18418342516796277
Fold 2 IBS: 0.21398568457576359
Fold 3 IBS: 0.17180685386512737
Fold 4 IBS: 0.16853046456549617
Fold 5 IBS: 0.21796221967170884
[I 2024-04-14 12:55:01,542] Trial 51 finished with value: 0.19129372956921173 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 282, 'oob_score': False, 'max_samples': 0.5339129728689683, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02486008231217142}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.188473072056308
Fold 2 IBS: 0.21213461920995005
Fold 3 IBS: 0.1655313580207494
Fold 4 IBS: 0.1578629604653661
Fold 5 IBS: 0.22401464423156242
[I 2024-04-14 12:55:03,960] Trial 52 finished with value: 0.18960333079678718 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.3755587650574629, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.059621971581715116}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1858710587631692
Fold 2 IBS: 0.2022757390559367
Fold 3 IBS: 0.1702357840214369
Fold 4 IBS: 0.17335065237272326
Fold 5 IBS: 0.2178324179205592
[I 2024-04-14 12:55:06,148] Trial 53 finished with value: 0.18991313042676505 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.2521299984293861, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07686213578570306}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18885163451627218
Fold 2 IBS: 0.2113852170697761
Fold 3 IBS: 0.1667126403392528
Fold 4 IBS: 0.161596343308626
Fold 5 IBS: 0.22022177214213645
[I 2024-04-14 12:55:08,575] Trial 54 finished with value: 0.1897535214752127 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.35869997822197885, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050802472238117985}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.184879533163129
Fold 2 IBS: 0.20611156630518104
Fold 3 IBS: 0.1725077855748233
Fold 4 IBS: 0.1679082825900172
Fold 5 IBS: 0.2167125562747186
[I 2024-04-14 12:55:11,217] Trial 55 finished with value: 0.18962394478157382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.26065411177594827, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023272904912282413}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18726932520579356
Fold 2 IBS: 0.21103097485050146
Fold 3 IBS: 0.1662751916586931
Fold 4 IBS: 0.16339326096967347
Fold 5 IBS: 0.2201805490892411
[I 2024-04-14 12:55:14,535] Trial 56 finished with value: 0.18962986035478052 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 356, 'oob_score': False, 'max_samples': 0.44552130939597795, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09092575815534781}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18856654713758678
Fold 2 IBS: 0.20218914534022803
Fold 3 IBS: 0.17483844008341942
Fold 4 IBS: 0.1843468675051885
Fold 5 IBS: 0.21400983846893604
[I 2024-04-14 12:55:18,498] Trial 57 finished with value: 0.19279016770707175 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 4, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.5011326323539219, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014534729005103757}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18734597602393233
Fold 2 IBS: 0.20704064028646169
Fold 3 IBS: 0.17184608980678043
Fold 4 IBS: 0.17838589841698635
Fold 5 IBS: 0.21502372930201283
[I 2024-04-14 12:55:21,030] Trial 58 finished with value: 0.19192846676723474 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.19628532913441968, 'max_features': None, 'min_weight_fraction_leaf': 0.05746938691599661}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18909443086334854
Fold 2 IBS: 0.20421139540559663
Fold 3 IBS: 0.17300976210881366
Fold 4 IBS: 0.1806873284903129
Fold 5 IBS: 0.21577967984934432
[I 2024-04-14 12:55:23,459] Trial 59 finished with value: 0.19255651934348322 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.371668514573798, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1407531024835348}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1876454210528593
Fold 2 IBS: 0.2096125993552857
Fold 3 IBS: 0.16923492860687686
Fold 4 IBS: 0.1713444771675155
Fold 5 IBS: 0.21892299667361922
[I 2024-04-14 12:55:26,343] Trial 60 finished with value: 0.19135208457123132 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.42110945885484424, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11994014208489068}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18815224875726572
Fold 2 IBS: 0.23598048082706644
Fold 3 IBS: 0.1696005808046372
Fold 4 IBS: 0.16003318115161522
Fold 5 IBS: 0.22417437501725682
[I 2024-04-14 12:55:29,316] Trial 61 finished with value: 0.19558817331156825 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 272, 'oob_score': False, 'max_samples': 0.49025468909720565, 'max_features': None, 'min_weight_fraction_leaf': 0.07402423070809273}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18430014811313047
Fold 2 IBS: 0.21456360724680767
Fold 3 IBS: 0.16346896373246209
Fold 4 IBS: 0.1565640007717709

Fold 5 IBS: 0.22281161806162805
[I 2024-04-14 12:55:32,163] Trial 62 finished with value: 0.18834166758515986 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.5443419407354706, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05508766374457823}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18363533539050453
Fold 2 IBS: 0.21416998096689313
Fold 3 IBS: 0.164866110696086
Fold 4 IBS: 0.15364072515883115
Fold 5 IBS: 0.22209693010700793
[I 2024-04-14 12:55:34,647] Trial 63 finished with value: 0.18768181646386456 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.6213136733560154, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05547383035537368}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1860680402386841
Fold 2 IBS: 0.21636201369626543
Fold 3 IBS: 0.1630664237511174
Fold 4 IBS: 0.15267099938602305
Fold 5 IBS: 0.2225108061072101
[I 2024-04-14 12:55:36,327] Trial 64 finished with value: 0.18813565663586002 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 162, 'oob_score': False, 'max_samples': 0.6368140832595837, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0008491717483775363}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18495241847951527
Fold 2 IBS: 0.21618251107895997
Fold 3 IBS: 0.16287641870996075
Fold 4 IBS: 0.15137924601842853
Fold 5 IBS: 0.2210008699541239
[I 2024-04-14 12:55:37,825] Trial 65 finished with value: 0.1872782928481977 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.6291450123817965, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0005466149819530336}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18665783279307888
Fold 2 IBS: 0.21522571891659223
Fold 3 IBS: 0.1713715476997358
Fold 4 IBS: 0.17224994956097903
Fold 5 IBS: 0.21749261806711218
[I 2024-04-14 12:55:39,354] Trial 66 finished with value: 0.19259953340749963 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.6250759833048096, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00020035353765513603}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1828331293025943
Fold 2 IBS: 0.21733271661689468
Fold 3 IBS: 0.16272290481001114
Fold 4 IBS: 0.15339200001345243
Fold 5 IBS: 0.22209029292298693
[I 2024-04-14 12:55:40,819] Trial 67 finished with value: 0.1876742087331879 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.6414149577595744, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01763469147626975}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1931014127417682
Fold 2 IBS: 0.23911729241011084
Fold 3 IBS: 0.16298591288914419
Fold 4 IBS: 0.1428676122540395
Fold 5 IBS: 0.2383188116122745
[I 2024-04-14 12:55:42,341] Trial 68 finished with value: 0.19527820838146742 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 120, 'oob_score': False, 'max_samples': 0.6957771439549085, 'max_features': None, 'min_weight_fraction_leaf': 0.014456410931185043}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18950570233518776
Fold 2 IBS: 0.21834547458179218
Fold 3 IBS: 0.17545628817103345
Fold 4 IBS: 0.17612604057180492
Fold 5 IBS: 0.22046799962810745
[I 2024-04-14 12:55:43,410] Trial 69 finished with value: 0.19598030105758515 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.6402595576691843, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021393045935948277}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18445847574357374
Fold 2 IBS: 0.2290849004375877
Fold 3 IBS: 0.15828928426299965
Fold 4 IBS: 0.1448209875573666
Fold 5 IBS: 0.23086491954041338
[I 2024-04-14 12:55:45,205] Trial 70 finished with value: 0.1895037135083882 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.5789473544634998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01021575340271326}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18720637653939057
Fold 2 IBS: 0.2169546612831484
Fold 3 IBS: 0.16351811093766713
Fold 4 IBS: 0.15559379643757515
Fold 5 IBS: 0.22407637937466116
[I 2024-04-14 12:55:46,968] Trial 71 finished with value: 0.1894698649144885 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 190, 'oob_score': False, 'max_samples': 0.6529858335628935, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08574331588345063}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18701040681402856
Fold 2 IBS: 0.2135360697373599
Fold 3 IBS: 0.16385436835506695
Fold 4 IBS: 0.1543407611713795
Fold 5 IBS: 0.22140239263600858
[I 2024-04-14 12:55:48,460] Trial 72 finished with value: 0.1880287997427687 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.5328005222160991, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05082124731751805}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18014580068480637
Fold 2 IBS: 0.22087807612721888
Fold 3 IBS: 0.16394361841385885
Fold 4 IBS: 0.14303825789928387
Fold 5 IBS: 0.22557225409968568
[I 2024-04-14 12:55:49,640] Trial 73 finished with value: 0.18671560144497074 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.752659590530161, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0005107312801573255}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18395974223944653
Fold 2 IBS: 0.23506302377708557
Fold 3 IBS: 0.16287739265343937
Fold 4 IBS: 0.148377786606262
Fold 5 IBS: 0.22923303719281254
[I 2024-04-14 12:55:50,471] Trial 74 finished with value: 0.19190219649380919 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.7597462679117017, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02728217350399372}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18415404411870323
Fold 2 IBS: 0.22742895890035336
Fold 3 IBS: 0.1651332499164073
Fold 4 IBS: 0.14589371754586347
Fold 5 IBS: 0.22868040059490924
[I 2024-04-14 12:55:51,855] Trial 75 finished with value: 0.19025807421524732 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 122, 'oob_score': False, 'max_samples': 0.8008754377614388, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.037492963472899224}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1892300716321658
Fold 2 IBS: 0.2402850855580857
Fold 3 IBS: 0.1685347368053093
Fold 4 IBS: 0.1425501486762919
Fold 5 IBS: 0.23709230571100484
[I 2024-04-14 12:55:53,097] Trial 76 finished with value: 0.19553846967657149 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.6070712759060003, 'max_features': None, 'min_weight_fraction_leaf': 0.0484939171277916}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1861264843339361
Fold 2 IBS: 0.21676700277444996
Fold 3 IBS: 0.16870031701401633
Fold 4 IBS: 0.1673369867796002
Fold 5 IBS: 0.22387347651288084
[I 2024-04-14 12:55:54,397] Trial 77 finished with value: 0.1925608534829767 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.7476579626792843, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1648569090893628}. Best is trial 11 with value: 0.18498244011454343.

Fold 1 IBS: 0.18755610055924535
Fold 2 IBS: 0.213667461857247
Fold 3 IBS: 0.16673545659559605
Fold 4 IBS: 0.16836861050203789
Fold 5 IBS: 0.22211605013296412
[I 2024-04-14 12:55:56,527] Trial 78 finished with value: 0.1916887359294181 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.7004531022711529, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1840602311535524}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18688920841087794
Fold 2 IBS: 0.21267348472465292
Fold 3 IBS: 0.16215180077755184
Fold 4 IBS: 0.15379535963668461
Fold 5 IBS: 0.22306656476174708
[I 2024-04-14 12:55:57,659] Trial 79 finished with value: 0.1877152836623029 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.5637611791475481, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07041146248875944}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.19075031480968493
Fold 2 IBS: 0.21809404321891182
Fold 3 IBS: 0.16545204493551682
Fold 4 IBS: 0.16238368369679054
Fold 5 IBS: 0.22632201127248092
[I 2024-04-14 12:55:58,785] Trial 80 finished with value: 0.192600419586677 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.521334760820193, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11294729513201165}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18395638241906248
Fold 2 IBS: 0.21275739398170665
Fold 3 IBS: 0.1634225002170577
Fold 4 IBS: 0.15427794489424565
Fold 5 IBS: 0.21954267467686703
[I 2024-04-14 12:56:00,270] Trial 81 finished with value: 0.1867913792377879 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.5708322779877213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019485356507173947}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18534146501298487
Fold 2 IBS: 0.2092368456524862
Fold 3 IBS: 0.1635601740471881
Fold 4 IBS: 0.15580809369146376
Fold 5 IBS: 0.222394357443769
[I 2024-04-14 12:56:01,773] Trial 82 finished with value: 0.18726818716957838 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.5648336757485385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06776810086412506}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1864418979505011
Fold 2 IBS: 0.21145538901971403
Fold 3 IBS: 0.16395706142805702
Fold 4 IBS: 0.15435283449086473
Fold 5 IBS: 0.22933764860611053
[I 2024-04-14 12:56:02,417] Trial 83 finished with value: 0.18910896629904944 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 51, 'oob_score': False, 'max_samples': 0.5800688842526741, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06479980840036557}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18577532701411661
Fold 2 IBS: 0.21042976607527247
Fold 3 IBS: 0.1719752698131818
Fold 4 IBS: 0.17365673061387454
Fold 5 IBS: 0.2150400639236767
[I 2024-04-14 12:56:03,851] Trial 84 finished with value: 0.19137543148802444 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.5997692056693714, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.014505837929176608}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1845225006206427
Fold 2 IBS: 0.21383635326100994
Fold 3 IBS: 0.16132905278010082
Fold 4 IBS: 0.15171204976673702
Fold 5 IBS: 0.22045789825678833
[I 2024-04-14 12:56:04,962] Trial 85 finished with value: 0.18637157093705575 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.5587785757159852, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028598463474199406}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18687667393007515
Fold 2 IBS: 0.21209002234080523
Fold 3 IBS: 0.16435294701003927
Fold 4 IBS: 0.1509303604573547
Fold 5 IBS: 0.23209242325925417
[I 2024-04-14 12:56:05,740] Trial 86 finished with value: 0.18926848539950572 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 66, 'oob_score': False, 'max_samples': 0.6680779077245744, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0802231237879626}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18902905568076725
Fold 2 IBS: 0.21876279867417267
Fold 3 IBS: 0.1633276407806532
Fold 4 IBS: 0.15352151194824754
Fold 5 IBS: 0.21899295092915122
[I 2024-04-14 12:56:07,252] Trial 87 finished with value: 0.1887267916025984 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.5569193762246847, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.018907771103614922}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18366276171006501
Fold 2 IBS: 0.2160730388191014
Fold 3 IBS: 0.17041979622592487
Fold 4 IBS: 0.16840505623975435
Fold 5 IBS: 0.2191624775445691
[I 2024-04-14 12:56:08,961] Trial 88 finished with value: 0.19154462610788295 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 176, 'oob_score': False, 'max_samples': 0.5707906644898473, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12484505256331452}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18707890419983247
Fold 2 IBS: 0.2160749162667919
Fold 3 IBS: 0.16371398141958368
Fold 4 IBS: 0.15222416705348865
Fold 5 IBS: 0.22542896952357483
[I 2024-04-14 12:56:10,512] Trial 89 finished with value: 0.18890418769265432 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.596234690722856, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0692234334984962}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18337510503922438
Fold 2 IBS: 0.21961162554356878
Fold 3 IBS: 0.1645469299031179
Fold 4 IBS: 0.1468671465097425
Fold 5 IBS: 0.22616252092522407
[I 2024-04-14 12:56:12,212] Trial 90 finished with value: 0.18811266558417553 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.6811808829460995, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04560304073127637}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18682327379532493
Fold 2 IBS: 0.21410148440499338
Fold 3 IBS: 0.16183951265601573
Fold 4 IBS: 0.15001492149895923
Fold 5 IBS: 0.2214934535541553
[I 2024-04-14 12:56:13,551] Trial 91 finished with value: 0.18685452918188972 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.5496083410748811, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03410202304931616}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1864033847158399
Fold 2 IBS: 0.21258641053252883
Fold 3 IBS: 0.16025998215598017
Fold 4 IBS: 0.1509117086527614
Fold 5 IBS: 0.22165961073946594
[I 2024-04-14 12:56:14,732] Trial 92 finished with value: 0.18636421935931524 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 96, 'oob_score': False, 'max_samples': 0.555984991333635, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03291413020039802}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18766553172007336
Fold 2 IBS: 0.2171363559381044
Fold 3 IBS: 0.16425351655347464
Fold 4 IBS: 0.1460611773883444

Fold 5 IBS: 0.23505030209245742
[I 2024-04-14 12:56:15,625] Trial 93 finished with value: 0.19003337673849088 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 67, 'oob_score': False, 'max_samples': 0.6206641744799919, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.033188309865125526}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18730646376000343
Fold 2 IBS: 0.20758047942586721
Fold 3 IBS: 0.1722304326118517
Fold 4 IBS: 0.17236254605622933
Fold 5 IBS: 0.22175559456656074
[I 2024-04-14 12:56:16,167] Trial 94 finished with value: 0.1922471032841025 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 38, 'oob_score': False, 'max_samples': 0.5052122145733884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009395619419171504}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18680985415580556
Fold 2 IBS: 0.22003034533065385
Fold 3 IBS: 0.16289239668798242
Fold 4 IBS: 0.15177692158936293
Fold 5 IBS: 0.22470081968167965
[I 2024-04-14 12:56:17,266] Trial 95 finished with value: 0.1892420674890969 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 112, 'oob_score': False, 'max_samples': 0.6511964163900639, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025612468339343383}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.1870049186623291
Fold 2 IBS: 0.21873083543820065
Fold 3 IBS: 0.16157175425900122
Fold 4 IBS: 0.1470364498411416
Fold 5 IBS: 0.2300765796607362
[I 2024-04-14 12:56:18,330] Trial 96 finished with value: 0.18888410757228175 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.5163113155673729, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04179869871694232}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18963619838725607
Fold 2 IBS: 0.21573095419748695
Fold 3 IBS: 0.16183219583870723
Fold 4 IBS: 0.15912427847937546
Fold 5 IBS: 0.22609064755833122
[I 2024-04-14 12:56:19,342] Trial 97 finished with value: 0.19048285489223138 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 90, 'oob_score': False, 'max_samples': 0.5524868211403451, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09429458300549397}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18288524347059168
Fold 2 IBS: 0.21912191304165698
Fold 3 IBS: 0.16322271163952887
Fold 4 IBS: 0.155084108886297
Fold 5 IBS: 0.22217905888424933
[I 2024-04-14 12:56:21,090] Trial 98 finished with value: 0.18849860718446476 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.7168057557876314, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009975268179451033}. Best is trial 11 with value: 0.18498244011454343.
Fold 1 IBS: 0.18797449251280968
Fold 2 IBS: 0.21194515251455207
Fold 3 IBS: 0.17422207605318807
Fold 4 IBS: 0.17595356868001397
Fold 5 IBS: 0.21665942653668194
[I 2024-04-14 12:56:21,970] Trial 99 finished with value: 0.19335094325944915 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.5966424924694992, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0008624120915829564}. Best is trial 11 with value: 0.18498244011454343.


* Best trial for IBS:
 FrozenTrial(number=11, state=TrialState.COMPLETE, values=[0.18498244011454343], datetime_start=datetime.datetime(2024, 4, 14, 12, 52, 59, 479911), datetime_complete=datetime.datetime(2024, 4, 14, 12, 53, 3, 352266), params={'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=11, value=None)


* Best Score for IBS:
 0.18498244011454343

In [164]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [165]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.787
train_ibs:  0.185

#### Test

In [166]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [167]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=12, max_features='auto', max_leaf_nodes=11,
                     max_samples=0.9415203168151968, min_samples_leaf=19,
                     min_samples_split=17,
                     min_weight_fraction_leaf=0.30712180280602136,
                     n_estimators=274, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.708

RandomSurvivalForest(max_depth=3, max_features='log2', max_leaf_nodes=18,
                     max_samples=0.9878564362760905, min_samples_leaf=1,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.008231293935378081,
                     n_estimators=287, random_state=123)

test_ibs:  0.208

In [168]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [169]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:56:23,457] A new study created in memory with name: no-name-3918d267-e299-41fc-ae19-95ba46855fec

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:56:24,427] Trial 0 finished with value: 0.7787743763285959 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:56:26,564] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:56:31,918] Trial 2 finished with value: 0.7499334338631805 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:56:32,359] Trial 3 finished with value: 0.768500520173547 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:56:34,035] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:56:36,141] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:56:37,248] Trial 6 finished with value: 0.7744973958805066 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:56:39,560] Trial 7 finished with value: 0.7548536256347627 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.8357843137254902
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:56:39,733] Trial 8 finished with value: 0.7696338820338261 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:56:44,746] Trial 9 finished with value: 0.7542574565604779 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:56:46,483] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:56:47,397] Trial 11 finished with value: 0.7673165914812414 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7787743763285959.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:56:48,823] Trial 12 finished with value: 0.7814432639860918 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:56:50,027] Trial 13 finished with value: 0.7656808431366193 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:56:51,065] Trial 14 finished with value: 0.7671137814840032 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:56:51,747] Trial 15 finished with value: 0.7668972191868693 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7814432639860918.

Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:56:52,957] Trial 16 finished with value: 0.7756419137412984 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:56:53,840] Trial 17 finished with value: 0.7646900847933786 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:56:55,181] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:56:56,107] Trial 19 finished with value: 0.7685248008221264 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 12:56:56,257] Trial 20 finished with value: 0.759486772674677 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:56:57,431] Trial 21 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.880411609136682, 'min_weight_fraction_leaf': 0.4858190779814263}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:56:58,514] Trial 22 finished with value: 0.7717582936471239 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8896430644020052, 'min_weight_fraction_leaf': 0.3852211875166954}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:56:59,558] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 402, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8095024948236286, 'min_weight_fraction_leaf': 0.45555823295366793}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:00,653] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7397932899671588, 'min_weight_fraction_leaf': 0.3984329214033346}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:57:01,523] Trial 25 finished with value: 0.7664698443316775 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 349, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9128448809634693, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:57:07,268] Trial 26 finished with value: 0.7429743667674041 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 497, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6539680943502474, 'min_weight_fraction_leaf': 0.029672959118918006}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:57:07,969] Trial 27 finished with value: 0.7766545923706685 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8435977690846584, 'min_weight_fraction_leaf': 0.4126502647568297}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:57:08,734] Trial 28 finished with value: 0.759846122499795 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.94126425282106, 'min_weight_fraction_leaf': 0.28691956257494355}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:57:09,841] Trial 29 finished with value: 0.7713959216160248 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 218, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4766061840882204, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:57:10,430] Trial 30 finished with value: 0.7702370330253367 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.09023089007695154}. Best is trial 12 with value: 0.7814432639860918.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:11,438] Trial 31 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.72769080216046, 'min_weight_fraction_leaf': 0.41272796590787575}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:57:12,176] Trial 32 finished with value: 0.7708654365042669 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8366845330876531, 'min_weight_fraction_leaf': 0.34784904798797006}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:57:13,302] Trial 33 finished with value: 0.7778913822859084 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9301489258006082, 'min_weight_fraction_leaf': 0.43289300269949504}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:57:14,419] Trial 34 finished with value: 0.7761597805543066 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9398413706723989, 'min_weight_fraction_leaf': 0.4343046990677687}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:17,610] Trial 35 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 353, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.621194216223224, 'min_weight_fraction_leaf': 0.4952101145012534}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:57:18,767] Trial 36 finished with value: 0.7783289676913896 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7566543169432488, 'min_weight_fraction_leaf': 0.3625767446532363}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:57:19,934] Trial 37 finished with value: 0.7783289676913896 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7360655051020905, 'min_weight_fraction_leaf': 0.3563561730502426}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:24,735] Trial 38 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.3738459674812765}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:25,746] Trial 39 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 417, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5264266369076203, 'min_weight_fraction_leaf': 0.29691465386433785}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:57:26,998] Trial 40 finished with value: 0.767076974187461 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6158156118114211, 'min_weight_fraction_leaf': 0.039419418548500465}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:57:28,260] Trial 41 finished with value: 0.7769109901290456 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7620488800258761, 'min_weight_fraction_leaf': 0.35704315415860516}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 12:57:29,876] Trial 42 finished with value: 0.7729992417557309 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7054469991615693, 'min_weight_fraction_leaf': 0.3059552343037062}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:31,202] Trial 43 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.4479880985297759}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:57:32,409] Trial 44 finished with value: 0.760139943998475 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9986794798353059, 'min_weight_fraction_leaf': 0.2667983839112549}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:57:33,728] Trial 45 finished with value: 0.7736315950147057 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5998350649536632, 'min_weight_fraction_leaf': 0.0038012551219620827}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8037974683544303

Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:57:39,172] Trial 46 finished with value: 0.7420446645894455 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 436, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9211093225260556, 'min_weight_fraction_leaf': 0.11885042035043525}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:57:40,196] Trial 47 finished with value: 0.7653969163760741 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 365, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7741866602866047, 'min_weight_fraction_leaf': 0.1625947698183845}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:57:41,409] Trial 48 finished with value: 0.767969831330318 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9511515257322404, 'min_weight_fraction_leaf': 0.323189732513714}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:42,388] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8342146852588146, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:42,756] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 131, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.3710121613591568}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 12:57:43,955] Trial 51 finished with value: 0.7755200688437581 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7519201793926822, 'min_weight_fraction_leaf': 0.33908633101213104}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:45,037] Trial 52 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 454, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6939735816947525, 'min_weight_fraction_leaf': 0.36705688887043514}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:57:46,302] Trial 53 finished with value: 0.7719120900519887 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 480, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6438951245849898, 'min_weight_fraction_leaf': 0.05356594422715742}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:57:47,471] Trial 54 finished with value: 0.7681943961882716 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7739652051283161, 'min_weight_fraction_leaf': 0.2664306077093404}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:48,491] Trial 55 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5781784707288, 'min_weight_fraction_leaf': 0.3580676250623995}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:49,718] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6512965318821388, 'min_weight_fraction_leaf': 0.4768847641109783}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6596244131455399
[I 2024-04-14 12:57:53,642] Trial 57 finished with value: 0.7560892808394855 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 332, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9692935256546863, 'min_weight_fraction_leaf': 0.31630763777804893}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:57:54,785] Trial 58 finished with value: 0.771685353524382 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8667645982363676, 'min_weight_fraction_leaf': 0.38989033611364154}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:57:56,029] Trial 59 finished with value: 0.7787646925575203 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8083186611240062, 'min_weight_fraction_leaf': 0.02005389901726501}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:57:57,101] Trial 60 finished with value: 0.7759668448653064 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9032704467477163, 'min_weight_fraction_leaf': 0.014842401729451352}. Best is trial 12 with value: 0.7814432639860918.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:57:58,305] Trial 61 finished with value: 0.782091838015616 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7257016512849445, 'min_weight_fraction_leaf': 0.062379614657593535}. Best is trial 61 with value: 0.782091838015616.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:57:59,574] Trial 62 finished with value: 0.7869694687790998 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228469890997942, 'min_weight_fraction_leaf': 0.027494235560794347}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:00,896] Trial 63 finished with value: 0.7758988158627524 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 487, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.806009878329206, 'min_weight_fraction_leaf': 0.07612547105086738}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:02,045] Trial 64 finished with value: 0.7868819337650942 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 441, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.713038949125605, 'min_weight_fraction_leaf': 0.022272602173385614}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:03,275] Trial 65 finished with value: 0.785259786056759 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 487, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6778536045937293, 'min_weight_fraction_leaf': 0.025648352583914895}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:04,452] Trial 66 finished with value: 0.785259786056759 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 486, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6730561270194201, 'min_weight_fraction_leaf': 0.03149493700066888}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:58:05,885] Trial 67 finished with value: 0.7833357417911653 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6738321310708877, 'min_weight_fraction_leaf': 0.05238025128920368}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:58:07,043] Trial 68 finished with value: 0.7842747089273155 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 441, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6703629041356399, 'min_weight_fraction_leaf': 0.046511332975292155}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:58:08,128] Trial 69 finished with value: 0.7852136760634658 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 443, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6707216296902905, 'min_weight_fraction_leaf': 0.05349890730460912}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:58:10,392] Trial 70 finished with value: 0.7824428846483082 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6823364827927276, 'min_weight_fraction_leaf': 0.04690975154319159}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:58:12,611] Trial 71 finished with value: 0.7824428846483082 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 444, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6843503861854034, 'min_weight_fraction_leaf': 0.045380480106732075}. Best is trial 62 with value: 0.7869694687790998.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:14,948] Trial 72 finished with value: 0.7888449900535912 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 441, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6609264157532758, 'min_weight_fraction_leaf': 0.02660756763708747}. Best is trial 72 with value: 0.7888449900535912.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 12:58:17,078] Trial 73 finished with value: 0.7925961736256115 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 403, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.02701709888426442}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:58:19,230] Trial 74 finished with value: 0.7813791881685656 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 410, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5762811196680634, 'min_weight_fraction_leaf': 0.02757820542539685}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:21,343] Trial 75 finished with value: 0.7742985871636779 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 391, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6272463118775813, 'min_weight_fraction_leaf': 0.07851392205182675}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:26,523] Trial 76 finished with value: 0.7460849834106968 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 426, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7067159927289913, 'min_weight_fraction_leaf': 0.10969081431732125}. Best is trial 73 with value: 0.7925961736256115.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:58:28,926] Trial 77 finished with value: 0.7848475288995644 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5978024026349597, 'min_weight_fraction_leaf': 0.03063395697352311}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:32,050] Trial 78 finished with value: 0.7838866427541535 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5980986566216576, 'min_weight_fraction_leaf': 0.029542421106654577}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:58:34,552] Trial 79 finished with value: 0.7861785153939046 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5486608089279829, 'min_weight_fraction_leaf': 0.00033162417021381785}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:58:35,029] Trial 80 finished with value: 0.7718491323456885 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 54, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5502376105048146, 'min_weight_fraction_leaf': 0.09320610726136773}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:58:36,485] Trial 81 finished with value: 0.7862135742317802 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 455, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5142822895790823, 'min_weight_fraction_leaf': 0.01330770736648687}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:58:37,289] Trial 82 finished with value: 0.7885400534141922 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 241, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5079992975344458, 'min_weight_fraction_leaf': 0.001196219546186289}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:58:38,161] Trial 83 finished with value: 0.784855079165169 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 235, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4499919256607343, 'min_weight_fraction_leaf': 0.00957224094953179}. Best is trial 73 with value: 0.7925961736256115.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:38,744] Trial 84 finished with value: 0.7928810134890437 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 161, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5008972872516362, 'min_weight_fraction_leaf': 0.00018833809088633245}. Best is trial 84 with value: 0.7928810134890437.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:58:39,353] Trial 85 finished with value: 0.7931368000530088 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 177, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4838169252356709, 'min_weight_fraction_leaf': 0.004647194711942176}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:39,972] Trial 86 finished with value: 0.7920279001566428 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 172, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.40589341337482365, 'min_weight_fraction_leaf': 0.0009869137403309193}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:40,597] Trial 87 finished with value: 0.7872840891895746 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 162, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.39088821419783343, 'min_weight_fraction_leaf': 0.015863259250876956}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:41,884] Trial 88 finished with value: 0.7548114688264972 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 172, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.42859006066483346, 'min_weight_fraction_leaf': 0.014888568764553262}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:42,512] Trial 89 finished with value: 0.7848888148834795 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 164, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.362508661108379, 'min_weight_fraction_leaf': 0.0008685918957534455}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:43,003] Trial 90 finished with value: 0.7657139689373861 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.33533817865445426, 'min_weight_fraction_leaf': 0.06862392911932823}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:58:43,622] Trial 91 finished with value: 0.7819355422115037 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.47084522157488384, 'min_weight_fraction_leaf': 0.016759726307007696}. Best is trial 85 with value: 0.7931368000530088.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8504901960784313
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:44,148] Trial 92 finished with value: 0.7820650078861672 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 138, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5044719233071477, 'min_weight_fraction_leaf': 0.03930241520040703}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.8553921568627451
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:44,511] Trial 93 finished with value: 0.7833184397967035 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3908167286174801, 'min_weight_fraction_leaf': 0.014825167480761998}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6737089201877934
[I 2024-04-14 12:58:45,243] Trial 94 finished with value: 0.7749891142699968 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.2780918596516202, 'min_weight_fraction_leaf': 0.03884426084169305}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:45,934] Trial 95 finished with value: 0.7892566564462703 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 191, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5041444934872338, 'min_weight_fraction_leaf': 0.007215005540802878}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8553921568627451
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:58:46,766] Trial 96 finished with value: 0.7720099892661322 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 234, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.45196361472436125, 'min_weight_fraction_leaf': 0.06634080669702952}. Best is trial 85 with value: 0.7931368000530088.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 12:58:47,476] Trial 97 finished with value: 0.7975982204742705 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 192, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4107674575173371, 'min_weight_fraction_leaf': 0.005571403264584145}. Best is trial 97 with value: 0.7975982204742705.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:48,164] Trial 98 finished with value: 0.79656416805851 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 187, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4120733267576636, 'min_weight_fraction_leaf': 0.0007570876208337516}. Best is trial 97 with value: 0.7975982204742705.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8676470588235294

[I 2024-04-14 12:58:48,972] A new study created in memory with name: no-name-352ccad5-2dfd-4184-8370-c955929b5c65

Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:58:48,965] Trial 99 finished with value: 0.7928515442141784 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 192, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4059258234959344, 'min_weight_fraction_leaf': 0.004096956817464835}. Best is trial 97 with value: 0.7975982204742705.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.7975982204742705], datetime_start=datetime.datetime(2024, 4, 14, 12, 58, 46, 769261), datetime_complete=datetime.datetime(2024, 4, 14, 12, 58, 47, 476389), params={'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 192, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4107674575173371, 'min_weight_fraction_leaf': 0.005571403264584145}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=97, value=None)


* Best Score for C-index:
 0.7975982204742705

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16934136618698026
Fold 2 IBS: 0.21907328411915208
Fold 3 IBS: 0.1626813163108608
Fold 4 IBS: 0.1580380550118908
Fold 5 IBS: 0.23347702540793708
[I 2024-04-14 12:58:51,308] Trial 0 finished with value: 0.1885222094073642 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.1885222094073642.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 12:58:54,539] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.1885222094073642.
Fold 1 IBS: 0.18694501980721975
Fold 2 IBS: 0.21087471112059328
Fold 3 IBS: 0.18120806903812425
Fold 4 IBS: 0.18937462779975614
Fold 5 IBS: 0.2163088880023713
[I 2024-04-14 12:58:57,464] Trial 2 finished with value: 0.19694226315361293 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.1885222094073642.
Fold 1 IBS: 0.1866845962776733
Fold 2 IBS: 0.20925924675074875
Fold 3 IBS: 0.17923190777286485
Fold 4 IBS: 0.189845815723595
Fold 5 IBS: 0.2175503848449372
[I 2024-04-14 12:58:58,427] Trial 3 finished with value: 0.1965143902739638 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.1885222094073642.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 12:59:01,008] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.1885222094073642.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 12:59:02,137] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.1885222094073642.
Fold 1 IBS: 0.17004575064677332
Fold 2 IBS: 0.21580652766088734
Fold 3 IBS: 0.16339702016952762
Fold 4 IBS: 0.15806498082828052
Fold 5 IBS: 0.23267408828629588
[I 2024-04-14 12:59:04,716] Trial 6 finished with value: 0.18799767351835292 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.18799767351835292.
Fold 1 IBS: 0.17497327303330132
Fold 2 IBS: 0.2056171953232327
Fold 3 IBS: 0.17043971353425558
Fold 4 IBS: 0.17254274000250394
Fold 5 IBS: 0.21940450702390055
[I 2024-04-14 12:59:06,378] Trial 7 finished with value: 0.18859548578343882 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.18799767351835292.
Fold 1 IBS: 0.19313521780445328
Fold 2 IBS: 0.21013142538702784
Fold 3 IBS: 0.18066042889263706
Fold 4 IBS: 0.1926981694530255
Fold 5 IBS: 0.21774519253934846
[I 2024-04-14 12:59:06,760] Trial 8 finished with value: 0.19887408681529842 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.18799767351835292.
Fold 1 IBS: 0.19548755637453058
Fold 2 IBS: 0.21146170127316247
Fold 3 IBS: 0.18865046446712105
Fold 4 IBS: 0.20545929311873617
Fold 5 IBS: 0.21585588279223925
[I 2024-04-14 12:59:10,350] Trial 9 finished with value: 0.20338297960515792 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.18799767351835292.
Fold 1 IBS: 0.21397612241164576
Fold 2 IBS: 0.2207394210478338
Fold 3 IBS: 0.20537940251283027
Fold 4 IBS: 0.22474853253260105
Fold 5 IBS: 0.2174222289467434
[I 2024-04-14 12:59:13,188] Trial 10 finished with value: 0.21645314149033087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.18799767351835292.
Fold 1 IBS: 0.1956256251173504
Fold 2 IBS: 0.20958803865270828
Fold 3 IBS: 0.18859720030986
Fold 4 IBS: 0.207639898785505
Fold 5 IBS: 0.2145167936957468
[I 2024-04-14 12:59:15,330] Trial 11 finished with value: 0.20319351131223412 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.18799767351835292.
Fold 1 IBS: 0.16616903441159217
Fold 2 IBS: 0.22437347519803458
Fold 3 IBS: 0.16023805437139926
Fold 4 IBS: 0.15180960792408862
Fold 5 IBS: 0.2352620930353275
[I 2024-04-14 12:59:18,664] Trial 12 finished with value: 0.18757045298808844 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18757045298808844.
Fold 1 IBS: 0.17000003113591047
Fold 2 IBS: 0.21764757620121283
Fold 3 IBS: 0.16744235939505028
Fold 4 IBS: 0.16523242813372893
Fold 5 IBS: 0.2284166634296367
[I 2024-04-14 12:59:21,752] Trial 13 finished with value: 0.18974781165910787 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.18757045298808844.
Fold 1 IBS: 0.2139646814364898
Fold 2 IBS: 0.22074056096749928
Fold 3 IBS: 0.20501656315227804
Fold 4 IBS: 0.22494601314735585
Fold 5 IBS: 0.21705148409657263
[I 2024-04-14 12:59:24,502] Trial 14 finished with value: 0.21634386056003913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.18757045298808844.

Fold 1 IBS: 0.21400643269593325
Fold 2 IBS: 0.22111219981278188
Fold 3 IBS: 0.20502803908063474
Fold 4 IBS: 0.22484462106669664
Fold 5 IBS: 0.21822466700224044
[I 2024-04-14 12:59:26,184] Trial 15 finished with value: 0.21664319193165743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.18757045298808844.
Fold 1 IBS: 0.17181998430496237
Fold 2 IBS: 0.21126314670293095
Fold 3 IBS: 0.17026641118499533
Fold 4 IBS: 0.17021219047707836
Fold 5 IBS: 0.223608273593242
[I 2024-04-14 12:59:29,762] Trial 16 finished with value: 0.18943400125264181 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.18757045298808844.
Fold 1 IBS: 0.17458759318425687
Fold 2 IBS: 0.2098778386775778
Fold 3 IBS: 0.1676106242202489
Fold 4 IBS: 0.16711186374391745
Fold 5 IBS: 0.22613019983389468
[I 2024-04-14 12:59:32,772] Trial 17 finished with value: 0.18906362393197912 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.18757045298808844.
Fold 1 IBS: 0.17057571630859214
Fold 2 IBS: 0.19848007749455726
Fold 3 IBS: 0.17202708963027058
Fold 4 IBS: 0.17197618535979886
Fold 5 IBS: 0.21656815238207547
[I 2024-04-14 12:59:33,123] Trial 18 finished with value: 0.18592544423505888 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.19529424354309308
Fold 2 IBS: 0.19822378590785053
Fold 3 IBS: 0.17654589763440068
Fold 4 IBS: 0.19598547478025136
Fold 5 IBS: 0.21948585025319733
[I 2024-04-14 12:59:33,402] Trial 19 finished with value: 0.1971070504237586 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 11, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.34104237757007294, 'min_weight_fraction_leaf': 0.07656656299673237}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.2139495915232692
Fold 2 IBS: 0.22066932397884073
Fold 3 IBS: 0.20470202679364338
Fold 4 IBS: 0.22465730727709501
Fold 5 IBS: 0.21835854216171097
[I 2024-04-14 12:59:34,617] Trial 20 finished with value: 0.21646735834691183 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 107, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.260577294057957, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.17663529230890174
Fold 2 IBS: 0.20438087573194738
Fold 3 IBS: 0.17261041512097114
Fold 4 IBS: 0.18354055112359274
Fold 5 IBS: 0.2170148628426929
[I 2024-04-14 12:59:36,259] Trial 21 finished with value: 0.1908363994256212 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 182, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.476824756466839, 'min_weight_fraction_leaf': 0.022958663817377156}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.17149459574673181
Fold 2 IBS: 0.21606455530930976
Fold 3 IBS: 0.16889745237623602
Fold 4 IBS: 0.16723415801887523
Fold 5 IBS: 0.22798738067885238
[I 2024-04-14 12:59:39,036] Trial 22 finished with value: 0.19033562842600102 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 307, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6062808897551145, 'min_weight_fraction_leaf': 0.08709752671032596}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.16832852245209795
Fold 2 IBS: 0.21881080687084112
Fold 3 IBS: 0.16206919586410048
Fold 4 IBS: 0.1559487505200731
Fold 5 IBS: 0.23197705655720785
[I 2024-04-14 12:59:42,873] Trial 23 finished with value: 0.18742686645286408 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 447, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.43233870739572433, 'min_weight_fraction_leaf': 0.04814654754133644}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.1729665237437015
Fold 2 IBS: 0.20691872179727372
Fold 3 IBS: 0.16844464622625507
Fold 4 IBS: 0.17086946880942885
Fold 5 IBS: 0.21829366713206766
[I 2024-04-14 12:59:43,913] Trial 24 finished with value: 0.18749860554174538 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 97, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.41304861180490127, 'min_weight_fraction_leaf': 0.11645452898547606}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.19704424624982855
Fold 2 IBS: 0.2130762969118197
Fold 3 IBS: 0.18829023815255203
Fold 4 IBS: 0.20052188544146293
Fold 5 IBS: 0.21578299812478097
[I 2024-04-14 12:59:44,720] Trial 25 finished with value: 0.20294313297608885 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 76, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.4049817627517634, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.21452255875236032
Fold 2 IBS: 0.221298648647994
Fold 3 IBS: 0.20550433263071297
Fold 4 IBS: 0.22715560995764233
Fold 5 IBS: 0.2237380588445429
[I 2024-04-14 12:59:44,972] Trial 26 finished with value: 0.2184438417666505 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 9, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.25960788192883616, 'min_weight_fraction_leaf': 0.09666572299489368}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.1743478983599966
Fold 2 IBS: 0.20331783808775453
Fold 3 IBS: 0.16960836548655137
Fold 4 IBS: 0.17480959495628945
Fold 5 IBS: 0.21677312901387336
[I 2024-04-14 12:59:46,049] Trial 27 finished with value: 0.18777136518089305 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 114, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4037750861728433, 'min_weight_fraction_leaf': 0.04691681556780837}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.21389107125387527
Fold 2 IBS: 0.22069520012117508
Fold 3 IBS: 0.20460105522687297
Fold 4 IBS: 0.2247080762413135
Fold 5 IBS: 0.21850378709602827
[I 2024-04-14 12:59:46,819] Trial 28 finished with value: 0.21647983798785303 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 65, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2577451336816736, 'min_weight_fraction_leaf': 0.16825008957166532}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.21400381268642565
Fold 2 IBS: 0.22109450936660485
Fold 3 IBS: 0.20503862284986576
Fold 4 IBS: 0.2246274770790179
Fold 5 IBS: 0.21844806220919266
[I 2024-04-14 12:59:48,667] Trial 29 finished with value: 0.21664249683822137 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 208, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3996547259452995, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 18 with value: 0.18592544423505888.

Fold 1 IBS: 0.17098851044726665
Fold 2 IBS: 0.21481315097086512
Fold 3 IBS: 0.16632603025301468
Fold 4 IBS: 0.16401546065620026
Fold 5 IBS: 0.2278634394044985
[I 2024-04-14 12:59:49,862] Trial 30 finished with value: 0.18880131834636904 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 133, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5318918739079888, 'min_weight_fraction_leaf': 0.10732787343717065}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.16709338870083962
Fold 2 IBS: 0.2207970817898967
Fold 3 IBS: 0.16106031320634173
Fold 4 IBS: 0.15411080176278658
Fold 5 IBS: 0.23492661118338568
[I 2024-04-14 12:59:53,926] Trial 31 finished with value: 0.18759763932865006 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7099276247741286, 'min_weight_fraction_leaf': 0.062147327530191525}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.1724424087021706
Fold 2 IBS: 0.2089852547642303
Fold 3 IBS: 0.16379174265905339
Fold 4 IBS: 0.15291634694501582
Fold 5 IBS: 0.23848464400047958
[I 2024-04-14 12:59:54,314] Trial 32 finished with value: 0.18732407941418994 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4590303067651391, 'min_weight_fraction_leaf': 0.04994381169357695}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.17164647775629463
Fold 2 IBS: 0.2189152591764269
Fold 3 IBS: 0.16779233898432894
Fold 4 IBS: 0.158343869308426
Fold 5 IBS: 0.2367093348062445
[I 2024-04-14 12:59:54,791] Trial 33 finished with value: 0.1906814560063442 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 38, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5096486076788278, 'min_weight_fraction_leaf': 0.07462244540321868}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.17150336244073855
Fold 2 IBS: 0.23413930590251508
Fold 3 IBS: 0.15016842228794366
Fold 4 IBS: 0.14577996788276337
Fold 5 IBS: 0.2506280036590901
[I 2024-04-14 12:59:55,617] Trial 34 finished with value: 0.19044381243461014 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 82, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4438969261133742, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.1959608619809252
Fold 2 IBS: 0.21467078390929184
Fold 3 IBS: 0.18531264002432915
Fold 4 IBS: 0.20339174529671952
Fold 5 IBS: 0.21354426799377946
[I 2024-04-14 12:59:56,011] Trial 35 finished with value: 0.20257605984100904 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 31, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.3652305205316355, 'min_weight_fraction_leaf': 0.12037381835622729}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.1727462199496023
Fold 2 IBS: 0.21445389753736868
Fold 3 IBS: 0.16590434163462062
Fold 4 IBS: 0.16630733753004115
Fold 5 IBS: 0.2279741049789929
[I 2024-04-14 12:59:57,632] Trial 36 finished with value: 0.18947718032612512 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 153, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4613158155791392, 'min_weight_fraction_leaf': 0.09794997319269053}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.2139411835757384
Fold 2 IBS: 0.22109590374849766
Fold 3 IBS: 0.20465553472112794
Fold 4 IBS: 0.22464975610918914
Fold 5 IBS: 0.21832943212476583
[I 2024-04-14 12:59:58,482] Trial 37 finished with value: 0.2165343620558638 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 97, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.2855670174180933, 'min_weight_fraction_leaf': 0.16392025638393132}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.17332231081726507
Fold 2 IBS: 0.2041451639527933
Fold 3 IBS: 0.1746507103409507
Fold 4 IBS: 0.17164792169234858
Fold 5 IBS: 0.2208045397872162
[I 2024-04-14 12:59:59,099] Trial 38 finished with value: 0.18891412931811477 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 56, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.18443416794911643, 'min_weight_fraction_leaf': 0.06144243153316475}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.21879773034296215
Fold 2 IBS: 0.22180612097893898
Fold 3 IBS: 0.20393892490086993
Fold 4 IBS: 0.23038441001836493
Fold 5 IBS: 0.2183895613649977
[I 2024-04-14 12:59:59,287] Trial 39 finished with value: 0.21866334952122676 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 3, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5743736178608209, 'min_weight_fraction_leaf': 0.26803256454749924}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.1730993551616581
Fold 2 IBS: 0.2112075998749046
Fold 3 IBS: 0.16931706947271463
Fold 4 IBS: 0.17078719417082106
Fold 5 IBS: 0.22315902181166664
[I 2024-04-14 13:00:01,850] Trial 40 finished with value: 0.18951404809835298 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 292, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.42439317266867815, 'min_weight_fraction_leaf': 0.0295107662656946}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.1703642080613142
Fold 2 IBS: 0.21439771974918959
Fold 3 IBS: 0.16242283111074446
Fold 4 IBS: 0.15813638535056032
Fold 5 IBS: 0.23429052137073095
[I 2024-04-14 13:00:03,962] Trial 41 finished with value: 0.18792233312850787 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 227, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5013876707670448, 'min_weight_fraction_leaf': 0.056733989404072684}. Best is trial 18 with value: 0.18592544423505888.
Fold 1 IBS: 0.16392612887152175
Fold 2 IBS: 0.22075992284359355
Fold 3 IBS: 0.1579277675136615
Fold 4 IBS: 0.14946795485123024
Fold 5 IBS: 0.23473892276930133
[I 2024-04-14 13:00:06,842] Trial 42 finished with value: 0.18536413936986168 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8291203686449198, 'min_weight_fraction_leaf': 0.021277109376101316}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16393719526641504
Fold 2 IBS: 0.22208027248321102
Fold 3 IBS: 0.15863743773147637
Fold 4 IBS: 0.15150663088875235
Fold 5 IBS: 0.23394740350912158
[I 2024-04-14 13:00:10,666] Trial 43 finished with value: 0.1860217879757953 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 398, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.837257142849845, 'min_weight_fraction_leaf': 0.03868756313108112}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17324867535578212
Fold 2 IBS: 0.20447683904371408
Fold 3 IBS: 0.17212848917815507
Fold 4 IBS: 0.17430996910757815
Fold 5 IBS: 0.2184169062434037
[I 2024-04-14 13:00:13,346] Trial 44 finished with value: 0.1885161757857266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8909266850031794, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 42 with value: 0.18536413936986168.

Fold 1 IBS: 0.16919093793006681
Fold 2 IBS: 0.22072139997365403
Fold 3 IBS: 0.16323839347363078
Fold 4 IBS: 0.15681709166454283
Fold 5 IBS: 0.23415423999459772
[I 2024-04-14 13:00:17,038] Trial 45 finished with value: 0.18882441260729843 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.848529004532656, 'min_weight_fraction_leaf': 0.027746600647391314}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17088136388053118
Fold 2 IBS: 0.22055326503970013
Fold 3 IBS: 0.16296852866957956
Fold 4 IBS: 0.15728088459397643
Fold 5 IBS: 0.23399061285989559
[I 2024-04-14 13:00:19,285] Trial 46 finished with value: 0.1891349310087366 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7065720458945994, 'min_weight_fraction_leaf': 0.08266300950859551}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16587089650196102
Fold 2 IBS: 0.2169105776707177
Fold 3 IBS: 0.16212730684795526
Fold 4 IBS: 0.1561135359585933
Fold 5 IBS: 0.23132805435696568
[I 2024-04-14 13:00:23,237] Trial 47 finished with value: 0.1864700742672386 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6315369697816096, 'min_weight_fraction_leaf': 0.04366498030628087}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16537116624211357
Fold 2 IBS: 0.2173825980171524
Fold 3 IBS: 0.16179407108135443
Fold 4 IBS: 0.15680203698451298
Fold 5 IBS: 0.23072724260230307
[I 2024-04-14 13:00:25,718] Trial 48 finished with value: 0.1864154229854873 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7196628263534421, 'min_weight_fraction_leaf': 0.013692455015716525}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16872521716542774
Fold 2 IBS: 0.21330422808063002
Fold 3 IBS: 0.16929153026221802
Fold 4 IBS: 0.17487537419767285
Fold 5 IBS: 0.22341926063054532
[I 2024-04-14 13:00:28,179] Trial 49 finished with value: 0.18992312206729878 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8193232034026557, 'min_weight_fraction_leaf': 0.005747175925330623}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16878392243500004
Fold 2 IBS: 0.2123396235920515
Fold 3 IBS: 0.16957932900231176
Fold 4 IBS: 0.1737075191427868
Fold 5 IBS: 0.22345747400407742
[I 2024-04-14 13:00:32,289] Trial 50 finished with value: 0.18957357363524552 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 470, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7382583734728886, 'min_weight_fraction_leaf': 0.019151396476784134}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16943981559362684
Fold 2 IBS: 0.2181084248704849
Fold 3 IBS: 0.1635365256382045
Fold 4 IBS: 0.15865870040670066
Fold 5 IBS: 0.2320574272242207
[I 2024-04-14 13:00:35,447] Trial 51 finished with value: 0.18836017874664754 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6340464824924721, 'min_weight_fraction_leaf': 0.0657780770375467}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16554848132110891
Fold 2 IBS: 0.220012127749002
Fold 3 IBS: 0.16089166557378376
Fold 4 IBS: 0.15390914430754338
Fold 5 IBS: 0.23426167287110344
[I 2024-04-14 13:00:38,716] Trial 52 finished with value: 0.1869246183645083 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 431, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6737582074937531, 'min_weight_fraction_leaf': 0.04361366076930043}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.18288986975221336
Fold 2 IBS: 0.20228790226751528
Fold 3 IBS: 0.18016206703244153
Fold 4 IBS: 0.19352874641778853
Fold 5 IBS: 0.21423256442897598
[I 2024-04-14 13:00:41,870] Trial 53 finished with value: 0.19462022997978695 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7578061268299945, 'min_weight_fraction_leaf': 0.32112215016899026}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16611430633901464
Fold 2 IBS: 0.21940127235799115
Fold 3 IBS: 0.16128870608507292
Fold 4 IBS: 0.15592937503664833
Fold 5 IBS: 0.2317730238436129
[I 2024-04-14 13:00:44,819] Trial 54 finished with value: 0.18690133673246798 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6773099637579149, 'min_weight_fraction_leaf': 0.01250582376619716}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.167130736105669
Fold 2 IBS: 0.22204344172385923
Fold 3 IBS: 0.16186244194074492
Fold 4 IBS: 0.156633638546383
Fold 5 IBS: 0.23136285398809117
[I 2024-04-14 13:00:47,363] Trial 55 finished with value: 0.18780662246094948 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 345, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8360043872778312, 'min_weight_fraction_leaf': 0.00903199457944659}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.2139721195036936
Fold 2 IBS: 0.22126403950079757
Fold 3 IBS: 0.2047962507612815
Fold 4 IBS: 0.22464328477628995
Fold 5 IBS: 0.21862502764679473
[I 2024-04-14 13:00:50,198] Trial 56 finished with value: 0.21666014443777146 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 372, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9131116384948843, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16456938648388716
Fold 2 IBS: 0.21973250670220545
Fold 3 IBS: 0.15904736399244437
Fold 4 IBS: 0.15012643178808985
Fold 5 IBS: 0.23468582108085484
[I 2024-04-14 13:00:53,121] Trial 57 finished with value: 0.18563230200949632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 402, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7989464598338779, 'min_weight_fraction_leaf': 0.016643809086357014}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.21398382816509803
Fold 2 IBS: 0.22131896272218296
Fold 3 IBS: 0.2047615079222636
Fold 4 IBS: 0.22463497008066519
Fold 5 IBS: 0.21856091601900027
[I 2024-04-14 13:00:55,894] Trial 58 finished with value: 0.21665203698184202 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7720518840465647, 'min_weight_fraction_leaf': 0.4035578043371162}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16567730142102843
Fold 2 IBS: 0.22197345042741767
Fold 3 IBS: 0.1593600288876755
Fold 4 IBS: 0.15113254345207822
Fold 5 IBS: 0.23524419870007882
[I 2024-04-14 13:00:59,208] Trial 59 finished with value: 0.18667750457765572 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7916525376316971, 'min_weight_fraction_leaf': 7.056694785460144e-05}. Best is trial 42 with value: 0.18536413936986168.

Fold 1 IBS: 0.18690585538594123
Fold 2 IBS: 0.20938648863281817
Fold 3 IBS: 0.181022371952325
Fold 4 IBS: 0.19009687205800668
Fold 5 IBS: 0.2170173183599625
[I 2024-04-14 13:01:01,746] Trial 60 finished with value: 0.1968857812778107 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8876535776296195, 'min_weight_fraction_leaf': 0.08357065616960663}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16859725994611574
Fold 2 IBS: 0.21968660391194714
Fold 3 IBS: 0.16222130074755978
Fold 4 IBS: 0.15526729388868263
Fold 5 IBS: 0.2352496659850785
[I 2024-04-14 13:01:04,793] Trial 61 finished with value: 0.18820442489587677 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.802876817140778, 'min_weight_fraction_leaf': 0.00046770097798727595}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.1661570452627173
Fold 2 IBS: 0.22443101428470488
Fold 3 IBS: 0.15904396789834224
Fold 4 IBS: 0.15237274667808365
Fold 5 IBS: 0.23640508635996949
[I 2024-04-14 13:01:08,125] Trial 62 finished with value: 0.18768197209676352 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8502686409539971, 'min_weight_fraction_leaf': 0.04456383050959978}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16310721404646558
Fold 2 IBS: 0.22268037576876568
Fold 3 IBS: 0.15785777327730532
Fold 4 IBS: 0.14904682857530838
Fold 5 IBS: 0.2341618337404653
[I 2024-04-14 13:01:11,547] Trial 63 finished with value: 0.18537080508166207 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9508169242448795, 'min_weight_fraction_leaf': 0.03048627384181986}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16832696951766724
Fold 2 IBS: 0.214489098255302
Fold 3 IBS: 0.16944983657531693
Fold 4 IBS: 0.17348904005340124
Fold 5 IBS: 0.2235913017901991
[I 2024-04-14 13:01:14,331] Trial 64 finished with value: 0.18986924923837728 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9908921217635815, 'min_weight_fraction_leaf': 0.033230268485464856}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17431726395360797
Fold 2 IBS: 0.2550479555221831
Fold 3 IBS: 0.1612987813984537
Fold 4 IBS: 0.1568420553554684
Fold 5 IBS: 0.24559072493729456
[I 2024-04-14 13:01:17,253] Trial 65 finished with value: 0.19861935623340154 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9169553552522498, 'min_weight_fraction_leaf': 0.06356871285982306}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.21397839179600897
Fold 2 IBS: 0.22133146163753645
Fold 3 IBS: 0.20475557518254933
Fold 4 IBS: 0.22461796655577554
Fold 5 IBS: 0.21864816969213718
[I 2024-04-14 13:01:20,208] Trial 66 finished with value: 0.21666631297280148 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 441, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9341878165858052, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17219387511087106
Fold 2 IBS: 0.20701889137774832
Fold 3 IBS: 0.16966409509059802
Fold 4 IBS: 0.16980563284797662
Fold 5 IBS: 0.22084598083165485
[I 2024-04-14 13:01:23,512] Trial 67 finished with value: 0.18790569505176974 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.867172412444357, 'min_weight_fraction_leaf': 0.021833539145788197}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.1691567319111541
Fold 2 IBS: 0.22309069788261698
Fold 3 IBS: 0.16172963302474225
Fold 4 IBS: 0.15587040121775092
Fold 5 IBS: 0.23576882275754313
[I 2024-04-14 13:01:26,048] Trial 68 finished with value: 0.18912325735876148 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9548092512769554, 'min_weight_fraction_leaf': 0.10192712553960526}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.1740204834770185
Fold 2 IBS: 0.2082296321622783
Fold 3 IBS: 0.17087230927095848
Fold 4 IBS: 0.17457348942908948
Fold 5 IBS: 0.22098989977026587
[I 2024-04-14 13:01:28,222] Trial 69 finished with value: 0.18973716282192213 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6000248242496466, 'min_weight_fraction_leaf': 0.07615893087175928}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17096321826271313
Fold 2 IBS: 0.21805178669625944
Fold 3 IBS: 0.16805517804549433
Fold 4 IBS: 0.16512726896378685
Fold 5 IBS: 0.22960321032585862
[I 2024-04-14 13:01:31,595] Trial 70 finished with value: 0.19036013245882247 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7475614346734533, 'min_weight_fraction_leaf': 0.14045750500673848}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16608928988953414
Fold 2 IBS: 0.22174486653128392
Fold 3 IBS: 0.15915594899617824
Fold 4 IBS: 0.15096476010747392
Fold 5 IBS: 0.2354104576371314
[I 2024-04-14 13:01:34,883] Trial 71 finished with value: 0.18667306463232033 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 422, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7907524067271253, 'min_weight_fraction_leaf': 0.0369529143766379}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16536690986838246
Fold 2 IBS: 0.22274570345122793
Fold 3 IBS: 0.15834080703184705
Fold 4 IBS: 0.1509711768672338
Fold 5 IBS: 0.23464271967955017
[I 2024-04-14 13:01:37,777] Trial 72 finished with value: 0.18641346337964831 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7244719995956458, 'min_weight_fraction_leaf': 0.043591370911141555}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16586388269672708
Fold 2 IBS: 0.22387887379921298
Fold 3 IBS: 0.15943648809014654
Fold 4 IBS: 0.15199080662056397
Fold 5 IBS: 0.23507084484926263
[I 2024-04-14 13:01:40,677] Trial 73 finished with value: 0.18724817921118264 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6973727268996786, 'min_weight_fraction_leaf': 0.05275692854988752}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.1679142138548871
Fold 2 IBS: 0.21903575686381085
Fold 3 IBS: 0.16131036950445646
Fold 4 IBS: 0.1547412045733022
Fold 5 IBS: 0.23495651882356208
[I 2024-04-14 13:01:43,492] Trial 74 finished with value: 0.18759161272400374 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 364, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7370174951810275, 'min_weight_fraction_leaf': 0.015641860753105398}. Best is trial 42 with value: 0.18536413936986168.

Fold 1 IBS: 0.17119567250301165
Fold 2 IBS: 0.24105206157891446
Fold 3 IBS: 0.15213609072622497
Fold 4 IBS: 0.14859184553071816
Fold 5 IBS: 0.24326056635040982
[I 2024-04-14 13:01:46,676] Trial 75 finished with value: 0.1912472473378558 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6510484272191477, 'min_weight_fraction_leaf': 0.0708680095858405}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.18853691736578462
Fold 2 IBS: 0.209428188689307
Fold 3 IBS: 0.18272779365407454
Fold 4 IBS: 0.19346798348237323
Fold 5 IBS: 0.21682995331709484
[I 2024-04-14 13:01:50,968] Trial 76 finished with value: 0.19819816730172685 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 491, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8197928399417203, 'min_weight_fraction_leaf': 0.03415229574496717}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17014690883896852
Fold 2 IBS: 0.21861725321890052
Fold 3 IBS: 0.16364751007800205
Fold 4 IBS: 0.1588363943733344
Fold 5 IBS: 0.23311550080884022
[I 2024-04-14 13:01:53,937] Trial 77 finished with value: 0.18887271346360915 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.72450513752201, 'min_weight_fraction_leaf': 0.09053076866898657}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.18360628001316176
Fold 2 IBS: 0.210261667942571
Fold 3 IBS: 0.17866802992749822
Fold 4 IBS: 0.18514984912707352
Fold 5 IBS: 0.2163906460561689
[I 2024-04-14 13:01:57,691] Trial 78 finished with value: 0.19481529461329467 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.050786640284420134}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17123172672834652
Fold 2 IBS: 0.21769617641176348
Fold 3 IBS: 0.16968113776302185
Fold 4 IBS: 0.17010044162416768
Fold 5 IBS: 0.22485476554889008
[I 2024-04-14 13:02:00,049] Trial 79 finished with value: 0.19071284961523793 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 254, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.867714153034519, 'min_weight_fraction_leaf': 0.11361158104753287}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.17107458489822464
Fold 2 IBS: 0.21807950960918318
Fold 3 IBS: 0.164141728247378
Fold 4 IBS: 0.15953531518105785
Fold 5 IBS: 0.23339213728896752
[I 2024-04-14 13:02:02,751] Trial 80 finished with value: 0.18924465504496224 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7650625591580945, 'min_weight_fraction_leaf': 0.021280866356883095}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.1656884586665797
Fold 2 IBS: 0.22199960816653425
Fold 3 IBS: 0.15845809022856405
Fold 4 IBS: 0.15156893360695747
Fold 5 IBS: 0.23546332252449312
[I 2024-04-14 13:02:05,827] Trial 81 finished with value: 0.1866356826386257 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 422, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8177437691692557, 'min_weight_fraction_leaf': 0.03756096611225669}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16386587081152787
Fold 2 IBS: 0.22043993593292063
Fold 3 IBS: 0.15831558969457737
Fold 4 IBS: 0.15146357482804987
Fold 5 IBS: 0.23372039694620436
[I 2024-04-14 13:02:08,775] Trial 82 finished with value: 0.185561073642656 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8249706193135742, 'min_weight_fraction_leaf': 0.03812553846692457}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16382148540644464
Fold 2 IBS: 0.22296613993434358
Fold 3 IBS: 0.15892399123376577
Fold 4 IBS: 0.15132022105085102
Fold 5 IBS: 0.234233018694088
[I 2024-04-14 13:02:11,654] Trial 83 finished with value: 0.1862529712638986 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.946400272758323, 'min_weight_fraction_leaf': 0.056711070962204235}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16554748784205559
Fold 2 IBS: 0.22325384666992362
Fold 3 IBS: 0.15983848301479955
Fold 4 IBS: 0.15206811709709686
Fold 5 IBS: 0.23534503530108655
[I 2024-04-14 13:02:14,566] Trial 84 finished with value: 0.18721059398499243 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.960881259934268, 'min_weight_fraction_leaf': 0.06738655202467413}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16413841705005125
Fold 2 IBS: 0.22279827977481154
Fold 3 IBS: 0.1596934512945492
Fold 4 IBS: 0.15185329587873378
Fold 5 IBS: 0.2343460993249675
[I 2024-04-14 13:02:16,945] Trial 85 finished with value: 0.18656590866462266 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9447086236328559, 'min_weight_fraction_leaf': 0.056359295233899334}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16329873427770597
Fold 2 IBS: 0.22504054437434673
Fold 3 IBS: 0.15621791943205485
Fold 4 IBS: 0.14871612910983092
Fold 5 IBS: 0.2347502805021228
[I 2024-04-14 13:02:19,921] Trial 86 finished with value: 0.18560472153921223 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8814370606980997, 'min_weight_fraction_leaf': 0.017128693486592957}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16870790099219218
Fold 2 IBS: 0.2221250913106811
Fold 3 IBS: 0.16151783733803732
Fold 4 IBS: 0.15613832339901462
Fold 5 IBS: 0.23550015078622713
[I 2024-04-14 13:02:22,858] Trial 87 finished with value: 0.18879786076523045 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8767965404701702, 'min_weight_fraction_leaf': 0.09025375377286744}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16892319415646814
Fold 2 IBS: 0.21806674417601127
Fold 3 IBS: 0.17019440105930844
Fold 4 IBS: 0.16721028264239693
Fold 5 IBS: 0.2254068310797526
[I 2024-04-14 13:02:24,746] Trial 88 finished with value: 0.18996029062278746 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9323727137281094, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16703225880521694
Fold 2 IBS: 0.22522036534469675
Fold 3 IBS: 0.15946669220534124
Fold 4 IBS: 0.15235802682674315
Fold 5 IBS: 0.23580092695985078
[I 2024-04-14 13:02:27,654] Trial 89 finished with value: 0.18797565402836977 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 386, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.904878643399301, 'min_weight_fraction_leaf': 0.03034405340399308}. Best is trial 42 with value: 0.18536413936986168.

Fold 1 IBS: 0.16995945205700103
Fold 2 IBS: 0.22143925404090192
Fold 3 IBS: 0.16372958458946052
Fold 4 IBS: 0.15806194585094185
Fold 5 IBS: 0.23432624599230448
[I 2024-04-14 13:02:31,277] Trial 90 finished with value: 0.18950329650612197 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9979423948457556, 'min_weight_fraction_leaf': 0.1267762525048648}. Best is trial 42 with value: 0.18536413936986168.
Fold 1 IBS: 0.16294257869738282
Fold 2 IBS: 0.22247116644247825
Fold 3 IBS: 0.1575456290734587
Fold 4 IBS: 0.150103345920691
Fold 5 IBS: 0.23188419808478244
[I 2024-04-14 13:02:34,490] Trial 91 finished with value: 0.18498938364375864 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8444258086410001, 'min_weight_fraction_leaf': 0.01775686776140395}. Best is trial 91 with value: 0.18498938364375864.
Fold 1 IBS: 0.16334696282721115
Fold 2 IBS: 0.22239261764330487
Fold 3 IBS: 0.1585124992059021
Fold 4 IBS: 0.15094779609459608
Fold 5 IBS: 0.23394686804621428
[I 2024-04-14 13:02:37,370] Trial 92 finished with value: 0.1858293487634457 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 367, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8431229402073177, 'min_weight_fraction_leaf': 0.013833689939098698}. Best is trial 91 with value: 0.18498938364375864.
Fold 1 IBS: 0.16314487519836676
Fold 2 IBS: 0.22190072768158675
Fold 3 IBS: 0.15744410848136337
Fold 4 IBS: 0.15015997212200474
Fold 5 IBS: 0.23295452035162387
[I 2024-04-14 13:02:39,962] Trial 93 finished with value: 0.1851208407669891 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 331, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8417404434057405, 'min_weight_fraction_leaf': 0.01453522990613677}. Best is trial 91 with value: 0.18498938364375864.
Fold 1 IBS: 0.16475166628630258
Fold 2 IBS: 0.22206179645841356
Fold 3 IBS: 0.15689538282454912
Fold 4 IBS: 0.14799817765884163
Fold 5 IBS: 0.2314000011267525
[I 2024-04-14 13:02:42,313] Trial 94 finished with value: 0.1846214048709719 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8425420987546135, 'min_weight_fraction_leaf': 0.013411223309098799}. Best is trial 94 with value: 0.1846214048709719.
Fold 1 IBS: 0.16445003950387088
Fold 2 IBS: 0.22170994232786118
Fold 3 IBS: 0.15655644306400576
Fold 4 IBS: 0.14823335156520442
Fold 5 IBS: 0.2314617765250129
[I 2024-04-14 13:02:44,680] Trial 95 finished with value: 0.18448231059719103 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 331, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8403749665514068, 'min_weight_fraction_leaf': 0.01274638040242543}. Best is trial 95 with value: 0.18448231059719103.
Fold 1 IBS: 0.16431323988186475
Fold 2 IBS: 0.2232076135320923
Fold 3 IBS: 0.15737916305019678
Fold 4 IBS: 0.14938496610064664
Fold 5 IBS: 0.23383429025402466
[I 2024-04-14 13:02:47,062] Trial 96 finished with value: 0.185623854563765 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8505526233309074, 'min_weight_fraction_leaf': 0.017874258557190735}. Best is trial 95 with value: 0.18448231059719103.
Fold 1 IBS: 0.16380683134467422
Fold 2 IBS: 0.22023565891111624
Fold 3 IBS: 0.15648846615056528
Fold 4 IBS: 0.14830982681881624
Fold 5 IBS: 0.23204698039694074
[I 2024-04-14 13:02:49,338] Trial 97 finished with value: 0.18417755272442254 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8853584450011042, 'min_weight_fraction_leaf': 0.00885577315322818}. Best is trial 97 with value: 0.18417755272442254.
Fold 1 IBS: 0.16486786728412392
Fold 2 IBS: 0.22221152525627483
Fold 3 IBS: 0.15705468180990448
Fold 4 IBS: 0.1494738252798924
Fold 5 IBS: 0.23351642458417307
[I 2024-04-14 13:02:51,756] Trial 98 finished with value: 0.18542486484287374 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8931339045364779, 'min_weight_fraction_leaf': 0.0009544237092152102}. Best is trial 97 with value: 0.18417755272442254.
Fold 1 IBS: 0.16501341755454046
Fold 2 IBS: 0.22233361897060563
Fold 3 IBS: 0.15707921138740794
Fold 4 IBS: 0.14962139682228304
Fold 5 IBS: 0.23328996863475673
[I 2024-04-14 13:02:54,177] Trial 99 finished with value: 0.18546752267391878 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 337, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8893477669458972, 'min_weight_fraction_leaf': 0.007259167100140962}. Best is trial 97 with value: 0.18417755272442254.


* Best trial for IBS:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.18417755272442254], datetime_start=datetime.datetime(2024, 4, 14, 13, 2, 47, 68879), datetime_complete=datetime.datetime(2024, 4, 14, 13, 2, 49, 337771), params={'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 322, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8853584450011042, 'min_weight_fraction_leaf': 0.00885577315322818}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=97, value=None)


* Best Score for IBS:
 0.18417755272442254

In [170]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [171]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.798
train_ibs:  0.184

#### Test

In [172]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [173]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=20, max_features='auto', max_leaf_nodes=18,
                   max_samples=0.4107674575173371, min_samples_leaf=1,
                   min_samples_split=17,
                   min_weight_fraction_leaf=0.005571403264584145,
                   n_estimators=192, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.632

ExtraSurvivalTrees(max_depth=17, max_features='log2', max_leaf_nodes=6,
                   max_samples=0.8853584450011042, min_samples_leaf=2,
                   min_samples_split=15,
                   min_weight_fraction_leaf=0.00885577315322818,
                   n_estimators=322, random_state=123, warm_start=True)

IBS: 0.217

In [174]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [175]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 13:02:55,227] A new study created in memory with name: no-name-77de4da3-4372-48b6-a0a4-4c6faec7a37b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:08,618] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:15,955] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:25,934] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:40,184] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:45,503] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:46,739] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:03:58,058] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:04:01,206] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:04:01,618] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.8455882352941176
Fold 4 C-index: 0.8080168776371308
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 13:21:46,726] Trial 9 finished with value: 0.7287367685773478 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 13:37:41,791] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:47:19,866] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:29:50,614] Trial 12 finished with value: 0.7078554607388912 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:07,545] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:32,376] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:35:42,460] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:35:57,216] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:30,941] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:37:19,443] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:37:21,418] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:37:44,744] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:38:24,888] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 14:39:04,936] Trial 22 finished with value: 0.7074432574939246 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:39:37,478] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:40:06,431] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:40:23,691] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:41:00,229] Trial 26 finished with value: 0.5351043762575453 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:34,396] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:42:03,548] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:42:30,256] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:42:56,662] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:43:44,467] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:44:36,260] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:45:16,081] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:13,361] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:22,849] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:07,883] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:09,237] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:26,760] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:53,624] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:38,551] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 14:48:38,714] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:48:43,723] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:50,900] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:04,436] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:09,415] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:13,714] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:31,778] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:39,481] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:58,875] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:00,375] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:50:00,669] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:00,939] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:50:04,430] Trial 53 finished with value: 0.7066921324762583 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:07,753] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:08,529] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:02,710] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:05,985] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:14,196] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:58,382] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:13,447] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:14,856] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:52:21,686] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:52:22,698] Trial 63 finished with value: 0.715358098862813 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:24,667] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:27,751] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:16,975] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:17,592] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:28,644] Trial 68 finished with value: 0.6289549910873441 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:29,756] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:06,532] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:54:06,764] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:54:07,110] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:15,426] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:15,762] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:18,256] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:39,201] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:40,051] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:27,369] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:34,764] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:52,866] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 14:55:53,179] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:55:53,720] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:54,618] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:03,026] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:03,413] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:04,674] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:05,660] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:06,918] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:45,300] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:49,110] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:57:49,562] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:49,963] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:50,146] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:50,749] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:57:51,776] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7287367685773478.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6220657276995305
[I 2024-04-14 14:57:54,113] Trial 96 finished with value: 0.7426401716783246 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7426401716783246.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:56,532] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7426401716783246.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:57:58,584] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7426401716783246.
Fold 1 C-index: 0.4675324675324675
Fold 2 C-index: 0.6919642857142857

[I 2024-04-14 14:57:58,877] A new study created in memory with name: no-name-90022e5b-4bd5-4399-95ce-932890dd929e

Fold 3 C-index: 0.4877450980392157
Fold 4 C-index: 0.5928270042194093
Fold 5 C-index: 0.5516431924882629
[I 2024-04-14 14:57:58,857] Trial 99 finished with value: 0.5583424095987283 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7426401716783246.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7426401716783246], datetime_start=datetime.datetime(2024, 4, 14, 14, 57, 51, 784558), datetime_complete=datetime.datetime(2024, 4, 14, 14, 57, 54, 113206), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7426401716783246

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:58:12,727] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:58:20,356] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:58:27,910] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:58:40,294] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:58:45,056] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:58:46,263] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:58:57,978] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:59:01,261] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:59:01,706] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.2130270917861311
Fold 2 IBS: 0.2213261650256521
Fold 3 IBS: 0.2035895232879886
Fold 4 IBS: 0.22376098665180924
Fold 5 IBS: 0.21793593352546728
[I 2024-04-14 14:59:32,780] Trial 9 finished with value: 0.21592794005540966 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 15:00:19,476] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:01:12,841] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.2138394554380325
Fold 2 IBS: 0.22156449267228215
Fold 3 IBS: 0.20440421917640686
Fold 4 IBS: 0.22459155969877373
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 15:02:00,656] Trial 12 finished with value: 0.21649969068723066 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 15:02:22,680] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:03:02,046] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:03:35,953] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:03:54,682] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:04:40,711] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:05:06,695] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:05:12,214] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:06:05,508] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 15:06:57,663] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21592794005540966.
Fold 1 IBS: 0.2127480593246117
Fold 2 IBS: 0.2214154340077775

Fold 3 IBS: 0.20333427322851355
Fold 4 IBS: 0.22312878836495256
Fold 5 IBS: 0.21791022310639455
[I 2024-04-14 15:07:55,984] Trial 22 finished with value: 0.21570735560645 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:08:46,054] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:09:16,496] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:09:45,860] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:10:30,554] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:10:36,032] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:10:52,258] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:11:33,707] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:11:51,089] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 15:12:51,987] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.22144791559015894
Fold 3 IBS: 0.20359640314421312
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.21789545644168284
[I 2024-04-14 15:13:46,868] Trial 32 finished with value: 0.21589780985224039 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:14:25,361] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:15:14,394] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:15:25,151] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:16:19,811] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:16:21,536] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:16:47,983] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:17:26,717] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:18:04,089] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21336832511750178
Fold 2 IBS: 0.22149081759520453
Fold 3 IBS: 0.20392451903804681
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21799037217752354
[I 2024-04-14 15:18:50,800] Trial 41 finished with value: 0.2161463683278478 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.2130684349835424
Fold 2 IBS: 0.2213765150144246
Fold 3 IBS: 0.20363555732260985
Fold 4 IBS: 0.2236086603904485
Fold 5 IBS: 0.21789149192159524
[I 2024-04-14 15:19:48,616] Trial 42 finished with value: 0.2159161319265241 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:20:47,854] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268

Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:21:37,103] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.2137594873102941
Fold 2 IBS: 0.22146654936526117
Fold 3 IBS: 0.20433236975792607
Fold 4 IBS: 0.2244535243326402
Fold 5 IBS: 0.21807365172970994
[I 2024-04-14 15:22:19,099] Trial 45 finished with value: 0.2164171164991663 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:22:56,736] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:23:11,821] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:23:12,090] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:23:19,960] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:24:01,389] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 15:24:50,755] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:25:50,302] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21570735560645.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22137600200037952
Fold 3 IBS: 0.20240438380881318
Fold 4 IBS: 0.22194891399880726
Fold 5 IBS: 0.21777686189712414
[I 2024-04-14 15:26:29,938] Trial 53 finished with value: 0.21504986372331816 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:27:09,099] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:27:43,181] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:28:17,291] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:29:05,194] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:29:58,484] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:30:34,225] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:31:04,157] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:31:47,127] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 15:32:34,231] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:33:32,485] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21295750753141518
Fold 2 IBS: 0.22124428220001838
Fold 3 IBS: 0.20360387919673426
Fold 4 IBS: 0.2236501361430326
Fold 5 IBS: 0.2179071095932534
[I 2024-04-14 15:34:30,840] Trial 64 finished with value: 0.21587258293289077 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21281733818690107
Fold 2 IBS: 0.22095131540546672
Fold 3 IBS: 0.2032506863600244
Fold 4 IBS: 0.22301259728320078
Fold 5 IBS: 0.21783452308265203
[I 2024-04-14 15:35:34,282] Trial 65 finished with value: 0.215573292063649 and parameters: {'subsample': 0.9189183326723824, 'learning_rate': 0.00872213651685068, 'dropout_rate': 0.15744491147958184, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 0.0027457451635429023, 'min_weight_fraction_leaf': 0.218026428516915, 'max_features': 'log2', 'min_impurity_decrease': 3.884557803763542e-06, 'validation_fraction': 0.9772658166542009, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:36:38,847] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8639813037885321, 'learning_rate': 0.010366561182703663, 'dropout_rate': 0.2054023171521986, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.0590752315578722, 'min_weight_fraction_leaf': 0.1974211678184809, 'max_features': 'log2', 'min_impurity_decrease': 4.836772048236878e-06, 'validation_fraction': 0.9971715713668047, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:37:42,859] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.924711151270876, 'learning_rate': 0.009416377941785207, 'dropout_rate': 0.1662721971023693, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.6209101057240151, 'min_weight_fraction_leaf': 0.17934817748077603, 'max_features': 'log2', 'min_impurity_decrease': 3.102112447557567e-06, 'validation_fraction': 0.911923187481934, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 8}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:38:30,518] Trial 68 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8140014869251382, 'learning_rate': 0.014752651720825174, 'dropout_rate': 0.11923568819182435, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.2065728012666141, 'min_weight_fraction_leaf': 0.21218775276698854, 'max_features': 'log2', 'min_impurity_decrease': 1.4539585728269896e-05, 'validation_fraction': 0.8273349120190413, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:39:33,522] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9988924989656905, 'learning_rate': 0.02831436330338611, 'dropout_rate': 0.16724677379095765, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 3.9803027487021705, 'min_weight_fraction_leaf': 0.16278537089773978, 'max_features': 'log2', 'min_impurity_decrease': 1.2991862538035283e-06, 'validation_fraction': 0.974238719043193, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:40:05,235] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8990643394736435, 'learning_rate': 0.008813612810119076, 'dropout_rate': 0.5905404972480945, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 6.120501546200477, 'min_weight_fraction_leaf': 0.15260562743112346, 'max_features': 'log2', 'min_impurity_decrease': 7.713426989240967e-06, 'validation_fraction': 0.9231652645655831, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21320376527492474
Fold 2 IBS: 0.22123046496341217
Fold 3 IBS: 0.20375873612465098
Fold 4 IBS: 0.22364459952824678
Fold 5 IBS: 0.21801071609912814
[I 2024-04-14 15:40:57,775] Trial 71 finished with value: 0.21596965639807256 and parameters: {'subsample': 0.9733969125354864, 'learning_rate': 0.004534805415780903, 'dropout_rate': 0.132474187624217, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.02682769133444822, 'min_weight_fraction_leaf': 0.1936286226601749, 'max_features': 'log2', 'min_impurity_decrease': 8.886845592590798e-07, 'validation_fraction': 0.9729187814085662, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:41:54,279] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9301573375470014, 'learning_rate': 0.003546549118661939, 'dropout_rate': 0.1933034526628665, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.3051396205214099, 'min_weight_fraction_leaf': 0.22121218007981025, 'max_features': 'log2', 'min_impurity_decrease': 1.4531877098171637e-06, 'validation_fraction': 0.9471253058954233, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 15:42:39,233] Trial 73 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.999953059550104, 'learning_rate': 0.016413333024245372, 'dropout_rate': 0.1494767846695832, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.8024489997023381, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'sqrt', 'min_impurity_decrease': 6.897864555007704e-07, 'validation_fraction': 0.8647043482635267, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:42:44,062] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9677492383027341, 'learning_rate': 0.007152092860070451, 'dropout_rate': 0.22741374895706717, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.35084579238043634, 'max_features': 'log2', 'min_impurity_decrease': 2.9943562650383953e-06, 'validation_fraction': 0.8935136450037395, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.2127730800210749
Fold 2 IBS: 0.22114748457812344
Fold 3 IBS: 0.2030176503545218
Fold 4 IBS: 0.22261318462046037
Fold 5 IBS: 0.21790532080965794
[I 2024-04-14 15:43:29,464] Trial 75 finished with value: 0.2154913440767677 and parameters: {'subsample': 0.8825286004306149, 'learning_rate': 0.011275284948798047, 'dropout_rate': 0.24636984302682827, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.008819925578928337, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.9658955990718601, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:44:14,687] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8822084861636357, 'learning_rate': 0.022756306561370964, 'dropout_rate': 0.31336983386215705, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.8575030371262532, 'min_weight_fraction_leaf': 0.09504128680510565, 'max_features': None, 'min_impurity_decrease': 0.00034462183165821184, 'validation_fraction': 0.9276129852375451, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 5}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:44:56,957] Trial 77 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9392590368987991, 'learning_rate': 0.011132229721027662, 'dropout_rate': 0.25203573700169807, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.33381590515318865, 'min_weight_fraction_leaf': 0.13051249394026804, 'max_features': 1, 'min_impurity_decrease': 7.70123021698274e-05, 'validation_fraction': 0.994934454010795, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:45:46,395] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8479726466301248, 'learning_rate': 0.04205291686981777, 'dropout_rate': 0.19830895403108711, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.6761477264897129, 'min_weight_fraction_leaf': 0.25364713658708027, 'max_features': 'auto', 'min_impurity_decrease': 0.0013458661001827122, 'validation_fraction': 0.8409381236879163, 'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:46:34,539] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9212007778521843, 'learning_rate': 0.018691773370111166, 'dropout_rate': 0.3401666755702263, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 1.3697303469982207, 'min_weight_fraction_leaf': 0.059436543656145036, 'max_features': 0.1, 'min_impurity_decrease': 4.409444341620953e-06, 'validation_fraction': 0.9714354901540546, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:47:21,258] Trial 80 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7969534216428152, 'learning_rate': 0.012583222435427047, 'dropout_rate': 0.28829477813771426, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.23485405917391566, 'max_features': 'auto', 'min_impurity_decrease': 6.230227949979902e-05, 'validation_fraction': 0.8858889560798657, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21327366041011542
Fold 2 IBS: 0.2214652687075112
Fold 3 IBS: 0.20384804288543604
Fold 4 IBS: 0.22387672832999023
Fold 5 IBS: 0.21797504874463694
[I 2024-04-14 15:48:07,778] Trial 81 finished with value: 0.21608774981553797 and parameters: {'subsample': 0.9722344486637098, 'learning_rate': 0.0037084225030570616, 'dropout_rate': 0.14904466424240095, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.025432112194026565, 'min_weight_fraction_leaf': 0.27646519093862765, 'max_features': 'auto', 'min_impurity_decrease': 2.61961103925368e-07, 'validation_fraction': 0.9431731904944002, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:48:55,131] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9448720976014137, 'learning_rate': 0.0538447232797746, 'dropout_rate': 0.2311360143359113, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.286660364444207, 'min_weight_fraction_leaf': 0.2885976911827929, 'max_features': 'auto', 'min_impurity_decrease': 0.08366939436473018, 'validation_fraction': 0.9622307477778195, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:49:46,177] Trial 83 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9046881322576289, 'learning_rate': 0.0073983454460704555, 'dropout_rate': 0.17220577471999526, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.6351743384287122, 'min_weight_fraction_leaf': 0.20706187101204562, 'max_features': 'auto', 'min_impurity_decrease': 0.0002249075769166659, 'validation_fraction': 0.9187090458278299, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:50:36,497] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9783982119260082, 'learning_rate': 0.009985920145385636, 'dropout_rate': 0.20939689519159663, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.20835125759711, 'min_weight_fraction_leaf': 0.3292923962058931, 'max_features': 'auto', 'min_impurity_decrease': 4.596257266663254e-07, 'validation_fraction': 0.9759866579556983, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504986372331816.
Fold 1 IBS: 0.21011501977427374
Fold 2 IBS: 0.22152929132927757
Fold 3 IBS: 0.20082180957706125
Fold 4 IBS: 0.21978630729009394
Fold 5 IBS: 0.21760692558038056
[I 2024-04-14 15:50:52,618] Trial 85 finished with value: 0.21397187071021745 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.014554866476952134, 'dropout_rate': 0.10391090561180716, 'n_estimators': 265, 'criterion': 'squared_error', 'ccp_alpha': 0.011241474018604543, 'min_weight_fraction_leaf': 0.12733224205170357, 'max_features': 'auto', 'min_impurity_decrease': 1.8697047323397577e-06, 'validation_fraction': 0.9999275626013308, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:51:04,775] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8606137140909582, 'learning_rate': 0.08767662742937916, 'dropout_rate': 0.10513626119564579, 'n_estimators': 241, 'criterion': 'squared_error', 'ccp_alpha': 0.9972723133843666, 'min_weight_fraction_leaf': 0.12562792621841556, 'max_features': 'auto', 'min_impurity_decrease': 1.0043785970844547e-05, 'validation_fraction': 0.9069972250123114, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 12}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:51:20,254] Trial 87 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7492693301217667, 'learning_rate': 0.013995510320305746, 'dropout_rate': 0.12354996158381873, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4341718461308403, 'min_weight_fraction_leaf': 0.11226806281497859, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6520281006567596e-06, 'validation_fraction': 0.9988717362956292, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 15:51:50,365] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8335693537780458, 'learning_rate': 0.025896998029808806, 'dropout_rate': 0.2592233887917012, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.998777407817298, 'min_weight_fraction_leaf': 0.06882085091143297, 'max_features': 'log2', 'min_impurity_decrease': 2.1900682995121406e-06, 'validation_fraction': 0.9382598277453086, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:51:58,438] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8801139289725153, 'learning_rate': 0.020383519809556987, 'dropout_rate': 0.17834614797528062, 'n_estimators': 209, 'criterion': 'squared_error', 'ccp_alpha': 0.6288168257140196, 'min_weight_fraction_leaf': 0.1838364799257016, 'max_features': 'auto', 'min_impurity_decrease': 3.99756238428e-06, 'validation_fraction': 0.8034906419904587, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:52:03,155] Trial 90 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9063467714031336, 'learning_rate': 0.015446119614603297, 'dropout_rate': 0.49901991527256273, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 2.4090644268425367, 'min_weight_fraction_leaf': 0.1395867989876331, 'max_features': 'auto', 'min_impurity_decrease': 2.2011519634799453e-05, 'validation_fraction': 0.8698393517024319, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.2128591122343161
Fold 2 IBS: 0.22142691927590935
Fold 3 IBS: 0.20345810208349668
Fold 4 IBS: 0.22336589150369232
Fold 5 IBS: 0.2179205991770419
[I 2024-04-14 15:52:41,012] Trial 91 finished with value: 0.2158061248548913 and parameters: {'subsample': 0.9540489140438861, 'learning_rate': 0.005831236591272541, 'dropout_rate': 0.14708835875280205, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.03795241787727033, 'min_weight_fraction_leaf': 0.3042489932965161, 'max_features': 'auto', 'min_impurity_decrease': 1.118647105999176e-06, 'validation_fraction': 0.9699154831592086, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:53:31,710] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.951860889195645, 'learning_rate': 0.007101713560747508, 'dropout_rate': 0.10091584870331681, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.19927212455432985, 'min_weight_fraction_leaf': 0.30595192978898894, 'max_features': 'auto', 'min_impurity_decrease': 1.1064396495665298e-06, 'validation_fraction': 0.9753757089288397, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:54:17,730] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.92180602311204, 'learning_rate': 0.017584949800848754, 'dropout_rate': 0.155352175491657, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.4610108245103026, 'min_weight_fraction_leaf': 0.25029878498224645, 'max_features': 'auto', 'min_impurity_decrease': 5.995680339686021e-06, 'validation_fraction': 0.9407929591551207, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21332722957119254
Fold 2 IBS: 0.22153950213362675
Fold 3 IBS: 0.20391981628635714
Fold 4 IBS: 0.2240629645665599
Fold 5 IBS: 0.217980411216748
[I 2024-04-14 15:54:43,550] Trial 94 finished with value: 0.21616598475489684 and parameters: {'subsample': 0.8793150927230791, 'learning_rate': 0.0027749992265539737, 'dropout_rate': 0.12764820329670162, 'n_estimators': 330, 'criterion': 'squared_error', 'ccp_alpha': 0.058163245004349426, 'min_weight_fraction_leaf': 0.2276941023602314, 'max_features': 'auto', 'min_impurity_decrease': 7.291508576058386e-07, 'validation_fraction': 0.9049661887509745, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 15:55:36,897] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9607117348561939, 'learning_rate': 0.012174074938611536, 'dropout_rate': 0.2185428700896648, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.7661738021343146, 'min_weight_fraction_leaf': 0.04194427014757368, 'max_features': None, 'min_impurity_decrease': 2.2434503326428074e-06, 'validation_fraction': 0.9999156284888805, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:55:39,338] Trial 96 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.936238883955148, 'learning_rate': 0.00973456374774443, 'dropout_rate': 0.23827215642775817, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 0.23613296469146558, 'min_weight_fraction_leaf': 0.2672850265092407, 'max_features': 'auto', 'min_impurity_decrease': 9.064174649500895e-07, 'validation_fraction': 0.9555544239307169, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:55:46,821] Trial 97 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.008255029347526567, 'dropout_rate': 0.8479620532477699, 'n_estimators': 295, 'criterion': 'friedman_mse', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.1636003712532283, 'max_features': 'auto', 'min_impurity_decrease': 3.679208144644871e-07, 'validation_fraction': 0.9257391585276332, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:56:33,100] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9024599692364454, 'learning_rate': 0.005266504740966472, 'dropout_rate': 0.18638214668831496, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.9707354386571323, 'min_weight_fraction_leaf': 0.23894367903351932, 'max_features': 1, 'min_impurity_decrease': 3.0399930076335373e-06, 'validation_fraction': 0.9743184170175514, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 85 with value: 0.21397187071021745.
Fold 1 IBS: 0.21256519342739535
Fold 2 IBS: 0.22131045172110525

Fold 3 IBS: 0.2031414835960969
Fold 4 IBS: 0.22300087224173537
Fold 5 IBS: 0.2178046738886567
[I 2024-04-14 15:57:27,774] Trial 99 finished with value: 0.21556453497499795 and parameters: {'subsample': 0.9762156523558686, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2717132298988158, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.004394120129034387, 'min_weight_fraction_leaf': 0.28881659395589254, 'max_features': 'auto', 'min_impurity_decrease': 1.3534409368328512e-06, 'validation_fraction': 0.6748895535913024, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 17}. Best is trial 85 with value: 0.21397187071021745.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.21397187071021745], datetime_start=datetime.datetime(2024, 4, 14, 15, 50, 36, 523157), datetime_complete=datetime.datetime(2024, 4, 14, 15, 50, 52, 617914), params={'subsample': 0.8559905830599279, 'learning_rate': 0.014554866476952134, 'dropout_rate': 0.10391090561180716, 'n_estimators': 265, 'criterion': 'squared_error', 'ccp_alpha': 0.011241474018604543, 'min_weight_fraction_leaf': 0.12733224205170357, 'max_features': 'auto', 'min_impurity_decrease': 1.8697047323397577e-06, 'validation_fraction': 0.9999275626013308, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 1}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.21397187071021745

In [176]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [177]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.743
train_ibs:  0.214

#### Test

In [178]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [179]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.59

GradientBoostingSurvivalAnalysis(ccp_alpha=0.011241474018604543,
                                 criterion='squared_error',
                                 dropout_rate=0.10391090561180716,
                                 learning_rate=0.014554866476952134,
                                 max_depth=1, max_features='auto',
                                 max_leaf_nodes=18,
                                 min_impurity_decrease=1.8697047323397577e-06,
                                 min_samples_leaf=19, min_samples_split=20,
                                 min_weight_fraction_leaf=0.12733224205170357,
                                 n_estimators=265, random_state=123,
                                 subsample=0.8559905830599279,
                                 validation_fraction=0.9999275626013308)

IBS: 0.218

In [180]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [181]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 15:57:35,270] A new study created in memory with name: no-name-4dcdc826-72cd-4f82-967b-69010ed42821

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 15:57:36,663] Trial 0 finished with value: 0.6849872959240584 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6849872959240584.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 15:57:44,545] Trial 1 finished with value: 0.6943010214142545 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6943010214142545.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:57:45,889] Trial 2 finished with value: 0.7047272149390397 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7047272149390397.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:57:47,839] Trial 3 finished with value: 0.7119568919076407 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7119568919076407.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:57:50,788] Trial 4 finished with value: 0.7207747803979043 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7207747803979043.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 15:57:54,671] Trial 5 finished with value: 0.6747194387812013 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7207747803979043.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:57:56,478] Trial 6 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7207747803979043.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:57:56,897] Trial 7 finished with value: 0.7119313465917007 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7207747803979043.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:57:59,018] Trial 8 finished with value: 0.6895756997875244 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7207747803979043.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:58:05,016] Trial 9 finished with value: 0.7154200953708442 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7207747803979043.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 15:58:09,036] Trial 10 finished with value: 0.7282679898407117 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.7282679898407117.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 15:58:14,597] Trial 11 finished with value: 0.733893625948248 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.733893625948248.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 15:58:20,292] Trial 12 finished with value: 0.7330278250824471 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.733893625948248.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:58:26,115] Trial 13 finished with value: 0.679353493107157 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.733893625948248.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 15:58:31,201] Trial 14 finished with value: 0.7353348154201955 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 14 with value: 0.7353348154201955.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:58:35,743] Trial 15 finished with value: 0.721869763845829 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.7098041576457912, 'n_estimators': 365, 'learning_rate': 0.08616677729964022}. Best is trial 14 with value: 0.7353348154201955.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 15:58:43,477] Trial 16 finished with value: 0.7191821019644344 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.7326988341376399, 'n_estimators': 423, 'learning_rate': 0.08463638125592773}. Best is trial 14 with value: 0.7353348154201955.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:58:49,227] Trial 17 finished with value: 0.716285896236645 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.6125221083505048, 'n_estimators': 413, 'learning_rate': 0.08749976591807801}. Best is trial 14 with value: 0.7353348154201955.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:58:52,844] Trial 18 finished with value: 0.7145542945050433 and parameters: {'subsample': 0.35888747153360906, 'dropout_rate': 0.8058789888144481, 'n_estimators': 324, 'learning_rate': 0.09062397105934869}. Best is trial 14 with value: 0.7353348154201955.

Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 15:58:57,512] Trial 19 finished with value: 0.7378573705369926 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9820749239416067, 'n_estimators': 431, 'learning_rate': 0.08300323114610605}. Best is trial 19 with value: 0.7378573705369926.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:59:02,793] Trial 20 finished with value: 0.7207747803979043 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.7933084651006226, 'n_estimators': 438, 'learning_rate': 0.0796244585080611}. Best is trial 19 with value: 0.7378573705369926.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 15:59:06,781] Trial 21 finished with value: 0.7360641059856737 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.9754161103921428, 'n_estimators': 387, 'learning_rate': 0.09637537942321125}. Best is trial 19 with value: 0.7378573705369926.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 15:59:11,869] Trial 22 finished with value: 0.739640219529683 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.9893004819878006, 'n_estimators': 396, 'learning_rate': 0.09976063116358903}. Best is trial 22 with value: 0.739640219529683.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 15:59:19,149] Trial 23 finished with value: 0.7209844569685766 and parameters: {'subsample': 0.196453315887333, 'dropout_rate': 0.9573423083551811, 'n_estimators': 448, 'learning_rate': 0.0794231371864776}. Best is trial 22 with value: 0.739640219529683.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:59:24,634] Trial 24 finished with value: 0.7179736599497251 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.9937491366220721, 'n_estimators': 390, 'learning_rate': 0.06814590891052567}. Best is trial 22 with value: 0.739640219529683.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 15:59:32,710] Trial 25 finished with value: 0.7255697001567609 and parameters: {'subsample': 0.19107837087373805, 'dropout_rate': 0.903277976932438, 'n_estimators': 494, 'learning_rate': 0.09478792669831074}. Best is trial 22 with value: 0.739640219529683.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:59:34,988] Trial 26 finished with value: 0.7154200953708442 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9922812936808074, 'n_estimators': 245, 'learning_rate': 0.08147044841076591}. Best is trial 22 with value: 0.739640219529683.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:59:41,474] Trial 27 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.8368873118701377, 'n_estimators': 405, 'learning_rate': 0.09100705603827391}. Best is trial 22 with value: 0.739640219529683.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 15:59:44,675] Trial 28 finished with value: 0.74162050985486 and parameters: {'subsample': 0.10061641287468016, 'dropout_rate': 0.9261509226223655, 'n_estimators': 274, 'learning_rate': 0.04202399206134448}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 15:59:45,142] Trial 29 finished with value: 0.6747194387812013 and parameters: {'subsample': 0.6457430091897011, 'dropout_rate': 0.9275322768632013, 'n_estimators': 62, 'learning_rate': 0.03905518643948439}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:59:46,209] Trial 30 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.8415754035698367, 'dropout_rate': 0.8712756161058139, 'n_estimators': 133, 'learning_rate': 0.01710528601594865}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 15:59:48,196] Trial 31 finished with value: 0.7320351976873993 and parameters: {'subsample': 0.14083449930913786, 'dropout_rate': 0.9985452939587839, 'n_estimators': 274, 'learning_rate': 0.06065446620667305}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 15:59:53,226] Trial 32 finished with value: 0.7208698656775147 and parameters: {'subsample': 0.20475665397727377, 'dropout_rate': 0.9343064022117069, 'n_estimators': 457, 'learning_rate': 0.043252728226482254}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 15:59:53,527] Trial 33 finished with value: 0.6981620085877752 and parameters: {'subsample': 0.10119033004596172, 'dropout_rate': 0.7934352133838902, 'n_estimators': 11, 'learning_rate': 0.03287495088836398}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 15:59:56,579] Trial 34 finished with value: 0.7216405812637052 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.9447966796198379, 'n_estimators': 341, 'learning_rate': 0.06958595449186536}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:00:01,019] Trial 35 finished with value: 0.7287732350918616 and parameters: {'subsample': 0.16865462544073573, 'dropout_rate': 0.8446462314626279, 'n_estimators': 390, 'learning_rate': 0.059610579305310316}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:00:04,209] Trial 36 finished with value: 0.718417519887256 and parameters: {'subsample': 0.30986291207776295, 'dropout_rate': 0.8841876813000313, 'n_estimators': 289, 'learning_rate': 0.09544820168496339}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:00:09,541] Trial 37 finished with value: 0.7346643415344387 and parameters: {'subsample': 0.1523274978768497, 'dropout_rate': 0.9580743520992803, 'n_estimators': 476, 'learning_rate': 0.07677405503763898}. Best is trial 28 with value: 0.74162050985486.

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:00:11,829] Trial 38 finished with value: 0.7207747803979043 and parameters: {'subsample': 0.23911041397514493, 'dropout_rate': 0.47419599199828566, 'n_estimators': 249, 'learning_rate': 0.06698521350410276}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:00:13,579] Trial 39 finished with value: 0.7078251586619834 and parameters: {'subsample': 0.4245656147243987, 'dropout_rate': 0.7665133891733147, 'n_estimators': 224, 'learning_rate': 0.05575307634287385}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:00:18,330] Trial 40 finished with value: 0.6835279066771849 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.5443446234145757, 'n_estimators': 434, 'learning_rate': 0.07411063894982059}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:00:21,578] Trial 41 finished with value: 0.7370762393921734 and parameters: {'subsample': 0.10437662902118044, 'dropout_rate': 0.6633503830383093, 'n_estimators': 342, 'learning_rate': 0.09926058281057615}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:00:25,847] Trial 42 finished with value: 0.7287732350918616 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.648107961196573, 'n_estimators': 382, 'learning_rate': 0.09338633648767328}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:00:30,551] Trial 43 finished with value: 0.7379305368073419 and parameters: {'subsample': 0.10596132568342653, 'dropout_rate': 0.3836769535493768, 'n_estimators': 338, 'learning_rate': 0.09980244031568099}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:00:35,291] Trial 44 finished with value: 0.7222051501113906 and parameters: {'subsample': 0.16242789119917195, 'dropout_rate': 0.39294801572366844, 'n_estimators': 337, 'learning_rate': 0.08435529874329645}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:00:38,743] Trial 45 finished with value: 0.724346208969333 and parameters: {'subsample': 0.28355480117942644, 'dropout_rate': 0.295844522167053, 'n_estimators': 291, 'learning_rate': 0.09959254503445845}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:00:43,070] Trial 46 finished with value: 0.7365837008274517 and parameters: {'subsample': 0.14242637662763621, 'dropout_rate': 0.4158988808509281, 'n_estimators': 311, 'learning_rate': 0.024992652172925307}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:00:46,865] Trial 47 finished with value: 0.7149192575861768 and parameters: {'subsample': 0.22935228775832767, 'dropout_rate': 0.5076851571944427, 'n_estimators': 352, 'learning_rate': 0.046521935229950455}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:00:48,468] Trial 48 finished with value: 0.7347594268140488 and parameters: {'subsample': 0.1004172298398558, 'dropout_rate': 0.5899705333542886, 'n_estimators': 192, 'learning_rate': 0.09072031695987003}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:00:49,878] Trial 49 finished with value: 0.7189126270858754 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.22429510456479168, 'n_estimators': 162, 'learning_rate': 0.035417181031780896}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:00:52,729] Trial 50 finished with value: 0.7179736599497251 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.30505070389836964, 'n_estimators': 264, 'learning_rate': 0.08395152382849014}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:00:56,009] Trial 51 finished with value: 0.7365837008274517 and parameters: {'subsample': 0.1422401972634589, 'dropout_rate': 0.42103437800441734, 'n_estimators': 306, 'learning_rate': 0.02490569756015621}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:00:59,787] Trial 52 finished with value: 0.7336644433661241 and parameters: {'subsample': 0.13446553100787184, 'dropout_rate': 0.3650414028894897, 'n_estimators': 325, 'learning_rate': 0.010085149840326754}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:01:05,160] Trial 53 finished with value: 0.7207747803979043 and parameters: {'subsample': 0.2478452933899453, 'dropout_rate': 0.3074105703752685, 'n_estimators': 410, 'learning_rate': 0.02098169255908478}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:01:09,054] Trial 54 finished with value: 0.7356252276798497 and parameters: {'subsample': 0.12886636459844406, 'dropout_rate': 0.4747292949581128, 'n_estimators': 363, 'learning_rate': 0.003802241983920464}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:01:12,232] Trial 55 finished with value: 0.7173992529717441 and parameters: {'subsample': 0.20218830483801442, 'dropout_rate': 0.423286821743516, 'n_estimators': 313, 'learning_rate': 0.02839198015036078}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:01:15,354] Trial 56 finished with value: 0.7306954596778986 and parameters: {'subsample': 0.14221640418806392, 'dropout_rate': 0.20726258482397952, 'n_estimators': 273, 'learning_rate': 0.014897416548086101}. Best is trial 28 with value: 0.74162050985486.

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:01:19,189] Trial 57 finished with value: 0.7370762393921734 and parameters: {'subsample': 0.10149143411861405, 'dropout_rate': 0.510494526556246, 'n_estimators': 337, 'learning_rate': 0.09978539397913937}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:01:21,276] Trial 58 finished with value: 0.7243577124199654 and parameters: {'subsample': 0.18094424024609052, 'dropout_rate': 0.668797085767497, 'n_estimators': 228, 'learning_rate': 0.09816381108016395}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:01:24,861] Trial 59 finished with value: 0.7370762393921734 and parameters: {'subsample': 0.10171829498369382, 'dropout_rate': 0.5190587240097809, 'n_estimators': 347, 'learning_rate': 0.09339322934480054}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:01:28,353] Trial 60 finished with value: 0.7217137475340547 and parameters: {'subsample': 0.22392091298087624, 'dropout_rate': 0.5846081323015373, 'n_estimators': 370, 'learning_rate': 0.08853749394073637}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:01:31,159] Trial 61 finished with value: 0.7370762393921734 and parameters: {'subsample': 0.106964452401597, 'dropout_rate': 0.9137032591710131, 'n_estimators': 351, 'learning_rate': 0.09338953238729536}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:01:35,723] Trial 62 finished with value: 0.7351154550784479 and parameters: {'subsample': 0.10594163089135693, 'dropout_rate': 0.5130343061825433, 'n_estimators': 402, 'learning_rate': 0.09266821097349769}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:01:40,662] Trial 63 finished with value: 0.7279074342260609 and parameters: {'subsample': 0.17458797397516695, 'dropout_rate': 0.5769390120224127, 'n_estimators': 427, 'learning_rate': 0.09677026496968014}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:01:44,086] Trial 64 finished with value: 0.6320961091409123 and parameters: {'subsample': 0.7632599340249784, 'dropout_rate': 0.4512404391776561, 'n_estimators': 334, 'learning_rate': 0.08698839628820304}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:01:46,645] Trial 65 finished with value: 0.7309718170198111 and parameters: {'subsample': 0.13329347877026815, 'dropout_rate': 0.3302234969055321, 'n_estimators': 290, 'learning_rate': 0.09880313133070402}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:01:51,785] Trial 66 finished with value: 0.7361372722560231 and parameters: {'subsample': 0.10041734071097298, 'dropout_rate': 0.5194325491060701, 'n_estimators': 457, 'learning_rate': 0.09977448020847997}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:01:55,725] Trial 67 finished with value: 0.7183163010986336 and parameters: {'subsample': 0.21067079438353736, 'dropout_rate': 0.6300671264802817, 'n_estimators': 384, 'learning_rate': 0.09491869250628704}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:01:58,976] Trial 68 finished with value: 0.7268999857921419 and parameters: {'subsample': 0.16895742485902565, 'dropout_rate': 0.9723670238493325, 'n_estimators': 351, 'learning_rate': 0.088257531672639}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:01,918] Trial 69 finished with value: 0.7199089795321035 and parameters: {'subsample': 0.2675480945868436, 'dropout_rate': 0.6742877948812134, 'n_estimators': 323, 'learning_rate': 0.09124693956316268}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:02:06,198] Trial 70 finished with value: 0.7370006601240149 and parameters: {'subsample': 0.12908972578800693, 'dropout_rate': 0.8429025687821614, 'n_estimators': 418, 'learning_rate': 0.050873486958066906}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:02:10,343] Trial 71 finished with value: 0.7346229165137262 and parameters: {'subsample': 0.11712592226971504, 'dropout_rate': 0.9283040385686381, 'n_estimators': 360, 'learning_rate': 0.09404485553295071}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 16:02:13,417] Trial 72 finished with value: 0.7268463255332441 and parameters: {'subsample': 0.1551192737796193, 'dropout_rate': 0.9176305878368808, 'n_estimators': 346, 'learning_rate': 0.08145092042986896}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:02:16,783] Trial 73 finished with value: 0.7227650339864954 and parameters: {'subsample': 0.18597033136891927, 'dropout_rate': 0.8911792137620391, 'n_estimators': 379, 'learning_rate': 0.0953664978913032}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:02:20,885] Trial 74 finished with value: 0.7351154550784479 and parameters: {'subsample': 0.10086780506047602, 'dropout_rate': 0.7510013881743404, 'n_estimators': 400, 'learning_rate': 0.09672009603319694}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 16:02:23,679] Trial 75 finished with value: 0.7308475419576734 and parameters: {'subsample': 0.12699942087463448, 'dropout_rate': 0.9740869122046054, 'n_estimators': 329, 'learning_rate': 0.04098863427371479}. Best is trial 28 with value: 0.74162050985486.

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 16:02:26,476] Trial 76 finished with value: 0.7298825872834425 and parameters: {'subsample': 0.1564795972551688, 'dropout_rate': 0.8139830353727877, 'n_estimators': 299, 'learning_rate': 0.09183466080256694}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:02:31,426] Trial 77 finished with value: 0.7192091582414908 and parameters: {'subsample': 0.20528870566266566, 'dropout_rate': 0.6981056962456518, 'n_estimators': 475, 'learning_rate': 0.08481051126539103}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:35,175] Trial 78 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.9132397120588486, 'dropout_rate': 0.9500484290456483, 'n_estimators': 447, 'learning_rate': 0.08882511375514734}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:02:40,419] Trial 79 finished with value: 0.7370352666666757 and parameters: {'subsample': 0.12316882586507066, 'dropout_rate': 0.8584043440906037, 'n_estimators': 370, 'learning_rate': 0.09745001223850905}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:44,231] Trial 80 finished with value: 0.7154200953708442 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.9003317461846495, 'n_estimators': 399, 'learning_rate': 0.09303295781666399}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:02:47,328] Trial 81 finished with value: 0.7378664609898158 and parameters: {'subsample': 0.12771380892606496, 'dropout_rate': 0.8658036880862092, 'n_estimators': 367, 'learning_rate': 0.099962737852032}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:02:50,090] Trial 82 finished with value: 0.7317144115624499 and parameters: {'subsample': 0.15816754431465238, 'dropout_rate': 0.877741231926985, 'n_estimators': 355, 'learning_rate': 0.09702417280150998}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:02:52,743] Trial 83 finished with value: 0.735603308670589 and parameters: {'subsample': 0.12485705742267929, 'dropout_rate': 0.9897530807623683, 'n_estimators': 338, 'learning_rate': 0.09979719808199436}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:02:55,649] Trial 84 finished with value: 0.69197583130158 and parameters: {'subsample': 0.5584624909113933, 'dropout_rate': 0.9099410481304606, 'n_estimators': 376, 'learning_rate': 0.09449733418125483}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:02:58,625] Trial 85 finished with value: 0.7210334322548937 and parameters: {'subsample': 0.18430133992220865, 'dropout_rate': 0.5608759099537627, 'n_estimators': 316, 'learning_rate': 0.046118625370362286}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:03:02,124] Trial 86 finished with value: 0.7363521052475189 and parameters: {'subsample': 0.15309209341249358, 'dropout_rate': 0.9466587881139311, 'n_estimators': 394, 'learning_rate': 0.09054173483658579}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:03:05,273] Trial 87 finished with value: 0.7369915696711917 and parameters: {'subsample': 0.10089753425111023, 'dropout_rate': 0.4490530340016638, 'n_estimators': 344, 'learning_rate': 0.07823986277139501}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 16:03:09,687] Trial 88 finished with value: 0.73740807667254 and parameters: {'subsample': 0.11999703567403837, 'dropout_rate': 0.4900833501953954, 'n_estimators': 419, 'learning_rate': 0.08220063324492037}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:14,153] Trial 89 finished with value: 0.7200893278509477 and parameters: {'subsample': 0.25667292111118717, 'dropout_rate': 0.5275020607411128, 'n_estimators': 437, 'learning_rate': 0.08208547139684774}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 16:03:18,414] Trial 90 finished with value: 0.7225416532113097 and parameters: {'subsample': 0.218516106759281, 'dropout_rate': 0.49021980206092486, 'n_estimators': 418, 'learning_rate': 0.07174948443325804}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:03:21,859] Trial 91 finished with value: 0.7354887173795271 and parameters: {'subsample': 0.12070374007632043, 'dropout_rate': 0.3845938740024235, 'n_estimators': 362, 'learning_rate': 0.06320723344161999}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:03:26,056] Trial 92 finished with value: 0.7235974123924032 and parameters: {'subsample': 0.1440331910545538, 'dropout_rate': 0.6097020888597454, 'n_estimators': 409, 'learning_rate': 0.0866479087292009}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:03:30,306] Trial 93 finished with value: 0.7361372722560231 and parameters: {'subsample': 0.11629067382185615, 'dropout_rate': 0.9645771063565084, 'n_estimators': 427, 'learning_rate': 0.09250180305252}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:03:35,033] Trial 94 finished with value: 0.7279074342260609 and parameters: {'subsample': 0.1766297349025856, 'dropout_rate': 0.5532163155933437, 'n_estimators': 388, 'learning_rate': 0.07525464064028349}. Best is trial 28 with value: 0.74162050985486.

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 16:03:40,075] Trial 95 finished with value: 0.7328181485117751 and parameters: {'subsample': 0.14240044374788033, 'dropout_rate': 0.9283106717319588, 'n_estimators': 462, 'learning_rate': 0.09765588873855385}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 16:03:42,910] Trial 96 finished with value: 0.7212918066057846 and parameters: {'subsample': 0.194895706993773, 'dropout_rate': 0.9965842349833566, 'n_estimators': 300, 'learning_rate': 0.03563352439903737}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:03:47,290] Trial 97 finished with value: 0.7222051501113906 and parameters: {'subsample': 0.16750883128661836, 'dropout_rate': 0.48408931906180186, 'n_estimators': 373, 'learning_rate': 0.09982539002325702}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 16:03:50,805] Trial 98 finished with value: 0.6854567794921336 and parameters: {'subsample': 0.6340595518294957, 'dropout_rate': 0.4449944120022278, 'n_estimators': 333, 'learning_rate': 0.08962941873034379}. Best is trial 28 with value: 0.74162050985486.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827

[I 2024-04-14 16:03:53,446] A new study created in memory with name: no-name-985e23f0-0d4f-4b8e-b376-3a56161d7310

Fold 5 C-index: 0.647887323943662
[I 2024-04-14 16:03:53,424] Trial 99 finished with value: 0.7351568800991604 and parameters: {'subsample': 0.10063504139773932, 'dropout_rate': 0.5014216586223145, 'n_estimators': 278, 'learning_rate': 0.09459285564746922}. Best is trial 28 with value: 0.74162050985486.


* Best trial for C-index:
 FrozenTrial(number=28, state=TrialState.COMPLETE, values=[0.74162050985486], datetime_start=datetime.datetime(2024, 4, 14, 15, 59, 41, 512513), datetime_complete=datetime.datetime(2024, 4, 14, 15, 59, 44, 673708), params={'subsample': 0.10061641287468016, 'dropout_rate': 0.9261509226223655, 'n_estimators': 274, 'learning_rate': 0.04202399206134448}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=28, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10061641287468016, 'dropout_rate': 0.9261509226223655, 'n_estimators': 274, 'learning_rate': 0.04202399206134448}


* Best Score for C-index:
 0.74162050985486

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18504584755520848
Fold 2 IBS: 0.263946415780978
Fold 3 IBS: 0.1617903636180167
Fold 4 IBS: 0.2600787216130082
Fold 5 IBS: 0.23318480871469416
[I 2024-04-14 16:03:54,476] Trial 0 finished with value: 0.22080923145638112 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.20370621643796663
Fold 2 IBS: 0.3014080683205247
Fold 3 IBS: 0.17042892249188574
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.27370157532625616
[I 2024-04-14 16:04:00,214] Trial 1 finished with value: 0.2530198867111848 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.19309554280636426
Fold 2 IBS: 0.30090488415559263
Fold 3 IBS: 0.1653332066108254
Fold 4 IBS: 0.31368208313434126
Fold 5 IBS: 0.26490979029895373
[I 2024-04-14 16:04:01,364] Trial 2 finished with value: 0.24758510140121545 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.19845564193720544
Fold 2 IBS: 0.29867185430046916
Fold 3 IBS: 0.16607224064552437
Fold 4 IBS: 0.31117164271618164
Fold 5 IBS: 0.26803683949365764
[I 2024-04-14 16:04:03,519] Trial 3 finished with value: 0.24848164381860766 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.19008093760022654
Fold 2 IBS: 0.3006292211879915
Fold 3 IBS: 0.18398085503045797
Fold 4 IBS: 0.31302496706623006
Fold 5 IBS: 0.26908387741821566
[I 2024-04-14 16:04:07,239] Trial 4 finished with value: 0.25135997166062435 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.2034038137478441
Fold 2 IBS: 0.3014078956744048
Fold 3 IBS: 0.16987803315182726
Fold 4 IBS: 0.31585217062420684
Fold 5 IBS: 0.27369201709429525
[I 2024-04-14 16:04:11,141] Trial 5 finished with value: 0.2528467860585156 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.1829350490073511
Fold 2 IBS: 0.22574908076349612
Fold 3 IBS: 0.16688500534550946
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.21906832093288123
[I 2024-04-14 16:04:12,555] Trial 6 finished with value: 0.2038699731037017 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2038699731037017.
Fold 1 IBS: 0.19171533392644077
Fold 2 IBS: 0.20303779786155224
Fold 3 IBS: 0.17884668693475606
Fold 4 IBS: 0.20856968304886764
Fold 5 IBS: 0.211118754013436
[I 2024-04-14 16:04:12,901] Trial 7 finished with value: 0.19865765115701053 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18555056703963912
Fold 2 IBS: 0.27502505757765827
Fold 3 IBS: 0.1610534980201046
Fold 4 IBS: 0.26090944510806957
Fold 5 IBS: 0.2349744292756046
[I 2024-04-14 16:04:14,380] Trial 8 finished with value: 0.22350259940421524 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.20141041035693819
Fold 2 IBS: 0.3014080117730072
Fold 3 IBS: 0.1827239722426296
Fold 4 IBS: 0.31585254695670684
Fold 5 IBS: 0.2759459715593507
[I 2024-04-14 16:04:18,363] Trial 9 finished with value: 0.2554681825777265 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22091211268741265
Fold 3 IBS: 0.20387901759065918
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21780913258638765
[I 2024-04-14 16:04:18,650] Trial 10 finished with value: 0.21607415429104124 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.21347906149386553
Fold 2 IBS: 0.22105802807283764
Fold 3 IBS: 0.2036691246434108
Fold 4 IBS: 0.22441463958947244
Fold 5 IBS: 0.21777799603810094
[I 2024-04-14 16:04:18,869] Trial 11 finished with value: 0.21607976996753747 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18668302483732233
Fold 2 IBS: 0.297403850587758
Fold 3 IBS: 0.16597777897100402
Fold 4 IBS: 0.29519467653629033
Fold 5 IBS: 0.25346374715090736
[I 2024-04-14 16:04:19,514] Trial 12 finished with value: 0.23974461561665641 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19280005315897206
Fold 2 IBS: 0.2974213595064474
Fold 3 IBS: 0.17117639615033295
Fold 4 IBS: 0.30578737203308676
Fold 5 IBS: 0.25431185381872007
[I 2024-04-14 16:04:22,001] Trial 13 finished with value: 0.24429940693351188 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19784216344977562
Fold 2 IBS: 0.20506180854560294
Fold 3 IBS: 0.18635045949578385
Fold 4 IBS: 0.21499223626865088
Fold 5 IBS: 0.21149042228501566
[I 2024-04-14 16:04:22,603] Trial 14 finished with value: 0.20314741800896577 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2102363624015555
Fold 2 IBS: 0.21734365927334173
Fold 3 IBS: 0.20020119375698603
Fold 4 IBS: 0.22202144488912645
Fold 5 IBS: 0.21659611545289936
[I 2024-04-14 16:04:23,118] Trial 15 finished with value: 0.2132797551547818 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2039212844188623
Fold 2 IBS: 0.2103474992415337
Fold 3 IBS: 0.19339791850328025
Fold 4 IBS: 0.21877297557249897
Fold 5 IBS: 0.21360848363027263
[I 2024-04-14 16:04:23,551] Trial 16 finished with value: 0.20800963227328956 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18288342929944057
Fold 2 IBS: 0.23926430161132384
Fold 3 IBS: 0.16665249308120655
Fold 4 IBS: 0.2362841280803267
Fold 5 IBS: 0.22353483274970617
[I 2024-04-14 16:04:24,372] Trial 17 finished with value: 0.20972383696440078 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18068058395328543
Fold 2 IBS: 0.24024111720982294
Fold 3 IBS: 0.16255955996419777
Fold 4 IBS: 0.22670032118705843
Fold 5 IBS: 0.22295397631420336
[I 2024-04-14 16:04:26,995] Trial 18 finished with value: 0.2066271117257136 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19698215794343982
Fold 2 IBS: 0.2023431594465361

Fold 3 IBS: 0.1783999568257794
Fold 4 IBS: 0.20183880070145502
Fold 5 IBS: 0.2121882393181561
[I 2024-04-14 16:04:27,362] Trial 19 finished with value: 0.19835046284707328 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19835046284707328.
Fold 1 IBS: 0.1922099266697023
Fold 2 IBS: 0.20500626401911293
Fold 3 IBS: 0.1819421294378562
Fold 4 IBS: 0.20531861803436055
Fold 5 IBS: 0.21298081915188694
[I 2024-04-14 16:04:27,702] Trial 20 finished with value: 0.1994915514625838 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19835046284707328.
Fold 1 IBS: 0.20013778642266292
Fold 2 IBS: 0.20393569161683953
Fold 3 IBS: 0.18712698518091442
Fold 4 IBS: 0.20944879242499856
Fold 5 IBS: 0.21303933620208118
[I 2024-04-14 16:04:28,017] Trial 21 finished with value: 0.20273771836949933 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19835046284707328.
Fold 1 IBS: 0.21339362387111827
Fold 2 IBS: 0.22073279019144837
Fold 3 IBS: 0.20313821183683503
Fold 4 IBS: 0.22386245547893124
Fold 5 IBS: 0.2175077980822652
[I 2024-04-14 16:04:28,231] Trial 22 finished with value: 0.21572697589211964 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19835046284707328.
Fold 1 IBS: 0.1761616635250337
Fold 2 IBS: 0.23394437917728408
Fold 3 IBS: 0.16561486282339552
Fold 4 IBS: 0.22557670629357213
Fold 5 IBS: 0.22623410400791188
[I 2024-04-14 16:04:29,133] Trial 23 finished with value: 0.20550634316543945 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19835046284707328.
Fold 1 IBS: 0.18534907002924922
Fold 2 IBS: 0.2124184957753865
Fold 3 IBS: 0.16839399220873313
Fold 4 IBS: 0.21192615623352185
Fold 5 IBS: 0.21327382867550682
[I 2024-04-14 16:04:29,501] Trial 24 finished with value: 0.19827230858447947 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.18388802734235174
Fold 2 IBS: 0.2613406847101467
Fold 3 IBS: 0.16154029812386547
Fold 4 IBS: 0.2530341774375341
Fold 5 IBS: 0.22930188107334332
[I 2024-04-14 16:04:29,951] Trial 25 finished with value: 0.21782101373744828 and parameters: {'subsample': 0.41513882888547626, 'dropout_rate': 0.92193566363172, 'n_estimators': 70, 'learning_rate': 0.08579428551722094}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.18959239144142057
Fold 2 IBS: 0.2985918938567073
Fold 3 IBS: 0.16263813544153358
Fold 4 IBS: 0.3060194232926818
Fold 5 IBS: 0.2556802208583101
[I 2024-04-14 16:04:30,782] Trial 26 finished with value: 0.24250441297813063 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9863699266040719, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.18798017921022403
Fold 2 IBS: 0.30140793076134154
Fold 3 IBS: 0.2638425153760916
Fold 4 IBS: 0.31584947980565353
Fold 5 IBS: 0.2814970895229344
[I 2024-04-14 16:04:34,490] Trial 27 finished with value: 0.27011543893524903 and parameters: {'subsample': 0.26021450312326855, 'dropout_rate': 0.9019594475838296, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.19607520823560468
Fold 2 IBS: 0.30021973088050485
Fold 3 IBS: 0.16582318707762056
Fold 4 IBS: 0.3115140810699333
Fold 5 IBS: 0.26099002390515563
[I 2024-04-14 16:04:36,133] Trial 28 finished with value: 0.2469244462337638 and parameters: {'subsample': 0.5971669636685615, 'dropout_rate': 0.7292365612928325, 'n_estimators': 236, 'learning_rate': 0.046726352221374515}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.1835487795710174
Fold 2 IBS: 0.28472280021030205
Fold 3 IBS: 0.16185774322786736
Fold 4 IBS: 0.2713973172083697
Fold 5 IBS: 0.23947299482188275
[I 2024-04-14 16:04:36,754] Trial 29 finished with value: 0.22819992700788783 and parameters: {'subsample': 0.3457177033536965, 'dropout_rate': 0.528113503868086, 'n_estimators': 97, 'learning_rate': 0.08423642007181871}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.17535954590969488
Fold 2 IBS: 0.2710458939557432
Fold 3 IBS: 0.16548011051002756
Fold 4 IBS: 0.2773300532393083
Fold 5 IBS: 0.2400789372188414
[I 2024-04-14 16:04:37,743] Trial 30 finished with value: 0.2258589081667231 and parameters: {'subsample': 0.21287332299822773, 'dropout_rate': 0.8300645798351977, 'n_estimators': 136, 'learning_rate': 0.05802531255595394}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.1926615629336458
Fold 2 IBS: 0.20244043279658744
Fold 3 IBS: 0.181359327071659
Fold 4 IBS: 0.2027098002202131
Fold 5 IBS: 0.2126106509263375
[I 2024-04-14 16:04:38,208] Trial 31 finished with value: 0.19835635478968855 and parameters: {'subsample': 0.15465256682910847, 'dropout_rate': 0.7665254119155692, 'n_estimators': 42, 'learning_rate': 0.04796619662341173}. Best is trial 24 with value: 0.19827230858447947.
Fold 1 IBS: 0.18680519861628095
Fold 2 IBS: 0.20534906897611818
Fold 3 IBS: 0.16824752824640996
Fold 4 IBS: 0.19602835489490866
Fold 5 IBS: 0.21551715623031892
[I 2024-04-14 16:04:38,955] Trial 32 finished with value: 0.19438946139280736 and parameters: {'subsample': 0.10342193656652618, 'dropout_rate': 0.9389584836732486, 'n_estimators': 75, 'learning_rate': 0.04909887443838165}. Best is trial 32 with value: 0.19438946139280736.
Fold 1 IBS: 0.17926993425191953
Fold 2 IBS: 0.20738418246324197
Fold 3 IBS: 0.16747303495958266
Fold 4 IBS: 0.19216268268169184
Fold 5 IBS: 0.21889823419400425
[I 2024-04-14 16:04:39,817] Trial 33 finished with value: 0.19303761371008804 and parameters: {'subsample': 0.10120824695002664, 'dropout_rate': 0.9165491191113839, 'n_estimators': 84, 'learning_rate': 0.05193153712447138}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18338138251453634
Fold 2 IBS: 0.22268497163840112
Fold 3 IBS: 0.16472450951449746
Fold 4 IBS: 0.21677950639715615
Fold 5 IBS: 0.21758945445294195
[I 2024-04-14 16:04:40,608] Trial 34 finished with value: 0.2010319649035066 and parameters: {'subsample': 0.27605512644200536, 'dropout_rate': 0.9367464353144932, 'n_estimators': 83, 'learning_rate': 0.053958561792099055}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18751187280563467
Fold 2 IBS: 0.2963487446427413
Fold 3 IBS: 0.18638505635108912
Fold 4 IBS: 0.30309261968404877
Fold 5 IBS: 0.26065728506195185
[I 2024-04-14 16:04:42,054] Trial 35 finished with value: 0.24679911570909313 and parameters: {'subsample': 0.18803636578765642, 'dropout_rate': 0.9999704558613048, 'n_estimators': 168, 'learning_rate': 0.06936375971172346}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.17962396554242877
Fold 2 IBS: 0.23815090757764804
Fold 3 IBS: 0.1647102267833534
Fold 4 IBS: 0.19081267019358134
Fold 5 IBS: 0.23419680155692701
[I 2024-04-14 16:04:42,923] Trial 36 finished with value: 0.20149891433078765 and parameters: {'subsample': 0.10993892506507363, 'dropout_rate': 0.8736174627174981, 'n_estimators': 108, 'learning_rate': 0.06500327084691943}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.19222221138861062
Fold 2 IBS: 0.20341648411240412
Fold 3 IBS: 0.1828291205365253
Fold 4 IBS: 0.20870273718662988
Fold 5 IBS: 0.2115926907915131
[I 2024-04-14 16:04:43,252] Trial 37 finished with value: 0.19975264880313662 and parameters: {'subsample': 0.24452105971925578, 'dropout_rate': 0.8608568379956052, 'n_estimators': 22, 'learning_rate': 0.07677405503763898}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.17653011849570036
Fold 2 IBS: 0.21782597051745478

Fold 3 IBS: 0.1685675012002108
Fold 4 IBS: 0.20909390394783278
Fold 5 IBS: 0.23159412949218366
[I 2024-04-14 16:04:45,106] Trial 38 finished with value: 0.20072232473067647 and parameters: {'subsample': 0.10045702238474481, 'dropout_rate': 0.13272164755980653, 'n_estimators': 197, 'learning_rate': 0.034653901878161156}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1763284024432531
Fold 2 IBS: 0.24237849570630937
Fold 3 IBS: 0.16838621148605842
Fold 4 IBS: 0.23433215637540045
Fold 5 IBS: 0.23218136784009083
[I 2024-04-14 16:04:46,013] Trial 39 finished with value: 0.21072132677022243 and parameters: {'subsample': 0.167666800643059, 'dropout_rate': 0.9404469958471148, 'n_estimators': 122, 'learning_rate': 0.05575307634287385}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1835607046663353
Fold 2 IBS: 0.20550258426704343
Fold 3 IBS: 0.17033281078924473
Fold 4 IBS: 0.20234480009040523
Fold 5 IBS: 0.21318875015485583
[I 2024-04-14 16:04:46,504] Trial 40 finished with value: 0.19498592999357692 and parameters: {'subsample': 0.2965781974768929, 'dropout_rate': 0.27073406810212547, 'n_estimators': 63, 'learning_rate': 0.04938832582545226}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18501835939885972
Fold 2 IBS: 0.21279759898814296
Fold 3 IBS: 0.16848234290781128
Fold 4 IBS: 0.2118426517106074
Fold 5 IBS: 0.21426827206989704
[I 2024-04-14 16:04:47,010] Trial 41 finished with value: 0.19848184501506366 and parameters: {'subsample': 0.45250479767498475, 'dropout_rate': 0.3148196375868446, 'n_estimators': 67, 'learning_rate': 0.051104586008163616}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18203177294187226
Fold 2 IBS: 0.22782754293742905
Fold 3 IBS: 0.1632339437132109
Fold 4 IBS: 0.22886064096987924
Fold 5 IBS: 0.2200400820824444
[I 2024-04-14 16:04:47,584] Trial 42 finished with value: 0.20439879652896717 and parameters: {'subsample': 0.5528592548338757, 'dropout_rate': 0.2592678819776844, 'n_estimators': 81, 'learning_rate': 0.060074363009380766}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.20118309421870142
Fold 2 IBS: 0.2088783881862968
Fold 3 IBS: 0.18987722690446193
Fold 4 IBS: 0.21487800434261742
Fold 5 IBS: 0.21334647650684385
[I 2024-04-14 16:04:47,929] Trial 43 finished with value: 0.20563263803178428 and parameters: {'subsample': 0.3096634576801395, 'dropout_rate': 0.43449856801087844, 'n_estimators': 21, 'learning_rate': 0.04987534978342077}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1968133954794308
Fold 2 IBS: 0.20363402360299165
Fold 3 IBS: 0.17983341765342395
Fold 4 IBS: 0.20763495219753336
Fold 5 IBS: 0.21164565889520867
[I 2024-04-14 16:04:48,476] Trial 44 finished with value: 0.1999122895657177 and parameters: {'subsample': 0.25193606019150794, 'dropout_rate': 0.9420860580138689, 'n_estimators': 53, 'learning_rate': 0.035815869904080436}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18457109843072536
Fold 2 IBS: 0.29221473532974757
Fold 3 IBS: 0.16560705544603085
Fold 4 IBS: 0.2971477262891639
Fold 5 IBS: 0.2551451910113016
[I 2024-04-14 16:04:50,024] Trial 45 finished with value: 0.23893716130139384 and parameters: {'subsample': 0.22120310251842165, 'dropout_rate': 0.22060355945188226, 'n_estimators': 174, 'learning_rate': 0.06466280247158755}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.21236817006678255
Fold 2 IBS: 0.22009626927100215
Fold 3 IBS: 0.20294002727897903
Fold 4 IBS: 0.22334601909369778
Fold 5 IBS: 0.21744023437275475
[I 2024-04-14 16:04:50,330] Trial 46 finished with value: 0.21523814401664326 and parameters: {'subsample': 0.2889770552152724, 'dropout_rate': 0.4861231033029888, 'n_estimators': 4, 'learning_rate': 0.024992652172925307}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.17371666656354298
Fold 2 IBS: 0.2227265427313125
Fold 3 IBS: 0.1677638943896912
Fold 4 IBS: 0.19640160836707157
Fold 5 IBS: 0.22208941055217546
[I 2024-04-14 16:04:51,082] Trial 47 finished with value: 0.19653962452075874 and parameters: {'subsample': 0.16636507062504322, 'dropout_rate': 0.8779847546321204, 'n_estimators': 111, 'learning_rate': 0.04627922322472232}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.17698250496334314
Fold 2 IBS: 0.2712998737125614
Fold 3 IBS: 0.16705480188064725
Fold 4 IBS: 0.23730560526595004
Fold 5 IBS: 0.23961996458094884
[I 2024-04-14 16:04:52,001] Trial 48 finished with value: 0.21845255008069014 and parameters: {'subsample': 0.15612985788996714, 'dropout_rate': 0.8767697806036618, 'n_estimators': 114, 'learning_rate': 0.07309667362367553}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.19017412875792714
Fold 2 IBS: 0.30116449436178705
Fold 3 IBS: 0.18712727921488045
Fold 4 IBS: 0.3147668026984696
Fold 5 IBS: 0.2724912891761605
[I 2024-04-14 16:04:57,140] Trial 49 finished with value: 0.25314479884184493 and parameters: {'subsample': 0.3184068433782157, 'dropout_rate': 0.332056795636834, 'n_estimators': 272, 'learning_rate': 0.055793665880233545}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1820149865336656
Fold 2 IBS: 0.22606882162885394
Fold 3 IBS: 0.16424324536186266
Fold 4 IBS: 0.2136169181542773
Fold 5 IBS: 0.21754524957994423
[I 2024-04-14 16:04:58,740] Trial 50 finished with value: 0.20069784425172074 and parameters: {'subsample': 0.38208318082180337, 'dropout_rate': 0.8307509046283464, 'n_estimators': 95, 'learning_rate': 0.046066451728728156}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18780796098863967
Fold 2 IBS: 0.20394415475005334
Fold 3 IBS: 0.17316096983922113
Fold 4 IBS: 0.19578308004808476
Fold 5 IBS: 0.21462197659662766
[I 2024-04-14 16:05:00,668] Trial 51 finished with value: 0.1950636284445253 and parameters: {'subsample': 0.12135448139256556, 'dropout_rate': 0.9065849750626525, 'n_estimators': 56, 'learning_rate': 0.05204426163128646}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18006887614011985
Fold 2 IBS: 0.20502051999350268
Fold 3 IBS: 0.1686981498967985
Fold 4 IBS: 0.19773946156094835
Fold 5 IBS: 0.21372462507338852
[I 2024-04-14 16:05:02,079] Trial 52 finished with value: 0.19305032653295157 and parameters: {'subsample': 0.1810597283598112, 'dropout_rate': 0.8848004617616638, 'n_estimators': 65, 'learning_rate': 0.05224169698208609}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.17645005522615637
Fold 2 IBS: 0.2646925041271424
Fold 3 IBS: 0.1676845850450743
Fold 4 IBS: 0.253694949955965
Fold 5 IBS: 0.23831929653550152
[I 2024-04-14 16:05:03,911] Trial 53 finished with value: 0.2201682781779679 and parameters: {'subsample': 0.18126422617156043, 'dropout_rate': 0.8429888451700271, 'n_estimators': 149, 'learning_rate': 0.0514420485274077}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1774889110247305
Fold 2 IBS: 0.20728240656364363
Fold 3 IBS: 0.16961480887442856
Fold 4 IBS: 0.19940941516689872
Fold 5 IBS: 0.22081984572557967
[I 2024-04-14 16:05:04,876] Trial 54 finished with value: 0.19492307747105622 and parameters: {'subsample': 0.13391056766821002, 'dropout_rate': 0.9526163348507636, 'n_estimators': 93, 'learning_rate': 0.04704895502445404}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1786166295857935
Fold 2 IBS: 0.2075979618859867
Fold 3 IBS: 0.1700935409037084
Fold 4 IBS: 0.19879645817464067
Fold 5 IBS: 0.21947597845507816
[I 2024-04-14 16:05:05,494] Trial 55 finished with value: 0.19491611380104149 and parameters: {'subsample': 0.12995391922746025, 'dropout_rate': 0.9436469345986359, 'n_estimators': 77, 'learning_rate': 0.053343545412390905}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1828833953236436
Fold 2 IBS: 0.2062807392651492
Fold 3 IBS: 0.1713039039621801
Fold 4 IBS: 0.20552329164189845
Fold 5 IBS: 0.21264875119979887
[I 2024-04-14 16:05:06,089] Trial 56 finished with value: 0.19572801627853403 and parameters: {'subsample': 0.22893377767290243, 'dropout_rate': 0.9635210313911957, 'n_estimators': 83, 'learning_rate': 0.03661052808954925}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1792538104579256
Fold 2 IBS: 0.2437638037379017

Fold 3 IBS: 0.16822611367610577
Fold 4 IBS: 0.2337714954670114
Fold 5 IBS: 0.23499642019553307
[I 2024-04-14 16:05:06,966] Trial 57 finished with value: 0.2120023287068955 and parameters: {'subsample': 0.13688965562363797, 'dropout_rate': 0.9526896712757614, 'n_estimators': 130, 'learning_rate': 0.055651931121615976}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.20180718166088418
Fold 2 IBS: 0.20823056304136786
Fold 3 IBS: 0.19148854447397767
Fold 4 IBS: 0.2174086350391278
Fold 5 IBS: 0.21280121650803058
[I 2024-04-14 16:05:07,315] Trial 58 finished with value: 0.2063472281446776 and parameters: {'subsample': 0.7132233145884603, 'dropout_rate': 0.7590040418023142, 'n_estimators': 30, 'learning_rate': 0.03238483343413252}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18523772398626553
Fold 2 IBS: 0.20192659760289666
Fold 3 IBS: 0.17581399422575117
Fold 4 IBS: 0.2042588924101933
Fold 5 IBS: 0.21198594062334492
[I 2024-04-14 16:05:07,965] Trial 59 finished with value: 0.1958446297696903 and parameters: {'subsample': 0.19278782699530245, 'dropout_rate': 0.8079545528980361, 'n_estimators': 85, 'learning_rate': 0.028837933202626346}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.17104580942385206
Fold 2 IBS: 0.2591717928881219
Fold 3 IBS: 0.1653885228057337
Fold 4 IBS: 0.2431850855716636
Fold 5 IBS: 0.2416347445590348
[I 2024-04-14 16:05:09,597] Trial 60 finished with value: 0.2160851910496812 and parameters: {'subsample': 0.1338607058810486, 'dropout_rate': 0.6781214551233278, 'n_estimators': 191, 'learning_rate': 0.0446898818239094}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.18121569554089587
Fold 2 IBS: 0.20491106523989283
Fold 3 IBS: 0.16983376487163176
Fold 4 IBS: 0.19383103355174774
Fold 5 IBS: 0.2160139939508865
[I 2024-04-14 16:05:10,173] Trial 61 finished with value: 0.19316111063101093 and parameters: {'subsample': 0.1283694581512807, 'dropout_rate': 0.8932397829998899, 'n_estimators': 65, 'learning_rate': 0.05206626611796866}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1808514257068909
Fold 2 IBS: 0.20567433113456862
Fold 3 IBS: 0.17099894446172467
Fold 4 IBS: 0.19532198171365325
Fold 5 IBS: 0.21378246367884865
[I 2024-04-14 16:05:10,684] Trial 62 finished with value: 0.19332582933913722 and parameters: {'subsample': 0.13977816691885722, 'dropout_rate': 0.9005150901450276, 'n_estimators': 64, 'learning_rate': 0.04911317839549217}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.2057500796011461
Fold 2 IBS: 0.210339576908909
Fold 3 IBS: 0.19078271807187708
Fold 4 IBS: 0.21446568260035975
Fold 5 IBS: 0.21448741451800749
[I 2024-04-14 16:05:10,956] Trial 63 finished with value: 0.2071650943400599 and parameters: {'subsample': 0.14415942232117435, 'dropout_rate': 0.8994920863712805, 'n_estimators': 17, 'learning_rate': 0.057643716488773436}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.1992435475888555
Fold 2 IBS: 0.20515988219818393
Fold 3 IBS: 0.18608577523542474
Fold 4 IBS: 0.20884432643793274
Fold 5 IBS: 0.2123090034987794
[I 2024-04-14 16:05:11,327] Trial 64 finished with value: 0.20232850699183524 and parameters: {'subsample': 0.10180662017343259, 'dropout_rate': 0.9591055345325767, 'n_estimators': 36, 'learning_rate': 0.03929492532815135}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.175005710045105
Fold 2 IBS: 0.21509793054636944
Fold 3 IBS: 0.16611312629904115
Fold 4 IBS: 0.20541330329644883
Fold 5 IBS: 0.2179086271384639
[I 2024-04-14 16:05:12,079] Trial 65 finished with value: 0.19590773946508566 and parameters: {'subsample': 0.19730494385673214, 'dropout_rate': 0.9166529747583585, 'n_estimators': 103, 'learning_rate': 0.04305914063121836}. Best is trial 33 with value: 0.19303761371008804.
Fold 1 IBS: 0.17733955130649104
Fold 2 IBS: 0.20921496336925344
Fold 3 IBS: 0.1669796231531542
Fold 4 IBS: 0.19480728769198255
Fold 5 IBS: 0.2156491938738671
[I 2024-04-14 16:05:12,643] Trial 66 finished with value: 0.19279812387894965 and parameters: {'subsample': 0.1743050319704076, 'dropout_rate': 0.863517260153889, 'n_estimators': 74, 'learning_rate': 0.05374862600189621}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.17843035913749233
Fold 2 IBS: 0.2071264865428685
Fold 3 IBS: 0.16772324150213183
Fold 4 IBS: 0.20289194688810902
Fold 5 IBS: 0.21439274841230535
[I 2024-04-14 16:05:13,215] Trial 67 finished with value: 0.19411295649658142 and parameters: {'subsample': 0.23855948311312114, 'dropout_rate': 0.8497860417192638, 'n_estimators': 71, 'learning_rate': 0.05222811059922317}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.20431540437655768
Fold 2 IBS: 0.30140468063229253
Fold 3 IBS: 0.2570383479720521
Fold 4 IBS: 0.31580640083015044
Fold 5 IBS: 0.27849140895855223
[I 2024-04-14 16:05:16,938] Trial 68 finished with value: 0.27141124855392096 and parameters: {'subsample': 0.23615226030223976, 'dropout_rate': 0.8111460621600243, 'n_estimators': 371, 'learning_rate': 0.058889111230423924}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.17980104641063985
Fold 2 IBS: 0.29057903608678615
Fold 3 IBS: 0.18104733730826839
Fold 4 IBS: 0.2866827437370125
Fold 5 IBS: 0.25319898364291865
[I 2024-04-14 16:05:18,285] Trial 69 finished with value: 0.23826182943712512 and parameters: {'subsample': 0.1757266603381627, 'dropout_rate': 0.8543666590430856, 'n_estimators': 165, 'learning_rate': 0.06320971942184304}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.18401658208877172
Fold 2 IBS: 0.20353677542394039
Fold 3 IBS: 0.17051454277443648
Fold 4 IBS: 0.2024765180911247
Fold 5 IBS: 0.211800088437674
[I 2024-04-14 16:05:18,668] Trial 70 finished with value: 0.19446890136318945 and parameters: {'subsample': 0.20938426224411552, 'dropout_rate': 0.7297543173987021, 'n_estimators': 43, 'learning_rate': 0.06827725256730752}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.18295035168107582
Fold 2 IBS: 0.20402651713454154
Fold 3 IBS: 0.16966503579491465
Fold 4 IBS: 0.20260336891004424
Fold 5 IBS: 0.21206581247342246
[I 2024-04-14 16:05:19,092] Trial 71 finished with value: 0.19426221719879974 and parameters: {'subsample': 0.21112454294543329, 'dropout_rate': 0.7281173223881637, 'n_estimators': 44, 'learning_rate': 0.06973455759352304}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.17878478908890855
Fold 2 IBS: 0.22525274772480877
Fold 3 IBS: 0.16763731229082318
Fold 4 IBS: 0.19460133187802256
Fold 5 IBS: 0.22283970518270843
[I 2024-04-14 16:05:19,578] Trial 72 finished with value: 0.1978231772330543 and parameters: {'subsample': 0.15604862420445412, 'dropout_rate': 0.8901402491105642, 'n_estimators': 68, 'learning_rate': 0.0792265383317001}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.2077236756909544
Fold 2 IBS: 0.21474710094075666
Fold 3 IBS: 0.1967650251939208
Fold 4 IBS: 0.21994814513801328
Fold 5 IBS: 0.21484425248309438
[I 2024-04-14 16:05:19,868] Trial 73 finished with value: 0.21080563988934792 and parameters: {'subsample': 0.2679692101418073, 'dropout_rate': 0.8193702681952173, 'n_estimators': 11, 'learning_rate': 0.048891538961434285}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.1851957642087419
Fold 2 IBS: 0.21225789352906302
Fold 3 IBS: 0.17122710808665048
Fold 4 IBS: 0.21463416721467501
Fold 5 IBS: 0.21333331359594804
[I 2024-04-14 16:05:20,271] Trial 74 finished with value: 0.19932964932701572 and parameters: {'subsample': 0.7948212261000067, 'dropout_rate': 0.7581832774542927, 'n_estimators': 46, 'learning_rate': 0.07149770909339206}. Best is trial 66 with value: 0.19279812387894965.
Fold 1 IBS: 0.18390562856392695
Fold 2 IBS: 0.20567777352142447
Fold 3 IBS: 0.17140934913211425
Fold 4 IBS: 0.18844235887801652
Fold 5 IBS: 0.21259390769940248
[I 2024-04-14 16:05:20,632] Trial 75 finished with value: 0.19240580355897693 and parameters: {'subsample': 0.17893165130868519, 'dropout_rate': 0.8569541058357456, 'n_estimators': 34, 'learning_rate': 0.09037100397054215}. Best is trial 75 with value: 0.19240580355897693.
Fold 1 IBS: 0.1874845979207037
Fold 2 IBS: 0.20228055234323383
Fold 3 IBS: 0.17614530912073678

Fold 4 IBS: 0.19977802798795471
Fold 5 IBS: 0.21147728525732398
[I 2024-04-14 16:05:21,029] Trial 76 finished with value: 0.1954331545259906 and parameters: {'subsample': 0.2401639575567464, 'dropout_rate': 0.7857326186782545, 'n_estimators': 28, 'learning_rate': 0.08898292294449694}. Best is trial 75 with value: 0.19240580355897693.
Fold 1 IBS: 0.17686859585016973
Fold 2 IBS: 0.21612375928723943
Fold 3 IBS: 0.16351449690372113
Fold 4 IBS: 0.20921833604228476
Fold 5 IBS: 0.21934697817438564
[I 2024-04-14 16:05:21,509] Trial 77 finished with value: 0.19701443325156015 and parameters: {'subsample': 0.20835315159322065, 'dropout_rate': 0.6981056962456518, 'n_estimators': 55, 'learning_rate': 0.08671273256255693}. Best is trial 75 with value: 0.19240580355897693.
Fold 1 IBS: 0.1790517521200231
Fold 2 IBS: 0.20778503734954273
Fold 3 IBS: 0.1687165120258161
Fold 4 IBS: 0.1864366058034224
Fold 5 IBS: 0.21459658176413984
[I 2024-04-14 16:05:21,863] Trial 78 finished with value: 0.19131729781258883 and parameters: {'subsample': 0.17910269140503615, 'dropout_rate': 0.8516991920191342, 'n_estimators': 36, 'learning_rate': 0.09808413258788978}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.18081337969148692
Fold 2 IBS: 0.2976413831012317
Fold 3 IBS: 0.19240321832262472
Fold 4 IBS: 0.296968386742462
Fold 5 IBS: 0.25873375484144767
[I 2024-04-14 16:05:22,724] Trial 79 finished with value: 0.24531202453985063 and parameters: {'subsample': 0.17586806424589277, 'dropout_rate': 0.8551094005633922, 'n_estimators': 120, 'learning_rate': 0.0983514933405076}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.1849708335763389
Fold 2 IBS: 0.20472042501144078
Fold 3 IBS: 0.174549753512971
Fold 4 IBS: 0.19474848952922844
Fold 5 IBS: 0.21390230739654956
[I 2024-04-14 16:05:23,088] Trial 80 finished with value: 0.19457836180530572 and parameters: {'subsample': 0.16067957617145104, 'dropout_rate': 0.9178765225223764, 'n_estimators': 32, 'learning_rate': 0.09342021395183185}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.2009545598456572
Fold 2 IBS: 0.20757086108776626
Fold 3 IBS: 0.1891408235087506
Fold 4 IBS: 0.213809725088945
Fold 5 IBS: 0.2118289516198751
[I 2024-04-14 16:05:23,362] Trial 81 finished with value: 0.20466098423019882 and parameters: {'subsample': 0.22215890008875613, 'dropout_rate': 0.8794846667135415, 'n_estimators': 13, 'learning_rate': 0.09993787248225433}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.17500173313884562
Fold 2 IBS: 0.24888782315629673
Fold 3 IBS: 0.1637680643868198
Fold 4 IBS: 0.23850161577093545
Fold 5 IBS: 0.23015235972435077
[I 2024-04-14 16:05:23,923] Trial 82 finished with value: 0.2112623192354497 and parameters: {'subsample': 0.26372021229785475, 'dropout_rate': 0.8335686209903734, 'n_estimators': 67, 'learning_rate': 0.09472583994842627}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.18154224520649243
Fold 2 IBS: 0.21098450936180638
Fold 3 IBS: 0.16605568713404453
Fold 4 IBS: 0.20296551895339746
Fold 5 IBS: 0.21564204409171414
[I 2024-04-14 16:05:24,339] Trial 83 finished with value: 0.195438000949491 and parameters: {'subsample': 0.19117440261296625, 'dropout_rate': 0.5880713157522124, 'n_estimators': 44, 'learning_rate': 0.09157658017061529}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.20057434054288062
Fold 2 IBS: 0.30137702086465973
Fold 3 IBS: 0.26400068864971615
Fold 4 IBS: 0.31580476530089385
Fold 5 IBS: 0.28332773310934434
[I 2024-04-14 16:05:29,931] Trial 84 finished with value: 0.2730169096934989 and parameters: {'subsample': 0.1340496967551166, 'dropout_rate': 0.7994143440322944, 'n_estimators': 494, 'learning_rate': 0.05411447543421863}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.18250245978554738
Fold 2 IBS: 0.20978766084072098
Fold 3 IBS: 0.16751526500689215
Fold 4 IBS: 0.2069450995082109
Fold 5 IBS: 0.2147967798384957
[I 2024-04-14 16:05:30,379] Trial 85 finished with value: 0.1963094529959734 and parameters: {'subsample': 0.3499070610936068, 'dropout_rate': 0.7397767828858219, 'n_estimators': 59, 'learning_rate': 0.06084207839658691}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.17867703942973556
Fold 2 IBS: 0.23685519168479188
Fold 3 IBS: 0.16483466432509394
Fold 4 IBS: 0.19215481409119434
Fold 5 IBS: 0.23425808962419709
[I 2024-04-14 16:05:30,963] Trial 86 finished with value: 0.20135595983100255 and parameters: {'subsample': 0.11687428058758571, 'dropout_rate': 0.8597621321871682, 'n_estimators': 89, 'learning_rate': 0.07682858835275239}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.19798133122504205
Fold 2 IBS: 0.3014080244158332
Fold 3 IBS: 0.267992694916423
Fold 4 IBS: 0.315854398653198
Fold 5 IBS: 0.285591580924237
[I 2024-04-14 16:05:34,964] Trial 87 finished with value: 0.2737656060269466 and parameters: {'subsample': 0.16819420392244477, 'dropout_rate': 0.9792458968551334, 'n_estimators': 472, 'learning_rate': 0.06617165271694533}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.19484448493294582
Fold 2 IBS: 0.30138958659145226
Fold 3 IBS: 0.21783689065667927
Fold 4 IBS: 0.3157526653905466
Fold 5 IBS: 0.2776771446355286
[I 2024-04-14 16:05:36,602] Trial 88 finished with value: 0.2615001544414305 and parameters: {'subsample': 0.2820850179082329, 'dropout_rate': 0.920976958245464, 'n_estimators': 227, 'learning_rate': 0.08050027666004259}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.2120996994149135
Fold 2 IBS: 0.21987206872178136
Fold 3 IBS: 0.20230933230891127
Fold 4 IBS: 0.22390479635570432
Fold 5 IBS: 0.2179545263438928
[I 2024-04-14 16:05:36,862] Trial 89 finished with value: 0.2152280846290407 and parameters: {'subsample': 0.3258113489285195, 'dropout_rate': 0.6436774805198799, 'n_estimators': 2, 'learning_rate': 0.0584724174276294}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.1758750011277574
Fold 2 IBS: 0.29190805151991744
Fold 3 IBS: 0.16992365992637126
Fold 4 IBS: 0.2913347856391773
Fold 5 IBS: 0.24893878712680237
[I 2024-04-14 16:05:37,656] Trial 90 finished with value: 0.23559605706800513 and parameters: {'subsample': 0.2503650396218897, 'dropout_rate': 0.8878886464456023, 'n_estimators': 102, 'learning_rate': 0.09173327777332059}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.18484898097608476
Fold 2 IBS: 0.20571350995016308
Fold 3 IBS: 0.170406452601833
Fold 4 IBS: 0.19280299084189537
Fold 5 IBS: 0.21621815968498975
[I 2024-04-14 16:05:38,178] Trial 91 finished with value: 0.19399801881099318 and parameters: {'subsample': 0.12133290178399077, 'dropout_rate': 0.8442798709112938, 'n_estimators': 68, 'learning_rate': 0.05019551432237313}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.17518111062298197
Fold 2 IBS: 0.20717603187621544
Fold 3 IBS: 0.16754471009125943
Fold 4 IBS: 0.20577488144560135
Fold 5 IBS: 0.21487386707925307
[I 2024-04-14 16:05:38,789] Trial 92 finished with value: 0.19411012022306223 and parameters: {'subsample': 0.1997432341753716, 'dropout_rate': 0.8432565273520194, 'n_estimators': 72, 'learning_rate': 0.05232816444073158}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.19827510770092602
Fold 2 IBS: 0.2067487468985087
Fold 3 IBS: 0.1866192026843836
Fold 4 IBS: 0.2094697712060283
Fold 5 IBS: 0.21350061651211152
[I 2024-04-14 16:05:39,489] Trial 93 finished with value: 0.20292268900039162 and parameters: {'subsample': 0.1206410626786128, 'dropout_rate': 0.8434001392242207, 'n_estimators': 74, 'learning_rate': 0.019127674637257917}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.1749084636497462
Fold 2 IBS: 0.2349564415796216
Fold 3 IBS: 0.16681794727467392
Fold 4 IBS: 0.21480732180699322
Fold 5 IBS: 0.2273698192024792
[I 2024-04-14 16:05:40,623] Trial 94 finished with value: 0.20377199870270282 and parameters: {'subsample': 0.15369677561678466, 'dropout_rate': 0.8731417999992503, 'n_estimators': 140, 'learning_rate': 0.04469189464513441}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.20904051272968713
Fold 2 IBS: 0.21671396979860788
Fold 3 IBS: 0.19923767953920732
Fold 4 IBS: 0.22052357345201626

Fold 5 IBS: 0.21623431750226857
[I 2024-04-14 16:05:41,158] Trial 95 finished with value: 0.21235001060435743 and parameters: {'subsample': 0.18849122365713838, 'dropout_rate': 0.8183000737870284, 'n_estimators': 63, 'learning_rate': 0.0058046127253871885}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.17920744733080823
Fold 2 IBS: 0.20650083821997772
Fold 3 IBS: 0.16787219115746788
Fold 4 IBS: 0.1935736735660491
Fold 5 IBS: 0.2172044375016859
[I 2024-04-14 16:05:41,627] Trial 96 finished with value: 0.19287171755519777 and parameters: {'subsample': 0.10202382959971797, 'dropout_rate': 0.7861202496553675, 'n_estimators': 78, 'learning_rate': 0.05227568594858167}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.1811475437618194
Fold 2 IBS: 0.2024565347988353
Fold 3 IBS: 0.17222008300034344
Fold 4 IBS: 0.1956371349303774
Fold 5 IBS: 0.21757937566078778
[I 2024-04-14 16:05:42,259] Trial 97 finished with value: 0.19380813443043265 and parameters: {'subsample': 0.12159929530368488, 'dropout_rate': 0.9263488734601075, 'n_estimators': 91, 'learning_rate': 0.04116321754492538}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.17949655482036236
Fold 2 IBS: 0.20209673842039463
Fold 3 IBS: 0.17217202497610157
Fold 4 IBS: 0.19607590536841812
Fold 5 IBS: 0.2185122477243223
[I 2024-04-14 16:05:42,923] Trial 98 finished with value: 0.1936706942619198 and parameters: {'subsample': 0.11815539357661095, 'dropout_rate': 0.9274414511318402, 'n_estimators': 95, 'learning_rate': 0.04074105732458695}. Best is trial 78 with value: 0.19131729781258883.
Fold 1 IBS: 0.17970435277827293
Fold 2 IBS: 0.209196121212854
Fold 3 IBS: 0.16682295054653248
Fold 4 IBS: 0.19520877659082483
Fold 5 IBS: 0.22040542315475709
[I 2024-04-14 16:05:43,751] Trial 99 finished with value: 0.19426752485664828 and parameters: {'subsample': 0.10097593345090024, 'dropout_rate': 0.9272644513047693, 'n_estimators': 115, 'learning_rate': 0.04086832108112694}. Best is trial 78 with value: 0.19131729781258883.


* Best trial for IBS:
 FrozenTrial(number=78, state=TrialState.COMPLETE, values=[0.19131729781258883], datetime_start=datetime.datetime(2024, 4, 14, 16, 5, 21, 516054), datetime_complete=datetime.datetime(2024, 4, 14, 16, 5, 21, 863295), params={'subsample': 0.17910269140503615, 'dropout_rate': 0.8516991920191342, 'n_estimators': 36, 'learning_rate': 0.09808413258788978}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=78, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.17910269140503615, 'dropout_rate': 0.8516991920191342, 'n_estimators': 36, 'learning_rate': 0.09808413258788978}


* Best Score for IBS:
 0.19131729781258883

In [182]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [183]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.742
train_ibs:  0.191

#### Test

In [184]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [185]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9261509226223655,
                                              learning_rate=0.04202399206134448,
                                              n_estimators=274,
                                              random_state=123,
                                              subsample=0.10061641287468016)

C-index score: 0.667

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8516991920191342,
                                              learning_rate=0.09808413258788978,
                                              n_estimators=36, random_state=123,
                                              subsample=0.17910269140503615)

IBS: 0.205

In [186]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [187]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.798   1.0
Randomsurvivalforest             0.787   2.0
GradientBoosting                 0.743   3.0
ComponentwiseGradientBoosting    0.742   4.0
CoxPH                            0.737   5.0
CoxLasso                         0.736   6.5
CoxElastic                       0.736   6.5
CoxRidge                         0.647   8.0

In [188]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.184   1.0
Randomsurvivalforest           0.185   2.0
CoxPH                          0.187   4.0
CoxLasso                       0.187   4.0
CoxElastic                     0.187   4.0
ComponentwiseGradientBoosting  0.191   6.0
GradientBoosting               0.214   7.0
CoxRidge                       0.217   8.0

In [189]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.708   1.0
CoxRidge                         0.701   2.0
ComponentwiseGradientBoosting    0.667   3.0
ExtraSurvivalTrees               0.632   4.0
CoxElastic                       0.598   5.0
CoxLasso                         0.597   6.0
CoxPH                            0.593   7.0
GradientBoosting                 0.590   8.0

In [190]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.205   1.0
Randomsurvivalforest           0.208   2.0
ExtraSurvivalTrees             0.217   3.0
GradientBoosting               0.218   4.0
CoxRidge                       0.221   5.0
CoxPH                          0.269   6.0
CoxLasso                       0.272   7.5
CoxElastic                     0.272   7.5

In [191]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/yeojohnson/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_os_yeojohnson_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [192]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14