In [91]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
    
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification
from sklearn.preprocessing import PowerTransformer

In [92]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [93]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [94]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [95]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [96]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [97]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic      p  -log2(p)
MTV                       0.07   0.80      0.33
SUVpeak                   0.17   0.68      0.56
TLG                       0.38   0.54      0.90
age                       0.09   0.77      0.38
cavum_oris                0.00   0.99      0.02
charlson                  1.66   0.20      2.34
female                    2.67   0.10      3.29
histgrade_high            0.13   0.72      0.48
hpv_related              12.67 <0.005     11.39
hypopharynx               0.00   0.99      0.01
larynx                    0.00   0.98      0.03
oropharynx                0.00   0.98      0.02
pack_years                0.06   0.81      0.31
uicc8_III-IV              0.09   0.76      0.39

In [98]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [99]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.59 0.44      1.17
SUVpeak                   0.01 0.91      0.14
TLG                       0.00 0.96      0.06
age                       0.43 0.51      0.97
cavum_oris                0.41 0.52      0.94
charlson                  0.87 0.35      1.51
female                    2.39 0.12      3.04
histgrade_high            0.11 0.74      0.44
hpv_related               6.46 0.01      6.51
hypopharynx               0.04 0.84      0.25
larynx                    0.97 0.33      1.62
oropharynx                0.85 0.36      1.49
pack_years                0.00 0.99      0.01
uicc8_III-IV              0.00 0.95      0.07

In [100]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [101]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [102]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [103]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [104]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [105]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [106]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [107]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [108]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [109]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [110]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [111]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [112]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Yeo-Johnson Transformation

In [113]:
original_X = X.copy()

In [114]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
pt = PowerTransformer(method='yeo-johnson')
X_numeric_std = pt.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [117]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [118]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [119]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [120]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.785036,1,0,1,0,0,1,0.0,0,-1.533345,0.0,0.750782,0.080033,0.343545
1,-0.746998,0,0,0,0,1,0,0.0,1,0.397233,0.0,-1.213660,-1.722060,-1.657833
2,-0.175256,0,1,0,0,0,1,0.0,1,0.830437,1.0,-0.474112,0.735716,0.318631
3,1.371631,0,0,0,0,1,0,0.0,1,0.727938,0.0,-1.992620,-1.291020,-1.835650
4,0.987008,0,0,0,0,1,0,0.0,1,1.144253,0.0,-1.106304,-0.816679,-1.003396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.007949,0,0,1,0,0,1,1.0,0,-1.533345,0.0,-0.158214,-0.822461,-0.611074
135,1.111443,0,0,1,0,0,1,1.0,0,-1.533345,1.0,-0.632361,1.008070,0.474941
136,-0.370651,0,0,1,0,0,1,1.0,1,0.786825,0.0,0.658564,-0.170908,0.133612
137,0.696583,0,0,1,0,0,1,1.0,1,1.554125,1.0,-0.551725,0.574668,0.197985
138,0.169401,0,0,1,0,0,1,1.0,0,-1.110899,1.0,0.527960,0.086991,0.270290

In [121]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [122]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,-0.688798,0,0,1,0,0,1,1,1,-1.533345,0,0.893634,1.188930,1.218887
1,-0.688798,0,0,1,0,0,0,0,0,0.104884,1,-0.254678,-0.307894,-0.335276
2,-0.688798,0,0,1,0,0,0,0,1,-0.713198,1,0.595996,0.059450,0.228548
3,0.081262,1,0,0,0,1,1,0,1,0.940197,1,-0.296877,0.076321,-0.145668
4,1.273609,0,0,1,0,0,1,1,1,1.285347,0,-0.058378,0.786849,0.519421
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.738387,1,0,0,0,1,0,0,0,1.192311,1,2.645651,-0.219083,0.751363
95,0.342484,0,0,0,0,1,0,0,1,3.094727,1,0.526028,-0.033134,0.168333
96,0.342484,0,0,1,0,0,1,1,1,-1.533345,1,-0.230255,0.867254,0.481447
97,-0.815082,0,0,1,0,0,1,1,0,-1.533345,0,0.706707,0.336049,0.486335
98,0.211597,0,0,0,1,0,1,0,0,0.801315,1,0.064287,-0.873431,-0.544074

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [123]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:58:35,307] A new study created in memory with name: no-name-20cde77c-d0ac-487e-9ad3-2666b073c79c

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836

[I 2024-04-13 23:58:37,908] A new study created in memory with name: no-name-833a1218-af08-45a3-969c-a67341914f73

Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 23:58:37,807] Trial 0 finished with value: 0.7434989412546489 and parameters: {}. Best is trial 0 with value: 0.7434989412546489.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7434989412546489], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 35, 498842), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 37, 805906), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7434989412546489

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16883035103807653
Fold 2 IBS: 0.19635745123057224
Fold 3 IBS: 0.16550671851920126
Fold 4 IBS: 0.14957197387797055
Fold 5 IBS: 0.26973255955213016
[I 2024-04-13 23:58:40,087] Trial 0 finished with value: 0.18999981084359013 and parameters: {}. Best is trial 0 with value: 0.18999981084359013.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18999981084359013], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 38, 113625), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 40, 85451), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18999981084359013

In [124]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [125]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.743
train_ibs:  0.19

#### Test

In [126]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [127]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.581
IBS score: 0.281

In [128]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [129]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [130]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:58:41,005] A new study created in memory with name: no-name-88dc9f68-b041-4a39-b943-aea865c0a3ba

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6298701298701299
Fold 2 C-index: 0.640625
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.7784810126582279
Fold 5 C-index: 0.5727699530516432
[I 2024-04-13 23:58:42,397] Trial 0 finished with value: 0.6748394151944316 and parameters: {}. Best is trial 0 with value: 0.6748394151944316.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6748394151944316], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 41, 72039), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 42, 395754), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6748394151944316

[I 2024-04-13 23:58:42,448] A new study created in memory with name: no-name-23b7025d-bcc6-4d91-a1a3-ce953f49398c

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651730092662
Fold 2 IBS: 0.22157791055888598
Fold 3 IBS: 0.20453594148397225
Fold 4 IBS: 0.22473803361997696
Fold 5 IBS: 0.21812431365411103
[I 2024-04-13 23:58:44,519] Trial 0 finished with value: 0.21659054332357458 and parameters: {}. Best is trial 0 with value: 0.21659054332357458.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054332357458], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 42, 669817), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 44, 519110), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054332357458

In [131]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [132]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.675
train_ibs:  0.217

#### Test

In [133]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [134]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [135]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [136]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:58:45,635] A new study created in memory with name: no-name-7bb41429-d3e0-45a2-8aec-0833823df13d

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836

[I 2024-04-13 23:58:50,015] A new study created in memory with name: no-name-8534428e-cc16-49bc-8cb6-1eafb604028f

Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:58:49,919] Trial 0 finished with value: 0.746490912691111 and parameters: {}. Best is trial 0 with value: 0.746490912691111.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.746490912691111], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 45, 690582), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 49, 905588), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.746490912691111

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1693166643871831
Fold 2 IBS: 0.19627569923765678
Fold 3 IBS: 0.16332206774428829
Fold 4 IBS: 0.14781384832535083
Fold 5 IBS: 0.26849204574549806
[I 2024-04-13 23:58:53,643] Trial 0 finished with value: 0.18904406508799543 and parameters: {}. Best is trial 0 with value: 0.18904406508799543.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18904406508799543], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 50, 208696), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 53, 631158), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18904406508799543

In [137]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [138]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.746
train_ibs:  0.189

#### Test

In [139]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [140]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.592

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.28

In [141]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [142]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:58:56,340] A new study created in memory with name: no-name-fccab477-810c-4229-af26-ce38ac6a6712

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:58:59,758] Trial 0 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:05,352] Trial 1 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:09,701] Trial 2 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:14,553] Trial 3 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:17,620] Trial 4 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:21,079] Trial 5 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:23,516] Trial 6 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:26,583] Trial 7 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:29,539] Trial 8 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:33,233] Trial 9 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:36,922] Trial 10 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:41,147] Trial 11 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:45,057] Trial 12 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:50,623] Trial 13 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8178071080614558}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:56,213] Trial 14 finished with value: 0.7447541736917136 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 23:59:59,874] Trial 15 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5998716175293216}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:04,860] Trial 16 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8431112134784231}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:09,550] Trial 17 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6422698927560148}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:13,548] Trial 18 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8885825731043129}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:18,653] Trial 19 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5264626269854424}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:23,612] Trial 20 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:27,943] Trial 21 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9632315494528705}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:31,871] Trial 22 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7603585811207305}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:37,933] Trial 23 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9339868118831415}. Best is trial 0 with value: 0.746490912691111.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:42,878] Trial 24 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8064824763528503}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:46,083] Trial 25 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6339676394936953}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 00:00:47,757] Trial 26 finished with value: 0.6814841461957966 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:51,729] Trial 27 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6942928064214194}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:55,080] Trial 28 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9063632126862387}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:00:58,570] Trial 29 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.3366186703390048}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:02,690] Trial 30 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5775787537083129}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:07,310] Trial 31 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.71574740581714}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:10,118] Trial 32 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6859625283120885}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:13,000] Trial 33 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.491973558069458}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:16,235] Trial 34 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7856939143902578}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:19,364] Trial 35 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.22335805122952096}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:22,196] Trial 36 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.42934638668253117}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:24,764] Trial 37 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.638107802249213}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:27,474] Trial 38 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:30,132] Trial 39 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8502102584656897}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:32,851] Trial 40 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9998763607475236}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:36,072] Trial 41 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.995844304426954}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:38,713] Trial 42 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9412604927405921}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:41,405] Trial 43 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7753616951318902}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:44,066] Trial 44 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9071205496489702}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:46,846] Trial 45 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8331567323676282}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:49,874] Trial 46 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6642734577753772}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:52,729] Trial 47 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7362617746615973}. Best is trial 0 with value: 0.746490912691111.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:56,144] Trial 48 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.45725440612299806}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:01:59,209] Trial 49 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.3754056069137437}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:02,803] Trial 50 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:06,304] Trial 51 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7482811902553718}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:09,747] Trial 52 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5383755553153362}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:12,173] Trial 53 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8759111832590323}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:14,690] Trial 54 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9618704906269463}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:17,336] Trial 55 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8201739011915794}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:19,860] Trial 56 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6914107748113156}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:23,250] Trial 57 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8048857750626598}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:27,152] Trial 58 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.6045473536185978}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:29,792] Trial 59 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9099250400802865}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:32,107] Trial 60 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8499949494426712}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:34,492] Trial 61 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.721785027890034}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:37,420] Trial 62 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6702160143572373}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:40,480] Trial 63 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7796869967757354}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:42,903] Trial 64 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7190336244512912}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:46,003] Trial 65 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6463081053454892}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:50,227] Trial 66 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.2283450959509596}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:53,557] Trial 67 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9598741045005194}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:02:57,727] Trial 68 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5066793283401715}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:01,024] Trial 69 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.6108424280401747}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:03,924] Trial 70 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7553608936485141}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:06,661] Trial 71 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8074481063968476}. Best is trial 0 with value: 0.746490912691111.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:09,241] Trial 72 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8665401936595644}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:11,667] Trial 73 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6984464870637777}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:14,218] Trial 74 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9244290763890299}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:17,121] Trial 75 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.776173996482925}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:19,446] Trial 76 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6639722649723583}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:22,005] Trial 77 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8832994937104452}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:24,499] Trial 78 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9804309784003453}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:27,604] Trial 79 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.5672511224078898}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:30,320] Trial 80 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7473724923384686}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:33,000] Trial 81 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8282501859389371}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:35,207] Trial 82 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7191205616242847}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:37,768] Trial 83 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7932215903823733}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:41,109] Trial 84 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9438198365105025}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:43,328] Trial 85 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.9030544516246045}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:45,896] Trial 86 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8532450694241727}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:47,889] Trial 87 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.698761807726428}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:50,638] Trial 88 finished with value: 0.7456470308345708 and parameters: {'l1_ratio': 0.6282964801981165}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:52,763] Trial 89 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8387351362306311}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:03:54,962] Trial 90 finished with value: 0.7455519455549606 and parameters: {'l1_ratio': 0.9745475621557447}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:03:57,575] Trial 91 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7389888445981441}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:00,110] Trial 92 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7693763777756671}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:03,244] Trial 93 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6662614699809396}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:05,267] Trial 94 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.681474367723924}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:07,490] Trial 95 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.6440024467340105}. Best is trial 0 with value: 0.746490912691111.

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:09,532] Trial 96 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.8074703261950165}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:11,698] Trial 97 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7086703628494722}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:13,871] Trial 98 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7336051820935596}. Best is trial 0 with value: 0.746490912691111.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836

[I 2024-04-14 00:04:16,505] A new study created in memory with name: no-name-3224af8b-3a4e-4517-bd63-58a1c18088b5

Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 00:04:16,451] Trial 99 finished with value: 0.746490912691111 and parameters: {'l1_ratio': 0.7652252865393889}. Best is trial 0 with value: 0.746490912691111.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.746490912691111], datetime_start=datetime.datetime(2024, 4, 13, 23, 58, 56, 467502), datetime_complete=datetime.datetime(2024, 4, 13, 23, 58, 59, 756973), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.746490912691111

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16939356487827184
Fold 2 IBS: 0.19677633886148008
Fold 3 IBS: 0.1631953006442755
Fold 4 IBS: 0.14789851767436374
Fold 5 IBS: 0.2683969898141077
[I 2024-04-14 00:04:18,858] Trial 0 finished with value: 0.18913214237449974 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.18913214237449974.
Fold 1 IBS: 0.1694912710909019
Fold 2 IBS: 0.19770864903522367
Fold 3 IBS: 0.16461913118179491
Fold 4 IBS: 0.14831322413708167
Fold 5 IBS: 0.2682120259189454
[I 2024-04-14 00:04:21,906] Trial 1 finished with value: 0.18966886027278954 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.18913214237449974.
Fold 1 IBS: 0.16950118238298933
Fold 2 IBS: 0.19785719051161688
Fold 3 IBS: 0.1645624877332342
Fold 4 IBS: 0.14817270753131573
Fold 5 IBS: 0.268248614110171
[I 2024-04-14 00:04:25,219] Trial 2 finished with value: 0.1896684364538654 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.18913214237449974.
Fold 1 IBS: 0.16946261568583662
Fold 2 IBS: 0.19695792002669082
Fold 3 IBS: 0.1629991128884912
Fold 4 IBS: 0.1484831043902643
Fold 5 IBS: 0.26839508213433855
[I 2024-04-14 00:04:27,685] Trial 3 finished with value: 0.1892595670251243 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.18913214237449974.
Fold 1 IBS: 0.16938070661852742
Fold 2 IBS: 0.19676987109822025
Fold 3 IBS: 0.1630516877402438
Fold 4 IBS: 0.1477518201916504
Fold 5 IBS: 0.2684394834763871
[I 2024-04-14 00:04:30,049] Trial 4 finished with value: 0.18907871382500577 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.18907871382500577.
Fold 1 IBS: 0.16949397183080486
Fold 2 IBS: 0.197301779147839
Fold 3 IBS: 0.1629704687063918
Fold 4 IBS: 0.14836193790036875
Fold 5 IBS: 0.26827584494327583
[I 2024-04-14 00:04:32,616] Trial 5 finished with value: 0.18928080050573606 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.18907871382500577.
Fold 1 IBS: 0.16932422328885602
Fold 2 IBS: 0.1962768074208909
Fold 3 IBS: 0.163283066817471
Fold 4 IBS: 0.14777032236778073
Fold 5 IBS: 0.2684640857219937
[I 2024-04-14 00:04:34,987] Trial 6 finished with value: 0.18902370112339847 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16939209175730086
Fold 2 IBS: 0.1967795984933343
Fold 3 IBS: 0.1631458917209151
Fold 4 IBS: 0.14787473117613847
Fold 5 IBS: 0.2683754007716889
[I 2024-04-14 00:04:37,766] Trial 7 finished with value: 0.18911354278387554 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.1694852790873154
Fold 2 IBS: 0.19712044814953236
Fold 3 IBS: 0.1630709297303018
Fold 4 IBS: 0.14846557221228354
Fold 5 IBS: 0.26832593880828515
[I 2024-04-14 00:04:40,427] Trial 8 finished with value: 0.18929363359754364 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16948353153709772
Fold 2 IBS: 0.19743136691941632
Fold 3 IBS: 0.16298648599802404
Fold 4 IBS: 0.14839863086828992
Fold 5 IBS: 0.26828515606225445
[I 2024-04-14 00:04:42,671] Trial 9 finished with value: 0.1893170342770165 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.1693227808043481
Fold 2 IBS: 0.19627597304813588
Fold 3 IBS: 0.16329440519355642
Fold 4 IBS: 0.14778505643069903
Fold 5 IBS: 0.26846960748807525
[I 2024-04-14 00:04:45,011] Trial 10 finished with value: 0.18902956459296294 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16931772932226077
Fold 2 IBS: 0.19627525058050707
Fold 3 IBS: 0.1633132808442985
Fold 4 IBS: 0.14780989216195076
Fold 5 IBS: 0.26848757519752114
[I 2024-04-14 00:04:47,121] Trial 11 finished with value: 0.18904074562130763 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16931874342415065
Fold 2 IBS: 0.19627507213065246
Fold 3 IBS: 0.1633050153757035
Fold 4 IBS: 0.1478061541943901
Fold 5 IBS: 0.2684839484206245
[I 2024-04-14 00:04:50,066] Trial 12 finished with value: 0.18903778670910426 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16933653162853976
Fold 2 IBS: 0.1965357874419996
Fold 3 IBS: 0.16331722309731012
Fold 4 IBS: 0.14779135591606535
Fold 5 IBS: 0.26846658008772717
[I 2024-04-14 00:04:52,735] Trial 13 finished with value: 0.18908949563432836 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16955420628999515
Fold 2 IBS: 0.19838889761587827
Fold 3 IBS: 0.16446836689376473
Fold 4 IBS: 0.1481933629358539
Fold 5 IBS: 0.268147100069595
[I 2024-04-14 00:04:55,822] Trial 14 finished with value: 0.18975038676101738 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.1693298250998367
Fold 2 IBS: 0.1965313383861305
Fold 3 IBS: 0.16334586873673224
Fold 4 IBS: 0.14781365357038645
Fold 5 IBS: 0.26848733486355164
[I 2024-04-14 00:04:58,313] Trial 15 finished with value: 0.1891016041313275 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16933302191378788
Fold 2 IBS: 0.19653347961960457
Fold 3 IBS: 0.16334504168476324
Fold 4 IBS: 0.14780300469689409
Fold 5 IBS: 0.2684771415396694
[I 2024-04-14 00:05:00,833] Trial 16 finished with value: 0.18909833789094382 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16936570552227634
Fold 2 IBS: 0.19655725869735297
Fold 3 IBS: 0.16318545037144713
Fold 4 IBS: 0.14772648576898104
Fold 5 IBS: 0.26840433933395863
[I 2024-04-14 00:05:03,250] Trial 17 finished with value: 0.18904784793880322 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.1694257395002915
Fold 2 IBS: 0.19695300116368797
Fold 3 IBS: 0.1631564544045919
Fold 4 IBS: 0.14851412957550458
Fold 5 IBS: 0.2683596265407176
[I 2024-04-14 00:05:05,658] Trial 18 finished with value: 0.1892817902369587 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16932928837856964
Fold 2 IBS: 0.1965047478899413
Fold 3 IBS: 0.16340308951679341
Fold 4 IBS: 0.1477470295457121
Fold 5 IBS: 0.2685215209422881
[I 2024-04-14 00:05:07,951] Trial 19 finished with value: 0.1891011352546609 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16939089486037762
Fold 2 IBS: 0.19675843103777096
Fold 3 IBS: 0.16319314418066902
Fold 4 IBS: 0.1478184845212501
Fold 5 IBS: 0.26840149436191196
[I 2024-04-14 00:05:10,372] Trial 20 finished with value: 0.18911248979239595 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16933265317861818
Fold 2 IBS: 0.1965071606659873
Fold 3 IBS: 0.16337882377111396
Fold 4 IBS: 0.1477348749210632
Fold 5 IBS: 0.26850973205722634
[I 2024-04-14 00:05:12,876] Trial 21 finished with value: 0.1890926489188018 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16931852744907486
Fold 2 IBS: 0.19627509418156427
Fold 3 IBS: 0.16330675396776026
Fold 4 IBS: 0.14780694798496713
Fold 5 IBS: 0.26848479338955644
[I 2024-04-14 00:05:15,342] Trial 22 finished with value: 0.1890384233945846 and parameters: {'l1_ratio': 0.9951649660667304}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16931907428237747
Fold 2 IBS: 0.19652410384632993
Fold 3 IBS: 0.16321532826836624
Fold 4 IBS: 0.14785264122100544
Fold 5 IBS: 0.268425411632799
[I 2024-04-14 00:05:18,290] Trial 23 finished with value: 0.1890673118501756 and parameters: {'l1_ratio': 0.8890150131901534}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16937486587249947
Fold 2 IBS: 0.19656294039495048
Fold 3 IBS: 0.1632902366286075
Fold 4 IBS: 0.14785923591162864
Fold 5 IBS: 0.2684474714719049
[I 2024-04-14 00:05:21,031] Trial 24 finished with value: 0.1891069500559182 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.18902370112339847.

Fold 1 IBS: 0.16933662501128705
Fold 2 IBS: 0.19650838285558786
Fold 3 IBS: 0.16335035126098837
Fold 4 IBS: 0.1477213551728845
Fold 5 IBS: 0.2684968762348328
[I 2024-04-14 00:05:23,181] Trial 25 finished with value: 0.18908271810711613 and parameters: {'l1_ratio': 0.9363009671094719}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.21329546612926484
Fold 2 IBS: 0.2206045919636927
Fold 3 IBS: 0.20367201451615735
Fold 4 IBS: 0.22360038965205914
Fold 5 IBS: 0.21789198128063986
[I 2024-04-14 00:05:24,363] Trial 26 finished with value: 0.2158128887083628 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16940894356216168
Fold 2 IBS: 0.19695045885917128
Fold 3 IBS: 0.16300729331681135
Fold 4 IBS: 0.14853733095928068
Fold 5 IBS: 0.2684088437874255
[I 2024-04-14 00:05:27,024] Trial 27 finished with value: 0.1892625740969701 and parameters: {'l1_ratio': 0.6022588122254688}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16941846451855527
Fold 2 IBS: 0.19678839480304677
Fold 3 IBS: 0.16322281405571434
Fold 4 IBS: 0.14778566293911438
Fold 5 IBS: 0.2684041066502247
[I 2024-04-14 00:05:29,461] Trial 28 finished with value: 0.18912388859333112 and parameters: {'l1_ratio': 0.6483163834613106}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.1693529673037713
Fold 2 IBS: 0.19652023989170492
Fold 3 IBS: 0.1632565497624624
Fold 4 IBS: 0.14787049278950892
Fold 5 IBS: 0.2684441875387649
[I 2024-04-14 00:05:31,756] Trial 29 finished with value: 0.1890888874572425 and parameters: {'l1_ratio': 0.9010792166439672}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16936836913745693
Fold 2 IBS: 0.19655870245444224
Fold 3 IBS: 0.16316825678835095
Fold 4 IBS: 0.14771837399879856
Fold 5 IBS: 0.26839671201321497
[I 2024-04-14 00:05:34,286] Trial 30 finished with value: 0.18904208287845276 and parameters: {'l1_ratio': 0.809491448907531}. Best is trial 6 with value: 0.18902370112339847.
Fold 1 IBS: 0.16932491018244225
Fold 2 IBS: 0.1962772765536101
Fold 3 IBS: 0.16327772486434275
Fold 4 IBS: 0.1477678607306966
Fold 5 IBS: 0.2684621795943914
[I 2024-04-14 00:05:37,064] Trial 31 finished with value: 0.18902199038509662 and parameters: {'l1_ratio': 0.979068464785078}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932269917499412
Fold 2 IBS: 0.19650045520827344
Fold 3 IBS: 0.16324624394892942
Fold 4 IBS: 0.14776998465904914
Fold 5 IBS: 0.26854298474403626
[I 2024-04-14 00:05:39,965] Trial 32 finished with value: 0.18907647354705648 and parameters: {'l1_ratio': 0.9692277690482485}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16934901180232872
Fold 2 IBS: 0.19651766886323752
Fold 3 IBS: 0.16328427872088996
Fold 4 IBS: 0.14788265687069369
Fold 5 IBS: 0.2684566528250559
[I 2024-04-14 00:05:42,568] Trial 33 finished with value: 0.18909805381644115 and parameters: {'l1_ratio': 0.9093475006606729}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16931710760200425
Fold 2 IBS: 0.1962754773170642
Fold 3 IBS: 0.16331839231696693
Fold 4 IBS: 0.14781219781736604
Fold 5 IBS: 0.26848999516037214
[I 2024-04-14 00:05:45,451] Trial 34 finished with value: 0.18904263404275473 and parameters: {'l1_ratio': 0.9988436065462645}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693471753359995
Fold 2 IBS: 0.1965427105999797
Fold 3 IBS: 0.16324320515086918
Fold 4 IBS: 0.14775615066202402
Fold 5 IBS: 0.2684324894345929
[I 2024-04-14 00:05:47,947] Trial 35 finished with value: 0.18906434623669305 and parameters: {'l1_ratio': 0.831068012042404}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16939194297342014
Fold 2 IBS: 0.19675893537065367
Fold 3 IBS: 0.16318653535974473
Fold 4 IBS: 0.1478153154372077
Fold 5 IBS: 0.2683990879017034
[I 2024-04-14 00:05:50,718] Trial 36 finished with value: 0.18911036340854592 and parameters: {'l1_ratio': 0.7523438986596134}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16952322857755428
Fold 2 IBS: 0.19760931019382055
Fold 3 IBS: 0.16456814423563437
Fold 4 IBS: 0.14823805451657676
Fold 5 IBS: 0.26826492316813244
[I 2024-04-14 00:05:53,702] Trial 37 finished with value: 0.1896407321383437 and parameters: {'l1_ratio': 0.2987860764489435}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693886199797619
Fold 2 IBS: 0.1967742418060004
Fold 3 IBS: 0.16322626778892
Fold 4 IBS: 0.14791326724138984
Fold 5 IBS: 0.26841119448795525
[I 2024-04-14 00:05:56,241] Trial 38 finished with value: 0.18914271826080548 and parameters: {'l1_ratio': 0.7039737188855323}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16934970344917716
Fold 2 IBS: 0.19651811938836689
Fold 3 IBS: 0.16327942117598832
Fold 4 IBS: 0.14788052676786936
Fold 5 IBS: 0.26845486025384047
[I 2024-04-14 00:05:58,703] Trial 39 finished with value: 0.18909652620704842 and parameters: {'l1_ratio': 0.9078904949599446}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16946086293807397
Fold 2 IBS: 0.19712048472070248
Fold 3 IBS: 0.1629888344809583
Fold 4 IBS: 0.14850227240333047
Fold 5 IBS: 0.2682853599949033
[I 2024-04-14 00:06:01,072] Trial 40 finished with value: 0.1892715629075937 and parameters: {'l1_ratio': 0.5051453398869654}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932160803324664
Fold 2 IBS: 0.19627548828869923
Fold 3 IBS: 0.16330371569751548
Fold 4 IBS: 0.1477893079831245
Fold 5 IBS: 0.26847361672214726
[I 2024-04-14 00:06:03,336] Trial 41 finished with value: 0.18903274734494663 and parameters: {'l1_ratio': 0.987311940976918}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16933441786149275
Fold 2 IBS: 0.19650836349721867
Fold 3 IBS: 0.16336615632141396
Fold 4 IBS: 0.14772886402162466
Fold 5 IBS: 0.2685041561200834
[I 2024-04-14 00:06:05,560] Trial 42 finished with value: 0.1890883915643667 and parameters: {'l1_ratio': 0.9412857997703421}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932996488498397
Fold 2 IBS: 0.19650524003130002
Fold 3 IBS: 0.16339820685051434
Fold 4 IBS: 0.1477446969769508
Fold 5 IBS: 0.2685192876160698
[I 2024-04-14 00:06:07,834] Trial 43 finished with value: 0.18909947927196377 and parameters: {'l1_ratio': 0.9519288744970593}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16931882619992802
Fold 2 IBS: 0.1962750656948782
Fold 3 IBS: 0.16330433810697573
Fold 4 IBS: 0.14780585028181425
Fold 5 IBS: 0.26848362508094903
[I 2024-04-14 00:06:10,639] Trial 44 finished with value: 0.18903754107290904 and parameters: {'l1_ratio': 0.9943958556900309}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932569726002464
Fold 2 IBS: 0.19652856738116897
Fold 3 IBS: 0.16316881840361885
Fold 4 IBS: 0.14783051847201506
Fold 5 IBS: 0.26850065021509484
[I 2024-04-14 00:06:12,941] Trial 45 finished with value: 0.1890708503463845 and parameters: {'l1_ratio': 0.8746070404800059}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16934375824439743
Fold 2 IBS: 0.1965129181089306
Fold 3 IBS: 0.16332122024110415
Fold 4 IBS: 0.1476915049996643
Fold 5 IBS: 0.2684735262765261
[I 2024-04-14 00:06:15,378] Trial 46 finished with value: 0.1890685855741245 and parameters: {'l1_ratio': 0.920575361251498}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16936633016660732
Fold 2 IBS: 0.1965627735039023
Fold 3 IBS: 0.1631147507733812
Fold 4 IBS: 0.14789271216745292
Fold 5 IBS: 0.2684721089624041
[I 2024-04-14 00:06:17,797] Trial 47 finished with value: 0.18908173511474957 and parameters: {'l1_ratio': 0.7954342997513979}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693355248102033
Fold 2 IBS: 0.1965351276002118
Fold 3 IBS: 0.1633242497596311
Fold 4 IBS: 0.14779469617594926
Fold 5 IBS: 0.2684692481943111
[I 2024-04-14 00:06:20,250] Trial 48 finished with value: 0.18909176930806132 and parameters: {'l1_ratio': 0.8541614135523112}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16947627540966703
Fold 2 IBS: 0.19751190078774458
Fold 3 IBS: 0.1629300638330788
Fold 4 IBS: 0.14830643728918028
Fold 5 IBS: 0.26826925467878454
[I 2024-04-14 00:06:22,867] Trial 49 finished with value: 0.18929878639969105 and parameters: {'l1_ratio': 0.355745098499332}. Best is trial 31 with value: 0.18902199038509662.

Fold 1 IBS: 0.1694905593580144
Fold 2 IBS: 0.19776818858044026
Fold 3 IBS: 0.16457935699733217
Fold 4 IBS: 0.14819660433157147
Fold 5 IBS: 0.268270109219041
[I 2024-04-14 00:06:26,096] Trial 50 finished with value: 0.18966096369727986 and parameters: {'l1_ratio': 0.2311229033161103}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693245407561358
Fold 2 IBS: 0.19627705473388177
Fold 3 IBS: 0.1632805799677891
Fold 4 IBS: 0.14776918362708977
Fold 5 IBS: 0.26846286888583126
[I 2024-04-14 00:06:28,950] Trial 51 finished with value: 0.18902284559414556 and parameters: {'l1_ratio': 0.9799805566834315}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693208013101448
Fold 2 IBS: 0.1964992102077115
Fold 3 IBS: 0.16326112633889883
Fold 4 IBS: 0.1477766982484385
Fold 5 IBS: 0.26854959082925056
[I 2024-04-14 00:06:31,216] Trial 52 finished with value: 0.18908148538688882 and parameters: {'l1_ratio': 0.973873594635656}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932292793857012
Fold 2 IBS: 0.19650060179802
Fold 3 IBS: 0.16324444617032557
Fold 4 IBS: 0.14776917881288437
Fold 5 IBS: 0.2685421612625574
[I 2024-04-14 00:06:33,677] Trial 53 finished with value: 0.18907586319647146 and parameters: {'l1_ratio': 0.9686715071129661}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932432509738948
Fold 2 IBS: 0.1965235668710055
Fold 3 IBS: 0.16322124215113745
Fold 4 IBS: 0.1478559478098945
Fold 5 IBS: 0.2684282564506075
[I 2024-04-14 00:06:36,219] Trial 54 finished with value: 0.1890706676760069 and parameters: {'l1_ratio': 0.8907253952541039}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693417036763688
Fold 2 IBS: 0.19651162891567545
Fold 3 IBS: 0.16331408347126436
Fold 4 IBS: 0.1476984335911018
Fold 5 IBS: 0.2684802732392635
[I 2024-04-14 00:06:39,065] Trial 55 finished with value: 0.1890692245787348 and parameters: {'l1_ratio': 0.9250461327329565}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932180609282335
Fold 2 IBS: 0.19627555902044003
Fold 3 IBS: 0.16330213748792027
Fold 4 IBS: 0.1477885904514715
Fold 5 IBS: 0.26847282243412457
[I 2024-04-14 00:06:42,968] Trial 56 finished with value: 0.18903218309735595 and parameters: {'l1_ratio': 0.9868128559675079}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16933834705779288
Fold 2 IBS: 0.196536974013021
Fold 3 IBS: 0.16330457306859142
Fold 4 IBS: 0.14778533568575108
Fold 5 IBS: 0.2684607798436142
[I 2024-04-14 00:06:45,897] Trial 57 finished with value: 0.1890852019337541 and parameters: {'l1_ratio': 0.8484534980225887}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16939526015056472
Fold 2 IBS: 0.19676053351905048
Fold 3 IBS: 0.16316543746011652
Fold 4 IBS: 0.1478051928757581
Fold 5 IBS: 0.2683895889857425
[I 2024-04-14 00:06:49,077] Trial 58 finished with value: 0.18910320259824648 and parameters: {'l1_ratio': 0.7470367643570736}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16933010817673522
Fold 2 IBS: 0.19650544955959973
Fold 3 IBS: 0.16339592705882527
Fold 4 IBS: 0.1477436084120043
Fold 5 IBS: 0.2685181716800771
[I 2024-04-14 00:06:51,750] Trial 59 finished with value: 0.18909865297744832 and parameters: {'l1_ratio': 0.9511927358384068}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16940697472396093
Fold 2 IBS: 0.19678422237579707
Fold 3 IBS: 0.16305269347635012
Fold 4 IBS: 0.14782968463186058
Fold 5 IBS: 0.2684340413331938
[I 2024-04-14 00:06:54,161] Trial 60 finished with value: 0.1891015233082325 and parameters: {'l1_ratio': 0.6637869319032095}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16931717804017804
Fold 2 IBS: 0.19627544683973003
Fold 3 IBS: 0.16331782953663673
Fold 4 IBS: 0.1478119360410946
Fold 5 IBS: 0.2684897180583261
[I 2024-04-14 00:06:56,642] Trial 61 finished with value: 0.1890424217031931 and parameters: {'l1_ratio': 0.9986601851105383}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932375496832053
Fold 2 IBS: 0.19652723939404498
Fold 3 IBS: 0.1631796505025028
Fold 4 IBS: 0.14783701208288658
Fold 5 IBS: 0.26850706292942694
[I 2024-04-14 00:06:58,940] Trial 62 finished with value: 0.18907494397543637 and parameters: {'l1_ratio': 0.8788116589411044}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693208157059616
Fold 2 IBS: 0.19649921915063676
Fold 3 IBS: 0.16326105554576073
Fold 4 IBS: 0.1477766471260386
Fold 5 IBS: 0.2685495387605238
[I 2024-04-14 00:07:01,152] Trial 63 finished with value: 0.1890814552577843 and parameters: {'l1_ratio': 0.9738381434120449}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16933844556545233
Fold 2 IBS: 0.1965095557207489
Fold 3 IBS: 0.16333733201973447
Fold 4 IBS: 0.14771518162097516
Fold 5 IBS: 0.2684906859783348
[I 2024-04-14 00:07:03,491] Trial 64 finished with value: 0.18907824018104913 and parameters: {'l1_ratio': 0.9322318696677371}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16931813300701132
Fold 2 IBS: 0.19627515355458058
Fold 3 IBS: 0.16330997271201395
Fold 4 IBS: 0.1478084008777856
Fold 5 IBS: 0.26848671965446935
[I 2024-04-14 00:07:05,823] Trial 65 finished with value: 0.18903967596117216 and parameters: {'l1_ratio': 0.9961830159271203}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693486021628083
Fold 2 IBS: 0.19651740210767618
Fold 3 IBS: 0.1632871534304209
Fold 4 IBS: 0.14788391912789065
Fold 5 IBS: 0.26845805080496465
[I 2024-04-14 00:07:07,925] Trial 66 finished with value: 0.18909902552675215 and parameters: {'l1_ratio': 0.9102127181645361}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16934778478449955
Fold 2 IBS: 0.19654319329339154
Fold 3 IBS: 0.16323794731875782
Fold 4 IBS: 0.1477536420065857
Fold 5 IBS: 0.2684299679492706
[I 2024-04-14 00:07:10,394] Trial 67 finished with value: 0.18906250707050104 and parameters: {'l1_ratio': 0.8296064792836273}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932495458886912
Fold 2 IBS: 0.19650188646379266
Fold 3 IBS: 0.1632285867740848
Fold 4 IBS: 0.14776206752438945
Fold 5 IBS: 0.26853547939673744
[I 2024-04-14 00:07:13,103] Trial 68 finished with value: 0.1890705949495747 and parameters: {'l1_ratio': 0.9637775450046503}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932326703475276
Fold 2 IBS: 0.19652690748743876
Fold 3 IBS: 0.1631833678011135
Fold 4 IBS: 0.14783863919473308
Fold 5 IBS: 0.26850873741402237
[I 2024-04-14 00:07:15,847] Trial 69 finished with value: 0.18907618378641208 and parameters: {'l1_ratio': 0.8798643259241765}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16933927373558716
Fold 2 IBS: 0.19651008880402054
Fold 3 IBS: 0.16333147308354645
Fold 4 IBS: 0.14771237975341867
Fold 5 IBS: 0.26848838323318325
[I 2024-04-14 00:07:18,357] Trial 70 finished with value: 0.1890763197219512 and parameters: {'l1_ratio': 0.930393962491112}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16931840930827166
Fold 2 IBS: 0.19627510934711737
Fold 3 IBS: 0.1633077241743551
Fold 4 IBS: 0.1478073827132321
Fold 5 IBS: 0.26848551439093965
[I 2024-04-14 00:07:20,544] Trial 71 finished with value: 0.18903882798678318 and parameters: {'l1_ratio': 0.9954695754519097}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932344671363708
Fold 2 IBS: 0.19650092361545396
Fold 3 IBS: 0.1632403836766313
Fold 4 IBS: 0.1477673539190796
Fold 5 IBS: 0.2685406377919468
[I 2024-04-14 00:07:22,943] Trial 72 finished with value: 0.18907454914334973 and parameters: {'l1_ratio': 0.9674129718028212}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16955370403738615
Fold 2 IBS: 0.198300004340412
Fold 3 IBS: 0.16448998618700417
Fold 4 IBS: 0.14819418315475139
Fold 5 IBS: 0.2681673214544546
[I 2024-04-14 00:07:26,122] Trial 73 finished with value: 0.18974103983480167 and parameters: {'l1_ratio': 0.12420054405329062}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16935409025712936
Fold 2 IBS: 0.19652097018865705
Fold 3 IBS: 0.16324868892424002
Fold 4 IBS: 0.1478670468481683
Fold 5 IBS: 0.26844058269933146
[I 2024-04-14 00:07:28,445] Trial 74 finished with value: 0.18908627578350526 and parameters: {'l1_ratio': 0.8987598406896761}. Best is trial 31 with value: 0.18902199038509662.

Fold 1 IBS: 0.16933159838976095
Fold 2 IBS: 0.1965064417315675
Fold 3 IBS: 0.1633851894024835
Fold 4 IBS: 0.14773848846386436
Fold 5 IBS: 0.2685131075754331
[I 2024-04-14 00:07:30,711] Trial 75 finished with value: 0.1890949651126219 and parameters: {'l1_ratio': 0.9477404366976027}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16932473978852686
Fold 2 IBS: 0.19627717308437517
Fold 3 IBS: 0.16327905934000325
Fold 4 IBS: 0.14776847060934775
Fold 5 IBS: 0.2684628316037903
[I 2024-04-14 00:07:32,852] Trial 76 finished with value: 0.1890224548852087 and parameters: {'l1_ratio': 0.9794888852309296}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.1693231660203654
Fold 2 IBS: 0.19650074862145128
Fold 3 IBS: 0.16324258292199828
Fold 4 IBS: 0.14776834087788812
Fold 5 IBS: 0.2685416460331903
[I 2024-04-14 00:07:35,192] Trial 77 finished with value: 0.18907529689497868 and parameters: {'l1_ratio': 0.9680934252919277}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16934522635416993
Fold 2 IBS: 0.1965414248175579
Fold 3 IBS: 0.16325674960509248
Fold 4 IBS: 0.14776259852542778
Fold 5 IBS: 0.2684391654709519
[I 2024-04-14 00:07:37,484] Trial 78 finished with value: 0.18906903295464 and parameters: {'l1_ratio': 0.8348464698812909}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16934027966253268
Fold 2 IBS: 0.19651072412685522
Fold 3 IBS: 0.16332428786224515
Fold 4 IBS: 0.14770898109311562
Fold 5 IBS: 0.268484892973722
[I 2024-04-14 00:07:40,266] Trial 79 finished with value: 0.18907383314369414 and parameters: {'l1_ratio': 0.9281720738830627}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16937295346448544
Fold 2 IBS: 0.19656190057811196
Fold 3 IBS: 0.16330243167909347
Fold 4 IBS: 0.14786530840882278
Fold 5 IBS: 0.26845270719601905
[I 2024-04-14 00:07:42,953] Trial 80 finished with value: 0.18911106026530655 and parameters: {'l1_ratio': 0.7838500269619935}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.16931944463151896
Fold 2 IBS: 0.19627505457049513
Fold 3 IBS: 0.16329932054383856
Fold 4 IBS: 0.14780358518630324
Fold 5 IBS: 0.2684813080202751
[I 2024-04-14 00:07:45,188] Trial 81 finished with value: 0.1890357425904862 and parameters: {'l1_ratio': 0.9928090564186438}. Best is trial 31 with value: 0.18902199038509662.
Fold 1 IBS: 0.169325541797261
Fold 2 IBS: 0.19627768935286405
Fold 3 IBS: 0.16327278370996814
Fold 4 IBS: 0.14776560431772595
Fold 5 IBS: 0.2684593310434314
[I 2024-04-14 00:07:47,743] Trial 82 finished with value: 0.18902019004425008 and parameters: {'l1_ratio': 0.9775140863480035}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16935149031979288
Fold 2 IBS: 0.1965192842047653
Fold 3 IBS: 0.16326688754405383
Fold 4 IBS: 0.14787502991897095
Fold 5 IBS: 0.26844878993715177
[I 2024-04-14 00:07:50,124] Trial 83 finished with value: 0.18909229638494693 and parameters: {'l1_ratio': 0.9041484826693346}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16933170459186242
Fold 2 IBS: 0.19650651304614963
Fold 3 IBS: 0.16338442383529375
Fold 4 IBS: 0.14773812425338279
Fold 5 IBS: 0.2685127341090778
[I 2024-04-14 00:07:52,353] Trial 84 finished with value: 0.18909469996715328 and parameters: {'l1_ratio': 0.9474954953055537}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.1693218905767825
Fold 2 IBS: 0.1964999470638596
Fold 3 IBS: 0.16325259105917378
Fold 4 IBS: 0.14777283874829902
Fold 5 IBS: 0.26854624219322965
[I 2024-04-14 00:07:55,158] Trial 85 finished with value: 0.18907870192826892 and parameters: {'l1_ratio': 0.9712003433510082}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16933193641418298
Fold 2 IBS: 0.19653275389366442
Fold 3 IBS: 0.16335256945738474
Fold 4 IBS: 0.14780663250533574
Fold 5 IBS: 0.26848061755208535
[I 2024-04-14 00:07:57,410] Trial 86 finished with value: 0.18910090196453067 and parameters: {'l1_ratio': 0.8615282091613938}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16932386971368366
Fold 2 IBS: 0.19627661398449384
Fold 3 IBS: 0.16328584543616587
Fold 4 IBS: 0.14777159275019947
Fold 5 IBS: 0.2684654420433563
[I 2024-04-14 00:07:59,694] Trial 87 finished with value: 0.18902467278557983 and parameters: {'l1_ratio': 0.9816429634175655}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16933438327933317
Fold 2 IBS: 0.19650834048489285
Fold 3 IBS: 0.16336640453625556
Fold 4 IBS: 0.14772898191525546
Fold 5 IBS: 0.2685042770064275
[I 2024-04-14 00:08:01,711] Trial 88 finished with value: 0.18908847744443288 and parameters: {'l1_ratio': 0.9413643718113899}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16944596470602308
Fold 2 IBS: 0.19726694319902094
Fold 3 IBS: 0.16301178004761213
Fold 4 IBS: 0.14843778002972735
Fold 5 IBS: 0.2682813697490153
[I 2024-04-14 00:08:04,183] Trial 89 finished with value: 0.18928876754627974 and parameters: {'l1_ratio': 0.4643340820573789}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.1693462606429933
Fold 2 IBS: 0.19651448350221912
Fold 3 IBS: 0.16330360788484755
Fold 4 IBS: 0.14789102075189403
Fold 5 IBS: 0.2684657530582077
[I 2024-04-14 00:08:06,435] Trial 90 finished with value: 0.18910422516803232 and parameters: {'l1_ratio': 0.915191337511072}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16931800796438295
Fold 2 IBS: 0.1962751796079932
Fold 3 IBS: 0.1633110099595
Fold 4 IBS: 0.14780886233167587
Fold 5 IBS: 0.26848720929065717
[I 2024-04-14 00:08:08,434] Trial 91 finished with value: 0.18904005383084183 and parameters: {'l1_ratio': 0.9965063697190074}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16932014196231607
Fold 2 IBS: 0.1962782419285759
Fold 3 IBS: 0.1632663198404636
Fold 4 IBS: 0.14777903940967543
Fold 5 IBS: 0.2685519633510157
[I 2024-04-14 00:08:11,126] Trial 92 finished with value: 0.18903914129840932 and parameters: {'l1_ratio': 0.975498238789646}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16932332583890788
Fold 2 IBS: 0.19627625874608226
Fold 3 IBS: 0.16329011061811732
Fold 4 IBS: 0.14777355136531997
Fold 5 IBS: 0.2684675310039456
[I 2024-04-14 00:08:13,284] Trial 93 finished with value: 0.1890261555144746 and parameters: {'l1_ratio': 0.9829957406074067}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16931930317080282
Fold 2 IBS: 0.19652426062081635
Fold 3 IBS: 0.1632135791315565
Fold 4 IBS: 0.14785187581954887
Fold 5 IBS: 0.26842457101016753
[I 2024-04-14 00:08:15,597] Trial 94 finished with value: 0.18906671795057842 and parameters: {'l1_ratio': 0.8885105265050498}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.1693301813943178
Fold 2 IBS: 0.196505498228688
Fold 3 IBS: 0.16339539801945485
Fold 4 IBS: 0.14774335643490386
Fold 5 IBS: 0.2685179133573738
[I 2024-04-14 00:08:17,848] Trial 95 finished with value: 0.18909846948694767 and parameters: {'l1_ratio': 0.9510224428094153}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16934229540324114
Fold 2 IBS: 0.19651200548619255
Fold 3 IBS: 0.16333153430584296
Fold 4 IBS: 0.14769643631775908
Fold 5 IBS: 0.26847823366386575
[I 2024-04-14 00:08:19,901] Trial 96 finished with value: 0.18907210103538033 and parameters: {'l1_ratio': 0.9237538021205675}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16932170621981849
Fold 2 IBS: 0.19649983394146617
Fold 3 IBS: 0.16325404971141708
Fold 4 IBS: 0.1477734907480027
Fold 5 IBS: 0.26854690695992695
[I 2024-04-14 00:08:22,424] Trial 97 finished with value: 0.18907919751612629 and parameters: {'l1_ratio': 0.9716514879899321}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16932369330473146
Fold 2 IBS: 0.19627651887086875
Fold 3 IBS: 0.1632872218436579
Fold 4 IBS: 0.14777222743441737
Fold 5 IBS: 0.26846611921662916
[I 2024-04-14 00:08:24,928] Trial 98 finished with value: 0.18902515613406093 and parameters: {'l1_ratio': 0.9820812101913992}. Best is trial 82 with value: 0.18902019004425008.
Fold 1 IBS: 0.16933016173149812
Fold 2 IBS: 0.19650548515315946
Fold 3 IBS: 0.1633955404389969
Fold 4 IBS: 0.14774342409976368
Fold 5 IBS: 0.26851798272674365
[I 2024-04-14 00:08:27,768] Trial 99 finished with value: 0.18909851883003237 and parameters: {'l1_ratio': 0.9510681686622354}. Best is trial 82 with value: 0.18902019004425008.


* Best trial for IBS:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.18902019004425008], datetime_start=datetime.datetime(2024, 4, 14, 0, 7, 45, 201637), datetime_complete=datetime.datetime(2024, 4, 14, 0, 7, 47, 742524), params={'l1_ratio': 0.9775140863480035}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=82, value=None)


* Best Score for IBS:
 0.18902019004425008

In [143]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [144]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.746
train_ibs:  0.189

#### Test

In [145]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [146]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.592

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.9775140863480035)

test_ibs:  0.28

In [147]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [148]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 00:08:28,796] A new study created in memory with name: no-name-0f6c0e91-4986-40ae-8192-e0a79d80e1b1

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 00:08:43,198] Trial 0 finished with value: 0.7372744686944293 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7372744686944293.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:08:55,148] Trial 1 finished with value: 0.74027341750814 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.74027341750814.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:09:04,144] Trial 2 finished with value: 0.7431341569351123 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:09:08,172] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:09:12,150] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:09:26,494] Trial 5 finished with value: 0.7299704758481619 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:09:41,872] Trial 6 finished with value: 0.7171141106323402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:09:49,164] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 00:10:09,707] Trial 8 finished with value: 0.5225352112676056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 00:10:19,719] Trial 9 finished with value: 0.7250144025097357 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:10:20,662] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:10:26,602] Trial 11 finished with value: 0.7414728561808361 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 00:10:33,362] Trial 12 finished with value: 0.7380805853192668 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8619834498485652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1611753146667314, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:10:37,991] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1567471583060459, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 00:10:42,767] Trial 14 finished with value: 0.8012393138587386 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1306449501762567, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 00:10:47,195] Trial 15 finished with value: 0.7949512064262649 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.9835664616143871, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0921839163034627, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.

Fold 1 C-index: 0.70995670995671
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 00:10:49,774] Trial 16 finished with value: 0.7913196149300414 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9622193970781673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07748782870655765, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8839662447257384
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 00:12:49,039] Trial 17 finished with value: 0.7952544618554078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.8172323984404596, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10327357472994507, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:12:55,054] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.525862463381169, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 00:12:59,151] Trial 19 finished with value: 0.7740929694743747 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.8094383772852811, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2171861810731355, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 00:13:09,385] Trial 20 finished with value: 0.7896403509052692 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.7024632981250558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11709282828400099, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 00:13:25,502] Trial 21 finished with value: 0.7918532818563494 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.8592332834187432, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09213353726970255, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 00:13:43,314] Trial 22 finished with value: 0.7987506334970494 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9966124899846646, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.006871014098231751, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 00:30:41,799] Trial 23 finished with value: 0.7965507033377867 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8404793290892639, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 00:30:46,492] Trial 24 finished with value: 0.8010124032513863 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.8944464461493312, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003220931076182737, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:30:50,283] Trial 25 finished with value: 0.8009100471985094 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.9947609548616138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04884572997850131, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 00:30:55,834] Trial 26 finished with value: 0.8019323166712997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.8936722563667562, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 00:31:00,741] Trial 27 finished with value: 0.7848754931720334 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.7589607003643692, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05616441169904532, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 00:31:10,108] Trial 28 finished with value: 0.7687300510570361 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.47643241204116027, 'max_features': None, 'min_weight_fraction_leaf': 0.21228506833672414, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 00:31:27,626] Trial 29 finished with value: 0.791216072808157 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18639977321756945, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 00:31:45,201] Trial 30 finished with value: 0.8141045941707695 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.8995699838431843, 'max_features': None, 'min_weight_fraction_leaf': 0.048019257453591285, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 00:32:00,120] Trial 31 finished with value: 0.8102976168343801 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.8965443067001324, 'max_features': None, 'min_weight_fraction_leaf': 0.04869831874272522, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:32:10,746] Trial 32 finished with value: 0.8044151254239035 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.7822231835771817, 'max_features': None, 'min_weight_fraction_leaf': 0.05953475058332531, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:32:20,972] Trial 33 finished with value: 0.8002008917150547 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.7587808099894491, 'max_features': None, 'min_weight_fraction_leaf': 0.06414988767677843, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:32:31,776] Trial 34 finished with value: 0.802539604149412 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.9277369756073641, 'max_features': None, 'min_weight_fraction_leaf': 0.13073113131665734, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:32:43,138] Trial 35 finished with value: 0.8025908514105005 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.9215912670469352, 'max_features': None, 'min_weight_fraction_leaf': 0.12213968035691111, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:32:54,810] Trial 36 finished with value: 0.8030592181442181 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.7521477069490586, 'max_features': None, 'min_weight_fraction_leaf': 0.028614277170057895, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:33:02,282] Trial 37 finished with value: 0.7924417951105628 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.6723788047810191, 'max_features': None, 'min_weight_fraction_leaf': 0.027521497544371276, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:33:13,242] Trial 38 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.7390641925180915, 'max_features': None, 'min_weight_fraction_leaf': 0.0747020966452816, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 00:33:24,226] Trial 39 finished with value: 0.770986545074277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.6220569630425845, 'max_features': None, 'min_weight_fraction_leaf': 0.2635408988115671, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:33:32,241] Trial 40 finished with value: 0.8014911829899953 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.5663987587631532, 'max_features': None, 'min_weight_fraction_leaf': 0.07499456126338316, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:33:42,130] Trial 41 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 439, 'oob_score': True, 'max_samples': 0.7534073290864295, 'max_features': None, 'min_weight_fraction_leaf': 0.03371263169436823, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:33:51,253] Trial 42 finished with value: 0.8004185708465463 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.7191743052052858, 'max_features': None, 'min_weight_fraction_leaf': 0.03134587591441676, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:33:58,439] Trial 43 finished with value: 0.8044421817009597 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7630755401354222, 'max_features': None, 'min_weight_fraction_leaf': 0.08864460050779976, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:34:10,380] Trial 44 finished with value: 0.7970569598688273 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.6530853458961033, 'max_features': None, 'min_weight_fraction_leaf': 0.0960200605067859, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:34:14,894] Trial 45 finished with value: 0.8063373500099402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.7241711356177275, 'max_features': None, 'min_weight_fraction_leaf': 0.03945374601794358, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 00:34:32,986] Trial 46 finished with value: 0.7213832269889107 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.7253224444871529, 'max_features': None, 'min_weight_fraction_leaf': 0.03678143977799287, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:34:37,698] Trial 47 finished with value: 0.7895586843791148 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.3630824057039081, 'max_features': None, 'min_weight_fraction_leaf': 0.07375724144112171, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 00:34:57,135] Trial 48 finished with value: 0.7518177358789349 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.8664880785038714, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 00:35:01,833] Trial 49 finished with value: 0.79501517952681 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.8009921187460273, 'max_features': None, 'min_weight_fraction_leaf': 0.14468128914092981, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:35:05,035] Trial 50 finished with value: 0.8025838944631485 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.5979222342836801, 'max_features': None, 'min_weight_fraction_leaf': 0.010569144430309353, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:35:09,824] Trial 51 finished with value: 0.8027595552556749 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.737951588098304, 'max_features': None, 'min_weight_fraction_leaf': 0.08276842957644326, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:35:19,434] Trial 52 finished with value: 0.8046323522601799 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.88848382237019, 'max_features': None, 'min_weight_fraction_leaf': 0.10800154944324664, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 00:35:25,368] Trial 53 finished with value: 0.800061200877051 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.9477043092007602, 'max_features': None, 'min_weight_fraction_leaf': 0.1769969783833071, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:35:33,221] Trial 54 finished with value: 0.8075268254192226 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.8862399763900326, 'max_features': None, 'min_weight_fraction_leaf': 0.04347302641797581, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 00:35:40,640] Trial 55 finished with value: 0.8100342825585477 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.8308423379101402, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04184905264916955, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:35:56,623] Trial 56 finished with value: 0.7307990843706159 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.8390380366939857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04576803383695833, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:36:00,435] Trial 57 finished with value: 0.8035130393589224 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.862792308947798, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06959281888785387, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 00:36:08,863] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9167198766277185, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:36:15,108] Trial 59 finished with value: 0.8154047485458795 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.960673091645226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016185485823452278, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 00:36:28,360] Trial 60 finished with value: 0.7281182409672728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.9694253886674298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017099050018490658, 'warm_start': False}. Best is trial 59 with value: 0.8154047485458795.

Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:36:35,795] Trial 61 finished with value: 0.8091270566720341 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.8024635915627699, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04437120929765639, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:36:43,133] Trial 62 finished with value: 0.8100170485218674 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.8255198768266782, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04384835034305919, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:36:48,480] Trial 63 finished with value: 0.8116391962302029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.8867126274469075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018776766987265683, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:36:54,261] Trial 64 finished with value: 0.805082894192702 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.822935057311086, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012420915832592992, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:36:59,067] Trial 65 finished with value: 0.8127164933462323 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.9479411108137946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019799142307208247, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:37:03,447] Trial 66 finished with value: 0.8152263609296293 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.9503349354445524, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02249332834269111, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:37:07,791] Trial 67 finished with value: 0.8117067729375418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.947093672368275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01713780998356157, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:37:12,452] Trial 68 finished with value: 0.8089947790490772 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.944193226589343, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002610024525408112, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:37:17,654] Trial 69 finished with value: 0.816613418694436 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.9994241275208928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018458075829861618, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:37:22,628] Trial 70 finished with value: 0.8107505717647113 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.9759466742205646, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020962084356569866, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:37:27,163] Trial 71 finished with value: 0.809906689908171 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.9691411143781642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019131120871457744, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:37:31,503] Trial 72 finished with value: 0.8163018383661023 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9857485121561103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019949674867014808, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:37:36,464] Trial 73 finished with value: 0.8209526975590314 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 179, 'oob_score': True, 'max_samples': 0.9999465776424662, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0037053086158703695, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:37:42,075] Trial 74 finished with value: 0.8089728600398164 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.9451824063260522, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006367895628996485, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:37:46,935] Trial 75 finished with value: 0.8193500558621478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.9983757102481674, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00202750601418214, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:37:51,815] Trial 76 finished with value: 0.8120677808474076 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 190, 'oob_score': True, 'max_samples': 0.992384429953266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06509728021815406, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 00:37:55,248] Trial 77 finished with value: 0.8245454518214682 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'max_samples': 0.994249602929978, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003950036087865894, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:38:00,342] Trial 78 finished with value: 0.8200379214069133 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.9921516335417828, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0013870857819101067, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 00:38:03,901] Trial 79 finished with value: 0.8145453138629154 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.9936071962591497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001248251048872611, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 00:38:10,646] Trial 80 finished with value: 0.7350889356536794 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'max_samples': 0.9980073532203214, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027351555411740894, 'warm_start': False}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 00:38:14,510] Trial 81 finished with value: 0.814530945119259 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 134, 'oob_score': True, 'max_samples': 0.974317190473141, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008552111924736726, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:38:16,682] Trial 82 finished with value: 0.818405951458202 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.9200032426792089, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004694893977022773, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:38:19,746] Trial 83 finished with value: 0.816209618379516 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.9644628063092593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05687217713082389, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:38:21,535] Trial 84 finished with value: 0.8122353006098141 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 43, 'oob_score': True, 'max_samples': 0.925618686700756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002296274259735591, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:38:24,034] Trial 85 finished with value: 0.8104992933979698 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.912496637320817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06207048371618876, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:38:27,129] Trial 86 finished with value: 0.8114849995979849 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.97217788579977, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03336570424835292, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:38:29,455] Trial 87 finished with value: 0.8229024307173397 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.9977866104840274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05743230682168733, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 00:38:31,684] Trial 88 finished with value: 0.8163898256753228 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.9290745100371565, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055244525623157625, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7034313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 00:38:34,991] Trial 89 finished with value: 0.7348861423976064 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.16405866867269464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03211514251936686, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.715962441314554
[I 2024-04-14 00:38:36,901] Trial 90 finished with value: 0.7889841593617299 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 44, 'oob_score': True, 'max_samples': 0.9275901377744842, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2513921457170648, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 00:38:40,104] Trial 91 finished with value: 0.8154508585391724 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9984694614507701, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05353258404318052, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 00:38:42,898] Trial 92 finished with value: 0.7935889758097764 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9795045559078126, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30990393575918357, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 00:38:45,799] Trial 93 finished with value: 0.8139388966416563 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 93, 'oob_score': True, 'max_samples': 0.9084682802153162, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.056428548931904784, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 00:38:47,632] Trial 94 finished with value: 0.8132041893160448 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9288744492993337, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08347470326932997, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 00:38:51,675] Trial 95 finished with value: 0.8036708753502536 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9612484718465076, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09744509645373221, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 00:38:55,293] Trial 96 finished with value: 0.8082626231905751 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.8773134009465923, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0004414494070137942, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 00:38:58,249] Trial 97 finished with value: 0.825818370590428 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6924882629107981
[I 2024-04-14 00:39:01,207] Trial 98 finished with value: 0.7931972050153308 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9818733759466801, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.34016797358596224, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.869198312236287

[I 2024-04-14 00:39:08,059] A new study created in memory with name: no-name-019554d2-478d-41c0-bd85-80573e8abb24

Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:39:08,029] Trial 99 finished with value: 0.733396625437319 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.9114919789954895, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031714611388828556, 'warm_start': False}. Best is trial 97 with value: 0.825818370590428.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.825818370590428], datetime_start=datetime.datetime(2024, 4, 14, 0, 38, 55, 298295), datetime_complete=datetime.datetime(2024, 4, 14, 0, 38, 58, 248838), params={'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=97, value=None)


* Best Score for C-index:
 0.825818370590428

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1750328804590392
Fold 2 IBS: 0.2457909346263125
Fold 3 IBS: 0.16304371295824233
Fold 4 IBS: 0.15636010174832157
Fold 5 IBS: 0.23719057610640573
[I 2024-04-14 00:39:24,999] Trial 0 finished with value: 0.19548364117966427 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19548364117966427.
Fold 1 IBS: 0.18431216543925236
Fold 2 IBS: 0.20449576284397977
Fold 3 IBS: 0.1734496564138547
Fold 4 IBS: 0.1702249879841256
Fold 5 IBS: 0.22320286146192567
[I 2024-04-14 00:39:28,589] Trial 1 finished with value: 0.19113708682862765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-14 00:39:31,307] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-14 00:39:41,559] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-14 00:39:49,275] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.18112177909144025
Fold 2 IBS: 0.21559325389144568
Fold 3 IBS: 0.16126717086083114
Fold 4 IBS: 0.14612944369048034
Fold 5 IBS: 0.2233514487463136
[I 2024-04-14 00:40:00,080] Trial 5 finished with value: 0.1854926192561022 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.1741078934640366
Fold 2 IBS: 0.20103465197964324
Fold 3 IBS: 0.16459803471117013
Fold 4 IBS: 0.16185722968286678
Fold 5 IBS: 0.2275095895598425
[I 2024-04-14 00:40:11,366] Trial 6 finished with value: 0.18582147987951186 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2112963873415951
Fold 2 IBS: 0.2163217730619842
Fold 3 IBS: 0.20084732748350573
Fold 4 IBS: 0.218588755276252
Fold 5 IBS: 0.21598442308805077
[I 2024-04-14 00:40:23,363] Trial 7 finished with value: 0.21260773325027754 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-14 00:40:42,322] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.184925661127663
Fold 2 IBS: 0.2085223967682221
Fold 3 IBS: 0.17516209049302708
Fold 4 IBS: 0.17855956510549414
Fold 5 IBS: 0.2209085976393104
[I 2024-04-14 00:40:46,622] Trial 9 finished with value: 0.19361566222674337 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-14 00:41:10,305] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18095919781067835
Fold 2 IBS: 0.20577163118124792
Fold 3 IBS: 0.1716987840867246
Fold 4 IBS: 0.17502946521027946
Fold 5 IBS: 0.2198343004178619
[I 2024-04-14 00:41:21,647] Trial 11 finished with value: 0.19065867574135845 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17390057719337093
Fold 2 IBS: 0.20052745262326843
Fold 3 IBS: 0.1641107464885408
Fold 4 IBS: 0.161310620284919
Fold 5 IBS: 0.22799428371541863
[I 2024-04-14 00:41:32,368] Trial 12 finished with value: 0.18556873606110355 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18027770462477655
Fold 2 IBS: 0.21277323191047734
Fold 3 IBS: 0.16455120069297058
Fold 4 IBS: 0.1566383560604833
Fold 5 IBS: 0.22277178793167127
[I 2024-04-14 00:41:39,211] Trial 13 finished with value: 0.1874024562440758 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.19012850590013755
Fold 2 IBS: 0.2508215358616786
Fold 3 IBS: 0.16250392476408873
Fold 4 IBS: 0.13720938920743592
Fold 5 IBS: 0.2363581833511397
[I 2024-04-14 00:41:53,140] Trial 14 finished with value: 0.1954043078168961 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.8286563887351183, 'max_features': None, 'min_weight_fraction_leaf': 0.09422981531813096}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18457894361619234
Fold 2 IBS: 0.20704365739729078
Fold 3 IBS: 0.17241207107928186
Fold 4 IBS: 0.17174770550689625
Fold 5 IBS: 0.21936818212879036
[I 2024-04-14 00:42:07,092] Trial 15 finished with value: 0.1910301119456903 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.6817544899569143, 'max_features': 'auto', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 5 with value: 0.1854926192561022.

Fold 1 IBS: 0.1827776694681521
Fold 2 IBS: 0.20934680739331213
Fold 3 IBS: 0.16890212120236864
Fold 4 IBS: 0.1686588011660482
Fold 5 IBS: 0.2195767733572381
[I 2024-04-14 00:42:19,992] Trial 16 finished with value: 0.18985243451742384 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24786833673530304}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140210250926074
Fold 2 IBS: 0.22165374242688704
Fold 3 IBS: 0.20482992077952775
Fold 4 IBS: 0.2248506856151436
Fold 5 IBS: 0.21866286292181575
[I 2024-04-14 00:42:25,301] Trial 17 finished with value: 0.2168036473671963 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3527363076520275}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21398207456199575
Fold 2 IBS: 0.2210878885925555
Fold 3 IBS: 0.20500084248625938
Fold 4 IBS: 0.22467759051518113
Fold 5 IBS: 0.21837641563069746
[I 2024-04-14 00:42:37,916] Trial 18 finished with value: 0.21662496235733783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17751239261549384
Fold 2 IBS: 0.25254123379304744
Fold 3 IBS: 0.17260860317747417
Fold 4 IBS: 0.15329948726148748
Fold 5 IBS: 0.23725228156825823
[I 2024-04-14 00:42:38,894] Trial 19 finished with value: 0.1986427996831522 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.7744054221786105, 'max_features': None, 'min_weight_fraction_leaf': 0.15294426956488405}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140058010941674
Fold 2 IBS: 0.22070271305097472
Fold 3 IBS: 0.20512571269324692
Fold 4 IBS: 0.2244581340346379
Fold 5 IBS: 0.2175740773836072
[I 2024-04-14 00:42:46,276] Trial 20 finished with value: 0.21637328765132682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': None, 'min_weight_fraction_leaf': 0.3111340864325056}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17301280315188314
Fold 2 IBS: 0.19545931456517315
Fold 3 IBS: 0.1650054298323013
Fold 4 IBS: 0.1623577222774968
Fold 5 IBS: 0.22550368553678712
[I 2024-04-14 00:42:56,518] Trial 21 finished with value: 0.1842677910727283 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8774254573678859, 'max_features': None, 'min_weight_fraction_leaf': 0.38285115003898385}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17215244177111103
Fold 2 IBS: 0.18853820269712923
Fold 3 IBS: 0.16580216324267041
Fold 4 IBS: 0.16693346335577489
Fold 5 IBS: 0.22851547915283357
[I 2024-04-14 00:43:09,064] Trial 22 finished with value: 0.1843883500439038 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8533162629857436, 'max_features': None, 'min_weight_fraction_leaf': 0.39473610054688535}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17177605757487213
Fold 2 IBS: 0.1873134062038458
Fold 3 IBS: 0.16528873750502146
Fold 4 IBS: 0.16415554447420388
Fold 5 IBS: 0.22606704734165115
[I 2024-04-14 00:43:24,298] Trial 23 finished with value: 0.1829201586199189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17276619506594362
Fold 2 IBS: 0.18752575408286087
Fold 3 IBS: 0.1660506832687537
Fold 4 IBS: 0.16535591796486823
Fold 5 IBS: 0.2269916388177798
[I 2024-04-14 00:43:39,222] Trial 24 finished with value: 0.18373803784004125 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.911762237036045, 'max_features': None, 'min_weight_fraction_leaf': 0.4145963396824019}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1791579050529914
Fold 2 IBS: 0.18710203409403112
Fold 3 IBS: 0.17160657333121804
Fold 4 IBS: 0.1730776073587778
Fold 5 IBS: 0.23520287606237242
[I 2024-04-14 00:43:54,845] Trial 25 finished with value: 0.18922939917987816 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9270259482202138, 'max_features': None, 'min_weight_fraction_leaf': 0.44717127940994156}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17277943380976452
Fold 2 IBS: 0.20056722047631442
Fold 3 IBS: 0.1648928002543546
Fold 4 IBS: 0.16219739373996186
Fold 5 IBS: 0.22641514420706116
[I 2024-04-14 00:44:12,595] Trial 26 finished with value: 0.18537039849749132 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9129740059593043, 'max_features': None, 'min_weight_fraction_leaf': 0.3870919920523195}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17240759648455306
Fold 2 IBS: 0.18549219526338728
Fold 3 IBS: 0.16616481950290676
Fold 4 IBS: 0.16561034850301004
Fold 5 IBS: 0.22653216582265312
[I 2024-04-14 00:44:26,456] Trial 27 finished with value: 0.18324142511530206 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9882040097907008, 'max_features': None, 'min_weight_fraction_leaf': 0.45340256450947913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.173798138626336
Fold 2 IBS: 0.18532321108542035
Fold 3 IBS: 0.1668142641939112
Fold 4 IBS: 0.16714200768594834
Fold 5 IBS: 0.2276860831891378
[I 2024-04-14 00:44:43,177] Trial 28 finished with value: 0.18415274095615075 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9741542767559068, 'max_features': None, 'min_weight_fraction_leaf': 0.450638299943646}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.213981238234591
Fold 2 IBS: 0.22129600200231184
Fold 3 IBS: 0.20476687908413987
Fold 4 IBS: 0.22462916295400534
Fold 5 IBS: 0.21851703166023365
[I 2024-04-14 00:44:54,518] Trial 29 finished with value: 0.21663806278705633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.773357424692515, 'max_features': None, 'min_weight_fraction_leaf': 0.4837438075147879}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17449266503317365
Fold 2 IBS: 0.19742695190345053
Fold 3 IBS: 0.16471477798087575
Fold 4 IBS: 0.16267147593706363
Fold 5 IBS: 0.22648735220891497
[I 2024-04-14 00:45:07,303] Trial 30 finished with value: 0.18515864461269568 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 377, 'oob_score': False, 'max_samples': 0.9986438777088522, 'max_features': None, 'min_weight_fraction_leaf': 0.42773069772809913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18186563850382112
Fold 2 IBS: 0.18838226339150496
Fold 3 IBS: 0.1747206639662102
Fold 4 IBS: 0.17560736221213202
Fold 5 IBS: 0.23404857262959045
[I 2024-04-14 00:45:22,775] Trial 31 finished with value: 0.19092490014065175 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.939658841329532, 'max_features': None, 'min_weight_fraction_leaf': 0.4524256463348925}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398563901141657
Fold 2 IBS: 0.22134596740550985
Fold 3 IBS: 0.2048025990579434
Fold 4 IBS: 0.22461415055237854
Fold 5 IBS: 0.21851803782809134
[I 2024-04-14 00:45:35,888] Trial 32 finished with value: 0.21665327877106794 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.7396444271446992, 'max_features': None, 'min_weight_fraction_leaf': 0.4501495537267681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19337121417130673
Fold 2 IBS: 0.19511882700454072
Fold 3 IBS: 0.18642967451701625
Fold 4 IBS: 0.1895345717679471
Fold 5 IBS: 0.21856358775020004
[I 2024-04-14 00:45:51,734] Trial 33 finished with value: 0.19660357504220216 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.9933327757837453, 'max_features': None, 'min_weight_fraction_leaf': 0.49338351231891625}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397810999123087
Fold 2 IBS: 0.22130875696604183
Fold 3 IBS: 0.2047621585928816
Fold 4 IBS: 0.2246288907097577
Fold 5 IBS: 0.21863208708031015
[I 2024-04-14 00:46:04,905] Trial 34 finished with value: 0.21666200066804442 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8938554646810188, 'max_features': None, 'min_weight_fraction_leaf': 0.45754449369723726}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397501954215553
Fold 2 IBS: 0.22130442891193944
Fold 3 IBS: 0.20482836466241144
Fold 4 IBS: 0.22464430529398755
Fold 5 IBS: 0.22545436387504872
[I 2024-04-14 00:46:20,964] Trial 35 finished with value: 0.2180412964571085 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.8179898225635556, 'max_features': None, 'min_weight_fraction_leaf': 0.406528295392146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18423128002886327
Fold 2 IBS: 0.20075733721613034
Fold 3 IBS: 0.17640819175973563
Fold 4 IBS: 0.18326652441136565
Fold 5 IBS: 0.21536169700367772
[I 2024-04-14 00:46:36,835] Trial 36 finished with value: 0.1920050060839545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9504880220263004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3678752707538403}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398603848843456
Fold 2 IBS: 0.2212516593844012
Fold 3 IBS: 0.20480476599516775
Fold 4 IBS: 0.22467106118379263
Fold 5 IBS: 0.2186056754258949
[I 2024-04-14 00:46:50,029] Trial 37 finished with value: 0.2166638400955382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.6134779412492984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42910258289196446}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736188003490057
Fold 2 IBS: 0.19364285777259932
Fold 3 IBS: 0.1647798135113072
Fold 4 IBS: 0.1633666298088931
Fold 5 IBS: 0.22711044098051275
[I 2024-04-14 00:47:01,242] Trial 38 finished with value: 0.18450370848446362 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.7324083825350811, 'max_features': None, 'min_weight_fraction_leaf': 0.3267902150060746}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17613246987510892
Fold 2 IBS: 0.25370396104689813
Fold 3 IBS: 0.16470531172106329
Fold 4 IBS: 0.15671091985566343
Fold 5 IBS: 0.23754782764703308
[I 2024-04-14 00:47:18,469] Trial 39 finished with value: 0.19776009802915337 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.8998447540408812, 'max_features': None, 'min_weight_fraction_leaf': 0.26335636534084506}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139718451769373
Fold 2 IBS: 0.22132290174406308
Fold 3 IBS: 0.2049379534123754
Fold 4 IBS: 0.2246651821236489
Fold 5 IBS: 0.21845691499847839
[I 2024-04-14 00:47:29,992] Trial 40 finished with value: 0.21667095949110057 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.5051356852082238, 'max_features': None, 'min_weight_fraction_leaf': 0.46950692236254693}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736115784806322
Fold 2 IBS: 0.19708658583278066
Fold 3 IBS: 0.1647004041861114
Fold 4 IBS: 0.16193266728653144
Fold 5 IBS: 0.2269439330088383
[I 2024-04-14 00:47:40,528] Trial 41 finished with value: 0.1848550337589788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.8766530642885175, 'max_features': None, 'min_weight_fraction_leaf': 0.37480517219328874}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17445559716534967
Fold 2 IBS: 0.20736534205005006
Fold 3 IBS: 0.16501326377011497
Fold 4 IBS: 0.16209455350644228
Fold 5 IBS: 0.22737252886994871
[I 2024-04-14 00:47:54,299] Trial 42 finished with value: 0.18726025707238114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9712277852430382, 'max_features': None, 'min_weight_fraction_leaf': 0.4047116771034673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19485182356242944
Fold 2 IBS: 0.1960274570730997
Fold 3 IBS: 0.18423026068342546
Fold 4 IBS: 0.18829121228006515
Fold 5 IBS: 0.23411274191187137
[I 2024-04-14 00:48:08,164] Trial 43 finished with value: 0.19950269910217824 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8817254098792388, 'max_features': None, 'min_weight_fraction_leaf': 0.43343991639669144}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1712641582188513
Fold 2 IBS: 0.18994637490008684
Fold 3 IBS: 0.16479726253163554
Fold 4 IBS: 0.1632404230753816
Fold 5 IBS: 0.22572502599434202
[I 2024-04-14 00:48:25,250] Trial 44 finished with value: 0.18299464894405942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.9374671457275974, 'max_features': None, 'min_weight_fraction_leaf': 0.41455323262354377}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19234550794011246
Fold 2 IBS: 0.200986097128332
Fold 3 IBS: 0.1855643390306468
Fold 4 IBS: 0.1932590693758762
Fold 5 IBS: 0.21341012086817227
[I 2024-04-14 00:48:40,905] Trial 45 finished with value: 0.19711302686862794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9378530595799813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42089417671131313}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398691344914347
Fold 2 IBS: 0.22137599652455153
Fold 3 IBS: 0.20479386291855103
Fold 4 IBS: 0.2246023464574881
Fold 5 IBS: 0.21853103069298896
[I 2024-04-14 00:48:54,385] Trial 46 finished with value: 0.2166580300085446 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.7938991773051969, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4697812825251582}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1747444583541159
Fold 2 IBS: 0.23713516882516442
Fold 3 IBS: 0.16640805876585935
Fold 4 IBS: 0.1610873512530414
Fold 5 IBS: 0.234167489152576
[I 2024-04-14 00:49:11,785] Trial 47 finished with value: 0.1947085052701514 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.9498935746233631, 'max_features': None, 'min_weight_fraction_leaf': 0.33913737671094774}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398162469590376
Fold 2 IBS: 0.22136781149843104
Fold 3 IBS: 0.20480753036595514
Fold 4 IBS: 0.22461586717115936
Fold 5 IBS: 0.21858421480458282
[I 2024-04-14 00:49:25,350] Trial 48 finished with value: 0.21667140970720644 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8399357435042919, 'max_features': None, 'min_weight_fraction_leaf': 0.43949783817145754}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18607291644289184
Fold 2 IBS: 0.1997166990883884
Fold 3 IBS: 0.17871196581310303
Fold 4 IBS: 0.1866755623669813
Fold 5 IBS: 0.21401906861191788
[I 2024-04-14 00:49:39,906] Trial 49 finished with value: 0.19303924246465648 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 480, 'oob_score': False, 'max_samples': 0.9976678104279734, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4100286247036702}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398689006749297
Fold 2 IBS: 0.22138730674766524
Fold 3 IBS: 0.20483789730275198
Fold 4 IBS: 0.22469041440834978
Fold 5 IBS: 0.21866425238172585
[I 2024-04-14 00:49:50,180] Trial 50 finished with value: 0.21671335218159715 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7082075481455445, 'max_features': None, 'min_weight_fraction_leaf': 0.35750036696317244}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17354922029359332
Fold 2 IBS: 0.20364062415291528
Fold 3 IBS: 0.1656072740863152
Fold 4 IBS: 0.1629843663853799
Fold 5 IBS: 0.22805293589620068
[I 2024-04-14 00:49:57,991] Trial 51 finished with value: 0.18676688416288084 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.9128659910136828, 'max_features': None, 'min_weight_fraction_leaf': 0.3781612359397365}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1713164651684285
Fold 2 IBS: 0.1908535842776438
Fold 3 IBS: 0.16501795349457885
Fold 4 IBS: 0.16355225040434904
Fold 5 IBS: 0.22558632701889753
[I 2024-04-14 00:50:11,748] Trial 52 finished with value: 0.18326531607277957 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.8747189140359779, 'max_features': None, 'min_weight_fraction_leaf': 0.39127818009875937}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1944075620870496
Fold 2 IBS: 0.19446392844340746
Fold 3 IBS: 0.18592909130830435
Fold 4 IBS: 0.18840569735760734
Fold 5 IBS: 0.23475202007425236
[I 2024-04-14 00:50:26,731] Trial 53 finished with value: 0.19959165985412422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9590363563278936, 'max_features': None, 'min_weight_fraction_leaf': 0.47102290336229075}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398291231618569
Fold 2 IBS: 0.22130196765397775
Fold 3 IBS: 0.20479880441504156
Fold 4 IBS: 0.22463025012599544
Fold 5 IBS: 0.21857716931098428
[I 2024-04-14 00:50:38,873] Trial 54 finished with value: 0.21665822076443692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8049999889328818, 'max_features': None, 'min_weight_fraction_leaf': 0.41366841406796956}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19752377093956933
Fold 2 IBS: 0.20161258811122215
Fold 3 IBS: 0.18853359622298724
Fold 4 IBS: 0.19729854245931258
Fold 5 IBS: 0.21444154842475172
[I 2024-04-14 00:50:50,233] Trial 55 finished with value: 0.1998820092315686 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8604557082726361, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.39803093257208977}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18353091887871
Fold 2 IBS: 0.20136616660184192
Fold 3 IBS: 0.17417121851089504
Fold 4 IBS: 0.1806079641160692
Fold 5 IBS: 0.21629928891489889
[I 2024-04-14 00:51:05,145] Trial 56 finished with value: 0.191195111404483 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.9140825717192246, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.33142873928622046}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.176153787215779
Fold 2 IBS: 0.255503897064317
Fold 3 IBS: 0.16322193569881852
Fold 4 IBS: 0.15492145863817686
Fold 5 IBS: 0.23637436039500087
[I 2024-04-14 00:51:21,321] Trial 57 finished with value: 0.19723508780241844 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.846572289034959, 'max_features': None, 'min_weight_fraction_leaf': 0.1892509778618988}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21396974144117978
Fold 2 IBS: 0.22126810284573772
Fold 3 IBS: 0.20478519546942675
Fold 4 IBS: 0.22462583298910568
Fold 5 IBS: 0.2186668640880457
[I 2024-04-14 00:51:36,967] Trial 58 finished with value: 0.21666314736669912 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.9616810596485048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4994697733211825}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17564136184525772
Fold 2 IBS: 0.25480558879113324
Fold 3 IBS: 0.1643534207862224
Fold 4 IBS: 0.1574357976027508
Fold 5 IBS: 0.24128856654900457
[I 2024-04-14 00:51:40,266] Trial 59 finished with value: 0.19870494711487374 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9304423548229083, 'max_features': None, 'min_weight_fraction_leaf': 0.30249606930327194}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397063753981885
Fold 2 IBS: 0.22120321030131956
Fold 3 IBS: 0.20498353734020044
Fold 4 IBS: 0.22465541176579787
Fold 5 IBS: 0.21817456614748645
[I 2024-04-14 00:51:53,546] Trial 60 finished with value: 0.21659747261892465 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.2967533381027988, 'max_features': None, 'min_weight_fraction_leaf': 0.45702707568744816}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1723055398262932
Fold 2 IBS: 0.19143168367074548
Fold 3 IBS: 0.16495123980236973
Fold 4 IBS: 0.16377185203308486
Fold 5 IBS: 0.22590801582391506
[I 2024-04-14 00:52:04,655] Trial 61 finished with value: 0.18367366623128167 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.8753600395959259, 'max_features': None, 'min_weight_fraction_leaf': 0.3908186672612388}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1734277654013816
Fold 2 IBS: 0.20401881796514246
Fold 3 IBS: 0.16490921556493102
Fold 4 IBS: 0.1622125526423405
Fold 5 IBS: 0.2282204138485982
[I 2024-04-14 00:52:15,866] Trial 62 finished with value: 0.18655775308447872 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.8863444595022553, 'max_features': None, 'min_weight_fraction_leaf': 0.3630397965166024}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17425299200408814
Fold 2 IBS: 0.19784814184405533
Fold 3 IBS: 0.16448226706235544
Fold 4 IBS: 0.16221744449574835
Fold 5 IBS: 0.22561034364497506
[I 2024-04-14 00:52:30,712] Trial 63 finished with value: 0.18488223781024446 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.9774803581744468, 'max_features': None, 'min_weight_fraction_leaf': 0.422237244496606}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.17214163753608527
Fold 2 IBS: 0.19020363580055616
Fold 3 IBS: 0.16550959046326688
Fold 4 IBS: 0.16526794959392554
Fold 5 IBS: 0.22833087784482511
[I 2024-04-14 00:52:42,122] Trial 64 finished with value: 0.1842907382477318 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.8662053800926933, 'max_features': None, 'min_weight_fraction_leaf': 0.39542258978805284}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139792007492792
Fold 2 IBS: 0.22131668306329724
Fold 3 IBS: 0.20481655835559517
Fold 4 IBS: 0.22465389902940344
Fold 5 IBS: 0.2186107338002615
[I 2024-04-14 00:52:52,855] Trial 65 finished with value: 0.21667541499956733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 370, 'oob_score': False, 'max_samples': 0.8126605473414451, 'max_features': None, 'min_weight_fraction_leaf': 0.4432122195886301}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139839404571568
Fold 2 IBS: 0.22128662025715748
Fold 3 IBS: 0.20475660906152154
Fold 4 IBS: 0.22463254345676723
Fold 5 IBS: 0.2185879578955235
[I 2024-04-14 00:53:05,530] Trial 66 finished with value: 0.2166495342256253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.7628822009195562, 'max_features': None, 'min_weight_fraction_leaf': 0.4806954217012357}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17446682144724857
Fold 2 IBS: 0.20343226965949585
Fold 3 IBS: 0.16509877229395598
Fold 4 IBS: 0.16272402121276544
Fold 5 IBS: 0.22837609800630052
[I 2024-04-14 00:53:15,494] Trial 67 finished with value: 0.18681959652395327 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9273407143986389, 'max_features': None, 'min_weight_fraction_leaf': 0.3829484376044615}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139737017543663
Fold 2 IBS: 0.22132584453552323
Fold 3 IBS: 0.20489534413800095
Fold 4 IBS: 0.22458301458145777
Fold 5 IBS: 0.21855108631457426
[I 2024-04-14 00:53:29,225] Trial 68 finished with value: 0.21666579826478452 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.4560255505580615, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.43542376867133237}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18183019653099627
Fold 2 IBS: 0.20776625174627097
Fold 3 IBS: 0.16953634624872876
Fold 4 IBS: 0.170118714579068
Fold 5 IBS: 0.21958622926343907
[I 2024-04-14 00:53:44,333] Trial 69 finished with value: 0.18976754767370063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.970602689136413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.263156524754376}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398228747656492
Fold 2 IBS: 0.22137876391118777
Fold 3 IBS: 0.20476882960361822
Fold 4 IBS: 0.22463276305816607
Fold 5 IBS: 0.21856497560430035
[I 2024-04-14 00:53:58,167] Trial 70 finished with value: 0.21666552393076746 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 465, 'oob_score': False, 'max_samples': 0.9012147144740991, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.46397187987790006}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17367631623248717
Fold 2 IBS: 0.18729177749490242
Fold 3 IBS: 0.16716923559227603
Fold 4 IBS: 0.16896965253402357
Fold 5 IBS: 0.22871507732594165
[I 2024-04-14 00:54:07,601] Trial 71 finished with value: 0.1851644118359262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.8369240734764914, 'max_features': None, 'min_weight_fraction_leaf': 0.3894108977238639}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17623676574788
Fold 2 IBS: 0.18722146882244894
Fold 3 IBS: 0.16923825257873615
Fold 4 IBS: 0.17041309974033034
Fold 5 IBS: 0.2308208580988099
[I 2024-04-14 00:54:18,796] Trial 72 finished with value: 0.1867860889976411 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.8867920327737324, 'max_features': None, 'min_weight_fraction_leaf': 0.4157314879593541}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17466534845952894
Fold 2 IBS: 0.21319655330881065
Fold 3 IBS: 0.165618296143337
Fold 4 IBS: 0.1624164693292741
Fold 5 IBS: 0.22901894445979137
[I 2024-04-14 00:54:29,041] Trial 73 finished with value: 0.1889831223401484 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9448081876116871, 'max_features': None, 'min_weight_fraction_leaf': 0.37829799509574824}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19283001171526404
Fold 2 IBS: 0.25233074235756864
Fold 3 IBS: 0.16531718816798083
Fold 4 IBS: 0.1371287117522084
Fold 5 IBS: 0.23777310085766115
[I 2024-04-14 00:54:40,588] Trial 74 finished with value: 0.1970759509701366 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.8560145872964813, 'max_features': None, 'min_weight_fraction_leaf': 0.028106730951250714}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1765526886203159
Fold 2 IBS: 0.24189641128474174
Fold 3 IBS: 0.16693060419975347
Fold 4 IBS: 0.16161303135180896
Fold 5 IBS: 0.2376375116037371
[I 2024-04-14 00:54:47,468] Trial 75 finished with value: 0.19692604941207142 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.9957860072135883, 'max_features': None, 'min_weight_fraction_leaf': 0.34756145962819307}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1751244271301782
Fold 2 IBS: 0.24107670158411845
Fold 3 IBS: 0.16626442192082944
Fold 4 IBS: 0.16107692991176065
Fold 5 IBS: 0.23441060343413975
[I 2024-04-14 00:54:55,760] Trial 76 finished with value: 0.1955906167962053 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.9214268543378774, 'max_features': None, 'min_weight_fraction_leaf': 0.32041444551979115}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398382567775925
Fold 2 IBS: 0.22132197857579206
Fold 3 IBS: 0.20483550783639218
Fold 4 IBS: 0.22469410346846014
Fold 5 IBS: 0.2185234061706301
[I 2024-04-14 00:55:06,848] Trial 77 finished with value: 0.21667176434580676 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': None, 'min_weight_fraction_leaf': 0.4816802580265169}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139815287454151
Fold 2 IBS: 0.22144251355248706
Fold 3 IBS: 0.20476517865000235
Fold 4 IBS: 0.22461967295013774
Fold 5 IBS: 0.21859926137399327
[I 2024-04-14 00:55:20,076] Trial 78 finished with value: 0.21668163105440713 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.8709125293011857, 'max_features': None, 'min_weight_fraction_leaf': 0.4500024716514146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21393847873679495
Fold 2 IBS: 0.2206352907056855
Fold 3 IBS: 0.2052031401141122
Fold 4 IBS: 0.22465935825676747
Fold 5 IBS: 0.2170322205916447
[I 2024-04-14 00:55:30,790] Trial 79 finished with value: 0.21629369768100096 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': None, 'min_weight_fraction_leaf': 0.40382275005132695}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398666839515476
Fold 2 IBS: 0.22133561292920703
Fold 3 IBS: 0.20476084552868884
Fold 4 IBS: 0.22460858228328426
Fold 5 IBS: 0.21850495327987215
[I 2024-04-14 00:55:45,434] Trial 80 finished with value: 0.2166393324832414 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.7543724309332009, 'max_features': None, 'min_weight_fraction_leaf': 0.43164085935118673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1718240887458899
Fold 2 IBS: 0.191437443203446
Fold 3 IBS: 0.16491345446124533
Fold 4 IBS: 0.16398408770898562
Fold 5 IBS: 0.22656733476064983
[I 2024-04-14 00:55:56,114] Trial 81 finished with value: 0.18374528177604332 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.8723363913158229, 'max_features': None, 'min_weight_fraction_leaf': 0.39397540986506063}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17374604878476174
Fold 2 IBS: 0.19798109455852192
Fold 3 IBS: 0.16401735622550842
Fold 4 IBS: 0.1619573282383729
Fold 5 IBS: 0.22581911344299607
[I 2024-04-14 00:56:06,015] Trial 82 finished with value: 0.1847041882500322 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8247493235113283, 'max_features': None, 'min_weight_fraction_leaf': 0.3601096556690917}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17340750457612014
Fold 2 IBS: 0.1865209431926325
Fold 3 IBS: 0.16660200760670268
Fold 4 IBS: 0.16731704053628665
Fold 5 IBS: 0.23067593415026993
[I 2024-04-14 00:56:16,606] Trial 83 finished with value: 0.1849046860124024 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.8997196592880778, 'max_features': None, 'min_weight_fraction_leaf': 0.42074986147139254}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17452011364531658
Fold 2 IBS: 0.21400766260887688
Fold 3 IBS: 0.16568783150449218
Fold 4 IBS: 0.16229140988658286
Fold 5 IBS: 0.22955502465730293
[I 2024-04-14 00:56:29,600] Trial 84 finished with value: 0.1892124084605143 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.9496964476824827, 'max_features': None, 'min_weight_fraction_leaf': 0.37072364798951474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17525073412789557
Fold 2 IBS: 0.2105659370926584
Fold 3 IBS: 0.16602025501429193
Fold 4 IBS: 0.1622139028904671
Fold 5 IBS: 0.22956434629388905
[I 2024-04-14 00:56:39,165] Trial 85 finished with value: 0.18872303508384042 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.9768787275271766, 'max_features': None, 'min_weight_fraction_leaf': 0.389212711709705}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139824234419341
Fold 2 IBS: 0.22136539954988055
Fold 3 IBS: 0.204822165703736
Fold 4 IBS: 0.22464122963551408
Fold 5 IBS: 0.2185219969232711
[I 2024-04-14 00:56:50,546] Trial 86 finished with value: 0.21666664305086716 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.7799819637825093, 'max_features': None, 'min_weight_fraction_leaf': 0.4000713988176814}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.20027780376461612
Fold 2 IBS: 0.20307340294666915
Fold 3 IBS: 0.19102009672018105
Fold 4 IBS: 0.20003685084746606
Fold 5 IBS: 0.21421965519619954
[I 2024-04-14 00:57:02,377] Trial 87 finished with value: 0.20172556189502638 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.9292189383035607, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4390757544239005}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398570828038652
Fold 2 IBS: 0.22140151761658128
Fold 3 IBS: 0.2048003761944947
Fold 4 IBS: 0.22459594623574206
Fold 5 IBS: 0.21853396569713832
[I 2024-04-14 00:57:16,991] Trial 88 finished with value: 0.2166635028048686 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 488, 'oob_score': False, 'max_samples': 0.7896863299148335, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.45607963249620537}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17203791887421
Fold 2 IBS: 0.18726791026590833
Fold 3 IBS: 0.16576625757294128
Fold 4 IBS: 0.16530852151519143
Fold 5 IBS: 0.22888342314880578
[I 2024-04-14 00:57:29,948] Trial 89 finished with value: 0.18385280627541137 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8904926128857917, 'max_features': None, 'min_weight_fraction_leaf': 0.4120116856268681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1940772853656249
Fold 2 IBS: 0.2004241668146479
Fold 3 IBS: 0.18634724520921406
Fold 4 IBS: 0.19496657142921314
Fold 5 IBS: 0.21367459762057212
[I 2024-04-14 00:57:42,887] Trial 90 finished with value: 0.19789797328785444 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.9106880455831121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.40976298541889333}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1926191075437479
Fold 2 IBS: 0.19415079186842468
Fold 3 IBS: 0.18487947833584825
Fold 4 IBS: 0.18641681431445226
Fold 5 IBS: 0.23439208959229954
[I 2024-04-14 00:57:55,481] Trial 91 finished with value: 0.1984916563309545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.8647633953620859, 'max_features': None, 'min_weight_fraction_leaf': 0.42597944887100797}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17236214134250716
Fold 2 IBS: 0.19455412228125918
Fold 3 IBS: 0.16427712812224537
Fold 4 IBS: 0.162949090773761
Fold 5 IBS: 0.2259494780328012
[I 2024-04-14 00:58:10,512] Trial 92 finished with value: 0.18401839211051477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.8900467044086138, 'max_features': None, 'min_weight_fraction_leaf': 0.3893348459268057}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17257330060839252
Fold 2 IBS: 0.18644424300898413
Fold 3 IBS: 0.167229764854462
Fold 4 IBS: 0.16728718203115409
Fold 5 IBS: 0.22779364161313018
[I 2024-04-14 00:58:25,410] Trial 93 finished with value: 0.18426562642322458 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.951027581141039, 'max_features': None, 'min_weight_fraction_leaf': 0.44280477596355444}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17363154839056466
Fold 2 IBS: 0.22743622651322085
Fold 3 IBS: 0.1659053390876856
Fold 4 IBS: 0.1617200646570578
Fold 5 IBS: 0.2317058059728232
[I 2024-04-14 00:58:40,359] Trial 94 finished with value: 0.1920797969242704 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.8997870199007337, 'max_features': None, 'min_weight_fraction_leaf': 0.3407068895244753}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1742039929754336
Fold 2 IBS: 0.22427050607023472
Fold 3 IBS: 0.1662296675861061
Fold 4 IBS: 0.16181525206129235
Fold 5 IBS: 0.2312628649338052
[I 2024-04-14 00:58:54,632] Trial 95 finished with value: 0.1915564567253744 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.9777582543649842, 'max_features': None, 'min_weight_fraction_leaf': 0.37055856104990403}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.18206223269633873
Fold 2 IBS: 0.18820585180072097
Fold 3 IBS: 0.17369714014143833
Fold 4 IBS: 0.1751220212365198
Fold 5 IBS: 0.22437209861320465
[I 2024-04-14 00:59:08,459] Trial 96 finished with value: 0.1886918688976445 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.8430407084230132, 'max_features': None, 'min_weight_fraction_leaf': 0.41419337591128474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17261810934600746
Fold 2 IBS: 0.19291443628076307
Fold 3 IBS: 0.16469348295311864
Fold 4 IBS: 0.16293280131529528
Fold 5 IBS: 0.2265701418039605
[I 2024-04-14 00:59:23,374] Trial 97 finished with value: 0.183945794339829 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.8784577990568653, 'max_features': None, 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1806635839384418
Fold 2 IBS: 0.18847632703053457
Fold 3 IBS: 0.17326431415814442
Fold 4 IBS: 0.17486447351236495
Fold 5 IBS: 0.2258002518864047
[I 2024-04-14 00:59:38,317] Trial 98 finished with value: 0.18861379010517812 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.8075349562887142, 'max_features': None, 'min_weight_fraction_leaf': 0.3942015894342152}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17457318039218142
Fold 2 IBS: 0.19576662913389825
Fold 3 IBS: 0.1643932476316186
Fold 4 IBS: 0.16120104626761333
Fold 5 IBS: 0.22682167562644817
[I 2024-04-14 00:59:45,651] Trial 99 finished with value: 0.18455115581035195 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.8213734885898443, 'max_features': None, 'min_weight_fraction_leaf': 0.35155796421429664}. Best is trial 23 with value: 0.1829201586199189.


* Best trial for IBS:
 FrozenTrial(number=23, state=TrialState.COMPLETE, values=[0.1829201586199189], datetime_start=datetime.datetime(2024, 4, 14, 0, 43, 9, 73146), datetime_complete=datetime.datetime(2024, 4, 14, 0, 43, 24, 297962), params={'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=23, value=None)


* Best Score for IBS:
 0.1829201586199189

In [149]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [150]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.183

#### Test

In [151]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [152]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=19, max_features='log2', max_leaf_nodes=15,
                     max_samples=0.9995515317027949, min_samples_split=18,
                     min_weight_fraction_leaf=0.032175807966512454,
                     n_estimators=115, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.653

RandomSurvivalForest(max_depth=20, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9248759152889626, min_samples_split=2,
                     min_weight_fraction_leaf=0.41894325026727597,
                     n_estimators=396, random_state=123)

test_ibs:  0.206

In [153]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [154]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [155]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 00:59:49,769] A new study created in memory with name: no-name-a9aa1914-577b-4f77-818c-8c1a81f29400

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 00:59:52,275] Trial 0 finished with value: 0.7836129950691764 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:00:01,038] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:00:14,408] Trial 2 finished with value: 0.7556152507681301 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:00:15,598] Trial 3 finished with value: 0.7717160075913865 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:00:20,760] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:00:26,211] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:00:29,050] Trial 6 finished with value: 0.7781769130770997 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:00:35,880] Trial 7 finished with value: 0.7508462032035622 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:00:36,268] Trial 8 finished with value: 0.7684324398125025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:00:52,267] Trial 9 finished with value: 0.7552175391299489 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:01:00,955] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:01:06,301] Trial 11 finished with value: 0.7698273464882801 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 01:01:09,842] Trial 12 finished with value: 0.7914452579440178 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 01:01:13,451] Trial 13 finished with value: 0.7653468723507815 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:01:16,579] Trial 14 finished with value: 0.7661538756898894 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8284313725490197

Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:01:18,629] Trial 15 finished with value: 0.7684393821468035 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6267605633802817
[I 2024-04-14 01:01:22,286] Trial 16 finished with value: 0.77051229268592 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:01:24,654] Trial 17 finished with value: 0.7723249788334919 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:01:28,961] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:01:32,050] Trial 19 finished with value: 0.765551411653658 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 01:01:32,384] Trial 20 finished with value: 0.7391209661793047 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 01:01:35,822] Trial 21 finished with value: 0.7817887210557736 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 01:01:39,022] Trial 22 finished with value: 0.7809862642199459 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:01:41,938] Trial 23 finished with value: 0.7759304206293289 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4155863532247274, 'min_weight_fraction_leaf': 0.07928484585286968}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 01:01:45,392] Trial 24 finished with value: 0.7747196235015181 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.00901469432212705}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 01:01:48,402] Trial 25 finished with value: 0.780898135887688 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.895337843232826, 'min_weight_fraction_leaf': 0.09625756753241399}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:02:00,733] Trial 26 finished with value: 0.7535362780827659 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5901308628926357, 'min_weight_fraction_leaf': 0.04311046725313979}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:02:02,710] Trial 27 finished with value: 0.7700615298551389 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 01:02:06,596] Trial 28 finished with value: 0.7607683592529704 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:02:14,265] Trial 29 finished with value: 0.783702202780981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.11187426524781394}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:02:20,994] Trial 30 finished with value: 0.7671596620665804 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.23846812660748434}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 01:02:28,897] Trial 31 finished with value: 0.7712482704957379 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9319495980432307, 'min_weight_fraction_leaf': 0.028814153765248245}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:02:36,319] Trial 32 finished with value: 0.7875856659621985 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.83936093173654, 'min_weight_fraction_leaf': 0.10465149498791723}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:02:43,251] Trial 33 finished with value: 0.7854274383297459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8110657459614115, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 01:02:50,220] Trial 34 finished with value: 0.7875712972185422 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8312111470897382, 'min_weight_fraction_leaf': 0.11396804804122496}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:02:57,175] Trial 35 finished with value: 0.7805626784012362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8317242802235407, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 01:03:10,866] Trial 36 finished with value: 0.7392301426964731 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.919159658755392, 'min_weight_fraction_leaf': 0.12417590138595275}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 01:03:18,246] Trial 37 finished with value: 0.7733460193912409 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9384999627665201, 'min_weight_fraction_leaf': 0.21309962076960762}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 01:03:23,988] Trial 38 finished with value: 0.7639313460923033 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 345, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7810779808078776, 'min_weight_fraction_leaf': 0.2883645958901683}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:03:39,015] Trial 39 finished with value: 0.7557517610684528 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 438, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7126142286152415, 'min_weight_fraction_leaf': 0.051535007757158066}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:03:46,092] Trial 40 finished with value: 0.7815020978326014 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6423525258918861, 'min_weight_fraction_leaf': 0.12542889840419838}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:03:52,538] Trial 41 finished with value: 0.7864193339372411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 449, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8300934016687722, 'min_weight_fraction_leaf': 0.10960380301974583}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:03:58,714] Trial 42 finished with value: 0.7880709509204418 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 420, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0742644879267989}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 01:04:04,808] Trial 43 finished with value: 0.7828465399677109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 413, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7812921734334815, 'min_weight_fraction_leaf': 0.07650726650715535}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 01:04:11,716] Trial 44 finished with value: 0.7803513206203079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9997498444523031, 'min_weight_fraction_leaf': 0.1566845549254962}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 01:04:19,092] Trial 45 finished with value: 0.7788761410494602 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 498, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9223521852303842, 'min_weight_fraction_leaf': 0.059273843380186375}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:04:26,135] Trial 46 finished with value: 0.7685371916964001 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 454, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9500103809873137, 'min_weight_fraction_leaf': 0.03660618092052255}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 01:04:39,347] Trial 47 finished with value: 0.742317931200098 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8574312076294325, 'min_weight_fraction_leaf': 0.08931620844737977}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:04:45,352] Trial 48 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.755266816507861, 'min_weight_fraction_leaf': 0.020812961475463188}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:04:47,766] Trial 49 finished with value: 0.7845202124432327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.814593864444954, 'min_weight_fraction_leaf': 0.09888902748696558}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:04:53,265] Trial 50 finished with value: 0.7773994153326739 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 367, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6864757488123517, 'min_weight_fraction_leaf': 0.0622709472266257}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 01:05:00,442] Trial 51 finished with value: 0.7857905817313229 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 477, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8138857282473038, 'min_weight_fraction_leaf': 0.139261908142962}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:05:07,121] Trial 52 finished with value: 0.7754721899619019 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 483, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.897591154770797, 'min_weight_fraction_leaf': 0.18036745341019644}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:05:13,737] Trial 53 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8040300125345899, 'min_weight_fraction_leaf': 0.13782166853114988}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:05:20,839] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8778737344226841, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 01:05:24,801] Trial 55 finished with value: 0.7758270084642879 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7446102701098806, 'min_weight_fraction_leaf': 0.0765135926752003}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 01:05:31,151] Trial 56 finished with value: 0.7744763834479156 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 431, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957871319428308, 'min_weight_fraction_leaf': 0.15347039261632256}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:05:38,428] Trial 57 finished with value: 0.7699442097541136 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 490, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651987019932437, 'min_weight_fraction_leaf': 0.1066939379481781}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 01:05:51,989] Trial 58 finished with value: 0.7510997177927557 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8492110159158694, 'min_weight_fraction_leaf': 0.1370897749041413}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:05:56,144] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3278490557085546, 'min_weight_fraction_leaf': 0.20658865997161166}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 01:06:02,632] Trial 60 finished with value: 0.7646046839942156 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.2714828861387636}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:06:09,239] Trial 61 finished with value: 0.7875908032299939 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8197782912980647, 'min_weight_fraction_leaf': 0.11182880406892551}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:06:16,103] Trial 62 finished with value: 0.7867469213734538 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7728729369504425, 'min_weight_fraction_leaf': 0.08684392452952273}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 01:06:22,708] Trial 63 finished with value: 0.7798808652133927 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7730739126088626, 'min_weight_fraction_leaf': 0.08638346674570552}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:06:29,675] Trial 64 finished with value: 0.7930563544969358 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 397, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7094023899138029, 'min_weight_fraction_leaf': 0.016985502713105286}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 01:06:36,001] Trial 65 finished with value: 0.7782230230703928 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5432894752024745, 'min_weight_fraction_leaf': 0.021766672705799798}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:06:38,899] Trial 66 finished with value: 0.7938811826372392 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7228780771138192, 'min_weight_fraction_leaf': 0.0031520648190986253}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:06:41,491] Trial 67 finished with value: 0.7920349896145755 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7208856143139186, 'min_weight_fraction_leaf': 0.000720456341576893}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:06:44,074] Trial 68 finished with value: 0.794041883921594 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7036950154527627, 'min_weight_fraction_leaf': 0.005216408266220198}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 01:06:46,544] Trial 69 finished with value: 0.7859079077910682 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7175215556344815, 'min_weight_fraction_leaf': 0.011727820970865974}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 01:06:56,083] Trial 70 finished with value: 0.751088073319086 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7068868150575319, 'min_weight_fraction_leaf': 0.04275053996657477}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:06:58,921] Trial 71 finished with value: 0.7894658722092704 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6765833323968065, 'min_weight_fraction_leaf': 0.0056539519960706885}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:07:01,237] Trial 72 finished with value: 0.7914342067886004 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 303, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6657543859502482, 'min_weight_fraction_leaf': 0.0007645303007875817}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:03,581] Trial 73 finished with value: 0.7939687176512447 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.0006629495375479764}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:07:05,768] Trial 74 finished with value: 0.7929417632058738 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6089504598680775, 'min_weight_fraction_leaf': 0.009816745037317486}. Best is trial 68 with value: 0.794041883921594.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:08,009] Trial 75 finished with value: 0.7886490466297866 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.532426516857448, 'min_weight_fraction_leaf': 0.0002663514949337425}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:10,377] Trial 76 finished with value: 0.7801220886659336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6123538402148698, 'min_weight_fraction_leaf': 0.019649932961991672}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:12,568] Trial 77 finished with value: 0.7814522179558544 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5811927471801297, 'min_weight_fraction_leaf': 0.04878077669029726}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 01:07:15,096] Trial 78 finished with value: 0.7845818837754068 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6462796252211019, 'min_weight_fraction_leaf': 0.03369012476405811}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:07:17,666] Trial 79 finished with value: 0.7787001559323222 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5164947678000329, 'min_weight_fraction_leaf': 0.01622265318172269}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:07:19,575] Trial 80 finished with value: 0.7818525173809616 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 243, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6235631347306672, 'min_weight_fraction_leaf': 0.031552173049052425}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:07:22,401] Trial 81 finished with value: 0.7905684059227995 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6646517878972749, 'min_weight_fraction_leaf': 0.003319138338666917}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 01:07:25,531] Trial 82 finished with value: 0.7915344293360062 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6559993331175135, 'min_weight_fraction_leaf': 0.0007051454739791334}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:28,504] Trial 83 finished with value: 0.784834519027793 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6078088154987048, 'min_weight_fraction_leaf': 0.05269795093090639}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:30,753] Trial 84 finished with value: 0.7876737917407194 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 252, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.56420075442896, 'min_weight_fraction_leaf': 0.0001867103765655385}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 01:07:32,957] Trial 85 finished with value: 0.7941830791944973 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 01:07:35,191] Trial 86 finished with value: 0.7910103136701933 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7300691279502551, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:37,118] Trial 87 finished with value: 0.7870370369739819 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6972914076775041, 'min_weight_fraction_leaf': 0.042431862202902404}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 01:07:44,488] Trial 88 finished with value: 0.7393760229419569 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.592229960198248, 'min_weight_fraction_leaf': 0.016246248347428313}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:07:46,900] Trial 89 finished with value: 0.7766334763698508 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45159856922443276, 'min_weight_fraction_leaf': 0.05921570024221322}. Best is trial 85 with value: 0.7941830791944973.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 01:07:49,470] Trial 90 finished with value: 0.7708838065283327 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7242276540625545, 'min_weight_fraction_leaf': 0.34283486638092503}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:52,237] Trial 91 finished with value: 0.7895419037726438 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6583630297112304, 'min_weight_fraction_leaf': 0.013827947129714684}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:54,666] Trial 92 finished with value: 0.7920954683515248 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7515631882154823, 'min_weight_fraction_leaf': 0.028988151290404485}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:07:57,129] Trial 93 finished with value: 0.7937492188401966 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 304, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7381814767748153, 'min_weight_fraction_leaf': 0.030278173261689908}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:07:59,442] Trial 94 finished with value: 0.7930758605083875 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6942749611849839, 'min_weight_fraction_leaf': 0.02829541014533638}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 01:08:01,614] Trial 95 finished with value: 0.7862754612128648 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.750467494063393, 'min_weight_fraction_leaf': 0.03084864174659612}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:08:04,044] Trial 96 finished with value: 0.7937809600898336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6916627249534713, 'min_weight_fraction_leaf': 0.0642170412166308}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:08:06,384] Trial 97 finished with value: 0.7922100596425867 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6847338071332475, 'min_weight_fraction_leaf': 0.06422450776206082}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 01:08:08,653] Trial 98 finished with value: 0.7896281650393346 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6945703344834594, 'min_weight_fraction_leaf': 0.06929480157264988}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608

[I 2024-04-14 01:08:10,295] A new study created in memory with name: no-name-fdf20b21-32d4-4c69-982a-4bb4cb5fed3b

Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 01:08:10,286] Trial 99 finished with value: 0.7912614087353609 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6926648599741109, 'min_weight_fraction_leaf': 0.05098663692788332}. Best is trial 85 with value: 0.7941830791944973.


* Best trial for C-index:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.7941830791944973], datetime_start=datetime.datetime(2024, 4, 14, 1, 7, 30, 760433), datetime_complete=datetime.datetime(2024, 4, 14, 1, 7, 32, 956567), params={'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for C-index:
 0.7941830791944973

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16943133784699038
Fold 2 IBS: 0.217110921492143
Fold 3 IBS: 0.16458005935948244
Fold 4 IBS: 0.15978141365273868
Fold 5 IBS: 0.23006411985790817
[I 2024-04-14 01:08:20,128] Trial 0 finished with value: 0.18819357044185253 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 01:08:35,113] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.1920088773895634
Fold 2 IBS: 0.20722305192399237
Fold 3 IBS: 0.1843664308419076
Fold 4 IBS: 0.19578634061172853
Fold 5 IBS: 0.21729770324619507
[I 2024-04-14 01:08:47,093] Trial 2 finished with value: 0.1993364808026774 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.19258828625505786
Fold 2 IBS: 0.2045422331943319
Fold 3 IBS: 0.1853898388957368
Fold 4 IBS: 0.19796057104495973
Fold 5 IBS: 0.21730311317672968
[I 2024-04-14 01:08:50,972] Trial 3 finished with value: 0.1995568085133632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 01:09:01,378] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 01:09:07,078] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.17108054547230092
Fold 2 IBS: 0.21332710542268465
Fold 3 IBS: 0.1636503921602676
Fold 4 IBS: 0.1601897971404523
Fold 5 IBS: 0.23011170771684802
[I 2024-04-14 01:09:18,611] Trial 6 finished with value: 0.1876719095825107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.1802257330412862
Fold 2 IBS: 0.20553844032632104
Fold 3 IBS: 0.17516423786860197
Fold 4 IBS: 0.18156654611164302
Fold 5 IBS: 0.21889734913100833
[I 2024-04-14 01:09:25,308] Trial 7 finished with value: 0.1922784612957721 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19324605458737515
Fold 2 IBS: 0.20063316435414258
Fold 3 IBS: 0.18395193632306783
Fold 4 IBS: 0.19657870618224477
Fold 5 IBS: 0.2180785905917539
[I 2024-04-14 01:09:26,890] Trial 8 finished with value: 0.19849769040771686 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19947118578728948
Fold 2 IBS: 0.2128915375997729
Fold 3 IBS: 0.19180552923211425
Fold 4 IBS: 0.21059003168383789
Fold 5 IBS: 0.2166615073888468
[I 2024-04-14 01:09:41,330] Trial 9 finished with value: 0.20628395833837226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.21397612241164576
Fold 2 IBS: 0.2207394210478338
Fold 3 IBS: 0.20537940251283027
Fold 4 IBS: 0.22474853253260105
Fold 5 IBS: 0.2174222289467434
[I 2024-04-14 01:09:52,815] Trial 10 finished with value: 0.21645314149033087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.2015386647704584
Fold 2 IBS: 0.21349515547127124
Fold 3 IBS: 0.19259186402255285
Fold 4 IBS: 0.21338933172129262
Fold 5 IBS: 0.21568498079724013
[I 2024-04-14 01:10:01,799] Trial 11 finished with value: 0.20733999935656305 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.16481288780890282
Fold 2 IBS: 0.2210169243096472
Fold 3 IBS: 0.1621024154551832
Fold 4 IBS: 0.1533029510139564
Fold 5 IBS: 0.23439416692917028
[I 2024-04-14 01:10:14,723] Trial 12 finished with value: 0.18712586910337198 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17402283336818236
Fold 2 IBS: 0.2087374728480146
Fold 3 IBS: 0.17174698691539156
Fold 4 IBS: 0.17261429502370135
Fold 5 IBS: 0.22300398757472922
[I 2024-04-14 01:10:28,065] Trial 13 finished with value: 0.19002511514600381 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.2139646814364898
Fold 2 IBS: 0.22074056096749928
Fold 3 IBS: 0.20501656315227804
Fold 4 IBS: 0.22494601314735585
Fold 5 IBS: 0.21705148409657263
[I 2024-04-14 01:10:38,463] Trial 14 finished with value: 0.21634386056003913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.18712586910337198.

Fold 1 IBS: 0.21400643269593325
Fold 2 IBS: 0.22111219981278188
Fold 3 IBS: 0.20502803908063474
Fold 4 IBS: 0.22484462106669664
Fold 5 IBS: 0.21822466700224044
[I 2024-04-14 01:10:45,444] Trial 15 finished with value: 0.21664319193165743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17764770478002706
Fold 2 IBS: 0.20867663392001196
Fold 3 IBS: 0.17428317770837892
Fold 4 IBS: 0.17942136638629663
Fold 5 IBS: 0.2202481090473258
[I 2024-04-14 01:10:58,413] Trial 16 finished with value: 0.19205539836840807 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1745416753225377
Fold 2 IBS: 0.21000021208635342
Fold 3 IBS: 0.16747801651861197
Fold 4 IBS: 0.1665050437548392
Fold 5 IBS: 0.2259884313484794
[I 2024-04-14 01:11:08,149] Trial 17 finished with value: 0.18890267580616435 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.18877375960277615
Fold 2 IBS: 0.2104175503296011
Fold 3 IBS: 0.17887147368827228
Fold 4 IBS: 0.20070265473963897
Fold 5 IBS: 0.21455512687410158
[I 2024-04-14 01:11:09,416] Trial 18 finished with value: 0.19866411304687803 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1693931134036931
Fold 2 IBS: 0.21423273576779828
Fold 3 IBS: 0.16523484371479388
Fold 4 IBS: 0.16359614521845625
Fold 5 IBS: 0.23143820702196424
[I 2024-04-14 01:11:12,831] Trial 19 finished with value: 0.18877900902534114 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17421547013270003
Fold 2 IBS: 0.2050823834385182
Fold 3 IBS: 0.17114430210298628
Fold 4 IBS: 0.17339485761183707
Fold 5 IBS: 0.22351478015249363
[I 2024-04-14 01:11:21,282] Trial 20 finished with value: 0.18947035868770704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17111493042801526
Fold 2 IBS: 0.2137721819185777
Fold 3 IBS: 0.16456471169620251
Fold 4 IBS: 0.16449227846347558
Fold 5 IBS: 0.22864796656377134
[I 2024-04-14 01:11:32,294] Trial 21 finished with value: 0.1885184138140085 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16532773770032788
Fold 2 IBS: 0.2186442284652855
Fold 3 IBS: 0.16460826885307955
Fold 4 IBS: 0.15506743410900792
Fold 5 IBS: 0.23319986958345387
[I 2024-04-14 01:11:40,883] Trial 22 finished with value: 0.18736950774223093 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8844026166095639, 'min_weight_fraction_leaf': 0.08688290860444149}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16301700829191232
Fold 2 IBS: 0.219030517452768
Fold 3 IBS: 0.1623853390492206
Fold 4 IBS: 0.1532916510108008
Fold 5 IBS: 0.23013904250092193
[I 2024-04-14 01:11:52,508] Trial 23 finished with value: 0.1855727116611247 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.882373739187446, 'min_weight_fraction_leaf': 0.012868164547398506}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16304988087529812
Fold 2 IBS: 0.22094207521693815
Fold 3 IBS: 0.161348064662482
Fold 4 IBS: 0.15096714326145844
Fold 5 IBS: 0.23463058158669606
[I 2024-04-14 01:12:04,340] Trial 24 finished with value: 0.18618754912057453 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8872409155608235, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1737150468913634
Fold 2 IBS: 0.2064240961037397
Fold 3 IBS: 0.17070043959096043
Fold 4 IBS: 0.17215340254727685
Fold 5 IBS: 0.22073392460374922
[I 2024-04-14 01:12:16,046] Trial 25 finished with value: 0.1887453819474179 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9949818354422626, 'min_weight_fraction_leaf': 0.04193971879336897}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17192147575817168
Fold 2 IBS: 0.2125807619877445
Fold 3 IBS: 0.1691262873841453
Fold 4 IBS: 0.16885171298035456
Fold 5 IBS: 0.2265576203614483
[I 2024-04-14 01:12:31,665] Trial 26 finished with value: 0.18980757169437287 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8751983869140558, 'min_weight_fraction_leaf': 0.14849424791584837}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16246717022558158
Fold 2 IBS: 0.22278551957594211
Fold 3 IBS: 0.15990422558540457
Fold 4 IBS: 0.1487070056469065
Fold 5 IBS: 0.23422547394882334
[I 2024-04-14 01:12:44,350] Trial 27 finished with value: 0.18561787899653162 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.027289624478908987}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1654696844792975
Fold 2 IBS: 0.2234990134256156
Fold 3 IBS: 0.15946196024021897
Fold 4 IBS: 0.14893349177557935
Fold 5 IBS: 0.2381082176321455
[I 2024-04-14 01:12:49,996] Trial 28 finished with value: 0.18709447351057137 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8312285602471605, 'min_weight_fraction_leaf': 0.04077685648220064}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17845647167398127
Fold 2 IBS: 0.2130730563466517
Fold 3 IBS: 0.1730128250957027
Fold 4 IBS: 0.1775098861437066
Fold 5 IBS: 0.22205252382699645
[I 2024-04-14 01:13:00,169] Trial 29 finished with value: 0.19282095261740773 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7271017134796036, 'min_weight_fraction_leaf': 0.1096845451205721}. Best is trial 23 with value: 0.1855727116611247.

Fold 1 IBS: 0.16792251267623906
Fold 2 IBS: 0.2174484716230587
Fold 3 IBS: 0.16273781989489802
Fold 4 IBS: 0.1558940391227505
Fold 5 IBS: 0.23222422254692077
[I 2024-04-14 01:13:12,568] Trial 30 finished with value: 0.18724541317277338 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7293028765390641, 'min_weight_fraction_leaf': 0.08037045697723012}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16646920043412164
Fold 2 IBS: 0.22144555868438975
Fold 3 IBS: 0.1612585234507463
Fold 4 IBS: 0.15276461377317607
Fold 5 IBS: 0.23760424924495455
[I 2024-04-14 01:13:18,750] Trial 31 finished with value: 0.18790842911747765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8386292091834852, 'min_weight_fraction_leaf': 0.04730132529579094}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16030007033105986
Fold 2 IBS: 0.22398118562940655
Fold 3 IBS: 0.15846297307347587
Fold 4 IBS: 0.1470891139577854
Fold 5 IBS: 0.23657286223224763
[I 2024-04-14 01:13:24,806] Trial 32 finished with value: 0.18528124104479504 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9163496831204196, 'min_weight_fraction_leaf': 0.030126739530685447}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.172937674157177
Fold 2 IBS: 0.24427201483908298
Fold 3 IBS: 0.15582695988286352
Fold 4 IBS: 0.14290514986885272
Fold 5 IBS: 0.24818545842857834
[I 2024-04-14 01:13:29,531] Trial 33 finished with value: 0.1928254514353109 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9201437866465091, 'min_weight_fraction_leaf': 0.07060844824971078}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16533026201292797
Fold 2 IBS: 0.22263639369462013
Fold 3 IBS: 0.16342873596728688
Fold 4 IBS: 0.16226909673388507
Fold 5 IBS: 0.22835592740970792
[I 2024-04-14 01:13:33,167] Trial 34 finished with value: 0.18840408316368557 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.023639916096884216}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1768239075644783
Fold 2 IBS: 0.2081027487281694
Fold 3 IBS: 0.17413951134311367
Fold 4 IBS: 0.17907108232142022
Fold 5 IBS: 0.2215257917188389
[I 2024-04-14 01:13:47,793] Trial 35 finished with value: 0.1919326083352041 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8401348549146568, 'min_weight_fraction_leaf': 0.24235302278015497}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1940843114270721
Fold 2 IBS: 0.2056845420523829
Fold 3 IBS: 0.18788157295828922
Fold 4 IBS: 0.20006428856720795
Fold 5 IBS: 0.2177170857082032
[I 2024-04-14 01:13:53,926] Trial 36 finished with value: 0.20108636014263107 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6624062812925291, 'min_weight_fraction_leaf': 0.1276665161224413}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17340674788508836
Fold 2 IBS: 0.24768190748122734
Fold 3 IBS: 0.16867891640678653
Fold 4 IBS: 0.1616763611285437
Fold 5 IBS: 0.23877880170969434
[I 2024-04-14 01:14:01,761] Trial 37 finished with value: 0.19804454692226806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7790217874657425, 'min_weight_fraction_leaf': 0.062396376437804296}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16624738684053258
Fold 2 IBS: 0.21973229478344297
Fold 3 IBS: 0.16383689986898148
Fold 4 IBS: 0.1555626613940214
Fold 5 IBS: 0.23337565279263775
[I 2024-04-14 01:14:13,866] Trial 38 finished with value: 0.18775097913592323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9337822506368412, 'min_weight_fraction_leaf': 0.09676916841079641}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.19406740130079023
Fold 2 IBS: 0.2080998067364733
Fold 3 IBS: 0.18690687392991395
Fold 4 IBS: 0.1983924325024786
Fold 5 IBS: 0.21669307860788134
[I 2024-04-14 01:14:25,194] Trial 39 finished with value: 0.20083191861550748 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8439046690156142, 'min_weight_fraction_leaf': 0.1681587492068492}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1754231584570973
Fold 2 IBS: 0.20862733191088295
Fold 3 IBS: 0.17201575641485803
Fold 4 IBS: 0.17247754688839995
Fold 5 IBS: 0.22441791937181546
[I 2024-04-14 01:14:29,963] Trial 40 finished with value: 0.19059234260861074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 166, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.05363435608897611}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16687091698705347
Fold 2 IBS: 0.22145067973996654
Fold 3 IBS: 0.16083193542269436
Fold 4 IBS: 0.15145269120336982
Fold 5 IBS: 0.23763053320077898
[I 2024-04-14 01:14:35,828] Trial 41 finished with value: 0.18764735131077265 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8160068596533434, 'min_weight_fraction_leaf': 0.051128939929752766}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16440787739420146
Fold 2 IBS: 0.22051774173279667
Fold 3 IBS: 0.15866302088929105
Fold 4 IBS: 0.1505697309482162
Fold 5 IBS: 0.2344294950935966
[I 2024-04-14 01:14:40,848] Trial 42 finished with value: 0.18571757321162038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8502001595263011, 'min_weight_fraction_leaf': 0.025832096901499825}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.166093032959539
Fold 2 IBS: 0.22071181466302323
Fold 3 IBS: 0.16315038997597892
Fold 4 IBS: 0.1615108085837709
Fold 5 IBS: 0.22986943061414675
[I 2024-04-14 01:14:43,496] Trial 43 finished with value: 0.18826709535929176 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7462221833323165, 'min_weight_fraction_leaf': 0.019530073851423135}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17856291254676518
Fold 2 IBS: 0.20622912686970393
Fold 3 IBS: 0.1728547352397574
Fold 4 IBS: 0.17474142784909633
Fold 5 IBS: 0.22146523571485058
[I 2024-04-14 01:14:48,425] Trial 44 finished with value: 0.19077068764403465 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 183, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9478697073891121, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 32 with value: 0.18528124104479504.

Fold 1 IBS: 0.16512803721910052
Fold 2 IBS: 0.21893230349393553
Fold 3 IBS: 0.1593836385256823
Fold 4 IBS: 0.15058205502042205
Fold 5 IBS: 0.23336241815587846
[I 2024-04-14 01:14:56,009] Trial 45 finished with value: 0.18547769048300378 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6931500413934508, 'min_weight_fraction_leaf': 0.021457257714753555}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1659546836323674
Fold 2 IBS: 0.2153197227930472
Fold 3 IBS: 0.16360867863772716
Fold 4 IBS: 0.15557836846786757
Fold 5 IBS: 0.233640633124344
[I 2024-04-14 01:15:03,832] Trial 46 finished with value: 0.18682041733107066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7831947572035725, 'min_weight_fraction_leaf': 0.01931405227872043}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.2065277829489426
Fold 2 IBS: 0.216421790160963
Fold 3 IBS: 0.1977088009136629
Fold 4 IBS: 0.21668719017242724
Fold 5 IBS: 0.21616573903460984
[I 2024-04-14 01:15:09,986] Trial 47 finished with value: 0.21070226064612113 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 239, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6100992136402282, 'min_weight_fraction_leaf': 0.2926129328054348}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16819818157316316
Fold 2 IBS: 0.21738390622648787
Fold 3 IBS: 0.16156044111171175
Fold 4 IBS: 0.15316407589462896
Fold 5 IBS: 0.24011367020312108
[I 2024-04-14 01:15:14,865] Trial 48 finished with value: 0.18808405500182257 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 123, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6791860734720297, 'min_weight_fraction_leaf': 0.003213779418364194}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17209598869991036
Fold 2 IBS: 0.21187077120599623
Fold 3 IBS: 0.16727613640288252
Fold 4 IBS: 0.16695787846814034
Fold 5 IBS: 0.2272726675718586
[I 2024-04-14 01:15:18,880] Trial 49 finished with value: 0.1890946884697576 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8621088667656548, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.18268255673834424
Fold 2 IBS: 0.2116406133958206
Fold 3 IBS: 0.17317749084487088
Fold 4 IBS: 0.18115159425862645
Fold 5 IBS: 0.21966339609454685
[I 2024-04-14 01:15:21,656] Trial 50 finished with value: 0.19366313026644183 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 90, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.07395605063366822}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16168497854927735
Fold 2 IBS: 0.22270197197696373
Fold 3 IBS: 0.15969319515722263
Fold 4 IBS: 0.14836469505004918
Fold 5 IBS: 0.23398522053840312
[I 2024-04-14 01:15:34,749] Trial 51 finished with value: 0.18528601225438318 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9098861737626865, 'min_weight_fraction_leaf': 0.03317554027209381}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16283944924818344
Fold 2 IBS: 0.2217235758500272
Fold 3 IBS: 0.15875960819361015
Fold 4 IBS: 0.1480062250468594
Fold 5 IBS: 0.23242571799847053
[I 2024-04-14 01:15:47,084] Trial 52 finished with value: 0.18475091526743012 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6920435785662685, 'min_weight_fraction_leaf': 0.023623022439616993}. Best is trial 52 with value: 0.18475091526743012.
Fold 1 IBS: 0.16156116277380467
Fold 2 IBS: 0.21645044154721294
Fold 3 IBS: 0.15680725082067987
Fold 4 IBS: 0.1463271703292176
Fold 5 IBS: 0.23173369241683808
[I 2024-04-14 01:15:59,877] Trial 53 finished with value: 0.18257594357755064 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16345657480280432
Fold 2 IBS: 0.21941864722007984
Fold 3 IBS: 0.1609004507368225
Fold 4 IBS: 0.15232912028765422
Fold 5 IBS: 0.2304650281766842
[I 2024-04-14 01:16:10,966] Trial 54 finished with value: 0.185313964244809 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6831651026874692, 'min_weight_fraction_leaf': 0.003203141018784241}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21398942294707132
Fold 2 IBS: 0.22147230949301053
Fold 3 IBS: 0.20481071402497053
Fold 4 IBS: 0.22464130383350117
Fold 5 IBS: 0.21857501052674366
[I 2024-04-14 01:16:23,207] Trial 55 finished with value: 0.21669775216505943 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6865690783108706, 'min_weight_fraction_leaf': 0.38949341979712204}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21399089065449398
Fold 2 IBS: 0.2214447680813218
Fold 3 IBS: 0.20479456577543795
Fold 4 IBS: 0.22461278604587448
Fold 5 IBS: 0.21855736344590462
[I 2024-04-14 01:16:34,982] Trial 56 finished with value: 0.21668007480060658 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.602520835973954, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17871648336439458
Fold 2 IBS: 0.20746679738869533
Fold 3 IBS: 0.17495717299824248
Fold 4 IBS: 0.1821696732464211
Fold 5 IBS: 0.22029130965865304
[I 2024-04-14 01:16:45,280] Trial 57 finished with value: 0.19272028733128133 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6950911045016969, 'min_weight_fraction_leaf': 0.06162344008829474}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17152567449091236
Fold 2 IBS: 0.2132707954363787
Fold 3 IBS: 0.16577002064558846
Fold 4 IBS: 0.16352941407058058
Fold 5 IBS: 0.2293168915362626
[I 2024-04-14 01:16:55,754] Trial 58 finished with value: 0.18868255923594454 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6159821240459256, 'min_weight_fraction_leaf': 0.08195171278424525}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17647106232629753
Fold 2 IBS: 0.20824417376602933
Fold 3 IBS: 0.1723553183748716
Fold 4 IBS: 0.1736062035933313
Fold 5 IBS: 0.22224901748255857
[I 2024-04-14 01:17:07,221] Trial 59 finished with value: 0.19058515510861768 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.525386145731032, 'min_weight_fraction_leaf': 0.000152340144876216}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.17342492293804432
Fold 2 IBS: 0.2110732537830341
Fold 3 IBS: 0.16831819527481992
Fold 4 IBS: 0.16873369129336893
Fold 5 IBS: 0.22655614890084055
[I 2024-04-14 01:17:18,245] Trial 60 finished with value: 0.18962124243802156 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5735294094022945, 'min_weight_fraction_leaf': 0.10077092974890593}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16275315104094723
Fold 2 IBS: 0.22028966274589679
Fold 3 IBS: 0.16253743592400494
Fold 4 IBS: 0.15352895984062664
Fold 5 IBS: 0.23021227496706434
[I 2024-04-14 01:17:29,070] Trial 61 finished with value: 0.18586429690370798 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7582468632632998, 'min_weight_fraction_leaf': 0.014165988553227182}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16187634732795245
Fold 2 IBS: 0.21936803684113038
Fold 3 IBS: 0.1608633743218315
Fold 4 IBS: 0.15050003762977443
Fold 5 IBS: 0.23315135185396704
[I 2024-04-14 01:17:40,126] Trial 62 finished with value: 0.18515182959493115 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9688682344495251, 'min_weight_fraction_leaf': 0.03803430028119831}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16803000111589547
Fold 2 IBS: 0.21883335722590105
Fold 3 IBS: 0.16153399726646753
Fold 4 IBS: 0.15499454989097905
Fold 5 IBS: 0.23015675492479587
[I 2024-04-14 01:17:51,601] Trial 63 finished with value: 0.18670973208480782 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4289211196547223, 'min_weight_fraction_leaf': 0.03483517796766671}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16353133471191258
Fold 2 IBS: 0.22078931633305934
Fold 3 IBS: 0.16232987702451745
Fold 4 IBS: 0.1497770751049068
Fold 5 IBS: 0.23519973886423967
[I 2024-04-14 01:18:03,660] Trial 64 finished with value: 0.18632546840772718 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9928124170835537, 'min_weight_fraction_leaf': 0.0546315910617156}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16705858086425657
Fold 2 IBS: 0.21688710748739626
Fold 3 IBS: 0.16302480802361138
Fold 4 IBS: 0.16043857461543376
Fold 5 IBS: 0.22735018728687206
[I 2024-04-14 01:18:12,129] Trial 65 finished with value: 0.186951851655514 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.700753371069358, 'min_weight_fraction_leaf': 0.034080382470936726}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.2139764009793113
Fold 2 IBS: 0.22128743928758063
Fold 3 IBS: 0.20478422039927321
Fold 4 IBS: 0.22461901938020365
Fold 5 IBS: 0.21866318582772845
[I 2024-04-14 01:18:25,168] Trial 66 finished with value: 0.21666605317481946 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17803507005686864
Fold 2 IBS: 0.20584595762292543
Fold 3 IBS: 0.17289828813524646
Fold 4 IBS: 0.177343485740087
Fold 5 IBS: 0.22038680074032185
[I 2024-04-14 01:18:38,466] Trial 67 finished with value: 0.19090192045908988 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8083420047439778, 'min_weight_fraction_leaf': 0.0005690362936050055}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18517903096649513
Fold 2 IBS: 0.2068570229240262
Fold 3 IBS: 0.1787293688926839
Fold 4 IBS: 0.18812296323512723
Fold 5 IBS: 0.2160660198664728
[I 2024-04-14 01:18:50,566] Trial 68 finished with value: 0.19499088117696103 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.06709563455447608}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18645916216015707
Fold 2 IBS: 0.20636548084294315
Fold 3 IBS: 0.17885851202915032
Fold 4 IBS: 0.18718410387690065
Fold 5 IBS: 0.21792963761071232
[I 2024-04-14 01:19:00,824] Trial 69 finished with value: 0.19535937930397268 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9134125139788976, 'min_weight_fraction_leaf': 0.09022342402306419}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1757749566349244
Fold 2 IBS: 0.2608203853544215
Fold 3 IBS: 0.1687965292943309
Fold 4 IBS: 0.16154593350334548
Fold 5 IBS: 0.2409053655581546
[I 2024-04-14 01:19:10,041] Trial 70 finished with value: 0.20156863406903539 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9558804805474729, 'min_weight_fraction_leaf': 0.038804497461907755}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1641556888310035
Fold 2 IBS: 0.21756591667129618
Fold 3 IBS: 0.16214425980311192
Fold 4 IBS: 0.1527006421467362
Fold 5 IBS: 0.23008748551996394
[I 2024-04-14 01:19:20,995] Trial 71 finished with value: 0.18533079859442234 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6369371661585259, 'min_weight_fraction_leaf': 0.01592906514292467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16591246996228284
Fold 2 IBS: 0.2157266700943674
Fold 3 IBS: 0.1639704528415932
Fold 4 IBS: 0.15917069749386206
Fold 5 IBS: 0.22728835985586845
[I 2024-04-14 01:19:32,075] Trial 72 finished with value: 0.18641373004959477 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6355486112323981, 'min_weight_fraction_leaf': 0.016225042494993316}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16466547332455966
Fold 2 IBS: 0.21692658302629209
Fold 3 IBS: 0.1589302212774401
Fold 4 IBS: 0.14980038348586724
Fold 5 IBS: 0.23137411159828591
[I 2024-04-14 01:19:43,214] Trial 73 finished with value: 0.184339354542489 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5876918007096606, 'min_weight_fraction_leaf': 0.01373372285606849}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16792178126681906
Fold 2 IBS: 0.21606101236454162
Fold 3 IBS: 0.16289143446225338
Fold 4 IBS: 0.15694953508014142
Fold 5 IBS: 0.2316203069237443
[I 2024-04-14 01:19:54,194] Trial 74 finished with value: 0.18708881401949995 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5762811196680634, 'min_weight_fraction_leaf': 0.04721403021162478}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.16278536069617075
Fold 2 IBS: 0.22061911570320727
Fold 3 IBS: 0.15948095174532076
Fold 4 IBS: 0.1500453215492157
Fold 5 IBS: 0.23108140998200039
[I 2024-04-14 01:20:05,452] Trial 75 finished with value: 0.18480243193518295 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6487943567829829, 'min_weight_fraction_leaf': 0.011079149496446542}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1649931201311961
Fold 2 IBS: 0.2191098546301487
Fold 3 IBS: 0.1604180424655896
Fold 4 IBS: 0.15133070246635846
Fold 5 IBS: 0.23270813963892614
[I 2024-04-14 01:20:20,817] Trial 76 finished with value: 0.18571197186644378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 496, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6611270444897925, 'min_weight_fraction_leaf': 0.03472791790328323}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17454705567490922
Fold 2 IBS: 0.20946654124798095
Fold 3 IBS: 0.17107052561345987
Fold 4 IBS: 0.17205506925206807
Fold 5 IBS: 0.22301050367917757
[I 2024-04-14 01:20:32,762] Trial 77 finished with value: 0.19002993909351912 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5365605521283588, 'min_weight_fraction_leaf': 0.11295942956753599}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18204012108405643
Fold 2 IBS: 0.2063716852750058
Fold 3 IBS: 0.17875146851232082
Fold 4 IBS: 0.18921011660617745
Fold 5 IBS: 0.2162548711235392
[I 2024-04-14 01:20:42,735] Trial 78 finished with value: 0.19452565252021997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 427, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5917795612536799, 'min_weight_fraction_leaf': 0.2198684675175928}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17845532120437899
Fold 2 IBS: 0.20772503338895465
Fold 3 IBS: 0.17421627745462215
Fold 4 IBS: 0.18019949439245914
Fold 5 IBS: 0.22083458875793646
[I 2024-04-14 01:20:54,849] Trial 79 finished with value: 0.19228614303967032 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.49597522186369347, 'min_weight_fraction_leaf': 0.06112532202305438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16158996672320755
Fold 2 IBS: 0.21729610032334276
Fold 3 IBS: 0.157796999636179
Fold 4 IBS: 0.1472728675908385
Fold 5 IBS: 0.23183976837586612
[I 2024-04-14 01:21:05,410] Trial 80 finished with value: 0.18315914052988677 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6281972616252203, 'min_weight_fraction_leaf': 0.00848688046818526}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16157863775376022
Fold 2 IBS: 0.22087534780676452
Fold 3 IBS: 0.15999281456554124
Fold 4 IBS: 0.14853123619761843
Fold 5 IBS: 0.23150501980376892
[I 2024-04-14 01:21:15,173] Trial 81 finished with value: 0.18449661122549066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7386940991152582, 'min_weight_fraction_leaf': 0.01046274314610217}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16352260586628395
Fold 2 IBS: 0.22200502430399466
Fold 3 IBS: 0.15886916219783537
Fold 4 IBS: 0.14807572814886177
Fold 5 IBS: 0.2339085838911687
[I 2024-04-14 01:21:25,382] Trial 82 finished with value: 0.1852762208816289 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7162267948855195, 'min_weight_fraction_leaf': 0.032010312646594104}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16546027653935427
Fold 2 IBS: 0.2211659942343032
Fold 3 IBS: 0.16100661860428056
Fold 4 IBS: 0.15097334931915155
Fold 5 IBS: 0.2358306721546786
[I 2024-04-14 01:21:35,343] Trial 83 finished with value: 0.18688738217035364 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7326293257583885, 'min_weight_fraction_leaf': 0.04562346387387325}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285220423552985
Fold 2 IBS: 0.2188473500308101
Fold 3 IBS: 0.1599688920049345
Fold 4 IBS: 0.14885881691304034
Fold 5 IBS: 0.23161635394463342
[I 2024-04-14 01:21:44,223] Trial 84 finished with value: 0.18442872342578964 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7090996631118544, 'min_weight_fraction_leaf': 0.011358284348193259}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285549245105505
Fold 2 IBS: 0.21942277067272614
Fold 3 IBS: 0.15946829525657427
Fold 4 IBS: 0.14838517247840774
Fold 5 IBS: 0.23122387168068076
[I 2024-04-14 01:21:53,138] Trial 85 finished with value: 0.1842711205078888 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7186868789202818, 'min_weight_fraction_leaf': 0.01496729486923688}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16128591165678588
Fold 2 IBS: 0.21980011323918688
Fold 3 IBS: 0.15937248726208542
Fold 4 IBS: 0.1486127266622536
Fold 5 IBS: 0.2323048878882266
[I 2024-04-14 01:22:02,248] Trial 86 finished with value: 0.18427522534170765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7543993526497688, 'min_weight_fraction_leaf': 0.013808236520630852}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16094110571393064
Fold 2 IBS: 0.21986993252478362
Fold 3 IBS: 0.1588596843743244
Fold 4 IBS: 0.14614051224869679
Fold 5 IBS: 0.23352782586558365
[I 2024-04-14 01:22:11,038] Trial 87 finished with value: 0.1838678121454638 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7599338110461693, 'min_weight_fraction_leaf': 0.01151287364248438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16095650535504896
Fold 2 IBS: 0.21964363350705826
Fold 3 IBS: 0.15886397081421852
Fold 4 IBS: 0.14614666331841772
Fold 5 IBS: 0.23313729954057164
[I 2024-04-14 01:22:22,797] Trial 88 finished with value: 0.183749614507063 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 360, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7606093640745762, 'min_weight_fraction_leaf': 0.010471830721284079}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16110829576026084
Fold 2 IBS: 0.21851253412110366
Fold 3 IBS: 0.15675512925824683
Fold 4 IBS: 0.14727139463073632
Fold 5 IBS: 0.23209620967854572
[I 2024-04-14 01:22:34,747] Trial 89 finished with value: 0.18314871268977867 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7587282239351308, 'min_weight_fraction_leaf': 0.008176941543787496}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.18162653052097805
Fold 2 IBS: 0.20612651784753333
Fold 3 IBS: 0.1771784733434652
Fold 4 IBS: 0.18941755917999278
Fold 5 IBS: 0.21614311489575638
[I 2024-04-14 01:22:45,824] Trial 90 finished with value: 0.19409843915754516 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7635642567316503, 'min_weight_fraction_leaf': 0.280081595660318}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16186089564069253
Fold 2 IBS: 0.21899259491528042
Fold 3 IBS: 0.15921485444738478
Fold 4 IBS: 0.148193042465612
Fold 5 IBS: 0.23190417972474658
[I 2024-04-14 01:22:55,857] Trial 91 finished with value: 0.18403311343874326 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.789178452265885, 'min_weight_fraction_leaf': 0.011545143067658635}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16265353400501528
Fold 2 IBS: 0.2175575638863236
Fold 3 IBS: 0.16133894389326223
Fold 4 IBS: 0.15458872962543557
Fold 5 IBS: 0.229228321655463
[I 2024-04-14 01:23:05,703] Trial 92 finished with value: 0.18507341861309995 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7985486683510279, 'min_weight_fraction_leaf': 0.007901199895383132}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1620791424844971
Fold 2 IBS: 0.21900011819041879
Fold 3 IBS: 0.15920401655120014
Fold 4 IBS: 0.14637781084518398
Fold 5 IBS: 0.23282788799260146
[I 2024-04-14 01:23:16,590] Trial 93 finished with value: 0.1838977952127803 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7705275977783406, 'min_weight_fraction_leaf': 0.013704505872889598}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1793411990654569
Fold 2 IBS: 0.20613622174736498
Fold 3 IBS: 0.17275187695258565
Fold 4 IBS: 0.17818980825839892
Fold 5 IBS: 0.22022859697507743
[I 2024-04-14 01:23:27,203] Trial 94 finished with value: 0.19132954059977678 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7755480125040337, 'min_weight_fraction_leaf': 0.05063148942960361}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1610317396130936
Fold 2 IBS: 0.2202627419888432
Fold 3 IBS: 0.15951569709008712
Fold 4 IBS: 0.1458873166232896
Fold 5 IBS: 0.23482464408960785
[I 2024-04-14 01:23:38,490] Trial 95 finished with value: 0.18430442788098428 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 350, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7576152916362451, 'min_weight_fraction_leaf': 0.023770792047509592}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17066297262534935
Fold 2 IBS: 0.22975974207949945
Fold 3 IBS: 0.1519444360637532
Fold 4 IBS: 0.13950104633987118
Fold 5 IBS: 0.2439409705061117
[I 2024-04-14 01:23:50,162] Trial 96 finished with value: 0.18716183352291696 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7560665367452727, 'min_weight_fraction_leaf': 0.02298285611760403}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18361848353136237
Fold 2 IBS: 0.2052929877088459
Fold 3 IBS: 0.17656731308943907
Fold 4 IBS: 0.18399483123099875
Fold 5 IBS: 0.21866940095388543
[I 2024-04-14 01:23:59,569] Trial 97 finished with value: 0.1936286033029063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7936215885628722, 'min_weight_fraction_leaf': 0.0702592146341984}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16102070948187022
Fold 2 IBS: 0.22255035648510013
Fold 3 IBS: 0.1611617777057763
Fold 4 IBS: 0.14597987975871002
Fold 5 IBS: 0.23595320519699498
[I 2024-04-14 01:24:10,267] Trial 98 finished with value: 0.18533318572569035 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.817957524711727, 'min_weight_fraction_leaf': 0.0008689368092096427}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16218129609850532
Fold 2 IBS: 0.21864999525446885
Fold 3 IBS: 0.1599823914541389
Fold 4 IBS: 0.14944190039573815
Fold 5 IBS: 0.23537346983323632
[I 2024-04-14 01:24:20,309] Trial 99 finished with value: 0.1851258106072175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7505423882418932, 'min_weight_fraction_leaf': 0.027516392549616332}. Best is trial 53 with value: 0.18257594357755064.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.18257594357755064], datetime_start=datetime.datetime(2024, 4, 14, 1, 15, 47, 91113), datetime_complete=datetime.datetime(2024, 4, 14, 1, 15, 59, 876480), params={'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=53, value=None)


* Best Score for IBS:
 0.18257594357755064

In [156]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [157]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.794
train_ibs:  0.183

#### Test

In [158]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [159]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=12, max_features=None, max_leaf_nodes=6,
                   max_samples=0.7030590704740037, min_samples_leaf=6,
                   min_samples_split=13,
                   min_weight_fraction_leaf=0.020016091327628317,
                   n_estimators=273, random_state=123, warm_start=True)

C-index score: 0.618

ExtraSurvivalTrees(max_depth=13, max_features='log2', max_leaf_nodes=6,
                   max_samples=0.7048480399273186, min_samples_leaf=1,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.0010291888027469595,
                   n_estimators=485, random_state=123, warm_start=True)

IBS: 0.215

In [160]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [161]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 01:24:24,685] A new study created in memory with name: no-name-ef53575b-01ef-4bf9-9c9a-82bb9c4c32ef

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:25:13,700] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:25:41,115] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:26:06,820] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:26:48,362] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:27:05,500] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:27:09,611] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:27:50,934] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:28:02,446] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:28:03,828] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 01:29:47,044] Trial 9 finished with value: 0.7334874350516556 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:32:34,451] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:35:35,525] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:38:07,861] Trial 12 finished with value: 0.703856671925322 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:39:22,377] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:41:00,557] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:42:32,371] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:43:33,250] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:45:39,294] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:48:28,626] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:48:35,013] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:49:35,256] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:51:45,944] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 01:53:49,064] Trial 22 finished with value: 0.7242619704042982 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:55:28,978] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:56:59,250] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 01:57:54,269] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 01:59:50,361] Trial 26 finished with value: 0.5421550134138162 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:01:54,329] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:03:26,064] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:04:29,116] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:05:42,114] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 02:31:00,908] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:56:18,917] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 02:58:25,585] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:00:25,907] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:00:47,281] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:02:40,107] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:02:43,459] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:03:26,201] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:04:33,862] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:06:24,006] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 03:06:24,486] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:06:37,321] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:06:50,745] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:23,616] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:38,013] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:07:51,233] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:08:43,963] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:09:07,335] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:08,286] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:12,957] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:10:13,818] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:14,843] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:10:25,381] Trial 53 finished with value: 0.7035675756915192 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:34,418] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:10:36,737] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:13:11,499] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:13:21,508] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:13:38,687] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:15:46,260] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:16:33,727] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:16:37,802] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:16:58,953] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:17:02,289] Trial 63 finished with value: 0.7163384910196757 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:08,385] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:17:18,909] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:19:57,227] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:19:59,248] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:20:36,148] Trial 68 finished with value: 0.6328510949834479 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:20:38,897] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:22:39,775] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:22:40,466] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 03:22:41,395] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:23:10,182] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:23:11,401] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:23:20,867] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:24:35,588] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:24:38,763] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:27:51,214] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:28:19,162] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:29:30,402] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 03:29:31,179] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:29:32,192] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:29:34,877] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:33:10,253] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:33:11,381] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:33:16,090] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:33:19,827] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:33:24,204] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:36:09,519] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:36:25,930] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:36:27,632] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:36:29,342] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:36:30,009] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:36:32,593] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 03:36:36,623] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.607981220657277
[I 2024-04-14 03:36:45,939] Trial 96 finished with value: 0.7453020253507325 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:36:55,805] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 03:37:04,219] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7723214285714286

[I 2024-04-14 03:37:05,251] A new study created in memory with name: no-name-69ff39d2-72d5-4169-ae0e-802c5c588509

Fold 3 C-index: 0.7083333333333334
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 03:37:05,221] Trial 99 finished with value: 0.7038145684617871 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7453020253507325], datetime_start=datetime.datetime(2024, 4, 14, 3, 36, 36, 634197), datetime_complete=datetime.datetime(2024, 4, 14, 3, 36, 45, 918286), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7453020253507325

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:38:06,835] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:38:41,963] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:39:14,859] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:40:07,198] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:40:28,820] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:40:34,330] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:41:28,418] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 03:41:43,307] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:41:45,411] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21302115522395498
Fold 2 IBS: 0.22130101345683229
Fold 3 IBS: 0.20356574496128135
Fold 4 IBS: 0.22373082985786685
Fold 5 IBS: 0.21796021556320513
[I 2024-04-14 03:44:02,906] Trial 9 finished with value: 0.21591579181262813 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 03:47:23,891] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 03:51:10,523] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21383968411387158
Fold 2 IBS: 0.22156451448592526
Fold 3 IBS: 0.20440536466519849
Fold 4 IBS: 0.22459255869133457
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 03:54:26,742] Trial 12 finished with value: 0.21650016968139757 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 03:56:01,155] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 03:58:53,299] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:01:31,484] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:02:56,432] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:06:11,580] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:07:57,290] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:08:14,710] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:11:13,647] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 04:14:13,291] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21275233971420443
Fold 2 IBS: 0.22141006773816166

Fold 3 IBS: 0.20334575604936503
Fold 4 IBS: 0.2231342747566171
Fold 5 IBS: 0.2179288192033457
[I 2024-04-14 04:17:36,555] Trial 22 finished with value: 0.21571425149233878 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:20:28,526] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:22:19,343] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:24:06,469] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:26:45,917] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:27:01,221] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:27:58,104] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:30:34,610] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:31:34,750] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 04:34:30,387] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.2214475600367709
Fold 3 IBS: 0.2035963921195872
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.2179179888442139
[I 2024-04-14 04:37:23,701] Trial 32 finished with value: 0.21590224301714384 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 04:39:31,866] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 04:41:52,090] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:42:23,275] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:45:22,863] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:45:28,404] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 04:47:02,688] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 04:49:00,614] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 04:50:57,108] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2133737249398968
Fold 2 IBS: 0.22149810300618933
Fold 3 IBS: 0.20392418223551953
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21807108026974395
[I 2024-04-14 04:53:43,527] Trial 41 finished with value: 0.21616497963246242 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21306226677867723
Fold 2 IBS: 0.22147749486211882
Fold 3 IBS: 0.20359544985689815
Fold 4 IBS: 0.22359166073512057
Fold 5 IBS: 0.21793202518042964
[I 2024-04-14 04:56:47,131] Trial 42 finished with value: 0.21593177948264888 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 05:00:16,597] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:02:35,731] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21378011659547358
Fold 2 IBS: 0.22145278135911364
Fold 3 IBS: 0.20436255304908924
Fold 4 IBS: 0.22448271516750193
Fold 5 IBS: 0.2180782304104917
[I 2024-04-14 05:04:50,267] Trial 45 finished with value: 0.21643127931633402 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:07:08,864] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:08:05,335] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 05:08:06,194] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 05:08:37,007] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:11:17,298] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 05:14:09,136] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:17:02,997] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22136281903923083
Fold 3 IBS: 0.2023927630992915
Fold 4 IBS: 0.2219411019366781
Fold 5 IBS: 0.21777624808878387
[I 2024-04-14 05:19:36,793] Trial 53 finished with value: 0.2150432178150902 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:22:08,699] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:24:13,848] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:26:18,038] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:29:08,028] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:32:26,805] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:34:34,144] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 05:36:17,126] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:38:49,014] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 05:41:53,648] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:45:02,647] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21315225506544797
Fold 2 IBS: 0.22120521782494593
Fold 3 IBS: 0.20370415696975244
Fold 4 IBS: 0.22392954297429343
Fold 5 IBS: 0.21800569131579653
[I 2024-04-14 05:48:29,636] Trial 64 finished with value: 0.21599937283004728 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 05:50:58,158] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8687566763675275, 'learning_rate': 0.010290863736545098, 'dropout_rate': 0.20090531278751475, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.35267930800388836, 'max_features': 'auto', 'min_impurity_decrease': 2.9695254103704335e-06, 'validation_fraction': 0.9981673914604385, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 05:51:19,184] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9104313304151431, 'learning_rate': 0.014815622348446418, 'dropout_rate': 0.1415896279444537, 'n_estimators': 149, 'criterion': 'squared_error', 'ccp_alpha': 0.7060910424624821, 'min_weight_fraction_leaf': 0.2796836959018326, 'max_features': 'auto', 'min_impurity_decrease': 5.127880425748818e-06, 'validation_fraction': 0.916501041728546, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:53:43,709] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.802369464636257, 'learning_rate': 0.00417552385002208, 'dropout_rate': 0.3370707390697732, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.22284347226729986, 'max_features': 'sqrt', 'min_impurity_decrease': 7.319926345244562e-07, 'validation_fraction': 0.8373361504171383, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:56:43,817] Trial 68 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9271983184882995, 'learning_rate': 0.026761786505961737, 'dropout_rate': 0.23198968531289843, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.3246047057302614, 'max_features': 'auto', 'min_impurity_decrease': 2.8105707733985375e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 05:59:07,930] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9669065339055751, 'learning_rate': 0.010765506871731714, 'dropout_rate': 0.30527953045505896, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.8784198437522095, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:00:30,912] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.041826568167709126, 'dropout_rate': 0.5905404972480945, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.3744309428528772, 'max_features': None, 'min_impurity_decrease': 1.5635679037041744e-07, 'validation_fraction': 0.9186076475421031, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21310093398309657
Fold 2 IBS: 0.22107852954082238
Fold 3 IBS: 0.20363684344049715
Fold 4 IBS: 0.2235062321376155
Fold 5 IBS: 0.2179952952989321
[I 2024-04-14 06:03:58,490] Trial 71 finished with value: 0.21586356688019276 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.008268552307118088, 'dropout_rate': 0.18133086892644865, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.1936286226601749, 'max_features': 'log2', 'min_impurity_decrease': 9.627538760330365e-07, 'validation_fraction': 0.9695063743987746, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.2124258387603463
Fold 2 IBS: 0.22057958449066262
Fold 3 IBS: 0.20279757841484652
Fold 4 IBS: 0.222180058336135
Fold 5 IBS: 0.21771098701395403
[I 2024-04-14 06:07:25,193] Trial 72 finished with value: 0.21513880940318889 and parameters: {'subsample': 0.9765713621264592, 'learning_rate': 0.00878714781905863, 'dropout_rate': 0.12511582109542432, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.1603532575763104, 'max_features': 'log2', 'min_impurity_decrease': 4.6121007580567444e-07, 'validation_fraction': 0.9726077921006634, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 06:10:28,659] Trial 73 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9999531614476969, 'learning_rate': 0.017515788008347112, 'dropout_rate': 0.12067593932125548, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.1608125340894365, 'max_features': 'log2', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9762008597583516, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:13:42,144] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9378736061625563, 'learning_rate': 0.00962248608121305, 'dropout_rate': 0.17315149200510316, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.11427286298314121, 'max_features': 'log2', 'min_impurity_decrease': 7.393622885050152e-07, 'validation_fraction': 0.9760588067950509, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:16:26,966] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8548930681972974, 'learning_rate': 0.05554512018944124, 'dropout_rate': 0.14951765413144097, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.3275069627126754, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 'log2', 'min_impurity_decrease': 1.0058881333640878e-06, 'validation_fraction': 0.9013416300485078, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 06:19:40,991] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9721782395774373, 'learning_rate': 0.003194443723182592, 'dropout_rate': 0.12011548645109148, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.9325305665153546, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:22:57,049] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8921532985730489, 'learning_rate': 0.021931279910218017, 'dropout_rate': 0.19284931428290142, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.5905545096948588, 'min_weight_fraction_leaf': 0.07057220045251793, 'max_features': 'log2', 'min_impurity_decrease': 1.637559261311236e-05, 'validation_fraction': 0.8150762480319586, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 06:25:36,171] Trial 78 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.25883194688905886, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.9915392376256854, 'min_weight_fraction_leaf': 0.18968885272282524, 'max_features': 'log2', 'min_impurity_decrease': 3.9150597642462115e-06, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 06:28:00,546] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.01335084153769065, 'dropout_rate': 0.10072101837872541, 'n_estimators': 393, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28871198232416817, 'min_weight_fraction_leaf': 0.17483536292771176, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982218331650979, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:29:27,973] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.977148848015456, 'learning_rate': 0.004307663599041434, 'dropout_rate': 0.15920080431792163, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 1, 'min_impurity_decrease': 1.424247746508587e-06, 'validation_fraction': 0.8670066304726413, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21299867857890398
Fold 2 IBS: 0.2214477278201705
Fold 3 IBS: 0.20356620117857893
Fold 4 IBS: 0.22350168421901248
Fold 5 IBS: 0.21792379994243102
[I 2024-04-14 06:32:30,578] Trial 81 finished with value: 0.2158876183478194 and parameters: {'subsample': 0.9579178853393634, 'learning_rate': 0.007273589951884828, 'dropout_rate': 0.2054590932290375, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.02521700237735763, 'min_weight_fraction_leaf': 0.23721821844476393, 'max_features': 'auto', 'min_impurity_decrease': 2.628308399801263e-07, 'validation_fraction': 0.945876154428725, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21281996790006147
Fold 2 IBS: 0.22144914962179446
Fold 3 IBS: 0.2034201419570034
Fold 4 IBS: 0.22330541406123097
Fold 5 IBS: 0.21789799579435803
[I 2024-04-14 06:35:41,583] Trial 82 finished with value: 0.21577853386688967 and parameters: {'subsample': 0.9374850920793417, 'learning_rate': 0.009537962827339893, 'dropout_rate': 0.2311360143359113, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.01786403260693046, 'min_weight_fraction_leaf': 0.30128352038824946, 'max_features': 'auto', 'min_impurity_decrease': 2.672883759599648e-07, 'validation_fraction': 0.9419164447228301, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 06:38:38,121] Trial 83 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.008698584299413689, 'dropout_rate': 0.2878607631400676, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.42714757621714333, 'min_weight_fraction_leaf': 0.2701739605759479, 'max_features': 0.1, 'min_impurity_decrease': 4.793545557946714e-07, 'validation_fraction': 0.9339252824355873, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:41:25,898] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.016064279530571223, 'dropout_rate': 0.2326295808813899, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.7147702528804116, 'min_weight_fraction_leaf': 0.23638615893438736, 'max_features': 'auto', 'min_impurity_decrease': 3.019646046469693e-07, 'validation_fraction': 0.8979947940782089, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 06:43:53,063] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9376269876567488, 'learning_rate': 0.019091747704160993, 'dropout_rate': 0.20706945781506403, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.16619718561211044, 'min_weight_fraction_leaf': 0.15561996067062303, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9731668294064385, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:46:31,888] Trial 86 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8785484469699407, 'learning_rate': 0.012070502053282707, 'dropout_rate': 0.2505427438802027, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.1270526375680832, 'min_weight_fraction_leaf': 0.25781248698190756, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2713997001011194e-06, 'validation_fraction': 0.943859242495053, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:48:15,583] Trial 87 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9090955901211109, 'learning_rate': 0.006929208749359209, 'dropout_rate': 0.49308788025511585, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.32252019630070927, 'min_weight_fraction_leaf': 0.3051832272732572, 'max_features': 'log2', 'min_impurity_decrease': 7.049454515025671e-07, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:50:32,413] Trial 88 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9447987915285996, 'learning_rate': 0.014159070275535094, 'dropout_rate': 0.18102387516231752, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.5935000311483954, 'min_weight_fraction_leaf': 0.2151508441811604, 'max_features': 'auto', 'min_impurity_decrease': 3.72786238165322e-07, 'validation_fraction': 0.898328514849679, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21292314886383587
Fold 2 IBS: 0.2213935582997429
Fold 3 IBS: 0.20349492943164285
Fold 4 IBS: 0.2234443788901035
Fold 5 IBS: 0.2178743294294726
[I 2024-04-14 06:52:01,820] Trial 89 finished with value: 0.21582606898295956 and parameters: {'subsample': 0.9777744983689288, 'learning_rate': 0.01038357183462239, 'dropout_rate': 0.27697802684175754, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.019074305728520667, 'min_weight_fraction_leaf': 0.2917659918820059, 'max_features': 'auto', 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.855835665987138, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:52:33,157] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9728383671704387, 'learning_rate': 0.009918951595706415, 'dropout_rate': 0.8458602043820649, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.8331973858915148, 'min_weight_fraction_leaf': 0.2921200274675525, 'max_features': 'auto', 'min_impurity_decrease': 1.4263141271201017e-07, 'validation_fraction': 0.6746483744961582, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21336618881179586
Fold 2 IBS: 0.22114294232267198
Fold 3 IBS: 0.20384999569236736
Fold 4 IBS: 0.22375343637403386
Fold 5 IBS: 0.21796174726134912
[I 2024-04-14 06:54:06,711] Trial 91 finished with value: 0.21601486209244367 and parameters: {'subsample': 0.2845120808216636, 'learning_rate': 0.007013602341022412, 'dropout_rate': 0.2673714840258141, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.03785557112751456, 'min_weight_fraction_leaf': 0.28289624505615074, 'max_features': 'auto', 'min_impurity_decrease': 2.167221721970957e-07, 'validation_fraction': 0.8389190675336428, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 06:54:43,544] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.012214946715626797, 'dropout_rate': 0.21822342387423224, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.2716052866202, 'min_weight_fraction_leaf': 0.2516221825059295, 'max_features': 'auto', 'min_impurity_decrease': 5.164764561896499e-07, 'validation_fraction': 0.9118535684017283, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:56:18,906] Trial 93 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9215121808289675, 'learning_rate': 0.023968389847749173, 'dropout_rate': 0.3096195311954267, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.526845938693122, 'min_weight_fraction_leaf': 0.23408949316338243, 'max_features': 'auto', 'min_impurity_decrease': 3.3639036073651944e-07, 'validation_fraction': 0.9394031242668214, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:57:31,198] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9794737431495151, 'learning_rate': 0.002207391632430766, 'dropout_rate': 0.355864908714743, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.25602285176947265, 'min_weight_fraction_leaf': 0.1982598024964269, 'max_features': 'auto', 'min_impurity_decrease': 7.85301346539494e-07, 'validation_fraction': 0.8716461599738365, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 06:59:02,948] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8243603473818633, 'learning_rate': 0.016754070407166113, 'dropout_rate': 0.18244406164714, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.969239817362121, 'min_weight_fraction_leaf': 0.27320139306393876, 'max_features': None, 'min_impurity_decrease': 1.4323978100998562e-07, 'validation_fraction': 0.7967240220364479, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 07:00:50,493] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9567077577297926, 'learning_rate': 0.009321682904042736, 'dropout_rate': 0.24495589575382673, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 5.08611115752829, 'min_weight_fraction_leaf': 0.30649414543812215, 'max_features': 'auto', 'min_impurity_decrease': 1.2053286940776505e-06, 'validation_fraction': 0.7556909999934059, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 07:02:36,288] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8987436119584659, 'learning_rate': 0.0203626546956988, 'dropout_rate': 0.12954890528084062, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 1.5784834259170004, 'min_weight_fraction_leaf': 0.2550731647118252, 'max_features': 'auto', 'min_impurity_decrease': 1.890730180714205e-06, 'validation_fraction': 0.9772741387306807, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 07:03:54,524] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9426449416232375, 'learning_rate': 0.005258427870498378, 'dropout_rate': 0.29094318599258845, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.5297744472721807, 'min_weight_fraction_leaf': 0.2938783217761457, 'max_features': 1, 'min_impurity_decrease': 2.1824147145190313e-07, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21192565389705484
Fold 2 IBS: 0.22123776935159062

Fold 3 IBS: 0.20237857642828805
Fold 4 IBS: 0.22105646622231043
Fold 5 IBS: 0.21749535106188492
[I 2024-04-14 07:05:00,203] Trial 99 finished with value: 0.21481876339222578 and parameters: {'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 99 with value: 0.21481876339222578.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.21481876339222578], datetime_start=datetime.datetime(2024, 4, 14, 7, 3, 54, 536311), datetime_complete=datetime.datetime(2024, 4, 14, 7, 5, 0, 201656), params={'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for IBS:
 0.21481876339222578

In [162]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [163]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.745
train_ibs:  0.215

#### Test

In [164]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [165]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.603

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004422201299274769,
                                 criterion='squared_error',
                                 dropout_rate=0.2044520049398774,
                                 learning_rate=0.01377474153403631, max_depth=2,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=0.00015837847703956763,
                                 min_samples_leaf=13, min_samples_split=13,
                                 min_weight_fraction_leaf=0.13940114558509004,
                                 n_estimators=378, random_state=123,
                                 subsample=0.8569271041566342,
                                 validation_fraction=0.9580200141092102)

IBS: 0.22

In [166]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [167]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [168]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 07:05:14,604] A new study created in memory with name: no-name-e08a3be9-5624-483e-bc3a-7c0f4905ce7c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:05:16,072] Trial 0 finished with value: 0.70555546693142 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.70555546693142.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:05:26,193] Trial 1 finished with value: 0.7053278758950055 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.70555546693142.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:05:28,330] Trial 2 finished with value: 0.7105795179139096 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7105795179139096.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 07:05:31,123] Trial 3 finished with value: 0.7171352291868951 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 07:05:35,482] Trial 4 finished with value: 0.7160804642607784 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:05:40,242] Trial 5 finished with value: 0.7029343480613368 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:05:42,335] Trial 6 finished with value: 0.7004833676691798 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:05:42,859] Trial 7 finished with value: 0.7204471013109047 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:05:45,250] Trial 8 finished with value: 0.712874481994292 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7377450980392157
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:05:51,939] Trial 9 finished with value: 0.7118940898374293 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:05:52,345] Trial 10 finished with value: 0.63080934443503 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:05:52,631] Trial 11 finished with value: 0.643796357422043 and parameters: {'subsample': 0.23723133177827593, 'dropout_rate': 0.10580803679784617, 'n_estimators': 2, 'learning_rate': 0.09608989358701946}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:05:53,921] Trial 12 finished with value: 0.7158889143997766 and parameters: {'subsample': 0.33844938606580793, 'dropout_rate': 0.6721285244531343, 'n_estimators': 82, 'learning_rate': 0.09051861433341617}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:05:59,165] Trial 13 finished with value: 0.7248732123443066 and parameters: {'subsample': 0.12903027153499375, 'dropout_rate': 0.6941033938078734, 'n_estimators': 296, 'learning_rate': 0.03429144976267833}. Best is trial 13 with value: 0.7248732123443066.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:06:03,670] Trial 14 finished with value: 0.7340829902359167 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7138954389087271, 'n_estimators': 306, 'learning_rate': 0.03425729519343641}. Best is trial 14 with value: 0.7340829902359167.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:06:08,013] Trial 15 finished with value: 0.731553616641068 and parameters: {'subsample': 0.10123497548852628, 'dropout_rate': 0.7873619072737351, 'n_estimators': 323, 'learning_rate': 0.016491644482656317}. Best is trial 14 with value: 0.7340829902359167.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:06:12,557] Trial 16 finished with value: 0.7359390054989564 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 363, 'learning_rate': 0.01003429752501748}. Best is trial 16 with value: 0.7359390054989564.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:06:18,140] Trial 17 finished with value: 0.7170684066832458 and parameters: {'subsample': 0.2050425035399529, 'dropout_rate': 0.9227797229016296, 'n_estimators': 419, 'learning_rate': 0.0029037898937952335}. Best is trial 16 with value: 0.7359390054989564.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:06:23,200] Trial 18 finished with value: 0.713285168035674 and parameters: {'subsample': 0.37037319144530356, 'dropout_rate': 0.9695964681697122, 'n_estimators': 396, 'learning_rate': 0.01363192780505302}. Best is trial 16 with value: 0.7359390054989564.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:06:27,688] Trial 19 finished with value: 0.7222412032042431 and parameters: {'subsample': 0.16691848936207518, 'dropout_rate': 0.8098474688245095, 'n_estimators': 341, 'learning_rate': 0.03936102119031181}. Best is trial 16 with value: 0.7359390054989564.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:06:30,923] Trial 20 finished with value: 0.716885334094415 and parameters: {'subsample': 0.29109263215046977, 'dropout_rate': 0.5903532280380733, 'n_estimators': 258, 'learning_rate': 0.022816282680087063}. Best is trial 16 with value: 0.7359390054989564.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:06:35,237] Trial 21 finished with value: 0.7331221040905056 and parameters: {'subsample': 0.11014863416226671, 'dropout_rate': 0.7894895262884137, 'n_estimators': 326, 'learning_rate': 0.015088887447797343}. Best is trial 16 with value: 0.7359390054989564.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:06:40,878] Trial 22 finished with value: 0.7368779726351067 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.9771912810322235, 'n_estimators': 419, 'learning_rate': 0.012269705471982865}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:06:46,487] Trial 23 finished with value: 0.7206462014375111 and parameters: {'subsample': 0.1850567218204376, 'dropout_rate': 0.9552331062882607, 'n_estimators': 429, 'learning_rate': 0.0077115583455727365}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:06:51,170] Trial 24 finished with value: 0.7180487988401085 and parameters: {'subsample': 0.20156072978987, 'dropout_rate': 0.9933973616860394, 'n_estimators': 380, 'learning_rate': 0.02608569706066704}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:06:58,233] Trial 25 finished with value: 0.7114660312900667 and parameters: {'subsample': 0.41518848496569194, 'dropout_rate': 0.8704601572726042, 'n_estimators': 437, 'learning_rate': 0.012434348623088405}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:07:02,224] Trial 26 finished with value: 0.7160656432219072 and parameters: {'subsample': 0.2958189169734158, 'dropout_rate': 0.7567866013354554, 'n_estimators': 294, 'learning_rate': 0.02946889013847121}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:07:08,282] Trial 27 finished with value: 0.643796357422043 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.8507339987761069, 'n_estimators': 457, 'learning_rate': 0.019446112529306572}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:07:13,559] Trial 28 finished with value: 0.7053278758950055 and parameters: {'subsample': 0.6095590802808257, 'dropout_rate': 0.6002302376295083, 'n_estimators': 370, 'learning_rate': 0.03864415450530194}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:07:14,772] Trial 29 finished with value: 0.6978047962406084 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.9185025324835255, 'n_estimators': 135, 'learning_rate': 0.008574106790086229}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:07:19,050] Trial 30 finished with value: 0.7241363715132237 and parameters: {'subsample': 0.15458618028476984, 'dropout_rate': 0.9903171628408615, 'n_estimators': 403, 'learning_rate': 0.04391679459792564}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:07:22,798] Trial 31 finished with value: 0.731553616641068 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.8114843600986842, 'n_estimators': 328, 'learning_rate': 0.016869391505996457}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:07:25,919] Trial 32 finished with value: 0.7333364656337583 and parameters: {'subsample': 0.102000681955651, 'dropout_rate': 0.7505014860246594, 'n_estimators': 293, 'learning_rate': 0.008489081652056663}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 07:07:29,081] Trial 33 finished with value: 0.7151490473902328 and parameters: {'subsample': 0.24341813124327433, 'dropout_rate': 0.6204123341051746, 'n_estimators': 290, 'learning_rate': 0.006843983707907562}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 07:07:31,477] Trial 34 finished with value: 0.7201806486383269 and parameters: {'subsample': 0.18164246038967474, 'dropout_rate': 0.5051054684842515, 'n_estimators': 233, 'learning_rate': 0.009159980956225075}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:07:35,401] Trial 35 finished with value: 0.716088014526383 and parameters: {'subsample': 0.24430564869860838, 'dropout_rate': 0.7437746446335112, 'n_estimators': 354, 'learning_rate': 0.0017158565427090608}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:07:42,222] Trial 36 finished with value: 0.7248490213602743 and parameters: {'subsample': 0.1478952270746442, 'dropout_rate': 0.42504221478450555, 'n_estimators': 485, 'learning_rate': 0.062332141209271844}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:07:44,533] Trial 37 finished with value: 0.7156025034205322 and parameters: {'subsample': 0.3119274799261066, 'dropout_rate': 0.8463118546828734, 'n_estimators': 272, 'learning_rate': 0.022241926803536257}. Best is trial 22 with value: 0.7368779726351067.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:07:46,748] Trial 38 finished with value: 0.7324194175068689 and parameters: {'subsample': 0.10130616072821844, 'dropout_rate': 0.2860710109197408, 'n_estimators': 229, 'learning_rate': 0.028067533175364198}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:07:49,438] Trial 39 finished with value: 0.7211634537929987 and parameters: {'subsample': 0.21652307168545082, 'dropout_rate': 0.904275906561924, 'n_estimators': 309, 'learning_rate': 0.011375143101675419}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 07:07:53,790] Trial 40 finished with value: 0.7128888507379483 and parameters: {'subsample': 0.4315561410698563, 'dropout_rate': 0.5443446234145757, 'n_estimators': 379, 'learning_rate': 0.07617201333466918}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:07:57,838] Trial 41 finished with value: 0.726833996658032 and parameters: {'subsample': 0.15915526866054197, 'dropout_rate': 0.7756070775424474, 'n_estimators': 345, 'learning_rate': 0.0174718686711804}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:08:00,749] Trial 42 finished with value: 0.7315997266343611 and parameters: {'subsample': 0.10322385674116245, 'dropout_rate': 0.7264258363242468, 'n_estimators': 277, 'learning_rate': 0.020050603475210968}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:08:04,047] Trial 43 finished with value: 0.7278000200712385 and parameters: {'subsample': 0.13663430693394862, 'dropout_rate': 0.6393157228727168, 'n_estimators': 324, 'learning_rate': 0.03389197237045789}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:08:08,978] Trial 44 finished with value: 0.7162343470670818 and parameters: {'subsample': 0.2601940129912548, 'dropout_rate': 0.8744232037583888, 'n_estimators': 456, 'learning_rate': 0.005371751468510441}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:08:12,368] Trial 45 finished with value: 0.6978047962406084 and parameters: {'subsample': 0.7945402024352797, 'dropout_rate': 0.8202486927157613, 'n_estimators': 390, 'learning_rate': 0.012649680113277627}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:08:15,377] Trial 46 finished with value: 0.7206462014375111 and parameters: {'subsample': 0.1818222123837999, 'dropout_rate': 0.9350417805331598, 'n_estimators': 358, 'learning_rate': 0.025477159977527607}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:08:16,628] Trial 47 finished with value: 0.7277971547782146 and parameters: {'subsample': 0.1373201199185609, 'dropout_rate': 0.6410075469370599, 'n_estimators': 173, 'learning_rate': 0.014523722710668865}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:08:18,444] Trial 48 finished with value: 0.7011486337756225 and parameters: {'subsample': 0.5997115110609152, 'dropout_rate': 0.7029434264763865, 'n_estimators': 244, 'learning_rate': 0.00427576245266725}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:08:20,739] Trial 49 finished with value: 0.7211634537929987 and parameters: {'subsample': 0.21846268375703792, 'dropout_rate': 0.8900446513789535, 'n_estimators': 301, 'learning_rate': 0.04897928524498507}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:08:22,137] Trial 50 finished with value: 0.7166704305914005 and parameters: {'subsample': 0.2801684486742844, 'dropout_rate': 0.9501582476866339, 'n_estimators': 210, 'learning_rate': 0.039026346066239816}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:08:23,177] Trial 51 finished with value: 0.7315069133295224 and parameters: {'subsample': 0.10361138177639376, 'dropout_rate': 0.27203577644954774, 'n_estimators': 138, 'learning_rate': 0.029579501346200097}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:08:25,298] Trial 52 finished with value: 0.7284780633756281 and parameters: {'subsample': 0.13448357359171226, 'dropout_rate': 0.3372580141612238, 'n_estimators': 226, 'learning_rate': 0.02704823833084303}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:08:27,502] Trial 53 finished with value: 0.7216778408554625 and parameters: {'subsample': 0.1767841879114515, 'dropout_rate': 0.4885969807458471, 'n_estimators': 259, 'learning_rate': 0.020953239600338514}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:08:30,678] Trial 54 finished with value: 0.7293168079643728 and parameters: {'subsample': 0.12816729862417073, 'dropout_rate': 0.1495897230999219, 'n_estimators': 314, 'learning_rate': 0.009852232998091737}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:08:34,956] Trial 55 finished with value: 0.7222683491458465 and parameters: {'subsample': 0.2210693725673854, 'dropout_rate': 0.23563340525508142, 'n_estimators': 410, 'learning_rate': 0.031958696093131116}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:08:37,419] Trial 56 finished with value: 0.734904953083196 and parameters: {'subsample': 0.1096098809898617, 'dropout_rate': 0.6678318143513288, 'n_estimators': 346, 'learning_rate': 0.016068414122033046}. Best is trial 22 with value: 0.7368779726351067.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:08:39,744] Trial 57 finished with value: 0.717540916429782 and parameters: {'subsample': 0.3433206640803756, 'dropout_rate': 0.6663522439631572, 'n_estimators': 337, 'learning_rate': 0.014955776210569753}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:08:42,365] Trial 58 finished with value: 0.7185660511955961 and parameters: {'subsample': 0.1863707140403058, 'dropout_rate': 0.7728322826313266, 'n_estimators': 368, 'learning_rate': 0.0010488222431758228}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:08:46,016] Trial 59 finished with value: 0.726833996658032 and parameters: {'subsample': 0.15630573474368517, 'dropout_rate': 0.6904821676981175, 'n_estimators': 444, 'learning_rate': 0.005663730684868106}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:08:47,947] Trial 60 finished with value: 0.7179831828353638 and parameters: {'subsample': 0.205054171425066, 'dropout_rate': 0.5726254550080179, 'n_estimators': 284, 'learning_rate': 0.01876986623860961}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:08:49,198] Trial 61 finished with value: 0.7359414184967654 and parameters: {'subsample': 0.1069022471980777, 'dropout_rate': 0.7356857644831156, 'n_estimators': 200, 'learning_rate': 0.024909698921241077}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:08:50,009] Trial 62 finished with value: 0.7284071690800504 and parameters: {'subsample': 0.1249707253693691, 'dropout_rate': 0.7338773936689029, 'n_estimators': 150, 'learning_rate': 0.024086317208703356}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:08:52,391] Trial 63 finished with value: 0.721302236068093 and parameters: {'subsample': 0.1662041541038436, 'dropout_rate': 0.7953935813640524, 'n_estimators': 340, 'learning_rate': 0.011590165477269834}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:08:56,288] Trial 64 finished with value: 0.7334315509133684 and parameters: {'subsample': 0.10183713459244362, 'dropout_rate': 0.8283799567995446, 'n_estimators': 415, 'learning_rate': 0.016026997408142868}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:09:00,295] Trial 65 finished with value: 0.7268415469236367 and parameters: {'subsample': 0.13687794775914805, 'dropout_rate': 0.8255660415108226, 'n_estimators': 423, 'learning_rate': 0.02278795599730747}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 07:09:02,984] Trial 66 finished with value: 0.7350000383628061 and parameters: {'subsample': 0.10041763521200302, 'dropout_rate': 0.9670358724472017, 'n_estimators': 396, 'learning_rate': 0.03544011608923425}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:09:03,994] Trial 67 finished with value: 0.7162948258040311 and parameters: {'subsample': 0.25974906221514926, 'dropout_rate': 0.9673966441155493, 'n_estimators': 190, 'learning_rate': 0.041668182352134694}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:09:07,654] Trial 68 finished with value: 0.7228460802382835 and parameters: {'subsample': 0.1961242548640958, 'dropout_rate': 0.9800690685838565, 'n_estimators': 496, 'learning_rate': 0.03557646010123462}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:09:10,342] Trial 69 finished with value: 0.7242954812518696 and parameters: {'subsample': 0.1519327184313979, 'dropout_rate': 0.9993958624048898, 'n_estimators': 412, 'learning_rate': 0.050584813579231405}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:09:10,786] Trial 70 finished with value: 0.7179854548101352 and parameters: {'subsample': 0.23649207636081934, 'dropout_rate': 0.9420988995738275, 'n_estimators': 86, 'learning_rate': 0.05474597229332904}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:09:13,652] Trial 71 finished with value: 0.7295610910777057 and parameters: {'subsample': 0.11680216211078241, 'dropout_rate': 0.7590704320133158, 'n_estimators': 392, 'learning_rate': 0.016924227631907724}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 07:09:16,226] Trial 72 finished with value: 0.7333583846430191 and parameters: {'subsample': 0.10275927069926616, 'dropout_rate': 0.8512089852772666, 'n_estimators': 377, 'learning_rate': 0.03618796143639107}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:09:18,790] Trial 73 finished with value: 0.726833996658032 and parameters: {'subsample': 0.1510610295390668, 'dropout_rate': 0.898413094594842, 'n_estimators': 384, 'learning_rate': 0.03682125338487788}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:09:22,402] Trial 74 finished with value: 0.7325386937705114 and parameters: {'subsample': 0.10138470930306413, 'dropout_rate': 0.8494379105735579, 'n_estimators': 468, 'learning_rate': 0.04651197650581266}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:09:25,366] Trial 75 finished with value: 0.7029343480613368 and parameters: {'subsample': 0.6882223870109341, 'dropout_rate': 0.92262513262595, 'n_estimators': 436, 'learning_rate': 0.032618866153218046}. Best is trial 22 with value: 0.7368779726351067.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:09:28,194] Trial 76 finished with value: 0.7180977741264256 and parameters: {'subsample': 0.17522915624841012, 'dropout_rate': 0.8378045771958231, 'n_estimators': 401, 'learning_rate': 0.02994552488850459}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:09:30,615] Trial 77 finished with value: 0.7295121157913886 and parameters: {'subsample': 0.12192451662638024, 'dropout_rate': 0.8886374184433461, 'n_estimators': 368, 'learning_rate': 0.042025913086595354}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:09:32,724] Trial 78 finished with value: 0.7180487988401085 and parameters: {'subsample': 0.19990971419665512, 'dropout_rate': 0.9660653477172952, 'n_estimators': 351, 'learning_rate': 0.05979387682445049}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:09:35,645] Trial 79 finished with value: 0.7213241550773537 and parameters: {'subsample': 0.1624924984254839, 'dropout_rate': 0.8749042812122334, 'n_estimators': 420, 'learning_rate': 0.024702099303801045}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7377450980392157
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:09:39,056] Trial 80 finished with value: 0.7102282451336099 and parameters: {'subsample': 0.5101993192021703, 'dropout_rate': 0.7149950051121291, 'n_estimators': 445, 'learning_rate': 0.036602017893453756}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:09:41,789] Trial 81 finished with value: 0.7258121794804568 and parameters: {'subsample': 0.12856419982112, 'dropout_rate': 0.6762513032247001, 'n_estimators': 377, 'learning_rate': 0.00925076158747955}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 07:09:44,285] Trial 82 finished with value: 0.7343705180495187 and parameters: {'subsample': 0.1024927451432468, 'dropout_rate': 0.7462685638351548, 'n_estimators': 360, 'learning_rate': 0.01933350925265048}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:09:46,700] Trial 83 finished with value: 0.7258121794804568 and parameters: {'subsample': 0.131197363113661, 'dropout_rate': 0.8036063033033016, 'n_estimators': 359, 'learning_rate': 0.019864241707504282}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:09:49,748] Trial 84 finished with value: 0.726833996658032 and parameters: {'subsample': 0.15422889424189484, 'dropout_rate': 0.6548142178607976, 'n_estimators': 401, 'learning_rate': 0.014391699512327015}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:09:51,974] Trial 85 finished with value: 0.7334315509133684 and parameters: {'subsample': 0.1022899725426802, 'dropout_rate': 0.7583764824299879, 'n_estimators': 332, 'learning_rate': 0.027822496590124805}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 07:09:54,237] Trial 86 finished with value: 0.7228926425267913 and parameters: {'subsample': 0.18491032784644768, 'dropout_rate': 0.6960358113895483, 'n_estimators': 305, 'learning_rate': 0.026981814303832636}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7377450980392157
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 07:09:56,675] Trial 87 finished with value: 0.709736842556274 and parameters: {'subsample': 0.44812568641832, 'dropout_rate': 0.7392767492825502, 'n_estimators': 334, 'learning_rate': 0.021710162303916772}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:09:58,734] Trial 88 finished with value: 0.7295121157913886 and parameters: {'subsample': 0.11992466506972414, 'dropout_rate': 0.7701646942365531, 'n_estimators': 313, 'learning_rate': 0.01881309646356112}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:10:00,781] Trial 89 finished with value: 0.718805145682643 and parameters: {'subsample': 0.23155543773530513, 'dropout_rate': 0.6314152894615127, 'n_estimators': 352, 'learning_rate': 0.030697566275495792}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:10:02,457] Trial 90 finished with value: 0.7259681957922312 and parameters: {'subsample': 0.143997521108038, 'dropout_rate': 0.7211266599729008, 'n_estimators': 324, 'learning_rate': 0.016236716352883023}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 07:10:04,415] Trial 91 finished with value: 0.7296072010709987 and parameters: {'subsample': 0.11285973659842954, 'dropout_rate': 0.914590534158038, 'n_estimators': 380, 'learning_rate': 0.028703653394759762}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 07:10:06,425] Trial 92 finished with value: 0.7295121157913886 and parameters: {'subsample': 0.12035213651469226, 'dropout_rate': 0.7901551879698766, 'n_estimators': 363, 'learning_rate': 0.012173415325811215}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:10:08,694] Trial 93 finished with value: 0.7342973517791693 and parameters: {'subsample': 0.1012003476269077, 'dropout_rate': 0.825776631000656, 'n_estimators': 407, 'learning_rate': 0.03282523046076718}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 07:10:11,021] Trial 94 finished with value: 0.7232435143703666 and parameters: {'subsample': 0.16722949778207236, 'dropout_rate': 0.8215968724999192, 'n_estimators': 410, 'learning_rate': 0.08077924912008731}. Best is trial 22 with value: 0.7368779726351067.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 07:10:13,370] Trial 95 finished with value: 0.7360340907785666 and parameters: {'subsample': 0.10055134593356568, 'dropout_rate': 0.9340059616549866, 'n_estimators': 434, 'learning_rate': 0.024983293704130542}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 07:10:15,638] Trial 96 finished with value: 0.7244100725429314 and parameters: {'subsample': 0.14653831826242128, 'dropout_rate': 0.9477788410530358, 'n_estimators': 431, 'learning_rate': 0.025609142954482245}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 07:10:18,268] Trial 97 finished with value: 0.7070865339036634 and parameters: {'subsample': 0.5606440507914384, 'dropout_rate': 0.9332966416727289, 'n_estimators': 480, 'learning_rate': 0.033723616524412414}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 07:10:20,919] Trial 98 finished with value: 0.7153857802379611 and parameters: {'subsample': 0.2022819093692041, 'dropout_rate': 0.8714705695252908, 'n_estimators': 454, 'learning_rate': 0.022052117342070115}. Best is trial 22 with value: 0.7368779726351067.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819

[I 2024-04-14 07:10:22,682] A new study created in memory with name: no-name-88120acf-6d2c-440e-beb7-61cfe9a1d3ff

Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 07:10:22,678] Trial 99 finished with value: 0.6995905105263227 and parameters: {'subsample': 0.7891133961911398, 'dropout_rate': 0.6083010645073066, 'n_estimators': 393, 'learning_rate': 0.0036472925037491326}. Best is trial 22 with value: 0.7368779726351067.


* Best trial for C-index:
 FrozenTrial(number=22, state=TrialState.COMPLETE, values=[0.7368779726351067], datetime_start=datetime.datetime(2024, 4, 14, 7, 6, 35, 245278), datetime_complete=datetime.datetime(2024, 4, 14, 7, 6, 40, 877232), params={'subsample': 0.10322253994980501, 'dropout_rate': 0.9771912810322235, 'n_estimators': 419, 'learning_rate': 0.012269705471982865}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=22, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10322253994980501, 'dropout_rate': 0.9771912810322235, 'n_estimators': 419, 'learning_rate': 0.012269705471982865}


* Best Score for C-index:
 0.7368779726351067

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17468486153985427
Fold 2 IBS: 0.21248933875310147
Fold 3 IBS: 0.194855347846977
Fold 4 IBS: 0.22697820304357663
Fold 5 IBS: 0.28517539420510435
[I 2024-04-14 07:10:23,060] Trial 0 finished with value: 0.21883662907772275 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.1986321730994685
Fold 2 IBS: 0.3120078749344299
Fold 3 IBS: 0.24996445306241238
Fold 4 IBS: 0.31689326323842354
Fold 5 IBS: 0.335943687848095
[I 2024-04-14 07:10:25,720] Trial 1 finished with value: 0.28268829043656585 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.1782313888075919
Fold 2 IBS: 0.23887158390826022
Fold 3 IBS: 0.22391624006476715
Fold 4 IBS: 0.3051666646220198
Fold 5 IBS: 0.3084641364030169
[I 2024-04-14 07:10:26,285] Trial 2 finished with value: 0.2509300027611312 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.18280279867268556
Fold 2 IBS: 0.2687886303305837
Fold 3 IBS: 0.21057603387531768
Fold 4 IBS: 0.30155508579638324
Fold 5 IBS: 0.30154512922966814
[I 2024-04-14 07:10:27,032] Trial 3 finished with value: 0.2530535355809277 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.17768577432586086
Fold 2 IBS: 0.26071599003700413
Fold 3 IBS: 0.21099308314290005
Fold 4 IBS: 0.30353660690462075
Fold 5 IBS: 0.30872361378403196
[I 2024-04-14 07:10:28,134] Trial 4 finished with value: 0.25233101363888355 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.1904868260436939
Fold 2 IBS: 0.3132436090741233
Fold 3 IBS: 0.24395973116382566
Fold 4 IBS: 0.3159243162013543
Fold 5 IBS: 0.33186943565989657
[I 2024-04-14 07:10:29,509] Trial 5 finished with value: 0.27909678362857876 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.17780585696151255
Fold 2 IBS: 0.20708379142389674
Fold 3 IBS: 0.18227745733835357
Fold 4 IBS: 0.2141280706510948
Fold 5 IBS: 0.26351899157103026
[I 2024-04-14 07:10:30,117] Trial 6 finished with value: 0.2089628335891776 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2089628335891776.
Fold 1 IBS: 0.19015600326147195
Fold 2 IBS: 0.19355181017105216
Fold 3 IBS: 0.17743814928441723
Fold 4 IBS: 0.20291235829146803
Fold 5 IBS: 0.22736906975431576
[I 2024-04-14 07:10:30,288] Trial 7 finished with value: 0.19828547815254502 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.17040000366665245
Fold 2 IBS: 0.21357933257629527
Fold 3 IBS: 0.19414461063668192
Fold 4 IBS: 0.2318262465845874
Fold 5 IBS: 0.2884854378459845
[I 2024-04-14 07:10:31,018] Trial 8 finished with value: 0.2196871262620403 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.20715328009521433
Fold 2 IBS: 0.28062382621165427
Fold 3 IBS: 0.2432029695587583
Fold 4 IBS: 0.31679825960552194
Fold 5 IBS: 0.32925395077964825
[I 2024-04-14 07:10:33,013] Trial 9 finished with value: 0.27540645725015944 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22073305097989868
Fold 3 IBS: 0.20360033665381083
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21786150836405777
[I 2024-04-14 07:10:33,147] Trial 10 finished with value: 0.21599308091770278 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.21313236776720154
Fold 2 IBS: 0.22046918252905495
Fold 3 IBS: 0.20374843644321758
Fold 4 IBS: 0.22316838226204444
Fold 5 IBS: 0.21783099603000905
[I 2024-04-14 07:10:33,247] Trial 11 finished with value: 0.21566987300630552 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.1704735293955719
Fold 2 IBS: 0.22371331534618163
Fold 3 IBS: 0.21028536975066447
Fold 4 IBS: 0.2738014814948179
Fold 5 IBS: 0.301999663747711
[I 2024-04-14 07:10:33,583] Trial 12 finished with value: 0.23605467194698937 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.1916381360421157
Fold 2 IBS: 0.2671841424090184
Fold 3 IBS: 0.21459049695951046
Fold 4 IBS: 0.30189816891413546
Fold 5 IBS: 0.3033750519625981
[I 2024-04-14 07:10:34,807] Trial 13 finished with value: 0.2557371992574756 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.19765213183356498
Fold 2 IBS: 0.20312481708224114
Fold 3 IBS: 0.18337571072980624
Fold 4 IBS: 0.21396864848533864
Fold 5 IBS: 0.2206642376330897
[I 2024-04-14 07:10:35,098] Trial 14 finished with value: 0.20375710915280815 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.21017626388882493
Fold 2 IBS: 0.2164928794138353
Fold 3 IBS: 0.19869882569389757
Fold 4 IBS: 0.22146951352786337
Fold 5 IBS: 0.21679227193830283
[I 2024-04-14 07:10:35,336] Trial 15 finished with value: 0.2127259508925448 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.20382898092240473
Fold 2 IBS: 0.20865995687278818
Fold 3 IBS: 0.19030977064327284
Fold 4 IBS: 0.217701879376951
Fold 5 IBS: 0.21695003006174762
[I 2024-04-14 07:10:35,540] Trial 16 finished with value: 0.20749012357543287 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.17873976040794087
Fold 2 IBS: 0.22245202961786034
Fold 3 IBS: 0.1866525375903488
Fold 4 IBS: 0.22321054787529954
Fold 5 IBS: 0.27326406478224247
[I 2024-04-14 07:10:35,932] Trial 17 finished with value: 0.21686378805473838 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.17048838374646885
Fold 2 IBS: 0.19862543386442882
Fold 3 IBS: 0.1840472570167188
Fold 4 IBS: 0.19731162944762204
Fold 5 IBS: 0.2733853585304743
[I 2024-04-14 07:10:37,240] Trial 18 finished with value: 0.20477161252114257 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.19226474967500068
Fold 2 IBS: 0.19426953833697888
Fold 3 IBS: 0.17561521038419572
Fold 4 IBS: 0.19617937926603082
Fold 5 IBS: 0.21948569273556234
[I 2024-04-14 07:10:37,428] Trial 19 finished with value: 0.19556291407955367 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19556291407955367.

Fold 1 IBS: 0.19426171832065434
Fold 2 IBS: 0.19715811856127513
Fold 3 IBS: 0.17946469994393788
Fold 4 IBS: 0.20156135236511127
Fold 5 IBS: 0.21995157160040674
[I 2024-04-14 07:10:37,606] Trial 20 finished with value: 0.1984794921582771 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.1974689136933835
Fold 2 IBS: 0.20116625589103407
Fold 3 IBS: 0.18307602213830743
Fold 4 IBS: 0.20415973589751046
Fold 5 IBS: 0.21825141892231678
[I 2024-04-14 07:10:37,760] Trial 21 finished with value: 0.20082446930851044 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.2131782018406857
Fold 2 IBS: 0.21966297563854562
Fold 3 IBS: 0.20310325082392688
Fold 4 IBS: 0.22331313612323705
Fold 5 IBS: 0.21758975980778372
[I 2024-04-14 07:10:37,859] Trial 22 finished with value: 0.21536946484683578 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.16750931402711908
Fold 2 IBS: 0.19624059320767942
Fold 3 IBS: 0.17747692152992783
Fold 4 IBS: 0.19581639879093649
Fold 5 IBS: 0.26649025771923585
[I 2024-04-14 07:10:38,311] Trial 23 finished with value: 0.20070669705497973 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.17898230352039668
Fold 2 IBS: 0.19173170753090724
Fold 3 IBS: 0.17738416768704218
Fold 4 IBS: 0.19456534934637693
Fold 5 IBS: 0.24694741754828667
[I 2024-04-14 07:10:38,511] Trial 24 finished with value: 0.19792218912660192 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.1704298525889321
Fold 2 IBS: 0.20762804398231333
Fold 3 IBS: 0.18234672133552832
Fold 4 IBS: 0.22885650725731932
Fold 5 IBS: 0.28497595044100466
[I 2024-04-14 07:10:38,737] Trial 25 finished with value: 0.21484741512101957 and parameters: {'subsample': 0.41513882888547626, 'dropout_rate': 0.92193566363172, 'n_estimators': 70, 'learning_rate': 0.08579428551722094}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.1703512798387949
Fold 2 IBS: 0.22562223346851765
Fold 3 IBS: 0.20843001375733985
Fold 4 IBS: 0.29135970508437503
Fold 5 IBS: 0.3051857387236929
[I 2024-04-14 07:10:39,177] Trial 26 finished with value: 0.24018979417454406 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9863699266040719, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.22436428397738614
Fold 2 IBS: 0.2725511996750387
Fold 3 IBS: 0.23552022367923722
Fold 4 IBS: 0.32485683596649784
Fold 5 IBS: 0.3236345797555115
[I 2024-04-14 07:10:40,897] Trial 27 finished with value: 0.2761854246107343 and parameters: {'subsample': 0.26021450312326855, 'dropout_rate': 0.9019594475838296, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.1784319276912986
Fold 2 IBS: 0.25491791145635706
Fold 3 IBS: 0.21993799206943312
Fold 4 IBS: 0.3022980158292422
Fold 5 IBS: 0.30769024798209993
[I 2024-04-14 07:10:41,695] Trial 28 finished with value: 0.2526552190056862 and parameters: {'subsample': 0.5971669636685615, 'dropout_rate': 0.7292365612928325, 'n_estimators': 236, 'learning_rate': 0.046726352221374515}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.1677637708472082
Fold 2 IBS: 0.21203316623792792
Fold 3 IBS: 0.198493186070553
Fold 4 IBS: 0.22230992453466503
Fold 5 IBS: 0.2918465306042412
[I 2024-04-14 07:10:42,012] Trial 29 finished with value: 0.21848931565891908 and parameters: {'subsample': 0.3457177033536965, 'dropout_rate': 0.528113503868086, 'n_estimators': 97, 'learning_rate': 0.08423642007181871}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.16411551731670374
Fold 2 IBS: 0.20420611804318603
Fold 3 IBS: 0.19208550664521554
Fold 4 IBS: 0.2392377676875803
Fold 5 IBS: 0.286750803216586
[I 2024-04-14 07:10:42,430] Trial 30 finished with value: 0.21727914258185432 and parameters: {'subsample': 0.21287332299822773, 'dropout_rate': 0.8300645798351977, 'n_estimators': 136, 'learning_rate': 0.05802531255595394}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.19182818926996023
Fold 2 IBS: 0.1945750054983278
Fold 3 IBS: 0.17796726400707605
Fold 4 IBS: 0.19845534293847908
Fold 5 IBS: 0.2199669430451495
[I 2024-04-14 07:10:42,605] Trial 31 finished with value: 0.19655854895179853 and parameters: {'subsample': 0.15465256682910847, 'dropout_rate': 0.7665254119155692, 'n_estimators': 42, 'learning_rate': 0.04796619662341173}. Best is trial 19 with value: 0.19556291407955367.
Fold 1 IBS: 0.1803357500576901
Fold 2 IBS: 0.1890014042122981
Fold 3 IBS: 0.1680043391176252
Fold 4 IBS: 0.18027934135181622
Fold 5 IBS: 0.23535439987434953
[I 2024-04-14 07:10:42,851] Trial 32 finished with value: 0.19059504692275583 and parameters: {'subsample': 0.10342193656652618, 'dropout_rate': 0.9389584836732486, 'n_estimators': 75, 'learning_rate': 0.04909887443838165}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17524259020392927
Fold 2 IBS: 0.18941431705026662
Fold 3 IBS: 0.1669321858768433
Fold 4 IBS: 0.1807019596885962
Fold 5 IBS: 0.24288156940925884
[I 2024-04-14 07:10:43,122] Trial 33 finished with value: 0.19103452444577884 and parameters: {'subsample': 0.10120824695002664, 'dropout_rate': 0.9165491191113839, 'n_estimators': 84, 'learning_rate': 0.05193153712447138}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17256501512255987
Fold 2 IBS: 0.19166044060285933
Fold 3 IBS: 0.16617805619473233
Fold 4 IBS: 0.17643309585058128
Fold 5 IBS: 0.2498558785871286
[I 2024-04-14 07:10:43,406] Trial 34 finished with value: 0.1913384972715723 and parameters: {'subsample': 0.10905456354152472, 'dropout_rate': 0.9451805114606486, 'n_estimators': 91, 'learning_rate': 0.05207614347752842}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.16282853692365376
Fold 2 IBS: 0.20679087669966964
Fold 3 IBS: 0.17661276614283983
Fold 4 IBS: 0.18833005341520517
Fold 5 IBS: 0.28539936811940186
[I 2024-04-14 07:10:43,895] Trial 35 finished with value: 0.20399232026015404 and parameters: {'subsample': 0.10507846371518663, 'dropout_rate': 0.9999401788331197, 'n_estimators': 167, 'learning_rate': 0.05193224978956916}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1680767419923715
Fold 2 IBS: 0.20485113146183934
Fold 3 IBS: 0.1820718323317957
Fold 4 IBS: 0.2255503798805306
Fold 5 IBS: 0.28559269142762045
[I 2024-04-14 07:10:44,203] Trial 36 finished with value: 0.2132285554188315 and parameters: {'subsample': 0.2789987305825237, 'dropout_rate': 0.9397768947869433, 'n_estimators': 102, 'learning_rate': 0.06778534734243152}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1696340822381199
Fold 2 IBS: 0.1925378996118369
Fold 3 IBS: 0.1707225827791565
Fold 4 IBS: 0.1861757019260066
Fold 5 IBS: 0.25589809631788585
[I 2024-04-14 07:10:44,480] Trial 37 finished with value: 0.19499367257460115 and parameters: {'subsample': 0.18501180265201958, 'dropout_rate': 0.8608568379956052, 'n_estimators': 87, 'learning_rate': 0.05621431261796065}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17974473327984655
Fold 2 IBS: 0.24566963543620682
Fold 3 IBS: 0.21726677705287487
Fold 4 IBS: 0.30676632937496334
Fold 5 IBS: 0.3088785718394419
[I 2024-04-14 07:10:45,105] Trial 38 finished with value: 0.2516652093966667 and parameters: {'subsample': 0.1954790971490823, 'dropout_rate': 0.8663362825803563, 'n_estimators': 197, 'learning_rate': 0.07288612365177065}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1741531074162061
Fold 2 IBS: 0.19117022812858242
Fold 3 IBS: 0.1658112441781456

Fold 4 IBS: 0.19062854819614738
Fold 5 IBS: 0.2531160401238152
[I 2024-04-14 07:10:45,384] Trial 39 finished with value: 0.19497583360857934 and parameters: {'subsample': 0.2485509072011421, 'dropout_rate': 0.2538651184588351, 'n_estimators': 81, 'learning_rate': 0.05575307634287385}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1742564619506075
Fold 2 IBS: 0.2618544585408401
Fold 3 IBS: 0.1954849738012067
Fold 4 IBS: 0.2706753920831236
Fold 5 IBS: 0.29857369751177665
[I 2024-04-14 07:10:45,994] Trial 40 finished with value: 0.2401689967775109 and parameters: {'subsample': 0.24862688656216192, 'dropout_rate': 0.1585668555692103, 'n_estimators': 167, 'learning_rate': 0.08018822574072365}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17431035295693673
Fold 2 IBS: 0.19126346272609226
Fold 3 IBS: 0.16576671229380383
Fold 4 IBS: 0.1869585355531429
Fold 5 IBS: 0.24797577822458722
[I 2024-04-14 07:10:46,280] Trial 41 finished with value: 0.1932549683509126 and parameters: {'subsample': 0.1585599913809354, 'dropout_rate': 0.3148196375868446, 'n_estimators': 83, 'learning_rate': 0.05557356768144063}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1671290494081326
Fold 2 IBS: 0.20144855185246316
Fold 3 IBS: 0.17006230650155987
Fold 4 IBS: 0.19629106828284426
Fold 5 IBS: 0.27225998264294665
[I 2024-04-14 07:10:46,708] Trial 42 finished with value: 0.2014381917375893 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.26999302379658047, 'n_estimators': 125, 'learning_rate': 0.05424653086707643}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17223948083814544
Fold 2 IBS: 0.19401390001727215
Fold 3 IBS: 0.16749530189742262
Fold 4 IBS: 0.19558052529222295
Fold 5 IBS: 0.26090290488614903
[I 2024-04-14 07:10:46,980] Trial 43 finished with value: 0.19804642258624244 and parameters: {'subsample': 0.2430110855433824, 'dropout_rate': 0.29536490844597246, 'n_estimators': 79, 'learning_rate': 0.06449172446370455}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17500470147437597
Fold 2 IBS: 0.1904462971402209
Fold 3 IBS: 0.1746382330263165
Fold 4 IBS: 0.18694397289460316
Fold 5 IBS: 0.25501234516209886
[I 2024-04-14 07:10:47,382] Trial 44 finished with value: 0.1964091099395231 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.20469327838227, 'n_estimators': 115, 'learning_rate': 0.03623572468577923}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.20187063162080013
Fold 2 IBS: 0.20561388539095182
Fold 3 IBS: 0.18689541174357552
Fold 4 IBS: 0.2104713900634551
Fold 5 IBS: 0.2164973142323958
[I 2024-04-14 07:10:47,516] Trial 45 finished with value: 0.20426972661023565 and parameters: {'subsample': 0.13068805832299113, 'dropout_rate': 0.4460595216067117, 'n_estimators': 21, 'learning_rate': 0.04915746375596674}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.16671636972004447
Fold 2 IBS: 0.2607660374830686
Fold 3 IBS: 0.20069811481912922
Fold 4 IBS: 0.28924492513209604
Fold 5 IBS: 0.3056627697488687
[I 2024-04-14 07:10:48,401] Trial 46 finished with value: 0.24461764338064143 and parameters: {'subsample': 0.16726046911998677, 'dropout_rate': 0.31822754354932514, 'n_estimators': 227, 'learning_rate': 0.059281821924062436}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.16656705380139106
Fold 2 IBS: 0.2236240097798587
Fold 3 IBS: 0.18000387977097176
Fold 4 IBS: 0.2443726905225727
Fold 5 IBS: 0.2881981637738681
[I 2024-04-14 07:10:49,143] Trial 47 finished with value: 0.22055315952973248 and parameters: {'subsample': 0.2277299740630483, 'dropout_rate': 0.1240463473883398, 'n_estimators': 193, 'learning_rate': 0.052901452884087485}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.19601152012275264
Fold 2 IBS: 0.20038243698024644
Fold 3 IBS: 0.18205764317257428
Fold 4 IBS: 0.20900167503819417
Fold 5 IBS: 0.21844262987275423
[I 2024-04-14 07:10:49,275] Trial 48 finished with value: 0.20117918103730434 and parameters: {'subsample': 0.2975238164171056, 'dropout_rate': 0.19701471782839963, 'n_estimators': 19, 'learning_rate': 0.0742083228856075}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1624532072630862
Fold 2 IBS: 0.2201331560299126
Fold 3 IBS: 0.18399902867521886
Fold 4 IBS: 0.23896103911601183
Fold 5 IBS: 0.2928171179122215
[I 2024-04-14 07:10:50,401] Trial 49 finished with value: 0.21967270979929018 and parameters: {'subsample': 0.15135538768590925, 'dropout_rate': 0.3636706331127014, 'n_estimators': 272, 'learning_rate': 0.035891833524239594}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1703131800270176
Fold 2 IBS: 0.1940827239137127
Fold 3 IBS: 0.1667106944034888
Fold 4 IBS: 0.1791643104238559
Fold 5 IBS: 0.2537855523858028
[I 2024-04-14 07:10:50,770] Trial 50 finished with value: 0.19281129223077556 and parameters: {'subsample': 0.11814319708114722, 'dropout_rate': 0.4374274096737686, 'n_estimators': 110, 'learning_rate': 0.04757501495749242}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1794348062706688
Fold 2 IBS: 0.1896538544778645
Fold 3 IBS: 0.1667801799313858
Fold 4 IBS: 0.178165693443497
Fold 5 IBS: 0.24095056120353503
[I 2024-04-14 07:10:51,065] Trial 51 finished with value: 0.19099701906539024 and parameters: {'subsample': 0.10407825783072332, 'dropout_rate': 0.4338402624626162, 'n_estimators': 84, 'learning_rate': 0.04616595390661125}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.1788698511760232
Fold 2 IBS: 0.1901244277399669
Fold 3 IBS: 0.1660523581015929
Fold 4 IBS: 0.18203218668359422
Fold 5 IBS: 0.23688568112267755
[I 2024-04-14 07:10:51,464] Trial 52 finished with value: 0.19079290096477095 and parameters: {'subsample': 0.11143680359752346, 'dropout_rate': 0.4401580661014436, 'n_estimators': 113, 'learning_rate': 0.03168513402825832}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.18655615135282175
Fold 2 IBS: 0.19146671396474227
Fold 3 IBS: 0.16979548107012848
Fold 4 IBS: 0.18996307192845008
Fold 5 IBS: 0.2268539544265766
[I 2024-04-14 07:10:51,834] Trial 53 finished with value: 0.19292707454854383 and parameters: {'subsample': 0.10739468479906676, 'dropout_rate': 0.43683760589060466, 'n_estimators': 108, 'learning_rate': 0.025068006308297534}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17982021451528285
Fold 2 IBS: 0.20283213754925183
Fold 3 IBS: 0.18039048157912618
Fold 4 IBS: 0.20691358137518362
Fold 5 IBS: 0.2564154622321178
[I 2024-04-14 07:10:52,221] Trial 54 finished with value: 0.20527437545019245 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.47972285128258574, 'n_estimators': 122, 'learning_rate': 0.0316002312907681}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.16419473041780963
Fold 2 IBS: 0.20107339818977987
Fold 3 IBS: 0.17024287719591932
Fold 4 IBS: 0.18706033073978476
Fold 5 IBS: 0.2750766169309888
[I 2024-04-14 07:10:52,745] Trial 55 finished with value: 0.19952959069485648 and parameters: {'subsample': 0.12669157817599314, 'dropout_rate': 0.5085304258401852, 'n_estimators': 153, 'learning_rate': 0.045492182952046295}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.20156965410693206
Fold 2 IBS: 0.20395874465036698
Fold 3 IBS: 0.18575689997938283
Fold 4 IBS: 0.20920880606975095
Fold 5 IBS: 0.21627410589774526
[I 2024-04-14 07:10:52,964] Trial 56 finished with value: 0.20335364214083565 and parameters: {'subsample': 0.1929884973546785, 'dropout_rate': 0.40292778602491347, 'n_estimators': 59, 'learning_rate': 0.019506157375919604}. Best is trial 32 with value: 0.19059504692275583.
Fold 1 IBS: 0.17093127070775105
Fold 2 IBS: 0.19124111063464866
Fold 3 IBS: 0.1636583044980514
Fold 4 IBS: 0.17202705294497736
Fold 5 IBS: 0.2544720088899451
[I 2024-04-14 07:10:53,586] Trial 57 finished with value: 0.19046594953507473 and parameters: {'subsample': 0.10158446690685444, 'dropout_rate': 0.47900572112881107, 'n_estimators': 177, 'learning_rate': 0.028234629788730554}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.16932081861283269
Fold 2 IBS: 0.1934493742684012
Fold 3 IBS: 0.1711251784561754

Fold 4 IBS: 0.18579562086352025
Fold 5 IBS: 0.25844938334040174
[I 2024-04-14 07:10:54,528] Trial 58 finished with value: 0.19562807510826627 and parameters: {'subsample': 0.17455703880609846, 'dropout_rate': 0.5681825165583033, 'n_estimators': 177, 'learning_rate': 0.02857135261777332}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.16918296299612848
Fold 2 IBS: 0.19385471607741084
Fold 3 IBS: 0.16423780215620198
Fold 4 IBS: 0.17037260513956887
Fold 5 IBS: 0.2606061379815798
[I 2024-04-14 07:10:55,486] Trial 59 finished with value: 0.191650844870178 and parameters: {'subsample': 0.10169393529521677, 'dropout_rate': 0.4915957741107889, 'n_estimators': 156, 'learning_rate': 0.03590100641045702}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18520166379023767
Fold 2 IBS: 0.19128134476499634
Fold 3 IBS: 0.16985515532232098
Fold 4 IBS: 0.1930586229948487
Fold 5 IBS: 0.22818293335247655
[I 2024-04-14 07:10:56,171] Trial 60 finished with value: 0.19351594404497602 and parameters: {'subsample': 0.14262867520388295, 'dropout_rate': 0.5882669677272625, 'n_estimators': 138, 'learning_rate': 0.020471561460991612}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1630487100557358
Fold 2 IBS: 0.19655128003335087
Fold 3 IBS: 0.1672770601978581
Fold 4 IBS: 0.17131396915231506
Fold 5 IBS: 0.2724339470922203
[I 2024-04-14 07:10:57,215] Trial 61 finished with value: 0.194124993306296 and parameters: {'subsample': 0.1069482884348372, 'dropout_rate': 0.49858393814005675, 'n_estimators': 211, 'learning_rate': 0.03180682366531635}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1892562065523463
Fold 2 IBS: 0.19272312860865543
Fold 3 IBS: 0.17352694179708442
Fold 4 IBS: 0.19696137812520229
Fold 5 IBS: 0.2262110180450087
[I 2024-04-14 07:10:57,541] Trial 62 finished with value: 0.1957357346256594 and parameters: {'subsample': 0.21737924659848748, 'dropout_rate': 0.46711751128783624, 'n_estimators': 68, 'learning_rate': 0.03486759399285252}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1852324943946168
Fold 2 IBS: 0.1916695488653195
Fold 3 IBS: 0.1705788412812646
Fold 4 IBS: 0.19332579748598205
Fold 5 IBS: 0.22568916069274142
[I 2024-04-14 07:10:57,917] Trial 63 finished with value: 0.19329916854398488 and parameters: {'subsample': 0.13394184802626136, 'dropout_rate': 0.40903004933517045, 'n_estimators': 96, 'learning_rate': 0.02818991074181612}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1721982267300787
Fold 2 IBS: 0.19274394014303514
Fold 3 IBS: 0.1648867853075587
Fold 4 IBS: 0.1709005050672404
Fold 5 IBS: 0.25406780915619465
[I 2024-04-14 07:10:58,315] Trial 64 finished with value: 0.19095945328082153 and parameters: {'subsample': 0.10180662017343259, 'dropout_rate': 0.9527735025918749, 'n_estimators': 131, 'learning_rate': 0.03878555158574537}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17031931901058067
Fold 2 IBS: 0.2089158998596879
Fold 3 IBS: 0.18929271236505477
Fold 4 IBS: 0.22409241371329214
Fold 5 IBS: 0.28257691037458416
[I 2024-04-14 07:10:58,701] Trial 65 finished with value: 0.21503945106463992 and parameters: {'subsample': 0.45078180913690563, 'dropout_rate': 0.9399341069127701, 'n_estimators': 134, 'learning_rate': 0.04432124134348776}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.19891638325848987
Fold 2 IBS: 0.20121325140460242
Fold 3 IBS: 0.1827277157445376
Fold 4 IBS: 0.20519437414839387
Fold 5 IBS: 0.21768062795524531
[I 2024-04-14 07:10:58,859] Trial 66 finished with value: 0.2011464705022538 and parameters: {'subsample': 0.17873653326006567, 'dropout_rate': 0.958110920140438, 'n_estimators': 35, 'learning_rate': 0.038797860236966186}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18468696569302087
Fold 2 IBS: 0.1909677800674901
Fold 3 IBS: 0.1709392826369369
Fold 4 IBS: 0.1899266419442833
Fold 5 IBS: 0.2274312502109852
[I 2024-04-14 07:10:59,083] Trial 67 finished with value: 0.19279038411054328 and parameters: {'subsample': 0.138325754212348, 'dropout_rate': 0.8778822323522614, 'n_estimators': 57, 'learning_rate': 0.05131311630449647}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1660941164348067
Fold 2 IBS: 0.22621701153617865
Fold 3 IBS: 0.2057381567169501
Fold 4 IBS: 0.27123262469443554
Fold 5 IBS: 0.30060969269149684
[I 2024-04-14 07:11:01,438] Trial 68 finished with value: 0.23397832041477357 and parameters: {'subsample': 0.20226393461223402, 'dropout_rate': 0.8200813841720307, 'n_estimators': 496, 'learning_rate': 0.022282779567709743}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18056058127721675
Fold 2 IBS: 0.2087906744199945
Fold 3 IBS: 0.18140072919889613
Fold 4 IBS: 0.2109261137033639
Fold 5 IBS: 0.2604715660958165
[I 2024-04-14 07:11:01,741] Trial 69 finished with value: 0.20842993293905754 and parameters: {'subsample': 0.8584661298748817, 'dropout_rate': 0.37271980436436675, 'n_estimators': 93, 'learning_rate': 0.04428144290636794}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.2014294701692952
Fold 2 IBS: 0.20567351656929406
Fold 3 IBS: 0.18760858992938526
Fold 4 IBS: 0.21298881991930516
Fold 5 IBS: 0.21660298227663588
[I 2024-04-14 07:11:02,108] Trial 70 finished with value: 0.2048606757727831 and parameters: {'subsample': 0.2213536562486425, 'dropout_rate': 0.88867127780828, 'n_estimators': 120, 'learning_rate': 0.008227552186261713}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17019330576229122
Fold 2 IBS: 0.21341556454282076
Fold 3 IBS: 0.1927407807879857
Fold 4 IBS: 0.22849503629511206
Fold 5 IBS: 0.286437005635593
[I 2024-04-14 07:11:02,581] Trial 71 finished with value: 0.21825633860476054 and parameters: {'subsample': 0.5300843058226148, 'dropout_rate': 0.9213719383102132, 'n_estimators': 161, 'learning_rate': 0.03839861082021665}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17221385118713248
Fold 2 IBS: 0.1931027318307507
Fold 3 IBS: 0.1653669051265346
Fold 4 IBS: 0.17928327877967662
Fold 5 IBS: 0.2495560117764922
[I 2024-04-14 07:11:03,078] Trial 72 finished with value: 0.19190455574011733 and parameters: {'subsample': 0.10275580567166055, 'dropout_rate': 0.5433779614987243, 'n_estimators': 148, 'learning_rate': 0.033431833691059336}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18794587195170465
Fold 2 IBS: 0.19165692943750143
Fold 3 IBS: 0.1707439347077885
Fold 4 IBS: 0.19354469904509253
Fold 5 IBS: 0.22485668014103066
[I 2024-04-14 07:11:03,432] Trial 73 finished with value: 0.19374962305662355 and parameters: {'subsample': 0.10317771857558955, 'dropout_rate': 0.5116586133887824, 'n_estimators': 106, 'learning_rate': 0.025283493403310785}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18309069900048985
Fold 2 IBS: 0.26286033991332186
Fold 3 IBS: 0.21459755491029475
Fold 4 IBS: 0.3035722652563377
Fold 5 IBS: 0.30401689669571075
[I 2024-04-14 07:11:04,002] Trial 74 finished with value: 0.25362755115523095 and parameters: {'subsample': 0.7948212261000067, 'dropout_rate': 0.9581063374295968, 'n_estimators': 193, 'learning_rate': 0.048970538965115266}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1649813940818681
Fold 2 IBS: 0.19997570329935332
Fold 3 IBS: 0.17712302896359225
Fold 4 IBS: 0.19485446316314864
Fold 5 IBS: 0.2741286023300803
[I 2024-04-14 07:11:04,626] Trial 75 finished with value: 0.20221263836760847 and parameters: {'subsample': 0.15538557813659692, 'dropout_rate': 0.6439373471603412, 'n_estimators': 184, 'learning_rate': 0.03733986386022821}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18360675919017314
Fold 2 IBS: 0.18827344847047467
Fold 3 IBS: 0.16868295096998015
Fold 4 IBS: 0.18614268160196712
Fold 5 IBS: 0.22866496032117997
[I 2024-04-14 07:11:04,886] Trial 76 finished with value: 0.191074160110755 and parameters: {'subsample': 0.1260717925821591, 'dropout_rate': 0.42091394942662985, 'n_estimators': 74, 'learning_rate': 0.0421256001261936}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18463168993281143
Fold 2 IBS: 0.19018935889698163
Fold 3 IBS: 0.16883680319445318
Fold 4 IBS: 0.18903751837225255
Fold 5 IBS: 0.22897179468560253
[I 2024-04-14 07:11:05,134] Trial 77 finished with value: 0.19233343301642028 and parameters: {'subsample': 0.18012976919937668, 'dropout_rate': 0.4249741472200822, 'n_estimators': 70, 'learning_rate': 0.04192596817316249}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18980550827045745

Fold 2 IBS: 0.19368370154067086
Fold 3 IBS: 0.17466480787356398
Fold 4 IBS: 0.19441480400408118
Fold 5 IBS: 0.22030789644181628
[I 2024-04-14 07:11:05,321] Trial 78 finished with value: 0.19457534362611795 and parameters: {'subsample': 0.1289388075828276, 'dropout_rate': 0.3540380121430278, 'n_estimators': 45, 'learning_rate': 0.05031324288681145}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.19996995210195043
Fold 2 IBS: 0.20487136825192176
Fold 3 IBS: 0.1868270122179074
Fold 4 IBS: 0.2094329875633396
Fold 5 IBS: 0.2148277651809021
[I 2024-04-14 07:11:05,441] Trial 79 finished with value: 0.2031858170632043 and parameters: {'subsample': 0.14605546351673254, 'dropout_rate': 0.8543708031677456, 'n_estimators': 11, 'learning_rate': 0.0983514933405076}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17164249487743055
Fold 2 IBS: 0.19348710238254757
Fold 3 IBS: 0.16672720255994614
Fold 4 IBS: 0.1811824773100978
Fold 5 IBS: 0.2528607570353557
[I 2024-04-14 07:11:05,799] Trial 80 finished with value: 0.19318000683307554 and parameters: {'subsample': 0.17494339129994102, 'dropout_rate': 0.4632567093243996, 'n_estimators': 80, 'learning_rate': 0.06270524285807688}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1767305119127629
Fold 2 IBS: 0.1901025895254464
Fold 3 IBS: 0.1663192566788303
Fold 4 IBS: 0.18530911491018653
Fold 5 IBS: 0.23716297083677626
[I 2024-04-14 07:11:06,288] Trial 81 finished with value: 0.19112488877280048 and parameters: {'subsample': 0.1290036097834308, 'dropout_rate': 0.3784547205248006, 'n_estimators': 129, 'learning_rate': 0.029769641935068782}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17697485085234027
Fold 2 IBS: 0.189442378735158
Fold 3 IBS: 0.1669868058210012
Fold 4 IBS: 0.1870141002843214
Fold 5 IBS: 0.23610868401454352
[I 2024-04-14 07:11:06,605] Trial 82 finished with value: 0.19130536394147288 and parameters: {'subsample': 0.13148951972743397, 'dropout_rate': 0.3973134332180718, 'n_estimators': 92, 'learning_rate': 0.041292421081344545}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17402750371987108
Fold 2 IBS: 0.19109803703853123
Fold 3 IBS: 0.17052380620858335
Fold 4 IBS: 0.1912204628462195
Fold 5 IBS: 0.2542193075959974
[I 2024-04-14 07:11:07,067] Trial 83 finished with value: 0.19621782348184053 and parameters: {'subsample': 0.27156381539936447, 'dropout_rate': 0.3865666244218296, 'n_estimators': 138, 'learning_rate': 0.03048551856868638}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17014832436456823
Fold 2 IBS: 0.279721213978315
Fold 3 IBS: 0.21290065609266196
Fold 4 IBS: 0.3095112771066431
Fold 5 IBS: 0.31531810664332716
[I 2024-04-14 07:11:08,989] Trial 84 finished with value: 0.25751991563710314 and parameters: {'subsample': 0.1277160788198849, 'dropout_rate': 0.3421478479295125, 'n_estimators': 384, 'learning_rate': 0.046178206777150566}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1718603914983415
Fold 2 IBS: 0.19224635842472565
Fold 3 IBS: 0.1650926613599034
Fold 4 IBS: 0.18566148943118257
Fold 5 IBS: 0.24909797974640777
[I 2024-04-14 07:11:09,398] Trial 85 finished with value: 0.19279177609211218 and parameters: {'subsample': 0.15777817774457403, 'dropout_rate': 0.3881403148461216, 'n_estimators': 116, 'learning_rate': 0.041838089666429205}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18448258883272683
Fold 2 IBS: 0.19089905355732248
Fold 3 IBS: 0.17028056143865505
Fold 4 IBS: 0.1929398854679628
Fold 5 IBS: 0.2340186000828469
[I 2024-04-14 07:11:09,650] Trial 86 finished with value: 0.19452413787590284 and parameters: {'subsample': 0.23331559569396715, 'dropout_rate': 0.33509873382850536, 'n_estimators': 71, 'learning_rate': 0.03980016181457362}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18052823779063892
Fold 2 IBS: 0.18948814144678003
Fold 3 IBS: 0.16776114809115691
Fold 4 IBS: 0.18783419721927522
Fold 5 IBS: 0.2346329834966896
[I 2024-04-14 07:11:09,983] Trial 87 finished with value: 0.19204894160890812 and parameters: {'subsample': 0.12580871283224881, 'dropout_rate': 0.5331535032805622, 'n_estimators': 100, 'learning_rate': 0.03287999379573524}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.2085455281774281
Fold 2 IBS: 0.2129577601169862
Fold 3 IBS: 0.19618686328607562
Fold 4 IBS: 0.21778974296666584
Fold 5 IBS: 0.21633916382492865
[I 2024-04-14 07:11:10,134] Trial 88 finished with value: 0.21036381167441687 and parameters: {'subsample': 0.20202766362196517, 'dropout_rate': 0.42962852693374687, 'n_estimators': 29, 'learning_rate': 0.017282087080855827}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1802307641202605
Fold 2 IBS: 0.18998498978826217
Fold 3 IBS: 0.16686773379846084
Fold 4 IBS: 0.1889431389873783
Fold 5 IBS: 0.23397907810537105
[I 2024-04-14 07:11:10,569] Trial 89 finished with value: 0.19200114095994655 and parameters: {'subsample': 0.15824229970869488, 'dropout_rate': 0.4084619203857438, 'n_estimators': 128, 'learning_rate': 0.026681988071217248}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1873912957758612
Fold 2 IBS: 0.191600904275189
Fold 3 IBS: 0.1718842157987294
Fold 4 IBS: 0.1922134894213369
Fold 5 IBS: 0.22404792781321287
[I 2024-04-14 07:11:10,867] Trial 90 finished with value: 0.19342756661686583 and parameters: {'subsample': 0.12559533908256393, 'dropout_rate': 0.47433109731576706, 'n_estimators': 88, 'learning_rate': 0.02925122402627411}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18705580012298495
Fold 2 IBS: 0.18812063171815285
Fold 3 IBS: 0.17163867976399863
Fold 4 IBS: 0.1880368727936419
Fold 5 IBS: 0.22861790077777291
[I 2024-04-14 07:11:11,063] Trial 91 finished with value: 0.19269397703531024 and parameters: {'subsample': 0.11984292115884303, 'dropout_rate': 0.9192758169082014, 'n_estimators': 51, 'learning_rate': 0.05316404205866543}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18231282564113552
Fold 2 IBS: 0.18918363479314296
Fold 3 IBS: 0.1679868285412437
Fold 4 IBS: 0.18972872078584532
Fold 5 IBS: 0.23275609925021581
[I 2024-04-14 07:11:11,297] Trial 92 finished with value: 0.19239362180231664 and parameters: {'subsample': 0.1459913322753606, 'dropout_rate': 0.9710400663076758, 'n_estimators': 70, 'learning_rate': 0.0441183385632035}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17370454523555787
Fold 2 IBS: 0.19189840780750325
Fold 3 IBS: 0.16733459837658446
Fold 4 IBS: 0.172184287869358
Fold 5 IBS: 0.2545390440469014
[I 2024-04-14 07:11:11,593] Trial 93 finished with value: 0.19193217666718101 and parameters: {'subsample': 0.10127934669764797, 'dropout_rate': 0.4550270256933496, 'n_estimators': 86, 'learning_rate': 0.05784583060885566}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1706157973591188
Fold 2 IBS: 0.19519977138696468
Fold 3 IBS: 0.16777400335970838
Fold 4 IBS: 0.18800978189445944
Fold 5 IBS: 0.26039759757959346
[I 2024-04-14 07:11:11,920] Trial 94 finished with value: 0.19639939031596892 and parameters: {'subsample': 0.19119037226827262, 'dropout_rate': 0.9461354546309334, 'n_estimators': 107, 'learning_rate': 0.04766715116613102}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1610339818618072
Fold 2 IBS: 0.22552860137644684
Fold 3 IBS: 0.18782698301132997
Fold 4 IBS: 0.24432080856080013
Fold 5 IBS: 0.29652269683920285
[I 2024-04-14 07:11:13,191] Trial 95 finished with value: 0.2230466143299174 and parameters: {'subsample': 0.17043407745053826, 'dropout_rate': 0.41913680912261475, 'n_estimators': 297, 'learning_rate': 0.03427996370339302}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.17736112272567894
Fold 2 IBS: 0.18975087128532095
Fold 3 IBS: 0.1651469777853348
Fold 4 IBS: 0.18742908742783915
Fold 5 IBS: 0.23740910626366823
[I 2024-04-14 07:11:13,522] Trial 96 finished with value: 0.19141943309756843 and parameters: {'subsample': 0.1410028502543736, 'dropout_rate': 0.3762147013166444, 'n_estimators': 97, 'learning_rate': 0.040449874588649556}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.16532039944760768
Fold 2 IBS: 0.1990768216257136
Fold 3 IBS: 0.16827508581573403

Fold 4 IBS: 0.1725939047574419
Fold 5 IBS: 0.26916428963724165
[I 2024-04-14 07:11:13,907] Trial 97 finished with value: 0.19488610025674777 and parameters: {'subsample': 0.11658895674183224, 'dropout_rate': 0.5693703139031614, 'n_estimators': 116, 'learning_rate': 0.05468275806027857}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.1819200561017552
Fold 2 IBS: 0.19484138963367623
Fold 3 IBS: 0.17803463882277085
Fold 4 IBS: 0.20400784936010083
Fold 5 IBS: 0.24720801744754423
[I 2024-04-14 07:11:14,356] Trial 98 finished with value: 0.2012023902731695 and parameters: {'subsample': 0.6256495106817341, 'dropout_rate': 0.5171615627018341, 'n_estimators': 140, 'learning_rate': 0.02311141545634017}. Best is trial 57 with value: 0.19046594953507473.
Fold 1 IBS: 0.18497690412089743
Fold 2 IBS: 0.2047865657788103
Fold 3 IBS: 0.1778718387416613
Fold 4 IBS: 0.21398164113622073
Fold 5 IBS: 0.24576001387482957
[I 2024-04-14 07:11:14,565] Trial 99 finished with value: 0.20547539273048385 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.7430212022127866, 'n_estimators': 61, 'learning_rate': 0.051024460885117466}. Best is trial 57 with value: 0.19046594953507473.


* Best trial for IBS:
 FrozenTrial(number=57, state=TrialState.COMPLETE, values=[0.19046594953507473], datetime_start=datetime.datetime(2024, 4, 14, 7, 10, 52, 965273), datetime_complete=datetime.datetime(2024, 4, 14, 7, 10, 53, 586685), params={'subsample': 0.10158446690685444, 'dropout_rate': 0.47900572112881107, 'n_estimators': 177, 'learning_rate': 0.028234629788730554}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=57, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10158446690685444, 'dropout_rate': 0.47900572112881107, 'n_estimators': 177, 'learning_rate': 0.028234629788730554}


* Best Score for IBS:
 0.19046594953507473

In [169]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [170]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.737
train_ibs:  0.19

#### Test

In [171]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [172]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9771912810322235,
                                              learning_rate=0.012269705471982865,
                                              n_estimators=419,
                                              random_state=123,
                                              subsample=0.10322253994980501)

C-index score: 0.509

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.47900572112881107,
                                              learning_rate=0.028234629788730554,
                                              n_estimators=177,
                                              random_state=123,
                                              subsample=0.10158446690685444)

IBS: 0.259

In [173]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [174]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.826   1.0
ExtraSurvivalTrees               0.794   2.0
CoxLasso                         0.746   3.5
CoxElastic                       0.746   3.5
GradientBoosting                 0.745   5.0
CoxPH                            0.743   6.0
ComponentwiseGradientBoosting    0.737   7.0
CoxRidge                         0.675   8.0

In [175]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.183   1.5
ExtraSurvivalTrees             0.183   1.5
CoxLasso                       0.189   3.5
CoxElastic                     0.189   3.5
CoxPH                          0.190   5.5
ComponentwiseGradientBoosting  0.190   5.5
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [176]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.653   1.0
ExtraSurvivalTrees               0.618   2.0
GradientBoosting                 0.603   3.0
CoxLasso                         0.592   4.5
CoxElastic                       0.592   4.5
CoxPH                            0.581   6.0
CoxRidge                         0.534   7.0
ComponentwiseGradientBoosting    0.509   8.0

In [177]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.206   1.0
ExtraSurvivalTrees             0.215   2.0
GradientBoosting               0.220   3.0
CoxRidge                       0.221   4.0
ComponentwiseGradientBoosting  0.259   5.0
CoxLasso                       0.280   6.5
CoxElastic                     0.280   6.5
CoxPH                          0.281   8.0

In [178]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/yeojohnson/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_os_yeojohnson_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [179]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14