In [129]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import PowerTransformer

In [130]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [131]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [132]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [133]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [134]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [135]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [136]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [137]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [138]:
# Merge MAASTRO_D1 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [139]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [140]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [141]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
times = np.arange(lower, upper)

In [142]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [143]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [144]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [145]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

# Feature Selection: RENT

In [146]:
# Choose features from the result of RENT 
selected_features = ["age",
"cavum_oris",
"hpv_related",
"uicc8_III-IV",
"oropharynx",
"pack_years",
"charlson"]

In [147]:
X_rent = X.loc[:, selected_features]
X_new = X_rent.copy()

In [148]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Yeo-Johnson Transformation

In [149]:
# Copy the original X for later 
original_X = X.copy()

In [150]:
X_new.columns

Index(['age', 'cavum_oris', 'hpv_related', 'uicc8_III-IV', 'oropharynx',
       'pack_years', 'charlson'],
      dtype='object')

In [151]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)
X_new_std = X_new_std.reindex(columns=X_new.columns)

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new.reindex(columns=X_new.columns)
MAASTRO_new_std = MAASTRO_new_std.reindex(columns=X_new.columns)

In [152]:
X_new

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,54.238356,0,0.0,0.0,1,0.000000,0
1,54.539726,0,0.0,0.0,0,27.404795,1
2,59.019178,1,0.0,1.0,0,41.019178,1
3,70.726027,0,0.0,0.0,0,37.500000,1
4,67.865753,0,0.0,0.0,0,53.000000,1
...,...,...,...,...,...,...,...
134,60.435616,0,1.0,0.0,1,0.000000,0
135,68.794521,0,1.0,1.0,1,0.000000,0
136,57.498630,0,1.0,0.0,1,39.498630,1
137,65.684932,0,1.0,1.0,1,71.527397,1
138,61.676712,0,1.0,1.0,1,2.250000,0

In [153]:
X_new_std

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,-0.785036,0,0.0,0.0,1,-1.533345,0
1,-0.746998,0,0.0,0.0,0,0.397233,1
2,-0.175256,1,0.0,1.0,0,0.830437,1
3,1.371631,0,0.0,0.0,0,0.727938,1
4,0.987008,0,0.0,0.0,0,1.144253,1
...,...,...,...,...,...,...,...
134,0.007949,0,1.0,0.0,1,-1.533345,0
135,1.111443,0,1.0,1.0,1,-1.533345,0
136,-0.370651,0,1.0,0.0,1,0.786825,1
137,0.696583,0,1.0,1.0,1,1.554125,1
138,0.169401,0,1.0,1.0,1,-1.110899,0

In [154]:
MAASTRO_new

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,55,0,1,0,1,0,1
1,55,0,0,1,1,20,0
2,55,0,0,1,1,6,1
3,61,0,0,1,0,45,1
4,70,0,1,0,1,59,1
...,...,...,...,...,...,...,...
94,66,0,0,1,0,55,0
95,63,0,0,1,0,174,1
96,63,0,1,1,1,0,1
97,54,0,1,0,1,0,0
98,62,0,0,1,0,40,0

In [155]:
MAASTRO_new_std

,age,cavum_oris,hpv_related,uicc8_III-IV,oropharynx,pack_years,charlson
0,-0.688798,0,1,0,1,-1.533345,1
1,-0.688798,0,0,1,1,0.104884,0
2,-0.688798,0,0,1,1,-0.713198,1
3,0.081262,0,0,1,0,0.940197,1
4,1.273609,0,1,0,1,1.285347,1
...,...,...,...,...,...,...,...
94,0.738387,0,0,1,0,1.192311,0
95,0.342484,0,0,1,0,3.094727,1
96,0.342484,0,1,1,1,-1.533345,1
97,-0.815082,0,1,0,1,-1.533345,0
98,0.211597,0,0,1,0,0.801315,0

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [156]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:59:31,227] A new study created in memory with name: no-name-c201f636-a6a6-4ce7-80f8-29e6e0548b7c

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8481012658227848

[I 2024-04-13 23:59:33,613] A new study created in memory with name: no-name-9f7b5ff9-40a9-4a38-8d46-5397f32930f4

Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:33,604] Trial 0 finished with value: 0.7633991699809635 and parameters: {}. Best is trial 0 with value: 0.7633991699809635.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7633991699809635], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 31, 321698), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 33, 603104), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7633991699809635

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16083908303470473
Fold 2 IBS: 0.17782936802981544
Fold 3 IBS: 0.15392547258993877
Fold 4 IBS: 0.1487529169730995
Fold 5 IBS: 0.2589625484030112
[I 2024-04-13 23:59:35,956] Trial 0 finished with value: 0.1800618778061139 and parameters: {}. Best is trial 0 with value: 0.1800618778061139.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1800618778061139], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 33, 971562), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 35, 955714), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1800618778061139

In [157]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [158]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.763
train_ibs:  0.18

#### Test

In [159]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [160]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.572
IBS score: 0.274

In [161]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [162]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [163]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:59:36,921] A new study created in memory with name: no-name-0675379c-702b-4d41-8f28-c4ba47533a01

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.640625
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.7784810126582279

[I 2024-04-13 23:59:38,589] A new study created in memory with name: no-name-14f8d5f2-1175-4ba4-b72a-faf13eed4a46

Fold 5 C-index: 0.5727699530516432
[I 2024-04-13 23:59:38,537] Trial 0 finished with value: 0.6878264281814446 and parameters: {}. Best is trial 0 with value: 0.6878264281814446.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6878264281814446], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 37, 313262), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 38, 537482), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6878264281814446

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651688105565
Fold 2 IBS: 0.22157791055888598
Fold 3 IBS: 0.20453594148397225
Fold 4 IBS: 0.22473803361997696
Fold 5 IBS: 0.21812431365411103
[I 2024-04-13 23:59:40,856] Trial 0 finished with value: 0.2165905432396004 and parameters: {}. Best is trial 0 with value: 0.2165905432396004.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2165905432396004], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 38, 972282), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 40, 855896), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2165905432396004

In [164]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [165]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.688
train_ibs:  0.217

#### Test

In [166]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [167]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [168]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [169]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:59:41,341] A new study created in memory with name: no-name-ea82e667-75a8-4bab-b21a-fef8e65b541e

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848

[I 2024-04-13 23:59:44,574] A new study created in memory with name: no-name-58580a70-0e85-4610-8e4c-716c0d11a753

Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 23:59:44,556] Trial 0 finished with value: 0.7599423327005967 and parameters: {}. Best is trial 0 with value: 0.7599423327005967.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7599423327005967], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 41, 849256), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 44, 555255), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7599423327005967

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.16110404192759542
Fold 2 IBS: 0.1850963138512818
Fold 3 IBS: 0.15349562060437788
Fold 4 IBS: 0.14737342192359726
Fold 5 IBS: 0.25731405171852934
[I 2024-04-13 23:59:49,033] Trial 0 finished with value: 0.1808766900050763 and parameters: {}. Best is trial 0 with value: 0.1808766900050763.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1808766900050763], datetime_start=datetime.datetime(2024, 4, 13, 23, 59, 44, 764242), datetime_complete=datetime.datetime(2024, 4, 13, 23, 59, 49, 32499), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1808766900050763

In [170]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [171]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.76
train_ibs:  0.181

#### Test

In [172]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [173]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.577

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.269

In [174]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [175]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 23:59:52,364] A new study created in memory with name: no-name-420bac82-1fae-400d-a748-193dad573a49

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 23:59:55,997] Trial 0 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7598962227073037.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 23:59:58,891] Trial 1 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7598962227073037.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:03,509] Trial 2 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7598962227073037.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:07,632] Trial 3 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7598962227073037.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:11,514] Trial 4 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:15,133] Trial 5 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:18,413] Trial 6 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:22,082] Trial 7 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:25,918] Trial 8 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:29,113] Trial 9 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:31,659] Trial 10 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:35,574] Trial 11 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9954153487071029}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:39,236] Trial 12 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.8248288740076454}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:43,177] Trial 13 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8136827928100274}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:46,478] Trial 14 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:49,599] Trial 15 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8328859424067903}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:52,565] Trial 16 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6653074061398166}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:00:55,460] Trial 17 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8280353827474872}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:00:58,133] Trial 18 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5995916040937666}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:01,460] Trial 19 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7736309176939304}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:04,684] Trial 20 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.8972371984714923}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:07,694] Trial 21 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.8835843224108981}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:09,950] Trial 22 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7606522186263021}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:11,931] Trial 23 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.8889810233987315}. Best is trial 4 with value: 0.7608351898434539.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:13,968] Trial 24 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6311595421486845}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:16,775] Trial 25 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7477530840540471}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:18,663] Trial 26 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5655191009169166}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:20,630] Trial 27 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8395242097038057}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:22,697] Trial 28 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7205903470501512}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:24,677] Trial 29 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9110380551443042}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:26,706] Trial 30 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6894297343739559}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:29,061] Trial 31 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7805636507477988}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:31,290] Trial 32 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.774312073175179}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:33,154] Trial 33 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9326745116073929}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 00:01:34,497] Trial 34 finished with value: 0.6954296323304116 and parameters: {'l1_ratio': 0.0037772681753269755}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:37,086] Trial 35 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8360631196124947}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:39,346] Trial 36 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.64388366625112}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:41,664] Trial 37 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5054028416661493}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:43,869] Trial 38 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7039737188855323}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:46,564] Trial 39 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:48,807] Trial 40 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:51,548] Trial 41 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8453995437763238}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:01:53,623] Trial 42 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9330298242268411}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:56,501] Trial 43 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.7944887369006646}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:01:58,687] Trial 44 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8717249879313654}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:01,179] Trial 45 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7323210384855136}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:03,633] Trial 46 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.944164944589737}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:06,546] Trial 47 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8461329736571472}. Best is trial 4 with value: 0.7608351898434539.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:09,184] Trial 48 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9631281987642258}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:11,805] Trial 49 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:13,988] Trial 50 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5938078108685914}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:15,955] Trial 51 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7145748209714864}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:18,083] Trial 52 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7864328178437691}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:19,983] Trial 53 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7372919291516811}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:22,769] Trial 54 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.815338395476501}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:25,919] Trial 55 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6744418315818305}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:28,370] Trial 56 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6260166567068426}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:30,566] Trial 57 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8660532692979819}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:32,750] Trial 58 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8065317133972703}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:34,762] Trial 59 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.754164239726686}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:37,084] Trial 60 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.2047834856757912}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:39,335] Trial 61 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7718485575101891}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:41,431] Trial 62 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9021519450612746}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:43,570] Trial 63 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7107013765981689}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:46,060] Trial 64 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6554343575655337}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:48,532] Trial 65 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8279179129882649}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:51,356] Trial 66 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7865233087561105}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:54,146] Trial 67 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8719524804015109}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:02:57,578] Trial 68 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7408865837473612}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:02:59,819] Trial 69 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9912652237205304}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:02,285] Trial 70 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6869545928343562}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:04,645] Trial 71 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7701661405973381}. Best is trial 4 with value: 0.7608351898434539.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:06,460] Trial 72 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8505041645100946}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:08,781] Trial 73 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8070122977597664}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:11,113] Trial 74 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.732651539636735}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:13,132] Trial 75 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.910942721380767}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:15,297] Trial 76 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.7718060673206022}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:17,541] Trial 77 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5945449732743856}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:19,623] Trial 78 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8216838711526583}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:21,986] Trial 79 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7120921418578845}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:24,042] Trial 80 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.5487936211972553}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:26,248] Trial 81 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8418123488382484}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:28,357] Trial 82 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8825120791406728}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:30,268] Trial 83 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7890950042017242}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:32,568] Trial 84 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9594594845516515}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:34,395] Trial 85 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.9254047826070391}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:36,522] Trial 86 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8526341711451}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:38,752] Trial 87 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8264165092004155}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:41,213] Trial 88 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7531471745858783}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:42,851] Trial 89 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6762998225457834}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:44,896] Trial 90 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7253405435487246}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:46,690] Trial 91 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8005296998139079}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:48,486] Trial 92 finished with value: 0.7608351898434539 and parameters: {'l1_ratio': 0.8322863665335952}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:50,341] Trial 93 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8617942459159145}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 00:03:52,114] Trial 94 finished with value: 0.7599423327005967 and parameters: {'l1_ratio': 0.8993506868303637}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:54,021] Trial 95 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.769242924786557}. Best is trial 4 with value: 0.7608351898434539.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:55,868] Trial 96 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8824838530201219}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:57,974] Trial 97 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.6242322112672503}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:03:59,768] Trial 98 finished with value: 0.7590033655644465 and parameters: {'l1_ratio': 0.8024162214307801}. Best is trial 4 with value: 0.7608351898434539.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 00:04:01,903] Trial 99 finished with value: 0.7598962227073037 and parameters: {'l1_ratio': 0.7027028067805403}. Best is trial 4 with value: 0.7608351898434539.

[I 2024-04-14 00:04:02,152] A new study created in memory with name: no-name-d6af47bf-dcf9-4d11-8e66-866eb4d183c6

* Best trial for C-index:
 FrozenTrial(number=4, state=TrialState.COMPLETE, values=[0.7608351898434539], datetime_start=datetime.datetime(2024, 4, 14, 0, 0, 7, 660497), datetime_complete=datetime.datetime(2024, 4, 14, 0, 0, 11, 508441), params={'l1_ratio': 0.7194970228885845}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=4, value=None)


* Best Score for C-index:
 0.7608351898434539

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16104778611325374
Fold 2 IBS: 0.18451024301927516
Fold 3 IBS: 0.15335484337078437
Fold 4 IBS: 0.1473613938635699
Fold 5 IBS: 0.25716919342656835
[I 2024-04-14 00:04:04,499] Trial 0 finished with value: 0.1806886919586903 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.1806886919586903.
Fold 1 IBS: 0.1609248986949724
Fold 2 IBS: 0.18357347655213407
Fold 3 IBS: 0.15319254722217174
Fold 4 IBS: 0.14725671210972432
Fold 5 IBS: 0.25703159098488604
[I 2024-04-14 00:04:06,577] Trial 1 finished with value: 0.1803958451127777 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.1803958451127777.
Fold 1 IBS: 0.1609083029281512
Fold 2 IBS: 0.18339581114281553
Fold 3 IBS: 0.1531353127892448
Fold 4 IBS: 0.1471872738245949
Fold 5 IBS: 0.2570843134945033
[I 2024-04-14 00:04:08,570] Trial 2 finished with value: 0.18034220283586194 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.1610078758049508
Fold 2 IBS: 0.18420181911014807
Fold 3 IBS: 0.15326023451479895
Fold 4 IBS: 0.1472847371525702
Fold 5 IBS: 0.25717321784278746
[I 2024-04-14 00:04:10,529] Trial 3 finished with value: 0.1805855768850511 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.16104768673769754
Fold 2 IBS: 0.18455733506848945
Fold 3 IBS: 0.15333487660854137
Fold 4 IBS: 0.1472809220575838
Fold 5 IBS: 0.2572366110112408
[I 2024-04-14 00:04:12,238] Trial 4 finished with value: 0.1806914862967106 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.16096906941576417
Fold 2 IBS: 0.1838890496517619
Fold 3 IBS: 0.15320818490487875
Fold 4 IBS: 0.14729386717447102
Fold 5 IBS: 0.25713566003535526
[I 2024-04-14 00:04:14,699] Trial 5 finished with value: 0.1804991662364462 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.16110431110205822
Fold 2 IBS: 0.185068277005147
Fold 3 IBS: 0.1534783462523194
Fold 4 IBS: 0.1473458034507503
Fold 5 IBS: 0.2572711022690198
[I 2024-04-14 00:04:16,900] Trial 6 finished with value: 0.18085356801585895 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.16103483120717307
Fold 2 IBS: 0.18448533542470885
Fold 3 IBS: 0.15334074156095673
Fold 4 IBS: 0.1473379107794271
Fold 5 IBS: 0.2571335082203107
[I 2024-04-14 00:04:19,078] Trial 7 finished with value: 0.18066646543851528 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.16098354215734856
Fold 2 IBS: 0.18403453926600008
Fold 3 IBS: 0.1532559178629498
Fold 4 IBS: 0.14721777611995573
Fold 5 IBS: 0.2570667692083479
[I 2024-04-14 00:04:21,238] Trial 8 finished with value: 0.1805117089229204 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.1609563488469891
Fold 2 IBS: 0.18383261313680288
Fold 3 IBS: 0.1532043062928288
Fold 4 IBS: 0.14731421807741507
Fold 5 IBS: 0.25698958632113594
[I 2024-04-14 00:04:23,786] Trial 9 finished with value: 0.18045941453503436 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.18034220283586194.
Fold 1 IBS: 0.16086300861271302
Fold 2 IBS: 0.18108032122647133
Fold 3 IBS: 0.15309095235962067
Fold 4 IBS: 0.14721142327299358
Fold 5 IBS: 0.25690492934847975
[I 2024-04-14 00:04:26,790] Trial 10 finished with value: 0.17983012696405568 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.17983012696405568.
Fold 1 IBS: 0.2133774722183375
Fold 2 IBS: 0.2207964152235585
Fold 3 IBS: 0.20384338991875048
Fold 4 IBS: 0.22382382496282693
Fold 5 IBS: 0.21793727278497435
[I 2024-04-14 00:04:27,766] Trial 11 finished with value: 0.21595567502168955 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.17983012696405568.
Fold 1 IBS: 0.16086299850425687
Fold 2 IBS: 0.18108266193509603
Fold 3 IBS: 0.15309018261787063
Fold 4 IBS: 0.14720996424071373
Fold 5 IBS: 0.25690291474449806
[I 2024-04-14 00:04:30,149] Trial 12 finished with value: 0.1798297444084871 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.1798297444084871.
Fold 1 IBS: 0.21381588156373524
Fold 2 IBS: 0.2213679288231817
Fold 3 IBS: 0.20435093370346463
Fold 4 IBS: 0.22449190537095037
Fold 5 IBS: 0.2180737278078542
[I 2024-04-14 00:04:31,162] Trial 13 finished with value: 0.21642007545383724 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.1798297444084871.
Fold 1 IBS: 0.1608850725776546
Fold 2 IBS: 0.1832192538019742
Fold 3 IBS: 0.15310288497666702
Fold 4 IBS: 0.14718751379663958
Fold 5 IBS: 0.25705895912417354
[I 2024-04-14 00:04:33,474] Trial 14 finished with value: 0.1802907368554218 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.1798297444084871.
Fold 1 IBS: 0.16088518523163486
Fold 2 IBS: 0.18324055161436423
Fold 3 IBS: 0.15311294829976257
Fold 4 IBS: 0.1472065216328171
Fold 5 IBS: 0.2569209023559225
[I 2024-04-14 00:04:35,918] Trial 15 finished with value: 0.18027322182690025 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.1798297444084871.
Fold 1 IBS: 0.16088045632156184
Fold 2 IBS: 0.1831243174185109
Fold 3 IBS: 0.15311892819917156
Fold 4 IBS: 0.1472274578357852
Fold 5 IBS: 0.25694505559814323
[I 2024-04-14 00:04:38,398] Trial 16 finished with value: 0.18025924307463453 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.1798297444084871.
Fold 1 IBS: 0.16092582325471647
Fold 2 IBS: 0.1835968095711305
Fold 3 IBS: 0.15314421815070856
Fold 4 IBS: 0.1472779355027855
Fold 5 IBS: 0.2570611016282241
[I 2024-04-14 00:04:40,627] Trial 17 finished with value: 0.180401177621513 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.1798297444084871.
Fold 1 IBS: 0.1608562821088103
Fold 2 IBS: 0.18081729682466535
Fold 3 IBS: 0.153054980849113
Fold 4 IBS: 0.14728165863474155
Fold 5 IBS: 0.2569890141597511
[I 2024-04-14 00:04:43,029] Trial 18 finished with value: 0.17979984651541625 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16110414008384627
Fold 2 IBS: 0.1850861329520588
Fold 3 IBS: 0.15348934121741895
Fold 4 IBS: 0.1473632622865966
Fold 5 IBS: 0.25729845533203477
[I 2024-04-14 00:04:44,860] Trial 19 finished with value: 0.18086826637439107 and parameters: {'l1_ratio': 0.9929377968859474}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16090774163969992
Fold 2 IBS: 0.1834754188078498
Fold 3 IBS: 0.15316770317021283
Fold 4 IBS: 0.1472601837976304
Fold 5 IBS: 0.2570152522277066
[I 2024-04-14 00:04:46,873] Trial 20 finished with value: 0.1803652599286199 and parameters: {'l1_ratio': 0.2388879688839749}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16086314067755786
Fold 2 IBS: 0.18104933080560592
Fold 3 IBS: 0.1531011465604696
Fold 4 IBS: 0.14723072556130976
Fold 5 IBS: 0.25693152893916316
[I 2024-04-14 00:04:49,805] Trial 21 finished with value: 0.17983517450882128 and parameters: {'l1_ratio': 0.08499433228302328}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.1608580656198578
Fold 2 IBS: 0.18090916660650452
Fold 3 IBS: 0.1531077635533376
Fold 4 IBS: 0.14725379420717205
Fold 5 IBS: 0.2569581973535618
[I 2024-04-14 00:04:52,402] Trial 22 finished with value: 0.17981739746808673 and parameters: {'l1_ratio': 0.07181511589086235}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.21385701189705342
Fold 2 IBS: 0.2214216958437877
Fold 3 IBS: 0.2043983375199022
Fold 4 IBS: 0.2245548735646799
Fold 5 IBS: 0.2180866482381502
[I 2024-04-14 00:04:53,352] Trial 23 finished with value: 0.2164637134127147 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16090116625909337
Fold 2 IBS: 0.18333632774862538
Fold 3 IBS: 0.15311927418661342
Fold 4 IBS: 0.1473018702529134
Fold 5 IBS: 0.2570585955119947
[I 2024-04-14 00:04:55,621] Trial 24 finished with value: 0.18034344679184805 and parameters: {'l1_ratio': 0.20495632796046423}. Best is trial 18 with value: 0.17979984651541625.

Fold 1 IBS: 0.16095633204662854
Fold 2 IBS: 0.18378571499753618
Fold 3 IBS: 0.15317979537938767
Fold 4 IBS: 0.14727206416174068
Fold 5 IBS: 0.25709241819825984
[I 2024-04-14 00:04:57,920] Trial 25 finished with value: 0.18045726495671058 and parameters: {'l1_ratio': 0.3804525958179419}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.1609447058146484
Fold 2 IBS: 0.18371527005793908
Fold 3 IBS: 0.15318722138516566
Fold 4 IBS: 0.1472042050958536
Fold 5 IBS: 0.25698679393803664
[I 2024-04-14 00:05:00,249] Trial 26 finished with value: 0.18040763925832864 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16085788163181322
Fold 2 IBS: 0.18095123883742373
Fold 3 IBS: 0.15309395372044504
Fold 4 IBS: 0.14722766946238738
Fold 5 IBS: 0.2569221645669365
[I 2024-04-14 00:05:02,707] Trial 27 finished with value: 0.17981058164380118 and parameters: {'l1_ratio': 0.07046652721581821}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16089463006524668
Fold 2 IBS: 0.18337960081907334
Fold 3 IBS: 0.15309999108809047
Fold 4 IBS: 0.14728096641600635
Fold 5 IBS: 0.25702325382612934
[I 2024-04-14 00:05:05,038] Trial 28 finished with value: 0.18033568844290923 and parameters: {'l1_ratio': 0.1840952093317843}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16107853759067275
Fold 2 IBS: 0.1848788683497439
Fold 3 IBS: 0.15342484747050925
Fold 4 IBS: 0.14732104048630698
Fold 5 IBS: 0.25719667813736036
[I 2024-04-14 00:05:06,846] Trial 29 finished with value: 0.18077999440691866 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16086325341182348
Fold 2 IBS: 0.18102224824211316
Fold 3 IBS: 0.1531100591535879
Fold 4 IBS: 0.14724756992252633
Fold 5 IBS: 0.25695477086497476
[I 2024-04-14 00:05:09,374] Trial 30 finished with value: 0.1798395803190051 and parameters: {'l1_ratio': 0.08603677952870634}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.16086325402000562
Fold 2 IBS: 0.1810221005070122
Fold 3 IBS: 0.15311010778198614
Fold 4 IBS: 0.14724766174829546
Fold 5 IBS: 0.256954897539683
[I 2024-04-14 00:05:12,084] Trial 31 finished with value: 0.17983960431939647 and parameters: {'l1_ratio': 0.08604252528991772}. Best is trial 18 with value: 0.17979984651541625.
Fold 1 IBS: 0.1608530056874099
Fold 2 IBS: 0.18079591231430456
Fold 3 IBS: 0.15309787763833801
Fold 4 IBS: 0.1472476738877721
Fold 5 IBS: 0.25694363131962494
[I 2024-04-14 00:05:14,431] Trial 32 finished with value: 0.1797876201694899 and parameters: {'l1_ratio': 0.05413792748818495}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16091624001183497
Fold 2 IBS: 0.18348796718114563
Fold 3 IBS: 0.15316684957468976
Fold 4 IBS: 0.14722738452883383
Fold 5 IBS: 0.25698531631593174
[I 2024-04-14 00:05:17,035] Trial 33 finished with value: 0.18035675152248717 and parameters: {'l1_ratio': 0.2557928465940727}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16089212016192686
Fold 2 IBS: 0.1832740835421089
Fold 3 IBS: 0.1531117990311426
Fold 4 IBS: 0.147185501941785
Fold 5 IBS: 0.2570623739262929
[I 2024-04-14 00:05:19,613] Trial 34 finished with value: 0.18030517572065125 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16102683366827195
Fold 2 IBS: 0.18434586976091333
Fold 3 IBS: 0.153303817163659
Fold 4 IBS: 0.14731911262328792
Fold 5 IBS: 0.25708583963631737
[I 2024-04-14 00:05:21,932] Trial 35 finished with value: 0.18061629457048992 and parameters: {'l1_ratio': 0.6179848099431686}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.1609258084575769
Fold 2 IBS: 0.18359467364550713
Fold 3 IBS: 0.1531431002840603
Fold 4 IBS: 0.14727599312511436
Fold 5 IBS: 0.25705840142483505
[I 2024-04-14 00:05:24,318] Trial 36 finished with value: 0.18039959538741873 and parameters: {'l1_ratio': 0.2901961606553578}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085143051948303
Fold 2 IBS: 0.18089841165638568
Fold 3 IBS: 0.15306437685617763
Fold 4 IBS: 0.2213395628736208
Fold 5 IBS: 0.2570223424853528
[I 2024-04-14 00:05:26,928] Trial 37 finished with value: 0.194635224878204 and parameters: {'l1_ratio': 0.05172410716345872}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16088013336400925
Fold 2 IBS: 0.18289031904499653
Fold 3 IBS: 0.15309145727854387
Fold 4 IBS: 0.14730253109138447
Fold 5 IBS: 0.25703909348571197
[I 2024-04-14 00:05:29,100] Trial 38 finished with value: 0.1802407068529292 and parameters: {'l1_ratio': 0.12979849919200753}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16084696432868278
Fold 2 IBS: 0.1807395960817679
Fold 3 IBS: 0.15308115139472844
Fold 4 IBS: 0.22199380065480395
Fold 5 IBS: 0.2569084036371884
[I 2024-04-14 00:05:31,318] Trial 39 finished with value: 0.1947139832194343 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.1609836191290143
Fold 2 IBS: 0.18398780994349792
Fold 3 IBS: 0.15323148239782464
Fold 4 IBS: 0.14730406617466132
Fold 5 IBS: 0.25716499706561685
[I 2024-04-14 00:05:33,291] Trial 40 finished with value: 0.18053439494212303 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085155995584652
Fold 2 IBS: 0.18087135018059183
Fold 3 IBS: 0.15307321592183695
Fold 4 IBS: 0.22130530272479568
Fold 5 IBS: 0.257043891916421
[I 2024-04-14 00:05:35,933] Trial 41 finished with value: 0.1946290641398984 and parameters: {'l1_ratio': 0.05234350132353384}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.1608733716384612
Fold 2 IBS: 0.18283065039471538
Fold 3 IBS: 0.1530696283513023
Fold 4 IBS: 0.14727331089160875
Fold 5 IBS: 0.256993091286248
[I 2024-04-14 00:05:38,846] Trial 42 finished with value: 0.18020801051246713 and parameters: {'l1_ratio': 0.11570869869888623}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16090091165212805
Fold 2 IBS: 0.18338429043313378
Fold 3 IBS: 0.15314820680664654
Fold 4 IBS: 0.1472536471210217
Fold 5 IBS: 0.25699160597852483
[I 2024-04-14 00:05:41,744] Trial 43 finished with value: 0.18033573239829098 and parameters: {'l1_ratio': 0.19786711653676464}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16107093020731952
Fold 2 IBS: 0.1847000118929276
Fold 3 IBS: 0.15337157021466274
Fold 4 IBS: 0.1472901298923364
Fold 5 IBS: 0.25712246916796416
[I 2024-04-14 00:05:43,900] Trial 44 finished with value: 0.1807110222750421 and parameters: {'l1_ratio': 0.791399986164104}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085123484822655
Fold 2 IBS: 0.18093836481241654
Fold 3 IBS: 0.153051340969712
Fold 4 IBS: 0.2213891421095749
Fold 5 IBS: 0.256990453844088
[I 2024-04-14 00:05:46,553] Trial 45 finished with value: 0.19464410731680357 and parameters: {'l1_ratio': 0.05083189201848518}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16099906480738468
Fold 2 IBS: 0.18414086823201173
Fold 3 IBS: 0.15328013272562196
Fold 4 IBS: 0.1472265128489739
Fold 5 IBS: 0.25709731339782205
[I 2024-04-14 00:05:48,765] Trial 46 finished with value: 0.18054877840236286 and parameters: {'l1_ratio': 0.5296312468775739}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16086964662713868
Fold 2 IBS: 0.18112981623360833
Fold 3 IBS: 0.15311611846710768
Fold 4 IBS: 0.1472587532084859
Fold 5 IBS: 0.25696936060417647
[I 2024-04-14 00:05:51,684] Trial 47 finished with value: 0.17986873902810344 and parameters: {'l1_ratio': 0.10437275082796443}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16089066164120808
Fold 2 IBS: 0.1832955311792642
Fold 3 IBS: 0.15313130632257274
Fold 4 IBS: 0.1472304997156963
Fold 5 IBS: 0.2569592338599152
[I 2024-04-14 00:05:54,023] Trial 48 finished with value: 0.1803014465437313 and parameters: {'l1_ratio': 0.16226501113996325}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16091620916153712
Fold 2 IBS: 0.18347809605058527
Fold 3 IBS: 0.15316201989419964
Fold 4 IBS: 0.14721836904705438
Fold 5 IBS: 0.2569727996126772
[I 2024-04-14 00:05:56,531] Trial 49 finished with value: 0.18034949875321074 and parameters: {'l1_ratio': 0.2541790385622397}. Best is trial 32 with value: 0.1797876201694899.

Fold 1 IBS: 0.16084399217043524
Fold 2 IBS: 0.18084266545097055
Fold 3 IBS: 0.1530380420028172
Fold 4 IBS: 0.2223318863687651
Fold 5 IBS: 0.2569678365850347
[I 2024-04-14 00:05:58,828] Trial 50 finished with value: 0.19480488451560457 and parameters: {'l1_ratio': 0.034744277134253675}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16086029199227134
Fold 2 IBS: 0.1810193377508919
Fold 3 IBS: 0.1530902379382648
Fold 4 IBS: 0.14721559411026014
Fold 5 IBS: 0.2569079967367536
[I 2024-04-14 00:06:01,159] Trial 51 finished with value: 0.17981869170568837 and parameters: {'l1_ratio': 0.07664015002356084}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.21375089513713016
Fold 2 IBS: 0.2212829738184272
Fold 3 IBS: 0.20427598896848173
Fold 4 IBS: 0.22439248930226477
Fold 5 IBS: 0.21805335904331832
[I 2024-04-14 00:06:01,984] Trial 52 finished with value: 0.21635114125392443 and parameters: {'l1_ratio': 0.004509908798268153}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.1608772035420781
Fold 2 IBS: 0.18299014037262074
Fold 3 IBS: 0.15312242323869193
Fold 4 IBS: 0.14724284384451108
Fold 5 IBS: 0.25696198801106185
[I 2024-04-14 00:06:04,409] Trial 53 finished with value: 0.18023891980179277 and parameters: {'l1_ratio': 0.1241210074188008}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085775501164407
Fold 2 IBS: 0.18097942892934654
Fold 3 IBS: 0.15308470578926606
Fold 4 IBS: 0.14721013541763525
Fold 5 IBS: 0.25689801296671033
[I 2024-04-14 00:06:07,006] Trial 54 finished with value: 0.17980600762292046 and parameters: {'l1_ratio': 0.06958666788045736}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16089965203850004
Fold 2 IBS: 0.18339085291092425
Fold 3 IBS: 0.15314596364443703
Fold 4 IBS: 0.14722297368529616
Fold 5 IBS: 0.25696320292365654
[I 2024-04-14 00:06:09,178] Trial 55 finished with value: 0.1803245290405628 and parameters: {'l1_ratio': 0.21222924908780288}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16086027518679025
Fold 2 IBS: 0.18102314735063466
Fold 3 IBS: 0.1530889870378705
Fold 4 IBS: 0.14721322257197744
Fold 5 IBS: 0.25690472307909495
[I 2024-04-14 00:06:11,885] Trial 56 finished with value: 0.17981807104527353 and parameters: {'l1_ratio': 0.07651045478243039}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16084337490455258
Fold 2 IBS: 0.18068041276646393
Fold 3 IBS: 0.15307387168380848
Fold 4 IBS: 0.22260470600740626
Fold 5 IBS: 0.25689576325329044
[I 2024-04-14 00:06:14,235] Trial 57 finished with value: 0.19481962572310435 and parameters: {'l1_ratio': 0.030378487165710136}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16089050010591047
Fold 2 IBS: 0.18326205720220795
Fold 3 IBS: 0.15311545073520055
Fold 4 IBS: 0.14720064178085934
Fold 5 IBS: 0.2569179820488569
[I 2024-04-14 00:06:16,770] Trial 58 finished with value: 0.18027732637460706 and parameters: {'l1_ratio': 0.15887351653337586}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16087339226951833
Fold 2 IBS: 0.18282312031854608
Fold 3 IBS: 0.15307167457699178
Fold 4 IBS: 0.14727573944428274
Fold 5 IBS: 0.256998092463448
[I 2024-04-14 00:06:19,198] Trial 59 finished with value: 0.1802084038145574 and parameters: {'l1_ratio': 0.11601712692446617}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085648370985578
Fold 2 IBS: 0.18102973324446092
Fold 3 IBS: 0.15306799598684137
Fold 4 IBS: 0.14717837278387177
Fold 5 IBS: 0.25702084567767414
[I 2024-04-14 00:06:21,502] Trial 60 finished with value: 0.1798306862805408 and parameters: {'l1_ratio': 0.06804204536431924}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.1608605845814535
Fold 2 IBS: 0.18095187787625874
Fold 3 IBS: 0.15310604158961097
Fold 4 IBS: 0.14725798440208826
Fold 5 IBS: 0.2569593749935163
[I 2024-04-14 00:06:24,248] Trial 61 finished with value: 0.17982717268858556 and parameters: {'l1_ratio': 0.07902678129124668}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16088668054641156
Fold 2 IBS: 0.18318959281415761
Fold 3 IBS: 0.15309142549842583
Fold 4 IBS: 0.14728386960716489
Fold 5 IBS: 0.2570224109144753
[I 2024-04-14 00:06:27,160] Trial 62 finished with value: 0.18029479587612704 and parameters: {'l1_ratio': 0.153950251990069}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.21397059113968203
Fold 2 IBS: 0.2215701647537156
Fold 3 IBS: 0.20452912080766225
Fold 4 IBS: 0.2247289443763843
Fold 5 IBS: 0.21812244166420502
[I 2024-04-14 00:06:28,093] Trial 63 finished with value: 0.21658425254832983 and parameters: {'l1_ratio': 0.00011700932248795426}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.1608696877218078
Fold 2 IBS: 0.18111893220008335
Fold 3 IBS: 0.1531197406137467
Fold 4 IBS: 0.14726552709013443
Fold 5 IBS: 0.2569787350488982
[I 2024-04-14 00:06:30,748] Trial 64 finished with value: 0.17987052453493407 and parameters: {'l1_ratio': 0.10489148116152583}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16084318456670174
Fold 2 IBS: 0.18071737270606777
Fold 3 IBS: 0.15306185170914868
Fold 4 IBS: 0.22263601794068802
Fold 5 IBS: 0.25702990538599474
[I 2024-04-14 00:06:33,270] Trial 65 finished with value: 0.19485766646172017 and parameters: {'l1_ratio': 0.029885179692736165}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16090834008604937
Fold 2 IBS: 0.18340562107672206
Fold 3 IBS: 0.1531401062745257
Fold 4 IBS: 0.1471962640983322
Fold 5 IBS: 0.25693372957178456
[I 2024-04-14 00:06:35,467] Trial 66 finished with value: 0.1803168122214828 and parameters: {'l1_ratio': 0.2283450959509596}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.1609448342624805
Fold 2 IBS: 0.18373849214605897
Fold 3 IBS: 0.15317827761388983
Fold 4 IBS: 0.147294049968955
Fold 5 IBS: 0.2571049623286272
[I 2024-04-14 00:06:37,456] Trial 67 finished with value: 0.1804521232640023 and parameters: {'l1_ratio': 0.35287754160056}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085641526701727
Fold 2 IBS: 0.18104335558400744
Fold 3 IBS: 0.1530635408113755
Fold 4 IBS: 0.14716987441050547
Fold 5 IBS: 0.2570099518515615
[I 2024-04-14 00:06:40,762] Trial 68 finished with value: 0.17982862758489343 and parameters: {'l1_ratio': 0.06763913573941491}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16089479181315905
Fold 2 IBS: 0.1833062079259776
Fold 3 IBS: 0.15311657725054184
Fold 4 IBS: 0.1471817743579814
Fold 5 IBS: 0.2570635145049962
[I 2024-04-14 00:06:44,012] Trial 69 finished with value: 0.18031257317053123 and parameters: {'l1_ratio': 0.18808524100713275}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16102683239914306
Fold 2 IBS: 0.18434834217116258
Fold 3 IBS: 0.1533052140856773
Fold 4 IBS: 0.14732145937817698
Fold 5 IBS: 0.25708939193315056
[I 2024-04-14 00:06:46,151] Trial 70 finished with value: 0.1806182479934621 and parameters: {'l1_ratio': 0.6190167670320361}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16086304343075247
Fold 2 IBS: 0.18107222509639825
Fold 3 IBS: 0.15309361499541113
Fold 4 IBS: 0.14721646856134485
Fold 5 IBS: 0.2569118952139425
[I 2024-04-14 00:06:49,580] Trial 71 finished with value: 0.1798314494595698 and parameters: {'l1_ratio': 0.08412959361156182}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16086645804273528
Fold 2 IBS: 0.181032763078546
Fold 3 IBS: 0.15306443016085816
Fold 4 IBS: 0.14727700690102924
Fold 5 IBS: 0.25699298170509516
[I 2024-04-14 00:06:51,826] Trial 72 finished with value: 0.17984672797765272 and parameters: {'l1_ratio': 0.096521421864628}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16088168228564112
Fold 2 IBS: 0.18308609545717386
Fold 3 IBS: 0.15312699550001788
Fold 4 IBS: 0.1472551460506906
Fold 5 IBS: 0.25697620773438923
[I 2024-04-14 00:06:54,208] Trial 73 finished with value: 0.1802652254055825 and parameters: {'l1_ratio': 0.13734489926238325}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.21267659973360406
Fold 2 IBS: 0.18088137608852625
Fold 3 IBS: 0.1530770287156461
Fold 4 IBS: 0.2227666432373955
Fold 5 IBS: 0.25690581326954953
[I 2024-04-14 00:06:56,159] Trial 74 finished with value: 0.20526149220894427 and parameters: {'l1_ratio': 0.027844067328299624}. Best is trial 32 with value: 0.1797876201694899.

Fold 1 IBS: 0.1608555293405721
Fold 2 IBS: 0.18092429527294762
Fold 3 IBS: 0.15308563284934484
Fold 4 IBS: 0.14721648117820035
Fold 5 IBS: 0.25690449586435554
[I 2024-04-14 00:06:58,614] Trial 75 finished with value: 0.17979728690108412 and parameters: {'l1_ratio': 0.0637151684499458}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085354758420364
Fold 2 IBS: 0.180884481411374
Fold 3 IBS: 0.15308308294772466
Fold 4 IBS: 0.1472158208369685
Fold 5 IBS: 0.2569015546570554
[I 2024-04-14 00:07:01,189] Trial 76 finished with value: 0.17978769748746526 and parameters: {'l1_ratio': 0.05804597688293481}. Best is trial 32 with value: 0.1797876201694899.
Fold 1 IBS: 0.16085503615706354
Fold 2 IBS: 0.18079663162121018
Fold 3 IBS: 0.15304553499855655
Fold 4 IBS: 0.14726910837494794
Fold 5 IBS: 0.256969636149881
[I 2024-04-14 00:07:03,427] Trial 77 finished with value: 0.17978718946033184 and parameters: {'l1_ratio': 0.06039237081117726}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.1608513014597936
Fold 2 IBS: 0.18092488913415272
Fold 3 IBS: 0.1530557388534373
Fold 4 IBS: 0.22137255106408268
Fold 5 IBS: 0.25700121961803085
[I 2024-04-14 00:07:05,401] Trial 78 finished with value: 0.19464114002589944 and parameters: {'l1_ratio': 0.05112991788867725}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16088186865632617
Fold 2 IBS: 0.1830549508241233
Fold 3 IBS: 0.15308949041050726
Fold 4 IBS: 0.14729020034100918
Fold 5 IBS: 0.257026391344937
[I 2024-04-14 00:07:07,740] Trial 79 finished with value: 0.18026858031538057 and parameters: {'l1_ratio': 0.14104602147178058}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16089210168224516
Fold 2 IBS: 0.1832688979897507
Fold 3 IBS: 0.1531092588703663
Fold 4 IBS: 0.1473080363888103
Fold 5 IBS: 0.2570562162196916
[I 2024-04-14 00:07:09,669] Trial 80 finished with value: 0.18032690223017284 and parameters: {'l1_ratio': 0.17140870391302115}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.21293668994413917
Fold 2 IBS: 0.2202231192332579
Fold 3 IBS: 0.20332964227681363
Fold 4 IBS: 0.22315733547643407
Fold 5 IBS: 0.2569684465053398
[I 2024-04-14 00:07:11,190] Trial 81 finished with value: 0.22332304668719694 and parameters: {'l1_ratio': 0.021896682457329737}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16086965432285796
Fold 2 IBS: 0.18112778578337999
Fold 3 IBS: 0.1531167940788615
Fold 4 IBS: 0.14726001704790304
Fold 5 IBS: 0.2569711097618688
[I 2024-04-14 00:07:13,701] Trial 82 finished with value: 0.17986907219897427 and parameters: {'l1_ratio': 0.10446918232349936}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16085314315249788
Fold 2 IBS: 0.18097006370678512
Fold 3 IBS: 0.15305510731797617
Fold 4 IBS: 0.14728993809841245
Fold 5 IBS: 0.2569965403393333
[I 2024-04-14 00:07:16,362] Trial 83 finished with value: 0.179832958523001 and parameters: {'l1_ratio': 0.055904371869240896}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16087581591694738
Fold 2 IBS: 0.18110684665381988
Fold 3 IBS: 0.15309501824814017
Fold 4 IBS: 0.1471910853749994
Fold 5 IBS: 0.2570549703090886
[I 2024-04-14 00:07:18,743] Trial 84 finished with value: 0.17986474730059906 and parameters: {'l1_ratio': 0.1196340107896692}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.2138652371615219
Fold 2 IBS: 0.22143244805930212
Fold 3 IBS: 0.20440781463946886
Fold 4 IBS: 0.22456747033085592
Fold 5 IBS: 0.21808923473629657
[I 2024-04-14 00:07:19,631] Trial 85 finished with value: 0.21647244098548907 and parameters: {'l1_ratio': 0.002209291125851637}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16085541406918866
Fold 2 IBS: 0.18094913256267792
Fold 3 IBS: 0.15307749783839178
Fold 4 IBS: 0.1472010335656507
Fold 5 IBS: 0.25704776437303006
[I 2024-04-14 00:07:21,956] Trial 86 finished with value: 0.1798261684817878 and parameters: {'l1_ratio': 0.06301723971345552}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16084414627813667
Fold 2 IBS: 0.18075968074767942
Fold 3 IBS: 0.15305610866258593
Fold 4 IBS: 0.22247178963615402
Fold 5 IBS: 0.25701408915155605
[I 2024-04-14 00:07:24,316] Trial 87 finished with value: 0.19482916289522242 and parameters: {'l1_ratio': 0.032490188218825156}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16086792269393219
Fold 2 IBS: 0.18101655714140905
Fold 3 IBS: 0.15307012004826906
Fold 4 IBS: 0.14728706835752575
Fold 5 IBS: 0.2570068883808259
[I 2024-04-14 00:07:27,085] Trial 88 finished with value: 0.17984971132439237 and parameters: {'l1_ratio': 0.09724422427494367}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16088169071861091
Fold 2 IBS: 0.18308389180217582
Fold 3 IBS: 0.15312785031508128
Fold 4 IBS: 0.14725674158584237
Fold 5 IBS: 0.25697841799619975
[I 2024-04-14 00:07:29,218] Trial 89 finished with value: 0.18026571848358203 and parameters: {'l1_ratio': 0.1375041516817002}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16088615547950894
Fold 2 IBS: 0.18330573111047485
Fold 3 IBS: 0.15312731515809924
Fold 4 IBS: 0.14721470631658562
Fold 5 IBS: 0.2569385431205661
[I 2024-04-14 00:07:31,265] Trial 90 finished with value: 0.18029449023704694 and parameters: {'l1_ratio': 0.1755300618740318}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.1608563947732407
Fold 2 IBS: 0.18104740995697108
Fold 3 IBS: 0.15306221315698876
Fold 4 IBS: 0.14729447145257735
Fold 5 IBS: 0.25700670755282157
[I 2024-04-14 00:07:33,815] Trial 91 finished with value: 0.17985343937851989 and parameters: {'l1_ratio': 0.0675199916123736}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16086167136638024
Fold 2 IBS: 0.18088504343134648
Fold 3 IBS: 0.1530698307956658
Fold 4 IBS: 0.1471712953146471
Fold 5 IBS: 0.257016633467264
[I 2024-04-14 00:07:36,047] Trial 92 finished with value: 0.17980089487506073 and parameters: {'l1_ratio': 0.08149105691650985}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16084930725432814
Fold 2 IBS: 0.18094664876153232
Fold 3 IBS: 0.15309617436975334
Fold 4 IBS: 0.22169137404294173
Fold 5 IBS: 0.25695521657073306
[I 2024-04-14 00:07:38,015] Trial 93 finished with value: 0.1947077441998577 and parameters: {'l1_ratio': 0.04549643080926877}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16109646469655894
Fold 2 IBS: 0.18492092706652705
Fold 3 IBS: 0.1534507216383344
Fold 4 IBS: 0.14736334421072148
Fold 5 IBS: 0.25726142872315527
[I 2024-04-14 00:07:40,172] Trial 94 finished with value: 0.18081857726705944 and parameters: {'l1_ratio': 0.9094578869039874}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.1608648226500418
Fold 2 IBS: 0.18091290782396877
Fold 3 IBS: 0.15308231336159414
Fold 4 IBS: 0.14718897195032618
Fold 5 IBS: 0.2570420922663936
[I 2024-04-14 00:07:43,207] Trial 95 finished with value: 0.1798182216104649 and parameters: {'l1_ratio': 0.09050974651190381}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.21295085498333105
Fold 2 IBS: 0.22024152328888233
Fold 3 IBS: 0.20334620690833785
Fold 4 IBS: 0.22317866921133953
Fold 5 IBS: 0.2569412223527854
[I 2024-04-14 00:07:44,526] Trial 96 finished with value: 0.2233316953489352 and parameters: {'l1_ratio': 0.021578529074268618}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.1608774799992134
Fold 2 IBS: 0.18290487790800006
Fold 3 IBS: 0.1530854848031123
Fold 4 IBS: 0.14716420578889292
Fold 5 IBS: 0.2570245578166061
[I 2024-04-14 00:07:47,086] Trial 97 finished with value: 0.18021132126316494 and parameters: {'l1_ratio': 0.1287852710472535}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.1608555037452497
Fold 2 IBS: 0.1809298497289702
Fold 3 IBS: 0.15308381329307946
Fold 4 IBS: 0.14721302815559809
Fold 5 IBS: 0.2568997763461262
[I 2024-04-14 00:07:49,526] Trial 98 finished with value: 0.17979639425380473 and parameters: {'l1_ratio': 0.063557960147049}. Best is trial 77 with value: 0.17978718946033184.
Fold 1 IBS: 0.16087164257630604
Fold 2 IBS: 0.1810687940385503
Fold 3 IBS: 0.15307870307061547
Fold 4 IBS: 0.14729551172700897

Fold 5 IBS: 0.25702183130397105
[I 2024-04-14 00:07:51,503] Trial 99 finished with value: 0.17986729654329037 and parameters: {'l1_ratio': 0.10733829561035309}. Best is trial 77 with value: 0.17978718946033184.


* Best trial for IBS:
 FrozenTrial(number=77, state=TrialState.COMPLETE, values=[0.17978718946033184], datetime_start=datetime.datetime(2024, 4, 14, 0, 7, 1, 207555), datetime_complete=datetime.datetime(2024, 4, 14, 0, 7, 3, 426492), params={'l1_ratio': 0.06039237081117726}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=77, value=None)


* Best Score for IBS:
 0.17978718946033184

In [176]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [177]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.761
train_ibs:  0.18

#### Test

In [178]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [179]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.7194970228885845)

test_cindex : 0.577

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.06039237081117726)

test_ibs:  0.269

In [180]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [213]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:48:50,539] A new study created in memory with name: no-name-8879b552-aecf-45dd-9d37-ed2f6d8804ed

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:48:53,950] Trial 0 finished with value: 0.7281518440331286 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7281518440331286.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:48:56,941] Trial 1 finished with value: 0.7457480169493687 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-14 12:48:59,544] Trial 2 finished with value: 0.735155830513213 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:00,550] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:01,904] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7457480169493687.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:49:05,811] Trial 5 finished with value: 0.7472660785898178 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:49:09,599] Trial 6 finished with value: 0.7381544794046891 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:11,600] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6032863849765259
[I 2024-04-14 12:49:17,195] Trial 8 finished with value: 0.5206572769953052 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:49:20,889] Trial 9 finished with value: 0.7451609000218509 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:21,362] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:49:23,100] Trial 11 finished with value: 0.7377757428843917 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6384976525821596
[I 2024-04-14 12:49:28,456] Trial 12 finished with value: 0.7420971969477915 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:49:35,204] Trial 13 finished with value: 0.7365266504825564 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017530569165213797, 'warm_start': False}. Best is trial 5 with value: 0.7472660785898178.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:49:36,041] Trial 14 finished with value: 0.7600266365278019 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.48589405900235655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17488909350671974, 'warm_start': True}. Best is trial 14 with value: 0.7600266365278019.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:36,457] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.3692598016141903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19402726021030228, 'warm_start': True}. Best is trial 14 with value: 0.7600266365278019.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:37,255] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.5327960974085133, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38557060567081813, 'warm_start': True}. Best is trial 14 with value: 0.7600266365278019.
Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:49:37,477] Trial 17 finished with value: 0.7892309398880706 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 10, 'oob_score': True, 'max_samples': 0.4160888955210671, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06727307964156963, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:37,741] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.17503204955528034, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.165096259780819, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:49:38,498] Trial 19 finished with value: 0.7559522827753771 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 125, 'oob_score': True, 'max_samples': 0.41063061032948006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09963343232395264, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:38,687] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.29917214033678546, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24858261413121135, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:49:39,420] Trial 21 finished with value: 0.7650079920053727 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.4202227424087738, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07827117442054096, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:49:39,993] Trial 22 finished with value: 0.7809788776772643 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.41838439074526307, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0666458280631612, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:49:40,507] Trial 23 finished with value: 0.761909393532612 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.3932594208559168, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06762138067737998, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:49:41,549] Trial 24 finished with value: 0.7578548603269246 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.29362935445915617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06066228805580226, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:49:42,095] Trial 25 finished with value: 0.7694514319893504 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 85, 'oob_score': True, 'max_samples': 0.23502644549798718, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00235449332701948, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:42,612] Trial 26 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.21022320161020103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13164567172053532, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:42,771] Trial 27 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.17910991023083944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014724641541276492, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:43,114] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 40, 'oob_score': True, 'max_samples': 0.11183446310324852, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002444034582697069, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:49:44,153] Trial 29 finished with value: 0.7775741604685764 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.34624300666434216, 'max_features': None, 'min_weight_fraction_leaf': 0.04703846961241064, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:49:45,409] Trial 30 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.3359229598579714, 'max_features': None, 'min_weight_fraction_leaf': 0.21535820339738693, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:49:46,338] Trial 31 finished with value: 0.7659152903896449 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.25074023423629904, 'max_features': None, 'min_weight_fraction_leaf': 0.04816721016288783, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.

Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:49:46,830] Trial 32 finished with value: 0.7843718803263862 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.5438109085992663, 'max_features': None, 'min_weight_fraction_leaf': 0.08648554774122166, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:49:47,932] Trial 33 finished with value: 0.7740147548914054 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.544101480226597, 'max_features': None, 'min_weight_fraction_leaf': 0.13964795626206533, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:49:48,567] Trial 34 finished with value: 0.7760559603588271 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 97, 'oob_score': True, 'max_samples': 0.4518556433747414, 'max_features': None, 'min_weight_fraction_leaf': 0.08699466312158283, 'warm_start': True}. Best is trial 17 with value: 0.7892309398880706.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7347417840375586
[I 2024-04-14 12:49:48,982] Trial 35 finished with value: 0.821075806982058 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 33, 'oob_score': True, 'max_samples': 0.5216655889434714, 'max_features': None, 'min_weight_fraction_leaf': 0.044982812395241205, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:49:49,289] Trial 36 finished with value: 0.7722469807506789 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 32, 'oob_score': True, 'max_samples': 0.6700160400996815, 'max_features': None, 'min_weight_fraction_leaf': 0.1426556640974837, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.6784037558685446
[I 2024-04-14 12:49:49,739] Trial 37 finished with value: 0.7873906957959766 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.5830642701570617, 'max_features': None, 'min_weight_fraction_leaf': 0.08356687905505909, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:49:50,230] Trial 38 finished with value: 0.7859622867850847 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.6815535626086774, 'max_features': None, 'min_weight_fraction_leaf': 0.10357596080807438, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:49:50,521] Trial 39 finished with value: 0.7850456909534103 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 28, 'oob_score': True, 'max_samples': 0.7097826087207546, 'max_features': None, 'min_weight_fraction_leaf': 0.11787330832903728, 'warm_start': True}. Best is trial 35 with value: 0.821075806982058.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7723004694835681
[I 2024-04-14 12:49:51,048] Trial 40 finished with value: 0.8256151813632308 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 57, 'oob_score': True, 'max_samples': 0.8420978362663503, 'max_features': None, 'min_weight_fraction_leaf': 0.03739385491872656, 'warm_start': True}. Best is trial 40 with value: 0.8256151813632308.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7535211267605634
[I 2024-04-14 12:49:51,579] Trial 41 finished with value: 0.8215139473997348 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.9990097687431341, 'max_features': None, 'min_weight_fraction_leaf': 0.03835542275521481, 'warm_start': True}. Best is trial 40 with value: 0.8256151813632308.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7676056338028169
[I 2024-04-14 12:49:51,865] Trial 42 finished with value: 0.8317529517114874 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 22, 'oob_score': True, 'max_samples': 0.9854345464574438, 'max_features': None, 'min_weight_fraction_leaf': 0.030065593229884995, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.7790178571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:49:52,128] Trial 43 finished with value: 0.805884737138506 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.9910765017367337, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03822397715359825, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:49:52,526] Trial 44 finished with value: 0.8074873596823615 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 35, 'oob_score': True, 'max_samples': 0.9674422854509271, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03099581273343698, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:49:53,055] Trial 45 finished with value: 0.8110918415567981 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8546485810385884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.035451817405702565, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.625
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:49:54,655] Trial 46 finished with value: 0.7428514327009917 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.8685366583806222, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027234676496553298, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.

Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.744131455399061
[I 2024-04-14 12:49:55,110] Trial 47 finished with value: 0.8171341032725834 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.8684089446104679, 'max_features': None, 'min_weight_fraction_leaf': 0.04618465431156833, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6173708920187794
[I 2024-04-14 12:49:56,109] Trial 48 finished with value: 0.7458915026407004 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9166675132024303, 'max_features': None, 'min_weight_fraction_leaf': 0.39782702169399947, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:49:56,510] Trial 49 finished with value: 0.8202536040834915 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.7878171540040061, 'max_features': None, 'min_weight_fraction_leaf': 0.0009009708504232813, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:49:57,571] Trial 50 finished with value: 0.8181130647691741 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 356, 'oob_score': False, 'max_samples': 0.7899706436285319, 'max_features': None, 'min_weight_fraction_leaf': 0.006710204917764943, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:49:58,766] Trial 51 finished with value: 0.8172806863632663 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.7750707159461326, 'max_features': None, 'min_weight_fraction_leaf': 0.0008710587792558205, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 12:49:59,939] Trial 52 finished with value: 0.82066790309537 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 417, 'oob_score': False, 'max_samples': 0.8281135464935815, 'max_features': None, 'min_weight_fraction_leaf': 0.021483356033540256, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7605633802816901
[I 2024-04-14 12:50:00,906] Trial 53 finished with value: 0.8217024078063453 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.8291152952323888, 'max_features': None, 'min_weight_fraction_leaf': 0.031921658073411095, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:50:02,060] Trial 54 finished with value: 0.8274713535392276 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.9443966405068337, 'max_features': None, 'min_weight_fraction_leaf': 0.02588019976858258, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-14 12:50:03,258] Trial 55 finished with value: 0.8304447235546677 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.9461860404965909, 'max_features': None, 'min_weight_fraction_leaf': 0.05336607321645103, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6272321428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 12:50:07,847] Trial 56 finished with value: 0.7294502275334355 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.9504771378964706, 'max_features': None, 'min_weight_fraction_leaf': 0.29669443075161894, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:50:09,249] Trial 57 finished with value: 0.8221036118218825 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9974125372324327, 'max_features': None, 'min_weight_fraction_leaf': 0.06517220061887827, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:50:10,236] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.9056124925654404, 'max_features': None, 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:50:11,582] Trial 59 finished with value: 0.8199567511570018 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 325, 'oob_score': False, 'max_samples': 0.9347501839505428, 'max_features': None, 'min_weight_fraction_leaf': 0.06560214874955103, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.5892857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:50:15,660] Trial 60 finished with value: 0.730423526969257 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.8874254435807117, 'max_features': None, 'min_weight_fraction_leaf': 0.1189877126682585, 'warm_start': False}. Best is trial 42 with value: 0.8317529517114874.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:50:17,227] Trial 61 finished with value: 0.8202057192429153 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9834494437668313, 'max_features': None, 'min_weight_fraction_leaf': 0.0573547525154411, 'warm_start': True}. Best is trial 42 with value: 0.8317529517114874.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:50:19,629] Trial 62 finished with value: 0.8326345559536964 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 339, 'oob_score': False, 'max_samples': 0.8272875133535434, 'max_features': None, 'min_weight_fraction_leaf': 0.021834423884142258, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 12:50:21,476] Trial 63 finished with value: 0.8122955024081626 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.8329452765420907, 'max_features': None, 'min_weight_fraction_leaf': 0.07497271601770447, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 12:50:23,115] Trial 64 finished with value: 0.8093918874378062 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9368894740163626, 'max_features': None, 'min_weight_fraction_leaf': 0.09351386622613925, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:50:25,174] Trial 65 finished with value: 0.8326190031272723 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.7454841889145698, 'max_features': None, 'min_weight_fraction_leaf': 0.022536083830532825, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:50:27,461] Trial 66 finished with value: 0.8313609053971838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.7230484371829358, 'max_features': None, 'min_weight_fraction_leaf': 0.021500018947879146, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:50:30,281] Trial 67 finished with value: 0.8305170235406436 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.7393599850936642, 'max_features': None, 'min_weight_fraction_leaf': 0.024147535010390957, 'warm_start': True}. Best is trial 62 with value: 0.8326345559536964.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7981220657276995
[I 2024-04-14 12:50:32,346] Trial 68 finished with value: 0.8452762458003509 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.7427007695988085, 'max_features': None, 'min_weight_fraction_leaf': 0.01779057408953172, 'warm_start': True}. Best is trial 68 with value: 0.8452762458003509.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:50:34,891] Trial 69 finished with value: 0.8496835536675003 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.7457884481689102, 'max_features': None, 'min_weight_fraction_leaf': 0.017318131927655057, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:50:36,940] Trial 70 finished with value: 0.8434202305373113 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.7347919547095044, 'max_features': None, 'min_weight_fraction_leaf': 0.020651216069239264, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:50:38,595] Trial 71 finished with value: 0.84883967181096 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 218, 'oob_score': False, 'max_samples': 0.7354619515845321, 'max_features': None, 'min_weight_fraction_leaf': 0.016803980885547094, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:50:39,886] Trial 72 finished with value: 0.8378948361302088 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.6304929288353576, 'max_features': None, 'min_weight_fraction_leaf': 0.013738560806839913, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:50:41,256] Trial 73 finished with value: 0.8383957655656632 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.6195015886070395, 'max_features': None, 'min_weight_fraction_leaf': 0.01505981838898209, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:50:42,258] Trial 74 finished with value: 0.8448087388247897 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.6199378596508701, 'max_features': None, 'min_weight_fraction_leaf': 0.008813491940142528, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:50:43,162] Trial 75 finished with value: 0.8284271407228996 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.6422952688306902, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.007943385677349297, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:50:44,569] Trial 76 finished with value: 0.8356249741505056 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.6150026911684802, 'max_features': None, 'min_weight_fraction_leaf': 0.012082946593644771, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:50:45,576] Trial 77 finished with value: 0.7599705217019304 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.5914589089574711, 'max_features': None, 'min_weight_fraction_leaf': 0.014685184397003228, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 12:50:47,019] Trial 78 finished with value: 0.8202670577380209 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 197, 'oob_score': False, 'max_samples': 0.6274066209011758, 'max_features': None, 'min_weight_fraction_leaf': 0.05381552916573561, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:50:48,125] Trial 79 finished with value: 0.8478741006929684 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.6820548566666732, 'max_features': None, 'min_weight_fraction_leaf': 0.00967942569015243, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.5848214285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6338028169014085
[I 2024-04-14 12:50:50,648] Trial 80 finished with value: 0.7303866484518248 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 177, 'oob_score': False, 'max_samples': 0.6775857540438628, 'max_features': None, 'min_weight_fraction_leaf': 0.0773231750938129, 'warm_start': False}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7934272300469484
[I 2024-04-14 12:50:51,548] Trial 81 finished with value: 0.8451760232529454 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.705654254937387, 'max_features': None, 'min_weight_fraction_leaf': 0.011423196772596417, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:50:52,523] Trial 82 finished with value: 0.8266529747200911 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 234, 'oob_score': False, 'max_samples': 0.7024106575493354, 'max_features': None, 'min_weight_fraction_leaf': 0.04609671450162135, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:50:53,257] Trial 83 finished with value: 0.8154772752469601 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 206, 'oob_score': False, 'max_samples': 0.5734722599298255, 'max_features': None, 'min_weight_fraction_leaf': 0.010125018270759366, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:50:54,000] Trial 84 finished with value: 0.8432058689940586 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.666309775124175, 'max_features': None, 'min_weight_fraction_leaf': 0.0026218583854184007, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:50:54,694] Trial 85 finished with value: 0.8470031625593721 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.6635405881192851, 'max_features': None, 'min_weight_fraction_leaf': 0.002344826629627635, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 12:50:55,406] Trial 86 finished with value: 0.8065029590095005 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.6526270280183535, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0020177600275221325, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:50:56,173] Trial 87 finished with value: 0.8139120605534877 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 170, 'oob_score': False, 'max_samples': 0.6930812988503632, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04046611420841914, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:50:56,793] Trial 88 finished with value: 0.8140807643986621 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.6570670022833975, 'max_features': None, 'min_weight_fraction_leaf': 0.05499149836556118, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:50:57,485] Trial 89 finished with value: 0.8416349685468119 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 189, 'oob_score': False, 'max_samples': 0.740597932752879, 'max_features': None, 'min_weight_fraction_leaf': 0.0346978319197411, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:50:58,354] Trial 90 finished with value: 0.7686498625771644 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.7290242468037214, 'max_features': None, 'min_weight_fraction_leaf': 0.2513921457170648, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.812206572769953
[I 2024-04-14 12:50:58,976] Trial 91 finished with value: 0.8486473677462687 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 184, 'oob_score': False, 'max_samples': 0.7549021412312438, 'max_features': None, 'min_weight_fraction_leaf': 0.0003353156461928454, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:50:59,919] Trial 92 finished with value: 0.843258483639489 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.7744489279015901, 'max_features': None, 'min_weight_fraction_leaf': 0.003312926413915166, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:51:01,087] Trial 93 finished with value: 0.8321012919503528 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 261, 'oob_score': False, 'max_samples': 0.7645840199325343, 'max_features': None, 'min_weight_fraction_leaf': 0.041343328705331334, 'warm_start': True}. Best is trial 69 with value: 0.8496835536675003.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8028169014084507
[I 2024-04-14 12:51:02,079] Trial 94 finished with value: 0.855232407271082 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.7127178148051858, 'max_features': None, 'min_weight_fraction_leaf': 0.01586498778855871, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-14 12:51:03,847] Trial 95 finished with value: 0.8416834915379139 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.8079013616638635, 'max_features': None, 'min_weight_fraction_leaf': 0.031762515929408985, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6643192488262911
[I 2024-04-14 12:51:04,378] Trial 96 finished with value: 0.7758217737288599 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 137, 'oob_score': False, 'max_samples': 0.6909885888874797, 'max_features': None, 'min_weight_fraction_leaf': 0.18731988166300653, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:51:05,227] Trial 97 finished with value: 0.8433268264679574 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.7159257509447517, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017328506018913566, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:51:06,013] Trial 98 finished with value: 0.8151855700869628 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 161, 'oob_score': False, 'max_samples': 0.760284301272186, 'max_features': None, 'min_weight_fraction_leaf': 0.07012484642850524, 'warm_start': True}. Best is trial 94 with value: 0.855232407271082.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6116071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8227848101265823

[I 2024-04-14 12:51:09,241] A new study created in memory with name: no-name-29e1fe25-cb2e-4650-afff-f877ea450706

Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:51:09,223] Trial 99 finished with value: 0.7345071219868683 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.7955506870578684, 'max_features': None, 'min_weight_fraction_leaf': 0.05139875752922479, 'warm_start': False}. Best is trial 94 with value: 0.855232407271082.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.855232407271082], datetime_start=datetime.datetime(2024, 4, 14, 12, 51, 1, 93374), datetime_complete=datetime.datetime(2024, 4, 14, 12, 51, 2, 78416), params={'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.7127178148051858, 'max_features': None, 'min_weight_fraction_leaf': 0.01586498778855871, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=94, value=None)


* Best Score for C-index:
 0.855232407271082

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16880360625985416
Fold 2 IBS: 0.24732433151635422
Fold 3 IBS: 0.1659072118315618
Fold 4 IBS: 0.1568116644950886
Fold 5 IBS: 0.23807687059812613
[I 2024-04-14 12:51:13,776] Trial 0 finished with value: 0.19538473694019698 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19538473694019698.
Fold 1 IBS: 0.16543513322609077
Fold 2 IBS: 0.20977957358344046
Fold 3 IBS: 0.1706303561657185
Fold 4 IBS: 0.16172607637443032
Fold 5 IBS: 0.22765702732918122
[I 2024-04-14 12:51:15,002] Trial 1 finished with value: 0.18704563333577223 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-14 12:51:16,038] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-14 12:51:19,693] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-14 12:51:23,194] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.18704563333577223.
Fold 1 IBS: 0.15631707214386673
Fold 2 IBS: 0.2242742311664943
Fold 3 IBS: 0.16295157476672437
Fold 4 IBS: 0.14718772732955032
Fold 5 IBS: 0.2319828116610088
[I 2024-04-14 12:51:30,218] Trial 5 finished with value: 0.18454268341352892 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17185590557761352
Fold 2 IBS: 0.20103465197964324
Fold 3 IBS: 0.16459803471117013
Fold 4 IBS: 0.16143456485788238
Fold 5 IBS: 0.22772639076003676
[I 2024-04-14 12:51:34,487] Trial 6 finished with value: 0.1853299095772692 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.20761917964024726
Fold 2 IBS: 0.215551580537287
Fold 3 IBS: 0.19929872434455675
Fold 4 IBS: 0.2165802601490779
Fold 5 IBS: 0.21629941564703706
[I 2024-04-14 12:51:39,259] Trial 7 finished with value: 0.21106983206364122 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-14 12:51:46,839] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.1657342642026369
Fold 2 IBS: 0.2117847519725899
Fold 3 IBS: 0.17386517217632436
Fold 4 IBS: 0.1656320690177135
Fold 5 IBS: 0.22808746599083526
[I 2024-04-14 12:51:48,707] Trial 9 finished with value: 0.18902074467201999 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-14 12:51:56,985] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.16834827701348198
Fold 2 IBS: 0.2105625570851029
Fold 3 IBS: 0.17143938900361566
Fold 4 IBS: 0.16649569203235007
Fold 5 IBS: 0.22507759132080626
[I 2024-04-14 12:52:01,478] Trial 11 finished with value: 0.18838470129107138 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17137590171088243
Fold 2 IBS: 0.20079034220960656
Fold 3 IBS: 0.16417736688832213
Fold 4 IBS: 0.16117081707433228
Fold 5 IBS: 0.22799428371541863
[I 2024-04-14 12:52:05,990] Trial 12 finished with value: 0.18510174231971238 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.1607651825958809
Fold 2 IBS: 0.22174579782307546
Fold 3 IBS: 0.1649550027841188
Fold 4 IBS: 0.1531991644518084
Fold 5 IBS: 0.23307239842144356
[I 2024-04-14 12:52:09,100] Trial 13 finished with value: 0.18674750921526542 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.16690971688810288
Fold 2 IBS: 0.26006508023076974
Fold 3 IBS: 0.15642059173639022
Fold 4 IBS: 0.1435033675526236
Fold 5 IBS: 0.23748928499217753
[I 2024-04-14 12:52:15,655] Trial 14 finished with value: 0.19287760828001282 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.8286563887351183, 'max_features': None, 'min_weight_fraction_leaf': 0.09422981531813096}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17020016973897817
Fold 2 IBS: 0.21806226199654052
Fold 3 IBS: 0.1717651716228649
Fold 4 IBS: 0.1653338076108178
Fold 5 IBS: 0.22984629902145176
[I 2024-04-14 12:52:23,695] Trial 15 finished with value: 0.19104154199813062 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.6817544899569143, 'max_features': 'auto', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 5 with value: 0.18454268341352892.

Fold 1 IBS: 0.16429944092453677
Fold 2 IBS: 0.21977053735105737
Fold 3 IBS: 0.17110337054121788
Fold 4 IBS: 0.16302411703282363
Fold 5 IBS: 0.22782986562873245
[I 2024-04-14 12:52:30,324] Trial 16 finished with value: 0.1892054662956736 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24786833673530304}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.2140210250926074
Fold 2 IBS: 0.22165374242688704
Fold 3 IBS: 0.20482992077952775
Fold 4 IBS: 0.2248506856151436
Fold 5 IBS: 0.21866286292181575
[I 2024-04-14 12:52:33,750] Trial 17 finished with value: 0.2168036473671963 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3527363076520275}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.21398207456199575
Fold 2 IBS: 0.2210878885925555
Fold 3 IBS: 0.20500084248625938
Fold 4 IBS: 0.22467759051518113
Fold 5 IBS: 0.21837641563069746
[I 2024-04-14 12:52:40,221] Trial 18 finished with value: 0.21662496235733783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.16753738713947874
Fold 2 IBS: 0.26234248514438036
Fold 3 IBS: 0.16650041026644735
Fold 4 IBS: 0.14521562457631151
Fold 5 IBS: 0.23833905713496578
[I 2024-04-14 12:52:40,623] Trial 19 finished with value: 0.19598699285231674 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.7744054221786105, 'max_features': None, 'min_weight_fraction_leaf': 0.15294426956488405}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.2140058010941674
Fold 2 IBS: 0.22070271305097472
Fold 3 IBS: 0.20512571269324692
Fold 4 IBS: 0.2244581340346379
Fold 5 IBS: 0.2175740773836072
[I 2024-04-14 12:52:43,345] Trial 20 finished with value: 0.21637328765132682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': None, 'min_weight_fraction_leaf': 0.3111340864325056}. Best is trial 5 with value: 0.18454268341352892.
Fold 1 IBS: 0.17010203492581122
Fold 2 IBS: 0.19545931456517315
Fold 3 IBS: 0.16505420285841496
Fold 4 IBS: 0.162036366008543
Fold 5 IBS: 0.22560745868664608
[I 2024-04-14 12:52:47,134] Trial 21 finished with value: 0.1836518754089177 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8774254573678859, 'max_features': None, 'min_weight_fraction_leaf': 0.38285115003898385}. Best is trial 21 with value: 0.1836518754089177.
Fold 1 IBS: 0.16858975944081775
Fold 2 IBS: 0.1887959819871508
Fold 3 IBS: 0.16607588423226846
Fold 4 IBS: 0.16617493745455414
Fold 5 IBS: 0.22880387054646664
[I 2024-04-14 12:52:51,920] Trial 22 finished with value: 0.18368808673225157 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8533162629857436, 'max_features': None, 'min_weight_fraction_leaf': 0.39473610054688535}. Best is trial 21 with value: 0.1836518754089177.
Fold 1 IBS: 0.16993490334905023
Fold 2 IBS: 0.18743907860924672
Fold 3 IBS: 0.16537727963411333
Fold 4 IBS: 0.16398158190840675
Fold 5 IBS: 0.22610918708699476
[I 2024-04-14 12:52:56,816] Trial 23 finished with value: 0.18256840611756237 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1691974301015811
Fold 2 IBS: 0.18763591528579984
Fold 3 IBS: 0.16630590486501148
Fold 4 IBS: 0.1648688267770149
Fold 5 IBS: 0.22705580400526276
[I 2024-04-14 12:53:02,550] Trial 24 finished with value: 0.183012776206934 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.911762237036045, 'max_features': None, 'min_weight_fraction_leaf': 0.4145963396824019}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17458509293896438
Fold 2 IBS: 0.18732389614959596
Fold 3 IBS: 0.1720385595590766
Fold 4 IBS: 0.17206638184046272
Fold 5 IBS: 0.23627026792126057
[I 2024-04-14 12:53:07,335] Trial 25 finished with value: 0.18845683968187205 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9270259482202138, 'max_features': None, 'min_weight_fraction_leaf': 0.44717127940994156}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1715342983017772
Fold 2 IBS: 0.20056722047631442
Fold 3 IBS: 0.16491283245976326
Fold 4 IBS: 0.1620343465169812
Fold 5 IBS: 0.22647312176686948
[I 2024-04-14 12:53:13,395] Trial 26 finished with value: 0.18510436390434112 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9129740059593043, 'max_features': None, 'min_weight_fraction_leaf': 0.3870919920523195}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1699990733958502
Fold 2 IBS: 0.18557893849483392
Fold 3 IBS: 0.16633066996451829
Fold 4 IBS: 0.16502841596463963
Fold 5 IBS: 0.22683004436910625
[I 2024-04-14 12:53:17,206] Trial 27 finished with value: 0.18275342843778963 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9882040097907008, 'max_features': None, 'min_weight_fraction_leaf': 0.45340256450947913}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17016221643396637
Fold 2 IBS: 0.18540296557411892
Fold 3 IBS: 0.16710214191696457
Fold 4 IBS: 0.16678323591071748
Fold 5 IBS: 0.22789974639547422
[I 2024-04-14 12:53:22,193] Trial 28 finished with value: 0.18347006124624832 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9741542767559068, 'max_features': None, 'min_weight_fraction_leaf': 0.450638299943646}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.213981238234591
Fold 2 IBS: 0.22129600200231184
Fold 3 IBS: 0.20476687908413987
Fold 4 IBS: 0.22462916295400534
Fold 5 IBS: 0.21851703166023365
[I 2024-04-14 12:53:25,804] Trial 29 finished with value: 0.21663806278705633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.773357424692515, 'max_features': None, 'min_weight_fraction_leaf': 0.4837438075147879}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1737873785599842
Fold 2 IBS: 0.19753704149828014
Fold 3 IBS: 0.16474278602254563
Fold 4 IBS: 0.16243873156676453
Fold 5 IBS: 0.22660859518105705
[I 2024-04-14 12:53:30,357] Trial 30 finished with value: 0.1850229065657263 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 377, 'oob_score': False, 'max_samples': 0.9986438777088522, 'max_features': None, 'min_weight_fraction_leaf': 0.42773069772809913}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17751338669623418
Fold 2 IBS: 0.18856087241291536
Fold 3 IBS: 0.17527262906800933
Fold 4 IBS: 0.17490246385178213
Fold 5 IBS: 0.23490629026498758
[I 2024-04-14 12:53:35,133] Trial 31 finished with value: 0.1902311284587857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.939658841329532, 'max_features': None, 'min_weight_fraction_leaf': 0.4524256463348925}. Best is trial 23 with value: 0.18256840611756237.

Fold 1 IBS: 0.21398563901141657
Fold 2 IBS: 0.22134596740550985
Fold 3 IBS: 0.2048025990579434
Fold 4 IBS: 0.22461415055237854
Fold 5 IBS: 0.21851803782809134
[I 2024-04-14 12:53:39,400] Trial 32 finished with value: 0.21665327877106794 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.7396444271446992, 'max_features': None, 'min_weight_fraction_leaf': 0.4501495537267681}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1881712152839018
Fold 2 IBS: 0.19602908273271186
Fold 3 IBS: 0.187050921824735
Fold 4 IBS: 0.18923643256610323
Fold 5 IBS: 0.21856358775020004
[I 2024-04-14 12:53:43,871] Trial 33 finished with value: 0.19581024803153038 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.9933327757837453, 'max_features': None, 'min_weight_fraction_leaf': 0.49338351231891625}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397810999123087
Fold 2 IBS: 0.22130875696604183
Fold 3 IBS: 0.2047621585928816
Fold 4 IBS: 0.2246288907097577
Fold 5 IBS: 0.21863208708031015
[I 2024-04-14 12:53:47,815] Trial 34 finished with value: 0.21666200066804442 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8938554646810188, 'max_features': None, 'min_weight_fraction_leaf': 0.45754449369723726}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397501954215553
Fold 2 IBS: 0.22130442891193944
Fold 3 IBS: 0.20482836466241144
Fold 4 IBS: 0.22464430529398755
Fold 5 IBS: 0.2263366391256349
[I 2024-04-14 12:53:52,162] Trial 35 finished with value: 0.21821775150722575 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.8179898225635556, 'max_features': None, 'min_weight_fraction_leaf': 0.406528295392146}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1704043619824355
Fold 2 IBS: 0.1996769947732447
Fold 3 IBS: 0.17293358110279214
Fold 4 IBS: 0.17522810502150687
Fold 5 IBS: 0.22035983910919235
[I 2024-04-14 12:53:56,484] Trial 36 finished with value: 0.1877205763978343 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9504880220263004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3678752707538403}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21398603848843456
Fold 2 IBS: 0.2212516593844012
Fold 3 IBS: 0.20480476599516775
Fold 4 IBS: 0.22467106118379263
Fold 5 IBS: 0.2186056754258949
[I 2024-04-14 12:53:59,984] Trial 37 finished with value: 0.2166638400955382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.6134779412492984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42910258289196446}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16894666579605158
Fold 2 IBS: 0.19374351857626196
Fold 3 IBS: 0.16515102637277138
Fold 4 IBS: 0.16283706893147565
Fold 5 IBS: 0.22711044098051275
[I 2024-04-14 12:54:02,953] Trial 38 finished with value: 0.18355774413141468 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.7324083825350811, 'max_features': None, 'min_weight_fraction_leaf': 0.3267902150060746}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.171282531867511
Fold 2 IBS: 0.25508848652905003
Fold 3 IBS: 0.1669250836383552
Fold 4 IBS: 0.15770675719213736
Fold 5 IBS: 0.23678921646135723
[I 2024-04-14 12:54:07,475] Trial 39 finished with value: 0.19755841513768216 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.8998447540408812, 'max_features': None, 'min_weight_fraction_leaf': 0.26335636534084506}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.2139718451769373
Fold 2 IBS: 0.22132290174406308
Fold 3 IBS: 0.2049379534123754
Fold 4 IBS: 0.2246651821236489
Fold 5 IBS: 0.21845691499847839
[I 2024-04-14 12:54:10,935] Trial 40 finished with value: 0.21667095949110057 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.5051356852082238, 'max_features': None, 'min_weight_fraction_leaf': 0.46950692236254693}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1721962878712996
Fold 2 IBS: 0.1867998174317839
Fold 3 IBS: 0.17047364354936667
Fold 4 IBS: 0.16869178324374284
Fold 5 IBS: 0.23042464053354605
[I 2024-04-14 12:54:14,014] Trial 41 finished with value: 0.1857172345259478 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 328, 'oob_score': False, 'max_samples': 0.6950314186231272, 'max_features': None, 'min_weight_fraction_leaf': 0.3301730431422}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21398443372975648
Fold 2 IBS: 0.22133306215617224
Fold 3 IBS: 0.20478162661751423
Fold 4 IBS: 0.224616165333405
Fold 5 IBS: 0.21859375419206165
[I 2024-04-14 12:54:17,866] Trial 42 finished with value: 0.21666180840578192 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 432, 'oob_score': False, 'max_samples': 0.7359525705085804, 'max_features': None, 'min_weight_fraction_leaf': 0.4248133739979326}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1736208583095885
Fold 2 IBS: 0.2142799695808254
Fold 3 IBS: 0.16557686291518559
Fold 4 IBS: 0.16205491926644927
Fold 5 IBS: 0.22950893731135472
[I 2024-04-14 12:54:21,891] Trial 43 finished with value: 0.18900830947668068 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9424025262276309, 'max_features': None, 'min_weight_fraction_leaf': 0.3723018188063154}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17220312279887087
Fold 2 IBS: 0.18725195811040996
Fold 3 IBS: 0.1692113254426714
Fold 4 IBS: 0.16961224398342983
Fold 5 IBS: 0.22996231906173675
[I 2024-04-14 12:54:26,397] Trial 44 finished with value: 0.18564819387942375 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.86762300263298, 'max_features': None, 'min_weight_fraction_leaf': 0.4072940485682038}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17353029619868152
Fold 2 IBS: 0.1960823439514855
Fold 3 IBS: 0.17508121734079327
Fold 4 IBS: 0.17794858732068533
Fold 5 IBS: 0.2191881303895723
[I 2024-04-14 12:54:30,032] Trial 45 finished with value: 0.1883661150402436 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.8045246379242162, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32901914427946066}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.1641095642199566
Fold 2 IBS: 0.22265946803961062
Fold 3 IBS: 0.16903299137029618
Fold 4 IBS: 0.15824030170824924
Fold 5 IBS: 0.22928987086599778
[I 2024-04-14 12:54:33,878] Trial 46 finished with value: 0.18866643924082208 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 363, 'oob_score': False, 'max_samples': 0.9607559032696665, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.211303506589669}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17189303802131756
Fold 2 IBS: 0.24494738775532268
Fold 3 IBS: 0.1666602138983221
Fold 4 IBS: 0.15996661850151628
Fold 5 IBS: 0.23743154462367178
[I 2024-04-14 12:54:37,064] Trial 47 finished with value: 0.1961797605600301 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.876896242953909, 'max_features': None, 'min_weight_fraction_leaf': 0.2817538668731424}. Best is trial 23 with value: 0.18256840611756237.

Fold 1 IBS: 0.1705674173139149
Fold 2 IBS: 0.1852617720416809
Fold 3 IBS: 0.16929920721077502
Fold 4 IBS: 0.16857228614310335
Fold 5 IBS: 0.23285081643644664
[I 2024-04-14 12:54:41,330] Trial 48 finished with value: 0.18531029982918418 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.9996528707471266, 'max_features': None, 'min_weight_fraction_leaf': 0.47380170342998185}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397420828984268
Fold 2 IBS: 0.22140730914697682
Fold 3 IBS: 0.2048165899556378
Fold 4 IBS: 0.22466454285026752
Fold 5 IBS: 0.2185528446348627
[I 2024-04-14 12:54:44,248] Trial 49 finished with value: 0.21668309897551746 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8459565404966409, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4242257306364142}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16902430601502333
Fold 2 IBS: 0.19338265075792843
Fold 3 IBS: 0.16486539224344463
Fold 4 IBS: 0.16147203223041565
Fold 5 IBS: 0.22765220951812717
[I 2024-04-14 12:54:47,834] Trial 50 finished with value: 0.18327931815298784 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.7982382644517961, 'max_features': None, 'min_weight_fraction_leaf': 0.35750036696317244}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16859461221748046
Fold 2 IBS: 0.19038638924084872
Fold 3 IBS: 0.16553825872694258
Fold 4 IBS: 0.16353660023264655
Fold 5 IBS: 0.22807647271719378
[I 2024-04-14 12:54:51,796] Trial 51 finished with value: 0.1832264666270224 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.8005649206872336, 'max_features': None, 'min_weight_fraction_leaf': 0.36691532058452314}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.17293958401347873
Fold 2 IBS: 0.2192681783178068
Fold 3 IBS: 0.1659565471985156
Fold 4 IBS: 0.16202566536404225
Fold 5 IBS: 0.23130480410736612
[I 2024-04-14 12:54:56,526] Trial 52 finished with value: 0.1902989558002419 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9178460283734129, 'max_features': None, 'min_weight_fraction_leaf': 0.3557818682293127}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.21397828800315355
Fold 2 IBS: 0.2213044801251445
Fold 3 IBS: 0.20478578064864883
Fold 4 IBS: 0.2246281820625841
Fold 5 IBS: 0.2186066093064182
[I 2024-04-14 12:55:00,065] Trial 53 finished with value: 0.21666066802918982 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.8082070646632502, 'max_features': None, 'min_weight_fraction_leaf': 0.4060864243885318}. Best is trial 23 with value: 0.18256840611756237.
Fold 1 IBS: 0.16929857607063142
Fold 2 IBS: 0.1855709592705922
Fold 3 IBS: 0.16590078913270798
Fold 4 IBS: 0.1644087579365555
Fold 5 IBS: 0.22603924109858942
[I 2024-04-14 12:55:03,847] Trial 54 finished with value: 0.1822436647018153 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.9565029369785671, 'max_features': None, 'min_weight_fraction_leaf': 0.43699319744655357}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2029441241859812
Fold 2 IBS: 0.20884651281655017
Fold 3 IBS: 0.19540591699611048
Fold 4 IBS: 0.2068895040199807
Fold 5 IBS: 0.218505374625429
[I 2024-04-14 12:55:07,049] Trial 55 finished with value: 0.20651828652881035 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.7759180607351711, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3850162625050211}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17387417382717657
Fold 2 IBS: 0.1967912473931568
Fold 3 IBS: 0.1754869137337466
Fold 4 IBS: 0.18059787836339708
Fold 5 IBS: 0.21820683103881933
[I 2024-04-14 12:55:10,897] Trial 56 finished with value: 0.18899140887125926 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 428, 'oob_score': False, 'max_samples': 0.8899843079416504, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.36599094159376067}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2139799225651981
Fold 2 IBS: 0.22127927639217232
Fold 3 IBS: 0.20485144900872682
Fold 4 IBS: 0.2246460458464435
Fold 5 IBS: 0.21852930609789148
[I 2024-04-14 12:55:14,365] Trial 57 finished with value: 0.2166571999820864 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.576438276587755, 'max_features': None, 'min_weight_fraction_leaf': 0.43635893837546796}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17480240560632257
Fold 2 IBS: 0.19615522167799648
Fold 3 IBS: 0.1763934683738566
Fold 4 IBS: 0.18169915729415803
Fold 5 IBS: 0.21709493251231066
[I 2024-04-14 12:55:19,116] Trial 58 finished with value: 0.18922903709292888 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9532859852286428, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.39848192471528204}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21397578197228534
Fold 2 IBS: 0.22105121992448867
Fold 3 IBS: 0.20474712700666953
Fold 4 IBS: 0.22460210382536355
Fold 5 IBS: 0.21846630950749174
[I 2024-04-14 12:55:19,992] Trial 59 finished with value: 0.21656850844725978 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.8354470540495106, 'max_features': None, 'min_weight_fraction_leaf': 0.4712438108607243}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1726127601700496
Fold 2 IBS: 0.23213992452417942
Fold 3 IBS: 0.16625971951919333
Fold 4 IBS: 0.16169924600658186
Fold 5 IBS: 0.23296316972000924
[I 2024-04-14 12:55:24,519] Trial 60 finished with value: 0.19313496398800267 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.918505174941936, 'max_features': None, 'min_weight_fraction_leaf': 0.34083396149253076}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17115985783827192
Fold 2 IBS: 0.18669540101486526
Fold 3 IBS: 0.1690037370937305
Fold 4 IBS: 0.16774797187785795
Fold 5 IBS: 0.2290404472831437
[I 2024-04-14 12:55:28,934] Trial 61 finished with value: 0.18472948302157385 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.9476308520028045, 'max_features': None, 'min_weight_fraction_leaf': 0.44612613879924584}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21397833720638162
Fold 2 IBS: 0.22133523964491808
Fold 3 IBS: 0.20478229195041203
Fold 4 IBS: 0.2246079755345025
Fold 5 IBS: 0.2186167177505955
[I 2024-04-14 12:55:33,775] Trial 62 finished with value: 0.21666411241736197 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9762049404553764, 'max_features': None, 'min_weight_fraction_leaf': 0.49754275023260003}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1744223841640345
Fold 2 IBS: 0.18700899459676598
Fold 3 IBS: 0.17217919062602105
Fold 4 IBS: 0.17202141747271338
Fold 5 IBS: 0.23216785220262717
[I 2024-04-14 12:55:37,982] Trial 63 finished with value: 0.1875599678124324 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 439, 'oob_score': False, 'max_samples': 0.968031626078303, 'max_features': None, 'min_weight_fraction_leaf': 0.4618736342149034}. Best is trial 54 with value: 0.1822436647018153.

Fold 1 IBS: 0.17758210577267103
Fold 2 IBS: 0.18839515678161117
Fold 3 IBS: 0.17378027525748194
Fold 4 IBS: 0.17402263926693903
Fold 5 IBS: 0.23329928868140723
[I 2024-04-14 12:55:41,730] Trial 64 finished with value: 0.1894158931520221 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.8662053800926933, 'max_features': None, 'min_weight_fraction_leaf': 0.4182804957604697}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17735779335885185
Fold 2 IBS: 0.18791831745948914
Fold 3 IBS: 0.17437629608751362
Fold 4 IBS: 0.1754060616546171
Fold 5 IBS: 0.2347254760738243
[I 2024-04-14 12:55:45,039] Trial 65 finished with value: 0.18995678892685922 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9168825987611354, 'max_features': None, 'min_weight_fraction_leaf': 0.4432122195886301}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2139724421467841
Fold 2 IBS: 0.2214527792035684
Fold 3 IBS: 0.2048590624528698
Fold 4 IBS: 0.2245788896889019
Fold 5 IBS: 0.2185362799035361
[I 2024-04-14 12:55:49,011] Trial 66 finished with value: 0.21667989067913207 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.46781511608424425, 'max_features': None, 'min_weight_fraction_leaf': 0.3045521505569209}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398680109724927
Fold 2 IBS: 0.22135827072227557
Fold 3 IBS: 0.2048735104861736
Fold 4 IBS: 0.22472365818178486
Fold 5 IBS: 0.21862352189579365
[I 2024-04-14 12:55:51,980] Trial 67 finished with value: 0.2167131524766554 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 350, 'oob_score': False, 'max_samples': 0.6582583476676168, 'max_features': None, 'min_weight_fraction_leaf': 0.3804796765638992}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398754621893906
Fold 2 IBS: 0.220784415256965
Fold 3 IBS: 0.20495861786072853
Fold 4 IBS: 0.22449787181399974
Fold 5 IBS: 0.21784084447117796
[I 2024-04-14 12:55:55,588] Trial 68 finished with value: 0.21641385912436206 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.23482143077480938, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3934624841168519}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398687185517215
Fold 2 IBS: 0.22139575665018285
Fold 3 IBS: 0.2047910639890974
Fold 4 IBS: 0.2245872648354145
Fold 5 IBS: 0.21854958475231978
[I 2024-04-14 12:56:01,109] Trial 69 finished with value: 0.21666210841643735 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 483, 'oob_score': True, 'max_samples': 0.7940255804653553, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4805897754538581}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2041191703983927
Fold 2 IBS: 0.20962737898277756
Fold 3 IBS: 0.19711142562638187
Fold 4 IBS: 0.20772967559861563
Fold 5 IBS: 0.2183057037055133
[I 2024-04-14 12:56:04,576] Trial 70 finished with value: 0.20737867086233625 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 17, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8487227557239918, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41490592987501546}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17259575541877814
Fold 2 IBS: 0.22029683841472378
Fold 3 IBS: 0.16571612203247052
Fold 4 IBS: 0.16231349383737712
Fold 5 IBS: 0.22994744909940326
[I 2024-04-14 12:56:07,963] Trial 71 finished with value: 0.19017393176055059 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.9046665199728599, 'max_features': None, 'min_weight_fraction_leaf': 0.3490138103045144}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398984891500278
Fold 2 IBS: 0.22132703559112848
Fold 3 IBS: 0.20485538942898837
Fold 4 IBS: 0.22468184149566728
Fold 5 IBS: 0.21854197240369455
[I 2024-04-14 12:56:10,899] Trial 72 finished with value: 0.2166792175668963 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.7417237460119614, 'max_features': None, 'min_weight_fraction_leaf': 0.4377532191740801}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17342415334654118
Fold 2 IBS: 0.2520286159476192
Fold 3 IBS: 0.16733908162702638
Fold 4 IBS: 0.15971476716385674
Fold 5 IBS: 0.2369472008097499
[I 2024-04-14 12:56:13,603] Trial 73 finished with value: 0.1978907637789587 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.9791771001513038, 'max_features': None, 'min_weight_fraction_leaf': 0.3151341872573396}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1523783018315216
Fold 2 IBS: 0.25752841787809405
Fold 3 IBS: 0.15865023022022903
Fold 4 IBS: 0.1469293709645116
Fold 5 IBS: 0.22884537022153476
[I 2024-04-14 12:56:18,468] Trial 74 finished with value: 0.18886633822317822 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.7597261021888175, 'max_features': None, 'min_weight_fraction_leaf': 0.028106730951250714}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17203138027431822
Fold 2 IBS: 0.18672618290031268
Fold 3 IBS: 0.17038726217502925
Fold 4 IBS: 0.16864095356589795
Fold 5 IBS: 0.2343085215113195
[I 2024-04-14 12:56:21,305] Trial 75 finished with value: 0.18641886008537553 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 323, 'oob_score': False, 'max_samples': 0.6919465218861461, 'max_features': None, 'min_weight_fraction_leaf': 0.3306551754510087}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1727138115840506
Fold 2 IBS: 0.21855719163630852
Fold 3 IBS: 0.16598015598426627
Fold 4 IBS: 0.16195355474343384
Fold 5 IBS: 0.23014794794296067
[I 2024-04-14 12:56:25,265] Trial 76 finished with value: 0.189870532378204 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.933109377361605, 'max_features': None, 'min_weight_fraction_leaf': 0.36359582317154915}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17070857985890084
Fold 2 IBS: 0.2654744432740884
Fold 3 IBS: 0.15749050693194808
Fold 4 IBS: 0.1458281671643887
Fold 5 IBS: 0.23993349327215213
[I 2024-04-14 12:56:29,204] Trial 77 finished with value: 0.19588703810029565 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.8922687338805234, 'max_features': None, 'min_weight_fraction_leaf': 0.1648569090893628}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17127175238988016
Fold 2 IBS: 0.23681907170241595
Fold 3 IBS: 0.16632945506132488
Fold 4 IBS: 0.15998000173876423
Fold 5 IBS: 0.2355786897961462
[I 2024-04-14 12:56:33,468] Trial 78 finished with value: 0.19399579413770632 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.8314975823537563, 'max_features': None, 'min_weight_fraction_leaf': 0.28987424398930645}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.21398696115622517
Fold 2 IBS: 0.22132775110717479
Fold 3 IBS: 0.2047844743795546
Fold 4 IBS: 0.22466419241471253
Fold 5 IBS: 0.218639565452965
[I 2024-04-14 12:56:37,815] Trial 79 finished with value: 0.21668058890212644 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.7147863835024943, 'max_features': None, 'min_weight_fraction_leaf': 0.45897134740659273}. Best is trial 54 with value: 0.1822436647018153.

Fold 1 IBS: 0.1754183266894564
Fold 2 IBS: 0.2119163985327653
Fold 3 IBS: 0.16611082563106694
Fold 4 IBS: 0.16255778819587066
Fold 5 IBS: 0.22916546086072462
[I 2024-04-14 12:56:40,234] Trial 80 finished with value: 0.18903375998197677 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9992480396864105, 'max_features': None, 'min_weight_fraction_leaf': 0.40510470687091726}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16993730570122387
Fold 2 IBS: 0.195387539069006
Fold 3 IBS: 0.1651714087990093
Fold 4 IBS: 0.16201193892631496
Fold 5 IBS: 0.22567140464684687
[I 2024-04-14 12:56:43,067] Trial 81 finished with value: 0.18363591942848018 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.8729504953795615, 'max_features': None, 'min_weight_fraction_leaf': 0.37901339934104195}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17059602798051093
Fold 2 IBS: 0.19576025349618845
Fold 3 IBS: 0.16527586886048148
Fold 4 IBS: 0.16216921896963785
Fold 5 IBS: 0.22563934477366224
[I 2024-04-14 12:56:45,853] Trial 82 finished with value: 0.1838881428160962 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.8793433759139604, 'max_features': None, 'min_weight_fraction_leaf': 0.37875540676023556}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1688164787241748
Fold 2 IBS: 0.18965430682325518
Fold 3 IBS: 0.16618614577597546
Fold 4 IBS: 0.1661442613630979
Fold 5 IBS: 0.22745311651470046
[I 2024-04-14 12:56:48,408] Trial 83 finished with value: 0.18365086184024076 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 267, 'oob_score': False, 'max_samples': 0.8596640069096237, 'max_features': None, 'min_weight_fraction_leaf': 0.3926517547430121}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.213982517924714
Fold 2 IBS: 0.22134028753572813
Fold 3 IBS: 0.20486839792753697
Fold 4 IBS: 0.22465180979217697
Fold 5 IBS: 0.21856402394553515
[I 2024-04-14 12:56:51,390] Trial 84 finished with value: 0.21668140742513825 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.7978897939316169, 'max_features': None, 'min_weight_fraction_leaf': 0.43016329217079746}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16955786746443186
Fold 2 IBS: 0.1888109914576175
Fold 3 IBS: 0.165403814650411
Fold 4 IBS: 0.16378935148321216
Fold 5 IBS: 0.22551798003020745
[I 2024-04-14 12:56:54,231] Trial 85 finished with value: 0.182616001017176 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9358948791674491, 'max_features': None, 'min_weight_fraction_leaf': 0.4163843260750398}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.2139659127114189
Fold 2 IBS: 0.2213058430062058
Fold 3 IBS: 0.2047998954201997
Fold 4 IBS: 0.2246551289755502
Fold 5 IBS: 0.2186437833442124
[I 2024-04-14 12:56:58,314] Trial 86 finished with value: 0.2166741126915174 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.9672107753485744, 'max_features': None, 'min_weight_fraction_leaf': 0.4839309447096827}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.18029523595045296
Fold 2 IBS: 0.19756882734748873
Fold 3 IBS: 0.18140356580749964
Fold 4 IBS: 0.187442503869447
Fold 5 IBS: 0.21589354656941978
[I 2024-04-14 12:57:02,306] Trial 87 finished with value: 0.19252073590886165 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.937791500744923, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.41589566298884967}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1658833334845161
Fold 2 IBS: 0.21698059956725585
Fold 3 IBS: 0.17024180776620185
Fold 4 IBS: 0.1629144227091129
Fold 5 IBS: 0.22737649617013614
[I 2024-04-14 12:57:05,868] Trial 88 finished with value: 0.18867933193944458 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.9297067916046122, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2581006317330029}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.17060519156572782
Fold 2 IBS: 0.18930502849920408
Fold 3 IBS: 0.1647821300478589
Fold 4 IBS: 0.16296071452652267
Fold 5 IBS: 0.22571370308607533
[I 2024-04-14 12:57:09,595] Trial 89 finished with value: 0.18267335354507777 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.9794054457739549, 'max_features': None, 'min_weight_fraction_leaf': 0.43792324727874116}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.18738975895838167
Fold 2 IBS: 0.200316373598964
Fold 3 IBS: 0.1858553433488537
Fold 4 IBS: 0.19295326279019026
Fold 5 IBS: 0.2178645385965687
[I 2024-04-14 12:57:11,157] Trial 90 finished with value: 0.19687585545859165 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.972970797060855, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4522473691813417}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16926655000191373
Fold 2 IBS: 0.18542452377204885
Fold 3 IBS: 0.16585353947869277
Fold 4 IBS: 0.16460153716121895
Fold 5 IBS: 0.22773118838132586
[I 2024-04-14 12:57:14,763] Trial 91 finished with value: 0.18257546775904004 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.9521862960288366, 'max_features': None, 'min_weight_fraction_leaf': 0.43852883097869544}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.16892429762898473
Fold 2 IBS: 0.18646265672233156
Fold 3 IBS: 0.1654282006715355
Fold 4 IBS: 0.1642863887112045
Fold 5 IBS: 0.22770623766264497
[I 2024-04-14 12:57:18,424] Trial 92 finished with value: 0.18256155627934026 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.9594749224604052, 'max_features': None, 'min_weight_fraction_leaf': 0.4382959745060329}. Best is trial 54 with value: 0.1822436647018153.
Fold 1 IBS: 0.1694038540499289
Fold 2 IBS: 0.18543879935671284
Fold 3 IBS: 0.16586969023548903
Fold 4 IBS: 0.16462913915674826
Fold 5 IBS: 0.22586792111306306
[I 2024-04-14 12:57:22,465] Trial 93 finished with value: 0.18224188078238843 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.951027581141039, 'max_features': None, 'min_weight_fraction_leaf': 0.434183032379547}. Best is trial 93 with value: 0.18224188078238843.
Fold 1 IBS: 0.16928255935057204
Fold 2 IBS: 0.18540640777204148
Fold 3 IBS: 0.1658202361732081
Fold 4 IBS: 0.1646058136763985
Fold 5 IBS: 0.22579726235858852
[I 2024-04-14 12:57:26,359] Trial 94 finished with value: 0.18218245586616172 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.9526180318811873, 'max_features': None, 'min_weight_fraction_leaf': 0.4336258803047899}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.16923916265142389
Fold 2 IBS: 0.18529265639052703
Fold 3 IBS: 0.16693367705651438
Fold 4 IBS: 0.16496792978619326
Fold 5 IBS: 0.22691047903734007
[I 2024-04-14 12:57:31,432] Trial 95 finished with value: 0.1826687809843997 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9482701576034527, 'max_features': None, 'min_weight_fraction_leaf': 0.43618730769703484}. Best is trial 94 with value: 0.18218245586616172.

Fold 1 IBS: 0.17691142196188117
Fold 2 IBS: 0.1884356638717461
Fold 3 IBS: 0.17473493092732248
Fold 4 IBS: 0.1743581409278057
Fold 5 IBS: 0.23455157057349743
[I 2024-04-14 12:57:35,826] Trial 96 finished with value: 0.18979834565245057 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.9548184208743441, 'max_features': None, 'min_weight_fraction_leaf': 0.46352447817689174}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.1720334166380091
Fold 2 IBS: 0.19310219127184633
Fold 3 IBS: 0.16467180888297991
Fold 4 IBS: 0.16215325103272105
Fold 5 IBS: 0.225731258677061
[I 2024-04-14 12:57:39,841] Trial 97 finished with value: 0.1835383853005235 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.9862595341313025, 'max_features': None, 'min_weight_fraction_leaf': 0.43210430346944234}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.1700673000394276
Fold 2 IBS: 0.18617467101403062
Fold 3 IBS: 0.16757525868013873
Fold 4 IBS: 0.16662978949249674
Fold 5 IBS: 0.2279242667055234
[I 2024-04-14 12:57:43,270] Trial 98 finished with value: 0.1836742571863234 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.9536448054185881, 'max_features': None, 'min_weight_fraction_leaf': 0.44518295335622443}. Best is trial 94 with value: 0.18218245586616172.
Fold 1 IBS: 0.21397475855510784
Fold 2 IBS: 0.2213213472048057
Fold 3 IBS: 0.20476273142913345
Fold 4 IBS: 0.22463568800419415
Fold 5 IBS: 0.21866074781038855
[I 2024-04-14 12:57:46,961] Trial 99 finished with value: 0.21667105460072594 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.9313705172208678, 'max_features': None, 'min_weight_fraction_leaf': 0.48244475073479054}. Best is trial 94 with value: 0.18218245586616172.


* Best trial for IBS:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.18218245586616172], datetime_start=datetime.datetime(2024, 4, 14, 12, 57, 22, 471282), datetime_complete=datetime.datetime(2024, 4, 14, 12, 57, 26, 358622), params={'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.9526180318811873, 'max_features': None, 'min_weight_fraction_leaf': 0.4336258803047899}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for IBS:
 0.18218245586616172

In [214]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [215]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.855
train_ibs:  0.182

#### Test

In [216]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [217]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=14, max_features=None, max_leaf_nodes=11,
                     max_samples=0.7127178148051858, min_samples_leaf=1,
                     min_samples_split=8,
                     min_weight_fraction_leaf=0.01586498778855871,
                     n_estimators=236, random_state=123, warm_start=True)

test_cindex:  0.643

RandomSurvivalForest(max_depth=2, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9526180318811873, min_samples_leaf=6,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.4336258803047899,
                     n_estimators=408, random_state=123)

test_ibs:  0.206

In [218]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [219]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [220]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 12:57:48,645] A new study created in memory with name: no-name-56a079ec-81c4-4472-b2db-d648da77fd08

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:57:49,605] Trial 0 finished with value: 0.7745879261443795 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:51,614] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:57:55,808] Trial 2 finished with value: 0.74921582480056 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:57:56,344] Trial 3 finished with value: 0.7668106824003204 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:57,946] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:57:59,700] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:00,729] Trial 6 finished with value: 0.7664150659615537 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:03,098] Trial 7 finished with value: 0.7616331450082747 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:03,269] Trial 8 finished with value: 0.7593018606857644 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7120535714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:08,409] Trial 9 finished with value: 0.7490908660462516 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:10,275] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6737089201877934
[I 2024-04-14 12:58:10,670] Trial 11 finished with value: 0.7734410842409543 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13639294401318086}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6941964285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:10,828] Trial 12 finished with value: 0.721690734532196 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 2, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9861268838969514, 'min_weight_fraction_leaf': 0.19160160653003072}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7433035714285714
Fold 3 C-index: 0.8406862745098039
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6502347417840375
[I 2024-04-14 12:58:11,275] Trial 13 finished with value: 0.7681118362797557 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.09287447212810436}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:11,618] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 0 with value: 0.7745879261443795.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:12,546] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.38518225566002634}. Best is trial 0 with value: 0.7745879261443795.

Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:13,247] Trial 16 finished with value: 0.7829471027296476 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8988170687511211, 'min_weight_fraction_leaf': 0.1144909881867055}. Best is trial 16 with value: 0.7829471027296476.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:58:14,005] Trial 17 finished with value: 0.7903075269233125 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8640754037508087, 'min_weight_fraction_leaf': 0.07031499130910734}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.647887323943662
[I 2024-04-14 12:58:16,928] Trial 18 finished with value: 0.7395348597144817 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 257, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8895071108037167, 'min_weight_fraction_leaf': 0.0011589181071390564}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:58:17,516] Trial 19 finished with value: 0.7598333453018479 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.41695365388974803, 'min_weight_fraction_leaf': 0.18034377200013021}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:18,292] Trial 20 finished with value: 0.7807674841440166 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6674617762374991, 'min_weight_fraction_leaf': 0.07545444842690581}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:19,047] Trial 21 finished with value: 0.7776727023732231 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.05962726046385198}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:19,788] Trial 22 finished with value: 0.7830784757621748 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 199, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8771608646297815, 'min_weight_fraction_leaf': 0.10225905155944082}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:20,355] Trial 23 finished with value: 0.7851496206758364 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8802210933826596, 'min_weight_fraction_leaf': 0.11513537121280795}. Best is trial 17 with value: 0.7903075269233125.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:58:20,837] Trial 24 finished with value: 0.8035361410322084 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 178, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8280973992230685, 'min_weight_fraction_leaf': 0.039544913909338314}. Best is trial 24 with value: 0.8035361410322084.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:58:21,322] Trial 25 finished with value: 0.8076326900231233 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 164, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7316226562435669, 'min_weight_fraction_leaf': 0.033937366778186574}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:58:23,212] Trial 26 finished with value: 0.7518596934957065 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 154, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7208034772056066, 'min_weight_fraction_leaf': 0.029644882569539167}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 12:58:23,518] Trial 27 finished with value: 0.7603700938794618 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 84, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.030014352957988627}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.636150234741784
[I 2024-04-14 12:58:24,038] Trial 28 finished with value: 0.7636235600497999 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 166, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6118099528026927, 'min_weight_fraction_leaf': 0.15653961257940716}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6455399061032864
[I 2024-04-14 12:58:25,050] Trial 29 finished with value: 0.7613503804818579 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7417740935442027, 'min_weight_fraction_leaf': 0.21971840542663756}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:58:25,525] Trial 30 finished with value: 0.7585961222444212 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 60, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8287064817805315, 'min_weight_fraction_leaf': 0.2917886569515737}. Best is trial 25 with value: 0.8076326900231233.

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 12:58:26,200] Trial 31 finished with value: 0.789727434191557 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9117101001226512, 'min_weight_fraction_leaf': 0.07589392630375186}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:26,972] Trial 32 finished with value: 0.7998784511940888 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9461941300895063, 'min_weight_fraction_leaf': 0.059917450695551475}. Best is trial 25 with value: 0.8076326900231233.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:58:27,534] Trial 33 finished with value: 0.8277557904796954 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9253318298362483, 'min_weight_fraction_leaf': 0.03545814398460863}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 12:58:28,255] Trial 34 finished with value: 0.8207865463159607 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9492142992192825, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:29,582] Trial 35 finished with value: 0.7965082826433545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 171, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7408527707592886, 'min_weight_fraction_leaf': 0.027557073332567256}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:31,310] Trial 36 finished with value: 0.7524488383742287 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 118, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9405179069693569, 'min_weight_fraction_leaf': 0.007687894074078279}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:31,991] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 191, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4720019534455855, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:32,485] Trial 38 finished with value: 0.7928763753349765 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8312601725260211, 'min_weight_fraction_leaf': 0.04442416941679308}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:58:34,934] Trial 39 finished with value: 0.7439658383126666 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 172, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9887286618847455, 'min_weight_fraction_leaf': 0.3676238651442645}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:35,876] Trial 40 finished with value: 0.7645366793940384 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.530081714362, 'min_weight_fraction_leaf': 0.08564159788365241}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7510822510822511
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:36,305] Trial 41 finished with value: 0.7975503824522079 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9630979224273323, 'min_weight_fraction_leaf': 0.05753755330386147}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:58:36,648] Trial 42 finished with value: 0.8197059316116923 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.936335968839529, 'min_weight_fraction_leaf': 0.0196273766061303}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-14 12:58:36,965] Trial 43 finished with value: 0.8065119240454575 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7820142238093898, 'min_weight_fraction_leaf': 0.01502244059442382}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7857142857142857
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:58:37,242] Trial 44 finished with value: 0.7843530124654604 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9277478422411788, 'min_weight_fraction_leaf': 0.01862377405598601}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7770562770562771
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:58:37,766] Trial 45 finished with value: 0.8071680483405862 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7801908997243348, 'min_weight_fraction_leaf': 0.003596095332568664}. Best is trial 33 with value: 0.8277557904796954.

Fold 1 C-index: 0.79004329004329
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:58:38,310] Trial 46 finished with value: 0.7771578201695108 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 296, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3546626066657711, 'min_weight_fraction_leaf': 0.04136165195538784}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:58:39,036] Trial 47 finished with value: 0.7420345847053712 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 106, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6036313637833004, 'min_weight_fraction_leaf': 0.14035378430654144}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:58:40,004] Trial 48 finished with value: 0.7911104360543549 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 325, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9981726809518219, 'min_weight_fraction_leaf': 0.09485011729041189}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7183098591549296
[I 2024-04-14 12:58:40,445] Trial 49 finished with value: 0.8145687781668691 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8520528511725862, 'min_weight_fraction_leaf': 0.005130204491028089}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:58:41,074] Trial 50 finished with value: 0.7598345729400207 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8517006580337982, 'min_weight_fraction_leaf': 0.05367186162265391}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:58:41,640] Trial 51 finished with value: 0.8082755334665999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7867769730122244, 'min_weight_fraction_leaf': 0.000567877460161197}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7136150234741784
[I 2024-04-14 12:58:42,160] Trial 52 finished with value: 0.816489818670138 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6993857292105528, 'min_weight_fraction_leaf': 0.0019627716877025497}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:42,758] Trial 53 finished with value: 0.792930487889089 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9018947927380415, 'min_weight_fraction_leaf': 0.0026886780958639556}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:58:43,230] Trial 54 finished with value: 0.801950095221479 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6857415391610537, 'min_weight_fraction_leaf': 0.018807937661752497}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6854460093896714
[I 2024-04-14 12:58:43,780] Trial 55 finished with value: 0.7734562026483229 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8526921799077428, 'min_weight_fraction_leaf': 0.0690156297051535}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:44,139] Trial 56 finished with value: 0.7911372233377703 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9287340946056967, 'min_weight_fraction_leaf': 0.048509967258659394}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:58:44,841] Trial 57 finished with value: 0.7628345469373019 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9641242469397642, 'min_weight_fraction_leaf': 0.10495833421992688}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7813852813852814
Fold 2 C-index: 0.75
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:58:45,357] Trial 58 finished with value: 0.7742217809667181 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 264, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8013305653217244, 'min_weight_fraction_leaf': 0.08339466927336016}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:58:47,676] Trial 59 finished with value: 0.762559424611025 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 301, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7639334102320097, 'min_weight_fraction_leaf': 5.2123975336132444e-05}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:58:48,161] Trial 60 finished with value: 0.7524260845766856 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6968556353741848, 'min_weight_fraction_leaf': 0.1227005732829336}. Best is trial 33 with value: 0.8277557904796954.

Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 12:58:48,521] Trial 61 finished with value: 0.7927460479159167 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6192920945584268, 'min_weight_fraction_leaf': 0.028331502848269144}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:48,984] Trial 62 finished with value: 0.7901297749038513 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8587851429043888, 'min_weight_fraction_leaf': 0.03786024116571255}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6948356807511737
[I 2024-04-14 12:58:49,438] Trial 63 finished with value: 0.8018215874819757 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 195, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.902572914251135, 'min_weight_fraction_leaf': 0.02139829571380404}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7611607142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6549295774647887
[I 2024-04-14 12:58:50,201] Trial 64 finished with value: 0.7619425976479832 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 348, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7397571765612656, 'min_weight_fraction_leaf': 0.06699693366368531}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:58:50,733] Trial 65 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8152768766632212, 'min_weight_fraction_leaf': 0.4134291052499814}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6431924882629108
[I 2024-04-14 12:58:51,023] Trial 66 finished with value: 0.7476285289355211 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 148, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9671004949877344, 'min_weight_fraction_leaf': 0.2772702088742331}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7943722943722944
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:58:51,665] Trial 67 finished with value: 0.7912429906159129 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7124789245232053, 'min_weight_fraction_leaf': 0.0397223511048666}. Best is trial 33 with value: 0.8277557904796954.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.755868544600939
[I 2024-04-14 12:58:52,385] Trial 68 finished with value: 0.8339253020775889 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7655598056446573, 'min_weight_fraction_leaf': 0.024444075764824668}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:58:53,067] Trial 69 finished with value: 0.814775589444517 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8785074378527057, 'min_weight_fraction_leaf': 0.01463438422425671}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 12:58:56,726] Trial 70 finished with value: 0.7525231438950724 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8806838182536976, 'min_weight_fraction_leaf': 0.05390111103124775}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7276995305164319
[I 2024-04-14 12:58:57,413] Trial 71 finished with value: 0.8174760798823492 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9147835512625551, 'min_weight_fraction_leaf': 0.021711085638457594}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7464788732394366
[I 2024-04-14 12:58:58,054] Trial 72 finished with value: 0.8249346090078683 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9341419337500907, 'min_weight_fraction_leaf': 0.017715787168804925}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7230046948356808
[I 2024-04-14 12:58:58,765] Trial 73 finished with value: 0.8155618578571318 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 419, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9206915345316207, 'min_weight_fraction_leaf': 0.0199096151844373}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6995305164319249
[I 2024-04-14 12:58:59,462] Trial 74 finished with value: 0.7956937290386422 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9223690642871444, 'min_weight_fraction_leaf': 0.027323163950626075}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6807511737089202
[I 2024-04-14 12:59:00,123] Trial 75 finished with value: 0.7933974489324085 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 425, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9633824901969965, 'min_weight_fraction_leaf': 0.07492570501709929}. Best is trial 68 with value: 0.8339253020775889.

Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6901408450704225
[I 2024-04-14 12:59:00,956] Trial 76 finished with value: 0.7865958181681074 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9445741584510846, 'min_weight_fraction_leaf': 0.04529598588507214}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:59:01,639] Trial 77 finished with value: 0.8275693066655989 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 385, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9177495621960954, 'min_weight_fraction_leaf': 0.0175914943830058}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:02,348] Trial 78 finished with value: 0.8039065188872353 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 389, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9999309599975079, 'min_weight_fraction_leaf': 0.06082418990255621}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6126760563380281
[I 2024-04-14 12:59:03,007] Trial 79 finished with value: 0.752101204811168 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.15501833559358602}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6572769953051644
[I 2024-04-14 12:59:03,875] Trial 80 finished with value: 0.7898209662315144 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8345492972234845, 'min_weight_fraction_leaf': 0.08687921144727206}. Best is trial 68 with value: 0.8339253020775889.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7699530516431925
[I 2024-04-14 12:59:04,617] Trial 81 finished with value: 0.8379466409572306 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9144351157674113, 'min_weight_fraction_leaf': 0.02101412026626872}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7417840375586855
[I 2024-04-14 12:59:05,380] Trial 82 finished with value: 0.8258377049339971 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9018142227663485, 'min_weight_fraction_leaf': 0.030243117812127265}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7370892018779343
[I 2024-04-14 12:59:06,226] Trial 83 finished with value: 0.8212887494987298 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 434, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8987511549772431, 'min_weight_fraction_leaf': 0.030708676849641337}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7597402597402597
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7323943661971831
[I 2024-04-14 12:59:07,182] Trial 84 finished with value: 0.815946338015911 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 447, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9712348786474978, 'min_weight_fraction_leaf': 0.03859567778983075}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 12:59:08,063] Trial 85 finished with value: 0.5 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 429, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.10698873156508726, 'min_weight_fraction_leaf': 0.20690811169877674}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6314553990610329
[I 2024-04-14 12:59:08,842] Trial 86 finished with value: 0.7683500624961893 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.888143001293517, 'min_weight_fraction_leaf': 0.047492110690733655}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6525821596244131
[I 2024-04-14 12:59:12,939] Trial 87 finished with value: 0.7476292753361251 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9811204002381699, 'min_weight_fraction_leaf': 0.015144189829260607}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7089201877934272
[I 2024-04-14 12:59:13,764] Trial 88 finished with value: 0.8052656989228859 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9375347651581424, 'min_weight_fraction_leaf': 0.06271623214415978}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7890295358649789
Fold 5 C-index: 0.6408450704225352
[I 2024-04-14 12:59:14,487] Trial 89 finished with value: 0.76219324949789 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 385, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9495185080796891, 'min_weight_fraction_leaf': 0.03327821020686611}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-14 12:59:15,105] Trial 90 finished with value: 0.7879114291788776 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8992892522112221, 'min_weight_fraction_leaf': 0.10106275880196715}. Best is trial 81 with value: 0.8379466409572306.

Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7511737089201878
[I 2024-04-14 12:59:15,934] Trial 91 finished with value: 0.8315679050838799 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9106660966863834, 'min_weight_fraction_leaf': 0.02781514243344381}. Best is trial 81 with value: 0.8379466409572306.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:59:16,670] Trial 92 finished with value: 0.8432300242257715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8652215671367193, 'min_weight_fraction_leaf': 0.012452248638747002}. Best is trial 92 with value: 0.8432300242257715.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7746478873239436
[I 2024-04-14 12:59:17,315] Trial 93 finished with value: 0.8432300242257715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.866955242071647, 'min_weight_fraction_leaf': 0.010049890541173948}. Best is trial 92 with value: 0.8432300242257715.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:59:18,057] Trial 94 finished with value: 0.8451079584980722 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8716108940255133, 'min_weight_fraction_leaf': 0.011609527241604658}. Best is trial 94 with value: 0.8451079584980722.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:59:18,932] Trial 95 finished with value: 0.8452444687983947 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 407, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8660570643802762, 'min_weight_fraction_leaf': 0.0114176313655637}. Best is trial 95 with value: 0.8452444687983947.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.784037558685446
[I 2024-04-14 12:59:19,703] Trial 96 finished with value: 0.8426419289331968 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8346852194839303, 'min_weight_fraction_leaf': 0.011973250765768627}. Best is trial 95 with value: 0.8452444687983947.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:59:20,491] Trial 97 finished with value: 0.8441419350848655 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8065462716711389, 'min_weight_fraction_leaf': 0.011063583331044763}. Best is trial 95 with value: 0.8452444687983947.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7793427230046949
[I 2024-04-14 12:59:21,263] Trial 98 finished with value: 0.8432709969512692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8030550782984262, 'min_weight_fraction_leaf': 0.009969371259572098}. Best is trial 95 with value: 0.8452444687983947.

[I 2024-04-14 12:59:22,022] A new study created in memory with name: no-name-49ab8c11-166d-4e32-93cc-9577bf712192

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.812206572769953
[I 2024-04-14 12:59:22,005] Trial 99 finished with value: 0.8475275642437399 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7657259832611387, 'min_weight_fraction_leaf': 0.007259167100140962}. Best is trial 99 with value: 0.8475275642437399.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.8475275642437399], datetime_start=datetime.datetime(2024, 4, 14, 12, 59, 21, 272122), datetime_complete=datetime.datetime(2024, 4, 14, 12, 59, 22, 4538), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7657259832611387, 'min_weight_fraction_leaf': 0.007259167100140962}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=99, value=None)


* Best Score for C-index:
 0.8475275642437399

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1634495256547181
Fold 2 IBS: 0.2207215628045014
Fold 3 IBS: 0.16345393335965422
Fold 4 IBS: 0.15807900971573238
Fold 5 IBS: 0.23372859122405484
[I 2024-04-14 12:59:24,529] Trial 0 finished with value: 0.18788652455173221 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-14 12:59:28,020] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.17758308948531826
Fold 2 IBS: 0.20689085226294357
Fold 3 IBS: 0.1754223431485378
Fold 4 IBS: 0.17751726525948885
Fold 5 IBS: 0.22185249393073614
[I 2024-04-14 12:59:31,962] Trial 2 finished with value: 0.19185320881740492 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.17878695086095409
Fold 2 IBS: 0.20726271618706082
Fold 3 IBS: 0.17784011679731462
Fold 4 IBS: 0.1775723120105269
Fold 5 IBS: 0.22068259102560173
[I 2024-04-14 12:59:33,306] Trial 3 finished with value: 0.19242893737629163 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-14 12:59:36,145] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-14 12:59:37,438] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.16370111758710457
Fold 2 IBS: 0.21987223286992366
Fold 3 IBS: 0.16496917801290514
Fold 4 IBS: 0.1588222771800454
Fold 5 IBS: 0.2351001359843554
[I 2024-04-14 12:59:40,255] Trial 6 finished with value: 0.18849298832686684 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.18788652455173221.
Fold 1 IBS: 0.16353665733560305
Fold 2 IBS: 0.2110107862840051
Fold 3 IBS: 0.16686408187867838
Fold 4 IBS: 0.16172494829232667
Fold 5 IBS: 0.2256350896528721
[I 2024-04-14 12:59:41,978] Trial 7 finished with value: 0.18575431268869705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.18076192842718883
Fold 2 IBS: 0.20318073756732816
Fold 3 IBS: 0.17583427747236266
Fold 4 IBS: 0.1782527958014281
Fold 5 IBS: 0.22087176188525123
[I 2024-04-14 12:59:42,367] Trial 8 finished with value: 0.1917803002307118 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.18664290949595258
Fold 2 IBS: 0.2082110927214874
Fold 3 IBS: 0.1837409529358456
Fold 4 IBS: 0.19671407957723833
Fold 5 IBS: 0.21620854529635383
[I 2024-04-14 12:59:46,130] Trial 9 finished with value: 0.19830351600537555 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.2139976337400846
Fold 2 IBS: 0.22078850566211056
Fold 3 IBS: 0.20468678510920732
Fold 4 IBS: 0.2246562137512858
Fold 5 IBS: 0.21763185598455237
[I 2024-04-14 12:59:47,156] Trial 10 finished with value: 0.21635219884944812 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 98, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.21752764504502275, 'min_weight_fraction_leaf': 0.20722772178871404}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1616297345532555
Fold 2 IBS: 0.22477157982658855
Fold 3 IBS: 0.1628591795670332
Fold 4 IBS: 0.15347907270492941
Fold 5 IBS: 0.23632329428819998
[I 2024-04-14 12:59:49,376] Trial 11 finished with value: 0.18781257218800135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9798332536002032, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1598451980902628
Fold 2 IBS: 0.22567451798648389
Fold 3 IBS: 0.1613372135816081
Fold 4 IBS: 0.1527503434788428
Fold 5 IBS: 0.23634129086119499
[I 2024-04-14 12:59:51,680] Trial 12 finished with value: 0.18718971279967853 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 325, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9918679953533508, 'min_weight_fraction_leaf': 0.0011000669636376317}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16467084723870426
Fold 2 IBS: 0.2176412981294037
Fold 3 IBS: 0.16837867720229477
Fold 4 IBS: 0.1659362482405388
Fold 5 IBS: 0.23013568014439548
[I 2024-04-14 12:59:53,407] Trial 13 finished with value: 0.1893525501910674 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 230, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9797860832276054, 'min_weight_fraction_leaf': 0.16922765932800388}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1584759165156057
Fold 2 IBS: 0.22632609949403584
Fold 3 IBS: 0.16096919429847978
Fold 4 IBS: 0.14975247791796673
Fold 5 IBS: 0.2381029557244808
[I 2024-04-14 12:59:56,035] Trial 14 finished with value: 0.18672532879011378 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 353, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9137196108207343, 'min_weight_fraction_leaf': 0.060153931854044475}. Best is trial 7 with value: 0.18575431268869705.

Fold 1 IBS: 0.17001829960754553
Fold 2 IBS: 0.21114960801375182
Fold 3 IBS: 0.1680714029134848
Fold 4 IBS: 0.16577229376912112
Fold 5 IBS: 0.22377735237388288
[I 2024-04-14 12:59:58,532] Trial 15 finished with value: 0.1877577913355572 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 383, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8889618006305522, 'min_weight_fraction_leaf': 0.07436726243220565}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.21400217070766633
Fold 2 IBS: 0.22100539917942766
Fold 3 IBS: 0.20500880185904657
Fold 4 IBS: 0.22489607038963122
Fold 5 IBS: 0.21842771716193188
[I 2024-04-14 13:00:00,280] Trial 16 finished with value: 0.21666803185954073 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 249, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.34623136307464575, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1714610200768086
Fold 2 IBS: 0.2535348499538688
Fold 3 IBS: 0.16708922017863614
Fold 4 IBS: 0.16097218140786684
Fold 5 IBS: 0.24047543618622114
[I 2024-04-14 13:00:01,413] Trial 17 finished with value: 0.1987065415606803 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 172, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.680642613858846, 'min_weight_fraction_leaf': 0.18837169005037474}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.15727222398111593
Fold 2 IBS: 0.22636873507694102
Fold 3 IBS: 0.16085031055264207
Fold 4 IBS: 0.14989663564301253
Fold 5 IBS: 0.2399011989692626
[I 2024-04-14 13:00:04,141] Trial 18 finished with value: 0.18685782084459485 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 278, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.890683333800088, 'min_weight_fraction_leaf': 0.04810695432871126}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.21393422737114717
Fold 2 IBS: 0.22070652500675628
Fold 3 IBS: 0.20517424231033535
Fold 4 IBS: 0.22472266626046555
Fold 5 IBS: 0.21698629200627595
[I 2024-04-14 13:00:06,832] Trial 19 finished with value: 0.21630479059099605 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 378, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.10730942678329708, 'min_weight_fraction_leaf': 0.11946047041251526}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.18672950016710899
Fold 2 IBS: 0.18938332474155176
Fold 3 IBS: 0.17421169595898747
Fold 4 IBS: 0.18793677804530293
Fold 5 IBS: 0.21778991805646736
[I 2024-04-14 13:00:06,987] Trial 20 finished with value: 0.19121024339388368 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 6, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8835873208001659, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.15681298167605615
Fold 2 IBS: 0.2271960747866135
Fold 3 IBS: 0.16070156544785022
Fold 4 IBS: 0.14896763064780782
Fold 5 IBS: 0.23914784020726454
[I 2024-04-14 13:00:09,889] Trial 21 finished with value: 0.18656521855311844 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 289, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8999640553775872, 'min_weight_fraction_leaf': 0.04716588401379651}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1592289985770573
Fold 2 IBS: 0.22391660419829243
Fold 3 IBS: 0.1626503856606286
Fold 4 IBS: 0.15555083464553174
Fold 5 IBS: 0.23457220531293152
[I 2024-04-14 13:00:12,867] Trial 22 finished with value: 0.18718380567888832 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8795160396221542, 'min_weight_fraction_leaf': 0.05190855638530002}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16448977781499782
Fold 2 IBS: 0.21570259714710632
Fold 3 IBS: 0.16594723348471818
Fold 4 IBS: 0.15991904995512302
Fold 5 IBS: 0.23342393771993838
[I 2024-04-14 13:00:15,397] Trial 23 finished with value: 0.18789651922437672 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 271, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.66555351612603, 'min_weight_fraction_leaf': 0.09969684717552962}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1667895131394715
Fold 2 IBS: 0.2111672239286755
Fold 3 IBS: 0.1673249965925457
Fold 4 IBS: 0.16435567812575633
Fold 5 IBS: 0.22436532479069474
[I 2024-04-14 13:00:17,668] Trial 24 finished with value: 0.18680054731542878 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9309715061102081, 'min_weight_fraction_leaf': 0.03661049811995851}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1646108674306539
Fold 2 IBS: 0.21505911732400712
Fold 3 IBS: 0.16632277504976264
Fold 4 IBS: 0.1639991387811288
Fold 5 IBS: 0.22970868480968595
[I 2024-04-14 13:00:19,390] Trial 25 finished with value: 0.1879401166790477 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 201, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8351422293659327, 'min_weight_fraction_leaf': 0.16172786458443078}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.17182749380843
Fold 2 IBS: 0.24743091699916395
Fold 3 IBS: 0.16832356578798716
Fold 4 IBS: 0.16182773001582368
Fold 5 IBS: 0.23807911639445214
[I 2024-04-14 13:00:22,720] Trial 26 finished with value: 0.19749776460117136 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 357, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.723442048171647, 'min_weight_fraction_leaf': 0.22955083164714912}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16270170377022197
Fold 2 IBS: 0.21885279863174525
Fold 3 IBS: 0.1604747506158197
Fold 4 IBS: 0.15589312229487554
Fold 5 IBS: 0.233984619675705
[I 2024-04-14 13:00:23,776] Trial 27 finished with value: 0.18638139899767348 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 128, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9382216081429866, 'min_weight_fraction_leaf': 0.09432766696317679}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16886841956994145
Fold 2 IBS: 0.21375557337826087
Fold 3 IBS: 0.1714933178886696
Fold 4 IBS: 0.17345862613841123
Fold 5 IBS: 0.22553760527316705
[I 2024-04-14 13:00:25,146] Trial 28 finished with value: 0.19062270844969004 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 134, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8472712874409023, 'min_weight_fraction_leaf': 0.10335375332904807}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16270185532709952
Fold 2 IBS: 0.21994261443718016
Fold 3 IBS: 0.16127647472475745
Fold 4 IBS: 0.1571589664918226
Fold 5 IBS: 0.2328495122786568
[I 2024-04-14 13:00:26,072] Trial 29 finished with value: 0.18678588465190332 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7351436146825867, 'min_weight_fraction_leaf': 0.08929387187435558}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.16288193492716865

Fold 2 IBS: 0.2145204309047712
Fold 3 IBS: 0.16344681522379592
Fold 4 IBS: 0.1607591766490642
Fold 5 IBS: 0.23285217315239765
[I 2024-04-14 13:00:26,822] Trial 30 finished with value: 0.18689210617143953 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 87, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9504933061433887, 'min_weight_fraction_leaf': 0.1352883886134873}. Best is trial 7 with value: 0.18575431268869705.
Fold 1 IBS: 0.1522561822367273
Fold 2 IBS: 0.22165813527341477
Fold 3 IBS: 0.15806345503003275
Fold 4 IBS: 0.14643989125013568
Fold 5 IBS: 0.23525263253654355
[I 2024-04-14 13:00:28,347] Trial 31 finished with value: 0.18273405926537079 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9254246685599902, 'min_weight_fraction_leaf': 0.03593211426266471}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.152084228096772
Fold 2 IBS: 0.22338679434727662
Fold 3 IBS: 0.1592399130977972
Fold 4 IBS: 0.14639330672692666
Fold 5 IBS: 0.23427790617525826
[I 2024-04-14 13:00:30,405] Trial 32 finished with value: 0.18307642968880614 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 194, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8345378470592087, 'min_weight_fraction_leaf': 0.035230873471267764}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15380255879912433
Fold 2 IBS: 0.22181666026356436
Fold 3 IBS: 0.15705843385114202
Fold 4 IBS: 0.14721631258548995
Fold 5 IBS: 0.2338932564033125
[I 2024-04-14 13:00:32,466] Trial 33 finished with value: 0.18275744438052663 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 188, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8258297946312451, 'min_weight_fraction_leaf': 0.026110711916289307}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16205520207895716
Fold 2 IBS: 0.21385077584076523
Fold 3 IBS: 0.1706352761032662
Fold 4 IBS: 0.17133887157807096
Fold 5 IBS: 0.22690608447450347
[I 2024-04-14 13:00:34,154] Trial 34 finished with value: 0.1889572420151126 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8278794226549628, 'min_weight_fraction_leaf': 0.025466420115565977}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1522965326564986
Fold 2 IBS: 0.22209122076352877
Fold 3 IBS: 0.15849077495543015
Fold 4 IBS: 0.1458628906600359
Fold 5 IBS: 0.23585540742953134
[I 2024-04-14 13:00:35,989] Trial 35 finished with value: 0.18291936529300495 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 219, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6150980762772024, 'min_weight_fraction_leaf': 0.02487125392124865}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16169475241976686
Fold 2 IBS: 0.2168496018008369
Fold 3 IBS: 0.16242406959288777
Fold 4 IBS: 0.15514556293471984
Fold 5 IBS: 0.23504817437319558
[I 2024-04-14 13:00:37,340] Trial 36 finished with value: 0.18623243222428137 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 157, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6184306005543774, 'min_weight_fraction_leaf': 0.06555595087029042}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.21400195954884413
Fold 2 IBS: 0.22153443838080922
Fold 3 IBS: 0.20488071601118957
Fold 4 IBS: 0.2247084450075908
Fold 5 IBS: 0.21844619763715448
[I 2024-04-14 13:00:38,765] Trial 37 finished with value: 0.21671435131711764 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4657687648677202, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1558201715273734
Fold 2 IBS: 0.21762918288292568
Fold 3 IBS: 0.16186255500360855
Fold 4 IBS: 0.15614141377459878
Fold 5 IBS: 0.23635811168272997
[I 2024-04-14 13:00:40,562] Trial 38 finished with value: 0.18556228697424726 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 224, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.021082336124271187}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16709619511888768
Fold 2 IBS: 0.20717502377437425
Fold 3 IBS: 0.16588698156023982
Fold 4 IBS: 0.15929610941773517
Fold 5 IBS: 0.22970985966686808
[I 2024-04-14 13:00:41,113] Trial 39 finished with value: 0.185832833907621 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5170603136817243, 'min_weight_fraction_leaf': 0.07850341492135832}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15535306786987405
Fold 2 IBS: 0.21968220141827496
Fold 3 IBS: 0.15817361001927507
Fold 4 IBS: 0.1500191949330929
Fold 5 IBS: 0.23811441381413023
[I 2024-04-14 13:00:42,367] Trial 40 finished with value: 0.18426849761092945 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 166, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6193719603364062, 'min_weight_fraction_leaf': 0.026060732225759387}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15525917425921365
Fold 2 IBS: 0.21959565973354
Fold 3 IBS: 0.1579184197036489
Fold 4 IBS: 0.1499338299909122
Fold 5 IBS: 0.238221550884136
[I 2024-04-14 13:00:43,747] Trial 41 finished with value: 0.18418572691429014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 169, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6256149415751115, 'min_weight_fraction_leaf': 0.02449027643146977}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15078559029270888
Fold 2 IBS: 0.22274109803457892
Fold 3 IBS: 0.1585513727674162
Fold 4 IBS: 0.14641316263224702
Fold 5 IBS: 0.23535565723438484
[I 2024-04-14 13:00:45,371] Trial 42 finished with value: 0.18276937619226716 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 213, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7203447396327514, 'min_weight_fraction_leaf': 0.0015088944882710696}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.17374544997287594
Fold 2 IBS: 0.2061968924844769
Fold 3 IBS: 0.17281750596449846
Fold 4 IBS: 0.18307213900280708
Fold 5 IBS: 0.21711811614435095
[I 2024-04-14 13:00:47,061] Trial 43 finished with value: 0.19059002071380185 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 218, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7447038358575387, 'min_weight_fraction_leaf': 0.27764552944355786}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16406093006581368
Fold 2 IBS: 0.21499120889996837
Fold 3 IBS: 0.16536711596153658
Fold 4 IBS: 0.16197817418246774
Fold 5 IBS: 0.23133183232652665
[I 2024-04-14 13:00:48,988] Trial 44 finished with value: 0.1875458522872626 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 251, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.704529879921064, 'min_weight_fraction_leaf': 0.11873435420263456}. Best is trial 31 with value: 0.18273405926537079.

Fold 1 IBS: 0.154877427493089
Fold 2 IBS: 0.2119381972371029
Fold 3 IBS: 0.16230571380133155
Fold 4 IBS: 0.15585982768129883
Fold 5 IBS: 0.23020111518690609
[I 2024-04-14 13:00:50,061] Trial 45 finished with value: 0.18303645627994566 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 139, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7784599232837964, 'min_weight_fraction_leaf': 0.0038388411371728937}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1807341100446867
Fold 2 IBS: 0.20797545001135234
Fold 3 IBS: 0.17776524098244717
Fold 4 IBS: 0.18082034578648548
Fold 5 IBS: 0.22062001984045795
[I 2024-04-14 13:00:51,053] Trial 46 finished with value: 0.19358303333308596 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 138, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7835655363480928, 'min_weight_fraction_leaf': 0.012753322482536189}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.17357198284816136
Fold 2 IBS: 0.2076463796451187
Fold 3 IBS: 0.17165012622183687
Fold 4 IBS: 0.17167595706828814
Fold 5 IBS: 0.22234280598800027
[I 2024-04-14 13:00:54,479] Trial 47 finished with value: 0.18937745035428108 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5769040196663563, 'min_weight_fraction_leaf': 0.06629554430454714}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1776031563236035
Fold 2 IBS: 0.20715044966565485
Fold 3 IBS: 0.1741935756429268
Fold 4 IBS: 0.17625883720668134
Fold 5 IBS: 0.22185225847744403
[I 2024-04-14 13:00:55,996] Trial 48 finished with value: 0.1914116554632621 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7889727038638424, 'min_weight_fraction_leaf': 0.0024058613061327646}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.2140273796553489
Fold 2 IBS: 0.22164355262784735
Fold 3 IBS: 0.20485005087992433
Fold 4 IBS: 0.22478667236309535
Fold 5 IBS: 0.2185719225359654
[I 2024-04-14 13:00:57,343] Trial 49 finished with value: 0.21677591561243625 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 183, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.691739557624784, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15548669193123835
Fold 2 IBS: 0.21990220358017945
Fold 3 IBS: 0.16360047479288634
Fold 4 IBS: 0.1563346755585229
Fold 5 IBS: 0.23717706454740067
[I 2024-04-14 13:00:58,130] Trial 50 finished with value: 0.18650022208204553 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 90, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7668034916331786, 'min_weight_fraction_leaf': 0.003320042867536673}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15627339813164665
Fold 2 IBS: 0.22498174666133097
Fold 3 IBS: 0.16220735085232846
Fold 4 IBS: 0.14912647182487654
Fold 5 IBS: 0.2376450410667353
[I 2024-04-14 13:00:59,326] Trial 51 finished with value: 0.18604680170738358 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 144, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8252061287283556, 'min_weight_fraction_leaf': 0.04949342957471389}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15659883389607573
Fold 2 IBS: 0.22047290642541456
Fold 3 IBS: 0.1630699661650437
Fold 4 IBS: 0.15695721562566778
Fold 5 IBS: 0.23229697140734873
[I 2024-04-14 13:01:01,160] Trial 52 finished with value: 0.18587917870391008 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 241, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8037463915769376, 'min_weight_fraction_leaf': 0.03358842069468584}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16374041515527638
Fold 2 IBS: 0.2194256628341777
Fold 3 IBS: 0.16253411822788286
Fold 4 IBS: 0.15761805594663011
Fold 5 IBS: 0.23407720659165393
[I 2024-04-14 13:01:02,545] Trial 53 finished with value: 0.1874790917511242 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 186, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7476134901339011, 'min_weight_fraction_leaf': 0.08146609479604885}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15667446587656828
Fold 2 IBS: 0.22259170068516151
Fold 3 IBS: 0.16027821329780895
Fold 4 IBS: 0.149898570567792
Fold 5 IBS: 0.23658634721466398
[I 2024-04-14 13:01:04,010] Trial 54 finished with value: 0.18520585952839894 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 210, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8622593333790171, 'min_weight_fraction_leaf': 0.03984454525206663}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16327473957676134
Fold 2 IBS: 0.23793741115902334
Fold 3 IBS: 0.15053184132363184
Fold 4 IBS: 0.14316701516036756
Fold 5 IBS: 0.24831073015833066
[I 2024-04-14 13:01:04,908] Trial 55 finished with value: 0.18864434747562292 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 114, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5835542910574787, 'min_weight_fraction_leaf': 0.05960637598557158}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15801374020627632
Fold 2 IBS: 0.22263594010741847
Fold 3 IBS: 0.1601823126838589
Fold 4 IBS: 0.14861579443004172
Fold 5 IBS: 0.23891130968989982
[I 2024-04-14 13:01:07,059] Trial 56 finished with value: 0.18567181942349903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 305, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6487362571584319, 'min_weight_fraction_leaf': 0.01779271930046888}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.17721006055316293
Fold 2 IBS: 0.20739633530595358
Fold 3 IBS: 0.1750934765714907
Fold 4 IBS: 0.17633166264985042
Fold 5 IBS: 0.22245946466694386
[I 2024-04-14 13:01:09,002] Trial 57 finished with value: 0.1916981999494803 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 262, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7062791073111182, 'min_weight_fraction_leaf': 0.10871806767374792}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16847265453919935
Fold 2 IBS: 0.2137302894041514
Fold 3 IBS: 0.17041856076770165
Fold 4 IBS: 0.16994282276424133
Fold 5 IBS: 0.22561414584176495
[I 2024-04-14 13:01:10,253] Trial 58 finished with value: 0.18963569466341174 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 154, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.1414379463860349}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1520987816995429
Fold 2 IBS: 0.22538594222039326
Fold 3 IBS: 0.15848369927445602
Fold 4 IBS: 0.14522784389823484
Fold 5 IBS: 0.2376527406797429
[I 2024-04-14 13:01:11,737] Trial 59 finished with value: 0.18376980155447398 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 177, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8101006803604213, 'min_weight_fraction_leaf': 5.7497736778936576e-05}. Best is trial 31 with value: 0.18273405926537079.

Fold 1 IBS: 0.1667377112785077
Fold 2 IBS: 0.21139971336963634
Fold 3 IBS: 0.16719610422116873
Fold 4 IBS: 0.16444742789928804
Fold 5 IBS: 0.22433929414894066
[I 2024-04-14 13:01:13,416] Trial 60 finished with value: 0.18682405018350828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 233, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9208992051748564, 'min_weight_fraction_leaf': 0.04194475489343627}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15339272842252286
Fold 2 IBS: 0.22875929926363106
Fold 3 IBS: 0.15824814328892167
Fold 4 IBS: 0.14551047397439773
Fold 5 IBS: 0.23751514003516505
[I 2024-04-14 13:01:14,769] Trial 61 finished with value: 0.1846851569969277 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 182, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8077284317253199, 'min_weight_fraction_leaf': 0.0006022708509563421}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1531401068257667
Fold 2 IBS: 0.22284906609817628
Fold 3 IBS: 0.15962162064637261
Fold 4 IBS: 0.14675610783249
Fold 5 IBS: 0.23583191058017725
[I 2024-04-14 13:01:16,354] Trial 62 finished with value: 0.18363976239659657 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 203, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8625178350822468, 'min_weight_fraction_leaf': 0.01696754675050992}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1610834021733162
Fold 2 IBS: 0.22086338525240415
Fold 3 IBS: 0.16236228725378696
Fold 4 IBS: 0.1515522563818741
Fold 5 IBS: 0.23680568002031074
[I 2024-04-14 13:01:17,998] Trial 63 finished with value: 0.18653340221633843 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 207, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8622451667885025, 'min_weight_fraction_leaf': 0.06810442573344055}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15409680839983858
Fold 2 IBS: 0.2246057860471813
Fold 3 IBS: 0.15853349670725211
Fold 4 IBS: 0.14772663167931482
Fold 5 IBS: 0.23906549765623225
[I 2024-04-14 13:01:20,145] Trial 64 finished with value: 0.18480564409796382 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 286, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9774551144004276, 'min_weight_fraction_leaf': 0.032811899933904855}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15876817257161227
Fold 2 IBS: 0.2337194086132522
Fold 3 IBS: 0.15156379070347947
Fold 4 IBS: 0.1436732108857659
Fold 5 IBS: 0.24518317596592573
[I 2024-04-14 13:01:22,112] Trial 65 finished with value: 0.1865815517480071 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 254, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9556644596936762, 'min_weight_fraction_leaf': 0.04883609768643495}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15479653570424312
Fold 2 IBS: 0.22540014506157335
Fold 3 IBS: 0.15728703741772068
Fold 4 IBS: 0.14646377091078305
Fold 5 IBS: 0.23433900686523373
[I 2024-04-14 13:01:23,980] Trial 66 finished with value: 0.18365729919191082 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 228, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9061006292109164, 'min_weight_fraction_leaf': 0.01908254070151858}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1726183642606273
Fold 2 IBS: 0.21020146818228028
Fold 3 IBS: 0.17257201371972314
Fold 4 IBS: 0.16617980308164432
Fold 5 IBS: 0.22155798482236494
[I 2024-04-14 13:01:24,906] Trial 67 finished with value: 0.188625926813328 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7664140967912066, 'min_weight_fraction_leaf': 0.07799415348547353}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15906353773281454
Fold 2 IBS: 0.22118269249527334
Fold 3 IBS: 0.16077385786347104
Fold 4 IBS: 0.15116824719229166
Fold 5 IBS: 0.23645145511246304
[I 2024-04-14 13:01:26,503] Trial 68 finished with value: 0.18572795807926273 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8429328898653983, 'min_weight_fraction_leaf': 0.06106194405494651}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15312391663953767
Fold 2 IBS: 0.22710307424261464
Fold 3 IBS: 0.15977752814265386
Fold 4 IBS: 0.14492224287947064
Fold 5 IBS: 0.23636375415289873
[I 2024-04-14 13:01:27,839] Trial 69 finished with value: 0.18425810321143513 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 157, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8699683499475267, 'min_weight_fraction_leaf': 0.014982379758998384}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1698912280155125
Fold 2 IBS: 0.21328832848113072
Fold 3 IBS: 0.1718396678417333
Fold 4 IBS: 0.17209395401833588
Fold 5 IBS: 0.22630147205526466
[I 2024-04-14 13:01:29,643] Trial 70 finished with value: 0.1906829300823954 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 219, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6441662068912183, 'min_weight_fraction_leaf': 0.034967060084702115}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15429001961275463
Fold 2 IBS: 0.22596034800169917
Fold 3 IBS: 0.15684431253808698
Fold 4 IBS: 0.14640686810147274
Fold 5 IBS: 0.23498409076302662
[I 2024-04-14 13:01:31,803] Trial 71 finished with value: 0.18369712780340802 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9109992173441673, 'min_weight_fraction_leaf': 0.017379344628651688}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15721123499115444
Fold 2 IBS: 0.22420625053604556
Fold 3 IBS: 0.1609330693357165
Fold 4 IBS: 0.14884076327365278
Fold 5 IBS: 0.23831241859402336
[I 2024-04-14 13:01:34,008] Trial 72 finished with value: 0.18590074734611856 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 271, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8855407360417882, 'min_weight_fraction_leaf': 0.051245242416170705}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.15277218005266113
Fold 2 IBS: 0.2240665791099297
Fold 3 IBS: 0.15811031095474104
Fold 4 IBS: 0.14680663239264824
Fold 5 IBS: 0.23265508413820515
[I 2024-04-14 13:01:35,639] Trial 73 finished with value: 0.18288215732963703 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9973771850648571, 'min_weight_fraction_leaf': 0.018555322731373097}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16297491172262576
Fold 2 IBS: 0.22062900217624173
Fold 3 IBS: 0.16274476161358134
Fold 4 IBS: 0.15453446188660103
Fold 5 IBS: 0.23396466160210022
[I 2024-04-14 13:01:37,077] Trial 74 finished with value: 0.18696955980023003 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9957605480055599, 'min_weight_fraction_leaf': 0.09026272413315149}. Best is trial 31 with value: 0.18273405926537079.

Fold 1 IBS: 0.15528894958073775
Fold 2 IBS: 0.21984680247745453
Fold 3 IBS: 0.15900685739714732
Fold 4 IBS: 0.14859781459794244
Fold 5 IBS: 0.23493449886479167
[I 2024-04-14 13:01:38,731] Trial 75 finished with value: 0.18353498458361475 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 162, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9532062735167633, 'min_weight_fraction_leaf': 0.030316433196080697}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1635808951920651
Fold 2 IBS: 0.20759879371938625
Fold 3 IBS: 0.16635458220500324
Fold 4 IBS: 0.1603635273963648
Fold 5 IBS: 0.2261410117149779
[I 2024-04-14 13:01:40,000] Trial 76 finished with value: 0.18480776204555946 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 128, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9660526429770501, 'min_weight_fraction_leaf': 0.0368089845979563}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.158751943435866
Fold 2 IBS: 0.22270261737826613
Fold 3 IBS: 0.1599837271324172
Fold 4 IBS: 0.15154393792606322
Fold 5 IBS: 0.2359564987679915
[I 2024-04-14 13:01:41,655] Trial 77 finished with value: 0.18578774492812083 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 161, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9584440636641491, 'min_weight_fraction_leaf': 0.05854659326851727}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1778233184873607
Fold 2 IBS: 0.2087412211571078
Fold 3 IBS: 0.17584802592926493
Fold 4 IBS: 0.17838177300207506
Fold 5 IBS: 0.22167925055265206
[I 2024-04-14 13:01:43,113] Trial 78 finished with value: 0.1924947178256921 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 142, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9995542851198572, 'min_weight_fraction_leaf': 0.1606840994476136}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.16510953096154146
Fold 2 IBS: 0.2159639911025736
Fold 3 IBS: 0.16350160380457593
Fold 4 IBS: 0.16258843264187522
Fold 5 IBS: 0.22782948351147597
[I 2024-04-14 13:01:44,885] Trial 79 finished with value: 0.18699860840440846 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 173, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.074977184471631}. Best is trial 31 with value: 0.18273405926537079.
Fold 1 IBS: 0.1512442018000724
Fold 2 IBS: 0.21632787605364548
Fold 3 IBS: 0.15935480265871577
Fold 4 IBS: 0.14734065466186042
Fold 5 IBS: 0.23740446748885152
[I 2024-04-14 13:01:45,507] Trial 80 finished with value: 0.18233440053262912 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 54, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9404771836526359, 'min_weight_fraction_leaf': 0.028434588483853534}. Best is trial 80 with value: 0.18233440053262912.
Fold 1 IBS: 0.15814675249772703
Fold 2 IBS: 0.20623206140937875
Fold 3 IBS: 0.15264146144969137
Fold 4 IBS: 0.1478349558608874
Fold 5 IBS: 0.237417758357945
[I 2024-04-14 13:01:45,945] Trial 81 finished with value: 0.1804545979151259 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9277129016361768, 'min_weight_fraction_leaf': 0.026154087319717897}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.17306642243599527
Fold 2 IBS: 0.20774766683862186
Fold 3 IBS: 0.15278129851922917
Fold 4 IBS: 0.14517727608090308
Fold 5 IBS: 0.23467651295982736
[I 2024-04-14 13:01:46,169] Trial 82 finished with value: 0.18268983536691535 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 8, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9333539319914951, 'min_weight_fraction_leaf': 0.009939968541497122}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.18889776607631728
Fold 2 IBS: 0.20425961405428697
Fold 3 IBS: 0.18068709507786104
Fold 4 IBS: 0.1575612464070665
Fold 5 IBS: 0.2988849748340575
[I 2024-04-14 13:01:46,332] Trial 83 finished with value: 0.20605813928991784 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 1, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.934514818741637, 'min_weight_fraction_leaf': 0.00812664677099249}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.20908231309181677
Fold 2 IBS: 0.21608557742548307
Fold 3 IBS: 0.20454948491486202
Fold 4 IBS: 0.22134543931687387
Fold 5 IBS: 0.21740554176549653
[I 2024-04-14 13:01:46,724] Trial 84 finished with value: 0.21369367130290645 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 17, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9006247216886643, 'min_weight_fraction_leaf': 0.4361528058995905}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16494947752218342
Fold 2 IBS: 0.2122691619956505
Fold 3 IBS: 0.16945255650930177
Fold 4 IBS: 0.16912977245388428
Fold 5 IBS: 0.22786981847875684
[I 2024-04-14 13:01:47,355] Trial 85 finished with value: 0.18873415739195537 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 46, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9330414647675185, 'min_weight_fraction_leaf': 0.19956019852118093}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15434181648270756
Fold 2 IBS: 0.21167748367587746
Fold 3 IBS: 0.15913412492995563
Fold 4 IBS: 0.14963242372193358
Fold 5 IBS: 0.23398242314303047
[I 2024-04-14 13:01:47,851] Trial 86 finished with value: 0.18175365439070096 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 35, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9775574041795743, 'min_weight_fraction_leaf': 0.025436198783908143}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15755954419068613
Fold 2 IBS: 0.20459180020629983
Fold 3 IBS: 0.15861950523187016
Fold 4 IBS: 0.15057932275187044
Fold 5 IBS: 0.23753856534808457
[I 2024-04-14 13:01:48,253] Trial 87 finished with value: 0.18177774754576223 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9857208572979869, 'min_weight_fraction_leaf': 0.047412450094911254}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.1713190051621762
Fold 2 IBS: 0.20663814704028693
Fold 3 IBS: 0.1719571649593095
Fold 4 IBS: 0.17201855450568557
Fold 5 IBS: 0.22773034399499317
[I 2024-04-14 13:01:48,691] Trial 88 finished with value: 0.18993264313249028 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 26, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9755600293092102, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15551362179043182
Fold 2 IBS: 0.21678382942929414
Fold 3 IBS: 0.15983542734498854
Fold 4 IBS: 0.1516385605702977
Fold 5 IBS: 0.2377747929425704
[I 2024-04-14 13:01:49,494] Trial 89 finished with value: 0.18430924641551652 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 72, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.93970419245073, 'min_weight_fraction_leaf': 0.05032187607137201}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.1753851382435368

Fold 2 IBS: 0.2063565222747697
Fold 3 IBS: 0.17003588715814522
Fold 4 IBS: 0.17777116278712887
Fold 5 IBS: 0.22022528125047466
[I 2024-04-14 13:01:49,962] Trial 90 finished with value: 0.18995479834281107 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 37, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9997596356740963, 'min_weight_fraction_leaf': 0.3292134206382089}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15458861367684845
Fold 2 IBS: 0.21750786042177303
Fold 3 IBS: 0.15767300132028467
Fold 4 IBS: 0.15084191777051614
Fold 5 IBS: 0.23638504482176886
[I 2024-04-14 13:01:50,617] Trial 91 finished with value: 0.18339928760223825 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.916420719730876, 'min_weight_fraction_leaf': 0.026018345165367416}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16926244801703716
Fold 2 IBS: 0.2066676766691297
Fold 3 IBS: 0.17008790964473064
Fold 4 IBS: 0.1820524596700145
Fold 5 IBS: 0.22610108366092097
[I 2024-04-14 13:01:50,943] Trial 92 finished with value: 0.19083431553236657 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 17, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.964752731171567, 'min_weight_fraction_leaf': 0.01250391523792243}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15809148003468684
Fold 2 IBS: 0.20958670734958446
Fold 3 IBS: 0.15840991467714924
Fold 4 IBS: 0.1507811899477792
Fold 5 IBS: 0.23549291506179715
[I 2024-04-14 13:01:51,411] Trial 93 finished with value: 0.18247244141419938 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 35, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8884053060973408, 'min_weight_fraction_leaf': 0.041256881684444274}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15797743739508543
Fold 2 IBS: 0.2116993770730125
Fold 3 IBS: 0.161819653131566
Fold 4 IBS: 0.15392702939042302
Fold 5 IBS: 0.23712263715887472
[I 2024-04-14 13:01:51,847] Trial 94 finished with value: 0.18450922682979234 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 36, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8932538311633453, 'min_weight_fraction_leaf': 0.04536309386296798}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16268328889908273
Fold 2 IBS: 0.2137299364042898
Fold 3 IBS: 0.16175964623736974
Fold 4 IBS: 0.15947622173026346
Fold 5 IBS: 0.23382367473762608
[I 2024-04-14 13:01:52,585] Trial 95 finished with value: 0.18629455360172636 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 71, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9798682573522689, 'min_weight_fraction_leaf': 0.08848051751764807}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.1738378029124256
Fold 2 IBS: 0.20291251147912878
Fold 3 IBS: 0.16988018099799151
Fold 4 IBS: 0.17884930227942303
Fold 5 IBS: 0.2279595208667826
[I 2024-04-14 13:01:52,896] Trial 96 finished with value: 0.1906878637071503 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 16, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9286121890215923, 'min_weight_fraction_leaf': 0.07027555068916512}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16334795326480145
Fold 2 IBS: 0.21098948637616388
Fold 3 IBS: 0.16348277314048718
Fold 4 IBS: 0.16036816603309584
Fold 5 IBS: 0.2349696440519836
[I 2024-04-14 13:01:53,522] Trial 97 finished with value: 0.1866316045733064 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 54, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9433581891891712, 'min_weight_fraction_leaf': 0.05578633304726292}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.16099953749641463
Fold 2 IBS: 0.20578172388126173
Fold 3 IBS: 0.15926165405907902
Fold 4 IBS: 0.15308207272671334
Fold 5 IBS: 0.23653164161080956
[I 2024-04-14 13:01:54,009] Trial 98 finished with value: 0.18313132595485565 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 31, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8905712013384897, 'min_weight_fraction_leaf': 0.04141197253924776}. Best is trial 81 with value: 0.1804545979151259.
Fold 1 IBS: 0.15246893987163504
Fold 2 IBS: 0.21792955284744994
Fold 3 IBS: 0.15667467626084478
Fold 4 IBS: 0.1515829511569252
Fold 5 IBS: 0.23629786824582152
[I 2024-04-14 13:01:54,613] Trial 99 finished with value: 0.1829907976765353 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 43, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8472749022928616, 'min_weight_fraction_leaf': 0.02766234914998976}. Best is trial 81 with value: 0.1804545979151259.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.1804545979151259], datetime_start=datetime.datetime(2024, 4, 14, 13, 1, 45, 521867), datetime_complete=datetime.datetime(2024, 4, 14, 13, 1, 45, 944819), params={'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 27, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9277129016361768, 'min_weight_fraction_leaf': 0.026154087319717897}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=81, value=None)


* Best Score for IBS:
 0.1804545979151259

In [221]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [222]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.848
train_ibs:  0.18

#### Test

In [223]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [224]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=10, max_features=None, max_leaf_nodes=17,
                   max_samples=0.7657259832611387, min_samples_leaf=1,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.007259167100140962,
                   n_estimators=358, random_state=123, warm_start=True)

C-index score: 0.61

ExtraSurvivalTrees(max_depth=5, max_leaf_nodes=17,
                   max_samples=0.9277129016361768, min_samples_leaf=1,
                   min_samples_split=16,
                   min_weight_fraction_leaf=0.026154087319717897,
                   n_estimators=27, oob_score=True, random_state=123)

IBS: 0.23

In [225]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [226]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 13:01:55,457] A new study created in memory with name: no-name-06736fcc-37e4-4f39-acb6-6f63d46f2273

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:09,208] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:16,625] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:23,921] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:36,888] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:41,632] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:42,706] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:53,538] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:56,956] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:02:57,353] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 13:03:29,227] Trial 9 finished with value: 0.7308620854904466 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 13:04:16,082] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:37:34,968] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 13:38:11,291] Trial 12 finished with value: 0.7099172779859281 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 13:47:23,712] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:28:28,155] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:03,715] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:30:17,648] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:35:34,000] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:19,490] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:21,286] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:36:39,952] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:37:17,675] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5892018779342723
[I 2024-04-14 14:38:00,964] Trial 22 finished with value: 0.7242619704042982 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:38:30,979] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:38:59,662] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:39:16,214] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:39:53,321] Trial 26 finished with value: 0.5440329476861168 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:40:31,182] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:00,089] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:18,455] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:41:41,348] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:42:34,126] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:43:18,941] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:43:51,399] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:44:38,418] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:44:46,407] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:45:43,908] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:45:46,265] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:05,829] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:46:34,255] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:16,966] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 14:47:17,143] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:47:22,388] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:27,577] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:40,662] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:46,363] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:47:51,001] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:09,111] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:18,206] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:41,811] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:43,554] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:48:43,924] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:44,334] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:48:49,716] Trial 53 finished with value: 0.6986656149072055 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:55,773] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:48:56,501] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:46,285] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:49,378] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:49:54,843] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:39,918] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:54,376] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:50:55,756] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:51:03,166] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:51:04,346] Trial 63 finished with value: 0.7163384910196757 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:06,567] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:51:11,751] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:05,394] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:06,073] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:17,185] Trial 68 finished with value: 0.6328510949834479 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:18,105] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:52:55,261] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:52:55,472] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 14:52:55,789] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:04,074] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:04,379] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:06,822] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:26,380] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:53:27,224] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:14,490] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:20,493] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:36,060] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 14:54:36,221] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:54:36,451] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:54:37,015] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:23,479] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5

Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:23,731] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:24,720] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:25,593] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:55:26,636] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:15,340] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:20,649] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:56:21,316] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:21,763] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:21,976] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:22,663] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 14:56:23,767] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7308620854904466.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7769607843137255
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 14:56:26,590] Trial 96 finished with value: 0.7397496129726304 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7397496129726304.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:29,568] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7397496129726304.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 14:56:33,370] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7397496129726304.

[I 2024-04-14 14:56:33,853] A new study created in memory with name: no-name-f7f42825-183e-45e9-9cde-32f43dd3b80c

Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.7433035714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6220657276995305
[I 2024-04-14 14:56:33,811] Trial 99 finished with value: 0.7362621731256239 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7397496129726304.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7397496129726304], datetime_start=datetime.datetime(2024, 4, 14, 14, 56, 23, 774492), datetime_complete=datetime.datetime(2024, 4, 14, 14, 56, 26, 589400), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7397496129726304

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:56:52,930] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:57:02,333] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:57:10,493] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:57:22,286] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:57:27,141] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:57:28,364] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:57:40,744] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 14:57:44,025] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 14:57:44,535] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21300086551681388
Fold 2 IBS: 0.22130101345683229
Fold 3 IBS: 0.20356009608364972
Fold 4 IBS: 0.223737338897546
Fold 5 IBS: 0.21796045724591795
[I 2024-04-14 14:58:14,533] Trial 9 finished with value: 0.21591195424015197 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-14 14:59:01,335] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 14:59:54,116] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.2138394660896716
Fold 2 IBS: 0.22156451448592526
Fold 3 IBS: 0.20440536466519849
Fold 4 IBS: 0.22459255869133457
Fold 5 IBS: 0.2180987264506579
[I 2024-04-14 15:00:39,657] Trial 12 finished with value: 0.21650012607655755 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-14 15:01:00,978] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:01:41,790] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:02:14,620] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:02:34,193] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:03:17,100] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:03:41,138] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:03:45,098] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:04:27,145] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-14 15:05:15,664] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591195424015197.
Fold 1 IBS: 0.21274017409214452
Fold 2 IBS: 0.22141099171063053

Fold 3 IBS: 0.20335117088275953
Fold 4 IBS: 0.22312834911084292
Fold 5 IBS: 0.2179288192033457
[I 2024-04-14 15:06:19,282] Trial 22 finished with value: 0.21571190099994464 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:07:06,004] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:07:38,344] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:08:05,525] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:08:51,307] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:08:56,191] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:09:11,573] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:09:49,534] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:10:06,494] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-14 15:10:58,431] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.2214475600367709
Fold 3 IBS: 0.20359712028328325
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.2179179888442139
[I 2024-04-14 15:11:50,140] Trial 32 finished with value: 0.21590238864988304 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:12:38,465] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:13:19,585] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:13:32,369] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:14:23,331] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:14:24,908] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:14:57,945] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:15:35,119] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:16:07,493] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.2133737249398968
Fold 2 IBS: 0.22149810300618933
Fold 3 IBS: 0.2039253275544007
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21807108026974395
[I 2024-04-14 15:16:59,520] Trial 41 finished with value: 0.21616520869623862 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21306076700870485
Fold 2 IBS: 0.22147749486211882
Fold 3 IBS: 0.20359741169509465
Fold 4 IBS: 0.2235915022761023
Fold 5 IBS: 0.2179320496417716
[I 2024-04-14 15:18:03,398] Trial 42 finished with value: 0.21593184509675845 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:19:00,526] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:19:44,358] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21364321685567275
Fold 2 IBS: 0.22142448507128704
Fold 3 IBS: 0.20425326961779583
Fold 4 IBS: 0.22431353914927907
Fold 5 IBS: 0.21808668272206289
[I 2024-04-14 15:20:21,913] Trial 45 finished with value: 0.21634423868321956 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:21:04,385] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:21:25,416] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:21:25,732] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:21:35,763] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:22:24,171] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-14 15:23:13,484] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:23:58,494] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21571190099994464.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22136281903923083
Fold 3 IBS: 0.20241247448818608
Fold 4 IBS: 0.2219411019366781
Fold 5 IBS: 0.21777624808878387
[I 2024-04-14 15:24:41,087] Trial 53 finished with value: 0.21504716009286912 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:25:28,132] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:26:06,954] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:26:38,992] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:27:20,958] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:28:16,709] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:28:53,998] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:29:21,836] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:30:01,044] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-14 15:30:54,402] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:31:46,439] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.2129979350841566
Fold 2 IBS: 0.2212280479447545
Fold 3 IBS: 0.20348955609618546
Fold 4 IBS: 0.22374381655427747
Fold 5 IBS: 0.21801501746323726
[I 2024-04-14 15:32:39,617] Trial 64 finished with value: 0.21589487462852225 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:33:40,682] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9189183326723824, 'learning_rate': 0.011096659410828054, 'dropout_rate': 0.15744491147958184, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 1.1124245211667088, 'min_weight_fraction_leaf': 0.21730511044745757, 'max_features': 'log2', 'min_impurity_decrease': 4.00127934674698e-06, 'validation_fraction': 0.998233299727277, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:34:42,052] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9998769156045215, 'learning_rate': 0.008782667792366316, 'dropout_rate': 0.12972298735589705, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.7134499429690735, 'min_weight_fraction_leaf': 0.19311178079767077, 'max_features': 'log2', 'min_impurity_decrease': 1.142816958470248e-06, 'validation_fraction': 0.9729459657934212, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:35:28,216] Trial 67 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8640185330574577, 'learning_rate': 0.015997347081349804, 'dropout_rate': 0.18369926136498038, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.3491418081323188, 'max_features': 'log2', 'min_impurity_decrease': 2.9677822215329938e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:36:13,613] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8052124560044422, 'learning_rate': 0.027698938792055094, 'dropout_rate': 0.3183724976622295, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2920470355270516, 'min_weight_fraction_leaf': 0.16901934601360036, 'max_features': 'log2', 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:37:03,647] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.022661198063658503, 'dropout_rate': 0.15177883474257473, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 5.781491720141274, 'min_weight_fraction_leaf': 0.3709922257167516, 'max_features': 'sqrt', 'min_impurity_decrease': 7.4830347845666965e-06, 'validation_fraction': 0.8281891917990171, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:37:17,550] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.0031189928817958587, 'dropout_rate': 0.5905404972480945, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.3188535514715946, 'max_features': 'log2', 'min_impurity_decrease': 1.1928111158414438e-06, 'validation_fraction': 0.8771634368243094, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21281861880669364
Fold 2 IBS: 0.22147036875244297
Fold 3 IBS: 0.20342132281483385
Fold 4 IBS: 0.223306383872192
Fold 5 IBS: 0.21789594373420879
[I 2024-04-14 15:38:14,421] Trial 71 finished with value: 0.21578252759607425 and parameters: {'subsample': 0.9303280421214478, 'learning_rate': 0.00867928513859834, 'dropout_rate': 0.2114071609099808, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.2830289864785245, 'max_features': 'auto', 'min_impurity_decrease': 2.8309589446706505e-07, 'validation_fraction': 0.9341930519363522, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21264377959603953
Fold 2 IBS: 0.22145456521669551
Fold 3 IBS: 0.20325758942159297
Fold 4 IBS: 0.22308382132272495
Fold 5 IBS: 0.21784549875213116
[I 2024-04-14 15:39:09,307] Trial 72 finished with value: 0.2156570508618368 and parameters: {'subsample': 0.9301573375470014, 'learning_rate': 0.011204053201905661, 'dropout_rate': 0.23553989617782028, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004820830813732985, 'min_weight_fraction_leaf': 0.2737805456341038, 'max_features': 'auto', 'min_impurity_decrease': 3.6620964530112787e-07, 'validation_fraction': 0.9737030143041076, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:39:15,082] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9298981705927085, 'learning_rate': 0.010195438618282406, 'dropout_rate': 0.23585972620145051, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.27451237461517963, 'max_features': 'auto', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9203017882586108, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:40:07,758] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8776896116214433, 'learning_rate': 0.014494378748744683, 'dropout_rate': 0.28898081809802034, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.37345543486587357, 'min_weight_fraction_leaf': 0.20816976567601184, 'max_features': 'auto', 'min_impurity_decrease': 2.611979113511538e-07, 'validation_fraction': 0.9762608022070116, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:40:48,982] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8972316596616344, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.34962098273262876, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 1.2014771498456696, 'min_weight_fraction_leaf': 0.2901314285672209, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.8483032778113153, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:41:37,842] Trial 76 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9427845846760775, 'learning_rate': 0.040991201384238105, 'dropout_rate': 0.2075245331259492, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.934389124127465, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.

Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:42:17,047] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6527746876723795, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.2556920821676466, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.5896250392603071, 'min_weight_fraction_leaf': 0.22988050749684658, 'max_features': 1, 'min_impurity_decrease': 1.4995945809430595e-05, 'validation_fraction': 0.8950354974332698, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:43:04,632] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.1812306278517568, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.2911423302160594, 'min_weight_fraction_leaf': 0.2568526167512072, 'max_features': 'auto', 'min_impurity_decrease': 6.881976645342321e-07, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:43:43,342] Trial 79 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9711804489125221, 'learning_rate': 0.008977463652006058, 'dropout_rate': 0.10045868399742758, 'n_estimators': 408, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8456191926639984, 'min_weight_fraction_leaf': 0.28189763106059557, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982937136983077, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:44:24,743] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8535702305805324, 'learning_rate': 0.013008132772511784, 'dropout_rate': 0.23306750004092583, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 5.501302028342128e-06, 'validation_fraction': 0.8033655207154786, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21328441825357652
Fold 2 IBS: 0.22144767701711832
Fold 3 IBS: 0.2038537340831823
Fold 4 IBS: 0.22389243027837222
Fold 5 IBS: 0.2179733655894191
[I 2024-04-14 15:45:12,323] Trial 81 finished with value: 0.2160903250443337 and parameters: {'subsample': 0.9784145478438975, 'learning_rate': 0.00415560855116564, 'dropout_rate': 0.16880106444935875, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.025432112194026565, 'min_weight_fraction_leaf': 0.32661813483692875, 'max_features': 'auto', 'min_impurity_decrease': 4.1696350773463576e-07, 'validation_fraction': 0.9618626661496192, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21313529710939624
Fold 2 IBS: 0.2214959526155037
Fold 3 IBS: 0.20372727007596517
Fold 4 IBS: 0.2237011172817945
Fold 5 IBS: 0.2179583294148407
[I 2024-04-14 15:46:10,459] Trial 82 finished with value: 0.21600359329950006 and parameters: {'subsample': 0.9292256563323309, 'learning_rate': 0.005938788819943272, 'dropout_rate': 0.20112867357024375, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.01786403260693046, 'min_weight_fraction_leaf': 0.2694686872154886, 'max_features': 'auto', 'min_impurity_decrease': 1.4936787149467238e-07, 'validation_fraction': 0.9322976146952479, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:47:12,890] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.997030710636302, 'learning_rate': 0.017347504146358047, 'dropout_rate': 0.12875284011164154, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.42770746896829764, 'min_weight_fraction_leaf': 0.30582130984370137, 'max_features': 'auto', 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.9763733963887893, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:47:55,717] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9699238743776749, 'learning_rate': 0.009959638401621597, 'dropout_rate': 0.305574256636177, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.262145494050454, 'min_weight_fraction_leaf': 0.23583033266274414, 'max_features': 'auto', 'min_impurity_decrease': 7.781008937605048e-07, 'validation_fraction': 0.8657748182811282, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:48:37,486] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9039638029331271, 'learning_rate': 0.0037679534600800306, 'dropout_rate': 0.15830961459250859, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.9670160633661875, 'min_weight_fraction_leaf': 0.22273143316885707, 'max_features': 'auto', 'min_impurity_decrease': 1.549053164841614e-07, 'validation_fraction': 0.9112741324892579, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:49:25,448] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9330830727147826, 'learning_rate': 0.00786307119428408, 'dropout_rate': 0.2679588154714714, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.6251717679448328, 'min_weight_fraction_leaf': 0.34273533762708086, 'max_features': 'auto', 'min_impurity_decrease': 1.94114481416941e-06, 'validation_fraction': 0.9710286882527703, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:49:37,454] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8202668472614781, 'learning_rate': 0.012273440310927393, 'dropout_rate': 0.49308788025511585, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.2337543925553926, 'min_weight_fraction_leaf': 0.2565004395308679, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00023480828622143336, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:50:08,914] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8800231052433968, 'learning_rate': 0.015424283294721588, 'dropout_rate': 0.20093805843087115, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.351539840282731, 'min_weight_fraction_leaf': 0.28958635214901884, 'max_features': 'auto', 'min_impurity_decrease': 2.329078771156988e-07, 'validation_fraction': 0.939344740485312, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:50:43,436] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9819209167757807, 'learning_rate': 0.020219241696711625, 'dropout_rate': 0.2428130031440519, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.5765552790097783, 'min_weight_fraction_leaf': 0.18311512377308206, 'max_features': 'auto', 'min_impurity_decrease': 5.126619309081385e-07, 'validation_fraction': 0.8909484827188601, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 15:50:53,845] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6196341847942087, 'learning_rate': 0.006689654877596743, 'dropout_rate': 0.8458602043820649, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.5932807780543458, 'min_weight_fraction_leaf': 0.20408203732171998, 'max_features': None, 'min_impurity_decrease': 0.0012769637169882761, 'validation_fraction': 0.8340062857341481, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21354560132435954
Fold 2 IBS: 0.22152311434279084
Fold 3 IBS: 0.20412434040298866
Fold 4 IBS: 0.22420753466621227
Fold 5 IBS: 0.21802246276346793
[I 2024-04-14 15:51:35,816] Trial 91 finished with value: 0.21628461069996385 and parameters: {'subsample': 0.9519061011910324, 'learning_rate': 0.003286435592844394, 'dropout_rate': 0.21804174357954037, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.037605992845398076, 'min_weight_fraction_leaf': 0.2518132577788482, 'max_features': 'auto', 'min_impurity_decrease': 2.167221721970957e-07, 'validation_fraction': 0.9509830628877887, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21228604216711322
Fold 2 IBS: 0.2210505145073144
Fold 3 IBS: 0.2029838755299775
Fold 4 IBS: 0.22264411729074315
Fold 5 IBS: 0.21786028421349793
[I 2024-04-14 15:52:20,080] Trial 92 finished with value: 0.21536496674172928 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.007580646944168386, 'dropout_rate': 0.1248497169759688, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.04676515809970792, 'min_weight_fraction_leaf': 0.24126121445524454, 'max_features': 'auto', 'min_impurity_decrease': 1.41179952896197e-07, 'validation_fraction': 0.9803593350541797, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 15:53:10,223] Trial 93 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5074494668833536, 'learning_rate': 0.010358551431621075, 'dropout_rate': 0.11851429853955366, 'n_estimators': 492, 'criterion': 'squared_error', 'ccp_alpha': 0.386541225183722, 'min_weight_fraction_leaf': 0.28001284523923786, 'max_features': 'auto', 'min_impurity_decrease': 1.2653383309827397e-07, 'validation_fraction': 0.979813726530939, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 15:53:59,251] Trial 94 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4696467705452906, 'learning_rate': 0.012513597466310221, 'dropout_rate': 0.1368992177740068, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.8568623495412244, 'min_weight_fraction_leaf': 0.3103128063965126, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9107078483961247, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21395579375917034
Fold 2 IBS: 0.22156669674580007
Fold 3 IBS: 0.2045252270179711
Fold 4 IBS: 0.22472200503768064
Fold 5 IBS: 0.21811291772715782
[I 2024-04-14 15:54:51,552] Trial 95 finished with value: 0.216576528057556 and parameters: {'subsample': 0.5795813627066926, 'learning_rate': 0.0011500826880246348, 'dropout_rate': 0.15371309107333708, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.12848433868181566, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 'auto', 'min_impurity_decrease': 2.9339240471384527e-07, 'validation_fraction': 0.9999690268176494, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 15:55:44,411] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5510219457804204, 'learning_rate': 0.017505885682568743, 'dropout_rate': 0.1723932907588553, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5519118282179587, 'min_weight_fraction_leaf': 0.27203175602825513, 'max_features': 'log2', 'min_impurity_decrease': 1.4367172438359607e-07, 'validation_fraction': 0.6783354896202222, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-14 15:56:28,966] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.529148797369217, 'learning_rate': 0.009070651237536868, 'dropout_rate': 0.22319654132501116, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 1.0614519036494967, 'min_weight_fraction_leaf': 0.14961516639891254, 'max_features': 'auto', 'min_impurity_decrease': 1.3572955342683883e-06, 'validation_fraction': 0.9307441942928913, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 53 with value: 0.21504716009286912.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 15:57:39,819] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9166190498458621, 'learning_rate': 0.005876010120169104, 'dropout_rate': 0.1928526990947004, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.2351987698633502, 'min_weight_fraction_leaf': 0.24763944144203606, 'max_features': 1, 'min_impurity_decrease': 3.0003509704748335e-06, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 53 with value: 0.21504716009286912.

Fold 1 IBS: 0.21252354672208404
Fold 2 IBS: 0.22052727078684145
Fold 3 IBS: 0.20320794231873263
Fold 4 IBS: 0.2228335466693306
Fold 5 IBS: 0.21782914318597227
[I 2024-04-14 15:58:40,038] Trial 99 finished with value: 0.21538428993659223 and parameters: {'subsample': 0.24286963781937687, 'learning_rate': 0.01358129947690588, 'dropout_rate': 0.25496540816023416, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.004367160733265784, 'min_weight_fraction_leaf': 0.2624099419664444, 'max_features': 'auto', 'min_impurity_decrease': 5.321953542697131e-07, 'validation_fraction': 0.9620562032012763, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 53 with value: 0.21504716009286912.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.21504716009286912], datetime_start=datetime.datetime(2024, 4, 14, 15, 23, 58, 526416), datetime_complete=datetime.datetime(2024, 4, 14, 15, 24, 41, 86112), params={'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=53, value=None)


* Best Score for IBS:
 0.21504716009286912

In [227]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [228]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.74
train_ibs:  0.215

#### Test

In [229]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [230]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.612

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009625013743012712,
                                 criterion='squared_error',
                                 dropout_rate=0.1897783294507234,
                                 learning_rate=0.015420772490455037,
                                 max_features='auto', max_leaf_nodes=14,
                                 min_impurity_decrease=5.869825897765074e-07,
                                 min_samples_leaf=13, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29880213170319914,
                                 n_estimators=430, random_state=123,
                                 subsample=0.9101431135071837,
                                 validation_fraction=0.9964423942006735)

IBS: 0.22

In [231]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [232]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [233]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 15:58:53,333] A new study created in memory with name: no-name-25c9cbdd-ffab-4aeb-a664-e02699f00869

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 15:58:54,206] Trial 0 finished with value: 0.70555546693142 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.70555546693142.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 15:59:01,146] Trial 1 finished with value: 0.7053278758950055 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.70555546693142.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 15:59:02,629] Trial 2 finished with value: 0.7105795179139096 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7105795179139096.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.57981220657277
[I 2024-04-14 15:59:04,577] Trial 3 finished with value: 0.7171352291868951 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 15:59:07,490] Trial 4 finished with value: 0.7160804642607784 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:59:12,125] Trial 5 finished with value: 0.7029343480613368 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:59:14,017] Trial 6 finished with value: 0.7004833676691798 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 3 with value: 0.7171352291868951.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 15:59:14,442] Trial 7 finished with value: 0.7204471013109047 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 15:59:17,505] Trial 8 finished with value: 0.712874481994292 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7377450980392157
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 15:59:25,255] Trial 9 finished with value: 0.7127598907032302 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:59:25,605] Trial 10 finished with value: 0.63080934443503 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 15:59:25,853] Trial 11 finished with value: 0.643796357422043 and parameters: {'subsample': 0.23723133177827593, 'dropout_rate': 0.10580803679784617, 'n_estimators': 2, 'learning_rate': 0.09608989358701946}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5938967136150235
[I 2024-04-14 15:59:26,654] Trial 12 finished with value: 0.7158889143997766 and parameters: {'subsample': 0.33844938606580793, 'dropout_rate': 0.6721285244531343, 'n_estimators': 82, 'learning_rate': 0.09051861433341617}. Best is trial 7 with value: 0.7204471013109047.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 15:59:30,999] Trial 13 finished with value: 0.7240074114785057 and parameters: {'subsample': 0.12903027153499375, 'dropout_rate': 0.6941033938078734, 'n_estimators': 296, 'learning_rate': 0.03429144976267833}. Best is trial 13 with value: 0.7240074114785057.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 15:59:34,586] Trial 14 finished with value: 0.7366584738240586 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7138954389087271, 'n_estimators': 306, 'learning_rate': 0.03425729519343641}. Best is trial 14 with value: 0.7366584738240586.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 15:59:38,561] Trial 15 finished with value: 0.7359390054989564 and parameters: {'subsample': 0.10123497548852628, 'dropout_rate': 0.7873619072737351, 'n_estimators': 323, 'learning_rate': 0.016491644482656317}. Best is trial 14 with value: 0.7366584738240586.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 15:59:43,416] Trial 16 finished with value: 0.7358900302126393 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 363, 'learning_rate': 0.01003429752501748}. Best is trial 14 with value: 0.7366584738240586.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 15:59:47,309] Trial 17 finished with value: 0.717095462960302 and parameters: {'subsample': 0.20444912123366213, 'dropout_rate': 0.8343849227917408, 'n_estimators': 361, 'learning_rate': 0.015377978185239283}. Best is trial 14 with value: 0.7366584738240586.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 15:59:52,005] Trial 18 finished with value: 0.715043826044332 and parameters: {'subsample': 0.37037319144530356, 'dropout_rate': 0.7843669240092277, 'n_estimators': 430, 'learning_rate': 0.03594685807321116}. Best is trial 14 with value: 0.7366584738240586.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 15:59:55,143] Trial 19 finished with value: 0.7259192205059142 and parameters: {'subsample': 0.16691848936207518, 'dropout_rate': 0.573860614797082, 'n_estimators': 299, 'learning_rate': 0.017941064631859}. Best is trial 14 with value: 0.7366584738240586.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 15:59:59,279] Trial 20 finished with value: 0.7134411843474483 and parameters: {'subsample': 0.29019430370134297, 'dropout_rate': 0.7703393766216369, 'n_estimators': 412, 'learning_rate': 0.0016589351820883932}. Best is trial 14 with value: 0.7366584738240586.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:00:03,050] Trial 21 finished with value: 0.7330731288041887 and parameters: {'subsample': 0.11014863416226671, 'dropout_rate': 0.9754161103921428, 'n_estimators': 332, 'learning_rate': 0.015088887447797343}. Best is trial 14 with value: 0.7366584738240586.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:00:07,323] Trial 22 finished with value: 0.7367558310784401 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.9917550401558495, 'n_estimators': 400, 'learning_rate': 0.009397683024520643}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:00:11,117] Trial 23 finished with value: 0.7220073356495388 and parameters: {'subsample': 0.1850567218204376, 'dropout_rate': 0.8865280011925201, 'n_estimators': 401, 'learning_rate': 0.025993723328133253}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:00:13,167] Trial 24 finished with value: 0.7151393636191571 and parameters: {'subsample': 0.3038332766774453, 'dropout_rate': 0.5993544182667485, 'n_estimators': 252, 'learning_rate': 0.04338790451384301}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:00:15,470] Trial 25 finished with value: 0.7121878229484309 and parameters: {'subsample': 0.41518848496569194, 'dropout_rate': 0.9908539273305443, 'n_estimators': 315, 'learning_rate': 0.008500348756543277}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:00:19,637] Trial 26 finished with value: 0.7220073356495388 and parameters: {'subsample': 0.2192857037806549, 'dropout_rate': 0.7710807407466631, 'n_estimators': 434, 'learning_rate': 0.02508809651693958}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:00:22,858] Trial 27 finished with value: 0.643796357422043 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.900425295078122, 'n_estimators': 382, 'learning_rate': 0.043249245558858396}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:00:25,246] Trial 28 finished with value: 0.7044350187521483 and parameters: {'subsample': 0.6095590802808257, 'dropout_rate': 0.6272051960361522, 'n_estimators': 272, 'learning_rate': 0.019624123294647897}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:00:26,265] Trial 29 finished with value: 0.6978047962406084 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.7889098813803405, 'n_estimators': 138, 'learning_rate': 0.01079131697710575}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:00:32,017] Trial 30 finished with value: 0.726785021371715 and parameters: {'subsample': 0.15736775526254157, 'dropout_rate': 0.9307479078578905, 'n_estimators': 464, 'learning_rate': 0.02938393131962359}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:00:35,299] Trial 31 finished with value: 0.7347828115265296 and parameters: {'subsample': 0.10801177869921114, 'dropout_rate': 0.9596013021555434, 'n_estimators': 343, 'learning_rate': 0.00837958786529103}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:00:39,700] Trial 32 finished with value: 0.7359660617760128 and parameters: {'subsample': 0.102000681955651, 'dropout_rate': 0.8369771475424806, 'n_estimators': 386, 'learning_rate': 0.008432576953284697}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:00:44,070] Trial 33 finished with value: 0.721141534783738 and parameters: {'subsample': 0.18445396732787273, 'dropout_rate': 0.8431226092938587, 'n_estimators': 388, 'learning_rate': 0.0033766915424613374}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 16:00:48,771] Trial 34 finished with value: 0.713417445658631 and parameters: {'subsample': 0.2475662434654825, 'dropout_rate': 0.7388473846478782, 'n_estimators': 454, 'learning_rate': 0.020684756718428673}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:00:50,562] Trial 35 finished with value: 0.7258046292148522 and parameters: {'subsample': 0.16409845249239785, 'dropout_rate': 0.8249361651539662, 'n_estimators': 219, 'learning_rate': 0.038042352747052754}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7475490196078431
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:00:53,191] Trial 36 finished with value: 0.7116976268699995 and parameters: {'subsample': 0.4157829714840906, 'dropout_rate': 0.9213570137143106, 'n_estimators': 330, 'learning_rate': 0.062332141209271844}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:00:56,020] Trial 37 finished with value: 0.7169855566418206 and parameters: {'subsample': 0.2789515310161084, 'dropout_rate': 0.5153149868378608, 'n_estimators': 283, 'learning_rate': 0.011979304832032835}. Best is trial 22 with value: 0.7367558310784401.

Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:00:58,116] Trial 38 finished with value: 0.7258046292148522 and parameters: {'subsample': 0.14807719394046315, 'dropout_rate': 0.6401103186758491, 'n_estimators': 242, 'learning_rate': 0.029594359565260984}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:01:03,590] Trial 39 finished with value: 0.7188512556759361 and parameters: {'subsample': 0.2250121153664736, 'dropout_rate': 0.43471642740612565, 'n_estimators': 423, 'learning_rate': 0.006059367484731356}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:01:08,019] Trial 40 finished with value: 0.7348317868128467 and parameters: {'subsample': 0.10547181103602242, 'dropout_rate': 0.280971539366882, 'n_estimators': 379, 'learning_rate': 0.016082219591213465}. Best is trial 22 with value: 0.7367558310784401.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:01:10,785] Trial 41 finished with value: 0.7385657363481869 and parameters: {'subsample': 0.10440609687561335, 'dropout_rate': 0.952742553272642, 'n_estimators': 351, 'learning_rate': 0.02273880593088505}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:01:13,450] Trial 42 finished with value: 0.7269071629283814 and parameters: {'subsample': 0.15503211892248595, 'dropout_rate': 0.8722776092956734, 'n_estimators': 315, 'learning_rate': 0.024031978971510427}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:01:16,558] Trial 43 finished with value: 0.7170684066832458 and parameters: {'subsample': 0.20979862666572763, 'dropout_rate': 0.940518899196065, 'n_estimators': 350, 'learning_rate': 0.01499843170422061}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:01:19,531] Trial 44 finished with value: 0.7029343480613368 and parameters: {'subsample': 0.7026509113834132, 'dropout_rate': 0.8116126318736293, 'n_estimators': 315, 'learning_rate': 0.02138537360726618}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:01:23,696] Trial 45 finished with value: 0.6995905105263227 and parameters: {'subsample': 0.7945402024352797, 'dropout_rate': 0.7369846499088291, 'n_estimators': 398, 'learning_rate': 0.0390576421812656}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:01:26,677] Trial 46 finished with value: 0.7152222136605821 and parameters: {'subsample': 0.24864019346089142, 'dropout_rate': 0.864459133134658, 'n_estimators': 368, 'learning_rate': 0.028867385023015654}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:01:28,039] Trial 47 finished with value: 0.7266560613369969 and parameters: {'subsample': 0.13779685499002012, 'dropout_rate': 0.9922735450464466, 'n_estimators': 236, 'learning_rate': 0.08063451221472408}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:01:30,312] Trial 48 finished with value: 0.7368318626418136 and parameters: {'subsample': 0.10041208522824104, 'dropout_rate': 0.7029434264763865, 'n_estimators': 288, 'learning_rate': 0.011712366407010132}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:01:35,920] Trial 49 finished with value: 0.7133265930563866 and parameters: {'subsample': 0.3182821323497742, 'dropout_rate': 0.7027764567666558, 'n_estimators': 495, 'learning_rate': 0.005370334896509708}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:01:38,433] Trial 50 finished with value: 0.7229877278064015 and parameters: {'subsample': 0.18185787257240701, 'dropout_rate': 0.6684311621112123, 'n_estimators': 296, 'learning_rate': 0.012062446069569684}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:01:40,834] Trial 51 finished with value: 0.7359390054989564 and parameters: {'subsample': 0.10358892633132594, 'dropout_rate': 0.7447692874017322, 'n_estimators': 268, 'learning_rate': 0.019196914515673402}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:01:42,177] Trial 52 finished with value: 0.727745907517126 and parameters: {'subsample': 0.1340585075240214, 'dropout_rate': 0.8091871656630458, 'n_estimators': 185, 'learning_rate': 0.005870947994272792}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:01:45,054] Trial 53 finished with value: 0.7179393448168422 and parameters: {'subsample': 0.20668861121227977, 'dropout_rate': 0.8571880538125878, 'n_estimators': 341, 'learning_rate': 0.013961065771346044}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:01:48,589] Trial 54 finished with value: 0.7235172154000743 and parameters: {'subsample': 0.14636857181463744, 'dropout_rate': 0.9409667289386588, 'n_estimators': 440, 'learning_rate': 0.04893045633977665}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5985915492957746
[I 2024-04-14 16:01:51,968] Trial 55 finished with value: 0.7080064473235768 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.9018211649006455, 'n_estimators': 408, 'learning_rate': 0.03296561512866516}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:01:55,192] Trial 56 finished with value: 0.7161197557760198 and parameters: {'subsample': 0.2696935295856255, 'dropout_rate': 0.7047040338474623, 'n_estimators': 364, 'learning_rate': 0.001007952949653352}. Best is trial 41 with value: 0.7385657363481869.

Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:01:58,027] Trial 57 finished with value: 0.7368318626418136 and parameters: {'subsample': 0.10151923981488473, 'dropout_rate': 0.5748578133498727, 'n_estimators': 290, 'learning_rate': 0.022952443780972002}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5727699530516432
[I 2024-04-14 16:02:00,766] Trial 58 finished with value: 0.7229145615360523 and parameters: {'subsample': 0.18304861033971642, 'dropout_rate': 0.5462080102365253, 'n_estimators': 287, 'learning_rate': 0.026896972891595122}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:02:02,936] Trial 59 finished with value: 0.7265587040826151 and parameters: {'subsample': 0.1345525537792179, 'dropout_rate': 0.49577349479396987, 'n_estimators': 252, 'learning_rate': 0.023027535719870366}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:02:05,849] Trial 60 finished with value: 0.7146411649799063 and parameters: {'subsample': 0.36657489556153916, 'dropout_rate': 0.5872538617152262, 'n_estimators': 310, 'learning_rate': 0.009548207086811753}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:02:09,781] Trial 61 finished with value: 0.7368779726351067 and parameters: {'subsample': 0.1068373101754143, 'dropout_rate': 0.6303602090182723, 'n_estimators': 323, 'learning_rate': 0.01732290613502217}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:02:13,393] Trial 62 finished with value: 0.7312217985137295 and parameters: {'subsample': 0.12358342549562941, 'dropout_rate': 0.6243209894515288, 'n_estimators': 353, 'learning_rate': 0.01885134318861659}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:16,539] Trial 63 finished with value: 0.7011486337756225 and parameters: {'subsample': 0.6038235962186711, 'dropout_rate': 0.6522130513996315, 'n_estimators': 334, 'learning_rate': 0.013702686363527703}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7720588235294118
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:02:19,087] Trial 64 finished with value: 0.7180977741264256 and parameters: {'subsample': 0.1937827732795532, 'dropout_rate': 0.5662931098738813, 'n_estimators': 278, 'learning_rate': 0.023660984462446313}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:22,060] Trial 65 finished with value: 0.7222389312294716 and parameters: {'subsample': 0.1618643189116502, 'dropout_rate': 0.43232607452555816, 'n_estimators': 303, 'learning_rate': 0.008347845864333188}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-14 16:02:24,733] Trial 66 finished with value: 0.7350000383628061 and parameters: {'subsample': 0.10041734071097298, 'dropout_rate': 0.613074365886943, 'n_estimators': 259, 'learning_rate': 0.031642409577483925}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:02:26,553] Trial 67 finished with value: 0.7175171777409646 and parameters: {'subsample': 0.23446791626492278, 'dropout_rate': 0.6723731426076928, 'n_estimators': 226, 'learning_rate': 0.017668810800559223}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:02:29,858] Trial 68 finished with value: 0.7258121794804568 and parameters: {'subsample': 0.12949846385212768, 'dropout_rate': 0.7568081321034419, 'n_estimators': 376, 'learning_rate': 0.0267624773650322}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:02:32,711] Trial 69 finished with value: 0.7239681199632643 and parameters: {'subsample': 0.17355025375302546, 'dropout_rate': 0.9973583125700416, 'n_estimators': 393, 'learning_rate': 0.021522946040105788}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:02:35,178] Trial 70 finished with value: 0.7283634720845663 and parameters: {'subsample': 0.1290955905734481, 'dropout_rate': 0.9675898417461594, 'n_estimators': 325, 'learning_rate': 0.040201567222722626}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:02:38,697] Trial 71 finished with value: 0.7330489378201562 and parameters: {'subsample': 0.11680216211078241, 'dropout_rate': 0.7975198107381547, 'n_estimators': 291, 'learning_rate': 0.016569936931315806}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:02:42,612] Trial 72 finished with value: 0.7377218544916467 and parameters: {'subsample': 0.10275158765462408, 'dropout_rate': 0.7289310638753843, 'n_estimators': 328, 'learning_rate': 0.012948162046558399}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:02:46,094] Trial 73 finished with value: 0.7259681957922312 and parameters: {'subsample': 0.15095553637511136, 'dropout_rate': 0.7195981691262208, 'n_estimators': 356, 'learning_rate': 0.005106161888277554}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:02:50,052] Trial 74 finished with value: 0.716251581103762 and parameters: {'subsample': 0.20462691630390645, 'dropout_rate': 0.6812870440629315, 'n_estimators': 416, 'learning_rate': 0.011296618823933416}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 16:02:53,289] Trial 75 finished with value: 0.7378169397712568 and parameters: {'subsample': 0.10157205631910818, 'dropout_rate': 0.5179405008423784, 'n_estimators': 341, 'learning_rate': 0.007334572449275428}. Best is trial 41 with value: 0.7385657363481869.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:02:56,277] Trial 76 finished with value: 0.725922085798938 and parameters: {'subsample': 0.1620371837929913, 'dropout_rate': 0.5174922700900502, 'n_estimators': 339, 'learning_rate': 0.05992326510937737}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6197183098591549
[I 2024-04-14 16:02:59,235] Trial 77 finished with value: 0.7377708297779637 and parameters: {'subsample': 0.10011010706260669, 'dropout_rate': 0.5338712401222789, 'n_estimators': 306, 'learning_rate': 0.013080186457781433}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:03:01,736] Trial 78 finished with value: 0.7220292546587996 and parameters: {'subsample': 0.18584480426704478, 'dropout_rate': 0.5253951820250353, 'n_estimators': 274, 'learning_rate': 0.0034442184993240302}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:03:04,372] Trial 79 finished with value: 0.7197389755509976 and parameters: {'subsample': 0.25240621641505473, 'dropout_rate': 0.4789936364148586, 'n_estimators': 324, 'learning_rate': 0.012931181638195809}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7377450980392157
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:03:05,648] Trial 80 finished with value: 0.7114246062693541 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.5653433198031864, 'n_estimators': 199, 'learning_rate': 0.007611419087064912}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:03:08,372] Trial 81 finished with value: 0.7293024392207166 and parameters: {'subsample': 0.12672545388680065, 'dropout_rate': 0.36925004198076483, 'n_estimators': 305, 'learning_rate': 0.016493645708685695}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6056338028169014
[I 2024-04-14 16:03:11,133] Trial 82 finished with value: 0.7349268720924568 and parameters: {'subsample': 0.10251493019486126, 'dropout_rate': 0.4729919944525848, 'n_estimators': 318, 'learning_rate': 0.011056455472249862}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:03:14,089] Trial 83 finished with value: 0.726833996658032 and parameters: {'subsample': 0.15145647200737752, 'dropout_rate': 0.5912029459139471, 'n_estimators': 346, 'learning_rate': 0.022194146175182984}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:03:16,046] Trial 84 finished with value: 0.7220292546587996 and parameters: {'subsample': 0.22133309571737, 'dropout_rate': 0.6504440341384942, 'n_estimators': 262, 'learning_rate': 0.03569337289177748}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.596244131455399
[I 2024-04-14 16:03:18,571] Trial 85 finished with value: 0.7284366383549157 and parameters: {'subsample': 0.12863247105954737, 'dropout_rate': 0.45593407139253406, 'n_estimators': 297, 'learning_rate': 0.019060060984685618}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:03:21,839] Trial 86 finished with value: 0.7221219269406007 and parameters: {'subsample': 0.16541006269707592, 'dropout_rate': 0.6078185119513708, 'n_estimators': 371, 'learning_rate': 0.01462522267111395}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:03:24,489] Trial 87 finished with value: 0.7339608486792504 and parameters: {'subsample': 0.10085895545369629, 'dropout_rate': 0.17971650523934474, 'n_estimators': 283, 'learning_rate': 0.007190805934355407}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:03:27,380] Trial 88 finished with value: 0.7277049347916285 and parameters: {'subsample': 0.14143363599623185, 'dropout_rate': 0.5350579617125844, 'n_estimators': 329, 'learning_rate': 0.003209560892987965}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7671568627450981
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:03:29,258] Trial 89 finished with value: 0.7188783119529923 and parameters: {'subsample': 0.1941216248136392, 'dropout_rate': 0.7244376875320141, 'n_estimators': 244, 'learning_rate': 0.025056796383218}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:03:32,994] Trial 90 finished with value: 0.7338733136652447 and parameters: {'subsample': 0.12003248732048777, 'dropout_rate': 0.4980193697997328, 'n_estimators': 302, 'learning_rate': 0.04638324399962829}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:03:36,830] Trial 91 finished with value: 0.7303289413708723 and parameters: {'subsample': 0.11787677593364676, 'dropout_rate': 0.6363064119538621, 'n_estimators': 381, 'learning_rate': 0.00915079691426401}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5774647887323944
[I 2024-04-14 16:03:40,240] Trial 92 finished with value: 0.7238535286722024 and parameters: {'subsample': 0.17435918551916632, 'dropout_rate': 0.9192355951187405, 'n_estimators': 357, 'learning_rate': 0.013337378607079328}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 16:03:40,912] Trial 93 finished with value: 0.7213317053429582 and parameters: {'subsample': 0.14421811821613884, 'dropout_rate': 0.8829554946066316, 'n_estimators': 86, 'learning_rate': 0.010265199733807162}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831

Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 16:03:44,356] Trial 94 finished with value: 0.7378169397712568 and parameters: {'subsample': 0.10166647325988434, 'dropout_rate': 0.8244134738987358, 'n_estimators': 340, 'learning_rate': 0.004727090345537489}. Best is trial 41 with value: 0.7385657363481869.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-14 16:03:47,328] Trial 95 finished with value: 0.738709796914114 and parameters: {'subsample': 0.10055409799174729, 'dropout_rate': 0.6911773987018819, 'n_estimators': 313, 'learning_rate': 0.0038777019677429035}. Best is trial 95 with value: 0.738709796914114.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5915492957746479
[I 2024-04-14 16:03:50,597] Trial 96 finished with value: 0.726833996658032 and parameters: {'subsample': 0.14570103308383708, 'dropout_rate': 0.7705356049352989, 'n_estimators': 335, 'learning_rate': 0.004561529382553371}. Best is trial 95 with value: 0.738709796914114.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6009389671361502
[I 2024-04-14 16:03:53,364] Trial 97 finished with value: 0.7312217985137295 and parameters: {'subsample': 0.12131394343745006, 'dropout_rate': 0.6951056950423564, 'n_estimators': 312, 'learning_rate': 0.002217368545384632}. Best is trial 95 with value: 0.738709796914114.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.5821596244131455
[I 2024-04-14 16:03:57,041] Trial 98 finished with value: 0.7249341433764708 and parameters: {'subsample': 0.17083292922062382, 'dropout_rate': 0.5507585877339117, 'n_estimators': 346, 'learning_rate': 0.07063377968277355}. Best is trial 95 with value: 0.738709796914114.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8396624472573839

[I 2024-04-14 16:03:58,989] A new study created in memory with name: no-name-4717c2ef-dfdb-47be-a2a5-c083fdbc117a

Fold 5 C-index: 0.6150234741784038
[I 2024-04-14 16:03:58,973] Trial 99 finished with value: 0.7375997129349804 and parameters: {'subsample': 0.10061578878505581, 'dropout_rate': 0.9496351245360807, 'n_estimators': 289, 'learning_rate': 0.0071141189037418045}. Best is trial 95 with value: 0.738709796914114.


* Best trial for C-index:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.738709796914114], datetime_start=datetime.datetime(2024, 4, 14, 16, 3, 44, 364813), datetime_complete=datetime.datetime(2024, 4, 14, 16, 3, 47, 328003), params={'subsample': 0.10055409799174729, 'dropout_rate': 0.6911773987018819, 'n_estimators': 313, 'learning_rate': 0.0038777019677429035}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=95, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10055409799174729, 'dropout_rate': 0.6911773987018819, 'n_estimators': 313, 'learning_rate': 0.0038777019677429035}


* Best Score for C-index:
 0.738709796914114

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17468486153985427
Fold 2 IBS: 0.21248933875310147
Fold 3 IBS: 0.194855347846977
Fold 4 IBS: 0.22697820304357663
Fold 5 IBS: 0.28517539420510435
[I 2024-04-14 16:03:59,731] Trial 0 finished with value: 0.21883662907772275 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.1986321730994685
Fold 2 IBS: 0.3120078749344299
Fold 3 IBS: 0.24996445306241238
Fold 4 IBS: 0.31689326323842354
Fold 5 IBS: 0.335943687848095
[I 2024-04-14 16:04:06,874] Trial 1 finished with value: 0.28268829043656585 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.1782313888075919
Fold 2 IBS: 0.23887158390826022
Fold 3 IBS: 0.22391624006476715
Fold 4 IBS: 0.3051666646220198
Fold 5 IBS: 0.3084641364030169
[I 2024-04-14 16:04:08,674] Trial 2 finished with value: 0.2509300027611312 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.18280279867268556
Fold 2 IBS: 0.2687886303305837
Fold 3 IBS: 0.21057603387531768
Fold 4 IBS: 0.30155508579638324
Fold 5 IBS: 0.30154512922966814
[I 2024-04-14 16:04:10,455] Trial 3 finished with value: 0.2530535355809277 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.17737859514388607
Fold 2 IBS: 0.26071599003700413
Fold 3 IBS: 0.21099308314290005
Fold 4 IBS: 0.30353660690462075
Fold 5 IBS: 0.30872361378403196
[I 2024-04-14 16:04:13,184] Trial 4 finished with value: 0.2522695778024886 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.1904868260436939
Fold 2 IBS: 0.3132436090741233
Fold 3 IBS: 0.24395973116382566
Fold 4 IBS: 0.3159243162013543
Fold 5 IBS: 0.33186943565989657
[I 2024-04-14 16:04:15,790] Trial 5 finished with value: 0.27909678362857876 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.21883662907772275.
Fold 1 IBS: 0.17780585696151255
Fold 2 IBS: 0.20708379142389674
Fold 3 IBS: 0.18227745733835357
Fold 4 IBS: 0.2141280706510948
Fold 5 IBS: 0.26351899157103026
[I 2024-04-14 16:04:16,915] Trial 6 finished with value: 0.2089628335891776 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2089628335891776.
Fold 1 IBS: 0.19015600326147195
Fold 2 IBS: 0.19355181017105216
Fold 3 IBS: 0.17743814928441723
Fold 4 IBS: 0.20291235829146803
Fold 5 IBS: 0.22736906975431576
[I 2024-04-14 16:04:17,214] Trial 7 finished with value: 0.19828547815254502 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.17040000366665245
Fold 2 IBS: 0.21357933257629527
Fold 3 IBS: 0.19414461063668192
Fold 4 IBS: 0.2318262465845874
Fold 5 IBS: 0.2884854378459845
[I 2024-04-14 16:04:18,617] Trial 8 finished with value: 0.2196871262620403 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.20620416623285268
Fold 2 IBS: 0.28062382621165427
Fold 3 IBS: 0.2432029695587583
Fold 4 IBS: 0.31679825960552194
Fold 5 IBS: 0.32925395077964825
[I 2024-04-14 16:04:22,651] Trial 9 finished with value: 0.27521663447768707 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22073305097989868
Fold 3 IBS: 0.20360033665381083
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21786150836405777
[I 2024-04-14 16:04:22,899] Trial 10 finished with value: 0.21599308091770278 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.21313236776720154
Fold 2 IBS: 0.22046918252905495
Fold 3 IBS: 0.20374843644321758
Fold 4 IBS: 0.22316838226204444
Fold 5 IBS: 0.21783099603000905
[I 2024-04-14 16:04:23,118] Trial 11 finished with value: 0.21566987300630552 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.1704735293955719
Fold 2 IBS: 0.22371331534618163
Fold 3 IBS: 0.21028536975066447
Fold 4 IBS: 0.2738014814948179
Fold 5 IBS: 0.301999663747711
[I 2024-04-14 16:04:23,734] Trial 12 finished with value: 0.23605467194698937 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.1916381360421157
Fold 2 IBS: 0.2671841424090184
Fold 3 IBS: 0.21459049695951046
Fold 4 IBS: 0.30189816891413546
Fold 5 IBS: 0.3033750519625981
[I 2024-04-14 16:04:26,110] Trial 13 finished with value: 0.2557371992574756 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.19765213183356498
Fold 2 IBS: 0.20312481708224114
Fold 3 IBS: 0.18337571072980624
Fold 4 IBS: 0.21396864848533864
Fold 5 IBS: 0.2206642376330897
[I 2024-04-14 16:04:26,649] Trial 14 finished with value: 0.20375710915280815 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.21017626388882493
Fold 2 IBS: 0.2164928794138353
Fold 3 IBS: 0.19869882569389757
Fold 4 IBS: 0.22146951352786337
Fold 5 IBS: 0.21679227193830283
[I 2024-04-14 16:04:27,099] Trial 15 finished with value: 0.2127259508925448 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.20382898092240473
Fold 2 IBS: 0.20865995687278818
Fold 3 IBS: 0.19030977064327284
Fold 4 IBS: 0.217701879376951
Fold 5 IBS: 0.21695003006174762
[I 2024-04-14 16:04:27,458] Trial 16 finished with value: 0.20749012357543287 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.17873976040794087
Fold 2 IBS: 0.22245202961786034
Fold 3 IBS: 0.1866525375903488
Fold 4 IBS: 0.22321054787529954
Fold 5 IBS: 0.27326406478224247
[I 2024-04-14 16:04:28,165] Trial 17 finished with value: 0.21686378805473838 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.17048838374646885
Fold 2 IBS: 0.19862543386442882
Fold 3 IBS: 0.1840472570167188
Fold 4 IBS: 0.19731162944762204
Fold 5 IBS: 0.2733853585304743
[I 2024-04-14 16:04:30,677] Trial 18 finished with value: 0.20477161252114257 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19828547815254502.
Fold 1 IBS: 0.19034716689536788
Fold 2 IBS: 0.19426953833697888

Fold 3 IBS: 0.17561521038419572
Fold 4 IBS: 0.19617937926603082
Fold 5 IBS: 0.22030982851403455
[I 2024-04-14 16:04:31,033] Trial 19 finished with value: 0.19534422467932158 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.1934568269543391
Fold 2 IBS: 0.19715811856127513
Fold 3 IBS: 0.17946469994393788
Fold 4 IBS: 0.20156135236511127
Fold 5 IBS: 0.21995157160040674
[I 2024-04-14 16:04:31,454] Trial 20 finished with value: 0.19831851388501404 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.19629608820460723
Fold 2 IBS: 0.20116625589103407
Fold 3 IBS: 0.18307602213830743
Fold 4 IBS: 0.20415973589751046
Fold 5 IBS: 0.21825141892231678
[I 2024-04-14 16:04:31,748] Trial 21 finished with value: 0.2005899042107552 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.2131782018406857
Fold 2 IBS: 0.21966297563854562
Fold 3 IBS: 0.20310325082392688
Fold 4 IBS: 0.22331313612323705
Fold 5 IBS: 0.21758975980778372
[I 2024-04-14 16:04:31,941] Trial 22 finished with value: 0.21536946484683578 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.16750931402711908
Fold 2 IBS: 0.19624059320767942
Fold 3 IBS: 0.17747692152992783
Fold 4 IBS: 0.19527723207298991
Fold 5 IBS: 0.26649025771923585
[I 2024-04-14 16:04:32,856] Trial 23 finished with value: 0.2005988637113904 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.17898230352039668
Fold 2 IBS: 0.19173170753090724
Fold 3 IBS: 0.17738416768704218
Fold 4 IBS: 0.19456534934637693
Fold 5 IBS: 0.24694741754828667
[I 2024-04-14 16:04:33,228] Trial 24 finished with value: 0.19792218912660192 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.1704298525889321
Fold 2 IBS: 0.20762804398231333
Fold 3 IBS: 0.18234672133552832
Fold 4 IBS: 0.22885650725731932
Fold 5 IBS: 0.28497595044100466
[I 2024-04-14 16:04:33,638] Trial 25 finished with value: 0.21484741512101957 and parameters: {'subsample': 0.41513882888547626, 'dropout_rate': 0.92193566363172, 'n_estimators': 70, 'learning_rate': 0.08579428551722094}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.1703512798387949
Fold 2 IBS: 0.22562223346851765
Fold 3 IBS: 0.20843001375733985
Fold 4 IBS: 0.29135970508437503
Fold 5 IBS: 0.3051857387236929
[I 2024-04-14 16:04:34,418] Trial 26 finished with value: 0.24018979417454406 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.9863699266040719, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.22588162636111023
Fold 2 IBS: 0.2725511996750387
Fold 3 IBS: 0.23552022367923722
Fold 4 IBS: 0.32485683596649784
Fold 5 IBS: 0.3236345797555115
[I 2024-04-14 16:04:37,933] Trial 27 finished with value: 0.2764888930874791 and parameters: {'subsample': 0.26021450312326855, 'dropout_rate': 0.9019594475838296, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.1784319276912986
Fold 2 IBS: 0.25491791145635706
Fold 3 IBS: 0.21993799206943312
Fold 4 IBS: 0.3022980158292422
Fold 5 IBS: 0.30769024798209993
[I 2024-04-14 16:04:40,333] Trial 28 finished with value: 0.2526552190056862 and parameters: {'subsample': 0.5971669636685615, 'dropout_rate': 0.7292365612928325, 'n_estimators': 236, 'learning_rate': 0.046726352221374515}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.1677637708472082
Fold 2 IBS: 0.21203316623792792
Fold 3 IBS: 0.198493186070553
Fold 4 IBS: 0.22230992453466503
Fold 5 IBS: 0.2918465306042412
[I 2024-04-14 16:04:41,084] Trial 29 finished with value: 0.21848931565891908 and parameters: {'subsample': 0.3457177033536965, 'dropout_rate': 0.528113503868086, 'n_estimators': 97, 'learning_rate': 0.08423642007181871}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.16411551731670374
Fold 2 IBS: 0.20420611804318603
Fold 3 IBS: 0.19208550664521554
Fold 4 IBS: 0.2392377676875803
Fold 5 IBS: 0.286750803216586
[I 2024-04-14 16:04:42,230] Trial 30 finished with value: 0.21727914258185432 and parameters: {'subsample': 0.21287332299822773, 'dropout_rate': 0.8300645798351977, 'n_estimators': 136, 'learning_rate': 0.05802531255595394}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.19058080969509453
Fold 2 IBS: 0.1945750054983278
Fold 3 IBS: 0.17796726400707605
Fold 4 IBS: 0.19845534293847908
Fold 5 IBS: 0.2199669430451495
[I 2024-04-14 16:04:42,640] Trial 31 finished with value: 0.1963090730368254 and parameters: {'subsample': 0.15465256682910847, 'dropout_rate': 0.7665254119155692, 'n_estimators': 42, 'learning_rate': 0.04796619662341173}. Best is trial 19 with value: 0.19534422467932158.
Fold 1 IBS: 0.176777470219372
Fold 2 IBS: 0.1890014042122981
Fold 3 IBS: 0.1680043391176252
Fold 4 IBS: 0.18027934135181622
Fold 5 IBS: 0.23650142825408577
[I 2024-04-14 16:04:43,148] Trial 32 finished with value: 0.19011279663103947 and parameters: {'subsample': 0.10342193656652618, 'dropout_rate': 0.9389584836732486, 'n_estimators': 75, 'learning_rate': 0.04909887443838165}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17261732889040501
Fold 2 IBS: 0.18941431705026662
Fold 3 IBS: 0.1669321858768433
Fold 4 IBS: 0.18079995756392414
Fold 5 IBS: 0.2441147270560215
[I 2024-04-14 16:04:43,773] Trial 33 finished with value: 0.1907757032874921 and parameters: {'subsample': 0.10120824695002664, 'dropout_rate': 0.9165491191113839, 'n_estimators': 84, 'learning_rate': 0.05193153712447138}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.16831203777288678
Fold 2 IBS: 0.19166044060285933
Fold 3 IBS: 0.16617805619473233
Fold 4 IBS: 0.17643309585058128
Fold 5 IBS: 0.2498558785871286
[I 2024-04-14 16:04:44,449] Trial 34 finished with value: 0.19048790180163766 and parameters: {'subsample': 0.10905456354152472, 'dropout_rate': 0.9451805114606486, 'n_estimators': 91, 'learning_rate': 0.05207614347752842}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.15893911477710435
Fold 2 IBS: 0.20582126512229598
Fold 3 IBS: 0.17674918758619404
Fold 4 IBS: 0.18833005341520517
Fold 5 IBS: 0.2862112969059526
[I 2024-04-14 16:04:45,473] Trial 35 finished with value: 0.20321018356135045 and parameters: {'subsample': 0.10507846371518663, 'dropout_rate': 0.9999401788331197, 'n_estimators': 167, 'learning_rate': 0.05193224978956916}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.1680767419923715
Fold 2 IBS: 0.20485113146183934
Fold 3 IBS: 0.1820718323317957
Fold 4 IBS: 0.2255503798805306
Fold 5 IBS: 0.28559269142762045
[I 2024-04-14 16:04:46,066] Trial 36 finished with value: 0.2132285554188315 and parameters: {'subsample': 0.2789987305825237, 'dropout_rate': 0.9397768947869433, 'n_estimators': 102, 'learning_rate': 0.06778534734243152}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.1696340822381199
Fold 2 IBS: 0.1925378996118369
Fold 3 IBS: 0.1707225827791565
Fold 4 IBS: 0.18528634201996333
Fold 5 IBS: 0.25589809631788585
[I 2024-04-14 16:04:46,606] Trial 37 finished with value: 0.19481580059339249 and parameters: {'subsample': 0.18501180265201958, 'dropout_rate': 0.8608568379956052, 'n_estimators': 87, 'learning_rate': 0.05621431261796065}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17974473327984655
Fold 2 IBS: 0.24566963543620682

Fold 3 IBS: 0.21726677705287487
Fold 4 IBS: 0.3067540059676042
Fold 5 IBS: 0.3088785718394419
[I 2024-04-14 16:04:47,978] Trial 38 finished with value: 0.2516627447151949 and parameters: {'subsample': 0.1954790971490823, 'dropout_rate': 0.8663362825803563, 'n_estimators': 197, 'learning_rate': 0.07288612365177065}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17384033345948605
Fold 2 IBS: 0.19117022812858242
Fold 3 IBS: 0.1658112441781456
Fold 4 IBS: 0.19062854819614738
Fold 5 IBS: 0.2531160401238152
[I 2024-04-14 16:04:48,713] Trial 39 finished with value: 0.19491327881723533 and parameters: {'subsample': 0.2485509072011421, 'dropout_rate': 0.2538651184588351, 'n_estimators': 81, 'learning_rate': 0.05575307634287385}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17198132816848963
Fold 2 IBS: 0.2379402139667447
Fold 3 IBS: 0.20755181076017126
Fold 4 IBS: 0.28872031988166974
Fold 5 IBS: 0.30715041622153244
[I 2024-04-14 16:04:49,768] Trial 40 finished with value: 0.24266881779972155 and parameters: {'subsample': 0.1707812730556729, 'dropout_rate': 0.8568038953339088, 'n_estimators': 168, 'learning_rate': 0.08018822574072365}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17287551330714795
Fold 2 IBS: 0.19296640801322962
Fold 3 IBS: 0.16308928797415692
Fold 4 IBS: 0.18124037359270814
Fold 5 IBS: 0.24393778098254895
[I 2024-04-14 16:04:50,459] Trial 41 finished with value: 0.19082187277395832 and parameters: {'subsample': 0.2523684700326532, 'dropout_rate': 0.12946395236119468, 'n_estimators': 83, 'learning_rate': 0.05557356768144063}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.16632624811780838
Fold 2 IBS: 0.19907563543759352
Fold 3 IBS: 0.16792729867205436
Fold 4 IBS: 0.188124351321481
Fold 5 IBS: 0.2624521951918444
[I 2024-04-14 16:04:51,442] Trial 42 finished with value: 0.19678114574815633 and parameters: {'subsample': 0.2168003321830646, 'dropout_rate': 0.13661676516072546, 'n_estimators': 116, 'learning_rate': 0.05424653086707643}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.1985327178299728
Fold 2 IBS: 0.20039385432523266
Fold 3 IBS: 0.1828542383883863
Fold 4 IBS: 0.20493541647570307
Fold 5 IBS: 0.2154107740439107
[I 2024-04-14 16:04:51,812] Trial 43 finished with value: 0.2004254002126411 and parameters: {'subsample': 0.16058851674117988, 'dropout_rate': 0.2918731852044582, 'n_estimators': 21, 'learning_rate': 0.06449172446370455}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.1662909154870701
Fold 2 IBS: 0.2072268964984118
Fold 3 IBS: 0.1835004606995974
Fold 4 IBS: 0.22375989511781022
Fold 5 IBS: 0.28585984859917984
[I 2024-04-14 16:04:53,135] Trial 44 finished with value: 0.2133276032804139 and parameters: {'subsample': 0.3087080179108906, 'dropout_rate': 0.48118283516039095, 'n_estimators': 120, 'learning_rate': 0.058037094067983255}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.18473664066276843
Fold 2 IBS: 0.19038763545149617
Fold 3 IBS: 0.17110765519414445
Fold 4 IBS: 0.19753400484652694
Fold 5 IBS: 0.23194911315066036
[I 2024-04-14 16:04:54,173] Trial 45 finished with value: 0.19514300986111927 and parameters: {'subsample': 0.24265872160421625, 'dropout_rate': 0.9424089103886609, 'n_estimators': 80, 'learning_rate': 0.03400538573985265}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.15125405923325003
Fold 2 IBS: 0.22424728826167586
Fold 3 IBS: 0.17997325999467167
Fold 4 IBS: 0.24579768495129628
Fold 5 IBS: 0.2914964903525055
[I 2024-04-14 16:04:59,610] Trial 46 finished with value: 0.21855375655867987 and parameters: {'subsample': 0.13059280498853088, 'dropout_rate': 0.16964722293724843, 'n_estimators': 227, 'learning_rate': 0.04793167667146644}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17615778272214205
Fold 2 IBS: 0.25145662792137885
Fold 3 IBS: 0.21288418921697055
Fold 4 IBS: 0.3022422035994955
Fold 5 IBS: 0.3091055112176773
[I 2024-04-14 16:05:03,132] Trial 47 finished with value: 0.25036926293553285 and parameters: {'subsample': 0.1776999546245493, 'dropout_rate': 0.8801411833130257, 'n_estimators': 193, 'learning_rate': 0.07372360059436274}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.205690370035544
Fold 2 IBS: 0.21051518460568627
Fold 3 IBS: 0.19343233144073316
Fold 4 IBS: 0.21743556499317027
Fold 5 IBS: 0.21687195047193664
[I 2024-04-14 16:05:03,655] Trial 48 finished with value: 0.20878908030941407 and parameters: {'subsample': 0.2975238164171056, 'dropout_rate': 0.9466636735140487, 'n_estimators': 19, 'learning_rate': 0.03558355577476204}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.16855214659028536
Fold 2 IBS: 0.21791434549618618
Fold 3 IBS: 0.1981934932095487
Fold 4 IBS: 0.24562589766860954
Fold 5 IBS: 0.2932232087674821
[I 2024-04-14 16:05:06,328] Trial 49 finished with value: 0.2247018183464224 and parameters: {'subsample': 0.44591927509152196, 'dropout_rate': 0.8215330154174192, 'n_estimators': 272, 'learning_rate': 0.02713079119975165}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17469848848791253
Fold 2 IBS: 0.19172564165878492
Fold 3 IBS: 0.16903867255122468
Fold 4 IBS: 0.19437347321087844
Fold 5 IBS: 0.2571160670602787
[I 2024-04-14 16:05:06,964] Trial 50 finished with value: 0.19739046859381587 and parameters: {'subsample': 0.23506363300762062, 'dropout_rate': 0.42732372125147283, 'n_estimators': 88, 'learning_rate': 0.05079775146508922}. Best is trial 32 with value: 0.19011279663103947.
Fold 1 IBS: 0.17134958308790302
Fold 2 IBS: 0.1883551986675922
Fold 3 IBS: 0.16365840522605254
Fold 4 IBS: 0.1766502346085376
Fold 5 IBS: 0.23792119907350284
[I 2024-04-14 16:05:07,572] Trial 51 finished with value: 0.18758692413271766 and parameters: {'subsample': 0.143043777223833, 'dropout_rate': 0.10045382034687865, 'n_estimators': 79, 'learning_rate': 0.05674565223918392}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1590778881723867
Fold 2 IBS: 0.19884387987942467
Fold 3 IBS: 0.16670293774758252
Fold 4 IBS: 0.19348808615922558
Fold 5 IBS: 0.2693451688409717
[I 2024-04-14 16:05:08,406] Trial 52 finished with value: 0.19749159215991824 and parameters: {'subsample': 0.1351375148183566, 'dropout_rate': 0.1983852595536179, 'n_estimators': 113, 'learning_rate': 0.05882424425049454}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1574507565216457
Fold 2 IBS: 0.20462496192120083
Fold 3 IBS: 0.16700983028840577
Fold 4 IBS: 0.176823125996836
Fold 5 IBS: 0.2723680592599561
[I 2024-04-14 16:05:09,736] Trial 53 finished with value: 0.19565534679760888 and parameters: {'subsample': 0.10739468479906676, 'dropout_rate': 0.10712027063978075, 'n_estimators': 149, 'learning_rate': 0.05471276097646021}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.17599621223688117
Fold 2 IBS: 0.19043026304268718
Fold 3 IBS: 0.1663345894668427
Fold 4 IBS: 0.18357659342572996
Fold 5 IBS: 0.242801818007054
[I 2024-04-14 16:05:10,263] Trial 54 finished with value: 0.191827895235839 and parameters: {'subsample': 0.1653685825705842, 'dropout_rate': 0.3327400827984601, 'n_estimators': 64, 'learning_rate': 0.0648095739895299}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.18395931009853092
Fold 2 IBS: 0.19012175456528846
Fold 3 IBS: 0.16815129523334996
Fold 4 IBS: 0.19124945693060466
Fold 5 IBS: 0.230655317771399
[I 2024-04-14 16:05:10,882] Trial 55 finished with value: 0.19282742691983462 and parameters: {'subsample': 0.14987657619389141, 'dropout_rate': 0.34256511422587643, 'n_estimators': 66, 'learning_rate': 0.045492182952046295}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.21122977088364134
Fold 2 IBS: 0.21828575385936358
Fold 3 IBS: 0.20201709272828994
Fold 4 IBS: 0.22081595199116158
Fold 5 IBS: 0.2170812216061952
[I 2024-04-14 16:05:11,112] Trial 56 finished with value: 0.21388595821373033 and parameters: {'subsample': 0.1668652595089497, 'dropout_rate': 0.2558467672073461, 'n_estimators': 3, 'learning_rate': 0.0643642899033242}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.15947630365060744
Fold 2 IBS: 0.19501103210124268

Fold 3 IBS: 0.1659808217178906
Fold 4 IBS: 0.1885288450582718
Fold 5 IBS: 0.25937603443602375
[I 2024-04-14 16:05:12,134] Trial 57 finished with value: 0.19367460739280726 and parameters: {'subsample': 0.10158446690685444, 'dropout_rate': 0.17532364403171014, 'n_estimators': 133, 'learning_rate': 0.048923651208961784}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.18163819459855188
Fold 2 IBS: 0.18938416944320802
Fold 3 IBS: 0.17070754202477906
Fold 4 IBS: 0.19532813835815624
Fold 5 IBS: 0.22827735864019225
[I 2024-04-14 16:05:12,670] Trial 58 finished with value: 0.1930670806129775 and parameters: {'subsample': 0.7591484265070766, 'dropout_rate': 0.10710740658854133, 'n_estimators': 53, 'learning_rate': 0.06216375518515009}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.18818122279496977
Fold 2 IBS: 0.1924822958080667
Fold 3 IBS: 0.1745201537844417
Fold 4 IBS: 0.19623717827044204
Fold 5 IBS: 0.2253054718123723
[I 2024-04-14 16:05:13,025] Trial 59 finished with value: 0.19534526449405848 and parameters: {'subsample': 0.22466321698115937, 'dropout_rate': 0.32367185464830683, 'n_estimators': 34, 'learning_rate': 0.06977285134460831}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.17767382180366384
Fold 2 IBS: 0.19024756843465587
Fold 3 IBS: 0.16895873187050336
Fold 4 IBS: 0.1801690161269844
Fold 5 IBS: 0.240197796640385
[I 2024-04-14 16:05:13,850] Trial 60 finished with value: 0.1914493869752385 and parameters: {'subsample': 0.1432041041132586, 'dropout_rate': 0.2208020726507778, 'n_estimators': 101, 'learning_rate': 0.03723183452431825}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16677109263444362
Fold 2 IBS: 0.19367453772163076
Fold 3 IBS: 0.17067533061525686
Fold 4 IBS: 0.16698870891492354
Fold 5 IBS: 0.2610327130649642
[I 2024-04-14 16:05:14,616] Trial 61 finished with value: 0.19182847659024377 and parameters: {'subsample': 0.1347725875065711, 'dropout_rate': 0.20834803608430047, 'n_estimators': 104, 'learning_rate': 0.05339232351092521}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1867839400248981
Fold 2 IBS: 0.19194939603549316
Fold 3 IBS: 0.1728550582775793
Fold 4 IBS: 0.19475551298063812
Fold 5 IBS: 0.22847499565880913
[I 2024-04-14 16:05:15,127] Trial 62 finished with value: 0.19496378059548355 and parameters: {'subsample': 0.19433192188895293, 'dropout_rate': 0.21659304167812493, 'n_estimators': 68, 'learning_rate': 0.03612303080242765}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.18098454994118493
Fold 2 IBS: 0.1902668123205212
Fold 3 IBS: 0.16671976767489366
Fold 4 IBS: 0.1906035032468281
Fold 5 IBS: 0.23425092629614616
[I 2024-04-14 16:05:15,728] Trial 63 finished with value: 0.1925651118959148 and parameters: {'subsample': 0.28109491458190883, 'dropout_rate': 0.14213818814606993, 'n_estimators': 77, 'learning_rate': 0.04415337609777841}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1816437829438478
Fold 2 IBS: 0.19166289511221216
Fold 3 IBS: 0.17117702939720253
Fold 4 IBS: 0.18800434276201525
Fold 5 IBS: 0.2306033567481692
[I 2024-04-14 16:05:16,220] Trial 64 finished with value: 0.19261828139268938 and parameters: {'subsample': 0.13086168312603375, 'dropout_rate': 0.23679248958159427, 'n_estimators': 58, 'learning_rate': 0.05176292749406915}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16594741080399708
Fold 2 IBS: 0.19931601932188783
Fold 3 IBS: 0.1676057733951703
Fold 4 IBS: 0.2007777971100812
Fold 5 IBS: 0.26989240329426123
[I 2024-04-14 16:05:17,058] Trial 65 finished with value: 0.2007078807850795 and parameters: {'subsample': 0.15918469055962084, 'dropout_rate': 0.2984199321461972, 'n_estimators': 103, 'learning_rate': 0.06535858147826955}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.15977782356763046
Fold 2 IBS: 0.20237525772830622
Fold 3 IBS: 0.1703465589623638
Fold 4 IBS: 0.1715910529246231
Fold 5 IBS: 0.2776957512443112
[I 2024-04-14 16:05:18,053] Trial 66 finished with value: 0.19635728888544696 and parameters: {'subsample': 0.10041063725756964, 'dropout_rate': 0.3706294199754716, 'n_estimators': 129, 'learning_rate': 0.059807146048566455}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16801601205567288
Fold 2 IBS: 0.2140048281846156
Fold 3 IBS: 0.19604418021452602
Fold 4 IBS: 0.24536051514937252
Fold 5 IBS: 0.2933809933550019
[I 2024-04-14 16:05:21,714] Trial 67 finished with value: 0.22336130579183777 and parameters: {'subsample': 0.3309533857642075, 'dropout_rate': 0.14931369576787984, 'n_estimators': 321, 'learning_rate': 0.02946289284113323}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1936859943370826
Fold 2 IBS: 0.27959895080979547
Fold 3 IBS: 0.2237559317505915
Fold 4 IBS: 0.3155048774790561
Fold 5 IBS: 0.3148856889492112
[I 2024-04-14 16:05:28,128] Trial 68 finished with value: 0.26548628866514734 and parameters: {'subsample': 0.19805022531133837, 'dropout_rate': 0.583662202262188, 'n_estimators': 496, 'learning_rate': 0.038155238832854765}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1944644699288984
Fold 2 IBS: 0.19889644126971573
Fold 3 IBS: 0.18088432291084286
Fold 4 IBS: 0.202069750948095
Fold 5 IBS: 0.21501098360946702
[I 2024-04-14 16:05:28,520] Trial 69 finished with value: 0.19826519373340382 and parameters: {'subsample': 0.13154921608577017, 'dropout_rate': 0.10818352444763235, 'n_estimators': 37, 'learning_rate': 0.04579016113529154}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.2042092235758531
Fold 2 IBS: 0.29942012829663384
Fold 3 IBS: 0.23552701427604117
Fold 4 IBS: 0.3212365868816139
Fold 5 IBS: 0.32053350973044126
[I 2024-04-14 16:05:33,022] Trial 70 finished with value: 0.27618529255211666 and parameters: {'subsample': 0.5299328063049298, 'dropout_rate': 0.1806794570956778, 'n_estimators': 408, 'learning_rate': 0.07134636849203568}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16861950679964197
Fold 2 IBS: 0.19435452830308808
Fold 3 IBS: 0.16955712159413444
Fold 4 IBS: 0.17131119756036767
Fold 5 IBS: 0.26200484859502887
[I 2024-04-14 16:05:33,718] Trial 71 finished with value: 0.19316944057045218 and parameters: {'subsample': 0.14278912872963992, 'dropout_rate': 0.21567313226194013, 'n_estimators': 107, 'learning_rate': 0.05266540628798919}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.17126869401945646
Fold 2 IBS: 0.1913394994821132
Fold 3 IBS: 0.16560099007675974
Fold 4 IBS: 0.1861194349001596
Fold 5 IBS: 0.24881874759101147
[I 2024-04-14 16:05:34,362] Trial 72 finished with value: 0.1926294732139001 and parameters: {'subsample': 0.17241312521672594, 'dropout_rate': 0.20064467313669482, 'n_estimators': 93, 'learning_rate': 0.04951438149116794}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1806174481304124
Fold 2 IBS: 0.19002274415720877
Fold 3 IBS: 0.16710258330566913
Fold 4 IBS: 0.1866992837244112
Fold 5 IBS: 0.23483655762487998
[I 2024-04-14 16:05:35,448] Trial 73 finished with value: 0.19185572338851628 and parameters: {'subsample': 0.1250703223166888, 'dropout_rate': 0.2723961921094384, 'n_estimators': 158, 'learning_rate': 0.020512531820716794}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1792179753383167
Fold 2 IBS: 0.19038352300089367
Fold 3 IBS: 0.16824465017208656
Fold 4 IBS: 0.18566925244578425
Fold 5 IBS: 0.23880218173432857
[I 2024-04-14 16:05:35,792] Trial 74 finished with value: 0.19246351653828195 and parameters: {'subsample': 0.22110918328341286, 'dropout_rate': 0.9624969956679588, 'n_estimators': 47, 'learning_rate': 0.07831544352981691}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1608159758533586
Fold 2 IBS: 0.20474730268531907
Fold 3 IBS: 0.17682717798709732
Fold 4 IBS: 0.20477758319681671
Fold 5 IBS: 0.2777775539540653
[I 2024-04-14 16:05:36,844] Trial 75 finished with value: 0.20498911873533138 and parameters: {'subsample': 0.18383409334462184, 'dropout_rate': 0.4968625102017052, 'n_estimators': 138, 'learning_rate': 0.05488888059303308}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.17634837687343466
Fold 2 IBS: 0.19104832793318685
Fold 3 IBS: 0.17088277522817272

Fold 4 IBS: 0.19225152703112275
Fold 5 IBS: 0.24483129098310055
[I 2024-04-14 16:05:37,508] Trial 76 finished with value: 0.19507245960980352 and parameters: {'subsample': 0.7158013476720768, 'dropout_rate': 0.13019725043087785, 'n_estimators': 75, 'learning_rate': 0.06127673455407747}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.20048691718406164
Fold 2 IBS: 0.2073649027207117
Fold 3 IBS: 0.1897554383249612
Fold 4 IBS: 0.21150446590995753
Fold 5 IBS: 0.21634700092017156
[I 2024-04-14 16:05:37,772] Trial 77 finished with value: 0.20509174501197275 and parameters: {'subsample': 0.1253062349895917, 'dropout_rate': 0.9060890066502643, 'n_estimators': 16, 'learning_rate': 0.05673526298023662}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16495807583311792
Fold 2 IBS: 0.19756648497686738
Fold 3 IBS: 0.17396450451531964
Fold 4 IBS: 0.1719002916858016
Fold 5 IBS: 0.2648373708929835
[I 2024-04-14 16:05:38,640] Trial 78 finished with value: 0.194645345580818 and parameters: {'subsample': 0.15638659943897548, 'dropout_rate': 0.23587576804659371, 'n_estimators': 118, 'learning_rate': 0.05297505481088832}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1652513278287801
Fold 2 IBS: 0.2157896421992984
Fold 3 IBS: 0.200728160599522
Fold 4 IBS: 0.25220358415624533
Fold 5 IBS: 0.2950209174353288
[I 2024-04-14 16:05:39,432] Trial 79 finished with value: 0.22579872644383495 and parameters: {'subsample': 0.25253112496351476, 'dropout_rate': 0.6701764979910259, 'n_estimators': 95, 'learning_rate': 0.0983514933405076}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1855009188998692
Fold 2 IBS: 0.19283569776761333
Fold 3 IBS: 0.17107858512759164
Fold 4 IBS: 0.19341081872000643
Fold 5 IBS: 0.22703415975048588
[I 2024-04-14 16:05:40,086] Trial 80 finished with value: 0.1939720360531133 and parameters: {'subsample': 0.21083282729472314, 'dropout_rate': 0.1541822993475877, 'n_estimators': 63, 'learning_rate': 0.041824926992796774}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.17867409811334958
Fold 2 IBS: 0.18993739745520816
Fold 3 IBS: 0.16648455224882255
Fold 4 IBS: 0.1855286312669227
Fold 5 IBS: 0.23582788104978455
[I 2024-04-14 16:05:41,406] Trial 81 finished with value: 0.19129051202681752 and parameters: {'subsample': 0.1198202112299331, 'dropout_rate': 0.28865731241034603, 'n_estimators': 163, 'learning_rate': 0.020627527568966752}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.2021975361177949
Fold 2 IBS: 0.20805236861083187
Fold 3 IBS: 0.18909694807027622
Fold 4 IBS: 0.211553869057228
Fold 5 IBS: 0.21567242921864105
[I 2024-04-14 16:05:41,987] Trial 82 finished with value: 0.20531463021495444 and parameters: {'subsample': 0.11534213258093495, 'dropout_rate': 0.294604952291048, 'n_estimators': 83, 'learning_rate': 0.010907606251756838}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.18093330222940296
Fold 2 IBS: 0.19058493249368985
Fold 3 IBS: 0.16814800836883215
Fold 4 IBS: 0.19004055701523667
Fold 5 IBS: 0.2346052396431055
[I 2024-04-14 16:05:43,507] Trial 83 finished with value: 0.19286240795005344 and parameters: {'subsample': 0.14451157755626098, 'dropout_rate': 0.19658411026680572, 'n_estimators': 186, 'learning_rate': 0.016959745355074107}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.20266405991661726
Fold 2 IBS: 0.20700095570593602
Fold 3 IBS: 0.1884111223364496
Fold 4 IBS: 0.21196197567597314
Fold 5 IBS: 0.21590071189123888
[I 2024-04-14 16:05:44,306] Trial 84 finished with value: 0.205187765105243 and parameters: {'subsample': 0.17546575897395367, 'dropout_rate': 0.4185483826646459, 'n_estimators': 106, 'learning_rate': 0.008854543626086779}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16663628711773576
Fold 2 IBS: 0.18996948573063824
Fold 3 IBS: 0.16334234094015934
Fold 4 IBS: 0.1731045654404081
Fold 5 IBS: 0.24814662557867545
[I 2024-04-14 16:05:45,946] Trial 85 finished with value: 0.18823986096152337 and parameters: {'subsample': 0.10242620997977529, 'dropout_rate': 0.32728801230978943, 'n_estimators': 210, 'learning_rate': 0.02385665186334581}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16582463215253943
Fold 2 IBS: 0.19258724423626503
Fold 3 IBS: 0.16396795136265313
Fold 4 IBS: 0.17364801202514635
Fold 5 IBS: 0.2549657633334204
[I 2024-04-14 16:05:47,483] Trial 86 finished with value: 0.19019872062200488 and parameters: {'subsample': 0.11512452425383443, 'dropout_rate': 0.3232340824764945, 'n_estimators': 218, 'learning_rate': 0.02337188448046181}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16297905611550417
Fold 2 IBS: 0.19235518294519
Fold 3 IBS: 0.16461446866235876
Fold 4 IBS: 0.17102685103707493
Fold 5 IBS: 0.26200880138611504
[I 2024-04-14 16:05:48,893] Trial 87 finished with value: 0.19059687202924858 and parameters: {'subsample': 0.10135600423514604, 'dropout_rate': 0.38094793285661743, 'n_estimators': 209, 'learning_rate': 0.027604515620693}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16684704109019216
Fold 2 IBS: 0.1898584211477013
Fold 3 IBS: 0.1631300475079879
Fold 4 IBS: 0.17310713847913237
Fold 5 IBS: 0.2530252604602008
[I 2024-04-14 16:05:50,292] Trial 88 finished with value: 0.1891935817370429 and parameters: {'subsample': 0.10165359567952403, 'dropout_rate': 0.4005550335962743, 'n_estimators': 206, 'learning_rate': 0.024099543252977373}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1647736709186713
Fold 2 IBS: 0.1929881853284999
Fold 3 IBS: 0.1660623081645636
Fold 4 IBS: 0.177984252474281
Fold 5 IBS: 0.25680108769060983
[I 2024-04-14 16:05:51,827] Trial 89 finished with value: 0.1917219009153251 and parameters: {'subsample': 0.10062064924302194, 'dropout_rate': 0.547816026996555, 'n_estimators': 217, 'learning_rate': 0.025056796383218}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.17050822000868152
Fold 2 IBS: 0.1926407968944445
Fold 3 IBS: 0.16811802837473305
Fold 4 IBS: 0.18643213485722554
Fold 5 IBS: 0.257938497827182
[I 2024-04-14 16:05:53,984] Trial 90 finished with value: 0.19512753559245333 and parameters: {'subsample': 0.1989800370804572, 'dropout_rate': 0.3871485607424056, 'n_estimators': 260, 'learning_rate': 0.017894776696135192}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16874916092905973
Fold 2 IBS: 0.19111461686669312
Fold 3 IBS: 0.16398988181893653
Fold 4 IBS: 0.1758316967243901
Fold 5 IBS: 0.24876839146406926
[I 2024-04-14 16:05:55,463] Trial 91 finished with value: 0.18969074956062976 and parameters: {'subsample': 0.11662786547735388, 'dropout_rate': 0.45657785560785213, 'n_estimators': 208, 'learning_rate': 0.021627505531494128}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1704613531600452
Fold 2 IBS: 0.19094493744409308
Fold 3 IBS: 0.1651108295551241
Fold 4 IBS: 0.17639253609023264
Fold 5 IBS: 0.2490798613766612
[I 2024-04-14 16:05:56,990] Trial 92 finished with value: 0.19039790352523125 and parameters: {'subsample': 0.12148966707467249, 'dropout_rate': 0.42477381159880423, 'n_estimators': 209, 'learning_rate': 0.021674391717027577}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1640261313803742
Fold 2 IBS: 0.19306960999153466
Fold 3 IBS: 0.16443499284924312
Fold 4 IBS: 0.17421545427158722
Fold 5 IBS: 0.257364704917278
[I 2024-04-14 16:05:59,618] Trial 93 finished with value: 0.19062217868200343 and parameters: {'subsample': 0.11515232263308812, 'dropout_rate': 0.44973963310007453, 'n_estimators': 241, 'learning_rate': 0.022023566287188323}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16524161272199836
Fold 2 IBS: 0.19409233311474056
Fold 3 IBS: 0.16678471547376406
Fold 4 IBS: 0.17641073831303106
Fold 5 IBS: 0.2609217570169164
[I 2024-04-14 16:06:01,577] Trial 94 finished with value: 0.1926902313280901 and parameters: {'subsample': 0.11956417062432721, 'dropout_rate': 0.4464767055263928, 'n_estimators': 241, 'learning_rate': 0.022713835873377913}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1651553904694927
Fold 2 IBS: 0.19947196641958245
Fold 3 IBS: 0.1704010673670612

Fold 4 IBS: 0.19194585623129345
Fold 5 IBS: 0.2725075187014806
[I 2024-04-14 16:06:03,064] Trial 95 finished with value: 0.1998963598377821 and parameters: {'subsample': 0.15581855729613242, 'dropout_rate': 0.4970595697042566, 'n_estimators': 214, 'learning_rate': 0.029994587608032502}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.1684853889941405
Fold 2 IBS: 0.1898378515109147
Fold 3 IBS: 0.16348142475190114
Fold 4 IBS: 0.17300211213188432
Fold 5 IBS: 0.2517731530441877
[I 2024-04-14 16:06:04,389] Trial 96 finished with value: 0.18931598608660566 and parameters: {'subsample': 0.10088444704400297, 'dropout_rate': 0.4137282240267256, 'n_estimators': 179, 'learning_rate': 0.0269141539102375}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16741374104074316
Fold 2 IBS: 0.1947282103384171
Fold 3 IBS: 0.1660941001615167
Fold 4 IBS: 0.1824650024349122
Fold 5 IBS: 0.25946103645491997
[I 2024-04-14 16:06:06,582] Trial 97 finished with value: 0.1940324180861018 and parameters: {'subsample': 0.14582369610303933, 'dropout_rate': 0.407760927959692, 'n_estimators': 204, 'learning_rate': 0.026249424671687744}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.15950059915856557
Fold 2 IBS: 0.21218032370490145
Fold 3 IBS: 0.18535252819341583
Fold 4 IBS: 0.22203254950409443
Fold 5 IBS: 0.2912069726961742
[I 2024-04-14 16:06:09,324] Trial 98 finished with value: 0.21405459465143029 and parameters: {'subsample': 0.18078346224526556, 'dropout_rate': 0.36313000021764696, 'n_estimators': 276, 'learning_rate': 0.03255286246127822}. Best is trial 51 with value: 0.18758692413271766.
Fold 1 IBS: 0.16630696434672831
Fold 2 IBS: 0.19110779226079527
Fold 3 IBS: 0.16352778567312543
Fold 4 IBS: 0.1721678654100502
Fold 5 IBS: 0.2570091555477983
[I 2024-04-14 16:06:11,356] Trial 99 finished with value: 0.19002391264769952 and parameters: {'subsample': 0.10062180005394816, 'dropout_rate': 0.38292148455467356, 'n_estimators': 183, 'learning_rate': 0.028734303800990554}. Best is trial 51 with value: 0.18758692413271766.


* Best trial for IBS:
 FrozenTrial(number=51, state=TrialState.COMPLETE, values=[0.18758692413271766], datetime_start=datetime.datetime(2024, 4, 14, 16, 5, 6, 968483), datetime_complete=datetime.datetime(2024, 4, 14, 16, 5, 7, 572379), params={'subsample': 0.143043777223833, 'dropout_rate': 0.10045382034687865, 'n_estimators': 79, 'learning_rate': 0.05674565223918392}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=51, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.143043777223833, 'dropout_rate': 0.10045382034687865, 'n_estimators': 79, 'learning_rate': 0.05674565223918392}


* Best Score for IBS:
 0.18758692413271766

In [234]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [235]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.739
train_ibs:  0.188

#### Test

In [236]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [237]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6911773987018819,
                                              learning_rate=0.0038777019677429035,
                                              n_estimators=313,
                                              random_state=123,
                                              subsample=0.10055409799174729)

C-index score: 0.514

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10045382034687865,
                                              learning_rate=0.05674565223918392,
                                              n_estimators=79, random_state=123,
                                              subsample=0.143043777223833)

IBS: 0.238

In [238]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [239]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.855   1.0
ExtraSurvivalTrees               0.848   2.0
CoxPH                            0.763   3.0
CoxElastic                       0.761   4.0
CoxLasso                         0.760   5.0
GradientBoosting                 0.740   6.0
ComponentwiseGradientBoosting    0.739   7.0
CoxRidge                         0.688   8.0

In [240]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxPH                          0.180   2.0
CoxElastic                     0.180   2.0
ExtraSurvivalTrees             0.180   2.0
CoxLasso                       0.181   4.0
Randomsurvivalforest           0.182   5.0
ComponentwiseGradientBoosting  0.188   6.0
GradientBoosting               0.215   7.0
CoxRidge                       0.217   8.0

In [241]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.643   1.0
GradientBoosting                 0.612   2.0
ExtraSurvivalTrees               0.610   3.0
CoxLasso                         0.577   4.5
CoxElastic                       0.577   4.5
CoxPH                            0.572   6.0
CoxRidge                         0.534   7.0
ComponentwiseGradientBoosting    0.514   8.0

In [242]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
Randomsurvivalforest           0.206   1.0
GradientBoosting               0.220   2.0
CoxRidge                       0.221   3.0
ExtraSurvivalTrees             0.230   4.0
ComponentwiseGradientBoosting  0.238   5.0
CoxLasso                       0.269   6.5
CoxElastic                     0.269   6.5
CoxPH                          0.274   8.0

In [243]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/yeojohnson/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_os_yeojohnson_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [244]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14