In [13]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
  
from sklearn.preprocessing import PowerTransformer

In [15]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [17]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [19]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

## Test dataset: MAASTRO

In [21]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [23]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [25]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [27]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [29]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [31]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [33]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [35]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [37]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [39]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [41]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

In [43]:
# Choose features from the result of Cox PLSR in R
selectd_features = [
"first_order_Maximum_CT",
"LBP_201_PET",
"LBP_102_PET",
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16",
"LBP_003_PET",
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2"    
]

In [45]:
X_plsr = X.loc[:, selectd_features]
X_new = X_plsr.copy()

In [47]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selectd_features]

# Yeo-Johnson Transformation

In [49]:
# Copy the original X for later 
original_X = X.copy()

In [51]:
# Transform X_new 
# Set the categorical_columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Apply Yeo-Johnson transformation
pt = PowerTransformer(method='yeo-johnson')
X_new_numeric_transformed = pt.fit_transform(X_new_numeric)

# Create DataFrame with transformed numerical data
X_new_numeric_transformed = pd.DataFrame(X_new_numeric_transformed, 
                                         columns=X_new_numeric.columns, 
                                         index=X_new.index)

# Concatenate transformed numerical data with categorical data
X_new_std = pd.concat([X_new_numeric_transformed, X_new_categoric], axis=1)

# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the transformation for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[X_new.columns]

In [53]:
X_new

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,1763.283818,0.000062,0.000000,0.000416,0.000123,0.000959
1,1432.109636,0.000349,0.000000,0.001753,0.000349,0.002776
2,1685.931373,0.000000,0.000034,0.000230,0.000000,0.001179
3,1329.347515,0.000000,0.000000,0.000711,0.000300,0.002748
4,1197.225910,0.000399,0.000199,0.001033,0.000000,0.002309
...,...,...,...,...,...,...
134,1267.959716,0.000000,0.000000,0.000226,0.000000,0.001347
135,1788.278096,0.000079,0.000000,0.000183,0.000039,0.000850
136,1478.297861,0.000000,0.000000,0.000621,0.000000,0.001111
137,1207.068493,0.000054,0.000000,0.000265,0.000000,0.000935
138,1368.499199,0.000000,0.000000,0.000421,0.000000,0.000629

In [55]:
X_new_std

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,1.022943,-0.074611,-0.784694,-0.128003,1.042615,-0.456825
1,0.072727,1.689445,-0.784694,1.761655,1.929439,1.829690
2,0.853782,-1.065926,0.236612,-0.861897,-0.799521,0.033412
3,-0.390532,-1.065926,-0.784694,0.668885,1.846691,1.814149
4,-1.187658,1.782787,1.784568,1.208077,-0.799521,1.522029
...,...,...,...,...,...,...
134,-0.727488,-1.065926,-0.784694,-0.877225,-0.799521,0.352487
135,1.072604,0.138716,-0.784694,-1.082845,-0.000653,-0.735470
136,0.247868,-1.065926,-0.784694,0.464990,-0.799521,-0.108155
137,-1.118344,-0.175482,-0.784694,-0.706059,-0.799521,-0.515193
138,-0.200688,-1.065926,-0.784694,-0.112899,-0.799521,-1.381293

In [57]:
MAASTRO_new

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,1226.795917,0.000026,0.000026,0.000241,0.000026,0.000768
1,1876.570382,0.000167,0.000167,0.000621,0.000056,0.001213
2,1269.217095,0.000000,0.000057,0.000327,0.000286,0.001176
3,1951.924395,0.000080,0.000000,0.001419,0.000160,0.001192
4,1646.853670,0.000035,0.000000,0.000165,0.000071,0.000766
...,...,...,...,...,...,...
94,2311.845731,0.000078,0.000000,0.000739,0.000000,0.001137
95,1299.857157,0.000054,0.000000,0.001130,0.000109,0.000962
96,1256.024949,0.000028,0.000000,0.000226,0.000000,0.000621
97,1668.742962,0.000000,0.000000,0.000296,0.000114,0.000947
98,1654.841840,0.000112,0.000000,0.001394,0.000000,0.001661

In [59]:
MAASTRO_new_std

,first_order_Maximum_CT,LBP_201_PET,LBP_102_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16,LBP_003_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2
0,-0.984802,-0.597387,0.033184,-0.811666,-0.238970,-0.960377
1,1.231237,0.946684,1.682719,0.464229,0.263801,0.101598
2,-0.720051,-1.065926,0.693043,-0.453072,1.817599,0.027699
3,1.348682,0.152800,-0.784694,1.579512,1.314752,0.060650
4,0.758335,-0.453142,-0.784694,-1.171859,0.471935,-0.967045
...,...,...,...,...,...,...
94,1.750433,0.126817,-0.784694,0.727222,-0.799521,-0.052777
95,-0.545966,-0.173978,-0.784694,1.322893,0.907497,-0.450240
96,-0.799285,-0.565019,-0.784694,-0.877027,-0.799521,-1.409205
97,0.812692,-1.065926,-0.784694,-0.577241,0.962590,-0.485449
98,0.778442,0.498900,-0.784694,1.561904,-0.799521,0.840017

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [61]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 04:30:45,497] A new study created in memory with name: no-name-746e3e9b-43f7-4972-a56e-0bace4227d16

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6075949367088608

[I 2024-04-19 04:30:47,375] A new study created in memory with name: no-name-864484f1-cac2-4ab5-978f-193cb14662af

Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:30:47,316] Trial 0 finished with value: 0.6640896071389869 and parameters: {}. Best is trial 0 with value: 0.6640896071389869.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6640896071389869], datetime_start=datetime.datetime(2024, 4, 19, 4, 30, 45, 649878), datetime_complete=datetime.datetime(2024, 4, 19, 4, 30, 47, 313302), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6640896071389869

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.19675872550942683
Fold 2 IBS: 0.1783326995533363
Fold 3 IBS: 0.18580016536387306
Fold 4 IBS: 0.2148920002265226
Fold 5 IBS: 0.23991728125827994
[I 2024-04-19 04:30:49,605] Trial 0 finished with value: 0.20314017438228776 and parameters: {}. Best is trial 0 with value: 0.20314017438228776.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20314017438228776], datetime_start=datetime.datetime(2024, 4, 19, 4, 30, 47, 552936), datetime_complete=datetime.datetime(2024, 4, 19, 4, 30, 49, 604428), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20314017438228776

In [63]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [65]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.666
train_ibs:  0.203

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.586
IBS score: 0.239

In [71]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [72]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 04:31:18,420] A new study created in memory with name: no-name-354004f3-c443-49b5-8d47-a3d9be87b4b9

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5952380952380952
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.70042194092827

[I 2024-04-19 04:31:19,863] A new study created in memory with name: no-name-e774119d-9ae3-4778-855d-95344f42aaef

Fold 5 C-index: 0.647887323943662
[I 2024-04-19 04:31:19,780] Trial 0 finished with value: 0.6753341218819494 and parameters: {}. Best is trial 0 with value: 0.6753341218819494.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6753341218819494], datetime_start=datetime.datetime(2024, 4, 19, 4, 31, 18, 627377), datetime_complete=datetime.datetime(2024, 4, 19, 4, 31, 19, 779800), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6753341218819494

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651842800988
Fold 2 IBS: 0.2215779102658637
Fold 3 IBS: 0.20453594230284272
Fold 4 IBS: 0.22473803637388992
Fold 5 IBS: 0.2181243145661695
[I 2024-04-19 04:31:21,569] Trial 0 finished with value: 0.21659054438735512 and parameters: {}. Best is trial 0 with value: 0.21659054438735512.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054438735512], datetime_start=datetime.datetime(2024, 4, 19, 4, 31, 20, 269430), datetime_complete=datetime.datetime(2024, 4, 19, 4, 31, 21, 568572), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054438735512

In [74]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [75]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.675
train_ibs:  0.217

#### Test

In [76]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [77]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.616

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [78]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [79]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 04:31:22,406] A new study created in memory with name: no-name-8260b3ae-b65f-4ca9-8487-09da5fba7796

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608

[I 2024-04-19 04:31:25,340] A new study created in memory with name: no-name-b482b541-364e-43f4-9730-f7793b8807eb

Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:25,294] Trial 0 finished with value: 0.6659628564387068 and parameters: {}. Best is trial 0 with value: 0.6659628564387068.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6659628564387068], datetime_start=datetime.datetime(2024, 4, 19, 4, 31, 22, 586109), datetime_complete=datetime.datetime(2024, 4, 19, 4, 31, 25, 293445), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6659628564387068

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.19563802137250225
Fold 2 IBS: 0.17860209501109262
Fold 3 IBS: 0.18572177672598686
Fold 4 IBS: 0.2142665104146998
Fold 5 IBS: 0.23919274264809653
[I 2024-04-19 04:31:28,833] Trial 0 finished with value: 0.20268422923447563 and parameters: {}. Best is trial 0 with value: 0.20268422923447563.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20268422923447563], datetime_start=datetime.datetime(2024, 4, 19, 4, 31, 25, 410467), datetime_complete=datetime.datetime(2024, 4, 19, 4, 31, 28, 832496), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20268422923447563

In [80]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [81]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.666
train_ibs:  0.203

#### Test

In [82]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [83]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.588

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.238

In [84]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [85]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 04:31:30,206] A new study created in memory with name: no-name-af1496be-e53a-4dfd-8e5d-a2aaf34d6dea

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:32,658] Trial 0 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6650699992958496.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:35,391] Trial 1 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6650699992958496.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:38,446] Trial 2 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6650699992958496.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:40,704] Trial 3 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6650699992958496.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:43,093] Trial 4 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6650699992958496.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:45,465] Trial 5 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6650699992958496.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:47,838] Trial 6 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:50,260] Trial 7 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:52,883] Trial 8 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:55,827] Trial 9 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:31:58,143] Trial 10 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:01,105] Trial 11 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:03,989] Trial 12 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:06,589] Trial 13 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:09,850] Trial 14 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:12,083] Trial 15 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:14,822] Trial 16 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:17,449] Trial 17 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:20,283] Trial 18 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:22,694] Trial 19 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:25,452] Trial 20 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:28,130] Trial 21 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:30,611] Trial 22 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.9952149413953396}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:33,553] Trial 23 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.8898693182098678}. Best is trial 6 with value: 0.6659628564387068.

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:36,160] Trial 24 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:39,019] Trial 25 finished with value: 0.6659628564387068 and parameters: {'l1_ratio': 0.9368557715647121}. Best is trial 6 with value: 0.6659628564387068.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:32:40,179] Trial 26 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:32:41,737] Trial 27 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:32:43,063] Trial 28 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.01626846455091114}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:32:44,481] Trial 29 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.016175696683504215}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:32:45,739] Trial 30 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.0012154994010131932}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:32:47,089] Trial 31 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.00012703664653388076}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:50,256] Trial 32 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.10289004005540359}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:53,654] Trial 33 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.09759078578935104}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:56,538] Trial 34 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.21553914253693035}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:32:59,557] Trial 35 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.1844792199975079}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:03,609] Trial 36 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.06305566571241641}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:07,150] Trial 37 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.2782358726057584}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:10,482] Trial 38 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.14443330911816266}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:13,722] Trial 39 finished with value: 0.6616067958326461 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:16,995] Trial 40 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.33542590225852514}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:33:18,481] Trial 41 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.00896914124159653}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:21,483] Trial 42 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.15306577655298592}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:24,821] Trial 43 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.04844254797607179}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:27,649] Trial 44 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.14130414873999636}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:30,404] Trial 45 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.2519528402290643}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:33,208] Trial 46 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.05000976318706715}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697

Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:33:34,151] Trial 47 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.01366650336233158}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:36,961] Trial 48 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.08891191758251386}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:39,555] Trial 49 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.18318195239603682}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:41,983] Trial 50 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.31297686520002327}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:33:43,308] Trial 51 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.006440752943402048}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:45,114] Trial 52 finished with value: 0.6775426005342736 and parameters: {'l1_ratio': 0.03516028800284399}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:47,831] Trial 53 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.11992944861538461}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:50,362] Trial 54 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.07414327234641538}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:52,810] Trial 55 finished with value: 0.6775426005342736 and parameters: {'l1_ratio': 0.028633754220212325}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:55,409] Trial 56 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.19735510614319607}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:33:57,613] Trial 57 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.6246196826499275}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:00,409] Trial 58 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.42178589378695625}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:03,149] Trial 59 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.4986933461973026}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:05,655] Trial 60 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.07331191156478757}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:34:06,924] Trial 61 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.0018425035317285489}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:09,603] Trial 62 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.12733536947199928}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:34:11,148] Trial 63 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.02021777411387443}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:13,743] Trial 64 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.06818714331584337}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:34:15,241] Trial 65 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.001099647533724388}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:17,800] Trial 66 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.10521698022304518}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:20,470] Trial 67 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.16946048489101645}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:22,930] Trial 68 finished with value: 0.6616067958326461 and parameters: {'l1_ratio': 0.04077188776362027}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:25,960] Trial 69 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.08622072771270425}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:28,771] Trial 70 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.12401374118777451}. Best is trial 26 with value: 0.6805205170529939.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:34:29,986] Trial 71 finished with value: 0.6805205170529939 and parameters: {'l1_ratio': 0.014725563748040777}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:31,773] Trial 72 finished with value: 0.6775426005342736 and parameters: {'l1_ratio': 0.025748944276739162}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:34,716] Trial 73 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.06024071084300721}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:34:35,766] Trial 74 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.0021541572809729865}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:38,067] Trial 75 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.0928593204765475}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:40,941] Trial 76 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.053094624190746065}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:34:42,017] Trial 77 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.020483477829814453}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:44,441] Trial 78 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.15354206987993527}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:46,888] Trial 79 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.11365337277209968}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:49,372] Trial 80 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.22520269450675956}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:34:50,345] Trial 81 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.002119383188532457}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:52,681] Trial 82 finished with value: 0.6775426005342736 and parameters: {'l1_ratio': 0.03163714494713934}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:55,825] Trial 83 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.05157183699355799}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:34:58,764] Trial 84 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.07635615314488461}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:35:00,368] Trial 85 finished with value: 0.6747256991258229 and parameters: {'l1_ratio': 0.021968450048151476}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:03,564] Trial 86 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.06444599524927197}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:35:04,654] Trial 87 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.00026240465041552606}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:07,180] Trial 88 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.09410784853468104}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:09,333] Trial 89 finished with value: 0.6598210815469319 and parameters: {'l1_ratio': 0.03913516693193171}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:11,709] Trial 90 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.5485323194707394}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:35:12,898] Trial 91 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.021032480406439517}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:15,434] Trial 92 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.05566473952391516}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:18,272] Trial 93 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.08141958643656944}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902

Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:35:19,646] Trial 94 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.020414012906665356}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:22,236] Trial 95 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.6870711567804066}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:24,882] Trial 96 finished with value: 0.6650699992958496 and parameters: {'l1_ratio': 0.1343084889624756}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:27,457] Trial 97 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.10902442485479938}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6075949367088608
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:35:30,234] Trial 98 finished with value: 0.6642041984300489 and parameters: {'l1_ratio': 0.04369334648973928}. Best is trial 26 with value: 0.6805205170529939.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697

[I 2024-04-19 04:35:31,321] A new study created in memory with name: no-name-98f0f350-7d8a-4975-bcd6-ca52bf938c5c

Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 04:35:31,306] Trial 99 finished with value: 0.6796276599101366 and parameters: {'l1_ratio': 0.0006058001767646429}. Best is trial 26 with value: 0.6805205170529939.


* Best trial for C-index:
 FrozenTrial(number=26, state=TrialState.COMPLETE, values=[0.6805205170529939], datetime_start=datetime.datetime(2024, 4, 19, 4, 32, 39, 84684), datetime_complete=datetime.datetime(2024, 4, 19, 4, 32, 40, 177846), params={'l1_ratio': 0.015423757551295547}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=26, value=None)


* Best Score for C-index:
 0.6805205170529939

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19567677986005333
Fold 2 IBS: 0.17857093604269592
Fold 3 IBS: 0.18572718284313966
Fold 4 IBS: 0.21425221710181686
Fold 5 IBS: 0.239091161099382
[I 2024-04-19 04:35:33,729] Trial 0 finished with value: 0.20266365538941758 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.20266365538941758.
Fold 1 IBS: 0.1959198487054693
Fold 2 IBS: 0.17847730434007683
Fold 3 IBS: 0.1857458148783586
Fold 4 IBS: 0.2142847137128549
Fold 5 IBS: 0.23874367666989163
[I 2024-04-19 04:35:36,529] Trial 1 finished with value: 0.20263427166133025 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.20263427166133025.
Fold 1 IBS: 0.19600075027660835
Fold 2 IBS: 0.1784456415189215
Fold 3 IBS: 0.18575148926036986
Fold 4 IBS: 0.21425593723877995
Fold 5 IBS: 0.23870102337363563
[I 2024-04-19 04:35:39,389] Trial 2 finished with value: 0.20263096833366304 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.19577243017558496
Fold 2 IBS: 0.17854415888525005
Fold 3 IBS: 0.1857320361935748
Fold 4 IBS: 0.2142536617748378
Fold 5 IBS: 0.23898980410882378
[I 2024-04-19 04:35:42,211] Trial 3 finished with value: 0.20265841822761427 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.19567926818859227
Fold 2 IBS: 0.17857149631212077
Fold 3 IBS: 0.18572697190737344
Fold 4 IBS: 0.2142594701725086
Fold 5 IBS: 0.23911407134676219
[I 2024-04-19 04:35:44,779] Trial 4 finished with value: 0.20267025558547144 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.1958000626997317
Fold 2 IBS: 0.178518992036383
Fold 3 IBS: 0.1857370918394511
Fold 4 IBS: 0.21424138398917386
Fold 5 IBS: 0.23893389190316883
[I 2024-04-19 04:35:47,181] Trial 5 finished with value: 0.20264628449358169 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.19563684373381637
Fold 2 IBS: 0.17860180532655634
Fold 3 IBS: 0.18572187985806551
Fold 4 IBS: 0.21426308355125095
Fold 5 IBS: 0.23924305403213034
[I 2024-04-19 04:35:49,569] Trial 6 finished with value: 0.20269333330036393 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.19573464662474596
Fold 2 IBS: 0.17857064145998078
Fold 3 IBS: 0.18572729766849658
Fold 4 IBS: 0.21424836605559394
Fold 5 IBS: 0.23907899674747687
[I 2024-04-19 04:35:51,888] Trial 7 finished with value: 0.20267198971125883 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.19576031516437087
Fold 2 IBS: 0.17854153894345373
Fold 3 IBS: 0.18573336132802917
Fold 4 IBS: 0.21427440099487655
Fold 5 IBS: 0.2389591634629259
[I 2024-04-19 04:35:54,148] Trial 8 finished with value: 0.20265375597873128 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.1958410608193237
Fold 2 IBS: 0.17851748118034794
Fold 3 IBS: 0.18573823969195333
Fold 4 IBS: 0.21427558260541676
Fold 5 IBS: 0.23886443709316768
[I 2024-04-19 04:35:56,694] Trial 9 finished with value: 0.20264736027804192 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.20263096833366304.
Fold 1 IBS: 0.196167287551877
Fold 2 IBS: 0.1783636527872284
Fold 3 IBS: 0.18576812394235237
Fold 4 IBS: 0.21426145992059556
Fold 5 IBS: 0.23853053004200747
[I 2024-04-19 04:35:59,424] Trial 10 finished with value: 0.20261821084881215 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.20261821084881215.
Fold 1 IBS: 0.21355449162837645
Fold 2 IBS: 0.22076022560160116
Fold 3 IBS: 0.20393910375396407
Fold 4 IBS: 0.22414493020805126
Fold 5 IBS: 0.2180471996323647
[I 2024-04-19 04:36:00,843] Trial 11 finished with value: 0.21608919016487152 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.20261821084881215.
Fold 1 IBS: 0.19616689290829634
Fold 2 IBS: 0.17836363468789782
Fold 3 IBS: 0.18576813332499964
Fold 4 IBS: 0.21426094940688367
Fold 5 IBS: 0.23852918123477804
[I 2024-04-19 04:36:03,482] Trial 12 finished with value: 0.2026177583125711 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.2026177583125711.
Fold 1 IBS: 0.21386452051842889
Fold 2 IBS: 0.2213586691896521
Fold 3 IBS: 0.2043767047825539
Fold 4 IBS: 0.2245789104608679
Fold 5 IBS: 0.21810276976185058
[I 2024-04-19 04:36:04,807] Trial 13 finished with value: 0.21645631494267067 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.2026177583125711.
Fold 1 IBS: 0.19609656307207343
Fold 2 IBS: 0.17840610785586694
Fold 3 IBS: 0.18575978272375973
Fold 4 IBS: 0.21429001730709515
Fold 5 IBS: 0.23861186796784076
[I 2024-04-19 04:36:08,350] Trial 14 finished with value: 0.20263286778532721 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.2026177583125711.
Fold 1 IBS: 0.19610126191422342
Fold 2 IBS: 0.1784063555145123
Fold 3 IBS: 0.18575962749537867
Fold 4 IBS: 0.214240415196418
Fold 5 IBS: 0.23862793361708057
[I 2024-04-19 04:36:10,815] Trial 15 finished with value: 0.2026271187475226 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.2026177583125711.
Fold 1 IBS: 0.1960732438022964
Fold 2 IBS: 0.17840495202285647
Fold 3 IBS: 0.18576129323719798
Fold 4 IBS: 0.21426219417749287
Fold 5 IBS: 0.23853183350154658
[I 2024-04-19 04:36:13,041] Trial 16 finished with value: 0.20260670334827804 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 16 with value: 0.20260670334827804.
Fold 1 IBS: 0.19591974976143778
Fold 2 IBS: 0.1784772451987322
Fold 3 IBS: 0.18574584677795858
Fold 4 IBS: 0.21428371011940128
Fold 5 IBS: 0.23874052159977577
[I 2024-04-19 04:36:15,220] Trial 17 finished with value: 0.20263341469146115 and parameters: {'l1_ratio': 0.2853691373958437}. Best is trial 16 with value: 0.20260670334827804.
Fold 1 IBS: 0.19598878912886344
Fold 2 IBS: 0.17844449431857606
Fold 3 IBS: 0.18575206738245012
Fold 4 IBS: 0.21428908229457802
Fold 5 IBS: 0.23863517921468186
[I 2024-04-19 04:36:18,141] Trial 18 finished with value: 0.2026219224678299 and parameters: {'l1_ratio': 0.21416053383156064}. Best is trial 16 with value: 0.20260670334827804.
Fold 1 IBS: 0.19587367382271473
Fold 2 IBS: 0.1784959690530044
Fold 3 IBS: 0.1857424052143616
Fold 4 IBS: 0.2142743853030839
Fold 5 IBS: 0.23878222991695208
[I 2024-04-19 04:36:20,382] Trial 19 finished with value: 0.2026337326620234 and parameters: {'l1_ratio': 0.32722716564021426}. Best is trial 16 with value: 0.20260670334827804.
Fold 1 IBS: 0.19563423288683005
Fold 2 IBS: 0.17860116754018898
Fold 3 IBS: 0.18572211445169193
Fold 4 IBS: 0.21425547202589557
Fold 5 IBS: 0.23921894696024948
[I 2024-04-19 04:36:22,606] Trial 20 finished with value: 0.20268638677297118 and parameters: {'l1_ratio': 0.9405325330891504}. Best is trial 16 with value: 0.20260670334827804.
Fold 1 IBS: 0.19613160317185907
Fold 2 IBS: 0.17837760025682403
Fold 3 IBS: 0.18576553634682488
Fold 4 IBS: 0.2142925782531913
Fold 5 IBS: 0.23851956038376088
[I 2024-04-19 04:36:25,076] Trial 21 finished with value: 0.20261737568249205 and parameters: {'l1_ratio': 0.10039375875562537}. Best is trial 16 with value: 0.20260670334827804.
Fold 1 IBS: 0.19611912380193605
Fold 2 IBS: 0.17837704914154848
Fold 3 IBS: 0.18576591758205765
Fold 4 IBS: 0.21427764633300705
Fold 5 IBS: 0.23847670937709972
[I 2024-04-19 04:36:27,457] Trial 22 finished with value: 0.2026032892471298 and parameters: {'l1_ratio': 0.09719212464432796}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19606310168662353
Fold 2 IBS: 0.17839629312999697
Fold 3 IBS: 0.18576154686464977
Fold 4 IBS: 0.214250043345763
Fold 5 IBS: 0.23861674877655667
[I 2024-04-19 04:36:29,628] Trial 23 finished with value: 0.202617546760718 and parameters: {'l1_ratio': 0.13106172654563228}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19599382900312057
Fold 2 IBS: 0.17844478671641292
Fold 3 IBS: 0.18575190946667822
Fold 4 IBS: 0.2142389234470655
Fold 5 IBS: 0.23865253967863775
[I 2024-04-19 04:36:32,011] Trial 24 finished with value: 0.202616397662383 and parameters: {'l1_ratio': 0.21736087814603194}. Best is trial 22 with value: 0.2026032892471298.

Fold 1 IBS: 0.19602833763428143
Fold 2 IBS: 0.17843162840626733
Fold 3 IBS: 0.18575424861725504
Fold 4 IBS: 0.21425998252982092
Fold 5 IBS: 0.23865919831968643
[I 2024-04-19 04:36:34,187] Trial 25 finished with value: 0.20262667910146223 and parameters: {'l1_ratio': 0.1987244050980175}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19583018440273753
Fold 2 IBS: 0.17849747496561694
Fold 3 IBS: 0.1857416331490958
Fold 4 IBS: 0.21424207986970434
Fold 5 IBS: 0.2388567915020896
[I 2024-04-19 04:36:36,188] Trial 26 finished with value: 0.20263363277784885 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19571965174961367
Fold 2 IBS: 0.1785447131755078
Fold 3 IBS: 0.18573182518062856
Fold 4 IBS: 0.21426135998165247
Fold 5 IBS: 0.23901391113707188
[I 2024-04-19 04:36:38,261] Trial 27 finished with value: 0.2026542922448949 and parameters: {'l1_ratio': 0.5681788491232276}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19596145782102892
Fold 2 IBS: 0.17846024665373283
Fold 3 IBS: 0.18574891335784832
Fold 4 IBS: 0.2142342721181871
Fold 5 IBS: 0.23869738858461723
[I 2024-04-19 04:36:40,826] Trial 28 finished with value: 0.2026204557070829 and parameters: {'l1_ratio': 0.24906192963492235}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19621468931296412
Fold 2 IBS: 0.17834042504849112
Fold 3 IBS: 0.18577387628207812
Fold 4 IBS: 0.21428297432185822
Fold 5 IBS: 0.23849095647414212
[I 2024-04-19 04:36:43,363] Trial 29 finished with value: 0.20262058428790675 and parameters: {'l1_ratio': 0.05082993760503683}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19605307486826423
Fold 2 IBS: 0.17842948712629747
Fold 3 IBS: 0.18575543722731677
Fold 4 IBS: 0.21427078572690567
Fold 5 IBS: 0.23864177512165147
[I 2024-04-19 04:36:45,705] Trial 30 finished with value: 0.20263011201408712 and parameters: {'l1_ratio': 0.1779240087330034}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19612338217026623
Fold 2 IBS: 0.17837723291080068
Fold 3 IBS: 0.18576578333714044
Fold 4 IBS: 0.21428274670221947
Fold 5 IBS: 0.23849133465501726
[I 2024-04-19 04:36:47,940] Trial 31 finished with value: 0.2026080959550888 and parameters: {'l1_ratio': 0.09826378244944886}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.19619527894067185
Fold 2 IBS: 0.17834148654336138
Fold 3 IBS: 0.1857731374186083
Fold 4 IBS: 0.21426451857339437
Fold 5 IBS: 0.23845785177277892
[I 2024-04-19 04:36:50,691] Trial 32 finished with value: 0.20260645464976296 and parameters: {'l1_ratio': 0.05448134988858411}. Best is trial 22 with value: 0.2026032892471298.
Fold 1 IBS: 0.1961884898301595
Fold 2 IBS: 0.17834121622950644
Fold 3 IBS: 0.18577329570092233
Fold 4 IBS: 0.2142557119647306
Fold 5 IBS: 0.23843459159480138
[I 2024-04-19 04:36:53,456] Trial 33 finished with value: 0.20259866106402408 and parameters: {'l1_ratio': 0.05357058643952424}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.2138444022467837
Fold 2 IBS: 0.2213194439315363
Fold 3 IBS: 0.20434815234179415
Fold 4 IBS: 0.22455044444449468
Fold 5 IBS: 0.21809898140821998
[I 2024-04-19 04:36:54,968] Trial 34 finished with value: 0.21643228487456576 and parameters: {'l1_ratio': 0.0037772681753269755}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19591942459935732
Fold 2 IBS: 0.17847705215364623
Fold 3 IBS: 0.18574595266971156
Fold 4 IBS: 0.21428041413572332
Fold 5 IBS: 0.2387301597463318
[I 2024-04-19 04:36:57,348] Trial 35 finished with value: 0.20263060066095404 and parameters: {'l1_ratio': 0.2826383200204105}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.1962126813570666
Fold 2 IBS: 0.17834035259336037
Fold 3 IBS: 0.18577394001942021
Fold 4 IBS: 0.2142803771976709
Fold 5 IBS: 0.2384841045755878
[I 2024-04-19 04:36:59,810] Trial 36 finished with value: 0.20261829114862118 and parameters: {'l1_ratio': 0.050571441465253955}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19603264916973345
Fold 2 IBS: 0.17841817308382033
Fold 3 IBS: 0.18575714748290026
Fold 4 IBS: 0.2142464244521987
Fold 5 IBS: 0.23857223341877645
[I 2024-04-19 04:37:01,980] Trial 37 finished with value: 0.20260532552148586 and parameters: {'l1_ratio': 0.1679065876445084}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19569172291327566
Fold 2 IBS: 0.1785997422329068
Fold 3 IBS: 0.18572267801579045
Fold 4 IBS: 0.21423811327566428
Fold 5 IBS: 0.2391639685278735
[I 2024-04-19 04:37:04,061] Trial 38 finished with value: 0.20268324499310214 and parameters: {'l1_ratio': 0.8598478847078105}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.21265955097113545
Fold 2 IBS: 0.17833240776307718
Fold 3 IBS: 0.18577556783006363
Fold 4 IBS: 0.2142704200210362
Fold 5 IBS: 0.2384307546865512
[I 2024-04-19 04:37:06,454] Trial 39 finished with value: 0.20589374025437274 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.1958071853143634
Fold 2 IBS: 0.17852044965638927
Fold 3 IBS: 0.1857364858795961
Fold 4 IBS: 0.21425959168069922
Fold 5 IBS: 0.23891260065211892
[I 2024-04-19 04:37:09,066] Trial 40 finished with value: 0.20264726263663335 and parameters: {'l1_ratio': 0.45606782576170923}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19605822643579732
Fold 2 IBS: 0.17841631587554965
Fold 3 IBS: 0.18575919451113737
Fold 4 IBS: 0.21425987147595635
Fold 5 IBS: 0.23856653575833067
[I 2024-04-19 04:37:11,547] Trial 41 finished with value: 0.2026120288113543 and parameters: {'l1_ratio': 0.15200009271881143}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19614028396519137
Fold 2 IBS: 0.17837800425021927
Fold 3 IBS: 0.185765292843109
Fold 4 IBS: 0.21424868186323875
Fold 5 IBS: 0.23854929657605506
[I 2024-04-19 04:37:13,910] Trial 42 finished with value: 0.2026163118995627 and parameters: {'l1_ratio': 0.10273470335539853}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19596165691171066
Fold 2 IBS: 0.17846035493690948
Fold 3 IBS: 0.18574885654002757
Fold 4 IBS: 0.21423636294650955
Fold 5 IBS: 0.23870343280350598
[I 2024-04-19 04:37:16,272] Trial 43 finished with value: 0.20262213282773267 and parameters: {'l1_ratio': 0.25041663481858534}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19605394550138408
Fold 2 IBS: 0.17842953493384797
Fold 3 IBS: 0.1857554051763469
Fold 4 IBS: 0.21427182138499898
Fold 5 IBS: 0.2386447577443664
[I 2024-04-19 04:37:18,700] Trial 44 finished with value: 0.20263109294818887 and parameters: {'l1_ratio': 0.1783750460703294}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.1957695411499947
Fold 2 IBS: 0.17854352193945658
Fold 3 IBS: 0.1857324630328698
Fold 4 IBS: 0.21424467403971756
Fold 5 IBS: 0.23896148367009207
[I 2024-04-19 04:37:20,696] Trial 45 finished with value: 0.20265033676642616 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19617301597418307
Fold 2 IBS: 0.1783510999575617
Fold 3 IBS: 0.18577088446952175
Fold 4 IBS: 0.21425103873143464
Fold 5 IBS: 0.23845817893357024
[I 2024-04-19 04:37:23,233] Trial 46 finished with value: 0.2026008436132543 and parameters: {'l1_ratio': 0.06575527274505497}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19620919349653737
Fold 2 IBS: 0.17834515643551102
Fold 3 IBS: 0.18577288531163688
Fold 4 IBS: 0.21428252831006536
Fold 5 IBS: 0.23850510390966936
[I 2024-04-19 04:37:26,166] Trial 47 finished with value: 0.20262297349268396 and parameters: {'l1_ratio': 0.056437226236262183}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.19573427556076856
Fold 2 IBS: 0.1785705533827418
Fold 3 IBS: 0.18572733253655319
Fold 4 IBS: 0.21424720949838366
Fold 5 IBS: 0.2390753435044108
[I 2024-04-19 04:37:28,525] Trial 48 finished with value: 0.20267094289657162 and parameters: {'l1_ratio': 0.6814395334066481}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.2138263641186082
Fold 2 IBS: 0.2212843149221996
Fold 3 IBS: 0.20432256537974497
Fold 4 IBS: 0.22452495205167136

Fold 5 IBS: 0.21809560596130464
[I 2024-04-19 04:37:29,837] Trial 49 finished with value: 0.21641076048670577 and parameters: {'l1_ratio': 0.004297293952703132}. Best is trial 33 with value: 0.20259866106402408.
Fold 1 IBS: 0.1961487812916338
Fold 2 IBS: 0.17835618651303217
Fold 3 IBS: 0.185770146445766
Fold 4 IBS: 0.2142834886793201
Fold 5 IBS: 0.23841899924858256
[I 2024-04-19 04:37:32,241] Trial 50 finished with value: 0.20259552043566692 and parameters: {'l1_ratio': 0.07022059668984147}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1961808477488711
Fold 2 IBS: 0.17834591096200678
Fold 3 IBS: 0.1857723338485543
Fold 4 IBS: 0.2142531432163535
Fold 5 IBS: 0.23844492471507603
[I 2024-04-19 04:37:35,555] Trial 51 finished with value: 0.20259943209817233 and parameters: {'l1_ratio': 0.059283402019761226}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1961036555809237
Fold 2 IBS: 0.17838532729073253
Fold 3 IBS: 0.18576434866885227
Fold 4 IBS: 0.2142712764596368
Fold 5 IBS: 0.23848837796198324
[I 2024-04-19 04:37:38,734] Trial 52 finished with value: 0.20260259719242574 and parameters: {'l1_ratio': 0.10776625353331712}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19611155359347798
Fold 2 IBS: 0.17838567939002273
Fold 3 IBS: 0.18576407915585527
Fold 4 IBS: 0.21428073078002324
Fold 5 IBS: 0.23851554288582608
[I 2024-04-19 04:37:41,359] Trial 53 finished with value: 0.20261151716104106 and parameters: {'l1_ratio': 0.11001207801370774}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19616571937820892
Fold 2 IBS: 0.17835080873098
Fold 3 IBS: 0.1857710724383253
Fold 4 IBS: 0.21429611101796564
Fold 5 IBS: 0.2384331335247975
[I 2024-04-19 04:37:43,917] Trial 54 finished with value: 0.20260336901805545 and parameters: {'l1_ratio': 0.06457047044632028}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19609772202813586
Fold 2 IBS: 0.17839494899526437
Fold 3 IBS: 0.18576225534218038
Fold 4 IBS: 0.2142772009241128
Fold 5 IBS: 0.23853866792108866
[I 2024-04-19 04:37:46,420] Trial 55 finished with value: 0.2026141590421564 and parameters: {'l1_ratio': 0.1230998171238566}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.21296432539452523
Fold 2 IBS: 0.2196530955330006
Fold 3 IBS: 0.18577770876703648
Fold 4 IBS: 0.22334325946962358
Fold 5 IBS: 0.23842963115961832
[I 2024-04-19 04:37:48,064] Trial 56 finished with value: 0.21603360406476085 and parameters: {'l1_ratio': 0.03043479158964555}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1961384252095668
Fold 2 IBS: 0.17836242280569667
Fold 3 IBS: 0.1857689067219348
Fold 4 IBS: 0.21428003872001755
Fold 5 IBS: 0.23843152469549433
[I 2024-04-19 04:37:50,841] Trial 57 finished with value: 0.20259626363054206 and parameters: {'l1_ratio': 0.07786358306040081}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1961823531014828
Fold 2 IBS: 0.17836214400662814
Fold 3 IBS: 0.1857691348934495
Fold 4 IBS: 0.21427131029077667
Fold 5 IBS: 0.23853378227479985
[I 2024-04-19 04:37:53,532] Trial 58 finished with value: 0.20262374491342744 and parameters: {'l1_ratio': 0.0764811371717959}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19600090919609403
Fold 2 IBS: 0.17844569632783513
Fold 3 IBS: 0.18575146428232697
Fold 4 IBS: 0.21425700132742048
Fold 5 IBS: 0.23870409465775264
[I 2024-04-19 04:37:55,825] Trial 59 finished with value: 0.20263183315828584 and parameters: {'l1_ratio': 0.2275538705988292}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19572560963731028
Fold 2 IBS: 0.1785459852341721
Fold 3 IBS: 0.18572820096878215
Fold 4 IBS: 0.2142786217810561
Fold 5 IBS: 0.2390683046648754
[I 2024-04-19 04:37:58,077] Trial 60 finished with value: 0.20266934445723922 and parameters: {'l1_ratio': 0.6097637962339882}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19613836178158003
Fold 2 IBS: 0.17836976217232145
Fold 3 IBS: 0.18576720607659258
Fold 4 IBS: 0.21428985491163755
Fold 5 IBS: 0.23848446338813545
[I 2024-04-19 04:38:01,204] Trial 61 finished with value: 0.20260992966605343 and parameters: {'l1_ratio': 0.08895213747171299}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19609318728757422
Fold 2 IBS: 0.17840593299943755
Fold 3 IBS: 0.18575989042586716
Fold 4 IBS: 0.2142859993591423
Fold 5 IBS: 0.2386003133159177
[I 2024-04-19 04:38:03,774] Trial 62 finished with value: 0.20262906467758776 and parameters: {'l1_ratio': 0.1421916318931956}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.21302757449209575
Fold 2 IBS: 0.21976979446814524
Fold 3 IBS: 0.18577791713435537
Fold 4 IBS: 0.22342768820537343
Fold 5 IBS: 0.23846453856418046
[I 2024-04-19 04:38:05,941] Trial 63 finished with value: 0.21609350257283003 and parameters: {'l1_ratio': 0.028426561226924267}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1960155610196462
Fold 2 IBS: 0.1784308976342949
Fold 3 IBS: 0.18575460283939482
Fold 4 IBS: 0.21424475993830314
Fold 5 IBS: 0.2386159346755982
[I 2024-04-19 04:38:08,695] Trial 64 finished with value: 0.20261235122144744 and parameters: {'l1_ratio': 0.1914666773841506}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19613170272883057
Fold 2 IBS: 0.1783866432953836
Fold 3 IBS: 0.1857634822853744
Fold 4 IBS: 0.21425057481766907
Fold 5 IBS: 0.23858482338804377
[I 2024-04-19 04:38:11,689] Trial 65 finished with value: 0.20262344530306028 and parameters: {'l1_ratio': 0.11614107620817249}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.21394433976247446
Fold 2 IBS: 0.22151476670199483
Fold 3 IBS: 0.20449014105461627
Fold 4 IBS: 0.22469220278294605
Fold 5 IBS: 0.2181180455088275
[I 2024-04-19 04:38:12,968] Trial 66 finished with value: 0.21655189916217182 and parameters: {'l1_ratio': 0.0009149882378114843}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19607769438627318
Fold 2 IBS: 0.17841732213640782
Fold 3 IBS: 0.1857576354327163
Fold 4 IBS: 0.21428307751209338
Fold 5 IBS: 0.23863264120710884
[I 2024-04-19 04:38:15,495] Trial 67 finished with value: 0.2026336741349199 and parameters: {'l1_ratio': 0.16054680060974633}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1961593746204698
Fold 2 IBS: 0.17836329665439063
Fold 3 IBS: 0.18576831902002633
Fold 4 IBS: 0.214251215467649
Fold 5 IBS: 0.23850345798964237
[I 2024-04-19 04:38:18,121] Trial 68 finished with value: 0.20260913275043563 and parameters: {'l1_ratio': 0.08211262364101025}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19587317648020872
Fold 2 IBS: 0.17849563608207705
Fold 3 IBS: 0.18574458451704165
Fold 4 IBS: 0.2142689412571593
Fold 5 IBS: 0.23876508712702285
[I 2024-04-19 04:38:20,460] Trial 69 finished with value: 0.2026294850927019 and parameters: {'l1_ratio': 0.32186405670552004}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.21288593042207998
Fold 2 IBS: 0.2195090859862021
Fold 3 IBS: 0.18577689286719845
Fold 4 IBS: 0.22323909497139352
Fold 5 IBS: 0.23840912702756856
[I 2024-04-19 04:38:22,342] Trial 70 finished with value: 0.21596402625488853 and parameters: {'l1_ratio': 0.032945082571324835}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19617418062923436
Fold 2 IBS: 0.17835723314756513
Fold 3 IBS: 0.18576947498259058
Fold 4 IBS: 0.21426079935332212
Fold 5 IBS: 0.23850586020658218
[I 2024-04-19 04:38:24,935] Trial 71 finished with value: 0.20261350966385888 and parameters: {'l1_ratio': 0.07486713169488839}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19616206247114912
Fold 2 IBS: 0.17835671483140367
Fold 3 IBS: 0.1857697766169158
Fold 4 IBS: 0.21424508569664072
Fold 5 IBS: 0.23846434425906377
[I 2024-04-19 04:38:28,078] Trial 72 finished with value: 0.2025995967750346 and parameters: {'l1_ratio': 0.07258368686387957}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19610477638055496
Fold 2 IBS: 0.17839528823332573
Fold 3 IBS: 0.1857620260272602
Fold 4 IBS: 0.21428562298720907
Fold 5 IBS: 0.23856287534942794
[I 2024-04-19 04:38:30,777] Trial 73 finished with value: 0.20262211779555556 and parameters: {'l1_ratio': 0.12546768851300397}. Best is trial 50 with value: 0.20259552043566692.

Fold 1 IBS: 0.21303488873832213
Fold 2 IBS: 0.2197833194180575
Fold 3 IBS: 0.18577800593309995
Fold 4 IBS: 0.22343747424433247
Fold 5 IBS: 0.23845332542974051
[I 2024-04-19 04:38:32,925] Trial 74 finished with value: 0.21609740275271055 and parameters: {'l1_ratio': 0.028195299315553535}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1961845438669615
Fold 2 IBS: 0.17835563899983484
Fold 3 IBS: 0.18577061249803245
Fold 4 IBS: 0.21426541160545684
Fold 5 IBS: 0.23849764786613312
[I 2024-04-19 04:38:35,466] Trial 75 finished with value: 0.20261477096728372 and parameters: {'l1_ratio': 0.06770838940630236}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19603171762469188
Fold 2 IBS: 0.178443234622852
Fold 3 IBS: 0.18575415004487017
Fold 4 IBS: 0.21426400153471836
Fold 5 IBS: 0.23867078554393042
[I 2024-04-19 04:38:38,013] Trial 76 finished with value: 0.20263277787421258 and parameters: {'l1_ratio': 0.20072860823217953}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19604801418715442
Fold 2 IBS: 0.17840665802250397
Fold 3 IBS: 0.185759460393662
Fold 4 IBS: 0.2142476537188747
Fold 5 IBS: 0.23864710986558063
[I 2024-04-19 04:38:40,808] Trial 77 finished with value: 0.20262177923755514 and parameters: {'l1_ratio': 0.14783883643331833}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1961410394118462
Fold 2 IBS: 0.17837804021994894
Fold 3 IBS: 0.18576527248818114
Fold 4 IBS: 0.21424965888047656
Fold 5 IBS: 0.23855188107319963
[I 2024-04-19 04:38:43,530] Trial 78 finished with value: 0.2026171784147305 and parameters: {'l1_ratio': 0.10294307776235329}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19568849607130348
Fold 2 IBS: 0.17857362347871328
Fold 3 IBS: 0.1857230247732152
Fold 4 IBS: 0.21422799785071708
Fold 5 IBS: 0.23913193334832053
[I 2024-04-19 04:38:45,960] Trial 79 finished with value: 0.20266901510445395 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19596022000450833
Fold 2 IBS: 0.17845980282531318
Fold 3 IBS: 0.18574915607772974
Fold 4 IBS: 0.21428248846484843
Fold 5 IBS: 0.2386728800119739
[I 2024-04-19 04:38:48,315] Trial 80 finished with value: 0.2026249094768747 and parameters: {'l1_ratio': 0.24357351680443923}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19617818221496286
Fold 2 IBS: 0.17834580583209853
Fold 3 IBS: 0.18577240107692197
Fold 4 IBS: 0.21424968306868605
Fold 5 IBS: 0.2384357802073975
[I 2024-04-19 04:38:51,220] Trial 81 finished with value: 0.2025963704800134 and parameters: {'l1_ratio': 0.05889290154459757}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19621361646185786
Fold 2 IBS: 0.1783364384206072
Fold 3 IBS: 0.18577497277129895
Fold 4 IBS: 0.21427550363502407
Fold 5 IBS: 0.23845707782727668
[I 2024-04-19 04:38:54,467] Trial 82 finished with value: 0.20261152182321296 and parameters: {'l1_ratio': 0.04513905707841428}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.21334547727030245
Fold 2 IBS: 0.22036339430337762
Fold 3 IBS: 0.20364649624659809
Fold 4 IBS: 0.2238574055144315
Fold 5 IBS: 0.21801312240250875
[I 2024-04-19 04:38:55,799] Trial 83 finished with value: 0.2158451791474437 and parameters: {'l1_ratio': 0.018556673131907286}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19611960052470168
Fold 2 IBS: 0.17837706950478066
Fold 3 IBS: 0.1857659023386228
Fold 4 IBS: 0.21427821758140148
Fold 5 IBS: 0.238478329628322
[I 2024-04-19 04:38:58,719] Trial 84 finished with value: 0.20260382391556572 and parameters: {'l1_ratio': 0.09731105267567132}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19606746832942246
Fold 2 IBS: 0.17839650695957496
Fold 3 IBS: 0.18576143512751034
Fold 4 IBS: 0.21425527857781107
Fold 5 IBS: 0.23863060590211085
[I 2024-04-19 04:39:01,408] Trial 85 finished with value: 0.20262225897928593 and parameters: {'l1_ratio': 0.13257827709423287}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19619190605497047
Fold 2 IBS: 0.17834994485760303
Fold 3 IBS: 0.18577207276961127
Fold 4 IBS: 0.21426747701707943
Fold 5 IBS: 0.23848279184291918
[I 2024-04-19 04:39:04,263] Trial 86 finished with value: 0.20261283850843664 and parameters: {'l1_ratio': 0.06095409262783028}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19605825402750082
Fold 2 IBS: 0.17842977403163665
Fold 3 IBS: 0.18575524919165057
Fold 4 IBS: 0.2142769433129537
Fold 5 IBS: 0.23865950750954565
[I 2024-04-19 04:39:06,721] Trial 87 finished with value: 0.20263594561465745 and parameters: {'l1_ratio': 0.1806380412295976}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19615302184469458
Fold 2 IBS: 0.17836302048248284
Fold 3 IBS: 0.1857684862642117
Fold 4 IBS: 0.214297533151637
Fold 5 IBS: 0.23848168178060175
[I 2024-04-19 04:39:09,746] Trial 88 finished with value: 0.20261274870472556 and parameters: {'l1_ratio': 0.08078101291984821}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19613383470309081
Fold 2 IBS: 0.1783867505978147
Fold 3 IBS: 0.18576342469560922
Fold 4 IBS: 0.214253327186165
Fold 5 IBS: 0.23859210550654805
[I 2024-04-19 04:39:13,200] Trial 89 finished with value: 0.20262588853784552 and parameters: {'l1_ratio': 0.11682570890167254}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.2126372960301135
Fold 2 IBS: 0.17833264105555724
Fold 3 IBS: 0.18577569230226212
Fold 4 IBS: 0.21427993228740141
Fold 5 IBS: 0.238455848135144
[I 2024-04-19 04:39:16,342] Trial 90 finished with value: 0.20589628196209567 and parameters: {'l1_ratio': 0.04106579315859652}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19619463918482416
Fold 2 IBS: 0.17835004401757237
Fold 3 IBS: 0.18577201264767113
Fold 4 IBS: 0.21427101449445857
Fold 5 IBS: 0.23849213363132374
[I 2024-04-19 04:39:19,355] Trial 91 finished with value: 0.20261596879517 and parameters: {'l1_ratio': 0.06138007078009955}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19615858842225223
Fold 2 IBS: 0.17837067947787058
Fold 3 IBS: 0.18576666609710069
Fold 4 IBS: 0.21426077112562683
Fold 5 IBS: 0.23855373865047033
[I 2024-04-19 04:39:22,294] Trial 92 finished with value: 0.20262208875466414 and parameters: {'l1_ratio': 0.09379858128478835}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19607612908527083
Fold 2 IBS: 0.17841723812886506
Fold 3 IBS: 0.1857576883853386
Fold 4 IBS: 0.21428121575145376
Fold 5 IBS: 0.2386272848266611
[I 2024-04-19 04:39:25,043] Trial 93 finished with value: 0.20263191123551788 and parameters: {'l1_ratio': 0.1598276544633182}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.21329181315738174
Fold 2 IBS: 0.22026235557278379
Fold 3 IBS: 0.2035716813738389
Fold 4 IBS: 0.22378423027825836
Fold 5 IBS: 0.21800481617107403
[I 2024-04-19 04:39:26,453] Trial 94 finished with value: 0.21578297931066737 and parameters: {'l1_ratio': 0.02019714608867159}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19617452024852727
Fold 2 IBS: 0.1783511615325952
Fold 3 IBS: 0.18577084728089294
Fold 4 IBS: 0.21425241549542087
Fold 5 IBS: 0.238463336185557
[I 2024-04-19 04:39:29,358] Trial 95 finished with value: 0.20260245614859868 and parameters: {'l1_ratio': 0.06600437718066372}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.1960723417929914
Fold 2 IBS: 0.17840490985904572
Fold 3 IBS: 0.1857613149563199
Fold 4 IBS: 0.21426111474976026
Fold 5 IBS: 0.23852872744045772
[I 2024-04-19 04:39:32,169] Trial 96 finished with value: 0.202605681759715 and parameters: {'l1_ratio': 0.1343084889624756}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.19621353348517212
Fold 2 IBS: 0.1783364357327229
Fold 3 IBS: 0.18577497548820085
Fold 4 IBS: 0.21427539613886806
Fold 5 IBS: 0.23845679420510132
[I 2024-04-19 04:39:35,107] Trial 97 finished with value: 0.20261142701001306 and parameters: {'l1_ratio': 0.045129730347281925}. Best is trial 50 with value: 0.20259552043566692.
Fold 1 IBS: 0.2138989642247673
Fold 2 IBS: 0.2214259361077622
Fold 3 IBS: 0.20442562463866423
Fold 4 IBS: 0.22462772913331652
Fold 5 IBS: 0.2181093135113579
[I 2024-04-19 04:39:36,224] Trial 98 finished with value: 0.21649751352317365 and parameters: {'l1_ratio': 0.0022106362174480407}. Best is trial 50 with value: 0.20259552043566692.

Fold 1 IBS: 0.19583855394777175
Fold 2 IBS: 0.1784990783463084
Fold 3 IBS: 0.18574079905797627
Fold 4 IBS: 0.21426788636210636
Fold 5 IBS: 0.2388401592257628
[I 2024-04-19 04:39:38,931] Trial 99 finished with value: 0.20263729538798508 and parameters: {'l1_ratio': 0.382376673820383}. Best is trial 50 with value: 0.20259552043566692.


* Best trial for IBS:
 FrozenTrial(number=50, state=TrialState.COMPLETE, values=[0.20259552043566692], datetime_start=datetime.datetime(2024, 4, 19, 4, 37, 29, 844731), datetime_complete=datetime.datetime(2024, 4, 19, 4, 37, 32, 240769), params={'l1_ratio': 0.07022059668984147}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=50, value=None)


* Best Score for IBS:
 0.20259552043566692

In [86]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [87]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.681
train_ibs:  0.203

#### Test

In [88]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [89]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.015423757551295547)

test_cindex : 0.617

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.07022059668984147)

test_ibs:  0.237

In [90]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [91]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 04:39:39,938] A new study created in memory with name: no-name-d064a47e-3a48-4462-8669-542b2bb5a0b3

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6139240506329114
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 04:39:57,723] Trial 0 finished with value: 0.651480110269687 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.651480110269687.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 04:40:11,498] Trial 1 finished with value: 0.6554955781077403 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.6554955781077403.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.5949367088607594
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:40:21,610] Trial 2 finished with value: 0.6504903527076401 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.6554955781077403.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:40:24,612] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.6554955781077403.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:40:29,914] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.6554955781077403.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6033755274261603
Fold 5 C-index: 0.6431924882629108
[I 2024-04-19 04:40:46,944] Trial 5 finished with value: 0.6534261572503682 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.6554955781077403.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:41:04,217] Trial 6 finished with value: 0.6594251492960107 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:41:13,117] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6690140845070423
[I 2024-04-19 04:41:38,488] Trial 8 finished with value: 0.5338028169014084 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 04:41:50,650] Trial 9 finished with value: 0.6543932685555787 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:41:52,187] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.40740851493126695, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:41:58,474] Trial 11 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.11379276107227315, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.6176470588235294
Fold 4 C-index: 0.6033755274261603
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 04:42:07,820] Trial 12 finished with value: 0.6500536270603153 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.8206827027986038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.5949367088607594
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 04:42:24,269] Trial 13 finished with value: 0.6526515821161768 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.47497684741348173, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08474327360564854, 'warm_start': False}. Best is trial 6 with value: 0.6594251492960107.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 04:42:33,536] Trial 14 finished with value: 0.7004823677392317 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.7597438994612711, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18789428118059787, 'warm_start': True}. Best is trial 14 with value: 0.7004823677392317.
Fold 1 C-index: 0.577922077922078
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6446078431372549
Fold 4 C-index: 0.7278481012658228

Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 04:42:42,358] Trial 15 finished with value: 0.6905576634858226 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.4747428535255964, 'max_features': None, 'min_weight_fraction_leaf': 0.19147439464820804, 'warm_start': True}. Best is trial 14 with value: 0.7004823677392317.
Fold 1 C-index: 0.5995670995670995
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 04:42:55,662] Trial 16 finished with value: 0.7052364401894569 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.8353789630965257, 'max_features': None, 'min_weight_fraction_leaf': 0.18739880110892437, 'warm_start': True}. Best is trial 16 with value: 0.7052364401894569.
Fold 1 C-index: 0.5995670995670995
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6299019607843137
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 04:43:07,695] Trial 17 finished with value: 0.6877260820615383 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 1, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.9787373309536591, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 16 with value: 0.7052364401894569.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 04:43:19,416] Trial 18 finished with value: 0.7138832697214448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 480, 'oob_score': True, 'max_samples': 0.8326564387629503, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17047935743788273, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.577922077922078
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.7025316455696202
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 04:43:30,481] Trial 19 finished with value: 0.672862453381813 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 493, 'oob_score': True, 'max_samples': 0.8451741232843377, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3933604732001355, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7236286919831224
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 04:43:41,200] Trial 20 finished with value: 0.712810113631994 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.9965086442613145, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24858261413121135, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.6125541125541125
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 04:43:52,720] Trial 21 finished with value: 0.7038039704528305 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 448, 'oob_score': True, 'max_samples': 0.8654496326475805, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.255834558741605, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 04:44:05,074] Trial 22 finished with value: 0.7069285821429172 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 7, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.991612912786197, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22450446081852962, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 04:44:15,134] Trial 23 finished with value: 0.710498826631578 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.9859933897340725, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27355128284391594, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 04:44:26,498] Trial 24 finished with value: 0.7077677790268768 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 425, 'oob_score': True, 'max_samples': 0.9883250792402232, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28021855793337186, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.5995670995670995
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6299019607843137
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 04:44:35,368] Trial 25 finished with value: 0.686093024220823 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9109361356364238, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38373527888751957, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:44:45,253] Trial 26 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 420, 'oob_score': True, 'max_samples': 0.6819762420236617, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4461128531136588, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 04:44:55,971] Trial 27 finished with value: 0.7007373822233476 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.7838271975800054, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14918319374247518, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7067510548523207
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 04:45:05,068] Trial 28 finished with value: 0.7062770043510687 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.876041281537138, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22932326739338416, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.
Fold 1 C-index: 0.6125541125541125
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.7151898734177216
Fold 5 C-index: 0.6807511737089202
[I 2024-04-19 04:45:14,318] Trial 29 finished with value: 0.6943285837568791 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.9389954145401067, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31512460196704517, 'warm_start': True}. Best is trial 18 with value: 0.7138832697214448.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 04:45:21,502] Trial 30 finished with value: 0.7141673349512903 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.7229708697769008, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.151583696008541, 'warm_start': True}. Best is trial 30 with value: 0.7141673349512903.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 04:45:29,671] Trial 31 finished with value: 0.7127138910881294 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.7487289552088571, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15332132568985768, 'warm_start': True}. Best is trial 30 with value: 0.7141673349512903.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 04:45:34,709] Trial 32 finished with value: 0.7136155274116324 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.7429064313205944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15023084549434396, 'warm_start': True}. Best is trial 30 with value: 0.7141673349512903.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 04:45:39,798] Trial 33 finished with value: 0.7153256624291882 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.697659537347253, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1280338808941886, 'warm_start': True}. Best is trial 33 with value: 0.7153256624291882.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.875
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 04:45:45,598] Trial 34 finished with value: 0.7195479370049127 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.6915749357444305, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13042487156096202, 'warm_start': True}. Best is trial 34 with value: 0.7195479370049127.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 04:45:47,551] Trial 35 finished with value: 0.712830940209274 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 173, 'oob_score': False, 'max_samples': 0.6930219051974595, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06651444215794694, 'warm_start': True}. Best is trial 34 with value: 0.7195479370049127.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 04:45:52,701] Trial 36 finished with value: 0.7164593466278389 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.6344285650799314, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12095391183256232, 'warm_start': True}. Best is trial 34 with value: 0.7195479370049127.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 04:45:55,602] Trial 37 finished with value: 0.7066956276910997 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.548895923435001, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12819069469935257, 'warm_start': True}. Best is trial 34 with value: 0.7195479370049127.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 04:46:00,879] Trial 38 finished with value: 0.7236916007427947 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.5602012310841897, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09246075046549623, 'warm_start': True}. Best is trial 38 with value: 0.7236916007427947.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 04:46:03,697] Trial 39 finished with value: 0.7301260407159671 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.5584624909113933, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04793371047097461, 'warm_start': True}. Best is trial 39 with value: 0.7301260407159671.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 04:46:05,480] Trial 40 finished with value: 0.7226121701212941 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 128, 'oob_score': False, 'max_samples': 0.5830962577096583, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0027150897727451773, 'warm_start': True}. Best is trial 39 with value: 0.7301260407159671.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 04:46:06,956] Trial 41 finished with value: 0.7337877285713876 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 115, 'oob_score': False, 'max_samples': 0.5444845677467408, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0005730062131473479, 'warm_start': True}. Best is trial 41 with value: 0.7337877285713876.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 04:46:08,364] Trial 42 finished with value: 0.7391010782422824 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.5570337093433774, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03854346245536206, 'warm_start': True}. Best is trial 42 with value: 0.7391010782422824.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 04:46:09,887] Trial 43 finished with value: 0.736267083820189 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.5582016767187282, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01915854839346568, 'warm_start': True}. Best is trial 42 with value: 0.7391010782422824.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 04:46:10,985] Trial 44 finished with value: 0.7252177137488166 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 73, 'oob_score': False, 'max_samples': 0.5238835573161168, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03794753448044159, 'warm_start': True}. Best is trial 42 with value: 0.7391010782422824.

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 04:46:11,951] Trial 45 finished with value: 0.7327123921579524 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.4009938605214738, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0459916725594289, 'warm_start': True}. Best is trial 42 with value: 0.7391010782422824.
Fold 1 C-index: 0.6212121212121212
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.5882352941176471
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 04:46:12,776] Trial 46 finished with value: 0.6740113811209503 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 9, 'oob_score': False, 'max_samples': 0.3704630617696939, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.003682396491272201, 'warm_start': False}. Best is trial 42 with value: 0.7391010782422824.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 04:46:14,248] Trial 47 finished with value: 0.7096791402990473 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 89, 'oob_score': False, 'max_samples': 0.2766890848304698, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05574216570821283, 'warm_start': True}. Best is trial 42 with value: 0.7391010782422824.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6127450980392157
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 04:46:16,281] Trial 48 finished with value: 0.6495177219253152 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 38, 'oob_score': False, 'max_samples': 0.396142547545275, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0315954574467603, 'warm_start': False}. Best is trial 42 with value: 0.7391010782422824.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 04:46:18,144] Trial 49 finished with value: 0.7417265801764718 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 129, 'oob_score': False, 'max_samples': 0.5125321841486757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07480570504958844, 'warm_start': True}. Best is trial 49 with value: 0.7417265801764718.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 04:46:20,195] Trial 50 finished with value: 0.7377767354368772 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.5043937160531627, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07578089457711798, 'warm_start': True}. Best is trial 49 with value: 0.7417265801764718.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 04:46:22,193] Trial 51 finished with value: 0.7178695497632107 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.4935741044476889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08023641696910894, 'warm_start': True}. Best is trial 49 with value: 0.7417265801764718.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.9107142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 04:46:23,643] Trial 52 finished with value: 0.8072878401753739 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 103, 'oob_score': False, 'max_samples': 0.45427692384516094, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01590308450260479, 'warm_start': True}. Best is trial 52 with value: 0.8072878401753739.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 04:46:25,501] Trial 53 finished with value: 0.7905620224313002 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.43937926747250533, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019347410601578303, 'warm_start': True}. Best is trial 52 with value: 0.8072878401753739.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.812206572769953
[I 2024-04-19 04:46:26,981] Trial 54 finished with value: 0.7889111372356524 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.4323390143553766, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020968435374117817, 'warm_start': True}. Best is trial 52 with value: 0.8072878401753739.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 04:46:28,937] Trial 55 finished with value: 0.7392071723987736 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 164, 'oob_score': False, 'max_samples': 0.43840911925720466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07013575069470758, 'warm_start': True}. Best is trial 52 with value: 0.8072878401753739.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 04:46:36,269] Trial 56 finished with value: 0.6609813989535263 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 173, 'oob_score': False, 'max_samples': 0.3356182325221925, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09871163070518371, 'warm_start': False}. Best is trial 52 with value: 0.8072878401753739.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 04:46:37,926] Trial 57 finished with value: 0.7911883661793864 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.4476324126284268, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019701922542522107, 'warm_start': True}. Best is trial 52 with value: 0.8072878401753739.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.8591549295774648
[I 2024-04-19 04:46:39,884] Trial 58 finished with value: 0.8192172044995895 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 127, 'oob_score': False, 'max_samples': 0.4376852467560235, 'max_features': None, 'min_weight_fraction_leaf': 0.020595341404685313, 'warm_start': True}. Best is trial 58 with value: 0.8192172044995895.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8450704225352113
[I 2024-04-19 04:46:41,912] Trial 59 finished with value: 0.8204768358906798 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 128, 'oob_score': False, 'max_samples': 0.43034357128802603, 'max_features': None, 'min_weight_fraction_leaf': 0.012075901156418264, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.5864978902953587
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 04:46:45,608] Trial 60 finished with value: 0.6323574610073855 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.43366872836050313, 'max_features': None, 'min_weight_fraction_leaf': 0.01878269789157313, 'warm_start': False}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.875
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 04:46:47,221] Trial 61 finished with value: 0.7882460413783499 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.3494737387048452, 'max_features': None, 'min_weight_fraction_leaf': 0.024716009716938887, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.812206572769953
[I 2024-04-19 04:46:49,028] Trial 62 finished with value: 0.7951571684444536 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.3481599037127711, 'max_features': None, 'min_weight_fraction_leaf': 0.02135219893566599, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 04:46:50,667] Trial 63 finished with value: 0.6997986321548506 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.21163084086126932, 'max_features': None, 'min_weight_fraction_leaf': 0.05499278824656979, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7887323943661971
[I 2024-04-19 04:46:51,788] Trial 64 finished with value: 0.7529277418272127 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.2828213716624862, 'max_features': None, 'min_weight_fraction_leaf': 0.008830139298612639, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 04:46:52,661] Trial 65 finished with value: 0.7665340902564692 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 21, 'oob_score': False, 'max_samples': 0.45343786071005465, 'max_features': None, 'min_weight_fraction_leaf': 0.02073895933724094, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 04:46:54,127] Trial 66 finished with value: 0.7563399644692316 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 94, 'oob_score': False, 'max_samples': 0.36826292743980393, 'max_features': None, 'min_weight_fraction_leaf': 0.06143556763635516, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 04:46:56,226] Trial 67 finished with value: 0.7492082572262928 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.3121475218309513, 'max_features': None, 'min_weight_fraction_leaf': 0.03324742373664542, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 04:46:57,279] Trial 68 finished with value: 0.7243925099254114 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.21896926049284302, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01565124525288915, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 04:46:59,437] Trial 69 finished with value: 0.7138538004465793 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 187, 'oob_score': False, 'max_samples': 0.4282080482559533, 'max_features': None, 'min_weight_fraction_leaf': 0.1015843819224478, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8075117370892019
[I 2024-04-19 04:47:01,225] Trial 70 finished with value: 0.7883213028481137 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.4708033909119915, 'max_features': None, 'min_weight_fraction_leaf': 0.04834629799222376, 'warm_start': True}. Best is trial 59 with value: 0.8204768358906798.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8497652582159625
[I 2024-04-19 04:47:03,151] Trial 71 finished with value: 0.822888123830871 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 118, 'oob_score': False, 'max_samples': 0.47400767177916026, 'max_features': None, 'min_weight_fraction_leaf': 0.038400490539505186, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 04:47:04,826] Trial 72 finished with value: 0.8045613813524891 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 98, 'oob_score': False, 'max_samples': 0.4111019173137385, 'max_features': None, 'min_weight_fraction_leaf': 0.028746276424478513, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8075117370892019
[I 2024-04-19 04:47:07,013] Trial 73 finished with value: 0.799723357916401 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.37703659520841803, 'max_features': None, 'min_weight_fraction_leaf': 0.03588353536476762, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 04:47:09,282] Trial 74 finished with value: 0.7787458320740572 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.38353053850996266, 'max_features': None, 'min_weight_fraction_leaf': 0.036662880417809865, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 04:47:11,656] Trial 75 finished with value: 0.7062881341048388 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.31089238036546907, 'max_features': None, 'min_weight_fraction_leaf': 0.08911707858269173, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7934272300469484
[I 2024-04-19 04:47:13,709] Trial 76 finished with value: 0.7917013767775543 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.4871021190554715, 'max_features': None, 'min_weight_fraction_leaf': 0.05060557077684914, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7793427230046949
[I 2024-04-19 04:47:15,924] Trial 77 finished with value: 0.769710177341492 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 164, 'oob_score': False, 'max_samples': 0.4842296343451894, 'max_features': None, 'min_weight_fraction_leaf': 0.06696661310764733, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 04:47:17,348] Trial 78 finished with value: 0.7539318621741959 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.3465904964365048, 'max_features': None, 'min_weight_fraction_leaf': 0.052182758961744194, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8450704225352113
[I 2024-04-19 04:47:19,959] Trial 79 finished with value: 0.8201392871772933 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 144, 'oob_score': False, 'max_samples': 0.4112545631043669, 'max_features': None, 'min_weight_fraction_leaf': 0.002416247241630469, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.6294642857142857
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.596244131455399
[I 2024-04-19 04:47:29,073] Trial 80 finished with value: 0.6271769601453119 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.40683966593810433, 'max_features': None, 'min_weight_fraction_leaf': 0.00835555387565294, 'warm_start': False}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 04:47:32,933] Trial 81 finished with value: 0.803891519938013 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 151, 'oob_score': False, 'max_samples': 0.4116621936886864, 'max_features': None, 'min_weight_fraction_leaf': 0.03596559197383655, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.8028169014084507
[I 2024-04-19 04:47:37,029] Trial 82 finished with value: 0.7852862700129565 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 140, 'oob_score': False, 'max_samples': 0.37172149543604055, 'max_features': None, 'min_weight_fraction_leaf': 0.03089021639245441, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.8075117370892019
[I 2024-04-19 04:47:39,648] Trial 83 finished with value: 0.7898145353540045 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 123, 'oob_score': False, 'max_samples': 0.41556873374927905, 'max_features': None, 'min_weight_fraction_leaf': 0.00421531187130679, 'warm_start': True}. Best is trial 71 with value: 0.822888123830871.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8732394366197183
[I 2024-04-19 04:47:42,806] Trial 84 finished with value: 0.8277442898665488 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 173, 'oob_score': False, 'max_samples': 0.5275419572192259, 'max_features': None, 'min_weight_fraction_leaf': 0.03994467973278975, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 04:47:45,890] Trial 85 finished with value: 0.7981414485922735 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.4635455498201441, 'max_features': None, 'min_weight_fraction_leaf': 0.039730484663918035, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8262910798122066
[I 2024-04-19 04:47:51,027] Trial 86 finished with value: 0.8039001197895649 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 286, 'oob_score': False, 'max_samples': 0.5251230716747477, 'max_features': None, 'min_weight_fraction_leaf': 0.03434615365873439, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7981220657276995
[I 2024-04-19 04:47:54,153] Trial 87 finished with value: 0.7876674888338129 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.5269789281622497, 'max_features': None, 'min_weight_fraction_leaf': 0.06503996443099541, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:47:58,428] Trial 88 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.596285734954256, 'max_features': None, 'min_weight_fraction_leaf': 0.4978507265200673, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 04:48:02,868] Trial 89 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 288, 'oob_score': False, 'max_samples': 0.5329722447738285, 'max_features': None, 'min_weight_fraction_leaf': 0.42980933716176023, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.

Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7699530516431925
[I 2024-04-19 04:48:06,386] Trial 90 finished with value: 0.7482998472570117 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.5053297816752218, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08038071296253088, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7887323943661971
[I 2024-04-19 04:48:09,079] Trial 91 finished with value: 0.7738750217748649 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 161, 'oob_score': False, 'max_samples': 0.3893457212837976, 'max_features': None, 'min_weight_fraction_leaf': 0.042511020081938744, 'warm_start': True}. Best is trial 84 with value: 0.8277442898665488.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.9241071428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8779342723004695
[I 2024-04-19 04:48:11,294] Trial 92 finished with value: 0.8579415886437559 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 146, 'oob_score': False, 'max_samples': 0.6234906979848106, 'max_features': None, 'min_weight_fraction_leaf': 0.0014738956820701497, 'warm_start': True}. Best is trial 92 with value: 0.8579415886437559.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.9196428571428571
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-19 04:48:14,567] Trial 93 finished with value: 0.8490930981543496 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 221, 'oob_score': False, 'max_samples': 0.5872522554199079, 'max_features': None, 'min_weight_fraction_leaf': 0.008094552920274454, 'warm_start': True}. Best is trial 92 with value: 0.8579415886437559.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-19 04:48:19,051] Trial 94 finished with value: 0.856221631385824 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.6343068465731646, 'max_features': None, 'min_weight_fraction_leaf': 0.0013788207731124497, 'warm_start': True}. Best is trial 92 with value: 0.8579415886437559.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8873239436619719
[I 2024-04-19 04:48:22,772] Trial 95 finished with value: 0.8528506479092066 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.6248639314127461, 'max_features': None, 'min_weight_fraction_leaf': 0.009851788208546739, 'warm_start': True}. Best is trial 92 with value: 0.8579415886437559.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8169014084507042
[I 2024-04-19 04:48:25,606] Trial 96 finished with value: 0.8049227070607495 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.6578157909239207, 'max_features': None, 'min_weight_fraction_leaf': 0.0001240790776083217, 'warm_start': True}. Best is trial 92 with value: 0.8579415886437559.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.9151785714285714
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.892018779342723
[I 2024-04-19 04:48:28,904] Trial 97 finished with value: 0.8626870808210804 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 218, 'oob_score': False, 'max_samples': 0.630961889364407, 'max_features': None, 'min_weight_fraction_leaf': 0.011342387005902448, 'warm_start': True}. Best is trial 97 with value: 0.8626870808210804.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 04:48:41,833] Trial 98 finished with value: 0.6581195293560138 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.6312869715737468, 'max_features': None, 'min_weight_fraction_leaf': 0.011249202966430718, 'warm_start': False}. Best is trial 97 with value: 0.8626870808210804.
Fold 1 C-index: 0.5995670995670995
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.6924882629107981
[I 2024-04-19 04:48:44,517] Trial 99 finished with value: 0.7025311572383374 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.6703634080887481, 'max_features': None, 'min_weight_fraction_leaf': 0.20123851264921916, 'warm_start': True}. Best is trial 97 with value: 0.8626870808210804.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.8626870808210804], datetime_start=datetime.datetime(2024, 4, 19, 4, 48, 25, 647560), datetime_complete=datetime.datetime(2024, 4, 19, 4, 48, 28, 891549), params={'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 218, 'oob_score': False, 'max_samples': 0.630961889364407, 'max_features': None, 'min_weight_fraction_leaf': 0.011342387005902448, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=97, value=None)


* Best Score for C-index:
 0.8626870808210804

[I 2024-04-19 04:48:44,548] A new study created in memory with name: no-name-6a7eae14-aa02-4330-86ee-2bbe5c508a68

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2145450214629436
Fold 2 IBS: 0.1866400391614707
Fold 3 IBS: 0.19885590708086562
Fold 4 IBS: 0.2204861819557205
Fold 5 IBS: 0.21512852151647596
[I 2024-04-19 04:49:01,411] Trial 0 finished with value: 0.20713113423549528 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.20713113423549528.
Fold 1 IBS: 0.21060091989287688
Fold 2 IBS: 0.19391127235579766
Fold 3 IBS: 0.19634207820125976
Fold 4 IBS: 0.21746327753157452
Fold 5 IBS: 0.21240720972246227
[I 2024-04-19 04:49:05,459] Trial 1 finished with value: 0.2061449515407942 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2061449515407942.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-19 04:49:08,062] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2061449515407942.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-19 04:49:19,954] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2061449515407942.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-19 04:49:28,816] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2061449515407942.
Fold 1 IBS: 0.19953646935601677
Fold 2 IBS: 0.1986102928987884
Fold 3 IBS: 0.19507025132149147
Fold 4 IBS: 0.2119812474086997
Fold 5 IBS: 0.2099753635158815
[I 2024-04-19 04:49:41,977] Trial 5 finished with value: 0.20303472490017554 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.21350455609138683
Fold 2 IBS: 0.1908578848491911
Fold 3 IBS: 0.19667105156090298
Fold 4 IBS: 0.22023635054140694
Fold 5 IBS: 0.21705917401312358
[I 2024-04-19 04:49:53,952] Trial 6 finished with value: 0.20766580341120228 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.2119277055389414
Fold 2 IBS: 0.2171017261187946
Fold 3 IBS: 0.20240510494554387
Fold 4 IBS: 0.22305434430086898
Fold 5 IBS: 0.2168829457739729
[I 2024-04-19 04:50:08,442] Trial 7 finished with value: 0.21427436533562436 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-19 04:50:30,617] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.20943970506468257
Fold 2 IBS: 0.1962176176188532
Fold 3 IBS: 0.19998926967512587
Fold 4 IBS: 0.21971614083556912
Fold 5 IBS: 0.2118880254771277
[I 2024-04-19 04:50:35,021] Trial 9 finished with value: 0.20745015173427167 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-19 04:50:59,880] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.20856156134894782
Fold 2 IBS: 0.20233398760249466
Fold 3 IBS: 0.19878862951670714
Fold 4 IBS: 0.21647109109138252
Fold 5 IBS: 0.21445766804348482
[I 2024-04-19 04:51:06,768] Trial 11 finished with value: 0.20812258752060336 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.20074677303593494
Fold 2 IBS: 0.20010993386461762
Fold 3 IBS: 0.1938515525353699
Fold 4 IBS: 0.22403016388356217
Fold 5 IBS: 0.21172743799794932
[I 2024-04-19 04:51:08,477] Trial 12 finished with value: 0.20609317226348675 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.18825035896000356
Fold 2 IBS: 0.19270017377863707
Fold 3 IBS: 0.1887750854519646
Fold 4 IBS: 0.2247112746335604
Fold 5 IBS: 0.22288513022789366
[I 2024-04-19 04:51:09,946] Trial 13 finished with value: 0.20346440461041185 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 5 with value: 0.20303472490017554.
Fold 1 IBS: 0.1957177794290442
Fold 2 IBS: 0.1975594597151971
Fold 3 IBS: 0.1863088512172313
Fold 4 IBS: 0.21204290000805612
Fold 5 IBS: 0.21258379903562832
[I 2024-04-19 04:51:25,293] Trial 14 finished with value: 0.20084255788103142 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9171185190122554, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.056489839500542004}. Best is trial 14 with value: 0.20084255788103142.
Fold 1 IBS: 0.1920077697511958
Fold 2 IBS: 0.19672964482722285
Fold 3 IBS: 0.18099453725508438
Fold 4 IBS: 0.2095976026052937
Fold 5 IBS: 0.20997945649998254
[I 2024-04-19 04:51:40,094] Trial 15 finished with value: 0.19786180218775584 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9965285643122548, 'max_features': 'log2', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 15 with value: 0.19786180218775584.

Fold 1 IBS: 0.20147039236728934
Fold 2 IBS: 0.19662869942267286
Fold 3 IBS: 0.1942962270930756
Fold 4 IBS: 0.2119797833927941
Fold 5 IBS: 0.21288178945582584
[I 2024-04-19 04:51:56,266] Trial 16 finished with value: 0.20345137834633156 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.9765957384255363, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00939201506667553}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20944054772335907
Fold 2 IBS: 0.19578996448889527
Fold 3 IBS: 0.19829564965304194
Fold 4 IBS: 0.2186538354483846
Fold 5 IBS: 0.21067894790471442
[I 2024-04-19 04:52:06,793] Trial 17 finished with value: 0.20657178904367904 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.9861686560685959, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19205722629162517
Fold 2 IBS: 0.20139944402541562
Fold 3 IBS: 0.19107644397954437
Fold 4 IBS: 0.21139649760827833
Fold 5 IBS: 0.20770354184620468
[I 2024-04-19 04:52:16,878] Trial 18 finished with value: 0.20072663075021366 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.8863359289238266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03745656942668121}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.1927903723466791
Fold 2 IBS: 0.2029159999647967
Fold 3 IBS: 0.19156587128522473
Fold 4 IBS: 0.2127137087146151
Fold 5 IBS: 0.21176906956021976
[I 2024-04-19 04:52:26,489] Trial 19 finished with value: 0.20235100437430703 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 150, 'oob_score': True, 'max_samples': 0.8412630414660432, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001333393983976}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20767106537945534
Fold 2 IBS: 0.1975021138277969
Fold 3 IBS: 0.1977783224476105
Fold 4 IBS: 0.2159437490819389
Fold 5 IBS: 0.213124976806829
[I 2024-04-19 04:52:37,041] Trial 20 finished with value: 0.20640404550872615 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 178, 'oob_score': True, 'max_samples': 0.9925887490489678, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1760853632720823}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19492391344481702
Fold 2 IBS: 0.19679668782106682
Fold 3 IBS: 0.18488958418657875
Fold 4 IBS: 0.21060372798407406
Fold 5 IBS: 0.21159220195877043
[I 2024-04-19 04:52:54,765] Trial 21 finished with value: 0.19976122307906138 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.905807530773294, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05390717642011646}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.1952625554369858
Fold 2 IBS: 0.198129153842201
Fold 3 IBS: 0.18642187158783385
Fold 4 IBS: 0.211110377475944
Fold 5 IBS: 0.20629114304654095
[I 2024-04-19 04:53:10,600] Trial 22 finished with value: 0.19944302027790112 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.8112718122193755, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04509253601870647}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20485425630623985
Fold 2 IBS: 0.19704343115006318
Fold 3 IBS: 0.1943600970161465
Fold 4 IBS: 0.21472990554658503
Fold 5 IBS: 0.21201279284932464
[I 2024-04-19 04:53:31,500] Trial 23 finished with value: 0.20460009657367184 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.802823244361611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10941914893046613}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19902112740669428
Fold 2 IBS: 0.1984424296436489
Fold 3 IBS: 0.19339076670968391
Fold 4 IBS: 0.21233248587842363
Fold 5 IBS: 0.2146921966170045
[I 2024-04-19 04:53:47,888] Trial 24 finished with value: 0.20357580125109104 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 253, 'oob_score': True, 'max_samples': 0.9069659200458383, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05283430096524438}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20842875109376804
Fold 2 IBS: 0.19449427824036866
Fold 3 IBS: 0.19778730871512606
Fold 4 IBS: 0.2168202037004743
Fold 5 IBS: 0.2107572186536838
[I 2024-04-19 04:54:05,693] Trial 25 finished with value: 0.20565755208068418 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.6219587265298226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14752917843030455}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19056366147294207
Fold 2 IBS: 0.20292281880572105
Fold 3 IBS: 0.18783174785043427
Fold 4 IBS: 0.2088003011228546
Fold 5 IBS: 0.20866396438333776
[I 2024-04-19 04:54:27,859] Trial 26 finished with value: 0.19975649872705797 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 387, 'oob_score': True, 'max_samples': 0.7818137659984028, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03246728391959019}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19931350691433533
Fold 2 IBS: 0.19601442962130944
Fold 3 IBS: 0.18796854020412562
Fold 4 IBS: 0.21164896468025474
Fold 5 IBS: 0.21020215321085348
[I 2024-04-19 04:54:52,544] Trial 27 finished with value: 0.2010295189261757 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.7467474904815533, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03398935415705853}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20537139917916725
Fold 2 IBS: 0.19794281274680597
Fold 3 IBS: 0.19479594302639255
Fold 4 IBS: 0.21362311805760684
Fold 5 IBS: 0.21109959348044247
[I 2024-04-19 04:55:15,573] Trial 28 finished with value: 0.20456657329808298 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.7924314502908029, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10210965662749363}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.2085316745240264
Fold 2 IBS: 0.19624993128563048
Fold 3 IBS: 0.19942916002813466
Fold 4 IBS: 0.21827922779222586
Fold 5 IBS: 0.2109486112949144
[I 2024-04-19 04:55:42,288] Trial 29 finished with value: 0.20668772098498636 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 469, 'oob_score': True, 'max_samples': 0.6911949097779824, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20876250884532774
Fold 2 IBS: 0.2047728388418694
Fold 3 IBS: 0.19795126036514604
Fold 4 IBS: 0.21808261740690807
Fold 5 IBS: 0.21344038584082622
[I 2024-04-19 04:56:02,902] Trial 30 finished with value: 0.20860192226001545 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.42881910015561364, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20604809366903232}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19582018456785547
Fold 2 IBS: 0.19411848894287953
Fold 3 IBS: 0.18616865357877121
Fold 4 IBS: 0.21102439454042154

Fold 5 IBS: 0.21026303080320738
[I 2024-04-19 04:56:17,716] Trial 31 finished with value: 0.19947895048662703 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.9640858485797439, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07919805807535037}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19629489252012824
Fold 2 IBS: 0.19759768258837943
Fold 3 IBS: 0.18480416566240168
Fold 4 IBS: 0.21321890670626756
Fold 5 IBS: 0.2135292151651214
[I 2024-04-19 04:56:32,638] Trial 32 finished with value: 0.20108897252845964 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.9502203520505428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.022621037970528283}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20008218370007697
Fold 2 IBS: 0.19783245181287795
Fold 3 IBS: 0.19156084111933405
Fold 4 IBS: 0.21401787549534762
Fold 5 IBS: 0.21094294931994026
[I 2024-04-19 04:56:47,873] Trial 33 finished with value: 0.20288726028951537 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.9412448576783576, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09227781345982045}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20262838908699918
Fold 2 IBS: 0.20849808826469104
Fold 3 IBS: 0.1751722591453099
Fold 4 IBS: 0.2117413711489072
Fold 5 IBS: 0.22020271121508903
[I 2024-04-19 04:57:13,991] Trial 34 finished with value: 0.20364856377219928 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.8572422306646357, 'max_features': None, 'min_weight_fraction_leaf': 0.00033898439226084524}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20827700186222317
Fold 2 IBS: 0.19562273654878523
Fold 3 IBS: 0.19680900261765885
Fold 4 IBS: 0.21731889591437908
Fold 5 IBS: 0.21024341526650012
[I 2024-04-19 04:57:32,063] Trial 35 finished with value: 0.2056542104419093 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.6246728790165794, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16609546988013513}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.1923505502180288
Fold 2 IBS: 0.19547501856823907
Fold 3 IBS: 0.18708289710016698
Fold 4 IBS: 0.21326915075074065
Fold 5 IBS: 0.21177725636674438
[I 2024-04-19 04:57:42,626] Trial 36 finished with value: 0.19999097460078397 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 177, 'oob_score': True, 'max_samples': 0.9920464767910379, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07821728657119803}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.2069501324676298
Fold 2 IBS: 0.1970417765868274
Fold 3 IBS: 0.18765287652349222
Fold 4 IBS: 0.21063846205329517
Fold 5 IBS: 0.2298057991967839
[I 2024-04-19 04:57:57,447] Trial 37 finished with value: 0.20641780936560572 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.7794999171641684, 'max_features': None, 'min_weight_fraction_leaf': 0.033485546245412896}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20797031874612584
Fold 2 IBS: 0.19792872432242578
Fold 3 IBS: 0.1990871898682854
Fold 4 IBS: 0.2192463351331694
Fold 5 IBS: 0.21111678976521245
[I 2024-04-19 04:58:09,637] Trial 38 finished with value: 0.20706987156704376 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.8663614716264392, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20109779431219682
Fold 2 IBS: 0.19621350469225554
Fold 3 IBS: 0.19424884720055247
Fold 4 IBS: 0.21187003413532768
Fold 5 IBS: 0.21174247928306175
[I 2024-04-19 04:58:33,223] Trial 39 finished with value: 0.20303453192467885 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.6597243413434503, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07536072772121663}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.21165368578544405
Fold 2 IBS: 0.18662351607834654
Fold 3 IBS: 0.1969460094871025
Fold 4 IBS: 0.21709270141678652
Fold 5 IBS: 0.21366542426252913
[I 2024-04-19 04:58:42,696] Trial 40 finished with value: 0.20519626740604174 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.46905234645105404, 'max_features': None, 'min_weight_fraction_leaf': 0.12878599199458388}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.21397097593695538
Fold 2 IBS: 0.22141337387830856
Fold 3 IBS: 0.2047934514326142
Fold 4 IBS: 0.22463297954126654
Fold 5 IBS: 0.21855109732430977
[I 2024-04-19 04:58:58,732] Trial 41 finished with value: 0.21667237562269087 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.9407859364956584, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49110484919759173}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19502592174188366
Fold 2 IBS: 0.19749493839923365
Fold 3 IBS: 0.18627296420000075
Fold 4 IBS: 0.20992083251721216
Fold 5 IBS: 0.210975832127458
[I 2024-04-19 04:59:16,794] Trial 42 finished with value: 0.19993809779715763 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.9017564800231042, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05342205994744838}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.19163566093022655
Fold 2 IBS: 0.19845993388386496
Fold 3 IBS: 0.18442993656390624
Fold 4 IBS: 0.21093261918775008
Fold 5 IBS: 0.20933774145535594
[I 2024-04-19 04:59:37,615] Trial 43 finished with value: 0.19895917840422075 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 365, 'oob_score': True, 'max_samples': 0.8223742689754489, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03695240640593313}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.1935785793276764
Fold 2 IBS: 0.19908421344562813
Fold 3 IBS: 0.18729294531322233
Fold 4 IBS: 0.2092253410743728
Fold 5 IBS: 0.20788234101928768
[I 2024-04-19 04:59:58,096] Trial 44 finished with value: 0.19941268403603746 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 372, 'oob_score': True, 'max_samples': 0.8252733369298172, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02931178504777006}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.2014774135747063
Fold 2 IBS: 0.19453477838198652
Fold 3 IBS: 0.19343726063919275
Fold 4 IBS: 0.21264290852794718
Fold 5 IBS: 0.21213933195522844
[I 2024-04-19 05:00:16,246] Trial 45 finished with value: 0.20284633861581222 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.7211266599729008, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0753855145437521}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.2041927029482341
Fold 2 IBS: 0.2009202048512784
Fold 3 IBS: 0.19509720734778754
Fold 4 IBS: 0.21444664627884027
Fold 5 IBS: 0.2105256877438966
[I 2024-04-19 05:00:28,829] Trial 46 finished with value: 0.2050364898340074 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.1873692143114088, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.021672760524907915}. Best is trial 15 with value: 0.19786180218775584.

Fold 1 IBS: 0.21398232464651643
Fold 2 IBS: 0.22130003244265287
Fold 3 IBS: 0.20480819176804077
Fold 4 IBS: 0.22460990433148936
Fold 5 IBS: 0.21859907545237395
[I 2024-04-19 05:00:49,652] Trial 47 finished with value: 0.21665990572821467 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.8235549211572327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4234817047062571}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20724380394603853
Fold 2 IBS: 0.1964488483468546
Fold 3 IBS: 0.19697222605093012
Fold 4 IBS: 0.2161799369468603
Fold 5 IBS: 0.2109509933041631
[I 2024-04-19 05:01:01,766] Trial 48 finished with value: 0.20555916171896932 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 268, 'oob_score': False, 'max_samples': 0.5606440507914384, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11277825579151453}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.21117317428026525
Fold 2 IBS: 0.19431820679844278
Fold 3 IBS: 0.1972541744042535
Fold 4 IBS: 0.21914503468850785
Fold 5 IBS: 0.21254021726208358
[I 2024-04-19 05:01:07,393] Trial 49 finished with value: 0.20688616148671057 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.9603166891760758, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.045883970634078154}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.20788382268499145
Fold 2 IBS: 0.19581605377854436
Fold 3 IBS: 0.1969920133537411
Fold 4 IBS: 0.21590983093342436
Fold 5 IBS: 0.21121494829047086
[I 2024-04-19 05:01:15,309] Trial 50 finished with value: 0.2055633338082344 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 14, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.8342659968669214, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14757275377871126}. Best is trial 15 with value: 0.19786180218775584.
Fold 1 IBS: 0.1892459717160389
Fold 2 IBS: 0.1989380096739198
Fold 3 IBS: 0.17838921054145607
Fold 4 IBS: 0.20647939759830777
Fold 5 IBS: 0.2100143090671217
[I 2024-04-19 05:01:35,670] Trial 51 finished with value: 0.19661337971936885 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.8776182930757223, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.023354941022412236}. Best is trial 51 with value: 0.19661337971936885.
Fold 1 IBS: 0.1898441378040831
Fold 2 IBS: 0.19209372403814187
Fold 3 IBS: 0.17754655430155736
Fold 4 IBS: 0.20760393340027183
Fold 5 IBS: 0.21171539301126888
[I 2024-04-19 05:01:52,580] Trial 52 finished with value: 0.19576074851106462 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.8824765921644189, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020467084926041993}. Best is trial 52 with value: 0.19576074851106462.
Fold 1 IBS: 0.18947932758087585
Fold 2 IBS: 0.193034958184681
Fold 3 IBS: 0.1771493384433015
Fold 4 IBS: 0.20742374276140152
Fold 5 IBS: 0.20954196821762916
[I 2024-04-19 05:02:12,363] Trial 53 finished with value: 0.19532586703757782 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 377, 'oob_score': True, 'max_samples': 0.8724609614102242, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016215503821404215}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.18958512997475976
Fold 2 IBS: 0.19315486086883904
Fold 3 IBS: 0.17753789678226
Fold 4 IBS: 0.20765959311584378
Fold 5 IBS: 0.20964768374135684
[I 2024-04-19 05:02:33,634] Trial 54 finished with value: 0.19551703289661188 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 378, 'oob_score': True, 'max_samples': 0.8762926085138941, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016271099450277143}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.18941277753673877
Fold 2 IBS: 0.1921789075999271
Fold 3 IBS: 0.17838140694257712
Fold 4 IBS: 0.20728305710109132
Fold 5 IBS: 0.20986490178479986
[I 2024-04-19 05:02:52,988] Trial 55 finished with value: 0.19542421019302683 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 344, 'oob_score': True, 'max_samples': 0.8754020118433227, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0069198875931894}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.1894889754403791
Fold 2 IBS: 0.19228954758810865
Fold 3 IBS: 0.17775074730173174
Fold 4 IBS: 0.2067707264112556
Fold 5 IBS: 0.21041669742926708
[I 2024-04-19 05:03:08,797] Trial 56 finished with value: 0.19534333883414842 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 339, 'oob_score': False, 'max_samples': 0.8769899550088869, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0018341883864397938}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.20881656046475316
Fold 2 IBS: 0.19283756705850594
Fold 3 IBS: 0.19776794017374055
Fold 4 IBS: 0.21690934450109275
Fold 5 IBS: 0.21032372999345558
[I 2024-04-19 05:03:30,235] Trial 57 finished with value: 0.20533102843830958 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 418, 'oob_score': True, 'max_samples': 0.8776302476211182, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012103079951441852}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.1979090810411236
Fold 2 IBS: 0.19452088847969778
Fold 3 IBS: 0.18976100273291202
Fold 4 IBS: 0.21245982449330217
Fold 5 IBS: 0.2091965499619894
[I 2024-04-19 05:03:44,784] Trial 58 finished with value: 0.200769469341805 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.7496797414133035, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06360682939834583}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.20637991235717185
Fold 2 IBS: 0.19990727479486486
Fold 3 IBS: 0.19458690584124314
Fold 4 IBS: 0.2145718258939471
Fold 5 IBS: 0.21191886370747545
[I 2024-04-19 05:04:04,226] Trial 59 finished with value: 0.20547295651894046 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 393, 'oob_score': True, 'max_samples': 0.9256301438934582, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01773945951304631}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.189585512677613
Fold 2 IBS: 0.19221358726178173
Fold 3 IBS: 0.17829826112733715
Fold 4 IBS: 0.20741014280805758
Fold 5 IBS: 0.2098299772121954
[I 2024-04-19 05:04:23,308] Trial 60 finished with value: 0.19546749621739698 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 345, 'oob_score': True, 'max_samples': 0.8735669370239985, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0034183730776501725}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.18946929490244824
Fold 2 IBS: 0.19208389491725356
Fold 3 IBS: 0.178210473251096
Fold 4 IBS: 0.2073513624066658
Fold 5 IBS: 0.20964358491848364
[I 2024-04-19 05:04:42,505] Trial 61 finished with value: 0.19535172207918947 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8703358727295742, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004616031730023357}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.18933514133952473
Fold 2 IBS: 0.19415977098882964
Fold 3 IBS: 0.18024966577864315
Fold 4 IBS: 0.2111896982449013

Fold 5 IBS: 0.20741974855549727
[I 2024-04-19 05:05:01,910] Trial 62 finished with value: 0.19647080498147923 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.8590719713823661, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002132335828788339}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.1945971546402581
Fold 2 IBS: 0.19921212051462786
Fold 3 IBS: 0.19069889225062295
Fold 4 IBS: 0.2095358322545664
Fold 5 IBS: 0.21153899502669316
[I 2024-04-19 05:05:18,540] Trial 63 finished with value: 0.2011165989373537 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.9011866179753103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06358250218509034}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.19748461096657727
Fold 2 IBS: 0.200895869860986
Fold 3 IBS: 0.19519055275409988
Fold 4 IBS: 0.2135176678792689
Fold 5 IBS: 0.21334437039122078
[I 2024-04-19 05:05:37,887] Trial 64 finished with value: 0.20408661437043057 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.26967029716304014, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0005113585420692525}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.19353479396380838
Fold 2 IBS: 0.1965692767673565
Fold 3 IBS: 0.1831191005430294
Fold 4 IBS: 0.20850197572531542
Fold 5 IBS: 0.21119001602782805
[I 2024-04-19 05:06:01,664] Trial 65 finished with value: 0.19858303260546756 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.764333616096535, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04483522505241103}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.20453983076395274
Fold 2 IBS: 0.19771612895770338
Fold 3 IBS: 0.1897326956754674
Fold 4 IBS: 0.21040832101600895
Fold 5 IBS: 0.22934458403816893
[I 2024-04-19 05:06:19,330] Trial 66 finished with value: 0.20634831209026028 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.7971811287543605, 'max_features': None, 'min_weight_fraction_leaf': 0.019793309911120063}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.20557783530449505
Fold 2 IBS: 0.19652591079002668
Fold 3 IBS: 0.19415791657028825
Fold 4 IBS: 0.213785674537103
Fold 5 IBS: 0.21047453029034366
[I 2024-04-19 05:06:34,038] Trial 67 finished with value: 0.20410437349845134 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.7014262954234541, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09333890046308156}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.19822254982264054
Fold 2 IBS: 0.19558108221994697
Fold 3 IBS: 0.1912796556998267
Fold 4 IBS: 0.21196604383891604
Fold 5 IBS: 0.21301686196988628
[I 2024-04-19 05:06:55,371] Trial 68 finished with value: 0.2020132387102433 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.9137473607178082, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01343749941939249}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.19260884197173797
Fold 2 IBS: 0.1969195589196943
Fold 3 IBS: 0.18556925373164737
Fold 4 IBS: 0.2085902663061315
Fold 5 IBS: 0.21050765059318063
[I 2024-04-19 05:07:13,121] Trial 69 finished with value: 0.19883911430447837 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.8499127865166863, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057063966086236796}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.19172065644032707
Fold 2 IBS: 0.1986169920615685
Fold 3 IBS: 0.176389992782783
Fold 4 IBS: 0.20889914991529018
Fold 5 IBS: 0.2112777971538129
[I 2024-04-19 05:07:36,932] Trial 70 finished with value: 0.19738091767075633 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 427, 'oob_score': True, 'max_samples': 0.9610439908039032, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0415962943637813}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.18973995970367008
Fold 2 IBS: 0.19231670687129115
Fold 3 IBS: 0.17768766326412638
Fold 4 IBS: 0.20823595011625357
Fold 5 IBS: 0.20922996720305376
[I 2024-04-19 05:07:58,276] Trial 71 finished with value: 0.195442049431679 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 350, 'oob_score': True, 'max_samples': 0.8793436281140008, 'max_features': 'log2', 'min_weight_fraction_leaf': 8.299408988513132e-05}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.19016663421543734
Fold 2 IBS: 0.19744698818894402
Fold 3 IBS: 0.18343946350253587
Fold 4 IBS: 0.20682775701133055
Fold 5 IBS: 0.21156036238878212
[I 2024-04-19 05:08:18,945] Trial 72 finished with value: 0.19788824106140596 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8852733325216853, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01175861068517633}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.18988342151012738
Fold 2 IBS: 0.2001390520417897
Fold 3 IBS: 0.18220398736398827
Fold 4 IBS: 0.20643016184976595
Fold 5 IBS: 0.20818583582253333
[I 2024-04-19 05:08:40,330] Trial 73 finished with value: 0.19736849171764093 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.9244877811580879, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030147830778679965}. Best is trial 53 with value: 0.19532586703757782.
Fold 1 IBS: 0.17870255459947532
Fold 2 IBS: 0.19625745534527977
Fold 3 IBS: 0.18690295076302646
Fold 4 IBS: 0.19999496684667706
Fold 5 IBS: 0.21210281227805783
[I 2024-04-19 05:08:44,309] Trial 74 finished with value: 0.1947921479665033 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.8407950651939462, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018820068972654837}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.1884090270901608
Fold 2 IBS: 0.2005412137472612
Fold 3 IBS: 0.18518473531433868
Fold 4 IBS: 0.2109960125530602
Fold 5 IBS: 0.21568585048213243
[I 2024-04-19 05:08:48,598] Trial 75 finished with value: 0.2001633678373907 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 69, 'oob_score': True, 'max_samples': 0.8020664927907588, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0014546526816572084}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19565947660068866
Fold 2 IBS: 0.19631251537938318
Fold 3 IBS: 0.18964053149657953
Fold 4 IBS: 0.2105993516345744
Fold 5 IBS: 0.21075701103177097
[I 2024-04-19 05:09:08,577] Trial 76 finished with value: 0.20059377722859936 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.8471105282946587, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06731770666648224}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.2086725950469635
Fold 2 IBS: 0.198719412364134
Fold 3 IBS: 0.19984746827490713
Fold 4 IBS: 0.2196788814646441
Fold 5 IBS: 0.21144264910905794
[I 2024-04-19 05:09:13,363] Trial 77 finished with value: 0.20767220125194133 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 124, 'oob_score': False, 'max_samples': 0.857986820275778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3084424043942947}. Best is trial 74 with value: 0.1947921479665033.

Fold 1 IBS: 0.1989053774529102
Fold 2 IBS: 0.19827714229698426
Fold 3 IBS: 0.19062588382836543
Fold 4 IBS: 0.2093318900607619
Fold 5 IBS: 0.20997416546820158
[I 2024-04-19 05:09:35,081] Trial 78 finished with value: 0.20142289182144468 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.9323713852052357, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04247308366617032}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.18598650836541217
Fold 2 IBS: 0.1884315468040781
Fold 3 IBS: 0.19522799169986055
Fold 4 IBS: 0.22724133183991238
Fold 5 IBS: 0.21327248450930764
[I 2024-04-19 05:09:37,268] Trial 79 finished with value: 0.20203197264371414 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 25, 'oob_score': True, 'max_samples': 0.9993252499502729, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08733895686376512}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19643998509673552
Fold 2 IBS: 0.20948379740037812
Fold 3 IBS: 0.17910694810196517
Fold 4 IBS: 0.2094467411983755
Fold 5 IBS: 0.21548639260238725
[I 2024-04-19 05:10:07,002] Trial 80 finished with value: 0.20199277287996834 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 479, 'oob_score': True, 'max_samples': 0.7587030711514144, 'max_features': None, 'min_weight_fraction_leaf': 0.02965181993746184}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19170428980287904
Fold 2 IBS: 0.19201497571791518
Fold 3 IBS: 0.17782515916302138
Fold 4 IBS: 0.20709707452512244
Fold 5 IBS: 0.20902490125573236
[I 2024-04-19 05:10:25,125] Trial 81 finished with value: 0.19553328009293408 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.8898653780156545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01694799594042332}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.20854920409391237
Fold 2 IBS: 0.20121445157202003
Fold 3 IBS: 0.1978884021325597
Fold 4 IBS: 0.21921070693674072
Fold 5 IBS: 0.21167055373292068
[I 2024-04-19 05:10:41,854] Trial 82 finished with value: 0.20770666369363072 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.8943500691594968, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.37875540676023556}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.18921850980617175
Fold 2 IBS: 0.1935858155427138
Fold 3 IBS: 0.18136973053736977
Fold 4 IBS: 0.2104098431821585
Fold 5 IBS: 0.20821515976448157
[I 2024-04-19 05:10:58,857] Trial 83 finished with value: 0.19655981176657908 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.8408113929741404, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010097023120830936}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19236799982184727
Fold 2 IBS: 0.19628045755189585
Fold 3 IBS: 0.18424824050435457
Fold 4 IBS: 0.2092527312692294
Fold 5 IBS: 0.21146023875670542
[I 2024-04-19 05:11:18,768] Trial 84 finished with value: 0.19872193358080648 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.778538760126459, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05113045735766471}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.195494976151048
Fold 2 IBS: 0.19860132822215498
Fold 3 IBS: 0.18692353842171697
Fold 4 IBS: 0.21014701176324097
Fold 5 IBS: 0.2083492801955209
[I 2024-04-19 05:11:36,134] Trial 85 finished with value: 0.19990322695073637 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 311, 'oob_score': True, 'max_samples': 0.8102502230701356, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030343078703234334}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.18863760468078056
Fold 2 IBS: 0.20337871623926948
Fold 3 IBS: 0.179806485841862
Fold 4 IBS: 0.20968503093291688
Fold 5 IBS: 0.21430920135033332
[I 2024-04-19 05:11:51,303] Trial 86 finished with value: 0.19916340780903244 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.9711788670716626, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01189015916126129}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.21005872027374187
Fold 2 IBS: 0.19474826140218343
Fold 3 IBS: 0.19798316761919488
Fold 4 IBS: 0.21669309048717694
Fold 5 IBS: 0.21016707136008378
[I 2024-04-19 05:12:06,700] Trial 87 finished with value: 0.20593006222847618 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 379, 'oob_score': False, 'max_samples': 0.9371147151901998, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23270154165056978}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.20904635083373438
Fold 2 IBS: 0.1958373505132311
Fold 3 IBS: 0.19901546815538798
Fold 4 IBS: 0.2181330241122277
Fold 5 IBS: 0.21055924230145212
[I 2024-04-19 05:12:23,132] Trial 88 finished with value: 0.20651828718320667 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.9061173973772448, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27389916846875384}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19723009397417499
Fold 2 IBS: 0.1949583050049705
Fold 3 IBS: 0.18957977589795172
Fold 4 IBS: 0.2120838490610189
Fold 5 IBS: 0.20945642995685287
[I 2024-04-19 05:12:42,182] Trial 89 finished with value: 0.20066169077899382 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.823578602701572, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03960670788588953}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.18393341020495624
Fold 2 IBS: 0.19937723221907902
Fold 3 IBS: 0.18087011025075267
Fold 4 IBS: 0.20797384643482184
Fold 5 IBS: 0.20972929243579505
[I 2024-04-19 05:13:00,913] Trial 90 finished with value: 0.19637677830908098 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.87124477368274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02125413687076729}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19130766639588193
Fold 2 IBS: 0.19294504892824751
Fold 3 IBS: 0.178234722413023
Fold 4 IBS: 0.20944388861940846
Fold 5 IBS: 0.20830792636827813
[I 2024-04-19 05:13:21,163] Trial 91 finished with value: 0.1960478505449678 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.8898268929381877, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016984099264329644}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19129845886377192
Fold 2 IBS: 0.19683452399991896
Fold 3 IBS: 0.18206729614682252
Fold 4 IBS: 0.20673521244967968
Fold 5 IBS: 0.21277211035866653
[I 2024-04-19 05:13:37,839] Trial 92 finished with value: 0.19794152036377194 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.87221067756335, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0008635915888943087}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.1896681785627518
Fold 2 IBS: 0.19734326279159708
Fold 3 IBS: 0.17880808734747608
Fold 4 IBS: 0.20807475394924582
Fold 5 IBS: 0.21128113738467275
[I 2024-04-19 05:13:57,448] Trial 93 finished with value: 0.1970350840071487 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.8414535459165708, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.025708904718510714}. Best is trial 74 with value: 0.1947921479665033.

Fold 1 IBS: 0.1968798726882478
Fold 2 IBS: 0.1998433173802242
Fold 3 IBS: 0.18609682967348268
Fold 4 IBS: 0.21023083237520823
Fold 5 IBS: 0.21164269021564036
[I 2024-04-19 05:14:14,519] Trial 94 finished with value: 0.20093870846656064 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.9158810703611461, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06111476813323878}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.19370745975298193
Fold 2 IBS: 0.19737884950176132
Fold 3 IBS: 0.1830704811594634
Fold 4 IBS: 0.20837912758814287
Fold 5 IBS: 0.21257524928247132
[I 2024-04-19 05:14:36,876] Trial 95 finished with value: 0.19902223345696415 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 412, 'oob_score': True, 'max_samples': 0.9420898595431166, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.049012277759372655}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.20904658327445652
Fold 2 IBS: 0.19411513174938153
Fold 3 IBS: 0.19784985709949598
Fold 4 IBS: 0.2167064234928242
Fold 5 IBS: 0.21014366953900038
[I 2024-04-19 05:14:51,014] Trial 96 finished with value: 0.20557233303103173 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.8872364394307753, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03485699935097149}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.20072642234901872
Fold 2 IBS: 0.19459715554172505
Fold 3 IBS: 0.19041480488932447
Fold 4 IBS: 0.20893734352083024
Fold 5 IBS: 0.21423658713814303
[I 2024-04-19 05:15:08,575] Trial 97 finished with value: 0.20178246268780833 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.521538664132392, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009629170294038076}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.2018983775106938
Fold 2 IBS: 0.2084558383723328
Fold 3 IBS: 0.18986168860968852
Fold 4 IBS: 0.21102024128009733
Fold 5 IBS: 0.22882649022664583
[I 2024-04-19 05:15:31,716] Trial 98 finished with value: 0.20801252719989166 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.7281128575202597, 'max_features': None, 'min_weight_fraction_leaf': 0.06748568004804964}. Best is trial 74 with value: 0.1947921479665033.
Fold 1 IBS: 0.20760300976828355
Fold 2 IBS: 0.1944296234579453
Fold 3 IBS: 0.19877237538335837
Fold 4 IBS: 0.21663047075475553
Fold 5 IBS: 0.21026231765299425
[I 2024-04-19 05:15:46,739] Trial 99 finished with value: 0.20553955940346738 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.8594175508592206, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19023551454841547}. Best is trial 74 with value: 0.1947921479665033.


* Best trial for IBS:
 FrozenTrial(number=74, state=TrialState.COMPLETE, values=[0.1947921479665033], datetime_start=datetime.datetime(2024, 4, 19, 5, 8, 40, 340251), datetime_complete=datetime.datetime(2024, 4, 19, 5, 8, 44, 308274), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.8407950651939462, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018820068972654837}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=74, value=None)


* Best Score for IBS:
 0.1947921479665033

In [92]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [93]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.863
train_ibs:  0.195

#### Test

In [94]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [95]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=19, max_features=None, max_leaf_nodes=12,
                     max_samples=0.630961889364407, min_samples_split=5,
                     min_weight_fraction_leaf=0.011342387005902448,
                     n_estimators=218, random_state=123, warm_start=True)

test_cindex:  0.621

RandomSurvivalForest(max_depth=18, max_features='log2', max_leaf_nodes=17,
                     max_samples=0.8407950651939462, min_samples_leaf=2,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.018820068972654837,
                     n_estimators=68, oob_score=True, random_state=123)

test_ibs:  0.22

In [96]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [97]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [98]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 05:15:50,388] A new study created in memory with name: no-name-4e8544af-61c9-4bdd-a800-c353c9697a4d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 05:15:53,769] Trial 0 finished with value: 0.695318892358642 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:16:02,089] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6455696202531646
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 05:16:19,543] Trial 2 finished with value: 0.6640296573093653 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6495098039215687
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 05:16:21,156] Trial 3 finished with value: 0.6777004799391353 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:16:27,555] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:16:35,502] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 05:16:39,631] Trial 6 finished with value: 0.6942427858515973 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6413502109704642
Fold 5 C-index: 0.6713615023474179
[I 2024-04-19 05:16:49,771] Trial 7 finished with value: 0.6778275476546638 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.5906862745098039
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 05:16:50,345] Trial 8 finished with value: 0.65466805747729 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.5906862745098039
Fold 4 C-index: 0.5970464135021097
Fold 5 C-index: 0.607981220657277
[I 2024-04-19 05:17:11,063] Trial 9 finished with value: 0.6400139938550502 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:17:17,952] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 05:17:21,516] Trial 11 finished with value: 0.671819718543668 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.695318892358642.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 05:17:26,979] Trial 12 finished with value: 0.7316118600068109 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6372549019607843
Fold 4 C-index: 0.6856540084388185
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 05:17:31,825] Trial 13 finished with value: 0.6767129021335758 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 05:17:35,732] Trial 14 finished with value: 0.6763759467384419 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8258928571428571

Fold 3 C-index: 0.5931372549019608
Fold 4 C-index: 0.6434599156118144
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 05:17:38,473] Trial 15 finished with value: 0.6682628979159372 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.5833333333333334
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6455399061032864
[I 2024-04-19 05:17:43,950] Trial 16 finished with value: 0.6626992053973245 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6323529411764706
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 05:17:47,395] Trial 17 finished with value: 0.6766882588543287 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:17:53,043] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6274509803921569
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.6150234741784038
[I 2024-04-19 05:17:57,648] Trial 19 finished with value: 0.6733596095288308 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.5952380952380952
Fold 2 C-index: 0.6272321428571429
Fold 3 C-index: 0.5612745098039216
Fold 4 C-index: 0.5864978902953587
Fold 5 C-index: 0.5727699530516432
[I 2024-04-19 05:17:58,183] Trial 20 finished with value: 0.5886025182492324 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 05:18:02,809] Trial 21 finished with value: 0.6947480311027473 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 05:18:07,689] Trial 22 finished with value: 0.7040470226648821 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7316118600068109.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 05:18:12,731] Trial 23 finished with value: 0.7368025709935508 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 05:18:17,435] Trial 24 finished with value: 0.717057170523763 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 05:18:21,950] Trial 25 finished with value: 0.7034276384178852 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.38951355347611605, 'min_weight_fraction_leaf': 0.04193971879336897}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:18:45,480] Trial 26 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.27487888259278787, 'min_weight_fraction_leaf': 0.14724522382749441}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.6561181434599156
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 05:18:49,405] Trial 27 finished with value: 0.676088069346606 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 396, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4781538194281684, 'min_weight_fraction_leaf': 0.0904199061977867}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:18:52,664] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.17318794780983382, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.6029411764705882
Fold 4 C-index: 0.6729957805907173
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 05:18:57,949] Trial 29 finished with value: 0.6654946897477284 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4010222518898351, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 23 with value: 0.7368025709935508.

Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6519607843137255
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 05:19:01,625] Trial 30 finished with value: 0.6874414240809373 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.04228849156393042}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 05:19:05,547] Trial 31 finished with value: 0.7093396374092839 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 401, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6266312071772465, 'min_weight_fraction_leaf': 0.02883143947787432}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 05:19:09,680] Trial 32 finished with value: 0.7007847574514984 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5366184656750503, 'min_weight_fraction_leaf': 0.06665303212999554}. Best is trial 23 with value: 0.7368025709935508.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 05:19:14,486] Trial 33 finished with value: 0.7425680581151568 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6272400043308528, 'min_weight_fraction_leaf': 0.026618193212986738}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 05:19:19,000] Trial 34 finished with value: 0.6968501809385159 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5205488182996534, 'min_weight_fraction_leaf': 0.0794145152463269}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.5735294117647058
Fold 4 C-index: 0.6603375527426161
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 05:19:28,982] Trial 35 finished with value: 0.6609177286127015 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4082890393817229, 'min_weight_fraction_leaf': 0.12132570942744575}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6244725738396625
Fold 5 C-index: 0.6431924882629108
[I 2024-04-19 05:19:37,138] Trial 36 finished with value: 0.6662478710912556 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 206, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8433256372932227, 'min_weight_fraction_leaf': 0.015689588085094987}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6151960784313726
Fold 4 C-index: 0.6603375527426161
Fold 5 C-index: 0.6056338028169014
[I 2024-04-19 05:19:42,179] Trial 37 finished with value: 0.6713904132051044 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9245147124114204, 'min_weight_fraction_leaf': 0.053816600225102}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6384976525821596
[I 2024-04-19 05:19:47,149] Trial 38 finished with value: 0.6870276605026036 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7345769604633695, 'min_weight_fraction_leaf': 0.11154191927197109}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.6053921568627451
Fold 4 C-index: 0.609704641350211
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 05:20:06,890] Trial 39 finished with value: 0.6579126969390975 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.35834900093396527, 'min_weight_fraction_leaf': 0.16834706520126874}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:20:11,096] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.46241027523020106, 'min_weight_fraction_leaf': 0.4492877633512613}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6948356807511737
[I 2024-04-19 05:20:16,680] Trial 41 finished with value: 0.7042446050204065 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.613847833873583, 'min_weight_fraction_leaf': 0.0038214521335236395}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 05:20:21,175] Trial 42 finished with value: 0.7224570674799037 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.645660565169646, 'min_weight_fraction_leaf': 0.028954072511129886}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 05:20:25,869] Trial 43 finished with value: 0.7162105260911802 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6770838324718738, 'min_weight_fraction_leaf': 0.02622851394888776}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 05:20:31,428] Trial 44 finished with value: 0.720800454251945 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8140890830718792, 'min_weight_fraction_leaf': 0.05283060304092351}. Best is trial 33 with value: 0.7425680581151568.

Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 05:20:37,322] Trial 45 finished with value: 0.7131156052835891 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8207238871817507, 'min_weight_fraction_leaf': 0.08042455204747012}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 05:20:42,236] Trial 46 finished with value: 0.6801558340316952 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7408693234023009, 'min_weight_fraction_leaf': 0.05790671547050146}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6255411255411255
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.5612745098039216
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.5892018779342723
[I 2024-04-19 05:21:01,692] Trial 47 finished with value: 0.6380847564231935 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 442, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.938104471893314, 'min_weight_fraction_leaf': 0.28271174351550016}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 05:21:09,649] Trial 48 finished with value: 0.7324142785365819 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 378, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7738864404593994, 'min_weight_fraction_leaf': 0.0033462024732769657}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 05:21:16,124] Trial 49 finished with value: 0.7416470568032396 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 280, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5878068215906733, 'min_weight_fraction_leaf': 0.018474903208824816}. Best is trial 33 with value: 0.7425680581151568.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 05:21:22,407] Trial 50 finished with value: 0.7449360988013416 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 287, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7684297183829674, 'min_weight_fraction_leaf': 0.0033950329567280467}. Best is trial 50 with value: 0.7449360988013416.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 05:21:27,908] Trial 51 finished with value: 0.7422142826725011 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 219, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7766727944323193, 'min_weight_fraction_leaf': 0.0006969493256422897}. Best is trial 50 with value: 0.7449360988013416.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7323943661971831
[I 2024-04-19 05:21:33,531] Trial 52 finished with value: 0.7394682755596282 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 234, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7548255633618559, 'min_weight_fraction_leaf': 0.0017072474457803313}. Best is trial 50 with value: 0.7449360988013416.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 05:21:38,869] Trial 53 finished with value: 0.7364170159952017 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 230, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7007792479846704, 'min_weight_fraction_leaf': 0.017548966653496968}. Best is trial 50 with value: 0.7449360988013416.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 05:21:42,364] Trial 54 finished with value: 0.7089476518171736 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 151, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7564318572815869, 'min_weight_fraction_leaf': 0.06808029508414576}. Best is trial 50 with value: 0.7449360988013416.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 05:21:49,191] Trial 55 finished with value: 0.745556076366591 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 295, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5907788143309503, 'min_weight_fraction_leaf': 0.01934584842509632}. Best is trial 55 with value: 0.745556076366591.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7652582159624414
[I 2024-04-19 05:21:55,337] Trial 56 finished with value: 0.7595290327674207 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 283, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.595446274886461, 'min_weight_fraction_leaf': 0.017557826969164237}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 05:22:02,622] Trial 57 finished with value: 0.74385908117765 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5929248648695017, 'min_weight_fraction_leaf': 0.020565109671974353}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6341991341991342
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.5980392156862745
Fold 4 C-index: 0.630801687763713
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 05:22:06,063] Trial 58 finished with value: 0.671073802298436 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 167, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5012067138000867, 'min_weight_fraction_leaf': 0.09773275602331735}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:22:20,108] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 282, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5650937244529346, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 56 with value: 0.7595290327674207.

Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 05:22:27,432] Trial 60 finished with value: 0.701086792478057 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 325, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6715273874224342, 'min_weight_fraction_leaf': 0.08439662809627732}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 05:22:34,537] Trial 61 finished with value: 0.7482807577884555 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5786142078032889, 'min_weight_fraction_leaf': 0.019308286494261306}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 05:22:42,715] Trial 62 finished with value: 0.7471050578045769 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 302, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.581144073126684, 'min_weight_fraction_leaf': 0.021617057311557338}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6995305164319249
[I 2024-04-19 05:22:49,879] Trial 63 finished with value: 0.7132306488698659 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 297, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5811382879895272, 'min_weight_fraction_leaf': 0.048346736188851804}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 05:22:55,968] Trial 64 finished with value: 0.747242161423152 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 251, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.550578404711721, 'min_weight_fraction_leaf': 0.022272602173385614}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 05:23:02,242] Trial 65 finished with value: 0.6921332559993639 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 262, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5185963788976474, 'min_weight_fraction_leaf': 0.062472276523278136}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:23:09,495] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 307, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.43987566300168945, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-19 05:23:15,127] Trial 67 finished with value: 0.716643195836496 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 253, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5438446862110337, 'min_weight_fraction_leaf': 0.03968181972003887}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 05:23:21,443] Trial 68 finished with value: 0.7481660280280931 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 268, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4935722353302252, 'min_weight_fraction_leaf': 0.01628761845926131}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6572769953051644
[I 2024-04-19 05:23:29,840] Trial 69 finished with value: 0.6892064482724322 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 338, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.48490098908304324, 'min_weight_fraction_leaf': 0.06677788948542236}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6854460093896714
[I 2024-04-19 05:23:37,724] Trial 70 finished with value: 0.7163429804894941 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 306, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.44300281300351113, 'min_weight_fraction_leaf': 0.03639216953975695}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7605633802816901
[I 2024-04-19 05:23:44,129] Trial 71 finished with value: 0.74385908117765 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 276, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5975740041691894, 'min_weight_fraction_leaf': 0.022035149780415014}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7511737089201878
[I 2024-04-19 05:23:49,950] Trial 72 finished with value: 0.7549097763548278 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 268, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5614433033648029, 'min_weight_fraction_leaf': 0.016312534920031953}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 05:23:54,887] Trial 73 finished with value: 0.7466298751465448 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5344433308661544, 'min_weight_fraction_leaf': 0.01556522341255021}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6901408450704225
[I 2024-04-19 05:24:01,122] Trial 74 finished with value: 0.7147773583330803 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5481444123860234, 'min_weight_fraction_leaf': 0.04814296879219118}. Best is trial 56 with value: 0.7595290327674207.

Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 05:24:07,359] Trial 75 finished with value: 0.7538106986988381 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4979386231480663, 'min_weight_fraction_leaf': 0.017327659016829845}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.6371308016877637
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 05:24:16,866] Trial 76 finished with value: 0.67209439254721 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 184, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5107246121423185, 'min_weight_fraction_leaf': 0.03550146021516345}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.676056338028169
[I 2024-04-19 05:24:22,618] Trial 77 finished with value: 0.699229904404427 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 265, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4644871016321285, 'min_weight_fraction_leaf': 0.07285082975325433}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6350210970464135
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 05:24:27,658] Trial 78 finished with value: 0.6676463789619642 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 213, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5352693259445603, 'min_weight_fraction_leaf': 0.13273356770989325}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7136150234741784
[I 2024-04-19 05:24:33,538] Trial 79 finished with value: 0.7089861440127032 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 244, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4261900842378196, 'min_weight_fraction_leaf': 0.013391896916119719}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6421568627450981
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 05:24:37,815] Trial 80 finished with value: 0.6948803444780236 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 190, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4856164602611386, 'min_weight_fraction_leaf': 0.03598749283324841}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 05:24:44,557] Trial 81 finished with value: 0.7464979087957652 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 321, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6083058702868847, 'min_weight_fraction_leaf': 0.02090805051309326}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.704225352112676
[I 2024-04-19 05:24:51,243] Trial 82 finished with value: 0.7121766381474388 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5685153612749743, 'min_weight_fraction_leaf': 0.051766331694915194}. Best is trial 56 with value: 0.7595290327674207.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 05:24:59,593] Trial 83 finished with value: 0.7702640508544623 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 354, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6515639219466551, 'min_weight_fraction_leaf': 0.014432583960109812}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.7464788732394366
[I 2024-04-19 05:25:07,879] Trial 84 finished with value: 0.7559074383006903 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6558154688123807, 'min_weight_fraction_leaf': 0.012415960770006482}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7183098591549296
[I 2024-04-19 05:25:15,684] Trial 85 finished with value: 0.7140297881174544 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 359, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6514865638630355, 'min_weight_fraction_leaf': 0.05903160131687053}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 05:25:23,613] Trial 86 finished with value: 0.695999659933018 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6615882665031715, 'min_weight_fraction_leaf': 0.09134218430306051}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.6470588235294118
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6619718309859155
[I 2024-04-19 05:25:29,780] Trial 87 finished with value: 0.6909443713545971 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 266, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6303347416000258, 'min_weight_fraction_leaf': 0.033343924773771995}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6255411255411255
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.5661764705882353
Fold 4 C-index: 0.5822784810126582
Fold 5 C-index: 0.5704225352112676
[I 2024-04-19 05:25:41,497] Trial 88 finished with value: 0.6269194367563716 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 224, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7079742258779333, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7370892018779343
[I 2024-04-19 05:25:48,424] Trial 89 finished with value: 0.7467268476378705 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 332, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5615309124452766, 'min_weight_fraction_leaf': 0.04579458322090792}. Best is trial 83 with value: 0.7702640508544623.

Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.7417840375586855
[I 2024-04-19 05:25:55,178] Trial 90 finished with value: 0.7433757932418174 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 306, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6361159681828972, 'min_weight_fraction_leaf': 0.00873529221168662}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.755868544600939
[I 2024-04-19 05:26:03,114] Trial 91 finished with value: 0.7583893742427035 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 371, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5555240538262884, 'min_weight_fraction_leaf': 0.0446943410651284}. Best is trial 83 with value: 0.7702640508544623.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 05:26:10,631] Trial 92 finished with value: 0.7796813074003486 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 392, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6136124414087472, 'min_weight_fraction_leaf': 0.02855366076379152}. Best is trial 92 with value: 0.7796813074003486.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8169014084507042
[I 2024-04-19 05:26:17,661] Trial 93 finished with value: 0.8053103189524566 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.614535952562826, 'min_weight_fraction_leaf': 0.00932835229179093}. Best is trial 93 with value: 0.8053103189524566.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.8215962441314554
[I 2024-04-19 05:26:25,200] Trial 94 finished with value: 0.8080298631065256 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 370, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6196177319145886, 'min_weight_fraction_leaf': 0.010458229178985291}. Best is trial 94 with value: 0.8080298631065256.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8169014084507042
[I 2024-04-19 05:26:32,803] Trial 95 finished with value: 0.8053103189524566 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 370, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6125597128128425, 'min_weight_fraction_leaf': 0.0016484675050177748}. Best is trial 94 with value: 0.8080298631065256.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8169014084507042
[I 2024-04-19 05:26:40,637] Trial 96 finished with value: 0.8044174618095996 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 368, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6110678570769325, 'min_weight_fraction_leaf': 0.010535243135849949}. Best is trial 94 with value: 0.8080298631065256.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7230046948356808
[I 2024-04-19 05:26:48,330] Trial 97 finished with value: 0.7393029250550119 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 369, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6165335294838272, 'min_weight_fraction_leaf': 0.003260866161392}. Best is trial 94 with value: 0.8080298631065256.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.784037558685446
[I 2024-04-19 05:26:56,138] Trial 98 finished with value: 0.7824890156389952 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 394, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6849724890175477, 'min_weight_fraction_leaf': 0.030131861130174794}. Best is trial 94 with value: 0.8080298631065256.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827

[I 2024-04-19 05:27:04,648] A new study created in memory with name: no-name-140cc47c-58e7-461a-a22a-2f69a9d0f859

Fold 5 C-index: 0.784037558685446
[I 2024-04-19 05:27:04,632] Trial 99 finished with value: 0.7833714572232238 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6639073301110476, 'min_weight_fraction_leaf': 0.032165140012279894}. Best is trial 94 with value: 0.8080298631065256.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.8080298631065256], datetime_start=datetime.datetime(2024, 4, 19, 5, 26, 17, 668758), datetime_complete=datetime.datetime(2024, 4, 19, 5, 26, 25, 199226), params={'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 370, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6196177319145886, 'min_weight_fraction_leaf': 0.010458229178985291}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=94, value=None)


* Best Score for C-index:
 0.8080298631065256

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.20727933434502707
Fold 2 IBS: 0.2132532394373222
Fold 3 IBS: 0.20068722953806026
Fold 4 IBS: 0.21847528718726078
Fold 5 IBS: 0.21460529776072682
[I 2024-04-19 05:27:18,771] Trial 0 finished with value: 0.21086007765367945 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-19 05:27:38,993] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.21169408533028256
Fold 2 IBS: 0.21829853652008552
Fold 3 IBS: 0.20306418829112627
Fold 4 IBS: 0.2224271169584378
Fold 5 IBS: 0.21706917937629827
[I 2024-04-19 05:27:55,897] Trial 2 finished with value: 0.21451062129524606 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.21133335781176385
Fold 2 IBS: 0.218226072373453
Fold 3 IBS: 0.20321018241655253
Fold 4 IBS: 0.22263040709113233
Fold 5 IBS: 0.2169213590509278
[I 2024-04-19 05:28:02,025] Trial 3 finished with value: 0.21446427574876595 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-19 05:28:16,497] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-19 05:28:23,722] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.20761170408680765
Fold 2 IBS: 0.2129559852793209
Fold 3 IBS: 0.20085197675451552
Fold 4 IBS: 0.21887314150975173
Fold 5 IBS: 0.2146907187065096
[I 2024-04-19 05:28:40,497] Trial 6 finished with value: 0.21099670526738107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.20877020523964696
Fold 2 IBS: 0.21476228908891304
Fold 3 IBS: 0.20112591022130982
Fold 4 IBS: 0.21990587813860776
Fold 5 IBS: 0.21491887786906605
[I 2024-04-19 05:28:50,298] Trial 7 finished with value: 0.2118966321115087 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.21300995565709424
Fold 2 IBS: 0.2196052061043441
Fold 3 IBS: 0.2035482152510369
Fold 4 IBS: 0.2240044590417637
Fold 5 IBS: 0.21634412233002018
[I 2024-04-19 05:28:52,355] Trial 8 finished with value: 0.2153023916768518 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.2130885098825688
Fold 2 IBS: 0.22039898758191573
Fold 3 IBS: 0.20419192934231212
Fold 4 IBS: 0.22415375875723023
Fold 5 IBS: 0.217837430286046
[I 2024-04-19 05:29:11,923] Trial 9 finished with value: 0.21593412317001456 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.21398675665395545
Fold 2 IBS: 0.22062051307224878
Fold 3 IBS: 0.2050387676808756
Fold 4 IBS: 0.22464909968237873
Fold 5 IBS: 0.2178578633686426
[I 2024-04-19 05:29:28,877] Trial 10 finished with value: 0.2164306000916202 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.2111918126144865
Fold 2 IBS: 0.21713497544202337
Fold 3 IBS: 0.20298392453422545
Fold 4 IBS: 0.22250924050795332
Fold 5 IBS: 0.21623866496586805
[I 2024-04-19 05:29:44,381] Trial 11 finished with value: 0.21401172361291132 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21086007765367945.
Fold 1 IBS: 0.20313582323373355
Fold 2 IBS: 0.20884385928873006
Fold 3 IBS: 0.19861100880595692
Fold 4 IBS: 0.2154799818012607
Fold 5 IBS: 0.21302192030879405
[I 2024-04-19 05:30:02,974] Trial 12 finished with value: 0.20781851868769508 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.21118597395071495
Fold 2 IBS: 0.21695687429135083
Fold 3 IBS: 0.2025651967705601
Fold 4 IBS: 0.22128931451206424
Fold 5 IBS: 0.2166910496970897
[I 2024-04-19 05:30:21,136] Trial 13 finished with value: 0.213737681844356 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.21105818026450082
Fold 2 IBS: 0.21744840836453688
Fold 3 IBS: 0.20302686936168018
Fold 4 IBS: 0.22200473367367998
Fold 5 IBS: 0.21634082507240035
[I 2024-04-19 05:30:36,037] Trial 14 finished with value: 0.21397580334735963 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.20781851868769508.

Fold 1 IBS: 0.211942627728142
Fold 2 IBS: 0.21792596768934377
Fold 3 IBS: 0.20318395070375334
Fold 4 IBS: 0.22171811745803355
Fold 5 IBS: 0.21658132948247918
[I 2024-04-19 05:30:45,889] Trial 15 finished with value: 0.21427039861235037 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.2135910734264954
Fold 2 IBS: 0.22084412990790042
Fold 3 IBS: 0.20452940342331205
Fold 4 IBS: 0.22433327711097464
Fold 5 IBS: 0.2182237006084311
[I 2024-04-19 05:31:03,216] Trial 16 finished with value: 0.2163043168954227 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.209263135119613
Fold 2 IBS: 0.2124511030088567
Fold 3 IBS: 0.20074118766654447
Fold 4 IBS: 0.2199375196002034
Fold 5 IBS: 0.21521952313681025
[I 2024-04-19 05:31:15,341] Trial 17 finished with value: 0.21152249370640552 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.21392899653036146
Fold 2 IBS: 0.22029482373918088
Fold 3 IBS: 0.20455777196221334
Fold 4 IBS: 0.2254607993521297
Fold 5 IBS: 0.217315286840508
[I 2024-04-19 05:31:20,854] Trial 18 finished with value: 0.21631153568487868 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.21087640167017066
Fold 2 IBS: 0.21683324507869903
Fold 3 IBS: 0.2024740618052882
Fold 4 IBS: 0.22143460442969243
Fold 5 IBS: 0.21624379136010355
[I 2024-04-19 05:31:36,010] Trial 19 finished with value: 0.2135724208687908 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.2110023974277348
Fold 2 IBS: 0.22005248568935004
Fold 3 IBS: 0.2041108243388403
Fold 4 IBS: 0.22389889481995562
Fold 5 IBS: 0.21593871450552427
[I 2024-04-19 05:31:36,931] Trial 20 finished with value: 0.215000663356281 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.20758351571513003
Fold 2 IBS: 0.21254074487246657
Fold 3 IBS: 0.20094660201532688
Fold 4 IBS: 0.2183446914986538
Fold 5 IBS: 0.21458859991338916
[I 2024-04-19 05:31:54,205] Trial 21 finished with value: 0.2108008308029933 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.2066938712685817
Fold 2 IBS: 0.21030124935406655
Fold 3 IBS: 0.19938245744554872
Fold 4 IBS: 0.2170917064144435
Fold 5 IBS: 0.21346591373080134
[I 2024-04-19 05:32:10,806] Trial 22 finished with value: 0.20938703964268837 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.2112490874379704
Fold 2 IBS: 0.21644106046567402
Fold 3 IBS: 0.2028980651341261
Fold 4 IBS: 0.22157930660819017
Fold 5 IBS: 0.21599036340922748
[I 2024-04-19 05:32:27,411] Trial 23 finished with value: 0.21363157661103763 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4354485106193713, 'min_weight_fraction_leaf': 0.02923560760429222}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.21107241936869328
Fold 2 IBS: 0.2169973608851237
Fold 3 IBS: 0.20272904949032244
Fold 4 IBS: 0.2222666916817044
Fold 5 IBS: 0.2162175082370245
[I 2024-04-19 05:32:44,127] Trial 24 finished with value: 0.21385660593257366 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.34950482438457253, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.2052490687089369
Fold 2 IBS: 0.2129630572262836
Fold 3 IBS: 0.20012047793785964
Fold 4 IBS: 0.21941084024769567
Fold 5 IBS: 0.21408218146285218
[I 2024-04-19 05:32:59,562] Trial 25 finished with value: 0.21036512511672562 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6363223369371479, 'min_weight_fraction_leaf': 0.004408180869012377}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.2104867950590723
Fold 2 IBS: 0.21622069747801462
Fold 3 IBS: 0.20212858448258228
Fold 4 IBS: 0.2213229312090521
Fold 5 IBS: 0.21540401617705537
[I 2024-04-19 05:33:17,508] Trial 26 finished with value: 0.21311260488115535 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.650716722386954, 'min_weight_fraction_leaf': 0.06237722339727473}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.2126546429242057
Fold 2 IBS: 0.2200059341064932
Fold 3 IBS: 0.2040991517112951
Fold 4 IBS: 0.2237611989420676
Fold 5 IBS: 0.21751291639535705
[I 2024-04-19 05:33:28,790] Trial 27 finished with value: 0.21560676881588373 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.21283219185375624
Fold 2 IBS: 0.22030330003957335
Fold 3 IBS: 0.20413910686138773
Fold 4 IBS: 0.22365524485897761
Fold 5 IBS: 0.2176096795614041
[I 2024-04-19 05:33:46,308] Trial 28 finished with value: 0.2157079046350198 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.20781851868769508.
Fold 1 IBS: 0.20717341096428746
Fold 2 IBS: 0.2135114284838961
Fold 3 IBS: 0.20084339913632895
Fold 4 IBS: 0.2184882116934449
Fold 5 IBS: 0.21398812981315804
[I 2024-04-19 05:33:59,641] Trial 29 finished with value: 0.2108009160182231 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8297742842413881, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 12 with value: 0.20781851868769508.

Fold 1 IBS: 0.20644252348164513
Fold 2 IBS: 0.2019403019456175
Fold 3 IBS: 0.19518482770678974
Fold 4 IBS: 0.21117332821307674
Fold 5 IBS: 0.21254756150696177
[I 2024-04-19 05:34:14,875] Trial 30 finished with value: 0.2054577085708182 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6204655821432031, 'min_weight_fraction_leaf': 0.08941926090357169}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20219437207626473
Fold 2 IBS: 0.20791758297727755
Fold 3 IBS: 0.19810920318501377
Fold 4 IBS: 0.21211014051688712
Fold 5 IBS: 0.21592391251551635
[I 2024-04-19 05:34:29,392] Trial 31 finished with value: 0.20725104225419191 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6210819054689052, 'min_weight_fraction_leaf': 0.03048718971899994}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20670033019794845
Fold 2 IBS: 0.2056331619171435
Fold 3 IBS: 0.19813634948915615
Fold 4 IBS: 0.21340999003465985
Fold 5 IBS: 0.21431274129288203
[I 2024-04-19 05:34:46,298] Trial 32 finished with value: 0.20763851458635801 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5079102747784384, 'min_weight_fraction_leaf': 0.08937056854739861}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.21390612229222838
Fold 2 IBS: 0.22132288047022172
Fold 3 IBS: 0.20489917610236724
Fold 4 IBS: 0.22453230602806556
Fold 5 IBS: 0.21834500588409775
[I 2024-04-19 05:35:03,066] Trial 33 finished with value: 0.21660109815539613 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 477, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3962727024860553, 'min_weight_fraction_leaf': 0.09751612000578311}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.2083203599567022
Fold 2 IBS: 0.20664178523882343
Fold 3 IBS: 0.1978243320523925
Fold 4 IBS: 0.215585163312774
Fold 5 IBS: 0.21554430236540706
[I 2024-04-19 05:35:17,906] Trial 34 finished with value: 0.20878318858521983 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.49166977839595477, 'min_weight_fraction_leaf': 0.07866207888293249}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.2083789733912639
Fold 2 IBS: 0.21007956151588253
Fold 3 IBS: 0.19875439927683303
Fold 4 IBS: 0.21707768819458828
Fold 5 IBS: 0.21457352296839521
[I 2024-04-19 05:35:39,285] Trial 35 finished with value: 0.2097728290693926 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 460, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5325333724281855, 'min_weight_fraction_leaf': 0.12132570942744575}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20806509460450587
Fold 2 IBS: 0.21080916576658884
Fold 3 IBS: 0.200597065448584
Fold 4 IBS: 0.21877211825758047
Fold 5 IBS: 0.21279124319235382
[I 2024-04-19 05:35:47,123] Trial 36 finished with value: 0.2102069374539226 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 211, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.1758938056585586, 'min_weight_fraction_leaf': 0.05191307232995372}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.21399372057502197
Fold 2 IBS: 0.22137476763668024
Fold 3 IBS: 0.2048516295134419
Fold 4 IBS: 0.22469334957908055
Fold 5 IBS: 0.2186442758127293
[I 2024-04-19 05:36:00,262] Trial 37 finished with value: 0.21671154862339082 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6004665239248355, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.21171794535514088
Fold 2 IBS: 0.21770444892321258
Fold 3 IBS: 0.20360344793514237
Fold 4 IBS: 0.22295002623989935
Fold 5 IBS: 0.2167326674270523
[I 2024-04-19 05:36:11,162] Trial 38 finished with value: 0.2145417071760895 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5370743290843752, 'min_weight_fraction_leaf': 0.22752773294338688}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20932258909405613
Fold 2 IBS: 0.20896318534191766
Fold 3 IBS: 0.19936427239349994
Fold 4 IBS: 0.21616128725289482
Fold 5 IBS: 0.2146698854992716
[I 2024-04-19 05:36:33,909] Trial 39 finished with value: 0.20969624391632805 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 464, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7368965026873375, 'min_weight_fraction_leaf': 0.16636758415640174}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.21314010999766989
Fold 2 IBS: 0.22003027946343715
Fold 3 IBS: 0.20444690287917824
Fold 4 IBS: 0.22417386983210022
Fold 5 IBS: 0.21782185053347722
[I 2024-04-19 05:36:49,365] Trial 40 finished with value: 0.21592260254117254 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.2916032370349774, 'min_weight_fraction_leaf': 0.11514282781737215}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.2086454469036863
Fold 2 IBS: 0.20662977129107624
Fold 3 IBS: 0.19837483399257366
Fold 4 IBS: 0.21568265107460038
Fold 5 IBS: 0.21480218880149227
[I 2024-04-19 05:37:04,489] Trial 41 finished with value: 0.2088269784126858 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4702096146910742, 'min_weight_fraction_leaf': 0.08226188224156158}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20626048672109482
Fold 2 IBS: 0.20540750500043428
Fold 3 IBS: 0.19690293836222686
Fold 4 IBS: 0.21310452072277225
Fold 5 IBS: 0.21458329740793505
[I 2024-04-19 05:37:18,960] Trial 42 finished with value: 0.20725174964289267 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5156649848065784, 'min_weight_fraction_leaf': 0.07751955445846775}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.206582198796219
Fold 2 IBS: 0.20136891594851036
Fold 3 IBS: 0.19707987890771597
Fold 4 IBS: 0.21192466451142913
Fold 5 IBS: 0.21443180049424918
[I 2024-04-19 05:37:36,831] Trial 43 finished with value: 0.2062774917316247 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 467, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4046400043649434, 'min_weight_fraction_leaf': 0.027915385689975328}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.2097342576470217
Fold 2 IBS: 0.21366738320611556
Fold 3 IBS: 0.20224836898948684
Fold 4 IBS: 0.2217999305793146
Fold 5 IBS: 0.2157282297161526
[I 2024-04-19 05:37:49,976] Trial 44 finished with value: 0.21263563402761826 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4139474482693062, 'min_weight_fraction_leaf': 0.1371301994924716}. Best is trial 30 with value: 0.2054577085708182.

Fold 1 IBS: 0.2061060330108144
Fold 2 IBS: 0.20556259199015003
Fold 3 IBS: 0.19681570752543345
Fold 4 IBS: 0.21286266572595886
Fold 5 IBS: 0.21454019901532653
[I 2024-04-19 05:38:05,084] Trial 45 finished with value: 0.20717743945353667 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5228042333033645, 'min_weight_fraction_leaf': 0.05423198281417843}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20940293520492773
Fold 2 IBS: 0.20804660036517866
Fold 3 IBS: 0.1995328323215525
Fold 4 IBS: 0.2168538036825499
Fold 5 IBS: 0.21460320909795136
[I 2024-04-19 05:38:17,252] Trial 46 finished with value: 0.20968787613443202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.36540420680824204, 'min_weight_fraction_leaf': 0.02733036364821487}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20852919111382545
Fold 2 IBS: 0.2066867568141793
Fold 3 IBS: 0.19844244991254203
Fold 4 IBS: 0.2156818112332441
Fold 5 IBS: 0.21439016238240802
[I 2024-04-19 05:38:33,209] Trial 47 finished with value: 0.20874607429123979 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 418, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6065404121120935, 'min_weight_fraction_leaf': 0.06086626537379046}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.21339461788557962
Fold 2 IBS: 0.22100258548336046
Fold 3 IBS: 0.20457736804828475
Fold 4 IBS: 0.22456603303290237
Fold 5 IBS: 0.21856883352063214
[I 2024-04-19 05:38:51,132] Trial 48 finished with value: 0.21642188759415185 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 371, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5730269297696603, 'min_weight_fraction_leaf': 0.2841871251719599}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.2034724833065633
Fold 2 IBS: 0.2065654363057247
Fold 3 IBS: 0.1968784011605011
Fold 4 IBS: 0.2150596699062983
Fold 5 IBS: 0.2129114317519193
[I 2024-04-19 05:39:01,567] Trial 49 finished with value: 0.2069774844862013 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 280, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6881795920042697, 'min_weight_fraction_leaf': 0.05171744823893367}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20111231566811738
Fold 2 IBS: 0.20578943505447808
Fold 3 IBS: 0.19690615767333358
Fold 4 IBS: 0.21368615987821665
Fold 5 IBS: 0.21008515817629295
[I 2024-04-19 05:39:08,875] Trial 50 finished with value: 0.20551584529008776 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 201, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6837390941410062, 'min_weight_fraction_leaf': 0.04306305628451121}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.2008164455550439
Fold 2 IBS: 0.2070132645195135
Fold 3 IBS: 0.19655684381456312
Fold 4 IBS: 0.2126267652723355
Fold 5 IBS: 0.2108334177083541
[I 2024-04-19 05:39:17,991] Trial 51 finished with value: 0.205569347373962 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7005737149975064, 'min_weight_fraction_leaf': 0.04381240300365606}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.20431543479008302
Fold 2 IBS: 0.20661695572561137
Fold 3 IBS: 0.19688928065575495
Fold 4 IBS: 0.2154519348351984
Fold 5 IBS: 0.21216106228621573
[I 2024-04-19 05:39:26,161] Trial 52 finished with value: 0.2070869336585727 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6723988556086362, 'min_weight_fraction_leaf': 0.05022271633590118}. Best is trial 30 with value: 0.2054577085708182.
Fold 1 IBS: 0.19192690642515642
Fold 2 IBS: 0.19921512635921096
Fold 3 IBS: 0.19467555498251585
Fold 4 IBS: 0.2111437586893305
Fold 5 IBS: 0.21671248124003203
[I 2024-04-19 05:39:33,336] Trial 53 finished with value: 0.20273476553924916 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 152, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7003741693205557, 'min_weight_fraction_leaf': 0.016282568232595954}. Best is trial 53 with value: 0.20273476553924916.
Fold 1 IBS: 0.1938191942106238
Fold 2 IBS: 0.19917147919958267
Fold 3 IBS: 0.18863716848394632
Fold 4 IBS: 0.20936840017409536
Fold 5 IBS: 0.21378631458088065
[I 2024-04-19 05:39:39,077] Trial 54 finished with value: 0.20095651132982578 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 116, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7370943052680473, 'min_weight_fraction_leaf': 0.02088225190549203}. Best is trial 54 with value: 0.20095651132982578.
Fold 1 IBS: 0.19538416841256298
Fold 2 IBS: 0.20245520093801866
Fold 3 IBS: 0.18611807887968762
Fold 4 IBS: 0.21124711871977872
Fold 5 IBS: 0.21400131144701237
[I 2024-04-19 05:39:44,641] Trial 55 finished with value: 0.20184117567941207 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 126, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7550756187305346, 'min_weight_fraction_leaf': 0.018492843192326382}. Best is trial 54 with value: 0.20095651132982578.
Fold 1 IBS: 0.19304954992475742
Fold 2 IBS: 0.19812481998746778
Fold 3 IBS: 0.18670305110218668
Fold 4 IBS: 0.21234921404869633
Fold 5 IBS: 0.21730198977445142
[I 2024-04-19 05:39:49,255] Trial 56 finished with value: 0.20150572496751193 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 109, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8077688640377045, 'min_weight_fraction_leaf': 0.020924807899981048}. Best is trial 54 with value: 0.20095651132982578.
Fold 1 IBS: 0.1971548598271666
Fold 2 IBS: 0.20118251562244044
Fold 3 IBS: 0.18927258639649022
Fold 4 IBS: 0.21487249465140698
Fold 5 IBS: 0.21742350528319923
[I 2024-04-19 05:39:55,285] Trial 57 finished with value: 0.2039811923561407 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 117, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8253885248306065, 'min_weight_fraction_leaf': 0.012331205204555369}. Best is trial 54 with value: 0.20095651132982578.
Fold 1 IBS: 0.19666841233102025
Fold 2 IBS: 0.19814931725591095
Fold 3 IBS: 0.1883440198867122
Fold 4 IBS: 0.21427765449001276
Fold 5 IBS: 0.21791244885702585
[I 2024-04-19 05:40:00,274] Trial 58 finished with value: 0.2030703705641364 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 114, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8199471954526103, 'min_weight_fraction_leaf': 0.017310807427010466}. Best is trial 54 with value: 0.20095651132982578.
Fold 1 IBS: 0.19593694891176733
Fold 2 IBS: 0.1969573103910906
Fold 3 IBS: 0.18654565533335357
Fold 4 IBS: 0.21295126546717394
Fold 5 IBS: 0.21402084273841346
[I 2024-04-19 05:40:06,007] Trial 59 finished with value: 0.20128240456835975 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8186634012542725, 'min_weight_fraction_leaf': 0.01790516294886912}. Best is trial 54 with value: 0.20095651132982578.

Fold 1 IBS: 0.191170709407248
Fold 2 IBS: 0.20034725956824517
Fold 3 IBS: 0.1860917463084432
Fold 4 IBS: 0.2126886619299396
Fold 5 IBS: 0.2135244566742881
[I 2024-04-19 05:40:10,890] Trial 60 finished with value: 0.20076456677763282 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 86, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9280982393500873, 'min_weight_fraction_leaf': 0.01669807793304111}. Best is trial 60 with value: 0.20076456677763282.
Fold 1 IBS: 0.1926004831958468
Fold 2 IBS: 0.1987117406768836
Fold 3 IBS: 0.1856472650351245
Fold 4 IBS: 0.2125202423023172
Fold 5 IBS: 0.21157082059492746
[I 2024-04-19 05:40:15,461] Trial 61 finished with value: 0.20021011036101988 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 89, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9355045617327991, 'min_weight_fraction_leaf': 0.017018073060781347}. Best is trial 61 with value: 0.20021011036101988.
Fold 1 IBS: 0.19007149029568574
Fold 2 IBS: 0.19911834035151552
Fold 3 IBS: 0.1863160697959859
Fold 4 IBS: 0.2047553958356642
Fold 5 IBS: 0.21899436007168507
[I 2024-04-19 05:40:20,584] Trial 62 finished with value: 0.19985113127010729 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 80, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9331920290611762, 'min_weight_fraction_leaf': 0.002905153919869702}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19069431071133724
Fold 2 IBS: 0.1998207986869149
Fold 3 IBS: 0.18609485517667618
Fold 4 IBS: 0.20506843122896526
Fold 5 IBS: 0.21796243251831054
[I 2024-04-19 05:40:24,466] Trial 63 finished with value: 0.1999281656644408 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 84, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9363405828408166, 'min_weight_fraction_leaf': 8.734124602250912e-05}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.1947293803733131
Fold 2 IBS: 0.20328639824365494
Fold 3 IBS: 0.18979698955905314
Fold 4 IBS: 0.21214504926474484
Fold 5 IBS: 0.20800418974864224
[I 2024-04-19 05:40:28,546] Trial 64 finished with value: 0.20159240143788165 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 72, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9375568155306879, 'min_weight_fraction_leaf': 0.0014859888312628263}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.21315910664347512
Fold 2 IBS: 0.21969469409411166
Fold 3 IBS: 0.20376112679513364
Fold 4 IBS: 0.22429739223330475
Fold 5 IBS: 0.2181228018249157
[I 2024-04-19 05:40:32,936] Trial 65 finished with value: 0.21580702431818816 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 77, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9303700901639224, 'min_weight_fraction_leaf': 0.40019809578387655}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.20329415442542592
Fold 2 IBS: 0.21225378130180078
Fold 3 IBS: 0.20149415111206415
Fold 4 IBS: 0.21576550895921276
Fold 5 IBS: 0.21587842266224064
[I 2024-04-19 05:40:34,419] Trial 66 finished with value: 0.20973720369214885 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 16, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8589895105273044, 'min_weight_fraction_leaf': 0.06382685481760672}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19111911859651334
Fold 2 IBS: 0.19930988026185695
Fold 3 IBS: 0.1904001417688579
Fold 4 IBS: 0.2080025691665853
Fold 5 IBS: 0.2230205276606804
[I 2024-04-19 05:40:38,718] Trial 67 finished with value: 0.20237044749089877 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 86, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9165230228224167, 'min_weight_fraction_leaf': 0.0005665606291913104}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.21314809040322122
Fold 2 IBS: 0.21756849579761786
Fold 3 IBS: 0.20278352231375815
Fold 4 IBS: 0.22247368508960758
Fold 5 IBS: 0.21674175648383354
[I 2024-04-19 05:40:41,798] Trial 68 finished with value: 0.21454311001760767 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 47, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9443781818781137, 'min_weight_fraction_leaf': 0.03417236616792663}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.20181797983145008
Fold 2 IBS: 0.2094475474787719
Fold 3 IBS: 0.19308630452304867
Fold 4 IBS: 0.2190502058868913
Fold 5 IBS: 0.21317815937742124
[I 2024-04-19 05:40:44,952] Trial 69 finished with value: 0.20731603941951665 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 48, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9635773294206186, 'min_weight_fraction_leaf': 0.07100230351231371}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19655544374558437
Fold 2 IBS: 0.20409617193467752
Fold 3 IBS: 0.1923047113118594
Fold 4 IBS: 0.21093213707870287
Fold 5 IBS: 0.21201530166381505
[I 2024-04-19 05:40:52,476] Trial 70 finished with value: 0.2031807531469278 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9003579634085844, 'min_weight_fraction_leaf': 0.016546897678516356}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.1914617805107785
Fold 2 IBS: 0.1961868365886253
Fold 3 IBS: 0.183875328106228
Fold 4 IBS: 0.21226324390338666
Fold 5 IBS: 0.21722967306515992
[I 2024-04-19 05:40:58,029] Trial 71 finished with value: 0.20020337243483569 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 89, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.854539698086163, 'min_weight_fraction_leaf': 0.005600695234638349}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19447864150607913
Fold 2 IBS: 0.1978121391968079
Fold 3 IBS: 0.18730293623299535
Fold 4 IBS: 0.21399463769677282
Fold 5 IBS: 0.20999071390439175
[I 2024-04-19 05:41:03,610] Trial 72 finished with value: 0.20071581370740937 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 97, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.855180300464991, 'min_weight_fraction_leaf': 0.024825828440887467}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19916627206304877
Fold 2 IBS: 0.20242880605240063
Fold 3 IBS: 0.19360996480752304
Fold 4 IBS: 0.2139381873174987
Fold 5 IBS: 0.21151103490151538
[I 2024-04-19 05:41:08,369] Trial 73 finished with value: 0.2041308530283973 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 96, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8593392376233806, 'min_weight_fraction_leaf': 0.040844912028458996}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.2010332749555111
Fold 2 IBS: 0.21350845223676954
Fold 3 IBS: 0.19849693738154464
Fold 4 IBS: 0.21839389837990472
Fold 5 IBS: 0.2145768640804847
[I 2024-04-19 05:41:11,635] Trial 74 finished with value: 0.20920188540684298 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 58, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9994013705984273, 'min_weight_fraction_leaf': 0.004237094152818506}. Best is trial 62 with value: 0.19985113127010729.

Fold 1 IBS: 0.2015619084730176
Fold 2 IBS: 0.20340538458456545
Fold 3 IBS: 0.1947998336835993
Fold 4 IBS: 0.21288774116744222
Fold 5 IBS: 0.2122749350143774
[I 2024-04-19 05:41:16,390] Trial 75 finished with value: 0.20498596058460042 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 95, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.855914969192737, 'min_weight_fraction_leaf': 0.03770339568279605}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19197793012924233
Fold 2 IBS: 0.21261684937986214
Fold 3 IBS: 0.19593075143531394
Fold 4 IBS: 0.21235581098598563
Fold 5 IBS: 0.21671379378403846
[I 2024-04-19 05:41:18,494] Trial 76 finished with value: 0.2059190271428885 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 28, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7851402982521988, 'min_weight_fraction_leaf': 0.023840982208012642}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19250141492359218
Fold 2 IBS: 0.1991443522732381
Fold 3 IBS: 0.18613489784901185
Fold 4 IBS: 0.21002303244704681
Fold 5 IBS: 0.2224196812682715
[I 2024-04-19 05:41:22,633] Trial 77 finished with value: 0.20204467575223212 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 71, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8982358424922625, 'min_weight_fraction_leaf': 0.0015247574258462314}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.20105264667541106
Fold 2 IBS: 0.20649348778726948
Fold 3 IBS: 0.1958335852226894
Fold 4 IBS: 0.2150548630901936
Fold 5 IBS: 0.2110136282220498
[I 2024-04-19 05:41:29,603] Trial 78 finished with value: 0.20588964219952266 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 135, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9644797122864728, 'min_weight_fraction_leaf': 0.05836192646609549}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.20434519015548355
Fold 2 IBS: 0.2094365379590598
Fold 3 IBS: 0.19868881536167562
Fold 4 IBS: 0.21585315397054655
Fold 5 IBS: 0.21278589279627216
[I 2024-04-19 05:41:37,276] Trial 79 finished with value: 0.20822191804860757 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 162, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8426087583955321, 'min_weight_fraction_leaf': 0.0698161140128812}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19116775522716162
Fold 2 IBS: 0.20448047254503138
Fold 3 IBS: 0.1893376940184613
Fold 4 IBS: 0.21720562760702133
Fold 5 IBS: 0.2091233885934089
[I 2024-04-19 05:41:39,653] Trial 80 finished with value: 0.20226298759821693 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 33, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8782565427714625, 'min_weight_fraction_leaf': 0.030714483753547545}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19685146503564424
Fold 2 IBS: 0.20076347202657177
Fold 3 IBS: 0.18525464397244215
Fold 4 IBS: 0.2137045617713918
Fold 5 IBS: 0.21536572621215758
[I 2024-04-19 05:41:44,831] Trial 81 finished with value: 0.2023879738036415 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 102, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7689926378557995, 'min_weight_fraction_leaf': 0.020111081200512432}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19492478201074495
Fold 2 IBS: 0.1975118712774793
Fold 3 IBS: 0.18818516693535023
Fold 4 IBS: 0.2144583316384904
Fold 5 IBS: 0.2210113478363593
[I 2024-04-19 05:41:49,232] Trial 82 finished with value: 0.20321829993968482 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 81, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8048192735810434, 'min_weight_fraction_leaf': 0.013073294164916788}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19879383952635177
Fold 2 IBS: 0.20318147154513583
Fold 3 IBS: 0.19263511845692335
Fold 4 IBS: 0.21290317672562348
Fold 5 IBS: 0.211389765144062
[I 2024-04-19 05:41:52,839] Trial 83 finished with value: 0.20378067427961927 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 66, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9110661146803025, 'min_weight_fraction_leaf': 0.04365429248199171}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.20118429039049768
Fold 2 IBS: 0.20433950514384042
Fold 3 IBS: 0.19295926958322338
Fold 4 IBS: 0.21064930418238206
Fold 5 IBS: 0.2154665563281902
[I 2024-04-19 05:41:58,700] Trial 84 finished with value: 0.20491978512562672 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 114, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7993733531235074, 'min_weight_fraction_leaf': 0.028630376022891497}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.1922553531730743
Fold 2 IBS: 0.20061258764049236
Fold 3 IBS: 0.18986459759812524
Fold 4 IBS: 0.2089661143492623
Fold 5 IBS: 0.21162383775866864
[I 2024-04-19 05:42:03,442] Trial 85 finished with value: 0.20066449810392456 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 87, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9495203682561782, 'min_weight_fraction_leaf': 0.01678543213640385}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.2131916417718118
Fold 2 IBS: 0.21984634659359834
Fold 3 IBS: 0.20398060712823918
Fold 4 IBS: 0.2239710188825635
Fold 5 IBS: 0.21869977793352935
[I 2024-04-19 05:42:07,721] Trial 86 finished with value: 0.21593787846194842 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 87, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9605495508521364, 'min_weight_fraction_leaf': 0.3398946099594511}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.1927861900057189
Fold 2 IBS: 0.20090103952052565
Fold 3 IBS: 0.1893269966754948
Fold 4 IBS: 0.2100386926886117
Fold 5 IBS: 0.20871885341768173
[I 2024-04-19 05:42:11,168] Trial 87 finished with value: 0.20035435446160657 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 57, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9247196630211004, 'min_weight_fraction_leaf': 0.01329240560421817}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.2081241068390017
Fold 2 IBS: 0.21223069824912943
Fold 3 IBS: 0.20174597522065654
Fold 4 IBS: 0.22018104300664673
Fold 5 IBS: 0.21634505777043736
[I 2024-04-19 05:42:14,833] Trial 88 finished with value: 0.21172537621717438 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 57, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8840760272053876, 'min_weight_fraction_leaf': 0.10570416936432725}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.20584376241175356
Fold 2 IBS: 0.21693742751213452
Fold 3 IBS: 0.19898047305773947
Fold 4 IBS: 0.22198648827398207
Fold 5 IBS: 0.2144422991677424
[I 2024-04-19 05:42:17,197] Trial 89 finished with value: 0.21163809008467044 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 36, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9290852121987835, 'min_weight_fraction_leaf': 0.05032128004549887}. Best is trial 62 with value: 0.19985113127010729.

Fold 1 IBS: 0.18917643633846162
Fold 2 IBS: 0.21015262595618928
Fold 3 IBS: 0.1935077870422502
Fold 4 IBS: 0.2164703849597155
Fold 5 IBS: 0.2081976082003696
[I 2024-04-19 05:42:18,976] Trial 90 finished with value: 0.20350096849939722 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 21, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9990067443357235, 'min_weight_fraction_leaf': 0.009830617135283846}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.19666080291709018
Fold 2 IBS: 0.2052297665080179
Fold 3 IBS: 0.19192574041702756
Fold 4 IBS: 0.21136412922820036
Fold 5 IBS: 0.21257426066349058
[I 2024-04-19 05:42:25,547] Trial 91 finished with value: 0.2035509399467653 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9573887366097225, 'min_weight_fraction_leaf': 0.03609884154193235}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.18934142069739274
Fold 2 IBS: 0.1992338848432967
Fold 3 IBS: 0.18667536407881252
Fold 4 IBS: 0.21001773296039342
Fold 5 IBS: 0.21432093278421116
[I 2024-04-19 05:42:30,269] Trial 92 finished with value: 0.19991786707282128 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 92, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9146004448900085, 'min_weight_fraction_leaf': 0.009321280734491271}. Best is trial 62 with value: 0.19985113127010729.
Fold 1 IBS: 0.18996356136561013
Fold 2 IBS: 0.19521174089948307
Fold 3 IBS: 0.18848212985379573
Fold 4 IBS: 0.20735957503907473
Fold 5 IBS: 0.21339483203526474
[I 2024-04-19 05:42:40,021] Trial 93 finished with value: 0.1988823678386457 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 232, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9167048247496662, 'min_weight_fraction_leaf': 0.007458772586464836}. Best is trial 93 with value: 0.1988823678386457.
Fold 1 IBS: 0.19592256304880604
Fold 2 IBS: 0.20469914430409905
Fold 3 IBS: 0.19165866605246912
Fold 4 IBS: 0.21118365445572523
Fold 5 IBS: 0.21131079470928033
[I 2024-04-19 05:42:47,424] Trial 94 finished with value: 0.20295496451407594 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 148, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9145290265370722, 'min_weight_fraction_leaf': 0.00999378796441661}. Best is trial 93 with value: 0.1988823678386457.
Fold 1 IBS: 0.18897260928017717
Fold 2 IBS: 0.1962675077447216
Fold 3 IBS: 0.18680914133292484
Fold 4 IBS: 0.20738764269973245
Fold 5 IBS: 0.21091884902077607
[I 2024-04-19 05:42:57,498] Trial 95 finished with value: 0.19807115001566641 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9710275551272143, 'min_weight_fraction_leaf': 0.0015644507667663538}. Best is trial 95 with value: 0.19807115001566641.
Fold 1 IBS: 0.18991873743355875
Fold 2 IBS: 0.19582263801467606
Fold 3 IBS: 0.18717659153183933
Fold 4 IBS: 0.20723093423802025
Fold 5 IBS: 0.21020072782388347
[I 2024-04-19 05:43:09,014] Trial 96 finished with value: 0.19806992580839558 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 234, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9523317599123883, 'min_weight_fraction_leaf': 0.0028784190622166937}. Best is trial 96 with value: 0.19806992580839558.
Fold 1 IBS: 0.19613102018482598
Fold 2 IBS: 0.2045518206230927
Fold 3 IBS: 0.1945079620669418
Fold 4 IBS: 0.21166745371619022
Fold 5 IBS: 0.21095467618115574
[I 2024-04-19 05:43:20,923] Trial 97 finished with value: 0.20356258655444132 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 235, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9691019343870649, 'min_weight_fraction_leaf': 0.002452207328542587}. Best is trial 96 with value: 0.19806992580839558.
Fold 1 IBS: 0.19512144941430312
Fold 2 IBS: 0.20392238142786423
Fold 3 IBS: 0.1935395514055763
Fold 4 IBS: 0.20931434280289715
Fold 5 IBS: 0.21107430680465977
[I 2024-04-19 05:43:32,971] Trial 98 finished with value: 0.20259440637106013 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 241, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9797660432580821, 'min_weight_fraction_leaf': 0.04393739206501838}. Best is trial 96 with value: 0.19806992580839558.
Fold 1 IBS: 0.1947079034963974
Fold 2 IBS: 0.2043646807890731
Fold 3 IBS: 0.19143191489660724
Fold 4 IBS: 0.20857673965186163
Fold 5 IBS: 0.2118237246261193
[I 2024-04-19 05:43:44,479] Trial 99 finished with value: 0.20218099269201173 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 230, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9445115355496312, 'min_weight_fraction_leaf': 0.008475572565800546}. Best is trial 96 with value: 0.19806992580839558.


* Best trial for IBS:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.19806992580839558], datetime_start=datetime.datetime(2024, 4, 19, 5, 42, 57, 505986), datetime_complete=datetime.datetime(2024, 4, 19, 5, 43, 9, 13337), params={'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 234, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9523317599123883, 'min_weight_fraction_leaf': 0.0028784190622166937}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=96, value=None)


* Best Score for IBS:
 0.19806992580839558

In [99]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [100]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.808
train_ibs:  0.198

#### Test

In [101]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [102]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=20, max_features=None, max_leaf_nodes=15,
                   max_samples=0.6196177319145886, min_samples_leaf=2,
                   min_samples_split=9,
                   min_weight_fraction_leaf=0.010458229178985291,
                   n_estimators=370, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.614

ExtraSurvivalTrees(max_depth=19, max_features='auto', max_leaf_nodes=20,
                   max_samples=0.9523317599123883, min_samples_leaf=2,
                   min_samples_split=8,
                   min_weight_fraction_leaf=0.0028784190622166937,
                   n_estimators=234, oob_score=True, random_state=123)

IBS: 0.211

In [103]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [104]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 05:43:48,535] A new study created in memory with name: no-name-1fbe30f5-0754-4ea9-96f1-fe50592806ff

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:45:03,960] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:45:47,026] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:46:27,058] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:47:30,454] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:47:57,703] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:48:03,491] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:49:05,494] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:49:23,752] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:49:25,941] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6348039215686274
Fold 4 C-index: 0.6434599156118144
Fold 5 C-index: 0.6737089201877934
[I 2024-04-19 05:52:19,634] Trial 9 finished with value: 0.6608490969281925 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:56:33,348] Trial 10 finished with value: 0.5 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 05:59:25,903] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.8081282674845877, 'learning_rate': 0.03957576815132133, 'dropout_rate': 0.3592207054036807, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 9.74116027708086, 'min_weight_fraction_leaf': 0.365889927692422, 'max_features': 'log2', 'min_impurity_decrease': 1.459170836380829e-06, 'validation_fraction': 0.7986785049611014, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:02:11,885] Trial 12 finished with value: 0.5 and parameters: {'subsample': 0.3678235114093892, 'learning_rate': 0.04567946973839636, 'dropout_rate': 0.25727844951644346, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.3231056999503768, 'min_weight_fraction_leaf': 0.19696526950140963, 'max_features': 'auto', 'min_impurity_decrease': 1.6810148621356602e-06, 'validation_fraction': 0.8490366656238622, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:02:30,224] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.7784830438231676, 'learning_rate': 0.02439641670004065, 'dropout_rate': 0.4821375662037144, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 6.245821408640139, 'min_weight_fraction_leaf': 0.3469021849356369, 'max_features': 1, 'min_impurity_decrease': 0.002901900339595834, 'validation_fraction': 0.40492470595401014, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:04:58,521] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.5522283925781899, 'learning_rate': 0.010913227078192221, 'dropout_rate': 0.275468298707492, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.2209251544817152, 'max_features': 'log2', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.7267940764758692, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:07:47,987] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8321814107294574, 'learning_rate': 0.03462515781182537, 'dropout_rate': 0.10188162797857298, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 5.585208670000242, 'min_weight_fraction_leaf': 0.3203472576334258, 'max_features': 0.1, 'min_impurity_decrease': 9.84228208509291e-05, 'validation_fraction': 0.9508448160253733, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:08:00,671] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.41637694759398924, 'learning_rate': 0.05102954371215744, 'dropout_rate': 0.4800989647660596, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 9.356569787888832, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': None, 'min_impurity_decrease': 6.315552530348283e-07, 'validation_fraction': 0.6329472651499938, 'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:12:07,166] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.18427032297888507, 'learning_rate': 0.016160179473353013, 'dropout_rate': 0.2643467397617198, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 1.767647956851031, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 'auto', 'min_impurity_decrease': 9.756988906280483e-06, 'validation_fraction': 0.460466512261803, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:12:49,627] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.29960178961969325, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.480521228562659, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 6.571359927175668, 'min_weight_fraction_leaf': 0.3081685769690769, 'max_features': 'auto', 'min_impurity_decrease': 0.00017103826195115595, 'validation_fraction': 0.8334165513948124, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:13:32,158] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.6107103985877803, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.8022840901094805, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 4.726491220462886, 'min_weight_fraction_leaf': 0.23723421649302917, 'max_features': None, 'min_impurity_decrease': 0.005573123702146452, 'validation_fraction': 0.733318779116827, 'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:16:10,258] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.7486596812728094, 'learning_rate': 0.030015766309112166, 'dropout_rate': 0.41862843505834413, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 8.442374914253744, 'min_weight_fraction_leaf': 0.43152288390795446, 'max_features': 0.1, 'min_impurity_decrease': 5.093079199752527e-07, 'validation_fraction': 0.485777565058473, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 17}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:16:48,926] Trial 21 finished with value: 0.5 and parameters: {'subsample': 0.6645352255107654, 'learning_rate': 0.09848488597888547, 'dropout_rate': 0.7687435120123771, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.841872183700346, 'min_weight_fraction_leaf': 0.12726799092659097, 'max_features': 'sqrt', 'min_impurity_decrease': 4.129428860721829e-05, 'validation_fraction': 0.26781949045355996, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:17:34,358] Trial 22 finished with value: 0.5 and parameters: {'subsample': 0.473874743610687, 'learning_rate': 0.08064716128589619, 'dropout_rate': 0.7441459115178709, 'n_estimators': 319, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7836160564934809, 'min_weight_fraction_leaf': 0.08573145040193865, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6571343171562185e-05, 'validation_fraction': 0.3666637457155964, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:17:50,809] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9031806207514874, 'learning_rate': 0.05231237416288583, 'dropout_rate': 0.9933061120594999, 'n_estimators': 376, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9734842724745505, 'min_weight_fraction_leaf': 0.18816784942881926, 'max_features': 'sqrt', 'min_impurity_decrease': 5.564325269330583e-05, 'validation_fraction': 0.22191224417069177, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:18:13,019] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.6032411000441751, 'learning_rate': 0.08510490014384028, 'dropout_rate': 0.8499447592488185, 'n_estimators': 264, 'criterion': 'friedman_mse', 'ccp_alpha': 2.564923335664723, 'min_weight_fraction_leaf': 0.2675376131769848, 'max_features': 'sqrt', 'min_impurity_decrease': 4.632626838690667e-06, 'validation_fraction': 0.5456395158226394, 'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:18:41,442] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7215349051479215, 'learning_rate': 0.04238950086330006, 'dropout_rate': 0.3050189841876249, 'n_estimators': 160, 'criterion': 'friedman_mse', 'ccp_alpha': 4.1944004294560635, 'min_weight_fraction_leaf': 0.31435920289715347, 'max_features': 'log2', 'min_impurity_decrease': 0.00032844478717469067, 'validation_fraction': 0.005916255331971709, 'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:20:09,655] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.8806073308147355, 'learning_rate': 0.022376976197093057, 'dropout_rate': 0.6881130985931054, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 2.7801390404743485, 'min_weight_fraction_leaf': 0.14826348238129222, 'max_features': 1, 'min_impurity_decrease': 3.2746646321179855e-06, 'validation_fraction': 0.654336976255422, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:22:19,784] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.6416570269538786, 'learning_rate': 0.08875752985571464, 'dropout_rate': 0.19627515205758927, 'n_estimators': 344, 'criterion': 'friedman_mse', 'ccp_alpha': 5.931957554140308, 'min_weight_fraction_leaf': 0.08440730068390215, 'max_features': 'sqrt', 'min_impurity_decrease': 4.19885324392308e-07, 'validation_fraction': 0.37029719014273693, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:22:57,849] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.497258076729488, 'learning_rate': 0.008892113552158437, 'dropout_rate': 0.5412836692874428, 'n_estimators': 228, 'criterion': 'squared_error', 'ccp_alpha': 7.112328377904401, 'min_weight_fraction_leaf': 0.22283394976693366, 'max_features': None, 'min_impurity_decrease': 0.0009606983262736196, 'validation_fraction': 0.7883279075003073, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:24:11,900] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6818794942229185, 'learning_rate': 0.05992326510937737, 'dropout_rate': 0.4279996334051157, 'n_estimators': 293, 'criterion': 'friedman_mse', 'ccp_alpha': 4.98367064023063, 'min_weight_fraction_leaf': 0.48609051334926223, 'max_features': 'auto', 'min_impurity_decrease': 2.7205182948043777e-05, 'validation_fraction': 0.8992753588751915, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:24:24,611] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.8339878628842677, 'learning_rate': 0.01736979095038719, 'dropout_rate': 0.9018920438096094, 'n_estimators': 205, 'criterion': 'friedman_mse', 'ccp_alpha': 8.526748409672111, 'min_weight_fraction_leaf': 0.061083375695457354, 'max_features': None, 'min_impurity_decrease': 4.064893428944893e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:25:00,235] Trial 31 finished with value: 0.5 and parameters: {'subsample': 0.7067650123833389, 'learning_rate': 0.010128712060556065, 'dropout_rate': 0.34778224400860064, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 5.487014966748448, 'min_weight_fraction_leaf': 0.39961580373240596, 'max_features': None, 'min_impurity_decrease': 1.0411120773977246e-05, 'validation_fraction': 0.308558812747987, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 14}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:25:27,756] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.6110503802842687, 'learning_rate': 0.027415486687298214, 'dropout_rate': 0.4231091261598614, 'n_estimators': 165, 'criterion': 'friedman_mse', 'ccp_alpha': 4.725664402361732, 'min_weight_fraction_leaf': 0.4578429432624628, 'max_features': None, 'min_impurity_decrease': 1.102268047930114e-07, 'validation_fraction': 0.6040860894665333, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:27:37,026] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.7527918357143221, 'learning_rate': 0.013800242549203569, 'dropout_rate': 0.21901675178661018, 'n_estimators': 343, 'criterion': 'friedman_mse', 'ccp_alpha': 4.336519464922468, 'min_weight_fraction_leaf': 0.49560720146678894, 'max_features': None, 'min_impurity_decrease': 0.00011658144802596447, 'validation_fraction': 0.5695864375011732, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:27:46,449] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.5550888124148649, 'learning_rate': 0.07031962025287278, 'dropout_rate': 0.609287527548691, 'n_estimators': 109, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1886879010945073, 'min_weight_fraction_leaf': 0.35104146554842863, 'max_features': None, 'min_impurity_decrease': 1.4503905721935394e-05, 'validation_fraction': 0.1781977553519499, 'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:28:53,298] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6647484092740189, 'learning_rate': 0.03716684708129065, 'dropout_rate': 0.32199768169248655, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 6.677117818544033, 'min_weight_fraction_leaf': 0.0024719709736978485, 'max_features': None, 'min_impurity_decrease': 0.0003527658310127607, 'validation_fraction': 0.4303498724987228, 'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:29:31,253] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.5132724920534562, 'learning_rate': 0.05938980302581085, 'dropout_rate': 0.5454399629254872, 'n_estimators': 232, 'criterion': 'squared_error', 'ccp_alpha': 2.377008407008705, 'min_weight_fraction_leaf': 0.2560267496278468, 'max_features': 1, 'min_impurity_decrease': 1.611508696646605e-05, 'validation_fraction': 0.3206572028643662, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:30:12,652] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6133316469108037, 'learning_rate': 0.0192978405124231, 'dropout_rate': 0.3734539105394589, 'n_estimators': 209, 'criterion': 'squared_error', 'ccp_alpha': 7.974952733297302, 'min_weight_fraction_leaf': 0.2937726053633184, 'max_features': 'auto', 'min_impurity_decrease': 2.9025315549537875e-07, 'validation_fraction': 0.5215770496136994, 'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:31:39,758] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.9564449642405839, 'learning_rate': 0.0055035268399332106, 'dropout_rate': 0.15548835641172376, 'n_estimators': 278, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8766250077556945, 'min_weight_fraction_leaf': 0.37706312078571214, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0010896766592292972, 'validation_fraction': 0.6758418959443157, 'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:33:20,065] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.43972351129566345, 'learning_rate': 0.06600221935919671, 'dropout_rate': 0.2199359809739201, 'n_estimators': 311, 'criterion': 'squared_error', 'ccp_alpha': 3.728373112411028, 'min_weight_fraction_leaf': 0.4354213118859305, 'max_features': 0.1, 'min_impurity_decrease': 6.240626814101929e-05, 'validation_fraction': 0.15340933394972178, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:33:55,946] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.7968754596525256, 'learning_rate': 0.033357301502402015, 'dropout_rate': 0.6498448126467091, 'n_estimators': 250, 'criterion': 'friedman_mse', 'ccp_alpha': 5.281445352241334, 'min_weight_fraction_leaf': 0.3381586418579516, 'max_features': 'auto', 'min_impurity_decrease': 6.661303017365454e-06, 'validation_fraction': 0.07579960633039973, 'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:33:56,610] Trial 41 finished with value: 0.5 and parameters: {'subsample': 0.7127655796244947, 'learning_rate': 0.07428645893623183, 'dropout_rate': 0.70485161120415, 'n_estimators': 1, 'criterion': 'friedman_mse', 'ccp_alpha': 9.861114809899185, 'min_weight_fraction_leaf': 0.12458170809215217, 'max_features': None, 'min_impurity_decrease': 1.662245720310093e-07, 'validation_fraction': 0.7267564157130575, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 18}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:35:28,179] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.7560260044979399, 'learning_rate': 0.025751385187231305, 'dropout_rate': 0.6346183377825835, 'n_estimators': 408, 'criterion': 'friedman_mse', 'ccp_alpha': 7.475073875167142, 'min_weight_fraction_leaf': 0.04609024675850246, 'max_features': None, 'min_impurity_decrease': 9.328966670608897e-07, 'validation_fraction': 0.6034991541241608, 'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:36:13,366] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5800218768698703, 'learning_rate': 0.060657130303905384, 'dropout_rate': 0.8315823321401684, 'n_estimators': 373, 'criterion': 'friedman_mse', 'ccp_alpha': 9.052626765771977, 'min_weight_fraction_leaf': 0.11245484624078364, 'max_features': 'log2', 'min_impurity_decrease': 2.7032867367744606e-06, 'validation_fraction': 0.7627780727404674, 'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 14}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:38:00,914] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.650007501014019, 'learning_rate': 0.042999799171261954, 'dropout_rate': 0.6859431566383477, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 9.255798461541156, 'min_weight_fraction_leaf': 0.19508406829791197, 'max_features': None, 'min_impurity_decrease': 1.803850310358625e-07, 'validation_fraction': 0.4932258209212708, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 16}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:39:13,536] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8267526608162997, 'learning_rate': 0.013494375221622822, 'dropout_rate': 0.562451794592445, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 7.951274135957477, 'min_weight_fraction_leaf': 0.15414208319180517, 'max_features': None, 'min_impurity_decrease': 0.02254931450703544, 'validation_fraction': 0.6904472538348748, 'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:42:04,593] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.6929864855836454, 'learning_rate': 0.007563282406611266, 'dropout_rate': 0.29094189233267964, 'n_estimators': 357, 'criterion': 'squared_error', 'ccp_alpha': 6.2062474416489986, 'min_weight_fraction_leaf': 0.2757251898825701, 'max_features': 'auto', 'min_impurity_decrease': 0.00020148550328401993, 'validation_fraction': 0.5782346210702172, 'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:43:44,919] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5253005441150441, 'learning_rate': 0.04837065116276148, 'dropout_rate': 0.40371810493552335, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 0.424583130603446, 'min_weight_fraction_leaf': 0.24358906077310583, 'max_features': 1, 'min_impurity_decrease': 1.7170256007439695e-06, 'validation_fraction': 0.423183184019399, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:47:44,639] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.8553523642443996, 'learning_rate': 0.055123011100452285, 'dropout_rate': 0.11178105681173112, 'n_estimators': 398, 'criterion': 'friedman_mse', 'ccp_alpha': 8.808635181507519, 'min_weight_fraction_leaf': 0.2141846663477463, 'max_features': 0.1, 'min_impurity_decrease': 8.385166952734583e-07, 'validation_fraction': 0.8693234429106627, 'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:51:11,895] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.3427196246281643, 'learning_rate': 0.02181226739450172, 'dropout_rate': 0.25330085395937585, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 3.1260410279491686, 'min_weight_fraction_leaf': 0.09975982578242681, 'max_features': None, 'min_impurity_decrease': 3.2453997760645774e-07, 'validation_fraction': 0.64281654153714, 'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 15}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:51:37,700] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.12134026571324846, 'learning_rate': 0.030037341123185, 'dropout_rate': 0.476177268516495, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 2.002448222737427, 'min_weight_fraction_leaf': 0.1675014656774081, 'max_features': 'sqrt', 'min_impurity_decrease': 2.614633035612604e-05, 'validation_fraction': 0.3148019982511154, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:51:44,536] Trial 51 finished with value: 0.5 and parameters: {'subsample': 0.22560952991832442, 'learning_rate': 0.07096865200025802, 'dropout_rate': 0.7403990506884194, 'n_estimators': 105, 'criterion': 'friedman_mse', 'ccp_alpha': 3.6955183727273386, 'min_weight_fraction_leaf': 0.033756448345697854, 'max_features': None, 'min_impurity_decrease': 0.00034438274690092334, 'validation_fraction': 0.8185501989107483, 'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:52:26,026] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.4078669152596949, 'learning_rate': 0.07972542806076426, 'dropout_rate': 0.5885469293985746, 'n_estimators': 258, 'criterion': 'friedman_mse', 'ccp_alpha': 4.196656708934098, 'min_weight_fraction_leaf': 0.06070449344498474, 'max_features': None, 'min_impurity_decrease': 0.0006522112972854332, 'validation_fraction': 0.6875552859786656, 'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:53:22,643] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.5780503682164675, 'learning_rate': 0.06351565920160718, 'dropout_rate': 0.5268425864933246, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 5.912988737296398, 'min_weight_fraction_leaf': 0.2880138147880729, 'max_features': 'log2', 'min_impurity_decrease': 0.0023620162241031065, 'validation_fraction': 0.7386953311243849, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:53:56,991] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.771877515032402, 'learning_rate': 0.0879386461062289, 'dropout_rate': 0.6531928050964037, 'n_estimators': 243, 'criterion': 'friedman_mse', 'ccp_alpha': 6.749514129274708, 'min_weight_fraction_leaf': 0.010727427625077723, 'max_features': 'auto', 'min_impurity_decrease': 6.568909958494579e-05, 'validation_fraction': 0.5260231128653986, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:54:46,118] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.6352427224249186, 'learning_rate': 0.0018114229555726662, 'dropout_rate': 0.7780580098014175, 'n_estimators': 361, 'criterion': 'friedman_mse', 'ccp_alpha': 4.674374022230462, 'min_weight_fraction_leaf': 0.4028675241355946, 'max_features': None, 'min_impurity_decrease': 0.00015802436521782464, 'validation_fraction': 0.6116726877072444, 'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:55:06,824] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.7310159697721421, 'learning_rate': 0.09459281124929597, 'dropout_rate': 0.33513381234631495, 'n_estimators': 143, 'criterion': 'squared_error', 'ccp_alpha': 9.504060286925714, 'min_weight_fraction_leaf': 0.07554400849922152, 'max_features': 'sqrt', 'min_impurity_decrease': 3.609461626813292e-05, 'validation_fraction': 0.45003037837116033, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:55:24,880] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.4496884297691718, 'learning_rate': 0.055717108591229025, 'dropout_rate': 0.7227843588112581, 'n_estimators': 184, 'criterion': 'friedman_mse', 'ccp_alpha': 3.477932962998816, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': None, 'min_impurity_decrease': 6.805459531517676e-06, 'validation_fraction': 0.7746725177759497, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 20}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:56:08,520] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.5390990270834256, 'learning_rate': 0.08228345726531958, 'dropout_rate': 0.3867389328769052, 'n_estimators': 217, 'criterion': 'friedman_mse', 'ccp_alpha': 7.96887264775278, 'min_weight_fraction_leaf': 0.025824097286407145, 'max_features': 'auto', 'min_impurity_decrease': 2.1217250957605284e-07, 'validation_fraction': 0.7085899837169293, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:57:36,798] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.26995457899931047, 'learning_rate': 0.07839400629330891, 'dropout_rate': 0.44277207988197187, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 5.190496612405482, 'min_weight_fraction_leaf': 0.18052310410291128, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006646480686851006, 'validation_fraction': 0.36899118019789573, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:57:52,561] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.6821263907321534, 'learning_rate': 0.072006110155798, 'dropout_rate': 0.5000787935588615, 'n_estimators': 140, 'criterion': 'squared_error', 'ccp_alpha': 2.878661154904403, 'min_weight_fraction_leaf': 0.13302043494927485, 'max_features': None, 'min_impurity_decrease': 1.6927874845319952e-05, 'validation_fraction': 0.649254298624334, 'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:58:00,820] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.47645185130049367, 'learning_rate': 0.06448712922727752, 'dropout_rate': 0.18066337573915892, 'n_estimators': 76, 'criterion': 'squared_error', 'ccp_alpha': 9.986171866114088, 'min_weight_fraction_leaf': 0.3016342642588235, 'max_features': 'auto', 'min_impurity_decrease': 2.135935478598492e-06, 'validation_fraction': 0.39240181900023485, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:58:07,493] Trial 62 finished with value: 0.5 and parameters: {'subsample': 0.5808153861385129, 'learning_rate': 0.0681246585307992, 'dropout_rate': 0.23730162924900122, 'n_estimators': 71, 'criterion': 'squared_error', 'ccp_alpha': 8.569241148604158, 'min_weight_fraction_leaf': 0.26373450314917496, 'max_features': 'auto', 'min_impurity_decrease': 7.545132996978128e-05, 'validation_fraction': 0.5445924537815071, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 06:59:23,329] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.6306507981955418, 'learning_rate': 0.05196613429356862, 'dropout_rate': 0.29459029024130556, 'n_estimators': 276, 'criterion': 'squared_error', 'ccp_alpha': 7.302937119968669, 'min_weight_fraction_leaf': 0.21346358926716819, 'max_features': 'auto', 'min_impurity_decrease': 8.99541018098363e-06, 'validation_fraction': 0.48617563689534593, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:02:31,450] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.6655843820171748, 'learning_rate': 0.0755078862846863, 'dropout_rate': 0.16477104886116545, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 1.4394908967284419, 'min_weight_fraction_leaf': 0.3561841078487707, 'max_features': 0.1, 'min_impurity_decrease': 0.00011982157410057435, 'validation_fraction': 0.26717204824424134, 'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:02:34,710] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.7929453548007699, 'learning_rate': 0.05703829829485283, 'dropout_rate': 0.26693346156697134, 'n_estimators': 40, 'criterion': 'friedman_mse', 'ccp_alpha': 9.622909679545497, 'min_weight_fraction_leaf': 0.3739817512639645, 'max_features': 1, 'min_impurity_decrease': 1.132537699639542e-06, 'validation_fraction': 0.5719114708143103, 'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:07:10,986] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.7297228220058729, 'learning_rate': 0.048039429864377176, 'dropout_rate': 0.13146807723463924, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 2.2139349489390074, 'min_weight_fraction_leaf': 0.22907689759626237, 'max_features': None, 'min_impurity_decrease': 3.649342411644349e-05, 'validation_fraction': 0.6184842144993817, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:08:10,115] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.5640799123153939, 'learning_rate': 0.013731811381943973, 'dropout_rate': 0.6010596795994926, 'n_estimators': 312, 'criterion': 'friedman_mse', 'ccp_alpha': 4.4267489755284135, 'min_weight_fraction_leaf': 0.24894174086156923, 'max_features': 'log2', 'min_impurity_decrease': 5.850812869882035e-07, 'validation_fraction': 0.20583470481171634, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:10:47,319] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.6103857042426706, 'learning_rate': 0.004499506882329311, 'dropout_rate': 0.20156861633079565, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 7.575686101065674, 'min_weight_fraction_leaf': 0.3201448672949048, 'max_features': 'auto', 'min_impurity_decrease': 2.0511672586731725e-05, 'validation_fraction': 0.9734477789916156, 'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:11:34,788] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.38208631321852893, 'learning_rate': 0.019445173055985306, 'dropout_rate': 0.3471760689409496, 'n_estimators': 221, 'criterion': 'squared_error', 'ccp_alpha': 8.23137310474947, 'min_weight_fraction_leaf': 0.46019349583797037, 'max_features': 'sqrt', 'min_impurity_decrease': 5.25007498558406e-06, 'validation_fraction': 0.6668478041329834, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 8}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.5
Fold 3 C-index: 0.6495098039215687
Fold 4 C-index: 0.5168776371308017
Fold 5 C-index: 0.6220657276995305
[I 2024-04-19 07:11:47,106] Trial 70 finished with value: 0.5745737506334969 and parameters: {'subsample': 0.695791357845726, 'learning_rate': 0.0386121015837519, 'dropout_rate': 0.8772407730274028, 'n_estimators': 196, 'criterion': 'friedman_mse', 'ccp_alpha': 0.08521619959958793, 'min_weight_fraction_leaf': 0.2793514647088877, 'max_features': None, 'min_impurity_decrease': 1.0560662656413339e-07, 'validation_fraction': 0.4673552004275108, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:11:55,654] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.6953908543100885, 'learning_rate': 0.03743237534286249, 'dropout_rate': 0.9621327216313197, 'n_estimators': 198, 'criterion': 'friedman_mse', 'ccp_alpha': 0.15374641631577673, 'min_weight_fraction_leaf': 0.27657260116198973, 'max_features': None, 'min_impurity_decrease': 2.8920488173461134e-07, 'validation_fraction': 0.3339850543602635, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:12:10,292] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.6693434488547243, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.9021061225848414, 'n_estimators': 237, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6518397080948914, 'min_weight_fraction_leaf': 0.30089860849042194, 'max_features': None, 'min_impurity_decrease': 1.1606027609483291e-07, 'validation_fraction': 0.7490765541175108, 'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:12:20,317] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.7420556902526638, 'learning_rate': 0.03446255878761435, 'dropout_rate': 0.842247850975758, 'n_estimators': 164, 'criterion': 'friedman_mse', 'ccp_alpha': 1.27222591420132, 'min_weight_fraction_leaf': 0.23598753048020413, 'max_features': None, 'min_impurity_decrease': 1.55879459379031e-07, 'validation_fraction': 0.2508680771703865, 'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:12:32,293] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6407847417329294, 'learning_rate': 0.027234278844566435, 'dropout_rate': 0.8680349866283517, 'n_estimators': 184, 'criterion': 'friedman_mse', 'ccp_alpha': 8.952599299327895, 'min_weight_fraction_leaf': 0.26554541506545176, 'max_features': None, 'min_impurity_decrease': 1.0251502472109203e-07, 'validation_fraction': 0.2850419392236734, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5909090909090909
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6151960784313726
Fold 4 C-index: 0.6181434599156118
Fold 5 C-index: 0.6314553990610329
[I 2024-04-19 07:13:03,968] Trial 75 finished with value: 0.642926519949136 and parameters: {'subsample': 0.49605383018584304, 'learning_rate': 0.06741276323402065, 'dropout_rate': 0.8003972830508307, 'n_estimators': 296, 'criterion': 'friedman_mse', 'ccp_alpha': 0.08304534706000144, 'min_weight_fraction_leaf': 0.47835629989654377, 'max_features': None, 'min_impurity_decrease': 0.0002469950977072107, 'validation_fraction': 0.46406091324791776, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5995670995670995
Fold 2 C-index: 0.43526785714285715
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.6596244131455399
[I 2024-04-19 07:13:44,623] Trial 76 finished with value: 0.5992790668229235 and parameters: {'subsample': 0.31410999108550985, 'learning_rate': 0.04574117277556769, 'dropout_rate': 0.7628827130120311, 'n_estimators': 299, 'criterion': 'friedman_mse', 'ccp_alpha': 0.10179413563763529, 'min_weight_fraction_leaf': 0.48322374587938177, 'max_features': None, 'min_impurity_decrease': 0.0002155234609466344, 'validation_fraction': 0.4669980954945373, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:14:15,210] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7636926742441101, 'learning_rate': 0.04683137626817, 'dropout_rate': 0.8060826625310789, 'n_estimators': 296, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1204540963831401, 'min_weight_fraction_leaf': 0.4886312478929783, 'max_features': None, 'min_impurity_decrease': 0.00018014467270761062, 'validation_fraction': 0.45479088985861454, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:14:45,215] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.7126240797835157, 'learning_rate': 0.03866771774540286, 'dropout_rate': 0.7696992583170289, 'n_estimators': 268, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5562075267667846, 'min_weight_fraction_leaf': 0.44108285001317943, 'max_features': None, 'min_impurity_decrease': 0.00048603949189907753, 'validation_fraction': 0.34493979705070354, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:15:12,451] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.5915825661664962, 'learning_rate': 0.02377615162596504, 'dropout_rate': 0.8831816560103296, 'n_estimators': 324, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8644379636521962, 'min_weight_fraction_leaf': 0.47533730868525637, 'max_features': None, 'min_impurity_decrease': 0.00026754667959111344, 'validation_fraction': 0.3975502888375885, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:15:56,376] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.15032773286356033, 'learning_rate': 0.044220046970848, 'dropout_rate': 0.8012542413818668, 'n_estimators': 348, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05615612216402271, 'min_weight_fraction_leaf': 0.47264436421233097, 'max_features': None, 'min_impurity_decrease': 2.3708130065662297e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:16:30,279] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.3458856991309244, 'learning_rate': 0.061880262920121366, 'dropout_rate': 0.6683098819549974, 'n_estimators': 252, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0641865265099684, 'min_weight_fraction_leaf': 0.448452505667851, 'max_features': None, 'min_impurity_decrease': 0.0014437277259298509, 'validation_fraction': 0.5858261663814373, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5168776371308017
Fold 5 C-index: 0.5
[I 2024-04-19 07:17:10,963] Trial 82 finished with value: 0.5033755274261603 and parameters: {'subsample': 0.2979066859374864, 'learning_rate': 0.03192859199890033, 'dropout_rate': 0.7431338924278378, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 0.25619854049785146, 'min_weight_fraction_leaf': 0.4154239703802, 'max_features': None, 'min_impurity_decrease': 0.0006017716157596374, 'validation_fraction': 0.4734943895870986, 'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:17:50,077] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.18728973640084134, 'learning_rate': 0.03330792414298163, 'dropout_rate': 0.7362748870700768, 'n_estimators': 294, 'criterion': 'friedman_mse', 'ccp_alpha': 0.45015427190108215, 'min_weight_fraction_leaf': 0.41222450962239143, 'max_features': None, 'min_impurity_decrease': 0.0005484773067096504, 'validation_fraction': 0.47958183115384834, 'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:18:22,367] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.2845658432082305, 'learning_rate': 0.04081669734362587, 'dropout_rate': 0.821691123019113, 'n_estimators': 309, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6794510840916247, 'min_weight_fraction_leaf': 0.41828965104910665, 'max_features': None, 'min_impurity_decrease': 4.026918744152846e-07, 'validation_fraction': 0.4234978876665736, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:18:50,798] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.3286999719741053, 'learning_rate': 0.030988903051816365, 'dropout_rate': 0.7835055788285401, 'n_estimators': 268, 'criterion': 'friedman_mse', 'ccp_alpha': 0.36637580090608235, 'min_weight_fraction_leaf': 0.47537390714161937, 'max_features': None, 'min_impurity_decrease': 5.011899853561089e-05, 'validation_fraction': 0.5103256635243018, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:19:30,807] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.2614188055017745, 'learning_rate': 0.045388782330051294, 'dropout_rate': 0.7141718915119125, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5820304909263354, 'min_weight_fraction_leaf': 0.49165399924279257, 'max_features': None, 'min_impurity_decrease': 0.00023611116504182125, 'validation_fraction': 0.5510310673765155, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:20:18,293] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.24251315001966853, 'learning_rate': 0.016501644813831366, 'dropout_rate': 0.7576312694750015, 'n_estimators': 337, 'criterion': 'friedman_mse', 'ccp_alpha': 1.105952123672767, 'min_weight_fraction_leaf': 0.45037091777486393, 'max_features': 1, 'min_impurity_decrease': 9.437826649460271e-05, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:21:06,459] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.6520586662910131, 'learning_rate': 0.053489441535809173, 'dropout_rate': 0.6925885136491301, 'n_estimators': 316, 'criterion': 'friedman_mse', 'ccp_alpha': 0.863953681025809, 'min_weight_fraction_leaf': 0.42842611905779604, 'max_features': 'sqrt', 'min_impurity_decrease': 0.08546129120562182, 'validation_fraction': 0.35196407528199913, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.564935064935065
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.6053921568627451
Fold 4 C-index: 0.6476793248945147
Fold 5 C-index: 0.6408450704225352
[I 2024-04-19 07:21:33,350] Trial 89 finished with value: 0.6390917519944006 and parameters: {'subsample': 0.29788879637206783, 'learning_rate': 0.035555720782382214, 'dropout_rate': 0.9289339524597527, 'n_estimators': 366, 'criterion': 'friedman_mse', 'ccp_alpha': 0.020086704993095825, 'min_weight_fraction_leaf': 0.4667949943266333, 'max_features': 0.1, 'min_impurity_decrease': 0.0008812423360306166, 'validation_fraction': 0.38186035290218956, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:21:59,338] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.03247374059041004, 'dropout_rate': 0.9304311564311895, 'n_estimators': 365, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2639930078446805, 'min_weight_fraction_leaf': 0.3908665766982689, 'max_features': 0.1, 'min_impurity_decrease': 0.0018867119413392888, 'validation_fraction': 0.29585084927667094, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:22:15,936] Trial 91 finished with value: 0.5 and parameters: {'subsample': 0.32341400997126246, 'learning_rate': 0.036327713844900564, 'dropout_rate': 0.9925454077948749, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3111522605524543, 'min_weight_fraction_leaf': 0.4678372823653073, 'max_features': 0.1, 'min_impurity_decrease': 0.000768945964951233, 'validation_fraction': 0.3894300048498697, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:23:01,814] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.2254273223766157, 'learning_rate': 0.027929847361018882, 'dropout_rate': 0.8562165450473785, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.051481042392730963, 'min_weight_fraction_leaf': 0.49621848794515483, 'max_features': 0.1, 'min_impurity_decrease': 0.0029747778240912224, 'validation_fraction': 0.43212573688223266, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:23:24,971] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.7014559397669213, 'learning_rate': 0.04941640219482665, 'dropout_rate': 0.938553646035921, 'n_estimators': 351, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6471317001475573, 'min_weight_fraction_leaf': 0.49950467747375193, 'max_features': 0.1, 'min_impurity_decrease': 0.00014898895401809737, 'validation_fraction': 0.4756960290383652, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:23:47,403] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.6243723676927855, 'learning_rate': 0.010640812705694017, 'dropout_rate': 0.8972373322063223, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 0.749126219889791, 'min_weight_fraction_leaf': 0.45578862178588564, 'max_features': None, 'min_impurity_decrease': 0.0010375628696626341, 'validation_fraction': 0.41115482329305547, 'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:25:29,986] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.3575417229044505, 'learning_rate': 0.03602414533125063, 'dropout_rate': 0.31555645359514173, 'n_estimators': 333, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2620042855552611, 'min_weight_fraction_leaf': 0.4830374674994227, 'max_features': None, 'min_impurity_decrease': 0.00044880034816871956, 'validation_fraction': 0.5042132949646849, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5995670995670995
Fold 2 C-index: 0.75
Fold 3 C-index: 0.6053921568627451
Fold 4 C-index: 0.6139240506329114
Fold 5 C-index: 0.6784037558685446
[I 2024-04-19 07:25:53,714] Trial 96 finished with value: 0.6494574125862601 and parameters: {'subsample': 0.38768770746428227, 'learning_rate': 0.09228994112386232, 'dropout_rate': 0.815165927942691, 'n_estimators': 247, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0329344621321584, 'min_weight_fraction_leaf': 0.3309349122019748, 'max_features': None, 'min_impurity_decrease': 1.4894860335591788e-07, 'validation_fraction': 0.43791446522787536, 'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:26:07,759] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.39222767459068186, 'learning_rate': 0.09559539992853426, 'dropout_rate': 0.9250025476611926, 'n_estimators': 246, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4386059820040108, 'min_weight_fraction_leaf': 0.42699719679026016, 'max_features': 'log2', 'min_impurity_decrease': 0.004452254036847487, 'validation_fraction': 0.37371628758073683, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-19 07:26:28,453] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.427067537198888, 'learning_rate': 0.08984402570083139, 'dropout_rate': 0.8192282529527549, 'n_estimators': 224, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2503354049670562, 'min_weight_fraction_leaf': 0.36148411412968423, 'max_features': None, 'min_impurity_decrease': 0.0002882682632151261, 'validation_fraction': 0.43837016030823805, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 11}. Best is trial 9 with value: 0.6608490969281925.
Fold 1 C-index: 0.6168831168831169
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.6078431372549019
Fold 4 C-index: 0.6181434599156118

[I 2024-04-19 07:27:03,624] A new study created in memory with name: no-name-3a24c6ef-18b4-4432-9574-3591bc4e5f8a

Fold 5 C-index: 0.6666666666666666
[I 2024-04-19 07:27:03,597] Trial 99 finished with value: 0.6617287047154881 and parameters: {'subsample': 0.293918127029324, 'learning_rate': 0.09922718569465194, 'dropout_rate': 0.7939431243365798, 'n_estimators': 279, 'criterion': 'friedman_mse', 'ccp_alpha': 0.00443168890264431, 'min_weight_fraction_leaf': 0.34678735520439286, 'max_features': 'sqrt', 'min_impurity_decrease': 8.596034523879625e-05, 'validation_fraction': 0.3332285029879782, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 99 with value: 0.6617287047154881.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.6617287047154881], datetime_start=datetime.datetime(2024, 4, 19, 7, 26, 28, 471643), datetime_complete=datetime.datetime(2024, 4, 19, 7, 27, 3, 596187), params={'subsample': 0.293918127029324, 'learning_rate': 0.09922718569465194, 'dropout_rate': 0.7939431243365798, 'n_estimators': 279, 'criterion': 'friedman_mse', 'ccp_alpha': 0.00443168890264431, 'min_weight_fraction_leaf': 0.34678735520439286, 'max_features': 'sqrt', 'min_impurity_decrease': 8.596034523879625e-05, 'validation_fraction': 0.3332285029879782, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 12}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for C-index:
 0.6617287047154881

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 07:28:19,553] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 07:29:02,212] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:29:42,803] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:30:42,588] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:31:08,442] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 07:31:14,375] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 07:32:14,720] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 07:32:31,979] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:32:34,121] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21389609169187893
Fold 2 IBS: 0.22151809570438574
Fold 3 IBS: 0.20434951031162685
Fold 4 IBS: 0.22469248319684446
Fold 5 IBS: 0.21805954250695855
[I 2024-04-19 07:35:13,974] Trial 9 finished with value: 0.2165031446823389 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:39:19,214] Trial 10 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 07:42:05,768] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8081282674845877, 'learning_rate': 0.03957576815132133, 'dropout_rate': 0.3592207054036807, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 9.74116027708086, 'min_weight_fraction_leaf': 0.365889927692422, 'max_features': 'log2', 'min_impurity_decrease': 1.459170836380829e-06, 'validation_fraction': 0.7986785049611014, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 07:44:40,575] Trial 12 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3678235114093892, 'learning_rate': 0.04567946973839636, 'dropout_rate': 0.25727844951644346, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.3231056999503768, 'min_weight_fraction_leaf': 0.19696526950140963, 'max_features': 'auto', 'min_impurity_decrease': 1.6810148621356602e-06, 'validation_fraction': 0.8490366656238622, 'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:44:58,988] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7784830438231676, 'learning_rate': 0.02439641670004065, 'dropout_rate': 0.4821375662037144, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 6.245821408640139, 'min_weight_fraction_leaf': 0.3469021849356369, 'max_features': 1, 'min_impurity_decrease': 0.002901900339595834, 'validation_fraction': 0.40492470595401014, 'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:47:29,688] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5522283925781899, 'learning_rate': 0.010913227078192221, 'dropout_rate': 0.275468298707492, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.2209251544817152, 'max_features': 'log2', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.7267940764758692, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 07:50:19,158] Trial 15 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8321814107294574, 'learning_rate': 0.03462515781182537, 'dropout_rate': 0.10188162797857298, 'n_estimators': 375, 'criterion': 'friedman_mse', 'ccp_alpha': 5.585208670000242, 'min_weight_fraction_leaf': 0.3203472576334258, 'max_features': 0.1, 'min_impurity_decrease': 9.84228208509291e-05, 'validation_fraction': 0.9508448160253733, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 07:50:32,175] Trial 16 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.41637694759398924, 'learning_rate': 0.05102954371215744, 'dropout_rate': 0.4800989647660596, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 9.356569787888832, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': None, 'min_impurity_decrease': 6.315552530348283e-07, 'validation_fraction': 0.6329472651499938, 'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 19}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 07:54:36,702] Trial 17 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.18427032297888507, 'learning_rate': 0.016160179473353013, 'dropout_rate': 0.2643467397617198, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 1.767647956851031, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 'auto', 'min_impurity_decrease': 9.756988906280483e-06, 'validation_fraction': 0.460466512261803, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 07:55:20,633] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.29960178961969325, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.480521228562659, 'n_estimators': 234, 'criterion': 'friedman_mse', 'ccp_alpha': 6.571359927175668, 'min_weight_fraction_leaf': 0.3081685769690769, 'max_features': 'auto', 'min_impurity_decrease': 0.00017103826195115595, 'validation_fraction': 0.8334165513948124, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-19 07:55:41,651] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.14079986349305024, 'learning_rate': 0.0022617590243428215, 'dropout_rate': 0.7517968453304719, 'n_estimators': 197, 'criterion': 'squared_error', 'ccp_alpha': 6.452074842928597, 'min_weight_fraction_leaf': 0.2587652353783316, 'max_features': 'auto', 'min_impurity_decrease': 0.005768680906957018, 'validation_fraction': 0.8786489241905744, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 1}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 07:57:07,761] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.24265872160421625, 'learning_rate': 0.09210641510546798, 'dropout_rate': 0.46523489726077377, 'n_estimators': 329, 'criterion': 'squared_error', 'ccp_alpha': 4.870804793608105, 'min_weight_fraction_leaf': 0.43152288390795446, 'max_features': 'auto', 'min_impurity_decrease': 0.0002304744011468318, 'validation_fraction': 0.48727408136805295, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 07:57:56,007] Trial 21 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6094950880850886, 'learning_rate': 0.008899729354740909, 'dropout_rate': 0.4156145778245767, 'n_estimators': 236, 'criterion': 'friedman_mse', 'ccp_alpha': 8.278621831249582, 'min_weight_fraction_leaf': 0.3155932474077326, 'max_features': 'auto', 'min_impurity_decrease': 4.694387394774905e-05, 'validation_fraction': 0.7547747052438045, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 07:58:21,129] Trial 22 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2871142790618468, 'learning_rate': 0.025093979402539022, 'dropout_rate': 0.2770995126593906, 'n_estimators': 146, 'criterion': 'friedman_mse', 'ccp_alpha': 6.835319645459137, 'min_weight_fraction_leaf': 0.30133732679009123, 'max_features': None, 'min_impurity_decrease': 0.0007773401372966076, 'validation_fraction': 0.6658472502317975, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 08:00:29,625] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.48769513568564904, 'learning_rate': 0.018456221083045135, 'dropout_rate': 0.53741894468906, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 8.817736687096165, 'min_weight_fraction_leaf': 0.3638156336905286, 'max_features': 'auto', 'min_impurity_decrease': 2.810229431824276e-05, 'validation_fraction': 0.8357013182292345, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-19 08:01:34,553] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7488754310335448, 'learning_rate': 0.03089952267930116, 'dropout_rate': 0.32879197402435767, 'n_estimators': 259, 'criterion': 'friedman_mse', 'ccp_alpha': 9.981120123612905, 'min_weight_fraction_leaf': 0.2164711289226942, 'max_features': 0.1, 'min_impurity_decrease': 5.42338990036805e-06, 'validation_fraction': 0.9143974560141267, 'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 3}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:03:43,238] Trial 25 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8874543522938172, 'learning_rate': 0.004761399604301435, 'dropout_rate': 0.18173309155533923, 'n_estimators': 341, 'criterion': 'friedman_mse', 'ccp_alpha': 5.542613074541842, 'min_weight_fraction_leaf': 0.40164299470943704, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9852194132056973e-07, 'validation_fraction': 0.7563954099792602, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:04:52,901] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.46277628442238006, 'learning_rate': 0.04325862603961612, 'dropout_rate': 0.43074917692858017, 'n_estimators': 290, 'criterion': 'friedman_mse', 'ccp_alpha': 7.668509356745217, 'min_weight_fraction_leaf': 0.25134084317387756, 'max_features': 1, 'min_impurity_decrease': 0.00015745431279058403, 'validation_fraction': 0.5603595903911948, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 13}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:05:01,471] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3193135166121804, 'learning_rate': 0.015536686124689843, 'dropout_rate': 0.9847790608248583, 'n_estimators': 225, 'criterion': 'friedman_mse', 'ccp_alpha': 4.424459452567016, 'min_weight_fraction_leaf': 0.3372212390713461, 'max_features': 'log2', 'min_impurity_decrease': 0.005020040981624099, 'validation_fraction': 0.6424430041225765, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 08:05:23,074] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6224481475710952, 'learning_rate': 0.027340808999678275, 'dropout_rate': 0.5232444267019107, 'n_estimators': 166, 'criterion': 'squared_error', 'ccp_alpha': 1.3579090466039423, 'min_weight_fraction_leaf': 0.1605065207620611, 'max_features': None, 'min_impurity_decrease': 3.3238057066467287e-06, 'validation_fraction': 0.7883279075003073, 'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:06:07,563] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7165866941586748, 'learning_rate': 0.037453335849444366, 'dropout_rate': 0.7130342804882008, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 4.144031624908622, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'sqrt', 'min_impurity_decrease': 2.7205182948043777e-05, 'validation_fraction': 0.3265002522472238, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:07:01,575] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.636031175896398, 'learning_rate': 0.008217970787439355, 'dropout_rate': 0.8423465978925959, 'n_estimators': 422, 'criterion': 'friedman_mse', 'ccp_alpha': 2.3899676108316683, 'min_weight_fraction_leaf': 0.23371629234007008, 'max_features': 'auto', 'min_impurity_decrease': 5.4690807820604754e-05, 'validation_fraction': 0.697941804171905, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 17}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.2139765219514961
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:07:51,743] Trial 31 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6704587435666225, 'learning_rate': 0.09868202705851985, 'dropout_rate': 0.7942968321130364, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6708317687116205, 'min_weight_fraction_leaf': 0.09254919790029942, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005916374005909833, 'validation_fraction': 0.2154459552955903, 'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:08:50,848] Trial 32 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7031549425639906, 'learning_rate': 0.0841909264193112, 'dropout_rate': 0.6396107081761062, 'n_estimators': 327, 'criterion': 'friedman_mse', 'ccp_alpha': 3.180606095131633, 'min_weight_fraction_leaf': 0.49702216690803946, 'max_features': 'sqrt', 'min_impurity_decrease': 8.538682201266657e-05, 'validation_fraction': 0.3709424400465384, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676

Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:09:50,334] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7319198255223508, 'learning_rate': 0.054169729844528294, 'dropout_rate': 0.6101705401317011, 'n_estimators': 313, 'criterion': 'friedman_mse', 'ccp_alpha': 2.876665224201397, 'min_weight_fraction_leaf': 0.47840362890298604, 'max_features': 'sqrt', 'min_impurity_decrease': 8.968491592950819e-05, 'validation_fraction': 0.3688154101045705, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:10:30,660] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5833432046167292, 'learning_rate': 0.07952157166524661, 'dropout_rate': 0.6439627277495299, 'n_estimators': 267, 'criterion': 'friedman_mse', 'ccp_alpha': 5.427479405311726, 'min_weight_fraction_leaf': 0.45046287494052506, 'max_features': None, 'min_impurity_decrease': 0.001411350654717537, 'validation_fraction': 0.24963536181862767, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 08:12:22,459] Trial 35 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6759981312721777, 'learning_rate': 0.06142645602971149, 'dropout_rate': 0.32027248724159646, 'n_estimators': 343, 'criterion': 'friedman_mse', 'ccp_alpha': 4.129615069838275, 'min_weight_fraction_leaf': 0.4998924611243427, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2440446336188077e-05, 'validation_fraction': 0.5404012082537679, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:14:43,598] Trial 36 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5272918110993997, 'learning_rate': 0.06261578581596848, 'dropout_rate': 0.21517948211889956, 'n_estimators': 362, 'criterion': 'friedman_mse', 'ccp_alpha': 4.063848184083534, 'min_weight_fraction_leaf': 0.4963250705419947, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0003129076691432843, 'validation_fraction': 0.4348133972223629, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:16:32,698] Trial 37 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.08444404399090331, 'dropout_rate': 0.5625381440734535, 'n_estimators': 415, 'criterion': 'friedman_mse', 'ccp_alpha': 3.1379925153627317, 'min_weight_fraction_leaf': 0.4350557396734583, 'max_features': 'sqrt', 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.5464067179600798, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:18:18,359] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.845614406035329, 'learning_rate': 0.06824987522226218, 'dropout_rate': 0.32918341372879295, 'n_estimators': 339, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9635828477255348, 'min_weight_fraction_leaf': 0.47683179862026137, 'max_features': 'sqrt', 'min_impurity_decrease': 4.32232538916105e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 13}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:19:02,522] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6597097236895602, 'learning_rate': 0.05917897179340344, 'dropout_rate': 0.40168145360764357, 'n_estimators': 220, 'criterion': 'squared_error', 'ccp_alpha': 3.8498889793304736, 'min_weight_fraction_leaf': 0.38831552991944795, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0025382220080623e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:20:48,111] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7674106289123288, 'learning_rate': 0.07560432459160085, 'dropout_rate': 0.6757239331922499, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.9680569992941467, 'min_weight_fraction_leaf': 0.4599197939705914, 'max_features': 'auto', 'min_impurity_decrease': 2.8984969801345965e-07, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:22:06,951] Trial 41 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6905443471415563, 'learning_rate': 0.08991844550349633, 'dropout_rate': 0.3062177672417189, 'n_estimators': 284, 'criterion': 'friedman_mse', 'ccp_alpha': 4.7678853782582475, 'min_weight_fraction_leaf': 0.2815316241639545, 'max_features': None, 'min_impurity_decrease': 1.5004604379229747e-05, 'validation_fraction': 0.570943263446734, 'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:23:56,476] Trial 42 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5727452533507132, 'learning_rate': 0.07249852124211806, 'dropout_rate': 0.21510431819480508, 'n_estimators': 319, 'criterion': 'friedman_mse', 'ccp_alpha': 7.2599793775059345, 'min_weight_fraction_leaf': 0.28888666819812236, 'max_features': 1, 'min_impurity_decrease': 0.00015834833648163015, 'validation_fraction': 0.37796771299239895, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:25:50,183] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4265790468278674, 'learning_rate': 0.020077866785162254, 'dropout_rate': 0.37018492375604106, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 5.960286004690163, 'min_weight_fraction_leaf': 0.49889273199542455, 'max_features': 'sqrt', 'min_impurity_decrease': 5.9638605394856106e-05, 'validation_fraction': 0.7029786985243873, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:27:07,947] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7973150053365794, 'learning_rate': 0.006337134606386357, 'dropout_rate': 0.15064482764363352, 'n_estimators': 247, 'criterion': 'friedman_mse', 'ccp_alpha': 3.381558950528815, 'min_weight_fraction_leaf': 0.3628684941350201, 'max_features': None, 'min_impurity_decrease': 1.0072469681841355e-05, 'validation_fraction': 0.5967195594051253, 'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 9}. Best is trial 9 with value: 0.2165031446823389.

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:29:22,863] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5303064017076159, 'learning_rate': 0.013591809817627606, 'dropout_rate': 0.4506745791740544, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 2.5557833119257145, 'min_weight_fraction_leaf': 0.3344828403640176, 'max_features': 0.1, 'min_impurity_decrease': 0.02254931450703544, 'validation_fraction': 0.5042239156018957, 'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 14}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 08:30:39,373] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.042767734352667994, 'dropout_rate': 0.35811970946933236, 'n_estimators': 281, 'criterion': 'squared_error', 'ccp_alpha': 8.351912968810883, 'min_weight_fraction_leaf': 0.18996792578183735, 'max_features': 'log2', 'min_impurity_decrease': 0.000481840927394298, 'validation_fraction': 0.7889980344404982, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:31:04,921] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9461825771401899, 'learning_rate': 0.06195303328645835, 'dropout_rate': 0.5120167018154631, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 9.159235216571009, 'min_weight_fraction_leaf': 0.40375519491189016, 'max_features': 'auto', 'min_impurity_decrease': 2.531081899593294e-06, 'validation_fraction': 0.27559882629024807, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:31:06,003] Trial 48 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6409588871422276, 'learning_rate': 0.04865851095390379, 'dropout_rate': 0.5797126801998765, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.739609107328239, 'min_weight_fraction_leaf': 0.26407271071264776, 'max_features': 'auto', 'min_impurity_decrease': 0.0016897510356946545, 'validation_fraction': 0.98037867112525, 'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 8}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:33:28,568] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5894342645761806, 'learning_rate': 0.034101100960505684, 'dropout_rate': 0.30505113946900136, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 5.146711552010747, 'min_weight_fraction_leaf': 0.4399857804304742, 'max_features': 'sqrt', 'min_impurity_decrease': 6.203981222541818e-06, 'validation_fraction': 0.8372171681899604, 'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:35:45,326] Trial 50 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8328212088129892, 'learning_rate': 0.011750047838064437, 'dropout_rate': 0.22305695210880072, 'n_estimators': 358, 'criterion': 'squared_error', 'ccp_alpha': 6.882189904068126, 'min_weight_fraction_leaf': 0.31040829786124846, 'max_features': None, 'min_impurity_decrease': 7.50899650138145e-07, 'validation_fraction': 0.8962280884203246, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:36:17,751] Trial 51 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7357800616216513, 'learning_rate': 0.08274067108256297, 'dropout_rate': 0.8090617340394859, 'n_estimators': 298, 'criterion': 'friedman_mse', 'ccp_alpha': 4.526907013943373, 'min_weight_fraction_leaf': 0.008974406259752363, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2968653187143025e-05, 'validation_fraction': 0.14802842495662882, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 11}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:36:40,005] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.679117430541056, 'learning_rate': 0.08852429820426559, 'dropout_rate': 0.8771304848138055, 'n_estimators': 268, 'criterion': 'friedman_mse', 'ccp_alpha': 2.185255366537462, 'min_weight_fraction_leaf': 0.12135448690030037, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00013766373531663148, 'validation_fraction': 0.3383251947958834, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 08:37:35,755] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6116904400168919, 'learning_rate': 0.001099142947171871, 'dropout_rate': 0.6671338375088499, 'n_estimators': 326, 'criterion': 'friedman_mse', 'ccp_alpha': 3.7461701959089693, 'min_weight_fraction_leaf': 0.22337481705087078, 'max_features': 'auto', 'min_impurity_decrease': 8.269015090875863e-05, 'validation_fraction': 0.44314541028163157, 'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 12}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 08:38:02,349] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.771877515032402, 'learning_rate': 0.09629805895453353, 'dropout_rate': 0.7237985203908401, 'n_estimators': 243, 'criterion': 'friedman_mse', 'ccp_alpha': 2.900081225715882, 'min_weight_fraction_leaf': 0.1946180352482926, 'max_features': 1, 'min_impurity_decrease': 0.000310545367295499, 'validation_fraction': 0.19540582298921147, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-19 08:38:08,460] Trial 55 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7086352508071794, 'learning_rate': 0.08496463063739257, 'dropout_rate': 0.6248605528903883, 'n_estimators': 89, 'criterion': 'friedman_mse', 'ccp_alpha': 5.946169893251803, 'min_weight_fraction_leaf': 0.16253399075243827, 'max_features': 0.1, 'min_impurity_decrease': 2.0745433473467182e-05, 'validation_fraction': 0.28365184351149203, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 6}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 08:38:53,402] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1173095704794419, 'learning_rate': 0.022797925457682687, 'dropout_rate': 0.2500192595896841, 'n_estimators': 209, 'criterion': 'squared_error', 'ccp_alpha': 1.515994978548666, 'min_weight_fraction_leaf': 0.04557038009296144, 'max_features': 'sqrt', 'min_impurity_decrease': 8.288990661784225e-06, 'validation_fraction': 0.6682715637714014, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 7}. Best is trial 9 with value: 0.2165031446823389.
Fold 1 IBS: 0.21382373751543124
Fold 2 IBS: 0.2214840159838248
Fold 3 IBS: 0.20428815063117983
Fold 4 IBS: 0.22465724629235706
Fold 5 IBS: 0.21804196994519903
[I 2024-04-19 08:39:30,711] Trial 57 finished with value: 0.2164590240735984 and parameters: {'subsample': 0.553868700002313, 'learning_rate': 0.07780886066105958, 'dropout_rate': 0.7575479273298723, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0636428366764088, 'min_weight_fraction_leaf': 0.2954895332892262, 'max_features': 'log2', 'min_impurity_decrease': 4.237895965249124e-05, 'validation_fraction': 0.7444606410682515, 'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 57 with value: 0.2164590240735984.
Fold 1 IBS: 0.21363803371357373
Fold 2 IBS: 0.22110039380624796
Fold 3 IBS: 0.2040767000566504
Fold 4 IBS: 0.224494688896027
Fold 5 IBS: 0.217885225044749
[I 2024-04-19 08:40:33,025] Trial 58 finished with value: 0.21623900830344964 and parameters: {'subsample': 0.5068380874811701, 'learning_rate': 0.07262285651752191, 'dropout_rate': 0.7041347398290517, 'n_estimators': 378, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03918644077746685, 'min_weight_fraction_leaf': 0.3501224417387053, 'max_features': 'log2', 'min_impurity_decrease': 4.18700542213e-05, 'validation_fraction': 0.7454328663550801, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 58 with value: 0.21623900830344964.
Fold 1 IBS: 0.21394342866781602
Fold 2 IBS: 0.22153634560932614
Fold 3 IBS: 0.2044554248188238
Fold 4 IBS: 0.2247111464752178
Fold 5 IBS: 0.21811060397061782
[I 2024-04-19 08:41:45,916] Trial 59 finished with value: 0.21655138990836034 and parameters: {'subsample': 0.3756731628300646, 'learning_rate': 0.0713336187568541, 'dropout_rate': 0.7116701148836264, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11427638256939372, 'min_weight_fraction_leaf': 0.2989130613985737, 'max_features': 'log2', 'min_impurity_decrease': 4.314426667063267e-05, 'validation_fraction': 0.7417723383986068, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 58 with value: 0.21623900830344964.
Fold 1 IBS: 0.2139602873514173
Fold 2 IBS: 0.22156453867176737
Fold 3 IBS: 0.20449004945132213
Fold 4 IBS: 0.22471838055977042
Fold 5 IBS: 0.21810869160404658
[I 2024-04-19 08:43:00,673] Trial 60 finished with value: 0.21656838952766475 and parameters: {'subsample': 0.352587285254757, 'learning_rate': 0.0759991473024008, 'dropout_rate': 0.7719154717054937, 'n_estimators': 461, 'criterion': 'friedman_mse', 'ccp_alpha': 0.12935509535102224, 'min_weight_fraction_leaf': 0.29577635182154743, 'max_features': 'log2', 'min_impurity_decrease': 0.00022374666447428864, 'validation_fraction': 0.7250691100626211, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 58 with value: 0.21623900830344964.
Fold 1 IBS: 0.21387999664668364
Fold 2 IBS: 0.22147225161710657
Fold 3 IBS: 0.20434643556045545
Fold 4 IBS: 0.2246561673733787
Fold 5 IBS: 0.21803394102232293
[I 2024-04-19 08:44:45,026] Trial 61 finished with value: 0.21647775844398948 and parameters: {'subsample': 0.365140791655746, 'learning_rate': 0.07256692244824432, 'dropout_rate': 0.6998637630005794, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.29736911681242306, 'max_features': 'log2', 'min_impurity_decrease': 0.00025106852346533435, 'validation_fraction': 0.7571179766181859, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 58 with value: 0.21623900830344964.
Fold 1 IBS: 0.21354933124553058
Fold 2 IBS: 0.22087999543626624
Fold 3 IBS: 0.20408994702452557
Fold 4 IBS: 0.22447226456287456
Fold 5 IBS: 0.21783133948006986
[I 2024-04-19 08:46:11,040] Trial 62 finished with value: 0.21616457554985335 and parameters: {'subsample': 0.35162005527246953, 'learning_rate': 0.07162165893265986, 'dropout_rate': 0.7683459560011311, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022802443424669597, 'min_weight_fraction_leaf': 0.2983669388531223, 'max_features': 'log2', 'min_impurity_decrease': 0.0001919679928415339, 'validation_fraction': 0.8181036899378618, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.21616457554985335.
Fold 1 IBS: 0.21354267039076394
Fold 2 IBS: 0.22078849750094748
Fold 3 IBS: 0.20408010239044164
Fold 4 IBS: 0.22446143598986593
Fold 5 IBS: 0.21780490280487722
[I 2024-04-19 08:47:35,029] Trial 63 finished with value: 0.21613552181537923 and parameters: {'subsample': 0.3567446827796533, 'learning_rate': 0.07169892058573697, 'dropout_rate': 0.7775471917139705, 'n_estimators': 495, 'criterion': 'friedman_mse', 'ccp_alpha': 0.01806705726143175, 'min_weight_fraction_leaf': 0.29353532528586684, 'max_features': 'log2', 'min_impurity_decrease': 0.0010116175104178482, 'validation_fraction': 0.7243004778427239, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-19 08:49:24,500] Trial 64 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.3886078974413502, 'learning_rate': 0.07144507176729598, 'dropout_rate': 0.7023821481980385, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.43348045602434143, 'min_weight_fraction_leaf': 0.27473389221902517, 'max_features': 'log2', 'min_impurity_decrease': 0.0009682656128507961, 'validation_fraction': 0.7627539202845117, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:50:12,968] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2673613405331815, 'learning_rate': 0.06567665087392267, 'dropout_rate': 0.9044904250308854, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.925332478660159, 'min_weight_fraction_leaf': 0.32166013263939586, 'max_features': 'log2', 'min_impurity_decrease': 0.0038325871299788386, 'validation_fraction': 0.8074879921001441, 'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21379514235646263
Fold 2 IBS: 0.22130942202833423
Fold 3 IBS: 0.20421069896752325
Fold 4 IBS: 0.22457996641220127
Fold 5 IBS: 0.21803648696207817
[I 2024-04-19 08:51:38,329] Trial 66 finished with value: 0.21638634334531986 and parameters: {'subsample': 0.4479841440927695, 'learning_rate': 0.07944842979211152, 'dropout_rate': 0.7558727638855666, 'n_estimators': 479, 'criterion': 'friedman_mse', 'ccp_alpha': 0.06581072581869334, 'min_weight_fraction_leaf': 0.24401127082290142, 'max_features': 'log2', 'min_impurity_decrease': 0.007856364367505055, 'validation_fraction': 0.8694699708304008, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 08:52:35,642] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.44533772449036413, 'learning_rate': 0.0814448088163274, 'dropout_rate': 0.8313520760085876, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5496755232313972, 'min_weight_fraction_leaf': 0.23846073397265538, 'max_features': 'log2', 'min_impurity_decrease': 0.0245829172127866, 'validation_fraction': 0.8751349059723512, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-19 08:54:03,012] Trial 68 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.49945879365729917, 'learning_rate': 0.07904961819884797, 'dropout_rate': 0.7519380649315037, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.8957585677593288, 'min_weight_fraction_leaf': 0.34957407691787235, 'max_features': 'log2', 'min_impurity_decrease': 0.013697139277504513, 'validation_fraction': 0.9123753116320972, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:55:17,185] Trial 69 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.32975856917620583, 'learning_rate': 0.06481359395677139, 'dropout_rate': 0.7746913930571027, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1637311364800136, 'min_weight_fraction_leaf': 0.2664740964846672, 'max_features': 'log2', 'min_impurity_decrease': 0.009633379913496559, 'validation_fraction': 0.6626736312675832, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 08:56:11,083] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.2082560982819609, 'learning_rate': 0.056100758346501266, 'dropout_rate': 0.8822399932671225, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010162627459860702, 'min_weight_fraction_leaf': 0.25337827716940275, 'max_features': 'log2', 'min_impurity_decrease': 0.042176472946749144, 'validation_fraction': 0.8082415325648188, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.2215779171866794
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:57:22,474] Trial 71 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39260950413966267, 'learning_rate': 0.07026974490651595, 'dropout_rate': 0.7335367340802712, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2698698998773895, 'min_weight_fraction_leaf': 0.33122858051664955, 'max_features': 'log2', 'min_impurity_decrease': 0.07623847919135997, 'validation_fraction': 0.7333696044027135, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 08:58:54,094] Trial 72 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.36137940306921024, 'learning_rate': 0.07365043020696545, 'dropout_rate': 0.6771558577713755, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6400766669093484, 'min_weight_fraction_leaf': 0.30089829515047245, 'max_features': 'log2', 'min_impurity_decrease': 0.00042689293034457433, 'validation_fraction': 0.7634619284628702, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 09:00:38,153] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.48151682839955934, 'learning_rate': 0.06817264381363343, 'dropout_rate': 0.7024988926880507, 'n_estimators': 471, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3657398885794429, 'min_weight_fraction_leaf': 0.24216909030592224, 'max_features': 'log2', 'min_impurity_decrease': 0.0021650937570782437, 'validation_fraction': 0.8641607956473496, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-19 09:01:54,248] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4215055568651348, 'learning_rate': 0.07810222356149038, 'dropout_rate': 0.8205209533828131, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7381991024391248, 'min_weight_fraction_leaf': 0.35369645882730016, 'max_features': 'log2', 'min_impurity_decrease': 4.6048213048729805e-05, 'validation_fraction': 0.9414144145640158, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 63 with value: 0.21613552181537923.
Fold 1 IBS: 0.21339400690696403
Fold 2 IBS: 0.22035420066692074
Fold 3 IBS: 0.20386120154902201
Fold 4 IBS: 0.22428681941532955
Fold 5 IBS: 0.21768298723924243
[I 2024-04-19 09:02:50,443] Trial 75 finished with value: 0.21591584315549578 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.7826693566389662, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.009365616677551508, 'min_weight_fraction_leaf': 0.2812508412156809, 'max_features': 'log2', 'min_impurity_decrease': 0.0008096076350961149, 'validation_fraction': 0.7004324115891782, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 09:03:44,335] Trial 76 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5316206971146037, 'learning_rate': 0.08789602466821712, 'dropout_rate': 0.7878921244358874, 'n_estimators': 376, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7129649228563721, 'min_weight_fraction_leaf': 0.2739615311557543, 'max_features': 'log2', 'min_impurity_decrease': 0.000870969610631372, 'validation_fraction': 0.708303200355191, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 09:04:41,806] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.44602496158905264, 'learning_rate': 0.09471995926608345, 'dropout_rate': 0.8416081500565789, 'n_estimators': 449, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1836750520365744, 'min_weight_fraction_leaf': 0.322243588217481, 'max_features': 'log2', 'min_impurity_decrease': 0.0006764533780293487, 'validation_fraction': 0.685260872290134, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21350170214785763

Fold 2 IBS: 0.2207305662643275
Fold 3 IBS: 0.20400135988740564
Fold 4 IBS: 0.22440754040830044
Fold 5 IBS: 0.21783913995162144
[I 2024-04-19 09:05:39,249] Trial 78 finished with value: 0.21609606173190254 and parameters: {'subsample': 0.3352733938121141, 'learning_rate': 0.07411999177509665, 'dropout_rate': 0.8605229004531987, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.023234528924181166, 'min_weight_fraction_leaf': 0.20870378808533252, 'max_features': 'log2', 'min_impurity_decrease': 0.007686471270079544, 'validation_fraction': 0.6325076348170467, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.2136232633771708
Fold 2 IBS: 0.2208637477666032
Fold 3 IBS: 0.2041050225232073
Fold 4 IBS: 0.22443455729626233
Fold 5 IBS: 0.2178626020978067
[I 2024-04-19 09:06:07,014] Trial 79 finished with value: 0.21617783861221004 and parameters: {'subsample': 0.33166032751272273, 'learning_rate': 0.07500771068641232, 'dropout_rate': 0.959151447197707, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.006098257907680538, 'min_weight_fraction_leaf': 0.1475995309958919, 'max_features': 'log2', 'min_impurity_decrease': 0.00794742620491249, 'validation_fraction': 0.8199692718327473, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 09:06:35,272] Trial 80 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.32209627148296655, 'learning_rate': 0.08110077633419584, 'dropout_rate': 0.9673309512711019, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.4189618906006418, 'min_weight_fraction_leaf': 0.1370057476341762, 'max_features': 'log2', 'min_impurity_decrease': 0.007576465474689223, 'validation_fraction': 0.7888212409638161, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21361399187185576
Fold 2 IBS: 0.22087724469745423
Fold 3 IBS: 0.2041267037778896
Fold 4 IBS: 0.224474104015821
Fold 5 IBS: 0.2178859658252375
[I 2024-04-19 09:07:24,220] Trial 81 finished with value: 0.21619560203765165 and parameters: {'subsample': 0.2730789104176549, 'learning_rate': 0.07535038448871262, 'dropout_rate': 0.8907726644005417, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.025664346357114027, 'min_weight_fraction_leaf': 0.21347182296833242, 'max_features': 'log2', 'min_impurity_decrease': 0.0028792178882720604, 'validation_fraction': 0.8134622977427909, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 09:08:01,746] Trial 82 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.2443803359673073, 'learning_rate': 0.07515191280946948, 'dropout_rate': 0.9365742852061131, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.6846594891336125, 'min_weight_fraction_leaf': 0.2110761039955827, 'max_features': 'log2', 'min_impurity_decrease': 0.003770285603834295, 'validation_fraction': 0.8215587831404426, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-19 09:08:34,680] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2987744122181278, 'learning_rate': 0.07751714625692861, 'dropout_rate': 0.9517605425833411, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 1.1625030732953487, 'min_weight_fraction_leaf': 0.17683438341305044, 'max_features': 'log2', 'min_impurity_decrease': 0.013019692174691478, 'validation_fraction': 0.8425793687098613, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 09:09:12,160] Trial 84 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.272692965452795, 'learning_rate': 0.09218659555435788, 'dropout_rate': 0.9120677449246954, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.31345585885032023, 'min_weight_fraction_leaf': 0.1504169269634668, 'max_features': 'log2', 'min_impurity_decrease': 0.001310541261910843, 'validation_fraction': 0.77453385805827, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21332397893223676
Fold 2 IBS: 0.22046888863984318
Fold 3 IBS: 0.20384241600387937
Fold 4 IBS: 0.22432109810362974
Fold 5 IBS: 0.21778321628427988
[I 2024-04-19 09:09:53,624] Trial 85 finished with value: 0.21594791959277382 and parameters: {'subsample': 0.33629527130521414, 'learning_rate': 0.0870188009772593, 'dropout_rate': 0.8650736182476468, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.011442347425600019, 'min_weight_fraction_leaf': 0.20755679443331537, 'max_features': 'log2', 'min_impurity_decrease': 0.0023183056456774986, 'validation_fraction': 0.611401083754954, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 09:10:34,756] Trial 86 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.21963133741289753, 'learning_rate': 0.08691689895122054, 'dropout_rate': 0.8639328821805979, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.8595756716116553, 'min_weight_fraction_leaf': 0.2075199255789235, 'max_features': 'log2', 'min_impurity_decrease': 0.0024751974417942736, 'validation_fraction': 0.6298878350786835, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 6}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 09:10:54,601] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3402343884216612, 'learning_rate': 0.08193314615040609, 'dropout_rate': 0.9957728348703542, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.4303615780077674, 'min_weight_fraction_leaf': 0.10151778721521143, 'max_features': 'log2', 'min_impurity_decrease': 0.006334784831296356, 'validation_fraction': 0.5951116917871544, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 09:11:49,702] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.301968281614769, 'learning_rate': 0.09101353432453513, 'dropout_rate': 0.8588126669771299, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.5804172950325953, 'min_weight_fraction_leaf': 0.22570081451818483, 'max_features': 'log2', 'min_impurity_decrease': 0.003713652825592109, 'validation_fraction': 0.8637776054651919, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613

Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 09:12:40,387] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.40845912170347753, 'learning_rate': 0.07409455257113193, 'dropout_rate': 0.9031580025226588, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 1.426169496743956, 'min_weight_fraction_leaf': 0.17670307432796536, 'max_features': 'log2', 'min_impurity_decrease': 0.001833888378396466, 'validation_fraction': 0.7135149436193794, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.2139763741496877
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473191517656796
Fold 5 IBS: 0.21812464788704478
[I 2024-04-19 09:13:31,460] Trial 90 finished with value: 0.21658936034403223 and parameters: {'subsample': 0.2452119153654136, 'learning_rate': 0.06690965498406037, 'dropout_rate': 0.8066291177301238, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.25226236647044514, 'min_weight_fraction_leaf': 0.2043087203480301, 'max_features': 'log2', 'min_impurity_decrease': 0.015893997542605183, 'validation_fraction': 0.6554569651844447, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21359293347020145
Fold 2 IBS: 0.2210328130469813
Fold 3 IBS: 0.20406398804605086
Fold 4 IBS: 0.22446002756653557
Fold 5 IBS: 0.21787663365501675
[I 2024-04-19 09:14:39,132] Trial 91 finished with value: 0.21620527915695717 and parameters: {'subsample': 0.4756341195439041, 'learning_rate': 0.0800252800386436, 'dropout_rate': 0.7652963456531969, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.03815642121067697, 'min_weight_fraction_leaf': 0.2460810079638242, 'max_features': 'log2', 'min_impurity_decrease': 0.0029462543097600468, 'validation_fraction': 0.8222999411247428, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 09:15:11,799] Trial 92 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4738692621675931, 'learning_rate': 0.08571120447983799, 'dropout_rate': 0.9279795412285471, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0329237742117718, 'min_weight_fraction_leaf': 0.24643635347261278, 'max_features': 'log2', 'min_impurity_decrease': 0.009212522759670414, 'validation_fraction': 0.6810950539045996, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.2137018611895883
Fold 2 IBS: 0.2211544434145148
Fold 3 IBS: 0.2040695657468695
Fold 4 IBS: 0.22447452328372927
Fold 5 IBS: 0.21795761856437224
[I 2024-04-19 09:16:35,556] Trial 93 finished with value: 0.2162716024398148 and parameters: {'subsample': 0.502022316864097, 'learning_rate': 0.08011752117044743, 'dropout_rate': 0.738394230646288, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.04782056519286319, 'min_weight_fraction_leaf': 0.2319086524805259, 'max_features': 'log2', 'min_impurity_decrease': 0.004724206934754632, 'validation_fraction': 0.8956179143254437, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 09:17:33,302] Trial 94 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.3474996745904486, 'learning_rate': 0.06916682435148223, 'dropout_rate': 0.7863795201728742, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.5434180175655979, 'min_weight_fraction_leaf': 0.17702787860367203, 'max_features': 'log2', 'min_impurity_decrease': 0.00132591111872389, 'validation_fraction': 0.817381490179014, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-19 09:18:26,248] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5072126109779981, 'learning_rate': 0.09404126235069282, 'dropout_rate': 0.8526269567049083, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.7732662773015029, 'min_weight_fraction_leaf': 0.2319533947623919, 'max_features': 'log2', 'min_impurity_decrease': 0.002924808261158542, 'validation_fraction': 0.9258516255293189, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 09:19:12,257] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3103600726415323, 'learning_rate': 0.06406371557843682, 'dropout_rate': 0.8199827211243065, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 0.2396855828547869, 'min_weight_fraction_leaf': 0.261970915381811, 'max_features': 1, 'min_impurity_decrease': 0.005183152799306324, 'validation_fraction': 0.8996721903976425, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-19 09:20:37,973] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.28651805009091497, 'learning_rate': 0.0838006258575085, 'dropout_rate': 0.7414748169104224, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.299429272232856, 'min_weight_fraction_leaf': 0.22029404567890065, 'max_features': 0.1, 'min_impurity_decrease': 0.0032862083702029487, 'validation_fraction': 0.6089360683568277, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-19 09:21:24,697] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5129217027539859, 'learning_rate': 0.08060435391980184, 'dropout_rate': 0.8846093811473095, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.5371484454220302, 'min_weight_fraction_leaf': 0.20058461034167657, 'max_features': 'log2', 'min_impurity_decrease': 0.0011099956679015755, 'validation_fraction': 0.97208801308084, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.21591584315549578.
Fold 1 IBS: 0.21343994097124971
Fold 2 IBS: 0.22070402299353245
Fold 3 IBS: 0.20388179408154122
Fold 4 IBS: 0.2243241978151226
Fold 5 IBS: 0.21783613251153827
[I 2024-04-19 09:21:47,935] Trial 99 finished with value: 0.21603721767459683 and parameters: {'subsample': 0.40639725945398314, 'learning_rate': 0.07562787330036341, 'dropout_rate': 0.97231310078209, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.0045100151809840325, 'min_weight_fraction_leaf': 0.14310707528126343, 'max_features': 'log2', 'min_impurity_decrease': 0.0005780747492707621, 'validation_fraction': 0.7834834248980211, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 75 with value: 0.21591584315549578.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.21591584315549578], datetime_start=datetime.datetime(2024, 4, 19, 9, 1, 54, 256335), datetime_complete=datetime.datetime(2024, 4, 19, 9, 2, 50, 441620), params={'subsample': 0.5200735929114648, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.7826693566389662, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.009365616677551508, 'min_weight_fraction_leaf': 0.2812508412156809, 'max_features': 'log2', 'min_impurity_decrease': 0.0008096076350961149, 'validation_fraction': 0.7004324115891782, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.21591584315549578

In [105]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [106]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.662
train_ibs:  0.216

#### Test

In [107]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [108]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.00443168890264431,
                                 dropout_rate=0.7939431243365798,
                                 learning_rate=0.09922718569465194,
                                 max_depth=12, max_features='sqrt',
                                 max_leaf_nodes=20,
                                 min_impurity_decrease=8.596034523879625e-05,
                                 min_samples_leaf=11, min_samples_split=5,
                                 min_weight_fraction_leaf=0.34678735520439286,
                                 n_estimators=279, random_state=123,
                                 subsample=0.293918127029324,
                                 validation_fraction=0.3332285029879782)

C-index score: 0.595

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009365616677551508,
                                 dropout_rate=0.7826693566389662,
                                 learning_rate=0.08843409287484169, max_depth=4,
                                 max_features='log2', max_leaf_nodes=14,
                                 min_impurity_decrease=0.0008096076350961149,
                                 min_samples_leaf=16, min_samples_split=19,
                                 min_weight_fraction_leaf=0.2812508412156809,
                                 n_estimators=403, random_state=123,
                                 subsample=0.5200735929114648,
                                 validation_fraction=0.7004324115891782)

IBS: 0.221

In [109]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [110]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [111]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')

            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)

                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-19 09:22:05,815] A new study created in memory with name: no-name-1b0c7f0e-c0a6-4d65-a4f3-1df90e419fb1

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:22:08,496] Trial 0 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:22:32,009] Trial 1 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:22:36,844] Trial 2 finished with value: 0.6805414605346831 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:22:43,222] Trial 3 finished with value: 0.6790391824082426 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:22:53,419] Trial 4 finished with value: 0.6783422264106538 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:23:06,213] Trial 5 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.6830731061043034.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:23:11,532] Trial 6 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:23:12,950] Trial 7 finished with value: 0.683258591690943 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:23:19,236] Trial 8 finished with value: 0.683209616404626 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:23:36,932] Trial 9 finished with value: 0.6840534982611661 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:23:48,264] Trial 10 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 328, 'learning_rate': 0.0017980531969980576}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:23:58,910] Trial 11 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.756040755732822, 'n_estimators': 318, 'learning_rate': 0.01192895807324408}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:24:12,567] Trial 12 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9876601507615164, 'dropout_rate': 0.6475328937135156, 'n_estimators': 368, 'learning_rate': 0.00211473379798891}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:24:15,143] Trial 13 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8828571249279873, 'dropout_rate': 0.9845292840882569, 'n_estimators': 109, 'learning_rate': 0.021551885021979505}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:24:27,154] Trial 14 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.8303809418383279, 'dropout_rate': 0.3633325368639867, 'n_estimators': 312, 'learning_rate': 0.08842544557957996}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:24:28,356] Trial 15 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.8500676869704417, 'dropout_rate': 0.7036446331147568, 'n_estimators': 30, 'learning_rate': 0.026008464594474617}. Best is trial 6 with value: 0.6847608698173835.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:24:46,892] Trial 16 finished with value: 0.6855981769358904 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.5672052413745938, 'n_estimators': 419, 'learning_rate': 0.0016507495863954742}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:25:09,695] Trial 17 finished with value: 0.6837934089339394 and parameters: {'subsample': 0.17085174271948028, 'dropout_rate': 0.10421921753457947, 'n_estimators': 433, 'learning_rate': 0.03660615787439462}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:25:29,623] Trial 18 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.6228632499672725, 'dropout_rate': 0.33602353085084236, 'n_estimators': 413, 'learning_rate': 0.0169316883078754}. Best is trial 16 with value: 0.6855981769358904.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:25:33,436] Trial 19 finished with value: 0.682842486051942 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.5750257507026826, 'n_estimators': 131, 'learning_rate': 0.009453412662102966}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:25:42,853] Trial 20 finished with value: 0.6850932812629744 and parameters: {'subsample': 0.3813470543085155, 'dropout_rate': 0.2342004098513716, 'n_estimators': 258, 'learning_rate': 0.03971460589320458}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:25:52,056] Trial 21 finished with value: 0.6850932812629744 and parameters: {'subsample': 0.3544427943546895, 'dropout_rate': 0.21933350115865263, 'n_estimators': 255, 'learning_rate': 0.03976615073210863}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:26:01,400] Trial 22 finished with value: 0.6850932812629744 and parameters: {'subsample': 0.3471313882452718, 'dropout_rate': 0.23422743217006892, 'n_estimators': 258, 'learning_rate': 0.03964896917658691}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:26:11,811] Trial 23 finished with value: 0.6806498266659456 and parameters: {'subsample': 0.3562476445262424, 'dropout_rate': 0.2444847293155728, 'n_estimators': 277, 'learning_rate': 0.09323355252515839}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 09:26:32,103] Trial 24 finished with value: 0.6773935755034278 and parameters: {'subsample': 0.2557249722760191, 'dropout_rate': 0.1802439250559449, 'n_estimators': 406, 'learning_rate': 0.04499692649926165}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:26:39,749] Trial 25 finished with value: 0.6805414605346831 and parameters: {'subsample': 0.4273211004911626, 'dropout_rate': 0.4581486278087431, 'n_estimators': 238, 'learning_rate': 0.03165412454785818}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:26:55,245] Trial 26 finished with value: 0.6772523802305246 and parameters: {'subsample': 0.22809976025677553, 'dropout_rate': 0.2957532613537218, 'n_estimators': 362, 'learning_rate': 0.08428411509794898}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:27:14,588] Trial 27 finished with value: 0.6838614379364933 and parameters: {'subsample': 0.1004911963942467, 'dropout_rate': 0.5697175944982166, 'n_estimators': 433, 'learning_rate': 0.06071884280131438}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:27:28,034] Trial 28 finished with value: 0.6810157990407302 and parameters: {'subsample': 0.18797548936281522, 'dropout_rate': 0.10435509106314214, 'n_estimators': 296, 'learning_rate': 0.029712947643330115}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:27:32,030] Trial 29 finished with value: 0.6833075669772601 and parameters: {'subsample': 0.3151298518101162, 'dropout_rate': 0.4175950896276197, 'n_estimators': 131, 'learning_rate': 0.012081639584001175}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:27:34,662] Trial 30 finished with value: 0.6815708279778628 and parameters: {'subsample': 0.4169254489502223, 'dropout_rate': 0.5073809994327254, 'n_estimators': 93, 'learning_rate': 0.04659984582278388}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:27:45,033] Trial 31 finished with value: 0.6791371329808767 and parameters: {'subsample': 0.3016703819245796, 'dropout_rate': 0.19222986882670284, 'n_estimators': 259, 'learning_rate': 0.038031871063739356}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:27:53,556] Trial 32 finished with value: 0.6841024735474831 and parameters: {'subsample': 0.4068628433881887, 'dropout_rate': 0.2962930768652379, 'n_estimators': 239, 'learning_rate': 0.03945823488457274}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:28:00,483] Trial 33 finished with value: 0.6813853423912232 and parameters: {'subsample': 0.5983063637122126, 'dropout_rate': 0.24339194707134354, 'n_estimators': 210, 'learning_rate': 0.0574421228891803}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:28:05,623] Trial 34 finished with value: 0.6828400730541329 and parameters: {'subsample': 0.16338901105740034, 'dropout_rate': 0.20269789815635297, 'n_estimators': 161, 'learning_rate': 0.06719848119540581}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:28:19,893] Trial 35 finished with value: 0.6850932812629744 and parameters: {'subsample': 0.3214183065949459, 'dropout_rate': 0.30651060757027226, 'n_estimators': 341, 'learning_rate': 0.039974506577767986}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:28:46,683] Trial 36 finished with value: 0.6813853423912232 and parameters: {'subsample': 0.5302228207208626, 'dropout_rate': 0.4209338614518377, 'n_estimators': 499, 'learning_rate': 0.050875148824736156}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:28:57,102] Trial 37 finished with value: 0.6790391824082426 and parameters: {'subsample': 0.44051936983119183, 'dropout_rate': 0.1585216473218155, 'n_estimators': 269, 'learning_rate': 0.07677405503763898}. Best is trial 16 with value: 0.6855981769358904.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:29:07,411] Trial 38 finished with value: 0.6841024735474831 and parameters: {'subsample': 0.3631428306108071, 'dropout_rate': 0.5184650999753722, 'n_estimators': 289, 'learning_rate': 0.019705698270018484}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 09:29:16,842] Trial 39 finished with value: 0.6782864326462851 and parameters: {'subsample': 0.21082898345107914, 'dropout_rate': 0.22565165560333753, 'n_estimators': 235, 'learning_rate': 0.0666636052087898}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:29:21,736] Trial 40 finished with value: 0.6825886919704105 and parameters: {'subsample': 0.27409799996701123, 'dropout_rate': 0.6180501890220548, 'n_estimators': 158, 'learning_rate': 0.027238212287347824}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:29:37,252] Trial 41 finished with value: 0.6850932812629744 and parameters: {'subsample': 0.32995313596362325, 'dropout_rate': 0.2915942508190784, 'n_estimators': 348, 'learning_rate': 0.041736150429636736}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 09:29:56,946] Trial 42 finished with value: 0.6831635064113329 and parameters: {'subsample': 0.387949526807165, 'dropout_rate': 0.3499576045923318, 'n_estimators': 399, 'learning_rate': 0.03566287030311954}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 09:30:21,220] Trial 43 finished with value: 0.684007388267873 and parameters: {'subsample': 0.5541381723474943, 'dropout_rate': 0.1322736128020839, 'n_estimators': 459, 'learning_rate': 0.047169485046043555}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:30:27,821] Trial 44 finished with value: 0.6841024735474831 and parameters: {'subsample': 0.4739956054970109, 'dropout_rate': 0.3089648723925339, 'n_estimators': 195, 'learning_rate': 0.055120795493321134}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:30:39,877] Trial 45 finished with value: 0.6818815999065311 and parameters: {'subsample': 0.13910858216903038, 'dropout_rate': 0.7991522227764232, 'n_estimators': 335, 'learning_rate': 0.03400538573985265}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:30:52,225] Trial 46 finished with value: 0.6842493994064343 and parameters: {'subsample': 0.2801457720215478, 'dropout_rate': 0.2642877741444409, 'n_estimators': 304, 'learning_rate': 0.04169152050472783}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 09:31:00,059] Trial 47 finished with value: 0.6772984902238177 and parameters: {'subsample': 0.23491261018939397, 'dropout_rate': 0.21751283995297202, 'n_estimators': 219, 'learning_rate': 0.04882633024242143}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:31:16,442] Trial 48 finished with value: 0.6815218526915459 and parameters: {'subsample': 0.4588054933849818, 'dropout_rate': 0.39174954878460244, 'n_estimators': 385, 'learning_rate': 0.02491473366036642}. Best is trial 16 with value: 0.6855981769358904.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 09:31:31,106] Trial 49 finished with value: 0.6858853225401734 and parameters: {'subsample': 0.33379884845910957, 'dropout_rate': 0.156559660213791, 'n_estimators': 330, 'learning_rate': 0.0168251593655677}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:31:36,661] Trial 50 finished with value: 0.6848973801177062 and parameters: {'subsample': 0.5150535018207708, 'dropout_rate': 0.15047239779419277, 'n_estimators': 180, 'learning_rate': 0.00421449678956495}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 09:31:51,919] Trial 51 finished with value: 0.6850414406836334 and parameters: {'subsample': 0.31910943819014487, 'dropout_rate': 0.1818470729551736, 'n_estimators': 348, 'learning_rate': 0.016769783329425858}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:32:06,419] Trial 52 finished with value: 0.6841024735474831 and parameters: {'subsample': 0.3693776734290453, 'dropout_rate': 0.26671963338973725, 'n_estimators': 329, 'learning_rate': 0.007122913481934856}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:32:16,834] Trial 53 finished with value: 0.6830731061043034 and parameters: {'subsample': 0.6999265997500215, 'dropout_rate': 0.3281136712592989, 'n_estimators': 276, 'learning_rate': 0.01567783909312001}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:32:34,841] Trial 54 finished with value: 0.6842879591341229 and parameters: {'subsample': 0.34075360641702246, 'dropout_rate': 0.13581687783008112, 'n_estimators': 377, 'learning_rate': 0.029318435530556883}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 09:32:56,463] Trial 55 finished with value: 0.6851664475333237 and parameters: {'subsample': 0.2902596497170333, 'dropout_rate': 0.6116677856087096, 'n_estimators': 470, 'learning_rate': 0.02248885317953929}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7552742616033755
Fold 5 C-index: 0.6197183098591549
[I 2024-04-19 09:33:17,335] Trial 56 finished with value: 0.6814267674119356 and parameters: {'subsample': 0.3906409580146984, 'dropout_rate': 0.6342096197902003, 'n_estimators': 469, 'learning_rate': 0.006780416715406464}. Best is trial 49 with value: 0.6858853225401734.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:33:36,708] Trial 57 finished with value: 0.6842274803971735 and parameters: {'subsample': 0.24892868107560692, 'dropout_rate': 0.5954958976202265, 'n_estimators': 432, 'learning_rate': 0.020728278965199902}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:33:58,152] Trial 58 finished with value: 0.6842274803971735 and parameters: {'subsample': 0.28512964046701994, 'dropout_rate': 0.6693418112550454, 'n_estimators': 485, 'learning_rate': 0.012702314241540981}. Best is trial 49 with value: 0.6858853225401734.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:34:06,715] Trial 59 finished with value: 0.6889712913642418 and parameters: {'subsample': 0.20242575932269302, 'dropout_rate': 0.5421969302450425, 'n_estimators': 251, 'learning_rate': 0.0332916598506947}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 09:34:25,555] Trial 60 finished with value: 0.6844666262427109 and parameters: {'subsample': 0.1984841594269347, 'dropout_rate': 0.7990647650248779, 'n_estimators': 451, 'learning_rate': 0.03338956702994945}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:34:35,357] Trial 61 finished with value: 0.683683954910673 and parameters: {'subsample': 0.14796471332909983, 'dropout_rate': 0.4838214699414214, 'n_estimators': 256, 'learning_rate': 0.028030796010083882}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:34:43,069] Trial 62 finished with value: 0.6854887229126241 and parameters: {'subsample': 0.11608035843979618, 'dropout_rate': 0.5290014376557277, 'n_estimators': 230, 'learning_rate': 0.022869494938231934}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:34:51,136] Trial 63 finished with value: 0.6853522126123014 and parameters: {'subsample': 0.12834405012610542, 'dropout_rate': 0.5522467149325495, 'n_estimators': 241, 'learning_rate': 0.022493032896608565}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:34:58,366] Trial 64 finished with value: 0.6861989597618654 and parameters: {'subsample': 0.12100855146795174, 'dropout_rate': 0.5431094475423189, 'n_estimators': 222, 'learning_rate': 0.01914733122737817}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:35:05,793] Trial 65 finished with value: 0.6845083307557613 and parameters: {'subsample': 0.13039718572400497, 'dropout_rate': 0.538778510278355, 'n_estimators': 225, 'learning_rate': 0.023075310711980518}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:35:12,131] Trial 66 finished with value: 0.6845083307557613 and parameters: {'subsample': 0.10852389386023417, 'dropout_rate': 0.6884114659596392, 'n_estimators': 207, 'learning_rate': 0.015492015837864206}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:35:18,267] Trial 67 finished with value: 0.6828400730541329 and parameters: {'subsample': 0.17357014061408943, 'dropout_rate': 0.5741208111648264, 'n_estimators': 199, 'learning_rate': 0.019001299840511375}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:35:28,934] Trial 68 finished with value: 0.6772742992397853 and parameters: {'subsample': 0.2134098905302746, 'dropout_rate': 0.4758324497703306, 'n_estimators': 287, 'learning_rate': 0.009867393278798327}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:35:41,083] Trial 69 finished with value: 0.6854011878986185 and parameters: {'subsample': 0.12959530222318535, 'dropout_rate': 0.5025414532400496, 'n_estimators': 312, 'learning_rate': 0.023481633619148467}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:35:48,895] Trial 70 finished with value: 0.6853522126123014 and parameters: {'subsample': 0.13155683386269787, 'dropout_rate': 0.5332362990714898, 'n_estimators': 236, 'learning_rate': 0.014009141309046687}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:36:00,742] Trial 71 finished with value: 0.6862450697551585 and parameters: {'subsample': 0.11886130189930208, 'dropout_rate': 0.5440918717009253, 'n_estimators': 318, 'learning_rate': 0.013939210798663624}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 09:36:12,607] Trial 72 finished with value: 0.6791792897891422 and parameters: {'subsample': 0.1661009316579267, 'dropout_rate': 0.5058258051591118, 'n_estimators': 313, 'learning_rate': 0.0012883073478823365}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:36:23,556] Trial 73 finished with value: 0.6862450697551585 and parameters: {'subsample': 0.11853524848924768, 'dropout_rate': 0.5547469970849755, 'n_estimators': 301, 'learning_rate': 0.017794101079834042}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:36:34,223] Trial 74 finished with value: 0.6821131954864639 and parameters: {'subsample': 0.10089265797410693, 'dropout_rate': 0.5931554417807641, 'n_estimators': 283, 'learning_rate': 0.01015081288480469}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7172995780590717

Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:36:47,590] Trial 75 finished with value: 0.6764084983739845 and parameters: {'subsample': 0.18796166323860544, 'dropout_rate': 0.42716475861702957, 'n_estimators': 318, 'learning_rate': 0.004397831014632836}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:36:57,535] Trial 76 finished with value: 0.6819472159112758 and parameters: {'subsample': 0.15448212024810162, 'dropout_rate': 0.449350356472916, 'n_estimators': 269, 'learning_rate': 0.01818184806545427}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:37:12,742] Trial 77 finished with value: 0.6845958657697669 and parameters: {'subsample': 0.1208346395933577, 'dropout_rate': 0.49230197286519484, 'n_estimators': 361, 'learning_rate': 0.025512570062193523}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:37:24,076] Trial 78 finished with value: 0.683634979624356 and parameters: {'subsample': 0.18819110052442745, 'dropout_rate': 0.5558731588510241, 'n_estimators': 302, 'learning_rate': 0.007714402729458329}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6291079812206573
[I 2024-04-19 09:37:35,782] Trial 79 finished with value: 0.6826837772500205 and parameters: {'subsample': 0.21582770040734545, 'dropout_rate': 0.6526929866875516, 'n_estimators': 327, 'learning_rate': 0.03074529069965677}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:37:47,258] Trial 80 finished with value: 0.6819472159112758 and parameters: {'subsample': 0.159111173604474, 'dropout_rate': 0.45513247295304177, 'n_estimators': 298, 'learning_rate': 0.013611794111417101}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:37:55,301] Trial 81 finished with value: 0.6853522126123014 and parameters: {'subsample': 0.13231825451477652, 'dropout_rate': 0.526254762713732, 'n_estimators': 241, 'learning_rate': 0.02123225963936754}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:38:01,404] Trial 82 finished with value: 0.6845083307557613 and parameters: {'subsample': 0.11306268329275732, 'dropout_rate': 0.565247896938647, 'n_estimators': 189, 'learning_rate': 0.023853373361298266}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:38:08,088] Trial 83 finished with value: 0.6851203375400308 and parameters: {'subsample': 0.2425906955157005, 'dropout_rate': 0.5974523531664861, 'n_estimators': 220, 'learning_rate': 0.018835960693965557}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:38:15,736] Trial 84 finished with value: 0.6827525380401273 and parameters: {'subsample': 0.14298324427395268, 'dropout_rate': 0.7218544301099536, 'n_estimators': 247, 'learning_rate': 0.027024971340993544}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:38:25,143] Trial 85 finished with value: 0.683634979624356 and parameters: {'subsample': 0.18432322738305698, 'dropout_rate': 0.5337091739141145, 'n_estimators': 270, 'learning_rate': 0.015962370158925196}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:38:36,894] Trial 86 finished with value: 0.6845958657697669 and parameters: {'subsample': 0.11718591218429616, 'dropout_rate': 0.9466587881139311, 'n_estimators': 353, 'learning_rate': 0.010393246430019452}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:38:44,547] Trial 87 finished with value: 0.683634979624356 and parameters: {'subsample': 0.15366485952498626, 'dropout_rate': 0.5064618702961672, 'n_estimators': 228, 'learning_rate': 0.004313929934029402}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 09:39:02,082] Trial 88 finished with value: 0.6844666262427109 and parameters: {'subsample': 0.20196672022971585, 'dropout_rate': 0.5515134188806337, 'n_estimators': 390, 'learning_rate': 0.024099543252977373}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6525821596244131
[I 2024-04-19 09:39:07,209] Trial 89 finished with value: 0.6819057908905632 and parameters: {'subsample': 0.10075247655597118, 'dropout_rate': 0.3807798074753591, 'n_estimators': 151, 'learning_rate': 0.021034521816314253}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:39:24,960] Trial 90 finished with value: 0.6842274803971735 and parameters: {'subsample': 0.23047313547139664, 'dropout_rate': 0.6398086088998653, 'n_estimators': 416, 'learning_rate': 0.017608885600324867}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:39:33,744] Trial 91 finished with value: 0.6853061026190084 and parameters: {'subsample': 0.13425837379150862, 'dropout_rate': 0.577918825677845, 'n_estimators': 253, 'learning_rate': 0.013996917816922989}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:39:41,417] Trial 92 finished with value: 0.6845768120535302 and parameters: {'subsample': 0.1716246658271949, 'dropout_rate': 0.5347065441728538, 'n_estimators': 234, 'learning_rate': 0.01200347272744925}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6338028169014085
[I 2024-04-19 09:39:53,119] Trial 93 finished with value: 0.6808670535022223 and parameters: {'subsample': 0.13823377177382926, 'dropout_rate': 0.4704954294320032, 'n_estimators': 308, 'learning_rate': 0.014877947639538175}. Best is trial 59 with value: 0.6889712913642418.

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:40:03,641] Trial 94 finished with value: 0.6853061026190084 and parameters: {'subsample': 0.1232259608873817, 'dropout_rate': 0.6199730739701872, 'n_estimators': 290, 'learning_rate': 0.019449331648383892}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:40:09,767] Trial 95 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.7904534140423415, 'dropout_rate': 0.49636602351726383, 'n_estimators': 207, 'learning_rate': 0.006884325386238411}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:40:18,444] Trial 96 finished with value: 0.677115869930202 and parameters: {'subsample': 0.17541731772888014, 'dropout_rate': 0.4403183330151242, 'n_estimators': 247, 'learning_rate': 0.02617236225408604}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.647887323943662
[I 2024-04-19 09:40:30,863] Trial 97 finished with value: 0.6818596808972701 and parameters: {'subsample': 0.15096646901274413, 'dropout_rate': 0.520512564675783, 'n_estimators': 321, 'learning_rate': 0.03313474017582292}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:40:36,445] Trial 98 finished with value: 0.6825886919704105 and parameters: {'subsample': 0.26497556177098114, 'dropout_rate': 0.5501236466994853, 'n_estimators': 185, 'learning_rate': 0.03646335112689174}. Best is trial 59 with value: 0.6889712913642418.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.7721518987341772

[I 2024-04-19 09:40:44,872] A new study created in memory with name: no-name-5ec89bae-d7aa-406e-88c7-0c0d3aa9eb2d

Fold 5 C-index: 0.6244131455399061
[I 2024-04-19 09:40:44,855] Trial 99 finished with value: 0.6847608698173835 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.5989561549127228, 'n_estimators': 263, 'learning_rate': 0.022081857425899597}. Best is trial 59 with value: 0.6889712913642418.


* Best trial for C-index:
 FrozenTrial(number=59, state=TrialState.COMPLETE, values=[0.6889712913642418], datetime_start=datetime.datetime(2024, 4, 19, 9, 33, 58, 159081), datetime_complete=datetime.datetime(2024, 4, 19, 9, 34, 6, 714604), params={'subsample': 0.20242575932269302, 'dropout_rate': 0.5421969302450425, 'n_estimators': 251, 'learning_rate': 0.0332916598506947}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=59, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.20242575932269302, 'dropout_rate': 0.5421969302450425, 'n_estimators': 251, 'learning_rate': 0.0332916598506947}


* Best Score for C-index:
 0.6889712913642418

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2224371243647886
Fold 2 IBS: 0.19317332913894678
Fold 3 IBS: 0.18175388084440755
Fold 4 IBS: 0.19244381929374016
Fold 5 IBS: 0.2895470556233037
[I 2024-04-19 09:40:47,989] Trial 0 finished with value: 0.21587104185303735 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.24671279381337202
Fold 2 IBS: 0.29825563341910016
Fold 3 IBS: 0.22274079495378193
Fold 4 IBS: 0.2992450056446656
Fold 5 IBS: 0.3807985230506669
[I 2024-04-19 09:41:11,610] Trial 1 finished with value: 0.28955055017631737 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.23108469847085208
Fold 2 IBS: 0.2336848295780041
Fold 3 IBS: 0.18494628590086665
Fold 4 IBS: 0.22195970987072647
Fold 5 IBS: 0.34828871064569805
[I 2024-04-19 09:41:17,218] Trial 2 finished with value: 0.24399284689322945 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.23157554398476274
Fold 2 IBS: 0.23143286367095128
Fold 3 IBS: 0.18256067353122335
Fold 4 IBS: 0.23846682563036353
Fold 5 IBS: 0.3508974125718185
[I 2024-04-19 09:41:24,626] Trial 3 finished with value: 0.2469866638778239 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.23265002745306723
Fold 2 IBS: 0.2357058090135899
Fold 3 IBS: 0.18205382773702086
Fold 4 IBS: 0.24410614290530402
Fold 5 IBS: 0.3535026706006858
[I 2024-04-19 09:41:34,860] Trial 4 finished with value: 0.24960369554193357 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.24128998792103662
Fold 2 IBS: 0.2762997787521807
Fold 3 IBS: 0.20025811559513157
Fold 4 IBS: 0.26546816179349464
Fold 5 IBS: 0.3725504924440945
[I 2024-04-19 09:41:46,491] Trial 5 finished with value: 0.2711733073011876 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.21587104185303735.
Fold 1 IBS: 0.21068463318276223
Fold 2 IBS: 0.18684500549023667
Fold 3 IBS: 0.17566720250103562
Fold 4 IBS: 0.189966463145634
Fold 5 IBS: 0.2632777024308626
[I 2024-04-19 09:41:51,889] Trial 6 finished with value: 0.20528820135010623 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20528820135010623.
Fold 1 IBS: 0.19893358640106418
Fold 2 IBS: 0.19480655197258015
Fold 3 IBS: 0.17781694236500464
Fold 4 IBS: 0.2013110478330258
Fold 5 IBS: 0.22988057976140916
[I 2024-04-19 09:41:53,424] Trial 7 finished with value: 0.2005497416666168 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22411588363673707
Fold 2 IBS: 0.19395660599165604
Fold 3 IBS: 0.1838931084018872
Fold 4 IBS: 0.19659222258901207
Fold 5 IBS: 0.29713134944437064
[I 2024-04-19 09:42:00,097] Trial 8 finished with value: 0.21913783401273262 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.24215194796114747
Fold 2 IBS: 0.2795582542494505
Fold 3 IBS: 0.2021738805487265
Fold 4 IBS: 0.268679491816033
Fold 5 IBS: 0.37379244274565304
[I 2024-04-19 09:42:17,692] Trial 9 finished with value: 0.2732712034642021 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2133777392595339
Fold 2 IBS: 0.22075911663973774
Fold 3 IBS: 0.20362701953372184
Fold 4 IBS: 0.2240281500374084
Fold 5 IBS: 0.21809863906487453
[I 2024-04-19 09:42:18,960] Trial 10 finished with value: 0.21597813290705528 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21288380226283657
Fold 2 IBS: 0.22032322957937875
Fold 3 IBS: 0.2042745608511555
Fold 4 IBS: 0.22410217190422801
Fold 5 IBS: 0.21809281059218802
[I 2024-04-19 09:42:19,925] Trial 11 finished with value: 0.21593531503795735 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22944247263535614
Fold 2 IBS: 0.20765472579544875
Fold 3 IBS: 0.1855396229358887
Fold 4 IBS: 0.21344387061271705
Fold 5 IBS: 0.3318352940522482
[I 2024-04-19 09:42:22,777] Trial 12 finished with value: 0.23358319720633175 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2290028773230912
Fold 2 IBS: 0.21252645480254392
Fold 3 IBS: 0.1855329634191624
Fold 4 IBS: 0.2057484889693888
Fold 5 IBS: 0.326385787266454
[I 2024-04-19 09:42:34,204] Trial 13 finished with value: 0.23183931435612806 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2005833169532511
Fold 2 IBS: 0.2008374330432463
Fold 3 IBS: 0.18240897572139836
Fold 4 IBS: 0.20640866347396433
Fold 5 IBS: 0.2237482380656478
[I 2024-04-19 09:42:37,019] Trial 14 finished with value: 0.20279732545150156 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2100788008631381
Fold 2 IBS: 0.2165116314827259
Fold 3 IBS: 0.19904919834791537
Fold 4 IBS: 0.22105344434847998
Fold 5 IBS: 0.2181778394270942
[I 2024-04-19 09:42:39,247] Trial 15 finished with value: 0.2129741828938707 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2047752320765482
Fold 2 IBS: 0.20805178791278306
Fold 3 IBS: 0.1902278421564896
Fold 4 IBS: 0.21388284815653996
Fold 5 IBS: 0.21967933702448122
[I 2024-04-19 09:42:41,106] Trial 16 finished with value: 0.20732340946536837 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21549515107667103
Fold 2 IBS: 0.18788613695948134
Fold 3 IBS: 0.17820999898175136
Fold 4 IBS: 0.1900257147184032
Fold 5 IBS: 0.27413215537692803
[I 2024-04-19 09:42:44,682] Trial 17 finished with value: 0.20914983142264704 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21636303175596067
Fold 2 IBS: 0.18768401418830014
Fold 3 IBS: 0.1800307888892072
Fold 4 IBS: 0.19399500745388318
Fold 5 IBS: 0.276083877120051
[I 2024-04-19 09:42:56,069] Trial 18 finished with value: 0.21083134388148045 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.1984667375758634

Fold 2 IBS: 0.19581322731122527
Fold 3 IBS: 0.18012266008596378
Fold 4 IBS: 0.2080662242520272
Fold 5 IBS: 0.228727148642183
[I 2024-04-19 09:42:57,795] Trial 19 finished with value: 0.20223919957345254 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.19900268568861765
Fold 2 IBS: 0.19673124531818784
Fold 3 IBS: 0.18097673731541652
Fold 4 IBS: 0.20623674025628727
Fold 5 IBS: 0.22394152158247504
[I 2024-04-19 09:42:59,521] Trial 20 finished with value: 0.20137778603219686 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20102182120527576
Fold 2 IBS: 0.20177601792835187
Fold 3 IBS: 0.1880831686670229
Fold 4 IBS: 0.21737450486532756
Fold 5 IBS: 0.22131729031914832
[I 2024-04-19 09:43:00,998] Trial 21 finished with value: 0.20591456059702526 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2124646743569866
Fold 2 IBS: 0.22042523088546775
Fold 3 IBS: 0.2025909014053614
Fold 4 IBS: 0.2235691020770519
Fold 5 IBS: 0.21809103495193327
[I 2024-04-19 09:43:02,028] Trial 22 finished with value: 0.21542818873536018 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.21862277197658694
Fold 2 IBS: 0.18332269702089818
Fold 3 IBS: 0.18399636284561172
Fold 4 IBS: 0.20418493060437545
Fold 5 IBS: 0.2808037945631659
[I 2024-04-19 09:43:06,089] Trial 23 finished with value: 0.21418611140212765 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20491067601921656
Fold 2 IBS: 0.18740598066657257
Fold 3 IBS: 0.17465020553120653
Fold 4 IBS: 0.1941870846020327
Fold 5 IBS: 0.24866689726201885
[I 2024-04-19 09:43:07,784] Trial 24 finished with value: 0.20196416881620943 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22216629666753407
Fold 2 IBS: 0.19060249929699566
Fold 3 IBS: 0.1817624831102358
Fold 4 IBS: 0.19525170860969823
Fold 5 IBS: 0.28582833839045163
[I 2024-04-19 09:43:09,761] Trial 25 finished with value: 0.21512226521498307 and parameters: {'subsample': 0.39649741038083114, 'dropout_rate': 0.9011181177707686, 'n_estimators': 70, 'learning_rate': 0.08579428551722094}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2292652379408988
Fold 2 IBS: 0.21328570806551253
Fold 3 IBS: 0.18524706089498968
Fold 4 IBS: 0.21037011829159993
Fold 5 IBS: 0.33075206466524854
[I 2024-04-19 09:43:13,862] Trial 26 finished with value: 0.2337840379716499 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.7428521025450486, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.24292657838565376
Fold 2 IBS: 0.27765564122267306
Fold 3 IBS: 0.1965459221233886
Fold 4 IBS: 0.27293041494917186
Fold 5 IBS: 0.3766083819755308
[I 2024-04-19 09:43:29,966] Trial 27 finished with value: 0.27333338773128363 and parameters: {'subsample': 0.25017268379052987, 'dropout_rate': 0.8368873118701377, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.23011061167903255
Fold 2 IBS: 0.2218173694627172
Fold 3 IBS: 0.1846219976211082
Fold 4 IBS: 0.21774372942926154
Fold 5 IBS: 0.33874338539432947
[I 2024-04-19 09:43:36,816] Trial 28 finished with value: 0.2386074187172898 and parameters: {'subsample': 0.32549498689313283, 'dropout_rate': 0.9187406138362325, 'n_estimators': 236, 'learning_rate': 0.046726352221374515}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.22753595132167745
Fold 2 IBS: 0.20249716167749232
Fold 3 IBS: 0.18520370978507786
Fold 4 IBS: 0.19929228608349597
Fold 5 IBS: 0.31324840664297765
[I 2024-04-19 09:43:39,901] Trial 29 finished with value: 0.22555550310214426 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.528113503868086, 'n_estimators': 98, 'learning_rate': 0.08423642007181871}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2253452656038164
Fold 2 IBS: 0.188831488272457
Fold 3 IBS: 0.1894267642776359
Fold 4 IBS: 0.21084453751232646
Fold 5 IBS: 0.30052403445526077
[I 2024-04-19 09:43:43,898] Trial 30 finished with value: 0.2229944180242993 and parameters: {'subsample': 0.18603736202301935, 'dropout_rate': 0.6813568533831397, 'n_estimators': 131, 'learning_rate': 0.05802531255595394}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.19833758538279453
Fold 2 IBS: 0.1940020524879146
Fold 3 IBS: 0.18459430443696237
Fold 4 IBS: 0.2096206578233813
Fold 5 IBS: 0.22666021808265216
[I 2024-04-19 09:43:45,634] Trial 31 finished with value: 0.202642963642741 and parameters: {'subsample': 0.13178840570553013, 'dropout_rate': 0.974912474343522, 'n_estimators': 42, 'learning_rate': 0.04796619662341173}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.19895154376305535
Fold 2 IBS: 0.1971961089866832
Fold 3 IBS: 0.17946858446419894
Fold 4 IBS: 0.2055509964621163
Fold 5 IBS: 0.22679100620232656
[I 2024-04-19 09:43:47,450] Trial 32 finished with value: 0.20159164797567608 and parameters: {'subsample': 0.2663212387057611, 'dropout_rate': 0.791102993543661, 'n_estimators': 50, 'learning_rate': 0.035458087225080745}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20024695169682136
Fold 2 IBS: 0.18939916557837946
Fold 3 IBS: 0.17571446824416467
Fold 4 IBS: 0.20025143315267666
Fold 5 IBS: 0.23849736004290123
[I 2024-04-19 09:43:50,144] Trial 33 finished with value: 0.2008218757429887 and parameters: {'subsample': 0.28375960802245515, 'dropout_rate': 0.7724416054749447, 'n_estimators': 85, 'learning_rate': 0.031317710466820706}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.20190374206513476
Fold 2 IBS: 0.18659988482318876
Fold 3 IBS: 0.17537182001884782
Fold 4 IBS: 0.20002486596442334
Fold 5 IBS: 0.24378253012810414
[I 2024-04-19 09:43:52,926] Trial 34 finished with value: 0.2015365685999398 and parameters: {'subsample': 0.2692662272345522, 'dropout_rate': 0.7720700330888676, 'n_estimators': 96, 'learning_rate': 0.032157467810215834}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.2061573289314405
Fold 2 IBS: 0.18308063611650024
Fold 3 IBS: 0.17645812014909326
Fold 4 IBS: 0.1976608025630094
Fold 5 IBS: 0.25304005480349206
[I 2024-04-19 09:43:57,901] Trial 35 finished with value: 0.2032793885127071 and parameters: {'subsample': 0.23406275629450798, 'dropout_rate': 0.5856891687807478, 'n_estimators': 167, 'learning_rate': 0.023048782790281344}. Best is trial 7 with value: 0.2005497416666168.
Fold 1 IBS: 0.1995176120322553
Fold 2 IBS: 0.1916289417043371
Fold 3 IBS: 0.17634370275909048
Fold 4 IBS: 0.20064388725831098
Fold 5 IBS: 0.23452454352588636
[I 2024-04-19 09:44:00,492] Trial 36 finished with value: 0.20053173745597602 and parameters: {'subsample': 0.3079529125404247, 'dropout_rate': 0.7451770945587517, 'n_estimators': 91, 'learning_rate': 0.02664320713072585}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20613254936180075
Fold 2 IBS: 0.21070580029601446
Fold 3 IBS: 0.19201164359217274
Fold 4 IBS: 0.21530311678503808
Fold 5 IBS: 0.2190529350806702
[I 2024-04-19 09:44:01,806] Trial 37 finished with value: 0.20864120902313923 and parameters: {'subsample': 0.4453495437188899, 'dropout_rate': 0.48858816459860266, 'n_estimators': 22, 'learning_rate': 0.028811820403570124}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.19858942493964413
Fold 2 IBS: 0.19656092487140125

Fold 3 IBS: 0.1822935200256659
Fold 4 IBS: 0.2097335127069102
Fold 5 IBS: 0.22465026642731892
[I 2024-04-19 09:44:04,219] Trial 38 finished with value: 0.20236552979418806 and parameters: {'subsample': 0.17017303600682596, 'dropout_rate': 0.6744028301161138, 'n_estimators': 84, 'learning_rate': 0.02105811333204098}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.2293570713772131
Fold 2 IBS: 0.21090831309405633
Fold 3 IBS: 0.1854937460956396
Fold 4 IBS: 0.2135188317245189
Fold 5 IBS: 0.3310658823973223
[I 2024-04-19 09:44:09,535] Trial 39 finished with value: 0.23406876893775003 and parameters: {'subsample': 0.3439557983328422, 'dropout_rate': 0.844167451106476, 'n_estimators': 194, 'learning_rate': 0.051973238153326454}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.21206377067603904
Fold 2 IBS: 0.1864274650720211
Fold 3 IBS: 0.17644966324602238
Fold 4 IBS: 0.19294957610953867
Fold 5 IBS: 0.2664281407354722
[I 2024-04-19 09:44:13,281] Trial 40 finished with value: 0.20686372316781867 and parameters: {'subsample': 0.548888469715097, 'dropout_rate': 0.27073406810212547, 'n_estimators': 125, 'learning_rate': 0.03592906349335382}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.19870888593455063
Fold 2 IBS: 0.19592332852462746
Fold 3 IBS: 0.1801814151183319
Fold 4 IBS: 0.20547482085306887
Fold 5 IBS: 0.22780394191799094
[I 2024-04-19 09:44:16,044] Trial 41 finished with value: 0.20161847846971398 and parameters: {'subsample': 0.25669644622473264, 'dropout_rate': 0.7637125910183031, 'n_estimators': 96, 'learning_rate': 0.01975292785105187}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20838776678662158
Fold 2 IBS: 0.18458876507607672
Fold 3 IBS: 0.17622427787792194
Fold 4 IBS: 0.19577750517111836
Fold 5 IBS: 0.2592881055896767
[I 2024-04-19 09:44:20,341] Trial 42 finished with value: 0.20485328410028308 and parameters: {'subsample': 0.318913417614635, 'dropout_rate': 0.6954623000860509, 'n_estimators': 155, 'learning_rate': 0.026680268344183765}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20581884982167936
Fold 2 IBS: 0.21100985371559966
Fold 3 IBS: 0.19204077392894559
Fold 4 IBS: 0.21581842461339115
Fold 5 IBS: 0.2194124220515187
[I 2024-04-19 09:44:21,514] Trial 43 finished with value: 0.20882006482622692 and parameters: {'subsample': 0.27766830774246254, 'dropout_rate': 0.7378843308551086, 'n_estimators': 21, 'learning_rate': 0.03236373140691688}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.211373898868855
Fold 2 IBS: 0.18197417827746332
Fold 3 IBS: 0.1795094750790974
Fold 4 IBS: 0.20080705853626143
Fold 5 IBS: 0.26049311453387325
[I 2024-04-19 09:44:24,912] Trial 44 finished with value: 0.20683154505911006 and parameters: {'subsample': 0.29218877081350936, 'dropout_rate': 0.12176369536773762, 'n_estimators': 111, 'learning_rate': 0.04450424844427492}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.2081058656945365
Fold 2 IBS: 0.18342757569088866
Fold 3 IBS: 0.1803744362520886
Fold 4 IBS: 0.20369940084704236
Fold 5 IBS: 0.2529963370999858
[I 2024-04-19 09:44:27,249] Trial 45 finished with value: 0.2057207231169084 and parameters: {'subsample': 0.1595465697102985, 'dropout_rate': 0.810409547267725, 'n_estimators': 75, 'learning_rate': 0.05514452912306929}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.21244834619002742
Fold 2 IBS: 0.22002682487467506
Fold 3 IBS: 0.20230908770197017
Fold 4 IBS: 0.22323550260132452
Fold 5 IBS: 0.21808679037848674
[I 2024-04-19 09:44:28,276] Trial 46 finished with value: 0.21522131034929676 and parameters: {'subsample': 0.46900532967733044, 'dropout_rate': 0.6411889920335619, 'n_estimators': 3, 'learning_rate': 0.03359936538613975}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.1989674980171421
Fold 2 IBS: 0.19596922449831902
Fold 3 IBS: 0.17917972111143207
Fold 4 IBS: 0.20356056552271987
Fold 5 IBS: 0.22777485709313988
[I 2024-04-19 09:44:34,715] Trial 47 finished with value: 0.20109037324855059 and parameters: {'subsample': 0.3543985160964519, 'dropout_rate': 0.8704597969866263, 'n_estimators': 221, 'learning_rate': 0.008209618821055878}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.1988087509281216
Fold 2 IBS: 0.194809116140053
Fold 3 IBS: 0.1783178863545788
Fold 4 IBS: 0.20300899074823334
Fold 5 IBS: 0.22939290034831902
[I 2024-04-19 09:44:40,841] Trial 48 finished with value: 0.20086752890386114 and parameters: {'subsample': 0.34997900922070224, 'dropout_rate': 0.8583767544982763, 'n_estimators': 221, 'learning_rate': 0.008866449400387288}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.20026714131029694
Fold 2 IBS: 0.19996746721066921
Fold 3 IBS: 0.18245881898731398
Fold 4 IBS: 0.20712070721836112
Fold 5 IBS: 0.22383992788618978
[I 2024-04-19 09:44:48,961] Trial 49 finished with value: 0.2027308125225662 and parameters: {'subsample': 0.360958249405207, 'dropout_rate': 0.8740409706839273, 'n_estimators': 272, 'learning_rate': 0.00524351186486742}. Best is trial 36 with value: 0.20053173745597602.
Fold 1 IBS: 0.1990464452126766
Fold 2 IBS: 0.19231535356119261
Fold 3 IBS: 0.17640198836658966
Fold 4 IBS: 0.20083441062240975
Fold 5 IBS: 0.23260537265893996
[I 2024-04-19 09:44:55,195] Trial 50 finished with value: 0.2002407140843617 and parameters: {'subsample': 0.4373334297322835, 'dropout_rate': 0.9260233690194004, 'n_estimators': 226, 'learning_rate': 0.009590101642146711}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.201300346521472
Fold 2 IBS: 0.20187803014855335
Fold 3 IBS: 0.1844251452029284
Fold 4 IBS: 0.20932018063125366
Fold 5 IBS: 0.2225022640449257
[I 2024-04-19 09:45:01,585] Trial 51 finished with value: 0.20388519330982663 and parameters: {'subsample': 0.43083736341534906, 'dropout_rate': 0.9404007957184433, 'n_estimators': 228, 'learning_rate': 0.005306046137852891}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20199374520220834
Fold 2 IBS: 0.18741848520066026
Fold 3 IBS: 0.17497519063844968
Fold 4 IBS: 0.19634461287889246
Fold 5 IBS: 0.24449705546360098
[I 2024-04-19 09:45:10,413] Trial 52 finished with value: 0.20104581787676232 and parameters: {'subsample': 0.3681476442942809, 'dropout_rate': 0.8660885032854598, 'n_estimators': 284, 'learning_rate': 0.010879916649294472}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20544662432868555
Fold 2 IBS: 0.18672034859852907
Fold 3 IBS: 0.17472120028561494
Fold 4 IBS: 0.19316436687777605
Fold 5 IBS: 0.2517371644954932
[I 2024-04-19 09:45:21,594] Trial 53 finished with value: 0.20235794091721973 and parameters: {'subsample': 0.48900242562477936, 'dropout_rate': 0.8299583658948217, 'n_estimators': 335, 'learning_rate': 0.010670184521637897}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21094194920642484
Fold 2 IBS: 0.18559765775758102
Fold 3 IBS: 0.17643861381451179
Fold 4 IBS: 0.19409856772983944
Fold 5 IBS: 0.26140960735797286
[I 2024-04-19 09:45:29,538] Trial 54 finished with value: 0.205697279173266 and parameters: {'subsample': 0.37369693855918124, 'dropout_rate': 0.944656111823258, 'n_estimators': 271, 'learning_rate': 0.015564937079776901}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21979660617383143
Fold 2 IBS: 0.1892262703859355
Fold 3 IBS: 0.18156404701635165
Fold 4 IBS: 0.19336168043363092
Fold 5 IBS: 0.28460738586913
[I 2024-04-19 09:45:38,998] Trial 55 finished with value: 0.2137111979757759 and parameters: {'subsample': 0.44271112931064716, 'dropout_rate': 0.7139725161317707, 'n_estimators': 291, 'learning_rate': 0.019874419509118953}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.209631736413387
Fold 2 IBS: 0.2155994032197187
Fold 3 IBS: 0.19791952673985064
Fold 4 IBS: 0.21979375188696387
Fold 5 IBS: 0.2182561011891302
[I 2024-04-19 09:45:48,753] Trial 56 finished with value: 0.21224010388981007 and parameters: {'subsample': 0.5030867670027215, 'dropout_rate': 0.8693983003771366, 'n_estimators': 320, 'learning_rate': 0.0010380687366828949}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19885615519176145
Fold 2 IBS: 0.19483646447298053

Fold 3 IBS: 0.17849049434659467
Fold 4 IBS: 0.20302608352234905
Fold 5 IBS: 0.22884938440987548
[I 2024-04-19 09:45:57,646] Trial 57 finished with value: 0.20081171638871226 and parameters: {'subsample': 0.31114891339062667, 'dropout_rate': 0.6489378315882792, 'n_estimators': 251, 'learning_rate': 0.007801704420672669}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.2180531959388824
Fold 2 IBS: 0.1850434781595872
Fold 3 IBS: 0.18125157795710164
Fold 4 IBS: 0.1957099312923242
Fold 5 IBS: 0.2808496755196348
[I 2024-04-19 09:46:04,260] Trial 58 finished with value: 0.21218157177350605 and parameters: {'subsample': 0.3221818826721476, 'dropout_rate': 0.5833347466815137, 'n_estimators': 202, 'learning_rate': 0.027679523779857756}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21120995027458148
Fold 2 IBS: 0.1838676821243201
Fold 3 IBS: 0.17761827785583964
Fold 4 IBS: 0.1945128293118185
Fold 5 IBS: 0.2635788119779368
[I 2024-04-19 09:46:12,678] Trial 59 finished with value: 0.20615751030889928 and parameters: {'subsample': 0.2996242069065176, 'dropout_rate': 0.6192368181246879, 'n_estimators': 251, 'learning_rate': 0.017802575785705377}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19866191713016035
Fold 2 IBS: 0.19513258472618417
Fold 3 IBS: 0.17997492062652226
Fold 4 IBS: 0.2040192033824718
Fold 5 IBS: 0.2270852380927582
[I 2024-04-19 09:46:20,546] Trial 60 finished with value: 0.20097477279161935 and parameters: {'subsample': 0.22455927919482993, 'dropout_rate': 0.5527446724622991, 'n_estimators': 248, 'learning_rate': 0.007693689744162442}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19860339599320959
Fold 2 IBS: 0.19277322392050603
Fold 3 IBS: 0.17858572035004985
Fold 4 IBS: 0.20247218732304564
Fold 5 IBS: 0.2292468009724076
[I 2024-04-19 09:46:29,250] Trial 61 finished with value: 0.20033626571184376 and parameters: {'subsample': 0.21909136776287286, 'dropout_rate': 0.5515385173674032, 'n_estimators': 253, 'learning_rate': 0.008495962988587152}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19845171225113126
Fold 2 IBS: 0.1910629687358273
Fold 3 IBS: 0.17791413908896317
Fold 4 IBS: 0.20292503438373793
Fold 5 IBS: 0.2316698048652442
[I 2024-04-19 09:46:35,183] Trial 62 finished with value: 0.20040473186498073 and parameters: {'subsample': 0.21070703060386461, 'dropout_rate': 0.6557587421398771, 'n_estimators': 186, 'learning_rate': 0.012461426370993078}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.1990233809674153
Fold 2 IBS: 0.18981340202816493
Fold 3 IBS: 0.17717340767054812
Fold 4 IBS: 0.2011374888060369
Fold 5 IBS: 0.2347508961193226
[I 2024-04-19 09:46:40,969] Trial 63 finished with value: 0.20037971511829755 and parameters: {'subsample': 0.2269261019756698, 'dropout_rate': 0.6600763787957576, 'n_estimators': 190, 'learning_rate': 0.013211594928327765}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.1990378316602107
Fold 2 IBS: 0.18966900674368065
Fold 3 IBS: 0.17950670204654398
Fold 4 IBS: 0.2039737820766132
Fold 5 IBS: 0.23182454501582786
[I 2024-04-19 09:46:46,411] Trial 64 finished with value: 0.20080237350857527 and parameters: {'subsample': 0.18726116090476716, 'dropout_rate': 0.6507886461152487, 'n_estimators': 182, 'learning_rate': 0.01349521306943945}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19933572164505922
Fold 2 IBS: 0.19032048584858532
Fold 3 IBS: 0.1783454061665879
Fold 4 IBS: 0.2046808915453473
Fold 5 IBS: 0.2335285176591034
[I 2024-04-19 09:46:52,290] Trial 65 finished with value: 0.2012422045729366 and parameters: {'subsample': 0.1989323413578517, 'dropout_rate': 0.48561639379475857, 'n_estimators': 189, 'learning_rate': 0.013028047850482744}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.208728868674151
Fold 2 IBS: 0.18226176514893502
Fold 3 IBS: 0.17724578832700771
Fold 4 IBS: 0.1978503091117691
Fold 5 IBS: 0.25808759858754554
[I 2024-04-19 09:46:57,448] Trial 66 finished with value: 0.20483486596988168 and parameters: {'subsample': 0.2329869246327621, 'dropout_rate': 0.5270149291863772, 'n_estimators': 172, 'learning_rate': 0.024491890262711834}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.1988404602160198
Fold 2 IBS: 0.19061465686948595
Fold 3 IBS: 0.1794349557403622
Fold 4 IBS: 0.2053480830191295
Fold 5 IBS: 0.23028790282701023
[I 2024-04-19 09:47:03,086] Trial 67 finished with value: 0.2009052117344015 and parameters: {'subsample': 0.15568423059658415, 'dropout_rate': 0.42909922613780493, 'n_estimators': 180, 'learning_rate': 0.01323859721246935}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20277376143472872
Fold 2 IBS: 0.1829205128289286
Fold 3 IBS: 0.18012683783481556
Fold 4 IBS: 0.20176018622162195
Fold 5 IBS: 0.24233789818983398
[I 2024-04-19 09:47:09,984] Trial 68 finished with value: 0.20198383930198577 and parameters: {'subsample': 0.11678475769543026, 'dropout_rate': 0.5715447915185884, 'n_estimators': 211, 'learning_rate': 0.017172021010629823}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20658605382281173
Fold 2 IBS: 0.2118060229244657
Fold 3 IBS: 0.19448832888163925
Fold 4 IBS: 0.2176223447408348
Fold 5 IBS: 0.21843115460759768
[I 2024-04-19 09:47:21,759] Trial 69 finished with value: 0.20978678099546982 and parameters: {'subsample': 0.21161263790130455, 'dropout_rate': 0.6101977093901618, 'n_estimators': 312, 'learning_rate': 0.0018867758471883605}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.21808851604798607
Fold 2 IBS: 0.1808423044818364
Fold 3 IBS: 0.18340281811168282
Fold 4 IBS: 0.20461257022620316
Fold 5 IBS: 0.27082523677530806
[I 2024-04-19 09:47:29,636] Trial 70 finished with value: 0.2115542891286033 and parameters: {'subsample': 0.17041285286100422, 'dropout_rate': 0.6501636726304723, 'n_estimators': 238, 'learning_rate': 0.023120413215931158}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20008920764178695
Fold 2 IBS: 0.19989773508322836
Fold 3 IBS: 0.18317859171688963
Fold 4 IBS: 0.20825434900667236
Fold 5 IBS: 0.22301531571356484
[I 2024-04-19 09:47:38,447] Trial 71 finished with value: 0.20288703983242845 and parameters: {'subsample': 0.23858657434101843, 'dropout_rate': 0.6537322442371875, 'n_estimators': 263, 'learning_rate': 0.005527323146336553}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19834822909178282
Fold 2 IBS: 0.1924700142508621
Fold 3 IBS: 0.17943290634407566
Fold 4 IBS: 0.20406232844027072
Fold 5 IBS: 0.2304651445580731
[I 2024-04-19 09:47:44,689] Trial 72 finished with value: 0.20095572453701288 and parameters: {'subsample': 0.19000200029464814, 'dropout_rate': 0.7041015795761488, 'n_estimators': 210, 'learning_rate': 0.010670174704970479}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.19892321882781402
Fold 2 IBS: 0.19237685454516393
Fold 3 IBS: 0.1768200627218346
Fold 4 IBS: 0.20130565322056024
Fold 5 IBS: 0.2322650875578959
[I 2024-04-19 09:47:49,316] Trial 73 finished with value: 0.20033817537465373 and parameters: {'subsample': 0.3111832069220738, 'dropout_rate': 0.6677638486292921, 'n_estimators': 161, 'learning_rate': 0.014168674253488573}. Best is trial 50 with value: 0.2002407140843617.
Fold 1 IBS: 0.20045646442424045
Fold 2 IBS: 0.18947002191463266
Fold 3 IBS: 0.17447698970568096
Fold 4 IBS: 0.19710671606799232
Fold 5 IBS: 0.2395434169641527
[I 2024-04-19 09:47:53,541] Trial 74 finished with value: 0.2002107218153398 and parameters: {'subsample': 0.40204509376080955, 'dropout_rate': 0.7430055304940392, 'n_estimators': 158, 'learning_rate': 0.017337315932922898}. Best is trial 74 with value: 0.2002107218153398.
Fold 1 IBS: 0.19958452290903828
Fold 2 IBS: 0.19030732004212766
Fold 3 IBS: 0.17483785114255218
Fold 4 IBS: 0.19826060106382068
Fold 5 IBS: 0.23644304468515295
[I 2024-04-19 09:47:57,448] Trial 75 finished with value: 0.19988666796853835 and parameters: {'subsample': 0.4120463882442201, 'dropout_rate': 0.7444263029012758, 'n_estimators': 139, 'learning_rate': 0.017991057563342606}. Best is trial 75 with value: 0.19988666796853835.
Fold 1 IBS: 0.19924984096025528
Fold 2 IBS: 0.19151621970525132

Fold 3 IBS: 0.175369518258988
Fold 4 IBS: 0.19886694224374504
Fold 5 IBS: 0.23393332559570487
[I 2024-04-19 09:48:00,944] Trial 76 finished with value: 0.1997871693527889 and parameters: {'subsample': 0.5836047825601226, 'dropout_rate': 0.7414222854721267, 'n_estimators': 134, 'learning_rate': 0.017294952519981824}. Best is trial 76 with value: 0.1997871693527889.
Fold 1 IBS: 0.1990704813975664
Fold 2 IBS: 0.19235978313316857
Fold 3 IBS: 0.1756310426455353
Fold 4 IBS: 0.199178691043083
Fold 5 IBS: 0.23281528440987867
[I 2024-04-19 09:48:04,603] Trial 77 finished with value: 0.19981105652584638 and parameters: {'subsample': 0.610825053306389, 'dropout_rate': 0.7342999581448342, 'n_estimators': 136, 'learning_rate': 0.016329266673119444}. Best is trial 76 with value: 0.1997871693527889.
Fold 1 IBS: 0.20021184069742604
Fold 2 IBS: 0.1898669747346325
Fold 3 IBS: 0.17413074885324495
Fold 4 IBS: 0.19575506187113495
Fold 5 IBS: 0.23873279804958214
[I 2024-04-19 09:48:08,287] Trial 78 finished with value: 0.1997394848412041 and parameters: {'subsample': 0.6396347136821389, 'dropout_rate': 0.734258496850757, 'n_estimators': 138, 'learning_rate': 0.01917134937571007}. Best is trial 78 with value: 0.1997394848412041.
Fold 1 IBS: 0.19932365313628017
Fold 2 IBS: 0.19167868282673206
Fold 3 IBS: 0.1749880126220531
Fold 4 IBS: 0.19737561376825485
Fold 5 IBS: 0.23486767475837775
[I 2024-04-19 09:48:11,850] Trial 79 finished with value: 0.1996467274223396 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.7399249006923357, 'n_estimators': 133, 'learning_rate': 0.017648665721298102}. Best is trial 79 with value: 0.1996467274223396.
Fold 1 IBS: 0.19961887781716814
Fold 2 IBS: 0.19096447765703103
Fold 3 IBS: 0.17454081586805628
Fold 4 IBS: 0.19629047146094572
Fold 5 IBS: 0.23660732506531448
[I 2024-04-19 09:48:15,862] Trial 80 finished with value: 0.19960439357370313 and parameters: {'subsample': 0.7315717945946657, 'dropout_rate': 0.7357326565933753, 'n_estimators': 140, 'learning_rate': 0.01759253922056418}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.19999229968928536
Fold 2 IBS: 0.1902977349821739
Fold 3 IBS: 0.17430384981765815
Fold 4 IBS: 0.19578552359620682
Fold 5 IBS: 0.23788978607627034
[I 2024-04-19 09:48:19,728] Trial 81 finished with value: 0.1996538388323189 and parameters: {'subsample': 0.6844318320098943, 'dropout_rate': 0.741087533758798, 'n_estimators': 133, 'learning_rate': 0.019298639447445032}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.1998072413276961
Fold 2 IBS: 0.19072136683199542
Fold 3 IBS: 0.17443363860115832
Fold 4 IBS: 0.195703288803085
Fold 5 IBS: 0.23735705582774405
[I 2024-04-19 09:48:23,541] Trial 82 finished with value: 0.19960451827833575 and parameters: {'subsample': 0.7023525889552518, 'dropout_rate': 0.8166311879600783, 'n_estimators': 142, 'learning_rate': 0.017759980453938354}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.19966128385530138
Fold 2 IBS: 0.1910397634489925
Fold 3 IBS: 0.17458672473872375
Fold 4 IBS: 0.19603969658678633
Fold 5 IBS: 0.23679093033244544
[I 2024-04-19 09:48:27,894] Trial 83 finished with value: 0.19962367979244988 and parameters: {'subsample': 0.7051354923879309, 'dropout_rate': 0.735219196892226, 'n_estimators': 136, 'learning_rate': 0.018213126285462143}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.19977204199897935
Fold 2 IBS: 0.19091706928306987
Fold 3 IBS: 0.17451970398428615
Fold 4 IBS: 0.19605546349896716
Fold 5 IBS: 0.2369903499229805
[I 2024-04-19 09:48:31,245] Trial 84 finished with value: 0.1996509257376566 and parameters: {'subsample': 0.7204195703298658, 'dropout_rate': 0.8121241037229759, 'n_estimators': 120, 'learning_rate': 0.020748026919745793}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.20014362777087816
Fold 2 IBS: 0.1903183154274374
Fold 3 IBS: 0.1742606004215005
Fold 4 IBS: 0.19542412970581186
Fold 5 IBS: 0.23863553683900043
[I 2024-04-19 09:48:34,534] Trial 85 finished with value: 0.19975644203292567 and parameters: {'subsample': 0.7091353379705275, 'dropout_rate': 0.8028280061275229, 'n_estimators': 119, 'learning_rate': 0.021871423283261218}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.1998988283297914
Fold 2 IBS: 0.19073736624196466
Fold 3 IBS: 0.1744276307295157
Fold 4 IBS: 0.1959017369600191
Fold 5 IBS: 0.23763364904143752
[I 2024-04-19 09:48:37,513] Trial 86 finished with value: 0.19971984226054568 and parameters: {'subsample': 0.7075354081908148, 'dropout_rate': 0.8053753071140581, 'n_estimators': 118, 'learning_rate': 0.02147683802935845}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.20046038829606697
Fold 2 IBS: 0.189903457683387
Fold 3 IBS: 0.17409633710850367
Fold 4 IBS: 0.19495360704359868
Fold 5 IBS: 0.2397637680699324
[I 2024-04-19 09:48:40,542] Trial 87 finished with value: 0.19983551164029772 and parameters: {'subsample': 0.7113165522015475, 'dropout_rate': 0.7914036501196641, 'n_estimators': 119, 'learning_rate': 0.02253314843935789}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.20270875254962017
Fold 2 IBS: 0.18789956229691346
Fold 3 IBS: 0.17376078168747475
Fold 4 IBS: 0.19274378152496585
Fold 5 IBS: 0.24693577377839332
[I 2024-04-19 09:48:43,366] Trial 88 finished with value: 0.2008097303674735 and parameters: {'subsample': 0.7947472470580279, 'dropout_rate': 0.8092067959772727, 'n_estimators': 107, 'learning_rate': 0.029045336629888754}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.2058414081718099
Fold 2 IBS: 0.18689229038948543
Fold 3 IBS: 0.17436151578758788
Fold 4 IBS: 0.1912997267349409
Fold 5 IBS: 0.253363160445477
[I 2024-04-19 09:48:47,239] Trial 89 finished with value: 0.20235162030586024 and parameters: {'subsample': 0.6724577663283842, 'dropout_rate': 0.7682757241078133, 'n_estimators': 144, 'learning_rate': 0.025056796383218}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.2002421592569719
Fold 2 IBS: 0.19000690912500504
Fold 3 IBS: 0.1741686471648253
Fold 4 IBS: 0.19517043111281202
Fold 5 IBS: 0.2389778125131324
[I 2024-04-19 09:48:50,264] Trial 90 finished with value: 0.19971319183454933 and parameters: {'subsample': 0.7667575287793054, 'dropout_rate': 0.8106776337766259, 'n_estimators': 118, 'learning_rate': 0.022178106548447513}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.19926702569679292
Fold 2 IBS: 0.19175336748953867
Fold 3 IBS: 0.17512272353043026
Fold 4 IBS: 0.19733362851083255
Fold 5 IBS: 0.23472247799899368
[I 2024-04-19 09:48:53,105] Trial 91 finished with value: 0.19963984464531764 and parameters: {'subsample': 0.7695552478269991, 'dropout_rate': 0.8162347483305431, 'n_estimators': 111, 'learning_rate': 0.020743150893703773}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.19900863814058042
Fold 2 IBS: 0.1929282581566159
Fold 3 IBS: 0.175868426797474
Fold 4 IBS: 0.19854200005689782
Fold 5 IBS: 0.23253862308474066
[I 2024-04-19 09:48:55,930] Trial 92 finished with value: 0.19977718924726173 and parameters: {'subsample': 0.766467054168876, 'dropout_rate': 0.8264557730503493, 'n_estimators': 112, 'learning_rate': 0.01912439097423276}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.2000824855344407
Fold 2 IBS: 0.19945570031844187
Fold 3 IBS: 0.1813950180275522
Fold 4 IBS: 0.20606677259347034
Fold 5 IBS: 0.2243887093228803
[I 2024-04-19 09:48:58,064] Trial 93 finished with value: 0.20227773715935707 and parameters: {'subsample': 0.6715555451078695, 'dropout_rate': 0.7622407236932554, 'n_estimators': 70, 'learning_rate': 0.020731819562374982}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.2078495885256513
Fold 2 IBS: 0.18667266242300104
Fold 3 IBS: 0.17493601167825457
Fold 4 IBS: 0.19033502317311582
Fold 5 IBS: 0.25850829638940104
[I 2024-04-19 09:49:01,837] Trial 94 finished with value: 0.20366031643788474 and parameters: {'subsample': 0.8299924387055171, 'dropout_rate': 0.890608861357131, 'n_estimators': 150, 'learning_rate': 0.025869957785517338}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.20700029477753523
Fold 2 IBS: 0.18677258452757037

Fold 3 IBS: 0.17467023221093744
Fold 4 IBS: 0.19067718405926123
Fold 5 IBS: 0.25649411258858085
[I 2024-04-19 09:49:05,047] Trial 95 finished with value: 0.20312288163277703 and parameters: {'subsample': 0.742801951389467, 'dropout_rate': 0.6950389161933, 'n_estimators': 126, 'learning_rate': 0.029845688472146227}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.19915942234350345
Fold 2 IBS: 0.19639364745164575
Fold 3 IBS: 0.1785603826338131
Fold 4 IBS: 0.20275925974876494
Fold 5 IBS: 0.22744247015099853
[I 2024-04-19 09:49:07,487] Trial 96 finished with value: 0.20086303646574516 and parameters: {'subsample': 0.6896197002613113, 'dropout_rate': 0.8197700303393364, 'n_estimators': 83, 'learning_rate': 0.021117969427201858}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.20018341772485804
Fold 2 IBS: 0.1898492293864333
Fold 3 IBS: 0.17423959635583383
Fold 4 IBS: 0.19657311132315583
Fold 5 IBS: 0.23867363903033434
[I 2024-04-19 09:49:10,054] Trial 97 finished with value: 0.19990379876412306 and parameters: {'subsample': 0.6474000154192278, 'dropout_rate': 0.843742599901377, 'n_estimators': 106, 'learning_rate': 0.02449275927173883}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.20389563260613033
Fold 2 IBS: 0.18737523054863542
Fold 3 IBS: 0.1738987224060007
Fold 4 IBS: 0.19175726467871268
Fold 5 IBS: 0.24948414831200155
[I 2024-04-19 09:49:14,593] Trial 98 finished with value: 0.20128219971029612 and parameters: {'subsample': 0.7872126058275576, 'dropout_rate': 0.7173746535805982, 'n_estimators': 168, 'learning_rate': 0.01973626745486202}. Best is trial 80 with value: 0.19960439357370313.
Fold 1 IBS: 0.21734603561089808
Fold 2 IBS: 0.18884686115212496
Fold 3 IBS: 0.1794610587395472
Fold 4 IBS: 0.19052985632131925
Fold 5 IBS: 0.2786715164188068
[I 2024-04-19 09:49:18,447] Trial 99 finished with value: 0.21097106564853924 and parameters: {'subsample': 0.7309805099618746, 'dropout_rate': 0.7932852826751436, 'n_estimators': 145, 'learning_rate': 0.03626362328950353}. Best is trial 80 with value: 0.19960439357370313.


* Best trial for IBS:
 FrozenTrial(number=80, state=TrialState.COMPLETE, values=[0.19960439357370313], datetime_start=datetime.datetime(2024, 4, 19, 9, 48, 11, 861755), datetime_complete=datetime.datetime(2024, 4, 19, 9, 48, 15, 861530), params={'subsample': 0.7315717945946657, 'dropout_rate': 0.7357326565933753, 'n_estimators': 140, 'learning_rate': 0.01759253922056418}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=80, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.7315717945946657, 'dropout_rate': 0.7357326565933753, 'n_estimators': 140, 'learning_rate': 0.01759253922056418}


* Best Score for IBS:
 0.19960439357370313

In [112]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [113]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.689
train_ibs:  0.2

#### Test

In [114]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [115]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5421969302450425,
                                              learning_rate=0.0332916598506947,
                                              n_estimators=251,
                                              random_state=123,
                                              subsample=0.20242575932269302)

C-index score: 0.635

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7357326565933753,
                                              learning_rate=0.01759253922056418,
                                              n_estimators=140,
                                              random_state=123,
                                              subsample=0.7315717945946657)

IBS: 0.206

In [116]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [117]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.863   1.0
ExtraSurvivalTrees               0.808   2.0
ComponentwiseGradientBoosting    0.689   3.0
CoxElastic                       0.681   4.0
CoxRidge                         0.675   5.0
CoxLasso                         0.666   6.0
CoxPH                            0.664   7.0
GradientBoosting                 0.662   8.0

In [118]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.195   1.0
ExtraSurvivalTrees             0.198   2.0
ComponentwiseGradientBoosting  0.200   3.0
CoxPH                          0.203   5.0
CoxLasso                       0.203   5.0
CoxElastic                     0.203   5.0
GradientBoosting               0.216   7.0
CoxRidge                       0.217   8.0

In [119]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.635   1.0
Randomsurvivalforest             0.621   2.0
CoxElastic                       0.617   3.0
CoxRidge                         0.616   4.0
ExtraSurvivalTrees               0.614   5.0
GradientBoosting                 0.595   6.0
CoxLasso                         0.588   7.0
CoxPH                            0.586   8.0

In [120]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.206   1.0
ExtraSurvivalTrees             0.211   2.0
Randomsurvivalforest           0.220   3.0
CoxRidge                       0.221   4.5
GradientBoosting               0.221   4.5
CoxElastic                     0.237   6.0
CoxLasso                       0.238   7.0
CoxPH                          0.239   8.0

In [121]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/yeojohnson/plsr/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_yeojohnson_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [122]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-19