In [28]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import PowerTransformer

In [29]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [30]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [31]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [32]:
# Check null values in D3 
clinical_train.isnull().sum().sum()

0

### COX assumption in Train data

In [33]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.97      0.05
LBP_003_PET                                                      0.00 0.97      0.05
LBP_012_CT                                                       0.00 0.96      0.06
LBP_012_PET                                                      0.01 0.94      0.09
LBP_021_CT                                                       0.00 0.98      0.04
LBP_021_PET                                                      0.01 0.94      0.10
LBP_030_CT                                                       0.00 0.99      0.02
LBP_030_PET                                                      0.00 0.98      0.02
LBP_102_CT                                                       0.00 0.96      0.05
LBP_102_PET                                                      0.01 0.92      0.12
LBP_111_CT                                                       0.00 0.95      0.07
LBP_111_PET                                                      0.00 1.00      0.00
LBP_120_CT                                                       0.00 0.98      0.03
LBP_120_PET                                                      0.00 0.99      0.02
LBP_201_CT                                                       0.00 0.97      0.04
LBP_201_PET                                                      0.00 0.97      0.04
LBP_210_CT                                                       0.00 1.00      0.01
LBP_210_PET                                                      0.00 1.00      0.00
LBP_300_CT                                                       0.00 0.97      0.04
LBP_300_PET                                                      0.01 0.94      0.09
MTV                                                              0.00 0.98      0.04
SUVpeak                                                          0.00 0.98      0.02
TLG                                                              0.00 0.99      0.02
age                                                              0.00 0.97      0.05
cavum_oris                                                       0.00 0.99      0.02
charlson                                                         0.02 0.90      0.15
female                                                           0.00 0.96      0.06
first_order_10Percentile_CT                                      0.00 0.98      0.03
first_order_10Percentile_PET                                     0.00 1.00      0.01
first_order_90Percentile_CT                                      0.00 0.98      0.04
first_order_90Percentile_PET                                     0.00 0.99      0.01
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 1.00      0.00
first_order_Entropy_CT_c16                                       0.00 1.00      0.00
first_order_Entropy_PET_b2                                       0.00 1.00      0.00
first_order_Entropy_PET_c04                                      0.00 1.00      0.00
first_order_InterquartileRange_CT                                0.00 0.97      0.04
first_order_InterquartileRange_PET                               0.00 0.99      0.01
first_order_Kurtosis_CT                                          0.00 0.95      0.08
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.00 0.99      0.02
first_order_Maximum_PET                                          0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_PET                            0.00 0.99      0.02
first_order_Mean_CT                                              0.00 0.99      0.02
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.98      0.03
first_order_Median_PET                                           0.00 0.99      0.01
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.01 0.94      0.09
first_order_Range_CT                                             0.00 0.99      0.01
first_order_Range_PET                                            0.00 0.99      0.02
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.98      0.04
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 1.00      0.00
first_order_RootMeanSquared_CT                                   0.00 0.98      0.03
first_order_RootMeanSquared_PET                                  0.00 0.99      0.01
first_order_Skewness_CT                                          0.00 0.98      0.03
first_order_Skewness_PET                                         0.00 1.00      0.00
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.97      0.05
first_order_Uniformity_CT_c16                                    0.00 0.99      0.01
first_order_Uniformity_PET_b2                                    0.00 1.00      0.00
first_order_Uniformity_PET_c04                                   0.00 1.00      0.00
first_order_Variance_CT                                          0.00 1.00      0.01
first_order_Variance_PET                                         0.00 1.00      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_CT_c16                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.99      0.01
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.99      0.01
glcm_ClusterProminence_d_1_CT_b20                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.98      0.03
glcm_ClusterProminence_d_1_PET_b2                                0.00 0.97      0.05
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.97      0.05
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.97      0.04
glcm_ClusterShade_d_1_CT_c16                                     0.00 1.00      0.01
glcm_ClusterShade_d_1_PET_b2                                     0.01 0.93      0.11
glcm_ClusterShade_d_1_PET_c04                                    0.00 1.00      0.00
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.99      0.02
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.99      0.01
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.01
glcm_Contrast_d_1_CT_c16                                         0.00 0.99      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 1.00      0.01
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.99      0.02
glcm_Correlation_d_1_CT_c16                                      0.00 0.95      0.07
glcm_Correlation_d_1_PET_b2                                      0.00 0.98      0.03
glcm_Correlation_d_1_PET_c04                                     0.00 0.99      0.02
glcm_DifferenceAverage_d_1_CT_b20                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_c16                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_PET_b2                                0.00 1.00      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 1.00      0.01
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceVariance_d_1_CT_b20                               0.00 1.00      0.01
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_PET_b2                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.98      0.02
glcm_Id_d_1_CT_b20                                               0.00 0.99      0.02
glcm_Id_d_1_CT_c16                                               0.00 1.00      0.00
glcm_Id_d_1_PET_b2                                               0.00 1.00      0.01
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 0.99      0.02
glcm_Idm_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00 1.00      0.01
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Idmn_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_c16                                             0.00 0.99      0.01
glcm_Idmn_d_1_PET_b2                                             0.00 1.00      0.01
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 0.98      0.03
glcm_Idn_d_1_CT_c16                                              0.00 1.00      0.00
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.01
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.01
glcm_Imc1_d_1_CT_b20                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_c16                                             0.01 0.94      0.10
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Imc2_d_1_CT_b20                                             0.00 1.00      0.01
glcm_Imc2_d_1_CT_c16                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.98      0.02
glcm_InverseVariance_d_1_CT_b20                                  0.00 1.00      0.00
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_PET_b2                                  0.00 1.00      0.01
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.01
glcm_JointAverage_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointAverage_d_1_PET_b2                                     0.00 1.00      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 0.99      0.01
glcm_JointEnergy_d_1_CT_b20                                      0.00 0.97      0.04
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_b2                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_c04                                     0.00 0.98      0.03
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.97      0.04
glcm_MCC_d_1_CT_c16                                              0.00 0.95      0.07
glcm_MCC_d_1_PET_b2                                              0.00 0.99      0.01
glcm_MCC_d_1_PET_c04                                             0.00 0.98      0.02
glcm_MaximumProbability_d_1_CT_b20                               0.00 0.96      0.06
glcm_MaximumProbability_d_1_CT_c16                               0.00 1.00      0.00
glcm_MaximumProbability_d_1_PET_b2                               0.00 0.99      0.01
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.99      0.01
glcm_SumAverage_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumAverage_d_1_PET_b2                                       0.00 1.00      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumEntropy_d_1_CT_b20                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.99      0.02
glcm_SumSquares_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumSquares_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumSquares_d_1_PET_c04                                      0.00 0.99      0.01
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 1.00      0.00
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 1.00      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.04
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.99      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 0.98      0.03
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.97      0.05
gldm_DependenceVariance_d_1_CT_c16                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.99      0.02
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.99      0.01
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 1.00      0.01
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.03
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.99      0.01
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 1.00      0.00
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 1.00      0.00
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.97      0.04
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.00
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.02
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.97      0.05
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.01 0.93      0.10
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.99      0.01
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.98      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_b20                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_c16                                   0.00 1.00      0.01
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.01

In [34]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [35]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.00 0.95      0.07
LBP_003_PET                                                      0.08 0.77      0.37
LBP_012_CT                                                       0.00 0.95      0.07
LBP_012_PET                                                      0.18 0.67      0.57
LBP_021_CT                                                       0.15 0.69      0.53
LBP_021_PET                                                      0.01 0.94      0.09
LBP_030_CT                                                       0.00 0.99      0.01
LBP_030_PET                                                      0.03 0.86      0.21
LBP_102_CT                                                       0.02 0.89      0.17
LBP_102_PET                                                      0.69 0.41      1.30
LBP_111_CT                                                       0.01 0.93      0.11
LBP_111_PET                                                      0.00 0.98      0.03
LBP_120_CT                                                       0.01 0.92      0.12
LBP_120_PET                                                      0.01 0.91      0.14
LBP_201_CT                                                       0.04 0.84      0.25
LBP_201_PET                                                      1.08 0.30      1.74
LBP_210_CT                                                       0.13 0.72      0.47
LBP_210_PET                                                      0.06 0.81      0.30
LBP_300_CT                                                       0.03 0.87      0.19
LBP_300_PET                                                      0.23 0.63      0.67
MTV                                                              0.00 0.98      0.03
SUVpeak                                                          0.01 0.91      0.14
TLG                                                              0.00 0.97      0.05
age                                                              0.11 0.74      0.43
cavum_oris                                                       0.35 0.55      0.85
charlson                                                         1.37 0.24      2.05
female                                                           2.09 0.15      2.76
first_order_10Percentile_CT                                      0.16 0.69      0.54
first_order_10Percentile_PET                                     0.00 0.96      0.06
first_order_90Percentile_CT                                      0.28 0.60      0.74
first_order_90Percentile_PET                                     0.01 0.94      0.08
first_order_Energy_CT                                            0.00 0.95      0.07
first_order_Energy_PET                                           0.02 0.89      0.17
first_order_Entropy_CT_b20                                       0.00 0.95      0.08
first_order_Entropy_CT_c16                                       0.01 0.94      0.09
first_order_Entropy_PET_b2                                       0.00 0.99      0.01
first_order_Entropy_PET_c04                                      0.00 0.99      0.02
first_order_InterquartileRange_CT                                0.00 0.99      0.02
first_order_InterquartileRange_PET                               0.04 0.85      0.23
first_order_Kurtosis_CT                                          0.00 0.95      0.07
first_order_Kurtosis_PET                                         0.00 0.97      0.04
first_order_Maximum_CT                                           0.04 0.83      0.26
first_order_Maximum_PET                                          0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_CT                             0.01 0.92      0.11
first_order_MeanAbsoluteDeviation_PET                            0.00 0.97      0.04
first_order_Mean_CT                                              0.01 0.93      0.11
first_order_Mean_PET                                             0.01 0.92      0.11
first_order_Median_CT                                            0.20 0.65      0.61
first_order_Median_PET                                           0.01 0.93      0.11
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.02 0.88      0.19
first_order_Range_CT                                             0.03 0.87      0.20
first_order_Range_PET                                            0.01 0.93      0.10
first_order_RobustMeanAbsoluteDeviation_CT                       0.18 0.67      0.57
first_order_RobustMeanAbsoluteDeviation_PET                      0.02 0.88      0.18
first_order_RootMeanSquared_CT                                   0.01 0.91      0.13
first_order_RootMeanSquared_PET                                  0.01 0.93      0.11
first_order_Skewness_CT                                          0.04 0.84      0.25
first_order_Skewness_PET                                         0.00 0.99      0.02
first_order_TotalEnergy_CT                                       0.00 0.95      0.07
first_order_TotalEnergy_PET                                      0.02 0.89      0.17
first_order_Uniformity_CT_b20                                    0.00 0.97      0.04
first_order_Uniformity_CT_c16                                    0.00 0.97      0.04
first_order_Uniformity_PET_b2                                    0.02 0.90      0.15
first_order_Uniformity_PET_c04                                   0.01 0.93      0.10
first_order_Variance_CT                                          0.00 1.00      0.00
first_order_Variance_PET                                         0.00 0.95      0.07
glcm_Autocorrelation_d_1_CT_b20                                  0.00 0.97      0.05
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.01
glcm_Autocorrelation_d_1_PET_b2                                  0.00 0.98      0.03
glcm_Autocorrelation_d_1_PET_c04                                 0.00 0.95      0.07
glcm_ClusterProminence_d_1_CT_b20                                0.03 0.86      0.22
glcm_ClusterProminence_d_1_CT_c16                                0.01 0.93      0.11
glcm_ClusterProminence_d_1_PET_b2                                0.02 0.88      0.19
glcm_ClusterProminence_d_1_PET_c04                               0.03 0.86      0.22
glcm_ClusterShade_d_1_CT_b20                                     0.11 0.74      0.42
glcm_ClusterShade_d_1_CT_c16                                     0.02 0.89      0.16
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.99      0.01
glcm_ClusterShade_d_1_PET_c04                                    0.06 0.81      0.31
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.96      0.06
glcm_ClusterTendency_d_1_CT_c16                                  0.01 0.91      0.14
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.95      0.08
glcm_ClusterTendency_d_1_PET_c04                                 0.08 0.78      0.36
glcm_Contrast_d_1_CT_b20                                         0.00 0.98      0.02
glcm_Contrast_d_1_CT_c16                                         0.02 0.89      0.17
glcm_Contrast_d_1_PET_b2                                         0.00 0.97      0.04
glcm_Contrast_d_1_PET_c04                                        0.00 0.98      0.04
glcm_Correlation_d_1_CT_b20                                      0.05 0.82      0.28
glcm_Correlation_d_1_CT_c16                                      0.29 0.59      0.77
glcm_Correlation_d_1_PET_b2                                      0.00 0.97      0.04
glcm_Correlation_d_1_PET_c04                                     0.00 0.96      0.05
glcm_DifferenceAverage_d_1_CT_b20                                0.01 0.92      0.13
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.95      0.08
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.96      0.06
glcm_DifferenceAverage_d_1_PET_c04                               0.00 0.98      0.03
glcm_DifferenceEntropy_d_1_CT_b20                                0.01 0.93      0.10
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.97      0.05
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 0.95      0.07
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.98      0.03
glcm_DifferenceVariance_d_1_CT_c16                               0.02 0.88      0.18
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 0.99      0.02
glcm_Id_d_1_CT_b20                                               0.05 0.83      0.27
glcm_Id_d_1_CT_c16                                               0.00 0.96      0.05
glcm_Id_d_1_PET_b2                                               0.01 0.93      0.11
glcm_Id_d_1_PET_c04                                              0.00 0.96      0.06
glcm_Idm_d_1_CT_b20                                              0.05 0.83      0.27
glcm_Idm_d_1_CT_c16                                              0.00 0.97      0.04
glcm_Idm_d_1_PET_b2                                              0.01 0.94      0.09
glcm_Idm_d_1_PET_c04                                             0.00 0.97      0.05
glcm_Idmn_d_1_CT_b20                                             0.02 0.90      0.15
glcm_Idmn_d_1_CT_c16                                             0.02 0.90      0.15
glcm_Idmn_d_1_PET_b2                                             0.01 0.93      0.11
glcm_Idmn_d_1_PET_c04                                            0.00 0.98      0.03
glcm_Idn_d_1_CT_b20                                              0.00 0.99      0.01
glcm_Idn_d_1_CT_c16                                              0.00 0.96      0.06
glcm_Idn_d_1_PET_b2                                              0.00 0.99      0.02
glcm_Idn_d_1_PET_c04                                             0.00 0.97      0.04
glcm_Imc1_d_1_CT_b20                                             0.04 0.85      0.24
glcm_Imc1_d_1_CT_c16                                             0.34 0.56      0.84
glcm_Imc1_d_1_PET_b2                                             0.00 0.99      0.02
glcm_Imc1_d_1_PET_c04                                            0.00 0.96      0.07
glcm_Imc2_d_1_CT_b20                                             0.09 0.77      0.38
glcm_Imc2_d_1_CT_c16                                             0.13 0.72      0.48
glcm_Imc2_d_1_PET_b2                                             0.01 0.94      0.09
glcm_Imc2_d_1_PET_c04                                            0.01 0.93      0.11
glcm_InverseVariance_d_1_CT_b20                                  0.18 0.67      0.58
glcm_InverseVariance_d_1_CT_c16                                  0.01 0.91      0.14
glcm_InverseVariance_d_1_PET_b2                                  0.03 0.87      0.20
glcm_InverseVariance_d_1_PET_c04                                 0.01 0.91      0.13
glcm_JointAverage_d_1_CT_b20                                     0.00 0.98      0.02
glcm_JointAverage_d_1_CT_c16                                     0.00 0.97      0.04
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.01 0.93      0.10
glcm_JointEnergy_d_1_CT_b20                                      0.01 0.93      0.11
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.03 0.86      0.22
glcm_JointEnergy_d_1_PET_c04                                     0.02 0.90      0.16
glcm_JointEntropy_d_1_CT_b20                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_c16                                     0.02 0.90      0.15
glcm_JointEntropy_d_1_PET_b2                                     0.00 0.97      0.05
glcm_JointEntropy_d_1_PET_c04                                    0.00 0.99      0.01
glcm_MCC_d_1_CT_b20                                              0.00 0.96      0.06
glcm_MCC_d_1_CT_c16                                              0.01 0.94      0.08
glcm_MCC_d_1_PET_b2                                              0.00 1.00      0.00
glcm_MCC_d_1_PET_c04                                             0.00 0.99      0.01
glcm_MaximumProbability_d_1_CT_b20                               0.01 0.92      0.11
glcm_MaximumProbability_d_1_CT_c16                               0.02 0.89      0.17
glcm_MaximumProbability_d_1_PET_b2                               0.04 0.85      0.23
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.95      0.07
glcm_SumAverage_d_1_CT_b20                                       0.00 0.98      0.02
glcm_SumAverage_d_1_CT_c16                                       0.00 0.97      0.04
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.01 0.93      0.10
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.95      0.08
glcm_SumEntropy_d_1_CT_c16                                       0.01 0.91      0.14
glcm_SumEntropy_d_1_PET_b2                                       0.00 0.96      0.05
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.98      0.03
glcm_SumSquares_d_1_CT_b20                                       0.00 0.96      0.05
glcm_SumSquares_d_1_CT_c16                                       0.01 0.93      0.11
glcm_SumSquares_d_1_PET_b2                                       0.00 0.95      0.08
glcm_SumSquares_d_1_PET_c04                                      0.08 0.78      0.36
gldm_DependenceEntropy_d_1_CT_b20                                0.11 0.74      0.44
gldm_DependenceEntropy_d_1_CT_c16                                0.05 0.83      0.27
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.97      0.04
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.95      0.07
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.10 0.75      0.42
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.02
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.01 0.92      0.12
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 0.99      0.01
gldm_DependenceNonUniformity_d_1_CT_c16                          0.01 0.93      0.10
gldm_DependenceNonUniformity_d_1_PET_b2                          0.01 0.90      0.15
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 0.99      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.52 0.47      1.09
gldm_DependenceVariance_d_1_CT_c16                               0.17 0.68      0.55
gldm_DependenceVariance_d_1_PET_b2                               0.07 0.80      0.33
gldm_DependenceVariance_d_1_PET_c04                              0.07 0.78      0.35
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.97      0.05
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.01 0.94      0.09
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 1.00      0.00
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.94      0.08
gldm_GrayLevelVariance_d_1_PET_c04                               0.05 0.83      0.27
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 0.99      0.02
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 0.95      0.07
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.02 0.88      0.18
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.03 0.86      0.22
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.01 0.92      0.11
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 0.98      0.03
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.96      0.06
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.03 0.86      0.22
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.01 0.94      0.09
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.95      0.07
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.03 0.86      0.22
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.02
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.08
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.06 0.81      0.30
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.03 0.86      0.21
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.94      0.08
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.02 0.89      0.17
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.01 0.91      0.13
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.01
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.07 0.79      0.33
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.96      0.06
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.97      0.04
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.02 0.89      0.16
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01 0.92      0.13
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.01 0.94      0.08
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.03 0.86      0.22
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.22 0.64      0.65
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 1.00      0.00
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00 0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.95      0.08
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.96      0.06
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 1.00      0.01
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 0.95      0.07
glrlm_GrayLevelNonUniformity_CT_c16                              0.06 0.81      0.30
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.02
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.99      0.01
glrlm_GrayLevelVariance_CT_b20                                   0.00 0.95      0.08
glrlm_GrayLevelVariance_CT_c16                                   0.00 0.96      0.06
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.96      0.06

In [36]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

## Test dataset: MAASTRO

In [37]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [38]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [39]:
# Need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [40]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [41]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [42]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [43]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# Set y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [46]:
# Change the name of a column 'OS_event' in the clincial_test 
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [47]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

# Yeo-Johnson Transformation

In [48]:
# Copy the original X for later 
original_X = X.copy()

In [49]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
pt = PowerTransformer(method='yeo-johnson')
X_numeric_std = pt.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [52]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = pt.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [53]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [54]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:28:22,068] A new study created in memory with name: no-name-ea79c532-3e9d-4eb0-81ee-e4b51823644d
python(7418) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-18 03:28:29,547] Trial 0 failed with parameters: {} because of the following error: LinAlgError('Matrix is singular.').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_6391/487959643.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 449, in fit
    delta = solve(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 220, in solve
    _solve_check(n, info)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[W 2024-04-18 03:28:29,555] Trial 0 failed with value None.

LinAlgError: Matrix is singular.

In [55]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {}

In [56]:
# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [57]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [58]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [59]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [60]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [61]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [62]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:28:52,381] A new study created in memory with name: no-name-5f7a4320-5f1e-4d08-a9d1-32398e006000

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.689873417721519

[I 2024-04-18 03:29:30,738] A new study created in memory with name: no-name-858acf81-ccd6-4195-ba3a-34cecfbdd29c

Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 03:29:30,698] Trial 0 finished with value: 0.7161392368175977 and parameters: {}. Best is trial 0 with value: 0.7161392368175977.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7161392368175977], datetime_start=datetime.datetime(2024, 4, 18, 3, 28, 52, 565389), datetime_complete=datetime.datetime(2024, 4, 18, 3, 29, 30, 697857), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7161392368175977

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651724235042
Fold 2 IBS: 0.2215779146315195
Fold 3 IBS: 0.20453594072931716
Fold 4 IBS: 0.22473803872764997
Fold 5 IBS: 0.21812431098174057
[I 2024-04-18 03:30:04,788] Trial 0 finished with value: 0.2165905444625155 and parameters: {}. Best is trial 0 with value: 0.2165905444625155.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2165905444625155], datetime_start=datetime.datetime(2024, 4, 18, 3, 29, 30, 935602), datetime_complete=datetime.datetime(2024, 4, 18, 3, 30, 4, 787702), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2165905444625155

In [63]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [64]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.716
train_ibs:  0.217

#### Test

In [65]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [66]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.573

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [67]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [68]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:30:05,514] A new study created in memory with name: no-name-915df40a-2c58-42d4-92a4-df19be137f77

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7922077922077922
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.6075949367088608

[I 2024-04-18 03:30:46,500] A new study created in memory with name: no-name-e3938e04-ec70-4359-bea9-437716aa158b

Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:30:46,408] Trial 0 finished with value: 0.6778264174841235 and parameters: {}. Best is trial 0 with value: 0.6778264174841235.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6778264174841235], datetime_start=datetime.datetime(2024, 4, 18, 3, 30, 5, 617174), datetime_complete=datetime.datetime(2024, 4, 18, 3, 30, 46, 407987), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6778264174841235

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21533544230916105
Fold 2 IBS: 0.35684861315058924
Fold 3 IBS: 0.2999824518344091
Fold 4 IBS: 0.3450292483985389
Fold 5 IBS: 0.34672666404044594
[I 2024-04-18 03:31:32,397] Trial 0 finished with value: 0.31278448394662883 and parameters: {}. Best is trial 0 with value: 0.31278448394662883.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.31278448394662883], datetime_start=datetime.datetime(2024, 4, 18, 3, 30, 46, 659703), datetime_complete=datetime.datetime(2024, 4, 18, 3, 31, 32, 397126), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.31278448394662883

In [69]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [70]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.678
train_ibs:  0.313

#### Test

In [71]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [72]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.55

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.419

In [73]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [74]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 03:31:36,622] A new study created in memory with name: no-name-986e34a2-9863-4add-8735-1f1783c7d63d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:32:18,521] Trial 0 finished with value: 0.6832812671738819 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6832812671738819.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 03:32:55,899] Trial 1 finished with value: 0.70640219506983 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.70640219506983.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:33:34,772] Trial 2 finished with value: 0.710956287772893 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:34:09,229] Trial 3 finished with value: 0.6816833104495789 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:34:49,841] Trial 4 finished with value: 0.6823884100310249 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:35:29,777] Trial 5 finished with value: 0.6955318507652335 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6244131455399061
[I 2024-04-18 03:36:11,377] Trial 6 finished with value: 0.6758630817032885 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:36:45,623] Trial 7 finished with value: 0.6832812671738819 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6431924882629108
[I 2024-04-18 03:37:20,256] Trial 8 finished with value: 0.6898371169161679 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 03:37:53,374] Trial 9 finished with value: 0.6984316022151092 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.710956287772893.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:38:33,319] Trial 10 finished with value: 0.7340772156688411 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.7340772156688411.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:39:04,014] Trial 11 finished with value: 0.724105511870383 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.7340772156688411.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:39:32,070] Trial 12 finished with value: 0.7499920028304033 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:39:57,438] Trial 13 finished with value: 0.7239909205793211 and parameters: {'l1_ratio': 0.002630198731852655}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 03:40:26,097] Trial 14 finished with value: 0.7191779822189982 and parameters: {'l1_ratio': 0.1640712833693377}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:40:54,007] Trial 15 finished with value: 0.7264239694808214 and parameters: {'l1_ratio': 0.12555451639526363}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 03:41:23,547] Trial 16 finished with value: 0.7264700794741145 and parameters: {'l1_ratio': 0.11581492628181542}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:41:52,601] Trial 17 finished with value: 0.7027950720637369 and parameters: {'l1_ratio': 0.3160042276805186}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 03:42:20,520] Trial 18 finished with value: 0.743109613251612 and parameters: {'l1_ratio': 0.05618708893326824}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 03:42:48,570] Trial 19 finished with value: 0.7128709620933253 and parameters: {'l1_ratio': 0.2107995377699209}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.620253164556962
Fold 5 C-index: 0.6291079812206573
[I 2024-04-18 03:43:21,538] Trial 20 finished with value: 0.6793826696953762 and parameters: {'l1_ratio': 0.9610045169697747}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:43:50,738] Trial 21 finished with value: 0.729462015158257 and parameters: {'l1_ratio': 0.06922839398387204}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:44:29,645] Trial 22 finished with value: 0.729462015158257 and parameters: {'l1_ratio': 0.06905658484938232}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 03:45:06,991] Trial 23 finished with value: 0.707409643503749 and parameters: {'l1_ratio': 0.27605145560653}. Best is trial 12 with value: 0.7499920028304033.

Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:45:37,647] Trial 24 finished with value: 0.7230519534431709 and parameters: {'l1_ratio': 0.004279993897261608}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 03:46:10,875] Trial 25 finished with value: 0.718239015082848 and parameters: {'l1_ratio': 0.17401480064872898}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 03:46:42,550] Trial 26 finished with value: 0.7321578563758281 and parameters: {'l1_ratio': 0.08693050661949489}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:47:16,180] Trial 27 finished with value: 0.6824886325784305 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 03:47:49,634] Trial 28 finished with value: 0.6992293740783563 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:48:22,356] Trial 29 finished with value: 0.7109292314958366 and parameters: {'l1_ratio': 0.23283839910693951}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 03:48:53,970] Trial 30 finished with value: 0.7220143896389007 and parameters: {'l1_ratio': 0.14503775811438477}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 03:49:25,599] Trial 31 finished with value: 0.7274551208512384 and parameters: {'l1_ratio': 0.0728992060643543}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.75
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 03:49:56,785] Trial 32 finished with value: 0.730016235695724 and parameters: {'l1_ratio': 0.0791975914093239}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:50:33,000] Trial 33 finished with value: 0.7091924924964393 and parameters: {'l1_ratio': 0.2465409363510514}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:51:05,283] Trial 34 finished with value: 0.7156342032428784 and parameters: {'l1_ratio': 0.1897517037335145}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 03:51:36,438] Trial 35 finished with value: 0.7282287374827725 and parameters: {'l1_ratio': 0.08995837513978883}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.8008658008658008
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.6862745098039216
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 03:52:10,578] Trial 36 finished with value: 0.6880260275636536 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 03:52:43,521] Trial 37 finished with value: 0.7027950720637369 and parameters: {'l1_ratio': 0.3178097032619953}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:53:12,689] Trial 38 finished with value: 0.7443070912217137 and parameters: {'l1_ratio': 0.03443185902489488}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:53:40,874] Trial 39 finished with value: 0.7460386929533154 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 03:54:10,152] Trial 40 finished with value: 0.7470922513805276 and parameters: {'l1_ratio': 0.0317537118064967}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:54:39,080] Trial 41 finished with value: 0.7460386929533154 and parameters: {'l1_ratio': 0.0418512232291414}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:55:08,789] Trial 42 finished with value: 0.7499920028304033 and parameters: {'l1_ratio': 0.029589328135142038}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 03:55:34,924] Trial 43 finished with value: 0.7249713127361839 and parameters: {'l1_ratio': 0.002121522440452609}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 03:56:04,486] Trial 44 finished with value: 0.7219412233685514 and parameters: {'l1_ratio': 0.14655977197582426}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:56:35,950] Trial 45 finished with value: 0.7264239694808214 and parameters: {'l1_ratio': 0.1261706148540832}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 03:57:06,090] Trial 46 finished with value: 0.7450997258171652 and parameters: {'l1_ratio': 0.043841584916934045}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6525821596244131
[I 2024-04-18 03:57:37,883] Trial 47 finished with value: 0.6926735243360703 and parameters: {'l1_ratio': 0.4361397059879219}. Best is trial 12 with value: 0.7499920028304033.

Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 03:58:08,516] Trial 48 finished with value: 0.6834690247352933 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 03:58:35,712] Trial 49 finished with value: 0.7255800876242814 and parameters: {'l1_ratio': 0.12391166716004895}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 03:59:06,771] Trial 50 finished with value: 0.7146538110860157 and parameters: {'l1_ratio': 0.19334719885624377}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 03:59:33,522] Trial 51 finished with value: 0.7443070912217137 and parameters: {'l1_ratio': 0.036716428598859846}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 04:00:00,664] Trial 52 finished with value: 0.7451728920875146 and parameters: {'l1_ratio': 0.037346638052424476}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 04:00:27,045] Trial 53 finished with value: 0.7470922513805276 and parameters: {'l1_ratio': 0.032161485373578755}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 04:00:53,901] Trial 54 finished with value: 0.7263825444601089 and parameters: {'l1_ratio': 0.11075334643253895}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 04:01:23,606] Trial 55 finished with value: 0.6832812671738819 and parameters: {'l1_ratio': 0.6751302644579473}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 04:01:49,481] Trial 56 finished with value: 0.7499920028304033 and parameters: {'l1_ratio': 0.024911547309691535}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 04:02:12,129] Trial 57 finished with value: 0.7230519534431709 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 04:02:36,948] Trial 58 finished with value: 0.7201583743758609 and parameters: {'l1_ratio': 0.16182945398239404}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 04:03:02,057] Trial 59 finished with value: 0.7283019037531219 and parameters: {'l1_ratio': 0.09615544013876437}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 04:03:27,617] Trial 60 finished with value: 0.7072731332034264 and parameters: {'l1_ratio': 0.2528964924230062}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 04:03:52,586] Trial 61 finished with value: 0.7450997258171652 and parameters: {'l1_ratio': 0.04331559874936107}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 04:04:19,316] Trial 62 finished with value: 0.7451728920875146 and parameters: {'l1_ratio': 0.03739235181456524}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 04:04:43,054] Trial 63 finished with value: 0.7250859040272457 and parameters: {'l1_ratio': 0.00011204350585463513}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 04:05:09,378] Trial 64 finished with value: 0.7273215115962591 and parameters: {'l1_ratio': 0.10468037224255958}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 04:05:33,632] Trial 65 finished with value: 0.7421706461154616 and parameters: {'l1_ratio': 0.06023584783431974}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 04:05:58,757] Trial 66 finished with value: 0.7220143896389007 and parameters: {'l1_ratio': 0.14098326046602175}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 04:06:25,712] Trial 67 finished with value: 0.7303790632851465 and parameters: {'l1_ratio': 0.06442513947747977}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 04:06:52,189] Trial 68 finished with value: 0.7118905699364626 and parameters: {'l1_ratio': 0.20619303533451588}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 04:07:17,974] Trial 69 finished with value: 0.7499920028304033 and parameters: {'l1_ratio': 0.02765190087472786}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 04:07:43,828] Trial 70 finished with value: 0.7264286544534019 and parameters: {'l1_ratio': 0.09884968410615819}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 04:08:09,275] Trial 71 finished with value: 0.7490116106735406 and parameters: {'l1_ratio': 0.031017574513129822}. Best is trial 12 with value: 0.7499920028304033.

Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:08:32,752] Trial 72 finished with value: 0.7258959111286778 and parameters: {'l1_ratio': 0.0207995730510049}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 04:08:57,891] Trial 73 finished with value: 0.729462015158257 and parameters: {'l1_ratio': 0.06923230250518525}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6540084388185654
Fold 5 C-index: 0.6431924882629108
[I 2024-04-18 04:09:26,806] Trial 74 finished with value: 0.6889713160503671 and parameters: {'l1_ratio': 0.5200833454503305}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 04:09:53,781] Trial 75 finished with value: 0.7183341003624582 and parameters: {'l1_ratio': 0.16561865633656248}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:10:17,403] Trial 76 finished with value: 0.725030110262877 and parameters: {'l1_ratio': 0.019097692435626888}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 04:10:44,046] Trial 77 finished with value: 0.7340772156688411 and parameters: {'l1_ratio': 0.08267071438295703}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 04:11:08,663] Trial 78 finished with value: 0.7255800876242814 and parameters: {'l1_ratio': 0.1269558898924968}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7965367965367965
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.6582278481012658
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 04:11:37,121] Trial 79 finished with value: 0.6860433242406672 and parameters: {'l1_ratio': 0.8187818034877232}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 04:12:00,897] Trial 80 finished with value: 0.7430364469812626 and parameters: {'l1_ratio': 0.0596721166608314}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 04:12:25,145] Trial 81 finished with value: 0.7499920028304033 and parameters: {'l1_ratio': 0.02611467824056133}. Best is trial 12 with value: 0.7499920028304033.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:12:50,336] Trial 82 finished with value: 0.7529649205506285 and parameters: {'l1_ratio': 0.022395157685824067}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:13:15,104] Trial 83 finished with value: 0.725030110262877 and parameters: {'l1_ratio': 0.02038107599350536}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 04:13:42,349] Trial 84 finished with value: 0.7331382485326908 and parameters: {'l1_ratio': 0.08560547684917591}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 04:14:06,422] Trial 85 finished with value: 0.7250859040272457 and parameters: {'l1_ratio': 0.0006181227016955303}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 04:14:32,002] Trial 86 finished with value: 0.7447973769646922 and parameters: {'l1_ratio': 0.05150961425445736}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 04:14:58,514] Trial 87 finished with value: 0.7281873124620599 and parameters: {'l1_ratio': 0.10585635979685737}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 04:15:23,095] Trial 88 finished with value: 0.7509309699665535 and parameters: {'l1_ratio': 0.024361457891679393}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 04:15:50,087] Trial 89 finished with value: 0.7220143896389007 and parameters: {'l1_ratio': 0.14521963516600056}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 04:16:16,178] Trial 90 finished with value: 0.7285547892717437 and parameters: {'l1_ratio': 0.06720585451810077}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 04:16:41,133] Trial 91 finished with value: 0.7510455612576153 and parameters: {'l1_ratio': 0.023743976297338345}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:17:05,189] Trial 92 finished with value: 0.7258959111286778 and parameters: {'l1_ratio': 0.021585189498343642}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 04:17:31,286] Trial 93 finished with value: 0.7321578563758281 and parameters: {'l1_ratio': 0.08696319768929298}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:17:56,654] Trial 94 finished with value: 0.7519845283937656 and parameters: {'l1_ratio': 0.023058812654591355}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 04:18:22,443] Trial 95 finished with value: 0.7447973769646922 and parameters: {'l1_ratio': 0.05152429020883781}. Best is trial 82 with value: 0.7529649205506285.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 04:18:47,280] Trial 96 finished with value: 0.7501383353711021 and parameters: {'l1_ratio': 0.02227510753274366}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.6497890295358649
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 04:19:15,288] Trial 97 finished with value: 0.6824886325784305 and parameters: {'l1_ratio': 0.6242322112672503}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 04:19:38,027] Trial 98 finished with value: 0.7250859040272457 and parameters: {'l1_ratio': 0.0014780654096449436}. Best is trial 82 with value: 0.7529649205506285.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.7254901960784313
Fold 4 C-index: 0.7172995780590717

[I 2024-04-18 04:20:04,385] A new study created in memory with name: no-name-10f9cc86-8ce7-43dd-b0ac-d90b526e5a78

Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 04:20:04,366] Trial 99 finished with value: 0.7255800876242814 and parameters: {'l1_ratio': 0.12340583973321426}. Best is trial 82 with value: 0.7529649205506285.


* Best trial for C-index:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.7529649205506285], datetime_start=datetime.datetime(2024, 4, 18, 4, 12, 25, 155079), datetime_complete=datetime.datetime(2024, 4, 18, 4, 12, 50, 336016), params={'l1_ratio': 0.022395157685824067}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=82, value=None)


* Best Score for C-index:
 0.7529649205506285

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18794653865421088
Fold 2 IBS: 0.26160300244411944
Fold 3 IBS: 0.28499323418158673
Fold 4 IBS: 0.37889222817047347
Fold 5 IBS: 0.33256810688981997
[I 2024-04-18 04:20:33,833] Trial 0 finished with value: 0.2892006220680421 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2892006220680421.
Fold 1 IBS: 0.1851004644537256
Fold 2 IBS: 0.23181203791678803
Fold 3 IBS: 0.25749421908055464
Fold 4 IBS: 0.2982983305423583
Fold 5 IBS: 0.31018586605458565
[I 2024-04-18 04:21:00,967] Trial 1 finished with value: 0.2565781836096025 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.2565781836096025.
Fold 1 IBS: 0.18500316807064598
Fold 2 IBS: 0.22643389657788915
Fold 3 IBS: 0.24787833814277196
Fold 4 IBS: 0.27820420873175505
Fold 5 IBS: 0.30188670644796195
[I 2024-04-18 04:21:27,099] Trial 2 finished with value: 0.24788126359420484 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.1836577564603465
Fold 2 IBS: 0.24708069682209008
Fold 3 IBS: 0.2795379958459555
Fold 4 IBS: 0.3597610961309764
Fold 5 IBS: 0.32905021473556334
[I 2024-04-18 04:21:54,266] Trial 3 finished with value: 0.2798175519989864 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.18873553483368266
Fold 2 IBS: 0.26412756749367305
Fold 3 IBS: 0.28594828586349336
Fold 4 IBS: 0.3818105892166553
Fold 5 IBS: 0.33331608984427724
[I 2024-04-18 04:22:23,468] Trial 4 finished with value: 0.2907876134503563 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.1840162712049819
Fold 2 IBS: 0.2390471966360185
Fold 3 IBS: 0.2717362317493549
Fold 4 IBS: 0.33673879369852044
Fold 5 IBS: 0.32287563623151333
[I 2024-04-18 04:22:50,459] Trial 5 finished with value: 0.2708828259040778 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.21233126114675627
Fold 2 IBS: 0.3513839877163349
Fold 3 IBS: 0.2983393080098776
Fold 4 IBS: 0.35026438583113634
Fold 5 IBS: 0.3500805058955989
[I 2024-04-18 04:23:20,326] Trial 6 finished with value: 0.31247988971994084 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.18734249170225364
Fold 2 IBS: 0.2602195468838447
Fold 3 IBS: 0.28484023871897296
Fold 4 IBS: 0.3774507490818262
Fold 5 IBS: 0.3322591500769251
[I 2024-04-18 04:23:47,930] Trial 7 finished with value: 0.2884224352927645 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.18401159512692528
Fold 2 IBS: 0.24203929094873394
Fold 3 IBS: 0.27583379474087
Fold 4 IBS: 0.3487262568449446
Fold 5 IBS: 0.32621428222877097
[I 2024-04-18 04:24:15,223] Trial 8 finished with value: 0.27536504397804895 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.18423986387580907
Fold 2 IBS: 0.2378944285524119
Fold 3 IBS: 0.26920123683417296
Fold 4 IBS: 0.32898879095102357
Fold 5 IBS: 0.3205756280377108
[I 2024-04-18 04:24:41,411] Trial 9 finished with value: 0.26817998965022566 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.24788126359420484.
Fold 1 IBS: 0.18879071110762796
Fold 2 IBS: 0.20986156651643764
Fold 3 IBS: 0.2043374741435942
Fold 4 IBS: 0.2308693947952237
Fold 5 IBS: 0.2657141776604926
[I 2024-04-18 04:25:06,203] Trial 10 finished with value: 0.21991466484467526 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.21991466484467526.
Fold 1 IBS: 0.2134514400391762
Fold 2 IBS: 0.22127067094363234
Fold 3 IBS: 0.2037962027189473
Fold 4 IBS: 0.22442032798535133
Fold 5 IBS: 0.21762627249040964
[I 2024-04-18 04:25:28,721] Trial 11 finished with value: 0.21611298283550337 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 11 with value: 0.21611298283550337.
Fold 1 IBS: 0.20157915361345066
Fold 2 IBS: 0.22094184868690322
Fold 3 IBS: 0.1659202137754282
Fold 4 IBS: 0.22408765061617184
Fold 5 IBS: 0.2387214368947456
[I 2024-04-18 04:25:52,547] Trial 12 finished with value: 0.21025006071733993 and parameters: {'l1_ratio': 0.025939717088620355}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.21377069127505616
Fold 2 IBS: 0.2214628347299675
Fold 3 IBS: 0.20424548218544103
Fold 4 IBS: 0.22461817256070624
Fold 5 IBS: 0.21793340872131284
[I 2024-04-18 04:26:15,950] Trial 13 finished with value: 0.21640611789449676 and parameters: {'l1_ratio': 0.004533947374774427}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18604820313486528
Fold 2 IBS: 0.2167322654301558
Fold 3 IBS: 0.22760065262689932
Fold 4 IBS: 0.24942130926376796
Fold 5 IBS: 0.28501688707757694
[I 2024-04-18 04:26:41,919] Trial 14 finished with value: 0.23296386350665305 and parameters: {'l1_ratio': 0.14337364566668}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.21368373719427777
Fold 2 IBS: 0.22141208243034227
Fold 3 IBS: 0.20412132906564273
Fold 4 IBS: 0.22456555557875466
Fold 5 IBS: 0.217850224261304
[I 2024-04-18 04:27:04,757] Trial 15 finished with value: 0.21632658570606428 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18514832410621798
Fold 2 IBS: 0.22469319212550418
Fold 3 IBS: 0.24542524956576886
Fold 4 IBS: 0.273455435239688
Fold 5 IBS: 0.29972869891299697
[I 2024-04-18 04:27:29,617] Trial 16 finished with value: 0.2456901799900352 and parameters: {'l1_ratio': 0.21332970570491078}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1853484003865962
Fold 2 IBS: 0.23353396002211324
Fold 3 IBS: 0.26087834039475066
Fold 4 IBS: 0.3066585707145195
Fold 5 IBS: 0.3136644540234804
[I 2024-04-18 04:27:55,345] Trial 17 finished with value: 0.26001674510829204 and parameters: {'l1_ratio': 0.31307066649676046}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18699717326933543
Fold 2 IBS: 0.214679217609738
Fold 3 IBS: 0.22024137791701154
Fold 4 IBS: 0.24181510380223104
Fold 5 IBS: 0.27848308211025014
[I 2024-04-18 04:28:22,156] Trial 18 finished with value: 0.22844319094171323 and parameters: {'l1_ratio': 0.12120380780234859}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18830661497887694
Fold 2 IBS: 0.21138741541974337
Fold 3 IBS: 0.2081519108213873
Fold 4 IBS: 0.2333092419465919
Fold 5 IBS: 0.2687175484063121
[I 2024-04-18 04:28:48,358] Trial 19 finished with value: 0.2219745463145823 and parameters: {'l1_ratio': 0.09170436955756033}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.21201785674978105
Fold 2 IBS: 0.34281561250650877
Fold 3 IBS: 0.2976839282135737
Fold 4 IBS: 0.35544817024635644
Fold 5 IBS: 0.348594039792132
[I 2024-04-18 04:29:16,668] Trial 20 finished with value: 0.3113119215016704 and parameters: {'l1_ratio': 0.9656427853442138}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.21357754360688325
Fold 2 IBS: 0.22134827359731046
Fold 3 IBS: 0.20396853154914527
Fold 4 IBS: 0.22449961802283191
Fold 5 IBS: 0.21774649709722566
[I 2024-04-18 04:29:38,709] Trial 21 finished with value: 0.2162280927746793 and parameters: {'l1_ratio': 0.009107838351343097}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.21320885563416855
Fold 2 IBS: 0.22110699474513104
Fold 3 IBS: 0.20343920116395442
Fold 4 IBS: 0.22425378761940593
Fold 5 IBS: 0.23422450337059975
[I 2024-04-18 04:30:02,028] Trial 22 finished with value: 0.21924666850665195 and parameters: {'l1_ratio': 0.018997068950600285}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18563267321113855
Fold 2 IBS: 0.21959267667124144
Fold 3 IBS: 0.23529043941143785
Fold 4 IBS: 0.2584997618455432
Fold 5 IBS: 0.29139398014542883
[I 2024-04-18 04:30:27,137] Trial 23 finished with value: 0.23808190625695796 and parameters: {'l1_ratio': 0.16991532695760067}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18530757041413973
Fold 2 IBS: 0.2336721946313016
Fold 3 IBS: 0.26118742657094757
Fold 4 IBS: 0.3075946882370528
Fold 5 IBS: 0.3139574582445006
[I 2024-04-18 04:30:53,282] Trial 24 finished with value: 0.2603438676195885 and parameters: {'l1_ratio': 0.31612098478358897}. Best is trial 12 with value: 0.21025006071733993.

Fold 1 IBS: 0.1886783645535632
Fold 2 IBS: 0.21041644126736042
Fold 3 IBS: 0.2054630322886
Fold 4 IBS: 0.23163040552306483
Fold 5 IBS: 0.2666400705889357
[I 2024-04-18 04:31:19,333] Trial 25 finished with value: 0.22056566284430482 and parameters: {'l1_ratio': 0.0861486623508641}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18511999812868693
Fold 2 IBS: 0.22725446344072614
Fold 3 IBS: 0.24922821097430353
Fold 4 IBS: 0.2809228106336443
Fold 5 IBS: 0.30324147396616297
[I 2024-04-18 04:31:44,593] Trial 26 finished with value: 0.24915339142870474 and parameters: {'l1_ratio': 0.23521758130887002}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1997523133624926
Fold 2 IBS: 0.29601537826867064
Fold 3 IBS: 0.2910628698762797
Fold 4 IBS: 0.3814530039898754
Fold 5 IBS: 0.340768470315745
[I 2024-04-18 04:32:12,023] Trial 27 finished with value: 0.30181040716261265 and parameters: {'l1_ratio': 0.8345729974660353}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19364088430215304
Fold 2 IBS: 0.22035809660080843
Fold 3 IBS: 0.1855347589635687
Fold 4 IBS: 0.22352860795505494
Fold 5 IBS: 0.25197160601908275
[I 2024-04-18 04:32:36,106] Trial 28 finished with value: 0.21500679076813353 and parameters: {'l1_ratio': 0.05113204996404917}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18568024502213346
Fold 2 IBS: 0.21918967895274052
Fold 3 IBS: 0.23445211561228632
Fold 4 IBS: 0.25755761528832255
Fold 5 IBS: 0.29075586418180527
[I 2024-04-18 04:33:01,383] Trial 29 finished with value: 0.2375271038114576 and parameters: {'l1_ratio': 0.16695914539461998}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18923969889466558
Fold 2 IBS: 0.20868348530364778
Fold 3 IBS: 0.20188508820284762
Fold 4 IBS: 0.22298479926120512
Fold 5 IBS: 0.2638162539541084
[I 2024-04-18 04:33:25,359] Trial 30 finished with value: 0.21732186512329493 and parameters: {'l1_ratio': 0.07881194745858378}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.21397056565777256
Fold 2 IBS: 0.2215746825695051
Fold 3 IBS: 0.20452760897470723
Fold 4 IBS: 0.22473466173428758
Fold 5 IBS: 0.21811890556320687
[I 2024-04-18 04:33:47,794] Trial 31 finished with value: 0.21658528489989587 and parameters: {'l1_ratio': 0.00012661512081217803}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1919042611477901
Fold 2 IBS: 0.22017914749132605
Fold 3 IBS: 0.1907788076827455
Fold 4 IBS: 0.2233659476115868
Fold 5 IBS: 0.2554957882022814
[I 2024-04-18 04:34:13,089] Trial 32 finished with value: 0.21634479042714597 and parameters: {'l1_ratio': 0.0590523030616818}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1850140845978442
Fold 2 IBS: 0.2253095486084394
Fold 3 IBS: 0.2463116315847793
Fold 4 IBS: 0.2750930327356779
Fold 5 IBS: 0.3005872020913551
[I 2024-04-18 04:34:39,807] Trial 33 finished with value: 0.2464630999236192 and parameters: {'l1_ratio': 0.21840259574986878}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1856505019698117
Fold 2 IBS: 0.219743053298927
Fold 3 IBS: 0.23556030646218393
Fold 4 IBS: 0.2588486181978414
Fold 5 IBS: 0.2916472917273282
[I 2024-04-18 04:35:04,672] Trial 34 finished with value: 0.23828995433121847 and parameters: {'l1_ratio': 0.1709872376770914}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18519034625179243
Fold 2 IBS: 0.23133601751291116
Fold 3 IBS: 0.25656056227153806
Fold 4 IBS: 0.2962247245386182
Fold 5 IBS: 0.3093335278842914
[I 2024-04-18 04:35:30,448] Trial 35 finished with value: 0.25572903569183025 and parameters: {'l1_ratio': 0.2797641856780416}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18388290765097537
Fold 2 IBS: 0.2486158912467762
Fold 3 IBS: 0.28016779903530153
Fold 4 IBS: 0.36141262464871515
Fold 5 IBS: 0.3295672809946897
[I 2024-04-18 04:35:56,896] Trial 36 finished with value: 0.2807293007152916 and parameters: {'l1_ratio': 0.5659743178706899}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19731205705486332
Fold 2 IBS: 0.2206308613843358
Fold 3 IBS: 0.1767225570553592
Fold 4 IBS: 0.22378353793582756
Fold 5 IBS: 0.24621359545184235
[I 2024-04-18 04:36:21,483] Trial 37 finished with value: 0.21293252177644564 and parameters: {'l1_ratio': 0.03927416149637669}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1841670280528726
Fold 2 IBS: 0.23758139444123247
Fold 3 IBS: 0.26870598848497357
Fold 4 IBS: 0.3276892263105098
Fold 5 IBS: 0.32014702521029237
[I 2024-04-18 04:36:47,394] Trial 38 finished with value: 0.26765813249997616 and parameters: {'l1_ratio': 0.38597615937031754}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18669624916375752
Fold 2 IBS: 0.2155283601672244
Fold 3 IBS: 0.22275614108399816
Fold 4 IBS: 0.24427772975694523
Fold 5 IBS: 0.28057502198539275
[I 2024-04-18 04:37:12,647] Trial 39 finished with value: 0.2299667004314636 and parameters: {'l1_ratio': 0.1283397909515303}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1915051065160471
Fold 2 IBS: 0.2201328836372598
Fold 3 IBS: 0.19203618697433386
Fold 4 IBS: 0.22332447552671433
Fold 5 IBS: 0.2564263143311533
[I 2024-04-18 04:37:36,173] Trial 40 finished with value: 0.2166849933971017 and parameters: {'l1_ratio': 0.06111847519545227}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1934301832534372
Fold 2 IBS: 0.22033568521245492
Fold 3 IBS: 0.18621089657904039
Fold 4 IBS: 0.22350803961445653
Fold 5 IBS: 0.2523993265787978
[I 2024-04-18 04:38:00,125] Trial 41 finished with value: 0.21517682624763737 and parameters: {'l1_ratio': 0.0521177847645341}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19341418537330463
Fold 2 IBS: 0.22033374508961112
Fold 3 IBS: 0.18627083509307482
Fold 4 IBS: 0.22350626170890256
Fold 5 IBS: 0.2524377075876691
[I 2024-04-18 04:38:24,775] Trial 42 finished with value: 0.21519254697051243 and parameters: {'l1_ratio': 0.05220320125073802}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19174178507285133
Fold 2 IBS: 0.22016193364699288
Fold 3 IBS: 0.19124393075200655
Fold 4 IBS: 0.22335048901666987
Fold 5 IBS: 0.2558242986967773
[I 2024-04-18 04:38:49,710] Trial 43 finished with value: 0.2164644874370596 and parameters: {'l1_ratio': 0.059820186386939866}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.18715952414490575
Fold 2 IBS: 0.21408405957495494
Fold 3 IBS: 0.2186402731586076
Fold 4 IBS: 0.24029223915677442
Fold 5 IBS: 0.27701565936243205
[I 2024-04-18 04:39:15,595] Trial 44 finished with value: 0.22743835107953495 and parameters: {'l1_ratio': 0.11670570903522565}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.185549037867553
Fold 2 IBS: 0.22140512076395372
Fold 3 IBS: 0.23914078517471019
Fold 4 IBS: 0.263996479025576
Fold 5 IBS: 0.29463671222882504
[I 2024-04-18 04:39:42,053] Trial 45 finished with value: 0.2409456270121236 and parameters: {'l1_ratio': 0.18532945468239503}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19366560536395536
Fold 2 IBS: 0.22035429659796243
Fold 3 IBS: 0.1856586011210552
Fold 4 IBS: 0.22352511645774906
Fold 5 IBS: 0.25204248543223595
[I 2024-04-18 04:40:06,719] Trial 46 finished with value: 0.21504922099459162 and parameters: {'l1_ratio': 0.05129906415993883}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.185341615855299
Fold 2 IBS: 0.22886433492971633
Fold 3 IBS: 0.2526564939505168
Fold 4 IBS: 0.28747409383844924
Fold 5 IBS: 0.30587837637214443
[I 2024-04-18 04:40:32,759] Trial 47 finished with value: 0.2520429829892252 and parameters: {'l1_ratio': 0.2539570594551466}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1839032772049617
Fold 2 IBS: 0.2486931087473169
Fold 3 IBS: 0.2802280347095497
Fold 4 IBS: 0.36170242512007206
Fold 5 IBS: 0.32963330275510827
[I 2024-04-18 04:41:00,108] Trial 48 finished with value: 0.28083202970740173 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1866771631588325
Fold 2 IBS: 0.21555236018195437
Fold 3 IBS: 0.22309294798489357
Fold 4 IBS: 0.24459104917182053
Fold 5 IBS: 0.2808480074908706
[I 2024-04-18 04:41:25,436] Trial 49 finished with value: 0.23015230559767427 and parameters: {'l1_ratio': 0.12920872319413595}. Best is trial 12 with value: 0.21025006071733993.

Fold 1 IBS: 0.19680688470972987
Fold 2 IBS: 0.22059349240521664
Fold 3 IBS: 0.17790674695647057
Fold 4 IBS: 0.22374810517623409
Fold 5 IBS: 0.24705340079146137
[I 2024-04-18 04:41:49,911] Trial 50 finished with value: 0.2132217260078225 and parameters: {'l1_ratio': 0.04088364878367627}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19755520757290046
Fold 2 IBS: 0.22065105806317759
Fold 3 IBS: 0.17600353880473255
Fold 4 IBS: 0.22380275595019244
Fold 5 IBS: 0.24576191296373862
[I 2024-04-18 04:42:14,527] Trial 51 finished with value: 0.21275489467094832 and parameters: {'l1_ratio': 0.03840625231138948}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1876867489201972
Fold 2 IBS: 0.21276180085856197
Fold 3 IBS: 0.21328703368625607
Fold 4 IBS: 0.23657773218133069
Fold 5 IBS: 0.2727641534627712
[I 2024-04-18 04:42:39,426] Trial 52 finished with value: 0.22461549382182344 and parameters: {'l1_ratio': 0.1036080990209961}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19963690638674883
Fold 2 IBS: 0.22079432525175385
Fold 3 IBS: 0.17116595562499637
Fold 4 IBS: 0.2239408492071646
Fold 5 IBS: 0.24242342932264777
[I 2024-04-18 04:43:03,244] Trial 53 finished with value: 0.2115922931586623 and parameters: {'l1_ratio': 0.03227173590052892}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.1844432915427957
Fold 2 IBS: 0.254085162271486
Fold 3 IBS: 0.28278961254102747
Fold 4 IBS: 0.37141498980757565
Fold 5 IBS: 0.33105707609458224
[I 2024-04-18 04:43:29,784] Trial 54 finished with value: 0.2847580264514934 and parameters: {'l1_ratio': 0.6304504906551746}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.19901114998723662
Fold 2 IBS: 0.22075186335152028
Fold 3 IBS: 0.17260706098855447
Fold 4 IBS: 0.2238993923189694
Fold 5 IBS: 0.24341073184627324
[I 2024-04-18 04:43:53,581] Trial 55 finished with value: 0.21193603969851077 and parameters: {'l1_ratio': 0.034094833872978784}. Best is trial 12 with value: 0.21025006071733993.
Fold 1 IBS: 0.2019122853348499
Fold 2 IBS: 0.22096607948798808
Fold 3 IBS: 0.16507780464678223
Fold 4 IBS: 0.2241119077014024
Fold 5 IBS: 0.23808867341395473
[I 2024-04-18 04:44:17,900] Trial 56 finished with value: 0.21003135011699547 and parameters: {'l1_ratio': 0.024911547309691535}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.1858537657772499
Fold 2 IBS: 0.21742765418930976
Fold 3 IBS: 0.230072741550319
Fold 4 IBS: 0.2521578938654148
Fold 5 IBS: 0.28705353913901044
[I 2024-04-18 04:44:45,166] Trial 57 finished with value: 0.23451311890426077 and parameters: {'l1_ratio': 0.15111685643084957}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.18808967604422638
Fold 2 IBS: 0.21191596589585876
Fold 3 IBS: 0.2103514095967255
Fold 4 IBS: 0.23471061878485702
Fold 5 IBS: 0.27042457325256203
[I 2024-04-18 04:45:13,789] Trial 58 finished with value: 0.2230984487148459 and parameters: {'l1_ratio': 0.09668203966586397}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.1841072739205467
Fold 2 IBS: 0.24159742930986214
Fold 3 IBS: 0.2751040746381737
Fold 4 IBS: 0.34728021721951263
Fold 5 IBS: 0.3258499746995493
[I 2024-04-18 04:45:40,392] Trial 59 finished with value: 0.2747877939575289 and parameters: {'l1_ratio': 0.4720631387381872}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.1854103833366283
Fold 2 IBS: 0.22274355016861305
Fold 3 IBS: 0.24147186303033008
Fold 4 IBS: 0.2670502637846284
Fold 5 IBS: 0.29648502933840315
[I 2024-04-18 04:46:06,927] Trial 60 finished with value: 0.24263221793172057 and parameters: {'l1_ratio': 0.19470305580670896}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.19955218811538852
Fold 2 IBS: 0.2207891618720381
Fold 3 IBS: 0.17133447901172888
Fold 4 IBS: 0.22393573851580037
Fold 5 IBS: 0.2425423288248183
[I 2024-04-18 04:46:31,026] Trial 61 finished with value: 0.21163077926795487 and parameters: {'l1_ratio': 0.03249563624031122}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.19789188618447665
Fold 2 IBS: 0.2206746926283495
Fold 3 IBS: 0.17521320344330676
Fold 4 IBS: 0.22382530586509106
Fold 5 IBS: 0.2452090317350088
[I 2024-04-18 04:46:55,368] Trial 62 finished with value: 0.21256282397124654 and parameters: {'l1_ratio': 0.03739235181456524}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.2139712481007277
Fold 2 IBS: 0.22157505345661793
Fold 3 IBS: 0.20452856454332288
Fold 4 IBS: 0.22473504922191848
Fold 5 IBS: 0.21811952571836482
[I 2024-04-18 04:47:17,400] Trial 63 finished with value: 0.21658588820819036 and parameters: {'l1_ratio': 0.00011209480789966392}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.18779507597365708
Fold 2 IBS: 0.21249554256532646
Fold 3 IBS: 0.2125770081051497
Fold 4 IBS: 0.23612165328492263
Fold 5 IBS: 0.2721698048228259
[I 2024-04-18 04:47:41,779] Trial 64 finished with value: 0.22423181695037636 and parameters: {'l1_ratio': 0.10181510606627761}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.2012341320127694
Fold 2 IBS: 0.22091307706932045
Fold 3 IBS: 0.1668717204872316
Fold 4 IBS: 0.22405890091372518
Fold 5 IBS: 0.23948007558307996
[I 2024-04-18 04:48:06,223] Trial 65 finished with value: 0.2105115812132253 and parameters: {'l1_ratio': 0.02716487569601156}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.18607946897969826
Fold 2 IBS: 0.21670454321907884
Fold 3 IBS: 0.22735862094448986
Fold 4 IBS: 0.24919286033711613
Fold 5 IBS: 0.2848404548075553
[I 2024-04-18 04:48:32,428] Trial 66 finished with value: 0.2328351896575877 and parameters: {'l1_ratio': 0.14268834041817288}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.19601488536973943
Fold 2 IBS: 0.28239809327156623
Fold 3 IBS: 0.28864691927228275
Fold 4 IBS: 0.3836352186797365
Fold 5 IBS: 0.3376816128872916
[I 2024-04-18 04:49:00,562] Trial 67 finished with value: 0.2976753458961233 and parameters: {'l1_ratio': 0.7965604964350725}. Best is trial 56 with value: 0.21003135011699547.
Fold 1 IBS: 0.20214924402259174
Fold 2 IBS: 0.22098614702084912
Fold 3 IBS: 0.16439576802867073
Fold 4 IBS: 0.22413202798578508
Fold 5 IBS: 0.23751170516771025
[I 2024-04-18 04:49:24,049] Trial 68 finished with value: 0.2098349784451214 and parameters: {'l1_ratio': 0.02406253484295639}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.1890382768882829
Fold 2 IBS: 0.20925411323447987
Fold 3 IBS: 0.2030619390450443
Fold 4 IBS: 0.222941734483933
Fold 5 IBS: 0.26469713874874723
[I 2024-04-18 04:49:49,293] Trial 69 finished with value: 0.21779864048009748 and parameters: {'l1_ratio': 0.0811592088791159}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.21319592824528014
Fold 2 IBS: 0.22109823775535184
Fold 3 IBS: 0.20342072409334983
Fold 4 IBS: 0.2242449302632925
Fold 5 IBS: 0.23445744306935193
[I 2024-04-18 04:50:13,867] Trial 70 finished with value: 0.21928345268532526 and parameters: {'l1_ratio': 0.019361425222415376}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.20210779527232237
Fold 2 IBS: 0.22098152992555753
Fold 3 IBS: 0.1645478695405571
Fold 4 IBS: 0.22412739626653744
Fold 5 IBS: 0.23769164310476873
[I 2024-04-18 04:50:37,530] Trial 71 finished with value: 0.20989124682194862 and parameters: {'l1_ratio': 0.024257673773912518}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.21314544205731525
Fold 2 IBS: 0.22106377114982745
Fold 3 IBS: 0.203348577711792
Fold 4 IBS: 0.22421012069604035
Fold 5 IBS: 0.23540233095485594
[I 2024-04-18 04:51:00,812] Trial 72 finished with value: 0.21943404851396617 and parameters: {'l1_ratio': 0.0207995730510049}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.1894388682947606
Fold 2 IBS: 0.20800886207829689
Fold 3 IBS: 0.20035736272233046
Fold 4 IBS: 0.22303972554670484
Fold 5 IBS: 0.26261289592089454
[I 2024-04-18 04:51:25,479] Trial 73 finished with value: 0.21669154291259746 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.21386531734077552
Fold 2 IBS: 0.22151659987936834
Fold 3 IBS: 0.20437961165532134
Fold 4 IBS: 0.22467407781580662

Fold 5 IBS: 0.21802220001630135
[I 2024-04-18 04:51:47,280] Trial 74 finished with value: 0.21649156134151465 and parameters: {'l1_ratio': 0.0024082397705825313}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.18713776288010345
Fold 2 IBS: 0.21415584059731327
Fold 3 IBS: 0.21897376815099812
Fold 4 IBS: 0.24055905612506784
Fold 5 IBS: 0.277284314188442
[I 2024-04-18 04:52:12,505] Trial 75 finished with value: 0.22762214838838496 and parameters: {'l1_ratio': 0.1176051017445135}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.1891424886558718
Fold 2 IBS: 0.2090637464903817
Fold 3 IBS: 0.20273246646212909
Fold 4 IBS: 0.2229542737140009
Fold 5 IBS: 0.2644368439058008
[I 2024-04-18 04:52:37,187] Trial 76 finished with value: 0.21766596384563686 and parameters: {'l1_ratio': 0.08047320826246168}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.20279705638688392
Fold 2 IBS: 0.2210376400175663
Fold 3 IBS: 0.20329448071318942
Fold 4 IBS: 0.22418378485909968
Fold 5 IBS: 0.2361165393650749
[I 2024-04-18 04:53:00,319] Trial 77 finished with value: 0.21748590026836281 and parameters: {'l1_ratio': 0.021894273568164917}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.185696595731799
Fold 2 IBS: 0.21827373034333603
Fold 3 IBS: 0.23249966823123694
Fold 4 IBS: 0.2550409004984099
Fold 5 IBS: 0.2891947455361066
[I 2024-04-18 04:53:25,632] Trial 78 finished with value: 0.2361411280681777 and parameters: {'l1_ratio': 0.15989344119932394}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.18901687940091846
Fold 2 IBS: 0.20927794245552975
Fold 3 IBS: 0.20314055203589515
Fold 4 IBS: 0.222938959014725
Fold 5 IBS: 0.2647479604545466
[I 2024-04-18 04:53:50,783] Trial 79 finished with value: 0.21782445867232297 and parameters: {'l1_ratio': 0.0813113347667199}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.20055272627246507
Fold 2 IBS: 0.22086456247603586
Fold 3 IBS: 0.16864812195920795
Fold 4 IBS: 0.22401055381134394
Fold 5 IBS: 0.24068856735443617
[I 2024-04-18 04:54:15,554] Trial 80 finished with value: 0.21095290637469782 and parameters: {'l1_ratio': 0.02924141187656099}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.20038313721371875
Fold 2 IBS: 0.2208528245064169
Fold 3 IBS: 0.16906275890649303
Fold 4 IBS: 0.22399888097502815
Fold 5 IBS: 0.24098086240534047
[I 2024-04-18 04:54:39,274] Trial 81 finished with value: 0.2110556928013995 and parameters: {'l1_ratio': 0.029745851153293923}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.21395202276838818
Fold 2 IBS: 0.2215645771862137
Fold 3 IBS: 0.20450162489922327
Fold 4 IBS: 0.22472410711021462
Fold 5 IBS: 0.2181020214466855
[I 2024-04-18 04:55:01,283] Trial 82 finished with value: 0.21656887068214506 and parameters: {'l1_ratio': 0.00052248172936048}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.18755230797714043
Fold 2 IBS: 0.21293413976823672
Fold 3 IBS: 0.21409722901306003
Fold 4 IBS: 0.2371095659068094
Fold 5 IBS: 0.27344320617038387
[I 2024-04-18 04:55:26,062] Trial 83 finished with value: 0.22502728976712608 and parameters: {'l1_ratio': 0.10549308997926854}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.19095843965066328
Fold 2 IBS: 0.20494690177619918
Fold 3 IBS: 0.19352254682556
Fold 4 IBS: 0.22327380750793394
Fold 5 IBS: 0.257543823853974
[I 2024-04-18 04:55:50,279] Trial 84 finished with value: 0.21404910392286608 and parameters: {'l1_ratio': 0.06366949303606506}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.1865359635696961
Fold 2 IBS: 0.2159907863358465
Fold 3 IBS: 0.224217579295056
Fold 4 IBS: 0.2457649027762064
Fold 5 IBS: 0.2818311308420193
[I 2024-04-18 04:56:16,308] Trial 85 finished with value: 0.23086807256376485 and parameters: {'l1_ratio': 0.13257827709423287}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.19691651688512135
Fold 2 IBS: 0.2206015082149173
Fold 3 IBS: 0.17766989360909952
Fold 4 IBS: 0.2237556919645849
Fold 5 IBS: 0.24688342365168844
[I 2024-04-18 04:56:41,399] Trial 86 finished with value: 0.21316540686508229 and parameters: {'l1_ratio': 0.04053800826929621}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.19049562985812096
Fold 2 IBS: 0.20582896095761347
Fold 3 IBS: 0.1955787167299344
Fold 4 IBS: 0.22320611091202985
Fold 5 IBS: 0.2590341256108734
[I 2024-04-18 04:57:06,004] Trial 87 finished with value: 0.21482870881371446 and parameters: {'l1_ratio': 0.06712467834424898}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.18473833655402896
Fold 2 IBS: 0.23613341303156574
Fold 3 IBS: 0.2662800229253572
Fold 4 IBS: 0.3202954772913829
Fold 5 IBS: 0.3179712347667093
[I 2024-04-18 04:57:31,851] Trial 88 finished with value: 0.2650836969138088 and parameters: {'l1_ratio': 0.35921331762209774}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.20002949536420453
Fold 2 IBS: 0.22082437227781052
Fold 3 IBS: 0.17008252900363302
Fold 4 IBS: 0.22397062639586074
Fold 5 IBS: 0.24169863121692012
[I 2024-04-18 04:57:55,379] Trial 89 finished with value: 0.21132113085168575 and parameters: {'l1_ratio': 0.0309718845268796}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.18542914904476185
Fold 2 IBS: 0.2225433500487035
Fold 3 IBS: 0.2410680763813295
Fold 4 IBS: 0.2664777593108327
Fold 5 IBS: 0.29611836941255765
[I 2024-04-18 04:58:21,537] Trial 90 finished with value: 0.242327340839637 and parameters: {'l1_ratio': 0.1928719062860607}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.20183526791269488
Fold 2 IBS: 0.22096039455019886
Fold 3 IBS: 0.16526848863232932
Fold 4 IBS: 0.22410621292287405
Fold 5 IBS: 0.23823429487463488
[I 2024-04-18 04:58:45,533] Trial 91 finished with value: 0.21008093177854636 and parameters: {'l1_ratio': 0.025152475506538482}. Best is trial 68 with value: 0.2098349784451214.
Fold 1 IBS: 0.20252429639389885
Fold 2 IBS: 0.22100888135963132
Fold 3 IBS: 0.1637133263882886
Fold 4 IBS: 0.22415485601713284
Fold 5 IBS: 0.2369606041294879
[I 2024-04-18 04:59:10,546] Trial 92 finished with value: 0.20967239285768788 and parameters: {'l1_ratio': 0.023103419286485582}. Best is trial 92 with value: 0.20967239285768788.
Fold 1 IBS: 0.18810748958380766
Fold 2 IBS: 0.21181159084301138
Fold 3 IBS: 0.20998459466732666
Fold 4 IBS: 0.23448035405839243
Fold 5 IBS: 0.27018487943957115
[I 2024-04-18 04:59:35,515] Trial 93 finished with value: 0.22291378171842186 and parameters: {'l1_ratio': 0.09596770327139656}. Best is trial 92 with value: 0.20967239285768788.
Fold 1 IBS: 0.21317597180746578
Fold 2 IBS: 0.2210846645113884
Fold 3 IBS: 0.20339220303387615
Fold 4 IBS: 0.22423121204794397
Fold 5 IBS: 0.2348235124047663
[I 2024-04-18 04:59:58,452] Trial 94 finished with value: 0.2193415127610881 and parameters: {'l1_ratio': 0.019927002384945033}. Best is trial 92 with value: 0.20967239285768788.
Fold 1 IBS: 0.1910743396240632
Fold 2 IBS: 0.20480563015689912
Fold 3 IBS: 0.19317578253543746
Fold 4 IBS: 0.22328490263877906
Fold 5 IBS: 0.2573049391931298
[I 2024-04-18 05:00:23,471] Trial 95 finished with value: 0.21392911882966176 and parameters: {'l1_ratio': 0.06310834066617435}. Best is trial 92 with value: 0.20967239285768788.
Fold 1 IBS: 0.18723277353032267
Fold 2 IBS: 0.21404282274836542
Fold 3 IBS: 0.21810127124510748
Fold 4 IBS: 0.23984690119643493
Fold 5 IBS: 0.2766367945434394
[I 2024-04-18 05:00:49,049] Trial 96 finished with value: 0.22717211265273402 and parameters: {'l1_ratio': 0.11538802699991293}. Best is trial 92 with value: 0.20967239285768788.
Fold 1 IBS: 0.1928031887813902
Fold 2 IBS: 0.22027452254350557
Fold 3 IBS: 0.18806911720307085
Fold 4 IBS: 0.22345219473267597
Fold 5 IBS: 0.2535588926606905
[I 2024-04-18 05:01:14,294] Trial 97 finished with value: 0.21563158318426662 and parameters: {'l1_ratio': 0.05481692287858109}. Best is trial 92 with value: 0.20967239285768788.
Fold 1 IBS: 0.21390630255342372
Fold 2 IBS: 0.2215394288460002
Fold 3 IBS: 0.20443739228238492
Fold 4 IBS: 0.22469786649278853
Fold 5 IBS: 0.21806011164124672
[I 2024-04-18 05:01:36,930] Trial 98 finished with value: 0.2165282203631688 and parameters: {'l1_ratio': 0.0015096411495885767}. Best is trial 92 with value: 0.20967239285768788.

Fold 1 IBS: 0.1886593576885953
Fold 2 IBS: 0.21050054296640958
Fold 3 IBS: 0.2056396345482091
Fold 4 IBS: 0.2317394182543497
Fold 5 IBS: 0.26677120778113017
[I 2024-04-18 05:02:02,591] Trial 99 finished with value: 0.22066203224773878 and parameters: {'l1_ratio': 0.08650676983934198}. Best is trial 92 with value: 0.20967239285768788.


* Best trial for IBS:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.20967239285768788], datetime_start=datetime.datetime(2024, 4, 18, 4, 58, 45, 541205), datetime_complete=datetime.datetime(2024, 4, 18, 4, 59, 10, 544216), params={'l1_ratio': 0.023103419286485582}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=92, value=None)


* Best Score for IBS:
 0.20967239285768788

In [75]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.753
train_ibs:  0.21

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.022395157685824067)

test_cindex : 0.573

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.023103419286485582)

test_ibs:  0.221

In [79]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [80]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 05:02:03,014] A new study created in memory with name: no-name-b0b90f8f-ec6b-49f3-b385-873987dd70ca

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 05:03:19,740] Trial 0 finished with value: 0.7366032203169602 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 05:03:33,123] Trial 1 finished with value: 0.7181620567966567 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.6911764705882353
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.6948356807511737
[I 2024-04-18 05:03:43,953] Trial 2 finished with value: 0.7150860129299454 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:03:46,511] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:03:49,794] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 05:04:10,175] Trial 5 finished with value: 0.7100749491193421 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 05:05:26,488] Trial 6 finished with value: 0.727952663180055 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:05:32,425] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6056338028169014
[I 2024-04-18 05:05:52,549] Trial 8 finished with value: 0.5211267605633803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.704225352112676
[I 2024-04-18 05:06:07,253] Trial 9 finished with value: 0.7080431320407382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:06:08,613] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7366032203169602.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 05:06:54,731] Trial 11 finished with value: 0.7380484783177279 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 11 with value: 0.7380484783177279.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 05:07:59,877] Trial 12 finished with value: 0.7438602547617209 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4617373338142137, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 05:08:44,735] Trial 13 finished with value: 0.7433165908059199 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 20, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.430322282186733, 'max_features': None, 'min_weight_fraction_leaf': 0.1716937452680298, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:08:53,205] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.4652312819220314, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3866899818434614, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:09:12,853] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 491, 'oob_score': True, 'max_samples': 0.27229846028530913, 'max_features': None, 'min_weight_fraction_leaf': 0.20648604556011108, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.

Fold 1 C-index: 0.6038961038961039
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6032863849765259
[I 2024-04-18 05:09:18,586] Trial 16 finished with value: 0.6633327721070438 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': None, 'min_weight_fraction_leaf': 0.1048543527585735, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:09:34,901] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.1424705672746025, 'max_features': None, 'min_weight_fraction_leaf': 0.20205510510599584, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 05:09:44,162] Trial 18 finished with value: 0.7335541813688149 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5392320730567087, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07958856082174798, 'warm_start': True}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.6772151898734177
Fold 5 C-index: 0.5892018779342723
[I 2024-04-18 05:09:45,212] Trial 19 finished with value: 0.6638449108877411 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.5137509360533721, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16593096906146954, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:10:02,630] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8114307622571267, 'max_features': None, 'min_weight_fraction_leaf': 0.41597694280469266, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.729957805907173
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 05:10:44,686] Trial 21 finished with value: 0.7398700280611442 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.3990347915810166, 'max_features': None, 'min_weight_fraction_leaf': 0.14443114491291786, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:11:03,309] Trial 22 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.21351240485158024, 'max_features': None, 'min_weight_fraction_leaf': 0.2441929681165364, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 05:11:40,903] Trial 23 finished with value: 0.7271164711934142 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.3756805451824067, 'max_features': None, 'min_weight_fraction_leaf': 0.13775089899883528, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:12:06,279] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.36406078817327137, 'max_features': None, 'min_weight_fraction_leaf': 0.1822392883483817, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 05:12:22,680] Trial 25 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.4837577457111593, 'max_features': None, 'min_weight_fraction_leaf': 0.27111099648458864, 'warm_start': False}. Best is trial 12 with value: 0.7438602547617209.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7981220657276995
[I 2024-04-18 05:12:33,637] Trial 26 finished with value: 0.7952997362091728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 17, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.425133711322363, 'max_features': None, 'min_weight_fraction_leaf': 0.07929595127017089, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.759493670886076
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 05:12:39,934] Trial 27 finished with value: 0.7439785302441695 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.5634050049825258, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07348058796691775, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 05:12:44,370] Trial 28 finished with value: 0.7606780234987396 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.5671295227568508, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002810616935067567, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.7981220657276995
[I 2024-04-18 05:12:49,041] Trial 29 finished with value: 0.7861497989039858 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06647154253337151, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7981220657276995
[I 2024-04-18 05:12:53,859] Trial 30 finished with value: 0.7826158421682422 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.670660906330469, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008496584402552174, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8571428571428571

Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 05:12:58,350] Trial 31 finished with value: 0.7936613975238874 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.7258118850709611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020186907613437947, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.8169014084507042
[I 2024-04-18 05:13:01,681] Trial 32 finished with value: 0.7892741864327053 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 149, 'oob_score': True, 'max_samples': 0.7060378252364139, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04618667534698639, 'warm_start': True}. Best is trial 26 with value: 0.7952997362091728.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 05:13:05,188] Trial 33 finished with value: 0.8006493236932368 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 155, 'oob_score': True, 'max_samples': 0.7605972338377621, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046274896708941554, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 05:13:08,616] Trial 34 finished with value: 0.7998566890977854 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.7633408434752601, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04380970481841874, 'warm_start': True}. Best is trial 33 with value: 0.8006493236932368.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.8356807511737089
[I 2024-04-18 05:13:10,671] Trial 35 finished with value: 0.803331848306836 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.7948212261000067, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10423395463781872, 'warm_start': True}. Best is trial 35 with value: 0.803331848306836.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 05:13:12,173] Trial 36 finished with value: 0.81388019672447 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8091332552149437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10837446978579603, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 05:13:13,829] Trial 37 finished with value: 0.8138484554748331 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 101, 'oob_score': False, 'max_samples': 0.8220720793755758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09608472875949194, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.8075117370892019
[I 2024-04-18 05:13:15,323] Trial 38 finished with value: 0.794834129497761 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.8537902740382926, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09525205057743304, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.863849765258216
[I 2024-04-18 05:13:16,799] Trial 39 finished with value: 0.8134528027162501 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9833072699349469, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10393928454601242, 'warm_start': True}. Best is trial 36 with value: 0.81388019672447.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 05:13:18,331] Trial 40 finished with value: 0.8193359257510359 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 79, 'oob_score': False, 'max_samples': 0.9974049101283982, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11156682941225779, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 05:13:19,846] Trial 41 finished with value: 0.8034774490599819 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.9999220055692117, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12045420312726329, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 05:13:21,291] Trial 42 finished with value: 0.809391720026152 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.9881165529835445, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12443985149382927, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.8685446009389671
[I 2024-04-18 05:13:22,465] Trial 43 finished with value: 0.8118099200814217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.9912995656748597, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12253835631192889, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.5757575757575758
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7535211267605634
[I 2024-04-18 05:13:23,268] Trial 44 finished with value: 0.7512725179741098 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.9192360586272437, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09432875921172784, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.8169014084507042
[I 2024-04-18 05:13:24,236] Trial 45 finished with value: 0.7805310602984772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 35, 'oob_score': False, 'max_samples': 0.8671059553512112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22329822046282632, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.

Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 05:13:26,135] Trial 46 finished with value: 0.7374183107739604 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 123, 'oob_score': False, 'max_samples': 0.9536184653009308, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1531269560181571, 'warm_start': True}. Best is trial 40 with value: 0.8193359257510359.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 05:13:27,353] Trial 47 finished with value: 0.821440909099989 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.8733003039936599, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12467981297687225, 'warm_start': True}. Best is trial 47 with value: 0.821440909099989.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 05:13:29,221] Trial 48 finished with value: 0.8304915258944628 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.8813820217761629, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06296378903734845, 'warm_start': True}. Best is trial 48 with value: 0.8304915258944628.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:13:31,267] Trial 49 finished with value: 0.8329500051937337 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 106, 'oob_score': False, 'max_samples': 0.8805367238926652, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.057195379787481515, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:13:33,372] Trial 50 finished with value: 0.8314528643350888 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.9009010945275224, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.054961351160765004, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:13:36,455] Trial 51 finished with value: 0.8313163540347663 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 183, 'oob_score': False, 'max_samples': 0.8934638023278324, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03450702765653768, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 05:13:39,472] Trial 52 finished with value: 0.8320214536162119 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.8797580746407682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.024666679991640003, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 05:13:41,823] Trial 53 finished with value: 0.829623312030853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 118, 'oob_score': False, 'max_samples': 0.8886913182351664, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038639798107064416, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 05:13:44,960] Trial 54 finished with value: 0.8269793471449424 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 178, 'oob_score': False, 'max_samples': 0.8943965597615428, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02658068365989562, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 05:13:47,419] Trial 55 finished with value: 0.8314821925869167 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.9394960211783968, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03414063784444427, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 05:13:51,462] Trial 56 finished with value: 0.8291458931503687 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.9464163990983746, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05957529961744705, 'warm_start': True}. Best is trial 49 with value: 0.8329500051937337.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8967136150234741
[I 2024-04-18 05:13:54,888] Trial 57 finished with value: 0.837497279418745 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8375194335284916, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028965413024752612, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8732394366197183
[I 2024-04-18 05:13:58,134] Trial 58 finished with value: 0.8257460337171384 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.8473410457317984, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023049662318096596, 'warm_start': True}. Best is trial 57 with value: 0.837497279418745.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:14:01,961] Trial 59 finished with value: 0.8490112951451346 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9190157687794943, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013504221373780535, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:14:06,861] Trial 60 finished with value: 0.8462284069610924 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9302291542086784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020986391606638635, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.

Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 05:14:11,461] Trial 61 finished with value: 0.8471575518568665 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9319335934099356, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0028492650677599558, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 05:14:16,653] Trial 62 finished with value: 0.8424040571187227 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.9488273152669577, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006993125885435061, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 05:14:22,453] Trial 63 finished with value: 0.8459918151364014 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.9558680489418835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00656722209863304, 'warm_start': True}. Best is trial 59 with value: 0.8490112951451346.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 05:14:28,903] Trial 64 finished with value: 0.8560377835959099 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 283, 'oob_score': False, 'max_samples': 0.9511852166403515, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006787286025552868, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 05:14:35,025] Trial 65 finished with value: 0.8543281008735688 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.959702372838177, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0021045537516321865, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9436619718309859
[I 2024-04-18 05:14:41,464] Trial 66 finished with value: 0.846986714506221 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9606657832305625, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009645713200115154, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:14:47,926] Trial 67 finished with value: 0.8422965637980504 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 282, 'oob_score': False, 'max_samples': 0.9696946680213249, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015463863160716843, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 05:14:56,098] Trial 68 finished with value: 0.8400810425063071 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.9226346461200242, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.013757163062800108, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.6995305164319249
[I 2024-04-18 05:14:59,320] Trial 69 finished with value: 0.735120849138696 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9207461742012929, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3619470610261025, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 05:15:02,486] Trial 70 finished with value: 0.7199549229649882 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.9621462391123464, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4708820505432424, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 05:15:07,583] Trial 71 finished with value: 0.8477117723943335 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.95365805085536, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.006547106868712814, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 05:15:14,526] Trial 72 finished with value: 0.8468137779836808 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.9218265096398339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.002129212342459046, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6017316017316018
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9014084507042254
[I 2024-04-18 05:15:20,751] Trial 73 finished with value: 0.8355677775332243 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.7855691032277902, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.015061828643737101, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-18 05:15:25,125] Trial 74 finished with value: 0.8441728577198884 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9254876714681857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0812631651455817, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:15:32,077] Trial 75 finished with value: 0.8362371866524855 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.9681737785400921, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0015964899054660966, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 05:15:38,237] Trial 76 finished with value: 0.84313576068201 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.8305113746650353, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0426275461746545, 'warm_start': True}. Best is trial 64 with value: 0.8560377835959099.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.8973214285714286
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 05:15:43,047] Trial 77 finished with value: 0.8568403814547748 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.9144336511700586, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01595057842588041, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9061032863849765
[I 2024-04-18 05:15:47,509] Trial 78 finished with value: 0.8419192289956712 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9116776901842412, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07343560570014901, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:15:52,431] Trial 79 finished with value: 0.8328178212078037 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.8605744759700164, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023396832105227285, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 05:15:56,713] Trial 80 finished with value: 0.7687749931412297 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.969349688986363, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2986900237576432, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 05:16:02,573] Trial 81 finished with value: 0.8508482566919376 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9412070505938585, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01576257355000931, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 05:16:08,816] Trial 82 finished with value: 0.8416282042647364 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.9068065686971891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.016797956013047826, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8732394366197183
[I 2024-04-18 05:16:14,077] Trial 83 finished with value: 0.8318825303180803 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.6153744430709406, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04832190639289941, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 05:16:19,801] Trial 84 finished with value: 0.8433724935297382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.9399975078027157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0345364942691951, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-18 05:16:24,800] Trial 85 finished with value: 0.8358557576420413 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.9737845589861637, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01634294636489071, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-18 05:16:31,095] Trial 86 finished with value: 0.8377019506647049 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 315, 'oob_score': False, 'max_samples': 0.8518058828861286, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05107482426381401, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 05:16:54,516] Trial 87 finished with value: 0.7178329643580474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.9965938454935799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.034448975293513207, 'warm_start': False}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 05:17:00,867] Trial 88 finished with value: 0.8457089722953801 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 335, 'oob_score': False, 'max_samples': 0.9085692767397662, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0697346803584661, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 05:17:09,655] Trial 89 finished with value: 0.836101128647378 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 375, 'oob_score': False, 'max_samples': 0.7981108690303841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.012687139847991694, 'warm_start': True}. Best is trial 77 with value: 0.8568403814547748.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 05:17:15,059] Trial 90 finished with value: 0.858196741029675 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9399104719362167, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04454154696608814, 'warm_start': True}. Best is trial 90 with value: 0.858196741029675.

Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 05:17:20,244] Trial 91 finished with value: 0.8594063157686616 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.9393175331158453, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0004448382541777079, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.9017857142857143
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 05:17:25,092] Trial 92 finished with value: 0.8504093975391417 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'max_samples': 0.9511651006370562, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.023794967159176263, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.5887445887445888
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 05:17:29,845] Trial 93 finished with value: 0.8507722251285642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.9393138993988948, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04166845875792434, 'warm_start': True}. Best is trial 91 with value: 0.8594063157686616.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9342723004694836
[I 2024-04-18 05:17:34,935] Trial 94 finished with value: 0.864047670519609 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.9107981220657277
[I 2024-04-18 05:17:39,428] Trial 95 finished with value: 0.8462994805857642 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 226, 'oob_score': False, 'max_samples': 0.9851260930666599, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0877741788827067, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 05:17:43,335] Trial 96 finished with value: 0.8456767787505284 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 203, 'oob_score': False, 'max_samples': 0.9046678790431277, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05908913791760474, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.8169014084507042
[I 2024-04-18 05:17:46,339] Trial 97 finished with value: 0.7824887018130806 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.9994611759628653, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04096131539525037, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.7053571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 05:18:05,395] Trial 98 finished with value: 0.7022847020297285 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.9435261125804136, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025743264975163525, 'warm_start': False}. Best is trial 94 with value: 0.864047670519609.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8627450980392157

[I 2024-04-18 05:18:08,767] A new study created in memory with name: no-name-b6d3689b-2c51-44ff-aeb5-20d3349e083b

Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9061032863849765
[I 2024-04-18 05:18:08,740] Trial 99 finished with value: 0.8374434398307532 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.8689674666549045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04663818112580286, 'warm_start': True}. Best is trial 94 with value: 0.864047670519609.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.864047670519609], datetime_start=datetime.datetime(2024, 4, 18, 5, 17, 29, 856737), datetime_complete=datetime.datetime(2024, 4, 18, 5, 17, 34, 934911), params={'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'max_samples': 0.9847467855272036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04749646122417352, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=94, value=None)


* Best Score for C-index:
 0.864047670519609

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18324615167630967
Fold 2 IBS: 0.1973414798718171
Fold 3 IBS: 0.16795049053724004
Fold 4 IBS: 0.18912813741469703
Fold 5 IBS: 0.2061164871654968
[I 2024-04-18 05:19:29,931] Trial 0 finished with value: 0.18875654933311214 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20345329363741022
Fold 2 IBS: 0.1866704968763983
Fold 3 IBS: 0.18211060269283327
Fold 4 IBS: 0.18446935355917493
Fold 5 IBS: 0.20613420199922336
[I 2024-04-18 05:19:33,810] Trial 1 finished with value: 0.19256758975300803 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-18 05:19:36,066] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-18 05:19:44,991] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-18 05:19:51,506] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20630791540283333
Fold 2 IBS: 0.18077183063689325
Fold 3 IBS: 0.18637698687972554
Fold 4 IBS: 0.15939882886870535
Fold 5 IBS: 0.2113504541273204
[I 2024-04-18 05:20:07,965] Trial 5 finished with value: 0.18884120318309558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.18286701090322455
Fold 2 IBS: 0.18771259904008297
Fold 3 IBS: 0.1679729459105892
Fold 4 IBS: 0.19488974663997188
Fold 5 IBS: 0.2131586526955741
[I 2024-04-18 05:20:53,479] Trial 6 finished with value: 0.18932019103788852 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20907943912609248
Fold 2 IBS: 0.2142874391649597
Fold 3 IBS: 0.20035786531447508
Fold 4 IBS: 0.22002960031246824
Fold 5 IBS: 0.21626779318082703
[I 2024-04-18 05:21:04,404] Trial 7 finished with value: 0.2120044274197645 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-18 05:21:21,310] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20357073593273053
Fold 2 IBS: 0.18780891594621849
Fold 3 IBS: 0.18460304549691883
Fold 4 IBS: 0.1856640301109529
Fold 5 IBS: 0.20794919209811308
[I 2024-04-18 05:21:25,814] Trial 9 finished with value: 0.19391918391698676 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-18 05:21:45,435] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20470418186342312
Fold 2 IBS: 0.20409550521820866
Fold 3 IBS: 0.19035125570755929
Fold 4 IBS: 0.20279707515139048
Fold 5 IBS: 0.2139020077116487
[I 2024-04-18 05:21:58,889] Trial 11 finished with value: 0.203170005130446 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.751058151425702, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 0 with value: 0.18875654933311214.
Fold 1 IBS: 0.20586437433035337
Fold 2 IBS: 0.18045352650478874
Fold 3 IBS: 0.18471158232105125
Fold 4 IBS: 0.1564532839984733
Fold 5 IBS: 0.21278485149213985
[I 2024-04-18 05:22:21,095] Trial 12 finished with value: 0.1880535237293613 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9944667777599061, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10294337889507951}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.21738156589672325
Fold 2 IBS: 0.18148498524761636
Fold 3 IBS: 0.20328771782225072
Fold 4 IBS: 0.16200397997147525
Fold 5 IBS: 0.20246860054845137
[I 2024-04-18 05:25:47,509] Trial 13 finished with value: 0.1933253698973034 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.9694270540157217, 'max_features': None, 'min_weight_fraction_leaf': 0.1530029930440125}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19707033841317873
Fold 2 IBS: 0.1876771636325187
Fold 3 IBS: 0.1818736950861829
Fold 4 IBS: 0.179566358950222
Fold 5 IBS: 0.2109513215570391
[I 2024-04-18 05:26:04,327] Trial 14 finished with value: 0.19142777552782828 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.7631177214580046, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21229864789095249}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.22655147877004286
Fold 2 IBS: 0.18326284905513224
Fold 3 IBS: 0.2097169134350128
Fold 4 IBS: 0.16586651259722404
Fold 5 IBS: 0.20952385709991683
[I 2024-04-18 05:27:49,149] Trial 15 finished with value: 0.19898432219146575 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'max_samples': 0.9970673523205843, 'max_features': None, 'min_weight_fraction_leaf': 0.09604984749674861}. Best is trial 12 with value: 0.1880535237293613.

Fold 1 IBS: 0.20378808796262518
Fold 2 IBS: 0.19365995427708668
Fold 3 IBS: 0.1882413702928391
Fold 4 IBS: 0.19759396434280763
Fold 5 IBS: 0.21553362503994042
[I 2024-04-18 05:28:03,748] Trial 16 finished with value: 0.19976340038305979 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.8184724465806228, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.31376919111755797}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20035161627096812
Fold 2 IBS: 0.18410251599192942
Fold 3 IBS: 0.18211883476245105
Fold 4 IBS: 0.18801743258981968
Fold 5 IBS: 0.21327804714656015
[I 2024-04-18 05:28:13,978] Trial 17 finished with value: 0.19357368935234567 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.3060837787360696, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005619770510688432}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19808389265211931
Fold 2 IBS: 0.18205953021252363
Fold 3 IBS: 0.185875813422921
Fold 4 IBS: 0.17434571756518558
Fold 5 IBS: 0.212414509617453
[I 2024-04-18 05:28:33,182] Trial 18 finished with value: 0.19055589269404052 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.680642613858846, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12812974712655775}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.19002039864329462
Fold 2 IBS: 0.18942385941547232
Fold 3 IBS: 0.18799087691719493
Fold 4 IBS: 0.18284504372921612
Fold 5 IBS: 0.20840823704233402
[I 2024-04-18 05:29:19,158] Trial 19 finished with value: 0.1917376831495024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.8923233540949727, 'max_features': None, 'min_weight_fraction_leaf': 0.22336599579981053}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20241484728756806
Fold 2 IBS: 0.19065053491089928
Fold 3 IBS: 0.18779471719312824
Fold 4 IBS: 0.19480082717000774
Fold 5 IBS: 0.21868104809372813
[I 2024-04-18 05:29:28,162] Trial 20 finished with value: 0.19886839493106628 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.7871968885021372, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34030385853489}. Best is trial 12 with value: 0.1880535237293613.
Fold 1 IBS: 0.20741632570728089
Fold 2 IBS: 0.1780845098687536
Fold 3 IBS: 0.1846122378972077
Fold 4 IBS: 0.1564868201189816
Fold 5 IBS: 0.21131308248390057
[I 2024-04-18 05:29:45,028] Trial 21 finished with value: 0.18758259521522488 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.6541307441098512, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06381773403573333}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21885274316469258
Fold 2 IBS: 0.17828077601342465
Fold 3 IBS: 0.1880861120963736
Fold 4 IBS: 0.15017691808187725
Fold 5 IBS: 0.208661756520607
[I 2024-04-18 05:30:06,065] Trial 22 finished with value: 0.18881166117539502 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6139693116960656, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04453049413403026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19871040202258342
Fold 2 IBS: 0.184765649243245
Fold 3 IBS: 0.18498703463344066
Fold 4 IBS: 0.18599311903171908
Fold 5 IBS: 0.21143993706602787
[I 2024-04-18 05:30:15,166] Trial 23 finished with value: 0.1931792283994032 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 247, 'oob_score': False, 'max_samples': 0.4478983539583735, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20038924075539685
Fold 2 IBS: 0.18852724912576502
Fold 3 IBS: 0.1847265574388743
Fold 4 IBS: 0.19388302387911258
Fold 5 IBS: 0.21617210096544462
[I 2024-04-18 05:30:28,187] Trial 24 finished with value: 0.1967396344329187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.4295396819868078, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16813485936717243}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.23819448878865138
Fold 2 IBS: 0.18859860435971892
Fold 3 IBS: 0.19682793240255014
Fold 4 IBS: 0.15957526364066002
Fold 5 IBS: 0.20198931781322124
[I 2024-04-18 05:34:37,520] Trial 25 finished with value: 0.19703712140096036 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.7297972378004723, 'max_features': None, 'min_weight_fraction_leaf': 0.04981104107775003}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.2010034177138824
Fold 2 IBS: 0.182735296255063
Fold 3 IBS: 0.18466236755017185
Fold 4 IBS: 0.17246211363358033
Fold 5 IBS: 0.21643410204328975
[I 2024-04-18 05:34:49,378] Trial 26 finished with value: 0.19145945943919745 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.8472363371748154, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10973545356505882}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.1964328885601889
Fold 2 IBS: 0.18809613601862848
Fold 3 IBS: 0.1818420692920181
Fold 4 IBS: 0.17399619732336324
Fold 5 IBS: 0.2111836724460323
[I 2024-04-18 05:35:07,527] Trial 27 finished with value: 0.19031019272804622 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9331113837900542, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2386001330983712}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19854249756198333
Fold 2 IBS: 0.18810793646188287
Fold 3 IBS: 0.18308123282699756
Fold 4 IBS: 0.18681900970293147
Fold 5 IBS: 0.21245937503700765
[I 2024-04-18 05:35:19,163] Trial 28 finished with value: 0.19380201031816058 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.5883566242401418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1845919041664691}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19840416643063166
Fold 2 IBS: 0.18537155668553762
Fold 3 IBS: 0.18344052151498125
Fold 4 IBS: 0.17492059658908363
Fold 5 IBS: 0.21086762605161444
[I 2024-04-18 05:35:34,363] Trial 29 finished with value: 0.19060089345436973 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.6774353138386819, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.22252593046960736
Fold 2 IBS: 0.1888838348535354
Fold 3 IBS: 0.19671883214571217
Fold 4 IBS: 0.162697984958246
Fold 5 IBS: 0.1971675681434196
[I 2024-04-18 05:36:28,289] Trial 30 finished with value: 0.19359883011410411 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': None, 'min_weight_fraction_leaf': 0.04202783134992163}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.218645817549917
Fold 2 IBS: 0.17984916123604971
Fold 3 IBS: 0.18930240115766292
Fold 4 IBS: 0.1502748627436339
Fold 5 IBS: 0.20680109594224744
[I 2024-04-18 05:36:49,063] Trial 31 finished with value: 0.18897466772590218 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.6145656696996076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.028279638075097074}. Best is trial 21 with value: 0.18758259521522488.

Fold 1 IBS: 0.20444739845582136
Fold 2 IBS: 0.17446698341767913
Fold 3 IBS: 0.1910994493903993
Fold 4 IBS: 0.1668825886510828
Fold 5 IBS: 0.21103427734544067
[I 2024-04-18 05:37:03,065] Trial 32 finished with value: 0.18958613945208463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.6325115094238634, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0760629688237641}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21394095082970305
Fold 2 IBS: 0.18957239420831615
Fold 3 IBS: 0.18237897227425182
Fold 4 IBS: 0.17846689832832333
Fold 5 IBS: 0.2185435449686763
[I 2024-04-18 05:37:04,707] Trial 33 finished with value: 0.19658055212185413 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 19, 'oob_score': False, 'max_samples': 0.7088178154422675, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12510702348081404}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.21814598296546053
Fold 2 IBS: 0.1806418667764422
Fold 3 IBS: 0.185193327742374
Fold 4 IBS: 0.14930927407248543
Fold 5 IBS: 0.20730315585697304
[I 2024-04-18 05:37:26,439] Trial 34 finished with value: 0.18811872148274703 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.5179281521096981, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03287535020826214}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20068393107082932
Fold 2 IBS: 0.18004564547293722
Fold 3 IBS: 0.1813279250878163
Fold 4 IBS: 0.16606271502196493
Fold 5 IBS: 0.2133678565084531
[I 2024-04-18 05:37:39,502] Trial 35 finished with value: 0.1882976146324002 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 263, 'oob_score': True, 'max_samples': 0.5205069556471076, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08931012896561974}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.19921865381139617
Fold 2 IBS: 0.1879147544934006
Fold 3 IBS: 0.18415951307165418
Fold 4 IBS: 0.17928295771289782
Fold 5 IBS: 0.21187622162524927
[I 2024-04-18 05:37:48,607] Trial 36 finished with value: 0.19249042014291962 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.34556748843479757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08517804478502394}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20689459020742101
Fold 2 IBS: 0.18578195800005948
Fold 3 IBS: 0.18062395532410724
Fold 4 IBS: 0.16979980454141178
Fold 5 IBS: 0.20913380244139584
[I 2024-04-18 05:38:00,075] Trial 37 finished with value: 0.19044682210287905 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 257, 'oob_score': True, 'max_samples': 0.19350535662381702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02562193860216446}. Best is trial 21 with value: 0.18758259521522488.
Fold 1 IBS: 0.20164172687027268
Fold 2 IBS: 0.179042406474406
Fold 3 IBS: 0.18484112426907948
Fold 4 IBS: 0.15977140249838878
Fold 5 IBS: 0.2120612409546842
[I 2024-04-18 05:38:16,453] Trial 38 finished with value: 0.18747158021336624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.5607171176186949, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06539515726225846}. Best is trial 38 with value: 0.18747158021336624.
Fold 1 IBS: 0.20421151305171514
Fold 2 IBS: 0.17932735612158596
Fold 3 IBS: 0.17928162605465459
Fold 4 IBS: 0.16526541395746405
Fold 5 IBS: 0.2090081959308534
[I 2024-04-18 05:38:32,794] Trial 39 finished with value: 0.18741882102325463 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.3617667691015132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.052772428028015156}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2022159312451902
Fold 2 IBS: 0.1848488680529207
Fold 3 IBS: 0.17740255174053524
Fold 4 IBS: 0.1726825614136245
Fold 5 IBS: 0.213121743730351
[I 2024-04-18 05:38:45,846] Trial 40 finished with value: 0.19005433123652432 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.3736866960473132, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05524155311927098}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.22304701735374977
Fold 2 IBS: 0.19262749474927982
Fold 3 IBS: 0.18617094771467074
Fold 4 IBS: 0.16090440652263122
Fold 5 IBS: 0.2060830161959264
[I 2024-04-18 05:39:02,099] Trial 41 finished with value: 0.1937665765072516 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.26471791598500466, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008610506287772067}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.19780135900892157
Fold 2 IBS: 0.1857789376740191
Fold 3 IBS: 0.1799971131723769
Fold 4 IBS: 0.1804099527573313
Fold 5 IBS: 0.21177881228015194
[I 2024-04-18 05:39:19,169] Trial 42 finished with value: 0.19115323497856015 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.5034748057992058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13666482964507704}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21400092589198996
Fold 2 IBS: 0.2214210103976947
Fold 3 IBS: 0.2048692155883072
Fold 4 IBS: 0.22463234501283708
Fold 5 IBS: 0.2185873987821863
[I 2024-04-18 05:39:28,365] Trial 43 finished with value: 0.21670217913460305 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.4788775563231737, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20231241634002334
Fold 2 IBS: 0.18036495206092895
Fold 3 IBS: 0.1818599860701185
Fold 4 IBS: 0.16340196628946066
Fold 5 IBS: 0.21378560467248073
[I 2024-04-18 05:39:44,806] Trial 44 finished with value: 0.18834498508660244 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.5506248755449263, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0721857441783233}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1973845412708107
Fold 2 IBS: 0.18124870301190693
Fold 3 IBS: 0.1810814354603528
Fold 4 IBS: 0.1707551433320944
Fold 5 IBS: 0.2119250973889522
[I 2024-04-18 05:40:02,983] Trial 45 finished with value: 0.18847898409282343 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.5775224127982328, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10537693884726008}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21070983930823925
Fold 2 IBS: 0.18608759362092114
Fold 3 IBS: 0.18204123382213788
Fold 4 IBS: 0.16642669368966861
Fold 5 IBS: 0.21219350314332874
[I 2024-04-18 05:40:22,885] Trial 46 finished with value: 0.19149177271685913 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.26128950045955984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02835891103553452}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20296038593675553
Fold 2 IBS: 0.1835795355330322
Fold 3 IBS: 0.18270515601508316
Fold 4 IBS: 0.17696688246148076
Fold 5 IBS: 0.2124434684430158
[I 2024-04-18 05:40:34,857] Trial 47 finished with value: 0.19173108567787348 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.39724110016399944, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06776177948204519}. Best is trial 39 with value: 0.18741882102325463.

Fold 1 IBS: 0.21397545241919333
Fold 2 IBS: 0.22060585341756236
Fold 3 IBS: 0.20519466411613427
Fold 4 IBS: 0.2248054198587066
Fold 5 IBS: 0.21758241895615993
[I 2024-04-18 05:40:46,939] Trial 48 finished with value: 0.2164327617535513 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.1840472657347053, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20733215663048163
Fold 2 IBS: 0.19840873877308707
Fold 3 IBS: 0.1896647344947966
Fold 4 IBS: 0.2057146078926162
Fold 5 IBS: 0.2152447795126918
[I 2024-04-18 05:40:54,545] Trial 49 finished with value: 0.20327300346073468 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.4611544071310423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02536063881705921}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.204879944056226
Fold 2 IBS: 0.18198982906903266
Fold 3 IBS: 0.1813060638484819
Fold 4 IBS: 0.16283844353857155
Fold 5 IBS: 0.21363299219754156
[I 2024-04-18 05:41:08,952] Trial 50 finished with value: 0.18892945454197077 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.5416005248904892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0034087820600749476}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2004109367454522
Fold 2 IBS: 0.18404020643987526
Fold 3 IBS: 0.18234193379348762
Fold 4 IBS: 0.17143012200567861
Fold 5 IBS: 0.21239169444633466
[I 2024-04-18 05:41:20,899] Trial 51 finished with value: 0.19012297868616568 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.5290774243115414, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09439815236719598}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20363791714493526
Fold 2 IBS: 0.18084498958548437
Fold 3 IBS: 0.1865787886727044
Fold 4 IBS: 0.15958133230330762
Fold 5 IBS: 0.21346890098280094
[I 2024-04-18 05:41:37,055] Trial 52 finished with value: 0.18882238573784652 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.646747773042784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08961848913350215}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20381819322938977
Fold 2 IBS: 0.18114674744033232
Fold 3 IBS: 0.18113417018982886
Fold 4 IBS: 0.1618949090102553
Fold 5 IBS: 0.21456765862332783
[I 2024-04-18 05:41:57,157] Trial 53 finished with value: 0.18851233569862683 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.5080082016246513, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06630490839370301}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2042758448261322
Fold 2 IBS: 0.18877763887578689
Fold 3 IBS: 0.18209755324442445
Fold 4 IBS: 0.19391559310720333
Fold 5 IBS: 0.2159060762300408
[I 2024-04-18 05:42:10,372] Trial 54 finished with value: 0.1969945412567175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.38392655290485045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1447625548982195}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2034151090750003
Fold 2 IBS: 0.18176049250213502
Fold 3 IBS: 0.1857336365331899
Fold 4 IBS: 0.1788179124206326
Fold 5 IBS: 0.2129610073834551
[I 2024-04-18 05:42:23,165] Trial 55 finished with value: 0.1925376315828826 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 286, 'oob_score': True, 'max_samples': 0.5872802927086659, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046825551317268566}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20422176706868694
Fold 2 IBS: 0.1924062351097664
Fold 3 IBS: 0.18544969707631245
Fold 4 IBS: 0.1984840238620755
Fold 5 IBS: 0.21497590518150314
[I 2024-04-18 05:42:33,768] Trial 56 finished with value: 0.19910752565966888 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.4154965081431159, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18037694403417448}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.2059789858573675
Fold 2 IBS: 0.1967683996639164
Fold 3 IBS: 0.18831908034352698
Fold 4 IBS: 0.20147608897626476
Fold 5 IBS: 0.21654528774605497
[I 2024-04-18 05:42:42,535] Trial 57 finished with value: 0.20181756851742616 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7776350329623957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3781865060679536}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.20703604925067237
Fold 2 IBS: 0.18243435974189295
Fold 3 IBS: 0.18268181766890698
Fold 4 IBS: 0.20149520002925903
Fold 5 IBS: 0.21479477144824155
[I 2024-04-18 05:42:46,628] Trial 58 finished with value: 0.1976884396277946 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.32208030951555616, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11116699744055775}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.21121978023043514
Fold 2 IBS: 0.17834386764399476
Fold 3 IBS: 0.18431619963737042
Fold 4 IBS: 0.15794559160168345
Fold 5 IBS: 0.211915583151784
[I 2024-04-18 05:43:09,062] Trial 59 finished with value: 0.18874820445305357 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.706317491452594, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06164379588338738}. Best is trial 39 with value: 0.18741882102325463.
Fold 1 IBS: 0.1966264720209345
Fold 2 IBS: 0.18597478555674649
Fold 3 IBS: 0.1786448987547083
Fold 4 IBS: 0.16171860015636114
Fold 5 IBS: 0.20668689381001223
[I 2024-04-18 05:44:33,590] Trial 60 finished with value: 0.18593033005975254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.4446079220615766, 'max_features': None, 'min_weight_fraction_leaf': 0.09271318262887082}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2024856806183152
Fold 2 IBS: 0.18195716111018798
Fold 3 IBS: 0.18480931433897935
Fold 4 IBS: 0.16237325049629045
Fold 5 IBS: 0.20714210552628523
[I 2024-04-18 05:45:58,136] Trial 61 finished with value: 0.18775350241801164 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 306, 'oob_score': True, 'max_samples': 0.44685465277095665, 'max_features': None, 'min_weight_fraction_leaf': 0.08682673693183435}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2284531812120082
Fold 2 IBS: 0.1948622570457934
Fold 3 IBS: 0.18812485157230974
Fold 4 IBS: 0.16088214458625358
Fold 5 IBS: 0.20190289439703843
[I 2024-04-18 05:48:21,300] Trial 62 finished with value: 0.19484506576268068 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.4515303316200064, 'max_features': None, 'min_weight_fraction_leaf': 0.037039554766136004}. Best is trial 60 with value: 0.18593033005975254.
Fold 1 IBS: 0.2252402779389061
Fold 2 IBS: 0.1862300882985594
Fold 3 IBS: 0.18602106947089103
Fold 4 IBS: 0.17312433407761857
Fold 5 IBS: 0.1889042172268272
[I 2024-04-18 05:50:36,024] Trial 63 finished with value: 0.19190399740256042 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.41265009702186795, 'max_features': None, 'min_weight_fraction_leaf': 0.016364606682246152}. Best is trial 60 with value: 0.18593033005975254.

Fold 1 IBS: 0.18697650055709675
Fold 2 IBS: 0.18964751614322145
Fold 3 IBS: 0.17157067951262514
Fold 4 IBS: 0.17048079186700552
Fold 5 IBS: 0.20812563312237994
[I 2024-04-18 05:51:31,738] Trial 64 finished with value: 0.18536022424046578 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 381, 'oob_score': True, 'max_samples': 0.36087148528744895, 'max_features': None, 'min_weight_fraction_leaf': 0.10501492814170305}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.185980269157479
Fold 2 IBS: 0.18929665176523391
Fold 3 IBS: 0.17261558628019577
Fold 4 IBS: 0.17528863593015434
Fold 5 IBS: 0.20987976574068176
[I 2024-04-18 05:52:20,295] Trial 65 finished with value: 0.18661218177474898 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.35503340896452096, 'max_features': None, 'min_weight_fraction_leaf': 0.10944245403951429}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18694115431926822
Fold 2 IBS: 0.1908501583998164
Fold 3 IBS: 0.17205632092618067
Fold 4 IBS: 0.18203552427470343
Fold 5 IBS: 0.21326387492637428
[I 2024-04-18 05:53:06,495] Trial 66 finished with value: 0.1890294065692686 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.3614405881665075, 'max_features': None, 'min_weight_fraction_leaf': 0.12510407630083206}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397879618526044
Fold 2 IBS: 0.22095626300254492
Fold 3 IBS: 0.2049272671362546
Fold 4 IBS: 0.2246487203312697
Fold 5 IBS: 0.21797754042983516
[I 2024-04-18 05:53:20,623] Trial 67 finished with value: 0.21649771741703297 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 388, 'oob_score': True, 'max_samples': 0.277566908191509, 'max_features': None, 'min_weight_fraction_leaf': 0.16326642133899677}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18701806869001636
Fold 2 IBS: 0.19002615779169066
Fold 3 IBS: 0.17109529332077666
Fold 4 IBS: 0.17558286313646593
Fold 5 IBS: 0.20866467885193285
[I 2024-04-18 05:54:08,956] Trial 68 finished with value: 0.1864774123581765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.3339648956191334, 'max_features': None, 'min_weight_fraction_leaf': 0.10534737249789848}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.213990042339758
Fold 2 IBS: 0.22081844148187832
Fold 3 IBS: 0.2049164994171005
Fold 4 IBS: 0.22451019970461408
Fold 5 IBS: 0.2178161153197119
[I 2024-04-18 05:54:21,666] Trial 69 finished with value: 0.21641025965261257 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.22058879264036, 'max_features': None, 'min_weight_fraction_leaf': 0.14500630501117967}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397438613021721
Fold 2 IBS: 0.22116611565870514
Fold 3 IBS: 0.20499774371165358
Fold 4 IBS: 0.22471498188046043
Fold 5 IBS: 0.21823664145637212
[I 2024-04-18 05:54:32,795] Trial 70 finished with value: 0.21661797376748168 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.34596416260173934, 'max_features': None, 'min_weight_fraction_leaf': 0.2703111919415455}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18924036720156343
Fold 2 IBS: 0.18779280930051329
Fold 3 IBS: 0.17209448151288856
Fold 4 IBS: 0.17958207486087677
Fold 5 IBS: 0.211566257073253
[I 2024-04-18 05:55:14,410] Trial 71 finished with value: 0.18805519798981898 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.31453931029426085, 'max_features': None, 'min_weight_fraction_leaf': 0.1045230982104525}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19657952397027323
Fold 2 IBS: 0.19022838128535594
Fold 3 IBS: 0.1708771341601037
Fold 4 IBS: 0.17168544722624235
Fold 5 IBS: 0.20713375074665116
[I 2024-04-18 05:55:59,691] Trial 72 finished with value: 0.1873008474777253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.2926475761323768, 'max_features': None, 'min_weight_fraction_leaf': 0.07798192572483449}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.19885306195698255
Fold 2 IBS: 0.18210548225096054
Fold 3 IBS: 0.17731375226506932
Fold 4 IBS: 0.16883406032672896
Fold 5 IBS: 0.20809348652266163
[I 2024-04-18 05:56:39,904] Trial 73 finished with value: 0.18703996866448058 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.2870778190236743, 'max_features': None, 'min_weight_fraction_leaf': 0.05561809788206867}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.193787788585605
Fold 2 IBS: 0.18733247875335163
Fold 3 IBS: 0.17837994780791747
Fold 4 IBS: 0.1744246643744868
Fold 5 IBS: 0.21343920626735596
[I 2024-04-18 05:57:14,146] Trial 74 finished with value: 0.1894728171577434 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.22588589287949842, 'max_features': None, 'min_weight_fraction_leaf': 0.05443689708608288}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18723429594597044
Fold 2 IBS: 0.18527389087754653
Fold 3 IBS: 0.17197014707614233
Fold 4 IBS: 0.1772724521433817
Fold 5 IBS: 0.21429754155065364
[I 2024-04-18 05:57:47,924] Trial 75 finished with value: 0.1872096655187389 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 404, 'oob_score': False, 'max_samples': 0.2998143519691557, 'max_features': None, 'min_weight_fraction_leaf': 0.1075330144825516}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1941066110336133
Fold 2 IBS: 0.18509351343143435
Fold 3 IBS: 0.17110131699959152
Fold 4 IBS: 0.18270444973194716
Fold 5 IBS: 0.21156937371299012
[I 2024-04-18 05:58:16,226] Trial 76 finished with value: 0.1889150529819153 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.28316698675748087, 'max_features': None, 'min_weight_fraction_leaf': 0.12059869029554741}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21397695237476239
Fold 2 IBS: 0.22118615223089322
Fold 3 IBS: 0.2050313552835387
Fold 4 IBS: 0.2247532956416355
Fold 5 IBS: 0.21820980850510233
[I 2024-04-18 05:58:26,967] Trial 77 finished with value: 0.21663151280718643 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 371, 'oob_score': False, 'max_samples': 0.3371898508848934, 'max_features': None, 'min_weight_fraction_leaf': 0.2048303246846501}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.195733817221237
Fold 2 IBS: 0.18784802284526486
Fold 3 IBS: 0.1763445138354909
Fold 4 IBS: 0.17500708454376265
Fold 5 IBS: 0.20952700605055732
[I 2024-04-18 05:59:16,071] Trial 78 finished with value: 0.18889208889926254 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.29504437594758753, 'max_features': None, 'min_weight_fraction_leaf': 0.07587622273136602}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.21396670472446544
Fold 2 IBS: 0.22085379157505564
Fold 3 IBS: 0.20493941845669997
Fold 4 IBS: 0.22470262306501207
Fold 5 IBS: 0.21714959439503256
[I 2024-04-18 05:59:28,711] Trial 79 finished with value: 0.21632242644325314 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.13307661238331164, 'max_features': None, 'min_weight_fraction_leaf': 0.11597487641803922}. Best is trial 64 with value: 0.18536022424046578.

Fold 1 IBS: 0.2139852535910293
Fold 2 IBS: 0.22079135086710738
Fold 3 IBS: 0.2049571432154721
Fold 4 IBS: 0.22449984942587378
Fold 5 IBS: 0.21784420818016068
[I 2024-04-18 05:59:40,563] Trial 80 finished with value: 0.21641556105592863 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 401, 'oob_score': False, 'max_samples': 0.23317876663764808, 'max_features': None, 'min_weight_fraction_leaf': 0.13195032778351135}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.18698963922132994
Fold 2 IBS: 0.19117908340974094
Fold 3 IBS: 0.1716425830420473
Fold 4 IBS: 0.1706227695034198
Fold 5 IBS: 0.20890166136319582
[I 2024-04-18 06:00:30,437] Trial 81 finished with value: 0.1858671473079468 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.3619448678095568, 'max_features': None, 'min_weight_fraction_leaf': 0.10057070644705586}. Best is trial 64 with value: 0.18536022424046578.
Fold 1 IBS: 0.1890967403784016
Fold 2 IBS: 0.18652324224983566
Fold 3 IBS: 0.17238080905282963
Fold 4 IBS: 0.16710329314707312
Fold 5 IBS: 0.209650785925764
[I 2024-04-18 06:01:20,858] Trial 82 finished with value: 0.18495097415078082 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.3624030825154118, 'max_features': None, 'min_weight_fraction_leaf': 0.09714741335387223}. Best is trial 82 with value: 0.18495097415078082.
Fold 1 IBS: 0.1869379635607008
Fold 2 IBS: 0.1840979377124555
Fold 3 IBS: 0.1723208864840007
Fold 4 IBS: 0.16624305438296152
Fold 5 IBS: 0.20739680918357425
[I 2024-04-18 06:02:20,271] Trial 83 finished with value: 0.18339933026473856 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 368, 'oob_score': False, 'max_samples': 0.39234117831739307, 'max_features': None, 'min_weight_fraction_leaf': 0.09956600887465704}. Best is trial 83 with value: 0.18339933026473856.
Fold 1 IBS: 0.1886542770417182
Fold 2 IBS: 0.18606078762892803
Fold 3 IBS: 0.17038230752313355
Fold 4 IBS: 0.1646204973275064
Fold 5 IBS: 0.20651428479641726
[I 2024-04-18 06:03:17,302] Trial 84 finished with value: 0.1832464308635407 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19155628917728368
Fold 2 IBS: 0.1801885982714529
Fold 3 IBS: 0.17804730003931615
Fold 4 IBS: 0.1693620308491127
Fold 5 IBS: 0.20783919776163526
[I 2024-04-18 06:03:59,950] Trial 85 finished with value: 0.18539868321976014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.3968957116262019, 'max_features': None, 'min_weight_fraction_leaf': 0.095219664847033}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18538493455740376
Fold 2 IBS: 0.18576229943013492
Fold 3 IBS: 0.17402978107752123
Fold 4 IBS: 0.18507755128123915
Fold 5 IBS: 0.21358478244911275
[I 2024-04-18 06:04:29,956] Trial 86 finished with value: 0.18876786975908236 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.38638292055767265, 'max_features': None, 'min_weight_fraction_leaf': 0.17872796639110672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19006306497707842
Fold 2 IBS: 0.1859568983552553
Fold 3 IBS: 0.17526064526770588
Fold 4 IBS: 0.16110281294560094
Fold 5 IBS: 0.20520872126963988
[I 2024-04-18 06:05:28,751] Trial 87 finished with value: 0.18351842856305606 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.4051015506296675, 'max_features': None, 'min_weight_fraction_leaf': 0.09713693453540154}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19767011171898427
Fold 2 IBS: 0.17964734520295073
Fold 3 IBS: 0.1836195742480708
Fold 4 IBS: 0.1667956970154799
Fold 5 IBS: 0.2070890710759274
[I 2024-04-18 06:06:16,151] Trial 88 finished with value: 0.1869643598522826 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.4334251281469186, 'max_features': None, 'min_weight_fraction_leaf': 0.09492515708957672}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18447989656323524
Fold 2 IBS: 0.1882071335854152
Fold 3 IBS: 0.17009416602918556
Fold 4 IBS: 0.18175070837886942
Fold 5 IBS: 0.21200575266539284
[I 2024-04-18 06:06:50,468] Trial 89 finished with value: 0.18730753144441964 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.40662933261411155, 'max_features': None, 'min_weight_fraction_leaf': 0.14538592818664145}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18291200990480525
Fold 2 IBS: 0.18829799983042705
Fold 3 IBS: 0.174582652991839
Fold 4 IBS: 0.1734065332761776
Fold 5 IBS: 0.2073726719246909
[I 2024-04-18 06:07:49,060] Trial 90 finished with value: 0.18531437358558794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.46906936332717275, 'max_features': None, 'min_weight_fraction_leaf': 0.1301923106019002}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18483018153750577
Fold 2 IBS: 0.18822465780769382
Fold 3 IBS: 0.1731074140071581
Fold 4 IBS: 0.17188948389568984
Fold 5 IBS: 0.20714468645851628
[I 2024-04-18 06:08:50,785] Trial 91 finished with value: 0.18503928474131276 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 343, 'oob_score': False, 'max_samples': 0.47678737384020253, 'max_features': None, 'min_weight_fraction_leaf': 0.1325172709355868}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18950832462950518
Fold 2 IBS: 0.18701656820376608
Fold 3 IBS: 0.17893499023469356
Fold 4 IBS: 0.17722915182580176
Fold 5 IBS: 0.20663881973138198
[I 2024-04-18 06:09:40,521] Trial 92 finished with value: 0.18786557092502973 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.49169288583702514, 'max_features': None, 'min_weight_fraction_leaf': 0.13392414841790756}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19861247726074407
Fold 2 IBS: 0.17973057843635412
Fold 3 IBS: 0.185421278409284
Fold 4 IBS: 0.16412850305110133
Fold 5 IBS: 0.20541831001893
[I 2024-04-18 06:11:04,049] Trial 93 finished with value: 0.1866622294352827 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4745011682049886, 'max_features': None, 'min_weight_fraction_leaf': 0.09685737891379577}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19722640593255503
Fold 2 IBS: 0.18658267818572852
Fold 3 IBS: 0.17931575780016162
Fold 4 IBS: 0.15937059058391914
Fold 5 IBS: 0.20605274303785986
[I 2024-04-18 06:12:11,823] Trial 94 finished with value: 0.1857096351080448 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.4244190509544878, 'max_features': None, 'min_weight_fraction_leaf': 0.08390492642221409}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18486260175817798
Fold 2 IBS: 0.18637157071560814
Fold 3 IBS: 0.17201029045136673
Fold 4 IBS: 0.18278192459752535
Fold 5 IBS: 0.21486338860156232
[I 2024-04-18 06:12:46,184] Trial 95 finished with value: 0.1881779552248481 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 382, 'oob_score': False, 'max_samples': 0.3768152460146832, 'max_features': None, 'min_weight_fraction_leaf': 0.16125627455265384}. Best is trial 84 with value: 0.1832464308635407.

Fold 1 IBS: 0.19987889711029083
Fold 2 IBS: 0.18568352389906653
Fold 3 IBS: 0.18380646487398802
Fold 4 IBS: 0.16033813976360883
Fold 5 IBS: 0.20642365546571148
[I 2024-04-18 06:14:02,779] Trial 96 finished with value: 0.18722613622253315 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 363, 'oob_score': False, 'max_samples': 0.4255182801365352, 'max_features': None, 'min_weight_fraction_leaf': 0.08056036420837291}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.19365837237754394
Fold 2 IBS: 0.183435405665406
Fold 3 IBS: 0.18008910470800357
Fold 4 IBS: 0.17339462295545943
Fold 5 IBS: 0.20781358095494984
[I 2024-04-18 06:14:52,156] Trial 97 finished with value: 0.18767821733227258 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.4693979321374093, 'max_features': None, 'min_weight_fraction_leaf': 0.1201270975782226}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.18503478594867145
Fold 2 IBS: 0.1888913820526276
Fold 3 IBS: 0.1708577577733008
Fold 4 IBS: 0.18063206055766248
Fold 5 IBS: 0.214156204168513
[I 2024-04-18 06:15:27,514] Trial 98 finished with value: 0.18791443810015507 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.3850920531360686, 'max_features': None, 'min_weight_fraction_leaf': 0.1315399576273898}. Best is trial 84 with value: 0.1832464308635407.
Fold 1 IBS: 0.20344124949745349
Fold 2 IBS: 0.18698507294354125
Fold 3 IBS: 0.1879934856478453
Fold 4 IBS: 0.1880278288749208
Fold 5 IBS: 0.2133922668795308
[I 2024-04-18 06:15:38,841] Trial 99 finished with value: 0.19596798076865835 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 1, 'n_estimators': 353, 'oob_score': False, 'max_samples': 0.40653139828572354, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08424550739812792}. Best is trial 84 with value: 0.1832464308635407.


* Best trial for IBS:
 FrozenTrial(number=84, state=TrialState.COMPLETE, values=[0.1832464308635407], datetime_start=datetime.datetime(2024, 4, 18, 6, 2, 20, 281582), datetime_complete=datetime.datetime(2024, 4, 18, 6, 3, 17, 301555), params={'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.3902292236281065, 'max_features': None, 'min_weight_fraction_leaf': 0.0959966989881746}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=84, value=None)


* Best Score for IBS:
 0.1832464308635407

In [81]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [82]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.864
train_ibs:  0.183

#### Test

In [83]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [84]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=11, max_features='auto', max_leaf_nodes=15,
                     max_samples=0.9847467855272036, min_samples_leaf=4,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.04749646122417352,
                     n_estimators=230, random_state=123, warm_start=True)

test_cindex:  0.629

RandomSurvivalForest(max_depth=2, max_features=None, max_leaf_nodes=7,
                     max_samples=0.3902292236281065, min_samples_leaf=4,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.0959966989881746,
                     n_estimators=344, random_state=123)

test_ibs:  0.205

In [85]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [86]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [87]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 06:15:59,301] A new study created in memory with name: no-name-c81615ea-f86c-43b7-bba2-b91156804215

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 06:16:01,892] Trial 0 finished with value: 0.7784578545189774 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:16:08,988] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 06:16:24,028] Trial 2 finished with value: 0.7601142724144229 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7784578545189774.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 06:16:25,567] Trial 3 finished with value: 0.802961090796227 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:16:30,929] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:16:36,996] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 06:16:41,642] Trial 6 finished with value: 0.7670018279196149 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6568627450980392
Fold 4 C-index: 0.7426160337552743
Fold 5 C-index: 0.6150234741784038
[I 2024-04-18 06:16:50,578] Trial 7 finished with value: 0.6820130047188975 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 06:16:51,392] Trial 8 finished with value: 0.7996535923726207 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.6617647058823529
Fold 4 C-index: 0.7468354430379747
Fold 5 C-index: 0.5539906103286385
[I 2024-04-18 06:17:08,732] Trial 9 finished with value: 0.6684380652697066 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:17:11,107] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7524509803921569
Fold 4 C-index: 0.79957805907173
Fold 5 C-index: 0.6737089201877934
[I 2024-04-18 06:17:11,570] Trial 11 finished with value: 0.7252477001554444 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 06:17:12,500] Trial 12 finished with value: 0.7795687852038334 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 06:17:14,285] Trial 13 finished with value: 0.7859770734903794 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:17:16,145] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:17:17,255] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.40889055344541997}. Best is trial 3 with value: 0.802961090796227.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 06:17:18,505] Trial 16 finished with value: 0.7903520467896392 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.884183184043622, 'min_weight_fraction_leaf': 0.10581506507448754}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:17:20,671] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.37217752523657055, 'min_weight_fraction_leaf': 0.19947678741058694}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.7679324894514767
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 06:17:22,051] Trial 18 finished with value: 0.7422562391542786 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 21, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6674013857794929, 'min_weight_fraction_leaf': 0.0023155280568105674}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 06:17:23,774] Trial 19 finished with value: 0.7919172217583121 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 177, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8783131293076132, 'min_weight_fraction_leaf': 0.35588501080184637}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-18 06:17:24,948] Trial 20 finished with value: 0.7884100418072868 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7140167187076433, 'min_weight_fraction_leaf': 0.28881891871571913}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 06:17:27,508] Trial 21 finished with value: 0.7828532818336494 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8819344617828546, 'min_weight_fraction_leaf': 0.3430677365625254}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.704225352112676
[I 2024-04-18 06:17:29,213] Trial 22 finished with value: 0.7949143304625697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8606079420302547, 'min_weight_fraction_leaf': 0.37164871595060495}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:17:30,662] Trial 23 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8095519124644711, 'min_weight_fraction_leaf': 0.44720270469880896}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:17:32,695] Trial 24 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 226, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6043934042800692, 'min_weight_fraction_leaf': 0.3984329214033346}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7181372549019608
Fold 4 C-index: 0.7763713080168776
Fold 5 C-index: 0.6455399061032864
[I 2024-04-18 06:17:33,704] Trial 25 finished with value: 0.7173359925057237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9355023621313151, 'min_weight_fraction_leaf': 0.21828153747802176}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 06:17:40,155] Trial 26 finished with value: 0.75455954833675 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 172, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7429676103800898, 'min_weight_fraction_leaf': 0.2902550218399806}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 06:17:40,912] Trial 27 finished with value: 0.7870695134161543 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 32, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8169136436840319, 'min_weight_fraction_leaf': 0.07430019929598344}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:17:42,135] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 110, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6203838276523786, 'min_weight_fraction_leaf': 0.49397030324411406}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7974683544303798
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 06:17:45,160] Trial 29 finished with value: 0.7664099905509458 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7463806142458222, 'min_weight_fraction_leaf': 0.12619621560869665}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 06:17:47,162] Trial 30 finished with value: 0.7959507907686649 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9444316884960255, 'min_weight_fraction_leaf': 0.10548580221002543}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8392857142857143

Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 06:17:49,282] Trial 31 finished with value: 0.8023701302106281 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9175308644810205, 'min_weight_fraction_leaf': 0.1088935662786611}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 06:17:51,384] Trial 32 finished with value: 0.7950579336258078 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 211, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9467713628420997, 'min_weight_fraction_leaf': 0.08138167552522578}. Best is trial 3 with value: 0.802961090796227.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 06:17:53,821] Trial 33 finished with value: 0.8061356825263047 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.937124800917338, 'min_weight_fraction_leaf': 0.10798501652350923}. Best is trial 33 with value: 0.8061356825263047.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7793427230046949
[I 2024-04-18 06:17:58,947] Trial 34 finished with value: 0.8069410046551562 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9924586053612823, 'min_weight_fraction_leaf': 0.037167307803865623}. Best is trial 34 with value: 0.8069410046551562.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8725490196078431
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8309859154929577
[I 2024-04-18 06:18:05,332] Trial 35 finished with value: 0.8337706480426819 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 307, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.99537727544732, 'min_weight_fraction_leaf': 0.04956730948759107}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 06:18:22,043] Trial 36 finished with value: 0.7482461120884926 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 316, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9947891025922952, 'min_weight_fraction_leaf': 0.040945703784245044}. Best is trial 35 with value: 0.8337706480426819.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8591549295774648
[I 2024-04-18 06:18:30,551] Trial 37 finished with value: 0.847904896492382 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.989290011992841, 'min_weight_fraction_leaf': 0.02856480473176247}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 06:18:38,734] Trial 38 finished with value: 0.8469659293562317 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9932170620443503, 'min_weight_fraction_leaf': 0.050004592573005685}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 06:19:02,319] Trial 39 finished with value: 0.7495415406312282 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9915601275040028, 'min_weight_fraction_leaf': 0.03663352433082424}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8774509803921569
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 06:19:11,754] Trial 40 finished with value: 0.8357412545967835 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 497, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.02508749840989511}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8403755868544601
[I 2024-04-18 06:19:21,173] Trial 41 finished with value: 0.8293587936722526 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47059202334413597, 'min_weight_fraction_leaf': 0.028824885734288947}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.919831223628692
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 06:19:31,482] Trial 42 finished with value: 0.8460265073711295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.47951227685883335, 'min_weight_fraction_leaf': 0.013760080445973905}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 06:19:38,885] Trial 43 finished with value: 0.818279225092199 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 388, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3956943544905941, 'min_weight_fraction_leaf': 0.06238579527271516}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 06:19:48,131] Trial 44 finished with value: 0.8360856192344845 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 443, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4206894066469547, 'min_weight_fraction_leaf': 0.022459821558201455}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.8967136150234741
[I 2024-04-18 06:19:59,765] Trial 45 finished with value: 0.8420095331119368 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5190626877291048, 'min_weight_fraction_leaf': 0.009502780876316706}. Best is trial 37 with value: 0.847904896492382.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.8028169014084507
[I 2024-04-18 06:20:08,878] Trial 46 finished with value: 0.8220544611789512 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 451, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.517469689795079, 'min_weight_fraction_leaf': 0.07841045931780831}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 06:20:38,637] Trial 47 finished with value: 0.7254847827232809 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 414, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.32086266244117334, 'min_weight_fraction_leaf': 0.01763716368072068}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8450704225352113
[I 2024-04-18 06:20:47,889] Trial 48 finished with value: 0.8350464295509287 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 460, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4023308297410664, 'min_weight_fraction_leaf': 0.003079257502260936}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 06:20:55,925] Trial 49 finished with value: 0.8397048390094625 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 368, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5566958033733842, 'min_weight_fraction_leaf': 0.05919578966108157}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 06:21:02,702] Trial 50 finished with value: 0.8168300522124603 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 355, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5346285785794207, 'min_weight_fraction_leaf': 0.05949010437559907}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 06:21:11,976] Trial 51 finished with value: 0.8426559761897272 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4307713618159553, 'min_weight_fraction_leaf': 0.0006143407440005848}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.863849765258216
[I 2024-04-18 06:21:20,517] Trial 52 finished with value: 0.8261414109558636 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.2944027889978438, 'min_weight_fraction_leaf': 0.0025196302934173548}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 06:21:27,705] Trial 53 finished with value: 0.7977685626836676 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 414, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.17582352730772366, 'min_weight_fraction_leaf': 0.061407856338507316}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7805907172995781
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 06:21:35,391] Trial 54 finished with value: 0.7531047646128582 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 473, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.44561277075368966, 'min_weight_fraction_leaf': 0.08811499948097072}. Best is trial 37 with value: 0.847904896492382.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 06:21:45,538] Trial 55 finished with value: 0.8665875045053596 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 423, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5744229763504507, 'min_weight_fraction_leaf': 0.016027842870494274}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.7172995780590717
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 06:21:52,390] Trial 56 finished with value: 0.6951645058986333 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.015257524234107825}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 06:22:02,430] Trial 57 finished with value: 0.8481318045459971 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6103451470664683, 'min_weight_fraction_leaf': 0.047571291705527236}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 06:22:09,505] Trial 58 finished with value: 0.7701604423354131 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 412, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.59366729390164, 'min_weight_fraction_leaf': 0.14674774348708902}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6807511737089202
[I 2024-04-18 06:22:40,562] Trial 59 finished with value: 0.758267844731695 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6716331483015671, 'min_weight_fraction_leaf': 0.04950449980370537}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 06:22:48,830] Trial 60 finished with value: 0.8025306955794198 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6374430422021584, 'min_weight_fraction_leaf': 0.16819923331696962}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8823529411764706
Fold 4 C-index: 0.9324894514767933
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 06:23:00,802] Trial 61 finished with value: 0.8267317399171535 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.49232023541877573, 'min_weight_fraction_leaf': 0.00145953757858059}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8921568627450981
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 06:23:07,563] Trial 62 finished with value: 0.8414621270800418 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 402, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4565775326135385, 'min_weight_fraction_leaf': 0.0216071430745067}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8779342723004695
[I 2024-04-18 06:23:18,017] Trial 63 finished with value: 0.8515511699906788 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 485, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.574595322070414, 'min_weight_fraction_leaf': 0.04569685903621326}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.8544600938967136
[I 2024-04-18 06:23:27,705] Trial 64 finished with value: 0.8397072520072715 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 487, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5869227943626324, 'min_weight_fraction_leaf': 0.04476269499363313}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.784037558685446
[I 2024-04-18 06:23:35,889] Trial 65 finished with value: 0.8070528716762316 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 461, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5714061896889552, 'min_weight_fraction_leaf': 0.09443804061211797}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 06:23:44,125] Trial 66 finished with value: 0.8117060028439325 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 428, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4269898374784659, 'min_weight_fraction_leaf': 0.06693452124581281}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 06:23:50,834] Trial 67 finished with value: 0.8090148375189878 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 375, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8415815579585453, 'min_weight_fraction_leaf': 0.03102886731531589}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7510548523206751
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 06:23:58,941] Trial 68 finished with value: 0.724330800854678 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6969921866106945, 'min_weight_fraction_leaf': 0.08996201441410404}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8794642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8685446009389671
[I 2024-04-18 06:24:06,910] Trial 69 finished with value: 0.8410235474195836 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6336109184394701, 'min_weight_fraction_leaf': 0.04462823296429158}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 06:24:13,816] Trial 70 finished with value: 0.7949235593846933 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9130147369001846, 'min_weight_fraction_leaf': 0.25717771363652614}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 06:24:26,062] Trial 71 finished with value: 0.8504560046599232 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5168055835891595, 'min_weight_fraction_leaf': 0.012986169067804712}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8967136150234741
[I 2024-04-18 06:24:35,823] Trial 72 finished with value: 0.8519584263631383 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5366958727104124, 'min_weight_fraction_leaf': 0.016031857840163272}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.8028169014084507
[I 2024-04-18 06:24:45,401] Trial 73 finished with value: 0.8207791294121825 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5266040099828285, 'min_weight_fraction_leaf': 0.07379071659454789}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.92018779342723
[I 2024-04-18 06:24:57,895] Trial 74 finished with value: 0.8657901849373276 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.556218611994605, 'min_weight_fraction_leaf': 0.026708566480428787}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.658008658008658
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.9156118143459916
Fold 5 C-index: 0.812206572769953
[I 2024-04-18 06:25:05,433] Trial 75 finished with value: 0.8181142885767413 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.569175138136116, 'min_weight_fraction_leaf': 0.049779903595510204}. Best is trial 55 with value: 0.8665875045053596.

Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7136150234741784
[I 2024-04-18 06:25:34,050] Trial 76 finished with value: 0.7457830837322044 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.61013169816922, 'min_weight_fraction_leaf': 0.032654970370419666}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7887323943661971
[I 2024-04-18 06:25:42,448] Trial 77 finished with value: 0.813252260011932 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6556499931697389, 'min_weight_fraction_leaf': 0.11468485034119792}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 06:25:50,043] Trial 78 finished with value: 0.8054529568030716 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5407839514816556, 'min_weight_fraction_leaf': 0.13017998804408376}. Best is trial 55 with value: 0.8665875045053596.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8928571428571429
Fold 3 C-index: 0.9362745098039216
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 06:26:01,514] Trial 79 finished with value: 0.8680221676184047 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9631780533456042, 'min_weight_fraction_leaf': 0.022603700176597446}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 06:26:10,947] Trial 80 finished with value: 0.796736053008863 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5088492830088868, 'min_weight_fraction_leaf': 0.02502911966074306}. Best is trial 79 with value: 0.8680221676184047.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9295774647887324
[I 2024-04-18 06:26:22,407] Trial 81 finished with value: 0.882207251893772 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 372, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9615950289600182, 'min_weight_fraction_leaf': 0.03679139394563669}. Best is trial 81 with value: 0.882207251893772.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.90625
Fold 3 C-index: 0.946078431372549
Fold 4 C-index: 0.9620253164556962
Fold 5 C-index: 0.9436619718309859
[I 2024-04-18 06:26:33,927] Trial 82 finished with value: 0.8858022781309804 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9215686274509803
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9436619718309859
[I 2024-04-18 06:26:46,013] Trial 83 finished with value: 0.8652682964140128 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 339, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9609090906034798, 'min_weight_fraction_leaf': 0.01406330393712882}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9493670886075949
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 06:26:57,885] Trial 84 finished with value: 0.8614808250890755 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9134206211086566, 'min_weight_fraction_leaf': 0.01387175275139686}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.8872549019607843
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 06:27:03,653] Trial 85 finished with value: 0.8498449433258773 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9573743509441937, 'min_weight_fraction_leaf': 0.037220356101627605}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.8028169014084507
[I 2024-04-18 06:27:09,771] Trial 86 finished with value: 0.8063147993763705 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9691139339019299, 'min_weight_fraction_leaf': 0.013557733109048805}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9282700421940928
Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 06:27:17,479] Trial 87 finished with value: 0.8606583123370746 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9145533784322645, 'min_weight_fraction_leaf': 0.07241658060725681}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 06:27:39,158] Trial 88 finished with value: 0.7577736506359624 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.91048505123246, 'min_weight_fraction_leaf': 0.07341369185217136}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 06:27:44,645] Trial 89 finished with value: 0.7985598378397373 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8690506465331735, 'min_weight_fraction_leaf': 0.189066433472832}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6713615023474179
[I 2024-04-18 06:27:50,204] Trial 90 finished with value: 0.7685681160339142 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8972668164493001, 'min_weight_fraction_leaf': 0.31515481216778163}. Best is trial 82 with value: 0.8858022781309804.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.875
Fold 3 C-index: 0.9166666666666666
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9483568075117371
[I 2024-04-18 06:28:01,067] Trial 91 finished with value: 0.862597275251046 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9707802904512073, 'min_weight_fraction_leaf': 0.024021851910904807}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9117647058823529
Fold 4 C-index: 0.9409282700421941
Fold 5 C-index: 0.9389671361502347
[I 2024-04-18 06:28:11,574] Trial 92 finished with value: 0.8605776934106274 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9280981755055671, 'min_weight_fraction_leaf': 0.023404006766994168}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.9068627450980392
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9154929577464789
[I 2024-04-18 06:28:20,274] Trial 93 finished with value: 0.8582896374728435 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 320, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499587877144377, 'min_weight_fraction_leaf': 0.03127381290624083}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9240506329113924
Fold 5 C-index: 0.9014084507042254
[I 2024-04-18 06:28:29,766] Trial 94 finished with value: 0.8665655880498362 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9666217297893754, 'min_weight_fraction_leaf': 0.058324374733458}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8883928571428571
Fold 3 C-index: 0.9313725490196079
Fold 4 C-index: 0.9367088607594937
Fold 5 C-index: 0.8873239436619719
[I 2024-04-18 06:28:38,519] Trial 95 finished with value: 0.8664219797791237 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9706033105898769, 'min_weight_fraction_leaf': 0.06930608338875063}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6901408450704225
[I 2024-04-18 06:28:44,080] Trial 96 finished with value: 0.7713977049757649 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9653170534920801, 'min_weight_fraction_leaf': 0.05657719832813177}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8970588235294118
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8497652582159625
[I 2024-04-18 06:28:50,983] Trial 97 finished with value: 0.8459290116474474 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9660782335192536, 'min_weight_fraction_leaf': 0.10022719516204912}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8839285714285714
Fold 3 C-index: 0.9264705882352942
Fold 4 C-index: 0.9451476793248945
Fold 5 C-index: 0.9248826291079812
[I 2024-04-18 06:29:00,312] Trial 98 finished with value: 0.8772114347448893 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470976294421786, 'min_weight_fraction_leaf': 0.037342531882997666}. Best is trial 82 with value: 0.8858022781309804.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.9019607843137255
Fold 4 C-index: 0.9071729957805907

[I 2024-04-18 06:29:09,746] A new study created in memory with name: no-name-6d57fa8d-8f88-408e-8948-6a29c02337ac

Fold 5 C-index: 0.8826291079812206
[I 2024-04-18 06:29:09,733] Trial 99 finished with value: 0.8535852615977915 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9441404618918096, 'min_weight_fraction_leaf': 0.08095118320482457}. Best is trial 82 with value: 0.8858022781309804.


* Best trial for C-index:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.8858022781309804], datetime_start=datetime.datetime(2024, 4, 18, 6, 26, 22, 414009), datetime_complete=datetime.datetime(2024, 4, 18, 6, 26, 33, 926407), params={'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 336, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.965941994806725, 'min_weight_fraction_leaf': 0.017267854864073284}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for C-index:
 0.8858022781309804

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.19573874032428965
Fold 2 IBS: 0.19215300245103015
Fold 3 IBS: 0.18577123192698092
Fold 4 IBS: 0.18877405090465085
Fold 5 IBS: 0.2108069355911196
[I 2024-04-18 06:29:21,642] Trial 0 finished with value: 0.19464879223961423 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-18 06:29:37,919] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.19464879223961423.
Fold 1 IBS: 0.18661490821092397
Fold 2 IBS: 0.18849796485994302
Fold 3 IBS: 0.16935693688351927
Fold 4 IBS: 0.16616413385030462
Fold 5 IBS: 0.21353095384309942
[I 2024-04-18 06:29:52,372] Trial 2 finished with value: 0.18483297952955807 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18461528870168228
Fold 2 IBS: 0.19204843106240665
Fold 3 IBS: 0.16690491265843854
Fold 4 IBS: 0.1668314734874405
Fold 5 IBS: 0.21495543742143608
[I 2024-04-18 06:29:57,310] Trial 3 finished with value: 0.18507110866628082 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-18 06:30:08,837] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-18 06:30:15,026] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19873722451693057
Fold 2 IBS: 0.19705874496937723
Fold 3 IBS: 0.1849295300703863
Fold 4 IBS: 0.19065127758534944
Fold 5 IBS: 0.21038780527035808
[I 2024-04-18 06:30:27,614] Trial 6 finished with value: 0.1963529164824803 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2092186818635856
Fold 2 IBS: 0.2146879015458582
Fold 3 IBS: 0.2003062385248317
Fold 4 IBS: 0.21667734530345348
Fold 5 IBS: 0.2164099945650469
[I 2024-04-18 06:30:35,056] Trial 7 finished with value: 0.2114600323605552 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.18257976996986042
Fold 2 IBS: 0.19411505967038614
Fold 3 IBS: 0.17136720904530045
Fold 4 IBS: 0.17268722966186423
Fold 5 IBS: 0.21366089922807047
[I 2024-04-18 06:30:36,860] Trial 8 finished with value: 0.18688203351509633 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21317294453259816
Fold 2 IBS: 0.21979053165324058
Fold 3 IBS: 0.20367290529718618
Fold 4 IBS: 0.22322856514743522
Fold 5 IBS: 0.21829561184880927
[I 2024-04-18 06:30:52,828] Trial 9 finished with value: 0.2156321116958539 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.2139727346768592
Fold 2 IBS: 0.2213120202940904
Fold 3 IBS: 0.20503568053719107
Fold 4 IBS: 0.2245613118501098
Fold 5 IBS: 0.21766314539351875
[I 2024-04-18 06:31:10,826] Trial 10 finished with value: 0.21650897855035384 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.194147789023279, 'min_weight_fraction_leaf': 0.20179400484263296}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.19343732165265656
Fold 2 IBS: 0.18906543074097565
Fold 3 IBS: 0.17814248070868705
Fold 4 IBS: 0.17824816439818994
Fold 5 IBS: 0.2121006857387383
[I 2024-04-18 06:31:14,493] Trial 11 finished with value: 0.1901988166478495 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 111, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13052158247107556}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1889048827611632
Fold 2 IBS: 0.19557019296937925
Fold 3 IBS: 0.1711785441540699
Fold 4 IBS: 0.1739105142666198
Fold 5 IBS: 0.21378813670908908
[I 2024-04-18 06:31:20,083] Trial 12 finished with value: 0.18867045417206424 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 176, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6665600668811549, 'min_weight_fraction_leaf': 0.07739259194541037}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.21602403915542812
Fold 2 IBS: 0.22135942967444958
Fold 3 IBS: 0.207522129090302
Fold 4 IBS: 0.22681102026289354
Fold 5 IBS: 0.2196363896884173
[I 2024-04-18 06:31:20,921] Trial 13 finished with value: 0.21827060157429812 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 7, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.33474644057405917, 'min_weight_fraction_leaf': 0.1768405475625161}. Best is trial 2 with value: 0.18483297952955807.
Fold 1 IBS: 0.1908749026630227
Fold 2 IBS: 0.1928239743663976
Fold 3 IBS: 0.16705801079598037
Fold 4 IBS: 0.15060359337075535
Fold 5 IBS: 0.22085198243745763
[I 2024-04-18 06:31:25,720] Trial 14 finished with value: 0.18444249272672272 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8615610863035676, 'min_weight_fraction_leaf': 0.00662188941038383}. Best is trial 14 with value: 0.18444249272672272.

Fold 1 IBS: 0.18383586845275063
Fold 2 IBS: 0.2000835973214874
Fold 3 IBS: 0.15349960014749967
Fold 4 IBS: 0.13669669509253474
Fold 5 IBS: 0.23424660843190576
[I 2024-04-18 06:31:38,892] Trial 15 finished with value: 0.18167247388923563 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9163782618183121, 'min_weight_fraction_leaf': 0.0023088139988564262}. Best is trial 15 with value: 0.18167247388923563.
Fold 1 IBS: 0.1860236953856494
Fold 2 IBS: 0.2016030715036904
Fold 3 IBS: 0.155469005191737
Fold 4 IBS: 0.13731033566044606
Fold 5 IBS: 0.22747010982683524
[I 2024-04-18 06:31:51,762] Trial 16 finished with value: 0.1815752435136716 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8957765840335672, 'min_weight_fraction_leaf': 0.010191311991891749}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17998535045197436
Fold 2 IBS: 0.18813498335112747
Fold 3 IBS: 0.17047606760378545
Fold 4 IBS: 0.18020967518371683
Fold 5 IBS: 0.21407585022837167
[I 2024-04-18 06:32:01,602] Trial 17 finished with value: 0.18657638536379517 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9042785918294833, 'min_weight_fraction_leaf': 0.42038595995868033}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.21392851730727483
Fold 2 IBS: 0.2203112302740686
Fold 3 IBS: 0.20531706619567533
Fold 4 IBS: 0.22509036885374237
Fold 5 IBS: 0.21706040157641074
[I 2024-04-18 06:32:14,187] Trial 18 finished with value: 0.21634151684143438 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 312, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.22508105757456376}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1780064255903332
Fold 2 IBS: 0.1911276300331187
Fold 3 IBS: 0.16786438905278223
Fold 4 IBS: 0.1726113214449123
Fold 5 IBS: 0.21667391270579664
[I 2024-04-18 06:32:22,789] Trial 19 finished with value: 0.18525673576538862 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895543806821031, 'min_weight_fraction_leaf': 0.3097789443945588}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17575403131452658
Fold 2 IBS: 0.20366539827290087
Fold 3 IBS: 0.1659331777904529
Fold 4 IBS: 0.16662123172048018
Fold 5 IBS: 0.2231823176617039
[I 2024-04-18 06:32:35,092] Trial 20 finished with value: 0.18703123135201288 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 352, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8867517870122669, 'min_weight_fraction_leaf': 0.3678346055590361}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18848376456042643
Fold 2 IBS: 0.18922500536261308
Fold 3 IBS: 0.1744885363823047
Fold 4 IBS: 0.16595205181867084
Fold 5 IBS: 0.2141373046342922
[I 2024-04-18 06:32:39,048] Trial 21 finished with value: 0.18645733255166147 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8638184920383039, 'min_weight_fraction_leaf': 0.006217904257385862}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18773929580856016
Fold 2 IBS: 0.18598260697487606
Fold 3 IBS: 0.16906412373747556
Fold 4 IBS: 0.16368622468310087
Fold 5 IBS: 0.21228289069902992
[I 2024-04-18 06:32:48,299] Trial 22 finished with value: 0.18375102838060853 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9916304513453179, 'min_weight_fraction_leaf': 0.04142928400152037}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18853550770642435
Fold 2 IBS: 0.18431558910147325
Fold 3 IBS: 0.1692342266159003
Fold 4 IBS: 0.161355478193544
Fold 5 IBS: 0.21536507583817294
[I 2024-04-18 06:32:57,522] Trial 23 finished with value: 0.18376117549110296 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.971566349397283, 'min_weight_fraction_leaf': 0.048431151398292585}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18850231376560317
Fold 2 IBS: 0.18839766190435636
Fold 3 IBS: 0.17219466449743842
Fold 4 IBS: 0.169776646003973
Fold 5 IBS: 0.21215306500728826
[I 2024-04-18 06:33:04,048] Trial 24 finished with value: 0.18620487023573185 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9955995613709457, 'min_weight_fraction_leaf': 0.09809641655746978}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.1921961203281156
Fold 2 IBS: 0.18453047987592264
Fold 3 IBS: 0.16816775310750728
Fold 4 IBS: 0.16025534556804477
Fold 5 IBS: 0.21319844694890142
[I 2024-04-18 06:33:15,129] Trial 25 finished with value: 0.18366962916569834 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8862362117578689, 'min_weight_fraction_leaf': 0.041224153446454304}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.17583280457561398
Fold 2 IBS: 0.22475673220665077
Fold 3 IBS: 0.15629098950451684
Fold 4 IBS: 0.1521771664224135
Fold 5 IBS: 0.23338728904188227
[I 2024-04-18 06:33:32,075] Trial 26 finished with value: 0.1884889963502155 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 360, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7252723068238901, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.20101808740413787
Fold 2 IBS: 0.19364223596866614
Fold 3 IBS: 0.1581801817697089
Fold 4 IBS: 0.13490957896358
Fold 5 IBS: 0.22061607552916476
[I 2024-04-18 06:33:55,335] Trial 27 finished with value: 0.18167323192705154 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 380, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.845241798302616, 'min_weight_fraction_leaf': 0.027493332139652292}. Best is trial 16 with value: 0.1815752435136716.
Fold 1 IBS: 0.18622176253816625
Fold 2 IBS: 0.1999255042061287
Fold 3 IBS: 0.15584044840112993
Fold 4 IBS: 0.13526516764544533
Fold 5 IBS: 0.22802733572495915
[I 2024-04-18 06:34:17,830] Trial 28 finished with value: 0.18105604370316586 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8292254352883182, 'min_weight_fraction_leaf': 0.0850371679063824}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.17657957905072683
Fold 2 IBS: 0.22919795735904133
Fold 3 IBS: 0.15929222778603266
Fold 4 IBS: 0.15524572509143825
Fold 5 IBS: 0.23445783766810277
[I 2024-04-18 06:34:33,119] Trial 29 finished with value: 0.19095466539106837 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 388, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7274266056837884, 'min_weight_fraction_leaf': 0.10433587359666342}. Best is trial 28 with value: 0.18105604370316586.

Fold 1 IBS: 0.18973195855840097
Fold 2 IBS: 0.19901752012782084
Fold 3 IBS: 0.1553163395473765
Fold 4 IBS: 0.13719070606611738
Fold 5 IBS: 0.22779776404493374
[I 2024-04-18 06:34:49,020] Trial 30 finished with value: 0.18181085766892985 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 305, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8220971907615917, 'min_weight_fraction_leaf': 0.076444606879153}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.2164877455822723
Fold 2 IBS: 0.18827035681808446
Fold 3 IBS: 0.16565039781780372
Fold 4 IBS: 0.1417428766421557
Fold 5 IBS: 0.21575647924950747
[I 2024-04-18 06:35:22,842] Trial 31 finished with value: 0.18558157122196473 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 394, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9184090898444338, 'min_weight_fraction_leaf': 0.024048041704110457}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.19225590417182326
Fold 2 IBS: 0.19791478229895018
Fold 3 IBS: 0.15389649317000442
Fold 4 IBS: 0.13656122267395734
Fold 5 IBS: 0.2252432881883185
[I 2024-04-18 06:35:39,771] Trial 32 finished with value: 0.18117433810061073 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 339, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8398341558075527, 'min_weight_fraction_leaf': 0.07586243370778376}. Best is trial 28 with value: 0.18105604370316586.
Fold 1 IBS: 0.190099017520626
Fold 2 IBS: 0.19508386306537273
Fold 3 IBS: 0.15693141894064483
Fold 4 IBS: 0.1365814363126798
Fold 5 IBS: 0.2242513991199539
[I 2024-04-18 06:35:55,878] Trial 33 finished with value: 0.18058942699185546 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 328, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7393625680125055, 'min_weight_fraction_leaf': 0.0754095802252665}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1755388893326841
Fold 2 IBS: 0.22138923578766054
Fold 3 IBS: 0.15690295668954182
Fold 4 IBS: 0.1534002161724209
Fold 5 IBS: 0.23198506769187896
[I 2024-04-18 06:36:08,574] Trial 34 finished with value: 0.18784327313483729 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6411042409555412, 'min_weight_fraction_leaf': 0.1529713735680485}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18263254865306666
Fold 2 IBS: 0.20049141147500113
Fold 3 IBS: 0.1589092797218102
Fold 4 IBS: 0.13938245171749084
Fold 5 IBS: 0.22964090743188564
[I 2024-04-18 06:36:33,034] Trial 35 finished with value: 0.1822113197998509 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7381816364515512, 'min_weight_fraction_leaf': 0.09309533777806683}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20497295855599004
Fold 2 IBS: 0.20576214803730022
Fold 3 IBS: 0.19198391113255453
Fold 4 IBS: 0.20085090326245184
Fold 5 IBS: 0.21341213707903006
[I 2024-04-18 06:36:42,627] Trial 36 finished with value: 0.2033964116134653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 329, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6138083294843051, 'min_weight_fraction_leaf': 0.0629620770536272}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19527602912356506
Fold 2 IBS: 0.19485558505510198
Fold 3 IBS: 0.18174564019749553
Fold 4 IBS: 0.1886871891677721
Fold 5 IBS: 0.21159832776451956
[I 2024-04-18 06:36:56,422] Trial 37 finished with value: 0.19443255426169087 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 415, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5042351390354268, 'min_weight_fraction_leaf': 0.11525786573963492}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.2123324981539864
Fold 2 IBS: 0.21873675502636114
Fold 3 IBS: 0.2026801887391686
Fold 4 IBS: 0.2224371860221609
Fold 5 IBS: 0.2175210624415119
[I 2024-04-18 06:37:03,271] Trial 38 finished with value: 0.21474153807663776 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 215, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7775660926270328, 'min_weight_fraction_leaf': 0.20133705660393178}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396615975925184
Fold 2 IBS: 0.22136475473478168
Fold 3 IBS: 0.2049150370158522
Fold 4 IBS: 0.22458804795980403
Fold 5 IBS: 0.21835431962555002
[I 2024-04-18 06:37:19,975] Trial 39 finished with value: 0.21663766381904798 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 8, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3933070032512962, 'min_weight_fraction_leaf': 0.26079682823609596}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19711707736031672
Fold 2 IBS: 0.19196214561471756
Fold 3 IBS: 0.18237907022466343
Fold 4 IBS: 0.1838407369325067
Fold 5 IBS: 0.21066154976207546
[I 2024-04-18 06:37:30,316] Trial 40 finished with value: 0.19319211597885597 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.06421109758861666}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18187508975758154
Fold 2 IBS: 0.20470571701119905
Fold 3 IBS: 0.15462214843892588
Fold 4 IBS: 0.13791700485858222
Fold 5 IBS: 0.23199241229585657
[I 2024-04-18 06:37:43,687] Trial 41 finished with value: 0.18222247447242906 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 287, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9487776860553198, 'min_weight_fraction_leaf': 0.0012764688125286236}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18083474896839194
Fold 2 IBS: 0.20655297055486127
Fold 3 IBS: 0.1560859878078812
Fold 4 IBS: 0.13735104264690487
Fold 5 IBS: 0.2318981646914065
[I 2024-04-18 06:38:03,486] Trial 42 finished with value: 0.18254458293388914 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 410, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9263396365475575, 'min_weight_fraction_leaf': 0.07533198780818874}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.179220247667936
Fold 2 IBS: 0.20803479971941155
Fold 3 IBS: 0.15642984958925052
Fold 4 IBS: 0.1381823380575358
Fold 5 IBS: 0.23098585177667733
[I 2024-04-18 06:38:16,228] Trial 43 finished with value: 0.18257061736216224 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8260902726928496, 'min_weight_fraction_leaf': 0.12086835806486591}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20295458389503712
Fold 2 IBS: 0.18760128987987226
Fold 3 IBS: 0.16259754916275176
Fold 4 IBS: 0.13943881701142766
Fold 5 IBS: 0.21929671791406735
[I 2024-04-18 06:38:32,090] Trial 44 finished with value: 0.18237779157263123 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 269, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.755115496265169, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.21196016007242774
Fold 2 IBS: 0.21737810285668177
Fold 3 IBS: 0.20221519268515586
Fold 4 IBS: 0.21985834792032022
Fold 5 IBS: 0.21707100228614096
[I 2024-04-18 06:38:38,747] Trial 45 finished with value: 0.21369656116414532 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 226, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5998350649536632, 'min_weight_fraction_leaf': 0.05464331917294846}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18076053104236317
Fold 2 IBS: 0.2172100382529918
Fold 3 IBS: 0.15472808053026357
Fold 4 IBS: 0.14511587127121353
Fold 5 IBS: 0.2339666086051307
[I 2024-04-18 06:38:47,434] Trial 46 finished with value: 0.18635622594039253 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8402810693773478, 'min_weight_fraction_leaf': 0.144161655351996}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18818806948138703
Fold 2 IBS: 0.18585276291120573
Fold 3 IBS: 0.16931029735325712
Fold 4 IBS: 0.16495818665843412
Fold 5 IBS: 0.21221551295471194
[I 2024-04-18 06:38:56,840] Trial 47 finished with value: 0.1841049658717992 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9302813606785956, 'min_weight_fraction_leaf': 0.08930568525499841}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18928681061078317
Fold 2 IBS: 0.19449353516562573
Fold 3 IBS: 0.15782262613968703
Fold 4 IBS: 0.13927270133528777
Fold 5 IBS: 0.22728509464662824
[I 2024-04-18 06:39:18,784] Trial 48 finished with value: 0.1816321535796024 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 374, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7058374194287877, 'min_weight_fraction_leaf': 0.021185992511726287}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20695865791961138
Fold 2 IBS: 0.18446003189676
Fold 3 IBS: 0.1637203264374506
Fold 4 IBS: 0.14167171912108306
Fold 5 IBS: 0.21852048251093703
[I 2024-04-18 06:39:42,786] Trial 49 finished with value: 0.18306624357716844 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6944137175640025, 'min_weight_fraction_leaf': 0.023748345961229673}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.20395296501568036
Fold 2 IBS: 0.20356332435883023
Fold 3 IBS: 0.19198232817565247
Fold 4 IBS: 0.20503408115744123
Fold 5 IBS: 0.212977623601451
[I 2024-04-18 06:40:00,475] Trial 50 finished with value: 0.20350206446181107 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.1282263128781066}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1892478776386835
Fold 2 IBS: 0.1985691975751118
Fold 3 IBS: 0.1551366953595447
Fold 4 IBS: 0.13797047291334816
Fold 5 IBS: 0.2247976743236853
[I 2024-04-18 06:40:20,358] Trial 51 finished with value: 0.18114438356207468 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7991896596470566, 'min_weight_fraction_leaf': 0.020902281449632076}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18966875407315306
Fold 2 IBS: 0.20026668125593905
Fold 3 IBS: 0.1581902551783595
Fold 4 IBS: 0.1446898271378981
Fold 5 IBS: 0.22398935878186912
[I 2024-04-18 06:40:38,629] Trial 52 finished with value: 0.18336097528544376 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7963262944115481, 'min_weight_fraction_leaf': 0.06178807863600248}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1808545696000534
Fold 2 IBS: 0.2092001659472061
Fold 3 IBS: 0.1569134957561024
Fold 4 IBS: 0.14354275776617909
Fold 5 IBS: 0.23138632547295945
[I 2024-04-18 06:40:54,193] Trial 53 finished with value: 0.1843794629085001 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6795691608327338, 'min_weight_fraction_leaf': 0.028449876548026755}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18963311160047724
Fold 2 IBS: 0.20900009168815242
Fold 3 IBS: 0.15966211681395587
Fold 4 IBS: 0.14477830095268193
Fold 5 IBS: 0.2227272285777302
[I 2024-04-18 06:41:14,273] Trial 54 finished with value: 0.18516016992659953 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8793032020733721, 'min_weight_fraction_leaf': 0.07859078488282405}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1844153405050917
Fold 2 IBS: 0.20329447035960194
Fold 3 IBS: 0.156445527494686
Fold 4 IBS: 0.1385632327057539
Fold 5 IBS: 0.2286479785748904
[I 2024-04-18 06:41:33,701] Trial 55 finished with value: 0.18227330992800478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615617181298988, 'min_weight_fraction_leaf': 0.0463333928046309}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21398416445233792
Fold 2 IBS: 0.22128642959017203
Fold 3 IBS: 0.20479170826088208
Fold 4 IBS: 0.22465474077969866
Fold 5 IBS: 0.21866500422066165
[I 2024-04-18 06:41:48,285] Trial 56 finished with value: 0.21667640946075045 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7048250986458913, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.19154362908633138
Fold 2 IBS: 0.19025716940029977
Fold 3 IBS: 0.164641271809976
Fold 4 IBS: 0.1535983543533534
Fold 5 IBS: 0.21130984092669008
[I 2024-04-18 06:42:01,561] Trial 57 finished with value: 0.18227005311533012 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6509352527427404, 'min_weight_fraction_leaf': 0.01668177754116703}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1834614522490023
Fold 2 IBS: 0.20274762979546487
Fold 3 IBS: 0.1558259112444169
Fold 4 IBS: 0.13699785208498225
Fold 5 IBS: 0.227941946402463
[I 2024-04-18 06:42:21,941] Trial 58 finished with value: 0.18139495835526587 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 361, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8149000200033439, 'min_weight_fraction_leaf': 0.1073613839314761}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18264043127662102
Fold 2 IBS: 0.20563295068882514
Fold 3 IBS: 0.15774830297383735
Fold 4 IBS: 0.1409283130574975
Fold 5 IBS: 0.2302026151594693
[I 2024-04-18 06:42:44,855] Trial 59 finished with value: 0.18343052263125006 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 433, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.806842099370764, 'min_weight_fraction_leaf': 0.11194912742691053}. Best is trial 33 with value: 0.18058942699185546.

Fold 1 IBS: 0.1940353275621495
Fold 2 IBS: 0.19268012360689624
Fold 3 IBS: 0.18110607070067974
Fold 4 IBS: 0.18845548212963192
Fold 5 IBS: 0.2126254989546211
[I 2024-04-18 06:42:56,849] Trial 60 finished with value: 0.1937805005907957 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 305, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8575527275336559, 'min_weight_fraction_leaf': 0.18982981109623043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1881809892682945
Fold 2 IBS: 0.19390719781855054
Fold 3 IBS: 0.1588739037458674
Fold 4 IBS: 0.1367801254919651
Fold 5 IBS: 0.2266847482237021
[I 2024-04-18 06:43:16,674] Trial 61 finished with value: 0.18088539290967592 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7615189086372551, 'min_weight_fraction_leaf': 0.04095649181576018}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.1876754810451395
Fold 2 IBS: 0.19768374549602719
Fold 3 IBS: 0.15918815613876297
Fold 4 IBS: 0.13767028389195304
Fold 5 IBS: 0.22732368447379522
[I 2024-04-18 06:43:36,353] Trial 62 finished with value: 0.18190827020913558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 354, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7661278291112643, 'min_weight_fraction_leaf': 0.08934183246037483}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18158763535398614
Fold 2 IBS: 0.2058728330109782
Fold 3 IBS: 0.15634716717840097
Fold 4 IBS: 0.1393411349809578
Fold 5 IBS: 0.2305445348222664
[I 2024-04-18 06:44:00,491] Trial 63 finished with value: 0.18273866106931788 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8238233376692735, 'min_weight_fraction_leaf': 0.05246336243742043}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17660125627972975
Fold 2 IBS: 0.19950632480062638
Fold 3 IBS: 0.16593947035609424
Fold 4 IBS: 0.1676045776632834
Fold 5 IBS: 0.2238259008995345
[I 2024-04-18 06:44:19,374] Trial 64 finished with value: 0.18669550599985366 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 396, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8942985122180038, 'min_weight_fraction_leaf': 0.3739424140604035}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.17841559751185995
Fold 2 IBS: 0.2181576301923148
Fold 3 IBS: 0.15699607135742621
Fold 4 IBS: 0.14279995324086395
Fold 5 IBS: 0.23321351389303
[I 2024-04-18 06:44:37,028] Trial 65 finished with value: 0.185916553239099 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 321, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.157443472337933}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.21396919511710527
Fold 2 IBS: 0.22118312582133598
Fold 3 IBS: 0.20498660484161652
Fold 4 IBS: 0.22465182954726737
Fold 5 IBS: 0.218115813183982
[I 2024-04-18 06:44:50,356] Trial 66 finished with value: 0.21658131370226147 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.30029194568874296, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 33 with value: 0.18058942699185546.
Fold 1 IBS: 0.18873872659716473
Fold 2 IBS: 0.18791922078055107
Fold 3 IBS: 0.16453860462735764
Fold 4 IBS: 0.15207602931399142
Fold 5 IBS: 0.20920273391154215
[I 2024-04-18 06:45:06,706] Trial 67 finished with value: 0.18049506304612142 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 363, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7471014922297948, 'min_weight_fraction_leaf': 0.03879604091198421}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.18615572700917984
Fold 2 IBS: 0.1920922899342238
Fold 3 IBS: 0.1645126632956227
Fold 4 IBS: 0.15374635033745812
Fold 5 IBS: 0.21328354527729806
[I 2024-04-18 06:45:23,089] Trial 68 finished with value: 0.1819581151707565 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7411630198194591, 'min_weight_fraction_leaf': 0.0741944771835793}. Best is trial 67 with value: 0.18049506304612142.
Fold 1 IBS: 0.19221322343005157
Fold 2 IBS: 0.18747725704463866
Fold 3 IBS: 0.16271946974327306
Fold 4 IBS: 0.14893868190888562
Fold 5 IBS: 0.21053329237786875
[I 2024-04-18 06:45:38,713] Trial 69 finished with value: 0.18037638490094354 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873531668221723, 'min_weight_fraction_leaf': 0.03743740450038523}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19123449448406776
Fold 2 IBS: 0.18634187192427262
Fold 3 IBS: 0.16568962439316362
Fold 4 IBS: 0.14733219858236207
Fold 5 IBS: 0.2124042387639548
[I 2024-04-18 06:45:54,584] Trial 70 finished with value: 0.18060048562956416 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 342, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7884602797651743, 'min_weight_fraction_leaf': 0.03984902133772039}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19415415468436753
Fold 2 IBS: 0.1861415676999523
Fold 3 IBS: 0.16573890197473515
Fold 4 IBS: 0.14488999289270504
Fold 5 IBS: 0.2125204407894076
[I 2024-04-18 06:46:09,843] Trial 71 finished with value: 0.18068901160823353 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 343, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7819431269555398, 'min_weight_fraction_leaf': 0.03595825517448436}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.18984009710041735
Fold 2 IBS: 0.18778536549020883
Fold 3 IBS: 0.16555752286430367
Fold 4 IBS: 0.15132302702120518
Fold 5 IBS: 0.21187635057748866
[I 2024-04-18 06:46:27,587] Trial 72 finished with value: 0.18127647261072471 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 379, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7158237789595601, 'min_weight_fraction_leaf': 0.038892933150377174}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.19217054361716007
Fold 2 IBS: 0.18605477551854072
Fold 3 IBS: 0.1657195529075007
Fold 4 IBS: 0.1499033271314654
Fold 5 IBS: 0.21296314297306798
[I 2024-04-18 06:46:42,239] Trial 73 finished with value: 0.18136226842954697 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 348, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7776848187295278, 'min_weight_fraction_leaf': 0.041701970157165584}. Best is trial 69 with value: 0.18037638490094354.
Fold 1 IBS: 0.1919591413798442
Fold 2 IBS: 0.18680709380802085
Fold 3 IBS: 0.16611125142067912
Fold 4 IBS: 0.14880604710483025
Fold 5 IBS: 0.20779386416865475
[I 2024-04-18 06:46:55,357] Trial 74 finished with value: 0.18029547957640585 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 297, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7429251540613239, 'min_weight_fraction_leaf': 0.034122782806489685}. Best is trial 74 with value: 0.18029547957640585.

Fold 1 IBS: 0.20438643925191893
Fold 2 IBS: 0.1844312624795873
Fold 3 IBS: 0.17002168747641047
Fold 4 IBS: 0.14791525733420058
Fold 5 IBS: 0.21362624602582111
[I 2024-04-18 06:47:08,906] Trial 75 finished with value: 0.18407617851358768 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 296, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651148142523113, 'min_weight_fraction_leaf': 0.0005666053087619444}. Best is trial 74 with value: 0.18029547957640585.
Fold 1 IBS: 0.19306514020322818
Fold 2 IBS: 0.1842925536567217
Fold 3 IBS: 0.16281493341095712
Fold 4 IBS: 0.15026196851923793
Fold 5 IBS: 0.20907571723485416
[I 2024-04-18 06:47:20,125] Trial 76 finished with value: 0.1799020626049998 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6121072626884605, 'min_weight_fraction_leaf': 0.0375652827686181}. Best is trial 76 with value: 0.1799020626049998.
Fold 1 IBS: 0.19533191990808643
Fold 2 IBS: 0.18454077801628752
Fold 3 IBS: 0.16320484107502187
Fold 4 IBS: 0.14544314028091127
Fold 5 IBS: 0.2072692252418508
[I 2024-04-18 06:47:31,572] Trial 77 finished with value: 0.17915798090443158 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6024939881120506, 'min_weight_fraction_leaf': 0.03546615930788915}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18979383260600338
Fold 2 IBS: 0.18481018797624196
Fold 3 IBS: 0.16409936588525315
Fold 4 IBS: 0.1553259082203432
Fold 5 IBS: 0.21243305321372438
[I 2024-04-18 06:47:41,475] Trial 78 finished with value: 0.18129246958031323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 242, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6205262617833929, 'min_weight_fraction_leaf': 0.06309017855153265}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.1918516718483265
Fold 2 IBS: 0.18449081490872005
Fold 3 IBS: 0.1634428327969914
Fold 4 IBS: 0.14997364872576785
Fold 5 IBS: 0.20763662708758918
[I 2024-04-18 06:47:52,751] Trial 79 finished with value: 0.17947911907347897 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 273, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5944767216434486, 'min_weight_fraction_leaf': 0.03643432579651321}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19348005656430173
Fold 2 IBS: 0.18296399211241365
Fold 3 IBS: 0.16491035077279387
Fold 4 IBS: 0.1455645707584685
Fold 5 IBS: 0.21079082139142424
[I 2024-04-18 06:48:04,976] Trial 80 finished with value: 0.1795419583198804 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5738838339262928, 'min_weight_fraction_leaf': 0.01238447949116667}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19385166663658865
Fold 2 IBS: 0.1878440819583883
Fold 3 IBS: 0.165800948446184
Fold 4 IBS: 0.1476511958697635
Fold 5 IBS: 0.21025560153134265
[I 2024-04-18 06:48:17,848] Trial 81 finished with value: 0.1810806988884534 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5619354088357825, 'min_weight_fraction_leaf': 0.01565582556320865}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.18524833693093437
Fold 2 IBS: 0.19165170252652822
Fold 3 IBS: 0.16392769525776144
Fold 4 IBS: 0.15846496418540476
Fold 5 IBS: 0.2094683241817906
[I 2024-04-18 06:48:27,960] Trial 82 finished with value: 0.1817522046164839 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 232, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4638072011147492, 'min_weight_fraction_leaf': 0.05201742843067371}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19237185503026552
Fold 2 IBS: 0.18676559841777626
Fold 3 IBS: 0.16407017518328942
Fold 4 IBS: 0.1449765914249507
Fold 5 IBS: 0.20892364253609055
[I 2024-04-18 06:48:40,588] Trial 83 finished with value: 0.1794215725184745 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 275, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5992998998564371, 'min_weight_fraction_leaf': 0.011892575602326625}. Best is trial 77 with value: 0.17915798090443158.
Fold 1 IBS: 0.19394142912089907
Fold 2 IBS: 0.18287172537269059
Fold 3 IBS: 0.16363670208229797
Fold 4 IBS: 0.14366900591399753
Fold 5 IBS: 0.20892071259321834
[I 2024-04-18 06:48:51,888] Trial 84 finished with value: 0.1786079150166207 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 255, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5921978094028723, 'min_weight_fraction_leaf': 0.010779734440848038}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1934701576048722
Fold 2 IBS: 0.18356601291714442
Fold 3 IBS: 0.16350384856124178
Fold 4 IBS: 0.14362897455716736
Fold 5 IBS: 0.20935617313715904
[I 2024-04-18 06:49:02,707] Trial 85 finished with value: 0.17870503335551696 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 250, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.595683013252236, 'min_weight_fraction_leaf': 0.005599104949055786}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.191846570784011
Fold 2 IBS: 0.18680840183499514
Fold 3 IBS: 0.1640377893844091
Fold 4 IBS: 0.14812980552665286
Fold 5 IBS: 0.21175031324864774
[I 2024-04-18 06:49:13,256] Trial 86 finished with value: 0.18051457615574318 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 254, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5360572837412131, 'min_weight_fraction_leaf': 0.01185351158382457}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-18 06:49:24,640] Trial 87 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5878837691778286, 'min_weight_fraction_leaf': 0.008079079463688634}. Best is trial 84 with value: 0.1786079150166207.
Fold 1 IBS: 0.1914457217244506
Fold 2 IBS: 0.18052086391051203
Fold 3 IBS: 0.16215789222067095
Fold 4 IBS: 0.15081933866613106
Fold 5 IBS: 0.20784710369879605
[I 2024-04-18 06:49:35,939] Trial 88 finished with value: 0.1785581840441121 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19147665396547064
Fold 2 IBS: 0.18176345202270439
Fold 3 IBS: 0.16414261135311045
Fold 4 IBS: 0.15299647769153543
Fold 5 IBS: 0.2087010317651242
[I 2024-04-18 06:49:47,337] Trial 89 finished with value: 0.17981604535958903 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.585692212182858, 'min_weight_fraction_leaf': 0.0008838182441561699}. Best is trial 88 with value: 0.1785581840441121.

Fold 1 IBS: 0.19250257566167933
Fold 2 IBS: 0.18261531719008467
Fold 3 IBS: 0.16180974496548703
Fold 4 IBS: 0.14890218044290915
Fold 5 IBS: 0.2130135609453814
[I 2024-04-18 06:49:56,072] Trial 90 finished with value: 0.1797686758411083 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 202, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5935532822743834, 'min_weight_fraction_leaf': 0.007362099342399538}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19466401388017032
Fold 2 IBS: 0.18486336673650017
Fold 3 IBS: 0.16588446237479346
Fold 4 IBS: 0.1465134541216928
Fold 5 IBS: 0.21287370502296324
[I 2024-04-18 06:50:04,524] Trial 91 finished with value: 0.18095980042722398 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 197, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5826023797451899, 'min_weight_fraction_leaf': 0.00862038165347273}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19077050579200147
Fold 2 IBS: 0.18831329801859226
Fold 3 IBS: 0.16406961249991853
Fold 4 IBS: 0.14929003357858256
Fold 5 IBS: 0.21018706108863028
[I 2024-04-18 06:50:15,520] Trial 92 finished with value: 0.18052610219554502 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 252, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5070555008286651, 'min_weight_fraction_leaf': 0.009333694056201223}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.1942451581816268
Fold 2 IBS: 0.1830703742457603
Fold 3 IBS: 0.16097178413138724
Fold 4 IBS: 0.14654845241459755
Fold 5 IBS: 0.2121967833645088
[I 2024-04-18 06:50:25,154] Trial 93 finished with value: 0.17940651046757616 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 221, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5934768503177845, 'min_weight_fraction_leaf': 0.014878777313562812}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19736082973729024
Fold 2 IBS: 0.18309515782891686
Fold 3 IBS: 0.16366471911833752
Fold 4 IBS: 0.14526303100181923
Fold 5 IBS: 0.21417837651704477
[I 2024-04-18 06:50:32,769] Trial 94 finished with value: 0.18071242284068173 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 165, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6349033637819771, 'min_weight_fraction_leaf': 0.019343000331144743}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18578897328440416
Fold 2 IBS: 0.19239898124845878
Fold 3 IBS: 0.1616809082216946
Fold 4 IBS: 0.15362867068252217
Fold 5 IBS: 0.21229660365479858
[I 2024-04-18 06:50:41,679] Trial 95 finished with value: 0.18115882741837566 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 217, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5448232910672774, 'min_weight_fraction_leaf': 0.025610081517443647}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.18377286728444794
Fold 2 IBS: 0.18906137730159184
Fold 3 IBS: 0.162592162450128
Fold 4 IBS: 0.15646349234384718
Fold 5 IBS: 0.21273640937582883
[I 2024-04-18 06:50:50,153] Trial 96 finished with value: 0.18092526175116874 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 200, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5166375602788441, 'min_weight_fraction_leaf': 0.01004295110119176}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19320716981789404
Fold 2 IBS: 0.1833817504678623
Fold 3 IBS: 0.16276222353530903
Fold 4 IBS: 0.15005917812838457
Fold 5 IBS: 0.21149567165602431
[I 2024-04-18 06:51:00,950] Trial 97 finished with value: 0.18018119872109484 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 230, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5810941412605699, 'min_weight_fraction_leaf': 0.028715470907523112}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19665218645247226
Fold 2 IBS: 0.18461786549962422
Fold 3 IBS: 0.16585865869273442
Fold 4 IBS: 0.14468826763530046
Fold 5 IBS: 0.20808627775303898
[I 2024-04-18 06:51:12,287] Trial 98 finished with value: 0.17998065120663406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 246, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.558904433592998, 'min_weight_fraction_leaf': 0.0007593749444425981}. Best is trial 88 with value: 0.1785581840441121.
Fold 1 IBS: 0.19225977892006962
Fold 2 IBS: 0.19011577254533654
Fold 3 IBS: 0.1738613054687569
Fold 4 IBS: 0.1638041351036002
Fold 5 IBS: 0.2130479662700931
[I 2024-04-18 06:51:17,927] Trial 99 finished with value: 0.18661779166157128 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4718103481231686, 'min_weight_fraction_leaf': 0.013594026171513878}. Best is trial 88 with value: 0.1785581840441121.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.1785581840441121], datetime_start=datetime.datetime(2024, 4, 18, 6, 49, 24, 646200), datetime_complete=datetime.datetime(2024, 4, 18, 6, 49, 35, 938325), params={'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 279, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5945245081220258, 'min_weight_fraction_leaf': 0.006841645987133443}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.1785581840441121

In [88]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [89]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.886
train_ibs:  0.179

#### Test

In [90]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [91]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=9, max_features=None, max_leaf_nodes=14,
                   max_samples=0.965941994806725, min_samples_split=7,
                   min_weight_fraction_leaf=0.017267854864073284,
                   n_estimators=336, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.662

ExtraSurvivalTrees(max_depth=9, max_features=0.1, max_leaf_nodes=20,
                   max_samples=0.5945245081220258, min_samples_leaf=4,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.006841645987133443,
                   n_estimators=279, oob_score=True, random_state=123,
                   warm_start=True)

IBS: 0.2

In [92]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [93]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 06:51:27,493] A new study created in memory with name: no-name-1b2a5feb-3b43-4509-918d-fec944c9fb4c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:52:49,991] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:53:28,466] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:54:14,098] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:55:50,368] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:56:27,938] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:56:37,226] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:57:36,460] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:57:52,101] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 06:57:54,402] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 07:00:58,045] Trial 9 finished with value: 0.7375077219334873 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6160337552742616
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 07:05:20,212] Trial 10 finished with value: 0.6769991466942861 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:09:59,426] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.715962441314554
[I 2024-04-18 07:13:57,788] Trial 12 finished with value: 0.7180894810070741 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:15:49,912] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:18:22,252] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:21:08,293] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:22:37,556] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:25:41,864] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:29:58,556] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:30:12,954] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:32:00,405] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.6286919831223629
Fold 5 C-index: 0.6384976525821596
[I 2024-04-18 07:35:44,537] Trial 21 finished with value: 0.6596743990023763 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7375077219334873.
Fold 1 C-index: 0.7554112554112554
Fold 2 C-index: 0.8236607142857143
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.7447257383966245
Fold 5 C-index: 0.6830985915492958
[I 2024-04-18 07:39:30,612] Trial 22 finished with value: 0.7577518089481858 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:42:19,612] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:45:38,400] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:47:26,575] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5654008438818565
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 07:50:19,398] Trial 26 finished with value: 0.5295120936590003 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:53:00,702] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:55:15,301] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:56:47,913] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 07:58:50,180] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.7075892857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6118143459915611
Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 08:01:52,918] Trial 31 finished with value: 0.6975838362663174 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:03:59,522] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9113568740147856, 'learning_rate': 0.01936213758007274, 'dropout_rate': 0.1444594228310892, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 1.6183832787391992, 'min_weight_fraction_leaf': 0.4304319218036696, 'max_features': 'auto', 'min_impurity_decrease': 1.0277484189219154e-07, 'validation_fraction': 0.9117669993681574, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:05:41,620] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9728428556912192, 'learning_rate': 0.015742740923125064, 'dropout_rate': 0.30020186346124766, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 9.846141209805609, 'min_weight_fraction_leaf': 0.4958404435609285, 'max_features': 'auto', 'min_impurity_decrease': 2.2786499479002052e-07, 'validation_fraction': 0.8344453462672722, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:06:57,623] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.8496036715186095, 'learning_rate': 0.009253864701923034, 'dropout_rate': 0.22658656718653286, 'n_estimators': 403, 'criterion': 'friedman_mse', 'ccp_alpha': 0.641857272630336, 'min_weight_fraction_leaf': 0.43629024868714544, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9168532630851701, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:07:19,588] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.6806458891075314, 'learning_rate': 0.0016219483573201542, 'dropout_rate': 0.4078621112435248, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3706867126320781, 'max_features': None, 'min_impurity_decrease': 7.8587698841458e-07, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:09:15,567] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.9551502281749775, 'learning_rate': 0.026078126474550274, 'dropout_rate': 0.34789169882120996, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.40891402270131877, 'min_weight_fraction_leaf': 0.2325827619040188, 'max_features': 'auto', 'min_impurity_decrease': 7.145093229830912e-06, 'validation_fraction': 0.6747809687204889, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:09:24,174] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.7371581418455209, 'learning_rate': 0.0145417341576766, 'dropout_rate': 0.16172130996739253, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.3174537146690439, 'max_features': None, 'min_impurity_decrease': 2.89190119114804e-07, 'validation_fraction': 0.9548743578197549, 'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:09:58,741] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.8063221166350547, 'learning_rate': 0.006424315075939495, 'dropout_rate': 0.7673236646699829, 'n_estimators': 329, 'criterion': 'friedman_mse', 'ccp_alpha': 9.162989248724866, 'min_weight_fraction_leaf': 0.14601082900734919, 'max_features': 'auto', 'min_impurity_decrease': 1.1529415174162498e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:11:20,403] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.8852748015168422, 'learning_rate': 0.02975783779377629, 'dropout_rate': 0.2673592786040255, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1216454788806307, 'min_weight_fraction_leaf': 0.09194334498965648, 'max_features': 1, 'min_impurity_decrease': 8.588272604740831e-07, 'validation_fraction': 0.7628102853958754, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:12:28,279] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.5809866593286652, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.20816102573612866, 'n_estimators': 353, 'criterion': 'squared_error', 'ccp_alpha': 3.7898554763179284, 'min_weight_fraction_leaf': 0.4711996214427754, 'max_features': 'auto', 'min_impurity_decrease': 2.3584088371991464e-07, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.6666666666666666
Fold 4 C-index: 0.5907172995780591
Fold 5 C-index: 0.5821596244131455
[I 2024-04-18 08:12:28,837] Trial 41 finished with value: 0.6152707311185872 and parameters: {'subsample': 0.9964498482283193, 'learning_rate': 0.004158109708816752, 'dropout_rate': 0.13644226542045526, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4011310798872364, 'max_features': 'auto', 'min_impurity_decrease': 1.0090377437612141e-07, 'validation_fraction': 0.9993318631652353, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:14:45,850] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.10858843727097561, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.415120560514267, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9524403904515271, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:15:36,908] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.919916216831853, 'learning_rate': 0.0016321845585985228, 'dropout_rate': 0.16429624388711278, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.471921644995546, 'min_weight_fraction_leaf': 0.3704175909956657, 'max_features': 'auto', 'min_impurity_decrease': 0.0009050261380449993, 'validation_fraction': 0.8779568222622545, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:16:57,739] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.998598837606123, 'learning_rate': 0.015327765728784649, 'dropout_rate': 0.6859431566383477, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.2679892492803537, 'min_weight_fraction_leaf': 0.2706416993480579, 'max_features': 'auto', 'min_impurity_decrease': 8.738793222106795e-07, 'validation_fraction': 0.9744834265061879, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7683982683982684
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.6126760563380281
[I 2024-04-18 08:18:17,814] Trial 45 finished with value: 0.7169525524273146 and parameters: {'subsample': 0.8612793275132423, 'learning_rate': 0.008591203396202965, 'dropout_rate': 0.20237082649972205, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.09266970930573763, 'min_weight_fraction_leaf': 0.4478112124993417, 'max_features': 0.1, 'min_impurity_decrease': 1.775469126785021e-07, 'validation_fraction': 0.798828420958444, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:18:29,087] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.8576868620948644, 'learning_rate': 0.021769927230194788, 'dropout_rate': 0.9694253886674298, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 1.9903431110600875, 'min_weight_fraction_leaf': 0.45430295635160706, 'max_features': 0.1, 'min_impurity_decrease': 2.0131584568637675e-06, 'validation_fraction': 0.7976029227783121, 'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:18:53,639] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7056873961179977, 'learning_rate': 0.00929853233926034, 'dropout_rate': 0.3140351257259953, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 7.181314443016622, 'min_weight_fraction_leaf': 0.49464896810642006, 'max_features': 0.1, 'min_impurity_decrease': 2.1438208123963576e-05, 'validation_fraction': 0.6179698437276481, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:20:10,053] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7837245323509484, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.21043558082214228, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.4617743734350054, 'min_weight_fraction_leaf': 0.45246089314517907, 'max_features': 0.1, 'min_impurity_decrease': 4.221379974644956e-07, 'validation_fraction': 0.863214331971344, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:20:41,606] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.6507081753968225, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.26780621294484797, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 1.378218906104398, 'min_weight_fraction_leaf': 0.2916489694540698, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6845184717076465, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:21:42,924] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.03353370774351387, 'dropout_rate': 0.3787195779305788, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.7561621193902213, 'min_weight_fraction_leaf': 0.47814765735031256, 'max_features': 0.1, 'min_impurity_decrease': 1.6961878462023105e-07, 'validation_fraction': 0.8310153288008191, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7215189873417721
Fold 5 C-index: 0.6244131455399061
[I 2024-04-18 08:23:15,887] Trial 51 finished with value: 0.6982448681347772 and parameters: {'subsample': 0.9590755303360702, 'learning_rate': 0.001263628446733103, 'dropout_rate': 0.13293847894616523, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7341772151898734
Fold 5 C-index: 0.6338028169014085
[I 2024-04-18 08:24:49,739] Trial 52 finished with value: 0.7007875648598147 and parameters: {'subsample': 0.9309483691931049, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.1309992574789837, 'n_estimators': 478, 'criterion': 'squared_error', 'ccp_alpha': 0.036615235505588, 'min_weight_fraction_leaf': 0.4052806656624778, 'max_features': 'sqrt', 'min_impurity_decrease': 2.8184597843569143e-07, 'validation_fraction': 0.8992446934973449, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:26:02,007] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9119792149240027, 'learning_rate': 0.0011619738930768678, 'dropout_rate': 0.12019527221159815, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.33436888398209985, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0912509934146174e-06, 'validation_fraction': 0.7204767494493249, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:26:26,808] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.9422391559777883, 'learning_rate': 0.006469543850280348, 'dropout_rate': 0.8266353856620614, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.46449392886564433, 'min_weight_fraction_leaf': 0.20818644825744925, 'max_features': 'sqrt', 'min_impurity_decrease': 3.17346833824979e-07, 'validation_fraction': 0.8741639290304148, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:27:34,990] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8715328822130523, 'learning_rate': 0.011790338191706525, 'dropout_rate': 0.23926982708415356, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.4008945876330496, 'min_weight_fraction_leaf': 0.44051010658711054, 'max_features': 'sqrt', 'min_impurity_decrease': 5.615119149330365e-07, 'validation_fraction': 0.7887577239921508, 'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:29:06,402] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8015434219726096, 'learning_rate': 0.04061736247319854, 'dropout_rate': 0.1937709311352404, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.037591557618962, 'min_weight_fraction_leaf': 0.41307911755286036, 'max_features': 'sqrt', 'min_impurity_decrease': 1.854323715915516e-06, 'validation_fraction': 0.907633472782051, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.6619718309859155
[I 2024-04-18 08:29:39,543] Trial 57 finished with value: 0.694941105261048 and parameters: {'subsample': 0.47167111494444647, 'learning_rate': 0.018997287630538016, 'dropout_rate': 0.5891903890315894, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.007297661499282945, 'min_weight_fraction_leaf': 0.37949114392069716, 'max_features': 'sqrt', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.5599065409082953, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:31:08,808] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8972461919118405, 'learning_rate': 0.09671804411942064, 'dropout_rate': 0.10627978332234836, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.7590888481670788, 'min_weight_fraction_leaf': 0.25730821949204663, 'max_features': 'sqrt', 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9487716255435797, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:32:24,456] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.8358264770513102, 'learning_rate': 0.022823901724539096, 'dropout_rate': 0.28631447973846014, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.429314535364776, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': None, 'min_impurity_decrease': 5.131055724938468e-07, 'validation_fraction': 0.8437837761372522, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:33:11,150] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.22299455896998305, 'learning_rate': 0.0056069075336912105, 'dropout_rate': 0.3357871821335161, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 2.523299286625464, 'min_weight_fraction_leaf': 0.339521597129798, 'max_features': 'sqrt', 'min_impurity_decrease': 2.9638541699067996e-07, 'validation_fraction': 0.6410967521884806, 'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:34:38,859] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.010928263297494037, 'dropout_rate': 0.1843386992247676, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.22729228144381666, 'min_weight_fraction_leaf': 0.4037400789999268, 'max_features': 1, 'min_impurity_decrease': 1.310082490250357e-07, 'validation_fraction': 0.9622895789424137, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7257383966244726
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 08:36:02,364] Trial 62 finished with value: 0.7272773109470696 and parameters: {'subsample': 0.9756177414915416, 'learning_rate': 0.00487963758524286, 'dropout_rate': 0.14510716910347804, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.023608499803350655, 'min_weight_fraction_leaf': 0.22961838496572504, 'max_features': 0.1, 'min_impurity_decrease': 1.6297128321880156e-07, 'validation_fraction': 0.8969787245486088, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:37:21,313] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.9288654416933328, 'learning_rate': 0.013829624766460978, 'dropout_rate': 0.13653478929605453, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.7247405887368557, 'min_weight_fraction_leaf': 0.22479730957902153, 'max_features': 0.1, 'min_impurity_decrease': 5.575423017349267e-07, 'validation_fraction': 0.8936351824952593, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:38:35,235] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.3944303299889498, 'learning_rate': 0.005756823204408979, 'dropout_rate': 0.2327252655551748, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.30460031424817835, 'min_weight_fraction_leaf': 0.1885535376775951, 'max_features': 0.1, 'min_impurity_decrease': 3.354219995894836e-07, 'validation_fraction': 0.9295137020256315, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.7088607594936709
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 08:39:59,026] Trial 65 finished with value: 0.7220969706866847 and parameters: {'subsample': 0.8628229894737177, 'learning_rate': 0.008827661920605995, 'dropout_rate': 0.19214391420812213, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.002774143765696062, 'min_weight_fraction_leaf': 0.19849959041931706, 'max_features': 0.1, 'min_impurity_decrease': 2.5741032571081618e-06, 'validation_fraction': 0.81580153800389, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:41:36,947] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.7758851752296808, 'learning_rate': 0.009751888770788269, 'dropout_rate': 0.19122550095328222, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.898614500640199, 'min_weight_fraction_leaf': 0.15180913487925937, 'max_features': 0.1, 'min_impurity_decrease': 2.693782393576339e-06, 'validation_fraction': 0.8022828972461258, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:42:54,286] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8737277188190908, 'learning_rate': 0.017575803118928604, 'dropout_rate': 0.24650681062055632, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 1.184288941522344, 'min_weight_fraction_leaf': 0.20306006951316619, 'max_features': 0.1, 'min_impurity_decrease': 1.2046523007672827e-06, 'validation_fraction': 0.7485906145710193, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:43:54,737] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.819932305524277, 'learning_rate': 0.09136620662883123, 'dropout_rate': 0.21544296697082643, 'n_estimators': 401, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5667792373547914, 'min_weight_fraction_leaf': 0.24594914856187006, 'max_features': 0.1, 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.8633504402260139, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:44:51,471] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5360295416604122, 'learning_rate': 0.026072943824179864, 'dropout_rate': 0.15995252701068877, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 6.315803860540386, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 0.1, 'min_impurity_decrease': 4.676506095993518e-06, 'validation_fraction': 0.8221337964376644, 'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:45:49,860] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.7391884515801697, 'learning_rate': 0.0131539926632262, 'dropout_rate': 0.4370458221877003, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.3030856819564138, 'min_weight_fraction_leaf': 0.04227011624339991, 'max_features': 'log2', 'min_impurity_decrease': 4.094308088527539e-05, 'validation_fraction': 0.7311035029930464, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.6854460093896714
[I 2024-04-18 08:47:26,947] Trial 71 finished with value: 0.7057455222887223 and parameters: {'subsample': 0.8958059912610585, 'learning_rate': 0.00404243977738313, 'dropout_rate': 0.13685925262610546, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.27174017051065336, 'max_features': 0.1, 'min_impurity_decrease': 1.6903767334797878e-07, 'validation_fraction': 0.893021390165449, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.7130801687763713
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 08:49:00,997] Trial 72 finished with value: 0.7255383448051743 and parameters: {'subsample': 0.9033994568982797, 'learning_rate': 0.008576558002904872, 'dropout_rate': 0.1796601786158867, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.0049265702435675185, 'min_weight_fraction_leaf': 0.2698684133835347, 'max_features': 0.1, 'min_impurity_decrease': 2.520131654025212e-07, 'validation_fraction': 0.9039347234285049, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:50:26,502] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9030072931863139, 'learning_rate': 0.00868732713600762, 'dropout_rate': 0.2744775845272275, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8157217970730618, 'min_weight_fraction_leaf': 0.2706425923382264, 'max_features': 0.1, 'min_impurity_decrease': 1.5060083036338323e-07, 'validation_fraction': 0.8429645916964783, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:50:34,809] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8551098377950185, 'learning_rate': 0.017852326043636436, 'dropout_rate': 0.18670893655691517, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.3282745678695592, 'min_weight_fraction_leaf': 0.2216310042184134, 'max_features': 0.1, 'min_impurity_decrease': 0.00020700246413734948, 'validation_fraction': 0.7700706578571286, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:51:37,507] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.8885953564344566, 'learning_rate': 0.003923453373901735, 'dropout_rate': 0.25497810906198315, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 4.774324490228468, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 1.0309115243736615e-07, 'validation_fraction': 0.9298417275031959, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:53:03,200] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9671878335188347, 'learning_rate': 0.010137963140872869, 'dropout_rate': 0.1720967582787876, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.6017992226500892, 'min_weight_fraction_leaf': 0.2343670795832099, 'max_features': 0.1, 'min_impurity_decrease': 4.1389285578024635e-07, 'validation_fraction': 0.4666209889121972, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:54:19,869] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.7817997136792754, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.21878505744240392, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 2.226175878213271, 'min_weight_fraction_leaf': 0.11673456101680679, 'max_features': 0.1, 'min_impurity_decrease': 2.278338706941225e-07, 'validation_fraction': 0.8870735397490029, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:55:12,993] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.85971117635256, 'learning_rate': 0.020702169760542934, 'dropout_rate': 0.10184607865359452, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 1.1613144933398152, 'min_weight_fraction_leaf': 0.28827493961902323, 'max_features': 0.1, 'min_impurity_decrease': 1.0554012317973208e-06, 'validation_fraction': 0.7800831726807022, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:56:06,739] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7085303006120247, 'learning_rate': 0.007203573027836778, 'dropout_rate': 0.3309372439616984, 'n_estimators': 405, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7098465234455584, 'min_weight_fraction_leaf': 0.16909333970802584, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9874471393466349, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 08:57:28,635] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.43152853207212877, 'learning_rate': 0.012535821130981227, 'dropout_rate': 0.28829477813771426, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.29587735180979763, 'min_weight_fraction_leaf': 0.1932252614573767, 'max_features': None, 'min_impurity_decrease': 2.607076310858583e-06, 'validation_fraction': 0.2486636150723724, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.75
Fold 4 C-index: 0.7046413502109705
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 08:59:04,198] Trial 81 finished with value: 0.7232266055095437 and parameters: {'subsample': 0.9310152909641193, 'learning_rate': 0.004901464536992707, 'dropout_rate': 0.14649845200705908, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.0401224705257143, 'min_weight_fraction_leaf': 0.2140884860716641, 'max_features': 0.1, 'min_impurity_decrease': 3.294643059864092e-07, 'validation_fraction': 0.9215349695607397, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:00:40,065] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9804673759889536, 'learning_rate': 0.003705242334357205, 'dropout_rate': 0.15221754469070822, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.6905373562188476, 'min_weight_fraction_leaf': 0.214345215244296, 'max_features': 0.1, 'min_impurity_decrease': 1.535249456479472e-07, 'validation_fraction': 0.9202835513583518, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:02:01,683] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9176538987097111, 'learning_rate': 0.0076523566881114835, 'dropout_rate': 0.22968230522988387, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.20240849843431086, 'min_weight_fraction_leaf': 0.2383259127009152, 'max_features': 0.1, 'min_impurity_decrease': 4.399657878596901e-07, 'validation_fraction': 0.9767059181287342, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:03:16,091] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8255635604133957, 'learning_rate': 0.0036977258275946636, 'dropout_rate': 0.20402072590631012, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5198465206932167, 'min_weight_fraction_leaf': 0.15653086076945935, 'max_features': 0.1, 'min_impurity_decrease': 7.178610075896741e-07, 'validation_fraction': 0.8482804900297096, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7745098039215687

Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.676056338028169
[I 2024-04-18 09:05:09,660] Trial 85 finished with value: 0.7189891256993891 and parameters: {'subsample': 0.8918331608196582, 'learning_rate': 0.015605784733698558, 'dropout_rate': 0.14750634204389826, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.30357930249568654, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9997678373401905, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:06:46,814] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10092948452566086, 'learning_rate': 0.01532810679048379, 'dropout_rate': 0.17099114695337342, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.876197483648788, 'min_weight_fraction_leaf': 0.3015328988188304, 'max_features': 'auto', 'min_impurity_decrease': 1.6482137590771691e-06, 'validation_fraction': 0.9342270075718234, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:07:20,943] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.5929593460046293, 'learning_rate': 0.016822571784752067, 'dropout_rate': 0.19867600397015794, 'n_estimators': 263, 'criterion': 'squared_error', 'ccp_alpha': 0.23496207633721847, 'min_weight_fraction_leaf': 0.24832976306734728, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.9659857207632909, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:08:55,280] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9310702721088772, 'learning_rate': 0.009959700506785971, 'dropout_rate': 0.2555430411709441, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 8.088457238075051, 'min_weight_fraction_leaf': 0.22631747365745694, 'max_features': 'auto', 'min_impurity_decrease': 2.710852350800199e-07, 'validation_fraction': 0.7056533437856146, 'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:10:33,654] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.975612460964084, 'learning_rate': 0.012850444381300855, 'dropout_rate': 0.11846749927359909, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 1.425464889112629, 'min_weight_fraction_leaf': 0.1784633449883898, 'max_features': 'auto', 'min_impurity_decrease': 5.921522228604161e-07, 'validation_fraction': 0.9996319172531741, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:12:09,530] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.34045768877643007, 'learning_rate': 0.0581528234960663, 'dropout_rate': 0.15210696274519644, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9372956395735829, 'min_weight_fraction_leaf': 0.13514216761654674, 'max_features': 1, 'min_impurity_decrease': 3.412090206574042e-07, 'validation_fraction': 0.5798720476990769, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.7278481012658228
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 09:13:49,039] Trial 91 finished with value: 0.7299130919568267 and parameters: {'subsample': 0.8979069506313946, 'learning_rate': 0.008101193305888026, 'dropout_rate': 0.14427259297048306, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.05667376231617895, 'min_weight_fraction_leaf': 0.2662831727524566, 'max_features': 'auto', 'min_impurity_decrease': 2.2001283077718922e-07, 'validation_fraction': 0.8878992829265958, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:15:12,672] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8025284770642525, 'learning_rate': 0.008198746448650564, 'dropout_rate': 0.17658024519117366, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4944517626406935, 'min_weight_fraction_leaf': 0.281932786781083, 'max_features': 'auto', 'min_impurity_decrease': 2.092935799209152e-07, 'validation_fraction': 0.8240961218884286, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:16:25,981] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.866078324832748, 'learning_rate': 0.011107826666625974, 'dropout_rate': 0.15001558634639325, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.20618034747646607, 'min_weight_fraction_leaf': 0.26022589277342434, 'max_features': 'auto', 'min_impurity_decrease': 1.2653383309827397e-07, 'validation_fraction': 0.8676712222376753, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:17:20,238] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.8418316701841008, 'learning_rate': 0.006152062924759251, 'dropout_rate': 0.2291019421217302, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.6324588657889718, 'min_weight_fraction_leaf': 0.4804568203093911, 'max_features': 'auto', 'min_impurity_decrease': 9.38303925215205e-07, 'validation_fraction': 0.9086059943821162, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:18:34,241] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.87747934958027, 'learning_rate': 0.0012139304758565887, 'dropout_rate': 0.12498646666495616, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.3715046104772777, 'min_weight_fraction_leaf': 0.208961689017974, 'max_features': 'auto', 'min_impurity_decrease': 2.382313770891545e-07, 'validation_fraction': 0.3818872933371859, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6446078431372549
Fold 4 C-index: 0.6940928270042194
Fold 5 C-index: 0.7089201877934272
[I 2024-04-18 09:19:38,938] Trial 96 finished with value: 0.696510102322911 and parameters: {'subsample': 0.94218553177403, 'learning_rate': 0.020033817173644677, 'dropout_rate': 0.3058190228136884, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.030434277972844224, 'min_weight_fraction_leaf': 0.19188954018236168, 'max_features': 'auto', 'min_impurity_decrease': 3.679493950049724e-07, 'validation_fraction': 0.9459755275340084, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 22 with value: 0.7577518089481858.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:19:52,382] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.9071107405480169, 'learning_rate': 0.013884656270412483, 'dropout_rate': 0.8479620532477699, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 1.069614033248094, 'min_weight_fraction_leaf': 0.32699666489884094, 'max_features': 'log2', 'min_impurity_decrease': 5.25058355616678e-07, 'validation_fraction': 0.8836386308311208, 'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-18 09:20:42,480] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.9531544060001753, 'learning_rate': 0.008555926298082998, 'dropout_rate': 0.20235805532585233, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 0.7543795415309705, 'min_weight_fraction_leaf': 0.30398885673134707, 'max_features': 'auto', 'min_impurity_decrease': 1.0466185221530527e-07, 'validation_fraction': 0.9694358139640935, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 22 with value: 0.7577518089481858.
Fold 1 C-index: 0.7640692640692641
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.5654008438818565

[I 2024-04-18 09:21:43,565] A new study created in memory with name: no-name-d62c7a09-df8e-4d2f-be41-f0f8c8328b3c

Fold 5 C-index: 0.6103286384976526
[I 2024-04-18 09:21:43,544] Trial 99 finished with value: 0.6663823683373736 and parameters: {'subsample': 0.9976459171012907, 'learning_rate': 0.024328086787534252, 'dropout_rate': 0.36361374787631456, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.004395791161995251, 'min_weight_fraction_leaf': 0.353628504086837, 'max_features': 'auto', 'min_impurity_decrease': 1.5812750205075571e-07, 'validation_fraction': 0.8128875839784486, 'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 22 with value: 0.7577518089481858.


* Best trial for C-index:
 FrozenTrial(number=22, state=TrialState.COMPLETE, values=[0.7577518089481858], datetime_start=datetime.datetime(2024, 4, 18, 7, 35, 44, 573822), datetime_complete=datetime.datetime(2024, 4, 18, 7, 39, 30, 611067), params={'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=22, value=None)


* Best Score for C-index:
 0.7577518089481858

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:22:04,938] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:22:14,661] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:22:25,804] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:22:52,011] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:23:02,077] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:23:04,738] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:23:20,092] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:23:25,592] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:23:26,351] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21278960135067226
Fold 2 IBS: 0.22075148425471117
Fold 3 IBS: 0.20356154640252785
Fold 4 IBS: 0.22366437810992945
Fold 5 IBS: 0.2175108694850557
[I 2024-04-18 09:24:14,327] Trial 9 finished with value: 0.2156555759205793 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21360363678959007
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.20421474792063551
Fold 4 IBS: 0.22456346085174822
Fold 5 IBS: 0.21803455300047256
[I 2024-04-18 09:25:29,960] Trial 10 finished with value: 0.21637936117854983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:26:52,344] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2138334609344149
Fold 2 IBS: 0.22151322501680365
Fold 3 IBS: 0.20446062477316612
Fold 4 IBS: 0.2246559027106978
Fold 5 IBS: 0.2180563962052136
[I 2024-04-18 09:28:00,551] Trial 12 finished with value: 0.2165039219280592 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 09:28:28,814] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:29:24,227] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:29:57,044] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:30:15,391] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:30:58,642] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:31:20,817] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:31:25,362] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:32:10,560] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21367586546116044
Fold 2 IBS: 0.22153601357644734
Fold 3 IBS: 0.20438542163118117
Fold 4 IBS: 0.22463472155111044
Fold 5 IBS: 0.2180079529732588
[I 2024-04-18 09:32:59,817] Trial 21 finished with value: 0.21644799503863163 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21300133805358812
Fold 2 IBS: 0.22092783506924327

Fold 3 IBS: 0.20392740109457028
Fold 4 IBS: 0.22400556985244785
Fold 5 IBS: 0.2175786554209321
[I 2024-04-18 09:33:57,416] Trial 22 finished with value: 0.2158881598981563 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:34:48,513] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:35:21,028] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:35:50,845] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:36:16,712] Trial 26 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:36:19,925] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:36:27,956] Trial 28 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:36:59,535] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:37:49,487] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.2132673053926921
Fold 2 IBS: 0.22138150435074114
Fold 3 IBS: 0.20416936232206076
Fold 4 IBS: 0.224409146213765
Fold 5 IBS: 0.2177869543616682
[I 2024-04-18 09:38:41,806] Trial 31 finished with value: 0.2162028545281854 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21250908818560812
Fold 2 IBS: 0.22112061913596615
Fold 3 IBS: 0.20357254804690844
Fold 4 IBS: 0.22431509484129145
Fold 5 IBS: 0.21754679795245008
[I 2024-04-18 09:39:34,507] Trial 32 finished with value: 0.2158128296324448 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:40:07,724] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:40:42,320] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:40:54,392] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:41:33,444] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:41:38,345] Trial 37 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:41:54,833] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:42:20,301] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:42:54,099] Trial 40 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 9 with value: 0.2156555759205793.
Fold 1 IBS: 0.21343873621972445
Fold 2 IBS: 0.22049446029877326
Fold 3 IBS: 0.20337828484272225
Fold 4 IBS: 0.22303639527565466
Fold 5 IBS: 0.21729676723732877
[I 2024-04-18 09:43:52,617] Trial 41 finished with value: 0.21552892877484067 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.2131030184453258
Fold 2 IBS: 0.22050327285628324
Fold 3 IBS: 0.2033673824751969
Fold 4 IBS: 0.22363217726195525
Fold 5 IBS: 0.21724767258898225
[I 2024-04-18 09:44:53,006] Trial 42 finished with value: 0.2155707047255487 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:46:02,915] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:46:59,923] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:47:15,542] Trial 45 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21368294038898764
Fold 2 IBS: 0.22138561655450684
Fold 3 IBS: 0.2042880559361189
Fold 4 IBS: 0.22453830345531042
Fold 5 IBS: 0.21794750132893198
[I 2024-04-18 09:47:59,902] Trial 46 finished with value: 0.21636848353277113 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:48:24,827] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:48:25,123] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:48:36,919] Trial 49 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 09:49:08,275] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21305615407340403
Fold 2 IBS: 0.22124588111973337
Fold 3 IBS: 0.20390302508767316
Fold 4 IBS: 0.22446365006496424
Fold 5 IBS: 0.21777819332443837
[I 2024-04-18 09:50:00,516] Trial 51 finished with value: 0.21608938073404263 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21352169783850614
Fold 2 IBS: 0.22120550026908148
Fold 3 IBS: 0.20396949286236565
Fold 4 IBS: 0.22452441731877534
Fold 5 IBS: 0.2178146994022686
[I 2024-04-18 09:50:52,546] Trial 52 finished with value: 0.21620716153819944 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:51:40,844] Trial 53 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:52:29,333] Trial 54 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:53:08,815] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 09:53:39,524] Trial 56 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:54:13,436] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 09:54:52,818] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 09:55:23,307] Trial 59 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:55:49,064] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:56:41,921] Trial 61 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9319260511303565, 'learning_rate': 0.006981217524957076, 'dropout_rate': 0.2694290399109642, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.2266262530125842, 'min_weight_fraction_leaf': 0.2262208916321135, 'max_features': 'auto', 'min_impurity_decrease': 6.393438969585487e-06, 'validation_fraction': 0.968342815685117, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21261827944826023
Fold 2 IBS: 0.2212835131478303
Fold 3 IBS: 0.20384635335083123
Fold 4 IBS: 0.22428599240586905
Fold 5 IBS: 0.21722666261844198
[I 2024-04-18 09:57:31,833] Trial 62 finished with value: 0.21585216019424655 and parameters: {'subsample': 0.9972198040262032, 'learning_rate': 0.008659221224759001, 'dropout_rate': 0.18470289302046516, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.022476866600004634, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 3.745982455886227e-06, 'validation_fraction': 0.9275220875852723, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:57:48,852] Trial 63 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9899309662352432, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 09:58:33,301] Trial 64 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9658825052862857, 'learning_rate': 0.010845363858236992, 'dropout_rate': 0.13571080979315037, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.3681339382709387, 'min_weight_fraction_leaf': 0.15534331606940482, 'max_features': 'log2', 'min_impurity_decrease': 8.60046486145071e-06, 'validation_fraction': 0.9205869937759958, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21299720012323184
Fold 2 IBS: 0.22115174939969934
Fold 3 IBS: 0.2038040121811597
Fold 4 IBS: 0.2242157275656328
Fold 5 IBS: 0.21734625390047366
[I 2024-04-18 09:59:26,850] Trial 65 finished with value: 0.21590298863403948 and parameters: {'subsample': 0.9661607708539444, 'learning_rate': 0.008868026173365113, 'dropout_rate': 0.17835638219464384, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.002725826040487267, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135

Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 10:00:09,872] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9998769833869746, 'learning_rate': 0.003967598379054899, 'dropout_rate': 0.17654958266634313, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.8981368148483696, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'auto', 'min_impurity_decrease': 7.140027633149786e-05, 'validation_fraction': 0.6362228335648394, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:00:47,243] Trial 67 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8945386029541793, 'learning_rate': 0.01494075298406419, 'dropout_rate': 0.209071801122636, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1837261226658302, 'min_weight_fraction_leaf': 0.10443241497369499, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5552258602982892e-05, 'validation_fraction': 0.7259068897097584, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-18 10:01:48,360] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.843502945752621, 'learning_rate': 0.02075147594960792, 'dropout_rate': 0.16252263519114862, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.057901034918407895, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.6846740503948187, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:02:31,490] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.01037165919107231, 'dropout_rate': 0.19004731427008625, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.34303232955200197, 'min_weight_fraction_leaf': 0.3579731281150166, 'max_features': 'auto', 'min_impurity_decrease': 0.00014344627836102727, 'validation_fraction': 0.7769648880006281, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:03:21,285] Trial 70 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6499145948799803, 'learning_rate': 0.008667614598934925, 'dropout_rate': 0.2379061541841675, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.6762661413605899, 'min_weight_fraction_leaf': 0.2053436289550881, 'max_features': None, 'min_impurity_decrease': 2.7112245092072337e-05, 'validation_fraction': 0.5272974695233066, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21365379061917414
Fold 2 IBS: 0.22138264547298084
Fold 3 IBS: 0.2043021502572646
Fold 4 IBS: 0.22456249898531583
Fold 5 IBS: 0.2178752609515109
[I 2024-04-18 10:04:14,774] Trial 71 finished with value: 0.21635526925724924 and parameters: {'subsample': 0.9554665295189709, 'learning_rate': 0.004772306432110387, 'dropout_rate': 0.30773217080297294, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.019537053946387287, 'max_features': 'auto', 'min_impurity_decrease': 3.603782675882374e-06, 'validation_fraction': 0.8818766703918308, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 41 with value: 0.21552892877484067.
Fold 1 IBS: 0.21009179135163386
Fold 2 IBS: 0.21999119714274143
Fold 3 IBS: 0.2019997974702572
Fold 4 IBS: 0.22308677215739936
Fold 5 IBS: 0.2164934631302429
[I 2024-04-18 10:05:11,421] Trial 72 finished with value: 0.21433260425045497 and parameters: {'subsample': 0.9233416329717381, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.12211037740366137, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.004815836437462028, 'min_weight_fraction_leaf': 0.2452551786385524, 'max_features': 'auto', 'min_impurity_decrease': 1.5300590715832769e-06, 'validation_fraction': 0.974284387349558, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:05:22,253] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.916509573532907, 'learning_rate': 0.01366625897147706, 'dropout_rate': 0.10211108319082117, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.35137810274202946, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'auto', 'min_impurity_decrease': 5.253021283264037e-07, 'validation_fraction': 0.9862680394354211, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 16}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:06:11,443] Trial 74 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.98093897605085, 'learning_rate': 0.01711555655405715, 'dropout_rate': 0.13243922080536136, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.7083433911466146, 'min_weight_fraction_leaf': 0.24361782259873882, 'max_features': 'auto', 'min_impurity_decrease': 1.0928587879200682e-06, 'validation_fraction': 0.8125486143795312, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 72 with value: 0.21433260425045497.
Fold 1 IBS: 0.20063679042123642
Fold 2 IBS: 0.2148812250636474
Fold 3 IBS: 0.19380589049848737
Fold 4 IBS: 0.21616853881208678
Fold 5 IBS: 0.21227770638433743
[I 2024-04-18 10:06:52,092] Trial 75 finished with value: 0.20755403023595909 and parameters: {'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:07:30,833] Trial 76 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8704877196117842, 'learning_rate': 0.0916936247639216, 'dropout_rate': 0.13042337037884444, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2722270315020332, 'max_features': 'auto', 'min_impurity_decrease': 1.6370541352867706e-06, 'validation_fraction': 0.9218092808039015, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:08:01,015] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7865219593038091, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.25073094184082545, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.2846220433570537, 'min_weight_fraction_leaf': 0.32348748582358233, 'max_features': 1, 'min_impurity_decrease': 2.1196884133822008e-06, 'validation_fraction': 0.854746843935587, 'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 10:08:23,611] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.74450491092411, 'learning_rate': 0.08426314282635561, 'dropout_rate': 0.21845035750510394, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 0.3013998603131079, 'min_weight_fraction_leaf': 0.28488038648314357, 'max_features': 'auto', 'min_impurity_decrease': 4.969807589794284e-06, 'validation_fraction': 0.5953526855291732, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 10:09:02,065] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.07449175092046981, 'dropout_rate': 0.10061598571006734, 'n_estimators': 422, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8368147401670278, 'min_weight_fraction_leaf': 0.3103740193108716, 'max_features': 0.1, 'min_impurity_decrease': 1.5059537626102993e-07, 'validation_fraction': 0.8973370541013407, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-18 10:09:45,060] Trial 80 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8235918523200412, 'learning_rate': 0.04033855340571721, 'dropout_rate': 0.16425961502490374, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 1.694844319118747, 'min_weight_fraction_leaf': 0.2647465108562044, 'max_features': 'log2', 'min_impurity_decrease': 2.9198051926565164e-07, 'validation_fraction': 0.9949359598698552, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21270616661412084
Fold 2 IBS: 0.22114894326985232
Fold 3 IBS: 0.2033654110159561
Fold 4 IBS: 0.2242783032190139
Fold 5 IBS: 0.21754308206787823
[I 2024-04-18 10:10:45,852] Trial 81 finished with value: 0.21580838123736426 and parameters: {'subsample': 0.9683433550626522, 'learning_rate': 0.008693963960519305, 'dropout_rate': 0.1932014858120802, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.2888444623370858, 'max_features': 'auto', 'min_impurity_decrease': 1.789620202740983e-05, 'validation_fraction': 0.938473425448535, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 10:11:39,211] Trial 82 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9762052388738753, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.19741538666007516, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.534138531195614, 'min_weight_fraction_leaf': 0.24700237584705395, 'max_features': 'auto', 'min_impurity_decrease': 7.152609841250385e-06, 'validation_fraction': 0.9388911144407316, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 10:12:38,932] Trial 83 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8945279252278314, 'learning_rate': 0.012088994568921815, 'dropout_rate': 0.154422708294762, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.1988546603429769, 'min_weight_fraction_leaf': 0.2902454191677818, 'max_features': 'auto', 'min_impurity_decrease': 3.133577694489401e-05, 'validation_fraction': 0.8395709442103857, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:13:23,584] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9340088491306221, 'learning_rate': 0.020145328722091006, 'dropout_rate': 0.23069098430626017, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5566102523015541, 'min_weight_fraction_leaf': 0.3043408977845187, 'max_features': 'auto', 'min_impurity_decrease': 5.245144153489441e-06, 'validation_fraction': 0.961947672530741, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:14:13,428] Trial 85 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8559905830599279, 'learning_rate': 0.003151086314395833, 'dropout_rate': 0.12604720621824386, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 1.0429257766218587, 'min_weight_fraction_leaf': 0.13299714491615983, 'max_features': 'auto', 'min_impurity_decrease': 9.411442401014158e-06, 'validation_fraction': 0.9351152476505527, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:14:53,025] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.998032487033103, 'learning_rate': 0.015189890476328648, 'dropout_rate': 0.1929808152262999, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.25850792206277284, 'min_weight_fraction_leaf': 0.19547135211860373, 'max_features': 'sqrt', 'min_impurity_decrease': 7.182497909387456e-07, 'validation_fraction': 0.9008555229787725, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 10:15:21,934] Trial 87 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.586845457594135, 'learning_rate': 0.007791310814930576, 'dropout_rate': 0.2576203464314456, 'n_estimators': 376, 'criterion': 'squared_error', 'ccp_alpha': 0.5970165508324569, 'min_weight_fraction_leaf': 0.3246889883811851, 'max_features': 'auto', 'min_impurity_decrease': 1.2915207513275362e-06, 'validation_fraction': 0.7941466165973634, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 10:15:51,520] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9047974654661481, 'learning_rate': 0.053489441535809173, 'dropout_rate': 0.15111205819257206, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 0.8515398041309932, 'min_weight_fraction_leaf': 0.21790404115359022, 'max_features': 'auto', 'min_impurity_decrease': 2.7145979471070252e-06, 'validation_fraction': 0.8752408074269059, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:16:35,441] Trial 89 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8838515048108662, 'learning_rate': 0.01150450588881658, 'dropout_rate': 0.3106345257277401, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.181177839559219, 'max_features': 'auto', 'min_impurity_decrease': 1.2718861827092477e-05, 'validation_fraction': 0.9760648785366552, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 9}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-18 10:17:33,216] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.960313946457138, 'learning_rate': 0.02326628275454888, 'dropout_rate': 0.2094619744215954, 'n_estimators': 470, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.16213094006522927, 'max_features': None, 'min_impurity_decrease': 8.384298759153104e-07, 'validation_fraction': 0.8362867621481024, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21278867450434957
Fold 2 IBS: 0.22123796611209143
Fold 3 IBS: 0.20385360063526636
Fold 4 IBS: 0.22428500781668678
Fold 5 IBS: 0.2173590980603734
[I 2024-04-18 10:18:25,654] Trial 91 finished with value: 0.21590486942575354 and parameters: {'subsample': 0.974845880068985, 'learning_rate': 0.008764883268716819, 'dropout_rate': 0.18635760945321272, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.2754894562810546, 'max_features': 'auto', 'min_impurity_decrease': 4.2012810231263196e-05, 'validation_fraction': 0.6282967667391103, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:19:18,604] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9396947823626011, 'learning_rate': 0.004368164180849998, 'dropout_rate': 0.1759357421598699, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.25915463409396067, 'min_weight_fraction_leaf': 0.25965914250337996, 'max_features': 'auto', 'min_impurity_decrease': 8.321039301525785e-05, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20443254583780004
Fold 2 IBS: 0.21704992653232766
Fold 3 IBS: 0.20021814328282203
Fold 4 IBS: 0.21936269502578284
Fold 5 IBS: 0.2126381390950113
[I 2024-04-18 10:20:08,262] Trial 93 finished with value: 0.2107402899547488 and parameters: {'subsample': 0.9636218550527925, 'learning_rate': 0.08324257203844727, 'dropout_rate': 0.22319965814002635, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.04690043062719928, 'min_weight_fraction_leaf': 0.23684277621975902, 'max_features': 'auto', 'min_impurity_decrease': 1.548140174949508e-05, 'validation_fraction': 0.7388312145266367, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-18 10:20:57,032] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9216100363199584, 'learning_rate': 0.08937987875028564, 'dropout_rate': 0.2226719596812821, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.5370821041135924, 'min_weight_fraction_leaf': 0.23931318130410523, 'max_features': 'auto', 'min_impurity_decrease': 1.9804047777777935e-05, 'validation_fraction': 0.9344757106941509, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-18 10:21:51,387] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9505720618597318, 'learning_rate': 0.08804335553847131, 'dropout_rate': 0.2858426054482697, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.3311905561863823, 'min_weight_fraction_leaf': 0.1453679981012504, 'max_features': 'auto', 'min_impurity_decrease': 9.665752514196455e-06, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:22:37,508] Trial 96 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9806046119279813, 'learning_rate': 0.08726220388438458, 'dropout_rate': 0.2508258253233333, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.0842424782139257, 'min_weight_fraction_leaf': 0.2509877726726459, 'max_features': 'auto', 'min_impurity_decrease': 4.132954919887874e-06, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-18 10:23:13,371] Trial 97 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9139721535827401, 'learning_rate': 0.0956243686002578, 'dropout_rate': 0.11551248506043046, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.20602145594384874, 'min_weight_fraction_leaf': 0.21288677009944212, 'max_features': 1, 'min_impurity_decrease': 5.099166934714435e-07, 'validation_fraction': 0.6982085459927765, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-18 10:24:04,445] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.881458897433829, 'learning_rate': 0.0818716069302554, 'dropout_rate': 0.1602397729595261, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.7476516282703678, 'min_weight_fraction_leaf': 0.29398452840523387, 'max_features': 'auto', 'min_impurity_decrease': 2.2015056170379928e-06, 'validation_fraction': 0.9116047571236726, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 75 with value: 0.20755403023595909.
Fold 1 IBS: 0.20960061935285024
Fold 2 IBS: 0.21745644638172798

Fold 3 IBS: 0.20030580413616672
Fold 4 IBS: 0.21827950204883104
Fold 5 IBS: 0.2160767264619057
[I 2024-04-18 10:24:43,673] Trial 99 finished with value: 0.21234381967629634 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.07921297533010697, 'dropout_rate': 0.36361374787631456, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.004455045338579978, 'min_weight_fraction_leaf': 0.23447872920034368, 'max_features': 0.1, 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.4378698142708704, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 75 with value: 0.20755403023595909.


* Best trial for IBS:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.20755403023595909], datetime_start=datetime.datetime(2024, 4, 18, 10, 6, 11, 447018), datetime_complete=datetime.datetime(2024, 4, 18, 10, 6, 52, 91691), params={'subsample': 0.8646743646205938, 'learning_rate': 0.08843409287484169, 'dropout_rate': 0.1693875032679634, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.008810810992982535, 'min_weight_fraction_leaf': 0.29044798941528627, 'max_features': 'auto', 'min_impurity_decrease': 5.157320437854681e-06, 'validation_fraction': 0.7489142536117352, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for IBS:
 0.20755403023595909

In [94]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [95]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.208

#### Test

In [96]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [97]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0339977959383996,
                                 criterion='squared_error',
                                 dropout_rate=0.2075412325353082,
                                 learning_rate=0.010706280861824496,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=3.3602815261835675e-07,
                                 min_samples_leaf=13, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4472167339801619,
                                 n_estimators=445, random_state=123,
                                 subsample=0.9030031356045858,
                                 validation_fraction=0.9350158433232643)

C-index score: 0.618

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008810810992982535,
                                 criterion='squared_error',
                                 dropout_rate=0.1693875032679634,
                                 learning_rate=0.08843409287484169,
                                 max_features='auto', max_leaf_nodes=15,
                                 min_impurity_decrease=5.157320437854681e-06,
                                 min_samples_leaf=16, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29044798941528627,
                                 n_estimators=403, random_state=123,
                                 subsample=0.8646743646205938,
                                 validation_fraction=0.7489142536117352)

IBS: 0.213

In [98]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [99]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [100]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Transformation
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            pt = PowerTransformer(method='yeo-johnson')
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = pt.fit_transform(X_train_included)
                X_test_included_std = pt.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-18 10:25:03,330] A new study created in memory with name: no-name-6c6cfb35-8d81-4d3f-bafe-4a4e6d42ce76

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:25:12,048] Trial 0 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6877154599339533.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:25:36,471] Trial 1 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6877154599339533.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:25:46,993] Trial 2 finished with value: 0.6939638235559707 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6939638235559707.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 10:25:59,195] Trial 3 finished with value: 0.7055921984670949 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7055921984670949.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 10:26:13,580] Trial 4 finished with value: 0.7093282815079062 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7093282815079062.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:26:31,414] Trial 5 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7093282815079062.
Fold 1 C-index: 0.5584415584415584
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:26:42,688] Trial 6 finished with value: 0.6877154599339533 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7093282815079062.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:26:48,589] Trial 7 finished with value: 0.7036850744122671 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7093282815079062.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:27:00,992] Trial 8 finished with value: 0.6939638235559707 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7093282815079062.
Fold 1 C-index: 0.5670995670995671
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:27:23,380] Trial 9 finished with value: 0.6923468131154309 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7093282815079062.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 10:27:39,261] Trial 10 finished with value: 0.7084624806421054 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 4 with value: 0.7093282815079062.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:27:56,736] Trial 11 finished with value: 0.74027252284891 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:28:13,234] Trial 12 finished with value: 0.7292528396875533 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.2495649826842376, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:28:32,132] Trial 13 finished with value: 0.6920444642629577 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:28:50,708] Trial 14 finished with value: 0.7328767444351117 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24475605651992097, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:29:09,341] Trial 15 finished with value: 0.7041871365719986 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.6890184489677957, 'n_estimators': 365, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:29:31,178] Trial 16 finished with value: 0.7312402279831203 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.10221023026090809, 'n_estimators': 423, 'learning_rate': 0.08463638125592773}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:29:52,471] Trial 17 finished with value: 0.70940899804386 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 413, 'learning_rate': 0.08749976591807801}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:30:09,883] Trial 18 finished with value: 0.7075628050211964 and parameters: {'subsample': 0.35888747153360906, 'dropout_rate': 0.3446615188677563, 'n_estimators': 324, 'learning_rate': 0.09062397105934869}. Best is trial 11 with value: 0.74027252284891.

Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:30:31,232] Trial 19 finished with value: 0.7258622117301838 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7196046509277619, 'n_estimators': 431, 'learning_rate': 0.08300323114610605}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 10:30:45,617] Trial 20 finished with value: 0.7130448585372656 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 258, 'learning_rate': 0.09795590448114745}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:31:06,967] Trial 21 finished with value: 0.7321791951192704 and parameters: {'subsample': 0.19686631492543752, 'dropout_rate': 0.12395834975058428, 'n_estimators': 410, 'learning_rate': 0.08054438682658777}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:31:26,643] Trial 22 finished with value: 0.7129620084958407 and parameters: {'subsample': 0.18492658093246955, 'dropout_rate': 0.2970189594128161, 'n_estimators': 385, 'learning_rate': 0.07782058471981552}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:31:43,989] Trial 23 finished with value: 0.726610556011899 and parameters: {'subsample': 0.1533378629859366, 'dropout_rate': 0.1712975344247591, 'n_estimators': 325, 'learning_rate': 0.06566568862548955}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 10:32:07,309] Trial 24 finished with value: 0.7093231442401107 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.19012024616538375, 'n_estimators': 454, 'learning_rate': 0.09093035832888614}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:32:25,463] Trial 25 finished with value: 0.7268105488114953 and parameters: {'subsample': 0.21640803376008844, 'dropout_rate': 0.11261425324062513, 'n_estimators': 348, 'learning_rate': 0.07900549020166071}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6060606060606061
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:32:41,118] Trial 26 finished with value: 0.7049873214330546 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.3069768589655776, 'n_estimators': 294, 'learning_rate': 0.09234683154698595}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:33:01,368] Trial 27 finished with value: 0.7246036617048802 and parameters: {'subsample': 0.10030534830333891, 'dropout_rate': 0.9861686560685959, 'n_estimators': 405, 'learning_rate': 0.09858495461750998}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 10:33:14,235] Trial 28 finished with value: 0.7137085330979991 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.419579278974342, 'n_estimators': 229, 'learning_rate': 0.08043089714166637}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:33:24,078] Trial 29 finished with value: 0.6885812607997542 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.5416509825567621, 'n_estimators': 152, 'learning_rate': 0.06046208382653473}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5714285714285714
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:33:31,730] Trial 30 finished with value: 0.6903128625313559 and parameters: {'subsample': 0.6467563583015814, 'dropout_rate': 0.3577780272974884, 'n_estimators': 93, 'learning_rate': 0.04389352929202331}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:33:53,979] Trial 31 finished with value: 0.7285645218475726 and parameters: {'subsample': 0.22283004648527954, 'dropout_rate': 0.1039167246234861, 'n_estimators': 437, 'learning_rate': 0.0836679294661308}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:34:19,493] Trial 32 finished with value: 0.7302742045699137 and parameters: {'subsample': 0.15629937675916628, 'dropout_rate': 0.1646940835318062, 'n_estimators': 491, 'learning_rate': 0.07234238273943856}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:34:40,293] Trial 33 finished with value: 0.722193564373674 and parameters: {'subsample': 0.32649947052337897, 'dropout_rate': 0.10062708073380387, 'n_estimators': 402, 'learning_rate': 0.09003287047973285}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 10:34:58,611] Trial 34 finished with value: 0.7110892114913356 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.22450443007280424, 'n_estimators': 341, 'learning_rate': 0.06745514781297844}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6666666666666666
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:35:13,504] Trial 35 finished with value: 0.7032557197014528 and parameters: {'subsample': 0.4097665565939675, 'dropout_rate': 0.2880189912658185, 'n_estimators': 275, 'learning_rate': 0.07477832671700792}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:35:36,607] Trial 36 finished with value: 0.734820294712157 and parameters: {'subsample': 0.16866851113168313, 'dropout_rate': 0.1424802730801479, 'n_estimators': 451, 'learning_rate': 0.09368950169803325}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:36:00,028] Trial 37 finished with value: 0.7220500971259993 and parameters: {'subsample': 0.13890022905620997, 'dropout_rate': 0.47096246897520044, 'n_estimators': 460, 'learning_rate': 0.0942551407730424}. Best is trial 11 with value: 0.74027252284891.

Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7230046948356808
[I 2024-04-18 10:36:25,255] Trial 38 finished with value: 0.7004924785518998 and parameters: {'subsample': 0.6042961840380411, 'dropout_rate': 0.20387148741818267, 'n_estimators': 495, 'learning_rate': 0.09967365319698797}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:36:45,975] Trial 39 finished with value: 0.7102206863555484 and parameters: {'subsample': 0.2832198393968297, 'dropout_rate': 0.161479375813903, 'n_estimators': 401, 'learning_rate': 0.07166694704505695}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5930735930735931
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:37:10,057] Trial 40 finished with value: 0.6995024026239616 and parameters: {'subsample': 0.4314333091576431, 'dropout_rate': 0.3371254145527177, 'n_estimators': 468, 'learning_rate': 0.05848867655363496}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:37:32,050] Trial 41 finished with value: 0.7231054752327681 and parameters: {'subsample': 0.22930163512496973, 'dropout_rate': 0.13901743213482892, 'n_estimators': 430, 'learning_rate': 0.08419126026396086}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:37:52,159] Trial 42 finished with value: 0.7366740380004252 and parameters: {'subsample': 0.1585457235223686, 'dropout_rate': 0.14395313204316298, 'n_estimators': 384, 'learning_rate': 0.08763054543940382}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:38:13,175] Trial 43 finished with value: 0.7273744531200379 and parameters: {'subsample': 0.13875280823850272, 'dropout_rate': 0.20270103475711534, 'n_estimators': 384, 'learning_rate': 0.09246192134625801}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5497835497835498
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:38:17,706] Trial 44 finished with value: 0.695787779770979 and parameters: {'subsample': 0.17372241042405595, 'dropout_rate': 0.25934905096676963, 'n_estimators': 3, 'learning_rate': 0.07774114437177704}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:38:36,284] Trial 45 finished with value: 0.7239204811326951 and parameters: {'subsample': 0.12817138848149867, 'dropout_rate': 0.14027461130388127, 'n_estimators': 349, 'learning_rate': 0.02274904980797578}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:38:56,381] Trial 46 finished with value: 0.707764931326264 and parameters: {'subsample': 0.2535526058642174, 'dropout_rate': 0.596914051521217, 'n_estimators': 384, 'learning_rate': 0.08771698865357266}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:39:12,019] Trial 47 finished with value: 0.6930248564198205 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.26670221529345367, 'n_estimators': 285, 'learning_rate': 0.09497031925563747}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.5974025974025974
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:39:28,741] Trial 48 finished with value: 0.7020973922235549 and parameters: {'subsample': 0.3213924173083146, 'dropout_rate': 0.7966946340284661, 'n_estimators': 319, 'learning_rate': 0.08818174610683813}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:39:42,002] Trial 49 finished with value: 0.708608813182804 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.21753125771684506, 'n_estimators': 233, 'learning_rate': 0.00524351186486742}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:40:05,215] Trial 50 finished with value: 0.7364672267227773 and parameters: {'subsample': 0.1195222920464375, 'dropout_rate': 0.14501343490387253, 'n_estimators': 442, 'learning_rate': 0.09495309279125025}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:40:28,716] Trial 51 finished with value: 0.7394545131866586 and parameters: {'subsample': 0.10412054178332336, 'dropout_rate': 0.14319123802705364, 'n_estimators': 453, 'learning_rate': 0.09570993541362999}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:40:51,663] Trial 52 finished with value: 0.739330238124521 and parameters: {'subsample': 0.12518001647201818, 'dropout_rate': 0.15198746197466087, 'n_estimators': 445, 'learning_rate': 0.09499767732995089}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:41:15,449] Trial 53 finished with value: 0.7376544301572879 and parameters: {'subsample': 0.14579520301489285, 'dropout_rate': 0.1512120274026351, 'n_estimators': 449, 'learning_rate': 0.09477772623342627}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:41:40,045] Trial 54 finished with value: 0.7339107968508721 and parameters: {'subsample': 0.13263436964529463, 'dropout_rate': 0.18132684271574157, 'n_estimators': 477, 'learning_rate': 0.09585557106383087}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:42:02,580] Trial 55 finished with value: 0.7347817349844685 and parameters: {'subsample': 0.1091431272324415, 'dropout_rate': 0.1480216697300459, 'n_estimators': 450, 'learning_rate': 0.08768199392159111}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6147186147186147
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:42:23,995] Trial 56 finished with value: 0.7048946491512535 and parameters: {'subsample': 0.5378936898695973, 'dropout_rate': 0.229576258214932, 'n_estimators': 436, 'learning_rate': 0.0960389378863785}. Best is trial 11 with value: 0.74027252284891.

Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:42:47,783] Trial 57 finished with value: 0.736742519298194 and parameters: {'subsample': 0.1017129358296931, 'dropout_rate': 0.18800515155988587, 'n_estimators': 478, 'learning_rate': 0.08310045169235102}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:43:11,398] Trial 58 finished with value: 0.7200403375259568 and parameters: {'subsample': 0.15127851902524647, 'dropout_rate': 0.39285929686820636, 'n_estimators': 477, 'learning_rate': 0.0824144601088472}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7183098591549296
[I 2024-04-18 10:43:35,642] Trial 59 finished with value: 0.7076185987855652 and parameters: {'subsample': 0.2487406612923978, 'dropout_rate': 0.18773639549935606, 'n_estimators': 493, 'learning_rate': 0.041272609377688785}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:43:56,699] Trial 60 finished with value: 0.712076701618588 and parameters: {'subsample': 0.20412839583245423, 'dropout_rate': 0.3160261737141424, 'n_estimators': 421, 'learning_rate': 0.07587050984668854}. Best is trial 11 with value: 0.74027252284891.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:44:18,858] Trial 61 finished with value: 0.7412592811886096 and parameters: {'subsample': 0.1069505756417581, 'dropout_rate': 0.13083186529301188, 'n_estimators': 448, 'learning_rate': 0.09076095455157462}. Best is trial 61 with value: 0.7412592811886096.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:44:43,958] Trial 62 finished with value: 0.7409557034210952 and parameters: {'subsample': 0.16500864355809508, 'dropout_rate': 0.1003922615851948, 'n_estimators': 471, 'learning_rate': 0.09046844896904234}. Best is trial 61 with value: 0.7412592811886096.
Fold 1 C-index: 0.6536796536796536
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7699530516431925
[I 2024-04-18 10:45:09,574] Trial 63 finished with value: 0.7455917415751532 and parameters: {'subsample': 0.1072481243021174, 'dropout_rate': 0.10443578020986953, 'n_estimators': 500, 'learning_rate': 0.09196255088220771}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:45:33,005] Trial 64 finished with value: 0.7373727713990343 and parameters: {'subsample': 0.17922063579321743, 'dropout_rate': 0.10071633619778064, 'n_estimators': 470, 'learning_rate': 0.08990953274481464}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:45:55,864] Trial 65 finished with value: 0.7221665080966179 and parameters: {'subsample': 0.2832849224218006, 'dropout_rate': 0.13189560662833089, 'n_estimators': 458, 'learning_rate': 0.09131160154561961}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:46:20,562] Trial 66 finished with value: 0.7347276224303559 and parameters: {'subsample': 0.1365493476768176, 'dropout_rate': 0.17389693853840835, 'n_estimators': 498, 'learning_rate': 0.09955154926819447}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:46:44,898] Trial 67 finished with value: 0.7285202315338363 and parameters: {'subsample': 0.2187994851655431, 'dropout_rate': 0.12095016488941163, 'n_estimators': 482, 'learning_rate': 0.08570877414060708}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:47:07,996] Trial 68 finished with value: 0.7345525524023448 and parameters: {'subsample': 0.1028231387437121, 'dropout_rate': 0.24679199535995944, 'n_estimators': 423, 'learning_rate': 0.09175205986212062}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:47:20,046] Trial 69 finished with value: 0.7164574055038959 and parameters: {'subsample': 0.20155354321198304, 'dropout_rate': 0.28002836414714494, 'n_estimators': 165, 'learning_rate': 0.09765328187897142}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.5800865800865801
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:52:57,776] Trial 70 finished with value: 0.6920444642629577 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.21112935486850254, 'n_estimators': 366, 'learning_rate': 0.08058873331917904}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:53:18,543] Trial 71 finished with value: 0.7329769669825176 and parameters: {'subsample': 0.17391916951125236, 'dropout_rate': 0.11895634691103422, 'n_estimators': 469, 'learning_rate': 0.08964837214878224}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:53:37,398] Trial 72 finished with value: 0.7365432582861505 and parameters: {'subsample': 0.15710340956530955, 'dropout_rate': 0.1084427420065921, 'n_estimators': 445, 'learning_rate': 0.09258211467739061}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7544642857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:53:57,027] Trial 73 finished with value: 0.725661905104673 and parameters: {'subsample': 0.18597033136891927, 'dropout_rate': 0.16739104766903698, 'n_estimators': 462, 'learning_rate': 0.09689643443354096}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 10:54:15,603] Trial 74 finished with value: 0.7385155460505082 and parameters: {'subsample': 0.1261181183298701, 'dropout_rate': 0.13002948309394788, 'n_estimators': 413, 'learning_rate': 0.0859682422631983}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 10:54:34,156] Trial 75 finished with value: 0.7374523038522205 and parameters: {'subsample': 0.12535440888497598, 'dropout_rate': 0.15722589038441054, 'n_estimators': 407, 'learning_rate': 0.08612952350657353}. Best is trial 63 with value: 0.7455917415751532.

Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:54:53,813] Trial 76 finished with value: 0.7384741210297958 and parameters: {'subsample': 0.14261957909148354, 'dropout_rate': 0.1255293082176492, 'n_estimators': 420, 'learning_rate': 0.09404919893163159}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 10:55:13,250] Trial 77 finished with value: 0.7386204535704946 and parameters: {'subsample': 0.1001656230620945, 'dropout_rate': 0.12811194509255286, 'n_estimators': 417, 'learning_rate': 0.052806425976407945}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:55:31,471] Trial 78 finished with value: 0.7310258664398676 and parameters: {'subsample': 0.10230071936873004, 'dropout_rate': 0.23241625832791513, 'n_estimators': 391, 'learning_rate': 0.033948438490277316}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6708860759493671
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:55:51,823] Trial 79 finished with value: 0.707764931326264 and parameters: {'subsample': 0.23647324316869311, 'dropout_rate': 0.1818645107345581, 'n_estimators': 435, 'learning_rate': 0.021847064249626545}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 10:56:14,941] Trial 80 finished with value: 0.7109061389025051 and parameters: {'subsample': 0.20331785930342053, 'dropout_rate': 0.20224768507059213, 'n_estimators': 485, 'learning_rate': 0.0651694931268971}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:56:34,730] Trial 81 finished with value: 0.7337742865505495 and parameters: {'subsample': 0.1214742541651591, 'dropout_rate': 0.12489065917780094, 'n_estimators': 419, 'learning_rate': 0.05191285063438977}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:56:53,547] Trial 82 finished with value: 0.736452857979121 and parameters: {'subsample': 0.15547027454738033, 'dropout_rate': 0.10233252573928056, 'n_estimators': 395, 'learning_rate': 0.08964367587010329}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 10:57:10,091] Trial 83 finished with value: 0.7376083201639949 and parameters: {'subsample': 0.12829175664866302, 'dropout_rate': 0.1239954231634918, 'n_estimators': 337, 'learning_rate': 0.08136047667579}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6877637130801688
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:57:28,004] Trial 84 finished with value: 0.7285645218475726 and parameters: {'subsample': 0.16652243501977665, 'dropout_rate': 0.17034887620834985, 'n_estimators': 372, 'learning_rate': 0.08506417496391756}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:57:47,729] Trial 85 finished with value: 0.7291716708563846 and parameters: {'subsample': 0.14059467539968235, 'dropout_rate': 0.1389201795089357, 'n_estimators': 411, 'learning_rate': 0.05534589688617711}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7746478873239436
[I 2024-04-18 10:58:11,785] Trial 86 finished with value: 0.7403567402746767 and parameters: {'subsample': 0.11918286874044434, 'dropout_rate': 0.15985613695152145, 'n_estimators': 500, 'learning_rate': 0.09308650741107229}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7464788732394366
[I 2024-04-18 10:58:33,863] Trial 87 finished with value: 0.7337425453009125 and parameters: {'subsample': 0.11793990724000518, 'dropout_rate': 0.20522811576700428, 'n_estimators': 461, 'learning_rate': 0.07823986277139501}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 10:58:58,655] Trial 88 finished with value: 0.7284964928450188 and parameters: {'subsample': 0.10170132596189528, 'dropout_rate': 0.16284320673980263, 'n_estimators': 500, 'learning_rate': 0.018867705687932175}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6190476190476191
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.679324894514768
Fold 5 C-index: 0.7370892018779343
[I 2024-04-18 10:59:21,786] Trial 89 finished with value: 0.7139550881861034 and parameters: {'subsample': 0.17529239525508505, 'dropout_rate': 0.6436774805198799, 'n_estimators': 487, 'learning_rate': 0.07072198193973936}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.5627705627705628
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.6624472573839663
Fold 5 C-index: 0.7323943661971831
[I 2024-04-18 10:59:42,476] Trial 90 finished with value: 0.6885812607997542 and parameters: {'subsample': 0.7147405584008215, 'dropout_rate': 0.7914853260144449, 'n_estimators': 444, 'learning_rate': 0.09970974361519451}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 11:00:03,697] Trial 91 finished with value: 0.7385426023275645 and parameters: {'subsample': 0.14590879906030116, 'dropout_rate': 0.11995097308360905, 'n_estimators': 435, 'learning_rate': 0.09308366766788696}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-18 11:00:25,298] Trial 92 finished with value: 0.7447212557367717 and parameters: {'subsample': 0.12513506509875122, 'dropout_rate': 0.1012333218101087, 'n_estimators': 433, 'learning_rate': 0.09311771923393634}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.6751054852320675
Fold 5 C-index: 0.7417840375586855
[I 2024-04-18 11:00:46,332] Trial 93 finished with value: 0.7177425595110407 and parameters: {'subsample': 0.4627070216098863, 'dropout_rate': 0.10145815801401736, 'n_estimators': 430, 'learning_rate': 0.092485631091883}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.6835443037974683
Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 11:01:08,774] Trial 94 finished with value: 0.7145109899338267 and parameters: {'subsample': 0.1979961223009301, 'dropout_rate': 0.15684926838177587, 'n_estimators': 455, 'learning_rate': 0.04699166614840757}. Best is trial 63 with value: 0.7455917415751532.

Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.6919831223628692
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 11:01:31,397] Trial 95 finished with value: 0.7321935638629267 and parameters: {'subsample': 0.1601675067691602, 'dropout_rate': 0.18989674215619215, 'n_estimators': 467, 'learning_rate': 0.09681105702146361}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.7511737089201878
[I 2024-04-18 11:01:42,889] Trial 96 finished with value: 0.7358910871760495 and parameters: {'subsample': 0.14523604984057606, 'dropout_rate': 0.14724929099505382, 'n_estimators': 200, 'learning_rate': 0.08915498355311331}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.645021645021645
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.70042194092827
Fold 5 C-index: 0.7652582159624414
[I 2024-04-18 11:02:06,865] Trial 97 finished with value: 0.7430087077214069 and parameters: {'subsample': 0.11705143712370233, 'dropout_rate': 0.12107721368829978, 'n_estimators': 485, 'learning_rate': 0.09781587660071193}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6493506493506493
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.6962025316455697
Fold 5 C-index: 0.755868544600939
[I 2024-04-18 11:02:30,453] Trial 98 finished with value: 0.7356204795732131 and parameters: {'subsample': 0.12068537757409042, 'dropout_rate': 0.22847044703488156, 'n_estimators': 485, 'learning_rate': 0.09778702192951401}. Best is trial 63 with value: 0.7455917415751532.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.6624472573839663

[I 2024-04-18 11:02:54,942] A new study created in memory with name: no-name-1077398a-6212-45cc-9db5-eccf5e492243

Fold 5 C-index: 0.7276995305164319
[I 2024-04-18 11:02:54,933] Trial 99 finished with value: 0.7112990290850453 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.10045678423512755, 'n_estimators': 500, 'learning_rate': 0.09499424344252129}. Best is trial 63 with value: 0.7455917415751532.


* Best trial for C-index:
 FrozenTrial(number=63, state=TrialState.COMPLETE, values=[0.7455917415751532], datetime_start=datetime.datetime(2024, 4, 18, 10, 44, 43, 984492), datetime_complete=datetime.datetime(2024, 4, 18, 10, 45, 9, 574428), params={'subsample': 0.1072481243021174, 'dropout_rate': 0.10443578020986953, 'n_estimators': 500, 'learning_rate': 0.09196255088220771}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=63, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.1072481243021174, 'dropout_rate': 0.10443578020986953, 'n_estimators': 500, 'learning_rate': 0.09196255088220771}


* Best Score for C-index:
 0.7455917415751532

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2390629032911732
Fold 2 IBS: 0.21956170919192733
Fold 3 IBS: 0.20377285998622766
Fold 4 IBS: 0.26017942758755347
Fold 5 IBS: 0.2006754645153689
[I 2024-04-18 11:03:02,859] Trial 0 finished with value: 0.22465047291445012 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.3010964947715816
Fold 2 IBS: 0.32141602234375205
Fold 3 IBS: 0.3044709495587033
Fold 4 IBS: 0.30221309295028626
Fold 5 IBS: 0.2978808784319514
[I 2024-04-18 11:03:26,474] Trial 1 finished with value: 0.30541548761125487 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.25281739657888197
Fold 2 IBS: 0.28450082966659795
Fold 3 IBS: 0.23729933366856826
Fold 4 IBS: 0.2841935183364194
Fold 5 IBS: 0.2542997941517634
[I 2024-04-18 11:03:36,772] Trial 2 finished with value: 0.26262217448044617 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.23285875309846318
Fold 2 IBS: 0.2846959940051828
Fold 3 IBS: 0.24083990662543817
Fold 4 IBS: 0.28260084573855476
Fold 5 IBS: 0.25399181415103933
[I 2024-04-18 11:03:47,978] Trial 3 finished with value: 0.25899746272373564 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.23219828433696713
Fold 2 IBS: 0.28623495025274276
Fold 3 IBS: 0.2390977176738092
Fold 4 IBS: 0.27525634323606585
Fold 5 IBS: 0.2540218496927178
[I 2024-04-18 11:04:02,211] Trial 4 finished with value: 0.25736182903846055 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.2829269097551455
Fold 2 IBS: 0.31641454579276374
Fold 3 IBS: 0.28631221226205067
Fold 4 IBS: 0.2833121260031273
Fold 5 IBS: 0.2868040704444742
[I 2024-04-18 11:04:19,848] Trial 5 finished with value: 0.29115397285151234 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22465047291445012.
Fold 1 IBS: 0.22927167337558443
Fold 2 IBS: 0.1949307831638688
Fold 3 IBS: 0.1896534296397517
Fold 4 IBS: 0.238032022543999
Fold 5 IBS: 0.1884627677032548
[I 2024-04-18 11:04:30,293] Trial 6 finished with value: 0.20807013528529175 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.20807013528529175.
Fold 1 IBS: 0.19917207033538115
Fold 2 IBS: 0.18619054231616225
Fold 3 IBS: 0.18156673272749727
Fold 4 IBS: 0.21111695163998417
Fold 5 IBS: 0.1910664145750693
[I 2024-04-18 11:04:35,975] Trial 7 finished with value: 0.19382254231881882 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.2338249443889534
Fold 2 IBS: 0.2278866200430072
Fold 3 IBS: 0.20917477066881857
Fold 4 IBS: 0.26549673049645445
Fold 5 IBS: 0.20383546662758117
[I 2024-04-18 11:04:47,690] Trial 8 finished with value: 0.22804370644496297 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.2864326153342967
Fold 2 IBS: 0.3180120028377849
Fold 3 IBS: 0.2834147511480796
Fold 4 IBS: 0.28577599689770306
Fold 5 IBS: 0.2895633339017517
[I 2024-04-18 11:05:09,729] Trial 9 finished with value: 0.29263974002392323 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.2136348878836343
Fold 2 IBS: 0.22044150933225762
Fold 3 IBS: 0.20365345601250012
Fold 4 IBS: 0.22380783373623472
Fold 5 IBS: 0.21719294266426903
[I 2024-04-18 11:05:14,525] Trial 10 finished with value: 0.2157461259257792 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.2136761855347193
Fold 2 IBS: 0.22003714542377867
Fold 3 IBS: 0.20383322063064133
Fold 4 IBS: 0.22362308945768902
Fold 5 IBS: 0.21699330092763
[I 2024-04-18 11:05:18,727] Trial 11 finished with value: 0.21563258839489166 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.2267028133007011
Fold 2 IBS: 0.26408648304556276
Fold 3 IBS: 0.22553049862899618
Fold 4 IBS: 0.2779362184309732
Fold 5 IBS: 0.23240061991771427
[I 2024-04-18 11:05:26,564] Trial 12 finished with value: 0.2453313266647895 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.2529948298742377
Fold 2 IBS: 0.25996216627225793
Fold 3 IBS: 0.2262950834675201
Fold 4 IBS: 0.2802094450909461
Fold 5 IBS: 0.23293073779715276
[I 2024-04-18 11:05:41,757] Trial 13 finished with value: 0.25047845250042294 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.20922656916850566
Fold 2 IBS: 0.19345959218725786
Fold 3 IBS: 0.18606942412604216
Fold 4 IBS: 0.20876086066030902
Fold 5 IBS: 0.1957513308119005
[I 2024-04-18 11:05:48,984] Trial 14 finished with value: 0.19865355539080304 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.21059901048825336
Fold 2 IBS: 0.21387516914377427
Fold 3 IBS: 0.1988511004470261
Fold 4 IBS: 0.218989045225747
Fold 5 IBS: 0.21240037967197867
[I 2024-04-18 11:05:55,623] Trial 15 finished with value: 0.21094294099535588 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.20937813343837747
Fold 2 IBS: 0.20315511269787834
Fold 3 IBS: 0.19176436373007055
Fold 4 IBS: 0.2120006661308366
Fold 5 IBS: 0.2030730351658097
[I 2024-04-18 11:06:01,868] Trial 16 finished with value: 0.20387426223259456 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.23556129987958843
Fold 2 IBS: 0.20350612721326378
Fold 3 IBS: 0.19535944344133163
Fold 4 IBS: 0.24667676323830406
Fold 5 IBS: 0.19227886034547353
[I 2024-04-18 11:06:10,585] Trial 17 finished with value: 0.21467649882359224 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.2232885198139631
Fold 2 IBS: 0.20638926067732927
Fold 3 IBS: 0.19514081036061184
Fold 4 IBS: 0.25179170367334425
Fold 5 IBS: 0.1919247314166744
[I 2024-04-18 11:06:26,904] Trial 18 finished with value: 0.21370700518838456 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19382254231881882.
Fold 1 IBS: 0.20136847650127382

Fold 2 IBS: 0.18223515335825835
Fold 3 IBS: 0.1777423595055709
Fold 4 IBS: 0.2018999578285449
Fold 5 IBS: 0.1911082943649028
[I 2024-04-18 11:06:32,632] Trial 19 finished with value: 0.19087084831171014 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.19955188174503216
Fold 2 IBS: 0.1855544040643127
Fold 3 IBS: 0.17923234678472577
Fold 4 IBS: 0.20455539282706595
Fold 5 IBS: 0.19466473879647364
[I 2024-04-18 11:06:38,189] Trial 20 finished with value: 0.19271175284352204 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.20256510757658133
Fold 2 IBS: 0.19154224065115247
Fold 3 IBS: 0.18335986646954017
Fold 4 IBS: 0.20458588921838688
Fold 5 IBS: 0.1974805846771631
[I 2024-04-18 11:06:43,382] Trial 21 finished with value: 0.1959067377185648 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.21338552058692323
Fold 2 IBS: 0.21933399873094075
Fold 3 IBS: 0.20322285782084254
Fold 4 IBS: 0.22243914910086565
Fold 5 IBS: 0.2163886938377446
[I 2024-04-18 11:06:47,511] Trial 22 finished with value: 0.21495404401546336 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.20502088050921766
Fold 2 IBS: 0.2099037290953182
Fold 3 IBS: 0.19161811828372377
Fold 4 IBS: 0.2436722878048712
Fold 5 IBS: 0.19350388684163913
[I 2024-04-18 11:06:56,627] Trial 23 finished with value: 0.208743780506954 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.2071739912913989
Fold 2 IBS: 0.18832650306524928
Fold 3 IBS: 0.18347912741823666
Fold 4 IBS: 0.22733180863751976
Fold 5 IBS: 0.18734146785074768
[I 2024-04-18 11:07:02,700] Trial 24 finished with value: 0.19873057965263047 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.20204352314555216
Fold 2 IBS: 0.18606499023663162
Fold 3 IBS: 0.18111390925252036
Fold 4 IBS: 0.22200292410300038
Fold 5 IBS: 0.18790335255276575
[I 2024-04-18 11:07:09,736] Trial 25 finished with value: 0.19582573985809404 and parameters: {'subsample': 0.211474360454084, 'dropout_rate': 0.7565916135854155, 'n_estimators': 79, 'learning_rate': 0.04499564959136668}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.22914930947022683
Fold 2 IBS: 0.250788896381645
Fold 3 IBS: 0.23358939736102236
Fold 4 IBS: 0.2376743495342024
Fold 5 IBS: 0.2416802675650835
[I 2024-04-18 11:07:18,900] Trial 26 finished with value: 0.238576444062436 and parameters: {'subsample': 0.1041009856261342, 'dropout_rate': 0.9247094001740422, 'n_estimators': 150, 'learning_rate': 0.08556459741601653}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.22985617664517805
Fold 2 IBS: 0.24316801321520648
Fold 3 IBS: 0.21428767652763048
Fold 4 IBS: 0.27181565497429794
Fold 5 IBS: 0.21395348316547605
[I 2024-04-18 11:07:31,584] Trial 27 finished with value: 0.23461620090555782 and parameters: {'subsample': 0.26997549644935737, 'dropout_rate': 0.8368873118701377, 'n_estimators': 239, 'learning_rate': 0.03445164499250722}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.20467679817038256
Fold 2 IBS: 0.19711969586127606
Fold 3 IBS: 0.1875977831281758
Fold 4 IBS: 0.20962727178346416
Fold 5 IBS: 0.20251332023754076
[I 2024-04-18 11:07:37,174] Trial 28 finished with value: 0.20030697383616786 and parameters: {'subsample': 0.17869442508126104, 'dropout_rate': 0.5247590554772287, 'n_estimators': 42, 'learning_rate': 0.02423020317951243}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.22673353498270413
Fold 2 IBS: 0.23444301564254197
Fold 3 IBS: 0.21046691971779072
Fold 4 IBS: 0.2692285297542766
Fold 5 IBS: 0.20461018520205707
[I 2024-04-18 11:07:45,393] Trial 29 finished with value: 0.2290964370598741 and parameters: {'subsample': 0.40393394585149023, 'dropout_rate': 0.6674788347320111, 'n_estimators': 119, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.21218028602053185
Fold 2 IBS: 0.19431875060961784
Fold 3 IBS: 0.18609009076041863
Fold 4 IBS: 0.23288039614352557
Fold 5 IBS: 0.18878491010838364
[I 2024-04-18 11:07:52,664] Trial 30 finished with value: 0.2028508867284955 and parameters: {'subsample': 0.23664966998873388, 'dropout_rate': 0.9929371631271855, 'n_estimators': 94, 'learning_rate': 0.04801989891112703}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.20469622267906898
Fold 2 IBS: 0.1865903612284499
Fold 3 IBS: 0.17977058453902323
Fold 4 IBS: 0.21297221921159237
Fold 5 IBS: 0.18708658466447897
[I 2024-04-18 11:07:59,413] Trial 31 finished with value: 0.19422319446452269 and parameters: {'subsample': 0.17014389019645443, 'dropout_rate': 0.7487379608250186, 'n_estimators': 78, 'learning_rate': 0.049622187213913455}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.19997293798387525
Fold 2 IBS: 0.183910476781053
Fold 3 IBS: 0.17930545223250852
Fold 4 IBS: 0.20623591415698322
Fold 5 IBS: 0.19430063112731605
[I 2024-04-18 11:08:04,907] Trial 32 finished with value: 0.1927450824563472 and parameters: {'subsample': 0.15302721151223558, 'dropout_rate': 0.706204123606961, 'n_estimators': 35, 'learning_rate': 0.05596064724876046}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.20265591093470908
Fold 2 IBS: 0.19146356970362086
Fold 3 IBS: 0.18360475419941485
Fold 4 IBS: 0.20866983075557297
Fold 5 IBS: 0.19477696676626008
[I 2024-04-18 11:08:09,980] Trial 33 finished with value: 0.19623420647191556 and parameters: {'subsample': 0.3151893066667032, 'dropout_rate': 0.6875993832530338, 'n_estimators': 22, 'learning_rate': 0.06694265963579746}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.2644280967044245
Fold 2 IBS: 0.29121839447360237
Fold 3 IBS: 0.25501964353693113
Fold 4 IBS: 0.25369822444707335
Fold 5 IBS: 0.27483574078868434
[I 2024-04-18 11:08:30,897] Trial 34 finished with value: 0.2678400199901431 and parameters: {'subsample': 0.10316532108046203, 'dropout_rate': 0.5839581779687532, 'n_estimators': 433, 'learning_rate': 0.056208283387430134}. Best is trial 19 with value: 0.19087084831171014.
Fold 1 IBS: 0.19924729004681302
Fold 2 IBS: 0.17760734741778955
Fold 3 IBS: 0.17736638184117043
Fold 4 IBS: 0.2071713946792497
Fold 5 IBS: 0.18831842131085544
[I 2024-04-18 11:08:36,706] Trial 35 finished with value: 0.18994216705917563 and parameters: {'subsample': 0.16380438916747353, 'dropout_rate': 0.4731294957318265, 'n_estimators': 50, 'learning_rate': 0.07576486700752832}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.21700579179611773
Fold 2 IBS: 0.2622550361470025
Fold 3 IBS: 0.22900512900396416
Fold 4 IBS: 0.2768555875921138
Fold 5 IBS: 0.23711458034421806
[I 2024-04-18 11:08:45,672] Trial 36 finished with value: 0.24444722497668323 and parameters: {'subsample': 0.2668633426908267, 'dropout_rate': 0.3110312087749114, 'n_estimators': 139, 'learning_rate': 0.08190208605336496}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.2254588805040427
Fold 2 IBS: 0.2585147552914051
Fold 3 IBS: 0.23407028734447088
Fold 4 IBS: 0.260314853687896
Fold 5 IBS: 0.24673404130374077
[I 2024-04-18 11:08:55,893] Trial 37 finished with value: 0.24501856362631108 and parameters: {'subsample': 0.15139277364793602, 'dropout_rate': 0.47096246897520044, 'n_estimators': 170, 'learning_rate': 0.07673633674538209}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.2134236080358275

Fold 2 IBS: 0.21852631898868966
Fold 3 IBS: 0.2030153396872452
Fold 4 IBS: 0.22215040490755078
Fold 5 IBS: 0.21594262691145144
[I 2024-04-18 11:09:00,021] Trial 38 finished with value: 0.21461165970615292 and parameters: {'subsample': 0.23557094034920928, 'dropout_rate': 0.13272164755980653, 'n_estimators': 1, 'learning_rate': 0.0947653216013069}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.2062176081503947
Fold 2 IBS: 0.2037315366365509
Fold 3 IBS: 0.1923016777876445
Fold 4 IBS: 0.2412731246694159
Fold 5 IBS: 0.2033237070159203
[I 2024-04-18 11:09:08,311] Trial 39 finished with value: 0.20936953085198526 and parameters: {'subsample': 0.167666800643059, 'dropout_rate': 0.19868896123028712, 'n_estimators': 111, 'learning_rate': 0.06892741183938003}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.20440240507823856
Fold 2 IBS: 0.1849206764977604
Fold 3 IBS: 0.18225096974199848
Fold 4 IBS: 0.21621756942600678
Fold 5 IBS: 0.18862470755011918
[I 2024-04-18 11:09:13,957] Trial 40 finished with value: 0.19528326565882467 and parameters: {'subsample': 0.45126466504604507, 'dropout_rate': 0.5181363617049309, 'n_estimators': 48, 'learning_rate': 0.05602861659169126}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.20751609698724024
Fold 2 IBS: 0.18492115930656564
Fold 3 IBS: 0.18282117353438102
Fold 4 IBS: 0.21461717196126773
Fold 5 IBS: 0.18772784991267827
[I 2024-04-18 11:09:19,578] Trial 41 finished with value: 0.19552069034042657 and parameters: {'subsample': 0.5668271284927056, 'dropout_rate': 0.8201683839413054, 'n_estimators': 46, 'learning_rate': 0.0541725202595718}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.2051575267489001
Fold 2 IBS: 0.20542741674284506
Fold 3 IBS: 0.19207839251996406
Fold 4 IBS: 0.2115021576285373
Fold 5 IBS: 0.20406089715607587
[I 2024-04-18 11:09:24,364] Trial 42 finished with value: 0.20364527815926445 and parameters: {'subsample': 0.28071781207488156, 'dropout_rate': 0.40395946540885663, 'n_estimators': 20, 'learning_rate': 0.03690022084530886}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.1983393350275861
Fold 2 IBS: 0.1835453861899676
Fold 3 IBS: 0.17668882676742032
Fold 4 IBS: 0.20221395422761157
Fold 5 IBS: 0.19152696146723297
[I 2024-04-18 11:09:31,048] Trial 43 finished with value: 0.19046289273596373 and parameters: {'subsample': 0.1360248537753182, 'dropout_rate': 0.5614281957092329, 'n_estimators': 77, 'learning_rate': 0.027633234880330062}. Best is trial 35 with value: 0.18994216705917563.
Fold 1 IBS: 0.19496535484020086
Fold 2 IBS: 0.1799650259639504
Fold 3 IBS: 0.17707036421976027
Fold 4 IBS: 0.20091740837990155
Fold 5 IBS: 0.1916804258473456
[I 2024-04-18 11:09:38,026] Trial 44 finished with value: 0.18891971585023173 and parameters: {'subsample': 0.1307489777457696, 'dropout_rate': 0.4314562995710115, 'n_estimators': 80, 'learning_rate': 0.030518016997702}. Best is trial 44 with value: 0.18891971585023173.
Fold 1 IBS: 0.20276594776870013
Fold 2 IBS: 0.1975086612852043
Fold 3 IBS: 0.1834354267295091
Fold 4 IBS: 0.2265131745258451
Fold 5 IBS: 0.19278270573946746
[I 2024-04-18 11:09:49,251] Trial 45 finished with value: 0.20060118320974524 and parameters: {'subsample': 0.13086989483817016, 'dropout_rate': 0.3273013830702176, 'n_estimators': 198, 'learning_rate': 0.028323225750515407}. Best is trial 44 with value: 0.18891971585023173.
Fold 1 IBS: 0.20242099428802127
Fold 2 IBS: 0.18458543733087165
Fold 3 IBS: 0.1798383236833166
Fold 4 IBS: 0.20662148245980091
Fold 5 IBS: 0.19049267464502334
[I 2024-04-18 11:09:56,560] Trial 46 finished with value: 0.19279178248140677 and parameters: {'subsample': 0.23491982703558362, 'dropout_rate': 0.45072557421911436, 'n_estimators': 91, 'learning_rate': 0.023555827866012437}. Best is trial 44 with value: 0.18891971585023173.
Fold 1 IBS: 0.19779548256469096
Fold 2 IBS: 0.17611657812782003
Fold 3 IBS: 0.1712761961657115
Fold 4 IBS: 0.1962232952474419
Fold 5 IBS: 0.1890365998898883
[I 2024-04-18 11:10:06,763] Trial 47 finished with value: 0.18608963039911053 and parameters: {'subsample': 0.10113996760134518, 'dropout_rate': 0.42199222898101846, 'n_estimators': 159, 'learning_rate': 0.019183162288683518}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.1970190314067467
Fold 2 IBS: 0.17599584273046698
Fold 3 IBS: 0.1728073732066164
Fold 4 IBS: 0.20297775418252487
Fold 5 IBS: 0.18864196344147224
[I 2024-04-18 11:10:16,550] Trial 48 finished with value: 0.18748839299356543 and parameters: {'subsample': 0.10137040754191243, 'dropout_rate': 0.2406143543227986, 'n_estimators': 160, 'learning_rate': 0.018199888637109668}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.2023301683411933
Fold 2 IBS: 0.19366527769865272
Fold 3 IBS: 0.18388626566044894
Fold 4 IBS: 0.20736113292539227
Fold 5 IBS: 0.1989335072711691
[I 2024-04-18 11:10:26,993] Trial 49 finished with value: 0.19723527037937127 and parameters: {'subsample': 0.19014179792732033, 'dropout_rate': 0.24517203177528327, 'n_estimators': 171, 'learning_rate': 0.007658391862761979}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.21068843057807574
Fold 2 IBS: 0.19373211112173222
Fold 3 IBS: 0.18344455184930875
Fold 4 IBS: 0.2366638713137283
Fold 5 IBS: 0.1877575170088888
[I 2024-04-18 11:10:39,442] Trial 50 finished with value: 0.20245729637434678 and parameters: {'subsample': 0.32599134955844494, 'dropout_rate': 0.4326780653706334, 'n_estimators': 229, 'learning_rate': 0.018143608603204728}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.20037848698877506
Fold 2 IBS: 0.1778568143986169
Fold 3 IBS: 0.17047387218490861
Fold 4 IBS: 0.20268000969266567
Fold 5 IBS: 0.1873475537625904
[I 2024-04-18 11:10:50,425] Trial 51 finished with value: 0.1877473474055113 and parameters: {'subsample': 0.10361300378126209, 'dropout_rate': 0.34925879147940603, 'n_estimators': 189, 'learning_rate': 0.020566905188514006}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.19742494900411037
Fold 2 IBS: 0.18108026801773916
Fold 3 IBS: 0.17432258807179998
Fold 4 IBS: 0.20494217181348467
Fold 5 IBS: 0.19091364795007967
[I 2024-04-18 11:11:05,176] Trial 52 finished with value: 0.18973672497144278 and parameters: {'subsample': 0.14228317466355073, 'dropout_rate': 0.35670086273800994, 'n_estimators': 286, 'learning_rate': 0.008802736287483397}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.19918271148013028
Fold 2 IBS: 0.18342098019927808
Fold 3 IBS: 0.1769329211856434
Fold 4 IBS: 0.20831790021273522
Fold 5 IBS: 0.18985993453227512
[I 2024-04-18 11:11:19,795] Trial 53 finished with value: 0.19154288952201243 and parameters: {'subsample': 0.2063183208905497, 'dropout_rate': 0.3387186458168315, 'n_estimators': 276, 'learning_rate': 0.0086118379013326}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.2386357084064059
Fold 2 IBS: 0.21727914403546403
Fold 3 IBS: 0.20312426373665632
Fold 4 IBS: 0.2588218575169021
Fold 5 IBS: 0.1999536225839609
[I 2024-04-18 11:11:35,496] Trial 54 finished with value: 0.22356291925587785 and parameters: {'subsample': 0.7050102269043423, 'dropout_rate': 0.28287653746561314, 'n_estimators': 307, 'learning_rate': 0.01970261845759295}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.19693259508781769
Fold 2 IBS: 0.18234618389851368
Fold 3 IBS: 0.17599183135325341
Fold 4 IBS: 0.20272599598725927
Fold 5 IBS: 0.19189244628278662
[I 2024-04-18 11:11:46,628] Trial 55 finished with value: 0.18997781052192614 and parameters: {'subsample': 0.132283225655762, 'dropout_rate': 0.3631731548207841, 'n_estimators': 196, 'learning_rate': 0.011288624875880358}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.21059030674907933
Fold 2 IBS: 0.21474821543778397
Fold 3 IBS: 0.19929047323497623
Fold 4 IBS: 0.21929828265740214
Fold 5 IBS: 0.21306931673511317
[I 2024-04-18 11:12:00,606] Trial 56 finished with value: 0.21139931896287098 and parameters: {'subsample': 0.17508593418632573, 'dropout_rate': 0.1834512133844656, 'n_estimators': 264, 'learning_rate': 0.001022967402087089}. Best is trial 47 with value: 0.18608963039911053.

Fold 1 IBS: 0.2033663207076748
Fold 2 IBS: 0.18007792028319827
Fold 3 IBS: 0.17227783495267568
Fold 4 IBS: 0.20518748393382122
Fold 5 IBS: 0.18930167896409603
[I 2024-04-18 11:12:13,111] Trial 57 finished with value: 0.1900422477682932 and parameters: {'subsample': 0.101496956005944, 'dropout_rate': 0.49385760505702486, 'n_estimators': 215, 'learning_rate': 0.02025280377209624}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.20191437074126453
Fold 2 IBS: 0.18368497098361156
Fold 3 IBS: 0.17811956307175236
Fold 4 IBS: 0.2131306985901757
Fold 5 IBS: 0.18817122553751192
[I 2024-04-18 11:12:31,766] Trial 58 finished with value: 0.1930041657848632 and parameters: {'subsample': 0.23706967835523893, 'dropout_rate': 0.36573681723837637, 'n_estimators': 376, 'learning_rate': 0.006783089945917651}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.2022987991171443
Fold 2 IBS: 0.1859213832363397
Fold 3 IBS: 0.17823772867565482
Fold 4 IBS: 0.22102338598856885
Fold 5 IBS: 0.18880213817312436
[I 2024-04-18 11:12:41,956] Trial 59 finished with value: 0.1952566870381664 and parameters: {'subsample': 0.1464916952320863, 'dropout_rate': 0.2506153358299021, 'n_estimators': 163, 'learning_rate': 0.030514156459768273}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.20064044758933672
Fold 2 IBS: 0.18988481119516484
Fold 3 IBS: 0.18285349189144
Fold 4 IBS: 0.20575216561525306
Fold 5 IBS: 0.1964402141118523
[I 2024-04-18 11:12:50,669] Trial 60 finished with value: 0.19511422608060938 and parameters: {'subsample': 0.2100115761757803, 'dropout_rate': 0.41844921535932134, 'n_estimators': 133, 'learning_rate': 0.011145036037083703}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.19681838382017464
Fold 2 IBS: 0.1818840901656728
Fold 3 IBS: 0.17560820208535435
Fold 4 IBS: 0.2027537789520483
Fold 5 IBS: 0.19145106257887262
[I 2024-04-18 11:13:01,728] Trial 61 finished with value: 0.18970310352042455 and parameters: {'subsample': 0.12887925580035098, 'dropout_rate': 0.35893568672159626, 'n_estimators': 191, 'learning_rate': 0.012074005665938636}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.1968217150061881
Fold 2 IBS: 0.17997461252154884
Fold 3 IBS: 0.17357329273714497
Fold 4 IBS: 0.2058011907285391
Fold 5 IBS: 0.1886562329875466
[I 2024-04-18 11:13:13,103] Trial 62 finished with value: 0.18896540879619353 and parameters: {'subsample': 0.13190905951752951, 'dropout_rate': 0.2873170300985706, 'n_estimators': 191, 'learning_rate': 0.01583526265661637}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.19625801089424652
Fold 2 IBS: 0.1797647134109221
Fold 3 IBS: 0.17371809675018282
Fold 4 IBS: 0.2048291171697602
Fold 5 IBS: 0.18846684618255846
[I 2024-04-18 11:13:23,800] Trial 63 finished with value: 0.18860735688153402 and parameters: {'subsample': 0.1305910860154294, 'dropout_rate': 0.2954017445925562, 'n_estimators': 183, 'learning_rate': 0.016051252409336997}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.19671565217090892
Fold 2 IBS: 0.17562367313690228
Fold 3 IBS: 0.17264524626216682
Fold 4 IBS: 0.20350080386143463
Fold 5 IBS: 0.18997878823528697
[I 2024-04-18 11:13:34,598] Trial 64 finished with value: 0.18769283273333995 and parameters: {'subsample': 0.10180564206472163, 'dropout_rate': 0.21966346386241334, 'n_estimators': 185, 'learning_rate': 0.01617145824510766}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.20738101458347233
Fold 2 IBS: 0.18756872302247096
Fold 3 IBS: 0.17966134126169261
Fold 4 IBS: 0.2255263530674894
Fold 5 IBS: 0.18698082589479317
[I 2024-04-18 11:13:47,101] Trial 65 finished with value: 0.19742365156598368 and parameters: {'subsample': 0.2937999105281317, 'dropout_rate': 0.21215741965738966, 'n_estimators': 215, 'learning_rate': 0.016911198332154143}. Best is trial 47 with value: 0.18608963039911053.
Fold 1 IBS: 0.19823467617431564
Fold 2 IBS: 0.1754648773045972
Fold 3 IBS: 0.170555793350373
Fold 4 IBS: 0.19678951523426005
Fold 5 IBS: 0.1870202283675768
[I 2024-04-18 11:13:57,259] Trial 66 finished with value: 0.18561301808622452 and parameters: {'subsample': 0.10041041298681407, 'dropout_rate': 0.28132150572293957, 'n_estimators': 158, 'learning_rate': 0.02276408707314117}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.22523926545868422
Fold 2 IBS: 0.19052147786952678
Fold 3 IBS: 0.18711999340709584
Fold 4 IBS: 0.23169437465734216
Fold 5 IBS: 0.18717681364412844
[I 2024-04-18 11:14:07,255] Trial 67 finished with value: 0.2043503850073555 and parameters: {'subsample': 0.7814458599747043, 'dropout_rate': 0.2295722410968345, 'n_estimators': 157, 'learning_rate': 0.024697704559216764}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.2025007406901149
Fold 2 IBS: 0.1783839818637808
Fold 3 IBS: 0.17390822778994208
Fold 4 IBS: 0.21569022533363869
Fold 5 IBS: 0.19277433126088728
[I 2024-04-18 11:14:20,727] Trial 68 finished with value: 0.19265150138767276 and parameters: {'subsample': 0.10267321395467874, 'dropout_rate': 0.162334122624326, 'n_estimators': 242, 'learning_rate': 0.021337461673444504}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.2060779803776212
Fold 2 IBS: 0.20280662624750112
Fold 3 IBS: 0.1905736884745779
Fold 4 IBS: 0.21119664947003153
Fold 5 IBS: 0.20445748945055478
[I 2024-04-18 11:14:31,402] Trial 69 finished with value: 0.20302248680405732 and parameters: {'subsample': 0.18890607008448618, 'dropout_rate': 0.1044522012349917, 'n_estimators': 179, 'learning_rate': 0.004425392509973959}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.202361960303769
Fold 2 IBS: 0.18297478296556935
Fold 3 IBS: 0.17851814685810252
Fold 4 IBS: 0.21165652401796334
Fold 5 IBS: 0.18874140129472183
[I 2024-04-18 11:14:39,883] Trial 70 finished with value: 0.1928505630880252 and parameters: {'subsample': 0.2354455229958542, 'dropout_rate': 0.27793272026295446, 'n_estimators': 120, 'learning_rate': 0.0219000010493351}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.1953951074407951
Fold 2 IBS: 0.1792784578420588
Fold 3 IBS: 0.17292699229394323
Fold 4 IBS: 0.2015894952788095
Fold 5 IBS: 0.18893582638468362
[I 2024-04-18 11:14:50,660] Trial 71 finished with value: 0.18762517584805807 and parameters: {'subsample': 0.11836117346088168, 'dropout_rate': 0.2909575532384225, 'n_estimators': 181, 'learning_rate': 0.015927354319010587}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19780336524336462
Fold 2 IBS: 0.18303896109526951
Fold 3 IBS: 0.17803527687965584
Fold 4 IBS: 0.20453045880529788
Fold 5 IBS: 0.19127958288743266
[I 2024-04-18 11:15:00,192] Trial 72 finished with value: 0.1909375289822041 and parameters: {'subsample': 0.17061388205693567, 'dropout_rate': 0.3014185076008847, 'n_estimators': 150, 'learning_rate': 0.013996643303792619}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.20087318000631615
Fold 2 IBS: 0.18970988757867996
Fold 3 IBS: 0.18049039008778694
Fold 4 IBS: 0.2183160817806485
Fold 5 IBS: 0.1915785519099287
[I 2024-04-18 11:15:12,329] Trial 73 finished with value: 0.19619361827267207 and parameters: {'subsample': 0.11758536641294517, 'dropout_rate': 0.26038467680927563, 'n_estimators': 209, 'learning_rate': 0.02539065008704395}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.214032098337222
Fold 2 IBS: 0.20723576355208406
Fold 3 IBS: 0.1946330625124018
Fold 4 IBS: 0.22008196170244054
Fold 5 IBS: 0.20576141666986394
[I 2024-04-18 11:15:24,736] Trial 74 finished with value: 0.2083488605548025 and parameters: {'subsample': 0.10138462131091673, 'dropout_rate': 0.3891157698515415, 'n_estimators': 226, 'learning_rate': 0.03471229822615198}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.1967873006607372
Fold 2 IBS: 0.18031560111778852
Fold 3 IBS: 0.1728925630766008
Fold 4 IBS: 0.20922986106992877
Fold 5 IBS: 0.1873352813391847
[I 2024-04-18 11:15:35,232] Trial 75 finished with value: 0.189312121452848 and parameters: {'subsample': 0.15493645526642805, 'dropout_rate': 0.32748532455086893, 'n_estimators': 177, 'learning_rate': 0.017719271094012397}. Best is trial 66 with value: 0.18561301808622452.

Fold 1 IBS: 0.21736310414126978
Fold 2 IBS: 0.22621598527429648
Fold 3 IBS: 0.2043056587143774
Fold 4 IBS: 0.2530734029856345
Fold 5 IBS: 0.20903981299264454
[I 2024-04-18 11:15:48,846] Trial 76 finished with value: 0.22199959282164455 and parameters: {'subsample': 0.19161322654962637, 'dropout_rate': 0.2274390090824162, 'n_estimators': 255, 'learning_rate': 0.030984968300376045}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.2093926746060527
Fold 2 IBS: 0.18747812089941904
Fold 3 IBS: 0.18350793543368743
Fold 4 IBS: 0.21000092056566644
Fold 5 IBS: 0.19094130798199171
[I 2024-04-18 11:15:57,900] Trial 77 finished with value: 0.1962641918973635 and parameters: {'subsample': 0.5891607666001992, 'dropout_rate': 0.17629353184919394, 'n_estimators': 138, 'learning_rate': 0.014071343257691903}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19571917467377073
Fold 2 IBS: 0.18426023556786475
Fold 3 IBS: 0.1775312951028814
Fold 4 IBS: 0.19934669428156476
Fold 5 IBS: 0.19111658363331688
[I 2024-04-18 11:16:05,765] Trial 78 finished with value: 0.1895947966518797 and parameters: {'subsample': 0.12198335688027105, 'dropout_rate': 0.3065388972083445, 'n_estimators': 103, 'learning_rate': 0.01964028642221175}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.20346201636977654
Fold 2 IBS: 0.18820074798465575
Fold 3 IBS: 0.17979192872628189
Fold 4 IBS: 0.2306948786347611
Fold 5 IBS: 0.18687184237413765
[I 2024-04-18 11:16:15,663] Trial 79 finished with value: 0.1978042828179226 and parameters: {'subsample': 0.22154912607999083, 'dropout_rate': 0.3840329246048661, 'n_estimators': 158, 'learning_rate': 0.02574723738417559}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.20316418352841845
Fold 2 IBS: 0.1863941661453314
Fold 3 IBS: 0.18111448976738917
Fold 4 IBS: 0.22593812267045138
Fold 5 IBS: 0.18808911483473023
[I 2024-04-18 11:16:26,586] Trial 80 finished with value: 0.19694001538926414 and parameters: {'subsample': 0.257170146574131, 'dropout_rate': 0.14030017497322128, 'n_estimators': 180, 'learning_rate': 0.022430294831708757}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.1965539641308626
Fold 2 IBS: 0.18086819611159455
Fold 3 IBS: 0.1732057822775123
Fold 4 IBS: 0.21051025115829755
Fold 5 IBS: 0.18724476084223604
[I 2024-04-18 11:16:38,141] Trial 81 finished with value: 0.1896765909041006 and parameters: {'subsample': 0.15886694520632835, 'dropout_rate': 0.27820480634306805, 'n_estimators': 205, 'learning_rate': 0.015377610609758405}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.1931905279104841
Fold 2 IBS: 0.17630438896913184
Fold 3 IBS: 0.17189825372145454
Fold 4 IBS: 0.20344427893114925
Fold 5 IBS: 0.18803006723343263
[I 2024-04-18 11:16:49,126] Trial 82 finished with value: 0.18657350335313047 and parameters: {'subsample': 0.12337519880483173, 'dropout_rate': 0.2099639602384662, 'n_estimators': 189, 'learning_rate': 0.016822009297049703}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19926803071359167
Fold 2 IBS: 0.17259285603224786
Fold 3 IBS: 0.1733604678588626
Fold 4 IBS: 0.20733979307961778
Fold 5 IBS: 0.18816009051263305
[I 2024-04-18 11:16:57,741] Trial 83 finished with value: 0.18814424763939058 and parameters: {'subsample': 0.11583705486278034, 'dropout_rate': 0.2018940226720174, 'n_estimators': 124, 'learning_rate': 0.027890790681417744}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.1969546541663812
Fold 2 IBS: 0.19106525434315624
Fold 3 IBS: 0.18046480268444157
Fold 4 IBS: 0.20304563252308414
Fold 5 IBS: 0.19637968092292715
[I 2024-04-18 11:17:07,220] Trial 84 finished with value: 0.19358200492799807 and parameters: {'subsample': 0.11849564821954552, 'dropout_rate': 0.2146573873944886, 'n_estimators': 145, 'learning_rate': 0.010439750924090453}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.20295595481179757
Fold 2 IBS: 0.19650903265106448
Fold 3 IBS: 0.18649057812084574
Fold 4 IBS: 0.2077629597449092
Fold 5 IBS: 0.20016274052595998
[I 2024-04-18 11:17:20,021] Trial 85 finished with value: 0.1987762531709154 and parameters: {'subsample': 0.18293642671827012, 'dropout_rate': 0.19421117742362068, 'n_estimators': 231, 'learning_rate': 0.004932132536593638}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19896070468631266
Fold 2 IBS: 0.1833956781510808
Fold 3 IBS: 0.175586025614687
Fold 4 IBS: 0.20423461642810886
Fold 5 IBS: 0.190217858241334
[I 2024-04-18 11:17:28,854] Trial 86 finished with value: 0.19047897662430466 and parameters: {'subsample': 0.15699630475486864, 'dropout_rate': 0.24083210209187067, 'n_estimators': 132, 'learning_rate': 0.01759825844784763}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19824607950274292
Fold 2 IBS: 0.1773518937296558
Fold 3 IBS: 0.1702082855885876
Fold 4 IBS: 0.20594455568540831
Fold 5 IBS: 0.19144389347541693
[I 2024-04-18 11:17:39,104] Trial 87 finished with value: 0.18863894159636233 and parameters: {'subsample': 0.10086136422628394, 'dropout_rate': 0.10574006154657453, 'n_estimators': 164, 'learning_rate': 0.028019421691707326}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19998248941363783
Fold 2 IBS: 0.1831946464374285
Fold 3 IBS: 0.17712612428101623
Fold 4 IBS: 0.20866403818070423
Fold 5 IBS: 0.18969501814191175
[I 2024-04-18 11:17:49,985] Trial 88 finished with value: 0.1917324632909397 and parameters: {'subsample': 0.20079481435045193, 'dropout_rate': 0.2597300309739128, 'n_estimators': 188, 'learning_rate': 0.01284634557197569}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.20804397885254527
Fold 2 IBS: 0.18505024924213678
Fold 3 IBS: 0.18196789460837795
Fold 4 IBS: 0.21428955451616105
Fold 5 IBS: 0.18818829772193585
[I 2024-04-18 11:17:58,482] Trial 89 finished with value: 0.19550799498823138 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.15860471413359623, 'n_estimators': 124, 'learning_rate': 0.020241058267540014}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19770636693275567
Fold 2 IBS: 0.1814269063341596
Fold 3 IBS: 0.17289681879169486
Fold 4 IBS: 0.2022987706946301
Fold 5 IBS: 0.1902373387219641
[I 2024-04-18 11:18:06,678] Trial 90 finished with value: 0.18891324029504086 and parameters: {'subsample': 0.14401837920879912, 'dropout_rate': 0.21058186004866614, 'n_estimators': 107, 'learning_rate': 0.023058939482875754}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.1996483118951309
Fold 2 IBS: 0.1756759481534921
Fold 3 IBS: 0.17065090803322633
Fold 4 IBS: 0.21128369068493164
Fold 5 IBS: 0.19245503253422513
[I 2024-04-18 11:18:16,599] Trial 91 finished with value: 0.18994277826020123 and parameters: {'subsample': 0.11810941776941417, 'dropout_rate': 0.12773483057817064, 'n_estimators': 158, 'learning_rate': 0.027987970663937843}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19461945203418754
Fold 2 IBS: 0.1786645206476029
Fold 3 IBS: 0.1731066022814608
Fold 4 IBS: 0.20162932773960301
Fold 5 IBS: 0.18799989091218147
[I 2024-04-18 11:18:26,781] Trial 92 finished with value: 0.18720395872300716 and parameters: {'subsample': 0.12042558718357868, 'dropout_rate': 0.3398532883505976, 'n_estimators': 165, 'learning_rate': 0.018435633232671382}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.197097480496107
Fold 2 IBS: 0.18029138322417226
Fold 3 IBS: 0.17316624031582953
Fold 4 IBS: 0.2085639498738098
Fold 5 IBS: 0.18792913726485577
[I 2024-04-18 11:18:37,159] Trial 93 finished with value: 0.18940963823495488 and parameters: {'subsample': 0.16178582068293437, 'dropout_rate': 0.34056495794779934, 'n_estimators': 171, 'learning_rate': 0.01833084410735908}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19536208084817547
Fold 2 IBS: 0.18137128526685856
Fold 3 IBS: 0.17488207790009325
Fold 4 IBS: 0.19950441461961008
Fold 5 IBS: 0.18987546951495496
[I 2024-04-18 11:18:46,467] Trial 94 finished with value: 0.18819906562993846 and parameters: {'subsample': 0.12316833020424982, 'dropout_rate': 0.31724754589032145, 'n_estimators': 147, 'learning_rate': 0.016305756182291613}. Best is trial 66 with value: 0.18561301808622452.

Fold 1 IBS: 0.197838168025373
Fold 2 IBS: 0.1845307640679511
Fold 3 IBS: 0.17828065280806055
Fold 4 IBS: 0.20655436657739523
Fold 5 IBS: 0.19180023391350487
[I 2024-04-18 11:18:58,086] Trial 95 finished with value: 0.19180083707845694 and parameters: {'subsample': 0.17636450847859508, 'dropout_rate': 0.2683180256379605, 'n_estimators': 202, 'learning_rate': 0.009999123660042509}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19796746552096606
Fold 2 IBS: 0.1828469400711107
Fold 3 IBS: 0.1762298250835142
Fold 4 IBS: 0.20469635327408078
Fold 5 IBS: 0.19168554513903255
[I 2024-04-18 11:19:07,879] Trial 96 finished with value: 0.19068522581774086 and parameters: {'subsample': 0.14665105862236183, 'dropout_rate': 0.3166812067394869, 'n_estimators': 147, 'learning_rate': 0.014533634685131247}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.20281841887854912
Fold 2 IBS: 0.1944235832270459
Fold 3 IBS: 0.19487494976385714
Fold 4 IBS: 0.2279662550105142
Fold 5 IBS: 0.2022973787702932
[I 2024-04-18 11:19:19,990] Trial 97 finished with value: 0.2044761171300519 and parameters: {'subsample': 0.11661422559975447, 'dropout_rate': 0.23421638602883582, 'n_estimators': 219, 'learning_rate': 0.03362714073478312}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.19745944348578803
Fold 2 IBS: 0.17876335581914643
Fold 3 IBS: 0.17312399596481576
Fold 4 IBS: 0.19896388695127232
Fold 5 IBS: 0.18583599176044494
[I 2024-04-18 11:19:28,587] Trial 98 finished with value: 0.1868293347962935 and parameters: {'subsample': 0.12000709284591062, 'dropout_rate': 0.3425083894577178, 'n_estimators': 125, 'learning_rate': 0.026117089776837927}. Best is trial 66 with value: 0.18561301808622452.
Fold 1 IBS: 0.20014173406612182
Fold 2 IBS: 0.18113482876186723
Fold 3 IBS: 0.17691102401392333
Fold 4 IBS: 0.21574723697706902
Fold 5 IBS: 0.18757642598853191
[I 2024-04-18 11:19:36,794] Trial 99 finished with value: 0.19230224996150266 and parameters: {'subsample': 0.2198295893177045, 'dropout_rate': 0.33881573868012477, 'n_estimators': 116, 'learning_rate': 0.026256248926987902}. Best is trial 66 with value: 0.18561301808622452.


* Best trial for IBS:
 FrozenTrial(number=66, state=TrialState.COMPLETE, values=[0.18561301808622452], datetime_start=datetime.datetime(2024, 4, 18, 11, 13, 47, 108329), datetime_complete=datetime.datetime(2024, 4, 18, 11, 13, 57, 259686), params={'subsample': 0.10041041298681407, 'dropout_rate': 0.28132150572293957, 'n_estimators': 158, 'learning_rate': 0.02276408707314117}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=66, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.10041041298681407, 'dropout_rate': 0.28132150572293957, 'n_estimators': 158, 'learning_rate': 0.02276408707314117}


* Best Score for IBS:
 0.18561301808622452

In [101]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [102]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.746
train_ibs:  0.186

#### Test

In [103]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [104]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10443578020986953,
                                              learning_rate=0.09196255088220771,
                                              n_estimators=500,
                                              random_state=123,
                                              subsample=0.1072481243021174)

C-index score: 0.578

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.28132150572293957,
                                              learning_rate=0.02276408707314117,
                                              n_estimators=158,
                                              random_state=123,
                                              subsample=0.10041041298681407)

IBS: 0.234

In [105]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [106]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.886   1.0
Randomsurvivalforest             0.864   2.0
GradientBoosting                 0.758   3.0
CoxElastic                       0.753   4.0
ComponentwiseGradientBoosting    0.746   5.0
CoxRidge                         0.716   6.0
CoxLasso                         0.678   7.0

In [107]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.179   1.0
Randomsurvivalforest           0.183   2.0
ComponentwiseGradientBoosting  0.186   3.0
GradientBoosting               0.208   4.0
CoxElastic                     0.210   5.0
CoxRidge                       0.217   6.0
CoxLasso                       0.313   7.0

In [108]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ExtraSurvivalTrees               0.662   1.0
Randomsurvivalforest             0.629   2.0
GradientBoosting                 0.618   3.0
ComponentwiseGradientBoosting    0.578   4.0
CoxRidge                         0.573   5.5
CoxElastic                       0.573   5.5
CoxLasso                         0.550   7.0

In [109]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.200   1.0
Randomsurvivalforest           0.205   2.0
GradientBoosting               0.213   3.0
CoxRidge                       0.221   4.5
CoxElastic                     0.221   4.5
ComponentwiseGradientBoosting  0.234   6.0
CoxLasso                       0.419   7.0

In [110]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/os/yeojohnson/no_selection/' 

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_os_yeojohnson_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [111]:
from datetime import date

current_date = date.today()
print(current_date)

2024-04-18