In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [6]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [10]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [14]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [15]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [16]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [17]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

# Feature Selection

In [18]:
# Choose features from the result of Cox PLSR in R
selected_features = [
"shape_MajorAxisLength",
"shape_Elongation",
"glszm_LargeAreaLowGrayLevelEmphasis_CT_c16",
"shape_Sphericity",
"shape_MinorAxisLength",
"shape_SurfaceVolumeRatio",
"LBP_201_PET",
"gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2",
"shape_Flatness",
"glszm_GrayLevelNonUniformityNormalized_PET_c04"
]

In [19]:
X_plsr = X.loc[:, selected_features]
X_new = X_plsr.copy()

In [20]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, selected_features]

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [23]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [24]:
X_new

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,42.073251,0.600926,7442.066260,0.761164,25.282894,0.251218,0.000062,0.000959,0.535140,0.140496
1,24.613845,0.841579,238.870676,0.697049,20.714498,0.489853,0.000349,0.002776,0.367109,0.180556
2,48.030294,0.772821,12957.157420,0.565792,37.118833,0.278467,0.000000,0.001179,0.597785,0.251029
3,25.589900,0.847727,233.632355,0.684364,21.693241,0.474018,0.000000,0.002748,0.405730,0.190083
4,34.684750,0.831483,121.921768,0.503142,28.839789,0.563135,0.000399,0.002309,0.442406,0.160494
...,...,...,...,...,...,...,...,...,...,...
134,33.069705,0.680294,1528.464999,0.742102,22.497115,0.322021,0.000000,0.001347,0.523608,0.285714
135,41.043692,0.758193,41182.958565,0.722918,31.119023,0.227705,0.000079,0.000850,0.735524,0.200000
136,36.618802,0.770113,3964.057173,0.652963,28.200620,0.298398,0.000000,0.001111,0.648063,0.173469
137,45.870392,0.628897,5243.112516,0.724255,28.847736,0.252893,0.000054,0.000935,0.492193,0.263889
138,30.363259,0.892637,2169.952628,0.722633,27.103353,0.290461,0.000000,0.000629,0.756267,0.260331

In [25]:
X_new_std

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,-0.098422,-0.681983,-0.227575,1.075042,-0.404946,-0.558082,-0.315438,-0.496657,0.072232,-1.152048
1,-1.209119,1.006304,-0.275315,0.242767,-0.804734,1.585077,1.967842,2.054251,-1.302158,-0.669778
2,0.280542,0.523938,-0.191023,-1.461057,0.630836,-0.313359,-0.805067,-0.187799,0.584632,0.178635
3,-1.147026,1.049432,-0.275350,0.078112,-0.719083,1.442865,-0.805067,2.014276,-0.986261,-0.555083
4,-0.568449,0.935477,-0.276090,-2.274305,-0.093676,2.243217,2.359078,1.398595,-0.686277,-0.911297
...,...,...,...,...,...,...,...,...,...,...
134,-0.671191,-0.125182,-0.266768,0.827589,-0.648734,0.077795,-0.805067,0.048554,-0.022089,0.596207
135,-0.163918,0.421312,-0.003951,0.578577,0.105783,-0.769256,-0.180035,-0.649927,1.711257,-0.435690
136,-0.445412,0.504939,-0.250626,-0.329498,-0.149611,-0.134362,-0.805067,-0.282932,0.995873,-0.755087
137,0.143137,-0.485754,-0.242149,0.595927,-0.092981,-0.543043,-0.374777,-0.529934,-0.279046,0.333455
138,-0.843364,1.364493,-0.262517,0.574872,-0.245635,-0.205649,-0.805067,-0.959367,1.880915,0.290618

In [26]:
MAASTRO_new

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,50.002093,0.765178,9404.025346,0.668072,38.260495,0.215184,0.000026,0.000768,0.610062,0.232422
1,41.753334,0.776540,16468.863361,0.669961,32.423122,0.276092,0.000167,0.001213,0.504616,0.339506
2,44.375483,0.697164,3829.811759,0.624081,30.936983,0.298887,0.000000,0.001176,0.478604,0.171875
3,46.115989,0.574636,2212.056593,0.577624,26.499895,0.361096,0.000080,0.001192,0.446059,0.166667
4,54.394967,0.633419,20185.616389,0.630933,34.454789,0.251519,0.000035,0.000766,0.480378,0.301020
...,...,...,...,...,...,...,...,...,...,...
94,34.218615,0.882411,18006.593217,0.671754,30.194871,0.307574,0.000078,0.001137,0.577884,0.202216
95,51.046869,0.535802,1303.136099,0.632189,27.351039,0.289922,0.000054,0.000962,0.455642,0.157025
96,50.417953,0.716610,8928.353080,0.645548,36.130031,0.228184,0.000028,0.000621,0.631485,0.460317
97,44.901412,0.665145,13835.684015,0.727488,29.865942,0.223872,0.000000,0.000947,0.628338,0.314879
98,36.574294,0.616262,1301.796144,0.672838,22.539345,0.347373,0.000112,0.001661,0.469139,0.182222

In [27]:
MAASTRO_new_std

,shape_MajorAxisLength,shape_Elongation,glszm_LargeAreaLowGrayLevelEmphasis_CT_c16,shape_Sphericity,shape_MinorAxisLength,shape_SurfaceVolumeRatio,LBP_201_PET,gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2,shape_Flatness,glszm_GrayLevelNonUniformityNormalized_PET_c04
0,0.405980,0.470316,-0.214572,-0.133381,0.730745,-0.881698,-0.596780,-0.764236,0.685053,-0.045370
1,-0.118774,0.550025,-0.167748,-0.108854,0.219907,-0.334696,0.524128,-0.139994,-0.177437,1.243797
2,0.048037,-0.006831,-0.251516,-0.704414,0.089853,-0.129977,-0.805067,-0.191744,-0.390198,-0.774281
3,0.158761,-0.866418,-0.262238,-1.307469,-0.298444,0.428717,-0.170569,-0.168865,-0.656393,-0.836983
4,0.685437,-0.454030,-0.143115,-0.615466,0.397702,-0.555379,-0.525146,-0.767510,-0.375685,0.780474
...,...,...,...,...,...,...,...,...,...,...
94,-0.598102,1.292755,-0.157556,-0.085581,0.024909,-0.051953,-0.187979,-0.246354,0.421853,-0.409011
95,0.472444,-1.138850,-0.268262,-0.599161,-0.223959,-0.210490,-0.373913,-0.492861,-0.578011,-0.953060
96,0.432435,0.129595,-0.217724,-0.425762,0.544305,-0.764952,-0.581052,-0.971544,0.860275,2.698219
97,0.081495,-0.231458,-0.185200,0.637891,-0.003876,-0.803671,-0.805067,-0.513058,0.834539,0.947314
98,-0.448243,-0.574392,-0.268271,-0.071514,-0.645039,0.305474,0.087339,0.488842,-0.467616,-0.649713

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [28]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:07:05,305] A new study created in memory with name: no-name-b93d70ce-74b9-4ab5-8879-7427b2329300
python(43293) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 19:07:20,012] Trial 0 finished with value: 0.7028948264777959 and parameters: {}. Best is trial 0 with value: 0.7028948264777959.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7028948264777959], datetime_start=datetime.datetime(2024, 4, 14, 19, 7, 5, 476177), datetime_complete=datetime.datetime(2024, 4, 14, 19, 7, 20, 11421), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7028948264777959

[I 2024-04-14 19:07:20,119] A new study created in memory with name: no-name-d0b8e984-9d09-470d-8fd9-f8da9126effa

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.26188816761455547
Fold 2 IBS: 0.17457592134628122
Fold 3 IBS: 0.15644372418899136
Fold 4 IBS: 0.21056251915501756
Fold 5 IBS: 0.19139883133650912
[I 2024-04-14 19:07:20,941] Trial 0 finished with value: 0.19897383272827093 and parameters: {}. Best is trial 0 with value: 0.19897383272827093.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19897383272827093], datetime_start=datetime.datetime(2024, 4, 14, 19, 7, 20, 204827), datetime_complete=datetime.datetime(2024, 4, 14, 19, 7, 20, 940704), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19897383272827093

In [29]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [30]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.703
train_ibs:  0.199

#### Test

In [31]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [32]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.528
IBS score: 0.309

In [33]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:07:21,603] A new study created in memory with name: no-name-f5cff67d-c892-4577-bda7-16cbf96bb876

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7167300380228137

[I 2024-04-14 19:07:22,053] A new study created in memory with name: no-name-59c35267-2bad-465d-90d9-1bc58b6d2b5f

Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:07:22,041] Trial 0 finished with value: 0.6482287832820909 and parameters: {}. Best is trial 0 with value: 0.6482287832820909.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6482287832820909], datetime_start=datetime.datetime(2024, 4, 14, 19, 7, 21, 682902), datetime_complete=datetime.datetime(2024, 4, 14, 19, 7, 22, 41359), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6482287832820909

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709428728842
Fold 2 IBS: 0.2320398711590297
Fold 3 IBS: 0.22898186727039876
Fold 4 IBS: 0.24197476011764557
Fold 5 IBS: 0.22939558449397743
[I 2024-04-14 19:07:22,771] Trial 0 finished with value: 0.23592783546566798 and parameters: {}. Best is trial 0 with value: 0.23592783546566798.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783546566798], datetime_start=datetime.datetime(2024, 4, 14, 19, 7, 22, 129299), datetime_complete=datetime.datetime(2024, 4, 14, 19, 7, 22, 770562), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783546566798

In [36]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.648
train_ibs:  0.236

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.537

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:07:23,680] A new study created in memory with name: no-name-097de088-6d7c-4392-995e-8cf51ad216ce

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8

[I 2024-04-14 19:07:25,167] A new study created in memory with name: no-name-cf8791d5-9dfb-40d0-a9db-a05938bb3333

Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:25,118] Trial 0 finished with value: 0.7011706560246108 and parameters: {}. Best is trial 0 with value: 0.7011706560246108.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7011706560246108], datetime_start=datetime.datetime(2024, 4, 14, 19, 7, 23, 739624), datetime_complete=datetime.datetime(2024, 4, 14, 19, 7, 25, 117782), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7011706560246108

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2618018981937393
Fold 2 IBS: 0.1754076638033244
Fold 3 IBS: 0.1575583206585483
Fold 4 IBS: 0.21083436582901882
Fold 5 IBS: 0.18978087462357812
[I 2024-04-14 19:07:26,597] Trial 0 finished with value: 0.19907662462164177 and parameters: {}. Best is trial 0 with value: 0.19907662462164177.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19907662462164177], datetime_start=datetime.datetime(2024, 4, 14, 19, 7, 25, 209960), datetime_complete=datetime.datetime(2024, 4, 14, 19, 7, 26, 595979), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19907662462164177

In [42]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.701
train_ibs:  0.199

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.528

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.308

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:07:27,720] A new study created in memory with name: no-name-eec4122a-7a1f-465d-9b77-ddb289b1d5ae

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:29,454] Trial 0 finished with value: 0.7020217198543981 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7020217198543981.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:30,613] Trial 1 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7028727836841854.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:31,845] Trial 2 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:32,764] Trial 3 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:33,801] Trial 4 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:35,152] Trial 5 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:35,867] Trial 6 finished with value: 0.7011706560246108 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:36,501] Trial 7 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:37,506] Trial 8 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:38,315] Trial 9 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.7036695964331894.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:39,069] Trial 10 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:07:39,269] Trial 11 finished with value: 0.6482000157078526 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:39,996] Trial 12 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:07:40,351] Trial 13 finished with value: 0.6482000157078526 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:41,654] Trial 14 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:42,406] Trial 15 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:43,256] Trial 16 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:44,175] Trial 17 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:45,285] Trial 18 finished with value: 0.6547965279112251 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:46,198] Trial 19 finished with value: 0.7011706560246108 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:47,279] Trial 20 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:48,166] Trial 21 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.10825799833043775}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:48,820] Trial 22 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.18602446416420754}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:49,453] Trial 23 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.35431593754643226}. Best is trial 10 with value: 0.7045206602629766.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:50,404] Trial 24 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.07543723109624823}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:51,401] Trial 25 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.19147826708277826}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:52,711] Trial 26 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.33104202854466025}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:53,975] Trial 27 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.07505393448412474}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:55,340] Trial 28 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6010115468401365}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:07:57,604] Trial 29 finished with value: 0.7020217198543981 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:07:58,846] Trial 30 finished with value: 0.6482000157078526 and parameters: {'l1_ratio': 0.0027141332606375745}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:00,443] Trial 31 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:01,931] Trial 32 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.27357119396913165}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:03,231] Trial 33 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.12552692568198015}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:04,050] Trial 34 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.21553914253693035}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:04,879] Trial 35 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.26458368089665707}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:06,015] Trial 36 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.07755657280239842}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:06,849] Trial 37 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.14805343087788478}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:07,646] Trial 38 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4483972195751016}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:08,349] Trial 39 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:08,742] Trial 40 finished with value: 0.6409528309354791 and parameters: {'l1_ratio': 0.0419480283732345}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:09,627] Trial 41 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.14233132954823524}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:10,407] Trial 42 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.18996723622963846}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:11,174] Trial 43 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.1097087129067989}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:11,465] Trial 44 finished with value: 0.6409528309354791 and parameters: {'l1_ratio': 0.04424904269439714}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:12,053] Trial 45 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:12,778] Trial 46 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.24448489004615218}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:13,560] Trial 47 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.10524857778047021}. Best is trial 10 with value: 0.7045206602629766.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:14,297] Trial 48 finished with value: 0.7020217198543981 and parameters: {'l1_ratio': 0.7991933234425521}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:15,043] Trial 49 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.2943478497434463}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:15,770] Trial 50 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.16928824208309873}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:16,547] Trial 51 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.10522363173012594}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:17,391] Trial 52 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.2225918073443785}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:17,815] Trial 53 finished with value: 0.6409528309354791 and parameters: {'l1_ratio': 0.04641553906382965}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:18,748] Trial 54 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.12099819656297388}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:19,035] Trial 55 finished with value: 0.6482000157078526 and parameters: {'l1_ratio': 0.008887391546791648}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:19,770] Trial 56 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.38591495646936336}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:20,448] Trial 57 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.18753365082306073}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:21,225] Trial 58 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.07940958496111458}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:22,029] Trial 59 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.6443692288191284}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:22,330] Trial 60 finished with value: 0.6488846019502792 and parameters: {'l1_ratio': 0.0351685028518921}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:23,174] Trial 61 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.08497028745341434}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:23,873] Trial 62 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.1452484162228527}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:24,542] Trial 63 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.21019349003895454}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:25,261] Trial 64 finished with value: 0.6547965279112251 and parameters: {'l1_ratio': 0.05997257351419345}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:26,429] Trial 65 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.09504096425815595}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:27,492] Trial 66 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.16202892069064173}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:28,368] Trial 67 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.255842397554899}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:29,429] Trial 68 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.13135116751230524}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:29,673] Trial 69 finished with value: 0.6473489518780654 and parameters: {'l1_ratio': 0.027081761538015246}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:30,425] Trial 70 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.3095209018261047}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:31,184] Trial 71 finished with value: 0.6517547028161681 and parameters: {'l1_ratio': 0.07309717745006883}. Best is trial 10 with value: 0.7045206602629766.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:31,574] Trial 72 finished with value: 0.6482000157078526 and parameters: {'l1_ratio': 0.004482181741513144}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:32,499] Trial 73 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.12420054405329062}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:33,345] Trial 74 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.16757672227614667}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:34,036] Trial 75 finished with value: 0.6547965279112251 and parameters: {'l1_ratio': 0.066752857035873}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:35,101] Trial 76 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.20331332808738323}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:35,794] Trial 77 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.09783138914205564}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:36,381] Trial 78 finished with value: 0.7020217198543981 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:36,580] Trial 79 finished with value: 0.648124145676515 and parameters: {'l1_ratio': 0.02996414993509597}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:37,359] Trial 80 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.13897765110160076}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:38,409] Trial 81 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.17091361181037837}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:39,193] Trial 82 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.23312649196948607}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:39,759] Trial 83 finished with value: 0.6540360716374608 and parameters: {'l1_ratio': 0.05702437147371678}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:40,460] Trial 84 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.11165032186012427}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:41,353] Trial 85 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.15411521449323906}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:42,120] Trial 86 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.09219119136553999}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:42,938] Trial 87 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.18796989513326373}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:43,656] Trial 88 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.12864015421531919}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:08:43,898] Trial 89 finished with value: 0.6473489518780654 and parameters: {'l1_ratio': 0.029770518593184254}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:44,586] Trial 90 finished with value: 0.7020217198543981 and parameters: {'l1_ratio': 0.7580961383559556}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.548936170212766
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:45,122] Trial 91 finished with value: 0.6547965279112251 and parameters: {'l1_ratio': 0.0624151903824077}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:45,851] Trial 92 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.11105823430451653}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:46,539] Trial 93 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.1598276544633182}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:47,425] Trial 94 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.07589624075098894}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:48,168] Trial 95 finished with value: 0.7036695964331894 and parameters: {'l1_ratio': 0.20944257496670565}. Best is trial 10 with value: 0.7045206602629766.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:48,715] Trial 96 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.1343599231318625}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:49,214] Trial 97 finished with value: 0.7028727836841854 and parameters: {'l1_ratio': 0.4965881146918674}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:49,771] Trial 98 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.17953604381325466}. Best is trial 10 with value: 0.7045206602629766.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179

[I 2024-04-14 19:08:50,667] A new study created in memory with name: no-name-beec2d70-7c0c-49a4-b19d-b5fcf69a6b09

Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:08:50,657] Trial 99 finished with value: 0.7045206602629766 and parameters: {'l1_ratio': 0.09054408391391834}. Best is trial 10 with value: 0.7045206602629766.


* Best trial for C-index:
 FrozenTrial(number=10, state=TrialState.COMPLETE, values=[0.7045206602629766], datetime_start=datetime.datetime(2024, 4, 14, 19, 7, 38, 328501), datetime_complete=datetime.datetime(2024, 4, 14, 19, 7, 39, 68947), params={'l1_ratio': 0.08382735104105443}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=10, value=None)


* Best Score for C-index:
 0.7045206602629766

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2615054568432813
Fold 2 IBS: 0.17546124558500803
Fold 3 IBS: 0.15745953203134078
Fold 4 IBS: 0.21081180496529733
Fold 5 IBS: 0.18981091835099756
[I 2024-04-14 19:08:51,456] Trial 0 finished with value: 0.199009791555185 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.199009791555185.
Fold 1 IBS: 0.26102096459211444
Fold 2 IBS: 0.17546310911346108
Fold 3 IBS: 0.15727383805312153
Fold 4 IBS: 0.21071976990897665
Fold 5 IBS: 0.18981867332992686
[I 2024-04-14 19:08:52,398] Trial 1 finished with value: 0.1988592709995201 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.1988592709995201.
Fold 1 IBS: 0.26095653589842793
Fold 2 IBS: 0.175541884629451
Fold 3 IBS: 0.15722363282072982
Fold 4 IBS: 0.21070881524532029
Fold 5 IBS: 0.18972106375483969
[I 2024-04-14 19:08:53,140] Trial 2 finished with value: 0.19883038646975373 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.26137467563549804
Fold 2 IBS: 0.1754746474365563
Fold 3 IBS: 0.15744548828329702
Fold 4 IBS: 0.21078927336522013
Fold 5 IBS: 0.189766304697201
[I 2024-04-14 19:08:53,725] Trial 3 finished with value: 0.19897007788355453 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.26153535196607575
Fold 2 IBS: 0.1754437838288291
Fold 3 IBS: 0.15755596938581298
Fold 4 IBS: 0.21081125358863168
Fold 5 IBS: 0.18983131997302355
[I 2024-04-14 19:08:54,312] Trial 4 finished with value: 0.1990355357484746 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.26121184423742
Fold 2 IBS: 0.1755282928480119
Fold 3 IBS: 0.1573610794197778
Fold 4 IBS: 0.21076928204059217
Fold 5 IBS: 0.18980202737839116
[I 2024-04-14 19:08:54,919] Trial 5 finished with value: 0.19893450518483863 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.26178658616108924
Fold 2 IBS: 0.17541596456280298
Fold 3 IBS: 0.15756425151838258
Fold 4 IBS: 0.21083441636018035
Fold 5 IBS: 0.18989726024316206
[I 2024-04-14 19:08:55,577] Trial 6 finished with value: 0.19909969576912348 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.2614896791014327
Fold 2 IBS: 0.17547051011200462
Fold 3 IBS: 0.15746561640517148
Fold 4 IBS: 0.21081208490258202
Fold 5 IBS: 0.18979835550566557
[I 2024-04-14 19:08:56,075] Trial 7 finished with value: 0.19900724920537133 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.2612804605058633
Fold 2 IBS: 0.1754419160893097
Fold 3 IBS: 0.15740190523964226
Fold 4 IBS: 0.2107661707735715
Fold 5 IBS: 0.18978336360193546
[I 2024-04-14 19:08:56,745] Trial 8 finished with value: 0.19893476324206444 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.2611397669033172
Fold 2 IBS: 0.1754615713241546
Fold 3 IBS: 0.1573032245792605
Fold 4 IBS: 0.21075120445282478
Fold 5 IBS: 0.18973767588961893
[I 2024-04-14 19:08:57,245] Trial 9 finished with value: 0.1988786886298352 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.19883038646975373.
Fold 1 IBS: 0.2608149391155064
Fold 2 IBS: 0.17529446522320224
Fold 3 IBS: 0.15705160079815433
Fold 4 IBS: 0.21063769809123442
Fold 5 IBS: 0.18969460822061532
[I 2024-04-14 19:08:58,021] Trial 10 finished with value: 0.19869866228974256 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.19869866228974256.
Fold 1 IBS: 0.2465209494477647
Fold 2 IBS: 0.2304690476956912
Fold 3 IBS: 0.22890723397602178
Fold 4 IBS: 0.24063811314572492
Fold 5 IBS: 0.22838578057464493
[I 2024-04-14 19:08:58,216] Trial 11 finished with value: 0.2349842249679695 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.19869866228974256.
Fold 1 IBS: 0.26081389410336775
Fold 2 IBS: 0.17529496890045845
Fold 3 IBS: 0.15705215621062232
Fold 4 IBS: 0.21063774108573224
Fold 5 IBS: 0.18969336237257817
[I 2024-04-14 19:08:58,795] Trial 12 finished with value: 0.1986984245345518 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.24705210330097865
Fold 2 IBS: 0.23161650505065082
Fold 3 IBS: 0.22895760413999452
Fold 4 IBS: 0.24161570615327357
Fold 5 IBS: 0.22912468005824393
[I 2024-04-14 19:08:58,992] Trial 13 finished with value: 0.2356733197406283 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.2608567543401272
Fold 2 IBS: 0.17539103463540034
Fold 3 IBS: 0.1571615065933417
Fold 4 IBS: 0.21066853269460686
Fold 5 IBS: 0.1897278516543643
[I 2024-04-14 19:08:59,549] Trial 14 finished with value: 0.19876113598356807 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.2608695389814627
Fold 2 IBS: 0.17538569347587826
Fold 3 IBS: 0.15714605073686305
Fold 4 IBS: 0.21066801441558847
Fold 5 IBS: 0.18974377121929978
[I 2024-04-14 19:09:00,209] Trial 15 finished with value: 0.19876261376581844 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.26087344265405465
Fold 2 IBS: 0.17533652371606998
Fold 3 IBS: 0.1571273763238111
Fold 4 IBS: 0.21066485127113585
Fold 5 IBS: 0.18975607821618434
[I 2024-04-14 19:09:00,847] Trial 16 finished with value: 0.1987516544362512 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.2610362459335142
Fold 2 IBS: 0.1754509061332231
Fold 3 IBS: 0.15726669085351822
Fold 4 IBS: 0.21071934264862116
Fold 5 IBS: 0.18983402845890304
[I 2024-04-14 19:09:01,441] Trial 17 finished with value: 0.19886144280555593 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.26076194056219715
Fold 2 IBS: 0.1751955392973939
Fold 3 IBS: 0.22887041855208648
Fold 4 IBS: 0.23581132511095965
Fold 5 IBS: 0.18968741303573383
[I 2024-04-14 19:09:01,874] Trial 18 finished with value: 0.21806532731167422 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.26179631723652197
Fold 2 IBS: 0.17541067675880168
Fold 3 IBS: 0.15756045354413964
Fold 4 IBS: 0.21083445042171095
Fold 5 IBS: 0.18990478421886084
[I 2024-04-14 19:09:02,365] Trial 19 finished with value: 0.19910133643600703 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.26100548205567964
Fold 2 IBS: 0.17549517266250797
Fold 3 IBS: 0.15719819043281158
Fold 4 IBS: 0.2107070964018152
Fold 5 IBS: 0.18976817627886303
[I 2024-04-14 19:09:02,889] Trial 20 finished with value: 0.19883482356633547 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.2608094482337777
Fold 2 IBS: 0.17527659417261443
Fold 3 IBS: 0.1571068136086022
Fold 4 IBS: 0.2106480524965429
Fold 5 IBS: 0.18976216031162352
[I 2024-04-14 19:09:03,438] Trial 21 finished with value: 0.19872061376463215 and parameters: {'l1_ratio': 0.10825799833043775}. Best is trial 12 with value: 0.1986984245345518.
Fold 1 IBS: 0.26083014713459524
Fold 2 IBS: 0.17523274128567
Fold 3 IBS: 0.15707666284968502
Fold 4 IBS: 0.21064091820131725
Fold 5 IBS: 0.18969485236940062
[I 2024-04-14 19:09:03,997] Trial 22 finished with value: 0.1986950643681336 and parameters: {'l1_ratio': 0.10159828709381563}. Best is trial 22 with value: 0.1986950643681336.
Fold 1 IBS: 0.2609285938497083
Fold 2 IBS: 0.17551791621455312
Fold 3 IBS: 0.15719518562058682
Fold 4 IBS: 0.21069479671514252
Fold 5 IBS: 0.189737897018467
[I 2024-04-14 19:09:04,533] Trial 23 finished with value: 0.19881487788369154 and parameters: {'l1_ratio': 0.20521786879010379}. Best is trial 22 with value: 0.1986950643681336.
Fold 1 IBS: 0.26111755135297193
Fold 2 IBS: 0.175449803240711
Fold 3 IBS: 0.15727944118264817
Fold 4 IBS: 0.21073348405315032
Fold 5 IBS: 0.18973210962949702
[I 2024-04-14 19:09:05,041] Trial 24 finished with value: 0.19886247789179567 and parameters: {'l1_ratio': 0.3389201479305571}. Best is trial 22 with value: 0.1986950643681336.

Fold 1 IBS: 0.2606821812817422
Fold 2 IBS: 0.22738698140772204
Fold 3 IBS: 0.22888824044815342
Fold 4 IBS: 0.23799375816123436
Fold 5 IBS: 0.2263768358729022
[I 2024-04-14 19:09:05,362] Trial 25 finished with value: 0.23626559943435083 and parameters: {'l1_ratio': 0.03981317955666948}. Best is trial 22 with value: 0.1986950643681336.
Fold 1 IBS: 0.2609154703081647
Fold 2 IBS: 0.17545827162195377
Fold 3 IBS: 0.1571670244831515
Fold 4 IBS: 0.21068267014118114
Fold 5 IBS: 0.18976999274146958
[I 2024-04-14 19:09:06,028] Trial 26 finished with value: 0.19879868585918412 and parameters: {'l1_ratio': 0.18783928730207888}. Best is trial 22 with value: 0.1986950643681336.
Fold 1 IBS: 0.26079022916853595
Fold 2 IBS: 0.17520799790036354
Fold 3 IBS: 0.15704865024719103
Fold 4 IBS: 0.21063208131503916
Fold 5 IBS: 0.18970289615968972
[I 2024-04-14 19:09:06,663] Trial 27 finished with value: 0.19867637095816387 and parameters: {'l1_ratio': 0.07505393448412474}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2611165173478533
Fold 2 IBS: 0.17545263620173251
Fold 3 IBS: 0.15728115182858451
Fold 4 IBS: 0.2107335855279713
Fold 5 IBS: 0.18972849291165622
[I 2024-04-14 19:09:07,236] Trial 28 finished with value: 0.19886247676355956 and parameters: {'l1_ratio': 0.33764866886941186}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26169495764016854
Fold 2 IBS: 0.17546356015809825
Fold 3 IBS: 0.15759775996267733
Fold 4 IBS: 0.21083573706579217
Fold 5 IBS: 0.18983885175802914
[I 2024-04-14 19:09:07,903] Trial 29 finished with value: 0.19908617331695308 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26145253267164004
Fold 2 IBS: 0.17539412431266585
Fold 3 IBS: 0.15749407080477226
Fold 4 IBS: 0.21081349682193792
Fold 5 IBS: 0.18986385460023322
[I 2024-04-14 19:09:08,868] Trial 30 finished with value: 0.19900361584224988 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608189342370397
Fold 2 IBS: 0.1752051514792947
Fold 3 IBS: 0.15706330254632367
Fold 4 IBS: 0.21063415018258544
Fold 5 IBS: 0.18968477938286082
[I 2024-04-14 19:09:09,630] Trial 31 finished with value: 0.1986812635656209 and parameters: {'l1_ratio': 0.09232011433900482}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2607381564615499
Fold 2 IBS: 0.17523108616574223
Fold 3 IBS: 0.2288702625233257
Fold 4 IBS: 0.21062483610848354
Fold 5 IBS: 0.18976028144416615
[I 2024-04-14 19:09:10,254] Trial 32 finished with value: 0.21304492454065352 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2610143528038492
Fold 2 IBS: 0.17554799570653135
Fold 3 IBS: 0.1572394457598848
Fold 4 IBS: 0.2107215435985467
Fold 5 IBS: 0.18972695491598265
[I 2024-04-14 19:09:10,930] Trial 33 finished with value: 0.19885005855695895 and parameters: {'l1_ratio': 0.25883597019334637}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26090656417863506
Fold 2 IBS: 0.1754042766373625
Fold 3 IBS: 0.1571406980765673
Fold 4 IBS: 0.21067107094478218
Fold 5 IBS: 0.18979820306664782
[I 2024-04-14 19:09:11,892] Trial 34 finished with value: 0.19878416258079898 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2470990848237955
Fold 2 IBS: 0.23171847998307823
Fold 3 IBS: 0.2289632573563859
Fold 4 IBS: 0.24170221813600085
Fold 5 IBS: 0.2291899707695389
[I 2024-04-14 19:09:12,224] Trial 35 finished with value: 0.23573460221375986 and parameters: {'l1_ratio': 0.002421851191056451}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608170943890571
Fold 2 IBS: 0.1752380893411865
Fold 3 IBS: 0.15708277834068074
Fold 4 IBS: 0.21064138540392094
Fold 5 IBS: 0.18967960845267598
[I 2024-04-14 19:09:13,022] Trial 36 finished with value: 0.19869179118550423 and parameters: {'l1_ratio': 0.10030053483774418}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2610243351805584
Fold 2 IBS: 0.17546041680658098
Fold 3 IBS: 0.15727246112286225
Fold 4 IBS: 0.21071967194425154
Fold 5 IBS: 0.18982188153862822
[I 2024-04-14 19:09:13,816] Trial 37 finished with value: 0.19885975331857628 and parameters: {'l1_ratio': 0.28716984151466923}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2609371278775953
Fold 2 IBS: 0.17551079324569935
Fold 3 IBS: 0.1571913117293251
Fold 4 IBS: 0.2106945155832034
Fold 5 IBS: 0.189746819984547
[I 2024-04-14 19:09:14,619] Trial 38 finished with value: 0.19881611368407404 and parameters: {'l1_ratio': 0.2069590149454673}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2613826281588071
Fold 2 IBS: 0.17547076267289177
Fold 3 IBS: 0.15744196990548115
Fold 4 IBS: 0.21078909359423867
Fold 5 IBS: 0.18977337241660205
[I 2024-04-14 19:09:15,276] Trial 39 finished with value: 0.19897156534960414 and parameters: {'l1_ratio': 0.5561256026976026}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26108748918983
Fold 2 IBS: 0.17542784178470813
Fold 3 IBS: 0.1572671992835123
Fold 4 IBS: 0.2107327082997043
Fold 5 IBS: 0.18975592251188347
[I 2024-04-14 19:09:15,890] Trial 40 finished with value: 0.19885423221392765 and parameters: {'l1_ratio': 0.3490957813781693}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608862925230855
Fold 2 IBS: 0.17532285584335394
Fold 3 IBS: 0.15707353756536818
Fold 4 IBS: 0.21064716355810803
Fold 5 IBS: 0.18972136358295835
[I 2024-04-14 19:09:16,717] Trial 41 finished with value: 0.19873024261457478 and parameters: {'l1_ratio': 0.11577418005988488}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2607469175953686
Fold 2 IBS: 0.1751798106062574
Fold 3 IBS: 0.22887195216820275
Fold 4 IBS: 0.23630134175840536
Fold 5 IBS: 0.18968671702792647
[I 2024-04-14 19:09:17,242] Trial 42 finished with value: 0.2181573478312321 and parameters: {'l1_ratio': 0.06038960752768997}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2607967655347636
Fold 2 IBS: 0.17524660664242522
Fold 3 IBS: 0.1570934432008294
Fold 4 IBS: 0.21064202928118353
Fold 5 IBS: 0.18977391080184605
[I 2024-04-14 19:09:17,956] Trial 43 finished with value: 0.19871055109220956 and parameters: {'l1_ratio': 0.09831187915022918}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608145490874563
Fold 2 IBS: 0.17535599408915445
Fold 3 IBS: 0.1571178872725466
Fold 4 IBS: 0.21067286588966672
Fold 5 IBS: 0.189707825605881
[I 2024-04-14 19:09:18,896] Trial 44 finished with value: 0.19873382438894102 and parameters: {'l1_ratio': 0.15716109125636546}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26071961165291324
Fold 2 IBS: 0.22644700506736776
Fold 3 IBS: 0.22887843886267706
Fold 4 IBS: 0.23718581969299707
Fold 5 IBS: 0.18968071564410974
[I 2024-04-14 19:09:19,456] Trial 45 finished with value: 0.22858231818401298 and parameters: {'l1_ratio': 0.049304935017305714}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2616459120825593
Fold 2 IBS: 0.17538222406873163
Fold 3 IBS: 0.1575111534969429
Fold 4 IBS: 0.2108367464969653
Fold 5 IBS: 0.18978630179170417
[I 2024-04-14 19:09:20,141] Trial 46 finished with value: 0.19903246758738063 and parameters: {'l1_ratio': 0.8167652444349325}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2610089920190088
Fold 2 IBS: 0.17549221693749475
Fold 3 IBS: 0.1571963191998528
Fold 4 IBS: 0.2107069854244297
Fold 5 IBS: 0.1897717084769595
[I 2024-04-14 19:09:20,933] Trial 47 finished with value: 0.1988352444115491 and parameters: {'l1_ratio': 0.23971145636476637}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26086812787263736
Fold 2 IBS: 0.17525658325367752
Fold 3 IBS: 0.1570829626953587
Fold 4 IBS: 0.21064781952656014
Fold 5 IBS: 0.1897000338134998
[I 2024-04-14 19:09:21,836] Trial 48 finished with value: 0.1987111054323467 and parameters: {'l1_ratio': 0.11366529051765155}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2612134304521834
Fold 2 IBS: 0.1754884988694879
Fold 3 IBS: 0.15733730767681156
Fold 4 IBS: 0.21076783182678108

Fold 5 IBS: 0.1898459598326078
[I 2024-04-14 19:09:22,435] Trial 49 finished with value: 0.19893060573157434 and parameters: {'l1_ratio': 0.4477016529538363}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2457151388464811
Fold 2 IBS: 0.22873767739586323
Fold 3 IBS: 0.2288755391653703
Fold 4 IBS: 0.23915447826885858
Fold 5 IBS: 0.22726120269929223
[I 2024-04-14 19:09:22,655] Trial 50 finished with value: 0.23394880727517312 and parameters: {'l1_ratio': 0.02711267007130712}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26084493493469907
Fold 2 IBS: 0.17528004420872453
Fold 3 IBS: 0.15703511863648179
Fold 4 IBS: 0.21063649084213493
Fold 5 IBS: 0.1897265008034076
[I 2024-04-14 19:09:23,422] Trial 51 finished with value: 0.19870461788508959 and parameters: {'l1_ratio': 0.08640058638065554}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608817355366732
Fold 2 IBS: 0.17541335158964097
Fold 3 IBS: 0.15714376879533745
Fold 4 IBS: 0.21067184363919256
Fold 5 IBS: 0.18977298386398317
[I 2024-04-14 19:09:24,051] Trial 52 finished with value: 0.19877673668496545 and parameters: {'l1_ratio': 0.1677052436763387}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608632749400004
Fold 2 IBS: 0.17534049771459265
Fold 3 IBS: 0.15713251845816048
Fold 4 IBS: 0.21066526591410414
Fold 5 IBS: 0.18974504354817617
[I 2024-04-14 19:09:24,697] Trial 53 finished with value: 0.1987493201150068 and parameters: {'l1_ratio': 0.1332942954625656}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608110890919344
Fold 2 IBS: 0.17526663047397056
Fold 3 IBS: 0.15703601757163266
Fold 4 IBS: 0.21063125358227963
Fold 5 IBS: 0.18972438232711863
[I 2024-04-14 19:09:25,387] Trial 54 finished with value: 0.1986938746093872 and parameters: {'l1_ratio': 0.0766220227537334}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26074919393915363
Fold 2 IBS: 0.22672246554492498
Fold 3 IBS: 0.22888094206599943
Fold 4 IBS: 0.23742256088077443
Fold 5 IBS: 0.22593991956271228
[I 2024-04-14 19:09:25,817] Trial 55 finished with value: 0.23594301639871293 and parameters: {'l1_ratio': 0.0464642330671326}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2609409806927993
Fold 2 IBS: 0.17549874242660074
Fold 3 IBS: 0.157188900203346
Fold 4 IBS: 0.2106943412842216
Fold 5 IBS: 0.18975244723939014
[I 2024-04-14 19:09:26,848] Trial 56 finished with value: 0.19881508236927153 and parameters: {'l1_ratio': 0.20805861659750413}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.24686867449939795
Fold 2 IBS: 0.23121972700699894
Fold 3 IBS: 0.22893795560394717
Fold 4 IBS: 0.24127810464133093
Fold 5 IBS: 0.22886969148005673
[I 2024-04-14 19:09:27,273] Trial 57 finished with value: 0.23543483064634635 and parameters: {'l1_ratio': 0.00626942071754627}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26081037568801696
Fold 2 IBS: 0.17520870411534245
Fold 3 IBS: 0.15706777479271228
Fold 4 IBS: 0.2106344452335035
Fold 5 IBS: 0.18969408031079624
[I 2024-04-14 19:09:28,185] Trial 58 finished with value: 0.19868307602807428 and parameters: {'l1_ratio': 0.09154374107186612}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26087444656159897
Fold 2 IBS: 0.17538380316379645
Fold 3 IBS: 0.15714374997836691
Fold 4 IBS: 0.2106678312709171
Fold 5 IBS: 0.18974751153253389
[I 2024-04-14 19:09:29,016] Trial 59 finished with value: 0.19876346850144266 and parameters: {'l1_ratio': 0.14617073334935415}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608196034273222
Fold 2 IBS: 0.17526250007540067
Fold 3 IBS: 0.15703247253901811
Fold 4 IBS: 0.21063091778271711
Fold 5 IBS: 0.18973449917489962
[I 2024-04-14 19:09:29,701] Trial 60 finished with value: 0.19869599859987155 and parameters: {'l1_ratio': 0.07727832211191225}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26075914958564284
Fold 2 IBS: 0.17527987708030315
Fold 3 IBS: 0.15703493375985592
Fold 4 IBS: 0.21063647682662018
Fold 5 IBS: 0.18972692308269387
[I 2024-04-14 19:09:30,415] Trial 61 finished with value: 0.19868747206702317 and parameters: {'l1_ratio': 0.08643153547056362}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608768899762432
Fold 2 IBS: 0.1752530962191265
Fold 3 IBS: 0.15707843919335446
Fold 4 IBS: 0.21064750158759976
Fold 5 IBS: 0.1897103174999898
[I 2024-04-14 19:09:31,041] Trial 62 finished with value: 0.19871324889526273 and parameters: {'l1_ratio': 0.11467420055217481}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.24527442394711615
Fold 2 IBS: 0.22779379761624646
Fold 3 IBS: 0.22888451764295314
Fold 4 IBS: 0.238343397116115
Fold 5 IBS: 0.22664376188966975
[I 2024-04-14 19:09:31,298] Trial 63 finished with value: 0.23338797964242008 and parameters: {'l1_ratio': 0.03587631999008975}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26089953199595334
Fold 2 IBS: 0.175464744140847
Fold 3 IBS: 0.15717523888327348
Fold 4 IBS: 0.21068321937844747
Fold 5 IBS: 0.1897516530226367
[I 2024-04-14 19:09:31,885] Trial 64 finished with value: 0.19879487748423158 and parameters: {'l1_ratio': 0.18462986444183266}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2610425230482409
Fold 2 IBS: 0.17552264216102845
Fold 3 IBS: 0.1572254925359841
Fold 4 IBS: 0.21072057382034756
Fold 5 IBS: 0.18975625298729995
[I 2024-04-14 19:09:32,562] Trial 65 finished with value: 0.19885349691058019 and parameters: {'l1_ratio': 0.26643093229649334}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26079293384025337
Fold 2 IBS: 0.17524820445342218
Fold 3 IBS: 0.15709469194134976
Fold 4 IBS: 0.21064217081064007
Fold 5 IBS: 0.18976967412531207
[I 2024-04-14 19:09:33,214] Trial 66 finished with value: 0.19870953503419547 and parameters: {'l1_ratio': 0.09794901471945092}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608486765510033
Fold 2 IBS: 0.1753734656494725
Fold 3 IBS: 0.15714010826481112
Fold 4 IBS: 0.21066532197255078
Fold 5 IBS: 0.18977371096479131
[I 2024-04-14 19:09:33,995] Trial 67 finished with value: 0.1987602566805258 and parameters: {'l1_ratio': 0.14986455450872263}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2607500308064527
Fold 2 IBS: 0.1752014862139084
Fold 3 IBS: 0.2288772479113183
Fold 4 IBS: 0.23706120099273031
Fold 5 IBS: 0.1897176923158906
[I 2024-04-14 19:09:34,552] Trial 68 finished with value: 0.21832153164806006 and parameters: {'l1_ratio': 0.050820911942303246}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2609460340850873
Fold 2 IBS: 0.17555226866361165
Fold 3 IBS: 0.15722888135330354
Fold 4 IBS: 0.21069204817350168
Fold 5 IBS: 0.1897101726995298
[I 2024-04-14 19:09:35,203] Trial 69 finished with value: 0.1988258809950068 and parameters: {'l1_ratio': 0.22459254035217385}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608400129447334
Fold 2 IBS: 0.17535037880725818
Fold 3 IBS: 0.1571431651090372
Fold 4 IBS: 0.21065316791711886
Fold 5 IBS: 0.18972952402264587
[I 2024-04-14 19:09:35,870] Trial 70 finished with value: 0.1987432497601587 and parameters: {'l1_ratio': 0.13031688521890655}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26083916542850216
Fold 2 IBS: 0.1752827860387564
Fold 3 IBS: 0.15703872476873892
Fold 4 IBS: 0.2106367116343013
Fold 5 IBS: 0.18973907533334577
[I 2024-04-14 19:09:36,566] Trial 71 finished with value: 0.19870729264072892 and parameters: {'l1_ratio': 0.0858963853156825}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26079076826413916
Fold 2 IBS: 0.17524825470989278
Fold 3 IBS: 0.22887026204421002
Fold 4 IBS: 0.2356659196651391
Fold 5 IBS: 0.18971940910944377
[I 2024-04-14 19:09:37,089] Trial 72 finished with value: 0.21805892275856498 and parameters: {'l1_ratio': 0.06885314943838546}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.246289237956768
Fold 2 IBS: 0.22997016104717674
Fold 3 IBS: 0.22889222956212643
Fold 4 IBS: 0.24021163368025542
Fold 5 IBS: 0.22806290206156737
[I 2024-04-14 19:09:37,381] Trial 73 finished with value: 0.2346852328615788 and parameters: {'l1_ratio': 0.016389691899776605}. Best is trial 27 with value: 0.19867637095816387.

Fold 1 IBS: 0.2608575610544787
Fold 2 IBS: 0.17539348844468203
Fold 3 IBS: 0.15719466962952938
Fold 4 IBS: 0.2106838446583365
Fold 5 IBS: 0.1897136590361089
[I 2024-04-14 19:09:38,070] Trial 74 finished with value: 0.19876864456462712 and parameters: {'l1_ratio': 0.17727321357700984}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2607981994290502
Fold 2 IBS: 0.1752317549019866
Fold 3 IBS: 0.15706047451460672
Fold 4 IBS: 0.21062862657188466
Fold 5 IBS: 0.18967484364348253
[I 2024-04-14 19:09:38,651] Trial 75 finished with value: 0.19867877981220214 and parameters: {'l1_ratio': 0.08245157736410111}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608709289390057
Fold 2 IBS: 0.17529454472507108
Fold 3 IBS: 0.1571042565950744
Fold 4 IBS: 0.21065490271630477
Fold 5 IBS: 0.18979072613153178
[I 2024-04-14 19:09:39,204] Trial 76 finished with value: 0.19874307182139755 and parameters: {'l1_ratio': 0.12378281768481025}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.24565851054047413
Fold 2 IBS: 0.22861631857434933
Fold 3 IBS: 0.228875580245069
Fold 4 IBS: 0.2390501354717807
Fold 5 IBS: 0.2271819732016614
[I 2024-04-14 19:09:39,401] Trial 77 finished with value: 0.23387650360666687 and parameters: {'l1_ratio': 0.028211532473833734}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.24723025702907428
Fold 2 IBS: 0.2320032996407992
Fold 3 IBS: 0.2289796897545999
Fold 4 IBS: 0.24194375631795537
Fold 5 IBS: 0.22937219998540567
[I 2024-04-14 19:09:39,602] Trial 78 finished with value: 0.23590584054556687 and parameters: {'l1_ratio': 0.00027370336237243775}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2613894175596227
Fold 2 IBS: 0.17543212971038188
Fold 3 IBS: 0.15741664878554426
Fold 4 IBS: 0.2107878357793104
Fold 5 IBS: 0.18981690514638588
[I 2024-04-14 19:09:40,105] Trial 79 finished with value: 0.198968587396249 and parameters: {'l1_ratio': 0.5933865341035967}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26079458436658454
Fold 2 IBS: 0.17521538635899933
Fold 3 IBS: 0.15707636254662927
Fold 4 IBS: 0.2106349967786492
Fold 5 IBS: 0.18977584562404665
[I 2024-04-14 19:09:40,669] Trial 80 finished with value: 0.19869943513498178 and parameters: {'l1_ratio': 0.09014043733048978}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26080185091166935
Fold 2 IBS: 0.17521813166643316
Fold 3 IBS: 0.22887094748462827
Fold 4 IBS: 0.23604121513540835
Fold 5 IBS: 0.1897492518314113
[I 2024-04-14 19:09:41,092] Trial 81 finished with value: 0.21813627940591007 and parameters: {'l1_ratio': 0.06380093044101481}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608114812933693
Fold 2 IBS: 0.17524040235982172
Fold 3 IBS: 0.1570856832938731
Fold 4 IBS: 0.2106415882574755
Fold 5 IBS: 0.1897889889013088
[I 2024-04-14 19:09:41,651] Trial 82 finished with value: 0.19871362882116966 and parameters: {'l1_ratio': 0.09975120868531753}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26080625249573997
Fold 2 IBS: 0.1752406196800204
Fold 3 IBS: 0.2288702359204191
Fold 4 IBS: 0.2106254798086822
Fold 5 IBS: 0.18973701700175089
[I 2024-04-14 19:09:42,185] Trial 83 finished with value: 0.21305592098132248 and parameters: {'l1_ratio': 0.06992308092146007}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.26153913195829387
Fold 2 IBS: 0.17544158740277652
Fold 3 IBS: 0.15755438547351405
Fold 4 IBS: 0.21081119062739384
Fold 5 IBS: 0.1898343288625456
[I 2024-04-14 19:09:42,649] Trial 84 finished with value: 0.1990361248649048 and parameters: {'l1_ratio': 0.7224958901789822}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2608653301596985
Fold 2 IBS: 0.17536733305541752
Fold 3 IBS: 0.15713197227401357
Fold 4 IBS: 0.21067007644748242
Fold 5 IBS: 0.18979141951928677
[I 2024-04-14 19:09:43,219] Trial 85 finished with value: 0.19876522629117976 and parameters: {'l1_ratio': 0.1523311399437369}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2609516308394176
Fold 2 IBS: 0.1754457443737549
Fold 3 IBS: 0.1571410844102275
Fold 4 IBS: 0.21068152502018547
Fold 5 IBS: 0.18980668833316222
[I 2024-04-14 19:09:43,770] Trial 86 finished with value: 0.1988053345953495 and parameters: {'l1_ratio': 0.19495527725932302}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.24522780621304902
Fold 2 IBS: 0.2276940132266055
Fold 3 IBS: 0.2288866711109763
Fold 4 IBS: 0.2382576458318661
Fold 5 IBS: 0.22657833189841875
[I 2024-04-14 19:09:43,987] Trial 87 finished with value: 0.23332889365618312 and parameters: {'l1_ratio': 0.036832762438577894}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2609055317141403
Fold 2 IBS: 0.17535728949415644
Fold 3 IBS: 0.15708673530341247
Fold 4 IBS: 0.21065374525195754
Fold 5 IBS: 0.18971069077521302
[I 2024-04-14 19:09:44,775] Trial 88 finished with value: 0.19874279850777596 and parameters: {'l1_ratio': 0.12818348925399892}. Best is trial 27 with value: 0.19867637095816387.
Fold 1 IBS: 0.2607696528831088
Fold 2 IBS: 0.17521688272632624
Fold 3 IBS: 0.15706029288134285
Fold 4 IBS: 0.21062373705604026
Fold 5 IBS: 0.18967756718311796
[I 2024-04-14 19:09:45,968] Trial 89 finished with value: 0.19866962654598722 and parameters: {'l1_ratio': 0.07349840790755927}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.26082192118205233
Fold 2 IBS: 0.17527140214409442
Fold 3 IBS: 0.15710098119994131
Fold 4 IBS: 0.21064906003846856
Fold 5 IBS: 0.1897757631113294
[I 2024-04-14 19:09:46,785] Trial 90 finished with value: 0.1987238255351772 and parameters: {'l1_ratio': 0.10960201127093003}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.2607607438086149
Fold 2 IBS: 0.17519607961106604
Fold 3 IBS: 0.22887042758437748
Fold 4 IBS: 0.23581706487787546
Fold 5 IBS: 0.18968599904805247
[I 2024-04-14 19:09:47,226] Trial 91 finished with value: 0.21806606298599726 and parameters: {'l1_ratio': 0.06679943020749546}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.2608738673653788
Fold 2 IBS: 0.17541616595748039
Fold 3 IBS: 0.15715651054997168
Fold 4 IBS: 0.21067208332560292
Fold 5 IBS: 0.18976513321056218
[I 2024-04-14 19:09:47,907] Trial 92 finished with value: 0.1987767520817992 and parameters: {'l1_ratio': 0.16641301179776113}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.260771083515699
Fold 2 IBS: 0.17524402051694504
Fold 3 IBS: 0.15707567175236384
Fold 4 IBS: 0.2106295984693902
Fold 5 IBS: 0.189761776391369
[I 2024-04-14 19:09:48,637] Trial 93 finished with value: 0.19869643012915345 and parameters: {'l1_ratio': 0.08023770763594035}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.24585772229780903
Fold 2 IBS: 0.22904338590846327
Fold 3 IBS: 0.2288768223163113
Fold 4 IBS: 0.23941713625898176
Fold 5 IBS: 0.22746056549859764
[I 2024-04-14 19:09:48,835] Trial 94 finished with value: 0.23413112645603257 and parameters: {'l1_ratio': 0.02437971950460533}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.2617644494370255
Fold 2 IBS: 0.1754280669346635
Fold 3 IBS: 0.15757280518683545
Fold 4 IBS: 0.2108349011035
Fold 5 IBS: 0.18989303685284514
[I 2024-04-14 19:09:49,663] Trial 95 finished with value: 0.1990986519029739 and parameters: {'l1_ratio': 0.9540051824565325}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.2607765756677597
Fold 2 IBS: 0.22659805050743248
Fold 3 IBS: 0.22887977268323817
Fold 4 IBS: 0.2373156283901965
Fold 5 IBS: 0.225858004889677
[I 2024-04-14 19:09:50,248] Trial 96 finished with value: 0.23588560642766074 and parameters: {'l1_ratio': 0.04774104454003504}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.2613095694298431
Fold 2 IBS: 0.1754215378012241
Fold 3 IBS: 0.15738883241886473
Fold 4 IBS: 0.210765508008979
Fold 5 IBS: 0.18980974592634164
[I 2024-04-14 19:09:50,890] Trial 97 finished with value: 0.19893903871705051 and parameters: {'l1_ratio': 0.4965881146918674}. Best is trial 89 with value: 0.19866962654598722.
Fold 1 IBS: 0.2607835733209619
Fold 2 IBS: 0.175252123058763
Fold 3 IBS: 0.15709956320788573
Fold 4 IBS: 0.21064250835254894
Fold 5 IBS: 0.18975933283378463
[I 2024-04-14 19:09:51,693] Trial 98 finished with value: 0.19870742015478887 and parameters: {'l1_ratio': 0.09707217353740726}. Best is trial 89 with value: 0.19866962654598722.

Fold 1 IBS: 0.26091206231297664
Fold 2 IBS: 0.17532142366602946
Fold 3 IBS: 0.15710800910675635
Fold 4 IBS: 0.21066952588141638
Fold 5 IBS: 0.18970528727277605
[I 2024-04-14 19:09:52,528] Trial 99 finished with value: 0.198743261647991 and parameters: {'l1_ratio': 0.1400329988695925}. Best is trial 89 with value: 0.19866962654598722.


* Best trial for IBS:
 FrozenTrial(number=89, state=TrialState.COMPLETE, values=[0.19866962654598722], datetime_start=datetime.datetime(2024, 4, 14, 19, 9, 44, 790063), datetime_complete=datetime.datetime(2024, 4, 14, 19, 9, 45, 967885), params={'l1_ratio': 0.07349840790755927}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=89, value=None)


* Best Score for IBS:
 0.19866962654598722

In [48]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.705
train_ibs:  0.199

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08382735104105443)

test_cindex : 0.527

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.07349840790755927)

test_ibs:  0.308

In [52]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:09:53,190] A new study created in memory with name: no-name-bf3e278e-07d7-45d8-a879-f5d1d6a0d99c

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6931330472103004
[I 2024-04-14 19:10:02,463] Trial 0 finished with value: 0.7048122494993283 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 19:10:08,215] Trial 1 finished with value: 0.7045401103615428 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 19:10:14,315] Trial 2 finished with value: 0.7038559215138825 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:10:15,495] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:10:16,865] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7048122494993283.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 19:10:21,791] Trial 5 finished with value: 0.7065789011065878 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 19:10:27,463] Trial 6 finished with value: 0.6939192369651451 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:10:30,355] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 19:10:39,801] Trial 8 finished with value: 0.5330472103004291 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 19:10:45,504] Trial 9 finished with value: 0.7056557357443756 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:10:46,166] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 19:10:48,998] Trial 11 finished with value: 0.7022979418058652 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.9866547731576396, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018098423978521135, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 19:11:00,238] Trial 12 finished with value: 0.7013323984593981 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.8392165520631284, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08506650508113567, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 19:11:06,412] Trial 13 finished with value: 0.6893270242731889 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.4760095384782845, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008606277463368957, 'warm_start': False}. Best is trial 5 with value: 0.7065789011065878.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:11:08,465] Trial 14 finished with value: 0.7773044783671873 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1584235940276062, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7868217054263565

Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:11:09,979] Trial 15 finished with value: 0.7770080066545406 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.834513235692611, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1695220400209786, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:11:11,125] Trial 16 finished with value: 0.7738213229226775 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.804668454581114, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17004822192434552, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 19:11:12,540] Trial 17 finished with value: 0.77214163545148 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.8699768148803853, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19387458942106575, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:11:12,925] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.7252075252214651, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 19:11:14,604] Trial 19 finished with value: 0.7465432746830285 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.9892276103612732, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1022133684431561, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6901140684410646
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 19:11:15,328] Trial 20 finished with value: 0.6896452628649035 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.5018171832362744, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24858261413121135, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:11:16,392] Trial 21 finished with value: 0.7747954994518816 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 128, 'oob_score': True, 'max_samples': 0.804171251859245, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1580984841046789, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:11:17,748] Trial 22 finished with value: 0.7755485234698857 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.7798651905375668, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14609188473654175, 'warm_start': True}. Best is trial 14 with value: 0.7773044783671873.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:11:19,846] Trial 23 finished with value: 0.7838056739825504 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.6915006463773689, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12906697502800496, 'warm_start': True}. Best is trial 23 with value: 0.7838056739825504.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7510729613733905
[I 2024-04-14 19:11:22,281] Trial 24 finished with value: 0.7333004851794984 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.665565318795521, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22028324508793534, 'warm_start': True}. Best is trial 23 with value: 0.7838056739825504.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:11:24,475] Trial 25 finished with value: 0.7890416108092421 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.8918499102545804, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12502301449842818, 'warm_start': True}. Best is trial 25 with value: 0.7890416108092421.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:11:27,065] Trial 26 finished with value: 0.7940149960169461 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.9083119442021096, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 26 with value: 0.7940149960169461.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:11:29,668] Trial 27 finished with value: 0.7977677253229423 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.9274965245988948, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07009172976674138, 'warm_start': True}. Best is trial 27 with value: 0.7977677253229423.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 19:11:32,567] Trial 28 finished with value: 0.7837974275708264 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 236, 'oob_score': True, 'max_samples': 0.9976967175247285, 'max_features': None, 'min_weight_fraction_leaf': 0.08365358326712247, 'warm_start': True}. Best is trial 27 with value: 0.7977677253229423.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:11:37,141] Trial 29 finished with value: 0.7689052524199285 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 345, 'oob_score': True, 'max_samples': 0.9233414940787997, 'max_features': None, 'min_weight_fraction_leaf': 0.05878599020799078, 'warm_start': True}. Best is trial 27 with value: 0.7977677253229423.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 19:11:40,218] Trial 30 finished with value: 0.8187091599688708 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.9090216144690085, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07553359551188188, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 19:11:43,010] Trial 31 finished with value: 0.8090492137339151 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 307, 'oob_score': True, 'max_samples': 0.9009241102826697, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05767674949496584, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 19:11:45,961] Trial 32 finished with value: 0.8155619897931056 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 307, 'oob_score': True, 'max_samples': 0.9444789533658244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.061863348049174115, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 19:11:49,074] Trial 33 finished with value: 0.8115597345863208 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 313, 'oob_score': True, 'max_samples': 0.7498140550902006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.058944101870636915, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 19:11:52,473] Trial 34 finished with value: 0.8107481843126315 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.7487201934411643, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05921397662742622, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:11:55,298] Trial 35 finished with value: 0.7774715232187005 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7407146247417623, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 19:11:57,946] Trial 36 finished with value: 0.8133086810709184 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 323, 'oob_score': True, 'max_samples': 0.7626906097546058, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00052334394504433, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:12:04,579] Trial 37 finished with value: 0.7773627506492027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.6803527389169053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0029686221632765145, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 19:12:11,466] Trial 38 finished with value: 0.7758345328327488 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.5461815105682866, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11197515656308907, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:12:15,552] Trial 39 finished with value: 0.7967098226635841 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03746275234525784, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:12:20,199] Trial 40 finished with value: 0.7838025169016922 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.6285384337372241, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0016715706905124292, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:12:23,825] Trial 41 finished with value: 0.7994188859694267 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.767837172322005, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04107376710762661, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 19:12:26,927] Trial 42 finished with value: 0.8075965955408677 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.7198761567997874, 'max_features': None, 'min_weight_fraction_leaf': 0.06655767953419574, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8454935622317596
[I 2024-04-14 19:12:32,019] Trial 43 finished with value: 0.7935626689220804 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.5830624244187974, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03072132927204803, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:12:35,167] Trial 44 finished with value: 0.792243879751903 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.849283225599428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:12:36,767] Trial 45 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.7835335824282312, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4225092978230698, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 19:12:46,314] Trial 46 finished with value: 0.7095675932149055 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.9694479552382526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07708626038126316, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:12:49,563] Trial 47 finished with value: 0.7901000143340811 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.938566277881707, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13552684969677012, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 19:12:58,306] Trial 48 finished with value: 0.702758852119058 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.8593063971491026, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018767066815307473, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 19:13:02,403] Trial 49 finished with value: 0.790030635415705 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.810571778428794, 'max_features': None, 'min_weight_fraction_leaf': 0.05280316176834379, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:13:04,085] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.1200736185519305, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10823226660656002, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 19:13:08,508] Trial 51 finished with value: 0.8066776611996556 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.8845583885496642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.051704705274191215, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 19:13:13,554] Trial 52 finished with value: 0.8179846363272901 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9389508399123877, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026222660443315594, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 19:13:16,823] Trial 53 finished with value: 0.8132980917343 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.9634175796095735, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016212313831113056, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 19:13:20,606] Trial 54 finished with value: 0.8043701178309467 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 336, 'oob_score': True, 'max_samples': 0.960656376063002, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02538198771575413, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:13:23,436] Trial 55 finished with value: 0.783914853960843 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.95971543405748, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004128426819979457, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 19:13:33,938] Trial 56 finished with value: 0.7085351708519758 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 384, 'oob_score': True, 'max_samples': 0.9500997490374486, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02615027370538182, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 19:13:36,828] Trial 57 finished with value: 0.7324089772745679 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.8232445639619075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32552397591019333, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 19:13:38,987] Trial 58 finished with value: 0.8050110423292084 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.8753505408569753, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08839970870738312, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:13:40,672] Trial 59 finished with value: 0.7807352821123983 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.9918040219312247, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19118259682554753, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 19:13:47,387] Trial 60 finished with value: 0.7091889537434665 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.9070990540146153, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2884043121771884, 'warm_start': False}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 19:13:51,154] Trial 61 finished with value: 0.814880687618372 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 319, 'oob_score': True, 'max_samples': 0.7615399939782056, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04186680436111091, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:13:54,025] Trial 62 finished with value: 0.8026386421088365 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.860154468718914, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018996988817560154, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 19:13:56,770] Trial 63 finished with value: 0.8130875285597183 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 293, 'oob_score': True, 'max_samples': 0.650059130929082, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03985507545277717, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 19:14:00,562] Trial 64 finished with value: 0.812236464729931 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.648848020334941, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0370572148748974, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 19:14:04,506] Trial 65 finished with value: 0.7439994647953215 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.7085331758294136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07493747527848026, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:14:13,985] Trial 66 finished with value: 0.8113234207073792 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.5503522334237032, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014990122277374727, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 19:14:18,663] Trial 67 finished with value: 0.8109118016753551 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.9287743458652018, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09650876105157191, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 19:14:27,173] Trial 68 finished with value: 0.8097774617205067 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 354, 'oob_score': True, 'max_samples': 0.7846300394640543, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04429491696707287, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:14:37,036] Trial 69 finished with value: 0.797629748112005 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.8287968234410008, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07311553142208801, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:14:42,804] Trial 70 finished with value: 0.7790433863450577 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.613470597922394, 'max_features': None, 'min_weight_fraction_leaf': 0.1220007168733092, 'warm_start': True}. Best is trial 30 with value: 0.8187091599688708.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 19:14:48,967] Trial 71 finished with value: 0.8212219902160223 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.6600979014487112, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.034810079140300265, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:14:53,948] Trial 72 finished with value: 0.7986584296956625 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 316, 'oob_score': True, 'max_samples': 0.679366759155893, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012981940650464333, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:14:58,810] Trial 73 finished with value: 0.8002915687497681 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.5818969350992149, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.030324237180112363, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 19:15:03,179] Trial 74 finished with value: 0.8106833438952299 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.6605397044772018, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.044728991821657724, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:15:06,191] Trial 75 finished with value: 0.7869022845540203 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.43192925271620286, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004132732502672452, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:15:10,745] Trial 76 finished with value: 0.7961809812508033 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 380, 'oob_score': True, 'max_samples': 0.9092696799351757, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0655411250434925, 'warm_start': True}. Best is trial 71 with value: 0.8212219902160223.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8841201716738197
[I 2024-04-14 19:15:13,389] Trial 77 finished with value: 0.8259959952982054 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 215, 'oob_score': True, 'max_samples': 0.9704274765808761, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031933517179332606, 'warm_start': True}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 19:15:14,819] Trial 78 finished with value: 0.7239202782995913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.9634807471249888, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.36634172681308474, 'warm_start': True}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 19:15:17,398] Trial 79 finished with value: 0.8076877703610432 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.9796010144096535, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08340966492391791, 'warm_start': True}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:15:21,881] Trial 80 finished with value: 0.6692722328483665 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 180, 'oob_score': True, 'max_samples': 0.9967289700499299, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4514075579267288, 'warm_start': False}. Best is trial 77 with value: 0.8259959952982054.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:15:24,258] Trial 81 finished with value: 0.8266369197964671 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.9278309282278278, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031185763946052, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:15:26,738] Trial 82 finished with value: 0.8197949957404997 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 254, 'oob_score': True, 'max_samples': 0.8845418214747346, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026579185254879713, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8841201716738197
[I 2024-04-14 19:15:29,672] Trial 83 finished with value: 0.8245757288134271 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 248, 'oob_score': True, 'max_samples': 0.8884822038631196, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02817023990682517, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8841201716738197
[I 2024-04-14 19:15:32,278] Trial 84 finished with value: 0.8258179372670176 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.9342956222659774, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05206662664124263, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 19:15:34,841] Trial 85 finished with value: 0.8042543104004551 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.9343697525340412, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.052450844892942015, 'warm_start': True}. Best is trial 81 with value: 0.8266369197964671.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8884120171673819
[I 2024-04-14 19:15:37,854] Trial 86 finished with value: 0.8292332222001028 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.9074598841382039, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06260583991007246, 'warm_start': True}. Best is trial 86 with value: 0.8292332222001028.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9184549356223176
[I 2024-04-14 19:15:41,146] Trial 87 finished with value: 0.8446990286160186 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.8948299547976223, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03150292204046534, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 19:15:43,864] Trial 88 finished with value: 0.8219978882794878 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 214, 'oob_score': True, 'max_samples': 0.8859534162261831, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07009154752888405, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 19:15:46,122] Trial 89 finished with value: 0.8076150574105638 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 211, 'oob_score': True, 'max_samples': 0.88356616516019, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08891146848350209, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 19:15:48,199] Trial 90 finished with value: 0.760404993251153 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 245, 'oob_score': True, 'max_samples': 0.8450915216955311, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2441821280246807, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:15:49,867] Trial 91 finished with value: 0.8195457666959325 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.8945235910735918, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06727167400022452, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8841201716738197
[I 2024-04-14 19:15:51,278] Trial 92 finished with value: 0.8227181367461665 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.8656940158187053, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06051685306548257, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8841201716738197
[I 2024-04-14 19:15:53,042] Trial 93 finished with value: 0.8283099962497271 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.8607147952683254, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05002466956085034, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8626609442060086
[I 2024-04-14 19:15:54,475] Trial 94 finished with value: 0.8161518038571807 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 147, 'oob_score': True, 'max_samples': 0.8039671034590891, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05511376982757581, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8669527896995708
[I 2024-04-14 19:15:56,640] Trial 95 finished with value: 0.813265459604071 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.9180299751003221, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0976022167745263, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8884120171673819
[I 2024-04-14 19:15:59,185] Trial 96 finished with value: 0.827556845244888 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 159, 'oob_score': True, 'max_samples': 0.8201484101508788, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05047968764730313, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 19:16:00,478] Trial 97 finished with value: 0.7789361418828648 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.8658967681300396, 'max_features': None, 'min_weight_fraction_leaf': 0.1428162647896823, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 19:16:02,303] Trial 98 finished with value: 0.7928921095190898 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.845906981829974, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11585566276285697, 'warm_start': True}. Best is trial 87 with value: 0.8446990286160186.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7870722433460076

[I 2024-04-14 19:16:04,503] A new study created in memory with name: no-name-ff215401-8770-4c10-a149-99471208df6f

Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 19:16:04,468] Trial 99 finished with value: 0.7098377911129411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.821888296728338, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07696848402070876, 'warm_start': False}. Best is trial 87 with value: 0.8446990286160186.


* Best trial for C-index:
 FrozenTrial(number=87, state=TrialState.COMPLETE, values=[0.8446990286160186], datetime_start=datetime.datetime(2024, 4, 14, 19, 15, 37, 874252), datetime_complete=datetime.datetime(2024, 4, 14, 19, 15, 41, 144281), params={'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.8948299547976223, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03150292204046534, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=87, value=None)


* Best Score for C-index:
 0.8446990286160186

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22247227240535786
Fold 2 IBS: 0.18232664910750715
Fold 3 IBS: 0.2420580936789368
Fold 4 IBS: 0.2087871302790621
Fold 5 IBS: 0.21380523601862628
[I 2024-04-14 19:16:10,004] Trial 0 finished with value: 0.21388987629789802 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21388987629789802.
Fold 1 IBS: 0.22190200921656902
Fold 2 IBS: 0.18520497930133592
Fold 3 IBS: 0.2096554024234873
Fold 4 IBS: 0.20450583850411352
Fold 5 IBS: 0.20942035062626901
[I 2024-04-14 19:16:11,176] Trial 1 finished with value: 0.20613771601435493 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-14 19:16:12,283] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-14 19:16:15,459] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-14 19:16:18,465] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24349089504197247
Fold 2 IBS: 0.18718721338407
Fold 3 IBS: 0.20904030011349778
Fold 4 IBS: 0.19549836093110387
Fold 5 IBS: 0.20053012489350203
[I 2024-04-14 19:16:22,884] Trial 5 finished with value: 0.20714937887282922 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2112386460322564
Fold 2 IBS: 0.19508671635593208
Fold 3 IBS: 0.2539054626067449
Fold 4 IBS: 0.20596568095253565
Fold 5 IBS: 0.217860530835901
[I 2024-04-14 19:16:26,584] Trial 6 finished with value: 0.21681140735667398 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24089525456291452
Fold 2 IBS: 0.22612078074442202
Fold 3 IBS: 0.2282442357538558
Fold 4 IBS: 0.23490470640743932
Fold 5 IBS: 0.22514225661339773
[I 2024-04-14 19:16:31,660] Trial 7 finished with value: 0.2310614468164059 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-14 19:16:39,407] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22582896185315818
Fold 2 IBS: 0.18894634804682173
Fold 3 IBS: 0.2057784489559595
Fold 4 IBS: 0.2180447704779101
Fold 5 IBS: 0.2172744627174237
[I 2024-04-14 19:16:41,123] Trial 9 finished with value: 0.21117459841025465 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-14 19:16:43,418] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.27655340997373795
Fold 2 IBS: 0.20285589585360056
Fold 3 IBS: 0.1947393615356906
Fold 4 IBS: 0.25388874005881606
Fold 5 IBS: 0.2535773052181159
[I 2024-04-14 19:16:43,661] Trial 11 finished with value: 0.23632294252799219 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23661533269825294
Fold 2 IBS: 0.1897008690599795
Fold 3 IBS: 0.2099087326943024
Fold 4 IBS: 0.19797945389979577
Fold 5 IBS: 0.202316033023455
[I 2024-04-14 19:16:49,016] Trial 12 finished with value: 0.2073040842751571 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11583591034272536}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2248425881164494
Fold 2 IBS: 0.190961258650741
Fold 3 IBS: 0.21755351923447738
Fold 4 IBS: 0.2072423012270404
Fold 5 IBS: 0.2069603718270392
[I 2024-04-14 19:16:57,556] Trial 13 finished with value: 0.20951200781114948 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 489, 'oob_score': False, 'max_samples': 0.6258340703868753, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22334594057849727
Fold 2 IBS: 0.19531155973733316
Fold 3 IBS: 0.21478959068896128
Fold 4 IBS: 0.21326266865850366
Fold 5 IBS: 0.20996090428619574
[I 2024-04-14 19:17:01,651] Trial 14 finished with value: 0.21133413278989818 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 149, 'oob_score': False, 'max_samples': 0.3884265985399165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11968759270144667}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22218471099765655
Fold 2 IBS: 0.1908222695690612
Fold 3 IBS: 0.21809938496011258
Fold 4 IBS: 0.20522426138911296
Fold 5 IBS: 0.20529160871621235
[I 2024-04-14 19:17:08,756] Trial 15 finished with value: 0.2083244471264311 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 333, 'oob_score': False, 'max_samples': 0.9873764111748721, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 1 with value: 0.20613771601435493.

Fold 1 IBS: 0.22741079396568517
Fold 2 IBS: 0.19671898923275805
Fold 3 IBS: 0.21466613517706562
Fold 4 IBS: 0.21926376344435916
Fold 5 IBS: 0.21171233186655944
[I 2024-04-14 19:17:13,057] Trial 16 finished with value: 0.21395440273728544 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.656467758901384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18189213917493566}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23758559549732755
Fold 2 IBS: 0.19145243463776812
Fold 3 IBS: 0.2137404379947349
Fold 4 IBS: 0.19571197094726786
Fold 5 IBS: 0.21474767853149498
[I 2024-04-14 19:17:14,164] Trial 17 finished with value: 0.21064762352171867 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 43, 'oob_score': False, 'max_samples': 0.8368873118701377, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06960366441289781}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23049259545720302
Fold 2 IBS: 0.20911691627017634
Fold 3 IBS: 0.2181721573366182
Fold 4 IBS: 0.21742568141810073
Fold 5 IBS: 0.2146352649005535
[I 2024-04-14 19:17:21,911] Trial 18 finished with value: 0.2179685230765304 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.21062982570611943, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.059365270422688146}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2264952801409006
Fold 2 IBS: 0.19955387088265925
Fold 3 IBS: 0.21739580733146385
Fold 4 IBS: 0.21856008991312992
Fold 5 IBS: 0.21313745994875308
[I 2024-04-14 19:17:28,346] Trial 19 finished with value: 0.21502850164338133 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.44408982315616696, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15043236342899463}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22812558527558263
Fold 2 IBS: 0.2016157145341236
Fold 3 IBS: 0.22002757230540262
Fold 4 IBS: 0.21836889218778097
Fold 5 IBS: 0.2140609143058242
[I 2024-04-14 19:17:33,050] Trial 20 finished with value: 0.21643973572174283 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 10, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.6287093569089685, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2396569085937919
Fold 2 IBS: 0.1910935837619349
Fold 3 IBS: 0.20880750569491974
Fold 4 IBS: 0.19588658540225293
Fold 5 IBS: 0.20208571260715374
[I 2024-04-14 19:17:39,331] Trial 21 finished with value: 0.20750605921201065 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.7760640896680125, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10796776799958208}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24740452329365578
Fold 2 IBS: 0.19069021977636783
Fold 3 IBS: 0.2125162975535963
Fold 4 IBS: 0.19615654983751615
Fold 5 IBS: 0.2042061405444355
[I 2024-04-14 19:17:49,646] Trial 22 finished with value: 0.2101947462011143 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 239, 'oob_score': False, 'max_samples': 0.7910357296881861, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09662675583218894}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22771180153358486
Fold 2 IBS: 0.1908352856941038
Fold 3 IBS: 0.21056708435357757
Fold 4 IBS: 0.2039901093622608
Fold 5 IBS: 0.20215750442919442
[I 2024-04-14 19:17:55,721] Trial 23 finished with value: 0.2070523570745443 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 292, 'oob_score': False, 'max_samples': 0.6990339812704174, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1539276858922122}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22444999885353673
Fold 2 IBS: 0.19161037291839192
Fold 3 IBS: 0.21372027568608407
Fold 4 IBS: 0.20699175781965262
Fold 5 IBS: 0.20399814810887068
[I 2024-04-14 19:18:00,470] Trial 24 finished with value: 0.2081541106773072 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.6715158604870778, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17191377003527608}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2300079810993901
Fold 2 IBS: 0.1905197898562083
Fold 3 IBS: 0.21017312235899321
Fold 4 IBS: 0.20636975804390315
Fold 5 IBS: 0.2052533781333476
[I 2024-04-14 19:18:06,675] Trial 25 finished with value: 0.20846480589836847 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 392, 'oob_score': False, 'max_samples': 0.4804330704768072, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.041861849873669}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23041211905686212
Fold 2 IBS: 0.1987362490696931
Fold 3 IBS: 0.21977713526103848
Fold 4 IBS: 0.21517449955996573
Fold 5 IBS: 0.21826042042959132
[I 2024-04-14 19:18:08,971] Trial 26 finished with value: 0.21647208467543014 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.5822513269079284, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2332968426644862}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23415060118389855
Fold 2 IBS: 0.21272733854973816
Fold 3 IBS: 0.22645044277955098
Fold 4 IBS: 0.22259343512812918
Fold 5 IBS: 0.2152765633037375
[I 2024-04-14 19:18:15,402] Trial 27 finished with value: 0.22223967618901086 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.6977079452893333, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.31708355026774127}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23484870840624567
Fold 2 IBS: 0.18805373119166738
Fold 3 IBS: 0.21154546188079174
Fold 4 IBS: 0.19762071527137068
Fold 5 IBS: 0.20406253262826174
[I 2024-04-14 19:18:19,736] Trial 28 finished with value: 0.20722622987566744 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9030031356045858, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1514673448473745}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23098177402027859
Fold 2 IBS: 0.18326163821587102
Fold 3 IBS: 0.24298539875752923
Fold 4 IBS: 0.2087613858468209
Fold 5 IBS: 0.21044567928546803
[I 2024-04-14 19:18:26,444] Trial 29 finished with value: 0.21528717522519356 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 366, 'oob_score': False, 'max_samples': 0.7193977487980262, 'max_features': None, 'min_weight_fraction_leaf': 0.20016896711794063}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23343277722766048
Fold 2 IBS: 0.21179728899149092
Fold 3 IBS: 0.22526528502716633
Fold 4 IBS: 0.22149097258042505
Fold 5 IBS: 0.21460986909372803
[I 2024-04-14 19:18:33,761] Trial 30 finished with value: 0.22131923858409416 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 463, 'oob_score': False, 'max_samples': 0.49064978844124546, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22041946341162919}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23695479431722785
Fold 2 IBS: 0.19071257279151949
Fold 3 IBS: 0.21043824770270952
Fold 4 IBS: 0.19761806088243694
Fold 5 IBS: 0.20380760347832808
[I 2024-04-14 19:18:39,886] Trial 31 finished with value: 0.20790625583444436 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.9237409555651629, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14463230245566638}. Best is trial 1 with value: 0.20613771601435493.

Fold 1 IBS: 0.22871119834201115
Fold 2 IBS: 0.18629984266823443
Fold 3 IBS: 0.2136333562391605
Fold 4 IBS: 0.20508306074253652
Fold 5 IBS: 0.20460862507387245
[I 2024-04-14 19:18:44,946] Trial 32 finished with value: 0.20766721661316295 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.8321993039875358, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16244513867075333}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2450153519251981
Fold 2 IBS: 0.19177067560329883
Fold 3 IBS: 0.2050380118625506
Fold 4 IBS: 0.19783492315190962
Fold 5 IBS: 0.20502773397972165
[I 2024-04-14 19:18:50,531] Trial 33 finished with value: 0.20893733930453579 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.9881033887741655, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08859622451822674}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22749955148715942
Fold 2 IBS: 0.18624882711058469
Fold 3 IBS: 0.21078360191851478
Fold 4 IBS: 0.200331508207223
Fold 5 IBS: 0.20926660288320456
[I 2024-04-14 19:18:52,974] Trial 34 finished with value: 0.2068260183213373 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.5815698435586507, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12599071395328157}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24678040122780803
Fold 2 IBS: 0.18195759296226327
Fold 3 IBS: 0.23828026858559573
Fold 4 IBS: 0.2153550814520749
Fold 5 IBS: 0.21329119905325156
[I 2024-04-14 19:18:54,960] Trial 35 finished with value: 0.2191329086561987 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.5833988262520585, 'max_features': None, 'min_weight_fraction_leaf': 0.0342605819155805}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23083039213409773
Fold 2 IBS: 0.18085640624529303
Fold 3 IBS: 0.19206984685001427
Fold 4 IBS: 0.22614045465776608
Fold 5 IBS: 0.20714300993579865
[I 2024-04-14 19:18:55,350] Trial 36 finished with value: 0.20740802196459396 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.5229942126902646, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12653534095242983}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2675396820612739
Fold 2 IBS: 0.18492417970666833
Fold 3 IBS: 0.22653206265577877
Fold 4 IBS: 0.20478422844892483
Fold 5 IBS: 0.21138914533998968
[I 2024-04-14 19:18:56,983] Trial 37 finished with value: 0.2190338596425271 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.6110303802482602, 'max_features': None, 'min_weight_fraction_leaf': 0.08313017968513577}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23193050651882594
Fold 2 IBS: 0.20346085746399578
Fold 3 IBS: 0.21958564173291276
Fold 4 IBS: 0.2215875193534143
Fold 5 IBS: 0.21474869623317375
[I 2024-04-14 19:19:02,381] Trial 38 finished with value: 0.2182626442604645 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 194, 'oob_score': True, 'max_samples': 0.5399793822518019, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20783355153995484}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22723758437947836
Fold 2 IBS: 0.19685733236334332
Fold 3 IBS: 0.2260072038662561
Fold 4 IBS: 0.20783349829441977
Fold 5 IBS: 0.21539359722558588
[I 2024-04-14 19:19:04,475] Trial 39 finished with value: 0.2146658432258167 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 81, 'oob_score': True, 'max_samples': 0.6616268224727397, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2641597430185727}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2464411620206046
Fold 2 IBS: 0.23208919673298345
Fold 3 IBS: 0.22939828491770947
Fold 4 IBS: 0.24163774673370553
Fold 5 IBS: 0.23017045101980416
[I 2024-04-14 19:19:07,880] Trial 40 finished with value: 0.23594736828496146 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.7131209218929478, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3772343263698569}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23473304858494798
Fold 2 IBS: 0.1866035871208093
Fold 3 IBS: 0.20826926079165517
Fold 4 IBS: 0.20463633969823483
Fold 5 IBS: 0.2047547926961405
[I 2024-04-14 19:19:14,177] Trial 41 finished with value: 0.20779940577835757 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 364, 'oob_score': False, 'max_samples': 0.8701681705385872, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1343317776607293}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22656893321210875
Fold 2 IBS: 0.18723606830894912
Fold 3 IBS: 0.21109703496481325
Fold 4 IBS: 0.20987021696001218
Fold 5 IBS: 0.20601426227941114
[I 2024-04-14 19:19:17,067] Trial 42 finished with value: 0.2081573031450589 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 15, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.7897901557863907, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18070686065748254}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24744295325946178
Fold 2 IBS: 0.2320992006684519
Fold 3 IBS: 0.2299147319431908
Fold 4 IBS: 0.24125655639883625
Fold 5 IBS: 0.22977215463601064
[I 2024-04-14 19:19:18,339] Trial 43 finished with value: 0.23609711938119027 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.36202851108062717, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.237873852425811
Fold 2 IBS: 0.1911858625927698
Fold 3 IBS: 0.21217447541650147
Fold 4 IBS: 0.19464668557010967
Fold 5 IBS: 0.20526412831793428
[I 2024-04-14 19:19:24,070] Trial 44 finished with value: 0.2082290008646252 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 278, 'oob_score': True, 'max_samples': 0.9332193354742175, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10471530729487721}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2308383850787664
Fold 2 IBS: 0.1883757876211021
Fold 3 IBS: 0.21146318355642707
Fold 4 IBS: 0.20701750028297367
Fold 5 IBS: 0.20270601079373723
[I 2024-04-14 19:19:29,534] Trial 45 finished with value: 0.2080801734666013 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 224, 'oob_score': False, 'max_samples': 0.7426761003495893, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05179398828063411}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23814136700249025
Fold 2 IBS: 0.19047555395027155
Fold 3 IBS: 0.21285211041644087
Fold 4 IBS: 0.19449171857639905
Fold 5 IBS: 0.20306331832172417
[I 2024-04-14 19:19:36,071] Trial 46 finished with value: 0.20780481365346515 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.6888021858587338, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.019519921400110954}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23278469063178084
Fold 2 IBS: 0.18344460559174183
Fold 3 IBS: 0.21950571831113413
Fold 4 IBS: 0.24306339804016053
Fold 5 IBS: 0.21829232309628968
[I 2024-04-14 19:19:36,539] Trial 47 finished with value: 0.21941814713422142 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 1, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.5796439752373613, 'max_features': None, 'min_weight_fraction_leaf': 0.15867994777177402}. Best is trial 1 with value: 0.20613771601435493.

Fold 1 IBS: 0.2464013758053453
Fold 2 IBS: 0.23207408714903174
Fold 3 IBS: 0.22939892327646114
Fold 4 IBS: 0.2415689721009919
Fold 5 IBS: 0.23043319376810475
[I 2024-04-14 19:19:38,369] Trial 48 finished with value: 0.23597531041998696 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.6344615640154665, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.24633584274807316
Fold 2 IBS: 0.23218539826865298
Fold 3 IBS: 0.22972627891694997
Fold 4 IBS: 0.2411567932158465
Fold 5 IBS: 0.2301175121753443
[I 2024-04-14 19:19:41,030] Trial 49 finished with value: 0.2359043650649734 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 168, 'oob_score': False, 'max_samples': 0.2700643631363231, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12690725040328102}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.22805778621159317
Fold 2 IBS: 0.185599953677471
Fold 3 IBS: 0.21897300321074908
Fold 4 IBS: 0.19433397592691898
Fold 5 IBS: 0.2065854337466597
[I 2024-04-14 19:19:41,828] Trial 50 finished with value: 0.20671003055467838 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 30, 'oob_score': False, 'max_samples': 0.8720141909177958, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07495127057764972}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.23243327001803338
Fold 2 IBS: 0.18941306403608543
Fold 3 IBS: 0.21918339193212566
Fold 4 IBS: 0.20045338249946848
Fold 5 IBS: 0.20335769782277796
[I 2024-04-14 19:19:42,585] Trial 51 finished with value: 0.2089681612616982 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.8823837118861377, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0676426611884569}. Best is trial 1 with value: 0.20613771601435493.
Fold 1 IBS: 0.2361464454069328
Fold 2 IBS: 0.18250031051752705
Fold 3 IBS: 0.2090720657878296
Fold 4 IBS: 0.19679404106447074
Fold 5 IBS: 0.20349326858684608
[I 2024-04-14 19:19:43,801] Trial 52 finished with value: 0.2056012262727213 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.8227879143305075, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07825337635432089}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23885607750473734
Fold 2 IBS: 0.1848517569348757
Fold 3 IBS: 0.21163247963526902
Fold 4 IBS: 0.2001279282395039
Fold 5 IBS: 0.20182477381846523
[I 2024-04-14 19:19:45,863] Trial 53 finished with value: 0.20745860322657023 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 64, 'oob_score': False, 'max_samples': 0.8247386802784168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07686213578570306}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2417598447201395
Fold 2 IBS: 0.19379954646629008
Fold 3 IBS: 0.20059068455113124
Fold 4 IBS: 0.21343137209210217
Fold 5 IBS: 0.20739078882382453
[I 2024-04-14 19:19:48,341] Trial 54 finished with value: 0.2113944473306975 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.7523093632558471, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02761362577898832}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2435282613998248
Fold 2 IBS: 0.18461090145364523
Fold 3 IBS: 0.21130163008138786
Fold 4 IBS: 0.19773718095053663
Fold 5 IBS: 0.20528201919418199
[I 2024-04-14 19:19:50,267] Trial 55 finished with value: 0.20849199861591527 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 53, 'oob_score': False, 'max_samples': 0.8127631568998966, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10094495624247499}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23630716566501458
Fold 2 IBS: 0.19123236708831395
Fold 3 IBS: 0.20543373510057844
Fold 4 IBS: 0.20614543950307668
Fold 5 IBS: 0.2081136731187162
[I 2024-04-14 19:19:51,816] Trial 56 finished with value: 0.20944647609514 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6518007964702662, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.045191591449920396}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23645790592894317
Fold 2 IBS: 0.18766760229554244
Fold 3 IBS: 0.20971274141638638
Fold 4 IBS: 0.20693796142165954
Fold 5 IBS: 0.20571283305580854
[I 2024-04-14 19:19:54,733] Trial 57 finished with value: 0.20929780882366802 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 120, 'oob_score': False, 'max_samples': 0.6003360228940852, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11719096619167582}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23558890831528975
Fold 2 IBS: 0.18765488713793946
Fold 3 IBS: 0.20841015286377512
Fold 4 IBS: 0.20279934898314664
Fold 5 IBS: 0.20556011235640959
[I 2024-04-14 19:20:01,673] Trial 58 finished with value: 0.2080026819313121 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.9463423717095281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18529100559417558}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24810660030204534
Fold 2 IBS: 0.18659537930442788
Fold 3 IBS: 0.20638895469149965
Fold 4 IBS: 0.19672141355116166
Fold 5 IBS: 0.20692156250277413
[I 2024-04-14 19:20:07,495] Trial 59 finished with value: 0.20894678207038173 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.8547564638582521, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.082046556845009}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24853640495704013
Fold 2 IBS: 0.18885633347272196
Fold 3 IBS: 0.20365354876519
Fold 4 IBS: 0.19803748416241668
Fold 5 IBS: 0.20661458917629735
[I 2024-04-14 19:20:10,250] Trial 60 finished with value: 0.20913967210673326 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 94, 'oob_score': False, 'max_samples': 0.7660501894449964, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01168656559831241}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22877799740609422
Fold 2 IBS: 0.18217625474761148
Fold 3 IBS: 0.21499889813461354
Fold 4 IBS: 0.2022199042093769
Fold 5 IBS: 0.21203512415931286
[I 2024-04-14 19:20:12,523] Trial 61 finished with value: 0.2080416357314018 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 57, 'oob_score': False, 'max_samples': 0.8882410633772397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14539711658704613}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22754590235990318
Fold 2 IBS: 0.18884153233624934
Fold 3 IBS: 0.2189820762077244
Fold 4 IBS: 0.20521480488223304
Fold 5 IBS: 0.21663257940086067
[I 2024-04-14 19:20:14,734] Trial 62 finished with value: 0.21144337903739413 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 26, 'oob_score': False, 'max_samples': 0.7986798716288218, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.061373327150469156}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23473331365511063
Fold 2 IBS: 0.18972921303376702
Fold 3 IBS: 0.21324292263684766
Fold 4 IBS: 0.1958213954118823
Fold 5 IBS: 0.20450440606793152
[I 2024-04-14 19:20:23,111] Trial 63 finished with value: 0.20760625016110784 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 312, 'oob_score': False, 'max_samples': 0.9690103699749839, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16697994987339515}. Best is trial 52 with value: 0.2056012262727213.

Fold 1 IBS: 0.2263102371899488
Fold 2 IBS: 0.1935254758393429
Fold 3 IBS: 0.20737484396299696
Fold 4 IBS: 0.2086187676158567
Fold 5 IBS: 0.20696146438052143
[I 2024-04-14 19:20:27,835] Trial 64 finished with value: 0.2085581577977334 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 252, 'oob_score': False, 'max_samples': 0.5041409232103772, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1346031511543957}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23692845343363148
Fold 2 IBS: 0.19041679735965694
Fold 3 IBS: 0.21008157321222845
Fold 4 IBS: 0.1987406581683996
Fold 5 IBS: 0.20283869466958301
[I 2024-04-14 19:20:34,292] Trial 65 finished with value: 0.2078012353686999 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.689407190096443, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09569536169262748}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2255506657367698
Fold 2 IBS: 0.18805519263346854
Fold 3 IBS: 0.2140249543406543
Fold 4 IBS: 0.204793062748871
Fold 5 IBS: 0.2049034354586081
[I 2024-04-14 19:20:40,779] Trial 66 finished with value: 0.20746546218367432 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.906641395754475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22031559160924333}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24258554415106987
Fold 2 IBS: 0.18586608211580108
Fold 3 IBS: 0.20633005021889933
Fold 4 IBS: 0.20779200270329232
Fold 5 IBS: 0.20375949906916596
[I 2024-04-14 19:20:44,324] Trial 67 finished with value: 0.20926663565164572 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.7268429170353262, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10950641230663803}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2744717974664921
Fold 2 IBS: 0.18531476493261076
Fold 3 IBS: 0.2376281621978531
Fold 4 IBS: 0.2076758997152183
Fold 5 IBS: 0.21122359325090623
[I 2024-04-14 19:20:52,063] Trial 68 finished with value: 0.2232628435126161 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.8456686301837488, 'max_features': None, 'min_weight_fraction_leaf': 0.15110142201065135}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22989789397046154
Fold 2 IBS: 0.20557290568176295
Fold 3 IBS: 0.2205542450665648
Fold 4 IBS: 0.21801691051265681
Fold 5 IBS: 0.21304411377419208
[I 2024-04-14 19:21:00,754] Trial 69 finished with value: 0.2174172138011276 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.5570102260852274, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0010125423146907786}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23260433244255335
Fold 2 IBS: 0.2053937803587354
Fold 3 IBS: 0.21933048484950973
Fold 4 IBS: 0.21987041520976924
Fold 5 IBS: 0.21331744179953746
[I 2024-04-14 19:21:06,309] Trial 70 finished with value: 0.21810329093202102 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 269, 'oob_score': False, 'max_samples': 0.47050660582184156, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1864414628763665}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24058155183437327
Fold 2 IBS: 0.18810548775721886
Fold 3 IBS: 0.20800901901815527
Fold 4 IBS: 0.20075174580328325
Fold 5 IBS: 0.20329932911538148
[I 2024-04-14 19:21:10,265] Trial 71 finished with value: 0.20814942670568243 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 211, 'oob_score': False, 'max_samples': 0.7681995329120036, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11591991777378008}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2305091643085561
Fold 2 IBS: 0.19104698324307837
Fold 3 IBS: 0.21062449364741084
Fold 4 IBS: 0.20048937087490803
Fold 5 IBS: 0.20221331981575683
[I 2024-04-14 19:21:16,291] Trial 72 finished with value: 0.20697666637794204 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.707944231424585, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1352852442587333}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23856798991286943
Fold 2 IBS: 0.18966254783831424
Fold 3 IBS: 0.21288374749651073
Fold 4 IBS: 0.19550453830736692
Fold 5 IBS: 0.20119154003907394
[I 2024-04-14 19:21:23,901] Trial 73 finished with value: 0.20756207271882707 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.6783022835853422, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09454160680625662}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23346466154567588
Fold 2 IBS: 0.18915130481355927
Fold 3 IBS: 0.20898169048315382
Fold 4 IBS: 0.2061597989588016
Fold 5 IBS: 0.20265748674922124
[I 2024-04-14 19:21:28,499] Trial 74 finished with value: 0.2080829885100824 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.6355542023201384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1361826784325361}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.21840369971447826
Fold 2 IBS: 0.1838999491090235
Fold 3 IBS: 0.21836405609135384
Fold 4 IBS: 0.20249510240131743
Fold 5 IBS: 0.2081026177358157
[I 2024-04-14 19:21:29,845] Trial 75 finished with value: 0.20625308501039777 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.7227252643897649, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20055904339717942}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23049776586861626
Fold 2 IBS: 0.1968054951080838
Fold 3 IBS: 0.20983615907626868
Fold 4 IBS: 0.2213557455632088
Fold 5 IBS: 0.21198428796963106
[I 2024-04-14 19:21:36,568] Trial 76 finished with value: 0.21409589071716173 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7163522458845774, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.239658391299781}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2153379292303241
Fold 2 IBS: 0.18734937683851036
Fold 3 IBS: 0.2194856036215662
Fold 4 IBS: 0.21172307250951736
Fold 5 IBS: 0.21189997754796933
[I 2024-04-14 19:21:38,538] Trial 77 finished with value: 0.2091591919495775 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 46, 'oob_score': True, 'max_samples': 0.6648801840846614, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20053264417943462}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22080186193533002
Fold 2 IBS: 0.18679719875579373
Fold 3 IBS: 0.2135369535018638
Fold 4 IBS: 0.20857331045798186
Fold 5 IBS: 0.2079988293734741
[I 2024-04-14 19:21:40,707] Trial 78 finished with value: 0.2075416308048887 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 87, 'oob_score': False, 'max_samples': 0.6154987453242609, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17669063739201887}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2531712135550899
Fold 2 IBS: 0.23298694791088354
Fold 3 IBS: 0.22932958454282865
Fold 4 IBS: 0.2417074467970325
Fold 5 IBS: 0.23326542379819543
[I 2024-04-14 19:21:41,585] Trial 79 finished with value: 0.23809212332080598 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2593946514256877}. Best is trial 52 with value: 0.2056012262727213.

Fold 1 IBS: 0.2141097932587844
Fold 2 IBS: 0.20953167979731777
Fold 3 IBS: 0.25602778622576694
Fold 4 IBS: 0.2273921618025962
Fold 5 IBS: 0.2321408254663515
[I 2024-04-14 19:21:42,827] Trial 80 finished with value: 0.2278404493101634 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7067242004030547, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3136324910319987}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2300650150874554
Fold 2 IBS: 0.18010561006896428
Fold 3 IBS: 0.21441487116790292
Fold 4 IBS: 0.19757686931100543
Fold 5 IBS: 0.21275664692284824
[I 2024-04-14 19:21:46,629] Trial 81 finished with value: 0.20698380251163523 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.9023474857295949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16360107456547565}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.23002497302639052
Fold 2 IBS: 0.18368245768130084
Fold 3 IBS: 0.20926256560956186
Fold 4 IBS: 0.20438983840996378
Fold 5 IBS: 0.21178805819403893
[I 2024-04-14 19:21:50,466] Trial 82 finished with value: 0.20782957858425122 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 66, 'oob_score': False, 'max_samples': 0.8041501696371655, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15566497227824816}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22525709023484097
Fold 2 IBS: 0.19031985367511442
Fold 3 IBS: 0.21545971292146093
Fold 4 IBS: 0.19621095051088705
Fold 5 IBS: 0.21784011145862167
[I 2024-04-14 19:21:53,774] Trial 83 finished with value: 0.20901754376018503 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 41, 'oob_score': False, 'max_samples': 0.952138352048073, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16893964738099349}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22378096685445067
Fold 2 IBS: 0.1895053205284943
Fold 3 IBS: 0.20767776897298412
Fold 4 IBS: 0.20842593830082462
Fold 5 IBS: 0.20729577060869708
[I 2024-04-14 19:21:58,038] Trial 84 finished with value: 0.20733715305309017 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.7439251995058213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19442028971918945}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22314221501288856
Fold 2 IBS: 0.18950789991402148
Fold 3 IBS: 0.2158972480377118
Fold 4 IBS: 0.2085916183097106
Fold 5 IBS: 0.2124363950065684
[I 2024-04-14 19:21:59,936] Trial 85 finished with value: 0.2099150752561802 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.6452432470638817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21060208526832816}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2684729630224285
Fold 2 IBS: 0.19094079625717164
Fold 3 IBS: 0.22511728519830407
Fold 4 IBS: 0.20124427414478216
Fold 5 IBS: 0.2088391487984959
[I 2024-04-14 19:22:05,720] Trial 86 finished with value: 0.2189228934842365 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.5769304718540522, 'max_features': None, 'min_weight_fraction_leaf': 0.07346222327282463}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.21886595354416274
Fold 2 IBS: 0.18770809838968058
Fold 3 IBS: 0.21776025071920802
Fold 4 IBS: 0.2191458494090725
Fold 5 IBS: 0.21727579328961993
[I 2024-04-14 19:22:06,745] Trial 87 finished with value: 0.21215118907034874 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.7819434632545296, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1262182423341996}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.24762560270294712
Fold 2 IBS: 0.18712823463764675
Fold 3 IBS: 0.2209286915679543
Fold 4 IBS: 0.20450078818049727
Fold 5 IBS: 0.19930264931480454
[I 2024-04-14 19:22:08,086] Trial 88 finished with value: 0.21189719328076997 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 40, 'oob_score': False, 'max_samples': 0.8734278783104157, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05289369627992575}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2293730833939139
Fold 2 IBS: 0.18230440143406296
Fold 3 IBS: 0.21107718025893016
Fold 4 IBS: 0.19919668388653236
Fold 5 IBS: 0.21032363359663525
[I 2024-04-14 19:22:10,630] Trial 89 finished with value: 0.20645499651401492 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.8205331330759632, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1418352263930421}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2306626342614295
Fold 2 IBS: 0.18277073279130304
Fold 3 IBS: 0.2106550096038014
Fold 4 IBS: 0.19789664662095205
Fold 5 IBS: 0.21281412569624256
[I 2024-04-14 19:22:12,733] Trial 90 finished with value: 0.2069598297947457 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.844174565944255, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14102554699439274}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22769112001606934
Fold 2 IBS: 0.18102675167183196
Fold 3 IBS: 0.21420312024832305
Fold 4 IBS: 0.19898358439464284
Fold 5 IBS: 0.21291519072190637
[I 2024-04-14 19:22:14,511] Trial 91 finished with value: 0.20696395341055474 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.8292666432692936, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16644860786667023}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.21911251502993664
Fold 2 IBS: 0.18307233229493716
Fold 3 IBS: 0.21120632961768868
Fold 4 IBS: 0.2039789385653001
Fold 5 IBS: 0.21197518823031072
[I 2024-04-14 19:22:16,203] Trial 92 finished with value: 0.2058690607476347 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.8555425487679464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22831629554484761}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2234673384623202
Fold 2 IBS: 0.1821986392218098
Fold 3 IBS: 0.21481467224495482
Fold 4 IBS: 0.2069361756909747
Fold 5 IBS: 0.20999150887909127
[I 2024-04-14 19:22:17,847] Trial 93 finished with value: 0.20748166689983014 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.8129378318781638, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23048998631129713}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22099075591469905
Fold 2 IBS: 0.19058239584335612
Fold 3 IBS: 0.21539998805635147
Fold 4 IBS: 0.20918961907349512
Fold 5 IBS: 0.21392406089234697
[I 2024-04-14 19:22:19,796] Trial 94 finished with value: 0.21001736395604978 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 82, 'oob_score': False, 'max_samples': 0.8327213695553917, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28897270320550766}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.22859558861712112
Fold 2 IBS: 0.178762191008013
Fold 3 IBS: 0.21407289298806645
Fold 4 IBS: 0.1973726421624764
Fold 5 IBS: 0.2121487830307864
[I 2024-04-14 19:22:21,395] Trial 95 finished with value: 0.20619041956129264 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 54, 'oob_score': False, 'max_samples': 0.8447220475438465, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13472277274289662}. Best is trial 52 with value: 0.2056012262727213.

Fold 1 IBS: 0.22385859901871702
Fold 2 IBS: 0.18749154864023293
Fold 3 IBS: 0.215405777089575
Fold 4 IBS: 0.19883810395439896
Fold 5 IBS: 0.21146953699788537
[I 2024-04-14 19:22:22,820] Trial 96 finished with value: 0.20741271314016183 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 58, 'oob_score': False, 'max_samples': 0.8577528441109724, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18660062214819917}. Best is trial 52 with value: 0.2056012262727213.
Fold 1 IBS: 0.2206463816639038
Fold 2 IBS: 0.18415089303949564
Fold 3 IBS: 0.2084960116600641
Fold 4 IBS: 0.20343560492304824
Fold 5 IBS: 0.20851133716775203
[I 2024-04-14 19:22:26,091] Trial 97 finished with value: 0.20504804569085272 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.8475291147257535, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20904972733074298}. Best is trial 97 with value: 0.20504804569085272.
Fold 1 IBS: 0.22137385042757987
Fold 2 IBS: 0.18840071162084657
Fold 3 IBS: 0.20838987304883333
Fold 4 IBS: 0.20228899120347085
Fold 5 IBS: 0.21075747268896797
[I 2024-04-14 19:22:30,149] Trial 98 finished with value: 0.20624217979793974 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.9260520619562637, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2513983980188341}. Best is trial 97 with value: 0.20504804569085272.
Fold 1 IBS: 0.21992273761412498
Fold 2 IBS: 0.1886985928564911
Fold 3 IBS: 0.2096707172324783
Fold 4 IBS: 0.20387319214065205
Fold 5 IBS: 0.21008621708122602
[I 2024-04-14 19:22:32,954] Trial 99 finished with value: 0.20645029138499452 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 98, 'oob_score': True, 'max_samples': 0.9224169389480626, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2505708058914136}. Best is trial 97 with value: 0.20504804569085272.


* Best trial for IBS:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.20504804569085272], datetime_start=datetime.datetime(2024, 4, 14, 19, 22, 22, 825264), datetime_complete=datetime.datetime(2024, 4, 14, 19, 22, 26, 90313), params={'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.8475291147257535, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20904972733074298}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=97, value=None)


* Best Score for IBS:
 0.20504804569085272

In [54]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.845
train_ibs:  0.205

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=17, max_features='log2', max_leaf_nodes=14,
                     max_samples=0.8948299547976223, min_samples_leaf=2,
                     min_samples_split=7,
                     min_weight_fraction_leaf=0.03150292204046534,
                     n_estimators=213, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.521

RandomSurvivalForest(max_depth=3, max_features='log2', max_leaf_nodes=10,
                     max_samples=0.8475291147257535, min_samples_leaf=7,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.20904972733074298,
                     n_estimators=95, oob_score=True, random_state=123)

test_ibs:  0.248

In [58]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [60]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:22:36,348] A new study created in memory with name: no-name-0d44bbd0-d67b-47ec-b543-31eb5cbe21fb

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:22:38,971] Trial 0 finished with value: 0.7503380732219547 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:22:44,347] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 19:22:52,168] Trial 2 finished with value: 0.6800680971098857 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6437768240343348
[I 2024-04-14 19:22:52,924] Trial 3 finished with value: 0.6785996809541028 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:22:56,712] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:23:01,468] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7503380732219547.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:23:03,505] Trial 6 finished with value: 0.7513235497730262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.7467811158798283
[I 2024-04-14 19:23:08,354] Trial 7 finished with value: 0.6919069260387125 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.7306201550387597
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:23:08,628] Trial 8 finished with value: 0.7102796856574409 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6266094420600858
[I 2024-04-14 19:23:19,750] Trial 9 finished with value: 0.6410217732844281 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:23:23,625] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7532188841201717
[I 2024-04-14 19:23:25,976] Trial 11 finished with value: 0.719951703739174 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.7513235497730262.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:23:28,557] Trial 12 finished with value: 0.7665885346648663 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 19:23:31,113] Trial 13 finished with value: 0.7335841742499907 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:23:34,405] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:23:35,915] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.7665885346648663.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 19:23:38,271] Trial 16 finished with value: 0.7223376647099076 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 19:23:40,308] Trial 17 finished with value: 0.7176426303552769 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.45617529880478086
Fold 2 C-index: 0.6143410852713178
Fold 3 C-index: 0.6872340425531915
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6716738197424893
[I 2024-04-14 19:23:41,614] Trial 18 finished with value: 0.6303715412895651 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 19:23:42,287] Trial 19 finished with value: 0.736143950309 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 19:23:44,450] Trial 20 finished with value: 0.7306611602311586 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 19:23:46,859] Trial 21 finished with value: 0.7420520149240719 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 19:23:48,484] Trial 22 finished with value: 0.7610441882373165 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8844026166095639, 'min_weight_fraction_leaf': 0.08688290860444149}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:23:51,405] Trial 23 finished with value: 0.7585342182148019 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.882373739187446, 'min_weight_fraction_leaf': 0.012868164547398506}. Best is trial 12 with value: 0.7665885346648663.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 19:23:53,894] Trial 24 finished with value: 0.7703255353389682 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8872409155608235, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 19:23:55,669] Trial 25 finished with value: 0.7336138162365781 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 309, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9949916074323628, 'min_weight_fraction_leaf': 0.09165915851143527}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7553648068669528
[I 2024-04-14 19:24:07,146] Trial 26 finished with value: 0.6962682445689629 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8751983869140558, 'min_weight_fraction_leaf': 0.047587407578096305}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 19:24:08,086] Trial 27 finished with value: 0.7330076663260743 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 202, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 19:24:09,667] Trial 28 finished with value: 0.7445805074044459 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9451664896451075, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 19:24:11,460] Trial 29 finished with value: 0.7543258448777239 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 397, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7184746104211617, 'min_weight_fraction_leaf': 0.07308871236755035}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 19:24:12,528] Trial 30 finished with value: 0.7443508545078521 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 225, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.11302310596200714}. Best is trial 24 with value: 0.7703255353389682.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 19:24:14,936] Trial 31 finished with value: 0.7598850722510556 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9135692082875294, 'min_weight_fraction_leaf': 0.03048028383469985}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 19:24:17,625] Trial 32 finished with value: 0.7497695648179512 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9370962123126668, 'min_weight_fraction_leaf': 0.049067586957051254}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:24:19,830] Trial 33 finished with value: 0.7528989938232977 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7138561909733563, 'min_weight_fraction_leaf': 0.08163103394835805}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 19:24:22,581] Trial 34 finished with value: 0.7510292604682907 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.845516995136671, 'min_weight_fraction_leaf': 0.028265200297625945}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 19:24:27,255] Trial 35 finished with value: 0.7395599794574828 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 417, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9400074533502404, 'min_weight_fraction_leaf': 0.06271242126132281}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.759656652360515
[I 2024-04-14 19:24:36,087] Trial 36 finished with value: 0.6974698213724116 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 7, 'n_estimators': 482, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9972156373133719, 'min_weight_fraction_leaf': 0.127039149502548}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:24:37,731] Trial 37 finished with value: 0.7512618500022212 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7981935205122315, 'min_weight_fraction_leaf': 0.09593702929582507}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 19:24:39,512] Trial 38 finished with value: 0.7480090378895263 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9318415222011842, 'min_weight_fraction_leaf': 0.02222474597769994}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 19:24:48,384] Trial 39 finished with value: 0.6593872759924035 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5170840385542366, 'min_weight_fraction_leaf': 0.16663317312622763}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 19:24:49,159] Trial 40 finished with value: 0.7169049452659841 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 146, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7431830894771643, 'min_weight_fraction_leaf': 0.05525956604312231}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 19:24:51,771] Trial 41 finished with value: 0.7619310412781907 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8723164546475863, 'min_weight_fraction_leaf': 0.004141659689301247}. Best is trial 24 with value: 0.7703255353389682.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:24:54,190] Trial 42 finished with value: 0.7776447223765721 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8355854149043529, 'min_weight_fraction_leaf': 0.031641115802858916}. Best is trial 42 with value: 0.7776447223765721.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 19:24:56,408] Trial 43 finished with value: 0.7791730671798607 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8248853396475693, 'min_weight_fraction_leaf': 0.022073817105411248}. Best is trial 43 with value: 0.7791730671798607.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 19:24:58,641] Trial 44 finished with value: 0.7508132807825151 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6729278091345884, 'min_weight_fraction_leaf': 0.020796365994372488}. Best is trial 43 with value: 0.7791730671798607.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:25:01,418] Trial 45 finished with value: 0.7799707276149772 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5998350649536632, 'min_weight_fraction_leaf': 0.004189572339664063}. Best is trial 45 with value: 0.7799707276149772.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:25:03,791] Trial 46 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 425, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.579000826136298, 'min_weight_fraction_leaf': 0.29510475784112217}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.759656652360515
[I 2024-04-14 19:25:10,705] Trial 47 finished with value: 0.7000204230450678 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6009235078772265, 'min_weight_fraction_leaf': 0.05035737763653817}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 19:25:14,752] Trial 48 finished with value: 0.7719957251193016 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 481, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4774852616943502, 'min_weight_fraction_leaf': 0.0030643948751397435}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 19:25:18,628] Trial 49 finished with value: 0.690791396045542 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 437, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.4273472569795538, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 19:25:22,869] Trial 50 finished with value: 0.7382528906361088 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.49402812735141344, 'min_weight_fraction_leaf': 0.0632245786962973}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 19:25:27,291] Trial 51 finished with value: 0.7428200304404313 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 499, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.2489831732375976, 'min_weight_fraction_leaf': 0.0005722956691509512}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:25:31,234] Trial 52 finished with value: 0.7682006220325706 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 480, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45928398992040387, 'min_weight_fraction_leaf': 0.036551688685847315}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 19:25:36,226] Trial 53 finished with value: 0.7686961206298732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.42214192449799365, 'min_weight_fraction_leaf': 0.034015659139177284}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:25:40,369] Trial 54 finished with value: 0.7535579563481994 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 431, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.41513610987014904, 'min_weight_fraction_leaf': 0.02284427593190501}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 19:25:45,684] Trial 55 finished with value: 0.7054303373849022 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 452, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3513361735766896, 'min_weight_fraction_leaf': 0.06760747962074701}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:25:49,381] Trial 56 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 383, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5174679188452345, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 19:25:53,129] Trial 57 finished with value: 0.7542566628867486 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 411, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7619437489466176, 'min_weight_fraction_leaf': 0.0407505426374218}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:26:05,326] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 467, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.28101469689358977, 'min_weight_fraction_leaf': 0.4204236378509412}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 19:26:11,220] Trial 59 finished with value: 0.7396770084527329 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 484, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.38015716638911, 'min_weight_fraction_leaf': 0.02005389901726501}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 19:26:12,214] Trial 60 finished with value: 0.7368182011884782 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 74, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.10939920085201921}. Best is trial 45 with value: 0.7799707276149772.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:26:17,749] Trial 61 finished with value: 0.7682006220325706 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 481, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4625777004396452, 'min_weight_fraction_leaf': 0.039166639676877606}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 19:26:22,612] Trial 62 finished with value: 0.7729299478150901 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5364852453438473, 'min_weight_fraction_leaf': 0.03801770294767894}. Best is trial 45 with value: 0.7799707276149772.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 19:26:27,035] Trial 63 finished with value: 0.7849537439206138 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 442, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5344584161283484, 'min_weight_fraction_leaf': 0.0002732443076643165}. Best is trial 63 with value: 0.7849537439206138.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 19:26:31,411] Trial 64 finished with value: 0.8222903552251639 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 444, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.546787796418659, 'min_weight_fraction_leaf': 0.011917675243562732}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 19:26:37,566] Trial 65 finished with value: 0.7890105041818515 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 439, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5250438016612026, 'min_weight_fraction_leaf': 0.011213412313927024}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:26:42,108] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5545678380606688, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 19:26:45,724] Trial 67 finished with value: 0.7875112105848775 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 366, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5214369604412972, 'min_weight_fraction_leaf': 0.013476336133043445}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 19:26:49,308] Trial 68 finished with value: 0.74877294810037 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6582110361515794, 'min_weight_fraction_leaf': 0.08398927364833789}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 19:26:53,054] Trial 69 finished with value: 0.8220407023375402 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 365, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5906341058203064, 'min_weight_fraction_leaf': 0.01345854547135509}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.871244635193133
[I 2024-04-14 19:26:57,516] Trial 70 finished with value: 0.8215041318127779 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5891348159442482, 'min_weight_fraction_leaf': 0.015516761884048515}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 19:27:02,526] Trial 71 finished with value: 0.8190883667044625 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 353, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5807169476519992, 'min_weight_fraction_leaf': 0.010585814688353384}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:27:07,524] Trial 72 finished with value: 0.8215619802517372 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 350, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5736011457847143, 'min_weight_fraction_leaf': 0.01499327802887988}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 19:27:15,221] Trial 73 finished with value: 0.8206819922024705 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5774873773238861, 'min_weight_fraction_leaf': 0.01525821862054313}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 19:27:19,381] Trial 74 finished with value: 0.757744710734723 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 349, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5762811196680634, 'min_weight_fraction_leaf': 0.05738463591775203}. Best is trial 64 with value: 0.8222903552251639.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:27:24,190] Trial 75 finished with value: 0.8341042659728318 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 366, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6897650869142653, 'min_weight_fraction_leaf': 0.01699295724662715}. Best is trial 75 with value: 0.8341042659728318.

Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 19:27:33,850] Trial 76 finished with value: 0.6932114115412891 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 282, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6276249804527939, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:27:39,432] Trial 77 finished with value: 0.7736179879945961 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 346, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6860106604269457, 'min_weight_fraction_leaf': 0.05402303529207179}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 19:27:44,139] Trial 78 finished with value: 0.813949181726124 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 315, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5980986566216576, 'min_weight_fraction_leaf': 0.015874867623379977}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 19:27:47,368] Trial 79 finished with value: 0.8148075508248365 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 319, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5974077353274219, 'min_weight_fraction_leaf': 0.016952934933519306}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 19:27:50,257] Trial 80 finished with value: 0.7634124402696214 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 369, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6964413979919954, 'min_weight_fraction_leaf': 0.0668445758500843}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 19:27:53,584] Trial 81 finished with value: 0.8043264560867819 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 327, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6028287214634628, 'min_weight_fraction_leaf': 0.019698090759364247}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:27:56,890] Trial 82 finished with value: 0.825520700701192 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6447745636875917, 'min_weight_fraction_leaf': 0.014088129044148126}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:28:00,115] Trial 83 finished with value: 0.7737596895505442 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6613249054381096, 'min_weight_fraction_leaf': 0.049382122632357986}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:28:02,805] Trial 84 finished with value: 0.7912265923084251 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 262, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6376718422078788, 'min_weight_fraction_leaf': 0.02767427873036585}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:28:07,106] Trial 85 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5668354615852755, 'min_weight_fraction_leaf': 0.3673468061584153}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 19:28:10,618] Trial 86 finished with value: 0.738227266918584 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 319, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5038018885310944, 'min_weight_fraction_leaf': 0.09739016972229436}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 19:28:13,955] Trial 87 finished with value: 0.8310225034786207 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 238, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5549694654820233, 'min_weight_fraction_leaf': 0.01192590165034482}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 19:28:18,893] Trial 88 finished with value: 0.6788431676940953 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 243, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5553686095650655, 'min_weight_fraction_leaf': 0.23418814674021785}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 19:28:21,730] Trial 89 finished with value: 0.734022260482132 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 299, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6175752618294499, 'min_weight_fraction_leaf': 0.04505581233836201}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:28:23,758] Trial 90 finished with value: 0.7937581648472324 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 206, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6438026560737754, 'min_weight_fraction_leaf': 0.031112110300211236}. Best is trial 75 with value: 0.8341042659728318.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 19:28:26,772] Trial 91 finished with value: 0.8215114370817034 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 357, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5809298740197136, 'min_weight_fraction_leaf': 0.0093453186611939}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 19:28:29,513] Trial 92 finished with value: 0.7914367316399507 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 341, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5799350621984959, 'min_weight_fraction_leaf': 0.010109548479063073}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8755364806866953
[I 2024-04-14 19:28:32,870] Trial 93 finished with value: 0.8302689286307254 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 378, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5462779986734955, 'min_weight_fraction_leaf': 0.011947741376939065}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 19:28:36,060] Trial 94 finished with value: 0.785895542293259 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 375, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5430402594252137, 'min_weight_fraction_leaf': 0.02952432304402158}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:28:39,384] Trial 95 finished with value: 0.7627277106060983 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 390, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6968183041958589, 'min_weight_fraction_leaf': 0.060125990052631834}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:28:41,343] Trial 96 finished with value: 0.6917606537229914 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 234, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4906008497769984, 'min_weight_fraction_leaf': 0.04390780435102282}. Best is trial 75 with value: 0.8341042659728318.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:28:44,375] Trial 97 finished with value: 0.836555836726496 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.678838159065027, 'min_weight_fraction_leaf': 0.011359003866057657}. Best is trial 97 with value: 0.836555836726496.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.8798283261802575
[I 2024-04-14 19:28:47,887] Trial 98 finished with value: 0.8302025462762238 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 391, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6738963889937724, 'min_weight_fraction_leaf': 0.0008363114070352451}. Best is trial 97 with value: 0.836555836726496.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.779467680608365

[I 2024-04-14 19:28:51,091] A new study created in memory with name: no-name-6d3f8084-dc46-4809-9303-96add68ccd0f

Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 19:28:51,075] Trial 99 finished with value: 0.7580279704255228 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 389, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7385473779596855, 'min_weight_fraction_leaf': 0.02767948623325216}. Best is trial 97 with value: 0.836555836726496.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.836555836726496], datetime_start=datetime.datetime(2024, 4, 14, 19, 28, 41, 348265), datetime_complete=datetime.datetime(2024, 4, 14, 19, 28, 44, 374887), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 362, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.678838159065027, 'min_weight_fraction_leaf': 0.011359003866057657}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=97, value=None)


* Best Score for C-index:
 0.836555836726496

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23585685825736938
Fold 2 IBS: 0.2109839412282044
Fold 3 IBS: 0.21412659740794365
Fold 4 IBS: 0.21875528396418892
Fold 5 IBS: 0.21015182465139992
[I 2024-04-14 19:28:56,234] Trial 0 finished with value: 0.21797490110182122 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-14 19:29:04,351] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.2439819669765653
Fold 2 IBS: 0.2256456519845257
Fold 3 IBS: 0.22435648382447151
Fold 4 IBS: 0.23651721203568418
Fold 5 IBS: 0.2256208789540953
[I 2024-04-14 19:29:11,459] Trial 2 finished with value: 0.23122443875506843 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24532302893581745
Fold 2 IBS: 0.22600621799098158
Fold 3 IBS: 0.22638117048276798
Fold 4 IBS: 0.23824717142575275
Fold 5 IBS: 0.22593765243453734
[I 2024-04-14 19:29:13,826] Trial 3 finished with value: 0.23237904825397143 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-14 19:29:20,033] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-14 19:29:22,955] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.23401431845594178
Fold 2 IBS: 0.2093895811788793
Fold 3 IBS: 0.21530466495540002
Fold 4 IBS: 0.22104034767557193
Fold 5 IBS: 0.2128862532028971
[I 2024-04-14 19:29:29,019] Trial 6 finished with value: 0.21852703309373803 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.2409758305274641
Fold 2 IBS: 0.22176120105738192
Fold 3 IBS: 0.21997447641870563
Fold 4 IBS: 0.23197184876210186
Fold 5 IBS: 0.22085790811033054
[I 2024-04-14 19:29:32,543] Trial 7 finished with value: 0.2271082529751968 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24197053717762343
Fold 2 IBS: 0.22568522350748885
Fold 3 IBS: 0.22831266845131742
Fold 4 IBS: 0.23836792873299817
Fold 5 IBS: 0.22580413242447955
[I 2024-04-14 19:29:33,458] Trial 8 finished with value: 0.2320280980587815 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.2455652407518667
Fold 2 IBS: 0.23128441262450836
Fold 3 IBS: 0.22851660174776597
Fold 4 IBS: 0.24004255252880102
Fold 5 IBS: 0.22917223868673675
[I 2024-04-14 19:29:43,351] Trial 9 finished with value: 0.23491620926793577 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-14 19:29:51,319] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.23989277486634217
Fold 2 IBS: 0.22039591160187819
Fold 3 IBS: 0.22144486292617946
Fold 4 IBS: 0.22950231089972453
Fold 5 IBS: 0.221411730203088
[I 2024-04-14 19:30:04,535] Trial 11 finished with value: 0.22652951809944244 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21797490110182122.
Fold 1 IBS: 0.23077854275051773
Fold 2 IBS: 0.20498021525881208
Fold 3 IBS: 0.2091231517550083
Fold 4 IBS: 0.21219961560856726
Fold 5 IBS: 0.20523261190946868
[I 2024-04-14 19:30:15,614] Trial 12 finished with value: 0.21246282745647482 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2399650355604067
Fold 2 IBS: 0.21970154426905525
Fold 3 IBS: 0.22052880969997987
Fold 4 IBS: 0.22739994581399575
Fold 5 IBS: 0.21762661776907255
[I 2024-04-14 19:30:27,490] Trial 13 finished with value: 0.225044390622502 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2395431683896394
Fold 2 IBS: 0.21991165641706717
Fold 3 IBS: 0.22159606621372913
Fold 4 IBS: 0.22912694554889002
Fold 5 IBS: 0.21830961583916977
[I 2024-04-14 19:30:36,525] Trial 14 finished with value: 0.22569749048169913 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.21246282745647482.

Fold 1 IBS: 0.239828937780681
Fold 2 IBS: 0.21927859682244577
Fold 3 IBS: 0.22111060791027468
Fold 4 IBS: 0.22856613100551462
Fold 5 IBS: 0.21733565361795007
[I 2024-04-14 19:30:49,023] Trial 15 finished with value: 0.22522398542737326 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24596769858534037
Fold 2 IBS: 0.23138029339401794
Fold 3 IBS: 0.22859763070366051
Fold 4 IBS: 0.2405233873643777
Fold 5 IBS: 0.22936993903611647
[I 2024-04-14 19:31:06,833] Trial 16 finished with value: 0.23516778981670255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2310996610925315
Fold 2 IBS: 0.21281064961959256
Fold 3 IBS: 0.21867877900720747
Fold 4 IBS: 0.21901790329240847
Fold 5 IBS: 0.21204446102199587
[I 2024-04-14 19:31:15,213] Trial 17 finished with value: 0.21873029080674716 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-14 19:31:18,374] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23976258020108482
Fold 2 IBS: 0.21799715613788434
Fold 3 IBS: 0.22035961287850053
Fold 4 IBS: 0.22741466680115968
Fold 5 IBS: 0.21711078965147532
[I 2024-04-14 19:31:27,247] Trial 19 finished with value: 0.22452896113402093 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24945993364630784
Fold 2 IBS: 0.2320560179118942
Fold 3 IBS: 0.22673116653025222
Fold 4 IBS: 0.2404686527240072
Fold 5 IBS: 0.23045901092377374
[I 2024-04-14 19:31:27,962] Trial 20 finished with value: 0.235834956347247 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2355359290627521
Fold 2 IBS: 0.2104144345624633
Fold 3 IBS: 0.21473790413974397
Fold 4 IBS: 0.2209616352932694
Fold 5 IBS: 0.2126553073905229
[I 2024-04-14 19:31:38,953] Trial 21 finished with value: 0.21886104208975032 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2334127051026625
Fold 2 IBS: 0.21168460603965406
Fold 3 IBS: 0.21509284382409244
Fold 4 IBS: 0.22023068530196063
Fold 5 IBS: 0.2131988375077777
[I 2024-04-14 19:31:54,488] Trial 22 finished with value: 0.21872393555522945 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23572210435413657
Fold 2 IBS: 0.2099016121079893
Fold 3 IBS: 0.2140533564878653
Fold 4 IBS: 0.21938633770711632
Fold 5 IBS: 0.21095805029752102
[I 2024-04-14 19:32:04,957] Trial 23 finished with value: 0.21800429219092568 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2363014019421983
Fold 2 IBS: 0.21151765242656453
Fold 3 IBS: 0.21496359766273918
Fold 4 IBS: 0.21979892605046858
Fold 5 IBS: 0.2101002042724613
[I 2024-04-14 19:32:11,257] Trial 24 finished with value: 0.21853635647088637 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24183584565606747
Fold 2 IBS: 0.22191932808356524
Fold 3 IBS: 0.21944496840875904
Fold 4 IBS: 0.2322139551642192
Fold 5 IBS: 0.2218484279847713
[I 2024-04-14 19:32:16,904] Trial 25 finished with value: 0.22745250505947645 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23945873759332073
Fold 2 IBS: 0.21815447359223267
Fold 3 IBS: 0.2203321305940219
Fold 4 IBS: 0.22652804709513938
Fold 5 IBS: 0.2171264729964799
[I 2024-04-14 19:32:26,084] Trial 26 finished with value: 0.22431997237423892 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8454924050883471, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24023940683059092
Fold 2 IBS: 0.22083547380828175
Fold 3 IBS: 0.2218275700826917
Fold 4 IBS: 0.2314840515800722
Fold 5 IBS: 0.2203402431820872
[I 2024-04-14 19:32:29,288] Trial 27 finished with value: 0.22694534909674474 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23380923853384486
Fold 2 IBS: 0.2166521850791028
Fold 3 IBS: 0.22055403220785802
Fold 4 IBS: 0.22386128935143673
Fold 5 IBS: 0.21494560741650007
[I 2024-04-14 19:32:36,145] Trial 28 finished with value: 0.2219644705177485 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.10561943508937117}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24350097269026458
Fold 2 IBS: 0.22931066532348535
Fold 3 IBS: 0.2274935255592419
Fold 4 IBS: 0.236721348319726
Fold 5 IBS: 0.22667406766101417
[I 2024-04-14 19:32:42,736] Trial 29 finished with value: 0.23274011591074642 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.21246282745647482.

Fold 1 IBS: 0.23852023407558698
Fold 2 IBS: 0.22085127198360574
Fold 3 IBS: 0.22246208066369713
Fold 4 IBS: 0.22864256467493396
Fold 5 IBS: 0.21968838126903262
[I 2024-04-14 19:32:50,666] Trial 30 finished with value: 0.22603290653337127 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23299946909800737
Fold 2 IBS: 0.20723625804859605
Fold 3 IBS: 0.21221943785442013
Fold 4 IBS: 0.2177017964639846
Fold 5 IBS: 0.20854416781687213
[I 2024-04-14 19:32:57,065] Trial 31 finished with value: 0.21574022585637603 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362712139580162, 'min_weight_fraction_leaf': 0.0012002559281581464}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23329576386854547
Fold 2 IBS: 0.20864866291155204
Fold 3 IBS: 0.21077397107349774
Fold 4 IBS: 0.2160699109888221
Fold 5 IBS: 0.21065826025368684
[I 2024-04-14 19:33:06,379] Trial 32 finished with value: 0.21588931381922083 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6227992821807525, 'min_weight_fraction_leaf': 0.07179554342829253}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.24306153681199408
Fold 2 IBS: 0.22512404676788447
Fold 3 IBS: 0.22331772565995167
Fold 4 IBS: 0.23524719585690623
Fold 5 IBS: 0.224780617699734
[I 2024-04-14 19:33:13,433] Trial 33 finished with value: 0.2303062245592941 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 417, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6246674823350934, 'min_weight_fraction_leaf': 0.04929766610098481}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.23698248236362535
Fold 2 IBS: 0.21618699235488542
Fold 3 IBS: 0.2178869077744494
Fold 4 IBS: 0.22262991707187765
Fold 5 IBS: 0.21381894139135835
[I 2024-04-14 19:33:22,798] Trial 34 finished with value: 0.22150104819123922 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8180483921418293, 'min_weight_fraction_leaf': 0.12662220369343266}. Best is trial 12 with value: 0.21246282745647482.
Fold 1 IBS: 0.2310199794772503
Fold 2 IBS: 0.2024023719139507
Fold 3 IBS: 0.20669880623128378
Fold 4 IBS: 0.21092184504583145
Fold 5 IBS: 0.20560444264311953
[I 2024-04-14 19:33:27,755] Trial 35 finished with value: 0.21132948906228716 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 292, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.525544897367368, 'min_weight_fraction_leaf': 0.03874252122688228}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23001935349254238
Fold 2 IBS: 0.20485403814848732
Fold 3 IBS: 0.20682929538329672
Fold 4 IBS: 0.21591978157548516
Fold 5 IBS: 0.20626930124225762
[I 2024-04-14 19:33:32,922] Trial 36 finished with value: 0.21277835396841382 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 292, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.39581174032589594, 'min_weight_fraction_leaf': 0.031238193058764258}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23154981216684778
Fold 2 IBS: 0.2064096224008439
Fold 3 IBS: 0.208465263650005
Fold 4 IBS: 0.21691466100790038
Fold 5 IBS: 0.20633283892563786
[I 2024-04-14 19:33:37,953] Trial 37 finished with value: 0.213934439630247 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 216, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3907069630963366, 'min_weight_fraction_leaf': 0.030440421568832744}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23206947465441122
Fold 2 IBS: 0.2078551531476867
Fold 3 IBS: 0.21089757368337175
Fold 4 IBS: 0.22336843190578887
Fold 5 IBS: 0.21283383989106805
[I 2024-04-14 19:33:41,925] Trial 38 finished with value: 0.21740489465646534 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 199, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40232445463607813, 'min_weight_fraction_leaf': 0.022216332318415407}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23986526356765303
Fold 2 IBS: 0.22169871700287505
Fold 3 IBS: 0.22505665482896112
Fold 4 IBS: 0.2346684878456743
Fold 5 IBS: 0.22485697735227608
[I 2024-04-14 19:33:44,989] Trial 39 finished with value: 0.22922922011948793 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.28424052756646667, 'min_weight_fraction_leaf': 0.03401048379052402}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23787018625762488
Fold 2 IBS: 0.22182147769003757
Fold 3 IBS: 0.2242994999503461
Fold 4 IBS: 0.22950528863950773
Fold 5 IBS: 0.2215174511653471
[I 2024-04-14 19:33:48,578] Trial 40 finished with value: 0.22700278074057265 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 228, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4201868988545198, 'min_weight_fraction_leaf': 0.11561130788218002}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2372966707916344
Fold 2 IBS: 0.2028847016290367
Fold 3 IBS: 0.2015470375001461
Fold 4 IBS: 0.2212712313321188
Fold 5 IBS: 0.20888581099089984
[I 2024-04-14 19:33:52,745] Trial 41 finished with value: 0.21437709044876718 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 302, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5148221916816225, 'min_weight_fraction_leaf': 0.001151469558608545}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23434538123965318
Fold 2 IBS: 0.20853594804436915
Fold 3 IBS: 0.21092606279332207
Fold 4 IBS: 0.21997450427899343
Fold 5 IBS: 0.21032487309350506
[I 2024-04-14 19:33:56,316] Trial 42 finished with value: 0.2168213538899686 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 286, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.49736600647348106, 'min_weight_fraction_leaf': 0.06070225490406626}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23464644546128038
Fold 2 IBS: 0.20586610504904418
Fold 3 IBS: 0.21108954233849955
Fold 4 IBS: 0.22369852785781755
Fold 5 IBS: 0.21317929922286188
[I 2024-04-14 19:33:59,083] Trial 43 finished with value: 0.21769598398590068 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 178, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.35047561051666104, 'min_weight_fraction_leaf': 0.02619033998019891}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24333051067575723
Fold 2 IBS: 0.22501668698749652
Fold 3 IBS: 0.2227059709800223
Fold 4 IBS: 0.23657634956076623
Fold 5 IBS: 0.22479296948207325
[I 2024-04-14 19:34:04,265] Trial 44 finished with value: 0.2304844975372231 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 285, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5356329292060192, 'min_weight_fraction_leaf': 0.048808228983234156}. Best is trial 35 with value: 0.21132948906228716.

Fold 1 IBS: 0.23535635522895523
Fold 2 IBS: 0.19710426247292917
Fold 3 IBS: 0.20557962919622366
Fold 4 IBS: 0.21419277453695665
Fold 5 IBS: 0.20885872177069337
[I 2024-04-14 19:34:08,849] Trial 45 finished with value: 0.2122183486411516 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 226, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4468362954201356, 'min_weight_fraction_leaf': 0.022410036988178828}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23697226819401304
Fold 2 IBS: 0.21729894679225342
Fold 3 IBS: 0.21924579151831378
Fold 4 IBS: 0.22736263277866023
Fold 5 IBS: 0.21648723912795567
[I 2024-04-14 19:34:14,734] Trial 46 finished with value: 0.2234733756822392 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4404091377971465, 'min_weight_fraction_leaf': 0.0879920966146258}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2461763063865299
Fold 2 IBS: 0.23210038584430207
Fold 3 IBS: 0.22962662262622974
Fold 4 IBS: 0.2411075523095139
Fold 5 IBS: 0.23017348027867315
[I 2024-04-14 19:34:19,981] Trial 47 finished with value: 0.23583686948904975 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 151, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.22405207438014219, 'min_weight_fraction_leaf': 0.15203659778952378}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24666742425905117
Fold 2 IBS: 0.23236914915160214
Fold 3 IBS: 0.22960567029225595
Fold 4 IBS: 0.24127144751807053
Fold 5 IBS: 0.23014903819747332
[I 2024-04-14 19:34:26,437] Trial 48 finished with value: 0.23601254588369064 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 177, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.36038261603340377, 'min_weight_fraction_leaf': 0.4232459400228781}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24430819200769513
Fold 2 IBS: 0.22679228560405634
Fold 3 IBS: 0.22458075787871798
Fold 4 IBS: 0.23381361065171355
Fold 5 IBS: 0.22509732827993834
[I 2024-04-14 19:34:29,252] Trial 49 finished with value: 0.23091843488442426 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 114, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.20295168361746668, 'min_weight_fraction_leaf': 0.028375312606034528}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.24702382172674314
Fold 2 IBS: 0.232318745884667
Fold 3 IBS: 0.22978154274033197
Fold 4 IBS: 0.24116379679743785
Fold 5 IBS: 0.23057060543248775
[I 2024-04-14 19:34:35,497] Trial 50 finished with value: 0.23617170251633351 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 247, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.310704861435272, 'min_weight_fraction_leaf': 0.3163091534745454}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2371997639542927
Fold 2 IBS: 0.20287492980460803
Fold 3 IBS: 0.2010534314204571
Fold 4 IBS: 0.2199161264829775
Fold 5 IBS: 0.2091644231071567
[I 2024-04-14 19:34:43,188] Trial 51 finished with value: 0.21404173495389842 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 307, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5262968044798497, 'min_weight_fraction_leaf': 0.0005502265382308967}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23340285748939266
Fold 2 IBS: 0.2103004750100177
Fold 3 IBS: 0.21254949012757765
Fold 4 IBS: 0.22125709350379033
Fold 5 IBS: 0.21405910491883784
[I 2024-04-14 19:34:50,519] Trial 52 finished with value: 0.21831380420992322 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 327, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.45046128931810375, 'min_weight_fraction_leaf': 0.062433906006724466}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23951518069671124
Fold 2 IBS: 0.21511489478979384
Fold 3 IBS: 0.21427307540212315
Fold 4 IBS: 0.23114523284371163
Fold 5 IBS: 0.2177754388998862
[I 2024-04-14 19:34:54,072] Trial 53 finished with value: 0.22356476452644522 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 219, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5802842056975928, 'min_weight_fraction_leaf': 0.0228463676344103}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.2294603060430549
Fold 2 IBS: 0.20648137990863727
Fold 3 IBS: 0.2073507344488135
Fold 4 IBS: 0.21201412462921795
Fold 5 IBS: 0.20518046511594823
[I 2024-04-14 19:34:58,558] Trial 54 finished with value: 0.21209740202913435 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 268, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.45786130845956585, 'min_weight_fraction_leaf': 0.04070739223145016}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23601480280360246
Fold 2 IBS: 0.21588512872171312
Fold 3 IBS: 0.21817367585432837
Fold 4 IBS: 0.22656110143576336
Fold 5 IBS: 0.2162967711713978
[I 2024-04-14 19:35:03,847] Trial 55 finished with value: 0.22258629599736102 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4641737804722843, 'min_weight_fraction_leaf': 0.08551025986155897}. Best is trial 35 with value: 0.21132948906228716.
Fold 1 IBS: 0.23210499549350713
Fold 2 IBS: 0.19692965285403322
Fold 3 IBS: 0.2064340374063009
Fold 4 IBS: 0.20506141318697788
Fold 5 IBS: 0.1971187636853533
[I 2024-04-14 19:35:10,001] Trial 56 finished with value: 0.20752977252523447 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 341, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.37757258938870664, 'min_weight_fraction_leaf': 0.03960758211129986}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23845889782290072
Fold 2 IBS: 0.22481512830252323
Fold 3 IBS: 0.224556794519945
Fold 4 IBS: 0.23192837150634746
Fold 5 IBS: 0.22105761643448346
[I 2024-04-14 19:35:15,929] Trial 57 finished with value: 0.22816336171723997 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 269, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.27663853585083453, 'min_weight_fraction_leaf': 0.05590915506760377}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23509899171357032
Fold 2 IBS: 0.21878922018241584
Fold 3 IBS: 0.22304312110383104
Fold 4 IBS: 0.22405272437913187
Fold 5 IBS: 0.21494923878801575
[I 2024-04-14 19:35:24,299] Trial 58 finished with value: 0.22318665923339295 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5540450495358851, 'min_weight_fraction_leaf': 0.09986603842125079}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2288010200574269
Fold 2 IBS: 0.20499639396831307
Fold 3 IBS: 0.21690288880359831
Fold 4 IBS: 0.2124003661803745
Fold 5 IBS: 0.20449517441903264
[I 2024-04-14 19:35:28,124] Trial 59 finished with value: 0.21351916868574908 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.3509389761390235, 'min_weight_fraction_leaf': 0.07465720864035902}. Best is trial 56 with value: 0.20752977252523447.

Fold 1 IBS: 0.24665906141024754
Fold 2 IBS: 0.23238673943832674
Fold 3 IBS: 0.22958317859156768
Fold 4 IBS: 0.24137956784118675
Fold 5 IBS: 0.23028136399594556
[I 2024-04-14 19:35:33,038] Trial 60 finished with value: 0.23605798225545485 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 323, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.43142720229784703, 'min_weight_fraction_leaf': 0.48740241401755297}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2321959013757636
Fold 2 IBS: 0.2007164455461997
Fold 3 IBS: 0.20770062793391472
Fold 4 IBS: 0.20602392627423452
Fold 5 IBS: 0.19819621614422855
[I 2024-04-14 19:35:36,340] Trial 61 finished with value: 0.20896662345486822 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 193, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.34253183106774565, 'min_weight_fraction_leaf': 0.042959104672555634}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24129092702164456
Fold 2 IBS: 0.1940864249892709
Fold 3 IBS: 0.20445239603158735
Fold 4 IBS: 0.20177530657660103
Fold 5 IBS: 0.19641445065405433
[I 2024-04-14 19:35:40,874] Trial 62 finished with value: 0.20760390105463164 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4829578594466043, 'min_weight_fraction_leaf': 0.015417748095042628}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2438600498093446
Fold 2 IBS: 0.19339888761579696
Fold 3 IBS: 0.20511027589080238
Fold 4 IBS: 0.2020267512866158
Fold 5 IBS: 0.19974957277674807
[I 2024-04-14 19:35:44,558] Trial 63 finished with value: 0.20882910747586156 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 199, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4803020994632342, 'min_weight_fraction_leaf': 0.0178205092103982}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24555187702625741
Fold 2 IBS: 0.19258549198278238
Fold 3 IBS: 0.2081841849780967
Fold 4 IBS: 0.19873785239924144
Fold 5 IBS: 0.2026167159542672
[I 2024-04-14 19:35:47,764] Trial 64 finished with value: 0.20953522446812906 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 181, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4774266418532833, 'min_weight_fraction_leaf': 0.015960985611362433}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23775380834030116
Fold 2 IBS: 0.19861672834479435
Fold 3 IBS: 0.20921122217299923
Fold 4 IBS: 0.20268236981529783
Fold 5 IBS: 0.19463272538546011
[I 2024-04-14 19:35:51,108] Trial 65 finished with value: 0.20857937081177055 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 187, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.486147787500794, 'min_weight_fraction_leaf': 0.045698123637175965}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2501009906307814
Fold 2 IBS: 0.19560469256423904
Fold 3 IBS: 0.2013531178434995
Fold 4 IBS: 0.20240548396604943
Fold 5 IBS: 0.19742923218386338
[I 2024-04-14 19:35:54,542] Trial 66 finished with value: 0.20937870343768655 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 172, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5957538083039283, 'min_weight_fraction_leaf': 0.016756492980836386}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24073623571542466
Fold 2 IBS: 0.19904536378768864
Fold 3 IBS: 0.2072772055909507
Fold 4 IBS: 0.20431096174337093
Fold 5 IBS: 0.19751429463626025
[I 2024-04-14 19:35:59,114] Trial 67 finished with value: 0.20977681229473905 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 190, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5970548145736715, 'min_weight_fraction_leaf': 0.015632853202988805}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23489637068098582
Fold 2 IBS: 0.193544326767571
Fold 3 IBS: 0.21092412883744385
Fold 4 IBS: 0.2002444197679992
Fold 5 IBS: 0.20189264522954573
[I 2024-04-14 19:36:01,882] Trial 68 finished with value: 0.20830037825670913 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 124, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5534520440577227, 'min_weight_fraction_leaf': 0.06629333378490466}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23931787579206773
Fold 2 IBS: 0.19084396852936297
Fold 3 IBS: 0.2144928305905132
Fold 4 IBS: 0.19753590970221943
Fold 5 IBS: 0.19667239381712792
[I 2024-04-14 19:36:04,290] Trial 69 finished with value: 0.20777259568625825 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 80, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6808825798677897, 'min_weight_fraction_leaf': 0.06555713548594481}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.23171524768921273
Fold 2 IBS: 0.19751283454034116
Fold 3 IBS: 0.21284229688671272
Fold 4 IBS: 0.20495487374716068
Fold 5 IBS: 0.20475925584287327
[I 2024-04-14 19:36:06,375] Trial 70 finished with value: 0.21035690174126015 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 81, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7031805053141511, 'min_weight_fraction_leaf': 0.12952844171116187}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.24048053796318772
Fold 2 IBS: 0.1905442518290532
Fold 3 IBS: 0.21394807021334242
Fold 4 IBS: 0.1968562583018759
Fold 5 IBS: 0.20101728345045664
[I 2024-04-14 19:36:07,563] Trial 71 finished with value: 0.20856928035158315 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 51, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.676678599385812, 'min_weight_fraction_leaf': 0.06780430049274452}. Best is trial 56 with value: 0.20752977252523447.
Fold 1 IBS: 0.2347687448942329
Fold 2 IBS: 0.19207087212945004
Fold 3 IBS: 0.2087059109834091
Fold 4 IBS: 0.1993046128273454
Fold 5 IBS: 0.20260855491451796
[I 2024-04-14 19:36:08,740] Trial 72 finished with value: 0.2074917391497911 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 57, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7134910869727897, 'min_weight_fraction_leaf': 0.0694822375534185}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23816508193559668
Fold 2 IBS: 0.19181748584543223
Fold 3 IBS: 0.21845896954436658
Fold 4 IBS: 0.1993979863461671
Fold 5 IBS: 0.1982536936258922
[I 2024-04-14 19:36:09,853] Trial 73 finished with value: 0.20921864345949098 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 51, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.0645866992350865}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23508193319089465
Fold 2 IBS: 0.20740453808064727
Fold 3 IBS: 0.2244228921767311
Fold 4 IBS: 0.2115513627397087
Fold 5 IBS: 0.20330070970220407
[I 2024-04-14 19:36:10,249] Trial 74 finished with value: 0.21635228717803717 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 10, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7365855471939977, 'min_weight_fraction_leaf': 0.11029683626238679}. Best is trial 72 with value: 0.2074917391497911.

Fold 1 IBS: 0.2355921510352545
Fold 2 IBS: 0.18988955633106214
Fold 3 IBS: 0.2175269995788695
Fold 4 IBS: 0.1993059384582704
Fold 5 IBS: 0.19950554004549564
[I 2024-04-14 19:36:11,861] Trial 75 finished with value: 0.20836403708979043 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 62, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6761462774417768, 'min_weight_fraction_leaf': 0.07610410535003291}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2331646523531711
Fold 2 IBS: 0.19585793938278617
Fold 3 IBS: 0.21617307743244904
Fold 4 IBS: 0.20830690666506493
Fold 5 IBS: 0.2045693433216475
[I 2024-04-14 19:36:14,122] Trial 76 finished with value: 0.21161438383102374 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 52, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7683896711777872, 'min_weight_fraction_leaf': 0.07601195190861526}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23185803913727424
Fold 2 IBS: 0.1927053846142274
Fold 3 IBS: 0.21437990964313605
Fold 4 IBS: 0.20539476908050203
Fold 5 IBS: 0.20030669041348295
[I 2024-04-14 19:36:16,320] Trial 77 finished with value: 0.20892895857772453 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 86, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6772401875471966, 'min_weight_fraction_leaf': 0.09086495963124246}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2270528425436531
Fold 2 IBS: 0.20370693909806606
Fold 3 IBS: 0.21607794076802184
Fold 4 IBS: 0.21234078175322665
Fold 5 IBS: 0.20551197188342696
[I 2024-04-14 19:36:18,492] Trial 78 finished with value: 0.21293809520927892 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 33, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7174939715412089, 'min_weight_fraction_leaf': 0.15014407446734546}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2312106184137957
Fold 2 IBS: 0.1961557598326469
Fold 3 IBS: 0.21123889666002982
Fold 4 IBS: 0.20277393276288513
Fold 5 IBS: 0.20081089749241096
[I 2024-04-14 19:36:22,796] Trial 79 finished with value: 0.2084380210323537 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 108, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7578020159401693, 'min_weight_fraction_leaf': 0.09730158058764991}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23213572502402638
Fold 2 IBS: 0.19667369083068653
Fold 3 IBS: 0.2115226655645497
Fold 4 IBS: 0.2045619286298977
Fold 5 IBS: 0.20173177276721538
[I 2024-04-14 19:36:24,642] Trial 80 finished with value: 0.20932515656327513 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 73, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7979785314961634, 'min_weight_fraction_leaf': 0.11792446058995482}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23445318807843726
Fold 2 IBS: 0.1951572863760429
Fold 3 IBS: 0.2149660694153711
Fold 4 IBS: 0.20509036683078255
Fold 5 IBS: 0.2042614516727649
[I 2024-04-14 19:36:27,163] Trial 81 finished with value: 0.21078567247467977 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 113, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8295924251336164, 'min_weight_fraction_leaf': 0.09809524482500852}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24192987931784726
Fold 2 IBS: 0.19219909233140817
Fold 3 IBS: 0.20848213760886697
Fold 4 IBS: 0.19898144280286179
Fold 5 IBS: 0.2019881573718024
[I 2024-04-14 19:36:30,413] Trial 82 finished with value: 0.2087161418865573 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 130, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7036492405946972, 'min_weight_fraction_leaf': 0.053381019620523905}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.22986388794534468
Fold 2 IBS: 0.21179429717870366
Fold 3 IBS: 0.21642801921738683
Fold 4 IBS: 0.22351663563840726
Fold 5 IBS: 0.21359141032237122
[I 2024-04-14 19:36:32,698] Trial 83 finished with value: 0.2190388500604427 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 94, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7605047675747114, 'min_weight_fraction_leaf': 0.2113346050152473}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23494715234361263
Fold 2 IBS: 0.19543709284877217
Fold 3 IBS: 0.21414705144727122
Fold 4 IBS: 0.20223153004395855
Fold 5 IBS: 0.20029382839151266
[I 2024-04-14 19:36:35,541] Trial 84 finished with value: 0.20941133101502546 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 65, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6555570970853588, 'min_weight_fraction_leaf': 0.08005891040211782}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24640023232104058
Fold 2 IBS: 0.20948308532194032
Fold 3 IBS: 0.21812591127612121
Fold 4 IBS: 0.202827254816637
Fold 5 IBS: 0.20665107372351849
[I 2024-04-14 19:36:36,536] Trial 85 finished with value: 0.2166975114918515 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 28, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7818442849676701, 'min_weight_fraction_leaf': 0.06296555688051952}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24689816456522876
Fold 2 IBS: 0.23119434850668188
Fold 3 IBS: 0.22764888220532994
Fold 4 IBS: 0.24146149236347472
Fold 5 IBS: 0.22996493860216796
[I 2024-04-14 19:36:39,210] Trial 86 finished with value: 0.23543356524857667 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 99, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.563811671779571, 'min_weight_fraction_leaf': 0.27909147913563276}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.236011373107941
Fold 2 IBS: 0.1985884074612493
Fold 3 IBS: 0.20780546781507445
Fold 4 IBS: 0.2010388764949602
Fold 5 IBS: 0.19713896823850197
[I 2024-04-14 19:36:44,424] Trial 87 finished with value: 0.2081166186235454 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 127, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6062813764421088, 'min_weight_fraction_leaf': 0.06500929470204342}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.235645944677044
Fold 2 IBS: 0.22141885901720673
Fold 3 IBS: 0.2207856197944425
Fold 4 IBS: 0.2274282881509803
Fold 5 IBS: 0.2171444297396915
[I 2024-04-14 19:36:47,303] Trial 88 finished with value: 0.224484628275873 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 63, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6109295734326579, 'min_weight_fraction_leaf': 0.1387676132958523}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23784860552840467
Fold 2 IBS: 0.19256619074642353
Fold 3 IBS: 0.21706996017379332
Fold 4 IBS: 0.19359579678495026
Fold 5 IBS: 0.19769481439808093
[I 2024-04-14 19:36:49,356] Trial 89 finished with value: 0.20775507352633055 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 40, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6729644923369325, 'min_weight_fraction_leaf': 0.07107523629976642}. Best is trial 72 with value: 0.2074917391497911.

Fold 1 IBS: 0.2310593691941199
Fold 2 IBS: 0.19290862866485556
Fold 3 IBS: 0.2259889263099397
Fold 4 IBS: 0.20574406592712768
Fold 5 IBS: 0.2036881105655048
[I 2024-04-14 19:36:50,815] Trial 90 finished with value: 0.21187782013230955 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 33, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6403451257560147, 'min_weight_fraction_leaf': 0.1070974205302174}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.2401929507969826
Fold 2 IBS: 0.19402821024539957
Fold 3 IBS: 0.20959009756624364
Fold 4 IBS: 0.19925984870201024
Fold 5 IBS: 0.20019981509015003
[I 2024-04-14 19:36:55,034] Trial 91 finished with value: 0.2086541844801572 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6946924227216443, 'min_weight_fraction_leaf': 0.0691242091082612}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.22426201251922548
Fold 2 IBS: 0.20173365162942716
Fold 3 IBS: 0.22153956363961586
Fold 4 IBS: 0.19772548496651532
Fold 5 IBS: 0.20156108716753926
[I 2024-04-14 19:36:56,355] Trial 92 finished with value: 0.20936435998446462 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 23, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.67119389738411, 'min_weight_fraction_leaf': 0.0860360074958936}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23958587311487037
Fold 2 IBS: 0.19482142117809761
Fold 3 IBS: 0.20810860401827652
Fold 4 IBS: 0.20236991734706367
Fold 5 IBS: 0.20184750385355607
[I 2024-04-14 19:36:59,791] Trial 93 finished with value: 0.20934666390237283 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 61, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7203099531168516, 'min_weight_fraction_leaf': 0.07072043377458338}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23555684453740186
Fold 2 IBS: 0.19463692638306926
Fold 3 IBS: 0.21467835573939015
Fold 4 IBS: 0.19665081190705
Fold 5 IBS: 0.19807333303702296
[I 2024-04-14 19:37:03,847] Trial 94 finished with value: 0.20791925432078684 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 112, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6600067234493434, 'min_weight_fraction_leaf': 0.051204943590137345}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24725948885611485
Fold 2 IBS: 0.19577116275491813
Fold 3 IBS: 0.205693837657292
Fold 4 IBS: 0.20167078820690593
Fold 5 IBS: 0.19954646837579296
[I 2024-04-14 19:37:06,802] Trial 95 finished with value: 0.20998834917020476 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 112, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7494081940450164, 'min_weight_fraction_leaf': 0.049579977587926705}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24563774132454982
Fold 2 IBS: 0.2308792614731597
Fold 3 IBS: 0.22856339226732242
Fold 4 IBS: 0.2408496187728765
Fold 5 IBS: 0.22919426695438144
[I 2024-04-14 19:37:09,845] Trial 96 finished with value: 0.23502485615845797 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 7, 'n_estimators': 122, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6169317504839195, 'min_weight_fraction_leaf': 0.03573079381567339}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.24489162520079863
Fold 2 IBS: 0.22508252682921956
Fold 3 IBS: 0.22585906470442285
Fold 4 IBS: 0.23761976540509713
Fold 5 IBS: 0.225309631739468
[I 2024-04-14 19:37:13,692] Trial 97 finished with value: 0.23175252277580122 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 143, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5463268102121571, 'min_weight_fraction_leaf': 0.09247910817936378}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.22901002816464855
Fold 2 IBS: 0.21300670110379213
Fold 3 IBS: 0.21846007326572212
Fold 4 IBS: 0.22159690447263233
Fold 5 IBS: 0.21511330242953064
[I 2024-04-14 19:37:17,045] Trial 98 finished with value: 0.21943740188726518 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 88, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5769172890423364, 'min_weight_fraction_leaf': 0.16576392984791938}. Best is trial 72 with value: 0.2074917391497911.
Fold 1 IBS: 0.23670674888424822
Fold 2 IBS: 0.2052143070073981
Fold 3 IBS: 0.2105884842412907
Fold 4 IBS: 0.2176003799486971
Fold 5 IBS: 0.20502853904646207
[I 2024-04-14 19:37:21,003] Trial 99 finished with value: 0.21502769182561923 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 162, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6311261654761119, 'min_weight_fraction_leaf': 0.056550705829223946}. Best is trial 72 with value: 0.2074917391497911.


* Best trial for IBS:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.2074917391497911], datetime_start=datetime.datetime(2024, 4, 14, 19, 36, 7, 571162), datetime_complete=datetime.datetime(2024, 4, 14, 19, 36, 8, 739286), params={'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 57, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7134910869727897, 'min_weight_fraction_leaf': 0.0694822375534185}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=72, value=None)


* Best Score for IBS:
 0.2074917391497911

In [61]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [62]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.837
train_ibs:  0.207

#### Test

In [63]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [64]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=18, max_features='auto', max_leaf_nodes=17,
                   max_samples=0.678838159065027, min_samples_leaf=1,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.011359003866057657,
                   n_estimators=362, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.509

ExtraSurvivalTrees(max_depth=7, max_features=None, max_leaf_nodes=15,
                   max_samples=0.7134910869727897, min_samples_split=2,
                   min_weight_fraction_leaf=0.0694822375534185, n_estimators=57,
                   random_state=123)

IBS: 0.259

In [65]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [66]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:37:22,920] A new study created in memory with name: no-name-ec2242a4-bf3b-43fd-a0d8-a76741461787

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:38:06,534] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:38:35,931] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:39:00,016] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:39:32,576] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:39:42,777] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:39:45,687] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:14,989] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:22,740] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:40:23,672] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 19:41:44,465] Trial 9 finished with value: 0.6970416816836329 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 19:43:37,491] Trial 10 finished with value: 0.6727533375211936 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:45:46,994] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 19:47:48,044] Trial 12 finished with value: 0.6915084901128223 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:48:36,931] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:49:42,806] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:50:45,186] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:51:29,331] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:52:54,052] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:54:41,762] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:54:45,778] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:55:26,418] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 19:56:55,248] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6137339055793991
[I 2024-04-14 19:58:25,295] Trial 22 finished with value: 0.6443581285716469 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 19:59:52,942] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:00:57,239] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:02:15,712] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:02:48,885] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:04:14,412] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:04:18,791] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:05:15,402] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:05:32,460] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-14 20:06:46,766] Trial 31 finished with value: 0.6101958569131466 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:08:13,289] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:09:13,575] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:10:17,118] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 20:10:54,981] Trial 35 finished with value: 0.6743933936379024 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:11:28,191] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:11:49,966] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:12:08,333] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:12:30,587] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:12:55,021] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6072961373390557
[I 2024-04-14 20:14:19,941] Trial 41 finished with value: 0.6396344950460795 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:15:19,248] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:16:30,913] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:16:54,736] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:18:44,856] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.6970416816836329.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6802575107296137
[I 2024-04-14 20:18:55,715] Trial 46 finished with value: 0.699938783040987 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:19:14,399] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:19:14,735] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:19:24,989] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:20:08,957] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.7103004291845494
[I 2024-04-14 20:21:06,158] Trial 51 finished with value: 0.6891110661966153 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:21:45,300] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.699938783040987.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.7274678111587983
[I 2024-04-14 20:22:49,549] Trial 53 finished with value: 0.7103874182865171 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:23:36,236] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:23:43,851] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:24:31,079] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 20:24:37,824] Trial 57 finished with value: 0.6890047854219209 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:24:43,982] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:24:53,222] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:25:02,876] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:25:14,535] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 20:25:38,462] Trial 62 finished with value: 0.6974150909475259 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 20:26:00,536] Trial 63 finished with value: 0.6931669071981286 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:26:24,127] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.45557149928260715, 'learning_rate': 0.0340031673751867, 'dropout_rate': 0.8352402756430523, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4320841878399444, 'min_weight_fraction_leaf': 0.262263288003764, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:26:58,182] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.3438614405023237, 'learning_rate': 0.04403843282374086, 'dropout_rate': 0.7239851485767856, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9229393860301199, 'min_weight_fraction_leaf': 0.309698162609194, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0050503952773476865, 'validation_fraction': 0.9403459263609858, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:27:43,034] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.42720539699387877, 'learning_rate': 0.04104596376062255, 'dropout_rate': 0.6411641048875296, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5401195366715463, 'min_weight_fraction_leaf': 0.29863354085488475, 'max_features': 'sqrt', 'min_impurity_decrease': 0.014480191125608608, 'validation_fraction': 0.3085811036906729, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:28:02,902] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.5298851484353428, 'learning_rate': 0.027755653943344206, 'dropout_rate': 0.8089836729353025, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.26956754513635534, 'max_features': 'sqrt', 'min_impurity_decrease': 0.03775558722634611, 'validation_fraction': 0.9048601585941811, 'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:28:19,760] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.4876582694676368, 'learning_rate': 0.0657073123865678, 'dropout_rate': 0.8674995854284298, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 1.2002568362719879, 'min_weight_fraction_leaf': 0.32112921786322346, 'max_features': 1, 'min_impurity_decrease': 0.0017458997835306613, 'validation_fraction': 0.9998752778339147, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:28:34,422] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.9484129728256304, 'learning_rate': 0.06052072438720544, 'dropout_rate': 0.9166855139279758, 'n_estimators': 497, 'criterion': 'friedman_mse', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.28207507977380614, 'max_features': 'log2', 'min_impurity_decrease': 0.011832872184829375, 'validation_fraction': 0.953568420125366, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 20:29:22,889] Trial 70 finished with value: 0.6883943964411052 and parameters: {'subsample': 0.9023508276539349, 'learning_rate': 0.0700250470025932, 'dropout_rate': 0.4501645913744281, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.010068295219290181, 'min_weight_fraction_leaf': 0.41145613042238655, 'max_features': 0.1, 'min_impurity_decrease': 5.018301342173549e-05, 'validation_fraction': 0.7628778309539805, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7188841201716738
[I 2024-04-14 20:29:26,349] Trial 71 finished with value: 0.6952508762004349 and parameters: {'subsample': 0.4100186979142205, 'learning_rate': 0.04906470091498086, 'dropout_rate': 0.9728666594478519, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.23722839553187366, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0011019552130728865, 'validation_fraction': 0.9163857609630027, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:29:31,642] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.31530142016495843, 'learning_rate': 0.0512544853130206, 'dropout_rate': 0.7755480242253493, 'n_estimators': 151, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7530156413438767, 'min_weight_fraction_leaf': 0.2383940530318115, 'max_features': 'sqrt', 'min_impurity_decrease': 1.146086435542451e-05, 'validation_fraction': 0.9193282408968059, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:29:42,508] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.37329268328825294, 'learning_rate': 0.03701842361020617, 'dropout_rate': 0.4981563025706776, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.35666680166132303, 'min_weight_fraction_leaf': 0.24913433692567943, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013992830933391351, 'validation_fraction': 0.8591928424609534, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:29:44,537] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.2750560204205196, 'learning_rate': 0.04837445328457708, 'dropout_rate': 0.9582497574656967, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2638211102311142, 'min_weight_fraction_leaf': 0.38512775736188853, 'max_features': 'sqrt', 'min_impurity_decrease': 7.041464247923928e-06, 'validation_fraction': 0.9758954223995437, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:29:47,065] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.4404072237856687, 'learning_rate': 0.01994639562660709, 'dropout_rate': 0.5736138356445972, 'n_estimators': 99, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9317881303500567, 'min_weight_fraction_leaf': 0.2756234570388064, 'max_features': 'sqrt', 'min_impurity_decrease': 0.007503470003484048, 'validation_fraction': 0.9024163935083236, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:29:58,169] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.4918260327899229, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.35567267340087927, 'n_estimators': 198, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6097069779418983, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'sqrt', 'min_impurity_decrease': 0.023728799495950186, 'validation_fraction': 0.23951296722702176, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:30:19,837] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.42468600594731076, 'learning_rate': 0.014667395469136795, 'dropout_rate': 0.9118766474669582, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 5.674168126071088, 'min_weight_fraction_leaf': 0.2227746203792833, 'max_features': 'log2', 'min_impurity_decrease': 0.09875135917494669, 'validation_fraction': 0.9453177103288871, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.7103874182865171.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 20:30:49,156] Trial 78 finished with value: 0.7114957764128979 and parameters: {'subsample': 0.5109023203910539, 'learning_rate': 0.03158550801216725, 'dropout_rate': 0.7413014948736192, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25025224628887144, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.8776959526028103, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:31:27,559] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.525173705501519, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.7358383866611962, 'n_estimators': 463, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3699011999189556, 'min_weight_fraction_leaf': 0.24753153974472775, 'max_features': 1, 'min_impurity_decrease': 1.7270049584147727e-05, 'validation_fraction': 0.7980717773125984, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:31:33,639] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.567277013704589, 'learning_rate': 0.0051737974312490425, 'dropout_rate': 0.8482250914454597, 'n_estimators': 234, 'criterion': 'squared_error', 'ccp_alpha': 1.0339954917997785, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 3.5709870090356114e-05, 'validation_fraction': 0.8784998948355119, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 20:31:59,526] Trial 81 finished with value: 0.7051288500977226 and parameters: {'subsample': 0.47503146759741444, 'learning_rate': 0.04319851444329214, 'dropout_rate': 0.7985055948276671, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.02620579447326436, 'min_weight_fraction_leaf': 0.25486217792887067, 'max_features': 'sqrt', 'min_impurity_decrease': 7.44382247583082e-05, 'validation_fraction': 0.9164360167013661, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:32:23,547] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.507685743919513, 'learning_rate': 0.04335900283106986, 'dropout_rate': 0.7955521476520806, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.29362607241963007, 'min_weight_fraction_leaf': 0.25819868071808755, 'max_features': 'sqrt', 'min_impurity_decrease': 4.0114662083757234e-05, 'validation_fraction': 0.9013011255329684, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:32:46,281] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.5797745049666166, 'learning_rate': 0.0340824703981913, 'dropout_rate': 0.8789638175767511, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.6334696669297977, 'min_weight_fraction_leaf': 0.23189942173022937, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00011732864998245735, 'validation_fraction': 0.9231747707728767, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:33:07,225] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.4834541725153398, 'learning_rate': 0.023289638797856414, 'dropout_rate': 0.8328682293021811, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.26471956407136726, 'min_weight_fraction_leaf': 0.28189314017013245, 'max_features': 0.1, 'min_impurity_decrease': 5.731123744574336e-06, 'validation_fraction': 0.717424917124647, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 20:33:43,300] Trial 85 finished with value: 0.7029378184245214 and parameters: {'subsample': 0.46442416471302606, 'learning_rate': 0.03868120982137072, 'dropout_rate': 0.7555010939901714, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.21534553835140724, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002588366582089363, 'validation_fraction': 0.9754525788007801, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:34:00,936] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.4091031897854096, 'learning_rate': 0.03892699649828304, 'dropout_rate': 0.8966021251568653, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.4776199103579195, 'min_weight_fraction_leaf': 0.318990902266928, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002571816882616244, 'validation_fraction': 0.8611496501916631, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 20:34:51,074] Trial 87 finished with value: 0.700696106580423 and parameters: {'subsample': 0.46817200009967197, 'learning_rate': 0.04661767243536595, 'dropout_rate': 0.7376705742886068, 'n_estimators': 500, 'criterion': 'friedman_mse', 'ccp_alpha': 0.04557647433264077, 'min_weight_fraction_leaf': 0.21448093853857778, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002513028199602771, 'validation_fraction': 0.361331630037412, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:35:50,769] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.4734273359806112, 'learning_rate': 0.045317430108268164, 'dropout_rate': 0.6792015208901604, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.8373996404369569, 'min_weight_fraction_leaf': 0.2076554276967961, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00025922792722789, 'validation_fraction': 0.3782276435223031, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 9}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:36:21,260] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.5076059777658789, 'learning_rate': 0.05189362500314046, 'dropout_rate': 0.7514447580456498, 'n_estimators': 465, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5180606603106581, 'min_weight_fraction_leaf': 0.19106605392928014, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0007921505458300624, 'validation_fraction': 0.46777134963559586, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 8}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:36:56,349] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.5480227718329489, 'learning_rate': 0.04805596762658106, 'dropout_rate': 0.7066716225655056, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 1.2032615919351914, 'min_weight_fraction_leaf': 0.13639914209671022, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005203217678609466, 'validation_fraction': 0.34750901152193453, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 20:37:33,079] Trial 91 finished with value: 0.7042923968057858 and parameters: {'subsample': 0.4534948921776258, 'learning_rate': 0.03502795963916463, 'dropout_rate': 0.755627753350719, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.038324466824448115, 'min_weight_fraction_leaf': 0.25345276007887213, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00014354070633778947, 'validation_fraction': 0.2513534386677809, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-14 20:38:07,481] Trial 92 finished with value: 0.6654869537195273 and parameters: {'subsample': 0.45901870291397145, 'learning_rate': 0.04220683468610277, 'dropout_rate': 0.7610995478393064, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20198938667373578, 'min_weight_fraction_leaf': 0.22974950694765456, 'max_features': 'sqrt', 'min_impurity_decrease': 8.610273210310798e-05, 'validation_fraction': 0.21295376016707165, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.6266094420600858
[I 2024-04-14 20:38:37,721] Trial 93 finished with value: 0.6632943660515618 and parameters: {'subsample': 0.37244305499635777, 'learning_rate': 0.03895285718662616, 'dropout_rate': 0.7875609691891403, 'n_estimators': 474, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20205334259952537, 'min_weight_fraction_leaf': 0.24888065753134778, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000148363188299076, 'validation_fraction': 0.1299685001128385, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:39:03,563] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.43627908901840756, 'learning_rate': 0.04630380294028844, 'dropout_rate': 0.7208290031417008, 'n_estimators': 414, 'criterion': 'friedman_mse', 'ccp_alpha': 0.686936086932398, 'min_weight_fraction_leaf': 0.2141369130694551, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012504880596450284, 'validation_fraction': 0.2791478692094214, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 10}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:39:40,247] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.6285859050928441, 'learning_rate': 0.029038357232304236, 'dropout_rate': 0.6568164122517353, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 0.48602027021543714, 'min_weight_fraction_leaf': 0.16911337556412148, 'max_features': 'log2', 'min_impurity_decrease': 0.0002586731710309203, 'validation_fraction': 0.17068432884242818, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:40:16,045] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.11163353775210327, 'learning_rate': 0.03624893859534497, 'dropout_rate': 0.7401851281056467, 'n_estimators': 461, 'criterion': 'friedman_mse', 'ccp_alpha': 0.031023726124332976, 'min_weight_fraction_leaf': 0.24106600300562744, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010175709743728148, 'validation_fraction': 0.4508353689784418, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 78 with value: 0.7114957764128979.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:40:45,978] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.5066101762585695, 'learning_rate': 0.05098430577340745, 'dropout_rate': 0.8032993914079254, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 1.5924588674838394, 'min_weight_fraction_leaf': 0.2916743459566873, 'max_features': 'sqrt', 'min_impurity_decrease': 1.869990366510041e-05, 'validation_fraction': 0.24332889241821454, 'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:41:29,453] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.5419886775293563, 'learning_rate': 0.032225735364336795, 'dropout_rate': 0.6104661709305399, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.26209852400972233, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006021755492414387, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 78 with value: 0.7114957764128979.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-14 20:41:55,893] A new study created in memory with name: no-name-f8c9c603-4968-4265-ab6b-4b7909d41a22

Fold 5 C-index: 0.5
[I 2024-04-14 20:41:55,855] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.39063437722207883, 'learning_rate': 0.025815091055183734, 'dropout_rate': 0.8234328591249713, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.9385820631937101, 'min_weight_fraction_leaf': 0.22455882002189229, 'max_features': 'sqrt', 'min_impurity_decrease': 4.968275718083171e-05, 'validation_fraction': 0.35073001527955794, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 78 with value: 0.7114957764128979.


* Best trial for C-index:
 FrozenTrial(number=78, state=TrialState.COMPLETE, values=[0.7114957764128979], datetime_start=datetime.datetime(2024, 4, 14, 20, 30, 19, 845182), datetime_complete=datetime.datetime(2024, 4, 14, 20, 30, 49, 155106), params={'subsample': 0.5109023203910539, 'learning_rate': 0.03158550801216725, 'dropout_rate': 0.7413014948736192, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.25025224628887144, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.8776959526028103, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=78, value=None)


* Best Score for C-index:
 0.7114957764128979

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:42:22,426] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:42:39,172] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:42:55,105] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:43:17,762] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:43:29,662] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:43:31,884] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:43:51,966] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:43:57,947] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:43:58,928] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24601188999971108
Fold 2 IBS: 0.23037210839917271
Fold 3 IBS: 0.22866399971848883
Fold 4 IBS: 0.24084688533435283
Fold 5 IBS: 0.22855937522449543
[I 2024-04-14 20:44:59,206] Trial 9 finished with value: 0.23489085173524415 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316615258034594
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-14 20:46:28,490] Trial 10 finished with value: 0.2356345447701623 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 20:48:06,707] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24715496002116139
Fold 2 IBS: 0.23184677797440564
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-14 20:49:35,424] Trial 12 finished with value: 0.23582736637047277 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:50:19,012] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:51:36,644] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:52:40,499] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:53:18,645] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:54:41,670] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:55:23,447] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:55:30,046] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 20:56:44,336] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24711009086064675
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-14 20:58:09,149] Trial 21 finished with value: 0.2358286550709061 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23489085173524415.
Fold 1 IBS: 0.24631246902459264
Fold 2 IBS: 0.2301553946746369

Fold 3 IBS: 0.22860967046558744
Fold 4 IBS: 0.24066583979891498
Fold 5 IBS: 0.22847752254891643
[I 2024-04-14 20:59:46,810] Trial 22 finished with value: 0.23484417930252968 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:01:28,459] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:02:16,392] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:03:01,466] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:04:14,934] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:04:22,238] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:04:46,191] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:05:51,324] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:06:19,582] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.2469488707078328
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-14 21:07:35,088] Trial 31 finished with value: 0.23566408867478444 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.246666566986516
Fold 2 IBS: 0.23029138500538826
Fold 3 IBS: 0.2286104923116217
Fold 4 IBS: 0.2410306602915697
Fold 5 IBS: 0.22850948233448493
[I 2024-04-14 21:08:49,411] Trial 32 finished with value: 0.2350217173859161 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:09:48,271] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:10:48,211] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:11:01,566] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:12:19,191] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:12:21,694] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:13:03,283] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:13:55,764] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:14:46,570] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24691393295703395
Fold 2 IBS: 0.2308768926750243
Fold 3 IBS: 0.228693200751399
Fold 4 IBS: 0.24135578760651089
Fold 5 IBS: 0.2287912990304231
[I 2024-04-14 21:15:53,405] Trial 41 finished with value: 0.23532622260407826 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24669917045535314
Fold 2 IBS: 0.23039435703397623
Fold 3 IBS: 0.2286021142717964
Fold 4 IBS: 0.24108271788424998
Fold 5 IBS: 0.22850441164399574
[I 2024-04-14 21:17:16,103] Trial 42 finished with value: 0.23505655425787428 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:18:45,510] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:19:48,110] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24703887799052987
Fold 2 IBS: 0.23168875432685665
Fold 3 IBS: 0.22882805766925127
Fold 4 IBS: 0.241715763548256
Fold 5 IBS: 0.22920687339343254
[I 2024-04-14 21:20:43,510] Trial 45 finished with value: 0.23569566538566528 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:21:39,834] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:22:06,035] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:22:06,412] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:22:21,820] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:23:34,170] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.2462241972912113
Fold 2 IBS: 0.23077640891357248
Fold 3 IBS: 0.22882696907450273
Fold 4 IBS: 0.24135463401709267
Fold 5 IBS: 0.22888526357862624
[I 2024-04-14 21:24:53,089] Trial 51 finished with value: 0.23521349457500107 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:26:03,289] Trial 52 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.23484417930252968.
Fold 1 IBS: 0.24480295453274456
Fold 2 IBS: 0.22862007958956948
Fold 3 IBS: 0.22846906978601278
Fold 4 IBS: 0.23968740831242308
Fold 5 IBS: 0.22752375735775052
[I 2024-04-14 21:27:06,097] Trial 53 finished with value: 0.2338206539157001 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:28:05,031] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658996

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:28:58,968] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:29:49,957] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:30:54,606] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:32:34,859] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:33:23,003] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:34:04,175] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:35:05,913] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24574433264597934
Fold 2 IBS: 0.22927538950456844
Fold 3 IBS: 0.22873745223732048
Fold 4 IBS: 0.24073941337728164
Fold 5 IBS: 0.22810179683765522
[I 2024-04-14 21:36:22,738] Trial 62 finished with value: 0.23451967692056103 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:37:45,719] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.2466083692887466
Fold 2 IBS: 0.2306207063514776
Fold 3 IBS: 0.22847735216630757
Fold 4 IBS: 0.24115036494545394
Fold 5 IBS: 0.22887214566068675
[I 2024-04-14 21:39:06,626] Trial 64 finished with value: 0.23514578768253452 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:40:19,622] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8687566763675275, 'learning_rate': 0.009621975442769493, 'dropout_rate': 0.20090531278751475, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.21730511044745757, 'max_features': 'log2', 'min_impurity_decrease': 4.00127934674698e-06, 'validation_fraction': 0.998233299727277, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:41:29,068] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9998769156045215, 'learning_rate': 0.010488456761899951, 'dropout_rate': 0.32975112844548055, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.7134499429690735, 'min_weight_fraction_leaf': 0.19311178079767077, 'max_features': 'log2', 'min_impurity_decrease': 1.142816958470248e-06, 'validation_fraction': 0.916501041728546, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:42:34,055] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9237031040797604, 'learning_rate': 0.015997347081349804, 'dropout_rate': 0.1311947431151216, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.17471126075382626, 'max_features': 'log2', 'min_impurity_decrease': 2.9677822215329938e-06, 'validation_fraction': 0.8373361504171383, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:43:52,472] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8052124560044422, 'learning_rate': 0.027698938792055094, 'dropout_rate': 0.17163882429043748, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2902860030111922, 'min_weight_fraction_leaf': 0.2065206798225065, 'max_features': 'log2', 'min_impurity_decrease': 7.18785237781598e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 21:44:42,597] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.022661198063658503, 'dropout_rate': 0.29902706401252577, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 5.781491720141274, 'min_weight_fraction_leaf': 0.15344398719269492, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3987639087801584e-06, 'validation_fraction': 0.9734079114890423, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 20}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:45:23,918] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.008582797188938113, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.13005036354311128, 'max_features': 'log2', 'min_impurity_decrease': 7.713426989240967e-06, 'validation_fraction': 0.8771634368243094, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24660813053143274
Fold 2 IBS: 0.2313740896010414
Fold 3 IBS: 0.22888346736781262
Fold 4 IBS: 0.24154385958499447
Fold 5 IBS: 0.22907992714862077
[I 2024-04-14 21:46:30,921] Trial 71 finished with value: 0.23549789484678038 and parameters: {'subsample': 0.929404609689833, 'learning_rate': 0.004424988061063654, 'dropout_rate': 0.23482693737269283, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.35066087197674667, 'max_features': 'auto', 'min_impurity_decrease': 2.8309589446706505e-07, 'validation_fraction': 0.9695063743987746, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24443957359768934
Fold 2 IBS: 0.22898066177897697
Fold 3 IBS: 0.2286359719656182
Fold 4 IBS: 0.24035046542118138
Fold 5 IBS: 0.2281079279567809
[I 2024-04-14 21:47:43,597] Trial 72 finished with value: 0.23410292014404935 and parameters: {'subsample': 0.9711381132608441, 'learning_rate': 0.01307164167481496, 'dropout_rate': 0.16033065274696134, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.28323130225405224, 'max_features': 'auto', 'min_impurity_decrease': 4.6121007580567444e-07, 'validation_fraction': 0.9257122264827732, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:47:51,681] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9610645917359522, 'learning_rate': 0.014025237603958317, 'dropout_rate': 0.16734553890018478, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.2729437922989923, 'max_features': 'auto', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9151475421106045, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:49:03,400] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8982215127429586, 'learning_rate': 0.011469834124160947, 'dropout_rate': 0.1993916634953806, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.25576647956503945, 'max_features': 'auto', 'min_impurity_decrease': 7.393622885050152e-07, 'validation_fraction': 0.8125896097974837, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:50:03,236] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8548930681972974, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.25603892151293595, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 1.194698393798027, 'min_weight_fraction_leaf': 0.227857291707919, 'max_features': 'auto', 'min_impurity_decrease': 5.9734079360074814e-05, 'validation_fraction': 0.9391263043864969, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:50:56,716] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9721277657554889, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.12783725032075846, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.8995225231338432, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:51:50,386] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9372636724132823, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.2214138929394412, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.5872217111247551, 'min_weight_fraction_leaf': 0.2869095730072229, 'max_features': 1, 'min_impurity_decrease': 1.637559261311236e-05, 'validation_fraction': 0.8634632458479912, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:53:15,391] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.1032133459374581, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.3013998603131079, 'min_weight_fraction_leaf': 0.32139197698764493, 'max_features': 'auto', 'min_impurity_decrease': 5.258405165208321e-06, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 6}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:54:08,324] Trial 79 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9734119542324268, 'learning_rate': 0.00746613709211405, 'dropout_rate': 0.4920375503223646, 'n_estimators': 460, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8367973848765441, 'min_weight_fraction_leaf': 0.2996410468063834, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.93241471973226, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 10}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-14 21:54:52,861] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.880944209495621, 'learning_rate': 0.01757839546882116, 'dropout_rate': 0.1506586822025462, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.2351229170019059, 'max_features': 'auto', 'min_impurity_decrease': 2.0904779043950468e-07, 'validation_fraction': 0.985038184908284, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24676102336178163
Fold 2 IBS: 0.23092626118770207
Fold 3 IBS: 0.22884445831372108
Fold 4 IBS: 0.24139059004884203
Fold 5 IBS: 0.22894502692454705
[I 2024-04-14 21:56:20,717] Trial 81 finished with value: 0.23537347196731875 and parameters: {'subsample': 0.9953153224638304, 'learning_rate': 0.00415560855116564, 'dropout_rate': 0.1483184577320775, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.02521700237735763, 'min_weight_fraction_leaf': 0.25226618405818907, 'max_features': 'auto', 'min_impurity_decrease': 4.4684913792581215e-07, 'validation_fraction': 0.9678293267367657, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24673460160879498
Fold 2 IBS: 0.2312605158627123
Fold 3 IBS: 0.22877711474094156
Fold 4 IBS: 0.24147939872518737
Fold 5 IBS: 0.2289894752898651
[I 2024-04-14 21:57:48,738] Trial 82 finished with value: 0.23544822124550024 and parameters: {'subsample': 0.9139425050983833, 'learning_rate': 0.003095076319203989, 'dropout_rate': 0.18592812333507946, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.01766512408236868, 'min_weight_fraction_leaf': 0.27798560564966124, 'max_features': 'auto', 'min_impurity_decrease': 2.5718979151862506e-07, 'validation_fraction': 0.9466831295624905, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 21:59:07,166] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.008698584299413689, 'dropout_rate': 0.2159451606802952, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.43227235536812275, 'min_weight_fraction_leaf': 0.30582130984370137, 'max_features': 'auto', 'min_impurity_decrease': 1.4239613599957663e-07, 'validation_fraction': 0.8917283975361172, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:00:22,205] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9427477095506464, 'learning_rate': 0.013253369992371197, 'dropout_rate': 0.28698354158028666, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.2626782112744739, 'min_weight_fraction_leaf': 0.37366502204692825, 'max_features': 'auto', 'min_impurity_decrease': 9.351118010000074e-07, 'validation_fraction': 0.9794585372583974, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:01:21,278] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.975912726079302, 'learning_rate': 0.007475044296417039, 'dropout_rate': 0.15830961459250859, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.9666121832540018, 'min_weight_fraction_leaf': 0.21662805225917264, 'max_features': 'auto', 'min_impurity_decrease': 1.605110937110208e-07, 'validation_fraction': 0.9998997107949049, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:02:23,262] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.998032487033103, 'learning_rate': 0.01532810679048379, 'dropout_rate': 0.23799870869674608, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 1.4471152192323817, 'min_weight_fraction_leaf': 0.34273533762708086, 'max_features': 'sqrt', 'min_impurity_decrease': 2.348014993384585e-06, 'validation_fraction': 0.9194096150774934, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:03:06,950] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9164505822984168, 'learning_rate': 0.010518689458761585, 'dropout_rate': 0.18127430624736812, 'n_estimators': 386, 'criterion': 'squared_error', 'ccp_alpha': 0.6191599526075152, 'min_weight_fraction_leaf': 0.19734229255387364, 'max_features': 'auto', 'min_impurity_decrease': 5.635415445839132e-07, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:03:54,540] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5839343488674055, 'learning_rate': 0.005616464421601462, 'dropout_rate': 0.35953503133089737, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.3179664432907911, 'min_weight_fraction_leaf': 0.28749157637391265, 'max_features': 'auto', 'min_impurity_decrease': 3.335913971167387e-07, 'validation_fraction': 0.9542099213957375, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24665149166978298
Fold 2 IBS: 0.23100341911248753
Fold 3 IBS: 0.22874931175992053
Fold 4 IBS: 0.241449076384833
Fold 5 IBS: 0.22889139804833578
[I 2024-04-14 22:05:26,646] Trial 89 finished with value: 0.23534893939507198 and parameters: {'subsample': 0.9747597567605316, 'learning_rate': 0.0023221821235695954, 'dropout_rate': 0.12129931807719876, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.0187843407424986, 'min_weight_fraction_leaf': 0.27088299579805813, 'max_features': None, 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.8471649366493529, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:05:48,920] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8177896619586076, 'learning_rate': 0.025220139306170144, 'dropout_rate': 0.8458602043820649, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.5942787933242142, 'min_weight_fraction_leaf': 0.2526148431947255, 'max_features': 'auto', 'min_impurity_decrease': 0.00038999127447584, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898151309365794
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:06:57,695] Trial 91 finished with value: 0.2359277725171069 and parameters: {'subsample': 0.9509971840289189, 'learning_rate': 0.006250411110020785, 'dropout_rate': 0.2673714840258141, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.15431692617854653, 'min_weight_fraction_leaf': 0.24422274988904982, 'max_features': 'auto', 'min_impurity_decrease': 1.9176785824147386e-06, 'validation_fraction': 0.9656926905530724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:07:15,341] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.010420830230366905, 'dropout_rate': 0.2515504536642298, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.9241378948044482, 'min_weight_fraction_leaf': 0.23688053465240513, 'max_features': 'auto', 'min_impurity_decrease': 1.29569417753367e-06, 'validation_fraction': 0.9347724982483091, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:08:10,390] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9579265056005781, 'learning_rate': 0.005644515103436926, 'dropout_rate': 0.20759879422315985, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.21922288268105994, 'max_features': 'auto', 'min_impurity_decrease': 2.659018541949647e-06, 'validation_fraction': 0.9030263302405803, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:09:59,269] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8907857729292054, 'learning_rate': 0.01175213801479497, 'dropout_rate': 0.16486788507480765, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.2574700533601738, 'min_weight_fraction_leaf': 0.18108974600339167, 'max_features': 'auto', 'min_impurity_decrease': 2.379032042731447e-07, 'validation_fraction': 0.8736447132173984, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:10:49,671] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9455952167309377, 'learning_rate': 0.0011500826880246348, 'dropout_rate': 0.3201948574529592, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 1.2548600964987282, 'min_weight_fraction_leaf': 0.26353524052393096, 'max_features': 'log2', 'min_impurity_decrease': 8.22276697752205e-07, 'validation_fraction': 0.5342538893491903, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:11:43,682] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9798648277744092, 'learning_rate': 0.020033817173644677, 'dropout_rate': 0.27495368719691143, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7011862464885574, 'min_weight_fraction_leaf': 0.3195542671542451, 'max_features': 'auto', 'min_impurity_decrease': 5.186503543953528e-06, 'validation_fraction': 0.6783354896202222, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:12:47,183] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9344119758186928, 'learning_rate': 0.01702180833811468, 'dropout_rate': 0.22429524454783162, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.16853016350793706, 'min_weight_fraction_leaf': 0.22792544673999854, 'max_features': 1, 'min_impurity_decrease': 5.480220886635845e-07, 'validation_fraction': 0.9725840318690578, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:13:36,333] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9075182186822651, 'learning_rate': 0.013589188110358917, 'dropout_rate': 0.1959593061485241, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 0.987310061750523, 'min_weight_fraction_leaf': 0.20559490580314585, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.2951928169891771, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.2338206539157001.
Fold 1 IBS: 0.24701754842447565

Fold 2 IBS: 0.23172776185253358
Fold 3 IBS: 0.22878554072857857
Fold 4 IBS: 0.2416676429021851
Fold 5 IBS: 0.2290838777915168
[I 2024-04-14 22:14:54,526] Trial 99 finished with value: 0.23565647433985792 and parameters: {'subsample': 0.24286963781937687, 'learning_rate': 0.008804936390818944, 'dropout_rate': 0.14353784252843382, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.004530258324353442, 'min_weight_fraction_leaf': 0.29607175965989646, 'max_features': 0.1, 'min_impurity_decrease': 1.9888370412270107e-06, 'validation_fraction': 0.9539243209909428, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 53 with value: 0.2338206539157001.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.2338206539157001], datetime_start=datetime.datetime(2024, 4, 14, 21, 26, 3, 299914), datetime_complete=datetime.datetime(2024, 4, 14, 21, 27, 6, 96288), params={'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=53, value=None)


* Best Score for IBS:
 0.2338206539157001

In [67]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [68]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.711
train_ibs:  0.234

#### Test

In [69]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [70]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.02313127962403605,
                                 criterion='squared_error',
                                 dropout_rate=0.7413014948736192,
                                 learning_rate=0.03158550801216725,
                                 max_features='sqrt', max_leaf_nodes=20,
                                 min_impurity_decrease=1.9076132907505136e-05,
                                 min_samples_leaf=11, min_samples_split=18,
                                 min_weight_fraction_leaf=0.25025224628887144,
                                 n_estimators=449, random_state=123,
                                 subsample=0.5109023203910539,
                                 validation_fraction=0.8776959526028103)

C-index score: 0.517

GradientBoostingSurvivalAnalysis(ccp_alpha=0.009625013743012712,
                                 criterion='squared_error',
                                 dropout_rate=0.1897783294507234,
                                 learning_rate=0.015420772490455037,
                                 max_features='auto', max_leaf_nodes=14,
                                 min_impurity_decrease=5.869825897765074e-07,
                                 min_samples_leaf=13, min_samples_split=20,
                                 min_weight_fraction_leaf=0.29880213170319914,
                                 n_estimators=430, random_state=123,
                                 subsample=0.9101431135071837,
                                 validation_fraction=0.9964423942006735)

IBS: 0.229

In [71]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [72]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [73]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:15:10,945] A new study created in memory with name: no-name-1181e616-5fb6-48c6-b17a-30d116f64d61

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:15:12,355] Trial 0 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 22:15:19,669] Trial 1 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:15:20,920] Trial 2 finished with value: 0.6290789721738743 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6290789721738743.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:15:22,814] Trial 3 finished with value: 0.6321935102194108 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6321935102194108.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:15:25,763] Trial 4 finished with value: 0.63299762823734 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.63299762823734.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 22:15:29,604] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.63299762823734.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 22:15:31,435] Trial 6 finished with value: 0.6223931075093858 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.63299762823734.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:15:31,818] Trial 7 finished with value: 0.6289447028736863 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.63299762823734.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:15:33,929] Trial 8 finished with value: 0.6265038648777369 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.63299762823734.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 22:15:40,727] Trial 9 finished with value: 0.6256454957790245 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.63299762823734.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:15:45,811] Trial 10 finished with value: 0.6391687289026188 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6391687289026188.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:15:51,988] Trial 11 finished with value: 0.6491468763533488 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:15:56,909] Trial 12 finished with value: 0.6482199424922239 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:16:02,205] Trial 13 finished with value: 0.6284016912003729 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:16:05,886] Trial 14 finished with value: 0.6444820112990763 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:16:09,815] Trial 15 finished with value: 0.6391614236336937 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:16:16,811] Trial 16 finished with value: 0.6445292539671557 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:16:23,751] Trial 17 finished with value: 0.6346022669150224 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:16:26,766] Trial 18 finished with value: 0.6306830600216656 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 11 with value: 0.6491468763533488.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:16:27,927] Trial 19 finished with value: 0.6415416799528819 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:16:36,107] Trial 20 finished with value: 0.6383398348532772 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:16:43,887] Trial 21 finished with value: 0.6423237551772004 and parameters: {'subsample': 0.19686631492543752, 'dropout_rate': 0.12395834975058428, 'n_estimators': 431, 'learning_rate': 0.09000255639604265}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:16:47,773] Trial 22 finished with value: 0.6468148979633505 and parameters: {'subsample': 0.19525739351764543, 'dropout_rate': 0.10643415732680922, 'n_estimators': 323, 'learning_rate': 0.06478804138779268}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:16:51,389] Trial 23 finished with value: 0.6437613654376312 and parameters: {'subsample': 0.1529963084044875, 'dropout_rate': 0.3450678380411328, 'n_estimators': 311, 'learning_rate': 0.06498100052925637}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:16:55,526] Trial 24 finished with value: 0.6377388477541694 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.19210379926904825, 'n_estimators': 341, 'learning_rate': 0.08005361186179301}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:16:57,798] Trial 25 finished with value: 0.6383650347277458 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.284333596994065, 'n_estimators': 239, 'learning_rate': 0.03653717280890995}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:17:01,133] Trial 26 finished with value: 0.6362175113635848 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.18335657306839728, 'n_estimators': 287, 'learning_rate': 0.09310072935887158}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:17:04,977] Trial 27 finished with value: 0.6478865634744466 and parameters: {'subsample': 0.10030502914954577, 'dropout_rate': 0.9861686560685959, 'n_estimators': 387, 'learning_rate': 0.06071884280131438}. Best is trial 11 with value: 0.6491468763533488.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:17:08,868] Trial 28 finished with value: 0.6503096338516874 and parameters: {'subsample': 0.10146809971965022, 'dropout_rate': 0.8178252892822001, 'n_estimators': 383, 'learning_rate': 0.014116661098438898}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:17:17,825] Trial 29 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.6254835199581565, 'n_estimators': 458, 'learning_rate': 0.019348716454436136}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 22:17:26,309] Trial 30 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6496340242271839, 'dropout_rate': 0.8571729606353702, 'n_estimators': 390, 'learning_rate': 0.005177270413200799}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:17:34,253] Trial 31 finished with value: 0.6461698252770216 and parameters: {'subsample': 0.10793925840929003, 'dropout_rate': 0.9925382852879747, 'n_estimators': 381, 'learning_rate': 0.012440672458725079}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:17:39,137] Trial 32 finished with value: 0.6407407354500724 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.9635889254026732, 'n_estimators': 343, 'learning_rate': 0.04584704484322187}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:17:44,724] Trial 33 finished with value: 0.649498083577998 and parameters: {'subsample': 0.10119572499894987, 'dropout_rate': 0.9244327588135324, 'n_estimators': 404, 'learning_rate': 0.05879386689092163}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:17:50,983] Trial 34 finished with value: 0.6344748790407035 and parameters: {'subsample': 0.2373920056434941, 'dropout_rate': 0.8233032587634277, 'n_estimators': 462, 'learning_rate': 0.039452101341805365}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:17:53,840] Trial 35 finished with value: 0.6407407354500724 and parameters: {'subsample': 0.16710472630778297, 'dropout_rate': 0.7859308181520335, 'n_estimators': 275, 'learning_rate': 0.07191442813299788}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:18:08,213] Trial 36 finished with value: 0.6289447028736863 and parameters: {'subsample': 0.3088608819900312, 'dropout_rate': 0.45922216511134195, 'n_estimators': 490, 'learning_rate': 0.025279851317820894}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263

Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:18:11,639] Trial 37 finished with value: 0.6399802791763081 and parameters: {'subsample': 0.15245954770280346, 'dropout_rate': 0.9117253364549719, 'n_estimators': 230, 'learning_rate': 0.05621431261796065}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:18:19,932] Trial 38 finished with value: 0.6267465093526564 and parameters: {'subsample': 0.5602770145716328, 'dropout_rate': 0.5364701773999812, 'n_estimators': 404, 'learning_rate': 0.07843779087354608}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:18:21,465] Trial 39 finished with value: 0.6305782657708484 and parameters: {'subsample': 0.3116572492222035, 'dropout_rate': 0.6101586696414693, 'n_estimators': 145, 'learning_rate': 0.06892741183938003}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:18:21,846] Trial 40 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.7825497504780614, 'n_estimators': 44, 'learning_rate': 0.031056380853064336}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:18:25,711] Trial 41 finished with value: 0.6478792582055213 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.9378678421534942, 'n_estimators': 329, 'learning_rate': 0.06047386071641027}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:18:30,016] Trial 42 finished with value: 0.6375967223551652 and parameters: {'subsample': 0.15805964805992748, 'dropout_rate': 0.8782563183029866, 'n_estimators': 366, 'learning_rate': 0.0573047863536483}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:18:36,996] Trial 43 finished with value: 0.6304009019906482 and parameters: {'subsample': 0.23857367855652362, 'dropout_rate': 0.9989900493719511, 'n_estimators': 443, 'learning_rate': 0.050544109580621416}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 22:18:37,252] Trial 44 finished with value: 0.6434798852233399 and parameters: {'subsample': 0.1255006401851519, 'dropout_rate': 0.9375968312227013, 'n_estimators': 3, 'learning_rate': 0.04450424844427492}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:18:43,985] Trial 45 finished with value: 0.6359562780321342 and parameters: {'subsample': 0.19800610648800795, 'dropout_rate': 0.7991522227764232, 'n_estimators': 392, 'learning_rate': 0.0929402554336651}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:18:51,188] Trial 46 finished with value: 0.64225792365259 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.7209797512918751, 'n_estimators': 357, 'learning_rate': 0.0741420848055865}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:18:57,071] Trial 47 finished with value: 0.6321392591386276 and parameters: {'subsample': 0.26524540968090016, 'dropout_rate': 0.39192041571759667, 'n_estimators': 297, 'learning_rate': 0.06254077425956685}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:19:07,582] Trial 48 finished with value: 0.6495128211026835 and parameters: {'subsample': 0.10044152911408698, 'dropout_rate': 0.8394658701129177, 'n_estimators': 402, 'learning_rate': 0.05425668242496677}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:19:17,451] Trial 49 finished with value: 0.6351195278839761 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.8480935187842629, 'n_estimators': 495, 'learning_rate': 0.0523465983547244}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:19:23,203] Trial 50 finished with value: 0.6328486214124667 and parameters: {'subsample': 0.23434492792342293, 'dropout_rate': 0.7508012264442566, 'n_estimators': 406, 'learning_rate': 0.04670953562577961}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:19:32,566] Trial 51 finished with value: 0.6462240763578049 and parameters: {'subsample': 0.10358966238296467, 'dropout_rate': 0.9200607826207204, 'n_estimators': 374, 'learning_rate': 0.05925774791634502}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:19:40,796] Trial 52 finished with value: 0.6439637756571754 and parameters: {'subsample': 0.13637380813559394, 'dropout_rate': 0.8859130671281824, 'n_estimators': 439, 'learning_rate': 0.03976845502558922}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:19:47,070] Trial 53 finished with value: 0.6461086927703694 and parameters: {'subsample': 0.1785947760630057, 'dropout_rate': 0.1488587318045569, 'n_estimators': 329, 'learning_rate': 0.06851593399738345}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:19:54,874] Trial 54 finished with value: 0.6438515491505981 and parameters: {'subsample': 0.12802821219067972, 'dropout_rate': 0.8347625407198032, 'n_estimators': 399, 'learning_rate': 0.05437259183470327}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:19:59,454] Trial 55 finished with value: 0.6351810842336845 and parameters: {'subsample': 0.220193744880123, 'dropout_rate': 0.9635452032497741, 'n_estimators': 358, 'learning_rate': 0.08267620572048905}. Best is trial 28 with value: 0.6503096338516874.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:20:02,921] Trial 56 finished with value: 0.626684953002948 and parameters: {'subsample': 0.8325335055364452, 'dropout_rate': 0.296922267125389, 'n_estimators': 262, 'learning_rate': 0.04838203204104383}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:20:06,377] Trial 57 finished with value: 0.6477418318244752 and parameters: {'subsample': 0.10148816505974656, 'dropout_rate': 0.6739195794671835, 'n_estimators': 316, 'learning_rate': 0.09535622347024937}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:20:13,320] Trial 58 finished with value: 0.641515929248522 and parameters: {'subsample': 0.17872819351209274, 'dropout_rate': 0.4090143050433944, 'n_estimators': 414, 'learning_rate': 0.0980655118544413}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:20:19,354] Trial 59 finished with value: 0.6424649059032574 and parameters: {'subsample': 0.14522006252948272, 'dropout_rate': 0.5065802886056728, 'n_estimators': 348, 'learning_rate': 0.09027241834690336}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:20:22,212] Trial 60 finished with value: 0.6297272019410611 and parameters: {'subsample': 0.2552130359082268, 'dropout_rate': 0.9599021187081268, 'n_estimators': 287, 'learning_rate': 0.03136696153263342}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:20:26,431] Trial 61 finished with value: 0.6487376273042338 and parameters: {'subsample': 0.10680929775336306, 'dropout_rate': 0.936151712860273, 'n_estimators': 381, 'learning_rate': 0.05966603635110074}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:20:30,461] Trial 62 finished with value: 0.6439785131818607 and parameters: {'subsample': 0.13680120501115423, 'dropout_rate': 0.8891092031305728, 'n_estimators': 387, 'learning_rate': 0.06747867457625864}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:20:35,420] Trial 63 finished with value: 0.639085553602356 and parameters: {'subsample': 0.20245185034045857, 'dropout_rate': 0.2205178594196074, 'n_estimators': 371, 'learning_rate': 0.06485811083754686}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:20:44,197] Trial 64 finished with value: 0.6454493064024115 and parameters: {'subsample': 0.10197413109462203, 'dropout_rate': 0.14814178386748486, 'n_estimators': 425, 'learning_rate': 0.07514495786449392}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:20:51,726] Trial 65 finished with value: 0.6280863337749738 and parameters: {'subsample': 0.28853901115699654, 'dropout_rate': 0.8234954092671971, 'n_estimators': 444, 'learning_rate': 0.05708774911498015}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:20:56,126] Trial 66 finished with value: 0.6407407354500724 and parameters: {'subsample': 0.16945268953354836, 'dropout_rate': 0.9833029954247124, 'n_estimators': 329, 'learning_rate': 0.04096312807075328}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 22:21:00,120] Trial 67 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.5594113631201594, 'dropout_rate': 0.9335148889243268, 'n_estimators': 382, 'learning_rate': 0.052434820608049916}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 22:21:05,853] Trial 68 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6099875522212969, 'dropout_rate': 0.8646861201169278, 'n_estimators': 472, 'learning_rate': 0.010822396813495035}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:21:09,258] Trial 69 finished with value: 0.6399044091449705 and parameters: {'subsample': 0.14550059497413936, 'dropout_rate': 0.6013784858315676, 'n_estimators': 305, 'learning_rate': 0.08403050744828938}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:21:12,805] Trial 70 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.9036160911500482, 'n_estimators': 344, 'learning_rate': 0.025229270774777032}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:21:15,935] Trial 71 finished with value: 0.6436093285187348 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.9539171051587573, 'n_estimators': 335, 'learning_rate': 0.0600893395919644}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:21:18,515] Trial 72 finished with value: 0.6470208891068089 and parameters: {'subsample': 0.10272578654307185, 'dropout_rate': 0.9334392115432031, 'n_estimators': 274, 'learning_rate': 0.0626031078003601}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:21:23,138] Trial 73 finished with value: 0.6383319787544608 and parameters: {'subsample': 0.18174562511340475, 'dropout_rate': 0.9760688499996194, 'n_estimators': 409, 'learning_rate': 0.05428031689560182}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6653992395437263

Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:21:24,817] Trial 74 finished with value: 0.6408240377371702 and parameters: {'subsample': 0.12933565458879856, 'dropout_rate': 0.9055797005260723, 'n_estimators': 199, 'learning_rate': 0.0711612518017945}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:21:29,309] Trial 75 finished with value: 0.6375135470549024 and parameters: {'subsample': 0.21617702827555724, 'dropout_rate': 0.9422617503964087, 'n_estimators': 371, 'learning_rate': 0.060997075472904866}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:21:34,506] Trial 76 finished with value: 0.6392519042028816 and parameters: {'subsample': 0.15764335494086937, 'dropout_rate': 0.8071645276902537, 'n_estimators': 320, 'learning_rate': 0.04839368051126757}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:21:37,055] Trial 77 finished with value: 0.6438515491505981 and parameters: {'subsample': 0.12192854237394467, 'dropout_rate': 0.8864839155645223, 'n_estimators': 244, 'learning_rate': 0.06631560031679899}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:21:41,183] Trial 78 finished with value: 0.640012360476646 and parameters: {'subsample': 0.15364095054160787, 'dropout_rate': 0.7448790427150778, 'n_estimators': 357, 'learning_rate': 0.05796641894457688}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:21:50,385] Trial 79 finished with value: 0.6322446042193358 and parameters: {'subsample': 0.7645423045417526, 'dropout_rate': 0.13093787634155657, 'n_estimators': 455, 'learning_rate': 0.08807662007364396}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:21:56,214] Trial 80 finished with value: 0.6350979089334217 and parameters: {'subsample': 0.19044272366468012, 'dropout_rate': 0.860017641931637, 'n_estimators': 399, 'learning_rate': 0.0425874972124494}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:22:00,840] Trial 81 finished with value: 0.6469523243443964 and parameters: {'subsample': 0.10977669040135793, 'dropout_rate': 0.6768000949869927, 'n_estimators': 318, 'learning_rate': 0.09256435350978962}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:22:04,639] Trial 82 finished with value: 0.6469450190754713 and parameters: {'subsample': 0.1024594674688819, 'dropout_rate': 0.6485554290326331, 'n_estimators': 293, 'learning_rate': 0.09394421064359643}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:22:08,643] Trial 83 finished with value: 0.6439058002313813 and parameters: {'subsample': 0.13120320573739924, 'dropout_rate': 0.7755473686123889, 'n_estimators': 305, 'learning_rate': 0.09676257087647866}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:22:14,802] Trial 84 finished with value: 0.6391687289026188 and parameters: {'subsample': 0.16939440655578866, 'dropout_rate': 0.5760030907609586, 'n_estimators': 429, 'learning_rate': 0.0345629083684143}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:22:20,475] Trial 85 finished with value: 0.646191444227576 and parameters: {'subsample': 0.14498634829302595, 'dropout_rate': 0.20529355154590012, 'n_estimators': 348, 'learning_rate': 0.06281539444037365}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:22:25,626] Trial 86 finished with value: 0.634399009009366 and parameters: {'subsample': 0.23262422969409208, 'dropout_rate': 0.7048081666698877, 'n_estimators': 386, 'learning_rate': 0.09444592750905254}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:22:29,324] Trial 87 finished with value: 0.6477960829052585 and parameters: {'subsample': 0.10085624717858545, 'dropout_rate': 0.9144810810115751, 'n_estimators': 363, 'learning_rate': 0.050343581991000114}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:22:32,766] Trial 88 finished with value: 0.6454019367474972 and parameters: {'subsample': 0.12530965923351173, 'dropout_rate': 0.99573041659334, 'n_estimators': 365, 'learning_rate': 0.0035288713532488584}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:22:37,118] Trial 89 finished with value: 0.624171402056519 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.8405088974518644, 'n_estimators': 336, 'learning_rate': 0.07702059003890507}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:22:43,042] Trial 90 finished with value: 0.6359562780321342 and parameters: {'subsample': 0.20192966123849537, 'dropout_rate': 0.9157361312886566, 'n_estimators': 414, 'learning_rate': 0.028548360631165136}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:22:45,889] Trial 91 finished with value: 0.6469523243443964 and parameters: {'subsample': 0.11800706029226726, 'dropout_rate': 0.9730942556677186, 'n_estimators': 280, 'learning_rate': 0.09981907983776818}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:22:51,420] Trial 92 finished with value: 0.6383935351041692 and parameters: {'subsample': 0.1587394905821596, 'dropout_rate': 0.8794170239809405, 'n_estimators': 377, 'learning_rate': 0.05018200558311861}. Best is trial 28 with value: 0.6503096338516874.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:22:56,733] Trial 93 finished with value: 0.6478865634744466 and parameters: {'subsample': 0.10116363390375814, 'dropout_rate': 0.929917393917347, 'n_estimators': 395, 'learning_rate': 0.019127674637257917}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:23:01,114] Trial 94 finished with value: 0.6399439227010684 and parameters: {'subsample': 0.16592358004991675, 'dropout_rate': 0.9479965690635933, 'n_estimators': 395, 'learning_rate': 0.018994793959623224}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:23:05,208] Trial 95 finished with value: 0.6423669930783092 and parameters: {'subsample': 0.14082682676812386, 'dropout_rate': 0.9142778644623681, 'n_estimators': 360, 'learning_rate': 0.015447696171729001}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:23:11,385] Trial 96 finished with value: 0.6462461191514155 and parameters: {'subsample': 0.10075766090002664, 'dropout_rate': 0.16338736125895506, 'n_estimators': 419, 'learning_rate': 0.05469304318424442}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:23:15,745] Trial 97 finished with value: 0.6297198966721359 and parameters: {'subsample': 0.33846670341980367, 'dropout_rate': 0.9284409192863806, 'n_estimators': 402, 'learning_rate': 0.007278706132156287}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:23:21,267] Trial 98 finished with value: 0.6351195278839761 and parameters: {'subsample': 0.18058676916191113, 'dropout_rate': 0.8722241484151896, 'n_estimators': 435, 'learning_rate': 0.02035647334223366}. Best is trial 28 with value: 0.6503096338516874.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115

[I 2024-04-14 22:23:25,289] A new study created in memory with name: no-name-ded9021d-0d7b-4fcc-bf09-5c6ae041f7d7

Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:23:25,264] Trial 99 finished with value: 0.6429931800518857 and parameters: {'subsample': 0.12342167146561073, 'dropout_rate': 0.9020186714006526, 'n_estimators': 381, 'learning_rate': 0.015206979571228955}. Best is trial 28 with value: 0.6503096338516874.


* Best trial for C-index:
 FrozenTrial(number=28, state=TrialState.COMPLETE, values=[0.6503096338516874], datetime_start=datetime.datetime(2024, 4, 14, 22, 17, 4, 984164), datetime_complete=datetime.datetime(2024, 4, 14, 22, 17, 8, 867646), params={'subsample': 0.10146809971965022, 'dropout_rate': 0.8178252892822001, 'n_estimators': 383, 'learning_rate': 0.014116661098438898}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=28, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10146809971965022, 'dropout_rate': 0.8178252892822001, 'n_estimators': 383, 'learning_rate': 0.014116661098438898}


* Best Score for C-index:
 0.6503096338516874

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.325676523044078
Fold 2 IBS: 0.24304825871263852
Fold 3 IBS: 0.32959725402563417
Fold 4 IBS: 0.28525857993950676
Fold 5 IBS: 0.27275166189156874
[I 2024-04-14 22:23:26,243] Trial 0 finished with value: 0.29126645552268526 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4243468471583305
Fold 2 IBS: 0.3901688969230736
Fold 3 IBS: 0.3925037735733181
Fold 4 IBS: 0.37084045783124014
Fold 5 IBS: 0.34079939992495495
[I 2024-04-14 22:23:33,849] Trial 1 finished with value: 0.3837318750821835 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.388663470563614
Fold 2 IBS: 0.30068109749088767
Fold 3 IBS: 0.37991021668413694
Fold 4 IBS: 0.31125225156593306
Fold 5 IBS: 0.33025000236569196
[I 2024-04-14 22:23:35,608] Trial 2 finished with value: 0.3421514077340527 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.39180502103928067
Fold 2 IBS: 0.2723339174348366
Fold 3 IBS: 0.3810564835553453
Fold 4 IBS: 0.31083880707894046
Fold 5 IBS: 0.32302330983004995
[I 2024-04-14 22:23:37,612] Trial 3 finished with value: 0.3358115077876906 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.3942661310659211
Fold 2 IBS: 0.2786887228590945
Fold 3 IBS: 0.38453417136199225
Fold 4 IBS: 0.3097129889615458
Fold 5 IBS: 0.33866987350053085
[I 2024-04-14 22:23:41,258] Trial 4 finished with value: 0.34117437754981694 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4122519263817958
Fold 2 IBS: 0.37802969684822957
Fold 3 IBS: 0.39159093324564376
Fold 4 IBS: 0.3474683993736778
Fold 5 IBS: 0.331005424885477
[I 2024-04-14 22:23:46,085] Trial 5 finished with value: 0.3720692761469648 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.29828726911528397
Fold 2 IBS: 0.21645133017694293
Fold 3 IBS: 0.29703048020856426
Fold 4 IBS: 0.2630471709724218
Fold 5 IBS: 0.24865969387198464
[I 2024-04-14 22:23:48,742] Trial 6 finished with value: 0.26469518886903953 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.26469518886903953.
Fold 1 IBS: 0.2557242083039886
Fold 2 IBS: 0.20086012542584775
Fold 3 IBS: 0.2559954533104581
Fold 4 IBS: 0.22842064037634063
Fold 5 IBS: 0.21078271864122022
[I 2024-04-14 22:23:49,108] Trial 7 finished with value: 0.23035662921157102 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.3320623714087893
Fold 2 IBS: 0.24778879382834276
Fold 3 IBS: 0.33914263875054795
Fold 4 IBS: 0.28890146090534946
Fold 5 IBS: 0.2812784361061495
[I 2024-04-14 22:23:51,201] Trial 8 finished with value: 0.2978347401998358 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.41355256605441043
Fold 2 IBS: 0.3803418251430308
Fold 3 IBS: 0.391840649836237
Fold 4 IBS: 0.35131804113613163
Fold 5 IBS: 0.3420174736572878
[I 2024-04-14 22:23:56,869] Trial 9 finished with value: 0.3758141111654195 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24688672048424357
Fold 2 IBS: 0.23091253666135533
Fold 3 IBS: 0.22886383485395365
Fold 4 IBS: 0.2411627533361748
Fold 5 IBS: 0.22809345046771862
[I 2024-04-14 22:23:57,177] Trial 10 finished with value: 0.23518385916068918 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24591184955753378
Fold 2 IBS: 0.22742364641206644
Fold 3 IBS: 0.22872479609872584
Fold 4 IBS: 0.23866162133190572
Fold 5 IBS: 0.22419206168941844
[I 2024-04-14 22:23:57,373] Trial 11 finished with value: 0.23298279501793004 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.2785597117081745
Fold 2 IBS: 0.20674997718934848
Fold 3 IBS: 0.3033964040369018
Fold 4 IBS: 0.25665036329920676
Fold 5 IBS: 0.2440694773242412
[I 2024-04-14 22:23:57,870] Trial 12 finished with value: 0.25788518671157457 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24533484626464844
Fold 2 IBS: 0.22482603295491327
Fold 3 IBS: 0.2288900501286023
Fold 4 IBS: 0.2368692484235475
Fold 5 IBS: 0.22138571816323843
[I 2024-04-14 22:23:58,057] Trial 13 finished with value: 0.23146117918699 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.2838507400334174
Fold 2 IBS: 0.2064642223133477
Fold 3 IBS: 0.2862860280530503
Fold 4 IBS: 0.24790860860459804
Fold 5 IBS: 0.23314936884966506
[I 2024-04-14 22:23:58,954] Trial 14 finished with value: 0.25153179357081573 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.35006944344323987
Fold 2 IBS: 0.2558059352575901
Fold 3 IBS: 0.35764903579940016
Fold 4 IBS: 0.2961404203062488
Fold 5 IBS: 0.30092599232489686
[I 2024-04-14 22:23:59,872] Trial 15 finished with value: 0.31211816542627513 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.3594115482908769
Fold 2 IBS: 0.251393363830728
Fold 3 IBS: 0.3696313566225124
Fold 4 IBS: 0.2886210010497518
Fold 5 IBS: 0.31474824773557986
[I 2024-04-14 22:24:03,055] Trial 16 finished with value: 0.3167611035058898 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23035662921157102.
Fold 1 IBS: 0.24637560220536686
Fold 2 IBS: 0.21110503456978988
Fold 3 IBS: 0.23491938690940084
Fold 4 IBS: 0.22943718629070567
Fold 5 IBS: 0.21121348311812857
[I 2024-04-14 22:24:03,481] Trial 17 finished with value: 0.22661013861867835 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.291291305025286
Fold 2 IBS: 0.21140388138900232
Fold 3 IBS: 0.28863212236387226
Fold 4 IBS: 0.2563863518782749
Fold 5 IBS: 0.24311757382074356
[I 2024-04-14 22:24:07,126] Trial 18 finished with value: 0.2581662468954358 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2734286915536386
Fold 2 IBS: 0.20097901536547996

Fold 3 IBS: 0.2756019255493613
Fold 4 IBS: 0.2426706185564074
Fold 5 IBS: 0.22283081379821795
[I 2024-04-14 22:24:08,148] Trial 19 finished with value: 0.24310221296462103 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24550608887605468
Fold 2 IBS: 0.2133505584021398
Fold 3 IBS: 0.23294747738469943
Fold 4 IBS: 0.23024731593258208
Fold 5 IBS: 0.2123372739360029
[I 2024-04-14 22:24:08,573] Trial 20 finished with value: 0.22687774290629575 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448259892509062
Fold 2 IBS: 0.21786672573833757
Fold 3 IBS: 0.23050391968540718
Fold 4 IBS: 0.23249100529840805
Fold 5 IBS: 0.215533050087791
[I 2024-04-14 22:24:09,005] Trial 21 finished with value: 0.22824413801216997 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24640086873642586
Fold 2 IBS: 0.2292326597688009
Fold 3 IBS: 0.22875342577755223
Fold 4 IBS: 0.23993607277337323
Fold 5 IBS: 0.22642423701728293
[I 2024-04-14 22:24:09,518] Trial 22 finished with value: 0.23414945281468702 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2589848196302069
Fold 2 IBS: 0.2024618720492697
Fold 3 IBS: 0.25302707950360914
Fold 4 IBS: 0.23227378691244918
Fold 5 IBS: 0.21704698047063445
[I 2024-04-14 22:24:10,504] Trial 23 finished with value: 0.23275890771323388 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24622272418585897
Fold 2 IBS: 0.211517231301511
Fold 3 IBS: 0.23465708353277137
Fold 4 IBS: 0.22958311755255775
Fold 5 IBS: 0.21133338172755428
[I 2024-04-14 22:24:10,931] Trial 24 finished with value: 0.2266627076600507 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.27824402320018216
Fold 2 IBS: 0.20485085384499563
Fold 3 IBS: 0.2745783058664053
Fold 4 IBS: 0.24546543206826768
Fold 5 IBS: 0.23263373515357302
[I 2024-04-14 22:24:11,861] Trial 25 finished with value: 0.24715447002668472 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.33014689072398445
Fold 2 IBS: 0.24720038348309642
Fold 3 IBS: 0.3344515997942725
Fold 4 IBS: 0.28780550809923416
Fold 5 IBS: 0.2783585358589275
[I 2024-04-14 22:24:13,647] Trial 26 finished with value: 0.295592583591903 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24499219484414198
Fold 2 IBS: 0.21624851273382031
Fold 3 IBS: 0.2314723911058174
Fold 4 IBS: 0.23142113333280664
Fold 5 IBS: 0.21391217014232608
[I 2024-04-14 22:24:14,112] Trial 27 finished with value: 0.2276092804317825 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24515366399581964
Fold 2 IBS: 0.21501049991641955
Fold 3 IBS: 0.23211607481589766
Fold 4 IBS: 0.23087262715339726
Fold 5 IBS: 0.2134002972589192
[I 2024-04-14 22:24:14,765] Trial 28 finished with value: 0.22731063262809065 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3063594897860022
Fold 2 IBS: 0.22365458368515215
Fold 3 IBS: 0.3055669075377605
Fold 4 IBS: 0.2699993099904004
Fold 5 IBS: 0.25609676833722445
[I 2024-04-14 22:24:15,609] Trial 29 finished with value: 0.2723354118673079 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3037100708108595
Fold 2 IBS: 0.22137743897919782
Fold 3 IBS: 0.3028696552655383
Fold 4 IBS: 0.2673327822795468
Fold 5 IBS: 0.253763234707761
[I 2024-04-14 22:24:16,745] Trial 30 finished with value: 0.2698106364085807 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2449141797735416
Fold 2 IBS: 0.21676885376764835
Fold 3 IBS: 0.23117242159093349
Fold 4 IBS: 0.2319218743035483
Fold 5 IBS: 0.2146636746811494
[I 2024-04-14 22:24:17,452] Trial 31 finished with value: 0.2278882008233642 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24480968404806477
Fold 2 IBS: 0.21840173072243738
Fold 3 IBS: 0.2303084891481403
Fold 4 IBS: 0.23294002575148984
Fold 5 IBS: 0.21611746639599275
[I 2024-04-14 22:24:17,826] Trial 32 finished with value: 0.22851547921322504 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24444290623218176
Fold 2 IBS: 0.22003318344553727
Fold 3 IBS: 0.23004295934041907
Fold 4 IBS: 0.23318439942131822
Fold 5 IBS: 0.21729227081764876
[I 2024-04-14 22:24:18,423] Trial 33 finished with value: 0.228999143851421 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2599735862383478
Fold 2 IBS: 0.20223791307592695
Fold 3 IBS: 0.25497930340177116
Fold 4 IBS: 0.23208609347398076
Fold 5 IBS: 0.2141781691601287
[I 2024-04-14 22:24:19,353] Trial 34 finished with value: 0.2326910130700311 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24663201725543496
Fold 2 IBS: 0.2300001255908101
Fold 3 IBS: 0.22880051556212538
Fold 4 IBS: 0.2405667786146309
Fold 5 IBS: 0.2271226637337803
[I 2024-04-14 22:24:19,555] Trial 35 finished with value: 0.23462442015135632 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.367577937922695
Fold 2 IBS: 0.27682015096192025
Fold 3 IBS: 0.3682948275396474
Fold 4 IBS: 0.30452048859388936
Fold 5 IBS: 0.31541637422362634
[I 2024-04-14 22:24:25,056] Trial 36 finished with value: 0.32652595584835564 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.39841893189624056
Fold 2 IBS: 0.32060019829104597
Fold 3 IBS: 0.3852983569562301
Fold 4 IBS: 0.31620276009532605
Fold 5 IBS: 0.33770453446230725
[I 2024-04-14 22:24:27,168] Trial 37 finished with value: 0.35164495634023 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2614340968260537
Fold 2 IBS: 0.2021120088730102

Fold 3 IBS: 0.2566141669263308
Fold 4 IBS: 0.23453614765450895
Fold 5 IBS: 0.2122914778844625
[I 2024-04-14 22:24:28,671] Trial 38 finished with value: 0.2333975796328732 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2943463281154152
Fold 2 IBS: 0.21435275898375683
Fold 3 IBS: 0.292776623523439
Fold 4 IBS: 0.2606234117164125
Fold 5 IBS: 0.24191548716779984
[I 2024-04-14 22:24:29,042] Trial 39 finished with value: 0.26080292190136467 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2956705905294083
Fold 2 IBS: 0.21430445848659016
Fold 3 IBS: 0.2928588854990794
Fold 4 IBS: 0.2596622123064148
Fold 5 IBS: 0.24678618384472736
[I 2024-04-14 22:24:29,731] Trial 40 finished with value: 0.261856466133244 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2455156591195911
Fold 2 IBS: 0.2134495272871624
Fold 3 IBS: 0.23298021917302758
Fold 4 IBS: 0.2302623346190742
Fold 5 IBS: 0.21228868131417766
[I 2024-04-14 22:24:30,079] Trial 41 finished with value: 0.22689928430260659 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448957834513211
Fold 2 IBS: 0.2170005935741622
Fold 3 IBS: 0.2310161992206827
Fold 4 IBS: 0.23202460062538527
Fold 5 IBS: 0.21439769364800865
[I 2024-04-14 22:24:30,354] Trial 42 finished with value: 0.22786697410391196 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2658273736705565
Fold 2 IBS: 0.2020524405250075
Fold 3 IBS: 0.2606080098559383
Fold 4 IBS: 0.23638269291325226
Fold 5 IBS: 0.2218591947364019
[I 2024-04-14 22:24:30,881] Trial 43 finished with value: 0.23734594234023126 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24553832608292522
Fold 2 IBS: 0.22567851914167422
Fold 3 IBS: 0.22880097138904068
Fold 4 IBS: 0.23740161794197437
Fold 5 IBS: 0.22252686111769712
[I 2024-04-14 22:24:31,262] Trial 44 finished with value: 0.2319892591346623 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24514475725184326
Fold 2 IBS: 0.2232932452954966
Fold 3 IBS: 0.229031285656079
Fold 4 IBS: 0.23565641281785177
Fold 5 IBS: 0.2206722434927271
[I 2024-04-14 22:24:31,499] Trial 45 finished with value: 0.23075958890279952 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.34556775223404884
Fold 2 IBS: 0.26003024903765853
Fold 3 IBS: 0.35086044091810686
Fold 4 IBS: 0.29629520252719266
Fold 5 IBS: 0.2940333944770714
[I 2024-04-14 22:24:32,453] Trial 46 finished with value: 0.30935740783881566 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2540323022244742
Fold 2 IBS: 0.19805028914151954
Fold 3 IBS: 0.25415324167744757
Fold 4 IBS: 0.22627491702741187
Fold 5 IBS: 0.21162765491344585
[I 2024-04-14 22:24:33,110] Trial 47 finished with value: 0.22882768099685982 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.25728763936252025
Fold 2 IBS: 0.20231216512367317
Fold 3 IBS: 0.25262795298766366
Fold 4 IBS: 0.23138017803988314
Fold 5 IBS: 0.21120324156934484
[I 2024-04-14 22:24:34,708] Trial 48 finished with value: 0.23096223541661703 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24673307008984274
Fold 2 IBS: 0.23042055290160676
Fold 3 IBS: 0.22882596707663166
Fold 4 IBS: 0.2408186354309607
Fold 5 IBS: 0.22754159795832032
[I 2024-04-14 22:24:34,875] Trial 49 finished with value: 0.23486796469147248 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2703393986257053
Fold 2 IBS: 0.20257051463406026
Fold 3 IBS: 0.2660776078398826
Fold 4 IBS: 0.23954054354969337
Fold 5 IBS: 0.22554209413235315
[I 2024-04-14 22:24:35,776] Trial 50 finished with value: 0.24081403175633892 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24526003850914455
Fold 2 IBS: 0.21467902770255018
Fold 3 IBS: 0.23231863109009884
Fold 4 IBS: 0.23070537111335643
Fold 5 IBS: 0.2129056406944009
[I 2024-04-14 22:24:36,126] Trial 51 finished with value: 0.2271737418219102 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2465932017623929
Fold 2 IBS: 0.2299268996974446
Fold 3 IBS: 0.22878875620635092
Fold 4 IBS: 0.24043322363238803
Fold 5 IBS: 0.22699010755245638
[I 2024-04-14 22:24:36,532] Trial 52 finished with value: 0.23454643777020653 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24483084636350344
Fold 2 IBS: 0.21994268306656278
Fold 3 IBS: 0.2298159042727
Fold 4 IBS: 0.23377868427496837
Fold 5 IBS: 0.217018869345563
[I 2024-04-14 22:24:36,926] Trial 53 finished with value: 0.22907739746465952 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2542837578406007
Fold 2 IBS: 0.20408105962436318
Fold 3 IBS: 0.24632166462762337
Fold 4 IBS: 0.2299345290491981
Fold 5 IBS: 0.20927255603620012
[I 2024-04-14 22:24:37,147] Trial 54 finished with value: 0.2287787134355971 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2534849870495454
Fold 2 IBS: 0.2041508121560885
Fold 3 IBS: 0.24576477799133983
Fold 4 IBS: 0.22971527127754243
Fold 5 IBS: 0.21306295114857882
[I 2024-04-14 22:24:37,740] Trial 55 finished with value: 0.229235759924619 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24660568247659428
Fold 2 IBS: 0.21064080007395522
Fold 3 IBS: 0.23535116446600424
Fold 4 IBS: 0.22928161830063465
Fold 5 IBS: 0.21108618854351036
[I 2024-04-14 22:24:38,100] Trial 56 finished with value: 0.22659309077213977 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.32634594317205234
Fold 2 IBS: 0.2441074249846434
Fold 3 IBS: 0.33090013102352434

Fold 4 IBS: 0.28596472610806994
Fold 5 IBS: 0.27461860801929316
[I 2024-04-14 22:24:40,225] Trial 57 finished with value: 0.29238736666151666 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2524958013314946
Fold 2 IBS: 0.20467957580837548
Fold 3 IBS: 0.24466604990129345
Fold 4 IBS: 0.22951388023914565
Fold 5 IBS: 0.21232254648299242
[I 2024-04-14 22:24:40,579] Trial 58 finished with value: 0.22873557075266032 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2450766728615442
Fold 2 IBS: 0.21570571438138603
Fold 3 IBS: 0.23170031253784298
Fold 4 IBS: 0.23100841297079955
Fold 5 IBS: 0.21387190006582926
[I 2024-04-14 22:24:40,809] Trial 59 finished with value: 0.2274726025634804 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2799925625848654
Fold 2 IBS: 0.20541721127231735
Fold 3 IBS: 0.27641891339421315
Fold 4 IBS: 0.24728738758668545
Fold 5 IBS: 0.231501204035336
[I 2024-04-14 22:24:41,678] Trial 60 finished with value: 0.24812345577468348 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24506114552036967
Fold 2 IBS: 0.2227391563952413
Fold 3 IBS: 0.22917592951399726
Fold 4 IBS: 0.23541036546351077
Fold 5 IBS: 0.21951860445014307
[I 2024-04-14 22:24:42,294] Trial 61 finished with value: 0.23038104026865242 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.25624845596017926
Fold 2 IBS: 0.2031140844165004
Fold 3 IBS: 0.24945076411968525
Fold 4 IBS: 0.2308386419236711
Fold 5 IBS: 0.21467054375030795
[I 2024-04-14 22:24:43,831] Trial 62 finished with value: 0.23086449803406878 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24525813986654407
Fold 2 IBS: 0.22394706204039122
Fold 3 IBS: 0.22893913491420798
Fold 4 IBS: 0.23632535189099202
Fold 5 IBS: 0.2214331425247103
[I 2024-04-14 22:24:44,614] Trial 63 finished with value: 0.2311805662473691 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2456393866366244
Fold 2 IBS: 0.21299153169174545
Fold 3 IBS: 0.23361997509095692
Fold 4 IBS: 0.22975030626215406
Fold 5 IBS: 0.21253431380250287
[I 2024-04-14 22:24:45,192] Trial 64 finished with value: 0.22690710269679676 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24436030005286818
Fold 2 IBS: 0.21456927917072746
Fold 3 IBS: 0.23251529067371102
Fold 4 IBS: 0.23061435502797772
Fold 5 IBS: 0.21371928695614437
[I 2024-04-14 22:24:45,667] Trial 65 finished with value: 0.22715570237628574 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24425791895146917
Fold 2 IBS: 0.2144102132061209
Fold 3 IBS: 0.2326749313963326
Fold 4 IBS: 0.23050958085920942
Fold 5 IBS: 0.213580757387187
[I 2024-04-14 22:24:46,260] Trial 66 finished with value: 0.22708668036006383 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.30111629951862323
Fold 2 IBS: 0.22040932376290737
Fold 3 IBS: 0.3017744714900754
Fold 4 IBS: 0.2662157921914366
Fold 5 IBS: 0.24893153605233173
[I 2024-04-14 22:24:50,416] Trial 67 finished with value: 0.26768948460307485 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.37509937493932133
Fold 2 IBS: 0.28368774613275377
Fold 3 IBS: 0.3742704223614346
Fold 4 IBS: 0.3062111301277816
Fold 5 IBS: 0.32272587873763087
[I 2024-04-14 22:24:56,808] Trial 68 finished with value: 0.3323989104597844 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24693470011980795
Fold 2 IBS: 0.2311270655102999
Fold 3 IBS: 0.2288788081398321
Fold 4 IBS: 0.2412571776298174
Fold 5 IBS: 0.22851254319260392
[I 2024-04-14 22:24:57,042] Trial 69 finished with value: 0.2353420589184722 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.3852859364739752
Fold 2 IBS: 0.2874373793502864
Fold 3 IBS: 0.38033520143731914
Fold 4 IBS: 0.3073003186028882
Fold 5 IBS: 0.3331257805315763
[I 2024-04-14 22:25:03,089] Trial 70 finished with value: 0.3386969232792091 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2447983751594558
Fold 2 IBS: 0.21391212397472412
Fold 3 IBS: 0.2330229517211651
Fold 4 IBS: 0.23018009501747053
Fold 5 IBS: 0.21284182693141118
[I 2024-04-14 22:25:03,811] Trial 71 finished with value: 0.22695107456084535 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24442739217118456
Fold 2 IBS: 0.2202080752130095
Fold 3 IBS: 0.22992449606500545
Fold 4 IBS: 0.23367467424256175
Fold 5 IBS: 0.21734687615024553
[I 2024-04-14 22:25:04,346] Trial 72 finished with value: 0.22911630276840134 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24873206449656773
Fold 2 IBS: 0.20714960221304482
Fold 3 IBS: 0.2391494048288076
Fold 4 IBS: 0.22844134347141637
Fold 5 IBS: 0.20990424423992582
[I 2024-04-14 22:25:05,037] Trial 73 finished with value: 0.2266753318499525 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.255704669484436
Fold 2 IBS: 0.20256586151204847
Fold 3 IBS: 0.24898577012417628
Fold 4 IBS: 0.2304554628587353
Fold 5 IBS: 0.2113616322548472
[I 2024-04-14 22:25:05,841] Trial 74 finished with value: 0.22981467924684865 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.26069403640186745
Fold 2 IBS: 0.2002858960044775
Fold 3 IBS: 0.2590273478317007
Fold 4 IBS: 0.23277903197261338
Fold 5 IBS: 0.2129658995167273
[I 2024-04-14 22:25:06,952] Trial 75 finished with value: 0.23315044234547727 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2449207774729007
Fold 2 IBS: 0.2164741146584261
Fold 3 IBS: 0.23115475964699578
Fold 4 IBS: 0.2318272715320025

Fold 5 IBS: 0.21495710360760373
[I 2024-04-14 22:25:07,504] Trial 76 finished with value: 0.22786680538358572 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2506811440240583
Fold 2 IBS: 0.2053539697592853
Fold 3 IBS: 0.2432701864482772
Fold 4 IBS: 0.2284683602008423
Fold 5 IBS: 0.21006566848816424
[I 2024-04-14 22:25:08,691] Trial 77 finished with value: 0.22756786578412544 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24728609182637104
Fold 2 IBS: 0.20948456237788454
Fold 3 IBS: 0.2367879689804507
Fold 4 IBS: 0.22900068533758589
Fold 5 IBS: 0.21042389725248523
[I 2024-04-14 22:25:09,301] Trial 78 finished with value: 0.2265966411549555 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2491522359439618
Fold 2 IBS: 0.20720785646863638
Fold 3 IBS: 0.23970965460068624
Fold 4 IBS: 0.22880108027481874
Fold 5 IBS: 0.2102336161969871
[I 2024-04-14 22:25:09,983] Trial 79 finished with value: 0.22702088869701803 and parameters: {'subsample': 0.6723788047810191, 'dropout_rate': 0.7413305472330791, 'n_estimators': 82, 'learning_rate': 0.01601211448054851}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24520954400807898
Fold 2 IBS: 0.2238125298457514
Fold 3 IBS: 0.22900572731692778
Fold 4 IBS: 0.2362826500145415
Fold 5 IBS: 0.22138753922008994
[I 2024-04-14 22:25:10,432] Trial 80 finished with value: 0.23113959808107792 and parameters: {'subsample': 0.5472725501406392, 'dropout_rate': 0.7943244209025906, 'n_estimators': 49, 'learning_rate': 0.006807484156131071}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24699041341064157
Fold 2 IBS: 0.20997334219713817
Fold 3 IBS: 0.23605719801087272
Fold 4 IBS: 0.22913034206464886
Fold 5 IBS: 0.21064802263090768
[I 2024-04-14 22:25:11,149] Trial 81 finished with value: 0.2265598636628418 and parameters: {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26424067842199594
Fold 2 IBS: 0.2020280704264556
Fold 3 IBS: 0.2598748714749781
Fold 4 IBS: 0.2359141284498117
Fold 5 IBS: 0.21842360306513237
[I 2024-04-14 22:25:11,984] Trial 82 finished with value: 0.23609627036767472 and parameters: {'subsample': 0.5922453928972238, 'dropout_rate': 0.6191715075378723, 'n_estimators': 120, 'learning_rate': 0.019313878373930102}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24781953444770255
Fold 2 IBS: 0.20853906349093898
Fold 3 IBS: 0.23756791720192394
Fold 4 IBS: 0.22887020018619814
Fold 5 IBS: 0.21041983371444753
[I 2024-04-14 22:25:12,492] Trial 83 finished with value: 0.22664330980824224 and parameters: {'subsample': 0.6146609519724093, 'dropout_rate': 0.6421886730626755, 'n_estimators': 78, 'learning_rate': 0.015223953623176103}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.25409839780204135
Fold 2 IBS: 0.20375347292509463
Fold 3 IBS: 0.2467636455182986
Fold 4 IBS: 0.2300581935658389
Fold 5 IBS: 0.21199853281475728
[I 2024-04-14 22:25:13,100] Trial 84 finished with value: 0.22933444852520615 and parameters: {'subsample': 0.6143777540837653, 'dropout_rate': 0.5703883223273155, 'n_estimators': 78, 'learning_rate': 0.02181695324241678}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2454340835099757
Fold 2 IBS: 0.2136961772818287
Fold 3 IBS: 0.23273056567389488
Fold 4 IBS: 0.23041441332302406
Fold 5 IBS: 0.21235879524348852
[I 2024-04-14 22:25:13,855] Trial 85 finished with value: 0.22692680700644238 and parameters: {'subsample': 0.6445770962436083, 'dropout_rate': 0.6275050227423727, 'n_estimators': 92, 'learning_rate': 0.009130620696524702}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24639926921114977
Fold 2 IBS: 0.22928356450634207
Fold 3 IBS: 0.228754183334704
Fold 4 IBS: 0.2399932817551604
Fold 5 IBS: 0.22623158679105324
[I 2024-04-14 22:25:14,109] Trial 86 finished with value: 0.23413237711968188 and parameters: {'subsample': 0.973596102528499, 'dropout_rate': 0.6913304253389554, 'n_estimators': 30, 'learning_rate': 0.003578120462130444}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2781927071106972
Fold 2 IBS: 0.2046340904187838
Fold 3 IBS: 0.2743538100055575
Fold 4 IBS: 0.24537628788578655
Fold 5 IBS: 0.22685278282223925
[I 2024-04-14 22:25:15,291] Trial 87 finished with value: 0.24588193564861288 and parameters: {'subsample': 0.5848767613231778, 'dropout_rate': 0.5581423348405448, 'n_estimators': 110, 'learning_rate': 0.0276271691730997}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24497452272007741
Fold 2 IBS: 0.21606979660825898
Fold 3 IBS: 0.23139670442225413
Fold 4 IBS: 0.2314990720998036
Fold 5 IBS: 0.2141402661253793
[I 2024-04-14 22:25:15,997] Trial 88 finished with value: 0.22761607239515466 and parameters: {'subsample': 0.6722249946799236, 'dropout_rate': 0.6479045648592634, 'n_estimators': 46, 'learning_rate': 0.01557167084756894}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26516278956994344
Fold 2 IBS: 0.20203982539169615
Fold 3 IBS: 0.2600655154320181
Fold 4 IBS: 0.23608038055976957
Fold 5 IBS: 0.21836273665359834
[I 2024-04-14 22:25:18,486] Trial 89 finished with value: 0.2363422495214051 and parameters: {'subsample': 0.6016440183315196, 'dropout_rate': 0.5918885750046846, 'n_estimators': 128, 'learning_rate': 0.018267143567723715}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24573908001820546
Fold 2 IBS: 0.2267737594491462
Fold 3 IBS: 0.22873715282488816
Fold 4 IBS: 0.23814825000178638
Fold 5 IBS: 0.22350505658163744
[I 2024-04-14 22:25:18,746] Trial 90 finished with value: 0.23258065977513276 and parameters: {'subsample': 0.7078102048337904, 'dropout_rate': 0.6730763431068749, 'n_estimators': 9, 'learning_rate': 0.02340866249635589}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24723648683966212
Fold 2 IBS: 0.2097930026030373
Fold 3 IBS: 0.23695352163573088
Fold 4 IBS: 0.22904234996289285
Fold 5 IBS: 0.21058878491646402
[I 2024-04-14 22:25:19,312] Trial 91 finished with value: 0.22672282919155742 and parameters: {'subsample': 0.5313026641418505, 'dropout_rate': 0.5328649004247455, 'n_estimators': 76, 'learning_rate': 0.014627227900695133}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24577407492517803
Fold 2 IBS: 0.21257383264762358
Fold 3 IBS: 0.23379619719392244
Fold 4 IBS: 0.2299460468627917
Fold 5 IBS: 0.21208238643358707
[I 2024-04-14 22:25:20,065] Trial 92 finished with value: 0.22683450761262053 and parameters: {'subsample': 0.5720522744908453, 'dropout_rate': 0.5211260831534085, 'n_estimators': 76, 'learning_rate': 0.011981813096347545}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2464934086281741
Fold 2 IBS: 0.2109727784624746
Fold 3 IBS: 0.23508367038465994
Fold 4 IBS: 0.22944836247402864
Fold 5 IBS: 0.21128845087097128
[I 2024-04-14 22:25:20,739] Trial 93 finished with value: 0.22665733416406172 and parameters: {'subsample': 0.4994903777603958, 'dropout_rate': 0.5262836252450818, 'n_estimators': 87, 'learning_rate': 0.011492132047389617}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24588199063218563
Fold 2 IBS: 0.2125930156354007
Fold 3 IBS: 0.23390337282832738
Fold 4 IBS: 0.22995057861580706
Fold 5 IBS: 0.21216121330590818
[I 2024-04-14 22:25:21,660] Trial 94 finished with value: 0.22689803420352578 and parameters: {'subsample': 0.49968900942877426, 'dropout_rate': 0.523020546752894, 'n_estimators': 82, 'learning_rate': 0.011066289138468185}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24490369228481912
Fold 2 IBS: 0.2167329842481149
Fold 3 IBS: 0.23111158091166403
Fold 4 IBS: 0.23195611702074945
Fold 5 IBS: 0.21507941572440312
[I 2024-04-14 22:25:22,514] Trial 95 finished with value: 0.22795675803795015 and parameters: {'subsample': 0.5665760978972413, 'dropout_rate': 0.4628605993177724, 'n_estimators': 100, 'learning_rate': 0.006666098315025223}. Best is trial 81 with value: 0.2265598636628418.

Fold 1 IBS: 0.3528807852002724
Fold 2 IBS: 0.26163876419301324
Fold 3 IBS: 0.35927296600690356
Fold 4 IBS: 0.2978922662575483
Fold 5 IBS: 0.3041795583962892
[I 2024-04-14 22:25:24,483] Trial 96 finished with value: 0.31517286801080535 and parameters: {'subsample': 0.41313939490511475, 'dropout_rate': 0.5213109482382285, 'n_estimators': 158, 'learning_rate': 0.054487916689644846}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24708172105946397
Fold 2 IBS: 0.21005062605084635
Fold 3 IBS: 0.23658239945020892
Fold 4 IBS: 0.2291089640988238
Fold 5 IBS: 0.2105403389046395
[I 2024-04-14 22:25:25,466] Trial 97 finished with value: 0.2266728099127965 and parameters: {'subsample': 0.5389995281019297, 'dropout_rate': 0.6077476353900257, 'n_estimators': 73, 'learning_rate': 0.014931416501109941}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26183286577938214
Fold 2 IBS: 0.20183342233582774
Fold 3 IBS: 0.2575253907596287
Fold 4 IBS: 0.23417362585495322
Fold 5 IBS: 0.21506795896798186
[I 2024-04-14 22:25:26,758] Trial 98 finished with value: 0.23408665273955473 and parameters: {'subsample': 0.545068613650571, 'dropout_rate': 0.5497522480626178, 'n_estimators': 139, 'learning_rate': 0.01569072107683937}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24506962981870725
Fold 2 IBS: 0.2156886398952901
Fold 3 IBS: 0.23166204482631356
Fold 4 IBS: 0.2313740373654556
Fold 5 IBS: 0.2142704544460028
[I 2024-04-14 22:25:27,712] Trial 99 finished with value: 0.22761296127035385 and parameters: {'subsample': 0.4999064806675035, 'dropout_rate': 0.6190205560651515, 'n_estimators': 90, 'learning_rate': 0.00800890927792778}. Best is trial 81 with value: 0.2265598636628418.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2265598636628418], datetime_start=datetime.datetime(2024, 4, 14, 22, 25, 10, 447964), datetime_complete=datetime.datetime(2024, 4, 14, 22, 25, 11, 148782), params={'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}


* Best Score for IBS:
 0.2265598636628418

In [74]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [75]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.65
train_ibs:  0.227

#### Test

In [76]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [77]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8178252892822001,
                                              learning_rate=0.014116661098438898,
                                              n_estimators=383,
                                              random_state=123,
                                              subsample=0.10146809971965022)

C-index score: 0.531

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6341528845468055,
                                              learning_rate=0.014291926646619518,
                                              n_estimators=76, random_state=123,
                                              subsample=0.6070545538128025)

IBS: 0.234

In [78]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [79]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.845   1.0
ExtraSurvivalTrees               0.837   2.0
GradientBoosting                 0.711   3.0
CoxElastic                       0.705   4.0
CoxPH                            0.703   5.0
CoxLasso                         0.701   6.0
ComponentwiseGradientBoosting    0.650   7.0
CoxRidge                         0.648   8.0

In [80]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
CoxPH                          0.199   2.0
CoxLasso                       0.199   2.0
CoxElastic                     0.199   2.0
Randomsurvivalforest           0.205   4.0
ExtraSurvivalTrees             0.207   5.0
ComponentwiseGradientBoosting  0.227   6.0
GradientBoosting               0.234   7.0
CoxRidge                       0.236   8.0

In [81]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
CoxRidge                         0.537   1.0
ComponentwiseGradientBoosting    0.531   2.0
CoxPH                            0.528   3.5
CoxLasso                         0.528   3.5
CoxElastic                       0.527   5.0
Randomsurvivalforest             0.521   6.0
GradientBoosting                 0.517   7.0
ExtraSurvivalTrees               0.509   8.0

In [82]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ComponentwiseGradientBoosting  0.234   3.0
Randomsurvivalforest           0.248   4.0
ExtraSurvivalTrees             0.259   5.0
CoxLasso                       0.308   6.5
CoxElastic                     0.308   6.5
CoxPH                          0.309   8.0

In [85]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/standard/plsr/'  # Folder path where you want to save the files

# List of corresponding file namess
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_standard_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [86]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14