In [78]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import StandardScaler

In [79]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [80]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [81]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [82]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [83]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [84]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [85]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [86]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [87]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [88]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [89]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [90]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [91]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]


# Selecting features in the DataFrame
X_rent = X[selected_features]

In [92]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [93]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = StandardScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [94]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns

MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [95]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [96]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,1.075042,0.081641,-0.098422,-0.562251
1,0.242767,-0.395928,-1.209119,-0.562251
2,-1.461057,0.208583,0.280542,-0.202838
3,0.078112,-0.949323,-1.147026,-0.562251
4,-2.274305,1.555538,-0.568449,1.514080
...,...,...,...,...
134,0.827589,-0.217633,-0.671191,-0.562251
135,0.578577,1.572043,-0.163918,-0.562251
136,-0.329498,-0.648232,-0.445412,-0.562251
137,0.595927,1.711090,0.143137,-0.562251
138,0.574872,1.203504,-0.843364,-0.562251

In [97]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [98]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,-0.133381,0.800544,0.405980,-0.288893
1,-0.108854,-1.860610,-0.118774,1.182201
2,-0.704414,-0.754955,0.048037,0.033974
3,-1.307469,-1.134568,0.158761,-0.562251
4,-0.615466,-0.128772,0.685437,-0.562251
...,...,...,...,...
94,-0.085581,0.263605,-0.598102,-0.562251
95,-0.599161,-0.859260,0.472444,-0.562251
96,-0.425762,-1.598975,0.432435,-0.562251
97,0.637891,-0.499761,0.081495,-0.562251
98,-0.071514,-1.004520,-0.448243,-0.562251

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [99]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:05:26,946] A new study created in memory with name: no-name-1bf8c919-463d-45bb-89a9-fb488593abcf

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-14 22:05:27,292] A new study created in memory with name: no-name-ed177a89-2bdb-4577-a351-fa40d1691fb0

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:27,222] Trial 0 finished with value: 0.6885812252956434 and parameters: {}. Best is trial 0 with value: 0.6885812252956434.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6885812252956434], datetime_start=datetime.datetime(2024, 4, 14, 22, 5, 27, 15861), datetime_complete=datetime.datetime(2024, 4, 14, 22, 5, 27, 222679), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6885812252956434

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24445113125013965
Fold 2 IBS: 0.19124878012978022
Fold 3 IBS: 0.20665297767216081
Fold 4 IBS: 0.19438765965098836
Fold 5 IBS: 0.197759489882654
[I 2024-04-14 22:05:27,518] Trial 0 finished with value: 0.20690000771714462 and parameters: {}. Best is trial 0 with value: 0.20690000771714462.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20690000771714462], datetime_start=datetime.datetime(2024, 4, 14, 22, 5, 27, 354043), datetime_complete=datetime.datetime(2024, 4, 14, 22, 5, 27, 517901), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20690000771714462

In [100]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [101]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.689
train_ibs:  0.207

#### Test

In [102]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [103]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.532
IBS score: 0.29

In [104]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [105]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [106]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:05:27,756] A new study created in memory with name: no-name-1f4e87a3-d196-47f7-a3cc-6037e62d6369

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5702127659574469

[I 2024-04-14 22:05:27,939] A new study created in memory with name: no-name-ec35f23f-3d56-4b17-ada6-d8a187e899bf

Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6759656652360515
[I 2024-04-14 22:05:27,928] Trial 0 finished with value: 0.6629436568439727 and parameters: {}. Best is trial 0 with value: 0.6629436568439727.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6629436568439727], datetime_start=datetime.datetime(2024, 4, 14, 22, 5, 27, 794921), datetime_complete=datetime.datetime(2024, 4, 14, 22, 5, 27, 928313), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6629436568439727

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709421972138
Fold 2 IBS: 0.23203987311750648
Fold 3 IBS: 0.22898186706001533
Fold 4 IBS: 0.24197476010091573
Fold 5 IBS: 0.2293955839675724
[I 2024-04-14 22:05:28,175] Trial 0 finished with value: 0.23592783569314624 and parameters: {}. Best is trial 0 with value: 0.23592783569314624.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783569314624], datetime_start=datetime.datetime(2024, 4, 14, 22, 5, 28, 10361), datetime_complete=datetime.datetime(2024, 4, 14, 22, 5, 28, 175129), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783569314624

In [107]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [108]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.663
train_ibs:  0.236

#### Test

In [109]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [110]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.539

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [111]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [112]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:05:28,377] A new study created in memory with name: no-name-d32ca149-edb0-4f69-83c2-92e30e96a087

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734

[I 2024-04-14 22:05:28,824] A new study created in memory with name: no-name-761d7a50-1aba-441a-8ce3-9aea47dbab6f

Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:28,819] Trial 0 finished with value: 0.6910259146234387 and parameters: {}. Best is trial 0 with value: 0.6910259146234387.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6910259146234387], datetime_start=datetime.datetime(2024, 4, 14, 22, 5, 28, 461041), datetime_complete=datetime.datetime(2024, 4, 14, 22, 5, 28, 819351), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6910259146234387

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24331006599898158
Fold 2 IBS: 0.1911934758131866
Fold 3 IBS: 0.20675927385724954
Fold 4 IBS: 0.19435877417580916
Fold 5 IBS: 0.198512695677751
[I 2024-04-14 22:05:29,184] Trial 0 finished with value: 0.2068268571045956 and parameters: {}. Best is trial 0 with value: 0.2068268571045956.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2068268571045956], datetime_start=datetime.datetime(2024, 4, 14, 22, 5, 28, 864532), datetime_complete=datetime.datetime(2024, 4, 14, 22, 5, 29, 184110), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2068268571045956

In [113]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [114]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.691
train_ibs:  0.207

#### Test

In [115]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [116]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.288

In [117]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [118]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:05:29,502] A new study created in memory with name: no-name-b9c053af-9e49-452e-b276-c23fd78123db

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:30,071] Trial 0 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:30,347] Trial 1 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:30,632] Trial 2 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:31,000] Trial 3 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:31,440] Trial 4 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:32,438] Trial 5 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:33,448] Trial 6 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:33,988] Trial 7 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:34,341] Trial 8 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:34,597] Trial 9 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:34,922] Trial 10 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:05:35,278] Trial 11 finished with value: 0.6611740335489904 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:35,736] Trial 12 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.21309581087335225}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:36,027] Trial 13 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.743964055575976}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:36,383] Trial 14 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.21599024455432275}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:36,669] Trial 15 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.820763570686791}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:36,965] Trial 16 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5880713606511995}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:37,374] Trial 17 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.35870521424355084}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:05:37,568] Trial 18 finished with value: 0.6528002114854601 and parameters: {'l1_ratio': 0.039318771596377255}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:37,932] Trial 19 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:38,471] Trial 20 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:39,193] Trial 21 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.26843065456411686}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:39,833] Trial 22 finished with value: 0.6893780380446474 and parameters: {'l1_ratio': 0.13361135845786085}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:40,320] Trial 23 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.2976235432977797}. Best is trial 0 with value: 0.6910259146234387.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:41,087] Trial 24 finished with value: 0.6893780380446474 and parameters: {'l1_ratio': 0.15433706302991543}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:41,509] Trial 25 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4626599986704694}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:41,842] Trial 26 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3312072877416866}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:42,213] Trial 27 finished with value: 0.6893780380446474 and parameters: {'l1_ratio': 0.09486155085202524}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:42,530] Trial 28 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.2025095518368651}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:42,822] Trial 29 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6145503344695415}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:05:42,930] Trial 30 finished with value: 0.652890819041483 and parameters: {'l1_ratio': 0.0035318578749415352}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:43,264] Trial 31 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5342430724558584}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:43,558] Trial 32 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6960437702247678}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:43,908] Trial 33 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5593871049626861}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:44,358] Trial 34 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4211712386563343}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:44,635] Trial 35 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7958525494256051}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:45,101] Trial 36 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.50639081359896}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:45,449] Trial 37 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6697205263544034}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:45,733] Trial 38 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6537473008662477}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:46,034] Trial 39 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:46,335] Trial 40 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.26418109350708213}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:46,613] Trial 41 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7256161860307132}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:46,942] Trial 42 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7880264954590498}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:47,197] Trial 43 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9153215428357782}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:47,500] Trial 44 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.38013291367195734}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:47,813] Trial 45 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7592444182955842}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:48,106] Trial 46 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6258868107426709}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:48,403] Trial 47 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8434660181559295}. Best is trial 0 with value: 0.6910259146234387.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:48,685] Trial 48 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5675456270820948}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:48,973] Trial 49 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7153190338760974}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:49,339] Trial 50 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5027665121167861}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:49,638] Trial 51 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4343748320430144}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:49,991] Trial 52 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3205419509778473}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:50,284] Trial 53 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.24112783716201702}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:50,666] Trial 54 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.18839030732904585}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:50,969] Trial 55 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3443780252277794}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:51,348] Trial 56 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3830173282532755}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:51,627] Trial 57 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.2881177005412072}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:51,932] Trial 58 finished with value: 0.6893780380446474 and parameters: {'l1_ratio': 0.15943922435683724}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:52,291] Trial 59 finished with value: 0.6893780380446474 and parameters: {'l1_ratio': 0.11164662896587693}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:52,571] Trial 60 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9036037359091886}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:52,874] Trial 61 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9670348868417531}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:53,154] Trial 62 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.97871893028343}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:53,450] Trial 63 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.40821226975067815}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:53,715] Trial 64 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.525537885544615}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:53,989] Trial 65 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6419636889413851}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:54,384] Trial 66 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4695646906661062}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:54,632] Trial 67 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5755740346364364}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:54,914] Trial 68 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.22846750133299182}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:55,158] Trial 69 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6916888919217767}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:55,408] Trial 70 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.768976810819166}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:55,704] Trial 71 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5939686763494029}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877

Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:55,985] Trial 72 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.834486230848803}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:56,306] Trial 73 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5504312631377132}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:56,587] Trial 74 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6754459294745178}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:56,861] Trial 75 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8746987589861724}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:57,176] Trial 76 finished with value: 0.666399314640392 and parameters: {'l1_ratio': 0.070224175299129}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:57,630] Trial 77 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.18559634901200903}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:57,899] Trial 78 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7283854796904858}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:58,180] Trial 79 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3083198538951853}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:58,451] Trial 80 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8015395928294601}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:58,754] Trial 81 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4929382116678618}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:59,021] Trial 82 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4745826212598208}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:59,300] Trial 83 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3602379294474314}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:59,583] Trial 84 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.25546055543843504}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:05:59,963] Trial 85 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:00,289] Trial 86 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.5322933555815866}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:00,557] Trial 87 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.44528991043718924}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:00,845] Trial 88 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.6420436217559755}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:01,190] Trial 89 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9424220328275571}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:01,517] Trial 90 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7032927099515806}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:01,833] Trial 91 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.28649138832750976}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:02,140] Trial 92 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.3939149718995682}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:02,440] Trial 93 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.42498360746775166}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:02,738] Trial 94 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.35640327479951417}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:03,019] Trial 95 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.7539180027651575}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877

Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:03,316] Trial 96 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.33531618616504993}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:03,622] Trial 97 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.4965881146918674}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:03,918] Trial 98 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.396923248195223}. Best is trial 0 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876

[I 2024-04-14 22:06:04,224] A new study created in memory with name: no-name-48245e81-b382-4205-9f9c-9d43d30b2f40

Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:04,213] Trial 99 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.21243871234128145}. Best is trial 0 with value: 0.6910259146234387.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6910259146234387], datetime_start=datetime.datetime(2024, 4, 14, 22, 5, 29, 549338), datetime_complete=datetime.datetime(2024, 4, 14, 22, 5, 30, 71564), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.6910259146234387

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2433156114036618
Fold 2 IBS: 0.19115530450118298
Fold 3 IBS: 0.20654328851646514
Fold 4 IBS: 0.19431453572655688
Fold 5 IBS: 0.19840304293834035
[I 2024-04-14 22:06:04,582] Trial 0 finished with value: 0.20674635661724144 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.20674635661724144.
Fold 1 IBS: 0.24345534898240948
Fold 2 IBS: 0.19106167895592804
Fold 3 IBS: 0.2059890726266797
Fold 4 IBS: 0.1941873317240624
Fold 5 IBS: 0.1981025500302711
[I 2024-04-14 22:06:04,902] Trial 1 finished with value: 0.20655919646387016 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.20655919646387016.
Fold 1 IBS: 0.24352041762954318
Fold 2 IBS: 0.19104563842317818
Fold 3 IBS: 0.20588536144687355
Fold 4 IBS: 0.1941465437949834
Fold 5 IBS: 0.19803689766826307
[I 2024-04-14 22:06:05,239] Trial 2 finished with value: 0.20652697179256826 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.24334086391688084
Fold 2 IBS: 0.19112942178772988
Fold 3 IBS: 0.2063920873550314
Fold 4 IBS: 0.1942837434878405
Fold 5 IBS: 0.19828474612204844
[I 2024-04-14 22:06:05,578] Trial 3 finished with value: 0.2066861725339062 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.24332548580353816
Fold 2 IBS: 0.19115963328581026
Fold 3 IBS: 0.20656481440401053
Fold 4 IBS: 0.19431910817551307
Fold 5 IBS: 0.19846618630976146
[I 2024-04-14 22:06:05,855] Trial 4 finished with value: 0.20676704559572667 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.24343735882304576
Fold 2 IBS: 0.1911072284757582
Fold 3 IBS: 0.20624350338709607
Fold 4 IBS: 0.19424494720368277
Fold 5 IBS: 0.19818675546681516
[I 2024-04-14 22:06:06,149] Trial 5 finished with value: 0.2066439586712796 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.24330539804121823
Fold 2 IBS: 0.19119141704623677
Fold 3 IBS: 0.20674900813496738
Fold 4 IBS: 0.19435661733834528
Fold 5 IBS: 0.19851129505125997
[I 2024-04-14 22:06:06,518] Trial 6 finished with value: 0.2068227471224055 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.24331036632644856
Fold 2 IBS: 0.19115300830466303
Fold 3 IBS: 0.2065318605617709
Fold 4 IBS: 0.1943121077712945
Fold 5 IBS: 0.1984025016930321
[I 2024-04-14 22:06:06,847] Trial 7 finished with value: 0.2067419689314418 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.2433906749715971
Fold 2 IBS: 0.19111752206545787
Fold 3 IBS: 0.20631278550420895
Fold 4 IBS: 0.1942598477408941
Fold 5 IBS: 0.1982332429870926
[I 2024-04-14 22:06:07,161] Trial 8 finished with value: 0.20666281465385014 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.2434072535974265
Fold 2 IBS: 0.1910940960874116
Fold 3 IBS: 0.20617911661230956
Fold 4 IBS: 0.19422970784524307
Fold 5 IBS: 0.19814596810319074
[I 2024-04-14 22:06:07,472] Trial 9 finished with value: 0.2066112284491163 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.20652697179256826.
Fold 1 IBS: 0.243679420686421
Fold 2 IBS: 0.19096940541160512
Fold 3 IBS: 0.20545463051864474
Fold 4 IBS: 0.1940408463776027
Fold 5 IBS: 0.19786834264622075
[I 2024-04-14 22:06:07,838] Trial 10 finished with value: 0.20640252912809887 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 10 with value: 0.20640252912809887.
Fold 1 IBS: 0.24651386455298116
Fold 2 IBS: 0.23068617664474228
Fold 3 IBS: 0.22888129976262106
Fold 4 IBS: 0.24063682959561172
Fold 5 IBS: 0.22832620259373046
[I 2024-04-14 22:06:07,980] Trial 11 finished with value: 0.23500887462993733 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 10 with value: 0.20640252912809887.
Fold 1 IBS: 0.24367883303453994
Fold 2 IBS: 0.1909691312347668
Fold 3 IBS: 0.2054533188999548
Fold 4 IBS: 0.194040491894678
Fold 5 IBS: 0.19786831972391478
[I 2024-04-14 22:06:08,337] Trial 12 finished with value: 0.20640201895757088 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2470499080045225
Fold 2 IBS: 0.2316777688172811
Fold 3 IBS: 0.2289511978497366
Fold 4 IBS: 0.24161503786625416
Fold 5 IBS: 0.22910801443000903
[I 2024-04-14 22:06:08,479] Trial 13 finished with value: 0.23568038539356068 and parameters: {'l1_ratio': 0.0031985064812224406}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24360946813503787
Fold 2 IBS: 0.19099701014252465
Fold 3 IBS: 0.2056204940838331
Fold 4 IBS: 0.1941047642802518
Fold 5 IBS: 0.19795641938857786
[I 2024-04-14 22:06:08,826] Trial 14 finished with value: 0.20645763120604504 and parameters: {'l1_ratio': 0.14354731809284052}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436164536962923
Fold 2 IBS: 0.19100027737582428
Fold 3 IBS: 0.20563626836470636
Fold 4 IBS: 0.19410864054051585
Fold 5 IBS: 0.19795675585721914
[I 2024-04-14 22:06:09,204] Trial 15 finished with value: 0.20646367916691158 and parameters: {'l1_ratio': 0.14547377630010583}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24357462666883395
Fold 2 IBS: 0.19100190098950667
Fold 3 IBS: 0.20563599592408704
Fold 4 IBS: 0.19408546748082403
Fold 5 IBS: 0.19793640030270793
[I 2024-04-14 22:06:09,574] Trial 16 finished with value: 0.2064468782731919 and parameters: {'l1_ratio': 0.13463318817607284}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24346237043201197
Fold 2 IBS: 0.19106472275573877
Fold 3 IBS: 0.20600391723620873
Fold 4 IBS: 0.19419089247049065
Fold 5 IBS: 0.1981029794991238
[I 2024-04-14 22:06:10,049] Trial 17 finished with value: 0.2065649764787148 and parameters: {'l1_ratio': 0.2906031874230555}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24368795592276316
Fold 2 IBS: 0.2256280192024369
Fold 3 IBS: 0.22874864594385858
Fold 4 IBS: 0.23581095356002282
Fold 5 IBS: 0.19784295062598375
[I 2024-04-14 22:06:10,371] Trial 18 finished with value: 0.22634370505101303 and parameters: {'l1_ratio': 0.0668769468789637}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24330837299096092
Fold 2 IBS: 0.19119272843054697
Fold 3 IBS: 0.20675554774907715
Fold 4 IBS: 0.19435799134847598
Fold 5 IBS: 0.1985121869660004
[I 2024-04-14 22:06:10,685] Trial 19 finished with value: 0.2068253654970123 and parameters: {'l1_ratio': 0.9929341434741732}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24354474271292936
Fold 2 IBS: 0.1910398540046431
Fold 3 IBS: 0.2058693740803627
Fold 4 IBS: 0.19415998380074465
Fold 5 IBS: 0.1980382743716144
[I 2024-04-14 22:06:11,031] Trial 20 finished with value: 0.20653044579405883 and parameters: {'l1_ratio': 0.2388803760219412}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436064444323451
Fold 2 IBS: 0.19096815262286837
Fold 3 IBS: 0.20556641824650773
Fold 4 IBS: 0.19406903103568404
Fold 5 IBS: 0.1978996418019504
[I 2024-04-14 22:06:11,485] Trial 21 finished with value: 0.20642193762787117 and parameters: {'l1_ratio': 0.10825799833043775}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24364501194956745
Fold 2 IBS: 0.19097415641876334
Fold 3 IBS: 0.205587171076288
Fold 4 IBS: 0.19404815206676237
Fold 5 IBS: 0.1978981617895767
[I 2024-04-14 22:06:11,863] Trial 22 finished with value: 0.2064305306601916 and parameters: {'l1_ratio': 0.10159828709381563}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24355286251134198
Fold 2 IBS: 0.19102273263433095
Fold 3 IBS: 0.20584917558707014
Fold 4 IBS: 0.1941383483937395
Fold 5 IBS: 0.19800881521158256
[I 2024-04-14 22:06:12,223] Trial 23 finished with value: 0.20651438686761306 and parameters: {'l1_ratio': 0.20450032756347597}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24343957101568897
Fold 2 IBS: 0.1910802421757452
Fold 3 IBS: 0.2060946547260997
Fold 4 IBS: 0.19421109472296638
Fold 5 IBS: 0.19814196139903614
[I 2024-04-14 22:06:12,652] Trial 24 finished with value: 0.20659350480790728 and parameters: {'l1_ratio': 0.3389201479305571}. Best is trial 12 with value: 0.20640201895757088.

Fold 1 IBS: 0.2450682640426586
Fold 2 IBS: 0.22795487619322505
Fold 3 IBS: 0.22881012278568916
Fold 4 IBS: 0.23799365210664025
Fold 5 IBS: 0.2262129117046938
[I 2024-04-14 22:06:12,869] Trial 25 finished with value: 0.23320796536658137 and parameters: {'l1_ratio': 0.03981317955666948}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24359131338350348
Fold 2 IBS: 0.19102169658035204
Fold 3 IBS: 0.20575844749744293
Fold 4 IBS: 0.19413589776762996
Fold 5 IBS: 0.19800656094777605
[I 2024-04-14 22:06:14,392] Trial 26 finished with value: 0.2065027832353409 and parameters: {'l1_ratio': 0.18783928730207888}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2433607473731579
Fold 2 IBS: 0.19113811271624523
Fold 3 IBS: 0.20643511239831425
Fold 4 IBS: 0.19429297011760782
Fold 5 IBS: 0.19833925037164454
[I 2024-04-14 22:06:15,555] Trial 27 finished with value: 0.20671323859539395 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24365805729806375
Fold 2 IBS: 0.19096936019411132
Fold 3 IBS: 0.20545982796572826
Fold 4 IBS: 0.19404132735626348
Fold 5 IBS: 0.19788234678790204
[I 2024-04-14 22:06:16,405] Trial 28 finished with value: 0.20640218392041376 and parameters: {'l1_ratio': 0.09146853847676947}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2432786248021573
Fold 2 IBS: 0.19118416089363865
Fold 3 IBS: 0.20669015503365215
Fold 4 IBS: 0.19434424703697725
Fold 5 IBS: 0.19850332082475886
[I 2024-04-14 22:06:17,136] Trial 29 finished with value: 0.20680010171823687 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24341643695375628
Fold 2 IBS: 0.1910702361065453
Fold 3 IBS: 0.20604565755998314
Fold 4 IBS: 0.19419941552343142
Fold 5 IBS: 0.19810578624349862
[I 2024-04-14 22:06:17,795] Trial 30 finished with value: 0.20656750647744296 and parameters: {'l1_ratio': 0.32170963481394405}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436633009576301
Fold 2 IBS: 0.19097180357030688
Fold 3 IBS: 0.20547154591567623
Fold 4 IBS: 0.19404448599142773
Fold 5 IBS: 0.19788255532889173
[I 2024-04-14 22:06:18,436] Trial 31 finished with value: 0.20640673835278656 and parameters: {'l1_ratio': 0.09232011433900482}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24365579628137435
Fold 2 IBS: 0.19094941279112151
Fold 3 IBS: 0.22874222487603754
Fold 4 IBS: 0.19404490256807558
Fold 5 IBS: 0.1978443118634644
[I 2024-04-14 22:06:18,839] Trial 32 finished with value: 0.2110473296760147 and parameters: {'l1_ratio': 0.0713123037303855}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24358821914545878
Fold 2 IBS: 0.1910202449026299
Fold 3 IBS: 0.20575141485430148
Fold 4 IBS: 0.19413418394591767
Fold 5 IBS: 0.19800639232768424
[I 2024-04-14 22:06:19,774] Trial 33 finished with value: 0.2065000910351984 and parameters: {'l1_ratio': 0.18665523735409972}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2435299781632431
Fold 2 IBS: 0.1910329231291639
Fold 3 IBS: 0.20590543219693347
Fold 4 IBS: 0.19415182271178452
Fold 5 IBS: 0.1980374330222339
[I 2024-04-14 22:06:20,246] Trial 34 finished with value: 0.20653151784467177 and parameters: {'l1_ratio': 0.23148463885526435}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2471632242651268
Fold 2 IBS: 0.2318859697112438
Fold 3 IBS: 0.2289685011274592
Fold 4 IBS: 0.24182176748335318
Fold 5 IBS: 0.22927327538046438
[I 2024-04-14 22:06:20,464] Trial 35 finished with value: 0.23582254759352947 and parameters: {'l1_ratio': 0.0013526982279536137}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2435161148268484
Fold 2 IBS: 0.19104938814539132
Fold 3 IBS: 0.20592900669422037
Fold 4 IBS: 0.1941729225560546
Fold 5 IBS: 0.19806969410752862
[I 2024-04-14 22:06:20,849] Trial 36 finished with value: 0.20654742526600867 and parameters: {'l1_ratio': 0.26966204197246835}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24370429296479587
Fold 2 IBS: 0.19096374044020942
Fold 3 IBS: 0.22874575954505486
Fold 4 IBS: 0.235670218869743
Fold 5 IBS: 0.1978435422174444
[I 2024-04-14 22:06:21,250] Trial 37 finished with value: 0.21938551080744953 and parameters: {'l1_ratio': 0.06878895945834666}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24338880542165492
Fold 2 IBS: 0.19108608507783703
Fold 3 IBS: 0.20613973060560778
Fold 4 IBS: 0.19422038430439015
Fold 5 IBS: 0.19814478907077282
[I 2024-04-14 22:06:22,197] Trial 38 finished with value: 0.2065959588960525 and parameters: {'l1_ratio': 0.3752900822742875}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24357168201349497
Fold 2 IBS: 0.19099516936139613
Fold 3 IBS: 0.20570786809387992
Fold 4 IBS: 0.1941034478630985
Fold 5 IBS: 0.1979583399515823
[I 2024-04-14 22:06:22,705] Trial 39 finished with value: 0.20646730145669037 and parameters: {'l1_ratio': 0.15486970537243167}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24337937389544287
Fold 2 IBS: 0.19111259030736744
Fold 3 IBS: 0.20628848535091707
Fold 4 IBS: 0.19425413963426363
Fold 5 IBS: 0.19823239117702166
[I 2024-04-14 22:06:24,199] Trial 40 finished with value: 0.20665339607300254 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24366855047335662
Fold 2 IBS: 0.19098514791252663
Fold 3 IBS: 0.2055415154386566
Fold 4 IBS: 0.19406233329759895
Fold 5 IBS: 0.19789915497545424
[I 2024-04-14 22:06:24,715] Trial 41 finished with value: 0.2064313404195186 and parameters: {'l1_ratio': 0.10603433048484937}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24363720803377495
Fold 2 IBS: 0.19097052461342917
Fold 3 IBS: 0.20557110793254763
Fold 4 IBS: 0.19407133636125584
Fold 5 IBS: 0.19788443037903533
[I 2024-04-14 22:06:25,246] Trial 42 finished with value: 0.20642692146400857 and parameters: {'l1_ratio': 0.10020569221700752}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24374085078548657
Fold 2 IBS: 0.22778340642716716
Fold 3 IBS: 0.22880455786104034
Fold 4 IBS: 0.2378304856260858
Fold 5 IBS: 0.2260823215300034
[I 2024-04-14 22:06:25,608] Trial 43 finished with value: 0.23284832444595666 and parameters: {'l1_ratio': 0.04168452968922559}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24356901994399174
Fold 2 IBS: 0.19101124993788837
Fold 3 IBS: 0.20578825899042896
Fold 4 IBS: 0.19412354892838193
Fold 5 IBS: 0.1979826358693431
[I 2024-04-14 22:06:26,025] Trial 44 finished with value: 0.20649494273400681 and parameters: {'l1_ratio': 0.17961333377957792}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24361453898986898
Fold 2 IBS: 0.19097190669057712
Fold 3 IBS: 0.2055830920467237
Fold 4 IBS: 0.1940735163161875
Fold 5 IBS: 0.197899974212055
[I 2024-04-14 22:06:26,344] Trial 45 finished with value: 0.2064286056510825 and parameters: {'l1_ratio': 0.10979672150563659}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2434698871520127
Fold 2 IBS: 0.1910448483179674
Fold 3 IBS: 0.20589370711653548
Fold 4 IBS: 0.1941658546794573
Fold 5 IBS: 0.1980669941366439
[I 2024-04-14 22:06:26,690] Trial 46 finished with value: 0.20652825828052337 and parameters: {'l1_ratio': 0.24448489004615218}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24371486020397842
Fold 2 IBS: 0.22706833184453343
Fold 3 IBS: 0.22878303693814664
Fold 4 IBS: 0.23715387840883514
Fold 5 IBS: 0.19781349416197194
[I 2024-04-14 22:06:27,145] Trial 47 finished with value: 0.22690672031149312 and parameters: {'l1_ratio': 0.04968988578514158}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2432419484528097
Fold 2 IBS: 0.1911693631584673
Fold 3 IBS: 0.206613113111666
Fold 4 IBS: 0.19432936336260112
Fold 5 IBS: 0.19846961544208616
[I 2024-04-14 22:06:27,634] Trial 48 finished with value: 0.20676468070552603 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24362105540413065
Fold 2 IBS: 0.19100243084841143
Fold 3 IBS: 0.20564665754800662
Fold 4 IBS: 0.194111193463517
Fold 5 IBS: 0.19795697993514175
[I 2024-04-14 22:06:27,995] Trial 49 finished with value: 0.20646766343984152 and parameters: {'l1_ratio': 0.14676948111101923}. Best is trial 12 with value: 0.20640201895757088.

Fold 1 IBS: 0.24334390886691287
Fold 2 IBS: 0.19113075065475335
Fold 3 IBS: 0.20639867222499295
Fold 4 IBS: 0.19428515589467615
Fold 5 IBS: 0.1982849899059779
[I 2024-04-14 22:06:28,380] Trial 50 finished with value: 0.20668869550946267 and parameters: {'l1_ratio': 0.556147470734502}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436253663181637
Fold 2 IBS: 0.19096502589656006
Fold 3 IBS: 0.2055467515574163
Fold 4 IBS: 0.19406476572289086
Fold 5 IBS: 0.19788395464949432
[I 2024-04-14 22:06:28,878] Trial 51 finished with value: 0.20641717282890504 and parameters: {'l1_ratio': 0.09816171051292913}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436224995486653
Fold 2 IBS: 0.19096369692309786
Fold 3 IBS: 0.20554085835871463
Fold 4 IBS: 0.19406317611055732
Fold 5 IBS: 0.1978838412055684
[I 2024-04-14 22:06:29,403] Trial 52 finished with value: 0.2064148144293207 and parameters: {'l1_ratio': 0.09767894737350165}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24701260588140908
Fold 2 IBS: 0.23160916457264588
Fold 3 IBS: 0.22894569489843192
Fold 4 IBS: 0.24154697933785235
Fold 5 IBS: 0.22905360962602594
[I 2024-04-14 22:06:29,577] Trial 53 finished with value: 0.235633610863273 and parameters: {'l1_ratio': 0.0038107981929105667}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24369768145834778
Fold 2 IBS: 0.19096889148044813
Fold 3 IBS: 0.22873578605890355
Fold 4 IBS: 0.1940397152940616
Fold 5 IBS: 0.19785555435506255
[I 2024-04-14 22:06:30,166] Trial 54 finished with value: 0.21105952572936473 and parameters: {'l1_ratio': 0.0766220227537334}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24363104745786104
Fold 2 IBS: 0.19100711791221395
Fold 3 IBS: 0.20566924837093167
Fold 4 IBS: 0.19409316113124897
Fold 5 IBS: 0.1979574740133563
[I 2024-04-14 22:06:30,513] Trial 55 finished with value: 0.20647160977712237 and parameters: {'l1_ratio': 0.1496636657570243}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24527134850426952
Fold 2 IBS: 0.22834445539984705
Fold 3 IBS: 0.2288097549031259
Fold 4 IBS: 0.23836565055916764
Fold 5 IBS: 0.22651055354670718
[I 2024-04-14 22:06:30,676] Trial 56 finished with value: 0.23346035258262346 and parameters: {'l1_ratio': 0.035628177879366285}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24350279196727637
Fold 2 IBS: 0.19103800672682755
Fold 3 IBS: 0.2058483964381702
Fold 4 IBS: 0.19415634769179196
Fold 5 IBS: 0.19803593017779358
[I 2024-04-14 22:06:31,142] Trial 57 finished with value: 0.20651629460037194 and parameters: {'l1_ratio': 0.21897099299730738}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2434549308689679
Fold 2 IBS: 0.19106149783116685
Fold 3 IBS: 0.2059881889009445
Fold 4 IBS: 0.19418711974249553
Fold 5 IBS: 0.19810252458288638
[I 2024-04-14 22:06:31,975] Trial 58 finished with value: 0.20655885238529223 and parameters: {'l1_ratio': 0.2859532305825907}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24360097268856484
Fold 2 IBS: 0.19097867807715518
Fold 3 IBS: 0.20561958121245977
Fold 4 IBS: 0.19408221798284028
Fold 5 IBS: 0.19791754922055002
[I 2024-04-14 22:06:32,899] Trial 59 finished with value: 0.20643979983631403 and parameters: {'l1_ratio': 0.12271499039847353}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24355582186547217
Fold 2 IBS: 0.19100508883341824
Fold 3 IBS: 0.2057607514468488
Fold 4 IBS: 0.19411624869542293
Fold 5 IBS: 0.19798197195250603
[I 2024-04-14 22:06:33,586] Trial 60 finished with value: 0.20648397655873363 and parameters: {'l1_ratio': 0.17506453779750902}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24368702896666797
Fold 2 IBS: 0.1909729584250885
Fold 3 IBS: 0.20547161843979303
Fold 4 IBS: 0.19404543796703277
Fold 5 IBS: 0.19786864244474456
[I 2024-04-14 22:06:34,375] Trial 61 finished with value: 0.20640913724866533 and parameters: {'l1_ratio': 0.08497028745341434}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436986829261501
Fold 2 IBS: 0.19096935950528277
Fold 3 IBS: 0.22873563826904775
Fold 4 IBS: 0.19404032032584073
Fold 5 IBS: 0.197855592943384
[I 2024-04-14 22:06:34,785] Trial 62 finished with value: 0.2110599187939411 and parameters: {'l1_ratio': 0.0767583461344387}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24527992459218315
Fold 2 IBS: 0.2283608601195515
Fold 3 IBS: 0.22880974512354418
Fold 4 IBS: 0.23838135357470203
Fold 5 IBS: 0.22652311535100725
[I 2024-04-14 22:06:35,029] Trial 63 finished with value: 0.23347099975219762 and parameters: {'l1_ratio': 0.035453949085886734}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24363454504986462
Fold 2 IBS: 0.19096928676985755
Fold 3 IBS: 0.20556562874597495
Fold 4 IBS: 0.1940698581211325
Fold 5 IBS: 0.19788432241851034
[I 2024-04-14 22:06:35,485] Trial 64 finished with value: 0.206424728221068 and parameters: {'l1_ratio': 0.09973890142125685}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2432916689887429
Fold 2 IBS: 0.19115226763313006
Fold 3 IBS: 0.20649119407918234
Fold 4 IBS: 0.19430345747724087
Fold 5 IBS: 0.19840059509425317
[I 2024-04-14 22:06:35,848] Trial 65 finished with value: 0.20672783665450986 and parameters: {'l1_ratio': 0.6463081053454892}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24357342998973106
Fold 2 IBS: 0.1910013856899933
Fold 3 IBS: 0.20563352041184962
Fold 4 IBS: 0.1940848057916441
Fold 5 IBS: 0.19793634759228215
[I 2024-04-14 22:06:36,335] Trial 66 finished with value: 0.20644589789510004 and parameters: {'l1_ratio': 0.13434604320778154}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24354878632159588
Fold 2 IBS: 0.19102082454076255
Fold 3 IBS: 0.20584064667044297
Fold 4 IBS: 0.19413609437618287
Fold 5 IBS: 0.19800859708654692
[I 2024-04-14 22:06:36,805] Trial 67 finished with value: 0.20651098979910626 and parameters: {'l1_ratio': 0.20281557828451632}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24616370122993306
Fold 2 IBS: 0.23003285680446053
Fold 3 IBS: 0.2288473930178166
Fold 4 IBS: 0.2399974190491388
Fold 5 IBS: 0.22781518733320322
[I 2024-04-14 22:06:36,984] Trial 68 finished with value: 0.23457131148691043 and parameters: {'l1_ratio': 0.01849154012774587}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436577394305632
Fold 2 IBS: 0.19095931531849583
Fold 3 IBS: 0.22873171133626777
Fold 4 IBS: 0.19405709800144844
Fold 5 IBS: 0.1978675192546521
[I 2024-04-14 22:06:37,458] Trial 69 finished with value: 0.21105467666828548 and parameters: {'l1_ratio': 0.08072819111759641}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24360853918332878
Fold 2 IBS: 0.19101239552764884
Fold 3 IBS: 0.20570364015422266
Fold 4 IBS: 0.1941238690863047
Fold 5 IBS: 0.19798063677534325
[I 2024-04-14 22:06:37,877] Trial 70 finished with value: 0.20648581614536962 and parameters: {'l1_ratio': 0.16628697254523458}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2436601562737448
Fold 2 IBS: 0.1909931897801091
Fold 3 IBS: 0.20558676868238882
Fold 4 IBS: 0.19407341814412682
Fold 5 IBS: 0.19791687394708102
[I 2024-04-14 22:06:38,462] Trial 71 finished with value: 0.20644608136549011 and parameters: {'l1_ratio': 0.1193242692360745}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.2437031837786329
Fold 2 IBS: 0.22665197781079233
Fold 3 IBS: 0.22877181712761274
Fold 4 IBS: 0.23676286700307572
Fold 5 IBS: 0.19782228108541317
[I 2024-04-14 22:06:38,729] Trial 72 finished with value: 0.22674242536110537 and parameters: {'l1_ratio': 0.05450692292801165}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24366451365848363
Fold 2 IBS: 0.19097236906033585
Fold 3 IBS: 0.20547425674256922
Fold 4 IBS: 0.19404521675563668
Fold 5 IBS: 0.1978826039383504
[I 2024-04-14 22:06:39,324] Trial 73 finished with value: 0.20640779203107518 and parameters: {'l1_ratio': 0.09251924621858691}. Best is trial 12 with value: 0.20640201895757088.
Fold 1 IBS: 0.24366908050967223
Fold 2 IBS: 0.19096458793716775
Fold 3 IBS: 0.2054315697026132
Fold 4 IBS: 0.19403461447978324
Fold 5 IBS: 0.19786794433373758
[I 2024-04-14 22:06:39,790] Trial 74 finished with value: 0.2063935593925948 and parameters: {'l1_ratio': 0.08232138230466424}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24350130606192127

Fold 2 IBS: 0.19105845803079508
Fold 3 IBS: 0.2059598496156694
Fold 4 IBS: 0.19418181145185112
Fold 5 IBS: 0.1980688102664647
[I 2024-04-14 22:06:40,208] Trial 75 finished with value: 0.20655404708534028 and parameters: {'l1_ratio': 0.2610656085136891}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24354999743726324
Fold 2 IBS: 0.19102139129203694
Fold 3 IBS: 0.2058431805096221
Fold 4 IBS: 0.1941367640036499
Fold 5 IBS: 0.19800866175433174
[I 2024-04-14 22:06:40,614] Trial 76 finished with value: 0.2065119989993808 and parameters: {'l1_ratio': 0.20331332808738323}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24573621227936895
Fold 2 IBS: 0.22922850186128313
Fold 3 IBS: 0.22882001812587105
Fold 4 IBS: 0.23921619684147438
Fold 5 IBS: 0.2271907309066142
[I 2024-04-14 22:06:40,753] Trial 77 finished with value: 0.23403833200292232 and parameters: {'l1_ratio': 0.026460277308053073}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24358263618643597
Fold 2 IBS: 0.1909845079499787
Fold 3 IBS: 0.20565257052746333
Fold 4 IBS: 0.19408989810793204
Fold 5 IBS: 0.19793675609633418
[I 2024-04-14 22:06:41,207] Trial 78 finished with value: 0.20644927377362882 and parameters: {'l1_ratio': 0.1365860810424376}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24366454777246319
Fold 2 IBS: 0.19095346775833935
Fold 3 IBS: 0.22874084523709678
Fold 4 IBS: 0.19401973855356575
Fold 5 IBS: 0.1978446277481209
[I 2024-04-14 22:06:41,639] Trial 79 finished with value: 0.2110446454139172 and parameters: {'l1_ratio': 0.07236212705648226}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24721103885796936
Fold 2 IBS: 0.2319737306469353
Fold 3 IBS: 0.22897606346565677
Fold 4 IBS: 0.2419089907829589
Fold 5 IBS: 0.22934300467357369
[I 2024-04-14 22:06:41,803] Trial 80 finished with value: 0.2358825656854188 and parameters: {'l1_ratio': 0.0005801779489575665}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.243661428666619
Fold 2 IBS: 0.1909818157288455
Fold 3 IBS: 0.2055255425386822
Fold 4 IBS: 0.19405803804476815
Fold 5 IBS: 0.1978988487553171
[I 2024-04-14 22:06:42,161] Trial 81 finished with value: 0.20642513474684637 and parameters: {'l1_ratio': 0.10465292135806621}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24370991048193222
Fold 2 IBS: 0.22659912094334045
Fold 3 IBS: 0.22877046462896689
Fold 4 IBS: 0.23671338697130886
Fold 5 IBS: 0.19782250670521878
[I 2024-04-14 22:06:42,420] Trial 82 finished with value: 0.22672307794615346 and parameters: {'l1_ratio': 0.05512697650020583}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24367465935190605
Fold 2 IBS: 0.1909671865710763
Fold 3 IBS: 0.20544401302712953
Fold 4 IBS: 0.19403797697363512
Fold 5 IBS: 0.19786815801784535
[I 2024-04-14 22:06:42,827] Trial 83 finished with value: 0.2063983987883185 and parameters: {'l1_ratio': 0.0831276014028092}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.2435843970084453
Fold 2 IBS: 0.19100109656883443
Fold 3 IBS: 0.205734284077617
Fold 4 IBS: 0.1941104857769342
Fold 5 IBS: 0.19795894774751335
[I 2024-04-14 22:06:43,234] Trial 84 finished with value: 0.2064778422358689 and parameters: {'l1_ratio': 0.15863276499589563}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24369167079034476
Fold 2 IBS: 0.19097512910340786
Fold 3 IBS: 0.20548198872693962
Fold 4 IBS: 0.19404824124211204
Fold 5 IBS: 0.19786882811073148
[I 2024-04-14 22:06:43,622] Trial 85 finished with value: 0.20641317159470715 and parameters: {'l1_ratio': 0.08568252339456055}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24359796305880105
Fold 2 IBS: 0.19097728046450999
Fold 3 IBS: 0.2056133661914523
Fold 4 IBS: 0.19408055102512423
Fold 5 IBS: 0.19791741981496971
[I 2024-04-14 22:06:44,031] Trial 86 finished with value: 0.20643731611097146 and parameters: {'l1_ratio': 0.12205884471824033}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24369377787687257
Fold 2 IBS: 0.22672429388993992
Fold 3 IBS: 0.2287736940935862
Fold 4 IBS: 0.23683062178854974
Fold 5 IBS: 0.1978219669442161
[I 2024-04-14 22:06:44,329] Trial 87 finished with value: 0.2267688709186329 and parameters: {'l1_ratio': 0.05366174221037098}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24370009659165418
Fold 2 IBS: 0.19095585139973176
Fold 3 IBS: 0.20550082427242325
Fold 4 IBS: 0.19405333347446418
Fold 5 IBS: 0.19786917047037114
[I 2024-04-14 22:06:44,735] Trial 88 finished with value: 0.20641585524172892 and parameters: {'l1_ratio': 0.08700533554213949}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24576063678270385
Fold 2 IBS: 0.2292746716147722
Fold 3 IBS: 0.22882113940355475
Fold 4 IBS: 0.23926085349107876
Fold 5 IBS: 0.22722643200330953
[I 2024-04-14 22:06:44,883] Trial 89 finished with value: 0.23406874665908378 and parameters: {'l1_ratio': 0.025993531489116525}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24356734350421652
Fold 2 IBS: 0.19101046633736546
Fold 3 IBS: 0.2057847634459891
Fold 4 IBS: 0.19412262116302306
Fold 5 IBS: 0.1979825507531262
[I 2024-04-14 22:06:45,283] Trial 90 finished with value: 0.20649354904074407 and parameters: {'l1_ratio': 0.17902287186562998}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.2436362211139532
Fold 2 IBS: 0.19099511579669182
Fold 3 IBS: 0.20560337147297875
Fold 4 IBS: 0.1940767482298936
Fold 5 IBS: 0.197935714553831
[I 2024-04-14 22:06:45,671] Trial 91 finished with value: 0.20644943423346968 and parameters: {'l1_ratio': 0.13093973855210014}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24366274968057805
Fold 2 IBS: 0.1909715465573348
Fold 3 IBS: 0.20547031371273228
Fold 4 IBS: 0.19404415382924553
Fold 5 IBS: 0.1978825332789216
[I 2024-04-14 22:06:46,181] Trial 92 finished with value: 0.20640625941176247 and parameters: {'l1_ratio': 0.09222986567277357}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.2436992651997043
Fold 2 IBS: 0.22668233302010238
Fold 3 IBS: 0.22877260127335025
Fold 4 IBS: 0.2367912993296262
Fold 5 IBS: 0.19782214577931287
[I 2024-04-14 22:06:46,506] Trial 93 finished with value: 0.22675352892041917 and parameters: {'l1_ratio': 0.05415171070907786}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.2432864085766862
Fold 2 IBS: 0.19118305408902225
Fold 3 IBS: 0.20670725392833628
Fold 4 IBS: 0.1943478419563717
Fold 5 IBS: 0.1985056278569538
[I 2024-04-14 22:06:46,791] Trial 94 finished with value: 0.20680603728147404 and parameters: {'l1_ratio': 0.9094578869039874}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24367497721820877
Fold 2 IBS: 0.19096733473206903
Fold 3 IBS: 0.20544472220721174
Fold 4 IBS: 0.19403816862289697
Fold 5 IBS: 0.1978681702839075
[I 2024-04-14 22:06:47,179] Trial 95 finished with value: 0.20639867461285882 and parameters: {'l1_ratio': 0.08317399740204975}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.2435696337556911
Fold 2 IBS: 0.190994216129013
Fold 3 IBS: 0.20570361508363327
Fold 4 IBS: 0.19410231488201066
Fold 5 IBS: 0.19795824326997016
[I 2024-04-14 22:06:47,535] Trial 96 finished with value: 0.20646560462406366 and parameters: {'l1_ratio': 0.15427964147927195}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24599381780910748
Fold 2 IBS: 0.22971413631027965
Fold 3 IBS: 0.22883458576081878
Fold 4 IBS: 0.23968705377224883
Fold 5 IBS: 0.2275671235400198
[I 2024-04-14 22:06:47,674] Trial 97 finished with value: 0.2343593434384949 and parameters: {'l1_ratio': 0.021608322548745132}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24336563321194277
Fold 2 IBS: 0.19110660782495442
Fold 3 IBS: 0.2062589661508162
Fold 4 IBS: 0.19425665469476208
Fold 5 IBS: 0.1981884447521538
[I 2024-04-14 22:06:47,973] Trial 98 finished with value: 0.20663526132692586 and parameters: {'l1_ratio': 0.4503672610451996}. Best is trial 74 with value: 0.2063935593925948.
Fold 1 IBS: 0.24372315592596658
Fold 2 IBS: 0.1909487087793225
Fold 3 IBS: 0.2287424660726328
Fold 4 IBS: 0.19404405781996234
Fold 5 IBS: 0.19784425758989488
[I 2024-04-14 22:06:48,391] Trial 99 finished with value: 0.2110605292375558 and parameters: {'l1_ratio': 0.07113281690995393}. Best is trial 74 with value: 0.2063935593925948.


* Best trial for IBS:
 FrozenTrial(number=74, state=TrialState.COMPLETE, values=[0.2063935593925948], datetime_start=datetime.datetime(2024, 4, 14, 22, 6, 39, 355623), datetime_complete=datetime.datetime(2024, 4, 14, 22, 6, 39, 790335), params={'l1_ratio': 0.08232138230466424}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=74, value=None)


* Best Score for IBS:
 0.2063935593925948

In [119]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [120]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.691
train_ibs:  0.206

#### Test

In [121]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [122]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.533

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.08232138230466424)

test_ibs:  0.288

In [123]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [124]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:06:48,670] A new study created in memory with name: no-name-b8a79389-2ab4-436b-a25c-d59e3fb90ba9

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 22:06:52,215] Trial 0 finished with value: 0.6977075894586338 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6977075894586338.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:06:55,565] Trial 1 finished with value: 0.7128781680014569 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:06:58,017] Trial 2 finished with value: 0.7078951516958202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:06:58,742] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:06:59,673] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:07:03,249] Trial 5 finished with value: 0.7140624838621864 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:07:06,798] Trial 6 finished with value: 0.7101780788884746 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:07:08,301] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-14 22:07:13,242] Trial 8 finished with value: 0.5257510729613734 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:07:15,881] Trial 9 finished with value: 0.7039036721293016 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:07:16,220] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:07:17,742] Trial 11 finished with value: 0.7271736918163124 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:07:18,931] Trial 12 finished with value: 0.7217535824914708 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8064195611120726, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:07:20,211] Trial 13 finished with value: 0.7230396596037402 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.8350722272141606, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13041468920781069, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6845493562231759
[I 2024-04-14 22:07:20,944] Trial 14 finished with value: 0.7401429490839831 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9806297626114981, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18121651510792322, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383

Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:07:21,762] Trial 15 finished with value: 0.7359974816455777 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9916077098875709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2050785814281292, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7060085836909872
[I 2024-04-14 22:07:21,941] Trial 16 finished with value: 0.7424649927687818 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.9632036286697128, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19855793167729388, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:07:22,113] Trial 17 finished with value: 0.7187276534642637 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.9920927723346319, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6115879828326181
[I 2024-04-14 22:07:22,335] Trial 18 finished with value: 0.6821795609651563 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.4733682176858589, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18440565612965779, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6394849785407726
[I 2024-04-14 22:07:22,808] Trial 19 finished with value: 0.6909365199154465 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.8996903695627709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3933604732001355, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6974248927038627
[I 2024-04-14 22:07:23,772] Trial 20 finished with value: 0.731849318014498 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.7099567102313042, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2573277491349737, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:07:24,535] Trial 21 finished with value: 0.7351391125468653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9578709493710758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19090506657387685, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:07:25,015] Trial 22 finished with value: 0.7341648725242437 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.9967334344648481, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22971555033034935, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:07:25,782] Trial 23 finished with value: 0.7461784934529897 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.8688645990573083, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1729801266340484, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:07:26,918] Trial 24 finished with value: 0.7410139181199299 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.866350879679609, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07068946136637579, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 22:07:27,932] Trial 25 finished with value: 0.7568542957468967 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.8561321352006472, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07248837432829829, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:07:29,266] Trial 26 finished with value: 0.7469421068076121 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.766734838708136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07999208951911986, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 22:07:30,400] Trial 27 finished with value: 0.7510925047188961 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.7750769539334444, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06326441457712315, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 22:07:32,479] Trial 28 finished with value: 0.7651955962327717 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.6847169156044919, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003364807635412012, 'warm_start': True}. Best is trial 28 with value: 0.7651955962327717.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 22:07:34,682] Trial 29 finished with value: 0.7751733627229969 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.04113891562651206, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 22:07:36,783] Trial 30 finished with value: 0.7736629125252518 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.6833587310905035, 'max_features': None, 'min_weight_fraction_leaf': 0.008532800179007469, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 22:07:39,052] Trial 31 finished with value: 0.7735002862697369 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.6547593902381754, 'max_features': None, 'min_weight_fraction_leaf': 0.01653304213676029, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 22:07:41,454] Trial 32 finished with value: 0.7726671170454932 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.7011070731694715, 'max_features': None, 'min_weight_fraction_leaf': 0.002655419277963856, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-14 22:07:43,314] Trial 33 finished with value: 0.761951377352432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.4871505413082745, 'max_features': None, 'min_weight_fraction_leaf': 0.0037092008636243484, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 22:07:45,838] Trial 34 finished with value: 0.7772994105576999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5424853541641252, 'max_features': None, 'min_weight_fraction_leaf': 0.04005993867513943, 'warm_start': True}. Best is trial 34 with value: 0.7772994105576999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 22:07:48,594] Trial 35 finished with value: 0.7939453846462785 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5281329979576042, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.7939453846462785.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 22:07:51,201] Trial 36 finished with value: 0.7988094200063037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5475428261493075, 'max_features': None, 'min_weight_fraction_leaf': 0.04248766950155104, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8081395348837209
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:07:53,552] Trial 37 finished with value: 0.7438212214010235 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.537628436907505, 'max_features': None, 'min_weight_fraction_leaf': 0.13505191950972878, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 22:07:55,927] Trial 38 finished with value: 0.7773251612620597 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4079124058970714, 'max_features': None, 'min_weight_fraction_leaf': 0.043050318879278446, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:07:58,434] Trial 39 finished with value: 0.734846885715039 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': None, 'min_weight_fraction_leaf': 0.10012332890216755, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7381974248927039
[I 2024-04-14 22:08:00,741] Trial 40 finished with value: 0.7649536724571295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.38596283150687494, 'max_features': None, 'min_weight_fraction_leaf': 0.04061455540701541, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 22:08:03,239] Trial 41 finished with value: 0.7941370621081079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.5853104884542844, 'max_features': None, 'min_weight_fraction_leaf': 0.045291071200096567, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:08:05,552] Trial 42 finished with value: 0.736998260411046 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 466, 'oob_score': True, 'max_samples': 0.5547327087340422, 'max_features': None, 'min_weight_fraction_leaf': 0.15119679094835453, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 22:08:07,871] Trial 43 finished with value: 0.7838881672008012 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.43155969103520636, 'max_features': None, 'min_weight_fraction_leaf': 0.043472744875657617, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:08:09,926] Trial 44 finished with value: 0.7399894649828315 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.4005082288778946, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:08:11,140] Trial 45 finished with value: 0.7241222823816911 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.25182885979889597, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08391169894605255, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:08:18,343] Trial 46 finished with value: 0.7058457110259935 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.43126650753033136, 'max_features': None, 'min_weight_fraction_leaf': 0.05341940290949464, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 22:08:19,572] Trial 47 finished with value: 0.761821383227146 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.30342154143659733, 'max_features': None, 'min_weight_fraction_leaf': 0.03559822522548907, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:08:38,123] Trial 48 finished with value: 0.7117273483913299 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 435, 'oob_score': True, 'max_samples': 0.5993264662444304, 'max_features': None, 'min_weight_fraction_leaf': 0.1243065372654003, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:08:42,976] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.5188442477983979, 'max_features': None, 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:08:45,027] Trial 50 finished with value: 0.737899316580976 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.5847268231512849, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15227204260709018, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 22:08:49,607] Trial 51 finished with value: 0.7814971781238983 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.43199709338607994, 'max_features': None, 'min_weight_fraction_leaf': 0.03149759470389267, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 22:08:53,283] Trial 52 finished with value: 0.7567762597419098 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4387556889483383, 'max_features': None, 'min_weight_fraction_leaf': 0.09297907262518232, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 22:08:57,757] Trial 53 finished with value: 0.7986572561005724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.4978232271491865, 'max_features': None, 'min_weight_fraction_leaf': 0.033781036150152696, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 22:09:02,394] Trial 54 finished with value: 0.8175044273559141 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.4961608781156207, 'max_features': None, 'min_weight_fraction_leaf': 0.025003317155411986, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.759656652360515
[I 2024-04-14 22:09:05,374] Trial 55 finished with value: 0.7750834494179615 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.5021698171984055, 'max_features': None, 'min_weight_fraction_leaf': 0.06062440846922696, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:09:11,467] Trial 56 finished with value: 0.692159003960772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.6431467441559697, 'max_features': None, 'min_weight_fraction_leaf': 0.021762770810368127, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 22:09:14,650] Trial 57 finished with value: 0.7775457629433687 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.5757175357123006, 'max_features': None, 'min_weight_fraction_leaf': 0.05830794943324037, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:09:16,768] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.4648579376135416, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.30295661673067836, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:09:17,687] Trial 59 finished with value: 0.742832764389526 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.34319505493069397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08248014261229168, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:09:27,128] Trial 60 finished with value: 0.7094998068077641 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.6211328199713557, 'max_features': None, 'min_weight_fraction_leaf': 0.11070844936873359, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 22:09:33,980] Trial 61 finished with value: 0.8036986552407976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.5153677562911374, 'max_features': None, 'min_weight_fraction_leaf': 0.031485629345332306, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 22:09:38,123] Trial 62 finished with value: 0.8182757698225179 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.5112289023564809, 'max_features': None, 'min_weight_fraction_leaf': 0.02095528969051655, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 22:09:41,448] Trial 63 finished with value: 0.8111521115785895 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.5100900270084606, 'max_features': None, 'min_weight_fraction_leaf': 0.018150109857069722, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7510729613733905
[I 2024-04-14 22:09:44,239] Trial 64 finished with value: 0.7700709580629541 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.4955086388573719, 'max_features': None, 'min_weight_fraction_leaf': 0.06782578020859786, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 22:09:47,116] Trial 65 finished with value: 0.8185942843287751 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.572806842914682, 'max_features': None, 'min_weight_fraction_leaf': 0.02226915354245074, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 22:09:49,439] Trial 66 finished with value: 0.8160847545835782 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.5576081908424206, 'max_features': None, 'min_weight_fraction_leaf': 0.016475143309745643, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 22:09:53,231] Trial 67 finished with value: 0.8101126972372172 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.561957978855049, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.018288170265703986, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 22:09:55,975] Trial 68 finished with value: 0.8183234527679148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.6097336917403036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02099611885947379, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8454935622317596
[I 2024-04-14 22:09:58,167] Trial 69 finished with value: 0.8272146463529724 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7318335045229435, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017419775688352082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 22:10:00,281] Trial 70 finished with value: 0.8158063208975717 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.6243013523451256, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020464714362005143, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 22:10:02,520] Trial 71 finished with value: 0.824114421989065 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.7330924737377311, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016575501718897302, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 22:10:04,650] Trial 72 finished with value: 0.8125646918339378 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7326351452640015, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0027592484745489945, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 22:10:06,280] Trial 73 finished with value: 0.8078669641918867 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 262, 'oob_score': True, 'max_samples': 0.6560932996857387, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01505215827140816, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 22:10:09,125] Trial 74 finished with value: 0.8229478737470439 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.8040957518239317, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024607026709667742, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6931330472103004
[I 2024-04-14 22:10:11,211] Trial 75 finished with value: 0.7297534394801531 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.8244077376700942, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2738762867283342, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 22:10:13,138] Trial 76 finished with value: 0.8005224502929792 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.7779027631332152, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06198954175038082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 22:10:14,827] Trial 77 finished with value: 0.8054911364827252 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.7444363178817063, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00391494572036042, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 22:10:17,562] Trial 78 finished with value: 0.7766506135263602 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.7964582770234238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08072526041027032, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 22:10:18,414] Trial 79 finished with value: 0.7952779202339323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.618087421106259, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02724887288178213, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6716738197424893
[I 2024-04-14 22:10:22,102] Trial 80 finished with value: 0.7109603094858263 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.6608918473113886, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22754786457763954, 'warm_start': False}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 22:10:24,064] Trial 81 finished with value: 0.823191212472951 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 334, 'oob_score': True, 'max_samples': 0.7181496469643299, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01833632174034757, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 22:10:26,484] Trial 82 finished with value: 0.8055458278408263 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.718648090454236, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05194443679311898, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 22:10:28,364] Trial 83 finished with value: 0.812684350596275 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.7502215626294254, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011526440379393736, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 22:10:30,786] Trial 84 finished with value: 0.8232844098456795 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.8395867498100796, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024617503790133055, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 22:10:33,504] Trial 85 finished with value: 0.7921991713994829 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 368, 'oob_score': True, 'max_samples': 0.8857836580094625, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07264997820097252, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 22:10:36,115] Trial 86 finished with value: 0.8224086969713147 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9236490757653891, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05091910924778117, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:10:36,466] Trial 87 finished with value: 0.7444219877257969 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.8360547528312109, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05159081964644253, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 22:10:38,578] Trial 88 finished with value: 0.8299957447925681 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6373390557939914
[I 2024-04-14 22:10:40,804] Trial 89 finished with value: 0.6984552187416074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9606865260369674, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42980933716176023, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 22:10:43,076] Trial 90 finished with value: 0.8168638261621636 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.8970982407350513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0033122441195345426, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 22:10:45,117] Trial 91 finished with value: 0.8288039966760785 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.8500705105869577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02769924772148816, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 22:10:47,289] Trial 92 finished with value: 0.828952436236799 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.9318910170313084, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03466207519046283, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 22:10:48,986] Trial 93 finished with value: 0.8246721711870638 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.9237402520498113, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051627897348460114, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 22:10:50,574] Trial 94 finished with value: 0.7774842065936604 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.9315755472196319, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09044268069913194, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 22:10:52,515] Trial 95 finished with value: 0.8149658464044028 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.9428489419934195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05519942461860093, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:10:53,838] Trial 96 finished with value: 0.7343217686472692 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 18, 'n_estimators': 255, 'oob_score': True, 'max_samples': 0.8550701905177472, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07090475670535565, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7553648068669528
[I 2024-04-14 22:10:54,761] Trial 97 finished with value: 0.7709719977986227 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.9118193987076412, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.035787567288930885, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:10:56,217] Trial 98 finished with value: 0.7298807893419987 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9222109032849816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04727690829808437, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415

[I 2024-04-14 22:11:00,908] A new study created in memory with name: no-name-a4ef00c8-66c7-4dc0-a020-d8b541bb6f0b

Fold 5 C-index: 0.6759656652360515
[I 2024-04-14 22:11:00,891] Trial 99 finished with value: 0.7070161831399606 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.9759793763474963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3521412865651261, 'warm_start': False}. Best is trial 88 with value: 0.8299957447925681.


* Best trial for C-index:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.8299957447925681], datetime_start=datetime.datetime(2024, 4, 14, 22, 10, 36, 476242), datetime_complete=datetime.datetime(2024, 4, 14, 22, 10, 38, 577695), params={'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=88, value=None)


* Best Score for C-index:
 0.8299957447925681

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22407713995563355
Fold 2 IBS: 0.17470488039835566
Fold 3 IBS: 0.2398383923527903
Fold 4 IBS: 0.20906561324773706
Fold 5 IBS: 0.2195728796491891
[I 2024-04-14 22:11:04,063] Trial 0 finished with value: 0.21345178112074117 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21345178112074117.
Fold 1 IBS: 0.21616660020333003
Fold 2 IBS: 0.17486525786616586
Fold 3 IBS: 0.2107106205384323
Fold 4 IBS: 0.20216950628891073
Fold 5 IBS: 0.21532298657498944
[I 2024-04-14 22:11:04,838] Trial 1 finished with value: 0.20384699429436565 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-14 22:11:05,387] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-14 22:11:07,634] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-14 22:11:09,304] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24936759596080646
Fold 2 IBS: 0.17264271046131205
Fold 3 IBS: 0.20421070451417014
Fold 4 IBS: 0.21666312222005965
Fold 5 IBS: 0.21221582754312004
[I 2024-04-14 22:11:14,491] Trial 5 finished with value: 0.2110199921398937 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21621830894948232
Fold 2 IBS: 0.18912437295998735
Fold 3 IBS: 0.25661481391845226
Fold 4 IBS: 0.20519890764061255
Fold 5 IBS: 0.21737176566006436
[I 2024-04-14 22:11:17,055] Trial 6 finished with value: 0.21690563382571976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.239725565259837
Fold 2 IBS: 0.22117477833066543
Fold 3 IBS: 0.22403481418923998
Fold 4 IBS: 0.2325927375141085
Fold 5 IBS: 0.22473498221278954
[I 2024-04-14 22:11:20,859] Trial 7 finished with value: 0.22845257550132808 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-14 22:11:26,599] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22659514067603376
Fold 2 IBS: 0.17851765630325647
Fold 3 IBS: 0.2013246121030424
Fold 4 IBS: 0.20963921105379285
Fold 5 IBS: 0.2203202485023523
[I 2024-04-14 22:11:27,913] Trial 9 finished with value: 0.2072793737276956 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-14 22:11:29,671] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2540107203940081
Fold 2 IBS: 0.19018193572283806
Fold 3 IBS: 0.2693108522338297
Fold 4 IBS: 0.2204494801684996
Fold 5 IBS: 0.22801293569526146
[I 2024-04-14 22:11:29,855] Trial 11 finished with value: 0.23239318484288743 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9899815471614337, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23986882649245242
Fold 2 IBS: 0.17667107107700725
Fold 3 IBS: 0.19675890006825608
Fold 4 IBS: 0.21136980755566645
Fold 5 IBS: 0.21659638264865502
[I 2024-04-14 22:11:31,247] Trial 12 finished with value: 0.20825299756840746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.838341657174724, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007007532608717559}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22478082430068405
Fold 2 IBS: 0.17185450852530715
Fold 3 IBS: 0.21027987039395774
Fold 4 IBS: 0.20018219852324562
Fold 5 IBS: 0.21753825326760137
[I 2024-04-14 22:11:32,973] Trial 13 finished with value: 0.2049271310021592 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.964999799603621, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2691953450690723}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21998167437826233
Fold 2 IBS: 0.18978207675252776
Fold 3 IBS: 0.2156881327568739
Fold 4 IBS: 0.20498945225014242
Fold 5 IBS: 0.2158332545660207
[I 2024-04-14 22:11:33,960] Trial 14 finished with value: 0.2092549181407654 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7347591488544951, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2812321272168262}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24379041704605284
Fold 2 IBS: 0.16804912162483507
Fold 3 IBS: 0.2051845606137616
Fold 4 IBS: 0.20906885042686352
Fold 5 IBS: 0.2130970650630231
[I 2024-04-14 22:11:37,001] Trial 15 finished with value: 0.20783800295490723 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9966433181385008, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13541305845514623}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.24681956605569497
Fold 2 IBS: 0.23227093172764388
Fold 3 IBS: 0.22941903729651647
Fold 4 IBS: 0.24121738904572626
Fold 5 IBS: 0.2302321253386658
[I 2024-04-14 22:11:40,199] Trial 16 finished with value: 0.2359918098928495 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 162, 'oob_score': False, 'max_samples': 0.32587405036023415, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3357318242102959}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2231111330848275
Fold 2 IBS: 0.17656419065238982
Fold 3 IBS: 0.20901589415087424
Fold 4 IBS: 0.20307733734686217
Fold 5 IBS: 0.21545535438507316
[I 2024-04-14 22:11:47,116] Trial 17 finished with value: 0.20544478192400537 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8324456438302156, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2527008941020278}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23532815608885377
Fold 2 IBS: 0.1837655560742492
Fold 3 IBS: 0.20262687562645237
Fold 4 IBS: 0.2122206984989701
Fold 5 IBS: 0.2166747901565821
[I 2024-04-14 22:11:47,905] Trial 18 finished with value: 0.21012321528902148 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.6751019433313558, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11276726622420546}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22863054693293589
Fold 2 IBS: 0.1963315773237213
Fold 3 IBS: 0.21471249390143013
Fold 4 IBS: 0.219881142418457
Fold 5 IBS: 0.22152453289806817
[I 2024-04-14 22:11:48,158] Trial 19 finished with value: 0.21621605869492252 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.756071359635432, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32595449578288455}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22537941330506062
Fold 2 IBS: 0.19227308793145745
Fold 3 IBS: 0.21265991721222577
Fold 4 IBS: 0.20917597176350836
Fold 5 IBS: 0.21687868662201695
[I 2024-04-14 22:11:49,342] Trial 20 finished with value: 0.21127341536685385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.6036734235439312, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23857721033918533}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22324770605725813
Fold 2 IBS: 0.18253846781709399
Fold 3 IBS: 0.2045169037430424
Fold 4 IBS: 0.20783876653003266
Fold 5 IBS: 0.2175938501921847
[I 2024-04-14 22:11:54,137] Trial 21 finished with value: 0.20714713886792238 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.8230570050888841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2722629100041059}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24383129660582778
Fold 2 IBS: 0.16931429481145502
Fold 3 IBS: 0.20516950235518827
Fold 4 IBS: 0.20489042671888189
Fold 5 IBS: 0.21168593869445076
[I 2024-04-14 22:11:58,856] Trial 22 finished with value: 0.20697829183716077 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.9080266581136552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1738640799325239}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22798058234299892
Fold 2 IBS: 0.17066187178067507
Fold 3 IBS: 0.20762316176929713
Fold 4 IBS: 0.20163711855316047
Fold 5 IBS: 0.21357666387653937
[I 2024-04-14 22:12:02,367] Trial 23 finished with value: 0.20429587966453416 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.918144892067728, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22593418563490295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2333417951219333
Fold 2 IBS: 0.1700982573355749
Fold 3 IBS: 0.20661966502631599
Fold 4 IBS: 0.20215860951935866
Fold 5 IBS: 0.21369121522055837
[I 2024-04-14 22:12:05,567] Trial 24 finished with value: 0.20518190844474823 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.9261452409044857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2150416825146331}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2302095064014022
Fold 2 IBS: 0.20489193018995322
Fold 3 IBS: 0.22229468418463336
Fold 4 IBS: 0.22315856362376232
Fold 5 IBS: 0.22270247922464476
[I 2024-04-14 22:12:08,383] Trial 25 finished with value: 0.22065143272487914 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7754756321225551, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37858736351418476}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622588582203958
Fold 2 IBS: 0.23225616799196488
Fold 3 IBS: 0.22961130014021525
Fold 4 IBS: 0.24150610351006122
Fold 5 IBS: 0.23015340332834447
[I 2024-04-14 22:12:13,262] Trial 26 finished with value: 0.23595057215852505 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 410, 'oob_score': True, 'max_samples': 0.44732517583857423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30573135880353774}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24371312366354173
Fold 2 IBS: 0.17009470168949176
Fold 3 IBS: 0.20387614537935278
Fold 4 IBS: 0.2063297018706307
Fold 5 IBS: 0.21225767577269047
[I 2024-04-14 22:12:16,450] Trial 27 finished with value: 0.20725426967514146 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.9264498293472653, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16408374861729386}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24230033744905524
Fold 2 IBS: 0.1700083907734053
Fold 3 IBS: 0.20307970499577657
Fold 4 IBS: 0.21056222306350966
Fold 5 IBS: 0.21225464745768113
[I 2024-04-14 22:12:18,734] Trial 28 finished with value: 0.20764106074788558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.6539680943502474, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11167707604899824}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24611993726989195
Fold 2 IBS: 0.23218890990534718
Fold 3 IBS: 0.23048044870725193
Fold 4 IBS: 0.2410683146218637
Fold 5 IBS: 0.2299160122305334
[I 2024-04-14 22:12:22,370] Trial 29 finished with value: 0.23595472454697766 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.11354273074199811, 'max_features': None, 'min_weight_fraction_leaf': 0.23506901120045084}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22660818914056846
Fold 2 IBS: 0.17199394890259848
Fold 3 IBS: 0.20974235645980502
Fold 4 IBS: 0.20527990803227994
Fold 5 IBS: 0.2142164886689667
[I 2024-04-14 22:12:23,939] Trial 30 finished with value: 0.2055681782408437 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 164, 'oob_score': False, 'max_samples': 0.7841568813969919, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19739729582328963}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23708578217070322
Fold 2 IBS: 0.17051603032060797
Fold 3 IBS: 0.2048697308529193
Fold 4 IBS: 0.20307497656561538
Fold 5 IBS: 0.21255249060044212
[I 2024-04-14 22:12:27,563] Trial 31 finished with value: 0.20561980210205758 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 339, 'oob_score': False, 'max_samples': 0.9431792460514251, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20474531091370285}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.22612682993385486
Fold 2 IBS: 0.17223298934748948
Fold 3 IBS: 0.20782358499736456
Fold 4 IBS: 0.20181112716562463
Fold 5 IBS: 0.21350833459590543
[I 2024-04-14 22:12:30,516] Trial 32 finished with value: 0.2043005732080478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.8753375341925101, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2230974552568295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22177687649658975
Fold 2 IBS: 0.17630377861515312
Fold 3 IBS: 0.2122309287307206
Fold 4 IBS: 0.2017574245411477
Fold 5 IBS: 0.21470545803951144
[I 2024-04-14 22:12:35,348] Trial 33 finished with value: 0.20535489328462447 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.8780403780133842, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26554839348030423}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2347950025150411
Fold 2 IBS: 0.16799406158735225
Fold 3 IBS: 0.2119268936202999
Fold 4 IBS: 0.1995017747896286
Fold 5 IBS: 0.21645738910312
[I 2024-04-14 22:12:37,285] Trial 34 finished with value: 0.2061350243230884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.9713620300267395, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22449252311835874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2184171866823885
Fold 2 IBS: 0.18340292802030164
Fold 3 IBS: 0.24622741065146023
Fold 4 IBS: 0.21030733491515133
Fold 5 IBS: 0.218874594617978
[I 2024-04-14 22:12:40,090] Trial 35 finished with value: 0.21544589097745592 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.8006724007383993, 'max_features': None, 'min_weight_fraction_leaf': 0.2991859225334826}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24658618602469104
Fold 2 IBS: 0.2321884009769192
Fold 3 IBS: 0.2295721257429426
Fold 4 IBS: 0.24149932745394134
Fold 5 IBS: 0.23037083343869663
[I 2024-04-14 22:12:44,400] Trial 36 finished with value: 0.23604337472743814 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.7142345385665702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24597601805501332
Fold 2 IBS: 0.16679544014249023
Fold 3 IBS: 0.2291560830967934
Fold 4 IBS: 0.21774129632473188
Fold 5 IBS: 0.21808816775530818
[I 2024-04-14 22:12:50,303] Trial 37 finished with value: 0.21555140107486742 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.8893387526179963, 'max_features': None, 'min_weight_fraction_leaf': 0.05558599763353947}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22361789070615487
Fold 2 IBS: 0.17833589878764333
Fold 3 IBS: 0.20797628674399748
Fold 4 IBS: 0.20706581092390064
Fold 5 IBS: 0.21475624911298768
[I 2024-04-14 22:12:56,231] Trial 38 finished with value: 0.2063504272549368 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.48823423037203917, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10676050487618188}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2465964694944807
Fold 2 IBS: 0.23221073187531344
Fold 3 IBS: 0.22950988130319463
Fold 4 IBS: 0.241408499161141
Fold 5 IBS: 0.23022625655373033
[I 2024-04-14 22:12:59,366] Trial 39 finished with value: 0.235990367677572 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.5771239750792474, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3646319374122424}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21647863712170887
Fold 2 IBS: 0.17199966700669284
Fold 3 IBS: 0.19869719848871478
Fold 4 IBS: 0.20796789999763218
Fold 5 IBS: 0.21625226939504177
[I 2024-04-14 22:12:59,836] Trial 40 finished with value: 0.2022791344019581 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.7017810474930685, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15131446570826318}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22134427216375058
Fold 2 IBS: 0.1760712729646329
Fold 3 IBS: 0.19474566426704223
Fold 4 IBS: 0.21163414366897387
Fold 5 IBS: 0.21799528858603973
[I 2024-04-14 22:13:00,416] Trial 41 finished with value: 0.20435812833008785 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6851330046079013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1415472492884433}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21730762926082742
Fold 2 IBS: 0.17880052942015828
Fold 3 IBS: 0.19466820609343688
Fold 4 IBS: 0.20919417870986243
Fold 5 IBS: 0.2175415352637051
[I 2024-04-14 22:13:00,975] Trial 42 finished with value: 0.20350241574959801 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.6932739851311275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14781080589948162}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2266914017789978
Fold 2 IBS: 0.18902598179814228
Fold 3 IBS: 0.1886797492652457
Fold 4 IBS: 0.21746952054591362
Fold 5 IBS: 0.21485690053973838
[I 2024-04-14 22:13:01,436] Trial 43 finished with value: 0.20734471078560754 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 26, 'oob_score': False, 'max_samples': 0.6230606164996372, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17300117076396285}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2263300301352394
Fold 2 IBS: 0.17228759968501195
Fold 3 IBS: 0.20727538565975506
Fold 4 IBS: 0.20619156167481315
Fold 5 IBS: 0.2151350980475268
[I 2024-04-14 22:13:02,276] Trial 44 finished with value: 0.20544393504046926 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.5383399306130238, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07137280133151601}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2195259426238762
Fold 2 IBS: 0.17176930604867915
Fold 3 IBS: 0.21264489605286027
Fold 4 IBS: 0.2026960468857599
Fold 5 IBS: 0.2155061220972602
[I 2024-04-14 22:13:03,168] Trial 45 finished with value: 0.20442846274168716 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7211266599729008, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08955966829076284}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.24664109906894663
Fold 2 IBS: 0.23211151536965932
Fold 3 IBS: 0.22921725039634813
Fold 4 IBS: 0.24155332248199884
Fold 5 IBS: 0.2300252715829934
[I 2024-04-14 22:13:04,691] Trial 46 finished with value: 0.23590969177998927 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.4955610125060993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22677458805979425
Fold 2 IBS: 0.18128534484285147
Fold 3 IBS: 0.20359451039074664
Fold 4 IBS: 0.21860313764199735
Fold 5 IBS: 0.21528256346964708
[I 2024-04-14 22:13:04,992] Trial 47 finished with value: 0.20910802888100735 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.6381469780315093, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15711696604627562}. Best is trial 40 with value: 0.2022791344019581.

Fold 1 IBS: 0.23790435513187447
Fold 2 IBS: 0.16917310562036944
Fold 3 IBS: 0.2032724536335342
Fold 4 IBS: 0.20275263571784216
Fold 5 IBS: 0.21198800508925086
[I 2024-04-14 22:13:08,203] Trial 48 finished with value: 0.20501811103857426 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.862646612475437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18882619674434536}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21643739431200149
Fold 2 IBS: 0.18002210069568697
Fold 3 IBS: 0.20963559196115233
Fold 4 IBS: 0.20201711337877098
Fold 5 IBS: 0.21711926927169345
[I 2024-04-14 22:13:08,991] Trial 49 finished with value: 0.20504629392386103 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.712240935894755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03279359667752256}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21970666197039673
Fold 2 IBS: 0.17845771406023855
Fold 3 IBS: 0.20885143473324186
Fold 4 IBS: 0.20319913155933902
Fold 5 IBS: 0.2153595741585475
[I 2024-04-14 22:13:11,342] Trial 50 finished with value: 0.2051149032963527 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.581277730850803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13970814386185937}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21850000381456347
Fold 2 IBS: 0.17736923091725895
Fold 3 IBS: 0.20498374840747066
Fold 4 IBS: 0.2021359588037073
Fold 5 IBS: 0.21987202711845588
[I 2024-04-14 22:13:11,748] Trial 51 finished with value: 0.20457219381229125 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.6824265755354791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13000278013180866}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21997861326285056
Fold 2 IBS: 0.17510133496874586
Fold 3 IBS: 0.20782135929983414
Fold 4 IBS: 0.20318340455059253
Fold 5 IBS: 0.21807100804623603
[I 2024-04-14 22:13:12,218] Trial 52 finished with value: 0.20483114402565183 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 39, 'oob_score': False, 'max_samples': 0.7595422741248538, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1492553835770421}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.20187641777839058
Fold 2 IBS: 0.21697708771949703
Fold 3 IBS: 0.2594495566549233
Fold 4 IBS: 0.2052587865188469
Fold 5 IBS: 0.22918402151273276
[I 2024-04-14 22:13:12,391] Trial 53 finished with value: 0.22254917403687813 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7063377467137641, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12053402761378912}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2163446023224957
Fold 2 IBS: 0.17212550764211373
Fold 3 IBS: 0.21160944290207245
Fold 4 IBS: 0.20512480185219015
Fold 5 IBS: 0.2160354664693132
[I 2024-04-14 22:13:13,210] Trial 54 finished with value: 0.20424796423763705 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.6746935555292785, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0904689651104114}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22967201163797166
Fold 2 IBS: 0.17176959330058167
Fold 3 IBS: 0.20224897452635443
Fold 4 IBS: 0.20289718637619525
Fold 5 IBS: 0.21350582751457162
[I 2024-04-14 22:13:14,602] Trial 55 finished with value: 0.2040187186711349 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 135, 'oob_score': False, 'max_samples': 0.8028424541436651, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18708342016220178}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2329914623588844
Fold 2 IBS: 0.1709218692606976
Fold 3 IBS: 0.2022628895427006
Fold 4 IBS: 0.2037428253059489
Fold 5 IBS: 0.21379783296488847
[I 2024-04-14 22:13:16,041] Trial 56 finished with value: 0.204743375886624 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.8015891614775278, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08443475399948225}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22222933862075872
Fold 2 IBS: 0.17307243696245472
Fold 3 IBS: 0.2076841617030592
Fold 4 IBS: 0.20227550999755373
Fold 5 IBS: 0.21586625145405466
[I 2024-04-14 22:13:17,628] Trial 57 finished with value: 0.2042255397475762 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.6308231363037688, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04742769018003304}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2456168604122806
Fold 2 IBS: 0.1720780186944042
Fold 3 IBS: 0.1939891166776255
Fold 4 IBS: 0.21652289584699036
Fold 5 IBS: 0.21111767529637926
[I 2024-04-14 22:13:19,276] Trial 58 finished with value: 0.207864913385536 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.6079842908829092, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04294499138204588}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22124664269345137
Fold 2 IBS: 0.17562069103113492
Fold 3 IBS: 0.2089041573304958
Fold 4 IBS: 0.20473650596918874
Fold 5 IBS: 0.2141094172536013
[I 2024-04-14 22:13:21,762] Trial 59 finished with value: 0.20492348285557443 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.6538044546332764, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02711344752535265}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2181513360924439
Fold 2 IBS: 0.17768472605175628
Fold 3 IBS: 0.21223044737111443
Fold 4 IBS: 0.20136958313815562
Fold 5 IBS: 0.21615046674907337
[I 2024-04-14 22:13:22,964] Trial 60 finished with value: 0.20511731188050875 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 84, 'oob_score': True, 'max_samples': 0.7478284186818124, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006650389537996307}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23118626942195483
Fold 2 IBS: 0.1702053994866854
Fold 3 IBS: 0.2129030925098888
Fold 4 IBS: 0.19903740475703263
Fold 5 IBS: 0.2136572303984417
[I 2024-04-14 22:13:23,823] Trial 61 finished with value: 0.20539787931480066 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.830509938904831, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1023742346219489}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2205940046318535
Fold 2 IBS: 0.17584334134448318
Fold 3 IBS: 0.20675620555477245
Fold 4 IBS: 0.20426009333569892
Fold 5 IBS: 0.216570869801864
[I 2024-04-14 22:13:25,267] Trial 62 finished with value: 0.20480490293373438 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 102, 'oob_score': True, 'max_samples': 0.6818329215138573, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18242157905770487}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23169425244220557
Fold 2 IBS: 0.17140668425310054
Fold 3 IBS: 0.19908163234934842
Fold 4 IBS: 0.20893662933440016

Fold 5 IBS: 0.21281753768850425
[I 2024-04-14 22:13:27,746] Trial 63 finished with value: 0.20478734721351177 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.5771231216606082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05763095148942208}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21904071817956408
Fold 2 IBS: 0.17322770907939164
Fold 3 IBS: 0.21071337338690455
Fold 4 IBS: 0.20198953222034577
Fold 5 IBS: 0.21531568867352077
[I 2024-04-14 22:13:29,160] Trial 64 finished with value: 0.20405740430794536 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.6331344922813995, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1612709153840626}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2211019166635484
Fold 2 IBS: 0.17526371579768263
Fold 3 IBS: 0.20774379356238173
Fold 4 IBS: 0.20424362266236684
Fold 5 IBS: 0.21480184651012801
[I 2024-04-14 22:13:31,042] Trial 65 finished with value: 0.2046309790392215 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.6350728460096916, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1631502901267459}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22198736886877768
Fold 2 IBS: 0.19061491871912364
Fold 3 IBS: 0.21827968226635633
Fold 4 IBS: 0.2052006534517124
Fold 5 IBS: 0.21613440335803383
[I 2024-04-14 22:13:32,200] Trial 66 finished with value: 0.21044340533280076 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.5218576422719642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19995250145835095}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2179075292069881
Fold 2 IBS: 0.18413396774995214
Fold 3 IBS: 0.20963049043297036
Fold 4 IBS: 0.20746418192466917
Fold 5 IBS: 0.21676539015107638
[I 2024-04-14 22:13:33,204] Trial 67 finished with value: 0.20718031189313124 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 52, 'oob_score': False, 'max_samples': 0.6169103339039868, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0952902999587806}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2265700266034037
Fold 2 IBS: 0.18276032311436483
Fold 3 IBS: 0.2042864418492306
Fold 4 IBS: 0.20936741747437496
Fold 5 IBS: 0.21564455337157445
[I 2024-04-14 22:13:33,620] Trial 68 finished with value: 0.20772575248258968 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.7428544401290184, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07523325642012642}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2317749634162734
Fold 2 IBS: 0.1684381693450842
Fold 3 IBS: 0.23424060778843453
Fold 4 IBS: 0.21328093521325694
Fold 5 IBS: 0.21962511519703135
[I 2024-04-14 22:13:35,155] Trial 69 finished with value: 0.2134719581920161 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.6630802195286096, 'max_features': None, 'min_weight_fraction_leaf': 0.12509688782986045}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21940762796898436
Fold 2 IBS: 0.17406140071679074
Fold 3 IBS: 0.21074986909040594
Fold 4 IBS: 0.20255362262736462
Fold 5 IBS: 0.2145647222877615
[I 2024-04-14 22:13:36,579] Trial 70 finished with value: 0.20426744853826145 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.6927913414061104, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1491330560760582}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22012016394475659
Fold 2 IBS: 0.17475427785134492
Fold 3 IBS: 0.21014966656305184
Fold 4 IBS: 0.20376747945979912
Fold 5 IBS: 0.21541417348684497
[I 2024-04-14 22:13:38,167] Trial 71 finished with value: 0.2048411522611595 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.6845803813000064, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1523838280114369}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2216865262329327
Fold 2 IBS: 0.17268198910660865
Fold 3 IBS: 0.21309572839002539
Fold 4 IBS: 0.20002188205239937
Fold 5 IBS: 0.2166664932944772
[I 2024-04-14 22:13:39,314] Trial 72 finished with value: 0.20483052381528868 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7721996477240339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17006714738018724}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2204717268372329
Fold 2 IBS: 0.18965023421922483
Fold 3 IBS: 0.21023281503750718
Fold 4 IBS: 0.20732383670369434
Fold 5 IBS: 0.21359155179608108
[I 2024-04-14 22:13:40,141] Trial 73 finished with value: 0.20825403291874806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 44, 'oob_score': False, 'max_samples': 0.60377148666791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12161104496600006}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2191586477412759
Fold 2 IBS: 0.17078013242114562
Fold 3 IBS: 0.20927963366535351
Fold 4 IBS: 0.20258237972300233
Fold 5 IBS: 0.2149257258484936
[I 2024-04-14 22:13:41,139] Trial 74 finished with value: 0.2033453038798542 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7304174393685703, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18556210671805792}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21830414363737688
Fold 2 IBS: 0.17720271112298439
Fold 3 IBS: 0.20697150533408146
Fold 4 IBS: 0.20250876743216076
Fold 5 IBS: 0.2152601673419393
[I 2024-04-14 22:13:42,717] Trial 75 finished with value: 0.20404945897370858 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.6468801596739339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18546007907051182}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22430380108574707
Fold 2 IBS: 0.18306897497858327
Fold 3 IBS: 0.20464475027408288
Fold 4 IBS: 0.21223544052441004
Fold 5 IBS: 0.21727837802511207
[I 2024-04-14 22:13:44,564] Trial 76 finished with value: 0.20830626897758706 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.7294723925670973, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24992337115768753}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22302173389184585
Fold 2 IBS: 0.1887176942510202
Fold 3 IBS: 0.20967732423927182
Fold 4 IBS: 0.20791001510644727
Fold 5 IBS: 0.21680578739397888
[I 2024-04-14 22:13:45,904] Trial 77 finished with value: 0.2092265109765128 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2128668242174557}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2239900710700344
Fold 2 IBS: 0.1698615839561287
Fold 3 IBS: 0.2095547190098964
Fold 4 IBS: 0.2012069680997044
Fold 5 IBS: 0.21613576683580699
[I 2024-04-14 22:13:47,042] Trial 78 finished with value: 0.20414982179431415 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.798025512896543, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.187406229874218}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22242518635376562

Fold 2 IBS: 0.17356537149199874
Fold 3 IBS: 0.19348965127184473
Fold 4 IBS: 0.20729301862706373
Fold 5 IBS: 0.21518309439089522
[I 2024-04-14 22:13:47,424] Trial 79 finished with value: 0.2023912644271136 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.7940170614934956, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19696931079449848}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2449767955817733
Fold 2 IBS: 0.172095460075217
Fold 3 IBS: 0.21463433607213933
Fold 4 IBS: 0.21510140082957746
Fold 5 IBS: 0.21527266884222518
[I 2024-04-14 22:13:47,885] Trial 80 finished with value: 0.21241613228018644 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 28, 'oob_score': False, 'max_samples': 0.8170871700419534, 'max_features': None, 'min_weight_fraction_leaf': 0.21125680575069572}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22348296120259534
Fold 2 IBS: 0.16980207668047606
Fold 3 IBS: 0.21009370900921706
Fold 4 IBS: 0.20191156961895484
Fold 5 IBS: 0.21613576683580699
[I 2024-04-14 22:13:48,705] Trial 81 finished with value: 0.20428521666941007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7971516901362177, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18138610915926726}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2561856444522722
Fold 2 IBS: 0.1673967931519715
Fold 3 IBS: 0.20047088391888304
Fold 4 IBS: 0.21074651924541707
Fold 5 IBS: 0.2099772553369716
[I 2024-04-14 22:13:48,983] Trial 82 finished with value: 0.20895541922110308 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.8399824689482805, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19201377617331056}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22426305056629034
Fold 2 IBS: 0.18300755389928863
Fold 3 IBS: 0.20718971819956258
Fold 4 IBS: 0.20479720064549958
Fold 5 IBS: 0.21619343342523623
[I 2024-04-14 22:13:49,500] Trial 83 finished with value: 0.20709019134717543 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.7653436422440136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24531020078321944}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22467801181967628
Fold 2 IBS: 0.17100965075590382
Fold 3 IBS: 0.20899248385281644
Fold 4 IBS: 0.20131690199114788
Fold 5 IBS: 0.21546837157592233
[I 2024-04-14 22:13:50,464] Trial 84 finished with value: 0.20429308399909335 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.7307213180337556, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16397999497171722}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22483109101566637
Fold 2 IBS: 0.17542630441342943
Fold 3 IBS: 0.207300694612249
Fold 4 IBS: 0.20406653897060492
Fold 5 IBS: 0.2158305961193959
[I 2024-04-14 22:13:51,741] Trial 85 finished with value: 0.2054910450262691 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.7826456215522579, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22924983418535252}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22386484118726915
Fold 2 IBS: 0.17019457614889205
Fold 3 IBS: 0.19033990305706086
Fold 4 IBS: 0.20853944070357402
Fold 5 IBS: 0.21728171951643854
[I 2024-04-14 22:13:52,206] Trial 86 finished with value: 0.20204409612264693 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.20601078792005195
Fold 2 IBS: 0.21451972742974615
Fold 3 IBS: 0.24528820767892662
Fold 4 IBS: 0.22453641785090767
Fold 5 IBS: 0.23206174675939142
[I 2024-04-14 22:13:52,426] Trial 87 finished with value: 0.22448337752780478 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.6512094554417259, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20485933323937144}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.24762671522415539
Fold 2 IBS: 0.1715658463060267
Fold 3 IBS: 0.19148117469966647
Fold 4 IBS: 0.20997063572215197
Fold 5 IBS: 0.2129063439446945
[I 2024-04-14 22:13:52,978] Trial 88 finished with value: 0.206710143179339 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.7081631748214322, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.135797779820887}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.25058563680774437
Fold 2 IBS: 0.2338641464063254
Fold 3 IBS: 0.22952356547794778
Fold 4 IBS: 0.24193138867022507
Fold 5 IBS: 0.23265095037320685
[I 2024-04-14 22:13:53,321] Trial 89 finished with value: 0.2377111375470899 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.15094844814066605, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25791328124207724}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22061007889537348
Fold 2 IBS: 0.1708591714745691
Fold 3 IBS: 0.21077158373683536
Fold 4 IBS: 0.20117937734899835
Fold 5 IBS: 0.2131852975039104
[I 2024-04-14 22:13:54,162] Trial 90 finished with value: 0.20332110179193735 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7073303179127854, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17438023467720193}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22104227565411022
Fold 2 IBS: 0.1722308353188776
Fold 3 IBS: 0.21218986505215992
Fold 4 IBS: 0.2005308528950858
Fold 5 IBS: 0.21558296667096527
[I 2024-04-14 22:13:54,850] Trial 91 finished with value: 0.20431535911823975 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.7458306090358743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17711861957316688}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2188852968200289
Fold 2 IBS: 0.1741200249949188
Fold 3 IBS: 0.2102249823823517
Fold 4 IBS: 0.20502686094713804
Fold 5 IBS: 0.21682970835459212
[I 2024-04-14 22:13:55,544] Trial 92 finished with value: 0.20501737469980594 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.6974990002375354, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16157211463362758}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22524471349246272
Fold 2 IBS: 0.18187848730423692
Fold 3 IBS: 0.20172697428993133
Fold 4 IBS: 0.20497913158718492
Fold 5 IBS: 0.2205671313428573
[I 2024-04-14 22:13:56,068] Trial 93 finished with value: 0.20687928760333466 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.6611862408590626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1916422380825528}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22083768503980603
Fold 2 IBS: 0.1797588530429119
Fold 3 IBS: 0.2079648062250091
Fold 4 IBS: 0.20291373702977164
Fold 5 IBS: 0.21635495382740025
[I 2024-04-14 22:13:57,173] Trial 94 finished with value: 0.2055660070329798 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.713903532939743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22122568041634558}. Best is trial 86 with value: 0.20204409612264693.

Fold 1 IBS: 0.26932513184118945
Fold 2 IBS: 0.1697323509215535
Fold 3 IBS: 0.20905255797983618
Fold 4 IBS: 0.2258672184082545
Fold 5 IBS: 0.2152407835992728
[I 2024-04-14 22:13:57,655] Trial 95 finished with value: 0.21784360855002127 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.8547756485942715, 'max_features': None, 'min_weight_fraction_leaf': 0.17594983744388534}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22065985212578162
Fold 2 IBS: 0.1724043068676393
Fold 3 IBS: 0.212876495767763
Fold 4 IBS: 0.20196603399913246
Fold 5 IBS: 0.21590968295775706
[I 2024-04-14 22:13:58,542] Trial 96 finished with value: 0.2047632743436147 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.7614906038154946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.140922870660813}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2124870890419155
Fold 2 IBS: 0.1839728942989018
Fold 3 IBS: 0.20401760145240125
Fold 4 IBS: 0.2083031273260043
Fold 5 IBS: 0.2181106808859397
[I 2024-04-14 22:13:59,228] Trial 97 finished with value: 0.20537827860103253 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.6469848321883379, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20645813530532972}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.21598257747339383
Fold 2 IBS: 0.19029660089884604
Fold 3 IBS: 0.21934243199729314
Fold 4 IBS: 0.20794860179398514
Fold 5 IBS: 0.21465156821990095
[I 2024-04-14 22:14:00,038] Trial 98 finished with value: 0.2096443560766838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.5974486750517274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2337807792851884}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22905634179711468
Fold 2 IBS: 0.16952063124242736
Fold 3 IBS: 0.20512675662267585
Fold 4 IBS: 0.2057771072122423
Fold 5 IBS: 0.21371077936387817
[I 2024-04-14 22:14:02,009] Trial 99 finished with value: 0.20463832324766768 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 185, 'oob_score': False, 'max_samples': 0.7373842810679355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15101502561347407}. Best is trial 86 with value: 0.20204409612264693.


* Best trial for IBS:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.20204409612264693], datetime_start=datetime.datetime(2024, 4, 14, 22, 13, 51, 747213), datetime_complete=datetime.datetime(2024, 4, 14, 22, 13, 52, 205890), params={'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=86, value=None)


* Best Score for IBS:
 0.20204409612264693

In [125]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [126]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.83
train_ibs:  0.202

#### Test

In [127]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [128]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=18, max_leaf_nodes=11,
                     max_samples=0.9059465751594485, min_samples_leaf=1,
                     min_weight_fraction_leaf=0.029068528038335394,
                     n_estimators=318, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.544

RandomSurvivalForest(max_depth=13, max_features='log2', max_leaf_nodes=11,
                     max_samples=0.7105780352803006, min_samples_leaf=11,
                     min_samples_split=13,
                     min_weight_fraction_leaf=0.2021626029496649,
                     n_estimators=31, random_state=123)

test_ibs:  0.247

In [129]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [130]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:14:03,303] A new study created in memory with name: no-name-011f1d51-0a43-4b35-b959-37a048c17fc5

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:04,114] Trial 0 finished with value: 0.7329375617815092 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:14:05,935] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:09,669] Trial 2 finished with value: 0.7178460229393517 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.8
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:14:10,040] Trial 3 finished with value: 0.7317208004250113 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:14:11,497] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:14:13,857] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:15,044] Trial 6 finished with value: 0.7321370246874943 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:14:17,703] Trial 7 finished with value: 0.7075673219865799 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:14:17,927] Trial 8 finished with value: 0.7362139149697521 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6545064377682404
[I 2024-04-14 22:14:24,088] Trial 9 finished with value: 0.6956580572700294 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:14:24,444] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.26413466171660194, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6802575107296137
[I 2024-04-14 22:14:24,726] Trial 11 finished with value: 0.7002022988770951 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 5, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:14:25,090] Trial 12 finished with value: 0.7233216044410213 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 108, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.21197644982784386}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:14:25,913] Trial 13 finished with value: 0.7227860885168853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 336, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7132669067566587, 'min_weight_fraction_leaf': 0.09682728258065251}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.7538759689922481
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 22:14:27,075] Trial 14 finished with value: 0.6875118831760492 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.3790277944184374}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:14:27,455] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.25853971878279847, 'min_weight_fraction_leaf': 0.1136143317234711}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:14:28,070] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.12362405012814498, 'min_weight_fraction_leaf': 0.18949444225079395}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:28,897] Trial 17 finished with value: 0.7333650628805521 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8640754037508087, 'min_weight_fraction_leaf': 0.08300984976320161}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:33,587] Trial 18 finished with value: 0.7138187212932231 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.893843387841617, 'min_weight_fraction_leaf': 0.0012901863864347718}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6587982832618026
[I 2024-04-14 22:14:34,217] Trial 19 finished with value: 0.7057594207270395 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 173, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6462028944794036, 'min_weight_fraction_leaf': 0.24752940142621416}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:14:34,882] Trial 20 finished with value: 0.7323582709861934 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 214, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9046520586847226, 'min_weight_fraction_leaf': 0.15604495917089234}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:14:36,161] Trial 21 finished with value: 0.733056653279694 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8264846465847887, 'min_weight_fraction_leaf': 0.06531032832143097}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:37,630] Trial 22 finished with value: 0.7346870590959979 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8554939338437892, 'min_weight_fraction_leaf': 0.05912077213864973}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:39,167] Trial 23 finished with value: 0.7352841948632597 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 487, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6813559412681637, 'min_weight_fraction_leaf': 0.03807965277622394}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:40,493] Trial 24 finished with value: 0.7320605873920041 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7101858188995143, 'min_weight_fraction_leaf': 0.03414106493059247}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:14:42,623] Trial 25 finished with value: 0.727965007825656 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:14:47,831] Trial 26 finished with value: 0.7097917064892874 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7363157908211037, 'min_weight_fraction_leaf': 0.030609355115257964}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:48,741] Trial 27 finished with value: 0.7289930115925871 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.05966804358984962}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:14:50,090] Trial 28 finished with value: 0.727700523625848 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9547761993685097, 'min_weight_fraction_leaf': 0.18010884975569444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6716738197424893
[I 2024-04-14 22:14:50,344] Trial 29 finished with value: 0.7278903944963211 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 53, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6672466493035638, 'min_weight_fraction_leaf': 0.09570676535902678}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:14:51,586] Trial 30 finished with value: 0.7283637613256518 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.21525035641182588}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:14:52,661] Trial 31 finished with value: 0.7301852441402965 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8780867392507613, 'min_weight_fraction_leaf': 0.08053342835298444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:14:54,447] Trial 32 finished with value: 0.7270669981840107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8465161672872993, 'min_weight_fraction_leaf': 0.13728708040036253}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:14:55,457] Trial 33 finished with value: 0.7291276715364954 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7791575185731888, 'min_weight_fraction_leaf': 0.08782522649871717}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:14:56,426] Trial 34 finished with value: 0.732991669441196 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.0321950347302904}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:14:58,607] Trial 35 finished with value: 0.7285589865120596 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 462, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7484887897698851, 'min_weight_fraction_leaf': 0.11179394316240188}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 22:14:59,724] Trial 36 finished with value: 0.704782939479291 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 120, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5819516222091663, 'min_weight_fraction_leaf': 0.05929252020100452}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:15:00,347] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6894294877112123, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:15:01,569] Trial 38 finished with value: 0.6969977793569042 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6176423630852546, 'min_weight_fraction_leaf': 0.27842662148070446}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:15:03,849] Trial 39 finished with value: 0.7145032975216214 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4114486681290081, 'min_weight_fraction_leaf': 0.006316515579589441}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:15:04,610] Trial 40 finished with value: 0.7394420414645654 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.070818312691936}. Best is trial 40 with value: 0.7394420414645654.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:15:05,487] Trial 41 finished with value: 0.7402388542135694 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7929235954297236, 'min_weight_fraction_leaf': 0.06753409188567513}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:15:06,419] Trial 42 finished with value: 0.7385473158906132 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7814167764920316, 'min_weight_fraction_leaf': 0.053138807692614115}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 22:15:07,221] Trial 43 finished with value: 0.7526793316239683 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 342, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.0237916514620877}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:15:08,076] Trial 44 finished with value: 0.7517156174445475 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7903494194560798, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 22:15:09,245] Trial 45 finished with value: 0.75724249310961 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9975014761881965, 'min_weight_fraction_leaf': 0.01820664676789947}. Best is trial 45 with value: 0.75724249310961.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:10,462] Trial 46 finished with value: 0.7516108231937302 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9833287122666867, 'min_weight_fraction_leaf': 0.02167204729301097}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:15:14,524] Trial 47 finished with value: 0.7072551380763006 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 277, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9938409184868892, 'min_weight_fraction_leaf': 0.012424414465270794}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:15:16,293] Trial 48 finished with value: 0.736994195055912 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 315, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9943389290512517, 'min_weight_fraction_leaf': 0.024122723628498613}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6201716738197425
[I 2024-04-14 22:15:17,010] Trial 49 finished with value: 0.6871506500322846 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.943836768280026, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:15:17,729] Trial 50 finished with value: 0.738757879065195 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9218905769996524, 'min_weight_fraction_leaf': 0.017081546823995417}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:18,701] Trial 51 finished with value: 0.7587815706706135 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8006618362151878, 'min_weight_fraction_leaf': 0.0006942403087633227}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:19,516] Trial 52 finished with value: 0.7475219816321547 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7294591746589625, 'min_weight_fraction_leaf': 0.0016358111792067614}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:20,292] Trial 53 finished with value: 0.7566629550916705 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5353674654541881, 'min_weight_fraction_leaf': 0.0026771789807350996}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:15:21,050] Trial 54 finished with value: 0.7352011465498318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5280559833057176, 'min_weight_fraction_leaf': 0.039551718738544406}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:15:21,940] Trial 55 finished with value: 0.7336828402532702 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3722344587434572, 'min_weight_fraction_leaf': 0.019345288070128742}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 22:15:22,718] Trial 56 finished with value: 0.7370042171283777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5400588998582563, 'min_weight_fraction_leaf': 0.04313419866698206}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 22:15:23,550] Trial 57 finished with value: 0.7325789664550014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5822470231276546, 'min_weight_fraction_leaf': 0.10820490172022261}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:15:24,389] Trial 58 finished with value: 0.7420782648330935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.47947757991973655, 'min_weight_fraction_leaf': 0.019676870735375367}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:15:29,785] Trial 59 finished with value: 0.7082120978166874 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 402, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9629602149520176, 'min_weight_fraction_leaf': 5.104770246312437e-05}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:15:30,600] Trial 60 finished with value: 0.7315255752386033 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 266, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.04917170213673687}. Best is trial 51 with value: 0.7587815706706135.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 22:15:31,421] Trial 61 finished with value: 0.7467905765647049 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7262478375780741, 'min_weight_fraction_leaf': 0.0014391069076949321}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:32,465] Trial 62 finished with value: 0.7475583381073945 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8176070633016336, 'min_weight_fraction_leaf': 0.017513460534447932}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:33,512] Trial 63 finished with value: 0.7466925367529218 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9048655808252274, 'min_weight_fraction_leaf': 0.026324306931491667}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:15:34,515] Trial 64 finished with value: 0.7370190980741596 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8235728807014974, 'min_weight_fraction_leaf': 0.07647889290633725}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:35,366] Trial 65 finished with value: 0.7475730756320799 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8717939599515069, 'min_weight_fraction_leaf': 0.046903678085942646}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:15:36,665] Trial 66 finished with value: 0.7482897431748442 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8797774907667472, 'min_weight_fraction_leaf': 0.048960653209137665}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:15:37,575] Trial 67 finished with value: 0.7393805115631469 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9729538475019345, 'min_weight_fraction_leaf': 0.09677508382156286}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 22:15:38,570] Trial 68 finished with value: 0.7053000937674134 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9142124434676113, 'min_weight_fraction_leaf': 0.3293312145420018}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:15:39,582] Trial 69 finished with value: 0.7350965386026626 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8817438215622965, 'min_weight_fraction_leaf': 0.034436173984274676}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7381974248927039
[I 2024-04-14 22:15:41,124] Trial 70 finished with value: 0.7613284744465487 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470771316919997, 'min_weight_fraction_leaf': 0.05299254826291741}. Best is trial 70 with value: 0.7613284744465487.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7424892703862661
[I 2024-04-14 22:15:42,932] Trial 71 finished with value: 0.7638673522542814 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:15:44,181] Trial 72 finished with value: 0.7530816328485426 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9438070806786616, 'min_weight_fraction_leaf': 0.0719219098849957}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:15:45,714] Trial 73 finished with value: 0.7529399312925945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9476534872163854, 'min_weight_fraction_leaf': 0.07948506430889707}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:15:47,113] Trial 74 finished with value: 0.7416078997115878 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9315744574283523, 'min_weight_fraction_leaf': 0.12730293993691283}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:15:48,510] Trial 75 finished with value: 0.7537662190909693 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9538212906403223, 'min_weight_fraction_leaf': 0.07947418064331738}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 22:15:55,826] Trial 76 finished with value: 0.7089732912239908 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503206330661996, 'min_weight_fraction_leaf': 0.08332855281149479}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:15:57,218] Trial 77 finished with value: 0.736222548982041 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9563764400770771, 'min_weight_fraction_leaf': 0.15158139627292644}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:15:58,447] Trial 78 finished with value: 0.7474677305513714 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9184606416275723, 'min_weight_fraction_leaf': 0.10966234237102679}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:15:59,443] Trial 79 finished with value: 0.7513105165834996 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8509706901999897, 'min_weight_fraction_leaf': 0.07437080570205526}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 22:16:00,641] Trial 80 finished with value: 0.7250348087736878 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9986660238693948, 'min_weight_fraction_leaf': 0.16662237313004993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 22:16:02,120] Trial 81 finished with value: 0.7572071277415792 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9698042200030538, 'min_weight_fraction_leaf': 0.059098984023617004}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:16:03,175] Trial 82 finished with value: 0.7514553752203057 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9681006428937893, 'min_weight_fraction_leaf': 0.09188576940897883}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 22:16:04,202] Trial 83 finished with value: 0.7580508863024411 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.900953067564881, 'min_weight_fraction_leaf': 0.06238575631317688}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 22:16:05,421] Trial 84 finished with value: 0.7603690354420299 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981565134422631, 'min_weight_fraction_leaf': 0.055911383060435194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 22:16:06,697] Trial 85 finished with value: 0.7514701127449911 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8908313295588716, 'min_weight_fraction_leaf': 0.05754237849545954}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 22:16:07,875] Trial 86 finished with value: 0.7604986057242595 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9139139944038005, 'min_weight_fraction_leaf': 0.06479300875481753}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 22:16:09,211] Trial 87 finished with value: 0.7619731232898213 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.908648262335172, 'min_weight_fraction_leaf': 0.055676683204352095}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 22:16:14,941] Trial 88 finished with value: 0.7081331135870429 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 457, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8593524715534154, 'min_weight_fraction_leaf': 0.20522107340967194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 22:16:16,448] Trial 89 finished with value: 0.7612669180968402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9096225926270616, 'min_weight_fraction_leaf': 0.06086475861021993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:16:18,100] Trial 90 finished with value: 0.7482861622509297 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9036341058690905, 'min_weight_fraction_leaf': 0.10323471635782432}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 22:16:19,426] Trial 91 finished with value: 0.7579312275401037 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.930984837991578, 'min_weight_fraction_leaf': 0.06281312587463944}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 22:16:20,831] Trial 92 finished with value: 0.7465445210352575 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.837687225987731, 'min_weight_fraction_leaf': 0.03575880044104557}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 22:16:22,276] Trial 93 finished with value: 0.7562581510868437 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9274363792849041, 'min_weight_fraction_leaf': 0.0661014687608754}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 22:16:23,582] Trial 94 finished with value: 0.7581413668716293 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8978558580565509, 'min_weight_fraction_leaf': 0.04353249947872927}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 22:16:24,897] Trial 95 finished with value: 0.7464935540221674 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8979178686532339, 'min_weight_fraction_leaf': 0.09188808281710414}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:16:26,420] Trial 96 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8782096526369123, 'min_weight_fraction_leaf': 0.4423900052068913}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 22:16:27,976] Trial 97 finished with value: 0.707119307000758 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 467, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7568822772464855, 'min_weight_fraction_leaf': 0.12390809358298693}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 22:16:29,155] Trial 98 finished with value: 0.7595501798994153 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8379792984882093, 'min_weight_fraction_leaf': 0.04873278208701805}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 22:16:30,413] Trial 99 finished with value: 0.7454360752058654 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8115869270579641, 'min_weight_fraction_leaf': 0.046153664833883515}. Best is trial 71 with value: 0.7638673522542814.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.7638673522542814], datetime_start=datetime.datetime(2024, 4, 14, 22, 15, 41, 151776), datetime_complete=datetime.datetime(2024, 4, 14, 22, 15, 42, 932117), params={'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for C-index:
 0.7638673522542814

[I 2024-04-14 22:16:30,425] A new study created in memory with name: no-name-cf6690e6-42e8-404e-9c3f-61b68fd5528f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23536610912753758
Fold 2 IBS: 0.20145762246413637
Fold 3 IBS: 0.20393081537250338
Fold 4 IBS: 0.21602715770992703
Fold 5 IBS: 0.2123183673596273
[I 2024-04-14 22:16:35,510] Trial 0 finished with value: 0.21382001440674636 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-14 22:16:41,926] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24081748643654036
Fold 2 IBS: 0.21713451086140778
Fold 3 IBS: 0.21706845078329945
Fold 4 IBS: 0.22785653322218774
Fold 5 IBS: 0.2212935208368412
[I 2024-04-14 22:16:46,341] Trial 2 finished with value: 0.22483410042805532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24130149411697235
Fold 2 IBS: 0.2155958186901399
Fold 3 IBS: 0.21794780991257648
Fold 4 IBS: 0.2281735359031675
Fold 5 IBS: 0.2213413510348227
[I 2024-04-14 22:16:47,593] Trial 3 finished with value: 0.22487200193153578 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-14 22:16:51,511] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-14 22:16:53,323] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23588196908877218
Fold 2 IBS: 0.20300039081654195
Fold 3 IBS: 0.2032173161135722
Fold 4 IBS: 0.21660656247722504
Fold 5 IBS: 0.21313591685519812
[I 2024-04-14 22:16:56,742] Trial 6 finished with value: 0.21436843107026188 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23825239046762217
Fold 2 IBS: 0.20781792017117767
Fold 3 IBS: 0.20896423148161078
Fold 4 IBS: 0.2197851504145311
Fold 5 IBS: 0.21653670443025383
[I 2024-04-14 22:16:59,001] Trial 7 finished with value: 0.2182712793930391 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23441021296278977
Fold 2 IBS: 0.21668396635030526
Fold 3 IBS: 0.22051379811268176
Fold 4 IBS: 0.22841790837130418
Fold 5 IBS: 0.21971786351985503
[I 2024-04-14 22:16:59,514] Trial 8 finished with value: 0.2239487498633872 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24426590657878128
Fold 2 IBS: 0.22769375627843935
Fold 3 IBS: 0.22591830688186657
Fold 4 IBS: 0.23810899013034692
Fold 5 IBS: 0.22806252164373667
[I 2024-04-14 22:17:04,552] Trial 9 finished with value: 0.23280989630263416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-14 22:17:08,462] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.2366414313349858
Fold 2 IBS: 0.21027597932345765
Fold 3 IBS: 0.21371008388168403
Fold 4 IBS: 0.22126964028612253
Fold 5 IBS: 0.2183525448310651
[I 2024-04-14 22:17:12,412] Trial 11 finished with value: 0.22004993593146302 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23579256852371847
Fold 2 IBS: 0.19568412454984113
Fold 3 IBS: 0.20040747067699977
Fold 4 IBS: 0.21186400025265303
Fold 5 IBS: 0.20966969871024252
[I 2024-04-14 22:17:20,673] Trial 12 finished with value: 0.210683572542691 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2370011165638282
Fold 2 IBS: 0.21123276228104673
Fold 3 IBS: 0.21121286711017057
Fold 4 IBS: 0.2241696763859363
Fold 5 IBS: 0.21822141136063145
[I 2024-04-14 22:17:32,617] Trial 13 finished with value: 0.22036756674032265 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23685780568086942
Fold 2 IBS: 0.2126468337858846
Fold 3 IBS: 0.2143772281757236
Fold 4 IBS: 0.22443452861645802
Fold 5 IBS: 0.21899252589159815
[I 2024-04-14 22:17:38,182] Trial 14 finished with value: 0.22146178443010672 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.210683572542691.

Fold 1 IBS: 0.23656743298208832
Fold 2 IBS: 0.21264947915533935
Fold 3 IBS: 0.21321328704497466
Fold 4 IBS: 0.22340910553399146
Fold 5 IBS: 0.21947803887476586
[I 2024-04-14 22:17:41,666] Trial 15 finished with value: 0.22106346871823193 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24483198345747628
Fold 2 IBS: 0.2302859276502996
Fold 3 IBS: 0.2285602592982639
Fold 4 IBS: 0.24045635643173324
Fold 5 IBS: 0.22930909941169325
[I 2024-04-14 22:17:47,715] Trial 16 finished with value: 0.23468872524989326 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2357109983223001
Fold 2 IBS: 0.20494805543099556
Fold 3 IBS: 0.21371005693600734
Fold 4 IBS: 0.21914551084001152
Fold 5 IBS: 0.21764479743708764
[I 2024-04-14 22:17:51,132] Trial 17 finished with value: 0.21823188379328046 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-14 22:17:52,628] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23569889105742511
Fold 2 IBS: 0.21036165282675318
Fold 3 IBS: 0.2110188939735362
Fold 4 IBS: 0.2231729444607325
Fold 5 IBS: 0.21764713763142923
[I 2024-04-14 22:17:58,700] Trial 19 finished with value: 0.21957990398997523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2260422981383027
Fold 2 IBS: 0.21628115911706547
Fold 3 IBS: 0.22894435879157846
Fold 4 IBS: 0.22705631591030262
Fold 5 IBS: 0.2234837877858094
[I 2024-04-14 22:17:59,245] Trial 20 finished with value: 0.22436158394861172 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23626217363246013
Fold 2 IBS: 0.20265333339770739
Fold 3 IBS: 0.2030759075715199
Fold 4 IBS: 0.21605001910251603
Fold 5 IBS: 0.2129636719520293
[I 2024-04-14 22:18:07,364] Trial 21 finished with value: 0.21420102113124656 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23496608578657435
Fold 2 IBS: 0.1999430054098381
Fold 3 IBS: 0.201275593836101
Fold 4 IBS: 0.21418253302811457
Fold 5 IBS: 0.21127196072648274
[I 2024-04-14 22:18:14,664] Trial 22 finished with value: 0.21232783575742217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23555557011049139
Fold 2 IBS: 0.19236878946561603
Fold 3 IBS: 0.19926908881992766
Fold 4 IBS: 0.21084942333238568
Fold 5 IBS: 0.2081240396802252
[I 2024-04-14 22:18:21,219] Trial 23 finished with value: 0.20923338228172916 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23607695303226134
Fold 2 IBS: 0.203493581017792
Fold 3 IBS: 0.20360358222095004
Fold 4 IBS: 0.21361938713575862
Fold 5 IBS: 0.2127155595148638
[I 2024-04-14 22:18:26,898] Trial 24 finished with value: 0.21390181258432514 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23810448610418447
Fold 2 IBS: 0.20850297794887437
Fold 3 IBS: 0.20884091287918746
Fold 4 IBS: 0.21832663743927483
Fold 5 IBS: 0.2167935048771244
[I 2024-04-14 22:18:31,460] Trial 25 finished with value: 0.2181137038497291 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2366073194702186
Fold 2 IBS: 0.2094968403110053
Fold 3 IBS: 0.20963379712724098
Fold 4 IBS: 0.2223187457140648
Fold 5 IBS: 0.21676394473697067
[I 2024-04-14 22:18:40,913] Trial 26 finished with value: 0.21896412947190008 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23608107276763018
Fold 2 IBS: 0.21036141351373328
Fold 3 IBS: 0.21169155072466916
Fold 4 IBS: 0.22331018888988935
Fold 5 IBS: 0.2177506938697703
[I 2024-04-14 22:18:49,022] Trial 27 finished with value: 0.21983898395313844 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23715637039941884
Fold 2 IBS: 0.2120572412765648
Fold 3 IBS: 0.21620854589832805
Fold 4 IBS: 0.2250681900188581
Fold 5 IBS: 0.22134392576904316
[I 2024-04-14 22:18:53,908] Trial 28 finished with value: 0.22236685467244258 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24167838631766778
Fold 2 IBS: 0.22069051827263042
Fold 3 IBS: 0.22031739328406955
Fold 4 IBS: 0.23288818140652423
Fold 5 IBS: 0.22471508602895093
[I 2024-04-14 22:18:57,519] Trial 29 finished with value: 0.22805791306196857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.2369623605519169
Fold 2 IBS: 0.2015664827514855
Fold 3 IBS: 0.2044196732107329
Fold 4 IBS: 0.2152719150958778
Fold 5 IBS: 0.2123358137500061
[I 2024-04-14 22:19:06,275] Trial 30 finished with value: 0.21411124907200385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23451695205118067
Fold 2 IBS: 0.19751010562426458
Fold 3 IBS: 0.2027198084019687
Fold 4 IBS: 0.21411412044401185
Fold 5 IBS: 0.2111761169753505
[I 2024-04-14 22:19:12,687] Trial 31 finished with value: 0.21200742069935527 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.923666057752446, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2351025999648965
Fold 2 IBS: 0.1949158359424477
Fold 3 IBS: 0.20111115549804756
Fold 4 IBS: 0.21180546961424107
Fold 5 IBS: 0.20942511704648153
[I 2024-04-14 22:19:18,728] Trial 32 finished with value: 0.2104720356132229 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.939007534925735, 'min_weight_fraction_leaf': 0.056106269226335825}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2359807363001553
Fold 2 IBS: 0.20390144524422224
Fold 3 IBS: 0.20692223621119946
Fold 4 IBS: 0.2180339829065641
Fold 5 IBS: 0.21348267427916112
[I 2024-04-14 22:19:23,702] Trial 33 finished with value: 0.21566421498826044 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9138848353483187, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23760045008166628
Fold 2 IBS: 0.1836854003772293
Fold 3 IBS: 0.20658859037809638
Fold 4 IBS: 0.21356225516393262
Fold 5 IBS: 0.2080473806120064
[I 2024-04-14 22:19:34,837] Trial 34 finished with value: 0.2098968153225862 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.06204686171902169}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23705554587631616
Fold 2 IBS: 0.18409383187630057
Fold 3 IBS: 0.20774926569595484
Fold 4 IBS: 0.21266700404602018
Fold 5 IBS: 0.20816809551656013
[I 2024-04-14 22:19:43,395] Trial 35 finished with value: 0.2099467486022304 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8327847526324277, 'min_weight_fraction_leaf': 0.055940476394666754}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23566967538262615
Fold 2 IBS: 0.18498818375621254
Fold 3 IBS: 0.2076181431218228
Fold 4 IBS: 0.21248969655065036
Fold 5 IBS: 0.20727223939702627
[I 2024-04-14 22:19:52,490] Trial 36 finished with value: 0.20960758764166765 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827098326399153, 'min_weight_fraction_leaf': 0.07015937717166007}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2322804097655011
Fold 2 IBS: 0.1904595107494953
Fold 3 IBS: 0.20654496901893055
Fold 4 IBS: 0.21029065871150715
Fold 5 IBS: 0.20940168079092789
[I 2024-04-14 22:20:00,520] Trial 37 finished with value: 0.20979544580727238 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8333567609683693, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23402986510699297
Fold 2 IBS: 0.20551834233097463
Fold 3 IBS: 0.21448459324894656
Fold 4 IBS: 0.21983535419793537
Fold 5 IBS: 0.21738979632924899
[I 2024-04-14 22:20:05,102] Trial 38 finished with value: 0.2182515902428197 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 349, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.823414916934049, 'min_weight_fraction_leaf': 0.22365568672391764}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23303653525127266
Fold 2 IBS: 0.19614443640526336
Fold 3 IBS: 0.20759014709806334
Fold 4 IBS: 0.21278979581525073
Fold 5 IBS: 0.2115153572009253
[I 2024-04-14 22:20:10,771] Trial 39 finished with value: 0.21221525435415506 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7688812089462244, 'min_weight_fraction_leaf': 0.13832319540130408}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24085544671476855
Fold 2 IBS: 0.21881433431452443
Fold 3 IBS: 0.2205550472397075
Fold 4 IBS: 0.23189796849220526
Fold 5 IBS: 0.22387717931221346
[I 2024-04-14 22:20:17,823] Trial 40 finished with value: 0.22719999521468384 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7387886455857571, 'min_weight_fraction_leaf': 0.2794340971992336}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23558729160195155
Fold 2 IBS: 0.18499721054651033
Fold 3 IBS: 0.2078176191769497
Fold 4 IBS: 0.21254959703326678
Fold 5 IBS: 0.20740208695361273
[I 2024-04-14 22:20:24,118] Trial 41 finished with value: 0.20967076106245824 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 459, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8304297502532995, 'min_weight_fraction_leaf': 0.06567312882813131}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23638956396269079
Fold 2 IBS: 0.18490789291091672
Fold 3 IBS: 0.20644644482157795
Fold 4 IBS: 0.21257693995308247
Fold 5 IBS: 0.20732761178411305
[I 2024-04-14 22:20:29,879] Trial 42 finished with value: 0.20952969068647617 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 450, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7982039779530783, 'min_weight_fraction_leaf': 0.07186658790260646}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23274337848255236
Fold 2 IBS: 0.1929272244249927
Fold 3 IBS: 0.20732501652108193
Fold 4 IBS: 0.21144242883441275
Fold 5 IBS: 0.20983249626579628
[I 2024-04-14 22:20:35,198] Trial 43 finished with value: 0.21085410890576722 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 440, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.1211117088142}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2410193325812047
Fold 2 IBS: 0.2226476644714021
Fold 3 IBS: 0.22105022637397118
Fold 4 IBS: 0.23115256969605635
Fold 5 IBS: 0.2240981533222132
[I 2024-04-14 22:20:42,433] Trial 44 finished with value: 0.2279935892889695 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6979907483981592, 'min_weight_fraction_leaf': 0.16526223863734468}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.23247724033039832
Fold 2 IBS: 0.18748554961121114
Fold 3 IBS: 0.2090170455982855
Fold 4 IBS: 0.207742375469341
Fold 5 IBS: 0.20889347688505747
[I 2024-04-14 22:20:45,018] Trial 45 finished with value: 0.2091231375788587 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8505483502716148, 'min_weight_fraction_leaf': 0.09794633817349793}. Best is trial 45 with value: 0.2091231375788587.
Fold 1 IBS: 0.2314286160573986
Fold 2 IBS: 0.1860889745854672
Fold 3 IBS: 0.20638267011548084
Fold 4 IBS: 0.20884587453459477
Fold 5 IBS: 0.20805701088484838
[I 2024-04-14 22:20:47,490] Trial 46 finished with value: 0.20816062923555795 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7709286828220481, 'min_weight_fraction_leaf': 0.07995724348415684}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23766776108374213
Fold 2 IBS: 0.21002348979145327
Fold 3 IBS: 0.21765068090817657
Fold 4 IBS: 0.22280193059668152
Fold 5 IBS: 0.21940264282312605
[I 2024-04-14 22:20:50,036] Trial 47 finished with value: 0.22150930104063588 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 127, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7682715671327377, 'min_weight_fraction_leaf': 0.08646740062265149}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23713247312937227
Fold 2 IBS: 0.1864152472719121
Fold 3 IBS: 0.20569921628056348
Fold 4 IBS: 0.21202213139980625
Fold 5 IBS: 0.2062034346638877
[I 2024-04-14 22:20:54,656] Trial 48 finished with value: 0.20949450054910837 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 186, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8579998757196492, 'min_weight_fraction_leaf': 0.022631912267245}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2401019704407054
Fold 2 IBS: 0.20664694277509515
Fold 3 IBS: 0.20269468295254925
Fold 4 IBS: 0.2190769330154152
Fold 5 IBS: 0.21529320315539308
[I 2024-04-14 22:20:57,146] Trial 49 finished with value: 0.2167627464678316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 176, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.535541626399398, 'min_weight_fraction_leaf': 0.02410725915835375}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23775614182380903
Fold 2 IBS: 0.20743414808900665
Fold 3 IBS: 0.20687718864416932
Fold 4 IBS: 0.21905338149069295
Fold 5 IBS: 0.21496321205066113
[I 2024-04-14 22:20:58,455] Trial 50 finished with value: 0.21721681441966784 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 90, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8724086164488271, 'min_weight_fraction_leaf': 0.04430715227744478}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23333408320563848
Fold 2 IBS: 0.18618334408777154
Fold 3 IBS: 0.2054922876895997
Fold 4 IBS: 0.2095428614888614
Fold 5 IBS: 0.2081255374544523
[I 2024-04-14 22:21:00,483] Trial 51 finished with value: 0.2085356227852647 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 157, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7607239465677439, 'min_weight_fraction_leaf': 0.0768704777706238}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23294009669574758
Fold 2 IBS: 0.18886644911422001
Fold 3 IBS: 0.20450870840640553
Fold 4 IBS: 0.2098663013569692
Fold 5 IBS: 0.2093242311139224
[I 2024-04-14 22:21:03,130] Trial 52 finished with value: 0.2091011573374529 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 215, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6812726944311738, 'min_weight_fraction_leaf': 0.0924784870388018}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23340127695530247
Fold 2 IBS: 0.19037609007747622
Fold 3 IBS: 0.20443462122815134
Fold 4 IBS: 0.20971338145144297
Fold 5 IBS: 0.20931781265162946
[I 2024-04-14 22:21:06,017] Trial 53 finished with value: 0.2094486364728005 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 224, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6963870551875947, 'min_weight_fraction_leaf': 0.10563773255020543}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23338966290283988
Fold 2 IBS: 0.19138513453127515
Fold 3 IBS: 0.20331794017233815
Fold 4 IBS: 0.21130675152530337
Fold 5 IBS: 0.2105461957704023
[I 2024-04-14 22:21:08,961] Trial 54 finished with value: 0.20998913698043178 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6719877047239909, 'min_weight_fraction_leaf': 0.0997398012429799}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23593555870849725
Fold 2 IBS: 0.20801826761705877
Fold 3 IBS: 0.20827021219395564
Fold 4 IBS: 0.21956943852396218
Fold 5 IBS: 0.21586303213321972
[I 2024-04-14 22:21:11,161] Trial 55 finished with value: 0.21753130183533873 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7290878996075589, 'min_weight_fraction_leaf': 0.1329691849961646}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24666819701072148
Fold 2 IBS: 0.23210773115939679
Fold 3 IBS: 0.22932364190291274
Fold 4 IBS: 0.24152405514050876
Fold 5 IBS: 0.2303157661686399
[I 2024-04-14 22:21:13,331] Trial 56 finished with value: 0.23598787827643591 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5975963219999111, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23492638070785768
Fold 2 IBS: 0.21240221048192362
Fold 3 IBS: 0.2168912407987811
Fold 4 IBS: 0.22754745889623634
Fold 5 IBS: 0.22089364796872285
[I 2024-04-14 22:21:15,143] Trial 57 finished with value: 0.22253218777070433 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 128, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6735255380721511, 'min_weight_fraction_leaf': 0.18708850621022327}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23531750054242687
Fold 2 IBS: 0.2077683628397722
Fold 3 IBS: 0.21364739027613322
Fold 4 IBS: 0.21979565810435922
Fold 5 IBS: 0.21840068135164575
[I 2024-04-14 22:21:17,927] Trial 58 finished with value: 0.21898591862286745 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 238, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.15746351073381912}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24661384524722246
Fold 2 IBS: 0.23215291198462218
Fold 3 IBS: 0.22952739882394438
Fold 4 IBS: 0.24152565273881768
Fold 5 IBS: 0.2303053694496521
[I 2024-04-14 22:21:21,836] Trial 59 finished with value: 0.23602503564885174 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.75796811576398, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 46 with value: 0.20816062923555795.

Fold 1 IBS: 0.2376464824369693
Fold 2 IBS: 0.21593994734134395
Fold 3 IBS: 0.22177987321764975
Fold 4 IBS: 0.22790863488656224
Fold 5 IBS: 0.2205529164521157
[I 2024-04-14 22:21:22,972] Trial 60 finished with value: 0.22476557086692814 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 74, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6041879821929975, 'min_weight_fraction_leaf': 0.1056236625824671}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23781793031064252
Fold 2 IBS: 0.1862495208476139
Fold 3 IBS: 0.20248456745784213
Fold 4 IBS: 0.21234711020159586
Fold 5 IBS: 0.2076972639565933
[I 2024-04-14 22:21:26,439] Trial 61 finished with value: 0.20931927855485752 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 197, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7101126073432302, 'min_weight_fraction_leaf': 0.013226300887269365}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2382367270174128
Fold 2 IBS: 0.18483164704435992
Fold 3 IBS: 0.20455018380786597
Fold 4 IBS: 0.2115954964542311
Fold 5 IBS: 0.20832518097782782
[I 2024-04-14 22:21:29,566] Trial 62 finished with value: 0.20950784706033954 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7066561911530848, 'min_weight_fraction_leaf': 0.012902964688040898}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23653797420874464
Fold 2 IBS: 0.18352585769961322
Fold 3 IBS: 0.20365755657663714
Fold 4 IBS: 0.20917655609037722
Fold 5 IBS: 0.20729793495414095
[I 2024-04-14 22:21:32,837] Trial 63 finished with value: 0.20803917590590265 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 148, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6435418239181828, 'min_weight_fraction_leaf': 0.046981576659506384}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.2376440714946851
Fold 2 IBS: 0.18154571059609376
Fold 3 IBS: 0.20148827866234856
Fold 4 IBS: 0.21485752658604737
Fold 5 IBS: 0.21193720419679402
[I 2024-04-14 22:21:35,693] Trial 64 finished with value: 0.20949455830719374 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6558453673842368, 'min_weight_fraction_leaf': 0.0017360883857289438}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24069140178630108
Fold 2 IBS: 0.21023884738343832
Fold 3 IBS: 0.20819592567054473
Fold 4 IBS: 0.22032685614631106
Fold 5 IBS: 0.2181378139835771
[I 2024-04-14 22:21:37,627] Trial 65 finished with value: 0.21951816899403448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6369381520536594, 'min_weight_fraction_leaf': 0.04630739996813268}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24662572908345176
Fold 2 IBS: 0.2321190214638095
Fold 3 IBS: 0.22943780141623776
Fold 4 IBS: 0.2415441728621753
Fold 5 IBS: 0.2302929916244345
[I 2024-04-14 22:21:40,020] Trial 66 finished with value: 0.23600394329002175 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 190, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7534591387104144, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23761253968101
Fold 2 IBS: 0.19333058518344354
Fold 3 IBS: 0.19763843228218964
Fold 4 IBS: 0.2100557032515617
Fold 5 IBS: 0.208391029584297
[I 2024-04-14 22:21:42,344] Trial 67 finished with value: 0.20940565799650038 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 111, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7140591797427468, 'min_weight_fraction_leaf': 0.0380146506503018}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23568784825771597
Fold 2 IBS: 0.19836028806772887
Fold 3 IBS: 0.20225664393852164
Fold 4 IBS: 0.21479439327398367
Fold 5 IBS: 0.21109075078575282
[I 2024-04-14 22:21:44,948] Trial 68 finished with value: 0.21243798486474058 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 168, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7866638182428198, 'min_weight_fraction_leaf': 0.08748663516762165}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23356744505088914
Fold 2 IBS: 0.1834363879714103
Fold 3 IBS: 0.207688591468538
Fold 4 IBS: 0.20411915061999797
Fold 5 IBS: 0.21081229591952125
[I 2024-04-14 22:21:46,364] Trial 69 finished with value: 0.20792477420607133 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 78, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6633577858466918, 'min_weight_fraction_leaf': 0.05378179190948057}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23425832559812115
Fold 2 IBS: 0.1874883919439577
Fold 3 IBS: 0.20956087508825158
Fold 4 IBS: 0.20966146089051388
Fold 5 IBS: 0.21197029878987708
[I 2024-04-14 22:21:47,297] Trial 70 finished with value: 0.21058787046214428 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 46, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.609138718062076, 'min_weight_fraction_leaf': 0.08081693575379295}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23180288969924676
Fold 2 IBS: 0.18284953833260828
Fold 3 IBS: 0.20816697020659303
Fold 4 IBS: 0.20634477989340283
Fold 5 IBS: 0.2066720406825964
[I 2024-04-14 22:21:48,379] Trial 71 finished with value: 0.20716724376288945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24034476073822214
Fold 2 IBS: 0.18987915865551205
Fold 3 IBS: 0.2035631310131893
Fold 4 IBS: 0.21033288060199645
Fold 5 IBS: 0.20723055719361239
[I 2024-04-14 22:21:49,900] Trial 72 finished with value: 0.21027009764050644 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 64, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5683034340032609, 'min_weight_fraction_leaf': 0.04646174961182159}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2299054630450867
Fold 2 IBS: 0.19773469146740125
Fold 3 IBS: 0.19034097643724923
Fold 4 IBS: 0.22944964628361184
Fold 5 IBS: 0.2389286128541861
[I 2024-04-14 22:21:50,171] Trial 73 finished with value: 0.217271878017507 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.054429859852659815}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2303167286243434
Fold 2 IBS: 0.19516700665987674
Fold 3 IBS: 0.20660685643983331
Fold 4 IBS: 0.20899892281373353
Fold 5 IBS: 0.2066488418873486
[I 2024-04-14 22:21:50,808] Trial 74 finished with value: 0.20954767128502713 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 29, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7480880522886367, 'min_weight_fraction_leaf': 0.07511258593340842}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23693321208405524
Fold 2 IBS: 0.19000973925047765
Fold 3 IBS: 0.20243881773088923
Fold 4 IBS: 0.2110667431713562
Fold 5 IBS: 0.20765848231427028
[I 2024-04-14 22:21:52,287] Trial 75 finished with value: 0.20962139891020973 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.49599352625156035, 'min_weight_fraction_leaf': 0.03138093454428739}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2375162774090104
Fold 2 IBS: 0.21696007860868566
Fold 3 IBS: 0.2199964189465905
Fold 4 IBS: 0.2298197447784768
Fold 5 IBS: 0.2208032877666601
[I 2024-04-14 22:21:53,558] Trial 76 finished with value: 0.2250191615018847 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 81, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6498539620686062, 'min_weight_fraction_leaf': 0.1107936452967258}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.234645557683981
Fold 2 IBS: 0.19308386846985393
Fold 3 IBS: 0.21042866351417217
Fold 4 IBS: 0.213955157478479
Fold 5 IBS: 0.20941746392682734
[I 2024-04-14 22:21:54,986] Trial 77 finished with value: 0.21230614221466268 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 53, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6219886854752814, 'min_weight_fraction_leaf': 0.0881530598041391}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23208979344503086
Fold 2 IBS: 0.19134551959096457
Fold 3 IBS: 0.20969730607101159
Fold 4 IBS: 0.21155535213663088
Fold 5 IBS: 0.21094666727963496
[I 2024-04-14 22:21:57,959] Trial 78 finished with value: 0.21112692770465458 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8975377298130277, 'min_weight_fraction_leaf': 0.05792949206602531}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24656769908913287
Fold 2 IBS: 0.23207473314584195
Fold 3 IBS: 0.22956209752209408
Fold 4 IBS: 0.24131766392563656
Fold 5 IBS: 0.22974225690563504
[I 2024-04-14 22:21:59,970] Trial 79 finished with value: 0.2358528901176681 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.15079098086778978}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23398194286521523
Fold 2 IBS: 0.2042478759118354
Fold 3 IBS: 0.2149027538028443
Fold 4 IBS: 0.21138634120370936
Fold 5 IBS: 0.21509744244742898
[I 2024-04-14 22:22:00,832] Trial 80 finished with value: 0.21592327124620664 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 34, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.680202266270148, 'min_weight_fraction_leaf': 0.13027280080194392}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23821133340721135
Fold 2 IBS: 0.18697626156811917
Fold 3 IBS: 0.2025556131339658
Fold 4 IBS: 0.21248041803374165
Fold 5 IBS: 0.21006237384648405
[I 2024-04-14 22:22:03,738] Trial 81 finished with value: 0.2100571999979044 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7059723708255974, 'min_weight_fraction_leaf': 0.011081957753211642}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2354434465673004
Fold 2 IBS: 0.18590060696281396
Fold 3 IBS: 0.20237660521219805
Fold 4 IBS: 0.21289282208945418
Fold 5 IBS: 0.2079334303868527
[I 2024-04-14 22:22:06,975] Trial 82 finished with value: 0.20890938224372385 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7322939853383122, 'min_weight_fraction_leaf': 0.030199179896950257}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2391213827919915
Fold 2 IBS: 0.18339377899057588
Fold 3 IBS: 0.20630651107397327
Fold 4 IBS: 0.21414237142238046
Fold 5 IBS: 0.20709539863236437
[I 2024-04-14 22:22:10,515] Trial 83 finished with value: 0.2100118885822571 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 249, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8082167579651034, 'min_weight_fraction_leaf': 0.030688122459232033}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2338134437703758
Fold 2 IBS: 0.18585229495562317
Fold 3 IBS: 0.20232554114967682
Fold 4 IBS: 0.20935878852735582
Fold 5 IBS: 0.20693004752390112
[I 2024-04-14 22:22:12,837] Trial 84 finished with value: 0.20765602318538656 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7722055241934203, 'min_weight_fraction_leaf': 0.06706989383850837}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2325404292841733
Fold 2 IBS: 0.2037796259632883
Fold 3 IBS: 0.21285222741885748
Fold 4 IBS: 0.21748519543805853
Fold 5 IBS: 0.21558014668487166
[I 2024-04-14 22:22:16,106] Trial 85 finished with value: 0.21644752495784986 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 209, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8080700094351241, 'min_weight_fraction_leaf': 0.07313973736441735}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23185610825625882
Fold 2 IBS: 0.1883838499173774
Fold 3 IBS: 0.2069558256748436
Fold 4 IBS: 0.2056460896941882
Fold 5 IBS: 0.20834833869947297
[I 2024-04-14 22:22:18,984] Trial 86 finished with value: 0.2082380424484282 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 179, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7797829686997926, 'min_weight_fraction_leaf': 0.0930692046392031}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23732262587143452
Fold 2 IBS: 0.18516284894711776
Fold 3 IBS: 0.20293194154297275
Fold 4 IBS: 0.20976950466294828
Fold 5 IBS: 0.20684702854669929
[I 2024-04-14 22:22:21,792] Trial 87 finished with value: 0.2084067899142345 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 182, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7347045490916186, 'min_weight_fraction_leaf': 0.0569064501216709}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23610457243620386
Fold 2 IBS: 0.1843646040116617
Fold 3 IBS: 0.2038780530044773
Fold 4 IBS: 0.2105249290335657
Fold 5 IBS: 0.20647024537168604
[I 2024-04-14 22:22:24,259] Trial 88 finished with value: 0.20826848077151894 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7454117372266992, 'min_weight_fraction_leaf': 0.05974548060098256}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23977374886110586
Fold 2 IBS: 0.20834445745005828
Fold 3 IBS: 0.2081295030562698
Fold 4 IBS: 0.22184631620912326
Fold 5 IBS: 0.21759905094032755
[I 2024-04-14 22:22:26,919] Trial 89 finished with value: 0.21913861530337697 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7540347885452335, 'min_weight_fraction_leaf': 0.06459414509901623}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23900229487413618
Fold 2 IBS: 0.1829989350900894
Fold 3 IBS: 0.20504008460974205
Fold 4 IBS: 0.21135329415618298
Fold 5 IBS: 0.20658610615550185
[I 2024-04-14 22:22:28,151] Trial 90 finished with value: 0.20899614297713048 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 95, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7812194815989179, 'min_weight_fraction_leaf': 0.052583924158953604}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23336269917153504
Fold 2 IBS: 0.18793910685243745
Fold 3 IBS: 0.20227191981491185
Fold 4 IBS: 0.2126322523584538
Fold 5 IBS: 0.20891055719221097
[I 2024-04-14 22:22:30,242] Trial 91 finished with value: 0.2090233070779098 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7343789509732842, 'min_weight_fraction_leaf': 0.034512973636926236}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23849245554801698
Fold 2 IBS: 0.18514480626810045
Fold 3 IBS: 0.2021086406752317
Fold 4 IBS: 0.21479834430066197
Fold 5 IBS: 0.20909254443799166
[I 2024-04-14 22:22:32,299] Trial 92 finished with value: 0.20992735824600056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7636505288647887, 'min_weight_fraction_leaf': 0.022561082303242087}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23712661813293098
Fold 2 IBS: 0.1851768236866079
Fold 3 IBS: 0.20432880761759306
Fold 4 IBS: 0.2118089074273193
Fold 5 IBS: 0.20725293903536335
[I 2024-04-14 22:22:35,428] Trial 93 finished with value: 0.20913881917996288 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 195, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.780594325886568, 'min_weight_fraction_leaf': 0.06660760570218983}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23313202103339004
Fold 2 IBS: 0.19197759007192453
Fold 3 IBS: 0.2044094595924962
Fold 4 IBS: 0.20966584275861216
Fold 5 IBS: 0.211313413556971
[I 2024-04-14 22:22:38,622] Trial 94 finished with value: 0.21009966540267877 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 120, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5855639769841374, 'min_weight_fraction_leaf': 0.08355403368257994}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23520267938727427
Fold 2 IBS: 0.20116425107298522
Fold 3 IBS: 0.20510259876427595
Fold 4 IBS: 0.2176827586444227
Fold 5 IBS: 0.21292731974141504
[I 2024-04-14 22:22:41,329] Trial 95 finished with value: 0.21441592152207462 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8103082949117716, 'min_weight_fraction_leaf': 0.11381886996294271}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2366963489001733
Fold 2 IBS: 0.1837117121259892
Fold 3 IBS: 0.20226694531049833
Fold 4 IBS: 0.21335021541537497
Fold 5 IBS: 0.20661189736952593
[I 2024-04-14 22:22:43,621] Trial 96 finished with value: 0.20852742382431236 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7312350213287773, 'min_weight_fraction_leaf': 0.04898698424961209}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23608027081908015
Fold 2 IBS: 0.1835953504200279
Fold 3 IBS: 0.20150615985904316
Fold 4 IBS: 0.2102069690328971
Fold 5 IBS: 0.20748897405413733
[I 2024-04-14 22:22:46,176] Trial 97 finished with value: 0.20777554483703714 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 153, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6968965471814753, 'min_weight_fraction_leaf': 0.0505916256520447}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23389009461942958
Fold 2 IBS: 0.18577086451211336
Fold 3 IBS: 0.20307358104865128
Fold 4 IBS: 0.2086430242358467
Fold 5 IBS: 0.2076497222974857
[I 2024-04-14 22:22:48,783] Trial 98 finished with value: 0.20780545734270534 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6887726496402962, 'min_weight_fraction_leaf': 0.04771137682412141}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2434837934214731
Fold 2 IBS: 0.2272775037538945
Fold 3 IBS: 0.2265372467505086
Fold 4 IBS: 0.23746702398923994
Fold 5 IBS: 0.22710567134340368
[I 2024-04-14 22:22:51,176] Trial 99 finished with value: 0.23237424785170396 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 137, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6897878932245053, 'min_weight_fraction_leaf': 0.3195640033653079}. Best is trial 71 with value: 0.20716724376288945.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.20716724376288945], datetime_start=datetime.datetime(2024, 4, 14, 22, 21, 47, 318780), datetime_complete=datetime.datetime(2024, 4, 14, 22, 21, 48, 378867), params={'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.20716724376288945

In [131]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [132]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.764
train_ibs:  0.207

#### Test

In [133]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [134]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_features=None, max_leaf_nodes=13,
                   max_samples=0.9529576562335005, min_samples_split=15,
                   min_weight_fraction_leaf=0.05156899271012762,
                   n_estimators=376, random_state=123, warm_start=True)

C-index score: 0.543

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=17,
                   max_samples=0.6638490929451707, min_samples_leaf=2,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.052914450220883674,
                   n_estimators=60, oob_score=True, random_state=123)

IBS: 0.256

In [135]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [136]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 22:22:52,774] A new study created in memory with name: no-name-9363ac8e-6336-4eff-aba2-fdafdd2a391a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:23:12,072] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:23:23,203] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:23:33,634] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:23:52,536] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:23:59,669] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:24:01,527] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:24:16,265] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:24:20,657] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:24:21,137] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 22:25:02,765] Trial 9 finished with value: 0.7079199845805899 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 22:26:12,943] Trial 10 finished with value: 0.6677145778312712 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:27:37,770] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 22:28:33,743] Trial 12 finished with value: 0.6859221467184631 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:29:04,585] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:29:48,867] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:30:26,036] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:30:47,554] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:31:35,397] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:36:12,865] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:36:14,277] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:36:27,917] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 22:38:58,993] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6137339055793991
[I 2024-04-14 22:43:03,564] Trial 22 finished with value: 0.658086559263577 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:44:55,455] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:45:14,036] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:45:38,253] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:46:03,093] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:47:02,763] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:47:04,445] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:05:10,584] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:05:19,158] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-14 23:05:43,679] Trial 31 finished with value: 0.6020563220294257 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:06:19,537] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:06:44,359] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:07:21,338] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 23:07:42,062] Trial 35 finished with value: 0.6743933936379024 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:07:59,732] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:08:11,739] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:08:20,874] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:08:30,972] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:08:42,119] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-14 23:09:17,388] Trial 41 finished with value: 0.6433893503184027 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:09:41,759] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:10:15,828] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:10:24,922] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:10:59,369] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6673819742489271
[I 2024-04-14 23:11:05,006] Trial 46 finished with value: 0.6994229841114794 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:11:12,879] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:11:13,050] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:11:17,395] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:11:36,673] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 23:12:01,637] Trial 51 finished with value: 0.6921806327884186 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:12:11,436] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 23:12:32,187] Trial 53 finished with value: 0.7081084979356779 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:12:55,965] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:12:59,968] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:13:18,767] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6416309012875536
[I 2024-04-14 23:13:21,438] Trial 57 finished with value: 0.7057479712796905 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:13:24,247] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:13:30,266] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:13:35,993] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:13:41,451] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6673819742489271
[I 2024-04-14 23:13:53,809] Trial 62 finished with value: 0.712727180870049 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6630901287553648
[I 2024-04-14 23:14:05,887] Trial 63 finished with value: 0.7108187349167132 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:14:16,301] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.4297477654076297, 'learning_rate': 0.043910428099002294, 'dropout_rate': 0.8352402756430523, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4263511298787651, 'min_weight_fraction_leaf': 0.3160966031078735, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9463535838530875, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6416309012875536
[I 2024-04-14 23:14:29,640] Trial 65 finished with value: 0.6902478805446599 and parameters: {'subsample': 0.30781242416514565, 'learning_rate': 0.05113323137902576, 'dropout_rate': 0.7239851485767856, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0027463439227063506, 'min_weight_fraction_leaf': 0.26877432545564617, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0017887993094304819, 'validation_fraction': 0.761339316000577, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:14:35,794] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.48922080655608885, 'learning_rate': 0.035347527077929, 'dropout_rate': 0.8893092269739165, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5356537836856377, 'min_weight_fraction_leaf': 0.29863354085488475, 'max_features': 'sqrt', 'min_impurity_decrease': 0.012061434840147687, 'validation_fraction': 0.9051978098851384, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:14:44,857] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4210285565476828, 'learning_rate': 0.06591045167415374, 'dropout_rate': 0.8060412975360456, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7762639994874865, 'min_weight_fraction_leaf': 0.25473199100313054, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00610717642726731, 'validation_fraction': 0.8093169248034847, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:14:50,064] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.36755564370451066, 'learning_rate': 0.05068902572826714, 'dropout_rate': 0.9726834213374217, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1308236536377811, 'min_weight_fraction_leaf': 0.3065580571022596, 'max_features': 'sqrt', 'min_impurity_decrease': 0.021693222709295752, 'validation_fraction': 0.715818151257265, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:14:56,972] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5142803470563067, 'learning_rate': 0.03243373478476426, 'dropout_rate': 0.9137837647742049, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28985235680036014, 'min_weight_fraction_leaf': 0.4054829396615446, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001581139753892363, 'validation_fraction': 0.329118980782965, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:15:04,608] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.45559432833731667, 'learning_rate': 0.0700250470025932, 'dropout_rate': 0.8524549437406417, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6643601052078473, 'min_weight_fraction_leaf': 0.2388136010393243, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00031481444052736005, 'validation_fraction': 0.9166648433104408, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6373390557939914
[I 2024-04-14 23:15:18,006] Trial 71 finished with value: 0.6914213405066317 and parameters: {'subsample': 0.3096152191637527, 'learning_rate': 0.05014029765368843, 'dropout_rate': 0.72942553198655, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027173150322083957, 'min_weight_fraction_leaf': 0.28439521854539385, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002459385698607316, 'validation_fraction': 0.9631122514300272, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:15:33,161] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.2984794016129376, 'learning_rate': 0.04184406116938292, 'dropout_rate': 0.6550072165726977, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791436061459352, 'min_weight_fraction_leaf': 0.28556030062342436, 'max_features': 'sqrt', 'min_impurity_decrease': 4.3401892914387e-05, 'validation_fraction': 0.9667204228379752, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:15:35,478] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.24177977569589332, 'learning_rate': 0.06081438305266998, 'dropout_rate': 0.7352912026497521, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3565493126455575, 'min_weight_fraction_leaf': 0.2641618003854867, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005565263987110645, 'validation_fraction': 0.8591928424609534, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:15:43,106] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.41766913987966564, 'learning_rate': 0.04837445328457708, 'dropout_rate': 0.7848778465425879, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9796884706123067, 'min_weight_fraction_leaf': 0.3487238233672823, 'max_features': 0.1, 'min_impurity_decrease': 0.060142707029694174, 'validation_fraction': 0.9742035251830021, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:15:51,300] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.14697123662254313, 'learning_rate': 0.056288895309512615, 'dropout_rate': 0.9249274443508626, 'n_estimators': 491, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3014105775868996, 'min_weight_fraction_leaf': 0.2756234570388064, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5125842579708578e-05, 'validation_fraction': 0.9436471609372878, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:16:13,103] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.33597481611005453, 'learning_rate': 0.03785525432874416, 'dropout_rate': 0.5640100673453201, 'n_estimators': 465, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6095307820420031, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 0.009484910777116757, 'validation_fraction': 0.9018697914265744, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:16:31,917] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.3970316343863033, 'learning_rate': 0.02702816788183442, 'dropout_rate': 0.44124671276745586, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.38254401959264994, 'max_features': 1, 'min_impurity_decrease': 0.0031143423876080715, 'validation_fraction': 0.9903409642142473, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6545064377682404
[I 2024-04-14 23:16:55,500] Trial 78 finished with value: 0.6992944115505685 and parameters: {'subsample': 0.22930387168853233, 'learning_rate': 0.05145553889741248, 'dropout_rate': 0.5044517635709308, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.24788146923782178, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010045782837561419, 'validation_fraction': 0.8244464183531952, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:17:21,373] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.5787844954317829, 'learning_rate': 0.046320469166095994, 'dropout_rate': 0.4903660577547442, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8369274241395267, 'min_weight_fraction_leaf': 0.3217471182217138, 'max_features': 'sqrt', 'min_impurity_decrease': 6.262467662262306e-05, 'validation_fraction': 0.822046932546052, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:17:36,328] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.6081624319156314, 'n_estimators': 427, 'criterion': 'friedman_mse', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.20197769506016003, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010150765068526006, 'validation_fraction': 0.7818118403834172, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:17:54,958] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.18443408707190798, 'learning_rate': 0.05259966681355033, 'dropout_rate': 0.6449369275082966, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23050623823206434, 'min_weight_fraction_leaf': 0.25144155938407586, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013502467549795782, 'validation_fraction': 0.8730600269587929, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:18:16,667] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.21084564139781542, 'learning_rate': 0.0557198718851306, 'dropout_rate': 0.5142046015087244, 'n_estimators': 464, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017868752517803354, 'min_weight_fraction_leaf': 0.22672177077398445, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00028049277519258663, 'validation_fraction': 0.9277470449701044, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:18:31,219] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.4945458790853893, 'learning_rate': 0.05895862835575055, 'dropout_rate': 0.7558273871774451, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.501498258850682, 'min_weight_fraction_leaf': 0.28306768635206997, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04144166385519717, 'validation_fraction': 0.8951513356732839, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 23:18:50,113] Trial 84 finished with value: 0.5444860535940432 and parameters: {'subsample': 0.3659778071469274, 'learning_rate': 0.0502270627847683, 'dropout_rate': 0.6818395627907664, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2606567709484204, 'min_weight_fraction_leaf': 0.2982881980338302, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006662326950079798, 'validation_fraction': 0.8368533116927852, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:19:06,563] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.26399210031385845, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.5847508382404618, 'n_estimators': 406, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9671659583078602, 'min_weight_fraction_leaf': 0.24391254579161395, 'max_features': 'log2', 'min_impurity_decrease': 0.000147849817010694, 'validation_fraction': 0.9991453937475061, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:19:08,705] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10060967717953817, 'learning_rate': 0.020768593047903114, 'dropout_rate': 0.4508818797021682, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.625182110561999, 'min_weight_fraction_leaf': 0.2761510567632799, 'max_features': 1, 'min_impurity_decrease': 0.0023479607608161597, 'validation_fraction': 0.7423283408922972, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5319148936170213
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 23:19:43,013] Trial 87 finished with value: 0.5635118483198402 and parameters: {'subsample': 0.43950121810340115, 'learning_rate': 0.0648732804536445, 'dropout_rate': 0.34957168713474945, 'n_estimators': 475, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2369430535237365, 'min_weight_fraction_leaf': 0.3096474641971687, 'max_features': 0.1, 'min_impurity_decrease': 4.850175263275894e-05, 'validation_fraction': 0.951557506428991, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:19:50,004] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.21193910478383937, 'learning_rate': 0.06177410341848358, 'dropout_rate': 0.8846843251251039, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.2807191828912141, 'min_weight_fraction_leaf': 0.36091713798964337, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0185550531810504e-05, 'validation_fraction': 0.8545724907452001, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:20:04,959] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.3182195088282702, 'learning_rate': 0.038485790496188235, 'dropout_rate': 0.5004748125823506, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5179293303896771, 'min_weight_fraction_leaf': 0.3315564489154308, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00046699939753012373, 'validation_fraction': 0.9294234431035183, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:20:23,502] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.2762755336662733, 'learning_rate': 0.05273046932737523, 'dropout_rate': 0.5437417743878508, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.8405822272736876, 'min_weight_fraction_leaf': 0.43576713073659407, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8767498848039622, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6459227467811158
[I 2024-04-14 23:20:37,821] Trial 91 finished with value: 0.6948185874130767 and parameters: {'subsample': 0.3126184078929269, 'learning_rate': 0.051134988454074756, 'dropout_rate': 0.7292690956696949, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03786277950879616, 'min_weight_fraction_leaf': 0.2673649069566119, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009910717111428719, 'validation_fraction': 0.7562406049799346, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6673819742489271
[I 2024-04-14 23:20:44,242] Trial 92 finished with value: 0.6989359122811389 and parameters: {'subsample': 0.335844111701364, 'learning_rate': 0.05038873458029908, 'dropout_rate': 0.9571283850291226, 'n_estimators': 449, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046820443269266425, 'min_weight_fraction_leaf': 0.2690679137012573, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0008839215080019705, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:20:50,858] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.33719220910486725, 'learning_rate': 0.05705464633480763, 'dropout_rate': 0.9535384595922254, 'n_estimators': 458, 'criterion': 'friedman_mse', 'ccp_alpha': 0.46107702292048336, 'min_weight_fraction_leaf': 0.21683645486742856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.862155169827754e-06, 'validation_fraction': 0.6649080237925696, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5665236051502146
[I 2024-04-14 23:20:55,303] Trial 94 finished with value: 0.5133047210300429 and parameters: {'subsample': 0.3795391698153348, 'learning_rate': 0.05424992354992036, 'dropout_rate': 0.998020448184449, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.25606469361498857, 'min_weight_fraction_leaf': 0.41683364220226815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002584853980433294, 'validation_fraction': 0.7006781615049952, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:21:01,323] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8984320859036168, 'learning_rate': 0.04600776760199582, 'dropout_rate': 0.9375007175299167, 'n_estimators': 432, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6620944039517677, 'min_weight_fraction_leaf': 0.25977850599919555, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001020092546254454, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:21:06,319] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.9444669238877774, 'learning_rate': 0.03476407177203711, 'dropout_rate': 0.9688789578178828, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5985394199987468, 'min_weight_fraction_leaf': 0.4570304925648464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009757952163430444, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:21:14,296] Trial 97 finished with value: 0.6983542268255716 and parameters: {'subsample': 0.40802503425948106, 'learning_rate': 0.060600248591443, 'dropout_rate': 0.8994280356510341, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.16755337346680707, 'min_weight_fraction_leaf': 0.24511190648995798, 'max_features': 'sqrt', 'min_impurity_decrease': 8.96572949971136e-05, 'validation_fraction': 0.627628127325836, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 23:21:20,731] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.40520020589260825, 'learning_rate': 0.06969431851683794, 'dropout_rate': 0.852867621588153, 'n_estimators': 377, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.23289524687485436, 'max_features': 'sqrt', 'min_impurity_decrease': 9.215043781245307e-05, 'validation_fraction': 0.6236577327109031, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-14 23:21:29,137] A new study created in memory with name: no-name-0a3431b7-d0f8-46a0-80cc-8a216291f6c9

Fold 5 C-index: 0.5
[I 2024-04-14 23:21:29,113] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.04234673286327711, 'dropout_rate': 0.8983226388952166, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.0709913910444209, 'min_weight_fraction_leaf': 0.25005718600704474, 'max_features': 'log2', 'min_impurity_decrease': 0.0001309255892076454, 'validation_fraction': 0.6560219357259244, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.


* Best trial for C-index:
 FrozenTrial(number=62, state=TrialState.COMPLETE, values=[0.712727180870049], datetime_start=datetime.datetime(2024, 4, 14, 23, 13, 41, 457396), datetime_complete=datetime.datetime(2024, 4, 14, 23, 13, 53, 808103), params={'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=62, value=None)


* Best Score for C-index:
 0.712727180870049

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:21:39,561] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:21:46,024] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:21:52,845] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:22:02,610] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:22:07,025] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:22:07,960] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:22:18,496] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:22:21,576] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:22:22,004] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24603560357944756
Fold 2 IBS: 0.2303451757578765
Fold 3 IBS: 0.22864210229423013
Fold 4 IBS: 0.24084923849388645
Fold 5 IBS: 0.22856534560034253
[I 2024-04-14 23:22:46,143] Trial 9 finished with value: 0.2348874931451566 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316595760132136
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-14 23:23:26,663] Trial 10 finished with value: 0.2356341548121131 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:24:09,092] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24715496002116139
Fold 2 IBS: 0.23184438819341896
Fold 3 IBS: 0.2289550256511867
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-14 23:24:42,648] Trial 12 finished with value: 0.23582687970453725 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:25:04,891] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:25:37,512] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:26:06,307] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:26:21,575] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:27:00,785] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:27:19,267] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:27:22,402] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:27:57,375] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24711009086064675
Fold 2 IBS: 0.23198651484788396
Fold 3 IBS: 0.22892152217671352
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-14 23:28:29,688] Trial 21 finished with value: 0.23582876076562656 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.2461444810014907
Fold 2 IBS: 0.2300302068927662
Fold 3 IBS: 0.22866943981867105

Fold 4 IBS: 0.24076805673249593
Fold 5 IBS: 0.2286244137483669
[I 2024-04-14 23:29:04,028] Trial 22 finished with value: 0.23484731963875816 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:29:33,322] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:29:49,953] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:30:09,713] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:30:35,248] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:30:37,970] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:30:46,293] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:31:10,746] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:31:20,342] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2469488707078328
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-14 23:31:48,627] Trial 31 finished with value: 0.23566408867478444 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2462866194872135
Fold 2 IBS: 0.23015814957230293
Fold 3 IBS: 0.22867627879341337
Fold 4 IBS: 0.24075894829353398
Fold 5 IBS: 0.22871397901804405
[I 2024-04-14 23:32:18,824] Trial 32 finished with value: 0.23491879503290156 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:32:39,867] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:33:05,990] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:33:12,641] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:33:44,204] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:33:45,154] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:34:01,936] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:34:18,128] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:34:33,342] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24665512418855506
Fold 2 IBS: 0.23079937875838777
Fold 3 IBS: 0.22859112956406855
Fold 4 IBS: 0.2411732320853091
Fold 5 IBS: 0.2289343835210694
[I 2024-04-14 23:34:57,923] Trial 41 finished with value: 0.23523064962347795 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24633993932293982
Fold 2 IBS: 0.23025272242517308
Fold 3 IBS: 0.22801274485299367
Fold 4 IBS: 0.24081637601730027
Fold 5 IBS: 0.22872083072116958
[I 2024-04-14 23:35:25,506] Trial 42 finished with value: 0.2348285226679153 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:35:53,135] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:36:15,510] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24693882344056556
Fold 2 IBS: 0.23145350422053343
Fold 3 IBS: 0.22860307836669258
Fold 4 IBS: 0.24146437703078477
Fold 5 IBS: 0.22909817747073397
[I 2024-04-14 23:36:35,499] Trial 45 finished with value: 0.23551159210586206 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:37:00,908] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:37:09,683] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:37:09,800] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:37:14,447] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:37:37,706] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24695366408679845
Fold 2 IBS: 0.23146997904187452
Fold 3 IBS: 0.2285885733926773
Fold 4 IBS: 0.24149615706388644
Fold 5 IBS: 0.22910431519663427
[I 2024-04-14 23:37:57,768] Trial 51 finished with value: 0.2355225377563742 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:38:22,157] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24641855308804925
Fold 2 IBS: 0.23048568622584525
Fold 3 IBS: 0.2278623120416157
Fold 4 IBS: 0.24068876716298668
Fold 5 IBS: 0.22857688144644517
[I 2024-04-14 23:38:41,536] Trial 53 finished with value: 0.2348064399929884 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:39:05,962] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:39:27,144] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:39:45,643] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:40:04,921] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:40:32,870] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:40:54,382] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:41:08,446] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:41:26,791] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2468810203480293
Fold 2 IBS: 0.2311990963376084
Fold 3 IBS: 0.228454108036685
Fold 4 IBS: 0.24124096112643856
Fold 5 IBS: 0.22895207624265332
[I 2024-04-14 23:41:40,595] Trial 62 finished with value: 0.23534545241828292 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:41:56,803] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2465043054793762
Fold 2 IBS: 0.23031643211780425
Fold 3 IBS: 0.2279578986949742
Fold 4 IBS: 0.24045858876874635
Fold 5 IBS: 0.22854526131961184
[I 2024-04-14 23:42:11,254] Trial 64 finished with value: 0.23475649727610257 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-14 23:42:26,159] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:42:40,086] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:42:48,981] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:43:13,031] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:43:30,909] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:43:45,695] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.2469128753364667
Fold 2 IBS: 0.23120680886119857
Fold 3 IBS: 0.2284490521729702
Fold 4 IBS: 0.2412928489959067
Fold 5 IBS: 0.22897078571077217
[I 2024-04-14 23:44:00,585] Trial 71 finished with value: 0.23536647421546286 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24699640897951017
Fold 2 IBS: 0.23151620221444727
Fold 3 IBS: 0.22861416387399014
Fold 4 IBS: 0.24155860571648258
Fold 5 IBS: 0.22912133061238216
[I 2024-04-14 23:44:11,132] Trial 72 finished with value: 0.23556134227936246 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:44:12,737] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:44:43,819] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:44:55,808] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:45:15,421] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:45:36,682] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:45:45,640] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:46:06,212] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:46:14,526] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24689956409794034
Fold 2 IBS: 0.23118732433711728
Fold 3 IBS: 0.22843302311048683
Fold 4 IBS: 0.24126338444926765
Fold 5 IBS: 0.22894778512748845
[I 2024-04-14 23:46:26,701] Trial 81 finished with value: 0.23534621622446011 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:46:39,547] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:47:05,570] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898150255235122
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293932698055425
[I 2024-04-14 23:47:15,692] Trial 84 finished with value: 0.23592730576033555 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24536364898371674
Fold 2 IBS: 0.22661035397022303
Fold 3 IBS: 0.226596757813156
Fold 4 IBS: 0.2389442424082662
Fold 5 IBS: 0.22754912881625142
[I 2024-04-14 23:47:35,889] Trial 85 finished with value: 0.23301282639832266 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:47:54,717] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8908016266221349, 'learning_rate': 0.020782252048892114, 'dropout_rate': 0.20248417164561996, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.025928909209021245, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:48:02,962] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953409887733455, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:48:25,026] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.0030671608519508686, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.27772784044341225, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:48:44,612] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9240076064991638, 'learning_rate': 0.036372907201929795, 'dropout_rate': 0.16604269499086277, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.6288732373244443, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.8456629128553931, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:49:05,413] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.22333957383529762, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24648485188041894
Fold 2 IBS: 0.2305073947731919
Fold 3 IBS: 0.22795134549192056
Fold 4 IBS: 0.24057179186781263
Fold 5 IBS: 0.22853359304710397
[I 2024-04-14 23:49:27,607] Trial 91 finished with value: 0.23480979541208963 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.01642165444052923, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.901410266511097, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:49:47,921] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.012238074680872561, 'dropout_rate': 0.2583752131981347, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 2.0262506829884978e-07, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:50:07,283] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9444060832329966, 'learning_rate': 0.017856303491279684, 'dropout_rate': 0.30303355573944185, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.011908761872398903, 'max_features': 'auto', 'min_impurity_decrease': 6.055732421263935e-07, 'validation_fraction': 0.864284511598723, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:50:23,510] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8821760782294449, 'learning_rate': 0.005785552173633914, 'dropout_rate': 0.28058975756978766, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.8506324992317083, 'min_weight_fraction_leaf': 0.04622694094641695, 'max_features': None, 'min_impurity_decrease': 1.3402986834437386e-07, 'validation_fraction': 0.8985100287316004, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:50:43,975] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9761707513926794, 'learning_rate': 0.019567902784876703, 'dropout_rate': 0.3201948574529592, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.0386964570043107, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9417888137501867, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24641425402466968
Fold 2 IBS: 0.22943554006463165
Fold 3 IBS: 0.22871680820224374
Fold 4 IBS: 0.24077011514188554
Fold 5 IBS: 0.22840019828947677
[I 2024-04-14 23:50:59,644] Trial 96 finished with value: 0.2347473831445815 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.01055205151962401, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.09708890262536518, 'max_features': 'auto', 'min_impurity_decrease': 3.7395479538673736e-07, 'validation_fraction': 0.992337544991608, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:51:16,699] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.010954886262406833, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 1.603167122698403, 'min_weight_fraction_leaf': 0.06013220413302209, 'max_features': 'auto', 'min_impurity_decrease': 3.972456306049239e-07, 'validation_fraction': 0.9976245698846969, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:51:29,212] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8505038223267275, 'learning_rate': 0.013402809510359784, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 0.25666428673598457, 'min_weight_fraction_leaf': 0.1129024126904408, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.9625603744870045, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:51:47,842] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.06808689488183181, 'dropout_rate': 0.25443633448028735, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5386043790221791, 'min_weight_fraction_leaf': 0.03403879613376609, 'max_features': 'auto', 'min_impurity_decrease': 8.69596280226011e-07, 'validation_fraction': 0.9221483446288596, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23301282639832266], datetime_start=datetime.datetime(2024, 4, 14, 23, 47, 15, 699823), datetime_complete=datetime.datetime(2024, 4, 14, 23, 47, 35, 889019), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23301282639832266

In [137]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [138]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.713
train_ibs:  0.233

#### Test

In [139]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [140]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.022737959076050005,
                                 dropout_rate=0.8285090704895912,
                                 learning_rate=0.0513322635401625, max_depth=2,
                                 max_features='sqrt', max_leaf_nodes=10,
                                 min_impurity_decrease=0.002070496973827786,
                                 min_samples_leaf=15, min_samples_split=19,
                                 min_weight_fraction_leaf=0.3101145382804477,
                                 n_estimators=485, random_state=123,
                                 subsample=0.45214538811231725,
                                 validation_fraction=0.9071319756271838)

C-index score: 0.532

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.229

In [141]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [142]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = StandardScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 23:51:53,347] A new study created in memory with name: no-name-ea06af8c-d35e-4141-82ab-615ba49aa515

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:51:53,651] Trial 0 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 23:51:56,328] Trial 1 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6249682148055231.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:51:56,822] Trial 2 finished with value: 0.6290789721738743 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6290789721738743.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:51:57,517] Trial 3 finished with value: 0.6329687040178604 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6329687040178604.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:51:58,618] Trial 4 finished with value: 0.6369347297362402 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6369347297362402.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:52:00,175] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6369347297362402.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 23:52:00,758] Trial 6 finished with value: 0.6223931075093858 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6369347297362402.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:52:00,881] Trial 7 finished with value: 0.6297198966721359 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6369347297362402.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:52:01,776] Trial 8 finished with value: 0.6265038648777369 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6369347297362402.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 23:52:03,835] Trial 9 finished with value: 0.6256454957790245 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6369347297362402.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:05,206] Trial 10 finished with value: 0.6414506485538027 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6414506485538027.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:52:06,801] Trial 11 finished with value: 0.6577884170507827 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6577884170507827.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:52:08,254] Trial 12 finished with value: 0.6585125168493072 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:10,097] Trial 13 finished with value: 0.6284016912003729 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:11,512] Trial 14 finished with value: 0.6520365375426744 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:12,898] Trial 15 finished with value: 0.6414870050290424 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 23:52:15,437] Trial 16 finished with value: 0.6534897330139029 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:18,427] Trial 17 finished with value: 0.6346238858655768 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:19,502] Trial 18 finished with value: 0.6322334476185649 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.6585125168493072.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:19,805] Trial 19 finished with value: 0.6488830367709311 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:22,361] Trial 20 finished with value: 0.6430737491011814 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 23:52:24,896] Trial 21 finished with value: 0.6535187842202175 and parameters: {'subsample': 0.19686631492543752, 'dropout_rate': 0.12395834975058428, 'n_estimators': 431, 'learning_rate': 0.09000255639604265}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:26,426] Trial 22 finished with value: 0.6484264180669019 and parameters: {'subsample': 0.18443217486865215, 'dropout_rate': 0.2970189594128161, 'n_estimators': 321, 'learning_rate': 0.09335998424883366}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:28,590] Trial 23 finished with value: 0.650236920901208 and parameters: {'subsample': 0.1529963084044875, 'dropout_rate': 0.1714923229584688, 'n_estimators': 392, 'learning_rate': 0.06498100052925637}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:31,289] Trial 24 finished with value: 0.6430953680517357 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.16550473543623023, 'n_estimators': 454, 'learning_rate': 0.0805167394906014}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:33,032] Trial 25 finished with value: 0.650099918363218 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.11261425324062513, 'n_estimators': 330, 'learning_rate': 0.09163056701298726}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:52:34,067] Trial 26 finished with value: 0.6274237903261579 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.4358710230551022, 'n_estimators': 256, 'learning_rate': 0.037893735810538676}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 23:52:35,161] Trial 27 finished with value: 0.6545068505879945 and parameters: {'subsample': 0.10030534830333891, 'dropout_rate': 0.9861686560685959, 'n_estimators': 294, 'learning_rate': 0.08000489021783491}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 23:52:36,401] Trial 28 finished with value: 0.6538370018702533 and parameters: {'subsample': 0.10146809971965022, 'dropout_rate': 0.8178252892822001, 'n_estimators': 290, 'learning_rate': 0.07770957646628725}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:52:37,192] Trial 29 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.5985349208985528, 'n_estimators': 215, 'learning_rate': 0.06046208382653473}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:52:38,124] Trial 30 finished with value: 0.626684953002948 and parameters: {'subsample': 0.6496340242271839, 'dropout_rate': 0.3577780272974884, 'n_estimators': 233, 'learning_rate': 0.06770814359693789}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:39,152] Trial 31 finished with value: 0.6519317432918571 and parameters: {'subsample': 0.10793925840929003, 'dropout_rate': 0.9925382852879747, 'n_estimators': 297, 'learning_rate': 0.07829470270101738}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:40,191] Trial 32 finished with value: 0.6438479682266837 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.8490702762086779, 'n_estimators': 287, 'learning_rate': 0.07216031707143393}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:52:41,378] Trial 33 finished with value: 0.653648481489282 and parameters: {'subsample': 0.10119572499894987, 'dropout_rate': 0.938709782637818, 'n_estimators': 335, 'learning_rate': 0.08080565390746011}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:42,316] Trial 34 finished with value: 0.6385240800593464 and parameters: {'subsample': 0.23419761201309758, 'dropout_rate': 0.7993569310296019, 'n_estimators': 280, 'learning_rate': 0.09351360578393325}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:52:42,588] Trial 35 finished with value: 0.628003158474711 and parameters: {'subsample': 0.29440822025230656, 'dropout_rate': 0.9999752027858236, 'n_estimators': 124, 'learning_rate': 0.07264491128155415}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:44,156] Trial 36 finished with value: 0.645535782204629 and parameters: {'subsample': 0.14727924050650143, 'dropout_rate': 0.7863675029157968, 'n_estimators': 385, 'learning_rate': 0.08463482868709953}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475

Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:44,647] Trial 37 finished with value: 0.6385093425346609 and parameters: {'subsample': 0.23671119278535047, 'dropout_rate': 0.5461106068967396, 'n_estimators': 166, 'learning_rate': 0.059207327336158105}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:52:45,814] Trial 38 finished with value: 0.6289447028736863 and parameters: {'subsample': 0.32943357291500935, 'dropout_rate': 0.9353840762852635, 'n_estimators': 340, 'learning_rate': 0.07288612365177065}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:52:46,603] Trial 39 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6100491404460081, 'dropout_rate': 0.6783966902571436, 'n_estimators': 245, 'learning_rate': 0.013931445007643331}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:52:46,720] Trial 40 finished with value: 0.6274601468013976 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.8298978392077205, 'n_estimators': 44, 'learning_rate': 0.045625495883289256}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:48,060] Trial 41 finished with value: 0.6527901123905696 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.9378678421534942, 'n_estimators': 347, 'learning_rate': 0.07742964930395986}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:49,065] Trial 42 finished with value: 0.6430875119529195 and parameters: {'subsample': 0.15805964805992748, 'dropout_rate': 0.9097990444488188, 'n_estimators': 279, 'learning_rate': 0.08178281126220367}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:50,138] Trial 43 finished with value: 0.6438295063569874 and parameters: {'subsample': 0.13840274528511398, 'dropout_rate': 0.8835966985352072, 'n_estimators': 316, 'learning_rate': 0.06775336106592025}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 23:52:50,189] Trial 44 finished with value: 0.6440143465468495 and parameters: {'subsample': 0.1896045974922743, 'dropout_rate': 0.9646462143965941, 'n_estimators': 3, 'learning_rate': 0.0963689949419925}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:52:51,576] Trial 45 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.7786324016427586, 'n_estimators': 362, 'learning_rate': 0.089155313391396}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:53,012] Trial 46 finished with value: 0.634587529390337 and parameters: {'subsample': 0.24853633714468593, 'dropout_rate': 0.9526685983356193, 'n_estimators': 397, 'learning_rate': 0.07635421514953118}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:52:54,218] Trial 47 finished with value: 0.64543414503467 and parameters: {'subsample': 0.1311305982000336, 'dropout_rate': 0.5056449253744388, 'n_estimators': 305, 'learning_rate': 0.05504528103546815}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:52:55,093] Trial 48 finished with value: 0.6506066563942251 and parameters: {'subsample': 0.10044152911408698, 'dropout_rate': 0.8976788837228983, 'n_estimators': 272, 'learning_rate': 0.08446047516076069}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:55,976] Trial 49 finished with value: 0.6501431562643267 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.20960059631780176, 'n_estimators': 234, 'learning_rate': 0.09862432275261226}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:52:56,464] Trial 50 finished with value: 0.6392845363331106 and parameters: {'subsample': 0.21684849615971696, 'dropout_rate': 0.633091953438621, 'n_estimators': 178, 'learning_rate': 0.0923360832084614}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:52:59,680] Trial 51 finished with value: 0.6446345990478639 and parameters: {'subsample': 0.18401478686425216, 'dropout_rate': 0.28032368655139484, 'n_estimators': 491, 'learning_rate': 0.08956287661931121}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:53:03,003] Trial 52 finished with value: 0.6536337439645967 and parameters: {'subsample': 0.13637380813559394, 'dropout_rate': 0.12420390200480337, 'n_estimators': 440, 'learning_rate': 0.0874811768906592}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:53:05,183] Trial 53 finished with value: 0.6527143693460669 and parameters: {'subsample': 0.12235314965386802, 'dropout_rate': 0.1414997888592217, 'n_estimators': 372, 'learning_rate': 0.08152773384700819}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:07,136] Trial 54 finished with value: 0.6509757582244179 and parameters: {'subsample': 0.14932713692245705, 'dropout_rate': 0.20342812979572866, 'n_estimators': 345, 'learning_rate': 0.09559753486488298}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:53:09,323] Trial 55 finished with value: 0.6314477914703318 and parameters: {'subsample': 0.5460014539035196, 'dropout_rate': 0.15105403923216587, 'n_estimators': 322, 'learning_rate': 0.06485931104972373}. Best is trial 12 with value: 0.6585125168493072.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:53:11,757] Trial 56 finished with value: 0.6337291602916246 and parameters: {'subsample': 0.269378251951114, 'dropout_rate': 0.7454692460426802, 'n_estimators': 459, 'learning_rate': 0.08683391151256231}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:14,267] Trial 57 finished with value: 0.6502190262956644 and parameters: {'subsample': 0.17511701109487357, 'dropout_rate': 0.19707928395816876, 'n_estimators': 404, 'learning_rate': 0.0997291184079334}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:53:16,369] Trial 58 finished with value: 0.6525845450901674 and parameters: {'subsample': 0.21811121828623398, 'dropout_rate': 0.10187905549888307, 'n_estimators': 376, 'learning_rate': 0.08057529760073802}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:53:18,782] Trial 59 finished with value: 0.6476691188739958 and parameters: {'subsample': 0.13471366354051, 'dropout_rate': 0.43567601386873406, 'n_estimators': 444, 'learning_rate': 0.08701040020718107}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:53:19,499] Trial 60 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.9718433307655755, 'dropout_rate': 0.2783974854001528, 'n_estimators': 212, 'learning_rate': 0.0702127076864379}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:53:22,052] Trial 61 finished with value: 0.652660415121505 and parameters: {'subsample': 0.1948241216656475, 'dropout_rate': 0.12666752739579462, 'n_estimators': 435, 'learning_rate': 0.09028916130100588}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:53:25,076] Trial 62 finished with value: 0.6561405404719916 and parameters: {'subsample': 0.12353028919244316, 'dropout_rate': 0.14493060385923506, 'n_estimators': 467, 'learning_rate': 0.07585930251899534}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:28,080] Trial 63 finished with value: 0.6527684934400153 and parameters: {'subsample': 0.1308716913944263, 'dropout_rate': 0.16476602500283072, 'n_estimators': 471, 'learning_rate': 0.077827285822208}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:29,412] Trial 64 finished with value: 0.6520839071975886 and parameters: {'subsample': 0.10197413109462203, 'dropout_rate': 0.23556866709681284, 'n_estimators': 294, 'learning_rate': 0.08447359488201481}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:32,529] Trial 65 finished with value: 0.6501610508698704 and parameters: {'subsample': 0.16031747566028584, 'dropout_rate': 0.14120585858603804, 'n_estimators': 487, 'learning_rate': 0.07495311987084312}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:53:33,724] Trial 66 finished with value: 0.6492411254214494 and parameters: {'subsample': 0.12923552153873363, 'dropout_rate': 0.9690763216266052, 'n_estimators': 330, 'learning_rate': 0.06477950661604888}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:53:35,134] Trial 67 finished with value: 0.636174273462476 and parameters: {'subsample': 0.29956950761207946, 'dropout_rate': 0.34310328978504323, 'n_estimators': 264, 'learning_rate': 0.09473793944277918}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:53:36,362] Trial 68 finished with value: 0.6407118112305928 and parameters: {'subsample': 0.16655085936657832, 'dropout_rate': 0.8646861201169278, 'n_estimators': 307, 'learning_rate': 0.0267624773650322}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:53:37,910] Trial 69 finished with value: 0.6386219928842946 and parameters: {'subsample': 0.23680904710386677, 'dropout_rate': 0.8249474453710187, 'n_estimators': 355, 'learning_rate': 0.08099966706697827}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 23:53:40,167] Trial 70 finished with value: 0.6503969573400172 and parameters: {'subsample': 0.20056066571123762, 'dropout_rate': 0.1806794570956778, 'n_estimators': 408, 'learning_rate': 0.07503629044987359}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:42,693] Trial 71 finished with value: 0.6551620887678853 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.124033178596248, 'n_estimators': 427, 'learning_rate': 0.09080295600163082}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:53:45,774] Trial 72 finished with value: 0.6528044260721988 and parameters: {'subsample': 0.10337294841246229, 'dropout_rate': 0.13382572716109742, 'n_estimators': 479, 'learning_rate': 0.09099776905867352}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:48,541] Trial 73 finished with value: 0.6567635703647097 and parameters: {'subsample': 0.13375269605779172, 'dropout_rate': 0.10495942741643126, 'n_estimators': 446, 'learning_rate': 0.08385778058355023}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327

Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:50,968] Trial 74 finished with value: 0.6544094885929373 and parameters: {'subsample': 0.12316897094831497, 'dropout_rate': 0.18290930559198426, 'n_estimators': 419, 'learning_rate': 0.0836832834283662}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 23:53:53,805] Trial 75 finished with value: 0.6536341678076528 and parameters: {'subsample': 0.17743719973326125, 'dropout_rate': 0.10348545302264188, 'n_estimators': 458, 'learning_rate': 0.08511821040915617}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:56,453] Trial 76 finished with value: 0.6501610508698704 and parameters: {'subsample': 0.1562376737154374, 'dropout_rate': 0.2211948317756653, 'n_estimators': 425, 'learning_rate': 0.09670643878877244}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:53:58,862] Trial 77 finished with value: 0.6299988976222952 and parameters: {'subsample': 0.5161835623943133, 'dropout_rate': 0.18774676638069343, 'n_estimators': 413, 'learning_rate': 0.07019177645564464}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:54:02,387] Trial 78 finished with value: 0.6544311075434918 and parameters: {'subsample': 0.12380704786315203, 'dropout_rate': 0.16805986674852408, 'n_estimators': 472, 'learning_rate': 0.07877013778290308}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:54:06,254] Trial 79 finished with value: 0.6486838000665067 and parameters: {'subsample': 0.21364076997332287, 'dropout_rate': 0.16177532623781637, 'n_estimators': 468, 'learning_rate': 0.09294115164305988}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:54:09,594] Trial 80 finished with value: 0.6346238858655768 and parameters: {'subsample': 0.3259883854692743, 'dropout_rate': 0.2621274848541858, 'n_estimators': 496, 'learning_rate': 0.08307125062030996}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:54:12,110] Trial 81 finished with value: 0.6510952899999205 and parameters: {'subsample': 0.11767695041801506, 'dropout_rate': 0.3146227522093246, 'n_estimators': 446, 'learning_rate': 0.07907996916728055}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:54:14,075] Trial 82 finished with value: 0.6330197980177854 and parameters: {'subsample': 0.5872419871305887, 'dropout_rate': 0.15411074306118955, 'n_estimators': 382, 'learning_rate': 0.08357996781238416}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 23:54:17,290] Trial 83 finished with value: 0.6577809847950226 and parameters: {'subsample': 0.12829175664866302, 'dropout_rate': 0.10231710883953246, 'n_estimators': 479, 'learning_rate': 0.08856658818137675}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:54:20,246] Trial 84 finished with value: 0.6544236752877317 and parameters: {'subsample': 0.164030782336198, 'dropout_rate': 0.10230069284548952, 'n_estimators': 462, 'learning_rate': 0.08851376785226907}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:54:23,291] Trial 85 finished with value: 0.6510048094307324 and parameters: {'subsample': 0.16423543283142095, 'dropout_rate': 0.11796140787838225, 'n_estimators': 481, 'learning_rate': 0.08837196724579871}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 23:54:28,987] Trial 86 finished with value: 0.6535260894891426 and parameters: {'subsample': 0.2468654975608167, 'dropout_rate': 0.10103591217022476, 'n_estimators': 500, 'learning_rate': 0.0916673824323084}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:54:33,678] Trial 87 finished with value: 0.6534751224760524 and parameters: {'subsample': 0.15150670375911485, 'dropout_rate': 0.13961149432854167, 'n_estimators': 460, 'learning_rate': 0.096792544720343}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:54:36,654] Trial 88 finished with value: 0.6461666681961635 and parameters: {'subsample': 0.2088872651501132, 'dropout_rate': 0.2181010773924792, 'n_estimators': 451, 'learning_rate': 0.09425970178006793}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:54:40,833] Trial 89 finished with value: 0.6360763606375278 and parameters: {'subsample': 0.4199800608496284, 'dropout_rate': 0.16689331308725722, 'n_estimators': 484, 'learning_rate': 0.08933361605371407}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:54:44,379] Trial 90 finished with value: 0.6353669983636887 and parameters: {'subsample': 0.7147405584008215, 'dropout_rate': 0.12262034913438008, 'n_estimators': 466, 'learning_rate': 0.0870043653226492}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:54:46,972] Trial 91 finished with value: 0.6536342947944878 and parameters: {'subsample': 0.12390846758748335, 'dropout_rate': 0.18403186398286386, 'n_estimators': 427, 'learning_rate': 0.08287082106393794}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:54:49,586] Trial 92 finished with value: 0.6560573651717286 and parameters: {'subsample': 0.11981517826326402, 'dropout_rate': 0.14878509209900664, 'n_estimators': 434, 'learning_rate': 0.07943364992805321}. Best is trial 12 with value: 0.6585125168493072.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 23:54:52,276] Trial 93 finished with value: 0.6519320401480785 and parameters: {'subsample': 0.14686353423359538, 'dropout_rate': 0.14801671599090324, 'n_estimators': 434, 'learning_rate': 0.07949677164681694}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:54:55,593] Trial 94 finished with value: 0.6487454834030502 and parameters: {'subsample': 0.18112694385158684, 'dropout_rate': 0.1260789509040807, 'n_estimators': 477, 'learning_rate': 0.07554145938994386}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:54:57,629] Trial 95 finished with value: 0.6313966974704068 and parameters: {'subsample': 0.45973163997667565, 'dropout_rate': 0.2415344805411671, 'n_estimators': 400, 'learning_rate': 0.09751969757071219}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:55:00,096] Trial 96 finished with value: 0.6470493894832323 and parameters: {'subsample': 0.1370770905956337, 'dropout_rate': 0.593760388208773, 'n_estimators': 443, 'learning_rate': 0.08579936903513066}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 23:55:02,613] Trial 97 finished with value: 0.6510952899999205 and parameters: {'subsample': 0.11842111322304441, 'dropout_rate': 0.40046353052491246, 'n_estimators': 390, 'learning_rate': 0.07297901010354857}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:55:05,582] Trial 98 finished with value: 0.6517546763678783 and parameters: {'subsample': 0.1705019943747379, 'dropout_rate': 0.2002801186536965, 'n_estimators': 455, 'learning_rate': 0.09243727934231369}. Best is trial 12 with value: 0.6585125168493072.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772

[I 2024-04-14 23:55:08,520] A new study created in memory with name: no-name-dc8f6c8f-ca2c-44c4-9b07-c6182e4f23fd

Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:55:08,512] Trial 99 finished with value: 0.6283800722498184 and parameters: {'subsample': 0.9104218782867626, 'dropout_rate': 0.10171564973687436, 'n_estimators': 470, 'learning_rate': 0.052443959168945425}. Best is trial 12 with value: 0.6585125168493072.


* Best trial for C-index:
 FrozenTrial(number=12, state=TrialState.COMPLETE, values=[0.6585125168493072], datetime_start=datetime.datetime(2024, 4, 14, 23, 52, 6, 803318), datetime_complete=datetime.datetime(2024, 4, 14, 23, 52, 8, 254194), params={'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=12, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}


* Best Score for C-index:
 0.6585125168493072

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.325676523044078
Fold 2 IBS: 0.24304825871263852
Fold 3 IBS: 0.32959725402563417
Fold 4 IBS: 0.28525857993950676
Fold 5 IBS: 0.27275166189156874
[I 2024-04-14 23:55:08,850] Trial 0 finished with value: 0.29126645552268526 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4243468471583305
Fold 2 IBS: 0.3901688969230736
Fold 3 IBS: 0.3925037735733181
Fold 4 IBS: 0.37084045783124014
Fold 5 IBS: 0.34079939992495495
[I 2024-04-14 23:55:11,637] Trial 1 finished with value: 0.3837318750821835 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.388663470563614
Fold 2 IBS: 0.29938754993978567
Fold 3 IBS: 0.37991021668413694
Fold 4 IBS: 0.31125225156593306
Fold 5 IBS: 0.33025000236569196
[I 2024-04-14 23:55:12,150] Trial 2 finished with value: 0.34189269822383234 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.39180502103928067
Fold 2 IBS: 0.2712652024903501
Fold 3 IBS: 0.3810564835553453
Fold 4 IBS: 0.31083880707894046
Fold 5 IBS: 0.32302330983004995
[I 2024-04-14 23:55:12,956] Trial 3 finished with value: 0.3355977647987933 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.3942661310659211
Fold 2 IBS: 0.2808391971731164
Fold 3 IBS: 0.38335597155037054
Fold 4 IBS: 0.309678688625878
Fold 5 IBS: 0.3380956170278929
[I 2024-04-14 23:55:14,243] Trial 4 finished with value: 0.3412471210886358 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.4122519263817958
Fold 2 IBS: 0.37802969684822957
Fold 3 IBS: 0.39159093324564376
Fold 4 IBS: 0.3474683993736778
Fold 5 IBS: 0.331005424885477
[I 2024-04-14 23:55:15,718] Trial 5 finished with value: 0.3720692761469648 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.29126645552268526.
Fold 1 IBS: 0.29828726911528397
Fold 2 IBS: 0.21645133017694293
Fold 3 IBS: 0.29703048020856426
Fold 4 IBS: 0.2630471709724218
Fold 5 IBS: 0.24865969387198464
[I 2024-04-14 23:55:16,325] Trial 6 finished with value: 0.26469518886903953 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.26469518886903953.
Fold 1 IBS: 0.2557242083039886
Fold 2 IBS: 0.2015394183272912
Fold 3 IBS: 0.2559954533104581
Fold 4 IBS: 0.22842064037634063
Fold 5 IBS: 0.21078271864122022
[I 2024-04-14 23:55:16,446] Trial 7 finished with value: 0.2304924877918598 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.3320623714087893
Fold 2 IBS: 0.24778879382834276
Fold 3 IBS: 0.33914263875054795
Fold 4 IBS: 0.28890146090534946
Fold 5 IBS: 0.2812784361061495
[I 2024-04-14 23:55:17,120] Trial 8 finished with value: 0.2978347401998358 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.41355256605441043
Fold 2 IBS: 0.3803418251430308
Fold 3 IBS: 0.391840649836237
Fold 4 IBS: 0.35131804113613163
Fold 5 IBS: 0.3420174736572878
[I 2024-04-14 23:55:19,321] Trial 9 finished with value: 0.3758141111654195 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.24688672048424357
Fold 2 IBS: 0.23091253666135533
Fold 3 IBS: 0.22886383485395365
Fold 4 IBS: 0.2411627533361748
Fold 5 IBS: 0.22809345046771862
[I 2024-04-14 23:55:19,425] Trial 10 finished with value: 0.23518385916068918 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.24591184955753378
Fold 2 IBS: 0.22742364641206644
Fold 3 IBS: 0.22872479609872584
Fold 4 IBS: 0.23866162133190572
Fold 5 IBS: 0.22419206168941844
[I 2024-04-14 23:55:19,492] Trial 11 finished with value: 0.23298279501793004 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.2794662292785159
Fold 2 IBS: 0.2115268634179246
Fold 3 IBS: 0.29739289360650867
Fold 4 IBS: 0.2578240047532265
Fold 5 IBS: 0.24036670243462674
[I 2024-04-14 23:55:19,662] Trial 12 finished with value: 0.2573153386981605 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.24533484626464844
Fold 2 IBS: 0.22482603295491327
Fold 3 IBS: 0.2288900501286023
Fold 4 IBS: 0.2368692484235475
Fold 5 IBS: 0.22138571816323843
[I 2024-04-14 23:55:19,736] Trial 13 finished with value: 0.23146117918699 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.2838507400334174
Fold 2 IBS: 0.20611142919119801
Fold 3 IBS: 0.2862860280530503
Fold 4 IBS: 0.24790860860459804
Fold 5 IBS: 0.23314936884966506
[I 2024-04-14 23:55:20,027] Trial 14 finished with value: 0.2514612349463858 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.35006944344323987
Fold 2 IBS: 0.25456378467953805
Fold 3 IBS: 0.35764903579940016
Fold 4 IBS: 0.2961404203062488
Fold 5 IBS: 0.30092599232489686
[I 2024-04-14 23:55:20,370] Trial 15 finished with value: 0.31186973531066475 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.3578186240090688
Fold 2 IBS: 0.24514275845342567
Fold 3 IBS: 0.3594234429296754
Fold 4 IBS: 0.2871537665225233
Fold 5 IBS: 0.3078085049478534
[I 2024-04-14 23:55:21,823] Trial 16 finished with value: 0.31146941937250927 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.2304924877918598.
Fold 1 IBS: 0.24637560220536686
Fold 2 IBS: 0.21110503456978988
Fold 3 IBS: 0.23491938690940084
Fold 4 IBS: 0.22943718629070567
Fold 5 IBS: 0.21121348311812857
[I 2024-04-14 23:55:22,022] Trial 17 finished with value: 0.22661013861867835 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.291291305025286
Fold 2 IBS: 0.21140388138900232
Fold 3 IBS: 0.28863212236387226
Fold 4 IBS: 0.2563863518782749
Fold 5 IBS: 0.24311757382074356
[I 2024-04-14 23:55:23,652] Trial 18 finished with value: 0.2581662468954358 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2734286915536386
Fold 2 IBS: 0.20081443107830507

Fold 3 IBS: 0.2756019255493613
Fold 4 IBS: 0.2426706185564074
Fold 5 IBS: 0.22283081379821795
[I 2024-04-14 23:55:24,016] Trial 19 finished with value: 0.24306929610718608 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24550608887605468
Fold 2 IBS: 0.2133505584021398
Fold 3 IBS: 0.23294747738469943
Fold 4 IBS: 0.23024731593258208
Fold 5 IBS: 0.2123372739360029
[I 2024-04-14 23:55:24,184] Trial 20 finished with value: 0.22687774290629575 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448259892509062
Fold 2 IBS: 0.21786672573833757
Fold 3 IBS: 0.23050391968540718
Fold 4 IBS: 0.23249100529840805
Fold 5 IBS: 0.215533050087791
[I 2024-04-14 23:55:24,344] Trial 21 finished with value: 0.22824413801216997 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24640086873642586
Fold 2 IBS: 0.2292326597688009
Fold 3 IBS: 0.22875342577755223
Fold 4 IBS: 0.23993607277337323
Fold 5 IBS: 0.22642423701728293
[I 2024-04-14 23:55:24,532] Trial 22 finished with value: 0.23414945281468702 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2589848196302069
Fold 2 IBS: 0.2024618720492697
Fold 3 IBS: 0.25302707950360914
Fold 4 IBS: 0.23227378691244918
Fold 5 IBS: 0.21704698047063445
[I 2024-04-14 23:55:24,918] Trial 23 finished with value: 0.23275890771323388 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24622272418585897
Fold 2 IBS: 0.211517231301511
Fold 3 IBS: 0.23465708353277137
Fold 4 IBS: 0.22958311755255775
Fold 5 IBS: 0.21133338172755428
[I 2024-04-14 23:55:25,077] Trial 24 finished with value: 0.2266627076600507 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.27824402320018216
Fold 2 IBS: 0.20485085384499563
Fold 3 IBS: 0.2745783058664053
Fold 4 IBS: 0.24546543206826768
Fold 5 IBS: 0.23263373515357302
[I 2024-04-14 23:55:25,452] Trial 25 finished with value: 0.24715447002668472 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.33014689072398445
Fold 2 IBS: 0.24720038348309642
Fold 3 IBS: 0.3344515997942725
Fold 4 IBS: 0.28780550809923416
Fold 5 IBS: 0.2783585358589275
[I 2024-04-14 23:55:26,064] Trial 26 finished with value: 0.295592583591903 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24499219484414198
Fold 2 IBS: 0.21624851273382031
Fold 3 IBS: 0.2314723911058174
Fold 4 IBS: 0.23142113333280664
Fold 5 IBS: 0.21391217014232608
[I 2024-04-14 23:55:26,176] Trial 27 finished with value: 0.2276092804317825 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24515366399581964
Fold 2 IBS: 0.21501049991641955
Fold 3 IBS: 0.23211607481589766
Fold 4 IBS: 0.23087262715339726
Fold 5 IBS: 0.2134002972589192
[I 2024-04-14 23:55:26,390] Trial 28 finished with value: 0.22731063262809065 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3063594897860022
Fold 2 IBS: 0.22365458368515215
Fold 3 IBS: 0.3055669075377605
Fold 4 IBS: 0.2699993099904004
Fold 5 IBS: 0.25609676833722445
[I 2024-04-14 23:55:26,706] Trial 29 finished with value: 0.2723354118673079 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.3037100708108595
Fold 2 IBS: 0.22137743897919782
Fold 3 IBS: 0.3028696552655383
Fold 4 IBS: 0.2673327822795468
Fold 5 IBS: 0.253763234707761
[I 2024-04-14 23:55:27,238] Trial 30 finished with value: 0.2698106364085807 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2449141797735416
Fold 2 IBS: 0.21676885376764835
Fold 3 IBS: 0.23117242159093349
Fold 4 IBS: 0.2319218743035483
Fold 5 IBS: 0.2146636746811494
[I 2024-04-14 23:55:27,471] Trial 31 finished with value: 0.2278882008233642 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24480968404806477
Fold 2 IBS: 0.21840173072243738
Fold 3 IBS: 0.2303084891481403
Fold 4 IBS: 0.23294002575148984
Fold 5 IBS: 0.21611746639599275
[I 2024-04-14 23:55:27,600] Trial 32 finished with value: 0.22851547921322504 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24444290623218176
Fold 2 IBS: 0.22003318344553727
Fold 3 IBS: 0.23004295934041907
Fold 4 IBS: 0.23318439942131822
Fold 5 IBS: 0.21729227081764876
[I 2024-04-14 23:55:27,801] Trial 33 finished with value: 0.228999143851421 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2599735862383478
Fold 2 IBS: 0.20223791307592695
Fold 3 IBS: 0.25497930340177116
Fold 4 IBS: 0.23208609347398076
Fold 5 IBS: 0.2141781691601287
[I 2024-04-14 23:55:28,132] Trial 34 finished with value: 0.2326910130700311 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24663201725543496
Fold 2 IBS: 0.2300001255908101
Fold 3 IBS: 0.22880051556212538
Fold 4 IBS: 0.2405667786146309
Fold 5 IBS: 0.2271226637337803
[I 2024-04-14 23:55:28,226] Trial 35 finished with value: 0.23462442015135632 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.367577937922695
Fold 2 IBS: 0.27682015096192025
Fold 3 IBS: 0.3682948275396474
Fold 4 IBS: 0.30452048859388936
Fold 5 IBS: 0.31541637422362634
[I 2024-04-14 23:55:30,817] Trial 36 finished with value: 0.32652595584835564 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.39841893189624056
Fold 2 IBS: 0.3203475398759217
Fold 3 IBS: 0.3852983569562301
Fold 4 IBS: 0.31620276009532605
Fold 5 IBS: 0.33770453446230725
[I 2024-04-14 23:55:31,602] Trial 37 finished with value: 0.35159442465720514 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2614340968260537
Fold 2 IBS: 0.2021120088730102

Fold 3 IBS: 0.2566141669263308
Fold 4 IBS: 0.23453614765450895
Fold 5 IBS: 0.2122914778844625
[I 2024-04-14 23:55:32,325] Trial 38 finished with value: 0.2333975796328732 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2943463281154152
Fold 2 IBS: 0.21435275898375683
Fold 3 IBS: 0.292776623523439
Fold 4 IBS: 0.2606234117164125
Fold 5 IBS: 0.24191548716779984
[I 2024-04-14 23:55:32,517] Trial 39 finished with value: 0.26080292190136467 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2956705905294083
Fold 2 IBS: 0.21430445848659016
Fold 3 IBS: 0.2928588854990794
Fold 4 IBS: 0.2596622123064148
Fold 5 IBS: 0.24678618384472736
[I 2024-04-14 23:55:32,876] Trial 40 finished with value: 0.261856466133244 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2455156591195911
Fold 2 IBS: 0.2134495272871624
Fold 3 IBS: 0.23298021917302758
Fold 4 IBS: 0.2302623346190742
Fold 5 IBS: 0.21228868131417766
[I 2024-04-14 23:55:33,073] Trial 41 finished with value: 0.22689928430260659 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2448957834513211
Fold 2 IBS: 0.2170005935741622
Fold 3 IBS: 0.2310161992206827
Fold 4 IBS: 0.23202460062538527
Fold 5 IBS: 0.21439769364800865
[I 2024-04-14 23:55:33,234] Trial 42 finished with value: 0.22786697410391196 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2658273736705565
Fold 2 IBS: 0.2020524405250075
Fold 3 IBS: 0.2606080098559383
Fold 4 IBS: 0.23638269291325226
Fold 5 IBS: 0.2218591947364019
[I 2024-04-14 23:55:33,504] Trial 43 finished with value: 0.23734594234023126 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24553832608292522
Fold 2 IBS: 0.22567851914167422
Fold 3 IBS: 0.22880097138904068
Fold 4 IBS: 0.23740161794197437
Fold 5 IBS: 0.22252686111769712
[I 2024-04-14 23:55:33,700] Trial 44 finished with value: 0.2319892591346623 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24514475725184326
Fold 2 IBS: 0.2232932452954966
Fold 3 IBS: 0.229031285656079
Fold 4 IBS: 0.23565641281785177
Fold 5 IBS: 0.2206722434927271
[I 2024-04-14 23:55:33,836] Trial 45 finished with value: 0.23075958890279952 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.34556775223404884
Fold 2 IBS: 0.26003024903765853
Fold 3 IBS: 0.35086044091810686
Fold 4 IBS: 0.29629520252719266
Fold 5 IBS: 0.2940333944770714
[I 2024-04-14 23:55:34,342] Trial 46 finished with value: 0.30935740783881566 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2540323022244742
Fold 2 IBS: 0.19752261275642008
Fold 3 IBS: 0.25415324167744757
Fold 4 IBS: 0.22627491702741187
Fold 5 IBS: 0.2109899988311474
[I 2024-04-14 23:55:34,589] Trial 47 finished with value: 0.22859461450338023 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.25728763936252025
Fold 2 IBS: 0.20231216512367317
Fold 3 IBS: 0.25262795298766366
Fold 4 IBS: 0.23138017803988314
Fold 5 IBS: 0.21120324156934484
[I 2024-04-14 23:55:35,385] Trial 48 finished with value: 0.23096223541661703 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24673307008984274
Fold 2 IBS: 0.23042055290160676
Fold 3 IBS: 0.22882596707663166
Fold 4 IBS: 0.2408186354309607
Fold 5 IBS: 0.22754159795832032
[I 2024-04-14 23:55:35,463] Trial 49 finished with value: 0.23486796469147248 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2703393986257053
Fold 2 IBS: 0.20257051463406026
Fold 3 IBS: 0.2660776078398826
Fold 4 IBS: 0.23954054354969337
Fold 5 IBS: 0.22554209413235315
[I 2024-04-14 23:55:35,869] Trial 50 finished with value: 0.24081403175633892 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24526003850914455
Fold 2 IBS: 0.21467902770255018
Fold 3 IBS: 0.23231863109009884
Fold 4 IBS: 0.23070537111335643
Fold 5 IBS: 0.2129056406944009
[I 2024-04-14 23:55:36,023] Trial 51 finished with value: 0.2271737418219102 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2465932017623929
Fold 2 IBS: 0.2299268996974446
Fold 3 IBS: 0.22878875620635092
Fold 4 IBS: 0.24043322363238803
Fold 5 IBS: 0.22699010755245638
[I 2024-04-14 23:55:36,221] Trial 52 finished with value: 0.23454643777020653 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24483084636350344
Fold 2 IBS: 0.21994268306656278
Fold 3 IBS: 0.2298159042727
Fold 4 IBS: 0.23377868427496837
Fold 5 IBS: 0.217018869345563
[I 2024-04-14 23:55:36,378] Trial 53 finished with value: 0.22907739746465952 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2542837578406007
Fold 2 IBS: 0.20408105962436318
Fold 3 IBS: 0.24632166462762337
Fold 4 IBS: 0.2299345290491981
Fold 5 IBS: 0.20927255603620012
[I 2024-04-14 23:55:36,488] Trial 54 finished with value: 0.2287787134355971 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.2534849870495454
Fold 2 IBS: 0.2041508121560885
Fold 3 IBS: 0.24576477799133983
Fold 4 IBS: 0.22971527127754243
Fold 5 IBS: 0.21306295114857882
[I 2024-04-14 23:55:36,769] Trial 55 finished with value: 0.229235759924619 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.22661013861867835.
Fold 1 IBS: 0.24660568247659428
Fold 2 IBS: 0.21064080007395522
Fold 3 IBS: 0.23535116446600424
Fold 4 IBS: 0.22928161830063465
Fold 5 IBS: 0.21108618854351036
[I 2024-04-14 23:55:36,926] Trial 56 finished with value: 0.22659309077213977 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.32634594317205234
Fold 2 IBS: 0.2441074249846434
Fold 3 IBS: 0.33090013102352434
Fold 4 IBS: 0.28596472610806994

Fold 5 IBS: 0.27461860801929316
[I 2024-04-14 23:55:37,874] Trial 57 finished with value: 0.29238736666151666 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2524958013314946
Fold 2 IBS: 0.20467957580837548
Fold 3 IBS: 0.24466604990129345
Fold 4 IBS: 0.22951388023914565
Fold 5 IBS: 0.21232254648299242
[I 2024-04-14 23:55:38,023] Trial 58 finished with value: 0.22873557075266032 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2450766728615442
Fold 2 IBS: 0.21570571438138603
Fold 3 IBS: 0.23170031253784298
Fold 4 IBS: 0.23100841297079955
Fold 5 IBS: 0.21387190006582926
[I 2024-04-14 23:55:38,122] Trial 59 finished with value: 0.2274726025634804 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2799925625848654
Fold 2 IBS: 0.20541721127231735
Fold 3 IBS: 0.27641891339421315
Fold 4 IBS: 0.24728738758668545
Fold 5 IBS: 0.231501204035336
[I 2024-04-14 23:55:38,456] Trial 60 finished with value: 0.24812345577468348 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24506114552036967
Fold 2 IBS: 0.2227391563952413
Fold 3 IBS: 0.22917592951399726
Fold 4 IBS: 0.23541036546351077
Fold 5 IBS: 0.21951860445014307
[I 2024-04-14 23:55:38,662] Trial 61 finished with value: 0.23038104026865242 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.25624845596017926
Fold 2 IBS: 0.2031140844165004
Fold 3 IBS: 0.24945076411968525
Fold 4 IBS: 0.2308386419236711
Fold 5 IBS: 0.21467054375030795
[I 2024-04-14 23:55:38,919] Trial 62 finished with value: 0.23086449803406878 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24525813986654407
Fold 2 IBS: 0.22394706204039122
Fold 3 IBS: 0.22893913491420798
Fold 4 IBS: 0.23632535189099202
Fold 5 IBS: 0.2214331425247103
[I 2024-04-14 23:55:39,031] Trial 63 finished with value: 0.2311805662473691 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2456393866366244
Fold 2 IBS: 0.21299153169174545
Fold 3 IBS: 0.23361997509095692
Fold 4 IBS: 0.22975030626215406
Fold 5 IBS: 0.21253431380250287
[I 2024-04-14 23:55:39,195] Trial 64 finished with value: 0.22690710269679676 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24436030005286818
Fold 2 IBS: 0.21456927917072746
Fold 3 IBS: 0.23251529067371102
Fold 4 IBS: 0.23061435502797772
Fold 5 IBS: 0.21371928695614437
[I 2024-04-14 23:55:39,357] Trial 65 finished with value: 0.22715570237628574 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24425791895146917
Fold 2 IBS: 0.2144102132061209
Fold 3 IBS: 0.2326749313963326
Fold 4 IBS: 0.23050958085920942
Fold 5 IBS: 0.213580757387187
[I 2024-04-14 23:55:39,519] Trial 66 finished with value: 0.22708668036006383 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.30111629951862323
Fold 2 IBS: 0.22040932376290737
Fold 3 IBS: 0.3017744714900754
Fold 4 IBS: 0.2662157921914366
Fold 5 IBS: 0.24893153605233173
[I 2024-04-14 23:55:40,603] Trial 67 finished with value: 0.26768948460307485 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.37509937493932133
Fold 2 IBS: 0.28344081600106874
Fold 3 IBS: 0.3742704223614346
Fold 4 IBS: 0.3062111301277816
Fold 5 IBS: 0.32272587873763087
[I 2024-04-14 23:55:42,835] Trial 68 finished with value: 0.33234952443344745 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24693470011980795
Fold 2 IBS: 0.2311270655102999
Fold 3 IBS: 0.2288788081398321
Fold 4 IBS: 0.2412571776298174
Fold 5 IBS: 0.22851254319260392
[I 2024-04-14 23:55:42,914] Trial 69 finished with value: 0.2353420589184722 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.3852859364739752
Fold 2 IBS: 0.28908727760767267
Fold 3 IBS: 0.380296259387064
Fold 4 IBS: 0.3073003186028882
Fold 5 IBS: 0.3319997062353503
[I 2024-04-14 23:55:44,816] Trial 70 finished with value: 0.33879389966139006 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2447983751594558
Fold 2 IBS: 0.21391212397472412
Fold 3 IBS: 0.2330229517211651
Fold 4 IBS: 0.23018009501747053
Fold 5 IBS: 0.21284182693141118
[I 2024-04-14 23:55:45,002] Trial 71 finished with value: 0.22695107456084535 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24442739217118456
Fold 2 IBS: 0.2202080752130095
Fold 3 IBS: 0.22992449606500545
Fold 4 IBS: 0.23367467424256175
Fold 5 IBS: 0.21734687615024553
[I 2024-04-14 23:55:45,179] Trial 72 finished with value: 0.22911630276840134 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24873206449656773
Fold 2 IBS: 0.20714960221304482
Fold 3 IBS: 0.2391494048288076
Fold 4 IBS: 0.22844134347141637
Fold 5 IBS: 0.20990424423992582
[I 2024-04-14 23:55:45,457] Trial 73 finished with value: 0.2266753318499525 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.255704669484436
Fold 2 IBS: 0.20256586151204847
Fold 3 IBS: 0.24898577012417628
Fold 4 IBS: 0.2304554628587353
Fold 5 IBS: 0.2113616322548472
[I 2024-04-14 23:55:45,748] Trial 74 finished with value: 0.22981467924684865 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.26069403640186745
Fold 2 IBS: 0.20004298805182735
Fold 3 IBS: 0.2590273478317007
Fold 4 IBS: 0.23277903197261338
Fold 5 IBS: 0.2129658995167273
[I 2024-04-14 23:55:46,003] Trial 75 finished with value: 0.23310186075494724 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2449207774729007
Fold 2 IBS: 0.2164741146584261
Fold 3 IBS: 0.23115475964699578
Fold 4 IBS: 0.2318272715320025
Fold 5 IBS: 0.21495710360760373
[I 2024-04-14 23:55:46,122] Trial 76 finished with value: 0.22786680538358572 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22659309077213977.

Fold 1 IBS: 0.2506811440240583
Fold 2 IBS: 0.2053539697592853
Fold 3 IBS: 0.2432701864482772
Fold 4 IBS: 0.2284683602008423
Fold 5 IBS: 0.21006566848816424
[I 2024-04-14 23:55:46,554] Trial 77 finished with value: 0.22756786578412544 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24728609182637104
Fold 2 IBS: 0.20948456237788454
Fold 3 IBS: 0.2367879689804507
Fold 4 IBS: 0.22900068533758589
Fold 5 IBS: 0.21042389725248523
[I 2024-04-14 23:55:46,739] Trial 78 finished with value: 0.2265966411549555 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.2491522359439618
Fold 2 IBS: 0.20720785646863638
Fold 3 IBS: 0.23970965460068624
Fold 4 IBS: 0.22880108027481874
Fold 5 IBS: 0.2102336161969871
[I 2024-04-14 23:55:46,955] Trial 79 finished with value: 0.22702088869701803 and parameters: {'subsample': 0.6723788047810191, 'dropout_rate': 0.7413305472330791, 'n_estimators': 82, 'learning_rate': 0.01601211448054851}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24520954400807898
Fold 2 IBS: 0.2238125298457514
Fold 3 IBS: 0.22900572731692778
Fold 4 IBS: 0.2362826500145415
Fold 5 IBS: 0.22138753922008994
[I 2024-04-14 23:55:47,099] Trial 80 finished with value: 0.23113959808107792 and parameters: {'subsample': 0.5472725501406392, 'dropout_rate': 0.7943244209025906, 'n_estimators': 49, 'learning_rate': 0.006807484156131071}. Best is trial 56 with value: 0.22659309077213977.
Fold 1 IBS: 0.24699041341064157
Fold 2 IBS: 0.20997334219713817
Fold 3 IBS: 0.23605719801087272
Fold 4 IBS: 0.22913034206464886
Fold 5 IBS: 0.21064802263090768
[I 2024-04-14 23:55:47,312] Trial 81 finished with value: 0.2265598636628418 and parameters: {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26424067842199594
Fold 2 IBS: 0.2020280704264556
Fold 3 IBS: 0.2598748714749781
Fold 4 IBS: 0.2359141284498117
Fold 5 IBS: 0.21842360306513237
[I 2024-04-14 23:55:47,660] Trial 82 finished with value: 0.23609627036767472 and parameters: {'subsample': 0.5922453928972238, 'dropout_rate': 0.6191715075378723, 'n_estimators': 120, 'learning_rate': 0.019313878373930102}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24781953444770255
Fold 2 IBS: 0.20853906349093898
Fold 3 IBS: 0.23756791720192394
Fold 4 IBS: 0.22887020018619814
Fold 5 IBS: 0.21041983371444753
[I 2024-04-14 23:55:47,884] Trial 83 finished with value: 0.22664330980824224 and parameters: {'subsample': 0.6146609519724093, 'dropout_rate': 0.6421886730626755, 'n_estimators': 78, 'learning_rate': 0.015223953623176103}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.25409839780204135
Fold 2 IBS: 0.20375347292509463
Fold 3 IBS: 0.2467636455182986
Fold 4 IBS: 0.2300581935658389
Fold 5 IBS: 0.21199853281475728
[I 2024-04-14 23:55:48,110] Trial 84 finished with value: 0.22933444852520615 and parameters: {'subsample': 0.6143777540837653, 'dropout_rate': 0.5703883223273155, 'n_estimators': 78, 'learning_rate': 0.02181695324241678}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2454340835099757
Fold 2 IBS: 0.2136961772818287
Fold 3 IBS: 0.23273056567389488
Fold 4 IBS: 0.23041441332302406
Fold 5 IBS: 0.21235879524348852
[I 2024-04-14 23:55:48,358] Trial 85 finished with value: 0.22692680700644238 and parameters: {'subsample': 0.6445770962436083, 'dropout_rate': 0.6275050227423727, 'n_estimators': 92, 'learning_rate': 0.009130620696524702}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24639926921114977
Fold 2 IBS: 0.22928356450634207
Fold 3 IBS: 0.228754183334704
Fold 4 IBS: 0.2399932817551604
Fold 5 IBS: 0.22623158679105324
[I 2024-04-14 23:55:48,474] Trial 86 finished with value: 0.23413237711968188 and parameters: {'subsample': 0.973596102528499, 'dropout_rate': 0.6913304253389554, 'n_estimators': 30, 'learning_rate': 0.003578120462130444}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2781927071106972
Fold 2 IBS: 0.2046340904187838
Fold 3 IBS: 0.2743538100055575
Fold 4 IBS: 0.24537628788578655
Fold 5 IBS: 0.22685278282223925
[I 2024-04-14 23:55:48,827] Trial 87 finished with value: 0.24588193564861288 and parameters: {'subsample': 0.5848767613231778, 'dropout_rate': 0.5581423348405448, 'n_estimators': 110, 'learning_rate': 0.0276271691730997}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24497452272007741
Fold 2 IBS: 0.21606979660825898
Fold 3 IBS: 0.23139670442225413
Fold 4 IBS: 0.2314990720998036
Fold 5 IBS: 0.2141402661253793
[I 2024-04-14 23:55:48,990] Trial 88 finished with value: 0.22761607239515466 and parameters: {'subsample': 0.6722249946799236, 'dropout_rate': 0.6479045648592634, 'n_estimators': 46, 'learning_rate': 0.01557167084756894}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26516278956994344
Fold 2 IBS: 0.20203982539169615
Fold 3 IBS: 0.2600655154320181
Fold 4 IBS: 0.23608038055976957
Fold 5 IBS: 0.21836273665359834
[I 2024-04-14 23:55:49,501] Trial 89 finished with value: 0.2363422495214051 and parameters: {'subsample': 0.6016440183315196, 'dropout_rate': 0.5918885750046846, 'n_estimators': 128, 'learning_rate': 0.018267143567723715}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24573908001820546
Fold 2 IBS: 0.2267737594491462
Fold 3 IBS: 0.22873715282488816
Fold 4 IBS: 0.23814825000178638
Fold 5 IBS: 0.22350505658163744
[I 2024-04-14 23:55:49,595] Trial 90 finished with value: 0.23258065977513276 and parameters: {'subsample': 0.7078102048337904, 'dropout_rate': 0.6730763431068749, 'n_estimators': 9, 'learning_rate': 0.02340866249635589}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24723648683966212
Fold 2 IBS: 0.2097930026030373
Fold 3 IBS: 0.23695352163573088
Fold 4 IBS: 0.22904234996289285
Fold 5 IBS: 0.21058878491646402
[I 2024-04-14 23:55:49,835] Trial 91 finished with value: 0.22672282919155742 and parameters: {'subsample': 0.5313026641418505, 'dropout_rate': 0.5328649004247455, 'n_estimators': 76, 'learning_rate': 0.014627227900695133}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24577407492517803
Fold 2 IBS: 0.21257383264762358
Fold 3 IBS: 0.23379619719392244
Fold 4 IBS: 0.2299460468627917
Fold 5 IBS: 0.21208238643358707
[I 2024-04-14 23:55:50,082] Trial 92 finished with value: 0.22683450761262053 and parameters: {'subsample': 0.5720522744908453, 'dropout_rate': 0.5211260831534085, 'n_estimators': 76, 'learning_rate': 0.011981813096347545}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.2464934086281741
Fold 2 IBS: 0.2109727784624746
Fold 3 IBS: 0.23508367038465994
Fold 4 IBS: 0.22944836247402864
Fold 5 IBS: 0.21128845087097128
[I 2024-04-14 23:55:50,340] Trial 93 finished with value: 0.22665733416406172 and parameters: {'subsample': 0.4994903777603958, 'dropout_rate': 0.5262836252450818, 'n_estimators': 87, 'learning_rate': 0.011492132047389617}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24588199063218563
Fold 2 IBS: 0.2125930156354007
Fold 3 IBS: 0.23390337282832738
Fold 4 IBS: 0.22995057861580706
Fold 5 IBS: 0.21216121330590818
[I 2024-04-14 23:55:50,601] Trial 94 finished with value: 0.22689803420352578 and parameters: {'subsample': 0.49968900942877426, 'dropout_rate': 0.523020546752894, 'n_estimators': 82, 'learning_rate': 0.011066289138468185}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24490369228481912
Fold 2 IBS: 0.2167329842481149
Fold 3 IBS: 0.23111158091166403
Fold 4 IBS: 0.23195611702074945
Fold 5 IBS: 0.21507941572440312
[I 2024-04-14 23:55:50,913] Trial 95 finished with value: 0.22795675803795015 and parameters: {'subsample': 0.5665760978972413, 'dropout_rate': 0.4628605993177724, 'n_estimators': 100, 'learning_rate': 0.006666098315025223}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.3528807852002724

Fold 2 IBS: 0.26256077094216035
Fold 3 IBS: 0.35927296600690356
Fold 4 IBS: 0.2978922662575483
Fold 5 IBS: 0.3041795583962892
[I 2024-04-14 23:55:51,509] Trial 96 finished with value: 0.31535726936063474 and parameters: {'subsample': 0.41313939490511475, 'dropout_rate': 0.5213109482382285, 'n_estimators': 158, 'learning_rate': 0.054487916689644846}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24708172105946397
Fold 2 IBS: 0.21005062605084635
Fold 3 IBS: 0.23658239945020892
Fold 4 IBS: 0.2291089640988238
Fold 5 IBS: 0.2105403389046395
[I 2024-04-14 23:55:51,728] Trial 97 finished with value: 0.2266728099127965 and parameters: {'subsample': 0.5389995281019297, 'dropout_rate': 0.6077476353900257, 'n_estimators': 73, 'learning_rate': 0.014931416501109941}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.26183286577938214
Fold 2 IBS: 0.20183342233582774
Fold 3 IBS: 0.2575253907596287
Fold 4 IBS: 0.23417362585495322
Fold 5 IBS: 0.21506795896798186
[I 2024-04-14 23:55:52,140] Trial 98 finished with value: 0.23408665273955473 and parameters: {'subsample': 0.545068613650571, 'dropout_rate': 0.5497522480626178, 'n_estimators': 139, 'learning_rate': 0.01569072107683937}. Best is trial 81 with value: 0.2265598636628418.
Fold 1 IBS: 0.24506962981870725
Fold 2 IBS: 0.2156886398952901
Fold 3 IBS: 0.23166204482631356
Fold 4 IBS: 0.2313740373654556
Fold 5 IBS: 0.2142704544460028
[I 2024-04-14 23:55:52,368] Trial 99 finished with value: 0.22761296127035385 and parameters: {'subsample': 0.4999064806675035, 'dropout_rate': 0.6190205560651515, 'n_estimators': 90, 'learning_rate': 0.00800890927792778}. Best is trial 81 with value: 0.2265598636628418.


* Best trial for IBS:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.2265598636628418], datetime_start=datetime.datetime(2024, 4, 14, 23, 55, 47, 101434), datetime_complete=datetime.datetime(2024, 4, 14, 23, 55, 47, 312481), params={'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=81, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6070545538128025, 'dropout_rate': 0.6341528845468055, 'n_estimators': 76, 'learning_rate': 0.014291926646619518}


* Best Score for IBS:
 0.2265598636628418

In [143]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [144]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.659
train_ibs:  0.227

#### Test

In [145]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [146]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.10707700162921632,
                                              learning_rate=0.09635955935176935,
                                              n_estimators=311,
                                              random_state=123,
                                              subsample=0.11211713718471546)

C-index score: 0.536

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6341528845468055,
                                              learning_rate=0.014291926646619518,
                                              n_estimators=76, random_state=123,
                                              subsample=0.6070545538128025)

IBS: 0.234

In [147]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [148]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.830   1.0
ExtraSurvivalTrees               0.764   2.0
GradientBoosting                 0.713   3.0
CoxLasso                         0.691   4.5
CoxElastic                       0.691   4.5
CoxPH                            0.689   6.0
CoxRidge                         0.663   7.0
ComponentwiseGradientBoosting    0.659   8.0

In [149]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.202   1.0
CoxElastic                     0.206   2.0
CoxPH                          0.207   4.0
CoxLasso                       0.207   4.0
ExtraSurvivalTrees             0.207   4.0
ComponentwiseGradientBoosting  0.227   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [150]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.544   1.0
ExtraSurvivalTrees               0.543   2.0
CoxRidge                         0.539   3.0
ComponentwiseGradientBoosting    0.536   4.0
CoxElastic                       0.533   5.0
CoxPH                            0.532   7.0
CoxLasso                         0.532   7.0
GradientBoosting                 0.532   7.0

In [151]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ComponentwiseGradientBoosting  0.234   3.0
Randomsurvivalforest           0.247   4.0
ExtraSurvivalTrees             0.256   5.0
CoxLasso                       0.288   6.5
CoxElastic                     0.288   6.5
CoxPH                          0.290   8.0

In [154]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/standard/rent/'  # Folder path where you want to save the files

# List of corresponding file namess
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_standard_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [155]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14