In [2]:
import warnings
warnings.filterwarnings("ignore")
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_classification

In [3]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [4]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [5]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [6]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

In [7]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

### COX assumption in Train data

In [8]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic      p  -log2(p)
MTV                       0.07   0.80      0.33
SUVpeak                   0.17   0.68      0.56
TLG                       0.38   0.54      0.90
age                       0.09   0.77      0.38
cavum_oris                0.00   0.99      0.02
charlson                  1.66   0.20      2.34
female                    2.67   0.10      3.29
histgrade_high            0.13   0.72      0.48
hpv_related              12.67 <0.005     11.39
hypopharynx               0.00   0.99      0.01
larynx                    0.00   0.98      0.03
oropharynx                0.00   0.98      0.02
pack_years                0.06   0.81      0.31
uicc8_III-IV              0.09   0.76      0.39

In [9]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

In [10]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='OS', event_col='event_OS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 82 right-censored observations>
         test_name = proportional_hazard_test

---
                test_statistic    p  -log2(p)
MTV                       0.59 0.44      1.17
SUVpeak                   0.01 0.91      0.14
TLG                       0.00 0.96      0.06
age                       0.43 0.51      0.97
cavum_oris                0.41 0.52      0.94
charlson                  0.87 0.35      1.51
female                    2.39 0.12      3.04
histgrade_high            0.11 0.74      0.44
hpv_related               6.46 0.01      6.51
hypopharynx               0.04 0.84      0.25
larynx                    0.97 0.33      1.62
oropharynx                0.85 0.36      1.49
pack_years                0.00 0.99      0.01
uicc8_III-IV              0.00 0.95      0.07

In [11]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['hpv_related'], dtype='object')

###### penalizer values essentially result in same result

## Test dataset: MAASTRO

In [12]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [13]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [14]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [15]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG,OS,OS_event
0,1,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342,44.43,1.0
3,4,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979,37.20,1.0
4,6,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782,19.00,1.0
95,111,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212,72.07,0.0

In [16]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [17]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [18]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [19]:
# Set lower, upper time point and gbsg_times for IBS calculation later 
lower, upper = np.percentile(y['OS'], [10, 90])
gbsg_times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [20]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 14)
y_train:  (139,)

In [21]:
clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

In [22]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 16)

In [23]:
# VIF dataframe 
vif_data = pd.DataFrame() 
vif_data["feature"] = X.columns 
  
# calculating VIF for each feature 
vif_data["VIF"] = [variance_inflation_factor(X.values, i) 
                          for i in range(len(X.columns))] 

vif_data

           feature        VIF
0              age   1.136852
1           female   1.197250
2       cavum_oris   7.993011
3       oropharynx  60.199385
4      hypopharynx  11.118710
5           larynx  14.183474
6   histgrade_high   1.150479
7      hpv_related   4.309385
8         charlson   1.302350
9       pack_years   1.647441
10    uicc8_III-IV   2.026695
11         SUVpeak   2.157147
12             MTV   5.247552
13             TLG   6.368452

# Standardization

In [24]:
original_X = X.copy()

In [25]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = MinMaxScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [26]:
# Standardize X_MAASTRO 
MAASTRO_new = X_MAASTRO.copy()
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [27]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = MAASTRO_new_std

In [28]:
X_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,0.0,14.473272,7.934,86.228420
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,0.0,5.044678,1.656,7.040100
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,1.0,7.839043,14.502,83.569669
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,0.0,2.880631,2.440,5.567091
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,0.0,5.402006,3.668,16.150550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,0.0,9.290139,3.650,26.280140
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,1.0,7.172883,18.967,101.754834
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,0.0,13.873187,6.370,66.273201
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,1.0,7.507419,12.443,71.832443
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,1.0,13.053465,7.983,78.647696

In [29]:
X_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,0.365347,1,0,1,0,0,1,0.0,0,0.000000,0.0,0.435155,0.074159,0.044798
1,0.373041,0,0,0,0,1,0,0.0,1,0.213981,0.0,0.089331,0.008512,0.001900
2,0.487409,0,1,0,0,0,1,0.0,1,0.320284,1.0,0.191823,0.142839,0.043358
3,0.786304,0,0,0,0,1,0,0.0,1,0.292806,0.0,0.009957,0.016710,0.001102
4,0.713276,0,0,0,0,1,0,0.0,1,0.413832,0.0,0.102437,0.029551,0.006835
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,0.523573,0,0,1,0,0,1,1.0,0,0.000000,0.0,0.245047,0.029363,0.012323
135,0.736989,0,0,1,0,0,1,1.0,0,0.000000,1.0,0.167389,0.189529,0.053209
136,0.448587,0,0,1,0,0,1,1.0,1,0.308411,0.0,0.413145,0.057805,0.033988
137,0.657597,0,0,1,0,0,1,1.0,1,0.558497,1.0,0.179660,0.121309,0.037000
138,0.555260,0,0,1,0,0,1,1.0,0,0.017568,1.0,0.383079,0.074672,0.040692

In [30]:
MAASTRO_new

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,55,0,0,1,0,0,1,1,1,0,0,15.438583,22.841,263.611623
1,55,0,0,1,0,0,0,0,0,20,1,8.829353,5.660,36.980700
2,55,0,0,1,0,0,0,0,1,6,1,13.476123,7.791,74.636342
3,61,1,0,0,0,1,1,0,1,45,1,8.632732,7.908,46.791979
4,70,0,0,1,0,0,1,1,1,59,0,9.783954,15.237,107.637514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,66,1,0,0,0,1,0,0,0,55,1,31.338410,6.110,144.490782
95,63,0,0,0,0,1,0,0,1,174,1,13.041604,7.182,69.214868
96,63,0,0,1,0,0,1,1,1,0,1,8.944517,16.483,102.594274
97,54,0,0,1,0,0,1,1,0,0,0,14.184236,9.981,103.229492
98,62,0,0,0,1,0,1,0,0,40,1,10.414851,3.495,28.553212

In [31]:
MAASTRO_new_std

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,uicc8_III-IV,SUVpeak,MTV,TLG
0,0.384793,0,0,1,0,0,1,1,1,0.000000,0,0.470560,0.230038,0.140892
1,0.384793,0,0,1,0,0,0,0,0,0.156163,1,0.228146,0.050381,0.018119
2,0.384793,0,0,1,0,0,0,0,1,0.046849,1,0.398581,0.072664,0.038519
3,0.537983,1,0,0,0,1,1,0,1,0.351367,1,0.220934,0.073887,0.023434
4,0.767767,0,0,1,0,0,1,1,1,0.460681,0,0.263159,0.150525,0.056396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,0.665641,1,0,0,0,1,0,0,0,0.429449,1,1.053738,0.055086,0.076361
95,0.589046,0,0,0,0,1,0,0,1,1.358619,1,0.382644,0.066296,0.035582
96,0.589046,0,0,1,0,0,1,1,1,0.000000,1,0.232370,0.163554,0.053664
97,0.359261,0,0,1,0,0,1,1,0,0.000000,0,0.424553,0.095564,0.054008
98,0.563514,0,0,0,1,0,1,0,0,0.312326,1,0.286299,0.027742,0.013554

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [32]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-20 17:05:32,957] A new study created in memory with name: no-name-f25ecdb0-1408-4eb6-8725-ca3ef08c1083

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-20 17:05:33,345] A new study created in memory with name: no-name-257fa157-38e9-4686-9042-968a6e35b79e

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:33,340] Trial 0 finished with value: 0.7580581707147598 and parameters: {}. Best is trial 0 with value: 0.7580581707147598.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7580581707147598], datetime_start=datetime.datetime(2024, 4, 20, 17, 5, 33, 73745), datetime_complete=datetime.datetime(2024, 4, 20, 17, 5, 33, 340311), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7580581707147598

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.18224790157453521
Fold 2 IBS: 0.1793618517283866
Fold 3 IBS: 0.5169743692261356
Fold 4 IBS: 0.6484315948601662
Fold 5 IBS: 0.2737533899229805
[I 2024-04-20 17:05:33,755] Trial 0 finished with value: 0.3601538214624408 and parameters: {}. Best is trial 0 with value: 0.3601538214624408.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.3601538214624408], datetime_start=datetime.datetime(2024, 4, 20, 17, 5, 33, 395749), datetime_complete=datetime.datetime(2024, 4, 20, 17, 5, 33, 755532), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.3601538214624408

In [33]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [34]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.758
train_ibs:  0.36

#### Test

In [35]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [36]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [37]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [38]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [39]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-20 17:05:44,958] A new study created in memory with name: no-name-2e5b6053-4ef8-4a5f-b432-aa77d5ec5d5b

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-20 17:05:45,083] A new study created in memory with name: no-name-63b23f58-4d44-43a4-bd3e-fab293e59feb

Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 17:05:45,079] Trial 0 finished with value: 0.7182877718827688 and parameters: {}. Best is trial 0 with value: 0.7182877718827688.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7182877718827688], datetime_start=datetime.datetime(2024, 4, 20, 17, 5, 44, 994942), datetime_complete=datetime.datetime(2024, 4, 20, 17, 5, 45, 79146), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7182877718827688

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651763328035
Fold 2 IBS: 0.22157791469499555
Fold 3 IBS: 0.20453594133219627
Fold 4 IBS: 0.22473803324306438
Fold 5 IBS: 0.21812431436306018
[I 2024-04-20 17:05:45,246] Trial 0 finished with value: 0.21659054425331936 and parameters: {}. Best is trial 0 with value: 0.21659054425331936.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21659054425331936], datetime_start=datetime.datetime(2024, 4, 20, 17, 5, 45, 115219), datetime_complete=datetime.datetime(2024, 4, 20, 17, 5, 45, 246564), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21659054425331936

In [40]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [41]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.718
train_ibs:  0.217

#### Test

In [42]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [43]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.624

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [44]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [107]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-21 11:10:00,529] A new study created in memory with name: no-name-b1a1ab23-5ca1-4902-952c-104b3bd7e35a

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848

[I 2024-04-21 11:10:00,854] A new study created in memory with name: no-name-f6625b63-12ea-4961-b7b3-7ce2a81e100e

Fold 5 C-index: 0.6525821596244131
[I 2024-04-21 11:10:00,849] Trial 0 finished with value: 0.7563214317153626 and parameters: {}. Best is trial 0 with value: 0.7563214317153626.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7563214317153626], datetime_start=datetime.datetime(2024, 4, 21, 11, 10, 0, 553406), datetime_complete=datetime.datetime(2024, 4, 21, 11, 10, 0, 848722), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7563214317153626

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1822562210458609
Fold 2 IBS: 0.17929926098802096
Fold 3 IBS: 0.15678124122148837
Fold 4 IBS: 0.14669965181722588
Fold 5 IBS: 0.272560860180458
[I 2024-04-21 11:10:01,234] Trial 0 finished with value: 0.18751944705061083 and parameters: {}. Best is trial 0 with value: 0.18751944705061083.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.18751944705061083], datetime_start=datetime.datetime(2024, 4, 21, 11, 10, 0, 886321), datetime_complete=datetime.datetime(2024, 4, 21, 11, 10, 1, 234427), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.18751944705061083

In [108]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [109]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.756
train_ibs:  0.188

#### Test

In [110]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [111]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.583

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.287

In [112]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [51]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-20 17:05:49,495] A new study created in memory with name: no-name-0e51ccfa-8249-4b48-a610-1f979205fc9e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:49,874] Trial 0 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:50,261] Trial 1 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:50,882] Trial 2 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:51,246] Trial 3 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:51,549] Trial 4 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:51,909] Trial 5 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:52,219] Trial 6 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:52,522] Trial 7 finished with value: 0.7554285745725056 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:52,883] Trial 8 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:53,269] Trial 9 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:53,582] Trial 10 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:53,931] Trial 11 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:54,287] Trial 12 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:54,645] Trial 13 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8178071080614558}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:55,348] Trial 14 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:55,702] Trial 15 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.5998716175293216}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:56,043] Trial 16 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8431112134784231}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:56,401] Trial 17 finished with value: 0.7554285745725056 and parameters: {'l1_ratio': 0.6422698927560148}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:56,723] Trial 18 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8885825731043129}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:57,029] Trial 19 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.5264626269854424}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:57,325] Trial 20 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:57,653] Trial 21 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9632315494528705}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:57,975] Trial 22 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7603585811207305}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:58,279] Trial 23 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9339868118831415}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286

Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:58,575] Trial 24 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8064824763528503}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:59,058] Trial 25 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.6339676394936953}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 17:05:59,205] Trial 26 finished with value: 0.7227374646920308 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:59,514] Trial 27 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.6942928064214194}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:05:59,824] Trial 28 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9063632126862387}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:00,170] Trial 29 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.3366186703390048}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:00,491] Trial 30 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.5775787537083129}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:00,757] Trial 31 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9780144475848741}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:01,022] Trial 32 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9884029690140215}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:01,320] Trial 33 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8192521040492207}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:01,685] Trial 34 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.21553914253693035}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:01,954] Trial 35 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9089036386081054}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:02,198] Trial 36 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.999722407884233}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:02,660] Trial 37 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:02,929] Trial 38 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7883002392124641}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:03,246] Trial 39 finished with value: 0.7554285745725056 and parameters: {'l1_ratio': 0.6677750532870234}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:03,574] Trial 40 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7206710030756495}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:03,863] Trial 41 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7532760890335594}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:04,142] Trial 42 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8565463424508266}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:04,429] Trial 43 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9448773975732067}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:04,897] Trial 44 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.6078439179496484}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:05,203] Trial 45 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:05,516] Trial 46 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7729306642959861}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:05,809] Trial 47 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.6949407631028973}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451

Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:06,135] Trial 48 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8526883818058227}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:06,493] Trial 49 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.730055009401814}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:06,920] Trial 50 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.47241766561900594}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:07,251] Trial 51 finished with value: 0.7554285745725056 and parameters: {'l1_ratio': 0.6433949037564692}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:07,591] Trial 52 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.5631849799397499}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:07,947] Trial 53 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8297168739016059}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:08,222] Trial 54 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9364278194389339}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:08,622] Trial 55 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8907215806081076}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:08,914] Trial 56 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.39472230727834606}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:09,201] Trial 57 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7164121043962042}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:09,510] Trial 58 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.6602958868589475}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:09,805] Trial 59 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.5094208387932386}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:10,105] Trial 60 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.6097637962339882}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:10,494] Trial 61 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8055574351093431}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:10,774] Trial 62 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7499572491313622}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:11,089] Trial 63 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9216918423183558}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:11,359] Trial 64 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7879750008150864}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:11,651] Trial 65 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9625357271595593}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:11,932] Trial 66 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8753643302853108}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:12,341] Trial 67 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8227871339412823}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:12,618] Trial 68 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.6954738542511587}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:12,896] Trial 69 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7633770828385912}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:13,229] Trial 70 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8582359508807347}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:13,522] Trial 71 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7360867196139887}. Best is trial 0 with value: 0.7563214317153626.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:13,825] Trial 72 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8409191453510266}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:14,195] Trial 73 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8952506695818099}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:14,466] Trial 74 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9628319511795009}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:14,806] Trial 75 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.21877076880955348}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:15,139] Trial 76 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7946518030337633}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:15,410] Trial 77 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.996733481908993}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:15,732] Trial 78 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.6639449777685031}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:16,076] Trial 79 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7077365261767863}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:16,385] Trial 80 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9203111091931792}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:16,708] Trial 81 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8902792357538003}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:17,034] Trial 82 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8672656901543331}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:17,311] Trial 83 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9659265498288231}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:17,607] Trial 84 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7770620274322017}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:17,863] Trial 85 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9324626276543974}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:18,150] Trial 86 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8375451580592126}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:18,473] Trial 87 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8133902210097012}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:18,784] Trial 88 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7454551857385523}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:19,085] Trial 89 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.6319967548529334}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:19,635] Trial 90 finished with value: 0.7554285745725056 and parameters: {'l1_ratio': 0.6778185689008253}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:19,975] Trial 91 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.28649138832750976}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:20,250] Trial 92 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9531367076177379}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:20,586] Trial 93 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8741063886467}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:20,891] Trial 94 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9063037229447606}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:21,207] Trial 95 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8044045058977899}. Best is trial 0 with value: 0.7563214317153626.

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:21,934] Trial 96 finished with value: 0.7545846927159654 and parameters: {'l1_ratio': 0.1343084889624756}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:22,289] Trial 97 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.7693413316120632}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:22,559] Trial 98 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.9901988391019232}. Best is trial 0 with value: 0.7563214317153626.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451

[I 2024-04-20 17:06:22,970] A new study created in memory with name: no-name-cd841e38-11c2-4cad-93be-c0f0005876aa

Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:06:22,966] Trial 99 finished with value: 0.7563214317153626 and parameters: {'l1_ratio': 0.8291021247786665}. Best is trial 0 with value: 0.7563214317153626.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7563214317153626], datetime_start=datetime.datetime(2024, 4, 20, 17, 5, 49, 528308), datetime_complete=datetime.datetime(2024, 4, 20, 17, 5, 49, 874198), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.7563214317153626

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18223089538135095
Fold 2 IBS: 0.17953058635719008
Fold 3 IBS: 0.15710637636572208
Fold 4 IBS: 0.14705004078562361
Fold 5 IBS: 0.2725427772516032
[I 2024-04-20 17:06:23,355] Trial 0 finished with value: 0.187692135228298 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.187692135228298.
Fold 1 IBS: 0.1821862002988621
Fold 2 IBS: 0.1796266625284713
Fold 3 IBS: 0.15734267606089006
Fold 4 IBS: 0.14728145985772745
Fold 5 IBS: 0.2725925913053688
[I 2024-04-20 17:06:23,732] Trial 1 finished with value: 0.18780591801026394 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.187692135228298.
Fold 1 IBS: 0.18218283176202407
Fold 2 IBS: 0.1796412294542746
Fold 3 IBS: 0.1573625510861116
Fold 4 IBS: 0.1473020530956881
Fold 5 IBS: 0.2725878481090234
[I 2024-04-20 17:06:24,293] Trial 2 finished with value: 0.18781530270142435 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.187692135228298.
Fold 1 IBS: 0.18221297989437776
Fold 2 IBS: 0.1795665364907602
Fold 3 IBS: 0.15719774641742307
Fold 4 IBS: 0.14715025428785672
Fold 5 IBS: 0.2725897160965761
[I 2024-04-20 17:06:24,642] Trial 3 finished with value: 0.18774344663739878 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.187692135228298.
Fold 1 IBS: 0.1822329950439583
Fold 2 IBS: 0.17953037767192692
Fold 3 IBS: 0.15712556577133593
Fold 4 IBS: 0.14704160219742984
Fold 5 IBS: 0.2725135770571663
[I 2024-04-20 17:06:25,030] Trial 4 finished with value: 0.18768882354836344 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.18768882354836344.
Fold 1 IBS: 0.1822054800549531
Fold 2 IBS: 0.17961413208822005
Fold 3 IBS: 0.15730753602184086
Fold 4 IBS: 0.1472256996396382
Fold 5 IBS: 0.27255635547692253
[I 2024-04-20 17:06:25,381] Trial 5 finished with value: 0.18778184065631492 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.18768882354836344.
Fold 1 IBS: 0.18225547271773326
Fold 2 IBS: 0.17933487376120022
Fold 3 IBS: 0.15676391707433232
Fold 4 IBS: 0.14675387867068465
Fold 5 IBS: 0.27248588475609065
[I 2024-04-20 17:06:25,685] Trial 6 finished with value: 0.18751880539600824 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.18751880539600824.
Fold 1 IBS: 0.18222978203609957
Fold 2 IBS: 0.17954901945294552
Fold 3 IBS: 0.15709505447787953
Fold 4 IBS: 0.14706897279962777
Fold 5 IBS: 0.2726052597470601
[I 2024-04-20 17:06:26,179] Trial 7 finished with value: 0.1877096177027225 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.18751880539600824.
Fold 1 IBS: 0.18220442991070096
Fold 2 IBS: 0.1795987303932917
Fold 3 IBS: 0.15727663830197658
Fold 4 IBS: 0.1471929187122065
Fold 5 IBS: 0.27255943848943637
[I 2024-04-20 17:06:26,503] Trial 8 finished with value: 0.18776643116152242 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.18751880539600824.
Fold 1 IBS: 0.182194897677701
Fold 2 IBS: 0.17962967399664223
Fold 3 IBS: 0.15731575233414075
Fold 4 IBS: 0.1472396638074122
Fold 5 IBS: 0.272635217679984
[I 2024-04-20 17:06:26,874] Trial 9 finished with value: 0.18780304109917606 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.18751880539600824.
Fold 1 IBS: 0.18225575450720932
Fold 2 IBS: 0.17932767898852317
Fold 3 IBS: 0.1567675130681149
Fold 4 IBS: 0.14675229396742945
Fold 5 IBS: 0.27250098883494894
[I 2024-04-20 17:06:27,225] Trial 10 finished with value: 0.1875208458732452 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.18751880539600824.
Fold 1 IBS: 0.18225619562076134
Fold 2 IBS: 0.17930338882316996
Fold 3 IBS: 0.1567785405230181
Fold 4 IBS: 0.14670098168376755
Fold 5 IBS: 0.27254931150920225
[I 2024-04-20 17:06:27,517] Trial 11 finished with value: 0.18751768363198384 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 11 with value: 0.18751768363198384.
Fold 1 IBS: 0.1822532084914249
Fold 2 IBS: 0.17930773095736458
Fold 3 IBS: 0.15677618778360436
Fold 4 IBS: 0.14670214475163204
Fold 5 IBS: 0.2725392815651356
[I 2024-04-20 17:06:27,865] Trial 12 finished with value: 0.18751571070983228 and parameters: {'l1_ratio': 0.9948264745658929}. Best is trial 12 with value: 0.18751571070983228.
Fold 1 IBS: 0.2126772241154758
Fold 2 IBS: 0.1854845921359128
Fold 3 IBS: 0.15685181867411746
Fold 4 IBS: 0.22228759041217605
Fold 5 IBS: 0.26990854303416806
[I 2024-04-20 17:06:28,281] Trial 13 finished with value: 0.20944195367437005 and parameters: {'l1_ratio': 0.03152521162798527}. Best is trial 12 with value: 0.18751571070983228.
Fold 1 IBS: 0.18224698575815174
Fold 2 IBS: 0.17941118310342077
Fold 3 IBS: 0.15693347910098096
Fold 4 IBS: 0.1468620797088128
Fold 5 IBS: 0.27255241106695033
[I 2024-04-20 17:06:28,602] Trial 14 finished with value: 0.18760122774766336 and parameters: {'l1_ratio': 0.8887005110166508}. Best is trial 12 with value: 0.18751571070983228.
Fold 1 IBS: 0.18224224077815512
Fold 2 IBS: 0.17945960391127924
Fold 3 IBS: 0.156968133007699
Fold 4 IBS: 0.1469095486443697
Fold 5 IBS: 0.2725008697826045
[I 2024-04-20 17:06:28,915] Trial 15 finished with value: 0.1876160792248215 and parameters: {'l1_ratio': 0.8435258665171791}. Best is trial 12 with value: 0.18751571070983228.
Fold 1 IBS: 0.18223773775797641
Fold 2 IBS: 0.1794944397118666
Fold 3 IBS: 0.15700731671581653
Fold 4 IBS: 0.14695087281870034
Fold 5 IBS: 0.2725778591080452
[I 2024-04-20 17:06:29,281] Trial 16 finished with value: 0.187653645222481 and parameters: {'l1_ratio': 0.8046771700892117}. Best is trial 12 with value: 0.18751571070983228.
Fold 1 IBS: 0.18225583378639715
Fold 2 IBS: 0.17932569558063247
Fold 3 IBS: 0.15676851537474873
Fold 4 IBS: 0.1467067325659591
Fold 5 IBS: 0.27250521037016223
[I 2024-04-20 17:06:29,612] Trial 17 finished with value: 0.18751239753557997 and parameters: {'l1_ratio': 0.9853615392538034}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224590428303888
Fold 2 IBS: 0.17943642053719258
Fold 3 IBS: 0.15691919561045925
Fold 4 IBS: 0.1468685858607896
Fold 5 IBS: 0.2724996683784992
[I 2024-04-20 17:06:29,916] Trial 18 finished with value: 0.18759395493399592 and parameters: {'l1_ratio': 0.8736621911898683}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18222278852604165
Fold 2 IBS: 0.17955575075989225
Fold 3 IBS: 0.15719802928559926
Fold 4 IBS: 0.14712053663081642
Fold 5 IBS: 0.2725693138982824
[I 2024-04-20 17:06:30,439] Trial 19 finished with value: 0.18773328382012638 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18223627586605054
Fold 2 IBS: 0.17949189149569575
Fold 3 IBS: 0.1570599819594348
Fold 4 IBS: 0.1469804715060991
Fold 5 IBS: 0.27251907225185934
[I 2024-04-20 17:06:30,862] Trial 20 finished with value: 0.1876575386158279 and parameters: {'l1_ratio': 0.7862982025751247}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225436796230968
Fold 2 IBS: 0.17933704135124975
Fold 3 IBS: 0.15684312909273518
Fold 4 IBS: 0.14675563532240166
Fold 5 IBS: 0.2725469802153071
[I 2024-04-20 17:06:31,221] Trial 21 finished with value: 0.18754743078880068 and parameters: {'l1_ratio': 0.9705260458283718}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224867563225433
Fold 2 IBS: 0.179399324690423
Fold 3 IBS: 0.15687525741338307
Fold 4 IBS: 0.14681860526338153
Fold 5 IBS: 0.2725351389791835
[I 2024-04-20 17:06:31,563] Trial 22 finished with value: 0.18757540039572507 and parameters: {'l1_ratio': 0.9130757617488995}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225604159666933
Fold 2 IBS: 0.179320587021942
Fold 3 IBS: 0.15677112518543015
Fold 4 IBS: 0.146705417604403
Fold 5 IBS: 0.27251621653259345
[I 2024-04-20 17:06:31,887] Trial 23 finished with value: 0.18751387758820762 and parameters: {'l1_ratio': 0.9879856951002318}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18223577030766758
Fold 2 IBS: 0.17948873886772407
Fold 3 IBS: 0.1570459579838234
Fold 4 IBS: 0.14698652325161946
Fold 5 IBS: 0.27256400671581305
[I 2024-04-20 17:06:32,340] Trial 24 finished with value: 0.1876641994253295 and parameters: {'l1_ratio': 0.7685666053673711}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224845829561478
Fold 2 IBS: 0.1794047750370614

Fold 3 IBS: 0.156872222110765
Fold 4 IBS: 0.14685332071526855
Fold 5 IBS: 0.2725237858784887
[I 2024-04-20 17:06:32,703] Trial 25 finished with value: 0.1875805124074397 and parameters: {'l1_ratio': 0.9099439614290462}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822247523708942
Fold 2 IBS: 0.1795662094311297
Fold 3 IBS: 0.15716070874522764
Fold 4 IBS: 0.14710382843507397
Fold 5 IBS: 0.27252429124360517
[I 2024-04-20 17:06:33,100] Trial 26 finished with value: 0.1877159580451861 and parameters: {'l1_ratio': 0.6258200052759627}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224877276585452
Fold 2 IBS: 0.17939690902708083
Fold 3 IBS: 0.1568766125262203
Fold 4 IBS: 0.1468179562409922
Fold 5 IBS: 0.272540234203548
[I 2024-04-20 17:06:33,541] Trial 27 finished with value: 0.18757609695273916 and parameters: {'l1_ratio': 0.9144784282298041}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822391690282693
Fold 2 IBS: 0.1794631280953686
Fold 3 IBS: 0.15702468966810423
Fold 4 IBS: 0.1469434227755442
Fold 5 IBS: 0.272537682380537
[I 2024-04-20 17:06:33,893] Trial 28 finished with value: 0.18764161838956467 and parameters: {'l1_ratio': 0.82349678072636}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822325271785546
Fold 2 IBS: 0.1795389764211485
Fold 3 IBS: 0.1571207440306865
Fold 4 IBS: 0.14704346040125005
Fold 5 IBS: 0.27259650915613826
[I 2024-04-20 17:06:34,214] Trial 29 finished with value: 0.18770644343755558 and parameters: {'l1_ratio': 0.7142390779539207}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18216238236730634
Fold 2 IBS: 0.1800844227604244
Fold 3 IBS: 0.15739870960565944
Fold 4 IBS: 0.1473305552624676
Fold 5 IBS: 0.2723970930543498
[I 2024-04-20 17:06:34,655] Trial 30 finished with value: 0.18787463261004153 and parameters: {'l1_ratio': 0.12925484015425115}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225592266556434
Fold 2 IBS: 0.1793234970226453
Fold 3 IBS: 0.15676963487127477
Fold 4 IBS: 0.1467061676726301
Fold 5 IBS: 0.2725099285920851
[I 2024-04-20 17:06:34,982] Trial 31 finished with value: 0.18751303016483994 and parameters: {'l1_ratio': 0.9864858075876226}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822498043466856
Fold 2 IBS: 0.17939212479357713
Fold 3 IBS: 0.15689137319031443
Fold 4 IBS: 0.14681110190074295
Fold 5 IBS: 0.2724919777310155
[I 2024-04-20 17:06:35,368] Trial 32 finished with value: 0.18756727639246712 and parameters: {'l1_ratio': 0.9299444991776095}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225620390570124
Fold 2 IBS: 0.17930179269486954
Fold 3 IBS: 0.15677941562347705
Fold 4 IBS: 0.1467005501962541
Fold 5 IBS: 0.27255304965233995
[I 2024-04-20 17:06:35,911] Trial 33 finished with value: 0.18751820241452838 and parameters: {'l1_ratio': 0.9981243470104201}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822425304904581
Fold 2 IBS: 0.17945304285759744
Fold 3 IBS: 0.15697178737774312
Fold 4 IBS: 0.14690798211047243
Fold 5 IBS: 0.27251415560986764
[I 2024-04-20 17:06:36,237] Trial 34 finished with value: 0.18761789968922776 and parameters: {'l1_ratio': 0.8474069446870455}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225042139017564
Fold 2 IBS: 0.17938275778706692
Fold 3 IBS: 0.15689455190363777
Fold 4 IBS: 0.1468089179742859
Fold 5 IBS: 0.2725212300345101
[I 2024-04-20 17:06:36,555] Trial 35 finished with value: 0.18757157581793527 and parameters: {'l1_ratio': 0.934978261696144}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224361286888283
Fold 2 IBS: 0.1794299167290374
Fold 3 IBS: 0.15698550757580704
Fold 4 IBS: 0.1469024295225356
Fold 5 IBS: 0.27256418336627564
[I 2024-04-20 17:06:36,933] Trial 36 finished with value: 0.1876251300125077 and parameters: {'l1_ratio': 0.8622205319023497}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18223564178474402
Fold 2 IBS: 0.17949102824786067
Fold 3 IBS: 0.15704452695530594
Fold 4 IBS: 0.1469870662818385
Fold 5 IBS: 0.27255927872313207
[I 2024-04-20 17:06:37,291] Trial 37 finished with value: 0.18766350839857626 and parameters: {'l1_ratio': 0.7670445844987026}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1821857295743803
Fold 2 IBS: 0.1796304984736256
Fold 3 IBS: 0.15734001556235463
Fold 4 IBS: 0.1472823774660078
Fold 5 IBS: 0.27258544461090817
[I 2024-04-20 17:06:37,682] Trial 38 finished with value: 0.1878048131374553 and parameters: {'l1_ratio': 0.2845008125749434}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225448841524206
Fold 2 IBS: 0.1793702248646159
Fold 3 IBS: 0.1568278880367564
Fold 4 IBS: 0.14676361396902196
Fold 5 IBS: 0.2724831538809661
[I 2024-04-20 17:06:38,003] Trial 39 finished with value: 0.1875398738333205 and parameters: {'l1_ratio': 0.9530823314739104}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18223374012753774
Fold 2 IBS: 0.1795209332328187
Fold 3 IBS: 0.15708824528873638
Fold 4 IBS: 0.14701403272391728
Fold 5 IBS: 0.2725997015841506
[I 2024-04-20 17:06:38,354] Trial 40 finished with value: 0.18769133059143214 and parameters: {'l1_ratio': 0.7475193525755968}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225319858919686
Fold 2 IBS: 0.1793057877536212
Fold 3 IBS: 0.15677723592383055
Fold 4 IBS: 0.14670162607577295
Fold 5 IBS: 0.2725437474083348
[I 2024-04-20 17:06:38,721] Trial 41 finished with value: 0.18751631915015127 and parameters: {'l1_ratio': 0.9958948379248703}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225418439243596
Fold 2 IBS: 0.17937865067303108
Fold 3 IBS: 0.15682378866743685
Fold 4 IBS: 0.14676562578091423
Fold 5 IBS: 0.2725674639522509
[I 2024-04-20 17:06:39,099] Trial 42 finished with value: 0.18755794269321382 and parameters: {'l1_ratio': 0.9488989589816076}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224665620226219
Fold 2 IBS: 0.1794187185276594
Fold 3 IBS: 0.15692912912964152
Fold 4 IBS: 0.14686406962602322
Fold 5 IBS: 0.2725362997788384
[I 2024-04-20 17:06:39,618] Trial 43 finished with value: 0.18759897465288494 and parameters: {'l1_ratio': 0.8840821219021612}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225629234389185
Fold 2 IBS: 0.17931466435900298
Fold 3 IBS: 0.15677419796596923
Fold 4 IBS: 0.1467038777263928
Fold 5 IBS: 0.27252987970329523
[I 2024-04-20 17:06:39,935] Trial 44 finished with value: 0.18751578241971043 and parameters: {'l1_ratio': 0.9910913967128557}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.182227890777446
Fold 2 IBS: 0.17955007046288055
Fold 3 IBS: 0.15714001427007224
Fold 4 IBS: 0.14707604829079227
Fold 5 IBS: 0.27254586382997553
[I 2024-04-20 17:06:40,277] Trial 45 finished with value: 0.1877079775262333 and parameters: {'l1_ratio': 0.6650853818004321}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18221604378949513
Fold 2 IBS: 0.17961330814143736
Fold 3 IBS: 0.15722027872728472
Fold 4 IBS: 0.14716659451132297
Fold 5 IBS: 0.27259568604688017
[I 2024-04-20 17:06:40,701] Trial 46 finished with value: 0.18776238224328407 and parameters: {'l1_ratio': 0.5222973322437542}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.182239307854244
Fold 2 IBS: 0.17946016484778815
Fold 3 IBS: 0.1570263797863285
Fold 4 IBS: 0.14694269853088296
Fold 5 IBS: 0.2725438299756045
[I 2024-04-20 17:06:41,129] Trial 47 finished with value: 0.18764247619896962 and parameters: {'l1_ratio': 0.8253679568408561}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822020178379565
Fold 2 IBS: 0.17960730450282641
Fold 3 IBS: 0.15728394348890823
Fold 4 IBS: 0.14723488931032597
Fold 5 IBS: 0.2725813659670428
[I 2024-04-20 17:06:41,721] Trial 48 finished with value: 0.187781904221412 and parameters: {'l1_ratio': 0.4031966803329795}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225476968821114
Fold 2 IBS: 0.17936259720251585
Fold 3 IBS: 0.15683166066779972
Fold 4 IBS: 0.14676177964032253
Fold 5 IBS: 0.2724986092942911
[I 2024-04-20 17:06:42,146] Trial 49 finished with value: 0.18754188329862806 and parameters: {'l1_ratio': 0.9569522433312039}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224595210643055
Fold 2 IBS: 0.17943527531642253

Fold 3 IBS: 0.15691982750840544
Fold 4 IBS: 0.14686829028864845
Fold 5 IBS: 0.2725019968224739
[I 2024-04-20 17:06:42,507] Trial 50 finished with value: 0.18759426840847618 and parameters: {'l1_ratio': 0.8743196954547819}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225441586500854
Fold 2 IBS: 0.17933590719210243
Fold 3 IBS: 0.1568437243098027
Fold 4 IBS: 0.14675535719041946
Fold 5 IBS: 0.2725494403512185
[I 2024-04-20 17:06:42,841] Trial 51 finished with value: 0.1875477689817103 and parameters: {'l1_ratio': 0.9711488252676377}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225478681638807
Fold 2 IBS: 0.17934461863558518
Fold 3 IBS: 0.15684829781803014
Fold 4 IBS: 0.14675322963475146
Fold 5 IBS: 0.2725676193077559
[I 2024-04-20 17:06:43,152] Trial 52 finished with value: 0.18755371044250216 and parameters: {'l1_ratio': 0.9759519327420665}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225616070202216
Fold 2 IBS: 0.1793177157079479
Fold 3 IBS: 0.15677260811059543
Fold 4 IBS: 0.14670467332669382
Fold 5 IBS: 0.2725231535579295
[I 2024-04-20 17:06:43,539] Trial 53 finished with value: 0.18751486228103778 and parameters: {'l1_ratio': 0.9894824372635469}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224785137977711
Fold 2 IBS: 0.17941479045716768
Fold 3 IBS: 0.15694488264433987
Fold 4 IBS: 0.1468569216899182
Fold 5 IBS: 0.27249092185765356
[I 2024-04-20 17:06:43,900] Trial 54 finished with value: 0.1875910736057713 and parameters: {'l1_ratio': 0.9009805255241471}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822538222341257
Fold 2 IBS: 0.17936671257247
Fold 3 IBS: 0.1568188611817756
Fold 4 IBS: 0.14680514717804097
Fold 5 IBS: 0.2725547169298826
[I 2024-04-20 17:06:44,219] Trial 55 finished with value: 0.18755985201925895 and parameters: {'l1_ratio': 0.9439057470839547}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225320155653432
Fold 2 IBS: 0.17930755274524102
Fold 3 IBS: 0.15677628359824008
Fold 4 IBS: 0.14670209730000391
Fold 5 IBS: 0.27253968960047875
[I 2024-04-20 17:06:44,529] Trial 56 finished with value: 0.18751576496009964 and parameters: {'l1_ratio': 0.9949240408382425}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822109690254771
Fold 2 IBS: 0.17961451181713697
Fold 3 IBS: 0.15726754073421215
Fold 4 IBS: 0.1471965162691237
Fold 5 IBS: 0.2726225054862833
[I 2024-04-20 17:06:44,898] Trial 57 finished with value: 0.18778240866644663 and parameters: {'l1_ratio': 0.4713600432290703}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18223785707007079
Fold 2 IBS: 0.17949177563824611
Fold 3 IBS: 0.1570087560683171
Fold 4 IBS: 0.14695023547375666
Fold 5 IBS: 0.2725826998310214
[I 2024-04-20 17:06:45,230] Trial 58 finished with value: 0.1876542648162824 and parameters: {'l1_ratio': 0.8062139473127399}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224820856504537
Fold 2 IBS: 0.1794055937049443
Fold 3 IBS: 0.15686850644047504
Fold 4 IBS: 0.14685484158116896
Fold 5 IBS: 0.27250985215562423
[I 2024-04-20 17:06:45,588] Trial 59 finished with value: 0.18757740048945157 and parameters: {'l1_ratio': 0.9061332420978977}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224292626290942
Fold 2 IBS: 0.1794441024374527
Fold 3 IBS: 0.15697678972382687
Fold 4 IBS: 0.14690574718821955
Fold 5 IBS: 0.2725323263796256
[I 2024-04-20 17:06:45,911] Trial 60 finished with value: 0.1876203783984068 and parameters: {'l1_ratio': 0.8527642183881037}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225620880363044
Fold 2 IBS: 0.17930185321666234
Fold 3 IBS: 0.15678002878522052
Fold 4 IBS: 0.14670024819802333
Fold 5 IBS: 0.2725556711176623
[I 2024-04-20 17:06:46,253] Trial 61 finished with value: 0.1875188020242398 and parameters: {'l1_ratio': 0.998753441172107}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225057263030375
Fold 2 IBS: 0.17937871601615663
Fold 3 IBS: 0.15689662799081233
Fold 4 IBS: 0.14680797238591578
Fold 5 IBS: 0.2725302310859211
[I 2024-04-20 17:06:46,585] Trial 62 finished with value: 0.1875728240218219 and parameters: {'l1_ratio': 0.9371892220761058}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225425637201748
Fold 2 IBS: 0.179339687492195
Fold 3 IBS: 0.15684173923614844
Fold 4 IBS: 0.14675628770215932
Fold 5 IBS: 0.27254734944172476
[I 2024-04-20 17:06:46,904] Trial 63 finished with value: 0.187547864048849 and parameters: {'l1_ratio': 0.969073190292266}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224707830444076
Fold 2 IBS: 0.1794099601513333
Fold 3 IBS: 0.15693470039361418
Fold 4 IBS: 0.14686152564014035
Fold 5 IBS: 0.2725569336063111
[I 2024-04-20 17:06:47,230] Trial 64 finished with value: 0.1876020396191679 and parameters: {'l1_ratio': 0.8900038940952236}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822495573291617
Fold 2 IBS: 0.17939896423721
Fold 3 IBS: 0.15688797031384197
Fold 4 IBS: 0.1468126716814007
Fold 5 IBS: 0.27247818226235965
[I 2024-04-20 17:06:47,564] Trial 65 finished with value: 0.1875654691647948 and parameters: {'l1_ratio': 0.9263476367472074}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225319874724508
Fold 2 IBS: 0.17930582279836085
Fold 3 IBS: 0.1567772169525944
Fold 4 IBS: 0.1467016354558362
Fold 5 IBS: 0.27254366652870954
[I 2024-04-20 17:06:47,910] Trial 66 finished with value: 0.18751630809654923 and parameters: {'l1_ratio': 0.9958754797080202}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225367712123255
Fold 2 IBS: 0.1793538416668428
Fold 3 IBS: 0.15683605803794884
Fold 4 IBS: 0.14675974887440502
Fold 5 IBS: 0.27251667242387945
[I 2024-04-20 17:06:48,230] Trial 67 finished with value: 0.18754399962486173 and parameters: {'l1_ratio': 0.9614900701288679}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822491213765993
Fold 2 IBS: 0.17938954633551102
Fold 3 IBS: 0.15688146615554222
Fold 4 IBS: 0.14681564432856453
Fold 5 IBS: 0.272559121676039
[I 2024-04-20 17:06:48,559] Trial 68 finished with value: 0.18757897997445122 and parameters: {'l1_ratio': 0.9195265634855565}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18219276214127908
Fold 2 IBS: 0.17962578223494255
Fold 3 IBS: 0.1573039287068283
Fold 4 IBS: 0.14725854850841472
Fold 5 IBS: 0.2725667342014533
[I 2024-04-20 17:06:48,955] Trial 69 finished with value: 0.1877895511585836 and parameters: {'l1_ratio': 0.3481584113048518}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224590756667164
Fold 2 IBS: 0.17943634182597223
Fold 3 IBS: 0.15691923899826632
Fold 4 IBS: 0.14686856555510153
Fold 5 IBS: 0.2724998282342404
[I 2024-04-20 17:06:49,291] Trial 70 finished with value: 0.18759397643605044 and parameters: {'l1_ratio': 0.8737073141294072}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225320421937588
Fold 2 IBS: 0.17930689096666275
Fold 3 IBS: 0.15677663990781796
Fold 4 IBS: 0.1467019209063288
Fold 5 IBS: 0.27254120735382104
[I 2024-04-20 17:06:49,621] Trial 71 finished with value: 0.18751597267080128 and parameters: {'l1_ratio': 0.9952870346800783}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822561994912834
Fold 2 IBS: 0.1793025822904917
Fold 3 IBS: 0.15677898200354767
Fold 4 IBS: 0.14670076393073442
Fold 5 IBS: 0.27255119690262203
[I 2024-04-20 17:06:49,977] Trial 72 finished with value: 0.18751794492373586 and parameters: {'l1_ratio': 0.997679984608651}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225383310129098
Fold 2 IBS: 0.1793499523003413
Fold 3 IBS: 0.15683641556468486
Fold 4 IBS: 0.14675880361112942
Fold 5 IBS: 0.2725248013355793
[I 2024-04-20 17:06:50,432] Trial 73 finished with value: 0.18754476118260516 and parameters: {'l1_ratio': 0.9635382804657983}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224961670723705
Fold 2 IBS: 0.1793973080760854
Fold 3 IBS: 0.15688878909308637
Fold 4 IBS: 0.1468122895638584
Fold 5 IBS: 0.27248149990586357
[I 2024-04-20 17:06:50,900] Trial 74 finished with value: 0.18756590066922615 and parameters: {'l1_ratio': 0.9272116021515302}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822477248061211
Fold 2 IBS: 0.1794180731070332

Fold 3 IBS: 0.15694321789100807
Fold 4 IBS: 0.1468576641263616
Fold 5 IBS: 0.2724844407720259
[I 2024-04-20 17:06:51,348] Trial 75 finished with value: 0.18759022414050994 and parameters: {'l1_ratio': 0.8991728554833402}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18216275399195234
Fold 2 IBS: 0.1802289488354696
Fold 3 IBS: 0.1573965303596285
Fold 4 IBS: 0.14733515860809535
Fold 5 IBS: 0.27227111284228916
[I 2024-04-20 17:06:51,871] Trial 76 finished with value: 0.187878900927487 and parameters: {'l1_ratio': 0.11711434342988569}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18223961760864696
Fold 2 IBS: 0.17945450096558654
Fold 3 IBS: 0.157030153389453
Fold 4 IBS: 0.14694109335553382
Fold 5 IBS: 0.27255757384157153
[I 2024-04-20 17:06:52,237] Trial 77 finished with value: 0.18764458783215837 and parameters: {'l1_ratio': 0.8295696347989644}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225459643154102
Fold 2 IBS: 0.17933287216626345
Fold 3 IBS: 0.15684595773921625
Fold 4 IBS: 0.14675431528089103
Fold 5 IBS: 0.2725579021598076
[I 2024-04-20 17:06:52,592] Trial 78 finished with value: 0.18754912875554386 and parameters: {'l1_ratio': 0.9734912915250501}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822537825470813
Fold 2 IBS: 0.1793676763220374
Fold 3 IBS: 0.1568183191355863
Fold 4 IBS: 0.14680537523100656
Fold 5 IBS: 0.2725526631197539
[I 2024-04-20 17:06:52,941] Trial 79 finished with value: 0.18755956327109308 and parameters: {'l1_ratio': 0.9433584416832019}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224335154362614
Fold 2 IBS: 0.17943473850665673
Fold 3 IBS: 0.15698218457183613
Fold 4 IBS: 0.1469038657320636
Fold 5 IBS: 0.2725520255253253
[I 2024-04-20 17:06:53,329] Trial 80 finished with value: 0.18762323317590157 and parameters: {'l1_ratio': 0.8585977415767536}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225381044429292
Fold 2 IBS: 0.17931101144740427
Fold 3 IBS: 0.15677443486647447
Fold 4 IBS: 0.14670301438134464
Fold 5 IBS: 0.2725380332373481
[I 2024-04-20 17:06:53,637] Trial 81 finished with value: 0.1875160608753729 and parameters: {'l1_ratio': 0.9930447750955279}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822587975705084
Fold 2 IBS: 0.17934167926560457
Fold 3 IBS: 0.15676049157057573
Fold 4 IBS: 0.14675539995374975
Fold 5 IBS: 0.2724715943854444
[I 2024-04-20 17:06:53,968] Trial 82 finished with value: 0.18751759254917655 and parameters: {'l1_ratio': 0.9773643426600298}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822490966804634
Fold 2 IBS: 0.17939014663045655
Fold 3 IBS: 0.15688112337223353
Fold 4 IBS: 0.14681580696555074
Fold 5 IBS: 0.27255783092322494
[I 2024-04-20 17:06:54,275] Trial 83 finished with value: 0.18757880091438583 and parameters: {'l1_ratio': 0.9191681632230596}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225414370234924
Fold 2 IBS: 0.1793797961778674
Fold 3 IBS: 0.15682323571785636
Fold 4 IBS: 0.1467658978891538
Fold 5 IBS: 0.2725653611467702
[I 2024-04-20 17:06:54,626] Trial 84 finished with value: 0.18755768692679942 and parameters: {'l1_ratio': 0.9483381255341643}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822532765538995
Fold 2 IBS: 0.17930872717472238
Fold 3 IBS: 0.15677565327607665
Fold 4 IBS: 0.14670240964095654
Fold 5 IBS: 0.2725370059060274
[I 2024-04-20 17:06:54,932] Trial 85 finished with value: 0.18751541451033651 and parameters: {'l1_ratio': 0.994282472719398}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822548736568796
Fold 2 IBS: 0.17935981698467637
Fold 3 IBS: 0.15683304929317096
Fold 4 IBS: 0.14676120033187837
Fold 5 IBS: 0.2725043030687943
[I 2024-04-20 17:06:55,234] Trial 86 finished with value: 0.18754264866707993 and parameters: {'l1_ratio': 0.9583808358858049}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822200039350858
Fold 2 IBS: 0.17956065003402516
Fold 3 IBS: 0.1572244801262601
Fold 4 IBS: 0.14713956784551238
Fold 5 IBS: 0.27258252885230416
[I 2024-04-20 17:06:55,554] Trial 87 finished with value: 0.18774544615863753 and parameters: {'l1_ratio': 0.5802991656169367}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822479293937865
Fold 2 IBS: 0.17941274403577848
Fold 3 IBS: 0.15694592565790505
Fold 4 IBS: 0.14685646293495566
Fold 5 IBS: 0.27249510091633866
[I 2024-04-20 17:06:55,872] Trial 88 finished with value: 0.18759163258775285 and parameters: {'l1_ratio': 0.9021156822677737}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225555400814283
Fold 2 IBS: 0.17933277437635908
Fold 3 IBS: 0.1567649604722715
Fold 4 IBS: 0.14675341810039916
Fold 5 IBS: 0.2724902573881179
[I 2024-04-20 17:06:56,209] Trial 89 finished with value: 0.18751939286905808 and parameters: {'l1_ratio': 0.9818045165285653}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225367515384847
Fold 2 IBS: 0.17937029411190647
Fold 3 IBS: 0.15681684911421875
Fold 4 IBS: 0.14680599462772337
Fold 5 IBS: 0.2725471003866118
[I 2024-04-20 17:06:56,559] Trial 90 finished with value: 0.18755878267886178 and parameters: {'l1_ratio': 0.941877430212866}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225619249081973
Fold 2 IBS: 0.1793040166679638
Fold 3 IBS: 0.15677819784098873
Fold 4 IBS: 0.14670115080804702
Fold 5 IBS: 0.27254784869761456
[I 2024-04-20 17:06:56,930] Trial 91 finished with value: 0.18751748130108678 and parameters: {'l1_ratio': 0.9968774792347929}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225439997189125
Fold 2 IBS: 0.17933628065874013
Fold 3 IBS: 0.1568435269479547
Fold 4 IBS: 0.14675544899235055
Fold 5 IBS: 0.2725486286876232
[I 2024-04-20 17:06:57,250] Trial 92 finished with value: 0.18754765705171195 and parameters: {'l1_ratio': 0.9709422607290489}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224974551394899
Fold 2 IBS: 0.17939374430922292
Fold 3 IBS: 0.1568905630274779
Fold 4 IBS: 0.14681147757765306
Fold 5 IBS: 0.2724886938523938
[I 2024-04-20 17:06:57,579] Trial 93 finished with value: 0.18756684485613934 and parameters: {'l1_ratio': 0.9290872015280003}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18224658836783428
Fold 2 IBS: 0.17942029217462838
Fold 3 IBS: 0.1569282336395929
Fold 4 IBS: 0.1468644015266648
Fold 5 IBS: 0.27253298503220175
[I 2024-04-20 17:06:57,930] Trial 94 finished with value: 0.1875985001481844 and parameters: {'l1_ratio': 0.8831351144683814}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225621251852267
Fold 2 IBS: 0.17930101284772287
Fold 3 IBS: 0.15678049209117895
Fold 4 IBS: 0.14670002018482858
Fold 5 IBS: 0.27255765319547576
[I 2024-04-20 17:06:58,273] Trial 95 finished with value: 0.1875190781675458 and parameters: {'l1_ratio': 0.9992293711402211}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822546372662088
Fold 2 IBS: 0.17933192791545252
Fold 3 IBS: 0.15675710521603017
Fold 4 IBS: 0.14675408144528324
Fold 5 IBS: 0.27255999134371955
[I 2024-04-20 17:06:58,601] Trial 96 finished with value: 0.18753154863733884 and parameters: {'l1_ratio': 0.9740198810451595}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225435722378863
Fold 2 IBS: 0.17937384368829937
Fold 3 IBS: 0.15682612038068988
Fold 4 IBS: 0.14676447589134173
Fold 5 IBS: 0.2725763493353596
[I 2024-04-20 17:06:58,910] Trial 97 finished with value: 0.18755902930389587 and parameters: {'l1_ratio': 0.9512752795511406}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.1822485307596809
Fold 2 IBS: 0.17940293820827874
Fold 3 IBS: 0.1568732348143556
Fold 4 IBS: 0.14681957800704123
Fold 5 IBS: 0.2725275372759781
[I 2024-04-20 17:06:59,233] Trial 98 finished with value: 0.18757436381306694 and parameters: {'l1_ratio': 0.9109871118742077}. Best is trial 17 with value: 0.18751239753557997.
Fold 1 IBS: 0.18225891669177577
Fold 2 IBS: 0.17933847626588711
Fold 3 IBS: 0.15676214146141793
Fold 4 IBS: 0.1467546655079086
Fold 5 IBS: 0.2724784440370166
[I 2024-04-20 17:06:59,545] Trial 99 finished with value: 0.1875185287928012 and parameters: {'l1_ratio': 0.9790007182346007}. Best is trial 17 with value: 0.18751239753557997.


* Best trial for IBS:
 FrozenTrial(number=17, state=TrialState.COMPLETE, values=[0.18751239753557997], datetime_start=datetime.datetime(2024, 4, 20, 17, 6, 29, 284465), datetime_complete=datetime.datetime(2024, 4, 20, 17, 6, 29, 612172), params={'l1_ratio': 0.9853615392538034}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=17, value=None)


* Best Score for IBS:
 0.18751239753557997

In [52]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [53]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.756
train_ibs:  0.188

#### Test

In [54]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [55]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.582

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.9853615392538034)

test_ibs:  0.287

In [56]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [57]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-20 17:06:59,839] A new study created in memory with name: no-name-3e1b683d-6879-41eb-9feb-f5e82ae66a49

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6339285714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6408450704225352
[I 2024-04-20 17:07:02,451] Trial 0 finished with value: 0.7372744686944293 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7372744686944293.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 17:07:04,114] Trial 1 finished with value: 0.74027341750814 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.74027341750814.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:07:05,570] Trial 2 finished with value: 0.7431341569351123 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:07:06,080] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:07:06,705] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 17:07:09,291] Trial 5 finished with value: 0.7299704758481619 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.75
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 17:07:11,685] Trial 6 finished with value: 0.7171141106323402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:07:12,808] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 17:07:16,298] Trial 8 finished with value: 0.5225352112676056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 17:07:18,124] Trial 9 finished with value: 0.7250144025097357 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:07:18,280] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:07:19,232] Trial 11 finished with value: 0.7414728561808361 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1579906038170908, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6785714285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:07:20,134] Trial 12 finished with value: 0.7380805853192668 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 147, 'oob_score': False, 'max_samples': 0.8619834498485652, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1611753146667314, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:07:20,777] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1567471583060459, 'warm_start': False}. Best is trial 2 with value: 0.7431341569351123.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7464788732394366
[I 2024-04-20 17:07:21,458] Trial 14 finished with value: 0.8012393138587386 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1306449501762567, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7370892018779343
[I 2024-04-20 17:07:22,342] Trial 15 finished with value: 0.7949512064262649 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 197, 'oob_score': True, 'max_samples': 0.9835664616143871, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0921839163034627, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7230046948356808
[I 2024-04-20 17:07:22,687] Trial 16 finished with value: 0.7913196149300414 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9622193970781673, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07748782870655765, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8839662447257384
Fold 5 C-index: 0.7417840375586855
[I 2024-04-20 17:07:23,285] Trial 17 finished with value: 0.7952544618554078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.8172323984404596, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10327357472994507, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:07:23,740] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.525862463381169, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7089201877934272
[I 2024-04-20 17:07:23,881] Trial 19 finished with value: 0.7740929694743747 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.8094383772852811, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2171861810731355, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-20 17:07:24,627] Trial 20 finished with value: 0.7896403509052692 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.7024632981250558, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11709282828400099, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7276995305164319
[I 2024-04-20 17:07:25,399] Trial 21 finished with value: 0.7918532818563494 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.8592332834187432, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09213353726970255, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7323943661971831
[I 2024-04-20 17:07:26,371] Trial 22 finished with value: 0.7987506334970494 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9966124899846646, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.006871014098231751, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7230046948356808
[I 2024-04-20 17:07:27,345] Trial 23 finished with value: 0.7965507033377867 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8404793290892639, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-20 17:07:28,221] Trial 24 finished with value: 0.8010124032513863 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.8944464461493312, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003220931076182737, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:07:29,308] Trial 25 finished with value: 0.8009100471985094 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 244, 'oob_score': True, 'max_samples': 0.9947609548616138, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04884572997850131, 'warm_start': True}. Best is trial 14 with value: 0.8012393138587386.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7511737089201878
[I 2024-04-20 17:07:30,493] Trial 26 finished with value: 0.8019323166712997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 330, 'oob_score': True, 'max_samples': 0.8936722563667562, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7370892018779343
[I 2024-04-20 17:07:31,781] Trial 27 finished with value: 0.7848754931720334 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.7589607003643692, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05616441169904532, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6502347417840375
[I 2024-04-20 17:07:33,176] Trial 28 finished with value: 0.7687300510570361 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.47643241204116027, 'max_features': None, 'min_weight_fraction_leaf': 0.21228506833672414, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.7136150234741784
[I 2024-04-20 17:07:34,874] Trial 29 finished with value: 0.791216072808157 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18639977321756945, 'warm_start': True}. Best is trial 26 with value: 0.8019323166712997.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-20 17:07:36,257] Trial 30 finished with value: 0.8141045941707695 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.8995699838431843, 'max_features': None, 'min_weight_fraction_leaf': 0.048019257453591285, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-20 17:07:37,517] Trial 31 finished with value: 0.8102976168343801 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.8965443067001324, 'max_features': None, 'min_weight_fraction_leaf': 0.04869831874272522, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:07:38,723] Trial 32 finished with value: 0.8044151254239035 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.7822231835771817, 'max_features': None, 'min_weight_fraction_leaf': 0.05953475058332531, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.755868544600939
[I 2024-04-20 17:07:40,087] Trial 33 finished with value: 0.8002008917150547 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.7587808099894491, 'max_features': None, 'min_weight_fraction_leaf': 0.06414988767677843, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-20 17:07:41,597] Trial 34 finished with value: 0.802539604149412 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'max_samples': 0.9277369756073641, 'max_features': None, 'min_weight_fraction_leaf': 0.13073113131665734, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:07:43,503] Trial 35 finished with value: 0.8025908514105005 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 399, 'oob_score': True, 'max_samples': 0.9215912670469352, 'max_features': None, 'min_weight_fraction_leaf': 0.12213968035691111, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:07:45,352] Trial 36 finished with value: 0.8030592181442181 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.7521477069490586, 'max_features': None, 'min_weight_fraction_leaf': 0.028614277170057895, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.7745098039215687
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:07:46,501] Trial 37 finished with value: 0.7924417951105628 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.6723788047810191, 'max_features': None, 'min_weight_fraction_leaf': 0.027521497544371276, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:07:48,507] Trial 38 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.7390641925180915, 'max_features': None, 'min_weight_fraction_leaf': 0.0747020966452816, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6455399061032864
[I 2024-04-20 17:07:50,264] Trial 39 finished with value: 0.770986545074277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.6220569630425845, 'max_features': None, 'min_weight_fraction_leaf': 0.2635408988115671, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:07:51,451] Trial 40 finished with value: 0.8014911829899953 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.5663987587631532, 'max_features': None, 'min_weight_fraction_leaf': 0.07499456126338316, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:07:53,307] Trial 41 finished with value: 0.8059128596008007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 439, 'oob_score': True, 'max_samples': 0.7534073290864295, 'max_features': None, 'min_weight_fraction_leaf': 0.03371263169436823, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.8705357142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.755868544600939
[I 2024-04-20 17:07:55,226] Trial 42 finished with value: 0.8004185708465463 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.7191743052052858, 'max_features': None, 'min_weight_fraction_leaf': 0.03134587591441676, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:07:56,841] Trial 43 finished with value: 0.8044421817009597 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7630755401354222, 'max_features': None, 'min_weight_fraction_leaf': 0.08864460050779976, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8776371308016878
Fold 5 C-index: 0.7605633802816901
[I 2024-04-20 17:07:58,693] Trial 44 finished with value: 0.7970569598688273 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.6530853458961033, 'max_features': None, 'min_weight_fraction_leaf': 0.0960200605067859, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:07:59,516] Trial 45 finished with value: 0.8063373500099402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.7241711356177275, 'max_features': None, 'min_weight_fraction_leaf': 0.03945374601794358, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.65625
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:08:03,000] Trial 46 finished with value: 0.7213832269889107 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.7253224444871529, 'max_features': None, 'min_weight_fraction_leaf': 0.03678143977799287, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.7696078431372549
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-20 17:08:03,690] Trial 47 finished with value: 0.7895586843791148 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.3630824057039081, 'max_features': None, 'min_weight_fraction_leaf': 0.07375724144112171, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.636150234741784
[I 2024-04-20 17:08:06,828] Trial 48 finished with value: 0.7518177358789349 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.8664880785038714, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.38812198780775825, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7276995305164319
[I 2024-04-20 17:08:07,688] Trial 49 finished with value: 0.79501517952681 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.8009921187460273, 'max_features': None, 'min_weight_fraction_leaf': 0.14468128914092981, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7605633802816901
[I 2024-04-20 17:08:08,193] Trial 50 finished with value: 0.8025838944631485 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.5979222342836801, 'max_features': None, 'min_weight_fraction_leaf': 0.010569144430309353, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:08:09,177] Trial 51 finished with value: 0.8027595552556749 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.737951588098304, 'max_features': None, 'min_weight_fraction_leaf': 0.08276842957644326, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:10,632] Trial 52 finished with value: 0.8046323522601799 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.88848382237019, 'max_features': None, 'min_weight_fraction_leaf': 0.10800154944324664, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7323943661971831
[I 2024-04-20 17:08:11,612] Trial 53 finished with value: 0.800061200877051 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 421, 'oob_score': False, 'max_samples': 0.9477043092007602, 'max_features': None, 'min_weight_fraction_leaf': 0.1769969783833071, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:13,061] Trial 54 finished with value: 0.8075268254192226 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.8862399763900326, 'max_features': None, 'min_weight_fraction_leaf': 0.04347302641797581, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7605633802816901
[I 2024-04-20 17:08:14,200] Trial 55 finished with value: 0.8100342825585477 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.8308423379101402, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04184905264916955, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8649789029535865
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:08:16,911] Trial 56 finished with value: 0.7307990843706159 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 282, 'oob_score': True, 'max_samples': 0.8390380366939857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04576803383695833, 'warm_start': False}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8660714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.755868544600939
[I 2024-04-20 17:08:17,555] Trial 57 finished with value: 0.8035130393589224 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.862792308947798, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06959281888785387, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:08:18,729] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9167198766277185, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 30 with value: 0.8141045941707695.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:08:19,621] Trial 59 finished with value: 0.8154047485458795 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.960673091645226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.016185485823452278, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.6383928571428571
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6666666666666666
[I 2024-04-20 17:08:22,006] Trial 60 finished with value: 0.7281182409672728 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 259, 'oob_score': True, 'max_samples': 0.9694253886674298, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.017099050018490658, 'warm_start': False}. Best is trial 59 with value: 0.8154047485458795.

Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:08:23,190] Trial 61 finished with value: 0.8091270566720341 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.8024635915627699, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04437120929765639, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7699530516431925
[I 2024-04-20 17:08:24,275] Trial 62 finished with value: 0.8100170485218674 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.8255198768266782, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04384835034305919, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7699530516431925
[I 2024-04-20 17:08:25,344] Trial 63 finished with value: 0.8116391962302029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.8867126274469075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018776766987265683, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-20 17:08:26,274] Trial 64 finished with value: 0.805082894192702 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.822935057311086, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012420915832592992, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:27,191] Trial 65 finished with value: 0.8127164933462323 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 210, 'oob_score': True, 'max_samples': 0.9479411108137946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019799142307208247, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:27,839] Trial 66 finished with value: 0.8152263609296293 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.9503349354445524, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02249332834269111, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:28,584] Trial 67 finished with value: 0.8117067729375418 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.947093672368275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01713780998356157, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:29,246] Trial 68 finished with value: 0.8089947790490772 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.944193226589343, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002610024525408112, 'warm_start': True}. Best is trial 59 with value: 0.8154047485458795.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7934272300469484
[I 2024-04-20 17:08:29,977] Trial 69 finished with value: 0.816613418694436 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.9994241275208928, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.018458075829861618, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:30,923] Trial 70 finished with value: 0.8107505717647113 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.9759466742205646, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.020962084356569866, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:31,795] Trial 71 finished with value: 0.809906689908171 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 213, 'oob_score': True, 'max_samples': 0.9691411143781642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019131120871457744, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.7934272300469484
[I 2024-04-20 17:08:32,679] Trial 72 finished with value: 0.8163018383661023 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 172, 'oob_score': True, 'max_samples': 0.9857485121561103, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.019949674867014808, 'warm_start': True}. Best is trial 69 with value: 0.816613418694436.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7934272300469484
[I 2024-04-20 17:08:33,417] Trial 73 finished with value: 0.8209526975590314 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 179, 'oob_score': True, 'max_samples': 0.9999465776424662, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0037053086158703695, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:34,051] Trial 74 finished with value: 0.8089728600398164 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.9451824063260522, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006367895628996485, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:34,985] Trial 75 finished with value: 0.8193500558621478 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.9983757102481674, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.00202750601418214, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:08:35,735] Trial 76 finished with value: 0.8120677808474076 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 190, 'oob_score': True, 'max_samples': 0.992384429953266, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06509728021815406, 'warm_start': True}. Best is trial 73 with value: 0.8209526975590314.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9113924050632911
Fold 5 C-index: 0.8028169014084507
[I 2024-04-20 17:08:36,302] Trial 77 finished with value: 0.8245454518214682 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'max_samples': 0.994249602929978, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003950036087865894, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7934272300469484
[I 2024-04-20 17:08:36,892] Trial 78 finished with value: 0.8200379214069133 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 139, 'oob_score': True, 'max_samples': 0.9921516335417828, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0013870857819101067, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7746478873239436
[I 2024-04-20 17:08:37,451] Trial 79 finished with value: 0.8145453138629154 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 131, 'oob_score': True, 'max_samples': 0.9936071962591497, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.001248251048872611, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6428571428571429
Fold 3 C-index: 0.7598039215686274
Fold 4 C-index: 0.8734177215189873
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:08:38,475] Trial 80 finished with value: 0.7350889356536794 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'max_samples': 0.9980073532203214, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.027351555411740894, 'warm_start': False}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-20 17:08:39,052] Trial 81 finished with value: 0.814530945119259 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 134, 'oob_score': True, 'max_samples': 0.974317190473141, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.008552111924736726, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:39,398] Trial 82 finished with value: 0.818405951458202 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 73, 'oob_score': True, 'max_samples': 0.9200032426792089, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.004694893977022773, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8987341772151899
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:39,732] Trial 83 finished with value: 0.816209618379516 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.9644628063092593, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05687217713082389, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7699530516431925
[I 2024-04-20 17:08:39,982] Trial 84 finished with value: 0.8122353006098141 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 43, 'oob_score': True, 'max_samples': 0.925618686700756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.002296274259735591, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:40,588] Trial 85 finished with value: 0.8104992933979698 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.912496637320817, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06207048371618876, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:41,177] Trial 86 finished with value: 0.8114849995979849 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.97217788579977, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03336570424835292, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:41,591] Trial 87 finished with value: 0.8229024307173397 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 90, 'oob_score': True, 'max_samples': 0.9977866104840274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05743230682168733, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.784037558685446
[I 2024-04-20 17:08:41,995] Trial 88 finished with value: 0.8163898256753228 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 87, 'oob_score': True, 'max_samples': 0.9290745100371565, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.055244525623157625, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.8325892857142857
Fold 3 C-index: 0.7034313725490197
Fold 4 C-index: 0.7721518987341772
Fold 5 C-index: 0.755868544600939
[I 2024-04-20 17:08:42,578] Trial 89 finished with value: 0.7348861423976064 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.16405866867269464, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03211514251936686, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.715962441314554
[I 2024-04-20 17:08:42,824] Trial 90 finished with value: 0.7889841593617299 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 44, 'oob_score': True, 'max_samples': 0.9275901377744842, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2513921457170648, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.9029535864978903
Fold 5 C-index: 0.7793427230046949
[I 2024-04-20 17:08:43,235] Trial 91 finished with value: 0.8154508585391724 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9984694614507701, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05353258404318052, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.704225352112676
[I 2024-04-20 17:08:43,593] Trial 92 finished with value: 0.7935889758097764 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.9795045559078126, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.30990393575918357, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8860759493670886
Fold 5 C-index: 0.7934272300469484
[I 2024-04-20 17:08:44,121] Trial 93 finished with value: 0.8139388966416563 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 93, 'oob_score': True, 'max_samples': 0.9084682802153162, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.056428548931904784, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7699530516431925
[I 2024-04-20 17:08:44,444] Trial 94 finished with value: 0.8132041893160448 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 62, 'oob_score': True, 'max_samples': 0.9288744492993337, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08347470326932997, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.7652582159624414
[I 2024-04-20 17:08:45,156] Trial 95 finished with value: 0.8036708753502536 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9612484718465076, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09744509645373221, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8945147679324894
Fold 5 C-index: 0.7887323943661971
[I 2024-04-20 17:08:45,679] Trial 96 finished with value: 0.8082626231905751 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 146, 'oob_score': True, 'max_samples': 0.8773134009465923, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0004414494070137942, 'warm_start': True}. Best is trial 77 with value: 0.8245454518214682.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.9071729957805907
Fold 5 C-index: 0.7981220657276995
[I 2024-04-20 17:08:46,284] Trial 97 finished with value: 0.825818370590428 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6924882629107981
[I 2024-04-20 17:08:46,802] Trial 98 finished with value: 0.7931972050153308 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9818733759466801, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.34016797358596224, 'warm_start': True}. Best is trial 97 with value: 0.825818370590428.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6473214285714286
Fold 3 C-index: 0.75
Fold 4 C-index: 0.869198312236287

[I 2024-04-20 17:08:47,845] A new study created in memory with name: no-name-e1d86678-838b-4b57-bd79-1dc1843daeb7

Fold 5 C-index: 0.6948356807511737
[I 2024-04-20 17:08:47,841] Trial 99 finished with value: 0.733396625437319 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.9114919789954895, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.031714611388828556, 'warm_start': False}. Best is trial 97 with value: 0.825818370590428.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.825818370590428], datetime_start=datetime.datetime(2024, 4, 20, 17, 8, 45, 683128), datetime_complete=datetime.datetime(2024, 4, 20, 17, 8, 46, 284059), params={'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9995515317027949, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.032175807966512454, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=97, value=None)


* Best Score for C-index:
 0.825818370590428

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.1750328804590392
Fold 2 IBS: 0.2457909346263125
Fold 3 IBS: 0.16304371295824233
Fold 4 IBS: 0.15636010174832157
Fold 5 IBS: 0.23719057610640573
[I 2024-04-20 17:08:50,285] Trial 0 finished with value: 0.19548364117966427 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.19548364117966427.
Fold 1 IBS: 0.18431216543925236
Fold 2 IBS: 0.20449576284397977
Fold 3 IBS: 0.1734496564138547
Fold 4 IBS: 0.1702249879841256
Fold 5 IBS: 0.22320286146192567
[I 2024-04-20 17:08:50,893] Trial 1 finished with value: 0.19113708682862765 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-20 17:08:51,282] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-20 17:08:53,016] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-20 17:08:54,501] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.19113708682862765.
Fold 1 IBS: 0.18112177909144025
Fold 2 IBS: 0.21559325389144568
Fold 3 IBS: 0.16126717086083114
Fold 4 IBS: 0.14612944369048034
Fold 5 IBS: 0.2233514487463136
[I 2024-04-20 17:08:56,420] Trial 5 finished with value: 0.1854926192561022 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.1741078934640366
Fold 2 IBS: 0.20103465197964324
Fold 3 IBS: 0.16459803471117013
Fold 4 IBS: 0.16185722968286678
Fold 5 IBS: 0.2275095895598425
[I 2024-04-20 17:08:58,367] Trial 6 finished with value: 0.18582147987951186 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2112963873415951
Fold 2 IBS: 0.2163217730619842
Fold 3 IBS: 0.20084732748350573
Fold 4 IBS: 0.218588755276252
Fold 5 IBS: 0.21598442308805077
[I 2024-04-20 17:09:00,556] Trial 7 finished with value: 0.21260773325027754 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-20 17:09:03,959] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.184925661127663
Fold 2 IBS: 0.2085223967682221
Fold 3 IBS: 0.17516209049302708
Fold 4 IBS: 0.17855956510549414
Fold 5 IBS: 0.2209085976393104
[I 2024-04-20 17:09:04,650] Trial 9 finished with value: 0.19361566222674337 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-20 17:09:08,173] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18095919781067835
Fold 2 IBS: 0.20577163118124792
Fold 3 IBS: 0.1716987840867246
Fold 4 IBS: 0.17502946521027946
Fold 5 IBS: 0.2198343004178619
[I 2024-04-20 17:09:09,992] Trial 11 finished with value: 0.19065867574135845 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17390057719337093
Fold 2 IBS: 0.20052745262326843
Fold 3 IBS: 0.1641107464885408
Fold 4 IBS: 0.161310620284919
Fold 5 IBS: 0.22799428371541863
[I 2024-04-20 17:09:11,786] Trial 12 finished with value: 0.18556873606110355 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18027770462477655
Fold 2 IBS: 0.21277323191047734
Fold 3 IBS: 0.16455120069297058
Fold 4 IBS: 0.1566383560604833
Fold 5 IBS: 0.22277178793167127
[I 2024-04-20 17:09:12,941] Trial 13 finished with value: 0.1874024562440758 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.19012850590013755
Fold 2 IBS: 0.2508215358616786
Fold 3 IBS: 0.16250392476408873
Fold 4 IBS: 0.13720938920743592
Fold 5 IBS: 0.2363581833511397
[I 2024-04-20 17:09:15,749] Trial 14 finished with value: 0.1954043078168961 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 342, 'oob_score': False, 'max_samples': 0.8286563887351183, 'max_features': None, 'min_weight_fraction_leaf': 0.09422981531813096}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.18457894361619234
Fold 2 IBS: 0.20704365739729078
Fold 3 IBS: 0.17241207107928186
Fold 4 IBS: 0.17174770550689625
Fold 5 IBS: 0.21936818212879036
[I 2024-04-20 17:09:18,205] Trial 15 finished with value: 0.1910301119456903 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.6817544899569143, 'max_features': 'auto', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 5 with value: 0.1854926192561022.

Fold 1 IBS: 0.1827776694681521
Fold 2 IBS: 0.20934680739331213
Fold 3 IBS: 0.16890212120236864
Fold 4 IBS: 0.1686588011660482
Fold 5 IBS: 0.2195767733572381
[I 2024-04-20 17:09:19,847] Trial 16 finished with value: 0.18985243451742384 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 259, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24786833673530304}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140210250926074
Fold 2 IBS: 0.22165374242688704
Fold 3 IBS: 0.20482992077952775
Fold 4 IBS: 0.2248506856151436
Fold 5 IBS: 0.21866286292181575
[I 2024-04-20 17:09:20,823] Trial 17 finished with value: 0.2168036473671963 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.6340112818214192, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3527363076520275}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.21398207456199575
Fold 2 IBS: 0.2210878885925555
Fold 3 IBS: 0.20500084248625938
Fold 4 IBS: 0.22467759051518113
Fold 5 IBS: 0.21837641563069746
[I 2024-04-20 17:09:22,967] Trial 18 finished with value: 0.21662496235733783 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 295, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4936228322884221}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17751239261549384
Fold 2 IBS: 0.25254123379304744
Fold 3 IBS: 0.17260860317747417
Fold 4 IBS: 0.15329948726148748
Fold 5 IBS: 0.23725228156825823
[I 2024-04-20 17:09:23,140] Trial 19 finished with value: 0.1986427996831522 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.7744054221786105, 'max_features': None, 'min_weight_fraction_leaf': 0.15294426956488405}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.2140058010941674
Fold 2 IBS: 0.22070271305097472
Fold 3 IBS: 0.20512571269324692
Fold 4 IBS: 0.2244581340346379
Fold 5 IBS: 0.2175740773836072
[I 2024-04-20 17:09:24,330] Trial 20 finished with value: 0.21637328765132682 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': None, 'min_weight_fraction_leaf': 0.3111340864325056}. Best is trial 5 with value: 0.1854926192561022.
Fold 1 IBS: 0.17301280315188314
Fold 2 IBS: 0.19545931456517315
Fold 3 IBS: 0.1650054298323013
Fold 4 IBS: 0.1623577222774968
Fold 5 IBS: 0.22550368553678712
[I 2024-04-20 17:09:26,156] Trial 21 finished with value: 0.1842677910727283 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8774254573678859, 'max_features': None, 'min_weight_fraction_leaf': 0.38285115003898385}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17215244177111103
Fold 2 IBS: 0.18853820269712923
Fold 3 IBS: 0.16580216324267041
Fold 4 IBS: 0.16693346335577489
Fold 5 IBS: 0.22851547915283357
[I 2024-04-20 17:09:28,316] Trial 22 finished with value: 0.1843883500439038 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8533162629857436, 'max_features': None, 'min_weight_fraction_leaf': 0.39473610054688535}. Best is trial 21 with value: 0.1842677910727283.
Fold 1 IBS: 0.17177605757487213
Fold 2 IBS: 0.1873134062038458
Fold 3 IBS: 0.16528873750502146
Fold 4 IBS: 0.16415554447420388
Fold 5 IBS: 0.22606704734165115
[I 2024-04-20 17:09:30,712] Trial 23 finished with value: 0.1829201586199189 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17276619506594362
Fold 2 IBS: 0.18752575408286087
Fold 3 IBS: 0.1660506832687537
Fold 4 IBS: 0.16535591796486823
Fold 5 IBS: 0.2269916388177798
[I 2024-04-20 17:09:33,880] Trial 24 finished with value: 0.18373803784004125 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.911762237036045, 'max_features': None, 'min_weight_fraction_leaf': 0.4145963396824019}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1791579050529914
Fold 2 IBS: 0.18710203409403112
Fold 3 IBS: 0.17160657333121804
Fold 4 IBS: 0.1730776073587778
Fold 5 IBS: 0.23520287606237242
[I 2024-04-20 17:09:36,570] Trial 25 finished with value: 0.18922939917987816 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 474, 'oob_score': False, 'max_samples': 0.9270259482202138, 'max_features': None, 'min_weight_fraction_leaf': 0.44717127940994156}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17277943380976452
Fold 2 IBS: 0.20056722047631442
Fold 3 IBS: 0.1648928002543546
Fold 4 IBS: 0.16219739373996186
Fold 5 IBS: 0.22641514420706116
[I 2024-04-20 17:09:39,509] Trial 26 finished with value: 0.18537039849749132 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.9129740059593043, 'max_features': None, 'min_weight_fraction_leaf': 0.3870919920523195}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17240759648455306
Fold 2 IBS: 0.18549219526338728
Fold 3 IBS: 0.16616481950290676
Fold 4 IBS: 0.16561034850301004
Fold 5 IBS: 0.22653216582265312
[I 2024-04-20 17:09:41,685] Trial 27 finished with value: 0.18324142511530206 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.9882040097907008, 'max_features': None, 'min_weight_fraction_leaf': 0.45340256450947913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.173798138626336
Fold 2 IBS: 0.18532321108542035
Fold 3 IBS: 0.1668142641939112
Fold 4 IBS: 0.16714200768594834
Fold 5 IBS: 0.2276860831891378
[I 2024-04-20 17:09:44,306] Trial 28 finished with value: 0.18415274095615075 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.9741542767559068, 'max_features': None, 'min_weight_fraction_leaf': 0.450638299943646}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.213981238234591
Fold 2 IBS: 0.22129600200231184
Fold 3 IBS: 0.20476687908413987
Fold 4 IBS: 0.22462916295400534
Fold 5 IBS: 0.21851703166023365
[I 2024-04-20 17:09:46,328] Trial 29 finished with value: 0.21663806278705633 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.773357424692515, 'max_features': None, 'min_weight_fraction_leaf': 0.4837438075147879}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17449266503317365
Fold 2 IBS: 0.19742695190345053
Fold 3 IBS: 0.16471477798087575
Fold 4 IBS: 0.16267147593706363
Fold 5 IBS: 0.22648735220891497
[I 2024-04-20 17:09:48,463] Trial 30 finished with value: 0.18515864461269568 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 377, 'oob_score': False, 'max_samples': 0.9986438777088522, 'max_features': None, 'min_weight_fraction_leaf': 0.42773069772809913}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18186563850382112
Fold 2 IBS: 0.18838226339150496
Fold 3 IBS: 0.1747206639662102
Fold 4 IBS: 0.17560736221213202
Fold 5 IBS: 0.23404857262959045
[I 2024-04-20 17:09:51,050] Trial 31 finished with value: 0.19092490014065175 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.939658841329532, 'max_features': None, 'min_weight_fraction_leaf': 0.4524256463348925}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398563901141657
Fold 2 IBS: 0.22134596740550985
Fold 3 IBS: 0.2048025990579434
Fold 4 IBS: 0.22461415055237854
Fold 5 IBS: 0.21851803782809134
[I 2024-04-20 17:09:53,536] Trial 32 finished with value: 0.21665327877106794 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 451, 'oob_score': False, 'max_samples': 0.7396444271446992, 'max_features': None, 'min_weight_fraction_leaf': 0.4501495537267681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19337121417130673
Fold 2 IBS: 0.19511882700454072
Fold 3 IBS: 0.18642967451701625
Fold 4 IBS: 0.1895345717679471
Fold 5 IBS: 0.21856358775020004
[I 2024-04-20 17:09:56,380] Trial 33 finished with value: 0.19660357504220216 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 493, 'oob_score': False, 'max_samples': 0.9933327757837453, 'max_features': None, 'min_weight_fraction_leaf': 0.49338351231891625}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397810999123087
Fold 2 IBS: 0.22130875696604183
Fold 3 IBS: 0.2047621585928816
Fold 4 IBS: 0.2246288907097577
Fold 5 IBS: 0.21863208708031015
[I 2024-04-20 17:09:58,615] Trial 34 finished with value: 0.21666200066804442 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 443, 'oob_score': False, 'max_samples': 0.8938554646810188, 'max_features': None, 'min_weight_fraction_leaf': 0.45754449369723726}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397501954215553
Fold 2 IBS: 0.22130442891193944
Fold 3 IBS: 0.20482836466241144
Fold 4 IBS: 0.22464430529398755
Fold 5 IBS: 0.22545436387504872
[I 2024-04-20 17:10:01,298] Trial 35 finished with value: 0.2180412964571085 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 382, 'oob_score': True, 'max_samples': 0.8179898225635556, 'max_features': None, 'min_weight_fraction_leaf': 0.406528295392146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18423128002886327
Fold 2 IBS: 0.20075733721613034
Fold 3 IBS: 0.17640819175973563
Fold 4 IBS: 0.18326652441136565
Fold 5 IBS: 0.21536169700367772
[I 2024-04-20 17:10:03,793] Trial 36 finished with value: 0.1920050060839545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9504880220263004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3678752707538403}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398603848843456
Fold 2 IBS: 0.2212516593844012
Fold 3 IBS: 0.20480476599516775
Fold 4 IBS: 0.22467106118379263
Fold 5 IBS: 0.2186056754258949
[I 2024-04-20 17:10:05,887] Trial 37 finished with value: 0.2166638400955382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.6134779412492984, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42910258289196446}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736188003490057
Fold 2 IBS: 0.19364285777259932
Fold 3 IBS: 0.1647798135113072
Fold 4 IBS: 0.1633666298088931
Fold 5 IBS: 0.22711044098051275
[I 2024-04-20 17:10:07,707] Trial 38 finished with value: 0.18450370848446362 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 320, 'oob_score': False, 'max_samples': 0.7324083825350811, 'max_features': None, 'min_weight_fraction_leaf': 0.3267902150060746}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17613246987510892
Fold 2 IBS: 0.25370396104689813
Fold 3 IBS: 0.16470531172106329
Fold 4 IBS: 0.15671091985566343
Fold 5 IBS: 0.23754782764703308
[I 2024-04-20 17:10:10,455] Trial 39 finished with value: 0.19776009802915337 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.8998447540408812, 'max_features': None, 'min_weight_fraction_leaf': 0.26335636534084506}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139718451769373
Fold 2 IBS: 0.22132290174406308
Fold 3 IBS: 0.2049379534123754
Fold 4 IBS: 0.2246651821236489
Fold 5 IBS: 0.21845691499847839
[I 2024-04-20 17:10:12,296] Trial 40 finished with value: 0.21667095949110057 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.5051356852082238, 'max_features': None, 'min_weight_fraction_leaf': 0.46950692236254693}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1736115784806322
Fold 2 IBS: 0.19708658583278066
Fold 3 IBS: 0.1647004041861114
Fold 4 IBS: 0.16193266728653144
Fold 5 IBS: 0.2269439330088383
[I 2024-04-20 17:10:14,058] Trial 41 finished with value: 0.1848550337589788 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.8766530642885175, 'max_features': None, 'min_weight_fraction_leaf': 0.37480517219328874}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17445559716534967
Fold 2 IBS: 0.20736534205005006
Fold 3 IBS: 0.16501326377011497
Fold 4 IBS: 0.16209455350644228
Fold 5 IBS: 0.22737252886994871
[I 2024-04-20 17:10:16,501] Trial 42 finished with value: 0.18726025707238114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9712277852430382, 'max_features': None, 'min_weight_fraction_leaf': 0.4047116771034673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19485182356242944
Fold 2 IBS: 0.1960274570730997
Fold 3 IBS: 0.18423026068342546
Fold 4 IBS: 0.18829121228006515
Fold 5 IBS: 0.23411274191187137
[I 2024-04-20 17:10:18,970] Trial 43 finished with value: 0.19950269910217824 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.8817254098792388, 'max_features': None, 'min_weight_fraction_leaf': 0.43343991639669144}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1712641582188513
Fold 2 IBS: 0.18994637490008684
Fold 3 IBS: 0.16479726253163554
Fold 4 IBS: 0.1632404230753816
Fold 5 IBS: 0.22572502599434202
[I 2024-04-20 17:10:21,627] Trial 44 finished with value: 0.18299464894405942 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.9374671457275974, 'max_features': None, 'min_weight_fraction_leaf': 0.41455323262354377}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19234550794011246
Fold 2 IBS: 0.200986097128332
Fold 3 IBS: 0.1855643390306468
Fold 4 IBS: 0.1932590693758762
Fold 5 IBS: 0.21341012086817227
[I 2024-04-20 17:10:24,372] Trial 45 finished with value: 0.19711302686862794 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9378530595799813, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42089417671131313}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398691344914347
Fold 2 IBS: 0.22137599652455153
Fold 3 IBS: 0.20479386291855103
Fold 4 IBS: 0.2246023464574881
Fold 5 IBS: 0.21853103069298896
[I 2024-04-20 17:10:26,987] Trial 46 finished with value: 0.2166580300085446 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 470, 'oob_score': False, 'max_samples': 0.7938991773051969, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4697812825251582}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1747444583541159
Fold 2 IBS: 0.23713516882516442
Fold 3 IBS: 0.16640805876585935
Fold 4 IBS: 0.1610873512530414
Fold 5 IBS: 0.234167489152576
[I 2024-04-20 17:10:30,159] Trial 47 finished with value: 0.1947085052701514 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 432, 'oob_score': True, 'max_samples': 0.9498935746233631, 'max_features': None, 'min_weight_fraction_leaf': 0.33913737671094774}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398162469590376
Fold 2 IBS: 0.22136781149843104
Fold 3 IBS: 0.20480753036595514
Fold 4 IBS: 0.22461586717115936
Fold 5 IBS: 0.21858421480458282
[I 2024-04-20 17:10:32,489] Trial 48 finished with value: 0.21667140970720644 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.8399357435042919, 'max_features': None, 'min_weight_fraction_leaf': 0.43949783817145754}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18607291644289184
Fold 2 IBS: 0.1997166990883884
Fold 3 IBS: 0.17871196581310303
Fold 4 IBS: 0.1866755623669813
Fold 5 IBS: 0.21401906861191788
[I 2024-04-20 17:10:35,015] Trial 49 finished with value: 0.19303924246465648 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 480, 'oob_score': False, 'max_samples': 0.9976678104279734, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4100286247036702}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398689006749297
Fold 2 IBS: 0.22138730674766524
Fold 3 IBS: 0.20483789730275198
Fold 4 IBS: 0.22469041440834978
Fold 5 IBS: 0.21866425238172585
[I 2024-04-20 17:10:36,865] Trial 50 finished with value: 0.21671335218159715 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7082075481455445, 'max_features': None, 'min_weight_fraction_leaf': 0.35750036696317244}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17354922029359332
Fold 2 IBS: 0.20364062415291528
Fold 3 IBS: 0.1656072740863152
Fold 4 IBS: 0.1629843663853799
Fold 5 IBS: 0.22805293589620068
[I 2024-04-20 17:10:38,277] Trial 51 finished with value: 0.18676688416288084 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.9128659910136828, 'max_features': None, 'min_weight_fraction_leaf': 0.3781612359397365}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1713164651684285
Fold 2 IBS: 0.1908535842776438
Fold 3 IBS: 0.16501795349457885
Fold 4 IBS: 0.16355225040434904
Fold 5 IBS: 0.22558632701889753
[I 2024-04-20 17:10:40,652] Trial 52 finished with value: 0.18326531607277957 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 434, 'oob_score': False, 'max_samples': 0.8747189140359779, 'max_features': None, 'min_weight_fraction_leaf': 0.39127818009875937}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1944075620870496
Fold 2 IBS: 0.19446392844340746
Fold 3 IBS: 0.18592909130830435
Fold 4 IBS: 0.18840569735760734
Fold 5 IBS: 0.23475202007425236
[I 2024-04-20 17:10:43,077] Trial 53 finished with value: 0.19959165985412422 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 435, 'oob_score': False, 'max_samples': 0.9590363563278936, 'max_features': None, 'min_weight_fraction_leaf': 0.47102290336229075}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398291231618569
Fold 2 IBS: 0.22130196765397775
Fold 3 IBS: 0.20479880441504156
Fold 4 IBS: 0.22463025012599544
Fold 5 IBS: 0.21857716931098428
[I 2024-04-20 17:10:45,264] Trial 54 finished with value: 0.21665822076443692 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8049999889328818, 'max_features': None, 'min_weight_fraction_leaf': 0.41366841406796956}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19752377093956933
Fold 2 IBS: 0.20161258811122215
Fold 3 IBS: 0.18853359622298724
Fold 4 IBS: 0.19729854245931258
Fold 5 IBS: 0.21444154842475172
[I 2024-04-20 17:10:47,306] Trial 55 finished with value: 0.1998820092315686 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.8604557082726361, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.39803093257208977}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18353091887871
Fold 2 IBS: 0.20136616660184192
Fold 3 IBS: 0.17417121851089504
Fold 4 IBS: 0.1806079641160692
Fold 5 IBS: 0.21629928891489889
[I 2024-04-20 17:10:49,821] Trial 56 finished with value: 0.191195111404483 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.9140825717192246, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.33142873928622046}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.176153787215779
Fold 2 IBS: 0.255503897064317
Fold 3 IBS: 0.16322193569881852
Fold 4 IBS: 0.15492145863817686
Fold 5 IBS: 0.23637436039500087
[I 2024-04-20 17:10:52,500] Trial 57 finished with value: 0.19723508780241844 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 449, 'oob_score': False, 'max_samples': 0.846572289034959, 'max_features': None, 'min_weight_fraction_leaf': 0.1892509778618988}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21396974144117978
Fold 2 IBS: 0.22126810284573772
Fold 3 IBS: 0.20478519546942675
Fold 4 IBS: 0.22462583298910568
Fold 5 IBS: 0.2186668640880457
[I 2024-04-20 17:10:55,148] Trial 58 finished with value: 0.21666314736669912 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.9616810596485048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4994697733211825}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17564136184525772
Fold 2 IBS: 0.25480558879113324
Fold 3 IBS: 0.1643534207862224
Fold 4 IBS: 0.1574357976027508
Fold 5 IBS: 0.24128856654900457
[I 2024-04-20 17:10:55,721] Trial 59 finished with value: 0.19870494711487374 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9304423548229083, 'max_features': None, 'min_weight_fraction_leaf': 0.30249606930327194}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21397063753981885
Fold 2 IBS: 0.22120321030131956
Fold 3 IBS: 0.20498353734020044
Fold 4 IBS: 0.22465541176579787
Fold 5 IBS: 0.21817456614748645
[I 2024-04-20 17:10:58,041] Trial 60 finished with value: 0.21659747261892465 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 459, 'oob_score': False, 'max_samples': 0.2967533381027988, 'max_features': None, 'min_weight_fraction_leaf': 0.45702707568744816}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1723055398262932
Fold 2 IBS: 0.19143168367074548
Fold 3 IBS: 0.16495123980236973
Fold 4 IBS: 0.16377185203308486
Fold 5 IBS: 0.22590801582391506
[I 2024-04-20 17:10:59,967] Trial 61 finished with value: 0.18367366623128167 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 331, 'oob_score': False, 'max_samples': 0.8753600395959259, 'max_features': None, 'min_weight_fraction_leaf': 0.3908186672612388}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1734277654013816
Fold 2 IBS: 0.20401881796514246
Fold 3 IBS: 0.16490921556493102
Fold 4 IBS: 0.1622125526423405
Fold 5 IBS: 0.2282204138485982
[I 2024-04-20 17:11:01,855] Trial 62 finished with value: 0.18655775308447872 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.8863444595022553, 'max_features': None, 'min_weight_fraction_leaf': 0.3630397965166024}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17425299200408814
Fold 2 IBS: 0.19784814184405533
Fold 3 IBS: 0.16448226706235544
Fold 4 IBS: 0.16221744449574835
Fold 5 IBS: 0.22561034364497506
[I 2024-04-20 17:11:04,226] Trial 63 finished with value: 0.18488223781024446 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.9774803581744468, 'max_features': None, 'min_weight_fraction_leaf': 0.422237244496606}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.17214163753608527
Fold 2 IBS: 0.19020363580055616
Fold 3 IBS: 0.16550959046326688
Fold 4 IBS: 0.16526794959392554
Fold 5 IBS: 0.22833087784482511
[I 2024-04-20 17:11:06,242] Trial 64 finished with value: 0.1842907382477318 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.8662053800926933, 'max_features': None, 'min_weight_fraction_leaf': 0.39542258978805284}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139792007492792
Fold 2 IBS: 0.22131668306329724
Fold 3 IBS: 0.20481655835559517
Fold 4 IBS: 0.22465389902940344
Fold 5 IBS: 0.2186107338002615
[I 2024-04-20 17:11:08,128] Trial 65 finished with value: 0.21667541499956733 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 370, 'oob_score': False, 'max_samples': 0.8126605473414451, 'max_features': None, 'min_weight_fraction_leaf': 0.4432122195886301}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139839404571568
Fold 2 IBS: 0.22128662025715748
Fold 3 IBS: 0.20475660906152154
Fold 4 IBS: 0.22463254345676723
Fold 5 IBS: 0.2185879578955235
[I 2024-04-20 17:11:10,156] Trial 66 finished with value: 0.2166495342256253 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.7628822009195562, 'max_features': None, 'min_weight_fraction_leaf': 0.4806954217012357}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17446682144724857
Fold 2 IBS: 0.20343226965949585
Fold 3 IBS: 0.16509877229395598
Fold 4 IBS: 0.16272402121276544
Fold 5 IBS: 0.22837609800630052
[I 2024-04-20 17:11:11,634] Trial 67 finished with value: 0.18681959652395327 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9273407143986389, 'max_features': None, 'min_weight_fraction_leaf': 0.3829484376044615}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139737017543663
Fold 2 IBS: 0.22132584453552323
Fold 3 IBS: 0.20489534413800095
Fold 4 IBS: 0.22458301458145777
Fold 5 IBS: 0.21855108631457426
[I 2024-04-20 17:11:13,838] Trial 68 finished with value: 0.21666579826478452 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.4560255505580615, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.43542376867133237}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.18183019653099627
Fold 2 IBS: 0.20776625174627097
Fold 3 IBS: 0.16953634624872876
Fold 4 IBS: 0.170118714579068
Fold 5 IBS: 0.21958622926343907
[I 2024-04-20 17:11:16,473] Trial 69 finished with value: 0.18976754767370063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.970602689136413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.263156524754376}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398228747656492
Fold 2 IBS: 0.22137876391118777
Fold 3 IBS: 0.20476882960361822
Fold 4 IBS: 0.22463276305816607
Fold 5 IBS: 0.21856497560430035
[I 2024-04-20 17:11:18,806] Trial 70 finished with value: 0.21666552393076746 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 465, 'oob_score': False, 'max_samples': 0.9012147144740991, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.46397187987790006}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17367631623248717
Fold 2 IBS: 0.18729177749490242
Fold 3 IBS: 0.16716923559227603
Fold 4 IBS: 0.16896965253402357
Fold 5 IBS: 0.22871507732594165
[I 2024-04-20 17:11:20,476] Trial 71 finished with value: 0.1851644118359262 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 299, 'oob_score': False, 'max_samples': 0.8369240734764914, 'max_features': None, 'min_weight_fraction_leaf': 0.3894108977238639}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17623676574788
Fold 2 IBS: 0.18722146882244894
Fold 3 IBS: 0.16923825257873615
Fold 4 IBS: 0.17041309974033034
Fold 5 IBS: 0.2308208580988099
[I 2024-04-20 17:11:22,383] Trial 72 finished with value: 0.1867860889976411 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 344, 'oob_score': False, 'max_samples': 0.8867920327737324, 'max_features': None, 'min_weight_fraction_leaf': 0.4157314879593541}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17466534845952894
Fold 2 IBS: 0.21319655330881065
Fold 3 IBS: 0.165618296143337
Fold 4 IBS: 0.1624164693292741
Fold 5 IBS: 0.22901894445979137
[I 2024-04-20 17:11:24,093] Trial 73 finished with value: 0.1889831223401484 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.9448081876116871, 'max_features': None, 'min_weight_fraction_leaf': 0.37829799509574824}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.19283001171526404
Fold 2 IBS: 0.25233074235756864
Fold 3 IBS: 0.16531718816798083
Fold 4 IBS: 0.1371287117522084
Fold 5 IBS: 0.23777310085766115
[I 2024-04-20 17:11:26,156] Trial 74 finished with value: 0.1970759509701366 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.8560145872964813, 'max_features': None, 'min_weight_fraction_leaf': 0.028106730951250714}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1765526886203159
Fold 2 IBS: 0.24189641128474174
Fold 3 IBS: 0.16693060419975347
Fold 4 IBS: 0.16161303135180896
Fold 5 IBS: 0.2376375116037371
[I 2024-04-20 17:11:27,490] Trial 75 finished with value: 0.19692604941207142 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 227, 'oob_score': False, 'max_samples': 0.9957860072135883, 'max_features': None, 'min_weight_fraction_leaf': 0.34756145962819307}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1751244271301782
Fold 2 IBS: 0.24107670158411845
Fold 3 IBS: 0.16626442192082944
Fold 4 IBS: 0.16107692991176065
Fold 5 IBS: 0.23441060343413975
[I 2024-04-20 17:11:29,072] Trial 76 finished with value: 0.1955906167962053 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 273, 'oob_score': False, 'max_samples': 0.9214268543378774, 'max_features': None, 'min_weight_fraction_leaf': 0.32041444551979115}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398382567775925
Fold 2 IBS: 0.22132197857579206
Fold 3 IBS: 0.20483550783639218
Fold 4 IBS: 0.22469410346846014
Fold 5 IBS: 0.2185234061706301
[I 2024-04-20 17:11:31,227] Trial 77 finished with value: 0.21667176434580676 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 419, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': None, 'min_weight_fraction_leaf': 0.4816802580265169}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139815287454151
Fold 2 IBS: 0.22144251355248706
Fold 3 IBS: 0.20476517865000235
Fold 4 IBS: 0.22461967295013774
Fold 5 IBS: 0.21859926137399327
[I 2024-04-20 17:11:33,619] Trial 78 finished with value: 0.21668163105440713 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.8709125293011857, 'max_features': None, 'min_weight_fraction_leaf': 0.4500024716514146}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21393847873679495
Fold 2 IBS: 0.2206352907056855
Fold 3 IBS: 0.2052031401141122
Fold 4 IBS: 0.22465935825676747
Fold 5 IBS: 0.2170322205916447
[I 2024-04-20 17:11:35,504] Trial 79 finished with value: 0.21629369768100096 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': None, 'min_weight_fraction_leaf': 0.40382275005132695}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.21398666839515476
Fold 2 IBS: 0.22133561292920703
Fold 3 IBS: 0.20476084552868884
Fold 4 IBS: 0.22460858228328426
Fold 5 IBS: 0.21850495327987215
[I 2024-04-20 17:11:38,298] Trial 80 finished with value: 0.2166393324832414 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 442, 'oob_score': True, 'max_samples': 0.7543724309332009, 'max_features': None, 'min_weight_fraction_leaf': 0.43164085935118673}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1718240887458899
Fold 2 IBS: 0.191437443203446
Fold 3 IBS: 0.16491345446124533
Fold 4 IBS: 0.16398408770898562
Fold 5 IBS: 0.22656733476064983
[I 2024-04-20 17:11:40,253] Trial 81 finished with value: 0.18374528177604332 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 355, 'oob_score': False, 'max_samples': 0.8723363913158229, 'max_features': None, 'min_weight_fraction_leaf': 0.39397540986506063}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17374604878476174
Fold 2 IBS: 0.19798109455852192
Fold 3 IBS: 0.16401735622550842
Fold 4 IBS: 0.1619573282383729
Fold 5 IBS: 0.22581911344299607
[I 2024-04-20 17:11:42,096] Trial 82 finished with value: 0.1847041882500322 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8247493235113283, 'max_features': None, 'min_weight_fraction_leaf': 0.3601096556690917}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17340750457612014
Fold 2 IBS: 0.1865209431926325
Fold 3 IBS: 0.16660200760670268
Fold 4 IBS: 0.16731704053628665
Fold 5 IBS: 0.23067593415026993
[I 2024-04-20 17:11:44,157] Trial 83 finished with value: 0.1849046860124024 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.8997196592880778, 'max_features': None, 'min_weight_fraction_leaf': 0.42074986147139254}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17452011364531658
Fold 2 IBS: 0.21400766260887688
Fold 3 IBS: 0.16568783150449218
Fold 4 IBS: 0.16229140988658286
Fold 5 IBS: 0.22955502465730293
[I 2024-04-20 17:11:46,700] Trial 84 finished with value: 0.1892124084605143 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.9496964476824827, 'max_features': None, 'min_weight_fraction_leaf': 0.37072364798951474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17525073412789557
Fold 2 IBS: 0.2105659370926584
Fold 3 IBS: 0.16602025501429193
Fold 4 IBS: 0.1622139028904671
Fold 5 IBS: 0.22956434629388905
[I 2024-04-20 17:11:48,380] Trial 85 finished with value: 0.18872303508384042 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.9768787275271766, 'max_features': None, 'min_weight_fraction_leaf': 0.389212711709705}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.2139824234419341
Fold 2 IBS: 0.22136539954988055
Fold 3 IBS: 0.204822165703736
Fold 4 IBS: 0.22464122963551408
Fold 5 IBS: 0.2185219969232711
[I 2024-04-20 17:11:50,464] Trial 86 finished with value: 0.21666664305086716 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.7799819637825093, 'max_features': None, 'min_weight_fraction_leaf': 0.4000713988176814}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.20027780376461612
Fold 2 IBS: 0.20307340294666915
Fold 3 IBS: 0.19102009672018105
Fold 4 IBS: 0.20003685084746606
Fold 5 IBS: 0.21421965519619954
[I 2024-04-20 17:11:52,550] Trial 87 finished with value: 0.20172556189502638 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 19, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.9292189383035607, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4390757544239005}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.21398570828038652
Fold 2 IBS: 0.22140151761658128
Fold 3 IBS: 0.2048003761944947
Fold 4 IBS: 0.22459594623574206
Fold 5 IBS: 0.21853396569713832
[I 2024-04-20 17:11:55,029] Trial 88 finished with value: 0.2166635028048686 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 488, 'oob_score': False, 'max_samples': 0.7896863299148335, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.45607963249620537}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17203791887421
Fold 2 IBS: 0.18726791026590833
Fold 3 IBS: 0.16576625757294128
Fold 4 IBS: 0.16530852151519143
Fold 5 IBS: 0.22888342314880578
[I 2024-04-20 17:11:57,460] Trial 89 finished with value: 0.18385280627541137 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 431, 'oob_score': False, 'max_samples': 0.8904926128857917, 'max_features': None, 'min_weight_fraction_leaf': 0.4120116856268681}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1940772853656249
Fold 2 IBS: 0.2004241668146479
Fold 3 IBS: 0.18634724520921406
Fold 4 IBS: 0.19496657142921314
Fold 5 IBS: 0.21367459762057212
[I 2024-04-20 17:11:59,799] Trial 90 finished with value: 0.19789797328785444 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.9106880455831121, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.40976298541889333}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1926191075437479
Fold 2 IBS: 0.19415079186842468
Fold 3 IBS: 0.18487947833584825
Fold 4 IBS: 0.18641681431445226
Fold 5 IBS: 0.23439208959229954
[I 2024-04-20 17:12:02,233] Trial 91 finished with value: 0.1984916563309545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 436, 'oob_score': False, 'max_samples': 0.8647633953620859, 'max_features': None, 'min_weight_fraction_leaf': 0.42597944887100797}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17236214134250716
Fold 2 IBS: 0.19455412228125918
Fold 3 IBS: 0.16427712812224537
Fold 4 IBS: 0.162949090773761
Fold 5 IBS: 0.2259494780328012
[I 2024-04-20 17:12:04,772] Trial 92 finished with value: 0.18401839211051477 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 457, 'oob_score': False, 'max_samples': 0.8900467044086138, 'max_features': None, 'min_weight_fraction_leaf': 0.3893348459268057}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17257330060839252
Fold 2 IBS: 0.18644424300898413
Fold 3 IBS: 0.167229764854462
Fold 4 IBS: 0.16728718203115409
Fold 5 IBS: 0.22779364161313018
[I 2024-04-20 17:12:07,277] Trial 93 finished with value: 0.18426562642322458 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 454, 'oob_score': False, 'max_samples': 0.951027581141039, 'max_features': None, 'min_weight_fraction_leaf': 0.44280477596355444}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17363154839056466
Fold 2 IBS: 0.22743622651322085
Fold 3 IBS: 0.1659053390876856
Fold 4 IBS: 0.1617200646570578
Fold 5 IBS: 0.2317058059728232
[I 2024-04-20 17:12:09,904] Trial 94 finished with value: 0.1920797969242704 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.8997870199007337, 'max_features': None, 'min_weight_fraction_leaf': 0.3407068895244753}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1742039929754336
Fold 2 IBS: 0.22427050607023472
Fold 3 IBS: 0.1662296675861061
Fold 4 IBS: 0.16181525206129235
Fold 5 IBS: 0.2312628649338052
[I 2024-04-20 17:12:12,253] Trial 95 finished with value: 0.1915564567253744 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 414, 'oob_score': False, 'max_samples': 0.9777582543649842, 'max_features': None, 'min_weight_fraction_leaf': 0.37055856104990403}. Best is trial 23 with value: 0.1829201586199189.

Fold 1 IBS: 0.18206223269633873
Fold 2 IBS: 0.18820585180072097
Fold 3 IBS: 0.17369714014143833
Fold 4 IBS: 0.1751220212365198
Fold 5 IBS: 0.22437209861320465
[I 2024-04-20 17:12:14,882] Trial 96 finished with value: 0.1886918688976445 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 448, 'oob_score': False, 'max_samples': 0.8430407084230132, 'max_features': None, 'min_weight_fraction_leaf': 0.41419337591128474}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17261810934600746
Fold 2 IBS: 0.19291443628076307
Fold 3 IBS: 0.16469348295311864
Fold 4 IBS: 0.16293280131529528
Fold 5 IBS: 0.2265701418039605
[I 2024-04-20 17:12:17,774] Trial 97 finished with value: 0.183945794339829 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 499, 'oob_score': False, 'max_samples': 0.8784577990568653, 'max_features': None, 'min_weight_fraction_leaf': 0.3938564682169779}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.1806635839384418
Fold 2 IBS: 0.18847632703053457
Fold 3 IBS: 0.17326431415814442
Fold 4 IBS: 0.17486447351236495
Fold 5 IBS: 0.2258002518864047
[I 2024-04-20 17:12:21,265] Trial 98 finished with value: 0.18861379010517812 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.8075349562887142, 'max_features': None, 'min_weight_fraction_leaf': 0.3942015894342152}. Best is trial 23 with value: 0.1829201586199189.
Fold 1 IBS: 0.17457318039218142
Fold 2 IBS: 0.19576662913389825
Fold 3 IBS: 0.1643932476316186
Fold 4 IBS: 0.16120104626761333
Fold 5 IBS: 0.22682167562644817
[I 2024-04-20 17:12:22,641] Trial 99 finished with value: 0.18455115581035195 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.8213734885898443, 'max_features': None, 'min_weight_fraction_leaf': 0.35155796421429664}. Best is trial 23 with value: 0.1829201586199189.


* Best trial for IBS:
 FrozenTrial(number=23, state=TrialState.COMPLETE, values=[0.1829201586199189], datetime_start=datetime.datetime(2024, 4, 20, 17, 9, 28, 319809), datetime_complete=datetime.datetime(2024, 4, 20, 17, 9, 30, 711885), params={'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 396, 'oob_score': False, 'max_samples': 0.9248759152889626, 'max_features': None, 'min_weight_fraction_leaf': 0.41894325026727597}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=23, value=None)


* Best Score for IBS:
 0.1829201586199189

In [58]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [59]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.183

#### Test

In [60]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

In [61]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=19, max_features='log2', max_leaf_nodes=15,
                     max_samples=0.9995515317027949, min_samples_split=18,
                     min_weight_fraction_leaf=0.032175807966512454,
                     n_estimators=115, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.653

RandomSurvivalForest(max_depth=20, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9248759152889626, min_samples_split=2,
                     min_weight_fraction_leaf=0.41894325026727597,
                     n_estimators=396, random_state=123)

test_ibs:  0.206

In [62]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [63]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [64]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-20 17:12:23,456] A new study created in memory with name: no-name-2c34a0de-f269-46b8-8aa4-6130fd75326a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6948356807511737
[I 2024-04-20 17:12:24,070] Trial 0 finished with value: 0.7836129950691764 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:12:25,328] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:12:27,998] Trial 2 finished with value: 0.7556152507681301 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:12:28,266] Trial 3 finished with value: 0.7717160075913865 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:12:29,172] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:12:30,222] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:12:30,792] Trial 6 finished with value: 0.7781769130770997 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:12:32,226] Trial 7 finished with value: 0.7508462032035622 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:12:32,315] Trial 8 finished with value: 0.7684324398125025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:12:35,158] Trial 9 finished with value: 0.7552175391299489 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:12:36,415] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:12:37,016] Trial 11 finished with value: 0.7698273464882801 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7836129950691764.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8258928571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6901408450704225
[I 2024-04-20 17:12:37,754] Trial 12 finished with value: 0.7914452579440178 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6666666666666666
[I 2024-04-20 17:12:38,439] Trial 13 finished with value: 0.7653468723507815 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:12:38,995] Trial 14 finished with value: 0.7661538756898894 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8122362869198312
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:12:39,383] Trial 15 finished with value: 0.7684393821468035 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6267605633802817
[I 2024-04-20 17:12:40,052] Trial 16 finished with value: 0.77051229268592 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:12:40,535] Trial 17 finished with value: 0.7723249788334919 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:12:41,291] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7767857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:12:41,840] Trial 19 finished with value: 0.765551411653658 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7647058823529411
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 17:12:41,919] Trial 20 finished with value: 0.7391209661793047 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-20 17:12:42,514] Trial 21 finished with value: 0.7817887210557736 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6901408450704225
[I 2024-04-20 17:12:43,141] Trial 22 finished with value: 0.7809862642199459 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:12:43,649] Trial 23 finished with value: 0.7759304206293289 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4155863532247274, 'min_weight_fraction_leaf': 0.07928484585286968}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6901408450704225
[I 2024-04-20 17:12:44,283] Trial 24 finished with value: 0.7747196235015181 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.00901469432212705}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6995305164319249
[I 2024-04-20 17:12:44,874] Trial 25 finished with value: 0.780898135887688 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.895337843232826, 'min_weight_fraction_leaf': 0.09625756753241399}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:12:46,905] Trial 26 finished with value: 0.7535362780827659 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 291, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5901308628926357, 'min_weight_fraction_leaf': 0.04311046725313979}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:12:47,251] Trial 27 finished with value: 0.7700615298551389 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7879464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6549295774647887
[I 2024-04-20 17:12:47,836] Trial 28 finished with value: 0.7607683592529704 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:12:49,151] Trial 29 finished with value: 0.783702202780981 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 453, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.11187426524781394}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:12:50,486] Trial 30 finished with value: 0.7671596620665804 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 5, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.23846812660748434}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 17:12:51,898] Trial 31 finished with value: 0.7712482704957379 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 500, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9319495980432307, 'min_weight_fraction_leaf': 0.028814153765248245}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:12:53,217] Trial 32 finished with value: 0.7875856659621985 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 459, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.83936093173654, 'min_weight_fraction_leaf': 0.10465149498791723}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:12:54,593] Trial 33 finished with value: 0.7854274383297459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8110657459614115, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6666666666666666
[I 2024-04-20 17:12:56,036] Trial 34 finished with value: 0.7875712972185422 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 471, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8312111470897382, 'min_weight_fraction_leaf': 0.11396804804122496}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:12:57,505] Trial 35 finished with value: 0.7805626784012362 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8317242802235407, 'min_weight_fraction_leaf': 0.17026413245531302}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6607142857142857
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6338028169014085
[I 2024-04-20 17:13:00,517] Trial 36 finished with value: 0.7392301426964731 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 397, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.919159658755392, 'min_weight_fraction_leaf': 0.12417590138595275}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 17:13:01,961] Trial 37 finished with value: 0.7733460193912409 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 478, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9384999627665201, 'min_weight_fraction_leaf': 0.21309962076960762}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7727272727272727
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 17:13:03,019] Trial 38 finished with value: 0.7639313460923033 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 345, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7810779808078776, 'min_weight_fraction_leaf': 0.2883645958901683}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:13:05,859] Trial 39 finished with value: 0.7557517610684528 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 438, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7126142286152415, 'min_weight_fraction_leaf': 0.051535007757158066}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:13:07,239] Trial 40 finished with value: 0.7815020978326014 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6423525258918861, 'min_weight_fraction_leaf': 0.12542889840419838}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8627450980392157
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:13:08,550] Trial 41 finished with value: 0.7864193339372411 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 449, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8300934016687722, 'min_weight_fraction_leaf': 0.10960380301974583}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:13:09,791] Trial 42 finished with value: 0.7880709509204418 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 420, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0742644879267989}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8392857142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 17:13:11,018] Trial 43 finished with value: 0.7828465399677109 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 413, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7812921734334815, 'min_weight_fraction_leaf': 0.07650726650715535}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-20 17:13:12,310] Trial 44 finished with value: 0.7803513206203079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 440, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9997498444523031, 'min_weight_fraction_leaf': 0.1566845549254962}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6854460093896714
[I 2024-04-20 17:13:13,719] Trial 45 finished with value: 0.7788761410494602 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 498, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9223521852303842, 'min_weight_fraction_leaf': 0.059273843380186375}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:13:15,014] Trial 46 finished with value: 0.7685371916964001 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 454, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9500103809873137, 'min_weight_fraction_leaf': 0.03660618092052255}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6666666666666666
[I 2024-04-20 17:13:17,582] Trial 47 finished with value: 0.742317931200098 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8574312076294325, 'min_weight_fraction_leaf': 0.08931620844737977}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:18,782] Trial 48 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 422, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.755266816507861, 'min_weight_fraction_leaf': 0.020812961475463188}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:13:19,244] Trial 49 finished with value: 0.7845202124432327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 134, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.814593864444954, 'min_weight_fraction_leaf': 0.09888902748696558}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:13:20,311] Trial 50 finished with value: 0.7773994153326739 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 18, 'n_estimators': 367, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6864757488123517, 'min_weight_fraction_leaf': 0.0622709472266257}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8578431372549019
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 17:13:21,665] Trial 51 finished with value: 0.7857905817313229 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 477, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8138857282473038, 'min_weight_fraction_leaf': 0.139261908142962}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:13:23,196] Trial 52 finished with value: 0.7754721899619019 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 483, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.897591154770797, 'min_weight_fraction_leaf': 0.18036745341019644}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:24,469] Trial 53 finished with value: 0.7716977304949759 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 445, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8040300125345899, 'min_weight_fraction_leaf': 0.13782166853114988}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:13:25,792] Trial 54 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8778737344226841, 'min_weight_fraction_leaf': 0.4522260564219586}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8303571428571429
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 17:13:26,489] Trial 55 finished with value: 0.7758270084642879 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 223, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7446102701098806, 'min_weight_fraction_leaf': 0.0765135926752003}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6854460093896714
[I 2024-04-20 17:13:27,731] Trial 56 finished with value: 0.7744763834479156 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 431, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957871319428308, 'min_weight_fraction_leaf': 0.15347039261632256}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:29,126] Trial 57 finished with value: 0.7699442097541136 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 490, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6651987019932437, 'min_weight_fraction_leaf': 0.1066939379481781}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6666666666666666
[I 2024-04-20 17:13:31,861] Trial 58 finished with value: 0.7510997177927557 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8492110159158694, 'min_weight_fraction_leaf': 0.1370897749041413}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:13:32,721] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.3278490557085546, 'min_weight_fraction_leaf': 0.20658865997161166}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7857142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.6502347417840375
[I 2024-04-20 17:13:34,040] Trial 60 finished with value: 0.7646046839942156 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 19, 'n_estimators': 464, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.2714828861387636}. Best is trial 12 with value: 0.7914452579440178.

Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:13:35,461] Trial 61 finished with value: 0.7875908032299939 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 16, 'n_estimators': 482, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8197782912980647, 'min_weight_fraction_leaf': 0.11182880406892551}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:13:36,779] Trial 62 finished with value: 0.7867469213734538 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 447, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7728729369504425, 'min_weight_fraction_leaf': 0.08684392452952273}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7402597402597403
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6901408450704225
[I 2024-04-20 17:13:38,091] Trial 63 finished with value: 0.7798808652133927 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 446, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7730739126088626, 'min_weight_fraction_leaf': 0.08638346674570552}. Best is trial 12 with value: 0.7914452579440178.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:39,294] Trial 64 finished with value: 0.7930563544969358 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 18, 'n_estimators': 397, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7094023899138029, 'min_weight_fraction_leaf': 0.016985502713105286}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6854460093896714
[I 2024-04-20 17:13:40,472] Trial 65 finished with value: 0.7782230230703928 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 399, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5432894752024745, 'min_weight_fraction_leaf': 0.021766672705799798}. Best is trial 64 with value: 0.7930563544969358.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:41,059] Trial 66 finished with value: 0.7938811826372392 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7228780771138192, 'min_weight_fraction_leaf': 0.0031520648190986253}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:41,568] Trial 67 finished with value: 0.7920349896145755 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7208856143139186, 'min_weight_fraction_leaf': 0.000720456341576893}. Best is trial 66 with value: 0.7938811826372392.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:42,064] Trial 68 finished with value: 0.794041883921594 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7036950154527627, 'min_weight_fraction_leaf': 0.005216408266220198}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8035714285714286
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6901408450704225
[I 2024-04-20 17:13:42,548] Trial 69 finished with value: 0.7859079077910682 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 323, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7175215556344815, 'min_weight_fraction_leaf': 0.011727820970865974}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6666666666666666
[I 2024-04-20 17:13:44,373] Trial 70 finished with value: 0.751088073319086 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7068868150575319, 'min_weight_fraction_leaf': 0.04275053996657477}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:44,956] Trial 71 finished with value: 0.7894658722092704 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6765833323968065, 'min_weight_fraction_leaf': 0.0056539519960706885}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:45,435] Trial 72 finished with value: 0.7914342067886004 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 303, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6657543859502482, 'min_weight_fraction_leaf': 0.0007645303007875817}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:45,899] Trial 73 finished with value: 0.7939687176512447 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.0006629495375479764}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:46,364] Trial 74 finished with value: 0.7929417632058738 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 292, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6089504598680775, 'min_weight_fraction_leaf': 0.009816745037317486}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:46,828] Trial 75 finished with value: 0.7886490466297866 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 289, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.532426516857448, 'min_weight_fraction_leaf': 0.0002663514949337425}. Best is trial 68 with value: 0.794041883921594.

Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:47,308] Trial 76 finished with value: 0.7801220886659336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6123538402148698, 'min_weight_fraction_leaf': 0.019649932961991672}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.8080357142857143
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:47,732] Trial 77 finished with value: 0.7814522179558544 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5811927471801297, 'min_weight_fraction_leaf': 0.04878077669029726}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8214285714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6948356807511737
[I 2024-04-20 17:13:48,242] Trial 78 finished with value: 0.7845818837754068 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 306, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6462796252211019, 'min_weight_fraction_leaf': 0.03369012476405811}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8348214285714286
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:13:48,753] Trial 79 finished with value: 0.7787001559323222 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5164947678000329, 'min_weight_fraction_leaf': 0.01622265318172269}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:49,144] Trial 80 finished with value: 0.7818525173809616 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 243, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6235631347306672, 'min_weight_fraction_leaf': 0.031552173049052425}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:49,670] Trial 81 finished with value: 0.7905684059227995 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 341, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6646517878972749, 'min_weight_fraction_leaf': 0.003319138338666917}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6854460093896714
[I 2024-04-20 17:13:50,217] Trial 82 finished with value: 0.7915344293360062 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 352, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6559993331175135, 'min_weight_fraction_leaf': 0.0007051454739791334}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:13:50,761] Trial 83 finished with value: 0.784834519027793 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6078088154987048, 'min_weight_fraction_leaf': 0.05269795093090639}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:51,183] Trial 84 finished with value: 0.7876737917407194 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 252, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.56420075442896, 'min_weight_fraction_leaf': 0.0001867103765655385}. Best is trial 68 with value: 0.794041883921594.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6901408450704225
[I 2024-04-20 17:13:51,624] Trial 85 finished with value: 0.7941830791944973 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.8125
Fold 3 C-index: 0.8676470588235294
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-20 17:13:52,075] Trial 86 finished with value: 0.7910103136701933 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7300691279502551, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8482142857142857
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:13:52,467] Trial 87 finished with value: 0.7870370369739819 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6972914076775041, 'min_weight_fraction_leaf': 0.042431862202902404}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.6517857142857143
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 17:13:53,952] Trial 88 finished with value: 0.7393760229419569 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.592229960198248, 'min_weight_fraction_leaf': 0.016246248347428313}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7467532467532467
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:54,440] Trial 89 finished with value: 0.7766334763698508 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45159856922443276, 'min_weight_fraction_leaf': 0.05921570024221322}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 17:13:54,946] Trial 90 finished with value: 0.7708838065283327 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7242276540625545, 'min_weight_fraction_leaf': 0.34283486638092503}. Best is trial 85 with value: 0.7941830791944973.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:55,510] Trial 91 finished with value: 0.7895419037726438 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6583630297112304, 'min_weight_fraction_leaf': 0.013827947129714684}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:55,977] Trial 92 finished with value: 0.7920954683515248 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7515631882154823, 'min_weight_fraction_leaf': 0.028988151290404485}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:13:56,458] Trial 93 finished with value: 0.7937492188401966 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 304, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7381814767748153, 'min_weight_fraction_leaf': 0.030278173261689908}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:56,928] Trial 94 finished with value: 0.7930758605083875 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6942749611849839, 'min_weight_fraction_leaf': 0.02829541014533638}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.8616071428571429
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6619718309859155
[I 2024-04-20 17:13:57,356] Trial 95 finished with value: 0.7862754612128648 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.750467494063393, 'min_weight_fraction_leaf': 0.03084864174659612}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.8571428571428571
Fold 3 C-index: 0.8480392156862745
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6713615023474179
[I 2024-04-20 17:13:57,843] Trial 96 finished with value: 0.7937809600898336 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6916627249534713, 'min_weight_fraction_leaf': 0.0642170412166308}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8529411764705882
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.676056338028169
[I 2024-04-20 17:13:58,321] Trial 97 finished with value: 0.7922100596425867 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6847338071332475, 'min_weight_fraction_leaf': 0.06422450776206082}. Best is trial 85 with value: 0.7941830791944973.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.84375
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8565400843881856
Fold 5 C-index: 0.6807511737089202
[I 2024-04-20 17:13:58,765] Trial 98 finished with value: 0.7896281650393346 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6945703344834594, 'min_weight_fraction_leaf': 0.06929480157264988}. Best is trial 85 with value: 0.7941830791944973.

[I 2024-04-20 17:13:59,136] A new study created in memory with name: no-name-ad3ab32c-1db2-45d1-ab90-badf392ddff4

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.8526785714285714
Fold 3 C-index: 0.8431372549019608
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6854460093896714
[I 2024-04-20 17:13:59,131] Trial 99 finished with value: 0.7912614087353609 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6926648599741109, 'min_weight_fraction_leaf': 0.05098663692788332}. Best is trial 85 with value: 0.7941830791944973.


* Best trial for C-index:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.7941830791944973], datetime_start=datetime.datetime(2024, 4, 20, 17, 13, 51, 185344), datetime_complete=datetime.datetime(2024, 4, 20, 17, 13, 51, 624550), params={'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7030590704740037, 'min_weight_fraction_leaf': 0.020016091327628317}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for C-index:
 0.7941830791944973

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.16943133784699038
Fold 2 IBS: 0.217110921492143
Fold 3 IBS: 0.16458005935948244
Fold 4 IBS: 0.15978141365273868
Fold 5 IBS: 0.23006411985790817
[I 2024-04-20 17:14:01,060] Trial 0 finished with value: 0.18819357044185253 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-20 17:14:03,779] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.1920088773895634
Fold 2 IBS: 0.20722305192399237
Fold 3 IBS: 0.1843664308419076
Fold 4 IBS: 0.19578634061172853
Fold 5 IBS: 0.21729770324619507
[I 2024-04-20 17:14:06,197] Trial 2 finished with value: 0.1993364808026774 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.19258828625505786
Fold 2 IBS: 0.2045422331943319
Fold 3 IBS: 0.1853898388957368
Fold 4 IBS: 0.19796057104495973
Fold 5 IBS: 0.21730311317672968
[I 2024-04-20 17:14:07,016] Trial 3 finished with value: 0.1995568085133632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-20 17:14:09,080] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-20 17:14:10,128] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.18819357044185253.
Fold 1 IBS: 0.17108054547230092
Fold 2 IBS: 0.21332710542268465
Fold 3 IBS: 0.1636503921602676
Fold 4 IBS: 0.1601897971404523
Fold 5 IBS: 0.23011170771684802
[I 2024-04-20 17:14:12,319] Trial 6 finished with value: 0.1876719095825107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.1802257330412862
Fold 2 IBS: 0.20553844032632104
Fold 3 IBS: 0.17516423786860197
Fold 4 IBS: 0.18156654611164302
Fold 5 IBS: 0.21889734913100833
[I 2024-04-20 17:14:13,706] Trial 7 finished with value: 0.1922784612957721 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19324605458737515
Fold 2 IBS: 0.20063316435414258
Fold 3 IBS: 0.18395193632306783
Fold 4 IBS: 0.19657870618224477
Fold 5 IBS: 0.2180785905917539
[I 2024-04-20 17:14:14,002] Trial 8 finished with value: 0.19849769040771686 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.19947118578728948
Fold 2 IBS: 0.2128915375997729
Fold 3 IBS: 0.19180552923211425
Fold 4 IBS: 0.21059003168383789
Fold 5 IBS: 0.2166615073888468
[I 2024-04-20 17:14:16,868] Trial 9 finished with value: 0.20628395833837226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.21397612241164576
Fold 2 IBS: 0.2207394210478338
Fold 3 IBS: 0.20537940251283027
Fold 4 IBS: 0.22474853253260105
Fold 5 IBS: 0.2174222289467434
[I 2024-04-20 17:14:19,244] Trial 10 finished with value: 0.21645314149033087 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 19, 'max_depth': 1, 'n_estimators': 364, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.17451860010924325, 'min_weight_fraction_leaf': 0.0039346994453491185}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.2015386647704584
Fold 2 IBS: 0.21349515547127124
Fold 3 IBS: 0.19259186402255285
Fold 4 IBS: 0.21338933172129262
Fold 5 IBS: 0.21568498079724013
[I 2024-04-20 17:14:21,081] Trial 11 finished with value: 0.20733999935656305 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.14585874141164717}. Best is trial 6 with value: 0.1876719095825107.
Fold 1 IBS: 0.16481288780890282
Fold 2 IBS: 0.2210169243096472
Fold 3 IBS: 0.1621024154551832
Fold 4 IBS: 0.1533029510139564
Fold 5 IBS: 0.23439416692917028
[I 2024-04-20 17:14:23,695] Trial 12 finished with value: 0.18712586910337198 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17402283336818236
Fold 2 IBS: 0.2087374728480146
Fold 3 IBS: 0.17174698691539156
Fold 4 IBS: 0.17261429502370135
Fold 5 IBS: 0.22300398757472922
[I 2024-04-20 17:14:26,226] Trial 13 finished with value: 0.19002511514600381 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 491, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638831587887255, 'min_weight_fraction_leaf': 0.002470740135940064}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.2139646814364898
Fold 2 IBS: 0.22074056096749928
Fold 3 IBS: 0.20501656315227804
Fold 4 IBS: 0.22494601314735585
Fold 5 IBS: 0.21705148409657263
[I 2024-04-20 17:14:28,364] Trial 14 finished with value: 0.21634386056003913 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.20649381387566834}. Best is trial 12 with value: 0.18712586910337198.

Fold 1 IBS: 0.21400643269593325
Fold 2 IBS: 0.22111219981278188
Fold 3 IBS: 0.20502803908063474
Fold 4 IBS: 0.22484462106669664
Fold 5 IBS: 0.21822466700224044
[I 2024-04-20 17:14:29,797] Trial 15 finished with value: 0.21664319193165743 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 268, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.33571048327918607, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17764770478002706
Fold 2 IBS: 0.20867663392001196
Fold 3 IBS: 0.17428317770837892
Fold 4 IBS: 0.17942136638629663
Fold 5 IBS: 0.2202481090473258
[I 2024-04-20 17:14:32,363] Trial 16 finished with value: 0.19205539836840807 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6535355702555379, 'min_weight_fraction_leaf': 0.1906011147608997}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1745416753225377
Fold 2 IBS: 0.21000021208635342
Fold 3 IBS: 0.16747801651861197
Fold 4 IBS: 0.1665050437548392
Fold 5 IBS: 0.2259884313484794
[I 2024-04-20 17:14:34,345] Trial 17 finished with value: 0.18890267580616435 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.903993543626621, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.18877375960277615
Fold 2 IBS: 0.2104175503296011
Fold 3 IBS: 0.17887147368827228
Fold 4 IBS: 0.20070265473963897
Fold 5 IBS: 0.21455512687410158
[I 2024-04-20 17:14:34,602] Trial 18 finished with value: 0.19866411304687803 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 23, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.38500398118655316, 'min_weight_fraction_leaf': 0.0735015574561402}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.1693931134036931
Fold 2 IBS: 0.21423273576779828
Fold 3 IBS: 0.16523484371479388
Fold 4 IBS: 0.16359614521845625
Fold 5 IBS: 0.23143820702196424
[I 2024-04-20 17:14:35,244] Trial 19 finished with value: 0.18877900902534114 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.639253673774636, 'min_weight_fraction_leaf': 0.037408326362835864}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17421547013270003
Fold 2 IBS: 0.2050823834385182
Fold 3 IBS: 0.17114430210298628
Fold 4 IBS: 0.17339485761183707
Fold 5 IBS: 0.22351478015249363
[I 2024-04-20 17:14:36,895] Trial 20 finished with value: 0.18947035868770704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8892982712995542, 'min_weight_fraction_leaf': 0.18720118160246144}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.17111493042801526
Fold 2 IBS: 0.2137721819185777
Fold 3 IBS: 0.16456471169620251
Fold 4 IBS: 0.16449227846347558
Fold 5 IBS: 0.22864796656377134
[I 2024-04-20 17:14:38,986] Trial 21 finished with value: 0.1885184138140085 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7247491835588253, 'min_weight_fraction_leaf': 0.10612931382459131}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16532773770032788
Fold 2 IBS: 0.2186442284652855
Fold 3 IBS: 0.16460826885307955
Fold 4 IBS: 0.15506743410900792
Fold 5 IBS: 0.23319986958345387
[I 2024-04-20 17:14:40,849] Trial 22 finished with value: 0.18736950774223093 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8844026166095639, 'min_weight_fraction_leaf': 0.08688290860444149}. Best is trial 12 with value: 0.18712586910337198.
Fold 1 IBS: 0.16301700829191232
Fold 2 IBS: 0.219030517452768
Fold 3 IBS: 0.1623853390492206
Fold 4 IBS: 0.1532916510108008
Fold 5 IBS: 0.23013904250092193
[I 2024-04-20 17:14:43,225] Trial 23 finished with value: 0.1855727116611247 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.882373739187446, 'min_weight_fraction_leaf': 0.012868164547398506}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16304988087529812
Fold 2 IBS: 0.22094207521693815
Fold 3 IBS: 0.161348064662482
Fold 4 IBS: 0.15096714326145844
Fold 5 IBS: 0.23463058158669606
[I 2024-04-20 17:14:45,745] Trial 24 finished with value: 0.18618754912057453 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8872409155608235, 'min_weight_fraction_leaf': 0.04604331935587166}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1737150468913634
Fold 2 IBS: 0.2064240961037397
Fold 3 IBS: 0.17070043959096043
Fold 4 IBS: 0.17215340254727685
Fold 5 IBS: 0.22073392460374922
[I 2024-04-20 17:14:48,108] Trial 25 finished with value: 0.1887453819474179 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9949818354422626, 'min_weight_fraction_leaf': 0.04193971879336897}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17192147575817168
Fold 2 IBS: 0.2125807619877445
Fold 3 IBS: 0.1691262873841453
Fold 4 IBS: 0.16885171298035456
Fold 5 IBS: 0.2265576203614483
[I 2024-04-20 17:14:51,069] Trial 26 finished with value: 0.18980757169437287 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8751983869140558, 'min_weight_fraction_leaf': 0.14849424791584837}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16246717022558158
Fold 2 IBS: 0.22278551957594211
Fold 3 IBS: 0.15990422558540457
Fold 4 IBS: 0.1487070056469065
Fold 5 IBS: 0.23422547394882334
[I 2024-04-20 17:14:53,632] Trial 27 finished with value: 0.18561787899653162 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.027289624478908987}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.1654696844792975
Fold 2 IBS: 0.2234990134256156
Fold 3 IBS: 0.15946196024021897
Fold 4 IBS: 0.14893349177557935
Fold 5 IBS: 0.2381082176321455
[I 2024-04-20 17:14:54,776] Trial 28 finished with value: 0.18709447351057137 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 204, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8312285602471605, 'min_weight_fraction_leaf': 0.04077685648220064}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.17845647167398127
Fold 2 IBS: 0.2130730563466517
Fold 3 IBS: 0.1730128250957027
Fold 4 IBS: 0.1775098861437066
Fold 5 IBS: 0.22205252382699645
[I 2024-04-20 17:14:56,803] Trial 29 finished with value: 0.19282095261740773 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7271017134796036, 'min_weight_fraction_leaf': 0.1096845451205721}. Best is trial 23 with value: 0.1855727116611247.

Fold 1 IBS: 0.16792251267623906
Fold 2 IBS: 0.2174484716230587
Fold 3 IBS: 0.16273781989489802
Fold 4 IBS: 0.1558940391227505
Fold 5 IBS: 0.23222422254692077
[I 2024-04-20 17:14:59,201] Trial 30 finished with value: 0.18724541317277338 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7293028765390641, 'min_weight_fraction_leaf': 0.08037045697723012}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16646920043412164
Fold 2 IBS: 0.22144555868438975
Fold 3 IBS: 0.1612585234507463
Fold 4 IBS: 0.15276461377317607
Fold 5 IBS: 0.23760424924495455
[I 2024-04-20 17:15:00,396] Trial 31 finished with value: 0.18790842911747765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 209, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8386292091834852, 'min_weight_fraction_leaf': 0.04730132529579094}. Best is trial 23 with value: 0.1855727116611247.
Fold 1 IBS: 0.16030007033105986
Fold 2 IBS: 0.22398118562940655
Fold 3 IBS: 0.15846297307347587
Fold 4 IBS: 0.1470891139577854
Fold 5 IBS: 0.23657286223224763
[I 2024-04-20 17:15:01,570] Trial 32 finished with value: 0.18528124104479504 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9163496831204196, 'min_weight_fraction_leaf': 0.030126739530685447}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.172937674157177
Fold 2 IBS: 0.24427201483908298
Fold 3 IBS: 0.15582695988286352
Fold 4 IBS: 0.14290514986885272
Fold 5 IBS: 0.24818545842857834
[I 2024-04-20 17:15:02,537] Trial 33 finished with value: 0.1928254514353109 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9201437866465091, 'min_weight_fraction_leaf': 0.07060844824971078}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16533026201292797
Fold 2 IBS: 0.22263639369462013
Fold 3 IBS: 0.16342873596728688
Fold 4 IBS: 0.16226909673388507
Fold 5 IBS: 0.22835592740970792
[I 2024-04-20 17:15:03,211] Trial 34 finished with value: 0.18840408316368557 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 115, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.023639916096884216}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1768239075644783
Fold 2 IBS: 0.2081027487281694
Fold 3 IBS: 0.17413951134311367
Fold 4 IBS: 0.17907108232142022
Fold 5 IBS: 0.2215257917188389
[I 2024-04-20 17:15:05,995] Trial 35 finished with value: 0.1919326083352041 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8401348549146568, 'min_weight_fraction_leaf': 0.24235302278015497}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1940843114270721
Fold 2 IBS: 0.2056845420523829
Fold 3 IBS: 0.18788157295828922
Fold 4 IBS: 0.20006428856720795
Fold 5 IBS: 0.2177170857082032
[I 2024-04-20 17:15:07,255] Trial 36 finished with value: 0.20108636014263107 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 236, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6624062812925291, 'min_weight_fraction_leaf': 0.1276665161224413}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17340674788508836
Fold 2 IBS: 0.24768190748122734
Fold 3 IBS: 0.16867891640678653
Fold 4 IBS: 0.1616763611285437
Fold 5 IBS: 0.23877880170969434
[I 2024-04-20 17:15:08,845] Trial 37 finished with value: 0.19804454692226806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7790217874657425, 'min_weight_fraction_leaf': 0.062396376437804296}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16624738684053258
Fold 2 IBS: 0.21973229478344297
Fold 3 IBS: 0.16383689986898148
Fold 4 IBS: 0.1555626613940214
Fold 5 IBS: 0.23337565279263775
[I 2024-04-20 17:15:11,284] Trial 38 finished with value: 0.18775097913592323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9337822506368412, 'min_weight_fraction_leaf': 0.09676916841079641}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.19406740130079023
Fold 2 IBS: 0.2080998067364733
Fold 3 IBS: 0.18690687392991395
Fold 4 IBS: 0.1983924325024786
Fold 5 IBS: 0.21669307860788134
[I 2024-04-20 17:15:13,496] Trial 39 finished with value: 0.20083191861550748 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 336, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8439046690156142, 'min_weight_fraction_leaf': 0.1681587492068492}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1754231584570973
Fold 2 IBS: 0.20862733191088295
Fold 3 IBS: 0.17201575641485803
Fold 4 IBS: 0.17247754688839995
Fold 5 IBS: 0.22441791937181546
[I 2024-04-20 17:15:14,438] Trial 40 finished with value: 0.19059234260861074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 166, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.49205438109527067, 'min_weight_fraction_leaf': 0.05363435608897611}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16687091698705347
Fold 2 IBS: 0.22145067973996654
Fold 3 IBS: 0.16083193542269436
Fold 4 IBS: 0.15145269120336982
Fold 5 IBS: 0.23763053320077898
[I 2024-04-20 17:15:15,643] Trial 41 finished with value: 0.18764735131077265 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 213, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8160068596533434, 'min_weight_fraction_leaf': 0.051128939929752766}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16440787739420146
Fold 2 IBS: 0.22051774173279667
Fold 3 IBS: 0.15866302088929105
Fold 4 IBS: 0.1505697309482162
Fold 5 IBS: 0.2344294950935966
[I 2024-04-20 17:15:16,669] Trial 42 finished with value: 0.18571757321162038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8502001595263011, 'min_weight_fraction_leaf': 0.025832096901499825}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.166093032959539
Fold 2 IBS: 0.22071181466302323
Fold 3 IBS: 0.16315038997597892
Fold 4 IBS: 0.1615108085837709
Fold 5 IBS: 0.22986943061414675
[I 2024-04-20 17:15:17,213] Trial 43 finished with value: 0.18826709535929176 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7462221833323165, 'min_weight_fraction_leaf': 0.019530073851423135}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17856291254676518
Fold 2 IBS: 0.20622912686970393
Fold 3 IBS: 0.1728547352397574
Fold 4 IBS: 0.17474142784909633
Fold 5 IBS: 0.22146523571485058
[I 2024-04-20 17:15:18,256] Trial 44 finished with value: 0.19077068764403465 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 183, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9478697073891121, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 32 with value: 0.18528124104479504.

Fold 1 IBS: 0.16512803721910052
Fold 2 IBS: 0.21893230349393553
Fold 3 IBS: 0.1593836385256823
Fold 4 IBS: 0.15058205502042205
Fold 5 IBS: 0.23336241815587846
[I 2024-04-20 17:15:19,737] Trial 45 finished with value: 0.18547769048300378 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6931500413934508, 'min_weight_fraction_leaf': 0.021457257714753555}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.1659546836323674
Fold 2 IBS: 0.2153197227930472
Fold 3 IBS: 0.16360867863772716
Fold 4 IBS: 0.15557836846786757
Fold 5 IBS: 0.233640633124344
[I 2024-04-20 17:15:21,253] Trial 46 finished with value: 0.18682041733107066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7831947572035725, 'min_weight_fraction_leaf': 0.01931405227872043}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.2065277829489426
Fold 2 IBS: 0.216421790160963
Fold 3 IBS: 0.1977088009136629
Fold 4 IBS: 0.21668719017242724
Fold 5 IBS: 0.21616573903460984
[I 2024-04-20 17:15:22,534] Trial 47 finished with value: 0.21070226064612113 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 239, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6100992136402282, 'min_weight_fraction_leaf': 0.2926129328054348}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16819818157316316
Fold 2 IBS: 0.21738390622648787
Fold 3 IBS: 0.16156044111171175
Fold 4 IBS: 0.15316407589462896
Fold 5 IBS: 0.24011367020312108
[I 2024-04-20 17:15:23,445] Trial 48 finished with value: 0.18808405500182257 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 123, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6791860734720297, 'min_weight_fraction_leaf': 0.003213779418364194}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.17209598869991036
Fold 2 IBS: 0.21187077120599623
Fold 3 IBS: 0.16727613640288252
Fold 4 IBS: 0.16695787846814034
Fold 5 IBS: 0.2272726675718586
[I 2024-04-20 17:15:24,209] Trial 49 finished with value: 0.1890946884697576 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8621088667656548, 'min_weight_fraction_leaf': 0.1270208206498544}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.18268255673834424
Fold 2 IBS: 0.2116406133958206
Fold 3 IBS: 0.17317749084487088
Fold 4 IBS: 0.18115159425862645
Fold 5 IBS: 0.21966339609454685
[I 2024-04-20 17:15:24,751] Trial 50 finished with value: 0.19366313026644183 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 90, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.07395605063366822}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16168497854927735
Fold 2 IBS: 0.22270197197696373
Fold 3 IBS: 0.15969319515722263
Fold 4 IBS: 0.14836469505004918
Fold 5 IBS: 0.23398522053840312
[I 2024-04-20 17:15:27,312] Trial 51 finished with value: 0.18528601225438318 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9098861737626865, 'min_weight_fraction_leaf': 0.03317554027209381}. Best is trial 32 with value: 0.18528124104479504.
Fold 1 IBS: 0.16283944924818344
Fold 2 IBS: 0.2217235758500272
Fold 3 IBS: 0.15875960819361015
Fold 4 IBS: 0.1480062250468594
Fold 5 IBS: 0.23242571799847053
[I 2024-04-20 17:15:29,971] Trial 52 finished with value: 0.18475091526743012 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6920435785662685, 'min_weight_fraction_leaf': 0.023623022439616993}. Best is trial 52 with value: 0.18475091526743012.
Fold 1 IBS: 0.16156116277380467
Fold 2 IBS: 0.21645044154721294
Fold 3 IBS: 0.15680725082067987
Fold 4 IBS: 0.1463271703292176
Fold 5 IBS: 0.23173369241683808
[I 2024-04-20 17:15:32,573] Trial 53 finished with value: 0.18257594357755064 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16345657480280432
Fold 2 IBS: 0.21941864722007984
Fold 3 IBS: 0.1609004507368225
Fold 4 IBS: 0.15232912028765422
Fold 5 IBS: 0.2304650281766842
[I 2024-04-20 17:15:34,872] Trial 54 finished with value: 0.185313964244809 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 436, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6831651026874692, 'min_weight_fraction_leaf': 0.003203141018784241}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21398942294707132
Fold 2 IBS: 0.22147230949301053
Fold 3 IBS: 0.20481071402497053
Fold 4 IBS: 0.22464130383350117
Fold 5 IBS: 0.21857501052674366
[I 2024-04-20 17:15:37,305] Trial 55 finished with value: 0.21669775216505943 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6865690783108706, 'min_weight_fraction_leaf': 0.38949341979712204}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.21399089065449398
Fold 2 IBS: 0.2214447680813218
Fold 3 IBS: 0.20479456577543795
Fold 4 IBS: 0.22461278604587448
Fold 5 IBS: 0.21855736344590462
[I 2024-04-20 17:15:39,755] Trial 56 finished with value: 0.21668007480060658 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 482, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.602520835973954, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17871648336439458
Fold 2 IBS: 0.20746679738869533
Fold 3 IBS: 0.17495717299824248
Fold 4 IBS: 0.1821696732464211
Fold 5 IBS: 0.22029130965865304
[I 2024-04-20 17:15:41,985] Trial 57 finished with value: 0.19272028733128133 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 15, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6950911045016969, 'min_weight_fraction_leaf': 0.06162344008829474}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17152567449091236
Fold 2 IBS: 0.2132707954363787
Fold 3 IBS: 0.16577002064558846
Fold 4 IBS: 0.16352941407058058
Fold 5 IBS: 0.2293168915362626
[I 2024-04-20 17:15:44,163] Trial 58 finished with value: 0.18868255923594454 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 410, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6159821240459256, 'min_weight_fraction_leaf': 0.08195171278424525}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17647106232629753
Fold 2 IBS: 0.20824417376602933
Fold 3 IBS: 0.1723553183748716
Fold 4 IBS: 0.1736062035933313
Fold 5 IBS: 0.22224901748255857
[I 2024-04-20 17:15:46,668] Trial 59 finished with value: 0.19058515510861768 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.525386145731032, 'min_weight_fraction_leaf': 0.000152340144876216}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.17342492293804432
Fold 2 IBS: 0.2110732537830341
Fold 3 IBS: 0.16831819527481992
Fold 4 IBS: 0.16873369129336893
Fold 5 IBS: 0.22655614890084055
[I 2024-04-20 17:15:48,957] Trial 60 finished with value: 0.18962124243802156 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5735294094022945, 'min_weight_fraction_leaf': 0.10077092974890593}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16275315104094723
Fold 2 IBS: 0.22028966274589679
Fold 3 IBS: 0.16253743592400494
Fold 4 IBS: 0.15352895984062664
Fold 5 IBS: 0.23021227496706434
[I 2024-04-20 17:15:51,149] Trial 61 finished with value: 0.18586429690370798 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7582468632632998, 'min_weight_fraction_leaf': 0.014165988553227182}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16187634732795245
Fold 2 IBS: 0.21936803684113038
Fold 3 IBS: 0.1608633743218315
Fold 4 IBS: 0.15050003762977443
Fold 5 IBS: 0.23315135185396704
[I 2024-04-20 17:15:53,495] Trial 62 finished with value: 0.18515182959493115 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9688682344495251, 'min_weight_fraction_leaf': 0.03803430028119831}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16803000111589547
Fold 2 IBS: 0.21883335722590105
Fold 3 IBS: 0.16153399726646753
Fold 4 IBS: 0.15499454989097905
Fold 5 IBS: 0.23015675492479587
[I 2024-04-20 17:15:56,080] Trial 63 finished with value: 0.18670973208480782 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4289211196547223, 'min_weight_fraction_leaf': 0.03483517796766671}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16353133471191258
Fold 2 IBS: 0.22078931633305934
Fold 3 IBS: 0.16232987702451745
Fold 4 IBS: 0.1497770751049068
Fold 5 IBS: 0.23519973886423967
[I 2024-04-20 17:15:58,690] Trial 64 finished with value: 0.18632546840772718 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 483, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9928124170835537, 'min_weight_fraction_leaf': 0.0546315910617156}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16705858086425657
Fold 2 IBS: 0.21688710748739626
Fold 3 IBS: 0.16302480802361138
Fold 4 IBS: 0.16043857461543376
Fold 5 IBS: 0.22735018728687206
[I 2024-04-20 17:16:00,557] Trial 65 finished with value: 0.186951851655514 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 346, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.700753371069358, 'min_weight_fraction_leaf': 0.034080382470936726}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.2139764009793113
Fold 2 IBS: 0.22128743928758063
Fold 3 IBS: 0.20478422039927321
Fold 4 IBS: 0.22461901938020365
Fold 5 IBS: 0.21866318582772845
[I 2024-04-20 17:16:02,977] Trial 66 finished with value: 0.21666605317481946 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 440, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17803507005686864
Fold 2 IBS: 0.20584595762292543
Fold 3 IBS: 0.17289828813524646
Fold 4 IBS: 0.177343485740087
Fold 5 IBS: 0.22038680074032185
[I 2024-04-20 17:16:05,527] Trial 67 finished with value: 0.19090192045908988 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8083420047439778, 'min_weight_fraction_leaf': 0.0005690362936050055}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18517903096649513
Fold 2 IBS: 0.2068570229240262
Fold 3 IBS: 0.1787293688926839
Fold 4 IBS: 0.18812296323512723
Fold 5 IBS: 0.2160660198664728
[I 2024-04-20 17:16:07,922] Trial 68 finished with value: 0.19499088117696103 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.22939188072225208, 'min_weight_fraction_leaf': 0.06709563455447608}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18645916216015707
Fold 2 IBS: 0.20636548084294315
Fold 3 IBS: 0.17885851202915032
Fold 4 IBS: 0.18718410387690065
Fold 5 IBS: 0.21792963761071232
[I 2024-04-20 17:16:10,058] Trial 69 finished with value: 0.19535937930397268 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9134125139788976, 'min_weight_fraction_leaf': 0.09022342402306419}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1757749566349244
Fold 2 IBS: 0.2608203853544215
Fold 3 IBS: 0.1687965292943309
Fold 4 IBS: 0.16154593350334548
Fold 5 IBS: 0.2409053655581546
[I 2024-04-20 17:16:12,084] Trial 70 finished with value: 0.20156863406903539 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9558804805474729, 'min_weight_fraction_leaf': 0.038804497461907755}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1641556888310035
Fold 2 IBS: 0.21756591667129618
Fold 3 IBS: 0.16214425980311192
Fold 4 IBS: 0.1527006421467362
Fold 5 IBS: 0.23008748551996394
[I 2024-04-20 17:16:14,440] Trial 71 finished with value: 0.18533079859442234 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6369371661585259, 'min_weight_fraction_leaf': 0.01592906514292467}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16591246996228284
Fold 2 IBS: 0.2157266700943674
Fold 3 IBS: 0.1639704528415932
Fold 4 IBS: 0.15917069749386206
Fold 5 IBS: 0.22728835985586845
[I 2024-04-20 17:16:16,687] Trial 72 finished with value: 0.18641373004959477 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6355486112323981, 'min_weight_fraction_leaf': 0.016225042494993316}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16466547332455966
Fold 2 IBS: 0.21692658302629209
Fold 3 IBS: 0.1589302212774401
Fold 4 IBS: 0.14980038348586724
Fold 5 IBS: 0.23137411159828591
[I 2024-04-20 17:16:19,118] Trial 73 finished with value: 0.184339354542489 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 452, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5876918007096606, 'min_weight_fraction_leaf': 0.01373372285606849}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16792178126681906
Fold 2 IBS: 0.21606101236454162
Fold 3 IBS: 0.16289143446225338
Fold 4 IBS: 0.15694953508014142
Fold 5 IBS: 0.2316203069237443
[I 2024-04-20 17:16:21,544] Trial 74 finished with value: 0.18708881401949995 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 451, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5762811196680634, 'min_weight_fraction_leaf': 0.04721403021162478}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.16278536069617075
Fold 2 IBS: 0.22061911570320727
Fold 3 IBS: 0.15948095174532076
Fold 4 IBS: 0.1500453215492157
Fold 5 IBS: 0.23108140998200039
[I 2024-04-20 17:16:24,028] Trial 75 finished with value: 0.18480243193518295 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 463, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6487943567829829, 'min_weight_fraction_leaf': 0.011079149496446542}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1649931201311961
Fold 2 IBS: 0.2191098546301487
Fold 3 IBS: 0.1604180424655896
Fold 4 IBS: 0.15133070246635846
Fold 5 IBS: 0.23270813963892614
[I 2024-04-20 17:16:27,345] Trial 76 finished with value: 0.18571197186644378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 496, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6611270444897925, 'min_weight_fraction_leaf': 0.03472791790328323}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17454705567490922
Fold 2 IBS: 0.20946654124798095
Fold 3 IBS: 0.17107052561345987
Fold 4 IBS: 0.17205506925206807
Fold 5 IBS: 0.22301050367917757
[I 2024-04-20 17:16:29,783] Trial 77 finished with value: 0.19002993909351912 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5365605521283588, 'min_weight_fraction_leaf': 0.11295942956753599}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18204012108405643
Fold 2 IBS: 0.2063716852750058
Fold 3 IBS: 0.17875146851232082
Fold 4 IBS: 0.18921011660617745
Fold 5 IBS: 0.2162548711235392
[I 2024-04-20 17:16:32,017] Trial 78 finished with value: 0.19452565252021997 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 427, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.5917795612536799, 'min_weight_fraction_leaf': 0.2198684675175928}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17845532120437899
Fold 2 IBS: 0.20772503338895465
Fold 3 IBS: 0.17421627745462215
Fold 4 IBS: 0.18019949439245914
Fold 5 IBS: 0.22083458875793646
[I 2024-04-20 17:16:34,592] Trial 79 finished with value: 0.19228614303967032 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.49597522186369347, 'min_weight_fraction_leaf': 0.06112532202305438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16158996672320755
Fold 2 IBS: 0.21729610032334276
Fold 3 IBS: 0.157796999636179
Fold 4 IBS: 0.1472728675908385
Fold 5 IBS: 0.23183976837586612
[I 2024-04-20 17:16:36,725] Trial 80 finished with value: 0.18315914052988677 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6281972616252203, 'min_weight_fraction_leaf': 0.00848688046818526}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16157863775376022
Fold 2 IBS: 0.22087534780676452
Fold 3 IBS: 0.15999281456554124
Fold 4 IBS: 0.14853123619761843
Fold 5 IBS: 0.23150501980376892
[I 2024-04-20 17:16:38,843] Trial 81 finished with value: 0.18449661122549066 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 392, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7386940991152582, 'min_weight_fraction_leaf': 0.01046274314610217}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16352260586628395
Fold 2 IBS: 0.22200502430399466
Fold 3 IBS: 0.15886916219783537
Fold 4 IBS: 0.14807572814886177
Fold 5 IBS: 0.2339085838911687
[I 2024-04-20 17:16:40,989] Trial 82 finished with value: 0.1852762208816289 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7162267948855195, 'min_weight_fraction_leaf': 0.032010312646594104}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16546027653935427
Fold 2 IBS: 0.2211659942343032
Fold 3 IBS: 0.16100661860428056
Fold 4 IBS: 0.15097334931915155
Fold 5 IBS: 0.2358306721546786
[I 2024-04-20 17:16:43,099] Trial 83 finished with value: 0.18688738217035364 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7326293257583885, 'min_weight_fraction_leaf': 0.04562346387387325}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285220423552985
Fold 2 IBS: 0.2188473500308101
Fold 3 IBS: 0.1599688920049345
Fold 4 IBS: 0.14885881691304034
Fold 5 IBS: 0.23161635394463342
[I 2024-04-20 17:16:45,042] Trial 84 finished with value: 0.18442872342578964 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 356, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7090996631118544, 'min_weight_fraction_leaf': 0.011358284348193259}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16285549245105505
Fold 2 IBS: 0.21942277067272614
Fold 3 IBS: 0.15946829525657427
Fold 4 IBS: 0.14838517247840774
Fold 5 IBS: 0.23122387168068076
[I 2024-04-20 17:16:47,041] Trial 85 finished with value: 0.1842711205078888 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7186868789202818, 'min_weight_fraction_leaf': 0.01496729486923688}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16128591165678588
Fold 2 IBS: 0.21980011323918688
Fold 3 IBS: 0.15937248726208542
Fold 4 IBS: 0.1486127266622536
Fold 5 IBS: 0.2323048878882266
[I 2024-04-20 17:16:48,990] Trial 86 finished with value: 0.18427522534170765 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 363, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7543993526497688, 'min_weight_fraction_leaf': 0.013808236520630852}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16094110571393064
Fold 2 IBS: 0.21986993252478362
Fold 3 IBS: 0.1588596843743244
Fold 4 IBS: 0.14614051224869679
Fold 5 IBS: 0.23352782586558365
[I 2024-04-20 17:16:50,891] Trial 87 finished with value: 0.1838678121454638 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7599338110461693, 'min_weight_fraction_leaf': 0.01151287364248438}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16095650535504896
Fold 2 IBS: 0.21964363350705826
Fold 3 IBS: 0.15886397081421852
Fold 4 IBS: 0.14614666331841772
Fold 5 IBS: 0.23313729954057164
[I 2024-04-20 17:16:53,334] Trial 88 finished with value: 0.183749614507063 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 360, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7606093640745762, 'min_weight_fraction_leaf': 0.010471830721284079}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16110829576026084
Fold 2 IBS: 0.21851253412110366
Fold 3 IBS: 0.15675512925824683
Fold 4 IBS: 0.14727139463073632
Fold 5 IBS: 0.23209620967854572
[I 2024-04-20 17:16:55,786] Trial 89 finished with value: 0.18314871268977867 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7587282239351308, 'min_weight_fraction_leaf': 0.008176941543787496}. Best is trial 53 with value: 0.18257594357755064.

Fold 1 IBS: 0.18162653052097805
Fold 2 IBS: 0.20612651784753333
Fold 3 IBS: 0.1771784733434652
Fold 4 IBS: 0.18941755917999278
Fold 5 IBS: 0.21614311489575638
[I 2024-04-20 17:16:58,173] Trial 90 finished with value: 0.19409843915754516 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7635642567316503, 'min_weight_fraction_leaf': 0.280081595660318}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16186089564069253
Fold 2 IBS: 0.21899259491528042
Fold 3 IBS: 0.15921485444738478
Fold 4 IBS: 0.148193042465612
Fold 5 IBS: 0.23190417972474658
[I 2024-04-20 17:17:00,373] Trial 91 finished with value: 0.18403311343874326 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.789178452265885, 'min_weight_fraction_leaf': 0.011545143067658635}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16265353400501528
Fold 2 IBS: 0.2175575638863236
Fold 3 IBS: 0.16133894389326223
Fold 4 IBS: 0.15458872962543557
Fold 5 IBS: 0.229228321655463
[I 2024-04-20 17:17:02,524] Trial 92 finished with value: 0.18507341861309995 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 320, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7985486683510279, 'min_weight_fraction_leaf': 0.007901199895383132}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1620791424844971
Fold 2 IBS: 0.21900011819041879
Fold 3 IBS: 0.15920401655120014
Fold 4 IBS: 0.14637781084518398
Fold 5 IBS: 0.23282788799260146
[I 2024-04-20 17:17:04,832] Trial 93 finished with value: 0.1838977952127803 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 341, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7705275977783406, 'min_weight_fraction_leaf': 0.013704505872889598}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1793411990654569
Fold 2 IBS: 0.20613622174736498
Fold 3 IBS: 0.17275187695258565
Fold 4 IBS: 0.17818980825839892
Fold 5 IBS: 0.22022859697507743
[I 2024-04-20 17:17:07,006] Trial 94 finished with value: 0.19132954059977678 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 325, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7755480125040337, 'min_weight_fraction_leaf': 0.05063148942960361}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.1610317396130936
Fold 2 IBS: 0.2202627419888432
Fold 3 IBS: 0.15951569709008712
Fold 4 IBS: 0.1458873166232896
Fold 5 IBS: 0.23482464408960785
[I 2024-04-20 17:17:09,433] Trial 95 finished with value: 0.18430442788098428 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 350, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7576152916362451, 'min_weight_fraction_leaf': 0.023770792047509592}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.17066297262534935
Fold 2 IBS: 0.22975974207949945
Fold 3 IBS: 0.1519444360637532
Fold 4 IBS: 0.13950104633987118
Fold 5 IBS: 0.2439409705061117
[I 2024-04-20 17:17:11,947] Trial 96 finished with value: 0.18716183352291696 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7560665367452727, 'min_weight_fraction_leaf': 0.02298285611760403}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.18361848353136237
Fold 2 IBS: 0.2052929877088459
Fold 3 IBS: 0.17656731308943907
Fold 4 IBS: 0.18399483123099875
Fold 5 IBS: 0.21866940095388543
[I 2024-04-20 17:17:13,934] Trial 97 finished with value: 0.1936286033029063 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 294, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7936215885628722, 'min_weight_fraction_leaf': 0.0702592146341984}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16102070948187022
Fold 2 IBS: 0.22255035648510013
Fold 3 IBS: 0.1611617777057763
Fold 4 IBS: 0.14597987975871002
Fold 5 IBS: 0.23595320519699498
[I 2024-04-20 17:17:16,241] Trial 98 finished with value: 0.18533318572569035 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.817957524711727, 'min_weight_fraction_leaf': 0.0008689368092096427}. Best is trial 53 with value: 0.18257594357755064.
Fold 1 IBS: 0.16218129609850532
Fold 2 IBS: 0.21864999525446885
Fold 3 IBS: 0.1599823914541389
Fold 4 IBS: 0.14944190039573815
Fold 5 IBS: 0.23537346983323632
[I 2024-04-20 17:17:18,348] Trial 99 finished with value: 0.1851258106072175 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7505423882418932, 'min_weight_fraction_leaf': 0.027516392549616332}. Best is trial 53 with value: 0.18257594357755064.


* Best trial for IBS:
 FrozenTrial(number=53, state=TrialState.COMPLETE, values=[0.18257594357755064], datetime_start=datetime.datetime(2024, 4, 20, 17, 15, 29, 974560), datetime_complete=datetime.datetime(2024, 4, 20, 17, 15, 32, 573443), params={'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7048480399273186, 'min_weight_fraction_leaf': 0.0010291888027469595}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=53, value=None)


* Best Score for IBS:
 0.18257594357755064

In [65]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [66]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.794
train_ibs:  0.183

#### Test

In [67]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [68]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=12, max_features=None, max_leaf_nodes=6,
                   max_samples=0.7030590704740037, min_samples_leaf=6,
                   min_samples_split=13,
                   min_weight_fraction_leaf=0.020016091327628317,
                   n_estimators=273, random_state=123, warm_start=True)

C-index score: 0.618

ExtraSurvivalTrees(max_depth=13, max_features='log2', max_leaf_nodes=6,
                   max_samples=0.7048480399273186, min_samples_leaf=1,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.0010291888027469595,
                   n_estimators=485, random_state=123, warm_start=True)

IBS: 0.215

In [69]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [70]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-20 17:17:19,313] A new study created in memory with name: no-name-3229b0f1-758b-41e8-8f15-2a340747ffd7

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:17:29,612] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:17:35,340] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:17:40,795] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:17:49,410] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:17:52,917] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:17:53,780] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:18:02,294] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:18:04,817] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:18:05,119] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6450892857142857
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6314553990610329
[I 2024-04-20 17:18:28,037] Trial 9 finished with value: 0.7334874350516556 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:19:02,207] Trial 10 finished with value: 0.685844917453683 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:19:40,592] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.625
Fold 3 C-index: 0.7622549019607843
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:20:13,002] Trial 12 finished with value: 0.703856671925322 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:20:32,669] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:20:56,206] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:21:17,644] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:21:31,833] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:22:03,294] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:22:45,987] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:22:47,824] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:23:02,263] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:23:33,885] Trial 21 finished with value: 0.5772199484787512 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.5892018779342723
[I 2024-04-20 17:24:02,880] Trial 22 finished with value: 0.7242619704042982 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:24:26,792] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:24:48,263] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:25:01,049] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:25:28,053] Trial 26 finished with value: 0.5421550134138162 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:25:55,102] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:26:17,166] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:26:32,578] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:26:50,817] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:27:26,497] Trial 31 finished with value: 0.6331023014199277 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:27:59,792] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:28:22,055] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:28:52,786] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:28:58,594] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:29:27,465] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-20 17:29:28,354] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:29:39,062] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:29:55,856] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:30:23,668] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5868544600938967
[I 2024-04-20 17:30:23,774] Trial 41 finished with value: 0.669385375890579 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:30:26,951] Trial 42 finished with value: 0.7134801645905124 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:30:30,320] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8842674505407576, 'learning_rate': 0.01661025860323942, 'dropout_rate': 0.11585930219083569, 'n_estimators': 137, 'criterion': 'squared_error', 'ccp_alpha': 1.1648976852393267, 'min_weight_fraction_leaf': 0.2628710582683432, 'max_features': 'auto', 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.8573418806492034, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:30:38,194] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9369906738516638, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.2600301660425801, 'n_estimators': 236, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.44828046137677974, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.723434155611114, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:30:41,765] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.8508184042922002, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.5950934322255128, 'min_weight_fraction_leaf': 0.3672741344156673, 'max_features': 0.1, 'min_impurity_decrease': 9.999645993471922e-07, 'validation_fraction': 0.894831925816593, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:30:45,112] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.007318845785810312, 'dropout_rate': 0.9694253886674298, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.0041987442036233, 'min_weight_fraction_leaf': 0.41002460147990016, 'max_features': 'log2', 'min_impurity_decrease': 2.595046469962732e-06, 'validation_fraction': 0.8313632450390351, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:30:57,756] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.7881603947064, 'learning_rate': 0.024308371272538112, 'dropout_rate': 0.11931202058020746, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.46145706703279166, 'min_weight_fraction_leaf': 0.14638041253524992, 'max_features': 'sqrt', 'min_impurity_decrease': 3.124298610650395e-07, 'validation_fraction': 0.885979815139411, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:31:03,245] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9116990829700251, 'learning_rate': 0.0012697805220829685, 'dropout_rate': 0.2528872202970577, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.33510432917217986, 'max_features': None, 'min_impurity_decrease': 1.0186154127552982e-07, 'validation_fraction': 0.9531390028399015, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-20 17:31:17,689] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9503333802028551, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 420, 'criterion': 'friedman_mse', 'ccp_alpha': 6.6082653368298185, 'min_weight_fraction_leaf': 0.22522458248307622, 'max_features': 'auto', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.6535676180999174, 'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:31:18,709] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8351429935193848, 'learning_rate': 0.02150329631555176, 'dropout_rate': 0.3666232473259417, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 1.3133337630740611, 'min_weight_fraction_leaf': 0.47565429586146185, 'max_features': 'auto', 'min_impurity_decrease': 1.8633023596687113e-06, 'validation_fraction': 0.8119058063801081, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:31:18,880] Trial 51 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9947653262192967, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.1592738913883298, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3857975848065366, 'max_features': 'auto', 'min_impurity_decrease': 1.8142952936262792e-07, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:31:19,081] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9838263913881168, 'learning_rate': 0.007162813008405933, 'dropout_rate': 0.17395958025907304, 'n_estimators': 17, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.37395658840830287, 'max_features': 'auto', 'min_impurity_decrease': 1.9340874733278664e-07, 'validation_fraction': 0.9673436129299916, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.578125
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 17:31:21,530] Trial 53 finished with value: 0.7035675756915192 and parameters: {'subsample': 0.8832560354405471, 'learning_rate': 0.013515333982145643, 'dropout_rate': 0.1066966218862955, 'n_estimators': 115, 'criterion': 'squared_error', 'ccp_alpha': 0.00962522783777093, 'min_weight_fraction_leaf': 0.3102859232383388, 'max_features': 'auto', 'min_impurity_decrease': 5.129651522544754e-07, 'validation_fraction': 0.9977392300861776, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:31:23,703] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8839401595086688, 'learning_rate': 0.013720158661514745, 'dropout_rate': 0.11547001021095907, 'n_estimators': 108, 'criterion': 'squared_error', 'ccp_alpha': 0.9585348267499517, 'min_weight_fraction_leaf': 0.31281161202556473, 'max_features': 'auto', 'min_impurity_decrease': 5.50189997369896e-07, 'validation_fraction': 0.9994238437001496, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:31:24,236] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.8309421840852462, 'learning_rate': 0.011311223505622352, 'dropout_rate': 0.20419816136861105, 'n_estimators': 45, 'criterion': 'squared_error', 'ccp_alpha': 0.3986990587399982, 'min_weight_fraction_leaf': 0.2039350020074899, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8756039908972886, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:32:00,417] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.72294472419416, 'learning_rate': 0.030529655796453406, 'dropout_rate': 0.1042670173421051, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.0260576154507228, 'min_weight_fraction_leaf': 0.26869875361297285, 'max_features': 1, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.9043438819355977, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:32:02,589] Trial 57 finished with value: 0.5 and parameters: {'subsample': 0.781561535505851, 'learning_rate': 0.019599111388603693, 'dropout_rate': 0.28746581622574, 'n_estimators': 118, 'criterion': 'squared_error', 'ccp_alpha': 1.6775249385492055, 'min_weight_fraction_leaf': 0.4147367845229429, 'max_features': 'auto', 'min_impurity_decrease': 5.608534822955176e-07, 'validation_fraction': 0.5838562151808616, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:32:06,657] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.4443705051573945, 'learning_rate': 0.04030629833839253, 'dropout_rate': 0.24216293738207553, 'n_estimators': 164, 'criterion': 'squared_error', 'ccp_alpha': 0.7497240498249881, 'min_weight_fraction_leaf': 0.33754637584813874, 'max_features': 0.1, 'min_impurity_decrease': 3.445912059389303e-07, 'validation_fraction': 0.7729698485030033, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:32:36,470] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9301898151121387, 'learning_rate': 0.014811565508437466, 'dropout_rate': 0.1837704285299646, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.302647558909275, 'max_features': 'log2', 'min_impurity_decrease': 4.132096543200702e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:32:47,158] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.2779429418662181, 'learning_rate': 0.005013007250233982, 'dropout_rate': 0.14183557134552166, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 1.322729891908786, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'auto', 'min_impurity_decrease': 1.9418303906939395e-06, 'validation_fraction': 0.8435510786021796, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

Fold 5 C-index: 0.5
[I 2024-04-20 17:32:48,141] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.009978939472425662, 'dropout_rate': 0.2238557425834033, 'n_estimators': 70, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.4432436454062534, 'max_features': 'auto', 'min_impurity_decrease': 1.92080140518381e-07, 'validation_fraction': 0.9540853929856796, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:32:53,159] Trial 62 finished with value: 0.685844917453683 and parameters: {'subsample': 0.9949849995633986, 'learning_rate': 0.00590733686751327, 'dropout_rate': 0.15426665038628304, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.3771525913161122, 'max_features': 'auto', 'min_impurity_decrease': 1.6541961435697376e-07, 'validation_fraction': 0.998924391459097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 17:32:53,924] Trial 63 finished with value: 0.7163384910196757 and parameters: {'subsample': 0.8686583129899306, 'learning_rate': 0.001290161829137394, 'dropout_rate': 0.1898785022640528, 'n_estimators': 58, 'criterion': 'squared_error', 'ccp_alpha': 0.018078806214999348, 'min_weight_fraction_leaf': 0.3861329521141052, 'max_features': 'auto', 'min_impurity_decrease': 8.327527140717665e-07, 'validation_fraction': 0.932887892507485, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:32:55,310] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.8645070165323501, 'learning_rate': 0.09405807235270042, 'dropout_rate': 0.18802779859574847, 'n_estimators': 85, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.35251200695718055, 'max_features': 'auto', 'min_impurity_decrease': 9.420976138154327e-07, 'validation_fraction': 0.9231276840562984, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:32:57,646] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.903563418868777, 'learning_rate': 0.0016217786521075337, 'dropout_rate': 0.27304642297183634, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.35075027656676333, 'min_weight_fraction_leaf': 0.46836556984836597, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.8837902558696593, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:33:33,629] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.8164719060956207, 'learning_rate': 0.012803396580721372, 'dropout_rate': 0.13161439171907266, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.8927340743616367, 'min_weight_fraction_leaf': 0.24360172036034505, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.9783741103646215, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:33:34,100] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8652614464897083, 'learning_rate': 0.017792589526001042, 'dropout_rate': 0.4308859881762669, 'n_estimators': 45, 'criterion': 'friedman_mse', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.4527437444308926, 'max_features': 'auto', 'min_impurity_decrease': 3.132340488371029e-07, 'validation_fraction': 0.6922946122950581, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:33:42,174] Trial 68 finished with value: 0.6328510949834479 and parameters: {'subsample': 0.1828808967076968, 'learning_rate': 0.009763210879301733, 'dropout_rate': 0.227818798660288, 'n_estimators': 235, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.4165856705288462, 'max_features': 'auto', 'min_impurity_decrease': 1.2512174866550223e-06, 'validation_fraction': 0.4611449164937295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:33:42,849] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.7498611166680669, 'learning_rate': 0.04820609879441119, 'dropout_rate': 0.32090257654334975, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.7413034944146035, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': None, 'min_impurity_decrease': 2.3700234556978203e-06, 'validation_fraction': 0.8668588900403627, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:34:10,180] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.911088145674265, 'learning_rate': 0.0228629548900178, 'dropout_rate': 0.1866548676915602, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.2482267223936536, 'min_weight_fraction_leaf': 0.22078244504185224, 'max_features': 'auto', 'min_impurity_decrease': 4.8419433611640654e-06, 'validation_fraction': 0.9040102661274384, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 17:34:10,326] Trial 71 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9622573373756947, 'learning_rate': 0.005576631516276089, 'dropout_rate': 0.8462757993963043, 'n_estimators': 10, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.38504148100809776, 'max_features': 'auto', 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.9482945382047324, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 17:34:10,564] Trial 72 finished with value: 0.685844917453683 and parameters: {'subsample': 0.950430822794731, 'learning_rate': 0.0053064296987160465, 'dropout_rate': 0.7234474037831898, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.00479380572002332, 'min_weight_fraction_leaf': 0.3972455103663686, 'max_features': 'auto', 'min_impurity_decrease': 1.366202506746777e-07, 'validation_fraction': 0.9693127617967663, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:34:17,098] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.885575181084042, 'learning_rate': 0.003536949776399335, 'dropout_rate': 0.9088405719505623, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.35670027635353807, 'min_weight_fraction_leaf': 0.35822108217683835, 'max_features': 'auto', 'min_impurity_decrease': 4.2499433142234475e-07, 'validation_fraction': 0.20224553600156958, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:34:17,336] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.5836393594321302, 'learning_rate': 0.009340590354270865, 'dropout_rate': 0.8412829433501265, 'n_estimators': 30, 'criterion': 'squared_error', 'ccp_alpha': 0.6246646628477466, 'min_weight_fraction_leaf': 0.42429330054001607, 'max_features': 'auto', 'min_impurity_decrease': 2.8316890658493217e-07, 'validation_fraction': 0.9340639943674915, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:34:19,218] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.5200735929114648, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.128072187563372, 'n_estimators': 99, 'criterion': 'squared_error', 'ccp_alpha': 0.9318541971101635, 'min_weight_fraction_leaf': 0.329634418869288, 'max_features': 'auto', 'min_impurity_decrease': 7.061217543698309e-07, 'validation_fraction': 0.7955814541363518, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:34:33,920] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9312152381840203, 'learning_rate': 0.011963342113513162, 'dropout_rate': 0.640126219035525, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3025319765337648, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 1.4007647974844957e-07, 'validation_fraction': 0.7443065618057785, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:34:34,549] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.9689893891792536, 'learning_rate': 0.05776064499915696, 'dropout_rate': 0.5468452572744673, 'n_estimators': 63, 'criterion': 'squared_error', 'ccp_alpha': 0.5979952840890602, 'min_weight_fraction_leaf': 0.25434486774085874, 'max_features': 1, 'min_impurity_decrease': 2.595814783640358e-07, 'validation_fraction': 0.9726620416567261, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:35:09,540] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.8595097382714689, 'learning_rate': 0.0034833775412467377, 'dropout_rate': 0.10127265486770577, 'n_estimators': 473, 'criterion': 'friedman_mse', 'ccp_alpha': 1.4812955313687048, 'min_weight_fraction_leaf': 0.3131777562301877, 'max_features': 'auto', 'min_impurity_decrease': 1.0290395334568972e-07, 'validation_fraction': 0.8280705957992395, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:35:14,142] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.8015344520335466, 'learning_rate': 0.0012723432779221475, 'dropout_rate': 0.8831816560103296, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 1.8162144553916222, 'min_weight_fraction_leaf': 0.34854584327537885, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9186131425355593, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:35:24,843] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.8367376204446394, 'learning_rate': 0.007364213642980483, 'dropout_rate': 0.702176827465796, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3004980772276427, 'max_features': 'auto', 'min_impurity_decrease': 7.124034486377485e-07, 'validation_fraction': 0.9461272730178157, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 17:35:24,962] Trial 81 finished with value: 0.6684464087544287 and parameters: {'subsample': 0.9965174069194047, 'learning_rate': 0.007618988907310126, 'dropout_rate': 0.16198782693693461, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.025916849299345394, 'min_weight_fraction_leaf': 0.38961846335957595, 'max_features': 'auto', 'min_impurity_decrease': 1.766837964281054e-07, 'validation_fraction': 0.9399776044267211, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 17:35:25,134] Trial 82 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.9646485447558332, 'learning_rate': 0.006224947240679894, 'dropout_rate': 0.16886094857249775, 'n_estimators': 12, 'criterion': 'squared_error', 'ccp_alpha': 0.017707201149411784, 'min_weight_fraction_leaf': 0.38368758581534546, 'max_features': 'auto', 'min_impurity_decrease': 2.2084017063206466e-07, 'validation_fraction': 0.38434645874984097, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:35:25,539] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9674120427099258, 'learning_rate': 0.012634880227471968, 'dropout_rate': 0.24105562803816832, 'n_estimators': 36, 'criterion': 'squared_error', 'ccp_alpha': 0.49986991060004404, 'min_weight_fraction_leaf': 0.4028329566858333, 'max_features': 'auto', 'min_impurity_decrease': 3.7732222209322964e-07, 'validation_fraction': 0.29115286333596435, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:00,546] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.9187525025568754, 'learning_rate': 0.004160535799768975, 'dropout_rate': 0.2015650563323303, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.3706545282616189, 'max_features': 'auto', 'min_impurity_decrease': 1.4899460740955453e-06, 'validation_fraction': 0.39196940849585504, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:00,745] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.8968529080615669, 'learning_rate': 0.017670564382826763, 'dropout_rate': 0.2745425858009699, 'n_estimators': 16, 'criterion': 'squared_error', 'ccp_alpha': 1.0637247669291705, 'min_weight_fraction_leaf': 0.3822449692929958, 'max_features': 'auto', 'min_impurity_decrease': 2.3419797764275672e-07, 'validation_fraction': 0.5434611145938996, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:01,498] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.9428961007941905, 'learning_rate': 0.011402694667743098, 'dropout_rate': 0.134159592794598, 'n_estimators': 56, 'criterion': 'squared_error', 'ccp_alpha': 0.23936333725455253, 'min_weight_fraction_leaf': 0.27268436275419344, 'max_features': 'sqrt', 'min_impurity_decrease': 4.779762823701413e-07, 'validation_fraction': 0.3558315208173153, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:02,138] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9642091284813806, 'learning_rate': 0.009067059593875184, 'dropout_rate': 0.8053771471721777, 'n_estimators': 81, 'criterion': 'squared_error', 'ccp_alpha': 0.2360450448272922, 'min_weight_fraction_leaf': 0.36130355929034824, 'max_features': 'auto', 'min_impurity_decrease': 1.6608380458349677e-05, 'validation_fraction': 0.48901442871881995, 'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:02,877] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9166952579476793, 'learning_rate': 0.027428474441345257, 'dropout_rate': 0.9942411221597407, 'n_estimators': 142, 'criterion': 'squared_error', 'ccp_alpha': 0.736661694905559, 'min_weight_fraction_leaf': 0.3421577371226225, 'max_features': 'auto', 'min_impurity_decrease': 1.3101245725982968e-07, 'validation_fraction': 0.9819335319333689, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:29,785] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.38730242337646104, 'learning_rate': 0.020510559401054396, 'dropout_rate': 0.1637660735943165, 'n_estimators': 425, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5135760709608489, 'min_weight_fraction_leaf': 0.2338348901049672, 'max_features': None, 'min_impurity_decrease': 8.646658253890459e-07, 'validation_fraction': 0.2693385873685563, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:32,532] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.3351416528138606, 'learning_rate': 0.001130725657308556, 'dropout_rate': 0.21238181902547987, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 1.098484581242824, 'min_weight_fraction_leaf': 0.45624128176873047, 'max_features': 'auto', 'min_impurity_decrease': 2.8288075937135275e-07, 'validation_fraction': 0.8654647894710668, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.7637130801687764
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 17:36:32,809] Trial 91 finished with value: 0.6877228517259836 and parameters: {'subsample': 0.973859764718155, 'learning_rate': 0.006991850627181431, 'dropout_rate': 0.17031167363762192, 'n_estimators': 24, 'criterion': 'squared_error', 'ccp_alpha': 0.03873428305932247, 'min_weight_fraction_leaf': 0.38456389013049225, 'max_features': 'auto', 'min_impurity_decrease': 2.1057313400290866e-07, 'validation_fraction': 0.9606810926219381, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:33,105] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8803056919201186, 'learning_rate': 0.005845639334984173, 'dropout_rate': 0.17652933801835793, 'n_estimators': 26, 'criterion': 'squared_error', 'ccp_alpha': 0.20706720697578515, 'min_weight_fraction_leaf': 0.43161442258073124, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.9025757365890354, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:33,239] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9733203192391623, 'learning_rate': 0.014432394643112474, 'dropout_rate': 0.2300740953304724, 'n_estimators': 4, 'criterion': 'squared_error', 'ccp_alpha': 0.46903049977228617, 'min_weight_fraction_leaf': 0.404652010953728, 'max_features': 'auto', 'min_impurity_decrease': 5.086967260434284e-07, 'validation_fraction': 0.9736018036138772, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:33,674] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.9359287316154687, 'learning_rate': 0.003576820689332409, 'dropout_rate': 0.14182769534201045, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 0.850632602885982, 'min_weight_fraction_leaf': 0.41989514755999646, 'max_features': 'auto', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.9231910021785822, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5558035714285714
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 17:36:34,361] Trial 95 finished with value: 0.5701693113224804 and parameters: {'subsample': 0.8441489229564334, 'learning_rate': 0.010686672701851392, 'dropout_rate': 0.12427113599249004, 'n_estimators': 52, 'criterion': 'squared_error', 'ccp_alpha': 0.13095957774357525, 'min_weight_fraction_leaf': 0.208662917753807, 'max_features': 'auto', 'min_impurity_decrease': 0.04760435998517946, 'validation_fraction': 0.9999851977461973, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 9 with value: 0.7334874350516556.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.7566964285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.820675105485232
Fold 5 C-index: 0.607981220657277
[I 2024-04-20 17:36:35,953] Trial 96 finished with value: 0.7453020253507325 and parameters: {'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-20 17:36:37,583] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8890132762537363, 'learning_rate': 0.016000147782265963, 'dropout_rate': 0.33412474584068513, 'n_estimators': 102, 'criterion': 'squared_error', 'ccp_alpha': 4.683860932586834, 'min_weight_fraction_leaf': 0.3259150375155791, 'max_features': 1, 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.6283958723553874, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 96 with value: 0.7453020253507325.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-20 17:36:39,197] A new study created in memory with name: no-name-f3b2b629-4f3a-490a-9a80-b6b7ed146e71

Fold 5 C-index: 0.5
[I 2024-04-20 17:36:39,017] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8159517170308073, 'learning_rate': 0.008130653433584725, 'dropout_rate': 0.29126647641167647, 'n_estimators': 92, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.48045734256987266, 'max_features': 1, 'min_impurity_decrease': 1.030784288757872e-07, 'validation_fraction': 0.4049740702980035, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 96 with value: 0.7453020253507325.
Fold 1 C-index: 0.5844155844155844
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7083333333333334
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6291079812206573
[I 2024-04-20 17:36:39,192] Trial 99 finished with value: 0.7038145684617871 and parameters: {'subsample': 0.9036420036324795, 'learning_rate': 0.013060448266216875, 'dropout_rate': 0.37151966270502923, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 0.004512555601867606, 'min_weight_fraction_leaf': 0.43840629474088344, 'max_features': 1, 'min_impurity_decrease': 2.1305992007975229e-07, 'validation_fraction': 0.8858148503753556, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 16}. Best is trial 96 with value: 0.7453020253507325.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.7453020253507325], datetime_start=datetime.datetime(2024, 4, 20, 17, 36, 34, 365075), datetime_complete=datetime.datetime(2024, 4, 20, 17, 36, 35, 953117), params={'subsample': 0.8938290428827321, 'learning_rate': 0.007359366951045268, 'dropout_rate': 0.2576884847115747, 'n_estimators': 96, 'criterion': 'squared_error', 'ccp_alpha': 0.03063070291051248, 'min_weight_fraction_leaf': 0.38180626899357545, 'max_features': 1, 'min_impurity_decrease': 1.3903906488794697e-07, 'validation_fraction': 0.9577535215137098, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=96, value=None)


* Best Score for C-index:
 0.7453020253507325

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:36:49,268] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:36:54,821] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:37:00,168] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:37:08,531] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:37:11,978] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:37:12,847] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:37:21,203] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:37:23,713] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:37:24,036] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21302115522395498
Fold 2 IBS: 0.22130101345683229
Fold 3 IBS: 0.20356574496128135
Fold 4 IBS: 0.22373082985786685
Fold 5 IBS: 0.21796021556320513
[I 2024-04-20 17:37:45,766] Trial 9 finished with value: 0.21591579181262813 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21360017884301727
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2041609124821885
Fold 4 IBS: 0.22443190447044095
Fold 5 IBS: 0.21803455300047256
[I 2024-04-20 17:38:19,226] Trial 10 finished with value: 0.2163415912252844 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:38:57,019] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21383968411387158
Fold 2 IBS: 0.22156451448592526
Fold 3 IBS: 0.20440536466519849
Fold 4 IBS: 0.22459255869133457
Fold 5 IBS: 0.2180987264506579
[I 2024-04-20 17:39:29,177] Trial 12 finished with value: 0.21650016968139757 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-20 17:39:44,860] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:40:12,410] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:40:36,210] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:40:49,670] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:41:20,941] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:41:37,621] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:41:40,481] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:42:09,912] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21394946003688667
Fold 2 IBS: 0.22157225472001127
Fold 3 IBS: 0.20452938396094716
Fold 4 IBS: 0.2247371055371081
Fold 5 IBS: 0.21809210037899657
[I 2024-04-20 17:42:41,222] Trial 21 finished with value: 0.21657606092679 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21591579181262813.
Fold 1 IBS: 0.21275233971420443
Fold 2 IBS: 0.22141006773816166

Fold 3 IBS: 0.20334575604936503
Fold 4 IBS: 0.2231342747566171
Fold 5 IBS: 0.2179288192033457
[I 2024-04-20 17:43:16,234] Trial 22 finished with value: 0.21571425149233878 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:43:45,119] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:44:03,948] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:44:21,604] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:44:47,819] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:44:50,622] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:45:00,138] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:45:23,760] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:45:34,177] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2136950219225832
Fold 2 IBS: 0.2215362190250608
Fold 3 IBS: 0.2044185685149852
Fold 4 IBS: 0.22472904052923362
Fold 5 IBS: 0.21803316635813036
[I 2024-04-20 17:46:04,714] Trial 31 finished with value: 0.21648240326999862 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2130097385063184
Fold 2 IBS: 0.2214475600367709
Fold 3 IBS: 0.2035963921195872
Fold 4 IBS: 0.2235395355788286
Fold 5 IBS: 0.2179179888442139
[I 2024-04-20 17:46:34,594] Trial 32 finished with value: 0.21590224301714384 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:46:57,418] Trial 33 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:47:21,902] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:47:27,393] Trial 35 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:47:58,406] Trial 36 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:47:59,331] Trial 37 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:48:15,258] Trial 38 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609557
[I 2024-04-20 17:48:34,688] Trial 39 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-20 17:48:55,873] Trial 40 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.2133737249398968
Fold 2 IBS: 0.22149810300618933
Fold 3 IBS: 0.20392418223551953
Fold 4 IBS: 0.22395780771096238
Fold 5 IBS: 0.21807108026974395
[I 2024-04-20 17:49:27,465] Trial 41 finished with value: 0.21616497963246242 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21306226677867723
Fold 2 IBS: 0.22147749486211882
Fold 3 IBS: 0.20359544985689815
Fold 4 IBS: 0.22359166073512057
Fold 5 IBS: 0.21793202518042964
[I 2024-04-20 17:49:59,913] Trial 42 finished with value: 0.21593177948264888 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:50:36,183] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:51:03,483] Trial 44 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21378011659547358
Fold 2 IBS: 0.22145278135911364
Fold 3 IBS: 0.20436255304908924
Fold 4 IBS: 0.22448271516750193
Fold 5 IBS: 0.2180782304104917
[I 2024-04-20 17:51:30,074] Trial 45 finished with value: 0.21643127931633402 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:51:54,667] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-20 17:52:04,782] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:52:04,960] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:52:10,520] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-20 17:52:39,929] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21307969652873227
Fold 2 IBS: 0.22136886746037693
Fold 3 IBS: 0.203621499145842
Fold 4 IBS: 0.22363894843965748
Fold 5 IBS: 0.2179296735036949
[I 2024-04-20 17:53:12,395] Trial 51 finished with value: 0.2159277370156607 and parameters: {'subsample': 0.9914941239177857, 'learning_rate': 0.004643220694148276, 'dropout_rate': 0.14631717824203036, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.3402340557764622, 'max_features': 'auto', 'min_impurity_decrease': 1.0669017189349294e-07, 'validation_fraction': 0.9630345477132441, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:53:45,460] Trial 52 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9520094582202872, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.13770242385086745, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.3267226381086794, 'min_weight_fraction_leaf': 0.3347369286285409, 'max_features': 'auto', 'min_impurity_decrease': 1.8037977074379283e-07, 'validation_fraction': 0.9590095104838449, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 22 with value: 0.21571425149233878.
Fold 1 IBS: 0.21174315691146667
Fold 2 IBS: 0.22136281903923083
Fold 3 IBS: 0.2023927630992915
Fold 4 IBS: 0.2219411019366781
Fold 5 IBS: 0.21777624808878387
[I 2024-04-20 17:54:13,661] Trial 53 finished with value: 0.2150432178150902 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.1897783294507234, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.29880213170319914, 'max_features': 'auto', 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9964423942006735, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:54:41,734] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9951759842961662, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18641432881009587, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.29477236360216774, 'max_features': 'auto', 'min_impurity_decrease': 5.718312774105514e-07, 'validation_fraction': 0.9994814833877664, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:55:05,154] Trial 55 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9027683411994925, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.13472529918097312, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.36938177041618503, 'max_features': 'auto', 'min_impurity_decrease': 1.1016843774656315e-07, 'validation_fraction': 0.898549324711475, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:55:28,721] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8324789538052517, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.2217299975485909, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.33106978438275647, 'max_features': 'auto', 'min_impurity_decrease': 2.9232848365940597e-07, 'validation_fraction': 0.848519914422397, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:55:59,974] Trial 57 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8682011777139672, 'learning_rate': 0.031239466455985663, 'dropout_rate': 0.17322401428734607, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.2621422129699527, 'max_features': 'auto', 'min_impurity_decrease': 1.0096192890009967e-07, 'validation_fraction': 0.7861749990571634, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:56:38,147] Trial 58 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.10699123414946089, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 0.4695790047970817, 'min_weight_fraction_leaf': 0.4208497987584031, 'max_features': 1, 'min_impurity_decrease': 0.006144622142394407, 'validation_fraction': 0.9248722131485942, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 17:57:02,555] Trial 59 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.0011610373238817896, 'dropout_rate': 0.2835746645760172, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.2971262516319784, 'max_features': 0.1, 'min_impurity_decrease': 5.673772193709774e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 17:57:21,966] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7689457925126264, 'learning_rate': 0.01938137369688937, 'dropout_rate': 0.23766423890937624, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2523293803401735, 'min_weight_fraction_leaf': 0.31705920833651274, 'max_features': 'auto', 'min_impurity_decrease': 1.09574587374673e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-20 17:57:51,009] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.005150255907863737, 'dropout_rate': 0.2646601381824477, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.20542807578152888, 'min_weight_fraction_leaf': 0.24335809438237638, 'max_features': 'auto', 'min_impurity_decrease': 1.670100349442241e-07, 'validation_fraction': 0.9537438642784446, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21260039171576678
Fold 2 IBS: 0.22127522100059224
Fold 3 IBS: 0.2031294211565798
Fold 4 IBS: 0.22304748515979766
Fold 5 IBS: 0.21785716148870096
[I 2024-04-20 17:58:26,805] Trial 62 finished with value: 0.2155819361042875 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.009577802680942944, 'dropout_rate': 0.19576464123878148, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2712475429741565, 'max_features': 'auto', 'min_impurity_decrease': 2.6031567647465433e-06, 'validation_fraction': 0.9664234509760701, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 17:59:01,762] Trial 63 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9678670791375591, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.19439757224953633, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.2664239609493312, 'max_features': 'auto', 'min_impurity_decrease': 4.0390121021586725e-07, 'validation_fraction': 0.8804884805212966, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21315225506544797
Fold 2 IBS: 0.22120521782494593
Fold 3 IBS: 0.20370415696975244
Fold 4 IBS: 0.22392954297429343
Fold 5 IBS: 0.21800569131579653
[I 2024-04-20 17:59:40,093] Trial 64 finished with value: 0.21599937283004728 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.008241701765086935, 'dropout_rate': 0.16204590972071856, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.042747030615862165, 'min_weight_fraction_leaf': 0.20867683262863126, 'max_features': 'log2', 'min_impurity_decrease': 1.1622062475943789e-06, 'validation_fraction': 0.9709487288557038, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 18:00:07,770] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8687566763675275, 'learning_rate': 0.010290863736545098, 'dropout_rate': 0.20090531278751475, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 1.1077392169505795, 'min_weight_fraction_leaf': 0.35267930800388836, 'max_features': 'auto', 'min_impurity_decrease': 2.9695254103704335e-06, 'validation_fraction': 0.9981673914604385, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-20 18:00:11,712] Trial 66 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9104313304151431, 'learning_rate': 0.014815622348446418, 'dropout_rate': 0.1415896279444537, 'n_estimators': 149, 'criterion': 'squared_error', 'ccp_alpha': 0.7060910424624821, 'min_weight_fraction_leaf': 0.2796836959018326, 'max_features': 'auto', 'min_impurity_decrease': 5.127880425748818e-06, 'validation_fraction': 0.916501041728546, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:00:38,543] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.802369464636257, 'learning_rate': 0.00417552385002208, 'dropout_rate': 0.3370707390697732, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.22284347226729986, 'max_features': 'sqrt', 'min_impurity_decrease': 7.319926345244562e-07, 'validation_fraction': 0.8373361504171383, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:01:12,524] Trial 68 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9271983184882995, 'learning_rate': 0.026761786505961737, 'dropout_rate': 0.23198968531289843, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.3246047057302614, 'max_features': 'auto', 'min_impurity_decrease': 2.8105707733985375e-07, 'validation_fraction': 0.6390547838628696, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:01:38,282] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9669065339055751, 'learning_rate': 0.010765506871731714, 'dropout_rate': 0.30527953045505896, 'n_estimators': 440, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.18420157386134117, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.8784198437522095, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 18:01:53,143] Trial 70 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.041826568167709126, 'dropout_rate': 0.5905404972480945, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.3744309428528772, 'max_features': None, 'min_impurity_decrease': 1.5635679037041744e-07, 'validation_fraction': 0.9186076475421031, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21310093398309657
Fold 2 IBS: 0.22107852954082238
Fold 3 IBS: 0.20363684344049715
Fold 4 IBS: 0.2235062321376155
Fold 5 IBS: 0.2179952952989321
[I 2024-04-20 18:02:31,536] Trial 71 finished with value: 0.21586356688019276 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.008268552307118088, 'dropout_rate': 0.18133086892644865, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.1936286226601749, 'max_features': 'log2', 'min_impurity_decrease': 9.627538760330365e-07, 'validation_fraction': 0.9695063743987746, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.2124258387603463
Fold 2 IBS: 0.22057958449066262
Fold 3 IBS: 0.20279757841484652
Fold 4 IBS: 0.222180058336135
Fold 5 IBS: 0.21771098701395403
[I 2024-04-20 18:03:10,982] Trial 72 finished with value: 0.21513880940318889 and parameters: {'subsample': 0.9765713621264592, 'learning_rate': 0.00878714781905863, 'dropout_rate': 0.12511582109542432, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.1603532575763104, 'max_features': 'log2', 'min_impurity_decrease': 4.6121007580567444e-07, 'validation_fraction': 0.9726077921006634, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560958
[I 2024-04-20 18:03:46,169] Trial 73 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9999531614476969, 'learning_rate': 0.017515788008347112, 'dropout_rate': 0.12067593932125548, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.1608125340894365, 'max_features': 'log2', 'min_impurity_decrease': 4.330904032345818e-07, 'validation_fraction': 0.9762008597583516, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 18:04:23,539] Trial 74 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9378736061625563, 'learning_rate': 0.00962248608121305, 'dropout_rate': 0.17315149200510316, 'n_estimators': 491, 'criterion': 'squared_error', 'ccp_alpha': 0.370371857241124, 'min_weight_fraction_leaf': 0.11427286298314121, 'max_features': 'log2', 'min_impurity_decrease': 7.393622885050152e-07, 'validation_fraction': 0.9760588067950509, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:04:54,112] Trial 75 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8548930681972974, 'learning_rate': 0.05554512018944124, 'dropout_rate': 0.14951765413144097, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 1.3275069627126754, 'min_weight_fraction_leaf': 0.12844710013372065, 'max_features': 'log2', 'min_impurity_decrease': 1.0058881333640878e-06, 'validation_fraction': 0.9013416300485078, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560958
[I 2024-04-20 18:05:29,374] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9721782395774373, 'learning_rate': 0.003194443723182592, 'dropout_rate': 0.12011548645109148, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 1.507827148373076e-06, 'validation_fraction': 0.9325305665153546, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:06:05,759] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8921532985730489, 'learning_rate': 0.021931279910218017, 'dropout_rate': 0.19284931428290142, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.5905545096948588, 'min_weight_fraction_leaf': 0.07057220045251793, 'max_features': 'log2', 'min_impurity_decrease': 1.637559261311236e-05, 'validation_fraction': 0.8150762480319586, 'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-20 18:06:36,999] Trial 78 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.7443996478445325, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.25883194688905886, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 0.9915392376256854, 'min_weight_fraction_leaf': 0.18968885272282524, 'max_features': 'log2', 'min_impurity_decrease': 3.9150597642462115e-06, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-20 18:07:03,854] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9257604896060708, 'learning_rate': 0.01335084153769065, 'dropout_rate': 0.10072101837872541, 'n_estimators': 393, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28871198232416817, 'min_weight_fraction_leaf': 0.17483536292771176, 'max_features': 'log2', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9982218331650979, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 18:07:18,492] Trial 80 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.977148848015456, 'learning_rate': 0.004307663599041434, 'dropout_rate': 0.15920080431792163, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.20378735965998926, 'max_features': 1, 'min_impurity_decrease': 1.424247746508587e-06, 'validation_fraction': 0.8670066304726413, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21299867857890398
Fold 2 IBS: 0.2214477278201705
Fold 3 IBS: 0.20356620117857893
Fold 4 IBS: 0.22350168421901248
Fold 5 IBS: 0.21792379994243102
[I 2024-04-20 18:07:52,667] Trial 81 finished with value: 0.2158876183478194 and parameters: {'subsample': 0.9579178853393634, 'learning_rate': 0.007273589951884828, 'dropout_rate': 0.2054590932290375, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 0.02521700237735763, 'min_weight_fraction_leaf': 0.23721821844476393, 'max_features': 'auto', 'min_impurity_decrease': 2.628308399801263e-07, 'validation_fraction': 0.945876154428725, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21281996790006147
Fold 2 IBS: 0.22144914962179446
Fold 3 IBS: 0.2034201419570034
Fold 4 IBS: 0.22330541406123097
Fold 5 IBS: 0.21789799579435803
[I 2024-04-20 18:08:27,185] Trial 82 finished with value: 0.21577853386688967 and parameters: {'subsample': 0.9374850920793417, 'learning_rate': 0.009537962827339893, 'dropout_rate': 0.2311360143359113, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.01786403260693046, 'min_weight_fraction_leaf': 0.30128352038824946, 'max_features': 'auto', 'min_impurity_decrease': 2.672883759599648e-07, 'validation_fraction': 0.9419164447228301, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-20 18:08:58,914] Trial 83 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.008698584299413689, 'dropout_rate': 0.2878607631400676, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.42714757621714333, 'min_weight_fraction_leaf': 0.2701739605759479, 'max_features': 0.1, 'min_impurity_decrease': 4.793545557946714e-07, 'validation_fraction': 0.9339252824355873, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 18:09:29,898] Trial 84 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.016064279530571223, 'dropout_rate': 0.2326295808813899, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.7147702528804116, 'min_weight_fraction_leaf': 0.23638615893438736, 'max_features': 'auto', 'min_impurity_decrease': 3.019646046469693e-07, 'validation_fraction': 0.8979947940782089, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 18:09:57,733] Trial 85 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9376269876567488, 'learning_rate': 0.019091747704160993, 'dropout_rate': 0.20706945781506403, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.16619718561211044, 'min_weight_fraction_leaf': 0.15561996067062303, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.9731668294064385, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:10:28,948] Trial 86 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8785484469699407, 'learning_rate': 0.012070502053282707, 'dropout_rate': 0.2505427438802027, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 1.1270526375680832, 'min_weight_fraction_leaf': 0.25781248698190756, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2713997001011194e-06, 'validation_fraction': 0.943859242495053, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 18:10:52,860] Trial 87 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9090955901211109, 'learning_rate': 0.006929208749359209, 'dropout_rate': 0.49308788025511585, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.32252019630070927, 'min_weight_fraction_leaf': 0.3051832272732572, 'max_features': 'log2', 'min_impurity_decrease': 7.049454515025671e-07, 'validation_fraction': 0.37837273453407844, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:11:25,183] Trial 88 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9447987915285996, 'learning_rate': 0.014159070275535094, 'dropout_rate': 0.18102387516231752, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.5935000311483954, 'min_weight_fraction_leaf': 0.2151508441811604, 'max_features': 'auto', 'min_impurity_decrease': 3.72786238165322e-07, 'validation_fraction': 0.898328514849679, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21292314886383587
Fold 2 IBS: 0.2213935582997429
Fold 3 IBS: 0.20349492943164285
Fold 4 IBS: 0.2234443788901035
Fold 5 IBS: 0.2178743294294726
[I 2024-04-20 18:11:49,602] Trial 89 finished with value: 0.21582606898295956 and parameters: {'subsample': 0.9777744983689288, 'learning_rate': 0.01038357183462239, 'dropout_rate': 0.27697802684175754, 'n_estimators': 425, 'criterion': 'squared_error', 'ccp_alpha': 0.019074305728520667, 'min_weight_fraction_leaf': 0.2917659918820059, 'max_features': 'auto', 'min_impurity_decrease': 1.3598537758171917e-07, 'validation_fraction': 0.855835665987138, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:11:58,074] Trial 90 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9728383671704387, 'learning_rate': 0.009918951595706415, 'dropout_rate': 0.8458602043820649, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.8331973858915148, 'min_weight_fraction_leaf': 0.2921200274675525, 'max_features': 'auto', 'min_impurity_decrease': 1.4263141271201017e-07, 'validation_fraction': 0.6746483744961582, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21336618881179586
Fold 2 IBS: 0.22114294232267198
Fold 3 IBS: 0.20384999569236736
Fold 4 IBS: 0.22375343637403386
Fold 5 IBS: 0.21796174726134912
[I 2024-04-20 18:12:23,439] Trial 91 finished with value: 0.21601486209244367 and parameters: {'subsample': 0.2845120808216636, 'learning_rate': 0.007013602341022412, 'dropout_rate': 0.2673714840258141, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.03785557112751456, 'min_weight_fraction_leaf': 0.28289624505615074, 'max_features': 'auto', 'min_impurity_decrease': 2.167221721970957e-07, 'validation_fraction': 0.8389190675336428, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 18:12:33,737] Trial 92 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5328328014893517, 'learning_rate': 0.012214946715626797, 'dropout_rate': 0.21822342387423224, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 0.2716052866202, 'min_weight_fraction_leaf': 0.2516221825059295, 'max_features': 'auto', 'min_impurity_decrease': 5.164764561896499e-07, 'validation_fraction': 0.9118535684017283, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:13:02,091] Trial 93 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9215121808289675, 'learning_rate': 0.023968389847749173, 'dropout_rate': 0.3096195311954267, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.526845938693122, 'min_weight_fraction_leaf': 0.23408949316338243, 'max_features': 'auto', 'min_impurity_decrease': 3.3639036073651944e-07, 'validation_fraction': 0.9394031242668214, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:13:23,550] Trial 94 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9794737431495151, 'learning_rate': 0.002207391632430766, 'dropout_rate': 0.355864908714743, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.25602285176947265, 'min_weight_fraction_leaf': 0.1982598024964269, 'max_features': 'auto', 'min_impurity_decrease': 7.85301346539494e-07, 'validation_fraction': 0.8716461599738365, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:13:48,035] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8243603473818633, 'learning_rate': 0.016754070407166113, 'dropout_rate': 0.18244406164714, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 0.969239817362121, 'min_weight_fraction_leaf': 0.27320139306393876, 'max_features': None, 'min_impurity_decrease': 1.4323978100998562e-07, 'validation_fraction': 0.7967240220364479, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-20 18:14:21,818] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9567077577297926, 'learning_rate': 0.009321682904042736, 'dropout_rate': 0.24495589575382673, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 5.08611115752829, 'min_weight_fraction_leaf': 0.30649414543812215, 'max_features': 'auto', 'min_impurity_decrease': 1.2053286940776505e-06, 'validation_fraction': 0.7556909999934059, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-20 18:14:57,735] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8987436119584659, 'learning_rate': 0.0203626546956988, 'dropout_rate': 0.12954890528084062, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 1.5784834259170004, 'min_weight_fraction_leaf': 0.2550731647118252, 'max_features': 'auto', 'min_impurity_decrease': 1.890730180714205e-06, 'validation_fraction': 0.9772741387306807, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-20 18:15:25,781] Trial 98 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9426449416232375, 'learning_rate': 0.005258427870498378, 'dropout_rate': 0.29094318599258845, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.5297744472721807, 'min_weight_fraction_leaf': 0.2938783217761457, 'max_features': 1, 'min_impurity_decrease': 2.1824147145190313e-07, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 53 with value: 0.2150432178150902.
Fold 1 IBS: 0.21192565389705484
Fold 2 IBS: 0.22123776935159062

Fold 3 IBS: 0.20237857642828805
Fold 4 IBS: 0.22105646622231043
Fold 5 IBS: 0.21749535106188492
[I 2024-04-20 18:15:48,266] Trial 99 finished with value: 0.21481876339222578 and parameters: {'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 99 with value: 0.21481876339222578.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.21481876339222578], datetime_start=datetime.datetime(2024, 4, 20, 18, 15, 25, 784864), datetime_complete=datetime.datetime(2024, 4, 20, 18, 15, 48, 265093), params={'subsample': 0.8569271041566342, 'learning_rate': 0.01377474153403631, 'dropout_rate': 0.2044520049398774, 'n_estimators': 378, 'criterion': 'squared_error', 'ccp_alpha': 0.004422201299274769, 'min_weight_fraction_leaf': 0.13940114558509004, 'max_features': 'auto', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9580200141092102, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for IBS:
 0.21481876339222578

In [71]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [72]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.745
train_ibs:  0.215

#### Test

In [73]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [74]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03063070291051248,
                                 criterion='squared_error',
                                 dropout_rate=0.2576884847115747,
                                 learning_rate=0.007359366951045268,
                                 max_depth=16, max_features=1,
                                 max_leaf_nodes=16,
                                 min_impurity_decrease=1.3903906488794697e-07,
                                 min_samples_leaf=14, min_samples_split=20,
                                 min_weight_fraction_leaf=0.38180626899357545,
                                 n_estimators=96, random_state=123,
                                 subsample=0.8938290428827321,
                                 validation_fraction=0.9577535215137098)

C-index score: 0.603

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004422201299274769,
                                 criterion='squared_error',
                                 dropout_rate=0.2044520049398774,
                                 learning_rate=0.01377474153403631, max_depth=2,
                                 max_features='auto', max_leaf_nodes=17,
                                 min_impurity_decrease=0.00015837847703956763,
                                 min_samples_leaf=13, min_samples_split=13,
                                 min_weight_fraction_leaf=0.13940114558509004,
                                 n_estimators=378, random_state=123,
                                 subsample=0.8569271041566342,
                                 validation_fraction=0.9580200141092102)

IBS: 0.22

In [75]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [76]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

In [77]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-20 18:15:53,338] A new study created in memory with name: no-name-aa3d9c0c-a182-40ed-be54-7526fc2bdee6

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 18:15:53,932] Trial 0 finished with value: 0.6849872959240584 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6849872959240584.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 18:15:58,493] Trial 1 finished with value: 0.6943010214142545 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6943010214142545.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:15:59,388] Trial 2 finished with value: 0.7047272149390397 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.7047272149390397.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:00,621] Trial 3 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.7370651170158657.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:02,536] Trial 4 finished with value: 0.7394885374772608 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7394885374772608.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 18:16:04,858] Trial 5 finished with value: 0.6747194387812013 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7394885374772608.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 18:16:05,838] Trial 6 finished with value: 0.6218282519980552 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7394885374772608.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:06,039] Trial 7 finished with value: 0.7119313465917007 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7394885374772608.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:07,225] Trial 8 finished with value: 0.7129523231641478 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7394885374772608.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:10,650] Trial 9 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7394885374772608.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-20 18:16:13,007] Trial 10 finished with value: 0.7390281733043629 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 4 with value: 0.7394885374772608.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:16:15,781] Trial 11 finished with value: 0.747792568947383 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.747792568947383.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:16:18,257] Trial 12 finished with value: 0.7510870685654121 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.2495649826842376, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.7510870685654121.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 18:16:21,450] Trial 13 finished with value: 0.679353493107157 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24730256251618668, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.7510870685654121.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6572769953051644
[I 2024-04-20 18:16:24,732] Trial 14 finished with value: 0.7520577769511994 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.24475605651992097, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 14 with value: 0.7520577769511994.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:27,533] Trial 15 finished with value: 0.7256576426337078 and parameters: {'subsample': 0.2913523637503245, 'dropout_rate': 0.7439425643851582, 'n_estimators': 358, 'learning_rate': 0.08616677729964022}. Best is trial 14 with value: 0.7520577769511994.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:16:31,651] Trial 16 finished with value: 0.7361139858624205 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.27752360926296893, 'n_estimators': 427, 'learning_rate': 0.09672186349880336}. Best is trial 14 with value: 0.7520577769511994.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:34,901] Trial 17 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.39930407886471125, 'dropout_rate': 0.6004730897368156, 'n_estimators': 413, 'learning_rate': 0.08485124701632729}. Best is trial 14 with value: 0.7520577769511994.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:16:36,860] Trial 18 finished with value: 0.7447776354419302 and parameters: {'subsample': 0.14033791495138467, 'dropout_rate': 0.33602353085084236, 'n_estimators': 269, 'learning_rate': 0.08436585602805469}. Best is trial 14 with value: 0.7520577769511994.

Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-20 18:16:40,976] Trial 19 finished with value: 0.7413693370425853 and parameters: {'subsample': 0.34314044045637715, 'dropout_rate': 0.1962189134479061, 'n_estimators': 426, 'learning_rate': 0.09857240282031608}. Best is trial 14 with value: 0.7520577769511994.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:16:41,560] Trial 20 finished with value: 0.744563502032525 and parameters: {'subsample': 0.2628688080573812, 'dropout_rate': 0.43503165140528216, 'n_estimators': 112, 'learning_rate': 0.0794193638388259}. Best is trial 14 with value: 0.7520577769511994.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:16:44,163] Trial 21 finished with value: 0.7465173782036517 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.12395834975058428, 'n_estimators': 316, 'learning_rate': 0.08901916938853777}. Best is trial 14 with value: 0.7520577769511994.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 18:16:46,826] Trial 22 finished with value: 0.7529625898399036 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.22548081037710124, 'n_estimators': 323, 'learning_rate': 0.09182714940833918}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:16:48,452] Trial 23 finished with value: 0.7332824044381362 and parameters: {'subsample': 0.20462026465201016, 'dropout_rate': 0.3103238059409247, 'n_estimators': 241, 'learning_rate': 0.09318220603649982}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 18:16:51,252] Trial 24 finished with value: 0.7511383158265008 and parameters: {'subsample': 0.1003062325172735, 'dropout_rate': 0.21211137986888465, 'n_estimators': 337, 'learning_rate': 0.06534143326868806}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:16:54,976] Trial 25 finished with value: 0.7485485531592497 and parameters: {'subsample': 0.21256609796773357, 'dropout_rate': 0.2057291543015094, 'n_estimators': 385, 'learning_rate': 0.0701172941874553}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:16:57,921] Trial 26 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.40408688185102476, 'n_estimators': 344, 'learning_rate': 0.06338755967159565}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 18:17:01,119] Trial 27 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.9861686560685959, 'n_estimators': 448, 'learning_rate': 0.07937285751454146}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:03,269] Trial 28 finished with value: 0.6954134894488435 and parameters: {'subsample': 0.6095590802808257, 'dropout_rate': 0.18804677832052086, 'n_estimators': 283, 'learning_rate': 0.03974539493522584}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 18:17:06,652] Trial 29 finished with value: 0.6690856359642999 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.3396843425042856, 'n_estimators': 402, 'learning_rate': 0.06046208382653473}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:08,274] Trial 30 finished with value: 0.7351324768712003 and parameters: {'subsample': 0.21471077342152511, 'dropout_rate': 0.3605116469704098, 'n_estimators': 237, 'learning_rate': 0.016814619253793885}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:17:11,038] Trial 31 finished with value: 0.7510432305468907 and parameters: {'subsample': 0.10789178747133839, 'dropout_rate': 0.2422241040326975, 'n_estimators': 325, 'learning_rate': 0.09354109144068656}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:17:13,882] Trial 32 finished with value: 0.7366360128550358 and parameters: {'subsample': 0.17102327370382242, 'dropout_rate': 0.28961835044858825, 'n_estimators': 342, 'learning_rate': 0.08043184078527657}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:17:15,944] Trial 33 finished with value: 0.7376370951061181 and parameters: {'subsample': 0.29499990690136635, 'dropout_rate': 0.48095898939081394, 'n_estimators': 294, 'learning_rate': 0.09972240962355879}. Best is trial 22 with value: 0.7529625898399036.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:17:16,750] Trial 34 finished with value: 0.7541296003076832 and parameters: {'subsample': 0.10904393649144295, 'dropout_rate': 0.165569093503576, 'n_estimators': 142, 'learning_rate': 0.07576716957337241}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6173708920187794
[I 2024-04-20 18:17:17,468] Trial 35 finished with value: 0.7344544335668107 and parameters: {'subsample': 0.17223894572098292, 'dropout_rate': 0.16662578465651037, 'n_estimators': 124, 'learning_rate': 0.07548339207401675}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6197183098591549
[I 2024-04-20 18:17:18,213] Trial 36 finished with value: 0.7436245348963747 and parameters: {'subsample': 0.24627386090546444, 'dropout_rate': 0.16914613134643028, 'n_estimators': 136, 'learning_rate': 0.06730087832335879}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.5485232067510548
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 18:17:18,293] Trial 37 finished with value: 0.6169262912137415 and parameters: {'subsample': 0.3118772331268234, 'dropout_rate': 0.20885845524440264, 'n_estimators': 1, 'learning_rate': 0.05621431261796065}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6875

Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:18,701] Trial 38 finished with value: 0.7442644035198804 and parameters: {'subsample': 0.16295147397293233, 'dropout_rate': 0.5110436492508221, 'n_estimators': 82, 'learning_rate': 0.07364542219225001}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:19,634] Trial 39 finished with value: 0.7422160841921494 and parameters: {'subsample': 0.25410451878922247, 'dropout_rate': 0.14050020390445545, 'n_estimators': 159, 'learning_rate': 0.06709978541578802}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:20,855] Trial 40 finished with value: 0.7288400087907576 and parameters: {'subsample': 0.4320845531340142, 'dropout_rate': 0.38797383971882815, 'n_estimators': 206, 'learning_rate': 0.09080176439561004}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:17:23,282] Trial 41 finished with value: 0.747586393266524 and parameters: {'subsample': 0.1076986044852138, 'dropout_rate': 0.23939712080828718, 'n_estimators': 310, 'learning_rate': 0.09460317609924156}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:17:25,073] Trial 42 finished with value: 0.7349263301326949 and parameters: {'subsample': 0.16397191403724043, 'dropout_rate': 0.2841922709451475, 'n_estimators': 258, 'learning_rate': 0.08234632843764163}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:17:28,586] Trial 43 finished with value: 0.7429730059092796 and parameters: {'subsample': 0.13557680519498191, 'dropout_rate': 0.2250108050016534, 'n_estimators': 385, 'learning_rate': 0.08915282554361233}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:17:30,128] Trial 44 finished with value: 0.7478749666935933 and parameters: {'subsample': 0.10226591639783428, 'dropout_rate': 0.15532533153443387, 'n_estimators': 225, 'learning_rate': 0.07448721479222178}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:17:32,982] Trial 45 finished with value: 0.736614093845775 and parameters: {'subsample': 0.22355858337967788, 'dropout_rate': 0.29729835642773106, 'n_estimators': 349, 'learning_rate': 0.08727327651539835}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:35,011] Trial 46 finished with value: 0.7047272149390397 and parameters: {'subsample': 0.5632807984689181, 'dropout_rate': 0.2490912227635968, 'n_estimators': 284, 'learning_rate': 0.04800232009034214}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.5580357142857143
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 18:17:35,924] Trial 47 finished with value: 0.6690856359642999 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.6143459341491552, 'n_estimators': 178, 'learning_rate': 0.07729081283985179}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6525821596244131
[I 2024-04-20 18:17:39,371] Trial 48 finished with value: 0.7431037856235542 and parameters: {'subsample': 0.17804916918292163, 'dropout_rate': 0.11251401802949514, 'n_estimators': 378, 'learning_rate': 0.09509356545922891}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6291079812206573
[I 2024-04-20 18:17:44,143] Trial 49 finished with value: 0.7404072060922132 and parameters: {'subsample': 0.13887945714299843, 'dropout_rate': 0.3343401063734989, 'n_estimators': 477, 'learning_rate': 0.08415807848216121}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:46,592] Trial 50 finished with value: 0.7405283204790691 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.4326780653706334, 'n_estimators': 325, 'learning_rate': 0.07060092688675694}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 18:17:49,304] Trial 51 finished with value: 0.7512967451360842 and parameters: {'subsample': 0.10381515326901168, 'dropout_rate': 0.2630860793168884, 'n_estimators': 332, 'learning_rate': 0.09230235450212092}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-20 18:17:51,832] Trial 52 finished with value: 0.7434717689244291 and parameters: {'subsample': 0.1910565418778623, 'dropout_rate': 0.7442400087777848, 'n_estimators': 364, 'learning_rate': 0.09230844003710723}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:17:53,754] Trial 53 finished with value: 0.7421802328445276 and parameters: {'subsample': 0.14030585556675906, 'dropout_rate': 0.2642698195403201, 'n_estimators': 270, 'learning_rate': 0.09673207935616436}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:17:56,184] Trial 54 finished with value: 0.7461048052343029 and parameters: {'subsample': 0.12942782346544707, 'dropout_rate': 0.18891521344046994, 'n_estimators': 304, 'learning_rate': 0.08881568862741257}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:17:58,789] Trial 55 finished with value: 0.7359982777370011 and parameters: {'subsample': 0.2409700981100993, 'dropout_rate': 0.3188464709816241, 'n_estimators': 329, 'learning_rate': 0.0997126245400615}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:18:02,411] Trial 56 finished with value: 0.7436242395141172 and parameters: {'subsample': 0.19048648469937335, 'dropout_rate': 0.1405502348371697, 'n_estimators': 393, 'learning_rate': 0.05655256625712402}. Best is trial 34 with value: 0.7541296003076832.

Fold 1 C-index: 0.7792207792207793
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 18:18:05,331] Trial 57 finished with value: 0.7530283468676859 and parameters: {'subsample': 0.10151923981488473, 'dropout_rate': 0.37500606397197506, 'n_estimators': 358, 'learning_rate': 0.08545199695884205}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:09,380] Trial 58 finished with value: 0.7449337902230051 and parameters: {'subsample': 0.14979718011191664, 'dropout_rate': 0.36573681723837637, 'n_estimators': 440, 'learning_rate': 0.08234101074930732}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:13,316] Trial 59 finished with value: 0.7493554668338105 and parameters: {'subsample': 0.10171829498369382, 'dropout_rate': 0.2221051682453466, 'n_estimators': 417, 'learning_rate': 0.08607203962441975}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:18:16,224] Trial 60 finished with value: 0.7387528807289458 and parameters: {'subsample': 0.36988898988598745, 'dropout_rate': 0.2684819081113269, 'n_estimators': 353, 'learning_rate': 0.0790818346063833}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6964285714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:19,437] Trial 61 finished with value: 0.7458756226521792 and parameters: {'subsample': 0.1334402749925838, 'dropout_rate': 0.1839727997451115, 'n_estimators': 367, 'learning_rate': 0.09286265251781536}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:18:22,313] Trial 62 finished with value: 0.7449136420885474 and parameters: {'subsample': 0.2706988890900818, 'dropout_rate': 0.10336324660846125, 'n_estimators': 340, 'learning_rate': 0.09643701803227193}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:18:24,691] Trial 63 finished with value: 0.7332824044381362 and parameters: {'subsample': 0.20489552890790902, 'dropout_rate': 0.30778489098320055, 'n_estimators': 315, 'learning_rate': 0.08673263872156274}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:26,898] Trial 64 finished with value: 0.745592327515943 and parameters: {'subsample': 0.1520557177555442, 'dropout_rate': 0.22448196987662236, 'n_estimators': 291, 'learning_rate': 0.062431943149197325}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7878787878787878
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:28,889] Trial 65 finished with value: 0.7462597291140967 and parameters: {'subsample': 0.18711006517646184, 'dropout_rate': 0.26468277359302717, 'n_estimators': 272, 'learning_rate': 0.09108573775604234}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6103286384976526
[I 2024-04-20 18:18:32,217] Trial 66 finished with value: 0.6943010214142545 and parameters: {'subsample': 0.6975136114181246, 'dropout_rate': 0.40252573790618634, 'n_estimators': 398, 'learning_rate': 0.08251335368692411}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 18:18:33,974] Trial 67 finished with value: 0.7475668872550723 and parameters: {'subsample': 0.10279122751098718, 'dropout_rate': 0.20564744822089362, 'n_estimators': 248, 'learning_rate': 0.07738754502200122}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6941964285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:34,364] Trial 68 finished with value: 0.7427051930879485 and parameters: {'subsample': 0.12996054279677136, 'dropout_rate': 0.15423544639505543, 'n_estimators': 77, 'learning_rate': 0.0973447096699738}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:18:36,957] Trial 69 finished with value: 0.736614093845775 and parameters: {'subsample': 0.22428500850162247, 'dropout_rate': 0.3218162823195507, 'n_estimators': 330, 'learning_rate': 0.07169828384382979}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:39,204] Trial 70 finished with value: 0.7412576822654376 and parameters: {'subsample': 0.154131491910291, 'dropout_rate': 0.3563283380973254, 'n_estimators': 305, 'learning_rate': 0.008127880939407618}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:18:41,970] Trial 71 finished with value: 0.7483019084065983 and parameters: {'subsample': 0.1165767431633044, 'dropout_rate': 0.24097681575752686, 'n_estimators': 337, 'learning_rate': 0.09287196532155394}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.647887323943662
[I 2024-04-20 18:18:45,073] Trial 72 finished with value: 0.7496463122356514 and parameters: {'subsample': 0.10280783226592126, 'dropout_rate': 0.17376239636405927, 'n_estimators': 360, 'learning_rate': 0.09087438747878072}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:47,530] Trial 73 finished with value: 0.7427965256508932 and parameters: {'subsample': 0.18122154589697576, 'dropout_rate': 0.2881026298799005, 'n_estimators': 319, 'learning_rate': 0.09619784957707468}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:50,495] Trial 74 finished with value: 0.7517829366709974 and parameters: {'subsample': 0.1254074714599229, 'dropout_rate': 0.20676363441626078, 'n_estimators': 352, 'learning_rate': 0.03471229822615198}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-20 18:18:53,650] Trial 75 finished with value: 0.7439533980661424 and parameters: {'subsample': 0.15532416776661861, 'dropout_rate': 0.20904502496825816, 'n_estimators': 368, 'learning_rate': 0.034467086607900405}. Best is trial 34 with value: 0.7541296003076832.

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:18:56,621] Trial 76 finished with value: 0.735333515284264 and parameters: {'subsample': 0.2742587239497608, 'dropout_rate': 0.14089219590728164, 'n_estimators': 351, 'learning_rate': 0.028744697593665096}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:19:00,467] Trial 77 finished with value: 0.7518848404286591 and parameters: {'subsample': 0.1221112401863356, 'dropout_rate': 0.1252295988995756, 'n_estimators': 405, 'learning_rate': 0.042025913086595354}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6741071428571429
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-20 18:19:04,182] Trial 78 finished with value: 0.7361204192936677 and parameters: {'subsample': 0.23957179565357356, 'dropout_rate': 0.18254528173276074, 'n_estimators': 405, 'learning_rate': 0.04174106130241471}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:19:08,702] Trial 79 finished with value: 0.7441532523964383 and parameters: {'subsample': 0.12599836226663402, 'dropout_rate': 0.13768504571369147, 'n_estimators': 450, 'learning_rate': 0.03671652452957953}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:19:12,707] Trial 80 finished with value: 0.7370651170158657 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.22288901008942827, 'n_estimators': 429, 'learning_rate': 0.046625378484068634}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6291079812206573
[I 2024-04-20 18:19:16,134] Trial 81 finished with value: 0.7472897750000987 and parameters: {'subsample': 0.16529063352896167, 'dropout_rate': 0.12182011971768991, 'n_estimators': 379, 'learning_rate': 0.029435253509323984}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:19:19,591] Trial 82 finished with value: 0.7436093063945621 and parameters: {'subsample': 0.12331964232330386, 'dropout_rate': 0.2526083661100169, 'n_estimators': 388, 'learning_rate': 0.022462845661853945}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6173708920187794
[I 2024-04-20 18:19:22,484] Trial 83 finished with value: 0.7374060255960275 and parameters: {'subsample': 0.20194887749633236, 'dropout_rate': 0.17699150160462546, 'n_estimators': 347, 'learning_rate': 0.05288234891981261}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:19:24,713] Trial 84 finished with value: 0.7403340398218641 and parameters: {'subsample': 0.1438595091769208, 'dropout_rate': 0.2800177120836593, 'n_estimators': 299, 'learning_rate': 0.043574042225613153}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7619047619047619
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:19:28,027] Trial 85 finished with value: 0.7387113884598231 and parameters: {'subsample': 0.16519354904525796, 'dropout_rate': 0.2008032877943135, 'n_estimators': 375, 'learning_rate': 0.037351920577466426}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.5821596244131455
[I 2024-04-20 18:19:30,080] Trial 86 finished with value: 0.6744515323228433 and parameters: {'subsample': 0.992873343787547, 'dropout_rate': 0.15336195765434013, 'n_estimators': 280, 'learning_rate': 0.06613381241597355}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7532467532467533
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:19:30,922] Trial 87 finished with value: 0.7428061197574217 and parameters: {'subsample': 0.10092591193471474, 'dropout_rate': 0.23709784732594058, 'n_estimators': 148, 'learning_rate': 0.088792813037641}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.609375
Fold 3 C-index: 0.7450980392156863
Fold 4 C-index: 0.7848101265822784
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:19:32,051] Trial 88 finished with value: 0.6854567794921336 and parameters: {'subsample': 0.6350482367083102, 'dropout_rate': 0.45494778381644896, 'n_estimators': 197, 'learning_rate': 0.04946826057719945}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7662337662337663
Fold 2 C-index: 0.6919642857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:19:34,825] Trial 89 finished with value: 0.7362212351593257 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.12513357710611214, 'n_estimators': 334, 'learning_rate': 0.08423865173540673}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7748917748917749
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:19:37,888] Trial 90 finished with value: 0.7413087910572258 and parameters: {'subsample': 0.2198762407212527, 'dropout_rate': 0.7211266599729008, 'n_estimators': 407, 'learning_rate': 0.09972238022692363}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6291079812206573
[I 2024-04-20 18:19:40,467] Trial 91 finished with value: 0.7436214031634469 and parameters: {'subsample': 0.1231326533576678, 'dropout_rate': 0.2518308555347318, 'n_estimators': 324, 'learning_rate': 0.09544981020101878}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8382352941176471
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:19:42,919] Trial 92 finished with value: 0.7426824360272967 and parameters: {'subsample': 0.12035213651469226, 'dropout_rate': 0.2986171834733139, 'n_estimators': 309, 'learning_rate': 0.0942450305216496}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6126760563380281
[I 2024-04-20 18:19:43,095] Trial 93 finished with value: 0.7290886525520596 and parameters: {'subsample': 0.14495311875274053, 'dropout_rate': 0.20086295705240273, 'n_estimators': 28, 'learning_rate': 0.05988633822597151}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7705627705627706
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6173708920187794
[I 2024-04-20 18:19:46,321] Trial 94 finished with value: 0.7400149316440624 and parameters: {'subsample': 0.1820077610776279, 'dropout_rate': 0.22924465553173498, 'n_estimators': 363, 'learning_rate': 0.08818707315970555}. Best is trial 34 with value: 0.7541296003076832.

Fold 1 C-index: 0.7489177489177489
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:19:49,348] Trial 95 finished with value: 0.7467879858064881 and parameters: {'subsample': 0.10069940063876269, 'dropout_rate': 0.16283033997038202, 'n_estimators': 342, 'learning_rate': 0.09085026543015035}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7835497835497836
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6244131455399061
[I 2024-04-20 18:19:51,637] Trial 96 finished with value: 0.7438842746453677 and parameters: {'subsample': 0.17339326665749652, 'dropout_rate': 0.26715220734810446, 'n_estimators': 294, 'learning_rate': 0.080819932289942}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7445887445887446
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8143459915611815
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:19:54,660] Trial 97 finished with value: 0.7436531444130838 and parameters: {'subsample': 0.12375486288015465, 'dropout_rate': 0.3355022084524678, 'n_estimators': 353, 'learning_rate': 0.09861314660696283}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6384976525821596
[I 2024-04-20 18:19:56,480] Trial 98 finished with value: 0.7433900357173615 and parameters: {'subsample': 0.148242942967594, 'dropout_rate': 0.5892691543091901, 'n_estimators': 258, 'learning_rate': 0.08602065883625759}. Best is trial 34 with value: 0.7541296003076832.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8312236286919831

[I 2024-04-20 18:19:58,509] A new study created in memory with name: no-name-309e39d1-2fad-4419-91a3-56c88990333a

Fold 5 C-index: 0.647887323943662
[I 2024-04-20 18:19:58,503] Trial 99 finished with value: 0.748562832238359 and parameters: {'subsample': 0.1202744408558634, 'dropout_rate': 0.8459565404966409, 'n_estimators': 321, 'learning_rate': 0.09239045609668788}. Best is trial 34 with value: 0.7541296003076832.


* Best trial for C-index:
 FrozenTrial(number=34, state=TrialState.COMPLETE, values=[0.7541296003076832], datetime_start=datetime.datetime(2024, 4, 20, 18, 17, 15, 947677), datetime_complete=datetime.datetime(2024, 4, 20, 18, 17, 16, 750527), params={'subsample': 0.10904393649144295, 'dropout_rate': 0.165569093503576, 'n_estimators': 142, 'learning_rate': 0.07576716957337241}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=34, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10904393649144295, 'dropout_rate': 0.165569093503576, 'n_estimators': 142, 'learning_rate': 0.07576716957337241}


* Best Score for C-index:
 0.7541296003076832

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.18504584755520848
Fold 2 IBS: 0.263946415780978
Fold 3 IBS: 0.1617903636180167
Fold 4 IBS: 0.2600787216130082
Fold 5 IBS: 0.23318480871469416
[I 2024-04-20 18:19:59,139] Trial 0 finished with value: 0.22080923145638112 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.20370621643796663
Fold 2 IBS: 0.3014080683205247
Fold 3 IBS: 0.17042892249188574
Fold 4 IBS: 0.31585465097929083
Fold 5 IBS: 0.27370157532625616
[I 2024-04-20 18:20:03,884] Trial 1 finished with value: 0.2530198867111848 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.19309554280636426
Fold 2 IBS: 0.30090488415559263
Fold 3 IBS: 0.1653332066108254
Fold 4 IBS: 0.31368208313434126
Fold 5 IBS: 0.26490979029895373
[I 2024-04-20 18:20:04,789] Trial 2 finished with value: 0.24758510140121545 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.19319694714307042
Fold 2 IBS: 0.29867185430046916
Fold 3 IBS: 0.16607224064552437
Fold 4 IBS: 0.31117164271618164
Fold 5 IBS: 0.26803683949365764
[I 2024-04-20 18:20:06,033] Trial 3 finished with value: 0.24742990485978064 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.16913764081029461
Fold 2 IBS: 0.3006292211879915
Fold 3 IBS: 0.18407613385349988
Fold 4 IBS: 0.31302080377224895
Fold 5 IBS: 0.26908387741821566
[I 2024-04-20 18:20:07,917] Trial 4 finished with value: 0.24718953540845012 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.2034038137478441
Fold 2 IBS: 0.3014078956744048
Fold 3 IBS: 0.16987803315182726
Fold 4 IBS: 0.31585217062420684
Fold 5 IBS: 0.27369201709429525
[I 2024-04-20 18:20:10,402] Trial 5 finished with value: 0.2528467860585156 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22080923145638112.
Fold 1 IBS: 0.1829350490073511
Fold 2 IBS: 0.22574908076349612
Fold 3 IBS: 0.16688500534550946
Fold 4 IBS: 0.2247124094692705
Fold 5 IBS: 0.21906832093288123
[I 2024-04-20 18:20:11,547] Trial 6 finished with value: 0.2038699731037017 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2038699731037017.
Fold 1 IBS: 0.19171533392644077
Fold 2 IBS: 0.20303779786155224
Fold 3 IBS: 0.17884668693475606
Fold 4 IBS: 0.20856968304886764
Fold 5 IBS: 0.211118754013436
[I 2024-04-20 18:20:11,834] Trial 7 finished with value: 0.19865765115701053 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18287719589591964
Fold 2 IBS: 0.27502505757765827
Fold 3 IBS: 0.1610534980201046
Fold 4 IBS: 0.26090944510806957
Fold 5 IBS: 0.2349744292756046
[I 2024-04-20 18:20:13,228] Trial 8 finished with value: 0.22296792517547134 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19395518943031972
Fold 2 IBS: 0.3014080117730072
Fold 3 IBS: 0.1827239722426296
Fold 4 IBS: 0.31585254695670684
Fold 5 IBS: 0.2759459715593507
[I 2024-04-20 18:20:16,869] Trial 9 finished with value: 0.2539771383924028 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2133785145028611
Fold 2 IBS: 0.22091211268741265
Fold 3 IBS: 0.20387901759065918
Fold 4 IBS: 0.22439199408788554
Fold 5 IBS: 0.21780913258638765
[I 2024-04-20 18:20:17,039] Trial 10 finished with value: 0.21607415429104124 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2133947249090869
Fold 2 IBS: 0.22105802807283764
Fold 3 IBS: 0.2036691246434108
Fold 4 IBS: 0.2240933715115537
Fold 5 IBS: 0.21777799603810094
[I 2024-04-20 18:20:17,150] Trial 11 finished with value: 0.21599864903499802 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.1800964651509932
Fold 2 IBS: 0.297403850587758
Fold 3 IBS: 0.16597777897100402
Fold 4 IBS: 0.29519467653629033
Fold 5 IBS: 0.25346374715090736
[I 2024-04-20 18:20:17,680] Trial 12 finished with value: 0.23842730367939055 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19280005315897206
Fold 2 IBS: 0.2974213595064474
Fold 3 IBS: 0.17117639615033295
Fold 4 IBS: 0.30578737203308676
Fold 5 IBS: 0.25431185381872007
[I 2024-04-20 18:20:19,760] Trial 13 finished with value: 0.24429940693351188 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19784216344977562
Fold 2 IBS: 0.20506180854560294
Fold 3 IBS: 0.18635045949578385
Fold 4 IBS: 0.21499223626865088
Fold 5 IBS: 0.21149042228501566
[I 2024-04-20 18:20:20,206] Trial 14 finished with value: 0.20314741800896577 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.20999702532392847
Fold 2 IBS: 0.21734365927334173
Fold 3 IBS: 0.20020119375698603
Fold 4 IBS: 0.22202144488912645
Fold 5 IBS: 0.21659611545289936
[I 2024-04-20 18:20:20,563] Trial 15 finished with value: 0.21323188773925641 and parameters: {'subsample': 0.34068078817356096, 'dropout_rate': 0.6312734219618366, 'n_estimators': 71, 'learning_rate': 0.00410045813201973}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.2039212844188623
Fold 2 IBS: 0.2103474992415337
Fold 3 IBS: 0.19339791850328025
Fold 4 IBS: 0.21877297557249897
Fold 5 IBS: 0.21360848363027263
[I 2024-04-20 18:20:20,861] Trial 16 finished with value: 0.20800963227328956 and parameters: {'subsample': 0.6309635677630092, 'dropout_rate': 0.8347953120478615, 'n_estimators': 60, 'learning_rate': 0.013069354206479845}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.18288342929944057
Fold 2 IBS: 0.23926430161132384
Fold 3 IBS: 0.16665249308120655
Fold 4 IBS: 0.2362841280803267
Fold 5 IBS: 0.22353483274970617
[I 2024-04-20 18:20:21,493] Trial 17 finished with value: 0.20972383696440078 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 127, 'learning_rate': 0.03899652081277748}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.1773954201959245
Fold 2 IBS: 0.24024111720982294
Fold 3 IBS: 0.16255955996419777
Fold 4 IBS: 0.22670032118705843
Fold 5 IBS: 0.22295397631420336
[I 2024-04-20 18:20:23,776] Trial 18 finished with value: 0.2059700789742414 and parameters: {'subsample': 0.38613533952764606, 'dropout_rate': 0.7804104087034108, 'n_estimators': 336, 'learning_rate': 0.015594655416145919}. Best is trial 7 with value: 0.19865765115701053.
Fold 1 IBS: 0.19017638997629102
Fold 2 IBS: 0.2023431594465361
Fold 3 IBS: 0.1783999568257794

Fold 4 IBS: 0.2017180216457497
Fold 5 IBS: 0.2127622739815413
[I 2024-04-20 18:20:24,057] Trial 19 finished with value: 0.19707996037517952 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9930703343219778, 'n_estimators': 51, 'learning_rate': 0.04096883532946153}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.18844165738979637
Fold 2 IBS: 0.20472965504337676
Fold 3 IBS: 0.1819421294378562
Fold 4 IBS: 0.20465119827707254
Fold 5 IBS: 0.21298081915188694
[I 2024-04-20 18:20:24,312] Trial 20 finished with value: 0.19854909185999775 and parameters: {'subsample': 0.1435040576337751, 'dropout_rate': 0.7933084651006226, 'n_estimators': 43, 'learning_rate': 0.04127909023805986}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.19558104368646592
Fold 2 IBS: 0.20382011576839348
Fold 3 IBS: 0.18712698518091442
Fold 4 IBS: 0.20944879242499856
Fold 5 IBS: 0.21303933620208118
[I 2024-04-20 18:20:24,522] Trial 21 finished with value: 0.2018032546525707 and parameters: {'subsample': 0.11437919910307487, 'dropout_rate': 0.9754161103921428, 'n_estimators': 33, 'learning_rate': 0.042594274103339054}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.21319234752616703
Fold 2 IBS: 0.22073279019144837
Fold 3 IBS: 0.20313821183683503
Fold 4 IBS: 0.22386245547893124
Fold 5 IBS: 0.2175077980822652
[I 2024-04-20 18:20:24,632] Trial 22 finished with value: 0.21568672062312938 and parameters: {'subsample': 0.21143341146838185, 'dropout_rate': 0.9783239843444622, 'n_estimators': 2, 'learning_rate': 0.04261938215005666}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.1593548202119343
Fold 2 IBS: 0.23421543573086082
Fold 3 IBS: 0.16544541971054122
Fold 4 IBS: 0.2251103358325982
Fold 5 IBS: 0.22623410400791188
[I 2024-04-20 18:20:25,382] Trial 23 finished with value: 0.2020720230987693 and parameters: {'subsample': 0.19369753798035044, 'dropout_rate': 0.7930385598318731, 'n_estimators': 146, 'learning_rate': 0.0396495042605266}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.1848253360970415
Fold 2 IBS: 0.2124184957753865
Fold 3 IBS: 0.16839399220873313
Fold 4 IBS: 0.21192615623352185
Fold 5 IBS: 0.21327382867550682
[I 2024-04-20 18:20:25,667] Trial 24 finished with value: 0.19816756179803793 and parameters: {'subsample': 0.3980179643829882, 'dropout_rate': 0.9047292366273245, 'n_estimators': 56, 'learning_rate': 0.06234977614697124}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.15782951477876914
Fold 2 IBS: 0.24219622203257674
Fold 3 IBS: 0.16256464789472305
Fold 4 IBS: 0.23662630802467657
Fold 5 IBS: 0.22681115607844332
[I 2024-04-20 18:20:26,036] Trial 25 finished with value: 0.20520556976183774 and parameters: {'subsample': 0.2217965007715769, 'dropout_rate': 0.9319520966822452, 'n_estimators': 72, 'learning_rate': 0.08579428551722094}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.15544600643780843
Fold 2 IBS: 0.2647410132018659
Fold 3 IBS: 0.16952773223655743
Fold 4 IBS: 0.25154354453905636
Fold 5 IBS: 0.24849398597500735
[I 2024-04-20 18:20:26,803] Trial 26 finished with value: 0.21795045647805908 and parameters: {'subsample': 0.10665946004649053, 'dropout_rate': 0.89397617546164, 'n_estimators': 150, 'learning_rate': 0.06722393082067463}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.18839464619446405
Fold 2 IBS: 0.30140803928325294
Fold 3 IBS: 0.22433072883146754
Fold 4 IBS: 0.31585395754581636
Fold 5 IBS: 0.2797698955233327
[I 2024-04-20 18:20:29,607] Trial 27 finished with value: 0.26195145347566673 and parameters: {'subsample': 0.4014627938715816, 'dropout_rate': 0.9861686560685959, 'n_estimators': 422, 'learning_rate': 0.06071884280131438}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.17733461424898764
Fold 2 IBS: 0.30118368099824544
Fold 3 IBS: 0.18513777511883225
Fold 4 IBS: 0.31445075733845274
Fold 5 IBS: 0.2716451561242865
[I 2024-04-20 18:20:30,969] Trial 28 finished with value: 0.2499503967657609 and parameters: {'subsample': 0.301636198347479, 'dropout_rate': 0.7753950220583815, 'n_estimators': 236, 'learning_rate': 0.06152638329235058}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.15760672643659537
Fold 2 IBS: 0.27846903119481997
Fold 3 IBS: 0.17213035309959698
Fold 4 IBS: 0.2539880026469853
Fold 5 IBS: 0.2452014901267099
[I 2024-04-20 18:20:31,474] Trial 29 finished with value: 0.2214791207009415 and parameters: {'subsample': 0.17398784645198978, 'dropout_rate': 0.8349232147406402, 'n_estimators': 104, 'learning_rate': 0.08423642007181871}. Best is trial 19 with value: 0.19707996037517952.
Fold 1 IBS: 0.17445409555074234
Fold 2 IBS: 0.2151565488706753
Fold 3 IBS: 0.16669819924456905
Fold 4 IBS: 0.20817345718891475
Fold 5 IBS: 0.2152415677746221
[I 2024-04-20 18:20:31,878] Trial 30 finished with value: 0.19594477372590474 and parameters: {'subsample': 0.2381729579870052, 'dropout_rate': 0.9172391219359199, 'n_estimators': 82, 'learning_rate': 0.0483156944073118}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.1740208764857199
Fold 2 IBS: 0.22025554342589576
Fold 3 IBS: 0.1652689721096754
Fold 4 IBS: 0.21461975112376203
Fold 5 IBS: 0.2171510836061579
[I 2024-04-20 18:20:32,280] Trial 31 finished with value: 0.1982632453502422 and parameters: {'subsample': 0.2464163054601055, 'dropout_rate': 0.9271779254835972, 'n_estimators': 86, 'learning_rate': 0.04992642229657319}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.16992243256545633
Fold 2 IBS: 0.2547310774727292
Fold 3 IBS: 0.16316330053037192
Fold 4 IBS: 0.25196509736947087
Fold 5 IBS: 0.2308172007465473
[I 2024-04-20 18:20:32,875] Trial 32 finished with value: 0.21411982173691513 and parameters: {'subsample': 0.24679846818428344, 'dropout_rate': 0.9480531765532226, 'n_estimators': 129, 'learning_rate': 0.049309899563523385}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.17848705131694004
Fold 2 IBS: 0.23321850467354452
Fold 3 IBS: 0.16319852386981645
Fold 4 IBS: 0.22262857181662868
Fold 5 IBS: 0.22049811308495956
[I 2024-04-20 18:20:33,266] Trial 33 finished with value: 0.20360615295237783 and parameters: {'subsample': 0.42833421982844316, 'dropout_rate': 0.906441247519853, 'n_estimators': 84, 'learning_rate': 0.056987153621534996}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.1642762275903523
Fold 2 IBS: 0.2806746771173498
Fold 3 IBS: 0.16934743929847906
Fold 4 IBS: 0.27559620938851886
Fold 5 IBS: 0.24182314885255943
[I 2024-04-20 18:20:34,137] Trial 34 finished with value: 0.2263435404494519 and parameters: {'subsample': 0.25579443215975756, 'dropout_rate': 0.8350558435468665, 'n_estimators': 171, 'learning_rate': 0.04823191358053747}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.19115300176695646
Fold 2 IBS: 0.2031631168773369
Fold 3 IBS: 0.18087340046201708
Fold 4 IBS: 0.20788519828061772
Fold 5 IBS: 0.21287267911359212
[I 2024-04-20 18:20:34,314] Trial 35 finished with value: 0.19918947930010406 and parameters: {'subsample': 0.29314602479486707, 'dropout_rate': 0.9999658564779634, 'n_estimators': 26, 'learning_rate': 0.06920924038817856}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.17935029536671768
Fold 2 IBS: 0.2798133275191118
Fold 3 IBS: 0.16138201658108425
Fold 4 IBS: 0.277856543310019
Fold 5 IBS: 0.24341238821271485
[I 2024-04-20 18:20:34,913] Trial 36 finished with value: 0.22836291419792953 and parameters: {'subsample': 0.4392643760586835, 'dropout_rate': 0.24408912236765595, 'n_estimators': 113, 'learning_rate': 0.07650775910789946}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.18802170117548192
Fold 2 IBS: 0.29447369912211585
Fold 3 IBS: 0.16266230787828062
Fold 4 IBS: 0.29458389650118244
Fold 5 IBS: 0.24838156146814955
[I 2024-04-20 18:20:35,646] Trial 37 finished with value: 0.23762463322904206 and parameters: {'subsample': 0.5507574128502895, 'dropout_rate': 0.8608568379956052, 'n_estimators': 155, 'learning_rate': 0.05621431261796065}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.15739016878369946
Fold 2 IBS: 0.24738726785230314
Fold 3 IBS: 0.1675187073192873
Fold 4 IBS: 0.23165212259169163

Fold 5 IBS: 0.2332838201025736
[I 2024-04-20 18:20:36,654] Trial 38 finished with value: 0.20744641732991104 and parameters: {'subsample': 0.1710779175611994, 'dropout_rate': 0.9288534916051375, 'n_estimators': 197, 'learning_rate': 0.036023800474466655}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.1876140504745091
Fold 2 IBS: 0.20563381823568802
Fold 3 IBS: 0.17202903977012926
Fold 4 IBS: 0.2067894022485534
Fold 5 IBS: 0.21264550977192898
[I 2024-04-20 18:20:36,948] Trial 39 finished with value: 0.19694236410016178 and parameters: {'subsample': 0.3537909584345821, 'dropout_rate': 0.8744094300062906, 'n_estimators': 59, 'learning_rate': 0.04711870419619728}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.18448495606229867
Fold 2 IBS: 0.2155619099375562
Fold 3 IBS: 0.16824012001923247
Fold 4 IBS: 0.21346674211873537
Fold 5 IBS: 0.21402742087944407
[I 2024-04-20 18:20:37,223] Trial 40 finished with value: 0.19915622980345335 and parameters: {'subsample': 0.5732763428296245, 'dropout_rate': 0.7404989505064663, 'n_estimators': 54, 'learning_rate': 0.06660232733235426}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.17781363182607124
Fold 2 IBS: 0.22058844209659448
Fold 3 IBS: 0.16475547422493897
Fold 4 IBS: 0.2110634058418947
Fold 5 IBS: 0.2168150295367869
[I 2024-04-20 18:20:37,639] Trial 41 finished with value: 0.19820719670525724 and parameters: {'subsample': 0.34578757734799925, 'dropout_rate': 0.8788853441122854, 'n_estimators': 88, 'learning_rate': 0.04884047076787994}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.19934378150393145
Fold 2 IBS: 0.20617849037504465
Fold 3 IBS: 0.18774021509648142
Fold 4 IBS: 0.2147474654986803
Fold 5 IBS: 0.21293011575902263
[I 2024-04-20 18:20:37,814] Trial 42 finished with value: 0.20418801364663208 and parameters: {'subsample': 0.33789987815376404, 'dropout_rate': 0.8931341216565075, 'n_estimators': 23, 'learning_rate': 0.053894376446114514}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.18421572142692189
Fold 2 IBS: 0.21736385138879288
Fold 3 IBS: 0.16616190015704765
Fold 4 IBS: 0.21550013923018563
Fold 5 IBS: 0.21436791137771027
[I 2024-04-20 18:20:38,126] Trial 43 finished with value: 0.19952190471613168 and parameters: {'subsample': 0.4717598415162009, 'dropout_rate': 0.8680039169028084, 'n_estimators': 62, 'learning_rate': 0.05991231847439593}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.17539665412153915
Fold 2 IBS: 0.25381664475540106
Fold 3 IBS: 0.1619572164973234
Fold 4 IBS: 0.23626024469184084
Fold 5 IBS: 0.22868290366690983
[I 2024-04-20 18:20:38,821] Trial 44 finished with value: 0.21122273274660283 and parameters: {'subsample': 0.36128738430802604, 'dropout_rate': 0.5057702042743903, 'n_estimators': 130, 'learning_rate': 0.04652228012350071}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.20613463001830643
Fold 2 IBS: 0.21473355306575914
Fold 3 IBS: 0.19696939756848034
Fold 4 IBS: 0.21874826917004528
Fold 5 IBS: 0.21482113981948242
[I 2024-04-20 18:20:38,977] Trial 45 finished with value: 0.21028139792841474 and parameters: {'subsample': 0.2970668004862915, 'dropout_rate': 0.9580002968235438, 'n_estimators': 15, 'learning_rate': 0.03400538573985265}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.18897693890389555
Fold 2 IBS: 0.20370655370424656
Fold 3 IBS: 0.17722251041165302
Fold 4 IBS: 0.20953413853445993
Fold 5 IBS: 0.21135257825095138
[I 2024-04-20 18:20:39,399] Trial 46 finished with value: 0.1981585439610413 and parameters: {'subsample': 0.4307326273437892, 'dropout_rate': 0.8662614128615587, 'n_estimators': 91, 'learning_rate': 0.024992652172925307}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.20071819295605858
Fold 2 IBS: 0.2086370761903522
Fold 3 IBS: 0.1904492084139519
Fold 4 IBS: 0.21575539811202984
Fold 5 IBS: 0.21321105137650911
[I 2024-04-20 18:20:39,652] Trial 47 finished with value: 0.20575418540978033 and parameters: {'subsample': 0.5154202245870623, 'dropout_rate': 0.1240463473883398, 'n_estimators': 45, 'learning_rate': 0.023064794253730755}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.18048095982061635
Fold 2 IBS: 0.27262037995538513
Fold 3 IBS: 0.16097222600974445
Fold 4 IBS: 0.26356669635519725
Fold 5 IBS: 0.2346987328575458
[I 2024-04-20 18:20:41,073] Trial 48 finished with value: 0.2224677989996978 and parameters: {'subsample': 0.44240771735087686, 'dropout_rate': 0.8146600917967612, 'n_estimators': 248, 'learning_rate': 0.027044032224784076}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.18622697726531617
Fold 2 IBS: 0.20908058542212124
Fold 3 IBS: 0.17211482996183064
Fold 4 IBS: 0.21230414733090214
Fold 5 IBS: 0.2122281184103048
[I 2024-04-20 18:20:41,598] Trial 49 finished with value: 0.19839093167809502 and parameters: {'subsample': 0.6192069938222724, 'dropout_rate': 0.7271924315071985, 'n_estimators': 108, 'learning_rate': 0.02713079119975165}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.19550920546936468
Fold 2 IBS: 0.2037003767996933
Fold 3 IBS: 0.18432731614014047
Fold 4 IBS: 0.212376370905737
Fold 5 IBS: 0.21187299127420448
[I 2024-04-20 18:20:41,956] Trial 50 finished with value: 0.201557252117828 and parameters: {'subsample': 0.42222123825287444, 'dropout_rate': 0.6843290787742734, 'n_estimators': 72, 'learning_rate': 0.021363342350747383}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.1794600896917236
Fold 2 IBS: 0.22659761438995338
Fold 3 IBS: 0.1640761174187251
Fold 4 IBS: 0.2146280369395022
Fold 5 IBS: 0.21799604842142337
[I 2024-04-20 18:20:42,383] Trial 51 finished with value: 0.2005515813722655 and parameters: {'subsample': 0.3815255992575082, 'dropout_rate': 0.8803510576670203, 'n_estimators': 84, 'learning_rate': 0.05293830590274953}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.1900696466121789
Fold 2 IBS: 0.20266890508091306
Fold 3 IBS: 0.17679359544219617
Fold 4 IBS: 0.20816897343639296
Fold 5 IBS: 0.211695434354964
[I 2024-04-20 18:20:42,644] Trial 52 finished with value: 0.19787931098532902 and parameters: {'subsample': 0.3455946574392862, 'dropout_rate': 0.856113989682693, 'n_estimators': 49, 'learning_rate': 0.04652943750756749}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.18911731395783155
Fold 2 IBS: 0.20443523655436316
Fold 3 IBS: 0.17622135117863388
Fold 4 IBS: 0.20991490347987604
Fold 5 IBS: 0.21109130258008857
[I 2024-04-20 18:20:42,918] Trial 53 finished with value: 0.19815602155015866 and parameters: {'subsample': 0.4762788816560454, 'dropout_rate': 0.9385939481808312, 'n_estimators': 50, 'learning_rate': 0.04558051262695099}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.19694023473217756
Fold 2 IBS: 0.20505243224752875
Fold 3 IBS: 0.1858092435952595
Fold 4 IBS: 0.2137729836807142
Fold 5 IBS: 0.21206622874303588
[I 2024-04-20 18:20:43,136] Trial 54 finished with value: 0.20272822459974318 and parameters: {'subsample': 0.4782217418644513, 'dropout_rate': 0.9509150296349711, 'n_estimators': 37, 'learning_rate': 0.03727579170963399}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.21341121907065255
Fold 2 IBS: 0.22096269082327033
Fold 3 IBS: 0.20378224032590944
Fold 4 IBS: 0.22438363532649475
Fold 5 IBS: 0.21769864168746642
[I 2024-04-20 18:20:43,245] Trial 55 finished with value: 0.2160476854467587 and parameters: {'subsample': 0.7256048258456533, 'dropout_rate': 0.8378164810986685, 'n_estimators': 1, 'learning_rate': 0.044094398715112365}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.20397199032894792
Fold 2 IBS: 0.21333179025694868
Fold 3 IBS: 0.19601933314081957
Fold 4 IBS: 0.21783865017482698
Fold 5 IBS: 0.21523864792857939
[I 2024-04-20 18:20:43,401] Trial 56 finished with value: 0.2092800823660245 and parameters: {'subsample': 0.27433038550604805, 'dropout_rate': 0.7483350749905161, 'n_estimators': 19, 'learning_rate': 0.03223361260912044}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.17797518141236637
Fold 2 IBS: 0.30095875442079584
Fold 3 IBS: 0.17328317089014492
Fold 4 IBS: 0.31394529707721386

Fold 5 IBS: 0.2667682961494491
[I 2024-04-20 18:20:44,949] Trial 57 finished with value: 0.246586139989994 and parameters: {'subsample': 0.32826887806420246, 'dropout_rate': 0.9933561701936838, 'n_estimators': 283, 'learning_rate': 0.046115905841529976}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.20860918635569756
Fold 2 IBS: 0.21590342208816954
Fold 3 IBS: 0.19882549664838997
Fold 4 IBS: 0.22138259267967494
Fold 5 IBS: 0.21576315984193745
[I 2024-04-20 18:20:45,195] Trial 58 finished with value: 0.2120967715227739 and parameters: {'subsample': 0.5286310530837229, 'dropout_rate': 0.922313337459929, 'n_estimators': 41, 'learning_rate': 0.009368892992001188}. Best is trial 30 with value: 0.19594477372590474.
Fold 1 IBS: 0.16721506156919788
Fold 2 IBS: 0.20811485477202274
Fold 3 IBS: 0.1673944010677237
Fold 4 IBS: 0.19470174832450804
Fold 5 IBS: 0.2186581694007046
[I 2024-04-20 18:20:45,677] Trial 59 finished with value: 0.1912168470268314 and parameters: {'subsample': 0.14522006252948272, 'dropout_rate': 0.8084628917187764, 'n_estimators': 98, 'learning_rate': 0.04113440174073067}. Best is trial 59 with value: 0.1912168470268314.
Fold 1 IBS: 0.1612636162827836
Fold 2 IBS: 0.2140305568481367
Fold 3 IBS: 0.16775823930082936
Fold 4 IBS: 0.20203813270770588
Fold 5 IBS: 0.2226271677744071
[I 2024-04-20 18:20:46,271] Trial 60 finished with value: 0.1935435425827725 and parameters: {'subsample': 0.1375263612764897, 'dropout_rate': 0.9630819399302621, 'n_estimators': 126, 'learning_rate': 0.038980835478226394}. Best is trial 59 with value: 0.1912168470268314.
Fold 1 IBS: 0.16321765167190336
Fold 2 IBS: 0.21604842080500358
Fold 3 IBS: 0.16652407334684136
Fold 4 IBS: 0.20419359862595282
Fold 5 IBS: 0.2229048849127981
[I 2024-04-20 18:20:46,880] Trial 61 finished with value: 0.19457772587249983 and parameters: {'subsample': 0.1453463480776829, 'dropout_rate': 0.953864668987802, 'n_estimators': 127, 'learning_rate': 0.039832085240492705}. Best is trial 59 with value: 0.1912168470268314.
Fold 1 IBS: 0.16159209118127674
Fold 2 IBS: 0.2133381355589709
Fold 3 IBS: 0.16783749798195502
Fold 4 IBS: 0.20199642471324455
Fold 5 IBS: 0.2221523908949394
[I 2024-04-20 18:20:47,455] Trial 62 finished with value: 0.19338330806607734 and parameters: {'subsample': 0.14066257057329762, 'dropout_rate': 0.9632873028037965, 'n_estimators': 123, 'learning_rate': 0.03896306944108657}. Best is trial 59 with value: 0.1912168470268314.
Fold 1 IBS: 0.15428851643412103
Fold 2 IBS: 0.24721195035896862
Fold 3 IBS: 0.16765148414529102
Fold 4 IBS: 0.23096735188605222
Fold 5 IBS: 0.23612091027808027
[I 2024-04-20 18:20:48,388] Trial 63 finished with value: 0.20724804262050264 and parameters: {'subsample': 0.1426549697589047, 'dropout_rate': 0.9638280829839427, 'n_estimators': 188, 'learning_rate': 0.03969772372560614}. Best is trial 59 with value: 0.1912168470268314.
Fold 1 IBS: 0.1692314899416431
Fold 2 IBS: 0.2058008060721199
Fold 3 IBS: 0.16813246046555533
Fold 4 IBS: 0.19248544465964873
Fold 5 IBS: 0.21791794338447737
[I 2024-04-20 18:20:49,016] Trial 64 finished with value: 0.19071362890468885 and parameters: {'subsample': 0.106249473229961, 'dropout_rate': 0.9681316166382135, 'n_estimators': 131, 'learning_rate': 0.030226818337871844}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.16155433589895737
Fold 2 IBS: 0.2276108578708714
Fold 3 IBS: 0.1671309055173858
Fold 4 IBS: 0.21248101352093424
Fold 5 IBS: 0.22596839459009607
[I 2024-04-20 18:20:49,823] Trial 65 finished with value: 0.198949101479649 and parameters: {'subsample': 0.16933962095750288, 'dropout_rate': 0.963417150597045, 'n_estimators': 165, 'learning_rate': 0.03499600145878021}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.16870203348164428
Fold 2 IBS: 0.21162627354432478
Fold 3 IBS: 0.1672381354515126
Fold 4 IBS: 0.2087911087911822
Fold 5 IBS: 0.21661146458355962
[I 2024-04-20 18:20:50,493] Trial 66 finished with value: 0.1945938031704447 and parameters: {'subsample': 0.21214075898846796, 'dropout_rate': 0.9114369008420854, 'n_estimators': 141, 'learning_rate': 0.02868628998342892}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.15667744937766775
Fold 2 IBS: 0.22821071523139605
Fold 3 IBS: 0.1653628692043195
Fold 4 IBS: 0.20745929651725395
Fold 5 IBS: 0.23250501069196947
[I 2024-04-20 18:20:51,733] Trial 67 finished with value: 0.19804306820452136 and parameters: {'subsample': 0.12944030900429873, 'dropout_rate': 0.8097848452066606, 'n_estimators': 223, 'learning_rate': 0.03039794068880892}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.16832967777736196
Fold 2 IBS: 0.21098919335941246
Fold 3 IBS: 0.16728824594509742
Fold 4 IBS: 0.20894174842734062
Fold 5 IBS: 0.2163598855348881
[I 2024-04-20 18:20:52,399] Trial 68 finished with value: 0.1943817502088201 and parameters: {'subsample': 0.20186557071072295, 'dropout_rate': 0.9075490354548498, 'n_estimators': 137, 'learning_rate': 0.02915774415326921}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.18389707392455742
Fold 2 IBS: 0.2030474388663031
Fold 3 IBS: 0.17646293823442846
Fold 4 IBS: 0.20310053486731525
Fold 5 IBS: 0.21228161314265273
[I 2024-04-20 18:20:53,094] Trial 69 finished with value: 0.1957579198070514 and parameters: {'subsample': 0.2003202269366354, 'dropout_rate': 0.4356182142942594, 'n_estimators': 128, 'learning_rate': 0.019042871107947605}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.16875950337458784
Fold 2 IBS: 0.20830712521559458
Fold 3 IBS: 0.16935221320708793
Fold 4 IBS: 0.198430146352412
Fold 5 IBS: 0.21769664850412884
[I 2024-04-20 18:20:53,866] Trial 70 finished with value: 0.19250912733076225 and parameters: {'subsample': 0.1637427728527268, 'dropout_rate': 0.2890660362121499, 'n_estimators': 137, 'learning_rate': 0.029918818967291316}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.16997096496546987
Fold 2 IBS: 0.21072241873732198
Fold 3 IBS: 0.16750204474652988
Fold 4 IBS: 0.1977995709463947
Fold 5 IBS: 0.21748319883147935
[I 2024-04-20 18:20:54,680] Trial 71 finished with value: 0.19269563964543915 and parameters: {'subsample': 0.15895507393448402, 'dropout_rate': 0.3725784472845077, 'n_estimators': 142, 'learning_rate': 0.030215889981265856}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.16123049919539334
Fold 2 IBS: 0.2275049534514765
Fold 3 IBS: 0.16504091268478951
Fold 4 IBS: 0.20961497892686098
Fold 5 IBS: 0.2270179087463806
[I 2024-04-20 18:20:55,819] Trial 72 finished with value: 0.19808185060098019 and parameters: {'subsample': 0.1577049630965842, 'dropout_rate': 0.30876052527758674, 'n_estimators': 183, 'learning_rate': 0.03316907323369759}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.17180127681257082
Fold 2 IBS: 0.20074154318360177
Fold 3 IBS: 0.1744794596052511
Fold 4 IBS: 0.1974569122351379
Fold 5 IBS: 0.2140198545893546
[I 2024-04-20 18:20:56,811] Trial 73 finished with value: 0.19169980928518324 and parameters: {'subsample': 0.12016400841359953, 'dropout_rate': 0.20007644097106334, 'n_estimators': 161, 'learning_rate': 0.018186189980061628}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.19000576666611715
Fold 2 IBS: 0.20668649441109896
Fold 3 IBS: 0.18491190471638902
Fold 4 IBS: 0.20797329583988994
Fold 5 IBS: 0.21406997738838074
[I 2024-04-20 18:20:57,768] Trial 74 finished with value: 0.20072948780437513 and parameters: {'subsample': 0.1013565464030951, 'dropout_rate': 0.19663897957264692, 'n_estimators': 158, 'learning_rate': 0.009965879328126922}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.17727063614513205
Fold 2 IBS: 0.20316703577189085
Fold 3 IBS: 0.174239302593361
Fold 4 IBS: 0.19880099275474378
Fold 5 IBS: 0.21419383770694314
[I 2024-04-20 18:20:58,572] Trial 75 finished with value: 0.19353436099441418 and parameters: {'subsample': 0.18878169638443246, 'dropout_rate': 0.34163132072065266, 'n_estimators': 142, 'learning_rate': 0.02008974598166402}. Best is trial 64 with value: 0.19071362890468885.
Fold 1 IBS: 0.1682555378195436
Fold 2 IBS: 0.20243934651494552
Fold 3 IBS: 0.17089496863262907
Fold 4 IBS: 0.19419403325916945

Fold 5 IBS: 0.21640786738462428
[I 2024-04-20 18:20:59,986] Trial 76 finished with value: 0.1904383507221824 and parameters: {'subsample': 0.12400746444313113, 'dropout_rate': 0.3383709467175438, 'n_estimators': 215, 'learning_rate': 0.017149355016391896}. Best is trial 76 with value: 0.1904383507221824.
Fold 1 IBS: 0.1724380363374518
Fold 2 IBS: 0.20474762692041973
Fold 3 IBS: 0.1715063350229059
Fold 4 IBS: 0.19856558172691882
Fold 5 IBS: 0.2145540355925452
[I 2024-04-20 18:21:01,344] Trial 77 finished with value: 0.19236232312004828 and parameters: {'subsample': 0.17633990236538394, 'dropout_rate': 0.3283434771119012, 'n_estimators': 211, 'learning_rate': 0.015746054804451973}. Best is trial 76 with value: 0.1904383507221824.
Fold 1 IBS: 0.16981201583729438
Fold 2 IBS: 0.2017243145055686
Fold 3 IBS: 0.17165846403202692
Fold 4 IBS: 0.1944387983912983
Fold 5 IBS: 0.21589811641276688
[I 2024-04-20 18:21:02,720] Trial 78 finished with value: 0.19070634183579102 and parameters: {'subsample': 0.12079073184691407, 'dropout_rate': 0.2859631694115592, 'n_estimators': 212, 'learning_rate': 0.016501983022687235}. Best is trial 76 with value: 0.1904383507221824.
Fold 1 IBS: 0.17146474372075513
Fold 2 IBS: 0.20227940806489275
Fold 3 IBS: 0.1700065260766544
Fold 4 IBS: 0.19266457368279513
Fold 5 IBS: 0.215511057451677
[I 2024-04-20 18:21:04,043] Trial 79 finished with value: 0.19038526179935486 and parameters: {'subsample': 0.11978301660338266, 'dropout_rate': 0.23488007347076334, 'n_estimators': 205, 'learning_rate': 0.01644821231294548}. Best is trial 79 with value: 0.19038526179935486.
Fold 1 IBS: 0.16602892946414088
Fold 2 IBS: 0.20283500507788696
Fold 3 IBS: 0.16973396242863237
Fold 4 IBS: 0.19328430189563298
Fold 5 IBS: 0.2172395225207836
[I 2024-04-20 18:21:05,528] Trial 80 finished with value: 0.18982434427741535 and parameters: {'subsample': 0.1153928313338253, 'dropout_rate': 0.2802037422867093, 'n_estimators': 224, 'learning_rate': 0.017466484191523204}. Best is trial 80 with value: 0.18982434427741535.
Fold 1 IBS: 0.16988710387795963
Fold 2 IBS: 0.20118006339820546
Fold 3 IBS: 0.17132830674428873
Fold 4 IBS: 0.19434960884603605
Fold 5 IBS: 0.2159036994897413
[I 2024-04-20 18:21:06,917] Trial 81 finished with value: 0.1905297564712462 and parameters: {'subsample': 0.11711251603055826, 'dropout_rate': 0.2663973672273696, 'n_estimators': 208, 'learning_rate': 0.016919292800236865}. Best is trial 80 with value: 0.18982434427741535.
Fold 1 IBS: 0.16748118714081048
Fold 2 IBS: 0.20433299310725153
Fold 3 IBS: 0.16810008688331957
Fold 4 IBS: 0.1892141764171736
Fold 5 IBS: 0.21750141255616914
[I 2024-04-20 18:21:08,473] Trial 82 finished with value: 0.18932597122094488 and parameters: {'subsample': 0.11263052409999037, 'dropout_rate': 0.20981564910049627, 'n_estimators': 226, 'learning_rate': 0.017066518914446174}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.1871736943822292
Fold 2 IBS: 0.20345016724631107
Fold 3 IBS: 0.1816790144176308
Fold 4 IBS: 0.20348865554951306
Fold 5 IBS: 0.21406181944621056
[I 2024-04-20 18:21:10,370] Trial 83 finished with value: 0.1979706702083789 and parameters: {'subsample': 0.11656736381829241, 'dropout_rate': 0.21832295577025101, 'n_estimators': 261, 'learning_rate': 0.007256398389496111}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.17396312629997165
Fold 2 IBS: 0.20071499889948752
Fold 3 IBS: 0.1755673416332102
Fold 4 IBS: 0.1994089959391925
Fold 5 IBS: 0.21434233463033972
[I 2024-04-20 18:21:11,970] Trial 84 finished with value: 0.1927993594804403 and parameters: {'subsample': 0.11795939138617319, 'dropout_rate': 0.16733657152463624, 'n_estimators': 230, 'learning_rate': 0.011822581786269833}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.20130901400858012
Fold 2 IBS: 0.21156761075547575
Fold 3 IBS: 0.19228175738245856
Fold 4 IBS: 0.21409225910099375
Fold 5 IBS: 0.21473529298867494
[I 2024-04-20 18:21:13,254] Trial 85 finished with value: 0.2067971868472366 and parameters: {'subsample': 0.1027225441710333, 'dropout_rate': 0.2622992461767584, 'n_estimators': 198, 'learning_rate': 0.004551338424183234}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.16932941355202585
Fold 2 IBS: 0.21426682496134908
Fold 3 IBS: 0.1673552094283941
Fold 4 IBS: 0.2056470047745174
Fold 5 IBS: 0.2171369542293843
[I 2024-04-20 18:21:15,040] Trial 86 finished with value: 0.19474708138913413 and parameters: {'subsample': 0.22646017600913904, 'dropout_rate': 0.26609786437382627, 'n_estimators': 247, 'learning_rate': 0.016659923083370512}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.17880619721898977
Fold 2 IBS: 0.20087966089583822
Fold 3 IBS: 0.17489745307099164
Fold 4 IBS: 0.1976288363585748
Fold 5 IBS: 0.21410523927243486
[I 2024-04-20 18:21:16,483] Trial 87 finished with value: 0.19326347736336585 and parameters: {'subsample': 0.1232216852129193, 'dropout_rate': 0.23197930680997791, 'n_estimators': 213, 'learning_rate': 0.012324655707853138}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.16970260233336584
Fold 2 IBS: 0.20622463179190909
Fold 3 IBS: 0.16860545141900718
Fold 4 IBS: 0.20154912331958857
Fold 5 IBS: 0.21555115410474593
[I 2024-04-20 18:21:17,888] Trial 88 finished with value: 0.19232659259372334 and parameters: {'subsample': 0.1855154669854216, 'dropout_rate': 0.18337727424151423, 'n_estimators': 211, 'learning_rate': 0.01833526569904997}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.15167529135641003
Fold 2 IBS: 0.22169325093327652
Fold 3 IBS: 0.16496174909429
Fold 4 IBS: 0.19928474258903364
Fold 5 IBS: 0.23188855142190326
[I 2024-04-20 18:21:20,025] Trial 89 finished with value: 0.19390071707898265 and parameters: {'subsample': 0.10074251200602664, 'dropout_rate': 0.11624275294581894, 'n_estimators': 279, 'learning_rate': 0.024466551739280112}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.1828309947009821
Fold 2 IBS: 0.20375084866143192
Fold 3 IBS: 0.17353703845371196
Fold 4 IBS: 0.2040401876080071
Fold 5 IBS: 0.21202804320566004
[I 2024-04-20 18:21:21,131] Trial 90 finished with value: 0.19523742252595863 and parameters: {'subsample': 0.22968658313536472, 'dropout_rate': 0.2119537995545465, 'n_estimators': 179, 'learning_rate': 0.014532097791523266}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.16570524751137256
Fold 2 IBS: 0.21129649747119242
Fold 3 IBS: 0.1668144387946434
Fold 4 IBS: 0.20454681659854462
Fold 5 IBS: 0.21795340607544322
[I 2024-04-20 18:21:22,812] Trial 91 finished with value: 0.19326328129023926 and parameters: {'subsample': 0.18445841892157372, 'dropout_rate': 0.17413646016306772, 'n_estimators': 236, 'learning_rate': 0.018941163745444464}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.16926539599552295
Fold 2 IBS: 0.20196158665825045
Fold 3 IBS: 0.17128722917760203
Fold 4 IBS: 0.19433351440510213
Fold 5 IBS: 0.21606519842790625
[I 2024-04-20 18:21:24,202] Trial 92 finished with value: 0.19058258493287678 and parameters: {'subsample': 0.12391613433771263, 'dropout_rate': 0.2958722086506722, 'n_estimators': 210, 'learning_rate': 0.017101575645730577}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.15753497292719745
Fold 2 IBS: 0.24072576525476513
Fold 3 IBS: 0.16490489477766154
Fold 4 IBS: 0.22541879775235973
Fold 5 IBS: 0.2315409825959085
[I 2024-04-20 18:21:26,636] Trial 93 finished with value: 0.2040250826615785 and parameters: {'subsample': 0.1523989432412013, 'dropout_rate': 0.2834021495842052, 'n_estimators': 314, 'learning_rate': 0.022023566287188323}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.1700364489985676
Fold 2 IBS: 0.20184990181156778
Fold 3 IBS: 0.1732272117734306
Fold 4 IBS: 0.19825433231137235
Fold 5 IBS: 0.2142643178665628
[I 2024-04-20 18:21:27,891] Trial 94 finished with value: 0.19152644255230022 and parameters: {'subsample': 0.12769407808724031, 'dropout_rate': 0.14323899052679157, 'n_estimators': 190, 'learning_rate': 0.01673452858689594}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.19490844088774245
Fold 2 IBS: 0.20939353258983295
Fold 3 IBS: 0.18919428025838209

Fold 4 IBS: 0.21188491694556194
Fold 5 IBS: 0.21410930497209688
[I 2024-04-20 18:21:29,498] Trial 95 finished with value: 0.20389809513072327 and parameters: {'subsample': 0.13325875598093934, 'dropout_rate': 0.14328453982452782, 'n_estimators': 227, 'learning_rate': 0.0051619495422841905}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.18595695995906586
Fold 2 IBS: 0.2026086142619695
Fold 3 IBS: 0.17977537744545175
Fold 4 IBS: 0.20420808257142417
Fold 5 IBS: 0.2125609356574605
[I 2024-04-20 18:21:30,778] Trial 96 finished with value: 0.19702199397907433 and parameters: {'subsample': 0.1576853345960427, 'dropout_rate': 0.24198802409859813, 'n_estimators': 193, 'learning_rate': 0.01023216088648701}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.18656302725281798
Fold 2 IBS: 0.20311422177846558
Fold 3 IBS: 0.18168069964582573
Fold 4 IBS: 0.2048176795886752
Fold 5 IBS: 0.213526515687183
[I 2024-04-20 18:21:32,763] Trial 97 finished with value: 0.19794042879059348 and parameters: {'subsample': 0.12656716226385428, 'dropout_rate': 0.31372183756474226, 'n_estimators': 267, 'learning_rate': 0.007259050006609077}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.17496593666580776
Fold 2 IBS: 0.20640016359750818
Fold 3 IBS: 0.1710859194898251
Fold 4 IBS: 0.2007182943276308
Fold 5 IBS: 0.21374544025175432
[I 2024-04-20 18:21:34,486] Trial 98 finished with value: 0.19338315086650523 and parameters: {'subsample': 0.20145971148214295, 'dropout_rate': 0.41199001028487114, 'n_estimators': 242, 'learning_rate': 0.013507443757206819}. Best is trial 82 with value: 0.18932597122094488.
Fold 1 IBS: 0.15459375190674823
Fold 2 IBS: 0.21823540491640356
Fold 3 IBS: 0.16740966832058773
Fold 4 IBS: 0.21249254084834068
Fold 5 IBS: 0.22991727742853693
[I 2024-04-20 18:21:36,582] Trial 99 finished with value: 0.19652972868412344 and parameters: {'subsample': 0.10076607918246624, 'dropout_rate': 0.14117771688979866, 'n_estimators': 259, 'learning_rate': 0.025517167454679766}. Best is trial 82 with value: 0.18932597122094488.


* Best trial for IBS:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.18932597122094488], datetime_start=datetime.datetime(2024, 4, 20, 18, 21, 6, 919785), datetime_complete=datetime.datetime(2024, 4, 20, 18, 21, 8, 473171), params={'subsample': 0.11263052409999037, 'dropout_rate': 0.20981564910049627, 'n_estimators': 226, 'learning_rate': 0.017066518914446174}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=82, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.11263052409999037, 'dropout_rate': 0.20981564910049627, 'n_estimators': 226, 'learning_rate': 0.017066518914446174}


* Best Score for IBS:
 0.18932597122094488

In [78]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [79]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.754
train_ibs:  0.189

#### Test

In [80]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [81]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.165569093503576,
                                              learning_rate=0.07576716957337241,
                                              n_estimators=142,
                                              random_state=123,
                                              subsample=0.10904393649144295)

C-index score: 0.56

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.20981564910049627,
                                              learning_rate=0.017066518914446174,
                                              n_estimators=226,
                                              random_state=123,
                                              subsample=0.11263052409999037)

IBS: 0.205

In [82]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [83]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.826   1.0
ExtraSurvivalTrees               0.794   2.0
CoxPH                            0.758   3.0
CoxLasso                         0.756   4.5
CoxElastic                       0.756   4.5
ComponentwiseGradientBoosting    0.754   6.0
GradientBoosting                 0.745   7.0
CoxRidge                         0.718   8.0

In [84]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.183   1.5
ExtraSurvivalTrees             0.183   1.5
CoxLasso                       0.188   3.5
CoxElastic                     0.188   3.5
ComponentwiseGradientBoosting  0.189   5.0
GradientBoosting               0.215   6.0
CoxRidge                       0.217   7.0
CoxPH                          0.360   8.0

In [85]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.653   1.0
CoxRidge                         0.624   2.0
ExtraSurvivalTrees               0.618   3.0
GradientBoosting                 0.603   4.0
CoxLasso                         0.583   5.0
CoxElastic                       0.582   6.0
ComponentwiseGradientBoosting    0.560   7.0

In [86]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.205   1.0
Randomsurvivalforest           0.206   2.0
ExtraSurvivalTrees             0.215   3.0
GradientBoosting               0.220   4.0
CoxRidge                       0.221   5.0
CoxLasso                       0.287   6.5
CoxElastic                     0.287   6.5

In [87]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/minmax/no_selection/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_os_minmax_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [88]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-20