In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
 
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import MinMaxScaler

In [3]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [4]:
# Need to choose patient_id from OUS_D1 in response_OUS
data = list(OUS_D1['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D1, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS', 'LRC', 'event_LRC'])]

In [5]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [6]:
# Check null values in D1
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [7]:
(MAASTRO_D1['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [8]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [9]:
# need to choose patient_id from MAASTRO_D1 in response_MAASTRO
data = list(MAASTRO_D1['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [10]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D1, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'DFS_event', 'LRC', 'LRC_event'])]

In [11]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [12]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, OS, OS_event]
Index: []

In [13]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS'])]

# y 
y = clinical_train.loc[:, ['OS', 'event_OS']]

In [14]:
# Set lower, upper time point and gbsg_times for IBS calculation later 

# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'OS_event' : 'event_OS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'event_OS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['OS', 'event_OS']]
lower, upper = np.percentile(y_MAASTRO['OS'], [10, 90])
gbsg_times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_OS'], y_MAASTRO['OS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 14)
y_train:  (139,)

(99, 16)

# Feature Selection: PLSR

In [15]:
selected_features = ["hpv_related",
"MTV",
"TLG"]

# Selecting features in the DataFrame
X_plsr = X[selected_features]
X_new = X_plsr.copy()

In [16]:
X_MAASTRO_plsr = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_plsr.copy()

# Standardization

In [17]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [26]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new = MAASTRO_new[X_new.columns]
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [27]:
X_new

     hpv_related     MTV         TLG
0            0.0   7.934   86.228420
1            0.0   1.656    7.040100
2            0.0  14.502   83.569669
3            0.0   2.440    5.567091
4            0.0   3.668   16.150550
..           ...     ...         ...
134          1.0   3.650   26.280140
135          1.0  18.967  101.754834
136          1.0   6.370   66.273201
137          1.0  12.443   71.832443
138          1.0   7.983   78.647696

[139 rows x 3 columns]

In [28]:
X_new_std

     hpv_related       MTV       TLG
0            0.0  0.074159  0.044798
1            0.0  0.008512  0.001900
2            0.0  0.142839  0.043358
3            0.0  0.016710  0.001102
4            0.0  0.029551  0.006835
..           ...       ...       ...
134          1.0  0.029363  0.012323
135          1.0  0.189529  0.053209
136          1.0  0.057805  0.033988
137          1.0  0.121309  0.037000
138          1.0  0.074672  0.040692

[139 rows x 3 columns]

In [29]:
MAASTRO_new

    hpv_related     MTV         TLG
0             1  22.841  263.611623
1             0   5.660   36.980700
2             0   7.791   74.636342
3             0   7.908   46.791979
4             1  15.237  107.637514
..          ...     ...         ...
94            0   6.110  144.490782
95            0   7.182   69.214868
96            1  16.483  102.594274
97            1   9.981  103.229492
98            0   3.495   28.553212

[99 rows x 3 columns]

In [30]:
MAASTRO_new_std

    hpv_related       MTV       TLG
0             1  0.230038  0.140892
1             0  0.050381  0.018119
2             0  0.072664  0.038519
3             0  0.073887  0.023434
4             1  0.150525  0.056396
..          ...       ...       ...
94            0  0.055086  0.076361
95            0  0.066296  0.035582
96            1  0.163554  0.053664
97            1  0.095564  0.054008
98            0  0.027742  0.013554

[99 rows x 3 columns]

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [31]:
# Setting the y format for skf below  
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:55:26,311] A new study created in memory with name: no-name-91dc8cfb-15fd-4cc6-9bd9-08bda29ec3d9

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8270042194092827

[I 2024-04-13 17:55:27,441] A new study created in memory with name: no-name-27d47374-d5e7-449d-ad44-4fbe50fd1b9f

Fold 5 C-index: 0.6197183098591549
[I 2024-04-13 17:55:27,428] Trial 0 finished with value: 0.7361677806181388 and parameters: {}. Best is trial 0 with value: 0.7361677806181388.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7361677806181388], datetime_start=datetime.datetime(2024, 4, 13, 17, 55, 26, 455302), datetime_complete=datetime.datetime(2024, 4, 13, 17, 55, 27, 428052), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7361677806181388

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1791590650279046
Fold 2 IBS: 0.20170223404947618
Fold 3 IBS: 0.1750546844970336
Fold 4 IBS: 0.14253965894637302
Fold 5 IBS: 0.2695925587123099
[I 2024-04-13 17:55:28,621] Trial 0 finished with value: 0.19360964024661945 and parameters: {}. Best is trial 0 with value: 0.19360964024661945.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19360964024661945], datetime_start=datetime.datetime(2024, 4, 13, 17, 55, 27, 478579), datetime_complete=datetime.datetime(2024, 4, 13, 17, 55, 28, 620394), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19360964024661945

In [32]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [33]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.194

#### Test

In [34]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [35]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.623
IBS score: 0.234

In [36]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [37]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [38]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:55:29,211] A new study created in memory with name: no-name-1c943c8b-8e21-454e-b854-e2c2df70cadd

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019

[I 2024-04-13 17:55:29,942] A new study created in memory with name: no-name-103bdd14-b9f0-4cf6-b0c7-7b34211b684f

Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:55:29,932] Trial 0 finished with value: 0.6975692731548933 and parameters: {}. Best is trial 0 with value: 0.6975692731548933.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6975692731548933], datetime_start=datetime.datetime(2024, 4, 13, 17, 55, 29, 251179), datetime_complete=datetime.datetime(2024, 4, 13, 17, 55, 29, 919702), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6975692731548933

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397651764739065
Fold 2 IBS: 0.221577916505828
Fold 3 IBS: 0.20453594517659848
Fold 4 IBS: 0.2247380366950916
Fold 5 IBS: 0.21812431575089974
[I 2024-04-13 17:55:30,688] Trial 0 finished with value: 0.2165905463551617 and parameters: {}. Best is trial 0 with value: 0.2165905463551617.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2165905463551617], datetime_start=datetime.datetime(2024, 4, 13, 17, 55, 30, 105254), datetime_complete=datetime.datetime(2024, 4, 13, 17, 55, 30, 688669), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2165905463551617

In [39]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [40]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.698
train_ibs:  0.217

#### Test

In [41]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [42]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.589

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.221

In [43]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [44]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:55:33,374] A new study created in memory with name: no-name-bd668467-10f7-4baf-924e-49c189ab9722

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827

[I 2024-04-13 17:55:35,622] A new study created in memory with name: no-name-b49c04b1-2d3f-464d-b448-d3b0053945c1

Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:35,581] Trial 0 finished with value: 0.7361263555974262 and parameters: {}. Best is trial 0 with value: 0.7361263555974262.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7361263555974262], datetime_start=datetime.datetime(2024, 4, 13, 17, 55, 33, 610049), datetime_complete=datetime.datetime(2024, 4, 13, 17, 55, 35, 580772), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7361263555974262

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.1790010227435467
Fold 2 IBS: 0.20300340736300934
Fold 3 IBS: 0.17476312604505478
Fold 4 IBS: 0.1424966344952737
Fold 5 IBS: 0.2691552661970626
[I 2024-04-13 17:55:37,838] Trial 0 finished with value: 0.1936838913687894 and parameters: {}. Best is trial 0 with value: 0.1936838913687894.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1936838913687894], datetime_start=datetime.datetime(2024, 4, 13, 17, 55, 35, 788323), datetime_complete=datetime.datetime(2024, 4, 13, 17, 55, 37, 837771), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1936838913687894

In [45]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [46]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.736
train_ibs:  0.194

#### Test

In [47]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [48]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.624

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.232

In [49]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [50]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 17:55:39,208] A new study created in memory with name: no-name-b54b262b-0bff-4144-9fc8-496b732e478a

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:41,099] Trial 0 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7369702374539663.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:43,206] Trial 1 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.7369921564632271.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:45,300] Trial 2 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.7369921564632271.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:55:46,747] Trial 3 finished with value: 0.7370653227335765 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 3 with value: 0.7370653227335765.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:48,571] Trial 4 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 3 with value: 0.7370653227335765.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:50,400] Trial 5 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:51,978] Trial 6 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:53,449] Trial 7 finished with value: 0.7361263555974262 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:55,531] Trial 8 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:55:57,876] Trial 9 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:55:59,830] Trial 10 finished with value: 0.7345555961732171 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:01,879] Trial 11 finished with value: 0.7361263555974262 and parameters: {'l1_ratio': 0.48997130262629585}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:03,702] Trial 12 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.4198331713929624}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:56:04,176] Trial 13 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.025696257467433647}. Best is trial 5 with value: 0.7378360383197672.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:56:05,986] Trial 14 finished with value: 0.7379311235993773 and parameters: {'l1_ratio': 0.2709965207791268}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:08,253] Trial 15 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.20186533754516}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:10,160] Trial 16 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.30518868850921266}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:11,839] Trial 17 finished with value: 0.7361263555974262 and parameters: {'l1_ratio': 0.6174983689046709}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:13,337] Trial 18 finished with value: 0.7361263555974262 and parameters: {'l1_ratio': 0.870217338052673}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:15,310] Trial 19 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.16746447253492103}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:17,409] Trial 20 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.3731209156542978}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:56:19,547] Trial 21 finished with value: 0.7370653227335765 and parameters: {'l1_ratio': 0.4923489010257901}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:21,549] Trial 22 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.28859761771806275}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:23,573] Trial 23 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.5690839218392072}. Best is trial 14 with value: 0.7379311235993773.

Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:26,016] Trial 24 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.37291524271560916}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:28,337] Trial 25 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.4236492178393837}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:31,181] Trial 26 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.14172431544585673}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:33,472] Trial 27 finished with value: 0.7361263555974262 and parameters: {'l1_ratio': 0.7955621062891691}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:35,458] Trial 28 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.45557636249053446}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:38,228] Trial 29 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.6011016420338157}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:40,163] Trial 30 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.32198034394483777}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:42,139] Trial 31 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.36163472104060657}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:43,884] Trial 32 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.24683825876396973}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:45,745] Trial 33 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.53318089594935}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:47,492] Trial 34 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.2459209596030891}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:49,577] Trial 35 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.44096252678725323}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:51,454] Trial 36 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.3321544807607419}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:53,178] Trial 37 finished with value: 0.7361263555974262 and parameters: {'l1_ratio': 0.6528217245541015}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:55,356] Trial 38 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.38784270956363726}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:56:57,152] Trial 39 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.7304824129775314}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:56:59,031] Trial 40 finished with value: 0.7370653227335765 and parameters: {'l1_ratio': 0.5204911496675979}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:01,351] Trial 41 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.43310605009927233}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:03,111] Trial 42 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.4730624242917584}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:05,479] Trial 43 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.2546094211458251}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:07,205] Trial 44 finished with value: 0.7379311235993773 and parameters: {'l1_ratio': 0.40846097951258764}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:09,141] Trial 45 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.18661375955358842}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:10,453] Trial 46 finished with value: 0.7345555961732171 and parameters: {'l1_ratio': 0.08919298240967921}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8291139240506329

Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:12,301] Trial 47 finished with value: 0.7365482965256962 and parameters: {'l1_ratio': 0.573840629919339}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:13,808] Trial 48 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.3951993011558007}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:15,511] Trial 49 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.34713398312216626}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:17,399] Trial 50 finished with value: 0.7379311235993773 and parameters: {'l1_ratio': 0.29034943396094376}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:19,212] Trial 51 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.2841468483496545}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:20,935] Trial 52 finished with value: 0.7369702374539663 and parameters: {'l1_ratio': 0.508088650117101}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:22,838] Trial 53 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.28437686163142234}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:24,588] Trial 54 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.41598638484135825}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:26,802] Trial 55 finished with value: 0.7379311235993773 and parameters: {'l1_ratio': 0.132679519787263}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:57:27,214] Trial 56 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.023230044437482722}. Best is trial 14 with value: 0.7379311235993773.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:28,583] Trial 57 finished with value: 0.7527374143550352 and parameters: {'l1_ratio': 0.08642169680928646}. Best is trial 57 with value: 0.7527374143550352.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:29,953] Trial 58 finished with value: 0.7527374143550352 and parameters: {'l1_ratio': 0.07989103176852408}. Best is trial 57 with value: 0.7527374143550352.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:31,898] Trial 59 finished with value: 0.7345555961732171 and parameters: {'l1_ratio': 0.09628080803866126}. Best is trial 57 with value: 0.7527374143550352.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 17:57:33,620] Trial 60 finished with value: 0.7545692386340426 and parameters: {'l1_ratio': 0.0671733143869957}. Best is trial 60 with value: 0.7545692386340426.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:57:35,078] Trial 61 finished with value: 0.7555082057701928 and parameters: {'l1_ratio': 0.05698808605998924}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:57:36,592] Trial 62 finished with value: 0.7555082057701928 and parameters: {'l1_ratio': 0.06279608028313088}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:57:37,018] Trial 63 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.0001238080351030485}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 17:57:38,640] Trial 64 finished with value: 0.7545692386340426 and parameters: {'l1_ratio': 0.0694370096633014}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:57:40,623] Trial 65 finished with value: 0.7527374143550352 and parameters: {'l1_ratio': 0.08583354236970701}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 17:57:42,249] Trial 66 finished with value: 0.7545692386340426 and parameters: {'l1_ratio': 0.06404799997528651}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:57:43,744] Trial 67 finished with value: 0.7546153486273357 and parameters: {'l1_ratio': 0.056192833669170335}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:57:44,816] Trial 68 finished with value: 0.7422729116525457 and parameters: {'l1_ratio': 0.04805878597735917}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:46,920] Trial 69 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.13756290532288945}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:57:48,654] Trial 70 finished with value: 0.7546153486273357 and parameters: {'l1_ratio': 0.05548019817689797}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576

Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:57:50,183] Trial 71 finished with value: 0.7546153486273357 and parameters: {'l1_ratio': 0.05565522172384288}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:57:51,772] Trial 72 finished with value: 0.7546153486273357 and parameters: {'l1_ratio': 0.05528836367453126}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:57:52,302] Trial 73 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.03070539647866647}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:54,287] Trial 74 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.1173667128334347}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:56,626] Trial 75 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.17067445226287536}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:57:58,824] Trial 76 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.21673060039655495}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:57:59,213] Trial 77 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.02010745283366469}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:58:01,038] Trial 78 finished with value: 0.7546153486273357 and parameters: {'l1_ratio': 0.05464935163787742}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:03,396] Trial 79 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.11306180074768833}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:58:03,884] Trial 80 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.0004541040154042511}. Best is trial 61 with value: 0.7555082057701928.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:58:05,227] Trial 81 finished with value: 0.7564885979270556 and parameters: {'l1_ratio': 0.050990548882846466}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 17:58:05,951] Trial 82 finished with value: 0.7088368787886961 and parameters: {'l1_ratio': 0.04225334136772895}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:07,874] Trial 83 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.16463542481275276}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:58:09,420] Trial 84 finished with value: 0.7546153486273357 and parameters: {'l1_ratio': 0.05637012318052684}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:58:10,617] Trial 85 finished with value: 0.7564885979270556 and parameters: {'l1_ratio': 0.05352013611685191}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:12,430] Trial 86 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.11809740609755778}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:14,215] Trial 87 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.14304958222289965}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6623376623376623
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:15,472] Trial 88 finished with value: 0.7361263555974262 and parameters: {'l1_ratio': 0.9655660156128469}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 17:58:16,146] Trial 89 finished with value: 0.7088368787886961 and parameters: {'l1_ratio': 0.039313348903130554}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:58:16,579] Trial 90 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.0179933901719427}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:58:17,832] Trial 91 finished with value: 0.7564885979270556 and parameters: {'l1_ratio': 0.053436610865145125}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:58:19,402] Trial 92 finished with value: 0.7379311235993773 and parameters: {'l1_ratio': 0.10955184639328039}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6384976525821596
[I 2024-04-13 17:58:20,705] Trial 93 finished with value: 0.7564885979270556 and parameters: {'l1_ratio': 0.052149125023635175}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:22,408] Trial 94 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.158205644686582}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286

Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:58:22,823] Trial 95 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.003520259226220235}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 17:58:23,227] Trial 96 finished with value: 0.6975692731548933 and parameters: {'l1_ratio': 0.033087452747283294}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:24,811] Trial 97 finished with value: 0.7378360383197672 and parameters: {'l1_ratio': 0.20811948120275675}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6244131455399061
[I 2024-04-13 17:58:26,403] Trial 98 finished with value: 0.7369921564632271 and parameters: {'l1_ratio': 0.1854525624614252}. Best is trial 81 with value: 0.7564885979270556.
Fold 1 C-index: 0.6666666666666666
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.810126582278481

[I 2024-04-13 17:58:28,050] A new study created in memory with name: no-name-24611141-c3a7-4c21-a986-2fef7cfaabce

Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 17:58:28,019] Trial 99 finished with value: 0.7345555961732171 and parameters: {'l1_ratio': 0.10183370601044706}. Best is trial 81 with value: 0.7564885979270556.


* Best trial for C-index:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.7564885979270556], datetime_start=datetime.datetime(2024, 4, 13, 17, 58, 3, 890117), datetime_complete=datetime.datetime(2024, 4, 13, 17, 58, 5, 227059), params={'l1_ratio': 0.050990548882846466}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=81, value=None)


* Best Score for C-index:
 0.7564885979270556

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17901608673122438
Fold 2 IBS: 0.2032298388767962
Fold 3 IBS: 0.1748061167355499
Fold 4 IBS: 0.1424598127912613
Fold 5 IBS: 0.26925610304190817
[I 2024-04-13 17:58:29,830] Trial 0 finished with value: 0.193753591635348 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.193753591635348.
Fold 1 IBS: 0.17902658310162128
Fold 2 IBS: 0.20334768738254913
Fold 3 IBS: 0.1748247416286342
Fold 4 IBS: 0.14244653975493216
Fold 5 IBS: 0.2692995422000311
[I 2024-04-13 17:58:31,945] Trial 1 finished with value: 0.19378901881355354 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.193753591635348.
Fold 1 IBS: 0.17902862187768215
Fold 2 IBS: 0.20335940307073755
Fold 3 IBS: 0.1748246839697923
Fold 4 IBS: 0.1424447651679779
Fold 5 IBS: 0.26930098210916037
[I 2024-04-13 17:58:33,676] Trial 2 finished with value: 0.19379169123907009 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.193753591635348.
Fold 1 IBS: 0.17902287394625077
Fold 2 IBS: 0.2033305781427905
Fold 3 IBS: 0.17481920874090442
Fold 4 IBS: 0.14245523597489287
Fold 5 IBS: 0.2692570165566803
[I 2024-04-13 17:58:35,700] Trial 3 finished with value: 0.19377698267230375 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.193753591635348.
Fold 1 IBS: 0.1790092468334616
Fold 2 IBS: 0.20327094777051785
Fold 3 IBS: 0.17479956191043722
Fold 4 IBS: 0.1424598266104339
Fold 5 IBS: 0.2692449938789123
[I 2024-04-13 17:58:37,189] Trial 4 finished with value: 0.19375691540075257 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.193753591635348.
Fold 1 IBS: 0.1790271508076911
Fold 2 IBS: 0.20324661711041625
Fold 3 IBS: 0.17481572162970802
Fold 4 IBS: 0.1424474264779743
Fold 5 IBS: 0.26928296811859215
[I 2024-04-13 17:58:39,098] Trial 5 finished with value: 0.19376397682887636 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.193753591635348.
Fold 1 IBS: 0.179010591533365
Fold 2 IBS: 0.20310401720398022
Fold 3 IBS: 0.17477204540638952
Fold 4 IBS: 0.14248986124918028
Fold 5 IBS: 0.26913557545049444
[I 2024-04-13 17:58:40,756] Trial 6 finished with value: 0.1937024181686819 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.1937024181686819.
Fold 1 IBS: 0.17901248387483945
Fold 2 IBS: 0.2032865320221218
Fold 3 IBS: 0.1747997225676477
Fold 4 IBS: 0.14246316967521896
Fold 5 IBS: 0.26924762250448775
[I 2024-04-13 17:58:42,634] Trial 7 finished with value: 0.19376190612886313 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.1937024181686819.
Fold 1 IBS: 0.17902382696221064
Fold 2 IBS: 0.20323431545472376
Fold 3 IBS: 0.17481508162026696
Fold 4 IBS: 0.14245038131849647
Fold 5 IBS: 0.269279907872345
[I 2024-04-13 17:58:44,961] Trial 8 finished with value: 0.19376070264560857 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.1937024181686819.
Fold 1 IBS: 0.17902700336485755
Fold 2 IBS: 0.20326955855351278
Fold 3 IBS: 0.17481362134229858
Fold 4 IBS: 0.14244541061340052
Fold 5 IBS: 0.26928114140078896
[I 2024-04-13 17:58:46,710] Trial 9 finished with value: 0.1937673470549717 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.1937024181686819.
Fold 1 IBS: 0.1790114379495082
Fold 2 IBS: 0.20309387509085766
Fold 3 IBS: 0.17477466844348521
Fold 4 IBS: 0.1424910127717755
Fold 5 IBS: 0.26913927736323084
[I 2024-04-13 17:58:48,115] Trial 10 finished with value: 0.19370205432377147 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 10 with value: 0.19370205432377147.
Fold 1 IBS: 0.17900033632446508
Fold 2 IBS: 0.20301922463217068
Fold 3 IBS: 0.17478406760585982
Fold 4 IBS: 0.14249575120029795
Fold 5 IBS: 0.2691524245320554
[I 2024-04-13 17:58:51,236] Trial 11 finished with value: 0.1936903608589698 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17899973742031688
Fold 2 IBS: 0.20303300179125636
Fold 3 IBS: 0.1747823146490426
Fold 4 IBS: 0.1424949862203754
Fold 5 IBS: 0.26915004476065346
[I 2024-04-13 17:58:53,059] Trial 12 finished with value: 0.19369201696832894 and parameters: {'l1_ratio': 0.9948264745658929}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.2126378060967373
Fold 2 IBS: 0.22136888644736544
Fold 3 IBS: 0.20386738710071486
Fold 4 IBS: 0.22327435596532444
Fold 5 IBS: 0.21828896774980877
[I 2024-04-13 17:58:54,297] Trial 13 finished with value: 0.21588748067199015 and parameters: {'l1_ratio': 0.03152521162798527}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.1790152442544041
Fold 2 IBS: 0.20317927391706922
Fold 3 IBS: 0.17479741445978703
Fold 4 IBS: 0.14247850469461878
Fold 5 IBS: 0.26919388724368526
[I 2024-04-13 17:58:57,529] Trial 14 finished with value: 0.19373286491391287 and parameters: {'l1_ratio': 0.8887005110166508}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17901703141364872
Fold 2 IBS: 0.20311468465307914
Fold 3 IBS: 0.17479065585045034
Fold 4 IBS: 0.14247040315789147
Fold 5 IBS: 0.2692209430290836
[I 2024-04-13 17:59:02,231] Trial 15 finished with value: 0.19372274362083067 and parameters: {'l1_ratio': 0.8435258665171791}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.1790063311347725
Fold 2 IBS: 0.20315768656615024
Fold 3 IBS: 0.1748081267501531
Fold 4 IBS: 0.14247070290484667
Fold 5 IBS: 0.26922115957583936
[I 2024-04-13 17:59:05,211] Trial 16 finished with value: 0.19373280138635235 and parameters: {'l1_ratio': 0.8046771700892117}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17899733823282668
Fold 2 IBS: 0.20308797240226648
Fold 3 IBS: 0.17477540276670162
Fold 4 IBS: 0.14249133531077365
Fold 5 IBS: 0.26914031295867963
[I 2024-04-13 17:59:08,261] Trial 17 finished with value: 0.19369847233424958 and parameters: {'l1_ratio': 0.9853615392538034}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17901670316940563
Fold 2 IBS: 0.20321819591690896
Fold 3 IBS: 0.1748011617967256
Fold 4 IBS: 0.14246770674473855
Fold 5 IBS: 0.26921147676279467
[I 2024-04-13 17:59:10,790] Trial 18 finished with value: 0.1937430488781147 and parameters: {'l1_ratio': 0.7922918930288001}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17901532274402787
Fold 2 IBS: 0.20320117926914133
Fold 3 IBS: 0.1748142028023175
Fold 4 IBS: 0.14245683470237377
Fold 5 IBS: 0.26927286836117126
[I 2024-04-13 17:59:13,327] Trial 19 finished with value: 0.19375208157580634 and parameters: {'l1_ratio': 0.608409044915716}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.1790135083380919
Fold 2 IBS: 0.20306923759419945
Fold 3 IBS: 0.1747932351763764
Fold 4 IBS: 0.14247606270785465
Fold 5 IBS: 0.2691880208451014
[I 2024-04-13 17:59:15,607] Trial 20 finished with value: 0.19370801293232476 and parameters: {'l1_ratio': 0.8818811135844746}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17900813165105894
Fold 2 IBS: 0.20302974934201776
Fold 3 IBS: 0.1747871288432765
Fold 4 IBS: 0.14249049064161487
Fold 5 IBS: 0.2691632543813425
[I 2024-04-13 17:59:18,189] Trial 21 finished with value: 0.19369575097186212 and parameters: {'l1_ratio': 0.9705260458283718}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17900773109902138
Fold 2 IBS: 0.2030533350658119
Fold 3 IBS: 0.17479185674985168
Fold 4 IBS: 0.14248107601472149
Fold 5 IBS: 0.26918116924530655
[I 2024-04-13 17:59:19,902] Trial 22 finished with value: 0.1937030336349426 and parameters: {'l1_ratio': 0.9130757617488995}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.1789980096706
Fold 2 IBS: 0.20307262151391425
Fold 3 IBS: 0.17477731955738543
Fold 4 IBS: 0.14249217756830504
Fold 5 IBS: 0.2691430146065678
[I 2024-04-13 17:59:21,446] Trial 23 finished with value: 0.19369662858335449 and parameters: {'l1_ratio': 0.9879856951002318}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17901492616393092
Fold 2 IBS: 0.20325023952883775
Fold 3 IBS: 0.17479751690457598
Fold 4 IBS: 0.14246548674922507
Fold 5 IBS: 0.26923672148203115
[I 2024-04-13 17:59:23,446] Trial 24 finished with value: 0.19375297816572018 and parameters: {'l1_ratio': 0.7858694646230915}. Best is trial 11 with value: 0.1936903608589698.

Fold 1 IBS: 0.17900709032225995
Fold 2 IBS: 0.2030657494491206
Fold 3 IBS: 0.1747902900636781
Fold 4 IBS: 0.14247976499059278
Fold 5 IBS: 0.2691789681056567
[I 2024-04-13 17:59:25,160] Trial 25 finished with value: 0.19370437258626164 and parameters: {'l1_ratio': 0.9106143729430608}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.1790215114696707
Fold 2 IBS: 0.20325977532303732
Fold 3 IBS: 0.17480606376688093
Fold 4 IBS: 0.14245484304626913
Fold 5 IBS: 0.26926025679236704
[I 2024-04-13 17:59:27,313] Trial 26 finished with value: 0.19376049007964502 and parameters: {'l1_ratio': 0.6273790955054189}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17901879899676987
Fold 2 IBS: 0.20326597204973842
Fold 3 IBS: 0.17479803597320426
Fold 4 IBS: 0.14246228618752899
Fold 5 IBS: 0.2692403180909053
[I 2024-04-13 17:59:28,972] Trial 27 finished with value: 0.19375708225962934 and parameters: {'l1_ratio': 0.7517964642342185}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17900839756935194
Fold 2 IBS: 0.20317410196385965
Fold 3 IBS: 0.17479349579470582
Fold 4 IBS: 0.1424817859116274
Fold 5 IBS: 0.2691834704007167
[I 2024-04-13 17:59:31,016] Trial 28 finished with value: 0.19372825032805233 and parameters: {'l1_ratio': 0.915653932720269}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.2132850964439436
Fold 2 IBS: 0.2214692538275374
Fold 3 IBS: 0.20419109926080825
Fold 4 IBS: 0.22398232695219117
Fold 5 IBS: 0.21820662783527367
[I 2024-04-13 17:59:31,679] Trial 29 finished with value: 0.21622688086395084 and parameters: {'l1_ratio': 0.016175696683504215}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17900529354629288
Fold 2 IBS: 0.2032238326124724
Fold 3 IBS: 0.17479529374219435
Fold 4 IBS: 0.14247241825299972
Fold 5 IBS: 0.26919540016314236
[I 2024-04-13 17:59:33,811] Trial 30 finished with value: 0.19373844766342035 and parameters: {'l1_ratio': 0.8512940639677147}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.1789976264909666
Fold 2 IBS: 0.20308138528518618
Fold 3 IBS: 0.17477622401608395
Fold 4 IBS: 0.1424916961164273
Fold 5 IBS: 0.2691414707534302
[I 2024-04-13 17:59:35,464] Trial 31 finished with value: 0.19369768053241884 and parameters: {'l1_ratio': 0.9864858075876226}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.1790121637598908
Fold 2 IBS: 0.20310381424288956
Fold 3 IBS: 0.1747818282093042
Fold 4 IBS: 0.14248154216902112
Fold 5 IBS: 0.26916168314138317
[I 2024-04-13 17:59:37,722] Trial 32 finished with value: 0.19370820630449778 and parameters: {'l1_ratio': 0.930580777401446}. Best is trial 11 with value: 0.1936903608589698.
Fold 1 IBS: 0.17900056418816326
Fold 2 IBS: 0.2030139771317631
Fold 3 IBS: 0.1747847374864038
Fold 4 IBS: 0.142496043642355
Fold 5 IBS: 0.26915336580684246
[I 2024-04-13 17:59:39,253] Trial 33 finished with value: 0.19368973765110553 and parameters: {'l1_ratio': 0.9981458715067252}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.1790246867003099
Fold 2 IBS: 0.20328360356562428
Fold 3 IBS: 0.17481737760200836
Fold 4 IBS: 0.14243967942834365
Fold 5 IBS: 0.26929243793353347
[I 2024-04-13 17:59:41,308] Trial 34 finished with value: 0.19377155704596394 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.1790150928107495
Fold 2 IBS: 0.20315062374003456
Fold 3 IBS: 0.1748064472806731
Fold 4 IBS: 0.14247374165976184
Fold 5 IBS: 0.26921506125541406
[I 2024-04-13 17:59:42,883] Trial 35 finished with value: 0.19373219334932662 and parameters: {'l1_ratio': 0.8361501509216206}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17900004610304165
Fold 2 IBS: 0.2030604967256667
Fold 3 IBS: 0.17478726038264866
Fold 4 IBS: 0.14248391778503627
Fold 5 IBS: 0.2691693294187906
[I 2024-04-13 17:59:45,182] Trial 36 finished with value: 0.1937002100830368 and parameters: {'l1_ratio': 0.9387569263940667}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17901220504689414
Fold 2 IBS: 0.20329090802062152
Fold 3 IBS: 0.17481801313898868
Fold 4 IBS: 0.14246297009501738
Fold 5 IBS: 0.26924697279160503
[I 2024-04-13 17:59:46,976] Trial 37 finished with value: 0.19376621381862535 and parameters: {'l1_ratio': 0.6839793126777307}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.1790171733421525
Fold 2 IBS: 0.20314426021629023
Fold 3 IBS: 0.17479480476680825
Fold 4 IBS: 0.14246671466390978
Fold 5 IBS: 0.2692360255221116
[I 2024-04-13 17:59:48,906] Trial 38 finished with value: 0.1937317957022545 and parameters: {'l1_ratio': 0.7460594497443573}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17902587883573948
Fold 2 IBS: 0.20332437277337778
Fold 3 IBS: 0.174826217859237
Fold 4 IBS: 0.14244863745833267
Fold 5 IBS: 0.26927650412828724
[I 2024-04-13 17:59:50,981] Trial 39 finished with value: 0.19378032221099484 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17900173659756635
Fold 2 IBS: 0.2030269559140548
Fold 3 IBS: 0.1747915123455135
Fold 4 IBS: 0.14248639227530016
Fold 5 IBS: 0.2691753016138598
[I 2024-04-13 17:59:52,587] Trial 40 finished with value: 0.19369637974925893 and parameters: {'l1_ratio': 0.9451726978938738}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.1790016853265626
Fold 2 IBS: 0.20302797505326456
Fold 3 IBS: 0.17479138241117734
Fold 4 IBS: 0.14248633583295206
Fold 5 IBS: 0.26917511927436555
[I 2024-04-13 17:59:54,154] Trial 41 finished with value: 0.19369649957966442 and parameters: {'l1_ratio': 0.9449764242899545}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17900856902359835
Fold 2 IBS: 0.20316254264368297
Fold 3 IBS: 0.17480233408670423
Fold 4 IBS: 0.14247609691679916
Fold 5 IBS: 0.26920519660172637
[I 2024-04-13 17:59:55,993] Trial 42 finished with value: 0.19373094785450223 and parameters: {'l1_ratio': 0.8631700345624591}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17900304460368127
Fold 2 IBS: 0.203142789525979
Fold 3 IBS: 0.17477300983002675
Fold 4 IBS: 0.14248784220214186
Fold 5 IBS: 0.26917989834916234
[I 2024-04-13 17:59:57,825] Trial 43 finished with value: 0.19371731690219823 and parameters: {'l1_ratio': 0.950216367389394}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17899971003619
Fold 2 IBS: 0.20303363121415194
Fold 3 IBS: 0.17478223476355567
Fold 4 IBS: 0.14249495136886278
Fold 5 IBS: 0.26914993244580027
[I 2024-04-13 17:59:59,310] Trial 44 finished with value: 0.19369209196571213 and parameters: {'l1_ratio': 0.9947170440864863}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17899862196011412
Fold 2 IBS: 0.20305859971242154
Fold 3 IBS: 0.17477907934510645
Fold 4 IBS: 0.14249295126186426
Fold 5 IBS: 0.26914549301348095
[I 2024-04-13 18:00:01,072] Trial 45 finished with value: 0.19369494905859744 and parameters: {'l1_ratio': 0.9903953027765289}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.1790258352933474
Fold 2 IBS: 0.2033247839289327
Fold 3 IBS: 0.1748208885403798
Fold 4 IBS: 0.14245432978008288
Fold 5 IBS: 0.26926100278585785
[I 2024-04-13 18:00:02,949] Trial 46 finished with value: 0.19377736806572013 and parameters: {'l1_ratio': 0.5222973322437542}. Best is trial 33 with value: 0.19368973765110553.
Fold 1 IBS: 0.17900081451327948
Fold 2 IBS: 0.2030082087014948
Fold 3 IBS: 0.17478547527612642
Fold 4 IBS: 0.14249636580036226
Fold 5 IBS: 0.26915440220631276
[I 2024-04-13 18:00:04,532] Trial 47 finished with value: 0.19368905329951516 and parameters: {'l1_ratio': 0.9991568750151278}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790119951547149
Fold 2 IBS: 0.20320779395973299
Fold 3 IBS: 0.1747998549211033
Fold 4 IBS: 0.14247090023052705
Fold 5 IBS: 0.26920590226875646
[I 2024-04-13 18:00:07,310] Trial 48 finished with value: 0.19373928930696693 and parameters: {'l1_ratio': 0.8246849940816015}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790143924916156
Fold 2 IBS: 0.20319721967399762
Fold 3 IBS: 0.17479535591464082
Fold 4 IBS: 0.14247761466741815
Fold 5 IBS: 0.2691909990812958
[I 2024-04-13 18:00:09,669] Trial 49 finished with value: 0.1937351163657936 and parameters: {'l1_ratio': 0.8853380411551567}. Best is trial 47 with value: 0.19368905329951516.

Fold 1 IBS: 0.1790305164426132
Fold 2 IBS: 0.20440923769808736
Fold 3 IBS: 0.1747867033327353
Fold 4 IBS: 0.22070687724624155
Fold 5 IBS: 0.2692269146374073
[I 2024-04-13 18:00:12,106] Trial 50 finished with value: 0.20963204987141695 and parameters: {'l1_ratio': 0.08888770157152942}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790106951054058
Fold 2 IBS: 0.2031014457237615
Fold 3 IBS: 0.17477236503681473
Fold 4 IBS: 0.14249000151711563
Fold 5 IBS: 0.26913602677621024
[I 2024-04-13 18:00:13,764] Trial 51 finished with value: 0.19370210683186156 and parameters: {'l1_ratio': 0.9812035738211817}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17901486574638428
Fold 2 IBS: 0.20318725247970823
Fold 3 IBS: 0.1747964977912837
Fold 4 IBS: 0.14247810829404545
Fold 5 IBS: 0.2691926014773262
[I 2024-04-13 18:00:15,887] Trial 52 finished with value: 0.1937338651577496 and parameters: {'l1_ratio': 0.8872023576102256}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900575689060577
Fold 2 IBS: 0.2030826280725114
Fold 3 IBS: 0.17478044692624697
Fold 4 IBS: 0.14248694704686382
Fold 5 IBS: 0.26915385611212933
[I 2024-04-13 18:00:18,484] Trial 53 finished with value: 0.19370192700967145 and parameters: {'l1_ratio': 0.9609040426576048}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17899890555200929
Fold 2 IBS: 0.2030520977317983
Fold 3 IBS: 0.1747798982801198
Fold 4 IBS: 0.14249331144404417
Fold 5 IBS: 0.26914664573512853
[I 2024-04-13 18:00:21,395] Trial 54 finished with value: 0.19369417174862003 and parameters: {'l1_ratio': 0.9915167780895143}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900630434951226
Fold 2 IBS: 0.20308095425878803
Fold 3 IBS: 0.1747883805455988
Fold 4 IBS: 0.14247893134869158
Fold 5 IBS: 0.26917628324040954
[I 2024-04-13 18:00:24,754] Trial 55 finished with value: 0.19370617074860005 and parameters: {'l1_ratio': 0.9076182309368827}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17899984157305882
Fold 2 IBS: 0.20303060743078521
Fold 3 IBS: 0.17478261869749878
Fold 4 IBS: 0.1424951188751549
Fold 5 IBS: 0.2691504722030637
[I 2024-04-13 18:00:27,247] Trial 56 finished with value: 0.19369173175591228 and parameters: {'l1_ratio': 0.9952429820612867}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900934745552674
Fold 2 IBS: 0.2031478959554067
Fold 3 IBS: 0.17478346979761228
Fold 4 IBS: 0.14247683166065755
Fold 5 IBS: 0.26920757728959605
[I 2024-04-13 18:00:29,995] Trial 57 finished with value: 0.19372502443175987 and parameters: {'l1_ratio': 0.8660532692979819}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790068341136832
Fold 2 IBS: 0.2031493894842229
Fold 3 IBS: 0.1748090924150513
Fold 4 IBS: 0.14247111899582046
Fold 5 IBS: 0.26922251079934634
[I 2024-04-13 18:00:33,067] Trial 58 finished with value: 0.19373178916162484 and parameters: {'l1_ratio': 0.8064062909133375}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.179013058730932
Fold 2 IBS: 0.20308449969470901
Fold 3 IBS: 0.17478424815828997
Fold 4 IBS: 0.1424825999186435
Fold 5 IBS: 0.26916509173176434
[I 2024-04-13 18:00:36,360] Trial 59 finished with value: 0.19370589964686777 and parameters: {'l1_ratio': 0.9342203200397301}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900538684805434
Fold 2 IBS: 0.20309085925457732
Fold 3 IBS: 0.1747794202035432
Fold 4 IBS: 0.1424864971068728
Fold 5 IBS: 0.2691524095831553
[I 2024-04-13 18:00:38,991] Trial 60 finished with value: 0.1937029145992406 and parameters: {'l1_ratio': 0.9594272698353608}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17899979208451197
Fold 2 IBS: 0.20303174520158326
Fold 3 IBS: 0.17478247418588472
Fold 4 IBS: 0.14249505582389163
Fold 5 IBS: 0.26915026905006806
[I 2024-04-13 18:00:40,977] Trial 61 finished with value: 0.19369186726918794 and parameters: {'l1_ratio': 0.9950450178085434}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900609937713807
Fold 2 IBS: 0.20308491542765233
Fold 3 IBS: 0.17478788475512283
Fold 4 IBS: 0.14247871499188774
Fold 5 IBS: 0.2691755857441301
[I 2024-04-13 18:00:42,783] Trial 62 finished with value: 0.1937066400591862 and parameters: {'l1_ratio': 0.9068409939865709}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900440837785317
Fold 2 IBS: 0.2031125856446837
Fold 3 IBS: 0.17477672381776208
Fold 4 IBS: 0.14248531619298974
Fold 5 IBS: 0.26914860754722336
[I 2024-04-13 18:00:44,606] Trial 63 finished with value: 0.1937055283161024 and parameters: {'l1_ratio': 0.9555509825983416}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17899890466442572
Fold 2 IBS: 0.20305211808913554
Fold 3 IBS: 0.17477989571319374
Fold 4 IBS: 0.14249331031493087
Fold 5 IBS: 0.2691466421225804
[I 2024-04-13 18:00:46,600] Trial 64 finished with value: 0.19369417418085325 and parameters: {'l1_ratio': 0.9915132627151726}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900010793249885
Fold 2 IBS: 0.20302448111980922
Fold 3 IBS: 0.17478339779993218
Fold 4 IBS: 0.142495458851466
Fold 5 IBS: 0.2691515671984525
[I 2024-04-13 18:00:48,243] Trial 65 finished with value: 0.19369100258043176 and parameters: {'l1_ratio': 0.9963103204444769}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17902889400751043
Fold 2 IBS: 0.2033457552740579
Fold 3 IBS: 0.1748205480042668
Fold 4 IBS: 0.14245136046630574
Fold 5 IBS: 0.2692882948914987
[I 2024-04-13 18:00:49,939] Trial 66 finished with value: 0.19378697052872793 and parameters: {'l1_ratio': 0.4601899000449552}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900754428760976
Fold 2 IBS: 0.20305695606012303
Fold 3 IBS: 0.17479139907462193
Fold 4 IBS: 0.14248087786602384
Fold 5 IBS: 0.2691805263872629
[I 2024-04-13 18:00:52,129] Trial 67 finished with value: 0.19370346073512829 and parameters: {'l1_ratio': 0.9123564196496633}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900746659408834
Fold 2 IBS: 0.20318314243572996
Fold 3 IBS: 0.17479994428965656
Fold 4 IBS: 0.14247506485924283
Fold 5 IBS: 0.26920192749581984
[I 2024-04-13 18:00:53,831] Trial 68 finished with value: 0.19373350913490747 and parameters: {'l1_ratio': 0.8591272509201815}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790149372035141
Fold 2 IBS: 0.20318574670178585
Fold 3 IBS: 0.17479667061395276
Fold 4 IBS: 0.14247818301815512
Fold 5 IBS: 0.2691928439276937
[I 2024-04-13 18:00:55,649] Trial 69 finished with value: 0.1937336762930203 and parameters: {'l1_ratio': 0.8874847051403005}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17901355792953821
Fold 2 IBS: 0.20312551859396935
Fold 3 IBS: 0.17479474318747132
Fold 4 IBS: 0.14246428664464447
Fold 5 IBS: 0.26923304225183586
[I 2024-04-13 18:00:57,618] Trial 70 finished with value: 0.19372622972149184 and parameters: {'l1_ratio': 0.7810085531144388}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1789999057717919
Fold 2 IBS: 0.2030291312430708
Fold 3 IBS: 0.1747828062775151
Fold 4 IBS: 0.1424952007216967
Fold 5 IBS: 0.2691507358325995
[I 2024-04-13 18:00:58,996] Trial 71 finished with value: 0.1936915559693348 and parameters: {'l1_ratio': 0.9954999500271707}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790005049782609
Fold 2 IBS: 0.20301534098884724
Fold 3 IBS: 0.17478456326306338
Fold 4 IBS: 0.142495967577862
Fold 5 IBS: 0.26915312102371536
[I 2024-04-13 18:01:00,563] Trial 72 finished with value: 0.19368989956634977 and parameters: {'l1_ratio': 0.9979071447485004}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900656725263697
Fold 2 IBS: 0.20306457702645983
Fold 3 IBS: 0.17478270889973802
Fold 4 IBS: 0.14248793883170136
Fold 5 IBS: 0.269157040658258
[I 2024-04-13 18:01:02,760] Trial 73 finished with value: 0.19369976653375884 and parameters: {'l1_ratio': 0.9641590791558077}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790007812815933
Fold 2 IBS: 0.20300897470551924
Fold 3 IBS: 0.1747853772181667
Fold 4 IBS: 0.14249632297888842
Fold 5 IBS: 0.2691542644786998
[I 2024-04-13 18:01:04,349] Trial 74 finished with value: 0.1936891441325735 and parameters: {'l1_ratio': 0.9990224992830858}. Best is trial 47 with value: 0.19368905329951516.

Fold 1 IBS: 0.17901006774965633
Fold 2 IBS: 0.20314916802846342
Fold 3 IBS: 0.17477624324192376
Fold 4 IBS: 0.14248358560184746
Fold 5 IBS: 0.26918920997380735
[I 2024-04-13 18:01:05,591] Trial 75 finished with value: 0.19372165491913967 and parameters: {'l1_ratio': 0.92219738554081}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790067916698692
Fold 2 IBS: 0.2030595718618379
Fold 3 IBS: 0.17478333856840325
Fold 4 IBS: 0.14248821506689177
Fold 5 IBS: 0.26915792666645977
[I 2024-04-13 18:01:07,196] Trial 76 finished with value: 0.19369916876669238 and parameters: {'l1_ratio': 0.9650656605801265}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17901340039176797
Fold 2 IBS: 0.20307707168836137
Fold 3 IBS: 0.17478517763412116
Fold 4 IBS: 0.14248300642108122
Fold 5 IBS: 0.26916639994419245
[I 2024-04-13 18:01:09,003] Trial 77 finished with value: 0.19370501121590483 and parameters: {'l1_ratio': 0.9356194012373432}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17901574625165612
Fold 2 IBS: 0.20319529245007342
Fold 3 IBS: 0.1748148810843331
Fold 4 IBS: 0.14245712429494645
Fold 5 IBS: 0.26924719696662663
[I 2024-04-13 18:01:11,189] Trial 78 finished with value: 0.19374604820952715 and parameters: {'l1_ratio': 0.6096656041682533}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900649312283107
Fold 2 IBS: 0.20306622974818242
Fold 3 IBS: 0.17478250120387895
Fold 4 IBS: 0.14248784773582943
Fold 5 IBS: 0.26915674838230846
[I 2024-04-13 18:01:13,180] Trial 79 finished with value: 0.19369996403860607 and parameters: {'l1_ratio': 0.963860108593474}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790008077276719
Fold 2 IBS: 0.20300836511804662
Fold 3 IBS: 0.1747854552507615
Fold 4 IBS: 0.14249635705527072
Fold 5 IBS: 0.2691543740800689
[I 2024-04-13 18:01:14,901] Trial 80 finished with value: 0.19368907184636394 and parameters: {'l1_ratio': 0.9991294327070908}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.179012117670118
Fold 2 IBS: 0.20310481378814327
Fold 3 IBS: 0.17478170416143646
Fold 4 IBS: 0.14248148797210258
Fold 5 IBS: 0.2691615083140755
[I 2024-04-13 18:01:17,052] Trial 81 finished with value: 0.19370832638117513 and parameters: {'l1_ratio': 0.9303943298153176}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.179007351913369
Fold 2 IBS: 0.20304718585656842
Fold 3 IBS: 0.1747849169632789
Fold 4 IBS: 0.14248952816136698
Fold 5 IBS: 0.26916014637065494
[I 2024-04-13 18:01:19,625] Trial 82 finished with value: 0.19369782585304765 and parameters: {'l1_ratio': 0.9673387561687731}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900559582490938
Fold 2 IBS: 0.20309463965420543
Fold 3 IBS: 0.17478667062969966
Fold 4 IBS: 0.1424781853007324
Fold 5 IBS: 0.2691738769226772
[I 2024-04-13 18:01:21,902] Trial 83 finished with value: 0.1937077936664448 and parameters: {'l1_ratio': 0.9049387425244926}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900061334428108
Fold 2 IBS: 0.20301284469331343
Fold 3 IBS: 0.17478488221027674
Fold 4 IBS: 0.14249610683071595
Fold 5 IBS: 0.269153569130123
[I 2024-04-13 18:01:24,573] Trial 84 finished with value: 0.19368960324174203 and parameters: {'l1_ratio': 0.9983441810983122}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17902830974135664
Fold 2 IBS: 0.20335192243858366
Fold 3 IBS: 0.17482511373164392
Fold 4 IBS: 0.14244547718048303
Fold 5 IBS: 0.26930109086086873
[I 2024-04-13 18:01:28,183] Trial 85 finished with value: 0.1937903827905872 and parameters: {'l1_ratio': 0.24594453766515667}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17901301621382196
Fold 2 IBS: 0.203085423656994
Fold 3 IBS: 0.1747841327111208
Fold 4 IBS: 0.14248254943722172
Fold 5 IBS: 0.26916492920481466
[I 2024-04-13 18:01:30,856] Trial 86 finished with value: 0.19370601024479464 and parameters: {'l1_ratio': 0.9340465905634068}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17901143988095408
Fold 2 IBS: 0.20310841859139162
Fold 3 IBS: 0.1747883368535093
Fold 4 IBS: 0.1424739298587611
Fold 5 IBS: 0.269214040803992
[I 2024-04-13 18:01:33,702] Trial 87 finished with value: 0.1937192331977216 and parameters: {'l1_ratio': 0.8739235588778932}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790326668524974
Fold 2 IBS: 0.20321783481943292
Fold 3 IBS: 0.17482047793625907
Fold 4 IBS: 0.14244797149382316
Fold 5 IBS: 0.2692911044617248
[I 2024-04-13 18:01:37,135] Trial 88 finished with value: 0.19376201111274746 and parameters: {'l1_ratio': 0.37596191424171654}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17901443220913746
Fold 2 IBS: 0.2031628420479306
Fold 3 IBS: 0.17480502818668103
Fold 4 IBS: 0.14247312936547424
Fold 5 IBS: 0.2692130745595046
[I 2024-04-13 18:01:39,278] Trial 89 finished with value: 0.19373370127374556 and parameters: {'l1_ratio': 0.8336725708733272}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900068668195837
Fold 2 IBS: 0.20301115489492272
Fold 3 IBS: 0.17478509826965374
Fold 4 IBS: 0.1424962011703196
Fold 5 IBS: 0.2691538726507269
[I 2024-04-13 18:01:41,032] Trial 90 finished with value: 0.19368940273351626 and parameters: {'l1_ratio': 0.9986402458214408}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790085621620743
Fold 2 IBS: 0.2030201079856304
Fold 3 IBS: 0.1747883576723852
Fold 4 IBS: 0.1424910256629017
Fold 5 IBS: 0.269164896971782
[I 2024-04-13 18:01:43,461] Trial 91 finished with value: 0.19369459009095472 and parameters: {'l1_ratio': 0.9722977532686576}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900237587365433
Fold 2 IBS: 0.20314647469932995
Fold 3 IBS: 0.17479313762361506
Fold 4 IBS: 0.14248709853187233
Fold 5 IBS: 0.2691774998931893
[I 2024-04-13 18:01:45,841] Trial 92 finished with value: 0.1937213173243322 and parameters: {'l1_ratio': 0.9476289524997079}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17900896989551923
Fold 2 IBS: 0.20301096731588672
Fold 3 IBS: 0.17478952651048002
Fold 4 IBS: 0.14249153476453505
Fold 5 IBS: 0.26916653784495287
[I 2024-04-13 18:01:47,503] Trial 93 finished with value: 0.19369350726627474 and parameters: {'l1_ratio': 0.9739836328881986}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.17899962967985805
Fold 2 IBS: 0.20303547793905466
Fold 3 IBS: 0.1747820004804744
Fold 4 IBS: 0.1424948491636482
Fold 5 IBS: 0.2691496030344924
[I 2024-04-13 18:01:49,061] Trial 94 finished with value: 0.19369231205950554 and parameters: {'l1_ratio': 0.9943961190833396}. Best is trial 47 with value: 0.19368905329951516.
Fold 1 IBS: 0.1790008368366055
Fold 2 IBS: 0.20300769410157032
Fold 3 IBS: 0.17478554116589856
Fold 4 IBS: 0.14249639457485
Fold 5 IBS: 0.2691544947489223
[I 2024-04-13 18:01:50,704] Trial 95 finished with value: 0.19368899228556932 and parameters: {'l1_ratio': 0.9992471693779538}. Best is trial 95 with value: 0.19368899228556932.
Fold 1 IBS: 0.1790018811920931
Fold 2 IBS: 0.20302408109823203
Fold 3 IBS: 0.1747918791181988
Fold 4 IBS: 0.14248655161189658
Fold 5 IBS: 0.26917581625862125
[I 2024-04-13 18:01:52,295] Trial 96 finished with value: 0.19369604185580838 and parameters: {'l1_ratio': 0.9457268047169415}. Best is trial 95 with value: 0.19368899228556932.
Fold 1 IBS: 0.17900382646517532
Fold 2 IBS: 0.2031287290658217
Fold 3 IBS: 0.17478244693751344
Fold 4 IBS: 0.1424810482599923
Fold 5 IBS: 0.269202035870157
[I 2024-04-13 18:01:54,211] Trial 97 finished with value: 0.19371961731973195 and parameters: {'l1_ratio': 0.8983343547684316}. Best is trial 95 with value: 0.19368899228556932.
Fold 1 IBS: 0.17901041289323902
Fold 2 IBS: 0.20314171403714434
Fold 3 IBS: 0.17477715504030164
Fold 4 IBS: 0.14248396121898205
Fold 5 IBS: 0.26919042265494314
[I 2024-04-13 18:01:55,902] Trial 98 finished with value: 0.19372073316892205 and parameters: {'l1_ratio': 0.9235645480125243}. Best is trial 95 with value: 0.19368899228556932.
Fold 1 IBS: 0.17900715703172804
Fold 2 IBS: 0.20305141739733215
Fold 3 IBS: 0.17478436688388674
Fold 4 IBS: 0.14248866626314619
Fold 5 IBS: 0.26915937296241155
[I 2024-04-13 18:01:57,556] Trial 99 finished with value: 0.19369819610770095 and parameters: {'l1_ratio': 0.9665464440039804}. Best is trial 95 with value: 0.19368899228556932.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.19368899228556932], datetime_start=datetime.datetime(2024, 4, 13, 18, 1, 49, 66779), datetime_complete=datetime.datetime(2024, 4, 13, 18, 1, 50, 704213), params={'l1_ratio': 0.9992471693779538}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=95, value=None)


* Best Score for IBS:
 0.19368899228556932

In [51]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [52]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.756
train_ibs:  0.194

#### Test

In [53]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [54]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.050990548882846466)

test_cindex : 0.589

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.9992471693779538)

test_ibs:  0.232

In [55]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [56]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:01:58,356] A new study created in memory with name: no-name-add86d19-4f9f-48a1-8ff8-21a1fb86e7bd

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7424242424242424
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8713080168776371
Fold 5 C-index: 0.6737089201877934
[I 2024-04-13 18:02:10,907] Trial 0 finished with value: 0.7658565832368702 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6688311688311688
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.7058823529411765
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6995305164319249
[I 2024-04-13 18:02:21,273] Trial 1 finished with value: 0.7189363603834701 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.6838235294117647
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.704225352112676
[I 2024-04-13 18:02:29,404] Trial 2 finished with value: 0.7127901286529621 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:02:31,895] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:02:35,563] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.6901408450704225
[I 2024-04-13 18:02:48,095] Trial 5 finished with value: 0.7371681299466739 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6731601731601732
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.6813725490196079
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6267605633802817
[I 2024-04-13 18:03:00,395] Trial 6 finished with value: 0.7059783677810904 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:03:06,352] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6032863849765259
[I 2024-04-13 18:03:22,223] Trial 8 finished with value: 0.5206572769953052 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.6696428571428571
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.890295358649789
Fold 5 C-index: 0.6807511737089202
[I 2024-04-13 18:03:30,600] Trial 9 finished with value: 0.7350235412565649 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:03:31,645] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6385281385281385
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.6887254901960784
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 18:03:43,075] Trial 11 finished with value: 0.7048401211892398 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 386, 'oob_score': False, 'max_samples': 0.7819966138938776, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17782839593648317, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:03:57,916] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6341991341991342
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.7083333333333334
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.6549295774647887
[I 2024-04-13 18:04:08,144] Trial 13 finished with value: 0.705341188384623 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20243052390700345, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6385281385281385
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.8059071729957806
Fold 5 C-index: 0.7089201877934272
[I 2024-04-13 18:04:10,096] Trial 14 finished with value: 0.7295681586869988 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.6445886658470172, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09295212529598271, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:04:20,598] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.4000046030949549, 'max_features': None, 'min_weight_fraction_leaf': 0.23120758083264345, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.

Fold 1 C-index: 0.6385281385281385
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7083333333333334
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6291079812206573
[I 2024-04-13 18:04:25,880] Trial 16 finished with value: 0.7029809611408382 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.5506605211937063, 'max_features': None, 'min_weight_fraction_leaf': 0.00014872775190403337, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6103896103896104
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.6225490196078431
Fold 4 C-index: 0.689873417721519
Fold 5 C-index: 0.6314553990610329
[I 2024-04-13 18:04:30,089] Trial 17 finished with value: 0.6563892036417154 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8459339712389332, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': False}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7279411764705882
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.715962441314554
[I 2024-04-13 18:04:40,948] Trial 18 finished with value: 0.7499356156059079 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 431, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0909268924229721, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7206572769953051
[I 2024-04-13 18:04:52,658] Trial 19 finished with value: 0.751625792316797 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.9936509885949958, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.127876827130375, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6601731601731602
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7394366197183099
[I 2024-04-13 18:05:01,499] Trial 20 finished with value: 0.7505224904958985 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.9939957208203285, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.132387776410593, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8058035714285714
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7300469483568075
[I 2024-04-13 18:05:08,772] Trial 21 finished with value: 0.7506500851325149 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.8633430509996163, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14425730627158498, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7279411764705882
Fold 4 C-index: 0.8185654008438819
Fold 5 C-index: 0.7488262910798122
[I 2024-04-13 18:05:16,301] Trial 22 finished with value: 0.7592424394797221 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8490408791135752, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23370664661241383, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6298701298701299
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.7573839662447257
Fold 5 C-index: 0.6901408450704225
[I 2024-04-13 18:05:26,047] Trial 23 finished with value: 0.7161179938392965 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.7026509113834132, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2504370920378234, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.8013392857142857
Fold 3 C-index: 0.7181372549019608
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.7323943661971831
[I 2024-04-13 18:05:37,664] Trial 24 finished with value: 0.750741324767804 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 3, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 445, 'oob_score': True, 'max_samples': 0.8241004684874889, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1850210163398952, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.715962441314554
[I 2024-04-13 18:05:46,161] Trial 25 finished with value: 0.7506919624484423 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 462, 'oob_score': True, 'max_samples': 0.9070326964979241, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22459845073608742, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:05:53,310] Trial 26 finished with value: 0.748951692907507 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.7132205441848923, 'max_features': None, 'min_weight_fraction_leaf': 0.28362326643592495, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.6691176470588235
Fold 4 C-index: 0.7383966244725738
Fold 5 C-index: 0.6408450704225352
[I 2024-04-13 18:05:59,462] Trial 27 finished with value: 0.6887844225033406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.9447265001175396, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.39828535760223993, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7206572769953051
[I 2024-04-13 18:06:10,068] Trial 28 finished with value: 0.7529895656742412 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 473, 'oob_score': True, 'max_samples': 0.8128194981094562, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2064030622647233, 'warm_start': True}. Best is trial 0 with value: 0.7658565832368702.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7065727699530516
[I 2024-04-13 18:06:15,330] Trial 29 finished with value: 0.7685603760823929 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 251, 'oob_score': True, 'max_samples': 0.7300896280852288, 'max_features': None, 'min_weight_fraction_leaf': 0.20547962121975982, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:06:19,581] Trial 30 finished with value: 0.7492371235354544 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.7083144093832134, 'max_features': None, 'min_weight_fraction_leaf': 0.272071393711391, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.

Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.687793427230047
[I 2024-04-13 18:06:23,804] Trial 31 finished with value: 0.7641730265219104 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.7987771976681688, 'max_features': None, 'min_weight_fraction_leaf': 0.21375919595874837, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.8102678571428571
Fold 3 C-index: 0.6936274509803921
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.7347417840375586
[I 2024-04-13 18:06:27,865] Trial 32 finished with value: 0.7390913287834138 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.7603792028308581, 'max_features': None, 'min_weight_fraction_leaf': 0.16675548072877652, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:06:30,603] Trial 33 finished with value: 0.7501029244012554 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 143, 'oob_score': True, 'max_samples': 0.6665608919243252, 'max_features': None, 'min_weight_fraction_leaf': 0.22944898787325899, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:06:35,094] Trial 34 finished with value: 0.7477299521649857 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.8359433667773687, 'max_features': None, 'min_weight_fraction_leaf': 0.3146467431264981, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:06:42,069] Trial 35 finished with value: 0.7676646536465119 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.7345217743271941, 'max_features': None, 'min_weight_fraction_leaf': 0.2034838909465514, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:06:44,748] Trial 36 finished with value: 0.7475591128281001 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 322, 'oob_score': False, 'max_samples': 0.5379077316530604, 'max_features': None, 'min_weight_fraction_leaf': 0.1998111623883802, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.6277056277056277
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.6764705882352942
Fold 4 C-index: 0.7932489451476793
Fold 5 C-index: 0.744131455399061
[I 2024-04-13 18:06:49,197] Trial 37 finished with value: 0.7272398947261038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.7241856461969973, 'max_features': None, 'min_weight_fraction_leaf': 0.10505800659517792, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6338028169014085
[I 2024-04-13 18:06:55,374] Trial 38 finished with value: 0.7459076540347253 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.5911371577285531, 'max_features': None, 'min_weight_fraction_leaf': 0.16067007081096313, 'warm_start': False}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:07:00,876] Trial 39 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 290, 'oob_score': True, 'max_samples': 0.6674903333523107, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33727075283698127, 'warm_start': True}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6643192488262911
[I 2024-04-13 18:07:10,438] Trial 40 finished with value: 0.7472918260766113 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 17, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.7928043594387204, 'max_features': None, 'min_weight_fraction_leaf': 0.2768564589660503, 'warm_start': False}. Best is trial 29 with value: 0.7685603760823929.
Fold 1 C-index: 0.7272727272727273
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:07:16,592] Trial 41 finished with value: 0.7694118082045376 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 371, 'oob_score': True, 'max_samples': 0.8854850210753495, 'max_features': None, 'min_weight_fraction_leaf': 0.24042140144972785, 'warm_start': True}. Best is trial 41 with value: 0.7694118082045376.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:07:22,332] Trial 42 finished with value: 0.7673244960069312 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.899787531526231, 'max_features': None, 'min_weight_fraction_leaf': 0.2531378425453351, 'warm_start': True}. Best is trial 41 with value: 0.7694118082045376.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7065727699530516
[I 2024-04-13 18:07:29,338] Trial 43 finished with value: 0.7691651634518861 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 375, 'oob_score': True, 'max_samples': 0.9388551492979577, 'max_features': None, 'min_weight_fraction_leaf': 0.25524492531623943, 'warm_start': True}. Best is trial 41 with value: 0.7694118082045376.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7589285714285714
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6971830985915493
[I 2024-04-13 18:07:35,895] Trial 44 finished with value: 0.7386532165987191 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 374, 'oob_score': True, 'max_samples': 0.8970760978107303, 'max_features': None, 'min_weight_fraction_leaf': 0.25591336155079925, 'warm_start': True}. Best is trial 41 with value: 0.7694118082045376.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:07:41,955] Trial 45 finished with value: 0.7492371235354544 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 328, 'oob_score': True, 'max_samples': 0.9364299082940268, 'max_features': None, 'min_weight_fraction_leaf': 0.312155155291846, 'warm_start': True}. Best is trial 41 with value: 0.7694118082045376.

Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.71875
Fold 3 C-index: 0.8284313725490197
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.7018779342723005
[I 2024-04-13 18:07:48,441] Trial 46 finished with value: 0.7673854270390955 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 292, 'oob_score': True, 'max_samples': 0.8992697160665247, 'max_features': None, 'min_weight_fraction_leaf': 0.2909869067444449, 'warm_start': True}. Best is trial 41 with value: 0.7694118082045376.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7700892857142857
Fold 3 C-index: 0.6887254901960784
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 18:07:54,512] Trial 47 finished with value: 0.6957096889023846 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.8805663499438195, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.36926074151472277, 'warm_start': True}. Best is trial 41 with value: 0.7694118082045376.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.7206572769953051
[I 2024-04-13 18:08:03,057] Trial 48 finished with value: 0.7699619602131846 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 423, 'oob_score': True, 'max_samples': 0.9695045413401817, 'max_features': None, 'min_weight_fraction_leaf': 0.30147164105486174, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.6341991341991342
Fold 2 C-index: 0.7991071428571429
Fold 3 C-index: 0.7009803921568627
Fold 4 C-index: 0.8037974683544303
Fold 5 C-index: 0.7323943661971831
[I 2024-04-13 18:08:11,706] Trial 49 finished with value: 0.7340957007529505 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 17, 'n_estimators': 411, 'oob_score': True, 'max_samples': 0.9590885514660845, 'max_features': None, 'min_weight_fraction_leaf': 0.18185958721086334, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:08:17,296] Trial 50 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.1200736185519305, 'max_features': None, 'min_weight_fraction_leaf': 0.33175621027986, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 18:08:17,855] Trial 51 finished with value: 0.6975692731548933 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 1, 'oob_score': True, 'max_samples': 0.9275164239061681, 'max_features': None, 'min_weight_fraction_leaf': 0.29572529881832954, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7065727699530516
[I 2024-04-13 18:08:26,140] Trial 52 finished with value: 0.7685365028967551 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 401, 'oob_score': True, 'max_samples': 0.963918905690617, 'max_features': None, 'min_weight_fraction_leaf': 0.2881741404622818, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:08:35,922] Trial 53 finished with value: 0.7502711067165646 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.9519229084442155, 'max_features': None, 'min_weight_fraction_leaf': 0.35956281063074663, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.7181372549019608
Fold 4 C-index: 0.879746835443038
Fold 5 C-index: 0.7347417840375586
[I 2024-04-13 18:08:43,668] Trial 54 finished with value: 0.7608839411102777 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.9681779411643369, 'max_features': None, 'min_weight_fraction_leaf': 0.23823427572566283, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.6838235294117647
Fold 4 C-index: 0.7869198312236287
Fold 5 C-index: 0.7300469483568075
[I 2024-04-13 18:08:52,975] Trial 55 finished with value: 0.7345979968633752 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 425, 'oob_score': True, 'max_samples': 0.856801543299631, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2638115812701286, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:09:00,513] Trial 56 finished with value: 0.7473347721315141 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 350, 'oob_score': True, 'max_samples': 0.748370688237636, 'max_features': None, 'min_weight_fraction_leaf': 0.3191963338184487, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.6515151515151515
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.7511737089201878
[I 2024-04-13 18:09:08,251] Trial 57 finished with value: 0.7493822877414308 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 429, 'oob_score': True, 'max_samples': 0.9990230844370127, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1852252405610569, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:09:16,815] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.9231510185550938, 'max_features': None, 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:09:25,517] Trial 59 finished with value: 0.5 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.45215017757926323, 'max_features': None, 'min_weight_fraction_leaf': 0.2403795176512152, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.6515151515151515
Fold 2 C-index: 0.7834821428571429
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.7605633802816901
[I 2024-04-13 18:09:33,525] Trial 60 finished with value: 0.7471600376361829 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 439, 'oob_score': True, 'max_samples': 0.8699212581153903, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1478483729810709, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.

Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:09:41,337] Trial 61 finished with value: 0.7492371235354544 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.8848144549171937, 'max_features': None, 'min_weight_fraction_leaf': 0.2921112875512147, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:09:47,547] Trial 62 finished with value: 0.7698831978536078 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.9763992519178185, 'max_features': None, 'min_weight_fraction_leaf': 0.26808385302861754, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7065727699530516
[I 2024-04-13 18:09:55,044] Trial 63 finished with value: 0.7689224527312343 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 338, 'oob_score': True, 'max_samples': 0.9625772765411387, 'max_features': None, 'min_weight_fraction_leaf': 0.2686611012578494, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:10:04,191] Trial 64 finished with value: 0.7645281501958796 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 410, 'oob_score': True, 'max_samples': 0.978922991948887, 'max_features': None, 'min_weight_fraction_leaf': 0.27550927785909574, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8235294117647058
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.7065727699530516
[I 2024-04-13 18:10:09,732] Trial 65 finished with value: 0.7651524435768245 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.9238979862590739, 'max_features': None, 'min_weight_fraction_leaf': 0.30629347218314645, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8137254901960784
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:10:17,622] Trial 66 finished with value: 0.7689685627245274 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.965687744632506, 'max_features': None, 'min_weight_fraction_leaf': 0.2622201933595522, 'warm_start': True}. Best is trial 48 with value: 0.7699619602131846.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7433035714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7300469483568075
[I 2024-04-13 18:10:22,102] Trial 67 finished with value: 0.7703612780101262 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.9565500224976435, 'max_features': None, 'min_weight_fraction_leaf': 0.2608483862052085, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.6515151515151515
Fold 2 C-index: 0.8169642857142857
Fold 3 C-index: 0.6936274509803921
Fold 4 C-index: 0.8164556962025317
Fold 5 C-index: 0.7488262910798122
[I 2024-04-13 18:10:25,979] Trial 68 finished with value: 0.7454777750984347 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.999269912478451, 'max_features': None, 'min_weight_fraction_leaf': 0.2597087313931063, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.6320346320346321
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.6691176470588235
Fold 4 C-index: 0.7320675105485233
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 18:10:33,533] Trial 69 finished with value: 0.6812645984381207 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 159, 'oob_score': True, 'max_samples': 0.9578086610386422, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.34868753763319615, 'warm_start': False}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.6233766233766234
Fold 2 C-index: 0.7901785714285714
Fold 3 C-index: 0.7034313725490197
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.7488262910798122
[I 2024-04-13 18:10:38,618] Trial 70 finished with value: 0.739829238353472 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.9128556377610024, 'max_features': None, 'min_weight_fraction_leaf': 0.2207214843253411, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.7337662337662337
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8333333333333334
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.7065727699530516
[I 2024-04-13 18:10:43,706] Trial 71 finished with value: 0.7701654499301138 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 261, 'oob_score': True, 'max_samples': 0.8296091151090681, 'max_features': None, 'min_weight_fraction_leaf': 0.24298682614657147, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.7924107142857143
Fold 3 C-index: 0.7107843137254902
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.7394366197183099
[I 2024-04-13 18:10:49,689] Trial 72 finished with value: 0.7532663152985469 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 312, 'oob_score': True, 'max_samples': 0.9400021934989804, 'max_features': None, 'min_weight_fraction_leaf': 0.23979315153736, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.704225352112676
[I 2024-04-13 18:10:56,464] Trial 73 finished with value: 0.7668927507144448 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.8222517417092329, 'max_features': None, 'min_weight_fraction_leaf': 0.2674542468481606, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:11:00,656] Trial 74 finished with value: 0.7492005404002797 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.8721424280086124, 'max_features': None, 'min_weight_fraction_leaf': 0.32361765295273615, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.6774891774891775
Fold 2 C-index: 0.7946428571428571
Fold 3 C-index: 0.7205882352941176
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7394366197183099
[I 2024-04-13 18:11:05,202] Trial 75 finished with value: 0.7547858083086393 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.9740955002788919, 'max_features': None, 'min_weight_fraction_leaf': 0.2501167804665548, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.

Fold 1 C-index: 0.6558441558441559
Fold 2 C-index: 0.8147321428571429
Fold 3 C-index: 0.7132352941176471
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.7300469483568075
[I 2024-04-13 18:11:11,015] Trial 76 finished with value: 0.7477506111887371 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.8475209627412346, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.21856153923575045, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.7065727699530516
[I 2024-04-13 18:11:14,433] Trial 77 finished with value: 0.7650378522857626 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.9404135972875768, 'max_features': None, 'min_weight_fraction_leaf': 0.3029361675555098, 'warm_start': True}. Best is trial 67 with value: 0.7703612780101262.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7142857142857143
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.715962441314554
[I 2024-04-13 18:11:22,475] Trial 78 finished with value: 0.7714057183190299 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.9071879924350505, 'max_features': None, 'min_weight_fraction_leaf': 0.2767214759009209, 'warm_start': True}. Best is trial 78 with value: 0.7714057183190299.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:11:40,532] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 462, 'oob_score': True, 'max_samples': 0.33040395664789457, 'max_features': None, 'min_weight_fraction_leaf': 0.24435632684413805, 'warm_start': False}. Best is trial 78 with value: 0.7714057183190299.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.715962441314554
[I 2024-04-13 18:11:49,453] Trial 80 finished with value: 0.7727450040333156 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.9092320833572134, 'max_features': None, 'min_weight_fraction_leaf': 0.2776225889618983, 'warm_start': True}. Best is trial 80 with value: 0.7727450040333156.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7206572769953051
[I 2024-04-13 18:11:58,449] Trial 81 finished with value: 0.7744622370212612 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.9157070212716846, 'max_features': None, 'min_weight_fraction_leaf': 0.28086863940091983, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7316017316017316
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.8259803921568627
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.715962441314554
[I 2024-04-13 18:12:06,642] Trial 82 finished with value: 0.7727450040333156 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.9117330530840405, 'max_features': None, 'min_weight_fraction_leaf': 0.27924052837933727, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:12:14,784] Trial 83 finished with value: 0.7470116211041378 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.7831339819703007, 'max_features': None, 'min_weight_fraction_leaf': 0.2807773706602148, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7380952380952381
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.821078431372549
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:12:22,502] Trial 84 finished with value: 0.7725707746104326 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 452, 'oob_score': True, 'max_samples': 0.9070770285833184, 'max_features': None, 'min_weight_fraction_leaf': 0.2843403052354842, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:12:30,640] Trial 85 finished with value: 0.7492371235354544 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 490, 'oob_score': True, 'max_samples': 0.9089500490571759, 'max_features': None, 'min_weight_fraction_leaf': 0.30378601144463907, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:12:38,417] Trial 86 finished with value: 0.7492371235354544 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 449, 'oob_score': True, 'max_samples': 0.8376820264301911, 'max_features': None, 'min_weight_fraction_leaf': 0.2853552305189536, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6643192488262911
[I 2024-04-13 18:12:42,410] Trial 87 finished with value: 0.7501443494219678 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 472, 'oob_score': False, 'max_samples': 0.8145573670344342, 'max_features': None, 'min_weight_fraction_leaf': 0.326777198593039, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:12:50,756] Trial 88 finished with value: 0.7510285895464849 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 500, 'oob_score': True, 'max_samples': 0.8610227609969661, 'max_features': None, 'min_weight_fraction_leaf': 0.34679430576959414, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.6082251082251082
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.6715686274509803
Fold 4 C-index: 0.7362869198312236
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 18:12:59,751] Trial 89 finished with value: 0.6849796287540446 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 477, 'oob_score': True, 'max_samples': 0.8930530795749407, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3818062696280202, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.5758928571428571
Fold 3 C-index: 0.8161764705882353
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:13:17,953] Trial 90 finished with value: 0.7337119756491066 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 459, 'oob_score': True, 'max_samples': 0.9205669668233029, 'max_features': None, 'min_weight_fraction_leaf': 0.27870094509075405, 'warm_start': False}. Best is trial 81 with value: 0.7744622370212612.

Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.6924882629107981
[I 2024-04-13 18:13:25,556] Trial 91 finished with value: 0.7641363056268067 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.8755007393403584, 'max_features': None, 'min_weight_fraction_leaf': 0.22758195695403124, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:13:32,892] Trial 92 finished with value: 0.7487676399673793 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 464, 'oob_score': True, 'max_samples': 0.8914522384016942, 'max_features': None, 'min_weight_fraction_leaf': 0.3133091192418996, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:13:41,257] Trial 93 finished with value: 0.7492371235354544 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 485, 'oob_score': True, 'max_samples': 0.9125922770004414, 'max_features': None, 'min_weight_fraction_leaf': 0.29875595255132836, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.7745535714285714
Fold 3 C-index: 0.7426470588235294
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.7582159624413145
[I 2024-04-13 18:13:48,830] Trial 94 finished with value: 0.7610891270761371 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 438, 'oob_score': True, 'max_samples': 0.9877488349591033, 'max_features': None, 'min_weight_fraction_leaf': 0.1952079968546946, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.8112745098039216
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.7112676056338029
[I 2024-04-13 18:13:57,209] Trial 95 finished with value: 0.7701847957654999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 454, 'oob_score': True, 'max_samples': 0.9484776096682963, 'max_features': None, 'min_weight_fraction_leaf': 0.24878197849238956, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.6861471861471862
Fold 2 C-index: 0.796875
Fold 3 C-index: 0.7230392156862745
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.7347417840375586
[I 2024-04-13 18:14:04,557] Trial 96 finished with value: 0.7501859536299 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 425, 'oob_score': True, 'max_samples': 0.9402848345982121, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2696690569238423, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.78125
Fold 3 C-index: 0.7156862745098039
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.7300469483568075
[I 2024-04-13 18:14:07,011] Trial 97 finished with value: 0.7543998776271883 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 118, 'oob_score': True, 'max_samples': 0.9770898775185285, 'max_features': None, 'min_weight_fraction_leaf': 0.24955509151767616, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.7359307359307359
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.715962441314554
[I 2024-04-13 18:14:14,386] Trial 98 finished with value: 0.7688646342789698 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 450, 'oob_score': True, 'max_samples': 0.9477316655698517, 'max_features': None, 'min_weight_fraction_leaf': 0.28034340902508587, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.
Fold 1 C-index: 0.6645021645021645
Fold 2 C-index: 0.8191964285714286
Fold 3 C-index: 0.7181372549019608
Fold 4 C-index: 0.8312236286919831

[I 2024-04-13 18:14:22,477] A new study created in memory with name: no-name-5081c397-625c-4ba1-89c8-32410d7c0249

Fold 5 C-index: 0.7417840375586855
[I 2024-04-13 18:14:22,458] Trial 99 finished with value: 0.7549687028452444 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 482, 'oob_score': True, 'max_samples': 0.8344966669570604, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21318534707407957, 'warm_start': True}. Best is trial 81 with value: 0.7744622370212612.


* Best trial for C-index:
 FrozenTrial(number=81, state=TrialState.COMPLETE, values=[0.7744622370212612], datetime_start=datetime.datetime(2024, 4, 13, 18, 11, 49, 487540), datetime_complete=datetime.datetime(2024, 4, 13, 18, 11, 58, 448967), params={'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.9157070212716846, 'max_features': None, 'min_weight_fraction_leaf': 0.28086863940091983, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=81, value=None)


* Best Score for C-index:
 0.7744622370212612

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17552372172032427
Fold 2 IBS: 0.24687605677534413
Fold 3 IBS: 0.1785874023605988
Fold 4 IBS: 0.16240186800780074
Fold 5 IBS: 0.26250140355841234
[I 2024-04-13 18:14:33,999] Trial 0 finished with value: 0.20517809048449606 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.20517809048449606.
Fold 1 IBS: 0.19647710555094255
Fold 2 IBS: 0.20108466323146856
Fold 3 IBS: 0.1846739598340064
Fold 4 IBS: 0.18681682025974364
Fold 5 IBS: 0.2166235133930879
[I 2024-04-13 18:14:37,933] Trial 1 finished with value: 0.19713521245384982 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.19713521245384982.
Fold 1 IBS: 0.2139937557482124
Fold 2 IBS: 0.22188477784001379
Fold 3 IBS: 0.20416384807663968
Fold 4 IBS: 0.22524515169868858
Fold 5 IBS: 0.2179383549994646
[I 2024-04-13 18:14:40,189] Trial 2 finished with value: 0.2166451776726038 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.19713521245384982.
Fold 1 IBS: 0.21403316904964845
Fold 2 IBS: 0.2215601576922312
Fold 3 IBS: 0.20489673579680445
Fold 4 IBS: 0.2247331970208897
Fold 5 IBS: 0.21840225097702878
[I 2024-04-13 18:14:48,600] Trial 3 finished with value: 0.21672510210732052 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.19713521245384982.
Fold 1 IBS: 0.2140305612908134
Fold 2 IBS: 0.22159893571829403
Fold 3 IBS: 0.20489625174352644
Fold 4 IBS: 0.22471096181034556
Fold 5 IBS: 0.21849803650738384
[I 2024-04-13 18:14:57,456] Trial 4 finished with value: 0.21674694941407266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.19713521245384982.
Fold 1 IBS: 0.18852187909011575
Fold 2 IBS: 0.20996901908835522
Fold 3 IBS: 0.18449889292059415
Fold 4 IBS: 0.15814984962677794
Fold 5 IBS: 0.22993426736378744
[I 2024-04-13 18:15:06,074] Trial 5 finished with value: 0.1942147816179261 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.1771980200515147
Fold 2 IBS: 0.22006118116468573
Fold 3 IBS: 0.1811470554025649
Fold 4 IBS: 0.18471402776474355
Fold 5 IBS: 0.2204804703222885
[I 2024-04-13 18:15:15,292] Trial 6 finished with value: 0.1967201509411595 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.21416710956312388
Fold 2 IBS: 0.2196873993518854
Fold 3 IBS: 0.2040886444241197
Fold 4 IBS: 0.2227783977060954
Fold 5 IBS: 0.2170752688920923
[I 2024-04-13 18:15:25,340] Trial 7 finished with value: 0.21555936398746334 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.2139717543405284
Fold 2 IBS: 0.22125403379526087
Fold 3 IBS: 0.20485853329479786
Fold 4 IBS: 0.22459560806501025
Fold 5 IBS: 0.21859505869550636
[I 2024-04-13 18:15:40,979] Trial 8 finished with value: 0.21665499763822074 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.1987896514811301
Fold 2 IBS: 0.20200608055344244
Fold 3 IBS: 0.18725957709718777
Fold 4 IBS: 0.19237906881377242
Fold 5 IBS: 0.21239029474143886
[I 2024-04-13 18:15:44,380] Trial 9 finished with value: 0.19856493453739432 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.21395708715299197
Fold 2 IBS: 0.22118980337828023
Fold 3 IBS: 0.2050799845125664
Fold 4 IBS: 0.22515519619106775
Fold 5 IBS: 0.2170261763279105
[I 2024-04-13 18:16:03,534] Trial 10 finished with value: 0.21648164951256335 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19296147578895806
Fold 2 IBS: 0.2082242591043897
Fold 3 IBS: 0.18558345173990878
Fold 4 IBS: 0.18986898084346102
Fold 5 IBS: 0.21359558351380653
[I 2024-04-13 18:16:12,126] Trial 11 finished with value: 0.19804675019810483 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9878564362760905, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3071027733658521}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.17796353717209648
Fold 2 IBS: 0.21937091469446868
Fold 3 IBS: 0.18118595379075106
Fold 4 IBS: 0.1847630816979339
Fold 5 IBS: 0.22019775421263907
[I 2024-04-13 18:16:20,276] Trial 12 finished with value: 0.19669624831357785 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.831375598136572, 'max_features': None, 'min_weight_fraction_leaf': 0.34616445768228626}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19375702237113196
Fold 2 IBS: 0.20628947125864872
Fold 3 IBS: 0.184923233329183
Fold 4 IBS: 0.16827143753957033
Fold 5 IBS: 0.22770765383702096
[I 2024-04-13 18:16:25,673] Trial 13 finished with value: 0.196189763667111 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7780367789894055, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12012408817397843}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19476017929967046
Fold 2 IBS: 0.2039525493353013
Fold 3 IBS: 0.1840808070814504
Fold 4 IBS: 0.17546133417514806
Fold 5 IBS: 0.2264783347113864
[I 2024-04-13 18:16:30,443] Trial 14 finished with value: 0.19694664092059133 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 157, 'oob_score': False, 'max_samples': 0.7340982458611074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11848568472491557}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.1967038916457518
Fold 2 IBS: 0.20410260208071337
Fold 3 IBS: 0.18253642156580732
Fold 4 IBS: 0.1815896874247153
Fold 5 IBS: 0.22286689382157976
[I 2024-04-13 18:16:36,301] Trial 15 finished with value: 0.1975598993077135 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 176, 'oob_score': False, 'max_samples': 0.6433402879135517, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07260059363971005}. Best is trial 5 with value: 0.1942147816179261.

Fold 1 IBS: 0.18962549917018698
Fold 2 IBS: 0.2076479361062535
Fold 3 IBS: 0.1859185098952122
Fold 4 IBS: 0.16297267582967945
Fold 5 IBS: 0.22871527151525464
[I 2024-04-13 18:16:47,106] Trial 16 finished with value: 0.19497597850331735 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.7702473623171299, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.00939201506667553}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.18588437074618366
Fold 2 IBS: 0.21585803662904346
Fold 3 IBS: 0.18742906036276882
Fold 4 IBS: 0.15254028807746767
Fold 5 IBS: 0.23099943158383532
[I 2024-04-13 18:16:58,785] Trial 17 finished with value: 0.1945422374798598 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 359, 'oob_score': False, 'max_samples': 0.41184115950443606, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0027261845502768497}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.18738253782161157
Fold 2 IBS: 0.20871624947223646
Fold 3 IBS: 0.1827169864818855
Fold 4 IBS: 0.17617215691108323
Fold 5 IBS: 0.22159871562747693
[I 2024-04-13 18:17:14,412] Trial 18 finished with value: 0.19531732926285875 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.29354264648814793, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.1947789188322377
Fold 2 IBS: 0.20679289771575232
Fold 3 IBS: 0.1856582647996854
Fold 4 IBS: 0.19219498171708388
Fold 5 IBS: 0.2154878285224495
[I 2024-04-13 18:17:26,001] Trial 19 finished with value: 0.19898257831744176 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 410, 'oob_score': False, 'max_samples': 0.4386108822397098, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13513638481755805}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.18830148287188067
Fold 2 IBS: 0.2107497598278228
Fold 3 IBS: 0.18433734140917657
Fold 4 IBS: 0.17987465774017755
Fold 5 IBS: 0.213792035732883
[I 2024-04-13 18:17:39,317] Trial 20 finished with value: 0.1954110555163881 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.20097738776716928, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.002446857018531974}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19004382623155247
Fold 2 IBS: 0.20715008937233773
Fold 3 IBS: 0.1861274487727776
Fold 4 IBS: 0.16386555234003927
Fold 5 IBS: 0.22882306659185395
[I 2024-04-13 18:17:49,815] Trial 21 finished with value: 0.19520199666171217 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.6178629911568023, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03829904514895255}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19604470303499116
Fold 2 IBS: 0.20401349829895868
Fold 3 IBS: 0.18429309908469876
Fold 4 IBS: 0.17611829462893755
Fold 5 IBS: 0.2254607272670428
[I 2024-04-13 18:18:00,132] Trial 22 finished with value: 0.1971860644629258 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.45210922534491094, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08711500628067477}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19521368957196433
Fold 2 IBS: 0.20550720156378582
Fold 3 IBS: 0.183388124164059
Fold 4 IBS: 0.1825052478661174
Fold 5 IBS: 0.21912711612178226
[I 2024-04-13 18:18:10,920] Trial 23 finished with value: 0.19714827585754177 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 390, 'oob_score': False, 'max_samples': 0.3760365861983614, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.003781922843088023}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19839188499237195
Fold 2 IBS: 0.20465258436458886
Fold 3 IBS: 0.1842182901670121
Fold 4 IBS: 0.17603620727866895
Fold 5 IBS: 0.22385260659165152
[I 2024-04-13 18:18:19,639] Trial 24 finished with value: 0.1974303146788587 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.7813052371489524, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16187431718769785}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.18873757567964877
Fold 2 IBS: 0.20865209496079254
Fold 3 IBS: 0.18592803913147962
Fold 4 IBS: 0.1593617734733074
Fold 5 IBS: 0.23086059174320245
[I 2024-04-13 18:18:27,135] Trial 25 finished with value: 0.19470801499768614 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.49249555029072384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03209236169177276}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.19388207751945988
Fold 2 IBS: 0.20162991457439372
Fold 3 IBS: 0.18379400945341626
Fold 4 IBS: 0.17299608323498034
Fold 5 IBS: 0.22671896851688972
[I 2024-04-13 18:18:40,215] Trial 26 finished with value: 0.19580421065982798 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 204, 'oob_score': True, 'max_samples': 0.5016725581217393, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09435420004703986}. Best is trial 5 with value: 0.1942147816179261.
Fold 1 IBS: 0.18677099629267954
Fold 2 IBS: 0.20879077321949233
Fold 3 IBS: 0.18434567425976967
Fold 4 IBS: 0.16062462909156308
Fold 5 IBS: 0.22912286711740368
[I 2024-04-13 18:18:49,502] Trial 27 finished with value: 0.19393098799618166 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.337369677586095, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0435946992907518}. Best is trial 27 with value: 0.19393098799618166.
Fold 1 IBS: 0.2140425893256018
Fold 2 IBS: 0.22049697862208628
Fold 3 IBS: 0.2049347792275122
Fold 4 IBS: 0.22468785490500703
Fold 5 IBS: 0.21775170623584073
[I 2024-04-13 18:18:59,066] Trial 28 finished with value: 0.21638278166320962 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.2446896933168478, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.23600968673043138}. Best is trial 27 with value: 0.19393098799618166.
Fold 1 IBS: 0.21398540653267006
Fold 2 IBS: 0.22113524936806414
Fold 3 IBS: 0.20504294260083622
Fold 4 IBS: 0.22479100552158987
Fold 5 IBS: 0.21838582491102754
[I 2024-04-13 18:19:09,565] Trial 29 finished with value: 0.21666808578683758 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.3571755626038756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19697698521641305}. Best is trial 27 with value: 0.19393098799618166.
Fold 1 IBS: 0.21397863077431603
Fold 2 IBS: 0.2209032553042018
Fold 3 IBS: 0.205244618278275
Fold 4 IBS: 0.2246434252719254
Fold 5 IBS: 0.21736483478058732
[I 2024-04-13 18:19:21,968] Trial 30 finished with value: 0.21642695288186112 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 372, 'oob_score': False, 'max_samples': 0.14942102461546353, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15534755431912572}. Best is trial 27 with value: 0.19393098799618166.
Fold 1 IBS: 0.1850454625974252
Fold 2 IBS: 0.21711019153961636
Fold 3 IBS: 0.18654839050043193
Fold 4 IBS: 0.15179830500950117

Fold 5 IBS: 0.23185076637405122
[I 2024-04-13 18:19:29,404] Trial 31 finished with value: 0.1944706232042052 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 248, 'oob_score': False, 'max_samples': 0.5943093092467338, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.045073432551245296}. Best is trial 27 with value: 0.19393098799618166.
Fold 1 IBS: 0.19189320796178416
Fold 2 IBS: 0.2052610312293916
Fold 3 IBS: 0.1861107153615012
Fold 4 IBS: 0.16719140666147253
Fold 5 IBS: 0.22755309800616683
[I 2024-04-13 18:19:37,398] Trial 32 finished with value: 0.19560189184406326 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 255, 'oob_score': False, 'max_samples': 0.6062923942533682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09176370291993877}. Best is trial 27 with value: 0.19393098799618166.
Fold 1 IBS: 0.18633076489355724
Fold 2 IBS: 0.217904725043235
Fold 3 IBS: 0.18548945234223713
Fold 4 IBS: 0.14762195939762343
Fold 5 IBS: 0.23369727198190907
[I 2024-04-13 18:19:50,542] Trial 33 finished with value: 0.19420883473171238 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.7083524731449771, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050681546729188336}. Best is trial 27 with value: 0.19393098799618166.
Fold 1 IBS: 0.1892629440158444
Fold 2 IBS: 0.20165184641467226
Fold 3 IBS: 0.1873469924690526
Fold 4 IBS: 0.15538097798962372
Fold 5 IBS: 0.22091985804449915
[I 2024-04-13 18:19:57,339] Trial 34 finished with value: 0.19091252378673845 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 140, 'oob_score': False, 'max_samples': 0.7012702046646897, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.053360341470219855}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1931089978586135
Fold 2 IBS: 0.19892849572431118
Fold 3 IBS: 0.1863374559957587
Fold 4 IBS: 0.16516220433042308
Fold 5 IBS: 0.2227519582988725
[I 2024-04-13 18:20:03,285] Trial 35 finished with value: 0.19325782244159578 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 101, 'oob_score': True, 'max_samples': 0.6990687357279085, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10559004232142762}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1958347513227912
Fold 2 IBS: 0.19742476007882045
Fold 3 IBS: 0.17250229400500355
Fold 4 IBS: 0.15615679090649087
Fold 5 IBS: 0.2739860647363786
[I 2024-04-13 18:20:05,241] Trial 36 finished with value: 0.1991809322098969 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 20, 'oob_score': True, 'max_samples': 0.70571147380128, 'max_features': None, 'min_weight_fraction_leaf': 0.11091659563954627}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19872140102997066
Fold 2 IBS: 0.19915478859515254
Fold 3 IBS: 0.18580062415114554
Fold 4 IBS: 0.17764596447843364
Fold 5 IBS: 0.2215093825053252
[I 2024-04-13 18:20:09,533] Trial 37 finished with value: 0.19656643215200548 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.7240498407647448, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1506202838344293}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19713046435502224
Fold 2 IBS: 0.20093540196948126
Fold 3 IBS: 0.1861261347300928
Fold 4 IBS: 0.19050811043328994
Fold 5 IBS: 0.21319967048723906
[I 2024-04-13 18:20:12,735] Trial 38 finished with value: 0.19757995639502507 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 1, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.6830883188400352, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1799176597918699}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19585887388853887
Fold 2 IBS: 0.24663619375873386
Fold 3 IBS: 0.18377353254390327
Fold 4 IBS: 0.13953642647017256
Fold 5 IBS: 0.26054356497977615
[I 2024-04-13 18:20:18,433] Trial 39 finished with value: 0.2052697183282249 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 138, 'oob_score': True, 'max_samples': 0.850315218238024, 'max_features': None, 'min_weight_fraction_leaf': 0.0423852954717745}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.2176944142602045
Fold 2 IBS: 0.215946495645078
Fold 3 IBS: 0.20313557564984247
Fold 4 IBS: 0.22200187643276814
Fold 5 IBS: 0.2159028670372035
[I 2024-04-13 18:20:23,366] Trial 40 finished with value: 0.21493624580501933 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.5591790688861411, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2713991105009101}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1879981518654671
Fold 2 IBS: 0.20862721088010333
Fold 3 IBS: 0.18645331118946268
Fold 4 IBS: 0.1536501924535051
Fold 5 IBS: 0.23195943480320444
[I 2024-04-13 18:20:30,289] Trial 41 finished with value: 0.19373766023834854 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 218, 'oob_score': False, 'max_samples': 0.6668824396572224, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07003834025559996}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18713005374193037
Fold 2 IBS: 0.207918198622293
Fold 3 IBS: 0.1860018886021911
Fold 4 IBS: 0.1536785006835413
Fold 5 IBS: 0.2321703371099144
[I 2024-04-13 18:20:40,498] Trial 42 finished with value: 0.19337979575197403 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 212, 'oob_score': True, 'max_samples': 0.6730361227199791, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06998876842259748}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.21403718037644343
Fold 2 IBS: 0.22159524657354185
Fold 3 IBS: 0.20481918036232266
Fold 4 IBS: 0.22473431648640824
Fold 5 IBS: 0.21854629686479235
[I 2024-04-13 18:20:48,772] Trial 43 finished with value: 0.2167464441327017 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.6456876074737891, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.194667912330097
Fold 2 IBS: 0.20143648827696883
Fold 3 IBS: 0.18647046288631489
Fold 4 IBS: 0.15934068492704953
Fold 5 IBS: 0.23707449710686682
[I 2024-04-13 18:20:52,054] Trial 44 finished with value: 0.19579800910545941 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 76, 'oob_score': True, 'max_samples': 0.5791788257153967, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0730382590224415}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19062983898646763
Fold 2 IBS: 0.20899859055220868
Fold 3 IBS: 0.1858380088675385
Fold 4 IBS: 0.15776593626841054
Fold 5 IBS: 0.23182728748499928
[I 2024-04-13 18:21:00,564] Trial 45 finished with value: 0.1950119324319249 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 186, 'oob_score': True, 'max_samples': 0.8106776337766259, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10740277122863438}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19014091119044993
Fold 2 IBS: 0.20877391438750975
Fold 3 IBS: 0.19050931506739402
Fold 4 IBS: 0.15087350838382688
Fold 5 IBS: 0.2292740894535446
[I 2024-04-13 18:21:07,956] Trial 46 finished with value: 0.19391434769654503 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 145, 'oob_score': True, 'max_samples': 0.5291929981676499, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.022946173545516778}. Best is trial 34 with value: 0.19091252378673845.

Fold 1 IBS: 0.18831038256552204
Fold 2 IBS: 0.20330959953611447
Fold 3 IBS: 0.1851297747224047
Fold 4 IBS: 0.17704850491733026
Fold 5 IBS: 0.21187395154278196
[I 2024-04-13 18:21:14,359] Trial 47 finished with value: 0.1931344426568307 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.893618602031134, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025121977917597738}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.22231357319417014
Fold 2 IBS: 0.21299690199828966
Fold 3 IBS: 0.2020657967661787
Fold 4 IBS: 0.21789212937822908
Fold 5 IBS: 0.2150793184508971
[I 2024-04-13 18:21:18,822] Trial 48 finished with value: 0.21406954395755293 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 108, 'oob_score': True, 'max_samples': 0.9168117483275655, 'max_features': None, 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19408303831550547
Fold 2 IBS: 0.20035120690492722
Fold 3 IBS: 0.18510562952502474
Fold 4 IBS: 0.19292353876632598
Fold 5 IBS: 0.21340231662347453
[I 2024-04-13 18:21:21,064] Trial 49 finished with value: 0.19717314602705158 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.9125356050195117, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12978717926202077}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18788298081632043
Fold 2 IBS: 0.2057766837441801
Fold 3 IBS: 0.18672510677588364
Fold 4 IBS: 0.15555854536736413
Fold 5 IBS: 0.21961743323780222
[I 2024-04-13 18:21:27,737] Trial 50 finished with value: 0.1911121499883101 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.9856992496851368, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07420305310832734}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18875478637881013
Fold 2 IBS: 0.20224174466944705
Fold 3 IBS: 0.18610902075714789
Fold 4 IBS: 0.1566641359605202
Fold 5 IBS: 0.2209165667356506
[I 2024-04-13 18:21:32,497] Trial 51 finished with value: 0.19093725090031516 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 119, 'oob_score': True, 'max_samples': 0.9381349017860524, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06712275207104249}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18936941997829368
Fold 2 IBS: 0.20436465137037088
Fold 3 IBS: 0.18584261065696545
Fold 4 IBS: 0.15783574119407834
Fold 5 IBS: 0.2206677473597003
[I 2024-04-13 18:21:37,536] Trial 52 finished with value: 0.19161603411188172 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 117, 'oob_score': True, 'max_samples': 0.9695839650258227, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09635395694698896}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1883328504923177
Fold 2 IBS: 0.2029741968018816
Fold 3 IBS: 0.18439109728817427
Fold 4 IBS: 0.16190939322968942
Fold 5 IBS: 0.2204880194575864
[I 2024-04-13 18:21:42,639] Trial 53 finished with value: 0.1916191114539299 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 123, 'oob_score': True, 'max_samples': 0.9916806153010467, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10269411123392774}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18770431549015332
Fold 2 IBS: 0.19953618397513972
Fold 3 IBS: 0.1866334672486907
Fold 4 IBS: 0.17883761833797393
Fold 5 IBS: 0.21225547152141955
[I 2024-04-13 18:21:48,065] Trial 54 finished with value: 0.19299341131467546 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.9882515377195807, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02882658084020792}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19012306446475313
Fold 2 IBS: 0.20492965044639397
Fold 3 IBS: 0.18149712940622054
Fold 4 IBS: 0.166633698426558
Fold 5 IBS: 0.2208816717163389
[I 2024-04-13 18:21:54,354] Trial 55 finished with value: 0.19281304289205292 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.9966354832403584, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14116804383792317}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.192444685159226
Fold 2 IBS: 0.2049198357948083
Fold 3 IBS: 0.18162368638572832
Fold 4 IBS: 0.1692772921401002
Fold 5 IBS: 0.22196198896123384
[I 2024-04-13 18:22:00,569] Trial 56 finished with value: 0.19404549768821935 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 162, 'oob_score': True, 'max_samples': 0.9540596381236248, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13940915214891378}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.2000837549058867
Fold 2 IBS: 0.2016148875219945
Fold 3 IBS: 0.18286097596739692
Fold 4 IBS: 0.18207329807811534
Fold 5 IBS: 0.22194944005559553
[I 2024-04-13 18:22:03,556] Trial 57 finished with value: 0.1977164713057978 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 63, 'oob_score': True, 'max_samples': 0.9459341835963234, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2166088657032461}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18790580230184992
Fold 2 IBS: 0.19596935305104887
Fold 3 IBS: 0.1865806227738511
Fold 4 IBS: 0.1781100503031002
Fold 5 IBS: 0.21206624353742337
[I 2024-04-13 18:22:07,226] Trial 58 finished with value: 0.19212641439345468 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 89, 'oob_score': True, 'max_samples': 0.9533869250576935, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08889565659687755}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.20352424015721243
Fold 2 IBS: 0.20336775697656373
Fold 3 IBS: 0.18671959363754767
Fold 4 IBS: 0.213704836601293
Fold 5 IBS: 0.2129476100959287
[I 2024-04-13 18:22:08,011] Trial 59 finished with value: 0.20405280749370913 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 19, 'n_estimators': 10, 'oob_score': True, 'max_samples': 0.8762646217559431, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19045490131264523
Fold 2 IBS: 0.2167681555328052
Fold 3 IBS: 0.18451180099725137
Fold 4 IBS: 0.1488539706606624
Fold 5 IBS: 0.23857059765153008
[I 2024-04-13 18:22:11,285] Trial 60 finished with value: 0.19583188523097889 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.9557433246868419, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09165170445184322}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18855911786876692
Fold 2 IBS: 0.1976960758827471
Fold 3 IBS: 0.18765478123723367
Fold 4 IBS: 0.1790657695772058
Fold 5 IBS: 0.21165770699053776
[I 2024-04-13 18:22:15,760] Trial 61 finished with value: 0.19292669031129825 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 116, 'oob_score': True, 'max_samples': 0.9990391682066126, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12328019148829496}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19076759813986766
Fold 2 IBS: 0.2061026131423801
Fold 3 IBS: 0.1818142764523251
Fold 4 IBS: 0.16510890370908987
Fold 5 IBS: 0.22089713550480636
[I 2024-04-13 18:22:22,093] Trial 62 finished with value: 0.19293810538969383 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.9491395957283582, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06376516833339917}. Best is trial 34 with value: 0.19091252378673845.

Fold 1 IBS: 0.18940722653110123
Fold 2 IBS: 0.20195603211835453
Fold 3 IBS: 0.18524950719590635
Fold 4 IBS: 0.18167411231663144
Fold 5 IBS: 0.21301167725555065
[I 2024-04-13 18:22:28,890] Trial 63 finished with value: 0.19425971108350884 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.9709041364981504, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17457092877839805}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19042077788605422
Fold 2 IBS: 0.20503437363791857
Fold 3 IBS: 0.1812573535917489
Fold 4 IBS: 0.1599480522032286
Fold 5 IBS: 0.22133756944780028
[I 2024-04-13 18:22:32,590] Trial 64 finished with value: 0.19159962535335012 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.9232561076825374, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08247374764822177}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1855486807275111
Fold 2 IBS: 0.20889887216359987
Fold 3 IBS: 0.186757263162056
Fold 4 IBS: 0.1516223960439653
Fold 5 IBS: 0.23766765290617403
[I 2024-04-13 18:22:34,430] Trial 65 finished with value: 0.19409897300066126 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 39, 'oob_score': True, 'max_samples': 0.9239964449623014, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10212410937582425}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18972023265836888
Fold 2 IBS: 0.20827219770096392
Fold 3 IBS: 0.184072456155935
Fold 4 IBS: 0.15552667460774774
Fold 5 IBS: 0.23225547009007083
[I 2024-04-13 18:22:37,954] Trial 66 finished with value: 0.19396940624261727 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 79, 'oob_score': True, 'max_samples': 0.8229286325912109, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08356756122484327}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.2162615806595325
Fold 2 IBS: 0.2314895391751013
Fold 3 IBS: 0.18982263167403834
Fold 4 IBS: 0.16500207912522005
Fold 5 IBS: 0.2490970830892452
[I 2024-04-13 18:22:41,808] Trial 67 finished with value: 0.21033458274462746 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.8683895440504493, 'max_features': None, 'min_weight_fraction_leaf': 0.05861021648602916}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18667797303983946
Fold 2 IBS: 0.212478954186335
Fold 3 IBS: 0.18565540093157798
Fold 4 IBS: 0.15400304936935894
Fold 5 IBS: 0.2382948426517038
[I 2024-04-13 18:22:44,409] Trial 68 finished with value: 0.19542204403576302 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.8890713935546998, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07970274361521959}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.20256132882323044
Fold 2 IBS: 0.2091714914493512
Fold 3 IBS: 0.1916526329855485
Fold 4 IBS: 0.2082061408566928
Fold 5 IBS: 0.2131451363090046
[I 2024-04-13 18:22:49,239] Trial 69 finished with value: 0.2049473460847655 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9287332500754819, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.37507273812997705}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19279222406798027
Fold 2 IBS: 0.20805567864529337
Fold 3 IBS: 0.18460634844982596
Fold 4 IBS: 0.16272135921234857
Fold 5 IBS: 0.22968584520330837
[I 2024-04-13 18:22:54,647] Trial 70 finished with value: 0.1955722911157513 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 145, 'oob_score': True, 'max_samples': 0.8458154633905051, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11941984246057576}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18705718779369432
Fold 2 IBS: 0.20106150658467475
Fold 3 IBS: 0.18641352614940085
Fold 4 IBS: 0.1779323504817836
Fold 5 IBS: 0.21204353935529816
[I 2024-04-13 18:23:01,006] Trial 71 finished with value: 0.19290162207297035 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.9828154313743548, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05410525831350659}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.191342085509237
Fold 2 IBS: 0.2051470489259237
Fold 3 IBS: 0.18075954605572378
Fold 4 IBS: 0.1651024797549892
Fold 5 IBS: 0.22183360370428845
[I 2024-04-13 18:23:06,716] Trial 72 finished with value: 0.19283695279003243 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 99, 'oob_score': True, 'max_samples': 0.9718403195201334, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14185546812576943}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19001760987638033
Fold 2 IBS: 0.20245262186787985
Fold 3 IBS: 0.1844684794656913
Fold 4 IBS: 0.17236583875817466
Fold 5 IBS: 0.22129402787984084
[I 2024-04-13 18:23:08,533] Trial 73 finished with value: 0.19411971556959343 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 2, 'n_estimators': 31, 'oob_score': True, 'max_samples': 0.9964228603812916, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09718436899662969}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18835263712206055
Fold 2 IBS: 0.20652910775747693
Fold 3 IBS: 0.18493077689304596
Fold 4 IBS: 0.16084673239338115
Fold 5 IBS: 0.22614730302307817
[I 2024-04-13 18:23:16,751] Trial 74 finished with value: 0.19336131143780858 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.7563036526690692, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08265872368150795}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1865856836372834
Fold 2 IBS: 0.19846450459155177
Fold 3 IBS: 0.18667319105893243
Fold 4 IBS: 0.17577210277864422
Fold 5 IBS: 0.2125361950158652
[I 2024-04-13 18:23:23,238] Trial 75 finished with value: 0.1920063354164554 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 152, 'oob_score': True, 'max_samples': 0.8934320271287068, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020082183638978436}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1886780379663195
Fold 2 IBS: 0.1969969364673427
Fold 3 IBS: 0.18834342593020675
Fold 4 IBS: 0.1767167144401383
Fold 5 IBS: 0.21153932961845465
[I 2024-04-13 18:23:27,664] Trial 76 finished with value: 0.19245488888449236 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 113, 'oob_score': True, 'max_samples': 0.8967149820761576, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.025723916587172324}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.19121543733296342
Fold 2 IBS: 0.2091918671778832
Fold 3 IBS: 0.19009364071445495
Fold 4 IBS: 0.14814198542152313
Fold 5 IBS: 0.22937210309658887
[I 2024-04-13 18:23:33,429] Trial 77 finished with value: 0.19360300674868272 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.799690719737348, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04601635305530971}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1883886656744684
Fold 2 IBS: 0.21011307454500397
Fold 3 IBS: 0.18536023439714336
Fold 4 IBS: 0.15906452131574286
Fold 5 IBS: 0.23254351876612106
[I 2024-04-13 18:23:39,154] Trial 78 finished with value: 0.19509400293969592 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.9377327308841977, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.011884271709699766}. Best is trial 34 with value: 0.19091252378673845.

Fold 1 IBS: 0.18941186315145053
Fold 2 IBS: 0.20894591941191445
Fold 3 IBS: 0.187373667402488
Fold 4 IBS: 0.1572712742266229
Fold 5 IBS: 0.23558395033292584
[I 2024-04-13 18:23:42,147] Trial 79 finished with value: 0.19571733490508034 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 66, 'oob_score': True, 'max_samples': 0.840513464959072, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.017278165075527617}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.1874686284373422
Fold 2 IBS: 0.19665174781158837
Fold 3 IBS: 0.1871877356508405
Fold 4 IBS: 0.1763663924698438
Fold 5 IBS: 0.21229602140119605
[I 2024-04-13 18:23:46,080] Trial 80 finished with value: 0.1919941051541622 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 91, 'oob_score': True, 'max_samples': 0.8671378958998438, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.059517242025535634}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18787972475700745
Fold 2 IBS: 0.1965793683602537
Fold 3 IBS: 0.18697017539912755
Fold 4 IBS: 0.1754284455524885
Fold 5 IBS: 0.21175272454935387
[I 2024-04-13 18:23:50,195] Trial 81 finished with value: 0.1917220877236462 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 88, 'oob_score': True, 'max_samples': 0.9110052979515114, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.061844810255080235}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18928672937590252
Fold 2 IBS: 0.19572773732205992
Fold 3 IBS: 0.18875800033808568
Fold 4 IBS: 0.177277103543706
Fold 5 IBS: 0.21149292673995707
[I 2024-04-13 18:23:54,618] Trial 82 finished with value: 0.19250849946394225 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.8688774277930147, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.037642566056529284}. Best is trial 34 with value: 0.19091252378673845.
Fold 1 IBS: 0.18323958572652088
Fold 2 IBS: 0.20179959984503285
Fold 3 IBS: 0.18423859713676757
Fold 4 IBS: 0.15455341507293507
Fold 5 IBS: 0.2214651676232807
[I 2024-04-13 18:23:57,334] Trial 83 finished with value: 0.18905927308090742 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 58, 'oob_score': True, 'max_samples': 0.9093691271986448, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.060459981653401815}. Best is trial 83 with value: 0.18905927308090742.
Fold 1 IBS: 0.18229868972158023
Fold 2 IBS: 0.20154627021024019
Fold 3 IBS: 0.18203145527560965
Fold 4 IBS: 0.15392873774272633
Fold 5 IBS: 0.22286101229360045
[I 2024-04-13 18:23:59,903] Trial 84 finished with value: 0.18853323304875136 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.9114203728045779, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06114501262593285}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.18468723992269176
Fold 2 IBS: 0.20194687575248157
Fold 3 IBS: 0.18531023035650862
Fold 4 IBS: 0.1574856859091213
Fold 5 IBS: 0.22090211367899262
[I 2024-04-13 18:24:04,464] Trial 85 finished with value: 0.19006642912395916 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 60, 'oob_score': True, 'max_samples': 0.917448952843577, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11308691390660285}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.19477603264102292
Fold 2 IBS: 0.21379544738423523
Fold 3 IBS: 0.1751682405579849
Fold 4 IBS: 0.14051113145726496
Fold 5 IBS: 0.25689301053116215
[I 2024-04-13 18:24:08,690] Trial 86 finished with value: 0.19622877251433404 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.9600958151901968, 'max_features': None, 'min_weight_fraction_leaf': 0.11445394633102693}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.19068213521962762
Fold 2 IBS: 0.23586234516222535
Fold 3 IBS: 0.18309044630183868
Fold 4 IBS: 0.1537714999522103
Fold 5 IBS: 0.2706472905741154
[I 2024-04-13 18:24:09,707] Trial 87 finished with value: 0.20681074344200345 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 3, 'oob_score': True, 'max_samples': 0.9335611845324681, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1032366671702548}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.1903698311241902
Fold 2 IBS: 0.20831519167574022
Fold 3 IBS: 0.18680988906150273
Fold 4 IBS: 0.15879451299534442
Fold 5 IBS: 0.23763086073553377
[I 2024-04-13 18:24:15,066] Trial 88 finished with value: 0.19638405711846227 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.9125336042681119, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07341864276976343}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.18998536674855057
Fold 2 IBS: 0.2209186587232065
Fold 3 IBS: 0.18417064425076515
Fold 4 IBS: 0.1422001148511902
Fold 5 IBS: 0.2358582419433995
[I 2024-04-13 18:24:21,491] Trial 89 finished with value: 0.19462660530342238 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 76, 'oob_score': False, 'max_samples': 0.9784774171059273, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04916357735227042}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.19321123608117524
Fold 2 IBS: 0.2085887445968146
Fold 3 IBS: 0.18731107464667726
Fold 4 IBS: 0.1590037450688704
Fold 5 IBS: 0.2384920330796407
[I 2024-04-13 18:24:23,527] Trial 90 finished with value: 0.19732136669463565 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 31, 'oob_score': True, 'max_samples': 0.8187034329346825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03586855145102289}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.19430034758147022
Fold 2 IBS: 0.20282050455205633
Fold 3 IBS: 0.1839337664097729
Fold 4 IBS: 0.18880501740751374
Fold 5 IBS: 0.21657633148184902
[I 2024-04-13 18:24:27,015] Trial 91 finished with value: 0.19728719348653243 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 2, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.9002513157556775, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06466378586788281}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.1888176605118133
Fold 2 IBS: 0.2126614370796748
Fold 3 IBS: 0.18585503050904378
Fold 4 IBS: 0.14988496780915256
Fold 5 IBS: 0.23505603085106538
[I 2024-04-13 18:24:30,913] Trial 92 finished with value: 0.19445502535214998 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.9249259311983584, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08003228931891569}. Best is trial 84 with value: 0.18853323304875136.
Fold 1 IBS: 0.18423025988394848
Fold 2 IBS: 0.19803538797909473
Fold 3 IBS: 0.1825621399149803
Fold 4 IBS: 0.15023890096900144
Fold 5 IBS: 0.2210218897892516
[I 2024-04-13 18:24:34,188] Trial 93 finished with value: 0.18721771570725532 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 44, 'oob_score': True, 'max_samples': 0.7957196161977251, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.055989936415019606}. Best is trial 93 with value: 0.18721771570725532.
Fold 1 IBS: 0.18552316846762879
Fold 2 IBS: 0.19602269995867352
Fold 3 IBS: 0.18196785329443976
Fold 4 IBS: 0.16046527424386953
Fold 5 IBS: 0.22608044850226944
[I 2024-04-13 18:24:36,419] Trial 94 finished with value: 0.19001188889337622 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.7532378364252195, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09877418735412302}. Best is trial 93 with value: 0.18721771570725532.

Fold 1 IBS: 0.18624856075855828
Fold 2 IBS: 0.1984491501857183
Fold 3 IBS: 0.1837881604977131
Fold 4 IBS: 0.1616422821334367
Fold 5 IBS: 0.22637023753308694
[I 2024-04-13 18:24:39,151] Trial 95 finished with value: 0.19129967822170266 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 41, 'oob_score': True, 'max_samples': 0.7371655958571915, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09280511653934975}. Best is trial 93 with value: 0.18721771570725532.
Fold 1 IBS: 0.18864761738406893
Fold 2 IBS: 0.20913810852224018
Fold 3 IBS: 0.1877503271050813
Fold 4 IBS: 0.15313275677333474
Fold 5 IBS: 0.23158574356531922
[I 2024-04-13 18:24:42,152] Trial 96 finished with value: 0.19405091067000887 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 46, 'oob_score': True, 'max_samples': 0.7523032159371248, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07591598090901643}. Best is trial 93 with value: 0.18721771570725532.
Fold 1 IBS: 0.1991680074680787
Fold 2 IBS: 0.19251045615884382
Fold 3 IBS: 0.18389246641828566
Fold 4 IBS: 0.17067869318684856
Fold 5 IBS: 0.22723582951813107
[I 2024-04-13 18:24:44,035] Trial 97 finished with value: 0.19469709055003753 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 20, 'oob_score': False, 'max_samples': 0.747580631273081, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12985172655126914}. Best is trial 93 with value: 0.18721771570725532.
Fold 1 IBS: 0.19055964920747953
Fold 2 IBS: 0.2141893593646294
Fold 3 IBS: 0.1877541184348747
Fold 4 IBS: 0.14807785738693724
Fold 5 IBS: 0.23932741442217637
[I 2024-04-13 18:24:47,289] Trial 98 finished with value: 0.19598167976321945 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.7318752680098357, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05188451383027545}. Best is trial 93 with value: 0.18721771570725532.
Fold 1 IBS: 0.19414505549578753
Fold 2 IBS: 0.19895425042897827
Fold 3 IBS: 0.18382356192260188
Fold 4 IBS: 0.16375453649612862
Fold 5 IBS: 0.2276953811472078
[I 2024-04-13 18:24:49,326] Trial 99 finished with value: 0.1936745570981408 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 34, 'oob_score': True, 'max_samples': 0.7675810300384975, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11036099500899822}. Best is trial 93 with value: 0.18721771570725532.


* Best trial for IBS:
 FrozenTrial(number=93, state=TrialState.COMPLETE, values=[0.18721771570725532], datetime_start=datetime.datetime(2024, 4, 13, 18, 24, 30, 919942), datetime_complete=datetime.datetime(2024, 4, 13, 18, 24, 34, 188021), params={'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 44, 'oob_score': True, 'max_samples': 0.7957196161977251, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.055989936415019606}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=93, value=None)


* Best Score for IBS:
 0.18721771570725532

In [57]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [58]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.774
train_ibs:  0.187

#### Test

In [59]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [60]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=10, max_features=None, max_leaf_nodes=13,
                     max_samples=0.9157070212716846, min_samples_leaf=2,
                     min_samples_split=3,
                     min_weight_fraction_leaf=0.28086863940091983,
                     n_estimators=475, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.669

RandomSurvivalForest(max_depth=2, max_features='auto', max_leaf_nodes=7,
                     max_samples=0.7957196161977251, min_samples_leaf=4,
                     min_samples_split=18,
                     min_weight_fraction_leaf=0.055989936415019606,
                     n_estimators=44, oob_score=True, random_state=123)

test_ibs:  0.21

In [61]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [62]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:24:54,115] A new study created in memory with name: no-name-d16e0299-c537-47d3-b70f-b37f9f96e965

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6854460093896714
[I 2024-04-13 18:24:57,210] Trial 0 finished with value: 0.7564638130572738 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:25:04,796] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6267605633802817
[I 2024-04-13 18:25:21,273] Trial 2 finished with value: 0.7408541305142619 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 18:25:22,858] Trial 3 finished with value: 0.750081458964078 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:25:27,897] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:25:35,795] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:25:39,668] Trial 6 finished with value: 0.7468890720845299 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6455399061032864
[I 2024-04-13 18:25:48,945] Trial 7 finished with value: 0.7387356038462323 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6455399061032864
[I 2024-04-13 18:25:49,633] Trial 8 finished with value: 0.7424570003449928 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 18:26:10,692] Trial 9 finished with value: 0.7451724918601617 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:26:16,723] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6455399061032864
[I 2024-04-13 18:26:18,297] Trial 11 finished with value: 0.751411832277766 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9547450918366839, 'min_weight_fraction_leaf': 0.13639294401318086}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6651785714285714
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6173708920187794
[I 2024-04-13 18:26:18,667] Trial 12 finished with value: 0.7148357316556665 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 2, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9861268838969514, 'min_weight_fraction_leaf': 0.19160160653003072}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 18:26:20,650] Trial 13 finished with value: 0.7431488671701683 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.09287447212810436}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:26:21,714] Trial 14 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 95, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:26:25,208] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 3, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.38518225566002634}. Best is trial 0 with value: 0.7564638130572738.

Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:26:26,984] Trial 16 finished with value: 0.750809297730016 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8988170687511211, 'min_weight_fraction_leaf': 0.1144909881867055}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:26:29,326] Trial 17 finished with value: 0.746528835545142 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.18883691189794657}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.6830357142857143
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:26:36,684] Trial 18 finished with value: 0.7306907786777981 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 202, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8985807191210379, 'min_weight_fraction_leaf': 0.0021515317782870857}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.6904761904761905
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 18:26:40,267] Trial 19 finished with value: 0.7483601831265578 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 384, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.41695365388974803, 'min_weight_fraction_leaf': 0.07377892999653754}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 18:26:41,658] Trial 20 finished with value: 0.746192017909937 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8252630790507764, 'min_weight_fraction_leaf': 0.15650742712501486}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6643192488262911
[I 2024-04-13 18:26:43,435] Trial 21 finished with value: 0.7526463297883376 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 199, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9160676931210066, 'min_weight_fraction_leaf': 0.11205227332881289}. Best is trial 0 with value: 0.7564638130572738.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8839662447257384
Fold 5 C-index: 0.6854460093896714
[I 2024-04-13 18:26:45,199] Trial 22 finished with value: 0.767036894418702 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 199, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9925121615404277, 'min_weight_fraction_leaf': 0.04510371924387695}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.687793427230047
[I 2024-04-13 18:26:46,862] Trial 23 finished with value: 0.7606740132802502 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 191, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7292909199687266, 'min_weight_fraction_leaf': 0.044397653763862635}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:26:50,100] Trial 24 finished with value: 0.7534447161091051 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6240954690160195, 'min_weight_fraction_leaf': 0.03583425307277722}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6854460093896714
[I 2024-04-13 18:26:52,485] Trial 25 finished with value: 0.756807083276754 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 229, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7580541326308717, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7008928571428571
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6549295774647887
[I 2024-04-13 18:27:02,022] Trial 26 finished with value: 0.7395910405118951 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7201208295157817, 'min_weight_fraction_leaf': 0.036693878801276586}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:27:03,498] Trial 27 finished with value: 0.7577651885443395 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8428436161165677, 'min_weight_fraction_leaf': 0.015976534137045362}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:27:04,875] Trial 28 finished with value: 0.7568968190446409 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8286218784651163, 'min_weight_fraction_leaf': 0.008615314764917947}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6737089201877934
[I 2024-04-13 18:27:06,150] Trial 29 finished with value: 0.7581014141381606 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 77, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8499447592488185, 'min_weight_fraction_leaf': 0.08787587030277691}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.765625
Fold 3 C-index: 0.7549019607843137
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6737089201877934
[I 2024-04-13 18:27:06,778] Trial 30 finished with value: 0.7534342768574714 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 44, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9144438329247497, 'min_weight_fraction_leaf': 0.0766837430930732}. Best is trial 22 with value: 0.767036894418702.

Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8628691983122363
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:27:07,701] Trial 31 finished with value: 0.7545552221642317 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 78, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.870642154383752, 'min_weight_fraction_leaf': 0.07589392630375186}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6549295774647887
[I 2024-04-13 18:27:09,331] Trial 32 finished with value: 0.7528594347510638 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 172, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382946188213893, 'min_weight_fraction_leaf': 0.09399508879613472}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 18:27:10,614] Trial 33 finished with value: 0.7438706588285324 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 128, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6192498968822464, 'min_weight_fraction_leaf': 0.03040417736836283}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:27:11,476] Trial 34 finished with value: 0.7466949707564188 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9979291581118793, 'min_weight_fraction_leaf': 0.060610286223735835}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7165178571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.879746835443038
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:27:14,261] Trial 35 finished with value: 0.751012300392531 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 152, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7394569868267925, 'min_weight_fraction_leaf': 0.2150522713624248}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.636150234741784
[I 2024-04-13 18:27:20,028] Trial 36 finished with value: 0.7433921936252094 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 197, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9543604672808241, 'min_weight_fraction_leaf': 0.10305257519629671}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:27:20,531] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 23, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.5069340304409566, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8354430379746836
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:27:22,848] Trial 38 finished with value: 0.7525983348533176 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 17, 'n_estimators': 293, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8489517338201277, 'min_weight_fraction_leaf': 0.028333770749461123}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.6852678571428571
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.636150234741784
[I 2024-04-13 18:27:27,266] Trial 39 finished with value: 0.7319031172696959 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 123, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7898418765076363, 'min_weight_fraction_leaf': 0.3676238651442645}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7098214285714286
Fold 3 C-index: 0.7794117647058824
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6455399061032864
[I 2024-04-13 18:27:28,843] Trial 40 finished with value: 0.7338591077932656 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6639675100986713, 'min_weight_fraction_leaf': 0.2981475630451996}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:27:30,281] Trial 41 finished with value: 0.7570457393722656 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 171, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8236615315106797, 'min_weight_fraction_leaf': 0.002002972570708139}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:27:32,155] Trial 42 finished with value: 0.7513286664241864 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 215, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9387058802813981, 'min_weight_fraction_leaf': 0.012340937037097238}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8586497890295358
Fold 5 C-index: 0.6854460093896714
[I 2024-04-13 18:27:34,392] Trial 43 finished with value: 0.757536373842232 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.0571695157494708}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 18:27:36,564] Trial 44 finished with value: 0.7507978166955205 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7276769183001319, 'min_weight_fraction_leaf': 0.05832502537772804}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:27:39,700] Trial 45 finished with value: 0.7486579419203458 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 324, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7923574760433084, 'min_weight_fraction_leaf': 0.13987902134460642}. Best is trial 22 with value: 0.767036894418702.

Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6549295774647887
[I 2024-04-13 18:27:42,191] Trial 46 finished with value: 0.7448362312233925 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3546626066657711, 'min_weight_fraction_leaf': 0.058424355194011506}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7254464285714286
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6408450704225352
[I 2024-04-13 18:27:56,106] Trial 47 finished with value: 0.7491651988069575 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 493, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5901465370883026, 'min_weight_fraction_leaf': 0.1625947698183845}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6737089201877934
[I 2024-04-13 18:27:58,711] Trial 48 finished with value: 0.7516976788811117 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 147, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8761581951716622, 'min_weight_fraction_leaf': 0.12018482594310922}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:27:59,668] Trial 49 finished with value: 0.7541442394637234 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 70, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9559833900001994, 'min_weight_fraction_leaf': 0.08193113848639327}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:28:02,162] Trial 50 finished with value: 0.748015660299031 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7030087331520629, 'min_weight_fraction_leaf': 0.020091167332604194}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8607594936708861
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:28:04,033] Trial 51 finished with value: 0.7614248358219445 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7779072711586293, 'min_weight_fraction_leaf': 0.0005562763304838864}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6643192488262911
[I 2024-04-13 18:28:05,975] Trial 52 finished with value: 0.7530251176671254 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7727587735640222, 'min_weight_fraction_leaf': 0.04625746787608169}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 18:28:07,660] Trial 53 finished with value: 0.7497923224379787 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 188, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6592425039333766, 'min_weight_fraction_leaf': 0.022847799776599655}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.879746835443038
Fold 5 C-index: 0.6807511737089202
[I 2024-04-13 18:28:09,047] Trial 54 finished with value: 0.7652540454260117 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 15, 'n_estimators': 158, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8617893136952861, 'min_weight_fraction_leaf': 0.05827226832390916}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 18:28:10,492] Trial 55 finished with value: 0.7480815921159303 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 134, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.870638302288536, 'min_weight_fraction_leaf': 0.09054753943279187}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7388392857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 18:28:11,648] Trial 56 finished with value: 0.7494657120899543 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 97, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9435261083046782, 'min_weight_fraction_leaf': 0.06658343206490397}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6502347417840375
[I 2024-04-13 18:28:13,202] Trial 57 finished with value: 0.7504523775019984 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 160, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.750478214093817, 'min_weight_fraction_leaf': 0.03957705924295209}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8248945147679325
Fold 5 C-index: 0.6572769953051644
[I 2024-04-13 18:28:17,406] Trial 58 finished with value: 0.7285739760660582 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 114, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8943345814637109, 'min_weight_fraction_leaf': 0.019162835593157443}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8291139240506329
Fold 5 C-index: 0.6619718309859155
[I 2024-04-13 18:28:18,827] Trial 59 finished with value: 0.7486763119444118 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 145, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9707172085895303, 'min_weight_fraction_leaf': 4.9425055971434595e-05}. Best is trial 22 with value: 0.767036894418702.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:28:21,010] Trial 60 finished with value: 0.7504554036804595 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 217, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9208992051748564, 'min_weight_fraction_leaf': 0.2759721947630981}. Best is trial 22 with value: 0.767036894418702.

Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8839662447257384
Fold 5 C-index: 0.6901408450704225
[I 2024-04-13 18:28:22,781] Trial 61 finished with value: 0.7691854362938387 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 183, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8150275781190496, 'min_weight_fraction_leaf': 0.05115214438310639}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:28:24,347] Trial 62 finished with value: 0.7579193166512784 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 185, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8528409024287451, 'min_weight_fraction_leaf': 0.10085974846849723}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8375527426160337
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:28:26,123] Trial 63 finished with value: 0.7506593298026839 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 192, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8250036216350005, 'min_weight_fraction_leaf': 0.12724424306704513}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6643192488262911
[I 2024-04-13 18:28:28,037] Trial 64 finished with value: 0.75195393689332 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 208, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8598428878813489, 'min_weight_fraction_leaf': 0.10979715300088996}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:28:29,939] Trial 65 finished with value: 0.7531759954342359 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 182, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8082637357137693, 'min_weight_fraction_leaf': 0.09096952081464799}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.6854460093896714
[I 2024-04-13 18:28:32,020] Trial 66 finished with value: 0.7647459348818378 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7057466263854532, 'min_weight_fraction_leaf': 0.04852697875667484}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.7303921568627451
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.7136150234741784
[I 2024-04-13 18:28:34,668] Trial 67 finished with value: 0.7456569486982139 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6919420094192816, 'min_weight_fraction_leaf': 0.04283316284452468}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.676056338028169
[I 2024-04-13 18:28:36,922] Trial 68 finished with value: 0.7566273282761621 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6356332956572487, 'min_weight_fraction_leaf': 0.07350089746333772}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.6854460093896714
[I 2024-04-13 18:28:39,339] Trial 69 finished with value: 0.7627851505681124 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7650617956803925, 'min_weight_fraction_leaf': 0.043650944161466844}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.6875
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.6525821596244131
[I 2024-04-13 18:28:48,574] Trial 70 finished with value: 0.7330798681163903 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 232, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7404631453111323, 'min_weight_fraction_leaf': 0.050360859975285645}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.676056338028169
[I 2024-04-13 18:28:50,792] Trial 71 finished with value: 0.7566492472854228 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7672487284266724, 'min_weight_fraction_leaf': 0.032013898890968055}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6807511737089202
[I 2024-04-13 18:28:53,379] Trial 72 finished with value: 0.7532707135432011 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7209388585577007, 'min_weight_fraction_leaf': 0.07094990370250684}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:28:55,414] Trial 73 finished with value: 0.756951685802443 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 223, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6796064377720622, 'min_weight_fraction_leaf': 0.03029094148828231}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 18:28:56,256] Trial 74 finished with value: 0.7509388689591463 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7590451963740803, 'min_weight_fraction_leaf': 0.08746956837589816}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:28:58,206] Trial 75 finished with value: 0.7543749957153967 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 203, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5929773161110014, 'min_weight_fraction_leaf': 0.05439026033906994}. Best is trial 61 with value: 0.7691854362938387.

Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.75
Fold 3 C-index: 0.7352941176470589
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.7183098591549296
[I 2024-04-13 18:29:00,712] Trial 76 finished with value: 0.747181423340013 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 249, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.797263516061008, 'min_weight_fraction_leaf': 0.043908928693763075}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:29:02,179] Trial 77 finished with value: 0.7560887502296659 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 158, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8147479554398341, 'min_weight_fraction_leaf': 0.013190074023884269}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:29:02,679] Trial 78 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 20, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7068761745462286, 'min_weight_fraction_leaf': 0.41218066030994116}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8396624472573839
Fold 5 C-index: 0.676056338028169
[I 2024-04-13 18:29:04,101] Trial 79 finished with value: 0.7483372890153485 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 173, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5398413883194484, 'min_weight_fraction_leaf': 0.06465291113740826}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8333333333333334
Fold 5 C-index: 0.6619718309859155
[I 2024-04-13 18:29:07,205] Trial 80 finished with value: 0.745438674829727 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8944537690311801, 'min_weight_fraction_leaf': 0.21350064262063223}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 18:29:09,105] Trial 81 finished with value: 0.7561606586426205 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8474396925311871, 'min_weight_fraction_leaf': 0.10252106000486062}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8459915611814346
Fold 5 C-index: 0.6643192488262911
[I 2024-04-13 18:29:11,092] Trial 82 finished with value: 0.7503703489126732 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9264626943914532, 'min_weight_fraction_leaf': 0.12895983142186374}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:29:13,270] Trial 83 finished with value: 0.7456238637572404 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 239, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7728501877902084, 'min_weight_fraction_leaf': 0.14903304482402702}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:29:14,683] Trial 84 finished with value: 0.5 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.07741120856941303}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8417721518987342
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:29:17,023] Trial 85 finished with value: 0.7526665194919604 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 269, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.888373572391191, 'min_weight_fraction_leaf': 0.10139953373009479}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8755274261603375
Fold 5 C-index: 0.6690140845070423
[I 2024-04-13 18:29:18,675] Trial 86 finished with value: 0.7562695193476344 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.860714040293082, 'min_weight_fraction_leaf': 0.02642103208266877}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7121212121212122
Fold 2 C-index: 0.7321428571428571
Fold 3 C-index: 0.7941176470588235
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6408450704225352
[I 2024-04-13 18:29:25,834] Trial 87 finished with value: 0.7420900830874821 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 199, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8380967508659484, 'min_weight_fraction_leaf': 0.010159476214063176}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7455357142857143
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.6854460093896714
[I 2024-04-13 18:29:26,981] Trial 88 finished with value: 0.7602142603017642 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 125, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.974592707480633, 'min_weight_fraction_leaf': 0.053763594462199776}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.734375
Fold 3 C-index: 0.8063725490196079
Fold 4 C-index: 0.8438818565400844
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:29:28,046] Trial 89 finished with value: 0.7513847555708129 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 92, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9972726358959354, 'min_weight_fraction_leaf': 0.03719935591561677}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.6991341991341992
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.676056338028169
[I 2024-04-13 18:29:29,256] Trial 90 finished with value: 0.7528026626216379 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 105, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9587690427885938, 'min_weight_fraction_leaf': 0.05305541913345835}. Best is trial 61 with value: 0.7691854362938387.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8670886075949367
Fold 5 C-index: 0.676056338028169
[I 2024-04-13 18:29:30,424] Trial 91 finished with value: 0.7572554851775879 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 120, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9750465557027668, 'min_weight_fraction_leaf': 0.06624689680384555}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7207792207792207
Fold 2 C-index: 0.7477678571428571
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.8839662447257384
Fold 5 C-index: 0.6713615023474179
[I 2024-04-13 18:29:31,968] Trial 92 finished with value: 0.7650690826461057 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8083919746526695, 'min_weight_fraction_leaf': 0.08240208343097213}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.6948051948051948
Fold 2 C-index: 0.7522321428571429
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.8881856540084389
Fold 5 C-index: 0.6666666666666666
[I 2024-04-13 18:29:33,513] Trial 93 finished with value: 0.7596916571576846 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 158, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9099470670314438, 'min_weight_fraction_leaf': 0.07987706416912244}. Best is trial 61 with value: 0.7691854362938387.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8186274509803921
Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7464788732394366
[I 2024-04-13 18:29:34,982] Trial 94 finished with value: 0.7854153001335706 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 152, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9156069609477638, 'min_weight_fraction_leaf': 0.021322411935986683}. Best is trial 94 with value: 0.7854153001335706.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7633928571428571
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.869198312236287
Fold 5 C-index: 0.7417840375586855
[I 2024-04-13 18:29:36,299] Trial 95 finished with value: 0.7740729023501327 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 146, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9379897273950399, 'min_weight_fraction_leaf': 0.020594569215488454}. Best is trial 94 with value: 0.7854153001335706.
Fold 1 C-index: 0.7077922077922078
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.7843137254901961
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6502347417840375
[I 2024-04-13 18:29:37,891] Trial 96 finished with value: 0.7453363538197982 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 17, 'n_estimators': 145, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7808898679062846, 'min_weight_fraction_leaf': 0.007512392392877605}. Best is trial 94 with value: 0.7854153001335706.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.7401960784313726
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.7323943661971831
[I 2024-04-13 18:29:39,397] Trial 97 finished with value: 0.7562379091898352 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 169, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8125540835342867, 'min_weight_fraction_leaf': 0.021217092917651732}. Best is trial 94 with value: 0.7854153001335706.
Fold 1 C-index: 0.7251082251082251
Fold 2 C-index: 0.7678571428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8481012658227848
Fold 5 C-index: 0.6995305164319249
[I 2024-04-13 18:29:40,862] Trial 98 finished with value: 0.7698841359263685 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 136, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9304239636550578, 'min_weight_fraction_leaf': 0.03751875854853892}. Best is trial 94 with value: 0.7854153001335706.
Fold 1 C-index: 0.7034632034632035
Fold 2 C-index: 0.7723214285714286
Fold 3 C-index: 0.8333333333333334

[I 2024-04-13 18:29:42,587] A new study created in memory with name: no-name-cfd5f839-c9f7-4ae7-892a-b85fc23b4d1c

Fold 4 C-index: 0.8818565400843882
Fold 5 C-index: 0.7464788732394366
[I 2024-04-13 18:29:42,570] Trial 99 finished with value: 0.7874906757383581 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 132, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9351618935202715, 'min_weight_fraction_leaf': 0.035839978360771345}. Best is trial 99 with value: 0.7874906757383581.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.7874906757383581], datetime_start=datetime.datetime(2024, 4, 13, 18, 29, 40, 884962), datetime_complete=datetime.datetime(2024, 4, 13, 18, 29, 42, 569583), params={'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 132, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9351618935202715, 'min_weight_fraction_leaf': 0.035839978360771345}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=99, value=None)


* Best Score for C-index:
 0.7874906757383581

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.17977003304049463
Fold 2 IBS: 0.2151513971742152
Fold 3 IBS: 0.18601742779423505
Fold 4 IBS: 0.1861391948766247
Fold 5 IBS: 0.2254968746908274
[I 2024-04-13 18:29:53,473] Trial 0 finished with value: 0.19851498551527938 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.19851498551527938.
Fold 1 IBS: 0.21397044418009403
Fold 2 IBS: 0.2213577420328451
Fold 3 IBS: 0.20483341238572939
Fold 4 IBS: 0.2246317356403713
Fold 5 IBS: 0.21844555289646383
[I 2024-04-13 18:30:08,393] Trial 1 finished with value: 0.21664777742710073 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.19851498551527938.
Fold 1 IBS: 0.18177652839633304
Fold 2 IBS: 0.21613239784358157
Fold 3 IBS: 0.1868212423085333
Fold 4 IBS: 0.18737081876451456
Fold 5 IBS: 0.2258580410641433
[I 2024-04-13 18:30:25,224] Trial 2 finished with value: 0.19959180567542115 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.19851498551527938.
Fold 1 IBS: 0.18436789381773172
Fold 2 IBS: 0.21583430949725804
Fold 3 IBS: 0.18767157615182917
Fold 4 IBS: 0.1903009402534763
Fold 5 IBS: 0.22424228277496247
[I 2024-04-13 18:30:30,327] Trial 3 finished with value: 0.20048340049905153 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.19851498551527938.
Fold 1 IBS: 0.21397641813452659
Fold 2 IBS: 0.22121403897441458
Fold 3 IBS: 0.2049844173134295
Fold 4 IBS: 0.22471121760214624
Fold 5 IBS: 0.21862428920013807
[I 2024-04-13 18:30:45,111] Trial 4 finished with value: 0.21670207624493099 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.19851498551527938.
Fold 1 IBS: 0.21402791185291206
Fold 2 IBS: 0.22165060126210223
Fold 3 IBS: 0.20488390266784473
Fold 4 IBS: 0.2247741065950663
Fold 5 IBS: 0.21845820275927524
[I 2024-04-13 18:30:51,306] Trial 5 finished with value: 0.2167589450274401 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.19851498551527938.
Fold 1 IBS: 0.1794991058424641
Fold 2 IBS: 0.21465339904118858
Fold 3 IBS: 0.18587739868551786
Fold 4 IBS: 0.18461882515655892
Fold 5 IBS: 0.22590659392101745
[I 2024-04-13 18:31:04,171] Trial 6 finished with value: 0.19811106452934937 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 6 with value: 0.19811106452934937.
Fold 1 IBS: 0.175906032246917
Fold 2 IBS: 0.21372668758628946
Fold 3 IBS: 0.18282725438964767
Fold 4 IBS: 0.1793176417542498
Fold 5 IBS: 0.22652830834465523
[I 2024-04-13 18:31:13,054] Trial 7 finished with value: 0.19566118486435183 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1895318717276859
Fold 2 IBS: 0.21497427761742846
Fold 3 IBS: 0.1882423115587511
Fold 4 IBS: 0.1890629259277416
Fold 5 IBS: 0.22207541363269
[I 2024-04-13 18:31:14,967] Trial 8 finished with value: 0.20077736009285943 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18731528812337914
Fold 2 IBS: 0.21950384027263117
Fold 3 IBS: 0.19124096235001134
Fold 4 IBS: 0.19971391904677507
Fold 5 IBS: 0.22163686930432427
[I 2024-04-13 18:31:31,858] Trial 9 finished with value: 0.2038821758194242 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.2139976337400846
Fold 2 IBS: 0.22078850566211056
Fold 3 IBS: 0.20468678510920732
Fold 4 IBS: 0.2246562137512858
Fold 5 IBS: 0.21763185598455237
[I 2024-04-13 18:31:35,912] Trial 10 finished with value: 0.21635219884944812 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 98, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.21752764504502275, 'min_weight_fraction_leaf': 0.20722772178871404}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.17963424747561654
Fold 2 IBS: 0.21487393538882746
Fold 3 IBS: 0.18563573496551505
Fold 4 IBS: 0.18480215427498636
Fold 5 IBS: 0.22571052518340803
[I 2024-04-13 18:31:46,425] Trial 11 finished with value: 0.19813131945767068 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 296, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18782563485426526
Fold 2 IBS: 0.21647173799550826
Fold 3 IBS: 0.18930613135490026
Fold 4 IBS: 0.19134902250179098
Fold 5 IBS: 0.22306046827688025
[I 2024-04-13 18:31:52,632] Trial 12 finished with value: 0.201602598996669 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 214, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.2683866363584086, 'min_weight_fraction_leaf': 0.0005781139040304361}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18457922325253104
Fold 2 IBS: 0.21838922184857518
Fold 3 IBS: 0.18865143410824403
Fold 4 IBS: 0.19060955721322728
Fold 5 IBS: 0.22573660368312398
[I 2024-04-13 18:32:03,736] Trial 13 finished with value: 0.2015932080211403 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9638655338226161, 'min_weight_fraction_leaf': 0.16922765932800388}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.2139242004833309
Fold 2 IBS: 0.22063339342953675
Fold 3 IBS: 0.20543327096798636
Fold 4 IBS: 0.22521858786986126
Fold 5 IBS: 0.2170716312878449
[I 2024-04-13 18:32:10,859] Trial 14 finished with value: 0.21645621680771204 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.10322253994980501, 'min_weight_fraction_leaf': 0.07318050492704681}. Best is trial 7 with value: 0.19566118486435183.

Fold 1 IBS: 0.21397899766980513
Fold 2 IBS: 0.22119491249175238
Fold 3 IBS: 0.20501286878802247
Fold 4 IBS: 0.2247338457207233
Fold 5 IBS: 0.21814874287282784
[I 2024-04-13 18:32:20,659] Trial 15 finished with value: 0.2166138735086262 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 15, 'n_estimators': 379, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.33528007217980527, 'min_weight_fraction_leaf': 0.42361711480884395}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1806204511868358
Fold 2 IBS: 0.2136817725505626
Fold 3 IBS: 0.18460341306445016
Fold 4 IBS: 0.1835302854386435
Fold 5 IBS: 0.22497321504159398
[I 2024-04-13 18:32:36,762] Trial 16 finished with value: 0.1974818274564172 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 493, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6536453784519287, 'min_weight_fraction_leaf': 0.03818486015953676}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.19221382273733162
Fold 2 IBS: 0.21924302642533872
Fold 3 IBS: 0.19302057522702087
Fold 4 IBS: 0.2092290882928806
Fold 5 IBS: 0.2198118479137175
[I 2024-04-13 18:32:53,180] Trial 17 finished with value: 0.20670367211925783 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 493, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8884180578214513, 'min_weight_fraction_leaf': 0.36160662849739067}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.19555893009148453
Fold 2 IBS: 0.2194312770162627
Fold 3 IBS: 0.19101456049213858
Fold 4 IBS: 0.20697893973705506
Fold 5 IBS: 0.22408124682698147
[I 2024-04-13 18:32:54,878] Trial 18 finished with value: 0.20741299083278447 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 23, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.635457264859255, 'min_weight_fraction_leaf': 0.18605021589393816}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1802052070539101
Fold 2 IBS: 0.21395559076981333
Fold 3 IBS: 0.18656154327113936
Fold 4 IBS: 0.1831310922875697
Fold 5 IBS: 0.2257679528007263
[I 2024-04-13 18:33:00,213] Trial 19 finished with value: 0.19792427723663178 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 141, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6831327987735002, 'min_weight_fraction_leaf': 0.05567354271014018}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18591341814476828
Fold 2 IBS: 0.21597910519224403
Fold 3 IBS: 0.18768289521384093
Fold 4 IBS: 0.18988030509757856
Fold 5 IBS: 0.223550225956684
[I 2024-04-13 18:33:07,958] Trial 20 finished with value: 0.20060118992102316 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 1, 'n_estimators': 242, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8746512426406728, 'min_weight_fraction_leaf': 0.1092354718367409}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18165803112097154
Fold 2 IBS: 0.21457850267488923
Fold 3 IBS: 0.18760829756413228
Fold 4 IBS: 0.1854530551382621
Fold 5 IBS: 0.22408369647820434
[I 2024-04-13 18:33:12,175] Trial 21 finished with value: 0.1986763165952919 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 112, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6647253837986332, 'min_weight_fraction_leaf': 0.0514767164471617}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1824558640908348
Fold 2 IBS: 0.21348598733668
Fold 3 IBS: 0.18622615215006935
Fold 4 IBS: 0.18623757730470122
Fold 5 IBS: 0.2252422651255419
[I 2024-04-13 18:33:16,762] Trial 22 finished with value: 0.19872956920156545 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 166, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7012203687886621, 'min_weight_fraction_leaf': 0.0413390196683173}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18808692885486805
Fold 2 IBS: 0.21959495461560674
Fold 3 IBS: 0.19041983196419582
Fold 4 IBS: 0.19577687451394318
Fold 5 IBS: 0.2231163178371679
[I 2024-04-13 18:33:27,187] Trial 23 finished with value: 0.20339898155715633 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 325, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.44236466344473546, 'min_weight_fraction_leaf': 0.13411382575564806}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.17846215043681363
Fold 2 IBS: 0.2142359123617848
Fold 3 IBS: 0.1842970057431464
Fold 4 IBS: 0.18281209556254596
Fold 5 IBS: 0.22555990456259603
[I 2024-04-13 18:33:30,293] Trial 24 finished with value: 0.19707341373337736 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 87, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8838920474499801, 'min_weight_fraction_leaf': 0.04917014729703097}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1900956346857614
Fold 2 IBS: 0.21846035665761132
Fold 3 IBS: 0.19037249941158393
Fold 4 IBS: 0.19705756699537244
Fold 5 IBS: 0.22270515029208818
[I 2024-04-13 18:33:32,895] Trial 25 finished with value: 0.20373824160848347 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 75, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8989041493525656, 'min_weight_fraction_leaf': 0.24231962244941954}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18591359481717848
Fold 2 IBS: 0.21571102091011485
Fold 3 IBS: 0.18954532573865554
Fold 4 IBS: 0.19888666850667122
Fold 5 IBS: 0.22407138674392385
[I 2024-04-13 18:33:34,001] Trial 26 finished with value: 0.2028255993433088 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 14, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8530313428307515, 'min_weight_fraction_leaf': 0.09666572299489368}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18105737159178265
Fold 2 IBS: 0.2143246140463885
Fold 3 IBS: 0.18557890487308884
Fold 4 IBS: 0.18558171247546393
Fold 5 IBS: 0.22527790409995102
[I 2024-04-13 18:33:39,715] Trial 27 finished with value: 0.19836410141733501 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 196, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9947095577564384, 'min_weight_fraction_leaf': 0.031166036698169683}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.15320331871510853
Fold 2 IBS: 0.24913975059679835
Fold 3 IBS: 0.1857952907122326
Fold 4 IBS: 0.15577405066144728
Fold 5 IBS: 0.27665939707830683
[I 2024-04-13 18:33:47,043] Trial 28 finished with value: 0.20411436155277873 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 254, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.949706768823161, 'min_weight_fraction_leaf': 0.16298179421858316}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.17942256460314426
Fold 2 IBS: 0.21488890999850946
Fold 3 IBS: 0.1852132085662453
Fold 4 IBS: 0.18487150592646706
Fold 5 IBS: 0.2255653653011453
[I 2024-04-13 18:33:57,888] Trial 29 finished with value: 0.19799231087910227 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 389, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.73650015077135, 'min_weight_fraction_leaf': 0.08962850536510933}. Best is trial 7 with value: 0.19566118486435183.

Fold 1 IBS: 0.18924477737479084
Fold 2 IBS: 0.21799018832154027
Fold 3 IBS: 0.19085735726014838
Fold 4 IBS: 0.19739387248975301
Fold 5 IBS: 0.22297685200412704
[I 2024-04-13 18:34:00,306] Trial 30 finished with value: 0.2036926094900719 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 71, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8258632202024414, 'min_weight_fraction_leaf': 0.20241101766143602}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1838565603858093
Fold 2 IBS: 0.21310814139547
Fold 3 IBS: 0.18816591366268318
Fold 4 IBS: 0.18856139746979875
Fold 5 IBS: 0.2241428176297601
[I 2024-04-13 18:34:04,159] Trial 31 finished with value: 0.19956696610870425 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 133, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6053815899973549, 'min_weight_fraction_leaf': 0.0743722755653283}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18316094581819767
Fold 2 IBS: 0.21502203936899772
Fold 3 IBS: 0.18641509976160356
Fold 4 IBS: 0.18726677397022443
Fold 5 IBS: 0.2246743622644168
[I 2024-04-13 18:34:08,846] Trial 32 finished with value: 0.19930784423668804 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 166, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.717200420350947, 'min_weight_fraction_leaf': 0.033055097688339904}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1854129189126276
Fold 2 IBS: 0.21367350722675083
Fold 3 IBS: 0.18725002471883423
Fold 4 IBS: 0.18968499135620312
Fold 5 IBS: 0.2236437880285479
[I 2024-04-13 18:34:12,038] Trial 33 finished with value: 0.19993304604859272 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 109, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4852562573068969, 'min_weight_fraction_leaf': 0.057248685594014664}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1569615274362479
Fold 2 IBS: 0.2415769276080622
Fold 3 IBS: 0.18017280449606032
Fold 4 IBS: 0.15091936532146705
Fold 5 IBS: 0.2712397577028735
[I 2024-04-13 18:34:14,158] Trial 34 finished with value: 0.2001740765129422 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 60, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9045396157935386, 'min_weight_fraction_leaf': 0.09997502171855718}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18704468199901486
Fold 2 IBS: 0.21670762582507433
Fold 3 IBS: 0.18912483944115235
Fold 4 IBS: 0.19233979332916226
Fold 5 IBS: 0.22468594910454917
[I 2024-04-13 18:34:18,996] Trial 35 finished with value: 0.2019805779397906 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 19, 'n_estimators': 141, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6737644096968876, 'min_weight_fraction_leaf': 0.027100156057869546}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18213676411837862
Fold 2 IBS: 0.21593853702897697
Fold 3 IBS: 0.18660417268156407
Fold 4 IBS: 0.18874325529081545
Fold 5 IBS: 0.2250705829463418
[I 2024-04-13 18:34:26,125] Trial 36 finished with value: 0.19969866241321538 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7855851556187663, 'min_weight_fraction_leaf': 0.12300175093789192}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1794581213997596
Fold 2 IBS: 0.21511937877104959
Fold 3 IBS: 0.18552378920765938
Fold 4 IBS: 0.18428749587410362
Fold 5 IBS: 0.2258273359758277
[I 2024-04-13 18:34:36,354] Trial 37 finished with value: 0.19804322424567997 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 333, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.930695252095938, 'min_weight_fraction_leaf': 0.07777111877585957}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.18669671041803898
Fold 2 IBS: 0.21905593708181115
Fold 3 IBS: 0.18911685579556065
Fold 4 IBS: 0.19352650190774734
Fold 5 IBS: 0.22467926537263683
[I 2024-04-13 18:34:48,299] Trial 38 finished with value: 0.20261505411515895 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 414, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5085852464089775, 'min_weight_fraction_leaf': 0.1421286560947102}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.21396961033854078
Fold 2 IBS: 0.22139028772223554
Fold 3 IBS: 0.20489726956084445
Fold 4 IBS: 0.22458794968177886
Fold 5 IBS: 0.21842205062518424
[I 2024-04-13 18:35:03,843] Trial 39 finished with value: 0.2166534335857168 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 469, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.40481881699161604, 'min_weight_fraction_leaf': 0.29459574453988674}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1863219680929521
Fold 2 IBS: 0.21715115858075076
Fold 3 IBS: 0.18889439293275673
Fold 4 IBS: 0.19190299212948833
Fold 5 IBS: 0.22478599318243137
[I 2024-04-13 18:35:09,031] Trial 40 finished with value: 0.20181130098367586 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 181, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6070834891430421, 'min_weight_fraction_leaf': 0.022378030164210663}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.17978016188924792
Fold 2 IBS: 0.2147951204540773
Fold 3 IBS: 0.18518422342445934
Fold 4 IBS: 0.18499974282648032
Fold 5 IBS: 0.22571780421420395
[I 2024-04-13 18:35:18,814] Trial 41 finished with value: 0.19809541056169377 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7261449079774867, 'min_weight_fraction_leaf': 0.08632697548620948}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.1794589325170719
Fold 2 IBS: 0.21445132256198499
Fold 3 IBS: 0.18479375732425726
Fold 4 IBS: 0.18225502600810245
Fold 5 IBS: 0.2261958656666783
[I 2024-04-13 18:35:27,535] Trial 42 finished with value: 0.197430980815619 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 343, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7520555329886992, 'min_weight_fraction_leaf': 0.05599381777324058}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.17892273711150122
Fold 2 IBS: 0.21509169219193322
Fold 3 IBS: 0.18522044498703544
Fold 4 IBS: 0.18293987133999973
Fold 5 IBS: 0.2258758594978607
[I 2024-04-13 18:35:36,181] Trial 43 finished with value: 0.19761012102566605 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8365887196168282, 'min_weight_fraction_leaf': 0.053050718645247026}. Best is trial 7 with value: 0.19566118486435183.
Fold 1 IBS: 0.17757338590461497
Fold 2 IBS: 0.2149038973216175
Fold 3 IBS: 0.18456305638813994
Fold 4 IBS: 0.18146031713728156
Fold 5 IBS: 0.2266724403564482
[I 2024-04-13 18:35:44,114] Trial 44 finished with value: 0.19703461942162043 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.827035140677233, 'min_weight_fraction_leaf': 0.019927146702100718}. Best is trial 7 with value: 0.19566118486435183.

Fold 1 IBS: 0.1703204366046531
Fold 2 IBS: 0.21025469102399516
Fold 3 IBS: 0.17796886722259822
Fold 4 IBS: 0.16660788588877593
Fold 5 IBS: 0.2275290168888809
[I 2024-04-13 18:35:52,288] Trial 45 finished with value: 0.19053617952578067 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9986783002201525, 'min_weight_fraction_leaf': 0.004760507523990938}. Best is trial 45 with value: 0.19053617952578067.
Fold 1 IBS: 0.1716324348804869
Fold 2 IBS: 0.20993208788565448
Fold 3 IBS: 0.1789141654409001
Fold 4 IBS: 0.16837132365543245
Fold 5 IBS: 0.2264063005267728
[I 2024-04-13 18:36:03,076] Trial 46 finished with value: 0.19105126247784934 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9907862185231335, 'min_weight_fraction_leaf': 0.016955252976757165}. Best is trial 45 with value: 0.19053617952578067.
Fold 1 IBS: 0.17141776601097988
Fold 2 IBS: 0.21033313099030274
Fold 3 IBS: 0.1788297577951236
Fold 4 IBS: 0.16849058956905938
Fold 5 IBS: 0.22698581117819555
[I 2024-04-13 18:36:12,830] Trial 47 finished with value: 0.19121141110873224 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 291, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9958942993507406, 'min_weight_fraction_leaf': 0.020073324476870255}. Best is trial 45 with value: 0.19053617952578067.
Fold 1 IBS: 0.1700357112025686
Fold 2 IBS: 0.20992242208933873
Fold 3 IBS: 0.17802811332902982
Fold 4 IBS: 0.16595386766020598
Fold 5 IBS: 0.22744967114394235
[I 2024-04-13 18:36:22,935] Trial 48 finished with value: 0.19027795708501707 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 297, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9986927263388606, 'min_weight_fraction_leaf': 0.002877035183488596}. Best is trial 48 with value: 0.19027795708501707.
Fold 1 IBS: 0.17684335348549365
Fold 2 IBS: 0.21004641175476513
Fold 3 IBS: 0.1782937988378102
Fold 4 IBS: 0.16769914563898292
Fold 5 IBS: 0.22842340221045923
[I 2024-04-13 18:36:32,207] Trial 49 finished with value: 0.1922612223855022 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 280, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9838629855583365, 'min_weight_fraction_leaf': 0.005090137185324226}. Best is trial 48 with value: 0.19027795708501707.
Fold 1 IBS: 0.17635762766929902
Fold 2 IBS: 0.21021986137401882
Fold 3 IBS: 0.1809022058312201
Fold 4 IBS: 0.1742113304539245
Fold 5 IBS: 0.2249402408227272
[I 2024-04-13 18:36:42,763] Trial 50 finished with value: 0.19332625323023794 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 293, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9399070707281479, 'min_weight_fraction_leaf': 0.008248016832204151}. Best is trial 48 with value: 0.19027795708501707.
Fold 1 IBS: 0.17569300225473283
Fold 2 IBS: 0.2103512550959172
Fold 3 IBS: 0.18085080755519606
Fold 4 IBS: 0.17428444352504696
Fold 5 IBS: 0.2252749547812986
[I 2024-04-13 18:36:52,749] Trial 51 finished with value: 0.19329089264243837 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 280, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9988046252837648, 'min_weight_fraction_leaf': 0.0005791027571267274}. Best is trial 48 with value: 0.19027795708501707.
Fold 1 IBS: 0.17702809623523214
Fold 2 IBS: 0.2097780490846424
Fold 3 IBS: 0.17831730018281722
Fold 4 IBS: 0.1677127017627872
Fold 5 IBS: 0.22848493808260786
[I 2024-04-13 18:37:02,363] Trial 52 finished with value: 0.19226421706961735 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 276, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9798423737372163, 'min_weight_fraction_leaf': 0.001480389858468087}. Best is trial 48 with value: 0.19027795708501707.
Fold 1 IBS: 0.17265712474829384
Fold 2 IBS: 0.21176068171580162
Fold 3 IBS: 0.17399460605338057
Fold 4 IBS: 0.15596721179684545
Fold 5 IBS: 0.2303516868778267
[I 2024-04-13 18:37:10,255] Trial 53 finished with value: 0.18894626223842964 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 237, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9320344823662657, 'min_weight_fraction_leaf': 0.0008823184079615118}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17310856093762936
Fold 2 IBS: 0.21114524692604317
Fold 3 IBS: 0.1790823074148776
Fold 4 IBS: 0.16916084248920255
Fold 5 IBS: 0.22563498285692585
[I 2024-04-13 18:37:18,924] Trial 54 finished with value: 0.1916263881249357 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 238, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9201411663344998, 'min_weight_fraction_leaf': 0.01834770980081423}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17284727345692294
Fold 2 IBS: 0.21253745089987583
Fold 3 IBS: 0.17958221633892751
Fold 4 IBS: 0.17148619023102227
Fold 5 IBS: 0.22664815958827564
[I 2024-04-13 18:37:26,700] Trial 55 finished with value: 0.19262025810300484 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 229, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9280173224989334, 'min_weight_fraction_leaf': 0.020574804235243854}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.21397188614669696
Fold 2 IBS: 0.22139746834006352
Fold 3 IBS: 0.2048048307179599
Fold 4 IBS: 0.22463989507791254
Fold 5 IBS: 0.2185737452542027
[I 2024-04-13 18:37:39,409] Trial 56 finished with value: 0.21667756510736713 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 311, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9153145442083498, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.1770643113671612
Fold 2 IBS: 0.21354249150027133
Fold 3 IBS: 0.18307645869318523
Fold 4 IBS: 0.1782281807965793
Fold 5 IBS: 0.22711361950244704
[I 2024-04-13 18:37:48,358] Trial 57 finished with value: 0.19580501237192882 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 251, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9564443213324091, 'min_weight_fraction_leaf': 0.06496004251207682}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17547110676842156
Fold 2 IBS: 0.21132177166126315
Fold 3 IBS: 0.18090892459632665
Fold 4 IBS: 0.1731999704672583
Fold 5 IBS: 0.2258062672997824
[I 2024-04-13 18:37:57,513] Trial 58 finished with value: 0.1933416081586104 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8673581560206142, 'min_weight_fraction_leaf': 0.02113739762936735}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.19028608387922316
Fold 2 IBS: 0.21919429334283416
Fold 3 IBS: 0.192592783245311
Fold 4 IBS: 0.20829068970937242
Fold 5 IBS: 0.22066536357763208
[I 2024-04-13 18:38:12,245] Trial 59 finished with value: 0.20620584275087456 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 356, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9543977910042604, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 53 with value: 0.18894626223842964.

Fold 1 IBS: 0.184274939538523
Fold 2 IBS: 0.21449071346216647
Fold 3 IBS: 0.18683984328033068
Fold 4 IBS: 0.18862158723101846
Fold 5 IBS: 0.22342867248504114
[I 2024-04-13 18:38:24,017] Trial 60 finished with value: 0.19953115119941595 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 264, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9208992051748564, 'min_weight_fraction_leaf': 0.03681620368970328}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.1836552976058727
Fold 2 IBS: 0.2136549386921458
Fold 3 IBS: 0.1867615542979982
Fold 4 IBS: 0.18959745987948876
Fold 5 IBS: 0.22360735647497929
[I 2024-04-13 18:38:35,540] Trial 61 finished with value: 0.19945532139009697 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 292, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9964977138363789, 'min_weight_fraction_leaf': 0.00043501430260946966}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17117994348054727
Fold 2 IBS: 0.21038525067787447
Fold 3 IBS: 0.17700860888001563
Fold 4 IBS: 0.15991341534297837
Fold 5 IBS: 0.22922526497835197
[I 2024-04-13 18:38:47,279] Trial 62 finished with value: 0.18954249667195353 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 318, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9604637010257221, 'min_weight_fraction_leaf': 0.013861886341033695}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.1740643050982753
Fold 2 IBS: 0.21345605511848922
Fold 3 IBS: 0.1810512403565827
Fold 4 IBS: 0.1744082559671094
Fold 5 IBS: 0.22645459142337523
[I 2024-04-13 18:39:02,316] Trial 63 finished with value: 0.19388688959276637 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 319, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9611878954554883, 'min_weight_fraction_leaf': 0.04114485873651948}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.18719593822599892
Fold 2 IBS: 0.2187328460928218
Fold 3 IBS: 0.1889382556346196
Fold 4 IBS: 0.19282298855170463
Fold 5 IBS: 0.2248047646129912
[I 2024-04-13 18:39:11,248] Trial 64 finished with value: 0.20249895862362727 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 4, 'n_estimators': 219, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8850243909718964, 'min_weight_fraction_leaf': 0.014503693852876998}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17919304820045762
Fold 2 IBS: 0.21433923257959284
Fold 3 IBS: 0.18410949063806123
Fold 4 IBS: 0.1816742488497443
Fold 5 IBS: 0.2264416519317355
[I 2024-04-13 18:39:18,861] Trial 65 finished with value: 0.19715153443991829 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 198, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.07308094406509837}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.21397140803070977
Fold 2 IBS: 0.22134042313048596
Fold 3 IBS: 0.20481631890568547
Fold 4 IBS: 0.2246300626956995
Fold 5 IBS: 0.21859468117576816
[I 2024-04-13 18:39:31,228] Trial 66 finished with value: 0.21667057878766977 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 309, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17848702715826206
Fold 2 IBS: 0.21539591034811664
Fold 3 IBS: 0.18591928977821678
Fold 4 IBS: 0.18481403061209514
Fold 5 IBS: 0.22606087369000624
[I 2024-04-13 18:39:40,884] Trial 67 finished with value: 0.19813542631733938 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 265, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9146778226470277, 'min_weight_fraction_leaf': 0.10996708383439274}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.15888430682057877
Fold 2 IBS: 0.2458587660377994
Fold 3 IBS: 0.18013166024669014
Fold 4 IBS: 0.15685481460203018
Fold 5 IBS: 0.2724863282057065
[I 2024-04-13 18:39:50,448] Trial 68 finished with value: 0.202843175182561 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 234, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.793797669430143, 'min_weight_fraction_leaf': 0.04027317191249816}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17339460215767893
Fold 2 IBS: 0.21116357647187475
Fold 3 IBS: 0.1795921526594374
Fold 4 IBS: 0.16908300434114096
Fold 5 IBS: 0.22555389379179172
[I 2024-04-13 18:40:02,324] Trial 69 finished with value: 0.19175744588438476 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 354, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9429514256726095, 'min_weight_fraction_leaf': 0.02656755344195229}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.1770724161948764
Fold 2 IBS: 0.213160625131106
Fold 3 IBS: 0.18331983768690804
Fold 4 IBS: 0.18143780746630328
Fold 5 IBS: 0.2246872546895861
[I 2024-04-13 18:40:11,757] Trial 70 finished with value: 0.19593558823375598 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 2, 'n_estimators': 251, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9983077530203072, 'min_weight_fraction_leaf': 0.06420835624152443}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17364325524193994
Fold 2 IBS: 0.21076478638992593
Fold 3 IBS: 0.17991521766409463
Fold 4 IBS: 0.16933570565957953
Fold 5 IBS: 0.22553100138548207
[I 2024-04-13 18:40:25,362] Trial 71 finished with value: 0.19183799326820444 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 361, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9355755855781472, 'min_weight_fraction_leaf': 0.021090559041409572}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17619698700255726
Fold 2 IBS: 0.211167828731468
Fold 3 IBS: 0.18107114449236017
Fold 4 IBS: 0.17513295126223297
Fold 5 IBS: 0.22484817776154462
[I 2024-04-13 18:40:40,401] Trial 72 finished with value: 0.1936834178500326 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 341, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.895558223233324, 'min_weight_fraction_leaf': 0.03019299172433057}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17339501092404455
Fold 2 IBS: 0.21285299025650886
Fold 3 IBS: 0.1810899379927016
Fold 4 IBS: 0.17565783600330248
Fold 5 IBS: 0.22551428212145003
[I 2024-04-13 18:40:51,314] Trial 73 finished with value: 0.19370201145960148 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 299, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9662458102901887, 'min_weight_fraction_leaf': 0.04246726941752761}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17363271048096338
Fold 2 IBS: 0.21334406122234753
Fold 3 IBS: 0.18030486516612312
Fold 4 IBS: 0.17140214054865863
Fold 5 IBS: 0.22645790069416777
[I 2024-04-13 18:41:02,978] Trial 74 finished with value: 0.19302833562245209 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 318, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9439230940567749, 'min_weight_fraction_leaf': 0.014245360777983466}. Best is trial 53 with value: 0.18894626223842964.

Fold 1 IBS: 0.17437167064723375
Fold 2 IBS: 0.2135778688097458
Fold 3 IBS: 0.18267487121953555
Fold 4 IBS: 0.17744152361550006
Fold 5 IBS: 0.22599792012746062
[I 2024-04-13 18:41:13,275] Trial 75 finished with value: 0.19481277088389515 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 285, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8614518880476894, 'min_weight_fraction_leaf': 0.046111499155040925}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.18779799569555847
Fold 2 IBS: 0.2194030153528527
Fold 3 IBS: 0.19008139742953345
Fold 4 IBS: 0.1935917032465536
Fold 5 IBS: 0.22499236176871223
[I 2024-04-13 18:41:25,079] Trial 76 finished with value: 0.20317329469864212 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 331, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9020299212785601, 'min_weight_fraction_leaf': 0.2403778805377752}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.17959377564053372
Fold 2 IBS: 0.21415125353405906
Fold 3 IBS: 0.18509781289611074
Fold 4 IBS: 0.18344404626612498
Fold 5 IBS: 0.22413954788534787
[I 2024-04-13 18:41:37,872] Trial 77 finished with value: 0.19728528724443525 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 373, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9710181742593009, 'min_weight_fraction_leaf': 0.08223661961775336}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.18228617461364952
Fold 2 IBS: 0.21471925134244643
Fold 3 IBS: 0.1856904317419058
Fold 4 IBS: 0.18225838032900457
Fold 5 IBS: 0.22354669569235244
[I 2024-04-13 18:41:51,574] Trial 78 finished with value: 0.19770018674387174 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 401, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.2227070909773673, 'min_weight_fraction_leaf': 0.02967876550691668}. Best is trial 53 with value: 0.18894626223842964.
Fold 1 IBS: 0.16892176249926102
Fold 2 IBS: 0.2120959549438565
Fold 3 IBS: 0.17697156228606442
Fold 4 IBS: 0.1557123081181916
Fold 5 IBS: 0.2308466019050449
[I 2024-04-13 18:42:01,327] Trial 79 finished with value: 0.18890963795048368 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 268, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9358513866412379, 'min_weight_fraction_leaf': 0.0138253976427879}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.1767410674620255
Fold 2 IBS: 0.21422941048655622
Fold 3 IBS: 0.18390389513719557
Fold 4 IBS: 0.18032271455498475
Fold 5 IBS: 0.22750875282726216
[I 2024-04-13 18:42:10,745] Trial 80 finished with value: 0.19654116809360483 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 266, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.819299828652045, 'min_weight_fraction_leaf': 0.06873712980474972}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.17031861372629584
Fold 2 IBS: 0.20941356633797967
Fold 3 IBS: 0.1771365561308502
Fold 4 IBS: 0.16094602273755496
Fold 5 IBS: 0.2291892382121014
[I 2024-04-13 18:42:21,803] Trial 81 finished with value: 0.18940079942895643 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.943860771108682, 'min_weight_fraction_leaf': 0.010486045988261146}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.16833209458536894
Fold 2 IBS: 0.21144189932450377
Fold 3 IBS: 0.17805121433327656
Fold 4 IBS: 0.1605062229536944
Fold 5 IBS: 0.22861562317084824
[I 2024-04-13 18:42:32,408] Trial 82 finished with value: 0.1893894108735384 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9742186878953666, 'min_weight_fraction_leaf': 0.012572344381097606}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.1681973414317143
Fold 2 IBS: 0.2114882842255316
Fold 3 IBS: 0.17774747173665287
Fold 4 IBS: 0.16026982645768234
Fold 5 IBS: 0.2283539644325119
[I 2024-04-13 18:42:44,116] Trial 83 finished with value: 0.18921137765681859 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 306, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9771521007301615, 'min_weight_fraction_leaf': 0.011703452749764899}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.1676776598164303
Fold 2 IBS: 0.2147070717224989
Fold 3 IBS: 0.17815683625178455
Fold 4 IBS: 0.16211244212736423
Fold 5 IBS: 0.2292209442307709
[I 2024-04-13 18:42:55,615] Trial 84 finished with value: 0.19037499082976977 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 328, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.882049550389461, 'min_weight_fraction_leaf': 0.00022921105600090183}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.21393048903001483
Fold 2 IBS: 0.22035249765395915
Fold 3 IBS: 0.2052393529978709
Fold 4 IBS: 0.22510350932778364
Fold 5 IBS: 0.21703849468207653
[I 2024-04-13 18:43:06,339] Trial 85 finished with value: 0.216332868738341 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 307, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.10698873156508726, 'min_weight_fraction_leaf': 0.055617530662623926}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.17425030701822272
Fold 2 IBS: 0.21512309890837664
Fold 3 IBS: 0.18180445177094878
Fold 4 IBS: 0.17608890196435742
Fold 5 IBS: 0.22625308361437635
[I 2024-04-13 18:43:17,273] Trial 86 finished with value: 0.19470396865525638 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 326, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8730212604708996, 'min_weight_fraction_leaf': 0.008841631129174798}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.17232227054070925
Fold 2 IBS: 0.21403055971896445
Fold 3 IBS: 0.1807524600983417
Fold 4 IBS: 0.17312515937784126
Fold 5 IBS: 0.2266614941460698
[I 2024-04-13 18:43:27,546] Trial 87 finished with value: 0.19337838877638527 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 305, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8440025695437073, 'min_weight_fraction_leaf': 0.0358480811544889}. Best is trial 79 with value: 0.18890963795048368.
Fold 1 IBS: 0.17165212375145453
Fold 2 IBS: 0.21862053449589458
Fold 3 IBS: 0.17451778241400842
Fold 4 IBS: 0.14173830683002414
Fold 5 IBS: 0.23531305642493677
[I 2024-04-13 18:43:38,376] Trial 88 finished with value: 0.18836836078326372 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8883209781210527, 'min_weight_fraction_leaf': 0.0027749857774926326}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.1674320413135407
Fold 2 IBS: 0.2360253521676515
Fold 3 IBS: 0.1709817253061173
Fold 4 IBS: 0.13112717057718493
Fold 5 IBS: 0.24232908731472017
[I 2024-04-13 18:43:50,819] Trial 89 finished with value: 0.1895790753358429 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 337, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.885250193259915, 'min_weight_fraction_leaf': 0.0009919448935811603}. Best is trial 88 with value: 0.18836836078326372.

Fold 1 IBS: 0.15808052483464857
Fold 2 IBS: 0.24513001845338123
Fold 3 IBS: 0.17353386158892606
Fold 4 IBS: 0.1414323854793232
Fold 5 IBS: 0.2630100664214536
[I 2024-04-13 18:44:03,680] Trial 90 finished with value: 0.19623737135554653 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 344, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8925947395705395, 'min_weight_fraction_leaf': 0.04616859454268613}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.16806680758384937
Fold 2 IBS: 0.23525934869183998
Fold 3 IBS: 0.17105625756502627
Fold 4 IBS: 0.13250701046302357
Fold 5 IBS: 0.24272974372536513
[I 2024-04-13 18:44:14,984] Trial 91 finished with value: 0.18992383360582088 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 332, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9365032485864714, 'min_weight_fraction_leaf': 0.0014903860884488986}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.16314680173068632
Fold 2 IBS: 0.24026629333850855
Fold 3 IBS: 0.1707491922354808
Fold 4 IBS: 0.1341235445083268
Fold 5 IBS: 0.24649289368826005
[I 2024-04-13 18:44:27,727] Trial 92 finished with value: 0.1909557451002525 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 366, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9426172890667525, 'min_weight_fraction_leaf': 0.00928274865680847}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.15902484674895673
Fold 2 IBS: 0.24410614947688142
Fold 3 IBS: 0.1730007695998191
Fold 4 IBS: 0.13624453298937012
Fold 5 IBS: 0.2576263314123465
[I 2024-04-13 18:44:38,460] Trial 93 finished with value: 0.19400052604547477 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 318, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9710026251363465, 'min_weight_fraction_leaf': 0.029622936623472533}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.16486322266341427
Fold 2 IBS: 0.23918638062022954
Fold 3 IBS: 0.170603668196101
Fold 4 IBS: 0.1358470357037834
Fold 5 IBS: 0.24779008663689728
[I 2024-04-13 18:44:50,852] Trial 94 finished with value: 0.19165807876408508 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 338, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8133833194663921, 'min_weight_fraction_leaf': 0.012620038149158554}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.15785016948154904
Fold 2 IBS: 0.24333412832356732
Fold 3 IBS: 0.17413731507884783
Fold 4 IBS: 0.14276002962075066
Fold 5 IBS: 0.2638023956273605
[I 2024-04-13 18:45:02,334] Trial 95 finished with value: 0.19637680762641507 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 271, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9100761411983858, 'min_weight_fraction_leaf': 0.05461596308708522}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.15120811512019253
Fold 2 IBS: 0.24808736122126593
Fold 3 IBS: 0.1858932104642336
Fold 4 IBS: 0.1577519922032335
Fold 5 IBS: 0.2640611072629506
[I 2024-04-13 18:45:15,421] Trial 96 finished with value: 0.20140035725437522 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 385, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.933286674217365, 'min_weight_fraction_leaf': 0.3157465264411285}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.15918101172724888
Fold 2 IBS: 0.24394364011780217
Fold 3 IBS: 0.17331014223214955
Fold 4 IBS: 0.137848066003882
Fold 5 IBS: 0.2595498364533643
[I 2024-04-13 18:45:27,767] Trial 97 finished with value: 0.19476653930688942 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 354, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9560804269546791, 'min_weight_fraction_leaf': 0.0313203580419089}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.1698815591273314
Fold 2 IBS: 0.21182776429889047
Fold 3 IBS: 0.17877584572854088
Fold 4 IBS: 0.16226690679611244
Fold 5 IBS: 0.2291705628922113
[I 2024-04-13 18:45:36,561] Trial 98 finished with value: 0.1903845277686173 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 253, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7621608770811905, 'min_weight_fraction_leaf': 0.010929715771043076}. Best is trial 88 with value: 0.18836836078326372.
Fold 1 IBS: 0.15676292027708186
Fold 2 IBS: 0.24435090110745555
Fold 3 IBS: 0.17359097651135838
Fold 4 IBS: 0.1416825630758518
Fold 5 IBS: 0.2635982731341568
[I 2024-04-13 18:45:46,807] Trial 99 finished with value: 0.19599712682118087 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 278, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8443660540069339, 'min_weight_fraction_leaf': 0.048109709064868805}. Best is trial 88 with value: 0.18836836078326372.


* Best trial for IBS:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.18836836078326372], datetime_start=datetime.datetime(2024, 4, 13, 18, 43, 27, 551718), datetime_complete=datetime.datetime(2024, 4, 13, 18, 43, 38, 374859), params={'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 335, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8883209781210527, 'min_weight_fraction_leaf': 0.0027749857774926326}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=88, value=None)


* Best Score for IBS:
 0.18836836078326372

In [63]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [64]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.787
train_ibs:  0.188

#### Test

In [65]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [66]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=16,
                   max_samples=0.9351618935202715, min_samples_leaf=1,
                   min_samples_split=15,
                   min_weight_fraction_leaf=0.035839978360771345,
                   n_estimators=132, random_state=123, warm_start=True)

C-index score: 0.673

ExtraSurvivalTrees(max_depth=8, max_features=1, max_leaf_nodes=10,
                   max_samples=0.8883209781210527, min_samples_leaf=1,
                   min_samples_split=7,
                   min_weight_fraction_leaf=0.0027749857774926326,
                   n_estimators=335, oob_score=True, random_state=123,
                   warm_start=True)

IBS: 0.203

In [67]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [68]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-13 18:45:50,072] A new study created in memory with name: no-name-f659ab00-e558-4ae5-9d8c-249dcc3bb145

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:46:42,398] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:47:12,250] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:47:40,926] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:48:30,487] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:48:48,185] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:48:53,289] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:49:30,878] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:49:43,814] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:49:45,397] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7209821428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8523206751054853
Fold 5 C-index: 0.6455399061032864
[I 2024-04-13 18:51:36,787] Trial 9 finished with value: 0.7478429018287163 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 18:54:24,706] Trial 10 finished with value: 0.5840288051840454 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 18:57:40,558] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6515151515151515
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.8014705882352942
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 19:00:41,650] Trial 12 finished with value: 0.6900826421388505 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:02:12,747] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:04:26,610] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:06:15,308] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:07:34,658] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:10:05,183] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:13:36,110] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:13:44,932] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:15:07,239] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 19:18:11,932] Trial 21 finished with value: 0.5374601777330652 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7965686274509803
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5
[I 2024-04-13 19:21:21,138] Trial 22 finished with value: 0.6847183709502213 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:23:49,518] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.7608367802156369, 'learning_rate': 0.01191950460930238, 'dropout_rate': 0.314365505218826, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.9946740252123735, 'min_weight_fraction_leaf': 0.4640566782401924, 'max_features': 'auto', 'min_impurity_decrease': 3.881464387117906e-06, 'validation_fraction': 0.8998135601964038, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:26:05,392] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.8722818625026802, 'learning_rate': 0.023760893448449078, 'dropout_rate': 0.21619246692598015, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.0850502916575932, 'max_features': 'auto', 'min_impurity_decrease': 4.05068584859472e-07, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:27:28,272] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.7565257046780437, 'learning_rate': 0.01188344684416992, 'dropout_rate': 0.3433523077110169, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 2.063559212730723, 'min_weight_fraction_leaf': 0.25401273903421573, 'max_features': 'auto', 'min_impurity_decrease': 5.773435946665558e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 19:30:26,031] Trial 26 finished with value: 0.5374601777330652 and parameters: {'subsample': 0.8922404482621683, 'learning_rate': 0.011585260292674536, 'dropout_rate': 0.2527000999648632, 'n_estimators': 446, 'criterion': 'friedman_mse', 'ccp_alpha': 0.11820935501930148, 'min_weight_fraction_leaf': 0.3509209656285343, 'max_features': 1, 'min_impurity_decrease': 2.941022248196409e-06, 'validation_fraction': 0.9367695063592092, 'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:33:24,314] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.28451691271554613, 'learning_rate': 0.05452181969732228, 'dropout_rate': 0.4224088852960579, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 4.247561534591026, 'min_weight_fraction_leaf': 0.4279178795390794, 'max_features': 'sqrt', 'min_impurity_decrease': 6.004485816985879e-05, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:35:47,512] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.4652279120562356, 'learning_rate': 0.027664888666087937, 'dropout_rate': 0.17569843341340402, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.2907315194520839, 'max_features': 0.1, 'min_impurity_decrease': 3.906545292686796e-07, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:37:32,809] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.6302037486664767, 'learning_rate': 0.035133458098740605, 'dropout_rate': 0.2977987672602068, 'n_estimators': 342, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.16718632341890002, 'max_features': 'log2', 'min_impurity_decrease': 1.347158126436966e-06, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 19:39:39,139] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.7584229383842384, 'learning_rate': 0.00821530314223665, 'dropout_rate': 0.519324095764564, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.7935147308287903, 'min_weight_fraction_leaf': 0.35623924020378417, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 20:11:18,057] Trial 31 finished with value: 0.5840288051840454 and parameters: {'subsample': 0.9815972584348283, 'learning_rate': 0.004298446871567765, 'dropout_rate': 0.16159534615434212, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.403297521035105, 'max_features': 'auto', 'min_impurity_decrease': 1.3656987012084737e-07, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:14:01,614] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.014646774096998348, 'dropout_rate': 0.1399919603917502, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.3697873043854524, 'max_features': 'auto', 'min_impurity_decrease': 1.0578449947162986e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:15:55,810] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.8569187310482049, 'learning_rate': 0.002338141100304182, 'dropout_rate': 0.2912601440264632, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 1.6207446695706205, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.8464382368624134, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:18:22,349] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.7050414276319562, 'learning_rate': 0.01736580349254983, 'dropout_rate': 0.22658656718653286, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6387415680643302, 'min_weight_fraction_leaf': 0.4889718572023061, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6432989441697915e-07, 'validation_fraction': 0.996536937663533, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:18:52,149] Trial 35 finished with value: 0.5 and parameters: {'subsample': 0.9259773449771448, 'learning_rate': 0.0013702833078771113, 'dropout_rate': 0.34791628140951375, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.892552268167881, 'min_weight_fraction_leaf': 0.3235914313183653, 'max_features': None, 'min_impurity_decrease': 2.4072948146321942e-05, 'validation_fraction': 0.35098020419861614, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:26,772] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.7969176327337065, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.14643759904477674, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.48997012949363994, 'min_weight_fraction_leaf': 0.2382235703018389, 'max_features': 'auto', 'min_impurity_decrease': 2.2723634470889422e-07, 'validation_fraction': 0.6516623501512859, 'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:21:31,619] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.9918756329516758, 'learning_rate': 0.00951363179460697, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 3.090891310373169, 'min_weight_fraction_leaf': 0.4368222726762345, 'max_features': None, 'min_impurity_decrease': 6.512646857242401e-06, 'validation_fraction': 0.7869508417751669, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 9 with value: 0.7478429018287163.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:22:26,566] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.020515226007100745, 'dropout_rate': 0.4076069474884072, 'n_estimators': 305, 'criterion': 'friedman_mse', 'ccp_alpha': 4.262315932175718, 'min_weight_fraction_leaf': 0.2917882999283137, 'max_features': 'auto', 'min_impurity_decrease': 1.0494748289619345e-07, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 2}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:23:51,303] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.9054539953742826, 'learning_rate': 0.008896528916563095, 'dropout_rate': 0.19989910804141944, 'n_estimators': 341, 'criterion': 'squared_error', 'ccp_alpha': 1.1534181050612955, 'min_weight_fraction_leaf': 0.49878571807534433, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.9432676198570591, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:26:17,864] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.6882525064531181, 'learning_rate': 0.03063064644312167, 'dropout_rate': 0.32312131703374025, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.5303400047432362, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 3.430163547552312e-05, 'validation_fraction': 0.5293758628752836, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 20:26:18,277] Trial 41 finished with value: 0.6975692731548933 and parameters: {'subsample': 0.9712777195221016, 'learning_rate': 0.004941343157848163, 'dropout_rate': 0.15481487884491515, 'n_estimators': 1, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.3915419506490768, 'max_features': 'auto', 'min_impurity_decrease': 1.5934934034999224e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.7294372294372294
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.6408450704225352
[I 2024-04-13 20:26:35,157] Trial 42 finished with value: 0.7027396895929152 and parameters: {'subsample': 0.9483076611574458, 'learning_rate': 0.014323935862649555, 'dropout_rate': 0.10817256750176155, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.0025776361420084756, 'min_weight_fraction_leaf': 0.37832698407925297, 'max_features': 'auto', 'min_impurity_decrease': 2.604629144998991e-07, 'validation_fraction': 0.862357061730979, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:26:36,029] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.8735505723796891, 'learning_rate': 0.013455915558851193, 'dropout_rate': 0.11585930219083569, 'n_estimators': 13, 'criterion': 'squared_error', 'ccp_alpha': 1.1546454041172216, 'min_weight_fraction_leaf': 0.4571018098895751, 'max_features': 'auto', 'min_impurity_decrease': 3.602802269963817e-07, 'validation_fraction': 0.8650432234384267, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:27:21,035] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.9479336661285427, 'learning_rate': 0.0149361535238727, 'dropout_rate': 0.25335630680617827, 'n_estimators': 238, 'criterion': 'squared_error', 'ccp_alpha': 0.5490150526266808, 'min_weight_fraction_leaf': 0.4126953497238681, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.9438667820963776, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7232142857142857
Fold 3 C-index: 0.7916666666666666
Fold 4 C-index: 0.8502109704641351
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 20:27:37,516] Trial 45 finished with value: 0.7393192198839372 and parameters: {'subsample': 0.5852424762732177, 'learning_rate': 0.06563850661049836, 'dropout_rate': 0.2110190711691961, 'n_estimators': 128, 'criterion': 'squared_error', 'ccp_alpha': 0.027804703729289008, 'min_weight_fraction_leaf': 0.262143273989599, 'max_features': 0.1, 'min_impurity_decrease': 9.467252666446998e-07, 'validation_fraction': 0.7243304021069044, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:27:41,256] Trial 46 finished with value: 0.5 and parameters: {'subsample': 0.5661584399210104, 'learning_rate': 0.0647255784094387, 'dropout_rate': 0.9694253886674298, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 1.980441868470768, 'min_weight_fraction_leaf': 0.2621149519999694, 'max_features': 0.1, 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.7149599360255287, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 15}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:28:05,591] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.45583884600027197, 'learning_rate': 0.06333641179361332, 'dropout_rate': 0.277647175493169, 'n_estimators': 172, 'criterion': 'squared_error', 'ccp_alpha': 6.758849676180972, 'min_weight_fraction_leaf': 0.22656948980323957, 'max_features': 0.1, 'min_impurity_decrease': 2.338475237116342e-06, 'validation_fraction': 0.6499098781754827, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:28:11,903] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.584713932884162, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.10579627176846597, 'n_estimators': 77, 'criterion': 'squared_error', 'ccp_alpha': 1.4079486283020177, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': 0.1, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.5884862057231304, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:28:12,639] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.5312512417393443, 'learning_rate': 0.08225901412267347, 'dropout_rate': 0.5923973592579648, 'n_estimators': 9, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3775922041148432, 'min_weight_fraction_leaf': 0.2017769745958864, 'max_features': 'log2', 'min_impurity_decrease': 6.319359312322429e-06, 'validation_fraction': 0.8162506488425402, 'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7478429018287163.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:28:14,812] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.052706271754983484, 'dropout_rate': 0.16730097671960129, 'n_estimators': 37, 'criterion': 'squared_error', 'ccp_alpha': 1.077209816707269, 'min_weight_fraction_leaf': 0.31040829786124846, 'max_features': 0.1, 'min_impurity_decrease': 1.0106089337747014e-06, 'validation_fraction': 0.6959936026682685, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7120535714285714
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.6549295774647887
[I 2024-04-13 20:28:30,083] Trial 51 finished with value: 0.7293985702556685 and parameters: {'subsample': 0.7946888792311653, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.2196446942108301, 'n_estimators': 129, 'criterion': 'squared_error', 'ccp_alpha': 0.012243801070742757, 'min_weight_fraction_leaf': 0.377285576216956, 'max_features': 'sqrt', 'min_impurity_decrease': 2.4617573739462015e-07, 'validation_fraction': 0.8872414026388215, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:28:41,884] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.7938796766715603, 'learning_rate': 0.006935256483137735, 'dropout_rate': 0.22725206143365784, 'n_estimators': 109, 'criterion': 'squared_error', 'ccp_alpha': 0.5430622755642927, 'min_weight_fraction_leaf': 0.36469952190521415, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0228458778096525e-07, 'validation_fraction': 0.7452334109475507, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.696078431372549
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.6549295774647887
[I 2024-04-13 20:29:05,107] Trial 53 finished with value: 0.6949551841555437 and parameters: {'subsample': 0.8384650935032024, 'learning_rate': 0.05877903849297955, 'dropout_rate': 0.13903096492039457, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 0.009781579144263263, 'min_weight_fraction_leaf': 0.33111548353893067, 'max_features': 'sqrt', 'min_impurity_decrease': 6.050673952258984e-07, 'validation_fraction': 0.8510965011841733, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:29:24,733] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8382706715280057, 'learning_rate': 0.059834764453264265, 'dropout_rate': 0.1393394383811932, 'n_estimators': 147, 'criterion': 'squared_error', 'ccp_alpha': 0.36136630118276447, 'min_weight_fraction_leaf': 0.33394996198154614, 'max_features': 'sqrt', 'min_impurity_decrease': 5.992505366041584e-07, 'validation_fraction': 0.8741639290304148, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:29:54,077] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9585113598999722, 'learning_rate': 0.07325243845075922, 'dropout_rate': 0.18784418429116978, 'n_estimators': 184, 'criterion': 'squared_error', 'ccp_alpha': 1.8144609045046565, 'min_weight_fraction_leaf': 0.38075085922772955, 'max_features': 'sqrt', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8412758177105166, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:30:38,401] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.7257778418738097, 'learning_rate': 0.06999105925124914, 'dropout_rate': 0.13064667596279733, 'n_estimators': 225, 'criterion': 'squared_error', 'ccp_alpha': 1.2616701535027603, 'min_weight_fraction_leaf': 0.34416523204017957, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6899787551457573e-07, 'validation_fraction': 0.7796105590928633, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 9}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6731601731601732
Fold 2 C-index: 0.7433035714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8016877637130801
Fold 5 C-index: 0.6596244131455399
[I 2024-04-13 20:31:36,964] Trial 57 finished with value: 0.7329081254659435 and parameters: {'subsample': 0.6446884806787394, 'learning_rate': 0.04907531443988286, 'dropout_rate': 0.1715758087877031, 'n_estimators': 267, 'criterion': 'squared_error', 'ccp_alpha': 0.0019473494055538935, 'min_weight_fraction_leaf': 0.30533630657618055, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0149584631969638e-07, 'validation_fraction': 0.673013820505939, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 8}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:32:32,581] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.656210021309656, 'learning_rate': 0.04307867883189742, 'dropout_rate': 0.3755785582478294, 'n_estimators': 283, 'criterion': 'squared_error', 'ccp_alpha': 0.7470877807882045, 'min_weight_fraction_leaf': 0.2655765791815008, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2064456191034667e-07, 'validation_fraction': 0.6060102141374549, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 8}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:33:29,886] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.5905915575203071, 'learning_rate': 0.09069842971120201, 'dropout_rate': 0.21508681671678376, 'n_estimators': 264, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.3051539123714827, 'max_features': None, 'min_impurity_decrease': 1.1153173582244227e-07, 'validation_fraction': 0.5613110344363563, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:33:33,468] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.47818247513165746, 'learning_rate': 0.04707490524681282, 'dropout_rate': 0.10039598556224508, 'n_estimators': 50, 'criterion': 'squared_error', 'ccp_alpha': 0.9156412072061137, 'min_weight_fraction_leaf': 0.2834981878637842, 'max_features': 'sqrt', 'min_impurity_decrease': 2.0210254169351383e-07, 'validation_fraction': 0.4826444492816219, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:33:51,401] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.6283159329761169, 'learning_rate': 0.05673769745326444, 'dropout_rate': 0.17142272981110848, 'n_estimators': 141, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.33013948862434317, 'max_features': 'sqrt', 'min_impurity_decrease': 4.7486007124123165e-07, 'validation_fraction': 0.7271755608042784, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 10}. Best is trial 9 with value: 0.7478429018287163.

Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 20:34:12,922] Trial 62 finished with value: 0.7466422394903277 and parameters: {'subsample': 0.5059596838360567, 'learning_rate': 0.060551160422225275, 'dropout_rate': 0.24111462309561266, 'n_estimators': 163, 'criterion': 'squared_error', 'ccp_alpha': 0.022616672247981386, 'min_weight_fraction_leaf': 0.3744656977809062, 'max_features': 'sqrt', 'min_impurity_decrease': 6.669380969762316e-07, 'validation_fraction': 0.8883924759880634, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6385281385281385
Fold 2 C-index: 0.703125
Fold 3 C-index: 0.7818627450980392
Fold 4 C-index: 0.770042194092827
Fold 5 C-index: 0.6431924882629108
[I 2024-04-13 20:34:20,874] Trial 63 finished with value: 0.7073501131963832 and parameters: {'subsample': 0.513621786055727, 'learning_rate': 0.07957578149356517, 'dropout_rate': 0.2494121815898241, 'n_estimators': 88, 'criterion': 'squared_error', 'ccp_alpha': 0.017463579724077027, 'min_weight_fraction_leaf': 0.41197263934105943, 'max_features': 'sqrt', 'min_impurity_decrease': 1.9789954442825003e-06, 'validation_fraction': 0.8921678195650715, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:34:29,812] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.5092980275464744, 'learning_rate': 0.08020346495506504, 'dropout_rate': 0.2603466948459836, 'n_estimators': 87, 'criterion': 'squared_error', 'ccp_alpha': 0.3667438715407871, 'min_weight_fraction_leaf': 0.41252566213461744, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7375428501365761e-06, 'validation_fraction': 0.8933954835780389, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:34:42,850] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.43369393192701555, 'learning_rate': 0.08721738177552787, 'dropout_rate': 0.32269254472382836, 'n_estimators': 121, 'criterion': 'squared_error', 'ccp_alpha': 0.8992306864937782, 'min_weight_fraction_leaf': 0.3726662707458388, 'max_features': 'sqrt', 'min_impurity_decrease': 4.555713910510501e-06, 'validation_fraction': 0.6850220941695035, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:35:07,622] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.4025321956973507, 'learning_rate': 0.09984676062907398, 'dropout_rate': 0.24064975284716697, 'n_estimators': 174, 'criterion': 'squared_error', 'ccp_alpha': 1.535648472371134, 'min_weight_fraction_leaf': 0.30241657992833976, 'max_features': 'sqrt', 'min_impurity_decrease': 9.793222205193242e-07, 'validation_fraction': 0.8205900237459285, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 11}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:35:18,213] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.5465356637711977, 'learning_rate': 0.06867839438668775, 'dropout_rate': 0.4308859881762669, 'n_estimators': 125, 'criterion': 'squared_error', 'ccp_alpha': 2.352310671798754, 'min_weight_fraction_leaf': 0.35090085557825806, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1364105105240193e-06, 'validation_fraction': 0.6806910348522865, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:35:30,677] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.5046730609842387, 'learning_rate': 0.07835944725027354, 'dropout_rate': 0.27407711736273627, 'n_estimators': 106, 'criterion': 'squared_error', 'ccp_alpha': 0.761492090851228, 'min_weight_fraction_leaf': 0.4788639875505124, 'max_features': 1, 'min_impurity_decrease': 2.950791562308042e-07, 'validation_fraction': 0.8911843640090912, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 13}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:35:36,014] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5942813876889104, 'learning_rate': 0.07195699981950454, 'dropout_rate': 0.2008200059558356, 'n_estimators': 59, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2840361129928317, 'min_weight_fraction_leaf': 0.2718811214911974, 'max_features': 'sqrt', 'min_impurity_decrease': 4.908483340449882e-07, 'validation_fraction': 0.7941641162945625, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 14}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6363636363636364
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.6807511737089202
[I 2024-04-13 20:36:14,478] Trial 70 finished with value: 0.7169445288691012 and parameters: {'subsample': 0.5632959909251363, 'learning_rate': 0.06270872065614194, 'dropout_rate': 0.29263691395762514, 'n_estimators': 205, 'criterion': 'squared_error', 'ccp_alpha': 0.010011659094920826, 'min_weight_fraction_leaf': 0.40027745147479976, 'max_features': 0.1, 'min_impurity_decrease': 3.0857838212846365e-07, 'validation_fraction': 0.7608434987328658, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 20:36:53,467] Trial 71 finished with value: 0.7470886680617562 and parameters: {'subsample': 0.5629361708051109, 'learning_rate': 0.06362981156766247, 'dropout_rate': 0.30534098323418335, 'n_estimators': 207, 'criterion': 'squared_error', 'ccp_alpha': 0.02647951541473475, 'min_weight_fraction_leaf': 0.4144859526129469, 'max_features': 0.1, 'min_impurity_decrease': 2.8920488173461134e-07, 'validation_fraction': 0.7536048380367574, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:37:36,330] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.5606206192959431, 'learning_rate': 0.06351781223534345, 'dropout_rate': 0.3015317740664555, 'n_estimators': 205, 'criterion': 'squared_error', 'ccp_alpha': 0.6675201566322883, 'min_weight_fraction_leaf': 0.41050025776310384, 'max_features': 0.1, 'min_impurity_decrease': 0.00013057230488441944, 'validation_fraction': 0.7482580656743414, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:38:04,896] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.5261639585918082, 'learning_rate': 0.06614767176173511, 'dropout_rate': 0.3498807338765095, 'n_estimators': 188, 'criterion': 'squared_error', 'ccp_alpha': 0.3563872779387915, 'min_weight_fraction_leaf': 0.4414428875556457, 'max_features': 0.1, 'min_impurity_decrease': 1.0453737208386394e-07, 'validation_fraction': 0.6395841440291709, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 20}. Best is trial 9 with value: 0.7478429018287163.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:38:55,902] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6137508858597334, 'learning_rate': 0.06119179459035492, 'dropout_rate': 0.22944435920651826, 'n_estimators': 228, 'criterion': 'squared_error', 'ccp_alpha': 1.1695917270519893, 'min_weight_fraction_leaf': 0.4215375134508466, 'max_features': 0.1, 'min_impurity_decrease': 7.423353896841116e-07, 'validation_fraction': 0.6178778050308257, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:39:16,327] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.4404072237856687, 'learning_rate': 0.05021661777026515, 'dropout_rate': 0.3271002904436618, 'n_estimators': 165, 'criterion': 'squared_error', 'ccp_alpha': 0.29447524911064504, 'min_weight_fraction_leaf': 0.40069580020869916, 'max_features': 0.1, 'min_impurity_decrease': 3.6437095962407636e-07, 'validation_fraction': 0.7676432140335194, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 19}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:39:39,869] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.6761093930790771, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.2893965309182704, 'n_estimators': 160, 'criterion': 'squared_error', 'ccp_alpha': 0.901967629884674, 'min_weight_fraction_leaf': 0.24390700059269013, 'max_features': 0.1, 'min_impurity_decrease': 1.655096093187184e-07, 'validation_fraction': 0.6807988770030404, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 17}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:40:29,922] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.6431028800744022, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.2650696393411326, 'n_estimators': 251, 'criterion': 'squared_error', 'ccp_alpha': 0.5870202902981957, 'min_weight_fraction_leaf': 0.4703538807846486, 'max_features': 0.1, 'min_impurity_decrease': 1.6179862000465865e-05, 'validation_fraction': 0.8212093469588243, 'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6406926406926406
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.6740196078431373
Fold 4 C-index: 0.7531645569620253
Fold 5 C-index: 0.6502347417840375
[I 2024-04-13 20:40:40,459] Trial 78 finished with value: 0.6891580237420823 and parameters: {'subsample': 0.4843861088807909, 'learning_rate': 0.06973971664259065, 'dropout_rate': 0.8662300708468649, 'n_estimators': 203, 'criterion': 'squared_error', 'ccp_alpha': 0.022575408770505685, 'min_weight_fraction_leaf': 0.3594885892997258, 'max_features': 0.1, 'min_impurity_decrease': 1.1182011314778938e-06, 'validation_fraction': 0.5652082279550805, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 7}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:41:09,594] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.3611713617174567, 'learning_rate': 0.05096788993898087, 'dropout_rate': 0.3751471900923219, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 1.690791260282008, 'min_weight_fraction_leaf': 0.44898311577041705, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7282589311533272, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 20}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:41:41,318] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.5712639195888173, 'learning_rate': 0.061260397905956956, 'dropout_rate': 0.684566586558272, 'n_estimators': 301, 'criterion': 'friedman_mse', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.3915173867597325, 'max_features': 'log2', 'min_impurity_decrease': 2.7889157104284163e-06, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 15}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.7164502164502164
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7892156862745098
Fold 4 C-index: 0.7489451476793249
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 20:41:57,034] Trial 81 finished with value: 0.7005889605838284 and parameters: {'subsample': 0.7122831903314419, 'learning_rate': 0.06751374363535764, 'dropout_rate': 0.1862131915967848, 'n_estimators': 139, 'criterion': 'squared_error', 'ccp_alpha': 0.025429683198128432, 'min_weight_fraction_leaf': 0.42555298323746704, 'max_features': 0.1, 'min_impurity_decrease': 2.6387783037798784e-07, 'validation_fraction': 0.9127900223179898, 'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:42:04,756] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.5461933216055307, 'learning_rate': 0.033155385898944026, 'dropout_rate': 0.23778233870811108, 'n_estimators': 93, 'criterion': 'squared_error', 'ccp_alpha': 0.24328534502450452, 'min_weight_fraction_leaf': 0.37708446914457305, 'max_features': None, 'min_impurity_decrease': 2.5718979151862506e-07, 'validation_fraction': 0.9679600680783438, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:42:10,182] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.5987438264370049, 'learning_rate': 0.02170539897267, 'dropout_rate': 0.21433250003236387, 'n_estimators': 75, 'criterion': 'squared_error', 'ccp_alpha': 0.6352435481431712, 'min_weight_fraction_leaf': 0.38872694153097165, 'max_features': 1, 'min_impurity_decrease': 4.428539340729197e-07, 'validation_fraction': 0.839634911114055, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 12}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:42:36,088] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.5043953987750895, 'learning_rate': 0.016561157063883874, 'dropout_rate': 0.305574256636177, 'n_estimators': 193, 'criterion': 'squared_error', 'ccp_alpha': 3.8414979948005463, 'min_weight_fraction_leaf': 0.40340771120296015, 'max_features': 'sqrt', 'min_impurity_decrease': 1.644017634935428e-07, 'validation_fraction': 0.7591450213250632, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:42:50,646] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.6234048158586912, 'learning_rate': 0.07598437184353962, 'dropout_rate': 0.17048502312161007, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 1.387161095969697, 'min_weight_fraction_leaf': 0.34368600869845795, 'max_features': 0.1, 'min_impurity_decrease': 7.301823750269666e-07, 'validation_fraction': 0.797100407728423, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 9 with value: 0.7478429018287163.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:43:01,251] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.5210141358410558, 'learning_rate': 0.05740808605195022, 'dropout_rate': 0.19887892485451236, 'n_estimators': 113, 'criterion': 'squared_error', 'ccp_alpha': 0.2338614594645341, 'min_weight_fraction_leaf': 0.2560736553862558, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5828999281499541e-06, 'validation_fraction': 0.8734883105902851, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 9}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:43:15,880] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7431825194554932, 'learning_rate': 0.08448533747598223, 'dropout_rate': 0.45160387337686625, 'n_estimators': 156, 'criterion': 'squared_error', 'ccp_alpha': 1.033652301720168, 'min_weight_fraction_leaf': 0.2266396627198381, 'max_features': 'log2', 'min_impurity_decrease': 1.4116350694085938e-07, 'validation_fraction': 0.9277858014394638, 'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:43:38,594] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.5757451193674527, 'learning_rate': 0.053489441535809173, 'dropout_rate': 0.25264945272304623, 'n_estimators': 173, 'criterion': 'squared_error', 'ccp_alpha': 0.467499190716187, 'min_weight_fraction_leaf': 0.2911408271774989, 'max_features': 0.1, 'min_impurity_decrease': 2.710852350800199e-07, 'validation_fraction': 0.7118643148373707, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6341991341991342
Fold 2 C-index: 0.7299107142857143
Fold 3 C-index: 0.7867647058823529
Fold 4 C-index: 0.8544303797468354
Fold 5 C-index: 0.647887323943662
[I 2024-04-13 20:43:44,343] Trial 89 finished with value: 0.7306384516115398 and parameters: {'subsample': 0.5408133210473126, 'learning_rate': 0.06516595390230792, 'dropout_rate': 0.2795970861916126, 'n_estimators': 83, 'criterion': 'squared_error', 'ccp_alpha': 0.01899868316043881, 'min_weight_fraction_leaf': 0.36167122796854106, 'max_features': 'sqrt', 'min_impurity_decrease': 5.410518918895025e-07, 'validation_fraction': 0.6576512691198165, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:43:49,774] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.6807992306933826, 'learning_rate': 0.07237565390028954, 'dropout_rate': 0.28454352555508333, 'n_estimators': 78, 'criterion': 'squared_error', 'ccp_alpha': 0.7333314639587395, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0004016774292545023, 'validation_fraction': 0.661036942888286, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 17}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5868544600938967
[I 2024-04-13 20:43:57,469] Trial 91 finished with value: 0.5374601777330652 and parameters: {'subsample': 0.5492757560244571, 'learning_rate': 0.06264501502966024, 'dropout_rate': 0.340581817435607, 'n_estimators': 103, 'criterion': 'squared_error', 'ccp_alpha': 0.1554791441523225, 'min_weight_fraction_leaf': 0.36205576035202014, 'max_features': 'sqrt', 'min_impurity_decrease': 5.039222324082345e-07, 'validation_fraction': 0.7734841500558423, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 16}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.7186147186147186
Fold 2 C-index: 0.7276785714285714
Fold 3 C-index: 0.7573529411764706
Fold 4 C-index: 0.7194092827004219
Fold 5 C-index: 0.6220657276995305
[I 2024-04-13 20:43:59,218] Trial 92 finished with value: 0.7090242483239426 and parameters: {'subsample': 0.4673005628125065, 'learning_rate': 0.06580664994491621, 'dropout_rate': 0.3948553630163486, 'n_estimators': 35, 'criterion': 'squared_error', 'ccp_alpha': 0.04541226279610616, 'min_weight_fraction_leaf': 0.37234146929609746, 'max_features': 'sqrt', 'min_impurity_decrease': 3.272854788879507e-07, 'validation_fraction': 0.6269555041421602, 'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:44:00,766] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.4176632870030855, 'learning_rate': 0.06636627117855994, 'dropout_rate': 0.3601544595130046, 'n_estimators': 32, 'criterion': 'squared_error', 'ccp_alpha': 0.5272532159862464, 'min_weight_fraction_leaf': 0.43273840559532556, 'max_features': 'sqrt', 'min_impurity_decrease': 8.937260348140506e-07, 'validation_fraction': 0.633862605716626, 'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:44:04,429] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.4803761011979748, 'learning_rate': 0.064851962927369, 'dropout_rate': 0.4979698842583554, 'n_estimators': 68, 'criterion': 'squared_error', 'ccp_alpha': 0.25445118587644133, 'min_weight_fraction_leaf': 0.3174351699298558, 'max_features': 'sqrt', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.5743695470511763, 'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 17, 'max_depth': 20}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:44:07,431] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.46483681108127944, 'learning_rate': 0.05846453417932067, 'dropout_rate': 0.39232912315356605, 'n_estimators': 51, 'criterion': 'squared_error', 'ccp_alpha': 0.964187963078782, 'min_weight_fraction_leaf': 0.3695804200296627, 'max_features': 'sqrt', 'min_impurity_decrease': 5.965356165754819e-07, 'validation_fraction': 0.6712957362310329, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:44:09,327] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.5309601333892247, 'learning_rate': 0.060775526480398405, 'dropout_rate': 0.26697189284953354, 'n_estimators': 32, 'criterion': 'squared_error', 'ccp_alpha': 0.5039565451188223, 'min_weight_fraction_leaf': 0.4020200009369257, 'max_features': 'sqrt', 'min_impurity_decrease': 1.4126329867106287e-06, 'validation_fraction': 0.7111286677014577, 'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:44:16,709] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.38054192896008343, 'learning_rate': 0.07120062188282647, 'dropout_rate': 0.31084524413898235, 'n_estimators': 90, 'criterion': 'friedman_mse', 'ccp_alpha': 0.20691112935567513, 'min_weight_fraction_leaf': 0.27866834907477256, 'max_features': 'sqrt', 'min_impurity_decrease': 1.3568805622065066e-07, 'validation_fraction': 0.6269822362550138, 'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 9 with value: 0.7478429018287163.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-13 20:44:43,147] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.6120801460736243, 'learning_rate': 0.07872811111022683, 'dropout_rate': 0.24818093533133442, 'n_estimators': 179, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.4185926163264879, 'max_features': 'sqrt', 'min_impurity_decrease': 2.1152123511367953e-07, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 18}. Best is trial 9 with value: 0.7478429018287163.
Fold 1 C-index: 0.6168831168831169
Fold 2 C-index: 0.7232142857142857

[I 2024-04-13 20:44:44,335] A new study created in memory with name: no-name-336def06-4f23-4b38-9fd1-cca8dd9531d7

Fold 3 C-index: 0.6691176470588235
Fold 4 C-index: 0.7109704641350211
Fold 5 C-index: 0.6924882629107981
[I 2024-04-13 20:44:44,309] Trial 99 finished with value: 0.6825347553404091 and parameters: {'subsample': 0.6412657790925795, 'learning_rate': 0.07345360439249596, 'dropout_rate': 0.5621279291332008, 'n_estimators': 20, 'criterion': 'squared_error', 'ccp_alpha': 0.0044270406464835925, 'min_weight_fraction_leaf': 0.3816502751408651, 'max_features': 'sqrt', 'min_impurity_decrease': 3.6435126856959784e-07, 'validation_fraction': 0.5945655617106834, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 9 with value: 0.7478429018287163.


* Best trial for C-index:
 FrozenTrial(number=9, state=TrialState.COMPLETE, values=[0.7478429018287163], datetime_start=datetime.datetime(2024, 4, 13, 18, 49, 45, 410770), datetime_complete=datetime.datetime(2024, 4, 13, 18, 51, 36, 785349), params={'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=9, value=None)


* Best Score for C-index:
 0.7478429018287163

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 20:45:32,358] Trial 0 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 20:45:58,067] Trial 1 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 20:46:20,859] Trial 2 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 20:47:04,339] Trial 3 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 20:47:20,390] Trial 4 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 20:47:24,586] Trial 5 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 20:48:05,276] Trial 6 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 20:48:18,011] Trial 7 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 20:48:19,449] Trial 8 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.21659054862241586.
Fold 1 IBS: 0.2136728996432671
Fold 2 IBS: 0.22129381285413927
Fold 3 IBS: 0.20401558748821036
Fold 4 IBS: 0.22428896171062235
Fold 5 IBS: 0.21835957085781268
[I 2024-04-13 20:50:00,915] Trial 9 finished with value: 0.21632616651081035 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22148040733030283
Fold 3 IBS: 0.2042661767272568
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21819982285808667
[I 2024-04-13 20:52:55,058] Trial 10 finished with value: 0.21653219405295382 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 20:56:03,812] Trial 11 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.2139285504132104
Fold 2 IBS: 0.2215419405416392
Fold 3 IBS: 0.20444231920349729
Fold 4 IBS: 0.22467772193411403
Fold 5 IBS: 0.21815147147378977
[I 2024-04-13 20:58:47,117] Trial 12 finished with value: 0.21654840071325016 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609574
[I 2024-04-13 20:59:57,120] Trial 13 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:02:00,027] Trial 14 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:03:58,300] Trial 15 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:05:02,634] Trial 16 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:07:26,761] Trial 17 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:08:40,539] Trial 18 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:08:54,221] Trial 19 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:11:02,364] Trial 20 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22155379002446857
Fold 3 IBS: 0.2045348458645112
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21814789846032956
[I 2024-04-13 21:13:16,333] Trial 21 finished with value: 0.21659021953968643 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.21632616651081035.
Fold 1 IBS: 0.2128868622603165
Fold 2 IBS: 0.22126048870172876

Fold 3 IBS: 0.20365290094758007
Fold 4 IBS: 0.22320214781796247
Fold 5 IBS: 0.21838599567082578
[I 2024-04-13 21:15:38,761] Trial 22 finished with value: 0.21587767907968272 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 21:17:42,267] Trial 23 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:19:05,726] Trial 24 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:20:23,483] Trial 25 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:22:21,611] Trial 26 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:22:34,362] Trial 27 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:23:17,533] Trial 28 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:24:52,128] Trial 29 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 21:25:31,143] Trial 30 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22147227191441446
Fold 3 IBS: 0.20449584163770088
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21821269771363955
[I 2024-04-13 21:27:27,222] Trial 31 finished with value: 0.21657907492297554 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.21587767907968272.
Fold 1 IBS: 0.2125832997877287
Fold 2 IBS: 0.22120603131948602
Fold 3 IBS: 0.20347054598548492
Fold 4 IBS: 0.22277199627515254
Fold 5 IBS: 0.2184477947006929
[I 2024-04-13 21:29:53,903] Trial 32 finished with value: 0.21569593361370903 and parameters: {'subsample': 0.8694330194615664, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.15717168328156264, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2499659379613939, 'max_features': 'auto', 'min_impurity_decrease': 5.49537670642244e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:31:26,346] Trial 33 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.675788072227293, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.26248193046936125, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:33:17,283] Trial 34 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7608748108360882, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.22658656718653286, 'n_estimators': 442, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:33:43,940] Trial 35 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9877130911251436, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.10873393691266725, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.18547003694100694, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:35:21,593] Trial 36 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9020267654284275, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.30724325436819333, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-13 21:35:24,775] Trial 37 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7046496029198845, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.23856065179543168, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:36:11,026] Trial 38 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.4076069474884072, 'n_estimators': 326, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:37:43,170] Trial 39 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8217816383137475, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.1640291495128302, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.2798855562711405, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:39:05,581] Trial 40 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9616510844491497, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.34374532611622466, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.29265705281518334, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21366086623501337
Fold 2 IBS: 0.22146378671211514
Fold 3 IBS: 0.2042214067735942
Fold 4 IBS: 0.22417978006182668
Fold 5 IBS: 0.21821304296355556
[I 2024-04-13 21:40:57,999] Trial 41 finished with value: 0.216347776549221 and parameters: {'subsample': 0.8545793279341185, 'learning_rate': 0.004158109708816752, 'dropout_rate': 0.26580100771824766, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.2163463990358851, 'max_features': 'auto', 'min_impurity_decrease': 2.0657182985394914e-06, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21323532121158412
Fold 2 IBS: 0.2213546560203995
Fold 3 IBS: 0.2038554377123743
Fold 4 IBS: 0.22353035692919165
Fold 5 IBS: 0.2182730951377501
[I 2024-04-13 21:42:59,713] Trial 42 finished with value: 0.21604977340225995 and parameters: {'subsample': 0.8702399034039393, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.25186220971279083, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:45:09,920] Trial 43 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8612168289063256, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.25483238808810116, 'max_features': 'auto', 'min_impurity_decrease': 2.4438005942864937e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 21:47:01,753] Trial 44 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7438057966042957, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.28293775090891093, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19668003262875977, 'max_features': 'auto', 'min_impurity_decrease': 2.6902494973410383e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21351546133478636
Fold 2 IBS: 0.2212953393166131
Fold 3 IBS: 0.20416066011138567
Fold 4 IBS: 0.22414784694013984
Fold 5 IBS: 0.21808198223903946
[I 2024-04-13 21:47:38,534] Trial 45 finished with value: 0.21624025798839286 and parameters: {'subsample': 0.8944196831300942, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.3519610418464251, 'n_estimators': 286, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.14870356834295773, 'max_features': 0.1, 'min_impurity_decrease': 7.029217811198981e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:48:00,157] Trial 46 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8889360703444935, 'learning_rate': 0.021202453758263524, 'dropout_rate': 0.37366505757154717, 'n_estimators': 212, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.13495413044886762, 'max_features': 0.1, 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.7817276416748403, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 21:48:19,995] Trial 47 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8125642318651415, 'learning_rate': 0.009475933714573075, 'dropout_rate': 0.549053974469267, 'n_estimators': 246, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.05315075225369012, 'max_features': 0.1, 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.8455746050888122, 'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 16}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.2139765219514961
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-13 21:48:41,763] Trial 48 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5606784624022658, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.15161205457134033, 'max_features': 0.1, 'min_impurity_decrease': 7.58503158471156e-07, 'validation_fraction': 0.6558568899488589, 'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 21:49:28,974] Trial 49 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7862274829633776, 'learning_rate': 0.01539284097767942, 'dropout_rate': 0.22346295697530158, 'n_estimators': 297, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.11717838996501556, 'max_features': 0.1, 'min_impurity_decrease': 1.8252369398120913e-07, 'validation_fraction': 0.572249681332324, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 21:50:04,477] Trial 50 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9312887812434206, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.1405973314616702, 'n_estimators': 245, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.3280094923237546, 'max_features': 'log2', 'min_impurity_decrease': 6.557489275136285e-06, 'validation_fraction': 0.7454078357315349, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21390866906847378
Fold 2 IBS: 0.22152357169467504
Fold 3 IBS: 0.20447044800073966
Fold 4 IBS: 0.22463761968169865
Fold 5 IBS: 0.21811848890955576
[I 2024-04-13 21:51:37,660] Trial 51 finished with value: 0.2165317594710286 and parameters: {'subsample': 0.8416341118452358, 'learning_rate': 0.0011545433716222738, 'dropout_rate': 0.2714156533621327, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5575206740408547e-06, 'validation_fraction': 0.955918616426473, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 18}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-13 22:07:50,448] Trial 52 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9038254028690907, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.35708522969723233, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.2736663618456513, 'max_features': 'auto', 'min_impurity_decrease': 6.249703290808956e-07, 'validation_fraction': 0.8911327691979425, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 10}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21318789553535888
Fold 2 IBS: 0.22134043107420837
Fold 3 IBS: 0.20386354327606576
Fold 4 IBS: 0.22351016578128388
Fold 5 IBS: 0.21831900359189102
[I 2024-04-13 22:08:00,954] Trial 53 finished with value: 0.21604420785176157 and parameters: {'subsample': 0.8676207486799892, 'learning_rate': 0.006168874300076388, 'dropout_rate': 0.1890436022076237, 'n_estimators': 170, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.24329793299892918, 'max_features': None, 'min_impurity_decrease': 1.2175301870899398e-06, 'validation_fraction': 0.8404301090445275, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 14}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-13 22:08:09,626] Trial 54 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9517595160347714, 'learning_rate': 0.011898484337366975, 'dropout_rate': 0.18801209253891804, 'n_estimators': 154, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.18138913965803982, 'max_features': None, 'min_impurity_decrease': 2.1220791878785e-07, 'validation_fraction': 0.8463088761926056, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 14}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938

Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 22:08:20,636] Trial 55 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8826224600403735, 'learning_rate': 0.007074424640763303, 'dropout_rate': 0.13451729459411277, 'n_estimators': 150, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.2467647950019329, 'max_features': None, 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8026232644824398, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 22:08:25,843] Trial 56 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.28235337567058344, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.24047499291191018, 'n_estimators': 119, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.2964880597264897, 'max_features': None, 'min_impurity_decrease': 1.0882152569265186e-06, 'validation_fraction': 0.6726200432409829, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 22:08:27,048] Trial 57 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7810459175852128, 'learning_rate': 0.019486581077710775, 'dropout_rate': 0.19826716028503513, 'n_estimators': 42, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.26595476803289986, 'max_features': None, 'min_impurity_decrease': 1.0307639754375153e-07, 'validation_fraction': 0.6100016827196765, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 22:10:43,307] Trial 58 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.6789522190234277, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.42986712481966516, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.2566329111690735, 'min_weight_fraction_leaf': 0.3171702483213782, 'max_features': 0.1, 'min_impurity_decrease': 4.754437094021529e-07, 'validation_fraction': 0.7150017613841274, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 22:10:58,144] Trial 59 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.5271446119595178, 'learning_rate': 0.014198961603309504, 'dropout_rate': 0.10616462496513888, 'n_estimators': 187, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.1986729008847237, 'max_features': 1, 'min_impurity_decrease': 1.6927224987120254e-07, 'validation_fraction': 0.8300561202226027, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 19}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609574
[I 2024-04-13 22:11:18,901] Trial 60 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7332497596700902, 'learning_rate': 0.02962052419092614, 'dropout_rate': 0.3119122216591065, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 0.6675332732754606, 'min_weight_fraction_leaf': 0.009614251843305027, 'max_features': 'log2', 'min_impurity_decrease': 2.993429222136608e-06, 'validation_fraction': 0.901816194726108, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 15}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 22:13:04,230] Trial 61 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.004499907449693211, 'dropout_rate': 0.262312598009101, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.2109281806050815, 'max_features': 'auto', 'min_impurity_decrease': 1.5516315249939405e-06, 'validation_fraction': 0.9561272999176395, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21378030749911967
Fold 2 IBS: 0.22152259170617372
Fold 3 IBS: 0.20438216183888602
Fold 4 IBS: 0.22446178798877484
Fold 5 IBS: 0.21816686479416542
[I 2024-04-13 22:19:25,066] Trial 62 finished with value: 0.21646274276542393 and parameters: {'subsample': 0.8095968679200728, 'learning_rate': 0.0012407706020760864, 'dropout_rate': 0.1653584330674095, 'n_estimators': 415, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.24216094842339775, 'max_features': 'auto', 'min_impurity_decrease': 5.368407355240861e-06, 'validation_fraction': 0.8765131254615539, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 17}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21297995399784603
Fold 2 IBS: 0.22120478780276556
Fold 3 IBS: 0.2037875964740539
Fold 4 IBS: 0.22328018145177259
Fold 5 IBS: 0.21821128461791345
[I 2024-04-13 22:20:58,303] Trial 63 finished with value: 0.21589276086887027 and parameters: {'subsample': 0.8543251428514922, 'learning_rate': 0.010105246912026189, 'dropout_rate': 0.28841218854789885, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.017682771465895766, 'min_weight_fraction_leaf': 0.16136348952979457, 'max_features': 'auto', 'min_impurity_decrease': 3.248684145226931e-07, 'validation_fraction': 0.9634950299864261, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 22:22:19,107] Trial 64 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.44674873633955603, 'learning_rate': 0.010613549148600106, 'dropout_rate': 0.23092846232783942, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.42603993022683684, 'min_weight_fraction_leaf': 0.10509596884980266, 'max_features': 'auto', 'min_impurity_decrease': 3.705166577075673e-07, 'validation_fraction': 0.9158767212997163, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 22:23:07,892] Trial 65 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9238320627092557, 'learning_rate': 0.008868026173365113, 'dropout_rate': 0.1984753106236297, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 0.9125450824264325, 'min_weight_fraction_leaf': 0.15546303458018157, 'max_features': 'auto', 'min_impurity_decrease': 9.052530052726428e-07, 'validation_fraction': 0.9981227465042112, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 22:23:08,417] Trial 66 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9994775442301681, 'learning_rate': 0.01676432497697686, 'dropout_rate': 0.2942603509282204, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 1.301982997504856, 'min_weight_fraction_leaf': 0.2840514882476357, 'max_features': 'auto', 'min_impurity_decrease': 5.794511488038249e-07, 'validation_fraction': 0.7847157067637343, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 32 with value: 0.21569593361370903.

Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 22:24:22,212] Trial 67 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7752653699906195, 'learning_rate': 0.013816164977086237, 'dropout_rate': 0.3423659929403322, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.07630547308149627, 'max_features': 'sqrt', 'min_impurity_decrease': 1.489839319569471e-07, 'validation_fraction': 0.8730218040479422, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 22:40:33,212] Trial 68 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8986655221720145, 'learning_rate': 0.006375573501112446, 'dropout_rate': 0.47956937204864525, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 0.771309271935327, 'min_weight_fraction_leaf': 0.18276803677887216, 'max_features': None, 'min_impurity_decrease': 2.925898919906258e-07, 'validation_fraction': 0.9673463064736232, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609563
[I 2024-04-13 22:55:58,279] Trial 69 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8246558150418386, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.3910099546046163, 'n_estimators': 229, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.13508454697536748, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9279414151063008, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 18}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 22:56:08,228] Trial 70 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9596193639212897, 'learning_rate': 0.011623265396443191, 'dropout_rate': 0.14520564753098347, 'n_estimators': 176, 'criterion': 'squared_error', 'ccp_alpha': 6.120501546200477, 'min_weight_fraction_leaf': 0.34897025165070383, 'max_features': 0.1, 'min_impurity_decrease': 2.8282570018479815e-07, 'validation_fraction': 0.8470654980022871, 'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21361646186514888
Fold 2 IBS: 0.22144724176288016
Fold 3 IBS: 0.20417526189728913
Fold 4 IBS: 0.224097925583268
Fold 5 IBS: 0.2182265336464523
[I 2024-04-13 23:07:22,019] Trial 71 finished with value: 0.2163126849510077 and parameters: {'subsample': 0.8525037069165885, 'learning_rate': 0.004772306432110387, 'dropout_rate': 0.2656038277020879, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.21491710684687593, 'max_features': 'auto', 'min_impurity_decrease': 1.2328511691596008e-06, 'validation_fraction': 0.9449056087847856, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21348281351185516
Fold 2 IBS: 0.2212747678873435
Fold 3 IBS: 0.20413073742913063
Fold 4 IBS: 0.22395829728519678
Fold 5 IBS: 0.21810371609256507
[I 2024-04-13 23:31:53,372] Trial 72 finished with value: 0.21619006644121824 and parameters: {'subsample': 0.8772963574153866, 'learning_rate': 0.004068438023485704, 'dropout_rate': 0.25030187864168324, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.004891655702789276, 'min_weight_fraction_leaf': 0.16472116174210677, 'max_features': 'auto', 'min_impurity_decrease': 8.26774954405686e-07, 'validation_fraction': 0.9066256312243355, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 23:33:13,065] Trial 73 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8789059551053753, 'learning_rate': 0.004717809486455078, 'dropout_rate': 0.17589004891490057, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.6105603409601544, 'min_weight_fraction_leaf': 0.1608125340894365, 'max_features': 'auto', 'min_impurity_decrease': 1.234677792382508e-06, 'validation_fraction': 0.9045935380677651, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 23:34:49,935] Trial 74 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.8478466450449434, 'learning_rate': 0.007496404457245203, 'dropout_rate': 0.23223754316840572, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.3281588096091329, 'min_weight_fraction_leaf': 0.1675789146933581, 'max_features': 'auto', 'min_impurity_decrease': 9.368371294550907e-06, 'validation_fraction': 0.9431177399378227, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.2138347550669078
Fold 2 IBS: 0.22152315699263525
Fold 3 IBS: 0.20438559309392143
Fold 4 IBS: 0.22446470050508696
Fold 5 IBS: 0.2181656100061446
[I 2024-04-13 23:36:04,248] Trial 75 finished with value: 0.2164747631329392 and parameters: {'subsample': 0.9175533460307064, 'learning_rate': 0.0023603427686751015, 'dropout_rate': 0.3205851562311525, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.008819925578928337, 'min_weight_fraction_leaf': 0.1942611713172168, 'max_features': 'auto', 'min_impurity_decrease': 4.248619579048627e-06, 'validation_fraction': 0.9695262055512311, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 23:37:36,078] Trial 76 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.7986702147317346, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.2075245331259492, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.24804652581654402, 'max_features': 'auto', 'min_impurity_decrease': 7.596278796221777e-07, 'validation_fraction': 0.23951296722702176, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 23:38:55,533] Trial 77 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.948174826425534, 'learning_rate': 0.00894234614691969, 'dropout_rate': 0.2521312194335541, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.1501929638460315, 'min_weight_fraction_leaf': 0.22368248859864986, 'max_features': 1, 'min_impurity_decrease': 2.1196884133822008e-06, 'validation_fraction': 0.9945844905365533, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.

Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 23:40:47,624] Trial 78 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8298863213670412, 'learning_rate': 0.00451364015632944, 'dropout_rate': 0.12600533500433567, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.7257219477345627, 'min_weight_fraction_leaf': 0.13082025771859518, 'max_features': 'auto', 'min_impurity_decrease': 1.9076132907505136e-05, 'validation_fraction': 0.8664817216741038, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 23:42:14,819] Trial 79 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7574483245829817, 'learning_rate': 0.019863199816083397, 'dropout_rate': 0.17446937661488254, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 0.31499659157923954, 'min_weight_fraction_leaf': 0.21017421201967662, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8273941539647348, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 7}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 23:45:02,091] Trial 80 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8725888660383272, 'learning_rate': 0.0105819667920879, 'dropout_rate': 0.28829477813771426, 'n_estimators': 479, 'criterion': 'friedman_mse', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.23071219602263424, 'max_features': None, 'min_impurity_decrease': 4.0770684216277635e-07, 'validation_fraction': 0.928106026913601, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-13 23:47:03,979] Trial 81 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.8990065786316825, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.2748870347221869, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.4744498919971285, 'min_weight_fraction_leaf': 0.2630535348362975, 'max_features': 'auto', 'min_impurity_decrease': 5.537017218541503e-07, 'validation_fraction': 0.8952279969583862, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21328229255914521
Fold 2 IBS: 0.2212858013221039
Fold 3 IBS: 0.2038766018817242
Fold 4 IBS: 0.22347196184384838
Fold 5 IBS: 0.2182372501639556
[I 2024-04-13 23:49:51,978] Trial 82 finished with value: 0.21603078155415548 and parameters: {'subsample': 0.9754713580899053, 'learning_rate': 0.006526353273221224, 'dropout_rate': 0.21297581278410355, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.01766512408236868, 'min_weight_fraction_leaf': 0.17192439984108654, 'max_features': 'auto', 'min_impurity_decrease': 1.1471115029235744e-06, 'validation_fraction': 0.7827565614496917, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-13 23:53:17,319] Trial 83 finished with value: 0.21659054862241583 and parameters: {'subsample': 0.9784574312137415, 'learning_rate': 0.00585120413615953, 'dropout_rate': 0.24686998469347132, 'n_estimators': 452, 'criterion': 'squared_error', 'ccp_alpha': 0.9565900706551483, 'min_weight_fraction_leaf': 0.18048486019194648, 'max_features': 'auto', 'min_impurity_decrease': 1.1858911008713308e-06, 'validation_fraction': 0.8032079236654875, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-13 23:59:12,134] Trial 84 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.9394718228941793, 'learning_rate': 0.01274376325277435, 'dropout_rate': 0.2088574912220965, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.20869434162150352, 'min_weight_fraction_leaf': 0.14373558095200806, 'max_features': 'auto', 'min_impurity_decrease': 2.8420607024882546e-06, 'validation_fraction': 0.772058368592506, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.2137332537657108
Fold 2 IBS: 0.2214607572288379
Fold 3 IBS: 0.20433628984539925
Fold 4 IBS: 0.22431674227056686
Fold 5 IBS: 0.2181301614474756
[I 2024-04-14 00:04:30,716] Trial 85 finished with value: 0.2163954409115981 and parameters: {'subsample': 0.912681601393802, 'learning_rate': 0.0013249752823822469, 'dropout_rate': 0.1461697672537166, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.011241474018604543, 'min_weight_fraction_leaf': 0.1705999906338127, 'max_features': 'auto', 'min_impurity_decrease': 8.018975864229782e-07, 'validation_fraction': 0.9719249618460976, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609557
[I 2024-04-14 00:06:55,487] Trial 86 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8646905432970389, 'learning_rate': 0.008498434357869948, 'dropout_rate': 0.5994503938995064, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.6167656102443388, 'min_weight_fraction_leaf': 0.19777758658413871, 'max_features': 'log2', 'min_impurity_decrease': 1.934056534817461e-06, 'validation_fraction': 0.9210950907733381, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 00:10:36,207] Trial 87 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.9759341377278088, 'learning_rate': 0.0036081007715982843, 'dropout_rate': 0.18778447583293612, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.3195605225031562, 'min_weight_fraction_leaf': 0.21689264428803998, 'max_features': 0.1, 'min_impurity_decrease': 1.2232883715670806e-06, 'validation_fraction': 0.7334572672133262, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609563
[I 2024-04-14 00:34:34,137] Trial 88 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.842532245767955, 'learning_rate': 0.0226982005575902, 'dropout_rate': 0.3030895893125359, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.1079010517457524, 'min_weight_fraction_leaf': 0.2374374814518519, 'max_features': 'auto', 'min_impurity_decrease': 2.329078771156988e-07, 'validation_fraction': 0.8247615359467644, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.

Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 00:34:44,412] Trial 89 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8950685318650474, 'learning_rate': 0.0401442321523931, 'dropout_rate': 0.21800465633567007, 'n_estimators': 83, 'criterion': 'squared_error', 'ccp_alpha': 1.9753526447682455, 'min_weight_fraction_leaf': 0.12380998580246302, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005291280643839411, 'validation_fraction': 0.8620372359221313, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 00:35:03,949] Trial 90 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.933357756593576, 'learning_rate': 0.01663967016341421, 'dropout_rate': 0.15487109634803542, 'n_estimators': 120, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.0858457731048565, 'max_features': 'auto', 'min_impurity_decrease': 4.3300292936606785e-07, 'validation_fraction': 0.8895049558014025, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 16}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 00:39:08,859] Trial 91 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8092406443348498, 'learning_rate': 0.006550415384271891, 'dropout_rate': 0.33596523225484254, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 0.4689772579638022, 'min_weight_fraction_leaf': 0.2573561627869438, 'max_features': 'auto', 'min_impurity_decrease': 1.314710880352814e-07, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181249443584878
[I 2024-04-14 00:42:37,931] Trial 92 finished with value: 0.21659067444289432 and parameters: {'subsample': 0.644963563496714, 'learning_rate': 0.010621871147454658, 'dropout_rate': 0.2605659545044696, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.2754424406198085, 'max_features': 'auto', 'min_impurity_decrease': 3.373008958583936e-07, 'validation_fraction': 0.691850183800161, 'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609566
[I 2024-04-14 00:45:40,622] Trial 93 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8740366085958363, 'learning_rate': 0.012704222941907362, 'dropout_rate': 0.27990921906241656, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 0.790792088943923, 'min_weight_fraction_leaf': 0.28767375739839485, 'max_features': 'auto', 'min_impurity_decrease': 1.890585205315356e-07, 'validation_fraction': 0.6313881703470108, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 5}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.2215772663416734
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812451758939916
[I 2024-04-14 00:48:29,845] Trial 94 finished with value: 0.2165904589200754 and parameters: {'subsample': 0.6946240073504245, 'learning_rate': 0.003265152974994641, 'dropout_rate': 0.23752414424086984, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 0.17589395959024334, 'min_weight_fraction_leaf': 0.30830711849814396, 'max_features': 'auto', 'min_impurity_decrease': 5.705302353122631e-07, 'validation_fraction': 0.9460789157975008, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667935
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 00:50:37,356] Trial 95 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.5921128266700642, 'learning_rate': 0.008085042515827447, 'dropout_rate': 0.3645032961618391, 'n_estimators': 426, 'criterion': 'squared_error', 'ccp_alpha': 0.5679426855035544, 'min_weight_fraction_leaf': 0.14389035428851613, 'max_features': 0.1, 'min_impurity_decrease': 8.920619424711359e-07, 'validation_fraction': 0.7884524468137962, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018132
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 00:51:56,430] Trial 96 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.48032209804466314, 'learning_rate': 0.00544615832472076, 'dropout_rate': 0.2204223331906773, 'n_estimators': 301, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5983347189045871, 'min_weight_fraction_leaf': 0.2709316597935022, 'max_features': None, 'min_impurity_decrease': 1.5057379989495091e-06, 'validation_fraction': 0.9122100090104754, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 10}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149616
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.2181243152560957
[I 2024-04-14 00:52:26,069] Trial 97 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.7919447168995172, 'learning_rate': 0.014949459147251999, 'dropout_rate': 0.8479620532477699, 'n_estimators': 327, 'criterion': 'squared_error', 'ccp_alpha': 8.003203118644894, 'min_weight_fraction_leaf': 0.1909054160187561, 'max_features': 'auto', 'min_impurity_decrease': 1.4118150039086305e-07, 'validation_fraction': 0.7499482743470836, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018135
Fold 4 IBS: 0.2247380413976268
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 00:54:43,458] Trial 98 finished with value: 0.21659054862241586 and parameters: {'subsample': 0.8374499922138454, 'learning_rate': 0.010842152797118532, 'dropout_rate': 0.12031745156583781, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 0.8474863406823964, 'min_weight_fraction_leaf': 0.2387208678829098, 'max_features': 1, 'min_impurity_decrease': 2.5658674524773553e-07, 'validation_fraction': 0.97208801308084, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 19}. Best is trial 32 with value: 0.21569593361370903.
Fold 1 IBS: 0.21397652195149613
Fold 2 IBS: 0.22157791718667938
Fold 3 IBS: 0.20453594732018138
Fold 4 IBS: 0.22473804139762676
Fold 5 IBS: 0.21812431525609582
[I 2024-04-14 00:57:10,204] Trial 99 finished with value: 0.21659054862241592 and parameters: {'subsample': 0.24286963781937687, 'learning_rate': 0.019379774770211813, 'dropout_rate': 0.315996357844389, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004367456702591322, 'min_weight_fraction_leaf': 0.20598346026470685, 'max_features': 'auto', 'min_impurity_decrease': 6.619042391820512e-07, 'validation_fraction': 0.8357872512688199, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 32 with value: 0.21569593361370903.


* Best trial for IBS:
 FrozenTrial(number=32, state=TrialState.COMPLETE, values=[0.21569593361370903], datetime_start=datetime.datetime(2024, 4, 13, 21, 27, 27, 232470), datetime_complete=datetime.datetime(2024, 4, 13, 21, 29, 53, 901917), params={'subsample': 0.8694330194615664, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.15717168328156264, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2499659379613939, 'max_features': 'auto', 'min_impurity_decrease': 5.49537670642244e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=32, value=None)


* Best Score for IBS:
 0.21569593361370903

In [69]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [70]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.748
train_ibs:  0.216

#### Test

In [71]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [72]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.07426378544613033,
                                 criterion='squared_error',
                                 dropout_rate=0.28125955124323376,
                                 learning_rate=0.013102111413618,
                                 max_features='auto', max_leaf_nodes=16,
                                 min_impurity_decrease=1.4994028685178666e-07,
                                 min_samples_leaf=10,
                                 min_weight_fraction_leaf=0.27579636299120275,
                                 n_estimators=406, random_state=123,
                                 subsample=0.6059965408578151,
                                 validation_fraction=0.6359003593513561)

C-index score: 0.676

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01914282727239553,
                                 criterion='squared_error',
                                 dropout_rate=0.15717168328156264,
                                 learning_rate=0.008435334301058566,
                                 max_depth=2, max_features='auto',
                                 max_leaf_nodes=19,
                                 min_impurity_decrease=5.49537670642244e-07,
                                 min_samples_leaf=18, min_samples_split=19,
                                 min_weight_fraction_leaf=0.2499659379613939,
                                 n_estimators=472, random_state=123,
                                 subsample=0.8694330194615664,
                                 validation_fraction=0.9130609639429398)

IBS: 0.22

In [73]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [74]:
# Setting the y format 
y = clinical_train[['OS', 'event_OS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_OS'], y_train_df['OS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_OS'], y_test_df['OS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                gbsg_times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(gbsg_times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, gbsg_times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 00:58:16,318] A new study created in memory with name: no-name-5e19b7e4-35ea-4f56-8b3d-fff945e3cf52

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:58:18,660] Trial 0 finished with value: 0.6871796627652828 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6871796627652828.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:58:40,271] Trial 1 finished with value: 0.686313861899482 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6871796627652828.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:58:44,321] Trial 2 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6888455074691022.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:58:50,241] Trial 3 finished with value: 0.6879797066033013 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.6888455074691022.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:58:59,034] Trial 4 finished with value: 0.7156335978653119 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.7156335978653119.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:59:08,860] Trial 5 finished with value: 0.685448061033681 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.7156335978653119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:59:13,261] Trial 6 finished with value: 0.686313861899482 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.7156335978653119.
Fold 1 C-index: 0.7229437229437229
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:59:14,108] Trial 7 finished with value: 0.6931745117981064 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.7156335978653119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:59:19,110] Trial 8 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.7156335978653119.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 00:59:34,011] Trial 9 finished with value: 0.703061193743612 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.7156335978653119.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:59:44,175] Trial 10 finished with value: 0.7164555607125911 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.7164555607125911.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 00:59:57,638] Trial 11 finished with value: 0.7455338965923975 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:00:11,317] Trial 12 finished with value: 0.7445535044355348 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:00:25,369] Trial 13 finished with value: 0.6975692731548933 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:00:35,489] Trial 14 finished with value: 0.7454901995969136 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:00:47,292] Trial 15 finished with value: 0.7454901995969136 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.7098041576457912, 'n_estimators': 365, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:01:07,452] Trial 16 finished with value: 0.7428927969995109 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.7326988341376399, 'n_estimators': 423, 'learning_rate': 0.08463638125592773}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:01:22,341] Trial 17 finished with value: 0.7199626021943162 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.6125221083505048, 'n_estimators': 413, 'learning_rate': 0.08749976591807801}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:01:31,758] Trial 18 finished with value: 0.7199626021943162 and parameters: {'subsample': 0.35888747153360906, 'dropout_rate': 0.8058789888144481, 'n_estimators': 324, 'learning_rate': 0.09062397105934869}. Best is trial 11 with value: 0.7455338965923975.

Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.676056338028169
[I 2024-04-14 01:01:44,410] Trial 19 finished with value: 0.7428243157017421 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.9820749239416067, 'n_estimators': 431, 'learning_rate': 0.08300323114610605}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:01:52,464] Trial 20 finished with value: 0.7268571894146076 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.5777838682216713, 'n_estimators': 258, 'learning_rate': 0.09795590448114745}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:02:04,398] Trial 21 finished with value: 0.7419124048426482 and parameters: {'subsample': 0.20928102825226413, 'dropout_rate': 0.7434648327841792, 'n_estimators': 354, 'learning_rate': 0.08054438682658777}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:02:17,542] Trial 22 finished with value: 0.7446243987311127 and parameters: {'subsample': 0.2850810716899137, 'dropout_rate': 0.6816899967794596, 'n_estimators': 385, 'learning_rate': 0.06698245169017239}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:02:25,380] Trial 23 finished with value: 0.7430073882905729 and parameters: {'subsample': 0.15450687211748398, 'dropout_rate': 0.8014372139995105, 'n_estimators': 298, 'learning_rate': 0.09039902747837351}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:02:36,415] Trial 24 finished with value: 0.7446243987311127 and parameters: {'subsample': 0.30544113046891047, 'dropout_rate': 0.6537883290687992, 'n_estimators': 337, 'learning_rate': 0.07625484107479145}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:02:53,361] Trial 25 finished with value: 0.7430073882905729 and parameters: {'subsample': 0.17501176263162754, 'dropout_rate': 0.528565711666221, 'n_estimators': 451, 'learning_rate': 0.09443224929669784}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:02:58,991] Trial 26 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.7464748948448074, 'n_estimators': 245, 'learning_rate': 0.0806890354653704}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7366071428571429
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:03:09,328] Trial 27 finished with value: 0.741885348565592 and parameters: {'subsample': 0.10034436619848794, 'dropout_rate': 0.9861686560685959, 'n_estimators': 397, 'learning_rate': 0.08919415112422793}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:03:16,181] Trial 28 finished with value: 0.7438731891563737 and parameters: {'subsample': 0.23131169694169362, 'dropout_rate': 0.8528818052986153, 'n_estimators': 281, 'learning_rate': 0.06152638329235058}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:03:16,894] Trial 29 finished with value: 0.6975692731548933 and parameters: {'subsample': 0.660583543673307, 'dropout_rate': 0.32258564381252325, 'n_estimators': 28, 'learning_rate': 0.09852082119405899}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:03:19,764] Trial 30 finished with value: 0.6975692731548933 and parameters: {'subsample': 0.9885210981191594, 'dropout_rate': 0.41840830048821154, 'n_estimators': 144, 'learning_rate': 0.04083797376029951}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:03:32,563] Trial 31 finished with value: 0.7446243987311127 and parameters: {'subsample': 0.28768044353640015, 'dropout_rate': 0.6805794431102682, 'n_estimators': 380, 'learning_rate': 0.062795268442302}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:03:42,576] Trial 32 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.4222219693107251, 'dropout_rate': 0.6161841388400444, 'n_estimators': 343, 'learning_rate': 0.06719558084205016}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:03:55,464] Trial 33 finished with value: 0.7156335978653119 and parameters: {'subsample': 0.31642912250959304, 'dropout_rate': 0.48095898939081394, 'n_estimators': 385, 'learning_rate': 0.07640523198001815}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.670995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:04:11,643] Trial 34 finished with value: 0.7420269961337101 and parameters: {'subsample': 0.1644698979027382, 'dropout_rate': 0.7129143719684587, 'n_estimators': 453, 'learning_rate': 0.07104054321866782}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:04:17,222] Trial 35 finished with value: 0.7447389900221746 and parameters: {'subsample': 0.23046082538612173, 'dropout_rate': 0.7920235481779454, 'n_estimators': 237, 'learning_rate': 0.09185657793063773}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:04:22,225] Trial 36 finished with value: 0.7437585978653118 and parameters: {'subsample': 0.22991800703640367, 'dropout_rate': 0.7794160201987603, 'n_estimators': 224, 'learning_rate': 0.09268864606477101}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6666666666666666
[I 2024-04-14 01:04:24,691] Trial 37 finished with value: 0.7428196307291616 and parameters: {'subsample': 0.13890022905620997, 'dropout_rate': 0.8389642203595953, 'n_estimators': 114, 'learning_rate': 0.08560147823387264}. Best is trial 11 with value: 0.7455338965923975.

Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:04:29,690] Trial 38 finished with value: 0.6880454636310838 and parameters: {'subsample': 0.5686484351119852, 'dropout_rate': 0.9273237630210112, 'n_estimators': 246, 'learning_rate': 0.07845082851951218}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:04:38,187] Trial 39 finished with value: 0.6975692731548933 and parameters: {'subsample': 0.8328204942141013, 'dropout_rate': 0.1771839477929863, 'n_estimators': 285, 'learning_rate': 0.013931445007643331}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:04:41,295] Trial 40 finished with value: 0.7446243987311127 and parameters: {'subsample': 0.20512834037464736, 'dropout_rate': 0.9035431008219736, 'n_estimators': 169, 'learning_rate': 0.05705592821195385}. Best is trial 11 with value: 0.7455338965923975.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:04:50,566] Trial 41 finished with value: 0.7456047908879755 and parameters: {'subsample': 0.25894032837876935, 'dropout_rate': 0.6875395326119147, 'n_estimators': 333, 'learning_rate': 0.06813530725208441}. Best is trial 41 with value: 0.7456047908879755.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:04:59,577] Trial 42 finished with value: 0.7480876021943162 and parameters: {'subsample': 0.3346265288954276, 'dropout_rate': 0.611668764376818, 'n_estimators': 321, 'learning_rate': 0.09286121509803555}. Best is trial 42 with value: 0.7480876021943162.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:05:09,613] Trial 43 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.412210516160093, 'dropout_rate': 0.5038080662494101, 'n_estimators': 331, 'learning_rate': 0.09983881368300843}. Best is trial 42 with value: 0.7480876021943162.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:05:21,090] Trial 44 finished with value: 0.749819203925918 and parameters: {'subsample': 0.3346772930839735, 'dropout_rate': 0.5950141439065969, 'n_estimators': 358, 'learning_rate': 0.0721972100247915}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:05:30,788] Trial 45 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.4516370662115133, 'dropout_rate': 0.5882085543187293, 'n_estimators': 324, 'learning_rate': 0.07358829455007394}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:05:40,009] Trial 46 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.5301819996476037, 'dropout_rate': 0.44999007783582673, 'n_estimators': 311, 'learning_rate': 0.05378014293554952}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:05:46,719] Trial 47 finished with value: 0.7480876021943162 and parameters: {'subsample': 0.3453767208826718, 'dropout_rate': 0.6532308894704617, 'n_estimators': 276, 'learning_rate': 0.09473558281280803}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:05:53,470] Trial 48 finished with value: 0.7480876021943162 and parameters: {'subsample': 0.3457087938509151, 'dropout_rate': 0.644266468452372, 'n_estimators': 273, 'learning_rate': 0.0705777227101228}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:06:00,479] Trial 49 finished with value: 0.748953403060117 and parameters: {'subsample': 0.33220099497464983, 'dropout_rate': 0.6410270573167214, 'n_estimators': 272, 'learning_rate': 0.04575921161100688}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:06:04,433] Trial 50 finished with value: 0.748953403060117 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.633091953438621, 'n_estimators': 195, 'learning_rate': 0.04379408649449233}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:06:08,426] Trial 51 finished with value: 0.749819203925918 and parameters: {'subsample': 0.33836083203143946, 'dropout_rate': 0.6360453549167212, 'n_estimators': 189, 'learning_rate': 0.044972737627305054}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:12,618] Trial 52 finished with value: 0.6879797066033013 and parameters: {'subsample': 0.39018613021863213, 'dropout_rate': 0.562284204310507, 'n_estimators': 185, 'learning_rate': 0.043394012786333945}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:06:17,417] Trial 53 finished with value: 0.748953403060117 and parameters: {'subsample': 0.3185066051347939, 'dropout_rate': 0.6170851342509093, 'n_estimators': 209, 'learning_rate': 0.035560723291921593}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:22,052] Trial 54 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.46248562682407, 'dropout_rate': 0.6131781116156075, 'n_estimators': 200, 'learning_rate': 0.03712368626160444}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:25,274] Trial 55 finished with value: 0.7329177954752139 and parameters: {'subsample': 0.328690788381509, 'dropout_rate': 0.5387112996979111, 'n_estimators': 145, 'learning_rate': 0.02947982386104511}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:26,660] Trial 56 finished with value: 0.689711308334903 and parameters: {'subsample': 0.5126322256147516, 'dropout_rate': 0.6158965346115595, 'n_estimators': 83, 'learning_rate': 0.04849464086379648}. Best is trial 44 with value: 0.749819203925918.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:32,282] Trial 57 finished with value: 0.703061193743612 and parameters: {'subsample': 0.3757284300828613, 'dropout_rate': 0.5856006941737971, 'n_estimators': 215, 'learning_rate': 0.04809228066503415}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:35,797] Trial 58 finished with value: 0.6888235884598414 and parameters: {'subsample': 0.44696287521327244, 'dropout_rate': 0.5272357542550171, 'n_estimators': 165, 'learning_rate': 0.034364926319624366}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:39,686] Trial 59 finished with value: 0.6879797066033013 and parameters: {'subsample': 0.3899904687279276, 'dropout_rate': 0.6376953556703313, 'n_estimators': 187, 'learning_rate': 0.026769493555455874}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:06:42,764] Trial 60 finished with value: 0.689711308334903 and parameters: {'subsample': 0.5630255578139995, 'dropout_rate': 0.4966307050742853, 'n_estimators': 148, 'learning_rate': 0.020228156823351738}. Best is trial 44 with value: 0.749819203925918.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:06:47,810] Trial 61 finished with value: 0.7506850047917188 and parameters: {'subsample': 0.3385180226064827, 'dropout_rate': 0.6672299985480628, 'n_estimators': 225, 'learning_rate': 0.03906201007616112}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:06:53,758] Trial 62 finished with value: 0.7472218013285155 and parameters: {'subsample': 0.31109646030762605, 'dropout_rate': 0.570120177316096, 'n_estimators': 232, 'learning_rate': 0.03944036742801146}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:07:00,001] Trial 63 finished with value: 0.7277229902804085 and parameters: {'subsample': 0.25932754250436657, 'dropout_rate': 0.7001175645444487, 'n_estimators': 259, 'learning_rate': 0.04461842658350024}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:04,539] Trial 64 finished with value: 0.7472218013285155 and parameters: {'subsample': 0.2860352199171424, 'dropout_rate': 0.5946225330414188, 'n_estimators': 208, 'learning_rate': 0.058114715439072616}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:12,093] Trial 65 finished with value: 0.7480876021943162 and parameters: {'subsample': 0.34953832551791164, 'dropout_rate': 0.7536178932039197, 'n_estimators': 299, 'learning_rate': 0.050367972811122}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:16,287] Trial 66 finished with value: 0.748953403060117 and parameters: {'subsample': 0.32156863034793126, 'dropout_rate': 0.6645098503914225, 'n_estimators': 190, 'learning_rate': 0.03422571990323046}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:07:18,598] Trial 67 finished with value: 0.6905551901914432 and parameters: {'subsample': 0.3971221278983566, 'dropout_rate': 0.6622769398021714, 'n_estimators': 121, 'learning_rate': 0.03510083979855439}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:07:22,923] Trial 68 finished with value: 0.685448061033681 and parameters: {'subsample': 0.6099875522212969, 'dropout_rate': 0.7223768168679915, 'n_estimators': 199, 'learning_rate': 0.04579660040561051}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8312236286919831
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:07:27,074] Trial 69 finished with value: 0.7320081565908912 and parameters: {'subsample': 0.3056990064754349, 'dropout_rate': 0.549562744621341, 'n_estimators': 163, 'learning_rate': 0.03143434171900204}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8270042194092827
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:07:28,677] Trial 70 finished with value: 0.6888235884598414 and parameters: {'subsample': 0.42867958789469585, 'dropout_rate': 0.6345895145331699, 'n_estimators': 86, 'learning_rate': 0.04022275968536438}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:07:33,760] Trial 71 finished with value: 0.703061193743612 and parameters: {'subsample': 0.37104298081980164, 'dropout_rate': 0.6736934203246976, 'n_estimators': 230, 'learning_rate': 0.023337183213226805}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:38,746] Trial 72 finished with value: 0.7480876021943162 and parameters: {'subsample': 0.3198431288734141, 'dropout_rate': 0.6267991877897894, 'n_estimators': 220, 'learning_rate': 0.03716708955623538}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:42,594] Trial 73 finished with value: 0.7472218013285155 and parameters: {'subsample': 0.24753155556022144, 'dropout_rate': 0.7621002346579976, 'n_estimators': 188, 'learning_rate': 0.052058600558823165}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:48,495] Trial 74 finished with value: 0.7437585978653118 and parameters: {'subsample': 0.19730180066644326, 'dropout_rate': 0.6975657334749211, 'n_estimators': 250, 'learning_rate': 0.04662754369701142}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:07:55,097] Trial 75 finished with value: 0.7506850047917188 and parameters: {'subsample': 0.3340679648733413, 'dropout_rate': 0.5966220884674124, 'n_estimators': 261, 'learning_rate': 0.04263308474611405}. Best is trial 61 with value: 0.7506850047917188.

Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:07:59,558] Trial 76 finished with value: 0.6879797066033013 and parameters: {'subsample': 0.47979947406257184, 'dropout_rate': 0.5110686100436799, 'n_estimators': 203, 'learning_rate': 0.04316951632558747}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:08:02,532] Trial 77 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.3661588317176384, 'dropout_rate': 0.6608173019656793, 'n_estimators': 152, 'learning_rate': 0.04133851254492565}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.6796536796536796
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:08:05,094] Trial 78 finished with value: 0.7156335978653119 and parameters: {'subsample': 0.28620675122110767, 'dropout_rate': 0.45556132136232985, 'n_estimators': 126, 'learning_rate': 0.03457910137785391}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.6926406926406926
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:08:10,769] Trial 79 finished with value: 0.7463560004627144 and parameters: {'subsample': 0.29893498111414557, 'dropout_rate': 0.5619794603920352, 'n_estimators': 240, 'learning_rate': 0.029926071515463493}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7575757575757576
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.810126582278481
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:08:17,251] Trial 80 finished with value: 0.6975692731548933 and parameters: {'subsample': 0.8321289633684164, 'dropout_rate': 0.5961975726465606, 'n_estimators': 260, 'learning_rate': 0.03857238794480661}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:08:24,956] Trial 81 finished with value: 0.7480876021943162 and parameters: {'subsample': 0.3332129327082944, 'dropout_rate': 0.6294428090274307, 'n_estimators': 285, 'learning_rate': 0.04186642941322338}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:08:36,290] Trial 82 finished with value: 0.748953403060117 and parameters: {'subsample': 0.33780645697786327, 'dropout_rate': 0.600709945180324, 'n_estimators': 353, 'learning_rate': 0.04846741682925764}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.6883116883116883
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:08:46,834] Trial 83 finished with value: 0.7454901995969136 and parameters: {'subsample': 0.27690111533077316, 'dropout_rate': 0.7266926066608036, 'n_estimators': 366, 'learning_rate': 0.04940194280503194}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:09:04,687] Trial 84 finished with value: 0.7057469159198064 and parameters: {'subsample': 0.3965939459985383, 'dropout_rate': 0.6733136431242371, 'n_estimators': 494, 'learning_rate': 0.054823166073972196}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:09:18,822] Trial 85 finished with value: 0.7438731891563737 and parameters: {'subsample': 0.24122170239324311, 'dropout_rate': 0.5985523249779585, 'n_estimators': 409, 'learning_rate': 0.051771423775794495}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:09:29,073] Trial 86 finished with value: 0.703061193743612 and parameters: {'subsample': 0.4399423805357687, 'dropout_rate': 0.5784872900820404, 'n_estimators': 351, 'learning_rate': 0.0595880310632668}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:09:32,626] Trial 87 finished with value: 0.7021953928778112 and parameters: {'subsample': 0.3617196823716256, 'dropout_rate': 0.6898038619932075, 'n_estimators': 174, 'learning_rate': 0.04601158167265101}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7142857142857143
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:09:37,516] Trial 88 finished with value: 0.7506850047917188 and parameters: {'subsample': 0.3321049076053748, 'dropout_rate': 0.6516557791922656, 'n_estimators': 217, 'learning_rate': 0.037162986254297}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:09:41,461] Trial 89 finished with value: 0.748953403060117 and parameters: {'subsample': 0.27186462815090734, 'dropout_rate': 0.6520508409527307, 'n_estimators': 191, 'learning_rate': 0.03298122442492786}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:09:45,933] Trial 90 finished with value: 0.748953403060117 and parameters: {'subsample': 0.3155532104150591, 'dropout_rate': 0.7736257475237115, 'n_estimators': 216, 'learning_rate': 0.03656514081179736}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.70995670995671
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:09:49,519] Trial 91 finished with value: 0.7329177954752139 and parameters: {'subsample': 0.3353298681606855, 'dropout_rate': 0.5534943119761607, 'n_estimators': 176, 'learning_rate': 0.06455741274574349}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:09:54,517] Trial 92 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.38205107889556905, 'dropout_rate': 0.6458227043957403, 'n_estimators': 226, 'learning_rate': 0.044077962703692054}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:10:00,561] Trial 93 finished with value: 0.6888455074691022 and parameters: {'subsample': 0.4151547586945729, 'dropout_rate': 0.7072487186319236, 'n_estimators': 268, 'learning_rate': 0.026538068968566333}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.696969696969697
Fold 2 C-index: 0.6004464285714286
Fold 3 C-index: 0.7328431372549019
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:10:04,844] Trial 94 finished with value: 0.7048811150540055 and parameters: {'subsample': 0.3520018208761431, 'dropout_rate': 0.5306326676271426, 'n_estimators': 197, 'learning_rate': 0.03894829252125997}. Best is trial 61 with value: 0.7506850047917188.

Fold 1 C-index: 0.7012987012987013
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:10:09,504] Trial 95 finished with value: 0.7480876021943162 and parameters: {'subsample': 0.29682319369976184, 'dropout_rate': 0.6107323193763101, 'n_estimators': 211, 'learning_rate': 0.04194035074012053}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.7056277056277056
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.803921568627451
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:10:17,401] Trial 96 finished with value: 0.748953403060117 and parameters: {'subsample': 0.32613042309951357, 'dropout_rate': 0.6714640849895496, 'n_estimators': 293, 'learning_rate': 0.04805773812669599}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:10:23,682] Trial 97 finished with value: 0.7438731891563737 and parameters: {'subsample': 0.1816840399382675, 'dropout_rate': 0.622717815809777, 'n_estimators': 248, 'learning_rate': 0.03184901175247192}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.683982683982684
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.8088235294117647
Fold 4 C-index: 0.8227848101265823
Fold 5 C-index: 0.5868544600938967
[I 2024-04-14 01:10:32,554] Trial 98 finished with value: 0.7287033824372713 and parameters: {'subsample': 0.2659857973386154, 'dropout_rate': 0.5821322773093658, 'n_estimators': 308, 'learning_rate': 0.036291471317449066}. Best is trial 61 with value: 0.7506850047917188.
Fold 1 C-index: 0.6753246753246753
Fold 2 C-index: 0.7410714285714286
Fold 3 C-index: 0.7990196078431373
Fold 4 C-index: 0.8227848101265823

[I 2024-04-14 01:10:35,785] A new study created in memory with name: no-name-422b9c67-5e75-47a4-bf94-07159d902c81

Fold 5 C-index: 0.6713615023474179
[I 2024-04-14 01:10:35,743] Trial 99 finished with value: 0.7419124048426482 and parameters: {'subsample': 0.22511961525431745, 'dropout_rate': 0.7306115628455275, 'n_estimators': 163, 'learning_rate': 0.05265295186098596}. Best is trial 61 with value: 0.7506850047917188.


* Best trial for C-index:
 FrozenTrial(number=61, state=TrialState.COMPLETE, values=[0.7506850047917188], datetime_start=datetime.datetime(2024, 4, 14, 1, 6, 42, 770843), datetime_complete=datetime.datetime(2024, 4, 14, 1, 6, 47, 809502), params={'subsample': 0.3385180226064827, 'dropout_rate': 0.6672299985480628, 'n_estimators': 225, 'learning_rate': 0.03906201007616112}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=61, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.3385180226064827, 'dropout_rate': 0.6672299985480628, 'n_estimators': 225, 'learning_rate': 0.03906201007616112}


* Best Score for C-index:
 0.7506850047917188

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.14918352247008534
Fold 2 IBS: 0.2480311476040521
Fold 3 IBS: 0.1885044012763269
Fold 4 IBS: 0.15803839701813882
Fold 5 IBS: 0.2776943688545995
[I 2024-04-14 01:10:38,103] Trial 0 finished with value: 0.20429036744464052 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.20429036744464052.
Fold 1 IBS: 0.1402193335090749
Fold 2 IBS: 0.30424860142953786
Fold 3 IBS: 0.22267100958143807
Fold 4 IBS: 0.14265387268699134
Fold 5 IBS: 0.35818495115201227
[I 2024-04-14 01:10:57,749] Trial 1 finished with value: 0.2335955536718109 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.20429036744464052.
Fold 1 IBS: 0.1332782004241256
Fold 2 IBS: 0.288012689504797
Fold 3 IBS: 0.2073261891798709
Fold 4 IBS: 0.14030347657551043
Fold 5 IBS: 0.33454528452462623
[I 2024-04-14 01:11:01,300] Trial 2 finished with value: 0.22069316804178601 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.20429036744464052.
Fold 1 IBS: 0.13379389039292883
Fold 2 IBS: 0.2910726447702933
Fold 3 IBS: 0.21162355090896007
Fold 4 IBS: 0.14000884263542449
Fold 5 IBS: 0.3426938496142454
[I 2024-04-14 01:11:06,034] Trial 3 finished with value: 0.22383855566437044 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.20429036744464052.
Fold 1 IBS: 0.15968482862637481
Fold 2 IBS: 0.29302898854602555
Fold 3 IBS: 0.20865945413808482
Fold 4 IBS: 0.13778149604717774
Fold 5 IBS: 0.3419437202996414
[I 2024-04-14 01:11:13,674] Trial 4 finished with value: 0.22821969753146085 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.20429036744464052.
Fold 1 IBS: 0.13864660264682663
Fold 2 IBS: 0.3029903187309585
Fold 3 IBS: 0.22127978171041846
Fold 4 IBS: 0.14171695129747422
Fold 5 IBS: 0.35631880894959
[I 2024-04-14 01:11:23,137] Trial 5 finished with value: 0.23219049266705355 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.20429036744464052.
Fold 1 IBS: 0.16341393493965067
Fold 2 IBS: 0.23170723544772448
Fold 3 IBS: 0.18626742649980968
Fold 4 IBS: 0.1728377319222419
Fold 5 IBS: 0.25279397988332225
[I 2024-04-14 01:11:27,694] Trial 6 finished with value: 0.2014040617385498 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.1847676090933227
Fold 2 IBS: 0.22097595744110046
Fold 3 IBS: 0.19127685273470962
Fold 4 IBS: 0.1967496726653444
Fold 5 IBS: 0.22830347169000548
[I 2024-04-14 01:11:28,737] Trial 7 finished with value: 0.20441471272489653 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.14647777993065303
Fold 2 IBS: 0.25112633129815143
Fold 3 IBS: 0.19080719599135282
Fold 4 IBS: 0.15418474604933646
Fold 5 IBS: 0.28340934578346205
[I 2024-04-14 01:11:33,400] Trial 8 finished with value: 0.20520107981059116 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.1340934401856464
Fold 2 IBS: 0.3034720561008603
Fold 3 IBS: 0.22163902399242336
Fold 4 IBS: 0.14129184417810062
Fold 5 IBS: 0.3569395382029105
[I 2024-04-14 01:11:46,788] Trial 9 finished with value: 0.23148718053198825 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.20538536397156817
Fold 2 IBS: 0.22019853996541608
Fold 3 IBS: 0.19974441689998532
Fold 4 IBS: 0.2159360273742552
Fold 5 IBS: 0.21998044353840004
[I 2024-04-14 01:11:55,062] Trial 10 finished with value: 0.21224895834992497 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 328, 'learning_rate': 0.0017980531969980576}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.18596221217585793
Fold 2 IBS: 0.22078100848444115
Fold 3 IBS: 0.19106436965115287
Fold 4 IBS: 0.1960854479846967
Fold 5 IBS: 0.22908876811165793
[I 2024-04-14 01:11:57,062] Trial 11 finished with value: 0.20459636128156133 and parameters: {'subsample': 0.8563264881207873, 'dropout_rate': 0.3306437349344059, 'n_estimators': 99, 'learning_rate': 0.020726317464293063}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.1366847599808366
Fold 2 IBS: 0.2819534227885767
Fold 3 IBS: 0.20320208425396313
Fold 4 IBS: 0.1423082679558686
Fold 5 IBS: 0.324480615033528
[I 2024-04-14 01:11:59,453] Trial 12 finished with value: 0.21772583000255458 and parameters: {'subsample': 0.7005255083966228, 'dropout_rate': 0.3407483301890853, 'n_estimators': 116, 'learning_rate': 0.09635955935176935}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.2102519500614092
Fold 2 IBS: 0.2208690105137291
Fold 3 IBS: 0.202364049341396
Fold 4 IBS: 0.2207658371525474
Fold 5 IBS: 0.21875322482820383
[I 2024-04-14 01:12:00,044] Trial 13 finished with value: 0.2146008143794571 and parameters: {'subsample': 0.8375283540798665, 'dropout_rate': 0.10204657427249281, 'n_estimators': 12, 'learning_rate': 0.020825018906816123}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.21072412615199612
Fold 2 IBS: 0.22063673609199017
Fold 3 IBS: 0.20241135238746766
Fold 4 IBS: 0.22114929599866973
Fold 5 IBS: 0.21879204510844938
[I 2024-04-14 01:12:02,651] Trial 14 finished with value: 0.21474271114771462 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.3797566211149095, 'n_estimators': 124, 'learning_rate': 0.0025916531369806137}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.18420318614261982
Fold 2 IBS: 0.22113878859893407
Fold 3 IBS: 0.190578210361823
Fold 4 IBS: 0.1946959984897321
Fold 5 IBS: 0.2304254801647583
[I 2024-04-14 01:12:03,907] Trial 15 finished with value: 0.20420833275157343 and parameters: {'subsample': 0.9623249773241934, 'dropout_rate': 0.6659535844592464, 'n_estimators': 71, 'learning_rate': 0.030719364452518588}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.13950171744692333
Fold 2 IBS: 0.273219300056611
Fold 3 IBS: 0.20020276487730007
Fold 4 IBS: 0.1441790217922282
Fold 5 IBS: 0.31554466824466554
[I 2024-04-14 01:12:10,174] Trial 16 finished with value: 0.21452949448354558 and parameters: {'subsample': 0.9954991512541396, 'dropout_rate': 0.7066803662705897, 'n_estimators': 271, 'learning_rate': 0.03583624535718763}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.19985061607246224
Fold 2 IBS: 0.2197820174273508
Fold 3 IBS: 0.19717977139605783
Fold 4 IBS: 0.21053092643734245
Fold 5 IBS: 0.22192371746584236
[I 2024-04-14 01:12:11,270] Trial 17 finished with value: 0.20985340975981112 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 56, 'learning_rate': 0.017444467713368942}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.1525496652333737
Fold 2 IBS: 0.24232709550709394
Fold 3 IBS: 0.18783707900031024
Fold 4 IBS: 0.1600535626299324
Fold 5 IBS: 0.269821156460139
[I 2024-04-14 01:12:14,180] Trial 18 finished with value: 0.20251771176616984 and parameters: {'subsample': 0.5993762574986359, 'dropout_rate': 0.8307549552245073, 'n_estimators': 160, 'learning_rate': 0.035858486087103104}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.18514281653420592

Fold 2 IBS: 0.22098901295141482
Fold 3 IBS: 0.19045013870250915
Fold 4 IBS: 0.19457407998909504
Fold 5 IBS: 0.2297046752990242
[I 2024-04-14 01:12:17,710] Trial 19 finished with value: 0.20417214469524986 and parameters: {'subsample': 0.6203097276533311, 'dropout_rate': 0.7825648884185067, 'n_estimators': 169, 'learning_rate': 0.012702076480642453}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.1330635531817609
Fold 2 IBS: 0.2873945911931824
Fold 3 IBS: 0.20988152123608766
Fold 4 IBS: 0.13886518764316072
Fold 5 IBS: 0.3342176432895853
[I 2024-04-14 01:12:25,847] Trial 20 finished with value: 0.2206844993087554 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.825887859456495, 'n_estimators': 315, 'learning_rate': 0.039831795316557894}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.19073287393187716
Fold 2 IBS: 0.22033336815614252
Fold 3 IBS: 0.1923689926601459
Fold 4 IBS: 0.19934903879334157
Fold 5 IBS: 0.22693510103337397
[I 2024-04-14 01:12:28,856] Trial 21 finished with value: 0.20594387491497618 and parameters: {'subsample': 0.6018701078534102, 'dropout_rate': 0.9754161103921428, 'n_estimators': 165, 'learning_rate': 0.010940993943184235}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.14860095216944366
Fold 2 IBS: 0.24716593395082012
Fold 3 IBS: 0.18941245684345862
Fold 4 IBS: 0.15683242418400425
Fold 5 IBS: 0.2786699337529756
[I 2024-04-14 01:12:33,908] Trial 22 finished with value: 0.20413634018014046 and parameters: {'subsample': 0.6408240487280729, 'dropout_rate': 0.7925820693854744, 'n_estimators': 231, 'learning_rate': 0.02733211242542101}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.1482130765083953
Fold 2 IBS: 0.2487257203411851
Fold 3 IBS: 0.18964011482688656
Fold 4 IBS: 0.15591646608813137
Fold 5 IBS: 0.2814728131264584
[I 2024-04-14 01:12:38,621] Trial 23 finished with value: 0.20479363817821133 and parameters: {'subsample': 0.7836494840655531, 'dropout_rate': 0.7763274658777246, 'n_estimators': 230, 'learning_rate': 0.028308405342242465}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.13626332830353893
Fold 2 IBS: 0.2987371902795815
Fold 3 IBS: 0.21663215128916008
Fold 4 IBS: 0.14050367972220054
Fold 5 IBS: 0.34971644215893055
[I 2024-04-14 01:12:47,788] Trial 24 finished with value: 0.22837055835068232 and parameters: {'subsample': 0.6137727273131017, 'dropout_rate': 0.981998984030378, 'n_estimators': 385, 'learning_rate': 0.04338790451384301}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.14774472818077072
Fold 2 IBS: 0.2500296809259093
Fold 3 IBS: 0.19064483677293892
Fold 4 IBS: 0.1557378705317201
Fold 5 IBS: 0.2828729295934891
[I 2024-04-14 01:12:55,640] Trial 25 finished with value: 0.2054060092009656 and parameters: {'subsample': 0.38538376630592974, 'dropout_rate': 0.5518291595769297, 'n_estimators': 290, 'learning_rate': 0.02317780567031417}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.19277460439517552
Fold 2 IBS: 0.21986517506623263
Fold 3 IBS: 0.19370425645272454
Fold 4 IBS: 0.20348981807865243
Fold 5 IBS: 0.22484679287385206
[I 2024-04-14 01:12:58,269] Trial 26 finished with value: 0.20693612937332745 and parameters: {'subsample': 0.6602158150848849, 'dropout_rate': 0.9043358852861348, 'n_estimators': 150, 'learning_rate': 0.009971362950326447}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.15023747763915007
Fold 2 IBS: 0.24575376992723943
Fold 3 IBS: 0.18811794875252227
Fold 4 IBS: 0.15916469272014555
Fold 5 IBS: 0.27563135839668823
[I 2024-04-14 01:13:04,042] Trial 27 finished with value: 0.20378104948714912 and parameters: {'subsample': 0.7865056045166827, 'dropout_rate': 0.43844927240855114, 'n_estimators': 234, 'learning_rate': 0.025905020914217397}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.14457131039614401
Fold 2 IBS: 0.25533272235383586
Fold 3 IBS: 0.19187581897326514
Fold 4 IBS: 0.1516405800140905
Fold 5 IBS: 0.28993867766170295
[I 2024-04-14 01:13:08,883] Trial 28 finished with value: 0.20667182187980768 and parameters: {'subsample': 0.787271881966642, 'dropout_rate': 0.22471780618636442, 'n_estimators': 198, 'learning_rate': 0.037539067339670384}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.14201527814647438
Fold 2 IBS: 0.2638725041106925
Fold 3 IBS: 0.19511987767402966
Fold 4 IBS: 0.1481391536641321
Fold 5 IBS: 0.30106844246148584
[I 2024-04-14 01:13:11,721] Trial 29 finished with value: 0.2100430512113629 and parameters: {'subsample': 0.9170722284261257, 'dropout_rate': 0.4175950896276197, 'n_estimators': 139, 'learning_rate': 0.060104579126943766}. Best is trial 6 with value: 0.2014040617385498.
Fold 1 IBS: 0.16219530264987192
Fold 2 IBS: 0.23253922552200018
Fold 3 IBS: 0.1862621853159182
Fold 4 IBS: 0.17121466403271784
Fold 5 IBS: 0.25370311889169894
[I 2024-04-14 01:13:13,510] Trial 30 finished with value: 0.20118289928244143 and parameters: {'subsample': 0.7421985276925959, 'dropout_rate': 0.5137641761837478, 'n_estimators': 92, 'learning_rate': 0.047628078676825406}. Best is trial 30 with value: 0.20118289928244143.
Fold 1 IBS: 0.16421111540128447
Fold 2 IBS: 0.2308344398665977
Fold 3 IBS: 0.186258349808599
Fold 4 IBS: 0.1733976470107075
Fold 5 IBS: 0.2509321203919179
[I 2024-04-14 01:13:15,390] Trial 31 finished with value: 0.20112673449582133 and parameters: {'subsample': 0.7632781450536849, 'dropout_rate': 0.5162864520433952, 'n_estimators': 93, 'learning_rate': 0.044653981428756685}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1655289786273483
Fold 2 IBS: 0.22986997292884212
Fold 3 IBS: 0.18630310698863523
Fold 4 IBS: 0.17473194099958272
Fold 5 IBS: 0.24941046201394396
[I 2024-04-14 01:13:17,188] Trial 32 finished with value: 0.20116889231167043 and parameters: {'subsample': 0.7341499911170974, 'dropout_rate': 0.5052300815524811, 'n_estimators': 87, 'learning_rate': 0.04583218897228228}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.20646933301795375
Fold 2 IBS: 0.22033171824320508
Fold 3 IBS: 0.20044790376377603
Fold 4 IBS: 0.21689356186975722
Fold 5 IBS: 0.21967797929636174
[I 2024-04-14 01:13:17,845] Trial 33 finished with value: 0.21276409923821077 and parameters: {'subsample': 0.7587627313150367, 'dropout_rate': 0.5032281991773906, 'n_estimators': 11, 'learning_rate': 0.04529715527200868}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.15184771907571565
Fold 2 IBS: 0.244122482328955
Fold 3 IBS: 0.18814326103063747
Fold 4 IBS: 0.15952593670429427
Fold 5 IBS: 0.2731636907464685
[I 2024-04-14 01:13:19,743] Trial 34 finished with value: 0.2033606179772142 and parameters: {'subsample': 0.717908097279745, 'dropout_rate': 0.599422164900876, 'n_estimators': 97, 'learning_rate': 0.06088665781417231}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1540642530220619
Fold 2 IBS: 0.24055026033692928
Fold 3 IBS: 0.1869127979687166
Fold 4 IBS: 0.1641432832523913
Fold 5 IBS: 0.26635055714589606
[I 2024-04-14 01:13:21,288] Trial 35 finished with value: 0.20240423034519903 and parameters: {'subsample': 0.7258721139702676, 'dropout_rate': 0.48572309187478285, 'n_estimators': 76, 'learning_rate': 0.07116031059140247}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1746208562370821
Fold 2 IBS: 0.226693258784134
Fold 3 IBS: 0.18725996749801332
Fold 4 IBS: 0.1803914419021467
Fold 5 IBS: 0.24268033243907455
[I 2024-04-14 01:13:22,349] Trial 36 finished with value: 0.20232917137209014 and parameters: {'subsample': 0.560663332945815, 'dropout_rate': 0.2700522872940725, 'n_estimators': 40, 'learning_rate': 0.08793239753187249}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.15795028745600365
Fold 2 IBS: 0.23670722690745175
Fold 3 IBS: 0.1865343310905724
Fold 4 IBS: 0.16645704754398877
Fold 5 IBS: 0.26045349264296996
[I 2024-04-14 01:13:24,070] Trial 37 finished with value: 0.2016204771281973 and parameters: {'subsample': 0.8347465791537408, 'dropout_rate': 0.39390812989421653, 'n_estimators': 90, 'learning_rate': 0.05531916714852682}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1796808629062474
Fold 2 IBS: 0.22239844339586823
Fold 3 IBS: 0.18937540158360938

Fold 4 IBS: 0.18963358127091137
Fold 5 IBS: 0.23395808174187974
[I 2024-04-14 01:13:24,935] Trial 38 finished with value: 0.20300927417970324 and parameters: {'subsample': 0.9229861705051505, 'dropout_rate': 0.5445128971839069, 'n_estimators': 32, 'learning_rate': 0.07994143832657483}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.14089593072095502
Fold 2 IBS: 0.26511117850380844
Fold 3 IBS: 0.19677652632752524
Fold 4 IBS: 0.14729454625577706
Fold 5 IBS: 0.3047581909661958
[I 2024-04-14 01:13:28,680] Trial 39 finished with value: 0.2109672745548523 and parameters: {'subsample': 0.6847274160309886, 'dropout_rate': 0.6026791333381789, 'n_estimators': 182, 'learning_rate': 0.047260604312967414}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.13971317742997533
Fold 2 IBS: 0.2680025852392165
Fold 3 IBS: 0.19568605187963634
Fold 4 IBS: 0.14626529602655097
Fold 5 IBS: 0.30607863999868745
[I 2024-04-14 01:13:31,444] Trial 40 finished with value: 0.21114915011481333 and parameters: {'subsample': 0.5289574348660577, 'dropout_rate': 0.28569150631314294, 'n_estimators': 138, 'learning_rate': 0.0653345425150269}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1586425932900157
Fold 2 IBS: 0.23604101841641817
Fold 3 IBS: 0.18645424120135148
Fold 4 IBS: 0.16713794774071586
Fold 5 IBS: 0.25933929673240336
[I 2024-04-14 01:13:33,380] Trial 41 finished with value: 0.20152301947618093 and parameters: {'subsample': 0.8296733693641463, 'dropout_rate': 0.3955650676949525, 'n_estimators': 89, 'learning_rate': 0.054857348720456764}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.17209083014319493
Fold 2 IBS: 0.22620391014358368
Fold 3 IBS: 0.18711528000560107
Fold 4 IBS: 0.18184310057822442
Fold 5 IBS: 0.24154435527422655
[I 2024-04-14 01:13:34,910] Trial 42 finished with value: 0.20175949522896613 and parameters: {'subsample': 0.8059185097486953, 'dropout_rate': 0.4614374643800526, 'n_estimators': 67, 'learning_rate': 0.04995294401710439}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1512484495595032
Fold 2 IBS: 0.2449844058586995
Fold 3 IBS: 0.18823614399330163
Fold 4 IBS: 0.15915696147169306
Fold 5 IBS: 0.27420353011880194
[I 2024-04-14 01:13:37,763] Trial 43 finished with value: 0.2035658982003999 and parameters: {'subsample': 0.9054595545917978, 'dropout_rate': 0.316763951960898, 'n_estimators': 117, 'learning_rate': 0.05159300459483633}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.15907793990852429
Fold 2 IBS: 0.2352730689755104
Fold 3 IBS: 0.18648787272245734
Fold 4 IBS: 0.16811236869469545
Fold 5 IBS: 0.25900445620711016
[I 2024-04-14 01:13:39,492] Trial 44 finished with value: 0.2015911413016595 and parameters: {'subsample': 0.7380511801449722, 'dropout_rate': 0.5020020877800176, 'n_estimators': 83, 'learning_rate': 0.057433886209706145}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1463776229168604
Fold 2 IBS: 0.2533374566272833
Fold 3 IBS: 0.19083476809127434
Fold 4 IBS: 0.15341726034472997
Fold 5 IBS: 0.28606616846227817
[I 2024-04-14 01:13:41,820] Trial 45 finished with value: 0.20600665528848525 and parameters: {'subsample': 0.8700695716601613, 'dropout_rate': 0.41807203909136775, 'n_estimators': 110, 'learning_rate': 0.06411880777141404}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.1430132596040325
Fold 2 IBS: 0.25928727139802615
Fold 3 IBS: 0.19366775734884709
Fold 4 IBS: 0.14956222974535657
Fold 5 IBS: 0.29593505155130806
[I 2024-04-14 01:13:46,209] Trial 46 finished with value: 0.2082931139295141 and parameters: {'subsample': 0.8165161478472168, 'dropout_rate': 0.2220581094238878, 'n_estimators': 194, 'learning_rate': 0.04106943268126226}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.19492265314784585
Fold 2 IBS: 0.21977515373447323
Fold 3 IBS: 0.19501266039999943
Fold 4 IBS: 0.20642207681033067
Fold 5 IBS: 0.22377539766303875
[I 2024-04-14 01:13:46,999] Trial 47 finished with value: 0.20798158835113756 and parameters: {'subsample': 0.7592463159056656, 'dropout_rate': 0.3870963354626606, 'n_estimators': 27, 'learning_rate': 0.0486111103468835}. Best is trial 31 with value: 0.20112673449582133.
Fold 1 IBS: 0.16285561230661114
Fold 2 IBS: 0.23081920471595616
Fold 3 IBS: 0.18627944018629622
Fold 4 IBS: 0.1726572667492338
Fold 5 IBS: 0.2513516238461913
[I 2024-04-14 01:13:48,109] Trial 48 finished with value: 0.2007926295608577 and parameters: {'subsample': 0.6626333762174762, 'dropout_rate': 0.5685805772015377, 'n_estimators': 55, 'learning_rate': 0.07550425969628831}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.21027180993705039
Fold 2 IBS: 0.22092195608480053
Fold 3 IBS: 0.2027593837370433
Fold 4 IBS: 0.22064013075822794
Fold 5 IBS: 0.21869818697521187
[I 2024-04-14 01:13:48,623] Trial 49 finished with value: 0.2146582934984668 and parameters: {'subsample': 0.6817855157498574, 'dropout_rate': 0.6414150413521851, 'n_estimators': 3, 'learning_rate': 0.07807745749163557}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.15400499318344493
Fold 2 IBS: 0.24099011795908012
Fold 3 IBS: 0.18715636699073485
Fold 4 IBS: 0.16242133177670995
Fold 5 IBS: 0.2655056626664292
[I 2024-04-14 01:13:49,800] Trial 50 finished with value: 0.20201569451527984 and parameters: {'subsample': 0.5554941675308335, 'dropout_rate': 0.523648745470371, 'n_estimators': 55, 'learning_rate': 0.09908361867719767}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1377487496892971
Fold 2 IBS: 0.2827387812733881
Fold 3 IBS: 0.2057563705865248
Fold 4 IBS: 0.14187407016423445
Fold 5 IBS: 0.3281838295441446
[I 2024-04-14 01:13:52,262] Trial 51 finished with value: 0.21926036025151782 and parameters: {'subsample': 0.7014227085546867, 'dropout_rate': 0.5716067910794211, 'n_estimators': 132, 'learning_rate': 0.08717719986766616}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16208294788973826
Fold 2 IBS: 0.2325171428716414
Fold 3 IBS: 0.18625250438514998
Fold 4 IBS: 0.1732364197119983
Fold 5 IBS: 0.2538056183411742
[I 2024-04-14 01:13:53,561] Trial 52 finished with value: 0.20157892663994045 and parameters: {'subsample': 0.7478298739556589, 'dropout_rate': 0.4621891424903025, 'n_estimators': 65, 'learning_rate': 0.06739381621715893}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.15268073722321815
Fold 2 IBS: 0.24409062439504725
Fold 3 IBS: 0.18732445176431886
Fold 4 IBS: 0.1607619132622868
Fold 5 IBS: 0.27028833843050176
[I 2024-04-14 01:13:55,634] Trial 53 finished with value: 0.2030292130150746 and parameters: {'subsample': 0.66646531802325, 'dropout_rate': 0.3634994459725326, 'n_estimators': 106, 'learning_rate': 0.054646518470296224}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.17587498138103635
Fold 2 IBS: 0.2240625943333213
Fold 3 IBS: 0.18794508828491566
Fold 4 IBS: 0.18550561487084555
Fold 5 IBS: 0.23742192972000833
[I 2024-04-14 01:13:57,375] Trial 54 finished with value: 0.20216204171802543 and parameters: {'subsample': 0.8467773415996864, 'dropout_rate': 0.4291755471093362, 'n_estimators': 88, 'learning_rate': 0.03364188089421907}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.19053558794780692
Fold 2 IBS: 0.22002627948888553
Fold 3 IBS: 0.19332431244134127
Fold 4 IBS: 0.20139459143385668
Fold 5 IBS: 0.22614046506771307
[I 2024-04-14 01:13:58,282] Trial 55 finished with value: 0.20628424727592068 and parameters: {'subsample': 0.6409798018149724, 'dropout_rate': 0.6295197665368938, 'n_estimators': 38, 'learning_rate': 0.04320926081938297}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.14391253951649044
Fold 2 IBS: 0.30420993440578653
Fold 3 IBS: 0.22262987619097205
Fold 4 IBS: 0.14260803736940006
Fold 5 IBS: 0.35813620802252366
[I 2024-04-14 01:14:12,077] Trial 56 finished with value: 0.23429931910103458 and parameters: {'subsample': 0.8801201864628442, 'dropout_rate': 0.5194091093440398, 'n_estimators': 413, 'learning_rate': 0.07802142536761321}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16549026630324634
Fold 2 IBS: 0.282635792998726
Fold 3 IBS: 0.1900668352724054

Fold 4 IBS: 0.1421765996020749
Fold 5 IBS: 0.3198842216652
[I 2024-04-14 01:14:15,476] Trial 57 finished with value: 0.22005074316833056 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.31377442599984917, 'n_estimators': 151, 'learning_rate': 0.07355231920702918}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16761507596154626
Fold 2 IBS: 0.22803850923004326
Fold 3 IBS: 0.18654619322633878
Fold 4 IBS: 0.17717309570614478
Fold 5 IBS: 0.24622975248472237
[I 2024-04-14 01:14:17,738] Trial 58 finished with value: 0.2011205253217591 and parameters: {'subsample': 0.7705771626423796, 'dropout_rate': 0.7021812895625077, 'n_estimators': 122, 'learning_rate': 0.030622252622745642}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.18874788007962418
Fold 2 IBS: 0.2204792981603036
Fold 3 IBS: 0.19149147767111682
Fold 4 IBS: 0.19700150139666606
Fold 5 IBS: 0.22773666772180465
[I 2024-04-14 01:14:19,978] Trial 59 finished with value: 0.20509136500590305 and parameters: {'subsample': 0.5832099136427427, 'dropout_rate': 0.7098329901709999, 'n_estimators': 119, 'learning_rate': 0.016117457997491584}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1544332084826306
Fold 2 IBS: 0.23983738674093083
Fold 3 IBS: 0.18724145935836845
Fold 4 IBS: 0.16321840938501875
Fold 5 IBS: 0.2675399959340056
[I 2024-04-14 01:14:23,609] Trial 60 finished with value: 0.20245409198019085 and parameters: {'subsample': 0.7735647877207805, 'dropout_rate': 0.6631865180753896, 'n_estimators': 173, 'learning_rate': 0.03136696153263342}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.18192212598955654
Fold 2 IBS: 0.2216757634047317
Fold 3 IBS: 0.18994749699038788
Fold 4 IBS: 0.1925971378848909
Fold 5 IBS: 0.23231620222735208
[I 2024-04-14 01:14:24,967] Trial 61 finished with value: 0.20369174529938383 and parameters: {'subsample': 0.8141798696767119, 'dropout_rate': 0.5762031182954477, 'n_estimators': 60, 'learning_rate': 0.03913497127451206}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.15068904155183835
Fold 2 IBS: 0.24390870410842064
Fold 3 IBS: 0.18751399278775827
Fold 4 IBS: 0.16068936811570103
Fold 5 IBS: 0.27193911928885506
[I 2024-04-14 01:14:27,202] Trial 62 finished with value: 0.20294804517051465 and parameters: {'subsample': 0.7124033087922015, 'dropout_rate': 0.4635248508216416, 'n_estimators': 101, 'learning_rate': 0.057814011563862636}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.168556159863205
Fold 2 IBS: 0.22821295315264895
Fold 3 IBS: 0.18663789928446198
Fold 4 IBS: 0.1777715809267387
Fold 5 IBS: 0.24538955371494278
[I 2024-04-14 01:14:28,748] Trial 63 finished with value: 0.20131362938839947 and parameters: {'subsample': 0.803898395893133, 'dropout_rate': 0.48223671722271, 'n_estimators': 81, 'learning_rate': 0.0456163735495518}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.19810433637044436
Fold 2 IBS: 0.2197434951904078
Fold 3 IBS: 0.19630982238159156
Fold 4 IBS: 0.20871800031231413
Fold 5 IBS: 0.22254001059106832
[I 2024-04-14 01:14:29,787] Trial 64 finished with value: 0.20908313296916523 and parameters: {'subsample': 0.9499086639300935, 'dropout_rate': 0.532203111503653, 'n_estimators': 49, 'learning_rate': 0.022567582037908037}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16085578496098304
Fold 2 IBS: 0.23336726580877343
Fold 3 IBS: 0.1862496247988525
Fold 4 IBS: 0.17093051895688843
Fold 5 IBS: 0.25513209007316534
[I 2024-04-14 01:14:32,277] Trial 65 finished with value: 0.20130705691973252 and parameters: {'subsample': 0.7434703306222025, 'dropout_rate': 0.48938727226960727, 'n_estimators': 130, 'learning_rate': 0.03448632279548679}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.19851320343274376
Fold 2 IBS: 0.21976018766442462
Fold 3 IBS: 0.19663207717094555
Fold 4 IBS: 0.20957065893522536
Fold 5 IBS: 0.22228319280667425
[I 2024-04-14 01:14:33,012] Trial 66 finished with value: 0.20935186400200267 and parameters: {'subsample': 0.6345137728268424, 'dropout_rate': 0.5672570194955179, 'n_estimators': 23, 'learning_rate': 0.045530402930866645}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.18253619523286205
Fold 2 IBS: 0.2219444431900099
Fold 3 IBS: 0.1892433698811531
Fold 4 IBS: 0.1910907065953441
Fold 5 IBS: 0.2323773776548699
[I 2024-04-14 01:14:34,295] Trial 67 finished with value: 0.20343841851084782 and parameters: {'subsample': 0.4590303067651391, 'dropout_rate': 0.7338041316434949, 'n_estimators': 70, 'learning_rate': 0.03483181825791068}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1512415608800716
Fold 2 IBS: 0.24498276016435708
Fold 3 IBS: 0.18783969050638616
Fold 4 IBS: 0.15979912782624486
Fold 5 IBS: 0.2739888467950027
[I 2024-04-14 01:14:37,369] Trial 68 finished with value: 0.2035703972344125 and parameters: {'subsample': 0.7280135966760624, 'dropout_rate': 0.48729893794446527, 'n_estimators': 145, 'learning_rate': 0.04117388104963941}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.17083558107196695
Fold 2 IBS: 0.2260786802928645
Fold 3 IBS: 0.18698552751016906
Fold 4 IBS: 0.1803091079233965
Fold 5 IBS: 0.24269722688139958
[I 2024-04-14 01:14:39,556] Trial 69 finished with value: 0.2013812247359593 and parameters: {'subsample': 0.7783880767077602, 'dropout_rate': 0.6106185214223814, 'n_estimators': 119, 'learning_rate': 0.028660354502669412}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16483243378109536
Fold 2 IBS: 0.2306551714167766
Fold 3 IBS: 0.186333120766662
Fold 4 IBS: 0.17439231183235573
Fold 5 IBS: 0.24990459541638063
[I 2024-04-14 01:14:41,028] Trial 70 finished with value: 0.20122352664265403 and parameters: {'subsample': 0.7969973570011311, 'dropout_rate': 0.48141815115351416, 'n_estimators': 79, 'learning_rate': 0.05143682127042862}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16399822994351862
Fold 2 IBS: 0.23068812791223436
Fold 3 IBS: 0.18625926843362128
Fold 4 IBS: 0.17377771234226114
Fold 5 IBS: 0.25085359867548696
[I 2024-04-14 01:14:42,626] Trial 71 finished with value: 0.2011153874614245 and parameters: {'subsample': 0.7447303242619038, 'dropout_rate': 0.5085920554738735, 'n_estimators': 79, 'learning_rate': 0.05214224377442288}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1892900989065118
Fold 2 IBS: 0.22030474580895767
Fold 3 IBS: 0.19221756106781349
Fold 4 IBS: 0.19954738547341908
Fold 5 IBS: 0.22739481962345173
[I 2024-04-14 01:14:43,626] Trial 72 finished with value: 0.20575092217603075 and parameters: {'subsample': 0.6988484662492458, 'dropout_rate': 0.508891161378661, 'n_estimators': 48, 'learning_rate': 0.03755159106192801}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.14888145093947594
Fold 2 IBS: 0.24926903619225996
Fold 3 IBS: 0.18868543863879342
Fold 4 IBS: 0.15668274501126508
Fold 5 IBS: 0.27924118831870437
[I 2024-04-14 01:14:46,117] Trial 73 finished with value: 0.2045519718200998 and parameters: {'subsample': 0.6639705847965011, 'dropout_rate': 0.44723202055865025, 'n_estimators': 129, 'learning_rate': 0.050188058919262146}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.15683258426667127
Fold 2 IBS: 0.2374851141268117
Fold 3 IBS: 0.186741527605273
Fold 4 IBS: 0.16578832723475992
Fold 5 IBS: 0.2619839916868268
[I 2024-04-14 01:14:47,968] Trial 74 finished with value: 0.20176630898406853 and parameters: {'subsample': 0.7516038068119112, 'dropout_rate': 0.5566637714392022, 'n_estimators': 97, 'learning_rate': 0.05219909903169964}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.2016842801877615
Fold 2 IBS: 0.21986977666488458
Fold 3 IBS: 0.1977929299855055
Fold 4 IBS: 0.21156501607675066
Fold 5 IBS: 0.22129951058806957
[I 2024-04-14 01:14:48,638] Trial 75 finished with value: 0.21044230270059433 and parameters: {'subsample': 0.786107526545733, 'dropout_rate': 0.5903412208687462, 'n_estimators': 20, 'learning_rate': 0.04250423885955213}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.18396524790087113
Fold 2 IBS: 0.22122566930630402
Fold 3 IBS: 0.19025617116284751
Fold 4 IBS: 0.19401851757090655

Fold 5 IBS: 0.23080668782285596
[I 2024-04-14 01:14:50,020] Trial 76 finished with value: 0.20405445875275702 and parameters: {'subsample': 0.729382594130491, 'dropout_rate': 0.6783619617211385, 'n_estimators': 72, 'learning_rate': 0.03086841519700664}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16539769706536414
Fold 2 IBS: 0.22990940170380345
Fold 3 IBS: 0.18631811547303107
Fold 4 IBS: 0.17398371273466193
Fold 5 IBS: 0.25027000215867606
[I 2024-04-14 01:14:53,233] Trial 77 finished with value: 0.20117578582710735 and parameters: {'subsample': 0.8562487404883022, 'dropout_rate': 0.5355841488171579, 'n_estimators': 158, 'learning_rate': 0.025512570062193523}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1861460260765977
Fold 2 IBS: 0.2207349422884218
Fold 3 IBS: 0.19116024662320327
Fold 4 IBS: 0.19638098197841433
Fold 5 IBS: 0.22916888150998138
[I 2024-04-14 01:14:55,139] Trial 78 finished with value: 0.20471821569532372 and parameters: {'subsample': 0.8851960834851209, 'dropout_rate': 0.5403585768200623, 'n_estimators': 105, 'learning_rate': 0.01933290827558868}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.15967372392517742
Fold 2 IBS: 0.23406467200997452
Fold 3 IBS: 0.18631482368638058
Fold 4 IBS: 0.16937838851123344
Fold 5 IBS: 0.2581569756807167
[I 2024-04-14 01:14:56,585] Trial 79 finished with value: 0.20151771676269653 and parameters: {'subsample': 0.8593117731764272, 'dropout_rate': 0.7502049800791075, 'n_estimators': 79, 'learning_rate': 0.058432439419619654}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.19320254923919472
Fold 2 IBS: 0.21986057385351387
Fold 3 IBS: 0.19388531512577065
Fold 4 IBS: 0.20344813710493262
Fold 5 IBS: 0.22490855813002195
[I 2024-04-14 01:15:01,456] Trial 80 finished with value: 0.20706102669068677 and parameters: {'subsample': 0.8321289633684164, 'dropout_rate': 0.6447475810931549, 'n_estimators': 210, 'learning_rate': 0.007039353779474462}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.14373287786553807
Fold 2 IBS: 0.25776385628357457
Fold 3 IBS: 0.1929458971287221
Fold 4 IBS: 0.15080637465297117
Fold 5 IBS: 0.29430426986462854
[I 2024-04-14 01:15:04,784] Trial 81 finished with value: 0.20791065515908688 and parameters: {'subsample': 0.7699249172096021, 'dropout_rate': 0.5000109383270173, 'n_estimators': 163, 'learning_rate': 0.04694904098964455}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.162665800484408
Fold 2 IBS: 0.2320309314767097
Fold 3 IBS: 0.18628174870106531
Fold 4 IBS: 0.17229156718668034
Fold 5 IBS: 0.25244761019282547
[I 2024-04-14 01:15:07,257] Trial 82 finished with value: 0.20114353160833778 and parameters: {'subsample': 0.7022751515685015, 'dropout_rate': 0.47301232718792496, 'n_estimators': 128, 'learning_rate': 0.03346903274191958}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.17062990724294125
Fold 2 IBS: 0.22639816379710467
Fold 3 IBS: 0.1872538696944803
Fold 4 IBS: 0.1809531588077867
Fold 5 IBS: 0.24178768077620005
[I 2024-04-14 01:15:08,943] Trial 83 finished with value: 0.2014045560637026 and parameters: {'subsample': 0.6961612462666181, 'dropout_rate': 0.44328782628766306, 'n_estimators': 90, 'learning_rate': 0.03759310893284394}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16795499657627916
Fold 2 IBS: 0.22837624916738145
Fold 3 IBS: 0.18661627616075877
Fold 4 IBS: 0.17737622683631954
Fold 5 IBS: 0.2463536765448201
[I 2024-04-14 01:15:12,461] Trial 84 finished with value: 0.2013354850571118 and parameters: {'subsample': 0.8039475864187848, 'dropout_rate': 0.4133563870225232, 'n_estimators': 153, 'learning_rate': 0.024468290299619975}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.17367169831784776
Fold 2 IBS: 0.22484950210488763
Fold 3 IBS: 0.18743202999336644
Fold 4 IBS: 0.18356739741840375
Fold 5 IBS: 0.2395611547488839
[I 2024-04-14 01:15:14,731] Trial 85 finished with value: 0.2018163565166779 and parameters: {'subsample': 0.7102049184162177, 'dropout_rate': 0.5205680937652518, 'n_estimators': 114, 'learning_rate': 0.0277016386235217}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.17010861597659233
Fold 2 IBS: 0.22727385379732032
Fold 3 IBS: 0.18699156682511184
Fold 4 IBS: 0.18009920929069004
Fold 5 IBS: 0.24440510322573222
[I 2024-04-14 01:15:15,996] Trial 86 finished with value: 0.20177566982308934 and parameters: {'subsample': 0.6377165722098733, 'dropout_rate': 0.47460415491444974, 'n_estimators': 56, 'learning_rate': 0.06343657533600369}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.13990395727578273
Fold 2 IBS: 0.3036847700938676
Fold 3 IBS: 0.22195169439979642
Fold 4 IBS: 0.1421267261445425
Fold 5 IBS: 0.3573212098815924
[I 2024-04-14 01:15:32,835] Trial 87 finished with value: 0.2329976715591163 and parameters: {'subsample': 0.6762394312837521, 'dropout_rate': 0.6208296616071346, 'n_estimators': 472, 'learning_rate': 0.053187494714012046}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1344135754892278
Fold 2 IBS: 0.2966162639387687
Fold 3 IBS: 0.21627396072496255
Fold 4 IBS: 0.1401308922728608
Fold 5 IBS: 0.34666522916026143
[I 2024-04-14 01:15:36,850] Trial 88 finished with value: 0.22681998431721623 and parameters: {'subsample': 0.5876360524403157, 'dropout_rate': 0.5810767025456272, 'n_estimators': 180, 'learning_rate': 0.08802520186596538}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1384482249588335
Fold 2 IBS: 0.2861728280639887
Fold 3 IBS: 0.20778889822540275
Fold 4 IBS: 0.14099706255696665
Fold 5 IBS: 0.3329542860511072
[I 2024-04-14 01:15:42,758] Trial 89 finished with value: 0.2212722599712597 and parameters: {'subsample': 0.8951918863938514, 'dropout_rate': 0.5337091339003963, 'n_estimators': 249, 'learning_rate': 0.04862159870161449}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16674406409411902
Fold 2 IBS: 0.22857071306344007
Fold 3 IBS: 0.18646322079353556
Fold 4 IBS: 0.17622120779486936
Fold 5 IBS: 0.24811401935885388
[I 2024-04-14 01:15:44,569] Trial 90 finished with value: 0.2012226450209636 and parameters: {'subsample': 0.8572796032555069, 'dropout_rate': 0.5557842942221812, 'n_estimators': 98, 'learning_rate': 0.039021149744113484}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16528609648025294
Fold 2 IBS: 0.229446523309139
Fold 3 IBS: 0.1863544544000446
Fold 4 IBS: 0.1746825527795892
Fold 5 IBS: 0.24986269544131315
[I 2024-04-14 01:15:46,413] Trial 91 finished with value: 0.20112646448206778 and parameters: {'subsample': 0.8547962208596521, 'dropout_rate': 0.5580257710018726, 'n_estimators': 100, 'learning_rate': 0.039801300417978705}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16580996719653213
Fold 2 IBS: 0.2290845747218791
Fold 3 IBS: 0.18638254375173025
Fold 4 IBS: 0.17512136208105225
Fold 5 IBS: 0.24930115268738232
[I 2024-04-14 01:15:48,216] Trial 92 finished with value: 0.20113992008771522 and parameters: {'subsample': 0.8458825842332652, 'dropout_rate': 0.5505954897092625, 'n_estimators': 98, 'learning_rate': 0.04007046127999939}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.15786548501772307
Fold 2 IBS: 0.23623602264238094
Fold 3 IBS: 0.18652493582057886
Fold 4 IBS: 0.16683756975111455
Fold 5 IBS: 0.26106056506551784
[I 2024-04-14 01:15:50,951] Trial 93 finished with value: 0.20170491565946302 and parameters: {'subsample': 0.9427888005361366, 'dropout_rate': 0.6925202954825815, 'n_estimators': 136, 'learning_rate': 0.03612268523126554}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16019484511136953
Fold 2 IBS: 0.23329316720562868
Fold 3 IBS: 0.18628574799978684
Fold 4 IBS: 0.16919428667487835
Fold 5 IBS: 0.2566262903076804
[I 2024-04-14 01:15:52,913] Trial 94 finished with value: 0.2011188674598688 and parameters: {'subsample': 0.8254737459684816, 'dropout_rate': 0.5914104836923074, 'n_estimators': 110, 'learning_rate': 0.041423197139738785}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1631510516234425
Fold 2 IBS: 0.2312755243716866
Fold 3 IBS: 0.18625269535369893
Fold 4 IBS: 0.17190748202487674

Fold 5 IBS: 0.2530438768553521
[I 2024-04-14 01:15:55,402] Trial 95 finished with value: 0.2011261260458114 and parameters: {'subsample': 0.8422246435924808, 'dropout_rate': 0.5964014242242069, 'n_estimators': 127, 'learning_rate': 0.03356108802245582}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16833703881776008
Fold 2 IBS: 0.2272152857140041
Fold 3 IBS: 0.1866950376112
Fold 4 IBS: 0.17788130795097382
Fold 5 IBS: 0.24530983172104343
[I 2024-04-14 01:15:57,508] Trial 96 finished with value: 0.20108770036299628 and parameters: {'subsample': 0.8205106604823191, 'dropout_rate': 0.6501086479099357, 'n_estimators': 109, 'learning_rate': 0.03318174004435172}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.16600966254812746
Fold 2 IBS: 0.22917548167323062
Fold 3 IBS: 0.1863906804089131
Fold 4 IBS: 0.17530834913167373
Fold 5 IBS: 0.24859220802093854
[I 2024-04-14 01:15:59,806] Trial 97 finished with value: 0.20109527635657667 and parameters: {'subsample': 0.9784481999742963, 'dropout_rate': 0.6519942420501896, 'n_estimators': 123, 'learning_rate': 0.03184901175247192}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1625562477451101
Fold 2 IBS: 0.23152886361827676
Fold 3 IBS: 0.18624941668699113
Fold 4 IBS: 0.17144785490042433
Fold 5 IBS: 0.25345311597588216
[I 2024-04-14 01:16:02,549] Trial 98 finished with value: 0.2010470997853369 and parameters: {'subsample': 0.8262369367682384, 'dropout_rate': 0.6598313196292284, 'n_estimators': 144, 'learning_rate': 0.029823473458403554}. Best is trial 48 with value: 0.2007926295608577.
Fold 1 IBS: 0.1630298253162209
Fold 2 IBS: 0.23137590481399203
Fold 3 IBS: 0.18625325253439942
Fold 4 IBS: 0.17218424564103743
Fold 5 IBS: 0.2526209571034186
[I 2024-04-14 01:16:05,214] Trial 99 finished with value: 0.2010928370818137 and parameters: {'subsample': 0.9738189736940457, 'dropout_rate': 0.6616361037538174, 'n_estimators': 142, 'learning_rate': 0.029953162092398643}. Best is trial 48 with value: 0.2007926295608577.


* Best trial for IBS:
 FrozenTrial(number=48, state=TrialState.COMPLETE, values=[0.2007926295608577], datetime_start=datetime.datetime(2024, 4, 14, 1, 13, 47, 9242), datetime_complete=datetime.datetime(2024, 4, 14, 1, 13, 48, 109055), params={'subsample': 0.6626333762174762, 'dropout_rate': 0.5685805772015377, 'n_estimators': 55, 'learning_rate': 0.07550425969628831}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=48, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.6626333762174762, 'dropout_rate': 0.5685805772015377, 'n_estimators': 55, 'learning_rate': 0.07550425969628831}


* Best Score for IBS:
 0.2007926295608577

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.751
train_ibs:  0.201

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_OS'], y['OS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
gbsg_times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(gbsg_times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, gbsg_times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.6672299985480628,
                                              learning_rate=0.03906201007616112,
                                              n_estimators=225,
                                              random_state=123,
                                              subsample=0.3385180226064827)

C-index score: 0.663

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5685805772015377,
                                              learning_rate=0.07550425969628831,
                                              n_estimators=55, random_state=123,
                                              subsample=0.6626333762174762)

IBS: 0.207

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [80]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.787   1.0
Randomsurvivalforest             0.774   2.0
CoxElastic                       0.756   3.0
ComponentwiseGradientBoosting    0.751   4.0
GradientBoosting                 0.748   5.0
CoxPH                            0.736   6.5
CoxLasso                         0.736   6.5
CoxRidge                         0.698   8.0

In [81]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.187   1.0
ExtraSurvivalTrees             0.188   2.0
CoxPH                          0.194   4.0
CoxLasso                       0.194   4.0
CoxElastic                     0.194   4.0
ComponentwiseGradientBoosting  0.201   6.0
GradientBoosting               0.216   7.0
CoxRidge                       0.217   8.0

In [82]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.676   1.0
ExtraSurvivalTrees               0.673   2.0
Randomsurvivalforest             0.669   3.0
ComponentwiseGradientBoosting    0.663   4.0
CoxLasso                         0.624   5.0
CoxPH                            0.623   6.0
CoxRidge                         0.589   7.5
CoxElastic                       0.589   7.5

In [83]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.203   1.0
ComponentwiseGradientBoosting  0.207   2.0
Randomsurvivalforest           0.210   3.0
GradientBoosting               0.220   4.0
CoxRidge                       0.221   5.0
CoxLasso                       0.232   6.5
CoxElastic                     0.232   6.5
CoxPH                          0.234   8.0

In [84]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = 'path_to_your_folder/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d1/os/minmax/plsr/'  

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d1_os_minmax_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [85]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14