In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from lifelines import CoxPHFitter
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
response_OUS.isna().sum().sum()

0

In [4]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [5]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [6]:
# Check null values in D3
clinical_train.isnull().sum().sum()

0

In [7]:
clinical_train

,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,pack_years,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,event_DFS
0,54.238356,1,0,1,0,0,1,0.0,0,0.000000,...,0.029974,0.815962,0.000000,0.002035,0.140311,0.000062,0.009991,0.000370,32.909589,0
1,54.539726,0,0,0,0,1,0,0.0,1,27.404795,...,0.059728,0.707300,0.000000,0.008732,0.191058,0.000349,0.023402,0.000699,27.715068,0
2,59.019178,0,1,0,0,0,1,0.0,1,41.019178,...,0.039463,0.819828,0.000034,0.002518,0.126531,0.000000,0.009452,0.000414,43.101370,1
3,70.726027,0,0,0,0,1,0,0.0,1,37.500000,...,0.061133,0.716212,0.000000,0.003296,0.192388,0.000000,0.018879,0.000899,17.589041,1
4,67.865753,0,0,0,0,1,0,0.0,1,53.000000,...,0.058589,0.696493,0.000199,0.008968,0.202073,0.000399,0.029892,0.001395,47.473973,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134,60.435616,0,0,1,0,0,1,1.0,0,0.000000,...,0.029444,0.804831,0.000000,0.001442,0.152626,0.000000,0.009734,0.000361,41.490411,0
135,68.794521,0,0,1,0,0,1,1.0,0,0.000000,...,0.046451,0.792151,0.000000,0.004094,0.142778,0.000079,0.011810,0.000630,36.821918,0
136,57.498630,0,0,1,0,0,1,1.0,1,39.498630,...,0.016316,0.832202,0.000000,0.000914,0.140582,0.000000,0.009137,0.000522,40.043836,0
137,65.684932,0,0,1,0,0,1,1.0,1,71.527397,...,0.038862,0.787588,0.000000,0.003144,0.156640,0.000054,0.011978,0.000705,40.964384,0
138,61.676712,0,0,1,0,0,1,1.0,0,2.250000,...,0.011577,0.830670,0.000000,0.000978,0.147644,0.000000,0.008642,0.000408,30.608219,0

## Test dataset: MAASTRO

In [8]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [9]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [10]:
rows_with_nan = response_MAASTRO[response_MAASTRO.isna().any(axis=1)]

print("Rows with NaN values:")
print(rows_with_nan)

Rows with NaN values:
    patient_id  OS  OS_event  LRC  LRC_event  DFS  DFS_event
10          11 NaN       NaN  NaN        NaN  NaN        NaN
20          21 NaN       NaN  NaN        NaN  NaN        NaN
31          32 NaN       NaN  NaN        NaN  NaN        NaN
51          52 NaN       NaN  NaN        NaN  NaN        NaN
83          84 NaN       NaN  NaN        NaN  NaN        NaN
86          87 NaN       NaN  NaN        NaN  NaN        NaN

In [11]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

In [12]:
MAASTRO_D3

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_003_PET,LBP_012_PET,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET
0,1,55,0,0,1,0,0,1,1,1,...,0.000026,0.001181,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341
1,2,55,0,0,1,0,0,0,0,0,...,0.000056,0.002735,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335
2,3,55,0,0,1,0,0,0,0,1,...,0.000286,0.001888,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229
3,4,61,1,0,0,0,1,1,0,1,...,0.000160,0.003037,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240
4,6,70,0,0,1,0,0,1,1,1,...,0.000071,0.000881,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.000000,0.000544,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078
95,111,63,0,0,0,0,1,0,0,1,...,0.000109,0.000869,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489
96,112,63,0,0,1,0,0,1,1,1,...,0.000000,0.000734,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141
97,113,54,0,0,1,0,0,1,1,0,...,0.000114,0.001640,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038
98,114,62,0,0,0,1,0,1,0,0,...,0.000000,0.000225,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337

In [13]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(MAASTRO_D3['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: [5, 9, 11, 21, 32, 36, 46, 52, 65, 76, 78, 81, 84, 87, 92]

In [14]:
# Assuming your data is stored in a list or a pandas DataFrame/Series
# Convert data to a set for faster membership checking
data_set = set(list(response_MAASTRO['patient_id']))

# Find numbers from 1 to 114 not present in data
missing_numbers = set(range(1, 115)) - data_set

# Convert missing_numbers back to a sorted list
missing_numbers_list = sorted(missing_numbers)

print("Numbers from 1 to 114 not present in data:", missing_numbers_list)

Numbers from 1 to 114 not present in data: []

In [15]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [16]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [17]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [18]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [19]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [20]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 388)
y_train:  (139,)

(99, 390)

# Feature Selection: RENT

In [21]:
selected_features = [
"shape_Sphericity",
"hpv_related",
"glszm_SmallAreaLowGrayLevelEmphasis_CT_c16",
"LBP_102_PET",
"shape_Flatness",
"shape_Elongation",
"uicc8_III-IV",
"shape_MajorAxisLength",
"glrlm_HighGrayLevelRunEmphasis_PET_c04"]

# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [22]:
original_X = X.copy()

In [23]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [24]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [25]:
X_new

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.761164,0.0,0.029425,0.000000,0.535140,0.600926,0.0,42.073251,16.969770
1,0.697049,0.0,0.037915,0.000000,0.367109,0.841579,0.0,24.613845,15.598394
2,0.565792,0.0,0.008009,0.000034,0.597785,0.772821,1.0,48.030294,17.334294
3,0.684364,0.0,0.018398,0.000000,0.405730,0.847727,0.0,25.589900,14.009277
4,0.503142,0.0,0.013051,0.000199,0.442406,0.831483,0.0,34.684750,21.202180
...,...,...,...,...,...,...,...,...,...
134,0.742102,1.0,0.014938,0.000000,0.523608,0.680294,0.0,33.069705,16.110383
135,0.722918,1.0,0.011441,0.000000,0.735524,0.758193,1.0,41.043692,21.249575
136,0.652963,1.0,0.020431,0.000000,0.648063,0.770113,0.0,36.618802,14.873884
137,0.724255,1.0,0.019663,0.000000,0.492193,0.628897,1.0,45.870392,21.648860
138,0.722633,1.0,0.013864,0.000000,0.756267,0.892637,1.0,30.363259,20.191288

In [26]:
X_new_std

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.828413,0.0,0.603741,0.000000,0.499075,0.461898,0.0,0.350904,0.487448
1,0.645006,0.0,0.800232,0.000000,0.220565,0.829873,0.0,0.123069,0.388474
2,0.269537,0.0,0.108112,0.066875,0.602909,0.724738,1.0,0.428640,0.513756
3,0.608721,0.0,0.348551,0.000000,0.284579,0.839273,0.0,0.135806,0.273786
4,0.090323,0.0,0.224799,0.386334,0.345369,0.814436,0.0,0.254489,0.792905
...,...,...,...,...,...,...,...,...,...
134,0.773882,1.0,0.268474,0.000000,0.479962,0.583257,0.0,0.233413,0.425425
135,0.719008,1.0,0.187545,0.000000,0.831212,0.702369,1.0,0.337469,0.796326
136,0.518897,1.0,0.395599,0.000000,0.686245,0.720597,0.0,0.279727,0.336186
137,0.722831,1.0,0.377829,0.000000,0.427891,0.504667,1.0,0.400455,0.825142
138,0.718191,1.0,0.243616,0.000000,0.865592,0.907943,1.0,0.198096,0.719948

In [27]:
MAASTRO_new

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.668072,1,0.010495,0.000026,0.610062,0.765178,0,50.002093,19.034156
1,0.669961,0,0.035018,0.000167,0.504616,0.776540,1,41.753334,11.392444
2,0.624081,0,0.012819,0.000057,0.478604,0.697164,1,44.375483,14.567421
3,0.577624,0,0.029974,0.000000,0.446059,0.574636,1,46.115989,13.477331
4,0.630933,1,0.013458,0.000000,0.480378,0.633419,0,54.394967,16.365554
...,...,...,...,...,...,...,...,...,...
94,0.671754,0,0.039092,0.000000,0.577884,0.882411,1,34.218615,17.492295
95,0.632189,0,0.015831,0.000000,0.455642,0.535802,1,51.046869,14.267900
96,0.645548,1,0.011031,0.000000,0.631485,0.716610,1,50.417953,12.143752
97,0.727488,1,0.019801,0.000000,0.628338,0.665145,0,44.901412,15.300229
98,0.672838,0,0.015813,0.000000,0.469139,0.616262,1,36.574294,13.850774

In [28]:
MAASTRO_new_std

,shape_Sphericity,hpv_related,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,LBP_102_PET,shape_Flatness,shape_Elongation,uicc8_III-IV,shape_MajorAxisLength,glrlm_HighGrayLevelRunEmphasis_PET_c04
0,0.562115,1,0.165637,0.050863,0.623259,0.713050,0,0.454371,0.636436
1,0.567520,0,0.733175,0.324583,0.448482,0.730423,1,0.346729,0.084927
2,0.436277,0,0.219419,0.110937,0.405367,0.609052,1,0.380947,0.314068
3,0.303383,0,0.616439,0.000000,0.351425,0.421699,1,0.403660,0.235395
4,0.455879,1,0.234227,0.000000,0.408308,0.511582,0,0.511695,0.443841
...,...,...,...,...,...,...,...,...,...
94,0.572648,0,0.827475,0.000000,0.569924,0.892307,1,0.248406,0.525159
95,0.459472,0,0.289124,0.000000,0.367308,0.362320,1,0.468005,0.292451
96,0.497683,1,0.178051,0.000000,0.658767,0.638788,1,0.459798,0.139149
97,0.732079,1,0.381019,0.000000,0.653551,0.560093,0,0.387810,0.366955
98,0.575748,0,0.288721,0.000000,0.389679,0.485348,1,0.279146,0.262347

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [29]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:53,104] A new study created in memory with name: no-name-ed345adf-2205-4f40-a7c3-c47a1a3d9332

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-22 02:38:56,766] A new study created in memory with name: no-name-98b273a9-7a36-431d-9bcf-86a447be6a84

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:38:56,758] Trial 0 finished with value: 0.72444161978659 and parameters: {}. Best is trial 0 with value: 0.72444161978659.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.72444161978659], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 53, 181181), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 56, 758351), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.72444161978659

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.22218111763385023
Fold 2 IBS: 0.18214519470787685
Fold 3 IBS: 0.1994305821578018
Fold 4 IBS: 0.22498818963412248
Fold 5 IBS: 0.17079109178266774
[I 2024-04-22 02:38:57,131] Trial 0 finished with value: 0.1999072351832638 and parameters: {}. Best is trial 0 with value: 0.1999072351832638.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.1999072351832638], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 56, 808134), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 57, 130720), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.1999072351832638

In [30]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.724
train_ibs:  0.2

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.562
IBS score: 0.29

In [34]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [35]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [36]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:57,358] A new study created in memory with name: no-name-9773edf1-167d-451c-bbc3-412a008d4181

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217

[I 2024-04-22 02:38:57,531] A new study created in memory with name: no-name-e2f27a0f-8a8d-4f8a-9c8a-2b42332030d3

Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6223175965665236
[I 2024-04-22 02:38:57,524] Trial 0 finished with value: 0.6530227012960098 and parameters: {}. Best is trial 0 with value: 0.6530227012960098.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6530227012960098], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 57, 402314), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 57, 524539), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6530227012960098

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709740463627
Fold 2 IBS: 0.23203988107242277
Fold 3 IBS: 0.22898186333477166
Fold 4 IBS: 0.2419747676475077
Fold 5 IBS: 0.22939558866148296
[I 2024-04-22 02:38:57,751] Trial 0 finished with value: 0.23592783962416428 and parameters: {}. Best is trial 0 with value: 0.23592783962416428.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783962416428], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 57, 579763), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 57, 751350), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783962416428

In [37]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [38]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.653
train_ibs:  0.236

#### Test

In [39]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [40]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.601

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [41]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [42]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:57,929] A new study created in memory with name: no-name-8f0fc7ce-61ba-49e3-a91f-a928addb57be

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012

[I 2024-04-22 02:38:58,282] A new study created in memory with name: no-name-3002d24d-1896-4a1d-8431-39c1d6f1f536

Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:38:58,276] Trial 0 finished with value: 0.7238034285261303 and parameters: {}. Best is trial 0 with value: 0.7238034285261303.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.7238034285261303], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 57, 974820), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 58, 275988), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.7238034285261303

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.22182980078916964
Fold 2 IBS: 0.18172701387753668
Fold 3 IBS: 0.19797885012791275
Fold 4 IBS: 0.22438073478490372
Fold 5 IBS: 0.16966690546615495
[I 2024-04-22 02:38:58,587] Trial 0 finished with value: 0.19911666100913555 and parameters: {}. Best is trial 0 with value: 0.19911666100913555.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.19911666100913555], datetime_start=datetime.datetime(2024, 4, 22, 2, 38, 58, 313049), datetime_complete=datetime.datetime(2024, 4, 22, 2, 38, 58, 587697), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.19911666100913555

In [43]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [44]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.724
train_ibs:  0.199

#### Test

In [45]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [46]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.566

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.287

In [47]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [48]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:38:58,837] A new study created in memory with name: no-name-c8c69432-4504-4842-9a44-fec0d6aa6bd5

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:59,161] Trial 0 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:59,478] Trial 1 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:38:59,788] Trial 2 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:00,061] Trial 3 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:00,446] Trial 4 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:00,807] Trial 5 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:39:01,238] Trial 6 finished with value: 0.7238034285261303 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:01,604] Trial 7 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:01,968] Trial 8 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:02,566] Trial 9 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:39:03,016] Trial 10 finished with value: 0.7238034285261303 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:03,198] Trial 11 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.046971505265140434}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:03,686] Trial 12 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.6978253640763652}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:04,115] Trial 13 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.6189362712539238}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:04,571] Trial 14 finished with value: 0.7238649848758387 and parameters: {'l1_ratio': 0.8403787283021946}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:05,065] Trial 15 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.5892251114089379}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:05,497] Trial 16 finished with value: 0.7238649848758387 and parameters: {'l1_ratio': 0.8361111870922124}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:05,826] Trial 17 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.5632480038685016}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:06,138] Trial 18 finished with value: 0.7238649848758387 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:06,496] Trial 19 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.2466600496841937}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:06,672] Trial 20 finished with value: 0.6565775804916735 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:07,001] Trial 21 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.4402486352922271}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:07,369] Trial 22 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.36556027214152725}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:07,699] Trial 23 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.48118495682295287}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682

Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:08,020] Trial 24 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.5495622575930152}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:08,568] Trial 25 finished with value: 0.7246944297550717 and parameters: {'l1_ratio': 0.33805515463738495}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:08,944] Trial 26 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.7685574200470692}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:09,296] Trial 27 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.6291683679809102}. Best is trial 0 with value: 0.7254912425040756.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:09,621] Trial 28 finished with value: 0.7330928415463667 and parameters: {'l1_ratio': 0.1636708494922895}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:09,736] Trial 29 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.0995431913123267}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:10,242] Trial 30 finished with value: 0.7246364543292776 and parameters: {'l1_ratio': 0.19751100862494347}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:10,673] Trial 31 finished with value: 0.7262516987778399 and parameters: {'l1_ratio': 0.3013220087820099}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:11,146] Trial 32 finished with value: 0.7254548860288359 and parameters: {'l1_ratio': 0.3034452278173332}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:11,623] Trial 33 finished with value: 0.7246364543292776 and parameters: {'l1_ratio': 0.20036345185401683}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:11,804] Trial 34 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.0037772681753269755}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:12,108] Trial 35 finished with value: 0.6845361325495365 and parameters: {'l1_ratio': 0.1402297001974694}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:12,658] Trial 36 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.26823617230428015}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:13,245] Trial 37 finished with value: 0.7238649848758387 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:13,741] Trial 38 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.531399063056916}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:14,468] Trial 39 finished with value: 0.7246401786742884 and parameters: {'l1_ratio': 0.6774232326381104}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:14,943] Trial 40 finished with value: 0.7262516987778399 and parameters: {'l1_ratio': 0.43272387245989113}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:15,295] Trial 41 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.44809118075651944}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:15,681] Trial 42 finished with value: 0.7262516987778399 and parameters: {'l1_ratio': 0.32514085116185026}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:16,030] Trial 43 finished with value: 0.7262516987778399 and parameters: {'l1_ratio': 0.30017568253386157}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:16,394] Trial 44 finished with value: 0.7254548860288359 and parameters: {'l1_ratio': 0.31564413335916247}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:16,722] Trial 45 finished with value: 0.7254912425040756 and parameters: {'l1_ratio': 0.38751989022762734}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:17,026] Trial 46 finished with value: 0.7315208349989131 and parameters: {'l1_ratio': 0.16932718040441685}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:17,261] Trial 47 finished with value: 0.6845361325495365 and parameters: {'l1_ratio': 0.1426102255542931}. Best is trial 28 with value: 0.7330928415463667.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:17,656] Trial 48 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.2239382246971858}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:17,990] Trial 49 finished with value: 0.7315208349989131 and parameters: {'l1_ratio': 0.1747257685624083}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:18,259] Trial 50 finished with value: 0.7159314813867457 and parameters: {'l1_ratio': 0.15951349428304473}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:18,374] Trial 51 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.05354827362643566}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:18,702] Trial 52 finished with value: 0.7315208349989131 and parameters: {'l1_ratio': 0.18463356129371258}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:19,032] Trial 53 finished with value: 0.7323176477479171 and parameters: {'l1_ratio': 0.1894358595490555}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:19,427] Trial 54 finished with value: 0.7322960287973628 and parameters: {'l1_ratio': 0.1816696689570954}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:19,579] Trial 55 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.09496610583774175}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:20,007] Trial 56 finished with value: 0.7246364543292776 and parameters: {'l1_ratio': 0.19658509654998813}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:20,616] Trial 57 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.24964764165777947}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:20,792] Trial 58 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.052159363014773696}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:21,523] Trial 59 finished with value: 0.7322960287973628 and parameters: {'l1_ratio': 0.16680381722198787}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:21,656] Trial 60 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.006546243132476953}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:22,073] Trial 61 finished with value: 0.7322960287973628 and parameters: {'l1_ratio': 0.16579087773070636}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:22,270] Trial 62 finished with value: 0.6557807677426695 and parameters: {'l1_ratio': 0.1203600773703585}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:22,394] Trial 63 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.07882737662973964}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:22,678] Trial 64 finished with value: 0.7159314813867457 and parameters: {'l1_ratio': 0.15481391393252067}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:23,054] Trial 65 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.23925055093537484}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:23,421] Trial 66 finished with value: 0.7323176477479171 and parameters: {'l1_ratio': 0.1757957919422961}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:23,834] Trial 67 finished with value: 0.7254548860288359 and parameters: {'l1_ratio': 0.27241273361339335}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:24,261] Trial 68 finished with value: 0.723861260530828 and parameters: {'l1_ratio': 0.2140014934809695}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:24,456] Trial 69 finished with value: 0.6557807677426695 and parameters: {'l1_ratio': 0.12725753584891777}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:24,573] Trial 70 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.07185690172647319}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225

Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:24,922] Trial 71 finished with value: 0.7315208349989131 and parameters: {'l1_ratio': 0.17339724305353524}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:25,266] Trial 72 finished with value: 0.7323176477479171 and parameters: {'l1_ratio': 0.17600305871028435}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:25,457] Trial 73 finished with value: 0.6557807677426695 and parameters: {'l1_ratio': 0.12420054405329062}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:25,853] Trial 74 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.22762247094267996}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:26,386] Trial 75 finished with value: 0.7262516987778399 and parameters: {'l1_ratio': 0.35329746579561166}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:26,658] Trial 76 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.02587237656256572}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:26,787] Trial 77 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.08761357053409147}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:27,196] Trial 78 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.2707203303739988}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:27,607] Trial 79 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.2033912723130451}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:27,913] Trial 80 finished with value: 0.7159314813867457 and parameters: {'l1_ratio': 0.1590654899082177}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:28,281] Trial 81 finished with value: 0.7315208349989131 and parameters: {'l1_ratio': 0.1739535525870463}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:28,667] Trial 82 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.24829420008335246}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:28,845] Trial 83 finished with value: 0.6565775804916735 and parameters: {'l1_ratio': 0.11291899662372402}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:29,253] Trial 84 finished with value: 0.7322960287973628 and parameters: {'l1_ratio': 0.18180132508578553}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:29,523] Trial 85 finished with value: 0.6845361325495365 and parameters: {'l1_ratio': 0.14335510900069556}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:29,927] Trial 86 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.20387355361581896}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:30,311] Trial 87 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.23117979740937494}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:30,706] Trial 88 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.2834340317509121}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:31,066] Trial 89 finished with value: 0.7330928415463667 and parameters: {'l1_ratio': 0.1782103176095987}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:31,194] Trial 90 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.06726155534329738}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:31,651] Trial 91 finished with value: 0.7322960287973628 and parameters: {'l1_ratio': 0.18090623769679207}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:31,918] Trial 92 finished with value: 0.6845361325495365 and parameters: {'l1_ratio': 0.13996287182215253}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:32,108] Trial 93 finished with value: 0.6565775804916735 and parameters: {'l1_ratio': 0.10820443367955}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:32,607] Trial 94 finished with value: 0.7323176477479171 and parameters: {'l1_ratio': 0.1896963651348531}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877

Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:33,116] Trial 95 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.26128054981013793}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:33,553] Trial 96 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.20329400788731466}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:33,989] Trial 97 finished with value: 0.724658073279832 and parameters: {'l1_ratio': 0.2259025879148066}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 02:39:34,117] Trial 98 finished with value: 0.6525935167466536 and parameters: {'l1_ratio': 0.036027940577462836}. Best is trial 28 with value: 0.7330928415463667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:39:34,443] Trial 99 finished with value: 0.7315208349989131 and parameters: {'l1_ratio': 0.18595134660292403}. Best is trial 28 with value: 0.7330928415463667.

[I 2024-04-22 02:39:34,473] A new study created in memory with name: no-name-b54051da-8594-41e0-a3a3-42e66dc4fa78

* Best trial for C-index:
 FrozenTrial(number=28, state=TrialState.COMPLETE, values=[0.7330928415463667], datetime_start=datetime.datetime(2024, 4, 22, 2, 39, 9, 300866), datetime_complete=datetime.datetime(2024, 4, 22, 2, 39, 9, 620462), params={'l1_ratio': 0.1636708494922895}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=28, value=None)


* Best Score for C-index:
 0.7330928415463667

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2216485391246878
Fold 2 IBS: 0.1814722944718866
Fold 3 IBS: 0.19722326355176195
Fold 4 IBS: 0.2238551998049956
Fold 5 IBS: 0.16941221866693593
[I 2024-04-22 02:39:34,895] Trial 0 finished with value: 0.19872230312405353 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.19872230312405353.
Fold 1 IBS: 0.2214799630998252
Fold 2 IBS: 0.1812532027794153
Fold 3 IBS: 0.1963718639583461
Fold 4 IBS: 0.22347371303049401
Fold 5 IBS: 0.16914589283709572
[I 2024-04-22 02:39:35,513] Trial 1 finished with value: 0.19834492714103527 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.19834492714103527.
Fold 1 IBS: 0.22148633403129092
Fold 2 IBS: 0.18124960491527572
Fold 3 IBS: 0.196373014074587
Fold 4 IBS: 0.22331662163586258
Fold 5 IBS: 0.16917204871328384
[I 2024-04-22 02:39:35,943] Trial 2 finished with value: 0.19831952467406 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.22154376038381082
Fold 2 IBS: 0.1813804523947237
Fold 3 IBS: 0.19697656736268196
Fold 4 IBS: 0.22364580457560346
Fold 5 IBS: 0.16935320324786018
[I 2024-04-22 02:39:36,360] Trial 3 finished with value: 0.19857995759293603 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.2216290996878552
Fold 2 IBS: 0.1815109674569653
Fold 3 IBS: 0.19734371457535335
Fold 4 IBS: 0.22393273028625518
Fold 5 IBS: 0.16947167182573605
[I 2024-04-22 02:39:36,770] Trial 4 finished with value: 0.19877763676643304 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.2215508473838351
Fold 2 IBS: 0.18135687920619384
Fold 3 IBS: 0.19672170971322966
Fold 4 IBS: 0.2235753927238864
Fold 5 IBS: 0.169274562840634
[I 2024-04-22 02:39:37,151] Trial 5 finished with value: 0.1984958783735558 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.22181027711757142
Fold 2 IBS: 0.18173447979339127
Fold 3 IBS: 0.1980303687245911
Fold 4 IBS: 0.22432638597865887
Fold 5 IBS: 0.1696285128322031
[I 2024-04-22 02:39:37,492] Trial 6 finished with value: 0.19910600488928315 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.22163318205310553
Fold 2 IBS: 0.1815061866927254
Fold 3 IBS: 0.197347042572132
Fold 4 IBS: 0.22381430103805833
Fold 5 IBS: 0.1693808275706507
[I 2024-04-22 02:39:37,851] Trial 7 finished with value: 0.19873630798533437 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.22154148145445696
Fold 2 IBS: 0.18135962531872082
Fold 3 IBS: 0.1969312146633505
Fold 4 IBS: 0.22359051173762653
Fold 5 IBS: 0.1692385565728705
[I 2024-04-22 02:39:38,328] Trial 8 finished with value: 0.19853227794940506 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.22148782479782186
Fold 2 IBS: 0.1813471713831689
Fold 3 IBS: 0.19669555199922015
Fold 4 IBS: 0.2235504612686814
Fold 5 IBS: 0.16927493332882682
[I 2024-04-22 02:39:38,808] Trial 9 finished with value: 0.19847118855554383 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.2450226998389924
Fold 2 IBS: 0.22952783257927062
Fold 3 IBS: 0.22550299345196753
Fold 4 IBS: 0.23924320104810504
Fold 5 IBS: 0.2261908267063941
[I 2024-04-22 02:39:38,998] Trial 10 finished with value: 0.23309751072494594 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.22148082034374247
Fold 2 IBS: 0.18123679852642666
Fold 3 IBS: 0.22220818491558111
Fold 4 IBS: 0.22328315641257432
Fold 5 IBS: 0.16916528944963782
[I 2024-04-22 02:39:39,524] Trial 11 finished with value: 0.2034748499295925 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.22149509950847474
Fold 2 IBS: 0.1812595303230507
Fold 3 IBS: 0.19641014521226577
Fold 4 IBS: 0.22333911786350633
Fold 5 IBS: 0.16919080871544814
[I 2024-04-22 02:39:40,060] Trial 12 finished with value: 0.19833894032454913 and parameters: {'l1_ratio': 0.22959915831444896}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.2470717203782721
Fold 2 IBS: 0.23184018137693171
Fold 3 IBS: 0.2287086267296735
Fold 4 IBS: 0.2417553569654654
Fold 5 IBS: 0.22914267666568974
[I 2024-04-22 02:39:40,248] Trial 13 finished with value: 0.23570371242320648 and parameters: {'l1_ratio': 0.0058200831877644466}. Best is trial 2 with value: 0.19831952467406.
Fold 1 IBS: 0.2214708721001901
Fold 2 IBS: 0.18123594172532664
Fold 3 IBS: 0.19631736736351912
Fold 4 IBS: 0.22343241104427736
Fold 5 IBS: 0.16913617538048756
[I 2024-04-22 02:39:40,756] Trial 14 finished with value: 0.19831855352276015 and parameters: {'l1_ratio': 0.24133971598258583}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.2214556563514438
Fold 2 IBS: 0.22815087881223664
Fold 3 IBS: 0.22355276444193126
Fold 4 IBS: 0.2377697848511975
Fold 5 IBS: 0.1691166394427233
[I 2024-04-22 02:39:41,073] Trial 15 finished with value: 0.2160091447799065 and parameters: {'l1_ratio': 0.14279067273393495}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.22149160726326622
Fold 2 IBS: 0.1812711800176932
Fold 3 IBS: 0.19643267362621927
Fold 4 IBS: 0.22337649906369741
Fold 5 IBS: 0.16916633919196183
[I 2024-04-22 02:39:41,579] Trial 16 finished with value: 0.19834765983256758 and parameters: {'l1_ratio': 0.31408489302885545}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.2214792800809482
Fold 2 IBS: 0.18132657467155675
Fold 3 IBS: 0.19663587262433108
Fold 4 IBS: 0.22349897182327655
Fold 5 IBS: 0.16926855954599823
[I 2024-04-22 02:39:42,083] Trial 17 finished with value: 0.19844185174922213 and parameters: {'l1_ratio': 0.3341177174324976}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.24646531118891954
Fold 2 IBS: 0.2311520674100828
Fold 3 IBS: 0.2277632727554444
Fold 4 IBS: 0.24100233339769467
Fold 5 IBS: 0.22826937564798552
[I 2024-04-22 02:39:42,270] Trial 18 finished with value: 0.23493047208002538 and parameters: {'l1_ratio': 0.02687428103103129}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.22159475949626062
Fold 2 IBS: 0.18137433828572405
Fold 3 IBS: 0.19695660688002323
Fold 4 IBS: 0.22363258382609238
Fold 5 IBS: 0.16934327148917844
[I 2024-04-22 02:39:42,713] Trial 19 finished with value: 0.19858031199545575 and parameters: {'l1_ratio': 0.5482362917959815}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.2214347781772534
Fold 2 IBS: 0.2282342895399959
Fold 3 IBS: 0.22367182088668766
Fold 4 IBS: 0.23785862083943543
Fold 5 IBS: 0.1690717462288366
[I 2024-04-22 02:39:43,032] Trial 20 finished with value: 0.2160542511344418 and parameters: {'l1_ratio': 0.13886452843331773}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.2214558481540659
Fold 2 IBS: 0.18128529343344987
Fold 3 IBS: 0.1965060072136093
Fold 4 IBS: 0.22339698070815606
Fold 5 IBS: 0.1692392224658992
[I 2024-04-22 02:39:43,550] Trial 21 finished with value: 0.19837667039503606 and parameters: {'l1_ratio': 0.2367517986971607}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.22150254189070412
Fold 2 IBS: 0.18126798209182943
Fold 3 IBS: 0.19644170978569878
Fold 4 IBS: 0.22335817668889102
Fold 5 IBS: 0.16920675340046812
[I 2024-04-22 02:39:44,050] Trial 22 finished with value: 0.1983554327715183 and parameters: {'l1_ratio': 0.23191244143423032}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.22147205611841816
Fold 2 IBS: 0.2288245470108537
Fold 3 IBS: 0.22451093412501605
Fold 4 IBS: 0.23848876592351348
Fold 5 IBS: 0.22527990221727898
[I 2024-04-22 02:39:44,299] Trial 23 finished with value: 0.22771524107901606 and parameters: {'l1_ratio': 0.1124690541840564}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.22151256773271852
Fold 2 IBS: 0.18130619394382155
Fold 3 IBS: 0.19654713260297121
Fold 4 IBS: 0.2234612593948774
Fold 5 IBS: 0.1692004787085248
[I 2024-04-22 02:39:44,739] Trial 24 finished with value: 0.1984055264765827 and parameters: {'l1_ratio': 0.3752730935447346}. Best is trial 14 with value: 0.19831855352276015.
Fold 1 IBS: 0.2214696212417028

Fold 2 IBS: 0.1812371932325854
Fold 3 IBS: 0.19631729190649894
Fold 4 IBS: 0.22343753868352592
Fold 5 IBS: 0.16912765698741056
[I 2024-04-22 02:39:45,229] Trial 25 finished with value: 0.1983178604103447 and parameters: {'l1_ratio': 0.26085123056535237}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.22151868030814933
Fold 2 IBS: 0.18132595560456718
Fold 3 IBS: 0.19682891832452348
Fold 4 IBS: 0.2235130791854169
Fold 5 IBS: 0.1693282218555301
[I 2024-04-22 02:39:45,676] Trial 26 finished with value: 0.1985029710556374 and parameters: {'l1_ratio': 0.43696099753129897}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.2214592641915538
Fold 2 IBS: 0.18129567464185548
Fold 3 IBS: 0.19653472717995307
Fold 4 IBS: 0.2234250682478324
Fold 5 IBS: 0.16923731812040776
[I 2024-04-22 02:39:46,143] Trial 27 finished with value: 0.1983904104763205 and parameters: {'l1_ratio': 0.27892291380382256}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.22143540712990956
Fold 2 IBS: 0.18125118874220356
Fold 3 IBS: 0.22290426432466728
Fold 4 IBS: 0.2233124290392491
Fold 5 IBS: 0.16920721872739
[I 2024-04-22 02:39:46,569] Trial 28 finished with value: 0.20362210159268387 and parameters: {'l1_ratio': 0.16505294849875785}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.24554691619444616
Fold 2 IBS: 0.23011606709119656
Fold 3 IBS: 0.22632642868080757
Fold 4 IBS: 0.23987747058563824
Fold 5 IBS: 0.22694704255316003
[I 2024-04-22 02:39:46,742] Trial 29 finished with value: 0.2337627850210497 and parameters: {'l1_ratio': 0.06186755842727806}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.22161576903193467
Fold 2 IBS: 0.18147553434684038
Fold 3 IBS: 0.19707355255462272
Fold 4 IBS: 0.2237401683285351
Fold 5 IBS: 0.16936115151865397
[I 2024-04-22 02:39:47,137] Trial 30 finished with value: 0.19865323515611738 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.22149243014102055
Fold 2 IBS: 0.18125305516280815
Fold 3 IBS: 0.19638993808217783
Fold 4 IBS: 0.2233222403561213
Fold 5 IBS: 0.16918788204277044
[I 2024-04-22 02:39:47,609] Trial 31 finished with value: 0.19832910915697968 and parameters: {'l1_ratio': 0.2106643766834007}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.22150180058296018
Fold 2 IBS: 0.18128280445612102
Fold 3 IBS: 0.19647560408965659
Fold 4 IBS: 0.22340247907921287
Fold 5 IBS: 0.16918794625169206
[I 2024-04-22 02:39:48,138] Trial 32 finished with value: 0.19837012689192854 and parameters: {'l1_ratio': 0.3181420486246476}. Best is trial 25 with value: 0.1983178604103447.
Fold 1 IBS: 0.22145810809705857
Fold 2 IBS: 0.18121454076228447
Fold 3 IBS: 0.19624469681156212
Fold 4 IBS: 0.22338277156360697
Fold 5 IBS: 0.16911442623546782
[I 2024-04-22 02:39:48,675] Trial 33 finished with value: 0.19828290869399598 and parameters: {'l1_ratio': 0.20127514236943678}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22180462173016655
Fold 2 IBS: 0.18172428217599781
Fold 3 IBS: 0.19800934024487177
Fold 4 IBS: 0.2243106318027617
Fold 5 IBS: 0.16961740074363793
[I 2024-04-22 02:39:49,203] Trial 34 finished with value: 0.19909325533948716 and parameters: {'l1_ratio': 0.9753166172337435}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.221483877101269
Fold 2 IBS: 0.18133708560866602
Fold 3 IBS: 0.19666697173056621
Fold 4 IBS: 0.22352520560000955
Fold 5 IBS: 0.1692729185111588
[I 2024-04-22 02:39:49,695] Trial 35 finished with value: 0.1984572117103339 and parameters: {'l1_ratio': 0.36247161763690616}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22170308661231383
Fold 2 IBS: 0.1816243768664177
Fold 3 IBS: 0.19764344627915076
Fold 4 IBS: 0.22408900707912602
Fold 5 IBS: 0.1695661728539311
[I 2024-04-22 02:39:50,093] Trial 36 finished with value: 0.19892521793818788 and parameters: {'l1_ratio': 0.8532956215563254}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148496183330338
Fold 2 IBS: 0.18125445557423508
Fold 3 IBS: 0.19638189483025992
Fold 4 IBS: 0.22333272202637966
Fold 5 IBS: 0.16916025361727838
[I 2024-04-22 02:39:50,532] Trial 37 finished with value: 0.19832285757629128 and parameters: {'l1_ratio': 0.26600483265246294}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22153160514832324
Fold 2 IBS: 0.18135789365144855
Fold 3 IBS: 0.19691467651964625
Fold 4 IBS: 0.22359212357513616
Fold 5 IBS: 0.16934006308048755
[I 2024-04-22 02:39:50,903] Trial 38 finished with value: 0.19854727239500833 and parameters: {'l1_ratio': 0.5096961654673331}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22154593771432932
Fold 2 IBS: 0.18135773662947802
Fold 3 IBS: 0.196715139352222
Fold 4 IBS: 0.2235816368692938
Fold 5 IBS: 0.16925656009715198
[I 2024-04-22 02:39:51,319] Trial 39 finished with value: 0.19849140213249503 and parameters: {'l1_ratio': 0.45136264435780316}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2448308080047578
Fold 2 IBS: 0.2293130209492364
Fold 3 IBS: 0.2252008639546682
Fold 4 IBS: 0.23901233012737866
Fold 5 IBS: 0.225913455674192
[I 2024-04-22 02:39:51,479] Trial 40 finished with value: 0.23285409574204663 and parameters: {'l1_ratio': 0.09228140358480172}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214605443361673
Fold 2 IBS: 0.1812970325222477
Fold 3 IBS: 0.19653972608876327
Fold 4 IBS: 0.22342807857813546
Fold 5 IBS: 0.1692398375406412
[I 2024-04-22 02:39:51,971] Trial 41 finished with value: 0.19839304381319098 and parameters: {'l1_ratio': 0.27936373110641877}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22147511813964904
Fold 2 IBS: 0.18124773824126436
Fold 3 IBS: 0.19659669086838022
Fold 4 IBS: 0.22346233251380893
Fold 5 IBS: 0.1691356149248049
[I 2024-04-22 02:39:52,640] Trial 42 finished with value: 0.1983834989375815 and parameters: {'l1_ratio': 0.2844737577659129}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214822250203308
Fold 2 IBS: 0.18123549058540647
Fold 3 IBS: 0.22261003851597577
Fold 4 IBS: 0.22327830374889104
Fold 5 IBS: 0.16917035292453622
[I 2024-04-22 02:39:53,031] Trial 43 finished with value: 0.20355528215902807 and parameters: {'l1_ratio': 0.17567868399098885}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22150046272295754
Fold 2 IBS: 0.1812693912639527
Fold 3 IBS: 0.19644243289344077
Fold 4 IBS: 0.2233637642392846
Fold 5 IBS: 0.16919932006358857
[I 2024-04-22 02:39:53,452] Trial 44 finished with value: 0.19835507423664483 and parameters: {'l1_ratio': 0.2508711370001455}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148854034733384
Fold 2 IBS: 0.1813479423544415
Fold 3 IBS: 0.19669832637975537
Fold 4 IBS: 0.22355212340213018
Fold 5 IBS: 0.1692763244300509
[I 2024-04-22 02:39:53,849] Trial 45 finished with value: 0.19847265138274234 and parameters: {'l1_ratio': 0.3925067419926416}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22147024062714232
Fold 2 IBS: 0.18122493513630245
Fold 3 IBS: 0.2222785260543636
Fold 4 IBS: 0.22340292350142785
Fold 5 IBS: 0.1691426037262258
[I 2024-04-22 02:39:54,220] Trial 46 finished with value: 0.2035038458090924 and parameters: {'l1_ratio': 0.18808086198825413}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22149228903245827
Fold 2 IBS: 0.1812771495104671
Fold 3 IBS: 0.19668659668103514
Fold 4 IBS: 0.2233933365843507
Fold 5 IBS: 0.1691629351601149
[I 2024-04-22 02:39:54,629] Trial 47 finished with value: 0.19840246139368523 and parameters: {'l1_ratio': 0.3394655090677283}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.24597947700065603
Fold 2 IBS: 0.2306031179238936
Fold 3 IBS: 0.22700400021183914
Fold 4 IBS: 0.2404050207833326
Fold 5 IBS: 0.22757002008522406
[I 2024-04-22 02:39:54,839] Trial 48 finished with value: 0.2343123272009891 and parameters: {'l1_ratio': 0.04487776284637307}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22145541081538722
Fold 2 IBS: 0.22840702492682188
Fold 3 IBS: 0.22391799531885156
Fold 4 IBS: 0.2380427548771538
Fold 5 IBS: 0.2247348280823563
[I 2024-04-22 02:39:55,127] Trial 49 finished with value: 0.22731160280411414 and parameters: {'l1_ratio': 0.13089433650196083}. Best is trial 33 with value: 0.19828290869399598.

Fold 1 IBS: 0.22147885828503627
Fold 2 IBS: 0.18124756287016922
Fold 3 IBS: 0.19635614378314287
Fold 4 IBS: 0.223459242187016
Fold 5 IBS: 0.16914726192437393
[I 2024-04-22 02:39:55,638] Trial 50 finished with value: 0.19833781380994767 and parameters: {'l1_ratio': 0.26392974195782654}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22145249900032216
Fold 2 IBS: 0.18127487964792016
Fold 3 IBS: 0.19622103277723404
Fold 4 IBS: 0.22336949673368683
Fold 5 IBS: 0.1691024522781901
[I 2024-04-22 02:39:56,140] Trial 51 finished with value: 0.19828407208747065 and parameters: {'l1_ratio': 0.19981378826499338}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22147192974364843
Fold 2 IBS: 0.18122996669240043
Fold 3 IBS: 0.19630309492071613
Fold 4 IBS: 0.22341546315860908
Fold 5 IBS: 0.169143968523679
[I 2024-04-22 02:39:56,602] Trial 52 finished with value: 0.1983128846078106 and parameters: {'l1_ratio': 0.20496157351125788}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22147492596744867
Fold 2 IBS: 0.1812333256000158
Fold 3 IBS: 0.1963157705797653
Fold 4 IBS: 0.22327723815299952
Fold 5 IBS: 0.16915037951465817
[I 2024-04-22 02:39:57,028] Trial 53 finished with value: 0.1982903279629775 and parameters: {'l1_ratio': 0.20577718125619732}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22144808723482454
Fold 2 IBS: 0.18127023448457885
Fold 3 IBS: 0.19645786948918822
Fold 4 IBS: 0.22335905234923067
Fold 5 IBS: 0.16909304034747843
[I 2024-04-22 02:39:57,551] Trial 54 finished with value: 0.19832565678106012 and parameters: {'l1_ratio': 0.1986780439845564}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22145295742438714
Fold 2 IBS: 0.18120021602600936
Fold 3 IBS: 0.2231897992023848
Fold 4 IBS: 0.2374998014772154
Fold 5 IBS: 0.16910928942093123
[I 2024-04-22 02:39:58,172] Trial 55 finished with value: 0.2064904127101856 and parameters: {'l1_ratio': 0.15506238502646463}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.24508271905522333
Fold 2 IBS: 0.2295950751786677
Fold 3 IBS: 0.22559741086067178
Fold 4 IBS: 0.23931555183833048
Fold 5 IBS: 0.22627751024197404
[I 2024-04-22 02:39:58,365] Trial 56 finished with value: 0.23317365343497345 and parameters: {'l1_ratio': 0.0812308016621317}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22146545973795945
Fold 2 IBS: 0.22884879021798674
Fold 3 IBS: 0.22454527132792573
Fold 4 IBS: 0.23851470511781436
Fold 5 IBS: 0.225311445848692
[I 2024-04-22 02:39:58,593] Trial 57 finished with value: 0.22773713445007565 and parameters: {'l1_ratio': 0.11143368512064933}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.24713581612285834
Fold 2 IBS: 0.23191314434164764
Fold 3 IBS: 0.2288085462235603
Fold 4 IBS: 0.24183546536077546
Fold 5 IBS: 0.22923511280978112
[I 2024-04-22 02:39:58,780] Trial 58 finished with value: 0.23578561697172457 and parameters: {'l1_ratio': 0.003680241884233326}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22146902771166047
Fold 2 IBS: 0.1812267184491688
Fold 3 IBS: 0.19629082327288266
Fold 4 IBS: 0.22340860144018518
Fold 5 IBS: 0.16913776141256506
[I 2024-04-22 02:39:59,233] Trial 59 finished with value: 0.19830658645729243 and parameters: {'l1_ratio': 0.20417727570827063}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214801898721419
Fold 2 IBS: 0.18125823247939002
Fold 3 IBS: 0.19662760185938014
Fold 4 IBS: 0.22348713015059107
Fold 5 IBS: 0.1691421698006097
[I 2024-04-22 02:39:59,610] Trial 60 finished with value: 0.19839906483242256 and parameters: {'l1_ratio': 0.30965198859771054}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22145481382592896
Fold 2 IBS: 0.1812806128750051
Fold 3 IBS: 0.19649277405959445
Fold 4 IBS: 0.22338434137730712
Fold 5 IBS: 0.1691047609190612
[I 2024-04-22 02:40:00,152] Trial 61 finished with value: 0.19834346061137936 and parameters: {'l1_ratio': 0.21778278331184836}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148305024879789
Fold 2 IBS: 0.18123377322952422
Fold 3 IBS: 0.2230037796041026
Fold 4 IBS: 0.22327263592364607
Fold 5 IBS: 0.1691739611351806
[I 2024-04-22 02:40:00,572] Trial 62 finished with value: 0.2036334400282503 and parameters: {'l1_ratio': 0.1615360720002912}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22144590551490767
Fold 2 IBS: 0.1812748069626979
Fold 3 IBS: 0.19646710164192657
Fold 4 IBS: 0.22337351498040045
Fold 5 IBS: 0.16921957738328125
[I 2024-04-22 02:40:01,112] Trial 63 finished with value: 0.1983561812966428 and parameters: {'l1_ratio': 0.23380283740721886}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148624795749097
Fold 2 IBS: 0.22853235628972252
Fold 3 IBS: 0.22409629610122012
Fold 4 IBS: 0.23817649698913354
Fold 5 IBS: 0.22489882326248067
[I 2024-04-22 02:40:01,370] Trial 64 finished with value: 0.2274380441200096 and parameters: {'l1_ratio': 0.12524211481263461}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22146978371461498
Fold 2 IBS: 0.18122756416258953
Fold 3 IBS: 0.1962940196133198
Fold 4 IBS: 0.22341038909128402
Fold 5 IBS: 0.16913937819388766
[I 2024-04-22 02:40:01,798] Trial 65 finished with value: 0.1983082269551392 and parameters: {'l1_ratio': 0.20438105763682965}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22144414945363783
Fold 2 IBS: 0.18126609643613653
Fold 3 IBS: 0.1964424255105438
Fold 4 IBS: 0.22334972766335745
Fold 5 IBS: 0.16922092766830005
[I 2024-04-22 02:40:02,253] Trial 66 finished with value: 0.1983446653463951 and parameters: {'l1_ratio': 0.19767431528868015}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22147121377144
Fold 2 IBS: 0.18131296903597757
Fold 3 IBS: 0.19659255919358998
Fold 4 IBS: 0.2234660899987877
Fold 5 IBS: 0.16925706005238061
[I 2024-04-22 02:40:02,693] Trial 67 finished with value: 0.19841997841043518 and parameters: {'l1_ratio': 0.3062467698859164}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.24560818133334225
Fold 2 IBS: 0.23018495549718293
Fold 3 IBS: 0.2264224932019191
Fold 4 IBS: 0.23995195340625622
Fold 5 IBS: 0.22703531626470125
[I 2024-04-22 02:40:02,854] Trial 68 finished with value: 0.23384057994068033 and parameters: {'l1_ratio': 0.05940223331823771}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.24467475838067823
Fold 2 IBS: 0.22913852147707955
Fold 3 IBS: 0.2249548619474482
Fold 4 IBS: 0.2388250708754039
Fold 5 IBS: 0.22568759963841395
[I 2024-04-22 02:40:03,020] Trial 69 finished with value: 0.23265616246380477 and parameters: {'l1_ratio': 0.09933435064393535}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22150372550488265
Fold 2 IBS: 0.18129021431517048
Fold 3 IBS: 0.19649613530430476
Fold 4 IBS: 0.22342241372437782
Fold 5 IBS: 0.16918709597613632
[I 2024-04-22 02:40:03,400] Trial 70 finished with value: 0.19837991696497442 and parameters: {'l1_ratio': 0.34429792728023395}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22144465965940294
Fold 2 IBS: 0.1812734963607078
Fold 3 IBS: 0.19646222992888226
Fold 4 IBS: 0.22337057358498302
Fold 5 IBS: 0.16921711711356066
[I 2024-04-22 02:40:03,793] Trial 71 finished with value: 0.19835361532950735 and parameters: {'l1_ratio': 0.233438071844435}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22144266251502068
Fold 2 IBS: 0.18125624093628082
Fold 3 IBS: 0.22325110873515353
Fold 4 IBS: 0.23754531638422122
Fold 5 IBS: 0.1690872228752641
[I 2024-04-22 02:40:04,106] Trial 72 finished with value: 0.20651651028918802 and parameters: {'l1_ratio': 0.15295669125545786}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22146766633516632
Fold 2 IBS: 0.1812220585492567
Fold 3 IBS: 0.22229545091903685
Fold 4 IBS: 0.22339682811696396
Fold 5 IBS: 0.16913708842277547
[I 2024-04-22 02:40:04,468] Trial 73 finished with value: 0.20350381846863988 and parameters: {'l1_ratio': 0.1874361508838899}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22151184382648267
Fold 2 IBS: 0.18128101806150315
Fold 3 IBS: 0.19648562679758114
Fold 4 IBS: 0.22338982100458035
Fold 5 IBS: 0.16922111769053916
[I 2024-04-22 02:40:04,882] Trial 74 finished with value: 0.19837788547613727 and parameters: {'l1_ratio': 0.25431560306667794}. Best is trial 33 with value: 0.19828290869399598.

Fold 1 IBS: 0.22145833562660228
Fold 2 IBS: 0.1812843344061404
Fold 3 IBS: 0.19625474182474914
Fold 4 IBS: 0.2233926635645862
Fold 5 IBS: 0.1691122657125409
[I 2024-04-22 02:40:05,303] Trial 75 finished with value: 0.19830046822692377 and parameters: {'l1_ratio': 0.21877076880955348}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214954081558956
Fold 2 IBS: 0.181256429949
Fold 3 IBS: 0.1964025762828797
Fold 4 IBS: 0.2233298581667425
Fold 5 IBS: 0.16919427075206617
[I 2024-04-22 02:40:05,749] Trial 76 finished with value: 0.1983357086613168 and parameters: {'l1_ratio': 0.21151725679643862}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22151584096864146
Fold 2 IBS: 0.1813160798499
Fold 3 IBS: 0.1968043493341068
Fold 4 IBS: 0.2234870546265941
Fold 5 IBS: 0.16920092137734216
[I 2024-04-22 02:40:06,137] Trial 77 finished with value: 0.19846484923131694 and parameters: {'l1_ratio': 0.4054232104720076}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148573165142338
Fold 2 IBS: 0.1812597270659264
Fold 3 IBS: 0.19639615956592638
Fold 4 IBS: 0.22334755488681934
Fold 5 IBS: 0.16915813811567393
[I 2024-04-22 02:40:06,559] Trial 78 finished with value: 0.1983294622571539 and parameters: {'l1_ratio': 0.2883043637762722}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22160892992528686
Fold 2 IBS: 0.1814013328670032
Fold 3 IBS: 0.19703045247194792
Fold 4 IBS: 0.22369559948352577
Fold 5 IBS: 0.16936081666165004
[I 2024-04-22 02:40:06,942] Trial 79 finished with value: 0.19861942628188275 and parameters: {'l1_ratio': 0.5933865341035967}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214655061208468
Fold 2 IBS: 0.18121677469394118
Fold 3 IBS: 0.2227179143051974
Fold 4 IBS: 0.22338386216881312
Fold 5 IBS: 0.1691344503022063
[I 2024-04-22 02:40:07,309] Trial 80 finished with value: 0.20358370151820093 and parameters: {'l1_ratio': 0.17174249961271554}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214802380766397
Fold 2 IBS: 0.18124647303175553
Fold 3 IBS: 0.19635689240708687
Fold 4 IBS: 0.22331193828369789
Fold 5 IBS: 0.16915613637809274
[I 2024-04-22 02:40:07,733] Trial 81 finished with value: 0.19831033563545453 and parameters: {'l1_ratio': 0.24428344823243484}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22150075462214674
Fold 2 IBS: 0.1812625020311116
Fold 3 IBS: 0.1964252802913567
Fold 4 IBS: 0.22334359424990977
Fold 5 IBS: 0.16920574656432044
[I 2024-04-22 02:40:08,140] Trial 82 finished with value: 0.19834757555176905 and parameters: {'l1_ratio': 0.2130645786749037}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214735303913614
Fold 2 IBS: 0.2283348486387226
Fold 3 IBS: 0.22381519678388082
Fold 4 IBS: 0.23796578872229593
Fold 5 IBS: 0.16915644232851856
[I 2024-04-22 02:40:08,400] Trial 83 finished with value: 0.21614916137295587 and parameters: {'l1_ratio': 0.13419876060191055}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22146492575684457
Fold 2 IBS: 0.1812974872800386
Fold 3 IBS: 0.19654647508344864
Fold 4 IBS: 0.22342648460751874
Fold 5 IBS: 0.16911768485231715
[I 2024-04-22 02:40:08,788] Trial 84 finished with value: 0.19837061151603355 and parameters: {'l1_ratio': 0.2593091986660466}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22145017595234023
Fold 2 IBS: 0.18126941688352774
Fold 3 IBS: 0.22240851330579128
Fold 4 IBS: 0.22335538921542272
Fold 5 IBS: 0.16909966437827412
[I 2024-04-22 02:40:09,136] Trial 85 finished with value: 0.20351663194707123 and parameters: {'l1_ratio': 0.18316164171831117}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22146304534239342
Fold 2 IBS: 0.18130426924005646
Fold 3 IBS: 0.1965607033197016
Fold 4 IBS: 0.2234469325397568
Fold 5 IBS: 0.16924102280322992
[I 2024-04-22 02:40:09,533] Trial 86 finished with value: 0.19840319464902761 and parameters: {'l1_ratio': 0.3032070880652719}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2214630819272986
Fold 2 IBS: 0.1812272217057325
Fold 3 IBS: 0.19628453482542602
Fold 4 IBS: 0.22341404398052558
Fold 5 IBS: 0.16911959073069435
[I 2024-04-22 02:40:10,008] Trial 87 finished with value: 0.1983016946339354 and parameters: {'l1_ratio': 0.238940593221755}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22145646291688784
Fold 2 IBS: 0.18128594340561643
Fold 3 IBS: 0.1965084143310293
Fold 4 IBS: 0.22339843113364447
Fold 5 IBS: 0.16924043776565348
[I 2024-04-22 02:40:10,433] Trial 88 finished with value: 0.1983779379105663 and parameters: {'l1_ratio': 0.236936378853005}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22167200200516654
Fold 2 IBS: 0.1815741150060153
Fold 3 IBS: 0.19751642909278264
Fold 4 IBS: 0.2239754888198126
Fold 5 IBS: 0.16953145042864828
[I 2024-04-22 02:40:10,815] Trial 89 finished with value: 0.1988538970704851 and parameters: {'l1_ratio': 0.7903076413479658}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.2215188633998977
Fold 2 IBS: 0.1813076141710274
Fold 3 IBS: 0.19655987707912115
Fold 4 IBS: 0.2234608754486862
Fold 5 IBS: 0.16921912842281825
[I 2024-04-22 02:40:11,188] Trial 90 finished with value: 0.19841327170431014 and parameters: {'l1_ratio': 0.3508916349287031}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148074090781802
Fold 2 IBS: 0.18125408134404403
Fold 3 IBS: 0.19637513866247
Fold 4 IBS: 0.22347553973125217
Fold 5 IBS: 0.16914754342982155
[I 2024-04-22 02:40:11,559] Trial 91 finished with value: 0.19834660881508115 and parameters: {'l1_ratio': 0.28649138832750976}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22149812891893886
Fold 2 IBS: 0.18125951783654862
Fold 3 IBS: 0.19641412779716352
Fold 4 IBS: 0.2233368487597402
Fold 5 IBS: 0.169200109701035
[I 2024-04-22 02:40:11,964] Trial 92 finished with value: 0.19834174660268525 and parameters: {'l1_ratio': 0.21230206469506724}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148375956017743
Fold 2 IBS: 0.22803336643938008
Fold 3 IBS: 0.22338483285759367
Fold 4 IBS: 0.2376447149879324
Fold 5 IBS: 0.1691771321262463
[I 2024-04-22 02:40:12,315] Trial 93 finished with value: 0.21594476119426598 and parameters: {'l1_ratio': 0.14841073138047775}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22148705779493438
Fold 2 IBS: 0.18125417390844273
Fold 3 IBS: 0.19638570727334648
Fold 4 IBS: 0.22332941969045625
Fold 5 IBS: 0.1691706855609405
[I 2024-04-22 02:40:12,847] Trial 94 finished with value: 0.19832540884562405 and parameters: {'l1_ratio': 0.24646881752088112}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22149426434761965
Fold 2 IBS: 0.18124907116293815
Fold 3 IBS: 0.2225303272182521
Fold 4 IBS: 0.22330928901631086
Fold 5 IBS: 0.1691962545376337
[I 2024-04-22 02:40:13,304] Trial 95 finished with value: 0.20355584125655088 and parameters: {'l1_ratio': 0.1786180201976334}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22150946791480994
Fold 2 IBS: 0.1812915768667871
Fold 3 IBS: 0.1965079390681197
Fold 4 IBS: 0.2234220122245034
Fold 5 IBS: 0.16920421684879827
[I 2024-04-22 02:40:13,803] Trial 96 finished with value: 0.19838704258460368 and parameters: {'l1_ratio': 0.3212577944420877}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22149826581415802
Fold 2 IBS: 0.1812695562724876
Fold 3 IBS: 0.1964381072637815
Fold 4 IBS: 0.22336677712073358
Fold 5 IBS: 0.1691886064798785
[I 2024-04-22 02:40:14,322] Trial 97 finished with value: 0.19835226259020783 and parameters: {'l1_ratio': 0.27063364751050495}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22142625138923605
Fold 2 IBS: 0.22875780634520604
Fold 3 IBS: 0.22441635324018103
Fold 4 IBS: 0.2384173803051906
Fold 5 IBS: 0.22519300618838253
[I 2024-04-22 02:40:14,577] Trial 98 finished with value: 0.22764215949363922 and parameters: {'l1_ratio': 0.11533832542866733}. Best is trial 33 with value: 0.19828290869399598.
Fold 1 IBS: 0.22150947083955358
Fold 2 IBS: 0.18130262890624996
Fold 3 IBS: 0.1965341295842628
Fold 4 IBS: 0.22345341177858188
Fold 5 IBS: 0.1691939524583424
[I 2024-04-22 02:40:15,028] Trial 99 finished with value: 0.19839871871339815 and parameters: {'l1_ratio': 0.3738516745000514}. Best is trial 33 with value: 0.19828290869399598.


* Best trial for IBS:
 FrozenTrial(number=33, state=TrialState.COMPLETE, values=[0.19828290869399598], datetime_start=datetime.datetime(2024, 4, 22, 2, 39, 48, 144162), datetime_complete=datetime.datetime(2024, 4, 22, 2, 39, 48, 675073), params={'l1_ratio': 0.20127514236943678}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=33, value=None)


* Best Score for IBS:
 0.19828290869399598

In [49]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [50]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.733
train_ibs:  0.198

#### Test

In [51]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [52]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.1636708494922895)

test_cindex : 0.565

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.20127514236943678)

test_ibs:  0.287

In [53]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [54]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:40:15,485] A new study created in memory with name: no-name-a7314eca-af31-4f25-b775-73ac935ff4e2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 02:40:20,503] Trial 0 finished with value: 0.6991621322401306 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6991621322401306.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 02:40:23,720] Trial 1 finished with value: 0.7355301592065651 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 02:40:25,824] Trial 2 finished with value: 0.7272289231066792 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:26,484] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:27,438] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 02:40:30,962] Trial 5 finished with value: 0.7346380398835799 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 02:40:34,598] Trial 6 finished with value: 0.7176325154358497 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:36,511] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 02:40:41,728] Trial 8 finished with value: 0.5339055793991416 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 02:40:45,372] Trial 9 finished with value: 0.7297749791965019 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:45,912] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 02:40:47,326] Trial 11 finished with value: 0.7275011596037759 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 02:40:51,174] Trial 12 finished with value: 0.7312271571122319 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7124463519313304
[I 2024-04-22 02:40:55,893] Trial 13 finished with value: 0.7285078854302759 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017530569165213797, 'warm_start': False}. Best is trial 1 with value: 0.7355301592065651.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.776824034334764
[I 2024-04-22 02:40:56,632] Trial 14 finished with value: 0.7726196368380054 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.48589405900235655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17488909350671974, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7446808510638298

Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:40:57,280] Trial 15 finished with value: 0.7430557612306835 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.3692598016141903, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17993556917544976, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:57,645] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 6, 'oob_score': True, 'max_samples': 0.36871324569404207, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1937382585942945, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:58,523] Trial 17 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 3, 'n_estimators': 123, 'oob_score': True, 'max_samples': 0.21593809517049486, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 02:40:59,136] Trial 18 finished with value: 0.7670383225171615 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 113, 'oob_score': True, 'max_samples': 0.44482585532317004, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17047935743788273, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:40:59,552] Trial 19 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.4891559132906001, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.42883326307517006, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:41:00,500] Trial 20 finished with value: 0.5 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.4189734961049175, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2519967097606023, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:41:01,121] Trial 21 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.31767468948360755, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16572240592344814, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7725321888412017
[I 2024-04-22 02:41:01,670] Trial 22 finished with value: 0.7691752300964144 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.5356189047828304, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2038631927701136, 'warm_start': True}. Best is trial 14 with value: 0.7726196368380054.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 02:41:02,227] Trial 23 finished with value: 0.8046827761584172 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.5413453585840211, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07940861604666782, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 02:41:02,406] Trial 24 finished with value: 0.7968628519610398 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 12, 'oob_score': True, 'max_samples': 0.5434778837030446, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08417649111696884, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.812015503875969
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7253218884120172
[I 2024-04-22 02:41:02,600] Trial 25 finished with value: 0.781126535297143 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.6669213410828165, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07045653823703169, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 02:41:02,791] Trial 26 finished with value: 0.8041494497509662 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.6794016704774145, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08974480297156207, 'warm_start': True}. Best is trial 23 with value: 0.8046827761584172.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 02:41:03,100] Trial 27 finished with value: 0.8126094014577081 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.8630402705028295, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07610225238763382, 'warm_start': True}. Best is trial 27 with value: 0.8126094014577081.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 02:41:03,411] Trial 28 finished with value: 0.8020961148667425 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.9854572776620717, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1322471380695946, 'warm_start': True}. Best is trial 27 with value: 0.8126094014577081.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8927038626609443
[I 2024-04-22 02:41:04,300] Trial 29 finished with value: 0.839683794009181 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 163, 'oob_score': True, 'max_samples': 0.8309193149442771, 'max_features': None, 'min_weight_fraction_leaf': 0.061461466531914734, 'warm_start': True}. Best is trial 29 with value: 0.839683794009181.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:05,242] Trial 30 finished with value: 0.8471808956568762 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 162, 'oob_score': True, 'max_samples': 0.8384725652873207, 'max_features': None, 'min_weight_fraction_leaf': 0.03824151200409104, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8969957081545065
[I 2024-04-22 02:41:06,146] Trial 31 finished with value: 0.8438452051001395 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 166, 'oob_score': True, 'max_samples': 0.8383718236388968, 'max_features': None, 'min_weight_fraction_leaf': 0.05349821135610229, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8969957081545065
[I 2024-04-22 02:41:07,045] Trial 32 finished with value: 0.8463115133784891 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.844850651135347, 'max_features': None, 'min_weight_fraction_leaf': 0.047131601168288385, 'warm_start': True}. Best is trial 30 with value: 0.8471808956568762.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8969957081545065
[I 2024-04-22 02:41:08,417] Trial 33 finished with value: 0.8477634373205489 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 232, 'oob_score': True, 'max_samples': 0.8400958521101125, 'max_features': None, 'min_weight_fraction_leaf': 0.003787219752160495, 'warm_start': True}. Best is trial 33 with value: 0.8477634373205489.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8798283261802575
[I 2024-04-22 02:41:09,938] Trial 34 finished with value: 0.8348953318242721 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.7437347513388699, 'max_features': None, 'min_weight_fraction_leaf': 0.002606193898855683, 'warm_start': True}. Best is trial 33 with value: 0.8477634373205489.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9098712446351931
[I 2024-04-22 02:41:11,152] Trial 35 finished with value: 0.8513492046079651 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8867083209187331, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8927038626609443
[I 2024-04-22 02:41:12,477] Trial 36 finished with value: 0.8327544194780486 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 225, 'oob_score': True, 'max_samples': 0.9510497756961918, 'max_features': None, 'min_weight_fraction_leaf': 0.03820571175421267, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9184549356223176
[I 2024-04-22 02:41:14,666] Trial 37 finished with value: 0.8513421961952613 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 256, 'oob_score': True, 'max_samples': 0.8905785303043968, 'max_features': None, 'min_weight_fraction_leaf': 0.0015959813648095014, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-22 02:41:17,511] Trial 38 finished with value: 0.8036433012288817 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.8788883038694885, 'max_features': None, 'min_weight_fraction_leaf': 0.002532290324689703, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:41:19,902] Trial 39 finished with value: 0.7672578212055718 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.9144710105629309, 'max_features': None, 'min_weight_fraction_leaf': 0.12930362433818024, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:41:21,638] Trial 40 finished with value: 0.8277166012617376 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9980478663893719, 'max_features': None, 'min_weight_fraction_leaf': 0.029813810847214628, 'warm_start': True}. Best is trial 35 with value: 0.8513492046079651.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9098712446351931
[I 2024-04-22 02:41:22,894] Trial 41 finished with value: 0.8520485283750772 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 207, 'oob_score': True, 'max_samples': 0.8024276641096046, 'max_features': None, 'min_weight_fraction_leaf': 0.041434068575410196, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:24,738] Trial 42 finished with value: 0.8479087198004114 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.7648836348187944, 'max_features': None, 'min_weight_fraction_leaf': 0.033423986218882616, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:26,540] Trial 43 finished with value: 0.8496540853610947 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 205, 'oob_score': True, 'max_samples': 0.7796080313426239, 'max_features': None, 'min_weight_fraction_leaf': 0.014857830524255941, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 02:41:27,817] Trial 44 finished with value: 0.8078917831058507 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7797897259787169, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 02:41:28,617] Trial 45 finished with value: 0.7904418608687293 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7138201818624347, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14694492074117838, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 02:41:33,353] Trial 46 finished with value: 0.7254981239299447 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 284, 'oob_score': True, 'max_samples': 0.8992746801558931, 'max_features': None, 'min_weight_fraction_leaf': 0.028181408583194678, 'warm_start': False}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:34,001] Trial 47 finished with value: 0.8365327725015698 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.7205133550183166, 'max_features': None, 'min_weight_fraction_leaf': 0.05574216570821283, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 02:41:38,218] Trial 48 finished with value: 0.7086009095296246 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.8036505209305815, 'max_features': None, 'min_weight_fraction_leaf': 0.22178657477496955, 'warm_start': False}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 02:41:40,258] Trial 49 finished with value: 0.7960271358026422 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 389, 'oob_score': True, 'max_samples': 0.610884224629099, 'max_features': None, 'min_weight_fraction_leaf': 0.10220826251839069, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 02:41:40,963] Trial 50 finished with value: 0.7854372155985099 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.9361939014586368, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.28018530821993104, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 02:41:42,221] Trial 51 finished with value: 0.7756710134041036 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.7993151610130277, 'max_features': None, 'min_weight_fraction_leaf': 0.0005063458363507817, 'warm_start': True}. Best is trial 41 with value: 0.8520485283750772.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9141630901287554
[I 2024-04-22 02:41:43,590] Trial 52 finished with value: 0.8535946407970745 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 220, 'oob_score': True, 'max_samples': 0.8921259102671709, 'max_features': None, 'min_weight_fraction_leaf': 0.018293305903393637, 'warm_start': True}. Best is trial 52 with value: 0.8535946407970745.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.9069767441860465
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.927038626609442
[I 2024-04-22 02:41:45,002] Trial 53 finished with value: 0.8585132240941041 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 217, 'oob_score': True, 'max_samples': 0.9658618134365592, 'max_features': None, 'min_weight_fraction_leaf': 0.014650326015013641, 'warm_start': True}. Best is trial 53 with value: 0.8585132240941041.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:46,233] Trial 54 finished with value: 0.8632581679559443 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.9625534179904701, 'max_features': None, 'min_weight_fraction_leaf': 0.019842323563345525, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.9186046511627907
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:47,671] Trial 55 finished with value: 0.8631822979246067 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 183, 'oob_score': True, 'max_samples': 0.9637396879166721, 'max_features': None, 'min_weight_fraction_leaf': 0.02006130607634453, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 02:41:50,322] Trial 56 finished with value: 0.7258200494907298 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 141, 'oob_score': True, 'max_samples': 0.9627981016911359, 'max_features': None, 'min_weight_fraction_leaf': 0.05237976583817004, 'warm_start': False}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.9147286821705426
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.927038626609442
[I 2024-04-22 02:41:51,526] Trial 57 finished with value: 0.8624540499380153 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 187, 'oob_score': True, 'max_samples': 0.969742549381378, 'max_features': None, 'min_weight_fraction_leaf': 0.023371324683680833, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:52,534] Trial 58 finished with value: 0.8623951162735353 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': True, 'max_samples': 0.9690133939480812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021524357754764783, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:53,103] Trial 59 finished with value: 0.8623951162735353 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9702801247369853, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01939288260546853, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 02:41:54,910] Trial 60 finished with value: 0.7174226465122555 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 186, 'oob_score': False, 'max_samples': 0.9713481779848987, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.354956875935207, 'warm_start': False}. Best is trial 54 with value: 0.8632581679559443.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:41:55,393] Trial 61 finished with value: 0.863249761027237 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.9315899812443563, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023014102784859193, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9055793991416309
[I 2024-04-22 02:41:55,738] Trial 62 finished with value: 0.8405373371031004 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9238731528894242, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06716848446483438, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 02:41:56,186] Trial 63 finished with value: 0.7482015307786698 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 156, 'oob_score': False, 'max_samples': 0.949454174371522, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42582787243459574, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.8798283261802575
[I 2024-04-22 02:41:56,747] Trial 64 finished with value: 0.8273796413200459 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.9917921798289998, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09031712086014251, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:41:57,495] Trial 65 finished with value: 0.8592294842280737 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9240040548597519, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02047626469173783, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9012875536480687
[I 2024-04-22 02:41:58,173] Trial 66 finished with value: 0.8394945958114837 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9229156191863954, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06380717535025415, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 02:41:58,820] Trial 67 finished with value: 0.7955811892681643 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.995009976038662, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02429896250829207, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:41:59,241] Trial 68 finished with value: 0.8338770961561366 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 97, 'oob_score': False, 'max_samples': 0.9428503920721849, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-22 02:41:59,808] Trial 69 finished with value: 0.8069246578719019 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 146, 'oob_score': False, 'max_samples': 0.8666896988471977, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.124823245098527, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8154506437768241
[I 2024-04-22 02:42:00,295] Trial 70 finished with value: 0.7945878301699866 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 130, 'oob_score': False, 'max_samples': 0.12462860681265314, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02126228748040546, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:42:01,006] Trial 71 finished with value: 0.859189970671976 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 192, 'oob_score': False, 'max_samples': 0.9740624334770935, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016292071205830195, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.927038626609442
[I 2024-04-22 02:42:01,570] Trial 72 finished with value: 0.8567849383213751 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 175, 'oob_score': False, 'max_samples': 0.9162488213949347, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05261359898316401, 'warm_start': True}. Best is trial 54 with value: 0.8632581679559443.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:42:02,178] Trial 73 finished with value: 0.8633946196640432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.9999354575629575, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031604961665606564, 'warm_start': True}. Best is trial 73 with value: 0.8633946196640432.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9277566539923955
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:42:02,726] Trial 74 finished with value: 0.8649624944576914 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 148, 'oob_score': False, 'max_samples': 0.9395463682850804, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03591904730025234, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:42:03,524] Trial 75 finished with value: 0.8291758140384612 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 151, 'oob_score': False, 'max_samples': 0.9558720298384755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08775783727116993, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9574468085106383
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:42:03,942] Trial 76 finished with value: 0.8644300556867346 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 102, 'oob_score': False, 'max_samples': 0.993930256699719, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0398572345294084, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.8927038626609443
[I 2024-04-22 02:42:04,329] Trial 77 finished with value: 0.8340113654563247 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 95, 'oob_score': False, 'max_samples': 0.9913390641588559, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04234216642710123, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8884120171673819
[I 2024-04-22 02:42:04,756] Trial 78 finished with value: 0.8409578033411496 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 109, 'oob_score': False, 'max_samples': 0.8630045149985799, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0609070149180181, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 02:42:05,217] Trial 79 finished with value: 0.8035852429701545 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 127, 'oob_score': False, 'max_samples': 0.9045813350723169, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07865274171241976, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-22 02:42:06,159] Trial 80 finished with value: 0.7261480403266783 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.9452700606717033, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03478111510727396, 'warm_start': False}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.9227467811158798
[I 2024-04-22 02:42:06,756] Trial 81 finished with value: 0.8600881237347175 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 11, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9701774756059413, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009387333105181828, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:42:07,522] Trial 82 finished with value: 0.8634130815337395 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 199, 'oob_score': False, 'max_samples': 0.9740317203146824, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.031105510537608762, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:42:08,216] Trial 83 finished with value: 0.855212788352825 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 195, 'oob_score': False, 'max_samples': 0.9452433661930899, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.046861909789421494, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9227467811158798
[I 2024-04-22 02:42:08,691] Trial 84 finished with value: 0.85060280804216 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.991804397125127, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03327645272133899, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8626609442060086
[I 2024-04-22 02:42:09,184] Trial 85 finished with value: 0.8142802013847452 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.9999498552793648, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11550818315944608, 'warm_start': True}. Best is trial 74 with value: 0.8649624944576914.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.935361216730038
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:42:09,579] Trial 86 finished with value: 0.8662268726917273 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.8746458616251406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030922977401692878, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.9125475285171103
Fold 5 C-index: 0.8841201716738197
[I 2024-04-22 02:42:09,970] Trial 87 finished with value: 0.840718756224406 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.8654172382794998, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06452241723435258, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.871244635193133
[I 2024-04-22 02:42:10,241] Trial 88 finished with value: 0.8168442790669467 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.9315642015297859, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0949696957319068, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9184549356223176
[I 2024-04-22 02:42:10,677] Trial 89 finished with value: 0.8558359452323782 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 125, 'oob_score': False, 'max_samples': 0.9038308798666062, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.044442422879351094, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:42:10,874] Trial 90 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 29, 'oob_score': False, 'max_samples': 0.8757558739983621, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.4966080828658863, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9399141630901288
[I 2024-04-22 02:42:11,583] Trial 91 finished with value: 0.8626884309053237 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.9776306114812428, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.028839161868997508, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9313304721030042
[I 2024-04-22 02:42:12,280] Trial 92 finished with value: 0.8560280629715251 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 243, 'oob_score': False, 'max_samples': 0.9311993321115322, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030551566023909363, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9227467811158798
[I 2024-04-22 02:42:12,890] Trial 93 finished with value: 0.8541564276305669 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 200, 'oob_score': False, 'max_samples': 0.9091701552343036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009137289628038645, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:42:13,422] Trial 94 finished with value: 0.85451761277378 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9564057018609697, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05197512631502196, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.8798283261802575
[I 2024-04-22 02:42:14,169] Trial 95 finished with value: 0.8337498517029143 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8876723605013093, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07696236087701544, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9055793991416309
[I 2024-04-22 02:42:14,672] Trial 96 finished with value: 0.843083647166593 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 152, 'oob_score': False, 'max_samples': 0.9760183262225188, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00019495076365802846, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9399141630901288
[I 2024-04-22 02:42:15,347] Trial 97 finished with value: 0.8633118846410982 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 210, 'oob_score': False, 'max_samples': 0.8197716452211096, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03271483017646171, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7811158798283262
[I 2024-04-22 02:42:18,135] Trial 98 finished with value: 0.7399225237760426 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.8315355201803293, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03474288685672425, 'warm_start': False}. Best is trial 86 with value: 0.8662268726917273.

[I 2024-04-22 02:42:19,226] A new study created in memory with name: no-name-b71c4e8b-af4f-4184-bacc-94920f04a97b

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.9356223175965666
[I 2024-04-22 02:42:19,216] Trial 99 finished with value: 0.8552780690475444 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.9381470917280882, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.058903635501878514, 'warm_start': True}. Best is trial 86 with value: 0.8662268726917273.


* Best trial for C-index:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.8662268726917273], datetime_start=datetime.datetime(2024, 4, 22, 2, 42, 9, 187212), datetime_complete=datetime.datetime(2024, 4, 22, 2, 42, 9, 579035), params={'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.8746458616251406, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030922977401692878, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=86, value=None)


* Best Score for C-index:
 0.8662268726917273

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21762433179841878
Fold 2 IBS: 0.18195020133812084
Fold 3 IBS: 0.2361143230502189
Fold 4 IBS: 0.2073285062122392
Fold 5 IBS: 0.21392727346918483
[I 2024-04-22 02:42:22,772] Trial 0 finished with value: 0.21138892717363653 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21138892717363653.
Fold 1 IBS: 0.21581044184076711
Fold 2 IBS: 0.17697992286624134
Fold 3 IBS: 0.20953123826339945
Fold 4 IBS: 0.19758108917721037
Fold 5 IBS: 0.20179307042175074
[I 2024-04-22 02:42:23,609] Trial 1 finished with value: 0.2003391525138738 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-22 02:42:24,207] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-22 02:42:26,356] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-22 02:42:28,286] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2003391525138738.
Fold 1 IBS: 0.221854155851065
Fold 2 IBS: 0.17690263638724796
Fold 3 IBS: 0.1967547177467275
Fold 4 IBS: 0.18843430540942496
Fold 5 IBS: 0.18075314399111414
[I 2024-04-22 02:42:30,865] Trial 5 finished with value: 0.1929397918771159 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2131217857918839
Fold 2 IBS: 0.19307243279090222
Fold 3 IBS: 0.25137354374382015
Fold 4 IBS: 0.20218154161317498
Fold 5 IBS: 0.2126608840238083
[I 2024-04-22 02:42:33,689] Trial 6 finished with value: 0.2144820375927179 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2388433246721578
Fold 2 IBS: 0.22464552665811907
Fold 3 IBS: 0.22584090572561383
Fold 4 IBS: 0.231868515757187
Fold 5 IBS: 0.22190410121033288
[I 2024-04-22 02:42:37,043] Trial 7 finished with value: 0.22862047480468214 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-22 02:42:41,430] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.21807767436739164
Fold 2 IBS: 0.18501717466232873
Fold 3 IBS: 0.19984578577268608
Fold 4 IBS: 0.2107172403878465
Fold 5 IBS: 0.20405390685508257
[I 2024-04-22 02:42:42,617] Trial 9 finished with value: 0.20354235640906712 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-22 02:42:48,822] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.22667865765971248
Fold 2 IBS: 0.18386911210968868
Fold 3 IBS: 0.19650770014771463
Fold 4 IBS: 0.20835591158437963
Fold 5 IBS: 0.203472559428523
[I 2024-04-22 02:42:50,280] Trial 11 finished with value: 0.20377678818600367 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.23112230630238642
Fold 2 IBS: 0.1674454512633998
Fold 3 IBS: 0.19855471836895786
Fold 4 IBS: 0.1938632953802893
Fold 5 IBS: 0.18962922951564953
[I 2024-04-22 02:42:50,564] Trial 12 finished with value: 0.1961230001661366 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2413073544619049
Fold 2 IBS: 0.1811958871683442
Fold 3 IBS: 0.22244250686987974
Fold 4 IBS: 0.19750724899733643
Fold 5 IBS: 0.18232843513858982
[I 2024-04-22 02:42:50,848] Trial 13 finished with value: 0.20495628652721104 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 5 with value: 0.1929397918771159.
Fold 1 IBS: 0.2242647329441179
Fold 2 IBS: 0.17883999941146664
Fold 3 IBS: 0.1918443810565798
Fold 4 IBS: 0.19214931253213374
Fold 5 IBS: 0.1731968530886853
[I 2024-04-22 02:42:53,508] Trial 14 finished with value: 0.19205905580659666 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.6604916334814492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2288883257443599
Fold 2 IBS: 0.1738046533368976
Fold 3 IBS: 0.1959496843821166
Fold 4 IBS: 0.19095725701045163
Fold 5 IBS: 0.18213576812388554
[I 2024-04-22 02:42:55,987] Trial 15 finished with value: 0.19434713771954226 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.9870260431565661, 'max_features': 'log2', 'min_weight_fraction_leaf': 2.174000731099135e-05}. Best is trial 14 with value: 0.19205905580659666.

Fold 1 IBS: 0.221052045952944
Fold 2 IBS: 0.17864590278571793
Fold 3 IBS: 0.20121068717993237
Fold 4 IBS: 0.19156051442456593
Fold 5 IBS: 0.18700261900559814
[I 2024-04-22 02:42:59,132] Trial 16 finished with value: 0.19589435386975168 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 354, 'oob_score': False, 'max_samples': 0.6248405086569909, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.054994509022204895}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.24661458596136437
Fold 2 IBS: 0.23231122477788718
Fold 3 IBS: 0.229689256646579
Fold 4 IBS: 0.2413341340131506
Fold 5 IBS: 0.2302248378800009
[I 2024-04-22 02:43:00,764] Trial 17 finished with value: 0.23603480785579642 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 225, 'oob_score': False, 'max_samples': 0.39119490979325144, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.27799606575272795}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.222887661575006
Fold 2 IBS: 0.18421435942452744
Fold 3 IBS: 0.19421453594382496
Fold 4 IBS: 0.19981786115023864
Fold 5 IBS: 0.1912096155424649
[I 2024-04-22 02:43:02,270] Trial 18 finished with value: 0.1984688067272124 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.21062982570611943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05734145926999751}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22047405758964184
Fold 2 IBS: 0.1966030079539471
Fold 3 IBS: 0.21350757148135177
Fold 4 IBS: 0.20455158700455836
Fold 5 IBS: 0.2019153339379839
[I 2024-04-22 02:43:04,498] Trial 19 finished with value: 0.20741031159349657 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.4386108822397098, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17720383372155285}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2203832582181566
Fold 2 IBS: 0.19931517540854854
Fold 3 IBS: 0.21442829878986364
Fold 4 IBS: 0.2069356513930878
Fold 5 IBS: 0.20374628014066523
[I 2024-04-22 02:43:09,087] Trial 20 finished with value: 0.20896173279006436 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.6164262808144682, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24472699218520227}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.2275442075846795
Fold 2 IBS: 0.17484137550996653
Fold 3 IBS: 0.19334185644794946
Fold 4 IBS: 0.19132538175744745
Fold 5 IBS: 0.18115113844013128
[I 2024-04-22 02:43:11,759] Trial 21 finished with value: 0.19364079194803485 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 281, 'oob_score': False, 'max_samples': 0.9621081290297763, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.01052588707306133}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.23054333285986953
Fold 2 IBS: 0.1724746302154596
Fold 3 IBS: 0.20261710681612344
Fold 4 IBS: 0.1926073795425933
Fold 5 IBS: 0.18185095277627958
[I 2024-04-22 02:43:14,143] Trial 22 finished with value: 0.1960186804420651 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 256, 'oob_score': False, 'max_samples': 0.9874289067540774, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.012068014135528271}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22601236961439128
Fold 2 IBS: 0.17969996069427818
Fold 3 IBS: 0.19876167471795514
Fold 4 IBS: 0.196787842235057
Fold 5 IBS: 0.18785036721027695
[I 2024-04-22 02:43:16,842] Trial 23 finished with value: 0.19782244289439171 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 308, 'oob_score': False, 'max_samples': 0.8598545784448618, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08754103994167567}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22736870474237106
Fold 2 IBS: 0.17759080498432794
Fold 3 IBS: 0.1907220147867818
Fold 4 IBS: 0.19684291499550113
Fold 5 IBS: 0.173335537233157
[I 2024-04-22 02:43:19,211] Trial 24 finished with value: 0.19317199534842777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 171, 'oob_score': False, 'max_samples': 0.7977844441295365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03359112238003443}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22154369312237301
Fold 2 IBS: 0.17529814117915438
Fold 3 IBS: 0.19940916065427428
Fold 4 IBS: 0.19644777061534635
Fold 5 IBS: 0.18432305180010988
[I 2024-04-22 02:43:21,004] Trial 25 finished with value: 0.19540436347425158 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 172, 'oob_score': False, 'max_samples': 0.7991522227764232, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11631986143324591}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21676007374411307
Fold 2 IBS: 0.17824797677237728
Fold 3 IBS: 0.20701000107269518
Fold 4 IBS: 0.19291445170373886
Fold 5 IBS: 0.19374462748985236
[I 2024-04-22 02:43:22,845] Trial 26 finished with value: 0.19773542615655534 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 182, 'oob_score': True, 'max_samples': 0.6679645097491387, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.038185359995283503}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21502992986795352
Fold 2 IBS: 0.1870308796226911
Fold 3 IBS: 0.2076665120334582
Fold 4 IBS: 0.19610467365474676
Fold 5 IBS: 0.2006394525445189
[I 2024-04-22 02:43:25,898] Trial 27 finished with value: 0.2012942895446737 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 402, 'oob_score': False, 'max_samples': 0.4929150044278433, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15117671554446085}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22061913161771582
Fold 2 IBS: 0.1760211535374804
Fold 3 IBS: 0.1985451645372839
Fold 4 IBS: 0.1895387815583719
Fold 5 IBS: 0.18196669319802622
[I 2024-04-22 02:43:28,076] Trial 28 finished with value: 0.19333818488977564 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.7046067597565696, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08480904388715302}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.21738957168254863
Fold 2 IBS: 0.18629216965440445
Fold 3 IBS: 0.23966304898222662
Fold 4 IBS: 0.21639319543648572
Fold 5 IBS: 0.21400347731487693
[I 2024-04-22 02:43:29,106] Trial 29 finished with value: 0.2147482926141085 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 114, 'oob_score': False, 'max_samples': 0.6118767285087061, 'max_features': None, 'min_weight_fraction_leaf': 0.21149318025001101}. Best is trial 14 with value: 0.19205905580659666.
Fold 1 IBS: 0.22758569118959
Fold 2 IBS: 0.1745807047630518
Fold 3 IBS: 0.19331240272244285
Fold 4 IBS: 0.19188841853726443
Fold 5 IBS: 0.17272789020296123
[I 2024-04-22 02:43:32,479] Trial 30 finished with value: 0.19201902148306207 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.770559095997367, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.027011468511437653}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22584092896742133
Fold 2 IBS: 0.17585075081924822
Fold 3 IBS: 0.1972070156814071
Fold 4 IBS: 0.18881994130282825

Fold 5 IBS: 0.17585992091527558
[I 2024-04-22 02:43:35,674] Trial 31 finished with value: 0.19271571153723607 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.7600957156160437, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.045073432551245296}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22236771464371266
Fold 2 IBS: 0.17701546684229433
Fold 3 IBS: 0.19851905347240079
Fold 4 IBS: 0.18732302760178435
Fold 5 IBS: 0.18167933628393707
[I 2024-04-22 02:43:39,920] Trial 32 finished with value: 0.19338091976882582 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 394, 'oob_score': False, 'max_samples': 0.6752379846937863, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07718385932974292}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2270170034083123
Fold 2 IBS: 0.1795970779202372
Fold 3 IBS: 0.19695809379393509
Fold 4 IBS: 0.1963645526898038
Fold 5 IBS: 0.18960590139682051
[I 2024-04-22 02:43:42,885] Trial 33 finished with value: 0.19790852584182178 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 319, 'oob_score': False, 'max_samples': 0.7392038686189389, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050681546729188336}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22913107555986495
Fold 2 IBS: 0.1713200021524253
Fold 3 IBS: 0.20174276009751624
Fold 4 IBS: 0.19170526770572746
Fold 5 IBS: 0.18122337614028983
[I 2024-04-22 02:43:46,620] Trial 34 finished with value: 0.19502449633116475 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8878735229014442, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10769272272367647}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2263994177575451
Fold 2 IBS: 0.1782493853587001
Fold 3 IBS: 0.19967435367391417
Fold 4 IBS: 0.18957084972922195
Fold 5 IBS: 0.1806713908816942
[I 2024-04-22 02:43:52,378] Trial 35 finished with value: 0.1949130794802151 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.5635984815237928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.031068687969102886}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2140834251920096
Fold 2 IBS: 0.18302541234920544
Fold 3 IBS: 0.20583049051646687
Fold 4 IBS: 0.19225672545423975
Fold 5 IBS: 0.1950395683265298
[I 2024-04-22 02:43:55,168] Trial 36 finished with value: 0.19804712436769029 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.6797083197848384, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16437366905173617}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2232352512407339
Fold 2 IBS: 0.1768499163180223
Fold 3 IBS: 0.20266000918435328
Fold 4 IBS: 0.19138188589544256
Fold 5 IBS: 0.18665967315448365
[I 2024-04-22 02:43:58,469] Trial 37 finished with value: 0.19615734715860716 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.7779331709919757, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13312369867225185}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.24610665966261314
Fold 2 IBS: 0.23223155236224916
Fold 3 IBS: 0.22952300914119636
Fold 4 IBS: 0.2414811194823906
Fold 5 IBS: 0.23018872339055935
[I 2024-04-22 02:44:02,439] Trial 38 finished with value: 0.23590621280780172 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 422, 'oob_score': True, 'max_samples': 0.48580268101444124, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22481799036239483
Fold 2 IBS: 0.17685147774699653
Fold 3 IBS: 0.20049010291951425
Fold 4 IBS: 0.18982857043914958
Fold 5 IBS: 0.18254203063054433
[I 2024-04-22 02:44:06,233] Trial 39 finished with value: 0.1949060344197199 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.5843062137973745, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07067430477200148}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.2466142294056291
Fold 2 IBS: 0.23220067379443807
Fold 3 IBS: 0.22953256065286004
Fold 4 IBS: 0.24149352725075382
Fold 5 IBS: 0.23034005575836422
[I 2024-04-22 02:44:08,734] Trial 40 finished with value: 0.23603620937240904 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 327, 'oob_score': False, 'max_samples': 0.6533926233121279, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3997341974880029}. Best is trial 30 with value: 0.19201902148306207.
Fold 1 IBS: 0.22008661582176534
Fold 2 IBS: 0.17191458989661332
Fold 3 IBS: 0.19041182470823828
Fold 4 IBS: 0.1994085393279668
Fold 5 IBS: 0.17049962251252426
[I 2024-04-22 02:44:11,105] Trial 41 finished with value: 0.19046423845342159 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 196, 'oob_score': False, 'max_samples': 0.8079255109979475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03389223938021847}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.22280111750039264
Fold 2 IBS: 0.17796243072588608
Fold 3 IBS: 0.18962417076714974
Fold 4 IBS: 0.19463536301610113
Fold 5 IBS: 0.17836205501155145
[I 2024-04-22 02:44:12,976] Trial 42 finished with value: 0.19267702740421622 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 204, 'oob_score': False, 'max_samples': 0.7310718829833422, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.029447700275051822}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.24650381632587262
Fold 2 IBS: 0.23211797085492242
Fold 3 IBS: 0.22955740353559057
Fold 4 IBS: 0.24157053900567507
Fold 5 IBS: 0.23027910552347802
[I 2024-04-22 02:44:14,556] Trial 43 finished with value: 0.23600576704910775 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 202, 'oob_score': False, 'max_samples': 0.9068225316738959, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.2272741837619837
Fold 2 IBS: 0.18010040335739258
Fold 3 IBS: 0.18917888351764922
Fold 4 IBS: 0.19497471406918135
Fold 5 IBS: 0.17759835230906024
[I 2024-04-22 02:44:17,094] Trial 44 finished with value: 0.19382530740305343 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.8278518214882832, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.032724850462757596}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.21818859674129706
Fold 2 IBS: 0.19182889723265809
Fold 3 IBS: 0.20645079219948698
Fold 4 IBS: 0.2039075995565362
Fold 5 IBS: 0.20251751001463825
[I 2024-04-22 02:44:19,176] Trial 45 finished with value: 0.2045786791489233 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.7211266599729008, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0184904067184055}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.24605956999356746
Fold 2 IBS: 0.1715522843932026
Fold 3 IBS: 0.22997512987796287
Fold 4 IBS: 0.2114434138594334
Fold 5 IBS: 0.20680985045195013
[I 2024-04-22 02:44:23,163] Trial 46 finished with value: 0.2131680497152233 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'max_samples': 0.8319888092703853, 'max_features': None, 'min_weight_fraction_leaf': 0.0015300457559763413}. Best is trial 41 with value: 0.19046423845342159.

Fold 1 IBS: 0.22670665484519142
Fold 2 IBS: 0.175184981867077
Fold 3 IBS: 0.20276219990812896
Fold 4 IBS: 0.19658107727261281
Fold 5 IBS: 0.17640448174832232
[I 2024-04-22 02:44:24,859] Trial 47 finished with value: 0.1955278791282665 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.7533756239183884, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05433383705425634}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.21833683794653208
Fold 2 IBS: 0.16845072186321247
Fold 3 IBS: 0.20168040343516955
Fold 4 IBS: 0.1937674426294509
Fold 5 IBS: 0.19051837676249267
[I 2024-04-22 02:44:25,682] Trial 48 finished with value: 0.19455075652737155 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 82, 'oob_score': False, 'max_samples': 0.7075209195984526, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10074510594123325}. Best is trial 41 with value: 0.19046423845342159.
Fold 1 IBS: 0.22242522647319046
Fold 2 IBS: 0.17089945636142403
Fold 3 IBS: 0.195613872409514
Fold 4 IBS: 0.18922142541007175
Fold 5 IBS: 0.17303791504234847
[I 2024-04-22 02:44:27,817] Trial 49 finished with value: 0.19023957913930975 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.7890788621794695, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04458702793409107}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22555617401744368
Fold 2 IBS: 0.17741085594825706
Fold 3 IBS: 0.20242485916185912
Fold 4 IBS: 0.19387487722329108
Fold 5 IBS: 0.18754644311102073
[I 2024-04-22 02:44:29,900] Trial 50 finished with value: 0.19736264189237435 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 220, 'oob_score': False, 'max_samples': 0.8555734953303252, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14147922592542847}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21627803680039687
Fold 2 IBS: 0.18166264021393835
Fold 3 IBS: 0.2092710829548924
Fold 4 IBS: 0.19595939612381622
Fold 5 IBS: 0.2011472544518922
[I 2024-04-22 02:44:31,860] Trial 51 finished with value: 0.20086368210898717 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.792480439746047, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04337189753109918}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22826690607978067
Fold 2 IBS: 0.17514993464852044
Fold 3 IBS: 0.19499180688840081
Fold 4 IBS: 0.19607308855822925
Fold 5 IBS: 0.1785126372364033
[I 2024-04-22 02:44:34,062] Trial 52 finished with value: 0.1945988746822669 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.7551979832732026, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0695275941074916}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2272968554576038
Fold 2 IBS: 0.1698341110510439
Fold 3 IBS: 0.19814117513373936
Fold 4 IBS: 0.20422983853085452
Fold 5 IBS: 0.16857687543461305
[I 2024-04-22 02:44:35,566] Trial 53 finished with value: 0.19361577112157094 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.9323805201970561, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024719341884636734}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22481757046708095
Fold 2 IBS: 0.17677433524674352
Fold 3 IBS: 0.19744731736557988
Fold 4 IBS: 0.1900684049643577
Fold 5 IBS: 0.17563795002659072
[I 2024-04-22 02:44:38,090] Trial 54 finished with value: 0.19294911561407058 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.7054751660094117, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05861070426347463}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22109268216759362
Fold 2 IBS: 0.1795317897821966
Fold 3 IBS: 0.19864062457744264
Fold 4 IBS: 0.1887540514309438
Fold 5 IBS: 0.18579795261641194
[I 2024-04-22 02:44:40,221] Trial 55 finished with value: 0.1947634201149177 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 257, 'oob_score': False, 'max_samples': 0.6301567839071449, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08753416190089439}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23313488896504717
Fold 2 IBS: 0.19865251149482616
Fold 3 IBS: 0.20707690430687525
Fold 4 IBS: 0.20382506127552455
Fold 5 IBS: 0.20806640771791665
[I 2024-04-22 02:44:43,477] Trial 56 finished with value: 0.21015115475203797 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.8215366083160163, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.021781106435660526}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.251405085227788
Fold 2 IBS: 0.17971245840591804
Fold 3 IBS: 0.20892416859276688
Fold 4 IBS: 0.2096604234179674
Fold 5 IBS: 0.18424709009072612
[I 2024-04-22 02:44:46,283] Trial 57 finished with value: 0.20678984514703327 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.8705287129013517, 'max_features': None, 'min_weight_fraction_leaf': 0.04455613136763016}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22775475401909703
Fold 2 IBS: 0.17495565316697842
Fold 3 IBS: 0.20607913041505693
Fold 4 IBS: 0.19159948662275345
Fold 5 IBS: 0.18048871793748186
[I 2024-04-22 02:44:48,376] Trial 58 finished with value: 0.19617554843227353 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.9463423717095281, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1156031725017496}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22758477258081827
Fold 2 IBS: 0.17158899508130857
Fold 3 IBS: 0.19616659435415607
Fold 4 IBS: 0.19199468063765252
Fold 5 IBS: 0.17000810523027976
[I 2024-04-22 02:44:52,221] Trial 59 finished with value: 0.19146862957684302 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.7604421792719349, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003738110192922882}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22873607517785616
Fold 2 IBS: 0.17390045472096774
Fold 3 IBS: 0.19717465713467122
Fold 4 IBS: 0.19069798125902654
Fold 5 IBS: 0.16839044559038258
[I 2024-04-22 02:44:55,974] Trial 60 finished with value: 0.19177992277658085 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.8025318592826676, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0035012585111243765}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23001446011337487
Fold 2 IBS: 0.17351898966358764
Fold 3 IBS: 0.19693929350409167
Fold 4 IBS: 0.19025194043534524
Fold 5 IBS: 0.16918574368972547
[I 2024-04-22 02:44:59,688] Trial 61 finished with value: 0.19198208548122497 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 304, 'oob_score': False, 'max_samples': 0.7900678450377102, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00572289564152078}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22738806352311317
Fold 2 IBS: 0.17362132403038696
Fold 3 IBS: 0.19727565424618765
Fold 4 IBS: 0.19024256592293678

Fold 5 IBS: 0.16839194066878888
[I 2024-04-22 02:45:02,912] Trial 62 finished with value: 0.1913839096782827 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.8075940187858324, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0028869935676452026}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22802304509837604
Fold 2 IBS: 0.17093887708958988
Fold 3 IBS: 0.19997810028764312
Fold 4 IBS: 0.19416891669551373
Fold 5 IBS: 0.16864914160971897
[I 2024-04-22 02:45:05,901] Trial 63 finished with value: 0.19235161615616833 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.899801190989709, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0075083578814244606}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22706249643509485
Fold 2 IBS: 0.1740741132334453
Fold 3 IBS: 0.1982770517299122
Fold 4 IBS: 0.1942932217810348
Fold 5 IBS: 0.17209778370511547
[I 2024-04-22 02:45:08,758] Trial 64 finished with value: 0.1931609333769205 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 336, 'oob_score': False, 'max_samples': 0.8279032572597822, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0005239520819106591}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2249627623000506
Fold 2 IBS: 0.17734214004526475
Fold 3 IBS: 0.20042821363889923
Fold 4 IBS: 0.19132512948604202
Fold 5 IBS: 0.17992503554600825
[I 2024-04-22 02:45:11,324] Trial 65 finished with value: 0.19479665620325298 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7929889902503702, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0003379495295398175}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2258580567600176
Fold 2 IBS: 0.1725987117538336
Fold 3 IBS: 0.19691363075454665
Fold 4 IBS: 0.19294818573115283
Fold 5 IBS: 0.16674549590339433
[I 2024-04-22 02:45:14,702] Trial 66 finished with value: 0.191012816180589 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 300, 'oob_score': False, 'max_samples': 0.8542677970427669, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02018893978213555}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22715985053253537
Fold 2 IBS: 0.175194067127973
Fold 3 IBS: 0.20235598060063445
Fold 4 IBS: 0.1915473606751296
Fold 5 IBS: 0.17533957463955674
[I 2024-04-22 02:45:18,445] Trial 67 finished with value: 0.19431936671516584 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.8537028925191168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06691183155682784}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2276240233573705
Fold 2 IBS: 0.17466029156341425
Fold 3 IBS: 0.19585094966145308
Fold 4 IBS: 0.1956019894346285
Fold 5 IBS: 0.17236600002537372
[I 2024-04-22 02:45:21,996] Trial 68 finished with value: 0.19322065080844802 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 240, 'oob_score': False, 'max_samples': 0.8153568706687296, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020589797791063878}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2300113020332438
Fold 2 IBS: 0.1687511692442822
Fold 3 IBS: 0.200433873197082
Fold 4 IBS: 0.19350383522262551
Fold 5 IBS: 0.1749683856491631
[I 2024-04-22 02:45:26,318] Trial 69 finished with value: 0.1935337130692793 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 357, 'oob_score': False, 'max_samples': 0.9627183310414489, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04180485598378051}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21313163321533152
Fold 2 IBS: 0.18353505015435204
Fold 3 IBS: 0.21120737776495918
Fold 4 IBS: 0.19490170617054509
Fold 5 IBS: 0.19862473265977015
[I 2024-04-22 02:45:29,570] Trial 70 finished with value: 0.2002800999929916 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.9259785083383683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.26527703823768367}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22671408988493402
Fold 2 IBS: 0.17109357051379762
Fold 3 IBS: 0.19869894342562636
Fold 4 IBS: 0.1930683536390453
Fold 5 IBS: 0.1684970080938331
[I 2024-04-22 02:45:32,043] Trial 71 finished with value: 0.19161439311144726 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.8750321012509876, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016570826484099625}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22688669905527847
Fold 2 IBS: 0.17075390562804646
Fold 3 IBS: 0.1985253537047414
Fold 4 IBS: 0.19308404898587175
Fold 5 IBS: 0.16784784499547226
[I 2024-04-22 02:45:34,289] Trial 72 finished with value: 0.19141957047388206 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 232, 'oob_score': False, 'max_samples': 0.8727329170058532, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014958115304314575}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22972629414025617
Fold 2 IBS: 0.1714974106484998
Fold 3 IBS: 0.19533970259706934
Fold 4 IBS: 0.19369830153535858
Fold 5 IBS: 0.17274176927442175
[I 2024-04-22 02:45:36,845] Trial 73 finished with value: 0.19260069563912113 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.8762219604530712, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017456169974200266}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22245678083193057
Fold 2 IBS: 0.17710628298553246
Fold 3 IBS: 0.2034119116741666
Fold 4 IBS: 0.19479658460004864
Fold 5 IBS: 0.19147425591218886
[I 2024-04-22 02:45:39,365] Trial 74 finished with value: 0.19784916320077342 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 235, 'oob_score': False, 'max_samples': 0.8496697690131644, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06167959702360663}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22047766774477437
Fold 2 IBS: 0.19344669693934774
Fold 3 IBS: 0.21000391860404677
Fold 4 IBS: 0.20477338938353398
Fold 5 IBS: 0.20541683976071617
[I 2024-04-22 02:45:41,330] Trial 75 finished with value: 0.2068237024864838 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 228, 'oob_score': False, 'max_samples': 0.890700122872072, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3160611948377179}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22684996172732363
Fold 2 IBS: 0.17136700641226504
Fold 3 IBS: 0.20076384707932607
Fold 4 IBS: 0.19600823288434543
Fold 5 IBS: 0.17509643852531095
[I 2024-04-22 02:45:44,439] Trial 76 finished with value: 0.19401709732571423 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.963490685502655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03671779555332485}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22243091080935176
Fold 2 IBS: 0.17909250139952151
Fold 3 IBS: 0.2011051393467259
Fold 4 IBS: 0.1920426126768079
Fold 5 IBS: 0.19402260004185645
[I 2024-04-22 02:45:45,887] Trial 77 finished with value: 0.1977387528548527 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.331919983653197, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07824582320277648}. Best is trial 49 with value: 0.19023957913930975.

Fold 1 IBS: 0.22661384896598818
Fold 2 IBS: 0.20671937958697834
Fold 3 IBS: 0.22631312111115084
Fold 4 IBS: 0.21497952798665046
Fold 5 IBS: 0.21282749449450544
[I 2024-04-22 02:45:48,182] Trial 78 finished with value: 0.21749067442905465 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.9147835512625551, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.43785214928176214}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23052477127318172
Fold 2 IBS: 0.16982397129659127
Fold 3 IBS: 0.197745679074635
Fold 4 IBS: 0.19675496948041768
Fold 5 IBS: 0.1770213286573074
[I 2024-04-22 02:45:52,744] Trial 79 finished with value: 0.1943741439564266 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 275, 'oob_score': False, 'max_samples': 0.9974228392350986, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.013882614482266749}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.21778031450040175
Fold 2 IBS: 0.18157476210786558
Fold 3 IBS: 0.20901936393117487
Fold 4 IBS: 0.19843253192688598
Fold 5 IBS: 0.20260500447363683
[I 2024-04-22 02:45:54,811] Trial 80 finished with value: 0.201882395387993 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 196, 'oob_score': False, 'max_samples': 0.8074163719785258, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2343729610964786}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.23020712569648552
Fold 2 IBS: 0.17016574705246248
Fold 3 IBS: 0.19437724163558126
Fold 4 IBS: 0.19048729146333454
Fold 5 IBS: 0.16923782983271543
[I 2024-04-22 02:45:57,412] Trial 81 finished with value: 0.19089504713611585 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 302, 'oob_score': False, 'max_samples': 0.7784763388289013, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010595244727030426}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22633537924660144
Fold 2 IBS: 0.17245435825621444
Fold 3 IBS: 0.198261807277501
Fold 4 IBS: 0.19375808006799025
Fold 5 IBS: 0.17259241286993124
[I 2024-04-22 02:46:00,421] Trial 82 finished with value: 0.19268040754364765 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8431704918534557, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051048753251538945}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22652319655125724
Fold 2 IBS: 0.17122256301203548
Fold 3 IBS: 0.19686503258087146
Fold 4 IBS: 0.1924915525324402
Fold 5 IBS: 0.16992775902187662
[I 2024-04-22 02:46:02,860] Trial 83 finished with value: 0.1914060207396962 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 211, 'oob_score': False, 'max_samples': 0.8754608137046987, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.015226300624484834}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22719481979011316
Fold 2 IBS: 0.17681042979834713
Fold 3 IBS: 0.19352861064606583
Fold 4 IBS: 0.19070454017783864
Fold 5 IBS: 0.17349666127523256
[I 2024-04-22 02:46:05,062] Trial 84 finished with value: 0.19234701233751947 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 217, 'oob_score': False, 'max_samples': 0.8790183350095053, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0330313828916208}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2284060883547397
Fold 2 IBS: 0.17419251077518969
Fold 3 IBS: 0.19970363198080762
Fold 4 IBS: 0.19473581568220244
Fold 5 IBS: 0.176828897729793
[I 2024-04-22 02:46:07,414] Trial 85 finished with value: 0.19477338890454649 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.7631874187375279, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01872628122372143}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22305736755182187
Fold 2 IBS: 0.17574939085892582
Fold 3 IBS: 0.19568084111601947
Fold 4 IBS: 0.19164045666660487
Fold 5 IBS: 0.1705187427582713
[I 2024-04-22 02:46:09,571] Trial 86 finished with value: 0.19132935979032867 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.74503188520459, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.049354259957534494}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2240633369122398
Fold 2 IBS: 0.17538320131641633
Fold 3 IBS: 0.19866223365506058
Fold 4 IBS: 0.19055945999140522
Fold 5 IBS: 0.17899242470900267
[I 2024-04-22 02:46:11,654] Trial 87 finished with value: 0.19353213131682495 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 188, 'oob_score': False, 'max_samples': 0.7394132698699142, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09171826513128181}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22531436049097633
Fold 2 IBS: 0.17338649398202335
Fold 3 IBS: 0.19541984829438955
Fold 4 IBS: 0.19633643985222626
Fold 5 IBS: 0.17132056753628644
[I 2024-04-22 02:46:13,977] Trial 88 finished with value: 0.19235554203118038 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.7818271131584801, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04741359111187626}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.24634541122033987
Fold 2 IBS: 0.2321226179655187
Fold 3 IBS: 0.22957248320549392
Fold 4 IBS: 0.24133401177007524
Fold 5 IBS: 0.22999623321892046
[I 2024-04-22 02:46:15,330] Trial 89 finished with value: 0.23587415147606966 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 167, 'oob_score': False, 'max_samples': 0.15094844814066605, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18451336087256687}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22279933131837096
Fold 2 IBS: 0.17181835390229477
Fold 3 IBS: 0.2007160874798753
Fold 4 IBS: 0.197203380481848
Fold 5 IBS: 0.17515803600889934
[I 2024-04-22 02:46:16,604] Trial 90 finished with value: 0.19353903783825768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 129, 'oob_score': False, 'max_samples': 0.7242871632922839, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06749203999049488}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22424300030428562
Fold 2 IBS: 0.17328433759407055
Fold 3 IBS: 0.19523917924376888
Fold 4 IBS: 0.19315716958653814
Fold 5 IBS: 0.1704614508554719
[I 2024-04-22 02:46:18,744] Trial 91 finished with value: 0.19127702751682701 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 229, 'oob_score': False, 'max_samples': 0.8334209164391518, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014138517009539523}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22184929782482737
Fold 2 IBS: 0.17627486877830942
Fold 3 IBS: 0.1943876201108137
Fold 4 IBS: 0.19108122099131164
Fold 5 IBS: 0.17147705560864723
[I 2024-04-22 02:46:22,089] Trial 92 finished with value: 0.19101401266278187 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.6946552112995523, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03125200733960136}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2239870857063055
Fold 2 IBS: 0.17944345181206486
Fold 3 IBS: 0.1900538617099537
Fold 4 IBS: 0.19293425732594438

Fold 5 IBS: 0.16901501941163646
[I 2024-04-22 02:46:24,501] Trial 93 finished with value: 0.19108673519318098 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 179, 'oob_score': False, 'max_samples': 0.8387093701884653, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030817946786640082}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22184856220737365
Fold 2 IBS: 0.17312992964385657
Fold 3 IBS: 0.1948930255496256
Fold 4 IBS: 0.1925411854591036
Fold 5 IBS: 0.1730631403095586
[I 2024-04-22 02:46:26,460] Trial 94 finished with value: 0.1910951686339036 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.688472014648766, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03451598429298541}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.24047052597810953
Fold 2 IBS: 0.17250441339722747
Fold 3 IBS: 0.20953833222155935
Fold 4 IBS: 0.2100206291818941
Fold 5 IBS: 0.17584248631889507
[I 2024-04-22 02:46:28,822] Trial 95 finished with value: 0.2016752774195371 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.6970192006469513, 'max_features': None, 'min_weight_fraction_leaf': 0.03192478980412634}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2258454786784926
Fold 2 IBS: 0.17622029117710752
Fold 3 IBS: 0.19704459447649766
Fold 4 IBS: 0.18859439451234322
Fold 5 IBS: 0.17741716444849034
[I 2024-04-22 02:46:32,519] Trial 96 finished with value: 0.19302438465858626 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.6860275498472574, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05374102069256326}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.22481323122042657
Fold 2 IBS: 0.17216098643824315
Fold 3 IBS: 0.19306385345921517
Fold 4 IBS: 0.19583934030263228
Fold 5 IBS: 0.17882594481487218
[I 2024-04-22 02:46:34,139] Trial 97 finished with value: 0.19294067124707787 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 159, 'oob_score': False, 'max_samples': 0.6513894290159268, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04184810194054517}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2281068681622065
Fold 2 IBS: 0.17408803145260857
Fold 3 IBS: 0.19824195355773988
Fold 4 IBS: 0.1904600456326597
Fold 5 IBS: 0.17922094521554732
[I 2024-04-22 02:46:37,619] Trial 98 finished with value: 0.1940235688041524 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.7342462417517636, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07703075927677872}. Best is trial 49 with value: 0.19023957913930975.
Fold 1 IBS: 0.2259945894827042
Fold 2 IBS: 0.17396367577577646
Fold 3 IBS: 0.2055533021506421
Fold 4 IBS: 0.1955608834617829
Fold 5 IBS: 0.1805672129301506
[I 2024-04-22 02:46:39,479] Trial 99 finished with value: 0.19632793276021127 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 153, 'oob_score': False, 'max_samples': 0.8324527674106177, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09813787485590943}. Best is trial 49 with value: 0.19023957913930975.


* Best trial for IBS:
 FrozenTrial(number=49, state=TrialState.COMPLETE, values=[0.19023957913930975], datetime_start=datetime.datetime(2024, 4, 22, 2, 44, 25, 687212), datetime_complete=datetime.datetime(2024, 4, 22, 2, 44, 27, 817035), params={'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 215, 'oob_score': False, 'max_samples': 0.7890788621794695, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04458702793409107}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=49, value=None)


* Best Score for IBS:
 0.19023957913930975

In [55]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [56]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.866
train_ibs:  0.19

#### Test

In [57]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [58]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=10, max_leaf_nodes=14,
                     max_samples=0.8746458616251406, min_samples_leaf=2,
                     min_weight_fraction_leaf=0.030922977401692878,
                     n_estimators=113, random_state=123, warm_start=True)

test_cindex:  0.546

RandomSurvivalForest(max_depth=8, max_leaf_nodes=17,
                     max_samples=0.7890788621794695, min_samples_leaf=2,
                     min_samples_split=2,
                     min_weight_fraction_leaf=0.04458702793409107,
                     n_estimators=215, random_state=123)

test_ibs:  0.263

In [59]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [86]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [87]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 09:24:02,741] A new study created in memory with name: no-name-071fecac-7b3d-40ad-847e-dd2aa53d807f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7639484978540773
[I 2024-04-22 09:24:03,325] Trial 0 finished with value: 0.7623102721396274 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:24:04,594] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 09:24:07,223] Trial 2 finished with value: 0.7156366754220176 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7253218884120172
[I 2024-04-22 09:24:07,441] Trial 3 finished with value: 0.7402725229380251 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:24:08,471] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:24:09,458] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7381974248927039
[I 2024-04-22 09:24:10,023] Trial 6 finished with value: 0.7499745725457844 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 09:24:11,378] Trial 7 finished with value: 0.744770291905024 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7296137339055794
[I 2024-04-22 09:24:11,465] Trial 8 finished with value: 0.7197332454598995 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 09:24:14,891] Trial 9 finished with value: 0.7117523204127156 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:24:16,114] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:24:16,756] Trial 11 finished with value: 0.7295841326588206 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7623102721396274.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8111587982832618
[I 2024-04-22 09:24:17,597] Trial 12 finished with value: 0.7867972827001483 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:24:18,281] Trial 13 finished with value: 0.7316705235163293 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:24:18,830] Trial 14 finished with value: 0.7390987799796523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:24:19,257] Trial 15 finished with value: 0.7406634812581807 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7867972827001483.

Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6759656652360515
[I 2024-04-22 09:24:19,994] Trial 16 finished with value: 0.7032137338705444 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 09:24:20,456] Trial 17 finished with value: 0.731554986493769 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:24:21,187] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 09:24:21,724] Trial 19 finished with value: 0.7358463917100135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8361702127659575
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6630901287553648
[I 2024-04-22 09:24:21,796] Trial 20 finished with value: 0.7074965456605569 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7381974248927039
[I 2024-04-22 09:24:22,393] Trial 21 finished with value: 0.7550267044437244 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 09:24:23,288] Trial 22 finished with value: 0.7661315662080361 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7867972827001483.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8197424892703863
[I 2024-04-22 09:24:23,976] Trial 23 finished with value: 0.7937218312264874 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7424892703862661
[I 2024-04-22 09:24:24,675] Trial 24 finished with value: 0.7580764020718593 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 09:24:25,295] Trial 25 finished with value: 0.762803163214613 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 09:24:28,330] Trial 26 finished with value: 0.7223549195144154 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:24:29,010] Trial 27 finished with value: 0.7342711010948667 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7112403100775194
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 09:24:29,438] Trial 28 finished with value: 0.7193098171027112 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-22 09:24:29,884] Trial 29 finished with value: 0.7198566127686613 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 09:24:30,549] Trial 30 finished with value: 0.7622850722651587 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.7937218312264874.

Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 09:24:31,282] Trial 31 finished with value: 0.7651208885111453 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6357896182918609, 'min_weight_fraction_leaf': 0.043457520259011145}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7553648068669528
[I 2024-04-22 09:24:32,043] Trial 32 finished with value: 0.7493192073790584 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4847410905891233, 'min_weight_fraction_leaf': 0.054624644214656966}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:24:32,847] Trial 33 finished with value: 0.7351654028257627 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.527493679418052, 'min_weight_fraction_leaf': 0.11101292483370524}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8111587982832618
[I 2024-04-22 09:24:33,698] Trial 34 finished with value: 0.760702458675475 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 445, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9202590430146967, 'min_weight_fraction_leaf': 0.07023282430953717}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 09:24:35,213] Trial 35 finished with value: 0.7624993862330411 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6140705076527802, 'min_weight_fraction_leaf': 0.02925664606041241}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 09:24:37,176] Trial 36 finished with value: 0.719921700077874 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 349, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6785531388726883, 'min_weight_fraction_leaf': 0.1272251175690979}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 09:24:37,799] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8050041507306814, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 09:24:38,456] Trial 38 finished with value: 0.7247202242856303 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 2, 'n_estimators': 435, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.05649565215079118}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 09:24:41,683] Trial 39 finished with value: 0.7213553719700059 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 472, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5401322211198275, 'min_weight_fraction_leaf': 0.09113105544483305}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8197424892703863
[I 2024-04-22 09:24:42,158] Trial 40 finished with value: 0.7770575045494358 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7399942977302993, 'min_weight_fraction_leaf': 0.025013264992292644}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8497854077253219
[I 2024-04-22 09:24:42,523] Trial 41 finished with value: 0.7896617263093931 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7332367119565565, 'min_weight_fraction_leaf': 0.0016561031617871522}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:24:42,808] Trial 42 finished with value: 0.780595334917785 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 155, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7291601013114538, 'min_weight_fraction_leaf': 0.0015116719780719767}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:24:43,141] Trial 43 finished with value: 0.7901642333193999 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7528934931474498, 'min_weight_fraction_leaf': 0.007759295188642418}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 09:24:43,540] Trial 44 finished with value: 0.7872592837754979 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8327721232082076, 'min_weight_fraction_leaf': 0.01305046995423322}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:24:44,039] Trial 45 finished with value: 0.777513445436739 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 157, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8255054025331079, 'min_weight_fraction_leaf': 0.0031249321027524285}. Best is trial 23 with value: 0.7937218312264874.

Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:24:44,498] Trial 46 finished with value: 0.7917141970732431 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 198, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9257094805962044, 'min_weight_fraction_leaf': 0.022307192777154376}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 09:24:45,934] Trial 47 finished with value: 0.7453719568208577 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 196, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9265198018232372, 'min_weight_fraction_leaf': 0.05973916326993964}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7034883720930233
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 09:24:46,465] Trial 48 finished with value: 0.7193712893481361 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 121, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7632274813615122, 'min_weight_fraction_leaf': 0.3078000969326991}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.8148936170212766
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6802575107296137
[I 2024-04-22 09:24:46,891] Trial 49 finished with value: 0.7112005967373427 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 221, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9454880021924575, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8154506437768241
[I 2024-04-22 09:24:47,168] Trial 50 finished with value: 0.763269836859631 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 117, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.843804589889048, 'min_weight_fraction_leaf': 0.0873347394612367}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8497854077253219
[I 2024-04-22 09:24:47,541] Trial 51 finished with value: 0.7911199644131695 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 179, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.957889367228467, 'min_weight_fraction_leaf': 0.025973798263736272}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:24:47,890] Trial 52 finished with value: 0.7867595541571949 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7903103587545204, 'min_weight_fraction_leaf': 0.023179220994950622}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:24:48,101] Trial 53 finished with value: 0.7789155204597524 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 78, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.01957247755969179}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-22 09:24:48,494] Trial 54 finished with value: 0.7748590141721845 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8980357949184589, 'min_weight_fraction_leaf': 0.04833675638502302}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8068669527896996
[I 2024-04-22 09:24:48,814] Trial 55 finished with value: 0.7810021652909311 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 177, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8672614385579406, 'min_weight_fraction_leaf': 0.07284912883734934}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:24:49,082] Trial 56 finished with value: 0.7813968466847471 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 141, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8280080010077513, 'min_weight_fraction_leaf': 0.014205042834379285}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7081545064377682
[I 2024-04-22 09:24:49,478] Trial 57 finished with value: 0.7352517352068838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 247, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7559818229866901, 'min_weight_fraction_leaf': 0.12105610192383184}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.8
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7854077253218884
[I 2024-04-22 09:24:50,706] Trial 58 finished with value: 0.7495185198345575 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 223, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6819194445137657, 'min_weight_fraction_leaf': 0.0412960148860697}. Best is trial 23 with value: 0.7937218312264874.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 09:24:51,532] Trial 59 finished with value: 0.8084662710816808 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 271, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.964838395481847, 'min_weight_fraction_leaf': 4.407900941855603e-05}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 09:24:52,417] Trial 60 finished with value: 0.7300297987713386 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 274, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9553308503405183, 'min_weight_fraction_leaf': 0.2583710069782479}. Best is trial 59 with value: 0.8084662710816808.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8454935622317596
[I 2024-04-22 09:24:53,058] Trial 61 finished with value: 0.8006710951960759 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 191, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.99214746221766, 'min_weight_fraction_leaf': 0.00034340752043091755}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:24:53,855] Trial 62 finished with value: 0.7829099031334593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 194, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.995392611213117, 'min_weight_fraction_leaf': 0.03766384718061227}. Best is trial 59 with value: 0.8084662710816808.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 09:24:54,586] Trial 63 finished with value: 0.8166801836932367 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 231, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9159857443892336, 'min_weight_fraction_leaf': 0.000272750956431346}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:24:55,185] Trial 64 finished with value: 0.800657051922378 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 181, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9104584386149728, 'min_weight_fraction_leaf': 0.05591333445734158}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:24:55,843] Trial 65 finished with value: 0.7934970372032099 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9648986760030055, 'min_weight_fraction_leaf': 0.06680538576359879}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:24:56,499] Trial 66 finished with value: 0.7878220023993864 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 203, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9095982739365324, 'min_weight_fraction_leaf': 0.06752219873139698}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 09:24:57,330] Trial 67 finished with value: 0.7729438440738962 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 271, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8746455577810428, 'min_weight_fraction_leaf': 0.09750609016881821}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:24:58,126] Trial 68 finished with value: 0.7972745425406186 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 240, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.968180725622439, 'min_weight_fraction_leaf': 0.054110870458248334}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7296137339055794
[I 2024-04-22 09:24:58,900] Trial 69 finished with value: 0.7490725417029068 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 232, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.995297083745019, 'min_weight_fraction_leaf': 0.16115376582527763}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7682403433476395
[I 2024-04-22 09:25:01,131] Trial 70 finished with value: 0.7431377642689725 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9769199467223223, 'min_weight_fraction_leaf': 0.055426720208080725}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:25:01,826] Trial 71 finished with value: 0.8004580691916237 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9375782206126794, 'min_weight_fraction_leaf': 0.04507778368190728}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:25:02,599] Trial 72 finished with value: 0.7916358642120349 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9676798282975951, 'min_weight_fraction_leaf': 0.0787773084868472}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7424892703862661
[I 2024-04-22 09:25:03,305] Trial 73 finished with value: 0.7571821003409633 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 212, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8950935256166086, 'min_weight_fraction_leaf': 0.11229900026623069}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:25:04,175] Trial 74 finished with value: 0.795695654567296 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9359651513439894, 'min_weight_fraction_leaf': 0.05058223539315274}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8240343347639485
[I 2024-04-22 09:25:05,216] Trial 75 finished with value: 0.7939103516074585 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9343716260288816, 'min_weight_fraction_leaf': 0.043108638690303853}. Best is trial 63 with value: 0.8166801836932367.

Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-22 09:25:06,376] Trial 76 finished with value: 0.7784671388150444 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 286, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9321739716438541, 'min_weight_fraction_leaf': 0.03655310676155976}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-22 09:25:07,697] Trial 77 finished with value: 0.7875133994130215 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 254, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8655648399730119, 'min_weight_fraction_leaf': 0.04756050968696869}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7982832618025751
[I 2024-04-22 09:25:08,902] Trial 78 finished with value: 0.7817849347662374 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 269, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9999098672482281, 'min_weight_fraction_leaf': 0.0863331818418738}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-22 09:25:10,230] Trial 79 finished with value: 0.7456694044778016 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 303, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.034493408415334006}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 09:25:11,322] Trial 80 finished with value: 0.753005935291058 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 260, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9098917820806076, 'min_weight_fraction_leaf': 0.13389187501653388}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:25:11,946] Trial 81 finished with value: 0.8051772459148425 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9424018134336887, 'min_weight_fraction_leaf': 0.05108896602934009}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8497854077253219
[I 2024-04-22 09:25:13,014] Trial 82 finished with value: 0.809469091408405 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 282, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9410740612472716, 'min_weight_fraction_leaf': 0.012322578348389443}. Best is trial 63 with value: 0.8166801836932367.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 09:25:14,294] Trial 83 finished with value: 0.8167597780695852 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 285, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8871550861115998, 'min_weight_fraction_leaf': 0.013985838803987693}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-22 09:25:14,941] Trial 84 finished with value: 0.812474687015057 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 138, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8841264487793694, 'min_weight_fraction_leaf': 0.016386251952087417}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8540772532188842
[I 2024-04-22 09:25:15,649] Trial 85 finished with value: 0.8158908196342545 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 141, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.888479352560009, 'min_weight_fraction_leaf': 0.012716341560856033}. Best is trial 83 with value: 0.8167597780695852.
Fold 1 C-index: 0.6972111553784861
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8841201716738197
[I 2024-04-22 09:25:16,366] Trial 86 finished with value: 0.8257675162186733 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8608986608214496, 'min_weight_fraction_leaf': 0.013300177959391254}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7081545064377682
[I 2024-04-22 09:25:16,843] Trial 87 finished with value: 0.7417472944772566 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 91, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8607992629190876, 'min_weight_fraction_leaf': 0.01139343678306486}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.8025751072961373
[I 2024-04-22 09:25:17,805] Trial 88 finished with value: 0.7421126194553279 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 84, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8099246282391572, 'min_weight_fraction_leaf': 0.013604529607415802}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.701195219123506
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8626609442060086
[I 2024-04-22 09:25:18,549] Trial 89 finished with value: 0.8246591973761161 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 139, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8911664954143093, 'min_weight_fraction_leaf': 0.0010890713950365803}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-22 09:25:19,174] Trial 90 finished with value: 0.8093017497006703 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8846592522748477, 'min_weight_fraction_leaf': 0.027028995364682774}. Best is trial 86 with value: 0.8257675162186733.

Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:25:19,710] Trial 91 finished with value: 0.8083385863511406 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 133, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8818337195376095, 'min_weight_fraction_leaf': 0.029196432033481958}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7296137339055794
[I 2024-04-22 09:25:20,216] Trial 92 finished with value: 0.7552483413861439 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 135, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.887423031596968, 'min_weight_fraction_leaf': 0.025844049706309193}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8283261802575107
[I 2024-04-22 09:25:20,527] Trial 93 finished with value: 0.8059160832380525 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 66, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8488078188965495, 'min_weight_fraction_leaf': 0.013011220287553072}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-22 09:25:21,003] Trial 94 finished with value: 0.8092765498262015 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 111, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7853435226199493, 'min_weight_fraction_leaf': 0.02738269110214168}. Best is trial 86 with value: 0.8257675162186733.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8755364806866953
[I 2024-04-22 09:25:21,461] Trial 95 finished with value: 0.826448505102924 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8161032428574773, 'min_weight_fraction_leaf': 0.001106761767719347}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8154506437768241
[I 2024-04-22 09:25:21,996] Trial 96 finished with value: 0.7842940671166678 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 113, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7755580189933128, 'min_weight_fraction_leaf': 0.015997371825892767}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.759656652360515
[I 2024-04-22 09:25:22,239] Trial 97 finished with value: 0.7672112148047836 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 39, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8147988676493763, 'min_weight_fraction_leaf': 0.0308224860074267}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7124463519313304
[I 2024-04-22 09:25:22,647] Trial 98 finished with value: 0.7385526112254805 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 97, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7875371195797898, 'min_weight_fraction_leaf': 0.20718461376465755}. Best is trial 95 with value: 0.826448505102924.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.720532319391635

[I 2024-04-22 09:25:23,129] A new study created in memory with name: no-name-ef8d8509-1697-4da8-b2e6-fe92365e73de

Fold 5 C-index: 0.6459227467811158
[I 2024-04-22 09:25:23,122] Trial 99 finished with value: 0.6919788612158724 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 126, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8515495175736911, 'min_weight_fraction_leaf': 0.4077588868802398}. Best is trial 95 with value: 0.826448505102924.


* Best trial for C-index:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.826448505102924], datetime_start=datetime.datetime(2024, 4, 22, 9, 25, 21, 8461), datetime_complete=datetime.datetime(2024, 4, 22, 9, 25, 21, 460744), params={'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 105, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8161032428574773, 'min_weight_fraction_leaf': 0.001106761767719347}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=95, value=None)


* Best Score for C-index:
 0.826448505102924

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2216883708385238
Fold 2 IBS: 0.20116513124707355
Fold 3 IBS: 0.18963496960925966
Fold 4 IBS: 0.20548033840998792
Fold 5 IBS: 0.18750823813035528
[I 2024-04-22 09:25:25,433] Trial 0 finished with value: 0.20109540964704004 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-22 09:25:28,444] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23328845550406502
Fold 2 IBS: 0.21810066709735482
Fold 3 IBS: 0.2100774317752478
Fold 4 IBS: 0.22329553132649185
Fold 5 IBS: 0.2114469499436477
[I 2024-04-22 09:25:31,070] Trial 2 finished with value: 0.21924180712936142 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.2351174850348692
Fold 2 IBS: 0.219828345872527
Fold 3 IBS: 0.21173255582990505
Fold 4 IBS: 0.22584022524964367
Fold 5 IBS: 0.21387778959798523
[I 2024-04-22 09:25:31,982] Trial 3 finished with value: 0.22127928031698602 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-22 09:25:34,310] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-22 09:25:35,462] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.22285591564464766
Fold 2 IBS: 0.20324049199979516
Fold 3 IBS: 0.19028540014692436
Fold 4 IBS: 0.2090397510159576
Fold 5 IBS: 0.1897288358797867
[I 2024-04-22 09:25:37,884] Trial 6 finished with value: 0.20303007893742228 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.22779745048944502
Fold 2 IBS: 0.21116263533467225
Fold 3 IBS: 0.20158439716136908
Fold 4 IBS: 0.21503406407606104
Fold 5 IBS: 0.2009534751387103
[I 2024-04-22 09:25:39,567] Trial 7 finished with value: 0.21130640444005158 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.2336849435018476
Fold 2 IBS: 0.21699322646377178
Fold 3 IBS: 0.20944474413453934
Fold 4 IBS: 0.22497867659365728
Fold 5 IBS: 0.21355042601743562
[I 2024-04-22 09:25:39,897] Trial 8 finished with value: 0.21973040334225033 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23735614317408008
Fold 2 IBS: 0.22250970142913065
Fold 3 IBS: 0.21632908896013436
Fold 4 IBS: 0.23142974084173232
Fold 5 IBS: 0.21892814505251118
[I 2024-04-22 09:25:43,318] Trial 9 finished with value: 0.22531056389151768 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-22 09:25:46,481] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.23022250449663892
Fold 2 IBS: 0.20809523912377517
Fold 3 IBS: 0.19803303843460215
Fold 4 IBS: 0.21550808264334878
Fold 5 IBS: 0.20218737765773626
[I 2024-04-22 09:25:49,566] Trial 11 finished with value: 0.21080924847122023 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.20109540964704004.
Fold 1 IBS: 0.21613989052002444
Fold 2 IBS: 0.1966321312406504
Fold 3 IBS: 0.18848837574478716
Fold 4 IBS: 0.20253748024407425
Fold 5 IBS: 0.18190788145678702
[I 2024-04-22 09:25:53,724] Trial 12 finished with value: 0.19714115184126466 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22624638824497345
Fold 2 IBS: 0.208132783074928
Fold 3 IBS: 0.1957266434056336
Fold 4 IBS: 0.21533929207751132
Fold 5 IBS: 0.19842738811030086
[I 2024-04-22 09:25:57,104] Trial 13 finished with value: 0.20877449898266948 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22734034749345805
Fold 2 IBS: 0.20875433795400827
Fold 3 IBS: 0.19554481462030096
Fold 4 IBS: 0.217258375641282
Fold 5 IBS: 0.19872227743792803
[I 2024-04-22 09:25:59,527] Trial 14 finished with value: 0.20952403062939545 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.19714115184126466.

Fold 1 IBS: 0.2285622101008634
Fold 2 IBS: 0.20843529070864095
Fold 3 IBS: 0.19501846306370746
Fold 4 IBS: 0.21559689896401366
Fold 5 IBS: 0.19971924614220493
[I 2024-04-22 09:26:01,152] Trial 15 finished with value: 0.20946642179588607 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.2404239471321595
Fold 2 IBS: 0.22515713522164824
Fold 3 IBS: 0.21747041451130297
Fold 4 IBS: 0.23590557558587374
Fold 5 IBS: 0.2189832067887446
[I 2024-04-22 09:26:04,082] Trial 16 finished with value: 0.2275880558479458 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.2265766966093104
Fold 2 IBS: 0.21304461762010127
Fold 3 IBS: 0.19686726071348115
Fold 4 IBS: 0.21529218618416335
Fold 5 IBS: 0.19893026398098457
[I 2024-04-22 09:26:06,050] Trial 17 finished with value: 0.21014220502160813 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-22 09:26:06,956] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.226522202989843
Fold 2 IBS: 0.20703960609508038
Fold 3 IBS: 0.1942721352571641
Fold 4 IBS: 0.21479270879307474
Fold 5 IBS: 0.19770773184290516
[I 2024-04-22 09:26:09,361] Trial 19 finished with value: 0.2080668769956135 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22860530313751873
Fold 2 IBS: 0.2197286802115928
Fold 3 IBS: 0.20141531822386521
Fold 4 IBS: 0.23000502351334556
Fold 5 IBS: 0.20897153269462923
[I 2024-04-22 09:26:09,522] Trial 20 finished with value: 0.2177451715561903 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22277384041815695
Fold 2 IBS: 0.20334257879097034
Fold 3 IBS: 0.19030809415067831
Fold 4 IBS: 0.2080413933204737
Fold 5 IBS: 0.18916272546530452
[I 2024-04-22 09:26:12,111] Trial 21 finished with value: 0.20272572642911676 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.22001622035995086
Fold 2 IBS: 0.20143159104176697
Fold 3 IBS: 0.18930871547839062
Fold 4 IBS: 0.20556188928342486
Fold 5 IBS: 0.18618950630512082
[I 2024-04-22 09:26:14,696] Trial 22 finished with value: 0.20050158449373084 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.19714115184126466.
Fold 1 IBS: 0.21613582256339794
Fold 2 IBS: 0.19387991553904665
Fold 3 IBS: 0.18688212496978923
Fold 4 IBS: 0.19909456369999257
Fold 5 IBS: 0.1769669671210479
[I 2024-04-22 09:26:18,319] Trial 23 finished with value: 0.19459187877865486 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22098376153714128
Fold 2 IBS: 0.2017790967079455
Fold 3 IBS: 0.18977869471880326
Fold 4 IBS: 0.20562300123773503
Fold 5 IBS: 0.1895750781822595
[I 2024-04-22 09:26:21,991] Trial 24 finished with value: 0.2015479264767769 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2283056563231173
Fold 2 IBS: 0.21007958258826712
Fold 3 IBS: 0.20299281229435043
Fold 4 IBS: 0.21313667345754783
Fold 5 IBS: 0.20072093838312854
[I 2024-04-22 09:26:25,601] Trial 25 finished with value: 0.21104713260928226 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22547573656030792
Fold 2 IBS: 0.2067128508655798
Fold 3 IBS: 0.1939155139277123
Fold 4 IBS: 0.21316063898492277
Fold 5 IBS: 0.1966361463030427
[I 2024-04-22 09:26:29,932] Trial 26 finished with value: 0.20718017732831312 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22651286012786861
Fold 2 IBS: 0.2071828931412121
Fold 3 IBS: 0.19383543230944772
Fold 4 IBS: 0.21404492643798378
Fold 5 IBS: 0.1965677671793665
[I 2024-04-22 09:26:32,906] Trial 27 finished with value: 0.20762877583917572 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2296162488525048
Fold 2 IBS: 0.21553963633321688
Fold 3 IBS: 0.19785601697252495
Fold 4 IBS: 0.2188768233602731
Fold 5 IBS: 0.20093600143211168
[I 2024-04-22 09:26:34,711] Trial 28 finished with value: 0.2125649453901263 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2320037319505613
Fold 2 IBS: 0.21529282635362382
Fold 3 IBS: 0.20073796574461872
Fold 4 IBS: 0.22374477453593242
Fold 5 IBS: 0.20919202181500016
[I 2024-04-22 09:26:36,078] Trial 29 finished with value: 0.2161942640799473 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.19459187877865486.

Fold 1 IBS: 0.2233579319393271
Fold 2 IBS: 0.20096408163499427
Fold 3 IBS: 0.19049881866793233
Fold 4 IBS: 0.20774755146340546
Fold 5 IBS: 0.19123419554925844
[I 2024-04-22 09:26:38,258] Trial 30 finished with value: 0.20276051585098354 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2179837541713329
Fold 2 IBS: 0.19996868148399857
Fold 3 IBS: 0.18950194352113112
Fold 4 IBS: 0.20402491486791338
Fold 5 IBS: 0.18472430994108335
[I 2024-04-22 09:26:40,779] Trial 31 finished with value: 0.19924072079709187 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.923666057752446, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.2165115875368992
Fold 2 IBS: 0.19730089666900102
Fold 3 IBS: 0.18932681429498213
Fold 4 IBS: 0.2026285347669489
Fold 5 IBS: 0.18129650151368074
[I 2024-04-22 09:26:43,294] Trial 32 finished with value: 0.1974128669563024 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.939007534925735, 'min_weight_fraction_leaf': 0.056106269226335825}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.22215223881932283
Fold 2 IBS: 0.20404673534195444
Fold 3 IBS: 0.19059256536590438
Fold 4 IBS: 0.20867030880038456
Fold 5 IBS: 0.1902323613350749
[I 2024-04-22 09:26:45,733] Trial 33 finished with value: 0.20313884193252824 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9138848353483187, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 23 with value: 0.19459187877865486.
Fold 1 IBS: 0.21571300333932517
Fold 2 IBS: 0.1845951559627474
Fold 3 IBS: 0.18880163665481287
Fold 4 IBS: 0.1949110082696481
Fold 5 IBS: 0.17373428623842993
[I 2024-04-22 09:26:50,131] Trial 34 finished with value: 0.1915510180929927 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.06204686171902169}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21454541287943435
Fold 2 IBS: 0.18693346330112653
Fold 3 IBS: 0.19102421355153448
Fold 4 IBS: 0.19551337596236062
Fold 5 IBS: 0.1761961240257905
[I 2024-04-22 09:26:54,825] Trial 35 finished with value: 0.1928425179440493 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8327847526324277, 'min_weight_fraction_leaf': 0.055940476394666754}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21421473813611983
Fold 2 IBS: 0.18781798129221267
Fold 3 IBS: 0.19253146542248586
Fold 4 IBS: 0.19760463791446536
Fold 5 IBS: 0.17599130386074804
[I 2024-04-22 09:26:59,227] Trial 36 finished with value: 0.19363202532520635 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827098326399153, 'min_weight_fraction_leaf': 0.06897665469252873}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.220989467263724
Fold 2 IBS: 0.19890804921057023
Fold 3 IBS: 0.1955995866337726
Fold 4 IBS: 0.20347488198691915
Fold 5 IBS: 0.18652218714210275
[I 2024-04-22 09:27:02,974] Trial 37 finished with value: 0.20109883444741775 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8333567609683693, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21403271727225354
Fold 2 IBS: 0.1880480951062635
Fold 3 IBS: 0.1927275263843754
Fold 4 IBS: 0.19690061622051883
Fold 5 IBS: 0.17593442460775408
[I 2024-04-22 09:27:05,719] Trial 38 finished with value: 0.19352867591823306 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 345, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8095186934535692, 'min_weight_fraction_leaf': 0.06981260769852976}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.228306499716191
Fold 2 IBS: 0.211502363047124
Fold 3 IBS: 0.19915744044493738
Fold 4 IBS: 0.21580761059677792
Fold 5 IBS: 0.19923517798027957
[I 2024-04-22 09:27:08,337] Trial 39 finished with value: 0.21080181835706197 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8235915436715224, 'min_weight_fraction_leaf': 0.2150204152808745}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22009212142996487
Fold 2 IBS: 0.20235485246883128
Fold 3 IBS: 0.19662068942862213
Fold 4 IBS: 0.20713783696954896
Fold 5 IBS: 0.18874034333226591
[I 2024-04-22 09:27:09,709] Trial 40 finished with value: 0.20298916872584663 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 166, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7763291518258434, 'min_weight_fraction_leaf': 0.1415885205487063}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21512726209197802
Fold 2 IBS: 0.19166650395727697
Fold 3 IBS: 0.19078575336790274
Fold 4 IBS: 0.19733338482496118
Fold 5 IBS: 0.1785081121582588
[I 2024-04-22 09:27:13,483] Trial 41 finished with value: 0.19468420328007555 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 470, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7318083142370735, 'min_weight_fraction_leaf': 0.06567312882813131}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21532149949188067
Fold 2 IBS: 0.1847817766100537
Fold 3 IBS: 0.18879463768311291
Fold 4 IBS: 0.19584692384132116
Fold 5 IBS: 0.17539535562149766
[I 2024-04-22 09:27:16,939] Trial 42 finished with value: 0.19202803864957324 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 443, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8078708827436648, 'min_weight_fraction_leaf': 0.0507620305497474}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21471296520718855
Fold 2 IBS: 0.19373402376691015
Fold 3 IBS: 0.1935782510317697
Fold 4 IBS: 0.19816815937172588
Fold 5 IBS: 0.18130190427253323
[I 2024-04-22 09:27:21,358] Trial 43 finished with value: 0.1962990607300255 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 437, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8055193729946044, 'min_weight_fraction_leaf': 0.08265746982147082}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22368717006762112
Fold 2 IBS: 0.20588683903754684
Fold 3 IBS: 0.19891768749780012
Fold 4 IBS: 0.20962858279474328
Fold 5 IBS: 0.1937212074562581
[I 2024-04-22 09:27:24,070] Trial 44 finished with value: 0.20636829737079393 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 292, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7663562356315471, 'min_weight_fraction_leaf': 0.16789080732305503}. Best is trial 34 with value: 0.1915510180929927.

Fold 1 IBS: 0.22018361682359297
Fold 2 IBS: 0.19767576801393197
Fold 3 IBS: 0.19421270363305465
Fold 4 IBS: 0.20406059613721392
Fold 5 IBS: 0.1854331539519078
[I 2024-04-22 09:27:28,077] Trial 45 finished with value: 0.20031316771194024 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8420791678401572, 'min_weight_fraction_leaf': 0.1114478053387663}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22677495195617972
Fold 2 IBS: 0.20938982706068335
Fold 3 IBS: 0.20301008325030304
Fold 4 IBS: 0.21538736174154596
Fold 5 IBS: 0.2016448459853074
[I 2024-04-22 09:27:32,540] Trial 46 finished with value: 0.21124141399880392 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9457056327934814, 'min_weight_fraction_leaf': 0.062092086072191535}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.22930830715400474
Fold 2 IBS: 0.21438051208781905
Fold 3 IBS: 0.20096996720018
Fold 4 IBS: 0.21969610541253728
Fold 5 IBS: 0.20049850908169184
[I 2024-04-22 09:27:35,966] Trial 47 finished with value: 0.21297068018724657 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8736971337878316, 'min_weight_fraction_leaf': 0.026438797227417946}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.213913284691646
Fold 2 IBS: 0.19365644684493624
Fold 3 IBS: 0.19264144608983128
Fold 4 IBS: 0.1978352759197991
Fold 5 IBS: 0.1792186928752932
[I 2024-04-22 09:27:39,489] Trial 48 finished with value: 0.19545302928430117 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7979948724878182, 'min_weight_fraction_leaf': 0.08705758256253036}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.23833976091790518
Fold 2 IBS: 0.21548114767509935
Fold 3 IBS: 0.2019224001063648
Fold 4 IBS: 0.22951033126413029
Fold 5 IBS: 0.2066617134943696
[I 2024-04-22 09:27:42,078] Trial 49 finished with value: 0.21838307069157384 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 332, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.944869727275161, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2248852208588708
Fold 2 IBS: 0.2086945344469891
Fold 3 IBS: 0.19533980848254817
Fold 4 IBS: 0.2116409132896753
Fold 5 IBS: 0.19616008958660672
[I 2024-04-22 09:27:46,086] Trial 50 finished with value: 0.20734411333293803 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 482, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5323261217237781, 'min_weight_fraction_leaf': 0.1346406423395477}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2139844395487544
Fold 2 IBS: 0.18914728968054922
Fold 3 IBS: 0.18993424334874043
Fold 4 IBS: 0.19861945136516718
Fold 5 IBS: 0.17532292501761673
[I 2024-04-22 09:27:49,800] Trial 51 finished with value: 0.19340166979216558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 448, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6952532733159762, 'min_weight_fraction_leaf': 0.05105168315138192}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.21359431074388344
Fold 2 IBS: 0.18845827623129896
Fold 3 IBS: 0.18920811875796045
Fold 4 IBS: 0.19741430133274535
Fold 5 IBS: 0.17472384859961296
[I 2024-04-22 09:27:54,511] Trial 52 finished with value: 0.19267977113310025 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6895352885746311, 'min_weight_fraction_leaf': 0.05243800385790333}. Best is trial 34 with value: 0.1915510180929927.
Fold 1 IBS: 0.2116998447565635
Fold 2 IBS: 0.18628912985639196
Fold 3 IBS: 0.18838500488320775
Fold 4 IBS: 0.19561139573019
Fold 5 IBS: 0.17448408339296287
[I 2024-04-22 09:27:58,322] Trial 53 finished with value: 0.1912938917238632 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7530104333187604, 'min_weight_fraction_leaf': 0.04825576822079568}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.21465186773648143
Fold 2 IBS: 0.18855005015058893
Fold 3 IBS: 0.18511049876087637
Fold 4 IBS: 0.19705279145523985
Fold 5 IBS: 0.17274909831863947
[I 2024-04-22 09:28:01,427] Trial 54 finished with value: 0.1916228612843652 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 380, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6854242983573284, 'min_weight_fraction_leaf': 0.016297809364208576}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22796071086903075
Fold 2 IBS: 0.20969832304654898
Fold 3 IBS: 0.20267836033689163
Fold 4 IBS: 0.21278935271450855
Fold 5 IBS: 0.20040468065389563
[I 2024-04-22 09:28:04,815] Trial 55 finished with value: 0.2107062855241751 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6628876016595922, 'min_weight_fraction_leaf': 0.01845633424767698}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.24625934471253716
Fold 2 IBS: 0.23214786228629494
Fold 3 IBS: 0.2295871449534552
Fold 4 IBS: 0.24147697769672616
Fold 5 IBS: 0.23025545386023222
[I 2024-04-22 09:28:08,465] Trial 56 finished with value: 0.23594535670184916 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 425, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6032533491002975, 'min_weight_fraction_leaf': 0.3230607190970375}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22111769895311692
Fold 2 IBS: 0.204017488716264
Fold 3 IBS: 0.19621805096093797
Fold 4 IBS: 0.20670229645207078
Fold 5 IBS: 0.1917979613090219
[I 2024-04-22 09:28:12,412] Trial 57 finished with value: 0.20397069927828232 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 485, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7531615546706312, 'min_weight_fraction_leaf': 0.005684521692916746}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.22003274498373035
Fold 2 IBS: 0.1998660068050171
Fold 3 IBS: 0.1881698580726066
Fold 4 IBS: 0.20239036180242276
Fold 5 IBS: 0.18399424930109848
[I 2024-04-22 09:28:15,322] Trial 58 finished with value: 0.19889064419297506 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 14, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5394996653270911, 'min_weight_fraction_leaf': 0.023602592097570048}. Best is trial 53 with value: 0.1912938917238632.
Fold 1 IBS: 0.21789189671655823
Fold 2 IBS: 0.1830618664362058
Fold 3 IBS: 0.192172012950134
Fold 4 IBS: 0.1957675158574896
Fold 5 IBS: 0.16932510927863137
[I 2024-04-22 09:28:18,720] Trial 59 finished with value: 0.19164368024780382 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8661967641372095, 'min_weight_fraction_leaf': 0.039584340366555525}. Best is trial 53 with value: 0.1912938917238632.

Fold 1 IBS: 0.21476513837056027
Fold 2 IBS: 0.18143050987640613
Fold 3 IBS: 0.1908356407571883
Fold 4 IBS: 0.19427180424062881
Fold 5 IBS: 0.16683442835564766
[I 2024-04-22 09:28:22,587] Trial 60 finished with value: 0.18962750432008624 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 439, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8952499671372233, 'min_weight_fraction_leaf': 0.036398817545426995}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21627361369698
Fold 2 IBS: 0.1817225137067132
Fold 3 IBS: 0.19073393689024337
Fold 4 IBS: 0.19494098781318964
Fold 5 IBS: 0.16750297353174665
[I 2024-04-22 09:28:26,387] Trial 61 finished with value: 0.19023480512777455 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 438, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8757721856898264, 'min_weight_fraction_leaf': 0.04046785921890601}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21569547676030276
Fold 2 IBS: 0.19406435056789098
Fold 3 IBS: 0.18599781327998668
Fold 4 IBS: 0.19890833105526054
Fold 5 IBS: 0.17390689345537047
[I 2024-04-22 09:28:29,471] Trial 62 finished with value: 0.19371457302376227 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 422, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9066387670860593, 'min_weight_fraction_leaf': 0.03189756237329784}. Best is trial 60 with value: 0.18962750432008624.
Fold 1 IBS: 0.21402139447730326
Fold 2 IBS: 0.18083663656728602
Fold 3 IBS: 0.18753380129692818
Fold 4 IBS: 0.19255745305291946
Fold 5 IBS: 0.1667002799097155
[I 2024-04-22 09:28:32,509] Trial 63 finished with value: 0.1883299130608305 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002786019075411844}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2139897789072574
Fold 2 IBS: 0.18091332402839688
Fold 3 IBS: 0.1877363493532483
Fold 4 IBS: 0.1926457442603295
Fold 5 IBS: 0.16686510313910077
[I 2024-04-22 09:28:35,349] Trial 64 finished with value: 0.18843005993766654 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 370, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8662742964997368, 'min_weight_fraction_leaf': 0.002799383925114314}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21356453199756695
Fold 2 IBS: 0.18414337595624433
Fold 3 IBS: 0.19135848396732294
Fold 4 IBS: 0.19567506298543985
Fold 5 IBS: 0.16902410400423407
[I 2024-04-22 09:28:38,647] Trial 65 finished with value: 0.19075311178216164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 368, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9996741200655364, 'min_weight_fraction_leaf': 0.013343672274008771}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.24654787550564836
Fold 2 IBS: 0.23215877749004982
Fold 3 IBS: 0.22951426045636053
Fold 4 IBS: 0.2415490288777898
Fold 5 IBS: 0.23029214299076572
[I 2024-04-22 09:28:41,649] Trial 66 finished with value: 0.23601241706412285 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 321, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2266323511377712
Fold 2 IBS: 0.2071535974555395
Fold 3 IBS: 0.20048051366340186
Fold 4 IBS: 0.21211123932933376
Fold 5 IBS: 0.197924092034569
[I 2024-04-22 09:28:44,439] Trial 67 finished with value: 0.20886035872412304 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 363, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8902348249567581, 'min_weight_fraction_leaf': 0.0005656859239113344}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21760444020822703
Fold 2 IBS: 0.19984684424100796
Fold 3 IBS: 0.1923024665200439
Fold 4 IBS: 0.2028177913477314
Fold 5 IBS: 0.18410276014280125
[I 2024-04-22 09:28:46,989] Trial 68 finished with value: 0.1993348604919623 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 293, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9860764994598216, 'min_weight_fraction_leaf': 0.022286815780540634}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2365591490720433
Fold 2 IBS: 0.22131703584518395
Fold 3 IBS: 0.21468130634418622
Fold 4 IBS: 0.22918783390849085
Fold 5 IBS: 0.2181320987477092
[I 2024-04-22 09:28:48,775] Trial 69 finished with value: 0.2239754847835227 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 236, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9608682699921427, 'min_weight_fraction_leaf': 0.2864016846718066}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2141001980700463
Fold 2 IBS: 0.18008333278426925
Fold 3 IBS: 0.1879725741810636
Fold 4 IBS: 0.19498909793486166
Fold 5 IBS: 0.16584373802214583
[I 2024-04-22 09:28:52,502] Trial 70 finished with value: 0.18859778819847733 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9969480236364259, 'min_weight_fraction_leaf': 0.013812205414924436}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2140966903857263
Fold 2 IBS: 0.18072561052771724
Fold 3 IBS: 0.18882252022842136
Fold 4 IBS: 0.19597566403934094
Fold 5 IBS: 0.16539717562089074
[I 2024-04-22 09:28:56,380] Trial 71 finished with value: 0.18900353216041932 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9918558396160204, 'min_weight_fraction_leaf': 0.0068952357522586456}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21603071934692913
Fold 2 IBS: 0.18199677410478105
Fold 3 IBS: 0.18857834975768964
Fold 4 IBS: 0.1931833546739912
Fold 5 IBS: 0.16659700790160611
[I 2024-04-22 09:28:59,422] Trial 72 finished with value: 0.18927724115699943 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9121256508534055, 'min_weight_fraction_leaf': 0.0005212216954084261}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21375162072413798
Fold 2 IBS: 0.18715392969930847
Fold 3 IBS: 0.19203353721517546
Fold 4 IBS: 0.19646864440812928
Fold 5 IBS: 0.17158213719923593
[I 2024-04-22 09:29:02,540] Trial 73 finished with value: 0.1921979738491974 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9980006295053775, 'min_weight_fraction_leaf': 0.0006603867898888157}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21401318872018266
Fold 2 IBS: 0.18291770353148368
Fold 3 IBS: 0.1878785582518727
Fold 4 IBS: 0.1915900349059854
Fold 5 IBS: 0.16636063217999533
[I 2024-04-22 09:29:05,405] Trial 74 finished with value: 0.18855202351790395 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 372, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9034857567027796, 'min_weight_fraction_leaf': 0.013280468186275795}. Best is trial 63 with value: 0.1883299130608305.

Fold 1 IBS: 0.21657675292627207
Fold 2 IBS: 0.18996174454319362
Fold 3 IBS: 0.18393478555155848
Fold 4 IBS: 0.19722264590644567
Fold 5 IBS: 0.17340727825186003
[I 2024-04-22 09:29:08,373] Trial 75 finished with value: 0.19222064143586598 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 391, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9086795540810024, 'min_weight_fraction_leaf': 0.03284410208925504}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21374362171322053
Fold 2 IBS: 0.1809837734102344
Fold 3 IBS: 0.1928804193379134
Fold 4 IBS: 0.19389862294434004
Fold 5 IBS: 0.16641872761123616
[I 2024-04-22 09:29:11,662] Trial 76 finished with value: 0.1895850330033889 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 417, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8605344738061455, 'min_weight_fraction_leaf': 0.0132289654357266}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2136263783710042
Fold 2 IBS: 0.1797844883476793
Fold 3 IBS: 0.19019941306366508
Fold 4 IBS: 0.19332643220320936
Fold 5 IBS: 0.16540838604898453
[I 2024-04-22 09:29:15,054] Trial 77 finished with value: 0.18846901960690848 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 340, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8553757827166253, 'min_weight_fraction_leaf': 0.01267833398506176}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21394057344768827
Fold 2 IBS: 0.18063564607564772
Fold 3 IBS: 0.19110178366055228
Fold 4 IBS: 0.1933325146794154
Fold 5 IBS: 0.165642771743641
[I 2024-04-22 09:29:18,751] Trial 78 finished with value: 0.1889306579213889 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 371, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8575353599751615, 'min_weight_fraction_leaf': 0.011808738308151196}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2126262135430542
Fold 2 IBS: 0.18696373447968684
Fold 3 IBS: 0.1916799280019377
Fold 4 IBS: 0.19683095724446073
Fold 5 IBS: 0.17241956982191808
[I 2024-04-22 09:29:21,857] Trial 79 finished with value: 0.19210408061821152 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 333, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9589922281293288, 'min_weight_fraction_leaf': 0.00023409421845237187}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2153469063453449
Fold 2 IBS: 0.18778468182940314
Fold 3 IBS: 0.1866708606567345
Fold 4 IBS: 0.19691516821506336
Fold 5 IBS: 0.17754995961266154
[I 2024-04-22 09:29:24,493] Trial 80 finished with value: 0.1928535153318415 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2869597372530869, 'min_weight_fraction_leaf': 0.015545952867167576}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.20902792603358883
Fold 2 IBS: 0.18006042053021734
Fold 3 IBS: 0.18911702889503695
Fold 4 IBS: 0.19734675827568018
Fold 5 IBS: 0.16680814632667756
[I 2024-04-22 09:29:27,301] Trial 81 finished with value: 0.1884720560122402 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 309, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9259652503609331, 'min_weight_fraction_leaf': 0.011333713500102472}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.20965756514521555
Fold 2 IBS: 0.1814081067821129
Fold 3 IBS: 0.1896445243994355
Fold 4 IBS: 0.19634790225481819
Fold 5 IBS: 0.1667849972674436
[I 2024-04-22 09:29:30,023] Trial 82 finished with value: 0.1887686191698051 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9323699691639797, 'min_weight_fraction_leaf': 0.02308562555518695}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2153817227869837
Fold 2 IBS: 0.19064494420871675
Fold 3 IBS: 0.1928363140916346
Fold 4 IBS: 0.19848435688688135
Fold 5 IBS: 0.17685355407979692
[I 2024-04-22 09:29:32,641] Trial 83 finished with value: 0.19484017841080264 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9339793672931662, 'min_weight_fraction_leaf': 0.022004474344811363}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.24653067306998416
Fold 2 IBS: 0.23215271642663415
Fold 3 IBS: 0.23010902544257975
Fold 4 IBS: 0.24116005900490298
Fold 5 IBS: 0.23000207632521744
[I 2024-04-22 09:29:35,258] Trial 84 finished with value: 0.2359909100538637 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 342, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.1443115068222393, 'min_weight_fraction_leaf': 0.07505434810839277}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.23013207588924356
Fold 2 IBS: 0.21649686531732093
Fold 3 IBS: 0.20821441289778195
Fold 4 IBS: 0.22098308423517524
Fold 5 IBS: 0.20804654146185125
[I 2024-04-22 09:29:37,760] Trial 85 finished with value: 0.21677459596027457 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 311, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9650657834803271, 'min_weight_fraction_leaf': 0.035745447715905855}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.23776519245318667
Fold 2 IBS: 0.21599806462497675
Fold 3 IBS: 0.19854293183949293
Fold 4 IBS: 0.22768263426905036
Fold 5 IBS: 0.20526222555074036
[I 2024-04-22 09:29:40,526] Trial 86 finished with value: 0.2170502097474894 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8552680427767512, 'min_weight_fraction_leaf': 0.381622326839403}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.22498794680095857
Fold 2 IBS: 0.20871296427131997
Fold 3 IBS: 0.1986932860108566
Fold 4 IBS: 0.21342471202843274
Fold 5 IBS: 0.19611500802990536
[I 2024-04-22 09:29:43,014] Trial 87 finished with value: 0.20838678342829464 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 322, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9346631200415512, 'min_weight_fraction_leaf': 0.011829639629513685}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2162799881668905
Fold 2 IBS: 0.19232899542734697
Fold 3 IBS: 0.18648368909793978
Fold 4 IBS: 0.19899335757357461
Fold 5 IBS: 0.17300447570342775
[I 2024-04-22 09:29:45,966] Trial 88 finished with value: 0.19341810119383593 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 377, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8961097715415979, 'min_weight_fraction_leaf': 0.025293850990263902}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21685001465299827
Fold 2 IBS: 0.1961691885413081
Fold 3 IBS: 0.19377583257578665
Fold 4 IBS: 0.19986684493416645
Fold 5 IBS: 0.17774512608127138
[I 2024-04-22 09:29:48,649] Trial 89 finished with value: 0.1968814013571062 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9273501023983637, 'min_weight_fraction_leaf': 0.04735901557972175}. Best is trial 63 with value: 0.1883299130608305.

Fold 1 IBS: 0.21649654230068696
Fold 2 IBS: 0.1994536066038553
Fold 3 IBS: 0.1910443715333566
Fold 4 IBS: 0.20311940988854024
Fold 5 IBS: 0.18412454653280888
[I 2024-04-22 09:29:51,377] Trial 90 finished with value: 0.1988476953718496 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9531106840561406, 'min_weight_fraction_leaf': 0.09026278115621361}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21417020956953955
Fold 2 IBS: 0.18221070479947724
Fold 3 IBS: 0.1876123093586995
Fold 4 IBS: 0.1945453292939215
Fold 5 IBS: 0.1658337819099612
[I 2024-04-22 09:29:55,501] Trial 91 finished with value: 0.1888744669863198 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 390, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9155821930769641, 'min_weight_fraction_leaf': 0.0071593216081176705}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21334772506121008
Fold 2 IBS: 0.1816182181383867
Fold 3 IBS: 0.18952956072516672
Fold 4 IBS: 0.19750128460117958
Fold 5 IBS: 0.1685827762577281
[I 2024-04-22 09:29:58,932] Trial 92 finished with value: 0.19011591295673422 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 352, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.97798257382931, 'min_weight_fraction_leaf': 0.009783759359771677}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21517609409586363
Fold 2 IBS: 0.1821811797549699
Fold 3 IBS: 0.1870785183222405
Fold 4 IBS: 0.19102878902606021
Fold 5 IBS: 0.17067480247963093
[I 2024-04-22 09:30:02,215] Trial 93 finished with value: 0.18922787673575306 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 387, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8774391513202735, 'min_weight_fraction_leaf': 0.033797847017769014}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21137091510190062
Fold 2 IBS: 0.18839244695486237
Fold 3 IBS: 0.18742029037727956
Fold 4 IBS: 0.19491638605970943
Fold 5 IBS: 0.17114179611166253
[I 2024-04-22 09:30:05,055] Trial 94 finished with value: 0.19064836692108292 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 362, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3830871059653363, 'min_weight_fraction_leaf': 0.02515706968561085}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2138966882370574
Fold 2 IBS: 0.1844877510679235
Fold 3 IBS: 0.19259781557758243
Fold 4 IBS: 0.1952141807236525
Fold 5 IBS: 0.16975439013355925
[I 2024-04-22 09:30:07,573] Trial 95 finished with value: 0.191190165147955 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 331, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.853090178217675, 'min_weight_fraction_leaf': 0.012155059432012595}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2278103724303231
Fold 2 IBS: 0.20998652770068607
Fold 3 IBS: 0.2016895045401415
Fold 4 IBS: 0.2145197300147786
Fold 5 IBS: 0.20079551362441908
[I 2024-04-22 09:30:10,391] Trial 96 finished with value: 0.21096032966206962 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 376, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9196471588164407, 'min_weight_fraction_leaf': 0.04764222809243661}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.2129544257256905
Fold 2 IBS: 0.188757190081597
Fold 3 IBS: 0.1913596765199584
Fold 4 IBS: 0.19299294688332613
Fold 5 IBS: 0.16956267469915398
[I 2024-04-22 09:30:13,283] Trial 97 finished with value: 0.19112538278194519 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7906318813789162, 'min_weight_fraction_leaf': 0.05576114935877039}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21517779568864578
Fold 2 IBS: 0.18674501277395147
Fold 3 IBS: 0.19147087886044026
Fold 4 IBS: 0.1973182121218361
Fold 5 IBS: 0.170619113683073
[I 2024-04-22 09:30:15,375] Trial 98 finished with value: 0.19226620262558933 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 272, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8265091641061248, 'min_weight_fraction_leaf': 0.06956660551772675}. Best is trial 63 with value: 0.1883299130608305.
Fold 1 IBS: 0.21291524232383788
Fold 2 IBS: 0.17927405181896092
Fold 3 IBS: 0.19353115438588406
Fold 4 IBS: 0.19297220466886353
Fold 5 IBS: 0.17269237403404555
[I 2024-04-22 09:30:16,251] Trial 99 finished with value: 0.1902770054463184 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 10, 'n_estimators': 101, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.88561888536106, 'min_weight_fraction_leaf': 0.028367714803137684}. Best is trial 63 with value: 0.1883299130608305.


* Best trial for IBS:
 FrozenTrial(number=63, state=TrialState.COMPLETE, values=[0.1883299130608305], datetime_start=datetime.datetime(2024, 4, 22, 9, 28, 29, 475165), datetime_complete=datetime.datetime(2024, 4, 22, 9, 28, 32, 508971), params={'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 373, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8664901703822724, 'min_weight_fraction_leaf': 0.0002786019075411844}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=63, value=None)


* Best Score for IBS:
 0.1883299130608305

In [88]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [89]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.826
train_ibs:  0.188

#### Test

In [90]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [91]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_leaf_nodes=18,
                   max_samples=0.8161032428574773, min_samples_leaf=2,
                   min_samples_split=11,
                   min_weight_fraction_leaf=0.001106761767719347,
                   n_estimators=105, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.607

ExtraSurvivalTrees(max_depth=10, max_features=None, max_leaf_nodes=12,
                   max_samples=0.8664901703822724, min_samples_split=13,
                   min_weight_fraction_leaf=0.0002786019075411844,
                   n_estimators=373, oob_score=True, random_state=123)

IBS: 0.252

In [92]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [67]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 02:57:08,876] A new study created in memory with name: no-name-d0330b46-206f-4bab-85ac-38bd37d367e7

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:57:43,603] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:58:07,053] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:58:28,281] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:58:54,234] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:04,851] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:07,595] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:34,640] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:42,211] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 02:59:42,995] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 03:00:44,235] Trial 9 finished with value: 0.7053891693443892 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-22 03:02:15,913] Trial 10 finished with value: 0.6731409344204184 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:03:55,638] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-22 03:05:28,107] Trial 12 finished with value: 0.6892369560938594 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:06:17,951] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:07:16,419] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:08:02,588] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:08:32,315] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:09:22,916] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:10:19,500] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:10:21,569] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:10:41,070] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-22 03:11:23,536] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6437768240343348
[I 2024-04-22 03:12:03,246] Trial 22 finished with value: 0.6634639504505081 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:12:45,598] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:13:17,397] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:13:55,461] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:14:14,760] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:08,378] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:11,291] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:46,140] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:15:56,863] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.648068669527897
[I 2024-04-22 03:16:40,032] Trial 31 finished with value: 0.6148553306063567 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:17:29,848] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:18:05,452] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:18:39,127] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-22 03:19:02,505] Trial 35 finished with value: 0.6720678122425536 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:19,733] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:33,708] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:43,429] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:19:55,443] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:20:09,100] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6330472103004292
[I 2024-04-22 03:20:53,238] Trial 41 finished with value: 0.6603814554989593 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:21:26,103] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:22:05,593] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:22:17,592] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:01,339] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7053891693443892.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 03:23:07,477] Trial 46 finished with value: 0.7270154738948459 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:16,567] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:16,747] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:22,206] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:23:47,812] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7433460076045627
Fold 5 C-index: 0.703862660944206
[I 2024-04-22 03:24:13,301] Trial 51 finished with value: 0.6957971729128621 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:24:26,314] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6792828685258964
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 03:24:53,692] Trial 53 finished with value: 0.7166400375279826 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:25:17,038] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.04642759977764528, 'dropout_rate': 0.5787056799551111, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8043967529855988, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.9987906743578988, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:25:26,902] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9338509253358491, 'learning_rate': 0.05026798356278357, 'dropout_rate': 0.8859792395781099, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 2.0925706859481137, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.9220343002247878, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:25:57,598] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8543724704763108, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.3004273858397456, 'min_weight_fraction_leaf': 0.19369329911983815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7124463519313304
[I 2024-04-22 03:26:01,246] Trial 57 finished with value: 0.71352028974883 and parameters: {'subsample': 0.9087026240599475, 'learning_rate': 0.08124746006044987, 'dropout_rate': 0.997784793728882, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.410591151226506, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8063875242325604, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:04,689] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8212698530092863, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.181840851947653, 'min_weight_fraction_leaf': 0.4057697411163346, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8125246339086644, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 5}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:09,772] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9193087392842657, 'learning_rate': 0.0872713586054678, 'dropout_rate': 0.9474892480356638, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.3337975605954647, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.7937489212794213, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:11,084] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.7446094350786215, 'learning_rate': 0.09733264341118891, 'dropout_rate': 0.9841116957888287, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.6816514323618716, 'min_weight_fraction_leaf': 0.21423049941460018, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.7693486777346097, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 46 with value: 0.7270154738948459.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:20,130] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.079755577636651, 'dropout_rate': 0.9141007682217919, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.3860962100040052, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.960062895620913, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6314741035856574
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.6148936170212767
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6545064377682404
[I 2024-04-22 03:26:32,404] Trial 62 finished with value: 0.6738863298917944 and parameters: {'subsample': 0.9950153281899117, 'learning_rate': 0.08115591715872426, 'dropout_rate': 0.8285090704895912, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.46340528439350875, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.8636512797881153, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5836909871244635
[I 2024-04-22 03:26:43,065] Trial 63 finished with value: 0.5422175565840008 and parameters: {'subsample': 0.9879857181271309, 'learning_rate': 0.08167353877257796, 'dropout_rate': 0.8555425487679464, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.4732508331244123, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.8698220228130342, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:26:50,735] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9998194099499076, 'learning_rate': 0.08518105894428284, 'dropout_rate': 0.9084790128000951, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.43893162961234394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0018957941321912743, 'validation_fraction': 0.6573317669908815, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:10,071] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.8863506781235784, 'learning_rate': 0.09077517237486941, 'dropout_rate': 0.7155053041594167, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 1.0503703250594787, 'min_weight_fraction_leaf': 0.41623993393470454, 'max_features': 'sqrt', 'min_impurity_decrease': 5.4764171179088326e-05, 'validation_fraction': 0.7243703387674565, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:24,538] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9116050534419412, 'learning_rate': 0.07264703745168608, 'dropout_rate': 0.8194893498338957, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 1.5401195366715463, 'min_weight_fraction_leaf': 0.45613333197683914, 'max_features': 'sqrt', 'min_impurity_decrease': 0.013056447447707517, 'validation_fraction': 0.9169313175992941, 'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:28,843] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.2507118299802445, 'learning_rate': 0.036515998728865476, 'dropout_rate': 0.9726102863603132, 'n_estimators': 371, 'criterion': 'squared_error', 'ccp_alpha': 0.29393333981111347, 'min_weight_fraction_leaf': 0.48294812651480895, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0016007967193364127, 'validation_fraction': 0.8429859516851567, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:47,756] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8371795305913793, 'learning_rate': 0.04255428671400532, 'dropout_rate': 0.633247084204052, 'n_estimators': 400, 'criterion': 'squared_error', 'ccp_alpha': 0.8386209432307415, 'min_weight_fraction_leaf': 0.43086676861494394, 'max_features': 1, 'min_impurity_decrease': 0.006343103938039445, 'validation_fraction': 0.8911962268662544, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:27:54,790] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.9464359352204211, 'learning_rate': 0.06174138905299288, 'dropout_rate': 0.9285880327607973, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.45960319442458425, 'min_weight_fraction_leaf': 0.23985000065202236, 'max_features': 'log2', 'min_impurity_decrease': 0.00030338628790529525, 'validation_fraction': 0.329118980782965, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 46 with value: 0.7270154738948459.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 03:28:19,465] Trial 70 finished with value: 0.7584899292280459 and parameters: {'subsample': 0.7868009537469239, 'learning_rate': 0.06760822881110454, 'dropout_rate': 0.4501645913744281, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.010068295219290181, 'min_weight_fraction_leaf': 0.31623455708072684, 'max_features': 0.1, 'min_impurity_decrease': 1.7127716189044953e-05, 'validation_fraction': 0.773508933151765, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7553648068669528
[I 2024-04-22 03:28:43,552] Trial 71 finished with value: 0.7490850897378227 and parameters: {'subsample': 0.8731481729382106, 'learning_rate': 0.06824697098399125, 'dropout_rate': 0.44693614056417824, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.3047914794183888, 'max_features': 0.1, 'min_impurity_decrease': 3.976633059647162e-05, 'validation_fraction': 0.7895458945773391, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:29:06,082] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.7823514804378748, 'learning_rate': 0.05594196279186142, 'dropout_rate': 0.4470080666838303, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 0.3009753821860147, 'min_weight_fraction_leaf': 0.3059540589853319, 'max_features': 0.1, 'min_impurity_decrease': 1.5867418332223817e-05, 'validation_fraction': 0.7793460995771967, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 70 with value: 0.7584899292280459.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:29:33,766] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.8663908775735847, 'learning_rate': 0.06632362371857915, 'dropout_rate': 0.5067723878896389, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.618560685045426, 'min_weight_fraction_leaf': 0.31460076590199093, 'max_features': 0.1, 'min_impurity_decrease': 8.328437416038891e-06, 'validation_fraction': 0.7008907913024036, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 7}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:30:03,732] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.8288686373854733, 'learning_rate': 0.05998088897970471, 'dropout_rate': 0.35479137028960395, 'n_estimators': 414, 'criterion': 'squared_error', 'ccp_alpha': 0.9759418026741545, 'min_weight_fraction_leaf': 0.2773249572889655, 'max_features': 0.1, 'min_impurity_decrease': 5.198140001660516e-05, 'validation_fraction': 0.7466111961316684, 'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 70 with value: 0.7584899292280459.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 03:30:19,123] Trial 75 finished with value: 0.7593045273013703 and parameters: {'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:30:34,857] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.90806151385064, 'learning_rate': 0.06937411702873973, 'dropout_rate': 0.5775100962015742, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.3026218647170148, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 3.1759196242669716e-05, 'validation_fraction': 0.8054405672668666, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:30:46,719] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8021858195531186, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.4930834587163687, 'n_estimators': 291, 'criterion': 'squared_error', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.25797282688791734, 'max_features': 0.1, 'min_impurity_decrease': 8.194270761449124e-05, 'validation_fraction': 0.8191017051978536, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7553648068669528
[I 2024-04-22 03:31:06,455] Trial 78 finished with value: 0.7529889918423416 and parameters: {'subsample': 0.692374586728691, 'learning_rate': 0.05690511629279836, 'dropout_rate': 0.5670668275300401, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.3008453270284027, 'max_features': 0.1, 'min_impurity_decrease': 9.997537740252558e-05, 'validation_fraction': 0.634085956732461, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:31:26,173] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7354140786592815, 'learning_rate': 0.04969314557779707, 'dropout_rate': 0.44525279135712004, 'n_estimators': 366, 'criterion': 'squared_error', 'ccp_alpha': 0.5591541411162989, 'min_weight_fraction_leaf': 0.27054049814219927, 'max_features': 0.1, 'min_impurity_decrease': 0.0001332335562751616, 'validation_fraction': 0.6322159428309632, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:31:50,657] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.6390433213205666, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.4097359359491849, 'n_estimators': 387, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.2916012333412588, 'max_features': 0.1, 'min_impurity_decrease': 3.446222542448271e-05, 'validation_fraction': 0.658619742124138, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7339055793991416
[I 2024-04-22 03:32:04,736] Trial 81 finished with value: 0.7481542616623006 and parameters: {'subsample': 0.8900437147371856, 'learning_rate': 0.05732267025618887, 'dropout_rate': 0.5675964787359803, 'n_estimators': 338, 'criterion': 'squared_error', 'ccp_alpha': 0.02537647186946867, 'min_weight_fraction_leaf': 0.3203794260312518, 'max_features': 0.1, 'min_impurity_decrease': 0.00011928163703594395, 'validation_fraction': 0.5473179941373633, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:32:20,593] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.674646944161499, 'learning_rate': 0.06428673292745038, 'dropout_rate': 0.5603615855034783, 'n_estimators': 347, 'criterion': 'squared_error', 'ccp_alpha': 0.28819151280834227, 'min_weight_fraction_leaf': 0.30301215361806194, 'max_features': 0.1, 'min_impurity_decrease': 0.00011381045599980596, 'validation_fraction': 0.5688457919188374, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:32:33,147] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7076615576312072, 'learning_rate': 0.056710204467247914, 'dropout_rate': 0.6033560518396526, 'n_estimators': 335, 'criterion': 'squared_error', 'ccp_alpha': 0.8202792651285943, 'min_weight_fraction_leaf': 0.31878503420088733, 'max_features': 0.1, 'min_impurity_decrease': 0.0002767446387407935, 'validation_fraction': 0.51243688588132, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:32:52,080] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8885223542936614, 'learning_rate': 0.07000519724522539, 'dropout_rate': 0.5288642574811846, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 0.5149081571445734, 'min_weight_fraction_leaf': 0.34755924952935247, 'max_features': 0.1, 'min_impurity_decrease': 1.6951185184740712e-05, 'validation_fraction': 0.4777741397542481, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7896995708154506
[I 2024-04-22 03:33:07,768] Trial 85 finished with value: 0.7550455930886464 and parameters: {'subsample': 0.8605990508338958, 'learning_rate': 0.052056821807615235, 'dropout_rate': 0.4591414560091507, 'n_estimators': 318, 'criterion': 'squared_error', 'ccp_alpha': 0.011402478584663527, 'min_weight_fraction_leaf': 0.33201592938914204, 'max_features': 0.1, 'min_impurity_decrease': 4.500909928644848e-05, 'validation_fraction': 0.585795551959921, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:33:23,487] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.8602325771048466, 'learning_rate': 0.060666799241958703, 'dropout_rate': 0.4544018342257149, 'n_estimators': 320, 'criterion': 'squared_error', 'ccp_alpha': 0.22931497714889953, 'min_weight_fraction_leaf': 0.36106190454255527, 'max_features': 0.1, 'min_impurity_decrease': 0.0001528555634091728, 'validation_fraction': 0.5817279039264187, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:33:36,078] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7587617437729911, 'learning_rate': 0.04761165440524907, 'dropout_rate': 0.4957903377584335, 'n_estimators': 300, 'criterion': 'squared_error', 'ccp_alpha': 1.080975311316525, 'min_weight_fraction_leaf': 0.3363100713943507, 'max_features': 0.1, 'min_impurity_decrease': 0.00046289489298800726, 'validation_fraction': 0.5377854514350624, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:33:46,594] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.9306795844790319, 'learning_rate': 0.051627622421456736, 'dropout_rate': 0.4234035172725829, 'n_estimators': 252, 'criterion': 'squared_error', 'ccp_alpha': 0.7265789482493736, 'min_weight_fraction_leaf': 0.3769812431626508, 'max_features': 0.1, 'min_impurity_decrease': 4.642862113005286e-05, 'validation_fraction': 0.4739493451385479, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7510729613733905
[I 2024-04-22 03:34:00,320] Trial 89 finished with value: 0.7451295099349646 and parameters: {'subsample': 0.8391283049189849, 'learning_rate': 0.055724086293807554, 'dropout_rate': 0.6569553700677857, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.01877120542983873, 'min_weight_fraction_leaf': 0.32461639571647416, 'max_features': 0.1, 'min_impurity_decrease': 8.851047050185397e-05, 'validation_fraction': 0.6010087752598334, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:34:19,452] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.826829689860655, 'learning_rate': 0.05508607313298636, 'dropout_rate': 0.4747673828195568, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.46861411786043294, 'min_weight_fraction_leaf': 0.3271740396549214, 'max_features': 0.1, 'min_impurity_decrease': 9.545901155149427e-05, 'validation_fraction': 0.5913771141991949, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6995708154506438
[I 2024-04-22 03:34:36,225] Trial 91 finished with value: 0.7237191125293256 and parameters: {'subsample': 0.9670051193547057, 'learning_rate': 0.05358528744281843, 'dropout_rate': 0.658599767424636, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.037871277159682165, 'min_weight_fraction_leaf': 0.28864883630713, 'max_features': 0.1, 'min_impurity_decrease': 0.00022284757650732192, 'validation_fraction': 0.6230196429197797, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:34:47,291] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.04507048157049061, 'dropout_rate': 0.6619274742089222, 'n_estimators': 319, 'criterion': 'squared_error', 'ccp_alpha': 0.1977251065362092, 'min_weight_fraction_leaf': 0.2997333226617717, 'max_features': 0.1, 'min_impurity_decrease': 3.110697272043209e-05, 'validation_fraction': 0.7057224083251947, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:35:00,588] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.8713442146116508, 'learning_rate': 0.056893055161794756, 'dropout_rate': 0.6240038144153928, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.2020936997276668, 'min_weight_fraction_leaf': 0.27879305118961123, 'max_features': 0.1, 'min_impurity_decrease': 0.0002253362395408032, 'validation_fraction': 0.5411649201375784, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 7}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:35:17,140] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.846552766071321, 'learning_rate': 0.05225166033787123, 'dropout_rate': 0.5466158596699147, 'n_estimators': 343, 'criterion': 'squared_error', 'ccp_alpha': 0.5371670207357605, 'min_weight_fraction_leaf': 0.25551392419012386, 'max_features': 0.1, 'min_impurity_decrease': 1.9306777571724905e-05, 'validation_fraction': 0.612298406876781, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:35:34,388] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.7863806056473801, 'learning_rate': 0.06528678713702542, 'dropout_rate': 0.5828268476051283, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.9669214947186134, 'min_weight_fraction_leaf': 0.31565449545198027, 'max_features': 0.1, 'min_impurity_decrease': 9.721858189938487e-05, 'validation_fraction': 0.6404170541911562, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 6}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7680851063829788
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.7167381974248928
[I 2024-04-22 03:35:53,097] Trial 96 finished with value: 0.7361464780146243 and parameters: {'subsample': 0.8988051132134279, 'learning_rate': 0.06223070527189957, 'dropout_rate': 0.5156283651894482, 'n_estimators': 355, 'criterion': 'squared_error', 'ccp_alpha': 0.03101134846799354, 'min_weight_fraction_leaf': 0.34626128365000786, 'max_features': 0.1, 'min_impurity_decrease': 1.3094627017216677e-05, 'validation_fraction': 0.6632572619204413, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:36:00,901] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8930015289701463, 'learning_rate': 0.06902066318585262, 'dropout_rate': 0.6637119170834406, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5827663286593292, 'min_weight_fraction_leaf': 0.34069712252087353, 'max_features': 0.1, 'min_impurity_decrease': 1.0966163456816475e-05, 'validation_fraction': 0.6202090272853855, 'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-22 03:36:11,275] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.8120824030153192, 'learning_rate': 0.06065076232609097, 'dropout_rate': 0.750396388680249, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.2855531941206882, 'max_features': 0.1, 'min_impurity_decrease': 6.3587125691091546e-06, 'validation_fraction': 0.565884480208947, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 75 with value: 0.7593045273013703.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-22 03:36:26,763] A new study created in memory with name: no-name-a42276bc-407c-4254-a44b-fcacc0a984c9

Fold 5 C-index: 0.5
[I 2024-04-22 03:36:26,750] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.9759866968226103, 'learning_rate': 0.06186324982491159, 'dropout_rate': 0.38086979950007127, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 1.2268388380947401, 'min_weight_fraction_leaf': 0.32648395112982853, 'max_features': 0.1, 'min_impurity_decrease': 4.1512935010412314e-05, 'validation_fraction': 0.669722021056952, 'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 75 with value: 0.7593045273013703.


* Best trial for C-index:
 FrozenTrial(number=75, state=TrialState.COMPLETE, values=[0.7593045273013703], datetime_start=datetime.datetime(2024, 4, 22, 3, 30, 3, 739628), datetime_complete=datetime.datetime(2024, 4, 22, 3, 30, 19, 122933), params={'subsample': 0.9197287558651637, 'learning_rate': 0.05159117661647313, 'dropout_rate': 0.5604101432191428, 'n_estimators': 350, 'criterion': 'squared_error', 'ccp_alpha': 0.008821356078039954, 'min_weight_fraction_leaf': 0.26023745967507866, 'max_features': 0.1, 'min_impurity_decrease': 9.803482393630746e-05, 'validation_fraction': 0.8247616419720114, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=75, value=None)


* Best Score for C-index:
 0.7593045273013703

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:36:40,548] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:36:49,272] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:36:57,117] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:37:08,696] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:13,999] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:15,206] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:27,413] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:30,975] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:37:31,469] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24608005079919942
Fold 2 IBS: 0.23042815803611094
Fold 3 IBS: 0.22863801065607092
Fold 4 IBS: 0.24084051984701824
Fold 5 IBS: 0.22855540564358753
[I 2024-04-22 03:38:04,383] Trial 9 finished with value: 0.2349084289963974 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23166000859087926
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-22 03:38:54,789] Trial 10 finished with value: 0.23563424132764627 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:39:50,085] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24715489611868932
Fold 2 IBS: 0.23185086387290396
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-22 03:40:36,770] Trial 12 finished with value: 0.23582817076967802 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:40:59,921] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:41:39,659] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:42:14,225] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:42:33,864] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:43:20,167] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:43:43,453] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:43:48,073] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:44:31,731] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.24710981631467982
Fold 2 IBS: 0.23198582071341375
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-22 03:45:18,591] Trial 21 finished with value: 0.2358286001617127 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2349084289963974.
Fold 1 IBS: 0.2460949705832435
Fold 2 IBS: 0.23011947144053765
Fold 3 IBS: 0.22852853905222809

Fold 4 IBS: 0.24075460977388422
Fold 5 IBS: 0.22861261428074
[I 2024-04-22 03:46:10,620] Trial 22 finished with value: 0.23482204102612672 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:46:53,876] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:47:21,453] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:47:46,279] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:48:25,009] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:48:29,527] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:48:42,854] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:49:17,195] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:49:31,885] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24695000891576355
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-22 03:50:16,953] Trial 31 finished with value: 0.2356643163163706 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24623846601283667
Fold 2 IBS: 0.23034600631535648
Fold 3 IBS: 0.22852247093857828
Fold 4 IBS: 0.24075522979606004
Fold 5 IBS: 0.22871472601162812
[I 2024-04-22 03:51:01,136] Trial 32 finished with value: 0.23491537981489188 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:51:34,311] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:52:09,900] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:52:17,440] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:53:04,064] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:53:05,617] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:53:28,521] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:53:57,039] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:54:25,563] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2466243968963398
Fold 2 IBS: 0.230928831475849
Fold 3 IBS: 0.22863585294540403
Fold 4 IBS: 0.24117285713517794
Fold 5 IBS: 0.22893530922896765
[I 2024-04-22 03:55:09,142] Trial 41 finished with value: 0.23525944953634767 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24629176115681264
Fold 2 IBS: 0.23044441839041935
Fold 3 IBS: 0.22846692796424145
Fold 4 IBS: 0.2408165395500078
Fold 5 IBS: 0.22873017992338907
[I 2024-04-22 03:55:55,766] Trial 42 finished with value: 0.23494996539697408 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:56:47,999] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:57:24,421] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24690838091318074
Fold 2 IBS: 0.231606265379147
Fold 3 IBS: 0.22862607626808185
Fold 4 IBS: 0.24158411302700467
Fold 5 IBS: 0.22903582211104476
[I 2024-04-22 03:58:00,596] Trial 45 finished with value: 0.2355521315396918 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:58:34,649] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:58:48,893] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:58:49,108] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 03:58:57,434] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 03:59:38,540] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24692974063860446
Fold 2 IBS: 0.23163323773848501
Fold 3 IBS: 0.2286226342984277
Fold 4 IBS: 0.24159022036393826
Fold 5 IBS: 0.22903704159821506
[I 2024-04-22 04:00:11,655] Trial 51 finished with value: 0.23556257492753413 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:00:54,524] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2464290885826847
Fold 2 IBS: 0.23073960203048824
Fold 3 IBS: 0.2279244913585667
Fold 4 IBS: 0.2408200570354747
Fold 5 IBS: 0.22834887416862718
[I 2024-04-22 04:01:27,609] Trial 53 finished with value: 0.2348524226351683 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:02:06,006] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:02:40,377] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:03:16,283] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:03:48,459] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:04:36,375] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:05:17,684] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:05:37,062] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:06:05,900] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24682210218858872
Fold 2 IBS: 0.2313482899879881
Fold 3 IBS: 0.2284490764743384
Fold 4 IBS: 0.24135605392900966
Fold 5 IBS: 0.22883648614819466
[I 2024-04-22 04:06:31,232] Trial 62 finished with value: 0.2353624017456239 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:06:58,333] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24645999930951334
Fold 2 IBS: 0.23079036542305653
Fold 3 IBS: 0.22815699680939372
Fold 4 IBS: 0.24117712757037893
Fold 5 IBS: 0.22868044791806658
[I 2024-04-22 04:07:23,863] Trial 64 finished with value: 0.23505298740608183 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-22 04:07:47,876] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:08:14,732] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:08:31,034] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:09:10,857] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:09:43,431] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:10:10,880] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2468431050789432
Fold 2 IBS: 0.23139350861857055
Fold 3 IBS: 0.2284780982446439
Fold 4 IBS: 0.24138770464805553
Fold 5 IBS: 0.22885953849816865
[I 2024-04-22 04:10:36,031] Trial 71 finished with value: 0.23539239101767637 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24699749437820576
Fold 2 IBS: 0.23165218847082278
Fold 3 IBS: 0.22865219650261898
Fold 4 IBS: 0.24159606345259071
Fold 5 IBS: 0.229036727569616
[I 2024-04-22 04:10:54,961] Trial 72 finished with value: 0.2355869340747708 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:10:57,902] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:11:51,492] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:12:12,180] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:12:40,283] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:13:17,434] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:13:34,592] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:14:12,326] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:14:28,867] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24681345447018593
Fold 2 IBS: 0.2313872832399048
Fold 3 IBS: 0.22845032192169396
Fold 4 IBS: 0.24137509385879735
Fold 5 IBS: 0.22882473993565516
[I 2024-04-22 04:14:55,122] Trial 81 finished with value: 0.23537017868524743 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:15:24,255] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:15:56,033] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898042024574092
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293926775107472
[I 2024-04-22 04:16:11,921] Trial 84 finished with value: 0.23592697084005448 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 22 with value: 0.23482204102612672.
Fold 1 IBS: 0.2453657442225769
Fold 2 IBS: 0.22798116508039243
Fold 3 IBS: 0.22690390767406562
Fold 4 IBS: 0.2389258130051501
Fold 5 IBS: 0.22739074180659022
[I 2024-04-22 04:16:52,039] Trial 85 finished with value: 0.23331347435775504 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:17:32,602] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8908016266221349, 'learning_rate': 0.020782252048892114, 'dropout_rate': 0.20248417164561996, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.025928909209021245, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:17:46,982] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953409887733455, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:18:31,822] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.0030671608519508686, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.27772784044341225, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:19:14,531] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9240076064991638, 'learning_rate': 0.036372907201929795, 'dropout_rate': 0.16604269499086277, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.6288732373244443, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.8456629128553931, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:19:57,447] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.22333957383529762, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24645393673926166
Fold 2 IBS: 0.23072722650379557
Fold 3 IBS: 0.22798170496299774
Fold 4 IBS: 0.240998787435527
Fold 5 IBS: 0.22853988200436828
[I 2024-04-22 04:20:39,696] Trial 91 finished with value: 0.23494030752919004 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.01642165444052923, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.901410266511097, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:21:20,934] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.012238074680872561, 'dropout_rate': 0.2583752131981347, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 2.0262506829884978e-07, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:22:03,870] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9444060832329966, 'learning_rate': 0.017856303491279684, 'dropout_rate': 0.30303355573944185, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.011908761872398903, 'max_features': 'auto', 'min_impurity_decrease': 6.055732421263935e-07, 'validation_fraction': 0.864284511598723, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:22:38,288] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8821760782294449, 'learning_rate': 0.005785552173633914, 'dropout_rate': 0.28058975756978766, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.8506324992317083, 'min_weight_fraction_leaf': 0.04622694094641695, 'max_features': None, 'min_impurity_decrease': 1.3402986834437386e-07, 'validation_fraction': 0.8985100287316004, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:23:21,344] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9761707513926794, 'learning_rate': 0.019567902784876703, 'dropout_rate': 0.3201948574529592, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.0386964570043107, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9417888137501867, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.246384587613419
Fold 2 IBS: 0.22951287202587697
Fold 3 IBS: 0.22811619002717504
Fold 4 IBS: 0.2407635260296621
Fold 5 IBS: 0.22839097135136704
[I 2024-04-22 04:23:55,789] Trial 96 finished with value: 0.23463362940950003 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.01055205151962401, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.09708890262536518, 'max_features': 'auto', 'min_impurity_decrease': 3.7395479538673736e-07, 'validation_fraction': 0.992337544991608, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:24:30,537] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.010954886262406833, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 1.603167122698403, 'min_weight_fraction_leaf': 0.06013220413302209, 'max_features': 'auto', 'min_impurity_decrease': 3.972456306049239e-07, 'validation_fraction': 0.9976245698846969, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-22 04:24:57,816] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8505038223267275, 'learning_rate': 0.013402809510359784, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 0.25666428673598457, 'min_weight_fraction_leaf': 0.1129024126904408, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.9625603744870045, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 85 with value: 0.23331347435775504.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-22 04:25:39,883] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.06808689488183181, 'dropout_rate': 0.25443633448028735, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5386043790221791, 'min_weight_fraction_leaf': 0.03403879613376609, 'max_features': 'auto', 'min_impurity_decrease': 8.69596280226011e-07, 'validation_fraction': 0.9221483446288596, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.23331347435775504.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23331347435775504], datetime_start=datetime.datetime(2024, 4, 22, 4, 16, 11, 926547), datetime_complete=datetime.datetime(2024, 4, 22, 4, 16, 52, 37999), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23331347435775504

In [68]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [69]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.759
train_ibs:  0.233

#### Test

In [70]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [71]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.008821356078039954,
                                 criterion='squared_error',
                                 dropout_rate=0.5604101432191428,
                                 learning_rate=0.05159117661647313, max_depth=4,
                                 max_features=0.1, max_leaf_nodes=18,
                                 min_impurity_decrease=9.803482393630746e-05,
                                 min_samples_leaf=7, min_samples_split=8,
                                 min_weight_fraction_leaf=0.26023745967507866,
                                 n_estimators=350, random_state=123,
                                 subsample=0.9197287558651637,
                                 validation_fraction=0.8247616419720114)

C-index score: 0.586

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.228

In [72]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [73]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [74]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-22 04:25:52,094] A new study created in memory with name: no-name-5875394d-a906-4215-8301-5c1e3173736b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:25:52,795] Trial 0 finished with value: 0.6542270796438157 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6542270796438157.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:25:58,249] Trial 1 finished with value: 0.6418764820342538 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6542270796438157.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6394849785407726
[I 2024-04-22 04:25:59,321] Trial 2 finished with value: 0.6627548096515538 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6627548096515538.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 04:26:00,789] Trial 3 finished with value: 0.6684342086046409 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6684342086046409.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:26:03,317] Trial 4 finished with value: 0.6850951693484119 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6850951693484119.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:26:06,315] Trial 5 finished with value: 0.6542270796438157 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6850951693484119.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:26:07,485] Trial 6 finished with value: 0.6418764820342538 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6850951693484119.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6394849785407726
[I 2024-04-22 04:26:07,730] Trial 7 finished with value: 0.6676977754310215 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6850951693484119.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6351931330472103
[I 2024-04-22 04:26:09,341] Trial 8 finished with value: 0.6706416877011303 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6850951693484119.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6351931330472103
[I 2024-04-22 04:26:14,542] Trial 9 finished with value: 0.6765991345096409 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6850951693484119.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:26:17,753] Trial 10 finished with value: 0.7022145727923927 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.7022145727923927.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:26:21,418] Trial 11 finished with value: 0.6999947603208084 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 10 with value: 0.7022145727923927.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:26:24,642] Trial 12 finished with value: 0.7008605616752811 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 10 with value: 0.7022145727923927.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:26:28,550] Trial 13 finished with value: 0.614616551607913 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.20904030306390659, 'n_estimators': 372, 'learning_rate': 0.007730532223257889}. Best is trial 10 with value: 0.7022145727923927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:26:31,498] Trial 14 finished with value: 0.7046233294880044 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.28605856894907633, 'n_estimators': 309, 'learning_rate': 0.09964553963945819}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:26:34,319] Trial 15 finished with value: 0.6891692733853022 and parameters: {'subsample': 0.25820782722012925, 'dropout_rate': 0.2764445583790512, 'n_estimators': 283, 'learning_rate': 0.0020295313566686345}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.648068669527897
[I 2024-04-22 04:26:38,604] Trial 16 finished with value: 0.6961846834413341 and parameters: {'subsample': 0.25470623831733574, 'dropout_rate': 0.6585857848587966, 'n_estimators': 417, 'learning_rate': 0.01911977848093384}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6394849785407726
[I 2024-04-22 04:26:43,361] Trial 17 finished with value: 0.6920495738846265 and parameters: {'subsample': 0.35331796904627844, 'dropout_rate': 0.2598529888272882, 'n_estimators': 415, 'learning_rate': 0.036208666639295596}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:26:43,510] Trial 18 finished with value: 0.6870937783769332 and parameters: {'subsample': 0.1732298585045983, 'dropout_rate': 0.3447914306565574, 'n_estimators': 7, 'learning_rate': 0.08226012284775}. Best is trial 14 with value: 0.7046233294880044.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:26:44,394] Trial 19 finished with value: 0.7034414058549538 and parameters: {'subsample': 0.3662035355915435, 'dropout_rate': 0.6899537536342808, 'n_estimators': 131, 'learning_rate': 0.016199175505418453}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:26:45,128] Trial 20 finished with value: 0.6778774454648014 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.7592776498228061, 'n_estimators': 112, 'learning_rate': 0.017331004877487094}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:26:47,280] Trial 21 finished with value: 0.6997668533705743 and parameters: {'subsample': 0.19858154566104463, 'dropout_rate': 0.6422211515551133, 'n_estimators': 251, 'learning_rate': 0.008195978446847873}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6351931330472103
[I 2024-04-22 04:26:47,778] Trial 22 finished with value: 0.6953443359350001 and parameters: {'subsample': 0.3174393511919961, 'dropout_rate': 0.7353936502611795, 'n_estimators': 88, 'learning_rate': 0.0017102891257744137}. Best is trial 14 with value: 0.7046233294880044.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:26:50,819] Trial 23 finished with value: 0.7046635372950899 and parameters: {'subsample': 0.17211361795283012, 'dropout_rate': 0.5448333949645787, 'n_estimators': 330, 'learning_rate': 0.030336122223843992}. Best is trial 23 with value: 0.7046635372950899.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:26:54,309] Trial 24 finished with value: 0.7041924173344334 and parameters: {'subsample': 0.1004496298176178, 'dropout_rate': 0.5566658728636904, 'n_estimators': 354, 'learning_rate': 0.030479994950545524}. Best is trial 23 with value: 0.7046635372950899.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:26:57,965] Trial 25 finished with value: 0.7033446375723392 and parameters: {'subsample': 0.12679236768550098, 'dropout_rate': 0.5575045510073942, 'n_estimators': 376, 'learning_rate': 0.039275040442641955}. Best is trial 23 with value: 0.7046635372950899.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:27:00,979] Trial 26 finished with value: 0.6987530362984373 and parameters: {'subsample': 0.21611488991563177, 'dropout_rate': 0.5669682671953504, 'n_estimators': 341, 'learning_rate': 0.027397325386072348}. Best is trial 23 with value: 0.7046635372950899.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6866952789699571
[I 2024-04-22 04:27:04,798] Trial 27 finished with value: 0.7064989860301949 and parameters: {'subsample': 0.10012589049799628, 'dropout_rate': 0.9861686560685959, 'n_estimators': 439, 'learning_rate': 0.04118427575599055}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 04:27:08,977] Trial 28 finished with value: 0.6533687105451031 and parameters: {'subsample': 0.628241587571477, 'dropout_rate': 0.8178252892822001, 'n_estimators': 434, 'learning_rate': 0.04382640377830667}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:27:12,472] Trial 29 finished with value: 0.6278080409696151 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.9430576733480622, 'n_estimators': 432, 'learning_rate': 0.06046208382653473}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6394849785407726
[I 2024-04-22 04:27:14,291] Trial 30 finished with value: 0.6697979291402684 and parameters: {'subsample': 0.40859979232022925, 'dropout_rate': 0.3577780272974884, 'n_estimators': 223, 'learning_rate': 0.045171838984618004}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:27:18,224] Trial 31 finished with value: 0.7022760021552663 and parameters: {'subsample': 0.10788445841363141, 'dropout_rate': 0.4440149129718297, 'n_estimators': 384, 'learning_rate': 0.03192536022841976}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:27:23,126] Trial 32 finished with value: 0.7063218762236646 and parameters: {'subsample': 0.17097119411144196, 'dropout_rate': 0.9680856357530159, 'n_estimators': 471, 'learning_rate': 0.027672324604423097}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:27:27,598] Trial 33 finished with value: 0.6941313485571105 and parameters: {'subsample': 0.29329754516460305, 'dropout_rate': 0.9450206248252199, 'n_estimators': 485, 'learning_rate': 0.03865746467084896}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6437768240343348
[I 2024-04-22 04:27:31,384] Trial 34 finished with value: 0.697948494437452 and parameters: {'subsample': 0.20097738776716928, 'dropout_rate': 0.9877201525163405, 'n_estimators': 447, 'learning_rate': 0.024734341677464432}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:27:35,470] Trial 35 finished with value: 0.7047319750706674 and parameters: {'subsample': 0.1726500020021379, 'dropout_rate': 0.9999777196819869, 'n_estimators': 464, 'learning_rate': 0.05885752590955451}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6351931330472103
[I 2024-04-22 04:27:40,424] Trial 36 finished with value: 0.6832641518278003 and parameters: {'subsample': 0.43092545164422086, 'dropout_rate': 0.8327796770006013, 'n_estimators': 495, 'learning_rate': 0.06109697238030094}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:27:44,502] Trial 37 finished with value: 0.7005598312219942 and parameters: {'subsample': 0.23148584376616962, 'dropout_rate': 0.9601698866237893, 'n_estimators': 462, 'learning_rate': 0.0680999354634412}. Best is trial 27 with value: 0.7064989860301949.

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:27:47,766] Trial 38 finished with value: 0.700606904020687 and parameters: {'subsample': 0.31203656964523796, 'dropout_rate': 0.8980655864271353, 'n_estimators': 400, 'learning_rate': 0.05631197114963114}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:27:52,134] Trial 39 finished with value: 0.6982674327867653 and parameters: {'subsample': 0.1905083262956939, 'dropout_rate': 0.77311283324353, 'n_estimators': 457, 'learning_rate': 0.04852656631898444}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 04:27:55,930] Trial 40 finished with value: 0.6684884596854241 and parameters: {'subsample': 0.584963991203977, 'dropout_rate': 0.8876154533864683, 'n_estimators': 407, 'learning_rate': 0.06937946111275661}. Best is trial 27 with value: 0.7064989860301949.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:27:58,563] Trial 41 finished with value: 0.7105228173049826 and parameters: {'subsample': 0.13882130076067578, 'dropout_rate': 0.9909925207120113, 'n_estimators': 339, 'learning_rate': 0.07742964930395986}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:28:01,081] Trial 42 finished with value: 0.703782998415932 and parameters: {'subsample': 0.15473577218850043, 'dropout_rate': 0.9954113790512982, 'n_estimators': 339, 'learning_rate': 0.07856398138275451}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:28:06,198] Trial 43 finished with value: 0.7038844921647945 and parameters: {'subsample': 0.15791932066060616, 'dropout_rate': 0.9263356484235219, 'n_estimators': 496, 'learning_rate': 0.08692240469608553}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:28:10,715] Trial 44 finished with value: 0.6973005615264863 and parameters: {'subsample': 0.27181789512250165, 'dropout_rate': 0.8472746127845155, 'n_estimators': 470, 'learning_rate': 0.05478942222109011}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.648068669527897
[I 2024-04-22 04:28:13,746] Trial 45 finished with value: 0.6978651921503543 and parameters: {'subsample': 0.23872695728048815, 'dropout_rate': 0.9979343076793918, 'n_estimators': 395, 'learning_rate': 0.03562489950771264}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:28:17,817] Trial 46 finished with value: 0.700211908065038 and parameters: {'subsample': 0.15332821143109293, 'dropout_rate': 0.7997836433466274, 'n_estimators': 441, 'learning_rate': 0.0670571491059437}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:28:19,937] Trial 47 finished with value: 0.6418764820342538 and parameters: {'subsample': 0.7961983953812717, 'dropout_rate': 0.49255274679437616, 'n_estimators': 275, 'learning_rate': 0.07363807501210452}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:28:22,725] Trial 48 finished with value: 0.6997883453342938 and parameters: {'subsample': 0.14751149565728586, 'dropout_rate': 0.8795384324926829, 'n_estimators': 356, 'learning_rate': 0.020637661104988395}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:28:26,046] Trial 49 finished with value: 0.6973111508631046 and parameters: {'subsample': 0.21339041743427045, 'dropout_rate': 0.9636574620303712, 'n_estimators': 420, 'learning_rate': 0.04918005289120828}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6394849785407726
[I 2024-04-22 04:28:28,638] Trial 50 finished with value: 0.6921185624900952 and parameters: {'subsample': 0.32908238366786347, 'dropout_rate': 0.9180765546733092, 'n_estimators': 328, 'learning_rate': 0.0923360832084614}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:28:32,006] Trial 51 finished with value: 0.7031241628778652 and parameters: {'subsample': 0.13390340845944282, 'dropout_rate': 0.2045375768689921, 'n_estimators': 294, 'learning_rate': 0.09784207281528857}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:28:35,254] Trial 52 finished with value: 0.7069816864346786 and parameters: {'subsample': 0.18885542903662317, 'dropout_rate': 0.29718388767121895, 'n_estimators': 317, 'learning_rate': 0.08224750094124994}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:28:38,574] Trial 53 finished with value: 0.7051743406812309 and parameters: {'subsample': 0.1808422235627478, 'dropout_rate': 0.4118092780541023, 'n_estimators': 317, 'learning_rate': 0.08340522715501156}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6394849785407726
[I 2024-04-22 04:28:40,218] Trial 54 finished with value: 0.6904233162563898 and parameters: {'subsample': 0.27028686682229885, 'dropout_rate': 0.3213748949343307, 'n_estimators': 214, 'learning_rate': 0.0820035295604041}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:28:42,265] Trial 55 finished with value: 0.6991690397865865 and parameters: {'subsample': 0.2327731267436028, 'dropout_rate': 0.4127209398452274, 'n_estimators': 255, 'learning_rate': 0.07879075947007325}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:28:45,380] Trial 56 finished with value: 0.700741173320875 and parameters: {'subsample': 0.1934949224084939, 'dropout_rate': 0.22158267164148931, 'n_estimators': 312, 'learning_rate': 0.08712021375996278}. Best is trial 41 with value: 0.7105228173049826.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:28:48,939] Trial 57 finished with value: 0.6899196911523392 and parameters: {'subsample': 0.2888110376335854, 'dropout_rate': 0.38893787727265927, 'n_estimators': 364, 'learning_rate': 0.09122073227399896}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 04:28:50,176] Trial 58 finished with value: 0.6676373958556369 and parameters: {'subsample': 0.5228967921490845, 'dropout_rate': 0.15158538437050884, 'n_estimators': 176, 'learning_rate': 0.07964961755424188}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:28:55,493] Trial 59 finished with value: 0.7047749425638448 and parameters: {'subsample': 0.10299141238250675, 'dropout_rate': 0.49690186988978524, 'n_estimators': 480, 'learning_rate': 0.06352393210371998}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:00,629] Trial 60 finished with value: 0.7049929379941866 and parameters: {'subsample': 0.128499690786652, 'dropout_rate': 0.6106362838970125, 'n_estimators': 484, 'learning_rate': 0.06443536746939897}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:06,149] Trial 61 finished with value: 0.704217744195737 and parameters: {'subsample': 0.12903538248381946, 'dropout_rate': 0.6053689489356847, 'n_estimators': 477, 'learning_rate': 0.07074746856924126}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:12,298] Trial 62 finished with value: 0.7064417048553884 and parameters: {'subsample': 0.11092872039144577, 'dropout_rate': 0.5037566458514784, 'n_estimators': 481, 'learning_rate': 0.06345682241075902}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:29:17,677] Trial 63 finished with value: 0.7031194638599072 and parameters: {'subsample': 0.1360982994214226, 'dropout_rate': 0.4341536902890213, 'n_estimators': 451, 'learning_rate': 0.07615388230267464}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:29:19,432] Trial 64 finished with value: 0.6990025621992259 and parameters: {'subsample': 0.20153163927517673, 'dropout_rate': 0.47194422921568385, 'n_estimators': 234, 'learning_rate': 0.08425932852246905}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:29:24,104] Trial 65 finished with value: 0.7048225826266904 and parameters: {'subsample': 0.17643720785669942, 'dropout_rate': 0.3171226119727971, 'n_estimators': 424, 'learning_rate': 0.06618690466815137}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:27,764] Trial 66 finished with value: 0.7065248801556512 and parameters: {'subsample': 0.1007940959727623, 'dropout_rate': 0.5127020851093624, 'n_estimators': 381, 'learning_rate': 0.07538033540057507}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:31,480] Trial 67 finished with value: 0.7057280674066473 and parameters: {'subsample': 0.10295684693875845, 'dropout_rate': 0.5017731942819592, 'n_estimators': 385, 'learning_rate': 0.07173640774666014}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:35,297] Trial 68 finished with value: 0.7057280674066473 and parameters: {'subsample': 0.10272757327581118, 'dropout_rate': 0.5177585024261813, 'n_estimators': 385, 'learning_rate': 0.07256648925210166}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6437768240343348
[I 2024-04-22 04:29:38,852] Trial 69 finished with value: 0.6994298934288826 and parameters: {'subsample': 0.2485885978455818, 'dropout_rate': 0.7250794752160086, 'n_estimators': 350, 'learning_rate': 0.07585274128785724}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.623574144486692
Fold 5 C-index: 0.6244635193133047
[I 2024-04-22 04:29:43,243] Trial 70 finished with value: 0.614616551607913 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.5905257487531911, 'n_estimators': 392, 'learning_rate': 0.07072873387793481}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:29:47,064] Trial 71 finished with value: 0.705764423881887 and parameters: {'subsample': 0.10668014930774397, 'dropout_rate': 0.5191338336663401, 'n_estimators': 375, 'learning_rate': 0.07274000681689437}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:29:51,399] Trial 72 finished with value: 0.7034352451283622 and parameters: {'subsample': 0.14622960367844462, 'dropout_rate': 0.5263727153785562, 'n_estimators': 410, 'learning_rate': 0.07563034165253796}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:29:54,936] Trial 73 finished with value: 0.7022760021552663 and parameters: {'subsample': 0.10321312171423877, 'dropout_rate': 0.47908790002181884, 'n_estimators': 367, 'learning_rate': 0.01279681180237691}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:29:59,087] Trial 74 finished with value: 0.7050756894513933 and parameters: {'subsample': 0.1299436460892578, 'dropout_rate': 0.648915407300676, 'n_estimators': 431, 'learning_rate': 0.0788889828261788}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:30:02,556] Trial 75 finished with value: 0.7013673602944512 and parameters: {'subsample': 0.16529036118896168, 'dropout_rate': 0.5801460160773009, 'n_estimators': 378, 'learning_rate': 0.07266099436146455}. Best is trial 41 with value: 0.7105228173049826.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:30:05,426] Trial 76 finished with value: 0.6990748348723874 and parameters: {'subsample': 0.20713186843510073, 'dropout_rate': 0.6894953341707026, 'n_estimators': 343, 'learning_rate': 0.052321415637327034}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:30:08,259] Trial 77 finished with value: 0.7023671769754419 and parameters: {'subsample': 0.10011531435162725, 'dropout_rate': 0.5340794382591971, 'n_estimators': 293, 'learning_rate': 0.05790059363448126}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:30:13,236] Trial 78 finished with value: 0.7012371121954957 and parameters: {'subsample': 0.22123372140926736, 'dropout_rate': 0.459666503985583, 'n_estimators': 442, 'learning_rate': 0.06327592839403677}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6201716738197425
[I 2024-04-22 04:30:17,613] Trial 79 finished with value: 0.6621139576933922 and parameters: {'subsample': 0.6745068465882641, 'dropout_rate': 0.5114316528786205, 'n_estimators': 403, 'learning_rate': 0.04470103610651182}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6104651162790697
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6351931330472103
[I 2024-04-22 04:30:20,954] Trial 80 finished with value: 0.6783012621692155 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.6172580358250807, 'n_estimators': 372, 'learning_rate': 0.041625272231979406}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6781115879828327
[I 2024-04-22 04:30:24,964] Trial 81 finished with value: 0.7057750132185052 and parameters: {'subsample': 0.12665298615737547, 'dropout_rate': 0.526254762713732, 'n_estimators': 395, 'learning_rate': 0.07236160225834602}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:30:29,054] Trial 82 finished with value: 0.6993392252846964 and parameters: {'subsample': 0.15621620195475386, 'dropout_rate': 0.5549992841846945, 'n_estimators': 416, 'learning_rate': 0.06924388827245567}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:30:32,907] Trial 83 finished with value: 0.7055319449005296 and parameters: {'subsample': 0.12485560132630587, 'dropout_rate': 0.4334030341813008, 'n_estimators': 389, 'learning_rate': 0.08073956854070687}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6523605150214592
[I 2024-04-22 04:30:36,754] Trial 84 finished with value: 0.7030152368732425 and parameters: {'subsample': 0.17890082528024825, 'dropout_rate': 0.9673848952293052, 'n_estimators': 456, 'learning_rate': 0.0859354033978405}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6738197424892703
[I 2024-04-22 04:30:41,183] Trial 85 finished with value: 0.7034352451283622 and parameters: {'subsample': 0.14552274178192814, 'dropout_rate': 0.5052169517849318, 'n_estimators': 406, 'learning_rate': 0.07658560061130348}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-22 04:30:45,386] Trial 86 finished with value: 0.709867875981313 and parameters: {'subsample': 0.1167170076421751, 'dropout_rate': 0.6317123231952305, 'n_estimators': 431, 'learning_rate': 0.07149219367785196}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:30:50,650] Trial 87 finished with value: 0.7015700673702167 and parameters: {'subsample': 0.18758680277897016, 'dropout_rate': 0.8605849461447841, 'n_estimators': 468, 'learning_rate': 0.06559088056864305}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6566523605150214
[I 2024-04-22 04:30:56,898] Trial 88 finished with value: 0.7031342013845924 and parameters: {'subsample': 0.12086726695301638, 'dropout_rate': 0.3768468273870369, 'n_estimators': 499, 'learning_rate': 0.07403412599053018}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6609442060085837
[I 2024-04-22 04:31:00,638] Trial 89 finished with value: 0.7038013168645317 and parameters: {'subsample': 0.15723041673001642, 'dropout_rate': 0.9193147019979806, 'n_estimators': 437, 'learning_rate': 0.025056796383218}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6437768240343348
[I 2024-04-22 04:31:03,197] Trial 90 finished with value: 0.6962858803339754 and parameters: {'subsample': 0.22044498271495122, 'dropout_rate': 0.9781205279423844, 'n_estimators': 355, 'learning_rate': 0.0337312318803277}. Best is trial 41 with value: 0.7105228173049826.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6824034334763949
[I 2024-04-22 04:31:05,595] Trial 91 finished with value: 0.7115801691344495 and parameters: {'subsample': 0.12070239642485954, 'dropout_rate': 0.9439800508898758, 'n_estimators': 332, 'learning_rate': 0.07082775315124301}. Best is trial 91 with value: 0.7115801691344495.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:31:08,240] Trial 92 finished with value: 0.7106165819418637 and parameters: {'subsample': 0.13484205316891038, 'dropout_rate': 0.9469627233448897, 'n_estimators': 333, 'learning_rate': 0.06795071330570526}. Best is trial 91 with value: 0.7115801691344495.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:31:10,867] Trial 93 finished with value: 0.7104469472736449 and parameters: {'subsample': 0.1421221870403269, 'dropout_rate': 0.9449771234172557, 'n_estimators': 324, 'learning_rate': 0.0671475974378978}. Best is trial 91 with value: 0.7115801691344495.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:31:12,895] Trial 94 finished with value: 0.7071407317662791 and parameters: {'subsample': 0.1666516975876515, 'dropout_rate': 0.9447108787512812, 'n_estimators': 299, 'learning_rate': 0.07717695731667967}. Best is trial 91 with value: 0.7115801691344495.

Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:31:14,937] Trial 95 finished with value: 0.7096717534751953 and parameters: {'subsample': 0.14069776602064255, 'dropout_rate': 0.9420701351822005, 'n_estimators': 303, 'learning_rate': 0.0678338442101042}. Best is trial 91 with value: 0.7115801691344495.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6695278969957081
[I 2024-04-22 04:31:17,158] Trial 96 finished with value: 0.7096717534751953 and parameters: {'subsample': 0.14102057313519806, 'dropout_rate': 0.9380099788872344, 'n_estimators': 303, 'learning_rate': 0.06838946303068351}. Best is trial 91 with value: 0.7115801691344495.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:31:18,929] Trial 97 finished with value: 0.7013350250204438 and parameters: {'subsample': 0.19253827146205105, 'dropout_rate': 0.9336646529331861, 'n_estimators': 271, 'learning_rate': 0.06924701959479886}. Best is trial 91 with value: 0.7115801691344495.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6437768240343348
[I 2024-04-22 04:31:20,989] Trial 98 finished with value: 0.698654699630433 and parameters: {'subsample': 0.24614615470828544, 'dropout_rate': 0.9077870817005708, 'n_estimators': 299, 'learning_rate': 0.06714355390077242}. Best is trial 91 with value: 0.7115801691344495.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7604562737642585

[I 2024-04-22 04:31:23,637] A new study created in memory with name: no-name-4eeac411-c2cb-4923-b87c-a8d2b435f6f0

Fold 5 C-index: 0.6652360515021459
[I 2024-04-22 04:31:23,626] Trial 99 finished with value: 0.7030513229405508 and parameters: {'subsample': 0.14400150575473183, 'dropout_rate': 0.8760854480524463, 'n_estimators': 321, 'learning_rate': 0.06037288112982502}. Best is trial 91 with value: 0.7115801691344495.


* Best trial for C-index:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.7115801691344495], datetime_start=datetime.datetime(2024, 4, 22, 4, 31, 3, 203764), datetime_complete=datetime.datetime(2024, 4, 22, 4, 31, 5, 594787), params={'subsample': 0.12070239642485954, 'dropout_rate': 0.9439800508898758, 'n_estimators': 332, 'learning_rate': 0.07082775315124301}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=91, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.12070239642485954, 'dropout_rate': 0.9439800508898758, 'n_estimators': 332, 'learning_rate': 0.07082775315124301}


* Best Score for C-index:
 0.7115801691344495

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.27853337116308474
Fold 2 IBS: 0.2215528390328831
Fold 3 IBS: 0.20264770448336145
Fold 4 IBS: 0.25163337883839504
Fold 5 IBS: 0.2014656244155287
[I 2024-04-22 04:31:24,429] Trial 0 finished with value: 0.2311665835866506 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2311665835866506.
Fold 1 IBS: 0.33825562269814186
Fold 2 IBS: 0.3039651241989302
Fold 3 IBS: 0.247828008187909
Fold 4 IBS: 0.30915572500285826
Fold 5 IBS: 0.23687849009592335
[I 2024-04-22 04:31:30,095] Trial 1 finished with value: 0.2872165940367525 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2311665835866506.
Fold 1 IBS: 0.3172980678894649
Fold 2 IBS: 0.25679934623148076
Fold 3 IBS: 0.21662967527154678
Fold 4 IBS: 0.27074142141940405
Fold 5 IBS: 0.20944747172648706
[I 2024-04-22 04:31:31,258] Trial 2 finished with value: 0.25418319650767673 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2311665835866506.
Fold 1 IBS: 0.3172838922392006
Fold 2 IBS: 0.2622578238933627
Fold 3 IBS: 0.2160246745751651
Fold 4 IBS: 0.26889678872009826
Fold 5 IBS: 0.21433074681844114
[I 2024-04-22 04:31:32,813] Trial 3 finished with value: 0.2557587852492536 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2311665835866506.
Fold 1 IBS: 0.30994123875620133
Fold 2 IBS: 0.2657775138225991
Fold 3 IBS: 0.20447266032614345
Fold 4 IBS: 0.2522000644064627
Fold 5 IBS: 0.21098999882338107
[I 2024-04-22 04:31:35,027] Trial 4 finished with value: 0.2486762952269575 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2311665835866506.
Fold 1 IBS: 0.3355094998824222
Fold 2 IBS: 0.2898350421535593
Fold 3 IBS: 0.2423047753821743
Fold 4 IBS: 0.3040720704251516
Fold 5 IBS: 0.22731959827140763
[I 2024-04-22 04:31:37,831] Trial 5 finished with value: 0.27980819722294303 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2311665835866506.
Fold 1 IBS: 0.2589955150907868
Fold 2 IBS: 0.21694712185454476
Fold 3 IBS: 0.20422787214805443
Fold 4 IBS: 0.24056455735174984
Fold 5 IBS: 0.204476606270151
[I 2024-04-22 04:31:39,190] Trial 6 finished with value: 0.2250423345430574 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2250423345430574.
Fold 1 IBS: 0.2427153106395454
Fold 2 IBS: 0.2201567462995922
Fold 3 IBS: 0.20939182952065316
Fold 4 IBS: 0.2330813153871191
Fold 5 IBS: 0.21354182330159757
[I 2024-04-22 04:31:39,494] Trial 7 finished with value: 0.2237774050297015 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.27888794440964076
Fold 2 IBS: 0.22527176931331588
Fold 3 IBS: 0.19915570692600804
Fold 4 IBS: 0.2479274785601656
Fold 5 IBS: 0.2011160859788768
[I 2024-04-22 04:31:41,081] Trial 8 finished with value: 0.23047179703760143 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.3300401079560088
Fold 2 IBS: 0.29558947981965256
Fold 3 IBS: 0.23444250816602094
Fold 4 IBS: 0.2820480810929351
Fold 5 IBS: 0.22964179320569172
[I 2024-04-22 04:31:45,113] Trial 9 finished with value: 0.27435239404806183 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23166509292012982
Fold 3 IBS: 0.22856182093970995
Fold 4 IBS: 0.24171407848753257
Fold 5 IBS: 0.22900918733397618
[I 2024-04-22 04:31:45,321] Trial 10 finished with value: 0.23559710516658364 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.24687652993070414
Fold 2 IBS: 0.23169837345802843
Fold 3 IBS: 0.22803828196828552
Fold 4 IBS: 0.24151517366938874
Fold 5 IBS: 0.2286469874829567
[I 2024-04-22 04:31:45,458] Trial 11 finished with value: 0.23535506930187272 and parameters: {'subsample': 0.1386942949634342, 'dropout_rate': 0.7203378565511919, 'n_estimators': 2, 'learning_rate': 0.02740367873070984}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.29364114463865254
Fold 2 IBS: 0.24001529739855382
Fold 3 IBS: 0.19683434814629594
Fold 4 IBS: 0.2534816793333557
Fold 5 IBS: 0.20387954893241156
[I 2024-04-22 04:31:46,074] Trial 12 finished with value: 0.2375704036898539 and parameters: {'subsample': 0.3093590690380103, 'dropout_rate': 0.6721285244531343, 'n_estimators': 106, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.3066842143220508
Fold 2 IBS: 0.23401842282267074
Fold 3 IBS: 0.21233569023363008
Fold 4 IBS: 0.2744498736844971
Fold 5 IBS: 0.2038355228515873
[I 2024-04-22 04:31:48,694] Trial 13 finished with value: 0.24626474478288723 and parameters: {'subsample': 0.9456596107613977, 'dropout_rate': 0.3965317902775882, 'n_estimators': 296, 'learning_rate': 0.032095681908207524}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.24404114599530402
Fold 2 IBS: 0.22295870184744684
Fold 3 IBS: 0.2176668436693881
Fold 4 IBS: 0.23646890221396158
Fold 5 IBS: 0.21872786454713966
[I 2024-04-22 04:31:49,230] Trial 14 finished with value: 0.227972691654648 and parameters: {'subsample': 0.8561218139289557, 'dropout_rate': 0.6257121219137264, 'n_estimators': 93, 'learning_rate': 0.014498977723931744}. Best is trial 7 with value: 0.2237774050297015.
Fold 1 IBS: 0.24389705585948024
Fold 2 IBS: 0.2199559466322017
Fold 3 IBS: 0.2032856612173705
Fold 4 IBS: 0.23237587278103547
Fold 5 IBS: 0.20928572225459835
[I 2024-04-22 04:31:49,689] Trial 15 finished with value: 0.22176005174893723 and parameters: {'subsample': 0.3216102885686667, 'dropout_rate': 0.29225189689731357, 'n_estimators': 71, 'learning_rate': 0.041453433759673766}. Best is trial 15 with value: 0.22176005174893723.
Fold 1 IBS: 0.24175823078943662
Fold 2 IBS: 0.22045648110382673
Fold 3 IBS: 0.20702309541342326
Fold 4 IBS: 0.23165562810320844
Fold 5 IBS: 0.21123885621323654
[I 2024-04-22 04:31:50,074] Trial 16 finished with value: 0.22242645832462632 and parameters: {'subsample': 0.3629956613085432, 'dropout_rate': 0.10250266376462913, 'n_estimators': 60, 'learning_rate': 0.04490959886825815}. Best is trial 15 with value: 0.22176005174893723.
Fold 1 IBS: 0.23859667708807278
Fold 2 IBS: 0.21951851630431016
Fold 3 IBS: 0.20468972520454526
Fold 4 IBS: 0.23093163786347248
Fold 5 IBS: 0.2112222656261764
[I 2024-04-22 04:31:50,497] Trial 17 finished with value: 0.22099176441731544 and parameters: {'subsample': 0.17085174271948028, 'dropout_rate': 0.10239296101143325, 'n_estimators': 63, 'learning_rate': 0.04434161343977782}. Best is trial 17 with value: 0.22099176441731544.
Fold 1 IBS: 0.29493370740851316
Fold 2 IBS: 0.2458616162568508
Fold 3 IBS: 0.19288166581166716
Fold 4 IBS: 0.24029489881358843
Fold 5 IBS: 0.2009630148013399
[I 2024-04-22 04:31:51,332] Trial 18 finished with value: 0.2349869806183919 and parameters: {'subsample': 0.18450050665129242, 'dropout_rate': 0.23861314529106523, 'n_estimators': 127, 'learning_rate': 0.09446493878020829}. Best is trial 17 with value: 0.22099176441731544.
Fold 1 IBS: 0.28589440918338777

Fold 2 IBS: 0.24692558937073866
Fold 3 IBS: 0.1831671126898814
Fold 4 IBS: 0.2365485137021223
Fold 5 IBS: 0.20090181760153744
[I 2024-04-22 04:31:54,742] Trial 19 finished with value: 0.2306874885095335 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.2379003838874303, 'n_estimators': 341, 'learning_rate': 0.0387255870496736}. Best is trial 17 with value: 0.22099176441731544.
Fold 1 IBS: 0.24218906835325213
Fold 2 IBS: 0.2194593130968425
Fold 3 IBS: 0.20656862313365773
Fold 4 IBS: 0.2303446155463364
Fold 5 IBS: 0.21170279872915151
[I 2024-04-22 04:31:55,759] Trial 20 finished with value: 0.22205288377184806 and parameters: {'subsample': 0.23495674638237363, 'dropout_rate': 0.3086154579845777, 'n_estimators': 152, 'learning_rate': 0.017331004877487094}. Best is trial 17 with value: 0.22099176441731544.
Fold 1 IBS: 0.2409005562559852
Fold 2 IBS: 0.21978647474174687
Fold 3 IBS: 0.2080985964786667
Fold 4 IBS: 0.2300598372843996
Fold 5 IBS: 0.21296163826109915
[I 2024-04-22 04:31:56,874] Trial 21 finished with value: 0.2223614206043795 and parameters: {'subsample': 0.21998916108402466, 'dropout_rate': 0.2959463436825199, 'n_estimators': 146, 'learning_rate': 0.016628453308413924}. Best is trial 17 with value: 0.22099176441731544.
Fold 1 IBS: 0.24677762174930384
Fold 2 IBS: 0.23134509002373121
Fold 3 IBS: 0.22803955088704123
Fold 4 IBS: 0.24133009694415058
Fold 5 IBS: 0.2285789015748893
[I 2024-04-22 04:31:57,333] Trial 22 finished with value: 0.23521425223582323 and parameters: {'subsample': 0.3851624692496912, 'dropout_rate': 0.1669605808299724, 'n_estimators': 57, 'learning_rate': 0.0016409178578358878}. Best is trial 17 with value: 0.22099176441731544.
Fold 1 IBS: 0.24263528770268478
Fold 2 IBS: 0.22537137683749636
Fold 3 IBS: 0.21743478078136988
Fold 4 IBS: 0.23646569154886843
Fold 5 IBS: 0.22030666777909944
[I 2024-04-22 04:31:58,123] Trial 23 finished with value: 0.2284427609299038 and parameters: {'subsample': 0.2505815531606472, 'dropout_rate': 0.10001630590215177, 'n_estimators': 78, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.22099176441731544.
Fold 1 IBS: 0.24865482652476206
Fold 2 IBS: 0.22125753189026764
Fold 3 IBS: 0.19173354936291473
Fold 4 IBS: 0.23238252164980205
Fold 5 IBS: 0.20002525111716946
[I 2024-04-22 04:31:59,435] Trial 24 finished with value: 0.2188107361089832 and parameters: {'subsample': 0.1748642961781805, 'dropout_rate': 0.19012024616538375, 'n_estimators': 146, 'learning_rate': 0.04025844108845736}. Best is trial 24 with value: 0.2188107361089832.
Fold 1 IBS: 0.27085292052444165
Fold 2 IBS: 0.2315404820119707
Fold 3 IBS: 0.18757173904311875
Fold 4 IBS: 0.2345887309842098
Fold 5 IBS: 0.19849598999456858
[I 2024-04-22 04:32:01,843] Trial 25 finished with value: 0.22460997251166187 and parameters: {'subsample': 0.17400324178823182, 'dropout_rate': 0.2057291543015094, 'n_estimators': 236, 'learning_rate': 0.03790975314690388}. Best is trial 24 with value: 0.2188107361089832.
Fold 1 IBS: 0.24528281701046084
Fold 2 IBS: 0.2290044485937166
Fold 3 IBS: 0.22409135269961747
Fold 4 IBS: 0.23804691667709538
Fold 5 IBS: 0.22546176573953397
[I 2024-04-22 04:32:02,003] Trial 26 finished with value: 0.23237746014408484 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.16625214836701202, 'n_estimators': 8, 'learning_rate': 0.06367993248786023}. Best is trial 24 with value: 0.2188107361089832.
Fold 1 IBS: 0.23658246339807146
Fold 2 IBS: 0.21671887636266202
Fold 3 IBS: 0.19888495576754803
Fold 4 IBS: 0.22660093951808044
Fold 5 IBS: 0.20793397858077176
[I 2024-04-22 04:32:02,521] Trial 27 finished with value: 0.21734424272542677 and parameters: {'subsample': 0.1001811349712499, 'dropout_rate': 0.3060837787360696, 'n_estimators': 86, 'learning_rate': 0.043652841828953445}. Best is trial 27 with value: 0.21734424272542677.
Fold 1 IBS: 0.25076211260520803
Fold 2 IBS: 0.21906240827192583
Fold 3 IBS: 0.19155092712667085
Fold 4 IBS: 0.22427974468882733
Fold 5 IBS: 0.19886352038844207
[I 2024-04-22 04:32:03,388] Trial 28 finished with value: 0.21690374261621487 and parameters: {'subsample': 0.10086863400689129, 'dropout_rate': 0.3542506438364338, 'n_estimators': 138, 'learning_rate': 0.04711020308934093}. Best is trial 28 with value: 0.21690374261621487.
Fold 1 IBS: 0.26142072046013387
Fold 2 IBS: 0.23696448657681776
Fold 3 IBS: 0.18445915715185507
Fold 4 IBS: 0.22892297106865206
Fold 5 IBS: 0.20009044638993592
[I 2024-04-22 04:32:04,161] Trial 29 finished with value: 0.22237155632947894 and parameters: {'subsample': 0.13402031949117907, 'dropout_rate': 0.45420270189146295, 'n_estimators': 124, 'learning_rate': 0.08423642007181871}. Best is trial 28 with value: 0.21690374261621487.
Fold 1 IBS: 0.3282404157038746
Fold 2 IBS: 0.26767740235194426
Fold 3 IBS: 0.2243360464255518
Fold 4 IBS: 0.2915451336635365
Fold 5 IBS: 0.21592271000602276
[I 2024-04-22 04:32:06,327] Trial 30 finished with value: 0.26554434163018603 and parameters: {'subsample': 0.6244109540692406, 'dropout_rate': 0.3577780272974884, 'n_estimators': 261, 'learning_rate': 0.05802531255595394}. Best is trial 28 with value: 0.21690374261621487.
Fold 1 IBS: 0.23890702924236978
Fold 2 IBS: 0.21562798074279638
Fold 3 IBS: 0.193257919505915
Fold 4 IBS: 0.22477143508513897
Fold 5 IBS: 0.20202273221378417
[I 2024-04-22 04:32:06,986] Trial 31 finished with value: 0.21491741935800085 and parameters: {'subsample': 0.10791471095223147, 'dropout_rate': 0.3318606071411275, 'n_estimators': 105, 'learning_rate': 0.048926477327217985}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.24033641960879665
Fold 2 IBS: 0.2157546045450093
Fold 3 IBS: 0.19236763711352753
Fold 4 IBS: 0.22476670785310857
Fold 5 IBS: 0.20203180821639447
[I 2024-04-22 04:32:07,732] Trial 32 finished with value: 0.21505143546736732 and parameters: {'subsample': 0.10205167754931442, 'dropout_rate': 0.3290966919687764, 'n_estimators': 110, 'learning_rate': 0.05004800130766623}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2568108793532257
Fold 2 IBS: 0.2209058007293172
Fold 3 IBS: 0.18856257515973912
Fold 4 IBS: 0.224403906449119
Fold 5 IBS: 0.1989955451758428
[I 2024-04-22 04:32:08,437] Trial 33 finished with value: 0.21793574137344876 and parameters: {'subsample': 0.10119944375936658, 'dropout_rate': 0.5099593502178903, 'n_estimators': 107, 'learning_rate': 0.06645118412431683}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2612152354203138
Fold 2 IBS: 0.22404126866685314
Fold 3 IBS: 0.18806509400006063
Fold 4 IBS: 0.22791605720152006
Fold 5 IBS: 0.19718740786263095
[I 2024-04-22 04:32:09,610] Trial 34 finished with value: 0.2196850126302757 and parameters: {'subsample': 0.10317758573193452, 'dropout_rate': 0.4103303632625911, 'n_estimators': 163, 'learning_rate': 0.05021371222279493}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2424090929716965
Fold 2 IBS: 0.21923426932150422
Fold 3 IBS: 0.20647609466252714
Fold 4 IBS: 0.23023570034891572
Fold 5 IBS: 0.2108780178385074
[I 2024-04-22 04:32:09,902] Trial 35 finished with value: 0.2218466350286302 and parameters: {'subsample': 0.28599381133613416, 'dropout_rate': 0.3439793582432969, 'n_estimators': 37, 'learning_rate': 0.07266618325971635}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.28410714585279495
Fold 2 IBS: 0.2392777519897689
Fold 3 IBS: 0.19197131723032873
Fold 4 IBS: 0.24066815493124585
Fold 5 IBS: 0.20246758991662078
[I 2024-04-22 04:32:11,131] Trial 36 finished with value: 0.23169839198415182 and parameters: {'subsample': 0.2127757838464586, 'dropout_rate': 0.47769044528530935, 'n_estimators': 185, 'learning_rate': 0.05420255246852048}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.24709990395345402
Fold 2 IBS: 0.21699878601432387
Fold 3 IBS: 0.1896833027626039
Fold 4 IBS: 0.22495048921490676
Fold 5 IBS: 0.20077290432069408
[I 2024-04-22 04:32:11,634] Trial 37 finished with value: 0.21590107725319654 and parameters: {'subsample': 0.15265551466404892, 'dropout_rate': 0.32043776533398216, 'n_estimators': 99, 'learning_rate': 0.058697019062434394}. Best is trial 31 with value: 0.21491741935800085.

Fold 1 IBS: 0.3083582199710144
Fold 2 IBS: 0.26731931762836736
Fold 3 IBS: 0.2015992246240596
Fold 4 IBS: 0.24179547332887363
Fold 5 IBS: 0.21053937302540282
[I 2024-04-22 04:32:12,902] Trial 38 finished with value: 0.24592232171554357 and parameters: {'subsample': 0.15625970349050095, 'dropout_rate': 0.4206844353438282, 'n_estimators': 209, 'learning_rate': 0.0802388198308747}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.26854329591458154
Fold 2 IBS: 0.22695125511605937
Fold 3 IBS: 0.19435068055168625
Fold 4 IBS: 0.23491008921511294
Fold 5 IBS: 0.19986498118897203
[I 2024-04-22 04:32:13,523] Trial 39 finished with value: 0.2249240603972824 and parameters: {'subsample': 0.2684625107231529, 'dropout_rate': 0.3436874496277007, 'n_estimators': 123, 'learning_rate': 0.05854851947372738}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.31503461156363805
Fold 2 IBS: 0.2921347294253324
Fold 3 IBS: 0.21632748244753428
Fold 4 IBS: 0.2521216593960708
Fold 5 IBS: 0.2223820038993246
[I 2024-04-22 04:32:17,145] Trial 40 finished with value: 0.25960009734638 and parameters: {'subsample': 0.2104408081966576, 'dropout_rate': 0.5443446234145757, 'n_estimators': 434, 'learning_rate': 0.05032678610982225}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2368399535424011
Fold 2 IBS: 0.21601905324663587
Fold 3 IBS: 0.1951427370673055
Fold 4 IBS: 0.2242034387042277
Fold 5 IBS: 0.2036562952445236
[I 2024-04-22 04:32:17,760] Trial 41 finished with value: 0.21517229556101874 and parameters: {'subsample': 0.13609841894141306, 'dropout_rate': 0.2878524830509497, 'n_estimators': 90, 'learning_rate': 0.049424462853615896}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2413074168198784
Fold 2 IBS: 0.22133823722211968
Fold 3 IBS: 0.21642982543977743
Fold 4 IBS: 0.23186614302592803
Fold 5 IBS: 0.21801642834221643
[I 2024-04-22 04:32:17,968] Trial 42 finished with value: 0.225791610169984 and parameters: {'subsample': 0.15686427605676448, 'dropout_rate': 0.24143473272457944, 'n_estimators': 33, 'learning_rate': 0.050207275561300405}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.28932926268922976
Fold 2 IBS: 0.24514857538744228
Fold 3 IBS: 0.19488518486525386
Fold 4 IBS: 0.24335457230297064
Fold 5 IBS: 0.20435874622706346
[I 2024-04-22 04:32:18,990] Trial 43 finished with value: 0.23541526829439202 and parameters: {'subsample': 0.20979862666572763, 'dropout_rate': 0.36561341328147545, 'n_estimators': 182, 'learning_rate': 0.06210541418811967}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.23652891753287153
Fold 2 IBS: 0.21833518919591047
Fold 3 IBS: 0.2014407930406427
Fold 4 IBS: 0.22679610713991813
Fold 5 IBS: 0.2095286723375489
[I 2024-04-22 04:32:19,456] Trial 44 finished with value: 0.21852593584937835 and parameters: {'subsample': 0.13067968037872718, 'dropout_rate': 0.27284436067329976, 'n_estimators': 92, 'learning_rate': 0.03421518086002208}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.29736830391796343
Fold 2 IBS: 0.23579599833533654
Fold 3 IBS: 0.20795750398648633
Fold 4 IBS: 0.26318992024922105
Fold 5 IBS: 0.20318731567770826
[I 2024-04-22 04:32:20,065] Trial 45 finished with value: 0.24149980843334307 and parameters: {'subsample': 0.5848685566528298, 'dropout_rate': 0.5884334231606646, 'n_estimators': 128, 'learning_rate': 0.06923498563070397}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2755153858640362
Fold 2 IBS: 0.21982265972411547
Fold 3 IBS: 0.20389986342359276
Fold 4 IBS: 0.24914790301569475
Fold 5 IBS: 0.20160759055967475
[I 2024-04-22 04:32:20,576] Trial 46 finished with value: 0.22999868051742278 and parameters: {'subsample': 0.7983371068443791, 'dropout_rate': 0.4368736533210751, 'n_estimators': 108, 'learning_rate': 0.05470596021581968}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.29859042603843067
Fold 2 IBS: 0.2424085383786931
Fold 3 IBS: 0.1991260852889128
Fold 4 IBS: 0.2521918073996617
Fold 5 IBS: 0.20414699385790416
[I 2024-04-22 04:32:21,930] Trial 47 finished with value: 0.23929277019272047 and parameters: {'subsample': 0.318162083199977, 'dropout_rate': 0.33206627775150455, 'n_estimators': 221, 'learning_rate': 0.047486323637714115}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2428358217929094
Fold 2 IBS: 0.22514620312396877
Fold 3 IBS: 0.21949047386778228
Fold 4 IBS: 0.23661601608126068
Fold 5 IBS: 0.22111439722460688
[I 2024-04-22 04:32:22,086] Trial 48 finished with value: 0.2290405824181056 and parameters: {'subsample': 0.44232831707206716, 'dropout_rate': 0.3858495125365113, 'n_estimators': 19, 'learning_rate': 0.05881819973768585}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2827386312300425
Fold 2 IBS: 0.2308457304969726
Fold 3 IBS: 0.19404612254779985
Fold 4 IBS: 0.24148674611612556
Fold 5 IBS: 0.2012119017364319
[I 2024-04-22 04:32:24,105] Trial 49 finished with value: 0.23006582642547446 and parameters: {'subsample': 0.2889854652310479, 'dropout_rate': 0.49215655649065315, 'n_estimators': 301, 'learning_rate': 0.02713079119975165}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2635128787956399
Fold 2 IBS: 0.2240510280950479
Fold 3 IBS: 0.18776522214657218
Fold 4 IBS: 0.22698764008233022
Fold 5 IBS: 0.19895651010260354
[I 2024-04-22 04:32:25,054] Trial 50 finished with value: 0.22025465584443876 and parameters: {'subsample': 0.1404561168182083, 'dropout_rate': 0.20995437866461875, 'n_estimators': 166, 'learning_rate': 0.04711959974022807}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.23708839943323007
Fold 2 IBS: 0.21786944308615755
Fold 3 IBS: 0.20243110835626263
Fold 4 IBS: 0.22813644685159512
Fold 5 IBS: 0.2108456091174375
[I 2024-04-22 04:32:25,475] Trial 51 finished with value: 0.2192742013689366 and parameters: {'subsample': 0.10468514382889214, 'dropout_rate': 0.3026206765297631, 'n_estimators': 84, 'learning_rate': 0.03681842250297113}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.239624534981965
Fold 2 IBS: 0.21868018539215445
Fold 3 IBS: 0.2067995138261878
Fold 4 IBS: 0.2302178611916735
Fold 5 IBS: 0.21242258825620658
[I 2024-04-22 04:32:25,744] Trial 52 finished with value: 0.2215489367296375 and parameters: {'subsample': 0.1910565418778623, 'dropout_rate': 0.2730842959798365, 'n_estimators': 51, 'learning_rate': 0.05224169698208609}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.24839540741330743
Fold 2 IBS: 0.2186659844690372
Fold 3 IBS: 0.19888036531279385
Fold 4 IBS: 0.2276101669752509
Fold 5 IBS: 0.20507238340967135
[I 2024-04-22 04:32:26,163] Trial 53 finished with value: 0.21972486151601217 and parameters: {'subsample': 0.24459932011912405, 'dropout_rate': 0.8299583658948217, 'n_estimators': 93, 'learning_rate': 0.0433636548663099}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.24016059166722922
Fold 2 IBS: 0.21668059679135102
Fold 3 IBS: 0.1960660256273432
Fold 4 IBS: 0.22652965626581378
Fold 5 IBS: 0.20590822067015008
[I 2024-04-22 04:32:26,513] Trial 54 finished with value: 0.21706901820437746 and parameters: {'subsample': 0.1462732535781962, 'dropout_rate': 0.33432821951709296, 'n_estimators': 71, 'learning_rate': 0.05634491987142897}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2562306716582781
Fold 2 IBS: 0.22263879416377344
Fold 3 IBS: 0.18693192809919557
Fold 4 IBS: 0.22159310311501465
Fold 5 IBS: 0.19818007960523865
[I 2024-04-22 04:32:27,250] Trial 55 finished with value: 0.21711491532830013 and parameters: {'subsample': 0.14383790971480295, 'dropout_rate': 0.3775147685294936, 'n_estimators': 140, 'learning_rate': 0.05606592318737652}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.2410359238266747
Fold 2 IBS: 0.216821291343171
Fold 3 IBS: 0.20041885843202203
Fold 4 IBS: 0.23003189825156498
Fold 5 IBS: 0.20557260207622952
[I 2024-04-22 04:32:27,590] Trial 56 finished with value: 0.21877611478593245 and parameters: {'subsample': 0.1922586302851747, 'dropout_rate': 0.3297742663590158, 'n_estimators': 64, 'learning_rate': 0.06403813932959312}. Best is trial 31 with value: 0.21491741935800085.

Fold 1 IBS: 0.2529986944229438
Fold 2 IBS: 0.21897684304729892
Fold 3 IBS: 0.1940287385640011
Fold 4 IBS: 0.23439149466637788
Fold 5 IBS: 0.2029277662572779
[I 2024-04-22 04:32:28,111] Trial 57 finished with value: 0.2206647073915799 and parameters: {'subsample': 0.3377501312997669, 'dropout_rate': 0.24549147575426655, 'n_estimators': 105, 'learning_rate': 0.046935860424948676}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.28395719312076084
Fold 2 IBS: 0.24671899516479082
Fold 3 IBS: 0.19450191095969493
Fold 4 IBS: 0.2522108127918849
Fold 5 IBS: 0.20252548316759944
[I 2024-04-22 04:32:29,284] Trial 58 finished with value: 0.23598287904094617 and parameters: {'subsample': 0.24048734144744882, 'dropout_rate': 0.13453625688378332, 'n_estimators': 194, 'learning_rate': 0.060136695161078196}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.24857767387511362
Fold 2 IBS: 0.21845978617452352
Fold 3 IBS: 0.20666283371692445
Fold 4 IBS: 0.2355372160966114
Fold 5 IBS: 0.2089480471236626
[I 2024-04-22 04:32:29,516] Trial 59 finished with value: 0.2236371113973671 and parameters: {'subsample': 0.6869904791039767, 'dropout_rate': 0.26947446280772824, 'n_estimators': 44, 'learning_rate': 0.06677069125556893}. Best is trial 31 with value: 0.21491741935800085.
Fold 1 IBS: 0.23844547697639712
Fold 2 IBS: 0.2159033836173008
Fold 3 IBS: 0.19086503425385992
Fold 4 IBS: 0.22410859260823263
Fold 5 IBS: 0.20097135889135312
[I 2024-04-22 04:32:29,886] Trial 60 finished with value: 0.21405876926942874 and parameters: {'subsample': 0.1377983733895635, 'dropout_rate': 0.4494236909497902, 'n_estimators': 75, 'learning_rate': 0.07200825617838875}. Best is trial 60 with value: 0.21405876926942874.
Fold 1 IBS: 0.23937016434718814
Fold 2 IBS: 0.21799472330875877
Fold 3 IBS: 0.18812413372658038
Fold 4 IBS: 0.2231178401314671
Fold 5 IBS: 0.2011395118953899
[I 2024-04-22 04:32:30,233] Trial 61 finished with value: 0.21394927468187683 and parameters: {'subsample': 0.13134253810641847, 'dropout_rate': 0.4580141177156808, 'n_estimators': 70, 'learning_rate': 0.07841565629870267}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2676402455713437
Fold 2 IBS: 0.2403261003847321
Fold 3 IBS: 0.18434677798981478
Fold 4 IBS: 0.22863491202360725
Fold 5 IBS: 0.20079062391052005
[I 2024-04-22 04:32:31,052] Trial 62 finished with value: 0.22434773197600358 and parameters: {'subsample': 0.1308124787912429, 'dropout_rate': 0.45630244296392014, 'n_estimators': 139, 'learning_rate': 0.07705217193972827}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.26880574679733127
Fold 2 IBS: 0.23082712948807263
Fold 3 IBS: 0.18563597094294973
Fold 4 IBS: 0.23768500441186557
Fold 5 IBS: 0.20011529630273045
[I 2024-04-22 04:32:31,745] Trial 63 finished with value: 0.2246138295885899 and parameters: {'subsample': 0.17807149753703974, 'dropout_rate': 0.40703454986945614, 'n_estimators': 109, 'learning_rate': 0.08838466163068011}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24759449837718864
Fold 2 IBS: 0.21611913592324422
Fold 3 IBS: 0.1921102121013053
Fold 4 IBS: 0.22437256528377955
Fold 5 IBS: 0.20223496247237638
[I 2024-04-22 04:32:32,217] Trial 64 finished with value: 0.21648627483157884 and parameters: {'subsample': 0.12487963072447791, 'dropout_rate': 0.5257129526694306, 'n_estimators': 74, 'learning_rate': 0.07648095661317558}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24167900692992744
Fold 2 IBS: 0.2240770930239068
Fold 3 IBS: 0.21422091388630488
Fold 4 IBS: 0.2334154339715708
Fold 5 IBS: 0.21944496915111467
[I 2024-04-22 04:32:32,399] Trial 65 finished with value: 0.2265674833925649 and parameters: {'subsample': 0.19819558713825158, 'dropout_rate': 0.5665767833980432, 'n_estimators': 17, 'learning_rate': 0.0751635772638565}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.23848953791753488
Fold 2 IBS: 0.21571160718701135
Fold 3 IBS: 0.19903295427690149
Fold 4 IBS: 0.2235251711949513
Fold 5 IBS: 0.20400251985352721
[I 2024-04-22 04:32:32,762] Trial 66 finished with value: 0.21615235808598526 and parameters: {'subsample': 0.1272604114403119, 'dropout_rate': 0.5119806791328405, 'n_estimators': 55, 'learning_rate': 0.08613261204409457}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.23581030482582585
Fold 2 IBS: 0.21638382920467777
Fold 3 IBS: 0.20472458366282892
Fold 4 IBS: 0.22881138628553865
Fold 5 IBS: 0.20845574262374622
[I 2024-04-22 04:32:33,043] Trial 67 finished with value: 0.21883716932052347 and parameters: {'subsample': 0.16651199639183403, 'dropout_rate': 0.6167875683240538, 'n_estimators': 35, 'learning_rate': 0.09058963748009756}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24673323819106882
Fold 2 IBS: 0.23184109962733124
Fold 3 IBS: 0.22781405569362537
Fold 4 IBS: 0.241022381187755
Fold 5 IBS: 0.22882534144437347
[I 2024-04-22 04:32:33,186] Trial 68 finished with value: 0.2352472232288308 and parameters: {'subsample': 0.27454462162870047, 'dropout_rate': 0.4737384220240273, 'n_estimators': 1, 'learning_rate': 0.08296424298832916}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2650736955699687
Fold 2 IBS: 0.2234601318389826
Fold 3 IBS: 0.1877490722481821
Fold 4 IBS: 0.23013441200283205
Fold 5 IBS: 0.200553902432022
[I 2024-04-22 04:32:33,775] Trial 69 finished with value: 0.22139424281839748 and parameters: {'subsample': 0.2221279912919758, 'dropout_rate': 0.6703989045430142, 'n_estimators': 96, 'learning_rate': 0.07264454837795192}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.25922720929714077
Fold 2 IBS: 0.21784547079626243
Fold 3 IBS: 0.20122543100919812
Fold 4 IBS: 0.23555191986495785
Fold 5 IBS: 0.2039774649032208
[I 2024-04-22 04:32:34,086] Trial 70 finished with value: 0.22356549917415597 and parameters: {'subsample': 0.5080312248190293, 'dropout_rate': 0.9969638279429532, 'n_estimators': 49, 'learning_rate': 0.088458442384177}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24815296497860032
Fold 2 IBS: 0.21597421048870433
Fold 3 IBS: 0.19135377662530736
Fold 4 IBS: 0.22414003224763732
Fold 5 IBS: 0.201858552902066
[I 2024-04-22 04:32:34,491] Trial 71 finished with value: 0.21629590744846308 and parameters: {'subsample': 0.1224616058023833, 'dropout_rate': 0.5149305777021448, 'n_estimators': 73, 'learning_rate': 0.08041967122410196}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24361622719851136
Fold 2 IBS: 0.21816057050462564
Fold 3 IBS: 0.19487537584502115
Fold 4 IBS: 0.22733127475582454
Fold 5 IBS: 0.2026059069136177
[I 2024-04-22 04:32:34,818] Trial 72 finished with value: 0.2173178710435201 and parameters: {'subsample': 0.1650835155333015, 'dropout_rate': 0.5030206703933512, 'n_estimators': 65, 'learning_rate': 0.0792265383317001}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2532748981080488
Fold 2 IBS: 0.2178433633567949
Fold 3 IBS: 0.1882548004394344
Fold 4 IBS: 0.22353807262833394
Fold 5 IBS: 0.20080845949869108
[I 2024-04-22 04:32:35,206] Trial 73 finished with value: 0.21674391880626062 and parameters: {'subsample': 0.12390480680022734, 'dropout_rate': 0.5703273456112167, 'n_estimators': 79, 'learning_rate': 0.0840676158597219}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2682801637717559
Fold 2 IBS: 0.2342595958197819
Fold 3 IBS: 0.1843560564448171
Fold 4 IBS: 0.22771283110742938
Fold 5 IBS: 0.20018066155066336
[I 2024-04-22 04:32:35,843] Trial 74 finished with value: 0.2229578617388895 and parameters: {'subsample': 0.12458094591191285, 'dropout_rate': 0.4191930012678944, 'n_estimators': 118, 'learning_rate': 0.09663586729445058}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2858345996110935
Fold 2 IBS: 0.24430266449304563
Fold 3 IBS: 0.1914435334214305
Fold 4 IBS: 0.2382915188277261
Fold 5 IBS: 0.20104532068657374
[I 2024-04-22 04:32:36,714] Trial 75 finished with value: 0.23218352740797385 and parameters: {'subsample': 0.18473093776210897, 'dropout_rate': 0.5186184716860122, 'n_estimators': 158, 'learning_rate': 0.06940214578281045}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.23905410604850438
Fold 2 IBS: 0.21846804666070785
Fold 3 IBS: 0.2113099804325978
Fold 4 IBS: 0.2324729913867337
Fold 5 IBS: 0.21504504069785352
[I 2024-04-22 04:32:36,915] Trial 76 finished with value: 0.22327003304527948 and parameters: {'subsample': 0.15596515946502398, 'dropout_rate': 0.44129778860488267, 'n_estimators': 29, 'learning_rate': 0.07985481796691309}. Best is trial 61 with value: 0.21394927468187683.

Fold 1 IBS: 0.2393392770721095
Fold 2 IBS: 0.21537971922599472
Fold 3 IBS: 0.19569058995726943
Fold 4 IBS: 0.2267630571643693
Fold 5 IBS: 0.2042627768464641
[I 2024-04-22 04:32:37,229] Trial 77 finished with value: 0.21628708405324143 and parameters: {'subsample': 0.11836808514359815, 'dropout_rate': 0.602871144213147, 'n_estimators': 57, 'learning_rate': 0.08798155769745203}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.25148184048671246
Fold 2 IBS: 0.21882963025961874
Fold 3 IBS: 0.1971141346752486
Fold 4 IBS: 0.22736880491325037
Fold 5 IBS: 0.20424088523771952
[I 2024-04-22 04:32:37,566] Trial 78 finished with value: 0.21980705911450996 and parameters: {'subsample': 0.23783880894125464, 'dropout_rate': 0.6039967438323356, 'n_estimators': 51, 'learning_rate': 0.09131523154073178}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.27314574211798887
Fold 2 IBS: 0.23594957937855662
Fold 3 IBS: 0.18985704023597094
Fold 4 IBS: 0.23013972450136824
Fold 5 IBS: 0.1991625439084426
[I 2024-04-22 04:32:38,221] Trial 79 finished with value: 0.22565092602846545 and parameters: {'subsample': 0.20833911764796395, 'dropout_rate': 0.21830580132911775, 'n_estimators': 100, 'learning_rate': 0.0983514933405076}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2587622084016886
Fold 2 IBS: 0.2232689321117149
Fold 3 IBS: 0.185342521229951
Fold 4 IBS: 0.2318711323991913
Fold 5 IBS: 0.20056739374755125
[I 2024-04-22 04:32:38,759] Trial 80 finished with value: 0.21996243757801942 and parameters: {'subsample': 0.1598318526834561, 'dropout_rate': 0.6426287723823484, 'n_estimators': 86, 'learning_rate': 0.08619513291504852}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24090271196724858
Fold 2 IBS: 0.21535846283794524
Fold 3 IBS: 0.19586143104393527
Fold 4 IBS: 0.2254676139609017
Fold 5 IBS: 0.20434306954130324
[I 2024-04-22 04:32:39,150] Trial 81 finished with value: 0.2163866578702668 and parameters: {'subsample': 0.11755689179551444, 'dropout_rate': 0.7000398043119781, 'n_estimators': 60, 'learning_rate': 0.08115098136882044}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2566150752393419
Fold 2 IBS: 0.22236900612939717
Fold 3 IBS: 0.18758475127173993
Fold 4 IBS: 0.22397643826265556
Fold 5 IBS: 0.20004959004176376
[I 2024-04-22 04:32:39,653] Trial 82 finished with value: 0.21811897218897966 and parameters: {'subsample': 0.14305246646815237, 'dropout_rate': 0.5394929260888801, 'n_estimators': 78, 'learning_rate': 0.09271429029113289}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.322808230200054
Fold 2 IBS: 0.29836514498740435
Fold 3 IBS: 0.21949536446759715
Fold 4 IBS: 0.23776624095014295
Fold 5 IBS: 0.23244925409185785
[I 2024-04-22 04:32:43,353] Trial 83 finished with value: 0.2621768469394113 and parameters: {'subsample': 0.10215802558022695, 'dropout_rate': 0.4718671323037774, 'n_estimators': 395, 'learning_rate': 0.08655224661274442}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.239410856043329
Fold 2 IBS: 0.22292087981690947
Fold 3 IBS: 0.21505103561011213
Fold 4 IBS: 0.234526190736055
Fold 5 IBS: 0.21775835027277704
[I 2024-04-22 04:32:43,516] Trial 84 finished with value: 0.22593346249583654 and parameters: {'subsample': 0.17475795789455115, 'dropout_rate': 0.7575761223753412, 'n_estimators': 20, 'learning_rate': 0.07290250055404361}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.25661431392147277
Fold 2 IBS: 0.2252563346201509
Fold 3 IBS: 0.1833811431158558
Fold 4 IBS: 0.22435638008560782
Fold 5 IBS: 0.19805875807094372
[I 2024-04-22 04:32:44,117] Trial 85 finished with value: 0.2175333859628062 and parameters: {'subsample': 0.12120621499816343, 'dropout_rate': 0.3893392475352686, 'n_estimators': 118, 'learning_rate': 0.07811016059057542}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2519408213152369
Fold 2 IBS: 0.21953893603776894
Fold 3 IBS: 0.1966437415404613
Fold 4 IBS: 0.2295442785315931
Fold 5 IBS: 0.20272819881547124
[I 2024-04-22 04:32:44,413] Trial 86 finished with value: 0.22007919524810632 and parameters: {'subsample': 0.2585539083040265, 'dropout_rate': 0.5721089012385804, 'n_estimators': 58, 'learning_rate': 0.08239721029967538}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.25218107071922435
Fold 2 IBS: 0.2180807723744548
Fold 3 IBS: 0.1923070678356244
Fold 4 IBS: 0.2276377868781289
Fold 5 IBS: 0.20154659739803196
[I 2024-04-22 04:32:45,099] Trial 87 finished with value: 0.2183506590410929 and parameters: {'subsample': 0.22446555794035733, 'dropout_rate': 0.289379622584334, 'n_estimators': 131, 'learning_rate': 0.041516005480302}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24732248483713434
Fold 2 IBS: 0.21776292843682007
Fold 3 IBS: 0.19059015100096155
Fold 4 IBS: 0.22274434778014435
Fold 5 IBS: 0.20334645064713824
[I 2024-04-22 04:32:45,586] Trial 88 finished with value: 0.2163532725404397 and parameters: {'subsample': 0.14565273504856402, 'dropout_rate': 0.635175424179692, 'n_estimators': 96, 'learning_rate': 0.05281067430968921}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2437639099532454
Fold 2 IBS: 0.21591461984225968
Fold 3 IBS: 0.19818851885585392
Fold 4 IBS: 0.22927756105482602
Fold 5 IBS: 0.2056827773383906
[I 2024-04-22 04:32:45,826] Trial 89 finished with value: 0.2185654774089151 and parameters: {'subsample': 0.18873150657767507, 'dropout_rate': 0.31144454371722735, 'n_estimators': 43, 'learning_rate': 0.09407335699217094}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.23774052769304665
Fold 2 IBS: 0.21608405534055475
Fold 3 IBS: 0.19074554627397844
Fold 4 IBS: 0.2235030266245639
Fold 5 IBS: 0.20251127777808267
[I 2024-04-22 04:32:46,220] Trial 90 finished with value: 0.21411688674204526 and parameters: {'subsample': 0.1181024330875216, 'dropout_rate': 0.37122710910794615, 'n_estimators': 73, 'learning_rate': 0.06614579056733322}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2633347560438125
Fold 2 IBS: 0.21795773620069112
Fold 3 IBS: 0.2043620897992369
Fold 4 IBS: 0.24359643855045762
Fold 5 IBS: 0.20341983856924822
[I 2024-04-22 04:32:46,547] Trial 91 finished with value: 0.22653417183268929 and parameters: {'subsample': 0.8961006358184125, 'dropout_rate': 0.3657469454631184, 'n_estimators': 68, 'learning_rate': 0.07105506305992909}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24031372497848644
Fold 2 IBS: 0.21523382729440543
Fold 3 IBS: 0.18921809457922623
Fold 4 IBS: 0.2263366278927982
Fold 5 IBS: 0.20004056554343724
[I 2024-04-22 04:32:47,018] Trial 92 finished with value: 0.2142285680576707 and parameters: {'subsample': 0.11114144015337309, 'dropout_rate': 0.43200737950748, 'n_estimators': 89, 'learning_rate': 0.06668890512280624}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.23835484589199826
Fold 2 IBS: 0.21684720514767436
Fold 3 IBS: 0.19081224584133755
Fold 4 IBS: 0.22545950654204233
Fold 5 IBS: 0.20119303950063833
[I 2024-04-22 04:32:47,447] Trial 93 finished with value: 0.21453336858473815 and parameters: {'subsample': 0.10347759739933667, 'dropout_rate': 0.42780121079834177, 'n_estimators': 86, 'learning_rate': 0.06587279636037768}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24708787010415642
Fold 2 IBS: 0.21930270386950967
Fold 3 IBS: 0.18788490878251102
Fold 4 IBS: 0.2260202301629555
Fold 5 IBS: 0.1978614682566812
[I 2024-04-22 04:32:48,201] Trial 94 finished with value: 0.2156314362351628 and parameters: {'subsample': 0.10172705367988492, 'dropout_rate': 0.4292333354334588, 'n_estimators': 114, 'learning_rate': 0.06441927267378475}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24861920572854676
Fold 2 IBS: 0.22033971065238195
Fold 3 IBS: 0.18792842475937827
Fold 4 IBS: 0.22642548134024945
Fold 5 IBS: 0.19768805288155208
[I 2024-04-22 04:32:48,797] Trial 95 finished with value: 0.21620017507242167 and parameters: {'subsample': 0.10055445724169844, 'dropout_rate': 0.4284022805787155, 'n_estimators': 116, 'learning_rate': 0.06567496945869249}. Best is trial 61 with value: 0.21394927468187683.

Fold 1 IBS: 0.26678653392884516
Fold 2 IBS: 0.22722487286507992
Fold 3 IBS: 0.18937463399576313
Fold 4 IBS: 0.22517161107708847
Fold 5 IBS: 0.1984615532807891
[I 2024-04-22 04:32:49,592] Trial 96 finished with value: 0.22140384102951316 and parameters: {'subsample': 0.14974923898329817, 'dropout_rate': 0.39759849593900626, 'n_estimators': 150, 'learning_rate': 0.061060591001826744}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.2625536242665444
Fold 2 IBS: 0.2288105460949891
Fold 3 IBS: 0.18699579836219213
Fold 4 IBS: 0.22700714242637182
Fold 5 IBS: 0.19932972201299073
[I 2024-04-22 04:32:50,247] Trial 97 finished with value: 0.22093936663261765 and parameters: {'subsample': 0.1709410608057082, 'dropout_rate': 0.4550565297941984, 'n_estimators': 130, 'learning_rate': 0.06374086930130063}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24714572746694113
Fold 2 IBS: 0.22156564438553897
Fold 3 IBS: 0.1916282993243525
Fold 4 IBS: 0.22944315053662612
Fold 5 IBS: 0.2005894866990585
[I 2024-04-22 04:32:50,687] Trial 98 finished with value: 0.21807446168250344 and parameters: {'subsample': 0.20138371215121825, 'dropout_rate': 0.32455922522201436, 'n_estimators': 88, 'learning_rate': 0.06794905363738571}. Best is trial 61 with value: 0.21394927468187683.
Fold 1 IBS: 0.24926525288723209
Fold 2 IBS: 0.21868653001337712
Fold 3 IBS: 0.18865266437417783
Fold 4 IBS: 0.225934509997585
Fold 5 IBS: 0.2000287374033253
[I 2024-04-22 04:32:51,209] Trial 99 finished with value: 0.2165135389351395 and parameters: {'subsample': 0.15708242970251812, 'dropout_rate': 0.3543407309251354, 'n_estimators': 102, 'learning_rate': 0.0575516968601493}. Best is trial 61 with value: 0.21394927468187683.


* Best trial for IBS:
 FrozenTrial(number=61, state=TrialState.COMPLETE, values=[0.21394927468187683], datetime_start=datetime.datetime(2024, 4, 22, 4, 32, 29, 889458), datetime_complete=datetime.datetime(2024, 4, 22, 4, 32, 30, 233668), params={'subsample': 0.13134253810641847, 'dropout_rate': 0.4580141177156808, 'n_estimators': 70, 'learning_rate': 0.07841565629870267}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=61, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.13134253810641847, 'dropout_rate': 0.4580141177156808, 'n_estimators': 70, 'learning_rate': 0.07841565629870267}


* Best Score for IBS:
 0.21394927468187683

In [75]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [76]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.712
train_ibs:  0.214

#### Test

In [77]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [78]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9439800508898758,
                                              learning_rate=0.07082775315124301,
                                              n_estimators=332,
                                              random_state=123,
                                              subsample=0.12070239642485954)

C-index score: 0.622

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.4580141177156808,
                                              learning_rate=0.07841565629870267,
                                              n_estimators=70, random_state=123,
                                              subsample=0.13134253810641847)

IBS: 0.22

In [79]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [93]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.866   1.0
ExtraSurvivalTrees               0.826   2.0
GradientBoosting                 0.759   3.0
CoxElastic                       0.733   4.0
CoxPH                            0.724   5.5
CoxLasso                         0.724   5.5
ComponentwiseGradientBoosting    0.712   7.0
CoxRidge                         0.653   8.0

In [94]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.188   1.0
Randomsurvivalforest           0.190   2.0
CoxElastic                     0.198   3.0
CoxLasso                       0.199   4.0
CoxPH                          0.200   5.0
ComponentwiseGradientBoosting  0.214   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [95]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.622   1.0
ExtraSurvivalTrees               0.607   2.0
CoxRidge                         0.601   3.0
GradientBoosting                 0.586   4.0
CoxLasso                         0.566   5.0
CoxElastic                       0.565   6.0
CoxPH                            0.562   7.0
Randomsurvivalforest             0.546   8.0

In [96]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.220   1.0
GradientBoosting               0.228   2.0
CoxRidge                       0.229   3.0
ExtraSurvivalTrees             0.252   4.0
Randomsurvivalforest           0.263   5.0
CoxLasso                       0.287   6.5
CoxElastic                     0.287   6.5
CoxPH                          0.290   8.0

In [97]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/minmax/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_minmax_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [98]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-22