In [1]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import MinMaxScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D3 
clinical_train.isnull().sum().sum()

0

### COX assumption in Train data

In [6]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.00001)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic    p  -log2(p)
LBP_003_CT                                                       0.01 0.91      0.13
LBP_003_PET                                                      0.00 0.98      0.03
LBP_012_CT                                                       0.00 0.95      0.08
LBP_012_PET                                                      0.00 0.97      0.04
LBP_021_CT                                                       0.00 0.97      0.05
LBP_021_PET                                                      0.01 0.92      0.12
LBP_030_CT                                                       0.00 0.99      0.02
LBP_030_PET                                                      0.00 0.99      0.01
LBP_102_CT                                                       0.00 0.99      0.02
LBP_102_PET                                                      0.01 0.94      0.09
LBP_111_CT                                                       0.01 0.94      0.09
LBP_111_PET                                                      0.02 0.90      0.16
LBP_120_CT                                                       0.01 0.93      0.10
LBP_120_PET                                                      0.00 0.97      0.05
LBP_201_CT                                                       0.01 0.94      0.09
LBP_201_PET                                                      0.00 0.99      0.01
LBP_210_CT                                                       0.00 0.98      0.03
LBP_210_PET                                                      0.00 0.97      0.05
LBP_300_CT                                                       0.00 0.98      0.03
LBP_300_PET                                                      0.00 0.98      0.02
MTV                                                              0.00 1.00      0.00
SUVpeak                                                          0.00 1.00      0.00
TLG                                                              0.00 1.00      0.00
age                                                              0.00 0.98      0.03
cavum_oris                                                       0.00 0.97      0.05
charlson                                                         0.00 0.95      0.08
female                                                           0.00 1.00      0.00
first_order_10Percentile_CT                                      0.00 0.97      0.05
first_order_10Percentile_PET                                     0.00 1.00      0.00
first_order_90Percentile_CT                                      0.00 0.96      0.05
first_order_90Percentile_PET                                     0.00 1.00      0.00
first_order_Energy_CT                                            0.00 1.00      0.01
first_order_Energy_PET                                           0.00 0.99      0.02
first_order_Entropy_CT_b20                                       0.00 0.99      0.02
first_order_Entropy_CT_c16                                       0.00 0.99      0.02
first_order_Entropy_PET_b2                                       0.00 1.00      0.01
first_order_Entropy_PET_c04                                      0.00 0.99      0.02
first_order_InterquartileRange_CT                                0.00 0.98      0.03
first_order_InterquartileRange_PET                               0.00 1.00      0.00
first_order_Kurtosis_CT                                          0.00 0.98      0.02
first_order_Kurtosis_PET                                         0.00 0.99      0.02
first_order_Maximum_CT                                           0.01 0.94      0.09
first_order_Maximum_PET                                          0.00 0.99      0.02
first_order_MeanAbsoluteDeviation_CT                             0.00 0.99      0.01
first_order_MeanAbsoluteDeviation_PET                            0.00 1.00      0.00
first_order_Mean_CT                                              0.00 1.00      0.01
first_order_Mean_PET                                             0.00 1.00      0.00
first_order_Median_CT                                            0.00 0.99      0.01
first_order_Median_PET                                           0.00 0.99      0.01
first_order_Minimum_CT                                           0.00 0.99      0.01
first_order_Minimum_PET                                          0.01 0.93      0.11
first_order_Range_CT                                             0.00 0.96      0.06
first_order_Range_PET                                            0.00 0.99      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.00 0.96      0.07
first_order_RobustMeanAbsoluteDeviation_PET                      0.00 0.99      0.01
first_order_RootMeanSquared_CT                                   0.00 0.99      0.01
first_order_RootMeanSquared_PET                                  0.00 1.00      0.00
first_order_Skewness_CT                                          0.03 0.85      0.23
first_order_Skewness_PET                                         0.00 0.97      0.04
first_order_TotalEnergy_CT                                       0.00 1.00      0.01
first_order_TotalEnergy_PET                                      0.00 0.99      0.02
first_order_Uniformity_CT_b20                                    0.00 0.97      0.04
first_order_Uniformity_CT_c16                                    0.00 0.99      0.02
first_order_Uniformity_PET_b2                                    0.00 0.99      0.01
first_order_Uniformity_PET_c04                                   0.00 0.99      0.01
first_order_Variance_CT                                          0.00 0.99      0.02
first_order_Variance_PET                                         0.00 1.00      0.01
glcm_Autocorrelation_d_1_CT_b20                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_CT_c16                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_b2                                  0.00 1.00      0.00
glcm_Autocorrelation_d_1_PET_c04                                 0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_b20                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_CT_c16                                0.00 0.95      0.07
glcm_ClusterProminence_d_1_PET_b2                                0.00 1.00      0.00
glcm_ClusterProminence_d_1_PET_c04                               0.00 0.98      0.03
glcm_ClusterShade_d_1_CT_b20                                     0.00 0.94      0.08
glcm_ClusterShade_d_1_CT_c16                                     0.00 0.94      0.08
glcm_ClusterShade_d_1_PET_b2                                     0.00 0.97      0.04
glcm_ClusterShade_d_1_PET_c04                                    0.01 0.93      0.10
glcm_ClusterTendency_d_1_CT_b20                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_CT_c16                                  0.00 0.98      0.03
glcm_ClusterTendency_d_1_PET_b2                                  0.00 0.99      0.01
glcm_ClusterTendency_d_1_PET_c04                                 0.00 0.98      0.02
glcm_Contrast_d_1_CT_b20                                         0.00 0.99      0.02
glcm_Contrast_d_1_CT_c16                                         0.00 0.98      0.02
glcm_Contrast_d_1_PET_b2                                         0.00 1.00      0.00
glcm_Contrast_d_1_PET_c04                                        0.00 0.99      0.01
glcm_Correlation_d_1_CT_b20                                      0.00 0.97      0.05
glcm_Correlation_d_1_CT_c16                                      0.01 0.93      0.10
glcm_Correlation_d_1_PET_b2                                      0.00 0.99      0.01
glcm_Correlation_d_1_PET_c04                                     0.00 0.97      0.05
glcm_DifferenceAverage_d_1_CT_b20                                0.00 1.00      0.00
glcm_DifferenceAverage_d_1_CT_c16                                0.00 0.99      0.02
glcm_DifferenceAverage_d_1_PET_b2                                0.00 0.99      0.01
glcm_DifferenceAverage_d_1_PET_c04                               0.00 1.00      0.00
glcm_DifferenceEntropy_d_1_CT_b20                                0.00 0.99      0.01
glcm_DifferenceEntropy_d_1_CT_c16                                0.00 0.99      0.02
glcm_DifferenceEntropy_d_1_PET_b2                                0.00 1.00      0.00
glcm_DifferenceEntropy_d_1_PET_c04                               0.00 0.99      0.01
glcm_DifferenceVariance_d_1_CT_b20                               0.00 0.99      0.02
glcm_DifferenceVariance_d_1_CT_c16                               0.00 0.97      0.04
glcm_DifferenceVariance_d_1_PET_b2                               0.00 1.00      0.00
glcm_DifferenceVariance_d_1_PET_c04                              0.00 1.00      0.01
glcm_Id_d_1_CT_b20                                               0.00 1.00      0.00
glcm_Id_d_1_CT_c16                                               0.00 0.99      0.02
glcm_Id_d_1_PET_b2                                               0.00 0.99      0.02
glcm_Id_d_1_PET_c04                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idm_d_1_CT_c16                                              0.00 0.99      0.02
glcm_Idm_d_1_PET_b2                                              0.00 0.99      0.01
glcm_Idm_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Idmn_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Idmn_d_1_CT_c16                                             0.00 0.99      0.02
glcm_Idmn_d_1_PET_b2                                             0.00 0.95      0.08
glcm_Idmn_d_1_PET_c04                                            0.00 0.99      0.01
glcm_Idn_d_1_CT_b20                                              0.00 1.00      0.00
glcm_Idn_d_1_CT_c16                                              0.00 0.99      0.02
glcm_Idn_d_1_PET_b2                                              0.00 0.98      0.03
glcm_Idn_d_1_PET_c04                                             0.00 1.00      0.00
glcm_Imc1_d_1_CT_b20                                             0.00 0.99      0.02
glcm_Imc1_d_1_CT_c16                                             0.00 0.99      0.01
glcm_Imc1_d_1_PET_b2                                             0.00 0.96      0.06
glcm_Imc1_d_1_PET_c04                                            0.00 1.00      0.01
glcm_Imc2_d_1_CT_b20                                             0.00 0.96      0.05
glcm_Imc2_d_1_CT_c16                                             0.00 0.97      0.05
glcm_Imc2_d_1_PET_b2                                             0.00 0.98      0.02
glcm_Imc2_d_1_PET_c04                                            0.00 0.97      0.04
glcm_InverseVariance_d_1_CT_b20                                  0.00 0.99      0.01
glcm_InverseVariance_d_1_CT_c16                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_b2                                  0.00 0.98      0.03
glcm_InverseVariance_d_1_PET_c04                                 0.00 1.00      0.01
glcm_JointAverage_d_1_CT_b20                                     0.00 0.99      0.01
glcm_JointAverage_d_1_CT_c16                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_b2                                     0.00 0.99      0.01
glcm_JointAverage_d_1_PET_c04                                    0.00 1.00      0.00
glcm_JointEnergy_d_1_CT_b20                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_CT_c16                                      0.00 1.00      0.01
glcm_JointEnergy_d_1_PET_b2                                      0.00 1.00      0.00
glcm_JointEnergy_d_1_PET_c04                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_CT_b20                                     0.00 0.99      0.02
glcm_JointEntropy_d_1_CT_c16                                     0.00 0.98      0.02
glcm_JointEntropy_d_1_PET_b2                                     0.00 1.00      0.00
glcm_JointEntropy_d_1_PET_c04                                    0.00 1.00      0.00
glcm_MCC_d_1_CT_b20                                              0.01 0.93      0.10
glcm_MCC_d_1_CT_c16                                              0.00 0.99      0.02
glcm_MCC_d_1_PET_b2                                              0.00 0.97      0.05
glcm_MCC_d_1_PET_c04                                             0.00 0.99      0.01
glcm_MaximumProbability_d_1_CT_b20                               0.01 0.94      0.09
glcm_MaximumProbability_d_1_CT_c16                               0.00 0.99      0.01
glcm_MaximumProbability_d_1_PET_b2                               0.02 0.89      0.16
glcm_MaximumProbability_d_1_PET_c04                              0.00 0.98      0.02
glcm_SumAverage_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumAverage_d_1_CT_c16                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumAverage_d_1_PET_c04                                      0.00 1.00      0.00
glcm_SumEntropy_d_1_CT_b20                                       0.00 0.98      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_b2                                       0.00 1.00      0.00
glcm_SumEntropy_d_1_PET_c04                                      0.00 0.99      0.01
glcm_SumSquares_d_1_CT_b20                                       0.00 0.99      0.01
glcm_SumSquares_d_1_CT_c16                                       0.00 0.99      0.02
glcm_SumSquares_d_1_PET_b2                                       0.00 0.99      0.01
glcm_SumSquares_d_1_PET_c04                                      0.00 0.98      0.02
gldm_DependenceEntropy_d_1_CT_b20                                0.00 0.96      0.06
gldm_DependenceEntropy_d_1_CT_c16                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_b2                                0.00 0.98      0.03
gldm_DependenceEntropy_d_1_PET_c04                               0.00 0.96      0.05
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.00 0.99      0.01
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.00 0.97      0.05
gldm_DependenceNonUniformity_d_1_CT_b20                          0.00 1.00      0.00
gldm_DependenceNonUniformity_d_1_CT_c16                          0.00 0.98      0.02
gldm_DependenceNonUniformity_d_1_PET_b2                          0.00 1.00      0.00
gldm_DependenceNonUniformity_d_1_PET_c04                         0.00 1.00      0.01
gldm_DependenceVariance_d_1_CT_b20                               0.00 0.99      0.01
gldm_DependenceVariance_d_1_CT_c16                               0.01 0.93      0.11
gldm_DependenceVariance_d_1_PET_b2                               0.00 0.96      0.05
gldm_DependenceVariance_d_1_PET_c04                              0.00 0.97      0.04
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.00 0.99      0.01
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.00 0.98      0.03
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.00 1.00      0.00
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00 1.00      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00 0.99      0.02
gldm_GrayLevelVariance_d_1_CT_c16                                0.00 0.97      0.05
gldm_GrayLevelVariance_d_1_PET_b2                                0.00 0.99      0.01
gldm_GrayLevelVariance_d_1_PET_c04                               0.00 1.00      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.00 1.00      0.01
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00 1.00      0.00
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.00 1.00      0.00
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.02
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.99      0.02
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 1.00      0.01
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 1.00      0.00
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 1.00      0.00
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 1.00      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.96      0.06
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.00 0.99      0.02
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00 0.99      0.01
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.00 0.98      0.02
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.00 0.98      0.04
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.00 0.99      0.02
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.00 0.99      0.02
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.00 0.98      0.02
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.00 0.99      0.01
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.00 0.97      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00 0.96      0.07
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.00 0.96      0.05
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00 0.98      0.03
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.00 0.98      0.02
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.00 1.00      0.00
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.00 0.95      0.07
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.01 0.94      0.10
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.01 0.93      0.11
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.00 0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.00 0.98      0.02
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_CT_b20                              0.00 1.00      0.00
glrlm_GrayLevelNonUniformity_CT_c16                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_b2                              0.00 0.99      0.01
glrlm_GrayLevelNonUniformity_PET_c04                             0.00 0.98      0.03
glrlm_GrayLevelVariance_CT_b20                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_CT_c16                                   0.00 1.00      0.00
glrlm_GrayLevelVariance_PET_b2                                   0.00 0.99      0.02

In [7]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index([], dtype='object')

In [8]:
df = pd.DataFrame(clinical_train)

# Fit Cox proportional hazards model
cph = CoxPHFitter(penalizer=0.1)
cph.fit(df, duration_col='DFS', event_col='event_DFS')

# Perform the proportional hazards assumption test
results = proportional_hazard_test(cph, df)
print(results)

<lifelines.StatisticalResult: proportional_hazard_test>
    time_transform = rank
 null_distribution = chi squared
degrees_of_freedom = 1
             model = <lifelines.CoxPHFitter: fitted with 139 total observations, 71 right-censored observations>
         test_name = proportional_hazard_test

---
                                                       test_statistic      p  -log2(p)
LBP_003_CT                                                       0.06   0.81      0.31
LBP_003_PET                                                      0.76   0.38      1.38
LBP_012_CT                                                       0.13   0.72      0.48
LBP_012_PET                                                      0.27   0.60      0.73
LBP_021_CT                                                       0.56   0.45      1.14
LBP_021_PET                                                      0.00   0.97      0.04
LBP_030_CT                                                       0.04   0.83      0.26
LBP_030_PET                                                      0.06   0.81      0.30
LBP_102_CT                                                       0.00   1.00      0.00
LBP_102_PET                                                      0.02   0.90      0.15
LBP_111_CT                                                       0.14   0.71      0.49
LBP_111_PET                                                      0.51   0.47      1.08
LBP_120_CT                                                       0.51   0.47      1.08
LBP_120_PET                                                      0.14   0.71      0.50
LBP_201_CT                                                       0.27   0.61      0.72
LBP_201_PET                                                      0.70   0.40      1.31
LBP_210_CT                                                       1.25   0.26      1.92
LBP_210_PET                                                      0.00   1.00      0.00
LBP_300_CT                                                       0.01   0.91      0.14
LBP_300_PET                                                      0.01   0.93      0.10
MTV                                                              0.03   0.86      0.22
SUVpeak                                                          0.00   0.99      0.02
TLG                                                              0.13   0.72      0.48
age                                                              0.14   0.71      0.50
cavum_oris                                                       0.64   0.42      1.24
charlson                                                         7.69   0.01      7.49
female                                                           0.44   0.51      0.98
first_order_10Percentile_CT                                      0.00   0.98      0.03
first_order_10Percentile_PET                                     0.07   0.78      0.35
first_order_90Percentile_CT                                      2.21   0.14      2.87
first_order_90Percentile_PET                                     0.00   0.95      0.07
first_order_Energy_CT                                            0.01   0.94      0.09
first_order_Energy_PET                                           0.19   0.66      0.59
first_order_Entropy_CT_b20                                       0.00   0.96      0.05
first_order_Entropy_CT_c16                                       0.07   0.79      0.34
first_order_Entropy_PET_b2                                       0.00   0.98      0.04
first_order_Entropy_PET_c04                                      0.00   0.98      0.03
first_order_InterquartileRange_CT                                0.48   0.49      1.04
first_order_InterquartileRange_PET                               0.00   0.99      0.02
first_order_Kurtosis_CT                                          0.57   0.45      1.15
first_order_Kurtosis_PET                                         0.00   0.99      0.02
first_order_Maximum_CT                                           0.15   0.70      0.52
first_order_Maximum_PET                                          0.00   0.96      0.06
first_order_MeanAbsoluteDeviation_CT                             0.04   0.83      0.26
first_order_MeanAbsoluteDeviation_PET                            0.01   0.94      0.08
first_order_Mean_CT                                              0.00   0.98      0.03
first_order_Mean_PET                                             0.00   0.96      0.05
first_order_Median_CT                                            0.26   0.61      0.71
first_order_Median_PET                                           0.00   0.98      0.03
first_order_Minimum_CT                                           0.05   0.83      0.27
first_order_Minimum_PET                                          0.49   0.48      1.05
first_order_Range_CT                                             0.17   0.68      0.56
first_order_Range_PET                                            0.00   1.00      0.01
first_order_RobustMeanAbsoluteDeviation_CT                       0.05   0.82      0.29
first_order_RobustMeanAbsoluteDeviation_PET                      0.00   0.95      0.08
first_order_RootMeanSquared_CT                                   0.00   0.96      0.06
first_order_RootMeanSquared_PET                                  0.00   0.99      0.02
first_order_Skewness_CT                                          0.37   0.54      0.88
first_order_Skewness_PET                                         0.08   0.78      0.37
first_order_TotalEnergy_CT                                       0.01   0.94      0.09
first_order_TotalEnergy_PET                                      0.19   0.66      0.59
first_order_Uniformity_CT_b20                                    0.00   0.96      0.07
first_order_Uniformity_CT_c16                                    0.01   0.92      0.12
first_order_Uniformity_PET_b2                                    0.12   0.73      0.45
first_order_Uniformity_PET_c04                                   0.01   0.94      0.10
first_order_Variance_CT                                          0.00   1.00      0.00
first_order_Variance_PET                                         0.00   0.99      0.02
glcm_Autocorrelation_d_1_CT_b20                                  0.15   0.70      0.51
glcm_Autocorrelation_d_1_CT_c16                                  0.01   0.91      0.14
glcm_Autocorrelation_d_1_PET_b2                                  0.00   0.98      0.03
glcm_Autocorrelation_d_1_PET_c04                                 0.03   0.87      0.20
glcm_ClusterProminence_d_1_CT_b20                                0.00   0.94      0.08
glcm_ClusterProminence_d_1_CT_c16                                0.01   0.93      0.10
glcm_ClusterProminence_d_1_PET_b2                                0.10   0.75      0.41
glcm_ClusterProminence_d_1_PET_c04                               0.17   0.68      0.56
glcm_ClusterShade_d_1_CT_b20                                     0.98   0.32      1.63
glcm_ClusterShade_d_1_CT_c16                                     0.00   0.96      0.06
glcm_ClusterShade_d_1_PET_b2                                     0.75   0.39      1.37
glcm_ClusterShade_d_1_PET_c04                                    0.33   0.57      0.82
glcm_ClusterTendency_d_1_CT_b20                                  0.01   0.91      0.14
glcm_ClusterTendency_d_1_CT_c16                                  0.01   0.94      0.09
glcm_ClusterTendency_d_1_PET_b2                                  0.00   0.97      0.05
glcm_ClusterTendency_d_1_PET_c04                                 0.09   0.76      0.40
glcm_Contrast_d_1_CT_b20                                         0.00   0.95      0.07
glcm_Contrast_d_1_CT_c16                                         0.03   0.86      0.21
glcm_Contrast_d_1_PET_b2                                         0.04   0.83      0.26
glcm_Contrast_d_1_PET_c04                                        0.01   0.94      0.09
glcm_Correlation_d_1_CT_b20                                      0.44   0.51      0.98
glcm_Correlation_d_1_CT_c16                                      0.72   0.40      1.33
glcm_Correlation_d_1_PET_b2                                      0.04   0.85      0.23
glcm_Correlation_d_1_PET_c04                                     0.02   0.88      0.18
glcm_DifferenceAverage_d_1_CT_b20                                0.00   0.98      0.02
glcm_DifferenceAverage_d_1_CT_c16                                0.00   0.97      0.05
glcm_DifferenceAverage_d_1_PET_b2                                0.00   0.98      0.03
glcm_DifferenceAverage_d_1_PET_c04                               0.00   0.96      0.06
glcm_DifferenceEntropy_d_1_CT_b20                                0.01   0.92      0.12
glcm_DifferenceEntropy_d_1_CT_c16                                0.00   0.95      0.08
glcm_DifferenceEntropy_d_1_PET_b2                                0.04   0.83      0.26
glcm_DifferenceEntropy_d_1_PET_c04                               0.13   0.72      0.47
glcm_DifferenceVariance_d_1_CT_b20                               0.01   0.93      0.11
glcm_DifferenceVariance_d_1_CT_c16                               0.04   0.84      0.26
glcm_DifferenceVariance_d_1_PET_b2                               0.10   0.76      0.40
glcm_DifferenceVariance_d_1_PET_c04                              0.08   0.77      0.37
glcm_Id_d_1_CT_b20                                               0.00   0.95      0.07
glcm_Id_d_1_CT_c16                                               0.00   0.98      0.02
glcm_Id_d_1_PET_b2                                               0.00   0.96      0.05
glcm_Id_d_1_PET_c04                                              0.01   0.91      0.14
glcm_Idm_d_1_CT_b20                                              0.00   0.95      0.08
glcm_Idm_d_1_CT_c16                                              0.00   1.00      0.00
glcm_Idm_d_1_PET_b2                                              0.00   0.99      0.02
glcm_Idm_d_1_PET_c04                                             0.01   0.93      0.11
glcm_Idmn_d_1_CT_b20                                             0.02   0.90      0.16
glcm_Idmn_d_1_CT_c16                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_b2                                             0.02   0.89      0.17
glcm_Idmn_d_1_PET_c04                                            0.00   0.95      0.08
glcm_Idn_d_1_CT_b20                                              0.01   0.92      0.12
glcm_Idn_d_1_CT_c16                                              0.00   0.98      0.02
glcm_Idn_d_1_PET_b2                                              0.23   0.63      0.66
glcm_Idn_d_1_PET_c04                                             0.01   0.94      0.08
glcm_Imc1_d_1_CT_b20                                             0.80   0.37      1.43
glcm_Imc1_d_1_CT_c16                                             0.08   0.78      0.37
glcm_Imc1_d_1_PET_b2                                             0.10   0.76      0.41
glcm_Imc1_d_1_PET_c04                                            0.02   0.90      0.16
glcm_Imc2_d_1_CT_b20                                             0.03   0.86      0.22
glcm_Imc2_d_1_CT_c16                                             0.71   0.40      1.32
glcm_Imc2_d_1_PET_b2                                             0.08   0.78      0.36
glcm_Imc2_d_1_PET_c04                                            0.01   0.92      0.12
glcm_InverseVariance_d_1_CT_b20                                  0.02   0.88      0.19
glcm_InverseVariance_d_1_CT_c16                                  0.02   0.89      0.17
glcm_InverseVariance_d_1_PET_b2                                  0.04   0.85      0.23
glcm_InverseVariance_d_1_PET_c04                                 0.06   0.80      0.31
glcm_JointAverage_d_1_CT_b20                                     0.06   0.81      0.30
glcm_JointAverage_d_1_CT_c16                                     0.04   0.85      0.23
glcm_JointAverage_d_1_PET_b2                                     0.00   0.96      0.06
glcm_JointAverage_d_1_PET_c04                                    0.00   0.98      0.03
glcm_JointEnergy_d_1_CT_b20                                      0.03   0.87      0.20
glcm_JointEnergy_d_1_CT_c16                                      0.01   0.93      0.10
glcm_JointEnergy_d_1_PET_b2                                      0.16   0.69      0.53
glcm_JointEnergy_d_1_PET_c04                                     0.00   0.98      0.02
glcm_JointEntropy_d_1_CT_b20                                     0.01   0.90      0.15
glcm_JointEntropy_d_1_CT_c16                                     0.08   0.78      0.36
glcm_JointEntropy_d_1_PET_b2                                     0.00   0.96      0.06
glcm_JointEntropy_d_1_PET_c04                                    0.00   0.96      0.06
glcm_MCC_d_1_CT_b20                                              0.40   0.53      0.92
glcm_MCC_d_1_CT_c16                                              0.06   0.81      0.30
glcm_MCC_d_1_PET_b2                                              0.01   0.92      0.12
glcm_MCC_d_1_PET_c04                                             0.02   0.88      0.19
glcm_MaximumProbability_d_1_CT_b20                               0.04   0.85      0.23
glcm_MaximumProbability_d_1_CT_c16                               0.10   0.76      0.40
glcm_MaximumProbability_d_1_PET_b2                               0.13   0.71      0.49
glcm_MaximumProbability_d_1_PET_c04                              0.00   1.00      0.00
glcm_SumAverage_d_1_CT_b20                                       0.06   0.81      0.30
glcm_SumAverage_d_1_CT_c16                                       0.04   0.85      0.23
glcm_SumAverage_d_1_PET_b2                                       0.00   0.96      0.06
glcm_SumAverage_d_1_PET_c04                                      0.00   0.98      0.03
glcm_SumEntropy_d_1_CT_b20                                       0.00   0.99      0.02
glcm_SumEntropy_d_1_CT_c16                                       0.08   0.78      0.36
glcm_SumEntropy_d_1_PET_b2                                       0.00   0.97      0.05
glcm_SumEntropy_d_1_PET_c04                                      0.01   0.93      0.10
glcm_SumSquares_d_1_CT_b20                                       0.01   0.92      0.12
glcm_SumSquares_d_1_CT_c16                                       0.00   0.96      0.06
glcm_SumSquares_d_1_PET_b2                                       0.00   0.96      0.05
glcm_SumSquares_d_1_PET_c04                                      0.09   0.76      0.39
gldm_DependenceEntropy_d_1_CT_b20                                0.21   0.65      0.62
gldm_DependenceEntropy_d_1_CT_c16                                0.11   0.75      0.42
gldm_DependenceEntropy_d_1_PET_b2                                0.06   0.81      0.30
gldm_DependenceEntropy_d_1_PET_c04                               0.03   0.87      0.20
gldm_DependenceNonUniformityNormalized_d_1_CT_b20                0.14   0.70      0.51
gldm_DependenceNonUniformityNormalized_d_1_CT_c16                0.03   0.86      0.21
gldm_DependenceNonUniformityNormalized_d_1_PET_b2                0.34   0.56      0.84
gldm_DependenceNonUniformityNormalized_d_1_PET_c04               0.05   0.82      0.28
gldm_DependenceNonUniformity_d_1_CT_b20                          0.02   0.90      0.15
gldm_DependenceNonUniformity_d_1_CT_c16                          2.56   0.11      3.19
gldm_DependenceNonUniformity_d_1_PET_b2                          0.04   0.85      0.24
gldm_DependenceNonUniformity_d_1_PET_c04                         0.11   0.74      0.42
gldm_DependenceVariance_d_1_CT_b20                               0.83   0.36      1.47
gldm_DependenceVariance_d_1_CT_c16                               0.06   0.81      0.30
gldm_DependenceVariance_d_1_PET_b2                               0.28   0.60      0.75
gldm_DependenceVariance_d_1_PET_c04                              0.56   0.46      1.13
gldm_GrayLevelNonUniformity_d_1_CT_b20                           0.35   0.55      0.86
gldm_GrayLevelNonUniformity_d_1_CT_c16                           0.36   0.55      0.87
gldm_GrayLevelNonUniformity_d_1_PET_b2                           0.20   0.65      0.61
gldm_GrayLevelNonUniformity_d_1_PET_c04                          0.00   0.99      0.01
gldm_GrayLevelVariance_d_1_CT_b20                                0.00   1.00      0.00
gldm_GrayLevelVariance_d_1_CT_c16                                0.00   1.00      0.01
gldm_GrayLevelVariance_d_1_PET_b2                                0.00   0.98      0.03
gldm_GrayLevelVariance_d_1_PET_c04                               0.04   0.84      0.24
gldm_HighGrayLevelEmphasis_d_1_CT_b20                            0.16   0.69      0.54
gldm_HighGrayLevelEmphasis_d_1_CT_c16                            0.01   0.91      0.14
gldm_HighGrayLevelEmphasis_d_1_PET_b2                            0.00   0.98      0.03
gldm_HighGrayLevelEmphasis_d_1_PET_c04                           0.04   0.85      0.24
gldm_LargeDependenceEmphasis_d_1_CT_b20                          0.01   0.91      0.14
gldm_LargeDependenceEmphasis_d_1_CT_c16                          0.02   0.89      0.16
gldm_LargeDependenceEmphasis_d_1_PET_b2                          0.05   0.82      0.28
gldm_LargeDependenceEmphasis_d_1_PET_c04                         0.02   0.89      0.17
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.69   0.41      1.30
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.00   0.95      0.07
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.04   0.85      0.24
gldm_LargeDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.00   0.99      0.01
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.02   0.89      0.17
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.04   0.84      0.24
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.10   0.75      0.41
gldm_LargeDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.51   0.48      1.07
gldm_LowGrayLevelEmphasis_d_1_CT_b20                             0.03   0.87      0.20
gldm_LowGrayLevelEmphasis_d_1_CT_c16                             0.00   0.97      0.04
gldm_LowGrayLevelEmphasis_d_1_PET_b2                             0.01   0.94      0.09
gldm_LowGrayLevelEmphasis_d_1_PET_c04                            0.50   0.48      1.06
gldm_SmallDependenceEmphasis_d_1_CT_b20                          0.01   0.91      0.14
gldm_SmallDependenceEmphasis_d_1_CT_c16                          0.10   0.75      0.42
gldm_SmallDependenceEmphasis_d_1_PET_b2                          0.10   0.76      0.40
gldm_SmallDependenceEmphasis_d_1_PET_c04                         0.03   0.87      0.20
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20             0.27   0.60      0.74
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_c16             0.03   0.87      0.20
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_b2             0.05   0.82      0.28
gldm_SmallDependenceHighGrayLevelEmphasis_d_1_PET_c04            0.01   0.92      0.12
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20              0.02   0.88      0.19
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_c16              0.20   0.66      0.61
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_b2              0.03   0.87      0.19
gldm_SmallDependenceLowGrayLevelEmphasis_d_1_PET_c04             0.00   0.99      0.02
glrlm_GrayLevelNonUniformityNormalized_CT_b20                    0.00   0.96      0.05
glrlm_GrayLevelNonUniformityNormalized_CT_c16                    0.46   0.50      1.01
glrlm_GrayLevelNonUniformityNormalized_PET_b2                    0.03   0.87      0.21
glrlm_GrayLevelNonUniformityNormalized_PET_c04                   0.04   0.84      0.25
glrlm_GrayLevelNonUniformity_CT_b20                              0.01   0.93      0.10
glrlm_GrayLevelNonUniformity_CT_c16                              1.08   0.30      1.74

In [9]:
# Access the summary table
summary_table = results.summary

# Filter columns based on p-values lower than 0.05
significant_columns = summary_table[summary_table['p'] < 0.05].index

# Display significant columns
print("Columns with p-values < 0.05:")
print(significant_columns)

Columns with p-values < 0.05:
Index(['charlson', 'glszm_LargeAreaEmphasis_CT_c16',
       'glszm_LargeAreaLowGrayLevelEmphasis_CT_c16',
       'glszm_ZoneVariance_CT_c16', 'ngtdm_Busyness_d_1_PET_b2'],
      dtype='object')

## Test dataset: MAASTRO

In [10]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [11]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [12]:
# Need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [13]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [14]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [15]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [16]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# Set y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [17]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [18]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [19]:
# Change the name of a column 'DFS_event' in the clincial_test 
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [20]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

# Standardization

In [21]:
# Copy the original X for later 
original_X = X.copy()

In [22]:
# Standardize the data 
## Save the column and index 
X_columns = X.columns 
X_index = X.index

## Standardize the data but not the categorical columns
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']
### Separate the categorical and non-categorical columns
X_categorical = X[categorical_columns]
X_numeric = X.drop(categorical_columns, axis=1)
X_numeric_columns = X_numeric.columns
X_numeric_index = X_numeric.index

### Standardize non-categorical and then concat with the categorical
scaler = MinMaxScaler()  
X_numeric_std = scaler.fit_transform(X_numeric)
X_numeric_std = pd.DataFrame(X_numeric_std, columns=X_numeric_columns, index=X_numeric_index)
X_std = pd.concat([X_categorical, X_numeric_std], axis=1)

## Sort the order of the columns as it was in the clinical train 
X_std = X_std[original_X.columns]

In [23]:
# Divide the X_MAASTRO into numerical part and categorical part 
X_MAASTRO_categorical = X_MAASTRO[categorical_columns]
X_MAASTRO_numeric = X_MAASTRO.drop(categorical_columns, axis=1)

# Save the column name and index of the numeric part
X_MAASTRO_numeric_columns = X_MAASTRO_numeric.columns
X_MAASTRO_numeric_index = X_MAASTRO_numeric.index

In [24]:
# Standardize the numeric part 
X_MAASTRO_numeric_std = scaler.transform(X_MAASTRO_numeric)

# Change the standardized part into a dataframe 
X_MAASTRO_numeric_std = pd.DataFrame(X_MAASTRO_numeric_std, columns=X_MAASTRO_numeric_columns, index=X_MAASTRO_numeric_index)

# Concat the standardized part with the categorical part 
X_MAASTRO_std = pd.concat([X_MAASTRO_categorical, X_MAASTRO_numeric_std], axis=1)

# Change the column order of X_MAASTRO_std
X_MAASTRO_std = X_MAASTRO_std[original_X.columns]

In [25]:
# Saving the data 
X_new = X 
X_new_std = X_std 
MAASTRO_new = X_MAASTRO 
MAASTRO_new_std = X_MAASTRO_std

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [29]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:39:38,551] A new study created in memory with name: no-name-aa9910a6-7df4-4c31-9655-bc06ea7d5140
python(9921) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.

  0%|          | 0/1 [00:00<?, ?it/s]

[W 2024-04-16 09:39:39,278] Trial 0 failed with parameters: {} because of the following error: LinAlgError('Matrix is singular.').
Traceback (most recent call last):
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/optuna/study/_optimize.py", line 200, in _run_trial
    value_or_values = func(trial)
  File "/var/folders/64/jkqp6xyx2hj50dmd2pqfm3780000gn/T/ipykernel_82324/1714754791.py", line 62, in objective
    model.fit(X_train_std, y_train)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/sksurv/linear_model/coxph.py", line 449, in fit
    delta = solve(
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 220, in solve
    _solve_check(n, info)
  File "/Users/minjeongcheon/opt/anaconda3/lib/python3.9/site-packages/scipy/linalg/_basic.py", line 29, in _solve_check
    raise LinAlgError('Matrix is singular.')
numpy.linalg.LinAlgError: Matrix is singular.
[W 2024-04-16 09:39:39,282] Trial 0 failed with value None.

LinAlgError: Matrix is singular.

In [30]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {}

In [31]:
# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

ValueError: No trials are completed yet.

In [32]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

ValueError: No trials are completed yet.

#### Test

In [33]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [34]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

ValueError: search direction contains NaN or infinite values

In [35]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [36]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

NameError: name 'c_index' is not defined

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [37]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:39:45,960] A new study created in memory with name: no-name-170fb5c5-82b4-4f11-a92e-0b64f9d6954e

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-16 09:39:46,217] A new study created in memory with name: no-name-ba8d7aae-c643-49e5-8430-bb8c9d21fc96

Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6223175965665236
[I 2024-04-16 09:39:46,210] Trial 0 finished with value: 0.6438044662040505 and parameters: {}. Best is trial 0 with value: 0.6438044662040505.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6438044662040505], datetime_start=datetime.datetime(2024, 4, 16, 9, 39, 45, 994715), datetime_complete=datetime.datetime(2024, 4, 16, 9, 39, 46, 209912), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6438044662040505

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709935455955
Fold 2 IBS: 0.2320398831647367
Fold 3 IBS: 0.22898186660907244
Fold 4 IBS: 0.24197477002703405
Fold 5 IBS: 0.22939559119644085
[I 2024-04-16 09:39:46,527] Trial 0 finished with value: 0.2359278420703687 and parameters: {}. Best is trial 0 with value: 0.2359278420703687.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2359278420703687], datetime_start=datetime.datetime(2024, 4, 16, 9, 39, 46, 262440), datetime_complete=datetime.datetime(2024, 4, 16, 9, 39, 46, 527648), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2359278420703687

In [38]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [39]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.644
train_ibs:  0.236

#### Test

In [40]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [41]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.601

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [42]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [43]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:39:47,090] A new study created in memory with name: no-name-ed1a8088-6c0e-496a-a9fb-818ab3266ee4

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.41832669322709165
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.4723404255319149
Fold 4 C-index: 0.4790874524714829

[I 2024-04-16 09:39:48,832] A new study created in memory with name: no-name-266725a6-47a3-45be-8e57-e6c9c088dda8

Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 09:39:48,807] Trial 0 finished with value: 0.5092372036296025 and parameters: {}. Best is trial 0 with value: 0.5092372036296025.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.5092372036296025], datetime_start=datetime.datetime(2024, 4, 16, 9, 39, 47, 139058), datetime_complete=datetime.datetime(2024, 4, 16, 9, 39, 48, 806711), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.5092372036296025

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.4738282359790709
Fold 2 IBS: 0.3200280958202138
Fold 3 IBS: 0.4115943078102989
Fold 4 IBS: 0.3977654075725291
Fold 5 IBS: 0.36596639621612437
[I 2024-04-16 09:39:50,419] Trial 0 finished with value: 0.3938364886796474 and parameters: {}. Best is trial 0 with value: 0.3938364886796474.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.3938364886796474], datetime_start=datetime.datetime(2024, 4, 16, 9, 39, 48, 870048), datetime_complete=datetime.datetime(2024, 4, 16, 9, 39, 50, 419632), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.3938364886796474

In [44]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [45]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.509
train_ibs:  0.394

#### Test

In [46]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [47]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.516

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.406

In [48]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [49]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:39:51,201] A new study created in memory with name: no-name-f8411e01-7ab1-4bf4-9d68-4fc10974942b

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5450643776824035
[I 2024-04-16 09:39:52,335] Trial 0 finished with value: 0.5597999024041913 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.5597999024041913.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:39:52,698] Trial 1 finished with value: 0.6141583213579954 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6141583213579954.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:39:52,970] Trial 2 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 09:39:53,962] Trial 3 finished with value: 0.5725480522819093 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 09:39:54,996] Trial 4 finished with value: 0.5573988748205609 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 09:39:55,686] Trial 5 finished with value: 0.6175803478058993 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.451063829787234
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 09:39:56,714] Trial 6 finished with value: 0.5128262050203016 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5450643776824035
[I 2024-04-16 09:39:57,559] Trial 7 finished with value: 0.5637981364097439 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.6666666666666666
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 09:39:58,262] Trial 8 finished with value: 0.5962901922512872 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 09:39:58,803] Trial 9 finished with value: 0.6064232130286428 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:39:59,074] Trial 10 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:39:59,334] Trial 11 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:39:59,576] Trial 12 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:39:59,790] Trial 13 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.18977351772466045}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:00,138] Trial 14 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.187901372232152}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:00,380] Trial 15 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.187063776657101}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:00,780] Trial 16 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:01,221] Trial 17 finished with value: 0.6117678831109835 and parameters: {'l1_ratio': 0.32086883765249574}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:01,465] Trial 18 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.11915385898218006}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:01,765] Trial 19 finished with value: 0.6149551341069994 and parameters: {'l1_ratio': 0.2771695014618133}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 09:40:02,783] Trial 20 finished with value: 0.569451976106069 and parameters: {'l1_ratio': 0.5914245950308872}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:03,008] Trial 21 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.009313864616061021}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:03,255] Trial 22 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.1016291706752447}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:03,571] Trial 23 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 2 with value: 0.6253136998440512.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:03,802] Trial 24 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.11448133231208517}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:04,026] Trial 25 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.23869456856336438}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 09:40:04,511] Trial 26 finished with value: 0.6004261256771993 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:04,867] Trial 27 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.07507861039748792}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:05,133] Trial 28 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.19772188082870518}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.502127659574468
Fold 4 C-index: 0.5513307984790875
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 09:40:06,889] Trial 29 finished with value: 0.5272594823965314 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:07,241] Trial 30 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.0508148603646557}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:07,684] Trial 31 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.12559464536449572}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:07,986] Trial 32 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.0674387920700233}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:08,280] Trial 33 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.2524470716658479}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:08,536] Trial 34 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.17197863077056014}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:08,813] Trial 35 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.14927218250785496}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:09,131] Trial 36 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.057925419230613756}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:09,610] Trial 37 finished with value: 0.6125646958599875 and parameters: {'l1_ratio': 0.2933152842207709}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 09:40:10,189] Trial 38 finished with value: 0.6159467849087373 and parameters: {'l1_ratio': 0.4297947545378429}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:10,491] Trial 39 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:10,782] Trial 40 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.23125077465092259}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:11,044] Trial 41 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.14662749624950017}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:11,325] Trial 42 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.2093161642158936}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:11,552] Trial 43 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.09194828256645544}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 09:40:12,126] Trial 44 finished with value: 0.6004261256771993 and parameters: {'l1_ratio': 0.3561761752325566}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6511627906976745
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 09:40:13,181] Trial 45 finished with value: 0.5742032341296257 and parameters: {'l1_ratio': 0.532905188903257}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.44223107569721115
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 09:40:14,043] Trial 46 finished with value: 0.5384540875964922 and parameters: {'l1_ratio': 0.8167652444349325}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859

Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:14,279] Trial 47 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.1563134758404386}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:14,852] Trial 48 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.03497971425151816}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 09:40:15,900] Trial 49 finished with value: 0.6143531594107293 and parameters: {'l1_ratio': 0.45122940483907514}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5579399141630901
[I 2024-04-16 09:40:16,887] Trial 50 finished with value: 0.5703862152361191 and parameters: {'l1_ratio': 0.6064718647459368}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:17,263] Trial 51 finished with value: 0.6125646958599875 and parameters: {'l1_ratio': 0.2899996396587513}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:17,947] Trial 52 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.1913842919448679}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:18,584] Trial 53 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.10721729557236041}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:19,263] Trial 54 finished with value: 0.6085806321149676 and parameters: {'l1_ratio': 0.34625466233052565}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:19,670] Trial 55 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.019918167274360632}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:20,016] Trial 56 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.2590406280116174}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:20,541] Trial 57 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.08617893072376406}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:20,918] Trial 58 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.2159578167968363}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:21,313] Trial 59 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.13949079898210318}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:22,083] Trial 60 finished with value: 0.6117678831109835 and parameters: {'l1_ratio': 0.31843128943524074}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:22,451] Trial 61 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.1714407815234303}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:22,841] Trial 62 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.19045637554311906}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:23,112] Trial 63 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.00011033117624231238}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:23,437] Trial 64 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.11116258298001065}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:23,746] Trial 65 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.0760252739093915}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:24,037] Trial 66 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.25824517195500296}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:24,373] Trial 67 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.12301001014541578}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:24,679] Trial 68 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.05412089583336485}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:24,978] Trial 69 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.17360130515807745}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:25,433] Trial 70 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.22913383872562726}. Best is trial 2 with value: 0.6253136998440512.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:25,707] Trial 71 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.03282161696535647}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:26,014] Trial 72 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.0023417997955162556}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:26,385] Trial 73 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.0771592681335048}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:26,649] Trial 74 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.045514696778792295}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:26,935] Trial 75 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.11795158199092087}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 09:40:27,482] Trial 76 finished with value: 0.6064232130286428 and parameters: {'l1_ratio': 0.3870355975595541}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:27,777] Trial 77 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.09245405722205902}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:28,081] Trial 78 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.14026134747338187}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.4595744680851064
Fold 4 C-index: 0.49049429657794674
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 09:40:29,215] Trial 79 finished with value: 0.5145430702045616 and parameters: {'l1_ratio': 0.9846333768922103}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:29,467] Trial 80 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.17409236413969337}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:29,762] Trial 81 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.023760692816302692}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:30,055] Trial 82 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.06719361871228363}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:30,312] Trial 83 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.1555364957001691}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:30,583] Trial 84 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.20160100084782534}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:30,797] Trial 85 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.13257827709423287}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:31,084] Trial 86 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.10005463435646575}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:31,314] Trial 87 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.05316848523878631}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:31,810] Trial 88 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.23596308992395137}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:32,262] Trial 89 finished with value: 0.6125646958599875 and parameters: {'l1_ratio': 0.30835665887755975}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.44621513944223107
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 09:40:33,170] Trial 90 finished with value: 0.5581593310943253 and parameters: {'l1_ratio': 0.7135825642664739}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:33,427] Trial 91 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.02030215216472258}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:33,686] Trial 92 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.020389642569673343}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.450199203187251
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 09:40:34,591] Trial 93 finished with value: 0.5653558292755683 and parameters: {'l1_ratio': 0.6547273520711029}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:34,839] Trial 94 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.08711373012572787}. Best is trial 2 with value: 0.6253136998440512.

Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:35,192] Trial 95 finished with value: 0.6149551341069994 and parameters: {'l1_ratio': 0.27309107387256243}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:35,519] Trial 96 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.06382553610115703}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:35,766] Trial 97 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.11095939444363113}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.43824701195219123
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.5446808510638298
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 09:40:36,588] Trial 98 finished with value: 0.5451503717282128 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 2 with value: 0.6253136998440512.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.6939163498098859

[I 2024-04-16 09:40:36,810] A new study created in memory with name: no-name-2b20d194-3c80-4fe7-a2a9-e93831fd70ad

Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 09:40:36,802] Trial 99 finished with value: 0.6253136998440512 and parameters: {'l1_ratio': 0.1654067044122741}. Best is trial 2 with value: 0.6253136998440512.


* Best trial for C-index:
 FrozenTrial(number=2, state=TrialState.COMPLETE, values=[0.6253136998440512], datetime_start=datetime.datetime(2024, 4, 16, 9, 39, 52, 702274), datetime_complete=datetime.datetime(2024, 4, 16, 9, 39, 52, 970619), params={'l1_ratio': 0.22692876841884668}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=2, value=None)


* Best Score for C-index:
 0.6253136998440512

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.4313568890599343
Fold 2 IBS: 0.2656952358110491
Fold 3 IBS: 0.3081336866379725
Fold 4 IBS: 0.3300262592879362
Fold 5 IBS: 0.3042578459972329
[I 2024-04-16 09:40:37,800] Trial 0 finished with value: 0.32789398335882497 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.32789398335882497.
Fold 1 IBS: 0.35138663591425773
Fold 2 IBS: 0.2290220733303913
Fold 3 IBS: 0.2256095843510887
Fold 4 IBS: 0.23904537121643243
Fold 5 IBS: 0.22533252505308748
[I 2024-04-16 09:40:38,188] Trial 1 finished with value: 0.25407923797305154 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.25407923797305154.
Fold 1 IBS: 0.24534873181304112
Fold 2 IBS: 0.22952050649910102
Fold 3 IBS: 0.22621851462348927
Fold 4 IBS: 0.23949401370266352
Fold 5 IBS: 0.22600795958694317
[I 2024-04-16 09:40:38,453] Trial 2 finished with value: 0.23331794524504762 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.41375044801633976
Fold 2 IBS: 0.24990150056497903
Fold 3 IBS: 0.2921195075836531
Fold 4 IBS: 0.32936456298614053
Fold 5 IBS: 0.2898483693735418
[I 2024-04-16 09:40:39,345] Trial 3 finished with value: 0.3149968777049309 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.43311259071860914
Fold 2 IBS: 0.26808705975269137
Fold 3 IBS: 0.3124497460943788
Fold 4 IBS: 0.3307911290457366
Fold 5 IBS: 0.30674078080107264
[I 2024-04-16 09:40:40,205] Trial 4 finished with value: 0.3302362612824977 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.38688323629338633
Fold 2 IBS: 0.2358858091455868
Fold 3 IBS: 0.22424189131621095
Fold 4 IBS: 0.23823802232157842
Fold 5 IBS: 0.2775042704852588
[I 2024-04-16 09:40:40,862] Trial 5 finished with value: 0.27255064591240424 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.4612309575649333
Fold 2 IBS: 0.31125514439452895
Fold 3 IBS: 0.41233817904978914
Fold 4 IBS: 0.37120132606598133
Fold 5 IBS: 0.34966150506875304
[I 2024-04-16 09:40:41,966] Trial 6 finished with value: 0.38113742242879717 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.4301800342457628
Fold 2 IBS: 0.26444543956519195
Fold 3 IBS: 0.3066423191004207
Fold 4 IBS: 0.32977744829407735
Fold 5 IBS: 0.30299783270860375
[I 2024-04-16 09:40:42,932] Trial 7 finished with value: 0.32680861478281137 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.39974017421812436
Fold 2 IBS: 0.24155591895991307
Fold 3 IBS: 0.223684072766207
Fold 4 IBS: 0.3274233082759058
Fold 5 IBS: 0.2834242338029241
[I 2024-04-16 09:40:43,721] Trial 8 finished with value: 0.2951655416046149 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.3799853400896271
Fold 2 IBS: 0.2282556317468459
Fold 3 IBS: 0.22454918253728018
Fold 4 IBS: 0.2383955194847201
Fold 5 IBS: 0.27384373943253054
[I 2024-04-16 09:40:44,226] Trial 9 finished with value: 0.2690058826582008 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.24642911665181527
Fold 2 IBS: 0.23097890767627766
Fold 3 IBS: 0.22784888268652972
Fold 4 IBS: 0.24089250075498198
Fold 5 IBS: 0.2279687483136463
[I 2024-04-16 09:40:44,541] Trial 10 finished with value: 0.2348236312166502 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.24711499201557124
Fold 2 IBS: 0.2318734350359954
Fold 3 IBS: 0.22880457273736035
Fold 4 IBS: 0.24180155756005528
Fold 5 IBS: 0.2291711791966438
[I 2024-04-16 09:40:44,837] Trial 11 finished with value: 0.23575314730912522 and parameters: {'l1_ratio': 0.012263077917218868}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.24642987796807989
Fold 2 IBS: 0.23097992163030576
Fold 3 IBS: 0.22784997517916802
Fold 4 IBS: 0.24089351095473302
Fold 5 IBS: 0.22797010951314764
[I 2024-04-16 09:40:45,146] Trial 12 finished with value: 0.23482467904908683 and parameters: {'l1_ratio': 0.0837403091112675}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.2456018447276526
Fold 2 IBS: 0.22986209461805976
Fold 3 IBS: 0.22661549773096976
Fold 4 IBS: 0.23981098529568215
Fold 5 IBS: 0.2264685265000701
[I 2024-04-16 09:40:45,448] Trial 13 finished with value: 0.23367178977448688 and parameters: {'l1_ratio': 0.18977351772466045}. Best is trial 2 with value: 0.23331794524504762.
Fold 1 IBS: 0.24524694210170983
Fold 2 IBS: 0.22938430887399935
Fold 3 IBS: 0.22605613844364272
Fold 4 IBS: 0.2393696949724494
Fold 5 IBS: 0.22582386536589324
[I 2024-04-16 09:40:46,102] Trial 14 finished with value: 0.2331761899515389 and parameters: {'l1_ratio': 0.24249236510312352}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.24536455899266338
Fold 2 IBS: 0.22954175884549283
Fold 3 IBS: 0.226243620833192
Fold 4 IBS: 0.23951352249754407
Fold 5 IBS: 0.22603665929951283
[I 2024-04-16 09:40:46,538] Trial 15 finished with value: 0.23334002409368101 and parameters: {'l1_ratio': 0.2245403429070307}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.35992048465129994
Fold 2 IBS: 0.22880588019649717
Fold 3 IBS: 0.22533038000009467
Fold 4 IBS: 0.2388566115070142
Fold 5 IBS: 0.22503777743207978
[I 2024-04-16 09:40:47,002] Trial 16 finished with value: 0.2555902267573972 and parameters: {'l1_ratio': 0.31408489302885545}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.24590677213859052
Fold 2 IBS: 0.23027575740487552
Fold 3 IBS: 0.2270812158963346
Fold 4 IBS: 0.24020398891319952
Fold 5 IBS: 0.22702476148282305
[I 2024-04-16 09:40:47,344] Trial 17 finished with value: 0.23409849916716463 and parameters: {'l1_ratio': 0.14799833455264066}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.3670376152881628
Fold 2 IBS: 0.22862292016344704
Fold 3 IBS: 0.22508469649941876
Fold 4 IBS: 0.23870000506259786
Fold 5 IBS: 0.22478723614970997
[I 2024-04-16 09:40:48,040] Trial 18 finished with value: 0.2568464946326673 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.4131811931302223
Fold 2 IBS: 0.24940332867881626
Fold 3 IBS: 0.291714172120593
Fold 4 IBS: 0.32925625130723374
Fold 5 IBS: 0.2895562989810708
[I 2024-04-16 09:40:49,124] Trial 19 finished with value: 0.3146222488435872 and parameters: {'l1_ratio': 0.5476641842948985}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.24532034294047073
Fold 2 IBS: 0.2294824340492573
Fold 3 IBS: 0.22617338687645988
Fold 4 IBS: 0.23945913819583822
Fold 5 IBS: 0.22595652836513586
[I 2024-04-16 09:40:49,485] Trial 20 finished with value: 0.23327836608543243 and parameters: {'l1_ratio': 0.2312342395344777}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.24528425736205145
Fold 2 IBS: 0.22943413391819506
Fold 3 IBS: 0.22611584734994647
Fold 4 IBS: 0.23941503114058088
Fold 5 IBS: 0.22589124772561373
[I 2024-04-16 09:40:49,860] Trial 21 finished with value: 0.2332281034992775 and parameters: {'l1_ratio': 0.23674640483253295}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.2460881022085272
Fold 2 IBS: 0.23052118923397913
Fold 3 IBS: 0.22735186333325125
Fold 4 IBS: 0.2404415092111135
Fold 5 IBS: 0.22735434242608163
[I 2024-04-16 09:40:50,200] Trial 22 finished with value: 0.23435140128259055 and parameters: {'l1_ratio': 0.12469232350040972}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.24722124716322966
Fold 2 IBS: 0.23200736201124192
Fold 3 IBS: 0.22894726419601164
Fold 4 IBS: 0.2419408653575625
Fold 5 IBS: 0.2293517399112841
[I 2024-04-16 09:40:50,487] Trial 23 finished with value: 0.23589369572786598 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 14 with value: 0.2331761899515389.
Fold 1 IBS: 0.24511658418028567
Fold 2 IBS: 0.2292113782684044
Fold 3 IBS: 0.22584588173788686
Fold 4 IBS: 0.23921367347251105
Fold 5 IBS: 0.22558964461679437
[I 2024-04-16 09:40:50,806] Trial 24 finished with value: 0.23299543245517648 and parameters: {'l1_ratio': 0.2629237523336605}. Best is trial 24 with value: 0.23299543245517648.

Fold 1 IBS: 0.37940015123096377
Fold 2 IBS: 0.22827181985588968
Fold 3 IBS: 0.22457386307846533
Fold 4 IBS: 0.23840863230305193
Fold 5 IBS: 0.27353957588314765
[I 2024-04-16 09:40:51,340] Trial 25 finished with value: 0.2688388084703036 and parameters: {'l1_ratio': 0.38971525832834536}. Best is trial 24 with value: 0.23299543245517648.
Fold 1 IBS: 0.35297283759207587
Fold 2 IBS: 0.22898324998081745
Fold 3 IBS: 0.22556023378728773
Fold 4 IBS: 0.2390111946103968
Fold 5 IBS: 0.2252796882671587
[I 2024-04-16 09:40:51,834] Trial 26 finished with value: 0.2543614408475473 and parameters: {'l1_ratio': 0.2911123931485357}. Best is trial 24 with value: 0.23299543245517648.
Fold 1 IBS: 0.4001955028052518
Fold 2 IBS: 0.2417968478002696
Fold 3 IBS: 0.2236618398177358
Fold 4 IBS: 0.3275664814587584
Fold 5 IBS: 0.2836083219908448
[I 2024-04-16 09:40:52,720] Trial 27 finished with value: 0.29536579877457203 and parameters: {'l1_ratio': 0.48333206147305935}. Best is trial 24 with value: 0.23299543245517648.
Fold 1 IBS: 0.4562840390347286
Fold 2 IBS: 0.31197696216233656
Fold 3 IBS: 0.408612696706481
Fold 4 IBS: 0.3596187491245288
Fold 5 IBS: 0.3420161369279488
[I 2024-04-16 09:40:55,158] Trial 28 finished with value: 0.3757017167912048 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 24 with value: 0.23299543245517648.
Fold 1 IBS: 0.24586484779163212
Fold 2 IBS: 0.2302188942625727
Fold 3 IBS: 0.227017977622799
Fold 4 IBS: 0.24014940842711174
Fold 5 IBS: 0.22694836708968508
[I 2024-04-16 09:40:56,161] Trial 29 finished with value: 0.23403989903876013 and parameters: {'l1_ratio': 0.15354880795613854}. Best is trial 24 with value: 0.23299543245517648.
Fold 1 IBS: 0.4252149361630647
Fold 2 IBS: 0.2591875684329625
Fold 3 IBS: 0.30107134617108855
Fold 4 IBS: 0.32990280443277226
Fold 5 IBS: 0.2979889689052297
[I 2024-04-16 09:40:57,584] Trial 30 finished with value: 0.32267312482102356 and parameters: {'l1_ratio': 0.6348147138790865}. Best is trial 24 with value: 0.23299543245517648.
Fold 1 IBS: 0.24524015901768775
Fold 2 IBS: 0.22937526586808107
Fold 3 IBS: 0.2260452618836331
Fold 4 IBS: 0.23936148469015422
Fold 5 IBS: 0.2258116311889695
[I 2024-04-16 09:40:58,140] Trial 31 finished with value: 0.2331667605297051 and parameters: {'l1_ratio': 0.24354183082267372}. Best is trial 24 with value: 0.23299543245517648.
Fold 1 IBS: 0.24510845874959233
Fold 2 IBS: 0.22920066482040755
Fold 3 IBS: 0.22583269014599783
Fold 4 IBS: 0.23920407745090286
Fold 5 IBS: 0.22557511462234478
[I 2024-04-16 09:40:58,924] Trial 32 finished with value: 0.23298420115784907 and parameters: {'l1_ratio': 0.2642152854612092}. Best is trial 32 with value: 0.23298420115784907.
Fold 1 IBS: 0.36727629313257515
Fold 2 IBS: 0.22861691764477307
Fold 3 IBS: 0.22507647008282308
Fold 4 IBS: 0.23869491914644786
Fold 5 IBS: 0.22477899718881955
[I 2024-04-16 09:41:00,176] Trial 33 finished with value: 0.25688871943908775 and parameters: {'l1_ratio': 0.33967020776393025}. Best is trial 32 with value: 0.23298420115784907.
Fold 1 IBS: 0.24645281123775845
Fold 2 IBS: 0.2310104460463938
Fold 3 IBS: 0.22788284965706473
Fold 4 IBS: 0.2409239448544075
Fold 5 IBS: 0.2280110884904731
[I 2024-04-16 09:41:00,699] Trial 34 finished with value: 0.2348562280572195 and parameters: {'l1_ratio': 0.08112681909214389}. Best is trial 32 with value: 0.23298420115784907.
Fold 1 IBS: 0.3891958612482959
Fold 2 IBS: 0.23696695249380237
Fold 3 IBS: 0.2241341992411913
Fold 4 IBS: 0.23818534999357768
Fold 5 IBS: 0.2788514558929067
[I 2024-04-16 09:41:01,539] Trial 35 finished with value: 0.2734667637739548 and parameters: {'l1_ratio': 0.4341659024174019}. Best is trial 32 with value: 0.23298420115784907.
Fold 1 IBS: 0.24509759156202052
Fold 2 IBS: 0.22918634957628564
Fold 3 IBS: 0.22581503157386043
Fold 4 IBS: 0.23919126834785234
Fold 5 IBS: 0.22555569594627575
[I 2024-04-16 09:41:01,991] Trial 36 finished with value: 0.23296918740125894 and parameters: {'l1_ratio': 0.26594584591028053}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.4460178167624279
Fold 2 IBS: 0.2910881045006172
Fold 3 IBS: 0.3631296987541427
Fold 4 IBS: 0.34016910501805686
Fold 5 IBS: 0.3240460796631272
[I 2024-04-16 09:41:03,500] Trial 37 finished with value: 0.3528901609396744 and parameters: {'l1_ratio': 0.8808567522730943}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.34791176534850315
Fold 2 IBS: 0.22910674293960437
Fold 3 IBS: 0.2257161247766131
Fold 4 IBS: 0.23912031325070893
Fold 5 IBS: 0.2254476275533932
[I 2024-04-16 09:41:03,984] Trial 38 finished with value: 0.2534605147737645 and parameters: {'l1_ratio': 0.2756715601318073}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.37025019235305484
Fold 2 IBS: 0.22853226624671422
Fold 3 IBS: 0.224959226783285
Fold 4 IBS: 0.23862356296689421
Fold 5 IBS: 0.2687139875753198
[I 2024-04-16 09:41:04,930] Trial 39 finished with value: 0.26621584718505364 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24563612217392722
Fold 2 IBS: 0.22990855206260166
Fold 3 IBS: 0.2266685251489912
Fold 4 IBS: 0.23985464224872147
Fold 5 IBS: 0.2265310632817343
[I 2024-04-16 09:41:05,332] Trial 40 finished with value: 0.23371978098319515 and parameters: {'l1_ratio': 0.18491433848820432}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2451362220236568
Fold 2 IBS: 0.22923730505442297
Fold 3 IBS: 0.22587772204173368
Fold 4 IBS: 0.23923693041691835
Fold 5 IBS: 0.22562479765937676
[I 2024-04-16 09:41:05,782] Trial 41 finished with value: 0.2330225954392217 and parameters: {'l1_ratio': 0.2598109062528112}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.38763353338687406
Fold 2 IBS: 0.23622006931668155
Fold 3 IBS: 0.22420724048562105
Fold 4 IBS: 0.2382209316964379
Fold 5 IBS: 0.27791089675410013
[I 2024-04-16 09:41:06,756] Trial 42 finished with value: 0.27283853432794297 and parameters: {'l1_ratio': 0.4266958560552492}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24516022882282998
Fold 2 IBS: 0.22926906325482768
Fold 3 IBS: 0.22591656603971375
Fold 4 IBS: 0.23926548408851298
Fold 5 IBS: 0.22566783885181074
[I 2024-04-16 09:41:07,111] Trial 43 finished with value: 0.233055836211539 and parameters: {'l1_ratio': 0.2560221525361376}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.35175209116849554
Fold 2 IBS: 0.2290129281311119
Fold 3 IBS: 0.22559798844174755
Fold 4 IBS: 0.23903730990944771
Fold 5 IBS: 0.22532008230357292
[I 2024-04-16 09:41:07,588] Trial 44 finished with value: 0.2541440799908751 and parameters: {'l1_ratio': 0.28736138537485967}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3751064728257289
Fold 2 IBS: 0.2283940964799657
Fold 3 IBS: 0.22475798461719054
Fold 4 IBS: 0.2385086361469367
Fold 5 IBS: 0.2712745017696073
[I 2024-04-16 09:41:08,227] Trial 45 finished with value: 0.2676083383678859 and parameters: {'l1_ratio': 0.37145793322536885}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24569391270596097
Fold 2 IBS: 0.2299869315219524
Fold 3 IBS: 0.22675753613693056
Fold 4 IBS: 0.2399285790090669
Fold 5 IBS: 0.22663652586060343
[I 2024-04-16 09:41:08,626] Trial 46 finished with value: 0.23380069704690282 and parameters: {'l1_ratio': 0.17681569952657636}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24625677701234588
Fold 2 IBS: 0.2307484022273239
Fold 3 IBS: 0.22759963499085362
Fold 4 IBS: 0.24066411240778895
Fold 5 IBS: 0.2276593367613762
[I 2024-04-16 09:41:08,950] Trial 47 finished with value: 0.23458565267993775 and parameters: {'l1_ratio': 0.10400500229453774}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24663120271154998
Fold 2 IBS: 0.23124654308139217
Fold 3 IBS: 0.2281362955579616
Fold 4 IBS: 0.24116079549051284
Fold 5 IBS: 0.2283281334189194
[I 2024-04-16 09:41:09,309] Trial 48 finished with value: 0.23510059405206718 and parameters: {'l1_ratio': 0.061348305402541964}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.4128851571857309
Fold 2 IBS: 0.2493412080427004
Fold 3 IBS: 0.29164516043855854
Fold 4 IBS: 0.32926390714556786
Fold 5 IBS: 0.2895117668546128
[I 2024-04-16 09:41:10,435] Trial 49 finished with value: 0.3145294399334341 and parameters: {'l1_ratio': 0.547014414451201}. Best is trial 36 with value: 0.23296918740125894.

Fold 1 IBS: 0.359597288278231
Fold 2 IBS: 0.22881426494849127
Fold 3 IBS: 0.22534141900236643
Fold 4 IBS: 0.23886385969922194
Fold 5 IBS: 0.2250492336162952
[I 2024-04-16 09:41:10,883] Trial 50 finished with value: 0.25553321310892113 and parameters: {'l1_ratio': 0.31297686520002327}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3456948044699285
Fold 2 IBS: 0.22916040666499773
Fold 3 IBS: 0.22578291929559793
Fold 4 IBS: 0.23916809322437887
Fold 5 IBS: 0.22552049308201147
[I 2024-04-16 09:41:11,302] Trial 51 finished with value: 0.2530653433473829 and parameters: {'l1_ratio': 0.26909622386875975}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24537751349974465
Fold 2 IBS: 0.22955916719891492
Fold 3 IBS: 0.22626414194233685
Fold 4 IBS: 0.2395295243705451
Fold 5 IBS: 0.2260601627325639
[I 2024-04-16 09:41:11,614] Trial 52 finished with value: 0.23335810194882106 and parameters: {'l1_ratio': 0.2225918073443785}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24554110832776058
Fold 2 IBS: 0.2297798594230324
Fold 3 IBS: 0.2265211138672762
Fold 4 IBS: 0.2397340180302648
Fold 5 IBS: 0.22635777559608514
[I 2024-04-16 09:41:11,962] Trial 53 finished with value: 0.2335867750488838 and parameters: {'l1_ratio': 0.19848510263845484}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24510620365445882
Fold 2 IBS: 0.22919769295161174
Fold 3 IBS: 0.2258290272246596
Fold 4 IBS: 0.23920141703019016
Fold 5 IBS: 0.22557108363025338
[I 2024-04-16 09:41:12,256] Trial 54 finished with value: 0.2329810848982347 and parameters: {'l1_ratio': 0.2645740981864764}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.39421295887667185
Fold 2 IBS: 0.23904259569320668
Fold 3 IBS: 0.22391957441592397
Fold 4 IBS: 0.23808428362021003
Fold 5 IBS: 0.2811484894764419
[I 2024-04-16 09:41:12,968] Trial 55 finished with value: 0.27528158041649087 and parameters: {'l1_ratio': 0.4563189268255236}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.36156445603509163
Fold 2 IBS: 0.22876308075179888
Fold 3 IBS: 0.2252737449757001
Fold 4 IBS: 0.23881970853808746
Fold 5 IBS: 0.22497926639509577
[I 2024-04-16 09:41:13,386] Trial 56 finished with value: 0.25588005133915476 and parameters: {'l1_ratio': 0.31977601425555935}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.38048422417149
Fold 2 IBS: 0.22824351774095727
Fold 3 IBS: 0.22453066577779468
Fold 4 IBS: 0.2383857267756021
Fold 5 IBS: 0.27406100348108
[I 2024-04-16 09:41:14,016] Trial 57 finished with value: 0.2691410275893848 and parameters: {'l1_ratio': 0.39402869585964473}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24590604122319298
Fold 2 IBS: 0.23027476628790206
Fold 3 IBS: 0.2270801155212165
Fold 4 IBS: 0.2402030361091609
Fold 5 IBS: 0.2270234300765989
[I 2024-04-16 09:41:14,368] Trial 58 finished with value: 0.2340974778436143 and parameters: {'l1_ratio': 0.14809457918275226}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24672732656559795
Fold 2 IBS: 0.2313726935056458
Fold 3 IBS: 0.2282712211624802
Fold 4 IBS: 0.24128838629524885
Fold 5 IBS: 0.22849761973466273
[I 2024-04-16 09:41:14,769] Trial 59 finished with value: 0.2352314494527271 and parameters: {'l1_ratio': 0.05108476720607816}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3460386144812851
Fold 2 IBS: 0.2291518207623001
Fold 3 IBS: 0.22577226913320972
Fold 4 IBS: 0.23916043426467545
Fold 5 IBS: 0.22550883932841542
[I 2024-04-16 09:41:15,292] Trial 60 finished with value: 0.25312639559397715 and parameters: {'l1_ratio': 0.27014289931267665}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2452451663294399
Fold 2 IBS: 0.2293819410360443
Fold 3 IBS: 0.22605329170133756
Fold 4 IBS: 0.2393675446383232
Fold 5 IBS: 0.2258206620847833
[I 2024-04-16 09:41:15,674] Trial 61 finished with value: 0.23317372115798568 and parameters: {'l1_ratio': 0.24276696182893537}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2455342102577796
Fold 2 IBS: 0.22977052773139603
Fold 3 IBS: 0.2265103595176902
Fold 4 IBS: 0.23972530952500148
Fold 5 IBS: 0.22634520347896567
[I 2024-04-16 09:41:16,044] Trial 62 finished with value: 0.23357712210216658 and parameters: {'l1_ratio': 0.19948271034579906}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.37291000071166025
Fold 2 IBS: 0.2284567310914262
Fold 3 IBS: 0.22485076701435902
Fold 4 IBS: 0.23856049027153092
Fold 5 IBS: 0.2701158479471389
[I 2024-04-16 09:41:16,633] Trial 63 finished with value: 0.26697876740722304 and parameters: {'l1_ratio': 0.36233517707183305}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.35932488319410555
Fold 2 IBS: 0.22882158064549626
Fold 3 IBS: 0.22535103576037505
Fold 4 IBS: 0.2388701886813885
Fold 5 IBS: 0.22505922740384313
[I 2024-04-16 09:41:17,132] Trial 64 finished with value: 0.2554853831370417 and parameters: {'l1_ratio': 0.31201194298947293}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24517197195012944
Fold 2 IBS: 0.22928462264862984
Fold 3 IBS: 0.2259355348391709
Fold 4 IBS: 0.2392794995611238
Fold 5 IBS: 0.22568891874958888
[I 2024-04-16 09:41:17,523] Trial 65 finished with value: 0.23307210954972857 and parameters: {'l1_ratio': 0.25417557141240354}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24581882494455698
Fold 2 IBS: 0.23015644725265
Fold 3 IBS: 0.22694826941261695
Fold 4 IBS: 0.24008966819618482
Fold 5 IBS: 0.22686445066574334
[I 2024-04-16 09:41:17,825] Trial 66 finished with value: 0.2339755320943504 and parameters: {'l1_ratio': 0.1597124379499669}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3478382663304834
Fold 2 IBS: 0.22910853154696328
Fold 3 IBS: 0.22571835992373007
Fold 4 IBS: 0.23912190227486807
Fold 5 IBS: 0.22545005720828973
[I 2024-04-16 09:41:18,341] Trial 67 finished with value: 0.25344742345686694 and parameters: {'l1_ratio': 0.27545111606147815}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24545286899051844
Fold 2 IBS: 0.22966064573975625
Fold 3 IBS: 0.22638300885850493
Fold 4 IBS: 0.2396231625582056
Fold 5 IBS: 0.22619708826176987
[I 2024-04-16 09:41:18,850] Trial 68 finished with value: 0.233463354881751 and parameters: {'l1_ratio': 0.21137203538629853}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24615025595594725
Fold 2 IBS: 0.23060507084918333
Fold 3 IBS: 0.2274436111648864
Fold 4 IBS: 0.24052339123669778
Fold 5 IBS: 0.2274669461257357
[I 2024-04-16 09:41:19,393] Trial 69 finished with value: 0.23443785506649012 and parameters: {'l1_ratio': 0.11695911803611572}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.382440698964343
Fold 2 IBS: 0.22818476796530834
Fold 3 IBS: 0.22444027852643686
Fold 4 IBS: 0.23833848171876515
Fold 5 IBS: 0.2751451013844559
[I 2024-04-16 09:41:20,191] Trial 70 finished with value: 0.26970986571186184 and parameters: {'l1_ratio': 0.40309171142248057}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24515204012142755
Fold 2 IBS: 0.22925822298444554
Fold 3 IBS: 0.22590332627471613
Fold 4 IBS: 0.23925572947729015
Fold 5 IBS: 0.22565314941107747
[I 2024-04-16 09:41:20,751] Trial 71 finished with value: 0.23304449365379135 and parameters: {'l1_ratio': 0.2573124266130852}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2452220761428411
Fold 2 IBS: 0.22935118050260175
Fold 3 IBS: 0.2260162319889251
Fold 4 IBS: 0.2393396444855018
Fold 5 IBS: 0.2257790392791256
[I 2024-04-16 09:41:21,079] Trial 72 finished with value: 0.2331416344797991 and parameters: {'l1_ratio': 0.24634700971567852}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.35784915970750336
Fold 2 IBS: 0.22885926736995424
Fold 3 IBS: 0.22540036193978324
Fold 4 IBS: 0.238902864599383
Fold 5 IBS: 0.22511068507121257
[I 2024-04-16 09:41:21,548] Trial 73 finished with value: 0.2552244677375673 and parameters: {'l1_ratio': 0.3070679908842265}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.36489821351239077
Fold 2 IBS: 0.22867636172916828
Fold 3 IBS: 0.22515745290376113
Fold 4 IBS: 0.2387454347674661
Fold 5 IBS: 0.22486053324080188
[I 2024-04-16 09:41:22,008] Trial 74 finished with value: 0.2564675992307176 and parameters: {'l1_ratio': 0.3314919402970756}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2452433756801172
Fold 2 IBS: 0.22937955366974888
Fold 3 IBS: 0.22605042062242217

Fold 4 IBS: 0.23936537695598842
Fold 5 IBS: 0.22581743228535484
[I 2024-04-16 09:41:22,352] Trial 75 finished with value: 0.23317123184272628 and parameters: {'l1_ratio': 0.24304396493315028}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24510679825771317
Fold 2 IBS: 0.22919847648396693
Fold 3 IBS: 0.2258299931062552
Fold 4 IBS: 0.23920211838691818
Fold 5 IBS: 0.22557214641828732
[I 2024-04-16 09:41:22,773] Trial 76 finished with value: 0.23298190653062817 and parameters: {'l1_ratio': 0.26447947423473034}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2454226269688125
Fold 2 IBS: 0.22961987835631992
Fold 3 IBS: 0.22633540757549128
Fold 4 IBS: 0.23958548183691267
Fold 5 IBS: 0.22614209748071773
[I 2024-04-16 09:41:23,178] Trial 77 finished with value: 0.2334210984436508 and parameters: {'l1_ratio': 0.21585120490209841}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.35428584442423244
Fold 2 IBS: 0.22894932775125407
Fold 3 IBS: 0.22551684363457206
Fold 4 IBS: 0.23898143061206753
Fold 5 IBS: 0.22523348974380344
[I 2024-04-16 09:41:23,702] Trial 78 finished with value: 0.2545933872331859 and parameters: {'l1_ratio': 0.29543170528660406}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.37406332763644645
Fold 2 IBS: 0.2284245708927372
Fold 3 IBS: 0.22480325409580118
Fold 4 IBS: 0.23853381379277908
Fold 5 IBS: 0.27072798765425743
[I 2024-04-16 09:41:24,980] Trial 79 finished with value: 0.2673105908144043 and parameters: {'l1_ratio': 0.3670004283902255}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2456935098377347
Fold 2 IBS: 0.22998638494756002
Fold 3 IBS: 0.2267569173183243
Fold 4 IBS: 0.2399280622021958
Fold 5 IBS: 0.226635790606368
[I 2024-04-16 09:41:25,524] Trial 80 finished with value: 0.23380013298243657 and parameters: {'l1_ratio': 0.17687174918631415}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24511537859361926
Fold 2 IBS: 0.22920978816334164
Fold 3 IBS: 0.22584392511142742
Fold 4 IBS: 0.23921224869094448
Fold 5 IBS: 0.22558748820663282
[I 2024-04-16 09:41:26,086] Trial 81 finished with value: 0.23299376575319314 and parameters: {'l1_ratio': 0.2631152489147424}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3683620798219742
Fold 2 IBS: 0.2285848521270689
Fold 3 IBS: 0.225032332411789
Fold 4 IBS: 0.23866780823034203
Fold 5 IBS: 0.22473496250118755
[I 2024-04-16 09:41:27,022] Trial 82 finished with value: 0.25707640701847234 and parameters: {'l1_ratio': 0.3441329217877872}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.35317353696593345
Fold 2 IBS: 0.22897816854779945
Fold 3 IBS: 0.22555375032937544
Fold 4 IBS: 0.2390067302030576
Fold 5 IBS: 0.22527276980978794
[I 2024-04-16 09:41:27,953] Trial 83 finished with value: 0.25439699117119075 and parameters: {'l1_ratio': 0.2917572333671137}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3460079028971928
Fold 2 IBS: 0.22915256899134231
Fold 3 IBS: 0.22577319780136187
Fold 4 IBS: 0.23916110149689196
Fold 5 IBS: 0.22550985497378573
[I 2024-04-16 09:41:28,611] Trial 84 finished with value: 0.25312092523211493 and parameters: {'l1_ratio': 0.27005160507294756}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2460257751750386
Fold 2 IBS: 0.23043691932352908
Fold 3 IBS: 0.22725932670358023
Fold 4 IBS: 0.240359605711799
Fold 5 IBS: 0.22724120203254325
[I 2024-04-16 09:41:29,290] Trial 85 finished with value: 0.23426456578929805 and parameters: {'l1_ratio': 0.13257827709423287}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24539956300254895
Fold 2 IBS: 0.22958882380389006
Fold 3 IBS: 0.22629901192093824
Fold 4 IBS: 0.23955682961649732
Fold 5 IBS: 0.22610019323555017
[I 2024-04-16 09:41:29,724] Trial 86 finished with value: 0.23338888431588495 and parameters: {'l1_ratio': 0.2192885227305833}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2457371375003616
Fold 2 IBS: 0.230045584384238
Fold 3 IBS: 0.2268237933986221
Fold 4 IBS: 0.23998413542443467
Fold 5 IBS: 0.2267154120693996
[I 2024-04-16 09:41:30,093] Trial 87 finished with value: 0.2338612125554112 and parameters: {'l1_ratio': 0.17083519380659234}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2455596031517072
Fold 2 IBS: 0.22980488788833592
Fold 3 IBS: 0.22654991058225968
Fold 4 IBS: 0.23975740075503946
Fold 5 IBS: 0.2263914904498742
[I 2024-04-16 09:41:30,406] Trial 88 finished with value: 0.2336126585654433 and parameters: {'l1_ratio': 0.1958186038968468}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.4312212522645113
Fold 2 IBS: 0.26556126537202684
Fold 3 IBS: 0.3079652188111018
Fold 4 IBS: 0.3300408377129964
Fold 5 IBS: 0.30412748928656036
[I 2024-04-16 09:41:31,417] Trial 89 finished with value: 0.32778321268943933 and parameters: {'l1_ratio': 0.6952678291709651}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24517528384047646
Fold 2 IBS: 0.22928901367081286
Fold 3 IBS: 0.22594088076236032
Fold 4 IBS: 0.23928345796470546
Fold 5 IBS: 0.22569486686124976
[I 2024-04-16 09:41:31,784] Trial 90 finished with value: 0.23307670061992097 and parameters: {'l1_ratio': 0.25365558658883874}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.2451503483143492
Fold 2 IBS: 0.22925598430674549
Fold 3 IBS: 0.2259005896278505
Fold 4 IBS: 0.23925371607234774
Fold 5 IBS: 0.22565011557148396
[I 2024-04-16 09:41:32,090] Trial 91 finished with value: 0.23304215077855533 and parameters: {'l1_ratio': 0.257579267932138}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3654793856744731
Fold 2 IBS: 0.2286623423128748
Fold 3 IBS: 0.22513844970275898
Fold 4 IBS: 0.23873349142614012
Fold 5 IBS: 0.22484131469652874
[I 2024-04-16 09:41:32,579] Trial 92 finished with value: 0.2565709967625551 and parameters: {'l1_ratio': 0.3334097535990777}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.42746855565464925
Fold 2 IBS: 0.26125815941493696
Fold 3 IBS: 0.30316554562365067
Fold 4 IBS: 0.32972965030638557
Fold 5 IBS: 0.29997512677025345
[I 2024-04-16 09:41:33,634] Trial 93 finished with value: 0.32431940755397515 and parameters: {'l1_ratio': 0.6547273520711029}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.35648435192016364
Fold 2 IBS: 0.22889370536553516
Fold 3 IBS: 0.2254451298490206
Fold 4 IBS: 0.23893282824542328
Fold 5 IBS: 0.22515767084940524
[I 2024-04-16 09:41:34,068] Trial 94 finished with value: 0.2549827372459096 and parameters: {'l1_ratio': 0.3025890490313581}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24511117475494573
Fold 2 IBS: 0.22920424496197006
Fold 3 IBS: 0.2258371006872062
Fold 4 IBS: 0.23920728325160012
Fold 5 IBS: 0.22557997041772446
[I 2024-04-16 09:41:34,428] Trial 95 finished with value: 0.2329879548146893 and parameters: {'l1_ratio': 0.2637833475623551}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.43477529558130484
Fold 2 IBS: 0.27105949470373597
Fold 3 IBS: 0.31976358668099736
Fold 4 IBS: 0.33172617718061687
Fold 5 IBS: 0.3102502643389018
[I 2024-04-16 09:41:35,396] Trial 96 finished with value: 0.33351496369711137 and parameters: {'l1_ratio': 0.754234381640172}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.24531972203665584
Fold 2 IBS: 0.22948160206084164
Fold 3 IBS: 0.22617239850199788
Fold 4 IBS: 0.23945837712923368
Fold 5 IBS: 0.2259554041984063
[I 2024-04-16 09:41:35,940] Trial 97 finished with value: 0.23327750078542708 and parameters: {'l1_ratio': 0.23132871214839396}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.37648341778270034
Fold 2 IBS: 0.22835526245416643
Fold 3 IBS: 0.224699943685077
Fold 4 IBS: 0.23847669639926983
Fold 5 IBS: 0.2720256128489916
[I 2024-04-16 09:41:36,695] Trial 98 finished with value: 0.268008186634041 and parameters: {'l1_ratio': 0.37719100738165035}. Best is trial 36 with value: 0.23296918740125894.
Fold 1 IBS: 0.3498401276979168
Fold 2 IBS: 0.22905988500905114
Fold 3 IBS: 0.2256573430383068
Fold 4 IBS: 0.239078770624048
Fold 5 IBS: 0.22538394875468157
[I 2024-04-16 09:41:37,406] Trial 99 finished with value: 0.2538040150248009 and parameters: {'l1_ratio': 0.2814788723164725}. Best is trial 36 with value: 0.23296918740125894.


* Best trial for IBS:
 FrozenTrial(number=36, state=TrialState.COMPLETE, values=[0.23296918740125894], datetime_start=datetime.datetime(2024, 4, 16, 9, 41, 1, 551754), datetime_complete=datetime.datetime(2024, 4, 16, 9, 41, 1, 991407), params={'l1_ratio': 0.26594584591028053}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=36, value=None)


* Best Score for IBS:
 0.23296918740125894

In [50]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [51]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.625
train_ibs:  0.233

#### Test

In [52]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [53]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.22692876841884668)

test_cindex : 0.601

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.26594584591028053)

test_ibs:  0.225

In [54]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [55]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:41:37,953] A new study created in memory with name: no-name-6f048942-1760-47f4-962a-27c8822afc1e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 09:42:03,019] Trial 0 finished with value: 0.6887600217317204 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 09:42:08,578] Trial 1 finished with value: 0.6166380389955435 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.5622317596566524
[I 2024-04-16 09:42:12,177] Trial 2 finished with value: 0.62549226208284 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:42:12,941] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:42:13,871] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6782945736434108
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5407725321888412
[I 2024-04-16 09:42:19,072] Trial 5 finished with value: 0.6152561447305711 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 09:42:38,156] Trial 6 finished with value: 0.6539398109744831 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:42:39,577] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.45493562231759654
[I 2024-04-16 09:42:45,227] Trial 8 finished with value: 0.4909871244635193 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.5064377682403434
[I 2024-04-16 09:42:49,209] Trial 9 finished with value: 0.5980152878848332 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:42:50,378] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': None, 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 09:43:04,914] Trial 11 finished with value: 0.6475023250639829 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.4182289452010553, 'max_features': None, 'min_weight_fraction_leaf': 0.14354804402122565, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:43:11,012] Trial 12 finished with value: 0.5 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 498, 'oob_score': True, 'max_samples': 0.4725186573284777, 'max_features': None, 'min_weight_fraction_leaf': 0.42991693404730996, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 09:43:18,558] Trial 13 finished with value: 0.6848917982857154 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.765021860726683, 'max_features': None, 'min_weight_fraction_leaf': 0.20108807339664914, 'warm_start': False}. Best is trial 0 with value: 0.6887600217317204.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:43:19,091] Trial 14 finished with value: 0.7054382711677689 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.7873021337102564, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17530903073562382, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6996197718631179

Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 09:43:20,073] Trial 15 finished with value: 0.7004658341847222 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.7842656506469521, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21467510010373286, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.4203187250996016
Fold 2 C-index: 0.6996124031007752
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.564638783269962
Fold 5 C-index: 0.6330472103004292
[I 2024-04-16 09:43:20,278] Trial 16 finished with value: 0.6103319349924515 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.8500299963488761, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3855568975046046, 'warm_start': True}. Best is trial 14 with value: 0.7054382711677689.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 09:43:21,020] Trial 17 finished with value: 0.7340377976614955 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.9816256083986692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10458249310616385, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 09:43:21,975] Trial 18 finished with value: 0.6851322075080448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 1, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.9862374149206906, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09529552899934571, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4900398406374502
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.759656652360515
[I 2024-04-16 09:43:22,813] Trial 19 finished with value: 0.7320533243959054 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.9945689686268684, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06762043908551946, 'warm_start': True}. Best is trial 17 with value: 0.7340377976614955.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 09:43:23,854] Trial 20 finished with value: 0.7515482174710945 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.9966629277234803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06330216271601999, 'warm_start': True}. Best is trial 20 with value: 0.7515482174710945.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 09:43:25,545] Trial 21 finished with value: 0.7546701877723911 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.9639969203071097, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07844908418015549, 'warm_start': True}. Best is trial 21 with value: 0.7546701877723911.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 09:43:27,193] Trial 22 finished with value: 0.7403034664958661 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 203, 'oob_score': True, 'max_samples': 0.8676148902287203, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.005137686000517033, 'warm_start': True}. Best is trial 21 with value: 0.7546701877723911.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 09:43:28,762] Trial 23 finished with value: 0.7563113263464099 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.869669997416516, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 23 with value: 0.7563113263464099.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 09:43:30,021] Trial 24 finished with value: 0.7606536985757444 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.8640315509178289, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07916170845060883, 'warm_start': True}. Best is trial 24 with value: 0.7606536985757444.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 09:43:31,558] Trial 25 finished with value: 0.7695297572413502 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.8486986257893505, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0009444354266301414, 'warm_start': True}. Best is trial 25 with value: 0.7695297572413502.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 09:43:33,395] Trial 26 finished with value: 0.7733467661208285 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.6912922503777362, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.030529967348810284, 'warm_start': True}. Best is trial 26 with value: 0.7733467661208285.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 09:43:35,956] Trial 27 finished with value: 0.7847011373516671 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 327, 'oob_score': True, 'max_samples': 0.6826933317259629, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04163461906296005, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 09:43:37,231] Trial 28 finished with value: 0.7626451966882999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 233, 'oob_score': True, 'max_samples': 0.6790845875969467, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1346390093951372, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 09:43:39,504] Trial 29 finished with value: 0.7524072808207946 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 321, 'oob_score': True, 'max_samples': 0.5460873722581808, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04113891562651206, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.

Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 09:43:41,278] Trial 30 finished with value: 0.6881258758502385 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.7127914138629038, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2486312042554125, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 09:43:42,565] Trial 31 finished with value: 0.7493720402953852 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.6565648650889025, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14061763521617526, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 09:43:43,806] Trial 32 finished with value: 0.7736293479949021 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 241, 'oob_score': True, 'max_samples': 0.717337635186249, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11772473625239274, 'warm_start': True}. Best is trial 27 with value: 0.7847011373516671.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.9141630901287554
[I 2024-04-16 09:43:45,301] Trial 33 finished with value: 0.811548824267636 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.7247276784505238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03689864626175683, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 09:43:46,827] Trial 34 finished with value: 0.7829876832219352 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.7198178767085571, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11161272848170577, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 09:43:47,564] Trial 35 finished with value: 0.6912157648511975 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.5459623200293144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18558790111621754, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 09:43:49,506] Trial 36 finished with value: 0.7867216702362756 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.7338075895235944, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11281996673704411, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 09:43:51,137] Trial 37 finished with value: 0.7233721608611505 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 391, 'oob_score': False, 'max_samples': 0.6085366031970421, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16279221402739244, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.9012875536480687
[I 2024-04-16 09:43:53,547] Trial 38 finished with value: 0.8026868253099897 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.810357312668476, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10446792179794386, 'warm_start': True}. Best is trial 33 with value: 0.811548824267636.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 09:43:55,068] Trial 39 finished with value: 0.8315228203891329 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.8176202594483816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05127851337193651, 'warm_start': True}. Best is trial 39 with value: 0.8315228203891329.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:43:56,021] Trial 40 finished with value: 0.7216554226637257 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 337, 'oob_score': False, 'max_samples': 0.7959580927210158, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2448692090849676, 'warm_start': True}. Best is trial 39 with value: 0.8315228203891329.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:43:57,978] Trial 41 finished with value: 0.835684247914353 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.8200079355774805, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.045375207069811796, 'warm_start': True}. Best is trial 41 with value: 0.835684247914353.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 09:44:00,000] Trial 42 finished with value: 0.8179194749278222 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 305, 'oob_score': False, 'max_samples': 0.9273819199836401, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08150372432531681, 'warm_start': True}. Best is trial 41 with value: 0.835684247914353.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 09:44:01,503] Trial 43 finished with value: 0.8427105605974863 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.9388551492979577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05266231183563491, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 09:44:02,964] Trial 44 finished with value: 0.8323518578595712 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 295, 'oob_score': False, 'max_samples': 0.9237895859439657, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05612306340851575, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.

Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 09:44:04,834] Trial 45 finished with value: 0.830280628369804 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 301, 'oob_score': False, 'max_samples': 0.9104218782867626, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06634160384660395, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.5665236051502146
[I 2024-04-16 09:44:15,082] Trial 46 finished with value: 0.6286099736434962 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 383, 'oob_score': False, 'max_samples': 0.91240298039898, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.05822950436150222, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 09:44:16,830] Trial 47 finished with value: 0.8325077461103134 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9355514430804484, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020042410067937978, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.46613545816733065
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5536480686695279
[I 2024-04-16 09:44:28,269] Trial 48 finished with value: 0.6009684370641499 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 427, 'oob_score': False, 'max_samples': 0.823645744803961, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01683251340101157, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 09:44:30,276] Trial 49 finished with value: 0.8388530534749343 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.953849061764575, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050119666582895114, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 09:44:32,103] Trial 50 finished with value: 0.7812978402712039 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 367, 'oob_score': False, 'max_samples': 0.944966006745767, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.026515719222611322, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 09:44:33,321] Trial 51 finished with value: 0.8245657831536615 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 289, 'oob_score': False, 'max_samples': 0.8927024859362178, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.050579232359344195, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 09:44:34,861] Trial 52 finished with value: 0.8163869819364665 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 351, 'oob_score': False, 'max_samples': 0.957013350431845, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08747379737293745, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:44:36,884] Trial 53 finished with value: 0.835655340129135 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.9059004636526794, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.02247138851000744, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 09:44:39,474] Trial 54 finished with value: 0.8325767347157822 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 471, 'oob_score': False, 'max_samples': 0.9045683245877397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01863439664769996, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 09:44:41,860] Trial 55 finished with value: 0.8196868832821158 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8913844051686941, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.020495893741253532, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.6197718631178707
Fold 5 C-index: 0.51931330472103
[I 2024-04-16 09:44:48,202] Trial 56 finished with value: 0.6133741946644458 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 460, 'oob_score': False, 'max_samples': 0.959688406147559, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.29669443075161894, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:44:50,538] Trial 57 finished with value: 0.8237721374995439 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 415, 'oob_score': False, 'max_samples': 0.7632151618163023, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.01760206529138649, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:44:51,850] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 455, 'oob_score': False, 'max_samples': 0.8443244755845074, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4898856186887404, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 09:44:53,087] Trial 59 finished with value: 0.6869742749526709 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 477, 'oob_score': False, 'max_samples': 0.3824901058813928, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1265828087269749, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.

Fold 1 C-index: 0.46215139442231074
Fold 2 C-index: 0.6627906976744186
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 09:45:07,746] Trial 60 finished with value: 0.6218319311565197 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 426, 'oob_score': False, 'max_samples': 0.13319246988341354, 'max_features': None, 'min_weight_fraction_leaf': 0.00239012916342312, 'warm_start': False}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.8973384030418251
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:45:14,889] Trial 61 finished with value: 0.831772489711018 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 393, 'oob_score': False, 'max_samples': 0.9227017110627658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06216084192304142, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.8953488372093024
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:45:16,442] Trial 62 finished with value: 0.8356736421434732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.8850956833773682, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03863615331212726, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 09:45:18,688] Trial 63 finished with value: 0.8371544903050128 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.8853130778846439, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.03966154422786905, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 09:45:20,234] Trial 64 finished with value: 0.8196654077526582 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.8851895285643775, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09142295253878854, 'warm_start': True}. Best is trial 43 with value: 0.8427105605974863.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9201520912547528
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 09:45:22,493] Trial 65 finished with value: 0.8474444748453905 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9873533850424658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04287202412707603, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9239543726235742
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 09:45:24,556] Trial 66 finished with value: 0.8435072299253937 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9947311488203058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04006148809996164, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.9031007751937985
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 09:45:52,907] Trial 67 finished with value: 0.8388932548617867 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 433, 'oob_score': False, 'max_samples': 0.993658937532094, 'max_features': None, 'min_weight_fraction_leaf': 0.040436540638610116, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 09:46:16,182] Trial 68 finished with value: 0.8382846820717941 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9994331375177823, 'max_features': None, 'min_weight_fraction_leaf': 0.07188437817902898, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9531914893617022
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:46:33,676] Trial 69 finished with value: 0.8375560102421463 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 438, 'oob_score': False, 'max_samples': 0.9996362451167412, 'max_features': None, 'min_weight_fraction_leaf': 0.07337892913174533, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 09:46:56,412] Trial 70 finished with value: 0.8382846820717941 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.9959834334340328, 'max_features': None, 'min_weight_fraction_leaf': 0.07185098947134154, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:47:21,208] Trial 71 finished with value: 0.836704946412359 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 442, 'oob_score': False, 'max_samples': 0.9969458887289653, 'max_features': None, 'min_weight_fraction_leaf': 0.07306969695088597, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 09:47:40,641] Trial 72 finished with value: 0.8428910714445162 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.9705326205407735, 'max_features': None, 'min_weight_fraction_leaf': 0.09726369000634277, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 09:48:00,352] Trial 73 finished with value: 0.8347457235953728 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 403, 'oob_score': False, 'max_samples': 0.9622083984206554, 'max_features': None, 'min_weight_fraction_leaf': 0.10090208352548545, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8859315589353612
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 09:48:19,410] Trial 74 finished with value: 0.8233007612427727 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 374, 'oob_score': False, 'max_samples': 0.9751692801795903, 'max_features': None, 'min_weight_fraction_leaf': 0.15896417018836817, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 09:48:30,801] Trial 75 finished with value: 0.7521199937305012 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 481, 'oob_score': False, 'max_samples': 0.9753592654341334, 'max_features': None, 'min_weight_fraction_leaf': 0.35481417747069804, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8604651162790697
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 09:49:01,169] Trial 76 finished with value: 0.8372771691473451 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 462, 'oob_score': False, 'max_samples': 0.9488752737712128, 'max_features': None, 'min_weight_fraction_leaf': 0.0946162304034015, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9055793991416309
[I 2024-04-16 09:49:25,309] Trial 77 finished with value: 0.8330617609492732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 400, 'oob_score': False, 'max_samples': 0.9819615930431459, 'max_features': None, 'min_weight_fraction_leaf': 0.12149124274513819, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 09:49:53,840] Trial 78 finished with value: 0.8366834708829012 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.9466630798470281, 'max_features': None, 'min_weight_fraction_leaf': 0.07869379995443634, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 09:50:20,457] Trial 79 finished with value: 0.8280562944412313 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.9762362824615723, 'max_features': None, 'min_weight_fraction_leaf': 0.1438601153670844, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6539923954372624
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 09:53:59,849] Trial 80 finished with value: 0.6335124296425151 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 498, 'oob_score': False, 'max_samples': 0.9981652642996742, 'max_features': None, 'min_weight_fraction_leaf': 0.05275254415427701, 'warm_start': False}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 09:54:32,155] Trial 81 finished with value: 0.8391141269510269 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 440, 'oob_score': False, 'max_samples': 0.9979035111091495, 'max_features': None, 'min_weight_fraction_leaf': 0.0684721968600143, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 09:54:59,456] Trial 82 finished with value: 0.8390591716052278 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 430, 'oob_score': False, 'max_samples': 0.9394916145721695, 'max_features': None, 'min_weight_fraction_leaf': 0.08885679941630156, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4701195219123506
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9656652360515021
[I 2024-04-16 09:55:41,084] Trial 83 finished with value: 0.8358037897038839 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 405, 'oob_score': False, 'max_samples': 0.9369494626132739, 'max_features': None, 'min_weight_fraction_leaf': 0.03228804063616034, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.948936170212766
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 09:56:12,002] Trial 84 finished with value: 0.8413843291575205 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'max_samples': 0.9632963350821008, 'max_features': None, 'min_weight_fraction_leaf': 0.08645608734851228, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9227467811158798
[I 2024-04-16 09:56:31,710] Trial 85 finished with value: 0.8340869044915674 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 424, 'oob_score': False, 'max_samples': 0.8445466446433496, 'max_features': None, 'min_weight_fraction_leaf': 0.09405144363135096, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9276595744680851
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9399141630901288
[I 2024-04-16 09:56:52,686] Trial 86 finished with value: 0.8372383598562632 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 350, 'oob_score': False, 'max_samples': 0.9593020592230249, 'max_features': None, 'min_weight_fraction_leaf': 0.062345011421902685, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.9184549356223176
[I 2024-04-16 09:57:18,215] Trial 87 finished with value: 0.830877610701941 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 469, 'oob_score': False, 'max_samples': 0.9299549183842758, 'max_features': None, 'min_weight_fraction_leaf': 0.10663286795016572, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.8935361216730038
Fold 5 C-index: 0.927038626609442
[I 2024-04-16 09:57:40,231] Trial 88 finished with value: 0.8357167430437187 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.8678400525803166, 'max_features': None, 'min_weight_fraction_leaf': 0.08562946203667166, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 09:57:49,137] Trial 89 finished with value: 0.7461891440711376 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.9666623619578044, 'max_features': None, 'min_weight_fraction_leaf': 0.13289751230356953, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.

Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 09:58:08,563] Trial 90 finished with value: 0.7721635506485307 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 361, 'oob_score': False, 'max_samples': 0.9143479302159204, 'max_features': None, 'min_weight_fraction_leaf': 0.04481644229535587, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 09:58:50,690] Trial 91 finished with value: 0.8446737781674148 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.9488468959302472, 'max_features': None, 'min_weight_fraction_leaf': 0.060774497145647054, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.8992248062015504
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 09:59:34,583] Trial 92 finished with value: 0.8405269611800452 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 423, 'oob_score': False, 'max_samples': 0.94014101252894, 'max_features': None, 'min_weight_fraction_leaf': 0.0548113701472033, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.4342629482071713
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.9527896995708155
[I 2024-04-16 10:00:02,725] Trial 93 finished with value: 0.8120089069227732 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 485, 'oob_score': False, 'max_samples': 0.5075426217211035, 'max_features': None, 'min_weight_fraction_leaf': 0.0319777462255082, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.41434262948207173
Fold 2 C-index: 0.9108527131782945
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.944206008583691
[I 2024-04-16 10:01:04,637] Trial 94 finished with value: 0.8187892581947704 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.9227811582027634, 'max_features': None, 'min_weight_fraction_leaf': 0.00822735070118076, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9446808510638298
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9484978540772532
[I 2024-04-16 10:01:37,792] Trial 95 finished with value: 0.8407509903501437 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9752306812643342, 'max_features': None, 'min_weight_fraction_leaf': 0.06347739998417412, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 10:01:44,884] Trial 96 finished with value: 0.797411102196824 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 397, 'oob_score': False, 'max_samples': 0.9383924139197609, 'max_features': None, 'min_weight_fraction_leaf': 0.06205878427847117, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9404255319148936
Fold 4 C-index: 0.9049429657794676
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 10:02:13,222] Trial 97 finished with value: 0.8413305019197933 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 411, 'oob_score': False, 'max_samples': 0.9752654941017508, 'max_features': None, 'min_weight_fraction_leaf': 0.08608757981910961, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 10:03:41,244] Trial 98 finished with value: 0.6673031775286545 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 407, 'oob_score': False, 'max_samples': 0.9756872825157317, 'max_features': None, 'min_weight_fraction_leaf': 0.11068049094138749, 'warm_start': False}. Best is trial 65 with value: 0.8474444748453905.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8595744680851064

[I 2024-04-16 10:03:52,325] A new study created in memory with name: no-name-e1868ad3-31fb-4990-8488-d6670baa63c3

Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 10:03:52,298] Trial 99 finished with value: 0.8113937137105396 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 467, 'oob_score': False, 'max_samples': 0.9056858572892185, 'max_features': None, 'min_weight_fraction_leaf': 0.20123851264921916, 'warm_start': True}. Best is trial 65 with value: 0.8474444748453905.


* Best trial for C-index:
 FrozenTrial(number=65, state=TrialState.COMPLETE, values=[0.8474444748453905], datetime_start=datetime.datetime(2024, 4, 16, 9, 45, 20, 240294), datetime_complete=datetime.datetime(2024, 4, 16, 9, 45, 22, 492178), params={'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 441, 'oob_score': False, 'max_samples': 0.9873533850424658, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.04287202412707603, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=65, value=None)


* Best Score for C-index:
 0.8474444748453905

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23042752124267438
Fold 2 IBS: 0.18839054215405548
Fold 3 IBS: 0.2293899661136923
Fold 4 IBS: 0.2169146460429805
Fold 5 IBS: 0.2142567055646754
[I 2024-04-16 10:04:16,379] Trial 0 finished with value: 0.21587587622361562 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2508146115058545
Fold 2 IBS: 0.20305081069239997
Fold 3 IBS: 0.2125601518843403
Fold 4 IBS: 0.23802356391790935
Fold 5 IBS: 0.24031357707661585
[I 2024-04-16 10:04:17,540] Trial 1 finished with value: 0.228952543015424 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-16 10:04:18,177] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-16 10:04:20,590] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-16 10:04:23,210] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2555512810814963
Fold 2 IBS: 0.20324441473182778
Fold 3 IBS: 0.20138344229687621
Fold 4 IBS: 0.24823005681755586
Fold 5 IBS: 0.23986172601998265
[I 2024-04-16 10:04:27,818] Trial 5 finished with value: 0.22965418418954772 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22937230878310585
Fold 2 IBS: 0.19783748265063947
Fold 3 IBS: 0.24758962979639584
Fold 4 IBS: 0.2293592142258337
Fold 5 IBS: 0.21843413307330445
[I 2024-04-16 10:04:41,152] Trial 6 finished with value: 0.22451855370585588 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24645459314284615
Fold 2 IBS: 0.2284327655476503
Fold 3 IBS: 0.2269204476718718
Fold 4 IBS: 0.24193873418388995
Fold 5 IBS: 0.23242562407841813
[I 2024-04-16 10:04:44,147] Trial 7 finished with value: 0.23523443292493526 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-16 10:04:48,884] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.2514315797339687
Fold 2 IBS: 0.20486001394714717
Fold 3 IBS: 0.21413246491582993
Fold 4 IBS: 0.2488036649239709
Fold 5 IBS: 0.23916777605650416
[I 2024-04-16 10:04:50,174] Trial 9 finished with value: 0.23167909991548416 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-16 10:04:56,633] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27033688725897076}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22505044010769915
Fold 2 IBS: 0.19169873975025706
Fold 3 IBS: 0.24355652039688175
Fold 4 IBS: 0.22456118368774855
Fold 5 IBS: 0.2199364923604279
[I 2024-04-16 10:05:18,872] Trial 11 finished with value: 0.2209606752606029 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 345, 'oob_score': False, 'max_samples': 0.9485893528798968, 'max_features': None, 'min_weight_fraction_leaf': 0.34713111632234195}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.22641537530591904
Fold 2 IBS: 0.1856122448029484
Fold 3 IBS: 0.23970956613213612
Fold 4 IBS: 0.22689978521066698
Fold 5 IBS: 0.21984826293499948
[I 2024-04-16 10:05:44,970] Trial 12 finished with value: 0.219697046877334 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.99460329717513, 'max_features': None, 'min_weight_fraction_leaf': 0.3273519300270286}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.24906566803157934
Fold 2 IBS: 0.1844522654087228
Fold 3 IBS: 0.22247964562583175
Fold 4 IBS: 0.2200365797335415
Fold 5 IBS: 0.21390292106525644
[I 2024-04-16 10:06:28,249] Trial 13 finished with value: 0.21798741597298638 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.7795899048785642, 'max_features': None, 'min_weight_fraction_leaf': 0.16534086975223722}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.25156447987348923
Fold 2 IBS: 0.20970424521303116
Fold 3 IBS: 0.20875877537891965
Fold 4 IBS: 0.24770150304574612
Fold 5 IBS: 0.24420033286537043
[I 2024-04-16 10:06:33,185] Trial 14 finished with value: 0.23238586727531133 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 425, 'oob_score': False, 'max_samples': 0.7714173351535261, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1619227173876303}. Best is trial 0 with value: 0.21587587622361562.
Fold 1 IBS: 0.26683527729810225
Fold 2 IBS: 0.20435168056118677
Fold 3 IBS: 0.21099863333114646
Fold 4 IBS: 0.23944579683045827
Fold 5 IBS: 0.2220476423219148
[I 2024-04-16 10:07:10,103] Trial 15 finished with value: 0.22873580606856173 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 1, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.7857370506104712, 'max_features': None, 'min_weight_fraction_leaf': 9.381036713218549e-05}. Best is trial 0 with value: 0.21587587622361562.

Fold 1 IBS: 0.22884349745474517
Fold 2 IBS: 0.18834811375380564
Fold 3 IBS: 0.2312043647935247
Fold 4 IBS: 0.21471543299997775
Fold 5 IBS: 0.21368545250258145
[I 2024-04-16 10:07:28,307] Trial 16 finished with value: 0.21535937230092697 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.7160627225800851, 'max_features': None, 'min_weight_fraction_leaf': 0.2245547459670535}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.23115054536847185
Fold 2 IBS: 0.19232972177370425
Fold 3 IBS: 0.2306960604186981
Fold 4 IBS: 0.2282864781982014
Fold 5 IBS: 0.22100826632463474
[I 2024-04-16 10:07:42,351] Trial 17 finished with value: 0.22069421441674208 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.6871243940599472, 'max_features': None, 'min_weight_fraction_leaf': 0.2285855344271941}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.2547124645596499
Fold 2 IBS: 0.21239240552877675
Fold 3 IBS: 0.20907384621625053
Fold 4 IBS: 0.2552638099119818
Fold 5 IBS: 0.239861875460518
[I 2024-04-16 10:07:44,915] Trial 18 finished with value: 0.2342608803354354 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.3978019017721025, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08924573043815814}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.25153637815211566
Fold 2 IBS: 0.2130643844494364
Fold 3 IBS: 0.21653921536390197
Fold 4 IBS: 0.2515132161134549
Fold 5 IBS: 0.24551267392915996
[I 2024-04-16 10:07:46,752] Trial 19 finished with value: 0.2356331736016138 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.6061595584833309, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22791611456767383}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.24668838755067432
Fold 2 IBS: 0.2323223694774956
Fold 3 IBS: 0.22952287763530818
Fold 4 IBS: 0.24145505906170697
Fold 5 IBS: 0.23037434075470525
[I 2024-04-16 10:07:49,415] Trial 20 finished with value: 0.23607260689597806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 262, 'oob_score': False, 'max_samples': 0.4458729287336371, 'max_features': None, 'min_weight_fraction_leaf': 0.3007687013181908}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.25768407946447835
Fold 2 IBS: 0.18741993444051966
Fold 3 IBS: 0.21990359018458633
Fold 4 IBS: 0.22758690645744453
Fold 5 IBS: 0.2122845055529156
[I 2024-04-16 10:08:39,421] Trial 21 finished with value: 0.2209758032199889 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 399, 'oob_score': False, 'max_samples': 0.7968542041631069, 'max_features': None, 'min_weight_fraction_leaf': 0.14088312030047453}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.23994195701389592
Fold 2 IBS: 0.1880263620809246
Fold 3 IBS: 0.22200106857343152
Fold 4 IBS: 0.2333432594536798
Fold 5 IBS: 0.22313781821533352
[I 2024-04-16 10:09:13,409] Trial 22 finished with value: 0.22129009306745306 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 450, 'oob_score': False, 'max_samples': 0.7333978805634859, 'max_features': None, 'min_weight_fraction_leaf': 0.2049420412000723}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.2625956010796006
Fold 2 IBS: 0.1928923730378316
Fold 3 IBS: 0.21796884204077038
Fold 4 IBS: 0.23320993234287188
Fold 5 IBS: 0.21762131459681405
[I 2024-04-16 10:09:54,338] Trial 23 finished with value: 0.22485761261957773 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 330, 'oob_score': False, 'max_samples': 0.8558877999962695, 'max_features': None, 'min_weight_fraction_leaf': 0.12237281401289234}. Best is trial 16 with value: 0.21535937230092697.
Fold 1 IBS: 0.22276602783377017
Fold 2 IBS: 0.18341833821581766
Fold 3 IBS: 0.23515178773766685
Fold 4 IBS: 0.2158844598266772
Fold 5 IBS: 0.214498386011388
[I 2024-04-16 10:10:25,625] Trial 24 finished with value: 0.214343799925064 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 14, 'n_estimators': 389, 'oob_score': False, 'max_samples': 0.8436689400574193, 'max_features': None, 'min_weight_fraction_leaf': 0.244242289743401}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2232033563663133
Fold 2 IBS: 0.18483011757148574
Fold 3 IBS: 0.2387458608845854
Fold 4 IBS: 0.21469399502353012
Fold 5 IBS: 0.21400836240416607
[I 2024-04-16 10:10:55,115] Trial 25 finished with value: 0.21509633845001613 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 385, 'oob_score': False, 'max_samples': 0.8781861106771913, 'max_features': None, 'min_weight_fraction_leaf': 0.25578130205333305}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2243469078613741
Fold 2 IBS: 0.18503556791629602
Fold 3 IBS: 0.239615094137992
Fold 4 IBS: 0.2128207476339741
Fold 5 IBS: 0.21343897546943888
[I 2024-04-16 10:11:32,407] Trial 26 finished with value: 0.21505145860381503 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.8790368112638932, 'max_features': None, 'min_weight_fraction_leaf': 0.25879667379312365}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.24994978911265142
Fold 2 IBS: 0.20970593191211698
Fold 3 IBS: 0.21190261680704528
Fold 4 IBS: 0.24890297891386573
Fold 5 IBS: 0.24082074617028817
[I 2024-04-16 10:11:38,490] Trial 27 finished with value: 0.2322564125831935 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 463, 'oob_score': True, 'max_samples': 0.8959637112797967, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2611199851941091}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2502142619626781
Fold 2 IBS: 0.2062960293780691
Fold 3 IBS: 0.20914331859862303
Fold 4 IBS: 0.24450110394780006
Fold 5 IBS: 0.23744852143309458
[I 2024-04-16 10:11:45,133] Trial 28 finished with value: 0.22952064706405295 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.957086450216675, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3146636471285875}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2316496219569113
Fold 2 IBS: 0.20199211986849258
Fold 3 IBS: 0.25252580475553593
Fold 4 IBS: 0.23451794093985362
Fold 5 IBS: 0.22256455030066677
[I 2024-04-16 10:12:05,026] Trial 29 finished with value: 0.22865000756429205 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 376, 'oob_score': True, 'max_samples': 0.8498266742400898, 'max_features': None, 'min_weight_fraction_leaf': 0.37494346942158263}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.2293501237092553
Fold 2 IBS: 0.1835103223875015
Fold 3 IBS: 0.23279207931646337
Fold 4 IBS: 0.21732583133116853
Fold 5 IBS: 0.2103061227472283
[I 2024-04-16 10:12:33,463] Trial 30 finished with value: 0.2146568958983234 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 301, 'oob_score': True, 'max_samples': 0.9975403100242013, 'max_features': None, 'min_weight_fraction_leaf': 0.2599744768668571}. Best is trial 24 with value: 0.214343799925064.
Fold 1 IBS: 0.22543889947738152
Fold 2 IBS: 0.1845289972063156
Fold 3 IBS: 0.23174838796536676
Fold 4 IBS: 0.2144936679622966
Fold 5 IBS: 0.21144518832087167
[I 2024-04-16 10:13:03,042] Trial 31 finished with value: 0.21353102818644648 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 303, 'oob_score': True, 'max_samples': 0.9626750941879966, 'max_features': None, 'min_weight_fraction_leaf': 0.26115274999390314}. Best is trial 31 with value: 0.21353102818644648.

Fold 1 IBS: 0.22149490022552124
Fold 2 IBS: 0.18466865634717505
Fold 3 IBS: 0.23548539432841317
Fold 4 IBS: 0.2113697424267566
Fold 5 IBS: 0.2119677581906565
[I 2024-04-16 10:13:33,360] Trial 32 finished with value: 0.2129972903037045 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.9673759674409311, 'max_features': None, 'min_weight_fraction_leaf': 0.27417727195073677}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.2567229873354098
Fold 2 IBS: 0.18854079292396503
Fold 3 IBS: 0.2249457788925835
Fold 4 IBS: 0.22508129343804778
Fold 5 IBS: 0.21386415001842546
[I 2024-04-16 10:14:08,601] Trial 33 finished with value: 0.2218310005216863 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 304, 'oob_score': True, 'max_samples': 0.9964442664551478, 'max_features': None, 'min_weight_fraction_leaf': 0.1855920796843306}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22302338864627833
Fold 2 IBS: 0.18329215715895394
Fold 3 IBS: 0.23579844813453207
Fold 4 IBS: 0.21461565443498337
Fold 5 IBS: 0.21550729328840212
[I 2024-04-16 10:14:25,411] Trial 34 finished with value: 0.21444738833262997 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 234, 'oob_score': True, 'max_samples': 0.9279710918176601, 'max_features': None, 'min_weight_fraction_leaf': 0.2867300145495075}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24931299863626957
Fold 2 IBS: 0.21399812944525917
Fold 3 IBS: 0.21838058951641673
Fold 4 IBS: 0.24989391243794642
Fold 5 IBS: 0.23922813868039394
[I 2024-04-16 10:14:29,455] Trial 35 finished with value: 0.23416275374325718 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 18, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9536728448516014, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3909359479764509}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23117720087911678
Fold 2 IBS: 0.20908991901846688
Fold 3 IBS: 0.2539101731203305
Fold 4 IBS: 0.24099766821400376
Fold 5 IBS: 0.2293088693612524
[I 2024-04-16 10:14:38,765] Trial 36 finished with value: 0.23289676611863408 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 20, 'n_estimators': 170, 'oob_score': True, 'max_samples': 0.9283967702859293, 'max_features': None, 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.2523224496304161
Fold 2 IBS: 0.21043432067224094
Fold 3 IBS: 0.2112721950288639
Fold 4 IBS: 0.24870441754756062
Fold 5 IBS: 0.23989403542441912
[I 2024-04-16 10:14:42,461] Trial 37 finished with value: 0.23252548366070017 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 13, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.8243905227087784, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2901382904665285}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24687665709365722
Fold 2 IBS: 0.23216047658482733
Fold 3 IBS: 0.22943470935389718
Fold 4 IBS: 0.24151119067690444
Fold 5 IBS: 0.23038863917402108
[I 2024-04-16 10:14:46,220] Trial 38 finished with value: 0.23607433457666147 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 266, 'oob_score': True, 'max_samples': 0.6365393674376216, 'max_features': None, 'min_weight_fraction_leaf': 0.33188225283962414}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23138450633211288
Fold 2 IBS: 0.2012849705319908
Fold 3 IBS: 0.24592903460990817
Fold 4 IBS: 0.2321634541727149
Fold 5 IBS: 0.21646893363939826
[I 2024-04-16 10:14:56,596] Trial 39 finished with value: 0.225446179857225 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 178, 'oob_score': True, 'max_samples': 0.9213772884619962, 'max_features': None, 'min_weight_fraction_leaf': 0.3814300944091633}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.24772435188079012
Fold 2 IBS: 0.23218742086626878
Fold 3 IBS: 0.23060758736791892
Fold 4 IBS: 0.24175508770731288
Fold 5 IBS: 0.23204474443418183
[I 2024-04-16 10:14:57,104] Trial 40 finished with value: 0.2368638384512945 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.16382436256125943, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28669301454652507}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.23272078581366948
Fold 2 IBS: 0.18387215718777747
Fold 3 IBS: 0.2312356985823202
Fold 4 IBS: 0.21835974803092903
Fold 5 IBS: 0.2118508415801541
[I 2024-04-16 10:15:31,962] Trial 41 finished with value: 0.21560784623897006 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 309, 'oob_score': True, 'max_samples': 0.9968428823752321, 'max_features': None, 'min_weight_fraction_leaf': 0.24475563110472928}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22762467376302845
Fold 2 IBS: 0.19292454667228245
Fold 3 IBS: 0.24232575060581318
Fold 4 IBS: 0.22605305899139677
Fold 5 IBS: 0.2183712075716998
[I 2024-04-16 10:15:48,463] Trial 42 finished with value: 0.2214598475208441 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.8330638381230538, 'max_features': None, 'min_weight_fraction_leaf': 0.30703156935090925}. Best is trial 32 with value: 0.2129972903037045.
Fold 1 IBS: 0.22060072941583395
Fold 2 IBS: 0.1839788116163854
Fold 3 IBS: 0.2354589586695753
Fold 4 IBS: 0.2103428787902223
Fold 5 IBS: 0.21157714114706494
[I 2024-04-16 10:16:09,863] Trial 43 finished with value: 0.2123917039278164 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.9591424672361251, 'max_features': None, 'min_weight_fraction_leaf': 0.2785655043553118}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2256927624531365
Fold 2 IBS: 0.19403171073899753
Fold 3 IBS: 0.24180178869616473
Fold 4 IBS: 0.22271987208962252
Fold 5 IBS: 0.21926725742571193
[I 2024-04-16 10:16:25,186] Trial 44 finished with value: 0.22070267828072665 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.9395792767074951, 'max_features': None, 'min_weight_fraction_leaf': 0.35489094778373753}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2457081276764462
Fold 2 IBS: 0.2057089461106387
Fold 3 IBS: 0.2112006429304633
Fold 4 IBS: 0.2504179456089246
Fold 5 IBS: 0.2381093166637389
[I 2024-04-16 10:16:27,523] Trial 45 finished with value: 0.23022899579804235 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.8989588401372685, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.28207190827118556}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.246544080673752
Fold 2 IBS: 0.23213980573826468
Fold 3 IBS: 0.2295309513645431
Fold 4 IBS: 0.24164345141610383
Fold 5 IBS: 0.23038069732103597
[I 2024-04-16 10:16:30,640] Trial 46 finished with value: 0.23604779730273995 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 245, 'oob_score': True, 'max_samples': 0.9587168953650592, 'max_features': None, 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24900574598687916
Fold 2 IBS: 0.200322207738425
Fold 3 IBS: 0.20666582272059178
Fold 4 IBS: 0.24160407963613872
Fold 5 IBS: 0.23964332065507346
[I 2024-04-16 10:16:35,005] Trial 47 finished with value: 0.22744823534742165 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 193, 'oob_score': True, 'max_samples': 0.8252659010917025, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18709868233605237}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.23233061602902896
Fold 2 IBS: 0.20470776398952695
Fold 3 IBS: 0.24473722549758978
Fold 4 IBS: 0.23554082329183057
Fold 5 IBS: 0.22266798632628182
[I 2024-04-16 10:16:49,601] Trial 48 finished with value: 0.22799688302685164 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.7486071388218823, 'max_features': None, 'min_weight_fraction_leaf': 0.3316489763494004}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22140751210407167
Fold 2 IBS: 0.18446093935852728
Fold 3 IBS: 0.23819663142832964
Fold 4 IBS: 0.21304733351095642
Fold 5 IBS: 0.21354093321412873
[I 2024-04-16 10:17:15,331] Trial 49 finished with value: 0.21413066992320276 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.9104681524496127, 'max_features': None, 'min_weight_fraction_leaf': 0.2085463208364724}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22233291067700658
Fold 2 IBS: 0.18478464545596854
Fold 3 IBS: 0.23971913759043886
Fold 4 IBS: 0.21278768542579282
Fold 5 IBS: 0.21478540299561258
[I 2024-04-16 10:17:40,182] Trial 50 finished with value: 0.2148819564289639 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.8824600753169473, 'max_features': None, 'min_weight_fraction_leaf': 0.21462027388465296}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22734559235093124
Fold 2 IBS: 0.18318936929294466
Fold 3 IBS: 0.23297167248730816
Fold 4 IBS: 0.21245702972369868
Fold 5 IBS: 0.21111254387628536
[I 2024-04-16 10:18:10,935] Trial 51 finished with value: 0.21341524154623365 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.9625411717608587, 'max_features': None, 'min_weight_fraction_leaf': 0.23293844782753054}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22346864077437148
Fold 2 IBS: 0.18390840845858739
Fold 3 IBS: 0.23332464818299495
Fold 4 IBS: 0.2131988499365954
Fold 5 IBS: 0.21069690375604289
[I 2024-04-16 10:18:40,925] Trial 52 finished with value: 0.21291949022171847 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 352, 'oob_score': True, 'max_samples': 0.9641055300734946, 'max_features': None, 'min_weight_fraction_leaf': 0.23607641839390603}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22838038692070342
Fold 2 IBS: 0.18230534132767368
Fold 3 IBS: 0.2331843783263773
Fold 4 IBS: 0.21294291300198875
Fold 5 IBS: 0.21054265660575297
[I 2024-04-16 10:19:11,192] Trial 53 finished with value: 0.21347113523649922 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.9631487042826314, 'max_features': None, 'min_weight_fraction_leaf': 0.17637754776024273}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2284275692142271
Fold 2 IBS: 0.18246107795839966
Fold 3 IBS: 0.23265587552703618
Fold 4 IBS: 0.2133213439680979
Fold 5 IBS: 0.21041220939694896
[I 2024-04-16 10:19:40,525] Trial 54 finished with value: 0.21345561521294196 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 359, 'oob_score': True, 'max_samples': 0.967029635289036, 'max_features': None, 'min_weight_fraction_leaf': 0.13017229949607742}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24655826225731184
Fold 2 IBS: 0.23223212769483395
Fold 3 IBS: 0.2299109075503006
Fold 4 IBS: 0.24125502336117552
Fold 5 IBS: 0.23025881880809368
[I 2024-04-16 10:19:44,743] Trial 55 finished with value: 0.23604302793434312 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 351, 'oob_score': True, 'max_samples': 0.26065411177594827, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13302957117693476}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2288773906468273
Fold 2 IBS: 0.182557427331127
Fold 3 IBS: 0.23247262815573858
Fold 4 IBS: 0.21385954181177394
Fold 5 IBS: 0.2108105644361973
[I 2024-04-16 10:20:16,716] Trial 56 finished with value: 0.2137155104763328 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.975784426896677, 'max_features': None, 'min_weight_fraction_leaf': 0.10165017984714692}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2517864102395247
Fold 2 IBS: 0.21311790899482444
Fold 3 IBS: 0.21465108435997157
Fold 4 IBS: 0.25309517297336526
Fold 5 IBS: 0.2417203119244569
[I 2024-04-16 10:20:21,466] Trial 57 finished with value: 0.23487417769842858 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 326, 'oob_score': True, 'max_samples': 0.47523615475756226, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0456877909412422}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2243353112407589
Fold 2 IBS: 0.18266218635612108
Fold 3 IBS: 0.23393999495208184
Fold 4 IBS: 0.2149406342270133
Fold 5 IBS: 0.21045670202420302
[I 2024-04-16 10:20:59,161] Trial 58 finished with value: 0.21326696576003562 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.9713216893041037, 'max_features': None, 'min_weight_fraction_leaf': 0.17261347912606032}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24689331510957085
Fold 2 IBS: 0.20349936746264044
Fold 3 IBS: 0.20741536012216769
Fold 4 IBS: 0.24027185216325905
Fold 5 IBS: 0.23849175782634383
[I 2024-04-16 10:21:08,465] Trial 59 finished with value: 0.2273143305367964 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.9111341643808946, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15152628104819157}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23161246102067778
Fold 2 IBS: 0.18315762337529268
Fold 3 IBS: 0.23355670246252003
Fold 4 IBS: 0.2141622801821901
Fold 5 IBS: 0.21203217214938297
[I 2024-04-16 10:21:41,738] Trial 60 finished with value: 0.2149042478380127 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 416, 'oob_score': True, 'max_samples': 0.8718303197272472, 'max_features': None, 'min_weight_fraction_leaf': 0.23327466883167086}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22544682915255349
Fold 2 IBS: 0.1837835452877901
Fold 3 IBS: 0.2340793656204444
Fold 4 IBS: 0.2134652558712757
Fold 5 IBS: 0.21112250446162584
[I 2024-04-16 10:22:13,674] Trial 61 finished with value: 0.21357950007873788 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.9574526723194436, 'max_features': None, 'min_weight_fraction_leaf': 0.16996612592674035}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23566977171208375
Fold 2 IBS: 0.18355373888054702
Fold 3 IBS: 0.23122032354257444
Fold 4 IBS: 0.2166971166015121
Fold 5 IBS: 0.21225529499203713
[I 2024-04-16 10:22:40,532] Trial 62 finished with value: 0.2158792491457509 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.9692513608661454, 'max_features': None, 'min_weight_fraction_leaf': 0.10901914015734161}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22018115372329825
Fold 2 IBS: 0.18426413954689186
Fold 3 IBS: 0.234485531054646
Fold 4 IBS: 0.2145039808669085
Fold 5 IBS: 0.21463282350485688
[I 2024-04-16 10:23:00,684] Trial 63 finished with value: 0.21361352573932027 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 346, 'oob_score': True, 'max_samples': 0.8078307550305597, 'max_features': None, 'min_weight_fraction_leaf': 0.17457092877839805}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.2365430487443625
Fold 2 IBS: 0.18238280317098843
Fold 3 IBS: 0.2322276544017584
Fold 4 IBS: 0.21380685041046066
Fold 5 IBS: 0.21115528132467798
[I 2024-04-16 10:23:42,770] Trial 64 finished with value: 0.21522312761044962 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.9369908825823273, 'max_features': None, 'min_weight_fraction_leaf': 0.19119487575645203}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2545794604503248
Fold 2 IBS: 0.18515187912067008
Fold 3 IBS: 0.22861527937785475
Fold 4 IBS: 0.22050482646274178
Fold 5 IBS: 0.2129134229864224
[I 2024-04-16 10:24:27,253] Trial 65 finished with value: 0.22035297367960277 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 362, 'oob_score': True, 'max_samples': 0.9998359499913109, 'max_features': None, 'min_weight_fraction_leaf': 0.1490943973635694}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22654845800464724
Fold 2 IBS: 0.18332141958706227
Fold 3 IBS: 0.2350631328838295
Fold 4 IBS: 0.21236321104852912
Fold 5 IBS: 0.21200214915706886
[I 2024-04-16 10:25:05,474] Trial 66 finished with value: 0.2138596741362274 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 436, 'oob_score': True, 'max_samples': 0.8962905931034715, 'max_features': None, 'min_weight_fraction_leaf': 0.0680516900187007}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2314909050987209
Fold 2 IBS: 0.20249096930835778
Fold 3 IBS: 0.23980167405092054
Fold 4 IBS: 0.2353173847496087
Fold 5 IBS: 0.2224605814306102
[I 2024-04-16 10:25:16,177] Trial 67 finished with value: 0.22631230292764365 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.576072702219687, 'max_features': None, 'min_weight_fraction_leaf': 0.23671139187646353}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23493478177072255
Fold 2 IBS: 0.1839771658107539
Fold 3 IBS: 0.2327966378875902
Fold 4 IBS: 0.21470499176958288
Fold 5 IBS: 0.21135088245166292
[I 2024-04-16 10:25:49,040] Trial 68 finished with value: 0.21555289193806249 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 340, 'oob_score': True, 'max_samples': 0.9745293218944675, 'max_features': None, 'min_weight_fraction_leaf': 0.2208990376756659}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.24543506602157308
Fold 2 IBS: 0.20317035895085483
Fold 3 IBS: 0.20373744028936427
Fold 4 IBS: 0.2408108283305109
Fold 5 IBS: 0.23682283690526376
[I 2024-04-16 10:25:53,510] Trial 69 finished with value: 0.22599530609951338 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.8624070878492855, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1990248466441951}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2503935277219034
Fold 2 IBS: 0.20812254306242206
Fold 3 IBS: 0.2113368150498763
Fold 4 IBS: 0.249610089701322
Fold 5 IBS: 0.24046537193598522
[I 2024-04-16 10:25:58,917] Trial 70 finished with value: 0.2319856694943018 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9186596987029689, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11544109176287089}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.221575371693387
Fold 2 IBS: 0.18398808173473347
Fold 3 IBS: 0.23724504533105953
Fold 4 IBS: 0.214033992760505
Fold 5 IBS: 0.21096749762165287
[I 2024-04-16 10:26:33,819] Trial 71 finished with value: 0.2135619978282676 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 386, 'oob_score': True, 'max_samples': 0.9723894444805646, 'max_features': None, 'min_weight_fraction_leaf': 0.2730206487158777}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22000227604484365
Fold 2 IBS: 0.1835976512867323
Fold 3 IBS: 0.23496758393840209
Fold 4 IBS: 0.2108901768233098
Fold 5 IBS: 0.21502432185948614
[I 2024-04-16 10:26:53,768] Trial 72 finished with value: 0.21289640199055476 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.9429494364281713, 'max_features': None, 'min_weight_fraction_leaf': 0.26970631759176494}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22727419395708034
Fold 2 IBS: 0.1871701080786577
Fold 3 IBS: 0.2378340481827281
Fold 4 IBS: 0.2289741531942034
Fold 5 IBS: 0.22120111363123252
[I 2024-04-16 10:27:15,723] Trial 73 finished with value: 0.22049072340878037 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 361, 'oob_score': True, 'max_samples': 0.9341055458028956, 'max_features': None, 'min_weight_fraction_leaf': 0.31471941963288985}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22389252687104882
Fold 2 IBS: 0.18478568946187152
Fold 3 IBS: 0.23569319407407555
Fold 4 IBS: 0.21383105927421142
Fold 5 IBS: 0.21188816578028835
[I 2024-04-16 10:27:51,686] Trial 74 finished with value: 0.21401812709229912 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 476, 'oob_score': True, 'max_samples': 0.946932527578757, 'max_features': None, 'min_weight_fraction_leaf': 0.24504456019566914}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.21854302798549347
Fold 2 IBS: 0.18176372907932323
Fold 3 IBS: 0.23671374300002862
Fold 4 IBS: 0.21422935554752687
Fold 5 IBS: 0.21083967154267064
[I 2024-04-16 10:28:15,523] Trial 75 finished with value: 0.21241790543100855 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 288, 'oob_score': True, 'max_samples': 0.9803084469016909, 'max_features': None, 'min_weight_fraction_leaf': 0.13142931899110993}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2197445619216238
Fold 2 IBS: 0.18503554254500237
Fold 3 IBS: 0.23931664349279788
Fold 4 IBS: 0.21161636970789327
Fold 5 IBS: 0.2155020163620093
[I 2024-04-16 10:28:34,993] Trial 76 finished with value: 0.21424302680586535 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 10, 'n_estimators': 293, 'oob_score': True, 'max_samples': 0.8898157454998676, 'max_features': None, 'min_weight_fraction_leaf': 0.04187570620310249}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2327743668403808
Fold 2 IBS: 0.1821560057823301
Fold 3 IBS: 0.23089143622316666
Fold 4 IBS: 0.23577008510470598
Fold 5 IBS: 0.2235347877710858
[I 2024-04-16 10:28:51,739] Trial 77 finished with value: 0.22102533634433388 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 1, 'n_estimators': 277, 'oob_score': True, 'max_samples': 0.9879662653142723, 'max_features': None, 'min_weight_fraction_leaf': 0.2732568395879575}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22818707588004375
Fold 2 IBS: 0.19020975012058644
Fold 3 IBS: 0.23714209938276803
Fold 4 IBS: 0.2286788294533738
Fold 5 IBS: 0.21849469879449682
[I 2024-04-16 10:29:06,726] Trial 78 finished with value: 0.2205424907262538 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 14, 'n_estimators': 258, 'oob_score': True, 'max_samples': 0.8577519434160554, 'max_features': None, 'min_weight_fraction_leaf': 0.2950875024553569}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.23474728243730542
Fold 2 IBS: 0.1971796499722597
Fold 3 IBS: 0.22834092402557343
Fold 4 IBS: 0.23413287196690447
Fold 5 IBS: 0.2205931708782621
[I 2024-04-16 10:29:14,297] Trial 79 finished with value: 0.222998779856061 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 224, 'oob_score': True, 'max_samples': 0.5125421624254995, 'max_features': None, 'min_weight_fraction_leaf': 0.09061426277200699}. Best is trial 43 with value: 0.2123917039278164.

Fold 1 IBS: 0.2511057207255618
Fold 2 IBS: 0.21572593535559278
Fold 3 IBS: 0.2149073004231141
Fold 4 IBS: 0.2472468833843753
Fold 5 IBS: 0.24247425822381166
[I 2024-04-16 10:29:18,366] Trial 80 finished with value: 0.23429201962249113 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 335, 'oob_score': True, 'max_samples': 0.3618038809495957, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15390327148267055}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22731065610063553
Fold 2 IBS: 0.18233470119562936
Fold 3 IBS: 0.23388585350331287
Fold 4 IBS: 0.21305351886000728
Fold 5 IBS: 0.21153134197254575
[I 2024-04-16 10:29:41,418] Trial 81 finished with value: 0.21362321432642614 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9436804929256887, 'max_features': None, 'min_weight_fraction_leaf': 0.12227771301430333}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2272092638449265
Fold 2 IBS: 0.18337145552397865
Fold 3 IBS: 0.23253451313019002
Fold 4 IBS: 0.2138892087318099
Fold 5 IBS: 0.21064394129949776
[I 2024-04-16 10:30:04,011] Trial 82 finished with value: 0.21352967650608057 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 11, 'n_estimators': 291, 'oob_score': True, 'max_samples': 0.9739450345174413, 'max_features': None, 'min_weight_fraction_leaf': 0.13403887256843836}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.22274585720905865
Fold 2 IBS: 0.1844029972495469
Fold 3 IBS: 0.23578817469856042
Fold 4 IBS: 0.21351903584251283
Fold 5 IBS: 0.2127567489010132
[I 2024-04-16 10:30:30,442] Trial 83 finished with value: 0.2138425627801384 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 415, 'oob_score': True, 'max_samples': 0.9124790440575847, 'max_features': None, 'min_weight_fraction_leaf': 0.16278108493661606}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.2202096426617108
Fold 2 IBS: 0.18300193402384377
Fold 3 IBS: 0.23678774176994796
Fold 4 IBS: 0.21045698381793299
Fold 5 IBS: 0.21165170888809465
[I 2024-04-16 10:30:46,723] Trial 84 finished with value: 0.21242160223230605 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.936102238020355, 'max_features': None, 'min_weight_fraction_leaf': 0.2119155188772585}. Best is trial 43 with value: 0.2123917039278164.
Fold 1 IBS: 0.21864119730769158
Fold 2 IBS: 0.18332295425049822
Fold 3 IBS: 0.23624932020049083
Fold 4 IBS: 0.21147766575005164
Fold 5 IBS: 0.21180476450696664
[I 2024-04-16 10:31:03,622] Trial 85 finished with value: 0.21229918040313978 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.9290276329324785, 'max_features': None, 'min_weight_fraction_leaf': 0.20767416366171196}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22157963241090176
Fold 2 IBS: 0.18471642393517332
Fold 3 IBS: 0.23692790272940076
Fold 4 IBS: 0.2129824811604961
Fold 5 IBS: 0.21206997240184605
[I 2024-04-16 10:31:16,051] Trial 86 finished with value: 0.21365528252756358 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 15, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.9228769430188052, 'max_features': None, 'min_weight_fraction_leaf': 0.21001587254602957}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22291669368529446
Fold 2 IBS: 0.182919208879211
Fold 3 IBS: 0.2388503936972904
Fold 4 IBS: 0.2158328741690931
Fold 5 IBS: 0.21059528283696147
[I 2024-04-16 10:31:32,220] Trial 87 finished with value: 0.21422289065357009 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 249, 'oob_score': True, 'max_samples': 0.9992791729154259, 'max_features': None, 'min_weight_fraction_leaf': 0.2508797456646947}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25078768869857776
Fold 2 IBS: 0.2106109982817939
Fold 3 IBS: 0.21209311522476643
Fold 4 IBS: 0.2508930677647447
Fold 5 IBS: 0.2396844528546169
[I 2024-04-16 10:31:34,848] Trial 88 finished with value: 0.23281386456489997 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.8919471551124474, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2208845327776338}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25097719650425315
Fold 2 IBS: 0.21314574899449434
Fold 3 IBS: 0.21417231974570053
Fold 4 IBS: 0.24960112806534465
Fold 5 IBS: 0.23897071968187011
[I 2024-04-16 10:31:37,899] Trial 89 finished with value: 0.23337342259833255 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 239, 'oob_score': True, 'max_samples': 0.7625776406001812, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.27140964339693613}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2245068533940247
Fold 2 IBS: 0.18699761355556005
Fold 3 IBS: 0.23544042396212175
Fold 4 IBS: 0.21923587620229615
Fold 5 IBS: 0.21746532566897547
[I 2024-04-16 10:31:51,463] Trial 90 finished with value: 0.2167292185565956 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 308, 'oob_score': True, 'max_samples': 0.8012706364382673, 'max_features': None, 'min_weight_fraction_leaf': 0.23491486759055114}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2218234667655608
Fold 2 IBS: 0.18409612316964802
Fold 3 IBS: 0.23464760900884943
Fold 4 IBS: 0.2117828169055223
Fold 5 IBS: 0.2103391213040047
[I 2024-04-16 10:32:10,216] Trial 91 finished with value: 0.21253782743071703 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 272, 'oob_score': True, 'max_samples': 0.9410520587040254, 'max_features': None, 'min_weight_fraction_leaf': 0.1785736177001936}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22650071929198848
Fold 2 IBS: 0.18423351453669495
Fold 3 IBS: 0.23455340947340386
Fold 4 IBS: 0.2132023845394669
Fold 5 IBS: 0.21079535139402752
[I 2024-04-16 10:32:24,569] Trial 92 finished with value: 0.21385707584711638 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 19, 'max_depth': 13, 'n_estimators': 218, 'oob_score': True, 'max_samples': 0.9462078683111473, 'max_features': None, 'min_weight_fraction_leaf': 0.18398630290568166}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2206749867203408
Fold 2 IBS: 0.1845112548902161
Fold 3 IBS: 0.2346107050489519
Fold 4 IBS: 0.2108494294764449
Fold 5 IBS: 0.21185476519664903
[I 2024-04-16 10:32:40,596] Trial 93 finished with value: 0.21250022826652054 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 276, 'oob_score': True, 'max_samples': 0.9344189667836965, 'max_features': None, 'min_weight_fraction_leaf': 0.25854173047664814}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.21954476841343637
Fold 2 IBS: 0.18528849913355389
Fold 3 IBS: 0.2376539942951079
Fold 4 IBS: 0.21407967576842526
Fold 5 IBS: 0.21415642969000542
[I 2024-04-16 10:32:54,320] Trial 94 finished with value: 0.21414467346010574 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 273, 'oob_score': True, 'max_samples': 0.8713272061326163, 'max_features': None, 'min_weight_fraction_leaf': 0.2544497221932043}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.2208107209861332
Fold 2 IBS: 0.18302956342153184
Fold 3 IBS: 0.23391990270287968
Fold 4 IBS: 0.21268167805826516
Fold 5 IBS: 0.21308598369318132
[I 2024-04-16 10:33:13,208] Trial 95 finished with value: 0.21270556977239824 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.9058370293437961, 'max_features': None, 'min_weight_fraction_leaf': 0.19807593185105676}. Best is trial 85 with value: 0.21229918040313978.

Fold 1 IBS: 0.21975345965751325
Fold 2 IBS: 0.1826687616539912
Fold 3 IBS: 0.23593232323623828
Fold 4 IBS: 0.21692323202986982
Fold 5 IBS: 0.2157946933853038
[I 2024-04-16 10:33:27,664] Trial 96 finished with value: 0.21421449399258327 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 9, 'min_samples_leaf': 20, 'max_depth': 12, 'n_estimators': 296, 'oob_score': True, 'max_samples': 0.8401991280225705, 'max_features': None, 'min_weight_fraction_leaf': 0.20291905202477475}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.22595559817931396
Fold 2 IBS: 0.18811290557691393
Fold 3 IBS: 0.23790732230802805
Fold 4 IBS: 0.22652570350197412
Fold 5 IBS: 0.21929538367243218
[I 2024-04-16 10:33:39,499] Trial 97 finished with value: 0.21955938264773245 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 7, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.9001142343235446, 'max_features': None, 'min_weight_fraction_leaf': 0.3126608885366039}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.219856246176777
Fold 2 IBS: 0.18353273410232165
Fold 3 IBS: 0.2355137490033137
Fold 4 IBS: 0.21361316808033728
Fold 5 IBS: 0.2140273787654496
[I 2024-04-16 10:33:57,984] Trial 98 finished with value: 0.21330865522563985 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 285, 'oob_score': True, 'max_samples': 0.930993873060305, 'max_features': None, 'min_weight_fraction_leaf': 0.2803881279308147}. Best is trial 85 with value: 0.21229918040313978.
Fold 1 IBS: 0.25162904138051667
Fold 2 IBS: 0.21372129222801167
Fold 3 IBS: 0.21584553623530486
Fold 4 IBS: 0.24661972756352624
Fold 5 IBS: 0.2419641213954559
[I 2024-04-16 10:34:01,017] Trial 99 finished with value: 0.23395594376056308 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.7146385057934307, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2661847294368132}. Best is trial 85 with value: 0.21229918040313978.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.21229918040313978], datetime_start=datetime.datetime(2024, 4, 16, 10, 30, 46, 733739), datetime_complete=datetime.datetime(2024, 4, 16, 10, 31, 3, 621167), params={'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 13, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.9290276329324785, 'max_features': None, 'min_weight_fraction_leaf': 0.20767416366171196}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=85, value=None)


* Best Score for IBS:
 0.21229918040313978

In [56]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [57]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.847
train_ibs:  0.212

#### Test

In [58]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

In [59]:
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])
 
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=16, max_features='auto', max_leaf_nodes=14,
                     max_samples=0.9873533850424658, min_samples_leaf=4,
                     min_samples_split=8,
                     min_weight_fraction_leaf=0.04287202412707603,
                     n_estimators=441, random_state=123, warm_start=True)

test_cindex:  0.54

RandomSurvivalForest(max_depth=13, max_features=None, max_leaf_nodes=11,
                     max_samples=0.9290276329324785, min_samples_leaf=20,
                     min_samples_split=9,
                     min_weight_fraction_leaf=0.20767416366171196,
                     n_estimators=268, oob_score=True, random_state=123)

test_ibs:  0.262

In [60]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [61]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [62]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 10:34:09,726] A new study created in memory with name: no-name-6b5f4022-299b-4324-afa7-a8a0c772bcc7

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 10:34:10,666] Trial 0 finished with value: 0.716790225055755 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:12,641] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.5493562231759657
[I 2024-04-16 10:34:16,810] Trial 2 finished with value: 0.637634842816299 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.716790225055755.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 10:34:17,264] Trial 3 finished with value: 0.7443588775438851 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:18,725] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:20,374] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 10:34:21,299] Trial 6 finished with value: 0.7034666689139027 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.47410358565737054
Fold 2 C-index: 0.6744186046511628
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5095057034220533
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 10:34:23,538] Trial 7 finished with value: 0.5777346993743705 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 10:34:23,746] Trial 8 finished with value: 0.7256957651909646 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.4820717131474104
Fold 2 C-index: 0.686046511627907
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 10:34:28,460] Trial 9 finished with value: 0.6059266344558226 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:29,198] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5159362549800797
Fold 2 C-index: 0.560077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 10:34:29,368] Trial 11 finished with value: 0.6662340928785145 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 10:34:29,665] Trial 12 finished with value: 0.7197009443517154 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 10:34:30,126] Trial 13 finished with value: 0.72821263434496 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 10:34:30,635] Trial 14 finished with value: 0.7120489026779355 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9015509519801813, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.7443588775438851.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 10:34:31,127] Trial 15 finished with value: 0.7572849484519277 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.10514124205272785}. Best is trial 15 with value: 0.7572849484519277.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:31,708] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6778661833429002, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 10:34:32,094] Trial 17 finished with value: 0.7059353800436845 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 100, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3861349103797888, 'min_weight_fraction_leaf': 0.08960575345471988}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:35,169] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 16, 'n_estimators': 289, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.0015754650744169152}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 10:34:35,703] Trial 19 finished with value: 0.6786787744649703 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 187, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6687006907779914, 'min_weight_fraction_leaf': 0.2047592648179435}. Best is trial 15 with value: 0.7572849484519277.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:34:36,087] Trial 20 finished with value: 0.7839268317994365 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7175509123723454, 'min_weight_fraction_leaf': 0.10521853896660721}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 10:34:36,430] Trial 21 finished with value: 0.7300192593991303 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7031450748447657, 'min_weight_fraction_leaf': 0.09403903585726361}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 10:34:37,017] Trial 22 finished with value: 0.7824269267844081 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 152, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6098864513030943, 'min_weight_fraction_leaf': 0.12170977787094135}. Best is trial 20 with value: 0.7839268317994365.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:34:37,233] Trial 23 finished with value: 0.7877806145769775 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.612388364912981, 'min_weight_fraction_leaf': 0.04561569622889031}. Best is trial 23 with value: 0.7877806145769775.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:34:37,488] Trial 24 finished with value: 0.7999244832738667 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 28, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5945370691033937, 'min_weight_fraction_leaf': 0.053281515068204915}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.49203187250996017
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.6673003802281369
Fold 5 C-index: 0.48068669527896996
[I 2024-04-16 10:34:37,664] Trial 25 finished with value: 0.63181873270089 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4547673780685811, 'min_weight_fraction_leaf': 0.04996091221009652}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 10:34:38,410] Trial 26 finished with value: 0.6663763013235233 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 45, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2871142790618468, 'min_weight_fraction_leaf': 0.037039062886846254}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 10:34:38,657] Trial 27 finished with value: 0.7922020480583813 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 28, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5158783707916587, 'min_weight_fraction_leaf': 0.06598691661059801}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:38,826] Trial 28 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5202420447021523, 'min_weight_fraction_leaf': 0.46961689585527955}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 10:34:39,964] Trial 29 finished with value: 0.7702942146882898 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3719168657740124, 'min_weight_fraction_leaf': 0.0713932172807959}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7510729613733905
[I 2024-04-16 10:34:40,209] Trial 30 finished with value: 0.718731646723884 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 40, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5897285086805036, 'min_weight_fraction_leaf': 0.021168508687250828}. Best is trial 24 with value: 0.7999244832738667.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7424892703862661
[I 2024-04-16 10:34:40,589] Trial 31 finished with value: 0.7450836287108459 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 1, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6115041201105692, 'min_weight_fraction_leaf': 0.07529457384788989}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 10:34:41,027] Trial 32 finished with value: 0.7891534508186784 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 106, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5041709909476946, 'min_weight_fraction_leaf': 0.06275815026057982}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 10:34:41,293] Trial 33 finished with value: 0.7778383668899079 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 21, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5060458087305748, 'min_weight_fraction_leaf': 0.05994930115816848}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 10:34:41,620] Trial 34 finished with value: 0.7450364060708232 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 62, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3919948296728538, 'min_weight_fraction_leaf': 0.023576029209776687}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.689922480620155
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6349809885931559
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 10:34:42,274] Trial 35 finished with value: 0.6618125355016858 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 109, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4662710037037924, 'min_weight_fraction_leaf': 0.19476322320546924}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:42,663] Trial 36 finished with value: 0.5 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 28, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5268973035148778, 'min_weight_fraction_leaf': 0.38971770475262413}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 10:34:42,954] Trial 37 finished with value: 0.6460461608102859 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 74, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6401214919324493, 'min_weight_fraction_leaf': 0.2889936764724038}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7553648068669528
[I 2024-04-16 10:34:43,483] Trial 38 finished with value: 0.7517656861973904 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 124, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3198045057515263, 'min_weight_fraction_leaf': 0.06699213680332672}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.4903100775193798
Fold 3 C-index: 0.30425531914893617
Fold 4 C-index: 0.38022813688212925
Fold 5 C-index: 0.5364806866952789
[I 2024-04-16 10:34:43,676] Trial 39 finished with value: 0.45221500341169457 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5513036300755328, 'min_weight_fraction_leaf': 0.008478210005256219}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:44,806] Trial 40 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.43468184041368385, 'min_weight_fraction_leaf': 0.42733722871780283}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 10:34:45,205] Trial 41 finished with value: 0.786556444150027 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 94, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6273061563283064, 'min_weight_fraction_leaf': 0.10637509234156475}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8638297872340426
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 10:34:45,524] Trial 42 finished with value: 0.7790118129920596 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 56, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6164425687958124, 'min_weight_fraction_leaf': 0.039624372585458756}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7267441860465116
Fold 3 C-index: 0.8531914893617021
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 10:34:45,798] Trial 43 finished with value: 0.7182793874400513 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 43, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5600036197598728, 'min_weight_fraction_leaf': 0.08742449741166494}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.4940239043824701
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 10:34:46,376] Trial 44 finished with value: 0.6220741639573587 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 214, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.4844175747650499, 'min_weight_fraction_leaf': 0.12204423321537092}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 10:34:46,856] Trial 45 finished with value: 0.7157517489250119 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 175, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7291844385738098, 'min_weight_fraction_leaf': 0.1516538096539411}. Best is trial 24 with value: 0.7999244832738667.

Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 10:34:47,452] Trial 46 finished with value: 0.7975395138249034 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 107, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7438723611436409, 'min_weight_fraction_leaf': 0.03993350527314018}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 10:34:47,971] Trial 47 finished with value: 0.6647065921586429 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 26, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.42581868302241566, 'min_weight_fraction_leaf': 0.03606885164861798}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.47808764940239046
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 10:34:48,661] Trial 48 finished with value: 0.7398991153868522 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 116, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8248732462756444, 'min_weight_fraction_leaf': 0.05743142223461807}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 10:34:49,370] Trial 49 finished with value: 0.7740102565229516 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7375840189864764, 'min_weight_fraction_leaf': 0.02900897691743311}. Best is trial 24 with value: 0.7999244832738667.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 10:34:50,641] Trial 50 finished with value: 0.8061742964895082 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8580859398770397, 'min_weight_fraction_leaf': 0.14067466804198955}. Best is trial 50 with value: 0.8061742964895082.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8897338403041825
Fold 5 C-index: 0.9141630901287554
[I 2024-04-16 10:34:52,371] Trial 51 finished with value: 0.8345109680877927 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8650780732103325, 'min_weight_fraction_leaf': 0.07836530237930157}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 10:34:53,975] Trial 52 finished with value: 0.8118997310422689 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 382, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9368700755827909, 'min_weight_fraction_leaf': 0.13447102711070466}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 10:34:55,276] Trial 53 finished with value: 0.801596270492346 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9333985785267058, 'min_weight_fraction_leaf': 0.17098721901271324}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:34:56,552] Trial 54 finished with value: 0.7883044323959387 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 354, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9223836761742507, 'min_weight_fraction_leaf': 0.18255482980599205}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 10:34:57,535] Trial 55 finished with value: 0.6482113869397063 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.850640872005829, 'min_weight_fraction_leaf': 0.22456808619691168}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 10:34:59,123] Trial 56 finished with value: 0.8045156871530021 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9504873149405666, 'min_weight_fraction_leaf': 0.14183520465682528}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 10:35:00,167] Trial 57 finished with value: 0.7476944411137867 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 335, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9549982016992005, 'min_weight_fraction_leaf': 0.1632420912078524}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 10:35:05,591] Trial 58 finished with value: 0.7041938058364086 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 289, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9955977767169721, 'min_weight_fraction_leaf': 0.139303061496208}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 10:35:07,810] Trial 59 finished with value: 0.6850776550936483 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 407, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9316447705416647, 'min_weight_fraction_leaf': 0.2770418832937534}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 10:35:09,311] Trial 60 finished with value: 0.7659333705752307 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.858061041207964, 'min_weight_fraction_leaf': 0.20492284757517695}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 10:35:10,593] Trial 61 finished with value: 0.8072715857181292 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.895774589556567, 'min_weight_fraction_leaf': 0.13260279061395738}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 10:35:11,813] Trial 62 finished with value: 0.8087820359158744 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 317, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981332031409504, 'min_weight_fraction_leaf': 0.13337740856374872}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 10:35:13,100] Trial 63 finished with value: 0.8072173346373459 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 334, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.89018545929469, 'min_weight_fraction_leaf': 0.13345593137281736}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 10:35:14,306] Trial 64 finished with value: 0.8039397464932385 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 316, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8837514156336624, 'min_weight_fraction_leaf': 0.13743872464484008}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8497854077253219
[I 2024-04-16 10:35:15,411] Trial 65 finished with value: 0.8022232887177733 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 297, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7835122881802231, 'min_weight_fraction_leaf': 0.11229139643403509}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 10:35:16,353] Trial 66 finished with value: 0.7125273202159338 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 373, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8328417978438267, 'min_weight_fraction_leaf': 0.15095298703120333}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 10:35:17,705] Trial 67 finished with value: 0.8192305249719898 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8966863484745369, 'min_weight_fraction_leaf': 0.08534464991274132}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 10:35:18,568] Trial 68 finished with value: 0.7895818286565903 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 13, 'n_estimators': 329, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.978346026643418, 'min_weight_fraction_leaf': 0.09273408393147946}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 10:35:19,716] Trial 69 finished with value: 0.8102956431944776 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 274, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.896331905162175, 'min_weight_fraction_leaf': 0.12035329094677631}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 10:35:20,921] Trial 70 finished with value: 0.8079169388264177 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 270, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9017688247437723, 'min_weight_fraction_leaf': 0.08377148583149059}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 10:35:22,126] Trial 71 finished with value: 0.7983010681646548 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 278, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.891832704671649, 'min_weight_fraction_leaf': 0.12184359415244413}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 10:35:23,502] Trial 72 finished with value: 0.8130993617058649 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 271, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9102780085257545, 'min_weight_fraction_leaf': 0.07813836666294671}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 10:35:24,615] Trial 73 finished with value: 0.7998076505962926 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 254, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9138857823629444, 'min_weight_fraction_leaf': 0.07760837137280302}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 10:35:25,679] Trial 74 finished with value: 0.8086401909388299 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 238, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7932478141389542, 'min_weight_fraction_leaf': 0.09585515657733794}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 10:35:26,658] Trial 75 finished with value: 0.8097308691495133 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 235, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.768048780360931, 'min_weight_fraction_leaf': 0.08472098125787089}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.50199203187251
Fold 2 C-index: 0.6937984496124031
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5278969957081545
[I 2024-04-16 10:35:29,217] Trial 76 finished with value: 0.6077421067160182 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 229, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.8075950318465789, 'min_weight_fraction_leaf': 0.10238704048789282}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 10:35:30,207] Trial 77 finished with value: 0.8053956752022688 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7673803604130273, 'min_weight_fraction_leaf': 0.11299645952197773}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.871244635193133
[I 2024-04-16 10:35:31,085] Trial 78 finished with value: 0.8088475970325533 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 202, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8265609743395299, 'min_weight_fraction_leaf': 0.09652130656141297}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:35:31,650] Trial 79 finished with value: 0.5 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 194, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9626257579282349, 'min_weight_fraction_leaf': 0.4970767359615762}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 10:35:32,297] Trial 80 finished with value: 0.7313420533362782 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 18, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8393510141017606, 'min_weight_fraction_leaf': 0.07992117300354869}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8626609442060086
[I 2024-04-16 10:35:33,331] Trial 81 finished with value: 0.812638992208535 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7918630780504825, 'min_weight_fraction_leaf': 0.10229656223682107}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 10:35:34,502] Trial 82 finished with value: 0.8097453262522389 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8756895757277906, 'min_weight_fraction_leaf': 0.11757230018978515}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8540772532188842
[I 2024-04-16 10:35:35,586] Trial 83 finished with value: 0.807919942472151 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 273, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8726637848385762, 'min_weight_fraction_leaf': 0.11382370857816454}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7725321888412017
[I 2024-04-16 10:35:36,709] Trial 84 finished with value: 0.7704249207701752 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 295, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8061519296879504, 'min_weight_fraction_leaf': 0.09515235358222952}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8454935622317596
[I 2024-04-16 10:35:37,390] Trial 85 finished with value: 0.7697903027420463 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7614101494119764, 'min_weight_fraction_leaf': 0.05368501986833329}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 10:35:38,226] Trial 86 finished with value: 0.7980794918103985 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8672025396777255, 'min_weight_fraction_leaf': 0.15838375423479073}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 10:35:39,809] Trial 87 finished with value: 0.8168764432002176 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 390, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.821099320531621, 'min_weight_fraction_leaf': 0.07219095881107078}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.6311787072243346
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 10:35:43,997] Trial 88 finished with value: 0.6418944800226886 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 375, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9410457375171901, 'min_weight_fraction_leaf': 0.016074649059118228}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 10:35:45,791] Trial 89 finished with value: 0.8111823792625452 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 405, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9747877453952127, 'min_weight_fraction_leaf': 0.07239963989752378}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8669527896995708
[I 2024-04-16 10:35:46,886] Trial 90 finished with value: 0.8031613891936974 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 398, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9993570244260745, 'min_weight_fraction_leaf': 0.06937148653050808}. Best is trial 51 with value: 0.8345109680877927.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8927038626609443
[I 2024-04-16 10:35:48,753] Trial 91 finished with value: 0.8136959302089742 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9761926707915443, 'min_weight_fraction_leaf': 0.07539349300221282}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8841201716738197
[I 2024-04-16 10:35:50,644] Trial 92 finished with value: 0.8135443171331339 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9178848241272458, 'min_weight_fraction_leaf': 0.06881178939245426}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.9063829787234042
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8969957081545065
[I 2024-04-16 10:35:52,774] Trial 93 finished with value: 0.8168871695376991 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9726464389425372, 'min_weight_fraction_leaf': 0.04860102614756785}. Best is trial 51 with value: 0.8345109680877927.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 10:35:55,283] Trial 94 finished with value: 0.8363648293898092 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 420, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9661961925179824, 'min_weight_fraction_leaf': 0.05044552883677316}. Best is trial 94 with value: 0.8363648293898092.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9319148936170213
Fold 4 C-index: 0.908745247148289
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 10:35:58,118] Trial 95 finished with value: 0.8420040749825455 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9149322253821399, 'min_weight_fraction_leaf': 0.0472298750691944}. Best is trial 95 with value: 0.8420040749825455.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9361702127659575
Fold 4 C-index: 0.9163498098859315
Fold 5 C-index: 0.9356223175965666
[I 2024-04-16 10:36:01,320] Trial 96 finished with value: 0.8420072320634038 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9186714469202719, 'min_weight_fraction_leaf': 0.04956115599708024}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8851063829787233
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8583690987124464
[I 2024-04-16 10:36:03,165] Trial 97 finished with value: 0.8063263334084045 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 16, 'n_estimators': 469, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.964556183783718, 'min_weight_fraction_leaf': 0.045349231505527596}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8884120171673819
[I 2024-04-16 10:36:04,416] Trial 98 finished with value: 0.8016468008219135 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9181873113334154, 'min_weight_fraction_leaf': 0.0021149043736411396}. Best is trial 96 with value: 0.8420072320634038.
Fold 1 C-index: 0.5139442231075697
Fold 2 C-index: 0.8914728682170543
Fold 3 C-index: 0.9276595744680851

[I 2024-04-16 10:36:08,081] A new study created in memory with name: no-name-b35f32a2-6617-4fcd-911f-ba51df92c9bd

Fold 4 C-index: 0.9011406844106464
Fold 5 C-index: 0.9313304721030042
[I 2024-04-16 10:36:08,056] Trial 99 finished with value: 0.833109564461272 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9775205205061748, 'min_weight_fraction_leaf': 0.025836771862969607}. Best is trial 96 with value: 0.8420072320634038.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.8420072320634038], datetime_start=datetime.datetime(2024, 4, 16, 10, 35, 58, 123874), datetime_complete=datetime.datetime(2024, 4, 16, 10, 36, 1, 319795), params={'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9186714469202719, 'min_weight_fraction_leaf': 0.04956115599708024}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=96, value=None)


* Best Score for C-index:
 0.8420072320634038

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2458308290335683
Fold 2 IBS: 0.21843205852973288
Fold 3 IBS: 0.21441509219214497
Fold 4 IBS: 0.2444058540887671
Fold 5 IBS: 0.23326299386163582
[I 2024-04-16 10:36:11,085] Trial 0 finished with value: 0.2312693655411698 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.2312693655411698.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-16 10:36:15,683] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.2312693655411698.
Fold 1 IBS: 0.2422217804898227
Fold 2 IBS: 0.20604215939156156
Fold 3 IBS: 0.20536348887036088
Fold 4 IBS: 0.23816713819570307
Fold 5 IBS: 0.23443654693516552
[I 2024-04-16 10:36:19,746] Trial 2 finished with value: 0.22524622277652276 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 2 with value: 0.22524622277652276.
Fold 1 IBS: 0.23997737551317644
Fold 2 IBS: 0.20628917387182416
Fold 3 IBS: 0.19999308418823725
Fold 4 IBS: 0.2364990518088652
Fold 5 IBS: 0.2312952255166902
[I 2024-04-16 10:36:21,158] Trial 3 finished with value: 0.22281078217975864 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-16 10:36:24,617] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-16 10:36:26,349] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2471773923605192
Fold 2 IBS: 0.21732133101414405
Fold 3 IBS: 0.21608483753650748
Fold 4 IBS: 0.2446264041325047
Fold 5 IBS: 0.2336320559523974
[I 2024-04-16 10:36:29,931] Trial 6 finished with value: 0.23176840419921457 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24753232495746105
Fold 2 IBS: 0.22863034299161297
Fold 3 IBS: 0.22780059870027192
Fold 4 IBS: 0.24525231645256226
Fold 5 IBS: 0.22980036498615944
[I 2024-04-16 10:36:32,103] Trial 7 finished with value: 0.23580318961761354 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24388792032844758
Fold 2 IBS: 0.20431268727524246
Fold 3 IBS: 0.20272723355028044
Fold 4 IBS: 0.2323397363347534
Fold 5 IBS: 0.24009730434274343
[I 2024-04-16 10:36:32,692] Trial 8 finished with value: 0.2246729763662935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2463750753680711
Fold 2 IBS: 0.23137427725039786
Fold 3 IBS: 0.22881548983290517
Fold 4 IBS: 0.24172449141228589
Fold 5 IBS: 0.23039951809375644
[I 2024-04-16 10:36:37,162] Trial 9 finished with value: 0.2357377703914833 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24657852287672213
Fold 2 IBS: 0.23206316112817363
Fold 3 IBS: 0.23003515681903183
Fold 4 IBS: 0.2412906026999272
Fold 5 IBS: 0.22957933452614643
[I 2024-04-16 10:36:38,608] Trial 10 finished with value: 0.2359093556100002 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.25578614141973877, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24957527092392598
Fold 2 IBS: 0.22095833564497003
Fold 3 IBS: 0.22451358571145658
Fold 4 IBS: 0.23060380529406801
Fold 5 IBS: 0.2239626552625768
[I 2024-04-16 10:36:38,831] Trial 11 finished with value: 0.22992273056739948 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 4, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.24023311319978927
Fold 2 IBS: 0.20654639843048508
Fold 3 IBS: 0.2105997477995539
Fold 4 IBS: 0.237375222973572
Fold 5 IBS: 0.22992356847238266
[I 2024-04-16 10:36:39,554] Trial 12 finished with value: 0.22493561017515656 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 63, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.16694541300368826}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.2397712237804985
Fold 2 IBS: 0.21059242308473916
Fold 3 IBS: 0.20295179527005874
Fold 4 IBS: 0.23391501821825889
Fold 5 IBS: 0.22771604186877867
[I 2024-04-16 10:36:40,886] Trial 13 finished with value: 0.2229893004444668 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 139, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8757004183768704, 'min_weight_fraction_leaf': 0.12942492296949484}. Best is trial 3 with value: 0.22281078217975864.
Fold 1 IBS: 0.23887694209074434
Fold 2 IBS: 0.2134098978318189
Fold 3 IBS: 0.20587933877935985
Fold 4 IBS: 0.23635078736680823
Fold 5 IBS: 0.22529646039343412
[I 2024-04-16 10:36:42,388] Trial 14 finished with value: 0.2239626852924331 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9015509519801813, 'min_weight_fraction_leaf': 0.2319873930301426}. Best is trial 3 with value: 0.22281078217975864.

Fold 1 IBS: 0.22839809695394112
Fold 2 IBS: 0.20514152743957886
Fold 3 IBS: 0.20092249425472394
Fold 4 IBS: 0.2267763825894776
Fold 5 IBS: 0.2165164172534966
[I 2024-04-16 10:36:44,028] Trial 15 finished with value: 0.21555098369824366 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6967810217991331, 'min_weight_fraction_leaf': 0.10514124205272785}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2467245753421851
Fold 2 IBS: 0.23215086227692838
Fold 3 IBS: 0.22944190979967086
Fold 4 IBS: 0.24159087177588787
Fold 5 IBS: 0.2303525764883273
[I 2024-04-16 10:36:45,946] Trial 16 finished with value: 0.2360521591365999 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 4, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6778661833429002, 'min_weight_fraction_leaf': 0.35612645124522524}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2388284357689523
Fold 2 IBS: 0.21255562783348272
Fold 3 IBS: 0.19795960994236278
Fold 4 IBS: 0.23366309896652035
Fold 5 IBS: 0.21908035151857583
[I 2024-04-16 10:36:47,058] Trial 17 finished with value: 0.22041742480597878 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 100, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3861349103797888, 'min_weight_fraction_leaf': 0.08960575345471988}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24132280104394047
Fold 2 IBS: 0.21269327432629742
Fold 3 IBS: 0.20049020592168434
Fold 4 IBS: 0.24087378277320573
Fold 5 IBS: 0.22425840634695127
[I 2024-04-16 10:36:48,364] Trial 18 finished with value: 0.22392769408241583 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 99, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.3311809976298237, 'min_weight_fraction_leaf': 0.0013669683957226175}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24688611571045718
Fold 2 IBS: 0.23219132054830785
Fold 3 IBS: 0.23027940191796936
Fold 4 IBS: 0.2409026395193649
Fold 5 IBS: 0.22930251676390168
[I 2024-04-16 10:36:50,644] Trial 19 finished with value: 0.23591239889200016 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.10730942678329708, 'min_weight_fraction_leaf': 0.21750931502909437}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24536664618236573
Fold 2 IBS: 0.2357094417147659
Fold 3 IBS: 0.21756007685466264
Fold 4 IBS: 0.2351394543483008
Fold 5 IBS: 0.2245456493888334
[I 2024-04-16 10:36:50,894] Trial 20 finished with value: 0.23166425369778568 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3772282506046544, 'min_weight_fraction_leaf': 0.08406658048281501}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2440283698606937
Fold 2 IBS: 0.21764096243387274
Fold 3 IBS: 0.21271440236923256
Fold 4 IBS: 0.23885081521770216
Fold 5 IBS: 0.2333205794826251
[I 2024-04-16 10:36:52,559] Trial 21 finished with value: 0.22931102587282526 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 184, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6547034385443382, 'min_weight_fraction_leaf': 0.11712848599628017}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23989681726525797
Fold 2 IBS: 0.21257567014754183
Fold 3 IBS: 0.20496080476015688
Fold 4 IBS: 0.23573527504580374
Fold 5 IBS: 0.2401811583699638
[I 2024-04-16 10:36:53,468] Trial 22 finished with value: 0.22666994511774483 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 85, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.6873159527855055, 'min_weight_fraction_leaf': 0.05847692406679354}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24662017777674988
Fold 2 IBS: 0.2321469807414623
Fold 3 IBS: 0.2297372799644881
Fold 4 IBS: 0.2412254547631197
Fold 5 IBS: 0.2298155591809165
[I 2024-04-16 10:36:54,724] Trial 23 finished with value: 0.2359090904853473 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 138, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.242935508884002, 'min_weight_fraction_leaf': 0.19289553221610561}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23585018430451674
Fold 2 IBS: 0.20314428554405467
Fold 3 IBS: 0.1987071229364999
Fold 4 IBS: 0.2270924304194166
Fold 5 IBS: 0.2222151698718961
[I 2024-04-16 10:36:57,124] Trial 24 finished with value: 0.21740183861527682 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 221, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4214218271993085, 'min_weight_fraction_leaf': 0.1063490999450386}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.23764386500385992
Fold 2 IBS: 0.21572081027096882
Fold 3 IBS: 0.20688911926768339
Fold 4 IBS: 0.23390279551321708
Fold 5 IBS: 0.2244570150053522
[I 2024-04-16 10:36:59,638] Trial 25 finished with value: 0.22372272101221627 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.46423262855736735, 'min_weight_fraction_leaf': 0.03989016828055364}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2466435841775417
Fold 2 IBS: 0.23225630869945743
Fold 3 IBS: 0.22989986339484095
Fold 4 IBS: 0.24118506766749884
Fold 5 IBS: 0.2302270252070719
[I 2024-04-16 10:37:03,563] Trial 26 finished with value: 0.23604236982928217 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 308, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.2871142790618468, 'min_weight_fraction_leaf': 0.2830550434153414}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24581839690270998
Fold 2 IBS: 0.23209782103745266
Fold 3 IBS: 0.2301979993648951
Fold 4 IBS: 0.24136593180524166
Fold 5 IBS: 0.23032438582493162
[I 2024-04-16 10:37:04,235] Trial 27 finished with value: 0.23596090698704622 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 48, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.1729529760271648, 'min_weight_fraction_leaf': 0.09037604869015846}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24656075558902663
Fold 2 IBS: 0.23213951345883066
Fold 3 IBS: 0.23002825142879788
Fold 4 IBS: 0.2411104649641026
Fold 5 IBS: 0.22975811808319055
[I 2024-04-16 10:37:05,367] Trial 28 finished with value: 0.23591942070478966 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 3, 'n_estimators': 99, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.3965788725022428, 'min_weight_fraction_leaf': 0.46961689585527955}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24630859844407268
Fold 2 IBS: 0.2322956347000389
Fold 3 IBS: 0.22955007442663075
Fold 4 IBS: 0.24141130613962739
Fold 5 IBS: 0.23029996757106383
[I 2024-04-16 10:37:08,892] Trial 29 finished with value: 0.23597311625628672 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5102179166457144, 'min_weight_fraction_leaf': 0.41528561873840175}. Best is trial 15 with value: 0.21555098369824366.

Fold 1 IBS: 0.24189951983836425
Fold 2 IBS: 0.22116291305449884
Fold 3 IBS: 0.21713072638394984
Fold 4 IBS: 0.24023416048014104
Fold 5 IBS: 0.22691624187044754
[I 2024-04-16 10:37:10,552] Trial 30 finished with value: 0.2294687123254803 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 180, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5988223393644435, 'min_weight_fraction_leaf': 0.20241101766143602}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24364620279536037
Fold 2 IBS: 0.2205505651382432
Fold 3 IBS: 0.21184589055027794
Fold 4 IBS: 0.24142198209294274
Fold 5 IBS: 0.2268782233658812
[I 2024-04-16 10:37:12,080] Trial 31 finished with value: 0.22886857278854106 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 162, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4032327849321123, 'min_weight_fraction_leaf': 0.11708530604258689}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.24661093959371452
Fold 2 IBS: 0.2301025933150535
Fold 3 IBS: 0.22780980093586722
Fold 4 IBS: 0.24300904078398428
Fold 5 IBS: 0.230890565198856
[I 2024-04-16 10:37:13,393] Trial 32 finished with value: 0.2356845879654951 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 6, 'n_estimators': 140, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8550327764351591, 'min_weight_fraction_leaf': 0.09887734225836066}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2424013858898089
Fold 2 IBS: 0.22181355253513207
Fold 3 IBS: 0.21628743919777896
Fold 4 IBS: 0.2454744216544916
Fold 5 IBS: 0.23210919596554697
[I 2024-04-16 10:37:15,409] Trial 33 finished with value: 0.2316171990485517 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 231, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7143311025567932, 'min_weight_fraction_leaf': 0.059053506325031944}. Best is trial 15 with value: 0.21555098369824366.
Fold 1 IBS: 0.2343422980803409
Fold 2 IBS: 0.19726504628882152
Fold 3 IBS: 0.19589228360095498
Fold 4 IBS: 0.22148252413832495
Fold 5 IBS: 0.214706958088969
[I 2024-04-16 10:37:18,420] Trial 34 finished with value: 0.21273782203948227 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 206, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5121057659041139, 'min_weight_fraction_leaf': 0.09009257320408029}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23551743581515994
Fold 2 IBS: 0.1988816220790032
Fold 3 IBS: 0.19713820389502454
Fold 4 IBS: 0.2194355626151018
Fold 5 IBS: 0.2139468393382114
[I 2024-04-16 10:37:22,599] Trial 35 finished with value: 0.2129839327485002 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 289, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5035601925130949, 'min_weight_fraction_leaf': 0.030526656384477324}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23568872403345578
Fold 2 IBS: 0.19973786792004417
Fold 3 IBS: 0.19454987157876255
Fold 4 IBS: 0.2220374053163543
Fold 5 IBS: 0.21894163635279854
[I 2024-04-16 10:37:26,967] Trial 36 finished with value: 0.2141911010402831 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 295, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5262952246734235, 'min_weight_fraction_leaf': 0.0345815739535376}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.2448880936287523
Fold 2 IBS: 0.19358697937735503
Fold 3 IBS: 0.19135743911323064
Fold 4 IBS: 0.22209877079990858
Fold 5 IBS: 0.2136995510425158
[I 2024-04-16 10:37:33,400] Trial 37 finished with value: 0.21312616679235247 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 353, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5274918233702399, 'min_weight_fraction_leaf': 0.02265299373602317}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.2448767682487151
Fold 2 IBS: 0.1940286543150714
Fold 3 IBS: 0.19114962341732433
Fold 4 IBS: 0.22260340040871293
Fold 5 IBS: 0.2137471478793161
[I 2024-04-16 10:37:39,850] Trial 38 finished with value: 0.213281118853828 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 358, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5285575239051581, 'min_weight_fraction_leaf': 0.020652803664130342}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.25250559243829124
Fold 2 IBS: 0.2142865173352782
Fold 3 IBS: 0.2171359677193678
Fold 4 IBS: 0.24416225491761936
Fold 5 IBS: 0.23974411262472503
[I 2024-04-16 10:37:43,872] Trial 39 finished with value: 0.2335668890070563 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 366, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6097100988293976, 'min_weight_fraction_leaf': 0.019130885670483717}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.242901108432075
Fold 2 IBS: 0.19697988117930024
Fold 3 IBS: 0.19238091011496858
Fold 4 IBS: 0.22078058275151072
Fold 5 IBS: 0.21495218733382793
[I 2024-04-16 10:37:49,235] Trial 40 finished with value: 0.21359893396233648 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4791645577618608, 'min_weight_fraction_leaf': 0.0694663236398695}. Best is trial 34 with value: 0.21273782203948227.
Fold 1 IBS: 0.23908968735515912
Fold 2 IBS: 0.1947617350535389
Fold 3 IBS: 0.1930636406143849
Fold 4 IBS: 0.22123635288762244
Fold 5 IBS: 0.21467012929006576
[I 2024-04-16 10:37:54,780] Trial 41 finished with value: 0.2125643090401542 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 337, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4831314083966843, 'min_weight_fraction_leaf': 0.06563330905051376}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2396028413626137
Fold 2 IBS: 0.19718848617005288
Fold 3 IBS: 0.1948104348257847
Fold 4 IBS: 0.21837938467562384
Fold 5 IBS: 0.2149288714625758
[I 2024-04-16 10:38:02,084] Trial 42 finished with value: 0.21298200369933024 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 392, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5583443788864256, 'min_weight_fraction_leaf': 0.020815822054945837}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2396687176213861
Fold 2 IBS: 0.19612731372046435
Fold 3 IBS: 0.19260264364145704
Fold 4 IBS: 0.21936281835328128
Fold 5 IBS: 0.21697387881345614
[I 2024-04-16 10:38:10,099] Trial 43 finished with value: 0.212947074430009 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 398, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5930099345609534, 'min_weight_fraction_leaf': 0.0495559888649342}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2467168371470764
Fold 2 IBS: 0.23064557906926417
Fold 3 IBS: 0.2276870878947108
Fold 4 IBS: 0.24249203531915456
Fold 5 IBS: 0.2307608809971462
[I 2024-04-16 10:38:14,401] Trial 44 finished with value: 0.2356604840854704 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 394, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5868150496992739, 'min_weight_fraction_leaf': 0.05755833486941584}. Best is trial 41 with value: 0.2125643090401542.

Fold 1 IBS: 0.24970180838617465
Fold 2 IBS: 0.20711640796461644
Fold 3 IBS: 0.210622445605441
Fold 4 IBS: 0.2398038048480638
Fold 5 IBS: 0.23687430367329662
[I 2024-04-16 10:38:19,828] Trial 45 finished with value: 0.22882375409551847 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 481, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6241818506764952, 'min_weight_fraction_leaf': 0.003649071529300437}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.23201805390304453
Fold 2 IBS: 0.20002733588165444
Fold 3 IBS: 0.19908476397700547
Fold 4 IBS: 0.22074033459452136
Fold 5 IBS: 0.21494542822340232
[I 2024-04-16 10:38:25,697] Trial 46 finished with value: 0.2133631833159256 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5598513951057802, 'min_weight_fraction_leaf': 0.14065807022429982}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25373498445062415
Fold 2 IBS: 0.19975024860475576
Fold 3 IBS: 0.18626200905063714
Fold 4 IBS: 0.23343402582868134
Fold 5 IBS: 0.2162436088485457
[I 2024-04-16 10:38:33,144] Trial 47 finished with value: 0.21788497535664883 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 401, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.456067991993716, 'min_weight_fraction_leaf': 0.04492679621107826}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.24471890993869544
Fold 2 IBS: 0.2177801752519796
Fold 3 IBS: 0.2138769702970347
Fold 4 IBS: 0.24414741845988078
Fold 5 IBS: 0.23442893665869308
[I 2024-04-16 10:38:37,987] Trial 48 finished with value: 0.23099048212125672 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 451, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7258961740431729, 'min_weight_fraction_leaf': 0.08041738051512136}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25137663968626234
Fold 2 IBS: 0.20933386581443944
Fold 3 IBS: 0.2080886887712674
Fold 4 IBS: 0.2390514698710601
Fold 5 IBS: 0.23530782004401327
[I 2024-04-16 10:38:41,968] Trial 49 finished with value: 0.22863169683740853 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 329, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6352263471927108, 'min_weight_fraction_leaf': 0.06926131111849082}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2360626460552677
Fold 2 IBS: 0.20623441042932847
Fold 3 IBS: 0.20130662121469356
Fold 4 IBS: 0.22957511854007973
Fold 5 IBS: 0.2179557393265252
[I 2024-04-16 10:38:45,630] Trial 50 finished with value: 0.2182269071131789 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 261, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.49402812735141344, 'min_weight_fraction_leaf': 0.16186576022040558}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.25013784901547137
Fold 2 IBS: 0.195316535389084
Fold 3 IBS: 0.18808126103485753
Fold 4 IBS: 0.22936838612837893
Fold 5 IBS: 0.21349776174083104
[I 2024-04-16 10:38:52,612] Trial 51 finished with value: 0.2152803586617246 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 339, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5509334567262397, 'min_weight_fraction_leaf': 0.027839511211907052}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2427342211563647
Fold 2 IBS: 0.1958477826874508
Fold 3 IBS: 0.20028177886831744
Fold 4 IBS: 0.22985892846448394
Fold 5 IBS: 0.22177135601929956
[I 2024-04-16 10:38:57,058] Trial 52 finished with value: 0.2180988134391833 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 281, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4433955231058734, 'min_weight_fraction_leaf': 0.012876902678362334}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.24397581332160848
Fold 2 IBS: 0.19953500021907264
Fold 3 IBS: 0.18917458509628868
Fold 4 IBS: 0.22839776163972092
Fold 5 IBS: 0.21811042015429574
[I 2024-04-16 10:39:06,363] Trial 53 finished with value: 0.21583871608619729 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 445, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5100539037151481, 'min_weight_fraction_leaf': 0.046932235033188746}. Best is trial 41 with value: 0.2125643090401542.
Fold 1 IBS: 0.2347988257753084
Fold 2 IBS: 0.19668752838656633
Fold 3 IBS: 0.19211546662321186
Fold 4 IBS: 0.21780908681113587
Fold 5 IBS: 0.21515744682466584
[I 2024-04-16 10:39:13,729] Trial 54 finished with value: 0.21131367088417768 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 388, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5670320468073893, 'min_weight_fraction_leaf': 0.031478107602535506}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.24677947770699765
Fold 2 IBS: 0.23053037304430873
Fold 3 IBS: 0.2275728132543721
Fold 4 IBS: 0.24233405204889266
Fold 5 IBS: 0.23106120652731021
[I 2024-04-16 10:39:18,465] Trial 55 finished with value: 0.23565558451637628 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 392, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5737647614035145, 'min_weight_fraction_leaf': 0.07423158709263047}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.23689214883150628
Fold 2 IBS: 0.2120673796940858
Fold 3 IBS: 0.20315541673905635
Fold 4 IBS: 0.23098032372176497
Fold 5 IBS: 0.22253237757409347
[I 2024-04-16 10:39:23,657] Trial 56 finished with value: 0.22112552931210136 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 418, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.35399595847912424, 'min_weight_fraction_leaf': 0.13287864045187167}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2418042867685856
Fold 2 IBS: 0.20876050442208302
Fold 3 IBS: 0.20680932595685791
Fold 4 IBS: 0.23860265094248106
Fold 5 IBS: 0.23053544081685107
[I 2024-04-16 10:39:27,577] Trial 57 finished with value: 0.22530244178137168 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 323, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.649610303071809, 'min_weight_fraction_leaf': 0.042873000646334}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2424078057014189
Fold 2 IBS: 0.19483239886955803
Fold 3 IBS: 0.1957006646954686
Fold 4 IBS: 0.22122367318862327
Fold 5 IBS: 0.21799729720859018
[I 2024-04-16 10:39:32,067] Trial 58 finished with value: 0.2144323679327318 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 305, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.4329823869456646, 'min_weight_fraction_leaf': 0.05393151837123201}. Best is trial 54 with value: 0.21131367088417768.
Fold 1 IBS: 0.2318227492651181
Fold 2 IBS: 0.2004096906165338
Fold 3 IBS: 0.19250913676453307
Fold 4 IBS: 0.2145149387113131
Fold 5 IBS: 0.21608862724065606
[I 2024-04-16 10:39:36,003] Trial 59 finished with value: 0.21106902851963083 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 251, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.737660433782312, 'min_weight_fraction_leaf': 0.00011778406738288671}. Best is trial 59 with value: 0.21106902851963083.

Fold 1 IBS: 0.24516656524539981
Fold 2 IBS: 0.21062905264741455
Fold 3 IBS: 0.20928713648563754
Fold 4 IBS: 0.24177268946133224
Fold 5 IBS: 0.23349939521162735
[I 2024-04-16 10:39:40,283] Trial 60 finished with value: 0.2280709678102823 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 382, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7740796078428375, 'min_weight_fraction_leaf': 0.004254061138558238}. Best is trial 59 with value: 0.21106902851963083.
Fold 1 IBS: 0.23239287585025117
Fold 2 IBS: 0.19481155216054105
Fold 3 IBS: 0.19221809734433284
Fold 4 IBS: 0.21072513374212
Fold 5 IBS: 0.21430420045958357
[I 2024-04-16 10:39:44,542] Trial 61 finished with value: 0.20889037191136572 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 258, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7377275929061544, 'min_weight_fraction_leaf': 0.030622013808595125}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.23699492184296508
Fold 2 IBS: 0.20040108239906124
Fold 3 IBS: 0.19473792994851583
Fold 4 IBS: 0.2211524352297746
Fold 5 IBS: 0.21193828813811452
[I 2024-04-16 10:39:48,640] Trial 62 finished with value: 0.21304493151168624 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 252, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6744371054295076, 'min_weight_fraction_leaf': 0.016590925140165264}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.23928053090982188
Fold 2 IBS: 0.1936596610783976
Fold 3 IBS: 0.1908565913097194
Fold 4 IBS: 0.2136596034157615
Fold 5 IBS: 0.21619632218993348
[I 2024-04-16 10:39:57,009] Trial 63 finished with value: 0.21073054178072675 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 462, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7351622406813987, 'min_weight_fraction_leaf': 0.0003006902136090811}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24020476969246154
Fold 2 IBS: 0.19629415252007748
Fold 3 IBS: 0.19025094185398114
Fold 4 IBS: 0.21475012076783115
Fold 5 IBS: 0.21301644327935212
[I 2024-04-16 10:40:07,383] Trial 64 finished with value: 0.21090328562274072 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 476, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7465470505675268, 'min_weight_fraction_leaf': 0.0023272127300384103}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.22993405190596755
Fold 2 IBS: 0.1998559263223298
Fold 3 IBS: 0.19199793628872658
Fold 4 IBS: 0.21593343290217692
Fold 5 IBS: 0.21578188257171663
[I 2024-04-16 10:40:15,580] Trial 65 finished with value: 0.2107006459981835 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 494, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7459236633132993, 'min_weight_fraction_leaf': 0.007694946674736216}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24633591302363841
Fold 2 IBS: 0.23213986158018776
Fold 3 IBS: 0.2295520278725056
Fold 4 IBS: 0.24147959530165872
Fold 5 IBS: 0.2302765128959233
[I 2024-04-16 10:40:20,779] Trial 66 finished with value: 0.23595678213478277 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 495, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8287742581608164, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24369000739500146
Fold 2 IBS: 0.21434232747391735
Fold 3 IBS: 0.21139458332988464
Fold 4 IBS: 0.24232956272573275
Fold 5 IBS: 0.2345267106479697
[I 2024-04-16 10:40:26,009] Trial 67 finished with value: 0.22925663831450116 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 454, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7522789839507332, 'min_weight_fraction_leaf': 0.000561806644931952}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.24455511870316463
Fold 2 IBS: 0.2267934884914344
Fold 3 IBS: 0.22466410581046875
Fold 4 IBS: 0.24050323119395856
Fold 5 IBS: 0.22915624250480857
[I 2024-04-16 10:40:31,068] Trial 68 finished with value: 0.23313443734076697 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 475, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7468960619194147, 'min_weight_fraction_leaf': 0.35364036783604025}. Best is trial 61 with value: 0.20889037191136572.
Fold 1 IBS: 0.2300787980001647
Fold 2 IBS: 0.19641627828017147
Fold 3 IBS: 0.19122863621161298
Fold 4 IBS: 0.21189349607756788
Fold 5 IBS: 0.21244170680598337
[I 2024-04-16 10:40:38,960] Trial 69 finished with value: 0.20841178307510008 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 493, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9133634021932744, 'min_weight_fraction_leaf': 0.03482005395654732}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23082745033605492
Fold 2 IBS: 0.21258342376009118
Fold 3 IBS: 0.20163835694721952
Fold 4 IBS: 0.2224423063055546
Fold 5 IBS: 0.21255388838390268
[I 2024-04-16 10:40:45,295] Trial 70 finished with value: 0.21600908514656458 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 461, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9214187460767265, 'min_weight_fraction_leaf': 0.25717771363652614}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23082723175570813
Fold 2 IBS: 0.20323092307506263
Fold 3 IBS: 0.19491966614269055
Fold 4 IBS: 0.2171154201350026
Fold 5 IBS: 0.216027037289287
[I 2024-04-16 10:40:52,816] Trial 71 finished with value: 0.2124240556795502 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 490, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7932890461516613, 'min_weight_fraction_leaf': 0.032131426880574826}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23017369217350117
Fold 2 IBS: 0.20120230419550925
Fold 3 IBS: 0.193722336472291
Fold 4 IBS: 0.21617692077677259
Fold 5 IBS: 0.21617316312987098
[I 2024-04-16 10:41:00,656] Trial 72 finished with value: 0.211489683349589 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 496, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8066423104143661, 'min_weight_fraction_leaf': 0.034326469001936366}. Best is trial 69 with value: 0.20841178307510008.
Fold 1 IBS: 0.23070291890906766
Fold 2 IBS: 0.19797577360905477
Fold 3 IBS: 0.18899048202721042
Fold 4 IBS: 0.21031986359975194
Fold 5 IBS: 0.21398083574867297
[I 2024-04-16 10:41:09,741] Trial 73 finished with value: 0.20839397477875155 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9312721157462464, 'min_weight_fraction_leaf': 0.0012393034300419575}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.23615857055079026
Fold 2 IBS: 0.1966427796691383
Fold 3 IBS: 0.1929622046457027
Fold 4 IBS: 0.20870198205403534
Fold 5 IBS: 0.2125121533077471
[I 2024-04-16 10:41:17,632] Trial 74 finished with value: 0.20939553804548275 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 464, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9963604831342023, 'min_weight_fraction_leaf': 0.012116695798136328}. Best is trial 73 with value: 0.20839397477875155.

Fold 1 IBS: 0.23374241288259937
Fold 2 IBS: 0.19930439672774886
Fold 3 IBS: 0.18717738406829976
Fold 4 IBS: 0.20823176235963525
Fold 5 IBS: 0.21501371316102338
[I 2024-04-16 10:41:25,119] Trial 75 finished with value: 0.20869393383986132 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 435, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9528867121166885, 'min_weight_fraction_leaf': 0.0012590377645196535}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.24525891729558977
Fold 2 IBS: 0.21896003468791347
Fold 3 IBS: 0.21598508493564658
Fold 4 IBS: 0.24394612844374725
Fold 5 IBS: 0.2322350643210711
[I 2024-04-16 10:41:30,336] Trial 76 finished with value: 0.23127704593679366 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 465, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9658026435569093, 'min_weight_fraction_leaf': 0.015592248007567035}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.23502608441142722
Fold 2 IBS: 0.19922817017063826
Fold 3 IBS: 0.1913519268015393
Fold 4 IBS: 0.207834087421465
Fold 5 IBS: 0.2143743871087013
[I 2024-04-16 10:41:37,686] Trial 77 finished with value: 0.2095629311827542 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9853092886561814, 'min_weight_fraction_leaf': 0.010625988750975616}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.24649287843030504
Fold 2 IBS: 0.2314585308300189
Fold 3 IBS: 0.2289401139897681
Fold 4 IBS: 0.2417606515795492
Fold 5 IBS: 0.2302679373267155
[I 2024-04-16 10:41:42,264] Trial 78 finished with value: 0.23578402243127136 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 432, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9996115065732951, 'min_weight_fraction_leaf': 0.41218066030994116}. Best is trial 73 with value: 0.20839397477875155.
Fold 1 IBS: 0.2320831075429349
Fold 2 IBS: 0.19874748876281936
Fold 3 IBS: 0.1868862737714415
Fold 4 IBS: 0.2088372674979119
Fold 5 IBS: 0.2146701772034217
[I 2024-04-16 10:41:49,456] Trial 79 finished with value: 0.20824486295570588 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 433, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9333351337148593, 'min_weight_fraction_leaf': 0.013312290067980048}. Best is trial 79 with value: 0.20824486295570588.
Fold 1 IBS: 0.2321051762336623
Fold 2 IBS: 0.19872958357290424
Fold 3 IBS: 0.1868058011919495
Fold 4 IBS: 0.20883435526793945
Fold 5 IBS: 0.21456058420717486
[I 2024-04-16 10:41:56,719] Trial 80 finished with value: 0.2082071000947261 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 434, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9378042438987818, 'min_weight_fraction_leaf': 0.015273006586386988}. Best is trial 80 with value: 0.2082071000947261.
Fold 1 IBS: 0.23313533084879992
Fold 2 IBS: 0.1981286213929884
Fold 3 IBS: 0.18691652009336918
Fold 4 IBS: 0.20977045296104274
Fold 5 IBS: 0.21423701428211908
[I 2024-04-16 10:42:05,305] Trial 81 finished with value: 0.20843758791566386 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 439, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9417972207458584, 'min_weight_fraction_leaf': 0.04295474256066548}. Best is trial 80 with value: 0.2082071000947261.
Fold 1 IBS: 0.23424681521074975
Fold 2 IBS: 0.19613148875309624
Fold 3 IBS: 0.18531675217461782
Fold 4 IBS: 0.21089939380355308
Fold 5 IBS: 0.21326941327667795
[I 2024-04-16 10:42:13,694] Trial 82 finished with value: 0.20797277264373898 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9407754324156289, 'min_weight_fraction_leaf': 0.04206241234084829}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23409773201844755
Fold 2 IBS: 0.19653382628018295
Fold 3 IBS: 0.1848127640243094
Fold 4 IBS: 0.21249359291139658
Fold 5 IBS: 0.21212141767021883
[I 2024-04-16 10:42:20,878] Trial 83 finished with value: 0.20801186658091106 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 407, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9384130833098913, 'min_weight_fraction_leaf': 0.04519634108137036}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2329791447085086
Fold 2 IBS: 0.1967881823073177
Fold 3 IBS: 0.18728551841253535
Fold 4 IBS: 0.213032794231675
Fold 5 IBS: 0.21183681257533377
[I 2024-04-16 10:42:27,934] Trial 84 finished with value: 0.2083844904470741 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.925429012053495, 'min_weight_fraction_leaf': 0.05783142863073238}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2447356385509223
Fold 2 IBS: 0.21001665735971864
Fold 3 IBS: 0.20948126396091446
Fold 4 IBS: 0.24093216180850846
Fold 5 IBS: 0.2324937799728014
[I 2024-04-16 10:42:32,503] Trial 85 finished with value: 0.22753190033057305 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 411, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.9332004479717521, 'min_weight_fraction_leaf': 0.10710747728623181}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23246895566730055
Fold 2 IBS: 0.197925177609746
Fold 3 IBS: 0.18771443031867188
Fold 4 IBS: 0.21213172875001646
Fold 5 IBS: 0.2119327578096531
[I 2024-04-16 10:42:40,011] Trial 86 finished with value: 0.20843461003107758 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 440, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8874595645983381, 'min_weight_fraction_leaf': 0.06167441402952489}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23362791486913068
Fold 2 IBS: 0.19689264641068396
Fold 3 IBS: 0.18782225531230023
Fold 4 IBS: 0.21277906488160134
Fold 5 IBS: 0.2142720511235225
[I 2024-04-16 10:42:47,671] Trial 87 finished with value: 0.20907878651944775 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9017353280575152, 'min_weight_fraction_leaf': 0.08057063446482637}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.24405634920973077
Fold 2 IBS: 0.20958957820309626
Fold 3 IBS: 0.2098195749072522
Fold 4 IBS: 0.2397871849283553
Fold 5 IBS: 0.23205952756968465
[I 2024-04-16 10:42:52,114] Trial 88 finished with value: 0.22706244296362382 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 415, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8603916137186303, 'min_weight_fraction_leaf': 0.060569968472295434}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2405934580650391
Fold 2 IBS: 0.20440412320775256
Fold 3 IBS: 0.19898625051637614
Fold 4 IBS: 0.2317675135857698
Fold 5 IBS: 0.21634911771450452
[I 2024-04-16 10:42:57,233] Trial 89 finished with value: 0.2184200926178884 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 406, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8837193202561466, 'min_weight_fraction_leaf': 0.04645664782974562}. Best is trial 82 with value: 0.20797277264373898.

Fold 1 IBS: 0.24308229605873613
Fold 2 IBS: 0.20243085243083073
Fold 3 IBS: 0.20257300733372727
Fold 4 IBS: 0.2350012477048381
Fold 5 IBS: 0.22812847237666628
[I 2024-04-16 10:43:03,241] Trial 90 finished with value: 0.2222431751809597 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.9384169100812306, 'min_weight_fraction_leaf': 0.10055258156251395}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23494236000327381
Fold 2 IBS: 0.19851393414446025
Fold 3 IBS: 0.188316054669442
Fold 4 IBS: 0.20779679335240808
Fold 5 IBS: 0.21280969619087245
[I 2024-04-16 10:43:11,601] Trial 91 finished with value: 0.20847576767209133 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 442, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9619952733655167, 'min_weight_fraction_leaf': 0.040942271619228025}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23001265173746965
Fold 2 IBS: 0.1977150909325567
Fold 3 IBS: 0.19105114040885984
Fold 4 IBS: 0.21098586838673528
Fold 5 IBS: 0.2124489528575252
[I 2024-04-16 10:43:18,728] Trial 92 finished with value: 0.20844274086462936 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 449, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9098083130133213, 'min_weight_fraction_leaf': 0.055959244689231205}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23186934214354446
Fold 2 IBS: 0.19805339699670332
Fold 3 IBS: 0.1938995408571186
Fold 4 IBS: 0.21365134743523576
Fold 5 IBS: 0.213834084904634
[I 2024-04-16 10:43:26,391] Trial 93 finished with value: 0.21026154246744722 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 482, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9015170018833202, 'min_weight_fraction_leaf': 0.07022180710301966}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.2285498908935621
Fold 2 IBS: 0.20195173694905538
Fold 3 IBS: 0.1953268721154233
Fold 4 IBS: 0.21295922746705104
Fold 5 IBS: 0.2141875287765351
[I 2024-04-16 10:43:32,533] Trial 94 finished with value: 0.2105950512403254 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 419, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8354647860336294, 'min_weight_fraction_leaf': 0.055962542201087324}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23095232917209657
Fold 2 IBS: 0.1958865206360449
Fold 3 IBS: 0.18697181187731182
Fold 4 IBS: 0.21657103840856698
Fold 5 IBS: 0.21293289499416962
[I 2024-04-16 10:43:40,610] Trial 95 finished with value: 0.20866291901763798 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 452, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9126090538791146, 'min_weight_fraction_leaf': 0.09308205917407598}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23141696019440808
Fold 2 IBS: 0.1972469732359395
Fold 3 IBS: 0.19181384992497885
Fold 4 IBS: 0.2152661468482183
Fold 5 IBS: 0.21279056642111796
[I 2024-04-16 10:43:48,051] Trial 96 finished with value: 0.20970689932493256 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 469, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8661215594792465, 'min_weight_fraction_leaf': 0.023013782620960307}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23281842728585872
Fold 2 IBS: 0.1985355360657985
Fold 3 IBS: 0.1884611926825503
Fold 4 IBS: 0.21580615607654127
Fold 5 IBS: 0.2101267637405006
[I 2024-04-16 10:43:54,434] Trial 97 finished with value: 0.20914961517024988 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 13, 'n_estimators': 379, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8846229014197279, 'min_weight_fraction_leaf': 0.07875220306861608}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.24376771737441366
Fold 2 IBS: 0.2156464818855228
Fold 3 IBS: 0.21470997467703382
Fold 4 IBS: 0.24506757753025096
Fold 5 IBS: 0.23431638494569054
[I 2024-04-16 10:43:59,453] Trial 98 finished with value: 0.23070162728258237 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 14, 'n_estimators': 427, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9345235447965159, 'min_weight_fraction_leaf': 0.06398587825076422}. Best is trial 82 with value: 0.20797277264373898.
Fold 1 IBS: 0.23157995819346658
Fold 2 IBS: 0.19882579261217193
Fold 3 IBS: 0.19153184528522163
Fold 4 IBS: 0.21524003658426155
Fold 5 IBS: 0.21412013270935618
[I 2024-04-16 10:44:07,673] Trial 99 finished with value: 0.2102595530768956 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.84377839218482, 'min_weight_fraction_leaf': 0.11311649789821646}. Best is trial 82 with value: 0.20797277264373898.


* Best trial for IBS:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.20797277264373898], datetime_start=datetime.datetime(2024, 4, 16, 10, 42, 5, 312723), datetime_complete=datetime.datetime(2024, 4, 16, 10, 42, 13, 692916), params={'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 431, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9407754324156289, 'min_weight_fraction_leaf': 0.04206241234084829}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=82, value=None)


* Best Score for IBS:
 0.20797277264373898

In [63]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [64]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.842
train_ibs:  0.208

#### Test

In [65]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [66]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=16, max_features=None, max_leaf_nodes=10,
                   max_samples=0.9186714469202719, min_samples_leaf=2,
                   min_samples_split=3,
                   min_weight_fraction_leaf=0.04956115599708024,
                   n_estimators=474, random_state=123, warm_start=True)

C-index score: 0.567

ExtraSurvivalTrees(max_depth=12, max_features=None, max_leaf_nodes=9,
                   max_samples=0.9407754324156289, min_samples_leaf=9,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.04206241234084829,
                   n_estimators=431, oob_score=True, random_state=123)

IBS: 0.235

In [67]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [68]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 10:44:12,281] A new study created in memory with name: no-name-0ea7979c-821a-4512-a2a6-b56604c178c9

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:44:36,076] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:44:46,696] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:44:59,823] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:45:31,454] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:45:42,238] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:45:45,158] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:46:01,988] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:46:06,309] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:46:06,861] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 10:46:52,688] Trial 9 finished with value: 0.6832201973708838 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7737642585551331
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 10:48:01,706] Trial 10 finished with value: 0.6712397937360077 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:49:18,480] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6832201973708838.
Fold 1 C-index: 0.6713147410358565
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 10:50:23,763] Trial 12 finished with value: 0.6841431930275611 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:50:50,977] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:51:31,539] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:52:17,081] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:52:40,111] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:53:29,455] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:54:39,912] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:54:44,096] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:55:12,846] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 10:56:10,106] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6115537848605578
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 10:57:02,758] Trial 22 finished with value: 0.619312795708334 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:57:59,587] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:58:42,676] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:59:30,744] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:59:49,357] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:00:43,360] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:00:46,582] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:01:21,174] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:01:34,023] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5228136882129277
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 11:02:25,209] Trial 31 finished with value: 0.611786790783696 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:03:21,548] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:04:03,580] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:04:39,239] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6553784860557769
Fold 2 C-index: 0.6686046511627907
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 11:05:06,843] Trial 35 finished with value: 0.6685420013231411 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:05:28,774] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:05:48,430] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:06:03,018] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:06:20,205] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:06:38,065] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 11:07:34,618] Trial 41 finished with value: 0.6093445399392414 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:08:17,268] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:09:00,198] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:09:17,761] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:10:05,700] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.4860557768924303
Fold 2 C-index: 0.6821705426356589
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5551330798479087
Fold 5 C-index: 0.463519313304721
[I 2024-04-16 11:10:11,924] Trial 46 finished with value: 0.5692906361531651 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:10:30,904] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.03176403693294541, 'dropout_rate': 0.3498118985606263, 'n_estimators': 311, 'criterion': 'squared_error', 'ccp_alpha': 1.661787786465391, 'min_weight_fraction_leaf': 0.3313569504524189, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0658502841058407e-06, 'validation_fraction': 0.9349106995677626, 'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 7}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:10:31,319] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.7795620265296891, 'learning_rate': 0.02031575704478572, 'dropout_rate': 0.1073207171648626, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.1386953090406989, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9933742654917034, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 12 with value: 0.6841431930275611.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:11:17,654] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.9838861069093487, 'learning_rate': 0.015139882774656225, 'dropout_rate': 0.29582807120816745, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'auto', 'min_impurity_decrease': 1.0677294357907833e-07, 'validation_fraction': 0.28616351261163725, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:11:37,203] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.0013062644622639785, 'dropout_rate': 0.24125576461922837, 'n_estimators': 291, 'criterion': 'squared_error', 'ccp_alpha': 2.2224019868292646, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'auto', 'min_impurity_decrease': 4.1535796547081375e-07, 'validation_fraction': 0.4330566028790252, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5170212765957447
Fold 4 C-index: 0.6083650190114068
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:12:29,747] Trial 51 finished with value: 0.6138143425937758 and parameters: {'subsample': 0.8717443631112737, 'learning_rate': 0.006616728315935782, 'dropout_rate': 0.17858790490895218, 'n_estimators': 439, 'criterion': 'squared_error', 'ccp_alpha': 0.012928318097826519, 'min_weight_fraction_leaf': 0.4658711277635662, 'max_features': 'auto', 'min_impurity_decrease': 3.7719550144765347e-07, 'validation_fraction': 0.8890948102888172, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:13:29,916] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.8600452143616768, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.18426490654900665, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.3268256777978031, 'min_weight_fraction_leaf': 0.4698482977463435, 'max_features': 'auto', 'min_impurity_decrease': 1.8970689457597929e-07, 'validation_fraction': 0.7907152055757274, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:14:23,640] Trial 53 finished with value: 0.5 and parameters: {'subsample': 0.9429985164193612, 'learning_rate': 0.01210259689637212, 'dropout_rate': 0.16709004215832246, 'n_estimators': 442, 'criterion': 'squared_error', 'ccp_alpha': 1.355930920770751, 'min_weight_fraction_leaf': 0.44688401918267284, 'max_features': 'auto', 'min_impurity_decrease': 1.3370772545900196e-06, 'validation_fraction': 0.8482207213921362, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:14:39,588] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8147206508663337, 'learning_rate': 0.043146549395218045, 'dropout_rate': 0.8266353856620614, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 0.4402476369193899, 'min_weight_fraction_leaf': 0.403465815144378, 'max_features': 'auto', 'min_impurity_decrease': 0.009274431072766336, 'validation_fraction': 0.9013663610610466, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:15:43,567] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9029355236435976, 'learning_rate': 0.0069862044003569015, 'dropout_rate': 0.2714637824563154, 'n_estimators': 493, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.20205377440058656, 'max_features': 'auto', 'min_impurity_decrease': 5.480356851781927e-07, 'validation_fraction': 0.9611026002356494, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:16:18,055] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.9900310764127254, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.13035104784910678, 'n_estimators': 373, 'criterion': 'squared_error', 'ccp_alpha': 1.030013456919117, 'min_weight_fraction_leaf': 0.39532826999294124, 'max_features': 1, 'min_impurity_decrease': 1.6304555456718902e-07, 'validation_fraction': 0.6752987077694675, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 12 with value: 0.6841431930275611.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 11:16:50,756] Trial 57 finished with value: 0.6916626606095264 and parameters: {'subsample': 0.7372794740983749, 'learning_rate': 0.07439616301612664, 'dropout_rate': 0.5891903890315894, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.0019551426651700787, 'min_weight_fraction_leaf': 0.3663477858006307, 'max_features': 'auto', 'min_impurity_decrease': 3.365152936571637e-07, 'validation_fraction': 0.9993820900191361, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:17:16,918] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.740417255833941, 'learning_rate': 0.08011510722272602, 'dropout_rate': 0.6195846181212514, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 5.929975119025805, 'min_weight_fraction_leaf': 0.311339954548064, 'max_features': 0.1, 'min_impurity_decrease': 2.1554900690561924e-06, 'validation_fraction': 0.9698819721425359, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:17:48,508] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.6313932742304071, 'learning_rate': 0.08675370704859038, 'dropout_rate': 0.5460527407257292, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 1.8542659560131192, 'min_weight_fraction_leaf': 0.3698106479709166, 'max_features': 'log2', 'min_impurity_decrease': 7.380740444731775e-07, 'validation_fraction': 0.9977032043603392, 'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:17:54,709] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.6791716844984723, 'learning_rate': 0.08763134010262277, 'dropout_rate': 0.6506047265765441, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 1.3887836841387762, 'min_weight_fraction_leaf': 0.3542140149719947, 'max_features': 'auto', 'min_impurity_decrease': 5.3774251612153256e-05, 'validation_fraction': 0.9294449799181549, 'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 7, 'max_depth': 5}. Best is trial 57 with value: 0.6916626606095264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:18:39,978] Trial 61 finished with value: 0.5127659574468085 and parameters: {'subsample': 0.5777054240152439, 'learning_rate': 0.0043890144447948955, 'dropout_rate': 0.2238557425834033, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.22729228144381666, 'min_weight_fraction_leaf': 0.4847667891453218, 'max_features': 'auto', 'min_impurity_decrease': 3.121762528354459e-07, 'validation_fraction': 0.8794060911772942, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.5851063829787234
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6845493562231759
[I 2024-04-16 11:19:35,619] Trial 62 finished with value: 0.6671051444586171 and parameters: {'subsample': 0.8280927356694872, 'learning_rate': 0.012941968520404364, 'dropout_rate': 0.16851713525090162, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 0.022717462020606087, 'min_weight_fraction_leaf': 0.41782991757217913, 'max_features': 'auto', 'min_impurity_decrease': 1.6297128321880156e-07, 'validation_fraction': 0.8216047754912434, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:20:14,481] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.8179794453140475, 'learning_rate': 0.07155184022383326, 'dropout_rate': 0.5059523129078595, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.733686110808502, 'min_weight_fraction_leaf': 0.4266346533719304, 'max_features': 'auto', 'min_impurity_decrease': 1.456573145641989e-07, 'validation_fraction': 0.8226670106263154, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:21:00,822] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.7257892105627847, 'learning_rate': 0.02248195835921648, 'dropout_rate': 0.449913369550909, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4337068311554637, 'min_weight_fraction_leaf': 0.40949100256777493, 'max_features': 'auto', 'min_impurity_decrease': 2.3829259538917073e-07, 'validation_fraction': 0.9264223190540628, 'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:21:28,267] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.789360221844535, 'learning_rate': 0.011722172098720455, 'dropout_rate': 0.5832565770529121, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.9257201840062063, 'min_weight_fraction_leaf': 0.3826221056999394, 'max_features': 'auto', 'min_impurity_decrease': 0.00018567504305581884, 'validation_fraction': 0.7684528850780882, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:22:11,246] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.9423465114553011, 'learning_rate': 0.026890895479547216, 'dropout_rate': 0.27005657366012886, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.3406131595034317, 'min_weight_fraction_leaf': 0.273466592831212, 'max_features': 'sqrt', 'min_impurity_decrease': 5.724092120969544e-07, 'validation_fraction': 0.8663542646961032, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:23:01,744] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.8509816424016059, 'learning_rate': 0.018962435344391418, 'dropout_rate': 0.12106779245577974, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 1.1793178188167732, 'min_weight_fraction_leaf': 0.32971711200084314, 'max_features': None, 'min_impurity_decrease': 1.1734866199377895e-06, 'validation_fraction': 0.9601204189934851, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:24:03,415] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8877022924129648, 'learning_rate': 0.035301196481135985, 'dropout_rate': 0.21544296697082643, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.29598676708348526, 'min_weight_fraction_leaf': 0.437656675029897, 'max_features': 'auto', 'min_impurity_decrease': 1.3568513606672929e-07, 'validation_fraction': 0.7065228184822674, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:24:44,999] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5085409566716843, 'learning_rate': 0.07146375849643816, 'dropout_rate': 0.15565815102593683, 'n_estimators': 381, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7384677513512519, 'min_weight_fraction_leaf': 0.16528005308216742, 'max_features': 'auto', 'min_impurity_decrease': 3.4966343506407575e-07, 'validation_fraction': 0.5407783460399488, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.4765957446808511
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 11:25:20,044] Trial 70 finished with value: 0.6699861139528519 and parameters: {'subsample': 0.8427091117621403, 'learning_rate': 0.014080040753655973, 'dropout_rate': 0.7041903400301625, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.010117153579154908, 'min_weight_fraction_leaf': 0.23888457853481262, 'max_features': 'auto', 'min_impurity_decrease': 1.0665064545447388e-07, 'validation_fraction': 0.8311901171171172, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.49361702127659574
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 11:25:51,892] Trial 71 finished with value: 0.6705113277133752 and parameters: {'subsample': 0.837820165625454, 'learning_rate': 0.009162835586660466, 'dropout_rate': 0.7157677225693142, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.027818996011453684, 'min_weight_fraction_leaf': 0.2238024810121353, 'max_features': 'auto', 'min_impurity_decrease': 1.6903767334797878e-07, 'validation_fraction': 0.9136175276841315, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.49361702127659574
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 11:26:25,120] Trial 72 finished with value: 0.6704965901886897 and parameters: {'subsample': 0.8320550512705249, 'learning_rate': 0.015250213313703867, 'dropout_rate': 0.7084704325292757, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.0047914300176533624, 'min_weight_fraction_leaf': 0.22496831177560328, 'max_features': 'auto', 'min_impurity_decrease': 1.043158296301398e-07, 'validation_fraction': 0.8315500117499774, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:26:56,935] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.7522550686139352, 'learning_rate': 0.01549395863927688, 'dropout_rate': 0.7193234731509487, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.6105254483380164, 'min_weight_fraction_leaf': 0.23084281559796668, 'max_features': 'auto', 'min_impurity_decrease': 1.1425726740224786e-07, 'validation_fraction': 0.9089610037492091, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:27:21,439] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.6901097639595143, 'learning_rate': 0.009706466282346518, 'dropout_rate': 0.8289978122630015, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.32830586032225173, 'min_weight_fraction_leaf': 0.19648377877761647, 'max_features': 'auto', 'min_impurity_decrease': 1.0237452134280835e-07, 'validation_fraction': 0.6403761250010531, 'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:27:50,399] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.9243190445711414, 'learning_rate': 0.0038617948288836557, 'dropout_rate': 0.7224884343850821, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.5692251904189567, 'min_weight_fraction_leaf': 0.2446666417975855, 'max_features': None, 'min_impurity_decrease': 3.073066227115244e-07, 'validation_fraction': 0.9980785900823812, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:28:21,480] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.7974068669958387, 'learning_rate': 0.062047343259982284, 'dropout_rate': 0.6720237281802866, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 0.8485875561540186, 'min_weight_fraction_leaf': 0.2177983483250821, 'max_features': 'auto', 'min_impurity_decrease': 2.1896409704067416e-07, 'validation_fraction': 0.8579309717242278, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:28:47,177] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8422997308078775, 'learning_rate': 0.017766566895921525, 'dropout_rate': 0.6384272449487696, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5531698468613242, 'min_weight_fraction_leaf': 0.17978584394296698, 'max_features': 1, 'min_impurity_decrease': 1.6942780866930195e-07, 'validation_fraction': 0.9713474660357939, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 8}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:29:26,640] Trial 78 finished with value: 0.5 and parameters: {'subsample': 0.6517834016017484, 'learning_rate': 0.002407235870294221, 'dropout_rate': 0.5816105806888315, 'n_estimators': 498, 'criterion': 'squared_error', 'ccp_alpha': 1.1587287440372196, 'min_weight_fraction_leaf': 0.2981694522309396, 'max_features': 'auto', 'min_impurity_decrease': 5.608281082695417e-07, 'validation_fraction': 0.4642012910381656, 'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 10}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:29:34,929] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.7102653479652419, 'learning_rate': 0.00926581670466016, 'dropout_rate': 0.8340744983902122, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.244213895373325, 'min_weight_fraction_leaf': 0.26516890393090514, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.9441925364897708, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:29:55,466] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.5834757737011464, 'learning_rate': 0.026745879030501164, 'dropout_rate': 0.702176827465796, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 9.06300536097401, 'min_weight_fraction_leaf': 0.22999987323735258, 'max_features': 'log2', 'min_impurity_decrease': 2.3792015344208368e-07, 'validation_fraction': 0.3551379508028982, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 9}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.7131474103585658
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.4808510638297872
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6587982832618026
[I 2024-04-16 11:30:23,801] Trial 81 finished with value: 0.6730234656174222 and parameters: {'subsample': 0.8325293669317142, 'learning_rate': 0.011806037995297227, 'dropout_rate': 0.7551006664918564, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.04034911069069444, 'min_weight_fraction_leaf': 0.25447319867295237, 'max_features': 'auto', 'min_impurity_decrease': 1.5172002134087317e-07, 'validation_fraction': 0.9114851981025106, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 57 with value: 0.6916626606095264.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 11:30:52,566] Trial 82 finished with value: 0.698879373414812 and parameters: {'subsample': 0.7574564379023108, 'learning_rate': 0.014548313409933181, 'dropout_rate': 0.7388190394293348, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.017672701019498645, 'min_weight_fraction_leaf': 0.18953464920787744, 'max_features': 'auto', 'min_impurity_decrease': 1.4736811730220929e-07, 'validation_fraction': 0.9118325083710781, 'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:31:18,827] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.7686876073989469, 'learning_rate': 0.013838758072384357, 'dropout_rate': 0.7911803425652506, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.6372477576434026, 'min_weight_fraction_leaf': 0.19053597558098956, 'max_features': 'auto', 'min_impurity_decrease': 1.044261661000394e-07, 'validation_fraction': 0.9081833240552606, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:31:46,261] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.8417391470557727, 'learning_rate': 0.02022963558253854, 'dropout_rate': 0.7549313249685682, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.21448418173643904, 'min_weight_fraction_leaf': 0.14529026645886883, 'max_features': 'auto', 'min_impurity_decrease': 1.644017634935428e-07, 'validation_fraction': 0.7522154789012329, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.

Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5148936170212766
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6738197424892703
[I 2024-04-16 11:32:07,829] Trial 85 finished with value: 0.6764106721092568 and parameters: {'subsample': 0.7354973785260009, 'learning_rate': 0.016077297348185124, 'dropout_rate': 0.7998038530392593, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.011704477637461151, 'min_weight_fraction_leaf': 0.25414654453375674, 'max_features': 'auto', 'min_impurity_decrease': 4.3624226956840624e-07, 'validation_fraction': 0.8473925109174445, 'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:32:11,373] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.7408782122857952, 'learning_rate': 0.008176338925322723, 'dropout_rate': 0.8784853674438767, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.8792495785897113, 'min_weight_fraction_leaf': 0.21067569979765627, 'max_features': 'auto', 'min_impurity_decrease': 8.838933091327168e-07, 'validation_fraction': 0.976898355040724, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:32:33,848] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.7919841956110775, 'learning_rate': 0.016800285566641673, 'dropout_rate': 0.8053771471721777, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 6.848676757092456, 'min_weight_fraction_leaf': 0.25627475842564307, 'max_features': 'auto', 'min_impurity_decrease': 4.4582432432077124e-07, 'validation_fraction': 0.567887901649637, 'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:32:49,390] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.7637017957134666, 'learning_rate': 0.0046996483876466065, 'dropout_rate': 0.8619792930233291, 'n_estimators': 409, 'criterion': 'squared_error', 'ccp_alpha': 0.4746488265956075, 'min_weight_fraction_leaf': 0.28109817636901246, 'max_features': 'auto', 'min_impurity_decrease': 6.846032299820816e-07, 'validation_fraction': 0.8020692816016028, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 14}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:33:21,879] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.9623924871310936, 'learning_rate': 0.0015527825801297172, 'dropout_rate': 0.7519223066786315, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 1.2232438573199316, 'min_weight_fraction_leaf': 0.15271636525917553, 'max_features': 'auto', 'min_impurity_decrease': 3.1868906706070215e-07, 'validation_fraction': 0.9409810619692617, 'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:33:30,075] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.8745132816034922, 'learning_rate': 0.024313584301659426, 'dropout_rate': 0.8788019303444206, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.2487952428061195, 'min_weight_fraction_leaf': 0.008931419075771496, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5174531590387773e-06, 'validation_fraction': 0.8951588805626794, 'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.7131474103585658
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.4851063829787234
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6630901287553648
[I 2024-04-16 11:33:54,893] Trial 91 finished with value: 0.6731825109490227 and parameters: {'subsample': 0.8354990297039531, 'learning_rate': 0.0138293831902292, 'dropout_rate': 0.7281039467319077, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.03758540364708225, 'min_weight_fraction_leaf': 0.2530637808301116, 'max_features': 'auto', 'min_impurity_decrease': 1.5118979817918927e-07, 'validation_fraction': 0.8408512373546821, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:34:17,768] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.8085365523165823, 'learning_rate': 0.010756482814232722, 'dropout_rate': 0.7444483338307321, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.49447471804458437, 'min_weight_fraction_leaf': 0.25064996426719116, 'max_features': 'auto', 'min_impurity_decrease': 2.0676851144372516e-07, 'validation_fraction': 0.8390132957951739, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 11:34:38,630] Trial 93 finished with value: 0.6881273036948009 and parameters: {'subsample': 0.7453329553993305, 'learning_rate': 0.021174166394019457, 'dropout_rate': 0.7793451155626762, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04746460613674034, 'min_weight_fraction_leaf': 0.2093766049536608, 'max_features': 'auto', 'min_impurity_decrease': 4.3263336279630515e-07, 'validation_fraction': 0.7761975833676429, 'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:35:00,686] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.7279707912652753, 'learning_rate': 0.021608355611700266, 'dropout_rate': 0.7346078225406316, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.7086041731588438, 'min_weight_fraction_leaf': 0.20875637228664023, 'max_features': 'auto', 'min_impurity_decrease': 4.696900773859783e-07, 'validation_fraction': 0.7825380103331964, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 11}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:35:14,073] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.41059605701997526, 'learning_rate': 0.008265328833970157, 'dropout_rate': 0.7833536187763309, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.9761780021039411, 'min_weight_fraction_leaf': 0.26909043908757685, 'max_features': 'auto', 'min_impurity_decrease': 2.7953622898255886e-07, 'validation_fraction': 0.8675625663624191, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:35:44,261] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.7807484083766505, 'learning_rate': 0.019136234077479226, 'dropout_rate': 0.6797290416912756, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.2137190515453802, 'min_weight_fraction_leaf': 0.1836345173241593, 'max_features': 'auto', 'min_impurity_decrease': 1.5053955435348267e-07, 'validation_fraction': 0.9141346557445693, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 14, 'max_depth': 15}. Best is trial 82 with value: 0.698879373414812.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:36:04,265] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.6692392383366766, 'learning_rate': 0.005703846641879013, 'dropout_rate': 0.778639362865728, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.4660418580309801, 'min_weight_fraction_leaf': 0.19771711093861588, 'max_features': 'auto', 'min_impurity_decrease': 0.0032862083702029487, 'validation_fraction': 0.9476450583671194, 'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 12, 'max_depth': 13}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 11:36:20,246] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.7074353323873224, 'learning_rate': 0.012490550235605942, 'dropout_rate': 0.8460634884916687, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 4.816291450322713, 'min_weight_fraction_leaf': 0.2365858465049468, 'max_features': 'auto', 'min_impurity_decrease': 9.113797265483529e-07, 'validation_fraction': 0.9834615394391507, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 12}. Best is trial 82 with value: 0.698879373414812.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.7604562737642585

[I 2024-04-16 11:36:43,720] A new study created in memory with name: no-name-c9f706a9-f287-431a-8c2c-5d558c04a3dc

Fold 5 C-index: 0.6802575107296137
[I 2024-04-16 11:36:43,707] Trial 99 finished with value: 0.6997238381485732 and parameters: {'subsample': 0.8597838031871279, 'learning_rate': 0.010888929954369636, 'dropout_rate': 0.8022681311855436, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.004507507039685693, 'min_weight_fraction_leaf': 0.1685851039915477, 'max_features': 'auto', 'min_impurity_decrease': 4.0700060224631717e-07, 'validation_fraction': 0.8827408742810589, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 12}. Best is trial 99 with value: 0.6997238381485732.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.6997238381485732], datetime_start=datetime.datetime(2024, 4, 16, 11, 36, 20, 252637), datetime_complete=datetime.datetime(2024, 4, 16, 11, 36, 43, 706219), params={'subsample': 0.8597838031871279, 'learning_rate': 0.010888929954369636, 'dropout_rate': 0.8022681311855436, 'n_estimators': 443, 'criterion': 'squared_error', 'ccp_alpha': 0.004507507039685693, 'min_weight_fraction_leaf': 0.1685851039915477, 'max_features': 'auto', 'min_impurity_decrease': 4.0700060224631717e-07, 'validation_fraction': 0.8827408742810589, 'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 12}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=99, value=None)


* Best Score for C-index:
 0.6997238381485732

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:36:58,588] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:37:05,024] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:37:14,373] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:37:34,132] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:37:41,087] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:37:43,028] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:37:52,713] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:37:55,373] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:37:55,781] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24611646824848502
Fold 2 IBS: 0.23045314613284576
Fold 3 IBS: 0.22864908069318055
Fold 4 IBS: 0.24088343083773206
Fold 5 IBS: 0.2286067880417571
[I 2024-04-16 11:38:26,753] Trial 9 finished with value: 0.23494178279080008 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.23166000859087926
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164904353219824
Fold 5 IBS: 0.2291762528827903
[I 2024-04-16 11:39:13,632] Trial 10 finished with value: 0.23563423441371983 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:40:06,358] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2471389609167843
Fold 2 IBS: 0.23185194695073053
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.2418709994354467
Fold 5 IBS: 0.22931414809995274
[I 2024-04-16 11:40:44,692] Trial 12 finished with value: 0.23582622492055835 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:40:59,903] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:41:34,261] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:41:55,543] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:42:07,653] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:42:37,008] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:42:51,841] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:42:54,879] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:43:26,014] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2470758782497334
Fold 2 IBS: 0.2319847418263816
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.24189505261981767
Fold 5 IBS: 0.22923216203360366
[I 2024-04-16 11:43:59,571] Trial 21 finished with value: 0.23582190451342355 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.2464930115110139
Fold 2 IBS: 0.23084795543166578

Fold 3 IBS: 0.22877023826826642
Fold 4 IBS: 0.24122503350572105
Fold 5 IBS: 0.22878079391093029
[I 2024-04-16 11:44:38,954] Trial 22 finished with value: 0.2352234065255195 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-16 11:45:14,618] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:45:36,900] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:45:57,078] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:46:14,845] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:46:17,076] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:46:22,532] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:46:43,601] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:47:19,133] Trial 30 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24669611373458267
Fold 2 IBS: 0.23161054906241668
Fold 3 IBS: 0.22885749682655868
Fold 4 IBS: 0.2415375526987621
Fold 5 IBS: 0.22900046780800146
[I 2024-04-16 11:47:54,442] Trial 31 finished with value: 0.2355404360260643 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.23494178279080008.
Fold 1 IBS: 0.24559061103708343
Fold 2 IBS: 0.23024033663487284
Fold 3 IBS: 0.2293974925753989
Fold 4 IBS: 0.24024323071520023
Fold 5 IBS: 0.2284489804567101
[I 2024-04-16 11:48:30,964] Trial 32 finished with value: 0.2347841302838531 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:48:53,415] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:49:16,584] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:49:24,912] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:49:51,279] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:49:54,568] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:50:05,775] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:50:23,052] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:50:46,731] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 32 with value: 0.2347841302838531.
Fold 1 IBS: 0.24564975054404245
Fold 2 IBS: 0.22980985720122352
Fold 3 IBS: 0.22862944699148766
Fold 4 IBS: 0.24019850838895782
Fold 5 IBS: 0.22847935077439893
[I 2024-04-16 11:51:28,145] Trial 41 finished with value: 0.23455338278002208 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24577893568533524
Fold 2 IBS: 0.2300168763545233
Fold 3 IBS: 0.2283274561934457
Fold 4 IBS: 0.24018944863835465
Fold 5 IBS: 0.2284694599346158
[I 2024-04-16 11:52:10,086] Trial 42 finished with value: 0.23455643536125495 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:52:58,687] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:53:39,099] Trial 44 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:53:49,760] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24711436282531865
Fold 2 IBS: 0.23189796599325815
Fold 3 IBS: 0.2289389886288917
Fold 4 IBS: 0.2418829980148295
Fold 5 IBS: 0.22932341012264723
[I 2024-04-16 11:54:21,510] Trial 46 finished with value: 0.23583154511698906 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:54:39,414] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:54:39,614] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:54:47,652] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:55:09,729] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.2462802649053173
Fold 2 IBS: 0.23090518019736747
Fold 3 IBS: 0.22910230952131883
Fold 4 IBS: 0.24089201571280294
Fold 5 IBS: 0.22880129355386447
[I 2024-04-16 11:55:45,866] Trial 51 finished with value: 0.23519621277813424 and parameters: {'subsample': 0.9480276186148049, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.2856033525481214, 'n_estimators': 477, 'criterion': 'squared_error', 'ccp_alpha': 0.012353867750134667, 'min_weight_fraction_leaf': 0.22461792037583256, 'max_features': 'auto', 'min_impurity_decrease': 3.3864756991240473e-06, 'validation_fraction': 0.959807845534086, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24650272034345022
Fold 2 IBS: 0.23102415353022362
Fold 3 IBS: 0.22863881664006155
Fold 4 IBS: 0.2411028633234996
Fold 5 IBS: 0.22892412673294307
[I 2024-04-16 11:56:23,044] Trial 52 finished with value: 0.2352385361140356 and parameters: {'subsample': 0.9690886547521121, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.03660199451993653, 'min_weight_fraction_leaf': 0.17297727640490082, 'max_features': 'auto', 'min_impurity_decrease': 3.049559112525484e-06, 'validation_fraction': 0.9718410393680599, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:56:56,900] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8920228452074053, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.32661371595674515, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.2945173805852883, 'max_features': 'auto', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:57:31,438] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9472264097624746, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.1508637651435515, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.22035807288061335, 'max_features': 'auto', 'min_impurity_decrease': 0.015305241535958306, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:57:58,727] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.36065535241543395, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 1.5126136571072866, 'min_weight_fraction_leaf': 0.2002957617254777, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.8814649292460881, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:58:20,020] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2818850250060197, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23297170241739207, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.2552507873943692, 'max_features': 'auto', 'min_impurity_decrease': 1.4962235814136573e-06, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:58:43,354] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8654402967188083, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5925056825473531, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.3388560781293413, 'max_features': 'auto', 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.9457965904141827, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 1}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:59:10,179] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9153649013716585, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.20247794507096373, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.13686113855005327, 'max_features': 1, 'min_impurity_decrease': 5.6056583988076206e-05, 'validation_fraction': 0.7164235243058807, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:59:30,760] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5273941310970662, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.27120464223149515, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.08408118413163579, 'max_features': 0.1, 'min_impurity_decrease': 4.3252557742868694e-07, 'validation_fraction': 0.8195507001084924, 'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:59:48,258] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4687193173806922, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.40652994108993334, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'auto', 'min_impurity_decrease': 2.777282902745793e-06, 'validation_fraction': 0.8559576979556259, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 6}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.246792274967983
Fold 2 IBS: 0.23161964216377484
Fold 3 IBS: 0.22888176928337703
Fold 4 IBS: 0.24155890986096298
Fold 5 IBS: 0.22907544730443408
[I 2024-04-16 12:00:26,437] Trial 61 finished with value: 0.2355856087161064 and parameters: {'subsample': 0.9918985385533109, 'learning_rate': 0.005743016439014149, 'dropout_rate': 0.28747233681343587, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.16038675829082302, 'max_features': 'auto', 'min_impurity_decrease': 2.9513412376244623e-06, 'validation_fraction': 0.9751691260171886, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23455338278002208.
Fold 1 IBS: 0.24556197891151196
Fold 2 IBS: 0.22972947118075088
Fold 3 IBS: 0.22847603444167852
Fold 4 IBS: 0.23983661807749995
Fold 5 IBS: 0.22821417993674387
[I 2024-04-16 12:01:04,442] Trial 62 finished with value: 0.23436365650963703 and parameters: {'subsample': 0.9574333176186867, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.18564670695369828, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.1963819185824203, 'max_features': 'auto', 'min_impurity_decrease': 7.301362864132341e-06, 'validation_fraction': 0.9275594296798731, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:01:16,277] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9611556459137681, 'learning_rate': 0.009885633504393494, 'dropout_rate': 0.8555425487679464, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.40714661625851756, 'min_weight_fraction_leaf': 0.19157478425569488, 'max_features': 'auto', 'min_impurity_decrease': 1.0767504332570267e-06, 'validation_fraction': 0.9184663621892178, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:01:43,756] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9996724029846231, 'learning_rate': 0.02055321577299183, 'dropout_rate': 0.19552211208698841, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.21641604442433082, 'max_features': 'log2', 'min_impurity_decrease': 7.250192360253865e-06, 'validation_fraction': 0.9272295835693174, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.2289818680697771
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:02:21,447] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.919652344200739, 'learning_rate': 0.014473083324943868, 'dropout_rate': 0.16799591889422819, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.351957844105687, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'auto', 'min_impurity_decrease': 1.7045397927378775e-05, 'validation_fraction': 0.7413345803433677, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658996

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:02:59,127] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8489175059797514, 'learning_rate': 0.008448226967076113, 'dropout_rate': 0.12725750793823018, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.893877768639663, 'min_weight_fraction_leaf': 0.2702972473075093, 'max_features': 'auto', 'min_impurity_decrease': 7.586810829424823e-05, 'validation_fraction': 0.8971088342813041, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:03:25,912] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9594402941587806, 'learning_rate': 0.0039206688180527, 'dropout_rate': 0.25338876644885766, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 1.1787054950134963, 'min_weight_fraction_leaf': 0.29081789854917856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.005146223539456e-06, 'validation_fraction': 0.9662549030476638, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:03:58,714] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.885928079608526, 'learning_rate': 0.01958784726286755, 'dropout_rate': 0.3188313005563145, 'n_estimators': 463, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.24383256255051056, 'max_features': 'auto', 'min_impurity_decrease': 3.057918866616863e-07, 'validation_fraction': 0.99982951588149, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24724158711521824
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:04:31,693] Trial 69 finished with value: 0.23592674084605642 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.011561561592981577, 'dropout_rate': 0.2251092355441408, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 0.30419922755720963, 'min_weight_fraction_leaf': 0.1929901790072115, 'max_features': 'auto', 'min_impurity_decrease': 1.6729804035130242e-06, 'validation_fraction': 0.8450602738806452, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 62 with value: 0.23436365650963703.
Fold 1 IBS: 0.24516581707410637
Fold 2 IBS: 0.229362987548221
Fold 3 IBS: 0.2285150856495683
Fold 4 IBS: 0.2397404288488306
Fold 5 IBS: 0.22776390319047718
[I 2024-04-16 12:04:57,601] Trial 70 finished with value: 0.23410964446224067 and parameters: {'subsample': 0.7327319228005876, 'learning_rate': 0.016866948400001296, 'dropout_rate': 0.17898373444054652, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.01005746855001105, 'min_weight_fraction_leaf': 0.3640638074298326, 'max_features': None, 'min_impurity_decrease': 9.787021311876353e-06, 'validation_fraction': 0.7926074734474466, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.2454369019344366
Fold 2 IBS: 0.23016772493855195
Fold 3 IBS: 0.22866734075144848
Fold 4 IBS: 0.2406555824750769
Fold 5 IBS: 0.22795295445317568
[I 2024-04-16 12:05:20,384] Trial 71 finished with value: 0.2345761009105379 and parameters: {'subsample': 0.6580825781997457, 'learning_rate': 0.016629440896307336, 'dropout_rate': 0.17328978363215145, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.4078164122376511, 'max_features': None, 'min_impurity_decrease': 3.981143358338061e-06, 'validation_fraction': 0.9287047300321795, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.2455804604771737
Fold 2 IBS: 0.23015122616770395
Fold 3 IBS: 0.22864882824644148
Fold 4 IBS: 0.2406032444136894
Fold 5 IBS: 0.22814137040371196
[I 2024-04-16 12:05:42,134] Trial 72 finished with value: 0.2346250259417441 and parameters: {'subsample': 0.6433252951647072, 'learning_rate': 0.015406216424115876, 'dropout_rate': 0.174165060267479, 'n_estimators': 372, 'criterion': 'squared_error', 'ccp_alpha': 0.004831359506118816, 'min_weight_fraction_leaf': 0.4068999670923105, 'max_features': None, 'min_impurity_decrease': 9.143853678722166e-06, 'validation_fraction': 0.8050869160635631, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 12:06:06,027] Trial 73 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6415805639130162, 'learning_rate': 0.016957190070749008, 'dropout_rate': 0.1022557442615895, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 0.7340527434897883, 'min_weight_fraction_leaf': 0.41441154927232665, 'max_features': None, 'min_impurity_decrease': 2.8366918098535655e-05, 'validation_fraction': 0.8120762455660575, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:06:32,123] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5890037439982243, 'learning_rate': 0.02388572819447024, 'dropout_rate': 0.14309816759091956, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.33550183960235097, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': None, 'min_impurity_decrease': 1.1962100920927531e-05, 'validation_fraction': 0.6568048355299513, 'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 17}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 12:06:53,105] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6875143177223235, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.18219557324018512, 'n_estimators': 365, 'criterion': 'squared_error', 'ccp_alpha': 0.6626240923578504, 'min_weight_fraction_leaf': 0.3667876525646178, 'max_features': None, 'min_impurity_decrease': 8.996538110684365e-06, 'validation_fraction': 0.7854387247082943, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:07:16,560] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6310903661182281, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.16070017323462005, 'n_estimators': 383, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.43428922098282363, 'max_features': None, 'min_impurity_decrease': 4.880048865700701e-06, 'validation_fraction': 0.7567620429516432, 'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998

Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 12:07:31,467] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7234820637720293, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.19884799526452568, 'n_estimators': 302, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.4027406894595495, 'max_features': None, 'min_impurity_decrease': 5.35591590419612e-07, 'validation_fraction': 0.8758106078120852, 'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:07:49,497] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6708593402641205, 'learning_rate': 0.02742354559286264, 'dropout_rate': 0.12642193192647372, 'n_estimators': 329, 'criterion': 'squared_error', 'ccp_alpha': 0.2456295975030462, 'min_weight_fraction_leaf': 0.3629864105918121, 'max_features': None, 'min_impurity_decrease': 0.00015140034318578482, 'validation_fraction': 0.6173345703129903, 'min_samples_split': 10, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 70 with value: 0.23410964446224067.
Fold 1 IBS: 0.241851651618776
Fold 2 IBS: 0.225082141185961
Fold 3 IBS: 0.22886330137755048
Fold 4 IBS: 0.23945272971544493
Fold 5 IBS: 0.225546678965891
[I 2024-04-16 12:08:15,918] Trial 79 finished with value: 0.2321593005727247 and parameters: {'subsample': 0.6068487747881667, 'learning_rate': 0.08690058608305122, 'dropout_rate': 0.2202274723306249, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 0.0067848986270052205, 'min_weight_fraction_leaf': 0.442958513823715, 'max_features': None, 'min_impurity_decrease': 3.159003046563375e-05, 'validation_fraction': 0.6916250922837899, 'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 79 with value: 0.2321593005727247.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:08:41,893] Trial 80 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7431452433208791, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.22085807342340602, 'n_estimators': 416, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0208718228969498, 'min_weight_fraction_leaf': 0.4578321580005691, 'max_features': None, 'min_impurity_decrease': 6.219311571999601e-05, 'validation_fraction': 0.8063818584332632, 'min_samples_split': 15, 'max_leaf_nodes': 3, 'min_samples_leaf': 5, 'max_depth': 1}. Best is trial 79 with value: 0.2321593005727247.
Fold 1 IBS: 0.24040275609642484
Fold 2 IBS: 0.22344468173586884
Fold 3 IBS: 0.22846224162930656
Fold 4 IBS: 0.23645999283112776
Fold 5 IBS: 0.22436389610083335
[I 2024-04-16 12:09:10,942] Trial 81 finished with value: 0.23062671367871226 and parameters: {'subsample': 0.6143582554906275, 'learning_rate': 0.09196546766753708, 'dropout_rate': 0.17154122956253648, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.025343486133480444, 'min_weight_fraction_leaf': 0.422923580742715, 'max_features': None, 'min_impurity_decrease': 3.0516618185477245e-05, 'validation_fraction': 0.6839523176227551, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:09:33,814] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6156671358096751, 'learning_rate': 0.09024426530842436, 'dropout_rate': 0.17324784818426983, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 0.5340758841421452, 'min_weight_fraction_leaf': 0.44660441203015316, 'max_features': None, 'min_impurity_decrease': 3.596173256287884e-05, 'validation_fraction': 0.6862764853454645, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:10:08,891] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.59035693752921, 'learning_rate': 0.08769222490327029, 'dropout_rate': 0.13695127070120913, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.29851318725213727, 'min_weight_fraction_leaf': 0.4224884983147852, 'max_features': None, 'min_impurity_decrease': 1.7043338510624665e-05, 'validation_fraction': 0.708718433392457, 'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:10:41,438] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5692772731117001, 'learning_rate': 0.09337007500374273, 'dropout_rate': 0.19406549234317277, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 0.7908292561402825, 'min_weight_fraction_leaf': 0.3834871581332913, 'max_features': None, 'min_impurity_decrease': 2.8122570662289344e-05, 'validation_fraction': 0.9095186934735143, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24230603015357494
Fold 2 IBS: 0.22627075094258225
Fold 3 IBS: 0.22794332453533264
Fold 4 IBS: 0.2379855545919495
Fold 5 IBS: 0.22601443786759767
[I 2024-04-16 12:10:45,457] Trial 85 finished with value: 0.23210401961820742 and parameters: {'subsample': 0.6445419753261435, 'learning_rate': 0.06087928731142127, 'dropout_rate': 0.24518342938103005, 'n_estimators': 132, 'criterion': 'squared_error', 'ccp_alpha': 0.011216734292662366, 'min_weight_fraction_leaf': 0.4043905469812696, 'max_features': None, 'min_impurity_decrease': 1.493590751470447e-05, 'validation_fraction': 0.5742595190050698, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 12:10:49,765] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5345448615448432, 'learning_rate': 0.06299476346040861, 'dropout_rate': 0.16060697827295928, 'n_estimators': 138, 'criterion': 'squared_error', 'ccp_alpha': 0.62448544277789, 'min_weight_fraction_leaf': 0.4834818041059262, 'max_features': None, 'min_impurity_decrease': 1.4511890623038534e-05, 'validation_fraction': 0.531307128627143, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 3}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24187291146832404
Fold 2 IBS: 0.2251821854583426
Fold 3 IBS: 0.2280766922101586
Fold 4 IBS: 0.2375222631191458
Fold 5 IBS: 0.22529950757040032
[I 2024-04-16 12:11:14,181] Trial 87 finished with value: 0.2315907119652743 and parameters: {'subsample': 0.6482886513725954, 'learning_rate': 0.08056151243791008, 'dropout_rate': 0.2600398597942537, 'n_estimators': 374, 'criterion': 'squared_error', 'ccp_alpha': 0.01745937818789605, 'min_weight_fraction_leaf': 0.40356411913419793, 'max_features': None, 'min_impurity_decrease': 9.949241277389102e-06, 'validation_fraction': 0.5582433992805256, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 12:11:16,668] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6879348852579991, 'learning_rate': 0.08209035744510738, 'dropout_rate': 0.24522201083374043, 'n_estimators': 84, 'criterion': 'squared_error', 'ccp_alpha': 0.2983993026610602, 'min_weight_fraction_leaf': 0.3774672254272644, 'max_features': None, 'min_impurity_decrease': 5.4011226362110275e-06, 'validation_fraction': 0.568843188657281, 'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 11}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:11:21,135] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6555693108457097, 'learning_rate': 0.08348043724232247, 'dropout_rate': 0.1018982518393906, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.3922659564335438, 'max_features': None, 'min_impurity_decrease': 1.84353439530822e-05, 'validation_fraction': 0.4550485507485021, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 9}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:11:28,576] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6142534760575815, 'learning_rate': 0.07977183656340979, 'dropout_rate': 0.21675268812215465, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.43931856433894717, 'max_features': None, 'min_impurity_decrease': 4.509029295159726e-05, 'validation_fraction': 0.6255054030515286, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 8}. Best is trial 81 with value: 0.23062671367871226.
Fold 1 IBS: 0.24033659095145252
Fold 2 IBS: 0.22271607873274998
Fold 3 IBS: 0.22784490354997913
Fold 4 IBS: 0.23529399067272844
Fold 5 IBS: 0.22413051884016097
[I 2024-04-16 12:11:55,221] Trial 91 finished with value: 0.2300644165494142 and parameters: {'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24714728680988468
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22893463205005193
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22935673483794422
[I 2024-04-16 12:12:21,099] Trial 92 finished with value: 0.235890661939015 and parameters: {'subsample': 0.5057005214243391, 'learning_rate': 0.09883062819528839, 'dropout_rate': 0.2685922627272655, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.19747740396734947, 'min_weight_fraction_leaf': 0.4679716753672616, 'max_features': None, 'min_impurity_decrease': 1.0671241077127033e-05, 'validation_fraction': 0.5950373519486988, 'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:12:50,456] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5538299448336005, 'learning_rate': 0.0868661642219975, 'dropout_rate': 0.20334468934521452, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.5267007889739713, 'min_weight_fraction_leaf': 0.42336750014808644, 'max_features': None, 'min_impurity_decrease': 8.867094040313709e-05, 'validation_fraction': 0.520690018337254, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:12:56,886] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5702665640439277, 'learning_rate': 0.09449632562825357, 'dropout_rate': 0.13870793304287105, 'n_estimators': 169, 'criterion': 'squared_error', 'ccp_alpha': 0.8492587817200913, 'min_weight_fraction_leaf': 0.348550363613902, 'max_features': None, 'min_impurity_decrease': 6.826272330503328e-06, 'validation_fraction': 0.5659130589721448, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 7, 'max_depth': 12}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:13:21,642] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7076939032161012, 'learning_rate': 0.09136733918164754, 'dropout_rate': 0.18672112900745633, 'n_estimators': 356, 'criterion': 'squared_error', 'ccp_alpha': 0.561945255260577, 'min_weight_fraction_leaf': 0.40234945062950195, 'max_features': None, 'min_impurity_decrease': 2.5588389290979514e-05, 'validation_fraction': 0.4537896994588092, 'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:13:41,379] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6655863757457166, 'learning_rate': 0.08941626520289533, 'dropout_rate': 0.2411336203156454, 'n_estimators': 339, 'criterion': 'squared_error', 'ccp_alpha': 0.23565160101206817, 'min_weight_fraction_leaf': 0.42995214161407835, 'max_features': None, 'min_impurity_decrease': 3.937366373268103e-06, 'validation_fraction': 0.6733503587022674, 'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 16}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 12:13:41,933] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5830397464244746, 'learning_rate': 0.09649030637314325, 'dropout_rate': 0.1548001251941624, 'n_estimators': 44, 'criterion': 'squared_error', 'ccp_alpha': 1.0632556006826448, 'min_weight_fraction_leaf': 0.4466142202394081, 'max_features': 1, 'min_impurity_decrease': 9.319522810040033e-06, 'validation_fraction': 0.49048790135092346, 'min_samples_split': 19, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:14:06,230] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6220799571230118, 'learning_rate': 0.08529012031921517, 'dropout_rate': 0.2588962329024949, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3323104826759427, 'min_weight_fraction_leaf': 0.4570033067989539, 'max_features': None, 'min_impurity_decrease': 1.5778942534009964e-05, 'validation_fraction': 0.5403544212495923, 'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 3}. Best is trial 91 with value: 0.2300644165494142.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 12:14:15,713] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.07813501740629669, 'dropout_rate': 0.30318261654818046, 'n_estimators': 242, 'criterion': 'squared_error', 'ccp_alpha': 1.7079733343503498, 'min_weight_fraction_leaf': 0.32269779176244495, 'max_features': 0.1, 'min_impurity_decrease': 1.276230329676773e-06, 'validation_fraction': 0.36954438153697, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 91 with value: 0.2300644165494142.


* Best trial for IBS:
 FrozenTrial(number=91, state=TrialState.COMPLETE, values=[0.2300644165494142], datetime_start=datetime.datetime(2024, 4, 16, 12, 11, 28, 578408), datetime_complete=datetime.datetime(2024, 4, 16, 12, 11, 55, 221118), params={'subsample': 0.579213280645811, 'learning_rate': 0.09426091382038485, 'dropout_rate': 0.18479264516541616, 'n_estimators': 390, 'criterion': 'squared_error', 'ccp_alpha': 0.03787089343697578, 'min_weight_fraction_leaf': 0.4036747584607865, 'max_features': None, 'min_impurity_decrease': 7.4293259533530295e-06, 'validation_fraction': 0.5325834925366492, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=91, value=None)


* Best Score for IBS:
 0.2300644165494142

In [69]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [70]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.7
train_ibs:  0.23

#### Test

In [71]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [72]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.004507507039685693,
                                 criterion='squared_error',
                                 dropout_rate=0.8022681311855436,
                                 learning_rate=0.010888929954369636,
                                 max_depth=12, max_features='auto',
                                 max_leaf_nodes=3,
                                 min_impurity_decrease=4.0700060224631717e-07,
                                 min_samples_leaf=10, min_samples_split=19,
                                 min_weight_fraction_leaf=0.1685851039915477,
                                 n_estimators=443, random_state=123,
                                 subsample=0.8597838031871279,
                                 validation_fraction=0.8827408742810589)

C-index score: 0.516

GradientBoostingSurvivalAnalysis(ccp_alpha=0.03787089343697578,
                                 criterion='squared_error',
                                 dropout_rate=0.18479264516541616,
                                 learning_rate=0.09426091382038485, max_depth=2,
                                 max_leaf_nodes=6,
                                 min_impurity_decrease=7.4293259533530295e-06,
                                 min_samples_leaf=7, min_samples_split=18,
                                 min_weight_fraction_leaf=0.4036747584607865,
                                 n_estimators=390, random_state=123,
                                 subsample=0.579213280645811,
                                 validation_fraction=0.5325834925366492)

IBS: 0.228

In [73]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [74]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [75]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 12:14:27,430] A new study created in memory with name: no-name-2f1ecc1e-5b30-42a7-bee8-3954efce041d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.49809885931558934
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 12:14:30,951] Trial 0 finished with value: 0.5616995760769923 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.5616995760769923.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 12:14:47,560] Trial 1 finished with value: 0.5579952075331192 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.5616995760769923.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 12:14:52,761] Trial 2 finished with value: 0.5826790527193506 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.5826790527193506.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:14:58,919] Trial 3 finished with value: 0.6038922796023304 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6038922796023304.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.5930232558139535
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:15:07,270] Trial 4 finished with value: 0.6122348614416003 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6122348614416003.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 12:15:20,025] Trial 5 finished with value: 0.5609391198032279 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6122348614416003.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 12:15:25,515] Trial 6 finished with value: 0.5490517320514279 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6122348614416003.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:15:26,973] Trial 7 finished with value: 0.6108829796948088 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6122348614416003.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:15:33,561] Trial 8 finished with value: 0.5993537671612662 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6122348614416003.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:15:48,417] Trial 9 finished with value: 0.6144906031413748 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 9 with value: 0.6144906031413748.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.6330472103004292
[I 2024-04-16 12:16:03,939] Trial 10 finished with value: 0.5627181750000206 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.9974588415748801, 'n_estimators': 496, 'learning_rate': 0.0017980531969980576}. Best is trial 9 with value: 0.6144906031413748.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 12:16:14,982] Trial 11 finished with value: 0.6064540248454893 and parameters: {'subsample': 0.14800086414695102, 'dropout_rate': 0.10580803679784617, 'n_estimators': 338, 'learning_rate': 0.08933703080421439}. Best is trial 9 with value: 0.6144906031413748.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6266094420600858
[I 2024-04-16 12:16:26,100] Trial 12 finished with value: 0.6081345664230324 and parameters: {'subsample': 0.22177105064357905, 'dropout_rate': 0.7161296095061238, 'n_estimators': 352, 'learning_rate': 0.04208126869938818}. Best is trial 9 with value: 0.6144906031413748.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 12:16:36,672] Trial 13 finished with value: 0.6141296753758247 and parameters: {'subsample': 0.31415256531574187, 'dropout_rate': 0.20114226299194976, 'n_estimators': 296, 'learning_rate': 0.09228915933309809}. Best is trial 9 with value: 0.6144906031413748.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:16:56,692] Trial 14 finished with value: 0.6145963754691326 and parameters: {'subsample': 0.3640117027616684, 'dropout_rate': 0.7119492995632404, 'n_estimators': 426, 'learning_rate': 0.09964443263010372}. Best is trial 14 with value: 0.6145963754691326.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:23:39,332] Trial 15 finished with value: 0.6171385537788199 and parameters: {'subsample': 0.39408879774715655, 'dropout_rate': 0.7860661612062939, 'n_estimators': 420, 'learning_rate': 0.09878669756022851}. Best is trial 15 with value: 0.6171385537788199.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:24:21,458] Trial 16 finished with value: 0.6154547445678451 and parameters: {'subsample': 0.3629956613085432, 'dropout_rate': 0.7326988341376399, 'n_estimators': 427, 'learning_rate': 0.09825676628165285}. Best is trial 15 with value: 0.6171385537788199.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5019011406844106
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:24:38,240] Trial 17 finished with value: 0.5928480255753164 and parameters: {'subsample': 0.6278318159798674, 'dropout_rate': 0.8384493320704152, 'n_estimators': 424, 'learning_rate': 0.08390592617578929}. Best is trial 15 with value: 0.6171385537788199.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6266094420600858
[I 2024-04-16 12:25:03,268] Trial 18 finished with value: 0.6141165760391942 and parameters: {'subsample': 0.4083328817338626, 'dropout_rate': 0.6304426278279736, 'n_estimators': 397, 'learning_rate': 0.08235391520182245}. Best is trial 15 with value: 0.6171385537788199.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:25:09,801] Trial 19 finished with value: 0.6220112764895123 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7899863517350085, 'n_estimators': 299, 'learning_rate': 0.09922067979272678}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 12:25:28,347] Trial 20 finished with value: 0.6149476932463551 and parameters: {'subsample': 0.14832473390923503, 'dropout_rate': 0.7933084651006226, 'n_estimators': 291, 'learning_rate': 0.0817175642960023}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 12:25:40,805] Trial 21 finished with value: 0.618335028632908 and parameters: {'subsample': 0.11460779950448041, 'dropout_rate': 0.7907406860744977, 'n_estimators': 442, 'learning_rate': 0.09511750585282995}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6223175965665236
[I 2024-04-16 12:26:03,356] Trial 22 finished with value: 0.6135182359409621 and parameters: {'subsample': 0.10322253994980501, 'dropout_rate': 0.9771748263377964, 'n_estimators': 384, 'learning_rate': 0.09950947642265613}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:26:25,344] Trial 23 finished with value: 0.6082576791224494 and parameters: {'subsample': 0.22043255432774178, 'dropout_rate': 0.5763043643030875, 'n_estimators': 318, 'learning_rate': 0.08928000515216827}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 12:26:43,359] Trial 24 finished with value: 0.6176609047402648 and parameters: {'subsample': 0.10048817787073024, 'dropout_rate': 0.7887669679653863, 'n_estimators': 454, 'learning_rate': 0.09143177428978365}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:27:14,187] Trial 25 finished with value: 0.6135645039360942 and parameters: {'subsample': 0.19024836744082047, 'dropout_rate': 0.9164726203657018, 'n_estimators': 452, 'learning_rate': 0.07831919869747611}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:27:32,992] Trial 26 finished with value: 0.6180668697216867 and parameters: {'subsample': 0.10331872076553024, 'dropout_rate': 0.7881627860833683, 'n_estimators': 245, 'learning_rate': 0.06805754094520033}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:27:38,546] Trial 27 finished with value: 0.6176974310848908 and parameters: {'subsample': 0.2600290087577237, 'dropout_rate': 0.6340112818214192, 'n_estimators': 248, 'learning_rate': 0.06426653132618093}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 12:27:41,363] Trial 28 finished with value: 0.6138857681144148 and parameters: {'subsample': 0.1681102321808753, 'dropout_rate': 0.8528818052986153, 'n_estimators': 125, 'learning_rate': 0.06687129541605094}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 12:27:42,043] Trial 29 finished with value: 0.5425465011802781 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.9430576733480622, 'n_estimators': 28, 'learning_rate': 0.06046208382653473}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6356589147286822
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 12:28:07,387] Trial 30 finished with value: 0.6149273193766797 and parameters: {'subsample': 0.11172942297459405, 'dropout_rate': 0.5722033379107796, 'n_estimators': 129, 'learning_rate': 0.016814619253793885}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:37:17,211] Trial 31 finished with value: 0.620657852474808 and parameters: {'subsample': 0.28768044353640015, 'dropout_rate': 0.6483063687102298, 'n_estimators': 249, 'learning_rate': 0.060506543910742915}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:37:24,984] Trial 32 finished with value: 0.6197994833760955 and parameters: {'subsample': 0.28381802945268464, 'dropout_rate': 0.7597346990020082, 'n_estimators': 239, 'learning_rate': 0.0731475678905027}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:37:29,208] Trial 33 finished with value: 0.6205889908561744 and parameters: {'subsample': 0.28375960802245515, 'dropout_rate': 0.6782787016581171, 'n_estimators': 147, 'learning_rate': 0.07298545391962367}. Best is trial 19 with value: 0.6220112764895123.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:37:36,002] Trial 34 finished with value: 0.6224200517311609 and parameters: {'subsample': 0.2872345049580309, 'dropout_rate': 0.5051054684842515, 'n_estimators': 151, 'learning_rate': 0.07339961060601945}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.4828897338403042
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:37:38,728] Trial 35 finished with value: 0.5917209874853999 and parameters: {'subsample': 0.44531889703598726, 'dropout_rate': 0.4903442432295797, 'n_estimators': 88, 'learning_rate': 0.055828574199632074}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5209125475285171
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 12:37:43,279] Trial 36 finished with value: 0.5671206828182902 and parameters: {'subsample': 0.5781848696626097, 'dropout_rate': 0.42504221478450555, 'n_estimators': 155, 'learning_rate': 0.07480700775203325}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 12:37:46,207] Trial 37 finished with value: 0.6151073058421084 and parameters: {'subsample': 0.2920693373805513, 'dropout_rate': 0.32064486547669635, 'n_estimators': 98, 'learning_rate': 0.04326698602032029}. Best is trial 34 with value: 0.6224200517311609.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:37:51,082] Trial 38 finished with value: 0.6050714027993809 and parameters: {'subsample': 0.32074245257465167, 'dropout_rate': 0.6651715070515323, 'n_estimators': 193, 'learning_rate': 0.05829099053748285}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6266094420600858
[I 2024-04-16 12:37:55,131] Trial 39 finished with value: 0.6105212803250335 and parameters: {'subsample': 0.21722131972898429, 'dropout_rate': 0.5162237099413767, 'n_estimators': 159, 'learning_rate': 0.0725264899995596}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5437262357414449
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:38:01,026] Trial 40 finished with value: 0.5932091881688971 and parameters: {'subsample': 0.5486351151930511, 'dropout_rate': 0.35300917093402917, 'n_estimators': 221, 'learning_rate': 0.047524274997714416}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:38:08,868] Trial 41 finished with value: 0.6040328794984962 and parameters: {'subsample': 0.27305234192685357, 'dropout_rate': 0.6259851643529344, 'n_estimators': 271, 'learning_rate': 0.07187988192194965}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 12:38:10,937] Trial 42 finished with value: 0.5910230566476848 and parameters: {'subsample': 0.4396306795374554, 'dropout_rate': 0.6954623000860509, 'n_estimators': 64, 'learning_rate': 0.07684461328883248}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:38:18,031] Trial 43 finished with value: 0.622402013704521 and parameters: {'subsample': 0.25128275517100473, 'dropout_rate': 0.742663123299748, 'n_estimators': 228, 'learning_rate': 0.06350463155093221}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.6007751937984496
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:38:23,434] Trial 44 finished with value: 0.6144729923617843 and parameters: {'subsample': 0.18573762790231166, 'dropout_rate': 0.6044899086471134, 'n_estimators': 217, 'learning_rate': 0.06291820700365029}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:38:27,905] Trial 45 finished with value: 0.6134577569353891 and parameters: {'subsample': 0.33171411128657535, 'dropout_rate': 0.66691515069497, 'n_estimators': 168, 'learning_rate': 0.05273679269733128}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:38:31,717] Trial 46 finished with value: 0.6200552372016739 and parameters: {'subsample': 0.24628769012991808, 'dropout_rate': 0.5383724314247292, 'n_estimators': 143, 'learning_rate': 0.06866545188305799}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:38:38,537] Trial 47 finished with value: 0.6115570132039462 and parameters: {'subsample': 0.2377141956482313, 'dropout_rate': 0.7411038962786083, 'n_estimators': 195, 'learning_rate': 0.08527053882261267}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:38:47,636] Trial 48 finished with value: 0.6106490920424087 and parameters: {'subsample': 0.34211460129420834, 'dropout_rate': 0.4674073633809642, 'n_estimators': 279, 'learning_rate': 0.037322822074959586}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5665399239543726
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:38:57,308] Trial 49 finished with value: 0.6168846223123012 and parameters: {'subsample': 0.41902847635402285, 'dropout_rate': 0.8347217154069448, 'n_estimators': 316, 'learning_rate': 0.04837825332707669}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5399239543726235
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:39:07,568] Trial 50 finished with value: 0.60042766886045 and parameters: {'subsample': 0.47670374152096184, 'dropout_rate': 0.42732372125147283, 'n_estimators': 307, 'learning_rate': 0.0586710130321589}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:39:12,488] Trial 51 finished with value: 0.6145101800888749 and parameters: {'subsample': 0.2557066875302191, 'dropout_rate': 0.5346568894221453, 'n_estimators': 137, 'learning_rate': 0.0661967596753789}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:39:18,856] Trial 52 finished with value: 0.6183632750356616 and parameters: {'subsample': 0.1910565418778623, 'dropout_rate': 0.5872422907476271, 'n_estimators': 180, 'learning_rate': 0.07030877240370344}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.6266094420600858
[I 2024-04-16 12:39:22,657] Trial 53 finished with value: 0.6120523713963925 and parameters: {'subsample': 0.38009593681563614, 'dropout_rate': 0.49913809716020974, 'n_estimators': 110, 'learning_rate': 0.07840842188940783}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:39:25,638] Trial 54 finished with value: 0.5990833028949675 and parameters: {'subsample': 0.30393557568070756, 'dropout_rate': 0.6845717839230432, 'n_estimators': 76, 'learning_rate': 0.05613621475337917}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:39:33,446] Trial 55 finished with value: 0.6192395387399174 and parameters: {'subsample': 0.1480381860736912, 'dropout_rate': 0.5433155988861783, 'n_estimators': 223, 'learning_rate': 0.06267887558734277}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:39:38,313] Trial 56 finished with value: 0.6191968681029615 and parameters: {'subsample': 0.2457123476291894, 'dropout_rate': 0.6431254182610682, 'n_estimators': 147, 'learning_rate': 0.08563399654683987}. Best is trial 34 with value: 0.6224200517311609.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6550387596899225
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:39:49,560] Trial 57 finished with value: 0.6168695117084965 and parameters: {'subsample': 0.3520511251578655, 'dropout_rate': 0.7534647491792168, 'n_estimators': 337, 'learning_rate': 0.06921059228698109}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.4752851711026616
Fold 5 C-index: 0.6201716738197425
[I 2024-04-16 12:39:55,810] Trial 58 finished with value: 0.5618176894982364 and parameters: {'subsample': 0.7591484265070766, 'dropout_rate': 0.8770223988386677, 'n_estimators': 199, 'learning_rate': 0.05336246804120767}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6162790697674418
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:40:04,994] Trial 59 finished with value: 0.618559100685558 and parameters: {'subsample': 0.19503247679467187, 'dropout_rate': 0.8262625031143984, 'n_estimators': 270, 'learning_rate': 0.07829461448228939}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6266094420600858
[I 2024-04-16 12:40:14,628] Trial 60 finished with value: 0.6105576368002733 and parameters: {'subsample': 0.22016860703361402, 'dropout_rate': 0.7108907216246763, 'n_estimators': 236, 'learning_rate': 0.037667655525589566}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:40:30,214] Trial 61 finished with value: 0.6136841791326931 and parameters: {'subsample': 0.29713377313703293, 'dropout_rate': 0.7585021613585606, 'n_estimators': 255, 'learning_rate': 0.07402814773038838}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:40:42,856] Trial 62 finished with value: 0.6197994833760955 and parameters: {'subsample': 0.2818148260090159, 'dropout_rate': 0.7241541361148631, 'n_estimators': 239, 'learning_rate': 0.06759268593285006}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6395348837209303
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 12:40:52,364] Trial 63 finished with value: 0.6147239180499267 and parameters: {'subsample': 0.14274451767291874, 'dropout_rate': 0.5954830963086882, 'n_estimators': 286, 'learning_rate': 0.08020739034610208}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6361702127659574
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:40:57,889] Trial 64 finished with value: 0.6063550233910271 and parameters: {'subsample': 0.3921216085087726, 'dropout_rate': 0.8176289325515855, 'n_estimators': 175, 'learning_rate': 0.08799468678769942}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.6046511627906976
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:41:04,962] Trial 65 finished with value: 0.6160255589626011 and parameters: {'subsample': 0.3275572516662042, 'dropout_rate': 0.7597464202278386, 'n_estimators': 209, 'learning_rate': 0.06497059977828495}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5258964143426295
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:41:13,449] Trial 66 finished with value: 0.5968615647574603 and parameters: {'subsample': 0.2743443400568999, 'dropout_rate': 0.6555306758598545, 'n_estimators': 259, 'learning_rate': 0.09398806864546615}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:41:17,096] Trial 67 finished with value: 0.6074319421539658 and parameters: {'subsample': 0.22753825630659458, 'dropout_rate': 0.8893537420248085, 'n_estimators': 113, 'learning_rate': 0.06041936870596521}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:41:28,553] Trial 68 finished with value: 0.6146942882940809 and parameters: {'subsample': 0.3666647780085531, 'dropout_rate': 0.5634907051959339, 'n_estimators': 371, 'learning_rate': 0.07126073929985839}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:41:38,194] Trial 69 finished with value: 0.6128072047431881 and parameters: {'subsample': 0.1686182773080861, 'dropout_rate': 0.6184824942902617, 'n_estimators': 296, 'learning_rate': 0.07452010352952768}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.45627376425855515
Fold 5 C-index: 0.5321888412017167
[I 2024-04-16 12:41:43,168] Trial 70 finished with value: 0.5425465011802781 and parameters: {'subsample': 0.9847790608248583, 'dropout_rate': 0.6994011380385406, 'n_estimators': 138, 'learning_rate': 0.008127880939407618}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:41:50,519] Trial 71 finished with value: 0.6143298888858395 and parameters: {'subsample': 0.27651412063373193, 'dropout_rate': 0.7269777217130985, 'n_estimators': 225, 'learning_rate': 0.06759057514695066}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:41:57,925] Trial 72 finished with value: 0.6146759698454811 and parameters: {'subsample': 0.2988718168667681, 'dropout_rate': 0.8065635875861832, 'n_estimators': 241, 'learning_rate': 0.06580849784156395}. Best is trial 34 with value: 0.6224200517311609.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:42:03,774] Trial 73 finished with value: 0.6224383701797607 and parameters: {'subsample': 0.2458618277215654, 'dropout_rate': 0.7701139414981615, 'n_estimators': 185, 'learning_rate': 0.08116104600395319}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.624031007751938
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:42:08,552] Trial 74 finished with value: 0.6199321245022571 and parameters: {'subsample': 0.25055308313530283, 'dropout_rate': 0.7718870468549385, 'n_estimators': 156, 'learning_rate': 0.08187931756570656}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.6472868217054264
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 12:42:14,890] Trial 75 finished with value: 0.6093094058923046 and parameters: {'subsample': 0.12833412964541133, 'dropout_rate': 0.8640419805839678, 'n_estimators': 167, 'learning_rate': 0.08103025878355304}. Best is trial 73 with value: 0.6224383701797607.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 12:42:21,233] Trial 76 finished with value: 0.6162840624602431 and parameters: {'subsample': 0.19982432718441756, 'dropout_rate': 0.7771235741701813, 'n_estimators': 183, 'learning_rate': 0.09534814723213371}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.5581395348837209
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:42:26,454] Trial 77 finished with value: 0.6053918192915889 and parameters: {'subsample': 0.24159430234619053, 'dropout_rate': 0.6915680189290592, 'n_estimators': 147, 'learning_rate': 0.08356046619323207}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5968992248062015
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 12:42:30,269] Trial 78 finished with value: 0.6122272857647437 and parameters: {'subsample': 0.16302072462776218, 'dropout_rate': 0.5154969619057388, 'n_estimators': 121, 'learning_rate': 0.08751040424604349}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 12:42:33,668] Trial 79 finished with value: 0.5979787254673579 and parameters: {'subsample': 0.3166339220747283, 'dropout_rate': 0.37625708634004873, 'n_estimators': 102, 'learning_rate': 0.07592434340863276}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.5096899224806202
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.49429657794676807
Fold 5 C-index: 0.6244635193133047
[I 2024-04-16 12:42:39,960] Trial 80 finished with value: 0.5617974889019404 and parameters: {'subsample': 0.683412616900099, 'dropout_rate': 0.45330987207245177, 'n_estimators': 186, 'learning_rate': 0.09224210234624537}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:42:46,489] Trial 81 finished with value: 0.6208846820809069 and parameters: {'subsample': 0.25459998841918474, 'dropout_rate': 0.7714492686734928, 'n_estimators': 202, 'learning_rate': 0.071464762432056}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.627906976744186
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:42:54,747] Trial 82 finished with value: 0.6208846820809069 and parameters: {'subsample': 0.25564331813921143, 'dropout_rate': 0.7729227414662975, 'n_estimators': 209, 'learning_rate': 0.07089437358970246}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:43:02,379] Trial 83 finished with value: 0.6161678311866952 and parameters: {'subsample': 0.21180867205747894, 'dropout_rate': 0.735572715008727, 'n_estimators': 203, 'learning_rate': 0.0692402614218835}. Best is trial 73 with value: 0.6224383701797607.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:43:13,131] Trial 84 finished with value: 0.6268977120875324 and parameters: {'subsample': 0.2574863330898947, 'dropout_rate': 0.9244666566793354, 'n_estimators': 214, 'learning_rate': 0.06103705956604561}. Best is trial 84 with value: 0.6268977120875324.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5627376425855514
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:43:26,337] Trial 85 finished with value: 0.6018353802284537 and parameters: {'subsample': 0.3492946110105307, 'dropout_rate': 0.9274124308880509, 'n_estimators': 231, 'learning_rate': 0.05828190955146055}. Best is trial 84 with value: 0.6268977120875324.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.5852713178294574
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:43:38,026] Trial 86 finished with value: 0.6074860662479141 and parameters: {'subsample': 0.17264812937524862, 'dropout_rate': 0.956022299119552, 'n_estimators': 167, 'learning_rate': 0.06328675985306118}. Best is trial 84 with value: 0.6268977120875324.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:43:52,577] Trial 87 finished with value: 0.6099135552211534 and parameters: {'subsample': 0.31084326031103504, 'dropout_rate': 0.8504731500935819, 'n_estimators': 209, 'learning_rate': 0.07669085304963011}. Best is trial 84 with value: 0.6268977120875324.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 12:44:04,833] Trial 88 finished with value: 0.6287375629843742 and parameters: {'subsample': 0.2675684730129006, 'dropout_rate': 0.9935428319162685, 'n_estimators': 191, 'learning_rate': 0.059793836458530994}. Best is trial 88 with value: 0.6287375629843742.
Fold 1 C-index: 0.5358565737051793
Fold 2 C-index: 0.6065891472868217
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5361216730038023
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:44:23,452] Trial 89 finished with value: 0.5916882756213686 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.9953324130440065, 'n_estimators': 258, 'learning_rate': 0.04894690398708639}. Best is trial 88 with value: 0.6287375629843742.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 12:44:37,943] Trial 90 finished with value: 0.6303311884823822 and parameters: {'subsample': 0.2624985253235916, 'dropout_rate': 0.9679593679379627, 'n_estimators': 218, 'learning_rate': 0.058079531447075304}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 12:44:49,993] Trial 91 finished with value: 0.6287375629843742 and parameters: {'subsample': 0.264562330358844, 'dropout_rate': 0.9653721939583794, 'n_estimators': 195, 'learning_rate': 0.060393625892637276}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:45:01,826] Trial 92 finished with value: 0.6139043569709458 and parameters: {'subsample': 0.23032234447285718, 'dropout_rate': 0.9643143156410573, 'n_estimators': 196, 'learning_rate': 0.05490909974830207}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:45:18,691] Trial 93 finished with value: 0.6268977120875324 and parameters: {'subsample': 0.2568805377638092, 'dropout_rate': 0.9314613090988786, 'n_estimators': 213, 'learning_rate': 0.058369427175513314}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 12:45:33,022] Trial 94 finished with value: 0.6179315151959781 and parameters: {'subsample': 0.20814515972750236, 'dropout_rate': 0.9101681615753094, 'n_estimators': 187, 'learning_rate': 0.052335196844450385}. Best is trial 90 with value: 0.6303311884823822.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.5891472868217055
Fold 3 C-index: 0.6404255319148936
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:45:47,714] Trial 95 finished with value: 0.6039097667990793 and parameters: {'subsample': 0.33313844233705114, 'dropout_rate': 0.9297315519643073, 'n_estimators': 217, 'learning_rate': 0.05680153088738638}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6589147286821705
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6523605150214592
[I 2024-04-16 12:46:03,022] Trial 96 finished with value: 0.6295707322086179 and parameters: {'subsample': 0.26700179897015797, 'dropout_rate': 0.9984999103266156, 'n_estimators': 228, 'learning_rate': 0.06116596739941159}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.6124031007751938
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6007604562737643
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 12:46:20,798] Trial 97 finished with value: 0.6128072047431881 and parameters: {'subsample': 0.18154268162369758, 'dropout_rate': 0.9832458610560899, 'n_estimators': 223, 'learning_rate': 0.05059076901551338}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.6317829457364341
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 12:46:41,746] Trial 98 finished with value: 0.6132720105421283 and parameters: {'subsample': 0.13235696155841664, 'dropout_rate': 0.9462364020636557, 'n_estimators': 232, 'learning_rate': 0.0616240666966083}. Best is trial 90 with value: 0.6303311884823822.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.6085271317829457
Fold 3 C-index: 0.6446808510638298
Fold 4 C-index: 0.5665399239543726

[I 2024-04-16 12:47:00,907] A new study created in memory with name: no-name-5750d0bb-1794-4d50-b260-e191c36441e1

Fold 5 C-index: 0.6351931330472103
[I 2024-04-16 12:47:00,887] Trial 99 finished with value: 0.6168846223123012 and parameters: {'subsample': 0.4189860025467703, 'dropout_rate': 0.8935051973754019, 'n_estimators': 278, 'learning_rate': 0.04675566477513104}. Best is trial 90 with value: 0.6303311884823822.


* Best trial for C-index:
 FrozenTrial(number=90, state=TrialState.COMPLETE, values=[0.6303311884823822], datetime_start=datetime.datetime(2024, 4, 16, 12, 44, 23, 464436), datetime_complete=datetime.datetime(2024, 4, 16, 12, 44, 37, 941114), params={'subsample': 0.2624985253235916, 'dropout_rate': 0.9679593679379627, 'n_estimators': 218, 'learning_rate': 0.058079531447075304}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=90, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.2624985253235916, 'dropout_rate': 0.9679593679379627, 'n_estimators': 218, 'learning_rate': 0.058079531447075304}


* Best Score for C-index:
 0.6303311884823822

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2768605959166274
Fold 2 IBS: 0.3002240901900513
Fold 3 IBS: 0.20816241232849142
Fold 4 IBS: 0.31269202699034615
Fold 5 IBS: 0.23049650269649638
[I 2024-04-16 12:47:10,897] Trial 0 finished with value: 0.26568712562440255 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.26568712562440255.
Fold 1 IBS: 0.3314083926697305
Fold 2 IBS: 0.3801225465459666
Fold 3 IBS: 0.26584323394581666
Fold 4 IBS: 0.45802850446520443
Fold 5 IBS: 0.339376702626222
[I 2024-04-16 12:47:57,488] Trial 1 finished with value: 0.35495587605058804 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.26568712562440255.
Fold 1 IBS: 0.30929438977780943
Fold 2 IBS: 0.3776592383257721
Fold 3 IBS: 0.23159598205222015
Fold 4 IBS: 0.38240606463412674
Fold 5 IBS: 0.3072867135425469
[I 2024-04-16 12:48:12,362] Trial 2 finished with value: 0.32164847766649507 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.26568712562440255.
Fold 1 IBS: 0.3102839061707228
Fold 2 IBS: 0.3783699302877189
Fold 3 IBS: 0.23826415829830536
Fold 4 IBS: 0.3896106574297478
Fold 5 IBS: 0.2668088103396718
[I 2024-04-16 12:48:32,189] Trial 3 finished with value: 0.31666749250523335 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.26568712562440255.
Fold 1 IBS: 0.31401161830186947
Fold 2 IBS: 0.3791289617181479
Fold 3 IBS: 0.24921821613380954
Fold 4 IBS: 0.37803497587349316
Fold 5 IBS: 0.2774918111584465
[I 2024-04-16 12:48:54,518] Trial 4 finished with value: 0.3195771166371534 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.26568712562440255.
Fold 1 IBS: 0.3332145305423825
Fold 2 IBS: 0.38011990649983673
Fold 3 IBS: 0.25198997521142397
Fold 4 IBS: 0.44062878079630075
Fold 5 IBS: 0.33923818447315957
[I 2024-04-16 12:49:36,116] Trial 5 finished with value: 0.3490382755046207 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.26568712562440255.
Fold 1 IBS: 0.2583770894605203
Fold 2 IBS: 0.2538208871784848
Fold 3 IBS: 0.20728964004289857
Fold 4 IBS: 0.2958332286542107
Fold 5 IBS: 0.21760040361445157
[I 2024-04-16 12:49:56,630] Trial 6 finished with value: 0.24658424979011317 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.24658424979011317.
Fold 1 IBS: 0.24449081430179984
Fold 2 IBS: 0.23006896862415954
Fold 3 IBS: 0.21843183660549986
Fold 4 IBS: 0.26408050984406706
Fold 5 IBS: 0.21565801303901247
[I 2024-04-16 12:50:02,445] Trial 7 finished with value: 0.23454602848290773 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.2751545489394562
Fold 2 IBS: 0.31722578035710736
Fold 3 IBS: 0.2145310231981918
Fold 4 IBS: 0.31093129007057974
Fold 5 IBS: 0.2255234148861756
[I 2024-04-16 12:50:25,475] Trial 8 finished with value: 0.26867321149030216 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.3186596408140118
Fold 2 IBS: 0.38012170435921
Fold 3 IBS: 0.2744945823733866
Fold 4 IBS: 0.44220894914233844
Fold 5 IBS: 0.33899745307321766
[I 2024-04-16 12:51:08,105] Trial 9 finished with value: 0.3508964659524329 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.2470353461515696
Fold 2 IBS: 0.23180355778544998
Fold 3 IBS: 0.22856182093970995
Fold 4 IBS: 0.24232908392234695
Fold 5 IBS: 0.22906264846898927
[I 2024-04-16 12:51:10,772] Trial 10 finished with value: 0.23575849145361313 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.24639976969987745
Fold 2 IBS: 0.2310684912926093
Fold 3 IBS: 0.2272817268275755
Fold 4 IBS: 0.2435823646581995
Fold 5 IBS: 0.2279748608955893
[I 2024-04-16 12:51:11,575] Trial 11 finished with value: 0.2352614426747702 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.2515158071334219
Fold 2 IBS: 0.24327023415038398
Fold 3 IBS: 0.20627804410410866
Fold 4 IBS: 0.2908990724168824
Fold 5 IBS: 0.20562950345726422
[I 2024-04-16 12:51:15,834] Trial 12 finished with value: 0.2395185322524122 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.24595650697573987
Fold 2 IBS: 0.23053875457031342
Fold 3 IBS: 0.22629108962368527
Fold 4 IBS: 0.24464866387650103
Fold 5 IBS: 0.2271234075322375
[I 2024-04-16 12:51:16,615] Trial 13 finished with value: 0.2349116845156954 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.2490836201334585
Fold 2 IBS: 0.24389005424872692
Fold 3 IBS: 0.21631889499877097
Fold 4 IBS: 0.27921969309255895
Fold 5 IBS: 0.20885849113585772
[I 2024-04-16 12:51:24,104] Trial 14 finished with value: 0.23947415072187464 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.28000973168191573
Fold 2 IBS: 0.350352008883822
Fold 3 IBS: 0.23409551626163305
Fold 4 IBS: 0.31918142965981416
Fold 5 IBS: 0.21936693280885095
[I 2024-04-16 12:51:31,939] Trial 15 finished with value: 0.2806011238592072 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.29028396141030327
Fold 2 IBS: 0.3428881129745934
Fold 3 IBS: 0.21977846646504287
Fold 4 IBS: 0.3311704934181146
Fold 5 IBS: 0.22673865598383972
[I 2024-04-16 12:51:53,938] Trial 16 finished with value: 0.28217193805037877 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.23454602848290773.
Fold 1 IBS: 0.24417753569669493
Fold 2 IBS: 0.22851981082417397
Fold 3 IBS: 0.22026795046171047
Fold 4 IBS: 0.25338932974320866
Fold 5 IBS: 0.22198742696468415
[I 2024-04-16 12:51:59,004] Trial 17 finished with value: 0.23366841073809447 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.23366841073809447.
Fold 1 IBS: 0.2546743281324155
Fold 2 IBS: 0.24749605342701395
Fold 3 IBS: 0.20600928292977969
Fold 4 IBS: 0.291632547923045
Fold 5 IBS: 0.21624465931312048
[I 2024-04-16 12:52:27,160] Trial 18 finished with value: 0.24321137434507492 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.23366841073809447.
Fold 1 IBS: 0.2464113166183664

Fold 2 IBS: 0.2377390144376664
Fold 3 IBS: 0.21463933220734727
Fold 4 IBS: 0.27663826205330905
Fold 5 IBS: 0.2106178963363044
[I 2024-04-16 12:52:40,534] Trial 19 finished with value: 0.2372091643305987 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.23366841073809447.
Fold 1 IBS: 0.2446002185537661
Fold 2 IBS: 0.2287303136536246
Fold 3 IBS: 0.22126078534246113
Fold 4 IBS: 0.2503656854206287
Fold 5 IBS: 0.22296335334244682
[I 2024-04-16 12:52:45,618] Trial 20 finished with value: 0.23358407126258549 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24513654608372853
Fold 2 IBS: 0.229342015383954
Fold 3 IBS: 0.2235268797861896
Fold 4 IBS: 0.24775662996829356
Fold 5 IBS: 0.22475950483168106
[I 2024-04-16 12:52:52,205] Trial 21 finished with value: 0.23410431521076935 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24676894104572716
Fold 2 IBS: 0.23146619746833758
Fold 3 IBS: 0.22794831370893034
Fold 4 IBS: 0.24282708847425158
Fold 5 IBS: 0.22854475671534727
[I 2024-04-16 12:52:57,613] Trial 22 finished with value: 0.2355110594825188 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24490905621214568
Fold 2 IBS: 0.2307522956908903
Fold 3 IBS: 0.21327642599177393
Fold 4 IBS: 0.26846092437721764
Fold 5 IBS: 0.21681196041619413
[I 2024-04-16 12:53:08,669] Trial 23 finished with value: 0.23484213253764435 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24423622690142718
Fold 2 IBS: 0.22856015173538477
Fold 3 IBS: 0.22152266867721593
Fold 4 IBS: 0.25236306799820424
Fold 5 IBS: 0.22209682009858056
[I 2024-04-16 12:53:15,123] Trial 24 finished with value: 0.23375578708216257 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.249850146996592
Fold 2 IBS: 0.2383467153313154
Fold 3 IBS: 0.2083051970248939
Fold 4 IBS: 0.28368561146720445
Fold 5 IBS: 0.21494656861182862
[I 2024-04-16 12:53:27,191] Trial 25 finished with value: 0.23902684788636686 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.2748697538232193
Fold 2 IBS: 0.3108607166355892
Fold 3 IBS: 0.21047766890395617
Fold 4 IBS: 0.3133209466686309
Fold 5 IBS: 0.23089980793452003
[I 2024-04-16 12:53:42,570] Trial 26 finished with value: 0.2680857787931831 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.2446360248279642
Fold 2 IBS: 0.22905568784138206
Fold 3 IBS: 0.22262573135232494
Fold 4 IBS: 0.24944291232638682
Fold 5 IBS: 0.22412408102172918
[I 2024-04-16 12:53:46,323] Trial 27 finished with value: 0.23397688747395745 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24473645770003374
Fold 2 IBS: 0.2289158691164661
Fold 3 IBS: 0.22276101613545607
Fold 4 IBS: 0.24937343715664392
Fold 5 IBS: 0.22355537486256197
[I 2024-04-16 12:53:53,545] Trial 28 finished with value: 0.23386843099423235 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.26109329211485377
Fold 2 IBS: 0.2653598507237146
Fold 3 IBS: 0.2053050556222368
Fold 4 IBS: 0.2997127426236149
Fold 5 IBS: 0.2191916167333354
[I 2024-04-16 12:54:04,192] Trial 29 finished with value: 0.2501325115635511 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.26161896430958
Fold 2 IBS: 0.2615984983790391
Fold 3 IBS: 0.20457212614709605
Fold 4 IBS: 0.29885775349826127
Fold 5 IBS: 0.22237679615468514
[I 2024-04-16 12:54:18,538] Trial 30 finished with value: 0.24980482769773232 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24486869219322877
Fold 2 IBS: 0.22916959811402832
Fold 3 IBS: 0.2233569305502215
Fold 4 IBS: 0.24824926164659877
Fold 5 IBS: 0.224261691694723
[I 2024-04-16 12:54:27,914] Trial 31 finished with value: 0.23398123483976008 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24498377635507193
Fold 2 IBS: 0.22941875066565157
Fold 3 IBS: 0.22339890945219604
Fold 4 IBS: 0.24759731074612246
Fold 5 IBS: 0.2250266395311026
[I 2024-04-16 12:54:30,761] Trial 32 finished with value: 0.23408507735002893 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24586780553774673
Fold 2 IBS: 0.229603103296698
Fold 3 IBS: 0.22517754683232483
Fold 4 IBS: 0.24694000137177421
Fold 5 IBS: 0.22529050594067554
[I 2024-04-16 12:54:35,745] Trial 33 finished with value: 0.23457579259584388 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.2449812430476309
Fold 2 IBS: 0.2308750574556347
Fold 3 IBS: 0.2147577742870371
Fold 4 IBS: 0.2691711011431689
Fold 5 IBS: 0.21573715387892148
[I 2024-04-16 12:54:45,892] Trial 34 finished with value: 0.23510446596247864 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.2468610087668775
Fold 2 IBS: 0.23163540208577946
Fold 3 IBS: 0.22825550078025933
Fold 4 IBS: 0.24260840290920135
Fold 5 IBS: 0.22880705481434943
[I 2024-04-16 12:54:47,009] Trial 35 finished with value: 0.23563347387129344 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.29726185669915756
Fold 2 IBS: 0.36921678785232154
Fold 3 IBS: 0.22359897607366588
Fold 4 IBS: 0.3558379623990645
Fold 5 IBS: 0.27885006437703086
[I 2024-04-16 12:55:16,887] Trial 36 finished with value: 0.30495312948024805 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.3127744362175441
Fold 2 IBS: 0.3794076818469332
Fold 3 IBS: 0.258232194712534
Fold 4 IBS: 0.39581272723846544
Fold 5 IBS: 0.3250429368758641
[I 2024-04-16 12:55:36,218] Trial 37 finished with value: 0.33425399537826816 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24533193500022885

Fold 2 IBS: 0.23176181617690036
Fold 3 IBS: 0.21313003884668746
Fold 4 IBS: 0.272329564225104
Fold 5 IBS: 0.21452948232254365
[I 2024-04-16 12:55:49,434] Trial 38 finished with value: 0.23541656731429286 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.25621592862736614
Fold 2 IBS: 0.24945107894683533
Fold 3 IBS: 0.20677924290740515
Fold 4 IBS: 0.29281749501751253
Fold 5 IBS: 0.2129039571292548
[I 2024-04-16 12:55:58,343] Trial 39 finished with value: 0.2436335405256748 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.25624408670891335
Fold 2 IBS: 0.251287937820606
Fold 3 IBS: 0.20576959720528976
Fold 4 IBS: 0.2931627161055081
Fold 5 IBS: 0.21621506896582623
[I 2024-04-16 12:56:14,387] Trial 40 finished with value: 0.2445358813612287 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24436763209820364
Fold 2 IBS: 0.2287167802732215
Fold 3 IBS: 0.22153132052308366
Fold 4 IBS: 0.25127217874071295
Fold 5 IBS: 0.22305394137944842
[I 2024-04-16 12:56:21,141] Trial 41 finished with value: 0.23378837060293406 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24476457110519556
Fold 2 IBS: 0.22916244774972433
Fold 3 IBS: 0.22301679072004227
Fold 4 IBS: 0.24876678788664583
Fold 5 IBS: 0.22443185693393544
[I 2024-04-16 12:56:25,317] Trial 42 finished with value: 0.23402849087910868 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.246304806211056
Fold 2 IBS: 0.2330025133797744
Fold 3 IBS: 0.21145068524879307
Fold 4 IBS: 0.27512950258281227
Fold 5 IBS: 0.21555356517567764
[I 2024-04-16 12:56:36,546] Trial 43 finished with value: 0.2362882145196227 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24606543093740316
Fold 2 IBS: 0.23074625591545228
Fold 3 IBS: 0.22670035640743874
Fold 4 IBS: 0.24430642092349134
Fold 5 IBS: 0.22747450680060574
[I 2024-04-16 12:56:41,691] Trial 44 finished with value: 0.23505859419687822 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.245992169547344
Fold 2 IBS: 0.23030398883154765
Fold 3 IBS: 0.22602088555748998
Fold 4 IBS: 0.24506854708694867
Fold 5 IBS: 0.2266424541572869
[I 2024-04-16 12:56:43,996] Trial 45 finished with value: 0.23480560903612346 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.285272232553171
Fold 2 IBS: 0.34022481382607733
Fold 3 IBS: 0.22110161256805616
Fold 4 IBS: 0.32492480858119877
Fold 5 IBS: 0.2529675851466148
[I 2024-04-16 12:56:56,209] Trial 46 finished with value: 0.2848982105350236 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24400083224716765
Fold 2 IBS: 0.2286914601544719
Fold 3 IBS: 0.21802860270656116
Fold 4 IBS: 0.2616585117639279
Fold 5 IBS: 0.2155525744437183
[I 2024-04-16 12:57:01,923] Trial 47 finished with value: 0.23358639626316938 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.2447629771370417
Fold 2 IBS: 0.2295111852332123
Fold 3 IBS: 0.22096790757014262
Fold 4 IBS: 0.27210550511960613
Fold 5 IBS: 0.21120781197643132
[I 2024-04-16 12:57:10,423] Trial 48 finished with value: 0.2357110774072868 and parameters: {'subsample': 0.22653140537679164, 'dropout_rate': 0.19701471782839963, 'n_estimators': 121, 'learning_rate': 0.024161524863630254}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.2470990680925985
Fold 2 IBS: 0.23135650995860768
Fold 3 IBS: 0.22837712709480057
Fold 4 IBS: 0.24191259817585406
Fold 5 IBS: 0.22908833152868616
[I 2024-04-16 12:57:10,869] Trial 49 finished with value: 0.23556672697010944 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24470422142624032
Fold 2 IBS: 0.2285917168140393
Fold 3 IBS: 0.22186445740277122
Fold 4 IBS: 0.25184938951166586
Fold 5 IBS: 0.22256233757697086
[I 2024-04-16 12:57:13,862] Trial 50 finished with value: 0.2339144245463375 and parameters: {'subsample': 0.4595750860662744, 'dropout_rate': 0.985993838865288, 'n_estimators': 47, 'learning_rate': 0.019642786526356794}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.2447011739022072
Fold 2 IBS: 0.22815717478307107
Fold 3 IBS: 0.2229068397215183
Fold 4 IBS: 0.2520253561656566
Fold 5 IBS: 0.22122287248344558
[I 2024-04-16 12:57:20,036] Trial 51 finished with value: 0.23380268341117977 and parameters: {'subsample': 0.2799763343568198, 'dropout_rate': 0.9583640399237794, 'n_estimators': 85, 'learning_rate': 0.012885996913606607}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24446166993999344
Fold 2 IBS: 0.22826227362889145
Fold 3 IBS: 0.2219898947954163
Fold 4 IBS: 0.25397846233779164
Fold 5 IBS: 0.22108831920833702
[I 2024-04-16 12:57:25,435] Trial 52 finished with value: 0.23395612398208598 and parameters: {'subsample': 0.2871142790618468, 'dropout_rate': 0.9561009746358756, 'n_estimators': 65, 'learning_rate': 0.01745140959782642}. Best is trial 20 with value: 0.23358407126258549.
Fold 1 IBS: 0.24394528660433693
Fold 2 IBS: 0.22840422278574296
Fold 3 IBS: 0.21937578955060721
Fold 4 IBS: 0.2591991634016549
Fold 5 IBS: 0.2160820457337641
[I 2024-04-16 12:57:39,386] Trial 53 finished with value: 0.23340130161522127 and parameters: {'subsample': 0.17101504605859816, 'dropout_rate': 0.8425062477630199, 'n_estimators': 189, 'learning_rate': 0.010639328519898935}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.24611051911940046
Fold 2 IBS: 0.23010503153306544
Fold 3 IBS: 0.22660498648987212
Fold 4 IBS: 0.24464571607302885
Fold 5 IBS: 0.2264839213538699
[I 2024-04-16 12:57:51,701] Trial 54 finished with value: 0.23479003491384737 and parameters: {'subsample': 0.20571868565915807, 'dropout_rate': 0.8375325869157271, 'n_estimators': 196, 'learning_rate': 0.0019450569461602618}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.24472284209883258
Fold 2 IBS: 0.23006602014908545
Fold 3 IBS: 0.21525630829743492
Fold 4 IBS: 0.27575182071612625
Fold 5 IBS: 0.2109327399585117
[I 2024-04-16 12:58:16,132] Trial 55 finished with value: 0.23534594624399818 and parameters: {'subsample': 0.1518563693381615, 'dropout_rate': 0.9968470209003357, 'n_estimators': 296, 'learning_rate': 0.010400302487335426}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.2451771441083736
Fold 2 IBS: 0.2324210912918105
Fold 3 IBS: 0.2204333538292363
Fold 4 IBS: 0.27001380190416335
Fold 5 IBS: 0.21342405035448653
[I 2024-04-16 12:58:26,247] Trial 56 finished with value: 0.23629388829761408 and parameters: {'subsample': 0.23536407241968693, 'dropout_rate': 0.9035510726015369, 'n_estimators': 102, 'learning_rate': 0.024060590585430877}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.2605563044884192

Fold 2 IBS: 0.2559902377900189
Fold 3 IBS: 0.20593747426448292
Fold 4 IBS: 0.2966488979581647
Fold 5 IBS: 0.21989451198472817
[I 2024-04-16 12:58:39,995] Trial 57 finished with value: 0.2478054852971628 and parameters: {'subsample': 0.8287098573962808, 'dropout_rate': 0.36495170369158947, 'n_estimators': 148, 'learning_rate': 0.02983258418701287}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.24472680124664745
Fold 2 IBS: 0.22906958966306948
Fold 3 IBS: 0.22281472060721844
Fold 4 IBS: 0.2490125731053804
Fold 5 IBS: 0.2242497955703639
[I 2024-04-16 12:58:41,512] Trial 58 finished with value: 0.2339746960385359 and parameters: {'subsample': 0.9522999419915232, 'dropout_rate': 0.8437285494654791, 'n_estimators': 19, 'learning_rate': 0.036426191300585206}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.3635130282516715
Fold 2 IBS: 0.379191479979297
Fold 3 IBS: 0.2474770643970359
Fold 4 IBS: 0.37472848351738347
Fold 5 IBS: 0.3096348941943813
[I 2024-04-16 12:58:56,195] Trial 59 finished with value: 0.3349089900679538 and parameters: {'subsample': 0.14755630544314652, 'dropout_rate': 0.7923622382249117, 'n_estimators': 195, 'learning_rate': 0.08322655251020356}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.24553291178535147
Fold 2 IBS: 0.2294150155881073
Fold 3 IBS: 0.22537135905091296
Fold 4 IBS: 0.2466063880178406
Fold 5 IBS: 0.22512949486287082
[I 2024-04-16 12:59:05,007] Trial 60 finished with value: 0.23441103386101664 and parameters: {'subsample': 0.35920734190195525, 'dropout_rate': 0.7450175447181521, 'n_estimators': 135, 'learning_rate': 0.004163417098966211}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.24508472313780758
Fold 2 IBS: 0.22844998550823423
Fold 3 IBS: 0.22400968384040448
Fold 4 IBS: 0.24981172704038643
Fold 5 IBS: 0.22317084604792994
[I 2024-04-16 12:59:12,161] Trial 61 finished with value: 0.23410539311495254 and parameters: {'subsample': 0.2567323035577227, 'dropout_rate': 0.9505674287854481, 'n_estimators': 74, 'learning_rate': 0.012315236462893028}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.24518192094721164
Fold 2 IBS: 0.230518097845626
Fold 3 IBS: 0.2220199582113599
Fold 4 IBS: 0.2661429351342511
Fold 5 IBS: 0.21547857153531538
[I 2024-04-16 12:59:21,396] Trial 62 finished with value: 0.2358682967347528 and parameters: {'subsample': 0.3023043277224129, 'dropout_rate': 0.8891537175350246, 'n_estimators': 99, 'learning_rate': 0.021337190704722456}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.2457893477504726
Fold 2 IBS: 0.22946980397842426
Fold 3 IBS: 0.2258794728579572
Fold 4 IBS: 0.24616948538502054
Fold 5 IBS: 0.22591794271817509
[I 2024-04-16 12:59:26,006] Trial 63 finished with value: 0.2346452105380099 and parameters: {'subsample': 0.2675273969344081, 'dropout_rate': 0.5823907068184614, 'n_estimators': 48, 'learning_rate': 0.010759073901810426}. Best is trial 53 with value: 0.23340130161522127.
Fold 1 IBS: 0.24481610387440808
Fold 2 IBS: 0.22681468788470638
Fold 3 IBS: 0.22135829590414186
Fold 4 IBS: 0.25220439287544477
Fold 5 IBS: 0.22041905224791816
[I 2024-04-16 12:59:32,629] Trial 64 finished with value: 0.23312250655732383 and parameters: {'subsample': 0.18512675173225576, 'dropout_rate': 0.9618865041041474, 'n_estimators': 83, 'learning_rate': 0.016026997408142868}. Best is trial 64 with value: 0.23312250655732383.
Fold 1 IBS: 0.2445186721721489
Fold 2 IBS: 0.22743301379118622
Fold 3 IBS: 0.2247685843233049
Fold 4 IBS: 0.25013144978308455
Fold 5 IBS: 0.22203616915719201
[I 2024-04-16 12:59:37,173] Trial 65 finished with value: 0.2337775778453833 and parameters: {'subsample': 0.1840976697760306, 'dropout_rate': 0.6947852236615015, 'n_estimators': 63, 'learning_rate': 0.017416120135880828}. Best is trial 64 with value: 0.23312250655732383.
Fold 1 IBS: 0.24430217582583583
Fold 2 IBS: 0.22756845571630085
Fold 3 IBS: 0.21168246892414125
Fold 4 IBS: 0.26932817844021345
Fold 5 IBS: 0.21309779931235182
[I 2024-04-16 12:59:44,611] Trial 66 finished with value: 0.23319581564376862 and parameters: {'subsample': 0.11480326534458374, 'dropout_rate': 0.7035744251200552, 'n_estimators': 114, 'learning_rate': 0.026321402603498092}. Best is trial 64 with value: 0.23312250655732383.
Fold 1 IBS: 0.2454354907731004
Fold 2 IBS: 0.22876933230481453
Fold 3 IBS: 0.20776758367385878
Fold 4 IBS: 0.2787718787646663
Fold 5 IBS: 0.2098101101507343
[I 2024-04-16 12:59:55,742] Trial 67 finished with value: 0.23411087913343484 and parameters: {'subsample': 0.10608887189422572, 'dropout_rate': 0.6584841264798192, 'n_estimators': 155, 'learning_rate': 0.024950118804707842}. Best is trial 64 with value: 0.23312250655732383.
Fold 1 IBS: 0.24486124200044307
Fold 2 IBS: 0.2289900673042071
Fold 3 IBS: 0.21039687136168425
Fold 4 IBS: 0.26635992142307824
Fold 5 IBS: 0.21191337554954165
[I 2024-04-16 13:00:03,953] Trial 68 finished with value: 0.23250429552779087 and parameters: {'subsample': 0.12633116405171563, 'dropout_rate': 0.729989885152962, 'n_estimators': 114, 'learning_rate': 0.0267624773650322}. Best is trial 68 with value: 0.23250429552779087.
Fold 1 IBS: 0.246271565476242
Fold 2 IBS: 0.23100764982731473
Fold 3 IBS: 0.20886417431510984
Fold 4 IBS: 0.27867148031360073
Fold 5 IBS: 0.21036919846006757
[I 2024-04-16 13:00:10,933] Trial 69 finished with value: 0.235036813678467 and parameters: {'subsample': 0.12171593465314393, 'dropout_rate': 0.7268432347055517, 'n_estimators': 116, 'learning_rate': 0.032308868339687775}. Best is trial 68 with value: 0.23250429552779087.
Fold 1 IBS: 0.27744207539457266
Fold 2 IBS: 0.33814982265883575
Fold 3 IBS: 0.22117026852763771
Fold 4 IBS: 0.3109804627298319
Fold 5 IBS: 0.21935205392546367
[I 2024-04-16 13:00:29,431] Trial 70 finished with value: 0.2734189366472683 and parameters: {'subsample': 0.1782383751939549, 'dropout_rate': 0.6883033280385382, 'n_estimators': 213, 'learning_rate': 0.04067953220453687}. Best is trial 68 with value: 0.23250429552779087.
Fold 1 IBS: 0.24429374539178098
Fold 2 IBS: 0.22972153018945748
Fold 3 IBS: 0.2174945685167734
Fold 4 IBS: 0.26874132649733284
Fold 5 IBS: 0.211593873349801
[I 2024-04-16 13:00:37,765] Trial 71 finished with value: 0.23436900878902917 and parameters: {'subsample': 0.15392750431267843, 'dropout_rate': 0.6166818873131905, 'n_estimators': 100, 'learning_rate': 0.027414362645276517}. Best is trial 68 with value: 0.23250429552779087.
Fold 1 IBS: 0.2440053300833623
Fold 2 IBS: 0.2254385041064371
Fold 3 IBS: 0.2114556996609343
Fold 4 IBS: 0.2655732354762971
Fold 5 IBS: 0.21433349781901215
[I 2024-04-16 13:00:49,569] Trial 72 finished with value: 0.23216125342920862 and parameters: {'subsample': 0.10310321413083308, 'dropout_rate': 0.7847677514415349, 'n_estimators': 136, 'learning_rate': 0.02025591601675628}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24636233161344645
Fold 2 IBS: 0.23342378832290417
Fold 3 IBS: 0.20806437838617217
Fold 4 IBS: 0.2740232697322711
Fold 5 IBS: 0.20876124740593716
[I 2024-04-16 13:01:02,283] Trial 73 finished with value: 0.2341270030921462 and parameters: {'subsample': 0.12717046617496638, 'dropout_rate': 0.8170139436026628, 'n_estimators': 179, 'learning_rate': 0.020512531820716794}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24460007124509314
Fold 2 IBS: 0.2271746281771398
Fold 3 IBS: 0.22151073169820398
Fold 4 IBS: 0.2479489171862635
Fold 5 IBS: 0.22344944609395448
[I 2024-04-16 13:01:11,331] Trial 74 finished with value: 0.232936758880131 and parameters: {'subsample': 0.10176633125630379, 'dropout_rate': 0.5631858856980846, 'n_estimators': 128, 'learning_rate': 0.007696906592322719}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24452825467874492
Fold 2 IBS: 0.22679764968283259
Fold 3 IBS: 0.2209305449836741
Fold 4 IBS: 0.2486531262109866
Fold 5 IBS: 0.22295922285866723
[I 2024-04-16 13:01:21,359] Trial 75 finished with value: 0.23277375968298109 and parameters: {'subsample': 0.10152013959693323, 'dropout_rate': 0.7872476582623379, 'n_estimators': 136, 'learning_rate': 0.007916815713151356}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24491469936023438

Fold 2 IBS: 0.22722835245669692
Fold 3 IBS: 0.2213583543613421
Fold 4 IBS: 0.2492896157209996
Fold 5 IBS: 0.22297397591807772
[I 2024-04-16 13:01:33,134] Trial 76 finished with value: 0.23315299956347016 and parameters: {'subsample': 0.10872044007430444, 'dropout_rate': 0.7776650458314874, 'n_estimators': 135, 'learning_rate': 0.007952846343560593}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.2444008952395551
Fold 2 IBS: 0.22653089151378605
Fold 3 IBS: 0.22039733684992063
Fold 4 IBS: 0.24930368727631866
Fold 5 IBS: 0.22250819941405275
[I 2024-04-16 13:01:43,159] Trial 77 finished with value: 0.2326282020587266 and parameters: {'subsample': 0.10011750224614124, 'dropout_rate': 0.7725883386928235, 'n_estimators': 136, 'learning_rate': 0.008499607491977697}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24493585773048387
Fold 2 IBS: 0.22730380550302476
Fold 3 IBS: 0.2216341518354745
Fold 4 IBS: 0.24919505168860737
Fold 5 IBS: 0.22305630385096367
[I 2024-04-16 13:01:57,282] Trial 78 finished with value: 0.23322503412171086 and parameters: {'subsample': 0.10961263646152962, 'dropout_rate': 0.7807378376503163, 'n_estimators': 139, 'learning_rate': 0.007559570244779414}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24426245916855224
Fold 2 IBS: 0.2277963695095491
Fold 3 IBS: 0.22162642714610925
Fold 4 IBS: 0.2551339154954268
Fold 5 IBS: 0.21943298214754686
[I 2024-04-16 13:02:09,405] Trial 79 finished with value: 0.23365043069343688 and parameters: {'subsample': 0.20520157914116263, 'dropout_rate': 0.7231324884031991, 'n_estimators': 167, 'learning_rate': 0.0081877306359789}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24598554199862915
Fold 2 IBS: 0.22960683638658624
Fold 3 IBS: 0.22556338105294552
Fold 4 IBS: 0.2441097324050548
Fold 5 IBS: 0.22610572501486365
[I 2024-04-16 13:02:19,657] Trial 80 finished with value: 0.2342742433716159 and parameters: {'subsample': 0.13732830854696462, 'dropout_rate': 0.544032602974961, 'n_estimators': 127, 'learning_rate': 0.0036449858891288494}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24498754713158752
Fold 2 IBS: 0.2275970014204251
Fold 3 IBS: 0.22220221232815487
Fold 4 IBS: 0.2484980293984149
Fold 5 IBS: 0.22357527528336754
[I 2024-04-16 13:02:28,235] Trial 81 finished with value: 0.23337201311238998 and parameters: {'subsample': 0.10949278113898034, 'dropout_rate': 0.7430964117204553, 'n_estimators': 142, 'learning_rate': 0.006790549946292903}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24614370681188605
Fold 2 IBS: 0.23002191090341587
Fold 3 IBS: 0.22614896703684637
Fold 4 IBS: 0.24373449681950593
Fold 5 IBS: 0.2272185405842546
[I 2024-04-16 13:02:39,935] Trial 82 finished with value: 0.23465352443118176 and parameters: {'subsample': 0.10266753091211321, 'dropout_rate': 0.7729227414662975, 'n_estimators': 138, 'learning_rate': 0.002582076013439738}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24516550794446695
Fold 2 IBS: 0.22885891251301652
Fold 3 IBS: 0.22518337500922048
Fold 4 IBS: 0.24595154223539453
Fold 5 IBS: 0.2244492630708061
[I 2024-04-16 13:02:47,775] Trial 83 finished with value: 0.2339217201545809 and parameters: {'subsample': 0.1626959857092871, 'dropout_rate': 0.7853060834174002, 'n_estimators': 110, 'learning_rate': 0.006130340647869701}. Best is trial 72 with value: 0.23216125342920862.
Fold 1 IBS: 0.24464130761183397
Fold 2 IBS: 0.2268413985496079
Fold 3 IBS: 0.21379814702782507
Fold 4 IBS: 0.25887228870458134
Fold 5 IBS: 0.2157659758051336
[I 2024-04-16 13:02:57,741] Trial 84 finished with value: 0.23198382353979635 and parameters: {'subsample': 0.1297117655607607, 'dropout_rate': 0.8181892473002237, 'n_estimators': 153, 'learning_rate': 0.014352717720645333}. Best is trial 84 with value: 0.23198382353979635.
Fold 1 IBS: 0.24463308971325787
Fold 2 IBS: 0.22655612801710712
Fold 3 IBS: 0.21453291665658983
Fold 4 IBS: 0.2575304012175966
Fold 5 IBS: 0.2163659469421474
[I 2024-04-16 13:03:08,246] Trial 85 finished with value: 0.23192369650933978 and parameters: {'subsample': 0.13191567532022325, 'dropout_rate': 0.5146162039318547, 'n_estimators': 151, 'learning_rate': 0.013691270895338198}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.24413401100932766
Fold 2 IBS: 0.2301472931565073
Fold 3 IBS: 0.21786171392217663
Fold 4 IBS: 0.2621152932501541
Fold 5 IBS: 0.21459405408277907
[I 2024-04-16 13:03:18,319] Trial 86 finished with value: 0.23377047308418897 and parameters: {'subsample': 0.20098514435504208, 'dropout_rate': 0.4711624028296178, 'n_estimators': 157, 'learning_rate': 0.014716256660616383}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.2442073257700264
Fold 2 IBS: 0.22655926617437247
Fold 3 IBS: 0.21989275900470698
Fold 4 IBS: 0.2559909722712287
Fold 5 IBS: 0.21965505443458774
[I 2024-04-16 13:03:30,910] Trial 87 finished with value: 0.23326107553098444 and parameters: {'subsample': 0.14239320277780773, 'dropout_rate': 0.4997040224793169, 'n_estimators': 175, 'learning_rate': 0.009753788386785268}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.2500162749473922
Fold 2 IBS: 0.24201659557855423
Fold 3 IBS: 0.205598132395349
Fold 4 IBS: 0.28626809736870384
Fold 5 IBS: 0.20532666463832258
[I 2024-04-16 13:03:45,727] Trial 88 finished with value: 0.23784515298566436 and parameters: {'subsample': 0.13304540763298414, 'dropout_rate': 0.519381044557389, 'n_estimators': 227, 'learning_rate': 0.021660162048667008}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.2432717234522089
Fold 2 IBS: 0.22854838734748478
Fold 3 IBS: 0.21937581886922616
Fold 4 IBS: 0.2571881782587513
Fold 5 IBS: 0.2177931536062203
[I 2024-04-16 13:03:53,360] Trial 89 finished with value: 0.23323545230677828 and parameters: {'subsample': 0.2122379849687754, 'dropout_rate': 0.415617861413752, 'n_estimators': 124, 'learning_rate': 0.015069387749805142}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.24504601113412944
Fold 2 IBS: 0.23419909822292903
Fold 3 IBS: 0.21586348351678708
Fold 4 IBS: 0.2754982118566694
Fold 5 IBS: 0.20995919365779736
[I 2024-04-16 13:04:11,581] Trial 90 finished with value: 0.23611319967766248 and parameters: {'subsample': 0.1682015588029836, 'dropout_rate': 0.8176624166733474, 'n_estimators': 266, 'learning_rate': 0.01241075617336529}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.24515043337114775
Fold 2 IBS: 0.22738186358433302
Fold 3 IBS: 0.21220098905857168
Fold 4 IBS: 0.26986021459892495
Fold 5 IBS: 0.2135271545266809
[I 2024-04-16 13:04:21,379] Trial 91 finished with value: 0.23362413102793167 and parameters: {'subsample': 0.12250921088781065, 'dropout_rate': 0.5636430684480658, 'n_estimators': 152, 'learning_rate': 0.018507539656943857}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.24548335605935495
Fold 2 IBS: 0.22826229298307213
Fold 3 IBS: 0.22357328468066182
Fold 4 IBS: 0.24677239240179383
Fold 5 IBS: 0.2243960320759403
[I 2024-04-16 13:04:30,725] Trial 92 finished with value: 0.2336974716401646 and parameters: {'subsample': 0.1254264880830372, 'dropout_rate': 0.630911383430701, 'n_estimators': 128, 'learning_rate': 0.005903864149420823}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.24653995113794577
Fold 2 IBS: 0.23067387764108505
Fold 3 IBS: 0.2271380460690478
Fold 4 IBS: 0.2431711619536997
Fold 5 IBS: 0.22790476256349074
[I 2024-04-16 13:04:41,652] Trial 93 finished with value: 0.23508555987305382 and parameters: {'subsample': 0.10156652157288276, 'dropout_rate': 0.6670394346461228, 'n_estimators': 185, 'learning_rate': 0.0012764221198249513}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.2447473628160101
Fold 2 IBS: 0.22793028124010892
Fold 3 IBS: 0.22435901976439615
Fold 4 IBS: 0.24814638110013193
Fold 5 IBS: 0.22271291603971152
[I 2024-04-16 13:04:47,056] Trial 94 finished with value: 0.2335791921920717 and parameters: {'subsample': 0.1557243497134164, 'dropout_rate': 0.7451054354882352, 'n_estimators': 93, 'learning_rate': 0.00959641886375456}. Best is trial 85 with value: 0.23192369650933978.

Fold 1 IBS: 0.2438776644871741
Fold 2 IBS: 0.2273702416544349
Fold 3 IBS: 0.2216388578439526
Fold 4 IBS: 0.25462940750105734
Fold 5 IBS: 0.21857334992465485
[I 2024-04-16 13:04:53,969] Trial 95 finished with value: 0.23321790428225478 and parameters: {'subsample': 0.18731559423614882, 'dropout_rate': 0.6952487449215967, 'n_estimators': 113, 'learning_rate': 0.014561155672477087}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.3047438780802259
Fold 2 IBS: 0.36667578534077583
Fold 3 IBS: 0.22770961870063322
Fold 4 IBS: 0.3349989194790263
Fold 5 IBS: 0.2517589998313424
[I 2024-04-16 13:05:04,778] Trial 96 finished with value: 0.2971774402864007 and parameters: {'subsample': 0.14439450334056383, 'dropout_rate': 0.8606255051496826, 'n_estimators': 210, 'learning_rate': 0.054487916689644846}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.24649935060408712
Fold 2 IBS: 0.23914147413932216
Fold 3 IBS: 0.214847035469901
Fold 4 IBS: 0.27929194213187086
Fold 5 IBS: 0.2084310417416145
[I 2024-04-16 13:05:14,069] Trial 97 finished with value: 0.2376421688173591 and parameters: {'subsample': 0.16382796309843373, 'dropout_rate': 0.7170209380567314, 'n_estimators': 167, 'learning_rate': 0.02270715760917624}. Best is trial 85 with value: 0.23192369650933978.
Fold 1 IBS: 0.24428443921142234
Fold 2 IBS: 0.2264695534412878
Fold 3 IBS: 0.2153927307428986
Fold 4 IBS: 0.25615227539121316
Fold 5 IBS: 0.21696912110404842
[I 2024-04-16 13:05:21,232] Trial 98 finished with value: 0.23185362397817402 and parameters: {'subsample': 0.12997549398158215, 'dropout_rate': 0.8250651713012176, 'n_estimators': 110, 'learning_rate': 0.01816407400661799}. Best is trial 98 with value: 0.23185362397817402.
Fold 1 IBS: 0.2445661835426021
Fold 2 IBS: 0.2293387985845663
Fold 3 IBS: 0.2206375587567159
Fold 4 IBS: 0.2645993914907387
Fold 5 IBS: 0.21667521794196437
[I 2024-04-16 13:05:27,527] Trial 99 finished with value: 0.23516343006331747 and parameters: {'subsample': 0.22544453540337372, 'dropout_rate': 0.7994476106718348, 'n_estimators': 104, 'learning_rate': 0.018482789819412693}. Best is trial 98 with value: 0.23185362397817402.


* Best trial for IBS:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.23185362397817402], datetime_start=datetime.datetime(2024, 4, 16, 13, 5, 14, 73954), datetime_complete=datetime.datetime(2024, 4, 16, 13, 5, 21, 231783), params={'subsample': 0.12997549398158215, 'dropout_rate': 0.8250651713012176, 'n_estimators': 110, 'learning_rate': 0.01816407400661799}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=98, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.12997549398158215, 'dropout_rate': 0.8250651713012176, 'n_estimators': 110, 'learning_rate': 0.01816407400661799}


* Best Score for IBS:
 0.23185362397817402

In [76]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [77]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.63
train_ibs:  0.232

#### Test

In [78]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [79]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.9679593679379627,
                                              learning_rate=0.058079531447075304,
                                              n_estimators=218,
                                              random_state=123,
                                              subsample=0.2624985253235916)

C-index score: 0.677

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.8250651713012176,
                                              learning_rate=0.01816407400661799,
                                              n_estimators=110,
                                              random_state=123,
                                              subsample=0.12997549398158215)

IBS: 0.22

In [80]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [81]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.847   1.0
ExtraSurvivalTrees               0.842   2.0
GradientBoosting                 0.700   3.0
CoxRidge                         0.644   4.0
ComponentwiseGradientBoosting    0.630   5.0
CoxElastic                       0.625   6.0
CoxLasso                         0.509   7.0

In [82]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
ExtraSurvivalTrees             0.208   1.0
Randomsurvivalforest           0.212   2.0
GradientBoosting               0.230   3.0
ComponentwiseGradientBoosting  0.232   4.0
CoxElastic                     0.233   5.0
CoxRidge                       0.236   6.0
CoxLasso                       0.394   7.0

In [83]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
ComponentwiseGradientBoosting    0.677   1.0
CoxRidge                         0.601   2.5
CoxElastic                       0.601   2.5
ExtraSurvivalTrees               0.567   4.0
Randomsurvivalforest             0.540   5.0
CoxLasso                         0.516   6.5
GradientBoosting                 0.516   6.5

In [84]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
ComponentwiseGradientBoosting  0.220   1.0
CoxElastic                     0.225   2.0
GradientBoosting               0.228   3.0
CoxRidge                       0.229   4.0
ExtraSurvivalTrees             0.235   5.0
Randomsurvivalforest           0.262   6.0
CoxLasso                       0.406   7.0

In [87]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/minmax/no_selection/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_minmax_no_selection_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [88]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-16