In [65]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
 
from sklearn.preprocessing import MinMaxScaler

In [66]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [67]:
# Need to choose patient_id from OUS_D3 in response_OUS
data = list(OUS_D3['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D3 with response_OUS
clinical_train = pd.merge(OUS_D3, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [68]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

## Test dataset: MAASTRO

In [69]:
(MAASTRO_D3['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [70]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [71]:
# need to choose patient_id from MAASTRO_D3 in response_MAASTRO
data = list(MAASTRO_D3['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [72]:
# Merge MAASTRO_D3 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D3, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,age,female,cavum_oris,oropharynx,hypopharynx,larynx,histgrade_high,hpv_related,charlson,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,55,0,0,1,0,0,1,1,1,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,55,0,0,1,0,0,0,0,0,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,55,0,0,1,0,0,0,0,1,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,61,1,0,0,0,1,1,0,1,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,70,0,0,1,0,0,1,1,1,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,66,1,0,0,0,1,0,0,0,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,63,0,0,0,0,1,0,0,1,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,63,0,0,1,0,0,1,1,1,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,54,0,0,1,0,0,1,1,0,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,62,0,0,0,1,0,1,0,0,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [73]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [74]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [age, female, cavum_oris, oropharynx, hypopharynx, larynx, histgrade_high, hpv_related, charlson, pack_years, uicc8_III-IV, SUVpeak, MTV, TLG, shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, ...]
Index: []

[0 rows x 390 columns]

In [75]:
# Set X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# Set y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [76]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [77]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 388)
y_train:  (139,)

In [78]:
# Change the name of a column 'DFS_event' in the clincial_test 
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [79]:
# Set X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# Set y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]

# Change y_MAASTRO into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 390)

## Feature Selection

### COX PLSR

In [80]:
# Choose features from the result of Cox PLSR in R
plsr = [
"shape_MajorAxisLength",
"LBP_120_PET",
"LBP_201_PET",
"glszm_SmallAreaLowGrayLevelEmphasis_CT_c16",
"shape_Maximum3DDiameter",
"shape_SurfaceVolumeRatio",
"shape_Sphericity",
"shape_Elongation"
]

In [81]:
X_plsr = X.loc[:, plsr]
X_new = X_plsr.copy()

In [82]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, plsr]

# Standardization

In [83]:
# Copy the original X for later 
original_X = X.copy()

In [84]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = MinMaxScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [85]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [86]:
X_new

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation
0,42.073251,0.140311,0.000062,0.029425,47.339202,0.251218,0.761164,0.600926
1,24.613845,0.191058,0.000349,0.037915,28.106939,0.489853,0.697049,0.841579
2,48.030294,0.126531,0.000000,0.008009,60.049979,0.278467,0.565792,0.772821
3,25.589900,0.192388,0.000000,0.018398,32.572995,0.474018,0.684364,0.847727
4,34.684750,0.202073,0.000399,0.013051,39.962482,0.563135,0.503142,0.831483
...,...,...,...,...,...,...,...,...
134,33.069705,0.152626,0.000000,0.014938,37.696154,0.322021,0.742102,0.680294
135,41.043692,0.142778,0.000079,0.011441,52.430907,0.227705,0.722918,0.758193
136,36.618802,0.140582,0.000000,0.020431,42.743421,0.298398,0.652963,0.770113
137,45.870392,0.156640,0.000054,0.019663,51.536395,0.252893,0.724255,0.628897
138,30.363259,0.147644,0.000000,0.013864,39.408121,0.290461,0.722633,0.892637

In [87]:
X_new_std

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation
0,0.350904,0.174091,0.088609,0.603741,0.298726,0.263957,0.828413,0.461898
1,0.123069,0.456736,0.501821,0.800232,0.099559,0.707641,0.645006,0.829873
2,0.428640,0.097341,0.000000,0.108112,0.430358,0.314620,0.269537,0.724738
3,0.135806,0.464144,0.000000,0.348551,0.145809,0.678200,0.608721,0.839273
4,0.254489,0.518081,0.572624,0.224799,0.222333,0.843892,0.090323,0.814436
...,...,...,...,...,...,...,...,...
134,0.233413,0.242682,0.000000,0.268474,0.198864,0.395598,0.773882,0.583257
135,0.337469,0.187835,0.113114,0.187545,0.351455,0.220239,0.719008,0.702369
136,0.279727,0.175602,0.000000,0.395599,0.251133,0.351677,0.518897,0.720597
137,0.400455,0.265036,0.077871,0.377829,0.342192,0.267071,0.722831,0.504667
138,0.198096,0.214934,0.000000,0.243616,0.216592,0.336919,0.718191,0.907943

In [88]:
MAASTRO_new

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation
0,50.002093,0.122209,0.000026,0.010495,58.864251,0.215184,0.668072,0.765178
1,41.753334,0.128976,0.000167,0.035018,48.723711,0.276092,0.669961,0.776540
2,44.375483,0.137282,0.000000,0.012819,48.969378,0.298887,0.624081,0.697164
3,46.115989,0.171595,0.000080,0.029974,55.226805,0.361096,0.577624,0.574636
4,54.394967,0.128134,0.000035,0.013458,67.089492,0.251519,0.630933,0.633419
...,...,...,...,...,...,...,...,...
94,34.218615,0.137194,0.000078,0.039092,43.520110,0.307574,0.671754,0.882411
95,51.046869,0.137620,0.000054,0.015831,52.440442,0.289922,0.632189,0.535802
96,50.417953,0.115099,0.000028,0.011031,57.671483,0.228184,0.645548,0.716610
97,44.901412,0.117654,0.000000,0.019801,51.478151,0.223872,0.727488,0.665145
98,36.574294,0.156924,0.000112,0.015813,43.485630,0.347373,0.672838,0.616262

In [89]:
MAASTRO_new_std

,shape_MajorAxisLength,LBP_120_PET,LBP_201_PET,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_Maximum3DDiameter,shape_SurfaceVolumeRatio,shape_Sphericity,shape_Elongation
0,0.454371,0.073271,0.037694,0.165637,0.418078,0.196961,0.562115,0.713050
1,0.346729,0.110963,0.240548,0.733175,0.313064,0.310203,0.567520,0.730423
2,0.380947,0.157221,0.000000,0.219419,0.315608,0.352585,0.436277,0.609052
3,0.403660,0.348334,0.114827,0.616439,0.380409,0.468248,0.303383,0.421699
4,0.511695,0.106269,0.050658,0.234227,0.503258,0.264517,0.455879,0.511582
...,...,...,...,...,...,...,...,...
94,0.248406,0.156731,0.111676,0.827475,0.259176,0.368738,0.572648,0.892307
95,0.468005,0.159105,0.078027,0.289124,0.351554,0.335917,0.459472,0.362320
96,0.459798,0.033672,0.040540,0.178051,0.405726,0.221130,0.497683,0.638788
97,0.387810,0.047900,0.000000,0.381019,0.341589,0.213114,0.732079,0.560093
98,0.279146,0.266623,0.161501,0.288721,0.258819,0.442734,0.575748,0.485348

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [90]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:46:35,576] A new study created in memory with name: no-name-f79f46ba-f3bb-4d16-86fe-c616f737d22b

  0%|          | 0/1 [00:00<?, ?it/s]

[I 2024-04-16 09:46:35,910] A new study created in memory with name: no-name-6803fa01-3973-4815-99a6-56f11f9c1a7c

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 09:46:35,904] Trial 0 finished with value: 0.6811103040058727 and parameters: {}. Best is trial 0 with value: 0.6811103040058727.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6811103040058727], datetime_start=datetime.datetime(2024, 4, 16, 9, 46, 35, 631107), datetime_complete=datetime.datetime(2024, 4, 16, 9, 46, 35, 904392), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6811103040058727

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2644313749672424
Fold 2 IBS: 0.1772296022395614
Fold 3 IBS: 0.19936774967703333
Fold 4 IBS: 0.24814797488840457
Fold 5 IBS: 0.19174971398784724
[I 2024-04-16 09:46:36,189] Trial 0 finished with value: 0.21618528315201777 and parameters: {}. Best is trial 0 with value: 0.21618528315201777.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21618528315201777], datetime_start=datetime.datetime(2024, 4, 16, 9, 46, 35, 948840), datetime_complete=datetime.datetime(2024, 4, 16, 9, 46, 36, 189248), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21618528315201777

In [91]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [92]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.681
train_ibs:  0.216

#### Test

In [93]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [94]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.508
IBS score: 0.283

In [95]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [96]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [97]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:46:36,341] A new study created in memory with name: no-name-3038044e-8414-4e98-82eb-922a00b56e15

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.5446808510638298
Fold 4 C-index: 0.6711026615969582
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 09:46:36,473] Trial 0 finished with value: 0.6309148160341665 and parameters: {}. Best is trial 0 with value: 0.6309148160341665.

[I 2024-04-16 09:46:36,486] A new study created in memory with name: no-name-e309d9d9-ae5e-406e-8298-66b6f58ae171

* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6309148160341665], datetime_start=datetime.datetime(2024, 4, 16, 9, 46, 36, 370455), datetime_complete=datetime.datetime(2024, 4, 16, 9, 46, 36, 473375), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6309148160341665

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2472470987338797
Fold 2 IBS: 0.23203988176202153
Fold 3 IBS: 0.22898186794169834
Fold 4 IBS: 0.24197476878512575
Fold 5 IBS: 0.22939559108577243
[I 2024-04-16 09:46:36,676] Trial 0 finished with value: 0.23592784166169953 and parameters: {}. Best is trial 0 with value: 0.23592784166169953.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592784166169953], datetime_start=datetime.datetime(2024, 4, 16, 9, 46, 36, 524752), datetime_complete=datetime.datetime(2024, 4, 16, 9, 46, 36, 676417), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592784166169953

In [98]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [99]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.631
train_ibs:  0.236

#### Test

In [100]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [101]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.534

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [102]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [103]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:46:36,844] A new study created in memory with name: no-name-721b8728-8fc2-4e6c-98bf-fc3710ca8c4d

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753

[I 2024-04-16 09:46:37,255] A new study created in memory with name: no-name-0bc914cf-0729-4158-a53b-b96b5d682f07

Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:37,250] Trial 0 finished with value: 0.6827438669030348 and parameters: {}. Best is trial 0 with value: 0.6827438669030348.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6827438669030348], datetime_start=datetime.datetime(2024, 4, 16, 9, 46, 36, 893068), datetime_complete=datetime.datetime(2024, 4, 16, 9, 46, 37, 250048), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6827438669030348

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2626935744757735
Fold 2 IBS: 0.17625232710995545
Fold 3 IBS: 0.19835796742294537
Fold 4 IBS: 0.24640861437214787
Fold 5 IBS: 0.1894678752019021
[I 2024-04-16 09:46:37,607] Trial 0 finished with value: 0.21463607171654484 and parameters: {}. Best is trial 0 with value: 0.21463607171654484.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.21463607171654484], datetime_start=datetime.datetime(2024, 4, 16, 9, 46, 37, 298128), datetime_complete=datetime.datetime(2024, 4, 16, 9, 46, 37, 606991), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.21463607171654484

In [104]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [105]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.683
train_ibs:  0.215

#### Test

In [106]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [107]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.507

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.282

In [108]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [109]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:46:37,876] A new study created in memory with name: no-name-fd7dc929-3882-41ef-816c-feb606a22ac9

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:38,207] Trial 0 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:38,559] Trial 1 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:38,881] Trial 2 finished with value: 0.6538150019591941 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:39,221] Trial 3 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:39,530] Trial 4 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:39,854] Trial 5 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:40,116] Trial 6 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:40,415] Trial 7 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:40,711] Trial 8 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:41,041] Trial 9 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:41,284] Trial 10 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:41,557] Trial 11 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.748312136386636}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:41,860] Trial 12 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:42,220] Trial 13 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8178071080614558}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 09:46:42,325] Trial 14 finished with value: 0.638253629458991 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:42,660] Trial 15 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.5998716175293216}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:42,992] Trial 16 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8431112134784231}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:43,290] Trial 17 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6422698927560148}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:43,600] Trial 18 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8885825731043129}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:43,926] Trial 19 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5264626269854424}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:44,198] Trial 20 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8744063907908842}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:44,497] Trial 21 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6832429193864219}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:44,773] Trial 22 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7594753037793387}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:45,038] Trial 23 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6349612814622255}. Best is trial 0 with value: 0.6843626922755115.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:45,344] Trial 24 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7602371709740536}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:45,698] Trial 25 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5833004187842314}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:46,085] Trial 26 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.683379796474269}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6577946768060836
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 09:46:46,190] Trial 27 finished with value: 0.6397745420065195 and parameters: {'l1_ratio': 0.016560941611969082}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:46,575] Trial 28 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.9183288268767481}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:47,107] Trial 29 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.4499897586072885}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:47,457] Trial 30 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.352669675201142}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:47,800] Trial 31 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.7908953767882752}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:48,133] Trial 32 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7122014695560627}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:48,459] Trial 33 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6422195303308569}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:48,754] Trial 34 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5191043786540674}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:49,034] Trial 35 finished with value: 0.6538150019591941 and parameters: {'l1_ratio': 0.2725297648636211}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:49,270] Trial 36 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.9247539216867823}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:49,566] Trial 37 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.7763022920363096}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:49,930] Trial 38 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:50,263] Trial 39 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7304824129775314}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:50,620] Trial 40 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8265459436111273}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:50,963] Trial 41 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7030105763086383}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:51,461] Trial 42 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.6147680199924856}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:51,826] Trial 43 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6703798638434219}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:52,122] Trial 44 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.730059128547432}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:52,393] Trial 45 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.7991509500548386}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:52,753] Trial 46 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8604250605248984}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:53,143] Trial 47 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.4840774882217921}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395

Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:53,504] Trial 48 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.5683872043393509}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:53,873] Trial 49 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.9567711086913276}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:54,346] Trial 50 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7432829682775339}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:54,703] Trial 51 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6098430219758137}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:55,115] Trial 52 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6593383001284692}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:55,473] Trial 53 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.5982390847281355}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:46:55,818] Trial 54 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8269690580344214}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:56,184] Trial 55 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6872216057749948}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:56,597] Trial 56 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.541798917953184}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:56,942] Trial 57 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7703962102698737}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:57,261] Trial 58 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6487691409506016}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:57,584] Trial 59 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.38638223507692027}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:57,971] Trial 60 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7073757579947153}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:58,375] Trial 61 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6243582551215365}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:58,851] Trial 62 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7456789378724505}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:59,225] Trial 63 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5077383706618921}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:59,574] Trial 64 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6697997063166228}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:46:59,900] Trial 65 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5878079441111739}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:00,255] Trial 66 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.45190246613787144}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:47:00,587] Trial 67 finished with value: 0.683504323176799 and parameters: {'l1_ratio': 0.7965604964350725}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:00,972] Trial 68 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7069633373603904}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6463878326996197
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 09:47:01,167] Trial 69 finished with value: 0.6335307283907612 and parameters: {'l1_ratio': 0.14881965141192482}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:01,497] Trial 70 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6278366970608916}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:01,833] Trial 71 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6906758023989493}. Best is trial 0 with value: 0.6843626922755115.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:02,225] Trial 72 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7311532326667369}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:02,537] Trial 73 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6524882199292468}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:02,891] Trial 74 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5511221252829253}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:47:03,226] Trial 75 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8504922169278538}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:03,565] Trial 76 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7651868352121096}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:47:03,906] Trial 77 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8832994937104452}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:47:04,228] Trial 78 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.7997790529703294}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:04,542] Trial 79 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6717086134283189}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:04,878] Trial 80 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7249091919302515}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:05,217] Trial 81 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7510501142845641}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:05,573] Trial 82 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6962068529194394}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:05,904] Trial 83 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6381100217475618}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:47:06,226] Trial 84 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.8235387450207625}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:06,663] Trial 85 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6114164712527408}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:07,172] Trial 86 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5921705952860442}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:47:07,498] Trial 87 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.7851013059160962}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:07,865] Trial 88 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7619404132893269}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:08,338] Trial 89 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7243744558839097}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:47:08,734] Trial 90 finished with value: 0.6827438669030348 and parameters: {'l1_ratio': 0.9066462334744206}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:09,228] Trial 91 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6687992810209542}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:09,633] Trial 92 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6406937374775695}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:10,023] Trial 93 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6874888807965509}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:10,431] Trial 94 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5764563071532146}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:10,976] Trial 95 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7144465453420705}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395

Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:11,405] Trial 96 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.7421347952856484}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:11,745] Trial 97 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.5379594828250149}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:12,104] Trial 98 finished with value: 0.6843626922755115 and parameters: {'l1_ratio': 0.6541944670325653}. Best is trial 0 with value: 0.6843626922755115.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.7106382978723405

[I 2024-04-16 09:47:12,668] A new study created in memory with name: no-name-6f4658a1-7833-4d69-81c6-3223d2ef7fa3

Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:47:12,663] Trial 99 finished with value: 0.6836022360017473 and parameters: {'l1_ratio': 0.6203159839145498}. Best is trial 0 with value: 0.6843626922755115.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6843626922755115], datetime_start=datetime.datetime(2024, 4, 16, 9, 46, 37, 909957), datetime_complete=datetime.datetime(2024, 4, 16, 9, 46, 38, 207089), params={'l1_ratio': 0.6964995386793018}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=0, value=None)


* Best Score for C-index:
 0.6843626922755115

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.26257162940250955
Fold 2 IBS: 0.17633924242670115
Fold 3 IBS: 0.19822344706060782
Fold 4 IBS: 0.24637305627894682
Fold 5 IBS: 0.18905968865715259
[I 2024-04-16 09:47:13,174] Trial 0 finished with value: 0.2145134127651836 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.2145134127651836.
Fold 1 IBS: 0.26237731476072124
Fold 2 IBS: 0.17627548359861686
Fold 3 IBS: 0.19807053093982024
Fold 4 IBS: 0.24605840774168466
Fold 5 IBS: 0.18883411697939656
[I 2024-04-16 09:47:13,634] Trial 1 finished with value: 0.2143231708040479 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26237386642247196
Fold 2 IBS: 0.17620383273044332
Fold 3 IBS: 0.22875723206890197
Fold 4 IBS: 0.2460704170061998
Fold 5 IBS: 0.18882164380537048
[I 2024-04-16 09:47:14,039] Trial 2 finished with value: 0.2204453984066775 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2623645599617991
Fold 2 IBS: 0.17628207959432834
Fold 3 IBS: 0.19814578469786784
Fold 4 IBS: 0.24622911378084267
Fold 5 IBS: 0.1889164870076764
[I 2024-04-16 09:47:14,448] Trial 3 finished with value: 0.21438760500850287 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26253214699282135
Fold 2 IBS: 0.17637227919151893
Fold 3 IBS: 0.1982111023146803
Fold 4 IBS: 0.24632529021031452
Fold 5 IBS: 0.18908980077662904
[I 2024-04-16 09:47:14,893] Trial 4 finished with value: 0.21450612389719287 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26231906367188146
Fold 2 IBS: 0.17629338768031627
Fold 3 IBS: 0.1980398302599325
Fold 4 IBS: 0.2461001314985376
Fold 5 IBS: 0.1888677306882611
[I 2024-04-16 09:47:15,333] Trial 5 finished with value: 0.2143240287597858 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26272580573955195
Fold 2 IBS: 0.17629614705757288
Fold 3 IBS: 0.19836239149515913
Fold 4 IBS: 0.24648437011031926
Fold 5 IBS: 0.1894470325183365
[I 2024-04-16 09:47:15,696] Trial 6 finished with value: 0.21466314938418796 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26252497258705276
Fold 2 IBS: 0.1763186127332562
Fold 3 IBS: 0.1982107168676572
Fold 4 IBS: 0.24633164287755643
Fold 5 IBS: 0.18902280498655544
[I 2024-04-16 09:47:16,084] Trial 7 finished with value: 0.2144817500104156 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2624657098993869
Fold 2 IBS: 0.17628297017340028
Fold 3 IBS: 0.19813423650808082
Fold 4 IBS: 0.2462093706134283
Fold 5 IBS: 0.18890404852910903
[I 2024-04-16 09:47:16,639] Trial 8 finished with value: 0.2143992671446811 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2624383984368
Fold 2 IBS: 0.17628801173496964
Fold 3 IBS: 0.19812774253263107
Fold 4 IBS: 0.2460901188859635
Fold 5 IBS: 0.18885846059452446
[I 2024-04-16 09:47:17,072] Trial 9 finished with value: 0.21436054643697772 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.24561859999386787
Fold 2 IBS: 0.22934599822147697
Fold 3 IBS: 0.22886652187145956
Fold 4 IBS: 0.23947104556492577
Fold 5 IBS: 0.227499190206926
[I 2024-04-16 09:47:17,229] Trial 10 finished with value: 0.23416027117173127 and parameters: {'l1_ratio': 0.09799455604980911}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26226272715386395
Fold 2 IBS: 0.1762148502765844
Fold 3 IBS: 0.22873600840851555
Fold 4 IBS: 0.24608937505721507
Fold 5 IBS: 0.1888292288999615
[I 2024-04-16 09:47:17,645] Trial 11 finished with value: 0.2204264379592281 and parameters: {'l1_ratio': 0.2694535558091148}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2623904988865742
Fold 2 IBS: 0.17627773506208477
Fold 3 IBS: 0.19805598617137044
Fold 4 IBS: 0.24606359899611463
Fold 5 IBS: 0.18882973856552066
[I 2024-04-16 09:47:18,126] Trial 12 finished with value: 0.21432351153633294 and parameters: {'l1_ratio': 0.31013775902329344}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.24709599678917643
Fold 2 IBS: 0.23179443555171964
Fold 3 IBS: 0.22897061486829134
Fold 4 IBS: 0.2417390357676709
Fold 5 IBS: 0.22922222539879433
[I 2024-04-16 09:47:18,290] Trial 13 finished with value: 0.23576446167513052 and parameters: {'l1_ratio': 0.008843037318081559}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26226175497611526
Fold 2 IBS: 0.17622239367167183
Fold 3 IBS: 0.2287547173280063
Fold 4 IBS: 0.24596969622003656
Fold 5 IBS: 0.1888283181665357
[I 2024-04-16 09:47:18,674] Trial 14 finished with value: 0.22040737607247313 and parameters: {'l1_ratio': 0.2311909900500493}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26231155974446474
Fold 2 IBS: 0.17623009479265747
Fold 3 IBS: 0.19811815139859226
Fold 4 IBS: 0.24611419449214678
Fold 5 IBS: 0.18885606261203747
[I 2024-04-16 09:47:19,364] Trial 15 finished with value: 0.21432601260797973 and parameters: {'l1_ratio': 0.344095248197816}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2622582354601032
Fold 2 IBS: 0.22747845598370567
Fold 3 IBS: 0.2288003742771054
Fold 4 IBS: 0.23784086904934557
Fold 5 IBS: 0.18881517313720309
[I 2024-04-16 09:47:19,709] Trial 16 finished with value: 0.22903862158149257 and parameters: {'l1_ratio': 0.16734092354036395}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2623896350187069
Fold 2 IBS: 0.1762921207104873
Fold 3 IBS: 0.1980814235095413
Fold 4 IBS: 0.24624750215390973
Fold 5 IBS: 0.188909766269635
[I 2024-04-16 09:47:20,277] Trial 17 finished with value: 0.21438408953245608 and parameters: {'l1_ratio': 0.5561491581974486}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.24587337398935455
Fold 2 IBS: 0.22977510451261188
Fold 3 IBS: 0.22888352887069907
Fold 4 IBS: 0.23985771667406974
Fold 5 IBS: 0.2278003313968909
[I 2024-04-16 09:47:20,581] Trial 18 finished with value: 0.23443801108872525 and parameters: {'l1_ratio': 0.08224235450898737}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26267904493492467
Fold 2 IBS: 0.17627787310751786
Fold 3 IBS: 0.19835313611607375
Fold 4 IBS: 0.24645732819352462
Fold 5 IBS: 0.1894363017066917
[I 2024-04-16 09:47:21,182] Trial 19 finished with value: 0.21464073681174653 and parameters: {'l1_ratio': 0.9706178824214255}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26240380226844123
Fold 2 IBS: 0.17628502477445926
Fold 3 IBS: 0.19805506819741606
Fold 4 IBS: 0.24607827512189154
Fold 5 IBS: 0.18883771096003635
[I 2024-04-16 09:47:21,875] Trial 20 finished with value: 0.2143319762644489 and parameters: {'l1_ratio': 0.31242295912387974}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2623551500465977
Fold 2 IBS: 0.17630377729370197
Fold 3 IBS: 0.19814345310230183
Fold 4 IBS: 0.24612279928676933
Fold 5 IBS: 0.188891929072737
[I 2024-04-16 09:47:22,522] Trial 21 finished with value: 0.2143634217604216 and parameters: {'l1_ratio': 0.4588459269024019}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2624081406856464
Fold 2 IBS: 0.17627395213424948
Fold 3 IBS: 0.19811552702070362
Fold 4 IBS: 0.24618705648300124
Fold 5 IBS: 0.18886458652718416
[I 2024-04-16 09:47:23,336] Trial 22 finished with value: 0.214369852570157 and parameters: {'l1_ratio': 0.3864140929318433}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2624361771936933
Fold 2 IBS: 0.1763023331726508
Fold 3 IBS: 0.19817583933851843
Fold 4 IBS: 0.24627789309635473
Fold 5 IBS: 0.18896020923413268
[I 2024-04-16 09:47:23,924] Trial 23 finished with value: 0.21443049040706996 and parameters: {'l1_ratio': 0.5989699513916362}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.26234054153294833
Fold 2 IBS: 0.17630241290484147
Fold 3 IBS: 0.1980343405403074
Fold 4 IBS: 0.2461161966216118
Fold 5 IBS: 0.18887013431240238
[I 2024-04-16 09:47:24,325] Trial 24 finished with value: 0.21433272518242225 and parameters: {'l1_ratio': 0.42756718534418364}. Best is trial 1 with value: 0.2143231708040479.

Fold 1 IBS: 0.2623065776975309
Fold 2 IBS: 0.22771743121877502
Fold 3 IBS: 0.22880803314680423
Fold 4 IBS: 0.23804473214879163
Fold 5 IBS: 0.22635839546653805
[I 2024-04-16 09:47:24,545] Trial 25 finished with value: 0.23664703393568795 and parameters: {'l1_ratio': 0.15838797155583242}. Best is trial 1 with value: 0.2143231708040479.
Fold 1 IBS: 0.2623009993332655
Fold 2 IBS: 0.17622672114260704
Fold 3 IBS: 0.19812409407550668
Fold 4 IBS: 0.24611110866082173
Fold 5 IBS: 0.18883518257861268
[I 2024-04-16 09:47:24,988] Trial 26 finished with value: 0.21431962115816275 and parameters: {'l1_ratio': 0.31870248699447157}. Best is trial 26 with value: 0.21431962115816275.
Fold 1 IBS: 0.26239953416003275
Fold 2 IBS: 0.176282070497932
Fold 3 IBS: 0.19806101652311164
Fold 4 IBS: 0.2460708408061116
Fold 5 IBS: 0.18883071508438132
[I 2024-04-16 09:47:25,443] Trial 27 finished with value: 0.21432883541431388 and parameters: {'l1_ratio': 0.31149345374565823}. Best is trial 26 with value: 0.21431962115816275.
Fold 1 IBS: 0.2623593789045578
Fold 2 IBS: 0.22720936627066468
Fold 3 IBS: 0.22879207092734571
Fold 4 IBS: 0.24594269688209738
Fold 5 IBS: 0.18880648426691102
[I 2024-04-16 09:47:25,850] Trial 28 finished with value: 0.2306219994503153 and parameters: {'l1_ratio': 0.1774529132387866}. Best is trial 26 with value: 0.21431962115816275.
Fold 1 IBS: 0.2623031416305209
Fold 2 IBS: 0.17623967028273071
Fold 3 IBS: 0.22874222946029676
Fold 4 IBS: 0.24599821276666153
Fold 5 IBS: 0.18881653251221256
[I 2024-04-16 09:47:26,314] Trial 29 finished with value: 0.2204199573304845 and parameters: {'l1_ratio': 0.255000768059799}. Best is trial 26 with value: 0.21431962115816275.
Fold 1 IBS: 0.262310056786696
Fold 2 IBS: 0.17622854824172324
Fold 3 IBS: 0.19811703305398315
Fold 4 IBS: 0.24611183442948595
Fold 5 IBS: 0.18885398226144118
[I 2024-04-16 09:47:26,804] Trial 30 finished with value: 0.21432429095466593 and parameters: {'l1_ratio': 0.3435938322870975}. Best is trial 26 with value: 0.21431962115816275.
Fold 1 IBS: 0.26232145015867653
Fold 2 IBS: 0.17629720797121307
Fold 3 IBS: 0.1980450572543554
Fold 4 IBS: 0.24610505962633786
Fold 5 IBS: 0.18886669762523864
[I 2024-04-16 09:47:27,734] Trial 31 finished with value: 0.2143270945271643 and parameters: {'l1_ratio': 0.3960233578890906}. Best is trial 26 with value: 0.21431962115816275.
Fold 1 IBS: 0.2622768243730239
Fold 2 IBS: 0.1762179819944098
Fold 3 IBS: 0.1981121259369015
Fold 4 IBS: 0.24609543840429293
Fold 5 IBS: 0.18882699432366284
[I 2024-04-16 09:47:28,234] Trial 32 finished with value: 0.2143058730064582 and parameters: {'l1_ratio': 0.2924108895687465}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26224183410220075
Fold 2 IBS: 0.22673710946356157
Fold 3 IBS: 0.2287783697828407
Fold 4 IBS: 0.24596430108742617
Fold 5 IBS: 0.1888137864219454
[I 2024-04-16 09:47:28,636] Trial 33 finished with value: 0.23050708017159494 and parameters: {'l1_ratio': 0.19528244967856956}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2622505123297194
Fold 2 IBS: 0.22877272441747673
Fold 3 IBS: 0.2288447746386812
Fold 4 IBS: 0.2389615595412322
Fold 5 IBS: 0.22709729244760551
[I 2024-04-16 09:47:28,874] Trial 34 finished with value: 0.23718537267494302 and parameters: {'l1_ratio': 0.11913817427204429}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26237336563143926
Fold 2 IBS: 0.17629902930785774
Fold 3 IBS: 0.19807736203457016
Fold 4 IBS: 0.2462456132003484
Fold 5 IBS: 0.1889023408613194
[I 2024-04-16 09:47:29,297] Trial 35 finished with value: 0.214379542207107 and parameters: {'l1_ratio': 0.5222466375146795}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26227826314418395
Fold 2 IBS: 0.17622397293854172
Fold 3 IBS: 0.2287350822551156
Fold 4 IBS: 0.24610334101799622
Fold 5 IBS: 0.18882488169309664
[I 2024-04-16 09:47:29,726] Trial 36 finished with value: 0.22043310820978684 and parameters: {'l1_ratio': 0.271846924279129}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.24667152172227066
Fold 2 IBS: 0.23110053189361984
Fold 3 IBS: 0.22893950340866048
Fold 4 IBS: 0.24108103474794434
Fold 5 IBS: 0.22873260086141572
[I 2024-04-16 09:47:29,894] Trial 37 finished with value: 0.23530503852678222 and parameters: {'l1_ratio': 0.03394435882442354}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2625800914979533
Fold 2 IBS: 0.17637636831817297
Fold 3 IBS: 0.19829373245635717
Fold 4 IBS: 0.24643932567773283
Fold 5 IBS: 0.1892764563648161
[I 2024-04-16 09:47:30,268] Trial 38 finished with value: 0.2145931948630065 and parameters: {'l1_ratio': 0.8598478847078105}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623968659776984
Fold 2 IBS: 0.17627493482281392
Fold 3 IBS: 0.1980538858080068
Fold 4 IBS: 0.24606323155398552
Fold 5 IBS: 0.18884722061249892
[I 2024-04-16 09:47:30,685] Trial 39 finished with value: 0.2143272277550007 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2625169108152127
Fold 2 IBS: 0.1763386098878999
Fold 3 IBS: 0.19816174348175122
Fold 4 IBS: 0.24621858542651645
Fold 5 IBS: 0.1889817841501883
[I 2024-04-16 09:47:31,050] Trial 40 finished with value: 0.2144435267523137 and parameters: {'l1_ratio': 0.6177970839908449}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26244556523871726
Fold 2 IBS: 0.17627683050616239
Fold 3 IBS: 0.19814011367118856
Fold 4 IBS: 0.24620292511137665
Fold 5 IBS: 0.1888795866292525
[I 2024-04-16 09:47:31,438] Trial 41 finished with value: 0.2143890042313395 and parameters: {'l1_ratio': 0.44839127835494}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2624048653718812
Fold 2 IBS: 0.17627240764417457
Fold 3 IBS: 0.19811430187014398
Fold 4 IBS: 0.2461845373517331
Fold 5 IBS: 0.18886963804444135
[I 2024-04-16 09:47:31,839] Trial 42 finished with value: 0.21436915005647483 and parameters: {'l1_ratio': 0.3858463724033898}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2624035655272912
Fold 2 IBS: 0.176214312676889
Fold 3 IBS: 0.22873606413256026
Fold 4 IBS: 0.2460885406259579
Fold 5 IBS: 0.18882855281808936
[I 2024-04-16 09:47:32,269] Trial 43 finished with value: 0.22045420715615754 and parameters: {'l1_ratio': 0.2693119880401368}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2622697933025317
Fold 2 IBS: 0.22622994789999248
Fold 3 IBS: 0.22876499013690807
Fold 4 IBS: 0.2459802477791167
Fold 5 IBS: 0.1888276332301391
[I 2024-04-16 09:47:32,526] Trial 44 finished with value: 0.2304145224697376 and parameters: {'l1_ratio': 0.21455471840342855}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26239301899197154
Fold 2 IBS: 0.1763078714755289
Fold 3 IBS: 0.19815313910717317
Fold 4 IBS: 0.24625941104254315
Fold 5 IBS: 0.18893194919966913
[I 2024-04-16 09:47:32,889] Trial 45 finished with value: 0.21440907796337716 and parameters: {'l1_ratio': 0.5259358639547652}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26244033445112036
Fold 2 IBS: 0.1762823339600738
Fold 3 IBS: 0.19812965138208652
Fold 4 IBS: 0.2462068895663617
Fold 5 IBS: 0.18887298347214798
[I 2024-04-16 09:47:33,291] Trial 46 finished with value: 0.21438643856635808 and parameters: {'l1_ratio': 0.4187788348196837}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623206434509741
Fold 2 IBS: 0.17623445595715115
Fold 3 IBS: 0.19812703253600047
Fold 4 IBS: 0.24612113764115892
Fold 5 IBS: 0.18884717773762927
[I 2024-04-16 09:47:33,688] Trial 47 finished with value: 0.21433008946458276 and parameters: {'l1_ratio': 0.3455157312935835}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26232227570831285
Fold 2 IBS: 0.17624148220353417
Fold 3 IBS: 0.19811944124634354
Fold 4 IBS: 0.24600620960171504
Fold 5 IBS: 0.18884676872130524
[I 2024-04-16 09:47:34,097] Trial 48 finished with value: 0.21430723549624214 and parameters: {'l1_ratio': 0.29917676765202983}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26228565405722615
Fold 2 IBS: 0.17622369414606348
Fold 3 IBS: 0.19811088869352403
Fold 4 IBS: 0.24610443237598417
Fold 5 IBS: 0.1888382347245271
[I 2024-04-16 09:47:34,464] Trial 49 finished with value: 0.21431258079946502 and parameters: {'l1_ratio': 0.2940319916839086}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26227781141136786
Fold 2 IBS: 0.1762303789196913
Fold 3 IBS: 0.22875363917123687

Fold 4 IBS: 0.2459825779240315
Fold 5 IBS: 0.18882513676069446
[I 2024-04-16 09:47:34,794] Trial 50 finished with value: 0.22041390883740436 and parameters: {'l1_ratio': 0.2330625599543072}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623859572633629
Fold 2 IBS: 0.17627844132590192
Fold 3 IBS: 0.19806615177383452
Fold 4 IBS: 0.24606570142281473
Fold 5 IBS: 0.18883773320582636
[I 2024-04-16 09:47:35,241] Trial 51 finished with value: 0.21432679699834808 and parameters: {'l1_ratio': 0.28707431039828885}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2622418083206451
Fold 2 IBS: 0.22819689871071516
Fold 3 IBS: 0.2288241611255437
Fold 4 IBS: 0.2384579244113865
Fold 5 IBS: 0.22669399356844042
[I 2024-04-16 09:47:35,447] Trial 52 finished with value: 0.23688295722734617 and parameters: {'l1_ratio': 0.1404992778339893}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623253164824203
Fold 2 IBS: 0.17624295609223664
Fold 3 IBS: 0.19812779621958032
Fold 4 IBS: 0.24600608262901755
Fold 5 IBS: 0.18884874361458537
[I 2024-04-16 09:47:35,922] Trial 53 finished with value: 0.21431017900756802 and parameters: {'l1_ratio': 0.2996097481706516}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26225226262753243
Fold 2 IBS: 0.22627946834889734
Fold 3 IBS: 0.22876623215166825
Fold 4 IBS: 0.2459664319688002
Fold 5 IBS: 0.18882886154733866
[I 2024-04-16 09:47:36,315] Trial 54 finished with value: 0.23041865132884737 and parameters: {'l1_ratio': 0.21266696387804623}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2624248019847866
Fold 2 IBS: 0.17628613248005648
Fold 3 IBS: 0.1981133794185703
Fold 4 IBS: 0.24608360666391235
Fold 5 IBS: 0.18885958349068177
[I 2024-04-16 09:47:36,839] Trial 55 finished with value: 0.21435350080760154 and parameters: {'l1_ratio': 0.36387037018080215}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623491554412069
Fold 2 IBS: 0.1762566252288526
Fold 3 IBS: 0.1980595907133851
Fold 4 IBS: 0.24603110064422445
Fold 5 IBS: 0.18884017587253452
[I 2024-04-16 09:47:37,317] Trial 56 finished with value: 0.2143073295800407 and parameters: {'l1_ratio': 0.3036754532885025}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623439472737329
Fold 2 IBS: 0.1762923546903133
Fold 3 IBS: 0.1981406722846341
Fold 4 IBS: 0.2462253566810421
Fold 5 IBS: 0.1888975971511891
[I 2024-04-16 09:47:37,711] Trial 57 finished with value: 0.21437998561618227 and parameters: {'l1_ratio': 0.4850807566684493}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623553491511387
Fold 2 IBS: 0.17625976589747352
Fold 3 IBS: 0.19805990192844358
Fold 4 IBS: 0.24603385853996015
Fold 5 IBS: 0.18884440570252273
[I 2024-04-16 09:47:38,168] Trial 58 finished with value: 0.21431065624390774 and parameters: {'l1_ratio': 0.3046225950910994}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2460827215120409
Fold 2 IBS: 0.2301254607738081
Fold 3 IBS: 0.22889784204115401
Fold 4 IBS: 0.24017681493261747
Fold 5 IBS: 0.22804643517883424
[I 2024-04-16 09:47:38,368] Trial 59 finished with value: 0.23466585488769093 and parameters: {'l1_ratio': 0.06942505629653908}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623168125662022
Fold 2 IBS: 0.17623883295447712
Fold 3 IBS: 0.1981174035467613
Fold 4 IBS: 0.24612868373447774
Fold 5 IBS: 0.1888315774959957
[I 2024-04-16 09:47:38,754] Trial 60 finished with value: 0.2143266620595828 and parameters: {'l1_ratio': 0.2984011121961004}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26236836797794977
Fold 2 IBS: 0.1761993982347044
Fold 3 IBS: 0.2287471442431544
Fold 4 IBS: 0.24606207555234602
Fold 5 IBS: 0.18883734986499254
[I 2024-04-16 09:47:39,171] Trial 61 finished with value: 0.2204428671746294 and parameters: {'l1_ratio': 0.2450019513793636}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623410673530839
Fold 2 IBS: 0.17625059259431183
Fold 3 IBS: 0.19808179331785877
Fold 4 IBS: 0.24602112320094274
Fold 5 IBS: 0.1888459690768028
[I 2024-04-16 09:47:39,540] Trial 62 finished with value: 0.21430810910860001 and parameters: {'l1_ratio': 0.3018698767290804}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26240585373041403
Fold 2 IBS: 0.1762761164821611
Fold 3 IBS: 0.19811320847564218
Fold 4 IBS: 0.2460666246181835
Fold 5 IBS: 0.18884485724698322
[I 2024-04-16 09:47:40,073] Trial 63 finished with value: 0.2143413321106768 and parameters: {'l1_ratio': 0.36033669030006676}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26232343297543015
Fold 2 IBS: 0.1762460073408241
Fold 3 IBS: 0.2287328949540112
Fold 4 IBS: 0.24600994258212508
Fold 5 IBS: 0.18882901929972393
[I 2024-04-16 09:47:40,486] Trial 64 finished with value: 0.22042825943042285 and parameters: {'l1_ratio': 0.2778442427165749}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623195523758977
Fold 2 IBS: 0.22692733666379353
Fold 3 IBS: 0.22878375063823325
Fold 4 IBS: 0.2460343934896084
Fold 5 IBS: 0.18881922358762399
[I 2024-04-16 09:47:40,763] Trial 65 finished with value: 0.2305768513510314 and parameters: {'l1_ratio': 0.18808759383716844}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26234536744331677
Fold 2 IBS: 0.17630453760770934
Fold 3 IBS: 0.1981311986173345
Fold 4 IBS: 0.24612042166060455
Fold 5 IBS: 0.18886499626872263
[I 2024-04-16 09:47:41,283] Trial 66 finished with value: 0.21435330431953753 and parameters: {'l1_ratio': 0.4284327966462061}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26235483257799036
Fold 2 IBS: 0.17624317350111302
Fold 3 IBS: 0.19804536568281542
Fold 4 IBS: 0.24614146793419378
Fold 5 IBS: 0.1888543403062047
[I 2024-04-16 09:47:41,800] Trial 67 finished with value: 0.21432783600046346 and parameters: {'l1_ratio': 0.37627163301886574}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26239911265157245
Fold 2 IBS: 0.17628186834097923
Fold 3 IBS: 0.19806078217861375
Fold 4 IBS: 0.24607050287085366
Fold 5 IBS: 0.18883018433991064
[I 2024-04-16 09:47:42,267] Trial 68 finished with value: 0.21432849007638594 and parameters: {'l1_ratio': 0.31143001851546676}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623701850047736
Fold 2 IBS: 0.1761995313140227
Fold 3 IBS: 0.22874712775781844
Fold 4 IBS: 0.2460622802590892
Fold 5 IBS: 0.1888375153249923
[I 2024-04-16 09:47:42,681] Trial 69 finished with value: 0.22044332793213925 and parameters: {'l1_ratio': 0.24503391744441205}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.26231506120268105
Fold 2 IBS: 0.22769051036522
Fold 3 IBS: 0.2288071573596886
Fold 4 IBS: 0.23802169775204454
Fold 5 IBS: 0.18880286277510616
[I 2024-04-16 09:47:42,989] Trial 70 finished with value: 0.22912745789094807 and parameters: {'l1_ratio': 0.15939527513206964}. Best is trial 32 with value: 0.2143058730064582.
Fold 1 IBS: 0.2623504997693437
Fold 2 IBS: 0.17625064367006135
Fold 3 IBS: 0.1980524068749031
Fold 4 IBS: 0.24602290320261727
Fold 5 IBS: 0.18884396582239196
[I 2024-04-16 09:47:43,410] Trial 71 finished with value: 0.21430408386786345 and parameters: {'l1_ratio': 0.32614159377093416}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623389471848804
Fold 2 IBS: 0.17624508141199735
Fold 3 IBS: 0.19813221382706486
Fold 4 IBS: 0.24614058255733193
Fold 5 IBS: 0.18884394590426148
[I 2024-04-16 09:47:43,788] Trial 72 finished with value: 0.2143401541771072 and parameters: {'l1_ratio': 0.3243864236389665}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623835146080439
Fold 2 IBS: 0.17627726173291994
Fold 3 IBS: 0.19806480603941048
Fold 4 IBS: 0.24606135567800283
Fold 5 IBS: 0.18883615161209358
[I 2024-04-16 09:47:44,192] Trial 73 finished with value: 0.21432461793409413 and parameters: {'l1_ratio': 0.2867293725778652}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26237828235708555
Fold 2 IBS: 0.17624930822452828
Fold 3 IBS: 0.1980754245661868
Fold 4 IBS: 0.24615312667548556
Fold 5 IBS: 0.1888773567918294
[I 2024-04-16 09:47:44,586] Trial 74 finished with value: 0.2143466997230231 and parameters: {'l1_ratio': 0.40687937536568586}. Best is trial 71 with value: 0.21430408386786345.

Fold 1 IBS: 0.2623075377468284
Fold 2 IBS: 0.17624816741614854
Fold 3 IBS: 0.22876227158276394
Fold 4 IBS: 0.24601075283931992
Fold 5 IBS: 0.18881592231016656
[I 2024-04-16 09:47:45,093] Trial 75 finished with value: 0.22042893037904548 and parameters: {'l1_ratio': 0.21877076880955348}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26238165234868044
Fold 2 IBS: 0.17626360950860542
Fold 3 IBS: 0.1980492988603829
Fold 4 IBS: 0.24617008805051238
Fold 5 IBS: 0.18884853158303821
[I 2024-04-16 09:47:45,550] Trial 76 finished with value: 0.21434263607024384 and parameters: {'l1_ratio': 0.3557517419143058}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26226999857264344
Fold 2 IBS: 0.17622334636572434
Fold 3 IBS: 0.22874420184293884
Fold 4 IBS: 0.2461012750413376
Fold 5 IBS: 0.18882727787725043
[I 2024-04-16 09:47:46,019] Trial 77 finished with value: 0.22043321993997894 and parameters: {'l1_ratio': 0.25086758887372973}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2624360634374499
Fold 2 IBS: 0.17627088464396548
Fold 3 IBS: 0.19813808217549084
Fold 4 IBS: 0.24619599573003803
Fold 5 IBS: 0.18888256283381996
[I 2024-04-16 09:47:47,169] Trial 78 finished with value: 0.21438471776415283 and parameters: {'l1_ratio': 0.4459562608904493}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26235633159334587
Fold 2 IBS: 0.17625567323103786
Fold 3 IBS: 0.19805882763028484
Fold 4 IBS: 0.2460309977405004
Fold 5 IBS: 0.18884287577859024
[I 2024-04-16 09:47:47,803] Trial 79 finished with value: 0.21430894119475186 and parameters: {'l1_ratio': 0.32770681493409676}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26253783397492386
Fold 2 IBS: 0.17635642433738577
Fold 3 IBS: 0.19824709644956187
Fold 4 IBS: 0.2463222890715719
Fold 5 IBS: 0.1891255331343618
[I 2024-04-16 09:47:48,199] Trial 80 finished with value: 0.214517835393561 and parameters: {'l1_ratio': 0.7535102229130162}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26237184929750385
Fold 2 IBS: 0.1762623750622442
Fold 3 IBS: 0.19805829253056248
Fold 4 IBS: 0.24603967016753459
Fold 5 IBS: 0.1888362742580795
[I 2024-04-16 09:47:48,616] Trial 81 finished with value: 0.21431369226318492 and parameters: {'l1_ratio': 0.3298593762279284}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26231043934618986
Fold 2 IBS: 0.17623574043698387
Fold 3 IBS: 0.19811499105386743
Fold 4 IBS: 0.24612382149734663
Fold 5 IBS: 0.18883316499431088
[I 2024-04-16 09:47:49,029] Trial 82 finished with value: 0.21432363146573974 and parameters: {'l1_ratio': 0.29749988547426276}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.262264489909991
Fold 2 IBS: 0.17621571413735973
Fold 3 IBS: 0.22873591898504497
Fold 4 IBS: 0.24609071624071902
Fold 5 IBS: 0.1888303162729614
[I 2024-04-16 09:47:49,406] Trial 83 finished with value: 0.22042743110921523 and parameters: {'l1_ratio': 0.2696812969370707}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623876396395765
Fold 2 IBS: 0.17627167290166024
Fold 3 IBS: 0.19805008574228294
Fold 4 IBS: 0.24605776134591348
Fold 5 IBS: 0.1888474714991434
[I 2024-04-16 09:47:49,936] Trial 84 finished with value: 0.2143229262257153 and parameters: {'l1_ratio': 0.33288498992820414}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2624298884246991
Fold 2 IBS: 0.1762832298649637
Fold 3 IBS: 0.19812252505237551
Fold 4 IBS: 0.24607719339860593
Fold 5 IBS: 0.18885617627298149
[I 2024-04-16 09:47:50,591] Trial 85 finished with value: 0.21435380260272513 and parameters: {'l1_ratio': 0.38985386323647214}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26233648272490007
Fold 2 IBS: 0.22646820787301786
Fold 3 IBS: 0.22877109580418986
Fold 4 IBS: 0.24604083106504382
Fold 5 IBS: 0.18880894389292666
[I 2024-04-16 09:47:50,859] Trial 86 finished with value: 0.23048511227201565 and parameters: {'l1_ratio': 0.20548407204266242}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.262336472619579
Fold 2 IBS: 0.17625835293770395
Fold 3 IBS: 0.22874001383142326
Fold 4 IBS: 0.24603176548581263
Fold 5 IBS: 0.18882445377243154
[I 2024-04-16 09:47:51,393] Trial 87 finished with value: 0.22043821172939007 and parameters: {'l1_ratio': 0.25987230938505107}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26236376378649673
Fold 2 IBS: 0.17626307471069216
Fold 3 IBS: 0.19806421832178592
Fold 4 IBS: 0.2460417706613497
Fold 5 IBS: 0.18884159663454583
[I 2024-04-16 09:47:51,829] Trial 88 finished with value: 0.21431488482297406 and parameters: {'l1_ratio': 0.3056257858714368}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623028599140646
Fold 2 IBS: 0.17629577923703366
Fold 3 IBS: 0.19812657260353211
Fold 4 IBS: 0.24609996053456845
Fold 5 IBS: 0.18885098128644187
[I 2024-04-16 09:47:52,423] Trial 89 finished with value: 0.21433523071512814 and parameters: {'l1_ratio': 0.36732883821627954}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26228133601411735
Fold 2 IBS: 0.17623211333220803
Fold 3 IBS: 0.2287534052116353
Fold 4 IBS: 0.2459853839400173
Fold 5 IBS: 0.1888272865865252
[I 2024-04-16 09:47:52,821] Trial 90 finished with value: 0.22041590501690064 and parameters: {'l1_ratio': 0.23347240722228124}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.262355975724566
Fold 2 IBS: 0.17625338837322
Fold 3 IBS: 0.19805589224464978
Fold 4 IBS: 0.24602728718969208
Fold 5 IBS: 0.18883975364157474
[I 2024-04-16 09:47:53,207] Trial 91 finished with value: 0.2143064594347405 and parameters: {'l1_ratio': 0.3269782779530571}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623578454677615
Fold 2 IBS: 0.17625084087799356
Fold 3 IBS: 0.198052611420694
Fold 4 IBS: 0.24614957235724344
Fold 5 IBS: 0.18884360116937668
[I 2024-04-16 09:47:53,717] Trial 92 finished with value: 0.21433089425861382 and parameters: {'l1_ratio': 0.35142020185888834}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26235440466848053
Fold 2 IBS: 0.17626374651365526
Fold 3 IBS: 0.22873122273156404
Fold 4 IBS: 0.24604146306218772
Fold 5 IBS: 0.18883956431066473
[I 2024-04-16 09:47:54,255] Trial 93 finished with value: 0.2204460802573104 and parameters: {'l1_ratio': 0.2828344338418752}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623619552534632
Fold 2 IBS: 0.17626220263138256
Fold 3 IBS: 0.19806318789691635
Fold 4 IBS: 0.2460403234105778
Fold 5 IBS: 0.18884042602440018
[I 2024-04-16 09:47:54,755] Trial 94 finished with value: 0.21431361904334803 and parameters: {'l1_ratio': 0.30536084795615165}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623581430156407
Fold 2 IBS: 0.17625443062205662
Fold 3 IBS: 0.1980573098823407
Fold 4 IBS: 0.24602902270987892
Fold 5 IBS: 0.1888411836213762
[I 2024-04-16 09:47:55,185] Trial 95 finished with value: 0.21430801797025864 and parameters: {'l1_ratio': 0.32731026935145874}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26236110410464797
Fold 2 IBS: 0.1762412017373265
Fold 3 IBS: 0.19807338597632682
Fold 4 IBS: 0.24613992537426274
Fold 5 IBS: 0.18885835960881578
[I 2024-04-16 09:47:55,667] Trial 96 finished with value: 0.21433479536027597 and parameters: {'l1_ratio': 0.4038587232697288}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.26229511230344266
Fold 2 IBS: 0.17629857396627696
Fold 3 IBS: 0.19811327528970887
Fold 4 IBS: 0.24610096918914595
Fold 5 IBS: 0.1888585664171219
[I 2024-04-16 09:47:56,255] Trial 97 finished with value: 0.21433329943313928 and parameters: {'l1_ratio': 0.34138942292691604}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2622903857431882
Fold 2 IBS: 0.22840405493903365
Fold 3 IBS: 0.2288314268807414
Fold 4 IBS: 0.2386381763215847
Fold 5 IBS: 0.22683904461883922
[I 2024-04-16 09:47:56,494] Trial 98 finished with value: 0.23700061770067743 and parameters: {'l1_ratio': 0.13279960796640858}. Best is trial 71 with value: 0.21430408386786345.
Fold 1 IBS: 0.2623420188040605
Fold 2 IBS: 0.17623706861901292
Fold 3 IBS: 0.19804733405043587
Fold 4 IBS: 0.24613169054827544
Fold 5 IBS: 0.18885593305219275
[I 2024-04-16 09:47:57,331] Trial 99 finished with value: 0.2143228090147955 and parameters: {'l1_ratio': 0.37413441004314285}. Best is trial 71 with value: 0.21430408386786345.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.21430408386786345], datetime_start=datetime.datetime(2024, 4, 16, 9, 47, 42, 992992), datetime_complete=datetime.datetime(2024, 4, 16, 9, 47, 43, 409891), params={'l1_ratio': 0.32614159377093416}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.21430408386786345

In [110]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [111]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.684
train_ibs:  0.214

#### Test

In [112]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [113]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.6964995386793018)

test_cindex : 0.506

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.32614159377093416)

test_ibs:  0.282

In [114]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [115]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:47:57,714] A new study created in memory with name: no-name-506e6cb8-9e1b-4b72-b750-49ae36620c1f

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6972111553784861
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 09:48:02,714] Trial 0 finished with value: 0.7015133437732377 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7015133437732377.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:48:07,264] Trial 1 finished with value: 0.715218169153616 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 09:48:11,883] Trial 2 finished with value: 0.7119189620589541 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:48:14,664] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:48:16,014] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 09:48:20,008] Trial 5 finished with value: 0.7121029532913535 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 09:48:28,305] Trial 6 finished with value: 0.6959270877461442 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:48:32,092] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 09:48:40,336] Trial 8 finished with value: 0.5201716738197425 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 09:48:43,971] Trial 9 finished with value: 0.7048820200888208 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:48:44,396] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 09:48:47,375] Trial 11 finished with value: 0.696132525127542 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:48:54,369] Trial 12 finished with value: 0.7089711984569995 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 373, 'oob_score': False, 'max_samples': 0.48792003918647286, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10661539149160613, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 09:49:02,421] Trial 13 finished with value: 0.7073097024475669 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 490, 'oob_score': False, 'max_samples': 0.765021860726683, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017530569165213797, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.5756972111553785
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 09:49:04,109] Trial 14 finished with value: 0.711078644842627 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.48589405900235655, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17488909350671974, 'warm_start': True}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7209302325581395

Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 09:49:09,780] Trial 15 finished with value: 0.7085249151159188 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 338, 'oob_score': False, 'max_samples': 0.8070084084612321, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08673913474661687, 'warm_start': False}. Best is trial 1 with value: 0.715218169153616.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 09:49:12,758] Trial 16 finished with value: 0.7183912334548377 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.6501934815344157, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00010083006590155819, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 09:49:15,390] Trial 17 finished with value: 0.7106559823409215 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 18, 'n_estimators': 226, 'oob_score': False, 'max_samples': 0.9778223683479524, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16544550098450153, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:49:17,032] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 150, 'oob_score': True, 'max_samples': 0.6669276636557021, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.38335524316027697, 'warm_start': True}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6802575107296137
[I 2024-04-16 09:49:17,597] Trial 19 finished with value: 0.695639961397594 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.8436981317418756, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07207598742102975, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 09:49:21,489] Trial 20 finished with value: 0.6577634118331709 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 20, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.3939412338384674, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13609321171626237, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 09:49:28,611] Trial 21 finished with value: 0.7007057680024623 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.5732944857687029, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.003273942033913447, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 09:49:30,809] Trial 22 finished with value: 0.7135512798752374 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.7091404347150854, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.055266023963435856, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 09:49:32,647] Trial 23 finished with value: 0.7112009224484761 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 8, 'n_estimators': 163, 'oob_score': False, 'max_samples': 0.7026509113834132, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.053844695862474326, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 09:49:33,675] Trial 24 finished with value: 0.7178172421409688 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.7398874228753395, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.19081930965633345, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:49:34,668] Trial 25 finished with value: 0.7085079081468694 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 72, 'oob_score': False, 'max_samples': 0.8438384168771312, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1975193207120556, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 09:49:35,575] Trial 26 finished with value: 0.6901365994143193 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 91, 'oob_score': True, 'max_samples': 0.5392386052567728, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24293351675631525, 'warm_start': True}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7112403100775194
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 09:49:35,824] Trial 27 finished with value: 0.6636398994204891 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 1, 'oob_score': False, 'max_samples': 0.7539230686816791, 'max_features': None, 'min_weight_fraction_leaf': 0.1340823826164942, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6394849785407726
[I 2024-04-16 09:49:38,643] Trial 28 finished with value: 0.6905535781851404 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 13, 'n_estimators': 251, 'oob_score': False, 'max_samples': 0.6413752761890007, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2069838392004565, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6587982832618026
[I 2024-04-16 09:49:40,542] Trial 29 finished with value: 0.6981089271326458 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 19, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.7472642182524794, 'max_features': None, 'min_weight_fraction_leaf': 0.25087036098392035, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.

Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 09:49:47,847] Trial 30 finished with value: 0.7161275052654187 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 303, 'oob_score': False, 'max_samples': 0.9063670455515496, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09013372355598072, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6866952789699571
[I 2024-04-16 09:49:55,854] Trial 31 finished with value: 0.7111257466681262 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 16, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.8980407898083677, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0911873865066101, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 09:50:00,866] Trial 32 finished with value: 0.7153407310231418 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 221, 'oob_score': False, 'max_samples': 0.9796877796986787, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12418929910599076, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 09:50:05,179] Trial 33 finished with value: 0.7136610271176828 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.9948199315832256, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1494797518276191, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 09:50:12,344] Trial 34 finished with value: 0.7112279182337147 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.8999028788341759, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18969729705664468, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 09:50:16,548] Trial 35 finished with value: 0.7071807726361479 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 12, 'n_estimators': 212, 'oob_score': False, 'max_samples': 0.8552429302322142, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': False}. Best is trial 16 with value: 0.7183912334548377.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 09:50:18,623] Trial 36 finished with value: 0.76339262785359 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 412, 'oob_score': False, 'max_samples': 0.9497250907713197, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22251129147306872, 'warm_start': True}. Best is trial 36 with value: 0.76339262785359.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 09:50:20,056] Trial 37 finished with value: 0.7649971395444376 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.9355782808371594, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22467937733257806, 'warm_start': True}. Best is trial 37 with value: 0.7649971395444376.
Fold 1 C-index: 0.6713147410358565
Fold 2 C-index: 0.8081395348837209
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.7532188841201717
[I 2024-04-16 09:50:21,627] Trial 38 finished with value: 0.7488564506310387 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.799644415086533, 'max_features': None, 'min_weight_fraction_leaf': 0.2857691335120822, 'warm_start': True}. Best is trial 37 with value: 0.7649971395444376.
Fold 1 C-index: 0.6713147410358565
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.7167381974248928
[I 2024-04-16 09:50:25,160] Trial 39 finished with value: 0.7273051007549273 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 426, 'oob_score': True, 'max_samples': 0.9487292367646679, 'max_features': None, 'min_weight_fraction_leaf': 0.38045764561682943, 'warm_start': True}. Best is trial 37 with value: 0.7649971395444376.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.6787234042553192
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 09:50:28,908] Trial 40 finished with value: 0.7290760900331354 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 413, 'oob_score': True, 'max_samples': 0.9574468405258022, 'max_features': None, 'min_weight_fraction_leaf': 0.38462517942590646, 'warm_start': True}. Best is trial 37 with value: 0.7649971395444376.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.674468085106383
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 09:50:32,002] Trial 41 finished with value: 0.7257582940819425 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 420, 'oob_score': True, 'max_samples': 0.9395591381081873, 'max_features': None, 'min_weight_fraction_leaf': 0.3810462118318134, 'warm_start': True}. Best is trial 37 with value: 0.7649971395444376.
Fold 1 C-index: 0.6274900398406374
Fold 2 C-index: 0.7461240310077519
Fold 3 C-index: 0.6914893617021277
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 09:50:36,622] Trial 42 finished with value: 0.7028426483567393 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 414, 'oob_score': True, 'max_samples': 0.929145514566076, 'max_features': None, 'min_weight_fraction_leaf': 0.42795957065383305, 'warm_start': True}. Best is trial 37 with value: 0.7649971395444376.
Fold 1 C-index: 0.701195219123506
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 09:50:41,571] Trial 43 finished with value: 0.7673129692752523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.9598582891146799, 'max_features': None, 'min_weight_fraction_leaf': 0.296848051125248, 'warm_start': True}. Best is trial 43 with value: 0.7673129692752523.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.8042635658914729
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 09:50:45,992] Trial 44 finished with value: 0.7636908484178506 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 484, 'oob_score': True, 'max_samples': 0.871040135174336, 'max_features': None, 'min_weight_fraction_leaf': 0.28123237747956786, 'warm_start': True}. Best is trial 43 with value: 0.7673129692752523.

Fold 1 C-index: 0.6752988047808764
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7085106382978723
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 09:50:50,869] Trial 45 finished with value: 0.7409296909573337 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.8000771074935826, 'max_features': None, 'min_weight_fraction_leaf': 0.2985130489821115, 'warm_start': True}. Best is trial 43 with value: 0.7673129692752523.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.8081395348837209
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7699619771863118
Fold 5 C-index: 0.7832618025751072
[I 2024-04-16 09:50:55,335] Trial 46 finished with value: 0.7608680685406242 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.8691759086058688, 'max_features': None, 'min_weight_fraction_leaf': 0.28518691459210166, 'warm_start': True}. Best is trial 43 with value: 0.7673129692752523.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 09:50:58,796] Trial 47 finished with value: 0.742783729184645 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 456, 'oob_score': True, 'max_samples': 0.8728936139077907, 'max_features': None, 'min_weight_fraction_leaf': 0.3346495305615396, 'warm_start': True}. Best is trial 43 with value: 0.7673129692752523.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 09:51:02,612] Trial 48 finished with value: 0.7755873201424728 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 465, 'oob_score': True, 'max_samples': 0.8756494381263603, 'max_features': None, 'min_weight_fraction_leaf': 0.2305315761415458, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:51:08,434] Trial 49 finished with value: 0.7657898041053744 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.9916395995330168, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22858391293265978, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:51:12,827] Trial 50 finished with value: 0.7658261605806143 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.9953982847625787, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22705950772893763, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 09:51:17,002] Trial 51 finished with value: 0.7664669580920409 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.9923448664664665, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22447804518225306, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:51:20,632] Trial 52 finished with value: 0.76506570430685 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 471, 'oob_score': True, 'max_samples': 0.9847249368568864, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2253504305284242, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.785171102661597
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:51:23,650] Trial 53 finished with value: 0.763948180783858 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 472, 'oob_score': True, 'max_samples': 0.9988101512974772, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2365294184307653, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:51:26,689] Trial 54 finished with value: 0.7685472749016833 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 11, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.99424751966741, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26283432660195793, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:51:30,828] Trial 55 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.14215408816587916, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25781795730435875, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 09:51:33,368] Trial 56 finished with value: 0.7217011739388147 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 12, 'n_estimators': 383, 'oob_score': True, 'max_samples': 0.8966059578948761, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3270436258533716, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8003802281368821
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 09:51:37,311] Trial 57 finished with value: 0.7661316367802026 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.9993822947734584, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2708283939230126, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 09:51:41,447] Trial 58 finished with value: 0.7557849080350894 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 441, 'oob_score': True, 'max_samples': 0.9139220718027778, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2681248768228028, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:51:46,627] Trial 59 finished with value: 0.7157572898185742 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.8279590218191206, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3103615071813942, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.

Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:51:50,888] Trial 60 finished with value: 0.7657439763875603 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.9627980613714565, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26936642929291454, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:51:54,474] Trial 61 finished with value: 0.721845905588786 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 474, 'oob_score': True, 'max_samples': 0.9890431223874007, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.35766383123619266, 'warm_start': True}. Best is trial 48 with value: 0.7755873201424728.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 09:51:57,134] Trial 62 finished with value: 0.7817863374857608 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.964114802617666, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17601989324870537, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 09:52:00,397] Trial 63 finished with value: 0.7793996235837597 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 394, 'oob_score': True, 'max_samples': 0.9564157539578013, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17494779400733246, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 09:52:03,115] Trial 64 finished with value: 0.7658842794275048 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 396, 'oob_score': True, 'max_samples': 0.9254685341405605, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18184895718466598, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 09:52:06,052] Trial 65 finished with value: 0.7786244297853101 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 446, 'oob_score': True, 'max_samples': 0.9552508630325125, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17698856458935044, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 09:52:08,753] Trial 66 finished with value: 0.7811379807317389 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 440, 'oob_score': True, 'max_samples': 0.8820337627967693, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1566811915615436, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 09:52:11,854] Trial 67 finished with value: 0.774150774195909 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 437, 'oob_score': True, 'max_samples': 0.9031254454741277, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15570902039140344, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 09:52:15,603] Trial 68 finished with value: 0.7738979642274275 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 367, 'oob_score': True, 'max_samples': 0.7774126663207679, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15142690779565057, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:52:18,183] Trial 69 finished with value: 0.7752820012238011 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 357, 'oob_score': True, 'max_samples': 0.778820255277365, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16264281701449784, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:52:20,743] Trial 70 finished with value: 0.7698597763884593 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 329, 'oob_score': True, 'max_samples': 0.8275065092660108, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17253956230843562, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 09:52:23,841] Trial 71 finished with value: 0.7740675988956462 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 360, 'oob_score': True, 'max_samples': 0.8788887271916276, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16013492902000126, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 09:52:26,325] Trial 72 finished with value: 0.7685867745979611 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.8843551857597599, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.205898058250961, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 09:52:29,286] Trial 73 finished with value: 0.77153657718673 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 397, 'oob_score': True, 'max_samples': 0.8299293118091191, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15595291487251525, 'warm_start': True}. Best is trial 62 with value: 0.7817863374857608.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 09:52:31,721] Trial 74 finished with value: 0.7847081628083574 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 14, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.8584830946493216, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11054864758221403, 'warm_start': True}. Best is trial 74 with value: 0.7847081628083574.

Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 09:52:34,505] Trial 75 finished with value: 0.7854980941314924 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 434, 'oob_score': True, 'max_samples': 0.7817597321684238, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12119673612963944, 'warm_start': True}. Best is trial 75 with value: 0.7854980941314924.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 09:52:36,555] Trial 76 finished with value: 0.757834094731246 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 355, 'oob_score': True, 'max_samples': 0.3653273720661841, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10475994227109633, 'warm_start': True}. Best is trial 75 with value: 0.7854980941314924.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 09:52:38,702] Trial 77 finished with value: 0.777975776175067 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 332, 'oob_score': True, 'max_samples': 0.7841323611085548, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13769356278763065, 'warm_start': True}. Best is trial 75 with value: 0.7854980941314924.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 09:52:40,987] Trial 78 finished with value: 0.7863560393871486 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 433, 'oob_score': True, 'max_samples': 0.8538419777473767, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14008068057578502, 'warm_start': True}. Best is trial 78 with value: 0.7863560393871486.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 09:52:43,020] Trial 79 finished with value: 0.7814125366376099 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 375, 'oob_score': True, 'max_samples': 0.8055230876320885, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12447021494377211, 'warm_start': True}. Best is trial 78 with value: 0.7863560393871486.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 09:52:45,845] Trial 80 finished with value: 0.7937224690928317 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 375, 'oob_score': True, 'max_samples': 0.7314498178659028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0726530556006501, 'warm_start': True}. Best is trial 80 with value: 0.7937224690928317.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:52:48,232] Trial 81 finished with value: 0.788677202186499 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 370, 'oob_score': True, 'max_samples': 0.8468208140916632, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06953196571625712, 'warm_start': True}. Best is trial 80 with value: 0.7937224690928317.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 09:52:50,530] Trial 82 finished with value: 0.7856717500009432 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 405, 'oob_score': True, 'max_samples': 0.8409428162831655, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07542479104426592, 'warm_start': True}. Best is trial 80 with value: 0.7937224690928317.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 09:52:52,701] Trial 83 finished with value: 0.7937588255680714 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 317, 'oob_score': True, 'max_samples': 0.6987295797771368, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07398794875102636, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 09:52:55,498] Trial 84 finished with value: 0.7929472752943821 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 373, 'oob_score': True, 'max_samples': 0.7064702574947085, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07320181342699775, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 09:52:58,450] Trial 85 finished with value: 0.7937118797562134 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.7388697819331961, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06792437926502476, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:53:00,379] Trial 86 finished with value: 0.7912958177916765 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 288, 'oob_score': True, 'max_samples': 0.6831570774387574, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.044621000514041484, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 09:53:02,128] Trial 87 finished with value: 0.7912598851594929 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.689216197401876, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07027363673207727, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:53:04,102] Trial 88 finished with value: 0.7912378423658823 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 271, 'oob_score': True, 'max_samples': 0.681062462095111, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07009789262943517, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:53:05,580] Trial 89 finished with value: 0.7912083673165117 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 273, 'oob_score': True, 'max_samples': 0.6795080372835197, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03405394406964266, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:53:07,047] Trial 90 finished with value: 0.7912083673165117 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 268, 'oob_score': True, 'max_samples': 0.6711999827196613, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03752509679928332, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:53:08,794] Trial 91 finished with value: 0.7912810802669912 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 280, 'oob_score': True, 'max_samples': 0.6825932700003285, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04028695011559666, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:53:10,492] Trial 92 finished with value: 0.7936461752184378 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 269, 'oob_score': True, 'max_samples': 0.6830716877557337, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03599046060867248, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8240343347639485
[I 2024-04-16 09:53:12,117] Trial 93 finished with value: 0.7911429596349574 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 287, 'oob_score': True, 'max_samples': 0.6923305805802601, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02138213938814674, 'warm_start': True}. Best is trial 83 with value: 0.7937588255680714.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 09:53:13,946] Trial 94 finished with value: 0.7966880003134948 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.7275622802375871, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010224090801480467, 'warm_start': True}. Best is trial 94 with value: 0.7966880003134948.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 09:53:15,355] Trial 95 finished with value: 0.7958702628649241 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 242, 'oob_score': True, 'max_samples': 0.7308735774587108, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05991320997095104, 'warm_start': True}. Best is trial 94 with value: 0.7966880003134948.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 09:53:17,289] Trial 96 finished with value: 0.7950691749410181 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.7334741083212244, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.007219992833884428, 'warm_start': True}. Best is trial 94 with value: 0.7966880003134948.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 09:53:19,414] Trial 97 finished with value: 0.7942108058423057 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 315, 'oob_score': True, 'max_samples': 0.7275135705226743, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003173901690315499, 'warm_start': True}. Best is trial 94 with value: 0.7966880003134948.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 09:53:21,182] Trial 98 finished with value: 0.7918856482900132 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'max_samples': 0.7278254889723963, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0006960941980402912, 'warm_start': True}. Best is trial 94 with value: 0.7966880003134948.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8745247148288974

[I 2024-04-16 09:53:23,163] A new study created in memory with name: no-name-6a1d20ba-b4f6-408d-bbd7-7a56d70d08ac

Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 09:53:23,141] Trial 99 finished with value: 0.7934792737880211 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.7285231337552333, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.011226041102515898, 'warm_start': True}. Best is trial 94 with value: 0.7966880003134948.


* Best trial for C-index:
 FrozenTrial(number=94, state=TrialState.COMPLETE, values=[0.7966880003134948], datetime_start=datetime.datetime(2024, 4, 16, 9, 53, 12, 123916), datetime_complete=datetime.datetime(2024, 4, 16, 9, 53, 13, 945918), params={'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 281, 'oob_score': True, 'max_samples': 0.7275622802375871, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.010224090801480467, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=94, value=None)


* Best Score for C-index:
 0.7966880003134948

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21328647592716404
Fold 2 IBS: 0.1835933660066504
Fold 3 IBS: 0.24083981487173622
Fold 4 IBS: 0.21064411537664268
Fold 5 IBS: 0.21707283185838072
[I 2024-04-16 09:53:27,482] Trial 0 finished with value: 0.21308732080811482 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21308732080811482.
Fold 1 IBS: 0.22584170079041868
Fold 2 IBS: 0.18806481764204186
Fold 3 IBS: 0.2066294951276907
Fold 4 IBS: 0.21381808663168675
Fold 5 IBS: 0.21187678478023245
[I 2024-04-16 09:53:29,293] Trial 1 finished with value: 0.2092461769944141 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.2092461769944141.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-16 09:53:30,221] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.2092461769944141.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-16 09:53:33,071] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.2092461769944141.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-16 09:53:35,085] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.2092461769944141.
Fold 1 IBS: 0.23694217216337457
Fold 2 IBS: 0.1850255796149742
Fold 3 IBS: 0.20591140564859722
Fold 4 IBS: 0.1950360202756873
Fold 5 IBS: 0.20406480065203486
[I 2024-04-16 09:53:38,234] Trial 5 finished with value: 0.20539599567093364 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.21489005456954638
Fold 2 IBS: 0.19110405949996265
Fold 3 IBS: 0.2562692622202565
Fold 4 IBS: 0.2087162986741698
Fold 5 IBS: 0.21880215873197179
[I 2024-04-16 09:53:41,144] Trial 6 finished with value: 0.21795636673918142 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.24209061214120156
Fold 2 IBS: 0.224973493694478
Fold 3 IBS: 0.22614862691785234
Fold 4 IBS: 0.2383151611057495
Fold 5 IBS: 0.2277634338654156
[I 2024-04-16 09:53:44,241] Trial 7 finished with value: 0.2318582655449394 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-16 09:53:49,423] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.22887374205890612
Fold 2 IBS: 0.182944384612485
Fold 3 IBS: 0.19827770957865165
Fold 4 IBS: 0.22378532551254787
Fold 5 IBS: 0.21421322979153512
[I 2024-04-16 09:53:50,497] Trial 9 finished with value: 0.20961887831082518 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.24645571521465787
Fold 2 IBS: 0.23214351218858914
Fold 3 IBS: 0.23029990468218745
Fold 4 IBS: 0.24091247880712954
Fold 5 IBS: 0.22969387017589088
[I 2024-04-16 09:53:57,457] Trial 10 finished with value: 0.235901096213691 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 495, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011468023462250065}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.23210399067562176
Fold 2 IBS: 0.18548047635136222
Fold 3 IBS: 0.19988527090383337
Fold 4 IBS: 0.22373340598983932
Fold 5 IBS: 0.2178812317786454
[I 2024-04-16 09:53:59,557] Trial 11 finished with value: 0.21181687513986042 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12378097340613392}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.2313742913496488
Fold 2 IBS: 0.1822253778916412
Fold 3 IBS: 0.20936895089004504
Fold 4 IBS: 0.20819091108284854
Fold 5 IBS: 0.20263459369557704
[I 2024-04-16 09:53:59,949] Trial 12 finished with value: 0.20675882498195214 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.7642078791940475, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13207155531457032}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.23590065105872307
Fold 2 IBS: 0.19426853697954669
Fold 3 IBS: 0.22018659775588903
Fold 4 IBS: 0.1916912472595226
Fold 5 IBS: 0.2037206152885519
[I 2024-04-16 09:54:00,435] Trial 13 finished with value: 0.20915352966844666 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 14, 'oob_score': False, 'max_samples': 0.8293737737164385, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09633845721802128}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.24669516431089442
Fold 2 IBS: 0.1836346992834082
Fold 3 IBS: 0.20714905636566933
Fold 4 IBS: 0.20490206142296263
Fold 5 IBS: 0.20580046572669494
[I 2024-04-16 09:54:04,561] Trial 14 finished with value: 0.20963628942192591 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 284, 'oob_score': False, 'max_samples': 0.6604916334814492, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02382938621825248}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.22380821828116884
Fold 2 IBS: 0.1855743084359551
Fold 3 IBS: 0.20839303152988797
Fold 4 IBS: 0.21416701030595428
Fold 5 IBS: 0.2109115023528132
[I 2024-04-16 09:54:06,543] Trial 15 finished with value: 0.2085708141811559 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.9932150048245644, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2762403453179886}. Best is trial 5 with value: 0.20539599567093364.

Fold 1 IBS: 0.23424337993321515
Fold 2 IBS: 0.20035040943640972
Fold 3 IBS: 0.2097886490122235
Fold 4 IBS: 0.22904388924725805
Fold 5 IBS: 0.21965829750736157
[I 2024-04-16 09:54:10,244] Trial 16 finished with value: 0.21861692502729363 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 332, 'oob_score': False, 'max_samples': 0.3880731320622045, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.14354526791362227}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.23268762708589438
Fold 2 IBS: 0.18661155573608948
Fold 3 IBS: 0.202224223144087
Fold 4 IBS: 0.20290750506950714
Fold 5 IBS: 0.20319031918186678
[I 2024-04-16 09:54:13,249] Trial 17 finished with value: 0.20552424604348896 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7684587619660335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07846592181777899}. Best is trial 5 with value: 0.20539599567093364.
Fold 1 IBS: 0.23026187186065697
Fold 2 IBS: 0.18689700473434742
Fold 3 IBS: 0.19943249309173414
Fold 4 IBS: 0.20323800021111899
Fold 5 IBS: 0.20661659749007036
[I 2024-04-16 09:54:16,417] Trial 18 finished with value: 0.20528919347758562 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 247, 'oob_score': True, 'max_samples': 0.6155156742664507, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0589950618585231}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.2272206940671476
Fold 2 IBS: 0.18780721560163613
Fold 3 IBS: 0.20368728815122328
Fold 4 IBS: 0.20801677261563178
Fold 5 IBS: 0.20817665033114055
[I 2024-04-16 09:54:22,368] Trial 19 finished with value: 0.20698172415335586 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 17, 'n_estimators': 410, 'oob_score': True, 'max_samples': 0.6153609285009723, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0010576404251855381}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.23507070661615176
Fold 2 IBS: 0.19450382145555914
Fold 3 IBS: 0.20708753716280068
Fold 4 IBS: 0.22761423876550463
Fold 5 IBS: 0.22276289408538572
[I 2024-04-16 09:54:28,248] Trial 20 finished with value: 0.21740783961708038 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.23419761201309758, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05090168831567499}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.23219023254109752
Fold 2 IBS: 0.18905042977417308
Fold 3 IBS: 0.2018285648281259
Fold 4 IBS: 0.205761107656395
Fold 5 IBS: 0.20763445942698164
[I 2024-04-16 09:54:31,989] Trial 21 finished with value: 0.20729295884535462 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 246, 'oob_score': True, 'max_samples': 0.47328128429489624, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06249012522882601}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.2369582812366626
Fold 2 IBS: 0.18537997272868406
Fold 3 IBS: 0.21287205205514184
Fold 4 IBS: 0.19823752713062395
Fold 5 IBS: 0.20136150116623924
[I 2024-04-16 09:54:36,561] Trial 22 finished with value: 0.20696186686347035 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 240, 'oob_score': True, 'max_samples': 0.8048302184955297, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08611361559729094}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.22729846035275006
Fold 2 IBS: 0.19409724860757518
Fold 3 IBS: 0.20652668043882982
Fold 4 IBS: 0.21658264239186362
Fold 5 IBS: 0.2129126182268783
[I 2024-04-16 09:54:38,761] Trial 23 finished with value: 0.2114835300035794 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 153, 'oob_score': True, 'max_samples': 0.6143232161208779, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17807138804737838}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.2262621004414461
Fold 2 IBS: 0.18271786155581696
Fold 3 IBS: 0.20608526362131854
Fold 4 IBS: 0.21332814477577028
Fold 5 IBS: 0.2107872070715274
[I 2024-04-16 09:54:43,735] Trial 24 finished with value: 0.20783611549317582 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 298, 'oob_score': False, 'max_samples': 0.9129009358876962, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23768507053923305}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.22745629838942402
Fold 2 IBS: 0.18530677255214342
Fold 3 IBS: 0.2059491492691155
Fold 4 IBS: 0.20905817383563496
Fold 5 IBS: 0.2080148211407711
[I 2024-04-16 09:54:49,209] Trial 25 finished with value: 0.2071570430374178 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 18, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.6924758256666252, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10984368589886756}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.23283198993377457
Fold 2 IBS: 0.1837053918309308
Fold 3 IBS: 0.19841450349615106
Fold 4 IBS: 0.2077567310403492
Fold 5 IBS: 0.20741504813939407
[I 2024-04-16 09:54:53,200] Trial 26 finished with value: 0.20602473288811995 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 243, 'oob_score': True, 'max_samples': 0.6187124083035517, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.042198366910977045}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.23124808097848118
Fold 2 IBS: 0.18723727996483502
Fold 3 IBS: 0.20513671571550104
Fold 4 IBS: 0.2082714568633931
Fold 5 IBS: 0.20747665016129258
[I 2024-04-16 09:54:57,529] Trial 27 finished with value: 0.2078740367367006 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 317, 'oob_score': False, 'max_samples': 0.4780477687258653, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08840858412859012}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.2272866773210298
Fold 2 IBS: 0.1847332307257251
Fold 3 IBS: 0.20584684571927983
Fold 4 IBS: 0.2155052106153346
Fold 5 IBS: 0.20965275329215463
[I 2024-04-16 09:55:01,290] Trial 28 finished with value: 0.20860494353470477 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.7636780583134415, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1845919041664691}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.21844078661775027
Fold 2 IBS: 0.18997873380552038
Fold 3 IBS: 0.2523908404799174
Fold 4 IBS: 0.2098781957789575
Fold 5 IBS: 0.21827092047557814
[I 2024-04-16 09:55:06,336] Trial 29 finished with value: 0.21779189543154476 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 2, 'n_estimators': 378, 'oob_score': False, 'max_samples': 0.7137403943754692, 'max_features': None, 'min_weight_fraction_leaf': 0.2964705688027399}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.22660849396744023
Fold 2 IBS: 0.18395913222335272
Fold 3 IBS: 0.20402365301217334
Fold 4 IBS: 0.21327939169171645
Fold 5 IBS: 0.2118659187595795
[I 2024-04-16 09:55:09,755] Trial 30 finished with value: 0.20794731793085247 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 265, 'oob_score': False, 'max_samples': 0.8676775283569105, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.21960834742230517}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.2335372300443681
Fold 2 IBS: 0.1840165402571967
Fold 3 IBS: 0.19823917228241564
Fold 4 IBS: 0.20663752078888564

Fold 5 IBS: 0.2087860846359583
[I 2024-04-16 09:55:13,371] Trial 31 finished with value: 0.2062433096017649 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 246, 'oob_score': True, 'max_samples': 0.6079288251856192, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.043283773765183414}. Best is trial 18 with value: 0.20528919347758562.
Fold 1 IBS: 0.2297035767904694
Fold 2 IBS: 0.18353852060302428
Fold 3 IBS: 0.19854054014764616
Fold 4 IBS: 0.20605499505040847
Fold 5 IBS: 0.20598946772047116
[I 2024-04-16 09:55:15,985] Trial 32 finished with value: 0.20476542006240392 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 168, 'oob_score': True, 'max_samples': 0.6522520875850281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.023069227012922855}. Best is trial 32 with value: 0.20476542006240392.
Fold 1 IBS: 0.22593546080444016
Fold 2 IBS: 0.18349301915260266
Fold 3 IBS: 0.20075267452463064
Fold 4 IBS: 0.197950903912672
Fold 5 IBS: 0.20457622567857456
[I 2024-04-16 09:55:19,172] Trial 33 finished with value: 0.202541656814584 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 163, 'oob_score': True, 'max_samples': 0.664800041740168, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00037083121580618744}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.227321239504257
Fold 2 IBS: 0.1829859126723244
Fold 3 IBS: 0.20225414936026254
Fold 4 IBS: 0.204531498729332
Fold 5 IBS: 0.20313615128195714
[I 2024-04-16 09:55:21,190] Trial 34 finished with value: 0.2040457903096266 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 3, 'n_estimators': 107, 'oob_score': True, 'max_samples': 0.6670475216786844, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0010384685467203641}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.23284800354052113
Fold 2 IBS: 0.18563346934603234
Fold 3 IBS: 0.1949707827190948
Fold 4 IBS: 0.2117065113607522
Fold 5 IBS: 0.21282876003799567
[I 2024-04-16 09:55:22,383] Trial 35 finished with value: 0.20759750540087923 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.5406602625049062, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.019235764099438533}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22894771094858404
Fold 2 IBS: 0.1835873706594018
Fold 3 IBS: 0.2017061071489246
Fold 4 IBS: 0.20525055020405386
Fold 5 IBS: 0.2007565167727275
[I 2024-04-16 09:55:24,839] Trial 36 finished with value: 0.20404965114673837 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 6, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.4896820269526857, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03188420708952085}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22780890861963074
Fold 2 IBS: 0.18668569255244574
Fold 3 IBS: 0.2015901617599258
Fold 4 IBS: 0.20764151470033487
Fold 5 IBS: 0.20531548061662375
[I 2024-04-16 09:55:26,715] Trial 37 finished with value: 0.20580835164979217 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 127, 'oob_score': True, 'max_samples': 0.49794888107850344, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0023632302567297425}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22832715187437053
Fold 2 IBS: 0.18960305667713548
Fold 3 IBS: 0.1978322864226882
Fold 4 IBS: 0.20680619256378155
Fold 5 IBS: 0.2084232799539755
[I 2024-04-16 09:55:28,073] Trial 38 finished with value: 0.20619839349839025 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 95, 'oob_score': True, 'max_samples': 0.39462120676221285, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.032956375775297767}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.24667209864660164
Fold 2 IBS: 0.23215033372128444
Fold 3 IBS: 0.22935504036141371
Fold 4 IBS: 0.24150492492866238
Fold 5 IBS: 0.23030192751008824
[I 2024-04-16 09:55:30,794] Trial 39 finished with value: 0.2359968650336101 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 175, 'oob_score': True, 'max_samples': 0.570961332182233, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.33228094235869554}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22053849910086282
Fold 2 IBS: 0.1834664611952702
Fold 3 IBS: 0.2354248502165878
Fold 4 IBS: 0.2142748148716017
Fold 5 IBS: 0.20723810451115662
[I 2024-04-16 09:55:31,766] Trial 40 finished with value: 0.2121885459790958 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.6662495063138294, 'max_features': None, 'min_weight_fraction_leaf': 0.16074802605621386}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22896949477229725
Fold 2 IBS: 0.18163956522736027
Fold 3 IBS: 0.19426306942457297
Fold 4 IBS: 0.21142768639005
Fold 5 IBS: 0.2061478959376921
[I 2024-04-16 09:55:33,722] Trial 41 finished with value: 0.20448954235039452 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 111, 'oob_score': True, 'max_samples': 0.5746558186551526, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05937938528529281}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22693959015024706
Fold 2 IBS: 0.1840477622477897
Fold 3 IBS: 0.1973024579740445
Fold 4 IBS: 0.2110791492112415
Fold 5 IBS: 0.20774989984142817
[I 2024-04-16 09:55:36,036] Trial 42 finished with value: 0.20542377188495017 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 114, 'oob_score': True, 'max_samples': 0.513032975266388, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.028124995825654645}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.24669762207206475
Fold 2 IBS: 0.23211855497280065
Fold 3 IBS: 0.22932856930416562
Fold 4 IBS: 0.24147434203356752
Fold 5 IBS: 0.23039603235775877
[I 2024-04-16 09:55:38,264] Trial 43 finished with value: 0.23600302414807145 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 156, 'oob_score': True, 'max_samples': 0.5642723123929775, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.23722258268041305
Fold 2 IBS: 0.204647796669833
Fold 3 IBS: 0.2135949819607537
Fold 4 IBS: 0.23055509498054608
Fold 5 IBS: 0.2201920042064313
[I 2024-04-16 09:55:41,470] Trial 44 finished with value: 0.2212424920995954 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.324170182087475, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10891841875898124}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22883488477973404
Fold 2 IBS: 0.18862963848682351
Fold 3 IBS: 0.20401941603305976
Fold 4 IBS: 0.21357635944892056
Fold 5 IBS: 0.21034455317229586
[I 2024-04-16 09:55:45,506] Trial 45 finished with value: 0.20908097038416673 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.6438707505160381, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.005595969284201949}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.23444263953605218
Fold 2 IBS: 0.18258050221174046
Fold 3 IBS: 0.20015384610058481
Fold 4 IBS: 0.19645900676898706
Fold 5 IBS: 0.20567853585653673
[I 2024-04-16 09:55:46,865] Trial 46 finished with value: 0.20386290609478025 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 74, 'oob_score': True, 'max_samples': 0.7166797929459563, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.059119694636311206}. Best is trial 33 with value: 0.202541656814584.

Fold 1 IBS: 0.22547637004046184
Fold 2 IBS: 0.18496551370930772
Fold 3 IBS: 0.20478408769029746
Fold 4 IBS: 0.21368791701531417
Fold 5 IBS: 0.21306360231478774
[I 2024-04-16 09:55:48,458] Trial 47 finished with value: 0.20839549815403377 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.43491671167283275, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07153350270189084}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.24590405124273745
Fold 2 IBS: 0.23203729345433474
Fold 3 IBS: 0.2306508774403552
Fold 4 IBS: 0.24143250050767692
Fold 5 IBS: 0.22988062785342173
[I 2024-04-16 09:55:49,323] Trial 48 finished with value: 0.2359810700997052 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 4, 'n_estimators': 35, 'oob_score': True, 'max_samples': 0.7488226031933044, 'max_features': None, 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.24640968429245258
Fold 2 IBS: 0.23208768599539745
Fold 3 IBS: 0.22948727825320636
Fold 4 IBS: 0.2415017208241763
Fold 5 IBS: 0.23039982947689902
[I 2024-04-16 09:55:51,022] Trial 49 finished with value: 0.23597723976842633 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 110, 'oob_score': True, 'max_samples': 0.6916910281385112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.37411897805446126}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22183597378397477
Fold 2 IBS: 0.18186549679637215
Fold 3 IBS: 0.19368133145869906
Fold 4 IBS: 0.23149626037225762
Fold 5 IBS: 0.22698870701241275
[I 2024-04-16 09:55:51,763] Trial 50 finished with value: 0.2111735538847433 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.5751854739452711, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14147922592542847}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.23829586746570383
Fold 2 IBS: 0.18015771089172952
Fold 3 IBS: 0.1957409588737238
Fold 4 IBS: 0.21400021143681172
Fold 5 IBS: 0.20997185004899793
[I 2024-04-16 09:55:53,183] Trial 51 finished with value: 0.20763331974339336 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 2, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.7237359728701729, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029915121850802112}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22957013046807903
Fold 2 IBS: 0.18198951089470997
Fold 3 IBS: 0.2038512183897604
Fold 4 IBS: 0.19964899670856961
Fold 5 IBS: 0.20285670520393934
[I 2024-04-16 09:55:57,938] Trial 52 finished with value: 0.20358331233301166 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 176, 'oob_score': True, 'max_samples': 0.7953648845198504, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05430703501102517}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.23114822964418766
Fold 2 IBS: 0.18422994517050695
Fold 3 IBS: 0.19988085742978895
Fold 4 IBS: 0.20245706181638176
Fold 5 IBS: 0.20134935021912823
[I 2024-04-16 09:56:00,448] Trial 53 finished with value: 0.20381308885599872 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 94, 'oob_score': True, 'max_samples': 0.8035766709793983, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04511379867464467}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.23416644087737387
Fold 2 IBS: 0.18353341152078342
Fold 3 IBS: 0.1998944410396819
Fold 4 IBS: 0.20624494069877278
Fold 5 IBS: 0.2034377264482387
[I 2024-04-16 09:56:01,871] Trial 54 finished with value: 0.20545539211697011 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.8081577158827785, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10155700916609528}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.231159669059525
Fold 2 IBS: 0.18032370162747105
Fold 3 IBS: 0.2040424523674481
Fold 4 IBS: 0.20185726874012816
Fold 5 IBS: 0.20080461240985203
[I 2024-04-16 09:56:05,225] Trial 55 finished with value: 0.20363754084088487 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.8979038357967377, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0433582806278937}. Best is trial 33 with value: 0.202541656814584.
Fold 1 IBS: 0.22922116471215684
Fold 2 IBS: 0.1803986088953034
Fold 3 IBS: 0.20165324753234007
Fold 4 IBS: 0.19931372631931973
Fold 5 IBS: 0.20128607616171465
[I 2024-04-16 09:56:08,245] Trial 56 finished with value: 0.20237456472416696 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.8571482533547432, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.052104726607361256}. Best is trial 56 with value: 0.20237456472416696.
Fold 1 IBS: 0.22805106315795465
Fold 2 IBS: 0.18251837119509265
Fold 3 IBS: 0.2021921843177017
Fold 4 IBS: 0.19964616288596213
Fold 5 IBS: 0.19924130574764493
[I 2024-04-16 09:56:12,277] Trial 57 finished with value: 0.2023298174608712 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 188, 'oob_score': True, 'max_samples': 0.9532932142085897, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05011089777263817}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.228307962422061
Fold 2 IBS: 0.18368437929152992
Fold 3 IBS: 0.20260246173466528
Fold 4 IBS: 0.20949825704621552
Fold 5 IBS: 0.20858379040225078
[I 2024-04-16 09:56:15,907] Trial 58 finished with value: 0.2065353701793445 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.9779855270606636, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11981592689427545}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.22897097099469502
Fold 2 IBS: 0.18299081816687512
Fold 3 IBS: 0.20285181385788803
Fold 4 IBS: 0.20054440648775276
Fold 5 IBS: 0.20029711395130192
[I 2024-04-16 09:56:19,081] Trial 59 finished with value: 0.20313102469170258 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.9392471115261357, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07562344443972538}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.2606077292008831
Fold 2 IBS: 0.19373275593624045
Fold 3 IBS: 0.23415089313446638
Fold 4 IBS: 0.20636940106626686
Fold 5 IBS: 0.20689342493591817
[I 2024-04-16 09:56:23,639] Trial 60 finished with value: 0.22035084085475498 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 222, 'oob_score': True, 'max_samples': 0.9526296192334799, 'max_features': None, 'min_weight_fraction_leaf': 0.0775597264706641}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.22893042996635696
Fold 2 IBS: 0.1835810094929602
Fold 3 IBS: 0.20379284431279868
Fold 4 IBS: 0.20074066384451056
Fold 5 IBS: 0.20178326235376148
[I 2024-04-16 09:56:26,399] Trial 61 finished with value: 0.20376564199407757 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.8848019328227582, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.048563346706678036}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.227254467323276
Fold 2 IBS: 0.18478967370541907
Fold 3 IBS: 0.20133804053634766
Fold 4 IBS: 0.20183235774614527
Fold 5 IBS: 0.20270036534022054
[I 2024-04-16 09:56:29,001] Trial 62 finished with value: 0.20358298093028174 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 192, 'oob_score': True, 'max_samples': 0.8746694202839973, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09281412002575626}. Best is trial 57 with value: 0.2023298174608712.

Fold 1 IBS: 0.22738980486047694
Fold 2 IBS: 0.18424498258675306
Fold 3 IBS: 0.20401800243828214
Fold 4 IBS: 0.20439775352080095
Fold 5 IBS: 0.20383642835164115
[I 2024-04-16 09:56:31,899] Trial 63 finished with value: 0.20477739435159084 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 182, 'oob_score': True, 'max_samples': 0.9262735412221665, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08375003843429962}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.2297357114083422
Fold 2 IBS: 0.18475208112109387
Fold 3 IBS: 0.21076456987331543
Fold 4 IBS: 0.20644128003060727
Fold 5 IBS: 0.2085911701115838
[I 2024-04-16 09:56:34,102] Trial 64 finished with value: 0.20805696250898853 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 152, 'oob_score': True, 'max_samples': 0.8449961874170873, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0953708098882073}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.22922205254449252
Fold 2 IBS: 0.1826422345098706
Fold 3 IBS: 0.20167684556673787
Fold 4 IBS: 0.2026985201631487
Fold 5 IBS: 0.20115438383462167
[I 2024-04-16 09:56:37,489] Trial 65 finished with value: 0.20347880732377427 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 221, 'oob_score': True, 'max_samples': 0.943085739257025, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07026456088493926}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.22964284020162778
Fold 2 IBS: 0.18392350355269707
Fold 3 IBS: 0.20130471379997245
Fold 4 IBS: 0.20432123500050764
Fold 5 IBS: 0.20450587889932062
[I 2024-04-16 09:56:40,540] Trial 66 finished with value: 0.20473963429082512 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.9457422333602719, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12561425364367534}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.23807221790175953
Fold 2 IBS: 0.18233977866227397
Fold 3 IBS: 0.19590280075977798
Fold 4 IBS: 0.221594183248021
Fold 5 IBS: 0.21889979112840835
[I 2024-04-16 09:56:44,389] Trial 67 finished with value: 0.21136175434004817 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 14, 'max_depth': 11, 'n_estimators': 270, 'oob_score': True, 'max_samples': 0.9811234519950826, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07314173115614214}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.22744413494537588
Fold 2 IBS: 0.18532641530947883
Fold 3 IBS: 0.20323406113028883
Fold 4 IBS: 0.20276058181034728
Fold 5 IBS: 0.2043765859334657
[I 2024-04-16 09:56:47,316] Trial 68 finished with value: 0.2046283558257913 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.8697683608197417, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.15583221417022652}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.2263101195659876
Fold 2 IBS: 0.18180832583605294
Fold 3 IBS: 0.20555220440192612
Fold 4 IBS: 0.201394425742922
Fold 5 IBS: 0.20458357390827703
[I 2024-04-16 09:56:50,248] Trial 69 finished with value: 0.20392972989103314 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 143, 'oob_score': True, 'max_samples': 0.8328794204586144, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11288213110495689}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.22605052866504702
Fold 2 IBS: 0.18290646148295675
Fold 3 IBS: 0.2035595972943797
Fold 4 IBS: 0.21294859907577526
Fold 5 IBS: 0.21131569364998617
[I 2024-04-16 09:56:54,245] Trial 70 finished with value: 0.20735617603362896 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 209, 'oob_score': True, 'max_samples': 0.9525325148053274, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.014893384244355982}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.2305762268650142
Fold 2 IBS: 0.1806365594443355
Fold 3 IBS: 0.2039507216155661
Fold 4 IBS: 0.20193300432473463
Fold 5 IBS: 0.20143840597912563
[I 2024-04-16 09:56:59,037] Trial 71 finished with value: 0.20370698364575518 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 185, 'oob_score': True, 'max_samples': 0.8967342526177012, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0620575543464313}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.23045035393749425
Fold 2 IBS: 0.18213452453089204
Fold 3 IBS: 0.20316079133052595
Fold 4 IBS: 0.19946319944580784
Fold 5 IBS: 0.20037361324810932
[I 2024-04-16 09:57:02,467] Trial 72 finished with value: 0.2031164964985659 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 195, 'oob_score': True, 'max_samples': 0.9266700252828517, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03943462626070526}. Best is trial 57 with value: 0.2023298174608712.
Fold 1 IBS: 0.2261399146473475
Fold 2 IBS: 0.18076650978236128
Fold 3 IBS: 0.20386991347780273
Fold 4 IBS: 0.19926562007219212
Fold 5 IBS: 0.19794382041410172
[I 2024-04-16 09:57:05,381] Trial 73 finished with value: 0.20159715567876108 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.9280035754058158, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0918192183935895}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22814718953063481
Fold 2 IBS: 0.18230839650568592
Fold 3 IBS: 0.2029295802743672
Fold 4 IBS: 0.20142416945203614
Fold 5 IBS: 0.2013361832809154
[I 2024-04-16 09:57:09,336] Trial 74 finished with value: 0.20322910380872788 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 229, 'oob_score': True, 'max_samples': 0.927140558746675, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09489399488136084}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2314897988186868
Fold 2 IBS: 0.184370335002602
Fold 3 IBS: 0.2084928607984541
Fold 4 IBS: 0.2015540688625315
Fold 5 IBS: 0.20726066774223564
[I 2024-04-16 09:57:13,125] Trial 75 finished with value: 0.206633546244902 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.9976615480822635, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1338859569801302}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22808253241393736
Fold 2 IBS: 0.18295879804965715
Fold 3 IBS: 0.20565846641268876
Fold 4 IBS: 0.20163502177914755
Fold 5 IBS: 0.19847135623807008
[I 2024-04-16 09:57:16,019] Trial 76 finished with value: 0.20336123497870018 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.9177686697027323, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016399775743553183}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.229310322690829
Fold 2 IBS: 0.1832891985921302
Fold 3 IBS: 0.20608779681704487
Fold 4 IBS: 0.20130571897848815
Fold 5 IBS: 0.1979814851673532
[I 2024-04-16 09:57:19,231] Trial 77 finished with value: 0.20359490444916908 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 160, 'oob_score': True, 'max_samples': 0.9225623763567447, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01757567147676309}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2543387274119932
Fold 2 IBS: 0.1938688528285986
Fold 3 IBS: 0.22999111415852524
Fold 4 IBS: 0.21103481919847175

Fold 5 IBS: 0.20778331062924044
[I 2024-04-16 09:57:23,175] Trial 78 finished with value: 0.21940336484536585 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 143, 'oob_score': True, 'max_samples': 0.9696883436320323, 'max_features': None, 'min_weight_fraction_leaf': 0.03521042067680326}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.23036951675743086
Fold 2 IBS: 0.18464849451895313
Fold 3 IBS: 0.2043713140769145
Fold 4 IBS: 0.20232000830215705
Fold 5 IBS: 0.2000574478630733
[I 2024-04-16 09:57:27,694] Trial 79 finished with value: 0.20435335630370574 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 12, 'n_estimators': 264, 'oob_score': True, 'max_samples': 0.921109290734505, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01634003279013976}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22952283595294182
Fold 2 IBS: 0.18408491860180182
Fold 3 IBS: 0.20354308456971082
Fold 4 IBS: 0.20509186467498083
Fold 5 IBS: 0.20477656300105376
[I 2024-04-16 09:57:30,405] Trial 80 finished with value: 0.20540385336009784 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.8492700188119718, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08337942640478534}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22953488189770924
Fold 2 IBS: 0.18253950946698838
Fold 3 IBS: 0.20193196459684004
Fold 4 IBS: 0.2014431569302558
Fold 5 IBS: 0.20021170410021122
[I 2024-04-16 09:57:33,969] Trial 81 finished with value: 0.20313224339840094 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.9446738702468112, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06696503033099102}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22828396925116554
Fold 2 IBS: 0.18389793687494674
Fold 3 IBS: 0.20470720317054564
Fold 4 IBS: 0.2067405948735161
Fold 5 IBS: 0.2077497019746126
[I 2024-04-16 09:57:36,822] Trial 82 finished with value: 0.20627588122895735 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 199, 'oob_score': True, 'max_samples': 0.900222304457669, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.037436825403037215}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2293958364470615
Fold 2 IBS: 0.1837289531830732
Fold 3 IBS: 0.2033641483006749
Fold 4 IBS: 0.19933092999228372
Fold 5 IBS: 0.19899652484096553
[I 2024-04-16 09:57:40,381] Trial 83 finished with value: 0.20296327855281177 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 167, 'oob_score': True, 'max_samples': 0.9699262484405999, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05296075896558448}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2293099207839767
Fold 2 IBS: 0.18405080032428597
Fold 3 IBS: 0.20262846255915465
Fold 4 IBS: 0.20186979380466086
Fold 5 IBS: 0.20195260690444858
[I 2024-04-16 09:57:44,087] Trial 84 finished with value: 0.20396231687530536 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 11, 'n_estimators': 237, 'oob_score': True, 'max_samples': 0.9578505947924035, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10060640568093461}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.23036069726629657
Fold 2 IBS: 0.18463247341469188
Fold 3 IBS: 0.20487735033205698
Fold 4 IBS: 0.20643092105796393
Fold 5 IBS: 0.20722048775944288
[I 2024-04-16 09:57:47,719] Trial 85 finished with value: 0.20670438596609042 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 14, 'n_estimators': 260, 'oob_score': True, 'max_samples': 0.981874500881388, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06730812590028978}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22728894836928035
Fold 2 IBS: 0.1843329190119923
Fold 3 IBS: 0.20092412298686305
Fold 4 IBS: 0.19871047709750528
Fold 5 IBS: 0.20037396761822351
[I 2024-04-16 09:57:49,307] Trial 86 finished with value: 0.2023260870167729 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.997529309063804, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04678783424543201}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2268710132348071
Fold 2 IBS: 0.18465367501666
Fold 3 IBS: 0.20161435554161974
Fold 4 IBS: 0.19901358035492003
Fold 5 IBS: 0.2008172467675647
[I 2024-04-16 09:57:50,861] Trial 87 finished with value: 0.20259397418311428 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 134, 'oob_score': False, 'max_samples': 0.9988938433915365, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05182363124902023}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2271313405978693
Fold 2 IBS: 0.18469145381211055
Fold 3 IBS: 0.20145831628065042
Fold 4 IBS: 0.1990805339202023
Fold 5 IBS: 0.2005801605866903
[I 2024-04-16 09:57:52,578] Trial 88 finished with value: 0.20258836103950456 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 132, 'oob_score': False, 'max_samples': 0.9985671293811484, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05359842363049251}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2245347194620965
Fold 2 IBS: 0.18661529047082367
Fold 3 IBS: 0.20313725133970767
Fold 4 IBS: 0.2016407488344091
Fold 5 IBS: 0.20087305958290239
[I 2024-04-16 09:57:54,337] Trial 89 finished with value: 0.20336021393798784 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 12, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.9963850105344589, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05192424058546341}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22702747281974447
Fold 2 IBS: 0.18359554434916325
Fold 3 IBS: 0.20120333965275344
Fold 4 IBS: 0.20033598297954652
Fold 5 IBS: 0.20138620257280687
[I 2024-04-16 09:57:56,452] Trial 90 finished with value: 0.2027097084748029 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.9929955889708438, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02651710212708512}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.226581773486646
Fold 2 IBS: 0.1849773937659162
Fold 3 IBS: 0.20183994114491913
Fold 4 IBS: 0.19861535165275637
Fold 5 IBS: 0.20078975102125307
[I 2024-04-16 09:57:58,629] Trial 91 finished with value: 0.20256084221429815 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.9999746973397875, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.027817275996272324}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2285000022377107
Fold 2 IBS: 0.18472709244192484
Fold 3 IBS: 0.2046428398613563
Fold 4 IBS: 0.20348153806961547
Fold 5 IBS: 0.203383210804829
[I 2024-04-16 09:58:00,601] Trial 92 finished with value: 0.20494693668308725 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 15, 'n_estimators': 137, 'oob_score': False, 'max_samples': 0.9707883385156701, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.001041431058034583}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.22642956106432788
Fold 2 IBS: 0.1829521031690411
Fold 3 IBS: 0.20249676549664788
Fold 4 IBS: 0.199785798188105
Fold 5 IBS: 0.20084040328493316
[I 2024-04-16 09:58:02,778] Trial 93 finished with value: 0.202500926240611 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.9995196364036202, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029792017489157465}. Best is trial 73 with value: 0.20159715567876108.

Fold 1 IBS: 0.22661154321542654
Fold 2 IBS: 0.1826314318857676
Fold 3 IBS: 0.20258564093938022
Fold 4 IBS: 0.20038355387682857
Fold 5 IBS: 0.201005200159819
[I 2024-04-16 09:58:05,765] Trial 94 finished with value: 0.2026434740154444 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.9930073589533785, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.008971163622332974}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2226668884661819
Fold 2 IBS: 0.18494614156725506
Fold 3 IBS: 0.204837192196963
Fold 4 IBS: 0.20461549662877815
Fold 5 IBS: 0.2036474473766526
[I 2024-04-16 09:58:07,653] Trial 95 finished with value: 0.20414263324716614 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 14, 'n_estimators': 123, 'oob_score': False, 'max_samples': 0.9975077981339631, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.009999985863619741}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.23259624608527293
Fold 2 IBS: 0.18253588214186495
Fold 3 IBS: 0.21088271070098263
Fold 4 IBS: 0.20359014033258638
Fold 5 IBS: 0.20676166103840304
[I 2024-04-16 09:58:08,933] Trial 96 finished with value: 0.20727332805982196 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 98, 'oob_score': False, 'max_samples': 0.9640868146921107, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.026087950778419793}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.24641805816041673
Fold 2 IBS: 0.2321234402785419
Fold 3 IBS: 0.22945836268945743
Fold 4 IBS: 0.24125273471274303
Fold 5 IBS: 0.22992833999159096
[I 2024-04-16 09:58:10,916] Trial 97 finished with value: 0.23583618716655003 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 14, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.16235417871035346, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2624031307121196}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.2296286435167951
Fold 2 IBS: 0.18352812216778563
Fold 3 IBS: 0.20322682931094702
Fold 4 IBS: 0.20283253896298187
Fold 5 IBS: 0.20467974030684985
[I 2024-04-16 09:58:18,852] Trial 98 finished with value: 0.2047791748530719 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 500, 'oob_score': False, 'max_samples': 0.9009934558620053, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.009361765284286805}. Best is trial 73 with value: 0.20159715567876108.
Fold 1 IBS: 0.25829255289514264
Fold 2 IBS: 0.19492483497479116
Fold 3 IBS: 0.22944811974755017
Fold 4 IBS: 0.21030164792972988
Fold 5 IBS: 0.20851298563918458
[I 2024-04-16 09:58:22,307] Trial 99 finished with value: 0.22029602823727967 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 13, 'n_estimators': 130, 'oob_score': False, 'max_samples': 0.9670568176477521, 'max_features': None, 'min_weight_fraction_leaf': 0.03457584043321061}. Best is trial 73 with value: 0.20159715567876108.


* Best trial for IBS:
 FrozenTrial(number=73, state=TrialState.COMPLETE, values=[0.20159715567876108], datetime_start=datetime.datetime(2024, 4, 16, 9, 57, 2, 481808), datetime_complete=datetime.datetime(2024, 4, 16, 9, 57, 5, 380817), params={'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 10, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.9280035754058158, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0918192183935895}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=73, value=None)


* Best Score for IBS:
 0.20159715567876108

In [116]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [117]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.797
train_ibs:  0.202

#### Test

In [118]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [119]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=18, max_features='log2', max_leaf_nodes=6,
                     max_samples=0.7275622802375871, min_samples_split=17,
                     min_weight_fraction_leaf=0.010224090801480467,
                     n_estimators=281, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.517

RandomSurvivalForest(max_depth=10, max_leaf_nodes=20,
                     max_samples=0.9280035754058158, min_samples_leaf=11,
                     min_samples_split=13,
                     min_weight_fraction_leaf=0.0918192183935895,
                     n_estimators=165, oob_score=True, random_state=123)

test_ibs:  0.261

In [120]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [121]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [122]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 09:58:25,466] A new study created in memory with name: no-name-60b2bac2-2e21-48b1-8745-d7d5039651c5

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 09:58:26,661] Trial 0 finished with value: 0.736891888811905 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:29,599] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.630901287553648
[I 2024-04-16 09:58:37,369] Trial 2 finished with value: 0.6685477562390263 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5059760956175299
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 09:58:37,879] Trial 3 finished with value: 0.6882009011276333 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:40,198] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:42,536] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 09:58:44,017] Trial 6 finished with value: 0.7363995472954604 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.703862660944206
[I 2024-04-16 09:58:47,054] Trial 7 finished with value: 0.6988506983557575 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5378486055776892
Fold 2 C-index: 0.8313953488372093
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6630901287553648
[I 2024-04-16 09:58:47,422] Trial 8 finished with value: 0.6942493584995976 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5418326693227091
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 09:58:55,948] Trial 9 finished with value: 0.6677186649583862 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:58:58,583] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 09:58:59,971] Trial 11 finished with value: 0.7010629351504851 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.736891888811905.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 09:59:01,873] Trial 12 finished with value: 0.7524534888374881 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7339055793991416
[I 2024-04-16 09:59:04,069] Trial 13 finished with value: 0.7197155687193607 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7253218884120172
[I 2024-04-16 09:59:07,438] Trial 14 finished with value: 0.7123379824129067 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7186311787072244

Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 09:59:08,965] Trial 15 finished with value: 0.7059016436492067 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6223175965665236
[I 2024-04-16 09:59:11,488] Trial 16 finished with value: 0.6633435677778114 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.7081545064377682
[I 2024-04-16 09:59:13,058] Trial 17 finished with value: 0.7135984993010687 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 09:59:15,050] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 09:59:16,920] Trial 19 finished with value: 0.7157494160141459 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.5680851063829787
Fold 4 C-index: 0.6026615969581749
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 09:59:17,119] Trial 20 finished with value: 0.6512582679693069 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 09:59:18,542] Trial 21 finished with value: 0.739565179340922 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 09:59:20,224] Trial 22 finished with value: 0.7371674358249847 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 09:59:21,936] Trial 23 finished with value: 0.7021124308811358 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4354485106193713, 'min_weight_fraction_leaf': 0.02923560760429222}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:59:24,293] Trial 24 finished with value: 0.7031702242592709 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 9, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.34950482438457253, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7381974248927039
[I 2024-04-16 09:59:25,991] Trial 25 finished with value: 0.7211081851182947 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6363223369371479, 'min_weight_fraction_leaf': 0.004408180869012377}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 09:59:34,960] Trial 26 finished with value: 0.6927403505079763 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 494, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6041191076422192, 'min_weight_fraction_leaf': 0.06050836672641209}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 09:59:36,474] Trial 27 finished with value: 0.6899344596027064 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 408, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4912235374460364, 'min_weight_fraction_leaf': 0.15454662268064692}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:59:38,040] Trial 28 finished with value: 0.704341261699482 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 9, 'max_depth': 17, 'n_estimators': 301, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7093054331237321, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5298804780876494
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 09:59:38,921] Trial 29 finished with value: 0.6838140362030706 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 219, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.37188286366136036, 'min_weight_fraction_leaf': 0.10380226349432521}. Best is trial 12 with value: 0.7524534888374881.

Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 09:59:40,247] Trial 30 finished with value: 0.6974166967388813 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.23596047192138714, 'min_weight_fraction_leaf': 0.09139810961881356}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 09:59:42,104] Trial 31 finished with value: 0.7378767980988239 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 453, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5115588937941487, 'min_weight_fraction_leaf': 0.028675344107944124}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7725321888412017
[I 2024-04-16 09:59:44,297] Trial 32 finished with value: 0.7385145655162275 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 459, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4999135158398872, 'min_weight_fraction_leaf': 0.03283979494132459}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.549800796812749
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 09:59:46,065] Trial 33 finished with value: 0.6800715081644138 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 20, 'max_depth': 14, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5017879093982511, 'min_weight_fraction_leaf': 0.05994389102377999}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 09:59:47,751] Trial 34 finished with value: 0.7440473643684732 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5336701004778337, 'min_weight_fraction_leaf': 0.004940954301987932}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-16 09:59:52,270] Trial 35 finished with value: 0.735245273748254 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 15, 'n_estimators': 474, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.41617588285297324, 'min_weight_fraction_leaf': 0.0020643278054800025}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6909871244635193
[I 2024-04-16 09:59:57,264] Trial 36 finished with value: 0.6904301773721803 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 397, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5560282514292283, 'min_weight_fraction_leaf': 0.12068759884763168}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6824034334763949
[I 2024-04-16 09:59:58,997] Trial 37 finished with value: 0.690009364975125 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 13, 'n_estimators': 478, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.2644774312640942, 'min_weight_fraction_leaf': 0.07429314224868984}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 10:00:00,375] Trial 38 finished with value: 0.7253578444061204 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.04632699273988158}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:00:07,048] Trial 39 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 420, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8234703848097623, 'min_weight_fraction_leaf': 0.4602249568669607}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7424892703862661
[I 2024-04-16 10:00:07,775] Trial 40 finished with value: 0.7065426609944299 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 15, 'n_estimators': 156, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7219416809554898, 'min_weight_fraction_leaf': 0.019656576972989677}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 10:00:09,537] Trial 41 finished with value: 0.7369677588432426 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 455, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5195809451929053, 'min_weight_fraction_leaf': 0.0438790996164145}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 10:00:11,425] Trial 42 finished with value: 0.7475426346524399 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 468, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5823530664581796, 'min_weight_fraction_leaf': 0.026212297596626986}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.7339055793991416
[I 2024-04-16 10:00:13,195] Trial 43 finished with value: 0.7134629243318387 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 481, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.45882656924549725, 'min_weight_fraction_leaf': 0.08521907059188669}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7639484978540773
[I 2024-04-16 10:00:14,904] Trial 44 finished with value: 0.7286993646933537 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 465, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5902844249411112, 'min_weight_fraction_leaf': 0.01305046995423322}. Best is trial 12 with value: 0.7524534888374881.

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 10:00:16,705] Trial 45 finished with value: 0.7047430784928369 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.5514541990734136, 'min_weight_fraction_leaf': 0.11745685616845841}. Best is trial 12 with value: 0.7524534888374881.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7939914163090128
[I 2024-04-16 10:00:18,732] Trial 46 finished with value: 0.759461339650925 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 433, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.755169766356815, 'min_weight_fraction_leaf': 0.05221727000153778}. Best is trial 46 with value: 0.759461339650925.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6952789699570815
[I 2024-04-16 10:00:24,663] Trial 47 finished with value: 0.6934028498028908 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 396, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.9179543673612431, 'min_weight_fraction_leaf': 0.05983961740448324}. Best is trial 46 with value: 0.759461339650925.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:28,138] Trial 48 finished with value: 0.786544119490802 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 429, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7497047129432646, 'min_weight_fraction_leaf': 0.002555506864101678}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 10:00:30,137] Trial 49 finished with value: 0.7607720023143546 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 280, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7404554637409765, 'min_weight_fraction_leaf': 0.09131723435674605}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 10:00:32,331] Trial 50 finished with value: 0.7495248313918071 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 301, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7606273549181609, 'min_weight_fraction_leaf': 0.1510765828589958}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7639484978540773
[I 2024-04-16 10:00:34,220] Trial 51 finished with value: 0.736534020604908 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 298, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.75752614994413, 'min_weight_fraction_leaf': 0.16299423337519645}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 10:00:35,792] Trial 52 finished with value: 0.7544813698735732 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 220, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8208146212650123, 'min_weight_fraction_leaf': 0.10542134751298168}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 10:00:37,670] Trial 53 finished with value: 0.7455751583418707 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 283, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.837373810576047, 'min_weight_fraction_leaf': 0.13464394724014805}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:39,244] Trial 54 finished with value: 0.7633820511354666 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 226, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9232319523833421, 'min_weight_fraction_leaf': 0.10127554684215591}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:00:41,015] Trial 55 finished with value: 0.7762325324341314 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 234, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9381315837429987, 'min_weight_fraction_leaf': 0.08551025986155897}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:42,483] Trial 56 finished with value: 0.7673228769793778 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 225, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9351373511713297, 'min_weight_fraction_leaf': 0.10746009423818731}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 10:00:43,949] Trial 57 finished with value: 0.736125134810686 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 180, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9380241134700369, 'min_weight_fraction_leaf': 0.2227760109146411}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7811158798283262
[I 2024-04-16 10:00:45,667] Trial 58 finished with value: 0.7429914274892713 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 239, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8491292758924333, 'min_weight_fraction_leaf': 0.17781175569342278}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6781115879828327
[I 2024-04-16 10:00:48,522] Trial 59 finished with value: 0.6822526048016024 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 196, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9208394028602466, 'min_weight_fraction_leaf': 0.2795553265395688}. Best is trial 48 with value: 0.786544119490802.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8025751072961373
[I 2024-04-16 10:00:49,319] Trial 60 finished with value: 0.7666347098130368 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 102, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9490728939373339, 'min_weight_fraction_leaf': 0.09060920541147081}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:50,121] Trial 61 finished with value: 0.7667141607682888 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 106, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9456429299340572, 'min_weight_fraction_leaf': 0.09160475534368061}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:50,880] Trial 62 finished with value: 0.7682171787102738 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 96, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9510566714466717, 'min_weight_fraction_leaf': 0.09445985477050291}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 10:00:51,928] Trial 63 finished with value: 0.7487622659167903 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 120, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9474274989349436, 'min_weight_fraction_leaf': 0.13189925217057735}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:00:52,734] Trial 64 finished with value: 0.7778086707353904 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 76, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9606815190179392, 'min_weight_fraction_leaf': 0.07560225442237344}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:53,476] Trial 65 finished with value: 0.7806735558933036 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 78, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9998851065989206, 'min_weight_fraction_leaf': 0.07449040162927881}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:00:54,103] Trial 66 finished with value: 0.7642846328082351 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 67, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9697511853457705, 'min_weight_fraction_leaf': 0.07735506716273248}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 10:00:54,787] Trial 67 finished with value: 0.7486752557189431 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 51, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8911537156257379, 'min_weight_fraction_leaf': 0.11773239878112113}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.575107296137339
[I 2024-04-16 10:00:55,245] Trial 68 finished with value: 0.6650174461034278 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 18, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.860328051828477, 'min_weight_fraction_leaf': 0.35364036783604025}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8154506437768241
[I 2024-04-16 10:00:56,049] Trial 69 finished with value: 0.7794196400090507 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 74, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9900149788793398, 'min_weight_fraction_leaf': 0.07118889222911756}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 10:00:56,795] Trial 70 finished with value: 0.703342817086205 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 1, 'n_estimators': 77, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9876446438072931, 'min_weight_fraction_leaf': 0.06920009170857591}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:57,815] Trial 71 finished with value: 0.7642806444755261 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 132, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9968509395337187, 'min_weight_fraction_leaf': 0.10785215479995364}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:58,728] Trial 72 finished with value: 0.7777176393363112 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 87, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9580715420593225, 'min_weight_fraction_leaf': 0.07813836666294671}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:00:59,142] Trial 73 finished with value: 0.7455071544233778 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 4, 'n_estimators': 29, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.90005127266776, 'min_weight_fraction_leaf': 0.07294765306547502}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.8022813688212928
Fold 5 C-index: 0.7982832618025751
[I 2024-04-16 10:01:00,038] Trial 74 finished with value: 0.7510735500647715 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 75, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9657689812862759, 'min_weight_fraction_leaf': 0.13292019895461196}. Best is trial 48 with value: 0.786544119490802.

Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.7896995708154506
[I 2024-04-16 10:01:01,136] Trial 75 finished with value: 0.7633300033742478 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 94, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.799478926269112, 'min_weight_fraction_leaf': 0.043548604691548407}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.545816733067729
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 10:01:02,178] Trial 76 finished with value: 0.6486383894438124 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 40, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8746532697747706, 'min_weight_fraction_leaf': 0.05515077091723192}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7854077253218884
[I 2024-04-16 10:01:03,733] Trial 77 finished with value: 0.7417876144977348 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 145, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9052424536410493, 'min_weight_fraction_leaf': 0.1735677702611955}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7467811158798283
[I 2024-04-16 10:01:04,536] Trial 78 finished with value: 0.7285354643042037 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 58, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9999013726645501, 'min_weight_fraction_leaf': 0.07620523495795734}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7510729613733905
[I 2024-04-16 10:01:05,443] Trial 79 finished with value: 0.72705059046404 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 89, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.9634245518500324, 'min_weight_fraction_leaf': 0.20210055465710386}. Best is trial 48 with value: 0.786544119490802.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 10:01:06,806] Trial 80 finished with value: 0.7924039767788755 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 168, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8732815515831934, 'min_weight_fraction_leaf': 0.01861612913172194}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 10:01:08,451] Trial 81 finished with value: 0.7875184494551309 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 183, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8666712158937419, 'min_weight_fraction_leaf': 0.023532724240202894}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-16 10:01:09,634] Trial 82 finished with value: 0.7842046582709086 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 122, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8673791205922674, 'min_weight_fraction_leaf': 0.01613939594158079}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:01:10,961] Trial 83 finished with value: 0.7831249832258713 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 167, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8734963867641533, 'min_weight_fraction_leaf': 0.01812676013548712}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:01:12,146] Trial 84 finished with value: 0.7823429080015526 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 170, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8670601727373346, 'min_weight_fraction_leaf': 0.01914246735368293}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:01:13,401] Trial 85 finished with value: 0.755596273285778 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 2, 'n_estimators': 171, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7862058028831053, 'min_weight_fraction_leaf': 0.015762217898744817}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 10:01:14,797] Trial 86 finished with value: 0.78513916780889 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 199, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8540719693127281, 'min_weight_fraction_leaf': 0.022788357021419896}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.759656652360515
[I 2024-04-16 10:01:16,097] Trial 87 finished with value: 0.7357368175429964 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 194, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8656325190353895, 'min_weight_fraction_leaf': 0.023190465855644583}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.721030042918455
[I 2024-04-16 10:01:18,823] Trial 88 finished with value: 0.6977312822292423 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 3, 'n_estimators': 160, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.825728074592941, 'min_weight_fraction_leaf': 0.0364894132589554}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7639484978540773
[I 2024-04-16 10:01:19,841] Trial 89 finished with value: 0.7261571863836666 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 137, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6802342641616439, 'min_weight_fraction_leaf': 0.01857960471368049}. Best is trial 80 with value: 0.7924039767788755.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.776824034334764
[I 2024-04-16 10:01:21,125] Trial 90 finished with value: 0.7416543034362327 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 7, 'max_depth': 3, 'n_estimators': 179, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8054427408727943, 'min_weight_fraction_leaf': 0.004211335094341018}. Best is trial 80 with value: 0.7924039767788755.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8412017167381974
[I 2024-04-16 10:01:22,073] Trial 91 finished with value: 0.7981047458527974 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 119, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8823697763037918, 'min_weight_fraction_leaf': 0.03543323206321737}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8068669527896996
[I 2024-04-16 10:01:23,386] Trial 92 finished with value: 0.7757657153680169 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 113, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8473720041948303, 'min_weight_fraction_leaf': 0.034403598734470714}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 10:01:25,038] Trial 93 finished with value: 0.7809704514490062 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 208, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8873617017827929, 'min_weight_fraction_leaf': 0.04887195859324901}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 10:01:26,872] Trial 94 finished with value: 0.7833719028756927 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 209, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.887623497328762, 'min_weight_fraction_leaf': 0.04926394647683571}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8197424892703863
[I 2024-04-16 10:01:28,601] Trial 95 finished with value: 0.7803153402559503 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 209, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8768779924118164, 'min_weight_fraction_leaf': 0.014324032019698122}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7639484978540773
[I 2024-04-16 10:01:29,875] Trial 96 finished with value: 0.7416907704640459 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 167, 'oob_score': True, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8922045431110259, 'min_weight_fraction_leaf': 0.048831318703821694}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8111587982832618
[I 2024-04-16 10:01:31,268] Trial 97 finished with value: 0.7729556485550398 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 209, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8030878581468682, 'min_weight_fraction_leaf': 0.03372131738445533}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-16 10:01:32,559] Trial 98 finished with value: 0.7941178118691122 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 184, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8406433263063057, 'min_weight_fraction_leaf': 0.023686745654583865}. Best is trial 91 with value: 0.7981047458527974.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8555133079847909

[I 2024-04-16 10:01:33,951] A new study created in memory with name: no-name-f4a18f30-d2b6-4eb9-9bfa-fa7021cc84ba

Fold 5 C-index: 0.8283261802575107
[I 2024-04-16 10:01:33,934] Trial 99 finished with value: 0.7981883349820881 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 190, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7746492428469892, 'min_weight_fraction_leaf': 0.02592476635662061}. Best is trial 99 with value: 0.7981883349820881.


* Best trial for C-index:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.7981883349820881], datetime_start=datetime.datetime(2024, 4, 16, 10, 1, 32, 564323), datetime_complete=datetime.datetime(2024, 4, 16, 10, 1, 33, 933500), params={'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 190, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.7746492428469892, 'min_weight_fraction_leaf': 0.02592476635662061}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=99, value=None)


* Best Score for C-index:
 0.7981883349820881

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.2356741487124546
Fold 2 IBS: 0.19780807569987133
Fold 3 IBS: 0.20558545539240541
Fold 4 IBS: 0.22128032817904125
Fold 5 IBS: 0.21201928591586114
[I 2024-04-16 10:01:38,203] Trial 0 finished with value: 0.21447345877992677 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-16 10:01:44,336] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.24406984211647176
Fold 2 IBS: 0.22295673264443408
Fold 3 IBS: 0.22298941830629282
Fold 4 IBS: 0.23621197700216504
Fold 5 IBS: 0.22573757733065314
[I 2024-04-16 10:01:49,454] Trial 2 finished with value: 0.23039310948000336 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.245182266541267
Fold 2 IBS: 0.2222932971889546
Fold 3 IBS: 0.22348040677025166
Fold 4 IBS: 0.23605962447644957
Fold 5 IBS: 0.2257193238975315
[I 2024-04-16 10:01:51,294] Trial 3 finished with value: 0.23054698377489088 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-16 10:01:56,317] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-16 10:01:58,841] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.23544780728707737
Fold 2 IBS: 0.19819574698700165
Fold 3 IBS: 0.207432216161172
Fold 4 IBS: 0.22467230406916736
Fold 5 IBS: 0.21398735337599004
[I 2024-04-16 10:02:04,482] Trial 6 finished with value: 0.21594708557608167 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.23935073660711556
Fold 2 IBS: 0.21106387940515578
Fold 3 IBS: 0.21442938399169065
Fold 4 IBS: 0.2309073439387265
Fold 5 IBS: 0.21939141269976875
[I 2024-04-16 10:02:07,986] Trial 7 finished with value: 0.22302855132849145 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.24513983433957628
Fold 2 IBS: 0.22566682256232662
Fold 3 IBS: 0.22608922165969317
Fold 4 IBS: 0.23888096259416847
Fold 5 IBS: 0.22761580007926416
[I 2024-04-16 10:02:08,712] Trial 8 finished with value: 0.23267852824700572 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.2455756489386518
Fold 2 IBS: 0.22933972139988243
Fold 3 IBS: 0.22779166824398672
Fold 4 IBS: 0.24025312265285195
Fold 5 IBS: 0.22857693568312284
[I 2024-04-16 10:02:15,306] Trial 9 finished with value: 0.23430741938369914 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-16 10:02:20,244] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.24194292462805192
Fold 2 IBS: 0.21855670511970912
Fold 3 IBS: 0.22126915283903734
Fold 4 IBS: 0.23519923866727097
Fold 5 IBS: 0.22368476105389343
[I 2024-04-16 10:02:24,815] Trial 11 finished with value: 0.22813055646159258 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21447345877992677.
Fold 1 IBS: 0.2331829272708588
Fold 2 IBS: 0.189250356639547
Fold 3 IBS: 0.198577330272766
Fold 4 IBS: 0.21844692288723977
Fold 5 IBS: 0.2086239704516534
[I 2024-04-16 10:02:30,721] Trial 12 finished with value: 0.20961630150441302 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23768124636421759
Fold 2 IBS: 0.20871046971045734
Fold 3 IBS: 0.21456345601034096
Fold 4 IBS: 0.22770223209265883
Fold 5 IBS: 0.2192207075946759
[I 2024-04-16 10:02:36,310] Trial 13 finished with value: 0.22157562235447012 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.2381303944133899
Fold 2 IBS: 0.21162803711846565
Fold 3 IBS: 0.21780252435319944
Fold 4 IBS: 0.22919495531204792
Fold 5 IBS: 0.21992562247541178
[I 2024-04-16 10:02:40,585] Trial 14 finished with value: 0.22333630673450294 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.20961630150441302.

Fold 1 IBS: 0.2403693876649871
Fold 2 IBS: 0.21663294116246054
Fold 3 IBS: 0.21958206370972638
Fold 4 IBS: 0.23029140617367272
Fold 5 IBS: 0.22159218430461863
[I 2024-04-16 10:02:43,389] Trial 15 finished with value: 0.22569359660309307 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.24621146001328725
Fold 2 IBS: 0.23034282615145113
Fold 3 IBS: 0.22858350786099457
Fold 4 IBS: 0.2406853134797854
Fold 5 IBS: 0.2296779612068708
[I 2024-04-16 10:02:49,296] Trial 16 finished with value: 0.23510021374247786 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23238649953272297
Fold 2 IBS: 0.20522571780328708
Fold 3 IBS: 0.2145846471910429
Fold 4 IBS: 0.22586530498930596
Fold 5 IBS: 0.21689598457058412
[I 2024-04-16 10:02:52,260] Trial 17 finished with value: 0.21899163081738857 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-16 10:02:53,749] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23799175571463774
Fold 2 IBS: 0.20856598566333068
Fold 3 IBS: 0.2156754063279769
Fold 4 IBS: 0.228321331232294
Fold 5 IBS: 0.2178366309149347
[I 2024-04-16 10:02:57,702] Trial 19 finished with value: 0.2216782219706348 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23469726003280383
Fold 2 IBS: 0.23493019653744376
Fold 3 IBS: 0.23215912233770336
Fold 4 IBS: 0.23941545529653602
Fold 5 IBS: 0.23140883589967715
[I 2024-04-16 10:02:57,928] Trial 20 finished with value: 0.2345221740208328 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23535239524904697
Fold 2 IBS: 0.1985161012331111
Fold 3 IBS: 0.20787969783088261
Fold 4 IBS: 0.22407583975443468
Fold 5 IBS: 0.21394356881287288
[I 2024-04-16 10:03:02,304] Trial 21 finished with value: 0.21595352057606965 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23689039786450464
Fold 2 IBS: 0.19994319213832482
Fold 3 IBS: 0.2082820627664665
Fold 4 IBS: 0.2229405856912787
Fold 5 IBS: 0.21329751130992539
[I 2024-04-16 10:03:06,664] Trial 22 finished with value: 0.21627074995410003 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23555039629517807
Fold 2 IBS: 0.19531521716096664
Fold 3 IBS: 0.20445816608904363
Fold 4 IBS: 0.22172069076864817
Fold 5 IBS: 0.21199531180224912
[I 2024-04-16 10:03:10,154] Trial 23 finished with value: 0.21380795642321715 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23564341252996482
Fold 2 IBS: 0.19769803890967363
Fold 3 IBS: 0.2050527930071716
Fold 4 IBS: 0.22156119396188284
Fold 5 IBS: 0.2125066249962274
[I 2024-04-16 10:03:13,325] Trial 24 finished with value: 0.21449241268098404 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.2412495378451853
Fold 2 IBS: 0.2138545168543657
Fold 3 IBS: 0.21614574127509031
Fold 4 IBS: 0.2315122708296183
Fold 5 IBS: 0.2205004347232597
[I 2024-04-16 10:03:15,854] Trial 25 finished with value: 0.22465250030550385 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.24071760310386967
Fold 2 IBS: 0.21428940871163693
Fold 3 IBS: 0.21634044947480477
Fold 4 IBS: 0.23135797631383515
Fold 5 IBS: 0.22090551872419154
[I 2024-04-16 10:03:20,332] Trial 26 finished with value: 0.22472219126566761 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8454924050883471, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.24200474329522553
Fold 2 IBS: 0.22024877677304552
Fold 3 IBS: 0.22086174109325418
Fold 4 IBS: 0.23319439205898157
Fold 5 IBS: 0.2228226769426948
[I 2024-04-16 10:03:22,248] Trial 27 finished with value: 0.22782646603264034 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23583136061067697
Fold 2 IBS: 0.21246443337155693
Fold 3 IBS: 0.21753908573492847
Fold 4 IBS: 0.23187686848490693
Fold 5 IBS: 0.22092535233998586
[I 2024-04-16 10:03:26,536] Trial 28 finished with value: 0.22372742010841104 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.10561943508937117}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.2439849599164511
Fold 2 IBS: 0.22660077512505378
Fold 3 IBS: 0.22575096499647723
Fold 4 IBS: 0.23836936885258542
Fold 5 IBS: 0.2284088658264573
[I 2024-04-16 10:03:30,477] Trial 29 finished with value: 0.23262298694340497 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.20961630150441302.

Fold 1 IBS: 0.242353362091815
Fold 2 IBS: 0.21339799384020264
Fold 3 IBS: 0.21726638914512997
Fold 4 IBS: 0.23267246744838713
Fold 5 IBS: 0.2212980602481738
[I 2024-04-16 10:03:34,343] Trial 30 finished with value: 0.22539765455474173 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23674198115352363
Fold 2 IBS: 0.19518122847366612
Fold 3 IBS: 0.2050120018943178
Fold 4 IBS: 0.22046781019161954
Fold 5 IBS: 0.21215749826372995
[I 2024-04-16 10:03:37,962] Trial 31 finished with value: 0.2139121039953714 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7359152304070016, 'min_weight_fraction_leaf': 0.08655997300539783}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23616711726512715
Fold 2 IBS: 0.19668914054471603
Fold 3 IBS: 0.2059408610529654
Fold 4 IBS: 0.22206884003191094
Fold 5 IBS: 0.21292859180338186
[I 2024-04-16 10:03:41,476] Trial 32 finished with value: 0.21475891013962026 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.618283894727248, 'min_weight_fraction_leaf': 0.07716716290582956}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.24364205325069668
Fold 2 IBS: 0.22297592289144688
Fold 3 IBS: 0.22176358463940432
Fold 4 IBS: 0.23546440254929168
Fold 5 IBS: 0.2246726204325186
[I 2024-04-16 10:03:44,905] Trial 33 finished with value: 0.22970371675267165 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8125920153130402, 'min_weight_fraction_leaf': 0.12995854366525855}. Best is trial 12 with value: 0.20961630150441302.
Fold 1 IBS: 0.23297037023832048
Fold 2 IBS: 0.18959892038347967
Fold 3 IBS: 0.19534932544200698
Fold 4 IBS: 0.21717452236002283
Fold 5 IBS: 0.20527966173843912
[I 2024-04-16 10:03:47,898] Trial 34 finished with value: 0.20807456003245384 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6862833758870215, 'min_weight_fraction_leaf': 0.03963928663346105}. Best is trial 34 with value: 0.20807456003245384.
Fold 1 IBS: 0.23268506144143597
Fold 2 IBS: 0.18678365363532407
Fold 3 IBS: 0.19495086041150664
Fold 4 IBS: 0.2137740507716225
Fold 5 IBS: 0.2042060044954728
[I 2024-04-16 10:03:50,554] Trial 35 finished with value: 0.2064799261510724 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 285, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6699891298567331, 'min_weight_fraction_leaf': 0.035087014488190155}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23080729966808522
Fold 2 IBS: 0.18942585440827062
Fold 3 IBS: 0.19587682821914823
Fold 4 IBS: 0.21658537573995001
Fold 5 IBS: 0.20544171839223987
[I 2024-04-16 10:03:52,704] Trial 36 finished with value: 0.2076274152855388 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 222, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6844865203338923, 'min_weight_fraction_leaf': 0.03598599955769185}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23430981890914035
Fold 2 IBS: 0.19125293268833504
Fold 3 IBS: 0.19754998315829309
Fold 4 IBS: 0.21846428868359755
Fold 5 IBS: 0.20614604204341472
[I 2024-04-16 10:03:55,190] Trial 37 finished with value: 0.20954461309655614 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 209, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5201827001456041, 'min_weight_fraction_leaf': 0.030440421568832744}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23637887040735217
Fold 2 IBS: 0.20475785813217653
Fold 3 IBS: 0.20867434956787076
Fold 4 IBS: 0.22709839762033585
Fold 5 IBS: 0.21568291151002564
[I 2024-04-16 10:03:57,571] Trial 38 finished with value: 0.2185184774475522 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 214, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40610193315353077, 'min_weight_fraction_leaf': 0.044619031758070776}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2420199889630154
Fold 2 IBS: 0.21359815884632294
Fold 3 IBS: 0.2111841471555673
Fold 4 IBS: 0.23012342060814273
Fold 5 IBS: 0.2212315650587136
[I 2024-04-16 10:03:59,850] Trial 39 finished with value: 0.22363145612635238 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5113449703610475, 'min_weight_fraction_leaf': 0.032660270513651425}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2407782418379707
Fold 2 IBS: 0.2125971391290995
Fold 3 IBS: 0.21746227452828593
Fold 4 IBS: 0.22840328810433513
Fold 5 IBS: 0.21809603147987988
[I 2024-04-16 10:04:01,785] Trial 40 finished with value: 0.22346739501591423 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 169, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5320171133883594, 'min_weight_fraction_leaf': 0.11861732014948348}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2351609124994299
Fold 2 IBS: 0.19501489818568782
Fold 3 IBS: 0.20310530197164228
Fold 4 IBS: 0.22202459831234944
Fold 5 IBS: 0.20913725842134948
[I 2024-04-16 10:04:04,234] Trial 41 finished with value: 0.21288859387809178 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 233, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5866291705002558, 'min_weight_fraction_leaf': 0.05785299024344398}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23019441694965304
Fold 2 IBS: 0.1890085540033579
Fold 3 IBS: 0.191222393459484
Fold 4 IBS: 0.21634938592099162
Fold 5 IBS: 0.2057638332539035
[I 2024-04-16 10:04:06,978] Trial 42 finished with value: 0.20650771671747803 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 279, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6780823792802496, 'min_weight_fraction_leaf': 0.024593558245307935}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23104015212708987
Fold 2 IBS: 0.18998270517396296
Fold 3 IBS: 0.19566587961579598
Fold 4 IBS: 0.2157103816654228
Fold 5 IBS: 0.20545450183622233
[I 2024-04-16 10:04:09,608] Trial 43 finished with value: 0.20757072408369875 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 284, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7063394093413402, 'min_weight_fraction_leaf': 0.025460784920656652}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2401689359997014
Fold 2 IBS: 0.2080985282046952
Fold 3 IBS: 0.20980117716826197
Fold 4 IBS: 0.22816259274555822
Fold 5 IBS: 0.21614733584216517
[I 2024-04-16 10:04:12,228] Trial 44 finished with value: 0.22047571399207638 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 287, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6826607141009033, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 35 with value: 0.2064799261510724.

Fold 1 IBS: 0.2347053268942383
Fold 2 IBS: 0.1938225355692269
Fold 3 IBS: 0.19988939553972823
Fold 4 IBS: 0.22031520927619141
Fold 5 IBS: 0.21043236509727797
[I 2024-04-16 10:04:14,811] Trial 45 finished with value: 0.2118329664753326 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 284, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.7161510423088122, 'min_weight_fraction_leaf': 0.05492743841376213}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23315772457878367
Fold 2 IBS: 0.19283289362929562
Fold 3 IBS: 0.2009501574410602
Fold 4 IBS: 0.22027594986911345
Fold 5 IBS: 0.20896264084334623
[I 2024-04-16 10:04:17,711] Trial 46 finished with value: 0.2112358732723198 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 314, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.77223953632363, 'min_weight_fraction_leaf': 0.062543001089738}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.24136957316721788
Fold 2 IBS: 0.2220900482414143
Fold 3 IBS: 0.22116479410867682
Fold 4 IBS: 0.2352331655659413
Fold 5 IBS: 0.2239509787059272
[I 2024-04-16 10:04:19,902] Trial 47 finished with value: 0.2287617119578355 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 240, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6216858776002133, 'min_weight_fraction_leaf': 0.1625947698183845}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.24587568742360671
Fold 2 IBS: 0.230336793460673
Fold 3 IBS: 0.22846458039239234
Fold 4 IBS: 0.23947849703856205
Fold 5 IBS: 0.22830725867999074
[I 2024-04-16 10:04:23,801] Trial 48 finished with value: 0.23449256339904498 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 274, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6708341906838405, 'min_weight_fraction_leaf': 0.3098199009921797}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2465855050485315
Fold 2 IBS: 0.23209591914904104
Fold 3 IBS: 0.22940898093088674
Fold 4 IBS: 0.24164313817967256
Fold 5 IBS: 0.23014760866333128
[I 2024-04-16 10:04:25,522] Trial 49 finished with value: 0.23597623039429264 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 171, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.8063031158932581, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23746875691705016
Fold 2 IBS: 0.20664401702536975
Fold 3 IBS: 0.21324923634863022
Fold 4 IBS: 0.226055967673194
Fold 5 IBS: 0.21712188040534394
[I 2024-04-16 10:04:28,213] Trial 50 finished with value: 0.2201079716739176 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 303, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5954045060979408, 'min_weight_fraction_leaf': 0.1121860667542543}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23393171638277074
Fold 2 IBS: 0.19254723140244037
Fold 3 IBS: 0.19771881367258362
Fold 4 IBS: 0.21781792197370387
Fold 5 IBS: 0.20767784092913683
[I 2024-04-16 10:04:30,569] Trial 51 finished with value: 0.20993870487212707 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 254, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.554899867883559, 'min_weight_fraction_leaf': 0.026069679633803584}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23310060620557346
Fold 2 IBS: 0.18884581134739592
Fold 3 IBS: 0.19575648726372522
Fold 4 IBS: 0.22145958985478884
Fold 5 IBS: 0.20470459008990585
[I 2024-04-16 10:04:32,657] Trial 52 finished with value: 0.20877341695227786 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 191, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.45228815146589163, 'min_weight_fraction_leaf': 0.0019509583273463887}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2293033742019668
Fold 2 IBS: 0.19391143007133946
Fold 3 IBS: 0.20530906826534742
Fold 4 IBS: 0.22248043850692537
Fold 5 IBS: 0.20778114396274983
[I 2024-04-16 10:04:33,955] Trial 53 finished with value: 0.2117570910016658 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 126, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.41859456108995274, 'min_weight_fraction_leaf': 0.0011653317921695994}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2336345902563429
Fold 2 IBS: 0.19855135534726967
Fold 3 IBS: 0.20701521624906097
Fold 4 IBS: 0.2236166017249196
Fold 5 IBS: 0.20790139529979398
[I 2024-04-16 10:04:35,683] Trial 54 finished with value: 0.2141438317754774 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 185, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.3407325802402801, 'min_weight_fraction_leaf': 0.01776211117762474}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.24157331088606154
Fold 2 IBS: 0.21649695984087305
Fold 3 IBS: 0.21764367598774284
Fold 4 IBS: 0.23302685757263442
Fold 5 IBS: 0.22165255581118637
[I 2024-04-16 10:04:38,688] Trial 55 finished with value: 0.22607867201969967 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 333, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6931739477603681, 'min_weight_fraction_leaf': 0.06900961971618579}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.2329826344106978
Fold 2 IBS: 0.19575166292738896
Fold 3 IBS: 0.20389037597409793
Fold 4 IBS: 0.22119966422970128
Fold 5 IBS: 0.21095822675961193
[I 2024-04-16 10:04:41,069] Trial 56 finished with value: 0.21295651286029957 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 264, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.4570933817137677, 'min_weight_fraction_leaf': 0.03834918051662918}. Best is trial 35 with value: 0.2064799261510724.
Fold 1 IBS: 0.23103402438025128
Fold 2 IBS: 0.18055139390340708
Fold 3 IBS: 0.20166697312797108
Fold 4 IBS: 0.21705318924604977
Fold 5 IBS: 0.19827900800174
[I 2024-04-16 10:04:43,262] Trial 57 finished with value: 0.20571691773188383 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 233, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7687074462457086, 'min_weight_fraction_leaf': 0.016025847914471848}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2303587511642236
Fold 2 IBS: 0.18634974751141176
Fold 3 IBS: 0.20502548798640663
Fold 4 IBS: 0.212178800314967
Fold 5 IBS: 0.2057137702278461
[I 2024-04-16 10:04:45,448] Trial 58 finished with value: 0.20792531144097098 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 230, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8297869843717576, 'min_weight_fraction_leaf': 0.09389437446783147}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2437014808394117
Fold 2 IBS: 0.22538754388624643
Fold 3 IBS: 0.22564743579586888
Fold 4 IBS: 0.23952791543422203
Fold 5 IBS: 0.22826598718858468
[I 2024-04-16 10:04:48,142] Trial 59 finished with value: 0.23250607262886674 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 13, 'n_estimators': 237, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8360633322220128, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 57 with value: 0.20571691773188383.

Fold 1 IBS: 0.23265950444998454
Fold 2 IBS: 0.18636127453099866
Fold 3 IBS: 0.19993958938359596
Fold 4 IBS: 0.2162253571045426
Fold 5 IBS: 0.20381100578791037
[I 2024-04-16 10:04:50,231] Trial 60 finished with value: 0.20779934625140645 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 219, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9208992051748564, 'min_weight_fraction_leaf': 0.08831048402058213}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2310876809515107
Fold 2 IBS: 0.18774490398843385
Fold 3 IBS: 0.20242152649651662
Fold 4 IBS: 0.21366529710198845
Fold 5 IBS: 0.20379492815843792
[I 2024-04-16 10:04:52,559] Trial 61 finished with value: 0.20774286733937747 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 232, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9248961496485532, 'min_weight_fraction_leaf': 0.09104821379033963}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2352782823999446
Fold 2 IBS: 0.18487816273847338
Fold 3 IBS: 0.20020812439747357
Fold 4 IBS: 0.21776431757345951
Fold 5 IBS: 0.2033982510479429
[I 2024-04-16 10:04:54,836] Trial 62 finished with value: 0.2083054276314588 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 223, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9253048511626634, 'min_weight_fraction_leaf': 0.06399445607945686}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.24142320806629816
Fold 2 IBS: 0.18230951858740482
Fold 3 IBS: 0.20341277293151766
Fold 4 IBS: 0.220128727305064
Fold 5 IBS: 0.21129200327209777
[I 2024-04-16 10:04:57,529] Trial 63 finished with value: 0.2117132460324765 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 268, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9365042247575694, 'min_weight_fraction_leaf': 0.012496050336538894}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.22730791799052166
Fold 2 IBS: 0.1923219013252156
Fold 3 IBS: 0.2096451148148663
Fold 4 IBS: 0.21713098987614865
Fold 5 IBS: 0.21144946199068845
[I 2024-04-16 10:04:59,991] Trial 64 finished with value: 0.21157107719948814 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 251, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7759519595679867, 'min_weight_fraction_leaf': 0.141914112782639}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23310844929412863
Fold 2 IBS: 0.18662878606554953
Fold 3 IBS: 0.2042835035407403
Fold 4 IBS: 0.20950196281317934
Fold 5 IBS: 0.20827663933631899
[I 2024-04-16 10:05:03,441] Trial 65 finished with value: 0.20835986820998334 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 335, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8550412886514629, 'min_weight_fraction_leaf': 0.09654392670364854}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2467026474155206
Fold 2 IBS: 0.23211743003071852
Fold 3 IBS: 0.22949312716170547
Fold 4 IBS: 0.2415136600119815
Fold 5 IBS: 0.2302430365803021
[I 2024-04-16 10:05:05,650] Trial 66 finished with value: 0.23601398024004566 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 198, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7205375992106537, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2330803069068655
Fold 2 IBS: 0.183685066263366
Fold 3 IBS: 0.2027138186601394
Fold 4 IBS: 0.21450599414722984
Fold 5 IBS: 0.20376251708394708
[I 2024-04-16 10:05:08,710] Trial 67 finished with value: 0.20754954061230957 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 278, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.906646004890416, 'min_weight_fraction_leaf': 0.07850204539812101}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23302630897868232
Fold 2 IBS: 0.18623302938429703
Fold 3 IBS: 0.2060162990886244
Fold 4 IBS: 0.21609276036537517
Fold 5 IBS: 0.2077921858405305
[I 2024-04-16 10:05:11,978] Trial 68 finished with value: 0.2098321167315019 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 10, 'n_estimators': 322, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9664871688995124, 'min_weight_fraction_leaf': 0.04918508077503925}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.24076467300482898
Fold 2 IBS: 0.21239369539687555
Fold 3 IBS: 0.21508201097113527
Fold 4 IBS: 0.232474705301806
Fold 5 IBS: 0.2212872924640935
[I 2024-04-16 10:05:14,361] Trial 69 finished with value: 0.22440047542774785 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 271, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.8936783051754734, 'min_weight_fraction_leaf': 0.07586720386441106}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.24320460208602532
Fold 2 IBS: 0.22439551607650016
Fold 3 IBS: 0.22459413767422715
Fold 4 IBS: 0.23579944195621885
Fold 5 IBS: 0.22549245516953975
[I 2024-04-16 10:05:17,134] Trial 70 finished with value: 0.23069723059250222 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 249, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6642761268507975, 'min_weight_fraction_leaf': 0.21497621437910602}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2387559410404793
Fold 2 IBS: 0.17894348392199855
Fold 3 IBS: 0.20326987853815248
Fold 4 IBS: 0.2189649914774537
Fold 5 IBS: 0.20525704915474477
[I 2024-04-16 10:05:19,985] Trial 71 finished with value: 0.2090382688265658 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 11, 'n_estimators': 306, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.89777527857107, 'min_weight_fraction_leaf': 0.017607615128242864}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2343985001508229
Fold 2 IBS: 0.1871954142782053
Fold 3 IBS: 0.2013034381414081
Fold 4 IBS: 0.2129828716588136
Fold 5 IBS: 0.20221471553164294
[I 2024-04-16 10:05:22,064] Trial 72 finished with value: 0.20761898795217854 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 222, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9525961095514963, 'min_weight_fraction_leaf': 0.082176123689749}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.238023743930799
Fold 2 IBS: 0.1845271713779383
Fold 3 IBS: 0.20595297215824251
Fold 4 IBS: 0.21521594622573245
Fold 5 IBS: 0.19984221035367955
[I 2024-04-16 10:05:24,931] Trial 73 finished with value: 0.20871240880927838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 285, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9985454666108357, 'min_weight_fraction_leaf': 0.05107432062741957}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.22832366701200982
Fold 2 IBS: 0.18860904634987358
Fold 3 IBS: 0.20626710530367356
Fold 4 IBS: 0.2086218400373982
Fold 5 IBS: 0.20684120635761968
[I 2024-04-16 10:05:27,195] Trial 74 finished with value: 0.20773257301211498 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 244, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9513062038501129, 'min_weight_fraction_leaf': 0.12466563979314677}. Best is trial 57 with value: 0.20571691773188383.

Fold 1 IBS: 0.22515802372915686
Fold 2 IBS: 0.19075202603689245
Fold 3 IBS: 0.20939834429255869
Fold 4 IBS: 0.21245938135827597
Fold 5 IBS: 0.20851851328898718
[I 2024-04-16 10:05:29,514] Trial 75 finished with value: 0.2092572577411742 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 15, 'n_estimators': 250, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7564438927738872, 'min_weight_fraction_leaf': 0.12828483764121068}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.22744289060382553
Fold 2 IBS: 0.19075206728432154
Fold 3 IBS: 0.20554651061472592
Fold 4 IBS: 0.21217294361124195
Fold 5 IBS: 0.20891216606780766
[I 2024-04-16 10:05:31,993] Trial 76 finished with value: 0.2089653156363845 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 273, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.9522480184073386, 'min_weight_fraction_leaf': 0.15777250458506914}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23764352983811632
Fold 2 IBS: 0.1817141285863356
Fold 3 IBS: 0.20254600776340762
Fold 4 IBS: 0.21573304668543541
Fold 5 IBS: 0.2015759642474113
[I 2024-04-16 10:05:35,169] Trial 77 finished with value: 0.20784253542414124 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 349, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7967539528420338, 'min_weight_fraction_leaf': 0.0321045964344398}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2426917141820138
Fold 2 IBS: 0.2181357372303172
Fold 3 IBS: 0.21705462316329746
Fold 4 IBS: 0.23309999039357554
Fold 5 IBS: 0.22207437999566887
[I 2024-04-16 10:05:36,793] Trial 78 finished with value: 0.22661128899297456 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 182, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6276006950449654, 'min_weight_fraction_leaf': 0.07130519067880574}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23427985235107926
Fold 2 IBS: 0.1941147641342781
Fold 3 IBS: 0.19709925271903841
Fold 4 IBS: 0.21896770838115912
Fold 5 IBS: 0.20944977719672642
[I 2024-04-16 10:05:38,720] Trial 79 finished with value: 0.21078227095645624 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 14, 'n_estimators': 204, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.863788658996043, 'min_weight_fraction_leaf': 0.01721392468605365}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23741847558183043
Fold 2 IBS: 0.21444933257258855
Fold 3 IBS: 0.22037952090549673
Fold 4 IBS: 0.23345034169616496
Fold 5 IBS: 0.22186195827617425
[I 2024-04-16 10:05:41,333] Trial 80 finished with value: 0.225511925806451 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 295, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7489417532267347, 'min_weight_fraction_leaf': 0.2578980132057934}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23267603119555685
Fold 2 IBS: 0.1861778126525961
Fold 3 IBS: 0.20386339128727007
Fold 4 IBS: 0.21352859443223657
Fold 5 IBS: 0.20724719757735158
[I 2024-04-16 10:05:43,567] Trial 81 finished with value: 0.20869860542900223 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 13, 'n_estimators': 239, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.951765636913406, 'min_weight_fraction_leaf': 0.10629213764859513}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23346858065307327
Fold 2 IBS: 0.18670921799821416
Fold 3 IBS: 0.20190246424311514
Fold 4 IBS: 0.21405341619790538
Fold 5 IBS: 0.20407050724330533
[I 2024-04-16 10:05:45,672] Trial 82 finished with value: 0.20804083726712266 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 223, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8960105116487151, 'min_weight_fraction_leaf': 0.08527319738637096}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.24076685551833524
Fold 2 IBS: 0.21305877774383605
Fold 3 IBS: 0.21558495400925115
Fold 4 IBS: 0.2300185943161864
Fold 5 IBS: 0.220366610382598
[I 2024-04-16 10:05:47,958] Trial 83 finished with value: 0.22395915839404137 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 262, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7015913166682375, 'min_weight_fraction_leaf': 0.05338237886518023}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23246206643713657
Fold 2 IBS: 0.18538831159913158
Fold 3 IBS: 0.20670772606885016
Fold 4 IBS: 0.21055404677323492
Fold 5 IBS: 0.20044910864008247
[I 2024-04-16 10:05:50,568] Trial 84 finished with value: 0.20711225190368712 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 279, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6472561006310977, 'min_weight_fraction_leaf': 0.038390833827911516}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23625359413866323
Fold 2 IBS: 0.19855841225595836
Fold 3 IBS: 0.20348620047977495
Fold 4 IBS: 0.22206947490158757
Fold 5 IBS: 0.21403388496411999
[I 2024-04-16 10:05:53,118] Trial 85 finished with value: 0.21488031334802082 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 282, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6550757812215047, 'min_weight_fraction_leaf': 0.0624506021791882}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23447613943107276
Fold 2 IBS: 0.18601384628577902
Fold 3 IBS: 0.20566531859838766
Fold 4 IBS: 0.21207851176851725
Fold 5 IBS: 0.20147574489621595
[I 2024-04-16 10:05:56,592] Trial 86 finished with value: 0.20794191219599453 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 312, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5956458342960947, 'min_weight_fraction_leaf': 0.03833323271988472}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.2463984942726958
Fold 2 IBS: 0.23213433667461578
Fold 3 IBS: 0.2299769651556026
Fold 4 IBS: 0.2410402984163441
Fold 5 IBS: 0.23027966182647575
[I 2024-04-16 10:06:00,523] Trial 87 finished with value: 0.23596595126914682 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 19, 'n_estimators': 296, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.18254281589037946, 'min_weight_fraction_leaf': 0.029840287914366964}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23260989226964826
Fold 2 IBS: 0.18652072272758202
Fold 3 IBS: 0.20529350527588108
Fold 4 IBS: 0.20883440580463689
Fold 5 IBS: 0.20198282222878905
[I 2024-04-16 10:06:03,974] Trial 88 finished with value: 0.20704826966130746 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 332, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7092277130611284, 'min_weight_fraction_leaf': 0.04622301348310539}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23535054418954113
Fold 2 IBS: 0.18562743834257592
Fold 3 IBS: 0.19514118729513735
Fold 4 IBS: 0.21736481121095436
Fold 5 IBS: 0.20157198049865382
[I 2024-04-16 10:06:07,222] Trial 89 finished with value: 0.20701119230737247 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6427994020303571, 'min_weight_fraction_leaf': 0.007152221585354116}. Best is trial 57 with value: 0.20571691773188383.

Fold 1 IBS: 0.23162104883048065
Fold 2 IBS: 0.18920181466408656
Fold 3 IBS: 0.1946949770737152
Fold 4 IBS: 0.21631250088639659
Fold 5 IBS: 0.20244287119552642
[I 2024-04-16 10:06:10,513] Trial 90 finished with value: 0.2068546425300411 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7134961759303595, 'min_weight_fraction_leaf': 0.009412107712000094}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23181164849341912
Fold 2 IBS: 0.1893769722084939
Fold 3 IBS: 0.19447302134656916
Fold 4 IBS: 0.2163472127256083
Fold 5 IBS: 0.20229925588198513
[I 2024-04-16 10:06:13,810] Trial 91 finished with value: 0.20686162213121512 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7150532914239828, 'min_weight_fraction_leaf': 0.012296199838007407}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23218693226566028
Fold 2 IBS: 0.1871951141303739
Fold 3 IBS: 0.19341614227674322
Fold 4 IBS: 0.21597310276337037
Fold 5 IBS: 0.20210786464610833
[I 2024-04-16 10:06:17,051] Trial 92 finished with value: 0.20617583121645122 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 358, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7096547014841971, 'min_weight_fraction_leaf': 0.00808533839179477}. Best is trial 57 with value: 0.20571691773188383.
Fold 1 IBS: 0.23107055298133886
Fold 2 IBS: 0.18657924606093554
Fold 3 IBS: 0.19455732070942153
Fold 4 IBS: 0.2150628283764248
Fold 5 IBS: 0.2001660123689917
[I 2024-04-16 10:06:20,481] Trial 93 finished with value: 0.20548719209942248 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7323699705283335, 'min_weight_fraction_leaf': 0.01206291096955849}. Best is trial 93 with value: 0.20548719209942248.
Fold 1 IBS: 0.23099217076529782
Fold 2 IBS: 0.18668594670571312
Fold 3 IBS: 0.19456384286189174
Fold 4 IBS: 0.21501443300804354
Fold 5 IBS: 0.20025366099088127
[I 2024-04-16 10:06:24,537] Trial 94 finished with value: 0.2055020108663655 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7342217995930476, 'min_weight_fraction_leaf': 0.010678877290218113}. Best is trial 93 with value: 0.20548719209942248.
Fold 1 IBS: 0.23123877046871025
Fold 2 IBS: 0.1839873005635921
Fold 3 IBS: 0.19637446894332045
Fold 4 IBS: 0.21367433726646975
Fold 5 IBS: 0.20025366099088127
[I 2024-04-16 10:06:28,034] Trial 95 finished with value: 0.20510570764659475 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7338953025585497, 'min_weight_fraction_leaf': 0.008989573072247403}. Best is trial 95 with value: 0.20510570764659475.
Fold 1 IBS: 0.2315446348494711
Fold 2 IBS: 0.18632610994974572
Fold 3 IBS: 0.19514925859602342
Fold 4 IBS: 0.21591571675278415
Fold 5 IBS: 0.20091745426920563
[I 2024-04-16 10:06:31,782] Trial 96 finished with value: 0.20597063488344597 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 373, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7323855044658225, 'min_weight_fraction_leaf': 0.009206476831808275}. Best is trial 95 with value: 0.20510570764659475.
Fold 1 IBS: 0.23117896271227362
Fold 2 IBS: 0.18520856857476614
Fold 3 IBS: 0.19582011666702745
Fold 4 IBS: 0.21662318451302054
Fold 5 IBS: 0.20089607948912622
[I 2024-04-16 10:06:35,327] Trial 97 finished with value: 0.2059453823912428 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 374, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7388896040325839, 'min_weight_fraction_leaf': 0.008052162950262131}. Best is trial 95 with value: 0.20510570764659475.
Fold 1 IBS: 0.23198202766212653
Fold 2 IBS: 0.18539156649183258
Fold 3 IBS: 0.19630166153269088
Fold 4 IBS: 0.21659667530802648
Fold 5 IBS: 0.2012669734008026
[I 2024-04-16 10:06:38,791] Trial 98 finished with value: 0.20630778087909585 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 379, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7372496540657394, 'min_weight_fraction_leaf': 0.0007889734324125781}. Best is trial 95 with value: 0.20510570764659475.
Fold 1 IBS: 0.22953326662808884
Fold 2 IBS: 0.18800261853607836
Fold 3 IBS: 0.19407181246705787
Fold 4 IBS: 0.22027021149571147
Fold 5 IBS: 0.20450940968404038
[I 2024-04-16 10:06:42,304] Trial 99 finished with value: 0.20727746376219539 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7781535567621067, 'min_weight_fraction_leaf': 0.022281545555367488}. Best is trial 95 with value: 0.20510570764659475.


* Best trial for IBS:
 FrozenTrial(number=95, state=TrialState.COMPLETE, values=[0.20510570764659475], datetime_start=datetime.datetime(2024, 4, 16, 10, 6, 24, 543749), datetime_complete=datetime.datetime(2024, 4, 16, 10, 6, 28, 33500), params={'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 375, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7338953025585497, 'min_weight_fraction_leaf': 0.008989573072247403}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=95, value=None)


* Best Score for IBS:
 0.20510570764659475

In [123]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [124]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.798
train_ibs:  0.205

#### Test

In [125]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [126]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=18, max_features=None, max_leaf_nodes=16,
                   max_samples=0.7746492428469892, min_samples_leaf=4,
                   min_samples_split=2,
                   min_weight_fraction_leaf=0.02592476635662061,
                   n_estimators=190, oob_score=True, random_state=123,
                   warm_start=True)

C-index score: 0.506

ExtraSurvivalTrees(max_depth=19, max_features='log2', max_leaf_nodes=11,
                   max_samples=0.7338953025585497, min_samples_leaf=1,
                   min_samples_split=18,
                   min_weight_fraction_leaf=0.008989573072247403,
                   n_estimators=375, random_state=123, warm_start=True)

IBS: 0.25

In [127]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [128]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 10:06:43,627] A new study created in memory with name: no-name-2a3db80f-1c91-4492-a0b3-3e9b4413f1b5

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:07:02,476] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:07:12,540] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:07:21,641] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:07:36,150] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:07:42,236] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:07:43,758] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:08:00,326] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:08:05,301] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:08:05,916] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.648936170212766
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6437768240343348
[I 2024-04-16 10:08:45,402] Trial 9 finished with value: 0.687089865261709 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.687089865261709.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 10:09:46,735] Trial 10 finished with value: 0.6677145778312712 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.687089865261709.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:10:57,972] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.687089865261709.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6931330472103004
[I 2024-04-16 10:11:57,555] Trial 12 finished with value: 0.689211725925309 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.689211725925309.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:12:27,483] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:13:12,601] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:13:52,244] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:14:17,565] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:15:13,090] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:16:32,416] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:16:35,876] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:17:04,828] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-16 10:18:07,163] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7344961240310077
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 10:19:05,691] Trial 22 finished with value: 0.6557020277694866 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:20:04,772] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:20:52,255] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:21:47,311] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:22:09,592] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:23:13,039] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:23:16,806] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:24:09,447] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:24:26,482] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-16 10:25:28,992] Trial 31 finished with value: 0.6020563220294257 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:26:36,862] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:27:24,285] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:28:11,264] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 10:28:42,000] Trial 35 finished with value: 0.6696723635949839 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:29:07,231] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:29:23,961] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:29:36,145] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:29:49,559] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:30:05,945] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6072961373390557
[I 2024-04-16 10:30:57,978] Trial 41 finished with value: 0.6409733650714282 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:31:37,354] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:32:24,173] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:32:37,923] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:33:28,585] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 12 with value: 0.689211725925309.
Fold 1 C-index: 0.603585657370518
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.6977186311787072
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 10:33:35,073] Trial 46 finished with value: 0.6922524849655768 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:33:45,270] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:33:45,473] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:33:51,690] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:34:21,983] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.6749049429657795
Fold 5 C-index: 0.6609442060085837
[I 2024-04-16 10:34:50,135] Trial 51 finished with value: 0.6777403203873436 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:35:05,989] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.7538759689922481
Fold 3 C-index: 0.7
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.6373390557939914
[I 2024-04-16 10:35:36,384] Trial 53 finished with value: 0.6749363835341949 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:03,965] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:09,577] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:37,118] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 10:36:40,967] Trial 57 finished with value: 0.6913758106424096 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:45,131] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:50,956] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:36:56,944] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 46 with value: 0.6922524849655768.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:37:05,743] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 46 with value: 0.6922524849655768.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6695278969957081
[I 2024-04-16 10:37:22,487] Trial 62 finished with value: 0.701705212046132 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7053231939163498
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 10:37:36,956] Trial 63 finished with value: 0.6930458872957279 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:37:52,639] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.4297477654076297, 'learning_rate': 0.03167082341067062, 'dropout_rate': 0.8352402756430523, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4320841878399444, 'min_weight_fraction_leaf': 0.262263288003764, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9704806495311973, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:38:05,381] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.30781242416514565, 'learning_rate': 0.035706438264726054, 'dropout_rate': 0.9070553557876073, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9229393860301199, 'min_weight_fraction_leaf': 0.309698162609194, 'max_features': 'sqrt', 'min_impurity_decrease': 0.009270213926391263, 'validation_fraction': 0.9980996520608811, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:38:22,510] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.4940796114228873, 'learning_rate': 0.04310216489618765, 'dropout_rate': 0.7343017774937423, 'n_estimators': 415, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5356537836856377, 'min_weight_fraction_leaf': 0.2862767894594348, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001837889881839292, 'validation_fraction': 0.3085811036906729, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:38:28,781] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4210285565476828, 'learning_rate': 0.050089102888303386, 'dropout_rate': 0.9683202197361045, 'n_estimators': 439, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6259173019583208, 'min_weight_fraction_leaf': 0.26956754513635534, 'max_features': 'sqrt', 'min_impurity_decrease': 0.03775558722634611, 'validation_fraction': 0.904139153167577, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:38:41,693] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.36755564370451066, 'learning_rate': 0.02012145930359608, 'dropout_rate': 0.8584125222716712, 'n_estimators': 458, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1963333375412561, 'min_weight_fraction_leaf': 0.24702341213277396, 'max_features': 1, 'min_impurity_decrease': 0.013697139277504513, 'validation_fraction': 0.715818151257265, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:00,573] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.4580799169024674, 'learning_rate': 0.06977277743599776, 'dropout_rate': 0.798114398171325, 'n_estimators': 486, 'criterion': 'friedman_mse', 'ccp_alpha': 0.29402796325363834, 'min_weight_fraction_leaf': 0.22161177753979142, 'max_features': 'log2', 'min_impurity_decrease': 0.001581139753892363, 'validation_fraction': 0.9526558691939723, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6652360515021459
[I 2024-04-16 10:39:10,647] Trial 70 finished with value: 0.6939032349931498 and parameters: {'subsample': 0.5134787621027924, 'learning_rate': 0.02805743847404006, 'dropout_rate': 0.9288483863786423, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 0.010011726187714272, 'min_weight_fraction_leaf': 0.3011740807021421, 'max_features': 0.1, 'min_impurity_decrease': 0.0002956468253897944, 'validation_fraction': 0.7562323520914638, 'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.6566523605150214
[I 2024-04-16 10:39:13,042] Trial 71 finished with value: 0.7010889269092324 and parameters: {'subsample': 0.5131192378371329, 'learning_rate': 0.027272277842637044, 'dropout_rate': 0.9233304373928054, 'n_estimators': 177, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027675819185793663, 'min_weight_fraction_leaf': 0.30209681644390535, 'max_features': 0.1, 'min_impurity_decrease': 0.0011019552130728865, 'validation_fraction': 0.8184047274043963, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:14,990] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.5262594360584141, 'learning_rate': 0.026289054336699837, 'dropout_rate': 0.91502503958971, 'n_estimators': 151, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7530156413438767, 'min_weight_fraction_leaf': 0.3032600022438751, 'max_features': 0.1, 'min_impurity_decrease': 0.0003037017436105227, 'validation_fraction': 0.7641889881477056, 'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 62 with value: 0.701705212046132.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:17,297] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.4814809249533932, 'learning_rate': 0.034116480081869405, 'dropout_rate': 0.9272479513034744, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.35666680166132303, 'min_weight_fraction_leaf': 0.2765107966115551, 'max_features': 0.1, 'min_impurity_decrease': 0.0010312874624421808, 'validation_fraction': 0.8120762455660575, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:19,054] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.42309782837188237, 'learning_rate': 0.02949499300484511, 'dropout_rate': 0.8762079395596291, 'n_estimators': 132, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9759151255531388, 'min_weight_fraction_leaf': 0.3239344013372409, 'max_features': 0.1, 'min_impurity_decrease': 0.004288650403469109, 'validation_fraction': 0.7490498465938689, 'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.701705212046132.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7091254752851711
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 10:39:19,826] Trial 75 finished with value: 0.7060870536776628 and parameters: {'subsample': 0.576035216401896, 'learning_rate': 0.013221996813333869, 'dropout_rate': 0.9811764618124919, 'n_estimators': 99, 'criterion': 'friedman_mse', 'ccp_alpha': 0.008912857872006769, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 0.1, 'min_impurity_decrease': 0.0006905263252705159, 'validation_fraction': 0.860660039973653, 'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:21,655] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.5759403431999695, 'learning_rate': 0.04036762497523495, 'dropout_rate': 0.9796816851158388, 'n_estimators': 198, 'criterion': 'friedman_mse', 'ccp_alpha': 0.30261038604204304, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 0.1, 'min_impurity_decrease': 0.0007615811584742783, 'validation_fraction': 0.8591000661893881, 'min_samples_split': 17, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:22,268] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.5087733516881157, 'learning_rate': 0.038248399564390356, 'dropout_rate': 0.9472175566607237, 'n_estimators': 65, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5941090997205053, 'min_weight_fraction_leaf': 0.2937228091140052, 'max_features': 0.1, 'min_impurity_decrease': 0.0019164928071485558, 'validation_fraction': 0.7885888076146406, 'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.7124463519313304
[I 2024-04-16 10:39:23,567] Trial 78 finished with value: 0.701379297542913 and parameters: {'subsample': 0.43618263385881817, 'learning_rate': 0.014372335861434124, 'dropout_rate': 0.8982082105086914, 'n_estimators': 99, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.317233921173851, 'max_features': 0.1, 'min_impurity_decrease': 0.0003159968614630225, 'validation_fraction': 0.9035859714661311, 'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.7296137339055794
[I 2024-04-16 10:39:25,008] Trial 79 finished with value: 0.7010757568293993 and parameters: {'subsample': 0.443905671515513, 'learning_rate': 0.022360430269620486, 'dropout_rate': 0.8994265115864019, 'n_estimators': 110, 'criterion': 'friedman_mse', 'ccp_alpha': 0.006881367522992329, 'min_weight_fraction_leaf': 0.34239144090820406, 'max_features': 0.1, 'min_impurity_decrease': 0.00026754667959111344, 'validation_fraction': 0.8251082652585102, 'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:26,453] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.438172882306978, 'learning_rate': 0.021056979945437124, 'dropout_rate': 0.8356135239424233, 'n_estimators': 112, 'criterion': 'friedman_mse', 'ccp_alpha': 5.796520641928455, 'min_weight_fraction_leaf': 0.3181272670030366, 'max_features': 0.1, 'min_impurity_decrease': 0.001280723995124022, 'validation_fraction': 0.8993518768709966, 'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.547808764940239
Fold 2 C-index: 0.7073643410852714
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.648068669527897
[I 2024-04-16 10:39:27,093] Trial 81 finished with value: 0.6323885055839441 and parameters: {'subsample': 0.40270518369951813, 'learning_rate': 0.01443183849621029, 'dropout_rate': 0.9350730912271931, 'n_estimators': 65, 'criterion': 'friedman_mse', 'ccp_alpha': 0.025557079673147583, 'min_weight_fraction_leaf': 0.3032960129246959, 'max_features': 0.1, 'min_impurity_decrease': 0.0003784859639380024, 'validation_fraction': 0.8277635591503593, 'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:27,996] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.33578551109478, 'learning_rate': 0.024041843678746875, 'dropout_rate': 0.8984629056522297, 'n_estimators': 86, 'criterion': 'friedman_mse', 'ccp_alpha': 0.29093310545892165, 'min_weight_fraction_leaf': 0.3274912435637577, 'max_features': 0.1, 'min_impurity_decrease': 0.00012446223579366765, 'validation_fraction': 0.8520851342828201, 'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:28,498] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.5485591701074478, 'learning_rate': 0.027932750235286803, 'dropout_rate': 0.8543421907414702, 'n_estimators': 46, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6371924903356401, 'min_weight_fraction_leaf': 0.3565173549707516, 'max_features': 0.1, 'min_impurity_decrease': 0.0002564021280462751, 'validation_fraction': 0.8127975045846076, 'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:29,391] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.40109733784932894, 'learning_rate': 0.019231455340042603, 'dropout_rate': 0.8984845244020045, 'n_estimators': 88, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2622208926429443, 'min_weight_fraction_leaf': 0.3431778335030617, 'max_features': 0.1, 'min_impurity_decrease': 0.0005511881175550413, 'validation_fraction': 0.869407406135435, 'min_samples_split': 13, 'max_leaf_nodes': 4, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 75 with value: 0.7060870536776628.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:30,941] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.47409059174685836, 'learning_rate': 0.01617831413355696, 'dropout_rate': 0.9758355537271111, 'n_estimators': 174, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9007814287405299, 'min_weight_fraction_leaf': 0.2535805209193146, 'max_features': 0.1, 'min_impurity_decrease': 0.0027619407916087907, 'validation_fraction': 0.7691554866622335, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:31,865] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.37025829887477724, 'learning_rate': 0.03396899261532703, 'dropout_rate': 0.9945673550653182, 'n_estimators': 122, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2793432786350283, 'min_weight_fraction_leaf': 0.2780370351275338, 'max_features': 0.1, 'min_impurity_decrease': 0.0005522126336701015, 'validation_fraction': 0.9091779885833091, 'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:33,441] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.4476543911090847, 'learning_rate': 0.0233220210502826, 'dropout_rate': 0.9348822967430029, 'n_estimators': 148, 'criterion': 'friedman_mse', 'ccp_alpha': 0.598937287016192, 'min_weight_fraction_leaf': 0.37775372461639084, 'max_features': 0.1, 'min_impurity_decrease': 0.00010953730252622326, 'validation_fraction': 0.7058472436092041, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:35,956] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.5048905094884654, 'learning_rate': 0.004765503583322712, 'dropout_rate': 0.9595253559213653, 'n_estimators': 230, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5432824906216296, 'min_weight_fraction_leaf': 0.3185087694855689, 'max_features': 0.1, 'min_impurity_decrease': 0.0008918628927844579, 'validation_fraction': 0.8356916689575291, 'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 75 with value: 0.7060870536776628.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6995708154506438
[I 2024-04-16 10:39:37,166] Trial 89 finished with value: 0.7139824021493644 and parameters: {'subsample': 0.5853469030360458, 'learning_rate': 0.012605940574103688, 'dropout_rate': 0.7944636502481695, 'n_estimators': 92, 'criterion': 'friedman_mse', 'ccp_alpha': 0.019083182133763817, 'min_weight_fraction_leaf': 0.2980965136087394, 'max_features': 0.1, 'min_impurity_decrease': 3.8585457393914055e-05, 'validation_fraction': 0.8781823868858244, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:38,256] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.5899855031174466, 'learning_rate': 0.01749360314308157, 'dropout_rate': 0.7964839891645453, 'n_estimators': 85, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4643570370622033, 'min_weight_fraction_leaf': 0.30065729358539284, 'max_features': 0.1, 'min_impurity_decrease': 1.5414471614179684e-05, 'validation_fraction': 0.8771622863588029, 'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6716738197424893
[I 2024-04-16 10:39:39,261] Trial 91 finished with value: 0.6884913641937142 and parameters: {'subsample': 0.5402123586436749, 'learning_rate': 0.013711852133235655, 'dropout_rate': 0.8868708195499712, 'n_estimators': 94, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03815382570853529, 'min_weight_fraction_leaf': 0.3467385886055334, 'max_features': 0.1, 'min_impurity_decrease': 0.00030882952913924, 'validation_fraction': 0.9341029487567909, 'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:40,992] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.6336029885336751, 'learning_rate': 0.02166527114720276, 'dropout_rate': 0.833509716163244, 'n_estimators': 129, 'criterion': 'friedman_mse', 'ccp_alpha': 0.1964312480491506, 'min_weight_fraction_leaf': 0.33559080296016275, 'max_features': 0.1, 'min_impurity_decrease': 0.0001694214281607453, 'validation_fraction': 0.8091923734392032, 'min_samples_split': 18, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:41,640] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.4893097457639444, 'learning_rate': 0.010769348326614796, 'dropout_rate': 0.7595882154528453, 'n_estimators': 53, 'criterion': 'friedman_mse', 'ccp_alpha': 0.79151438040116, 'min_weight_fraction_leaf': 0.2837393860156707, 'max_features': 0.1, 'min_impurity_decrease': 0.00045824927240240736, 'validation_fraction': 0.8938187086448058, 'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:42,429] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.5721902927100647, 'learning_rate': 0.027015608361764205, 'dropout_rate': 0.9996388908828326, 'n_estimators': 102, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2577519524074663, 'min_weight_fraction_leaf': 0.2659814532356022, 'max_features': 'log2', 'min_impurity_decrease': 3.710066880696022e-05, 'validation_fraction': 0.7359713920653446, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:42,846] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.4643342629795362, 'learning_rate': 0.045113137984773205, 'dropout_rate': 0.870184212696498, 'n_estimators': 34, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0427247942345068, 'min_weight_fraction_leaf': 0.36400550806182436, 'max_features': 0.1, 'min_impurity_decrease': 0.0006321362964544851, 'validation_fraction': 0.8617195473606613, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:43,604] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.28506695020704487, 'learning_rate': 0.014569270357939097, 'dropout_rate': 0.930103525599012, 'n_estimators': 75, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5026428905030527, 'min_weight_fraction_leaf': 0.2309674471274549, 'max_features': 1, 'min_impurity_decrease': 0.0012970274674372717, 'validation_fraction': 0.7814530112330332, 'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 89 with value: 0.7139824021493644.
Fold 1 C-index: 0.6772908366533864

Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6914893617021277
Fold 4 C-index: 0.720532319391635
Fold 5 C-index: 0.7017167381974249
[I 2024-04-16 10:39:46,168] Trial 97 finished with value: 0.7144074015765116 and parameters: {'subsample': 0.5167163717577359, 'learning_rate': 0.02998154803834563, 'dropout_rate': 0.8142690261508861, 'n_estimators': 161, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05874457198222169, 'min_weight_fraction_leaf': 0.3150248435971541, 'max_features': 0.1, 'min_impurity_decrease': 4.899193303970509e-05, 'validation_fraction': 0.8336552353722929, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 97 with value: 0.7144074015765116.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-16 10:39:49,241] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.6817613836246057, 'learning_rate': 0.03103099326429963, 'dropout_rate': 0.7345320318352758, 'n_estimators': 162, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.3113223191588845, 'max_features': 0.1, 'min_impurity_decrease': 0.00015276231139666014, 'validation_fraction': 0.97208801308084, 'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 97 with value: 0.7144074015765116.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-16 10:39:50,741] A new study created in memory with name: no-name-d5e2f582-026b-4ae6-bdfe-8ade0afab186

Fold 5 C-index: 0.5
[I 2024-04-16 10:39:50,732] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.5125850739118061, 'learning_rate': 0.024441920443866866, 'dropout_rate': 0.8164846757853067, 'n_estimators': 113, 'criterion': 'friedman_mse', 'ccp_alpha': 0.21868650221384833, 'min_weight_fraction_leaf': 0.29540894307930565, 'max_features': 0.1, 'min_impurity_decrease': 6.0684009304279075e-06, 'validation_fraction': 0.9128248956034617, 'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 97 with value: 0.7144074015765116.


* Best trial for C-index:
 FrozenTrial(number=97, state=TrialState.COMPLETE, values=[0.7144074015765116], datetime_start=datetime.datetime(2024, 4, 16, 10, 39, 43, 622937), datetime_complete=datetime.datetime(2024, 4, 16, 10, 39, 46, 167126), params={'subsample': 0.5167163717577359, 'learning_rate': 0.02998154803834563, 'dropout_rate': 0.8142690261508861, 'n_estimators': 161, 'criterion': 'friedman_mse', 'ccp_alpha': 0.05874457198222169, 'min_weight_fraction_leaf': 0.3150248435971541, 'max_features': 0.1, 'min_impurity_decrease': 4.899193303970509e-05, 'validation_fraction': 0.8336552353722929, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 13, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=97, value=None)


* Best Score for C-index:
 0.7144074015765116

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:40:09,196] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:40:18,389] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:40:27,314] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 10:40:40,885] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:40:46,535] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:40:47,930] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:41:02,413] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:41:07,230] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:41:07,819] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24597905353670027
Fold 2 IBS: 0.2303334700282273
Fold 3 IBS: 0.2286375431505004
Fold 4 IBS: 0.24088736437983022
Fold 5 IBS: 0.22857407337624217
[I 2024-04-16 10:41:43,525] Trial 9 finished with value: 0.2348823008943001 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316595760132136
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-16 10:42:39,596] Trial 10 finished with value: 0.2356341548121131 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 10:43:42,217] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24714052976423928
Fold 2 IBS: 0.23184476824066438
Fold 3 IBS: 0.2289550256511867
Fold 4 IBS: 0.2418708580239349
Fold 5 IBS: 0.22931382332217862
[I 2024-04-16 10:44:35,981] Trial 12 finished with value: 0.2358250010004408 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:45:01,482] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:45:46,735] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:46:24,389] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:46:43,697] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:47:29,806] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:47:53,514] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:47:57,623] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:48:41,429] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24708096943556548
Fold 2 IBS: 0.2319847894382899
Fold 3 IBS: 0.22892152217671352
Fold 4 IBS: 0.24189505261981767
Fold 5 IBS: 0.22923205149412185
[I 2024-04-16 10:49:25,797] Trial 21 finished with value: 0.2358228770329017 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24653080707150826
Fold 2 IBS: 0.2308163540145221
Fold 3 IBS: 0.22876353753116432

Fold 4 IBS: 0.24123069912531167
Fold 5 IBS: 0.2287876678084262
[I 2024-04-16 10:50:14,835] Trial 22 finished with value: 0.23522581311018653 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-16 10:50:55,446] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:51:23,701] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:51:47,652] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:52:15,673] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:52:19,751] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:52:28,001] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:53:01,010] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:53:47,618] Trial 30 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24669271761943912
Fold 2 IBS: 0.23161158748658048
Fold 3 IBS: 0.22885749682655868
Fold 4 IBS: 0.2415375526987621
Fold 5 IBS: 0.22900015372798382
[I 2024-04-16 10:54:32,392] Trial 31 finished with value: 0.23553990167186484 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.2348823008943001.
Fold 1 IBS: 0.24564563860681737
Fold 2 IBS: 0.23004838667076483
Fold 3 IBS: 0.22843041081634244
Fold 4 IBS: 0.2405279086192378
Fold 5 IBS: 0.2284166708982888
[I 2024-04-16 10:55:16,078] Trial 32 finished with value: 0.23461380312229024 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115

Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:55:39,651] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 10:56:14,418] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:56:22,664] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 10:56:53,444] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 10:56:55,754] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 10:57:04,257] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:57:29,341] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 10:57:49,903] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 32 with value: 0.23461380312229024.
Fold 1 IBS: 0.24535392898444236
Fold 2 IBS: 0.22983855213430665
Fold 3 IBS: 0.22828579601330518
Fold 4 IBS: 0.2404818739619477
Fold 5 IBS: 0.22815595768125344
[I 2024-04-16 10:58:33,646] Trial 41 finished with value: 0.2344232217550511 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.2456246738690068
Fold 2 IBS: 0.2302022472275506
Fold 3 IBS: 0.2282651834167205
Fold 4 IBS: 0.24065825417068978
Fold 5 IBS: 0.22815367578346116
[I 2024-04-16 10:59:18,102] Trial 42 finished with value: 0.23458080689348576 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:00:06,517] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711

Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:00:47,839] Trial 44 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:01:02,191] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24668148640874393
Fold 2 IBS: 0.2314434495527833
Fold 3 IBS: 0.22880381191005433
Fold 4 IBS: 0.24152630299234565
Fold 5 IBS: 0.22899941338094207
[I 2024-04-16 11:01:44,829] Trial 46 finished with value: 0.23549089284897384 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:02:00,206] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:02:00,429] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:02:12,785] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:02:34,217] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24633004233906244
Fold 2 IBS: 0.2304844263963218
Fold 3 IBS: 0.2281276350946126
Fold 4 IBS: 0.24093009833688858
Fold 5 IBS: 0.22868087406207918
[I 2024-04-16 11:03:19,208] Trial 51 finished with value: 0.23491061524579293 and parameters: {'subsample': 0.7654204482217829, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.16919816074383062, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288631843664816, 'min_weight_fraction_leaf': 0.1689933524541079, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0415032179614574e-06, 'validation_fraction': 0.8197275960031745, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24685163330579102
Fold 2 IBS: 0.2313700656904065
Fold 3 IBS: 0.22859930126500913
Fold 4 IBS: 0.24155421543928507
Fold 5 IBS: 0.22911724231176442
[I 2024-04-16 11:03:56,557] Trial 52 finished with value: 0.23549849160245123 and parameters: {'subsample': 0.5053435062182351, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.036600491313384984, 'min_weight_fraction_leaf': 0.17248176220266245, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6630249663545005e-06, 'validation_fraction': 0.7333914400675312, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:04:41,215] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4631663309031124, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.15315671922192206, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.19064788811176675, 'max_features': 'sqrt', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:04:52,668] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9017461575502412, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.8266353856620614, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.09319645554340197, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01937053717718396, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:05:28,411] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.20419816136861105, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 1.5125790196698774, 'min_weight_fraction_leaf': 0.21953014805517473, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.9659902853562541, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:05:56,796] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2887765610954624, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23996644019536584, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.1313980673113705, 'max_features': 'auto', 'min_impurity_decrease': 4.350989437370722e-07, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:06:23,361] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6446884806787394, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5891903890315894, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.20021426582615917, 'max_features': 1, 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.8789871257745913, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 1}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:06:54,661] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9579507989353487, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.37031334062735055, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.2892805623291713, 'max_features': 'auto', 'min_impurity_decrease': 1.1543063953853995e-06, 'validation_fraction': 0.8234456145260549, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:07:22,460] Trial 59 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7291830079861774, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.3259416667709019, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.15797670971031227, 'max_features': 0.1, 'min_impurity_decrease': 2.556545341406747e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:08:08,703] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8610396134059503, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.10121382681282606, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6172084806681395e-06, 'validation_fraction': 0.7207277422863438, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24669558822573143
Fold 2 IBS: 0.23151016481358747
Fold 3 IBS: 0.22881669842500896
Fold 4 IBS: 0.24153533977106217
Fold 5 IBS: 0.22900436491929427
[I 2024-04-16 11:08:49,507] Trial 61 finished with value: 0.23551243123093685 and parameters: {'subsample': 0.793547371538957, 'learning_rate': 0.007879497950871669, 'dropout_rate': 0.1821518797890488, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.15642403295274038, 'max_features': 'sqrt', 'min_impurity_decrease': 9.882732394296688e-07, 'validation_fraction': 0.8276127057468522, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:09:29,128] Trial 62 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7797256328740491, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.13598930179576962, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.30303680983206904, 'min_weight_fraction_leaf': 0.1446235360050935, 'max_features': 'sqrt', 'min_impurity_decrease': 1.4865063577465509e-06, 'validation_fraction': 0.8523008424522974, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 3}. Best is trial 41 with value: 0.2344232217550511.
Fold 1 IBS: 0.24552406291052056
Fold 2 IBS: 0.2289109052994622
Fold 3 IBS: 0.22719845183134446
Fold 4 IBS: 0.24011204981163545
Fold 5 IBS: 0.22822320614570227
[I 2024-04-16 11:10:13,861] Trial 63 finished with value: 0.233993735199733 and parameters: {'subsample': 0.692943712947337, 'learning_rate': 0.018451257515222523, 'dropout_rate': 0.17342319762993127, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.018273771249527872, 'min_weight_fraction_leaf': 0.22065906606210625, 'max_features': 'sqrt', 'min_impurity_decrease': 4.701162926978375e-07, 'validation_fraction': 0.9637568180927849, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 63 with value: 0.233993735199733.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:10:52,661] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5929610408366162, 'learning_rate': 0.018936131124414023, 'dropout_rate': 0.2752721072737339, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.21641604442433082, 'max_features': 'log2', 'min_impurity_decrease': 5.301233747286273e-07, 'validation_fraction': 0.9558565998681479, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 63 with value: 0.233993735199733.
Fold 1 IBS: 0.2460070710741313
Fold 2 IBS: 0.22987095135107546
Fold 3 IBS: 0.22767170109207524
Fold 4 IBS: 0.24065307457799004
Fold 5 IBS: 0.22841183289827535
[I 2024-04-16 11:11:26,256] Trial 65 finished with value: 0.23452292619870949 and parameters: {'subsample': 0.6875174527450749, 'learning_rate': 0.012023060911592005, 'dropout_rate': 0.22795240768926875, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.002725697901156024, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'sqrt', 'min_impurity_decrease': 3.55046666349273e-07, 'validation_fraction': 0.97604137777707, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 63 with value: 0.233993735199733.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:11:51,428] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5392724474754766, 'learning_rate': 0.01461816521127875, 'dropout_rate': 0.22076051954616932, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.8099144041738244, 'min_weight_fraction_leaf': 0.03518122515344503, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1843050264198749e-07, 'validation_fraction': 0.9678192460592685, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 63 with value: 0.233993735199733.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:12:26,218] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.680855021230625, 'learning_rate': 0.004919883070534993, 'dropout_rate': 0.17168408254323692, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 1.1816384768705075, 'min_weight_fraction_leaf': 0.34044765865690435, 'max_features': 'sqrt', 'min_impurity_decrease': 3.64223716991965e-07, 'validation_fraction': 0.8999244727163287, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 63 with value: 0.233993735199733.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:13:08,377] Trial 68 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.631241891272345, 'learning_rate': 0.02020874707209061, 'dropout_rate': 0.1336766605116729, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.41011501927208094, 'min_weight_fraction_leaf': 0.24647880871939204, 'max_features': 'sqrt', 'min_impurity_decrease': 6.322991940675055e-05, 'validation_fraction': 0.9998887733080241, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 63 with value: 0.233993735199733.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:13:44,289] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7135254180093732, 'learning_rate': 0.012248299332324651, 'dropout_rate': 0.19754284273790385, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 8.536647141347391, 'min_weight_fraction_leaf': 0.06312724514848703, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7045057168188712e-07, 'validation_fraction': 0.8826997574671581, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 12}. Best is trial 63 with value: 0.233993735199733.
Fold 1 IBS: 0.24437067123719605
Fold 2 IBS: 0.22666564772605885
Fold 3 IBS: 0.2260709206071709
Fold 4 IBS: 0.23876141184323077
Fold 5 IBS: 0.22692945951686894
[I 2024-04-16 11:14:01,722] Trial 70 finished with value: 0.23255962218610512 and parameters: {'subsample': 0.6697553991712434, 'learning_rate': 0.04108545825236161, 'dropout_rate': 0.157870754346634, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 0.01008607715535667, 'min_weight_fraction_leaf': 0.36010549235644373, 'max_features': 'sqrt', 'min_impurity_decrease': 6.020485734459976e-07, 'validation_fraction': 0.9226664131821254, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 17}. Best is trial 70 with value: 0.23255962218610512.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:14:19,872] Trial 71 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6693819637756059, 'learning_rate': 0.05614284288525828, 'dropout_rate': 0.15702034457154107, 'n_estimators': 296, 'criterion': 'squared_error', 'ccp_alpha': 0.3433049873026723, 'min_weight_fraction_leaf': 0.40287687493722335, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2517278890323607e-07, 'validation_fraction': 0.923069188536789, 'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 9, 'max_depth': 18}. Best is trial 70 with value: 0.23255962218610512.
Fold 1 IBS: 0.2420954296893181
Fold 2 IBS: 0.2243810304675359
Fold 3 IBS: 0.22509871000730242
Fold 4 IBS: 0.23594052725397213
Fold 5 IBS: 0.22548144846248927
[I 2024-04-16 11:14:32,036] Trial 72 finished with value: 0.23059942917612353 and parameters: {'subsample': 0.579108878367126, 'learning_rate': 0.04131861156773751, 'dropout_rate': 0.23378840152554475, 'n_estimators': 253, 'criterion': 'squared_error', 'ccp_alpha': 0.004831107387468772, 'min_weight_fraction_leaf': 0.0015800417965165306, 'max_features': 'sqrt', 'min_impurity_decrease': 6.579953359019444e-07, 'validation_fraction': 0.9731455730491394, 'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:14:38,234] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5738428655793422, 'learning_rate': 0.0455181825324083, 'dropout_rate': 0.2343997299957806, 'n_estimators': 178, 'criterion': 'squared_error', 'ccp_alpha': 0.7340527434897883, 'min_weight_fraction_leaf': 0.0067953600457776875, 'max_features': 'sqrt', 'min_impurity_decrease': 6.698254390131449e-07, 'validation_fraction': 0.975393435114509, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 15}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:14:48,792] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6025026099765938, 'learning_rate': 0.032958214117911146, 'dropout_rate': 0.2869951320799577, 'n_estimators': 246, 'criterion': 'squared_error', 'ccp_alpha': 0.32446200678005266, 'min_weight_fraction_leaf': 0.4824501432585142, 'max_features': 'sqrt', 'min_impurity_decrease': 5.374331420183998e-07, 'validation_fraction': 0.9174828675502741, 'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 10, 'max_depth': 17}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:14:56,449] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.43027879849634443, 'learning_rate': 0.042720745162224044, 'dropout_rate': 0.3174641433502454, 'n_estimators': 211, 'criterion': 'squared_error', 'ccp_alpha': 0.9213193543014053, 'min_weight_fraction_leaf': 0.0019249398442275649, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0309115243736615e-07, 'validation_fraction': 0.937249294878607, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 19}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:15:10,036] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6140877311074591, 'learning_rate': 0.03803924745341146, 'dropout_rate': 0.26307849780329984, 'n_estimators': 269, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.3602762183936709, 'max_features': None, 'min_impurity_decrease': 1.493073490618048e-06, 'validation_fraction': 0.9733077860213678, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 16}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113

Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:15:13,698] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5357913465602108, 'learning_rate': 0.052009701795490706, 'dropout_rate': 0.19884799526452568, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.5891837005828349, 'min_weight_fraction_leaf': 0.02046465024104037, 'max_features': 1, 'min_impurity_decrease': 0.00801697775600995, 'validation_fraction': 0.8634632458479912, 'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 13}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:15:38,878] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9721672658830589, 'learning_rate': 0.0869328686638194, 'dropout_rate': 0.13115268850819523, 'n_estimators': 358, 'criterion': 'squared_error', 'ccp_alpha': 1.2957499806931485, 'min_weight_fraction_leaf': 0.3223892525342744, 'max_features': 'auto', 'min_impurity_decrease': 3.4628231080532276e-06, 'validation_fraction': 0.9088623912019655, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24642362587533867
Fold 2 IBS: 0.23101649062304183
Fold 3 IBS: 0.2285503071822295
Fold 4 IBS: 0.24139066053429295
Fold 5 IBS: 0.2289800599383448
[I 2024-04-16 11:15:53,817] Trial 79 finished with value: 0.23527222883064952 and parameters: {'subsample': 0.6598290039911562, 'learning_rate': 0.02377615162596504, 'dropout_rate': 0.23058735613266046, 'n_estimators': 286, 'criterion': 'squared_error', 'ccp_alpha': 0.006745375901080217, 'min_weight_fraction_leaf': 0.05181017186216383, 'max_features': 0.1, 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.7948571536797971, 'min_samples_split': 4, 'max_leaf_nodes': 14, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:16:09,930] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.03979776978619685, 'dropout_rate': 0.4097359359491849, 'n_estimators': 326, 'criterion': 'friedman_mse', 'ccp_alpha': 1.6825589365684388, 'min_weight_fraction_leaf': 0.2650334083023682, 'max_features': 'auto', 'min_impurity_decrease': 6.791944972082052e-06, 'validation_fraction': 0.9847675906151274, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 10}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:16:21,341] Trial 81 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7389045351693405, 'learning_rate': 0.015626838789191796, 'dropout_rate': 0.16758085244194437, 'n_estimators': 237, 'criterion': 'squared_error', 'ccp_alpha': 0.22752433432808897, 'min_weight_fraction_leaf': 0.42835099407898813, 'max_features': 'sqrt', 'min_impurity_decrease': 4.4684913792581215e-07, 'validation_fraction': 0.9439880537153739, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 16}. Best is trial 72 with value: 0.23059942917612353.
Fold 1 IBS: 0.24038375155672023
Fold 2 IBS: 0.21845623705977044
Fold 3 IBS: 0.2212320543008934
Fold 4 IBS: 0.23452763583972458
Fold 5 IBS: 0.2240725936071583
[I 2024-04-16 11:16:55,058] Trial 82 finished with value: 0.2277344544728534 and parameters: {'subsample': 0.6994793948584171, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.19156645482498222, 'n_estimators': 426, 'criterion': 'squared_error', 'ccp_alpha': 0.0177990205062633, 'min_weight_fraction_leaf': 0.08269791710039148, 'max_features': 'sqrt', 'min_impurity_decrease': 2.601503817654743e-07, 'validation_fraction': 0.6514317760469892, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:17:28,434] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6984533764119176, 'learning_rate': 0.061609893335421564, 'dropout_rate': 0.22002420204181877, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 0.6276545651340607, 'min_weight_fraction_leaf': 0.018522031931455765, 'max_features': 'sqrt', 'min_impurity_decrease': 2.9508041982243194e-07, 'validation_fraction': 0.633183021479895, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:17:57,992] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.625606721711451, 'learning_rate': 0.07168209331093675, 'dropout_rate': 0.19038786257865645, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 0.2875499855787776, 'min_weight_fraction_leaf': 0.07898036541687342, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5420519529397836e-07, 'validation_fraction': 0.760676986365436, 'min_samples_split': 3, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 15}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:18:24,330] Trial 85 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5718194253054419, 'learning_rate': 0.06843718884972436, 'dropout_rate': 0.26114316244435193, 'n_estimators': 385, 'criterion': 'squared_error', 'ccp_alpha': 0.9632022984619553, 'min_weight_fraction_leaf': 0.02969245414036512, 'max_features': 'auto', 'min_impurity_decrease': 2.429626863306918e-07, 'validation_fraction': 0.5319085204965728, 'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:18:56,763] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6949637154561719, 'learning_rate': 0.02824779029829077, 'dropout_rate': 0.12136420647833546, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.25472128048298465, 'min_weight_fraction_leaf': 0.2958841434615385, 'max_features': 'log2', 'min_impurity_decrease': 7.964322075883693e-07, 'validation_fraction': 0.6038098369494546, 'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 2}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:19:38,596] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9332739730674762, 'learning_rate': 0.05903368501201102, 'dropout_rate': 0.15122446567470643, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.5897918163618449, 'min_weight_fraction_leaf': 0.1061352085740554, 'max_features': 'sqrt', 'min_impurity_decrease': 1.6480660615557993e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118

Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:20:11,875] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.49209825028823895, 'learning_rate': 0.010473050195075363, 'dropout_rate': 0.20588321060682593, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 1.099942037302291, 'min_weight_fraction_leaf': 0.08127692641673222, 'max_features': 'auto', 'min_impurity_decrease': 1.5480811100354597e-07, 'validation_fraction': 0.696357383667876, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 1}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:20:32,932] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.995129754492818, 'learning_rate': 0.04745413618139034, 'dropout_rate': 0.35768717188704796, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.048065230860923444, 'max_features': 'sqrt', 'min_impurity_decrease': 3.9902015374155136e-07, 'validation_fraction': 0.8820285925774979, 'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 9}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:20:39,730] Trial 90 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5857034796416958, 'learning_rate': 0.0030759059571325367, 'dropout_rate': 0.25271587979533394, 'n_estimators': 191, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.3532868404531968, 'max_features': None, 'min_impurity_decrease': 5.887267273557201e-07, 'validation_fraction': 0.568217699248245, 'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24650327066651392
Fold 2 IBS: 0.2307939769479941
Fold 3 IBS: 0.22831986150961806
Fold 4 IBS: 0.24120301417586165
Fold 5 IBS: 0.2288634343471823
[I 2024-04-16 11:21:18,503] Trial 91 finished with value: 0.235136711529434 and parameters: {'subsample': 0.6406664021456252, 'learning_rate': 0.0059969295883687, 'dropout_rate': 0.17611045882869727, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.037809648957626285, 'min_weight_fraction_leaf': 0.11421843022011445, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1486665111831928e-06, 'validation_fraction': 0.9447350925339324, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 2}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:22:02,954] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7450821862179925, 'learning_rate': 0.07241575153943186, 'dropout_rate': 0.15587603019786975, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.2713289375742298, 'min_weight_fraction_leaf': 0.23052518506371966, 'max_features': 'sqrt', 'min_impurity_decrease': 8.846372055663885e-07, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:22:42,551] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6621621633344669, 'learning_rate': 0.08372015018698861, 'dropout_rate': 0.19288488144414834, 'n_estimators': 459, 'criterion': 'squared_error', 'ccp_alpha': 0.5221970929592914, 'min_weight_fraction_leaf': 0.1973744153749018, 'max_features': 'sqrt', 'min_impurity_decrease': 2.2931193284382314e-07, 'validation_fraction': 0.973784235683371, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24677049812409452
Fold 2 IBS: 0.23125770984579413
Fold 3 IBS: 0.2285524285871875
Fold 4 IBS: 0.2415227978168385
Fold 5 IBS: 0.2291117574627904
[I 2024-04-16 11:23:29,920] Trial 94 finished with value: 0.235443038367341 and parameters: {'subsample': 0.7628405856529468, 'learning_rate': 0.003352557680621047, 'dropout_rate': 0.11720825379394845, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 0.05761938784031302, 'min_weight_fraction_leaf': 0.1279407207657041, 'max_features': 'sqrt', 'min_impurity_decrease': 3.640599784132377e-07, 'validation_fraction': 0.8077177487804612, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 1}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:24:03,841] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9127812766629875, 'learning_rate': 0.01088755550907775, 'dropout_rate': 0.2752833630371681, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.7726089608371894, 'min_weight_fraction_leaf': 0.22378483013093067, 'max_features': 'auto', 'min_impurity_decrease': 5.265681476345367e-07, 'validation_fraction': 0.847482375824143, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-16 11:24:18,410] Trial 96 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7189342786044234, 'learning_rate': 0.04248371150931579, 'dropout_rate': 0.2198021375483558, 'n_estimators': 259, 'criterion': 'squared_error', 'ccp_alpha': 0.4982761124984416, 'min_weight_fraction_leaf': 0.17600968599317796, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8821479081427815e-06, 'validation_fraction': 0.89259116750544, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 2}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:24:58,639] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.007989754361911528, 'dropout_rate': 0.31117214367290413, 'n_estimators': 490, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22821046176692686, 'min_weight_fraction_leaf': 0.37787194602572943, 'max_features': 'auto', 'min_impurity_decrease': 0.0006732483133592823, 'validation_fraction': 0.9285057607938579, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 4}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-16 11:25:09,121] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9703344200287781, 'learning_rate': 0.016888510710096588, 'dropout_rate': 0.24572083012233178, 'n_estimators': 224, 'criterion': 'squared_error', 'ccp_alpha': 0.8399813894193418, 'min_weight_fraction_leaf': 0.24844496066162733, 'max_features': 1, 'min_impurity_decrease': 1.2452849557330686e-06, 'validation_fraction': 0.9551493879195305, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 82 with value: 0.2277344544728534.
Fold 1 IBS: 0.24225560086897543
Fold 2 IBS: 0.22125723167461134
Fold 3 IBS: 0.22292641479174868
Fold 4 IBS: 0.23658318621591878

Fold 5 IBS: 0.22576583126917327
[I 2024-04-16 11:25:49,605] Trial 99 finished with value: 0.2297576529640855 and parameters: {'subsample': 0.8869168213912387, 'learning_rate': 0.03566645000969104, 'dropout_rate': 0.10216550214025771, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.004367203675973822, 'min_weight_fraction_leaf': 0.1402070137569511, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00015837847703956763, 'validation_fraction': 0.9870731812554687, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 82 with value: 0.2277344544728534.


* Best trial for IBS:
 FrozenTrial(number=82, state=TrialState.COMPLETE, values=[0.2277344544728534], datetime_start=datetime.datetime(2024, 4, 16, 11, 16, 21, 347118), datetime_complete=datetime.datetime(2024, 4, 16, 11, 16, 55, 57565), params={'subsample': 0.6994793948584171, 'learning_rate': 0.06401898097796113, 'dropout_rate': 0.19156645482498222, 'n_estimators': 426, 'criterion': 'squared_error', 'ccp_alpha': 0.0177990205062633, 'min_weight_fraction_leaf': 0.08269791710039148, 'max_features': 'sqrt', 'min_impurity_decrease': 2.601503817654743e-07, 'validation_fraction': 0.6514317760469892, 'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=82, value=None)


* Best Score for IBS:
 0.2277344544728534

In [129]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [130]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.714
train_ibs:  0.228

#### Test

In [131]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [132]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.05874457198222169,
                                 dropout_rate=0.8142690261508861,
                                 learning_rate=0.02998154803834563, max_depth=4,
                                 max_features=0.1, max_leaf_nodes=5,
                                 min_impurity_decrease=4.899193303970509e-05,
                                 min_samples_leaf=13, min_samples_split=12,
                                 min_weight_fraction_leaf=0.3150248435971541,
                                 n_estimators=161, random_state=123,
                                 subsample=0.5167163717577359,
                                 validation_fraction=0.8336552353722929)

C-index score: 0.544

GradientBoostingSurvivalAnalysis(ccp_alpha=0.0177990205062633,
                                 criterion='squared_error',
                                 dropout_rate=0.19156645482498222,
                                 learning_rate=0.06401898097796113, max_depth=2,
                                 max_features='sqrt', max_leaf_nodes=17,
                                 min_impurity_decrease=2.601503817654743e-07,
                                 min_samples_leaf=6, min_samples_split=3,
                                 min_weight_fraction_leaf=0.08269791710039148,
                                 n_estimators=426, random_state=123,
                                 subsample=0.6994793948584171,
                                 validation_fraction=0.6514317760469892)

IBS: 0.229

In [133]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [134]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [135]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Min Max Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = MinMaxScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-16 11:25:57,290] A new study created in memory with name: no-name-54480853-85a6-4544-8580-40d03b6a55ae

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:25:57,895] Trial 0 finished with value: 0.6184658291608083 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6184658291608083.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6159695817490495
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:02,711] Trial 1 finished with value: 0.6192410229592579 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 1 with value: 0.6192410229592579.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:26:03,673] Trial 2 finished with value: 0.6274050260636042 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6274050260636042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:05,096] Trial 3 finished with value: 0.6263655688396808 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 2 with value: 0.6274050260636042.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:26:07,351] Trial 4 finished with value: 0.6326851918986134 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6326851918986134.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:10,158] Trial 5 finished with value: 0.6179919330797983 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6326851918986134.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6121673003802282
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:11,273] Trial 6 finished with value: 0.617705372887044 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6326851918986134.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:11,518] Trial 7 finished with value: 0.6248230373415977 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6326851918986134.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6085106382978723
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 11:26:12,907] Trial 8 finished with value: 0.6280675695124202 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6326851918986134.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:16,844] Trial 9 finished with value: 0.6238518909064169 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6326851918986134.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 11:26:19,334] Trial 10 finished with value: 0.6347201048635227 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6347201048635227.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:26:22,234] Trial 11 finished with value: 0.6378599697703627 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6378599697703627.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:26:25,022] Trial 12 finished with value: 0.6386278582998872 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.6386278582998872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:28,409] Trial 13 finished with value: 0.6222533730049442 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.6386278582998872.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 11:26:31,094] Trial 14 finished with value: 0.6377515945956314 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.6386278582998872.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:26:33,690] Trial 15 finished with value: 0.6360894472177623 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.6386278582998872.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:26:38,363] Trial 16 finished with value: 0.639674620792736 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 16 with value: 0.639674620792736.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:26:43,118] Trial 17 finished with value: 0.6335289504594753 and parameters: {'subsample': 0.27245577283447836, 'dropout_rate': 0.22654987460299786, 'n_estimators': 445, 'learning_rate': 0.0861429080785094}. Best is trial 16 with value: 0.639674620792736.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:26:47,320] Trial 18 finished with value: 0.6293573574406931 and parameters: {'subsample': 0.346332817286849, 'dropout_rate': 0.3438278728179395, 'n_estimators': 430, 'learning_rate': 0.08036408097329895}. Best is trial 16 with value: 0.639674620792736.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:26:50,747] Trial 19 finished with value: 0.6363246165543702 and parameters: {'subsample': 0.19720963658850754, 'dropout_rate': 0.6165615625273371, 'n_estimators': 400, 'learning_rate': 0.09107738339755381}. Best is trial 16 with value: 0.639674620792736.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.625531914893617
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:26:52,354] Trial 20 finished with value: 0.6315697376565172 and parameters: {'subsample': 0.38161734041406226, 'dropout_rate': 0.7906239277194107, 'n_estimators': 258, 'learning_rate': 0.06551866052750378}. Best is trial 16 with value: 0.639674620792736.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:55,211] Trial 21 finished with value: 0.6403155452909977 and parameters: {'subsample': 0.12432193929457189, 'dropout_rate': 0.12395834975058428, 'n_estimators': 318, 'learning_rate': 0.0929934357366757}. Best is trial 21 with value: 0.6403155452909977.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:26:59,235] Trial 22 finished with value: 0.6346546971819685 and parameters: {'subsample': 0.18730237115878284, 'dropout_rate': 0.17478832195623056, 'n_estimators': 404, 'learning_rate': 0.09972105130772678}. Best is trial 21 with value: 0.6403155452909977.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6223175965665236
[I 2024-04-16 11:27:01,669] Trial 23 finished with value: 0.6414602206087945 and parameters: {'subsample': 0.2183253598602433, 'dropout_rate': 0.1000154447433527, 'n_estimators': 290, 'learning_rate': 0.08013909093253938}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:27:03,501] Trial 24 finished with value: 0.634546491876623 and parameters: {'subsample': 0.23665112702499613, 'dropout_rate': 0.30380438866089066, 'n_estimators': 252, 'learning_rate': 0.07960482781211804}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.6045627376425855
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:27:07,471] Trial 25 finished with value: 0.6314353413694945 and parameters: {'subsample': 0.4041383335350801, 'dropout_rate': 0.1858291511129791, 'n_estimators': 401, 'learning_rate': 0.07896102698776229}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 11:27:08,318] Trial 26 finished with value: 0.6335216451905501 and parameters: {'subsample': 0.3146459875550977, 'dropout_rate': 0.18299625576468617, 'n_estimators': 142, 'learning_rate': 0.09027105769072469}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.3829787234042553
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:27:08,432] Trial 27 finished with value: 0.577206366572485 and parameters: {'subsample': 0.43278806375775025, 'dropout_rate': 0.9861686560685959, 'n_estimators': 1, 'learning_rate': 0.08220961290449552}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 11:27:11,412] Trial 28 finished with value: 0.6363714353793933 and parameters: {'subsample': 0.19308358356170718, 'dropout_rate': 0.3031717588663335, 'n_estimators': 345, 'learning_rate': 0.07332877553053706}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:27:12,923] Trial 29 finished with value: 0.623113053583207 and parameters: {'subsample': 0.5790219222156496, 'dropout_rate': 0.41296888375675844, 'n_estimators': 231, 'learning_rate': 0.06046208382653473}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:27:13,392] Trial 30 finished with value: 0.6199720041836514 and parameters: {'subsample': 0.8739790489864521, 'dropout_rate': 0.3033871261891664, 'n_estimators': 93, 'learning_rate': 0.044111725565593694}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:27:15,795] Trial 31 finished with value: 0.6363027007475945 and parameters: {'subsample': 0.12121460651074775, 'dropout_rate': 0.10343896418756497, 'n_estimators': 290, 'learning_rate': 0.09343762067404672}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:27:18,135] Trial 32 finished with value: 0.6378996531958471 and parameters: {'subsample': 0.15624765224504153, 'dropout_rate': 0.1503333561953488, 'n_estimators': 287, 'learning_rate': 0.09428352208615702}. Best is trial 23 with value: 0.6414602206087945.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:27:21,163] Trial 33 finished with value: 0.6415435228958922 and parameters: {'subsample': 0.2328915405558403, 'dropout_rate': 0.1006314006722607, 'n_estimators': 335, 'learning_rate': 0.0846963458038824}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:27:26,579] Trial 34 finished with value: 0.6333550406163546 and parameters: {'subsample': 0.3120359565345522, 'dropout_rate': 0.222899205316046, 'n_estimators': 476, 'learning_rate': 0.0702042664736413}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 11:27:30,031] Trial 35 finished with value: 0.6353683346307096 and parameters: {'subsample': 0.23812055437349924, 'dropout_rate': 0.16122865923898638, 'n_estimators': 340, 'learning_rate': 0.08445093577406038}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:27:33,894] Trial 36 finished with value: 0.635343304625627 and parameters: {'subsample': 0.23630105186741818, 'dropout_rate': 0.4552373859008323, 'n_estimators': 375, 'learning_rate': 0.07547222925204859}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:27:36,095] Trial 37 finished with value: 0.6223525973094428 and parameters: {'subsample': 0.581022601642927, 'dropout_rate': 0.20084479858415719, 'n_estimators': 273, 'learning_rate': 0.06427202847957798}. Best is trial 33 with value: 0.6415435228958922.

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:27:40,828] Trial 38 finished with value: 0.6205745996185306 and parameters: {'subsample': 0.6555428090282759, 'dropout_rate': 0.15265508330268462, 'n_estimators': 439, 'learning_rate': 0.05809962418833657}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:27:44,300] Trial 39 finished with value: 0.6337174708404466 and parameters: {'subsample': 0.3117059866773502, 'dropout_rate': 0.5217112798506811, 'n_estimators': 388, 'learning_rate': 0.06892741183938003}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:27:47,111] Trial 40 finished with value: 0.6323845719978998 and parameters: {'subsample': 0.43581969238553375, 'dropout_rate': 0.280971539366882, 'n_estimators': 329, 'learning_rate': 0.07638571808031254}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 11:27:48,629] Trial 41 finished with value: 0.633944911065073 and parameters: {'subsample': 0.1384707246581923, 'dropout_rate': 0.10193581373070416, 'n_estimators': 209, 'learning_rate': 0.09492674417021844}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:27:50,388] Trial 42 finished with value: 0.633651893289506 and parameters: {'subsample': 0.19837080884853528, 'dropout_rate': 0.13868109075147372, 'n_estimators': 231, 'learning_rate': 0.08682791376241338}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:27:53,133] Trial 43 finished with value: 0.6363420873168575 and parameters: {'subsample': 0.15004552831309048, 'dropout_rate': 0.20038585899742659, 'n_estimators': 318, 'learning_rate': 0.09473929182796301}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5708154506437768
[I 2024-04-16 11:27:55,472] Trial 44 finished with value: 0.628682469966221 and parameters: {'subsample': 0.10259577048184985, 'dropout_rate': 0.13954790576955645, 'n_estimators': 280, 'learning_rate': 0.08269313368936562}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6223175965665236
[I 2024-04-16 11:27:58,080] Trial 45 finished with value: 0.6414749581334798 and parameters: {'subsample': 0.22688063994989277, 'dropout_rate': 0.10418684057414657, 'n_estimators': 304, 'learning_rate': 0.02274904980797578}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:28:03,685] Trial 46 finished with value: 0.6363787406483186 and parameters: {'subsample': 0.22330339589508583, 'dropout_rate': 0.2544033257448694, 'n_estimators': 495, 'learning_rate': 0.024992652172925307}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:28:04,786] Trial 47 finished with value: 0.6293789763912475 and parameters: {'subsample': 0.2838126384021847, 'dropout_rate': 0.37363437486837914, 'n_estimators': 179, 'learning_rate': 0.008209618821055878}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6553191489361702
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:28:08,610] Trial 48 finished with value: 0.6368862599667662 and parameters: {'subsample': 0.33164309150212246, 'dropout_rate': 0.12650089355020094, 'n_estimators': 362, 'learning_rate': 0.04259556211366368}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:28:11,350] Trial 49 finished with value: 0.6394059552055251 and parameters: {'subsample': 0.1780327306754584, 'dropout_rate': 0.33487485864222355, 'n_estimators': 301, 'learning_rate': 0.02713079119975165}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:28:16,067] Trial 50 finished with value: 0.6319026928312385 and parameters: {'subsample': 0.2791221993694158, 'dropout_rate': 0.21417457740573387, 'n_estimators': 420, 'learning_rate': 0.05279862864270119}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:28:18,575] Trial 51 finished with value: 0.6387213689630984 and parameters: {'subsample': 0.1779176552405944, 'dropout_rate': 0.34423446209664954, 'n_estimators': 311, 'learning_rate': 0.016769783329425858}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:28:21,021] Trial 52 finished with value: 0.6347889664821563 and parameters: {'subsample': 0.2432553195167396, 'dropout_rate': 0.16580773341439545, 'n_estimators': 297, 'learning_rate': 0.031014346013351384}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 11:28:22,798] Trial 53 finished with value: 0.6363858760478573 and parameters: {'subsample': 0.1642075191378861, 'dropout_rate': 0.10192490757286515, 'n_estimators': 236, 'learning_rate': 0.015616184788445366}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:28:25,468] Trial 54 finished with value: 0.6395374912679112 and parameters: {'subsample': 0.2150708647705986, 'dropout_rate': 0.5839704698344542, 'n_estimators': 336, 'learning_rate': 0.0316002312907681}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.6180257510729614
[I 2024-04-16 11:28:28,042] Trial 55 finished with value: 0.6325187143112527 and parameters: {'subsample': 0.3610939462586782, 'dropout_rate': 0.6209235350632709, 'n_estimators': 339, 'learning_rate': 0.03497463705126907}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5779467680608364

Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 11:28:30,919] Trial 56 finished with value: 0.6387333732499819 and parameters: {'subsample': 0.21374627324326978, 'dropout_rate': 0.582295126135687, 'n_estimators': 359, 'learning_rate': 0.01967773745006787}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.6137339055793991
[I 2024-04-16 11:28:33,886] Trial 57 finished with value: 0.6386864274381239 and parameters: {'subsample': 0.2647612964733766, 'dropout_rate': 0.6651067628929089, 'n_estimators': 374, 'learning_rate': 0.0348183308643273}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:28:35,577] Trial 58 finished with value: 0.6353753430434135 and parameters: {'subsample': 0.14512499563683898, 'dropout_rate': 0.7243335252121512, 'n_estimators': 260, 'learning_rate': 0.010065355449169564}. Best is trial 33 with value: 0.6415435228958922.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:28:39,507] Trial 59 finished with value: 0.646483192019197 and parameters: {'subsample': 0.10200972368178224, 'dropout_rate': 0.5065802886056728, 'n_estimators': 417, 'learning_rate': 0.08860071779281121}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:28:43,452] Trial 60 finished with value: 0.6329306537156183 and parameters: {'subsample': 0.12832787269445792, 'dropout_rate': 0.8626001834456398, 'n_estimators': 463, 'learning_rate': 0.09016307484808038}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:28:47,314] Trial 61 finished with value: 0.6347378724822313 and parameters: {'subsample': 0.1975780150934986, 'dropout_rate': 0.48658517217378516, 'n_estimators': 408, 'learning_rate': 0.08723954982316946}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:28:51,693] Trial 62 finished with value: 0.6449622794716685 and parameters: {'subsample': 0.10705712643318503, 'dropout_rate': 0.5660100933434199, 'n_estimators': 454, 'learning_rate': 0.0971238840927248}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.6094420600858369
[I 2024-04-16 11:28:56,761] Trial 63 finished with value: 0.6374579654020097 and parameters: {'subsample': 0.11905434038519647, 'dropout_rate': 0.1332889304338894, 'n_estimators': 455, 'learning_rate': 0.09755379737466835}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:29:00,578] Trial 64 finished with value: 0.646483192019197 and parameters: {'subsample': 0.10219154727416663, 'dropout_rate': 0.5179684675639005, 'n_estimators': 416, 'learning_rate': 0.07839262467655704}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:29:05,297] Trial 65 finished with value: 0.6354005429178822 and parameters: {'subsample': 0.1564154683594502, 'dropout_rate': 0.5224077003300244, 'n_estimators': 473, 'learning_rate': 0.09158065066451133}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:29:09,790] Trial 66 finished with value: 0.6394710660308581 and parameters: {'subsample': 0.1014320210615958, 'dropout_rate': 0.4647799644657666, 'n_estimators': 421, 'learning_rate': 0.08002385116853233}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:29:13,543] Trial 67 finished with value: 0.6369941684158902 and parameters: {'subsample': 0.137919642133134, 'dropout_rate': 0.50695435425432, 'n_estimators': 385, 'learning_rate': 0.083572983462944}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 11:29:17,853] Trial 68 finished with value: 0.6424923902694045 and parameters: {'subsample': 0.10271105711603297, 'dropout_rate': 0.5710636293320419, 'n_estimators': 444, 'learning_rate': 0.07680071508088954}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6273764258555133
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:29:22,186] Trial 69 finished with value: 0.6199720041836514 and parameters: {'subsample': 0.8584661298748817, 'dropout_rate': 0.4350225049334703, 'n_estimators': 448, 'learning_rate': 0.07667266820422051}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:29:26,974] Trial 70 finished with value: 0.6339307243702788 and parameters: {'subsample': 0.1730294356390193, 'dropout_rate': 0.5957918070879165, 'n_estimators': 483, 'learning_rate': 0.07191737718926254}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:29:31,075] Trial 71 finished with value: 0.6400949436096887 and parameters: {'subsample': 0.10858054794494558, 'dropout_rate': 0.5724415312415936, 'n_estimators': 441, 'learning_rate': 0.08818319984809303}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5836909871244635
[I 2024-04-16 11:29:34,395] Trial 72 finished with value: 0.6351799412365734 and parameters: {'subsample': 0.13063842278118232, 'dropout_rate': 0.6596667689651377, 'n_estimators': 392, 'learning_rate': 0.06594985955162685}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:29:38,725] Trial 73 finished with value: 0.644284998498167 and parameters: {'subsample': 0.10319159570926917, 'dropout_rate': 0.6264600756019099, 'n_estimators': 462, 'learning_rate': 0.09194435483565748}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:29:42,493] Trial 74 finished with value: 0.646483192019197 and parameters: {'subsample': 0.10141309888609856, 'dropout_rate': 0.5475100797390481, 'n_estimators': 418, 'learning_rate': 0.08512312397435774}. Best is trial 59 with value: 0.646483192019197.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:29:46,511] Trial 75 finished with value: 0.6448716719156455 and parameters: {'subsample': 0.10152133747145038, 'dropout_rate': 0.556672684612476, 'n_estimators': 429, 'learning_rate': 0.09664277634599303}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:29:50,975] Trial 76 finished with value: 0.6450601922966166 and parameters: {'subsample': 0.10264815311012426, 'dropout_rate': 0.5507580879768375, 'n_estimators': 462, 'learning_rate': 0.09704609749180781}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:29:56,035] Trial 77 finished with value: 0.6460164742202774 and parameters: {'subsample': 0.10011117308581036, 'dropout_rate': 0.5429205894817576, 'n_estimators': 496, 'learning_rate': 0.09697340843487975}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:30:01,110] Trial 78 finished with value: 0.6330285665405665 and parameters: {'subsample': 0.15429148688953473, 'dropout_rate': 0.5440467961496551, 'n_estimators': 496, 'learning_rate': 0.09763834532053876}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5741444866920152
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:30:05,567] Trial 79 finished with value: 0.6314856111994274 and parameters: {'subsample': 0.1364624299110566, 'dropout_rate': 0.6284646498845764, 'n_estimators': 472, 'learning_rate': 0.0925227738862361}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5703422053231939
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 11:30:10,459] Trial 80 finished with value: 0.6347890934689912 and parameters: {'subsample': 0.17635034141598963, 'dropout_rate': 0.544032602974961, 'n_estimators': 461, 'learning_rate': 0.09967963717320291}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:30:15,006] Trial 81 finished with value: 0.6379822347836673 and parameters: {'subsample': 0.10948348285568388, 'dropout_rate': 0.4968781112371564, 'n_estimators': 434, 'learning_rate': 0.08916739252971367}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:30:18,619] Trial 82 finished with value: 0.6440206080858583 and parameters: {'subsample': 0.10248515416900086, 'dropout_rate': 0.6398473119189143, 'n_estimators': 412, 'learning_rate': 0.09626074948226011}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:30:22,042] Trial 83 finished with value: 0.6361973556668862 and parameters: {'subsample': 0.13122171152398532, 'dropout_rate': 0.6971779486067715, 'n_estimators': 412, 'learning_rate': 0.09594062071010098}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:30:26,961] Trial 84 finished with value: 0.6337890228143308 and parameters: {'subsample': 0.15842378480039954, 'dropout_rate': 0.636901453981428, 'n_estimators': 486, 'learning_rate': 0.09736624665392664}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5931558935361216
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:30:30,875] Trial 85 finished with value: 0.6457227357454328 and parameters: {'subsample': 0.10226711963340798, 'dropout_rate': 0.5991924348188908, 'n_estimators': 430, 'learning_rate': 0.09291235317703}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:30:35,784] Trial 86 finished with value: 0.6378745803082133 and parameters: {'subsample': 0.18489910584264704, 'dropout_rate': 0.6000989004556734, 'n_estimators': 500, 'learning_rate': 0.09205181244937784}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:30:39,724] Trial 87 finished with value: 0.6376718732324479 and parameters: {'subsample': 0.12541056369807102, 'dropout_rate': 0.5293590884248103, 'n_estimators': 428, 'learning_rate': 0.08528482002127202}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:30:44,092] Trial 88 finished with value: 0.6361141803666234 and parameters: {'subsample': 0.15092697629379373, 'dropout_rate': 0.5589682146925672, 'n_estimators': 454, 'learning_rate': 0.0938142208403005}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.596958174904943
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:30:48,669] Trial 89 finished with value: 0.6306061504639315 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.47386638495680733, 'n_estimators': 469, 'learning_rate': 0.09994209740410823}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.6051502145922747
[I 2024-04-16 11:30:53,571] Trial 90 finished with value: 0.6363641301104681 and parameters: {'subsample': 0.19832049143223224, 'dropout_rate': 0.4160085389515077, 'n_estimators': 481, 'learning_rate': 0.09045626166085625}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.6008583690987125
[I 2024-04-16 11:30:57,263] Trial 91 finished with value: 0.6418116818071136 and parameters: {'subsample': 0.1167241970522331, 'dropout_rate': 0.6453270422514132, 'n_estimators': 423, 'learning_rate': 0.09619766417795927}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:31:00,845] Trial 92 finished with value: 0.6346980620699121 and parameters: {'subsample': 0.14031454131124688, 'dropout_rate': 0.610138868870326, 'n_estimators': 406, 'learning_rate': 0.0937920864851589}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:31:04,704] Trial 93 finished with value: 0.6449622794716685 and parameters: {'subsample': 0.10118717007921987, 'dropout_rate': 0.7096963041358434, 'n_estimators': 431, 'learning_rate': 0.08861410991889813}. Best is trial 59 with value: 0.646483192019197.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.5893536121673004
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:31:08,641] Trial 94 finished with value: 0.6449622794716685 and parameters: {'subsample': 0.10168548520659682, 'dropout_rate': 0.686310945288123, 'n_estimators': 431, 'learning_rate': 0.08222966153330008}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5817490494296578
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:31:11,713] Trial 95 finished with value: 0.6354368993931219 and parameters: {'subsample': 0.16703517719167424, 'dropout_rate': 0.7819681796271336, 'n_estimators': 394, 'learning_rate': 0.08230676245316516}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791
Fold 5 C-index: 0.592274678111588
[I 2024-04-16 11:31:15,341] Trial 96 finished with value: 0.6385229370622351 and parameters: {'subsample': 0.12552952937428993, 'dropout_rate': 0.7172227199066672, 'n_estimators': 432, 'learning_rate': 0.08744162743985517}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5879828326180258
[I 2024-04-16 11:31:19,318] Trial 97 finished with value: 0.6354443316488821 and parameters: {'subsample': 0.14546921484619763, 'dropout_rate': 0.5590667388176285, 'n_estimators': 448, 'learning_rate': 0.0850639754460616}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.5779467680608364
Fold 5 C-index: 0.5965665236051502
[I 2024-04-16 11:31:22,541] Trial 98 finished with value: 0.6354589421867326 and parameters: {'subsample': 0.17061079769986723, 'dropout_rate': 0.6936070478827114, 'n_estimators': 415, 'learning_rate': 0.08961232965406875}. Best is trial 59 with value: 0.646483192019197.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.5855513307984791

[I 2024-04-16 11:31:25,693] A new study created in memory with name: no-name-6db10e0b-f050-4ad7-9a97-c88ed8c2fb2e

Fold 5 C-index: 0.5793991416309013
[I 2024-04-16 11:31:25,682] Trial 99 finished with value: 0.639156699712668 and parameters: {'subsample': 0.10061509123532142, 'dropout_rate': 0.5074785258766119, 'n_estimators': 381, 'learning_rate': 0.08219340776106977}. Best is trial 59 with value: 0.646483192019197.


* Best trial for C-index:
 FrozenTrial(number=59, state=TrialState.COMPLETE, values=[0.646483192019197], datetime_start=datetime.datetime(2024, 4, 16, 11, 28, 35, 583691), datetime_complete=datetime.datetime(2024, 4, 16, 11, 28, 39, 506497), params={'subsample': 0.10200972368178224, 'dropout_rate': 0.5065802886056728, 'n_estimators': 417, 'learning_rate': 0.08860071779281121}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=59, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10200972368178224, 'dropout_rate': 0.5065802886056728, 'n_estimators': 417, 'learning_rate': 0.08860071779281121}


* Best Score for C-index:
 0.646483192019197

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.25743063664610333
Fold 2 IBS: 0.1870598303035001
Fold 3 IBS: 0.23066689078693747
Fold 4 IBS: 0.23525450910152323
Fold 5 IBS: 0.22217354244464194
[I 2024-04-16 11:31:26,301] Trial 0 finished with value: 0.22651708185654124 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.3737646855274175
Fold 2 IBS: 0.16526672590116237
Fold 3 IBS: 0.2914187515159566
Fold 4 IBS: 0.3052831869523761
Fold 5 IBS: 0.30657822951178254
[I 2024-04-16 11:31:30,851] Trial 1 finished with value: 0.288462315881739 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.28929951046816776
Fold 2 IBS: 0.16522092748454437
Fold 3 IBS: 0.22605765378408388
Fold 4 IBS: 0.26323565016633904
Fold 5 IBS: 0.2320542559257309
[I 2024-04-16 11:31:31,738] Trial 2 finished with value: 0.2351735995657732 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.2989681210518655
Fold 2 IBS: 0.16272534679296155
Fold 3 IBS: 0.22889803995144994
Fold 4 IBS: 0.26892683316361454
Fold 5 IBS: 0.23684567449196767
[I 2024-04-16 11:31:32,963] Trial 3 finished with value: 0.23927280309037183 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.2981505439449266
Fold 2 IBS: 0.16910641881748387
Fold 3 IBS: 0.21544141511487444
Fold 4 IBS: 0.2793071313337293
Fold 5 IBS: 0.235325715294403
[I 2024-04-16 11:31:34,797] Trial 4 finished with value: 0.23946624490108345 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.3323279037150595
Fold 2 IBS: 0.1534354178131219
Fold 3 IBS: 0.2614336048429884
Fold 4 IBS: 0.2860460786008416
Fold 5 IBS: 0.2711023036063755
[I 2024-04-16 11:31:37,073] Trial 5 finished with value: 0.26086906171567736 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.24894755508266628
Fold 2 IBS: 0.20033694714548572
Fold 3 IBS: 0.22952771270088154
Fold 4 IBS: 0.23494727892952968
Fold 5 IBS: 0.22237048444737798
[I 2024-04-16 11:31:38,044] Trial 6 finished with value: 0.22722599566118826 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.2445972845598227
Fold 2 IBS: 0.2187486336871427
Fold 3 IBS: 0.2266108868574196
Fold 4 IBS: 0.24365805848771774
Fold 5 IBS: 0.22480015150699054
[I 2024-04-16 11:31:38,278] Trial 7 finished with value: 0.23168300301981865 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.26076173347211257
Fold 2 IBS: 0.18802182878478316
Fold 3 IBS: 0.22473341925537632
Fold 4 IBS: 0.2486051844290565
Fold 5 IBS: 0.22227522207991576
[I 2024-04-16 11:31:39,481] Trial 8 finished with value: 0.22887947760424887 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.3382081093389256
Fold 2 IBS: 0.15367195816727786
Fold 3 IBS: 0.24784841303481445
Fold 4 IBS: 0.3004836151220089
Fold 5 IBS: 0.2781245107923348
[I 2024-04-16 11:31:42,870] Trial 9 finished with value: 0.2636673212910723 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.24710671689969635
Fold 2 IBS: 0.23161435660541935
Fold 3 IBS: 0.22896099021176047
Fold 4 IBS: 0.24173739722053514
Fold 5 IBS: 0.22925595750859792
[I 2024-04-16 11:31:43,051] Trial 10 finished with value: 0.23573508368920182 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7165502912345604, 'n_estimators': 30, 'learning_rate': 0.0017980531969980576}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.24495824898147106
Fold 2 IBS: 0.21402052856294448
Fold 3 IBS: 0.2288502403265368
Fold 4 IBS: 0.23470551997346384
Fold 5 IBS: 0.22462445708235979
[I 2024-04-16 11:31:43,601] Trial 11 finished with value: 0.22943179898535515 and parameters: {'subsample': 0.8563264881207873, 'dropout_rate': 0.3306437349344059, 'n_estimators': 110, 'learning_rate': 0.020726317464293063}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.3559108274141316
Fold 2 IBS: 0.15707366183855756
Fold 3 IBS: 0.2764340156319726
Fold 4 IBS: 0.29988116388517094
Fold 5 IBS: 0.2934451068237095
[I 2024-04-16 11:31:45,701] Trial 12 finished with value: 0.2765489551187085 and parameters: {'subsample': 0.7005255083966228, 'dropout_rate': 0.3407483301890853, 'n_estimators': 299, 'learning_rate': 0.09635955935176935}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.24491888518632518
Fold 2 IBS: 0.21394643608724886
Fold 3 IBS: 0.22883360560392402
Fold 4 IBS: 0.23481674059049726
Fold 5 IBS: 0.22462925934514152
[I 2024-04-16 11:31:46,255] Trial 13 finished with value: 0.22942898536262737 and parameters: {'subsample': 0.8375283540798665, 'dropout_rate': 0.10204657427249281, 'n_estimators': 109, 'learning_rate': 0.020825018906816123}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.246378318400798
Fold 2 IBS: 0.23070779658658666
Fold 3 IBS: 0.22814404573020539
Fold 4 IBS: 0.24189059245172867
Fold 5 IBS: 0.2288714126780461
[I 2024-04-16 11:31:46,914] Trial 14 finished with value: 0.23519843316947292 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.3797566211149095, 'n_estimators': 124, 'learning_rate': 0.0025916531369806137}. Best is trial 0 with value: 0.22651708185654124.
Fold 1 IBS: 0.2504207187589881
Fold 2 IBS: 0.1977621186268543
Fold 3 IBS: 0.2303772353287059
Fold 4 IBS: 0.22925737721352257
Fold 5 IBS: 0.22210719599310766
[I 2024-04-16 11:31:47,671] Trial 15 finished with value: 0.22598492918423568 and parameters: {'subsample': 0.9623249773241934, 'dropout_rate': 0.6659535844592464, 'n_estimators': 152, 'learning_rate': 0.030719364452518588}. Best is trial 15 with value: 0.22598492918423568.
Fold 1 IBS: 0.24679287869168856
Fold 2 IBS: 0.23058284931467568
Fold 3 IBS: 0.22891382549401285
Fold 4 IBS: 0.2411837639462512
Fold 5 IBS: 0.22893412051708772
[I 2024-04-16 11:31:47,793] Trial 16 finished with value: 0.2352814875927432 and parameters: {'subsample': 0.9949729835634431, 'dropout_rate': 0.6811678867399016, 'n_estimators': 5, 'learning_rate': 0.03625963899140291}. Best is trial 15 with value: 0.22598492918423568.
Fold 1 IBS: 0.3756504096063402
Fold 2 IBS: 0.16778120097769486
Fold 3 IBS: 0.2973324871145832
Fold 4 IBS: 0.29974558564660014
Fold 5 IBS: 0.30890673025329657
[I 2024-04-16 11:31:50,217] Trial 17 finished with value: 0.289883282719703 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.7574099126710454, 'n_estimators': 360, 'learning_rate': 0.09528388678947255}. Best is trial 15 with value: 0.22598492918423568.
Fold 1 IBS: 0.247160664586713
Fold 2 IBS: 0.2040069850674547
Fold 3 IBS: 0.22546028610499586
Fold 4 IBS: 0.2372447779932013
Fold 5 IBS: 0.22290586357116488
[I 2024-04-16 11:31:50,678] Trial 18 finished with value: 0.22735571546470595 and parameters: {'subsample': 0.6211759851139029, 'dropout_rate': 0.5760573862272105, 'n_estimators': 95, 'learning_rate': 0.039198744936714616}. Best is trial 15 with value: 0.22598492918423568.
Fold 1 IBS: 0.2561709118165144
Fold 2 IBS: 0.1899101256856419

Fold 3 IBS: 0.23176649970092905
Fold 4 IBS: 0.22914748233649584
Fold 5 IBS: 0.22201402626583885
[I 2024-04-16 11:31:51,038] Trial 19 finished with value: 0.225801809161084 and parameters: {'subsample': 0.94616158758761, 'dropout_rate': 0.22827203020188386, 'n_estimators': 70, 'learning_rate': 0.08697733590757546}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.24959950048357138
Fold 2 IBS: 0.19954737342877818
Fold 3 IBS: 0.2300253764336497
Fold 4 IBS: 0.23015441638199688
Fold 5 IBS: 0.22218063467579216
[I 2024-04-16 11:31:51,315] Trial 20 finished with value: 0.22630146028075765 and parameters: {'subsample': 0.8915988185901454, 'dropout_rate': 0.7933084651006226, 'n_estimators': 54, 'learning_rate': 0.0817175642960023}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.25343805486117815
Fold 2 IBS: 0.1929792488703679
Fold 3 IBS: 0.23126028185408112
Fold 4 IBS: 0.2295679856672015
Fold 5 IBS: 0.22192783273263939
[I 2024-04-16 11:31:51,614] Trial 21 finished with value: 0.2258346807970936 and parameters: {'subsample': 0.9213485703871861, 'dropout_rate': 0.9754161103921428, 'n_estimators': 65, 'learning_rate': 0.08351893330336355}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.29970912359407115
Fold 2 IBS: 0.1602305616429425
Fold 3 IBS: 0.2479753262338787
Fold 4 IBS: 0.24876834183098923
Fold 5 IBS: 0.23834482884467761
[I 2024-04-16 11:31:52,362] Trial 22 finished with value: 0.23900563642931183 and parameters: {'subsample': 0.9423467987179995, 'dropout_rate': 0.9870356618218766, 'n_estimators': 158, 'learning_rate': 0.08907298086730236}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.24927132413256015
Fold 2 IBS: 0.19980597672796854
Fold 3 IBS: 0.23013942259256692
Fold 4 IBS: 0.2339438175358877
Fold 5 IBS: 0.22221948579355072
[I 2024-04-16 11:31:52,671] Trial 23 finished with value: 0.2270760053565068 and parameters: {'subsample': 0.7971671966184224, 'dropout_rate': 0.6090521893511177, 'n_estimators': 52, 'learning_rate': 0.0842122998711699}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.25601978446911017
Fold 2 IBS: 0.18988958686908056
Fold 3 IBS: 0.23189301605199258
Fold 4 IBS: 0.22991092903782545
Fold 5 IBS: 0.22203677129780458
[I 2024-04-16 11:31:53,023] Trial 24 finished with value: 0.22595001754516267 and parameters: {'subsample': 0.9175114339944408, 'dropout_rate': 0.9891266982842322, 'n_estimators': 76, 'learning_rate': 0.07932946294646856}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.2581233995802236
Fold 2 IBS: 0.18766976838054136
Fold 3 IBS: 0.2323938030797745
Fold 4 IBS: 0.2303126272336896
Fold 5 IBS: 0.22221980305485042
[I 2024-04-16 11:31:53,390] Trial 25 finished with value: 0.22614388026581592 and parameters: {'subsample': 0.916624000645056, 'dropout_rate': 0.9918160640215505, 'n_estimators': 81, 'learning_rate': 0.07962455224461008}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.24601526175052038
Fold 2 IBS: 0.22807147042882508
Fold 3 IBS: 0.2288275677008401
Fold 4 IBS: 0.23991647529224724
Fold 5 IBS: 0.22816348032668343
[I 2024-04-16 11:31:53,522] Trial 26 finished with value: 0.23419885109982327 and parameters: {'subsample': 0.8444307735647675, 'dropout_rate': 0.905674096459986, 'n_estimators': 8, 'learning_rate': 0.06549306685568446}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.25818961113358313
Fold 2 IBS: 0.18866151315816523
Fold 3 IBS: 0.23245099486535398
Fold 4 IBS: 0.23392344203003534
Fold 5 IBS: 0.2221768809749765
[I 2024-04-16 11:31:53,885] Trial 27 finished with value: 0.22708048843242282 and parameters: {'subsample': 0.7807658824198818, 'dropout_rate': 0.8247302853236417, 'n_estimators': 74, 'learning_rate': 0.0865388163577994}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.33082410515863797
Fold 2 IBS: 0.1537831885104763
Fold 3 IBS: 0.25173456031773794
Fold 4 IBS: 0.2881723578960256
Fold 5 IBS: 0.26782678790034803
[I 2024-04-16 11:31:55,366] Trial 28 finished with value: 0.25846819995664516 and parameters: {'subsample': 0.6392688011259168, 'dropout_rate': 0.21794975309288822, 'n_estimators': 229, 'learning_rate': 0.09712167196341212}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.26822449917785196
Fold 2 IBS: 0.17853100772870484
Fold 3 IBS: 0.2254633289214824
Fold 4 IBS: 0.24566339440625654
Fold 5 IBS: 0.22428960070546516
[I 2024-04-16 11:31:56,000] Trial 29 finished with value: 0.22843436618795215 and parameters: {'subsample': 0.5909365698967339, 'dropout_rate': 0.9430576733480622, 'n_estimators': 139, 'learning_rate': 0.06023494420229}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.33964612315040604
Fold 2 IBS: 0.15373857673352287
Fold 3 IBS: 0.27294202143785357
Fold 4 IBS: 0.27802952481498194
Fold 5 IBS: 0.27708881859916623
[I 2024-04-16 11:31:57,468] Trial 30 finished with value: 0.2642890129471861 and parameters: {'subsample': 0.9194279420283575, 'dropout_rate': 0.8369974833659269, 'n_estimators': 261, 'learning_rate': 0.09026223481130724}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.2831061774177976
Fold 2 IBS: 0.16835542678415427
Fold 3 IBS: 0.24047711098943358
Fold 4 IBS: 0.23808523652579733
Fold 5 IBS: 0.22882948006547693
[I 2024-04-16 11:31:58,097] Trial 31 finished with value: 0.23177068635653192 and parameters: {'subsample': 0.9660127728220417, 'dropout_rate': 0.9361526122466682, 'n_estimators': 140, 'learning_rate': 0.07767563160111796}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.2586115542331994
Fold 2 IBS: 0.18692638994875535
Fold 3 IBS: 0.2323748864218944
Fold 4 IBS: 0.23371991843033302
Fold 5 IBS: 0.22208568441543455
[I 2024-04-16 11:31:58,562] Trial 32 finished with value: 0.22674368668992337 and parameters: {'subsample': 0.8070059859957615, 'dropout_rate': 0.4911718716201293, 'n_estimators': 94, 'learning_rate': 0.06912302462064465}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.25089793193925464
Fold 2 IBS: 0.19688178000370352
Fold 3 IBS: 0.23043184440600992
Fold 4 IBS: 0.22970430258974917
Fold 5 IBS: 0.22206403242024939
[I 2024-04-16 11:31:58,884] Trial 33 finished with value: 0.22599597827179335 and parameters: {'subsample': 0.9425265254166793, 'dropout_rate': 0.775795985209953, 'n_estimators': 65, 'learning_rate': 0.073640124239003}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.24643989566100505
Fold 2 IBS: 0.2294229216753752
Fold 3 IBS: 0.22886623434993783
Fold 4 IBS: 0.24054098755748612
Fold 5 IBS: 0.2285465482840509
[I 2024-04-16 11:31:59,065] Trial 34 finished with value: 0.234763317505571 and parameters: {'subsample': 0.9946025548907218, 'dropout_rate': 0.8793547745290419, 'n_estimators': 26, 'learning_rate': 0.012827802002422114}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.3016404416526744
Fold 2 IBS: 0.15918702378979915
Fold 3 IBS: 0.2468846984850568
Fold 4 IBS: 0.2618763722274857
Fold 5 IBS: 0.2401891898401155
[I 2024-04-16 11:31:59,929] Trial 35 finished with value: 0.2419555451990263 and parameters: {'subsample': 0.7508543772382344, 'dropout_rate': 0.43975685710717877, 'n_estimators': 161, 'learning_rate': 0.09115779537923976}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.264763630855962
Fold 2 IBS: 0.1812986647378103
Fold 3 IBS: 0.23422628992452027
Fold 4 IBS: 0.23138895672205598
Fold 5 IBS: 0.22292514740416638
[I 2024-04-16 11:32:00,603] Trial 36 finished with value: 0.226920537928903 and parameters: {'subsample': 0.9054981099591123, 'dropout_rate': 0.24408912236765595, 'n_estimators': 129, 'learning_rate': 0.06005943075597116}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.2662078429457003
Fold 2 IBS: 0.18293665102158468
Fold 3 IBS: 0.23226481525998682
Fold 4 IBS: 0.23900979801029626
Fold 5 IBS: 0.2235141217893838
[I 2024-04-16 11:32:01,530] Trial 37 finished with value: 0.22878664580539035 and parameters: {'subsample': 0.7189998615155947, 'dropout_rate': 0.6215260670393689, 'n_estimators': 176, 'learning_rate': 0.044812988820562547}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.2448375733698387
Fold 2 IBS: 0.21343220618445963
Fold 3 IBS: 0.22532918207048103
Fold 4 IBS: 0.24034404302405254
Fold 5 IBS: 0.22442931728389132
[I 2024-04-16 11:32:01,734] Trial 38 finished with value: 0.22967446438654462 and parameters: {'subsample': 0.3846504386173175, 'dropout_rate': 0.9563981905125529, 'n_estimators': 35, 'learning_rate': 0.07220986107374139}. Best is trial 19 with value: 0.225801809161084.

Fold 1 IBS: 0.25319952780709715
Fold 2 IBS: 0.19447065295499547
Fold 3 IBS: 0.2308832935467258
Fold 4 IBS: 0.23130284304424584
Fold 5 IBS: 0.2219474736234986
[I 2024-04-16 11:32:02,835] Trial 39 finished with value: 0.22636075819531257 and parameters: {'subsample': 0.8264537565050025, 'dropout_rate': 0.5138173926600543, 'n_estimators': 199, 'learning_rate': 0.026783213087327076}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.35748458583075876
Fold 2 IBS: 0.1574368697533429
Fold 3 IBS: 0.28413193107336593
Fold 4 IBS: 0.29041667511576114
Fold 5 IBS: 0.2921425104485691
[I 2024-04-16 11:32:04,870] Trial 40 finished with value: 0.27632251444435957 and parameters: {'subsample': 0.8890339254719992, 'dropout_rate': 0.280971539366882, 'n_estimators': 289, 'learning_rate': 0.0996566606976679}. Best is trial 19 with value: 0.225801809161084.
Fold 1 IBS: 0.2533457475769324
Fold 2 IBS: 0.19315732935382318
Fold 3 IBS: 0.23104002496179532
Fold 4 IBS: 0.2293951872360855
Fold 5 IBS: 0.2219321753441482
[I 2024-04-16 11:32:05,214] Trial 41 finished with value: 0.2257740928945569 and parameters: {'subsample': 0.9443992828523667, 'dropout_rate': 0.7419164519353776, 'n_estimators': 71, 'learning_rate': 0.07585491431097509}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.259423505820603
Fold 2 IBS: 0.18625641208438362
Fold 3 IBS: 0.23264708576891716
Fold 4 IBS: 0.22922386377916368
Fold 5 IBS: 0.22225859746628762
[I 2024-04-16 11:32:05,667] Trial 42 finished with value: 0.225961892983871 and parameters: {'subsample': 0.9579738213269194, 'dropout_rate': 0.6954623000860509, 'n_estimators': 85, 'learning_rate': 0.07842468424553507}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2602123455895459
Fold 2 IBS: 0.18552967639339848
Fold 3 IBS: 0.23270944626630205
Fold 4 IBS: 0.2297993687048539
Fold 5 IBS: 0.22231532725361872
[I 2024-04-16 11:32:06,180] Trial 43 finished with value: 0.22611323284154383 and parameters: {'subsample': 0.9402657701474848, 'dropout_rate': 0.7362444157051781, 'n_estimators': 86, 'learning_rate': 0.0787720137048971}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24948086092451735
Fold 2 IBS: 0.199752999289811
Fold 3 IBS: 0.2299024567646964
Fold 4 IBS: 0.23168727284972107
Fold 5 IBS: 0.2222430855121907
[I 2024-04-16 11:32:06,559] Trial 44 finished with value: 0.2266133350681873 and parameters: {'subsample': 0.8702101278250107, 'dropout_rate': 0.8246936925931294, 'n_estimators': 64, 'learning_rate': 0.06741271995510012}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2448207828738162
Fold 2 IBS: 0.2184865650526666
Fold 3 IBS: 0.2287646994257834
Fold 4 IBS: 0.2376049385416809
Fold 5 IBS: 0.22556075762480207
[I 2024-04-16 11:32:06,776] Trial 45 finished with value: 0.23104754870374983 and parameters: {'subsample': 0.7634152448919623, 'dropout_rate': 0.4482955212137865, 'n_estimators': 20, 'learning_rate': 0.08428790051418254}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.26849883273547903
Fold 2 IBS: 0.17891053075026475
Fold 3 IBS: 0.23536011464842346
Fold 4 IBS: 0.23138550857042786
Fold 5 IBS: 0.22384337151465455
[I 2024-04-16 11:32:07,327] Trial 46 finished with value: 0.22759967164384992 and parameters: {'subsample': 0.9942450605977344, 'dropout_rate': 0.7127364349042715, 'n_estimators': 108, 'learning_rate': 0.07653714925482254}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24504035857987022
Fold 2 IBS: 0.21311751412369767
Fold 3 IBS: 0.2281644277459874
Fold 4 IBS: 0.23486189973643876
Fold 5 IBS: 0.22428943570657545
[I 2024-04-16 11:32:07,586] Trial 47 finished with value: 0.22909472717851392 and parameters: {'subsample': 0.8360122151529756, 'dropout_rate': 0.8788907102606666, 'n_estimators': 44, 'learning_rate': 0.05548548656431612}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.27071542760893125
Fold 2 IBS: 0.18470457842995128
Fold 3 IBS: 0.217620477927625
Fold 4 IBS: 0.26099438334151737
Fold 5 IBS: 0.22490291075539234
[I 2024-04-16 11:32:08,207] Trial 48 finished with value: 0.23178755561268347 and parameters: {'subsample': 0.23216850993067895, 'dropout_rate': 0.18065034164482444, 'n_estimators': 108, 'learning_rate': 0.09301459611515146}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24686970478807088
Fold 2 IBS: 0.23071184930256688
Fold 3 IBS: 0.22791364100890812
Fold 4 IBS: 0.24141059860062886
Fold 5 IBS: 0.22923491262886717
[I 2024-04-16 11:32:08,352] Trial 49 finished with value: 0.23522814126580838 and parameters: {'subsample': 0.6999223502099867, 'dropout_rate': 0.9113983562246994, 'n_estimators': 2, 'learning_rate': 0.07159897596844994}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.354545956353332
Fold 2 IBS: 0.15712526469470728
Fold 3 IBS: 0.282465368546601
Fold 4 IBS: 0.28682143660797993
Fold 5 IBS: 0.29026655919121797
[I 2024-04-16 11:32:12,101] Trial 50 finished with value: 0.27424491707876764 and parameters: {'subsample': 0.9551649622007263, 'dropout_rate': 0.633091953438621, 'n_estimators': 433, 'learning_rate': 0.06377492340886515}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2617696514780831
Fold 2 IBS: 0.18497746800193843
Fold 3 IBS: 0.23297328288554664
Fold 4 IBS: 0.23034193770759964
Fold 5 IBS: 0.22261692430093225
[I 2024-04-16 11:32:12,522] Trial 51 finished with value: 0.22653585287481998 and parameters: {'subsample': 0.9168226748743538, 'dropout_rate': 0.6711526594298516, 'n_estimators': 82, 'learning_rate': 0.08570804073000544}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.286985326079369
Fold 2 IBS: 0.1661120810369012
Fold 3 IBS: 0.24239806529395377
Fold 4 IBS: 0.24008131621162043
Fold 5 IBS: 0.23078826163744554
[I 2024-04-16 11:32:13,304] Trial 52 finished with value: 0.233273010051858 and parameters: {'subsample': 0.960460749341789, 'dropout_rate': 0.5525213089905855, 'n_estimators': 143, 'learning_rate': 0.08158171981489405}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24576864579944363
Fold 2 IBS: 0.20896463422279737
Fold 3 IBS: 0.2290762773471851
Fold 4 IBS: 0.2336923843227738
Fold 5 IBS: 0.2235217212356474
[I 2024-04-16 11:32:13,624] Trial 53 finished with value: 0.22820473258556948 and parameters: {'subsample': 0.8727898069929698, 'dropout_rate': 0.6994990493889525, 'n_estimators': 58, 'learning_rate': 0.05060340894075095}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2695993769269589
Fold 2 IBS: 0.17755779817444534
Fold 3 IBS: 0.2359543717254212
Fold 4 IBS: 0.23193066732448506
Fold 5 IBS: 0.22415278170423908
[I 2024-04-16 11:32:14,390] Trial 54 finished with value: 0.22783899917110992 and parameters: {'subsample': 0.974658854027039, 'dropout_rate': 0.6353830934393914, 'n_estimators': 115, 'learning_rate': 0.07461394866202432}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.31322820221062997
Fold 2 IBS: 0.15539411467471803
Fold 3 IBS: 0.2560768251212976
Fold 4 IBS: 0.25808589238754737
Fold 5 IBS: 0.24985739864871784
[I 2024-04-16 11:32:15,463] Trial 55 finished with value: 0.24652848660858212 and parameters: {'subsample': 0.9214603066870183, 'dropout_rate': 0.7928710931623068, 'n_estimators': 193, 'learning_rate': 0.08824418247601588}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24588207654615424
Fold 2 IBS: 0.227159595976155
Fold 3 IBS: 0.2288003419680462
Fold 4 IBS: 0.239643807997938
Fold 5 IBS: 0.22784140525639246
[I 2024-04-16 11:32:15,736] Trial 56 finished with value: 0.23386544554893715 and parameters: {'subsample': 0.8858881715083585, 'dropout_rate': 0.7518357579040702, 'n_estimators': 41, 'learning_rate': 0.014897416548086101}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.26564738533977783
Fold 2 IBS: 0.1813080726980039
Fold 3 IBS: 0.21937990243474834
Fold 4 IBS: 0.255217670760277
Fold 5 IBS: 0.2242960667896071
[I 2024-04-16 11:32:16,221] Trial 57 finished with value: 0.22916981960448282 and parameters: {'subsample': 0.43065093399202026, 'dropout_rate': 0.9979220368759698, 'n_estimators': 102, 'learning_rate': 0.08181927547435099}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25935506313321127

Fold 2 IBS: 0.18716533330408597
Fold 3 IBS: 0.23303197607358758
Fold 4 IBS: 0.23398477041757762
Fold 5 IBS: 0.22216692496562387
[I 2024-04-16 11:32:16,983] Trial 58 finished with value: 0.22714081357881727 and parameters: {'subsample': 0.8049034694205583, 'dropout_rate': 0.5787791443289121, 'n_estimators': 154, 'learning_rate': 0.043247386812275496}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24520739805611824
Fold 2 IBS: 0.212288887450923
Fold 3 IBS: 0.22892286779651505
Fold 4 IBS: 0.234841528625502
Fold 5 IBS: 0.22406946857168855
[I 2024-04-16 11:32:17,347] Trial 59 finished with value: 0.2290660301001494 and parameters: {'subsample': 0.8394135718238601, 'dropout_rate': 0.8497981022720253, 'n_estimators': 79, 'learning_rate': 0.03241534540850621}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.28252826808016807
Fold 2 IBS: 0.16820900927725183
Fold 3 IBS: 0.22493067580151604
Fold 4 IBS: 0.2564161095583284
Fold 5 IBS: 0.22837098545596912
[I 2024-04-16 11:32:17,968] Trial 60 finished with value: 0.23209100963464668 and parameters: {'subsample': 0.5376430707327773, 'dropout_rate': 0.3037405579652127, 'n_estimators': 122, 'learning_rate': 0.09374323513623611}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2510205593656709
Fold 2 IBS: 0.1969448826619744
Fold 3 IBS: 0.23045822654223297
Fold 4 IBS: 0.22986399753754694
Fold 5 IBS: 0.22203730957064605
[I 2024-04-16 11:32:18,278] Trial 61 finished with value: 0.22606499513561426 and parameters: {'subsample': 0.9356271629423867, 'dropout_rate': 0.7746115977556445, 'n_estimators': 65, 'learning_rate': 0.07405384760829568}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25019381666728086
Fold 2 IBS: 0.19822008992214815
Fold 3 IBS: 0.23033651139427064
Fold 4 IBS: 0.22922221510799776
Fold 5 IBS: 0.22212459113203598
[I 2024-04-16 11:32:18,595] Trial 62 finished with value: 0.2260194448447467 and parameters: {'subsample': 0.961664759366807, 'dropout_rate': 0.6586025353373273, 'n_estimators': 66, 'learning_rate': 0.07043322032294658}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2449594486852649
Fold 2 IBS: 0.2215374919683215
Fold 3 IBS: 0.22872365729212712
Fold 4 IBS: 0.23650387653431604
Fold 5 IBS: 0.22619684424432246
[I 2024-04-16 11:32:18,748] Trial 63 finished with value: 0.2315842637448704 and parameters: {'subsample': 0.99501228056662, 'dropout_rate': 0.7261449437227965, 'n_estimators': 17, 'learning_rate': 0.08112819964582989}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24629237470417534
Fold 2 IBS: 0.20770543978109599
Fold 3 IBS: 0.2292529535368587
Fold 4 IBS: 0.23173768510218695
Fold 5 IBS: 0.22320549267633466
[I 2024-04-16 11:32:18,993] Trial 64 finished with value: 0.2276387891601303 and parameters: {'subsample': 0.9361901917017421, 'dropout_rate': 0.9685288521404399, 'n_estimators': 43, 'learning_rate': 0.07519604401693643}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2668965468444188
Fold 2 IBS: 0.18089238288475598
Fold 3 IBS: 0.2343496422173808
Fold 4 IBS: 0.23123179152459497
Fold 5 IBS: 0.2235196813715162
[I 2024-04-16 11:32:19,405] Trial 65 finished with value: 0.22737800896853333 and parameters: {'subsample': 0.8937151982042366, 'dropout_rate': 0.8133640278196687, 'n_estimators': 91, 'learning_rate': 0.08660420061326018}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.3075654901914088
Fold 2 IBS: 0.15724001217661873
Fold 3 IBS: 0.25238519979676977
Fold 4 IBS: 0.25671722986946105
Fold 5 IBS: 0.24527400311533615
[I 2024-04-16 11:32:20,701] Trial 66 finished with value: 0.2438363870299189 and parameters: {'subsample': 0.8666816197173317, 'dropout_rate': 0.7792739477170713, 'n_estimators': 239, 'learning_rate': 0.06623652074006302}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24493186980192355
Fold 2 IBS: 0.2150632315336606
Fold 3 IBS: 0.22884963792576252
Fold 4 IBS: 0.2335796181241081
Fold 5 IBS: 0.22462976380805574
[I 2024-04-16 11:32:20,899] Trial 67 finished with value: 0.22941082423870213 and parameters: {'subsample': 0.968003497447528, 'dropout_rate': 0.41140974694353233, 'n_estimators': 29, 'learning_rate': 0.07746242613388166}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24929823244263646
Fold 2 IBS: 0.20036978980465883
Fold 3 IBS: 0.22992325266296793
Fold 4 IBS: 0.23059901456793433
Fold 5 IBS: 0.2222421218206451
[I 2024-04-16 11:32:21,254] Trial 68 finished with value: 0.22648648225976853 and parameters: {'subsample': 0.9086334894988488, 'dropout_rate': 0.583662202262188, 'n_estimators': 74, 'learning_rate': 0.0582375351466085}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.28183441687060357
Fold 2 IBS: 0.16905425509685773
Fold 3 IBS: 0.23992975885132875
Fold 4 IBS: 0.2372858385229312
Fold 5 IBS: 0.22815020600352215
[I 2024-04-16 11:32:21,832] Trial 69 finished with value: 0.23125089506904867 and parameters: {'subsample': 0.9452144350743412, 'dropout_rate': 0.8982972157128986, 'n_estimators': 127, 'learning_rate': 0.08363062693873462}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25158025798718103
Fold 2 IBS: 0.19616733227229582
Fold 3 IBS: 0.23082510985099672
Fold 4 IBS: 0.2337832724969983
Fold 5 IBS: 0.22198302408617332
[I 2024-04-16 11:32:22,118] Trial 70 finished with value: 0.226867799338729 and parameters: {'subsample': 0.7824510004515342, 'dropout_rate': 0.8554926349135679, 'n_estimators': 55, 'learning_rate': 0.09047778588933372}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.24993186861061617
Fold 2 IBS: 0.19880139036351263
Fold 3 IBS: 0.23026401761762996
Fold 4 IBS: 0.22926379706794883
Fold 5 IBS: 0.2221655810029332
[I 2024-04-16 11:32:22,436] Trial 71 finished with value: 0.2260853309325282 and parameters: {'subsample': 0.9686076132837765, 'dropout_rate': 0.6620452476202561, 'n_estimators': 64, 'learning_rate': 0.07142692396910126}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25717746064169283
Fold 2 IBS: 0.189317290279058
Fold 3 IBS: 0.2321046780029043
Fold 4 IBS: 0.22892263424323267
Fold 5 IBS: 0.22204580635291535
[I 2024-04-16 11:32:22,965] Trial 72 finished with value: 0.22591357390396066 and parameters: {'subsample': 0.9982807841920852, 'dropout_rate': 0.6865270883562795, 'n_estimators': 90, 'learning_rate': 0.0688100224299478}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2533410467975245
Fold 2 IBS: 0.1938793008374898
Fold 3 IBS: 0.23109569430042062
Fold 4 IBS: 0.22881993580834312
Fold 5 IBS: 0.2219323835969892
[I 2024-04-16 11:32:23,464] Trial 73 finished with value: 0.22581367226815346 and parameters: {'subsample': 0.9971336029436192, 'dropout_rate': 0.6939988157837401, 'n_estimators': 86, 'learning_rate': 0.06252075647004612}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25689340760950524
Fold 2 IBS: 0.18967575800888065
Fold 3 IBS: 0.23202813478834497
Fold 4 IBS: 0.2288931367271859
Fold 5 IBS: 0.22202592291059828
[I 2024-04-16 11:32:23,957] Trial 74 finished with value: 0.225903272008903 and parameters: {'subsample': 0.9917781863910351, 'dropout_rate': 0.7032984433443716, 'n_estimators': 98, 'learning_rate': 0.06255647559065586}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2579578216615319
Fold 2 IBS: 0.18789477177754652
Fold 3 IBS: 0.2324550180720669
Fold 4 IBS: 0.22905608285415
Fold 5 IBS: 0.22212518735415734
[I 2024-04-16 11:32:24,456] Trial 75 finished with value: 0.22589777634389058 and parameters: {'subsample': 0.9768542865537894, 'dropout_rate': 0.6013221357207541, 'n_estimators': 101, 'learning_rate': 0.06379518657495052}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.32991876690063243
Fold 2 IBS: 0.15320031241681484
Fold 3 IBS: 0.26733620087307847
Fold 4 IBS: 0.2715963301229544
Fold 5 IBS: 0.2665964792059447
[I 2024-04-16 11:32:27,545] Trial 76 finished with value: 0.257729617903885 and parameters: {'subsample': 0.9934815190828818, 'dropout_rate': 0.103048681019025, 'n_estimators': 344, 'learning_rate': 0.06436615939399397}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2521744060852405
Fold 2 IBS: 0.19522281378823012
Fold 3 IBS: 0.23074241213260618
Fold 4 IBS: 0.22924593627305967

Fold 5 IBS: 0.22195101233402054
[I 2024-04-16 11:32:28,022] Trial 77 finished with value: 0.2258673161226314 and parameters: {'subsample': 0.9241806819491492, 'dropout_rate': 0.6015827229072146, 'n_estimators': 96, 'learning_rate': 0.05340669166408334}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2502303777379061
Fold 2 IBS: 0.19871411116671306
Fold 3 IBS: 0.2301958168448245
Fold 4 IBS: 0.23109356781896448
Fold 5 IBS: 0.2220986101175287
[I 2024-04-16 11:32:28,477] Trial 78 finished with value: 0.22646649673718736 and parameters: {'subsample': 0.8563848810472314, 'dropout_rate': 0.6027083599398141, 'n_estimators': 98, 'learning_rate': 0.047078364671080265}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.27416643596802237
Fold 2 IBS: 0.1746513042353999
Fold 3 IBS: 0.23725344964183798
Fold 4 IBS: 0.23344106600037298
Fold 5 IBS: 0.22537565707734725
[I 2024-04-16 11:32:29,347] Trial 79 finished with value: 0.2289775825845961 and parameters: {'subsample': 0.9824205898574147, 'dropout_rate': 0.5353656663169338, 'n_estimators': 167, 'learning_rate': 0.055434989273590154}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2693470281292524
Fold 2 IBS: 0.17800143576256433
Fold 3 IBS: 0.23545611809022163
Fold 4 IBS: 0.23322133117857757
Fold 5 IBS: 0.2237500280585902
[I 2024-04-16 11:32:30,010] Trial 80 finished with value: 0.22795518824384123 and parameters: {'subsample': 0.9044958465819355, 'dropout_rate': 0.4752787091687975, 'n_estimators': 135, 'learning_rate': 0.06218144712712767}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25949837972236284
Fold 2 IBS: 0.18611816925240682
Fold 3 IBS: 0.2326442139915838
Fold 4 IBS: 0.22964632712424937
Fold 5 IBS: 0.22228078634659532
[I 2024-04-16 11:32:30,558] Trial 81 finished with value: 0.22603757528743965 and parameters: {'subsample': 0.9296412135209964, 'dropout_rate': 0.5574936139228506, 'n_estimators': 115, 'learning_rate': 0.058068569994318094}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25772659644533874
Fold 2 IBS: 0.18875524566049573
Fold 3 IBS: 0.2322569603322202
Fold 4 IBS: 0.22897676889257515
Fold 5 IBS: 0.22208633426453567
[I 2024-04-16 11:32:31,005] Trial 82 finished with value: 0.2259603811190331 and parameters: {'subsample': 0.9934417044259826, 'dropout_rate': 0.6371874921746887, 'n_estimators': 94, 'learning_rate': 0.06709435008215843}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25484360303520637
Fold 2 IBS: 0.19284374760444908
Fold 3 IBS: 0.23113322101986972
Fold 4 IBS: 0.22968531079875587
Fold 5 IBS: 0.22193873713380743
[I 2024-04-16 11:32:31,378] Trial 83 finished with value: 0.2260889239184177 and parameters: {'subsample': 0.9006910267647653, 'dropout_rate': 0.691111329986497, 'n_estimators': 81, 'learning_rate': 0.0692402614218835}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.2457170664263933
Fold 2 IBS: 0.20920697399626573
Fold 3 IBS: 0.22910883090666256
Fold 4 IBS: 0.23223052075827819
Fold 5 IBS: 0.22350497677184805
[I 2024-04-16 11:32:31,633] Trial 84 finished with value: 0.22795367377188955 and parameters: {'subsample': 0.927980533403528, 'dropout_rate': 0.6025938881780027, 'n_estimators': 48, 'learning_rate': 0.062057122438189005}. Best is trial 41 with value: 0.2257740928945569.
Fold 1 IBS: 0.25388349892455214
Fold 2 IBS: 0.19261897398168573
Fold 3 IBS: 0.23124452363681194
Fold 4 IBS: 0.22879567623990446
Fold 5 IBS: 0.22192845942792414
[I 2024-04-16 11:32:32,152] Trial 85 finished with value: 0.22569422644217568 and parameters: {'subsample': 0.9715715213181028, 'dropout_rate': 0.7450922639673777, 'n_estimators': 107, 'learning_rate': 0.05183366352011241}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2642327024910153
Fold 2 IBS: 0.1822720370678454
Fold 3 IBS: 0.23416488219564596
Fold 4 IBS: 0.23020642514114362
Fold 5 IBS: 0.22292039645853295
[I 2024-04-16 11:32:32,862] Trial 86 finished with value: 0.22675928867083667 and parameters: {'subsample': 0.973338874555221, 'dropout_rate': 0.7163043385786448, 'n_estimators': 148, 'learning_rate': 0.050975426677558236}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2586882080060807
Fold 2 IBS: 0.1869460620937375
Fold 3 IBS: 0.23251340578213958
Fold 4 IBS: 0.22918146205335915
Fold 5 IBS: 0.22218870542820193
[I 2024-04-16 11:32:33,413] Trial 87 finished with value: 0.22590356867270378 and parameters: {'subsample': 0.9467026517711762, 'dropout_rate': 0.7515300759355974, 'n_estimators': 121, 'learning_rate': 0.05396326729547295}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2783528391367452
Fold 2 IBS: 0.1716268039173328
Fold 3 IBS: 0.23865342352282945
Fold 4 IBS: 0.2353892500794583
Fold 5 IBS: 0.22669905860700343
[I 2024-04-16 11:32:34,351] Trial 88 finished with value: 0.23014427505267382 and parameters: {'subsample': 0.9494531033613437, 'dropout_rate': 0.7472416639297738, 'n_estimators': 186, 'learning_rate': 0.05352025369158552}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2450281390790575
Fold 2 IBS: 0.2074321275086972
Fold 3 IBS: 0.2224079369892734
Fold 4 IBS: 0.2592878941005463
Fold 5 IBS: 0.22472113929782106
[I 2024-04-16 11:32:34,907] Trial 89 finished with value: 0.2317754473950791 and parameters: {'subsample': 0.13360665877080907, 'dropout_rate': 0.5185158050153199, 'n_estimators': 109, 'learning_rate': 0.047963070621394974}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.25967260425283634
Fold 2 IBS: 0.18621452258088442
Fold 3 IBS: 0.23311093330465546
Fold 4 IBS: 0.2318602687833108
Fold 5 IBS: 0.22220662859779047
[I 2024-04-16 11:32:35,502] Trial 90 finished with value: 0.22661299150389552 and parameters: {'subsample': 0.8187507169164705, 'dropout_rate': 0.8106776337766259, 'n_estimators': 126, 'learning_rate': 0.05362308890567035}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2539941409444973
Fold 2 IBS: 0.19312776688802621
Fold 3 IBS: 0.2312722768263133
Fold 4 IBS: 0.2287990087373986
Fold 5 IBS: 0.221927837681318
[I 2024-04-16 11:32:35,960] Trial 91 finished with value: 0.2258242062155107 and parameters: {'subsample': 0.9965248054816894, 'dropout_rate': 0.6798415081183182, 'n_estimators': 95, 'learning_rate': 0.05816567614319185}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.24873541549879816
Fold 2 IBS: 0.20088152900262893
Fold 3 IBS: 0.23000177546867
Fold 4 IBS: 0.2296004084105936
Fold 5 IBS: 0.22236538574180031
[I 2024-04-16 11:32:36,310] Trial 92 finished with value: 0.22631690282449818 and parameters: {'subsample': 0.9755553803593067, 'dropout_rate': 0.6531890485207847, 'n_estimators': 73, 'learning_rate': 0.05829524604334563}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.256819720089552
Fold 2 IBS: 0.18965748548739025
Fold 3 IBS: 0.2317974358854204
Fold 4 IBS: 0.22988451548557118
Fold 5 IBS: 0.22205264844189257
[I 2024-04-16 11:32:36,784] Trial 93 finished with value: 0.2260423610779653 and parameters: {'subsample': 0.8877868040780087, 'dropout_rate': 0.7657261909851332, 'n_estimators': 102, 'learning_rate': 0.05979995730665267}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2564066226408396
Fold 2 IBS: 0.18945902080964425
Fold 3 IBS: 0.2319294346432616
Fold 4 IBS: 0.2289717477335028
Fold 5 IBS: 0.22201316979619032
[I 2024-04-16 11:32:37,336] Trial 94 finished with value: 0.22575599912468772 and parameters: {'subsample': 0.9526437861482817, 'dropout_rate': 0.7332302999669821, 'n_estimators': 116, 'learning_rate': 0.052543424649300195}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.25133858838576667
Fold 2 IBS: 0.19638761496910134
Fold 3 IBS: 0.23055220192663195
Fold 4 IBS: 0.22940002177241609
Fold 5 IBS: 0.22199354992642326
[I 2024-04-16 11:32:37,812] Trial 95 finished with value: 0.22593439539606783 and parameters: {'subsample': 0.9217389461712917, 'dropout_rate': 0.7147788219960369, 'n_estimators': 101, 'learning_rate': 0.04874985541171085}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2654052160306399
Fold 2 IBS: 0.18046952269179725
Fold 3 IBS: 0.23457097923602643
Fold 4 IBS: 0.23279955207564698
Fold 5 IBS: 0.22340512738713766
[I 2024-04-16 11:32:38,500] Trial 96 finished with value: 0.2273300794842496 and parameters: {'subsample': 0.8517830955966456, 'dropout_rate': 0.6202675693497828, 'n_estimators': 136, 'learning_rate': 0.057425548394441216}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2468361944497131
Fold 2 IBS: 0.2054832247771215

Fold 3 IBS: 0.22944653432708567
Fold 4 IBS: 0.23063827375154522
Fold 5 IBS: 0.2229432534166449
[I 2024-04-16 11:32:38,916] Trial 97 finished with value: 0.2270694961444221 and parameters: {'subsample': 0.9767455260315752, 'dropout_rate': 0.6488691992826511, 'n_estimators': 87, 'learning_rate': 0.04071453518360497}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.24480764542120276
Fold 2 IBS: 0.21626586987434746
Fold 3 IBS: 0.2272316015685666
Fold 4 IBS: 0.23945647308726237
Fold 5 IBS: 0.2251722183706185
[I 2024-04-16 11:32:39,152] Trial 98 finished with value: 0.2305867616643995 and parameters: {'subsample': 0.5666236381817311, 'dropout_rate': 0.6788633161910144, 'n_estimators': 36, 'learning_rate': 0.051501923007209446}. Best is trial 85 with value: 0.22569422644217568.
Fold 1 IBS: 0.2944680130865383
Fold 2 IBS: 0.1628625094014068
Fold 3 IBS: 0.24556046949396654
Fold 4 IBS: 0.24468301864678557
Fold 5 IBS: 0.23483960337036835
[I 2024-04-16 11:32:40,304] Trial 99 finished with value: 0.23648272279981314 and parameters: {'subsample': 0.9999284250082234, 'dropout_rate': 0.7314020713460329, 'n_estimators': 211, 'learning_rate': 0.06162659403497599}. Best is trial 85 with value: 0.22569422644217568.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.22569422644217568], datetime_start=datetime.datetime(2024, 4, 16, 11, 32, 31, 636247), datetime_complete=datetime.datetime(2024, 4, 16, 11, 32, 32, 152129), params={'subsample': 0.9715715213181028, 'dropout_rate': 0.7450922639673777, 'n_estimators': 107, 'learning_rate': 0.05183366352011241}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=85, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.9715715213181028, 'dropout_rate': 0.7450922639673777, 'n_estimators': 107, 'learning_rate': 0.05183366352011241}


* Best Score for IBS:
 0.22569422644217568

In [136]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [137]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.646
train_ibs:  0.226

#### Test

In [138]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [139]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.5065802886056728,
                                              learning_rate=0.08860071779281121,
                                              n_estimators=417,
                                              random_state=123,
                                              subsample=0.10200972368178224)

C-index score: 0.54

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7450922639673777,
                                              learning_rate=0.05183366352011241,
                                              n_estimators=107,
                                              random_state=123,
                                              subsample=0.9715715213181028)

IBS: 0.233

In [140]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [141]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
ExtraSurvivalTrees               0.798   1.0
Randomsurvivalforest             0.797   2.0
GradientBoosting                 0.714   3.0
CoxElastic                       0.684   4.0
CoxLasso                         0.683   5.0
CoxPH                            0.681   6.0
ComponentwiseGradientBoosting    0.646   7.0
CoxRidge                         0.631   8.0

In [142]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.202   1.0
ExtraSurvivalTrees             0.205   2.0
CoxElastic                     0.214   3.0
CoxLasso                       0.215   4.0
CoxPH                          0.216   5.0
ComponentwiseGradientBoosting  0.226   6.0
GradientBoosting               0.228   7.0
CoxRidge                       0.236   8.0

In [143]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
GradientBoosting                 0.544   1.0
ComponentwiseGradientBoosting    0.540   2.0
CoxRidge                         0.534   3.0
Randomsurvivalforest             0.517   4.0
CoxPH                            0.508   5.0
CoxLasso                         0.507   6.0
CoxElastic                       0.506   7.5
ExtraSurvivalTrees               0.506   7.5

In [144]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ComponentwiseGradientBoosting  0.233   3.0
ExtraSurvivalTrees             0.250   4.0
Randomsurvivalforest           0.261   5.0
CoxLasso                       0.282   6.5
CoxElastic                     0.282   6.5
CoxPH                          0.283   8.0

In [145]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d3/dfs/minmax/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d3_dfs_minmax_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [146]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-16