In [1]:
import warnings
warnings.filterwarnings("ignore")
import random
import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sklearn.cluster import KMeans
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [2]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [3]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [4]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [5]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

## Test dataset: MAASTRO

In [6]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [7]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [8]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask]

In [9]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]

In [10]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [11]:
# Check if some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [12]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

In [13]:
# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

X_train:  (139, 374)
y_train:  (139,)

(99, 376)

# Feature Selection: RENT

In [14]:
selected_features = ["shape_Sphericity",
                     "glrlm_HighGrayLevelRunEmphasis_PET_c04",
                     "shape_MajorAxisLength",
                     "LBP_102_PET"]

# Selecting features in the DataFrame
X_rent = X[selected_features]

In [15]:
# Selecting features in the DataFrame
X_rent = X[selected_features]
X_new = X_rent.copy()

X_MAASTRO_rent = X_MAASTRO[selected_features]
MAASTRO_new = X_MAASTRO_rent.copy()

# Standardization

In [16]:
# Standardize X_new, the new data with the selected features only 
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [17]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [18]:
X_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.761164,16.969770,42.073251,0.000000
1,0.697049,15.598394,24.613845,0.000000
2,0.565792,17.334294,48.030294,0.000034
3,0.684364,14.009277,25.589900,0.000000
4,0.503142,21.202180,34.684750,0.000199
...,...,...,...,...
134,0.742102,16.110383,33.069705,0.000000
135,0.722918,21.249575,41.043692,0.000000
136,0.652963,14.873884,36.618802,0.000000
137,0.724255,21.648860,45.870392,0.000000
138,0.722633,20.191288,30.363259,0.000000

In [19]:
X_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.704475,0.085656,0.059912,0.000000
1,0.101791,-0.291967,-0.755402,0.000000
2,-1.132016,0.186031,0.338093,0.524263
3,-0.017443,-0.729547,-0.709822,0.000000
4,-1.720923,1.251094,-0.285114,3.028668
...,...,...,...,...
134,0.525285,-0.150985,-0.360532,0.000000
135,0.344965,1.264145,0.011834,0.000000
136,-0.312609,-0.491468,-0.194798,0.000000
137,0.357529,1.374092,0.237230,0.000000
138,0.342282,0.972735,-0.486917,0.000000

In [20]:
MAASTRO_new

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,0.668072,19.034156,50.002093,0.000026
1,0.669961,11.392444,41.753334,0.000167
2,0.624081,14.567421,44.375483,0.000057
3,0.577624,13.477331,46.115989,0.000000
4,0.630933,16.365554,54.394967,0.000000
...,...,...,...,...
94,0.671754,17.492295,34.218615,0.000000
95,0.632189,14.267900,51.046869,0.000000
96,0.645548,12.143752,50.417953,0.000000
97,0.727488,15.300229,44.901412,0.000000
98,0.672838,13.850774,36.574294,0.000000

In [21]:
MAASTRO_new_std

,shape_Sphericity,glrlm_HighGrayLevelRunEmphasis_PET_c04,shape_MajorAxisLength,LBP_102_PET
0,-0.170593,0.654106,0.430171,0.398737
1,-0.152832,-1.450119,0.044973,2.544568
2,-0.584101,-0.575856,0.167421,0.869691
3,-1.020797,-0.876024,0.248699,0.000000
4,-0.519690,-0.080721,0.635308,0.000000
...,...,...,...,...
94,-0.135979,0.229539,-0.306881,0.000000
95,-0.507883,-0.658333,0.478960,0.000000
96,-0.382318,-1.243239,0.449591,0.000000
97,0.387916,-0.374070,0.191981,0.000000
98,-0.125793,-0.773193,-0.196876,0.000000

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [22]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:31:18,866] A new study created in memory with name: no-name-d05ffb63-2b6c-4117-819d-f63d35554a0e

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734

[I 2024-04-14 16:31:27,721] A new study created in memory with name: no-name-1927faca-d25a-441a-902e-7dab84fb4ccb

Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:27,707] Trial 0 finished with value: 0.6885812252956434 and parameters: {}. Best is trial 0 with value: 0.6885812252956434.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6885812252956434], datetime_start=datetime.datetime(2024, 4, 14, 16, 31, 18, 988674), datetime_complete=datetime.datetime(2024, 4, 14, 16, 31, 27, 706442), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6885812252956434

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24445113125013962
Fold 2 IBS: 0.19124878012978022
Fold 3 IBS: 0.20665297767216081
Fold 4 IBS: 0.19438765965098836
Fold 5 IBS: 0.19775948988265402
[I 2024-04-14 16:31:28,489] Trial 0 finished with value: 0.20690000771714462 and parameters: {}. Best is trial 0 with value: 0.20690000771714462.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20690000771714462], datetime_start=datetime.datetime(2024, 4, 14, 16, 31, 27, 878614), datetime_complete=datetime.datetime(2024, 4, 14, 16, 31, 28, 489067), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20690000771714462

In [23]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [24]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.689
train_ibs:  0.207

#### Test

In [25]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [26]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.532
IBS score: 0.29

In [27]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [28]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis - Ridge

#### Train

In [29]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:31:28,850] A new study created in memory with name: no-name-430ba2bd-467d-4ec4-8316-1aeb7c9de30b

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.599601593625498

[I 2024-04-14 16:31:29,122] A new study created in memory with name: no-name-d7047135-8ed6-4c89-8aa8-e9b99fefcba6

Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:31:29,103] Trial 0 finished with value: 0.6603978887575652 and parameters: {}. Best is trial 0 with value: 0.6603978887575652.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6603978887575652], datetime_start=datetime.datetime(2024, 4, 14, 16, 31, 28, 889267), datetime_complete=datetime.datetime(2024, 4, 14, 16, 31, 29, 103202), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6603978887575652

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709805071834
Fold 2 IBS: 0.2320398756992525
Fold 3 IBS: 0.2289818676351831
Fold 4 IBS: 0.2419747644101402
Fold 5 IBS: 0.22939558596182483
[I 2024-04-14 16:31:29,532] Trial 0 finished with value: 0.23592783835142378 and parameters: {}. Best is trial 0 with value: 0.23592783835142378.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783835142378], datetime_start=datetime.datetime(2024, 4, 14, 16, 31, 29, 203925), datetime_complete=datetime.datetime(2024, 4, 14, 16, 31, 29, 532463), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783835142378

In [30]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [31]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.66
train_ibs:  0.236

#### Test

In [32]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [33]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.535

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [34]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [35]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:31:29,752] A new study created in memory with name: no-name-ca02c333-dbd5-4161-805b-26a8fcd5d45a

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872

[I 2024-04-14 16:31:30,317] A new study created in memory with name: no-name-15dd2cad-4d63-4ff8-b0d0-72281b86ab6b

Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:30,288] Trial 0 finished with value: 0.6910259146234387 and parameters: {}. Best is trial 0 with value: 0.6910259146234387.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6910259146234387], datetime_start=datetime.datetime(2024, 4, 14, 16, 31, 29, 804985), datetime_complete=datetime.datetime(2024, 4, 14, 16, 31, 30, 287892), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6910259146234387

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24385936084363596
Fold 2 IBS: 0.19104145101471223
Fold 3 IBS: 0.2076394199174915
Fold 4 IBS: 0.19441380426749091
Fold 5 IBS: 0.1981557680324636
[I 2024-04-14 16:31:30,840] Trial 0 finished with value: 0.20702196081515883 and parameters: {}. Best is trial 0 with value: 0.20702196081515883.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.20702196081515883], datetime_start=datetime.datetime(2024, 4, 14, 16, 31, 30, 358620), datetime_complete=datetime.datetime(2024, 4, 14, 16, 31, 30, 840449), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.20702196081515883

In [36]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [37]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.691
train_ibs:  0.207

#### Test

In [38]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [39]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.288

In [40]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [41]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:31:31,262] A new study created in memory with name: no-name-54f73c05-a366-4012-ab35-2873daae3b29

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:31,703] Trial 0 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6901748507936514.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:32,136] Trial 1 finished with value: 0.6885196689459349 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 0 with value: 0.6901748507936514.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:32,520] Trial 2 finished with value: 0.6893780380446474 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 0 with value: 0.6901748507936514.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:32,995] Trial 3 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 0 with value: 0.6901748507936514.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:33,465] Trial 4 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 0 with value: 0.6901748507936514.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:33,872] Trial 5 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 0 with value: 0.6901748507936514.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:34,274] Trial 6 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:34,763] Trial 7 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:35,123] Trial 8 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:35,541] Trial 9 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:35,926] Trial 10 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:36,302] Trial 11 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9972280068904047}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:36,729] Trial 12 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9946087870438435}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:37,118] Trial 13 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8521165717679541}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:37,537] Trial 14 finished with value: 0.665602501891388 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:37,975] Trial 15 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8659212232095017}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:38,431] Trial 16 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8592866247617579}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:39,506] Trial 17 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8140829029918109}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:40,578] Trial 18 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.5819463953201167}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:41,234] Trial 19 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9535087433508003}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:42,194] Trial 20 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7540198302114602}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:42,701] Trial 21 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9453140545316446}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:43,538] Trial 22 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9952149413953396}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:44,583] Trial 23 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8898693182098678}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877

Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:45,195] Trial 24 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7805647035680947}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:46,002] Trial 25 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9368557715647121}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:31:46,427] Trial 26 finished with value: 0.6567448709556052 and parameters: {'l1_ratio': 0.015423757551295547}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:47,151] Trial 27 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.6022588122254688}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:47,789] Trial 28 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.6499747968454208}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:48,424] Trial 29 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9010792166439672}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:49,381] Trial 30 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8107108448948633}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:50,213] Trial 31 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9790160904460925}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:50,837] Trial 32 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9889509715055751}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:51,495] Trial 33 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9033942188713268}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:52,087] Trial 34 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9969906676119189}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:52,742] Trial 35 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9145273991086058}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:53,316] Trial 36 finished with value: 0.6893780380446474 and parameters: {'l1_ratio': 0.23789482035414378}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:53,881] Trial 37 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7342815000174964}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:54,315] Trial 38 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8450450825036032}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:54,847] Trial 39 finished with value: 0.6885196689459349 and parameters: {'l1_ratio': 0.35153102114871604}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:55,377] Trial 40 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.6762726602177129}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:56,120] Trial 41 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9440922341009589}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:56,863] Trial 42 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8629643445340418}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:57,484] Trial 43 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8119687552544277}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:58,024] Trial 44 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8940576552266526}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:31:58,732] Trial 45 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.5034995787719242}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:59,320] Trial 46 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9428787838786565}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:31:59,902] Trial 47 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9991045282580079}. Best is trial 6 with value: 0.6910259146234387.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:00,748] Trial 48 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8577244154633872}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:01,293] Trial 49 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9586049921503356}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:01,753] Trial 50 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7809764372372684}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:02,241] Trial 51 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.947113067248926}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:02,730] Trial 52 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9266288431945623}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:03,226] Trial 53 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8738032823955033}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:03,704] Trial 54 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9672083616741531}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:04,113] Trial 55 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.91673127684173}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:04,594] Trial 56 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8182548665223563}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:05,057] Trial 57 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7698172605367876}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:05,499] Trial 58 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9615190362083281}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:05,943] Trial 59 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8849977187572995}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:06,434] Trial 60 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8375350400183244}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:06,980] Trial 61 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9983361821362374}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:07,444] Trial 62 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9281823430944834}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:07,816] Trial 63 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9693089707333972}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:08,255] Trial 64 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9081736791840964}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:08,794] Trial 65 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9607766127341739}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:09,300] Trial 66 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8820170472794326}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:09,721] Trial 67 finished with value: 0.665602501891388 and parameters: {'l1_ratio': 0.10022359348974141}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:10,201] Trial 68 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9343762812680735}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:10,727] Trial 69 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9982048868245822}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:11,352] Trial 70 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.6278366970608916}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:11,908] Trial 71 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9740810608075614}. Best is trial 6 with value: 0.6910259146234387.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:12,604] Trial 72 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9081252899025114}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:13,289] Trial 73 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9793980507422808}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:13,785] Trial 74 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9393512015259131}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:14,350] Trial 75 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8304219935585806}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:14,883] Trial 76 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8840771276397438}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:15,325] Trial 77 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9976659558448657}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:32:15,953] Trial 78 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.5482840176570491}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:16,431] Trial 79 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7120921418578845}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:16,966] Trial 80 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8582408686713943}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:17,559] Trial 81 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9489378863670678}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:18,173] Trial 82 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7914528089022664}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:18,961] Trial 83 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.912736845537975}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:19,646] Trial 84 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.893901969387018}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:32:20,221] Trial 85 finished with value: 0.6885196689459349 and parameters: {'l1_ratio': 0.33218847491866843}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:20,653] Trial 86 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9775614329151197}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:21,103] Trial 87 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9247695361648618}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:32:21,587] Trial 88 finished with value: 0.6893164816949389 and parameters: {'l1_ratio': 0.43363935410934373}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:22,029] Trial 89 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9519539542206147}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:22,438] Trial 90 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8645281374342476}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:22,853] Trial 91 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9744891524849301}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:23,342] Trial 92 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9357185241600254}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:23,803] Trial 93 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9580271148305448}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:24,232] Trial 94 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9089883143589916}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:24,824] Trial 95 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9991107887307169}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876

Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:25,349] Trial 96 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.8811798113995886}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:25,832] Trial 97 finished with value: 0.6910259146234387 and parameters: {'l1_ratio': 0.9297903244741107}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:26,328] Trial 98 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.7409679226648089}. Best is trial 6 with value: 0.6910259146234387.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851

[I 2024-04-14 16:32:26,850] A new study created in memory with name: no-name-31c79ca8-6edd-4144-ac7a-399677c0c32f

Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:32:26,841] Trial 99 finished with value: 0.6901748507936514 and parameters: {'l1_ratio': 0.8361048592393505}. Best is trial 6 with value: 0.6910259146234387.


* Best trial for C-index:
 FrozenTrial(number=6, state=TrialState.COMPLETE, values=[0.6910259146234387], datetime_start=datetime.datetime(2024, 4, 14, 16, 31, 33, 876193), datetime_complete=datetime.datetime(2024, 4, 14, 16, 31, 34, 274449), params={'l1_ratio': 0.980766121964777}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=6, value=None)


* Best Score for C-index:
 0.6910259146234387

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24384372425403145
Fold 2 IBS: 0.19102097719113648
Fold 3 IBS: 0.20732370743921147
Fold 4 IBS: 0.1943604220569732
Fold 5 IBS: 0.19804380439121627
[I 2024-04-14 16:32:27,415] Trial 0 finished with value: 0.20691852706651379 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.20691852706651379.
Fold 1 IBS: 0.24385693771373115
Fold 2 IBS: 0.19096890975333564
Fold 3 IBS: 0.20666536420831402
Fold 4 IBS: 0.19423126307775032
Fold 5 IBS: 0.1978098990568525
[I 2024-04-14 16:32:28,120] Trial 1 finished with value: 0.20670647476199672 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.20670647476199672.
Fold 1 IBS: 0.24385714315300536
Fold 2 IBS: 0.1909610640349487
Fold 3 IBS: 0.20653138473563162
Fold 4 IBS: 0.19420655067123255
Fold 5 IBS: 0.1977610598434761
[I 2024-04-14 16:32:28,783] Trial 2 finished with value: 0.20666344048765883 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24386408391848477
Fold 2 IBS: 0.19099835777191068
Fold 3 IBS: 0.20715127579670206
Fold 4 IBS: 0.19432501875219213
Fold 5 IBS: 0.19798515644316372
[I 2024-04-14 16:32:29,325] Trial 3 finished with value: 0.20686477853649068 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24385558738562718
Fold 2 IBS: 0.19100704866961574
Fold 3 IBS: 0.20740608167658459
Fold 4 IBS: 0.19436540909873395
Fold 5 IBS: 0.19804817015240808
[I 2024-04-14 16:32:29,981] Trial 4 finished with value: 0.20693645939659394 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24386541335025777
Fold 2 IBS: 0.19098763826469495
Fold 3 IBS: 0.20693429346084102
Fold 4 IBS: 0.1942826681570079
Fold 5 IBS: 0.19790654842024416
[I 2024-04-14 16:32:30,533] Trial 5 finished with value: 0.20679531233060916 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24385313072519135
Fold 2 IBS: 0.19103861581250747
Fold 3 IBS: 0.20763131300511836
Fold 4 IBS: 0.19441143940140337
Fold 5 IBS: 0.19815341943227577
[I 2024-04-14 16:32:31,102] Trial 6 finished with value: 0.20701758367529927 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24383742988577814
Fold 2 IBS: 0.19101807495722486
Fold 3 IBS: 0.20731562273540569
Fold 4 IBS: 0.19435777577525917
Fold 5 IBS: 0.19804149557272727
[I 2024-04-14 16:32:31,589] Trial 7 finished with value: 0.206914079785279 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24386398473881618
Fold 2 IBS: 0.19099242071052838
Fold 3 IBS: 0.20703633105442668
Fold 4 IBS: 0.19430110450399682
Fold 5 IBS: 0.1979436497885527
[I 2024-04-14 16:32:32,198] Trial 8 finished with value: 0.20682749815926416 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24383309548348694
Fold 2 IBS: 0.19097121611978937
Fold 3 IBS: 0.20688965896436284
Fold 4 IBS: 0.19427539241478262
Fold 5 IBS: 0.19788047794593983
[I 2024-04-14 16:32:32,744] Trial 9 finished with value: 0.20676996818567234 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24389039681744457
Fold 2 IBS: 0.22567643500211304
Fold 3 IBS: 0.22875147163974346
Fold 4 IBS: 0.23700727959810097
Fold 5 IBS: 0.19762944032381444
[I 2024-04-14 16:32:33,109] Trial 10 finished with value: 0.2265910046762433 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.20666344048765883.
Fold 1 IBS: 0.24388088071595027
Fold 2 IBS: 0.19094218708579028
Fold 3 IBS: 0.20643336005464055
Fold 4 IBS: 0.19418143556857545
Fold 5 IBS: 0.19772930345069936
[I 2024-04-14 16:32:33,942] Trial 11 finished with value: 0.20663343337513118 and parameters: {'l1_ratio': 0.19077404209371474}. Best is trial 11 with value: 0.20663343337513118.
Fold 1 IBS: 0.24386311441691094
Fold 2 IBS: 0.2281331806276729
Fold 3 IBS: 0.22881811255712187
Fold 4 IBS: 0.23889479523969104
Fold 5 IBS: 0.22632066440984425
[I 2024-04-14 16:32:34,268] Trial 12 finished with value: 0.2332059734502482 and parameters: {'l1_ratio': 0.04835900598617554}. Best is trial 11 with value: 0.20663343337513118.
Fold 1 IBS: 0.24387686483757548
Fold 2 IBS: 0.19094344750168876
Fold 3 IBS: 0.20648518916973052
Fold 4 IBS: 0.19419006808999323
Fold 5 IBS: 0.19774712417423493
[I 2024-04-14 16:32:34,856] Trial 13 finished with value: 0.20664853875464462 and parameters: {'l1_ratio': 0.2114475350243538}. Best is trial 11 with value: 0.20663343337513118.
Fold 1 IBS: 0.24386545189611866
Fold 2 IBS: 0.1909335465624719
Fold 3 IBS: 0.20643180934660788
Fold 4 IBS: 0.19417331241631544
Fold 5 IBS: 0.19772365672667067
[I 2024-04-14 16:32:35,431] Trial 14 finished with value: 0.20662555538963692 and parameters: {'l1_ratio': 0.18459727307810245}. Best is trial 14 with value: 0.20662555538963692.
Fold 1 IBS: 0.24708827453635143
Fold 2 IBS: 0.23146793153089046
Fold 3 IBS: 0.22895428401890255
Fold 4 IBS: 0.2415187124533356
Fold 5 IBS: 0.22893830056959202
[I 2024-04-14 16:32:35,768] Trial 15 finished with value: 0.2355935006218144 and parameters: {'l1_ratio': 0.006552728882407266}. Best is trial 14 with value: 0.20662555538963692.
Fold 1 IBS: 0.2438458927052969
Fold 2 IBS: 0.1909484395568936
Fold 3 IBS: 0.20640554026914976
Fold 4 IBS: 0.19418057817320686
Fold 5 IBS: 0.1977165609240759
[I 2024-04-14 16:32:36,426] Trial 16 finished with value: 0.20661940232572462 and parameters: {'l1_ratio': 0.1772909900515591}. Best is trial 16 with value: 0.20661940232572462.
Fold 1 IBS: 0.24385534921056756
Fold 2 IBS: 0.1909725523672454
Fold 3 IBS: 0.2067407264321982
Fold 4 IBS: 0.19424481509430952
Fold 5 IBS: 0.19783749971336234
[I 2024-04-14 16:32:37,088] Trial 17 finished with value: 0.2067301885635366 and parameters: {'l1_ratio': 0.32162557863487895}. Best is trial 16 with value: 0.20661940232572462.
Fold 1 IBS: 0.24388669935491356
Fold 2 IBS: 0.19093925787766658
Fold 3 IBS: 0.20634174779402562
Fold 4 IBS: 0.19416588130632306
Fold 5 IBS: 0.1976979001614113
[I 2024-04-14 16:32:38,036] Trial 18 finished with value: 0.20660629729886804 and parameters: {'l1_ratio': 0.1552967775121356}. Best is trial 18 with value: 0.20660629729886804.
Fold 1 IBS: 0.24384851673443272
Fold 2 IBS: 0.1909391401783795
Fold 3 IBS: 0.20624218890101093
Fold 4 IBS: 0.19413015741970918
Fold 5 IBS: 0.19765647177710885
[I 2024-04-14 16:32:38,758] Trial 19 finished with value: 0.20656329500212825 and parameters: {'l1_ratio': 0.11626329996616502}. Best is trial 19 with value: 0.20656329500212825.
Fold 1 IBS: 0.24384947932624224
Fold 2 IBS: 0.19093749744089733
Fold 3 IBS: 0.206210764273938
Fold 4 IBS: 0.19412395284483128
Fold 5 IBS: 0.1976448320052108
[I 2024-04-14 16:32:39,439] Trial 20 finished with value: 0.20655330517822393 and parameters: {'l1_ratio': 0.10500472511016506}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384734939264133
Fold 2 IBS: 0.1909363838933515
Fold 3 IBS: 0.22873091189631373
Fold 4 IBS: 0.19412281755256258
Fold 5 IBS: 0.1976440800916237
[I 2024-04-14 16:32:40,023] Trial 21 finished with value: 0.2110563085652986 and parameters: {'l1_ratio': 0.10457346814139208}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24389034241872762
Fold 2 IBS: 0.19093377917906568
Fold 3 IBS: 0.2062285100184122
Fold 4 IBS: 0.19414575607411055
Fold 5 IBS: 0.19765283919974042
[I 2024-04-14 16:32:40,673] Trial 22 finished with value: 0.2065702453780113 and parameters: {'l1_ratio': 0.1139775430155659}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2471899065137811
Fold 2 IBS: 0.23183100248795194
Fold 3 IBS: 0.22897166987708772
Fold 4 IBS: 0.24180821520933402
Fold 5 IBS: 0.22922824625820684
[I 2024-04-14 16:32:40,913] Trial 23 finished with value: 0.23580580806927234 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.243851910329933
Fold 2 IBS: 0.1909663251275729
Fold 3 IBS: 0.20665851910621094
Fold 4 IBS: 0.1942288585471781
Fold 5 IBS: 0.19780802688581775
[I 2024-04-14 16:32:41,593] Trial 24 finished with value: 0.20670272799934253 and parameters: {'l1_ratio': 0.2830544587085615}. Best is trial 20 with value: 0.20655330517822393.

Fold 1 IBS: 0.24389125940108533
Fold 2 IBS: 0.1909321892340936
Fold 3 IBS: 0.2287320438949615
Fold 4 IBS: 0.19411853822138028
Fold 5 IBS: 0.19764125279155897
[I 2024-04-14 16:32:42,302] Trial 25 finished with value: 0.21106305670861594 and parameters: {'l1_ratio': 0.10297700483781348}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384175324356847
Fold 2 IBS: 0.19097041920242336
Fold 3 IBS: 0.20680750845909757
Fold 4 IBS: 0.19425414285743003
Fold 5 IBS: 0.19786339608895115
[I 2024-04-14 16:32:43,041] Trial 26 finished with value: 0.2067474439702941 and parameters: {'l1_ratio': 0.3527001258697712}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24383187824404834
Fold 2 IBS: 0.19100929740110129
Fold 3 IBS: 0.20718148857936933
Fold 4 IBS: 0.19433225538465687
Fold 5 IBS: 0.1979936739277619
[I 2024-04-14 16:32:43,940] Trial 27 finished with value: 0.20686971870738752 and parameters: {'l1_ratio': 0.58416616744615}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384783090114132
Fold 2 IBS: 0.19103620567487417
Fold 3 IBS: 0.20762441452946254
Fold 4 IBS: 0.19440942729374258
Fold 5 IBS: 0.19815142544433145
[I 2024-04-14 16:32:45,045] Trial 28 finished with value: 0.20701386076871042 and parameters: {'l1_ratio': 0.964957522585106}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438174722276448
Fold 2 IBS: 0.191022430267279
Fold 3 IBS: 0.20758485750109232
Fold 4 IBS: 0.19439789496625798
Fold 5 IBS: 0.1981400730351215
[I 2024-04-14 16:32:45,962] Trial 29 finished with value: 0.20699254559947913 and parameters: {'l1_ratio': 0.8830970003537575}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385387786380175
Fold 2 IBS: 0.19094427496016197
Fold 3 IBS: 0.20628529759393163
Fold 4 IBS: 0.1941403861364797
Fold 5 IBS: 0.1976715488929775
[I 2024-04-14 16:32:46,715] Trial 30 finished with value: 0.20657907708947051 and parameters: {'l1_ratio': 0.13048781200302498}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24388196367364423
Fold 2 IBS: 0.19092692312175513
Fold 3 IBS: 0.22873352111882
Fold 4 IBS: 0.19413520550708005
Fold 5 IBS: 0.1976454602254857
[I 2024-04-14 16:32:47,463] Trial 31 finished with value: 0.21106461472935703 and parameters: {'l1_ratio': 0.10103338112661776}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24383614471701268
Fold 2 IBS: 0.1909582343269931
Fold 3 IBS: 0.20663704490906362
Fold 4 IBS: 0.1942213195560888
Fold 5 IBS: 0.19780218528479687
[I 2024-04-14 16:32:48,286] Trial 32 finished with value: 0.206690985758791 and parameters: {'l1_ratio': 0.27357119396913165}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.243882522195874
Fold 2 IBS: 0.1909341708858019
Fold 3 IBS: 0.20629235168892998
Fold 4 IBS: 0.19415559771950125
Fold 5 IBS: 0.19768185031304308
[I 2024-04-14 16:32:48,953] Trial 33 finished with value: 0.20658929856063005 and parameters: {'l1_ratio': 0.13833195289260838}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384568670488724
Fold 2 IBS: 0.19095898126892458
Fold 3 IBS: 0.20657973372794608
Fold 4 IBS: 0.19421285824062204
Fold 5 IBS: 0.19778012245710117
[I 2024-04-14 16:32:49,620] Trial 34 finished with value: 0.2066754764798962 and parameters: {'l1_ratio': 0.24840395436271276}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24692025180435426
Fold 2 IBS: 0.2308904388367196
Fold 3 IBS: 0.22892757046520476
Fold 4 IBS: 0.24106074103112407
Fold 5 IBS: 0.22847911225662945
[I 2024-04-14 16:32:49,937] Trial 35 finished with value: 0.23525562287880644 and parameters: {'l1_ratio': 0.013339535951618589}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385595187472558
Fold 2 IBS: 0.22782093313337093
Fold 3 IBS: 0.22880785494847736
Fold 4 IBS: 0.23865237922013013
Fold 5 IBS: 0.19758849787612923
[I 2024-04-14 16:32:50,450] Trial 36 finished with value: 0.22734512341056665 and parameters: {'l1_ratio': 0.0526249606187868}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387609005129685
Fold 2 IBS: 0.19094682224378215
Fold 3 IBS: 0.2065569788768407
Fold 4 IBS: 0.19420149013697938
Fold 5 IBS: 0.19776805649133739
[I 2024-04-14 16:32:51,369] Trial 37 finished with value: 0.2066698875600473 and parameters: {'l1_ratio': 0.2364723475855005}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24388662031047087
Fold 2 IBS: 0.19093648299888183
Fold 3 IBS: 0.2062983088233766
Fold 4 IBS: 0.19415777569755
Fold 5 IBS: 0.19768333651192155
[I 2024-04-14 16:32:52,298] Trial 38 finished with value: 0.2065925048684402 and parameters: {'l1_ratio': 0.13952741775970778}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387172110416938
Fold 2 IBS: 0.19098095515475721
Fold 3 IBS: 0.206763105300613
Fold 4 IBS: 0.19425260627909938
Fold 5 IBS: 0.19784367223246177
[I 2024-04-14 16:32:53,178] Trial 39 finished with value: 0.20674241201422014 and parameters: {'l1_ratio': 0.33395743692477575}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385177776334577
Fold 2 IBS: 0.19098623647981747
Fold 3 IBS: 0.20701938250400026
Fold 4 IBS: 0.19430075183104584
Fold 5 IBS: 0.19793893083775047
[I 2024-04-14 16:32:53,931] Trial 40 finished with value: 0.20681941588319191 and parameters: {'l1_ratio': 0.46667819693088786}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385103481475592
Fold 2 IBS: 0.19094045529289647
Fold 3 IBS: 0.20624553987773706
Fold 4 IBS: 0.19413149673087662
Fold 5 IBS: 0.19765736489739907
[I 2024-04-14 16:32:54,612] Trial 41 finished with value: 0.20656517832273305 and parameters: {'l1_ratio': 0.1168365867214849}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24386364939947208
Fold 2 IBS: 0.22693709417539773
Fold 3 IBS: 0.22878151811012426
Fold 4 IBS: 0.23796995851317396
Fold 5 IBS: 0.19760421730332464
[I 2024-04-14 16:32:55,106] Trial 42 finished with value: 0.22703128750029852 and parameters: {'l1_ratio': 0.06506835223938401}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438609180610893
Fold 2 IBS: 0.1909220157241131
Fold 3 IBS: 0.20629468260317246
Fold 4 IBS: 0.19414412287152386
Fold 5 IBS: 0.1976740666479069
[I 2024-04-14 16:32:55,842] Trial 43 finished with value: 0.20657916118156114 and parameters: {'l1_ratio': 0.1323367782237295}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387517929332667
Fold 2 IBS: 0.19094250489162481
Fold 3 IBS: 0.20649764776329213
Fold 4 IBS: 0.1941891837052785
Fold 5 IBS: 0.19774650280276632
[I 2024-04-14 16:32:56,545] Trial 44 finished with value: 0.2066502036912577 and parameters: {'l1_ratio': 0.21067289160059371}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24381927050383814
Fold 2 IBS: 0.19100345793588472
Fold 3 IBS: 0.20716537758538195
Fold 4 IBS: 0.19432690509599557
Fold 5 IBS: 0.1979891211802755
[I 2024-04-14 16:32:57,198] Trial 45 finished with value: 0.2068608264602752 and parameters: {'l1_ratio': 0.566217627804496}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24609293652886643
Fold 2 IBS: 0.22834148203012344
Fold 3 IBS: 0.2288252189685608
Fold 4 IBS: 0.23905687392724093
Fold 5 IBS: 0.22648181104422663
[I 2024-04-14 16:32:57,470] Trial 46 finished with value: 0.23375966449980368 and parameters: {'l1_ratio': 0.04554949498856466}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438501287873844
Fold 2 IBS: 0.19102393257874134
Fold 3 IBS: 0.20733193082536372
Fold 4 IBS: 0.19436311448080357
Fold 5 IBS: 0.19804615901444803
[I 2024-04-14 16:32:58,070] Trial 47 finished with value: 0.2069230531373482 and parameters: {'l1_ratio': 0.708736948333703}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24382811919806113
Fold 2 IBS: 0.19102034811204152
Fold 3 IBS: 0.2074438235393462
Fold 4 IBS: 0.1943766103625439
Fold 5 IBS: 0.19808849616174246
[I 2024-04-14 16:32:58,610] Trial 48 finished with value: 0.20695147947474704 and parameters: {'l1_ratio': 0.7768768486379835}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384460580754067
Fold 2 IBS: 0.19097705479807597
Fold 3 IBS: 0.20690556218710537
Fold 4 IBS: 0.1942728853966854

Fold 5 IBS: 0.19789859412874944
[I 2024-04-14 16:32:59,120] Trial 49 finished with value: 0.20677974046363135 and parameters: {'l1_ratio': 0.402705511740666}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384018438088706
Fold 2 IBS: 0.19094548132286418
Fold 3 IBS: 0.20639786985872818
Fold 4 IBS: 0.1941778033859872
Fold 5 IBS: 0.19771450326274714
[I 2024-04-14 16:32:59,673] Trial 50 finished with value: 0.20661516844224276 and parameters: {'l1_ratio': 0.17526057356525065}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385251050406204
Fold 2 IBS: 0.1909412262689443
Fold 3 IBS: 0.20624750352205673
Fold 4 IBS: 0.1941322816934018
Fold 5 IBS: 0.1976578888489821
[I 2024-04-14 16:33:00,489] Trial 51 finished with value: 0.2065662821674894 and parameters: {'l1_ratio': 0.11717503156407644}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24386226617594486
Fold 2 IBS: 0.2259746889406444
Fold 3 IBS: 0.2287577295619982
Fold 4 IBS: 0.23723380880667908
Fold 5 IBS: 0.197619461823559
[I 2024-04-14 16:33:00,881] Trial 52 finished with value: 0.22668959106176514 and parameters: {'l1_ratio': 0.07927613090248242}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24386977441947774
Fold 2 IBS: 0.19092447061215262
Fold 3 IBS: 0.206270467332449
Fold 4 IBS: 0.19414146893522938
Fold 5 IBS: 0.19766404855265202
[I 2024-04-14 16:33:01,918] Trial 53 finished with value: 0.20657404597039214 and parameters: {'l1_ratio': 0.1212759292745614}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385118577637635
Fold 2 IBS: 0.1909544476328811
Fold 3 IBS: 0.20646533698738392
Fold 4 IBS: 0.1941929259897913
Fold 5 IBS: 0.1977377135990342
[I 2024-04-14 16:33:02,602] Trial 54 finished with value: 0.20664032199709337 and parameters: {'l1_ratio': 0.20020150935739411}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384993622499893
Fold 2 IBS: 0.1909611698413878
Fold 3 IBS: 0.20658549871432236
Fold 4 IBS: 0.19421490007399464
Fold 5 IBS: 0.19778168815361247
[I 2024-04-14 16:33:03,437] Trial 55 finished with value: 0.20667863860166324 and parameters: {'l1_ratio': 0.2506677472985503}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24635094820521472
Fold 2 IBS: 0.22909461872396822
Fold 3 IBS: 0.22885259718426593
Fold 4 IBS: 0.2396451737713415
Fold 5 IBS: 0.2270670376207132
[I 2024-04-14 16:33:03,745] Trial 56 finished with value: 0.23420207510110075 and parameters: {'l1_ratio': 0.03562567283648875}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387324076284017
Fold 2 IBS: 0.19092199111415864
Fold 3 IBS: 0.22873495487605272
Fold 4 IBS: 0.19413054010481137
Fold 5 IBS: 0.19764234448371792
[I 2024-04-14 16:33:04,423] Trial 57 finished with value: 0.21106061426831615 and parameters: {'l1_ratio': 0.09927147905123158}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384684193341086
Fold 2 IBS: 0.19094592176247513
Fold 3 IBS: 0.20635895702129387
Fold 4 IBS: 0.19417214267563984
Fold 5 IBS: 0.1976994160589757
[I 2024-04-14 16:33:05,057] Trial 58 finished with value: 0.2066046558903591 and parameters: {'l1_ratio': 0.15930228980341984}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24381383800054207
Fold 2 IBS: 0.19100721770418186
Fold 3 IBS: 0.20728529607358634
Fold 4 IBS: 0.19434811005251768
Fold 5 IBS: 0.1980328888661485
[I 2024-04-14 16:33:05,626] Trial 59 finished with value: 0.2068974701393953 and parameters: {'l1_ratio': 0.6443692288191284}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385036171370095
Fold 2 IBS: 0.19096999716779206
Fold 3 IBS: 0.2067339062115398
Fold 4 IBS: 0.1942424420337599
Fold 5 IBS: 0.19783562879481514
[I 2024-04-14 16:33:06,389] Trial 60 finished with value: 0.20672646718432156 and parameters: {'l1_ratio': 0.3180391659359798}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438668247391877
Fold 2 IBS: 0.19092281003255193
Fold 3 IBS: 0.2062665448465172
Fold 4 IBS: 0.1941398986703446
Fold 5 IBS: 0.19766299218471106
[I 2024-04-14 16:33:07,520] Trial 61 finished with value: 0.2065718140946625 and parameters: {'l1_ratio': 0.12055623004366132}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24389449035589195
Fold 2 IBS: 0.19093612935886944
Fold 3 IBS: 0.20623451035530113
Fold 4 IBS: 0.1941270895918769
Fold 5 IBS: 0.19765443004482872
[I 2024-04-14 16:33:08,388] Trial 62 finished with value: 0.20656932994135363 and parameters: {'l1_ratio': 0.11496960387622177}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387034460483187
Fold 2 IBS: 0.2258917356262109
Fold 3 IBS: 0.2287559341792189
Fold 4 IBS: 0.23717072451688015
Fold 5 IBS: 0.1976223121864725
[I 2024-04-14 16:33:08,911] Trial 63 finished with value: 0.22666221022272284 and parameters: {'l1_ratio': 0.0805347059304223}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438579809459045
Fold 2 IBS: 0.19095171471015887
Fold 3 IBS: 0.2063738789030736
Fold 4 IBS: 0.19415957971410597
Fold 5 IBS: 0.19770342830677315
[I 2024-04-14 16:33:09,671] Trial 64 finished with value: 0.20660931651600323 and parameters: {'l1_ratio': 0.1629378792071063}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385397107618112
Fold 2 IBS: 0.19095589040168434
Fold 3 IBS: 0.2064690893406894
Fold 4 IBS: 0.19419427538820444
Fold 5 IBS: 0.1977387285116419
[I 2024-04-14 16:33:10,497] Trial 65 finished with value: 0.20664239094368025 and parameters: {'l1_ratio': 0.2013662270774649}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24680824401241166
Fold 2 IBS: 0.23051919686287503
Fold 3 IBS: 0.22891103385203718
Fold 4 IBS: 0.2407667713123607
Fold 5 IBS: 0.22818524819588604
[I 2024-04-14 16:33:10,936] Trial 66 finished with value: 0.23503809884711407 and parameters: {'l1_ratio': 0.017796496389566818}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387003392689519
Fold 2 IBS: 0.22640808405383298
Fold 3 IBS: 0.2287677798916316
Fold 4 IBS: 0.23756436578377288
Fold 5 IBS: 0.19761396110507812
[I 2024-04-14 16:33:11,696] Trial 67 finished with value: 0.22684484495224214 and parameters: {'l1_ratio': 0.07278959096887233}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438856785954925
Fold 2 IBS: 0.19093113919623717
Fold 3 IBS: 0.20622176280617818
Fold 4 IBS: 0.1941432654667346
Fold 5 IBS: 0.1976577405582528
[I 2024-04-14 16:33:12,871] Trial 68 finished with value: 0.20656791732457905 and parameters: {'l1_ratio': 0.11288124265625091}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438402040359086
Fold 2 IBS: 0.19094549150366918
Fold 3 IBS: 0.20639789627255192
Fold 4 IBS: 0.1941778129396328
Fold 5 IBS: 0.1977145103374395
[I 2024-04-14 16:33:13,557] Trial 69 finished with value: 0.20661518301784038 and parameters: {'l1_ratio': 0.17526748949852153}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387225316363598
Fold 2 IBS: 0.19094880970665962
Fold 3 IBS: 0.20661575889317257
Fold 4 IBS: 0.19421251463293882
Fold 5 IBS: 0.19778996379921382
[I 2024-04-14 16:33:14,281] Trial 70 finished with value: 0.20668786003912415 and parameters: {'l1_ratio': 0.26322747090489684}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438504583535965
Fold 2 IBS: 0.19093800942471148
Fold 3 IBS: 0.20621206469785938
Fold 4 IBS: 0.19412447472347144
Fold 5 IBS: 0.1976451779083881
[I 2024-04-14 16:33:15,126] Trial 71 finished with value: 0.20655403702160538 and parameters: {'l1_ratio': 0.10520407620317028}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385095926439931
Fold 2 IBS: 0.19095786751288232
Fold 3 IBS: 0.2065230272680214
Fold 4 IBS: 0.19420356630699387
Fold 5 IBS: 0.1977587902985786
[I 2024-04-14 16:33:15,709] Trial 72 finished with value: 0.2066588421301751 and parameters: {'l1_ratio': 0.2239700834307211}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24623628957945837
Fold 2 IBS: 0.22875613068339748
Fold 3 IBS: 0.22883997291912034
Fold 4 IBS: 0.23938033860139638
Fold 5 IBS: 0.22680351220391723
[I 2024-04-14 16:33:15,988] Trial 73 finished with value: 0.23400324879745793 and parameters: {'l1_ratio': 0.040041167482102166}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387443319573454

Fold 2 IBS: 0.1909207215842509
Fold 3 IBS: 0.22874418247192937
Fold 4 IBS: 0.2367145075877851
Fold 5 IBS: 0.1976328176965277
[I 2024-04-14 16:33:16,514] Trial 74 finished with value: 0.2195773325072455 and parameters: {'l1_ratio': 0.0898435928340312}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385792264679257
Fold 2 IBS: 0.19094892430005037
Fold 3 IBS: 0.20633026634608104
Fold 4 IBS: 0.19415063727124496
Fold 5 IBS: 0.1976874814924129
[I 2024-04-14 16:33:17,417] Trial 75 finished with value: 0.20659504641131637 and parameters: {'l1_ratio': 0.14629098567939705}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24388972547886142
Fold 2 IBS: 0.1909334298052968
Fold 3 IBS: 0.2062276175202841
Fold 4 IBS: 0.19414542658059258
Fold 5 IBS: 0.19765260292402545
[I 2024-04-14 16:33:18,273] Trial 76 finished with value: 0.2065697604618121 and parameters: {'l1_ratio': 0.11383137001752158}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24386746509440765
Fold 2 IBS: 0.19092085472635653
Fold 3 IBS: 0.20623464626765795
Fold 4 IBS: 0.19413354418844336
Fold 5 IBS: 0.19765121513308354
[I 2024-04-14 16:33:19,116] Trial 77 finished with value: 0.20656154508198982 and parameters: {'l1_ratio': 0.10878412583526416}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24723920690240478
Fold 2 IBS: 0.23201080525882428
Fold 3 IBS: 0.22898043964921075
Fold 4 IBS: 0.2419515804246934
Fold 5 IBS: 0.2293722815372739
[I 2024-04-14 16:33:19,529] Trial 78 finished with value: 0.23591086275448142 and parameters: {'l1_ratio': 0.00032920257231860983}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385916290707024
Fold 2 IBS: 0.22697573292072912
Fold 3 IBS: 0.2287825827269332
Fold 4 IBS: 0.2379996699121979
Fold 5 IBS: 0.1976026468343969
[I 2024-04-14 16:33:20,122] Trial 79 finished with value: 0.22704395906026548 and parameters: {'l1_ratio': 0.0645126121663536}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387322791232297
Fold 2 IBS: 0.19095381141200937
Fold 3 IBS: 0.20668753530179676
Fold 4 IBS: 0.19423905591593443
Fold 5 IBS: 0.19781599649995332
[I 2024-04-14 16:33:20,929] Trial 80 finished with value: 0.20671392540840333 and parameters: {'l1_ratio': 0.2969125224652297}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385286578152693
Fold 2 IBS: 0.19094141191392605
Fold 3 IBS: 0.20624797625949076
Fold 4 IBS: 0.19413247068430944
Fold 5 IBS: 0.19765801505283825
[I 2024-04-14 16:33:21,811] Trial 81 finished with value: 0.20656654793841828 and parameters: {'l1_ratio': 0.11725678900313093}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438681568392129
Fold 2 IBS: 0.19092882795085347
Fold 3 IBS: 0.20634393701367867
Fold 4 IBS: 0.19415605635148508
Fold 5 IBS: 0.19769116931959763
[I 2024-04-14 16:33:22,582] Trial 82 finished with value: 0.20659762949496557 and parameters: {'l1_ratio': 0.1493783635169781}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387147908391735
Fold 2 IBS: 0.19093691854041772
Fold 3 IBS: 0.20643990023426254
Fold 4 IBS: 0.19417648500783827
Fold 5 IBS: 0.1977258574219898
[I 2024-04-14 16:33:23,432] Trial 83 finished with value: 0.20663012805768513 and parameters: {'l1_ratio': 0.18696457415751996}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2464093061188575
Fold 2 IBS: 0.22926944819817147
Fold 3 IBS: 0.2288593154338385
Fold 4 IBS: 0.23978222581270636
Fold 5 IBS: 0.22720347198553084
[I 2024-04-14 16:33:23,740] Trial 84 finished with value: 0.23430475350982097 and parameters: {'l1_ratio': 0.03337290531237189}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24389031048801643
Fold 2 IBS: 0.19093165118397357
Fold 3 IBS: 0.22873219207362877
Fold 4 IBS: 0.19413967155671058
Fold 5 IBS: 0.19764089071874108
[I 2024-04-14 16:33:24,399] Trial 85 finished with value: 0.2110669432042141 and parameters: {'l1_ratio': 0.10277537283355047}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24386964262695968
Fold 2 IBS: 0.1909432271698078
Fold 3 IBS: 0.2065482715710788
Fold 4 IBS: 0.19419812094802602
Fold 5 IBS: 0.19776566832362727
[I 2024-04-14 16:33:24,991] Trial 86 finished with value: 0.2066649861278999 and parameters: {'l1_ratio': 0.23314065997616562}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24386718412504876
Fold 2 IBS: 0.2269062656473604
Fold 3 IBS: 0.2287806745597475
Fold 4 IBS: 0.23794626112448744
Fold 5 IBS: 0.19760545723445283
[I 2024-04-14 16:33:25,437] Trial 87 finished with value: 0.22702116853821938 and parameters: {'l1_ratio': 0.06551254903005932}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387058474638693
Fold 2 IBS: 0.1909274474900228
Fold 3 IBS: 0.20630756494102312
Fold 4 IBS: 0.19414925581284337
Fold 5 IBS: 0.19767753873684699
[I 2024-04-14 16:33:26,421] Trial 88 finished with value: 0.20658647834542462 and parameters: {'l1_ratio': 0.13495747462104118}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438758844107108
Fold 2 IBS: 0.1909361488474583
Fold 3 IBS: 0.20639784924520577
Fold 4 IBS: 0.1941690336036715
Fold 5 IBS: 0.19770992504395646
[I 2024-04-14 16:33:27,360] Trial 89 finished with value: 0.20661776823020056 and parameters: {'l1_ratio': 0.1691207134137847}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24388102079406063
Fold 2 IBS: 0.19094577308951916
Fold 3 IBS: 0.20649130673468952
Fold 4 IBS: 0.19419224895294065
Fold 5 IBS: 0.19774865845647904
[I 2024-04-14 16:33:28,114] Trial 90 finished with value: 0.20665180160553778 and parameters: {'l1_ratio': 0.21338078478051675}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387826393661619
Fold 2 IBS: 0.19092925587303172
Fold 3 IBS: 0.2062468107779604
Fold 4 IBS: 0.19414598955711893
Fold 5 IBS: 0.1976670979480712
[I 2024-04-14 16:33:29,057] Trial 91 finished with value: 0.20657348361855968 and parameters: {'l1_ratio': 0.12339324236755263}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24385479113828615
Fold 2 IBS: 0.1909402763175178
Fold 3 IBS: 0.20621781925631247
Fold 4 IBS: 0.19412678464984673
Fold 5 IBS: 0.1976467108905974
[I 2024-04-14 16:33:29,857] Trial 92 finished with value: 0.20655727645051214 and parameters: {'l1_ratio': 0.10609493332819987}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24388732874726887
Fold 2 IBS: 0.19092802526516417
Fold 3 IBS: 0.22874162016907468
Fold 4 IBS: 0.23660153346245574
Fold 5 IBS: 0.19763741677264823
[I 2024-04-14 16:33:30,554] Trial 93 finished with value: 0.21955918488332235 and parameters: {'l1_ratio': 0.09220709556377626}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24389341334253395
Fold 2 IBS: 0.22753521862131487
Fold 3 IBS: 0.22879889594977562
Fold 4 IBS: 0.23843115337069445
Fold 5 IBS: 0.1975898775607741
[I 2024-04-14 16:33:31,259] Trial 94 finished with value: 0.2272497117690186 and parameters: {'l1_ratio': 0.056586942104987055}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24386349982814615
Fold 2 IBS: 0.19092621497800927
Fold 3 IBS: 0.20633771693189348
Fold 4 IBS: 0.19415359010747374
Fold 5 IBS: 0.19768948879875822
[I 2024-04-14 16:33:32,200] Trial 95 finished with value: 0.20659410212885615 and parameters: {'l1_ratio': 0.14795837443117882}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24656815962455614
Fold 2 IBS: 0.22975492955429938
Fold 3 IBS: 0.22887865384729994
Fold 4 IBS: 0.24016370628307454
Fold 5 IBS: 0.2275834967106631
[I 2024-04-14 16:33:32,476] Trial 96 finished with value: 0.23458978920397863 and parameters: {'l1_ratio': 0.027214067515020368}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.2438573910018141
Fold 2 IBS: 0.19091110082425372
Fold 3 IBS: 0.22874762248895403
Fold 4 IBS: 0.23685730164730234
Fold 5 IBS: 0.19762678754712756
[I 2024-04-14 16:33:33,149] Trial 97 finished with value: 0.21960004070189038 and parameters: {'l1_ratio': 0.08688997160621459}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24384760048731663
Fold 2 IBS: 0.19093866179533284
Fold 3 IBS: 0.20624096950821505
Fold 4 IBS: 0.19412967012885038

Fold 5 IBS: 0.1976561470934536
[I 2024-04-14 16:33:33,813] Trial 98 finished with value: 0.20656260980263372 and parameters: {'l1_ratio': 0.11605601047082038}. Best is trial 20 with value: 0.20655330517822393.
Fold 1 IBS: 0.24387273010897204
Fold 2 IBS: 0.1909376189870331
Fold 3 IBS: 0.20644157937053642
Fold 4 IBS: 0.19417714363141486
Fold 5 IBS: 0.1977263150373932
[I 2024-04-14 16:33:34,394] Trial 99 finished with value: 0.20663107742706993 and parameters: {'l1_ratio': 0.1874631498967019}. Best is trial 20 with value: 0.20655330517822393.


* Best trial for IBS:
 FrozenTrial(number=20, state=TrialState.COMPLETE, values=[0.20655330517822393], datetime_start=datetime.datetime(2024, 4, 14, 16, 32, 38, 766426), datetime_complete=datetime.datetime(2024, 4, 14, 16, 32, 39, 439626), params={'l1_ratio': 0.10500472511016506}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=20, value=None)


* Best Score for IBS:
 0.20655330517822393

In [42]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [43]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.691
train_ibs:  0.207

#### Test

In [44]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [45]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.980766121964777)

test_cindex : 0.532

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.10500472511016506)

test_ibs:  0.288

In [46]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [47]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:33:34,843] A new study created in memory with name: no-name-614f556a-a885-4a70-a632-b28a16876311

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.6723404255319149
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:33:41,705] Trial 0 finished with value: 0.6977075894586338 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.6977075894586338.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:33:48,416] Trial 1 finished with value: 0.7128781680014569 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:33:55,114] Trial 2 finished with value: 0.7078951516958202 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:33:57,114] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:33:59,032] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 1 with value: 0.7128781680014569.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:34:07,782] Trial 5 finished with value: 0.7140624838621864 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:34:15,569] Trial 6 finished with value: 0.7101780788884746 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:34:19,132] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-14 16:34:29,708] Trial 8 finished with value: 0.5257510729613734 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:34:35,116] Trial 9 finished with value: 0.7039036721293016 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:34:35,866] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 5 with value: 0.7140624838621864.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:34:38,345] Trial 11 finished with value: 0.7271736918163124 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 131, 'oob_score': False, 'max_samples': 0.8048496584476307, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11629432582260082, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7468085106382979
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:34:40,275] Trial 12 finished with value: 0.7217535824914708 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 108, 'oob_score': False, 'max_samples': 0.8064195611120726, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10227389828304193, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:34:42,828] Trial 13 finished with value: 0.7230396596037402 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 105, 'oob_score': False, 'max_samples': 0.8350722272141606, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13041468920781069, 'warm_start': False}. Best is trial 11 with value: 0.7271736918163124.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.6845493562231759
[I 2024-04-14 16:34:44,247] Trial 14 finished with value: 0.7401429490839831 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 2, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.9806297626114981, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18121651510792322, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565

Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:34:45,708] Trial 15 finished with value: 0.7359974816455777 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9916077098875709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2050785814281292, 'warm_start': True}. Best is trial 14 with value: 0.7401429490839831.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7060085836909872
[I 2024-04-14 16:34:46,010] Trial 16 finished with value: 0.7424649927687818 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 7, 'oob_score': True, 'max_samples': 0.9632036286697128, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19855793167729388, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:34:46,258] Trial 17 finished with value: 0.7187276534642637 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 4, 'oob_score': True, 'max_samples': 0.9920927723346319, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3637168382811743, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.599601593625498
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7129277566539924
Fold 5 C-index: 0.6115879828326181
[I 2024-04-14 16:34:46,616] Trial 18 finished with value: 0.6821795609651563 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 17, 'oob_score': True, 'max_samples': 0.4733682176858589, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18440565612965779, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6394849785407726
[I 2024-04-14 16:34:47,244] Trial 19 finished with value: 0.6909365199154465 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.8996903695627709, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.3933604732001355, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6974248927038627
[I 2024-04-14 16:34:48,977] Trial 20 finished with value: 0.731849318014498 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 184, 'oob_score': True, 'max_samples': 0.7099567102313042, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2573277491349737, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:34:50,297] Trial 21 finished with value: 0.7351391125468653 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 135, 'oob_score': True, 'max_samples': 0.9578709493710758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19090506657387685, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:34:51,147] Trial 22 finished with value: 0.7341648725242437 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.9967334344648481, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22971555033034935, 'warm_start': True}. Best is trial 16 with value: 0.7424649927687818.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:34:53,343] Trial 23 finished with value: 0.7461784934529897 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 161, 'oob_score': True, 'max_samples': 0.8688645990573083, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1729801266340484, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7813688212927756
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:34:55,218] Trial 24 finished with value: 0.7410139181199299 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 164, 'oob_score': True, 'max_samples': 0.866350879679609, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07068946136637579, 'warm_start': True}. Best is trial 23 with value: 0.7461784934529897.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 16:34:57,226] Trial 25 finished with value: 0.7568542957468967 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 13, 'n_estimators': 227, 'oob_score': True, 'max_samples': 0.8561321352006472, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07248837432829829, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7946768060836502
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:34:59,285] Trial 26 finished with value: 0.7469421068076121 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 235, 'oob_score': True, 'max_samples': 0.766734838708136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07999208951911986, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 16:35:02,118] Trial 27 finished with value: 0.7510925047188961 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 206, 'oob_score': True, 'max_samples': 0.7750769539334444, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06326441457712315, 'warm_start': True}. Best is trial 25 with value: 0.7568542957468967.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 16:35:04,635] Trial 28 finished with value: 0.7651955962327717 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 15, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 228, 'oob_score': True, 'max_samples': 0.6847169156044919, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.003364807635412012, 'warm_start': True}. Best is trial 28 with value: 0.7651955962327717.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 16:35:07,722] Trial 29 finished with value: 0.7751733627229969 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 339, 'oob_score': True, 'max_samples': 0.6869904791039767, 'max_features': None, 'min_weight_fraction_leaf': 0.04113891562651206, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.

Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 16:35:10,931] Trial 30 finished with value: 0.7736629125252518 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 17, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.6833587310905035, 'max_features': None, 'min_weight_fraction_leaf': 0.008532800179007469, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 16:35:14,319] Trial 31 finished with value: 0.7735002862697369 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 379, 'oob_score': True, 'max_samples': 0.6547593902381754, 'max_features': None, 'min_weight_fraction_leaf': 0.01653304213676029, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 16:35:18,351] Trial 32 finished with value: 0.7726671170454932 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 390, 'oob_score': True, 'max_samples': 0.7011070731694715, 'max_features': None, 'min_weight_fraction_leaf': 0.002655419277963856, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7424892703862661
[I 2024-04-14 16:35:21,500] Trial 33 finished with value: 0.761951377352432 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 20, 'n_estimators': 385, 'oob_score': True, 'max_samples': 0.4871505413082745, 'max_features': None, 'min_weight_fraction_leaf': 0.0037092008636243484, 'warm_start': True}. Best is trial 29 with value: 0.7751733627229969.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 16:35:25,462] Trial 34 finished with value: 0.7772994105576999 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 6, 'max_depth': 20, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5424853541641252, 'max_features': None, 'min_weight_fraction_leaf': 0.04005993867513943, 'warm_start': True}. Best is trial 34 with value: 0.7772994105576999.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 16:35:30,433] Trial 35 finished with value: 0.7939453846462785 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 492, 'oob_score': True, 'max_samples': 0.5281329979576042, 'max_features': None, 'min_weight_fraction_leaf': 0.041799651789036885, 'warm_start': True}. Best is trial 35 with value: 0.7939453846462785.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 16:35:36,229] Trial 36 finished with value: 0.7988094200063037 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 494, 'oob_score': True, 'max_samples': 0.5475428261493075, 'max_features': None, 'min_weight_fraction_leaf': 0.04248766950155104, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8081395348837209
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:35:39,918] Trial 37 finished with value: 0.7438212214010235 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 496, 'oob_score': True, 'max_samples': 0.537628436907505, 'max_features': None, 'min_weight_fraction_leaf': 0.13505191950972878, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 16:35:43,600] Trial 38 finished with value: 0.7773251612620597 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4079124058970714, 'max_features': None, 'min_weight_fraction_leaf': 0.043050318879278446, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:35:48,840] Trial 39 finished with value: 0.734846885715039 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 499, 'oob_score': True, 'max_samples': 0.3660594506190667, 'max_features': None, 'min_weight_fraction_leaf': 0.10012332890216755, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7381974248927039
[I 2024-04-14 16:35:52,565] Trial 40 finished with value: 0.7649536724571295 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.38596283150687494, 'max_features': None, 'min_weight_fraction_leaf': 0.04061455540701541, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 16:35:56,082] Trial 41 finished with value: 0.7941370621081079 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 460, 'oob_score': True, 'max_samples': 0.5853104884542844, 'max_features': None, 'min_weight_fraction_leaf': 0.045291071200096567, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:36:00,902] Trial 42 finished with value: 0.736998260411046 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 466, 'oob_score': True, 'max_samples': 0.5547327087340422, 'max_features': None, 'min_weight_fraction_leaf': 0.15119679094835453, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8449612403100775
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 16:36:04,284] Trial 43 finished with value: 0.7838881672008012 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 430, 'oob_score': True, 'max_samples': 0.43155969103520636, 'max_features': None, 'min_weight_fraction_leaf': 0.043472744875657617, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:36:07,389] Trial 44 finished with value: 0.7399894649828315 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.4005082288778946, 'max_features': None, 'min_weight_fraction_leaf': 0.10143753014282131, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:36:08,928] Trial 45 finished with value: 0.7241222823816911 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 437, 'oob_score': False, 'max_samples': 0.25182885979889597, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08391169894605255, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:36:18,239] Trial 46 finished with value: 0.7058457110259935 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 15, 'n_estimators': 470, 'oob_score': True, 'max_samples': 0.43126650753033136, 'max_features': None, 'min_weight_fraction_leaf': 0.05341940290949464, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 16:36:19,859] Trial 47 finished with value: 0.761821383227146 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 17, 'n_estimators': 408, 'oob_score': False, 'max_samples': 0.30342154143659733, 'max_features': None, 'min_weight_fraction_leaf': 0.03559822522548907, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:36:27,484] Trial 48 finished with value: 0.7117273483913299 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 435, 'oob_score': True, 'max_samples': 0.5993264662444304, 'max_features': None, 'min_weight_fraction_leaf': 0.1243065372654003, 'warm_start': False}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:36:31,726] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 475, 'oob_score': True, 'max_samples': 0.5188442477983979, 'max_features': None, 'min_weight_fraction_leaf': 0.4820963556426466, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:36:33,550] Trial 50 finished with value: 0.737899316580976 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 5, 'max_depth': 19, 'n_estimators': 445, 'oob_score': False, 'max_samples': 0.5847268231512849, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15227204260709018, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 16:36:37,669] Trial 51 finished with value: 0.7814971781238983 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 487, 'oob_score': True, 'max_samples': 0.43199709338607994, 'max_features': None, 'min_weight_fraction_leaf': 0.03149759470389267, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 16:36:41,583] Trial 52 finished with value: 0.7567762597419098 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 478, 'oob_score': True, 'max_samples': 0.4387556889483383, 'max_features': None, 'min_weight_fraction_leaf': 0.09297907262518232, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 16:36:45,346] Trial 53 finished with value: 0.7986572561005724 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 16, 'n_estimators': 409, 'oob_score': True, 'max_samples': 0.4978232271491865, 'max_features': None, 'min_weight_fraction_leaf': 0.033781036150152696, 'warm_start': True}. Best is trial 36 with value: 0.7988094200063037.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 16:36:49,167] Trial 54 finished with value: 0.8175044273559141 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 341, 'oob_score': True, 'max_samples': 0.4961608781156207, 'max_features': None, 'min_weight_fraction_leaf': 0.025003317155411986, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.759656652360515
[I 2024-04-14 16:36:52,622] Trial 55 finished with value: 0.7750834494179615 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 331, 'oob_score': True, 'max_samples': 0.5021698171984055, 'max_features': None, 'min_weight_fraction_leaf': 0.06062440846922696, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:37:00,133] Trial 56 finished with value: 0.692159003960772 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 310, 'oob_score': True, 'max_samples': 0.6431467441559697, 'max_features': None, 'min_weight_fraction_leaf': 0.021762770810368127, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 16:37:03,516] Trial 57 finished with value: 0.7775457629433687 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 404, 'oob_score': True, 'max_samples': 0.5757175357123006, 'max_features': None, 'min_weight_fraction_leaf': 0.05830794943324037, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:37:06,936] Trial 58 finished with value: 0.5 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 356, 'oob_score': True, 'max_samples': 0.4648579376135416, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.30295661673067836, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:37:07,999] Trial 59 finished with value: 0.742832764389526 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 17, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.34319505493069397, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.08248014261229168, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:37:16,175] Trial 60 finished with value: 0.7094998068077641 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.6211328199713557, 'max_features': None, 'min_weight_fraction_leaf': 0.11070844936873359, 'warm_start': False}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8643410852713178
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 16:37:20,637] Trial 61 finished with value: 0.8036986552407976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 455, 'oob_score': True, 'max_samples': 0.5153677562911374, 'max_features': None, 'min_weight_fraction_leaf': 0.031485629345332306, 'warm_start': True}. Best is trial 54 with value: 0.8175044273559141.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 16:37:24,358] Trial 62 finished with value: 0.8182757698225179 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 457, 'oob_score': True, 'max_samples': 0.5112289023564809, 'max_features': None, 'min_weight_fraction_leaf': 0.02095528969051655, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 16:37:28,592] Trial 63 finished with value: 0.8111521115785895 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 458, 'oob_score': True, 'max_samples': 0.5100900270084606, 'max_features': None, 'min_weight_fraction_leaf': 0.018150109857069722, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.7510729613733905
[I 2024-04-14 16:37:31,977] Trial 64 finished with value: 0.7700709580629541 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.4955086388573719, 'max_features': None, 'min_weight_fraction_leaf': 0.06782578020859786, 'warm_start': True}. Best is trial 62 with value: 0.8182757698225179.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 16:37:35,945] Trial 65 finished with value: 0.8185942843287751 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 407, 'oob_score': True, 'max_samples': 0.572806842914682, 'max_features': None, 'min_weight_fraction_leaf': 0.02226915354245074, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:37:39,511] Trial 66 finished with value: 0.8160847545835782 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 400, 'oob_score': True, 'max_samples': 0.5576081908424206, 'max_features': None, 'min_weight_fraction_leaf': 0.016475143309745643, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 16:37:42,625] Trial 67 finished with value: 0.8101126972372172 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 391, 'oob_score': True, 'max_samples': 0.561957978855049, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.018288170265703986, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:37:45,301] Trial 68 finished with value: 0.8183234527679148 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.6097336917403036, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02099611885947379, 'warm_start': True}. Best is trial 65 with value: 0.8185942843287751.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8837209302325582
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8454935622317596
[I 2024-04-14 16:37:48,104] Trial 69 finished with value: 0.8272146463529724 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7318335045229435, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.017419775688352082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8936170212765957
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 16:37:51,833] Trial 70 finished with value: 0.8158063208975717 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 294, 'oob_score': True, 'max_samples': 0.6243013523451256, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.020464714362005143, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:37:54,643] Trial 71 finished with value: 0.824114421989065 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.7330924737377311, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.016575501718897302, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8808510638297873
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 16:37:57,129] Trial 72 finished with value: 0.8125646918339378 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 298, 'oob_score': True, 'max_samples': 0.7326351452640015, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0027592484745489945, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 16:37:59,402] Trial 73 finished with value: 0.8078669641918867 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 262, 'oob_score': True, 'max_samples': 0.6560932996857387, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01505215827140816, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8783269961977186
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 16:38:02,390] Trial 74 finished with value: 0.8229478737470439 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 320, 'oob_score': True, 'max_samples': 0.8040957518239317, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024607026709667742, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6931330472103004
[I 2024-04-14 16:38:05,286] Trial 75 finished with value: 0.7297534394801531 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 322, 'oob_score': True, 'max_samples': 0.8244077376700942, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2738762867283342, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8488372093023255
Fold 3 C-index: 0.8723404255319149
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 16:38:07,995] Trial 76 finished with value: 0.8005224502929792 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 353, 'oob_score': True, 'max_samples': 0.7779027631332152, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06198954175038082, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8565891472868217
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 16:38:10,078] Trial 77 finished with value: 0.8054911364827252 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 283, 'oob_score': True, 'max_samples': 0.7444363178817063, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.00391494572036042, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.851063829787234
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7639484978540773
[I 2024-04-14 16:38:12,650] Trial 78 finished with value: 0.7766506135263602 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 369, 'oob_score': True, 'max_samples': 0.7964582770234238, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08072526041027032, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8595744680851064
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 16:38:13,746] Trial 79 finished with value: 0.7952779202339323 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 311, 'oob_score': False, 'max_samples': 0.618087421106259, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02724887288178213, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.6716738197424893
[I 2024-04-14 16:38:17,738] Trial 80 finished with value: 0.7109603094858263 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 250, 'oob_score': True, 'max_samples': 0.6608918473113886, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22754786457763954, 'warm_start': False}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.902127659574468
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:38:20,116] Trial 81 finished with value: 0.823191212472951 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 334, 'oob_score': True, 'max_samples': 0.7181496469643299, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.01833632174034757, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8527131782945736
Fold 3 C-index: 0.8765957446808511
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 16:38:23,172] Trial 82 finished with value: 0.8055458278408263 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 342, 'oob_score': True, 'max_samples': 0.718648090454236, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05194443679311898, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.8682170542635659
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 16:38:26,158] Trial 83 finished with value: 0.812684350596275 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 324, 'oob_score': True, 'max_samples': 0.7502215626294254, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.011526440379393736, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8412017167381974
[I 2024-04-14 16:38:28,891] Trial 84 finished with value: 0.8232844098456795 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 364, 'oob_score': True, 'max_samples': 0.8395867498100796, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.024617503790133055, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8410852713178295
Fold 3 C-index: 0.8680851063829788
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 16:38:31,578] Trial 85 finished with value: 0.7921991713994829 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 368, 'oob_score': True, 'max_samples': 0.8857836580094625, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07264997820097252, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 16:38:34,395] Trial 86 finished with value: 0.8224086969713147 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 337, 'oob_score': True, 'max_samples': 0.9236490757653891, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05091910924778117, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:38:37,079] Trial 87 finished with value: 0.7444219877257969 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.8360547528312109, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05159081964644253, 'warm_start': True}. Best is trial 69 with value: 0.8272146463529724.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9234042553191489
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 16:38:39,548] Trial 88 finished with value: 0.8299957447925681 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6373390557939914
[I 2024-04-14 16:38:41,868] Trial 89 finished with value: 0.6984552187416074 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9606865260369674, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.42980933716176023, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.8893617021276595
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8583690987124464
[I 2024-04-14 16:38:45,307] Trial 90 finished with value: 0.8168638261621636 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 333, 'oob_score': True, 'max_samples': 0.8970982407350513, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0033122441195345426, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.875968992248062
Fold 3 C-index: 0.9106382978723404
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8497854077253219
[I 2024-04-14 16:38:48,264] Trial 91 finished with value: 0.8288039966760785 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.8500705105869577, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.02769924772148816, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8798449612403101
Fold 3 C-index: 0.9191489361702128
Fold 4 C-index: 0.8821292775665399
Fold 5 C-index: 0.8540772532188842
[I 2024-04-14 16:38:50,858] Trial 92 finished with value: 0.828952436236799 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 299, 'oob_score': True, 'max_samples': 0.9318910170313084, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03466207519046283, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8875968992248062
Fold 3 C-index: 0.9148936170212766
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 16:38:55,648] Trial 93 finished with value: 0.8246721711870638 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 302, 'oob_score': True, 'max_samples': 0.9237402520498113, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.051627897348460114, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 16:38:58,525] Trial 94 finished with value: 0.7774842065936604 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 300, 'oob_score': True, 'max_samples': 0.9315755472196319, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.09044268069913194, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.872093023255814
Fold 3 C-index: 0.8978723404255319
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 16:39:00,854] Trial 95 finished with value: 0.8149658464044028 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 305, 'oob_score': True, 'max_samples': 0.9428489419934195, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05519942461860093, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:39:03,025] Trial 96 finished with value: 0.7343217686472692 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 18, 'n_estimators': 255, 'oob_score': True, 'max_samples': 0.8550701905177472, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07090475670535565, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8174904942965779
Fold 5 C-index: 0.7553648068669528
[I 2024-04-14 16:39:04,213] Trial 97 finished with value: 0.7709719977986227 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 285, 'oob_score': False, 'max_samples': 0.9118193987076412, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.035787567288930885, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:39:06,962] Trial 98 finished with value: 0.7298807893419987 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 17, 'n_estimators': 274, 'oob_score': True, 'max_samples': 0.9222109032849816, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04727690829808437, 'warm_start': True}. Best is trial 88 with value: 0.8299957447925681.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7395437262357415

[I 2024-04-14 16:39:12,409] A new study created in memory with name: no-name-0efeeaf6-b747-4283-8e30-6c95bbc7165b

Fold 5 C-index: 0.6759656652360515
[I 2024-04-14 16:39:12,390] Trial 99 finished with value: 0.7070161831399606 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 348, 'oob_score': True, 'max_samples': 0.9759793763474963, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3521412865651261, 'warm_start': False}. Best is trial 88 with value: 0.8299957447925681.


* Best trial for C-index:
 FrozenTrial(number=88, state=TrialState.COMPLETE, values=[0.8299957447925681], datetime_start=datetime.datetime(2024, 4, 14, 16, 38, 37, 91001), datetime_complete=datetime.datetime(2024, 4, 14, 16, 38, 39, 547773), params={'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 318, 'oob_score': True, 'max_samples': 0.9059465751594485, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.029068528038335394, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=88, value=None)


* Best Score for C-index:
 0.8299957447925681

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.22407713995563355
Fold 2 IBS: 0.17470488039835566
Fold 3 IBS: 0.2398383923527903
Fold 4 IBS: 0.20906561324773706
Fold 5 IBS: 0.2195728796491891
[I 2024-04-14 16:39:17,719] Trial 0 finished with value: 0.21345178112074117 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.21345178112074117.
Fold 1 IBS: 0.21616660020333003
Fold 2 IBS: 0.17486525786616586
Fold 3 IBS: 0.2107106205384323
Fold 4 IBS: 0.20216950628891073
Fold 5 IBS: 0.21532298657498944
[I 2024-04-14 16:39:18,867] Trial 1 finished with value: 0.20384699429436565 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-14 16:39:19,708] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-14 16:39:22,763] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-14 16:39:25,917] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24936759596080646
Fold 2 IBS: 0.17264271046131205
Fold 3 IBS: 0.20421070451417014
Fold 4 IBS: 0.21666312222005965
Fold 5 IBS: 0.21221582754312004
[I 2024-04-14 16:39:29,892] Trial 5 finished with value: 0.2110199921398937 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21621830894948232
Fold 2 IBS: 0.18912437295998735
Fold 3 IBS: 0.25661481391845226
Fold 4 IBS: 0.20519890764061255
Fold 5 IBS: 0.21737176566006436
[I 2024-04-14 16:39:34,934] Trial 6 finished with value: 0.21690563382571976 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.239725565259837
Fold 2 IBS: 0.22117477833066543
Fold 3 IBS: 0.22403481418923998
Fold 4 IBS: 0.2325927375141085
Fold 5 IBS: 0.22473498221278954
[I 2024-04-14 16:39:39,519] Trial 7 finished with value: 0.22845257550132808 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-14 16:39:47,630] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22659514067603376
Fold 2 IBS: 0.17851765630325647
Fold 3 IBS: 0.2013246121030424
Fold 4 IBS: 0.20963921105379285
Fold 5 IBS: 0.2203202485023523
[I 2024-04-14 16:39:50,009] Trial 9 finished with value: 0.2072793737276956 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-14 16:39:53,997] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2540107203940081
Fold 2 IBS: 0.19018193572283806
Fold 3 IBS: 0.2693108522338297
Fold 4 IBS: 0.2204494801684996
Fold 5 IBS: 0.22801293569526146
[I 2024-04-14 16:39:54,237] Trial 11 finished with value: 0.23239318484288743 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.9899815471614337, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17706129541113583}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23986882649245242
Fold 2 IBS: 0.17667107107700725
Fold 3 IBS: 0.19675890006825608
Fold 4 IBS: 0.21136980755566645
Fold 5 IBS: 0.21659638264865502
[I 2024-04-14 16:39:55,984] Trial 12 finished with value: 0.20825299756840746 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 13, 'max_depth': 19, 'n_estimators': 126, 'oob_score': False, 'max_samples': 0.838341657174724, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.007007532608717559}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22478082430068405
Fold 2 IBS: 0.17185450852530715
Fold 3 IBS: 0.21027987039395774
Fold 4 IBS: 0.20018219852324562
Fold 5 IBS: 0.21753825326760137
[I 2024-04-14 16:39:57,313] Trial 13 finished with value: 0.2049271310021592 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 8, 'n_estimators': 100, 'oob_score': False, 'max_samples': 0.964999799603621, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2691953450690723}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21998167437826233
Fold 2 IBS: 0.18978207675252776
Fold 3 IBS: 0.2156881327568739
Fold 4 IBS: 0.20498945225014242
Fold 5 IBS: 0.2158332545660207
[I 2024-04-14 16:39:58,140] Trial 14 finished with value: 0.2092549181407654 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7347591488544951, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2812321272168262}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24379041704605284
Fold 2 IBS: 0.16804912162483507
Fold 3 IBS: 0.2051845606137616
Fold 4 IBS: 0.20906885042686352
Fold 5 IBS: 0.2130970650630231
[I 2024-04-14 16:40:00,633] Trial 15 finished with value: 0.20783800295490723 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.9966433181385008, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13541305845514623}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.24681956605569497
Fold 2 IBS: 0.23227093172764388
Fold 3 IBS: 0.22941903729651647
Fold 4 IBS: 0.24121738904572626
Fold 5 IBS: 0.2302321253386658
[I 2024-04-14 16:40:02,884] Trial 16 finished with value: 0.2359918098928495 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 162, 'oob_score': False, 'max_samples': 0.32587405036023415, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3357318242102959}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2231111330848275
Fold 2 IBS: 0.17656419065238982
Fold 3 IBS: 0.20901589415087424
Fold 4 IBS: 0.20307733734686217
Fold 5 IBS: 0.21545535438507316
[I 2024-04-14 16:40:09,204] Trial 17 finished with value: 0.20544478192400537 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 11, 'max_depth': 5, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8324456438302156, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2527008941020278}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23532815608885377
Fold 2 IBS: 0.1837655560742492
Fold 3 IBS: 0.20262687562645237
Fold 4 IBS: 0.2122206984989701
Fold 5 IBS: 0.2166747901565821
[I 2024-04-14 16:40:10,183] Trial 18 finished with value: 0.21012321528902148 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 1, 'n_estimators': 48, 'oob_score': True, 'max_samples': 0.6751019433313558, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11276726622420546}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22863054693293589
Fold 2 IBS: 0.1963315773237213
Fold 3 IBS: 0.21471249390143013
Fold 4 IBS: 0.219881142418457
Fold 5 IBS: 0.22152453289806817
[I 2024-04-14 16:40:10,631] Trial 19 finished with value: 0.21621605869492252 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 5, 'n_estimators': 10, 'oob_score': False, 'max_samples': 0.756071359635432, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.32595449578288455}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22537941330506062
Fold 2 IBS: 0.19227308793145745
Fold 3 IBS: 0.21265991721222577
Fold 4 IBS: 0.20917597176350836
Fold 5 IBS: 0.21687868662201695
[I 2024-04-14 16:40:12,448] Trial 20 finished with value: 0.21127341536685385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 10, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.6036734235439312, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.23857721033918533}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22324770605725813
Fold 2 IBS: 0.18253846781709399
Fold 3 IBS: 0.2045169037430424
Fold 4 IBS: 0.20783876653003266
Fold 5 IBS: 0.2175938501921847
[I 2024-04-14 16:40:18,422] Trial 21 finished with value: 0.20714713886792238 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 491, 'oob_score': False, 'max_samples': 0.8230570050888841, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2722629100041059}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24383129660582778
Fold 2 IBS: 0.16931429481145502
Fold 3 IBS: 0.20516950235518827
Fold 4 IBS: 0.20489042671888189
Fold 5 IBS: 0.21168593869445076
[I 2024-04-14 16:40:24,804] Trial 22 finished with value: 0.20697829183716077 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 483, 'oob_score': False, 'max_samples': 0.9080266581136552, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1738640799325239}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22798058234299892
Fold 2 IBS: 0.17066187178067507
Fold 3 IBS: 0.20762316176929713
Fold 4 IBS: 0.20163711855316047
Fold 5 IBS: 0.21357666387653937
[I 2024-04-14 16:40:30,219] Trial 23 finished with value: 0.20429587966453416 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 341, 'oob_score': False, 'max_samples': 0.918144892067728, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22593418563490295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2333417951219333
Fold 2 IBS: 0.1700982573355749
Fold 3 IBS: 0.20661966502631599
Fold 4 IBS: 0.20215860951935866
Fold 5 IBS: 0.21369121522055837
[I 2024-04-14 16:40:34,711] Trial 24 finished with value: 0.20518190844474823 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'max_samples': 0.9261452409044857, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2150416825146331}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2302095064014022
Fold 2 IBS: 0.20489193018995322
Fold 3 IBS: 0.22229468418463336
Fold 4 IBS: 0.22315856362376232
Fold 5 IBS: 0.22270247922464476
[I 2024-04-14 16:40:38,165] Trial 25 finished with value: 0.22065143272487914 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 9, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.7754756321225551, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37858736351418476}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24622588582203958
Fold 2 IBS: 0.23225616799196488
Fold 3 IBS: 0.22961130014021525
Fold 4 IBS: 0.24150610351006122
Fold 5 IBS: 0.23015340332834447
[I 2024-04-14 16:40:45,145] Trial 26 finished with value: 0.23595057215852505 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 20, 'max_depth': 6, 'n_estimators': 410, 'oob_score': True, 'max_samples': 0.44732517583857423, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30573135880353774}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24371312366354173
Fold 2 IBS: 0.17009470168949176
Fold 3 IBS: 0.20387614537935278
Fold 4 IBS: 0.2063297018706307
Fold 5 IBS: 0.21225767577269047
[I 2024-04-14 16:40:50,113] Trial 27 finished with value: 0.20725426967514146 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 16, 'n_estimators': 309, 'oob_score': False, 'max_samples': 0.9264498293472653, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16408374861729386}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24230033744905524
Fold 2 IBS: 0.1700083907734053
Fold 3 IBS: 0.20307970499577657
Fold 4 IBS: 0.21056222306350966
Fold 5 IBS: 0.21225464745768113
[I 2024-04-14 16:40:53,665] Trial 28 finished with value: 0.20764106074788558 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 237, 'oob_score': False, 'max_samples': 0.6539680943502474, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11167707604899824}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24611993726989195
Fold 2 IBS: 0.23218890990534718
Fold 3 IBS: 0.23048044870725193
Fold 4 IBS: 0.2410683146218637
Fold 5 IBS: 0.2299160122305334
[I 2024-04-14 16:41:00,112] Trial 29 finished with value: 0.23595472454697766 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 384, 'oob_score': False, 'max_samples': 0.11354273074199811, 'max_features': None, 'min_weight_fraction_leaf': 0.23506901120045084}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22660818914056846
Fold 2 IBS: 0.17199394890259848
Fold 3 IBS: 0.20974235645980502
Fold 4 IBS: 0.20527990803227994
Fold 5 IBS: 0.2142164886689667
[I 2024-04-14 16:41:04,930] Trial 30 finished with value: 0.2055681782408437 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 2, 'n_estimators': 164, 'oob_score': False, 'max_samples': 0.7841568813969919, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19739729582328963}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.23708578217070322
Fold 2 IBS: 0.17051603032060797
Fold 3 IBS: 0.2048697308529193
Fold 4 IBS: 0.20307497656561538
Fold 5 IBS: 0.21255249060044212
[I 2024-04-14 16:41:11,670] Trial 31 finished with value: 0.20561980210205758 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 339, 'oob_score': False, 'max_samples': 0.9431792460514251, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20474531091370285}. Best is trial 1 with value: 0.20384699429436565.

Fold 1 IBS: 0.22612682993385486
Fold 2 IBS: 0.17223298934748948
Fold 3 IBS: 0.20782358499736456
Fold 4 IBS: 0.20181112716562463
Fold 5 IBS: 0.21350833459590543
[I 2024-04-14 16:41:18,110] Trial 32 finished with value: 0.2043005732080478 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.8753375341925101, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2230974552568295}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22177687649658975
Fold 2 IBS: 0.17630377861515312
Fold 3 IBS: 0.2122309287307206
Fold 4 IBS: 0.2017574245411477
Fold 5 IBS: 0.21470545803951144
[I 2024-04-14 16:41:22,739] Trial 33 finished with value: 0.20535489328462447 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.8780403780133842, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26554839348030423}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2347950025150411
Fold 2 IBS: 0.16799406158735225
Fold 3 IBS: 0.2119268936202999
Fold 4 IBS: 0.1995017747896286
Fold 5 IBS: 0.21645738910312
[I 2024-04-14 16:41:24,655] Trial 34 finished with value: 0.2061350243230884 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 11, 'n_estimators': 80, 'oob_score': True, 'max_samples': 0.9713620300267395, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22449252311835874}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2184171866823885
Fold 2 IBS: 0.18340292802030164
Fold 3 IBS: 0.24622741065146023
Fold 4 IBS: 0.21030733491515133
Fold 5 IBS: 0.218874594617978
[I 2024-04-14 16:41:28,176] Trial 35 finished with value: 0.21544589097745592 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 219, 'oob_score': False, 'max_samples': 0.8006724007383993, 'max_features': None, 'min_weight_fraction_leaf': 0.2991859225334826}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24658618602469104
Fold 2 IBS: 0.2321884009769192
Fold 3 IBS: 0.2295721257429426
Fold 4 IBS: 0.24149932745394134
Fold 5 IBS: 0.23037083343869663
[I 2024-04-14 16:41:32,299] Trial 36 finished with value: 0.23604337472743814 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.7142345385665702, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44701099039110287}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.24597601805501332
Fold 2 IBS: 0.16679544014249023
Fold 3 IBS: 0.2291560830967934
Fold 4 IBS: 0.21774129632473188
Fold 5 IBS: 0.21808816775530818
[I 2024-04-14 16:41:38,949] Trial 37 finished with value: 0.21555140107486742 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 14, 'n_estimators': 380, 'oob_score': False, 'max_samples': 0.8893387526179963, 'max_features': None, 'min_weight_fraction_leaf': 0.05558599763353947}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.22361789070615487
Fold 2 IBS: 0.17833589878764333
Fold 3 IBS: 0.20797628674399748
Fold 4 IBS: 0.20706581092390064
Fold 5 IBS: 0.21475624911298768
[I 2024-04-14 16:41:48,192] Trial 38 finished with value: 0.2063504272549368 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 444, 'oob_score': True, 'max_samples': 0.48823423037203917, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10676050487618188}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.2465964694944807
Fold 2 IBS: 0.23221073187531344
Fold 3 IBS: 0.22950988130319463
Fold 4 IBS: 0.241408499161141
Fold 5 IBS: 0.23022625655373033
[I 2024-04-14 16:41:53,826] Trial 39 finished with value: 0.235990367677572 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 313, 'oob_score': False, 'max_samples': 0.5771239750792474, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3646319374122424}. Best is trial 1 with value: 0.20384699429436565.
Fold 1 IBS: 0.21647863712170887
Fold 2 IBS: 0.17199966700669284
Fold 3 IBS: 0.19869719848871478
Fold 4 IBS: 0.20796789999763218
Fold 5 IBS: 0.21625226939504177
[I 2024-04-14 16:41:54,614] Trial 40 finished with value: 0.2022791344019581 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 32, 'oob_score': False, 'max_samples': 0.7017810474930685, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15131446570826318}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22134427216375058
Fold 2 IBS: 0.1760712729646329
Fold 3 IBS: 0.19474566426704223
Fold 4 IBS: 0.21163414366897387
Fold 5 IBS: 0.21799528858603973
[I 2024-04-14 16:41:55,407] Trial 41 finished with value: 0.20435812833008785 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.6851330046079013, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1415472492884433}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21730762926082742
Fold 2 IBS: 0.17880052942015828
Fold 3 IBS: 0.19466820609343688
Fold 4 IBS: 0.20919417870986243
Fold 5 IBS: 0.2175415352637051
[I 2024-04-14 16:41:55,997] Trial 42 finished with value: 0.20350241574959801 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 11, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.6932739851311275, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14781080589948162}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2266914017789978
Fold 2 IBS: 0.18902598179814228
Fold 3 IBS: 0.1886797492652457
Fold 4 IBS: 0.21746952054591362
Fold 5 IBS: 0.21485690053973838
[I 2024-04-14 16:41:56,691] Trial 43 finished with value: 0.20734471078560754 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 11, 'n_estimators': 26, 'oob_score': False, 'max_samples': 0.6230606164996372, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17300117076396285}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2263300301352394
Fold 2 IBS: 0.17228759968501195
Fold 3 IBS: 0.20727538565975506
Fold 4 IBS: 0.20619156167481315
Fold 5 IBS: 0.2151350980475268
[I 2024-04-14 16:41:58,350] Trial 44 finished with value: 0.20544393504046926 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.5383399306130238, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07137280133151601}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2195259426238762
Fold 2 IBS: 0.17176930604867915
Fold 3 IBS: 0.21264489605286027
Fold 4 IBS: 0.2026960468857599
Fold 5 IBS: 0.2155061220972602
[I 2024-04-14 16:41:59,563] Trial 45 finished with value: 0.20442846274168716 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 14, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7211266599729008, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08955966829076284}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.24664109906894663
Fold 2 IBS: 0.23211151536965932
Fold 3 IBS: 0.22921725039634813
Fold 4 IBS: 0.24155332248199884
Fold 5 IBS: 0.2300252715829934
[I 2024-04-14 16:42:03,732] Trial 46 finished with value: 0.23590969177998927 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 132, 'oob_score': True, 'max_samples': 0.4955610125060993, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.4987000897606556}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22677458805979425
Fold 2 IBS: 0.18128534484285147
Fold 3 IBS: 0.20359451039074664
Fold 4 IBS: 0.21860313764199735
Fold 5 IBS: 0.21528256346964708
[I 2024-04-14 16:42:04,304] Trial 47 finished with value: 0.20910802888100735 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 17, 'oob_score': False, 'max_samples': 0.6381469780315093, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15711696604627562}. Best is trial 40 with value: 0.2022791344019581.

Fold 1 IBS: 0.23790435513187447
Fold 2 IBS: 0.16917310562036944
Fold 3 IBS: 0.2032724536335342
Fold 4 IBS: 0.20275263571784216
Fold 5 IBS: 0.21198800508925086
[I 2024-04-14 16:42:10,738] Trial 48 finished with value: 0.20501811103857426 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 10, 'n_estimators': 369, 'oob_score': False, 'max_samples': 0.862646612475437, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18882619674434536}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21643739431200149
Fold 2 IBS: 0.18002210069568697
Fold 3 IBS: 0.20963559196115233
Fold 4 IBS: 0.20201711337877098
Fold 5 IBS: 0.21711926927169345
[I 2024-04-14 16:42:12,111] Trial 49 finished with value: 0.20504629392386103 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 7, 'n_estimators': 68, 'oob_score': False, 'max_samples': 0.712240935894755, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03279359667752256}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21970666197039673
Fold 2 IBS: 0.17845771406023855
Fold 3 IBS: 0.20885143473324186
Fold 4 IBS: 0.20319913155933902
Fold 5 IBS: 0.2153595741585475
[I 2024-04-14 16:42:18,238] Trial 50 finished with value: 0.2051149032963527 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 16, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.581277730850803, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13970814386185937}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21850000381456347
Fold 2 IBS: 0.17736923091725895
Fold 3 IBS: 0.20498374840747066
Fold 4 IBS: 0.2021359588037073
Fold 5 IBS: 0.21987202711845588
[I 2024-04-14 16:42:19,645] Trial 51 finished with value: 0.20457219381229125 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 37, 'oob_score': False, 'max_samples': 0.6824265755354791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13000278013180866}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21997861326285056
Fold 2 IBS: 0.17510133496874586
Fold 3 IBS: 0.20782135929983414
Fold 4 IBS: 0.20318340455059253
Fold 5 IBS: 0.21807100804623603
[I 2024-04-14 16:42:20,766] Trial 52 finished with value: 0.20483114402565183 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 39, 'oob_score': False, 'max_samples': 0.7595422741248538, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1492553835770421}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.20187641777839058
Fold 2 IBS: 0.21697708771949703
Fold 3 IBS: 0.2594495566549233
Fold 4 IBS: 0.2052587865188469
Fold 5 IBS: 0.22918402151273276
[I 2024-04-14 16:42:21,224] Trial 53 finished with value: 0.22254917403687813 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7063377467137641, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12053402761378912}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2163446023224957
Fold 2 IBS: 0.17212550764211373
Fold 3 IBS: 0.21160944290207245
Fold 4 IBS: 0.20512480185219015
Fold 5 IBS: 0.2160354664693132
[I 2024-04-14 16:42:22,321] Trial 54 finished with value: 0.20424796423763705 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 59, 'oob_score': False, 'max_samples': 0.6746935555292785, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0904689651104114}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22967201163797166
Fold 2 IBS: 0.17176959330058167
Fold 3 IBS: 0.20224897452635443
Fold 4 IBS: 0.20289718637619525
Fold 5 IBS: 0.21350582751457162
[I 2024-04-14 16:42:24,559] Trial 55 finished with value: 0.2040187186711349 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 135, 'oob_score': False, 'max_samples': 0.8028424541436651, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18708342016220178}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2329914623588844
Fold 2 IBS: 0.1709218692606976
Fold 3 IBS: 0.2022628895427006
Fold 4 IBS: 0.2037428253059489
Fold 5 IBS: 0.21379783296488847
[I 2024-04-14 16:42:27,309] Trial 56 finished with value: 0.204743375886624 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 143, 'oob_score': False, 'max_samples': 0.8015891614775278, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08443475399948225}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22222933862075872
Fold 2 IBS: 0.17307243696245472
Fold 3 IBS: 0.2076841617030592
Fold 4 IBS: 0.20227550999755373
Fold 5 IBS: 0.21586625145405466
[I 2024-04-14 16:42:30,154] Trial 57 finished with value: 0.2042255397475762 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 109, 'oob_score': True, 'max_samples': 0.6308231363037688, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04742769018003304}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2456168604122806
Fold 2 IBS: 0.1720780186944042
Fold 3 IBS: 0.1939891166776255
Fold 4 IBS: 0.21652289584699036
Fold 5 IBS: 0.21111767529637926
[I 2024-04-14 16:42:33,745] Trial 58 finished with value: 0.207864913385536 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 105, 'oob_score': True, 'max_samples': 0.6079842908829092, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04294499138204588}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22124664269345137
Fold 2 IBS: 0.17562069103113492
Fold 3 IBS: 0.2089041573304958
Fold 4 IBS: 0.20473650596918874
Fold 5 IBS: 0.2141094172536013
[I 2024-04-14 16:42:36,987] Trial 59 finished with value: 0.20492348285557443 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 2, 'n_estimators': 189, 'oob_score': True, 'max_samples': 0.6538044546332764, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.02711344752535265}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2181513360924439
Fold 2 IBS: 0.17768472605175628
Fold 3 IBS: 0.21223044737111443
Fold 4 IBS: 0.20136958313815562
Fold 5 IBS: 0.21615046674907337
[I 2024-04-14 16:42:38,408] Trial 60 finished with value: 0.20511731188050875 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 11, 'n_estimators': 84, 'oob_score': True, 'max_samples': 0.7478284186818124, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.006650389537996307}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23118626942195483
Fold 2 IBS: 0.1702053994866854
Fold 3 IBS: 0.2129030925098888
Fold 4 IBS: 0.19903740475703263
Fold 5 IBS: 0.2136572303984417
[I 2024-04-14 16:42:39,400] Trial 61 finished with value: 0.20539787931480066 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.830509938904831, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1023742346219489}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2205940046318535
Fold 2 IBS: 0.17584334134448318
Fold 3 IBS: 0.20675620555477245
Fold 4 IBS: 0.20426009333569892
Fold 5 IBS: 0.216570869801864
[I 2024-04-14 16:42:41,031] Trial 62 finished with value: 0.20480490293373438 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 102, 'oob_score': True, 'max_samples': 0.6818329215138573, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18242157905770487}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.23169425244220557
Fold 2 IBS: 0.17140668425310054
Fold 3 IBS: 0.19908163234934842
Fold 4 IBS: 0.20893662933440016

Fold 5 IBS: 0.21281753768850425
[I 2024-04-14 16:42:42,772] Trial 63 finished with value: 0.20478734721351177 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 145, 'oob_score': False, 'max_samples': 0.5771231216606082, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05763095148942208}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21904071817956408
Fold 2 IBS: 0.17322770907939164
Fold 3 IBS: 0.21071337338690455
Fold 4 IBS: 0.20198953222034577
Fold 5 IBS: 0.21531568867352077
[I 2024-04-14 16:42:43,804] Trial 64 finished with value: 0.20405740430794536 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 74, 'oob_score': False, 'max_samples': 0.6331344922813995, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1612709153840626}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2211019166635484
Fold 2 IBS: 0.17526371579768263
Fold 3 IBS: 0.20774379356238173
Fold 4 IBS: 0.20424362266236684
Fold 5 IBS: 0.21480184651012801
[I 2024-04-14 16:42:45,653] Trial 65 finished with value: 0.2046309790392215 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 121, 'oob_score': False, 'max_samples': 0.6350728460096916, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1631502901267459}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22198736886877768
Fold 2 IBS: 0.19061491871912364
Fold 3 IBS: 0.21827968226635633
Fold 4 IBS: 0.2052006534517124
Fold 5 IBS: 0.21613440335803383
[I 2024-04-14 16:42:47,422] Trial 66 finished with value: 0.21044340533280076 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 70, 'oob_score': True, 'max_samples': 0.5218576422719642, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19995250145835095}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2179075292069881
Fold 2 IBS: 0.18413396774995214
Fold 3 IBS: 0.20963049043297036
Fold 4 IBS: 0.20746418192466917
Fold 5 IBS: 0.21676539015107638
[I 2024-04-14 16:42:48,568] Trial 67 finished with value: 0.20718031189313124 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 52, 'oob_score': False, 'max_samples': 0.6169103339039868, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.0952902999587806}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2265700266034037
Fold 2 IBS: 0.18276032311436483
Fold 3 IBS: 0.2042864418492306
Fold 4 IBS: 0.20936741747437496
Fold 5 IBS: 0.21564455337157445
[I 2024-04-14 16:42:49,166] Trial 68 finished with value: 0.20772575248258968 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 18, 'oob_score': False, 'max_samples': 0.7428544401290184, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.07523325642012642}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2317749634162734
Fold 2 IBS: 0.1684381693450842
Fold 3 IBS: 0.23424060778843453
Fold 4 IBS: 0.21328093521325694
Fold 5 IBS: 0.21962511519703135
[I 2024-04-14 16:42:51,003] Trial 69 finished with value: 0.2134719581920161 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 2, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.6630802195286096, 'max_features': None, 'min_weight_fraction_leaf': 0.12509688782986045}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21940762796898436
Fold 2 IBS: 0.17406140071679074
Fold 3 IBS: 0.21074986909040594
Fold 4 IBS: 0.20255362262736462
Fold 5 IBS: 0.2145647222877615
[I 2024-04-14 16:42:52,429] Trial 70 finished with value: 0.20426744853826145 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 9, 'n_estimators': 91, 'oob_score': False, 'max_samples': 0.6927913414061104, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1491330560760582}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22012016394475659
Fold 2 IBS: 0.17475427785134492
Fold 3 IBS: 0.21014966656305184
Fold 4 IBS: 0.20376747945979912
Fold 5 IBS: 0.21541417348684497
[I 2024-04-14 16:42:53,851] Trial 71 finished with value: 0.2048411522611595 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.6845803813000064, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1523838280114369}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2216865262329327
Fold 2 IBS: 0.17268198910660865
Fold 3 IBS: 0.21309572839002539
Fold 4 IBS: 0.20002188205239937
Fold 5 IBS: 0.2166664932944772
[I 2024-04-14 16:42:54,947] Trial 72 finished with value: 0.20483052381528868 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 9, 'n_estimators': 70, 'oob_score': False, 'max_samples': 0.7721996477240339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17006714738018724}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2204717268372329
Fold 2 IBS: 0.18965023421922483
Fold 3 IBS: 0.21023281503750718
Fold 4 IBS: 0.20732383670369434
Fold 5 IBS: 0.21359155179608108
[I 2024-04-14 16:42:55,621] Trial 73 finished with value: 0.20825403291874806 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 44, 'oob_score': False, 'max_samples': 0.60377148666791, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12161104496600006}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2191586477412759
Fold 2 IBS: 0.17078013242114562
Fold 3 IBS: 0.20927963366535351
Fold 4 IBS: 0.20258237972300233
Fold 5 IBS: 0.2149257258484936
[I 2024-04-14 16:42:56,654] Trial 74 finished with value: 0.2033453038798542 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7304174393685703, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18556210671805792}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.21830414363737688
Fold 2 IBS: 0.17720271112298439
Fold 3 IBS: 0.20697150533408146
Fold 4 IBS: 0.20250876743216076
Fold 5 IBS: 0.2152601673419393
[I 2024-04-14 16:42:58,023] Trial 75 finished with value: 0.20404945897370858 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 113, 'oob_score': False, 'max_samples': 0.6468801596739339, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18546007907051182}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22430380108574707
Fold 2 IBS: 0.18306897497858327
Fold 3 IBS: 0.20464475027408288
Fold 4 IBS: 0.21223544052441004
Fold 5 IBS: 0.21727837802511207
[I 2024-04-14 16:43:00,014] Trial 76 finished with value: 0.20830626897758706 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 158, 'oob_score': False, 'max_samples': 0.7294723925670973, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24992337115768753}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22302173389184585
Fold 2 IBS: 0.1887176942510202
Fold 3 IBS: 0.20967732423927182
Fold 4 IBS: 0.20791001510644727
Fold 5 IBS: 0.21680578739397888
[I 2024-04-14 16:43:02,424] Trial 77 finished with value: 0.2092265109765128 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 117, 'oob_score': False, 'max_samples': 0.5629198845457468, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2128668242174557}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2239900710700344
Fold 2 IBS: 0.1698615839561287
Fold 3 IBS: 0.2095547190098964
Fold 4 IBS: 0.2012069680997044
Fold 5 IBS: 0.21613576683580699
[I 2024-04-14 16:43:03,793] Trial 78 finished with value: 0.20414982179431415 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 75, 'oob_score': True, 'max_samples': 0.798025512896543, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.187406229874218}. Best is trial 40 with value: 0.2022791344019581.

Fold 1 IBS: 0.22242518635376562
Fold 2 IBS: 0.17356537149199874
Fold 3 IBS: 0.19348965127184473
Fold 4 IBS: 0.20729301862706373
Fold 5 IBS: 0.21518309439089522
[I 2024-04-14 16:43:04,333] Trial 79 finished with value: 0.2023912644271136 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.7940170614934956, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19696931079449848}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2449767955817733
Fold 2 IBS: 0.172095460075217
Fold 3 IBS: 0.21463433607213933
Fold 4 IBS: 0.21510140082957746
Fold 5 IBS: 0.21527266884222518
[I 2024-04-14 16:43:05,188] Trial 80 finished with value: 0.21241613228018644 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 6, 'n_estimators': 28, 'oob_score': False, 'max_samples': 0.8170871700419534, 'max_features': None, 'min_weight_fraction_leaf': 0.21125680575069572}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22348296120259534
Fold 2 IBS: 0.16980207668047606
Fold 3 IBS: 0.21009370900921706
Fold 4 IBS: 0.20191156961895484
Fold 5 IBS: 0.21613576683580699
[I 2024-04-14 16:43:06,403] Trial 81 finished with value: 0.20428521666941007 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 75, 'oob_score': False, 'max_samples': 0.7971516901362177, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18138610915926726}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.2561856444522722
Fold 2 IBS: 0.1673967931519715
Fold 3 IBS: 0.20047088391888304
Fold 4 IBS: 0.21074651924541707
Fold 5 IBS: 0.2099772553369716
[I 2024-04-14 16:43:06,755] Trial 82 finished with value: 0.20895541922110308 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 11, 'oob_score': False, 'max_samples': 0.8399824689482805, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19201377617331056}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22426305056629034
Fold 2 IBS: 0.18300755389928863
Fold 3 IBS: 0.20718971819956258
Fold 4 IBS: 0.20479720064549958
Fold 5 IBS: 0.21619343342523623
[I 2024-04-14 16:43:07,544] Trial 83 finished with value: 0.20709019134717543 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 45, 'oob_score': False, 'max_samples': 0.7653436422440136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24531020078321944}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22467801181967628
Fold 2 IBS: 0.17100965075590382
Fold 3 IBS: 0.20899248385281644
Fold 4 IBS: 0.20131690199114788
Fold 5 IBS: 0.21546837157592233
[I 2024-04-14 16:43:08,896] Trial 84 finished with value: 0.20429308399909335 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 84, 'oob_score': False, 'max_samples': 0.7307213180337556, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16397999497171722}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22483109101566637
Fold 2 IBS: 0.17542630441342943
Fold 3 IBS: 0.207300694612249
Fold 4 IBS: 0.20406653897060492
Fold 5 IBS: 0.2158305961193959
[I 2024-04-14 16:43:11,264] Trial 85 finished with value: 0.2054910450262691 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.7826456215522579, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22924983418535252}. Best is trial 40 with value: 0.2022791344019581.
Fold 1 IBS: 0.22386484118726915
Fold 2 IBS: 0.17019457614889205
Fold 3 IBS: 0.19033990305706086
Fold 4 IBS: 0.20853944070357402
Fold 5 IBS: 0.21728171951643854
[I 2024-04-14 16:43:11,934] Trial 86 finished with value: 0.20204409612264693 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.20601078792005195
Fold 2 IBS: 0.21451972742974615
Fold 3 IBS: 0.24528820767892662
Fold 4 IBS: 0.22453641785090767
Fold 5 IBS: 0.23206174675939142
[I 2024-04-14 16:43:12,205] Trial 87 finished with value: 0.22448337752780478 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.6512094554417259, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20485933323937144}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.24762671522415539
Fold 2 IBS: 0.1715658463060267
Fold 3 IBS: 0.19148117469966647
Fold 4 IBS: 0.20997063572215197
Fold 5 IBS: 0.2129063439446945
[I 2024-04-14 16:43:12,858] Trial 88 finished with value: 0.206710143179339 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 15, 'n_estimators': 27, 'oob_score': False, 'max_samples': 0.7081631748214322, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.135797779820887}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.25058563680774437
Fold 2 IBS: 0.2338641464063254
Fold 3 IBS: 0.22952356547794778
Fold 4 IBS: 0.24193138867022507
Fold 5 IBS: 0.23265095037320685
[I 2024-04-14 16:43:13,406] Trial 89 finished with value: 0.2377111375470899 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 16, 'oob_score': False, 'max_samples': 0.15094844814066605, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25791328124207724}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22061007889537348
Fold 2 IBS: 0.1708591714745691
Fold 3 IBS: 0.21077158373683536
Fold 4 IBS: 0.20117937734899835
Fold 5 IBS: 0.2131852975039104
[I 2024-04-14 16:43:14,426] Trial 90 finished with value: 0.20332110179193735 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 60, 'oob_score': False, 'max_samples': 0.7073303179127854, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17438023467720193}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22104227565411022
Fold 2 IBS: 0.1722308353188776
Fold 3 IBS: 0.21218986505215992
Fold 4 IBS: 0.2005308528950858
Fold 5 IBS: 0.21558296667096527
[I 2024-04-14 16:43:15,542] Trial 91 finished with value: 0.20431535911823975 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 14, 'max_depth': 13, 'n_estimators': 63, 'oob_score': False, 'max_samples': 0.7458306090358743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.17711861957316688}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2188852968200289
Fold 2 IBS: 0.1741200249949188
Fold 3 IBS: 0.2102249823823517
Fold 4 IBS: 0.20502686094713804
Fold 5 IBS: 0.21682970835459212
[I 2024-04-14 16:43:16,497] Trial 92 finished with value: 0.20501737469980594 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 15, 'n_estimators': 48, 'oob_score': False, 'max_samples': 0.6974990002375354, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.16157211463362758}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22524471349246272
Fold 2 IBS: 0.18187848730423692
Fold 3 IBS: 0.20172697428993133
Fold 4 IBS: 0.20497913158718492
Fold 5 IBS: 0.2205671313428573
[I 2024-04-14 16:43:17,101] Trial 93 finished with value: 0.20687928760333466 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 12, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.6611862408590626, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1916422380825528}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22083768503980603
Fold 2 IBS: 0.1797588530429119
Fold 3 IBS: 0.2079648062250091
Fold 4 IBS: 0.20291373702977164

Fold 5 IBS: 0.21635495382740025
[I 2024-04-14 16:43:18,507] Trial 94 finished with value: 0.2055660070329798 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 93, 'oob_score': False, 'max_samples': 0.713903532939743, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.22122568041634558}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.26932513184118945
Fold 2 IBS: 0.1697323509215535
Fold 3 IBS: 0.20905255797983618
Fold 4 IBS: 0.2258672184082545
Fold 5 IBS: 0.2152407835992728
[I 2024-04-14 16:43:19,030] Trial 95 finished with value: 0.21784360855002127 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 12, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.8547756485942715, 'max_features': None, 'min_weight_fraction_leaf': 0.17594983744388534}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22065985212578162
Fold 2 IBS: 0.1724043068676393
Fold 3 IBS: 0.212876495767763
Fold 4 IBS: 0.20196603399913246
Fold 5 IBS: 0.21590968295775706
[I 2024-04-14 16:43:19,890] Trial 96 finished with value: 0.2047632743436147 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 13, 'n_estimators': 61, 'oob_score': False, 'max_samples': 0.7614906038154946, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.140922870660813}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.2124870890419155
Fold 2 IBS: 0.1839728942989018
Fold 3 IBS: 0.20401760145240125
Fold 4 IBS: 0.2083031273260043
Fold 5 IBS: 0.2181106808859397
[I 2024-04-14 16:43:20,539] Trial 97 finished with value: 0.20537827860103253 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 42, 'oob_score': False, 'max_samples': 0.6469848321883379, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20645813530532972}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.21598257747339383
Fold 2 IBS: 0.19029660089884604
Fold 3 IBS: 0.21934243199729314
Fold 4 IBS: 0.20794860179398514
Fold 5 IBS: 0.21465156821990095
[I 2024-04-14 16:43:21,482] Trial 98 finished with value: 0.2096443560766838 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 14, 'n_estimators': 55, 'oob_score': False, 'max_samples': 0.5974486750517274, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2337807792851884}. Best is trial 86 with value: 0.20204409612264693.
Fold 1 IBS: 0.22905634179711468
Fold 2 IBS: 0.16952063124242736
Fold 3 IBS: 0.20512675662267585
Fold 4 IBS: 0.2057771072122423
Fold 5 IBS: 0.21371077936387817
[I 2024-04-14 16:43:23,966] Trial 99 finished with value: 0.20463832324766768 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 185, 'oob_score': False, 'max_samples': 0.7373842810679355, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15101502561347407}. Best is trial 86 with value: 0.20204409612264693.


* Best trial for IBS:
 FrozenTrial(number=86, state=TrialState.COMPLETE, values=[0.20204409612264693], datetime_start=datetime.datetime(2024, 4, 14, 16, 43, 11, 275842), datetime_complete=datetime.datetime(2024, 4, 14, 16, 43, 11, 931237), params={'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 31, 'oob_score': False, 'max_samples': 0.7105780352803006, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2021626029496649}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=86, value=None)


* Best Score for IBS:
 0.20204409612264693

In [48]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [49]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.83
train_ibs:  0.202

#### Test

In [50]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [51]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=18, max_leaf_nodes=11,
                     max_samples=0.9059465751594485, min_samples_leaf=1,
                     min_weight_fraction_leaf=0.029068528038335394,
                     n_estimators=318, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.544

RandomSurvivalForest(max_depth=13, max_features='log2', max_leaf_nodes=11,
                     max_samples=0.7105780352803006, min_samples_leaf=11,
                     min_samples_split=13,
                     min_weight_fraction_leaf=0.2021626029496649,
                     n_estimators=31, random_state=123)

test_ibs:  0.247

In [52]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [53]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:43:25,568] A new study created in memory with name: no-name-45748c55-979d-4b1d-a3be-15efd46f1f6d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:43:26,735] Trial 0 finished with value: 0.7329375617815092 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:43:29,242] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:43:34,327] Trial 2 finished with value: 0.7178460229393517 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.8
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:43:34,853] Trial 3 finished with value: 0.7317208004250113 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:43:37,655] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:43:40,181] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:43:41,391] Trial 6 finished with value: 0.7321370246874943 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:43:44,370] Trial 7 finished with value: 0.7075673219865799 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7329375617815092.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:43:44,606] Trial 8 finished with value: 0.7362139149697521 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6545064377682404
[I 2024-04-14 16:43:51,110] Trial 9 finished with value: 0.6956580572700294 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:43:51,450] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 17, 'max_depth': 1, 'n_estimators': 24, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.26413466171660194, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6394422310756972
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6802575107296137
[I 2024-04-14 16:43:51,597] Trial 11 finished with value: 0.7002022988770951 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 5, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9684586161882143, 'min_weight_fraction_leaf': 0.15140395801593098}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:43:52,017] Trial 12 finished with value: 0.7233216044410213 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 5, 'min_samples_leaf': 7, 'max_depth': 11, 'n_estimators': 108, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8094511604072581, 'min_weight_fraction_leaf': 0.21197644982784386}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:43:53,184] Trial 13 finished with value: 0.7227860885168853 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 10, 'n_estimators': 336, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7132669067566587, 'min_weight_fraction_leaf': 0.09682728258065251}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5876494023904383
Fold 2 C-index: 0.7538759689922481
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 16:43:54,690] Trial 14 finished with value: 0.6875118831760492 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 5, 'max_depth': 16, 'n_estimators': 339, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.3790277944184374}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:43:55,110] Trial 15 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 19, 'max_depth': 4, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.25853971878279847, 'min_weight_fraction_leaf': 0.1136143317234711}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:43:56,004] Trial 16 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 20, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.12362405012814498, 'min_weight_fraction_leaf': 0.18949444225079395}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:43:57,139] Trial 17 finished with value: 0.7333650628805521 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 362, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8640754037508087, 'min_weight_fraction_leaf': 0.08300984976320161}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:44:02,209] Trial 18 finished with value: 0.7138187212932231 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 267, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.893843387841617, 'min_weight_fraction_leaf': 0.0012901863864347718}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5956175298804781
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7808510638297872
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6587982832618026
[I 2024-04-14 16:44:02,886] Trial 19 finished with value: 0.7057594207270395 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 173, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6462028944794036, 'min_weight_fraction_leaf': 0.24752940142621416}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:44:03,604] Trial 20 finished with value: 0.7323582709861934 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 8, 'n_estimators': 214, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9046520586847226, 'min_weight_fraction_leaf': 0.15604495917089234}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:44:04,893] Trial 21 finished with value: 0.733056653279694 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 387, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8264846465847887, 'min_weight_fraction_leaf': 0.06531032832143097}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:44:06,336] Trial 22 finished with value: 0.7346870590959979 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8554939338437892, 'min_weight_fraction_leaf': 0.05912077213864973}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:44:08,337] Trial 23 finished with value: 0.7352841948632597 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 487, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6813559412681637, 'min_weight_fraction_leaf': 0.03807965277622394}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:44:10,024] Trial 24 finished with value: 0.7320605873920041 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 495, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7101858188995143, 'min_weight_fraction_leaf': 0.03414106493059247}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:44:11,551] Trial 25 finished with value: 0.727965007825656 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 16, 'n_estimators': 460, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.13197369292803862}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:44:18,038] Trial 26 finished with value: 0.7097917064892874 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 18, 'n_estimators': 403, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7363157908211037, 'min_weight_fraction_leaf': 0.030609355115257964}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:44:19,086] Trial 27 finished with value: 0.7289930115925871 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 313, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.05966804358984962}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:44:20,882] Trial 28 finished with value: 0.727700523625848 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9547761993685097, 'min_weight_fraction_leaf': 0.18010884975569444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7623574144486692
Fold 5 C-index: 0.6716738197424893
[I 2024-04-14 16:44:21,239] Trial 29 finished with value: 0.7278903944963211 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 8, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 53, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6672466493035638, 'min_weight_fraction_leaf': 0.09570676535902678}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:44:23,226] Trial 30 finished with value: 0.7283637613256518 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 377, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8382504072008882, 'min_weight_fraction_leaf': 0.21525035641182588}. Best is trial 8 with value: 0.7362139149697521.

Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:44:24,254] Trial 31 finished with value: 0.7301852441402965 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8780867392507613, 'min_weight_fraction_leaf': 0.08053342835298444}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:44:25,558] Trial 32 finished with value: 0.7270669981840107 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 14, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8465161672872993, 'min_weight_fraction_leaf': 0.13728708040036253}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:44:26,995] Trial 33 finished with value: 0.7291276715364954 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7791575185731888, 'min_weight_fraction_leaf': 0.08782522649871717}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:44:29,119] Trial 34 finished with value: 0.732991669441196 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 404, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.0321950347302904}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:44:33,268] Trial 35 finished with value: 0.7285589865120596 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 462, 'oob_score': True, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7484887897698851, 'min_weight_fraction_leaf': 0.11179394316240188}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 16:44:35,048] Trial 36 finished with value: 0.704782939479291 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 8, 'min_samples_leaf': 8, 'max_depth': 19, 'n_estimators': 120, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5819516222091663, 'min_weight_fraction_leaf': 0.05929252020100452}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:44:35,935] Trial 37 finished with value: 0.5 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 10, 'max_depth': 15, 'n_estimators': 227, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6894294877112123, 'min_weight_fraction_leaf': 0.4916742087904424}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.7127659574468085
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:44:37,039] Trial 38 finished with value: 0.6969977793569042 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6176423630852546, 'min_weight_fraction_leaf': 0.27842662148070446}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:44:40,179] Trial 39 finished with value: 0.7145032975216214 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4114486681290081, 'min_weight_fraction_leaf': 0.006316515579589441}. Best is trial 8 with value: 0.7362139149697521.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:44:41,743] Trial 40 finished with value: 0.7394420414645654 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 344, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7923253229666314, 'min_weight_fraction_leaf': 0.070818312691936}. Best is trial 40 with value: 0.7394420414645654.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:44:43,575] Trial 41 finished with value: 0.7402388542135694 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 357, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7929235954297236, 'min_weight_fraction_leaf': 0.06753409188567513}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:44:44,812] Trial 42 finished with value: 0.7385473158906132 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 340, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7814167764920316, 'min_weight_fraction_leaf': 0.053138807692614115}. Best is trial 41 with value: 0.7402388542135694.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 16:44:45,963] Trial 43 finished with value: 0.7526793316239683 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 342, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.0237916514620877}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:44:47,102] Trial 44 finished with value: 0.7517156174445475 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7903494194560798, 'min_weight_fraction_leaf': 0.02431474917269355}. Best is trial 43 with value: 0.7526793316239683.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 16:44:48,163] Trial 45 finished with value: 0.75724249310961 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 338, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9975014761881965, 'min_weight_fraction_leaf': 0.01820664676789947}. Best is trial 45 with value: 0.75724249310961.

Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:44:49,748] Trial 46 finished with value: 0.7516108231937302 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9833287122666867, 'min_weight_fraction_leaf': 0.02167204729301097}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:44:54,532] Trial 47 finished with value: 0.7072551380763006 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 277, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9938409184868892, 'min_weight_fraction_leaf': 0.012424414465270794}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:44:57,223] Trial 48 finished with value: 0.736994195055912 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 315, 'oob_score': True, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9943389290512517, 'min_weight_fraction_leaf': 0.024122723628498613}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.5338645418326693
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.776595744680851
Fold 4 C-index: 0.7357414448669202
Fold 5 C-index: 0.6201716738197425
[I 2024-04-14 16:44:58,217] Trial 49 finished with value: 0.6871506500322846 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 308, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.943836768280026, 'min_weight_fraction_leaf': 0.3739970568853183}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:44:59,172] Trial 50 finished with value: 0.738757879065195 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 2, 'n_estimators': 255, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9218905769996524, 'min_weight_fraction_leaf': 0.017081546823995417}. Best is trial 45 with value: 0.75724249310961.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:45:00,400] Trial 51 finished with value: 0.7587815706706135 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 328, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8006618362151878, 'min_weight_fraction_leaf': 0.0006942403087633227}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:45:01,760] Trial 52 finished with value: 0.7475219816321547 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 330, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7294591746589625, 'min_weight_fraction_leaf': 0.0016358111792067614}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8553191489361702
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:45:03,203] Trial 53 finished with value: 0.7566629550916705 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 320, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5353674654541881, 'min_weight_fraction_leaf': 0.0026771789807350996}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:45:04,703] Trial 54 finished with value: 0.7352011465498318 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 283, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5280559833057176, 'min_weight_fraction_leaf': 0.039551718738544406}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:45:06,330] Trial 55 finished with value: 0.7336828402532702 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 327, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.3722344587434572, 'min_weight_fraction_leaf': 0.019345288070128742}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 16:45:07,368] Trial 56 finished with value: 0.7370042171283777 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 245, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5400588998582563, 'min_weight_fraction_leaf': 0.04313419866698206}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 16:45:08,651] Trial 57 finished with value: 0.7325789664550014 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 368, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5822470231276546, 'min_weight_fraction_leaf': 0.10820490172022261}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:45:09,732] Trial 58 finished with value: 0.7420782648330935 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.47947757991973655, 'min_weight_fraction_leaf': 0.019676870735375367}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:45:16,363] Trial 59 finished with value: 0.7082120978166874 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 402, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.9629602149520176, 'min_weight_fraction_leaf': 5.104770246312437e-05}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:45:17,366] Trial 60 finished with value: 0.7315255752386033 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 266, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6191277619189391, 'min_weight_fraction_leaf': 0.04917170213673687}. Best is trial 51 with value: 0.7587815706706135.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 16:45:18,481] Trial 61 finished with value: 0.7467905765647049 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.7262478375780741, 'min_weight_fraction_leaf': 0.0014391069076949321}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:45:19,794] Trial 62 finished with value: 0.7475583381073945 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 347, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8176070633016336, 'min_weight_fraction_leaf': 0.017513460534447932}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:45:21,047] Trial 63 finished with value: 0.7466925367529218 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 350, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.9048655808252274, 'min_weight_fraction_leaf': 0.026324306931491667}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:45:22,365] Trial 64 finished with value: 0.7370190980741596 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 4, 'n_estimators': 391, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8235728807014974, 'min_weight_fraction_leaf': 0.07647889290633725}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:45:23,399] Trial 65 finished with value: 0.7475730756320799 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 298, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8717939599515069, 'min_weight_fraction_leaf': 0.046903678085942646}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:45:24,500] Trial 66 finished with value: 0.7482897431748442 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 294, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8797774907667472, 'min_weight_fraction_leaf': 0.048960653209137665}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:45:25,399] Trial 67 finished with value: 0.7393805115631469 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9729538475019345, 'min_weight_fraction_leaf': 0.09677508382156286}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 16:45:26,414] Trial 68 finished with value: 0.7053000937674134 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 282, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9142124434676113, 'min_weight_fraction_leaf': 0.3293312145420018}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:45:27,525] Trial 69 finished with value: 0.7350965386026626 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 312, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8817438215622965, 'min_weight_fraction_leaf': 0.034436173984274676}. Best is trial 51 with value: 0.7587815706706135.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7381974248927039
[I 2024-04-14 16:45:29,293] Trial 70 finished with value: 0.7613284744465487 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 369, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9470771316919997, 'min_weight_fraction_leaf': 0.05299254826291741}. Best is trial 70 with value: 0.7613284744465487.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7424892703862661
[I 2024-04-14 16:45:30,793] Trial 71 finished with value: 0.7638673522542814 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:45:32,531] Trial 72 finished with value: 0.7530816328485426 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9438070806786616, 'min_weight_fraction_leaf': 0.0719219098849957}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:45:34,184] Trial 73 finished with value: 0.7529399312925945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9476534872163854, 'min_weight_fraction_leaf': 0.07948506430889707}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:45:35,954] Trial 74 finished with value: 0.7416078997115878 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 446, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9315744574283523, 'min_weight_fraction_leaf': 0.12730293993691283}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:45:38,169] Trial 75 finished with value: 0.7537662190909693 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 6, 'n_estimators': 423, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9538212906403223, 'min_weight_fraction_leaf': 0.07947418064331738}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7191489361702128
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 16:45:46,405] Trial 76 finished with value: 0.7089732912239908 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9503206330661996, 'min_weight_fraction_leaf': 0.08332855281149479}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7926356589147286
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:45:48,569] Trial 77 finished with value: 0.736222548982041 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 421, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9563764400770771, 'min_weight_fraction_leaf': 0.15158139627292644}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:45:50,422] Trial 78 finished with value: 0.7474677305513714 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 7, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9184606416275723, 'min_weight_fraction_leaf': 0.10966234237102679}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:45:52,190] Trial 79 finished with value: 0.7513105165834996 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8509706901999897, 'min_weight_fraction_leaf': 0.07437080570205526}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 16:45:54,048] Trial 80 finished with value: 0.7250348087736878 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 6, 'n_estimators': 437, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9986660238693948, 'min_weight_fraction_leaf': 0.16662237313004993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 16:45:55,849] Trial 81 finished with value: 0.7572071277415792 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 475, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9698042200030538, 'min_weight_fraction_leaf': 0.059098984023617004}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:45:57,517] Trial 82 finished with value: 0.7514553752203057 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 474, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9681006428937893, 'min_weight_fraction_leaf': 0.09188576940897883}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 16:45:59,143] Trial 83 finished with value: 0.7580508863024411 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 461, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.900953067564881, 'min_weight_fraction_leaf': 0.06238575631317688}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 16:46:02,090] Trial 84 finished with value: 0.7603690354420299 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 5, 'n_estimators': 476, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8981565134422631, 'min_weight_fraction_leaf': 0.055911383060435194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 16:46:04,057] Trial 85 finished with value: 0.7514701127449911 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 4, 'max_depth': 3, 'n_estimators': 479, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8908313295588716, 'min_weight_fraction_leaf': 0.05754237849545954}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 16:46:05,967] Trial 86 finished with value: 0.7604986057242595 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 11, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9139139944038005, 'min_weight_fraction_leaf': 0.06479300875481753}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 16:46:07,750] Trial 87 finished with value: 0.7619731232898213 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 462, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.908648262335172, 'min_weight_fraction_leaf': 0.055676683204352095}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7106382978723405
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 16:46:17,274] Trial 88 finished with value: 0.7081331135870429 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 457, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8593524715534154, 'min_weight_fraction_leaf': 0.20522107340967194}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 16:46:19,155] Trial 89 finished with value: 0.7612669180968402 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 488, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9096225926270616, 'min_weight_fraction_leaf': 0.06086475861021993}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:46:21,284] Trial 90 finished with value: 0.7482861622509297 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9036341058690905, 'min_weight_fraction_leaf': 0.10323471635782432}. Best is trial 71 with value: 0.7638673522542814.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 16:46:23,326] Trial 91 finished with value: 0.7579312275401037 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 5, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.930984837991578, 'min_weight_fraction_leaf': 0.06281312587463944}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 16:46:25,742] Trial 92 finished with value: 0.7465445210352575 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 456, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.837687225987731, 'min_weight_fraction_leaf': 0.03575880044104557}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 16:46:28,123] Trial 93 finished with value: 0.7562581510868437 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 485, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9274363792849041, 'min_weight_fraction_leaf': 0.0661014687608754}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7339055793991416
[I 2024-04-14 16:46:31,292] Trial 94 finished with value: 0.7581413668716293 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8978558580565509, 'min_weight_fraction_leaf': 0.04353249947872927}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 16:46:33,840] Trial 95 finished with value: 0.7464935540221674 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 3, 'n_estimators': 500, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8979178686532339, 'min_weight_fraction_leaf': 0.09188808281710414}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:46:36,668] Trial 96 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 464, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8782096526369123, 'min_weight_fraction_leaf': 0.4423900052068913}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7638297872340426
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 16:46:39,004] Trial 97 finished with value: 0.707119307000758 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 5, 'n_estimators': 467, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7568822772464855, 'min_weight_fraction_leaf': 0.12390809358298693}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7253218884120172
[I 2024-04-14 16:46:40,972] Trial 98 finished with value: 0.7595501798994153 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 450, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8379792984882093, 'min_weight_fraction_leaf': 0.04873278208701805}. Best is trial 71 with value: 0.7638673522542814.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8

[I 2024-04-14 16:46:42,916] A new study created in memory with name: no-name-0e6de77a-8533-4cee-b5e8-221c5690986e

Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 16:46:42,901] Trial 99 finished with value: 0.7454360752058654 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 449, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8115869270579641, 'min_weight_fraction_leaf': 0.046153664833883515}. Best is trial 71 with value: 0.7638673522542814.


* Best trial for C-index:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.7638673522542814], datetime_start=datetime.datetime(2024, 4, 14, 16, 45, 29, 302071), datetime_complete=datetime.datetime(2024, 4, 14, 16, 45, 30, 793221), params={'min_samples_split': 15, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 6, 'n_estimators': 376, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9529576562335005, 'min_weight_fraction_leaf': 0.05156899271012762}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for C-index:
 0.7638673522542814

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23536610912753758
Fold 2 IBS: 0.20145762246413637
Fold 3 IBS: 0.20393081537250338
Fold 4 IBS: 0.21602715770992703
Fold 5 IBS: 0.2123183673596273
[I 2024-04-14 16:46:48,738] Trial 0 finished with value: 0.21382001440674636 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-14 16:46:55,825] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24081748643654036
Fold 2 IBS: 0.21713451086140778
Fold 3 IBS: 0.21706845078329945
Fold 4 IBS: 0.22785653322218774
Fold 5 IBS: 0.2212935208368412
[I 2024-04-14 16:47:01,280] Trial 2 finished with value: 0.22483410042805532 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24130149411697235
Fold 2 IBS: 0.2155958186901399
Fold 3 IBS: 0.21794780991257648
Fold 4 IBS: 0.2281735359031675
Fold 5 IBS: 0.2213413510348227
[I 2024-04-14 16:47:03,135] Trial 3 finished with value: 0.22487200193153578 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-14 16:47:09,029] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-14 16:47:11,395] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23588196908877218
Fold 2 IBS: 0.20300039081654195
Fold 3 IBS: 0.2032173161135722
Fold 4 IBS: 0.21660656247722504
Fold 5 IBS: 0.21313591685519812
[I 2024-04-14 16:47:16,149] Trial 6 finished with value: 0.21436843107026188 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23825239046762217
Fold 2 IBS: 0.20781792017117767
Fold 3 IBS: 0.20896423148161078
Fold 4 IBS: 0.2197851504145311
Fold 5 IBS: 0.21653670443025383
[I 2024-04-14 16:47:19,161] Trial 7 finished with value: 0.2182712793930391 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23441021296278977
Fold 2 IBS: 0.21668396635030526
Fold 3 IBS: 0.22051379811268176
Fold 4 IBS: 0.22841790837130418
Fold 5 IBS: 0.21971786351985503
[I 2024-04-14 16:47:19,779] Trial 8 finished with value: 0.2239487498633872 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24426590657878128
Fold 2 IBS: 0.22769375627843935
Fold 3 IBS: 0.22591830688186657
Fold 4 IBS: 0.23810899013034692
Fold 5 IBS: 0.22806252164373667
[I 2024-04-14 16:47:26,300] Trial 9 finished with value: 0.23280989630263416 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-14 16:47:32,159] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.2366414313349858
Fold 2 IBS: 0.21027597932345765
Fold 3 IBS: 0.21371008388168403
Fold 4 IBS: 0.22126964028612253
Fold 5 IBS: 0.2183525448310651
[I 2024-04-14 16:47:36,770] Trial 11 finished with value: 0.22004993593146302 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21382001440674636.
Fold 1 IBS: 0.23579256852371847
Fold 2 IBS: 0.19568412454984113
Fold 3 IBS: 0.20040747067699977
Fold 4 IBS: 0.21186400025265303
Fold 5 IBS: 0.20966969871024252
[I 2024-04-14 16:47:42,558] Trial 12 finished with value: 0.210683572542691 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2370011165638282
Fold 2 IBS: 0.21123276228104673
Fold 3 IBS: 0.21121286711017057
Fold 4 IBS: 0.2241696763859363
Fold 5 IBS: 0.21822141136063145
[I 2024-04-14 16:47:50,158] Trial 13 finished with value: 0.22036756674032265 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23685780568086942
Fold 2 IBS: 0.2126468337858846
Fold 3 IBS: 0.2143772281757236
Fold 4 IBS: 0.22443452861645802
Fold 5 IBS: 0.21899252589159815
[I 2024-04-14 16:47:55,172] Trial 14 finished with value: 0.22146178443010672 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.210683572542691.

Fold 1 IBS: 0.23656743298208832
Fold 2 IBS: 0.21264947915533935
Fold 3 IBS: 0.21321328704497466
Fold 4 IBS: 0.22340910553399146
Fold 5 IBS: 0.21947803887476586
[I 2024-04-14 16:47:58,620] Trial 15 finished with value: 0.22106346871823193 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24483198345747628
Fold 2 IBS: 0.2302859276502996
Fold 3 IBS: 0.2285602592982639
Fold 4 IBS: 0.24045635643173324
Fold 5 IBS: 0.22930909941169325
[I 2024-04-14 16:48:07,376] Trial 16 finished with value: 0.23468872524989326 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2357109983223001
Fold 2 IBS: 0.20494805543099556
Fold 3 IBS: 0.21371005693600734
Fold 4 IBS: 0.21914551084001152
Fold 5 IBS: 0.21764479743708764
[I 2024-04-14 16:48:10,954] Trial 17 finished with value: 0.21823188379328046 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-14 16:48:12,600] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23569889105742511
Fold 2 IBS: 0.21036165282675318
Fold 3 IBS: 0.2110188939735362
Fold 4 IBS: 0.2231729444607325
Fold 5 IBS: 0.21764713763142923
[I 2024-04-14 16:48:17,017] Trial 19 finished with value: 0.21957990398997523 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.2260422981383027
Fold 2 IBS: 0.21628115911706547
Fold 3 IBS: 0.22894435879157846
Fold 4 IBS: 0.22705631591030262
Fold 5 IBS: 0.2234837877858094
[I 2024-04-14 16:48:17,285] Trial 20 finished with value: 0.22436158394861172 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23626217363246013
Fold 2 IBS: 0.20265333339770739
Fold 3 IBS: 0.2030759075715199
Fold 4 IBS: 0.21605001910251603
Fold 5 IBS: 0.2129636719520293
[I 2024-04-14 16:48:22,457] Trial 21 finished with value: 0.21420102113124656 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23496608578657435
Fold 2 IBS: 0.1999430054098381
Fold 3 IBS: 0.201275593836101
Fold 4 IBS: 0.21418253302811457
Fold 5 IBS: 0.21127196072648274
[I 2024-04-14 16:48:28,055] Trial 22 finished with value: 0.21232783575742217 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 12, 'n_estimators': 432, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6362083117849644, 'min_weight_fraction_leaf': 0.03085933791685891}. Best is trial 12 with value: 0.210683572542691.
Fold 1 IBS: 0.23555557011049139
Fold 2 IBS: 0.19236878946561603
Fold 3 IBS: 0.19926908881992766
Fold 4 IBS: 0.21084942333238568
Fold 5 IBS: 0.2081240396802252
[I 2024-04-14 16:48:34,896] Trial 23 finished with value: 0.20923338228172916 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 458, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7228255630253293, 'min_weight_fraction_leaf': 0.04381644940379864}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23607695303226134
Fold 2 IBS: 0.203493581017792
Fold 3 IBS: 0.20360358222095004
Fold 4 IBS: 0.21361938713575862
Fold 5 IBS: 0.2127155595148638
[I 2024-04-14 16:48:41,191] Trial 24 finished with value: 0.21390181258432514 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 466, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3952360400668078, 'min_weight_fraction_leaf': 0.03795721510797542}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23810448610418447
Fold 2 IBS: 0.20850297794887437
Fold 3 IBS: 0.20884091287918746
Fold 4 IBS: 0.21832663743927483
Fold 5 IBS: 0.2167935048771244
[I 2024-04-14 16:48:48,611] Trial 25 finished with value: 0.2181137038497291 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 5, 'n_estimators': 412, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.040940620238958246}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2366073194702186
Fold 2 IBS: 0.2094968403110053
Fold 3 IBS: 0.20963379712724098
Fold 4 IBS: 0.2223187457140648
Fold 5 IBS: 0.21676394473697067
[I 2024-04-14 16:48:58,630] Trial 26 finished with value: 0.21896412947190008 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8470663105570104, 'min_weight_fraction_leaf': 0.15947517522767574}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23608107276763018
Fold 2 IBS: 0.21036141351373328
Fold 3 IBS: 0.21169155072466916
Fold 4 IBS: 0.22331018888988935
Fold 5 IBS: 0.2177506938697703
[I 2024-04-14 16:49:06,072] Trial 27 finished with value: 0.21983898395313844 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 497, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.4851916929438269, 'min_weight_fraction_leaf': 0.10131727829817523}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23715637039941884
Fold 2 IBS: 0.2120572412765648
Fold 3 IBS: 0.21620854589832805
Fold 4 IBS: 0.2250681900188581
Fold 5 IBS: 0.22134392576904316
[I 2024-04-14 16:49:10,396] Trial 28 finished with value: 0.22236685467244258 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 9, 'n_estimators': 288, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7297703206425398, 'min_weight_fraction_leaf': 0.23690284852287818}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24167838631766778
Fold 2 IBS: 0.22069051827263042
Fold 3 IBS: 0.22031739328406955
Fold 4 IBS: 0.23288818140652423
Fold 5 IBS: 0.22471508602895093
[I 2024-04-14 16:49:15,065] Trial 29 finished with value: 0.22805791306196857 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 7, 'min_samples_leaf': 18, 'max_depth': 2, 'n_estimators': 216, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6225172300741029, 'min_weight_fraction_leaf': 0.08129451634552948}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.2369623605519169
Fold 2 IBS: 0.2015664827514855
Fold 3 IBS: 0.2044196732107329
Fold 4 IBS: 0.2152719150958778
Fold 5 IBS: 0.2123358137500061
[I 2024-04-14 16:49:20,727] Trial 30 finished with value: 0.21411124907200385 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 3, 'min_samples_leaf': 4, 'max_depth': 12, 'n_estimators': 355, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7262614295600427, 'min_weight_fraction_leaf': 0.020774312173092817}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23451695205118067
Fold 2 IBS: 0.19751010562426458
Fold 3 IBS: 0.2027198084019687
Fold 4 IBS: 0.21411412044401185
Fold 5 IBS: 0.2111761169753505
[I 2024-04-14 16:49:26,146] Trial 31 finished with value: 0.21200742069935527 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 8, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.923666057752446, 'min_weight_fraction_leaf': 0.09694658331929079}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2351025999648965
Fold 2 IBS: 0.1949158359424477
Fold 3 IBS: 0.20111115549804756
Fold 4 IBS: 0.21180546961424107
Fold 5 IBS: 0.20942511704648153
[I 2024-04-14 16:49:31,514] Trial 32 finished with value: 0.2104720356132229 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 400, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.939007534925735, 'min_weight_fraction_leaf': 0.056106269226335825}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2359807363001553
Fold 2 IBS: 0.20390144524422224
Fold 3 IBS: 0.20692223621119946
Fold 4 IBS: 0.2180339829065641
Fold 5 IBS: 0.21348267427916112
[I 2024-04-14 16:49:37,408] Trial 33 finished with value: 0.21566421498826044 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 16, 'n_estimators': 394, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9138848353483187, 'min_weight_fraction_leaf': 0.11908301006708072}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23760045008166628
Fold 2 IBS: 0.1836854003772293
Fold 3 IBS: 0.20658859037809638
Fold 4 IBS: 0.21356225516393262
Fold 5 IBS: 0.2080473806120064
[I 2024-04-14 16:49:43,921] Trial 34 finished with value: 0.2098968153225862 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 471, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9346426743133951, 'min_weight_fraction_leaf': 0.06204686171902169}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23705554587631616
Fold 2 IBS: 0.18409383187630057
Fold 3 IBS: 0.20774926569595484
Fold 4 IBS: 0.21266700404602018
Fold 5 IBS: 0.20816809551656013
[I 2024-04-14 16:49:52,277] Trial 35 finished with value: 0.2099467486022304 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 14, 'n_estimators': 465, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.8327847526324277, 'min_weight_fraction_leaf': 0.055940476394666754}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23566967538262615
Fold 2 IBS: 0.18498818375621254
Fold 3 IBS: 0.2076181431218228
Fold 4 IBS: 0.21248969655065036
Fold 5 IBS: 0.20727223939702627
[I 2024-04-14 16:49:59,209] Trial 36 finished with value: 0.20960758764166765 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 456, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.827098326399153, 'min_weight_fraction_leaf': 0.07015937717166007}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2322804097655011
Fold 2 IBS: 0.1904595107494953
Fold 3 IBS: 0.20654496901893055
Fold 4 IBS: 0.21029065871150715
Fold 5 IBS: 0.20940168079092789
[I 2024-04-14 16:50:07,116] Trial 37 finished with value: 0.20979544580727238 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 458, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8333567609683693, 'min_weight_fraction_leaf': 0.12103866621890363}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23402986510699297
Fold 2 IBS: 0.20551834233097463
Fold 3 IBS: 0.21448459324894656
Fold 4 IBS: 0.21983535419793537
Fold 5 IBS: 0.21738979632924899
[I 2024-04-14 16:50:12,022] Trial 38 finished with value: 0.2182515902428197 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 349, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.823414916934049, 'min_weight_fraction_leaf': 0.22365568672391764}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23303653525127266
Fold 2 IBS: 0.19614443640526336
Fold 3 IBS: 0.20759014709806334
Fold 4 IBS: 0.21278979581525073
Fold 5 IBS: 0.2115153572009253
[I 2024-04-14 16:50:18,061] Trial 39 finished with value: 0.21221525435415506 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 441, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7688812089462244, 'min_weight_fraction_leaf': 0.13832319540130408}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.24085544671476855
Fold 2 IBS: 0.21881433431452443
Fold 3 IBS: 0.2205550472397075
Fold 4 IBS: 0.23189796849220526
Fold 5 IBS: 0.22387717931221346
[I 2024-04-14 16:50:27,494] Trial 40 finished with value: 0.22719999521468384 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 477, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7387886455857571, 'min_weight_fraction_leaf': 0.2794340971992336}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23558729160195155
Fold 2 IBS: 0.18499721054651033
Fold 3 IBS: 0.2078176191769497
Fold 4 IBS: 0.21254959703326678
Fold 5 IBS: 0.20740208695361273
[I 2024-04-14 16:50:37,369] Trial 41 finished with value: 0.20967076106245824 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 459, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8304297502532995, 'min_weight_fraction_leaf': 0.06567312882813131}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23638956396269079
Fold 2 IBS: 0.18490789291091672
Fold 3 IBS: 0.20644644482157795
Fold 4 IBS: 0.21257693995308247
Fold 5 IBS: 0.20732761178411305
[I 2024-04-14 16:50:45,751] Trial 42 finished with value: 0.20952969068647617 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 450, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7982039779530783, 'min_weight_fraction_leaf': 0.07186658790260646}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.23274337848255236
Fold 2 IBS: 0.1929272244249927
Fold 3 IBS: 0.20732501652108193
Fold 4 IBS: 0.21144242883441275
Fold 5 IBS: 0.20983249626579628
[I 2024-04-14 16:50:55,728] Trial 43 finished with value: 0.21085410890576722 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 17, 'n_estimators': 440, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7924307971892496, 'min_weight_fraction_leaf': 0.1211117088142}. Best is trial 23 with value: 0.20923338228172916.
Fold 1 IBS: 0.2410193325812047
Fold 2 IBS: 0.2226476644714021
Fold 3 IBS: 0.22105022637397118
Fold 4 IBS: 0.23115256969605635
Fold 5 IBS: 0.2240981533222132
[I 2024-04-14 16:51:03,280] Trial 44 finished with value: 0.2279935892889695 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 453, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6979907483981592, 'min_weight_fraction_leaf': 0.16526223863734468}. Best is trial 23 with value: 0.20923338228172916.

Fold 1 IBS: 0.23247724033039832
Fold 2 IBS: 0.18748554961121114
Fold 3 IBS: 0.2090170455982855
Fold 4 IBS: 0.207742375469341
Fold 5 IBS: 0.20889347688505747
[I 2024-04-14 16:51:06,212] Trial 45 finished with value: 0.2091231375788587 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8505483502716148, 'min_weight_fraction_leaf': 0.09794633817349793}. Best is trial 45 with value: 0.2091231375788587.
Fold 1 IBS: 0.2314286160573986
Fold 2 IBS: 0.1860889745854672
Fold 3 IBS: 0.20638267011548084
Fold 4 IBS: 0.20884587453459477
Fold 5 IBS: 0.20805701088484838
[I 2024-04-14 16:51:09,499] Trial 46 finished with value: 0.20816062923555795 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7709286828220481, 'min_weight_fraction_leaf': 0.07995724348415684}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23766776108374213
Fold 2 IBS: 0.21002348979145327
Fold 3 IBS: 0.21765068090817657
Fold 4 IBS: 0.22280193059668152
Fold 5 IBS: 0.21940264282312605
[I 2024-04-14 16:51:11,966] Trial 47 finished with value: 0.22150930104063588 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 20, 'n_estimators': 127, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7682715671327377, 'min_weight_fraction_leaf': 0.08646740062265149}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23713247312937227
Fold 2 IBS: 0.1864152472719121
Fold 3 IBS: 0.20569921628056348
Fold 4 IBS: 0.21202213139980625
Fold 5 IBS: 0.2062034346638877
[I 2024-04-14 16:51:15,324] Trial 48 finished with value: 0.20949450054910837 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 186, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8579998757196492, 'min_weight_fraction_leaf': 0.022631912267245}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2401019704407054
Fold 2 IBS: 0.20664694277509515
Fold 3 IBS: 0.20269468295254925
Fold 4 IBS: 0.2190769330154152
Fold 5 IBS: 0.21529320315539308
[I 2024-04-14 16:51:18,338] Trial 49 finished with value: 0.2167627464678316 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 176, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.535541626399398, 'min_weight_fraction_leaf': 0.02410725915835375}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23775614182380903
Fold 2 IBS: 0.20743414808900665
Fold 3 IBS: 0.20687718864416932
Fold 4 IBS: 0.21905338149069295
Fold 5 IBS: 0.21496321205066113
[I 2024-04-14 16:51:20,073] Trial 50 finished with value: 0.21721681441966784 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 90, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.8724086164488271, 'min_weight_fraction_leaf': 0.04430715227744478}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23333408320563848
Fold 2 IBS: 0.18618334408777154
Fold 3 IBS: 0.2054922876895997
Fold 4 IBS: 0.2095428614888614
Fold 5 IBS: 0.2081255374544523
[I 2024-04-14 16:51:22,931] Trial 51 finished with value: 0.2085356227852647 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 157, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7607239465677439, 'min_weight_fraction_leaf': 0.0768704777706238}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23294009669574758
Fold 2 IBS: 0.18886644911422001
Fold 3 IBS: 0.20450870840640553
Fold 4 IBS: 0.2098663013569692
Fold 5 IBS: 0.2093242311139224
[I 2024-04-14 16:51:26,978] Trial 52 finished with value: 0.2091011573374529 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 215, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6812726944311738, 'min_weight_fraction_leaf': 0.0924784870388018}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23340127695530247
Fold 2 IBS: 0.19037609007747622
Fold 3 IBS: 0.20443462122815134
Fold 4 IBS: 0.20971338145144297
Fold 5 IBS: 0.20931781265162946
[I 2024-04-14 16:51:30,810] Trial 53 finished with value: 0.2094486364728005 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 224, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6963870551875947, 'min_weight_fraction_leaf': 0.10563773255020543}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23338966290283988
Fold 2 IBS: 0.19138513453127515
Fold 3 IBS: 0.20331794017233815
Fold 4 IBS: 0.21130675152530337
Fold 5 IBS: 0.2105461957704023
[I 2024-04-14 16:51:34,735] Trial 54 finished with value: 0.20998913698043178 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 228, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6719877047239909, 'min_weight_fraction_leaf': 0.0997398012429799}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23593555870849725
Fold 2 IBS: 0.20801826761705877
Fold 3 IBS: 0.20827021219395564
Fold 4 IBS: 0.21956943852396218
Fold 5 IBS: 0.21586303213321972
[I 2024-04-14 16:51:37,437] Trial 55 finished with value: 0.21753130183533873 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7290878996075589, 'min_weight_fraction_leaf': 0.1329691849961646}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24666819701072148
Fold 2 IBS: 0.23210773115939679
Fold 3 IBS: 0.22932364190291274
Fold 4 IBS: 0.24152405514050876
Fold 5 IBS: 0.2303157661686399
[I 2024-04-14 16:51:40,371] Trial 56 finished with value: 0.23598787827643591 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5975963219999111, 'min_weight_fraction_leaf': 0.4643802392700467}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23492638070785768
Fold 2 IBS: 0.21240221048192362
Fold 3 IBS: 0.2168912407987811
Fold 4 IBS: 0.22754745889623634
Fold 5 IBS: 0.22089364796872285
[I 2024-04-14 16:51:42,708] Trial 57 finished with value: 0.22253218777070433 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 128, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6735255380721511, 'min_weight_fraction_leaf': 0.18708850621022327}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23531750054242687
Fold 2 IBS: 0.2077683628397722
Fold 3 IBS: 0.21364739027613322
Fold 4 IBS: 0.21979565810435922
Fold 5 IBS: 0.21840068135164575
[I 2024-04-14 16:51:47,294] Trial 58 finished with value: 0.21898591862286745 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 238, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5389598332282572, 'min_weight_fraction_leaf': 0.15746351073381912}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.24661384524722246
Fold 2 IBS: 0.23215291198462218
Fold 3 IBS: 0.22952739882394438
Fold 4 IBS: 0.24152565273881768
Fold 5 IBS: 0.2303053694496521
[I 2024-04-14 16:51:51,891] Trial 59 finished with value: 0.23602503564885174 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 275, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.75796811576398, 'min_weight_fraction_leaf': 0.3795797400921996}. Best is trial 46 with value: 0.20816062923555795.

Fold 1 IBS: 0.2376464824369693
Fold 2 IBS: 0.21593994734134395
Fold 3 IBS: 0.22177987321764975
Fold 4 IBS: 0.22790863488656224
Fold 5 IBS: 0.2205529164521157
[I 2024-04-14 16:51:53,466] Trial 60 finished with value: 0.22476557086692814 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 74, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6041879821929975, 'min_weight_fraction_leaf': 0.1056236625824671}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23781793031064252
Fold 2 IBS: 0.1862495208476139
Fold 3 IBS: 0.20248456745784213
Fold 4 IBS: 0.21234711020159586
Fold 5 IBS: 0.2076972639565933
[I 2024-04-14 16:51:57,028] Trial 61 finished with value: 0.20931927855485752 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 197, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7101126073432302, 'min_weight_fraction_leaf': 0.013226300887269365}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.2382367270174128
Fold 2 IBS: 0.18483164704435992
Fold 3 IBS: 0.20455018380786597
Fold 4 IBS: 0.2115954964542311
Fold 5 IBS: 0.20832518097782782
[I 2024-04-14 16:52:00,718] Trial 62 finished with value: 0.20950784706033954 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7066561911530848, 'min_weight_fraction_leaf': 0.012902964688040898}. Best is trial 46 with value: 0.20816062923555795.
Fold 1 IBS: 0.23653797420874464
Fold 2 IBS: 0.18352585769961322
Fold 3 IBS: 0.20365755657663714
Fold 4 IBS: 0.20917655609037722
Fold 5 IBS: 0.20729793495414095
[I 2024-04-14 16:52:03,338] Trial 63 finished with value: 0.20803917590590265 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 148, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6435418239181828, 'min_weight_fraction_leaf': 0.046981576659506384}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.2376440714946851
Fold 2 IBS: 0.18154571059609376
Fold 3 IBS: 0.20148827866234856
Fold 4 IBS: 0.21485752658604737
Fold 5 IBS: 0.21193720419679402
[I 2024-04-14 16:52:05,945] Trial 64 finished with value: 0.20949455830719374 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 131, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6558453673842368, 'min_weight_fraction_leaf': 0.0017360883857289438}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24069140178630108
Fold 2 IBS: 0.21023884738343832
Fold 3 IBS: 0.20819592567054473
Fold 4 IBS: 0.22032685614631106
Fold 5 IBS: 0.2181378139835771
[I 2024-04-14 16:52:08,545] Trial 65 finished with value: 0.21951816899403448 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 144, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6369381520536594, 'min_weight_fraction_leaf': 0.04630739996813268}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.24662572908345176
Fold 2 IBS: 0.2321190214638095
Fold 3 IBS: 0.22943780141623776
Fold 4 IBS: 0.2415441728621753
Fold 5 IBS: 0.2302929916244345
[I 2024-04-14 16:52:11,711] Trial 66 finished with value: 0.23600394329002175 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 190, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7534591387104144, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23761253968101
Fold 2 IBS: 0.19333058518344354
Fold 3 IBS: 0.19763843228218964
Fold 4 IBS: 0.2100557032515617
Fold 5 IBS: 0.208391029584297
[I 2024-04-14 16:52:13,740] Trial 67 finished with value: 0.20940565799650038 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 111, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.7140591797427468, 'min_weight_fraction_leaf': 0.0380146506503018}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23568784825771597
Fold 2 IBS: 0.19836028806772887
Fold 3 IBS: 0.20225664393852164
Fold 4 IBS: 0.21479439327398367
Fold 5 IBS: 0.21109075078575282
[I 2024-04-14 16:52:16,416] Trial 68 finished with value: 0.21243798486474058 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 3, 'max_depth': 20, 'n_estimators': 168, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.7866638182428198, 'min_weight_fraction_leaf': 0.08748663516762165}. Best is trial 63 with value: 0.20803917590590265.
Fold 1 IBS: 0.23356744505088914
Fold 2 IBS: 0.1834363879714103
Fold 3 IBS: 0.207688591468538
Fold 4 IBS: 0.20411915061999797
Fold 5 IBS: 0.21081229591952125
[I 2024-04-14 16:52:17,768] Trial 69 finished with value: 0.20792477420607133 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 78, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6633577858466918, 'min_weight_fraction_leaf': 0.05378179190948057}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23425832559812115
Fold 2 IBS: 0.1874883919439577
Fold 3 IBS: 0.20956087508825158
Fold 4 IBS: 0.20966146089051388
Fold 5 IBS: 0.21197029878987708
[I 2024-04-14 16:52:18,702] Trial 70 finished with value: 0.21058787046214428 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 46, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.609138718062076, 'min_weight_fraction_leaf': 0.08081693575379295}. Best is trial 69 with value: 0.20792477420607133.
Fold 1 IBS: 0.23180288969924676
Fold 2 IBS: 0.18284953833260828
Fold 3 IBS: 0.20816697020659303
Fold 4 IBS: 0.20634477989340283
Fold 5 IBS: 0.2066720406825964
[I 2024-04-14 16:52:19,796] Trial 71 finished with value: 0.20716724376288945 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24034476073822214
Fold 2 IBS: 0.18987915865551205
Fold 3 IBS: 0.2035631310131893
Fold 4 IBS: 0.21033288060199645
Fold 5 IBS: 0.20723055719361239
[I 2024-04-14 16:52:20,941] Trial 72 finished with value: 0.21027009764050644 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 64, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5683034340032609, 'min_weight_fraction_leaf': 0.04646174961182159}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2299054630450867
Fold 2 IBS: 0.19773469146740125
Fold 3 IBS: 0.19034097643724923
Fold 4 IBS: 0.22944964628361184
Fold 5 IBS: 0.2389286128541861
[I 2024-04-14 16:52:21,275] Trial 73 finished with value: 0.217271878017507 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 2, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6645384838575977, 'min_weight_fraction_leaf': 0.054429859852659815}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2303167286243434
Fold 2 IBS: 0.19516700665987674
Fold 3 IBS: 0.20660685643983331
Fold 4 IBS: 0.20899892281373353
Fold 5 IBS: 0.2066488418873486
[I 2024-04-14 16:52:21,956] Trial 74 finished with value: 0.20954767128502713 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 29, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7480880522886367, 'min_weight_fraction_leaf': 0.07511258593340842}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23693321208405524
Fold 2 IBS: 0.19000973925047765
Fold 3 IBS: 0.20243881773088923
Fold 4 IBS: 0.2110667431713562
Fold 5 IBS: 0.20765848231427028
[I 2024-04-14 16:52:23,679] Trial 75 finished with value: 0.20962139891020973 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 104, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.49599352625156035, 'min_weight_fraction_leaf': 0.03138093454428739}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2375162774090104
Fold 2 IBS: 0.21696007860868566
Fold 3 IBS: 0.2199964189465905
Fold 4 IBS: 0.2298197447784768
Fold 5 IBS: 0.2208032877666601
[I 2024-04-14 16:52:25,349] Trial 76 finished with value: 0.2250191615018847 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 81, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6498539620686062, 'min_weight_fraction_leaf': 0.1107936452967258}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.234645557683981
Fold 2 IBS: 0.19308386846985393
Fold 3 IBS: 0.21042866351417217
Fold 4 IBS: 0.213955157478479
Fold 5 IBS: 0.20941746392682734
[I 2024-04-14 16:52:26,517] Trial 77 finished with value: 0.21230614221466268 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 20, 'n_estimators': 53, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6219886854752814, 'min_weight_fraction_leaf': 0.0881530598041391}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23208979344503086
Fold 2 IBS: 0.19134551959096457
Fold 3 IBS: 0.20969730607101159
Fold 4 IBS: 0.21155535213663088
Fold 5 IBS: 0.21094666727963496
[I 2024-04-14 16:52:29,254] Trial 78 finished with value: 0.21112692770465458 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 140, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8975377298130277, 'min_weight_fraction_leaf': 0.05792949206602531}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.24656769908913287
Fold 2 IBS: 0.23207473314584195
Fold 3 IBS: 0.22956209752209408
Fold 4 IBS: 0.24131766392563656
Fold 5 IBS: 0.22974225690563504
[I 2024-04-14 16:52:31,893] Trial 79 finished with value: 0.2358528901176681 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 3, 'max_depth': 15, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.2170140247726947, 'min_weight_fraction_leaf': 0.15079098086778978}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23398194286521523
Fold 2 IBS: 0.2042478759118354
Fold 3 IBS: 0.2149027538028443
Fold 4 IBS: 0.21138634120370936
Fold 5 IBS: 0.21509744244742898
[I 2024-04-14 16:52:32,738] Trial 80 finished with value: 0.21592327124620664 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 34, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.680202266270148, 'min_weight_fraction_leaf': 0.13027280080194392}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23821133340721135
Fold 2 IBS: 0.18697626156811917
Fold 3 IBS: 0.2025556131339658
Fold 4 IBS: 0.21248041803374165
Fold 5 IBS: 0.21006237384648405
[I 2024-04-14 16:52:37,056] Trial 81 finished with value: 0.2100571999979044 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 163, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7059723708255974, 'min_weight_fraction_leaf': 0.011081957753211642}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2354434465673004
Fold 2 IBS: 0.18590060696281396
Fold 3 IBS: 0.20237660521219805
Fold 4 IBS: 0.21289282208945418
Fold 5 IBS: 0.2079334303868527
[I 2024-04-14 16:52:40,858] Trial 82 finished with value: 0.20890938224372385 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 205, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7322939853383122, 'min_weight_fraction_leaf': 0.030199179896950257}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2391213827919915
Fold 2 IBS: 0.18339377899057588
Fold 3 IBS: 0.20630651107397327
Fold 4 IBS: 0.21414237142238046
Fold 5 IBS: 0.20709539863236437
[I 2024-04-14 16:52:45,395] Trial 83 finished with value: 0.2100118885822571 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 249, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8082167579651034, 'min_weight_fraction_leaf': 0.030688122459232033}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2338134437703758
Fold 2 IBS: 0.18585229495562317
Fold 3 IBS: 0.20232554114967682
Fold 4 IBS: 0.20935878852735582
Fold 5 IBS: 0.20693004752390112
[I 2024-04-14 16:52:49,089] Trial 84 finished with value: 0.20765602318538656 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 178, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7722055241934203, 'min_weight_fraction_leaf': 0.06706989383850837}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2325404292841733
Fold 2 IBS: 0.2037796259632883
Fold 3 IBS: 0.21285222741885748
Fold 4 IBS: 0.21748519543805853
Fold 5 IBS: 0.21558014668487166
[I 2024-04-14 16:52:55,018] Trial 85 finished with value: 0.21644752495784986 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 20, 'n_estimators': 209, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.8080700094351241, 'min_weight_fraction_leaf': 0.07313973736441735}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23185610825625882
Fold 2 IBS: 0.1883838499173774
Fold 3 IBS: 0.2069558256748436
Fold 4 IBS: 0.2056460896941882
Fold 5 IBS: 0.20834833869947297
[I 2024-04-14 16:52:58,207] Trial 86 finished with value: 0.2082380424484282 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 179, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7797829686997926, 'min_weight_fraction_leaf': 0.0930692046392031}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23732262587143452
Fold 2 IBS: 0.18516284894711776
Fold 3 IBS: 0.20293194154297275
Fold 4 IBS: 0.20976950466294828
Fold 5 IBS: 0.20684702854669929
[I 2024-04-14 16:53:01,272] Trial 87 finished with value: 0.2084067899142345 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 182, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7347045490916186, 'min_weight_fraction_leaf': 0.0569064501216709}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23610457243620386
Fold 2 IBS: 0.1843646040116617
Fold 3 IBS: 0.2038780530044773
Fold 4 IBS: 0.2105249290335657
Fold 5 IBS: 0.20647024537168604
[I 2024-04-14 16:53:04,237] Trial 88 finished with value: 0.20826848077151894 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7454117372266992, 'min_weight_fraction_leaf': 0.05974548060098256}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23977374886110586
Fold 2 IBS: 0.20834445745005828
Fold 3 IBS: 0.2081295030562698
Fold 4 IBS: 0.22184631620912326
Fold 5 IBS: 0.21759905094032755
[I 2024-04-14 16:53:08,139] Trial 89 finished with value: 0.21913861530337697 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.7540347885452335, 'min_weight_fraction_leaf': 0.06459414509901623}. Best is trial 71 with value: 0.20716724376288945.

Fold 1 IBS: 0.23900229487413618
Fold 2 IBS: 0.1829989350900894
Fold 3 IBS: 0.20504008460974205
Fold 4 IBS: 0.21135329415618298
Fold 5 IBS: 0.20658610615550185
[I 2024-04-14 16:53:10,085] Trial 90 finished with value: 0.20899614297713048 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 95, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7812194815989179, 'min_weight_fraction_leaf': 0.052583924158953604}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23336269917153504
Fold 2 IBS: 0.18793910685243745
Fold 3 IBS: 0.20227191981491185
Fold 4 IBS: 0.2126322523584538
Fold 5 IBS: 0.20891055719221097
[I 2024-04-14 16:53:13,423] Trial 91 finished with value: 0.2090233070779098 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 170, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7343789509732842, 'min_weight_fraction_leaf': 0.034512973636926236}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23849245554801698
Fold 2 IBS: 0.18514480626810045
Fold 3 IBS: 0.2021086406752317
Fold 4 IBS: 0.21479834430066197
Fold 5 IBS: 0.20909254443799166
[I 2024-04-14 16:53:17,005] Trial 92 finished with value: 0.20992735824600056 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 155, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7636505288647887, 'min_weight_fraction_leaf': 0.022561082303242087}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23712661813293098
Fold 2 IBS: 0.1851768236866079
Fold 3 IBS: 0.20432880761759306
Fold 4 IBS: 0.2118089074273193
Fold 5 IBS: 0.20725293903536335
[I 2024-04-14 16:53:19,839] Trial 93 finished with value: 0.20913881917996288 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 195, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.780594325886568, 'min_weight_fraction_leaf': 0.06660760570218983}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23313202103339004
Fold 2 IBS: 0.19197759007192453
Fold 3 IBS: 0.2044094595924962
Fold 4 IBS: 0.20966584275861216
Fold 5 IBS: 0.211313413556971
[I 2024-04-14 16:53:21,567] Trial 94 finished with value: 0.21009966540267877 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 120, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5855639769841374, 'min_weight_fraction_leaf': 0.08355403368257994}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23520267938727427
Fold 2 IBS: 0.20116425107298522
Fold 3 IBS: 0.20510259876427595
Fold 4 IBS: 0.2176827586444227
Fold 5 IBS: 0.21292731974141504
[I 2024-04-14 16:53:23,933] Trial 95 finished with value: 0.21441592152207462 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 180, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8103082949117716, 'min_weight_fraction_leaf': 0.11381886996294271}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2366963489001733
Fold 2 IBS: 0.1837117121259892
Fold 3 IBS: 0.20226694531049833
Fold 4 IBS: 0.21335021541537497
Fold 5 IBS: 0.20661189736952593
[I 2024-04-14 16:53:26,052] Trial 96 finished with value: 0.20852742382431236 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 152, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7312350213287773, 'min_weight_fraction_leaf': 0.04898698424961209}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23608027081908015
Fold 2 IBS: 0.1835953504200279
Fold 3 IBS: 0.20150615985904316
Fold 4 IBS: 0.2102069690328971
Fold 5 IBS: 0.20748897405413733
[I 2024-04-14 16:53:28,148] Trial 97 finished with value: 0.20777554483703714 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 153, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6968965471814753, 'min_weight_fraction_leaf': 0.0505916256520447}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.23389009461942958
Fold 2 IBS: 0.18577086451211336
Fold 3 IBS: 0.20307358104865128
Fold 4 IBS: 0.2086430242358467
Fold 5 IBS: 0.2076497222974857
[I 2024-04-14 16:53:30,264] Trial 98 finished with value: 0.20780545734270534 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 138, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6887726496402962, 'min_weight_fraction_leaf': 0.04771137682412141}. Best is trial 71 with value: 0.20716724376288945.
Fold 1 IBS: 0.2434837934214731
Fold 2 IBS: 0.2272775037538945
Fold 3 IBS: 0.2265372467505086
Fold 4 IBS: 0.23746702398923994
Fold 5 IBS: 0.22710567134340368
[I 2024-04-14 16:53:32,164] Trial 99 finished with value: 0.23237424785170396 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 137, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6897878932245053, 'min_weight_fraction_leaf': 0.3195640033653079}. Best is trial 71 with value: 0.20716724376288945.


* Best trial for IBS:
 FrozenTrial(number=71, state=TrialState.COMPLETE, values=[0.20716724376288945], datetime_start=datetime.datetime(2024, 4, 14, 16, 52, 18, 707189), datetime_complete=datetime.datetime(2024, 4, 14, 16, 52, 19, 796036), params={'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 60, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6638490929451707, 'min_weight_fraction_leaf': 0.052914450220883674}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=71, value=None)


* Best Score for IBS:
 0.20716724376288945

In [54]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [55]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.764
train_ibs:  0.207

#### Test

In [56]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [57]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=6, max_features=None, max_leaf_nodes=13,
                   max_samples=0.9529576562335005, min_samples_split=15,
                   min_weight_fraction_leaf=0.05156899271012762,
                   n_estimators=376, random_state=123, warm_start=True)

C-index score: 0.543

ExtraSurvivalTrees(max_depth=19, max_features=None, max_leaf_nodes=17,
                   max_samples=0.6638490929451707, min_samples_leaf=2,
                   min_samples_split=19,
                   min_weight_fraction_leaf=0.052914450220883674,
                   n_estimators=60, oob_score=True, random_state=123)

IBS: 0.256

In [58]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [59]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 16:53:33,341] A new study created in memory with name: no-name-0a463761-879b-4ec8-a00c-1b344565fff0

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:53:57,774] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:54:10,739] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:54:22,141] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:54:42,599] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:54:52,899] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:54:55,228] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:55:16,004] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:55:22,552] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 16:55:23,272] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 16:56:18,298] Trial 9 finished with value: 0.7079199845805899 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7189922480620154
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 16:57:45,548] Trial 10 finished with value: 0.6677145778312712 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:00:02,666] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6593625498007968
Fold 2 C-index: 0.7577519379844961
Fold 3 C-index: 0.5936170212765958
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 17:01:25,270] Trial 12 finished with value: 0.6859221467184631 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:02:04,580] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:02:56,394] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:03:43,726] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:04:17,536] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:05:38,669] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:07:01,832] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:07:04,756] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:07:31,840] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 17:08:26,346] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7616279069767442
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6137339055793991
[I 2024-04-14 17:09:15,026] Trial 22 finished with value: 0.658086559263577 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:10:25,638] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:11:14,017] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:12:23,128] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:12:42,951] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:14:18,348] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:14:23,192] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:15:11,547] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:15:28,042] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-14 17:16:47,624] Trial 31 finished with value: 0.6020563220294257 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:18:15,131] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:19:07,628] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:19:54,269] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 17:20:27,096] Trial 35 finished with value: 0.6743933936379024 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:20:51,486] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:21:09,013] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:21:23,435] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:21:39,974] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:21:58,910] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7422480620155039
Fold 3 C-index: 0.5297872340425532
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6072961373390557
[I 2024-04-14 17:23:15,236] Trial 41 finished with value: 0.6433893503184027 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:24:06,608] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:25:05,829] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:25:22,653] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:27:00,665] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5916334661354582
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.7212765957446808
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6673819742489271
[I 2024-04-14 17:27:12,542] Trial 46 finished with value: 0.6994229841114794 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:27:26,142] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:27:26,422] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:27:34,399] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:28:12,659] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7655038759689923
Fold 3 C-index: 0.6617021276595745
Fold 4 C-index: 0.7547528517110266
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 17:28:49,346] Trial 51 finished with value: 0.6921806327884186 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:29:11,890] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.7079199845805899.
Fold 1 C-index: 0.5836653386454184
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7297872340425532
Fold 4 C-index: 0.7585551330798479
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 17:29:53,937] Trial 53 finished with value: 0.7081084979356779 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:30:30,950] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.053258307688877335, 'dropout_rate': 0.5787056799551111, 'n_estimators': 450, 'criterion': 'squared_error', 'ccp_alpha': 0.38565717736646804, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.8843751202328924, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:30:38,449] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.7287654482320323, 'learning_rate': 0.045017508094901654, 'dropout_rate': 0.8859792395781099, 'n_estimators': 289, 'criterion': 'squared_error', 'ccp_alpha': 0.7342456209458248, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.7838592561027189, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:31:18,684] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.23423646323682273, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 2.053064831619942, 'min_weight_fraction_leaf': 0.33405673650554374, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 16, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7509505703422054
Fold 5 C-index: 0.6416309012875536
[I 2024-04-14 17:31:23,754] Trial 57 finished with value: 0.7057479712796905 and parameters: {'subsample': 0.4065884568013973, 'learning_rate': 0.050487991666858245, 'dropout_rate': 0.997784793728882, 'n_estimators': 385, 'criterion': 'friedman_mse', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.20436269339736532, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8254593382612642, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:31:29,455] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.3508301340402865, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.1290450838056185, 'min_weight_fraction_leaf': 0.20680480896575482, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8192112766928122, 'min_samples_split': 15, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:31:37,701] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.38439789354607845, 'learning_rate': 0.06139147262733905, 'dropout_rate': 0.9474892480356638, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.23145092940437437, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:31:45,345] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.9260093630094106, 'learning_rate': 0.04877472827527357, 'dropout_rate': 0.9841116957888287, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.7893894780964769, 'min_weight_fraction_leaf': 0.18154324685428969, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.6488296420582099, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 7, 'max_depth': 1}. Best is trial 53 with value: 0.7081084979356779.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:31:56,061] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.8388194022639991, 'learning_rate': 0.05667950785553603, 'dropout_rate': 0.9141007682217919, 'n_estimators': 392, 'criterion': 'friedman_mse', 'ccp_alpha': 0.22684324682430845, 'min_weight_fraction_leaf': 0.1921565591082464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.8546947848451162, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 53 with value: 0.7081084979356779.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.723404255319149
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6673819742489271
[I 2024-04-14 17:32:19,037] Trial 62 finished with value: 0.712727180870049 and parameters: {'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6630901287553648
[I 2024-04-14 17:32:37,282] Trial 63 finished with value: 0.7108187349167132 and parameters: {'subsample': 0.423629566204322, 'learning_rate': 0.03438070971435433, 'dropout_rate': 0.8555425487679464, 'n_estimators': 482, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017994665418520434, 'min_weight_fraction_leaf': 0.2737163567412147, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07017568466241592, 'validation_fraction': 0.9620208724483128, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:32:59,525] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.4297477654076297, 'learning_rate': 0.043910428099002294, 'dropout_rate': 0.8352402756430523, 'n_estimators': 488, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4263511298787651, 'min_weight_fraction_leaf': 0.3160966031078735, 'max_features': 'sqrt', 'min_impurity_decrease': 0.07065062649817302, 'validation_fraction': 0.9463535838530875, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6416309012875536
[I 2024-04-14 17:33:26,108] Trial 65 finished with value: 0.6902478805446599 and parameters: {'subsample': 0.30781242416514565, 'learning_rate': 0.05113323137902576, 'dropout_rate': 0.7239851485767856, 'n_estimators': 454, 'criterion': 'friedman_mse', 'ccp_alpha': 0.0027463439227063506, 'min_weight_fraction_leaf': 0.26877432545564617, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0017887993094304819, 'validation_fraction': 0.761339316000577, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:33:40,287] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.48922080655608885, 'learning_rate': 0.035347527077929, 'dropout_rate': 0.8893092269739165, 'n_estimators': 417, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5356537836856377, 'min_weight_fraction_leaf': 0.29863354085488475, 'max_features': 'sqrt', 'min_impurity_decrease': 0.012061434840147687, 'validation_fraction': 0.9051978098851384, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:34:03,733] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.4210285565476828, 'learning_rate': 0.06591045167415374, 'dropout_rate': 0.8060412975360456, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.7762639994874865, 'min_weight_fraction_leaf': 0.25473199100313054, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00610717642726731, 'validation_fraction': 0.8093169248034847, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:34:14,756] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.36755564370451066, 'learning_rate': 0.05068902572826714, 'dropout_rate': 0.9726834213374217, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 1.1308236536377811, 'min_weight_fraction_leaf': 0.3065580571022596, 'max_features': 'sqrt', 'min_impurity_decrease': 0.021693222709295752, 'validation_fraction': 0.715818151257265, 'min_samples_split': 8, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:34:32,071] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.5142803470563067, 'learning_rate': 0.03243373478476426, 'dropout_rate': 0.9137837647742049, 'n_estimators': 459, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28985235680036014, 'min_weight_fraction_leaf': 0.4054829396615446, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001581139753892363, 'validation_fraction': 0.329118980782965, 'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:34:58,645] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.45559432833731667, 'learning_rate': 0.0700250470025932, 'dropout_rate': 0.8524549437406417, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6643601052078473, 'min_weight_fraction_leaf': 0.2388136010393243, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00031481444052736005, 'validation_fraction': 0.9166648433104408, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7771317829457365
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6373390557939914
[I 2024-04-14 17:35:31,128] Trial 71 finished with value: 0.6914213405066317 and parameters: {'subsample': 0.3096152191637527, 'learning_rate': 0.05014029765368843, 'dropout_rate': 0.72942553198655, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.027173150322083957, 'min_weight_fraction_leaf': 0.28439521854539385, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002459385698607316, 'validation_fraction': 0.9631122514300272, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:36:03,783] Trial 72 finished with value: 0.5 and parameters: {'subsample': 0.2984794016129376, 'learning_rate': 0.04184406116938292, 'dropout_rate': 0.6550072165726977, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.004791436061459352, 'min_weight_fraction_leaf': 0.28556030062342436, 'max_features': 'sqrt', 'min_impurity_decrease': 4.3401892914387e-05, 'validation_fraction': 0.9667204228379752, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:36:08,885] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.24177977569589332, 'learning_rate': 0.06081438305266998, 'dropout_rate': 0.7352912026497521, 'n_estimators': 178, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3565493126455575, 'min_weight_fraction_leaf': 0.2641618003854867, 'max_features': 'sqrt', 'min_impurity_decrease': 0.005565263987110645, 'validation_fraction': 0.8591928424609534, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:36:25,530] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.41766913987966564, 'learning_rate': 0.04837445328457708, 'dropout_rate': 0.7848778465425879, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9796884706123067, 'min_weight_fraction_leaf': 0.3487238233672823, 'max_features': 0.1, 'min_impurity_decrease': 0.060142707029694174, 'validation_fraction': 0.9742035251830021, 'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:36:39,333] Trial 75 finished with value: 0.5 and parameters: {'subsample': 0.14697123662254313, 'learning_rate': 0.056288895309512615, 'dropout_rate': 0.9249274443508626, 'n_estimators': 491, 'criterion': 'friedman_mse', 'ccp_alpha': 0.3014105775868996, 'min_weight_fraction_leaf': 0.2756234570388064, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5125842579708578e-05, 'validation_fraction': 0.9436471609372878, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:37:23,851] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.33597481611005453, 'learning_rate': 0.03785525432874416, 'dropout_rate': 0.5640100673453201, 'n_estimators': 465, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6095307820420031, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': 'log2', 'min_impurity_decrease': 0.009484910777116757, 'validation_fraction': 0.9018697914265744, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:38:05,301] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.3970316343863033, 'learning_rate': 0.02702816788183442, 'dropout_rate': 0.44124671276745586, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2997944075240355, 'min_weight_fraction_leaf': 0.38254401959264994, 'max_features': 1, 'min_impurity_decrease': 0.0031143423876080715, 'validation_fraction': 0.9903409642142473, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.6936170212765957
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6545064377682404
[I 2024-04-14 17:38:46,591] Trial 78 finished with value: 0.6992944115505685 and parameters: {'subsample': 0.22930387168853233, 'learning_rate': 0.05145553889741248, 'dropout_rate': 0.5044517635709308, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 0.02270996969784733, 'min_weight_fraction_leaf': 0.24788146923782178, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010045782837561419, 'validation_fraction': 0.8244464183531952, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:39:33,360] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.5787844954317829, 'learning_rate': 0.046320469166095994, 'dropout_rate': 0.4903660577547442, 'n_estimators': 481, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8369274241395267, 'min_weight_fraction_leaf': 0.3217471182217138, 'max_features': 'sqrt', 'min_impurity_decrease': 6.262467662262306e-05, 'validation_fraction': 0.822046932546052, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:40:02,630] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.25430148678930137, 'learning_rate': 0.04349582782163459, 'dropout_rate': 0.6081624319156314, 'n_estimators': 427, 'criterion': 'friedman_mse', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.20197769506016003, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010150765068526006, 'validation_fraction': 0.7818118403834172, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 9, 'max_depth': 8}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:40:32,878] Trial 81 finished with value: 0.5 and parameters: {'subsample': 0.18443408707190798, 'learning_rate': 0.05259966681355033, 'dropout_rate': 0.6449369275082966, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.23050623823206434, 'min_weight_fraction_leaf': 0.25144155938407586, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0013502467549795782, 'validation_fraction': 0.8730600269587929, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:41:28,694] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.21084564139781542, 'learning_rate': 0.0557198718851306, 'dropout_rate': 0.5142046015087244, 'n_estimators': 464, 'criterion': 'friedman_mse', 'ccp_alpha': 0.017868752517803354, 'min_weight_fraction_leaf': 0.22672177077398445, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00028049277519258663, 'validation_fraction': 0.9277470449701044, 'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:41:56,721] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.4945458790853893, 'learning_rate': 0.05895862835575055, 'dropout_rate': 0.7558273871774451, 'n_estimators': 438, 'criterion': 'friedman_mse', 'ccp_alpha': 0.501498258850682, 'min_weight_fraction_leaf': 0.28306768635206997, 'max_features': 'sqrt', 'min_impurity_decrease': 0.04144166385519717, 'validation_fraction': 0.8951513356732839, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 17:42:33,670] Trial 84 finished with value: 0.5444860535940432 and parameters: {'subsample': 0.3659778071469274, 'learning_rate': 0.0502270627847683, 'dropout_rate': 0.6818395627907664, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2606567709484204, 'min_weight_fraction_leaf': 0.2982881980338302, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0006662326950079798, 'validation_fraction': 0.8368533116927852, 'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:43:03,996] Trial 85 finished with value: 0.5 and parameters: {'subsample': 0.26399210031385845, 'learning_rate': 0.04714737148720377, 'dropout_rate': 0.5847508382404618, 'n_estimators': 406, 'criterion': 'friedman_mse', 'ccp_alpha': 0.9671659583078602, 'min_weight_fraction_leaf': 0.24391254579161395, 'max_features': 'log2', 'min_impurity_decrease': 0.000147849817010694, 'validation_fraction': 0.9991453937475061, 'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:43:07,307] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10060967717953817, 'learning_rate': 0.020768593047903114, 'dropout_rate': 0.4508818797021682, 'n_estimators': 110, 'criterion': 'squared_error', 'ccp_alpha': 0.625182110561999, 'min_weight_fraction_leaf': 0.2761510567632799, 'max_features': 1, 'min_impurity_decrease': 0.0023479607608161597, 'validation_fraction': 0.7423283408922972, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5319148936170213
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.5708154506437768
[I 2024-04-14 17:44:07,213] Trial 87 finished with value: 0.5635118483198402 and parameters: {'subsample': 0.43950121810340115, 'learning_rate': 0.0648732804536445, 'dropout_rate': 0.34957168713474945, 'n_estimators': 475, 'criterion': 'friedman_mse', 'ccp_alpha': 0.2369430535237365, 'min_weight_fraction_leaf': 0.3096474641971687, 'max_features': 0.1, 'min_impurity_decrease': 4.850175263275894e-05, 'validation_fraction': 0.951557506428991, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:44:22,007] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.21193910478383937, 'learning_rate': 0.06177410341848358, 'dropout_rate': 0.8846843251251039, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 1.2807191828912141, 'min_weight_fraction_leaf': 0.36091713798964337, 'max_features': 'sqrt', 'min_impurity_decrease': 3.0185550531810504e-05, 'validation_fraction': 0.8545724907452001, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:44:48,242] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.3182195088282702, 'learning_rate': 0.038485790496188235, 'dropout_rate': 0.5004748125823506, 'n_estimators': 350, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5179293303896771, 'min_weight_fraction_leaf': 0.3315564489154308, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00046699939753012373, 'validation_fraction': 0.9294234431035183, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:45:20,089] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.2762755336662733, 'learning_rate': 0.05273046932737523, 'dropout_rate': 0.5437417743878508, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.8405822272736876, 'min_weight_fraction_leaf': 0.43576713073659407, 'max_features': 'log2', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8767498848039622, 'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7810077519379846
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.6459227467811158
[I 2024-04-14 17:45:50,090] Trial 91 finished with value: 0.6948185874130767 and parameters: {'subsample': 0.3126184078929269, 'learning_rate': 0.051134988454074756, 'dropout_rate': 0.7292690956696949, 'n_estimators': 456, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03786277950879616, 'min_weight_fraction_leaf': 0.2673649069566119, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009910717111428719, 'validation_fraction': 0.7562406049799346, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.6195219123505976
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.7281368821292775
Fold 5 C-index: 0.6673819742489271
[I 2024-04-14 17:46:01,711] Trial 92 finished with value: 0.6989359122811389 and parameters: {'subsample': 0.335844111701364, 'learning_rate': 0.05038873458029908, 'dropout_rate': 0.9571283850291226, 'n_estimators': 449, 'criterion': 'friedman_mse', 'ccp_alpha': 0.046820443269266425, 'min_weight_fraction_leaf': 0.2690679137012573, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0008839215080019705, 'validation_fraction': 0.6636818720897245, 'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:46:18,180] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.33719220910486725, 'learning_rate': 0.05705464633480763, 'dropout_rate': 0.9535384595922254, 'n_estimators': 458, 'criterion': 'friedman_mse', 'ccp_alpha': 0.46107702292048336, 'min_weight_fraction_leaf': 0.21683645486742856, 'max_features': 'sqrt', 'min_impurity_decrease': 6.862155169827754e-06, 'validation_fraction': 0.6649080237925696, 'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5665236051502146
[I 2024-04-14 17:46:31,185] Trial 94 finished with value: 0.5133047210300429 and parameters: {'subsample': 0.3795391698153348, 'learning_rate': 0.05424992354992036, 'dropout_rate': 0.998020448184449, 'n_estimators': 483, 'criterion': 'friedman_mse', 'ccp_alpha': 0.25606469361498857, 'min_weight_fraction_leaf': 0.41683364220226815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0002584853980433294, 'validation_fraction': 0.7006781615049952, 'min_samples_split': 11, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:46:53,603] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8984320859036168, 'learning_rate': 0.04600776760199582, 'dropout_rate': 0.9375007175299167, 'n_estimators': 432, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6620944039517677, 'min_weight_fraction_leaf': 0.25977850599919555, 'max_features': 'sqrt', 'min_impurity_decrease': 0.001020092546254454, 'validation_fraction': 0.5743893910381555, 'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:47:10,161] Trial 96 finished with value: 0.5 and parameters: {'subsample': 0.9444669238877774, 'learning_rate': 0.03476407177203711, 'dropout_rate': 0.9688789578178828, 'n_estimators': 469, 'criterion': 'friedman_mse', 'ccp_alpha': 1.5985394199987468, 'min_weight_fraction_leaf': 0.4570304925648464, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0009757952163430444, 'validation_fraction': 0.7662521699162499, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 4}. Best is trial 62 with value: 0.712727180870049.

Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7848837209302325
Fold 3 C-index: 0.6659574468085107
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 17:47:27,703] Trial 97 finished with value: 0.6983542268255716 and parameters: {'subsample': 0.40802503425948106, 'learning_rate': 0.060600248591443, 'dropout_rate': 0.8994280356510341, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.16755337346680707, 'min_weight_fraction_leaf': 0.24511190648995798, 'max_features': 'sqrt', 'min_impurity_decrease': 8.96572949971136e-05, 'validation_fraction': 0.627628127325836, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 17:47:44,498] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.40520020589260825, 'learning_rate': 0.06969431851683794, 'dropout_rate': 0.852867621588153, 'n_estimators': 377, 'criterion': 'friedman_mse', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.23289524687485436, 'max_features': 'sqrt', 'min_impurity_decrease': 9.215043781245307e-05, 'validation_fraction': 0.6236577327109031, 'min_samples_split': 6, 'max_leaf_nodes': 12, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 62 with value: 0.712727180870049.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-14 17:47:57,067] A new study created in memory with name: no-name-8db2b802-8bfe-4b75-b6a7-563702f18abf

Fold 5 C-index: 0.5
[I 2024-04-14 17:47:57,046] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.4750010457704055, 'learning_rate': 0.04234673286327711, 'dropout_rate': 0.8983226388952166, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.0709913910444209, 'min_weight_fraction_leaf': 0.25005718600704474, 'max_features': 'log2', 'min_impurity_decrease': 0.0001309255892076454, 'validation_fraction': 0.6560219357259244, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 3}. Best is trial 62 with value: 0.712727180870049.


* Best trial for C-index:
 FrozenTrial(number=62, state=TrialState.COMPLETE, values=[0.712727180870049], datetime_start=datetime.datetime(2024, 4, 14, 17, 31, 56, 68410), datetime_complete=datetime.datetime(2024, 4, 14, 17, 32, 19, 36015), params={'subsample': 0.45214538811231725, 'learning_rate': 0.0513322635401625, 'dropout_rate': 0.8285090704895912, 'n_estimators': 485, 'criterion': 'friedman_mse', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.3101145382804477, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.9071319756271838, 'min_samples_split': 19, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 2}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=62, value=None)


* Best Score for C-index:
 0.712727180870049

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:48:18,743] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:48:29,777] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:48:41,446] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 17:48:58,329] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:49:05,998] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:49:07,980] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:49:29,062] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:49:36,241] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:49:36,877] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24603560357944756
Fold 2 IBS: 0.2303451757578765
Fold 3 IBS: 0.22864210229423013
Fold 4 IBS: 0.24084923849388645
Fold 5 IBS: 0.22856534560034253
[I 2024-04-14 17:50:24,788] Trial 9 finished with value: 0.2348874931451566 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316595760132136
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-14 17:51:39,137] Trial 10 finished with value: 0.2356341548121131 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 17:53:25,360] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24715496002116139
Fold 2 IBS: 0.23184438819341896
Fold 3 IBS: 0.2289550256511867
Fold 4 IBS: 0.24186707989824685
Fold 5 IBS: 0.2293129447586724
[I 2024-04-14 17:54:46,645] Trial 12 finished with value: 0.23582687970453725 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:55:27,818] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:56:32,856] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:57:30,777] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:58:11,888] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 17:59:47,653] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:00:28,360] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:00:37,317] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:02:13,953] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.24711009086064675
Fold 2 IBS: 0.23198651484788396
Fold 3 IBS: 0.22892152217671352
Fold 4 IBS: 0.2418944853641206
Fold 5 IBS: 0.2292311905787679
[I 2024-04-14 18:03:25,905] Trial 21 finished with value: 0.23582876076562656 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.2348874931451566.
Fold 1 IBS: 0.2461444810014907
Fold 2 IBS: 0.2300302068927662
Fold 3 IBS: 0.22866943981867105

Fold 4 IBS: 0.24076805673249593
Fold 5 IBS: 0.2286244137483669
[I 2024-04-14 18:04:46,880] Trial 22 finished with value: 0.23484731963875816 and parameters: {'subsample': 0.7703379696576829, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2075412325353082, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.23498585836708596, 'max_features': 'auto', 'min_impurity_decrease': 2.2280807107293784e-06, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:05:53,154] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7833792987413262, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.1885740234105539, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.30670771592114143, 'max_features': 'auto', 'min_impurity_decrease': 4.0191728056062143e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:06:44,477] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7585061975555163, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.4052509453727411, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 2.1800275042483763, 'min_weight_fraction_leaf': 0.3860022104310472, 'max_features': 'auto', 'min_impurity_decrease': 3.390771428589743e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:07:30,481] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.8600439675728072, 'min_weight_fraction_leaf': 0.1450251894982284, 'max_features': 'auto', 'min_impurity_decrease': 2.2807831758658776e-07, 'validation_fraction': 0.8062268184400477, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:08:33,491] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926327458794827, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.3244872301335504, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.22854151316208582, 'max_features': 1, 'min_impurity_decrease': 9.955077842567335e-07, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:08:39,793] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.35490072755339674, 'max_features': 'sqrt', 'min_impurity_decrease': 3.2061185368331345e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:09:00,645] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5977759332227619, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.5232204998663266, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 1.8030854984326539, 'min_weight_fraction_leaf': 0.17238265074851772, 'max_features': 0.1, 'min_impurity_decrease': 2.2600931711354275e-06, 'validation_fraction': 0.6048891087010804, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:09:54,144] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 9.47088471540121, 'min_weight_fraction_leaf': 0.07753988647420768, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:10:15,555] Trial 30 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.8423465978925959, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 6.501477828976682, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.069077873911092e-05, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2469488707078328
Fold 2 IBS: 0.23168626242435933
Fold 3 IBS: 0.22889748884171018
Fold 4 IBS: 0.24165979501668006
Fold 5 IBS: 0.22912802638333987
[I 2024-04-14 18:11:22,028] Trial 31 finished with value: 0.23566408867478444 and parameters: {'subsample': 0.9342733911728862, 'learning_rate': 0.004033940158421295, 'dropout_rate': 0.24954610099274321, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 1.6441939257193988e-06, 'validation_fraction': 0.9791544457816299, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.2462866194872135
Fold 2 IBS: 0.23015814957230293
Fold 3 IBS: 0.22867627879341337
Fold 4 IBS: 0.24075894829353398
Fold 5 IBS: 0.22871397901804405
[I 2024-04-14 18:12:30,203] Trial 32 finished with value: 0.23491879503290156 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.24434150110166794, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.2455979476942942, 'max_features': 'auto', 'min_impurity_decrease': 5.816626727344966e-07, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:13:21,204] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9811508635425625, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.16170735312728074, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 0.8198047813090782, 'min_weight_fraction_leaf': 0.2581627311002509, 'max_features': 'auto', 'min_impurity_decrease': 3.823502942432414e-07, 'validation_fraction': 0.8569494715719248, 'min_samples_split': 15, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:14:03,936] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6788757668057952, 'learning_rate': 0.013511407728298952, 'dropout_rate': 0.3027350351846827, 'n_estimators': 440, 'criterion': 'friedman_mse', 'ccp_alpha': 2.9624404981896113, 'min_weight_fraction_leaf': 0.3567860921105543, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0864589766034404e-07, 'validation_fraction': 0.9180915394001326, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:14:14,148] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7506305400130867, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.39085032430718913, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2968355577860917, 'min_weight_fraction_leaf': 0.1845482261035821, 'max_features': None, 'min_impurity_decrease': 5.604883172055218e-07, 'validation_fraction': 0.8124454957346336, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:15:59,305] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8897211155405627, 'learning_rate': 0.01834438189091409, 'dropout_rate': 0.21686014466597864, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.49771367623939483, 'max_features': 'auto', 'min_impurity_decrease': 2.1409313721837074e-07, 'validation_fraction': 0.6522001614770703, 'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:16:02,769] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9369342648165562, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.7511928761026783, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 2.0449109485892953, 'min_weight_fraction_leaf': 0.27692498935622, 'max_features': None, 'min_impurity_decrease': 1.853571633351626e-05, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 7}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:17:04,495] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6539493205119853, 'learning_rate': 0.0251329839154807, 'dropout_rate': 0.15548835641172376, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.4274244171697348, 'min_weight_fraction_leaf': 0.10389249654266602, 'max_features': 'auto', 'min_impurity_decrease': 6.975088573801349e-06, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:18:00,334] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.819260090248173, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.35516943724692895, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 1.096959016509903, 'min_weight_fraction_leaf': 0.24646517799340742, 'max_features': 1, 'min_impurity_decrease': 7.705817626656289e-07, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:19:07,148] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7159090434937541, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.10440441674205939, 'n_estimators': 349, 'criterion': 'squared_error', 'ccp_alpha': 0.5271979525545425, 'min_weight_fraction_leaf': 0.28834287014133914, 'max_features': 'auto', 'min_impurity_decrease': 3.319400649905563e-05, 'validation_fraction': 0.7118804245265347, 'min_samples_split': 9, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 9}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24665512418855506
Fold 2 IBS: 0.23079937875838777
Fold 3 IBS: 0.22859112956406855
Fold 4 IBS: 0.2411732320853091
Fold 5 IBS: 0.2289343835210694
[I 2024-04-14 18:21:06,578] Trial 41 finished with value: 0.23523064962347795 and parameters: {'subsample': 0.955074899022356, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.25927237673806974, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.23872879654763424, 'max_features': 'auto', 'min_impurity_decrease': 2.1025305618095657e-06, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 22 with value: 0.23484731963875816.
Fold 1 IBS: 0.24633993932293982
Fold 2 IBS: 0.23025272242517308
Fold 3 IBS: 0.22801274485299367
Fold 4 IBS: 0.24081637601730027
Fold 5 IBS: 0.22872083072116958
[I 2024-04-14 18:22:48,855] Trial 42 finished with value: 0.2348285226679153 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.21228719021921444, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.0025426530497991567, 'min_weight_fraction_leaf': 0.2463193046178017, 'max_features': 'auto', 'min_impurity_decrease': 2.0353002099552046e-07, 'validation_fraction': 0.9483244851205971, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:24:22,000] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8870095440480134, 'learning_rate': 0.007695749924738961, 'dropout_rate': 0.21196164237096157, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.4652348853622196, 'min_weight_fraction_leaf': 0.2462039407349756, 'max_features': 'auto', 'min_impurity_decrease': 2.4806498054532166e-06, 'validation_fraction': 0.9384593723722422, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:25:33,705] Trial 44 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9516464460878133, 'learning_rate': 0.016732701733156254, 'dropout_rate': 0.27891283672415945, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.6646055539220843, 'min_weight_fraction_leaf': 0.19458903511044723, 'max_features': 'auto', 'min_impurity_decrease': 2.7552659293421345e-07, 'validation_fraction': 0.8820166309308186, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24693882344056556
Fold 2 IBS: 0.23145350422053343
Fold 3 IBS: 0.22860307836669258
Fold 4 IBS: 0.24146437703078477
Fold 5 IBS: 0.22909817747073397
[I 2024-04-14 18:26:40,328] Trial 45 finished with value: 0.23551159210586206 and parameters: {'subsample': 0.851207043181185, 'learning_rate': 0.00772865480167541, 'dropout_rate': 0.41919571454938065, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.02780416658973445, 'min_weight_fraction_leaf': 0.1471159990131628, 'max_features': 0.1, 'min_impurity_decrease': 7.887971041460266e-07, 'validation_fraction': 0.7796431184086376, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:27:42,752] Trial 46 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.903902300700614, 'learning_rate': 0.020663703110871602, 'dropout_rate': 0.2360087051303405, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 1.1211917215603515, 'min_weight_fraction_leaf': 0.2669829255578892, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00010837584456603868, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 13, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 10}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:28:09,571] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7863074443514393, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.3647927170689298, 'n_estimators': 282, 'criterion': 'squared_error', 'ccp_alpha': 0.49254099261514095, 'min_weight_fraction_leaf': 0.22788144167141447, 'max_features': 'auto', 'min_impurity_decrease': 0.00034956311929619434, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:28:09,928] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9905645338262768, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.6802419581273266, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 2.9604431730961878, 'min_weight_fraction_leaf': 0.31320618069911565, 'max_features': None, 'min_impurity_decrease': 1.9122310255368836e-07, 'validation_fraction': 0.9525630618237567, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 19}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:28:25,937] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5635480809432041, 'learning_rate': 0.012482528907344474, 'dropout_rate': 0.5370645699291972, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 7.402025441081827, 'min_weight_fraction_leaf': 0.28176110536629334, 'max_features': 'log2', 'min_impurity_decrease': 6.857507616394684e-06, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:29:45,587] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.291494609951249, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.32212200830663856, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.814138078898914, 'min_weight_fraction_leaf': 0.2172289504658858, 'max_features': 'auto', 'min_impurity_decrease': 1.7140400747091528e-06, 'validation_fraction': 0.8988678158132096, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 7}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24695366408679845
Fold 2 IBS: 0.23146997904187452
Fold 3 IBS: 0.2285885733926773
Fold 4 IBS: 0.24149615706388644
Fold 5 IBS: 0.22910431519663427
[I 2024-04-14 18:30:47,016] Trial 51 finished with value: 0.2355225377563742 and parameters: {'subsample': 0.8432391250804372, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.42932457769018856, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.012243529086999924, 'min_weight_fraction_leaf': 0.13427213537405694, 'max_features': 0.1, 'min_impurity_decrease': 7.107322942000855e-07, 'validation_fraction': 0.7779173644820415, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:31:45,837] Trial 52 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8647416200425169, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.27204051720793454, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.32951036616207574, 'min_weight_fraction_leaf': 0.0696136715803943, 'max_features': 0.1, 'min_impurity_decrease': 1.0411636207736935e-06, 'validation_fraction': 0.6649885450408526, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 17}. Best is trial 42 with value: 0.2348285226679153.
Fold 1 IBS: 0.24641855308804925
Fold 2 IBS: 0.23048568622584525
Fold 3 IBS: 0.2278623120416157
Fold 4 IBS: 0.24068876716298668
Fold 5 IBS: 0.22857688144644517
[I 2024-04-14 18:32:34,134] Trial 53 finished with value: 0.2348064399929884 and parameters: {'subsample': 0.9101431135071837, 'learning_rate': 0.015420772490455037, 'dropout_rate': 0.35255575108470655, 'n_estimators': 430, 'criterion': 'squared_error', 'ccp_alpha': 0.009625013743012712, 'min_weight_fraction_leaf': 0.15399525160080688, 'max_features': 0.1, 'min_impurity_decrease': 5.869825897765074e-07, 'validation_fraction': 0.9519356083737385, 'min_samples_split': 11, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:33:43,554] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9637771314277555, 'learning_rate': 0.015659176215841897, 'dropout_rate': 0.18483741622154692, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.0421552533325045, 'min_weight_fraction_leaf': 0.16826656130652193, 'max_features': 0.1, 'min_impurity_decrease': 1.891916944791205e-07, 'validation_fraction': 0.9592695072789675, 'min_samples_split': 8, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:34:45,656] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.918589848048704, 'learning_rate': 0.023646082998228058, 'dropout_rate': 0.1366452847323028, 'n_estimators': 388, 'criterion': 'squared_error', 'ccp_alpha': 1.3381569877935875, 'min_weight_fraction_leaf': 0.18967222528443176, 'max_features': 'auto', 'min_impurity_decrease': 0.008146563872249941, 'validation_fraction': 0.8868940629916056, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 19, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:35:39,301] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7513175598857118, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.35760497570906596, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 0.6191574359540201, 'min_weight_fraction_leaf': 0.29279606045526263, 'max_features': 'auto', 'min_impurity_decrease': 1.1427991588661997e-07, 'validation_fraction': 0.9992935111116187, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 20}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:36:20,584] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9629672876565945, 'learning_rate': 0.03044321993695316, 'dropout_rate': 0.2654836627375681, 'n_estimators': 407, 'criterion': 'squared_error', 'ccp_alpha': 0.8695299124170429, 'min_weight_fraction_leaf': 0.3309371032482379, 'max_features': 0.1, 'min_impurity_decrease': 4.889527309942819e-07, 'validation_fraction': 0.8335980560573747, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:37:29,656] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9051869988846165, 'learning_rate': 0.01142320954300501, 'dropout_rate': 0.2230573971097521, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.46721256406858613, 'min_weight_fraction_leaf': 0.24217068500219807, 'max_features': 1, 'min_impurity_decrease': 3.3273145847446367e-06, 'validation_fraction': 0.9559266299158219, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:38:32,565] Trial 59 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4797314320866474, 'learning_rate': 0.019139926132660745, 'dropout_rate': 0.3062756368166816, 'n_estimators': 460, 'criterion': 'squared_error', 'ccp_alpha': 1.5137108127416434, 'min_weight_fraction_leaf': 0.21472425517002308, 'max_features': 'auto', 'min_impurity_decrease': 3.097931869672697e-07, 'validation_fraction': 0.5754933128881518, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 1}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:38:57,326] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7996511669090498, 'learning_rate': 0.004536438460163583, 'dropout_rate': 0.47747471244727363, 'n_estimators': 364, 'criterion': 'squared_error', 'ccp_alpha': 0.2543538004837033, 'min_weight_fraction_leaf': 0.10444758350906072, 'max_features': 'log2', 'min_impurity_decrease': 1.4854430366731937e-06, 'validation_fraction': 0.7293123113680127, 'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 9, 'max_depth': 14}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:39:41,693] Trial 61 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8595582024746382, 'learning_rate': 0.009662456499934472, 'dropout_rate': 0.4098250163413181, 'n_estimators': 423, 'criterion': 'squared_error', 'ccp_alpha': 0.2074917467600883, 'min_weight_fraction_leaf': 0.15724667461688366, 'max_features': 0.1, 'min_impurity_decrease': 7.257266102562462e-07, 'validation_fraction': 0.9258995897425243, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 15}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2468810203480293
Fold 2 IBS: 0.2311990963376084
Fold 3 IBS: 0.228454108036685
Fold 4 IBS: 0.24124096112643856
Fold 5 IBS: 0.22895207624265332
[I 2024-04-14 18:40:22,044] Trial 62 finished with value: 0.23534545241828292 and parameters: {'subsample': 0.9971515930608508, 'learning_rate': 0.01537203137740326, 'dropout_rate': 0.5939902455485113, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.006733098283166955, 'max_features': 0.1, 'min_impurity_decrease': 1.7338007602824288e-07, 'validation_fraction': 0.7998452500875314, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:41:05,141] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9881778214681738, 'learning_rate': 0.01464331603065807, 'dropout_rate': 0.505857528523121, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.7193047798389587, 'min_weight_fraction_leaf': 0.012712121434543151, 'max_features': 0.1, 'min_impurity_decrease': 1.7159806179406314e-07, 'validation_fraction': 0.8999002791146725, 'min_samples_split': 13, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 18}. Best is trial 53 with value: 0.2348064399929884.
Fold 1 IBS: 0.2465043054793762
Fold 2 IBS: 0.23031643211780425
Fold 3 IBS: 0.2279578986949742
Fold 4 IBS: 0.24045858876874635
Fold 5 IBS: 0.22854526131961184
[I 2024-04-14 18:41:39,681] Trial 64 finished with value: 0.23475649727610257 and parameters: {'subsample': 0.9996443016624725, 'learning_rate': 0.04209806464905699, 'dropout_rate': 0.6515053075848445, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.04245308337653099, 'min_weight_fraction_leaf': 0.044350095557314374, 'max_features': 0.1, 'min_impurity_decrease': 4.491377932515504e-07, 'validation_fraction': 0.9610335014089881, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-14 18:42:13,473] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9388732674648854, 'learning_rate': 0.04244875829612528, 'dropout_rate': 0.6822179842512692, 'n_estimators': 485, 'criterion': 'squared_error', 'ccp_alpha': 1.1144766988816432, 'min_weight_fraction_leaf': 0.08731759636169496, 'max_features': 'auto', 'min_impurity_decrease': 4.028739847312721e-07, 'validation_fraction': 0.9616704158537814, 'min_samples_split': 12, 'max_leaf_nodes': 20, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:42:49,553] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8952643616873973, 'learning_rate': 0.05359198006915804, 'dropout_rate': 0.6509686174553241, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 0.713342732410399, 'min_weight_fraction_leaf': 0.037327349410482574, 'max_features': 'auto', 'min_impurity_decrease': 2.2946753237767036e-06, 'validation_fraction': 0.8670144195682054, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:43:12,554] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9559398584951578, 'learning_rate': 0.001312025546225645, 'dropout_rate': 0.8046607423826502, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 2.5489077007647944, 'min_weight_fraction_leaf': 0.04508345598854374, 'max_features': 'sqrt', 'min_impurity_decrease': 5.750753876092619e-06, 'validation_fraction': 0.9116952163053982, 'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:44:09,512] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9243406312878238, 'learning_rate': 0.058088208137035593, 'dropout_rate': 0.19698157671040928, 'n_estimators': 426, 'criterion': 'friedman_mse', 'ccp_alpha': 5.997767788709036, 'min_weight_fraction_leaf': 0.2604144011776313, 'max_features': 0.1, 'min_impurity_decrease': 1.1827988873109092e-06, 'validation_fraction': 0.9998742352056981, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:44:58,234] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8260339189937393, 'learning_rate': 0.08587936719454789, 'dropout_rate': 0.23558185081536823, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 0.2896259420269614, 'min_weight_fraction_leaf': 0.2330662826063859, 'max_features': 'auto', 'min_impurity_decrease': 6.006710681053735e-05, 'validation_fraction': 0.9704861722747272, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:45:38,780] Trial 70 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6828274816486636, 'learning_rate': 0.027514255341309163, 'dropout_rate': 0.5905404972480945, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 9.324860864050404, 'min_weight_fraction_leaf': 0.12615077879430528, 'max_features': None, 'min_impurity_decrease': 5.222228681732963e-07, 'validation_fraction': 0.8455426922265927, 'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.2469128753364667
Fold 2 IBS: 0.23120680886119857
Fold 3 IBS: 0.2284490521729702
Fold 4 IBS: 0.2412928489959067
Fold 5 IBS: 0.22897078571077217
[I 2024-04-14 18:46:12,343] Trial 71 finished with value: 0.23536647421546286 and parameters: {'subsample': 0.9998892193300933, 'learning_rate': 0.015392294492197107, 'dropout_rate': 0.5823696005202688, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.027146006534983884, 'min_weight_fraction_leaf': 0.06445986479432256, 'max_features': 0.1, 'min_impurity_decrease': 2.7569586568543097e-07, 'validation_fraction': 0.9287673956828812, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24699640897951017
Fold 2 IBS: 0.23151620221444727
Fold 3 IBS: 0.22861416387399014
Fold 4 IBS: 0.24155860571648258
Fold 5 IBS: 0.22912133061238216
[I 2024-04-14 18:46:37,886] Trial 72 finished with value: 0.23556134227936246 and parameters: {'subsample': 0.9695012667210274, 'learning_rate': 0.009880743240604978, 'dropout_rate': 0.7234474037831898, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.004793672160551997, 'min_weight_fraction_leaf': 0.0006344109437541792, 'max_features': 0.1, 'min_impurity_decrease': 1.0311442565316877e-07, 'validation_fraction': 0.7967022266516048, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:46:41,952] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9999520023767101, 'learning_rate': 0.022493973992953744, 'dropout_rate': 0.6438577663377525, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.8094197161101034, 'min_weight_fraction_leaf': 0.019994854935207237, 'max_features': 0.1, 'min_impurity_decrease': 1.5918517921458393e-07, 'validation_fraction': 0.9395376003114264, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:48:12,620] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9393704884452911, 'learning_rate': 0.005281947478642466, 'dropout_rate': 0.12943958636926897, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.3686824833949447, 'min_weight_fraction_leaf': 0.053815083102964845, 'max_features': 0.1, 'min_impurity_decrease': 2.539937499874641e-07, 'validation_fraction': 0.8777634783146918, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:49:06,041] Trial 75 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8731051806028837, 'learning_rate': 0.019330707767774714, 'dropout_rate': 0.6082487085608025, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 1.3248769325723149, 'min_weight_fraction_leaf': 0.2959887591923328, 'max_features': 'auto', 'min_impurity_decrease': 4.7652746848926277e-07, 'validation_fraction': 0.9771406523907726, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:50:11,610] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9712736025274701, 'learning_rate': 0.01258123741877497, 'dropout_rate': 0.5558253337837517, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.2663511381103464, 'max_features': 0.1, 'min_impurity_decrease': 1.131669404349593e-05, 'validation_fraction': 0.687477001647036, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 18:51:18,029] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9040601608260395, 'learning_rate': 0.008028762030775153, 'dropout_rate': 0.1661055390191164, 'n_estimators': 412, 'criterion': 'squared_error', 'ccp_alpha': 0.5920167940309409, 'min_weight_fraction_leaf': 0.20760648939509768, 'max_features': 1, 'min_impurity_decrease': 1.2858411523836384e-06, 'validation_fraction': 0.7519570151291436, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 5}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:51:49,050] Trial 78 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9412481314247185, 'learning_rate': 0.003888190949209832, 'dropout_rate': 0.6251655088821374, 'n_estimators': 382, 'criterion': 'squared_error', 'ccp_alpha': 0.9892893740980914, 'min_weight_fraction_leaf': 0.033793930334568206, 'max_features': 'auto', 'min_impurity_decrease': 0.0002118263312796081, 'validation_fraction': 0.6158958959698865, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 11}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927107
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:53:28,289] Trial 79 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.5431112126281161, 'learning_rate': 0.030593840345293603, 'dropout_rate': 0.28940296100102497, 'n_estimators': 452, 'criterion': 'friedman_mse', 'ccp_alpha': 0.28778903589913546, 'min_weight_fraction_leaf': 0.17610538826721606, 'max_features': 'auto', 'min_impurity_decrease': 0.0868902507221412, 'validation_fraction': 0.8300457615159439, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 19}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:53:54,710] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9189279907539, 'learning_rate': 0.016793358093448018, 'dropout_rate': 0.3388723042222102, 'n_estimators': 301, 'criterion': 'squared_error', 'ccp_alpha': 1.8966699930906152, 'min_weight_fraction_leaf': 0.3543882746154796, 'max_features': 'log2', 'min_impurity_decrease': 1.4631830515812678e-07, 'validation_fraction': 0.5239331200177724, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 13}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24689956409794034
Fold 2 IBS: 0.23118732433711728
Fold 3 IBS: 0.22843302311048683
Fold 4 IBS: 0.24126338444926765
Fold 5 IBS: 0.22894778512748845
[I 2024-04-14 18:54:53,245] Trial 81 finished with value: 0.23534621622446011 and parameters: {'subsample': 0.9965114629683737, 'learning_rate': 0.015327246809846502, 'dropout_rate': 0.5609953054435709, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.02552688345155017, 'min_weight_fraction_leaf': 0.06929483396903219, 'max_features': 0.1, 'min_impurity_decrease': 2.622082619894755e-07, 'validation_fraction': 0.9164477820882341, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:55:50,318] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9805053749629268, 'learning_rate': 0.010886411260799844, 'dropout_rate': 0.5683084429638622, 'n_estimators': 470, 'criterion': 'squared_error', 'ccp_alpha': 0.2901659063159545, 'min_weight_fraction_leaf': 0.00019462069720194673, 'max_features': 0.1, 'min_impurity_decrease': 6.285047241123457e-07, 'validation_fraction': 0.9118209657927552, 'min_samples_split': 16, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:56:51,953] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6438413298708685, 'learning_rate': 0.02471644851386544, 'dropout_rate': 0.5202192733555178, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.6302736024968735, 'min_weight_fraction_leaf': 0.08484719071542221, 'max_features': 0.1, 'min_impurity_decrease': 3.0720666780466816e-07, 'validation_fraction': 0.8846072833938841, 'min_samples_split': 11, 'max_leaf_nodes': 15, 'min_samples_leaf': 20, 'max_depth': 15}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898150255235122
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293932698055425
[I 2024-04-14 18:57:22,409] Trial 84 finished with value: 0.23592730576033555 and parameters: {'subsample': 0.411624430892823, 'learning_rate': 0.014346557003820789, 'dropout_rate': 0.6984815756762216, 'n_estimators': 418, 'criterion': 'squared_error', 'ccp_alpha': 0.214835028703023, 'min_weight_fraction_leaf': 0.0519525894881867, 'max_features': 0.1, 'min_impurity_decrease': 3.906058893074947e-07, 'validation_fraction': 0.939166800936518, 'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 16}. Best is trial 64 with value: 0.23475649727610257.
Fold 1 IBS: 0.24536364898371674
Fold 2 IBS: 0.22661035397022303
Fold 3 IBS: 0.226596757813156
Fold 4 IBS: 0.2389442424082662
Fold 5 IBS: 0.22754912881625142
[I 2024-04-14 18:58:36,469] Trial 85 finished with value: 0.23301282639832266 and parameters: {'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 18:59:50,056] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8908016266221349, 'learning_rate': 0.020782252048892114, 'dropout_rate': 0.20248417164561996, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.8648012196087868, 'min_weight_fraction_leaf': 0.025928909209021245, 'max_features': 'auto', 'min_impurity_decrease': 9.529217204035409e-07, 'validation_fraction': 0.9780308436827329, 'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:00:18,962] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.953409887733455, 'learning_rate': 0.007217130157082901, 'dropout_rate': 0.2326599983541061, 'n_estimators': 266, 'criterion': 'squared_error', 'ccp_alpha': 0.4347343354489257, 'min_weight_fraction_leaf': 0.25406866786837123, 'max_features': 'auto', 'min_impurity_decrease': 2.642399797861587e-06, 'validation_fraction': 0.46137820435469984, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 10, 'max_depth': 8}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705

Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:01:42,170] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7762725560789899, 'learning_rate': 0.0030671608519508686, 'dropout_rate': 0.2500967923284591, 'n_estimators': 479, 'criterion': 'squared_error', 'ccp_alpha': 1.2742275973203492, 'min_weight_fraction_leaf': 0.27772784044341225, 'max_features': 'auto', 'min_impurity_decrease': 0.0011701047770450368, 'validation_fraction': 0.9552938036430088, 'min_samples_split': 13, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:03:03,332] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9240076064991638, 'learning_rate': 0.036372907201929795, 'dropout_rate': 0.16604269499086277, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.6288732373244443, 'min_weight_fraction_leaf': 0.1967537060613447, 'max_features': 'auto', 'min_impurity_decrease': 1.8368798466082297e-06, 'validation_fraction': 0.8456629128553931, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 10}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:04:23,016] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.3053150575440778, 'learning_rate': 0.00911659038630352, 'dropout_rate': 0.38100622127956474, 'n_estimators': 498, 'criterion': 'friedman_mse', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.22333957383529762, 'max_features': 'sqrt', 'min_impurity_decrease': 1.8349831120132606e-05, 'validation_fraction': 0.8011498496617241, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 14}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24648485188041894
Fold 2 IBS: 0.2305073947731919
Fold 3 IBS: 0.22795134549192056
Fold 4 IBS: 0.24057179186781263
Fold 5 IBS: 0.22853359304710397
[I 2024-04-14 19:05:35,805] Trial 91 finished with value: 0.23480979541208963 and parameters: {'subsample': 0.9762027146117168, 'learning_rate': 0.01642165444052923, 'dropout_rate': 0.2673714840258141, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.03810514873003644, 'min_weight_fraction_leaf': 0.012296492316215053, 'max_features': 0.1, 'min_impurity_decrease': 2.2249919821233818e-07, 'validation_fraction': 0.901410266511097, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:08:13,624] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.970200161496241, 'learning_rate': 0.012238074680872561, 'dropout_rate': 0.2583752131981347, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.20177590902847325, 'min_weight_fraction_leaf': 0.022776576304230935, 'max_features': 'auto', 'min_impurity_decrease': 2.0262506829884978e-07, 'validation_fraction': 0.9761923045843292, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 17}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:09:45,966] Trial 93 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9444060832329966, 'learning_rate': 0.017856303491279684, 'dropout_rate': 0.30303355573944185, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.4632988607005709, 'min_weight_fraction_leaf': 0.011908761872398903, 'max_features': 'auto', 'min_impurity_decrease': 6.055732421263935e-07, 'validation_fraction': 0.864284511598723, 'min_samples_split': 12, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 20}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:11:08,728] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8821760782294449, 'learning_rate': 0.005785552173633914, 'dropout_rate': 0.28058975756978766, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.8506324992317083, 'min_weight_fraction_leaf': 0.04622694094641695, 'max_features': None, 'min_impurity_decrease': 1.3402986834437386e-07, 'validation_fraction': 0.8985100287316004, 'min_samples_split': 11, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 18}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 19:12:59,724] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9761707513926794, 'learning_rate': 0.019567902784876703, 'dropout_rate': 0.3201948574529592, 'n_estimators': 482, 'criterion': 'squared_error', 'ccp_alpha': 1.0386964570043107, 'min_weight_fraction_leaf': 0.2390619554248597, 'max_features': 0.1, 'min_impurity_decrease': 7.882358999259736e-07, 'validation_fraction': 0.9417888137501867, 'min_samples_split': 14, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 19}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24641425402466968
Fold 2 IBS: 0.22943554006463165
Fold 3 IBS: 0.22871680820224374
Fold 4 IBS: 0.24077011514188554
Fold 5 IBS: 0.22840019828947677
[I 2024-04-14 19:14:43,309] Trial 96 finished with value: 0.2347473831445815 and parameters: {'subsample': 0.9088634226642077, 'learning_rate': 0.01055205151962401, 'dropout_rate': 0.22112152895475082, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.03063069674161246, 'min_weight_fraction_leaf': 0.09708890262536518, 'max_features': 'auto', 'min_impurity_decrease': 3.7395479538673736e-07, 'validation_fraction': 0.992337544991608, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:16:11,275] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8201377508003859, 'learning_rate': 0.010954886262406833, 'dropout_rate': 0.18321575541765564, 'n_estimators': 399, 'criterion': 'squared_error', 'ccp_alpha': 1.603167122698403, 'min_weight_fraction_leaf': 0.06013220413302209, 'max_features': 'auto', 'min_impurity_decrease': 3.972456306049239e-07, 'validation_fraction': 0.9976245698846969, 'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 19:17:08,943] Trial 98 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8505038223267275, 'learning_rate': 0.013402809510359784, 'dropout_rate': 0.21292319653614647, 'n_estimators': 354, 'criterion': 'squared_error', 'ccp_alpha': 0.25666428673598457, 'min_weight_fraction_leaf': 0.1129024126904408, 'max_features': 'auto', 'min_impurity_decrease': 3.4044321201945537e-06, 'validation_fraction': 0.9625603744870045, 'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 15, 'max_depth': 6}. Best is trial 85 with value: 0.23301282639832266.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 19:18:47,107] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9084360842440081, 'learning_rate': 0.06808689488183181, 'dropout_rate': 0.25443633448028735, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 0.5386043790221791, 'min_weight_fraction_leaf': 0.03403879613376609, 'max_features': 'auto', 'min_impurity_decrease': 8.69596280226011e-07, 'validation_fraction': 0.9221483446288596, 'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 85 with value: 0.23301282639832266.


* Best trial for IBS:
 FrozenTrial(number=85, state=TrialState.COMPLETE, values=[0.23301282639832266], datetime_start=datetime.datetime(2024, 4, 14, 18, 57, 22, 418559), datetime_complete=datetime.datetime(2024, 4, 14, 18, 58, 36, 467993), params={'subsample': 0.9481727373988897, 'learning_rate': 0.02022975259096714, 'dropout_rate': 0.2479619862207481, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.01138981446692314, 'min_weight_fraction_leaf': 0.026767353450782638, 'max_features': 'auto', 'min_impurity_decrease': 9.61920586779085e-07, 'validation_fraction': 0.973754058089352, 'min_samples_split': 14, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 8}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=85, value=None)


* Best Score for IBS:
 0.23301282639832266

In [60]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [61]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.713
train_ibs:  0.233

#### Test

In [62]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [63]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.022737959076050005,
                                 dropout_rate=0.8285090704895912,
                                 learning_rate=0.0513322635401625, max_depth=2,
                                 max_features='sqrt', max_leaf_nodes=10,
                                 min_impurity_decrease=0.002070496973827786,
                                 min_samples_leaf=15, min_samples_split=19,
                                 min_weight_fraction_leaf=0.3101145382804477,
                                 n_estimators=485, random_state=123,
                                 subsample=0.45214538811231725,
                                 validation_fraction=0.9071319756271838)

C-index score: 0.532

GradientBoostingSurvivalAnalysis(ccp_alpha=0.01138981446692314,
                                 criterion='squared_error',
                                 dropout_rate=0.2479619862207481,
                                 learning_rate=0.02022975259096714, max_depth=8,
                                 max_features='auto', max_leaf_nodes=20,
                                 min_impurity_decrease=9.61920586779085e-07,
                                 min_samples_leaf=18, min_samples_split=14,
                                 min_weight_fraction_leaf=0.026767353450782638,
                                 n_estimators=438, random_state=123,
                                 subsample=0.9481727373988897,
                                 validation_fraction=0.973754058089352)

IBS: 0.229

In [64]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [65]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 19:19:15,510] A new study created in memory with name: no-name-51142c8f-fd7a-45f6-96dd-cab1d3a40f2d

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 19:19:16,853] Trial 0 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 19:19:28,949] Trial 1 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 19:19:31,942] Trial 2 finished with value: 0.6248486830300205 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6248486830300205.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:19:34,585] Trial 3 finished with value: 0.6338486920671272 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6338486920671272.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:19:38,452] Trial 4 finished with value: 0.6384556422837688 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6384556422837688.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 19:19:43,565] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6384556422837688.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 19:19:46,684] Trial 6 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6384556422837688.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:19:47,228] Trial 7 finished with value: 0.632761721767193 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6384556422837688.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 19:19:51,622] Trial 8 finished with value: 0.624787126680312 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6384556422837688.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 19:20:04,120] Trial 9 finished with value: 0.623990313931308 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6384556422837688.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:20:12,573] Trial 10 finished with value: 0.6477560185192694 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6477560185192694.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:20:23,641] Trial 11 finished with value: 0.6569984857276479 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6569984857276479.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.6
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:20:30,357] Trial 12 finished with value: 0.657849549557435 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:20:39,547] Trial 13 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:20:46,779] Trial 14 finished with value: 0.6512176820000598 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:20:52,888] Trial 15 finished with value: 0.6407334301811473 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:21:06,184] Trial 16 finished with value: 0.6501610508698704 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:21:17,449] Trial 17 finished with value: 0.6368436983371611 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 19:21:23,476] Trial 18 finished with value: 0.6320487785694395 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 12 with value: 0.657849549557435.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:21:25,082] Trial 19 finished with value: 0.6560031140909454 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:21:39,847] Trial 20 finished with value: 0.6424033495535489 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 12 with value: 0.657849549557435.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:21:40,244] Trial 21 finished with value: 0.6590183243612687 and parameters: {'subsample': 0.11001094780860332, 'dropout_rate': 0.7075879968118339, 'n_estimators': 12, 'learning_rate': 0.09417886707495288}. Best is trial 21 with value: 0.6590183243612687.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:21:40,918] Trial 22 finished with value: 0.6466906671698898 and parameters: {'subsample': 0.18302526270385422, 'dropout_rate': 0.6797578358009322, 'n_estimators': 31, 'learning_rate': 0.09016744377002948}. Best is trial 21 with value: 0.6590183243612687.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:21:53,220] Trial 23 finished with value: 0.642956823576646 and parameters: {'subsample': 0.1529963084044875, 'dropout_rate': 0.8293972968657299, 'n_estimators': 311, 'learning_rate': 0.06523678593976207}. Best is trial 21 with value: 0.6590183243612687.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 19:21:56,422] Trial 24 finished with value: 0.6303935967217231 and parameters: {'subsample': 0.3073558694541275, 'dropout_rate': 0.9639676260548358, 'n_estimators': 125, 'learning_rate': 0.07736898361535043}. Best is trial 21 with value: 0.6590183243612687.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:21:57,848] Trial 25 finished with value: 0.6391476607819555 and parameters: {'subsample': 0.21578783290493656, 'dropout_rate': 0.5515081710932523, 'n_estimators': 71, 'learning_rate': 0.09163056701298726}. Best is trial 21 with value: 0.6590183243612687.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:22:03,260] Trial 26 finished with value: 0.6274237903261579 and parameters: {'subsample': 0.41348825424586344, 'dropout_rate': 0.5707562654379044, 'n_estimators': 245, 'learning_rate': 0.08146277028320098}. Best is trial 21 with value: 0.6590183243612687.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.6008583690987125
[I 2024-04-14 19:22:03,673] Trial 27 finished with value: 0.6672323922890245 and parameters: {'subsample': 0.1001314126580015, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.04133902891970489}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 19:22:04,098] Trial 28 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.6101749765323342, 'dropout_rate': 0.3080593480767576, 'n_estimators': 6, 'learning_rate': 0.03545838957871889}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 19:22:06,100] Trial 29 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.4175950896276197, 'n_estimators': 81, 'learning_rate': 0.023587776181838133}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7224334600760456
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 19:22:06,435] Trial 30 finished with value: 0.6486749970143832 and parameters: {'subsample': 0.2171908589366593, 'dropout_rate': 0.7839643216652376, 'n_estimators': 2, 'learning_rate': 0.05802531255595394}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 19:22:09,513] Trial 31 finished with value: 0.6553942708930214 and parameters: {'subsample': 0.10788468267704324, 'dropout_rate': 0.15299510312424375, 'n_estimators': 144, 'learning_rate': 0.04664278616838727}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:22:10,997] Trial 32 finished with value: 0.6444924736488598 and parameters: {'subsample': 0.15588315806842334, 'dropout_rate': 0.3066408799427648, 'n_estimators': 76, 'learning_rate': 0.09194646383389606}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:22:19,774] Trial 33 finished with value: 0.65201491859212 and parameters: {'subsample': 0.1011872748551087, 'dropout_rate': 0.18933339780585234, 'n_estimators': 328, 'learning_rate': 0.06992697841465893}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:22:31,015] Trial 34 finished with value: 0.6374993603601082 and parameters: {'subsample': 0.23006986904874288, 'dropout_rate': 0.5034858083626976, 'n_estimators': 394, 'learning_rate': 0.03743221620352713}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:22:38,230] Trial 35 finished with value: 0.6439606185763173 and parameters: {'subsample': 0.16710472630778297, 'dropout_rate': 0.6280259760400897, 'n_estimators': 275, 'learning_rate': 0.09477610565881699}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:22:43,809] Trial 36 finished with value: 0.6329687040178604 and parameters: {'subsample': 0.3137905210466839, 'dropout_rate': 0.13691793360905996, 'n_estimators': 224, 'learning_rate': 0.008583210939492603}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:22:46,928] Trial 37 finished with value: 0.6502911719819912 and parameters: {'subsample': 0.14175801988729114, 'dropout_rate': 0.20225663176365216, 'n_estimators': 169, 'learning_rate': 0.06535236904084048}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5617529880478087

Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:22:47,531] Trial 38 finished with value: 0.6343121093640922 and parameters: {'subsample': 0.24816424105467477, 'dropout_rate': 0.3720991365773877, 'n_estimators': 35, 'learning_rate': 0.024453949190947188}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:22:52,434] Trial 39 finished with value: 0.634540710565314 and parameters: {'subsample': 0.3071617415896747, 'dropout_rate': 0.4352656711347185, 'n_estimators': 287, 'learning_rate': 0.0757363212737669}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 19:23:01,917] Trial 40 finished with value: 0.6265654212274454 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.280971539366882, 'n_estimators': 333, 'learning_rate': 0.05707799213201073}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:23:02,726] Trial 41 finished with value: 0.654354813669098 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.7717495545874982, 'n_estimators': 57, 'learning_rate': 0.09604731261424589}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:23:04,070] Trial 42 finished with value: 0.6447099182493105 and parameters: {'subsample': 0.19475739706517295, 'dropout_rate': 0.6488239501185972, 'n_estimators': 105, 'learning_rate': 0.09533279635169574}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 19:23:04,499] Trial 43 finished with value: 0.6537680132647846 and parameters: {'subsample': 0.13840274528511398, 'dropout_rate': 0.748027864882098, 'n_estimators': 21, 'learning_rate': 0.0819966718177991}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:23:06,127] Trial 44 finished with value: 0.6470423810705285 and parameters: {'subsample': 0.1821621950521402, 'dropout_rate': 0.6051058564629677, 'n_estimators': 101, 'learning_rate': 0.04450424844427492}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 19:23:07,779] Trial 45 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.6919978071889705, 'n_estimators': 137, 'learning_rate': 0.09860374160211322}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:23:10,232] Trial 46 finished with value: 0.6486254007976564 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.4784300471361532, 'n_estimators': 164, 'learning_rate': 0.09308191830693073}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:23:13,522] Trial 47 finished with value: 0.6454820819537368 and parameters: {'subsample': 0.2783077588956623, 'dropout_rate': 0.13054548795135493, 'n_estimators': 191, 'learning_rate': 0.0858245365985523}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 19:23:14,107] Trial 48 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.5990656023377149, 'dropout_rate': 0.8394658701129177, 'n_estimators': 47, 'learning_rate': 0.07234662540082946}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:23:21,152] Trial 49 finished with value: 0.6415701803293052 and parameters: {'subsample': 0.1861830169994726, 'dropout_rate': 0.9035230782305808, 'n_estimators': 336, 'learning_rate': 0.0885003648070262}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:23:31,447] Trial 50 finished with value: 0.6544922400501442 and parameters: {'subsample': 0.13313157642661333, 'dropout_rate': 0.16748957532592004, 'n_estimators': 368, 'learning_rate': 0.09940058921163343}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:23:36,910] Trial 51 finished with value: 0.6560646704406539 and parameters: {'subsample': 0.10378351076047812, 'dropout_rate': 0.10061697611668895, 'n_estimators': 226, 'learning_rate': 0.045234267637431096}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:23:41,724] Trial 52 finished with value: 0.6535653061890192 and parameters: {'subsample': 0.11141401718218528, 'dropout_rate': 0.22025117734287722, 'n_estimators': 222, 'learning_rate': 0.05224169698208609}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:23:47,502] Trial 53 finished with value: 0.6452676674473093 and parameters: {'subsample': 0.1558764859494839, 'dropout_rate': 0.10910468865102452, 'n_estimators': 246, 'learning_rate': 0.03962379302349117}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:23:54,642] Trial 54 finished with value: 0.6423054367286009 and parameters: {'subsample': 0.22026323870387873, 'dropout_rate': 0.26549722943556975, 'n_estimators': 299, 'learning_rate': 0.0316002312907681}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:24:06,045] Trial 55 finished with value: 0.6460575987704443 and parameters: {'subsample': 0.17753220851893142, 'dropout_rate': 0.15105403923216587, 'n_estimators': 389, 'learning_rate': 0.04933426314529795}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:24:16,792] Trial 56 finished with value: 0.64866133342984 and parameters: {'subsample': 0.13622577382187898, 'dropout_rate': 0.7093900296728407, 'n_estimators': 479, 'learning_rate': 0.02706656481041731}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7325581395348837

Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 19:24:17,166] Trial 57 finished with value: 0.6496172356643461 and parameters: {'subsample': 0.10148636451698463, 'dropout_rate': 0.11083986970748202, 'n_estimators': 14, 'learning_rate': 0.04093261896548113}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:24:18,426] Trial 58 finished with value: 0.6336200908659054 and parameters: {'subsample': 0.26763995414649766, 'dropout_rate': 0.20622533277341337, 'n_estimators': 93, 'learning_rate': 0.014454507969820687}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:24:19,123] Trial 59 finished with value: 0.6407049298047238 and parameters: {'subsample': 0.1975829135463259, 'dropout_rate': 0.34111575281091094, 'n_estimators': 52, 'learning_rate': 0.08322655251020356}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:24:25,647] Trial 60 finished with value: 0.6462429620705572 and parameters: {'subsample': 0.2384354955746535, 'dropout_rate': 0.17804848501148132, 'n_estimators': 275, 'learning_rate': 0.0793027188584265}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:24:28,589] Trial 61 finished with value: 0.6521813961794806 and parameters: {'subsample': 0.1260542958713624, 'dropout_rate': 0.14127544924767882, 'n_estimators': 152, 'learning_rate': 0.043359766095211465}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:24:31,271] Trial 62 finished with value: 0.6470386567255175 and parameters: {'subsample': 0.16356163896469167, 'dropout_rate': 0.10030279950957244, 'n_estimators': 150, 'learning_rate': 0.046621411747576266}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:24:39,356] Trial 63 finished with value: 0.6520076133231948 and parameters: {'subsample': 0.10599039061556222, 'dropout_rate': 0.16421006806712515, 'n_estimators': 351, 'learning_rate': 0.054515039930700046}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:24:42,436] Trial 64 finished with value: 0.6486833762234505 and parameters: {'subsample': 0.16153040076535957, 'dropout_rate': 0.23151215601663055, 'n_estimators': 196, 'learning_rate': 0.062049332343317054}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:24:44,164] Trial 65 finished with value: 0.6276048784513688 and parameters: {'subsample': 0.9712842797437069, 'dropout_rate': 0.13283899373874214, 'n_estimators': 123, 'learning_rate': 0.04841446942458946}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:24:47,957] Trial 66 finished with value: 0.6496208994211937 and parameters: {'subsample': 0.10044908429402967, 'dropout_rate': 0.8013879348024215, 'n_estimators': 259, 'learning_rate': 0.03413668435240494}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:24:48,382] Trial 67 finished with value: 0.6437467548997808 and parameters: {'subsample': 0.1381270050578309, 'dropout_rate': 0.2875075669181043, 'n_estimators': 32, 'learning_rate': 0.09040420011239365}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:24:52,006] Trial 68 finished with value: 0.6400197927324061 and parameters: {'subsample': 0.20267214842284226, 'dropout_rate': 0.583662202262188, 'n_estimators': 214, 'learning_rate': 0.08538844637410783}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:24:56,346] Trial 69 finished with value: 0.6354206986145808 and parameters: {'subsample': 0.3301300289232047, 'dropout_rate': 0.2533289665882174, 'n_estimators': 235, 'learning_rate': 0.09534087490523474}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:25:01,402] Trial 70 finished with value: 0.6360468855881571 and parameters: {'subsample': 0.2404394342313974, 'dropout_rate': 0.9969638279429532, 'n_estimators': 318, 'learning_rate': 0.030541753347826425}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:25:10,629] Trial 71 finished with value: 0.6528659824219073 and parameters: {'subsample': 0.1307446395430722, 'dropout_rate': 0.17195216373818878, 'n_estimators': 372, 'learning_rate': 0.09996599016985482}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:25:20,060] Trial 72 finished with value: 0.6510952899999205 and parameters: {'subsample': 0.15454205151563974, 'dropout_rate': 0.19119217183630188, 'n_estimators': 395, 'learning_rate': 0.09791183342279408}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:25:31,557] Trial 73 finished with value: 0.6513303323496933 and parameters: {'subsample': 0.12541675018736928, 'dropout_rate': 0.15513913196739304, 'n_estimators': 444, 'learning_rate': 0.09350290547985371}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:25:38,374] Trial 74 finished with value: 0.6534061338705839 and parameters: {'subsample': 0.19687880260084517, 'dropout_rate': 0.1294387649003385, 'n_estimators': 296, 'learning_rate': 0.08831159798300985}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 19:25:46,522] Trial 75 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6882223870109341, 'dropout_rate': 0.5154917592158309, 'n_estimators': 350, 'learning_rate': 0.09651132721041242}. Best is trial 27 with value: 0.6672323922890245.

Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:25:53,595] Trial 76 finished with value: 0.6447358123747668 and parameters: {'subsample': 0.1678494435617333, 'dropout_rate': 0.7249905533828817, 'n_estimators': 374, 'learning_rate': 0.04120372333588131}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:25:53,917] Trial 77 finished with value: 0.6323857549453928 and parameters: {'subsample': 0.5163710444825687, 'dropout_rate': 0.21059615104780455, 'n_estimators': 18, 'learning_rate': 0.0930673886398354}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:25:55,214] Trial 78 finished with value: 0.6528807199465925 and parameters: {'subsample': 0.12380704786315203, 'dropout_rate': 0.1616449301010375, 'n_estimators': 71, 'learning_rate': 0.04671025756706187}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 19:25:55,509] Trial 79 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.4458132832072995, 'dropout_rate': 0.6542327138364529, 'n_estimators': 1, 'learning_rate': 0.09012222671516869}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:25:59,228] Trial 80 finished with value: 0.6529096441660722 and parameters: {'subsample': 0.1509936678119816, 'dropout_rate': 0.1259413090827059, 'n_estimators': 177, 'learning_rate': 0.03636293751465863}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:00,086] Trial 81 finished with value: 0.6511565494934075 and parameters: {'subsample': 0.11441080339464722, 'dropout_rate': 0.759685616263992, 'n_estimators': 55, 'learning_rate': 0.09998111838605074}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:01,103] Trial 82 finished with value: 0.6519859943726404 and parameters: {'subsample': 0.10256359224684265, 'dropout_rate': 0.7989004815641472, 'n_estimators': 64, 'learning_rate': 0.09713180491026206}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:01,690] Trial 83 finished with value: 0.6453724616981266 and parameters: {'subsample': 0.17356036382141982, 'dropout_rate': 0.7593343936863531, 'n_estimators': 36, 'learning_rate': 0.05206308367355849}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:03,501] Trial 84 finished with value: 0.6454198313530408 and parameters: {'subsample': 0.14104837298520134, 'dropout_rate': 0.8428910869331744, 'n_estimators': 133, 'learning_rate': 0.09419141542000956}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:05,516] Trial 85 finished with value: 0.6439537371504482 and parameters: {'subsample': 0.2157761282579256, 'dropout_rate': 0.3886491682466028, 'n_estimators': 113, 'learning_rate': 0.09706724547923658}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.6042553191489362
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 19:26:07,432] Trial 86 finished with value: 0.6572265196647168 and parameters: {'subsample': 0.11918286874044434, 'dropout_rate': 0.10103591217022476, 'n_estimators': 97, 'learning_rate': 0.0916673824323084}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:26:08,744] Trial 87 finished with value: 0.6551988690861813 and parameters: {'subsample': 0.18489307311086792, 'dropout_rate': 0.10156000758619717, 'n_estimators': 90, 'learning_rate': 0.0842071612349159}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:26:10,384] Trial 88 finished with value: 0.6501610508698704 and parameters: {'subsample': 0.18451427950557056, 'dropout_rate': 0.11701394042463877, 'n_estimators': 86, 'learning_rate': 0.08482375263125085}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:26:11,750] Trial 89 finished with value: 0.6560646704406539 and parameters: {'subsample': 0.1500419615016772, 'dropout_rate': 0.10587228470781848, 'n_estimators': 90, 'learning_rate': 0.08937488561673924}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 19:26:14,302] Trial 90 finished with value: 0.6528807199465925 and parameters: {'subsample': 0.11995083680675664, 'dropout_rate': 0.15251415416738312, 'n_estimators': 108, 'learning_rate': 0.07899287914626152}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:26:15,768] Trial 91 finished with value: 0.6560646704406539 and parameters: {'subsample': 0.14675068399505622, 'dropout_rate': 0.1084597649250081, 'n_estimators': 89, 'learning_rate': 0.08772159852885064}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:17,779] Trial 92 finished with value: 0.6517583842786275 and parameters: {'subsample': 0.14701354566348224, 'dropout_rate': 0.19612386617896727, 'n_estimators': 147, 'learning_rate': 0.08810260827561281}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 19:26:19,246] Trial 93 finished with value: 0.6314841479455716 and parameters: {'subsample': 0.99766016156918, 'dropout_rate': 0.13787821356621374, 'n_estimators': 123, 'learning_rate': 0.09121278765341481}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:20,528] Trial 94 finished with value: 0.6552748661043538 and parameters: {'subsample': 0.12478370714452525, 'dropout_rate': 0.1197043117115332, 'n_estimators': 97, 'learning_rate': 0.08077924912008731}. Best is trial 27 with value: 0.6672323922890245.

Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 19:26:21,949] Trial 95 finished with value: 0.6526528129963584 and parameters: {'subsample': 0.10096590323094773, 'dropout_rate': 0.17529214238387703, 'n_estimators': 71, 'learning_rate': 0.0881700065494207}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:22,870] Trial 96 finished with value: 0.6466117064563655 and parameters: {'subsample': 0.2539414960774812, 'dropout_rate': 0.11685242147930193, 'n_estimators': 39, 'learning_rate': 0.05873889729527442}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:26:25,365] Trial 97 finished with value: 0.6551988690861813 and parameters: {'subsample': 0.15982218883593097, 'dropout_rate': 0.14390196791205861, 'n_estimators': 138, 'learning_rate': 0.092844184878561}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 19:26:27,614] Trial 98 finished with value: 0.6409328367549579 and parameters: {'subsample': 0.21751962882042508, 'dropout_rate': 0.22396087436354034, 'n_estimators': 166, 'learning_rate': 0.037970790455906664}. Best is trial 27 with value: 0.6672323922890245.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475

[I 2024-04-14 19:26:29,410] A new study created in memory with name: no-name-1dc7712d-7b1d-4a56-bc3e-cf9d9c632afa

Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 19:26:29,386] Trial 99 finished with value: 0.6431421868767588 and parameters: {'subsample': 0.2883785045000756, 'dropout_rate': 0.10033205692891198, 'n_estimators': 118, 'learning_rate': 0.04356439415574297}. Best is trial 27 with value: 0.6672323922890245.


* Best trial for C-index:
 FrozenTrial(number=27, state=TrialState.COMPLETE, values=[0.6672323922890245], datetime_start=datetime.datetime(2024, 4, 14, 19, 22, 3, 267001), datetime_complete=datetime.datetime(2024, 4, 14, 19, 22, 3, 672966), params={'subsample': 0.1001314126580015, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.04133902891970489}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=27, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.1001314126580015, 'dropout_rate': 0.3060837787360696, 'n_estimators': 1, 'learning_rate': 0.04133902891970489}


* Best Score for C-index:
 0.6672323922890245

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.32184685283009035
Fold 2 IBS: 0.24269519626988276
Fold 3 IBS: 0.32845286241320015
Fold 4 IBS: 0.28361609336040605
Fold 5 IBS: 0.2729305473144034
[I 2024-04-14 19:26:30,792] Trial 0 finished with value: 0.2899083104375965 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.42279422613772155
Fold 2 IBS: 0.3901128382737591
Fold 3 IBS: 0.39247472286878254
Fold 4 IBS: 0.36956665696576196
Fold 5 IBS: 0.3399595615106552
[I 2024-04-14 19:26:46,184] Trial 1 finished with value: 0.3829816011513361 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38477559331402056
Fold 2 IBS: 0.2991181473015651
Fold 3 IBS: 0.37939668767639545
Fold 4 IBS: 0.3096779826388825
Fold 5 IBS: 0.3252308860734576
[I 2024-04-14 19:26:49,463] Trial 2 finished with value: 0.3396398594008642 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38791718483853127
Fold 2 IBS: 0.28109275090527497
Fold 3 IBS: 0.38075337593630443
Fold 4 IBS: 0.30896380743221213
Fold 5 IBS: 0.33290864228938033
[I 2024-04-14 19:26:52,733] Trial 3 finished with value: 0.3383271522803406 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38792738170860425
Fold 2 IBS: 0.28031022316536996
Fold 3 IBS: 0.3832060130514111
Fold 4 IBS: 0.306682096465873
Fold 5 IBS: 0.3382261071090519
[I 2024-04-14 19:26:58,804] Trial 4 finished with value: 0.3392703643000621 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.41105192261386453
Fold 2 IBS: 0.3777174719916462
Fold 3 IBS: 0.3915300176353505
Fold 4 IBS: 0.3447295660931382
Fold 5 IBS: 0.32992002164058554
[I 2024-04-14 19:27:07,827] Trial 5 finished with value: 0.370989799994917 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.2950866836605978
Fold 2 IBS: 0.21617356864727175
Fold 3 IBS: 0.2960476577766528
Fold 4 IBS: 0.26116838532173825
Fold 5 IBS: 0.2492059247499634
[I 2024-04-14 19:27:13,747] Trial 6 finished with value: 0.2635364440312448 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2635364440312448.
Fold 1 IBS: 0.2525596717266013
Fold 2 IBS: 0.20163074155150337
Fold 3 IBS: 0.2554759579529817
Fold 4 IBS: 0.22423261256383803
Fold 5 IBS: 0.2116650686406854
[I 2024-04-14 19:27:15,278] Trial 7 finished with value: 0.22911281048712198 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.32773085091505505
Fold 2 IBS: 0.24764667449835662
Fold 3 IBS: 0.3381279691027075
Fold 4 IBS: 0.28727873359875167
Fold 5 IBS: 0.2819856805230031
[I 2024-04-14 19:27:19,058] Trial 8 finished with value: 0.2965539817275748 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.4128629984024713
Fold 2 IBS: 0.3805312612875153
Fold 3 IBS: 0.39180424534594577
Fold 4 IBS: 0.3483594650353357
Fold 5 IBS: 0.3350263678028636
[I 2024-04-14 19:27:31,927] Trial 9 finished with value: 0.3737168675748263 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.24690378026135393
Fold 2 IBS: 0.230918196199329
Fold 3 IBS: 0.2288651535714008
Fold 4 IBS: 0.24118860634197958
Fold 5 IBS: 0.22809859267819335
[I 2024-04-14 19:27:32,535] Trial 10 finished with value: 0.23519486581045132 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.24596520377467238
Fold 2 IBS: 0.22745516260233242
Fold 3 IBS: 0.22872408268029404
Fold 4 IBS: 0.23875682318201075
Fold 5 IBS: 0.22421110618785597
[I 2024-04-14 19:27:32,984] Trial 11 finished with value: 0.2330224756854331 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.2726084712112609
Fold 2 IBS: 0.21208678219728053
Fold 3 IBS: 0.29979781497918323
Fold 4 IBS: 0.24218691205683326
Fold 5 IBS: 0.23895352312088064
[I 2024-04-14 19:27:34,056] Trial 12 finished with value: 0.2531267007130877 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.24540145164058172
Fold 2 IBS: 0.22486461618174694
Fold 3 IBS: 0.2288799372028231
Fold 4 IBS: 0.23700499011587697
Fold 5 IBS: 0.22141183261877637
[I 2024-04-14 19:27:34,525] Trial 13 finished with value: 0.23151256555196104 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.2801288012575852
Fold 2 IBS: 0.20604672080743208
Fold 3 IBS: 0.2855821246683042
Fold 4 IBS: 0.2448269379427668
Fold 5 IBS: 0.23496945372244868
[I 2024-04-14 19:27:36,427] Trial 14 finished with value: 0.2503108076797074 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.34250383730825085
Fold 2 IBS: 0.2566809689410792
Fold 3 IBS: 0.35681785243304703
Fold 4 IBS: 0.2914232791743898
Fold 5 IBS: 0.29999553893473496
[I 2024-04-14 19:27:38,513] Trial 15 finished with value: 0.30948429535830035 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.3500604721890909
Fold 2 IBS: 0.2455317991789678
Fold 3 IBS: 0.35395568084206236
Fold 4 IBS: 0.2820227934607856
Fold 5 IBS: 0.31326887829101346
[I 2024-04-14 19:27:44,796] Trial 16 finished with value: 0.3089679247923841 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22911281048712198.
Fold 1 IBS: 0.24607714741491096
Fold 2 IBS: 0.21115546325606438
Fold 3 IBS: 0.23474191594216773
Fold 4 IBS: 0.2296381561690892
Fold 5 IBS: 0.21122928902161456
[I 2024-04-14 19:27:45,664] Trial 17 finished with value: 0.2265683943607694 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2883901804573134
Fold 2 IBS: 0.2112037980068735
Fold 3 IBS: 0.28770446755792806
Fold 4 IBS: 0.2544520687837577
Fold 5 IBS: 0.2431612806129336
[I 2024-04-14 19:27:51,362] Trial 18 finished with value: 0.2569823590837612 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.27019935319228533
Fold 2 IBS: 0.20115571960710218

Fold 3 IBS: 0.27495840642227154
Fold 4 IBS: 0.2403770465027076
Fold 5 IBS: 0.22389919673997055
[I 2024-04-14 19:27:53,162] Trial 19 finished with value: 0.24211794449286744 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24532728078212304
Fold 2 IBS: 0.21338053568843193
Fold 3 IBS: 0.23280583204014674
Fold 4 IBS: 0.23050963160208696
Fold 5 IBS: 0.21229213294998353
[I 2024-04-14 19:27:54,323] Trial 20 finished with value: 0.22686308261255445 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480948267779246
Fold 2 IBS: 0.217894217650721
Fold 3 IBS: 0.23043919128917217
Fold 4 IBS: 0.23275995527788665
Fold 5 IBS: 0.215372968667489
[I 2024-04-14 19:27:55,171] Trial 21 finished with value: 0.22825516311261226 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24643766317823718
Fold 2 IBS: 0.22924023219100237
Fold 3 IBS: 0.2287550024184287
Fold 4 IBS: 0.2400059006469264
Fold 5 IBS: 0.2262805735657194
[I 2024-04-14 19:27:56,011] Trial 22 finished with value: 0.23414387440006285 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.257478169662288
Fold 2 IBS: 0.20248903467735407
Fold 3 IBS: 0.252469752257427
Fold 4 IBS: 0.23159280968783177
Fold 5 IBS: 0.2169495351817077
[I 2024-04-14 19:27:57,711] Trial 23 finished with value: 0.2321958602933217 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24591385980787991
Fold 2 IBS: 0.21157801995971165
Fold 3 IBS: 0.23448495664364996
Fold 4 IBS: 0.229737329537672
Fold 5 IBS: 0.2112912785040094
[I 2024-04-14 19:27:58,384] Trial 24 finished with value: 0.22660108889058458 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2756443151410581
Fold 2 IBS: 0.20473874541146792
Fold 3 IBS: 0.27375023358490214
Fold 4 IBS: 0.2440459127498442
Fold 5 IBS: 0.23246982801186947
[I 2024-04-14 19:27:59,890] Trial 25 finished with value: 0.2461298069798284 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.32538815518873926
Fold 2 IBS: 0.2468744663909679
Fold 3 IBS: 0.3332171412462654
Fold 4 IBS: 0.28581063346445296
Fold 5 IBS: 0.2781065825703804
[I 2024-04-14 19:28:02,952] Trial 26 finished with value: 0.29387939577216116 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24492083546093882
Fold 2 IBS: 0.21628333393840363
Fold 3 IBS: 0.23138494832945591
Fold 4 IBS: 0.23162572469168902
Fold 5 IBS: 0.21394160498647347
[I 2024-04-14 19:28:04,085] Trial 27 finished with value: 0.2276312894813922 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24503999552218353
Fold 2 IBS: 0.21507419381927734
Fold 3 IBS: 0.23200152410434108
Fold 4 IBS: 0.23109618679052704
Fold 5 IBS: 0.21308573107611234
[I 2024-04-14 19:28:05,246] Trial 28 finished with value: 0.22725952626248827 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3030591065047406
Fold 2 IBS: 0.22336679794652556
Fold 3 IBS: 0.3044396799522218
Fold 4 IBS: 0.2678287080975696
Fold 5 IBS: 0.25695858296703405
[I 2024-04-14 19:28:07,380] Trial 29 finished with value: 0.2711305750936183 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.30057401042692355
Fold 2 IBS: 0.22109327570196485
Fold 3 IBS: 0.30174720098020524
Fold 4 IBS: 0.2651400266811706
Fold 5 IBS: 0.2537066735825353
[I 2024-04-14 19:28:09,924] Trial 30 finished with value: 0.26845223747455993 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24486090508062983
Fold 2 IBS: 0.21682633491745948
Fold 3 IBS: 0.23109486987541575
Fold 4 IBS: 0.23197486961623204
Fold 5 IBS: 0.21430589760825255
[I 2024-04-14 19:28:11,092] Trial 31 finished with value: 0.22781257541959793 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480604491948196
Fold 2 IBS: 0.21843195389759032
Fold 3 IBS: 0.23024293091022538
Fold 4 IBS: 0.23321504110381971
Fold 5 IBS: 0.21568765554273314
[I 2024-04-14 19:28:11,792] Trial 32 finished with value: 0.2284767252747701 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24434472696223403
Fold 2 IBS: 0.22006483265789914
Fold 3 IBS: 0.23001501374819164
Fold 4 IBS: 0.23353575529737952
Fold 5 IBS: 0.21714562015932423
[I 2024-04-14 19:28:13,073] Trial 33 finished with value: 0.2290211897650057 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25788116008451006
Fold 2 IBS: 0.20226079778720082
Fold 3 IBS: 0.2544783586806218
Fold 4 IBS: 0.23143342088904706
Fold 5 IBS: 0.21567691855898308
[I 2024-04-14 19:28:14,718] Trial 34 finished with value: 0.23234613120007258 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24665787355022445
Fold 2 IBS: 0.23001468040084486
Fold 3 IBS: 0.228802523121071
Fold 4 IBS: 0.24061435934394168
Fold 5 IBS: 0.2271257607053576
[I 2024-04-14 19:28:15,065] Trial 35 finished with value: 0.2346430394242879 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.36295049794153883
Fold 2 IBS: 0.27664373471149467
Fold 3 IBS: 0.3675445917607911
Fold 4 IBS: 0.3032504418743303
Fold 5 IBS: 0.311762833506537
[I 2024-04-14 19:28:24,891] Trial 36 finished with value: 0.3244304199589384 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3956248057488727
Fold 2 IBS: 0.3238900936919387
Fold 3 IBS: 0.38499901982444784
Fold 4 IBS: 0.31514930414846015
Fold 5 IBS: 0.3335159079818787
[I 2024-04-14 19:28:28,026] Trial 37 finished with value: 0.35063582627911966 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25969526762239703
Fold 2 IBS: 0.20212138827340803
Fold 3 IBS: 0.25611019690719544

Fold 4 IBS: 0.23376225132374828
Fold 5 IBS: 0.21475575962300342
[I 2024-04-14 19:28:30,584] Trial 38 finished with value: 0.23328897274995045 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.29108106719697524
Fold 2 IBS: 0.21415810554809628
Fold 3 IBS: 0.2917820507930866
Fold 4 IBS: 0.2588982634047282
Fold 5 IBS: 0.24407574900323586
[I 2024-04-14 19:28:31,375] Trial 39 finished with value: 0.25999904718922445 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2925659515921918
Fold 2 IBS: 0.2140746731129848
Fold 3 IBS: 0.2919432513336724
Fold 4 IBS: 0.257477121073266
Fold 5 IBS: 0.24657769529804316
[I 2024-04-14 19:28:32,508] Trial 40 finished with value: 0.2605277384820316 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24534003818367572
Fold 2 IBS: 0.21351313222790674
Fold 3 IBS: 0.23284352524242438
Fold 4 IBS: 0.2304630885922339
Fold 5 IBS: 0.21224567728236968
[I 2024-04-14 19:28:33,050] Trial 41 finished with value: 0.22688109230572212 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485006409680624
Fold 2 IBS: 0.21706394797525833
Fold 3 IBS: 0.23093672935586954
Fold 4 IBS: 0.23224267333240983
Fold 5 IBS: 0.21443505260308193
[I 2024-04-14 19:28:33,449] Trial 42 finished with value: 0.22790569347268522 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2638458495823219
Fold 2 IBS: 0.2020440306627012
Fold 3 IBS: 0.2599892350953784
Fold 4 IBS: 0.2353149724721722
Fold 5 IBS: 0.2221900668187372
[I 2024-04-14 19:28:34,510] Trial 43 finished with value: 0.2366768309262622 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2455964708749073
Fold 2 IBS: 0.22570478266765567
Fold 3 IBS: 0.228795022876604
Fold 4 IBS: 0.23752979609395375
Fold 5 IBS: 0.22236478482517102
[I 2024-04-14 19:28:35,088] Trial 44 finished with value: 0.23199817146765836 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24519921983594833
Fold 2 IBS: 0.22330524452579645
Fold 3 IBS: 0.2290157433965299
Fold 4 IBS: 0.23588777848641265
Fold 5 IBS: 0.2204866110425217
[I 2024-04-14 19:28:35,499] Trial 45 finished with value: 0.2307789194574418 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.34065073189493716
Fold 2 IBS: 0.2597363049038525
Fold 3 IBS: 0.3496713953679775
Fold 4 IBS: 0.2946768758327706
Fold 5 IBS: 0.29269474527583145
[I 2024-04-14 19:28:37,404] Trial 46 finished with value: 0.30748601065507386 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25039205968447736
Fold 2 IBS: 0.1983007752957413
Fold 3 IBS: 0.2539048960518954
Fold 4 IBS: 0.22477789659354785
Fold 5 IBS: 0.21270184763960173
[I 2024-04-14 19:28:38,206] Trial 47 finished with value: 0.2280154950530527 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2556573719237732
Fold 2 IBS: 0.20234787848056301
Fold 3 IBS: 0.2522638016406119
Fold 4 IBS: 0.23093407281830788
Fold 5 IBS: 0.21250246234410652
[I 2024-04-14 19:28:40,952] Trial 48 finished with value: 0.23074111744147255 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24675070321456416
Fold 2 IBS: 0.23043515587015717
Fold 3 IBS: 0.2288281703390381
Fold 4 IBS: 0.2408551079349057
Fold 5 IBS: 0.22755526151412517
[I 2024-04-14 19:28:41,226] Trial 49 finished with value: 0.23488487977455805 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.26805889781388065
Fold 2 IBS: 0.20252886898813807
Fold 3 IBS: 0.26533134677822295
Fold 4 IBS: 0.23829437556390634
Fold 5 IBS: 0.22589258667890266
[I 2024-04-14 19:28:42,601] Trial 50 finished with value: 0.2400212151646101 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24512963190106926
Fold 2 IBS: 0.2147274537502438
Fold 3 IBS: 0.2321986628737604
Fold 4 IBS: 0.23091267007941935
Fold 5 IBS: 0.21292902132889352
[I 2024-04-14 19:28:43,147] Trial 51 finished with value: 0.22717948798667725 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24662205885932792
Fold 2 IBS: 0.22993687263943438
Fold 3 IBS: 0.22879053467216642
Fold 4 IBS: 0.24048347407202147
Fold 5 IBS: 0.22699896965015748
[I 2024-04-14 19:28:43,856] Trial 52 finished with value: 0.23456638197862154 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485579223129506
Fold 2 IBS: 0.21998745903015368
Fold 3 IBS: 0.22977573478865335
Fold 4 IBS: 0.23404920712862456
Fold 5 IBS: 0.21705606342896017
[I 2024-04-14 19:28:44,380] Trial 53 finished with value: 0.22914485132153736 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2531442464481051
Fold 2 IBS: 0.20414594462184135
Fold 3 IBS: 0.2459059794082717
Fold 4 IBS: 0.22963377950406882
Fold 5 IBS: 0.21079567993043571
[I 2024-04-14 19:28:44,769] Trial 54 finished with value: 0.22872512598254455 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2524170789262838
Fold 2 IBS: 0.20420643525007415
Fold 3 IBS: 0.24534527368601658
Fold 4 IBS: 0.2294272521646032
Fold 5 IBS: 0.21300726025333291
[I 2024-04-14 19:28:45,829] Trial 55 finished with value: 0.22888066005606209 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24626134547224643
Fold 2 IBS: 0.21072141911440245
Fold 3 IBS: 0.23515116577403225
Fold 4 IBS: 0.22942525598464827
Fold 5 IBS: 0.21111562686038168
[I 2024-04-14 19:28:46,415] Trial 56 finished with value: 0.22653496264114223 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.32236762054514384
Fold 2 IBS: 0.24369761993112318
Fold 3 IBS: 0.32961555540384646
Fold 4 IBS: 0.28411316345226234

Fold 5 IBS: 0.27450442032616973
[I 2024-04-14 19:28:49,814] Trial 57 finished with value: 0.29085967593170914 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2514876544143989
Fold 2 IBS: 0.20473165445913052
Fold 3 IBS: 0.2442786298594191
Fold 4 IBS: 0.2292932477615486
Fold 5 IBS: 0.2122783863810015
[I 2024-04-14 19:28:50,406] Trial 58 finished with value: 0.2284139145750997 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2450009034050451
Fold 2 IBS: 0.21574021216390366
Fold 3 IBS: 0.2316126494096215
Fold 4 IBS: 0.2313085066143514
Fold 5 IBS: 0.2135215585555951
[I 2024-04-14 19:28:50,762] Trial 59 finished with value: 0.22743676602970336 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.27643234236120234
Fold 2 IBS: 0.20531960631582807
Fold 3 IBS: 0.2756328535259464
Fold 4 IBS: 0.24566178547120296
Fold 5 IBS: 0.23379390635926353
[I 2024-04-14 19:28:51,911] Trial 60 finished with value: 0.24736809880668864 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24511487846402005
Fold 2 IBS: 0.2227836793360944
Fold 3 IBS: 0.22915537398733413
Fold 4 IBS: 0.2355788750800659
Fold 5 IBS: 0.21936511210219634
[I 2024-04-14 19:28:52,670] Trial 61 finished with value: 0.23039958379394215 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.25492402733786423
Fold 2 IBS: 0.2031585290599715
Fold 3 IBS: 0.24895077307909572
Fold 4 IBS: 0.2303647335144685
Fold 5 IBS: 0.21487736782477726
[I 2024-04-14 19:28:53,611] Trial 62 finished with value: 0.23045508616323543 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24531708021685963
Fold 2 IBS: 0.22395449249387253
Fold 3 IBS: 0.22892582490539293
Fold 4 IBS: 0.23652996695441353
Fold 5 IBS: 0.2211888183692411
[I 2024-04-14 19:28:54,105] Trial 63 finished with value: 0.23118323658795595 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24543346554687298
Fold 2 IBS: 0.21302518909492982
Fold 3 IBS: 0.23348544240148608
Fold 4 IBS: 0.22993870744839895
Fold 5 IBS: 0.21193762927195595
[I 2024-04-14 19:28:54,743] Trial 64 finished with value: 0.22676408675272874 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24427299434478603
Fold 2 IBS: 0.2145724066475789
Fold 3 IBS: 0.23244031403754764
Fold 4 IBS: 0.2308013778601708
Fold 5 IBS: 0.21301937769687632
[I 2024-04-14 19:28:55,439] Trial 65 finished with value: 0.22702129411739191 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24414268593072253
Fold 2 IBS: 0.21442849246434953
Fold 3 IBS: 0.23260330769031967
Fold 4 IBS: 0.23070773208679712
Fold 5 IBS: 0.212827602266059
[I 2024-04-14 19:28:56,047] Trial 66 finished with value: 0.2269419640876496 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.29808498998226407
Fold 2 IBS: 0.22021424313364715
Fold 3 IBS: 0.3008089717671045
Fold 4 IBS: 0.26320289852555373
Fold 5 IBS: 0.25043406288056935
[I 2024-04-14 19:29:00,086] Trial 67 finished with value: 0.2665490332578278 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.36891251562644484
Fold 2 IBS: 0.2831141841580144
Fold 3 IBS: 0.3735215508072975
Fold 4 IBS: 0.30452010490955944
Fold 5 IBS: 0.3196121754758854
[I 2024-04-14 19:29:09,723] Trial 68 finished with value: 0.32993610619544034 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24694744262426244
Fold 2 IBS: 0.23112662775390544
Fold 3 IBS: 0.22888040570607412
Fold 4 IBS: 0.24129039277709646
Fold 5 IBS: 0.2284229264424595
[I 2024-04-14 19:29:10,118] Trial 69 finished with value: 0.23533355906075962 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.3789820127073879
Fold 2 IBS: 0.29066713229198904
Fold 3 IBS: 0.3797964399713672
Fold 4 IBS: 0.3055795866361115
Fold 5 IBS: 0.3297183983009644
[I 2024-04-14 19:29:17,896] Trial 70 finished with value: 0.336948713981564 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2442747298878039
Fold 2 IBS: 0.21394603308037777
Fold 3 IBS: 0.2329347454389621
Fold 4 IBS: 0.23037646611901139
Fold 5 IBS: 0.21249651991354515
[I 2024-04-14 19:29:18,643] Trial 71 finished with value: 0.22680569888794005 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24446665909481854
Fold 2 IBS: 0.2202286409877386
Fold 3 IBS: 0.2298979855224926
Fold 4 IBS: 0.23386125106403746
Fold 5 IBS: 0.21736824836572086
[I 2024-04-14 19:29:19,441] Trial 72 finished with value: 0.2291645570069616 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24809645932076727
Fold 2 IBS: 0.20746362379997257
Fold 3 IBS: 0.23887206962421953
Fold 4 IBS: 0.2284825651773238
Fold 5 IBS: 0.2100698715233792
[I 2024-04-14 19:29:20,526] Trial 73 finished with value: 0.22659691788913244 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2543888239593833
Fold 2 IBS: 0.20292319894393337
Fold 3 IBS: 0.24852527226160065
Fold 4 IBS: 0.22955225079581343
Fold 5 IBS: 0.21241475262132198
[I 2024-04-14 19:29:21,627] Trial 74 finished with value: 0.22956085971641055 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2586670573078814
Fold 2 IBS: 0.20052818501460207
Fold 3 IBS: 0.2585285364856659
Fold 4 IBS: 0.23185266301823715
Fold 5 IBS: 0.21512351643127495
[I 2024-04-14 19:29:22,609] Trial 75 finished with value: 0.2329399916515323 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24487192319121745
Fold 2 IBS: 0.21645877330178392
Fold 3 IBS: 0.23106107310931137
Fold 4 IBS: 0.2321278197949212

Fold 5 IBS: 0.21457551785343906
[I 2024-04-14 19:29:23,079] Trial 76 finished with value: 0.2278190214501346 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24975605957417094
Fold 2 IBS: 0.20544669926019324
Fold 3 IBS: 0.24292589881032364
Fold 4 IBS: 0.2283240329592914
Fold 5 IBS: 0.21054396005104126
[I 2024-04-14 19:29:24,641] Trial 77 finished with value: 0.22739933013100408 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24684927097070503
Fold 2 IBS: 0.2094952280230178
Fold 3 IBS: 0.23652719105524916
Fold 4 IBS: 0.22913951054643386
Fold 5 IBS: 0.2106573202990221
[I 2024-04-14 19:29:25,332] Trial 78 finished with value: 0.2265337041788856 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24502409439696052
Fold 2 IBS: 0.22205787317352343
Fold 3 IBS: 0.22926533447627775
Fold 4 IBS: 0.2352795597651623
Fold 5 IBS: 0.2188730593846164
[I 2024-04-14 19:29:26,278] Trial 79 finished with value: 0.23009998423930805 and parameters: {'subsample': 0.5862245141488869, 'dropout_rate': 0.7413305472330791, 'n_estimators': 79, 'learning_rate': 0.00518700542803859}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.2548529205408104
Fold 2 IBS: 0.2029551856530423
Fold 3 IBS: 0.2494742616554397
Fold 4 IBS: 0.23041757963367823
Fold 5 IBS: 0.21265412243334256
[I 2024-04-14 19:29:27,470] Trial 80 finished with value: 0.23007081398326265 and parameters: {'subsample': 0.5412030995339159, 'dropout_rate': 0.7943244209025906, 'n_estimators': 120, 'learning_rate': 0.015049190001982352}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24503928639713976
Fold 2 IBS: 0.22210439837147225
Fold 3 IBS: 0.22923064761200726
Fold 4 IBS: 0.23532466695341075
Fold 5 IBS: 0.2188890235672119
[I 2024-04-14 19:29:27,989] Trial 81 finished with value: 0.23011760458024838 and parameters: {'subsample': 0.6124074983469379, 'dropout_rate': 0.6341528845468055, 'n_estimators': 48, 'learning_rate': 0.008581896342583242}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24566232614650538
Fold 2 IBS: 0.20771193034028892
Fold 3 IBS: 0.2399122667638913
Fold 4 IBS: 0.22729435575947432
Fold 5 IBS: 0.20971833255484604
[I 2024-04-14 19:29:28,704] Trial 82 finished with value: 0.2260598423130012 and parameters: {'subsample': 0.36882902998484507, 'dropout_rate': 0.9266770484936306, 'n_estimators': 72, 'learning_rate': 0.01836411354022466}. Best is trial 82 with value: 0.2260598423130012.
Fold 1 IBS: 0.24387668061602458
Fold 2 IBS: 0.21371033528547154
Fold 3 IBS: 0.2333362520374528
Fold 4 IBS: 0.22948421407755595
Fold 5 IBS: 0.21270096527180668
[I 2024-04-14 19:29:29,430] Trial 83 finished with value: 0.2266216894576623 and parameters: {'subsample': 0.3619635368676717, 'dropout_rate': 0.9281653685578871, 'n_estimators': 75, 'learning_rate': 0.01174447149382581}. Best is trial 82 with value: 0.2260598423130012.
Fold 1 IBS: 0.2481782165598782
Fold 2 IBS: 0.2022577798304558
Fold 3 IBS: 0.2505921898057478
Fold 4 IBS: 0.22803942510176736
Fold 5 IBS: 0.21128535620380667
[I 2024-04-14 19:29:30,236] Trial 84 finished with value: 0.22807059350033118 and parameters: {'subsample': 0.3276130954169086, 'dropout_rate': 0.9694546795228237, 'n_estimators': 84, 'learning_rate': 0.022169484737510906}. Best is trial 82 with value: 0.2260598423130012.
Fold 1 IBS: 0.2449916816071917
Fold 2 IBS: 0.21058427079436912
Fold 3 IBS: 0.23561656068011147
Fold 4 IBS: 0.2278223716435641
Fold 5 IBS: 0.21102078940314542
[I 2024-04-14 19:29:31,166] Trial 85 finished with value: 0.2260071348256764 and parameters: {'subsample': 0.363388210801912, 'dropout_rate': 0.8895677781947375, 'n_estimators': 93, 'learning_rate': 0.011252915568896725}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.2507644683324895
Fold 2 IBS: 0.1988315238054202
Fold 3 IBS: 0.2542760719339917
Fold 4 IBS: 0.22511425700399493
Fold 5 IBS: 0.2125124481679968
[I 2024-04-14 19:29:32,228] Trial 86 finished with value: 0.22829975384877862 and parameters: {'subsample': 0.2377998071866918, 'dropout_rate': 0.9263524121710748, 'n_estimators': 107, 'learning_rate': 0.01902085002480073}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.24461520451936894
Fold 2 IBS: 0.21175292500978965
Fold 3 IBS: 0.2344490116850452
Fold 4 IBS: 0.22917043508852472
Fold 5 IBS: 0.21178897460870122
[I 2024-04-14 19:29:33,852] Trial 87 finished with value: 0.22635531018228594 and parameters: {'subsample': 0.35810969899809325, 'dropout_rate': 0.8886867033584094, 'n_estimators': 134, 'learning_rate': 0.007190805934355407}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.24456370610129832
Fold 2 IBS: 0.22133243378984238
Fold 3 IBS: 0.22947409303221045
Fold 4 IBS: 0.23463118790461507
Fold 5 IBS: 0.2191508748909942
[I 2024-04-14 19:29:35,490] Trial 88 finished with value: 0.22983045914379208 and parameters: {'subsample': 0.3554257183364478, 'dropout_rate': 0.8515802063127001, 'n_estimators': 151, 'learning_rate': 0.002966804106888144}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.2775193161210976
Fold 2 IBS: 0.2061379929384792
Fold 3 IBS: 0.28613237088303234
Fold 4 IBS: 0.24447960031747357
Fold 5 IBS: 0.23382248801015568
[I 2024-04-14 19:29:37,674] Trial 89 finished with value: 0.24961835365404766 and parameters: {'subsample': 0.2975632154761778, 'dropout_rate': 0.8979603248959219, 'n_estimators': 137, 'learning_rate': 0.026327304724599293}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.24489792409125763
Fold 2 IBS: 0.21471343766794707
Fold 3 IBS: 0.23214478243102468
Fold 4 IBS: 0.2311366433597866
Fold 5 IBS: 0.21331168885551222
[I 2024-04-14 19:29:38,917] Trial 90 finished with value: 0.22724089528110564 and parameters: {'subsample': 0.4239438985312938, 'dropout_rate': 0.8842980981030877, 'n_estimators': 94, 'learning_rate': 0.008199816001785099}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.24443912868099016
Fold 2 IBS: 0.21070940926142825
Fold 3 IBS: 0.2361002830373223
Fold 4 IBS: 0.22815140478159898
Fold 5 IBS: 0.21090216410324303
[I 2024-04-14 19:29:39,942] Trial 91 finished with value: 0.22606047797291656 and parameters: {'subsample': 0.36316393582436224, 'dropout_rate': 0.9330356356373378, 'n_estimators': 74, 'learning_rate': 0.014627227900695133}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.24696395568562218
Fold 2 IBS: 0.20632378108617228
Fold 3 IBS: 0.24098516387669733
Fold 4 IBS: 0.22738668862012074
Fold 5 IBS: 0.2096198352018724
[I 2024-04-14 19:29:41,607] Trial 92 finished with value: 0.22625588489409698 and parameters: {'subsample': 0.373278308068316, 'dropout_rate': 0.8205446675130532, 'n_estimators': 127, 'learning_rate': 0.010840707181494103}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.2445959002519018
Fold 2 IBS: 0.2136491360913386
Fold 3 IBS: 0.23288855680962822
Fold 4 IBS: 0.23008083622513512
Fold 5 IBS: 0.21285389160286478
[I 2024-04-14 19:29:43,141] Trial 93 finished with value: 0.2268136641961737 and parameters: {'subsample': 0.4052623501935374, 'dropout_rate': 0.8224708293111835, 'n_estimators': 122, 'learning_rate': 0.006828423866425095}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.26160555948702097
Fold 2 IBS: 0.20020778542277837
Fold 3 IBS: 0.267173994295559
Fold 4 IBS: 0.23029824587397804
Fold 5 IBS: 0.21639436758841524
[I 2024-04-14 19:29:45,186] Trial 94 finished with value: 0.2351359905335503 and parameters: {'subsample': 0.2685207405457639, 'dropout_rate': 0.5306326676271426, 'n_estimators': 159, 'learning_rate': 0.016919236533565633}. Best is trial 85 with value: 0.2260071348256764.
Fold 1 IBS: 0.2458959493820953
Fold 2 IBS: 0.20850592680764451
Fold 3 IBS: 0.23772658465187374
Fold 4 IBS: 0.22767957442334677

Fold 5 IBS: 0.21018857248815617
[I 2024-04-14 19:29:46,645] Trial 95 finished with value: 0.2259993215506233 and parameters: {'subsample': 0.37798247189331685, 'dropout_rate': 0.8572208063796695, 'n_estimators': 112, 'learning_rate': 0.01063058308878333}. Best is trial 95 with value: 0.2259993215506233.
Fold 1 IBS: 0.2471425193657016
Fold 2 IBS: 0.20595699893541525
Fold 3 IBS: 0.2415748835282002
Fold 4 IBS: 0.22741639083301954
Fold 5 IBS: 0.209543331672624
[I 2024-04-14 19:29:48,632] Trial 96 finished with value: 0.22632682486699213 and parameters: {'subsample': 0.34523349906195283, 'dropout_rate': 0.7739280807288145, 'n_estimators': 132, 'learning_rate': 0.010648288131411126}. Best is trial 95 with value: 0.2259993215506233.
Fold 1 IBS: 0.24385115968166024
Fold 2 IBS: 0.21638959078128364
Fold 3 IBS: 0.2310974483968285
Fold 4 IBS: 0.23167317839356094
Fold 5 IBS: 0.21518657563145072
[I 2024-04-14 19:29:51,719] Trial 97 finished with value: 0.22763959057695682 and parameters: {'subsample': 0.37469859653908655, 'dropout_rate': 0.8528934112321543, 'n_estimators': 187, 'learning_rate': 0.003684889317176295}. Best is trial 95 with value: 0.2259993215506233.
Fold 1 IBS: 0.24621689559308768
Fold 2 IBS: 0.2054773780083265
Fold 3 IBS: 0.24244710006219516
Fold 4 IBS: 0.22648768747110257
Fold 5 IBS: 0.20950699582535112
[I 2024-04-14 19:29:56,440] Trial 98 finished with value: 0.2260272113920126 and parameters: {'subsample': 0.340063793125768, 'dropout_rate': 0.7630617995157165, 'n_estimators': 226, 'learning_rate': 0.006438550621538491}. Best is trial 95 with value: 0.2259993215506233.
Fold 1 IBS: 0.24105265671956497
Fold 2 IBS: 0.20743473047311609
Fold 3 IBS: 0.23607317237170147
Fold 4 IBS: 0.22242584413678895
Fold 5 IBS: 0.21131937637628836
[I 2024-04-14 19:30:04,837] Trial 99 finished with value: 0.22366115601549197 and parameters: {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}. Best is trial 99 with value: 0.22366115601549197.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.22366115601549197], datetime_start=datetime.datetime(2024, 4, 14, 19, 29, 56, 449763), datetime_complete=datetime.datetime(2024, 4, 14, 19, 30, 4, 836435), params={'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=99, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}


* Best Score for IBS:
 0.22366115601549197

In [66]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [67]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.667
train_ibs:  0.224

#### Test

In [68]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [69]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.3060837787360696,
                                              learning_rate=0.04133902891970489,
                                              n_estimators=1, random_state=123,
                                              subsample=0.1001314126580015)

C-index score: 0.535

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7782160113329367,
                                              learning_rate=0.005308151321564225,
                                              n_estimators=212,
                                              random_state=123,
                                              subsample=0.17778434918103095)

IBS: 0.233

In [70]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

## Results

In [71]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.830   1.0
ExtraSurvivalTrees               0.764   2.0
GradientBoosting                 0.713   3.0
CoxLasso                         0.691   4.5
CoxElastic                       0.691   4.5
CoxPH                            0.689   6.0
ComponentwiseGradientBoosting    0.667   7.0
CoxRidge                         0.660   8.0

In [72]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.202   1.0
CoxPH                          0.207   3.5
CoxLasso                       0.207   3.5
CoxElastic                     0.207   3.5
ExtraSurvivalTrees             0.207   3.5
ComponentwiseGradientBoosting  0.224   6.0
GradientBoosting               0.233   7.0
CoxRidge                       0.236   8.0

In [73]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
Randomsurvivalforest             0.544   1.0
ExtraSurvivalTrees               0.543   2.0
CoxRidge                         0.535   3.5
ComponentwiseGradientBoosting    0.535   3.5
CoxPH                            0.532   6.5
CoxLasso                         0.532   6.5
CoxElastic                       0.532   6.5
GradientBoosting                 0.532   6.5

In [74]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.5
GradientBoosting               0.229   1.5
ComponentwiseGradientBoosting  0.233   3.0
Randomsurvivalforest           0.247   4.0
ExtraSurvivalTrees             0.256   5.0
CoxLasso                       0.288   6.5
CoxElastic                     0.288   6.5
CoxPH                          0.290   8.0

In [77]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/robust/rent/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_robust_rent_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [78]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14