In [99]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from yellowbrick.cluster import KElbowVisualizer
import matplotlib.pyplot as plt
import pandas as pd 
import seaborn as sns
from sksurv.base import SurvivalAnalysisMixin as s
from sklearn.model_selection import train_test_split, RandomizedSearchCV, cross_val_score
from sksurv.preprocessing import encode_categorical
from sksurv.datasets import load_gbsg2
from sksurv.functions import StepFunction
from sksurv.linear_model import CoxPHSurvivalAnalysis, CoxnetSurvivalAnalysis
from sksurv.ensemble import (ComponentwiseGradientBoostingSurvivalAnalysis, 
                            RandomSurvivalForest, 
                            ExtraSurvivalTrees, 
                            GradientBoostingSurvivalAnalysis, 
                            ExtraSurvivalTrees)
from sksurv.meta import EnsembleSelection, EnsembleSelectionRegressor
from sksurv.metrics import integrated_brier_score
from matplotlib.colors import ListedColormap
from mlxtend.evaluate import paired_ttest_5x2cv
from mlxtend.evaluate import combined_ftest_5x2cv
from lifelines import KaplanMeierFitter
from scipy.cluster import hierarchy
from lifelines.statistics import logrank_test, multivariate_logrank_test, pairwise_logrank_test
from sklearn import preprocessing
from sklearn.model_selection import StratifiedKFold, KFold
from lifelines.plotting import add_at_risk_counts
import scipy.stats
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import optuna
from sklearn.model_selection import cross_val_score
from sksurv.metrics import integrated_brier_score
from lifelines import CoxPHFitter
from lifelines.statistics import proportional_hazard_test
import scipy.stats as stats
from statsmodels.stats.outliers_influence import variance_inflation_factor 
import statsmodels.api as sm
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'
from sklearn.preprocessing import RobustScaler

In [100]:
# OUS: Train data
OUS_D1 = pd.read_csv('OUS_D1.csv')
OUS_D2 = pd.read_csv('OUS_D2.csv')
OUS_D3 = pd.read_csv('OUS_D3.csv')
OUS_DFS_target = pd.read_csv('OUS_DFS_target.csv')
OUS_OS_target = pd.read_csv('OUS_OS_target.csv')
response_OUS = pd.read_csv('response_ous.csv', sep=';')

# MAASTRO: Test data 
MAASTRO_D1 = pd.read_csv('MAASTRO_D1.csv')
MAASTRO_D2 = pd.read_csv('MAASTRO_D2.csv')
MAASTRO_D3 = pd.read_csv('MAASTRO_D3.csv')
MAASTRO_DFS_target = pd.read_csv('MAASTRO_DFS_target.csv')
MAASTRO_OS_target = pd.read_csv('MAASTRO_OS_target.csv')
response_MAASTRO = pd.read_csv('maastro_response_full.csv', sep=',')

In [101]:
# Need to choose patient_id from OUS_D2 in response_OUS
data = list(OUS_D2['patient_id'])
mask = response_OUS['patient_id'].isin(data)
response_OUS = response_OUS[mask] 

# Merge OUS_D2 with response_OUS
clinical_train = pd.merge(OUS_D2, response_OUS, on='patient_id', how='inner')
clinical_train = clinical_train.loc[:, ~clinical_train.columns.isin(['OS', 'event_OS', 'LRC', 'event_LRC'])]

In [102]:
# Drop patient_id column
clinical_train = clinical_train.drop('patient_id', axis=1)

In [103]:
# Check null values in D2 
clinical_train.isnull().sum().sum()

0

In [104]:
""" Takes too long time 
# Check collinearity for OUS data 
df = clinical_train

# Create a correlation matrix
correlation_matrix = df.corr()

plt.figure(figsize=(15, 12))

# Plot a heatmap
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.show()
"""

" Takes too long time \n# Check collinearity for OUS data \ndf = clinical_train\n\n# Create a correlation matrix\ncorrelation_matrix = df.corr()\n\nplt.figure(figsize=(15, 12))\n\n# Plot a heatmap\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=0.5)\nplt.show()\n"

## Test dataset: MAASTRO

In [105]:
(MAASTRO_D2['patient_id'] == MAASTRO_OS_target['patient_id']).sum()

99

In [106]:
# Rename the column name of response_MAASTRO 
response_MAASTRO.rename(columns = {'Index' : 'patient_id'}, inplace = True)

In [107]:
# need to choose patient_id from MAASTRO_D2 in response_MAASTRO
data = list(MAASTRO_D2['patient_id'])
mask = response_MAASTRO['patient_id'].isin(data)
response_MAASTRO = response_MAASTRO[mask] 
response_MAASTRO

     patient_id     OS  OS_event    LRC  LRC_event    DFS  DFS_event
0             1  62.43       0.0  62.43        0.0  62.43        0.0
1             2  60.00       0.0  60.00        0.0  60.00        0.0
2             3  44.43       1.0   8.83        1.0   8.83        1.0
3             4  37.20       1.0  19.37        0.0  19.73        1.0
5             6  59.23       0.0  59.23        0.0  59.23        0.0
..          ...    ...       ...    ...        ...    ...        ...
109         110  19.00       1.0  13.27        1.0  13.27        1.0
110         111  85.87       1.0  82.83        0.0  85.87        1.0
111         112  42.87       0.0  42.87        0.0  42.87        0.0
112         113  58.93       0.0  58.93        0.0  58.93        0.0
113         114  72.07       0.0  72.07        0.0  72.07        0.0

[99 rows x 7 columns]

In [108]:
# Merge MAASTRO_D2 with response_MAASTRO
clinical_test = pd.merge(MAASTRO_D2, response_MAASTRO, on='patient_id', how='inner')
clinical_test = clinical_test.loc[:, ~clinical_test.columns.isin(['OS', 'OS_event', 'LRC', 'LRC_event'])]
clinical_test

,patient_id,shape_Elongation,shape_Flatness,shape_LeastAxisLength,shape_MajorAxisLength,shape_Maximum2DDiameterColumn,shape_Maximum2DDiameterRow,shape_Maximum2DDiameterSlice,shape_Maximum3DDiameter,shape_MeshVolume,...,LBP_021_PET,LBP_030_PET,LBP_102_PET,LBP_111_PET,LBP_120_PET,LBP_201_PET,LBP_210_PET,LBP_300_PET,DFS,DFS_event
0,1,0.765178,0.610062,30.504395,50.002093,52.886671,58.000000,47.759816,58.864251,38067.208333,...,0.028808,0.837387,0.000026,0.001705,0.122209,0.000026,0.008291,0.000341,62.43,0.0
1,2,0.776540,0.504616,21.069386,41.753334,44.922155,44.294469,44.147480,48.723711,17870.791667,...,0.049615,0.806842,0.000167,0.002958,0.128976,0.000167,0.008148,0.000335,60.00,0.0
2,3,0.697164,0.478604,21.238275,44.375483,48.466483,45.891176,37.656341,48.969378,17426.500000,...,0.019514,0.830272,0.000057,0.001831,0.137282,0.000000,0.008641,0.000229,8.83,1.0
3,4,0.574636,0.446059,20.570459,46.115989,42.544095,47.507894,33.837849,55.226805,12463.791667,...,0.047155,0.760949,0.000000,0.003597,0.171595,0.000080,0.013187,0.000240,19.73,1.0
4,6,0.633419,0.480378,26.130155,54.394967,66.030296,56.320511,45.398238,67.089492,28300.125000,...,0.033990,0.824865,0.000000,0.002116,0.128134,0.000035,0.009379,0.000529,59.23,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,110,0.882411,0.577884,19.774388,34.218615,41.785165,40.261644,35.805028,43.520110,12822.458333,...,0.017489,0.834590,0.000000,0.001321,0.137194,0.000078,0.008706,0.000078,13.27,1.0
95,111,0.535802,0.455642,23.259099,51.046869,51.264022,51.264022,33.600595,52.440442,18368.291667,...,0.029979,0.821431,0.000000,0.000543,0.137620,0.000054,0.008907,0.000489,85.87,1.0
96,112,0.716610,0.631485,31.838169,50.417953,46.324939,56.035703,57.070132,57.671483,35384.541667,...,0.017354,0.859957,0.000000,0.000988,0.115099,0.000028,0.005700,0.000141,42.87,0.0
97,113,0.665145,0.628338,28.213278,44.901412,50.289164,50.596443,35.777088,51.478151,26180.208333,...,0.025399,0.847908,0.000000,0.001487,0.117654,0.000000,0.005759,0.000038,58.93,0.0
98,114,0.616262,0.469139,17.158420,36.574294,42.953463,39.204592,26.076810,43.485630,8857.958333,...,0.018885,0.812275,0.000000,0.000899,0.156924,0.000112,0.010342,0.000337,72.07,0.0

In [109]:
# Drop patient_id column
clinical_test = clinical_test.drop('patient_id', axis=1)

In [110]:
# Some rows have null values in OS, OS_event -> Remove those rows
clinical_test[clinical_test.isnull().any(axis=1)]
clinical_test = clinical_test.dropna(how='any',axis=0)

Empty DataFrame
Columns: [shape_Elongation, shape_Flatness, shape_LeastAxisLength, shape_MajorAxisLength, shape_Maximum2DDiameterColumn, shape_Maximum2DDiameterRow, shape_Maximum2DDiameterSlice, shape_Maximum3DDiameter, shape_MeshVolume, shape_MinorAxisLength, shape_Sphericity, shape_SurfaceArea, shape_SurfaceVolumeRatio, shape_VoxelVolume, first_order_10Percentile_CT, first_order_90Percentile_CT, first_order_Energy_CT, first_order_Entropy_CT_b20, first_order_InterquartileRange_CT, first_order_Kurtosis_CT, first_order_Maximum_CT, first_order_MeanAbsoluteDeviation_CT, first_order_Mean_CT, first_order_Median_CT, first_order_Minimum_CT, first_order_Range_CT, first_order_RobustMeanAbsoluteDeviation_CT, first_order_RootMeanSquared_CT, first_order_Skewness_CT, first_order_TotalEnergy_CT, first_order_Uniformity_CT_b20, first_order_Variance_CT, glszm_GrayLevelNonUniformity_CT_b20, glszm_GrayLevelNonUniformityNormalized_CT_b20, glszm_GrayLevelVariance_CT_b20, glszm_HighGrayLevelZoneEmphasis_CT_b20, glszm_LargeAreaEmphasis_CT_b20, glszm_LargeAreaHighGrayLevelEmphasis_CT_b20, glszm_LargeAreaLowGrayLevelEmphasis_CT_b20, glszm_LowGrayLevelZoneEmphasis_CT_b20, glszm_SizeZoneNonUniformity_CT_b20, glszm_SizeZoneNonUniformityNormalized_CT_b20, glszm_SmallAreaEmphasis_CT_b20, glszm_SmallAreaHighGrayLevelEmphasis_CT_b20, glszm_SmallAreaLowGrayLevelEmphasis_CT_b20, glszm_ZoneEntropy_CT_b20, glszm_ZonePercentage_CT_b20, glszm_ZoneVariance_CT_b20, glrlm_GrayLevelNonUniformity_CT_b20, glrlm_GrayLevelNonUniformityNormalized_CT_b20, glrlm_GrayLevelVariance_CT_b20, glrlm_HighGrayLevelRunEmphasis_CT_b20, glrlm_LongRunEmphasis_CT_b20, glrlm_LongRunHighGrayLevelEmphasis_CT_b20, glrlm_LongRunLowGrayLevelEmphasis_CT_b20, glrlm_LowGrayLevelRunEmphasis_CT_b20, glrlm_RunEntropy_CT_b20, glrlm_RunLengthNonUniformity_CT_b20, glrlm_RunLengthNonUniformityNormalized_CT_b20, glrlm_RunPercentage_CT_b20, glrlm_RunVariance_CT_b20, glrlm_ShortRunEmphasis_CT_b20, glrlm_ShortRunHighGrayLevelEmphasis_CT_b20, glrlm_ShortRunLowGrayLevelEmphasis_CT_b20, ngtdm_Busyness_d_1_CT_b20, ngtdm_Coarseness_d_1_CT_b20, ngtdm_Complexity_d_1_CT_b20, ngtdm_Contrast_d_1_CT_b20, ngtdm_Strength_d_1_CT_b20, gldm_DependenceEntropy_d_1_CT_b20, gldm_DependenceNonUniformity_d_1_CT_b20, gldm_DependenceNonUniformityNormalized_d_1_CT_b20, gldm_DependenceVariance_d_1_CT_b20, gldm_GrayLevelNonUniformity_d_1_CT_b20, gldm_GrayLevelVariance_d_1_CT_b20, gldm_HighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceEmphasis_d_1_CT_b20, gldm_LargeDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_LargeDependenceLowGrayLevelEmphasis_d_1_CT_b20, gldm_LowGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceEmphasis_d_1_CT_b20, gldm_SmallDependenceHighGrayLevelEmphasis_d_1_CT_b20, gldm_SmallDependenceLowGrayLevelEmphasis_d_1_CT_b20, glcm_Autocorrelation_d_1_CT_b20, glcm_ClusterProminence_d_1_CT_b20, glcm_ClusterShade_d_1_CT_b20, glcm_ClusterTendency_d_1_CT_b20, glcm_Contrast_d_1_CT_b20, glcm_Correlation_d_1_CT_b20, glcm_DifferenceAverage_d_1_CT_b20, glcm_DifferenceEntropy_d_1_CT_b20, glcm_DifferenceVariance_d_1_CT_b20, glcm_Id_d_1_CT_b20, glcm_Idm_d_1_CT_b20, glcm_Idmn_d_1_CT_b20, glcm_Idn_d_1_CT_b20, glcm_Imc1_d_1_CT_b20, glcm_Imc2_d_1_CT_b20, glcm_InverseVariance_d_1_CT_b20, glcm_JointAverage_d_1_CT_b20, ...]
Index: []

[0 rows x 376 columns]

In [111]:
# X
X = clinical_train.loc[:, ~clinical_train.columns.isin(['DFS', 'event_DFS'])]

# y 
y = clinical_train.loc[:, ['DFS', 'event_DFS']]

# Set lower, upper time point and times for IBS calculation later 
lower, upper = np.percentile(y['DFS'], [10, 90])
times = np.arange(lower, upper)

In [112]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [113]:
# Shape
print('X_train: ', X.shape)
print('y_train: ', y.shape)

X_train:  (139, 374)
y_train:  (139,)

In [114]:
clinical_test.rename(columns = {'DFS_event' : 'event_DFS'}, inplace = True)

In [115]:
# X
X_MAASTRO = clinical_test.loc[:, ~clinical_test.columns.isin(['DFS', 'event_DFS'])]

# y y_MAASTRO
y_MAASTRO = clinical_test.loc[:, ['DFS', 'event_DFS']]
lower, upper = np.percentile(y_MAASTRO['DFS'], [10, 90])
times = np.arange(lower, upper)

# y into array 
lists = [] 
for i, j in zip(y_MAASTRO['event_DFS'], y_MAASTRO['DFS']): 
    lists.append((i, j))

y_MAASTRO = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

clinical_test.shape

(99, 376)

# Feature Selection

In [116]:
# Choose features from the result of Cox PLSR in R
plsr = [
"shape_Elongation",
"shape_MajorAxisLength",
"shape_Sphericity",
"shape_SurfaceVolumeRatio",
"shape_Flatness",
"glszm_SmallAreaLowGrayLevelEmphasis_CT_c16",
"shape_MinorAxisLength",
"glszm_ZonePercentage_PET_b2",
"LBP_201_PET",
"shape_Maximum3DDiameter",
"glszm_GrayLevelVariance_PET_b2"
]

In [117]:
X_plsr = X.loc[:, plsr]
X_new = X_plsr.copy()

In [118]:
# Selecct the columns from X_MAASTRO
MAASTRO_new = X_MAASTRO.loc[:, plsr]

# Standardization

In [119]:
# Copy the original X for later 
original_X = X.copy()

In [133]:
categorical_columns = ['female', 
                        'cavum_oris',
                        'oropharynx',
                        'hypopharynx',
                        'larynx',
                        'histgrade_high',
                        'hpv_related',
                        'charlson',
                        'uicc8_III-IV']

# Standardize X_new, the new data with the selected features only 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in X_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
X_new_categoric = X_new[columns_to_drop]
X_new_numeric = X_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
scaler = RobustScaler() 
X_new_numeric_columns = X_new_numeric.columns
X_new_numeric_index = X_new_numeric.index 
X_new_numeric_std = scaler.fit_transform(X_new_numeric)
X_new_numeric_std = pd.DataFrame(X_new_numeric_std,
                                 columns=X_new_numeric_columns, 
                                 index=X_new_numeric_index)
X_new_std = pd.concat([X_new_numeric_std, X_new_categoric], axis=1)

# Change the order of the X_new_std 
X_new_std = X_new_std[X_new.columns]

In [134]:
# Standardize X_MAASTRO 
# Set the columns_to_drop which are categorical 
columns_to_drop = [col for col in MAASTRO_new.columns if col in categorical_columns]

# Drop the columns if they exist in the DataFrame and save the numeric part in X_new_numeric
MAASTRO_new_categoric = MAASTRO_new[columns_to_drop]
MAASTRO_new_numeric = MAASTRO_new.drop(columns=columns_to_drop, inplace=False)

# Do the standardization for the numeric part 
MAASTRO_new_numeric_columns = MAASTRO_new_numeric.columns
MAASTRO_new_numeric_index = MAASTRO_new_numeric.index 
MAASTRO_new_numeric_std = scaler.transform(MAASTRO_new_numeric)
MAASTRO_new_numeric_std = pd.DataFrame(MAASTRO_new_numeric_std,
                                 columns=MAASTRO_new_numeric_columns, 
                                 index=MAASTRO_new_numeric_index)
MAASTRO_new_std = pd.concat([MAASTRO_new_numeric_std, MAASTRO_new_categoric], axis=1)

# Change the order of the X_new_std 
MAASTRO_new_std = MAASTRO_new_std[MAASTRO_new.columns]

In [135]:
X_new

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_MinorAxisLength,glszm_ZonePercentage_PET_b2,LBP_201_PET,shape_Maximum3DDiameter,glszm_GrayLevelVariance_PET_b2
0,0.600926,42.073251,0.761164,0.251218,0.535140,0.029425,25.282894,0.001048,0.000062,47.339202,5.633218
1,0.841579,24.613845,0.697049,0.489853,0.367109,0.037915,20.714498,0.002794,0.000349,28.106939,1.187500
2,0.772821,48.030294,0.565792,0.278467,0.597785,0.008009,37.118833,0.000690,0.000000,60.049979,1.310000
3,0.847727,25.589900,0.684364,0.474018,0.405730,0.018398,21.693241,0.000899,0.000000,32.572995,0.666667
4,0.831483,34.684750,0.503142,0.563135,0.442406,0.013051,28.839789,0.002591,0.000399,39.962482,1.076923
...,...,...,...,...,...,...,...,...,...,...,...
134,0.680294,33.069705,0.742102,0.322021,0.523608,0.014938,22.497115,0.000961,0.000000,37.696154,3.000000
135,0.758193,41.043692,0.722918,0.227705,0.735524,0.011441,31.119023,0.000315,0.000079,52.430907,1.234375
136,0.770113,36.618802,0.652963,0.298398,0.648063,0.020431,28.200620,0.002023,0.000000,42.743421,4.349636
137,0.628897,45.870392,0.724255,0.252893,0.492193,0.019663,28.847736,0.000759,0.000054,51.536395,2.658163
138,0.892637,30.363259,0.722633,0.290461,0.756267,0.013864,27.103353,0.001549,0.000000,39.408121,3.706371

In [136]:
X_new_std

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_MinorAxisLength,glszm_ZonePercentage_PET_b2,LBP_201_PET,shape_Maximum3DDiameter,glszm_GrayLevelVariance_PET_b2
0,-0.485459,0.059912,0.704475,-0.258002,0.064971,1.172200,-0.225260,-0.086297,0.038290,0.030929,0.606009
1,0.666232,-0.755402,0.101791,1.308278,-0.952446,1.947696,-0.603339,1.454382,1.827361,-0.744926,-0.543389
2,0.337179,0.338093,-1.132016,-0.079152,0.444285,-0.783916,0.754279,-0.402730,-0.345359,0.543698,-0.511718
3,0.695653,-0.709822,-0.017443,1.204345,-0.718597,0.165035,-0.522339,-0.218202,-0.345359,-0.564759,-0.678045
4,0.617917,-0.285114,-1.720923,1.789265,-0.496529,-0.323382,0.069107,1.274704,2.133915,-0.266658,-0.571977
...,...,...,...,...,...,...,...,...,...,...,...
134,-0.105628,-0.360532,0.525285,0.206714,-0.004852,-0.151010,-0.455811,-0.163123,-0.345359,-0.358084,-0.074784
135,0.267171,0.011834,0.344965,-0.412334,1.278289,-0.470412,0.257736,-0.733664,0.144386,0.236335,-0.531270
136,0.324219,-0.194798,-0.312609,0.051664,0.748713,0.350720,0.016210,0.773935,-0.345359,-0.154471,0.274151
137,-0.351598,0.237230,0.357529,-0.247011,-0.195069,0.280586,0.069765,-0.341933,-0.008205,0.200249,-0.163163
138,0.910577,-0.486917,0.342282,-0.000434,1.403881,-0.249118,-0.074600,0.355416,-0.345359,-0.289021,0.107841

In [137]:
MAASTRO_new

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_MinorAxisLength,glszm_ZonePercentage_PET_b2,LBP_201_PET,shape_Maximum3DDiameter,glszm_GrayLevelVariance_PET_b2
0,0.765178,50.002093,0.668072,0.215184,0.610062,0.010495,38.260495,0.001102,0.000026,58.864251,4.473923
1,0.776540,41.753334,0.669961,0.276092,0.504616,0.035018,32.423122,0.000726,0.000167,48.723711,5.207101
2,0.697164,44.375483,0.624081,0.298887,0.478604,0.012819,30.936983,0.001030,0.000000,48.969378,6.728395
3,0.574636,46.115989,0.577624,0.361096,0.446059,0.029974,26.499895,0.000879,0.000080,55.226805,2.694215
4,0.633419,54.394967,0.630933,0.251519,0.480378,0.013458,34.454789,0.000458,0.000035,67.089492,2.710059
...,...,...,...,...,...,...,...,...,...,...,...
94,0.882411,34.218615,0.671754,0.307574,0.577884,0.039092,30.194871,0.003809,0.000078,43.520110,16.942940
95,0.535802,51.046869,0.632189,0.289922,0.455642,0.015831,27.351039,0.001032,0.000054,52.440442,4.742382
96,0.716610,50.417953,0.645548,0.228184,0.631485,0.011031,36.130031,0.000282,0.000028,57.671483,3.250000
97,0.665145,44.901412,0.727488,0.223872,0.628338,0.019801,29.865942,0.000953,0.000000,51.478151,3.222400
98,0.616262,36.574294,0.672838,0.347373,0.469139,0.015813,22.539345,0.001686,0.000112,43.485630,4.240000

In [138]:
MAASTRO_new_std

,shape_Elongation,shape_MajorAxisLength,shape_Sphericity,shape_SurfaceVolumeRatio,shape_Flatness,glszm_SmallAreaLowGrayLevelEmphasis_CT_c16,shape_MinorAxisLength,glszm_ZonePercentage_PET_b2,LBP_201_PET,shape_Maximum3DDiameter,glszm_GrayLevelVariance_PET_b2
0,0.300600,0.430171,-0.170593,-0.494510,0.518623,-0.556880,0.848762,-0.039126,-0.182156,0.495864,0.306284
1,0.354974,0.044973,-0.152832,-0.094745,-0.119851,1.683040,0.365663,-0.371303,0.696135,0.086782,0.495840
2,-0.024893,0.167421,-0.584101,0.054869,-0.277351,-0.344618,0.242671,-0.102565,-0.345359,0.096692,0.889156
3,-0.611274,0.248699,-1.020797,0.463178,-0.474407,1.222314,-0.124542,-0.235724,0.151803,0.349125,-0.153842
4,-0.329957,0.635308,-0.519690,-0.256026,-0.266607,-0.286171,0.533803,-0.607066,-0.126027,0.827681,-0.149746
...,...,...,...,...,...,...,...,...,...,...,...
94,0.861639,-0.306881,-0.135979,0.111891,0.323784,2.055216,0.181254,2.349697,0.138162,-0.123138,3.530028
95,-0.797117,0.478960,-0.507883,-0.003972,-0.416383,-0.069508,-0.054101,-0.100944,-0.007528,0.236720,0.375692
96,0.068172,0.449591,-0.382318,-0.409188,0.648334,-0.507885,0.672446,-0.762565,-0.169833,0.447747,-0.010149
97,-0.178126,0.191981,0.387916,-0.437485,0.629283,0.293176,0.154031,-0.170173,-0.345359,0.197899,-0.017285
98,-0.412064,-0.196876,-0.125793,0.373109,-0.334661,-0.071098,-0.452316,0.476456,0.353887,-0.124529,0.245806

# Modelling

### 1. CoxPHSurvivalAnalysis

#### Train

In [139]:
# Setting the y format for skf below  
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class()
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxPHSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxPHSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 20:31:03,193] A new study created in memory with name: no-name-d2c634e9-dfb6-457a-a4eb-9378ffcea7b2

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.6340425531914894

[I 2024-04-14 20:31:03,774] A new study created in memory with name: no-name-db707001-444b-490a-82e1-543c1269f96f

Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 20:31:03,766] Trial 0 finished with value: 0.6586792319760761 and parameters: {}. Best is trial 0 with value: 0.6586792319760761.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6586792319760761], datetime_start=datetime.datetime(2024, 4, 14, 20, 31, 3, 240161), datetime_complete=datetime.datetime(2024, 4, 14, 20, 31, 3, 766396), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6586792319760761

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.2745924402154568
Fold 2 IBS: 0.17145676574325394
Fold 3 IBS: 0.21215675308877574
Fold 4 IBS: 0.25357417599446125
Fold 5 IBS: 0.20650162568964595
[I 2024-04-14 20:31:04,587] Trial 0 finished with value: 0.2236563521463187 and parameters: {}. Best is trial 0 with value: 0.2236563521463187.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.2236563521463187], datetime_start=datetime.datetime(2024, 4, 14, 20, 31, 3, 882913), datetime_complete=datetime.datetime(2024, 4, 14, 20, 31, 4, 587101), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.2236563521463187

In [140]:
# Setting a dictionary to save the train results 
train_cindex = {} 
train_ibs = {} 

# Saving the values to the dictionary 
train_cindex['CoxPH'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxPH'] = np.round(study_ibs.best_value, 3)

In [141]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.659
train_ibs:  0.224

#### Test

In [142]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [143]:
# Test on MAASTRO 
cph = CoxPHSurvivalAnalysis()

cph.fit(X_new_std, y)

# Save C-index 
c_index = cph.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print('Concordance index:', c_index)

# Save IBS 
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in cph.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print('IBS score:', ibs)

CoxPHSurvivalAnalysis()

Concordance index: 0.499
IBS score: 0.288

In [144]:
# Setting a dictionary to save the test results 
test_cindex = {} 
test_ibs = {}

In [145]:
# Saving the values to the dictionary 
test_cindex['CoxPH'] = c_index
test_ibs['CoxPH'] = ibs

### 2. CoxnetSurvivalAnalysis

#### Train

In [146]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning 
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=0.0000001, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 20:31:05,050] A new study created in memory with name: no-name-677e34c2-8c26-4799-8629-e7c915f0a0bb

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5595744680851064
Fold 4 C-index: 0.6520912547528517

[I 2024-04-14 20:31:06,228] A new study created in memory with name: no-name-59013976-8820-49c5-ad73-85213da67fc9

Fold 5 C-index: 0.6244635193133047
[I 2024-04-14 20:31:06,180] Trial 0 finished with value: 0.6328285538874934 and parameters: {}. Best is trial 0 with value: 0.6328285538874934.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6328285538874934], datetime_start=datetime.datetime(2024, 4, 14, 20, 31, 5, 136076), datetime_complete=datetime.datetime(2024, 4, 14, 20, 31, 6, 179898), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6328285538874934

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724709562302793
Fold 2 IBS: 0.2320398715413607
Fold 3 IBS: 0.2289818676351831
Fold 4 IBS: 0.24197476311778662
Fold 5 IBS: 0.22939558654388334
[I 2024-04-14 20:31:07,065] Trial 0 finished with value: 0.23592783689224833 and parameters: {}. Best is trial 0 with value: 0.23592783689224833.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.23592783689224833], datetime_start=datetime.datetime(2024, 4, 14, 20, 31, 6, 270305), datetime_complete=datetime.datetime(2024, 4, 14, 20, 31, 7, 64830), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.23592783689224833

In [147]:
train_cindex['CoxRidge'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxRidge'] = np.round(study_ibs.best_value, 3)

In [148]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.633
train_ibs:  0.236

#### Test

In [149]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [150]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 0.0000001
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_cindex : 0.543

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1e-07)

test_ibs:  0.229

In [151]:
# Saving the values to the dictionary 
test_cindex['CoxRidge'] = c_index
test_ibs['CoxRidge'] = ibs

### 3. CoxnetSurvivalAnalysis - Lasso

#### Train

In [152]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Create and fit survival model 
        model = model_class(l1_ratio=1, 
                            fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=1, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 20:31:07,401] A new study created in memory with name: no-name-4a76f6cc-e8c7-4804-9a05-e8ff8223d158

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617

[I 2024-04-14 20:31:08,435] A new study created in memory with name: no-name-f57b0364-9807-46bb-8c22-e2301eedbc1f

Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:08,423] Trial 0 finished with value: 0.6574227098408564 and parameters: {}. Best is trial 0 with value: 0.6574227098408564.


* Best trial for C-index:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.6574227098408564], datetime_start=datetime.datetime(2024, 4, 14, 20, 31, 7, 528240), datetime_complete=datetime.datetime(2024, 4, 14, 20, 31, 8, 423556), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for C-index:
 0.6574227098408564

  0%|          | 0/1 [00:00<?, ?it/s]

Fold 1 IBS: 0.27277647463896704
Fold 2 IBS: 0.17342030361577185
Fold 3 IBS: 0.20977142507972169
Fold 4 IBS: 0.2526073567646622
Fold 5 IBS: 0.2050410788138167
[I 2024-04-14 20:31:09,296] Trial 0 finished with value: 0.22272332778258788 and parameters: {}. Best is trial 0 with value: 0.22272332778258788.


* Best trial for IBS:
 FrozenTrial(number=0, state=TrialState.COMPLETE, values=[0.22272332778258788], datetime_start=datetime.datetime(2024, 4, 14, 20, 31, 8, 516335), datetime_complete=datetime.datetime(2024, 4, 14, 20, 31, 9, 296236), params={}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={}, trial_id=0, value=None)


* Best Score for IBS:
 0.22272332778258788

In [153]:
train_cindex['CoxLasso'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxLasso'] = np.round(study_ibs.best_value, 3)

In [154]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.657
train_ibs:  0.223

#### Test

In [155]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [156]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params['l1_ratio'] = 1
    best_params['fit_baseline_model']=True
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_cindex : 0.498

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=1)

test_ibs:  0.288

In [157]:
# Saving the values to the dictionary 
test_cindex['CoxLasso'] = c_index
test_ibs['CoxLasso'] = ibs

### 4. CoxnetSurvivalAnalysis - ElasticNet

#### Train

In [158]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        l1_ratio = trial.suggest_float("l1_ratio", 0.0001, 1)
        
        # Create and fit survival model 
        model = model_class(l1_ratio=l1_ratio, 
                           fit_baseline_model=True)
        
        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(CoxnetSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(CoxnetSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 20:31:09,812] A new study created in memory with name: no-name-cf6143cd-b8ee-499e-971c-346338c2d039

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:10,767] Trial 0 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.6580925585585977.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:11,574] Trial 1 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.6581831661146207.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:12,203] Trial 2 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 1 with value: 0.6581831661146207.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:13,575] Trial 3 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 1 with value: 0.6581831661146207.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:14,672] Trial 4 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:15,542] Trial 5 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:16,199] Trial 6 finished with value: 0.6574227098408564 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:16,950] Trial 7 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:17,666] Trial 8 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:18,327] Trial 9 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:19,197] Trial 10 finished with value: 0.6574227098408564 and parameters: {'l1_ratio': 0.9843563326681124}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:19,896] Trial 11 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.729739426971179}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:20,484] Trial 12 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7236736559681478}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:21,022] Trial 13 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8365753292298825}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:21,529] Trial 14 finished with value: 0.6412377595502136 and parameters: {'l1_ratio': 0.1015556329868651}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:22,011] Trial 15 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5936985909694869}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:22,486] Trial 16 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8549474674911437}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:23,057] Trial 17 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6594892261146885}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:23,545] Trial 18 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8081045010661086}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:24,029] Trial 19 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.6076328072126191}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:24,505] Trial 20 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.88470877397518}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:24,989] Trial 21 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7678156320718279}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:25,488] Trial 22 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6828271296371035}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:26,002] Trial 23 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5132325893411083}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888

Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:26,548] Trial 24 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8896057121430163}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:27,040] Trial 25 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.6172146917600154}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:27,550] Trial 26 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7259873255784245}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:28,061] Trial 27 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.7778464836718683}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:28,549] Trial 28 finished with value: 0.6565716460110693 and parameters: {'l1_ratio': 0.9346196102606046}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:29,046] Trial 29 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6546417265992662}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:29,558] Trial 30 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.4360652786420327}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:29,997] Trial 31 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8533959143041439}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:30,480] Trial 32 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.7831642798691968}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:30,949] Trial 33 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7161477568821817}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:31,444] Trial 34 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.32114901167010745}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:31,891] Trial 35 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8144366713154305}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:32,367] Trial 36 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5411641129675752}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:32,861] Trial 37 finished with value: 0.6573321022848335 and parameters: {'l1_ratio': 0.9247217843962279}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:33,308] Trial 38 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6351931330472103
[I 2024-04-14 20:31:33,584] Trial 39 finished with value: 0.6328498942129855 and parameters: {'l1_ratio': 0.04032884745061077}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:34,049] Trial 40 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7363270003832804}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:34,533] Trial 41 finished with value: 0.6573321022848335 and parameters: {'l1_ratio': 0.6438742195640806}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:34,979] Trial 42 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6742522360600087}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:35,445] Trial 43 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.681920339144559}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:35,907] Trial 44 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8331504149903135}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:36,355] Trial 45 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.48511452540042665}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:36,828] Trial 46 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7593042514515428}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:37,302] Trial 47 finished with value: 0.6573321022848335 and parameters: {'l1_ratio': 0.5839374747196953}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888

Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:37,879] Trial 48 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.6273814473795578}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:38,345] Trial 49 finished with value: 0.6565716460110693 and parameters: {'l1_ratio': 0.9431560437165498}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:38,825] Trial 50 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8805577934156339}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:39,295] Trial 51 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8077835596723117}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:39,800] Trial 52 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.7022740677402595}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:40,340] Trial 53 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8203488015960938}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:40,774] Trial 54 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7564665877759291}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:41,202] Trial 55 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7961707869524477}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:41,681] Trial 56 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8590425150526257}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:42,144] Trial 57 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7070176430390448}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:42,818] Trial 58 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6606543618564982}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:43,624] Trial 59 finished with value: 0.6574227098408564 and parameters: {'l1_ratio': 0.980948780330091}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:44,073] Trial 60 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5207027863114488}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:44,540] Trial 61 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7593241047027559}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:45,021] Trial 62 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7393499767481052}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:45,505] Trial 63 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.6002579832620308}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:46,076] Trial 64 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.9113875019255742}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:47,024] Trial 65 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7893984675197981}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:47,670] Trial 66 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.2283450959509596}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:48,158] Trial 67 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8610659219481535}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:49,100] Trial 68 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.7001457736692274}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:49,787] Trial 69 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.6297262538705792}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:50,272] Trial 70 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8313985997160138}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:50,770] Trial 71 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6618226511817697}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888

Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:51,344] Trial 72 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.728170429925161}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:51,939] Trial 73 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.4444560608728035}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:52,419] Trial 74 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7647469477774845}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:53,126] Trial 75 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6897189251927811}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:53,609] Trial 76 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5565304696320154}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:54,092] Trial 77 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.7856263501024918}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:54,725] Trial 78 finished with value: 0.6565716460110693 and parameters: {'l1_ratio': 0.9506480490309224}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:55,397] Trial 79 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8986141482847662}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:55,898] Trial 80 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7377127197925855}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:56,387] Trial 81 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6805208585875125}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:56,933] Trial 82 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.716909644219542}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:57,417] Trial 83 finished with value: 0.6573321022848335 and parameters: {'l1_ratio': 0.6376945656372208}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:57,967] Trial 84 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.84318144048335}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:58,490] Trial 85 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7464741356232805}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:58,963] Trial 86 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.7751440372918974}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:31:59,749] Trial 87 finished with value: 0.6573321022848335 and parameters: {'l1_ratio': 0.5866224126283596}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:00,380] Trial 88 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.8053530158005092}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:00,935] Trial 89 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.8731797997118407}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:01,530] Trial 90 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6552066006120573}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:02,468] Trial 91 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.717514310881818}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:03,109] Trial 92 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.6143175248871401}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:03,639] Trial 93 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.6796494508743418}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:04,236] Trial 94 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.8177030584461242}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:04,838] Trial 95 finished with value: 0.6580925585585977 and parameters: {'l1_ratio': 0.6972254278901787}. Best is trial 4 with value: 0.6589436223883849.

Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:05,348] Trial 96 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.6496492060425906}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:05,912] Trial 97 finished with value: 0.6589436223883849 and parameters: {'l1_ratio': 0.7677648169785204}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:06,583] Trial 98 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.3410246190042779}. Best is trial 4 with value: 0.6589436223883849.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617

[I 2024-04-14 20:32:07,219] A new study created in memory with name: no-name-056b31fa-6fc2-42ed-849f-3434a2c5ea8a

Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 20:32:07,178] Trial 99 finished with value: 0.6581831661146207 and parameters: {'l1_ratio': 0.5350949465525721}. Best is trial 4 with value: 0.6589436223883849.


* Best trial for C-index:
 FrozenTrial(number=4, state=TrialState.COMPLETE, values=[0.6589436223883849], datetime_start=datetime.datetime(2024, 4, 14, 20, 31, 13, 613495), datetime_complete=datetime.datetime(2024, 4, 14, 20, 31, 14, 671650), params={'l1_ratio': 0.7194970228885845}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=4, value=None)


* Best Score for C-index:
 0.6589436223883849

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.27267447509122855
Fold 2 IBS: 0.17344925973192413
Fold 3 IBS: 0.20995771934819113
Fold 4 IBS: 0.2523770813863882
Fold 5 IBS: 0.20507943055313463
[I 2024-04-14 20:32:07,985] Trial 0 finished with value: 0.22270759322217332 and parameters: {'l1_ratio': 0.6964995386793018}. Best is trial 0 with value: 0.22270759322217332.
Fold 1 IBS: 0.2725025347145614
Fold 2 IBS: 0.17314954653948833
Fold 3 IBS: 0.2100613142241499
Fold 4 IBS: 0.25224126142504594
Fold 5 IBS: 0.20489681131134482
[I 2024-04-14 20:32:08,750] Trial 1 finished with value: 0.22257029364291805 and parameters: {'l1_ratio': 0.28621072101688444}. Best is trial 1 with value: 0.22257029364291805.
Fold 1 IBS: 0.27243658214766786
Fold 2 IBS: 0.17282261994180062
Fold 3 IBS: 0.20988632452153375
Fold 4 IBS: 0.2521745411667705
Fold 5 IBS: 0.20478516930358523
[I 2024-04-14 20:32:09,496] Trial 2 finished with value: 0.2224210474162716 and parameters: {'l1_ratio': 0.22692876841884668}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.2726218916855312
Fold 2 IBS: 0.1734513228173431
Fold 3 IBS: 0.20978679445146925
Fold 4 IBS: 0.2523478367425682
Fold 5 IBS: 0.2050434631864783
[I 2024-04-14 20:32:10,088] Trial 3 finished with value: 0.22265026177667804 and parameters: {'l1_ratio': 0.5513596376059829}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.272722134809067
Fold 2 IBS: 0.17343877694903226
Fold 3 IBS: 0.20980877657215966
Fold 4 IBS: 0.2524200790116679
Fold 5 IBS: 0.20512034454675843
[I 2024-04-14 20:32:10,660] Trial 4 finished with value: 0.22270202237773704 and parameters: {'l1_ratio': 0.7194970228885845}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.27251476150675036
Fold 2 IBS: 0.17332728571199768
Fold 3 IBS: 0.2100580709884127
Fold 4 IBS: 0.25230497169358773
Fold 5 IBS: 0.20497814078330173
[I 2024-04-14 20:32:11,259] Trial 5 finished with value: 0.22263664613681006 and parameters: {'l1_ratio': 0.4231641494784485}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.27274702060771794
Fold 2 IBS: 0.17342549250130895
Fold 3 IBS: 0.20974334031017905
Fold 4 IBS: 0.25258782002901475
Fold 5 IBS: 0.20530986465400833
[I 2024-04-14 20:32:11,877] Trial 6 finished with value: 0.22276270762044584 and parameters: {'l1_ratio': 0.980766121964777}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.27265130239427376
Fold 2 IBS: 0.17345492710933405
Fold 3 IBS: 0.2097354348131622
Fold 4 IBS: 0.2524401218142126
Fold 5 IBS: 0.20517624844489518
[I 2024-04-14 20:32:12,432] Trial 7 finished with value: 0.22269160691517556 and parameters: {'l1_ratio': 0.6848612556110047}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.2725619078977563
Fold 2 IBS: 0.17342703188089215
Fold 3 IBS: 0.2100851081915368
Fold 4 IBS: 0.2522761716522433
Fold 5 IBS: 0.20500361193278976
[I 2024-04-14 20:32:13,143] Trial 8 finished with value: 0.22267076631104366 and parameters: {'l1_ratio': 0.4809838082942125}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.2725443398548305
Fold 2 IBS: 0.17329809024617454
Fold 3 IBS: 0.20978782556484454
Fold 4 IBS: 0.25222041153891483
Fold 5 IBS: 0.20491715329495838
[I 2024-04-14 20:32:13,842] Trial 9 finished with value: 0.22255356409994453 and parameters: {'l1_ratio': 0.3921783064423311}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.272509886908485
Fold 2 IBS: 0.1723489512073146
Fold 3 IBS: 0.22875147163974346
Fold 4 IBS: 0.2520515627399957
Fold 5 IBS: 0.2048340237104556
[I 2024-04-14 20:32:14,509] Trial 10 finished with value: 0.22609917924119888 and parameters: {'l1_ratio': 0.08382735104105443}. Best is trial 2 with value: 0.2224210474162716.
Fold 1 IBS: 0.2725519919751355
Fold 2 IBS: 0.17262876022576318
Fold 3 IBS: 0.20986204198415975
Fold 4 IBS: 0.2521303646812237
Fold 5 IBS: 0.20477908959222574
[I 2024-04-14 20:32:15,332] Trial 11 finished with value: 0.22239044969170157 and parameters: {'l1_ratio': 0.18301335955800116}. Best is trial 11 with value: 0.22239044969170157.
Fold 1 IBS: 0.2724818311872945
Fold 2 IBS: 0.22679521371968697
Fold 3 IBS: 0.22882173413700507
Fold 4 IBS: 0.23873130586258368
Fold 5 IBS: 0.20483949014709113
[I 2024-04-14 20:32:15,830] Trial 12 finished with value: 0.23433391501073228 and parameters: {'l1_ratio': 0.0469133649279421}. Best is trial 11 with value: 0.22239044969170157.
Fold 1 IBS: 0.27260893603466446
Fold 2 IBS: 0.17275954445853056
Fold 3 IBS: 0.20991601975802632
Fold 4 IBS: 0.2521784977036988
Fold 5 IBS: 0.20481023895269565
[I 2024-04-14 20:32:16,526] Trial 13 finished with value: 0.22245464738152315 and parameters: {'l1_ratio': 0.2094262397934587}. Best is trial 11 with value: 0.22239044969170157.
Fold 1 IBS: 0.27251338565422045
Fold 2 IBS: 0.17290573471768997
Fold 3 IBS: 0.20995917335936365
Fold 4 IBS: 0.25222466110748754
Fold 5 IBS: 0.20483925603227016
[I 2024-04-14 20:32:17,256] Trial 14 finished with value: 0.22248844217420638 and parameters: {'l1_ratio': 0.23856005198520522}. Best is trial 11 with value: 0.22239044969170157.
Fold 1 IBS: 0.27245414236457194
Fold 2 IBS: 0.17252980621712238
Fold 3 IBS: 0.21006884013079502
Fold 4 IBS: 0.2521386940183683
Fold 5 IBS: 0.20472084234090618
[I 2024-04-14 20:32:17,925] Trial 15 finished with value: 0.22238246501435274 and parameters: {'l1_ratio': 0.15608110273200437}. Best is trial 15 with value: 0.22238246501435274.
Fold 1 IBS: 0.24706002175554387
Fold 2 IBS: 0.23153429422776403
Fold 3 IBS: 0.22896507881590783
Fold 4 IBS: 0.24165175565508393
Fold 5 IBS: 0.22914225320835466
[I 2024-04-14 20:32:18,174] Trial 16 finished with value: 0.2356706807325309 and parameters: {'l1_ratio': 0.00393776041933136}. Best is trial 15 with value: 0.22238246501435274.
Fold 1 IBS: 0.2724799953428319
Fold 2 IBS: 0.172447633057574
Fold 3 IBS: 0.20981657972909798
Fold 4 IBS: 0.2521441989547756
Fold 5 IBS: 0.20489401065691312
[I 2024-04-14 20:32:19,293] Trial 17 finished with value: 0.2223564835482385 and parameters: {'l1_ratio': 0.13165037459754073}. Best is trial 17 with value: 0.2223564835482385.
Fold 1 IBS: 0.27246865870638437
Fold 2 IBS: 0.17323067940252054
Fold 3 IBS: 0.20986133200366108
Fold 4 IBS: 0.25224046835562863
Fold 5 IBS: 0.20489643132034366
[I 2024-04-14 20:32:19,983] Trial 18 finished with value: 0.22253951395770769 and parameters: {'l1_ratio': 0.33883882709417557}. Best is trial 17 with value: 0.2223564835482385.
Fold 1 IBS: 0.2725487483137072
Fold 2 IBS: 0.1724459361189172
Fold 3 IBS: 0.2100306554294702
Fold 4 IBS: 0.2521015421689644
Fold 5 IBS: 0.20480938904093127
[I 2024-04-14 20:32:20,726] Trial 19 finished with value: 0.22238725421439803 and parameters: {'l1_ratio': 0.13776165601418522}. Best is trial 17 with value: 0.2223564835482385.
Fold 1 IBS: 0.27257972037627387
Fold 2 IBS: 0.17342690968865554
Fold 3 IBS: 0.20986227115333733
Fold 4 IBS: 0.252345646307226
Fold 5 IBS: 0.20512103567913978
[I 2024-04-14 20:32:21,392] Trial 20 finished with value: 0.2226671166409265 and parameters: {'l1_ratio': 0.5914245950308872}. Best is trial 17 with value: 0.2223564835482385.
Fold 1 IBS: 0.2724565685933809
Fold 2 IBS: 0.1723700311290434
Fold 3 IBS: 0.20979523849269996
Fold 4 IBS: 0.2521231192386908
Fold 5 IBS: 0.20488350591201981
[I 2024-04-14 20:32:22,200] Trial 21 finished with value: 0.22232569267316699 and parameters: {'l1_ratio': 0.11781148032178282}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724890118343207
Fold 2 IBS: 0.17243964874649556
Fold 3 IBS: 0.20997848033424105
Fold 4 IBS: 0.2521441536539333
Fold 5 IBS: 0.20490664035251008
[I 2024-04-14 20:32:22,936] Trial 22 finished with value: 0.22239158698430014 and parameters: {'l1_ratio': 0.12045064419966593}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.247133645508455
Fold 2 IBS: 0.23173363528797455
Fold 3 IBS: 0.22897166987708772
Fold 4 IBS: 0.24177876514150032
Fold 5 IBS: 0.22924221776098622
[I 2024-04-14 20:32:23,181] Trial 23 finished with value: 0.23577198671520078 and parameters: {'l1_ratio': 0.002373744016739676}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724303678704235
Fold 2 IBS: 0.17322193787826498
Fold 3 IBS: 0.20983165062250056
Fold 4 IBS: 0.25220404732415047
Fold 5 IBS: 0.20485890829935738
[I 2024-04-14 20:32:23,767] Trial 24 finished with value: 0.2225093823989394 and parameters: {'l1_ratio': 0.30100424142785454}. Best is trial 21 with value: 0.22232569267316699.

Fold 1 IBS: 0.27253376544295665
Fold 2 IBS: 0.17240489453662233
Fold 3 IBS: 0.21002324567043654
Fold 4 IBS: 0.2520836800787669
Fold 5 IBS: 0.20483452937549124
[I 2024-04-14 20:32:24,704] Trial 25 finished with value: 0.22237602302085474 and parameters: {'l1_ratio': 0.1238911155354028}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27280705714960496
Fold 2 IBS: 0.1734416623532437
Fold 3 IBS: 0.20982839720989
Fold 4 IBS: 0.25260209853835824
Fold 5 IBS: 0.20534754660191004
[I 2024-04-14 20:32:26,119] Trial 26 finished with value: 0.22280535237060137 and parameters: {'l1_ratio': 0.9276289503411492}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2723972152384981
Fold 2 IBS: 0.17233541800588956
Fold 3 IBS: 0.22874926185250916
Fold 4 IBS: 0.2520723565594682
Fold 5 IBS: 0.20485489827924006
[I 2024-04-14 20:32:26,702] Trial 27 finished with value: 0.226081829987121 and parameters: {'l1_ratio': 0.08555734699384382}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27254168979021726
Fold 2 IBS: 0.17327227301158357
Fold 3 IBS: 0.20977113023270905
Fold 4 IBS: 0.2522033383310808
Fold 5 IBS: 0.20490664268473413
[I 2024-04-14 20:32:27,315] Trial 28 finished with value: 0.222539014810065 and parameters: {'l1_ratio': 0.355721226193779}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.272511895563791
Fold 2 IBS: 0.17314948447621342
Fold 3 IBS: 0.2097826949999447
Fold 4 IBS: 0.2522488195770795
Fold 5 IBS: 0.20483180909847576
[I 2024-04-14 20:32:28,177] Trial 29 finished with value: 0.22250494074310087 and parameters: {'l1_ratio': 0.2883035752511037}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27245269218768986
Fold 2 IBS: 0.1723719377875596
Fold 3 IBS: 0.22875552847652456
Fold 4 IBS: 0.2521050400345707
Fold 5 IBS: 0.204795896540216
[I 2024-04-14 20:32:28,966] Trial 30 finished with value: 0.22609621900531213 and parameters: {'l1_ratio': 0.08082403736771315}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27247212660592696
Fold 2 IBS: 0.17253530909073694
Fold 3 IBS: 0.2098071224003203
Fold 4 IBS: 0.2521508371493545
Fold 5 IBS: 0.20473380907264688
[I 2024-04-14 20:32:29,679] Trial 31 finished with value: 0.2223398408637971 and parameters: {'l1_ratio': 0.1579645274939656}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27249183102907104
Fold 2 IBS: 0.17263457142519886
Fold 3 IBS: 0.20980204807619807
Fold 4 IBS: 0.2521697380953052
Fold 5 IBS: 0.20473598912209448
[I 2024-04-14 20:32:30,764] Trial 32 finished with value: 0.22236683554957354 and parameters: {'l1_ratio': 0.17584575048204967}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27251294780480567
Fold 2 IBS: 0.17273495262809238
Fold 3 IBS: 0.20981804383857838
Fold 4 IBS: 0.2522140183501542
Fold 5 IBS: 0.20483048528360856
[I 2024-04-14 20:32:31,492] Trial 33 finished with value: 0.22242208958104787 and parameters: {'l1_ratio': 0.21684874050642938}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724946970989076
Fold 2 IBS: 0.17296770753106377
Fold 3 IBS: 0.2100686258620798
Fold 4 IBS: 0.2522238779495667
Fold 5 IBS: 0.2048147362782615
[I 2024-04-14 20:32:32,223] Trial 34 finished with value: 0.22251392894397587 and parameters: {'l1_ratio': 0.2593224549665287}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27250653316321344
Fold 2 IBS: 0.17269203636610395
Fold 3 IBS: 0.20981841157712094
Fold 4 IBS: 0.25220025914945715
Fold 5 IBS: 0.2048232573483869
[I 2024-04-14 20:32:33,056] Trial 35 finished with value: 0.22240809952085652 and parameters: {'l1_ratio': 0.19631609988412568}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27247208270535495
Fold 2 IBS: 0.22592746005077088
Fold 3 IBS: 0.22879969206097936
Fold 4 IBS: 0.23820027283699527
Fold 5 IBS: 0.20482632940537468
[I 2024-04-14 20:32:33,507] Trial 36 finished with value: 0.23404516741189502 and parameters: {'l1_ratio': 0.056224933599674}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2726220379020533
Fold 2 IBS: 0.17337933131526942
Fold 3 IBS: 0.20981445813392416
Fold 4 IBS: 0.2522992494165717
Fold 5 IBS: 0.20496342867278391
[I 2024-04-14 20:32:34,351] Trial 37 finished with value: 0.2226157010881205 and parameters: {'l1_ratio': 0.4544709824843894}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2726534942307942
Fold 2 IBS: 0.17344302893228222
Fold 3 IBS: 0.20981909676449123
Fold 4 IBS: 0.2523723395938109
Fold 5 IBS: 0.20506936878481039
[I 2024-04-14 20:32:35,005] Trial 38 finished with value: 0.2226714656612378 and parameters: {'l1_ratio': 0.5638551523074651}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27263000255969255
Fold 2 IBS: 0.17347656366789282
Fold 3 IBS: 0.2098230259997802
Fold 4 IBS: 0.25250021650633486
Fold 5 IBS: 0.20526964835689804
[I 2024-04-14 20:32:35,550] Trial 39 finished with value: 0.2227398914181197 and parameters: {'l1_ratio': 0.8218066760829867}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725568267044786
Fold 2 IBS: 0.1732426304667824
Fold 3 IBS: 0.2097897004744903
Fold 4 IBS: 0.25219809379580305
Fold 5 IBS: 0.2049232472719936
[I 2024-04-14 20:32:36,163] Trial 40 finished with value: 0.22254209974270958 and parameters: {'l1_ratio': 0.3262219477103148}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725337385531216
Fold 2 IBS: 0.17240490422047886
Fold 3 IBS: 0.21002321894011328
Fold 4 IBS: 0.25208366270288624
Fold 5 IBS: 0.20483451207807146
[I 2024-04-14 20:32:36,820] Trial 41 finished with value: 0.22237600729893425 and parameters: {'l1_ratio': 0.1238890323782831}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725180548162021
Fold 2 IBS: 0.17249045887012673
Fold 3 IBS: 0.20999468322983614
Fold 4 IBS: 0.2520866832817889
Fold 5 IBS: 0.2047760642114493
[I 2024-04-14 20:32:37,446] Trial 42 finished with value: 0.22237318888188065 and parameters: {'l1_ratio': 0.14816115724262682}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725799576689414
Fold 2 IBS: 0.17257327800841463
Fold 3 IBS: 0.21004545384052592
Fold 4 IBS: 0.25213328590903983
Fold 5 IBS: 0.20479143409343228
[I 2024-04-14 20:32:38,016] Trial 43 finished with value: 0.2224246819040708 and parameters: {'l1_ratio': 0.16958160878319628}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27255916103930244
Fold 2 IBS: 0.17329446503842952
Fold 3 IBS: 0.2098042543684876
Fold 4 IBS: 0.252231823199669
Fold 5 IBS: 0.2049280216406895
[I 2024-04-14 20:32:38,618] Trial 44 finished with value: 0.22256354505731563 and parameters: {'l1_ratio': 0.3960372028330807}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.272483712419506
Fold 2 IBS: 0.17297574905642246
Fold 3 IBS: 0.20990600951305957
Fold 4 IBS: 0.25221612911819685
Fold 5 IBS: 0.20480516713697958
[I 2024-04-14 20:32:39,233] Trial 45 finished with value: 0.22247735344883285 and parameters: {'l1_ratio': 0.25705435694653944}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725052696137731
Fold 2 IBS: 0.22672506657845556
Fold 3 IBS: 0.22881988792437527
Fold 4 IBS: 0.23868850076156806
Fold 5 IBS: 0.20485430283990402
[I 2024-04-14 20:32:39,611] Trial 46 finished with value: 0.2343186055436152 and parameters: {'l1_ratio': 0.04764662881439466}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724474921385963
Fold 2 IBS: 0.17270317858630826
Fold 3 IBS: 0.2099128947002801
Fold 4 IBS: 0.2521610720427146
Fold 5 IBS: 0.20481192676001234
[I 2024-04-14 20:32:40,315] Trial 47 finished with value: 0.2224073128455823 and parameters: {'l1_ratio': 0.1888926107407425}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724759327699721
Fold 2 IBS: 0.17240179082981508
Fold 3 IBS: 0.22873524049362584
Fold 4 IBS: 0.25212814492446484
Fold 5 IBS: 0.20481139842322096
[I 2024-04-14 20:32:40,928] Trial 48 finished with value: 0.22611050148821973 and parameters: {'l1_ratio': 0.09893321444596145}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724187777587002
Fold 2 IBS: 0.17300498326274374
Fold 3 IBS: 0.2098592409606603
Fold 4 IBS: 0.2521735804274887
Fold 5 IBS: 0.20485531757052322
[I 2024-04-14 20:32:41,704] Trial 49 finished with value: 0.22246237999602325 and parameters: {'l1_ratio': 0.24668420292251425}. Best is trial 21 with value: 0.22232569267316699.

Fold 1 IBS: 0.2725595777761324
Fold 2 IBS: 0.22773614218874613
Fold 3 IBS: 0.22884747321581533
Fold 4 IBS: 0.23930457631194157
Fold 5 IBS: 0.22719631294170334
[I 2024-04-14 20:32:42,136] Trial 50 finished with value: 0.23912881648686776 and parameters: {'l1_ratio': 0.03738779124899358}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27241324639370174
Fold 2 IBS: 0.17240363993199545
Fold 3 IBS: 0.21004401066910072
Fold 4 IBS: 0.2521006210760798
Fold 5 IBS: 0.20485143916669354
[I 2024-04-14 20:32:43,045] Trial 51 finished with value: 0.22236259144751425 and parameters: {'l1_ratio': 0.12594937537013567}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725807308561395
Fold 2 IBS: 0.1725358755395789
Fold 3 IBS: 0.21006056510271615
Fold 4 IBS: 0.2521299293563059
Fold 5 IBS: 0.20479134153756906
[I 2024-04-14 20:32:43,846] Trial 52 finished with value: 0.22241968847846189 and parameters: {'l1_ratio': 0.1547276572252059}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27253857198684656
Fold 2 IBS: 0.17258809300146588
Fold 3 IBS: 0.21000795968232971
Fold 4 IBS: 0.2521065171555024
Fold 5 IBS: 0.20477858188012846
[I 2024-04-14 20:32:44,518] Trial 53 finished with value: 0.2224039447412546 and parameters: {'l1_ratio': 0.16500940612185233}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27246344530654776
Fold 2 IBS: 0.17275808316742045
Fold 3 IBS: 0.20991913528317532
Fold 4 IBS: 0.2521804251059785
Fold 5 IBS: 0.2048122776577445
[I 2024-04-14 20:32:45,175] Trial 54 finished with value: 0.22242667330417332 and parameters: {'l1_ratio': 0.20982547475390428}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724166045338285
Fold 2 IBS: 0.17236375053510503
Fold 3 IBS: 0.2287309441586547
Fold 4 IBS: 0.25209274573056917
Fold 5 IBS: 0.20486477683640025
[I 2024-04-14 20:32:45,726] Trial 55 finished with value: 0.22609376435891154 and parameters: {'l1_ratio': 0.10452649725548109}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27260278443076463
Fold 2 IBS: 0.17346595139816887
Fold 3 IBS: 0.20985463195229148
Fold 4 IBS: 0.25239568155282865
Fold 5 IBS: 0.20513408359453394
[I 2024-04-14 20:32:46,318] Trial 56 finished with value: 0.2226906265857175 and parameters: {'l1_ratio': 0.6609950930191556}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2464202562221116
Fold 2 IBS: 0.22978461525882454
Fold 3 IBS: 0.22890867914892085
Fold 4 IBS: 0.2405580108505631
Fold 5 IBS: 0.22825788956373386
[I 2024-04-14 20:32:46,541] Trial 57 finished with value: 0.2347858902088308 and parameters: {'l1_ratio': 0.018448934228956382}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27245069845282516
Fold 2 IBS: 0.17235874647056074
Fold 3 IBS: 0.22876668916194184
Fold 4 IBS: 0.2520991901336404
Fold 5 IBS: 0.20479926249538874
[I 2024-04-14 20:32:47,108] Trial 58 finished with value: 0.22609491734287138 and parameters: {'l1_ratio': 0.07345360682571}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724375696578914
Fold 2 IBS: 0.1724775482443417
Fold 3 IBS: 0.2100607425161866
Fold 4 IBS: 0.25212277323797316
Fold 5 IBS: 0.20481487385364694
[I 2024-04-14 20:32:47,875] Trial 59 finished with value: 0.22238270150200795 and parameters: {'l1_ratio': 0.14066541949457997}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27252451164173
Fold 2 IBS: 0.17314463319635096
Fold 3 IBS: 0.20977485859658923
Fold 4 IBS: 0.2522560396777446
Fold 5 IBS: 0.20490416500355785
[I 2024-04-14 20:32:48,498] Trial 60 finished with value: 0.22252084162319458 and parameters: {'l1_ratio': 0.29079246870604664}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725210831822394
Fold 2 IBS: 0.1724191459278384
Fold 3 IBS: 0.2100121047228189
Fold 4 IBS: 0.2520761795568327
Fold 5 IBS: 0.2048285438429683
[I 2024-04-14 20:32:49,184] Trial 61 finished with value: 0.22237141144653952 and parameters: {'l1_ratio': 0.12300000170055883}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27250033177468586
Fold 2 IBS: 0.17264332488635128
Fold 3 IBS: 0.20980873955837534
Fold 4 IBS: 0.25218173602815613
Fold 5 IBS: 0.20475826891767654
[I 2024-04-14 20:32:49,811] Trial 62 finished with value: 0.22237848023304901 and parameters: {'l1_ratio': 0.1767614153402856}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724095471298494
Fold 2 IBS: 0.17283096451272792
Fold 3 IBS: 0.2098621712088164
Fold 4 IBS: 0.25215671583197774
Fold 5 IBS: 0.20485878604489657
[I 2024-04-14 20:32:50,386] Trial 63 finished with value: 0.2224236369456536 and parameters: {'l1_ratio': 0.22296719267823029}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27244108089165714
Fold 2 IBS: 0.17237077813739615
Fold 3 IBS: 0.2100729807358064
Fold 4 IBS: 0.2521126208711755
Fold 5 IBS: 0.20487394247172652
[I 2024-04-14 20:32:51,027] Trial 64 finished with value: 0.22237428062155234 and parameters: {'l1_ratio': 0.11658144317908864}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27245944704615077
Fold 2 IBS: 0.2254768276187557
Fold 3 IBS: 0.2287889864208616
Fold 4 IBS: 0.25209691976481113
Fold 5 IBS: 0.2048147564593229
[I 2024-04-14 20:32:51,515] Trial 65 finished with value: 0.2367273874619804 and parameters: {'l1_ratio': 0.061276875123877445}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27237114764717646
Fold 2 IBS: 0.17247550907793333
Fold 3 IBS: 0.21000428332484938
Fold 4 IBS: 0.25209213556321736
Fold 5 IBS: 0.20478256619080829
[I 2024-04-14 20:32:52,138] Trial 66 finished with value: 0.22234512836079695 and parameters: {'l1_ratio': 0.1490649629620104}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724798841331858
Fold 2 IBS: 0.17240012154419634
Fold 3 IBS: 0.2287350337421227
Fold 4 IBS: 0.25213071145486804
Fold 5 IBS: 0.20491224500942126
[I 2024-04-14 20:32:52,728] Trial 67 finished with value: 0.22613159917675882 and parameters: {'l1_ratio': 0.09917767911375917}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2461365448375806
Fold 2 IBS: 0.22899626726780825
Fold 3 IBS: 0.22888440191356302
Fold 4 IBS: 0.2400734969311688
Fold 5 IBS: 0.2278535826906897
[I 2024-04-14 20:32:53,073] Trial 68 finished with value: 0.2343888587281621 and parameters: {'l1_ratio': 0.025466927244587212}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27244267986136583
Fold 2 IBS: 0.1729972351929752
Fold 3 IBS: 0.20987858627316175
Fold 4 IBS: 0.25218920681917534
Fold 5 IBS: 0.2048668902205295
[I 2024-04-14 20:32:53,657] Trial 69 finished with value: 0.22247491967344152 and parameters: {'l1_ratio': 0.2503439737625358}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27250404685397134
Fold 2 IBS: 0.17269321409581803
Fold 3 IBS: 0.20981584052278054
Fold 4 IBS: 0.2521987331980696
Fold 5 IBS: 0.20482164427155922
[I 2024-04-14 20:32:54,317] Trial 70 finished with value: 0.22240669578843977 and parameters: {'l1_ratio': 0.19601811855144502}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724267267223729
Fold 2 IBS: 0.1724728251321137
Fold 3 IBS: 0.21005125900590188
Fold 4 IBS: 0.2521150778729286
Fold 5 IBS: 0.20480702506444032
[I 2024-04-14 20:32:54,947] Trial 71 finished with value: 0.2223745827595515 and parameters: {'l1_ratio': 0.13960583587314923}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725075214525802
Fold 2 IBS: 0.17248785291238436
Fold 3 IBS: 0.20983772248484908
Fold 4 IBS: 0.25216727446031817
Fold 5 IBS: 0.2047691276914919
[I 2024-04-14 20:32:55,581] Trial 72 finished with value: 0.22235389980032477 and parameters: {'l1_ratio': 0.1471979788156534}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27250049514942404
Fold 2 IBS: 0.17233497914252208
Fold 3 IBS: 0.22876286522119546
Fold 4 IBS: 0.25204220334624866
Fold 5 IBS: 0.2048326247642517
[I 2024-04-14 20:32:56,154] Trial 73 finished with value: 0.22609463352472842 and parameters: {'l1_ratio': 0.07585352244108706}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725860800045409
Fold 2 IBS: 0.17257326028249448
Fold 3 IBS: 0.21005513487395394
Fold 4 IBS: 0.2521396564839328

Fold 5 IBS: 0.20479804430809104
[I 2024-04-14 20:32:56,735] Trial 74 finished with value: 0.22243043519060263 and parameters: {'l1_ratio': 0.17063221060123465}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27252024947484704
Fold 2 IBS: 0.1732585874278285
Fold 3 IBS: 0.20975567436238726
Fold 4 IBS: 0.25226631721901643
Fold 5 IBS: 0.204898114726913
[I 2024-04-14 20:32:57,274] Trial 75 finished with value: 0.22253978864219848 and parameters: {'l1_ratio': 0.3186692068904706}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724317016287503
Fold 2 IBS: 0.17281995720978222
Fold 3 IBS: 0.20988153305424986
Fold 4 IBS: 0.252171936742705
Fold 5 IBS: 0.20479798026846704
[I 2024-04-14 20:32:57,904] Trial 76 finished with value: 0.22242062178079086 and parameters: {'l1_ratio': 0.22627165809269023}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724137644671228
Fold 2 IBS: 0.17307016239184442
Fold 3 IBS: 0.20982935102349748
Fold 4 IBS: 0.2521822750885039
Fold 5 IBS: 0.20484077313208315
[I 2024-04-14 20:32:58,580] Trial 77 finished with value: 0.22246726522061033 and parameters: {'l1_ratio': 0.27066879559099527}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2472295610881124
Fold 2 IBS: 0.23199261346636796
Fold 3 IBS: 0.2289802883635628
Fold 4 IBS: 0.24194444517712518
Fold 5 IBS: 0.22937193343811235
[I 2024-04-14 20:32:58,830] Trial 78 finished with value: 0.23590376830665613 and parameters: {'l1_ratio': 0.0003641302711779454}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724266419218755
Fold 2 IBS: 0.1724067868998506
Fold 3 IBS: 0.21005489638404523
Fold 4 IBS: 0.252109188837027
Fold 5 IBS: 0.20485759028736353
[I 2024-04-14 20:32:59,522] Trial 79 finished with value: 0.2223710208660324 and parameters: {'l1_ratio': 0.12701423507973433}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27248302523244955
Fold 2 IBS: 0.17331343878327238
Fold 3 IBS: 0.2098627043194021
Fold 4 IBS: 0.25226742926244455
Fold 5 IBS: 0.20496933793083325
[I 2024-04-14 20:33:00,235] Trial 80 finished with value: 0.22257918710568037 and parameters: {'l1_ratio': 0.37710923909496186}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.272509115693222
Fold 2 IBS: 0.17243150142757172
Fold 3 IBS: 0.20999841215096546
Fold 4 IBS: 0.2520685527958893
Fold 5 IBS: 0.2049190450611862
[I 2024-04-14 20:33:00,869] Trial 81 finished with value: 0.22238532542576692 and parameters: {'l1_ratio': 0.12195150428237497}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27240099967498455
Fold 2 IBS: 0.17237000393653337
Fold 3 IBS: 0.22873165363101813
Fold 4 IBS: 0.25208291389010495
Fold 5 IBS: 0.20485555360446475
[I 2024-04-14 20:33:01,436] Trial 82 finished with value: 0.22608822494742115 and parameters: {'l1_ratio': 0.10351586133705698}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27248089071900733
Fold 2 IBS: 0.1726872949184576
Fold 3 IBS: 0.2099467781959354
Fold 4 IBS: 0.25218301741473526
Fold 5 IBS: 0.20481676505877153
[I 2024-04-14 20:33:02,077] Trial 83 finished with value: 0.22242294926138145 and parameters: {'l1_ratio': 0.19295913251939864}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27245719600243706
Fold 2 IBS: 0.17248773681582158
Fold 3 IBS: 0.21007960632434972
Fold 4 IBS: 0.25213412676862895
Fold 5 IBS: 0.20482608210927358
[I 2024-04-14 20:33:02,948] Trial 84 finished with value: 0.2223969496041022 and parameters: {'l1_ratio': 0.14225151749595594}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724715137236597
Fold 2 IBS: 0.2254368551153301
Fold 3 IBS: 0.2287880634422398
Fold 4 IBS: 0.2521051769069331
Fold 5 IBS: 0.20482235123452286
[I 2024-04-14 20:33:03,424] Trial 85 finished with value: 0.23672479208453714 and parameters: {'l1_ratio': 0.06173250564222516}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725317855964874
Fold 2 IBS: 0.17347405090794224
Fold 3 IBS: 0.2100280228845651
Fold 4 IBS: 0.2522788112152287
Fold 5 IBS: 0.20508893940970752
[I 2024-04-14 20:33:04,020] Trial 86 finished with value: 0.2226803220027862 and parameters: {'l1_ratio': 0.5196302291802515}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2723841694633759
Fold 2 IBS: 0.17235679025257
Fold 3 IBS: 0.2287405411932494
Fold 4 IBS: 0.2520680339776828
Fold 5 IBS: 0.2048499831048639
[I 2024-04-14 20:33:04,588] Trial 87 finished with value: 0.22607990359834843 and parameters: {'l1_ratio': 0.09325171252219029}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27244204233577735
Fold 2 IBS: 0.17253338639785845
Fold 3 IBS: 0.2100627393412857
Fold 4 IBS: 0.25213134937662
Fold 5 IBS: 0.204792817057962
[I 2024-04-14 20:33:05,568] Trial 88 finished with value: 0.2223924669019007 and parameters: {'l1_ratio': 0.15494321874479328}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27256366163564205
Fold 2 IBS: 0.22736025927394965
Fold 3 IBS: 0.2288369821734827
Fold 4 IBS: 0.23907568335592905
Fold 5 IBS: 0.22699705503530354
[I 2024-04-14 20:33:05,840] Trial 89 finished with value: 0.2389667282948614 and parameters: {'l1_ratio': 0.04112537483064632}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27243252723620787
Fold 2 IBS: 0.1728195691325524
Fold 3 IBS: 0.2098823435847744
Fold 4 IBS: 0.25217244722116344
Fold 5 IBS: 0.20479860050561882
[I 2024-04-14 20:33:06,391] Trial 90 finished with value: 0.22242109753606337 and parameters: {'l1_ratio': 0.22638261362085277}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725233259378154
Fold 2 IBS: 0.1724421150512216
Fold 3 IBS: 0.21000823324985884
Fold 4 IBS: 0.252084660953254
Fold 5 IBS: 0.20479116817679902
[I 2024-04-14 20:33:07,112] Trial 91 finished with value: 0.22236990067378976 and parameters: {'l1_ratio': 0.13537625554855906}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725273291261887
Fold 2 IBS: 0.17241117010286908
Fold 3 IBS: 0.21001685408781842
Fold 4 IBS: 0.2520795187310386
Fold 5 IBS: 0.20483041205938435
[I 2024-04-14 20:33:08,517] Trial 92 finished with value: 0.22237305682145986 and parameters: {'l1_ratio': 0.12339404719888745}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725167155722384
Fold 2 IBS: 0.17263729745056006
Fold 3 IBS: 0.20982972458812252
Fold 4 IBS: 0.25219241329905245
Fold 5 IBS: 0.20475613465559775
[I 2024-04-14 20:33:09,504] Trial 93 finished with value: 0.22238645711311422 and parameters: {'l1_ratio': 0.17896549217329016}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27239421385036
Fold 2 IBS: 0.1723366107237784
Fold 3 IBS: 0.22874945402680955
Fold 4 IBS: 0.2520705400977955
Fold 5 IBS: 0.2048530702288661
[I 2024-04-14 20:33:10,350] Trial 94 finished with value: 0.2260807777855219 and parameters: {'l1_ratio': 0.0854039772271626}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2724759519334244
Fold 2 IBS: 0.17275196118587438
Fold 3 IBS: 0.2099315240852117
Fold 4 IBS: 0.25218815890223173
Fold 5 IBS: 0.20482039536587582
[I 2024-04-14 20:33:11,217] Trial 95 finished with value: 0.22243359829452358 and parameters: {'l1_ratio': 0.21142472134659535}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27251065539923197
Fold 2 IBS: 0.17253146655743268
Fold 3 IBS: 0.2098329101086703
Fold 4 IBS: 0.2521764744169732
Fold 5 IBS: 0.20476006882689174
[I 2024-04-14 20:33:12,096] Trial 96 finished with value: 0.22236231506183998 and parameters: {'l1_ratio': 0.16217776656144753}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.2725475847061402
Fold 2 IBS: 0.17258790883236255
Fold 3 IBS: 0.2100169112780044
Fold 4 IBS: 0.252112432635402
Fold 5 IBS: 0.2047845877181862
[I 2024-04-14 20:33:13,036] Trial 97 finished with value: 0.2224098850340191 and parameters: {'l1_ratio': 0.16594139255688925}. Best is trial 21 with value: 0.22232569267316699.
Fold 1 IBS: 0.27267437395304833
Fold 2 IBS: 0.17341860640017123
Fold 3 IBS: 0.2097318185555649
Fold 4 IBS: 0.25241893192363424
Fold 5 IBS: 0.20518418550274029
[I 2024-04-14 20:33:13,722] Trial 98 finished with value: 0.2226855832670318 and parameters: {'l1_ratio': 0.7667338152719219}. Best is trial 21 with value: 0.22232569267316699.

Fold 1 IBS: 0.27251450716401543
Fold 2 IBS: 0.17269346713002628
Fold 3 IBS: 0.20982783116730855
Fold 4 IBS: 0.25211901168401063
Fold 5 IBS: 0.20482923375301645
[I 2024-04-14 20:33:14,530] Trial 99 finished with value: 0.22239681017967547 and parameters: {'l1_ratio': 0.19742502235371856}. Best is trial 21 with value: 0.22232569267316699.


* Best trial for IBS:
 FrozenTrial(number=21, state=TrialState.COMPLETE, values=[0.22232569267316699], datetime_start=datetime.datetime(2024, 4, 14, 20, 32, 21, 405235), datetime_complete=datetime.datetime(2024, 4, 14, 20, 32, 22, 200613), params={'l1_ratio': 0.11781148032178282}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'l1_ratio': FloatDistribution(high=1.0, log=False, low=0.0001, step=None)}, trial_id=21, value=None)


* Best Score for IBS:
 0.22232569267316699

In [159]:
train_cindex['CoxElastic'] = np.round(study_cindex.best_value, 3)
train_ibs['CoxElastic'] = np.round(study_ibs.best_value, 3)

In [160]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.659
train_ibs:  0.222

#### Test

In [161]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [162]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    return model_class(**best_params, fit_baseline_model=True)

# Set the best model 
best_model_cindex = create_best_model(CoxnetSurvivalAnalysis, 
                                      study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex :", c_index)

# Set the best model 
best_model_ibs = create_best_model(CoxnetSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.7194970228885845)

test_cindex : 0.497

CoxnetSurvivalAnalysis(fit_baseline_model=True, l1_ratio=0.11781148032178282)

test_ibs:  0.288

In [163]:
# Saving the values to the dictionary 
test_cindex['CoxElastic'] = c_index
test_ibs['CoxElastic'] = ibs

### 5. Random Survival Forest

#### Train

In [164]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None])
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics
        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score,
                            warm_start=warm_start,
                            max_depth=max_depth,
                            max_features=max_features,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_samples=max_samples, 
                            random_state=123)

        scores = [] 

        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])
            
            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                cox_surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, cox_surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(RandomSurvivalForest, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(RandomSurvivalForest, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 20:33:15,028] A new study created in memory with name: no-name-aeb9bb76-54d9-440f-b17a-8ed627906103

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6340425531914894
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 20:33:21,432] Trial 0 finished with value: 0.7036219044111919 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122, 'warm_start': False}. Best is trial 0 with value: 0.7036219044111919.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.676595744680851
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 20:33:25,324] Trial 1 finished with value: 0.7031589235757779 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 11, 'n_estimators': 266, 'oob_score': False, 'max_samples': 0.7520097923745717, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11413161543947781, 'warm_start': False}. Best is trial 0 with value: 0.7036219044111919.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6808510638297872
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 20:33:28,225] Trial 2 finished with value: 0.7068386430750734 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 213, 'oob_score': False, 'max_samples': 0.9040502468054213, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15864274091016045, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:33:29,086] Trial 3 finished with value: 0.5 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 11, 'n_estimators': 307, 'oob_score': False, 'max_samples': 0.6427541155698346, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3406503828963983, 'warm_start': True}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:33:30,256] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 14, 'n_estimators': 422, 'oob_score': False, 'max_samples': 0.3192997370831866, 'max_features': None, 'min_weight_fraction_leaf': 0.31362448602563436, 'warm_start': True}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.6851063829787234
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 20:33:34,353] Trial 5 finished with value: 0.6975735052207688 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 4, 'max_depth': 4, 'n_estimators': 348, 'oob_score': False, 'max_samples': 0.5989449247459949, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.021795731899520276, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 20:33:39,344] Trial 6 finished with value: 0.6958948794589715 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 297, 'oob_score': True, 'max_samples': 0.45898866345354095, 'max_features': None, 'min_weight_fraction_leaf': 0.052954242528406914, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:33:42,079] Trial 7 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.2539736462845892, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.26076652969866615, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 20:33:50,706] Trial 8 finished with value: 0.5304721030042918 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 451, 'oob_score': True, 'max_samples': 0.6079231386323035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.30034928391679494, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 20:33:55,030] Trial 9 finished with value: 0.6858969215869519 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 274, 'oob_score': False, 'max_samples': 0.9348258161369327, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.024289516422134394, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:33:55,580] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 2, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 26, 'oob_score': True, 'max_samples': 0.9607577284547746, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.49314452820084254, 'warm_start': True}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 20:33:57,964] Trial 11 finished with value: 0.6922085489417384 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 154, 'oob_score': False, 'max_samples': 0.8009569170593199, 'max_features': None, 'min_weight_fraction_leaf': 0.17782839593648317, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 20:34:00,440] Trial 12 finished with value: 0.6920306178973856 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 119, 'oob_score': False, 'max_samples': 0.7986766477402025, 'max_features': None, 'min_weight_fraction_leaf': 0.1776774219107311, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:34:06,659] Trial 13 finished with value: 0.5 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 381, 'oob_score': False, 'max_samples': 0.10013306718236009, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19432384347385334, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 20:34:08,463] Trial 14 finished with value: 0.7020666473172233 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 1, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.8364130211722378, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.39544239501812417, 'warm_start': True}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.748062015503876
Fold 3 C-index: 0.6297872340425532
Fold 4 C-index: 0.7186311787072244

Fold 5 C-index: 0.6587982832618026
[I 2024-04-14 20:34:10,306] Trial 15 finished with value: 0.6741633120242068 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 79, 'oob_score': False, 'max_samples': 0.9887043893136873, 'max_features': None, 'min_weight_fraction_leaf': 0.11311294291919405, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 20:34:16,945] Trial 16 finished with value: 0.6950964351319479 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 14, 'min_samples_leaf': 14, 'max_depth': 14, 'n_estimators': 475, 'oob_score': False, 'max_samples': 0.6976003666324501, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22594306843997863, 'warm_start': False}. Best is trial 2 with value: 0.7068386430750734.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 20:34:21,279] Trial 17 finished with value: 0.7075143089048166 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 362, 'oob_score': False, 'max_samples': 0.8699768148803853, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13594726716423428, 'warm_start': False}. Best is trial 17 with value: 0.7075143089048166.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 20:34:24,142] Trial 18 finished with value: 0.7291644451037455 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 8, 'n_estimators': 219, 'oob_score': True, 'max_samples': 0.5009018821071551, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.11022349442713597, 'warm_start': True}. Best is trial 18 with value: 0.7291644451037455.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 20:34:28,004] Trial 19 finished with value: 0.7252098564080962 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 417, 'oob_score': True, 'max_samples': 0.47998547229936334, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.08878780346952318, 'warm_start': True}. Best is trial 18 with value: 0.7291644451037455.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6866952789699571
[I 2024-04-14 20:34:32,684] Trial 20 finished with value: 0.7073293865436469 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 3, 'min_samples_leaf': 20, 'max_depth': 2, 'n_estimators': 489, 'oob_score': True, 'max_samples': 0.47910008684664174, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.07173814969549074, 'warm_start': True}. Best is trial 18 with value: 0.7291644451037455.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 20:34:36,805] Trial 21 finished with value: 0.7263247598203011 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 406, 'oob_score': True, 'max_samples': 0.47739226471547075, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10361885312371516, 'warm_start': True}. Best is trial 18 with value: 0.7291644451037455.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7604562737642585
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 20:34:41,628] Trial 22 finished with value: 0.7227252296811468 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 403, 'oob_score': True, 'max_samples': 0.48557150900079615, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0775042481848516, 'warm_start': True}. Best is trial 18 with value: 0.7291644451037455.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 20:34:45,449] Trial 23 finished with value: 0.7099367185612184 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 6, 'min_samples_leaf': 17, 'max_depth': 3, 'n_estimators': 325, 'oob_score': True, 'max_samples': 0.34795502363050157, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.0023497522601186316, 'warm_start': True}. Best is trial 18 with value: 0.7291644451037455.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 20:34:50,017] Trial 24 finished with value: 0.7131817851276706 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 18, 'max_depth': 8, 'n_estimators': 443, 'oob_score': True, 'max_samples': 0.40841210078120815, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.10558953545680927, 'warm_start': True}. Best is trial 18 with value: 0.7291644451037455.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 20:34:52,909] Trial 25 finished with value: 0.7529667588692662 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 241, 'oob_score': True, 'max_samples': 0.5431330979572236, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.06119871518877479, 'warm_start': True}. Best is trial 25 with value: 0.7529667588692662.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8217054263565892
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 20:34:56,157] Trial 26 finished with value: 0.7563284705382939 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 223, 'oob_score': True, 'max_samples': 0.5452005077936769, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.05058696770992366, 'warm_start': True}. Best is trial 26 with value: 0.7563284705382939.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 20:34:59,062] Trial 27 finished with value: 0.7546763187846007 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 245, 'oob_score': True, 'max_samples': 0.55983813128171, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04810535800309272, 'warm_start': True}. Best is trial 26 with value: 0.7563284705382939.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 20:35:01,488] Trial 28 finished with value: 0.758949548973342 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 165, 'oob_score': True, 'max_samples': 0.5637216222196281, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.03325721334872854, 'warm_start': True}. Best is trial 28 with value: 0.758949548973342.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:03,189] Trial 29 finished with value: 0.7732179335818625 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 151, 'oob_score': True, 'max_samples': 0.6812837284737498, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.039340901954407835, 'warm_start': True}. Best is trial 29 with value: 0.7732179335818625.

Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 20:35:05,620] Trial 30 finished with value: 0.7495900956522649 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.6787918855242834, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.010889063772751496, 'warm_start': True}. Best is trial 29 with value: 0.7732179335818625.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:35:07,586] Trial 31 finished with value: 0.7702273294735654 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 154, 'oob_score': True, 'max_samples': 0.6014811453047314, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.042046582248410305, 'warm_start': True}. Best is trial 29 with value: 0.7732179335818625.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:35:08,561] Trial 32 finished with value: 0.7710656947654818 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 3, 'n_estimators': 94, 'oob_score': True, 'max_samples': 0.74233019974597, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.04265159462265889, 'warm_start': True}. Best is trial 29 with value: 0.7732179335818625.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:09,509] Trial 33 finished with value: 0.7774363454256679 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.7344728614720489, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14457282135020835, 'warm_start': True}. Best is trial 33 with value: 0.7774363454256679.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:10,254] Trial 34 finished with value: 0.778287409255455 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 71, 'oob_score': True, 'max_samples': 0.7406298989411106, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1449816702804093, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 20:35:10,876] Trial 35 finished with value: 0.7742231902901672 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 2, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.761377331225515, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13827273942571375, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7965116279069767
Fold 3 C-index: 0.6702127659574468
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.630901287553648
[I 2024-04-14 20:35:11,102] Trial 36 finished with value: 0.7009545517017894 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 5, 'oob_score': True, 'max_samples': 0.7689798515390576, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14126482893229803, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7319148936170212
Fold 4 C-index: 0.7395437262357415
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 20:35:11,725] Trial 37 finished with value: 0.7263513949250882 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.6703763297322496, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23724314354395504, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:35:12,530] Trial 38 finished with value: 0.7735539188506069 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 61, 'oob_score': True, 'max_samples': 0.7239959303280503, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14986317940819743, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:13,437] Trial 39 finished with value: 0.7626471756666506 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 63, 'oob_score': True, 'max_samples': 0.8787895517979668, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2635408988115671, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.6613545816733067
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:35:14,442] Trial 40 finished with value: 0.7729678568511829 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 103, 'oob_score': True, 'max_samples': 0.7250616203236259, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14793955464157124, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7896995708154506
[I 2024-04-14 20:35:15,833] Trial 41 finished with value: 0.754118993429658 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 122, 'oob_score': True, 'max_samples': 0.6575166457839825, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.20041942701751392, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7702127659574468
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:35:16,363] Trial 42 finished with value: 0.7544428335648641 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 43, 'oob_score': True, 'max_samples': 0.7987794198734278, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.162181332836197, 'warm_start': True}. Best is trial 34 with value: 0.778287409255455.
Fold 1 C-index: 0.647410358565737
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8498098859315589
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 20:35:16,679] Trial 43 finished with value: 0.7798346542669913 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 13, 'oob_score': True, 'max_samples': 0.7630755401354222, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12784400974852253, 'warm_start': True}. Best is trial 43 with value: 0.7798346542669913.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.8294573643410853
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7167381974248928
[I 2024-04-14 20:35:16,921] Trial 44 finished with value: 0.7265831106823448 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 2, 'oob_score': True, 'max_samples': 0.7720635119143326, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.13248150189989094, 'warm_start': True}. Best is trial 43 with value: 0.7798346542669913.

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.8193916349809885
Fold 5 C-index: 0.778969957081545
[I 2024-04-14 20:35:17,402] Trial 45 finished with value: 0.7615615255621369 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 2, 'n_estimators': 29, 'oob_score': True, 'max_samples': 0.8296402972759989, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19345584383481748, 'warm_start': True}. Best is trial 43 with value: 0.7798346542669913.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:18,264] Trial 46 finished with value: 0.7765021062956178 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 67, 'oob_score': True, 'max_samples': 0.91240298039898, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17253128451182226, 'warm_start': True}. Best is trial 43 with value: 0.7798346542669913.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:35:19,735] Trial 47 finished with value: 0.7831513176286453 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 4, 'n_estimators': 81, 'oob_score': True, 'max_samples': 0.9157752544220371, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16290732645556993, 'warm_start': True}. Best is trial 47 with value: 0.7831513176286453.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.8255813953488372
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7775665399239544
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 20:35:21,969] Trial 48 finished with value: 0.7672587984529609 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 123, 'oob_score': True, 'max_samples': 0.9276691000256125, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.28029111886508185, 'warm_start': True}. Best is trial 47 with value: 0.7831513176286453.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8041825095057035
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:35:23,075] Trial 49 finished with value: 0.7763265510146573 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 92, 'oob_score': True, 'max_samples': 0.8935535591529834, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21395349861064727, 'warm_start': True}. Best is trial 47 with value: 0.7831513176286453.
Fold 1 C-index: 0.7051792828685259
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:35:23,729] Trial 50 finished with value: 0.790935326899451 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 24, 'oob_score': True, 'max_samples': 0.979549879532744, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1797623059518923, 'warm_start': True}. Best is trial 50 with value: 0.790935326899451.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:24,252] Trial 51 finished with value: 0.7915217299089978 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 20, 'oob_score': True, 'max_samples': 0.9596285313082096, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17386236892173593, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.703187250996016
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.7893617021276595
Fold 4 C-index: 0.8307984790874525
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 20:35:24,833] Trial 52 finished with value: 0.7783950744915984 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 22, 'oob_score': True, 'max_samples': 0.9692415476074083, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21015050951123831, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6792828685258964
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7965779467680608
Fold 5 C-index: 0.7854077253218884
[I 2024-04-14 20:35:25,529] Trial 53 finished with value: 0.7684635052533028 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 23, 'oob_score': True, 'max_samples': 0.9933318562008218, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.24016207650402643, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6952191235059761
Fold 2 C-index: 0.8158914728682171
Fold 3 C-index: 0.7978723404255319
Fold 4 C-index: 0.8155893536121673
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 20:35:26,114] Trial 54 finished with value: 0.7802792649493313 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 21, 'oob_score': True, 'max_samples': 0.9539527484712335, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21351185082667978, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6354581673306773
Fold 2 C-index: 0.8003875968992248
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 20:35:26,548] Trial 55 finished with value: 0.7249710029817216 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 22, 'oob_score': False, 'max_samples': 0.9571150211276048, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3281123512474438, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 20:35:27,743] Trial 56 finished with value: 0.7046622934255112 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 39, 'oob_score': True, 'max_samples': 0.9612257794669835, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.21214208395631484, 'warm_start': False}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.6872340425531915
Fold 4 C-index: 0.7870722433460076
Fold 5 C-index: 0.796137339055794
[I 2024-04-14 20:35:28,072] Trial 57 finished with value: 0.7232662783434801 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 6, 'n_estimators': 3, 'oob_score': True, 'max_samples': 0.8395412319483718, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1852252405610569, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6792828685258964
Fold 2 C-index: 0.7887596899224806
Fold 3 C-index: 0.7936170212765957
Fold 4 C-index: 0.7927756653992395
Fold 5 C-index: 0.7618025751072961
[I 2024-04-14 20:35:28,431] Trial 58 finished with value: 0.7632475640463017 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 22, 'oob_score': False, 'max_samples': 0.9388395452677827, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.22087432195964438, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.6382978723404256
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 20:35:29,481] Trial 59 finished with value: 0.7010293099183056 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 43, 'oob_score': True, 'max_samples': 0.9938087453564204, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2598344055599606, 'warm_start': False}. Best is trial 51 with value: 0.7915217299089978.

Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 20:35:29,829] Trial 60 finished with value: 0.7089196673857986 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 12, 'n_estimators': 11, 'oob_score': True, 'max_samples': 0.8641496222479828, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2884043121771884, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:35:30,730] Trial 61 finished with value: 0.786179947136117 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 76, 'oob_score': True, 'max_samples': 0.8982467438901276, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1701242881902554, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 20:35:31,359] Trial 62 finished with value: 0.7911625395986974 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 45, 'oob_score': True, 'max_samples': 0.9554828175432951, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12330312794274464, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:32,423] Trial 63 finished with value: 0.7812429019693912 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.9093924887101631, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.12311279473668053, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:35:33,789] Trial 64 finished with value: 0.7807614466457861 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 112, 'oob_score': True, 'max_samples': 0.9067348448312373, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16780780062643963, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:35:35,125] Trial 65 finished with value: 0.7756838180171559 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 137, 'oob_score': True, 'max_samples': 0.9107314929960374, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.17511199339419142, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:35:36,188] Trial 66 finished with value: 0.7797697993540946 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 106, 'oob_score': True, 'max_samples': 0.8509384228681494, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.16432428131242963, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:35:36,913] Trial 67 finished with value: 0.7732926993789764 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 86, 'oob_score': False, 'max_samples': 0.9214966809031178, 'max_features': None, 'min_weight_fraction_leaf': 0.08857128553717067, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:38,283] Trial 68 finished with value: 0.7709513022852551 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 10, 'n_estimators': 110, 'oob_score': True, 'max_samples': 0.8175780637532525, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11540263460062322, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:35:41,987] Trial 69 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 171, 'oob_score': True, 'max_samples': 0.20333731221955026, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.3911842602639984, 'warm_start': False}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:43,734] Trial 70 finished with value: 0.7765209920083702 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 12, 'n_estimators': 140, 'oob_score': True, 'max_samples': 0.8905714065935432, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09513332347174282, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6892430278884463
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:35:44,321] Trial 71 finished with value: 0.781257782915173 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 49, 'oob_score': True, 'max_samples': 0.9494253969500845, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1945920365520636, 'warm_start': True}. Best is trial 51 with value: 0.7915217299089978.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 20:35:44,895] Trial 72 finished with value: 0.7936139669312652 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 51, 'oob_score': True, 'max_samples': 0.9775185173829941, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11690390775679341, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:45,638] Trial 73 finished with value: 0.7821657040767105 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 7, 'n_estimators': 50, 'oob_score': True, 'max_samples': 0.9999128827028314, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18715149550150392, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:35:46,350] Trial 74 finished with value: 0.782705982512222 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 52, 'oob_score': True, 'max_samples': 0.9755609710278935, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18400107032610633, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.

Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:35:47,201] Trial 75 finished with value: 0.7826448500055697 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 78, 'oob_score': True, 'max_samples': 0.9980092571657981, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.157692113136589, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:48,087] Trial 76 finished with value: 0.7852379788940855 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 76, 'oob_score': True, 'max_samples': 0.9858130380323064, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15609666877726938, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 20:35:50,221] Trial 77 finished with value: 0.7695332623622895 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 289, 'oob_score': True, 'max_samples': 0.9637225353942439, 'max_features': None, 'min_weight_fraction_leaf': 0.0738266438606778, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6932270916334662
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:35:50,687] Trial 78 finished with value: 0.7803746377850479 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 34, 'oob_score': True, 'max_samples': 0.9729367715405993, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11682454352483734, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6852589641434262
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7908745247148289
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:35:51,424] Trial 79 finished with value: 0.7724844895275984 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 15, 'n_estimators': 181, 'oob_score': False, 'max_samples': 0.8688878496656431, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.234128578743793, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7854077253218884
[I 2024-04-14 20:35:51,923] Trial 80 finished with value: 0.7778200313454212 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 54, 'oob_score': True, 'max_samples': 0.9307218907380278, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09952623622408474, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6733067729083665
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:52,554] Trial 81 finished with value: 0.7852379788940855 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 76, 'oob_score': True, 'max_samples': 0.9786688910767736, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15357305736350996, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8307984790874525
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:35:53,197] Trial 82 finished with value: 0.779226377697545 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 72, 'oob_score': True, 'max_samples': 0.9762880520434982, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.18128528275351716, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:53,970] Trial 83 finished with value: 0.7828369513104552 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 85, 'oob_score': True, 'max_samples': 0.9411285339202718, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15422578898480016, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:35:54,698] Trial 84 finished with value: 0.7787230368612458 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 8, 'n_estimators': 86, 'oob_score': True, 'max_samples': 0.9382020434517306, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15445383821345005, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:55,721] Trial 85 finished with value: 0.7788387173049027 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 133, 'oob_score': True, 'max_samples': 0.893339032662877, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12461252878963344, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6812749003984063
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.8155893536121673
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:35:56,482] Trial 86 finished with value: 0.7801326837153243 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 94, 'oob_score': True, 'max_samples': 0.9367602078059545, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1390417640267184, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.6468085106382979
Fold 4 C-index: 0.7338403041825095
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 20:35:57,692] Trial 87 finished with value: 0.6984712318359876 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 17, 'n_estimators': 68, 'oob_score': True, 'max_samples': 0.884780434623403, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.08501632309340894, 'warm_start': False}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:35:58,082] Trial 88 finished with value: 0.5 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 10, 'n_estimators': 34, 'oob_score': True, 'max_samples': 0.8602160291919352, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4978507265200673, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6872509960159362
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7746781115879828
[I 2024-04-14 20:35:58,882] Trial 89 finished with value: 0.7781162351936948 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 81, 'oob_score': True, 'max_samples': 0.9772677337361966, 'max_features': None, 'min_weight_fraction_leaf': 0.20309848905443503, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.

Fold 1 C-index: 0.6772908366533864
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7914893617021277
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:35:59,460] Trial 90 finished with value: 0.7796278009419253 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 61, 'oob_score': True, 'max_samples': 0.9468724904454058, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.06416732648048804, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6972111553784861
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:36:00,115] Trial 91 finished with value: 0.7851718669475154 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 58, 'oob_score': True, 'max_samples': 0.9810694920945782, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15470502034568753, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6653386454183267
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:36:01,254] Trial 92 finished with value: 0.7785992299108413 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 98, 'oob_score': True, 'max_samples': 0.9160182057519459, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15309978450271344, 'warm_start': True}. Best is trial 72 with value: 0.7936139669312652.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 20:36:01,728] Trial 93 finished with value: 0.7937512498912148 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 42, 'oob_score': True, 'max_samples': 0.9543328663786653, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13277612565065217, 'warm_start': True}. Best is trial 93 with value: 0.7937512498912148.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 20:36:02,158] Trial 94 finished with value: 0.794469035528023 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 31, 'oob_score': True, 'max_samples': 0.9992983663237085, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10521130470858149, 'warm_start': True}. Best is trial 94 with value: 0.794469035528023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8669201520912547
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 20:36:02,596] Trial 95 finished with value: 0.7889341603430476 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 38, 'oob_score': True, 'max_samples': 0.9841472616569411, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.11141828951067143, 'warm_start': True}. Best is trial 94 with value: 0.794469035528023.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8574144486692015
Fold 5 C-index: 0.7918454935622318
[I 2024-04-14 20:36:02,860] Trial 96 finished with value: 0.7778397766962228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 20, 'n_estimators': 12, 'oob_score': True, 'max_samples': 0.997250770261379, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.10952777319036597, 'warm_start': True}. Best is trial 94 with value: 0.794469035528023.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 20:36:03,256] Trial 97 finished with value: 0.7847377912928529 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 19, 'n_estimators': 31, 'oob_score': True, 'max_samples': 0.973750709701587, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.13160173504227984, 'warm_start': True}. Best is trial 94 with value: 0.794469035528023.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.870722433460076
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 20:36:03,658] Trial 98 finished with value: 0.7945264436896644 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 40, 'oob_score': True, 'max_samples': 0.9538061740605386, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09899137909936344, 'warm_start': True}. Best is trial 98 with value: 0.7945264436896644.

[I 2024-04-14 20:36:03,974] A new study created in memory with name: no-name-902f012d-bc64-4310-ae34-16f0eb34b158

Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8042553191489362
Fold 4 C-index: 0.8745247148288974
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:36:03,960] Trial 99 finished with value: 0.7858198098725093 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 36, 'oob_score': False, 'max_samples': 0.9532701744144001, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09366006466735621, 'warm_start': True}. Best is trial 98 with value: 0.7945264436896644.


* Best trial for C-index:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.7945264436896644], datetime_start=datetime.datetime(2024, 4, 14, 20, 36, 3, 262944), datetime_complete=datetime.datetime(2024, 4, 14, 20, 36, 3, 657394), params={'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 11, 'max_depth': 19, 'n_estimators': 40, 'oob_score': True, 'max_samples': 0.9538061740605386, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09899137909936344, 'warm_start': True}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'warm_start': CategoricalDistribution(choices=(True, False))}, trial_id=98, value=None)


* Best Score for C-index:
 0.7945264436896644

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.21215241225326156
Fold 2 IBS: 0.18409767804301072
Fold 3 IBS: 0.24190050119403034
Fold 4 IBS: 0.21204333266214517
Fold 5 IBS: 0.21714215604592058
[I 2024-04-14 20:36:09,157] Trial 0 finished with value: 0.2134672160396737 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'max_samples': 0.7163467647263769, 'max_features': None, 'min_weight_fraction_leaf': 0.2192861223398122}. Best is trial 0 with value: 0.2134672160396737.
Fold 1 IBS: 0.21851164392345074
Fold 2 IBS: 0.18848503206973014
Fold 3 IBS: 0.22004978995083413
Fold 4 IBS: 0.205226469797756
Fold 5 IBS: 0.2100249738740771
[I 2024-04-14 20:36:10,615] Trial 1 finished with value: 0.20845958192316966 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 88, 'oob_score': False, 'max_samples': 0.6709608626961889, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1614794569265891}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.24615948084702247
Fold 2 IBS: 0.23204036144990578
Fold 3 IBS: 0.23015604135045867
Fold 4 IBS: 0.24151534293445684
Fold 5 IBS: 0.2300353202999985
[I 2024-04-14 20:36:11,607] Trial 2 finished with value: 0.23598130937636846 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 13, 'n_estimators': 47, 'oob_score': True, 'max_samples': 0.5443165878852756, 'max_features': None, 'min_weight_fraction_leaf': 0.4720800091019398}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.2467945458591145
Fold 2 IBS: 0.23221438596874516
Fold 3 IBS: 0.22941705607619028
Fold 4 IBS: 0.2414946976297431
Fold 5 IBS: 0.23030304845596666
[I 2024-04-14 20:36:15,609] Trial 3 finished with value: 0.23604474679795193 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 208, 'oob_score': True, 'max_samples': 0.5347308378364339, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.4131704002534166}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.24670918544928236
Fold 2 IBS: 0.23217012825540695
Fold 3 IBS: 0.22938012235849098
Fold 4 IBS: 0.24150360266800044
Fold 5 IBS: 0.23024325402729912
[I 2024-04-14 20:36:18,268] Trial 4 finished with value: 0.23600125855169596 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 209, 'oob_score': False, 'max_samples': 0.5593801037302101, 'max_features': None, 'min_weight_fraction_leaf': 0.42117121881012864}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.23612794634887901
Fold 2 IBS: 0.19782198345568366
Fold 3 IBS: 0.21196755824728333
Fold 4 IBS: 0.20130076848177703
Fold 5 IBS: 0.2070472005938211
[I 2024-04-14 20:36:22,477] Trial 5 finished with value: 0.21085309142548883 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 16, 'min_samples_leaf': 5, 'max_depth': 4, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.6645240748461418, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.07947982207236137}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.21212092728693907
Fold 2 IBS: 0.19520741280503734
Fold 3 IBS: 0.2539054626067449
Fold 4 IBS: 0.20737086108742184
Fold 5 IBS: 0.2181533165919949
[I 2024-04-14 20:36:26,307] Trial 6 finished with value: 0.2173515960756276 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 278, 'oob_score': False, 'max_samples': 0.8575029972214446, 'max_features': None, 'min_weight_fraction_leaf': 0.3524794152256811}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.2428595745310512
Fold 2 IBS: 0.2263245223248669
Fold 3 IBS: 0.22746428490756698
Fold 4 IBS: 0.23754320428942544
Fold 5 IBS: 0.22525871145615697
[I 2024-04-14 20:36:30,310] Trial 7 finished with value: 0.2318900595018135 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 12, 'n_estimators': 346, 'oob_score': False, 'max_samples': 0.31677030795126204, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.06544747533204037}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.24622543464122137
Fold 2 IBS: 0.2322702305189305
Fold 3 IBS: 0.22971004301620757
Fold 4 IBS: 0.24149565944557436
Fold 5 IBS: 0.23037394718674215
[I 2024-04-14 20:36:37,919] Trial 8 finished with value: 0.2360150629617352 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 12, 'n_estimators': 428, 'oob_score': True, 'max_samples': 0.4188382080325107, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.2892757340544165}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.22338966924645126
Fold 2 IBS: 0.18658719196223053
Fold 3 IBS: 0.2090309288036935
Fold 4 IBS: 0.21978291849837772
Fold 5 IBS: 0.21645574656603708
[I 2024-04-14 20:36:39,856] Trial 9 finished with value: 0.21104929101535802 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 2, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 104, 'oob_score': False, 'max_samples': 0.9117202353946035, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1971850269763874}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.246587342303552
Fold 2 IBS: 0.23212002973319837
Fold 3 IBS: 0.22961274657990574
Fold 4 IBS: 0.2413253549165465
Fold 5 IBS: 0.22920684798460136
[I 2024-04-14 20:36:42,307] Trial 10 finished with value: 0.2357704643035608 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 124, 'oob_score': True, 'max_samples': 0.10345432981037916, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.14486946907363749}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.20395160101780602
Fold 2 IBS: 0.19736204899694285
Fold 3 IBS: 0.2261855898177037
Fold 4 IBS: 0.2257880305518168
Fold 5 IBS: 0.19241927294002883
[I 2024-04-14 20:36:42,572] Trial 11 finished with value: 0.20914130866485964 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 11, 'max_depth': 1, 'n_estimators': 2, 'oob_score': False, 'max_samples': 0.7351810575897255, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.008231293935378081}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.23735476077098713
Fold 2 IBS: 0.19736034731394847
Fold 3 IBS: 0.20071622676038342
Fold 4 IBS: 0.21906402198610014
Fold 5 IBS: 0.21723255300779426
[I 2024-04-14 20:36:43,054] Trial 12 finished with value: 0.21434558196784273 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 1, 'n_estimators': 13, 'oob_score': False, 'max_samples': 0.7748822387405266, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0020197386275102834}. Best is trial 1 with value: 0.20845958192316966.
Fold 1 IBS: 0.22531108658680918
Fold 2 IBS: 0.18310962653683216
Fold 3 IBS: 0.20941073848698272
Fold 4 IBS: 0.20617236799229396
Fold 5 IBS: 0.20655705905571028
[I 2024-04-14 20:36:44,900] Trial 13 finished with value: 0.20611217573172563 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 110, 'oob_score': False, 'max_samples': 0.9282504676473301, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.0035697594234744834}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22573650859993868
Fold 2 IBS: 0.18536891226270694
Fold 3 IBS: 0.20751639397676247
Fold 4 IBS: 0.20829655530843277
Fold 5 IBS: 0.2060160313395714
[I 2024-04-14 20:36:47,597] Trial 14 finished with value: 0.20658688029748246 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 136, 'oob_score': False, 'max_samples': 0.9261960986621366, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12298316396935675}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22869040830741852
Fold 2 IBS: 0.18777351086640942
Fold 3 IBS: 0.21236708262582468
Fold 4 IBS: 0.20646353127738326
Fold 5 IBS: 0.20763917038543853
[I 2024-04-14 20:36:50,666] Trial 15 finished with value: 0.2085867406924949 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 8, 'n_estimators': 169, 'oob_score': False, 'max_samples': 0.9955118327783237, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09530675807505407}. Best is trial 13 with value: 0.20611217573172563.

Fold 1 IBS: 0.22149169826882395
Fold 2 IBS: 0.18787500296196655
Fold 3 IBS: 0.21683093655826374
Fold 4 IBS: 0.21074191060382028
Fold 5 IBS: 0.21169020922678142
[I 2024-04-14 20:36:52,666] Trial 16 finished with value: 0.2097259515239312 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 4, 'min_samples_leaf': 19, 'max_depth': 9, 'n_estimators': 149, 'oob_score': False, 'max_samples': 0.9684217810899436, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2726613219471218}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2313709263488008
Fold 2 IBS: 0.18921820974814835
Fold 3 IBS: 0.20840824975820502
Fold 4 IBS: 0.20557612235234599
Fold 5 IBS: 0.2074366568213961
[I 2024-04-14 20:37:00,036] Trial 17 finished with value: 0.20840203300577925 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 10, 'min_samples_leaf': 9, 'max_depth': 4, 'n_estimators': 494, 'oob_score': False, 'max_samples': 0.8368873118701377, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12082984897570387}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22030418722333822
Fold 2 IBS: 0.18045008143432864
Fold 3 IBS: 0.21811332365667777
Fold 4 IBS: 0.20630474973597052
Fold 5 IBS: 0.21227541906669753
[I 2024-04-14 20:37:01,515] Trial 18 finished with value: 0.20748955222340254 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 5, 'min_samples_leaf': 14, 'max_depth': 16, 'n_estimators': 59, 'oob_score': True, 'max_samples': 0.845128931910435, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.04006629526218301}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2216219291947606
Fold 2 IBS: 0.1855657276358531
Fold 3 IBS: 0.21285643003916604
Fold 4 IBS: 0.20980257202455146
Fold 5 IBS: 0.20596690157633488
[I 2024-04-14 20:37:05,252] Trial 19 finished with value: 0.2071627120941332 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 201, 'oob_score': False, 'max_samples': 0.9184228807683538, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.18135871852297286}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22707781542098432
Fold 2 IBS: 0.19858489450071762
Fold 3 IBS: 0.21063375891880362
Fold 4 IBS: 0.2115727330748602
Fold 5 IBS: 0.20424308889122253
[I 2024-04-14 20:37:09,002] Trial 20 finished with value: 0.21042245816131766 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 17, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.23419761201309758, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.046571021973888765}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22116415223757432
Fold 2 IBS: 0.18613906174002123
Fold 3 IBS: 0.21254808974986347
Fold 4 IBS: 0.209022111855855
Fold 5 IBS: 0.20556978095759143
[I 2024-04-14 20:37:12,121] Trial 21 finished with value: 0.20688863930818108 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 193, 'oob_score': False, 'max_samples': 0.9081877090178846, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1777372518975414}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22147903541799221
Fold 2 IBS: 0.19255454619594375
Fold 3 IBS: 0.2162592807214069
Fold 4 IBS: 0.21420589037077378
Fold 5 IBS: 0.21393173189540268
[I 2024-04-14 20:37:14,306] Trial 22 finished with value: 0.21168609692030388 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 18, 'max_depth': 6, 'n_estimators': 138, 'oob_score': False, 'max_samples': 0.7917839025119462, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.24537412490296323}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22898186741709603
Fold 2 IBS: 0.18560269367572454
Fold 3 IBS: 0.21244008853368096
Fold 4 IBS: 0.20549243428607072
Fold 5 IBS: 0.20696098493838766
[I 2024-04-14 20:37:17,556] Trial 23 finished with value: 0.207895613770192 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 3, 'n_estimators': 194, 'oob_score': False, 'max_samples': 0.9980455570845468, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.1193442431038026}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22365315919432138
Fold 2 IBS: 0.19832093557709848
Fold 3 IBS: 0.22013906219197438
Fold 4 IBS: 0.21511901665698904
Fold 5 IBS: 0.2180785189697422
[I 2024-04-14 20:37:18,941] Trial 24 finished with value: 0.21506213851802508 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 9, 'n_estimators': 89, 'oob_score': False, 'max_samples': 0.914215824364654, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3313249823430483}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22125658439403875
Fold 2 IBS: 0.19316006076597203
Fold 3 IBS: 0.21816317616508993
Fold 4 IBS: 0.21431070573666822
Fold 5 IBS: 0.21168711327209433
[I 2024-04-14 20:37:21,513] Trial 25 finished with value: 0.21171552806677268 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 163, 'oob_score': False, 'max_samples': 0.6219587265298226, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.12582755140264107}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22194205592390587
Fold 2 IBS: 0.1895654214830179
Fold 3 IBS: 0.216399899765147
Fold 4 IBS: 0.2088110726807596
Fold 5 IBS: 0.20958718502565915
[I 2024-04-14 20:37:22,548] Trial 26 finished with value: 0.20926112697569788 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 18, 'max_depth': 3, 'n_estimators': 55, 'oob_score': True, 'max_samples': 0.8764903164466223, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.2252306192135859}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.21925039289077666
Fold 2 IBS: 0.18620358688764588
Fold 3 IBS: 0.21240632205914436
Fold 4 IBS: 0.206432786696269
Fold 5 IBS: 0.2077566051352172
[I 2024-04-14 20:37:25,639] Trial 27 finished with value: 0.2064099387338106 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 8, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.7839419332056478, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18184651180637382}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.23219704571031427
Fold 2 IBS: 0.19268823133725893
Fold 3 IBS: 0.21124179396269196
Fold 4 IBS: 0.2065187974789508
Fold 5 IBS: 0.204564579035604
[I 2024-04-14 20:37:29,155] Trial 28 finished with value: 0.209442089504964 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 242, 'oob_score': False, 'max_samples': 0.8018034650264397, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10128126748121037}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2319869509362431
Fold 2 IBS: 0.19256197225729427
Fold 3 IBS: 0.21383761936827675
Fold 4 IBS: 0.20388694603659235
Fold 5 IBS: 0.20570862716129
[I 2024-04-14 20:37:33,649] Trial 29 finished with value: 0.2095964231519393 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 318, 'oob_score': False, 'max_samples': 0.7146887630319405, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.03298315127292836}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.21865201042157198
Fold 2 IBS: 0.18745422344662324
Fold 3 IBS: 0.214107093517385
Fold 4 IBS: 0.2088439339084661
Fold 5 IBS: 0.20871430869146615
[I 2024-04-14 20:37:38,783] Trial 30 finished with value: 0.2075543139971025 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 15, 'n_estimators': 388, 'oob_score': False, 'max_samples': 0.7366412690089136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2058998772588138}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22784674793984191
Fold 2 IBS: 0.1861075598435993
Fold 3 IBS: 0.21070633584988824
Fold 4 IBS: 0.20294630295234484

Fold 5 IBS: 0.20628342384593995
[I 2024-04-14 20:37:42,048] Trial 31 finished with value: 0.20677807408632284 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.9378460826208653, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1726892235544012}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22725825690793014
Fold 2 IBS: 0.18682969848680658
Fold 3 IBS: 0.21075711994523577
Fold 4 IBS: 0.20108520766951074
Fold 5 IBS: 0.20700698808236373
[I 2024-04-14 20:37:45,210] Trial 32 finished with value: 0.20658745421836944 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 253, 'oob_score': False, 'max_samples': 0.9502203520505428, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14645952871104895}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2255625199718266
Fold 2 IBS: 0.1850328902002003
Fold 3 IBS: 0.21213386226179334
Fold 4 IBS: 0.20442315497963176
Fold 5 IBS: 0.20599433296630212
[I 2024-04-14 20:37:50,658] Trial 33 finished with value: 0.20662935207595085 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 316, 'oob_score': False, 'max_samples': 0.9594385658956323, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1495769551504098}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.221252763677962
Fold 2 IBS: 0.18535468699011443
Fold 3 IBS: 0.21666081887766672
Fold 4 IBS: 0.2050965332555971
Fold 5 IBS: 0.2120311916570352
[I 2024-04-14 20:37:52,352] Trial 34 finished with value: 0.2080791988916751 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 10, 'max_depth': 7, 'n_estimators': 107, 'oob_score': False, 'max_samples': 0.8208895005295127, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22706059375124985}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.25658071291699575
Fold 2 IBS: 0.1946391531267193
Fold 3 IBS: 0.237204584832927
Fold 4 IBS: 0.21302742320434703
Fold 5 IBS: 0.2073052916039873
[I 2024-04-14 20:37:57,909] Trial 35 finished with value: 0.22175143313699527 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 11, 'max_depth': 9, 'n_estimators': 230, 'oob_score': True, 'max_samples': 0.8795203828065719, 'max_features': None, 'min_weight_fraction_leaf': 0.07863413232841465}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.21861926963361053
Fold 2 IBS: 0.18799882145716776
Fold 3 IBS: 0.2163443910920235
Fold 4 IBS: 0.2080214454604155
Fold 5 IBS: 0.20879295304799536
[I 2024-04-14 20:38:01,811] Trial 36 finished with value: 0.20795537613824253 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 5, 'n_estimators': 280, 'oob_score': False, 'max_samples': 0.6691238793351656, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.15801657467541547}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.23705525554120105
Fold 2 IBS: 0.2130002389001053
Fold 3 IBS: 0.22919711117145442
Fold 4 IBS: 0.22903692662897812
Fold 5 IBS: 0.2218054238562891
[I 2024-04-14 20:38:04,259] Trial 37 finished with value: 0.22601899121960561 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 13, 'max_depth': 3, 'n_estimators': 160, 'oob_score': False, 'max_samples': 0.6134779412492984, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28761401546402915}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.24488981176413607
Fold 2 IBS: 0.18776043791779448
Fold 3 IBS: 0.21918639063582318
Fold 4 IBS: 0.21545851914762648
Fold 5 IBS: 0.21379954054395417
[I 2024-04-14 20:38:05,784] Trial 38 finished with value: 0.2162189400018669 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 9, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.47409956893526933, 'max_features': None, 'min_weight_fraction_leaf': 0.06954583140857257}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2288820950754597
Fold 2 IBS: 0.21192288664095474
Fold 3 IBS: 0.2278004907164647
Fold 4 IBS: 0.22281691325557346
Fold 5 IBS: 0.2211943810397589
[I 2024-04-14 20:38:06,918] Trial 39 finished with value: 0.22252335334564233 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 13, 'n_estimators': 34, 'oob_score': True, 'max_samples': 0.7530003871120627, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.33228094235869554}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22001802102309784
Fold 2 IBS: 0.18805880502636083
Fold 3 IBS: 0.21772360159397441
Fold 4 IBS: 0.21039653383630222
Fold 5 IBS: 0.21046441915218986
[I 2024-04-14 20:38:12,506] Trial 40 finished with value: 0.20933227612638503 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 7, 'n_estimators': 366, 'oob_score': False, 'max_samples': 0.8788973461571579, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.25453881174352616}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2261494593554057
Fold 2 IBS: 0.1849212865910554
Fold 3 IBS: 0.21222892537983723
Fold 4 IBS: 0.20430348735971982
Fold 5 IBS: 0.20633390818236802
[I 2024-04-14 20:38:17,442] Trial 41 finished with value: 0.20678741337367726 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 324, 'oob_score': False, 'max_samples': 0.9481341331226376, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13840629546601674}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22745770766979795
Fold 2 IBS: 0.18601753146071465
Fold 3 IBS: 0.21193293939360064
Fold 4 IBS: 0.202534127564711
Fold 5 IBS: 0.2065744606724508
[I 2024-04-14 20:38:21,672] Trial 42 finished with value: 0.20690335335225502 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 5, 'n_estimators': 310, 'oob_score': False, 'max_samples': 0.9699572745459105, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15483903789073183}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2465020177976395
Fold 2 IBS: 0.2321428033292768
Fold 3 IBS: 0.22952650556746884
Fold 4 IBS: 0.24158590335667451
Fold 5 IBS: 0.23031194646803946
[I 2024-04-14 20:38:25,195] Trial 43 finished with value: 0.23601383530381984 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 297, 'oob_score': False, 'max_samples': 0.9502091234623028, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.48555369660230846}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2230914623380629
Fold 2 IBS: 0.1867186205789475
Fold 3 IBS: 0.21255089942479796
Fold 4 IBS: 0.20463131265466772
Fold 5 IBS: 0.2072932142112165
[I 2024-04-14 20:38:29,407] Trial 44 finished with value: 0.20685710184153852 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 16, 'max_depth': 7, 'n_estimators': 261, 'oob_score': False, 'max_samples': 0.9984437840240007, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19977994671892627}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.23656498776650484
Fold 2 IBS: 0.1887790703425684
Fold 3 IBS: 0.20543931564588722
Fold 4 IBS: 0.2194223928393851
Fold 5 IBS: 0.2170399181630002
[I 2024-04-14 20:38:32,738] Trial 45 finished with value: 0.2134491369514692 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 221, 'oob_score': False, 'max_samples': 0.8735053833802129, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.09808268360541557}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.24048492245584271
Fold 2 IBS: 0.1883553674944325
Fold 3 IBS: 0.23604782050948678
Fold 4 IBS: 0.21545599237527344
Fold 5 IBS: 0.21187987353104062
[I 2024-04-14 20:38:39,614] Trial 46 finished with value: 0.21844479527321523 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 20, 'n_estimators': 406, 'oob_score': False, 'max_samples': 0.8094239987096877, 'max_features': None, 'min_weight_fraction_leaf': 0.02436275652658372}. Best is trial 13 with value: 0.20611217573172563.

Fold 1 IBS: 0.21901722906427928
Fold 2 IBS: 0.1880121546737221
Fold 3 IBS: 0.2143915775970178
Fold 4 IBS: 0.20859975309235104
Fold 5 IBS: 0.21293055714902465
[I 2024-04-14 20:38:41,551] Trial 47 finished with value: 0.20859025431527894 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 10, 'n_estimators': 121, 'oob_score': True, 'max_samples': 0.7066230764403721, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.05497537161420828}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.24646474217837117
Fold 2 IBS: 0.2321704166482232
Fold 3 IBS: 0.22960401808871153
Fold 4 IBS: 0.24144503779242357
Fold 5 IBS: 0.23032179092673608
[I 2024-04-14 20:38:45,418] Trial 48 finished with value: 0.2360012011268931 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 6, 'max_depth': 4, 'n_estimators': 334, 'oob_score': False, 'max_samples': 0.8517947741571208, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.44962767788541247}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22777134919367417
Fold 2 IBS: 0.18994053730851976
Fold 3 IBS: 0.21088687411466062
Fold 4 IBS: 0.2027963554533835
Fold 5 IBS: 0.20668603074851633
[I 2024-04-14 20:38:49,111] Trial 49 finished with value: 0.2076162293637509 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 6, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 271, 'oob_score': False, 'max_samples': 0.902814523124901, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.11745180128599542}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.23381808328548517
Fold 2 IBS: 0.19082462515820714
Fold 3 IBS: 0.2107793810042227
Fold 4 IBS: 0.20322776722404784
Fold 5 IBS: 0.20734269626898874
[I 2024-04-14 20:38:51,560] Trial 50 finished with value: 0.20919851058819033 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 177, 'oob_score': False, 'max_samples': 0.9507816500316651, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.14147922592542847}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22598399265326405
Fold 2 IBS: 0.18753028637143293
Fold 3 IBS: 0.21125214170666543
Fold 4 IBS: 0.2042490852116011
Fold 5 IBS: 0.20525521089226442
[I 2024-04-14 20:38:54,638] Trial 51 finished with value: 0.20685414336704558 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 233, 'oob_score': False, 'max_samples': 0.9283985344372893, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1809827484496479}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22698687028032297
Fold 2 IBS: 0.18614159713033168
Fold 3 IBS: 0.21121819551592255
Fold 4 IBS: 0.20339975705136795
Fold 5 IBS: 0.20620485653593063
[I 2024-04-14 20:38:59,720] Trial 52 finished with value: 0.20679025530277517 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 352, 'oob_score': False, 'max_samples': 0.968775053697743, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1670119257153816}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22621811113864407
Fold 2 IBS: 0.1851649981271061
Fold 3 IBS: 0.20941292057620317
Fold 4 IBS: 0.2067621386840925
Fold 5 IBS: 0.20587696510179973
[I 2024-04-14 20:39:02,762] Trial 53 finished with value: 0.2066870267255691 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 216, 'oob_score': False, 'max_samples': 0.9280503629351077, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1940281050468535}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22059420238105204
Fold 2 IBS: 0.18427045825373084
Fold 3 IBS: 0.2144368815175032
Fold 4 IBS: 0.21081684608247453
Fold 5 IBS: 0.2079135684183107
[I 2024-04-14 20:39:06,660] Trial 54 finished with value: 0.20760639133061426 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 5, 'n_estimators': 214, 'oob_score': False, 'max_samples': 0.8377142585048136, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21100040118614916}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.21740233411194793
Fold 2 IBS: 0.18617257426603984
Fold 3 IBS: 0.21671386395713052
Fold 4 IBS: 0.2083956049309622
Fold 5 IBS: 0.2088951020993046
[I 2024-04-14 20:39:10,705] Trial 55 finished with value: 0.207515895873077 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 7, 'n_estimators': 296, 'oob_score': False, 'max_samples': 0.8923015979208301, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24911720637368157}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.24657253011729516
Fold 2 IBS: 0.2322870086765847
Fold 3 IBS: 0.2297213750702068
Fold 4 IBS: 0.2410363854572732
Fold 5 IBS: 0.2303270441979931
[I 2024-04-14 20:39:13,105] Trial 56 finished with value: 0.23598886870387056 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 11, 'min_samples_leaf': 14, 'max_depth': 9, 'n_estimators': 182, 'oob_score': False, 'max_samples': 0.30024289793570863, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.19139649808737833}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22310495268835936
Fold 2 IBS: 0.18652696389397908
Fold 3 IBS: 0.2122993587715239
Fold 4 IBS: 0.20834152025768285
Fold 5 IBS: 0.20834380728438665
[I 2024-04-14 20:39:15,457] Trial 57 finished with value: 0.20772332057918635 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 142, 'oob_score': False, 'max_samples': 0.9671960981203778, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.09083222295177434}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.21212014438962612
Fold 2 IBS: 0.18237092488325604
Fold 3 IBS: 0.2384022009178139
Fold 4 IBS: 0.2165694673555757
Fold 5 IBS: 0.2145061315706852
[I 2024-04-14 20:39:17,883] Trial 58 finished with value: 0.21279377382339137 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 11, 'n_estimators': 83, 'oob_score': True, 'max_samples': 0.7624364325486322, 'max_features': None, 'min_weight_fraction_leaf': 0.22802374280520338}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22384175844162507
Fold 2 IBS: 0.18477077651458546
Fold 3 IBS: 0.21311259440192992
Fold 4 IBS: 0.2105704371787589
Fold 5 IBS: 0.20989115718034665
[I 2024-04-14 20:39:20,444] Trial 59 finished with value: 0.2084373447434492 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 10, 'n_estimators': 128, 'oob_score': False, 'max_samples': 0.9985288329370337, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13434431011584091}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22918225797173647
Fold 2 IBS: 0.18374278460279475
Fold 3 IBS: 0.20788160851870316
Fold 4 IBS: 0.20716730944621214
Fold 5 IBS: 0.20750117626977935
[I 2024-04-14 20:39:24,391] Trial 60 finished with value: 0.20709502736184518 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2, 'n_estimators': 264, 'oob_score': False, 'max_samples': 0.9181478641882094, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.1134706261804552}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2264562988114501
Fold 2 IBS: 0.1860356340492797
Fold 3 IBS: 0.21062293075638186
Fold 4 IBS: 0.2065186781561469
Fold 5 IBS: 0.20559841437198567
[I 2024-04-14 20:39:27,136] Trial 61 finished with value: 0.20704639122904886 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 8, 'n_estimators': 205, 'oob_score': False, 'max_samples': 0.9490957201712591, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.17056783417027024}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22532348850314807
Fold 2 IBS: 0.18677967198934503
Fold 3 IBS: 0.21110497094205702
Fold 4 IBS: 0.20311699778623016

Fold 5 IBS: 0.20613396395481967
[I 2024-04-14 20:39:30,244] Trial 62 finished with value: 0.20649181863511998 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 241, 'oob_score': False, 'max_samples': 0.9254593391142755, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18664631824303496}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.21846829565911444
Fold 2 IBS: 0.18601729779341092
Fold 3 IBS: 0.21422746242483537
Fold 4 IBS: 0.20884474697455188
Fold 5 IBS: 0.20749656516108242
[I 2024-04-14 20:39:33,422] Trial 63 finished with value: 0.207010873602599 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 17, 'max_depth': 7, 'n_estimators': 246, 'oob_score': False, 'max_samples': 0.8562041421528351, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.15233334363188203}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22160509975134576
Fold 2 IBS: 0.1841648311046447
Fold 3 IBS: 0.21112481286142043
Fold 4 IBS: 0.20804353689724292
Fold 5 IBS: 0.20850114300866884
[I 2024-04-14 20:39:39,479] Trial 64 finished with value: 0.20668788472466454 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 11, 'max_depth': 12, 'n_estimators': 468, 'oob_score': False, 'max_samples': 0.7913384263329108, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.19252488503563916}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22758351530116114
Fold 2 IBS: 0.18977778058461667
Fold 3 IBS: 0.21211068956759802
Fold 4 IBS: 0.20276282807515922
Fold 5 IBS: 0.20725262005408893
[I 2024-04-14 20:39:43,399] Trial 65 finished with value: 0.20789748671652478 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 11, 'min_samples_leaf': 12, 'max_depth': 9, 'n_estimators': 287, 'oob_score': False, 'max_samples': 0.9020286671569347, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.014501927197572428}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2204167159009019
Fold 2 IBS: 0.18604636733922902
Fold 3 IBS: 0.2168905748595137
Fold 4 IBS: 0.20916026710652408
Fold 5 IBS: 0.21218267682687908
[I 2024-04-14 20:39:45,811] Trial 66 finished with value: 0.20893932040660954 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 111, 'oob_score': False, 'max_samples': 0.8331361078238348, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23796732415300764}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22174244591191963
Fold 2 IBS: 0.18654520998484017
Fold 3 IBS: 0.21511431340034542
Fold 4 IBS: 0.20824159589809854
Fold 5 IBS: 0.2088728702989168
[I 2024-04-14 20:39:48,553] Trial 67 finished with value: 0.2081032870988241 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 189, 'oob_score': False, 'max_samples': 0.934523070246248, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.265575195627134}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22261734702905836
Fold 2 IBS: 0.18593987419170496
Fold 3 IBS: 0.2088729702041733
Fold 4 IBS: 0.20732041799964945
Fold 5 IBS: 0.2083020807480902
[I 2024-04-14 20:39:50,801] Trial 68 finished with value: 0.20661053803453525 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 8, 'max_depth': 17, 'n_estimators': 155, 'oob_score': False, 'max_samples': 0.9715749471828077, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21021049337651831}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.2284497411946725
Fold 2 IBS: 0.20184771174427388
Fold 3 IBS: 0.21964291600952335
Fold 4 IBS: 0.2201514998279862
Fold 5 IBS: 0.21720440237942773
[I 2024-04-14 20:39:53,383] Trial 69 finished with value: 0.21745925423117676 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 8, 'max_depth': 16, 'n_estimators': 158, 'oob_score': True, 'max_samples': 0.9722126104010237, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.37507273812997705}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.23295945443715635
Fold 2 IBS: 0.20932648770586024
Fold 3 IBS: 0.2255274261549631
Fold 4 IBS: 0.22475149853155854
Fold 5 IBS: 0.217902508637539
[I 2024-04-14 20:39:59,231] Trial 70 finished with value: 0.22209347509341543 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 18, 'n_estimators': 365, 'oob_score': False, 'max_samples': 0.4878565997867668, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.21448995811780644}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.22952690361306918
Fold 2 IBS: 0.19097872844320093
Fold 3 IBS: 0.20958256660234761
Fold 4 IBS: 0.20306192893149377
Fold 5 IBS: 0.20625330412566478
[I 2024-04-14 20:40:03,818] Trial 71 finished with value: 0.20788068634315526 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 10, 'n_estimators': 222, 'oob_score': False, 'max_samples': 0.9167833711990095, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16023688171015327}. Best is trial 13 with value: 0.20611217573172563.
Fold 1 IBS: 0.21705511541649875
Fold 2 IBS: 0.1833363361856442
Fold 3 IBS: 0.2147408120031225
Fold 4 IBS: 0.20500063323621776
Fold 5 IBS: 0.20803329128988426
[I 2024-04-14 20:40:05,895] Trial 72 finished with value: 0.2056332376262735 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 90, 'oob_score': False, 'max_samples': 0.8661182997981863, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18591741258051608}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22715524432934137
Fold 2 IBS: 0.18987191298883258
Fold 3 IBS: 0.21409676852807638
Fold 4 IBS: 0.2073411395130727
Fold 5 IBS: 0.20766035067280367
[I 2024-04-14 20:40:07,314] Trial 73 finished with value: 0.20922508320642536 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 85, 'oob_score': False, 'max_samples': 0.8718980020057224, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.13205192086857}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22836182724875026
Fold 2 IBS: 0.18297209122504857
Fold 3 IBS: 0.21120801959692115
Fold 4 IBS: 0.2115321555763743
Fold 5 IBS: 0.21430317709766838
[I 2024-04-14 20:40:08,127] Trial 74 finished with value: 0.20967545414895256 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 11, 'n_estimators': 25, 'oob_score': False, 'max_samples': 0.9834872007818122, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1763679545414803}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22594739166424385
Fold 2 IBS: 0.19372065616120324
Fold 3 IBS: 0.21413965638224267
Fold 4 IBS: 0.20881711495917135
Fold 5 IBS: 0.21019622885355443
[I 2024-04-14 20:40:09,645] Trial 75 finished with value: 0.2105642096040831 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 69, 'oob_score': False, 'max_samples': 0.8855689770556183, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.10799378009058896}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2258696061804822
Fold 2 IBS: 0.18871975787742432
Fold 3 IBS: 0.2058709447937611
Fold 4 IBS: 0.2068990781420462
Fold 5 IBS: 0.21127844656210354
[I 2024-04-14 20:40:12,165] Trial 76 finished with value: 0.20772756671116346 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 14, 'min_samples_leaf': 7, 'max_depth': 12, 'n_estimators': 133, 'oob_score': False, 'max_samples': 0.8567145265118952, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1491073031270957}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.255373819175504
Fold 2 IBS: 0.1883546054578289
Fold 3 IBS: 0.23316719692473128
Fold 4 IBS: 0.2157989445567964
Fold 5 IBS: 0.2104601194631519
[I 2024-04-14 20:40:13,877] Trial 77 finished with value: 0.2206309371156025 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 4, 'min_samples_leaf': 12, 'max_depth': 18, 'n_estimators': 99, 'oob_score': False, 'max_samples': 0.7849544471110336, 'max_features': None, 'min_weight_fraction_leaf': 0.08274940372349021}. Best is trial 72 with value: 0.2056332376262735.

Fold 1 IBS: 0.22522734682714227
Fold 2 IBS: 0.19837387736388737
Fold 3 IBS: 0.21858863686312044
Fold 4 IBS: 0.22243847472975584
Fold 5 IBS: 0.21919229133701493
[I 2024-04-14 20:40:14,966] Trial 78 finished with value: 0.2167641254241842 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 14, 'n_estimators': 51, 'oob_score': False, 'max_samples': 0.8217049327242889, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.28987424398930645}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.24583066360819886
Fold 2 IBS: 0.2321884833969819
Fold 3 IBS: 0.22989598582612408
Fold 4 IBS: 0.2412239000663218
Fold 5 IBS: 0.2298832890136102
[I 2024-04-14 20:40:16,982] Trial 79 finished with value: 0.23580446438224736 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 8, 'min_samples_leaf': 9, 'max_depth': 10, 'n_estimators': 150, 'oob_score': False, 'max_samples': 0.12074719353470553, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.20517605848405143}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2231483062862216
Fold 2 IBS: 0.18495890718485095
Fold 3 IBS: 0.20714575813200573
Fold 4 IBS: 0.20803626050237317
Fold 5 IBS: 0.20890157186787028
[I 2024-04-14 20:40:19,781] Trial 80 finished with value: 0.20643816079466432 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 119, 'oob_score': True, 'max_samples': 0.9548374130843311, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2311340819384068}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2228832468148195
Fold 2 IBS: 0.18504378064084887
Fold 3 IBS: 0.21089240158428396
Fold 4 IBS: 0.20602631730440754
Fold 5 IBS: 0.20935583025476157
[I 2024-04-14 20:40:22,829] Trial 81 finished with value: 0.20684031531982425 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 7, 'min_samples_leaf': 13, 'max_depth': 8, 'n_estimators': 115, 'oob_score': True, 'max_samples': 0.9440576796387987, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23569162062109766}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2224089281694983
Fold 2 IBS: 0.1824756635166651
Fold 3 IBS: 0.21678144835042762
Fold 4 IBS: 0.2045021681850755
Fold 5 IBS: 0.20759833420306845
[I 2024-04-14 20:40:24,786] Trial 82 finished with value: 0.20675330848494697 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 14, 'max_depth': 7, 'n_estimators': 96, 'oob_score': True, 'max_samples': 0.9670200911321075, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1866568997681822}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22416494136575166
Fold 2 IBS: 0.18282478505127978
Fold 3 IBS: 0.21166198455780758
Fold 4 IBS: 0.20881560174173264
Fold 5 IBS: 0.2101975830061399
[I 2024-04-14 20:40:26,183] Trial 83 finished with value: 0.2075329791445423 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 8, 'n_estimators': 64, 'oob_score': True, 'max_samples': 0.8977528739766655, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22152956482138372}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.23532254998519328
Fold 2 IBS: 0.20871641219042236
Fold 3 IBS: 0.22458655615191447
Fold 4 IBS: 0.22499698057692488
Fold 5 IBS: 0.2187744359696543
[I 2024-04-14 20:40:29,401] Trial 84 finished with value: 0.22247938697482184 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 9, 'min_samples_leaf': 10, 'max_depth': 10, 'n_estimators': 169, 'oob_score': True, 'max_samples': 0.6333088310401366, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.2693081120265306}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22889226406204877
Fold 2 IBS: 0.1816244597415934
Fold 3 IBS: 0.2183339531931547
Fold 4 IBS: 0.20554821754528813
Fold 5 IBS: 0.21267679073898976
[I 2024-04-14 20:40:31,212] Trial 85 finished with value: 0.20941513705621495 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 10, 'min_samples_leaf': 13, 'max_depth': 9, 'n_estimators': 77, 'oob_score': True, 'max_samples': 0.978844833664608, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.16365069608689778}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2214092547666285
Fold 2 IBS: 0.1931829310918888
Fold 3 IBS: 0.21698685080520216
Fold 4 IBS: 0.21492068168122902
Fold 5 IBS: 0.217146993102114
[I 2024-04-14 20:40:33,153] Trial 86 finished with value: 0.21272934228941248 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 7, 'min_samples_leaf': 14, 'max_depth': 6, 'n_estimators': 141, 'oob_score': False, 'max_samples': 0.9278295603459689, 'max_features': 'sqrt', 'min_weight_fraction_leaf': 0.3051539123714827}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2255383993453277
Fold 2 IBS: 0.18470072311271965
Fold 3 IBS: 0.21257821681084493
Fold 4 IBS: 0.204510158606243
Fold 5 IBS: 0.21015139084496856
[I 2024-04-14 20:40:35,513] Trial 87 finished with value: 0.20749577774402078 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 122, 'oob_score': False, 'max_samples': 0.9992057329191695, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.20588714449643686}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22768274332530516
Fold 2 IBS: 0.18753209493530829
Fold 3 IBS: 0.21326611570536533
Fold 4 IBS: 0.2040477268890598
Fold 5 IBS: 0.2050657372685623
[I 2024-04-14 20:40:39,510] Trial 88 finished with value: 0.2075188836247202 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 7, 'n_estimators': 306, 'oob_score': False, 'max_samples': 0.8673358917327488, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.053527501116972465}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2218551095843746
Fold 2 IBS: 0.18626756518953322
Fold 3 IBS: 0.2123140754794241
Fold 4 IBS: 0.20884773524430744
Fold 5 IBS: 0.20909335930078218
[I 2024-04-14 20:40:42,849] Trial 89 finished with value: 0.2076755689596843 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 202, 'oob_score': True, 'max_samples': 0.9567094074592274, 'max_features': 'auto', 'min_weight_fraction_leaf': 0.25899744363155275}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22549064043257053
Fold 2 IBS: 0.18635475423634423
Fold 3 IBS: 0.21000146834436625
Fold 4 IBS: 0.2048481360145379
Fold 5 IBS: 0.2067653812509645
[I 2024-04-14 20:40:46,149] Trial 90 finished with value: 0.20669207605575668 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 9, 'n_estimators': 260, 'oob_score': False, 'max_samples': 0.9034952513009158, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.12608746979727553}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22516759777925502
Fold 2 IBS: 0.18602756649884775
Fold 3 IBS: 0.21103075096852214
Fold 4 IBS: 0.2037100109931971
Fold 5 IBS: 0.20604795007136745
[I 2024-04-14 20:40:49,599] Trial 91 finished with value: 0.2063967752622379 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 15, 'max_depth': 6, 'n_estimators': 250, 'oob_score': False, 'max_samples': 0.9310728700238726, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1838376780306037}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.22547228017913462
Fold 2 IBS: 0.18574729312382882
Fold 3 IBS: 0.21030874655021844
Fold 4 IBS: 0.20550523671114262
Fold 5 IBS: 0.20599466297396152
[I 2024-04-14 20:40:52,726] Trial 92 finished with value: 0.2066056439076572 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 235, 'oob_score': False, 'max_samples': 0.9353910524517819, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1775505254215348}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2209837363351243
Fold 2 IBS: 0.1870873477688161
Fold 3 IBS: 0.21304940238251585
Fold 4 IBS: 0.20985578716023282
Fold 5 IBS: 0.20620117595320486
[I 2024-04-14 20:40:56,120] Trial 93 finished with value: 0.2074354899199788 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 5, 'n_estimators': 231, 'oob_score': False, 'max_samples': 0.9312702946350637, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18056787365195612}. Best is trial 72 with value: 0.2056332376262735.

Fold 1 IBS: 0.21916825027396117
Fold 2 IBS: 0.18609727919340027
Fold 3 IBS: 0.2128086280899691
Fold 4 IBS: 0.20635539721723173
Fold 5 IBS: 0.20776868063059972
[I 2024-04-14 20:40:59,245] Trial 94 finished with value: 0.2064396470810324 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 254, 'oob_score': False, 'max_samples': 0.8841008918901287, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.21456685175612356}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.23182805456625516
Fold 2 IBS: 0.2022942845600236
Fold 3 IBS: 0.222033047775834
Fold 4 IBS: 0.22231079464762368
Fold 5 IBS: 0.2184937117905702
[I 2024-04-14 20:41:02,855] Trial 95 finished with value: 0.21939197866806132 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 17, 'max_depth': 6, 'n_estimators': 279, 'oob_score': False, 'max_samples': 0.5739374614153154, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.23253602618263863}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.2319303660790705
Fold 2 IBS: 0.18528053747960307
Fold 3 IBS: 0.24153176938261248
Fold 4 IBS: 0.21974446932925498
Fold 5 IBS: 0.21247980064378819
[I 2024-04-14 20:41:07,556] Trial 96 finished with value: 0.21819338858286583 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 16, 'max_depth': 6, 'n_estimators': 249, 'oob_score': False, 'max_samples': 0.8852529953400602, 'max_features': None, 'min_weight_fraction_leaf': 0.19647712147515248}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.21825073737846393
Fold 2 IBS: 0.1842040786669342
Fold 3 IBS: 0.21447643038277275
Fold 4 IBS: 0.20889236526313504
Fold 5 IBS: 0.20896652586194164
[I 2024-04-14 20:41:11,657] Trial 97 finished with value: 0.2069580275106495 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 16, 'max_depth': 5, 'n_estimators': 270, 'oob_score': False, 'max_samples': 0.8338635253461467, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.22125213686068373}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.21973654563403125
Fold 2 IBS: 0.1850676823309765
Fold 3 IBS: 0.21297827857560064
Fold 4 IBS: 0.2055487730760933
Fold 5 IBS: 0.20665430298459353
[I 2024-04-14 20:41:15,327] Trial 98 finished with value: 0.20599711652025904 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 3, 'n_estimators': 238, 'oob_score': False, 'max_samples': 0.8104102235074692, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.1716567926092295}. Best is trial 72 with value: 0.2056332376262735.
Fold 1 IBS: 0.21922917308046527
Fold 2 IBS: 0.18895561029515548
Fold 3 IBS: 0.21797243194918545
Fold 4 IBS: 0.21035003910917355
Fold 5 IBS: 0.21083761943631757
[I 2024-04-14 20:41:19,556] Trial 99 finished with value: 0.20946897477405946 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 2, 'n_estimators': 291, 'oob_score': False, 'max_samples': 0.8059139390313079, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.24412945880895315}. Best is trial 72 with value: 0.2056332376262735.


* Best trial for IBS:
 FrozenTrial(number=72, state=TrialState.COMPLETE, values=[0.2056332376262735], datetime_start=datetime.datetime(2024, 4, 14, 20, 40, 3, 824114), datetime_complete=datetime.datetime(2024, 4, 14, 20, 40, 5, 894854), params={'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 10, 'max_depth': 9, 'n_estimators': 90, 'oob_score': False, 'max_samples': 0.8661182997981863, 'max_features': 'log2', 'min_weight_fraction_leaf': 0.18591741258051608}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None)), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=72, value=None)


* Best Score for IBS:
 0.2056332376262735

In [165]:
train_cindex['Randomsurvivalforest'] = np.round(study_cindex.best_value, 3)
train_ibs['Randomsurvivalforest'] = np.round(study_ibs.best_value, 3)

In [166]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.795
train_ibs:  0.206

#### Test

In [167]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))
    
y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [168]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(RandomSurvivalForest, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("test_cindex: ", c_index)

# Set the best model 
best_model_ibs = create_best_model(RandomSurvivalForest, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("test_ibs: ", ibs)

RandomSurvivalForest(max_depth=19, max_features='auto', max_leaf_nodes=17,
                     max_samples=0.9538061740605386, min_samples_leaf=11,
                     min_samples_split=4,
                     min_weight_fraction_leaf=0.09899137909936344,
                     n_estimators=40, oob_score=True, random_state=123,
                     warm_start=True)

test_cindex:  0.509

RandomSurvivalForest(max_depth=9, max_features='log2', max_leaf_nodes=12,
                     max_samples=0.8661182997981863, min_samples_leaf=10,
                     min_samples_split=5,
                     min_weight_fraction_leaf=0.18591741258051608,
                     n_estimators=90, random_state=123)

test_ibs:  0.25

In [169]:
# Saving the values to the dictionary 
test_cindex['Randomsurvivalforest'] = c_index
test_ibs['Randomsurvivalforest'] = ibs

### 6. ExtraSurvivalTrees

#### Train

In [170]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [171]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters 
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        oob_score = trial.suggest_categorical("oob_score", [True, False])
        warm_start = trial.suggest_categorical("warm_start", [True, False])
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        max_samples = trial.suggest_float("max_samples", 0.1, 1.0) 
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        
        # Include warm_start for C-index optimization
        if metric == "c-index":
            warm_start = trial.suggest_categorical("warm_start", [True, False])
        else:
            warm_start = False  # Exclude warm_start for other metrics

        
        # Create and fit survival model 
        model = model_class(min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            max_leaf_nodes=max_leaf_nodes,
                            n_estimators=n_estimators, 
                            oob_score=oob_score, 
                            max_features=max_features, 
                            warm_start=warm_start, 
                            max_samples=max_samples,
                            min_weight_fraction_leaf=min_weight_fraction_leaf, 
                            max_depth=max_depth, 
                            random_state=123) 
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ExtraSurvivalTrees, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ExtraSurvivalTrees, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 20:41:20,410] A new study created in memory with name: no-name-579551a3-995b-4378-82bd-2eb6d66bb7b2

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:41:22,366] Trial 0 finished with value: 0.7444641826742117 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:41:26,094] Trial 1 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.7361702127659574
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.703862660944206
[I 2024-04-14 20:41:33,154] Trial 2 finished with value: 0.6936083607186496 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.648068669527897
[I 2024-04-14 20:41:33,725] Trial 3 finished with value: 0.6846448086953278 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:41:36,249] Trial 4 finished with value: 0.5 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:41:38,797] Trial 5 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 20:41:40,071] Trial 6 finished with value: 0.7323528091066882 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 20:41:43,042] Trial 7 finished with value: 0.6849638891943872 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6893617021276596
Fold 4 C-index: 0.752851711026616
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 20:41:43,220] Trial 8 finished with value: 0.7016714921159409 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5577689243027888
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6638297872340425
Fold 4 C-index: 0.6996197718631179
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 20:41:50,796] Trial 9 finished with value: 0.6690625408760175 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:41:53,150] Trial 10 finished with value: 0.5 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5537848605577689
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 20:41:54,627] Trial 11 finished with value: 0.7137714267796587 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.7444641826742117.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:41:56,616] Trial 12 finished with value: 0.7621811621627721 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 20:41:58,490] Trial 13 finished with value: 0.7313264742636919 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7553648068669528
[I 2024-04-14 20:42:00,017] Trial 14 finished with value: 0.7241807732261527 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.7621811621627721.

Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7262357414448669
Fold 5 C-index: 0.7467811158798283
[I 2024-04-14 20:42:01,179] Trial 15 finished with value: 0.7240470547558558 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.5099601593625498
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7340425531914894
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6351931330472103
[I 2024-04-14 20:42:03,133] Trial 16 finished with value: 0.6662538830648959 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.7659574468085106
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 20:42:04,323] Trial 17 finished with value: 0.7429824742080647 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:42:06,460] Trial 18 finished with value: 0.5 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 20:42:07,807] Trial 19 finished with value: 0.7337057559099328 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.5597609561752988
Fold 2 C-index: 0.6957364341085271
Fold 3 C-index: 0.7063829787234043
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 20:42:08,017] Trial 20 finished with value: 0.6898482910373669 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8178294573643411
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 20:42:09,286] Trial 21 finished with value: 0.7437286168002 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 307, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6637755741118154, 'min_weight_fraction_leaf': 0.19547198867705698}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7381974248927039
[I 2024-04-14 20:42:10,090] Trial 22 finished with value: 0.7147755199069016 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 7, 'max_depth': 8, 'n_estimators': 206, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6213502616396707, 'min_weight_fraction_leaf': 0.22808857760951512}. Best is trial 12 with value: 0.7621811621627721.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:42:11,457] Trial 23 finished with value: 0.7795288364216049 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 12, 'n_estimators': 304, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7345576286528173, 'min_weight_fraction_leaf': 0.028226857904205774}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:42:12,886] Trial 24 finished with value: 0.7589429934564507 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 16, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.03170566211309643}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:42:13,997] Trial 25 finished with value: 0.7636006138299611 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 4, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 286, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9065064561810402, 'min_weight_fraction_leaf': 0.03575283796335367}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.6909871244635193
[I 2024-04-14 20:42:17,406] Trial 26 finished with value: 0.6799477505167939 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 3, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 222, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9139047046287426, 'min_weight_fraction_leaf': 0.004500255463034276}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:42:18,043] Trial 27 finished with value: 0.7721589792271323 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 165, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8371227222322273, 'min_weight_fraction_leaf': 0.028880951144641013}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:42:18,770] Trial 28 finished with value: 0.7450225155706247 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 5, 'min_samples_leaf': 3, 'max_depth': 18, 'n_estimators': 167, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8350389484038729, 'min_weight_fraction_leaf': 0.15327826840218295}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8326996197718631
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:42:19,690] Trial 29 finished with value: 0.776255126057633 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 277, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7296167280495541, 'min_weight_fraction_leaf': 0.08403914312295946}. Best is trial 23 with value: 0.7795288364216049.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.8212927756653993
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:42:20,159] Trial 30 finished with value: 0.7622070063238183 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 111, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.733146369663002, 'min_weight_fraction_leaf': 0.10323731749624541}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:42:21,113] Trial 31 finished with value: 0.7762873343448058 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 276, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8214267730230186, 'min_weight_fraction_leaf': 0.049158740363499494}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:42:22,027] Trial 32 finished with value: 0.7743319728736935 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 237, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7243313871233443, 'min_weight_fraction_leaf': 0.07920978784356175}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7713178294573644
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:42:23,023] Trial 33 finished with value: 0.7539610952448579 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 236, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5034543590712514, 'min_weight_fraction_leaf': 0.08200723099366641}. Best is trial 23 with value: 0.7795288364216049.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:42:24,144] Trial 34 finished with value: 0.7801192177498326 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 6, 'min_samples_leaf': 1, 'max_depth': 19, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6951539080512874, 'min_weight_fraction_leaf': 0.05928429546779432}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:42:26,223] Trial 35 finished with value: 0.7482892175218927 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 13, 'n_estimators': 281, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.6036171325592886, 'min_weight_fraction_leaf': 0.12132570942744575}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7276595744680852
Fold 4 C-index: 0.6920152091254753
Fold 5 C-index: 0.7424892703862661
[I 2024-04-14 20:42:30,799] Trial 36 finished with value: 0.7007486945477798 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 3, 'min_samples_leaf': 2, 'max_depth': 17, 'n_estimators': 347, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.4585897184305621, 'min_weight_fraction_leaf': 0.05010773950262152}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5179282868525896
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6829787234042554
Fold 4 C-index: 0.7015209125475285
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 20:42:33,340] Trial 37 finished with value: 0.6675468348519883 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 6, 'min_samples_leaf': 20, 'max_depth': 19, 'n_estimators': 284, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6113724270276354, 'min_weight_fraction_leaf': 0.11113631869089217}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.8
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.759656652360515
[I 2024-04-14 20:42:34,665] Trial 38 finished with value: 0.7362429383454405 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 15, 'n_estimators': 196, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.801146025500261, 'min_weight_fraction_leaf': 0.0661324819926455}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 20:42:41,746] Trial 39 finished with value: 0.6777872733079757 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 399, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5316709054002436, 'min_weight_fraction_leaf': 0.16225214864102175}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8098859315589354
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:42:43,091] Trial 40 finished with value: 0.7629274481760037 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 9, 'min_samples_leaf': 2, 'max_depth': 13, 'n_estimators': 305, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7031549425639906, 'min_weight_fraction_leaf': 0.055004481889868784}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:42:44,081] Trial 41 finished with value: 0.7729738135685147 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 246, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7385593021068815, 'min_weight_fraction_leaf': 0.08845148282083942}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.7756653992395437
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:42:45,536] Trial 42 finished with value: 0.7493502936963704 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 270, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6589369897719576, 'min_weight_fraction_leaf': 0.12452764537688477}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:42:46,326] Trial 43 finished with value: 0.7699965749171893 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 5, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 220, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8292976142475339, 'min_weight_fraction_leaf': 0.02752433404605898}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7596899224806202
Fold 3 C-index: 0.7787234042553192
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:42:47,678] Trial 44 finished with value: 0.7517043754681427 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 3, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 333, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7786901372070326, 'min_weight_fraction_leaf': 0.08096460856399929}. Best is trial 34 with value: 0.7801192177498326.

Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.747148288973384
Fold 5 C-index: 0.6995708154506438
[I 2024-04-14 20:42:49,256] Trial 45 finished with value: 0.7099623725728251 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 18, 'n_estimators': 299, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7199348056190417, 'min_weight_fraction_leaf': 0.25981797560073444}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7403100775193798
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7553648068669528
[I 2024-04-14 20:42:49,970] Trial 46 finished with value: 0.7280144980289676 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 1, 'max_depth': 14, 'n_estimators': 187, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.5659223538554059, 'min_weight_fraction_leaf': 0.053748514289518934}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.6978723404255319
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 20:42:53,803] Trial 47 finished with value: 0.7076374980169337 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 17, 'n_estimators': 244, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6491652969283795, 'min_weight_fraction_leaf': 0.017569484693263186}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 20:42:56,436] Trial 48 finished with value: 0.7321769872635879 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 8, 'min_samples_leaf': 10, 'max_depth': 20, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.7718871393405403, 'min_weight_fraction_leaf': 0.13727478449817654}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:42:57,460] Trial 49 finished with value: 0.5 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 18, 'n_estimators': 259, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.4079729445821513, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.751937984496124
Fold 3 C-index: 0.7531914893617021
Fold 4 C-index: 0.7414448669201521
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 20:42:58,083] Trial 50 finished with value: 0.7208912236777131 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 2, 'min_samples_leaf': 6, 'max_depth': 15, 'n_estimators': 131, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8518223091531967, 'min_weight_fraction_leaf': 0.09514895079159698}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:42:58,913] Trial 51 finished with value: 0.774393529223402 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 6, 'min_samples_leaf': 4, 'max_depth': 19, 'n_estimators': 229, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7330464432040066, 'min_weight_fraction_leaf': 0.0785416250357999}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:42:59,788] Trial 52 finished with value: 0.7715210683886322 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 19, 'n_estimators': 230, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7985766084601374, 'min_weight_fraction_leaf': 0.06747097783704106}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7635658914728682
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:43:00,801] Trial 53 finished with value: 0.7515333094153973 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 18, 'n_estimators': 275, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9463423717095281, 'min_weight_fraction_leaf': 0.045332181984042}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5219123505976095
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7489361702127659
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.7124463519313304
[I 2024-04-14 20:43:01,990] Trial 54 finished with value: 0.6816620694285251 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 325, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.714005584437707, 'min_weight_fraction_leaf': 0.3347027531859703}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:43:03,213] Trial 55 finished with value: 0.7745889145959806 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 291, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6812539154526723, 'min_weight_fraction_leaf': 0.016699217779926223}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7642585551330798
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 20:43:04,211] Trial 56 finished with value: 0.7460297051905626 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 2, 'max_depth': 20, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6808265962370864, 'min_weight_fraction_leaf': 0.010201383200067443}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7872340425531915
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 20:43:05,676] Trial 57 finished with value: 0.7353235901752007 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 418, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.6250144837081227, 'min_weight_fraction_leaf': 0.020760760289462554}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.6680851063829787
Fold 4 C-index: 0.7300380228136882
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 20:43:10,350] Trial 58 finished with value: 0.6985908741640635 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 17, 'n_estimators': 357, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.756693359350093, 'min_weight_fraction_leaf': 0.04092331806859899}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:12,409] Trial 59 finished with value: 0.7557383822505208 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 259, 'oob_score': True, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.8134161167197584, 'min_weight_fraction_leaf': 8.502750234120476e-05}. Best is trial 34 with value: 0.7801192177498326.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:43:13,516] Trial 60 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 7, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 315, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.5876523474241502, 'min_weight_fraction_leaf': 0.3720382868873145}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:43:14,380] Trial 61 finished with value: 0.7698371057425326 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 211, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7584366500354351, 'min_weight_fraction_leaf': 0.07308809221719109}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6374501992031872
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.7957446808510639
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:15,433] Trial 62 finished with value: 0.7665639626427135 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 20, 'n_estimators': 287, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6827016495738562, 'min_weight_fraction_leaf': 0.09511870728443896}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.7829787234042553
Fold 4 C-index: 0.7984790874524715
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:43:17,269] Trial 63 finished with value: 0.7529425627205012 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 6, 'min_samples_leaf': 2, 'max_depth': 19, 'n_estimators': 247, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.865043055009094, 'min_weight_fraction_leaf': 0.11884012018961995}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:18,477] Trial 64 finished with value: 0.7642926323281479 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 3, 'max_depth': 17, 'n_estimators': 267, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6457374530121598, 'min_weight_fraction_leaf': 0.06351778696293643}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:43:19,874] Trial 65 finished with value: 0.7762692963181657 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 189, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7327876063408303, 'min_weight_fraction_leaf': 0.0415919905958566}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:43:21,512] Trial 66 finished with value: 0.5 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 18, 'min_samples_leaf': 1, 'max_depth': 16, 'n_estimators': 193, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.7774150863578628, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8403041825095057
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:22,372] Trial 67 finished with value: 0.7760992378068907 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 18, 'n_estimators': 151, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6979096114785991, 'min_weight_fraction_leaf': 0.03946299005400537}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:22,817] Trial 68 finished with value: 0.7596823651752902 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 68, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.636687049032269, 'min_weight_fraction_leaf': 0.0384223432309741}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8288973384030418
Fold 5 C-index: 0.7939914163090128
[I 2024-04-14 20:43:23,606] Trial 69 finished with value: 0.7697466251733446 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 17, 'n_estimators': 142, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6786782498605258, 'min_weight_fraction_leaf': 0.020949167883598397}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.7148936170212766
Fold 4 C-index: 0.7072243346007605
Fold 5 C-index: 0.7381974248927039
[I 2024-04-14 20:43:27,384] Trial 70 finished with value: 0.704449498602 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 3, 'n_estimators': 166, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7043515897560921, 'min_weight_fraction_leaf': 0.047280961190121706}. Best is trial 34 with value: 0.7801192177498326.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:43:28,026] Trial 71 finished with value: 0.7833030576913206 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 116, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7308881538010942, 'min_weight_fraction_leaf': 0.034339748024412}. Best is trial 71 with value: 0.7833030576913206.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.825531914893617
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 20:43:28,568] Trial 72 finished with value: 0.7858417920779566 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20, 'n_estimators': 93, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8090258480680113, 'min_weight_fraction_leaf': 0.028110447824443725}. Best is trial 72 with value: 0.7858417920779566.
Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:29,040] Trial 73 finished with value: 0.7855486044330031 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 82, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9192524164544513, 'min_weight_fraction_leaf': 0.03799764475920653}. Best is trial 72 with value: 0.7858417920779566.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8154506437768241
[I 2024-04-14 20:43:29,480] Trial 74 finished with value: 0.7874064769222235 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 73, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9262734398316605, 'min_weight_fraction_leaf': 0.061229345497880144}. Best is trial 74 with value: 0.7874064769222235.

Fold 1 C-index: 0.6254980079681275
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:43:29,950] Trial 75 finished with value: 0.7847588000967032 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 69, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9225867458601602, 'min_weight_fraction_leaf': 0.05825744836904712}. Best is trial 74 with value: 0.7874064769222235.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7790697674418605
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.844106463878327
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:43:30,354] Trial 76 finished with value: 0.7634186715984045 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 75, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9408890646049121, 'min_weight_fraction_leaf': 0.06156546300754267}. Best is trial 74 with value: 0.7874064769222235.
Fold 1 C-index: 0.49800796812749004
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.7617021276595745
Fold 4 C-index: 0.6958174904942965
Fold 5 C-index: 0.7682403433476395
[I 2024-04-14 20:43:30,578] Trial 77 finished with value: 0.7067690898017691 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 11, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 13, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.929891665926839, 'min_weight_fraction_leaf': 0.027852174991749107}. Best is trial 74 with value: 0.7874064769222235.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8085106382978723
Fold 4 C-index: 0.8060836501901141
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:30,906] Trial 78 finished with value: 0.761845600737084 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 12, 'min_samples_leaf': 3, 'max_depth': 7, 'n_estimators': 43, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9989909763930809, 'min_weight_fraction_leaf': 0.10707294387787991}. Best is trial 74 with value: 0.7874064769222235.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.779467680608365
Fold 5 C-index: 0.776824034334764
[I 2024-04-14 20:43:31,441] Trial 79 finished with value: 0.7569858141036708 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 9, 'n_estimators': 104, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.8995707980037997, 'min_weight_fraction_leaf': 0.0006039564996443356}. Best is trial 74 with value: 0.7874064769222235.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8197424892703863
[I 2024-04-14 20:43:31,900] Trial 80 finished with value: 0.789068540195809 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 88, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9591796294691712, 'min_weight_fraction_leaf': 0.058732012819878776}. Best is trial 80 with value: 0.789068540195809.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8326180257510729
[I 2024-04-14 20:43:32,359] Trial 81 finished with value: 0.7925241863711043 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 94, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9542950427646696, 'min_weight_fraction_leaf': 0.0511398872664384}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6175298804780877
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8425531914893617
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 20:43:32,814] Trial 82 finished with value: 0.7908000159179192 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 85, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.946625617576546, 'min_weight_fraction_leaf': 0.05978401991224075}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.8062015503875969
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8555133079847909
Fold 5 C-index: 0.8283261802575107
[I 2024-04-14 20:43:33,258] Trial 83 finished with value: 0.7923610092856983 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9611832214140841, 'min_weight_fraction_leaf': 0.061492233480030814}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6334661354581673
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:43:33,738] Trial 84 finished with value: 0.7824961900013279 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 86, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9669012458102935, 'min_weight_fraction_leaf': 0.08949575595240514}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8340425531914893
Fold 4 C-index: 0.8479087452471483
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:43:34,066] Trial 85 finished with value: 0.7816083294189832 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 48, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9590441187061061, 'min_weight_fraction_leaf': 0.05721405622518019}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7906976744186046
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:43:34,584] Trial 86 finished with value: 0.7681860556486219 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 119, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9117968106125828, 'min_weight_fraction_leaf': 0.0737297049362212}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7751937984496124
Fold 3 C-index: 0.8170212765957446
Fold 4 C-index: 0.8250950570342205
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:43:35,047] Trial 87 finished with value: 0.7684029494191813 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 1, 'max_depth': 10, 'n_estimators': 90, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.888707973798634, 'min_weight_fraction_leaf': 0.09941102750255168}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7364341085271318
Fold 3 C-index: 0.6510638297872341
Fold 4 C-index: 0.7452471482889734
Fold 5 C-index: 0.7296137339055794
[I 2024-04-14 20:43:36,044] Trial 88 finished with value: 0.6919936764523814 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 54, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.9961313077361209, 'min_weight_fraction_leaf': 0.13159446908882738}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.5976095617529881
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 20:43:36,420] Trial 89 finished with value: 0.7820204815752865 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 13, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 62, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.9180654851291982, 'min_weight_fraction_leaf': 0.030076548324635938}. Best is trial 81 with value: 0.7925241863711043.

Fold 1 C-index: 0.6055776892430279
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:43:36,703] Trial 90 finished with value: 0.7754220673859628 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 23, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9672632339555209, 'min_weight_fraction_leaf': 0.012163845817492937}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8212765957446808
Fold 4 C-index: 0.8365019011406845
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:43:37,140] Trial 91 finished with value: 0.7816993772523239 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 8, 'n_estimators': 89, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9670594034179123, 'min_weight_fraction_leaf': 0.08891083438069615}. Best is trial 81 with value: 0.7925241863711043.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.8023255813953488
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8369098712446352
[I 2024-04-14 20:43:37,588] Trial 92 finished with value: 0.7940266534831981 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 87, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8680829438458175, 'min_weight_fraction_leaf': 0.05559928273470952}. Best is trial 92 with value: 0.7940266534831981.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7574468085106383
Fold 4 C-index: 0.7566539923954373
Fold 5 C-index: 0.7854077253218884
[I 2024-04-14 20:43:38,044] Trial 93 finished with value: 0.735151095282345 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 9, 'n_estimators': 100, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8643140005566761, 'min_weight_fraction_leaf': 0.21309389541627582}. Best is trial 92 with value: 0.7940266534831981.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.8372093023255814
Fold 3 C-index: 0.8468085106382979
Fold 4 C-index: 0.8631178707224335
Fold 5 C-index: 0.8111587982832618
[I 2024-04-14 20:43:38,329] Trial 94 finished with value: 0.7840094940034767 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 12, 'min_samples_leaf': 1, 'max_depth': 11, 'n_estimators': 33, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9330277700684522, 'min_weight_fraction_leaf': 0.055683271975382566}. Best is trial 92 with value: 0.7940266534831981.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.813953488372093
Fold 3 C-index: 0.8127659574468085
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.7982832618025751
[I 2024-04-14 20:43:38,617] Trial 95 finished with value: 0.7624792199664204 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 11, 'min_samples_leaf': 8, 'max_depth': 11, 'n_estimators': 39, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.9330552953783225, 'min_weight_fraction_leaf': 0.06760646073304538}. Best is trial 92 with value: 0.7940266534831981.
Fold 1 C-index: 0.6095617529880478
Fold 2 C-index: 0.8333333333333334
Fold 3 C-index: 0.8382978723404255
Fold 4 C-index: 0.8517110266159695
Fold 5 C-index: 0.8068669527896996
[I 2024-04-14 20:43:38,907] Trial 96 finished with value: 0.7879541876134952 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 13, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 29, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8786953940085371, 'min_weight_fraction_leaf': 0.052972037036932276}. Best is trial 92 with value: 0.7940266534831981.
Fold 1 C-index: 0.6454183266932271
Fold 2 C-index: 0.810077519379845
Fold 3 C-index: 0.8297872340425532
Fold 4 C-index: 0.8593155893536122
Fold 5 C-index: 0.8240343347639485
[I 2024-04-14 20:43:39,329] Trial 97 finished with value: 0.7937266008466372 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 14, 'min_samples_leaf': 2, 'max_depth': 6, 'n_estimators': 82, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8477036016233799, 'min_weight_fraction_leaf': 0.051316513809819525}. Best is trial 92 with value: 0.7940266534831981.
Fold 1 C-index: 0.6215139442231076
Fold 2 C-index: 0.7829457364341085
Fold 3 C-index: 0.774468085106383
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.7811158798283262
[I 2024-04-14 20:43:39,900] Trial 98 finished with value: 0.7486627215138224 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 130, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8516401508116112, 'min_weight_fraction_leaf': 0.15708043147612902}. Best is trial 92 with value: 0.7940266534831981.

[I 2024-04-14 20:43:40,440] A new study created in memory with name: no-name-0f0a8199-e1ce-4a7f-8a98-805c84177cef

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.8
Fold 4 C-index: 0.8136882129277566
Fold 5 C-index: 0.8025751072961373
[I 2024-04-14 20:43:40,421] Trial 99 finished with value: 0.7633261684766637 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 16, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 79, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8837630737696329, 'min_weight_fraction_leaf': 0.11319278144396797}. Best is trial 92 with value: 0.7940266534831981.


* Best trial for C-index:
 FrozenTrial(number=92, state=TrialState.COMPLETE, values=[0.7940266534831981], datetime_start=datetime.datetime(2024, 4, 14, 20, 43, 37, 145600), datetime_complete=datetime.datetime(2024, 4, 14, 20, 43, 37, 588317), params={'min_samples_split': 12, 'max_leaf_nodes': 14, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 87, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.8680829438458175, 'min_weight_fraction_leaf': 0.05559928273470952}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=92, value=None)


* Best Score for C-index:
 0.7940266534831981

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.23541000780759655
Fold 2 IBS: 0.2067761661131848
Fold 3 IBS: 0.20638127656650881
Fold 4 IBS: 0.22122194494618408
Fold 5 IBS: 0.211867760390908
[I 2024-04-14 20:43:44,937] Trial 0 finished with value: 0.21633143116487644 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 12, 'n_estimators': 360, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7641958651588321, 'min_weight_fraction_leaf': 0.09124586522674999}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24609870664410521
Fold 2 IBS: 0.2322322897001989
Fold 3 IBS: 0.22952656700785698
Fold 4 IBS: 0.24148921645731658
Fold 5 IBS: 0.23019106302613623
[I 2024-04-14 20:43:51,297] Trial 1 finished with value: 0.2359075685671228 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 11, 'max_depth': 13, 'n_estimators': 425, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.4877764869966794, 'min_weight_fraction_leaf': 0.2468425488251531}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.2447657897467725
Fold 2 IBS: 0.22541200386484336
Fold 3 IBS: 0.22400558269320267
Fold 4 IBS: 0.236596843656482
Fold 5 IBS: 0.22550687321467755
[I 2024-04-14 20:43:56,768] Trial 2 finished with value: 0.2312574186351956 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 7, 'min_samples_leaf': 9, 'max_depth': 18, 'n_estimators': 473, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.6516050731866709, 'min_weight_fraction_leaf': 0.06031433299516187}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24349462081664708
Fold 2 IBS: 0.22503305247562366
Fold 3 IBS: 0.22455114832494247
Fold 4 IBS: 0.23729673030219745
Fold 5 IBS: 0.22610866521166154
[I 2024-04-14 20:43:58,903] Trial 3 finished with value: 0.23129684342621445 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 153, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.7873145572990043, 'min_weight_fraction_leaf': 0.121833187268437}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24657522393140555
Fold 2 IBS: 0.23233102481025178
Fold 3 IBS: 0.22955556895196394
Fold 4 IBS: 0.2414104149445062
Fold 5 IBS: 0.23022225298005008
[I 2024-04-14 20:44:04,363] Trial 4 finished with value: 0.23601889712363552 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 18, 'n_estimators': 314, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4500555167108301, 'min_weight_fraction_leaf': 0.46256624480699304}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24664580957819934
Fold 2 IBS: 0.23217251680747322
Fold 3 IBS: 0.22935584130643083
Fold 4 IBS: 0.241440572614939
Fold 5 IBS: 0.23022342591131315
[I 2024-04-14 20:44:08,072] Trial 5 finished with value: 0.2359676332436711 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 200, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.561815338779102, 'min_weight_fraction_leaf': 0.3333122750820358}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.23583447744571467
Fold 2 IBS: 0.20816448387854342
Fold 3 IBS: 0.20870447828873862
Fold 4 IBS: 0.22174993693023834
Fold 5 IBS: 0.21222756037580223
[I 2024-04-14 20:44:14,028] Trial 6 finished with value: 0.21733618738380747 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 14, 'n_estimators': 424, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5693797534575991, 'min_weight_fraction_leaf': 0.001344032287160346}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24008407955279745
Fold 2 IBS: 0.22001171646700285
Fold 3 IBS: 0.2202331308819595
Fold 4 IBS: 0.2343998833525932
Fold 5 IBS: 0.2213403384038152
[I 2024-04-14 20:44:17,897] Trial 7 finished with value: 0.22721382973163365 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 6, 'n_estimators': 261, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.9851694482832, 'min_weight_fraction_leaf': 0.03968289518900786}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24213702213538632
Fold 2 IBS: 0.2239301571554859
Fold 3 IBS: 0.22823828795754114
Fold 4 IBS: 0.2336533614019845
Fold 5 IBS: 0.22551398237561687
[I 2024-04-14 20:44:18,872] Trial 8 finished with value: 0.23069456220520296 and parameters: {'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11, 'n_estimators': 47, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8028981441999615, 'min_weight_fraction_leaf': 0.14326830836455096}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24528172627644354
Fold 2 IBS: 0.23019569199157422
Fold 3 IBS: 0.22810447972353712
Fold 4 IBS: 0.24071190300337614
Fold 5 IBS: 0.22896442752217908
[I 2024-04-14 20:44:25,907] Trial 9 finished with value: 0.23465164570342206 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 14, 'min_samples_leaf': 3, 'max_depth': 14, 'n_estimators': 444, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.7756453003088511, 'min_weight_fraction_leaf': 0.28703191257498223}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24672496618607107
Fold 2 IBS: 0.23224650601788785
Fold 3 IBS: 0.23004987749916536
Fold 4 IBS: 0.2412296281450331
Fold 5 IBS: 0.23015666331663637
[I 2024-04-14 20:44:30,841] Trial 10 finished with value: 0.23608152823295875 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 2, 'min_samples_leaf': 18, 'max_depth': 1, 'n_estimators': 334, 'oob_score': True, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.243821979756625, 'min_weight_fraction_leaf': 0.1775271775427378}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.24295437239821252
Fold 2 IBS: 0.2190283007247468
Fold 3 IBS: 0.21921852378198423
Fold 4 IBS: 0.2322204458461499
Fold 5 IBS: 0.21937111331755668
[I 2024-04-14 20:44:35,629] Trial 11 finished with value: 0.22655855121373003 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 2, 'min_samples_leaf': 7, 'max_depth': 15, 'n_estimators': 370, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.3251929559633234, 'min_weight_fraction_leaf': 0.008038652206972807}. Best is trial 0 with value: 0.21633143116487644.
Fold 1 IBS: 0.23386318092025865
Fold 2 IBS: 0.20124598317421252
Fold 3 IBS: 0.20325658727940316
Fold 4 IBS: 0.22118810564306907
Fold 5 IBS: 0.20913515757707815
[I 2024-04-14 20:44:41,814] Trial 12 finished with value: 0.21373780291880431 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 498, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9826746994213879, 'min_weight_fraction_leaf': 0.001220613326079395}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23918852531892718
Fold 2 IBS: 0.2154345171834043
Fold 3 IBS: 0.21752894522063776
Fold 4 IBS: 0.23003112409928395
Fold 5 IBS: 0.21868399240084702
[I 2024-04-14 20:44:48,061] Trial 13 finished with value: 0.22417342084462005 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 9, 'min_samples_leaf': 15, 'max_depth': 10, 'n_estimators': 490, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9791374133648018, 'min_weight_fraction_leaf': 0.10296999070738919}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23954094174025162
Fold 2 IBS: 0.21754391640424023
Fold 3 IBS: 0.21782578364552393
Fold 4 IBS: 0.23070986864867826
Fold 5 IBS: 0.21951817906232923
[I 2024-04-14 20:44:52,682] Trial 14 finished with value: 0.22502773790020467 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 10, 'n_estimators': 383, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.8930281794338997, 'min_weight_fraction_leaf': 0.20156755541688948}. Best is trial 12 with value: 0.21373780291880431.

Fold 1 IBS: 0.23972733412957625
Fold 2 IBS: 0.216733225501965
Fold 3 IBS: 0.21671101773702317
Fold 4 IBS: 0.22924165165554902
Fold 5 IBS: 0.21887656987764706
[I 2024-04-14 20:44:57,965] Trial 15 finished with value: 0.2242579597803521 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 9, 'min_samples_leaf': 13, 'max_depth': 4, 'n_estimators': 258, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.6880212408103346, 'min_weight_fraction_leaf': 0.07884420972256234}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.24606737011629873
Fold 2 IBS: 0.23089475111753785
Fold 3 IBS: 0.22859907740096824
Fold 4 IBS: 0.24086252073023415
Fold 5 IBS: 0.2291116620203717
[I 2024-04-14 20:45:05,221] Trial 16 finished with value: 0.23510707627708216 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 20, 'n_estimators': 499, 'oob_score': False, 'warm_start': True, 'max_features': 'auto', 'max_samples': 0.8750346354626457, 'min_weight_fraction_leaf': 0.4093818399278544}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.2319079729319764
Fold 2 IBS: 0.2046708831760625
Fold 3 IBS: 0.214422277793119
Fold 4 IBS: 0.22602007257107706
Fold 5 IBS: 0.21454576398569697
[I 2024-04-14 20:45:09,340] Trial 17 finished with value: 0.21831339409158637 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 10, 'min_samples_leaf': 8, 'max_depth': 12, 'n_estimators': 318, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.6920108932666474, 'min_weight_fraction_leaf': 0.19239050103117486}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.24679929991389535
Fold 2 IBS: 0.23208761806557146
Fold 3 IBS: 0.2295482436451861
Fold 4 IBS: 0.24111555931482462
Fold 5 IBS: 0.22939893490285035
[I 2024-04-14 20:45:11,437] Trial 18 finished with value: 0.23578993116846556 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 105, 'oob_score': True, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.11021186122144816, 'min_weight_fraction_leaf': 0.06410839839317758}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23865959914028895
Fold 2 IBS: 0.21451620073119432
Fold 3 IBS: 0.21726445319565615
Fold 4 IBS: 0.2296125156175126
Fold 5 IBS: 0.21764375951458906
[I 2024-04-14 20:45:16,116] Trial 19 finished with value: 0.2235393056398482 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 4, 'n_estimators': 381, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.879016892949421, 'min_weight_fraction_leaf': 0.13986580326377504}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.24111867802772696
Fold 2 IBS: 0.230897067966171
Fold 3 IBS: 0.22660320612541593
Fold 4 IBS: 0.2355116734567556
Fold 5 IBS: 0.23222250779865844
[I 2024-04-14 20:45:16,405] Trial 20 finished with value: 0.23327062667494558 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 16, 'n_estimators': 6, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.9842806388697818, 'min_weight_fraction_leaf': 0.3334082239721289}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23592918703424454
Fold 2 IBS: 0.20751554778956324
Fold 3 IBS: 0.20849511398123036
Fold 4 IBS: 0.2229131389697958
Fold 5 IBS: 0.21241577796768152
[I 2024-04-14 20:45:21,745] Trial 21 finished with value: 0.2174537531485031 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 4, 'min_samples_leaf': 7, 'max_depth': 13, 'n_estimators': 426, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.5865344620215767, 'min_weight_fraction_leaf': 0.0037914391968427914}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23675498365850053
Fold 2 IBS: 0.20886103526328453
Fold 3 IBS: 0.21140679536117526
Fold 4 IBS: 0.22378791093852177
Fold 5 IBS: 0.21111691740405705
[I 2024-04-14 20:45:27,645] Trial 22 finished with value: 0.2183855285251078 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 4, 'min_samples_leaf': 6, 'max_depth': 16, 'n_estimators': 439, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.4780520239555279, 'min_weight_fraction_leaf': 0.01760516455314039}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23392920831924904
Fold 2 IBS: 0.20550811134679545
Fold 3 IBS: 0.20997504701229933
Fold 4 IBS: 0.21991919852495587
Fold 5 IBS: 0.21264031272150177
[I 2024-04-14 20:45:32,552] Trial 23 finished with value: 0.2163943755849603 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 393, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6423644985218102, 'min_weight_fraction_leaf': 0.07933617912675625}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.235869283908189
Fold 2 IBS: 0.20829883550367015
Fold 3 IBS: 0.2079258484701011
Fold 4 IBS: 0.2209101006699348
Fold 5 IBS: 0.21066015114099687
[I 2024-04-14 20:45:38,247] Trial 24 finished with value: 0.21673284393857836 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 9, 'n_estimators': 361, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7479661339947506, 'min_weight_fraction_leaf': 0.09384728704326059}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23978219816596788
Fold 2 IBS: 0.21926162183930378
Fold 3 IBS: 0.21930010752359563
Fold 4 IBS: 0.23097406645581847
Fold 5 IBS: 0.22102448269794936
[I 2024-04-14 20:45:42,265] Trial 25 finished with value: 0.226068495336527 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 10, 'min_samples_leaf': 1, 'max_depth': 8, 'n_estimators': 290, 'oob_score': False, 'warm_start': True, 'max_features': 1, 'max_samples': 0.6407612251366877, 'min_weight_fraction_leaf': 0.047956477383484165}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23907444808757625
Fold 2 IBS: 0.214777042555578
Fold 3 IBS: 0.21625825147010558
Fold 4 IBS: 0.2275156213578202
Fold 5 IBS: 0.21726690575856075
[I 2024-04-14 20:45:48,216] Trial 26 finished with value: 0.22297845384592815 and parameters: {'min_samples_split': 14, 'max_leaf_nodes': 8, 'min_samples_leaf': 3, 'max_depth': 5, 'n_estimators': 405, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.8454924050883471, 'min_weight_fraction_leaf': 0.16863579271898874}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.23912882830353752
Fold 2 IBS: 0.22035623012444322
Fold 3 IBS: 0.22011929593333043
Fold 4 IBS: 0.23276004116790824
Fold 5 IBS: 0.2202449113487284
[I 2024-04-14 20:45:50,651] Trial 27 finished with value: 0.22652186137558958 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 6, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 210, 'oob_score': False, 'warm_start': True, 'max_features': 'sqrt', 'max_samples': 0.9296679330104113, 'min_weight_fraction_leaf': 0.24207301181705376}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.2344072962111878
Fold 2 IBS: 0.21307038420529434
Fold 3 IBS: 0.21848036336455554
Fold 4 IBS: 0.22735041544384846
Fold 5 IBS: 0.21783162638973505
[I 2024-04-14 20:45:56,014] Trial 28 finished with value: 0.22222801712292423 and parameters: {'min_samples_split': 11, 'max_leaf_nodes': 3, 'min_samples_leaf': 19, 'max_depth': 12, 'n_estimators': 473, 'oob_score': False, 'warm_start': True, 'max_features': None, 'max_samples': 0.7294475749114913, 'min_weight_fraction_leaf': 0.10561943508937117}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.24486117267091953
Fold 2 IBS: 0.22712101671130253
Fold 3 IBS: 0.2259348063378496
Fold 4 IBS: 0.23883943690300063
Fold 5 IBS: 0.22798240293506997
[I 2024-04-14 20:46:01,049] Trial 29 finished with value: 0.2329477671116284 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 10, 'min_samples_leaf': 11, 'max_depth': 2, 'n_estimators': 351, 'oob_score': True, 'warm_start': True, 'max_features': None, 'max_samples': 0.5014355663623529, 'min_weight_fraction_leaf': 0.23367475592947387}. Best is trial 12 with value: 0.21373780291880431.

Fold 1 IBS: 0.24158942477782158
Fold 2 IBS: 0.21929391721716995
Fold 3 IBS: 0.2193550775567237
Fold 4 IBS: 0.2323195982287675
Fold 5 IBS: 0.2197126913890985
[I 2024-04-14 20:46:06,402] Trial 30 finished with value: 0.22645414183391624 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 9, 'max_depth': 8, 'n_estimators': 457, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.3838693489032564, 'min_weight_fraction_leaf': 0.03868084640768137}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.2354981935315128
Fold 2 IBS: 0.20611350006679782
Fold 3 IBS: 0.2080374995849842
Fold 4 IBS: 0.22144619637606308
Fold 5 IBS: 0.21166974370445468
[I 2024-04-14 20:46:11,508] Trial 31 finished with value: 0.21655302665276252 and parameters: {'min_samples_split': 13, 'max_leaf_nodes': 6, 'min_samples_leaf': 3, 'max_depth': 10, 'n_estimators': 409, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.7359152304070016, 'min_weight_fraction_leaf': 0.08655997300539783}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.2350232181555605
Fold 2 IBS: 0.20701877305100838
Fold 3 IBS: 0.20988357555272202
Fold 4 IBS: 0.2207813200437261
Fold 5 IBS: 0.2128514728081812
[I 2024-04-14 20:46:18,827] Trial 32 finished with value: 0.21711167192223962 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 12, 'n_estimators': 411, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.618283894727248, 'min_weight_fraction_leaf': 0.07716716290582956}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.24429537439957505
Fold 2 IBS: 0.22476060898059944
Fold 3 IBS: 0.2233975485845743
Fold 4 IBS: 0.23696714591607443
Fold 5 IBS: 0.22476138515059127
[I 2024-04-14 20:46:24,436] Trial 33 finished with value: 0.23083641260628288 and parameters: {'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 395, 'oob_score': False, 'warm_start': True, 'max_features': 0.1, 'max_samples': 0.8125920153130402, 'min_weight_fraction_leaf': 0.12995854366525855}. Best is trial 12 with value: 0.21373780291880431.
Fold 1 IBS: 0.22904393427252656
Fold 2 IBS: 0.2031896671921071
Fold 3 IBS: 0.19716626093785272
Fold 4 IBS: 0.21582451680821427
Fold 5 IBS: 0.2065288444156224
[I 2024-04-14 20:46:28,933] Trial 34 finished with value: 0.2103506447252646 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 300, 'oob_score': False, 'warm_start': True, 'max_features': 'log2', 'max_samples': 0.6862833758870215, 'min_weight_fraction_leaf': 0.03963928663346105}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.2316720282120584
Fold 2 IBS: 0.20387319540624332
Fold 3 IBS: 0.20178937218817874
Fold 4 IBS: 0.21795946116819784
Fold 5 IBS: 0.20672342441184713
[I 2024-04-14 20:46:33,015] Trial 35 finished with value: 0.2124034962773051 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 289, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6530069859702445, 'min_weight_fraction_leaf': 0.050567074439106276}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.2309509235236281
Fold 2 IBS: 0.2008004575612247
Fold 3 IBS: 0.2020762738189886
Fold 4 IBS: 0.21936555189674709
Fold 5 IBS: 0.20743210064348433
[I 2024-04-14 20:46:35,939] Trial 36 finished with value: 0.21212506148881455 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 212, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5213032265978997, 'min_weight_fraction_leaf': 0.031243121234821793}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.23074015939219508
Fold 2 IBS: 0.20610419519447712
Fold 3 IBS: 0.20248752872996595
Fold 4 IBS: 0.21895348691134447
Fold 5 IBS: 0.20910486381023072
[I 2024-04-14 20:46:38,881] Trial 37 finished with value: 0.21347804680764265 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 213, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.41218594978509804, 'min_weight_fraction_leaf': 0.031444007932221844}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.23238825440610444
Fold 2 IBS: 0.21022995652098855
Fold 3 IBS: 0.20743963989211522
Fold 4 IBS: 0.2225558266843722
Fold 5 IBS: 0.21045005152799942
[I 2024-04-14 20:46:41,610] Trial 38 finished with value: 0.21661274580631598 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 1, 'max_depth': 7, 'n_estimators': 204, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.40435140119451696, 'min_weight_fraction_leaf': 0.042905193405504985}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.23792351073948861
Fold 2 IBS: 0.21952716582245183
Fold 3 IBS: 0.22072323067251218
Fold 4 IBS: 0.23217575168411336
Fold 5 IBS: 0.22211681186522356
[I 2024-04-14 20:46:44,320] Trial 39 finished with value: 0.2264932941567579 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 143, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5268630766622321, 'min_weight_fraction_leaf': 0.03129947022699252}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.24494172352261248
Fold 2 IBS: 0.22892081192211297
Fold 3 IBS: 0.22678863669483915
Fold 4 IBS: 0.23899436456835554
Fold 5 IBS: 0.2258002333534824
[I 2024-04-14 20:46:47,939] Trial 40 finished with value: 0.2330891540122805 and parameters: {'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 2, 'max_depth': 3, 'n_estimators': 226, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.28252976048396017, 'min_weight_fraction_leaf': 0.1156143884282467}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.2356033899438255
Fold 2 IBS: 0.21070152241489806
Fold 3 IBS: 0.21237406170315362
Fold 4 IBS: 0.2249393129359781
Fold 5 IBS: 0.21283419423205463
[I 2024-04-14 20:46:48,439] Trial 41 finished with value: 0.219290496245982 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 9, 'min_samples_leaf': 1, 'max_depth': 6, 'n_estimators': 281, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.42429246951383215, 'min_weight_fraction_leaf': 0.05785299024344398}. Best is trial 34 with value: 0.2103506447252646.
Fold 1 IBS: 0.2309865620061274
Fold 2 IBS: 0.20027895285270966
Fold 3 IBS: 0.19828795024783957
Fold 4 IBS: 0.21995450762445468
Fold 5 IBS: 0.20192393408999054
[I 2024-04-14 20:46:51,082] Trial 42 finished with value: 0.21028638136422434 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 155, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5407230611270839, 'min_weight_fraction_leaf': 0.023334636687091077}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.23069427400001988
Fold 2 IBS: 0.19994723835778988
Fold 3 IBS: 0.2000229337898892
Fold 4 IBS: 0.21820755760361787
Fold 5 IBS: 0.20652926803082705
[I 2024-04-14 20:46:53,492] Trial 43 finished with value: 0.2110802543564288 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 2, 'max_depth': 7, 'n_estimators': 169, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5445322130902165, 'min_weight_fraction_leaf': 0.026310032275698454}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.24040868632227458
Fold 2 IBS: 0.2224089938631853
Fold 3 IBS: 0.22168924018224506
Fold 4 IBS: 0.23266217994548027
Fold 5 IBS: 0.2244244479817081
[I 2024-04-14 20:46:56,092] Trial 44 finished with value: 0.22831870965897866 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 7, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 173, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5939088327532095, 'min_weight_fraction_leaf': 0.0628628648873941}. Best is trial 42 with value: 0.21028638136422434.

Fold 1 IBS: 0.23004762363280065
Fold 2 IBS: 0.20207981520408078
Fold 3 IBS: 0.20542350510528304
Fold 4 IBS: 0.21487462055621293
Fold 5 IBS: 0.2031286821836111
[I 2024-04-14 20:46:57,700] Trial 45 finished with value: 0.2111108493363977 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 114, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5545433281929569, 'min_weight_fraction_leaf': 0.022411260801931558}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.23041156618088032
Fold 2 IBS: 0.20438661273089367
Fold 3 IBS: 0.2083274286291039
Fold 4 IBS: 0.21434598556991874
Fold 5 IBS: 0.20018044432936546
[I 2024-04-14 20:46:59,130] Trial 46 finished with value: 0.21153040748803242 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 102, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.5399077944190729, 'min_weight_fraction_leaf': 0.02207537638553926}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.23007992329762014
Fold 2 IBS: 0.2023395884279792
Fold 3 IBS: 0.20905028894098338
Fold 4 IBS: 0.2134021216063568
Fold 5 IBS: 0.20158027548623528
[I 2024-04-14 20:47:00,732] Trial 47 finished with value: 0.21129043955183496 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 96, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.552957209333458, 'min_weight_fraction_leaf': 0.02234311113247947}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.2465734003221463
Fold 2 IBS: 0.23211367930781418
Fold 3 IBS: 0.22936687042772075
Fold 4 IBS: 0.24146492649260143
Fold 5 IBS: 0.22997312600471817
[I 2024-04-14 20:47:02,611] Trial 48 finished with value: 0.23589840051100017 and parameters: {'min_samples_split': 20, 'max_leaf_nodes': 13, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 108, 'oob_score': True, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.4669655236956115, 'min_weight_fraction_leaf': 0.3098199009921797}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.24649304451500081
Fold 2 IBS: 0.23205232931533315
Fold 3 IBS: 0.22961345820751042
Fold 4 IBS: 0.241431849841236
Fold 5 IBS: 0.22999205538856052
[I 2024-04-14 20:47:03,760] Trial 49 finished with value: 0.23591654745352816 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 2, 'max_depth': 5, 'n_estimators': 77, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.5660156120513645, 'min_weight_fraction_leaf': 0.43477928434486296}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.23039349896939193
Fold 2 IBS: 0.20645910625869127
Fold 3 IBS: 0.20614057229362506
Fold 4 IBS: 0.21776932641542435
Fold 5 IBS: 0.20791341381004935
[I 2024-04-14 20:47:06,826] Trial 50 finished with value: 0.2137351835494364 and parameters: {'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 6, 'max_depth': 11, 'n_estimators': 164, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.6842972258472233, 'min_weight_fraction_leaf': 0.0033816243124838684}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.23191947568984364
Fold 2 IBS: 0.20283046453125658
Fold 3 IBS: 0.2037222024855227
Fold 4 IBS: 0.2165400412283832
Fold 5 IBS: 0.20370820916602986
[I 2024-04-14 20:47:08,636] Trial 51 finished with value: 0.21174407862020722 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 9, 'min_samples_leaf': 4, 'max_depth': 8, 'n_estimators': 123, 'oob_score': False, 'warm_start': False, 'max_features': 'auto', 'max_samples': 0.542711230088007, 'min_weight_fraction_leaf': 0.026069679633803584}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.2291592351216811
Fold 2 IBS: 0.20982595095261186
Fold 3 IBS: 0.20773370134788383
Fold 4 IBS: 0.21729801608588528
Fold 5 IBS: 0.1989616880586829
[I 2024-04-14 20:47:09,690] Trial 52 finished with value: 0.21259571831334897 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 12, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 66, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.6044682156389908, 'min_weight_fraction_leaf': 0.014345116305463704}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.24200109668481798
Fold 2 IBS: 0.22514407559025026
Fold 3 IBS: 0.22814909903345443
Fold 4 IBS: 0.2310310010541026
Fold 5 IBS: 0.22297914953357112
[I 2024-04-14 20:47:10,490] Trial 53 finished with value: 0.22986088437923927 and parameters: {'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 4, 'max_depth': 9, 'n_estimators': 44, 'oob_score': False, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.36723323819208314, 'min_weight_fraction_leaf': 0.06414008232987992}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.2428547945273447
Fold 2 IBS: 0.22783201825170782
Fold 3 IBS: 0.2251358388493631
Fold 4 IBS: 0.23721372955953712
Fold 5 IBS: 0.22285071628980896
[I 2024-04-14 20:47:12,322] Trial 54 finished with value: 0.23117741949555234 and parameters: {'min_samples_split': 17, 'max_leaf_nodes': 11, 'min_samples_leaf': 3, 'max_depth': 8, 'n_estimators': 136, 'oob_score': False, 'warm_start': False, 'max_features': 'log2', 'max_samples': 0.45233371176470716, 'min_weight_fraction_leaf': 0.15911827592136196}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.23667957376282697
Fold 2 IBS: 0.2187771553940336
Fold 3 IBS: 0.21760156653113052
Fold 4 IBS: 0.2282751389514541
Fold 5 IBS: 0.21681448376452717
[I 2024-04-14 20:47:13,612] Trial 55 finished with value: 0.2236295836807945 and parameters: {'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 2, 'max_depth': 10, 'n_estimators': 84, 'oob_score': False, 'warm_start': False, 'max_features': 1, 'max_samples': 0.5020658928712398, 'min_weight_fraction_leaf': 0.019297944181692415}. Best is trial 42 with value: 0.21028638136422434.
Fold 1 IBS: 0.22782584542612844
Fold 2 IBS: 0.190678831392239
Fold 3 IBS: 0.20575386398544498
Fold 4 IBS: 0.2104357277164361
Fold 5 IBS: 0.20714578164728875
[I 2024-04-14 20:47:16,524] Trial 56 finished with value: 0.20836801003350747 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 177, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5576425680081901, 'min_weight_fraction_leaf': 0.0676458331935679}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.23024843744091733
Fold 2 IBS: 0.19660575059674526
Fold 3 IBS: 0.2140909128084417
Fold 4 IBS: 0.2203796683458188
Fold 5 IBS: 0.2108985141868672
[I 2024-04-14 20:47:19,080] Trial 57 finished with value: 0.21444465667575807 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 4, 'n_estimators': 171, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5649651296502699, 'min_weight_fraction_leaf': 0.1169028238985022}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.23405870250882232
Fold 2 IBS: 0.19121198049249072
Fold 3 IBS: 0.2071135383626016
Fold 4 IBS: 0.2134757285603309
Fold 5 IBS: 0.20943526977695517
[I 2024-04-14 20:47:21,510] Trial 58 finished with value: 0.21105904394024014 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 125, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6659973923607253, 'min_weight_fraction_leaf': 0.07067539548362298}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.24669078644635123
Fold 2 IBS: 0.23214611575948257
Fold 3 IBS: 0.22950918855201136
Fold 4 IBS: 0.2415791323439235
Fold 5 IBS: 0.23036261693415022
[I 2024-04-14 20:47:25,559] Trial 59 finished with value: 0.23605756800718378 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 3, 'min_samples_leaf': 9, 'max_depth': 6, 'n_estimators': 234, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7018800988349638, 'min_weight_fraction_leaf': 0.3787205021140745}. Best is trial 56 with value: 0.20836801003350747.

Fold 1 IBS: 0.22886388120004955
Fold 2 IBS: 0.1922779447217556
Fold 3 IBS: 0.20596346109163932
Fold 4 IBS: 0.2162435591402912
Fold 5 IBS: 0.20842350045875987
[I 2024-04-14 20:47:28,127] Trial 60 finished with value: 0.2103544693224991 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 194, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6240740459164607, 'min_weight_fraction_leaf': 0.0999675321939971}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.2347250098325648
Fold 2 IBS: 0.1889247237462346
Fold 3 IBS: 0.20786146399799835
Fold 4 IBS: 0.21442044305481517
Fold 5 IBS: 0.2103485414591851
[I 2024-04-14 20:47:30,837] Trial 61 finished with value: 0.21125603641815957 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 3, 'min_samples_leaf': 8, 'max_depth': 5, 'n_estimators': 189, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6644350776650744, 'min_weight_fraction_leaf': 0.07493659875312506}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.23576739281121747
Fold 2 IBS: 0.19829955078555317
Fold 3 IBS: 0.20633177480515869
Fold 4 IBS: 0.22315034186026883
Fold 5 IBS: 0.2147427610962012
[I 2024-04-14 20:47:33,492] Trial 62 finished with value: 0.2156583642716799 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 2, 'min_samples_leaf': 8, 'max_depth': 3, 'n_estimators': 153, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6166350906936542, 'min_weight_fraction_leaf': 0.09211777696807427}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.22975230573346725
Fold 2 IBS: 0.19317515962710516
Fold 3 IBS: 0.21049953117592135
Fold 4 IBS: 0.21395420586863914
Fold 5 IBS: 0.20706174752035025
[I 2024-04-14 20:47:35,949] Trial 63 finished with value: 0.21088858998509666 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 7, 'n_estimators': 188, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6220361278829775, 'min_weight_fraction_leaf': 0.05189752478185136}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.2272286122963715
Fold 2 IBS: 0.192121631818631
Fold 3 IBS: 0.21240497447312223
Fold 4 IBS: 0.21426486026598482
Fold 5 IBS: 0.2066397613428236
[I 2024-04-14 20:47:38,428] Trial 64 finished with value: 0.21053196803938662 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 3, 'n_estimators': 190, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7187059677793391, 'min_weight_fraction_leaf': 0.14359469421914262}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.2356239968037487
Fold 2 IBS: 0.20089788635467862
Fold 3 IBS: 0.2055053325702284
Fold 4 IBS: 0.22290451128914357
Fold 5 IBS: 0.2156139466671022
[I 2024-04-14 20:47:40,704] Trial 65 finished with value: 0.2161091347369803 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 4, 'min_samples_leaf': 10, 'max_depth': 1, 'n_estimators': 188, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.770734707213561, 'min_weight_fraction_leaf': 0.15005096647379162}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.24670484568653853
Fold 2 IBS: 0.2321597403624784
Fold 3 IBS: 0.22953663738200086
Fold 4 IBS: 0.24157687334192918
Fold 5 IBS: 0.23040664853716178
[I 2024-04-14 20:47:43,446] Trial 66 finished with value: 0.23607694906202176 and parameters: {'min_samples_split': 7, 'max_leaf_nodes': 5, 'min_samples_leaf': 12, 'max_depth': 3, 'n_estimators': 237, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7097058737225727, 'min_weight_fraction_leaf': 0.4946184281535514}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.22842925584506726
Fold 2 IBS: 0.19784938647021968
Fold 3 IBS: 0.20856772345969588
Fold 4 IBS: 0.22026465263217174
Fold 5 IBS: 0.21315433642123308
[I 2024-04-14 20:47:46,938] Trial 67 finished with value: 0.2136530709656775 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 3, 'min_samples_leaf': 15, 'max_depth': 4, 'n_estimators': 266, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8110028999924759, 'min_weight_fraction_leaf': 0.1029556577231417}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.23015769518958015
Fold 2 IBS: 0.19116602618563608
Fold 3 IBS: 0.21120511305570738
Fold 4 IBS: 0.21598215266701998
Fold 5 IBS: 0.2095078481932503
[I 2024-04-14 20:47:49,954] Trial 68 finished with value: 0.21160376705823883 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 4, 'min_samples_leaf': 9, 'max_depth': 2, 'n_estimators': 189, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6761802916789802, 'min_weight_fraction_leaf': 0.13116770059584754}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.23441323707538236
Fold 2 IBS: 0.20971053111584542
Fold 3 IBS: 0.21718910067259084
Fold 4 IBS: 0.22405154712276362
Fold 5 IBS: 0.21457705413440678
[I 2024-04-14 20:47:51,594] Trial 69 finished with value: 0.2199882940241978 and parameters: {'min_samples_split': 9, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 5, 'n_estimators': 132, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6306682224595703, 'min_weight_fraction_leaf': 0.20025994963319688}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.23046391159848761
Fold 2 IBS: 0.19414908037057252
Fold 3 IBS: 0.21021773872424182
Fold 4 IBS: 0.21867056826503561
Fold 5 IBS: 0.2084559828278719
[I 2024-04-14 20:47:57,010] Trial 70 finished with value: 0.21239145635724185 and parameters: {'min_samples_split': 8, 'max_leaf_nodes': 3, 'min_samples_leaf': 12, 'max_depth': 6, 'n_estimators': 319, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.7218820303442508, 'min_weight_fraction_leaf': 0.07079842998882656}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.23437362827933286
Fold 2 IBS: 0.2019864539039948
Fold 3 IBS: 0.2071509566325182
Fold 4 IBS: 0.224200358422297
Fold 5 IBS: 0.21507451548159853
[I 2024-04-14 20:47:59,362] Trial 71 finished with value: 0.2165571825439483 and parameters: {'min_samples_split': 6, 'max_leaf_nodes': 2, 'min_samples_leaf': 11, 'max_depth': 4, 'n_estimators': 154, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5915716732615164, 'min_weight_fraction_leaf': 0.04959088024724835}. Best is trial 56 with value: 0.20836801003350747.
Fold 1 IBS: 0.2297708358160276
Fold 2 IBS: 0.18878213998710872
Fold 3 IBS: 0.21040068415193633
Fold 4 IBS: 0.20798241144388963
Fold 5 IBS: 0.20325219453013008
[I 2024-04-14 20:48:02,175] Trial 72 finished with value: 0.2080376531858185 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 183, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.6546728244508441, 'min_weight_fraction_leaf': 0.09415421702777221}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22915967645064336
Fold 2 IBS: 0.19076931891743967
Fold 3 IBS: 0.20657715026874915
Fold 4 IBS: 0.21236826098700323
Fold 5 IBS: 0.20304168988374494
[I 2024-04-14 20:48:05,394] Trial 73 finished with value: 0.20838321930151604 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 8, 'max_depth': 6, 'n_estimators': 248, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.647367274002876, 'min_weight_fraction_leaf': 0.0971498125736289}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22796901752317147
Fold 2 IBS: 0.19104044695929392
Fold 3 IBS: 0.20766198586250514
Fold 4 IBS: 0.21335385776159665
Fold 5 IBS: 0.20433547422513984
[I 2024-04-14 20:48:09,105] Trial 74 finished with value: 0.20887215646634139 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 5, 'n_estimators': 252, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.643629501785618, 'min_weight_fraction_leaf': 0.09594457315344829}. Best is trial 72 with value: 0.2080376531858185.

Fold 1 IBS: 0.2323383037155898
Fold 2 IBS: 0.1926386768769483
Fold 3 IBS: 0.2043263234125086
Fold 4 IBS: 0.2177958054014891
Fold 5 IBS: 0.20847206331237897
[I 2024-04-14 20:48:12,847] Trial 75 finished with value: 0.21111423454378295 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 2, 'n_estimators': 248, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7455530824826245, 'min_weight_fraction_leaf': 0.10174967743425128}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.23125321916750102
Fold 2 IBS: 0.19448300187171705
Fold 3 IBS: 0.2064500233945674
Fold 4 IBS: 0.2118211264767168
Fold 5 IBS: 0.2062701779464504
[I 2024-04-14 20:48:17,024] Trial 76 finished with value: 0.21005550977139054 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 303, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7855036521095284, 'min_weight_fraction_leaf': 0.12520246822003794}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.23933501399397233
Fold 2 IBS: 0.21293228103177061
Fold 3 IBS: 0.21397744312625078
Fold 4 IBS: 0.22788868754571634
Fold 5 IBS: 0.21723823091402275
[I 2024-04-14 20:48:20,736] Trial 77 finished with value: 0.22227433132234659 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 5, 'n_estimators': 301, 'oob_score': False, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.6510450158784382, 'min_weight_fraction_leaf': 0.11907360503196933}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.23021126445566464
Fold 2 IBS: 0.19745291503532902
Fold 3 IBS: 0.2085269519937124
Fold 4 IBS: 0.2198969079980828
Fold 5 IBS: 0.2106698563131173
[I 2024-04-14 20:48:24,243] Trial 78 finished with value: 0.21335157915918126 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 4, 'n_estimators': 270, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.7758887222892249, 'min_weight_fraction_leaf': 0.17517251864189415}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22901473449335605
Fold 2 IBS: 0.2019346972584239
Fold 3 IBS: 0.2120367017734523
Fold 4 IBS: 0.22390056488940216
Fold 5 IBS: 0.21551658945094893
[I 2024-04-14 20:48:28,627] Trial 79 finished with value: 0.21648065757311669 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 9, 'max_depth': 5, 'n_estimators': 337, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.8318964105461786, 'min_weight_fraction_leaf': 0.22324451118149274}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.2272422271346621
Fold 2 IBS: 0.19321691750644426
Fold 3 IBS: 0.2113732778132945
Fold 4 IBS: 0.21202793688213847
Fold 5 IBS: 0.20625298199094608
[I 2024-04-14 20:48:32,931] Trial 80 finished with value: 0.2100226682654971 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 222, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5095861562397511, 'min_weight_fraction_leaf': 0.08963663016744944}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.2279550157218713
Fold 2 IBS: 0.1920159484835093
Fold 3 IBS: 0.21233030332543065
Fold 4 IBS: 0.2167018047855499
Fold 5 IBS: 0.2065427228368758
[I 2024-04-14 20:48:36,142] Trial 81 finished with value: 0.2111091590306474 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 223, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4976377715259645, 'min_weight_fraction_leaf': 0.09196792156167266}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.2275495660671292
Fold 2 IBS: 0.1940817922800249
Fold 3 IBS: 0.20667335745276208
Fold 4 IBS: 0.21258066976697773
Fold 5 IBS: 0.2055800795225772
[I 2024-04-14 20:48:39,798] Trial 82 finished with value: 0.20929309301789423 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 7, 'n_estimators': 246, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5764071728587299, 'min_weight_fraction_leaf': 0.08565406311512272}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22560715273679657
Fold 2 IBS: 0.19210227699035337
Fold 3 IBS: 0.2124218100910431
Fold 4 IBS: 0.21493530019541082
Fold 5 IBS: 0.20415375944205408
[I 2024-04-14 20:48:43,006] Trial 83 finished with value: 0.2098440598911316 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 250, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5198345986399353, 'min_weight_fraction_leaf': 0.08342853524139951}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22657138426320422
Fold 2 IBS: 0.19405568109981639
Fold 3 IBS: 0.21111313223439981
Fold 4 IBS: 0.21328693193136206
Fold 5 IBS: 0.2052568956361618
[I 2024-04-14 20:48:46,382] Trial 84 finished with value: 0.21005680503298887 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 7, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 256, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5127325702626473, 'min_weight_fraction_leaf': 0.08489869722357606}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.2266629399582841
Fold 2 IBS: 0.1939543279381164
Fold 3 IBS: 0.21114385272850392
Fold 4 IBS: 0.2133429584524925
Fold 5 IBS: 0.2051580228877265
[I 2024-04-14 20:48:50,078] Trial 85 finished with value: 0.21005242039302469 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 6, 'min_samples_leaf': 7, 'max_depth': 7, 'n_estimators': 254, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.5130402670722527, 'min_weight_fraction_leaf': 0.08515489262414602}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.23362008498558895
Fold 2 IBS: 0.20850702523164819
Fold 3 IBS: 0.21365665787777974
Fold 4 IBS: 0.23032712838520547
Fold 5 IBS: 0.21333814959431224
[I 2024-04-14 20:48:53,680] Trial 86 finished with value: 0.21988980921490694 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 6, 'min_samples_leaf': 8, 'max_depth': 9, 'n_estimators': 247, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.43469861471683213, 'min_weight_fraction_leaf': 0.13247084981964286}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22884996138419847
Fold 2 IBS: 0.19708711716765906
Fold 3 IBS: 0.21453768543877827
Fold 4 IBS: 0.2216928477734207
Fold 5 IBS: 0.2113428380629648
[I 2024-04-14 20:48:56,468] Trial 87 finished with value: 0.21470208996540427 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 6, 'min_samples_leaf': 6, 'max_depth': 6, 'n_estimators': 221, 'oob_score': False, 'warm_start': False, 'max_features': None, 'max_samples': 0.4672771733169796, 'min_weight_fraction_leaf': 0.1124816847578164}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22760997167183872
Fold 2 IBS: 0.19146027266242763
Fold 3 IBS: 0.20856475672866
Fold 4 IBS: 0.21251350008658587
Fold 5 IBS: 0.20486451415346618
[I 2024-04-14 20:49:01,301] Trial 88 finished with value: 0.20900260306059568 and parameters: {'min_samples_split': 4, 'max_leaf_nodes': 7, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 283, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5794488894536745, 'min_weight_fraction_leaf': 0.08203525048441256}. Best is trial 72 with value: 0.2080376531858185.
Fold 1 IBS: 0.22831960711642793
Fold 2 IBS: 0.1917484701218111
Fold 3 IBS: 0.2078703942768865
Fold 4 IBS: 0.21405904174873328
Fold 5 IBS: 0.20510626497742698
[I 2024-04-14 20:49:06,098] Trial 89 finished with value: 0.20942075564825716 and parameters: {'min_samples_split': 5, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7, 'n_estimators': 285, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.583426861353741, 'min_weight_fraction_leaf': 0.08354477188637702}. Best is trial 72 with value: 0.2080376531858185.

Fold 1 IBS: 0.23068196697328497
Fold 2 IBS: 0.19089408813814912
Fold 3 IBS: 0.20382905085626038
Fold 4 IBS: 0.21084183448318802
Fold 5 IBS: 0.2025699645464283
[I 2024-04-14 20:49:10,754] Trial 90 finished with value: 0.20776338099946218 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 269, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5784776864026564, 'min_weight_fraction_leaf': 0.061135549090751994}. Best is trial 90 with value: 0.20776338099946218.
Fold 1 IBS: 0.2310128688684838
Fold 2 IBS: 0.19092846353894036
Fold 3 IBS: 0.20422692176342377
Fold 4 IBS: 0.21039728779594005
Fold 5 IBS: 0.2025066026589034
[I 2024-04-14 20:49:17,187] Trial 91 finished with value: 0.2078144289251383 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 8, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5774200267789502, 'min_weight_fraction_leaf': 0.06034453196030595}. Best is trial 90 with value: 0.20776338099946218.
Fold 1 IBS: 0.22718307124879925
Fold 2 IBS: 0.19208905428958362
Fold 3 IBS: 0.20693121338937276
Fold 4 IBS: 0.20940801049164792
Fold 5 IBS: 0.20385400848427218
[I 2024-04-14 20:49:23,671] Trial 92 finished with value: 0.20789307158073517 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 6, 'max_depth': 8, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5822334713126689, 'min_weight_fraction_leaf': 0.06916260521694025}. Best is trial 90 with value: 0.20776338099946218.
Fold 1 IBS: 0.23083628748664098
Fold 2 IBS: 0.1907791916408589
Fold 3 IBS: 0.20425124482812668
Fold 4 IBS: 0.21039370230860083
Fold 5 IBS: 0.2025810013066787
[I 2024-04-14 20:49:28,361] Trial 93 finished with value: 0.20776828551418122 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5799769388286501, 'min_weight_fraction_leaf': 0.06117326916057485}. Best is trial 90 with value: 0.20776338099946218.
Fold 1 IBS: 0.23394550933887112
Fold 2 IBS: 0.19102501644340095
Fold 3 IBS: 0.20554358870249348
Fold 4 IBS: 0.21024768861873852
Fold 5 IBS: 0.20239717125599174
[I 2024-04-14 20:49:32,677] Trial 94 finished with value: 0.20863179487189915 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.5850210354372214, 'min_weight_fraction_leaf': 0.0601094602081375}. Best is trial 90 with value: 0.20776338099946218.
Fold 1 IBS: 0.23349986227030126
Fold 2 IBS: 0.19091694683891905
Fold 3 IBS: 0.20454043545998424
Fold 4 IBS: 0.2086210729940778
Fold 5 IBS: 0.2007047189175405
[I 2024-04-14 20:49:37,514] Trial 95 finished with value: 0.20765660729616459 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 277, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.6126238139085486, 'min_weight_fraction_leaf': 0.0628358466674267}. Best is trial 95 with value: 0.20765660729616459.
Fold 1 IBS: 0.2411320150016894
Fold 2 IBS: 0.2217460212980695
Fold 3 IBS: 0.21990603430315006
Fold 4 IBS: 0.23211468726824347
Fold 5 IBS: 0.22363051008045123
[I 2024-04-14 20:49:42,981] Trial 96 finished with value: 0.22770585359032075 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 273, 'oob_score': True, 'warm_start': False, 'max_features': 0.1, 'max_samples': 0.5981588547550191, 'min_weight_fraction_leaf': 0.0616298505546881}. Best is trial 95 with value: 0.20765660729616459.
Fold 1 IBS: 0.24207832405500623
Fold 2 IBS: 0.22167164859216978
Fold 3 IBS: 0.22035650227816914
Fold 4 IBS: 0.2330198019477448
Fold 5 IBS: 0.22357628325075435
[I 2024-04-14 20:49:48,458] Trial 97 finished with value: 0.22814051202476887 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 11, 'min_samples_leaf': 6, 'max_depth': 10, 'n_estimators': 312, 'oob_score': True, 'warm_start': False, 'max_features': 1, 'max_samples': 0.6441447672234398, 'min_weight_fraction_leaf': 0.039094924694215265}. Best is trial 95 with value: 0.20765660729616459.
Fold 1 IBS: 0.2336581390725983
Fold 2 IBS: 0.19165969943222555
Fold 3 IBS: 0.20293377996347522
Fold 4 IBS: 0.2092825795043673
Fold 5 IBS: 0.1996558886144805
[I 2024-04-14 20:49:54,211] Trial 98 finished with value: 0.20743801731742942 and parameters: {'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 334, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.598575294078392, 'min_weight_fraction_leaf': 0.056138512874115615}. Best is trial 98 with value: 0.20743801731742942.
Fold 1 IBS: 0.2339265113154773
Fold 2 IBS: 0.20336641379460024
Fold 3 IBS: 0.20479752932043543
Fold 4 IBS: 0.22192526813157976
Fold 5 IBS: 0.2069699511286489
[I 2024-04-14 20:50:00,104] Trial 99 finished with value: 0.21419713473814833 and parameters: {'min_samples_split': 2, 'max_leaf_nodes': 10, 'min_samples_leaf': 5, 'max_depth': 11, 'n_estimators': 328, 'oob_score': True, 'warm_start': False, 'max_features': 'sqrt', 'max_samples': 0.5980291750915963, 'min_weight_fraction_leaf': 0.05667270913653155}. Best is trial 98 with value: 0.20743801731742942.


* Best trial for IBS:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.20743801731742942], datetime_start=datetime.datetime(2024, 4, 14, 20, 49, 48, 463331), datetime_complete=datetime.datetime(2024, 4, 14, 20, 49, 54, 210818), params={'min_samples_split': 3, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 9, 'n_estimators': 334, 'oob_score': True, 'warm_start': False, 'max_features': None, 'max_samples': 0.598575294078392, 'min_weight_fraction_leaf': 0.056138512874115615}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'oob_score': CategoricalDistribution(choices=(True, False)), 'warm_start': CategoricalDistribution(choices=(True, False)), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'max_samples': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None)}, trial_id=98, value=None)


* Best Score for IBS:
 0.20743801731742942

In [172]:
train_cindex['ExtraSurvivalTrees'] = np.round(study_cindex.best_value, 3)
train_ibs['ExtraSurvivalTrees'] = np.round(study_ibs.best_value, 3)

In [173]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.794
train_ibs:  0.207

#### Test

In [174]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [175]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ExtraSurvivalTrees, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ExtraSurvivalTrees, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ExtraSurvivalTrees(max_depth=8, max_features=None, max_leaf_nodes=14,
                   max_samples=0.8680829438458175, min_samples_leaf=1,
                   min_samples_split=12,
                   min_weight_fraction_leaf=0.05559928273470952,
                   n_estimators=87, random_state=123, warm_start=True)

C-index score: 0.506

ExtraSurvivalTrees(max_depth=9, max_features=None, max_leaf_nodes=9,
                   max_samples=0.598575294078392, min_samples_leaf=5,
                   min_samples_split=3,
                   min_weight_fraction_leaf=0.056138512874115615,
                   n_estimators=334, oob_score=True, random_state=123)

IBS: 0.257

In [176]:
# Saving the values to the dictionary 
test_cindex['ExtraSurvivalTrees'] = c_index
test_ibs['ExtraSurvivalTrees'] = ibs

### 7. GradientBoostingSurvivalAnalysis

#### Train

In [177]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

# Running to optuna for hyperparameter tuning
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        criterion = trial.suggest_categorical('criterion', ['friedman_mse', 'squared_error'])
        ccp_alpha = trial.suggest_float("ccp_alpha", 0.0, 10)
        min_weight_fraction_leaf = trial.suggest_float("min_weight_fraction_leaf", 0.0, 0.5)
        max_features = trial.suggest_categorical("max_features", ["auto", "sqrt", "log2", None, 0.1, 1])
        min_impurity_decrease = trial.suggest_loguniform('min_impurity_decrease', 1e-7, 1e-1)
        validation_fraction = trial.suggest_float("validation_fraction", 0.0, 1.0)
        min_samples_split = trial.suggest_int("min_samples_split", 2, 20)
        max_leaf_nodes = trial.suggest_int("max_leaf_nodes", 2, 20)
        min_samples_leaf = trial.suggest_int("min_samples_leaf", 1, 20)
        max_depth = trial.suggest_int("max_depth", 1, 20)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            learning_rate=learning_rate,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            ccp_alpha=ccp_alpha, 
                            criterion=criterion,
                            min_samples_split=min_samples_split,
                            min_samples_leaf=min_samples_leaf,
                            min_weight_fraction_leaf=min_weight_fraction_leaf,
                            max_depth=max_depth,
                            max_features=max_features,
                            max_leaf_nodes=max_leaf_nodes, 
                            min_impurity_decrease=min_impurity_decrease,
                            validation_fraction=validation_fraction, 
                            random_state=123)
        
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            model.fit(X_train, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective

# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(GradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# Example usage for IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(GradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 20:50:01,966] A new study created in memory with name: no-name-bc61b3c3-4c97-429f-a89d-52cc7c89b3b4

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:29,984] Trial 0 finished with value: 0.5 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:50:47,598] Trial 1 finished with value: 0.5 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:51:00,439] Trial 2 finished with value: 0.5 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:51:25,752] Trial 3 finished with value: 0.5 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:51:34,517] Trial 4 finished with value: 0.5 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:51:36,723] Trial 5 finished with value: 0.5 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:51:59,343] Trial 6 finished with value: 0.5 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:52:05,751] Trial 7 finished with value: 0.5 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:52:06,818] Trial 8 finished with value: 0.5 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 0 with value: 0.5.
Fold 1 C-index: 0.703187250996016
Fold 2 C-index: 0.7732558139534884
Fold 3 C-index: 0.6234042553191489
Fold 4 C-index: 0.7319391634980988
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 20:53:06,991] Trial 9 finished with value: 0.6985461379550671 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.5638297872340425
Fold 4 C-index: 0.7832699619771863
Fold 5 C-index: 0.6051502145922747
[I 2024-04-14 20:54:37,787] Trial 10 finished with value: 0.6727533375211936 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:56:11,968] Trial 11 finished with value: 0.5 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6693227091633466
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.5808510638297872
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6931330472103004
[I 2024-04-14 20:57:40,329] Trial 12 finished with value: 0.689371712730521 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:58:22,280] Trial 13 finished with value: 0.5 and parameters: {'subsample': 0.8386796524426539, 'learning_rate': 0.046734492485875676, 'dropout_rate': 0.4821375662037144, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.5696007313501796, 'min_weight_fraction_leaf': 0.18684147934268416, 'max_features': 'log2', 'min_impurity_decrease': 1.5044881127471587e-06, 'validation_fraction': 0.8166356053932342, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 20:59:26,381] Trial 14 finished with value: 0.5 and parameters: {'subsample': 0.33235389014851724, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.2712811374536856, 'n_estimators': 405, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.3593599611215348e-06, 'validation_fraction': 0.8509723448617921, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:00:27,518] Trial 15 finished with value: 0.5 and parameters: {'subsample': 0.8129019771780099, 'learning_rate': 0.018305177594982368, 'dropout_rate': 0.3931825233425479, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.21611501623460333, 'max_features': 'auto', 'min_impurity_decrease': 1.8080959437088904e-06, 'validation_fraction': 0.4162355349268205, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:01:12,777] Trial 16 finished with value: 0.5 and parameters: {'subsample': 0.5310633495459828, 'learning_rate': 0.03630483117513936, 'dropout_rate': 0.46717840123239474, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.13351887507507515, 'max_features': 'log2', 'min_impurity_decrease': 7.106148660660447e-07, 'validation_fraction': 0.8757926354424221, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 16, 'max_depth': 6}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:02:31,621] Trial 17 finished with value: 0.5 and parameters: {'subsample': 0.10730942678329708, 'learning_rate': 0.0030843137431910686, 'dropout_rate': 0.24430564869860838, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.32255170476025713, 'max_features': 0.1, 'min_impurity_decrease': 0.005531867233735077, 'validation_fraction': 0.6486893968922347, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 20, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:04:16,781] Trial 18 finished with value: 0.5 and parameters: {'subsample': 0.8179022915704841, 'learning_rate': 0.018519433454358032, 'dropout_rate': 0.1008806019705222, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 5.2703918988558005, 'min_weight_fraction_leaf': 0.23935988478408027, 'max_features': 1, 'min_impurity_decrease': 3.6851270823897832e-06, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 8, 'max_depth': 14}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:04:20,940] Trial 19 finished with value: 0.5 and parameters: {'subsample': 0.40038650690516625, 'learning_rate': 0.09492674417021844, 'dropout_rate': 0.7868206632311315, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 2.3852188192598858, 'min_weight_fraction_leaf': 0.17391697846092632, 'max_features': 'auto', 'min_impurity_decrease': 0.0001748309976476489, 'validation_fraction': 0.7697599802341146, 'min_samples_split': 14, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:04:57,519] Trial 20 finished with value: 0.5 and parameters: {'subsample': 0.6109477334802965, 'learning_rate': 0.03807498865669169, 'dropout_rate': 0.4736916576521926, 'n_estimators': 367, 'criterion': 'squared_error', 'ccp_alpha': 2.369581337168447, 'min_weight_fraction_leaf': 0.3142029548864006, 'max_features': 'auto', 'min_impurity_decrease': 2.3400962467789323e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 9, 'min_samples_leaf': 17, 'max_depth': 6}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6673306772908366
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5914893617021276
Fold 4 C-index: 0.5
Fold 5 C-index: 0.6888412017167382
[I 2024-04-14 21:06:21,103] Trial 21 finished with value: 0.5895322481419404 and parameters: {'subsample': 0.9353717494044597, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.1861830169994726, 'n_estimators': 454, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.3921482486515702, 'max_features': 'auto', 'min_impurity_decrease': 4.539661913787372e-07, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6137339055793991
[I 2024-04-14 21:07:31,567] Trial 22 finished with value: 0.6443581285716469 and parameters: {'subsample': 0.9030031356045858, 'learning_rate': 0.010706280861824496, 'dropout_rate': 0.2075412325353082, 'n_estimators': 445, 'criterion': 'squared_error', 'ccp_alpha': 0.0339977959383996, 'min_weight_fraction_leaf': 0.4472167339801619, 'max_features': 'auto', 'min_impurity_decrease': 3.3602815261835675e-07, 'validation_fraction': 0.9350158433232643, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:08:46,807] Trial 23 finished with value: 0.5 and parameters: {'subsample': 0.9850328720116182, 'learning_rate': 0.0022352926084811455, 'dropout_rate': 0.3347839164118928, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.3814793147095995, 'max_features': 'auto', 'min_impurity_decrease': 1.3867086507876819e-07, 'validation_fraction': 0.7985348560780942, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:09:43,467] Trial 24 finished with value: 0.5 and parameters: {'subsample': 0.7505294762841698, 'learning_rate': 0.013748989714410182, 'dropout_rate': 0.16056765011928048, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.9203720890771525, 'min_weight_fraction_leaf': 0.26681231280268275, 'max_features': 'auto', 'min_impurity_decrease': 5.718216945134322e-06, 'validation_fraction': 0.9974485851849321, 'min_samples_split': 20, 'max_leaf_nodes': 9, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:10:46,856] Trial 25 finished with value: 0.5 and parameters: {'subsample': 0.8502968404151126, 'learning_rate': 0.024443951259730985, 'dropout_rate': 0.2675273969344081, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 2.0753749717266823, 'min_weight_fraction_leaf': 0.3503497788125578, 'max_features': 'auto', 'min_impurity_decrease': 7.237153572123947e-07, 'validation_fraction': 0.41222573804914475, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:11:17,554] Trial 26 finished with value: 0.5 and parameters: {'subsample': 0.7670085127536703, 'learning_rate': 0.011828778593594373, 'dropout_rate': 0.4300954216773497, 'n_estimators': 330, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.0746699764936222, 'max_features': 1, 'min_impurity_decrease': 5.109218816246879e-07, 'validation_fraction': 0.8809838005252161, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:12:42,245] Trial 27 finished with value: 0.5 and parameters: {'subsample': 0.874644665128399, 'learning_rate': 0.0018981992329649981, 'dropout_rate': 0.13713876659995541, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.623821229554995, 'min_weight_fraction_leaf': 0.42252275124014166, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.6800666052293046, 'min_samples_split': 14, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:12:46,647] Trial 28 finished with value: 0.5 and parameters: {'subsample': 0.9594421765226429, 'learning_rate': 0.02726714987416799, 'dropout_rate': 0.23828233225863246, 'n_estimators': 105, 'criterion': 'squared_error', 'ccp_alpha': 1.8140088705032984, 'min_weight_fraction_leaf': 0.24016053353127162, 'max_features': 0.1, 'min_impurity_decrease': 4.0841773817979955e-06, 'validation_fraction': 0.21313726998461896, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:13:45,280] Trial 29 finished with value: 0.5 and parameters: {'subsample': 0.28287642608139807, 'learning_rate': 0.03189667175429266, 'dropout_rate': 0.3203162831648968, 'n_estimators': 418, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.3527580599889865, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 8}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:14:02,763] Trial 30 finished with value: 0.5 and parameters: {'subsample': 0.45334769335248726, 'learning_rate': 0.009498914594310164, 'dropout_rate': 0.2845276602004858, 'n_estimators': 218, 'criterion': 'squared_error', 'ccp_alpha': 3.0866232840054875, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 1.710497738154158e-06, 'validation_fraction': 0.9147142955266686, 'min_samples_split': 15, 'max_leaf_nodes': 20, 'min_samples_leaf': 6, 'max_depth': 13}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6434262948207171
Fold 2 C-index: 0.7383720930232558
Fold 3 C-index: 0.5404255319148936
Fold 4 C-index: 0.5
Fold 5 C-index: 0.628755364806867
[I 2024-04-14 21:15:12,312] Trial 31 finished with value: 0.6101958569131466 and parameters: {'subsample': 0.8762466289302759, 'learning_rate': 0.01677291448402691, 'dropout_rate': 0.2042113761435103, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.08695292205930799, 'min_weight_fraction_leaf': 0.449325910272154, 'max_features': 'auto', 'min_impurity_decrease': 3.2113674851552086e-07, 'validation_fraction': 0.9280762147853976, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:16:29,020] Trial 32 finished with value: 0.5 and parameters: {'subsample': 0.7721262056182681, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2021591125972153, 'n_estimators': 472, 'criterion': 'squared_error', 'ccp_alpha': 9.731013934510141, 'min_weight_fraction_leaf': 0.4998005062226735, 'max_features': 'auto', 'min_impurity_decrease': 2.6011241921041506e-07, 'validation_fraction': 0.9540041114852252, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:17:26,028] Trial 33 finished with value: 0.5 and parameters: {'subsample': 0.9269389459027624, 'learning_rate': 0.010873562385719666, 'dropout_rate': 0.33072602814097474, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 0.5001177901569112, 'min_weight_fraction_leaf': 0.4287857660972887, 'max_features': 'auto', 'min_impurity_decrease': 7.950238183861408e-07, 'validation_fraction': 0.82837726807294, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:18:24,355] Trial 34 finished with value: 0.5 and parameters: {'subsample': 0.6626677594044507, 'learning_rate': 0.016113697335551565, 'dropout_rate': 0.15034298582489583, 'n_estimators': 386, 'criterion': 'friedman_mse', 'ccp_alpha': 1.075022117996721, 'min_weight_fraction_leaf': 0.16467775935646276, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.7334666490017488, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 11, 'max_depth': 5}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.649402390438247
Fold 2 C-index: 0.6802325581395349
Fold 3 C-index: 0.6595744680851063
Fold 4 C-index: 0.6939163498098859
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 21:19:02,959] Trial 35 finished with value: 0.6696723635949839 and parameters: {'subsample': 0.6114116777400945, 'learning_rate': 0.054437786106373336, 'dropout_rate': 0.23585428053268853, 'n_estimators': 331, 'criterion': 'friedman_mse', 'ccp_alpha': 0.17218798253486745, 'min_weight_fraction_leaf': 0.36774952622841867, 'max_features': None, 'min_impurity_decrease': 2.440995345456354e-07, 'validation_fraction': 0.8853061347813449, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:19:35,400] Trial 36 finished with value: 0.5 and parameters: {'subsample': 0.6007341005701442, 'learning_rate': 0.05826981627285646, 'dropout_rate': 0.40991120855249724, 'n_estimators': 325, 'criterion': 'friedman_mse', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.37297762113648114, 'max_features': None, 'min_impurity_decrease': 2.033954345119292e-07, 'validation_fraction': 0.6013805146248444, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 18, 'max_depth': 18}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5

Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:19:55,901] Trial 37 finished with value: 0.5 and parameters: {'subsample': 0.6972617948861556, 'learning_rate': 0.05460066638134164, 'dropout_rate': 0.518754641115737, 'n_estimators': 307, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3154660033449486, 'min_weight_fraction_leaf': 0.2894016489320193, 'max_features': None, 'min_impurity_decrease': 1.0905009456555213e-07, 'validation_fraction': 0.8722204767958098, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 15, 'max_depth': 5}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:20:11,510] Trial 38 finished with value: 0.5 and parameters: {'subsample': 0.6042241842345398, 'learning_rate': 0.06699312756183548, 'dropout_rate': 0.7673236646699829, 'n_estimators': 359, 'criterion': 'friedman_mse', 'ccp_alpha': 0.5429360365034677, 'min_weight_fraction_leaf': 0.3408536656184234, 'max_features': None, 'min_impurity_decrease': 1.2577531588679714e-05, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 16, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:20:30,603] Trial 39 finished with value: 0.5 and parameters: {'subsample': 0.7162868070278713, 'learning_rate': 0.07741854767057152, 'dropout_rate': 0.29768975560951294, 'n_estimators': 240, 'criterion': 'friedman_mse', 'ccp_alpha': 2.846842081079357, 'min_weight_fraction_leaf': 0.2574201688995412, 'max_features': None, 'min_impurity_decrease': 3.135685232787251e-06, 'validation_fraction': 0.5164716588464817, 'min_samples_split': 10, 'max_leaf_nodes': 13, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:20:51,690] Trial 40 finished with value: 0.5 and parameters: {'subsample': 0.4692202785565428, 'learning_rate': 0.04100241199761595, 'dropout_rate': 0.3781690973136454, 'n_estimators': 272, 'criterion': 'friedman_mse', 'ccp_alpha': 3.771190152028044, 'min_weight_fraction_leaf': 0.2208231777876986, 'max_features': None, 'min_impurity_decrease': 8.473292089932365e-06, 'validation_fraction': 0.6187647988146615, 'min_samples_split': 13, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5255319148936171
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6072961373390557
[I 2024-04-14 21:22:08,891] Trial 41 finished with value: 0.637733354361669 and parameters: {'subsample': 0.8997879863238554, 'learning_rate': 0.02368846547972539, 'dropout_rate': 0.2172910652043255, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.4657295787481094, 'max_features': 'auto', 'min_impurity_decrease': 3.5396058259407833e-07, 'validation_fraction': 0.9548954079608488, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:23:10,352] Trial 42 finished with value: 0.5 and parameters: {'subsample': 0.9613417845095718, 'learning_rate': 0.007673205122337277, 'dropout_rate': 0.18737748771001767, 'n_estimators': 397, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6209714181337628, 'min_weight_fraction_leaf': 0.41852402513789905, 'max_features': 'auto', 'min_impurity_decrease': 9.241300018005784e-07, 'validation_fraction': 0.8967356708996139, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:24:20,185] Trial 43 finished with value: 0.5 and parameters: {'subsample': 0.5579790577196161, 'learning_rate': 0.06394713853774825, 'dropout_rate': 0.1388767921016552, 'n_estimators': 427, 'criterion': 'squared_error', 'ccp_alpha': 1.8212142196582026, 'min_weight_fraction_leaf': 0.4053933189589045, 'max_features': 1, 'min_impurity_decrease': 2.514193858366971e-07, 'validation_fraction': 0.7213817123678065, 'min_samples_split': 17, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:24:42,145] Trial 44 finished with value: 0.5 and parameters: {'subsample': 0.6432645105776923, 'learning_rate': 0.006240908059979385, 'dropout_rate': 0.6859431566383477, 'n_estimators': 348, 'criterion': 'squared_error', 'ccp_alpha': 0.3927903503796155, 'min_weight_fraction_leaf': 0.4414850125655836, 'max_features': 'auto', 'min_impurity_decrease': 0.00078866474186123, 'validation_fraction': 0.7941239261553803, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:25:51,720] Trial 45 finished with value: 0.5 and parameters: {'subsample': 0.809884615407807, 'learning_rate': 0.048453048884458026, 'dropout_rate': 0.24577900888130635, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 1.1472993277168393, 'min_weight_fraction_leaf': 0.48178993417768873, 'max_features': 0.1, 'min_impurity_decrease': 5.138129696047032e-07, 'validation_fraction': 0.9637666974356841, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 10}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6155378486055777
Fold 2 C-index: 0.7868217054263565
Fold 3 C-index: 0.6531914893617021
Fold 4 C-index: 0.7186311787072244
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 21:26:00,457] Trial 46 finished with value: 0.6964673457077258 and parameters: {'subsample': 0.9035029991499002, 'learning_rate': 0.05377375104309677, 'dropout_rate': 0.9694253886674298, 'n_estimators': 450, 'criterion': 'friedman_mse', 'ccp_alpha': 0.03525202624769574, 'min_weight_fraction_leaf': 0.3666298089106992, 'max_features': 'log2', 'min_impurity_decrease': 2.482390348219561e-06, 'validation_fraction': 0.8472602359999014, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:26:14,176] Trial 47 finished with value: 0.5 and parameters: {'subsample': 0.5223779429597124, 'learning_rate': 0.053196394932185635, 'dropout_rate': 0.70275818612764, 'n_estimators': 311, 'criterion': 'friedman_mse', 'ccp_alpha': 1.7367392845248242, 'min_weight_fraction_leaf': 0.36842596123645754, 'max_features': 'log2', 'min_impurity_decrease': 2.2130001167649176e-06, 'validation_fraction': 0.8419754547666245, 'min_samples_split': 2, 'max_leaf_nodes': 12, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:26:14,439] Trial 48 finished with value: 0.5 and parameters: {'subsample': 0.9854905905033491, 'learning_rate': 0.07499367009362275, 'dropout_rate': 0.8195624802251275, 'n_estimators': 8, 'criterion': 'friedman_mse', 'ccp_alpha': 0.8917240337073891, 'min_weight_fraction_leaf': 0.32965788605028784, 'max_features': 'log2', 'min_impurity_decrease': 1.2225255641975854e-06, 'validation_fraction': 0.8455422941346799, 'min_samples_split': 19, 'max_leaf_nodes': 14, 'min_samples_leaf': 17, 'max_depth': 16}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5

Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:26:24,515] Trial 49 finished with value: 0.5 and parameters: {'subsample': 0.7928982153787437, 'learning_rate': 0.0628925305235457, 'dropout_rate': 0.9570755199206264, 'n_estimators': 410, 'criterion': 'friedman_mse', 'ccp_alpha': 6.659192684443452, 'min_weight_fraction_leaf': 0.2912761936263655, 'max_features': 'log2', 'min_impurity_decrease': 1.743578448308132e-07, 'validation_fraction': 0.42748211202843867, 'min_samples_split': 4, 'max_leaf_nodes': 15, 'min_samples_leaf': 9, 'max_depth': 12}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:27:05,024] Trial 50 finished with value: 0.5 and parameters: {'subsample': 0.8511494628607659, 'learning_rate': 0.04091234090749085, 'dropout_rate': 0.6291546211472798, 'n_estimators': 480, 'criterion': 'friedman_mse', 'ccp_alpha': 1.3913441236862976, 'min_weight_fraction_leaf': 0.09680305394501165, 'max_features': 'log2', 'min_impurity_decrease': 2.274738198457575e-05, 'validation_fraction': 0.5545404177484662, 'min_samples_split': 11, 'max_leaf_nodes': 11, 'min_samples_leaf': 20, 'max_depth': 7}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6414342629482072
Fold 2 C-index: 0.7693798449612403
Fold 3 C-index: 0.5957446808510638
Fold 4 C-index: 0.6825095057034221
Fold 5 C-index: 0.6802575107296137
[I 2024-04-14 21:27:45,833] Trial 51 finished with value: 0.6738651610387094 and parameters: {'subsample': 0.9115121046901732, 'learning_rate': 0.05845917620681425, 'dropout_rate': 0.5540004810661991, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.04660345139175148, 'min_weight_fraction_leaf': 0.40812087314396844, 'max_features': 'sqrt', 'min_impurity_decrease': 7.767904466636394e-05, 'validation_fraction': 0.9492491267325289, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:28:04,013] Trial 52 finished with value: 0.5 and parameters: {'subsample': 0.9606972190963244, 'learning_rate': 0.058532095704419335, 'dropout_rate': 0.8655167247735727, 'n_estimators': 499, 'criterion': 'friedman_mse', 'ccp_alpha': 0.42267254326215464, 'min_weight_fraction_leaf': 0.35711614532127833, 'max_features': 'sqrt', 'min_impurity_decrease': 0.003049302929929116, 'validation_fraction': 0.985072081707868, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7674418604651163
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.7243346007604563
Fold 5 C-index: 0.7081545064377682
[I 2024-04-14 21:28:50,140] Trial 53 finished with value: 0.691205995177154 and parameters: {'subsample': 0.924085737836479, 'learning_rate': 0.05191355349770248, 'dropout_rate': 0.5292561748188663, 'n_estimators': 457, 'criterion': 'squared_error', 'ccp_alpha': 0.009828495801242839, 'min_weight_fraction_leaf': 0.3940618917042797, 'max_features': 'sqrt', 'min_impurity_decrease': 5.891874821169929e-05, 'validation_fraction': 0.9257611975304009, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:29:29,427] Trial 54 finished with value: 0.5 and parameters: {'subsample': 0.8842518374616221, 'learning_rate': 0.04642759977764528, 'dropout_rate': 0.5787056799551111, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.8043967529855988, 'min_weight_fraction_leaf': 0.39749144390795427, 'max_features': 'sqrt', 'min_impurity_decrease': 6.674900997744521e-05, 'validation_fraction': 0.9987906743578988, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:29:44,253] Trial 55 finished with value: 0.5 and parameters: {'subsample': 0.9338509253358491, 'learning_rate': 0.05026798356278357, 'dropout_rate': 0.8859792395781099, 'n_estimators': 456, 'criterion': 'squared_error', 'ccp_alpha': 2.0925706859481137, 'min_weight_fraction_leaf': 0.15390921956023235, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00018865565560969203, 'validation_fraction': 0.9220343002247878, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:30:28,811] Trial 56 finished with value: 0.5 and parameters: {'subsample': 0.8543724704763108, 'learning_rate': 0.07231303541927657, 'dropout_rate': 0.534386653988483, 'n_estimators': 484, 'criterion': 'squared_error', 'ccp_alpha': 0.3004273858397456, 'min_weight_fraction_leaf': 0.19369329911983815, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00012611033221339828, 'validation_fraction': 0.6860217015765494, 'min_samples_split': 15, 'max_leaf_nodes': 10, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.601593625498008
Fold 2 C-index: 0.7441860465116279
Fold 3 C-index: 0.6170212765957447
Fold 4 C-index: 0.714828897338403
Fold 5 C-index: 0.6952789699570815
[I 2024-04-14 21:30:34,291] Trial 57 finished with value: 0.6745817631801729 and parameters: {'subsample': 0.9087026240599475, 'learning_rate': 0.08124746006044987, 'dropout_rate': 0.997784793728882, 'n_estimators': 391, 'criterion': 'squared_error', 'ccp_alpha': 0.001956726907500393, 'min_weight_fraction_leaf': 0.410591151226506, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00033059213660683115, 'validation_fraction': 0.8063875242325604, 'min_samples_split': 18, 'max_leaf_nodes': 12, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:30:40,576] Trial 58 finished with value: 0.5 and parameters: {'subsample': 0.8212698530092863, 'learning_rate': 0.09011651240953941, 'dropout_rate': 0.9967495872781945, 'n_estimators': 402, 'criterion': 'squared_error', 'ccp_alpha': 1.181840851947653, 'min_weight_fraction_leaf': 0.4057697411163346, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0005537548403589421, 'validation_fraction': 0.8125246339086644, 'min_samples_split': 16, 'max_leaf_nodes': 12, 'min_samples_leaf': 20, 'max_depth': 5}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:30:50,042] Trial 59 finished with value: 0.5 and parameters: {'subsample': 0.9193087392842657, 'learning_rate': 0.0872713586054678, 'dropout_rate': 0.9474892480356638, 'n_estimators': 380, 'criterion': 'squared_error', 'ccp_alpha': 8.343149270456218, 'min_weight_fraction_leaf': 0.3337975605954647, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00021385037088054892, 'validation_fraction': 0.7937489212794213, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:30:52,317] Trial 60 finished with value: 0.5 and parameters: {'subsample': 0.7446094350786215, 'learning_rate': 0.09733264341118891, 'dropout_rate': 0.9841116957888287, 'n_estimators': 175, 'criterion': 'squared_error', 'ccp_alpha': 0.6816514323618716, 'min_weight_fraction_leaf': 0.21423049941460018, 'max_features': 'sqrt', 'min_impurity_decrease': 6.668735628479151e-05, 'validation_fraction': 0.7693486777346097, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:31:12,808] Trial 61 finished with value: 0.5 and parameters: {'subsample': 0.953217517548262, 'learning_rate': 0.079755577636651, 'dropout_rate': 0.9141007682217919, 'n_estimators': 461, 'criterion': 'squared_error', 'ccp_alpha': 0.3409580267399826, 'min_weight_fraction_leaf': 0.3860962100040052, 'max_features': 'sqrt', 'min_impurity_decrease': 0.00041666520721794905, 'validation_fraction': 0.960062895620913, 'min_samples_split': 19, 'max_leaf_nodes': 7, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6294820717131474
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5340425531914894
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6351931330472103
[I 2024-04-14 21:31:40,190] Trial 62 finished with value: 0.6496011871019088 and parameters: {'subsample': 0.9950153281899117, 'learning_rate': 0.08115591715872426, 'dropout_rate': 0.8285090704895912, 'n_estimators': 432, 'criterion': 'squared_error', 'ccp_alpha': 0.022737959076050005, 'min_weight_fraction_leaf': 0.46340528439350875, 'max_features': 'sqrt', 'min_impurity_decrease': 0.002070496973827786, 'validation_fraction': 0.8636512797881153, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 17, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:32:11,117] Trial 63 finished with value: 0.5 and parameters: {'subsample': 0.8958049100803265, 'learning_rate': 0.03463669561235694, 'dropout_rate': 0.727101025098758, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.8464623473284673, 'min_weight_fraction_leaf': 0.4135255090970029, 'max_features': 'sqrt', 'min_impurity_decrease': 0.011491466743305267, 'validation_fraction': 0.9003782170657106, 'min_samples_split': 8, 'max_leaf_nodes': 14, 'min_samples_leaf': 19, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:32:47,014] Trial 64 finished with value: 0.5 and parameters: {'subsample': 0.9999501074035284, 'learning_rate': 0.04343946750155403, 'dropout_rate': 0.6492592507323621, 'n_estimators': 486, 'criterion': 'squared_error', 'ccp_alpha': 1.5874488463106935, 'min_weight_fraction_leaf': 0.4319249528372747, 'max_features': 0.1, 'min_impurity_decrease': 0.0002890144110563875, 'validation_fraction': 0.9429801041318471, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:33:28,784] Trial 65 finished with value: 0.5 and parameters: {'subsample': 0.2342466559277479, 'learning_rate': 0.06303630401036493, 'dropout_rate': 0.4417348311096751, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 0.002720872474292621, 'min_weight_fraction_leaf': 0.3184132029860019, 'max_features': 1, 'min_impurity_decrease': 4.074489031583919e-05, 'validation_fraction': 0.2977145351524674, 'min_samples_split': 19, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:34:00,710] Trial 66 finished with value: 0.5 and parameters: {'subsample': 0.864043638107774, 'learning_rate': 0.06872484468207417, 'dropout_rate': 0.5072595744981533, 'n_estimators': 386, 'criterion': 'squared_error', 'ccp_alpha': 0.5322457636613249, 'min_weight_fraction_leaf': 0.38588320322553227, 'max_features': 'log2', 'min_impurity_decrease': 1.4582092932987181e-05, 'validation_fraction': 0.7083652644214015, 'min_samples_split': 17, 'max_leaf_nodes': 8, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:34:51,607] Trial 67 finished with value: 0.5 and parameters: {'subsample': 0.923972441287973, 'learning_rate': 0.006346393214351089, 'dropout_rate': 0.3626590313691083, 'n_estimators': 433, 'criterion': 'squared_error', 'ccp_alpha': 1.0775536270043082, 'min_weight_fraction_leaf': 0.29950042453298076, 'max_features': 'auto', 'min_impurity_decrease': 8.224117767206645e-05, 'validation_fraction': 0.6414462333303239, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:36:04,015] Trial 68 finished with value: 0.5 and parameters: {'subsample': 0.8273559517880378, 'learning_rate': 0.004436959478071222, 'dropout_rate': 0.1692459694312764, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.2962174055051826, 'min_weight_fraction_leaf': 0.48077549565405187, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0012848816946434004, 'validation_fraction': 0.9125972358312673, 'min_samples_split': 19, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:36:42,725] Trial 69 finished with value: 0.5 and parameters: {'subsample': 0.39517199438843464, 'learning_rate': 0.001319941290472186, 'dropout_rate': 0.5748763194202667, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 2.1869784288663223, 'min_weight_fraction_leaf': 0.35334166011937607, 'max_features': 'auto', 'min_impurity_decrease': 7.682400459075484e-06, 'validation_fraction': 0.9772384304934929, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:37:51,038] Trial 70 finished with value: 0.5 and parameters: {'subsample': 0.7902347436599237, 'learning_rate': 0.014080040753655973, 'dropout_rate': 0.10940958461697153, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 0.8396587812352148, 'min_weight_fraction_leaf': 0.238763366841546, 'max_features': 'sqrt', 'min_impurity_decrease': 0.0001237023227765934, 'validation_fraction': 0.8596914865720219, 'min_samples_split': 20, 'max_leaf_nodes': 10, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:38:33,568] Trial 71 finished with value: 0.5 and parameters: {'subsample': 0.6431334798178059, 'learning_rate': 0.06024115324576953, 'dropout_rate': 0.24287017345333597, 'n_estimators': 370, 'criterion': 'friedman_mse', 'ccp_alpha': 0.26089086292677216, 'min_weight_fraction_leaf': 0.3649619980487348, 'max_features': None, 'min_impurity_decrease': 1.41859363723174e-07, 'validation_fraction': 0.8883756518074789, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6972111553784861
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.6425531914893617
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 21:39:18,255] Trial 72 finished with value: 0.6864698923531024 and parameters: {'subsample': 0.956246320654329, 'learning_rate': 0.05367018411990536, 'dropout_rate': 0.2820686706759248, 'n_estimators': 397, 'criterion': 'squared_error', 'ccp_alpha': 0.004921143011242177, 'min_weight_fraction_leaf': 0.27560434856342986, 'max_features': None, 'min_impurity_decrease': 4.793796626628938e-07, 'validation_fraction': 0.936922237016099, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 15, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:40:17,116] Trial 73 finished with value: 0.5 and parameters: {'subsample': 0.9513472273109285, 'learning_rate': 0.05500529601036367, 'dropout_rate': 0.36060562220894815, 'n_estimators': 487, 'criterion': 'squared_error', 'ccp_alpha': 0.5905973560961533, 'min_weight_fraction_leaf': 0.259787767977606, 'max_features': 'auto', 'min_impurity_decrease': 5.551082218031582e-07, 'validation_fraction': 0.9389876549930612, 'min_samples_split': 18, 'max_leaf_nodes': 13, 'min_samples_leaf': 18, 'max_depth': 1}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:40:55,337] Trial 74 finished with value: 0.5 and parameters: {'subsample': 0.9008905344726109, 'learning_rate': 0.052527844837721896, 'dropout_rate': 0.2706903511005798, 'n_estimators': 352, 'criterion': 'squared_error', 'ccp_alpha': 1.3088454738301425, 'min_weight_fraction_leaf': 0.2784197682287948, 'max_features': 'log2', 'min_impurity_decrease': 4.080782453770548e-07, 'validation_fraction': 0.8229275455579805, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 5}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.7071713147410359
Fold 2 C-index: 0.7306201550387597
Fold 3 C-index: 0.6021276595744681
Fold 4 C-index: 0.7167300380228137
Fold 5 C-index: 0.6373390557939914
[I 2024-04-14 21:41:41,789] Trial 75 finished with value: 0.6787976446342137 and parameters: {'subsample': 0.9693250170531542, 'learning_rate': 0.04881287672496263, 'dropout_rate': 0.3139180788978998, 'n_estimators': 396, 'criterion': 'squared_error', 'ccp_alpha': 0.0090859650188881, 'min_weight_fraction_leaf': 0.31148215666130263, 'max_features': 'auto', 'min_impurity_decrease': 4.360845000758654e-06, 'validation_fraction': 0.9980785900823812, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:42:27,610] Trial 76 finished with value: 0.5 and parameters: {'subsample': 0.9607643120814894, 'learning_rate': 0.051511476416926376, 'dropout_rate': 0.30817242378089477, 'n_estimators': 401, 'criterion': 'squared_error', 'ccp_alpha': 0.32366698378279035, 'min_weight_fraction_leaf': 0.00278854120480998, 'max_features': None, 'min_impurity_decrease': 2.6311644914274462e-06, 'validation_fraction': 0.9681746165765701, 'min_samples_split': 16, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:43:01,902] Trial 77 finished with value: 0.5 and parameters: {'subsample': 0.8757948426417032, 'learning_rate': 0.05708163616109238, 'dropout_rate': 0.4328147804871142, 'n_estimators': 371, 'criterion': 'squared_error', 'ccp_alpha': 0.6023855308201027, 'min_weight_fraction_leaf': 0.3089634184008858, 'max_features': 'auto', 'min_impurity_decrease': 4.056046954676907e-06, 'validation_fraction': 0.9094500226195809, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 9 with value: 0.6985461379550671.
Fold 1 C-index: 0.6573705179282868
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.7446808510638298
Fold 4 C-index: 0.7490494296577946
Fold 5 C-index: 0.7467811158798283
[I 2024-04-14 21:43:45,943] Trial 78 finished with value: 0.7384911115881184 and parameters: {'subsample': 0.9115482308909325, 'learning_rate': 0.03772869943983537, 'dropout_rate': 0.3476599176890519, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.2716607703914049, 'max_features': 1, 'min_impurity_decrease': 1.0180375358163635e-06, 'validation_fraction': 0.9423719780700139, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:44:28,420] Trial 79 finished with value: 0.5 and parameters: {'subsample': 0.35510503842155305, 'learning_rate': 0.028164390492977597, 'dropout_rate': 0.34802656513805996, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0546158595316648, 'min_weight_fraction_leaf': 0.26783577777991785, 'max_features': 1, 'min_impurity_decrease': 1.232433468024114e-06, 'validation_fraction': 0.7655815853449542, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:45:05,937] Trial 80 finished with value: 0.5 and parameters: {'subsample': 0.9359531066095086, 'learning_rate': 0.01997306530740024, 'dropout_rate': 0.28829477813771426, 'n_estimators': 345, 'criterion': 'squared_error', 'ccp_alpha': 5.782208431977321, 'min_weight_fraction_leaf': 0.22963341515836005, 'max_features': 1, 'min_impurity_decrease': 9.393313457224091e-07, 'validation_fraction': 0.8784998948355119, 'min_samples_split': 17, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 4}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.6553784860557769
Fold 2 C-index: 0.7945736434108527
Fold 3 C-index: 0.725531914893617
Fold 4 C-index: 0.7680608365019012
Fold 5 C-index: 0.740343347639485
[I 2024-04-14 21:45:48,459] Trial 81 finished with value: 0.7367776457003266 and parameters: {'subsample': 0.9781847092859919, 'learning_rate': 0.04920429651099207, 'dropout_rate': 0.3925565836229571, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 0.02620579447326436, 'min_weight_fraction_leaf': 0.2714879663110738, 'max_features': 1, 'min_impurity_decrease': 1.8660886328239897e-06, 'validation_fraction': 0.9323296462361479, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:46:35,112] Trial 82 finished with value: 0.5 and parameters: {'subsample': 0.9724434639127338, 'learning_rate': 0.04881374767128929, 'dropout_rate': 0.3977769062247469, 'n_estimators': 415, 'criterion': 'squared_error', 'ccp_alpha': 0.29362607241963007, 'min_weight_fraction_leaf': 0.27382548419686714, 'max_features': 1, 'min_impurity_decrease': 5.257661092179595e-06, 'validation_fraction': 0.9239279962752922, 'min_samples_split': 3, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:47:18,463] Trial 83 finished with value: 0.5 and parameters: {'subsample': 0.9430168110621091, 'learning_rate': 0.04384912582199689, 'dropout_rate': 0.3293861499959515, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.7277573994585262, 'min_weight_fraction_leaf': 0.3228018134171798, 'max_features': 1, 'min_impurity_decrease': 2.0144429209627664e-06, 'validation_fraction': 0.9808779139542445, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 3}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:47:55,042] Trial 84 finished with value: 0.5 and parameters: {'subsample': 0.837607364913803, 'learning_rate': 0.03893576593334247, 'dropout_rate': 0.305574256636177, 'n_estimators': 359, 'criterion': 'squared_error', 'ccp_alpha': 0.4329810490177594, 'min_weight_fraction_leaf': 0.24329128027889632, 'max_features': 1, 'min_impurity_decrease': 1.1290333292741617e-06, 'validation_fraction': 0.8368533116927852, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 78 with value: 0.7384911115881184.

Fold 1 C-index: 0.6135458167330677
Fold 2 C-index: 0.7984496124031008
Fold 3 C-index: 0.7021276595744681
Fold 4 C-index: 0.7376425855513308
Fold 5 C-index: 0.7725321888412017
[I 2024-04-14 21:48:48,807] Trial 85 finished with value: 0.7248595726206337 and parameters: {'subsample': 0.9790364223563408, 'learning_rate': 0.032119492652033454, 'dropout_rate': 0.26298993005971005, 'n_estimators': 434, 'criterion': 'squared_error', 'ccp_alpha': 0.011637416243612385, 'min_weight_fraction_leaf': 0.28585954415962, 'max_features': 1, 'min_impurity_decrease': 6.341121592545689e-07, 'validation_fraction': 0.999563171528363, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:49:40,550] Trial 86 finished with value: 0.5 and parameters: {'subsample': 0.10080183348079819, 'learning_rate': 0.03357624070949028, 'dropout_rate': 0.26370671071190227, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 1.5340768497053712, 'min_weight_fraction_leaf': 0.25344502400479, 'max_features': 1, 'min_impurity_decrease': 6.991062032815163e-07, 'validation_fraction': 0.9372587806880348, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 4}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:50:32,814] Trial 87 finished with value: 0.5 and parameters: {'subsample': 0.9775029338505961, 'learning_rate': 0.04874207862479087, 'dropout_rate': 0.21868823895689093, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 0.9041328031165503, 'min_weight_fraction_leaf': 0.29674028783366374, 'max_features': 1, 'min_impurity_decrease': 1.5678874658079375e-06, 'validation_fraction': 0.9991265181296115, 'min_samples_split': 13, 'max_leaf_nodes': 17, 'min_samples_leaf': 17, 'max_depth': 5}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:50:52,407] Trial 88 finished with value: 0.5 and parameters: {'subsample': 0.8827195335108419, 'learning_rate': 0.04531670901602254, 'dropout_rate': 0.38362769362651744, 'n_estimators': 284, 'criterion': 'squared_error', 'ccp_alpha': 0.31963304083956173, 'min_weight_fraction_leaf': 0.2846532160633457, 'max_features': 1, 'min_impurity_decrease': 3.0142699671472754e-06, 'validation_fraction': 0.9628547751439464, 'min_samples_split': 6, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 8}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:50:56,286] Trial 89 finished with value: 0.5 and parameters: {'subsample': 0.9815904423856916, 'learning_rate': 0.030691451316405657, 'dropout_rate': 0.4106823803489017, 'n_estimators': 126, 'criterion': 'squared_error', 'ccp_alpha': 0.6289674109876843, 'min_weight_fraction_leaf': 0.2106777284879945, 'max_features': 1, 'min_impurity_decrease': 6.774012211188089e-07, 'validation_fraction': 0.8962705191374644, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:51:47,867] Trial 90 finished with value: 0.5 and parameters: {'subsample': 0.1430413165132784, 'learning_rate': 0.03781652109179391, 'dropout_rate': 0.3452472213551716, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.1817088382552795, 'min_weight_fraction_leaf': 0.2665008780429924, 'max_features': 1, 'min_impurity_decrease': 5.6856741000170754e-06, 'validation_fraction': 0.9989504839346807, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.6713147410358565
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7425531914893617
Fold 4 C-index: 0.7110266159695817
Fold 5 C-index: 0.6351931330472103
[I 2024-04-14 21:52:46,608] Trial 91 finished with value: 0.7031803270060764 and parameters: {'subsample': 0.914361253388594, 'learning_rate': 0.041001495437605215, 'dropout_rate': 0.2632998180358661, 'n_estimators': 435, 'criterion': 'squared_error', 'ccp_alpha': 0.03786277950879616, 'min_weight_fraction_leaf': 0.2277013916825244, 'max_features': 0.1, 'min_impurity_decrease': 0.08577320044011032, 'validation_fraction': 0.860803260236799, 'min_samples_split': 18, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:53:50,979] Trial 92 finished with value: 0.5 and parameters: {'subsample': 0.9422636593031991, 'learning_rate': 0.04083233646714493, 'dropout_rate': 0.2582610898844707, 'n_estimators': 441, 'criterion': 'squared_error', 'ccp_alpha': 0.20594179048085923, 'min_weight_fraction_leaf': 0.22696842212600565, 'max_features': 0.1, 'min_impurity_decrease': 0.030013118783166835, 'validation_fraction': 0.9374816210127846, 'min_samples_split': 19, 'max_leaf_nodes': 15, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:54:50,808] Trial 93 finished with value: 0.5 and parameters: {'subsample': 0.9162398046810232, 'learning_rate': 0.04261278407178158, 'dropout_rate': 0.29072051537906707, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.5246182006415491, 'min_weight_fraction_leaf': 0.18496719488857288, 'max_features': 0.1, 'min_impurity_decrease': 3.1064678849646776e-07, 'validation_fraction': 0.9778600636407362, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 17, 'max_depth': 3}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:55:46,224] Trial 94 finished with value: 0.5 and parameters: {'subsample': 0.972484167380033, 'learning_rate': 0.02377569250877797, 'dropout_rate': 0.22129409679337572, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.7888161896974057, 'min_weight_fraction_leaf': 0.24520689700163756, 'max_features': 0.1, 'min_impurity_decrease': 2.220594655309382e-06, 'validation_fraction': 0.861898005066742, 'min_samples_split': 17, 'max_leaf_nodes': 17, 'min_samples_leaf': 10, 'max_depth': 4}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:56:52,544] Trial 95 finished with value: 0.5 and parameters: {'subsample': 0.8640339394848673, 'learning_rate': 0.047055105402553865, 'dropout_rate': 0.3204019549752588, 'n_estimators': 436, 'criterion': 'squared_error', 'ccp_alpha': 1.2262578621891786, 'min_weight_fraction_leaf': 0.2819750333077766, 'max_features': 'auto', 'min_impurity_decrease': 9.63844798148473e-07, 'validation_fraction': 0.9010989968293432, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.6533864541832669
Fold 2 C-index: 0.7558139534883721
Fold 3 C-index: 0.7404255319148936
Fold 4 C-index: 0.7718631178707225
Fold 5 C-index: 0.721030042918455
[I 2024-04-14 21:58:04,020] Trial 96 finished with value: 0.728503820075142 and parameters: {'subsample': 0.8921334562375532, 'learning_rate': 0.035631627683985666, 'dropout_rate': 0.17499550333402586, 'n_estimators': 416, 'criterion': 'squared_error', 'ccp_alpha': 0.030615170758861943, 'min_weight_fraction_leaf': 0.20561252137367714, 'max_features': 0.1, 'min_impurity_decrease': 1.9947761093654924e-07, 'validation_fraction': 0.9524916937730252, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 16}. Best is trial 78 with value: 0.7384911115881184.

Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 21:59:33,178] Trial 97 finished with value: 0.5 and parameters: {'subsample': 0.8876336701050086, 'learning_rate': 0.0354485400473523, 'dropout_rate': 0.18559666508088146, 'n_estimators': 464, 'criterion': 'squared_error', 'ccp_alpha': 0.44425581083749544, 'min_weight_fraction_leaf': 0.20813849805475523, 'max_features': 0.1, 'min_impurity_decrease': 1.801861045586562e-07, 'validation_fraction': 0.9178747066969026, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 12}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5
Fold 5 C-index: 0.5
[I 2024-04-14 22:00:38,515] Trial 98 finished with value: 0.5 and parameters: {'subsample': 0.928099598455983, 'learning_rate': 0.03287645835309895, 'dropout_rate': 0.17569146429939028, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 9.922183986862624, 'min_weight_fraction_leaf': 0.23083966071422962, 'max_features': 0.1, 'min_impurity_decrease': 0.06003321525310818, 'validation_fraction': 0.9553833709976116, 'min_samples_split': 16, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 18}. Best is trial 78 with value: 0.7384911115881184.
Fold 1 C-index: 0.5
Fold 2 C-index: 0.5
Fold 3 C-index: 0.5
Fold 4 C-index: 0.5

[I 2024-04-14 22:01:30,757] A new study created in memory with name: no-name-bd685965-c53f-4954-b21e-5d842989af68

Fold 5 C-index: 0.5
[I 2024-04-14 22:01:30,724] Trial 99 finished with value: 0.5 and parameters: {'subsample': 0.7984456569855936, 'learning_rate': 0.026418588623478744, 'dropout_rate': 0.4577965489047534, 'n_estimators': 489, 'criterion': 'friedman_mse', 'ccp_alpha': 0.18730653295323416, 'min_weight_fraction_leaf': 0.1540153661268454, 'max_features': 0.1, 'min_impurity_decrease': 5.047303300728639e-07, 'validation_fraction': 0.8766522685364697, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 16}. Best is trial 78 with value: 0.7384911115881184.


* Best trial for C-index:
 FrozenTrial(number=78, state=TrialState.COMPLETE, values=[0.7384911115881184], datetime_start=datetime.datetime(2024, 4, 14, 21, 43, 1, 909764), datetime_complete=datetime.datetime(2024, 4, 14, 21, 43, 45, 941566), params={'subsample': 0.9115482308909325, 'learning_rate': 0.03772869943983537, 'dropout_rate': 0.3476599176890519, 'n_estimators': 392, 'criterion': 'squared_error', 'ccp_alpha': 0.02313127962403605, 'min_weight_fraction_leaf': 0.2716607703914049, 'max_features': 1, 'min_impurity_decrease': 1.0180375358163635e-06, 'validation_fraction': 0.9423719780700139, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 18, 'max_depth': 4}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=78, value=None)


* Best Score for C-index:
 0.7384911115881184

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:01:52,903] Trial 0 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7268222670380755, 'learning_rate': 0.02932779416008757, 'dropout_rate': 0.3041663082077828, 'n_estimators': 276, 'criterion': 'friedman_mse', 'ccp_alpha': 9.807641983846155, 'min_weight_fraction_leaf': 0.34241486929243165, 'max_features': None, 'min_impurity_decrease': 2.4449249473284515e-05, 'validation_fraction': 0.7379954057320357, 'min_samples_split': 5, 'max_leaf_nodes': 5, 'min_samples_leaf': 11, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:02:03,391] Trial 1 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6709608626961889, 'learning_rate': 0.08509374761370117, 'dropout_rate': 0.7520097923745717, 'n_estimators': 306, 'criterion': 'friedman_mse', 'ccp_alpha': 3.617886556223141, 'min_weight_fraction_leaf': 0.11413161543947781, 'max_features': 'sqrt', 'min_impurity_decrease': 3.589068454832194e-05, 'validation_fraction': 0.3122612229724653, 'min_samples_split': 10, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:02:12,820] Trial 2 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6615576566129001, 'learning_rate': 0.012446221112850278, 'dropout_rate': 0.3855569336382888, 'n_estimators': 208, 'criterion': 'friedman_mse', 'ccp_alpha': 4.830342642627043, 'min_weight_fraction_leaf': 0.4927798928053525, 'max_features': None, 'min_impurity_decrease': 1.139155477212975e-05, 'validation_fraction': 0.3041207890271841, 'min_samples_split': 9, 'max_leaf_nodes': 14, 'min_samples_leaf': 18, 'max_depth': 11}. Best is trial 0 with value: 0.23592784351233073.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:02:31,293] Trial 3 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7023824046660451, 'learning_rate': 0.059007718703659076, 'dropout_rate': 0.6624131518860399, 'n_estimators': 338, 'criterion': 'friedman_mse', 'ccp_alpha': 7.636828414433382, 'min_weight_fraction_leaf': 0.121833187268437, 'max_features': None, 'min_impurity_decrease': 1.2496121527731156e-07, 'validation_fraction': 0.5944318794450425, 'min_samples_split': 12, 'max_leaf_nodes': 5, 'min_samples_leaf': 4, 'max_depth': 14}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:02:38,486] Trial 4 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.38688978374368876, 'learning_rate': 0.06950505925765015, 'dropout_rate': 0.5989449247459949, 'n_estimators': 195, 'criterion': 'friedman_mse', 'ccp_alpha': 3.573975666831762, 'min_weight_fraction_leaf': 0.021795731899520276, 'max_features': None, 'min_impurity_decrease': 0.0003622942983888231, 'validation_fraction': 0.6917017987001771, 'min_samples_split': 4, 'max_leaf_nodes': 9, 'min_samples_leaf': 5, 'max_depth': 7}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:02:40,257] Trial 5 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.561815338779102, 'learning_rate': 0.06699583046624309, 'dropout_rate': 0.19531763655113243, 'n_estimators': 66, 'criterion': 'squared_error', 'ccp_alpha': 8.46506225270722, 'min_weight_fraction_leaf': 0.2766286723983567, 'max_features': 'auto', 'min_impurity_decrease': 1.0765273688465228e-05, 'validation_fraction': 0.5523700752940731, 'min_samples_split': 12, 'max_leaf_nodes': 11, 'min_samples_leaf': 1, 'max_depth': 20}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:02:57,649] Trial 6 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9148074180954489, 'learning_rate': 0.021555950258436127, 'dropout_rate': 0.3632404715131823, 'n_estimators': 261, 'criterion': 'squared_error', 'ccp_alpha': 2.575420641540831, 'min_weight_fraction_leaf': 0.28217952146239084, 'max_features': 1, 'min_impurity_decrease': 0.07963970730486686, 'validation_fraction': 0.07936579037801572, 'min_samples_split': 10, 'max_leaf_nodes': 5, 'min_samples_leaf': 10, 'max_depth': 11}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:03:02,364] Trial 7 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.1839940393328387, 'learning_rate': 0.03038921677258727, 'dropout_rate': 0.9348258161369327, 'n_estimators': 285, 'criterion': 'squared_error', 'ccp_alpha': 7.418621518420373, 'min_weight_fraction_leaf': 0.024289516422134394, 'max_features': 'sqrt', 'min_impurity_decrease': 0.000980773656231882, 'validation_fraction': 0.11139217160771575, 'min_samples_split': 14, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:03:02,890] Trial 8 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4943929459395022, 'learning_rate': 0.07674451342869135, 'dropout_rate': 0.6090778011032946, 'n_estimators': 43, 'criterion': 'squared_error', 'ccp_alpha': 3.3706638344760997, 'min_weight_fraction_leaf': 0.46378828978769476, 'max_features': 0.1, 'min_impurity_decrease': 0.028789223922376057, 'validation_fraction': 0.12863119750938, 'min_samples_split': 3, 'max_leaf_nodes': 4, 'min_samples_leaf': 8, 'max_depth': 9}. Best is trial 3 with value: 0.2359278435123307.
Fold 1 IBS: 0.24598314958816228
Fold 2 IBS: 0.23034970779735023
Fold 3 IBS: 0.2286602815881347
Fold 4 IBS: 0.24087385240755274
Fold 5 IBS: 0.22857650220616926
[I 2024-04-14 22:03:45,613] Trial 9 finished with value: 0.23488869871747386 and parameters: {'subsample': 0.6059965408578151, 'learning_rate': 0.013102111413618, 'dropout_rate': 0.28125955124323376, 'n_estimators': 406, 'criterion': 'squared_error', 'ccp_alpha': 0.07426378544613033, 'min_weight_fraction_leaf': 0.27579636299120275, 'max_features': 'auto', 'min_impurity_decrease': 1.4994028685178666e-07, 'validation_fraction': 0.6359003593513561, 'min_samples_split': 2, 'max_leaf_nodes': 16, 'min_samples_leaf': 10, 'max_depth': 3}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24677184466891003
Fold 2 IBS: 0.2316615258034594
Fold 3 IBS: 0.22891402239382141
Fold 4 IBS: 0.24164907810183034
Fold 5 IBS: 0.2291762528827903
[I 2024-04-14 22:05:09,285] Trial 10 finished with value: 0.2356345447701623 and parameters: {'subsample': 0.985919291330434, 'learning_rate': 0.001978698361179733, 'dropout_rate': 0.1492094724532367, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 0.064533742198293, 'min_weight_fraction_leaf': 0.3875179554315872, 'max_features': 'auto', 'min_impurity_decrease': 1.349041793173596e-07, 'validation_fraction': 0.998633732405058, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:06:41,558] Trial 11 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9974069032156301, 'learning_rate': 0.006595153873193416, 'dropout_rate': 0.11379276107227315, 'n_estimators': 494, 'criterion': 'squared_error', 'ccp_alpha': 0.16077304413945637, 'min_weight_fraction_leaf': 0.39306717422587795, 'max_features': 'auto', 'min_impurity_decrease': 1.437080459422343e-07, 'validation_fraction': 0.9895723509465364, 'min_samples_split': 20, 'max_leaf_nodes': 15, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24714052976423928
Fold 2 IBS: 0.23184731742475803
Fold 3 IBS: 0.2289550691998775
Fold 4 IBS: 0.2418708580239349
Fold 5 IBS: 0.22931391583966804
[I 2024-04-14 22:07:43,633] Trial 12 finished with value: 0.23582553805049558 and parameters: {'subsample': 0.873850481285158, 'learning_rate': 0.0012227187192111223, 'dropout_rate': 0.2527776031497929, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.058133567268478875, 'min_weight_fraction_leaf': 0.2151989029549357, 'max_features': 'auto', 'min_impurity_decrease': 1.5094636128058346e-06, 'validation_fraction': 0.9945176333416724, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:08:11,316] Trial 13 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.3002626528752279, 'learning_rate': 0.0399128250234414, 'dropout_rate': 0.47793429123548903, 'n_estimators': 394, 'criterion': 'squared_error', 'ccp_alpha': 1.5257399290031846, 'min_weight_fraction_leaf': 0.3862797379871147, 'max_features': 'log2', 'min_impurity_decrease': 1.107247536942129e-06, 'validation_fraction': 0.8158912512725045, 'min_samples_split': 16, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 4}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:09:44,231] Trial 14 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8317644201969276, 'learning_rate': 0.04522573411670834, 'dropout_rate': 0.1409706939250337, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 1.3805746155966725, 'min_weight_fraction_leaf': 0.20234919011102165, 'max_features': 'auto', 'min_impurity_decrease': 1.0791764760419112e-06, 'validation_fraction': 0.8511576356292246, 'min_samples_split': 7, 'max_leaf_nodes': 12, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:10:37,787] Trial 15 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.10168575329098828, 'learning_rate': 0.016972156032725325, 'dropout_rate': 0.24832294744598937, 'n_estimators': 419, 'criterion': 'squared_error', 'ccp_alpha': 5.424599415739354, 'min_weight_fraction_leaf': 0.320352163185648, 'max_features': 'auto', 'min_impurity_decrease': 5.464270262358716e-07, 'validation_fraction': 0.4126984816608015, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 4}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:11:05,295] Trial 16 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.519334459669722, 'learning_rate': 0.09485876702648487, 'dropout_rate': 0.46717840123239474, 'n_estimators': 361, 'criterion': 'squared_error', 'ccp_alpha': 1.467662495003349, 'min_weight_fraction_leaf': 0.4180077563730136, 'max_features': 'log2', 'min_impurity_decrease': 0.004392815797593798, 'validation_fraction': 0.8753639000050211, 'min_samples_split': 2, 'max_leaf_nodes': 9, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:12:13,498] Trial 17 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8041141806500862, 'learning_rate': 0.028008195060400188, 'dropout_rate': 0.11641015051479378, 'n_estimators': 449, 'criterion': 'squared_error', 'ccp_alpha': 0.768823946633231, 'min_weight_fraction_leaf': 0.16571693579916313, 'max_features': 0.1, 'min_impurity_decrease': 4.608869854221985e-06, 'validation_fraction': 0.6468263087368702, 'min_samples_split': 7, 'max_leaf_nodes': 13, 'min_samples_leaf': 8, 'max_depth': 1}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:12:51,250] Trial 18 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9676206504107124, 'learning_rate': 0.0020994684260237303, 'dropout_rate': 0.33487277955119327, 'n_estimators': 368, 'criterion': 'squared_error', 'ccp_alpha': 2.20582487151066, 'min_weight_fraction_leaf': 0.33532076655694854, 'max_features': 1, 'min_impurity_decrease': 1.1428995670455916e-07, 'validation_fraction': 0.49371624823841737, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 14}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:12:56,602] Trial 19 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.39123396977027813, 'learning_rate': 0.03839341657772177, 'dropout_rate': 0.4447059463799564, 'n_estimators': 151, 'criterion': 'squared_error', 'ccp_alpha': 5.575186091756277, 'min_weight_fraction_leaf': 0.4448742454457023, 'max_features': 'auto', 'min_impurity_decrease': 0.00011080276147152009, 'validation_fraction': 0.7687302921055329, 'min_samples_split': 14, 'max_leaf_nodes': 10, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:13:56,337] Trial 20 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.600653399589642, 'learning_rate': 0.014434912672576577, 'dropout_rate': 0.21331492035592214, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 2.6178835745332165, 'min_weight_fraction_leaf': 0.258634214304925, 'max_features': 'auto', 'min_impurity_decrease': 4.0677998184244577e-07, 'validation_fraction': 0.9222269864579477, 'min_samples_split': 7, 'max_leaf_nodes': 16, 'min_samples_leaf': 20, 'max_depth': 6}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24708096943556548
Fold 2 IBS: 0.2319847894382899
Fold 3 IBS: 0.2289216878375815
Fold 4 IBS: 0.24189505261981767
Fold 5 IBS: 0.22923205149412185
[I 2024-04-14 22:15:03,150] Trial 21 finished with value: 0.23582291016507528 and parameters: {'subsample': 0.8710949915772802, 'learning_rate': 0.003331822753867523, 'dropout_rate': 0.27402647455162554, 'n_estimators': 490, 'criterion': 'squared_error', 'ccp_alpha': 0.10831067194484424, 'min_weight_fraction_leaf': 0.2092798564005344, 'max_features': 'auto', 'min_impurity_decrease': 4.010743417223425e-06, 'validation_fraction': 0.9907436230019966, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.2465321886783108
Fold 2 IBS: 0.2308259985040075

Fold 3 IBS: 0.22877228595462096
Fold 4 IBS: 0.24123069912531167
Fold 5 IBS: 0.2287875638037069
[I 2024-04-14 22:16:12,965] Trial 22 finished with value: 0.2352297472131916 and parameters: {'subsample': 0.7705970564002892, 'learning_rate': 0.009167698493593415, 'dropout_rate': 0.2556338272384969, 'n_estimators': 497, 'criterion': 'squared_error', 'ccp_alpha': 0.07918776278151772, 'min_weight_fraction_leaf': 0.1819352198113874, 'max_features': 'auto', 'min_impurity_decrease': 2.8455032461612084e-06, 'validation_fraction': 0.934799684395542, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-14 22:17:11,635] Trial 23 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7836311463570909, 'learning_rate': 0.01132828894454847, 'dropout_rate': 0.19187858926690976, 'n_estimators': 447, 'criterion': 'squared_error', 'ccp_alpha': 0.9682317096442044, 'min_weight_fraction_leaf': 0.1238520089163157, 'max_features': 'auto', 'min_impurity_decrease': 3.0522262999316147e-07, 'validation_fraction': 0.90105523778627, 'min_samples_split': 18, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:18:13,531] Trial 24 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7587811397980595, 'learning_rate': 0.021820272704553792, 'dropout_rate': 0.38790491264114013, 'n_estimators': 410, 'criterion': 'squared_error', 'ccp_alpha': 1.9382331620898647, 'min_weight_fraction_leaf': 0.3092505738893419, 'max_features': 'auto', 'min_impurity_decrease': 1.835773315341181e-06, 'validation_fraction': 0.712148511066075, 'min_samples_split': 18, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 6}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:19:09,835] Trial 25 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.6215945368876574, 'learning_rate': 0.021776489596240636, 'dropout_rate': 0.17960538486983635, 'n_estimators': 344, 'criterion': 'squared_error', 'ccp_alpha': 0.7972724799167636, 'min_weight_fraction_leaf': 0.06342723550175844, 'max_features': 'auto', 'min_impurity_decrease': 4.2810579358018096e-07, 'validation_fraction': 0.8062622793646869, 'min_samples_split': 16, 'max_leaf_nodes': 13, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:20:06,490] Trial 26 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.926412059695023, 'learning_rate': 0.05388614620247714, 'dropout_rate': 0.5288432021501348, 'n_estimators': 462, 'criterion': 'friedman_mse', 'ccp_alpha': 4.582122091349964, 'min_weight_fraction_leaf': 0.3654495948602763, 'max_features': 1, 'min_impurity_decrease': 5.7767867868391535e-06, 'validation_fraction': 0.937633101369361, 'min_samples_split': 14, 'max_leaf_nodes': 17, 'min_samples_leaf': 5, 'max_depth': 19}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:20:12,913] Trial 27 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.45161453091251524, 'learning_rate': 0.009457280888572136, 'dropout_rate': 0.9847790608248583, 'n_estimators': 379, 'criterion': 'squared_error', 'ccp_alpha': 0.7199879736775374, 'min_weight_fraction_leaf': 0.23893572545700834, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0231645292117779e-07, 'validation_fraction': 0.44431184160191695, 'min_samples_split': 18, 'max_leaf_nodes': 19, 'min_samples_leaf': 16, 'max_depth': 8}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:20:25,744] Trial 28 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5982471609501279, 'learning_rate': 0.035171829641187445, 'dropout_rate': 0.7580627673470397, 'n_estimators': 315, 'criterion': 'squared_error', 'ccp_alpha': 2.8493571938075926, 'min_weight_fraction_leaf': 0.17979234805851085, 'max_features': 0.1, 'min_impurity_decrease': 2.8766461228225205e-07, 'validation_fraction': 0.6049517093174607, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:21:18,203] Trial 29 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7195085150242893, 'learning_rate': 0.026204209745027407, 'dropout_rate': 0.2977987672602068, 'n_estimators': 430, 'criterion': 'friedman_mse', 'ccp_alpha': 6.2722992158041215, 'min_weight_fraction_leaf': 0.1613885275758775, 'max_features': 'log2', 'min_impurity_decrease': 3.737724247037699e-05, 'validation_fraction': 0.7532616175615756, 'min_samples_split': 6, 'max_leaf_nodes': 7, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:22:28,838] Trial 30 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.8418253580819621, 'learning_rate': 0.018136222377147192, 'dropout_rate': 0.3265580511017444, 'n_estimators': 499, 'criterion': 'squared_error', 'ccp_alpha': 9.511571270019, 'min_weight_fraction_leaf': 0.3042180850166743, 'max_features': 'auto', 'min_impurity_decrease': 2.031090116944395e-06, 'validation_fraction': 0.2362933590307199, 'min_samples_split': 19, 'max_leaf_nodes': 13, 'min_samples_leaf': 11, 'max_depth': 13}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.24669271761943912
Fold 2 IBS: 0.23161158748658048
Fold 3 IBS: 0.22885749682655868
Fold 4 IBS: 0.2415375526987621
Fold 5 IBS: 0.22900015372798382
[I 2024-04-14 22:23:32,420] Trial 31 finished with value: 0.23553990167186484 and parameters: {'subsample': 0.9344383405023591, 'learning_rate': 0.006524518316879135, 'dropout_rate': 0.26649573367142365, 'n_estimators': 474, 'criterion': 'squared_error', 'ccp_alpha': 0.08882113004952032, 'min_weight_fraction_leaf': 0.23117398599557132, 'max_features': 'auto', 'min_impurity_decrease': 4.351117867352206e-06, 'validation_fraction': 0.9601957444024036, 'min_samples_split': 20, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 9 with value: 0.23488869871747386.
Fold 1 IBS: 0.2456605494983871
Fold 2 IBS: 0.23008816995066847
Fold 3 IBS: 0.22847351140220415
Fold 4 IBS: 0.24096318715752618
Fold 5 IBS: 0.22849198296973833
[I 2024-04-14 22:24:32,488] Trial 32 finished with value: 0.23473548019570484 and parameters: {'subsample': 0.9576019950563541, 'learning_rate': 0.008435334301058566, 'dropout_rate': 0.2287495679714313, 'n_estimators': 467, 'criterion': 'squared_error', 'ccp_alpha': 0.01914282727239553, 'min_weight_fraction_leaf': 0.23002205018404465, 'max_features': 'auto', 'min_impurity_decrease': 5.685341128394722e-05, 'validation_fraction': 0.9130609639429398, 'min_samples_split': 20, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:25:09,785] Trial 33 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9177537861930692, 'learning_rate': 0.00969453021125602, 'dropout_rate': 0.3914970241753336, 'n_estimators': 389, 'criterion': 'squared_error', 'ccp_alpha': 1.0507266620441584, 'min_weight_fraction_leaf': 0.23926229900744406, 'max_features': 'auto', 'min_impurity_decrease': 0.00011709565626556463, 'validation_fraction': 0.8393388494663446, 'min_samples_split': 19, 'max_leaf_nodes': 19, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:26:04,097] Trial 34 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6819681800793775, 'learning_rate': 0.014932417117098078, 'dropout_rate': 0.2500240325464975, 'n_estimators': 437, 'criterion': 'friedman_mse', 'ccp_alpha': 1.9765936590363733, 'min_weight_fraction_leaf': 0.13771184392949654, 'max_features': 'sqrt', 'min_impurity_decrease': 2.415346159906542e-05, 'validation_fraction': 0.9172090645295194, 'min_samples_split': 15, 'max_leaf_nodes': 19, 'min_samples_leaf': 20, 'max_depth': 3}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:26:19,037] Trial 35 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7476638601677043, 'learning_rate': 0.00715465005011402, 'dropout_rate': 0.30101053387291227, 'n_estimators': 210, 'criterion': 'friedman_mse', 'ccp_alpha': 0.44652508735115226, 'min_weight_fraction_leaf': 0.10093795447298021, 'max_features': None, 'min_impurity_decrease': 4.406156675878729e-05, 'validation_fraction': 0.6852856643785393, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 18, 'max_depth': 2}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:27:08,535] Trial 36 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6505975935001664, 'learning_rate': 0.02571949043074776, 'dropout_rate': 0.42230497047334825, 'n_estimators': 471, 'criterion': 'squared_error', 'ccp_alpha': 4.21907826177426, 'min_weight_fraction_leaf': 0.26995461743933613, 'max_features': 'auto', 'min_impurity_decrease': 1.3215601521076594e-05, 'validation_fraction': 0.7818001985604904, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 16, 'max_depth': 5}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:27:11,967] Trial 37 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9473900644033275, 'learning_rate': 0.03319376442404014, 'dropout_rate': 0.21915428448310503, 'n_estimators': 98, 'criterion': 'squared_error', 'ccp_alpha': 1.4358936193715688, 'min_weight_fraction_leaf': 0.23268483668726153, 'max_features': None, 'min_impurity_decrease': 0.00032393590103416044, 'validation_fraction': 0.36234755932857715, 'min_samples_split': 9, 'max_leaf_nodes': 20, 'min_samples_leaf': 17, 'max_depth': 7}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 22:27:31,689] Trial 38 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8672504967337782, 'learning_rate': 0.018430646064201885, 'dropout_rate': 0.7673236646699829, 'n_estimators': 322, 'criterion': 'friedman_mse', 'ccp_alpha': 0.6556730327214771, 'min_weight_fraction_leaf': 0.18834697224411925, 'max_features': 'auto', 'min_impurity_decrease': 0.00023363839115037033, 'validation_fraction': 0.012692984164186849, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 19, 'max_depth': 16}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:28:06,020] Trial 39 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8156280794845335, 'learning_rate': 0.012607094884384062, 'dropout_rate': 0.3466374755180119, 'n_estimators': 395, 'criterion': 'squared_error', 'ccp_alpha': 2.049217834173834, 'min_weight_fraction_leaf': 0.2802748909834897, 'max_features': 1, 'min_impurity_decrease': 0.001895508491501562, 'validation_fraction': 0.5697613916361016, 'min_samples_split': 12, 'max_leaf_nodes': 19, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:28:34,444] Trial 40 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9034992885699185, 'learning_rate': 0.06484286745425966, 'dropout_rate': 0.518652974052727, 'n_estimators': 411, 'criterion': 'squared_error', 'ccp_alpha': 3.416581893752396, 'min_weight_fraction_leaf': 0.07781604608486586, 'max_features': 'auto', 'min_impurity_decrease': 1.186294852384206e-05, 'validation_fraction': 0.6514426016998515, 'min_samples_split': 17, 'max_leaf_nodes': 2, 'min_samples_leaf': 2, 'max_depth': 10}. Best is trial 32 with value: 0.23473548019570484.
Fold 1 IBS: 0.24535392898444236
Fold 2 IBS: 0.22987508171862567
Fold 3 IBS: 0.22828579601330518
Fold 4 IBS: 0.2405288238508211
Fold 5 IBS: 0.2281686078231268
[I 2024-04-14 22:29:39,955] Trial 41 finished with value: 0.23444244767806421 and parameters: {'subsample': 0.9932038385002909, 'learning_rate': 0.0058523899242036315, 'dropout_rate': 0.1573621124822965, 'n_estimators': 468, 'criterion': 'squared_error', 'ccp_alpha': 0.0166355939713465, 'min_weight_fraction_leaf': 0.13954813567569782, 'max_features': 'auto', 'min_impurity_decrease': 7.535700463117119e-07, 'validation_fraction': 0.95592943950246, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.245634515226611
Fold 2 IBS: 0.2302086589736701
Fold 3 IBS: 0.22826566696628003
Fold 4 IBS: 0.2408349482593946
Fold 5 IBS: 0.22814822928869835
[I 2024-04-14 22:30:43,617] Trial 42 finished with value: 0.2346184037429308 and parameters: {'subsample': 0.964697700266936, 'learning_rate': 0.006887909703669877, 'dropout_rate': 0.18073816214366334, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 0.008327291371346121, 'min_weight_fraction_leaf': 0.1501825213718253, 'max_features': 'auto', 'min_impurity_decrease': 7.389724453793971e-07, 'validation_fraction': 0.9438929489105444, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:31:48,596] Trial 43 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9828290729869368, 'learning_rate': 0.005440117267094092, 'dropout_rate': 0.16429624388711278, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 1.1638059032250418, 'min_weight_fraction_leaf': 0.14400744495905113, 'max_features': 'auto', 'min_impurity_decrease': 7.160819992467899e-07, 'validation_fraction': 0.8682784817018523, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:36:14,786] Trial 44 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.9992871622667048, 'learning_rate': 0.012272887594565313, 'dropout_rate': 0.11965546339368549, 'n_estimators': 451, 'criterion': 'squared_error', 'ccp_alpha': 0.5504303626596221, 'min_weight_fraction_leaf': 0.10316812300893248, 'max_features': 'auto', 'min_impurity_decrease': 2.2780695231073978e-06, 'validation_fraction': 0.8946516967835402, 'min_samples_split': 17, 'max_leaf_nodes': 14, 'min_samples_leaf': 10, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:36:26,454] Trial 45 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8888336111822305, 'learning_rate': 0.022080051602678542, 'dropout_rate': 0.2121382569959027, 'n_estimators': 275, 'criterion': 'squared_error', 'ccp_alpha': 0.41647456900543567, 'min_weight_fraction_leaf': 0.045210542223651826, 'max_features': 0.1, 'min_impurity_decrease': 2.0256548340178764e-07, 'validation_fraction': 0.943601584155436, 'min_samples_split': 13, 'max_leaf_nodes': 14, 'min_samples_leaf': 9, 'max_depth': 3}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24662110599604836
Fold 2 IBS: 0.23145584795164761
Fold 3 IBS: 0.22875970443963095
Fold 4 IBS: 0.24156034399918552
Fold 5 IBS: 0.2289692669356275
[I 2024-04-14 22:39:00,190] Trial 46 finished with value: 0.23547325386442802 and parameters: {'subsample': 0.7744813929591432, 'learning_rate': 0.008102046534903828, 'dropout_rate': 0.1797794592098615, 'n_estimators': 473, 'criterion': 'squared_error', 'ccp_alpha': 0.08495175216102194, 'min_weight_fraction_leaf': 0.15177154165796414, 'max_features': 'sqrt', 'min_impurity_decrease': 1.1313197537973378e-06, 'validation_fraction': 0.8282995111719733, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 4}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:39:09,798] Trial 47 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7017637733903979, 'learning_rate': 0.0012930485564563617, 'dropout_rate': 0.7022058348677743, 'n_estimators': 431, 'criterion': 'squared_error', 'ccp_alpha': 1.7224181899716802, 'min_weight_fraction_leaf': 0.18604464195331838, 'max_features': 'auto', 'min_impurity_decrease': 6.985840903306681e-07, 'validation_fraction': 0.23829490589029295, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 7}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:39:09,926] Trial 48 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5605970169273662, 'learning_rate': 0.0764803107378837, 'dropout_rate': 0.10447148486096186, 'n_estimators': 8, 'criterion': 'squared_error', 'ccp_alpha': 7.631807716105536, 'min_weight_fraction_leaf': 0.2080122998414906, 'max_features': None, 'min_impurity_decrease': 2.1520342389791543e-07, 'validation_fraction': 0.9548943163211767, 'min_samples_split': 20, 'max_leaf_nodes': 11, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:39:16,985] Trial 49 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8470287699338075, 'learning_rate': 0.015427354382840298, 'dropout_rate': 0.1456275761236044, 'n_estimators': 235, 'criterion': 'friedman_mse', 'ccp_alpha': 1.2223686585045759, 'min_weight_fraction_leaf': 0.12204787996041808, 'max_features': 'log2', 'min_impurity_decrease': 0.0008845692122216605, 'validation_fraction': 0.8594860776957634, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 12, 'max_depth': 5}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:43:16,133] Trial 50 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9497672382316631, 'learning_rate': 0.04787473278637476, 'dropout_rate': 0.23703345601437922, 'n_estimators': 346, 'criterion': 'squared_error', 'ccp_alpha': 0.4773369462462276, 'min_weight_fraction_leaf': 0.25645611863450213, 'max_features': 'auto', 'min_impurity_decrease': 7.588820818919594e-06, 'validation_fraction': 0.7876099760634406, 'min_samples_split': 2, 'max_leaf_nodes': 18, 'min_samples_leaf': 9, 'max_depth': 4}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.2462253324523899
Fold 2 IBS: 0.23052264808077524
Fold 3 IBS: 0.2282761785824288
Fold 4 IBS: 0.24087657592887432
Fold 5 IBS: 0.2286011628254391
[I 2024-04-14 22:45:10,994] Trial 51 finished with value: 0.23490037957398147 and parameters: {'subsample': 0.7654204482217829, 'learning_rate': 0.006617235377025302, 'dropout_rate': 0.16919816074383062, 'n_estimators': 480, 'criterion': 'squared_error', 'ccp_alpha': 0.012288631843664816, 'min_weight_fraction_leaf': 0.1689933524541079, 'max_features': 'sqrt', 'min_impurity_decrease': 1.0415032179614574e-06, 'validation_fraction': 0.8197275960031745, 'min_samples_split': 19, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24677257825735915
Fold 2 IBS: 0.23136267513783498
Fold 3 IBS: 0.22862302810583077
Fold 4 IBS: 0.24151933095108347
Fold 5 IBS: 0.22907696995769353
[I 2024-04-14 22:45:39,063] Trial 52 finished with value: 0.2354709164819604 and parameters: {'subsample': 0.5053435062182351, 'learning_rate': 0.005408327553770254, 'dropout_rate': 0.29098664360409054, 'n_estimators': 475, 'criterion': 'squared_error', 'ccp_alpha': 0.036600491313384984, 'min_weight_fraction_leaf': 0.17248176220266245, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6630249663545005e-06, 'validation_fraction': 0.7333914400675312, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:46:52,927] Trial 53 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4631663309031124, 'learning_rate': 0.010335997729310374, 'dropout_rate': 0.15315671922192206, 'n_estimators': 483, 'criterion': 'squared_error', 'ccp_alpha': 1.0257967033802227, 'min_weight_fraction_leaf': 0.19064788811176675, 'max_features': 'sqrt', 'min_impurity_decrease': 7.833227343851573e-07, 'validation_fraction': 0.9011349602609936, 'min_samples_split': 17, 'max_leaf_nodes': 19, 'min_samples_leaf': 5, 'max_depth': 3}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 22:47:02,536] Trial 54 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9017461575502412, 'learning_rate': 0.01762169753824272, 'dropout_rate': 0.8266353856620614, 'n_estimators': 453, 'criterion': 'squared_error', 'ccp_alpha': 0.4362560228385305, 'min_weight_fraction_leaf': 0.09319645554340197, 'max_features': 'sqrt', 'min_impurity_decrease': 0.01937053717718396, 'validation_fraction': 0.9995106443638909, 'min_samples_split': 20, 'max_leaf_nodes': 16, 'min_samples_leaf': 6, 'max_depth': 1}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:05:16,875] Trial 55 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.809323041898869, 'learning_rate': 0.0040826970179266685, 'dropout_rate': 0.20419816136861105, 'n_estimators': 437, 'criterion': 'squared_error', 'ccp_alpha': 1.5125790196698774, 'min_weight_fraction_leaf': 0.21953014805517473, 'max_features': 'auto', 'min_impurity_decrease': 2.0868015436948727e-05, 'validation_fraction': 0.9659902853562541, 'min_samples_split': 19, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:05:37,149] Trial 56 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.2887765610954624, 'learning_rate': 0.09850922090204048, 'dropout_rate': 0.23996644019536584, 'n_estimators': 398, 'criterion': 'squared_error', 'ccp_alpha': 2.3897427065099115, 'min_weight_fraction_leaf': 0.1313980673113705, 'max_features': 'auto', 'min_impurity_decrease': 4.350989437370722e-07, 'validation_fraction': 0.5010775717552909, 'min_samples_split': 18, 'max_leaf_nodes': 14, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:05:56,249] Trial 57 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6446884806787394, 'learning_rate': 0.0010994123129714779, 'dropout_rate': 0.5891903890315894, 'n_estimators': 500, 'criterion': 'squared_error', 'ccp_alpha': 3.0806403612284923, 'min_weight_fraction_leaf': 0.20021426582615917, 'max_features': 1, 'min_impurity_decrease': 1.879800220304926e-07, 'validation_fraction': 0.8789871257745913, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 4, 'max_depth': 1}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658996
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:06:27,137] Trial 58 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9579507989353487, 'learning_rate': 0.02418028639032989, 'dropout_rate': 0.37031334062735055, 'n_estimators': 458, 'criterion': 'squared_error', 'ccp_alpha': 6.734647887782943, 'min_weight_fraction_leaf': 0.2892805623291713, 'max_features': 'auto', 'min_impurity_decrease': 1.1543063953853995e-06, 'validation_fraction': 0.8234456145260549, 'min_samples_split': 9, 'max_leaf_nodes': 12, 'min_samples_leaf': 14, 'max_depth': 4}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.2419747714592711
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:06:50,662] Trial 59 finished with value: 0.2359278435123307 and parameters: {'subsample': 0.7291830079861774, 'learning_rate': 0.013269545795309803, 'dropout_rate': 0.3259416667709019, 'n_estimators': 413, 'criterion': 'squared_error', 'ccp_alpha': 0.8996013780493972, 'min_weight_fraction_leaf': 0.15797670971031227, 'max_features': 0.1, 'min_impurity_decrease': 2.556545341406747e-07, 'validation_fraction': 0.9254022058214465, 'min_samples_split': 15, 'max_leaf_nodes': 15, 'min_samples_leaf': 10, 'max_depth': 5}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:07:49,235] Trial 60 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.8610396134059503, 'learning_rate': 0.0299620116966956, 'dropout_rate': 0.10121382681282606, 'n_estimators': 481, 'criterion': 'squared_error', 'ccp_alpha': 1.7110338383890442, 'min_weight_fraction_leaf': 0.1707925110352551, 'max_features': 'sqrt', 'min_impurity_decrease': 2.6172084806681395e-06, 'validation_fraction': 0.7207277422863438, 'min_samples_split': 16, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 6}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24693151503453267
Fold 2 IBS: 0.23164915966073843
Fold 3 IBS: 0.22879736929759598
Fold 4 IBS: 0.24173800591592182
Fold 5 IBS: 0.22921816172451576
[I 2024-04-14 23:08:28,198] Trial 61 finished with value: 0.23566684232666094 and parameters: {'subsample': 0.5319232616870766, 'learning_rate': 0.005743016439014149, 'dropout_rate': 0.28747233681343587, 'n_estimators': 469, 'criterion': 'squared_error', 'ccp_alpha': 0.08369853910029246, 'min_weight_fraction_leaf': 0.17414778507912232, 'max_features': 'sqrt', 'min_impurity_decrease': 2.9513412376244623e-06, 'validation_fraction': 0.7571179766181859, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 7, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24606828239893616
Fold 2 IBS: 0.2304366130812427
Fold 3 IBS: 0.22824138077077405
Fold 4 IBS: 0.24079616658546193
Fold 5 IBS: 0.2285563515994586
[I 2024-04-14 23:09:04,692] Trial 62 finished with value: 0.23481975888717468 and parameters: {'subsample': 0.4925035567743181, 'learning_rate': 0.008574233182053305, 'dropout_rate': 0.18472859039005549, 'n_estimators': 444, 'criterion': 'squared_error', 'ccp_alpha': 0.022436649946678315, 'min_weight_fraction_leaf': 0.2185932745342059, 'max_features': 'sqrt', 'min_impurity_decrease': 1.4865063577465509e-06, 'validation_fraction': 0.6567901131741327, 'min_samples_split': 18, 'max_leaf_nodes': 17, 'min_samples_leaf': 8, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:09:34,730] Trial 63 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.36250599252560084, 'learning_rate': 0.009885633504393494, 'dropout_rate': 0.17342319762993127, 'n_estimators': 438, 'criterion': 'squared_error', 'ccp_alpha': 0.40714661625851756, 'min_weight_fraction_leaf': 0.22065906606210625, 'max_features': 'sqrt', 'min_impurity_decrease': 1.5461603829886907e-06, 'validation_fraction': 0.5930718768662838, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 9, 'max_depth': 1}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:10:13,802] Trial 64 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5841735751044772, 'learning_rate': 0.02055321577299183, 'dropout_rate': 0.13571080979315037, 'n_estimators': 455, 'criterion': 'squared_error', 'ccp_alpha': 0.7050476759364486, 'min_weight_fraction_leaf': 0.26097856117428203, 'max_features': 'log2', 'min_impurity_decrease': 5.301233747286273e-07, 'validation_fraction': 0.6573317669908815, 'min_samples_split': 20, 'max_leaf_nodes': 18, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:10:35,753] Trial 65 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.46117939767485777, 'learning_rate': 0.014473083324943868, 'dropout_rate': 0.19566551609009084, 'n_estimators': 371, 'criterion': 'squared_error', 'ccp_alpha': 0.351957844105687, 'min_weight_fraction_leaf': 0.0025378122397684832, 'max_features': 'sqrt', 'min_impurity_decrease': 8.152865551058182e-06, 'validation_fraction': 0.969214445384316, 'min_samples_split': 17, 'max_leaf_nodes': 15, 'min_samples_leaf': 11, 'max_depth': 1}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809254
[I 2024-04-14 23:11:07,200] Trial 66 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.41194318384993134, 'learning_rate': 0.008448226967076113, 'dropout_rate': 0.22834912563776077, 'n_estimators': 424, 'criterion': 'squared_error', 'ccp_alpha': 0.893850403970479, 'min_weight_fraction_leaf': 0.11486333706731977, 'max_features': 'auto', 'min_impurity_decrease': 5.977994289888799e-05, 'validation_fraction': 0.5200975528135579, 'min_samples_split': 18, 'max_leaf_nodes': 8, 'min_samples_leaf': 6, 'max_depth': 4}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:11:43,316] Trial 67 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6282300518309584, 'learning_rate': 0.0039206688180527, 'dropout_rate': 0.2646418236350095, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 1.178673222363498, 'min_weight_fraction_leaf': 0.29808046537498534, 'max_features': 'auto', 'min_impurity_decrease': 8.331887157053983e-07, 'validation_fraction': 0.8056743728491266, 'min_samples_split': 19, 'max_leaf_nodes': 16, 'min_samples_leaf': 8, 'max_depth': 3}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:12:21,517] Trial 68 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9817200531176249, 'learning_rate': 0.01958784726286755, 'dropout_rate': 0.14310876631789804, 'n_estimators': 444, 'criterion': 'friedman_mse', 'ccp_alpha': 8.846039028998158, 'min_weight_fraction_leaf': 0.2499921488238046, 'max_features': 'auto', 'min_impurity_decrease': 3.803277550382527e-07, 'validation_fraction': 0.6927602784856939, 'min_samples_split': 16, 'max_leaf_nodes': 20, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:12:52,257] Trial 69 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5360295416604122, 'learning_rate': 0.011561561592981577, 'dropout_rate': 0.18808427427036908, 'n_estimators': 403, 'criterion': 'squared_error', 'ccp_alpha': 0.30419922755720963, 'min_weight_fraction_leaf': 0.3498652363920204, 'max_features': 'sqrt', 'min_impurity_decrease': 1.7335159824012415e-07, 'validation_fraction': 0.8530149882771714, 'min_samples_split': 20, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 12}. Best is trial 41 with value: 0.23444244767806421.
Fold 1 IBS: 0.2449859139085014
Fold 2 IBS: 0.22901165351251887
Fold 3 IBS: 0.2278354399437681
Fold 4 IBS: 0.23957757650551237
Fold 5 IBS: 0.22784528631372508
[I 2024-04-14 23:13:26,153] Trial 70 finished with value: 0.23385117403680517 and parameters: {'subsample': 0.6778926634738521, 'learning_rate': 0.016866948400001296, 'dropout_rate': 0.2706252637878238, 'n_estimators': 463, 'criterion': 'squared_error', 'ccp_alpha': 0.01005746855001105, 'min_weight_fraction_leaf': 0.14737357365856457, 'max_features': None, 'min_impurity_decrease': 1.4954856456498012e-06, 'validation_fraction': 0.4347052214290571, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 70 with value: 0.23385117403680517.
Fold 1 IBS: 0.24587142484716581
Fold 2 IBS: 0.22954021587827045
Fold 3 IBS: 0.22848845658187014
Fold 4 IBS: 0.24035753777669436
Fold 5 IBS: 0.22831995622356854
[I 2024-04-14 23:14:07,982] Trial 71 finished with value: 0.23451551826151387 and parameters: {'subsample': 0.6775135040406033, 'learning_rate': 0.016629440896307336, 'dropout_rate': 0.2629120158764063, 'n_estimators': 488, 'criterion': 'squared_error', 'ccp_alpha': 0.06024274183448569, 'min_weight_fraction_leaf': 0.14851146321450823, 'max_features': None, 'min_impurity_decrease': 1.450137086915353e-06, 'validation_fraction': 0.4382600149406195, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 70 with value: 0.23385117403680517.
Fold 1 IBS: 0.24481804238159408
Fold 2 IBS: 0.22887693609936965
Fold 3 IBS: 0.22809515492494067
Fold 4 IBS: 0.23959640105438712
Fold 5 IBS: 0.22780568448666996
[I 2024-04-14 23:14:40,071] Trial 72 finished with value: 0.23383844378939234 and parameters: {'subsample': 0.6757044468062707, 'learning_rate': 0.015406216424115876, 'dropout_rate': 0.21962634301888995, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.004831107387468772, 'min_weight_fraction_leaf': 0.1497685934535216, 'max_features': None, 'min_impurity_decrease': 1.3824526191429684e-06, 'validation_fraction': 0.37226476471314, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 72 with value: 0.23383844378939234.
Fold 1 IBS: 0.24724710044658993
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:14:43,691] Trial 73 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5815982239368568, 'learning_rate': 0.016957190070749008, 'dropout_rate': 0.32180449877064016, 'n_estimators': 153, 'criterion': 'squared_error', 'ccp_alpha': 0.7340527434897883, 'min_weight_fraction_leaf': 0.1453605586570601, 'max_features': None, 'min_impurity_decrease': 4.473581042465098e-06, 'validation_fraction': 0.3733192588934628, 'min_samples_split': 8, 'max_leaf_nodes': 18, 'min_samples_leaf': 17, 'max_depth': 4}. Best is trial 72 with value: 0.23383844378939234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:15:14,306] Trial 74 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.676688729962355, 'learning_rate': 0.02388572819447024, 'dropout_rate': 0.275140390957161, 'n_estimators': 462, 'criterion': 'squared_error', 'ccp_alpha': 0.33550183960235097, 'min_weight_fraction_leaf': 0.08880208262974063, 'max_features': None, 'min_impurity_decrease': 1.4887497256668162e-06, 'validation_fraction': 0.47383886501026795, 'min_samples_split': 6, 'max_leaf_nodes': 19, 'min_samples_leaf': 19, 'max_depth': 17}. Best is trial 72 with value: 0.23383844378939234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:15:36,048] Trial 75 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7057908257423335, 'learning_rate': 0.015707866913501012, 'dropout_rate': 0.4112328676414524, 'n_estimators': 421, 'criterion': 'squared_error', 'ccp_alpha': 0.6626240923578504, 'min_weight_fraction_leaf': 0.07137660038602918, 'max_features': None, 'min_impurity_decrease': 1.0345201955396856e-07, 'validation_fraction': 0.4338774432543437, 'min_samples_split': 10, 'max_leaf_nodes': 20, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 72 with value: 0.23383844378939234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:15:58,051] Trial 76 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.4918260327899229, 'learning_rate': 0.0558935141377456, 'dropout_rate': 0.35567267340087927, 'n_estimators': 384, 'criterion': 'squared_error', 'ccp_alpha': 3.8543981234707565, 'min_weight_fraction_leaf': 0.32254979446846543, 'max_features': None, 'min_impurity_decrease': 1.5576257483495967e-06, 'validation_fraction': 0.35120610496528537, 'min_samples_split': 4, 'max_leaf_nodes': 18, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 72 with value: 0.23383844378939234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:16:29,209] Trial 77 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.662142493553532, 'learning_rate': 0.04128077713454106, 'dropout_rate': 0.21207366660855861, 'n_estimators': 446, 'criterion': 'squared_error', 'ccp_alpha': 1.2832467794713243, 'min_weight_fraction_leaf': 0.13484676844178797, 'max_features': None, 'min_impurity_decrease': 5.433160474458954e-07, 'validation_fraction': 0.3082779826259943, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 17, 'max_depth': 2}. Best is trial 72 with value: 0.23383844378939234.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939128724118643
[I 2024-04-14 23:17:02,943] Trial 78 finished with value: 0.2359269823509495 and parameters: {'subsample': 0.6029614475469536, 'learning_rate': 0.02742354559286264, 'dropout_rate': 0.30983910835542605, 'n_estimators': 465, 'criterion': 'squared_error', 'ccp_alpha': 0.2456295975030462, 'min_weight_fraction_leaf': 0.11562704029980372, 'max_features': None, 'min_impurity_decrease': 3.3874047424531466e-07, 'validation_fraction': 0.27565017247651985, 'min_samples_split': 3, 'max_leaf_nodes': 20, 'min_samples_leaf': 18, 'max_depth': 5}. Best is trial 72 with value: 0.23383844378939234.
Fold 1 IBS: 0.2401275231540682
Fold 2 IBS: 0.21808588188730932
Fold 3 IBS: 0.22659243528363182
Fold 4 IBS: 0.23357316044345386
Fold 5 IBS: 0.22388801424072072
[I 2024-04-14 23:17:32,284] Trial 79 finished with value: 0.2284534030018368 and parameters: {'subsample': 0.6262723693325352, 'learning_rate': 0.08690058608305122, 'dropout_rate': 0.23058735613266046, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.0067848986270052205, 'min_weight_fraction_leaf': 0.052185986803038986, 'max_features': None, 'min_impurity_decrease': 6.572227406740716e-06, 'validation_fraction': 0.3977549795971044, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 79 with value: 0.2284534030018368.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:18:14,656] Trial 80 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7379172021186918, 'learning_rate': 0.07289104058957506, 'dropout_rate': 0.12856958604526103, 'n_estimators': 487, 'criterion': 'friedman_mse', 'ccp_alpha': 1.0208718228969498, 'min_weight_fraction_leaf': 0.023387870517704957, 'max_features': None, 'min_impurity_decrease': 5.981452490135581e-06, 'validation_fraction': 0.422036473624131, 'min_samples_split': 8, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 1}. Best is trial 79 with value: 0.2284534030018368.
Fold 1 IBS: 0.23739513598951673
Fold 2 IBS: 0.21575414373235283
Fold 3 IBS: 0.224077673889257
Fold 4 IBS: 0.23045843376143094
Fold 5 IBS: 0.2215233279750438
[I 2024-04-14 23:18:46,181] Trial 81 finished with value: 0.22584174306952026 and parameters: {'subsample': 0.6337873681967188, 'learning_rate': 0.09196546766753708, 'dropout_rate': 0.23328361444371593, 'n_estimators': 422, 'criterion': 'squared_error', 'ccp_alpha': 0.025343486133480444, 'min_weight_fraction_leaf': 0.04961493606388526, 'max_features': None, 'min_impurity_decrease': 1.789620202740983e-05, 'validation_fraction': 0.38463358300436473, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:19:16,311] Trial 82 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6350962300316173, 'learning_rate': 0.09024426530842436, 'dropout_rate': 0.24663358465620938, 'n_estimators': 429, 'criterion': 'squared_error', 'ccp_alpha': 0.5340758841421452, 'min_weight_fraction_leaf': 0.04482541922262277, 'max_features': None, 'min_impurity_decrease': 1.3792443320901406e-05, 'validation_fraction': 0.39306425194699585, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 2}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:19:52,847] Trial 83 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6941416321217367, 'learning_rate': 0.08769222490327029, 'dropout_rate': 0.22968230522988387, 'n_estimators': 448, 'criterion': 'squared_error', 'ccp_alpha': 0.29851318725213727, 'min_weight_fraction_leaf': 0.05645786104371703, 'max_features': None, 'min_impurity_decrease': 1.9406207763184885e-05, 'validation_fraction': 0.33637767366261256, 'min_samples_split': 7, 'max_leaf_nodes': 20, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:20:32,440] Trial 84 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5631596960173056, 'learning_rate': 0.09337007500374273, 'dropout_rate': 0.19485958925930286, 'n_estimators': 466, 'criterion': 'squared_error', 'ccp_alpha': 0.7908292561402825, 'min_weight_fraction_leaf': 0.03432008110643191, 'max_features': None, 'min_impurity_decrease': 6.872960387505756e-05, 'validation_fraction': 0.44812697868728824, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.23738180814604748
Fold 2 IBS: 0.216878335633832
Fold 3 IBS: 0.22407827411739062
Fold 4 IBS: 0.23111064290025385
Fold 5 IBS: 0.22140936879224918
[I 2024-04-14 23:21:06,424] Trial 85 finished with value: 0.2261716859179546 and parameters: {'subsample': 0.6182799647002708, 'learning_rate': 0.06087928731142127, 'dropout_rate': 0.16345037014762245, 'n_estimators': 420, 'criterion': 'squared_error', 'ccp_alpha': 0.011216734292662366, 'min_weight_fraction_leaf': 0.08078985580008471, 'max_features': None, 'min_impurity_decrease': 0.0001577724500897646, 'validation_fraction': 0.5341353413089467, 'min_samples_split': 5, 'max_leaf_nodes': 18, 'min_samples_leaf': 12, 'max_depth': 2}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927118
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:21:37,259] Trial 86 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.617943083149883, 'learning_rate': 0.06299476346040861, 'dropout_rate': 0.15862836305400332, 'n_estimators': 417, 'criterion': 'squared_error', 'ccp_alpha': 0.62448544277789, 'min_weight_fraction_leaf': 0.006470391452136008, 'max_features': None, 'min_impurity_decrease': 2.858962063513706e-05, 'validation_fraction': 0.3929243438216819, 'min_samples_split': 5, 'max_leaf_nodes': 19, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:21:58,648] Trial 87 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6562353160855874, 'learning_rate': 0.08056151243791008, 'dropout_rate': 0.27015052254499844, 'n_estimators': 362, 'criterion': 'squared_error', 'ccp_alpha': 0.23540692996188609, 'min_weight_fraction_leaf': 0.08034801037035519, 'max_features': None, 'min_impurity_decrease': 0.00010508944849456989, 'validation_fraction': 0.5356460325513532, 'min_samples_split': 6, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 4}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:22:39,457] Trial 88 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6723499933201714, 'learning_rate': 0.08445478533817788, 'dropout_rate': 0.2193630306533548, 'n_estimators': 489, 'criterion': 'squared_error', 'ccp_alpha': 0.5761857609766958, 'min_weight_fraction_leaf': 0.09845759507035474, 'max_features': None, 'min_impurity_decrease': 0.0001627481847856609, 'validation_fraction': 0.16955200144561516, 'min_samples_split': 5, 'max_leaf_nodes': 20, 'min_samples_leaf': 12, 'max_depth': 3}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:23:13,252] Trial 89 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.7153666202558423, 'learning_rate': 0.0596510546088449, 'dropout_rate': 0.12572810870358422, 'n_estimators': 428, 'criterion': 'squared_error', 'ccp_alpha': 5.474477626804302, 'min_weight_fraction_leaf': 0.060066177195707796, 'max_features': None, 'min_impurity_decrease': 7.317603928432135e-05, 'validation_fraction': 0.4594284700161132, 'min_samples_split': 9, 'max_leaf_nodes': 18, 'min_samples_leaf': 15, 'max_depth': 9}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:23:48,326] Trial 90 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.9251674654824944, 'learning_rate': 0.06882231759513935, 'dropout_rate': 0.2572481395180059, 'n_estimators': 476, 'criterion': 'squared_error', 'ccp_alpha': 5.0331221171402944, 'min_weight_fraction_leaf': 0.04290693736423035, 'max_features': None, 'min_impurity_decrease': 0.0005595170194677708, 'validation_fraction': 0.2840563139176175, 'min_samples_split': 10, 'max_leaf_nodes': 6, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 81 with value: 0.22584174306952026.
Fold 1 IBS: 0.23441761728472585
Fold 2 IBS: 0.21166844389846753
Fold 3 IBS: 0.22461325983420488
Fold 4 IBS: 0.22768397035260232
Fold 5 IBS: 0.2202728703092048
[I 2024-04-14 23:24:18,044] Trial 91 finished with value: 0.22373123233584108 and parameters: {'subsample': 0.5721381710605526, 'learning_rate': 0.09720752701033816, 'dropout_rate': 0.16710175269832556, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.038313592187199576, 'min_weight_fraction_leaf': 0.10939377946431963, 'max_features': None, 'min_impurity_decrease': 3.2951243510431054e-06, 'validation_fraction': 0.4740790632008704, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 14, 'max_depth': 2}. Best is trial 91 with value: 0.22373123233584108.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:24:44,784] Trial 92 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5776618730891118, 'learning_rate': 0.09773898069404122, 'dropout_rate': 0.15267987951170442, 'n_estimators': 404, 'criterion': 'squared_error', 'ccp_alpha': 0.274669453504222, 'min_weight_fraction_leaf': 0.1113155749033209, 'max_features': None, 'min_impurity_decrease': 8.566362057328663e-06, 'validation_fraction': 0.39419256216271326, 'min_samples_split': 7, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 2}. Best is trial 91 with value: 0.22373123233584108.
Fold 1 IBS: 0.23681693924917965
Fold 2 IBS: 0.2161256080665334
Fold 3 IBS: 0.22576926069465075
Fold 4 IBS: 0.23158403776049657
Fold 5 IBS: 0.22294344800411775
[I 2024-04-14 23:25:12,459] Trial 93 finished with value: 0.2266478587549956 and parameters: {'subsample': 0.5467548355692116, 'learning_rate': 0.09464470370929326, 'dropout_rate': 0.21245811127130074, 'n_estimators': 377, 'criterion': 'squared_error', 'ccp_alpha': 0.047806194751233454, 'min_weight_fraction_leaf': 0.15631662216103287, 'max_features': None, 'min_impurity_decrease': 3.525097349981354e-06, 'validation_fraction': 0.551673424245778, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 16, 'max_depth': 1}. Best is trial 91 with value: 0.22373123233584108.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927115
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:25:38,301] Trial 94 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.5508674541553358, 'learning_rate': 0.09368640485971641, 'dropout_rate': 0.20599175489372812, 'n_estimators': 381, 'criterion': 'squared_error', 'ccp_alpha': 0.8492587817200913, 'min_weight_fraction_leaf': 0.12831506416036972, 'max_features': None, 'min_impurity_decrease': 3.5612640405952423e-06, 'validation_fraction': 0.4782920663320762, 'min_samples_split': 8, 'max_leaf_nodes': 17, 'min_samples_leaf': 15, 'max_depth': 1}. Best is trial 91 with value: 0.22373123233584108.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:26:01,181] Trial 95 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6207251268444808, 'learning_rate': 0.09009762687235784, 'dropout_rate': 0.16658027291379346, 'n_estimators': 351, 'criterion': 'squared_error', 'ccp_alpha': 0.48353713970015955, 'min_weight_fraction_leaf': 0.15173062432088966, 'max_features': None, 'min_impurity_decrease': 5.6918807094900576e-06, 'validation_fraction': 0.5615187227931233, 'min_samples_split': 7, 'max_leaf_nodes': 17, 'min_samples_leaf': 12, 'max_depth': 1}. Best is trial 91 with value: 0.22373123233584108.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792299
Fold 3 IBS: 0.22898126954184234
Fold 4 IBS: 0.2419522280989299
Fold 5 IBS: 0.229380437423972
[I 2024-04-14 23:26:23,947] Trial 96 finished with value: 0.23592018400985143 and parameters: {'subsample': 0.6436106795551516, 'learning_rate': 0.08174905786851734, 'dropout_rate': 0.3047573533782313, 'n_estimators': 393, 'criterion': 'squared_error', 'ccp_alpha': 0.21378050037756677, 'min_weight_fraction_leaf': 0.10787868236709237, 'max_features': None, 'min_impurity_decrease': 2.078089373511934e-06, 'validation_fraction': 0.5158294992683045, 'min_samples_split': 4, 'max_leaf_nodes': 16, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 91 with value: 0.22373123233584108.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296
Fold 3 IBS: 0.22898186806977708
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.2293955930480925
[I 2024-04-14 23:26:40,401] Trial 97 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.6024688322982082, 'learning_rate': 0.09649030637314325, 'dropout_rate': 0.2463020656852733, 'n_estimators': 305, 'criterion': 'squared_error', 'ccp_alpha': 1.0564947708849686, 'min_weight_fraction_leaf': 0.08760619313242886, 'max_features': None, 'min_impurity_decrease': 3.835139108190128e-06, 'validation_fraction': 0.4123056392425912, 'min_samples_split': 6, 'max_leaf_nodes': 16, 'min_samples_leaf': 16, 'max_depth': 2}. Best is trial 91 with value: 0.22373123233584108.
Fold 1 IBS: 0.23592681104551091
Fold 2 IBS: 0.20772256789057714
Fold 3 IBS: 0.2238628087409883
Fold 4 IBS: 0.22632996465532695
Fold 5 IBS: 0.21926583683453693
[I 2024-04-14 23:27:14,779] Trial 98 finished with value: 0.22262159783338803 and parameters: {'subsample': 0.6871257727531467, 'learning_rate': 0.09035412650367348, 'dropout_rate': 0.1154715714520811, 'n_estimators': 413, 'criterion': 'friedman_mse', 'ccp_alpha': 0.050290828631146894, 'min_weight_fraction_leaf': 0.0717973518747433, 'max_features': None, 'min_impurity_decrease': 8.847299946943358e-07, 'validation_fraction': 0.4879609273935703, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}. Best is trial 98 with value: 0.22262159783338803.
Fold 1 IBS: 0.24724710044658998
Fold 2 IBS: 0.23203988453792296

Fold 3 IBS: 0.22898186806977705
Fold 4 IBS: 0.24197477145927113
Fold 5 IBS: 0.22939559304809248
[I 2024-04-14 23:27:45,550] Trial 99 finished with value: 0.23592784351233073 and parameters: {'subsample': 0.679529118780463, 'learning_rate': 0.09119413615927978, 'dropout_rate': 0.10216550214025771, 'n_estimators': 411, 'criterion': 'friedman_mse', 'ccp_alpha': 1.716394824031096, 'min_weight_fraction_leaf': 0.07701366240523831, 'max_features': None, 'min_impurity_decrease': 9.975932931017948e-07, 'validation_fraction': 0.46082617508021007, 'min_samples_split': 11, 'max_leaf_nodes': 19, 'min_samples_leaf': 14, 'max_depth': 3}. Best is trial 98 with value: 0.22262159783338803.


* Best trial for IBS:
 FrozenTrial(number=98, state=TrialState.COMPLETE, values=[0.22262159783338803], datetime_start=datetime.datetime(2024, 4, 14, 23, 26, 40, 407865), datetime_complete=datetime.datetime(2024, 4, 14, 23, 27, 14, 778330), params={'subsample': 0.6871257727531467, 'learning_rate': 0.09035412650367348, 'dropout_rate': 0.1154715714520811, 'n_estimators': 413, 'criterion': 'friedman_mse', 'ccp_alpha': 0.050290828631146894, 'min_weight_fraction_leaf': 0.0717973518747433, 'max_features': None, 'min_impurity_decrease': 8.847299946943358e-07, 'validation_fraction': 0.4879609273935703, 'min_samples_split': 11, 'max_leaf_nodes': 18, 'min_samples_leaf': 13, 'max_depth': 3}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'criterion': CategoricalDistribution(choices=('friedman_mse', 'squared_error')), 'ccp_alpha': FloatDistribution(high=10.0, log=False, low=0.0, step=None), 'min_weight_fraction_leaf': FloatDistribution(high=0.5, log=False, low=0.0, step=None), 'max_features': CategoricalDistribution(choices=('auto', 'sqrt', 'log2', None, 0.1, 1)), 'min_impurity_decrease': FloatDistribution(high=0.1, log=True, low=1e-07, step=None), 'validation_fraction': FloatDistribution(high=1.0, log=False, low=0.0, step=None), 'min_samples_split': IntDistribution(high=20, log=False, low=2, step=1), 'max_leaf_nodes': IntDistribution(high=20, log=False, low=2, step=1), 'min_samples_leaf': IntDistribution(high=20, log=False, low=1, step=1), 'max_depth': IntDistribution(high=20, log=False, low=1, step=1)}, trial_id=98, value=None)


* Best Score for IBS:
 0.22262159783338803

In [178]:
train_cindex['GradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['GradientBoosting'] = np.round(study_ibs.best_value, 3)

In [179]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.738
train_ibs:  0.223

#### Test

In [180]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [181]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(GradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(GradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

GradientBoostingSurvivalAnalysis(ccp_alpha=0.02313127962403605,
                                 criterion='squared_error',
                                 dropout_rate=0.3476599176890519,
                                 learning_rate=0.03772869943983537, max_depth=4,
                                 max_features=1, max_leaf_nodes=18,
                                 min_impurity_decrease=1.0180375358163635e-06,
                                 min_samples_leaf=18, min_samples_split=18,
                                 min_weight_fraction_leaf=0.2716607703914049,
                                 n_estimators=392, random_state=123,
                                 subsample=0.9115482308909325,
                                 validation_fraction=0.9423719780700139)

C-index score: 0.514

GradientBoostingSurvivalAnalysis(ccp_alpha=0.050290828631146894,
                                 dropout_rate=0.1154715714520811,
                                 learning_rate=0.09035412650367348,
                                 max_leaf_nodes=18,
                                 min_impurity_decrease=8.847299946943358e-07,
                                 min_samples_leaf=13, min_samples_split=11,
                                 min_weight_fraction_leaf=0.0717973518747433,
                                 n_estimators=413, random_state=123,
                                 subsample=0.6871257727531467,
                                 validation_fraction=0.4879609273935703)

IBS: 0.231

In [182]:
# Saving the values to the dictionary 
test_cindex['GradientBoosting'] = c_index
test_ibs['GradientBoosting'] = ibs

### 8. ComponentwiseGradientBoostingSurvivalAnalysis

#### Train

In [183]:
# Setting the y format 
y = clinical_train[['DFS', 'event_DFS']]

In [184]:
def create_objective(model_class, metric, X, y):
    def objective(trial): 
        # Suggest values for hyperparameters
        subsample = trial.suggest_float("subsample", 0.1, 1)
        dropout_rate = trial.suggest_float("dropout_rate", 0.1, 1)
        n_estimators = trial.suggest_int("n_estimators", 1, 500)
        learning_rate = trial.suggest_float("learning_rate", 0.001, 0.1)
        
        # Create and fit survival model 
        model = model_class(subsample=subsample,
                            dropout_rate=dropout_rate,
                            n_estimators=n_estimators,
                            learning_rate=learning_rate,
                            random_state=123)
                
        scores = [] 
        
        skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=123)
        
        for k, (train_index, test_index) in enumerate(skf.split(X, y.iloc[:, 1])): 
            X_train, X_test = X.iloc[train_index], X.iloc[test_index]
            y_train_df, y_test_df = y.iloc[train_index], y.iloc[test_index]
            
            # y_train into array 
            y_train = [] 
            for i, j in zip(y_train_df['event_DFS'], y_train_df['DFS']): 
                y_train.append((i, j))
            y_train = np.array(y_train, dtype=[('status', bool), ('time', np.int32)])

            # y_test into array
            y_test = [] 
            for i, j in zip(y_test_df['event_DFS'], y_test_df['DFS']): 
                y_test.append((i, j))
            y_test = np.array(y_test, dtype=[('status', bool), ('time', np.int32)])

            # Robust Standardization
            excluded_columns = ['female', 
                                'cavum_oris',
                                'oropharynx',
                                'hypopharynx',
                                'larynx',
                                'histgrade_high',
                                'hpv_related',
                                'charlson',
                                'uicc8_III-IV'
                               ]
            excluded_columns = set(excluded_columns).intersection(X.columns)

            scaler = RobustScaler() 
            X_train_included = X_train.drop(excluded_columns, axis=1)
            X_test_included = X_test.drop(excluded_columns, axis=1)
                        
            if not X_train_included.empty and not X_test_included.empty:
                X_train_included_std = scaler.fit_transform(X_train_included)
                X_test_included_std = scaler.transform(X_test_included)
                
                # Concatenation
                X_train_std_df = pd.DataFrame(X_train_included_std, columns=X_train_included.columns, index=X_train_included.index)
                X_train_std = pd.concat([X_train_std_df, X_train[excluded_columns]], axis=1)

                X_test_std_df = pd.DataFrame(X_test_included_std, columns=X_test_included.columns, index=X_test_included.index)
                X_test_std = pd.concat([X_test_std_df, X_test[excluded_columns]], axis=1)
            
            else: 
                X_train_std = X_train
                X_test_std = X_test 
            
            model.fit(X_train_std, y_train)

            if metric == "c-index":
                # Make predictions using C-index 
                c_index_score = model.score(X_test_std, y_test)
                scores.append(c_index_score)
                print(f"Fold {k + 1} C-index: {c_index_score}")
                
            elif metric == "ibs":
                # Make predictions using IBS 
                lower, upper = np.percentile(y_test["time"], [10, 90])    
                times = np.arange(lower, upper)
                surv_prob = np.row_stack([fn(times) for fn in model.predict_survival_function(X_test_std)])
                ibs = integrated_brier_score(y_test, y_test, surv_prob, times)
                scores.append(ibs)
                print(f"Fold {k + 1} IBS: {ibs}")
            else:
                raise ValueError("Invalid metric. Use 'C-index' or 'ibs'.")
        
        # Return the mean of scores
        return np.mean(scores)
    
    return objective


# C-index
study_cindex = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=123))
objective_cindex = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "c-index", X_new, y)
study_cindex.optimize(objective_cindex, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for C-index: \n", study_cindex.best_trial)
print("\n")
print("* Best hyperparameters for C-index: \n", study_cindex.best_params)
print("\n")
print("* Best Score for C-index: \n", study_cindex.best_value)

# IBS
study_ibs = optuna.create_study(direction="minimize", sampler=optuna.samplers.TPESampler(seed=123))
objective_ibs = create_objective(ComponentwiseGradientBoostingSurvivalAnalysis, "ibs", X_new, y)
study_ibs.optimize(objective_ibs, n_trials=100, show_progress_bar=True)
print("\n")
print("* Best trial for IBS: \n", study_ibs.best_trial)
print("\n")
print("* Best hyperparameters for IBS: \n", study_ibs.best_params)
print("\n")
print("* Best Score for IBS: \n", study_ibs.best_value)

[I 2024-04-14 23:27:58,507] A new study created in memory with name: no-name-0044fd14-e42f-4c16-89d8-efd423c8015e

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:27:59,201] Trial 0 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:28:03,166] Trial 1 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.6232514766080982.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 23:28:04,173] Trial 2 finished with value: 0.6248486830300205 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 2 with value: 0.6248486830300205.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:28:05,859] Trial 3 finished with value: 0.6338486920671272 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 3 with value: 0.6338486920671272.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:07,835] Trial 4 finished with value: 0.6344206279599203 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 4 with value: 0.6344206279599203.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:28:10,278] Trial 5 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 4 with value: 0.6344206279599203.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 23:28:11,156] Trial 6 finished with value: 0.6241098457068107 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 4 with value: 0.6344206279599203.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:28:11,336] Trial 7 finished with value: 0.6319865279687434 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 4 with value: 0.6344206279599203.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:28:12,283] Trial 8 finished with value: 0.624787126680312 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 4 with value: 0.6344206279599203.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:28:14,975] Trial 9 finished with value: 0.623990313931308 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 4 with value: 0.6344206279599203.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:17,632] Trial 10 finished with value: 0.6406280851004389 and parameters: {'subsample': 0.1671153628558601, 'dropout_rate': 0.10958860356703534, 'n_estimators': 299, 'learning_rate': 0.0017980531969980576}. Best is trial 10 with value: 0.6406280851004389.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5829787234042553
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:28:20,698] Trial 11 finished with value: 0.6482706126490928 and parameters: {'subsample': 0.11557957726835853, 'dropout_rate': 0.10580803679784617, 'n_estimators': 324, 'learning_rate': 0.08933703080421439}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5872340425531914
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:28:23,246] Trial 12 finished with value: 0.6475280509808721 and parameters: {'subsample': 0.11211713718471546, 'dropout_rate': 0.10707700162921632, 'n_estimators': 311, 'learning_rate': 0.09635955935176935}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:25,856] Trial 13 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.9611940213633826, 'dropout_rate': 0.24994017950074404, 'n_estimators': 372, 'learning_rate': 0.09914998942829482}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:28,078] Trial 14 finished with value: 0.6468760304700026 and parameters: {'subsample': 0.11379276107227315, 'dropout_rate': 0.7248360093802153, 'n_estimators': 353, 'learning_rate': 0.09979016703322471}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:28:30,014] Trial 15 finished with value: 0.6382488034541979 and parameters: {'subsample': 0.27469317698066514, 'dropout_rate': 0.24086418138171567, 'n_estimators': 312, 'learning_rate': 0.08616677729964022}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:28:33,425] Trial 16 finished with value: 0.6429425098950168 and parameters: {'subsample': 0.21179284570182194, 'dropout_rate': 0.1020587806983512, 'n_estimators': 423, 'learning_rate': 0.08820363883892024}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6615969581749049
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:36,820] Trial 17 finished with value: 0.6360685045387116 and parameters: {'subsample': 0.3605205209589362, 'dropout_rate': 0.22654987460299786, 'n_estimators': 416, 'learning_rate': 0.08639690405722114}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 23:28:38,241] Trial 18 finished with value: 0.6304983909725402 and parameters: {'subsample': 0.35801092912005106, 'dropout_rate': 0.33602353085084236, 'n_estimators': 256, 'learning_rate': 0.08307767561539126}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876

Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:38,674] Trial 19 finished with value: 0.6443949846669678 and parameters: {'subsample': 0.10013306718236009, 'dropout_rate': 0.7254192287154788, 'n_estimators': 117, 'learning_rate': 0.09614402133777997}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:28:42,144] Trial 20 finished with value: 0.6399802791763081 and parameters: {'subsample': 0.2630057481431337, 'dropout_rate': 0.18040218016888274, 'n_estimators': 423, 'learning_rate': 0.07788582119853761}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:45,098] Trial 21 finished with value: 0.6468760304700026 and parameters: {'subsample': 0.11062421192073678, 'dropout_rate': 0.7075879968118339, 'n_estimators': 348, 'learning_rate': 0.09588015704350664}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:28:47,096] Trial 22 finished with value: 0.6383935351041692 and parameters: {'subsample': 0.17037433318378448, 'dropout_rate': 0.764223918656215, 'n_estimators': 305, 'learning_rate': 0.09979249643444077}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:28:49,334] Trial 23 finished with value: 0.6383935351041692 and parameters: {'subsample': 0.1882001920901971, 'dropout_rate': 0.5767392416088596, 'n_estimators': 339, 'learning_rate': 0.09228487500058613}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:28:51,257] Trial 24 finished with value: 0.6469992701562546 and parameters: {'subsample': 0.10032123431548137, 'dropout_rate': 0.9684931648209879, 'n_estimators': 388, 'learning_rate': 0.0802723125714484}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6566523605150214
[I 2024-04-14 23:28:53,694] Trial 25 finished with value: 0.6248486830300205 and parameters: {'subsample': 0.4133596270549855, 'dropout_rate': 0.9814337999737701, 'n_estimators': 405, 'learning_rate': 0.07897720038644866}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6652360515021459
[I 2024-04-14 23:28:55,514] Trial 26 finished with value: 0.6319945274886563 and parameters: {'subsample': 0.29436693962013616, 'dropout_rate': 0.30720738642318285, 'n_estimators': 245, 'learning_rate': 0.06349383809213646}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:28:59,698] Trial 27 finished with value: 0.6249682148055231 and parameters: {'subsample': 0.9555788020080305, 'dropout_rate': 0.6087801618108066, 'n_estimators': 456, 'learning_rate': 0.06676860919367211}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:29:01,971] Trial 28 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.6088999383640823, 'dropout_rate': 0.8192295755232234, 'n_estimators': 384, 'learning_rate': 0.08078072275147408}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:29:03,908] Trial 29 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.8699768148803853, 'dropout_rate': 0.41533846889329507, 'n_estimators': 322, 'learning_rate': 0.0892538312157202}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:05,590] Trial 30 finished with value: 0.63988236635136 and parameters: {'subsample': 0.21797436717278929, 'dropout_rate': 0.16903977002361698, 'n_estimators': 283, 'learning_rate': 0.044040119088987244}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:07,700] Trial 31 finished with value: 0.6445504490746539 and parameters: {'subsample': 0.12927234629827838, 'dropout_rate': 0.9690972067181969, 'n_estimators': 383, 'learning_rate': 0.09233052029041879}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:10,607] Trial 32 finished with value: 0.6477886506494983 and parameters: {'subsample': 0.10197013154249483, 'dropout_rate': 0.9006234235846082, 'n_estimators': 449, 'learning_rate': 0.09214772080187031}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:14,858] Trial 33 finished with value: 0.6383319787544608 and parameters: {'subsample': 0.16421336528135802, 'dropout_rate': 0.9268713272970187, 'n_estimators': 453, 'learning_rate': 0.07794503671868204}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:29:18,937] Trial 34 finished with value: 0.6350979089334217 and parameters: {'subsample': 0.23087858755854718, 'dropout_rate': 0.8311198269799329, 'n_estimators': 477, 'learning_rate': 0.07104054321866782}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:29:20,286] Trial 35 finished with value: 0.6289120707434576 and parameters: {'subsample': 0.29440822025230656, 'dropout_rate': 0.9999753567840282, 'n_estimators': 232, 'learning_rate': 0.09340164470114515}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:24,441] Trial 36 finished with value: 0.6407118112305928 and parameters: {'subsample': 0.1472825644233607, 'dropout_rate': 0.45922216511134195, 'n_estimators': 490, 'learning_rate': 0.07364671948774787}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:27,734] Trial 37 finished with value: 0.6367530907811381 and parameters: {'subsample': 0.22877221290518623, 'dropout_rate': 0.5102437401048863, 'n_estimators': 437, 'learning_rate': 0.059207327336158105}. Best is trial 11 with value: 0.6482706126490928.

Fold 1 C-index: 0.5697211155378487
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:29:30,037] Trial 38 finished with value: 0.631313522170144 and parameters: {'subsample': 0.3297325755614151, 'dropout_rate': 0.8867789132968811, 'n_estimators': 392, 'learning_rate': 0.08480908032505553}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:30,688] Trial 39 finished with value: 0.6383467162791461 and parameters: {'subsample': 0.1910828860959901, 'dropout_rate': 0.29848665859072016, 'n_estimators': 145, 'learning_rate': 0.06892741183938003}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:29:30,863] Trial 40 finished with value: 0.624171402056519 and parameters: {'subsample': 0.43117832251264454, 'dropout_rate': 0.7942402623613096, 'n_estimators': 44, 'learning_rate': 0.09083529332655457}. Best is trial 11 with value: 0.6482706126490928.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:32,733] Trial 41 finished with value: 0.6486180955287313 and parameters: {'subsample': 0.10471436370118233, 'dropout_rate': 0.9432108264211424, 'n_estimators': 354, 'learning_rate': 0.0993939723603888}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:33,980] Trial 42 finished with value: 0.6454856628776512 and parameters: {'subsample': 0.10319905773816981, 'dropout_rate': 0.9428165272301137, 'n_estimators': 279, 'learning_rate': 0.09477321051183016}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:35,655] Trial 43 finished with value: 0.6399655416516228 and parameters: {'subsample': 0.1582430717253308, 'dropout_rate': 0.8684114133163081, 'n_estimators': 331, 'learning_rate': 0.0844262120808547}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.7034220532319392
Fold 5 C-index: 0.6609442060085837
[I 2024-04-14 23:29:35,738] Trial 44 finished with value: 0.6448727156455619 and parameters: {'subsample': 0.24718870034059304, 'dropout_rate': 0.9241820789065098, 'n_estimators': 3, 'learning_rate': 0.08951219679204844}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:29:38,229] Trial 45 finished with value: 0.6232514766080982 and parameters: {'subsample': 0.7937809606966539, 'dropout_rate': 0.20601602290044557, 'n_estimators': 362, 'learning_rate': 0.02274904980797578}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:40,030] Trial 46 finished with value: 0.647067707931832 and parameters: {'subsample': 0.13247691307003695, 'dropout_rate': 0.14648424644002478, 'n_estimators': 281, 'learning_rate': 0.07635421514953118}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:41,169] Trial 47 finished with value: 0.6480309982681967 and parameters: {'subsample': 0.1441055934293145, 'dropout_rate': 0.13054548795135493, 'n_estimators': 215, 'learning_rate': 0.09648686804984326}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:42,329] Trial 48 finished with value: 0.6447173505050706 and parameters: {'subsample': 0.19286527393095337, 'dropout_rate': 0.139424928912732, 'n_estimators': 212, 'learning_rate': 0.09967166220740545}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:43,361] Trial 49 finished with value: 0.6437609415945751 and parameters: {'subsample': 0.14597679593315122, 'dropout_rate': 0.10625636287606482, 'n_estimators': 187, 'learning_rate': 0.00524351186486742}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:29:44,903] Trial 50 finished with value: 0.6416354610240246 and parameters: {'subsample': 0.30761800010369206, 'dropout_rate': 0.19987153451840467, 'n_estimators': 233, 'learning_rate': 0.09624719899312528}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:46,705] Trial 51 finished with value: 0.6461702491200778 and parameters: {'subsample': 0.14471221479842475, 'dropout_rate': 0.15451447610093666, 'n_estimators': 286, 'learning_rate': 0.0873986677333669}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:48,667] Trial 52 finished with value: 0.6476659617931376 and parameters: {'subsample': 0.19998331446755446, 'dropout_rate': 0.13211371506312394, 'n_estimators': 302, 'learning_rate': 0.09521799369396833}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:29:49,405] Trial 53 finished with value: 0.6274237903261579 and parameters: {'subsample': 0.5690120024759672, 'dropout_rate': 0.28586431194579437, 'n_estimators': 165, 'learning_rate': 0.0958598482701556}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:51,107] Trial 54 finished with value: 0.6462209192769468 and parameters: {'subsample': 0.20042122380027189, 'dropout_rate': 0.12671960498863988, 'n_estimators': 263, 'learning_rate': 0.09129126427434006}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:54,150] Trial 55 finished with value: 0.6416134182304141 and parameters: {'subsample': 0.2525262633304453, 'dropout_rate': 0.23125369868510462, 'n_estimators': 316, 'learning_rate': 0.08255787762808443}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475

Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:29:56,175] Trial 56 finished with value: 0.6391903478531732 and parameters: {'subsample': 0.18022329642874463, 'dropout_rate': 0.6470926501057392, 'n_estimators': 301, 'learning_rate': 0.09681230911684639}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:29:58,857] Trial 57 finished with value: 0.6460212422952046 and parameters: {'subsample': 0.13165605060453595, 'dropout_rate': 0.3649163833130069, 'n_estimators': 349, 'learning_rate': 0.0997291184079334}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:30:01,782] Trial 58 finished with value: 0.6282353405998473 and parameters: {'subsample': 0.6810537336561748, 'dropout_rate': 0.1910107494795735, 'n_estimators': 332, 'learning_rate': 0.08870192859690751}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:30:03,764] Trial 59 finished with value: 0.6469086626002316 and parameters: {'subsample': 0.10183265607410649, 'dropout_rate': 0.2645251087109975, 'n_estimators': 245, 'learning_rate': 0.09339322934480054}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:07,068] Trial 60 finished with value: 0.6454856628776512 and parameters: {'subsample': 0.20574635949965217, 'dropout_rate': 0.12256906619026797, 'n_estimators': 364, 'learning_rate': 0.0860647234047792}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:09,212] Trial 61 finished with value: 0.6478971528110649 and parameters: {'subsample': 0.13316352431570933, 'dropout_rate': 0.15916090783934952, 'n_estimators': 271, 'learning_rate': 0.09663332600821103}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:10,290] Trial 62 finished with value: 0.6455684143348579 and parameters: {'subsample': 0.16422303726919274, 'dropout_rate': 0.10129675547009459, 'n_estimators': 207, 'learning_rate': 0.0958657367344994}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:12,199] Trial 63 finished with value: 0.6470824454565174 and parameters: {'subsample': 0.1308716913944263, 'dropout_rate': 0.16748645002706178, 'n_estimators': 299, 'learning_rate': 0.09224713921269888}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:30:13,857] Trial 64 finished with value: 0.6431494921456841 and parameters: {'subsample': 0.27127460198632286, 'dropout_rate': 0.21313548952551475, 'n_estimators': 266, 'learning_rate': 0.09802837699819798}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:15,200] Trial 65 finished with value: 0.6446167044423203 and parameters: {'subsample': 0.2330764184284433, 'dropout_rate': 0.17026153335936856, 'n_estimators': 234, 'learning_rate': 0.0822151082356204}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:17,273] Trial 66 finished with value: 0.646047009433826 and parameters: {'subsample': 0.17881900681359358, 'dropout_rate': 0.2650578475998151, 'n_estimators': 316, 'learning_rate': 0.08910499925884582}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:30:20,819] Trial 67 finished with value: 0.6472562283128032 and parameters: {'subsample': 0.1216056358564787, 'dropout_rate': 0.13386480557384356, 'n_estimators': 409, 'learning_rate': 0.0938433587100198}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:23,407] Trial 68 finished with value: 0.6437462040698897 and parameters: {'subsample': 0.1544310565963431, 'dropout_rate': 0.1844510052428059, 'n_estimators': 296, 'learning_rate': 0.03557646010123462}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:26,103] Trial 69 finished with value: 0.6407554729747578 and parameters: {'subsample': 0.2130395911423627, 'dropout_rate': 0.40498984510005687, 'n_estimators': 337, 'learning_rate': 0.08541699360240503}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:30:27,412] Trial 70 finished with value: 0.6321935102194108 and parameters: {'subsample': 0.38956476244889804, 'dropout_rate': 0.33967441928687825, 'n_estimators': 220, 'learning_rate': 0.09733795216652556}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6768060836501901
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:30:30,741] Trial 71 finished with value: 0.6429862986260166 and parameters: {'subsample': 0.11721243365128992, 'dropout_rate': 0.151117463899618, 'n_estimators': 403, 'learning_rate': 0.09403700330803805}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7209302325581395
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:30:35,185] Trial 72 finished with value: 0.64398222109261 and parameters: {'subsample': 0.103713649896811, 'dropout_rate': 0.1257671874876114, 'n_estimators': 443, 'learning_rate': 0.0999810517249613}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5737051792828686
Fold 2 C-index: 0.7170542635658915
Fold 3 C-index: 0.574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:30:38,954] Trial 73 finished with value: 0.6408893019976281 and parameters: {'subsample': 0.12531540142024392, 'dropout_rate': 0.10495942741643126, 'n_estimators': 422, 'learning_rate': 0.09332972215976093}. Best is trial 41 with value: 0.6486180955287313.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:42,877] Trial 74 finished with value: 0.6484553422863815 and parameters: {'subsample': 0.174435767387568, 'dropout_rate': 0.23511761812080736, 'n_estimators': 465, 'learning_rate': 0.08947815189449172}. Best is trial 41 with value: 0.6486180955287313.

Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:46,712] Trial 75 finished with value: 0.6492700496409289 and parameters: {'subsample': 0.16800686813829968, 'dropout_rate': 0.23137733808808567, 'n_estimators': 458, 'learning_rate': 0.08860773948540256}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5936254980079682
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:50,498] Trial 76 finished with value: 0.6484553422863815 and parameters: {'subsample': 0.17715878773642196, 'dropout_rate': 0.23933306680560718, 'n_estimators': 465, 'learning_rate': 0.0905147414687194}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:30:56,401] Trial 77 finished with value: 0.6476585295373775 and parameters: {'subsample': 0.17155029924256332, 'dropout_rate': 0.24010466678021705, 'n_estimators': 495, 'learning_rate': 0.0889810439564971}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5776892430278885
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6501901140684411
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:01,568] Trial 78 finished with value: 0.6329144529370772 and parameters: {'subsample': 0.3212721105651428, 'dropout_rate': 0.3164793407493782, 'n_estimators': 463, 'learning_rate': 0.082775094938708}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6695278969957081
[I 2024-04-14 23:31:06,051] Trial 79 finished with value: 0.6397991910510971 and parameters: {'subsample': 0.22909477232315287, 'dropout_rate': 0.22402836752255373, 'n_estimators': 472, 'learning_rate': 0.07723699472960002}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5617529880478087
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:09,241] Trial 80 finished with value: 0.6290573532233199 and parameters: {'subsample': 0.45334769335248726, 'dropout_rate': 0.2844745139531642, 'n_estimators': 436, 'learning_rate': 0.08022609677442455}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5531914893617021
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:31:13,834] Trial 81 finished with value: 0.6469053785325384 and parameters: {'subsample': 0.1909324914291439, 'dropout_rate': 0.1915777639037886, 'n_estimators': 484, 'learning_rate': 0.09098931976672621}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7131782945736435
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:31:17,433] Trial 82 finished with value: 0.6454088181733664 and parameters: {'subsample': 0.15073611068215856, 'dropout_rate': 0.5095499192980961, 'n_estimators': 449, 'learning_rate': 0.08822877817885005}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6653992395437263
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:31:22,109] Trial 83 finished with value: 0.6392050853778585 and parameters: {'subsample': 0.25092128899085286, 'dropout_rate': 0.2611502930386304, 'n_estimators': 498, 'learning_rate': 0.08673333063694418}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:27,192] Trial 84 finished with value: 0.6477054753492355 and parameters: {'subsample': 0.1751008193163871, 'dropout_rate': 0.15954260506966278, 'n_estimators': 474, 'learning_rate': 0.09146086526177581}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:30,142] Trial 85 finished with value: 0.6375351660054568 and parameters: {'subsample': 0.1676186554730635, 'dropout_rate': 0.8430789363882925, 'n_estimators': 467, 'learning_rate': 0.05404134590388063}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7093023255813954
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6730038022813688
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:33,418] Trial 86 finished with value: 0.6414938864549116 and parameters: {'subsample': 0.1374151532902582, 'dropout_rate': 0.89683207720842, 'n_estimators': 482, 'learning_rate': 0.07508572574984365}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:31:37,215] Trial 87 finished with value: 0.644678260792029 and parameters: {'subsample': 0.21296350141617598, 'dropout_rate': 0.16847976348673274, 'n_estimators': 435, 'learning_rate': 0.08405924798518011}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7054263565891473
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:31:40,905] Trial 88 finished with value: 0.6399655416516228 and parameters: {'subsample': 0.28539539807143866, 'dropout_rate': 0.21246967977162023, 'n_estimators': 457, 'learning_rate': 0.09030034275428493}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6425855513307985
Fold 5 C-index: 0.6523605150214592
[I 2024-04-14 23:31:43,461] Trial 89 finished with value: 0.6240119328818624 and parameters: {'subsample': 0.5132134792119997, 'dropout_rate': 0.7768207264522797, 'n_estimators': 431, 'learning_rate': 0.09811058639859867}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7015503875968992
Fold 3 C-index: 0.5574468085106383
Fold 4 C-index: 0.6692015209125475
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:46,373] Trial 90 finished with value: 0.6383319787544608 and parameters: {'subsample': 0.17933901303612043, 'dropout_rate': 0.9464234064155247, 'n_estimators': 474, 'learning_rate': 0.09136746141039755}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:49,371] Trial 91 finished with value: 0.6469992701562546 and parameters: {'subsample': 0.1565488345066457, 'dropout_rate': 0.15287413033769717, 'n_estimators': 395, 'learning_rate': 0.0949539774122884}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5856573705179283
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6806083650190115
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:52,685] Trial 92 finished with value: 0.646093955245684 and parameters: {'subsample': 0.19756082044947185, 'dropout_rate': 0.12808553137384152, 'n_estimators': 373, 'learning_rate': 0.08734771819130464}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5657370517928287
Fold 2 C-index: 0.6976744186046512
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6387832699619772

Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:55,040] Trial 93 finished with value: 0.6275433221016604 and parameters: {'subsample': 0.99766016156918, 'dropout_rate': 0.2393812839232397, 'n_estimators': 254, 'learning_rate': 0.09745344090229416}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7325581395348837
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6738197424892703
[I 2024-04-14 23:31:59,133] Trial 94 finished with value: 0.6476838563986812 and parameters: {'subsample': 0.1188023212860733, 'dropout_rate': 0.18619257295551966, 'n_estimators': 421, 'learning_rate': 0.09234180915846192}. Best is trial 75 with value: 0.6492700496409289.
Fold 1 C-index: 0.5896414342629482
Fold 2 C-index: 0.7248062015503876
Fold 3 C-index: 0.5659574468085107
Fold 4 C-index: 0.688212927756654
Fold 5 C-index: 0.6824034334763949
[I 2024-04-14 23:32:02,318] Trial 95 finished with value: 0.6502042887709791 and parameters: {'subsample': 0.10067217830702918, 'dropout_rate': 0.20031989847751397, 'n_estimators': 416, 'learning_rate': 0.09260941413753233}. Best is trial 95 with value: 0.6502042887709791.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:32:06,976] Trial 96 finished with value: 0.6503202231883056 and parameters: {'subsample': 0.10110319978064844, 'dropout_rate': 0.2525866290623745, 'n_estimators': 446, 'learning_rate': 0.0801524070565027}. Best is trial 96 with value: 0.6503202231883056.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5617021276595745
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:32:11,792] Trial 97 finished with value: 0.6469159678691567 and parameters: {'subsample': 0.1428225879209601, 'dropout_rate': 0.28378768487545125, 'n_estimators': 448, 'learning_rate': 0.05810785621442836}. Best is trial 96 with value: 0.6503202231883056.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5787234042553191
Fold 4 C-index: 0.6844106463878327
Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:32:14,725] Trial 98 finished with value: 0.6503202231883056 and parameters: {'subsample': 0.1034910315750943, 'dropout_rate': 0.33000598371489964, 'n_estimators': 410, 'learning_rate': 0.08062035216684603}. Best is trial 96 with value: 0.6503202231883056.
Fold 1 C-index: 0.5816733067729084
Fold 2 C-index: 0.7286821705426356
Fold 3 C-index: 0.5702127659574469
Fold 4 C-index: 0.6844106463878327

[I 2024-04-14 23:32:17,582] A new study created in memory with name: no-name-326756db-390d-46f1-a21e-9cb9a32216ee

Fold 5 C-index: 0.6781115879828327
[I 2024-04-14 23:32:17,573] Trial 99 finished with value: 0.6486180955287313 and parameters: {'subsample': 0.10089406734368996, 'dropout_rate': 0.3559285081412586, 'n_estimators': 408, 'learning_rate': 0.080007904417688}. Best is trial 96 with value: 0.6503202231883056.


* Best trial for C-index:
 FrozenTrial(number=96, state=TrialState.COMPLETE, values=[0.6503202231883056], datetime_start=datetime.datetime(2024, 4, 14, 23, 32, 2, 321190), datetime_complete=datetime.datetime(2024, 4, 14, 23, 32, 6, 974928), params={'subsample': 0.10110319978064844, 'dropout_rate': 0.2525866290623745, 'n_estimators': 446, 'learning_rate': 0.0801524070565027}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=96, value=None)


* Best hyperparameters for C-index:
 {'subsample': 0.10110319978064844, 'dropout_rate': 0.2525866290623745, 'n_estimators': 446, 'learning_rate': 0.0801524070565027}


* Best Score for C-index:
 0.6503202231883056

  0%|          | 0/100 [00:00<?, ?it/s]

Fold 1 IBS: 0.32184685283009035
Fold 2 IBS: 0.24269519626988276
Fold 3 IBS: 0.32845286241320015
Fold 4 IBS: 0.28361609336040605
Fold 5 IBS: 0.2729305473144034
[I 2024-04-14 23:32:18,076] Trial 0 finished with value: 0.2899083104375965 and parameters: {'subsample': 0.7268222670380755, 'dropout_rate': 0.3575254014553415, 'n_estimators': 114, 'learning_rate': 0.05558016213920623}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.42279422613772155
Fold 2 IBS: 0.3901128382737591
Fold 3 IBS: 0.39247472286878254
Fold 4 IBS: 0.36956665696576196
Fold 5 IBS: 0.3399595615106552
[I 2024-04-14 23:32:22,006] Trial 1 finished with value: 0.3829816011513361 and parameters: {'subsample': 0.7475220728070068, 'dropout_rate': 0.4807958141120149, 'n_estimators': 491, 'learning_rate': 0.06879814411990147}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38477559331402056
Fold 2 IBS: 0.3002072982420411
Fold 3 IBS: 0.37939668767639545
Fold 4 IBS: 0.3096779826388825
Fold 5 IBS: 0.3252308860734576
[I 2024-04-14 23:32:22,763] Trial 2 finished with value: 0.33985768958895946 and parameters: {'subsample': 0.5328387113359249, 'dropout_rate': 0.45290576637473545, 'n_estimators': 172, 'learning_rate': 0.07317592103102012}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38791718483853127
Fold 2 IBS: 0.28308398609663094
Fold 3 IBS: 0.38075337593630443
Fold 4 IBS: 0.30896380743221213
Fold 5 IBS: 0.33290864228938033
[I 2024-04-14 23:32:23,776] Trial 3 finished with value: 0.3387253993186118 and parameters: {'subsample': 0.494715020211662, 'dropout_rate': 0.15371010694861154, 'n_estimators': 200, 'learning_rate': 0.07406154516747154}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.38792738170860425
Fold 2 IBS: 0.2795795393275598
Fold 3 IBS: 0.3843436493133732
Fold 4 IBS: 0.30694108138179393
Fold 5 IBS: 0.3398256145059637
[I 2024-04-14 23:32:25,380] Trial 4 finished with value: 0.339723453247459 and parameters: {'subsample': 0.26424255740815, 'dropout_rate': 0.2579065805327433, 'n_estimators': 266, 'learning_rate': 0.05365093112258974}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.41105192261386453
Fold 2 IBS: 0.3777174719916462
Fold 3 IBS: 0.3915300176353505
Fold 4 IBS: 0.3447295660931382
Fold 5 IBS: 0.32992002164058554
[I 2024-04-14 23:32:27,336] Trial 5 finished with value: 0.370989799994917 and parameters: {'subsample': 0.6709608626961889, 'dropout_rate': 0.8644886146700106, 'n_estimators': 363, 'learning_rate': 0.061491327557080706}. Best is trial 0 with value: 0.2899083104375965.
Fold 1 IBS: 0.2950866836605978
Fold 2 IBS: 0.21617356864727175
Fold 3 IBS: 0.2960476577766528
Fold 4 IBS: 0.26116838532173825
Fold 5 IBS: 0.2492059247499634
[I 2024-04-14 23:32:28,257] Trial 6 finished with value: 0.2635364440312448 and parameters: {'subsample': 0.7501990443131994, 'dropout_rate': 0.39066302246786044, 'n_estimators': 181, 'learning_rate': 0.023598059857016608}. Best is trial 6 with value: 0.2635364440312448.
Fold 1 IBS: 0.2525596717266013
Fold 2 IBS: 0.2009504851975363
Fold 3 IBS: 0.2554759579529817
Fold 4 IBS: 0.22423261256383803
Fold 5 IBS: 0.2116650686406854
[I 2024-04-14 23:32:28,502] Trial 7 finished with value: 0.22897675921632854 and parameters: {'subsample': 0.36434264174994646, 'dropout_rate': 0.667878511469039, 'n_estimators': 47, 'learning_rate': 0.043936416095273295}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.32773085091505505
Fold 2 IBS: 0.24764667449835662
Fold 3 IBS: 0.3381279691027075
Fold 4 IBS: 0.28727873359875167
Fold 5 IBS: 0.2819856805230031
[I 2024-04-14 23:32:29,628] Trial 8 finished with value: 0.2965539817275748 and parameters: {'subsample': 0.4877764869966794, 'dropout_rate': 0.5443165878852756, 'n_estimators': 213, 'learning_rate': 0.03191386107427406}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.4128629984024713
Fold 2 IBS: 0.3805312612875153
Fold 3 IBS: 0.39180424534594577
Fold 4 IBS: 0.3483594650353357
Fold 5 IBS: 0.3350263678028636
[I 2024-04-14 23:32:32,800] Trial 9 finished with value: 0.3737168675748263 and parameters: {'subsample': 0.4837161762665274, 'dropout_rate': 0.9040502468054213, 'n_estimators': 473, 'learning_rate': 0.050681830912549325}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24690378026135393
Fold 2 IBS: 0.230918196199329
Fold 3 IBS: 0.2288651535714008
Fold 4 IBS: 0.24118860634197958
Fold 5 IBS: 0.22809859267819335
[I 2024-04-14 23:32:33,002] Trial 10 finished with value: 0.23519486581045132 and parameters: {'subsample': 0.985919291330434, 'dropout_rate': 0.7167862478384984, 'n_estimators': 24, 'learning_rate': 0.0017980531969980576}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24596520377467238
Fold 2 IBS: 0.22745516260233242
Fold 3 IBS: 0.22872408268029404
Fold 4 IBS: 0.23875682318201075
Fold 5 IBS: 0.22421110618785597
[I 2024-04-14 23:32:33,092] Trial 11 finished with value: 0.2330224756854331 and parameters: {'subsample': 0.9892976403836158, 'dropout_rate': 0.7190576071046072, 'n_estimators': 2, 'learning_rate': 0.0920832985456782}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.27231268325612534
Fold 2 IBS: 0.20918528642133735
Fold 3 IBS: 0.3057008256941006
Fold 4 IBS: 0.2477920370314576
Fold 5 IBS: 0.24461914425255768
[I 2024-04-14 23:32:33,306] Trial 12 finished with value: 0.2559219953311157 and parameters: {'subsample': 0.13297468819891436, 'dropout_rate': 0.711571026552851, 'n_estimators': 53, 'learning_rate': 0.09635955935176935}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24540145164058172
Fold 2 IBS: 0.22486461618174694
Fold 3 IBS: 0.2288799372028231
Fold 4 IBS: 0.23700499011587697
Fold 5 IBS: 0.22141183261877637
[I 2024-04-14 23:32:33,415] Trial 13 finished with value: 0.23151256555196104 and parameters: {'subsample': 0.9898470756659337, 'dropout_rate': 0.695526957994077, 'n_estimators': 3, 'learning_rate': 0.09855521540419598}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.2801288012575852
Fold 2 IBS: 0.20642643701643856
Fold 3 IBS: 0.2855821246683042
Fold 4 IBS: 0.2448269379427668
Fold 5 IBS: 0.23496945372244868
[I 2024-04-14 23:32:33,791] Trial 14 finished with value: 0.2503867509215087 and parameters: {'subsample': 0.3396588574455943, 'dropout_rate': 0.6361246097272036, 'n_estimators': 102, 'learning_rate': 0.035476350988955505}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.34250383730825085
Fold 2 IBS: 0.2562261533432662
Fold 3 IBS: 0.35681785243304703
Fold 4 IBS: 0.2914232791743898
Fold 5 IBS: 0.29999553893473496
[I 2024-04-14 23:32:34,176] Trial 15 finished with value: 0.3093933322387378 and parameters: {'subsample': 0.3199040019429541, 'dropout_rate': 0.8008445383221042, 'n_estimators': 98, 'learning_rate': 0.08616677729964022}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.35027400369565387
Fold 2 IBS: 0.2538714030013387
Fold 3 IBS: 0.36698552210014895
Fold 4 IBS: 0.29062056089536875
Fold 5 IBS: 0.31975716907466056
[I 2024-04-14 23:32:35,687] Trial 16 finished with value: 0.3163017317534341 and parameters: {'subsample': 0.10330987234502886, 'dropout_rate': 0.9733961081825167, 'n_estimators': 290, 'learning_rate': 0.03937008871594785}. Best is trial 7 with value: 0.22897675921632854.
Fold 1 IBS: 0.24607714741491096
Fold 2 IBS: 0.21115546325606438
Fold 3 IBS: 0.23474191594216773
Fold 4 IBS: 0.2296381561690892
Fold 5 IBS: 0.21122928902161456
[I 2024-04-14 23:32:35,996] Trial 17 finished with value: 0.2265683943607694 and parameters: {'subsample': 0.873850481285158, 'dropout_rate': 0.6004730897368156, 'n_estimators': 62, 'learning_rate': 0.01626030932876789}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2883901804573134
Fold 2 IBS: 0.2112037980068735
Fold 3 IBS: 0.28770446755792806
Fold 4 IBS: 0.2544520687837577
Fold 5 IBS: 0.2431612806129336
[I 2024-04-14 23:32:38,244] Trial 18 finished with value: 0.2569823590837612 and parameters: {'subsample': 0.8595216848981485, 'dropout_rate': 0.599936371320666, 'n_estimators': 336, 'learning_rate': 0.011281697111409719}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.27019935319228533
Fold 2 IBS: 0.20101355307479882
Fold 3 IBS: 0.27495840642227154

Fold 4 IBS: 0.2403770465027076
Fold 5 IBS: 0.22389919673997055
[I 2024-04-14 23:32:38,911] Trial 19 finished with value: 0.24208951118640676 and parameters: {'subsample': 0.3892284838807411, 'dropout_rate': 0.5354432466556798, 'n_estimators': 131, 'learning_rate': 0.023294697221931306}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24532728078212304
Fold 2 IBS: 0.21338053568843193
Fold 3 IBS: 0.23280583204014674
Fold 4 IBS: 0.23050963160208696
Fold 5 IBS: 0.21229213294998353
[I 2024-04-14 23:32:39,243] Trial 20 finished with value: 0.22686308261255445 and parameters: {'subsample': 0.6210873354088753, 'dropout_rate': 0.7933084651006226, 'n_estimators': 66, 'learning_rate': 0.013007963411749002}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480948267779246
Fold 2 IBS: 0.217894217650721
Fold 3 IBS: 0.23043919128917217
Fold 4 IBS: 0.23275995527788665
Fold 5 IBS: 0.215372968667489
[I 2024-04-14 23:32:39,527] Trial 21 finished with value: 0.22825516311261226 and parameters: {'subsample': 0.6393109031524401, 'dropout_rate': 0.8419340907581221, 'n_estimators': 66, 'learning_rate': 0.009243017562009487}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24643766317823718
Fold 2 IBS: 0.22924023219100237
Fold 3 IBS: 0.2287550024184287
Fold 4 IBS: 0.2400059006469264
Fold 5 IBS: 0.2262805735657194
[I 2024-04-14 23:32:39,821] Trial 22 finished with value: 0.23414387440006285 and parameters: {'subsample': 0.6537769964653461, 'dropout_rate': 0.8093716219515759, 'n_estimators': 77, 'learning_rate': 0.0014039455806401802}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.257478169662288
Fold 2 IBS: 0.20248903467735407
Fold 3 IBS: 0.252469752257427
Fold 4 IBS: 0.23159280968783177
Fold 5 IBS: 0.2169495351817077
[I 2024-04-14 23:32:40,390] Trial 23 finished with value: 0.2321958602933217 and parameters: {'subsample': 0.8534306852041174, 'dropout_rate': 0.801007553345817, 'n_estimators': 146, 'learning_rate': 0.013693154749890787}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24591385980787991
Fold 2 IBS: 0.21157801995971165
Fold 3 IBS: 0.23448495664364996
Fold 4 IBS: 0.229737329537672
Fold 5 IBS: 0.2112912785040094
[I 2024-04-14 23:32:40,674] Trial 24 finished with value: 0.22660108889058458 and parameters: {'subsample': 0.6057018904919792, 'dropout_rate': 0.9862533241546715, 'n_estimators': 62, 'learning_rate': 0.01572471796157672}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2756443151410581
Fold 2 IBS: 0.20473874541146792
Fold 3 IBS: 0.27375023358490214
Fold 4 IBS: 0.2440459127498442
Fold 5 IBS: 0.23246982801186947
[I 2024-04-14 23:32:41,242] Trial 25 finished with value: 0.2461298069798284 and parameters: {'subsample': 0.8655825350862807, 'dropout_rate': 0.991151252373464, 'n_estimators': 145, 'learning_rate': 0.0210314188428598}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.32538815518873926
Fold 2 IBS: 0.2468744663909679
Fold 3 IBS: 0.3332171412462654
Fold 4 IBS: 0.28581063346445296
Fold 5 IBS: 0.2781065825703804
[I 2024-04-14 23:32:42,240] Trial 26 finished with value: 0.29387939577216116 and parameters: {'subsample': 0.5978333574014947, 'dropout_rate': 0.8982223660451839, 'n_estimators': 222, 'learning_rate': 0.029166999751579693}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24492083546093882
Fold 2 IBS: 0.21628333393840363
Fold 3 IBS: 0.23138494832945591
Fold 4 IBS: 0.23162572469168902
Fold 5 IBS: 0.21394160498647347
[I 2024-04-14 23:32:42,439] Trial 27 finished with value: 0.2276312894813922 and parameters: {'subsample': 0.7973831324954838, 'dropout_rate': 0.9591162049738791, 'n_estimators': 39, 'learning_rate': 0.018143610116936895}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24503999552218353
Fold 2 IBS: 0.21507419381927734
Fold 3 IBS: 0.23200152410434108
Fold 4 IBS: 0.23109618679052704
Fold 5 IBS: 0.21308573107611234
[I 2024-04-14 23:32:42,773] Trial 28 finished with value: 0.22725952626248827 and parameters: {'subsample': 0.5742192061348756, 'dropout_rate': 0.920234801468329, 'n_estimators': 86, 'learning_rate': 0.008921459414064498}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3030591065047406
Fold 2 IBS: 0.22336679794652556
Fold 3 IBS: 0.3044396799522218
Fold 4 IBS: 0.2678287080975696
Fold 5 IBS: 0.25695858296703405
[I 2024-04-14 23:32:43,300] Trial 29 finished with value: 0.2711305750936183 and parameters: {'subsample': 0.6850952456167174, 'dropout_rate': 0.7643659553187094, 'n_estimators': 112, 'learning_rate': 0.04248605264426071}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.30057401042692355
Fold 2 IBS: 0.22109327570196485
Fold 3 IBS: 0.30174720098020524
Fold 4 IBS: 0.2651400266811706
Fold 5 IBS: 0.2537066735825353
[I 2024-04-14 23:32:44,028] Trial 30 finished with value: 0.26845223747455993 and parameters: {'subsample': 0.9166631566118534, 'dropout_rate': 0.6038945600293156, 'n_estimators': 166, 'learning_rate': 0.027648893219016982}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24486090508062983
Fold 2 IBS: 0.21682633491745948
Fold 3 IBS: 0.23109486987541575
Fold 4 IBS: 0.23197486961623204
Fold 5 IBS: 0.21430589760825255
[I 2024-04-14 23:32:44,339] Trial 31 finished with value: 0.22781257541959793 and parameters: {'subsample': 0.580266273279712, 'dropout_rate': 0.9271779254835972, 'n_estimators': 89, 'learning_rate': 0.007554955553126899}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24480604491948196
Fold 2 IBS: 0.21843195389759032
Fold 3 IBS: 0.23024293091022538
Fold 4 IBS: 0.23321504110381971
Fold 5 IBS: 0.21568765554273314
[I 2024-04-14 23:32:44,503] Trial 32 finished with value: 0.2284767252747701 and parameters: {'subsample': 0.7276466032162393, 'dropout_rate': 0.8648618701493432, 'n_estimators': 37, 'learning_rate': 0.015821999327691336}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24434472696223403
Fold 2 IBS: 0.22006483265789914
Fold 3 IBS: 0.23001501374819164
Fold 4 IBS: 0.23353575529737952
Fold 5 IBS: 0.21714562015932423
[I 2024-04-14 23:32:44,773] Trial 33 finished with value: 0.2290211897650057 and parameters: {'subsample': 0.42583224460357205, 'dropout_rate': 0.9322585736914469, 'n_estimators': 74, 'learning_rate': 0.007128988064747212}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25788116008451006
Fold 2 IBS: 0.20226079778720082
Fold 3 IBS: 0.2544783586806218
Fold 4 IBS: 0.23143342088904706
Fold 5 IBS: 0.21567691855898308
[I 2024-04-14 23:32:45,205] Trial 34 finished with value: 0.23234613120007258 and parameters: {'subsample': 0.5577914444927095, 'dropout_rate': 0.9877256275541959, 'n_estimators': 127, 'learning_rate': 0.016160179473353013}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24665787355022445
Fold 2 IBS: 0.23001468040084486
Fold 3 IBS: 0.228802523121071
Fold 4 IBS: 0.24061435934394168
Fold 5 IBS: 0.2271257607053576
[I 2024-04-14 23:32:45,315] Trial 35 finished with value: 0.2346430394242879 and parameters: {'subsample': 0.7803178043419461, 'dropout_rate': 0.43975685710717877, 'n_estimators': 13, 'learning_rate': 0.005826832206318818}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.36295049794153883
Fold 2 IBS: 0.27664373471149467
Fold 3 IBS: 0.3675445917607911
Fold 4 IBS: 0.3032504418743303
Fold 5 IBS: 0.311762833506537
[I 2024-04-14 23:32:48,478] Trial 36 finished with value: 0.3244304199589384 and parameters: {'subsample': 0.5171903924633928, 'dropout_rate': 0.2795306755316796, 'n_estimators': 421, 'learning_rate': 0.0238218995141648}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.3956248057488727
Fold 2 IBS: 0.3239854573821247
Fold 3 IBS: 0.38499901982444784
Fold 4 IBS: 0.31514930414846015
Fold 5 IBS: 0.3335159079818787
[I 2024-04-14 23:32:49,856] Trial 37 finished with value: 0.35065489901715685 and parameters: {'subsample': 0.43420796750396373, 'dropout_rate': 0.7621022900062648, 'n_estimators': 241, 'learning_rate': 0.059207327336158105}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25969526762239703
Fold 2 IBS: 0.20212138827340803
Fold 3 IBS: 0.25611019690719544
Fold 4 IBS: 0.23376225132374828

Fold 5 IBS: 0.21475575962300342
[I 2024-04-14 23:32:51,033] Trial 38 finished with value: 0.23328897274995045 and parameters: {'subsample': 0.605229739689187, 'dropout_rate': 0.13272164755980653, 'n_estimators': 176, 'learning_rate': 0.01283698591663533}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.29108106719697524
Fold 2 IBS: 0.21415810554809628
Fold 3 IBS: 0.2917820507930866
Fold 4 IBS: 0.2588982634047282
Fold 5 IBS: 0.24407574900323586
[I 2024-04-14 23:32:51,390] Trial 39 finished with value: 0.25999904718922445 and parameters: {'subsample': 0.6970162917669863, 'dropout_rate': 0.48841341315505027, 'n_estimators': 59, 'learning_rate': 0.06892741183938003}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2925659515921918
Fold 2 IBS: 0.2140746731129848
Fold 3 IBS: 0.2919432513336724
Fold 4 IBS: 0.257477121073266
Fold 5 IBS: 0.24657769529804316
[I 2024-04-14 23:32:51,903] Trial 40 finished with value: 0.2605277384820316 and parameters: {'subsample': 0.8054982836102402, 'dropout_rate': 0.876813469756125, 'n_estimators': 112, 'learning_rate': 0.035912260209657}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24534003818367572
Fold 2 IBS: 0.21351313222790674
Fold 3 IBS: 0.23284352524242438
Fold 4 IBS: 0.2304630885922339
Fold 5 IBS: 0.21224567728236968
[I 2024-04-14 23:32:52,209] Trial 41 finished with value: 0.22688109230572212 and parameters: {'subsample': 0.9180988510314624, 'dropout_rate': 0.9438179242085731, 'n_estimators': 49, 'learning_rate': 0.017446250508837573}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485006409680624
Fold 2 IBS: 0.21706394797525833
Fold 3 IBS: 0.23093672935586954
Fold 4 IBS: 0.23224267333240983
Fold 5 IBS: 0.21443505260308193
[I 2024-04-14 23:32:52,441] Trial 42 finished with value: 0.22790569347268522 and parameters: {'subsample': 0.9464169664396729, 'dropout_rate': 0.9430136432098365, 'n_estimators': 33, 'learning_rate': 0.020048086949614748}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2638458495823219
Fold 2 IBS: 0.2020440306627012
Fold 3 IBS: 0.2599892350953784
Fold 4 IBS: 0.2353149724721722
Fold 5 IBS: 0.2221900668187372
[I 2024-04-14 23:32:52,911] Trial 43 finished with value: 0.2366768309262622 and parameters: {'subsample': 0.8926693439285954, 'dropout_rate': 0.8370454250738812, 'n_estimators': 86, 'learning_rate': 0.027633234880330062}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2455964708749073
Fold 2 IBS: 0.22570478266765567
Fold 3 IBS: 0.228795022876604
Fold 4 IBS: 0.23752979609395375
Fold 5 IBS: 0.22236478482517102
[I 2024-04-14 23:32:53,335] Trial 44 finished with value: 0.23199817146765836 and parameters: {'subsample': 0.7574766140068628, 'dropout_rate': 0.9209040458467185, 'n_estimators': 56, 'learning_rate': 0.004536994661454437}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24519921983594833
Fold 2 IBS: 0.22330524452579645
Fold 3 IBS: 0.2290157433965299
Fold 4 IBS: 0.23588777848641265
Fold 5 IBS: 0.2204866110425217
[I 2024-04-14 23:32:53,599] Trial 45 finished with value: 0.2307789194574418 and parameters: {'subsample': 0.6254432766833774, 'dropout_rate': 0.7565492792792287, 'n_estimators': 25, 'learning_rate': 0.014308783844555807}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.34065073189493716
Fold 2 IBS: 0.2597363049038525
Fold 3 IBS: 0.3496713953679775
Fold 4 IBS: 0.2946768758327706
Fold 5 IBS: 0.29269474527583145
[I 2024-04-14 23:32:54,662] Trial 46 finished with value: 0.30748601065507386 and parameters: {'subsample': 0.5454269842024818, 'dropout_rate': 0.8816321250931852, 'n_estimators': 160, 'learning_rate': 0.048014785607437535}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.25039205968447736
Fold 2 IBS: 0.19881662927592997
Fold 3 IBS: 0.2539048960518954
Fold 4 IBS: 0.22477789659354785
Fold 5 IBS: 0.21334860039787545
[I 2024-04-14 23:32:55,194] Trial 47 finished with value: 0.2282480164007452 and parameters: {'subsample': 0.2385519301616531, 'dropout_rate': 0.9917631969393944, 'n_estimators': 81, 'learning_rate': 0.02513395893947125}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2556573719237732
Fold 2 IBS: 0.20234787848056301
Fold 3 IBS: 0.2522638016406119
Fold 4 IBS: 0.23093407281830788
Fold 5 IBS: 0.21250246234410652
[I 2024-04-14 23:32:56,625] Trial 48 finished with value: 0.23074111744147255 and parameters: {'subsample': 0.47852228408162223, 'dropout_rate': 0.19701471782839963, 'n_estimators': 193, 'learning_rate': 0.010411009503204737}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24675070321456416
Fold 2 IBS: 0.23043515587015717
Fold 3 IBS: 0.2288281703390381
Fold 4 IBS: 0.2408551079349057
Fold 5 IBS: 0.22755526151412517
[I 2024-04-14 23:32:56,789] Trial 49 finished with value: 0.23488487977455805 and parameters: {'subsample': 0.9361198918736817, 'dropout_rate': 0.6584903001856733, 'n_estimators': 2, 'learning_rate': 0.031855435969108184}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.26805889781388065
Fold 2 IBS: 0.20252886898813807
Fold 3 IBS: 0.26533134677822295
Fold 4 IBS: 0.23829437556390634
Fold 5 IBS: 0.22589258667890266
[I 2024-04-14 23:32:57,542] Trial 50 finished with value: 0.2400212151646101 and parameters: {'subsample': 0.7006430134270305, 'dropout_rate': 0.8318264141869088, 'n_estimators': 134, 'learning_rate': 0.019642786526356794}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24512963190106926
Fold 2 IBS: 0.2147274537502438
Fold 3 IBS: 0.2321986628737604
Fold 4 IBS: 0.23091267007941935
Fold 5 IBS: 0.21292902132889352
[I 2024-04-14 23:32:57,824] Trial 51 finished with value: 0.22717948798667725 and parameters: {'subsample': 0.7994296496769766, 'dropout_rate': 0.9513190706056927, 'n_estimators': 45, 'learning_rate': 0.017594085400454734}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24662205885932792
Fold 2 IBS: 0.22993687263943438
Fold 3 IBS: 0.22879053467216642
Fold 4 IBS: 0.24048347407202147
Fold 5 IBS: 0.22699896965015748
[I 2024-04-14 23:32:58,188] Trial 52 finished with value: 0.23456638197862154 and parameters: {'subsample': 0.9522184225974055, 'dropout_rate': 0.9540184058192569, 'n_estimators': 65, 'learning_rate': 0.00125014832336073}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24485579223129506
Fold 2 IBS: 0.21998745903015368
Fold 3 IBS: 0.22977573478865335
Fold 4 IBS: 0.23404920712862456
Fold 5 IBS: 0.21705606342896017
[I 2024-04-14 23:32:58,509] Trial 53 finished with value: 0.22914485132153736 and parameters: {'subsample': 0.843494929630295, 'dropout_rate': 0.915585413735216, 'n_estimators': 46, 'learning_rate': 0.011064278636511417}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2531442464481051
Fold 2 IBS: 0.20414594462184135
Fold 3 IBS: 0.2459059794082717
Fold 4 IBS: 0.22963377950406882
Fold 5 IBS: 0.21079567993043571
[I 2024-04-14 23:32:58,728] Trial 54 finished with value: 0.22872512598254455 and parameters: {'subsample': 0.8204677487117119, 'dropout_rate': 0.3571755626038756, 'n_estimators': 21, 'learning_rate': 0.08270475242185228}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.2524170789262838
Fold 2 IBS: 0.20420643525007415
Fold 3 IBS: 0.24534527368601658
Fold 4 IBS: 0.2294272521646032
Fold 5 IBS: 0.21300726025333291
[I 2024-04-14 23:32:59,261] Trial 55 finished with value: 0.22888066005606209 and parameters: {'subsample': 0.8887421810659816, 'dropout_rate': 0.8993071903534846, 'n_estimators': 99, 'learning_rate': 0.01667266938646207}. Best is trial 17 with value: 0.2265683943607694.
Fold 1 IBS: 0.24626134547224643
Fold 2 IBS: 0.21072141911440245
Fold 3 IBS: 0.23515116577403225
Fold 4 IBS: 0.22942525598464827
Fold 5 IBS: 0.21111562686038168
[I 2024-04-14 23:32:59,526] Trial 56 finished with value: 0.22653496264114223 and parameters: {'subsample': 0.7632340729628572, 'dropout_rate': 0.9968061240868161, 'n_estimators': 47, 'learning_rate': 0.0219993213211057}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.32236762054514384
Fold 2 IBS: 0.24369761993112318
Fold 3 IBS: 0.32961555540384646
Fold 4 IBS: 0.28411316345226234
Fold 5 IBS: 0.27450442032616973
[I 2024-04-14 23:33:01,088] Trial 57 finished with value: 0.29085967593170914 and parameters: {'subsample': 0.763955514973389, 'dropout_rate': 0.9964559295946985, 'n_estimators': 282, 'learning_rate': 0.02203371126489022}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2514876544143989
Fold 2 IBS: 0.20473165445913052
Fold 3 IBS: 0.2442786298594191

Fold 4 IBS: 0.2292932477615486
Fold 5 IBS: 0.2122783863810015
[I 2024-04-14 23:33:01,368] Trial 58 finished with value: 0.2284139145750997 and parameters: {'subsample': 0.8210665501105633, 'dropout_rate': 0.9557982366790785, 'n_estimators': 50, 'learning_rate': 0.03153701184110286}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2450009034050451
Fold 2 IBS: 0.21574021216390366
Fold 3 IBS: 0.2316126494096215
Fold 4 IBS: 0.2313085066143514
Fold 5 IBS: 0.2135215585555951
[I 2024-04-14 23:33:01,553] Trial 59 finished with value: 0.22743676602970336 and parameters: {'subsample': 0.7169412850975417, 'dropout_rate': 0.7863461136932807, 'n_estimators': 20, 'learning_rate': 0.03702429542217137}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.27643234236120234
Fold 2 IBS: 0.20531960631582807
Fold 3 IBS: 0.2756328535259464
Fold 4 IBS: 0.24566178547120296
Fold 5 IBS: 0.23379390635926353
[I 2024-04-14 23:33:02,108] Trial 60 finished with value: 0.24736809880668864 and parameters: {'subsample': 0.6580853749310097, 'dropout_rate': 0.8504207080106669, 'n_estimators': 120, 'learning_rate': 0.026233120654123206}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24511487846402005
Fold 2 IBS: 0.2227836793360944
Fold 3 IBS: 0.22915537398733413
Fold 4 IBS: 0.2355788750800659
Fold 5 IBS: 0.21936511210219634
[I 2024-04-14 23:33:02,470] Trial 61 finished with value: 0.23039958379394215 and parameters: {'subsample': 0.7368242492609791, 'dropout_rate': 0.9633166813429076, 'n_estimators': 74, 'learning_rate': 0.0051620199911569815}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.25492402733786423
Fold 2 IBS: 0.2031585290599715
Fold 3 IBS: 0.24895077307909572
Fold 4 IBS: 0.2303647335144685
Fold 5 IBS: 0.21487736782477726
[I 2024-04-14 23:33:02,927] Trial 62 finished with value: 0.23045508616323543 and parameters: {'subsample': 0.9008804237198612, 'dropout_rate': 0.8972785584562114, 'n_estimators': 99, 'learning_rate': 0.018480727132717638}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24531708021685963
Fold 2 IBS: 0.22395449249387253
Fold 3 IBS: 0.22892582490539293
Fold 4 IBS: 0.23652996695441353
Fold 5 IBS: 0.2211888183692411
[I 2024-04-14 23:33:03,159] Trial 63 finished with value: 0.23118323658795595 and parameters: {'subsample': 0.6297164279405434, 'dropout_rate': 0.5823907068184614, 'n_estimators': 34, 'learning_rate': 0.009594140607425444}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24543346554687298
Fold 2 IBS: 0.21302518909492982
Fold 3 IBS: 0.23348544240148608
Fold 4 IBS: 0.22993870744839895
Fold 5 IBS: 0.21193762927195595
[I 2024-04-14 23:33:03,489] Trial 64 finished with value: 0.22676408675272874 and parameters: {'subsample': 0.5245480196355067, 'dropout_rate': 0.9413786510901908, 'n_estimators': 62, 'learning_rate': 0.014230389833347484}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24427299434478603
Fold 2 IBS: 0.2145724066475789
Fold 3 IBS: 0.23244031403754764
Fold 4 IBS: 0.2308013778601708
Fold 5 IBS: 0.21301937769687632
[I 2024-04-14 23:33:03,872] Trial 65 finished with value: 0.22702129411739191 and parameters: {'subsample': 0.45473842457833824, 'dropout_rate': 0.9696337973251744, 'n_estimators': 60, 'learning_rate': 0.013175688908273541}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24414268593072253
Fold 2 IBS: 0.21442849246434953
Fold 3 IBS: 0.23260330769031967
Fold 4 IBS: 0.23070773208679712
Fold 5 IBS: 0.212827602266059
[I 2024-04-14 23:33:04,269] Trial 66 finished with value: 0.2269419640876496 and parameters: {'subsample': 0.4538390106754839, 'dropout_rate': 0.9973222357307537, 'n_estimators': 64, 'learning_rate': 0.012590689815234278}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.29808498998226407
Fold 2 IBS: 0.22021424313364715
Fold 3 IBS: 0.3008089717671045
Fold 4 IBS: 0.26320289852555373
Fold 5 IBS: 0.25043406288056935
[I 2024-04-14 23:33:06,113] Trial 67 finished with value: 0.2665490332578278 and parameters: {'subsample': 0.5164456222127641, 'dropout_rate': 0.9957101474211375, 'n_estimators': 321, 'learning_rate': 0.014042638169425688}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.36891251562644484
Fold 2 IBS: 0.28320463913092336
Fold 3 IBS: 0.3735215508072975
Fold 4 IBS: 0.30452010490955944
Fold 5 IBS: 0.3196121754758854
[I 2024-04-14 23:33:10,144] Trial 68 finished with value: 0.32995419719002206 and parameters: {'subsample': 0.396894830548818, 'dropout_rate': 0.8751386316641768, 'n_estimators': 496, 'learning_rate': 0.02170877428217187}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24694744262426244
Fold 2 IBS: 0.23112662775390544
Fold 3 IBS: 0.22888040570607412
Fold 4 IBS: 0.24129039277709646
Fold 5 IBS: 0.2284229264424595
[I 2024-04-14 23:33:10,315] Trial 69 finished with value: 0.23533355906075962 and parameters: {'subsample': 0.5321088311619213, 'dropout_rate': 0.6850428736307019, 'n_estimators': 11, 'learning_rate': 0.0033430171272597013}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.3789820127073879
Fold 2 IBS: 0.2881919135260274
Fold 3 IBS: 0.37987359081709904
Fold 4 IBS: 0.30582173340243274
Fold 5 IBS: 0.3303526100527719
[I 2024-04-14 23:33:13,992] Trial 70 finished with value: 0.3366443721011438 and parameters: {'subsample': 0.29831657136945555, 'dropout_rate': 0.7160048016307664, 'n_estimators': 408, 'learning_rate': 0.030184746562878957}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2442747298878039
Fold 2 IBS: 0.21394603308037777
Fold 3 IBS: 0.2329347454389621
Fold 4 IBS: 0.23037646611901139
Fold 5 IBS: 0.21249651991354515
[I 2024-04-14 23:33:14,330] Trial 71 finished with value: 0.22680569888794005 and parameters: {'subsample': 0.4656561384348985, 'dropout_rate': 0.9607291922995583, 'n_estimators': 67, 'learning_rate': 0.012470692352433808}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24446665909481854
Fold 2 IBS: 0.2202286409877386
Fold 3 IBS: 0.2298979855224926
Fold 4 IBS: 0.23386125106403746
Fold 5 IBS: 0.21736824836572086
[I 2024-04-14 23:33:14,632] Trial 72 finished with value: 0.2291645570069616 and parameters: {'subsample': 0.44632544286302367, 'dropout_rate': 0.940927063465276, 'n_estimators': 66, 'learning_rate': 0.007736153984692023}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24809645932076727
Fold 2 IBS: 0.20746362379997257
Fold 3 IBS: 0.23887206962421953
Fold 4 IBS: 0.2284825651773238
Fold 5 IBS: 0.2100698715233792
[I 2024-04-14 23:33:15,050] Trial 73 finished with value: 0.22659691788913244 and parameters: {'subsample': 0.47075831672242574, 'dropout_rate': 0.9113190760145863, 'n_estimators': 107, 'learning_rate': 0.011745458975142266}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2543888239593833
Fold 2 IBS: 0.20292319894393337
Fold 3 IBS: 0.24852527226160065
Fold 4 IBS: 0.22955225079581343
Fold 5 IBS: 0.21241475262132198
[I 2024-04-14 23:33:15,448] Trial 74 finished with value: 0.22956085971641055 and parameters: {'subsample': 0.48487077302079995, 'dropout_rate': 0.818126846171267, 'n_estimators': 107, 'learning_rate': 0.01659395710476026}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.2586670573078814
Fold 2 IBS: 0.20043803485847264
Fold 3 IBS: 0.2585285364856659
Fold 4 IBS: 0.23185266301823715
Fold 5 IBS: 0.21512351643127495
[I 2024-04-14 23:33:15,789] Trial 75 finished with value: 0.23292196162030643 and parameters: {'subsample': 0.3931286314918456, 'dropout_rate': 0.9058514756642456, 'n_estimators': 93, 'learning_rate': 0.024132850675330414}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24487192319121745
Fold 2 IBS: 0.21645877330178392
Fold 3 IBS: 0.23106107310931137
Fold 4 IBS: 0.2321278197949212
Fold 5 IBS: 0.21457551785343906
[I 2024-04-14 23:33:15,958] Trial 76 finished with value: 0.2278190214501346 and parameters: {'subsample': 0.5683268745859826, 'dropout_rate': 0.8653081987830238, 'n_estimators': 34, 'learning_rate': 0.020347121996093395}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24975605957417094
Fold 2 IBS: 0.20544669926019324
Fold 3 IBS: 0.24292589881032364

Fold 4 IBS: 0.2283240329592914
Fold 5 IBS: 0.21054396005104126
[I 2024-04-14 23:33:16,632] Trial 77 finished with value: 0.22739933013100408 and parameters: {'subsample': 0.5096986308003991, 'dropout_rate': 0.49881327862855496, 'n_estimators': 145, 'learning_rate': 0.010267257888313383}. Best is trial 56 with value: 0.22653496264114223.
Fold 1 IBS: 0.24684927097070503
Fold 2 IBS: 0.2094952280230178
Fold 3 IBS: 0.23652719105524916
Fold 4 IBS: 0.22913951054643386
Fold 5 IBS: 0.2106573202990221
[I 2024-04-14 23:33:16,949] Trial 78 finished with value: 0.2265337041788856 and parameters: {'subsample': 0.5939500427136554, 'dropout_rate': 0.7406477151463077, 'n_estimators': 73, 'learning_rate': 0.015420072941943445}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24502409439696052
Fold 2 IBS: 0.22205787317352343
Fold 3 IBS: 0.22926533447627775
Fold 4 IBS: 0.2352795597651623
Fold 5 IBS: 0.2188730593846164
[I 2024-04-14 23:33:17,282] Trial 79 finished with value: 0.23009998423930805 and parameters: {'subsample': 0.5862245141488869, 'dropout_rate': 0.7413305472330791, 'n_estimators': 79, 'learning_rate': 0.00518700542803859}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.2548529205408104
Fold 2 IBS: 0.2029551856530423
Fold 3 IBS: 0.2494742616554397
Fold 4 IBS: 0.23041757963367823
Fold 5 IBS: 0.21265412243334256
[I 2024-04-14 23:33:17,751] Trial 80 finished with value: 0.23007081398326265 and parameters: {'subsample': 0.5412030995339159, 'dropout_rate': 0.7943244209025906, 'n_estimators': 120, 'learning_rate': 0.015049190001982352}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24503928639713976
Fold 2 IBS: 0.22210439837147225
Fold 3 IBS: 0.22923064761200726
Fold 4 IBS: 0.23532466695341075
Fold 5 IBS: 0.2188890235672119
[I 2024-04-14 23:33:17,986] Trial 81 finished with value: 0.23011760458024838 and parameters: {'subsample': 0.6124074983469379, 'dropout_rate': 0.6341528845468055, 'n_estimators': 48, 'learning_rate': 0.008581896342583242}. Best is trial 78 with value: 0.2265337041788856.
Fold 1 IBS: 0.24566232614650538
Fold 2 IBS: 0.20763330396179233
Fold 3 IBS: 0.2399122667638913
Fold 4 IBS: 0.22729435575947432
Fold 5 IBS: 0.20971833255484604
[I 2024-04-14 23:33:18,335] Trial 82 finished with value: 0.22604411703730184 and parameters: {'subsample': 0.36882902998484507, 'dropout_rate': 0.9266770484936306, 'n_estimators': 72, 'learning_rate': 0.01836411354022466}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.24387668061602458
Fold 2 IBS: 0.21367297665454796
Fold 3 IBS: 0.2333362520374528
Fold 4 IBS: 0.22948421407755595
Fold 5 IBS: 0.21270096527180668
[I 2024-04-14 23:33:18,713] Trial 83 finished with value: 0.22661421773147755 and parameters: {'subsample': 0.3619635368676717, 'dropout_rate': 0.9281653685578871, 'n_estimators': 75, 'learning_rate': 0.01174447149382581}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.2481782165598782
Fold 2 IBS: 0.2032648830515002
Fold 3 IBS: 0.2505921898057478
Fold 4 IBS: 0.22803942510176736
Fold 5 IBS: 0.21128535620380667
[I 2024-04-14 23:33:19,066] Trial 84 finished with value: 0.22827201414454007 and parameters: {'subsample': 0.3276130954169086, 'dropout_rate': 0.9694546795228237, 'n_estimators': 84, 'learning_rate': 0.022169484737510906}. Best is trial 82 with value: 0.22604411703730184.
Fold 1 IBS: 0.2449916816071917
Fold 2 IBS: 0.21034889723149172
Fold 3 IBS: 0.23561656068011147
Fold 4 IBS: 0.2278223716435641
Fold 5 IBS: 0.21102078940314542
[I 2024-04-14 23:33:19,509] Trial 85 finished with value: 0.22596006011310088 and parameters: {'subsample': 0.363388210801912, 'dropout_rate': 0.8895677781947375, 'n_estimators': 93, 'learning_rate': 0.011252915568896725}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2507644683324895
Fold 2 IBS: 0.19921462815138938
Fold 3 IBS: 0.2542760719339917
Fold 4 IBS: 0.22500124256189552
Fold 5 IBS: 0.2130039704603047
[I 2024-04-14 23:33:19,978] Trial 86 finished with value: 0.22845207628801414 and parameters: {'subsample': 0.2377998071866918, 'dropout_rate': 0.9263524121710748, 'n_estimators': 107, 'learning_rate': 0.01902085002480073}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24461520451936894
Fold 2 IBS: 0.21162187155184128
Fold 3 IBS: 0.2344490116850452
Fold 4 IBS: 0.22917043508852472
Fold 5 IBS: 0.21178897460870122
[I 2024-04-14 23:33:20,581] Trial 87 finished with value: 0.22632909949069627 and parameters: {'subsample': 0.35810969899809325, 'dropout_rate': 0.8886867033584094, 'n_estimators': 134, 'learning_rate': 0.007190805934355407}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24456370610129832
Fold 2 IBS: 0.22128022630882604
Fold 3 IBS: 0.22947409303221045
Fold 4 IBS: 0.23463118790461507
Fold 5 IBS: 0.2191508748909942
[I 2024-04-14 23:33:21,288] Trial 88 finished with value: 0.2298200176475888 and parameters: {'subsample': 0.3554257183364478, 'dropout_rate': 0.8515802063127001, 'n_estimators': 151, 'learning_rate': 0.002966804106888144}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2775193161210976
Fold 2 IBS: 0.2056495855781246
Fold 3 IBS: 0.28613237088303234
Fold 4 IBS: 0.24447960031747357
Fold 5 IBS: 0.23382248801015568
[I 2024-04-14 23:33:21,934] Trial 89 finished with value: 0.24952067218197677 and parameters: {'subsample': 0.2975632154761778, 'dropout_rate': 0.8979603248959219, 'n_estimators': 137, 'learning_rate': 0.026327304724599293}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24489792409125763
Fold 2 IBS: 0.2147507134735931
Fold 3 IBS: 0.23214478243102468
Fold 4 IBS: 0.2311366433597866
Fold 5 IBS: 0.21331168885551222
[I 2024-04-14 23:33:22,374] Trial 90 finished with value: 0.22724835044223485 and parameters: {'subsample': 0.4239438985312938, 'dropout_rate': 0.8842980981030877, 'n_estimators': 94, 'learning_rate': 0.008199816001785099}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24443912868099016
Fold 2 IBS: 0.2106555205421554
Fold 3 IBS: 0.2361002830373223
Fold 4 IBS: 0.22815140478159898
Fold 5 IBS: 0.21090216410324303
[I 2024-04-14 23:33:22,720] Trial 91 finished with value: 0.226049700229062 and parameters: {'subsample': 0.36316393582436224, 'dropout_rate': 0.9330356356373378, 'n_estimators': 74, 'learning_rate': 0.014627227900695133}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24696395568562218
Fold 2 IBS: 0.206328757542603
Fold 3 IBS: 0.24098516387669733
Fold 4 IBS: 0.22738668862012074
Fold 5 IBS: 0.2096198352018724
[I 2024-04-14 23:33:23,367] Trial 92 finished with value: 0.22625688018538312 and parameters: {'subsample': 0.373278308068316, 'dropout_rate': 0.8205446675130532, 'n_estimators': 127, 'learning_rate': 0.010840707181494103}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2445959002519018
Fold 2 IBS: 0.21367655385448994
Fold 3 IBS: 0.23288855680962822
Fold 4 IBS: 0.23008083622513512
Fold 5 IBS: 0.21285389160286478
[I 2024-04-14 23:33:23,916] Trial 93 finished with value: 0.22681914774880396 and parameters: {'subsample': 0.4052623501935374, 'dropout_rate': 0.8224708293111835, 'n_estimators': 122, 'learning_rate': 0.006828423866425095}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.26112728548129654
Fold 2 IBS: 0.20039367088884036
Fold 3 IBS: 0.267173994295559
Fold 4 IBS: 0.23064925221212776
Fold 5 IBS: 0.21639436758841524
[I 2024-04-14 23:33:24,889] Trial 94 finished with value: 0.23514771409324778 and parameters: {'subsample': 0.2685207405457639, 'dropout_rate': 0.5306326676271426, 'n_estimators': 159, 'learning_rate': 0.016919236533565633}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2458959493820953
Fold 2 IBS: 0.20854810474644417
Fold 3 IBS: 0.23772658465187374
Fold 4 IBS: 0.22767957442334677
Fold 5 IBS: 0.21018857248815617
[I 2024-04-14 23:33:25,465] Trial 95 finished with value: 0.22600775713838323 and parameters: {'subsample': 0.37798247189331685, 'dropout_rate': 0.8572208063796695, 'n_estimators': 112, 'learning_rate': 0.01063058308878333}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.2471425193657016
Fold 2 IBS: 0.20576111765918625
Fold 3 IBS: 0.2415748835282002

Fold 4 IBS: 0.22741639083301954
Fold 5 IBS: 0.20957521984090532
[I 2024-04-14 23:33:26,189] Trial 96 finished with value: 0.2262940262454026 and parameters: {'subsample': 0.34523349906195283, 'dropout_rate': 0.7739280807288145, 'n_estimators': 132, 'learning_rate': 0.010648288131411126}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24385115968166024
Fold 2 IBS: 0.21643646571599923
Fold 3 IBS: 0.23116557489710682
Fold 4 IBS: 0.23167317839356094
Fold 5 IBS: 0.21516282794158326
[I 2024-04-14 23:33:27,248] Trial 97 finished with value: 0.22765784132598207 and parameters: {'subsample': 0.37469859653908655, 'dropout_rate': 0.8528934112321543, 'n_estimators': 187, 'learning_rate': 0.003684889317176295}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24621689559308768
Fold 2 IBS: 0.2055572040394727
Fold 3 IBS: 0.24230333094691225
Fold 4 IBS: 0.22648768747110257
Fold 5 IBS: 0.20952956681329585
[I 2024-04-14 23:33:28,561] Trial 98 finished with value: 0.22601893697277423 and parameters: {'subsample': 0.340063793125768, 'dropout_rate': 0.7630617995157165, 'n_estimators': 226, 'learning_rate': 0.006438550621538491}. Best is trial 85 with value: 0.22596006011310088.
Fold 1 IBS: 0.24105858388157023
Fold 2 IBS: 0.20817303425836378
Fold 3 IBS: 0.23679287394758858
Fold 4 IBS: 0.22332675419769993
Fold 5 IBS: 0.211518092772339
[I 2024-04-14 23:33:29,846] Trial 99 finished with value: 0.2241738678115123 and parameters: {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}. Best is trial 99 with value: 0.2241738678115123.


* Best trial for IBS:
 FrozenTrial(number=99, state=TrialState.COMPLETE, values=[0.2241738678115123], datetime_start=datetime.datetime(2024, 4, 14, 23, 33, 28, 568195), datetime_complete=datetime.datetime(2024, 4, 14, 23, 33, 29, 845843), params={'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}, user_attrs={}, system_attrs={}, intermediate_values={}, distributions={'subsample': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'dropout_rate': FloatDistribution(high=1.0, log=False, low=0.1, step=None), 'n_estimators': IntDistribution(high=500, log=False, low=1, step=1), 'learning_rate': FloatDistribution(high=0.1, log=False, low=0.001, step=None)}, trial_id=99, value=None)


* Best hyperparameters for IBS:
 {'subsample': 0.17778434918103095, 'dropout_rate': 0.7782160113329367, 'n_estimators': 212, 'learning_rate': 0.005308151321564225}


* Best Score for IBS:
 0.2241738678115123

In [185]:
train_cindex['ComponentwiseGradientBoosting'] = np.round(study_cindex.best_value, 3)
train_ibs['ComponentwiseGradientBoosting'] = np.round(study_ibs.best_value, 3)

In [186]:
print("train_cindex: ", np.round(study_cindex.best_value, 3))
print("train_ibs: ", np.round(study_ibs.best_value, 3))

train_cindex:  0.65
train_ibs:  0.224

#### Test

In [187]:
# y into array 
lists = [] 
for i, j in zip(y['event_DFS'], y['DFS']): 
    lists.append((i, j))

y = np.array(lists, dtype=[('status', bool), ('time', np.int32)])

In [188]:
# A function for building the best model with the best parameters 
def create_best_model(model_class, best_params):
    best_params["random_state"]=123
    return model_class(**best_params)

# Set the best model 
best_model_cindex = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_cindex.best_params)

# Train the best model for C-index on the whole dataset
best_model_cindex.fit(X_new_std, y)

# Evaluate the best model for C-index on MAASTRO dataset
c_index = best_model_cindex.score(MAASTRO_new_std, y_MAASTRO)
c_index = np.round(c_index, 3)
print("C-index score:", c_index)

# Set the best model 
best_model_ibs = create_best_model(ComponentwiseGradientBoostingSurvivalAnalysis, study_ibs.best_params)

# Train the best model for IBS on the whole dataset
best_model_ibs.fit(X_new_std, y)

# Evaluate the best model for IBS on MAASTRO dataset
lower, upper = np.percentile(y_MAASTRO["time"], [10, 90])
times = np.arange(lower, upper)
surv_prob = np.row_stack([fn(times) for fn in best_model_ibs.predict_survival_function(MAASTRO_new_std)])
ibs = integrated_brier_score(y_MAASTRO, y_MAASTRO, surv_prob, times)
ibs = np.round(ibs, 3)
print("IBS:", ibs)

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.2525866290623745,
                                              learning_rate=0.0801524070565027,
                                              n_estimators=446,
                                              random_state=123,
                                              subsample=0.10110319978064844)

C-index score: 0.532

ComponentwiseGradientBoostingSurvivalAnalysis(dropout_rate=0.7782160113329367,
                                              learning_rate=0.005308151321564225,
                                              n_estimators=212,
                                              random_state=123,
                                              subsample=0.17778434918103095)

IBS: 0.233

In [189]:
# Saving the values to the dictionary 
test_cindex['ComponentwiseGradientBoosting'] = c_index
test_ibs['ComponentwiseGradientBoosting'] = ibs

# Results

In [190]:
df_train_cindex = pd.DataFrame(train_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_train_cindex['rank'] = df_train_cindex['C-index'].rank(ascending=False)
df_train_cindex

                               C-index  rank
Randomsurvivalforest             0.795   1.0
ExtraSurvivalTrees               0.794   2.0
GradientBoosting                 0.738   3.0
CoxPH                            0.659   4.5
CoxElastic                       0.659   4.5
CoxLasso                         0.657   6.0
ComponentwiseGradientBoosting    0.650   7.0
CoxRidge                         0.633   8.0

In [191]:
df_train_ibs = pd.DataFrame(train_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_train_ibs['rank'] = df_train_ibs['IBS'].rank(ascending=True)
df_train_ibs

                                 IBS  rank
Randomsurvivalforest           0.206   1.0
ExtraSurvivalTrees             0.207   2.0
CoxElastic                     0.222   3.0
CoxLasso                       0.223   4.5
GradientBoosting               0.223   4.5
CoxPH                          0.224   6.5
ComponentwiseGradientBoosting  0.224   6.5
CoxRidge                       0.236   8.0

In [192]:
df_test_cindex = pd.DataFrame(test_cindex, index=['C-index']).transpose().sort_values(by='C-index', ascending=False)
df_test_cindex['rank'] = df_test_cindex['C-index'].rank(ascending=False)
df_test_cindex

                               C-index  rank
CoxRidge                         0.543   1.0
ComponentwiseGradientBoosting    0.532   2.0
GradientBoosting                 0.514   3.0
Randomsurvivalforest             0.509   4.0
ExtraSurvivalTrees               0.506   5.0
CoxPH                            0.499   6.0
CoxLasso                         0.498   7.0
CoxElastic                       0.497   8.0

In [193]:
df_test_ibs = pd.DataFrame(test_ibs, index=['IBS']).transpose().sort_values(by='IBS', ascending=True)
df_test_ibs['rank'] = df_test_ibs['IBS'].rank(ascending=True)
df_test_ibs

                                 IBS  rank
CoxRidge                       0.229   1.0
GradientBoosting               0.231   2.0
ComponentwiseGradientBoosting  0.233   3.0
Randomsurvivalforest           0.250   4.0
ExtraSurvivalTrees             0.257   5.0
CoxPH                          0.288   7.0
CoxLasso                       0.288   7.0
CoxElastic                     0.288   7.0

In [194]:
# Renaming the column "index" to "model" 
df_train_cindex = df_train_cindex.reset_index().rename(columns={"index": "model"})
df_train_ibs = df_train_ibs.reset_index().rename(columns={"index": "model"})
df_test_cindex = df_test_cindex.reset_index().rename(columns={"index": "model"})
df_test_ibs = df_test_ibs.reset_index().rename(columns={"index": "model"})

# Save the files 
dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = 'path_to_your_folder/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']


dfs = [df_train_cindex, df_train_ibs, df_test_cindex, df_test_ibs]  # List of your DataFrames
file_path = '/Users/minjeongcheon/Desktop/results_thesis/d2/dfs/robust/plsr/'  # Folder path where you want to save the files

# List of corresponding file names
file_names = ['train_cindex.csv', 'train_ibs.csv', 'test_cindex.csv', 'test_ibs.csv']

# Modify the file names to match the desired format
modified_file_names = ['d2_dfs_robust_plsr_' + file_name for file_name in file_names]

# Loop through each DataFrame and save them with corresponding modified file names
for df, modified_file_name in zip(dfs, modified_file_names):
    file_path_name = file_path + modified_file_name  # Construct the full file path
    df.to_csv(file_path_name, index=False)  # Save the DataFrame to CSV file

In [195]:
from datetime import date
today = date.today()
print("Date: ", today)

Date:  2024-04-14